### ISSUE TITLE
[Feature Request] Add AniDB indexer support

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#1]
Currently SR uses thetvdb or tvrage as indexer for animes(just like it does for normal shows).
I'd like to see the option(or the default) to use AniDB as indexer for anime.

The current indexers work terrible with anime, for example FairyTail S2 ep1 (if you continue numbering where S1 stopped, episode 176), is defined as S05E01 on thetvdb and tvrage.
This is just one example, as about every anime that consists out of more than 1 season are messed up like this.

Adding this will also add the functionality to display anime's in their Japanese name rather than their (IMHO ugly) Englishified name.

I understand adding AniDB is very difficult and requires a lot time, but IMHO it is worth it and I'd love to see it being added in the future.

**Comment by pct00** [comment]
+1

**Comment by dirkr07** [comment]
Hope somebody picks this one up soon. Really looking forward to a way to properly download/catalog my anime!

**Comment by fernandog** [comment]
@abeloin there's already anidb support, isn't?

**Comment by CtrlAltDefeat94** [comment]
To track what anime's you've downloaded? Yes. As an indexer? No, it is not.

**Comment by abeloin** [comment]
@fernandog Not as an indexer

**Comment by MrsAngelD** [comment]
Commenting to subscribe to this thread

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
