### ISSUE TITLE
Synology Package

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#10]
<a href="https://github.com/Diaoul"><img src="https://avatars.githubusercontent.com/u/319220?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Diaoul](https://github.com/Diaoul)**
_Saturday Nov 22, 2014 at 17:13 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/935 (20 comment(s))_

----

I think it would make more sense to add a standalone package at SynoCommunity rather than relying on sickbeard-custom.

Is the project ready for that? If that's the case I'd need a few screenshots and a logo (256x256px) @ diaoulael@gmail.com

**Comment by maxcore** [comment]
+1

**Comment by markheloking** [comment]
Whenever I have time on my hands I might still be interested in doing this. Only problem: I don't have a syno to test/play around with, and the stability of both the master and dev branch aren't all that (yet). Let's hope the latter will get better when @echel0n gets around.

**Comment by maxcore** [comment]
I can test for you :)

**Comment by neoatomic** [comment]
Here is a Synology SPK for Sickrage. 

http://cytec.us/spk/download/sickrage_noarch_20150103-1.spk

This is not the official Sickrage, but the Cytec fork, however this SPK could be used as a blueprint for our own package.

**Comment by fernandog** [comment]
@neoatomic what we need to do to have our own package?

**Comment by neoatomic** [comment]
@fernandog If you rename the .spk to .zip you can look inside the package.
To me it looks relatively easy to compile. As it downloads SR directly from github you probably only need to change the github url.?

If this SPK than can be added to the SR forum and on Synocommunity (largest Synology repository) it would open up Sickrage to a larger audience of Synology users.

**Comment by maxcore** [comment]
the installation working great!
git://github.com/SiCKRAGETV/SickRage.git
branch: master :)

thx!!!

**Comment by markheloking** [comment]
Can we publish it on Synocommunity?

**Comment by maxcore** [comment]
+1

**Comment by markheloking** [comment]
@maxcore since you seem to have a syno, are you up for it?

**Comment by Diaoul** [comment]
Publishing to SynoCommunity requires the code to be available at [spksrc](https://github.com/SynoCommunity/spksrc). Make a PR, we'll merge and publish.

**Comment by maxcore** [comment]
@markheloking  yep working good on my 1512+

**Comment by maxcore** [comment]
@Diaoul i dont know how to do that ...

@Cytec you can Pullrequest your spksrc to the  https://github.com/SynoCommunity/spksrc ?

**Comment by cytec** [comment]
done: https://github.com/SynoCommunity/spksrc/pull/1618

**Comment by fernandog** [comment]
@Diaoul @maxcore
 @cytec has a fork of sickrage with modifications. Not original sickrage.

**Comment by cytec** [comment]
@fernandog i changed the default URL for this PR to SiCKRAGETV's SickRage ;)

**Comment by fernandog** [comment]
@cytec Thanks!

**Comment by maxcore** [comment]
@cytec thanks!!!!!! :)

**Comment by neoatomic** [comment]
Today the Synology SPK for SickRage was added to Synocummunity repository. 

Thanks to all who made this possible.
