### ISSUE TITLE
[Feature Request] Add Strike torrent provider

### ISSUE THREAD

**Issue by Amnacog** [SiCKRAGETV/sickrage-issues#1000]
I recently discovered Strike wich is a powerfull and speedy search engine for torrents and it comes with a great api (json).
Hope it can be added soon as possible,

Thx in advance.

WWW: https://getstrike.net/
API: https://getstrike.net/api/

Yeah (#1000) issue

**Comment by Codeusa** [comment]
Strike owner here, if you require a special endpoint or changes to the existing API for smooth integration, I have no problem accommodating you in someway like I have other services.

**Comment by neoatomic** [comment]
@Amnacog We have A LOT of feature requests and we simple dont have the manpower to get it all coded up.
So i need to ask some practical questions. What does this search engine add over TBP, KAZ or RarBG.? What are the benefits for the SickRage users.?

@Codeusa Thank you for you offer to help, really appreciate that.
If we decide to add Strike we will get in touch with you to get it smoothly implemented.

**Comment by Codeusa** [comment]
Hey @neoatomic I can answer your question for you

Strike utilizes DHT AND public trackers, this allows it to index millions of torrents on the fly at request; further more it uses an AI on the back end to determine better results and learns from querys as they are given. 

That along with the API to get instant information on info-hashes makes it pretty unique.

**Comment by Amnacog** [comment]
@neoatomic if you do not have enough "manpower", I can implement the provider myself, I'm a brogrammer too, let me know..

**Comment by fernandog** [comment]
@Amnacog feel free to PR to develop

You can see all providers code in providers directory

https://github.com/SiCKRAGETV/SickRage/tree/develop/sickbeard/providers

check if you can use one of then as a base code

**Comment by Codeusa** [comment]
@Amnacog I've updated the API, it should be more helpful for you introducing a service provider here

**Comment by Amnacog** [comment]
@Codeusa Thx, I'm taking my time to make a proper code but I'll ask my merge request in the start of the next week.

**Comment by neoatomic** [comment]
Provider was added.
