### ISSUE TITLE
[Feature Request] Add Spanish to Subtitulos.es scrapper

### ISSUE THREAD

**Issue by emzero** [SiCKRAGETV/sickrage-issues#1002]
Subtitulos.es provides both Spanish (Spain) and Spanish (Latin American) subtitles. And since SR has a subtitulos.es scrapper it would be nice if we could have a way to download only latin american ones.

**Comment by alkalinelito** [comment]
I second this too

**Comment by neoatomic** [comment]
@emzero 
Glad to say that this week we updated subliminal to newest version 0.8.
This should bring a substantial improvement over the older version we where using.

However to allow easier updating in the future we decided to not modify the original subliminal code anymore.
In short that means that we wont be add any new subtitle providers our-selfs.
So if you still would like this provider added, than please post the request directly for the subliminal developers at. : https://github.com/Diaoul/subliminal
If its added in subliminal it will automatically be added to SickRage to. :)
