### ISSUE TITLE
Improve Manual Search - ask user what to do

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#1005]
- If that episode has previous download/snatch then ask user to:
    - re-download same quality (mark failed if enabled). Don't search for better quality OR
    - Force better quality check (don't download same quality).  If nothing better found, keep "Downloaded/Snatched" status.

* If no previous download/snatch: manual search won't ask anything and will do the search

@abeloin

**Comment by abeloin** [comment]
@fernandog @TagForce 
Part 1 of 2 DisplayShow: https://github.com/abeloin/SickRage/commit/4f4b57a8b8893ca7cfe631882a9be0c37e918eff?w=1
Part 2 of 2 ComingEpisode: Available later

**Comment by fernandog** [comment]
@abeloin 

```
pi@raspbmc:~/SickRage$ patch -p1 < 4f4*.patch
patching file gui/slick/css/dark.css
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file gui/slick/css/dark.css.rej
patching file gui/slick/interfaces/default/displayShow.tmpl
patching file gui/slick/js/ajaxEpSearch.js
patching file sickbeard/providers/btn.py
patching file sickbeard/providers/ezrss.py
patching file sickbeard/providers/generic.py
patching file sickbeard/providers/iptorrents.py
patching file sickbeard/providers/nyaatorrents.py
patching file sickbeard/providers/tokyotoshokan.py
patching file sickbeard/search.py
patching file sickbeard/search_queue.py
patching file sickbeard/tv.py
Hunk #2 FAILED at 1230.
1 out of 2 hunks FAILED -- saving rejects to file sickbeard/tv.py.rej
patching file sickbeard/tvcache.py
patching file sickbeard/webserve.py

```

**Comment by abeloin** [comment]
@fernandog https://github.com/SiCKRAGETV/SickRage/compare/develop...abeloin:patch-manual_search?w=1

**Comment by abeloin** [comment]
Screenshot:
![Imgur](http://i.imgur.com/XWkqH71.png)
![Imgur](http://i.imgur.com/LmM2xAK.png)
