### ISSUE TITLE
Hotlinking directly to proxied pages is not permitted

### ISSUE THREAD

**Issue by simonwicks** [SiCKRAGETV/sickrage-issues#1007]
SR Version:	BRANCH: (master) / COMMIT: (cc4896e96a27dda5cc9ed198209aa514bf68a4eb) 
Python Version:	2.7.8 (default, Dec 12 2014, 22:38:36) [GCC 4.3.2]
Using a Synology NAS

Hey, 

So as of Monday (I think) RBG hasn't been returning any results for my shows. 
I haven't changed any other settings from what I had before and had been working since I noticed RBG was a provider.
I upgraded to the latest of SR on Monday morning, and again sometime in the week, but it seems to have stopped finding results completely for me. 

I've done a manual search for the show 'Archer' as a test case, my log below showing no results found and a link to one of the results it *should* pick up on is [here](http://rarbg.com/torrent/wc12uli)

```
2015-03-20 20:15:33 INFO     SEARCHQUEUE-MANUAL-110381 :: Unable to find a download for: [Archer (2009) - 6x11 - Achub Y Morfilod]
2015-03-20 20:13:35 INFO     SEARCHQUEUE-MANUAL-110381 :: [Rarbg] :: Performing episode search for Archer (2009)
2015-03-20 20:12:35 INFO     SEARCHQUEUE-MANUAL-110381 :: Building internal name cache for Archer (2009)
2015-03-20 20:12:35 INFO     SEARCHQUEUE-MANUAL-110381 :: No scene exceptions update needed
2015-03-20 20:12:35 INFO     SEARCHQUEUE-MANUAL-110381 :: Beginning manual search for: [Archer (2009) - 6x11 - Achub Y Morfilod]
```

Here's a link to my Archer show page - http://awesomescreenshot.com/0ed4okrc09
Here's a link to my provider options for RBG - http://awesomescreenshot.com/00c4okri4d

I've tried using different Proxy URLs from the settings, but had no luck. 
I can get to the proxy URL's on their own just fine hideme.nl for example (thought they might have been blocked for some reason).

I enabled KAT as a test to make sure the app was working overall, and it found results. So seems to be a problem with RBG and the latest couple of updates, at least for me. 

Anyone else experiencing this? 

If there's anything else I can do to offer more information, let me know. 

Thanks ,

Simon

**Comment by fernandog** [comment]
@simonwicks here is working. last download yersterday

are you sure this episode is available in rarbg in the quality you want?

**Comment by simonwicks** [comment]
@fernandog Hey, it is indeed. 

I linked to my show page which shows it's set as HD720p, and I linked to a webdl torrent being available on RBG that it didn't pick up on. I'm guessing there's some not webdl one's it missed but could have picked as well. 

It's not only Archer though, it's all my shows all week.
I've been manually downloading them since.

Think i should try exporting all my settings and reinstalling it? Have never done that before.

**Comment by fernandog** [comment]
Use log search and search for rarbg

Post results

**Comment by simonwicks** [comment]
@fernandog 

Sure thing. 

Only goes back as far back as today it seems, and I have since manually downloaded Archer and all other shows from this week, so I don't think it's actively looking for anything at the moment. 

I can add a test show though, something I don't usually watch that's aired recently. 

Log here - http://pastebin.com/jbbr86gV

**Comment by fernandog** [comment]
@simonwicks

I tried to open the url from log and got this:

"Hotlinking directly to proxied pages is not permitted."

@abeloin we should change this proxy

**Comment by simonwicks** [comment]
Oh. Well at least you figured it out! 

I tried swapping to getprivate, and proxite and get a hotlinking errors as well. 
Interproxy says 'The requested resource could not be loaded. libcurl returned the error:
connect() timed out!' 

So seems they've all cracked down!

**Comment by fernandog** [comment]
for what read, proxies are disabling hotlinks because of they ads/page are going down in traffic

http://proxy.org/forum/glype-proxy-discussion/8634-users-byepassing-home-page.html

**Comment by abeloin** [comment]
@fernandog It's failing because it ask for a confirmation because the url is ssl and the the proxy isn't:
https://gist.github.com/abeloin/b86cac8b27526451f43f

**Comment by abeloin** [comment]
@simonwicks Can you try this PR? https://github.com/SiCKRAGETV/SickRage/issues/1616

**Comment by simonwicks** [comment]
@abeloin 

I'm not really sure how to pull individual files into my build, or even just replace them. 

If you're able to walk me through it I can give it a go though.

**Comment by abeloin** [comment]
Better wait until it is merged then

**Comment by simonwicks** [comment]
No worries.

**Comment by simonwicks** [comment]
@fernandog 

Hey, 

I updated this morning to the new build, and this is still occurring for me I'm afraid, failing to grab anything when there are definitely matching results. 

Do you want me to post anymore logs or anything else?

**Comment by fernandog** [comment]
@simonwicks full logs please

**Comment by simonwicks** [comment]
@fernandog 

RBG is blocked in the UK so not directly. I usually use TOR if I need to get to it manually.

What shall I set the logging level to to grab the logs you want?
Alternatively I can let you log in direct if it's easier?

**Comment by fernandog** [comment]
@simonwicks did you enabled proxy in provider settings?

**Comment by simonwicks** [comment]
@fernandog Indeed, it's always been ticked as all the sites are usually blocked here.

**Comment by simonwicks** [comment]
@fernandog 

I just tried to manually put hide.nl in my browser on a computer on the same network as my NAS and paste a search from the logs (https://rarbg.com/torrents.php?search=Bobs.Burgers.S05E16.&category=18&page=1 - for example) 
and I get this error on the hideme.nl page after hitting Go.

*The requested resource could not be loaded. libcurl returned the error:
connect() timed out!*

Tried TOR to go direct to the RBG URL and it's fine, loads and shows results it should be picking up on.

Tried a regular day to day site through hideme.nl and it loads fine. 

Could my ISP somehow be blocking me even though I'm trying to go through that you think?

**Comment by fernandog** [comment]
@simonwicks Try proxite instead of hideme.nl

@rarbg is hideme.nl proxy banned/blocked?

**Comment by rarbg** [comment]
@fernandog 
As i said many times before already - there is spam/bot protection.
hideme.nl is probably affected by that and its banned

**Comment by simonwicks** [comment]
@fernandog 

Changed to that and manually hit search on the show again. It span for ages but eventually came up with the notification saying nothing found. 

Tried it through the browser and get the same error as on hideme 

*The requested resource could not be loaded. libcurl returned the error:
connect() timed out!*

Log of that search here - http://pastebin.com/n06m4Cch 

Just seen RBG's reply, looks like I'm out of luck until the API fix is in place.

**Comment by fernandog** [comment]
@rarbg I remember. Just want to make sure is banned.

We are still waiting @corpo to update the code. 
Sorry

**Comment by simonwicks** [comment]
@fernandog No worries, these things happen :)
