### ISSUE TITLE
UN/PW no longer working

### ISSUE THREAD

**Issue by cnmsales** [SiCKRAGETV/sickrage-issues#1008]
When entering SickRage the UN/PW option is no longer working.Tried to log in and it wont accept my info. Verified info in config.ini file and tried again. Still UN/PW error. Cleared UN/PW from config. I can now access  SR. Set UN/PW back up and now its not working again. Just to note, I am running Windows 10 and this issue began after the update to the new build #10041. It was working properly in previous build. SR is still running and downloading shows. I just cant manage it w/ a PW set. Not sure of where to get SB Version info. Posting this here as requested by Devs on the forum.

Update: Python Version:	2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
SB Version TVRage (master)
Browser is latest version of Chrome
Encrypt Password is enabled.

I also just realize that its not connecting to Utorrent any more. I redid the UN and PW in SB and Utorrent to make sure they match but SB is giving the following: Error: Invalid uTorrent Username or Password, check your config!

The only thing in the logs and errors file currently is "2015-03-21 11:23:11 SEARCHQUEUE-BACKLOG-281470 :: uTorrent: Authentication Failed
2015-03-20 23:23:11 SEARCHQUEUE-BACKLOG-281470 :: uTorrent: Authentication Failed
2015-03-20 23:23:07 FINDPROPERS :: Exception generated in thread FINDPROPERS: Proper instance has no attribute 'airdate'"

Update2: Just disabled encryption on PW and restarted. Still getting the UN/PW errors on connecting to Utorrent and the other.

Pastebin with Debug: http://pastebin.com/8mf6Sp1t

**Comment by abeloin** [comment]
Please follow the instructions on [this page](https://github.com/SiCKRAGETV/sickrage-issues) to provide all the informations requires when submitting an issue.

Are you encrypting passwords?

**Comment by fernandog** [comment]
maybe this IE build has some issues.
it is a alpha/beta build. Isnt?
does it work with a release version of IE?

**Comment by cnmsales** [comment]
Where do I locate branch and commit hash? I tried looking for all this info last night before I submitted but wasn't seeing it anywhere.

**Comment by fernandog** [comment]
Help&info menu

**Comment by abeloin** [comment]
@cnmsales 
You are running to instance of sickrage on the same port?
```
`2015-03-21 15:30:34 ERROR    MAIN :: Unable to start web server, is something else running on port 8081?
2015-03-21 15:30:28 INFO     MAIN :: Starting Sick Beard on http://0.0.0.0:8081/
```

**Comment by cnmsales** [comment]
Nothing is running on 8081 that I am aware of. Everything was working correctly and everything is still working properly with the exception that I cannot PW protect SB.

**Comment by abeloin** [comment]
@cnmsales Can you try this in the python interpreter on the same machine running sickrage:
```
import uuid
uuid.getnode()
```
Press CTRL+C to exit, then try again. Do you get a different value?

**Comment by cnmsales** [comment]
Abeloin, I would love to. How do I open the interpreter?

**Comment by abeloin** [comment]
* Open command line(cmd.exe).
* Type: `c:\python27\python.exe` (If you installed python elsewhere you need to substitute)

**Comment by cnmsales** [comment]
Both times I get 10503546354L, and 10503546354L

**Comment by abeloin** [comment]
Ok so not the uuid bug.

Can you open the task manager, and make sure you don't have any python process. Check the config.ini file and make sure the password is the one you want(web_username and web_password). Start sickrage and try the user/pass. If not working check the log for:
```
2015-03-21 15:30:34 ERROR    MAIN :: Unable to start web server, is something else running on port 8081?
2015-03-21 15:30:28 INFO     MAIN :: Starting Sick Beard on http://0.0.0.0:8081/
```

**Comment by cnmsales** [comment]
Ok so this is what it looks like before I kill everything. http://imgur.com/w3YvGNY As you can see there are three python items running for some reason. Really unsure why that would be or how to fix it. After killing all three and closing sickrage and restarting it I only have one Python process running. I am able to get into SR fine. Restarted and now the three python processes are back but I am still able to get into python even with the UN/PW so not really sure what happened but its now working as expected so I guess this can be closed out though im not sure why it started working again.

**Comment by abeloin** [comment]
@cnmsales Use the taskmanager details tab next time it will give a better information. Looking at your screenshot those other python process are from plex.

My guess is that your were running 2 instance of Sickrage, hence the `Unable to start web server`.
