### ISSUE TITLE
Support update to offline kodi MySQL db.

### ISSUE THREAD

**Issue by Mycah** [SiCKRAGETV/sickrage-issues#1010]
I would love to see the ability to update the Kodi library, when Kodi isn't on and has an externally hosted MySQL database.

I have multiple machines that all hit one MySQL database on my fileserver, and it appears that SickRage can update the Kodi DB, but it interfaces through Kodi to do it.  My HTPC's aren't always on, and this is unreliable.  I'd love to have the ability to configure SickRage to do this without needing to rely upon a live kodi client when new episodes are added/removed.

**Comment by abeloin** [comment]
Editing the SQL database directly is unreliable, it's better to use the provided api. If we don't then we have to track every DB version change which is a pain in the **** and we have to do catch up game when a new version is out. 

Why don't you set Kodi to do a full update when it is started, this way your new episode will be available after the scan.

**Comment by Mycah** [comment]
That's too bad.  My htpc clients are not really all that beefy, they offload all the video to video specific hardware and library updates I would think would be easier to manage offline since it's just mysql.  If it isn't possible, oh well.  Thanks anyway.

**Comment by fernandog** [comment]
@Mycah you only have to add a custom keymap to remote.xml in XBMC/KODI that updates video library
OR enable the scan library at startup in XBMC/Kodi. It's the best solution as the HTPC's aren't always on

**Comment by DanielNagy** [comment]
i +1 this, as i also have kodi media players that are always off sharing a mysql database
However, given that kodi changes DB schema / Version so often, it would be silly to integrate this support into sickrage. http://kodi.wiki/view/Database_versions 

A better solution would be to create some sort of middle ware kodi API service/daemon, with code pulled directly/dependent on the original kodi code.

If there's something out there. Let me know :D

**Comment by WebSpider** [comment]
There would be no changes required from SR, as we already support kodi, and kodi api's would be used in a headless case as well.
