### ISSUE TITLE
Encrypted password are machine specific

### ISSUE THREAD

**Issue by abeloin** [SiCKRAGETV/sickrage-issues#1012]
```
SR Version: 	BRANCH: (production-stage) / COMMIT: (0d137d62c2b8a5166c47ecc6c58643cadc76bea6)
Python Version:	2.7.5 (default, Nov 3 2014, 14:26:24) [GCC 4.8.3 20140911 (Red Hat 4.8.3-7)]
```
Encrypting password in config.ini use uuid.getnode() as a random number which makes it machine specific. Also if it's unable to get a hardware address, it will generate a random 48 bits number which would cause issue to user encrypting password(Eg:Unable to login). Finally, if the config.ini is moved to another machine, all passwords will be invalid.

I think we should generate a random number like the web_secret instead instead of using uuid.getnode()? 

@fernandog @TagForce Any comments?

Ref: https://docs.python.org/2/library/uuid.html#uuid.getnode

**Comment by fernandog** [comment]
@abeloin agree

**Comment by TagForce** [comment]
@abeloin Yes, seems like a safer option.

**Comment by abeloin** [comment]
Proposed PR # 1666
@fernandog @TagForce Comments?

**Comment by fernandog** [comment]
@abeloin go ahead
