### ISSUE TITLE
Torrent is empty after update

### ISSUE THREAD

**Issue by DetectiveStern** [SiCKRAGETV/sickrage-issues#1013]
BRANCH: (master)
COMMIT: (3b11079a5a658fdc8fe35de1ecadd572e06dc872) 
OS: Ubuntu Server 12.04 
Python Version: 2.7.3

I was 2 updates behind based off of the SickRage webui, after the updates all searches result in "Torrent file content is empty". The server is in a different region when looking at the time stamps but I updated roughly 1 hour ago. I believe the commit version I am using now was released tonight and want to have a different person's eyes on this if it is a real issue. 

http://pastebin.com/Jn3J7NBv

**Comment by fernandog** [comment]
@DetectiveStern full logs please!

**Comment by abeloin** [comment]
A hotfix will be available shortly

**Comment by DetectiveStern** [comment]
Getting a new link setup with the full logs, it will be just a second....I have to create an account due to it's size.

**Comment by DetectiveStern** [comment]
@fernandog @abeloin 
Getting a new link with the full logs, it will be just a second....I have to create an account due to it's size.

**Comment by abeloin** [comment]
@DetectiveStern Please update to the latest version. It should fix the issue

**Comment by DetectiveStern** [comment]
@abeloin I just updated and it's working again. Thank you!
