### ISSUE TITLE
Couldn't find a download for MasterChef Canada - 2x05 - Slice of Life

### ISSUE THREAD

**Issue by Trevara** [SiCKRAGETV/sickrage-issues#1014]
Hi, first post here, hoping someone could assist.
SickRage is working wonders, but it's failing to find certain episodes on KAT as I believe it's omitting the "S" for season, and "E" for episode.
For Example, it's been unable to pull MasterChef Canada on KAT automatically.
Attempting to search is manually brings the error "Couldn't find a download for MasterChef Canada - 2x05 - Slice of Life"
The episode is clearly available with 190 seeds. 
If was searching for "MasterChef Canada - S2E05", SickRage would have found it. 

Any way to change this search criteria?

**Comment by abeloin** [comment]
@Trevara To better help you, please consult the following on how to submit an issue: https://github.com/SiCKRAGETV/sickrage-issues

**Comment by fernandog** [comment]
@Trevara did you set mim seeders or min leechers or trusted/verified only? If so check the torrent

**Comment by fernandog** [comment]
@Trevara reply or we will close
