### ISSUE TITLE
Feature Request - Add column widget selector to "displayShow"

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#1015]
Add column widget selector to "displayShow" like the one added Home

This eliminates the need for specific options in settings and simply allows you to select which columns you want to see on the fly.

Need to remove this setting from UI /config/general/:
- Display Filesizes - display filesizes for downloaded episodes on show page

https://sickrage.tv/forums/forum/main-category/feature-requests/866-filenames-on-show-pages-taking-up-a-lot-of-real-estate

no rush on this
@TagForce @abeloin

**Comment by TagForce** [comment]
@fernandog Yeah, maybe add the widget-columnselector across the board for all pages that have a table. Keeps the design the same all over the place.
Also adding it to DisplayShow would allow us to add the filename column again. People are asking for it (a couple of them anyway).

**Comment by saitoh183** [comment]
+1 here :)

**Comment by fernandog** [comment]
@Thraxis if you want to try this one =)

**Comment by Thraxis** [comment]
@fernandog Heh..  I did start looking at it the other night but it was really late and wasn't focusing that great so gave up to look at it another day.

**Comment by Thraxis** [comment]
PR will be going up shortly

![untitled](https://cloud.githubusercontent.com/assets/1131905/7100550/045accda-dfde-11e4-923c-793e9b1381dd.png)

**Comment by Thraxis** [comment]
PR superseded by https://github.com/SiCKRAGETV/SickRage/pull/1754

**Comment by fernandog** [comment]
working!
