### ISSUE TITLE
Home search field doesn't work

### ISSUE THREAD

**Issue by gborri** [SiCKRAGETV/sickrage-issues#1016]
Every time i'm searching for a show it doesn't find anything

**Comment by TagForce** [comment]
@gborri 
https://github.com/SiCKRAGETV/SickRage/blob/develop/gui/slick/interfaces/default/home.tmpl#L251

Can you change data-column="1" to data-column="2" and see if it works again?

@abeloin If we allow turning columns on and off, this needs to be changed from hardcoded to derived from the shown columns.

**Comment by saitoh183** [comment]
@TagForce 

I can confirm that the change works

**Comment by abeloin** [comment]
@TagForce I forgot to change that one when I added prev ep. There's no need to change it from hard coded to derived as tablesorter does the conversion internally. I will push a fix.

**Comment by abeloin** [comment]
@gborri @saitoh183 @TagForce PR merged in develop
