### ISSUE TITLE
Warn user about backlog search range less than oldest wanted episode airdate

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#1018]
@abeloin @TagForce @neoatomic 
What is better:
- Note in config_search.tmpl next to "Backlog Search days" warning user he has a wanted episode outside backlog search days and suggesting to increase the value to XX
- Show a warning in LOG?

**Comment by abeloin** [comment]
What happen if add a show from 2000 and set it to wanted by default(because I don't understand how backlog works), it will ask me to put the backlog to 5475 days?

**Comment by fernandog** [comment]
will warn you that you have an WANTED episode outside backlog search range

**Comment by abeloin** [comment]
We should change SearchBacklog.py#L88 because this is printed in the log when backlog is started: 
`BACKLOG :: Running limited backlog on missed episodes 7 day(s) and older only`

**Comment by fernandog** [comment]
@abeloin will fix in thi FR PR. I should read config setting

**Comment by fernandog** [comment]
![2](https://cloud.githubusercontent.com/assets/2620870/6789384/98f6efc2-d17e-11e4-8481-bcee8df8c1cb.png)

@abeloin suggestions?

**Comment by fernandog** [comment]
@abeloin message is correct:
```
        if not which_shows and not curDate - self._lastBacklog >= self.cycleTime:
	            logger.log(u"Running limited backlog on missed episodes " + str(sickbeard.BACKLOG_DAYS) + " day(s) and older only")
```

shouldn't be "earlier only" ?

**Comment by abeloin** [comment]
Yes
Also you should be careful on the numbers of days you go back as it will slow down the system. It fetch all episode before date: `SELECT status, season, episode FROM tv_episodes WHERE showid = ? AND season > 0 and airdate > ?`

**Comment by fernandog** [comment]
@abeloin is there anything that I can do to improve the query?

**Comment by abeloin** [comment]
Have a look in _get_segments() in searchBacklog.py#L137

**Comment by abeloin** [comment]
Wanted is one of the status it's searching:
 if (curStatus in (common.DOWNLOADED, common.SNATCHED, common.SNATCHED_PROPER,
                              common.SNATCHED_BEST) and curQuality < highestBestQuality) or curStatus == common.WANTED:

**Comment by abeloin** [comment]
String from sickbeard: logger.log(u"Running limited backlog on recently missed episodes only")
