### ISSUE TITLE
HoundDawgs torrent search provider not working

### ISSUE THREAD

**Issue by mattail** [SiCKRAGETV/sickrage-issues#1019]
It looks like the torrent search provider HoundDawgs has stopped working.
I'm using sickrage installed on a synology NAS version
SR Version:  BRANCH: (master) / COMMIT: (4b40fceda883f76174672ab4e1423f3713e037ca)  
When looking at logs I see this repeating line:
*The Data returned from HoundDawgs do not contains any torrent*

Logs:
http://hastebin.com/esexasocej.pas

**Comment by abeloin** [comment]
Please use pastebin or like for long log.

**Comment by abeloin** [comment]
Can you try changing [line 170 of sickbeard/providers/hounddawgs.py](https://github.com/SiCKRAGETV/SickRage/blob/7a7ff70fdb5faf714523d84d12531f0bba8e3bc7/sickbeard/providers/hounddawgs.py#L170):
from:
`searchURL = self.urls['search'] % (urllib.quote(search_string), self.categories)`
to
`searchURL = self.urls['search'] % (search_string, self.categories)`

Stop Sickrage first, edit, then start sickrage

**Comment by mattail** [comment]
Thanks for quick reply!
Can I edit .py files on synology via SSH or how is it done?

**Comment by neoatomic** [comment]
@mattail use WinSCP. with connection mode scp

**Comment by fernandog** [comment]
@mattail when you open this URL, do you get results?

https://hounddawgs.org/torrents.php?type=&userid=&searchstr=&searchimdb=&searchtags=&order_by=s3&order_way=desc&&filter_cat[85]=1&filter_cat[58]=1&filter_cat[57]=1&filter_cat[74]=1&filter_cat[92]=1&filter_cat[93]=1

**Comment by abeloin** [comment]
@fernandog See the definition of urlib.quote: https://docs.python.org/2/library/urllib.html#urllib.quote
It will encode any character except A-Z a-z 0-9 _.-

The only commit since February 20th that could have broken it is https://github.com/SiCKRAGETV/SickRage/commit/7a7ff70fdb5faf714523d84d12531f0bba8e3bc7#diff-36cd43ccb433b18422e4bdd4390b6c0b as the other one is for a space in a log string. This is why I asked hin to revert the change to see if it is related

**Comment by fernandog** [comment]
@abeloin but I only added to urllib.quote(search_string). not the URL itself. 

Also the all searchstr= in the URL are empty

**Comment by abeloin** [comment]
@fernandog I not saying that the issue is the commit, I want to cover the all the bases while troubleshooting his issue.

**Comment by mattail** [comment]
I'm at work.Will change line 170 in hounddawgs.py when I get home and report result here.

**Comment by fernandog** [comment]
@mattail can you open one of the URLs in the log, save the html page and send to us? Maybe provider changed something in the page

**Comment by mattail** [comment]
Sure. Should I send you this page before I make any change to the hounddawgs.py file?

**Comment by fernandog** [comment]
@mattail you can send now (without changing file)

**Comment by mattail** [comment]
Here you go.
https://www.dropbox.com/s/9nxsjgjm8b3dw1z/Browse_Torrents_HoundDawgs.html?dl=0

**Comment by mattail** [comment]
So I changed the hounddawgs.py file as recommended but issue still remains.
To test I added a new show which was released on this provider but sickrage is unable to download it.
If I copy+paste this link in line 2 from log then I'm redirected to the episode so I don't understand why sickrage is unable to detect/download it when it actually is found.

http://pastebin.com/wQFFA8Qw#

**Comment by fernandog** [comment]
@mattail when you open this URL, do you get results?

https://hounddawgs.org/torrents.php?type=&userid=&searchstr=&searchimdb=&searchtags=&order_by=s3&order_way=desc&&filter_cat[85]=1&filter_cat[58]=1&filter_cat[57]=1&filter_cat[74]=1&filter_cat[92]=1&filter_cat[93]=1

**Comment by mattail** [comment]
Yes I do.

**Comment by fernandog** [comment]
@mattail can you post a screenshot of this provider settings?

**Comment by abeloin** [comment]
Let's see the data content:

Can you try changing [line 186 of sickbeard/providers/hounddawgs.py](https://github.com/SiCKRAGETV/SickRage/blob/7a7ff70fdb5faf714523d84d12531f0bba8e3bc7/sickbeard/providers/hounddawgs.py#L186):
from:
`logger.log(u"The Data returned from " + self.name + " do not contains any torrent",`
to
`logger.log("The Data: " + data,`

Stop Sickrage first, edit, then start sickrage and post the log

**Comment by mattail** [comment]
@fernandog 

![udklip](https://cloud.githubusercontent.com/assets/11618853/6810094/e24189c2-d25e-11e4-9010-bdeb9fb0f718.PNG)

**Comment by mattail** [comment]
@abeloin I cannot restart sickrage after changing that line.

**Comment by fernandog** [comment]
@mattail what is the error ?

did you keep the indentation?

**Comment by mattail** [comment]
@abeloin Changed back to original line, now sickrage is able to start. Looks like line 187 is "connected".

**Comment by fernandog** [comment]
@mattail the result should looks like this

```
                        if not result_table:
                            logger.log("The Data: " + str(data),
                                       logger.DEBUG)
                            continue
```

**Comment by mattail** [comment]
@fernandog Ok, now sickrage is able to restart. What you posted is not quite the same as suggested in first place :-) 
Will post log shortly.

**Comment by fernandog** [comment]
@mattail force a search in that provider only

**Comment by mattail** [comment]
@fernandog  That's what I did, all other providers are off.
Here are Info and debug log:

http://pastebin.com/n3Y8Wauc

**Comment by mattail** [comment]
@fernandog I mean I perform a manual search for that particular episode if that's what you mean by "force a search "

**Comment by fernandog** [comment]
yes. manual search an episode you know it's available

**Comment by mattail** [comment]
ok that's what I did.

**Comment by abeloin** [comment]
@mattail That log did you take it from the log file directly(sickrage.log) or from the log page in the webui?

As the returned data is just one line: `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">`

**Comment by mattail** [comment]
@abeloin From the log page in the webui. Was not aware of any other logs.
I think this is what you're looking for, taken from sickrage.log:
http://pastebin.com/pAHZqrhG

**Comment by abeloin** [comment]
Thanks

**Comment by abeloin** [comment]
Ok it's asking for user/pass no cookies

**Comment by mattail** [comment]
@abeloin Yes I noticed the message saying that cookies was not activated, but request comes from a synology NAS not a browser. 
I can try to re-enter user+pass and see what's happening.

**Comment by abeloin** [comment]
Can you try using this version of houndDawgs.py file: https://gist.github.com/abeloin/2e66c8c6e4b2d3349c61

Stop sickrage, replace the file content by the one from the gist, save, restart sickrage

**Comment by mattail** [comment]
The html code from log looks like it's the providers login page
https://hounddawgs.org/login.php
I re-entered username+password in sickrage for that provider but nothing changed. Logs are the same after manual search.

**Comment by abeloin** [comment]
@mattail You tried with the new version and you get the same error: The Data returned from HoundDawgs do not contains any torrent ?

**Comment by mattail** [comment]
@abeloin Not yet.

**Comment by mattail** [comment]
It worked! Episode is now snatched and downloading!
What did you do??

**Comment by abeloin** [comment]
Added a code to detect when asking for cookie: `re.search('Dine cookies er ikke aktiveret.', response.text)` and get the base url before posting: `self.session.get(self.urls['base_url'], timeout=30, verify=False)`

**Comment by mattail** [comment]
@abeloin I cannot thank you enough. You've made a lot of people happy today.

**Comment by mattail** [comment]
So will this fix be included in next release?

**Comment by abeloin** [comment]
@mattail Yes

**Comment by abeloin** [comment]
Merge in master.

@mattail Enable git reset in the github config in sickrage, and update.
