### ISSUE TITLE
Parsing WEB-DL filenames

### ISSUE THREAD

**Issue by Alexwijn** [SiCKRAGETV/sickrage-issues#1020]
I do not have a lot of info to give you since he parsed it more than a day ago, and the logs are only from today. But you have to take my word for it:

The filename Continuum.S03E01.Minute.by.Minute.720p.WEB-DL.AAC2.0.H264.mkv will get parsed to Unknown. I think this is because he can't locate the uploader name.

I searched up the season pack for the TV Show and saw a exact match in file size in all episodes. So thats why I think he parsed it wrong.

**Other info:**
Python Version: 2.7.3 (default, Mar 18 2014, 05:13:23) 
[GCC 4.6.3]
Operating System: Linux-3.18.7+-armv6l-with-debian-7.8
Branch: master
Commit: SiCKRAGETV/SickRage@4b40fce

**Comment by fernandog** [comment]
@Alexwijn missing group

https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/name_parser/regexes.py#L65

this is torrent has a bad naming

**Comment by Alexwijn** [comment]
Will the regex be updated to support the above filename?

**Comment by fernandog** [comment]
As I said: this is torrent has a bad naming

**Comment by abeloin** [comment]
@fernandog To confirm, I will do some regex test when I'll be back tonight.

**Comment by Alexwijn** [comment]
@fernandog That does not mean it should not be fixed. A lot of torrents are using this name. 

@abeloin Ok, thanks!

**Comment by fernandog** [comment]
@abeloin ok. But we shouldnt add new regex because uploader did a mistake. otherwise we would have to accept s01e1 for example (missing lead zero to episode) and others errors

**Comment by Alexwijn** [comment]
More coverage is better, I think. Uploaders are creating torrents for the public and not specifically for Sickrage.  And yes s01e1 is an exception as it is impossible to correct, it can be episode 1 or 10.

**Comment by abeloin** [comment]
@Alexwijn Correctly detected(Tested with both 720p and 1080p version)
```
SEARCHQUEUE-MANUAL-258171 :: [Rarbg] :: Ignoring result Continuum.S03E01.Minute.by.Minute.1080p.WEB-DL.AAC2.0.H264 because we don't want an episode that is 1080p WEB-DL
SEARCHQUEUE-MANUAL-258171 :: [Rarbg] :: Parsed Continuum.S03E01.Minute.by.Minute.1080p.WEB-DL.AAC2.0.H264 into Continuum - S3E1 [ANIME VER: -1] [ABD: False] [ANIME: False] [whichReg: ['standard']]
SEARCHQUEUE-MANUAL-258171 :: [Rarbg] :: Converted parsed result Continuum.S03E01.Minute.by.Minute.1080p.WEB-DL.AAC2.0.H264 into Continuum - S3E1 [ANIME VER: -1] [ABD: False] [ANIME: False] [whichReg: ['standard']]

Processing Continuum.S03E01.Minute.by.Minute.1080p.WEB-DL.AAC2.0.H264.mkv (None)
Retrieving episode object for 3x1
Snatch history had a quality in it, using that: 1080p WEB-DL
SB snatched this episode and it is not processed before
Is ep a priority download: True
There is no existing file so there's no worries about replacing it
This download is marked a priority download so I'm going to replace an existing file if I find one
Destination folder for this episode: Continuum\Season 03
Copying file from Continuum.S03E01.Minute.by.Minute.1080p.WEB-DL.AAC2.0.H264.mkv to Continuum\Season 03\Continuum - S03E01 - Minute By Minute.mkv
Processing succeeded for Continuum.S03E01.Minute.by.Minute.1080p.WEB-DL.AAC2.0.H264.mkv
```

**Comment by Alexwijn** [comment]
Very weird. All I can say is that I use a different naming. Mine is using the naming where the name and group is specified in the filename at the final destination. Maybe that helps...?

**Comment by abeloin** [comment]
@Alexwijn Ok now I understand, you are talking about renaming your file with a name pattern. I thought you meant the parsing converted the release to unknown(Provider parsing a release before snatching).

As @fernandog said, there is no release group in the filename so you can't expect SR to magically find a group name out of thin air. Web-dl are release by non scene release group, so often they don't follow release name convention hence your issue.

@fernandog Sorry, I was very slow to understand that one!
