### ISSUE TITLE
PROPERs downloaded more than once

### ISSUE THREAD

**Issue by brimur** [SiCKRAGETV/sickrage-issues#1021]
I have noticed that, unlike normal episodes, when there is a PROPER found that it will download it more than once depending on how many providers have it, KAT, TPB etc. So if a PROPER is found on both KAT and TPB both finds are downloaded.

**Comment by fernandog** [comment]
follow guidelines:
https://github.com/SiCKRAGETV/sickrage-issues

**Comment by brimur** [comment]
I just noticed that I am 112 commits behind. I will close this issue for now and open again if the issue still exists in the latest version.
