### ISSUE TITLE
DVD Order, does it work ?

### ISSUE THREAD

**Issue by Zzaap** [SiCKRAGETV/sickrage-issues#1022]
If it does I'm not sure how to use this feature.
I tried to click it on and off on different series (Firefly and Kaamelott) with no apparent effect. 
On thetvdb.com the episodes are set correctly for both aired and DVD order.

For exemple on Firefly the 1st episode in DVD order is Serenity
![aired](https://cloud.githubusercontent.com/assets/5058994/6803156/0c738a70-d236-11e4-9b3f-dcd183ab75b1.png)
![dvd](https://cloud.githubusercontent.com/assets/5058994/6803161/14371056-d236-11e4-89cc-821ad2196a3d.png)

BRANCH: (master) / COMMIT: (4b40fceda883f76174672ab4e1423f3713e037ca)
Python Version:	2.7.9 (default, Mar 23 2015, 00:29:05) [GCC 4.6.4]

**Comment by abeloin** [comment]
@Zzaap You need to do a "Force full update" in the top right corner

**Comment by Zzaap** [comment]
Weird, i was sure i had done that. But I've done it now and it works for the database, however it doesn't rename the actual files. When i click on 'preview rename' it propose to rename all files, but instead of changing the episode numbers it will change the episode names.
![untitled](https://cloud.githubusercontent.com/assets/5058994/6813542/5fb295d8-d276-11e4-9242-eda9d102e58e.png)

**Comment by abeloin** [comment]
@Zzaap You will have to do it manually as SR doesn't support it.

From what I can see in the code DVD support rudimentary.
