### ISSUE TITLE
API: Unable to retrieve information from indexer

### ISSUE THREAD

**Issue by timkatgert** [SiCKRAGETV/sickrage-issues#1024]
When I'm trying to add an serie/show to SickRage I'm getting "Unable to retrieve information from indexer" returned?

What could be the cause of this? Do i have forgot to set something in the settings or is this because the wrong information is passed into the url parameters?

**Comment by fernandog** [comment]
@timkatgert follow guidelines:
https://github.com/SiCKRAGETV/sickrage-issues/

**Comment by timkatgert** [comment]
Branch:
master

Your operating system and python version:
Synology disk station manager (linux distro), aswell on windows 7.

**Comment by fernandog** [comment]
@timkatgert still missing info

**Comment by timkatgert** [comment]
What you did & What happened
When I'm trying to add an serie/show to SickRage I'm getting "Unable to retrieve information from indexer" returned

What you expected
show should have been added

No errors log

**Comment by fernandog** [comment]
@timkatgert 

we still need logs!
which indexer?
full screen shot of  the pagw showing "Unable to retrieve information from indexer"
do you use proxy?

we can't do nothing unless you send information!

**Comment by fernandog** [comment]
@abeloin we need ASAP to commit the submit log. tired to asking info....users thing we have a crystal ball

**Comment by abeloin** [comment]
@fernandog Everything for yesterday, got it! :wink:

**Comment by fernandog** [comment]
@timkatgert reply or we will close it
