### ISSUE TITLE
Add Provider Strike

### ISSUE THREAD

**Issue by abeloin** [SiCKRAGETV/sickrage-issues#1028]
https://getstrike.net

API: https://getstrike.net/api/

**Comment by neoatomic** [comment]
@abeloin https://github.com/SiCKRAGETV/sickrage-issues/issues/1000

**Comment by myandroidiptvbox** [comment]
OK so this item is closed....Any reason?
The site is a great lightning fast adfree torrent search site that appears to do all the scraping. It has some API functionality but a specific search can be obtained by:
https://getstrike.net/torrents/?q={searchTerms}
If not, does anyone know a fork that does?
