### ISSUE TITLE
[Feature Request] Add Transmission post processing API

### ISSUE THREAD

**Issue by NjayNL** [SiCKRAGETV/sickrage-issues#1029]
Hi Team,

first off wonderfull program ! love it !

Can you let sickrage talk to tranmission to check if a torrent has finished downloading or is stalled and let it talk back to sickrage to or have it completed or mark it as failed download

couchpotato does the same when a movie has finished seeding

thx !

**Comment by NjayNL** [comment]
Any word on this team?

**Comment by WebSpider** [comment]
It's on the list of things to do in general: Start processing feedback from clients.

We first have two major milestones: Cleanup of provider code and incremental show updates.

So: Not this coming 2 weeks.

You are always free to help yourself to an outstanding issue by sending in a pullrequest off course :)

**Comment by NjayNL** [comment]
Thanks for the update no hurry ofcourse :)

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
