### ISSUE TITLE
Set deleted episodes to 'Archived'

### ISSUE THREAD

**Issue by KaiStarkk** [SiCKRAGETV/sickrage-issues#1032]
Can we have a setting, perhaps underneath 'Skip Remove Detection' which allows another status to be selected (instead of Ignored) when an episode is detected as having been removed. This way I can have it so that when I delete a show from my media player, SickRage will determine that it has been Archived (which makes more sense to me than ignored as a default anyway), removing what is currently one of the regular manual steps in show management.

**Comment by fernandog** [comment]
@TagForce will be implemented in near futuru or long future ? if not, will close

**Comment by TagForce** [comment]
Ignored episodes don't count towards episode counts (show or total) archived counts as 1 towards both.
That's the only difference between them. Yes, no problem with changing the status. Either way one will need to manually change it if they want to redownload. Don't even make it a setting, just change the status to Archived.

**Comment by fernandog** [comment]
@TagForce ok! will PR that

**Comment by fernandog** [comment]
@KaiStarkk 
can you please stop SR
edit the file /SickRage/sickbeard/tv.py, line 1090

change
curEp.status = IGNORED
to
curEp.status = ARCHIVED

keep indentation
save, test, report back if worked

**Comment by KaiStarkk** [comment]
Hey guys.

That works exactly as I'd hoped. Do I need to double check this one after updates by the way (incase it gets reset).

Figured it'd be a one line fix, just didn't know about sickbeard enough to find that line. Thank you for the virtually instant replies!

**Comment by fernandog** [comment]
@KaiStarkk double check please

**Comment by KaiStarkk** [comment]
Yeah that's what I mean, it worked perfectly.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1650
