### ISSUE TITLE
Branch detection appears to be incorrect

### ISSUE THREAD

**Issue by WoLpH** [SiCKRAGETV/sickrage-issues#1034]
The interface is telling me that I'm currently running a different branch which I'm not.

Results from the interface:
```
You're using the echel0n-develop branch. Please use 'master' unless specifically asked
```

Results from git:
```
# git branch
  ThePirateBay
  custom-qualities
  echel0n-develop
  WoLpH-develop
  WoLpH-master
* master
```

```
# git remote -v
WoLpH	https://github.com/WoLpH/SickBeard-TVRage.git (fetch)
WoLpH	https://github.com/WoLpH/SickBeard-TVRage.git (push)
origin	https://github.com/SiCKRAGETV/SickRage.git (fetch)
origin	https://github.com/SiCKRAGETV/SickRage.git (push)
```

Is Sickrage confused or is this result cached somewhere?
Just a fyi, my repo is clean (already git the clean, reset, etc...)

**Comment by fernandog** [comment]
@WoLpH 

```
git remote add upstream https://github.com/SiCKRAGETV/SickRage.git
git fetch upstream
git checkout master
git reset --hard upstream/master
git pull
```

**Comment by WoLpH** [comment]
As I said in the original post, I have a clean repo. That's not the issue here :)

**Comment by fernandog** [comment]
@WoLpH there is not echel0n-develop in nowhere in SR repo. You don't have it clean

**Comment by WoLpH** [comment]
Just because I have other branches doesn't mean my current checkout isn't clean, which other branches I have should have no influence over the current one.

Regardless, I've executed all of the commands you requested, no change. As I said, that is not the issue.

Let me repeat my question for clarity: **Is Sickrage confused or is this result cached somewhere?**

**Comment by TagForce** [comment]
Stop SR
Remove the branch from your config.ini:
branch = 
Restart SR.

**Comment by WoLpH** [comment]
Brilliant, that fixed it. Thanks @TagForce :)

**Comment by TagForce** [comment]
@fernandog Initially it gets the branch info from the config.ini...
If it's empty there it will default to master until an update is run, which is when it's updated by _find_installed_branch...
This is why I was reluctant to simply go by the BRANCH variable when setting the big red box... However, when you use the switch branch from SR, it will work. It's only when you checkout different branches from different repo's that it may get messed up.

Switching to the develop branch on this repo, and then changing to master from SR should work. Removing from config.ini is easier and also works.

**Comment by WoLpH** [comment]
Might be better to have that big box point to the setting, perhaps the switch repo button would work (just found it now).

**Comment by TagForce** [comment]
@WoLpH Nah, we just need to fix the branch checks...
