### ISSUE TITLE
Redirect loop at /home/

### ISSUE THREAD

**Issue by lussierj** [SiCKRAGETV/sickrage-issues#1037]
BRANCH: master
COMMIT: c28ca92c6d19ce1610a83ac08707529ad0796718
OS: Windows 8.1 (64bit)
Python Version: 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]

Every time I go to xxx.xxx.xxx.xxx:8081/home/ I get a redirect loop error. The rest of site else seems to be working. (i.e. xxx.xxx.xxx.xxx:8081/history/)
It just started happening a few day ago. I haven't really done anything before it happened that I recall. I may have done a manual post processing on some files the days before the error appeared but that's all I can remember.

My error log is filling up with this error over and over.

-------------------------------
```
2015-03-25 11:22:00 Thread-26 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 723, in index
    return t.respond()
  File "C:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_home_tmpl.py", line 1014, in respond
    _v = VFN(VFSL([locals()]+SL+[globals(), builtin],"calendar",True),"timegm",False)(VFN(VFSL([locals()]+SL+[globals(), builtin],"pdatetime",True),"timetuple",False)()) # u'$calendar.timegm($pdatetime.timetuple())' on line 607, col 39
  File "C:\SickRage\lib\dateutil\tz.py", line 114, in dst
    if self._isdst(dt):
  File "C:\SickRage\lib\dateutil\tz.py", line 152, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: (22, 'Invalid argument')
 ```
-------------------------------

Thanks for help you can give.

**Comment by fernandog** [comment]
@lussierj do you have webroot enabled?

**Comment by lussierj** [comment]
I think I have webroot enabled. How would I verify that?
the time on the computer is set properly to right timezone and current time.

**Comment by abeloin** [comment]
@fernandog This error is produced by a time that Python doesn't like.

**Comment by abeloin** [comment]
@lussierj Added a new show?

**Comment by lussierj** [comment]
Yes, it could have broke after adding a new show.

**Comment by fernandog** [comment]
@lussierj post the tv-show name - or even better, the link to it in thetvdb or tvrage(depending the indexer you choosed)

**Comment by lussierj** [comment]
The Night Shift
http://thetvdb.com/?tab=series&id=269640

**Comment by abeloin** [comment]
@lussierj Try going directly to the page: http://localhost:8081/home/displayShow?show=269640

**Comment by lussierj** [comment]
That page works.

**Comment by abeloin** [comment]
Can you check all your show via the mass edit page?

**Comment by lussierj** [comment]
I can check all shows via mass edit no problem. I just removed "The Night Shift" and restarted Sickrage The problem persists.

**Comment by fernandog** [comment]
@lussierj so it's another show

**Comment by abeloin** [comment]
Try replacing gui/slick/interfaces/default/home.tmpl with the one from the PR https://raw.githubusercontent.com/SiCKRAGETV/SickRage/cc20c8d52a3bbdb4ed56a89344a9e7124dc1a804/gui/slick/interfaces/default/home.tmpl

**Comment by lussierj** [comment]
That did it. Thanks!!!!!
