### ISSUE TITLE
Feature Request: Collapse passed seasons.

### ISSUE THREAD

**Issue by neoatomic** [SiCKRAGETV/sickrage-issues#1040]
Some of my shows have 900 episodes and loading the show page takes considerable longer than a show that has 20 episodes.

So i was wondering if we can add an option to collapse passed seasons.
That would hopefully speedup the loading time of the page.

**Comment by fernandog** [comment]
@neoatomic collapsing it's not necessary not loading. isn't? Don't know how this works in html

**Comment by gborri** [comment]
@neoatomic @fernandog has to be defined correctly the meaning of "passed season".

**Comment by abeloin** [comment]
@fernandog What he meant is either use paging or ajax to load only a portion of the data.

**Comment by Thraxis** [comment]
Just for curiosity sake... how would you define a season as "passed" All shows downloaded?  All shows Archived?  Anything older than x number of days?  A combination of days and status?

Currently the showDisplay page relies on having all the episodes as that is how it builds the season "tables"

**Comment by Thraxis** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1827

**Comment by fernandog** [comment]
Thanks! All that PR ate tested and fully working so safe to merge?

**Comment by neoatomic** [comment]
@Thraxis Awesome, Thank you! 
I have the show cops in my list with 900+ episodes. That show is running from 1989.?
Clearly no need to load all those previous years/seasons, as i only need to see the current year for new episodes.

(I see you have put that setting in the general config part.? Isn't it better to place that in the show edit part.? That way it gives more custom ability to the users. As they might only want to collapse it in one show.)

**Comment by Thraxis** [comment]
@neoatomix Unfortunately I don't think this will improve your load speed as it still gets the data it just hides it.  Placing it as a Per-Show (editShow) option would require database changes to store that setting with each show.  I could possibly get creative with a dict / json config option to allow per show.

Can also look into loading season data on demand

**Comment by fernandog** [comment]
@neoatomic @Thraxis no db changes for now! it's a global setting but you can "show/hide episodes" in UI. merged in develop. try it
