### ISSUE TITLE
Remove jwplayer feature. MKV not compatible with all browsers

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#1042]
Mkv files only work with Chrome
@abeloin

**Comment by gborri** [comment]
@fernandog do you think is possible not to remove but be available only on chrome?

**Comment by abeloin** [comment]
@gborri It's unmaintained, doesn't work well in Linux and the way it is currently implemented is a nightmare for your browser if you try to open a show with a lot of episode.

**Comment by gborri** [comment]
ok.
