### ISSUE TITLE
[Feature Request] Add partial show update, instead of only full update

### ISSUE THREAD

**Issue by cyberundertaker** [SiCKRAGETV/sickrage-issues#1045]
Sometimes updating shows takes too much time so is it possible to partially update show with just new episodes and new airdates?
For example:
NCIS has 12 seasons
When doing force full update it takes much more time than updating a show with just one season.

Is it possible to add the option if a show has more than one season then just update the last season with new episodes and airdates and without scanning the media files on HDD.

I think this would significantly speed up the update time for shows.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/510

**Comment by cyberundertaker** [comment]
@fernandog in theory, when you pause a show season and do a force full update, will SR completely ignore those paused seasons and just update the unpaused ones? 

What I would like to know is there any way to update shows with new airdates and episode names but without rescaning the media files?

**Comment by fernandog** [comment]
I just linked feature requests cause the are complement each other.

No. not possible. and we shouldnt do that because can break SR checks. Right @Tagforce? Or not?

**Comment by cyberundertaker** [comment]
@fernandog @TagForce or updating shows with new airdates and episode names but rescanning the media files only for last season...

**Comment by fernandog** [comment]
Showupdater dont take long time

use log filter in log page and filter by SHOWUPDATER. check timestamps.

If you have update on startup I recommend disable. It will be updare 3am everyday.

**Comment by cyberundertaker** [comment]
@fernandog It takes about 15 minutes for The Simpsons (i have all 26 seasons downloaded) with force full update
If there is an option to update airdates and names and only rescan media for the last season it would take maybe 2 minutes...

**Comment by fernandog** [comment]
Why would you a force update?
let SR update at 3am.

**Comment by cyberundertaker** [comment]
@fernandog I did a force update because the simpsons haven't been updated at all for the last 7 days...
my pc/SR is on 24/7 and it should auto update at 3am but sometimes it doesn't...

**Comment by fernandog** [comment]
Only simpsons or other shows too?

**Comment by cyberundertaker** [comment]
@fernandog other shows too... i wasn't at home for the last few days but SR was running, and when i checked it today i had to do force update on multiple shows to pull new episode names and airdates to be able to snatch and download them.

**Comment by fernandog** [comment]
use log filter in log page and filter by SHOWUPDATER (listbox). post results

**Comment by cyberundertaker** [comment]
@fernandog it's empty...
![log](https://cloud.githubusercontent.com/assets/11670746/6859968/b6ec16d4-d420-11e4-8f35-f2f2ee8beb2e.PNG)

**Comment by cyberundertaker** [comment]
@fernandog this is the status of simpsons before force update... so from around 25.01.2015 it didnt update... the episodes above were downloaded manually and then PostProcessed by SR.
![simp](https://cloud.githubusercontent.com/assets/11670746/6859989/40510bd2-d421-11e4-9bd8-01ff20a0086b.PNG)

**Comment by fernandog** [comment]
Check you Logs directory  tell me the oldest timestamp from oldest file

You can see Logs directory in page Help & Info

**Comment by cyberundertaker** [comment]
@fernandog
![logs](https://cloud.githubusercontent.com/assets/11670746/6860110/c407b992-d423-11e4-93ca-28fa3168be8a.PNG)

I just restored SR to the point before i did force updates...then i set the update to run at 2am (in 10min)...and increased max size and number of logs.

**Comment by fernandog** [comment]
Ok. Mine is working;

```
2015-03-26 03:48:59 INFO     SHOWUPDATER :: 
Completed full update on all shows
2015-03-26 03:48:57 INFO     SHOWUPDATER :: Trying to clean cache folder /home/pi/SickRage/cache
2015-03-26 03:48:57 INFO     SHOWUPDATER :: Doing full update on all shows
2015-03-25 03:07:27 INFO     SHOWUPDATER :: Completed full update on all shows
2015-03-25 03:07:25 INFO     SHOWUPDATER :: Trying to clean cache folder /home/pi/SickRage/cache
2015-03-25 03:07:25 INFO     SHOWUPDATER :: Doing full update on all shows
2015-03-24 03:50:25 INFO     SHOWUPDATER :: Completed full update on all shows
2015-03-24 03:50:22 INFO     SHOWUPDATER :: Trying to clean cache folder /home/pi/SickRage/cache
2015-03-24 03:50:22 INFO     SHOWUPDATER :: Doing full update on all shows
2015-03-24 03:47:59 INFO     SHOWUPDATER :: Completed full update on all shows
2015-03-24 03:47:53 INFO     SHOWUPDATER :: Trying to clean cache folder /home/pi/SickRage/cache
2015-03-24 03:47:53 INFO     SHOWUPDATER :: Doing full update on all shows
2015-03-23 03:40:41 INFO     SHOWUPDATER :: Completed full update on all shows
2015-03-23 03:40:38 INFO     SHOWUPDATER :: Trying to clean cache folder /home/pi/SickRage/cache
2015-03-23 03:40:38 INFO     SHOWUPDATER :: Doing full update on all shows
```

**Comment by cyberundertaker** [comment]
@fernandog it's past 2am here (2:15am) and still nothing in the log. timezone problem or maybe something else? i set 2 in when to update...

**Comment by fernandog** [comment]
@cyberundertaker did you restarted as requested by UI when changing update time?

**Comment by cyberundertaker** [comment]
@fernandog it's not requested by UI
When to update shows    2

with information such as next air dates, show ended, etc. Use 15 for 3pm, 4 for 4am etc. Anything over 23 or under 0 will be set to 0 (12am)

Will set to 3 and restart

**Comment by fernandog** [comment]
@TagForce can you test if your SHOWUPDATER is working? Its the second user that report it's not running

**Comment by fernandog** [comment]
@cyberundertaker did it work after restart?

**Comment by cyberundertaker** [comment]
@fernandog it looks like it's working, but actually it's not...

This is the log:
2015-03-27 03:29:26 INFO     SHOWUPDATER :: Completed full update on all shows
2015-03-27 03:29:25 INFO     SHOWUPDATER :: Trying to clean cache folder C:\SickRage-develop\cache
2015-03-27 03:29:25 INFO     SHOWUPDATER :: Doing full update on all shows

And this is 10 hours after the timestamps in the log...This show is queued and awaiting an update.
![simp2](https://cloud.githubusercontent.com/assets/11670746/6867743/635c8282-d485-11e4-9440-7214894f0477.PNG)
all continuing shows show the same message

**Comment by fernandog** [comment]
Check logs. Filter by showrefresh. See if there is still updates

**Comment by cyberundertaker** [comment]
@fernandog This is the SHOWQUEUE-REFRESH log:
http://pastebin.com/P7hmeLkD

**Comment by cyberundertaker** [comment]
@fernandog 
I think it's stuck somewhere on Falling Skies
on that show it shows message: The episodes below are currently being refreshed from disk

**Comment by cyberundertaker** [comment]
#1043

**Comment by abeloin** [comment]
@cyberundertaker Your log contain only level:info only, can you provide the whole with the debug info?

**Comment by cyberundertaker** [comment]
@abeloin Full log(sickrage.log, 15MB):
https://drive.google.com/file/d/0ByFb16E-5XuQMGtmNDMzRGstMmM/view?usp=sharing

**Comment by abeloin** [comment]
@cyberundertaker Sorry I just realized you already posted the log in the other thread

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
