### ISSUE TITLE
[Feature Request] Don't use proxy for private trackers that ban if more than one IP is used

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#1047]
global proxy or provider proxy.

One that I know: HDT

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
