### ISSUE TITLE
[Feature Request] Check if proxy host has http:// or https// or socks5:// or socks4:// and port number

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#1048]
also add a label showing all types of proxies allowed:
http://
https//
socks4://
socks5://
...

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
