### ISSUE TITLE
traktException: 504 Server Error: Gateway Time-out

### ISSUE THREAD

**Issue by gborri** [SiCKRAGETV/sickrage-issues#1049]
@fernandog @abeloin today i got this one.
Probabily is better to manage all the return code (or part of it) from traktv as suggeste by @fernandog with inheritance...

http://docs.trakt.apiary.io/#introduction/status-codes

**Comment by abeloin** [comment]
@gborri Do you need this error to be handled specifically for your code? If not, it's already catched in the generic traktException, see https://github.com/SiCKRAGETV/SickRage/blob/fd640097758c8a5746a6f83cb29574d9a9106e15/lib/trakt/trakt.py#L49

If I didn't understand your question properly, please explain it in detail.

**Comment by gborri** [comment]
you are right. The point probably it's only cosmetic the exception error is not beautiful....

**Comment by abeloin** [comment]
That is because you are running with debug=1 in config.ini which result in you seeing all debug message. Set it to 0 and you won't see any debug message

**Comment by gborri** [comment]
ok, thanks. sorry for the unuseful issue.

**Comment by abeloin** [comment]
This PR should "fix" the issue: https://github.com/SiCKRAGETV/SickRage/pull/1660

The error is still recorded in the log but if the user didn't set debug=1, he wont be able to see it.

@fernandog

**Comment by fernandog** [comment]
@abeloin why don't we add this like https://github.com/SiCKRAGETV/SickRage/pull/1653/files ?

**Comment by abeloin** [comment]
@fernandog That is if you want to catch the error specifically and assign it a particular exception code. It will still be catched by this line: https://github.com/SiCKRAGETV/SickRage/blob/fd640097758c8a5746a6f83cb29574d9a9106e15/lib/trakt/trakt.py#L49

What @gborri is talking about is the caller is in a try...except block and output logger.log(ex(e)logger.DEBUG) in case of an error. It's the debug line he see in the view log that bothered him. We need those debug line when an error arise to be able to find a solution. The PR simply hide DEBUG and DB from the viewlog.tmpl when debug in config.ini is set to 0.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1662
