### ISSUE TITLE
[Feature Request] Add Notification for episodes that havn't been downloaded after airdate

### ISSUE THREAD

**Issue by Yaff1e** [SiCKRAGETV/sickrage-issues#1050]
Just wondering if there's any possibility of having a notification sent when a new episode should be available but hasn't been downloaded after X days? I've just found out that two new seasons of shows started a week ago but both are showing as missed even though episodes are available. If there was a notification after X days I could have investigated and downloaded manually.

**Comment by gborri** [comment]
@Yaff1e look at SiCKRAGETV/SickRage#1510, is this something that suit your need?

**Comment by Yaff1e** [comment]
I'll have a read through that thanks. I'm just after a notification (Pushbullet in my case) that says something like "Episode aired X days ago but hasn't been found / downloaded yet"

**Comment by gborri** [comment]
in SiCKRAGETV/SickRage#1510 you have also a notification when an episode is available on the torrent.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
