### ISSUE TITLE
failed download handling with sab

### ISSUE THREAD

**Issue by saitoh183** [SiCKRAGETV/sickrage-issues#1052]
i use nzbtomedia for postprocessing and i dont know if that is the problem but when i file fails to download in sab, it just stays failed and in SR, the file stays as snatched. Is this normal behavior or am i missing something?

**Comment by abeloin** [comment]
### SUBMITTING A BUG/ISSUE TICKET
(DO NOT POST ANYTHING THAT CONTAINS YOUR LOGIN INFORMATION OR API KEY)<br />
Please include the following when opening a new ticket:
 - Branch
 - Commit hash
 - Your operating system and python version
 - What you did
 - What happened
 - What you expected
 - Link to a copy/paste of your logfile with clear debug info of the error on [GIST](http://gist.github.com)

**Comment by saitoh183** [comment]
SR Version:	BRANCH: (master) / COMMIT: (c28ca92c6d19ce1610a83ac08707529ad0796718) 
Windows
python 2.7

**Comment by abeloin** [comment]
Did you enable fail download in Post-Process, if you did please provide logs from your sabtosr script and SR log

**Comment by saitoh183** [comment]
yes it has been enabled. There is not nzbtomedia log because the script doesnt run when a download fails. There is no SR log cuz it happened during the night and the log is already overwritten

**Comment by saitoh183** [comment]
all i see is the failed download in sab history

**Comment by fernandog** [comment]
@saitoh183 did you opened a thread in the sickrage.tv forum in nzbtomedia sub-forum? Please post there. If is a confirmed problem in SickRage than we can analyse. We can't help you with nzbtomedia. Also you need logs, otherwise they wont be able to help you

**Comment by saitoh183** [comment]
Ok but this isnt a nzbtomedia problem because Sab will not call a script if a download fails. So the only thing i could think off is SR not doing something.

**Comment by fernandog** [comment]
sab runs nzbtomedia that call SRs
are you 100% sure nzbtomedia is running/set ok? 
without nzbmedia logs and confirm it's ok we can't do much. first be sure nzbmedia is running ok and have no erros

**Comment by saitoh183** [comment]
Sab run nzbtomedia just fine when download doesnt fail. But Sab does not run any script if a download fails.

**Comment by saitoh183** [comment]
But how can nzbtomedia set anything if sab does call the script?

**Comment by fernandog** [comment]
you said: "i use nzbtomedia for postprocessing"

If nzbtomedia runs after SAB finishes download, then it calls SR to set that failed episode.

**Comment by saitoh183** [comment]
Yes but Sab will only execute a script if a download is successful not if a download fails

**Comment by fernandog** [comment]
tell me where did you get that information that "Sab will only execute a script if a download is successful not if a download fails"

please post the url or forum where you read that

**Comment by saitoh183** [comment]
![image](https://cloud.githubusercontent.com/assets/1534197/6875239/a33586b6-d493-11e4-9cd8-19166e25d55b.png)

**Comment by fernandog** [comment]
please read hot nzbtomedia works

https://github.com/clinton-hall/nzbToMedia

**Comment by fernandog** [comment]
@saitoh183 I don't get it how you set nzbtomedia and don't read what it does:

```
Config -> Switches -> Post-Process Only Verified Jobs (off) Deselect in order to allow for snatching of the next best release from CouchPotatoServer when a download fails.

Config -> Special -> empty_postproc (on) For better handling of failed downloads in version 0.7.5 of SABnzbd a new special parameter named "empty_postproc" was introduced.

Description of this special parameter according to SABnzbd manual:
```

Do post-processing and run the user script even if nothing has been downloaded. 
**This is useful in combination with tools like SickBeard, for which running the 
script on an empty or failed download is a trigger to try an alternative NZB. 
Note that the "Status" parameter for the script will be -1. [0.7.5+ only]**

https://github.com/clinton-hall/nzbToMedia/wiki/sabnzbd

**Comment by saitoh183** [comment]
yeah i had set that...i think i know what happened...i think my config switched back when my server crashed...didnt think of checking it again. Thanks fernandog
