### ISSUE TITLE
T411 errors

### ISSUE THREAD

**Issue by saitoh183** [SiCKRAGETV/sickrage-issues#1054]
Today i been seeing this in the error log

```
2015-03-27 17:14:11 SEARCHQUEUE-RETRY-164981 :: [T411] :: Failed parsing T411 Traceback: Traceback (most recent call last):
  File "E:\SickRage\sickbeard\providers\t411.py", line 220, in _doSearch
    torrent_name = str(torrentName)
  File "E:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u016b' in position 6: character maps to <undefined>
```

What does it mean?

BRANCH: (master) / COMMIT: (c28ca92c6d19ce1610a83ac08707529ad0796718)
Python Version:	2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
Windows
SR Locale:	('en_CA', 'cp1252')

**Comment by fernandog** [comment]
@saitoh183 why didn't you use the "submit error" ?

**Comment by saitoh183** [comment]
Cuz it was failing to submit...but i had to restart SR and now it worked

**Comment by fernandog** [comment]
@saitoh183 what worked? this "charmap' codec can't encode character u'\u016b'" or the button "submit error" ?

**Comment by abeloin** [comment]
@saitoh183 What were you searching for?

**Comment by saitoh183** [comment]
@fernandog 
submit error
@abeloin 
i wasnt searching for anything...i think this was during the auto search.

I also see 
2015-03-27 04:05:48 FINDPROPERS :: [T411] :: Invalid username or password for T411 Check your settings

pretty often

**Comment by abeloin** [comment]
@saitoh183 If the user/pass is valid, t411 is refusing you access temporarily.

**Comment by saitoh183** [comment]
@abeloin 
ok.. and what about the first error?

**Comment by abeloin** [comment]
@saitoh183 Manually apply this PR https://github.com/SiCKRAGETV/SickRage/pull/1664 which is a one liner. It will be merged Sunday in master.
