### ISSUE TITLE
KAT - Season search downloading wrong season

### ISSUE THREAD

**Issue by Alexwijn** [SiCKRAGETV/sickrage-issues#1055]
Hi, 

He keeps downloading season 5 (The Vampire Diaries S05 Season 5 COMPLETE 720p WEB DL DD5 1 H 264 KiNGS) when he flags season 1 as snatched as 720p Web-dl. Also season 5 is already 720p Web-dl. 

My logs (see the end of it):
http://s000.tinyupload.com/index.php?file_id=63934800944250113036

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/

**Comment by Alexwijn** [comment]
Other info, as silently requested:
Python Version: 2.7.3 (default, Mar 18 2014, 05:13:23) 
[GCC 4.6.3]
Operating System: Linux-3.18.7+-armv6l-with-debian-7.8
Branch: master
Commit: SiCKRAGETV/SickRage@3b11079

**Comment by fernandog** [comment]
@Alexwijn please update

**Comment by fernandog** [comment]
@abeloin 

SR is searching for Season 1  BUT the season 5 has the "1" in code so SR thinks this result is season 1. Or we need to adjust the search string or make change/adjust the regex

https://kickass.to/usearch/The+Vampire+Diaries+Season+1+-Ep%2A+category%3Atv/?field=seeders&sorder=desc

**Comment by Alexwijn** [comment]
@fernandog what do you want that I update?

**Comment by fernandog** [comment]
@Alexwijn you are using SR v4.0.13 but the last update is v4.0.14

**Comment by Alexwijn** [comment]
I will report back this evening (GMT+2)

**Comment by fernandog** [comment]
@Alexwijn no need.

**Comment by fernandog** [comment]
@abeloin @TagForce 

It searches for S01 and Season 1. But searching for Season 1, the Season 5 is a result too for that search string
```
[KickAssTorrents] :: Search string: https://kickass.to/usearch/The+Vampire+Diaries+S01+-S01E+category%3Atv/?field=seeders&sorder=desc&rss=1
[KickAssTorrents] :: Search string: https://kickass.to/usearch/The+Vampire+Diaries+Season+1+-Ep%2A+category%3Atv/?field=seeders&sorder=desc&rss=1
```

shouldn't we do regex match in pickbestresult to confirm the result are ok? In this case season 5 shouldn't be here:

Picking the best result out of [
u'The.Vampire.Diaries.S01.720p.Bluray.x264', u'The.Vampire.Diaries.S01.720p.Bluray.x264',
u'The.Vampire.Diaries.S05.Season.5.COMPLETE.720p.WEB-DL.DD5.1.H.264-KiNGS',
u'The.Vampire.Diaries.S01.720p.HDTV.x264', u'The.Vampire.Diaries.S01.HDTV.x264',
u'The.Vampire.Diaries.S01.HDTV.x264', u'The.Vampire.Diaries.S01.DVDRIP']

**Comment by fernandog** [comment]
@Alexwijn please test:

- stop SR
- edit SickRage/sickbeard/providers/kat.py and erase contents.
- paste this one: https://raw.githubusercontent.com/fernandog/SickRage/kat_season/sickbeard/providers/kat.py
- save
- start
- try to reproduce the error

**Comment by Alexwijn** [comment]
@fernandog With your fix he is now downloading the correct seasion. In this case season one.
