### ISSUE TITLE
Sickrage not launching in Firefox 

### ISSUE THREAD

**Issue by bkrieger674** [SiCKRAGETV/sickrage-issues#1057]
I have Windows 8 with Sickrage installed using Python. When my PC starts, Firefox opens automatically, but just brings up a blank webpage. I'm assuming this is Sickrage opening it, but it should direct to my Sickrage server. When I click on the Sickrage icon, nothing happens. I am able to go into my favorites on Firefox and connect to Sickrage that way.
So, is it because Sickrage is already open when I click on the icon, and that is why nothing happens?
Also, how do I fix this where Firefox opens and directs to Sickrage without having to manually go into my favorites and find Sickrage?

Lasso, there is no Sickrage tray icon in my task at like other programs like couch potato. Should there be?

Thanks.

**Comment by fernandog** [comment]
@abeloin can you reply this please ? I run as headless server

**Comment by abeloin** [comment]
@bkrieger674 Please provider how sickrage is installed in Windows 8?

> When my PC starts, Firefox opens automatically, but just brings up a blank webpage.

When you said that Firefox is opening a blank page, does it contain an url in address bar?

> Lasso, there is no Sickrage tray icon in my task at like other programs like couch potato. Should there be?

That depend on how you started SR.

**Comment by bkrieger674** [comment]
I have it installed using Python. I think I figured it out. The blank page is a problem in Firefox. I don't have Lauch Browser checked, but when I was using Interney Explorer, it would still open automatically.  Thanks.

**Comment by abeloin** [comment]
@
