### ISSUE TITLE
rtorrent: unable to send torrent

### ISSUE THREAD

**Issue by nytemyst** [SiCKRAGETV/sickrage-issues#1061]
BRANCH: (develop) / COMMIT: (44f949a914c68daf80bcb50989f1a75454327b59) 
Windows Server 2008 r2
Python 2.7

```
2015-03-29*13:38:37*INFO*****SEARCHQUEUE-DAILY-SEARCH*::*Downloading*Saturday.Night.Live.S40E16.Dwayne.Johnson.720p.HDTV.x264-W4F.-.TV-HD-X264*from*Ace*Torrents
2015-03-29*13:38:37*DEBUG****SEARCHQUEUE-DAILY-SEARCH*::*Calling*rTorrent*Client
2015-03-29*13:38:42*ERROR****SEARCHQUEUE-DAILY-SEARCH*::*rTorrent:*Unable*to*send*Torrent:*Return*code*undefined
None
2015-03-29*13:38:42*INFO*****SEARCHQUEUE-DAILY-SEARCH*::*Downloading*[AnimeRG].One.Piece.686.(720p).(Eng..Subbed).[ScavvyKiD]*from*NyaaTorrents
2015-03-29*13:38:42*DEBUG****SEARCHQUEUE-DAILY-SEARCH*::*Calling*rTorrent*Client
2015-03-29*13:38:47*ERROR****SEARCHQUEUE-DAILY-SEARCH*::*rTorrent:*Unable*to*send*Torrent:*Return*code*undefined
None
```

The torrent file is actually still making into Rtorrent but it's not registering as a snatch so it'll keep on trying. Also rtorrent is not picking up the downloaded files location.

**Comment by abeloin** [comment]
Need more info:
* rtorrent config in SR
* downloaded files location and rtorrent on the same machine?

**Comment by nytemyst** [comment]
rtorrent host: port
https://Myseedbox.com/nytemyst/rutorrent/plugins/httprpc/action.php

Http authentication : Basic
unchecked veryfiy ssl certificates
username and password filed in
add label to torrent: tv
label for anime : empty
downloaded files location : /home/nytemyst/downloads/tv

downloaded files location and rtorrent are on the same machine yes.

**Comment by abeloin** [comment]
@nytemyst Do you have logging enable in rtorrent? If so, can you check the log when SR added the torrent.

**Comment by nytemyst** [comment]
I do not and I'm not familair with setting it up as i tried and i couldn't get it to work. It's a seedbox so I'll have the host provider see about enabling logging for me.

**Comment by abeloin** [comment]
Ok, before you do that can you confirm `/home/nytemyst/downloads/tv` exits on the seedbox?

**Comment by nytemyst** [comment]
It does and i have other stuff in there.

**Comment by abeloin** [comment]
Will have to do some test

**Comment by nytemyst** [comment]
I can try having it use the default location and see if it goes thru all the way that way and if so at least that gives us a direction on where to look at .

**Comment by abeloin** [comment]
Yes

**Comment by abeloin** [comment]
@nytemyst Traceback added in develop, please update and retry.

**Comment by nytemyst** [comment]
2015-03-30*01:58:51*DEBUG****SEARCHQUEUE-MANUAL-262569*::*Calling*rTorrent*Client
2015-03-30*01:58:57*DEBUG****SEARCHQUEUE-MANUAL-262569*::*Traceback*(most*recent*call*last):
**File*"C:\SickRage\sickbeard\clients\rtorrent.py",*line*107,*in*_add_torrent_file
****torrent*=*self.auth.load_torrent(result.content)
**File*"C:\SickRage\lib\rtorrent\__init__.py",*line*320,*in*load_torrent
****self.get_torrents()
**File*"C:\SickRage\lib\rtorrent\__init__.py",*line*181,*in*get_torrents
****results*=*m.call()[0]**#*only*sent*one*call,*only*need*first*result
**File*"C:\SickRage\lib\rtorrent\rpc\__init__.py",*line*168,*in*call
****results*=*m()
**File*"C:\Python27\lib\xmlrpclib.py",*line*997,*in*__call__
****return*MultiCallIterator(self.__server.system.multicall(marshalled_list))
**File*"C:\Python27\lib\xmlrpclib.py",*line*1224,*in*__call__
****return*self.__send(self.__name,*args)
**File*"C:\Python27\lib\xmlrpclib.py",*line*1578,*in*__request
****verbose=self.__verbose
**File*"C:\SickRage\lib\rtorrent\lib\xmlrpc\requests_transport.py",*line*152,*in*request
****return*self.parse_response(response)
**File*"C:\SickRage\lib\rtorrent\lib\xmlrpc\requests_transport.py",*line*166,*in*parse_response
****p.feed(response.text)
**File*"C:\Python27\lib\xmlrpclib.py",*line*557,*in*feed
****self._parser.Parse(data,*0)
**File*"C:\Python27\lib\encodings\cp1252.py",*line*12,*in*encode
****return*codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError:*'charmap'*codec*can't*encode*character*u'\u200e'*in*position*1299031:*character*maps*to*<undefined>

2015-03-30*01:58:57*ERROR****SEARCHQUEUE-MANUAL-262569*::*rTorrent:*Unable*to*send*Torrent:*Return*code*undefined
None

**Comment by fernandog** [comment]
@nytemyst what is the torrent name?

**Comment by abeloin** [comment]
@fernandog It trying to encode the xml data returned from rtorrent

**Comment by nytemyst** [comment]
The Last Man on Earth S01E07 1080p WEB-DL DD5.1 H.264.torrent

**Comment by abeloin** [comment]
PR merged in develop

@nytemyst Please update SR

**Comment by nytemyst** [comment]
Looking good. Labeling works and it's saving in the right directory and showing up as snatched. Thanks!
