### ISSUE TITLE
[Feature Request] Add more than one TV-download dir for monitoring/PP

### ISSUE THREAD

**Issue by nytemyst** [SiCKRAGETV/sickrage-issues#1062]
Possible to add a feature to allow adding multiple folders to monitor for post processing?

**Comment by fernandog** [comment]
@tagforce

**Comment by TagForce** [comment]
@nytemyst @fernandog Of course it's possible... But why? I would like to see a use case in which this is really necessary, otherwise it's just a user configuration problem, and not something we need to fix.

Personally I cannot think of a valid reason to monitor more than one download folder.

**Comment by nytemyst** [comment]
I use BTSync to sync my completed folder from my home machine and my seedbox and sickrage is watching that folder. But there are times that i want to manually download something that's not part of my synching and I don't want download it into the folder where sickrage monitors because it will sync back to the seedbox taking up more space.

I've been using manual post processing to get around this but it would be nice to automate this.

**Comment by TagForce** [comment]
@nytemyst You could create a completed folder, and a sync folder inside that that gets synced... That way you could have your completed folder post-processed, and put your manual downloads in there, and have only the sync folder synced... That would solve your having to manually PP the manually downloaded files, wouldn't it?

I'll see if I can add an extra folder to auto sync, but it won't be a high priority thing, so don't expect that to be done anytime soon. I've been thinking about it, and I can think of 2 or 3 use cases where more than one PP folders would be nice to have. So, I'll work on it.

**Comment by nytemyst** [comment]
That would be doable i would have to think about how i would go about doing it. Currently My root folder is ~\completed and then i have subfolders in that one as tv/movies/music and those folders are the ones that are being monitored by the different apps. I sync just the root folder and it gets everything in one shot.

I'm not expecting this to be done anytime soon since it's more of a nice to have then anything. Thanks.

**Comment by Smiggel** [comment]
+1 I would like to see this too. Use case:

Usenet torrents are downloaded to my tv folder to be processed
My torrents are downloaded to a transmission folder. I don't want all my torrents in the tv folder, so I use a different folder for all torrents. 

In my case it would be nice to be able to set the transmission folder too for SR to find any files in there as well.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
