### ISSUE TITLE
"Mark as watched" feature

### ISSUE THREAD

**Issue by etatus** [SiCKRAGETV/sickrage-issues#1063]
It would be awesome if you could tag episodes as watched to know the progress when you are watching a tv-show.

**Comment by fernandog** [comment]
You can do that in your media center. Use trakt plugin. SR handles downloads only

**Comment by etatus** [comment]
Maybe you are right, but my Smart TV player via DLNA hasn't the posibility to automatically mark as watched the episodes. Another option could be to use the Archived tag as Wachted tag.

**Comment by fernandog** [comment]
Use SeriesGuide app or trakt website using phone. I did that before buying a raspberry pi.

**Comment by etatus** [comment]
I think I can do the same with SickRage android app using Archived tag :)

**Comment by TagForce** [comment]
@etatus Whether or not your DLNA TV Player marks an episode as watched or not is not an option of your TV, but of the DLNA server you're using to stream the video to your TV. Plex Media Server, for instance, will mark any video as watched when ANYTHING plays a video up to 80% of it's total running time, regardless of what is playing it (could be either a Plex Home Theater, the web interface, or a DLNA client).
