### ISSUE TITLE
Redirect Loop

### ISSUE THREAD

**Issue by rynsmns** [SiCKRAGETV/sickrage-issues#1064]
When sickrage starts it opens a chrome webpage and I receive the error redirect loop. I can get to the config section but not the shows section. I have tried removing and re installing but eventually the error comes back.

I grabbed this error from the Logs and Errors section:

```
2015-03-29 16:19:42 Thread-53 :: Failed doing webui callback: Traceback (most recent call last):
  File "c:\sickrage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "c:\sickrage\sickbeard\webserve.py", line 723, in index
    return t.respond()
  File "c:\sickrage\cache\cheetah\_sickrage_gui_slick_interfaces_default_home_tmpl.py", line 1014, in respond
    _v = VFN(VFSL([locals()]+SL+[globals(), builtin],"calendar",True),"timegm",False)(VFN(VFSL([locals()]+SL+[globals(), builtin],"pdatetime",True),"timetuple",False)()) # u'$calendar.timegm($pdatetime.timetuple())' on line 607, col 39
  File "c:\sickrage\lib\dateutil\tz.py", line 114, in dst
    if self._isdst(dt):
  File "c:\sickrage\lib\dateutil\tz.py", line 152, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: (22, 'Invalid argument')
```

What can I do to resolve?

**Comment by abeloin** [comment]
### SUBMITTING A BUG/ISSUE TICKET
(DO NOT POST ANYTHING THAT CONTAINS YOUR LOGIN INFORMATION OR API KEY)<br />
Please include the following when opening a new ticket:
 - Branch
 - Commit hash
 - Your operating system and python version
 - What you did
 - What happened
 - What you expected
 - Link to a copy/paste of your logfile with clear debug info of the error on [GIST](http://gist.github.com)

**Comment by rynsmns** [comment]
BRANCH: (master) / COMMIT: (c28ca92c6d19ce1610a83ac08707529ad0796718) 
Your operating system and python version: Windows 8.1/Python 2.7
What you did: Launched Sickbeard and opened a chrome page to it's webui
What happened: Redirect Loop error from Chrome
What you expected: I expected Sickrage's webui to open
Link to a copy/paste of your logfile with clear debug info of the error on GIST:
https://gist.github.com/rynsmns/36c43371815e3ec148c5

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1037

**Comment by abeloin** [comment]
@rynsmns Please update to the latest version, there is a fix in it.
