### ISSUE TITLE
[Feature Request] Add new Regex for Renamer [groupname]-[show]s04e20-1080p

### ISSUE THREAD

**Issue by gctrullinger** [SiCKRAGETV/sickrage-issues#1067]
**Branch:** master
 **Commit hash:** c28ca92c6d19ce1610a83ac08707529ad0796718
 **Operating system and python version:** FreeNAS-9.3-STABLE-201503071634 with Python 2.7.8

I have a lot of episodes that are downloaded with names formatted like the ones below:

[groupname]-[show]s01e03.mkv
[groupname]-[show]s04e20-1080p.mkv

Would it be possible to add a regex that matches these for the renaming?

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
