### ISSUE TITLE
Some shows not updating from thetvdb

### ISSUE THREAD

**Issue by scythe000** [SiCKRAGETV/sickrage-issues#1068]
`SR Version: 	BRANCH: (master) / COMMIT: (33921ecd1697f99ef47015c700331358481c9b98) `
Server 2012, Python 2.7.8

The Walking Dead episode list is showing only part of episode 13, even though TheTVDB shows through episode 16.

**Comment by scythe000** [comment]
Is this a dupe or something?

**Comment by fernandog** [comment]
nope. there's no info I can work with.

**Comment by scythe000** [comment]
Pastebin won't let me submit logs over 512 bytes now, so sorry about this next post:

**Comment by scythe000** [comment]
http://paste.ee/p/v8RUr

**Comment by scythe000** [comment]
Looks like none of my shows are being updated form thetvdb???

**Comment by scythe000** [comment]
https://www.dropbox.com/s/mobekzkrb85c0hj/sickrage%20-%20Copy.log?dl=0

**Comment by scythe000** [comment]
@fernandog or @TagForce can we re-open this, please? I just did a hard reset and git pull. Still shows are not showing their proper episode info.

**Comment by abeloin** [comment]
@scythe000 We are currently modifying the scheduler to give more info on what is going on. It will be merged in develop this week. See this post for more info: https://github.com/SiCKRAGETV/sickrage-issues/issues/1043#issuecomment-89497256

**Comment by scythe000** [comment]
Thanks, @abeloin , but it looks like it may be a dupe of 1043.

**Comment by scythe000** [comment]
you beat me, haha.
