### ISSUE TITLE
Sickbeard wont add new shows

### ISSUE THREAD

**Issue by icebal** [SiCKRAGETV/sickrage-issues#1073]
The only thing in the logs is "Adding SHOWNAME" and then nothing. in the GUI it shows "Loading... (E:\SHOWNAME)" and doesn't actually add it. i have let it sit for 2 hours and no improvement, or log entries, even in DEBUG or console. all permissions are correct in the Media Folder, and am using windows 8.1. Even after adding the folder manually, this still doesn't help to advance the issue.

**Comment by icebal** [comment]
as added information, i am on the newest Master branch, checking Develop right now.

**Comment by fernandog** [comment]
@icebal 
master = develop 
don't bother change
without logs there's nothing we can do. Log is not just for errors

**Comment by icebal** [comment]
coolio, adding the logs real quick

**Comment by icebal** [comment]
http://pastebin.com/4rA3v6wQ

this is the log right after adding 2 shows, and waited 5 minutes to pull the log.

**Comment by abeloin** [comment]
@icebal The log provided seem incomplete as I don't see any pertinent data

**Comment by icebal** [comment]
that's what I was saying, it shows as adding but neither in the log, debug
log, or console is any info on what is wrong.

**Comment by abeloin** [comment]
What I meant is that we don't even see the search for your show. You should have, at least, something like when searching:
```
2015-03-31 00:26:38 DEBUG    Thread-67 :: Searching for Show with searchterm: Unbreakable Kimmy Schmidt on Indexer: theTVDB
```
then following with(which can be missing):
```
2015-03-31 00:26:45 INFO     SHOWQUEUE-ADD :: Starting to add show /Media/TVSeries/Unbreakable Kimmy Schmidt
2015-03-31 00:26:45 INFO     SHOWQUEUE-ADD :: theTVDB: {'useZip': True, 'apikey': 'F9C450E78D99172E', 'cache': '/opt/SickRage/cache/indexers/theTVDB', 'language': 'en'}
2015-03-31 00:26:45 INFO     SHOWQUEUE-ADD :: 281593: Loading show info from database
```

**Comment by icebal** [comment]
I will restart and re do the logs to make sure

**Comment by icebal** [comment]
http://pastebin.com/hpyTdhaF

log right after adding 2 shows. i do not see anything in the log saying its adding these. will delete the folders and try a new add next.

**Comment by icebal** [comment]
when adding as new, no existing folder, i do see a couple of references in the log located here:
http://pastebin.com/rLbZqJWR
listed are the entries with the shows name in it:
2015-03-31 08:17:02 DEBUG    Thread-302 :: Searching for Show with searchterm: Better Off Ted on Indexer: theTVDB
2015-03-31 08:16:15 DEBUG    Thread-41 :: Can't load the metadata file from u'E:\\Better Off Ted\\tvshow.nfo', it doesn't exist

**Comment by dan9100** [comment]
I had this same exact problem. The log files I had showed never "seeing" the show being added. Finally removed Sickrage and ALL install files and started fresh and slow to add new shows and making any changes from the install default settings. Finally working like I expected, for now.

**Comment by icebal** [comment]
as an update, the shows still have not gone past "Loading..." do you guys need another log file?

**Comment by abeloin** [comment]
Maybe related to https://github.com/SiCKRAGETV/sickrage-issues/issues/563

**Comment by icebal** [comment]
checked the linklockfile.py file and is the same as the above fix. will follow the TS'ing to try and narrow things down

**Comment by abeloin** [comment]
@icebal To see if it's related to #563:
* Stop SR.
* Change timeout=None to timeout=10 in https://github.com/SiCKRAGETV/SickRage/blob/master/lib/lockfile/__init__.py#L159
* Start SR

**Comment by icebal** [comment]
made the change but no affect :(

**Comment by fernandog** [comment]
@icebal does this show have previously created folder? If so, is there any NFO inside it?
If there is a previously folder, are you using "adding existing show" ? SR recognizes the folder and show it in the screen? Check folder permissions, see if is the same as the other folders
if there is no folder, are you using adding new show? 
Which indexer are you using?
Do you have proxy host enable? Do you have proxy for indexers enabled?

this logs you sent. we don't care about the "MAIN" category!
please use the log filter and filter by thread in the listbox

**Comment by icebal** [comment]
Ok listed out in order:
1. Add new show doesn't create the folder.
2. If I manually create the folder, and Add Existing, it sees the folder
and shows it.
3. Folder permissions are the same across the board, rw access to everyone
4. I have tested with both indexers and neither are working.
5. I do not have any proxies anywhere, nor are they enabled. I will post a
filtered log in a few

**Comment by apoapostolov** [comment]
Hello,
I am having the same issue (can't add shows) however @icebal says Add Show doesn't create the folder, and in my case the folder is created. However no metadata files are generated in it.
I cannot provide logs since I am not at my own machine right now, but let me know if you need any.

**Comment by abeloin** [comment]
@icebal Can you try this?
* Stop SR
* Remove any log file in /Logs folder (Make a backup of the logs if you want to keep them)
* Start SR
* Try adding a show
* Wait 2-3 mins
* Stop SR
* Send the files in /Logs via Dropbox or something like Dropbox.

**Comment by apoapostolov** [comment]
I attempted to add two shows:
* Arrow
* Big Bang Theory

Here's the log file: https://drive.google.com/open?id=0B97yxdhXM0wEdEcxRWtOUmUzemM&authuser=0

**Comment by abeloin** [comment]
@apoapostolov Your right in the middle of a show queue refresh/update, so the added show is at the end of the queue. You need to wait until the queue items are processed.

**Comment by abeloin** [comment]
@icebal You can try this experimental branch, it will show you where in the queue the added item is:

https://github.com/SiCKRAGETV/sickrage-issues/issues/1043#issuecomment-89497256

Make a backup first of your whole sickrage folder because I'm not responsible for corrupted DB.

**Comment by apoapostolov** [comment]
@abeloin I left my SickRage for hours and when I came back the shows weren't added.

**Comment by abeloin** [comment]
Is it still doing a SHOWQUEUE-FORCE REFRESH in the log?

**Comment by abeloin** [comment]
If not you could try this branch: https://github.com/SiCKRAGETV/sickrage-issues/issues/1043#issuecomment-89497256 which would should you the queue items

**Comment by apoapostolov** [comment]
Looks like it. I restarted SR, deleted all logs, and trying to add the same shows. Even 10 minutes later I am still seeing SHOWQUEUE-FORCE-UPDATE. Shouldn't SickRage treat Add Show actions with priority?

**Comment by abeloin** [comment]
Do you have trakt enable?

**Comment by apoapostolov** [comment]
Yes.

**Comment by abeloin** [comment]
Can you disable it temporarily, restart SR, then try adding a show?

**Comment by apoapostolov** [comment]
Same behavior. Still locked into Show Refresh processes. No even a single log line about the show I am adding.

**Comment by abeloin** [comment]
Do you have "Update shows on startup" enable in config->General?

**Comment by apoapostolov** [comment]
No, it's turned off.

**Comment by abeloin** [comment]
Can you try the branch I was talking about in my previous comment?

**Comment by apoapostolov** [comment]
On it. Installed your fork, moved my db and ini. Now going through updates.

**Comment by abeloin** [comment]
Try adding a show

**Comment by apoapostolov** [comment]
I reinstalled your fork, only migrated the db since the ini caused update that overwrote with develop.

I cannot find the Status > Scheduler menu, however adding new shows works perfectly.

**Comment by abeloin** [comment]
You don't see Scheduler Status in the drop down menu:
![Imgur](http://i.imgur.com/jyktAxR.png)

**Comment by apoapostolov** [comment]
My bad. I was using "master", moved to "feature-scheduler_fix", and now I see it. 
Sorry, I am relatively new to GIT. 

Now I see it fine. What should I look for?

**Comment by abeloin** [comment]
If a show is not added, go to that page and look in the queue to see where it is located(by default the table is sorted in the same way the item are being processed) and it will give you an indication when it should be updated.

![Imgur](http://i.imgur.com/esZitlY.png)

**Comment by apoapostolov** [comment]
Okay, but with your fork I am able to add absolutely every show I throw at it.

**Comment by abeloin** [comment]
Perfect, this branch will be in version 4.0.16 or 4.0.17 of Sickrage which change the adding show from a normal priority to a high(meaning they will be processed before other items)

**Comment by abeloin** [comment]
It should be this week if everything goes well(In master for Milestone v4.0.16), if not next week(In master for Milestone v4.0.17)

**Comment by fernandog** [comment]
@apoapostolov please update develop branch and report back

**Comment by apoapostolov** [comment]
Updated yesterday, issue was resolved. Thanks a lot guys!
