### ISSUE TITLE
[Feature Request] Add possibility to add subs directly into MKV files or run script after download.

### ISSUE THREAD

**Issue by BenjV** [SiCKRAGETV/sickrage-issues#1075]
I have a python script that add the subtitle into the .mkv files and then move it to a location from which my mediaplayer can play that video.
It would be nice to be able to call that script from SickRage when the subtitle is downloaded.
So a switch to when an external script is called (after downloading video or after downloading sub) or a second option to call an external script(after downloading sub) would be nice

**Comment by neoatomic** [comment]
@miigotu An option to add the subs directly into the *.mkv files might be a nice addition. What do you think.?

@BenjV Would you able to compile the code and do a pull request of that function/script.?

**Comment by miigotu** [comment]
I would need to see the code, seems like a total re-encode of the file??? If so it is too risky/labor intensive to include directly, but maybe we can add a way to call a script when a subtitle is saved.

Can I see the code to that py script @BenjV ?

**Comment by fernandog** [comment]
I think there is a field for external script in PP. You could use that

**Comment by miigotu** [comment]
@fernandog This is different than PP script, he want to run a script when a new subtitle is downloaded.

**Comment by fernandog** [comment]
You can make a script that runs from time to time that finds .srt files in your tv folder and run mkvtool to merge it. Search the web. Easy script.

**Comment by miigotu** [comment]
Yes but what he is asking for is something that is on demand rather than timed. ie: sub downloaded? let me run this script now. It is more efficient this way.

**Comment by BenjV** [comment]
miigotu is right.
Just a possibility to run a script after a subttitle file is downloaded will do the trick.
Nothing fancy, just copy the existing code for a postprocessing script and make an extra field in the user interface.

I use ffmpeg to merge the subs into the video file and it just uses stream copy so no re-encode is needed.
Of course this works only on .mkv and .mp4 file's and ffmpeg should be installed on the system.

To much dependancies to put this code into SickRage, so please give me a postprocess call.

**Comment by miigotu** [comment]
postprocess-like call ^ for post-subtitle-download lol

**Comment by miigotu** [comment]
@BenjV The only thing I'm worried about, is what if 10 episodes (or more) download subtitles back to back? Your script would need to be persisten across subsequent calls and hold a queue, or you would have an assload of ffmpeg processes running at once.

**Comment by BenjV** [comment]
That's true but not very difficult to make.
On the other site, processing this with ffmpeg only takes about 45 second for a .mkv file of a GB on my Synology Nas.
Most of the time subtitles are not downloaded in the same moment of time.

**Comment by miigotu** [comment]
If you download a season pack, or more than 1 episode, it takes about 6 seconds per episode to get the subtitles for it, so essentially in 45 seconds you have 6 instances of the script. What happens if it is bluray? =P

**Comment by BenjV** [comment]
I don't download season packs or full blu rays

**Comment by BenjV** [comment]
The same is true if someone uses the normal postprocessing to do things.

**Comment by miigotu** [comment]
Nope, normal post processing is only intended for external notifications scripts or renames or moves, so its a little different. Either way, I can add this eventually but it is not a rush.

**Comment by BenjV** [comment]
If you use a normal postprocessing script to copy for example the video file to another location and you have 10 download ready it will start 10 copy jobs at the same time.
So I think the same problem would arise then.

**Comment by miigotu** [comment]
nope, SR waits for the first script to return before proceeding the PP, maybe I can make the subs one do that also.

**Comment by miigotu** [comment]
@BenjV Is the path + filename to each subtitle and the video path + filename enough parameters to pass to the script or should I pass more?

Also, should it process each video with all found subtitles at once, or process the video once for each subtitle?

**Comment by miigotu** [comment]
@BenjV can you test that branch?

argument #1 is the absolute path to the video
argument #2+ are absolute paths to each of the new subtitles downloaded. (however many downloaded)

**Comment by BenjV** [comment]
All the found subtitles at once is fine with me.

Parameters I would like are:
1. Absolute path to the video file
2. Absolute path to the sub file
3. Subtitle Language 
3. Name of the Show
4. Season Number
5. Episode Number
6. Episode Title

I am not able to test today because I am not at home today.
Will test tomorrow.

**Comment by miigotu** [comment]
I'll entend the parameters later, but why? Embedding that all in the container?

**Comment by BenjV** [comment]
I also place the muxed video to on my mediaplayer in a season folder and the name will be the episode number follewed by the episode title.
So
/Game.of.Thrones.S05E05.1080p.HDTV.x264-BATV.mkv
will become
/mediaplayer/Game of Thrones/ Season 5/05. Kill the Boy.mkv

That's much more userfriendly for the non technical viewers.
I also download sub in English (not my native language) in  case the Dutch subs wil not become available, so I need to know what language the sub is.

**Comment by miigotu** [comment]
If you download them in with the multi subs option, they have the lang code in the file name.
Also, why is your subtitle script doing renaming and moving of files?

when the video is post processed it's renamed, and you could just add the subs to the mkv in place as they are downloaded later no?

Just not sure how to pass that many args when it could be a lot of subs/languages per episode depending on how many languages someone has enabled for subtitles.

**Comment by adaur** [comment]
That would be a killer-feature. I hope you will share your script to add subtitles :)

**Comment by miigotu** [comment]
@adaur I've already coded it, but all those parameters are not passed yet.

Right now its passing like this:
`u'../Shows/Game of Thrones/Season 05/Game of Thrones - S05E03 - High Sparrow.mkv' u'../Shows/Game of Thrones/Season 05/Game of Thrones - S05E03 - High Sparrow.es.srt' u'../Shows/Game of Thrones/Season 05/Game of Thrones - S05E03 - High Sparrow.en.srt'`

**Comment by miigotu** [comment]
Also, it is passed between subtitles downloaded/saved and subtitles refreshed in the db, so you could even remove the srt and SR will still see you have it.

**Comment by BenjV** [comment]
Ok if so much parameters is a problem, forget that.
I didn' think about the fact that you have to support many subtitle languages.
I can analyse the filenames and get the information that way, or I will a call to the SickRage Api.

I am sorry to say that testing this has to be posponed. Something came up at work a I will not be at home for the rest of this week, maybe coming weekend.

**Comment by miigotu** [comment]
@BenjV Can the mkv container hold more than one subtitle? Do you only add them to mkv's or also to mp4?

**Comment by fernandog** [comment]
can be more then one. also user can choose the language code

**Comment by miigotu** [comment]
So the ffmpeg command only accepts one at a time? I could call the script once for each subtitle language, and provide all of the parameters you originally wanted very easily then

**Comment by fernandog** [comment]
one at the time: really don't know

**Comment by BenjV** [comment]
A mkv container can hold as many video, audio and subtitle streams as you want, but more then one video stream is not practical. More then one sub can be very handy.

Providing to call a subprocess after every subtitle is what I had in mind, if I want two subs (for example Dutch and English it is very easy to add the second sub to the container which already has the video, audio and other sub stream on board.

As I said, I create a new container and copy the videostream and the audiostreams from the original container to it and als the sub stream from the subtittlefile.
If a second sub arrived from SickRage I could add that one tot this container.

By the way everything is alsof true for .mp4 containers, ffmpeg supports those also.

**Comment by miigotu** [comment]
@BenjV I'd like to see your python code, just to make sure what I'm doing wont break anything when you use your script with it.

I think with this you should use copy or move method and renaming from the post processor
You should be able to mux in place, so if a new subtitles gets downloaded at some future time, it should add the subtitle to the container in place in your library.

I have added all of those arguments to the PR, and the script is called once for each subtitle (10 new subtitles/languages downloaded for the file at once == 10 consecutive calls to the script)

I have also added that mp4 be allowed to run scripts on subtitle download.

**Comment by BenjV** [comment]
@miigotu I think your'e right.
I will use the move and rename methode of SickRage postprocessor and just add the subtitle(s) to this file when they become available.
This will make the script very simple and I will not need all those parameters
Just these two.
1. Full file specs of the video file
2. Full files specs of the subtitle file

**Comment by miigotu** [comment]
It is already merged atm, is there any way to process more than one subtitle at a time with the ffmpeg command?

**Comment by BenjV** [comment]
No problem extra paramaters are never a problematic

ffmpeg will allow you to merge more subtitles into a container in one command, but why would you want to do that?

**Comment by miigotu** [comment]
You can have as many subtitle languages as you want configured in SR.

When it searches for subs, it downloads every subtitle in your languages list it can find for that video.

I then have a list of subtitles it downloaded in that run, for that one video.

Some people use 2 or more subtitle languages, in case their main language cannot be found and they speak more than one language, but they want to watch a movie in a language that they dont speak.

**Comment by BenjV** [comment]
aha, I did not know that it downloads every subtitle it can match for one language.
I always 0only got one for my language, but that can was probably coinsidence.

I shall build a scorematcher to select the beste subtitle then based on matching releasgroup, video quality and source (like web-dl, hdtv , bluray etc).

**Comment by miigotu** [comment]
No, I mean it downloads 1 subtitle for each language, you can have as many different languages as you want.

**Comment by BenjV** [comment]
Ok I knew that
