### ISSUE TITLE
Can't add existing shows

### ISSUE THREAD

**Issue by Jonnehs** [SiCKRAGETV/sickrage-issues#1076]
2015-03-31 16:05:28 Thread-22 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 2240, in massAddTable
    cur_path),
  File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)

Qnap QPKG

SR Version:	BRANCH: (master) / COMMIT: (e28f73f73048ce2e2a6c8a13aab0aa5ac7915c27) 
SR User:	admin
SR Locale:	(None, None)
SR Config file:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/config.ini
SR Database file:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/sickbeard.db
SR Cache Dir:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/cache
SR Log Dir:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/Logs
SR Arguments:	['--daemon', '--datadir', '/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config', '--pidfile', '/tmp/SickBeard-TVRage.pid']
Python Version:	2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]

**Comment by Jonnehs** [comment]
Selecting the directory with my series in causes it to hang with a spinning circle. I can press OK, but I get the above when I do.

**Comment by fernandog** [comment]
@Jonnehs 

you don't have a locale set for admin user:
SR Locale: (None, None)

please set UTF-8 as locale

**Comment by Jonnehs** [comment]
My locale output on SSH says it is utf-8, do I need to set it on SR somewhere?

**Comment by fernandog** [comment]
Are you logged as admin when running locale?

**Comment by Jonnehs** [comment]
@fernandog yes, the admin user on the NAS

**Comment by Jonnehs** [comment]
[~] # locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8

**Comment by Jonnehs** [comment]
Fixed this, there was a bloody folder with a non unicode char. Got rid of it, now working. Cheers.

**Comment by valantislevas** [comment]
Jonnehs how you fix the SR Locale: (None, None) ?

i also have correct locale like this:

root@hosted-by:~# locale
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
root@hosted-by:~#

**Comment by Jonnehs** [comment]
I never fixed it, it was a red herring. The software seems to work without that being correct. My issue was because there was a non-UTF character in the folder I was trying to scan.
