### ISSUE TITLE
Log levels narrowed in last few commits

### ISSUE THREAD

**Issue by kotysoft** [SiCKRAGETV/sickrage-issues#1077]
Hi. First thing first: Sickrage is awesome!

Issue (?): The possibilities in dropdown menu at 
/errorlogs/viewlog/
is decreased from db/debug/info/warning/errors
to
info/warning/errors

Since I'm not updating everyday it happened somewhere in last ~90 commits.
Is it intentional or accidental change?

Since I'm using on an old Syno nas (it means not everything works flawlessly), I need to check sometimes the debug for "what happening now, why python eats my cpu".

**Comment by fernandog** [comment]
@kotysoft by design. Please enable DEBUG in general settings
