### ISSUE TITLE
Request: Update only section appertaining in Plex 

### ISSUE THREAD

**Issue by Ockingshay** [SiCKRAGETV/sickrage-issues#1078]
Currently SR updates every section in Plex, This causes all my HDDs to spin up and slows my system right down, as i have a large library.

If i'm downloading a tv show, can it please just update the tv show section? 

Does it help that it works that way in sickbeard? so can you just adapt the code?

thanks

**Comment by fernandog** [comment]
@Ockingshay it updates all tv-shows sections. Each plex setup has different sections ID. Don't know if is possible to fetch al IDs and section names and user can select the ones he wants to update

**Comment by Ockingshay** [comment]
ok, interesting, thanks...i just did a retest and it indeed did just update various tv show sections...I'll check what sickbeard does.Would be nice though if it knew what parent folder it put the file in and then somehow knew what section plex assigns that to. 

It's not likely something they can happen without plex support giving out that info, but i can ask.

**Comment by Ockingshay** [comment]
does this help at all?

https://support.plex.tv/hc/en-us/articles/201242707-Plex-Media-Scanner-via-Command-Line

**Comment by fernandog** [comment]
@Ockingshay that what SR does:

This returns a list of Libraries and their ID:
/path/to/Plex\ Media\ Scanner --list
   29: Movies
   31: Music
   30: TV Shows

and update ID 30 in this case

**Comment by Ockingshay** [comment]
i'm not sure how i run Scanner as i have plex installed in unRAID and on console it doesn't recognise that command.

But what if one has multiple tv show categories?

TV Shows: Documentaries Series
TV Shows: TV Shows
TV Shows: Fitness DVDs
TV Shows: Kid's TV Shows

If running that command lists out unique section IDs then Sickrage isn't working properly, or if it just brings back a generic ID for all TV Show sections, plex isn't defining them at a deep enough level.

Hopefully plex gives a unique number for all 4 of those examples and sickrage can simply update that particular section.

**Comment by Ockingshay** [comment]
log shows:
2015-03-31 21:10:17 INFO     POSTPROCESSER :: Updating library for the Plex Media Server host: 192.168.0.3:32400

which is the same identic as if i click "update plex" on SR homepage. Are you sure SR is passing the correct command to plex?

**Comment by abeloin** [comment]
@Ockingshay The current notifications implementation as no way of knowing which sections to update when it post-process a file. So it look for all show section type in sections and update them.

It is possible to implement it but that is a feature request which will be considered.

Implementation: https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/notifiers/plex.py
Doc Reference: https://support.plex.tv/hc/en-us/articles/201638786-Plex-Media-Server-URL-Commands

**Comment by Ockingshay** [comment]
ok, lovely...at least it's possible and not currently broken,

**Comment by Thraxis** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1764

Should be only updating TV now... and if passed an epObj only updating Section that episode is found in.  Currently it always calls for full library.  Would need to modify postProcessor to send the episode for only updating specific section.

**Comment by fernandog** [comment]
@Thraxis AFAIK SR get the id of library that has "show" and update only that:

https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/notifiers/plex.py#L238

**Comment by Thraxis** [comment]
@fernandog It gets all of the sections of type "show" that could be 1 or 12.. it then checks to see if an epObj had been passed and the file location set.  If it has it then tries to eliminate all sections except the one that could contain that episode and then sends an update for just that section.

We just don't happen to have a call that sends the epObj (ie. from postProcessor.py ) for it to use the functionality right now.

**Comment by Thraxis** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1825
