### ISSUE TITLE
Error while searching NextGen, skipping

### ISSUE THREAD

**Issue by lthasenhod** [SiCKRAGETV/sickrage-issues#1079]
Branch: master

Commit hash: e28f73f73048ce2e2a6c8a13aab0aa5ac7915c27

Your operating system and python version: Synology DSM 5.1-5022 Update 4 / Python 2.7.8-11

What you did: nothing after a commit it stopped working (Error while searching NextGen, skipping)

What happened: Error while searching NextGen, skipping

What you expected: finding the tv shows that searched manually and found.

Link to a copy/paste of your logfile with clear debug info of the error on GIST:
2015-03-31 13:11:48 SEARCHQUEUE-BACKLOG-82459 :: Torrent file content is empty
2015-03-31 13:11:28 SEARCHQUEUE-BACKLOG-79824 :: [NextGen] :: Error while searching NextGen, skipping: 疾
2015-03-31 13:11:28 SEARCHQUEUE-BACKLOG-79824 :: No NZB/Torrent providers found or enabled in the sickrage config for backlog searches. Please check your settings.

and i checked that debug = 1 in the config.ini

Kind Regards,
lthasenhod

**Comment by fernandog** [comment]
@lthasenhod follow guidelines:
**Link to a copy/paste of your logfile with clear debug info of the error on GIST**

FULL log, that's why we as to upload to GIST

**Comment by fernandog** [comment]
@lthasenhod torrent name is just "疾" ?

**Comment by lthasenhod** [comment]
Hi Fernando,

 

I do not know where that chinese sign comes from, i only use sickrage on nxtgn, and thats a danish site.

 

I will try read up on how to do the GIST stuff when I wake up tomorrow.

 

/lthasenhod

**Comment by lthasenhod** [comment]
Just close the case, i uninstalled sickrage, logged into the synology with root access and removed everything sickrage related, and then reinstalled it, and updated it with the commits, and now it works flawlesly again, thank you.

/lthasenhod
