### ISSUE TITLE
Feature Request: Add new field to the shows screen

### ISSUE THREAD

**Issue by antron12345** [SiCKRAGETV/sickrage-issues#1080]
If it could be done just like you have on the Main "Shows List" window the option to add a field "Select Column" button.  it would be nice to have fields added to the actual show window.  The column that I am interested in is the "Show File Name" something to the effect of

American Dad! - s06e11 - A Jones for a Smith - HD TV.mkv

Thank you

**Comment by abeloin** [comment]
There's already a FR for that. You can also get the filename if you leave your mouse cursor for a few seconds on the episode number.
![Imgur](http://i.imgur.com/096o0Us.png)

**Comment by abeloin** [comment]
Duplicate of https://github.com/SiCKRAGETV/sickrage-issues/issues/1015
