### ISSUE TITLE
Enter on Add Existing Show in Search = Page Not Found / Invalid Request / Auto Pick First

### ISSUE THREAD

**Issue by AppliedEllipsis** [SiCKRAGETV/sickrage-issues#1081]
When I was adding my existing show folders, migrating from SickBeard, I found that on the search options, if a show didn't match, that when I pressed enter instead of the search button, it would search and then redirect the page to invalid parameters, page not found.

I suspect a return false is not being thrown by JS or an error is occurring prior to it returning false on the form submit.

This does not occur when adding a show normally, only when adding existing show.

There are 2 bugs:
1)
Steps to replicate:
Create a fake show folder and add exiting show
$  mkdir Testing
Goto Shows Menu -> Add Existing Shows
Make sure your show is selected
Submit
Under search, type anything and press enter.
It will redirect back to home after searching and add the show with a default value found.

2)
Steps to replicate:
Start from a fresh install
Create multiple fake show folders and add exiting show
$  mkdir Testing
$  mkdir Testing2
Goto Shows Menu -> Add Existing Shows
Make sure your shows are selected
Submit
Under search, type anything and press enter.
It will display an error about something not being submitted properly on a very basic, non-themed page.

Expected result in both cases is as normally adding shows and pressing Enter or hitting the search button.

Tested with latest branch as of 2015/04/01 at 2am est.

**Comment by MGaetan89** [comment]
I just tried both scenarios but I don't have any issue (tested with the latest development version).
Can you confirm that you are still facing this problem?

**Comment by fernandog** [comment]
@AppliedEllipsis do you still have this issue?
