### ISSUE TITLE
Problem after updating

### ISSUE THREAD

**Issue by DanielV88** [SiCKRAGETV/sickrage-issues#1082]
Hello,

I have had a problem with updating my SickRage. I followed the FAQ on this GitHub and updated with the following:

On Synology:

Stop SB using Syno package tool
Remove current sourcecode
cd /volume1/@appstore/sickbeard-custom/var
rm -Rf SickBeard
Fresh clone **/volume1/@appstore/git/bin/git clone https://github.com/echel0n/SickBeard-TVRage.git SickBeard
Start SB using Syno package tool
Enjoy!
_____

But now I have errors when checking for a new update:

2015-04-01 11:16:42 Thread-68 :: git config remote.origin.url https://github.com/SiCKRAGETV/SickRage.git returned : error: could not lock config file .git/config: Permission denied, treat as error for now
2015-04-01 11:16:42 Thread-68 :: git fetch origin returned : error: cannot open .git/FETCH_HEAD: Permission denied, treat as error for now
2015-04-01 11:16:42 Thread-68 :: Unable to contact github, can't check for update

Does anyone know how to resolve this? I also used the function in SickRage to submit the errors, but i'm not really known with GitHub so excuse me if I'm doing something wrong.

**Comment by abeloin** [comment]
You need to give permission to the user running sickrage to have write access to the file

**Comment by DanielV88** [comment]
I installed this in my Synology NAS with the package, so I'm not very known with the directory structure of Git and/or SickRage. Can you please explain how I should do this? 

I changed permission on /volume1/@appstore/sickbeard-custom/var/SickBeard/.git on the files config en HEAD to 755. But this doesn't resolve the issue.

SickRage seems to be running under the SickBear account. But the permissions on the files are for user root and group root.

**Comment by fernandog** [comment]
@neoatomic help?

**Comment by DanielV88** [comment]
Never mind, case closed.

I did a chmod chown -R 104 SickBeard at /volume1/@appstore/sickbeard-custom/var/ and that did the trick!~

After this command SickRage immediately said I was 2 commits behind and I had no problems updating.
