### ISSUE TITLE
update does not work anymore

### ISSUE THREAD

**Issue by BenjV** [SiCKRAGETV/sickrage-issues#1084]
BRANCH: (master) / COMMIT: (33921ecd1697f99ef47015c700331358481c9b98) 

Yesterday I did an update and all went fine.
Today there was a new update available with one commit and I tried the update and it failed to update.
SickRage is still function but won't update.
Log entry below:

2015-04-01 12:06:31 WARNING  Thread-90 :: Please enable 'git reset' in settings or stash your changes in local files
2015-04-01 12:06:12 INFO     Thread-90 :: Config backup successful, updating...
2015-04-01 12:06:00 INFO     Thread-90 :: Config backup in progress...

**Comment by arejaytee** [comment]
Also experiencing this

**Comment by TagForce** [comment]
Stop SickRage
Go into your SR install folder and perform the following actions:
```
git fetch origin
git reset --hard origin/master (or origin/develop if you're on develop)
```

That should fix it. And a fix for this was introduced, so it should'nt happen again.

**Comment by BenjV** [comment]
Thanks worked like a charm.
For anybody who is using an Synology (like me)
Log in with putt
Go to the this directory:
/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard
Give these commands:
/volume1/@appstore/git/bin/git fetch origin
/volume1/@appstore/git/bin/git reset --hard master
