### ISSUE TITLE
Cannot submit errors to GitHub

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#1085]
BRANCH: (develop) 
COMMIT: (eb96b3a1d62dd47f9cbb613edd9d1caba30e04f7) 
Python : 2.7.8 
OS :  Ubuntu 14.10
Debug log :http://pastebin.com/GzVctQbY

When i try to send an error via the submit error button i get this error everytime 
"object of type 'exceptions.TypeError' has no len()"

**Comment by abeloin** [comment]
@matigonkas Please restart sickrage, as from the log i can see you updated without restarting SR.

**Comment by abeloin** [comment]
please update pr merged

**Comment by matigonkas** [comment]
Just updated but its still happening :/

**Comment by abeloin** [comment]
@matigonkas Please provide the logs

**Comment by matigonkas** [comment]
Debug log : http://pastebin.com/FG6wYWqZ

And in the view log(error) 

http://pastebin.com/ezLW8ZYG  the last 2 errors happened when i tryed to submit an error

**Comment by abeloin** [comment]
@matigonkas Why do you want to submit this error?
```
2015-04-01 19:28:13 SEARCHQUEUE-MANUAL-40583 :: [TNTVillage] :: Error while searching TNTVillage, skipping: error ('Connection aborted.', gaierror(-2, 'Nome ou servi\xc3\xa7o desconhecido'))
```
It's telling you the name ou service is unknown, meaning it can find tntvilage in the dns(check your dns)

**Comment by matigonkas** [comment]
@abeloin no i dont what to submit that error ,the one i wanted isnt there anymore with all the sr restarts and what not

**Comment by abeloin** [comment]
@matigonkas Anyway pushed a fix if the error as no title
