### ISSUE TITLE
strange "Hawaii_Five-0" backlog problem?

### ISSUE THREAD

**Issue by mfrelink** [SiCKRAGETV/sickrage-issues#1086]
BRANCH: (master)
COMMIT: (e28f73f73048ce2e2a6c8a13aab0aa5ac7915c27)
OS: Linux iNas 3.10.35 #5532 SMP Wed Mar 11 12:09:56 CST 2015 x86_64 GNU/Linux synology_cedarview_1512+
Python Version: 2.7.9 (default, Mar 23 2015, 00:07:04) [GCC 4.7.3 20130102 (prerelease)]

I added a new show (Bones), but other than downloading the show info, it didn't go downloading anything.
I discovered it didn't had anything to do with this specific show, anything I add doesn't download.
It just started doing this today. I updated to the last sickrage version 2 days ago.

I was expecting it would download Bones episodes ;)

Super special bonus: I don't have Hawaii Five-O added to my shows!

Log:
https://gist.github.com/mfrelink/699ca18acc239d884465

Update, extra info: when I add a new show, it does -not- download the show info (I forgot). It does do that when I select "Force Full Update".
My own interpretation is that it has something to do with tvrage.

**Comment by abeloin** [comment]
Look at the show scene exceptions, is it empty?

**Comment by mfrelink** [comment]
Any show I add and have, the scene exception is empty. 
Am I suppose to add Hawaii_Five-0 to the show?

Also, I have this with any new show I add. No problem for me to add Hawaii_Five-0 to the scene exceptions but is this expected behaviors? (I really have no idea what this does)

**Comment by abeloin** [comment]
I think something is up with thexem.de service, I'm currently debugging

**Comment by mfrelink** [comment]
At least I now know I'm not seeing ghosts :) 
If there's anything I can do, I'm more than happy to help with info.

**Comment by ddmf** [comment]
I'm seeing the same thing, can't download anything automatically:

2015-04-01 21:25:23 INFO     SEARCHQUEUE-BACKLOG-285328 :: Checking for XEM scene exception updates for TVRage
2015-04-01 21:25:18 INFO     SEARCHQUEUE-BACKLOG-285328 :: Checking for XEM scene exception updates for theTVDB
2015-04-01 21:25:18 INFO     SEARCHQUEUE-BACKLOG-285328 :: Beginning backlog search for: [Play It Again, Dick]
AA
AAValueError: invalid literal for int() with base 10: 'Hawaii_Five-0'
AA    xem_exception_dict[int(indexerid)] = names
AA  File "/home/markr/.sickbeard/sickbeard/scene_exceptions.py", line 309, in _xem_exceptions_fetcher
AA    _xem_exceptions_fetcher()
AA  File "/home/markr/.sickbeard/sickbeard/scene_exceptions.py", line 203, in retrieve_exceptions
AA    sickbeard.scene_exceptions.retrieve_exceptions()
AA  File "/home/markr/.sickbeard/sickbeard/name_cache.py", line 91, in buildNameCache
AA    sickbeard.name_cache.buildNameCache(show)
AA  File "/home/markr/.sickbeard/sickbeard/search.py", line 438, in searchProviders
AA    searchResult = search.searchProviders(self.show, self.segment, False)
AA  File "/home/markr/.sickbeard/sickbeard/search_queue.py", line 221, in run
2015-04-01 21:25:11 INFO     SEARCHQUEUE-BACKLOG-281535 :: Checking for XEM scene exception updates for TVRage
2015-04-01 21:25:06 INFO     SEARCHQUEUE-BACKLOG-281535 :: Checking for XEM scene exception updates for theTVDB
2015-04-01 21:25:06 INFO     SEARCHQUEUE-BACKLOG-281535 :: Beginning backlog search for: [Forever (2014)]
AA

**Comment by abeloin** [comment]
@mfrelink @ddmf Please update your branch

**Comment by mfrelink** [comment]
Omg, you fixed it already! Updated and I can see in the logs Hawaii Five-O is a rejected entry and Bones episodes are downloading and adding new shows work again. 
Thanks!!

**Comment by ddmf** [comment]
Thanks very much!
