### ISSUE TITLE
Request: preferred words

### ISSUE THREAD

**Issue by Ockingshay** [SiCKRAGETV/sickrage-issues#1087]
In search settings there are options for ignored and required words. Could there be a preferred section as well, so that we could rank the search results instead of sr picking the first search that satisfies it's criteria?

Becomes particularly noticeable when one is searching for older season packs that has several results to choose from and it doesn't always pick the correct one.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/461

**Comment by Ockingshay** [comment]
thanks
