### ISSUE TITLE
[APP SUBMITTED]: Unable to extract title from error

### ISSUE THREAD

**Issue by thecolorchanges** [SiCKRAGETV/sickrage-issues#1088]
### INFO
Python Version: **2.6.5 (r265:79063, Jul 24 2010, 21:39:31) [GCC 4.2.3]**
Operating System: **Linux-3.0.3-unRAID-i686-AMD_Athlon-tm-_II_Neo_N36L_Dual-Core_Processor-with-slackware-13.1.0**
Locale: UTF8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@a6d4ae61cef2fba0cdb6ab18f301c19dfaea5244
Link to Log: https://gist.github.com/52ba193581509ea6e5cb
### ERROR
```
Thread-16 :: Failed doing webui callback: Traceback (most recent call last):
  File "/mnt/scratch/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/mnt/scratch/SickRage/sickbeard/webserve.py", line 2140, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/mnt/scratch/SickRage/sickbeard/processTV.py", line 203, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/mnt/scratch/SickRage/sickbeard/processTV.py", line 504, in process_media
    result.result = processor.process()
  File "/mnt/scratch/SickRage/sickbeard/postProcessor.py", line 899, in process
    if not verify_freespace(self.file_path, ek.ek(os.path.dirname, ep_obj.show._location), [ep_obj] + ep_obj.relatedEps):
  File "/mnt/scratch/SickRage/sickbeard/helpers.py", line 1517, in verify_freespace
    if os.path.isfile(file.location):
  File "/usr/lib/python2.6/genericpath.py", line 29, in isfile
    st = os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 89: ordinal not in range(128)

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by thecolorchanges** [comment]
Was Trying to process "The Walking Dead - What Happened and What’s Going On" all other episodes downloaded fine, it appears to be just an issue with the " 's " .

**Comment by abeloin** [comment]
PR merged

**Comment by abeloin** [comment]
@thecolorchanges Please update and let us know

**Comment by thecolorchanges** [comment]
Updated to latest commit, deleted failed.db and restarted. Downloaded the exact same copy and the issue is resolved. No issue in post processing. Ok to close, Thanks for the commit!
