### ISSUE TITLE
[Feature Request] Persist search queue across restarts

### ISSUE THREAD

**Issue by tjw1184** [SiCKRAGETV/sickrage-issues#1089]
Had a problem with the searchqueue-retry locking up, but it appears that was taken care of in issue  #1086.  Due to that issue, I had numerous failed downloads and partway through a backlog search that was lost when I updated the code and restarted sickrage (queues didn't persist).  Would it be possible to persist these queues across restarts (so in the future I don't have to try and compare sabnzbd failed entries to sickbeard and try to figure out the episodes I need to manually mark as bad)?

**Comment by fernandog** [comment]
@abeloin  @TagForce did you get it? feature request fix or won't fix?

**Comment by TagForce** [comment]
@fernandog Yeah... I think this will be solved once we get the download client api's sorted and actually check for stale and failed downloads in the actual clients every X minutes.

Don't know if @abeloin has any ideas about this. Saving the queues might be a little problematic.

**Comment by abeloin** [comment]
@TagForce @fernandog When a download is PP'ed as failed it doesn't reset it status to WANTED?

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
