### ISSUE TITLE
Webpage not available

### ISSUE THREAD

**Issue by kendog819** [SiCKRAGETV/sickrage-issues#1092]
Was using the most current master before everyone was having the update problems.
Qnap TS-451 - Python Version: 2.7.3 (default, Apr 12 2012, 20:25:04) [GCC 4.2.1]

I was attempting to fix the error with the fix Clinton.Hall provided on the qnap forums.
http://forum.qnap.com/viewtopic.php?f=223&t=35015&p=474814#p474814 

Prior to applying the fix, I (attempted to) shutdown Sickrage from within the GUI by clicking the shutdown link. It just sat there for minutes spinning, not really doing anything. I clicked the sickrage logo to return me to the home screen, and it took me to a page unavailable screen.

I have restarted my nas, and still same issues. Cannot get sickrage to run.

Tried doing the fix as suggested as well, image below.
![putty](https://cloud.githubusercontent.com/assets/11353628/6958077/4b5fb0fc-d8d4-11e4-90cf-d7a74725f5f0.JPG)

Here is the last few entries from my sickrage.log:

2015-04-01 23:39:04 DEBUG    EVENT-QUEUE :: 248742: Saving show info to database
2015-04-01 23:39:05 DEBUG    EVENT-QUEUE :: 265052: Saving show info to database
2015-04-01 23:39:05 DEBUG    EVENT-QUEUE :: 248841: Saving show info to database
2015-04-01 23:39:05 DEBUG    EVENT-QUEUE :: 262980: Saving show info to database
2015-04-01 23:39:05 DEBUG    EVENT-QUEUE :: 281622: Saving show info to database
2015-04-01 23:39:05 DEBUG    EVENT-QUEUE :: 283317: Saving show info to database
2015-04-01 23:39:06 DEBUG    EVENT-QUEUE :: 70682: Not saving show to db - record is not dirty
2015-04-01 23:39:06 DEBUG    EVENT-QUEUE :: 76321: Not saving show to db - record is not dirty
2015-04-01 23:39:06 INFO     EVENT-QUEUE :: Saving config file to disk
2015-04-01 23:39:06 INFO     EVENT-QUEUE :: Shutting down Tornado

Any help is appreciated,
Ken

**Comment by TagForce** [comment]
Try:
Stop SR, and go into your SR folder:
```
git fetch origin
git reset --hard origin/master
git pull
```

**Comment by kendog819** [comment]
@TagForce 

How do I stop it? I can't access SR. Thinking I may need help with that before getting rid of the update issue :-/
![image](https://cloud.githubusercontent.com/assets/11353628/6960271/ec741d92-d8ee-11e4-9c94-bd8ac19155db.png)

**Comment by abeloin** [comment]
@kendog819 From the ssh console:
* First we need to know on which branch you are(It's the one with the asterisk):
`git branch`
* Fetching the latest change:
`git fetch`
* Reseting the local changes(if the selected branch is develop, replace master with develop):
`git reset --hard origin/master`
* Try a git pull:
`git pull`

If still tell you that you have local changes:
* Try to remove the latest commit:
`git reset --hard HEAD^1`
* Try a git pull:
`git pull`

**Comment by kendog819** [comment]
![image](https://cloud.githubusercontent.com/assets/11353628/6969525/52bea9c0-d93d-11e4-8c2a-3bc35612a1ad.png)

Still "Page Unavailable" :(

**Comment by fernandog** [comment]
@kendog819 run "python SickBeard.py" and post the result messages/lon on screen

**Comment by kendog819** [comment]
@fernandog 

"The Python module Cheetah is required"

**Comment by abeloin** [comment]
@kendog819 You need to start it from your qnap ui

**Comment by kendog819** [comment]
@abeloin 

Start what? I am getting very confused here now. 

Here is where I am at.

I still cannot open SlickRage. 

![image](https://cloud.githubusercontent.com/assets/11353628/6975977/52f02b9c-d971-11e4-809e-da5030b6e58d.png)
 When I click open there, it just takes me to:
![image](https://cloud.githubusercontent.com/assets/11353628/6975983/6c1b37ce-d971-11e4-8efa-24902df1d7f9.png)

I am unsuccessful in running "python SickBeard.py" even after installing cheetah (which i'm not even sure if I did install)

![image](https://cloud.githubusercontent.com/assets/11353628/6976017/a8d1fb9e-d971-11e4-8cc3-be3269bb9885.png)

**Comment by abeloin** [comment]
Nothing in your qnap log?

**Comment by kendog819** [comment]
I just got cheetah installed, one second. Its creating log

**Comment by abeloin** [comment]
You should have a script in /etc/init.d/ called something like sickbeard.sh, sickbeard-tvrage.sh.
Try starting manually:
`/etc/init.d/sickbeard.sh start`

**Comment by kendog819** [comment]
Seems SR is still running, I just cant acess the GUI.

https://gist.github.com/kendog819/a0a33503d4ad3b37fff2

Trying to find "/etc/init.d/ " right now

**Comment by kendog819** [comment]
I have no idea how to run commands from the qnap. I've just been using putty.

**Comment by kendog819** [comment]
No sickrage files in init.d

![image](https://cloud.githubusercontent.com/assets/11353628/6976245/d9f943e6-d974-11e4-8cb1-158ff49075ac.png)

**Comment by abeloin** [comment]
try `ps -eaf | grep -i python` it should list all python process, try to find the one from sickrage

**Comment by kendog819** [comment]
![image](https://cloud.githubusercontent.com/assets/11353628/6976326/1fd96c96-d976-11e4-8adb-7c509a4ad346.png)

**Comment by kendog819** [comment]
If you'd like to teamview me @abeloin, I can give you access. May make this easier, as I'm so green.

**Comment by abeloin** [comment]
@kendog819 Ok

**Comment by kendog819** [comment]
Is there a way of me PM'ing you?

**Comment by abeloin** [comment]
On [the forum](https://sickrage.tv/forums/), username funkylove

**Comment by kendog819** [comment]
Sent :)

**Comment by abeloin** [comment]
Received and connecting...

**Comment by abeloin** [comment]
@kendog819 Got disconnect from internet. The file I installed is newer that the one you add before. You should reinstall the qpkg. Make a backup of the folder /share/CACHE1DEV_DATA/.qpkg/SickBeard-TVRage on your PC first

**Comment by kendog819** [comment]
Whatever u did got SR to work, But thesame thing happened when I went to shutdown. It never shut down. I clicked on something else, and it took me back to webpage being unavailable again.

**Comment by kendog819** [comment]
You can reconnect using the same ID + PW I sent you before if you would like.

**Comment by abeloin** [comment]
Yes, but since the sickbeard-tvrage.sh is newer than the one you add before it's causing issue. This is why you need to do a backup and reinstall sickrage.

**Comment by kendog819** [comment]
Do I just reinstall over the old copy? Or do I need to uninstall somehow 1st?

**Comment by abeloin** [comment]
I'm not sure. Try to reinstall over but do a backup first

**Comment by abeloin** [comment]
Are you ok to do the reinstall on your own? If not we can continue tomorrow afternoon as I have to be up at 4am and it's already 10:50pm.

**Comment by kendog819** [comment]
I'll try it, buddy. I'll keep you posted. Thanks so much for the help.

**Comment by kendog819** [comment]
![image](https://cloud.githubusercontent.com/assets/11353628/6978144/78f07080-d99a-11e4-8c37-a546f8032f77.png)

I'm still unable to shut down from within the GUI. It freezes me and takes me to page unavailable. This new qpkg has an on off button though, which seems to reset it.

**Comment by kendog819** [comment]
Anyone out there? =)

![image](https://cloud.githubusercontent.com/assets/11353628/6986154/983f5816-da08-11e4-9202-2089cc982cfd.png)


@abeloin 
@fernandog 
@TagForce

**Comment by abeloin** [comment]
After you load the page with the github info, check in SR log you should see why it doesn't show any branches.

**Comment by kendog819** [comment]
@abeloin 

![image](https://cloud.githubusercontent.com/assets/11353628/6987775/05e7846e-da19-11e4-8cd0-259460ef6322.png)

I'm also having issues with post processing now =(

You want to teamview me again? =)

**Comment by abeloin** [comment]
Pm me on SR forum with the info

**Comment by kendog819** [comment]
Sent :)

**Comment by abeloin** [comment]
@kendog819 Closing the issue
