### ISSUE TITLE
Push notifications get sent twice, but only the 'started' ones

### ISSUE THREAD

**Issue by dogeatdog** [SiCKRAGETV/sickrage-issues#1093]
BRANCH: (master) / COMMIT: (568421b27a7940bfdebfef1be5f2b121d8a00b8f) 
I have a notification set up via Push for SR started and finished downloads. This used to work great, but lately I've been getting duplicate (as in : same sent time of the notification) started notifications. Only the started notifications are duplicate, the finished are sent once as they should be.
![bestand 02-04-15 10 37 38](https://cloud.githubusercontent.com/assets/11708786/6960603/5af44622-d924-11e4-8ebc-eea40596fa4e.png)

I don't know what's causing this, and it doesn't happen on all shows/episodes. Tried turning notifications off and on, didn't help. Known bug ?

**Comment by dogeatdog** [comment]
I'll set up debug logging and check in the morning, there are bound to be new shows being downloaded then☺

**Comment by fernandog** [comment]
@dogeatdog please send a print of your pushover settings

**Comment by dogeatdog** [comment]
![schermafdruk 2015-04-02 22 15 25](https://cloud.githubusercontent.com/assets/11708786/6972716/eb43785e-d985-11e4-823a-9489fb995fa6.png)

**Comment by fernandog** [comment]
@dogeatdog
Did you downloaded any proper? Check history tab

**Comment by dogeatdog** [comment]
Ok, just to be clear. I just shut down Sickrage. Set the debug to 1 in config.ini. Restarted the service. 
Got a : 'start: Job is already running: sickrage', which was odd. Went back to Sickrage and now it said I was 331 commits (or something along that line) behind, so I updated. And now I'm on BRANCH: (master) / COMMIT: (ff7aee90fd26db93cc571be1cb5c62a6fcf08e19) .

![schermafdruk 2015-04-02 22 23 13](https://cloud.githubusercontent.com/assets/11708786/6972873/e4e96dd2-d986-11e4-9fcd-1ebac7cb4456.png)

**Comment by dogeatdog** [comment]
Noticed it's reacts incredibly slow right now, but that's probably the debug logging, that and the scanning everything on restart .. 

Anyway, debug logging is on, so I'd hopefully have some better logging for you guys in the morning. 

![schermafdruk 2015-04-02 22 26 35](https://cloud.githubusercontent.com/assets/11708786/6972959/7062ae0a-d987-11e4-850d-788b0a4a4be6.png)

**Comment by dogeatdog** [comment]
Good morning all ! 
There were a few downloads this night, but coincidence, bugfix (after all, running a new version now) or something to do with the weird shutdown message, but no duplicate finished notifications this night. 

![bestand 03-04-15 06 18 33](https://cloud.githubusercontent.com/assets/11708786/6977978/4a5dbd34-d9c9-11e4-80eb-6b7ef9105d19.png)

So, just turned off the debug parameter and restarted Sickrage again. Will be keeping a close eye and as soon as it reoccurs I'll report back in this thread.

Thanks for now !
