### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'Hawaii_Five-0'

### ISSUE THREAD

**Issue by suprdave23** [SiCKRAGETV/sickrage-issues#1095]
When manually searching for an episode, I am getting these errors in the log file:

http://pastebin.com/fZG6hz1E

This is with a dev pull from a couple of weeks ago.

**Comment by fernandog** [comment]
@suprdave23 please update to get the lasted SR and post branch version and all info as in guidelines:
https://github.com/SiCKRAGETV/sickrage-issues/

**Comment by suprdave23** [comment]
Well I'll be darned, didn't expect it but updating to latest commit did resolve the issue. I noticed a missing feature though that was in my previous build, I'll open a different ticket about it. Thanks!
