### ISSUE TITLE
"Minimum logging level to display" no longer has Debug as an option

### ISSUE THREAD

**Issue by suprdave23** [SiCKRAGETV/sickrage-issues#1096]
After updating my build to the latest commit today, the "Minimum logging level to display" seems to have Db and Debug removed. I used this option to be able to look at Debug messages without having to stop Sickrage and open the log file. Can we have this added back in?

**Comment by fernandog** [comment]
Please SEARCH before open issue

**Comment by suprdave23** [comment]
@fernandog Thanks, but unfortunately that's not super helpful given that I have already searched and not found anything except for an open ticket in February. If I need to mention "I have already searched" before opening tickets I can do so....

So with that in mind, and given the amount of "legit" bug reports I have fed back to you guys to help make this product better, can you please point me in the right direction of how to get these drop down options back? 

Thank you! :)

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1077

**Comment by suprdave23** [comment]
Thank you!
