### ISSUE TITLE
Torrentz.eu as extra provider

### ISSUE THREAD

**Issue by topper2830** [SiCKRAGETV/sickrage-issues#1099]
dear,
can you please merge the provider torrentz.eu
in other forks this one exists.
I tried to add it manualy with the py file from other fork but didn't work.
can you please assist ? or merge it ?
I tried the py file from sickbeard 1080p subtitles

kind regards

ps: can't getit added in custom provider tab

**Comment by abeloin** [comment]
Already requested: https://github.com/SiCKRAGETV/sickrage-issues/issues/874

**Comment by topper2830** [comment]
ok , it says 24 days ago in the dev but its not yet visible in the master ? any expectance date ?

**Comment by abeloin** [comment]
@topper2830 I don't know were you get your info that torrentz.eu is implemented in dev but it isn't. It is still a feature request.

**Comment by topper2830** [comment]
fernandog added this to the Dev 4.4.0 Provider Features milestone 25 days ago

**Comment by abeloin** [comment]
It's a future milestone as SR is at version 4.0.16
