### ISSUE TITLE
[Feature Request] Could permissions setting on destination be optional

### ISSUE THREAD

**Issue by tpihl** [SiCKRAGETV/sickrage-issues#110]
I have my finished downloads on a SMB share and every time SickRage try to change permission on a file i recieve an error. Just a config parameter to either hide the fact or not even try to set owner and permissions.

**Comment by Vodka2014** [comment]
So i just got this as well. I copied a file to a Windows Machine. then back to my Synology NAS then used SickRage to process it.

What am i missing here. Do i need the chmod all my files on my nas to 666 before i process it in SickRage ?

**Comment by abeloin** [comment]
Sickrage user need to be the file owner to be able to change the permissions

**Comment by Vodka2014** [comment]
So that will be Administrator by Default correct ?

**Comment by abeloin** [comment]
Depend on where sickrage is installed, nas or windows?

**Comment by Arcanemagus** [comment]
I'm unsure if Synology NAS's use an ACL aware file system, but at least on FreeNAS if the dataset type is set to Windows (Meaning ACL is enabled) then setting permissions with a simple chmod will fail regardless of the basic permissions on the file.

So even if SickRage is running as the owner this may still fail depending on your setup.

**Comment by Vodka2014** [comment]
thanks. the main thing is it still processes with no issues just gives this error,

**Comment by abeloin** [comment]
If it's on the nas, you need to set the samba permissions to always create your file as the same user(nas user). This way when sickrage try a chmod it will succeed as it is the owner.

**Comment by Arcanemagus** [comment]
@abeloin unless, as I said, it is using ACL permissions in which case no matter who the owner is a simple chmod will fail.

    [root@nas] /mnt/vol/public# touch test
    [root@nas] /mnt/vol/public# chmod 666 test
    chmod: test: Operation not permitted

If the system is using this setup permissions need to be specified using `setfacl`. I have my own system configured so that everyone has full permissions on the public directory no matter what so it isn't really an issue for me, other than creating the error from https://github.com/SiCKRAGETV/sickrage-issues/issues/110#issuecomment-67289312 every time a file is processed.

**Comment by abeloin** [comment]
@Arcanemagus If I remember correctly this is only applicable to zfs dataset with aclmode set to windows not to other file system that use ACL.
This is the result on Linux XFS:
```
[abeloin@core done]$ touch test
[abeloin@core done]$ chmod 666 test
[abeloin@core done]$ getfacl test
# file: test
# owner: abeloin
# group: media
user::rw-
user:root:rwx                   #effective:rw-
group::rwx                      #effective:rw-
group:media:rwx                 #effective:rw-
mask::rw-
other::rw-
```

**Comment by Arcanemagus** [comment]
@abeloin Score one for XFS ;)

**Comment by Vodka2014** [comment]
Stupid Question: How to i set this up on my Synology NAS since it has Admin rights to the shares. So it moves it from OpeneElec / SickRage to my NAS.

**Comment by abeloin** [comment]
@Vodka2014 I would set these value in samba config file in the share section:
```
   force user = rolf
   force group = coders
```
this way any user connecting to the share will create files as the sickrage user and group thus ensuring you have the proper permissions.

**Comment by Vodka2014** [comment]
@abeloin thanks now lets see if Synology will be so nice and let me edit the files.

**Comment by fernandog** [comment]
@Vodka2014 did it worked? can we close it?

**Comment by Arcanemagus** [comment]
@fernandog should I open a separate issue for FreeNAS installs if you want to close this one? On FreeNAS on a dataset that has Windows (ACL) permissions this command no matter what fails so this option would be very useful on that setup.

**Comment by fernandog** [comment]
@TagForce is something that we can fix or we give an option to disable?

**Comment by Vodka2014** [comment]
Well i did not find the settings to change this. If someone can give me a how to then maybe i can give it a go. it still process the files.

**Comment by TagForce** [comment]
@fernandog Option to disable is easy. We could check for an error on setting permissions and try something else if that fails. But I'll have to research it.

**Comment by xInsertx** [comment]
What about using setfacl instead? Copy/Move the file than you can set (@)owner/(@)group with inheritance from parent?

In my request #1254 i run a separate bash script afterwards on each file which runs setfacl for owner/group with inheritance from parent.

**Comment by TagForce** [comment]
@xInsertx setfacl is an external command, and I want to refrain from using external commands as much as possible for security reasons.

I'm looking at something that when chmod fails reverts back to using a different command using ACLs to set the permissions...

**Comment by TagForce** [comment]
@xInsertx Unfortunately, the only way of setting the permissions from within python using ACL is by implementing the pyWin32 modules, which are, of course, only available on Windows... Since this issue is occuring only on smb mounts from non-Windows OSes (since chmodAsParent will exit cleanly on windows without setting permissions), that is not an option.

So, there's no other option than to try and set the permissions using setfacl. Unless @abeloin or @miigotu  have another idea.

**Comment by Arcanemagus** [comment]
@TagForce this isn't _just_ occurring over smb mounts, I run into this with the native filesystem on FreeNAS when the system is set to use Windows ACLs. That doesn't really change the fact that to do this properly alternative methods of setting the permissions will need to be used though :wink:.

**Comment by xInsertx** [comment]
@Arcanemagus I think this will occur on any filesystem using essentially ntfs permissions (POSIX acl's) on non-windows platform. I've tested this now on many setups and the only common demoninator.

This includes Freenas w/ Windows type dataset.

**Comment by exzacklyright** [comment]
Same issue. Post Processor runs fine but then it outputs this error.

**Comment by JeremiahGillis** [comment]
I also have this issue, the post processor runs fine. I am on FreeNAS.

@Arcanemagus Have you just been ignoring these errors?

**Comment by miigotu** [comment]
@JeremiahGillis @exzacklyright is it an error or just a warning now? Log?

**Comment by Arcanemagus** [comment]
@JeremiahGillis I've just been clicking ignore for every single one...

@miigotu It is still an error, it looks exactly the same as it has from the very start (https://github.com/SiCKRAGETV/sickrage-issues/issues/110#issuecomment-67289312).

**Comment by miigotu** [comment]
imo, we should not be setting permissions at all, even when creating a folder.

```bash
miigotu@PC:~/Projects/SickRage $ mkdir try
miigotu@PC:~/Projects/SickRage $ ls -ld try
drwxrwxr-x 2 miigotu miigotu 4096 Jul 12 17:51 try
miigotu@PC:~/Projects/SickRage $ touch try/try.mp4
miigotu@PC:~/Projects/SickRage $ ls -l try
total 0
-rw-rw-r-- 1 miigotu miigotu 0 Jul 12 17:51 try.mp4
```

664 is the proper permissions for a file created by SR.
775 is the correct permissions for a folder created by SR.

These are the default settings, we shouldn't be trying to chown or chmod.

**Comment by miigotu** [comment]
@TagForce care to weigh in on that idea?

**Comment by Arcanemagus** [comment]
Sonarr's default is to not attempt setting permissions btw.

(SickRage is so much better in many functional aspects Sonarr's better UI isn't worth it to switch, although this has been annoying me for months.)

**Comment by miigotu** [comment]
I just don't see why we would ever need to set permissions. It is created with the SR user, so it should always be correct.

**Comment by JeremiahGillis** [comment]
@miigotu It is an error but it doesn't seem to have an adverse affect. The file is still renamed and moved to the correct folder. It will even create the folder if it is a new season.

2015-07-12 11:43:08 INFO     POSTPROCESSER :: Deleting folder (if it's empty): /media/Download/Defiance.S03E01-02.The.Last.Unicorn.720p.WEB-DL.DD5.1.H.264-ECI
2015-07-12 11:43:08 INFO     POSTPROCESSER :: Processing succeeded for /media/Download/Defiance.S03E01-02.The.Last.Unicorn.720p.WEB-DL.DD5.1.H.264-ECI/Defiance.S03E01-02.The.Last.Unicorn.720p.WEB-DL.DD5.1.H.264-ECI.mkv
AAOSError: [Errno 1] Operation not permitted: '/media/TV/Defiance (2013)/Season 03/Defiance.S03E01E02.The World We Seize & Last Unicorns.720p WEB-DL.mkv'
AA    result = func(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/encodingKludge.py", line 64, in ek
AA    ek.ek(os.chmod, childPath, childMode)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/helpers.py", line 617, in chmodAsParent
AATraceback (most recent call last):
2015-07-12 11:43:06 ERROR    POSTPROCESSER :: Failed to set permission for /media/TV/Defiance (2013)/Season 03/Defiance.S03E01E02.The World We Seize & Last Unicorns.720p WEB-DL.mkv to 664
2015-07-12 11:42:59 INFO     POSTPROCESSER :: Processing /media/Download/Defiance.S03E01-02.The.Last.Unicorn.720p.WEB-DL.DD5.1.H.264-ECI/Defiance.S03E01-02.The.Last.Unicorn.720p.WEB-DL.DD5.1.H.264-ECI.mkv (None)
2015-07-12 11:42:59 INFO     POSTPROCESSER :: PostProcessing Path: /media/Download

**Comment by miigotu** [comment]
Would it be ok if it just showed:
`2015-07-12 11:43:06 WARNING POSTPROCESSER :: Failed to set permission for /media/TV/Defiance (2013)/Season 03/Defiance.S03E01E02.The World We Seize & Last Unicorns.720p WEB-DL.mkv to 664`

warning instead of error and no traceback?

**Comment by miigotu** [comment]
or, I could make that a debug line so you see nothing at all

**Comment by miigotu** [comment]
Thats what I'm gonna do, debug instead of error, and pass on the exception.

**Comment by miigotu** [comment]
http://lmgtfy.com/?q=EAFP+Python

**Comment by JeremiahGillis** [comment]
Sounds good to me. All of my permissions seem right so far. I am glad I found this thread as I am new to NAS and SR. Thanks for your help @miigotu

**Comment by miigotu** [comment]
I'm gald you found this thread also, rather than opening a new one! Happy to help.

**Comment by Arcanemagus** [comment]
That's a perfectly valid solution for me as well, thanks @miigotu!

**Comment by miigotu** [comment]
I think the ERROR and traceback was initially intended to let us know if the code was not working as expected while it was being implemented. Now that we know it always works, except on systems where it  is not possible to chmod, there is no need for an ERROR to alert us, but a DEBUG line in case it ever does have a real issue is helpful.

Just glad to knock another issue down.
