### ISSUE TITLE
Download highest seeds instead of best quality when Quality is set to "Any"

### ISSUE THREAD

**Issue by suprdave23** [SiCKRAGETV/sickrage-issues#1100]
It seems like when quality for a show is set to "Any", SR finds the best quality it can to download instead of the version with the highest seeds. Is there an option to change this behavior to just grab the one with the highest seeds, irrespective of the quality when the quality is set to "Any"?

If you need logs of this behavior I can provide them.

**Comment by apoapostolov** [comment]
I would definitely prefer your suggestion over the current situation.

**Comment by abeloin** [comment]
@suprdave23 See my answer I gave you on March 2th in your FR https://github.com/SiCKRAGETV/sickrage-issues/issues/786#issuecomment-76758572
