### ISSUE TITLE
[APP SUBMITTED]: Error while searching EZTV, skipping: global name 'helpers' is not defined

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#1106]
### INFO
Python Version: **2.7.8 (default, Oct 20 2014, 15:05:29) [GCC 4.9.1]**
Operating System: **Linux-3.16.0-31-generic-i686-with-Ubuntu-14.10-utopic**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@9bc4d430aa98d2f07b45171bba4b1d6671eb3576
Link to Log: https://gist.github.com/ad43303b35d55225da01
### ERROR
```
FINDPROPERS :: [EZTV] :: Error while searching EZTV, skipping: global name 'helpers' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@abeloin do you know why issue submitter is not showing the error in title anymore?

**Comment by abeloin** [comment]
@fernandog Don't know why

**Comment by abeloin** [comment]
PR merged please update

**Comment by matigonkas** [comment]
@abeloin Updated and its now working ,thanks !
