### ISSUE TITLE
Add FILTER to shows home page

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#1112]
Something like this:

![image](https://cloud.githubusercontent.com/assets/2620870/6997141/20dcb6c2-db86-11e4-9bf9-1621f95bbf67.png)

http://tablefilter.free.fr/filter-sort.htm

**Comment by abeloin** [comment]
Table sorter already support this via the filter widget:
http://mottie.github.io/tablesorter/docs/index.html

**Comment by distracto** [comment]
I would like to see the ability to hide shows in the main show list. whether they are paused or ended or anything else.

**Comment by fernandog** [comment]
@Thraxis thanks!

**Comment by abeloin** [comment]
@Thraxis You can simply add `filter_hideFilters: true,` and set `filter_columnFilters: true,` and a grey bar will appear underneath the theader. On mouse over the filter will expand.

See demo http://mottie.github.io/tablesorter/docs/example-widget-filter.html

**Comment by Thraxis** [comment]
@abeloin That is what the code does.  I added an option to not include it as some might not want it popping up when their cursor is at the top of the table.  I also had to add the CSS code as without it the filter row doesn't hide when you move your cursor away

**Comment by abeloin** [comment]
@Thraxis My apologies, I saw the commit size and I guess you didn't use that method. Very sorry.
