### ISSUE TITLE
ThePirateBay wrong url

### ISSUE THREAD

**Issue by Xusqui** [SiCKRAGETV/sickrage-issues#1113]
Branch: Master (Sickbeard-custom)
Commit Hash: ff7aee90fd26db93cc571be1cb5c62a6fcf08e19
System: Synology DSM 5.2. (Synology DS214Play).
Python: Python: 2.7.9-13

I've noticed several errors in the log file when trying to access thepiratebay.se: error 104, connection reset by peer.

I wonder how could I change thepiratebay.se to thepiratebay.sl

Log file:
******************************
2015-04-05 14:40:46 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Connection error ('Connection aborted.', error(104, 'Connection reset by peer')) while loading URL https://thepiratebay.se/tv/latest/

**Comment by abeloin** [comment]
See:
* https://technet.microsoft.com/en-us/library/cc957018.aspx
* stackoverflow.com/questions/1434451/what-does-connection-reset-by-peer-mean

It mean the server is having some issue

**Comment by Xusqui** [comment]
Thank you... Anyway... Would it be difficult to change the url?

Thanks in advance!!

**Comment by abeloin** [comment]
Stop SR, open sickbeard/providers/thepiratebay.py change the corresponding url. To update SR you will need to revert the manual change and reapply them

**Comment by Xusqui** [comment]
Thank you. Will try tonight!
