### ISSUE TITLE
[Feature Request] Add Mass Update Option to set date of episode

### ISSUE THREAD

**Issue by Thraxis** [SiCKRAGETV/sickrage-issues#1116]
On systems that support this add a feature to mass update episodes to set file date of the episode to the original air-date.

Yes post processing has this feature.  But for a large collection that had not had this turned on in the past it would allow for this to be updated.

**Comment by fernandog** [comment]
@TagForce is this possible? I don't think it is to add this to mass update because there is no flag of this for tv-shows.

**Comment by TagForce** [comment]
@Thraxis @fernandog Yes, it is possible... It'll just mean that it will loop through each and every episode file to check and possibly set the file creation date to the correct one. No need for a flag, you select which shows you want to check, and it checks it.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
