### ISSUE TITLE
[APP SUBMITTED]: [Errno 5] Erro de Entrada/Saída de dados: '/media/ssd/Shows/Tori & Dean Cabin Fever/Season 01'

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#1118]
### INFO
Python Version: **2.7.8 (default, Oct 20 2014, 15:05:29) [GCC 4.9.1]**
Operating System: **Linux-3.16.0-31-generic-i686-with-Ubuntu-14.10-utopic**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@831f798ba1aa7e615401c08d45819bf4b403a6d9
Link to Log: https://gist.github.com/09425dac0a912dc3afe8
### ERROR
```
Thread-22 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/supergonkas/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/home/supergonkas/SickRage/sickbeard/webserve.py", line 1250, in displayShow
    return t.respond()
  File "/home/supergonkas/SickRage/cache/cheetah/_home_supergonkas_SickRage_gui_slick_interfaces_default_displayShow_tmpl.py", line 654, in respond
    _v = VFN(VFFSL(SL,"sickbeard.helpers",True),"pretty_filesize",False)(sickbeard.helpers.get_size(VFFSL(SL,"showLoc",True)[0])) # u'$sickbeard.helpers.pretty_filesize(sickbeard.helpers.get_size($showLoc[0]))' on line 246, col 46
  File "/home/supergonkas/SickRage/sickbeard/helpers.py", line 1412, in get_size
    total_size += ek.ek(os.path.getsize, fp)
  File "/home/supergonkas/SickRage/sickbeard/encodingKludge.py", line 58, in ek
    result = func(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
  File "/usr/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
OSError: [Errno 5] Erro de Entrada/Saída de dados: '/media/ssd/Shows/Tori & Dean Cabin Fever/Season 01'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@matigonkas check if your SSD is OK. can you read/write to it?

**Comment by matigonkas** [comment]
there was some kind of issue with my hard drives that i wasn`t able to even open them on ssh ,but a reboot solved the issue :)
Also would it be better if instead of the whole traceback just appeared the error with a little help tip like:
OSError: [Errno 5] Erro de Entrada/Saída de dados: '/media/ssd/Shows/Tori & Dean Cabin Fever/Season 01' (Please check your hard drives)
