### ISSUE TITLE
[Feature Request] Add EZRSS.ch torrent provider

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#1121]
The ezrss provider on sickrage its curretly set to use the ezrss.it url which is offline atm and as is ezrss.ch which is the official domain of EZTV (eztv.ch) atm when using the ezrss provider on SR it gets linked to eztv.it domain which is malicius (more info: https://torrentfreak.com/eztv-it-domain-compromised-by-scammers-150313/ ) 
My sugguestion is to either disable its atm as it is unusable or use this PR (https://github.com/SiCKRAGETV/SickRage/pull/1689) on the old ezrss provider isntead of the eztv new provider that is working .
Hopefully i was easy to understand ,but any question just ask ;)

**Comment by neoatomic** [comment]
@matigonkas As i dont use torrents what is the actual status of the eztv provider.? I think we removed it completely.? You still wont this added.?

**Comment by matigonkas** [comment]
nope @neoatomic dont want this anymore ,the website has been compromised
