### ISSUE TITLE
Some post processing methods disappeared in Windows!

### ISSUE THREAD

**Issue by bond-james** [SiCKRAGETV/sickrage-issues#1122]
Until a few days ago I could choose from these options: "copy", "move", "hard-link", "sym-link", etc. for post processing. Now there are only these two: "copy" and "move".
I did not change anything in my installation, nor modified configuration of any kind. Although I do not remember if Sickbeard was updated before the options disappear, can any of the latest updates have broken it?

OS: Windows 7 Ultimate 64bit
BRANCH: (master) / COMMIT: (345541ef6313f8f5d7ff45ef84647d44a2c29304)

EDIT: The options are being deliberately hidden, https://github.com/SiCKRAGETV/SickRage/commit/09b1d4b616edbfad4732658d970ed384b94bc5c3
But the functionality is still there: https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/helpers.py#L379 & https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/helpers.py#L398

**Comment by fernandog** [comment]
Windows dont have native support for symlink/hardlink

**Comment by bond-james** [comment]
NTFS6, which ships in Vista and Windows 7, supports symbolic links with the mklink command. But anyway, I use "hard-links" all the time, to organize TV shows from other directories within the same partition. The same type of link that is created using "mklink /h hard_link original_file" and until a few days ago the page "manual post-processing" included that option in the drop-down box "methods" and it worked perfectly. All of this in Windows 7.

**Comment by Geist-** [comment]
I've been using Hard Link ever since I switched to Sick Rage months ago and it's been working on Windows 8.1 perfectly. I know it does, because I have 2 terabytes of torrent downloads on a 3 TB hard drive with nearly 3 TB of television shows organized into folders. It couldn't fit if hard link didn't work.

**Comment by fernandog** [comment]
@abeloin should we revert it?

**Comment by abeloin** [comment]
I think so

**Comment by fernandog** [comment]
reverted! wait merge into master
