### ISSUE TITLE
[APP SUBMITTED]: None

### ISSUE THREAD

**Issue by ikkeenjij36** [SiCKRAGETV/sickrage-issues#1124]
### INFO
Python Version: **2.7.9 (default, Mar 23 2015, 00:07:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@345541ef6313f8f5d7ff45ef84647d44a2c29304
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-REFRESH :: No episode number found in /volume1/TV Series/New Girl/Season 3/3e2419e5078ad0c6947bc95f546093a197c61190.mkv, ignoring it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
@ikkeenjij36 And what exactly is the issue here?

**Comment by ikkeenjij36** [comment]
That it can't find an episode number.
Op 6 apr. 2015 21:55 schreef "Alexandre Beloin" <notifications@github.com>:

**Comment by abeloin** [comment]
Have a look at the filename: 3e2419e5078ad0c6947bc95f546093a197c61190.mkv

It should be self-explanatory as to why it is unable to find the episode number.

**Comment by ikkeenjij36** [comment]
Yes ik that i understand nut before the filename it says the right number.
So why can it not be renamed to the right ep. number?
Op 6 apr. 2015 22:38 schreef "Alexandre Beloin" <notifications@github.com>:

**Comment by abeloin** [comment]
no sure to understand what you're trying to say: before the filename it's the season number(3)

**Comment by abeloin** [comment]
@ikkeenjij36

**Comment by fernandog** [comment]
@ikkeenjij36 you probaly downloaded this episode from newsgroup. 

@TagForce can we rename the filename based on the nzbname?

**Comment by TagForce** [comment]
@ikkeenjij36 Do you have renaming turned on? If not, then that's the reason why it's not renaming.
If your renaming scheme is %RN (release name) then it might also not be renamed.
So, you should look at your settings first.
Post them here if you want.
