### ISSUE TITLE
[APP SUBMITTED]: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#1125]
### INFO
Python Version: **2.7.8 (default, Oct 20 2014, 15:05:29) [GCC 4.9.1]**
Operating System: **Linux-3.16.0-33-generic-i686-with-Ubuntu-14.10-utopic**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@64aba088e397674647b71cc314ecf9f810c2f9ce
Link to Log: https://gist.github.com/18a22a8b115b626d7b15
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: maximum recursion depth exceeded
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by matigonkas** [comment]
i believe this is also related but wasnt caught by the issue submiter http://pastebin.com/KB7dCPsm

**Comment by abeloin** [comment]
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1123
