### ISSUE TITLE
FR: Trakt PIN auth to replace Media Center Auth

### ISSUE THREAD

**Issue by Thraxis** [SiCKRAGETV/sickrage-issues#1126]
Trakt will be replacing the token based media center auth with PIN based auth (based on OAuth)

http://docs.trakt.apiary.io/#reference/authentication-pin

Quote from the post:
> PIN auth is up on staging and ready to test. This replaces the token based media center auth (which  will be deprecated once this is live). The main advantage is PIN auth is based on OAuth. This also allows users to sign in via their social accounts which was a big limitation of token auth. You can also use refresh tokens like normal OAuth.

@abeloin @TagForce @fernandog From cursory glance most of the OAuth code I created earlier can be re-purposed for this.  I'll get on the Trakt Staging and see how much I have to change

**Comment by Thraxis** [comment]
I started working on rebuilding this code last night.  After reviewing what I had I was not happy with how some of the code was.  Especially after reviewing the expanded Trakt API documentation for token refresh

**Comment by Thraxis** [comment]
NOTE: The TRAKT_API_KEY, TRAKT_API_SECRET, and TRAKT_PIN_URL are test
values. They need to be replaced before final merge

**Comment by Thraxis** [comment]
@SiCKRAGETV/moderators Still need to get a "permanent" Trakt API key and secret for this commit to replace the testing one I created..

**Comment by abeloin** [comment]
@fernandog Do we have an email account that could be used for that?

**Comment by fernandog** [comment]
@abeloin nope. I'm waiting @echel0n to reply about the SSL and the forum. the official email is sickrage.tv  a gmail

**Comment by cyberundertaker** [comment]
@fernandog @abeloin 
not sure if related but I have this problem. When trying to add trending show i get this message:
Trakt API did not return any results, please check your config.

SR doesn't give any error but from log i can see this:

2015-04-18 19:33:50 WARNING  Thread-43 :: Could not connect to Trakt service: error 401 Client Error: Unauthorized
2015-04-18 19:33:50 WARNING  Thread-43 :: Unauthorized. Please check your Trakt settings
2015-04-18 19:33:49 DEBUG    Thread-43 :: trending blacklist name is empty

**Comment by fernandog** [comment]
@cyberundertaker delete this post and open an issue

**Comment by fernandog** [comment]
@echel0n sent you some PM. can we use sickrage.tv email or should we create a new one?
