### ISSUE TITLE
Question about file detection

### ISSUE THREAD

**Issue by saitoh183** [SiCKRAGETV/sickrage-issues#1127]
i just downloaded a file that is in this format

S01E24.Au Secours de Béatrice.FINAL.HDTV.XViD-APW.avi

Is it possible for SR to detect the show even if the season-episode information is before the title? Or am i force to rename and run Manual-PP?

**Comment by maxcore** [comment]
hehe i have put APW in my ignore list , and the problem was done ;)

**Comment by abeloin** [comment]
No, it would conflict with the "s01e01 episode name regex". Maybe in the future, there is a feature request for specifying the data in manual PP.

Try http://www.advancedrenamer.com/ which does wonders to rename files automatically.

**Comment by saitoh183** [comment]
@abeloin 

Thanks, I dont mind renaming. This was the first time i encountered a file like this. Since its only for my french content, it isnt so bad.
