### ISSUE TITLE
[APP SUBMITTED]: 'charmap' codec can't decode byte 0x9d in position 35976: character maps to <undefined>

### ISSUE THREAD

**Issue by mbnoimi** [SiCKRAGETV/sickrage-issues#1128]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
Link to Log: https://gist.github.com/ab65309a789dbdb59e03
### ERROR

http://pastebin.com/isJpQE29
**Edit: Put log into pastebin**
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by mbnoimi** [comment]
Really strange error!

**Comment by abeloin** [comment]
Disable the proxy in rarbg preference(if I remember correctly you use tor in the global proxy so it will go through it). Rarbg use a new api and it's SSL only support SNI.

Original message:
```
The requested resource could not be loaded. libcurl returned the error: SSL connect error
```

**Comment by mbnoimi** [comment]
> if I remember correctly you use tor in the global proxy so it will go through it

Unfortunately I use M$ Windows now (my new laptop drivers aren't support by Linux) so the only available proxy is TOR/SOCKS which is not supported by SickRage :(

**Comment by abeloin** [comment]
Can you check if `https://torrentapi.org/pubapi.php?get_token=get_token` in your browser?

**Comment by abeloin** [comment]
Btw, both Privoxy and polipo works in Windows

http://www.privoxy.org/
http://www.pps.univ-paris-diderot.fr/~jch/software/polipo/

**Comment by mbnoimi** [comment]
> Can you check if https://torrentapi.org/pubapi.php?get_token=get_token in your browser?

Works and I received **cbvq62uexh**

**Comment by mbnoimi** [comment]
> Btw, both Privoxy and polipo works in Windows

Thanks, I'll try to run Privoxy because polipo hasn't stable release for Windows.

**Comment by mbnoimi** [comment]
> Thanks, I'll try to run Privoxy because polipo hasn't stable release for Windows.

Oh yea...it works smoothly with Privoxy.
Thank you guys once again for great help.
