### ISSUE TITLE
HTTPS without self signed certificate

### ISSUE THREAD

**Issue by tex0l** [SiCKRAGETV/sickrage-issues#1129]
Hi,

I've been using SickBeard then SickRage for a long time now, thanks for everything, it's f****** great !

I've recently moved in my new appartement, and I've re-installed my Synology DS713+ (sorry, I know...), bootstrapped with ipkg (at least !), and I've got a domain name.

I've decided to cipher all web connections with a free class 1 SSL certificate for my domain (with Startssl, expires in one year). It works great for the DSM (web interface of the NAS by Synology)  when I give it the cert and the key, but does not for SickRage:

I use the master branch; on commit 669046ea40a7a26a6121a1b07721f3c1c3cf5b10.

I put a copy in plain text (pasted it on nano, same files as DSM), in the directory right above SickBeard along with all the db files, I changed the permissions to 440, but I've tried with 777, and I chowned too. I called them ssl.crt, ssl-decrypted.key (the key was password-protected, I deciphered it before obviously). I checked that it was the right directory in the SickRage's settings ("All non-absolute folder locations are relative to ..."). I changed the filenames and enabled HTTPS; then restarted. 

I tried to connect in HTTPS, it works, but it does not use the key/certificate key I gave:
Here are the infos I have on that certificate.
![capture d ecran 2015-04-07 a 11 53 10](https://cloud.githubusercontent.com/assets/7548264/7020861/b4d3180c-dd1c-11e4-8731-d50a9c7fe0a4.png)

Normally I should have just like on the DSM web interface:
![capture d ecran 2015-04-07 a 11 54 34](https://cloud.githubusercontent.com/assets/7548264/7021102/97def5f2-dd1e-11e4-96b6-ee55d603c4dc.png)

I've watched the logs closely, the only line is regarding this issue is :
"TORNADO :: Starting SickRage on https://0.0.0.0:8083/"

...

Any idea guys ?

Thanks,
tex0l.

**Comment by abeloin** [comment]
My guess is that you forgot to set in config.ini[General]: https_cert and https_key.

It should be in your case:
```
enable_https = 1
https_cert = /path/to/your/file/ssl.crt
https_key = /path/to/your/file/ssl-decrypted.key

```

**Comment by tex0l** [comment]
I did it with the web UI.

When I check the config.ini, I've got:
```
enable_https = 1
https_cert = ssl.crt
https_key = ssl-decrypted.key
```

I'll try with absolute paths.

**Comment by tex0l** [comment]
It works with absolute paths... 

It seems then that the relative paths don't work here...

Thanks !
