### ISSUE TITLE
Episode Thumbnails DVD Order

### ISSUE THREAD

**Issue by jmf866** [SiCKRAGETV/sickrage-issues#1132]
When a TV series is set to DVD order, postprocessing pulls the broadcast order episode thumbnail from thetvdb instead of the correct DVD order.

BRANCH: (master) / COMMIT: (669046ea40a7a26a6121a1b07721f3c1c3cf5b10)
Windows 8.1
Python 2.7.8

**Comment by fernandog** [comment]
@jmf866 did you full update the show after enable DVD order?

**Comment by jmf866** [comment]
Yes, I did a full update.  The NFO files downloaded are correct.  But thumbnails are not.

For example, Seinfeld season 1.  Male-Unbonding is broadcast order 4, but DVD order 2.  Postprocessing names the thumbnail correctly for DVD order as "Seinfeld - S01E02 - Male-Unbonding.jpg", but the image in the file is pulsed from broadcast order episode 2, "The Stakeout".

I tried this for several metadata types: Kodi, Mede8er, etc.

**Comment by fernandog** [comment]
@TagForce is it an issue? can you check please?

**Comment by fernandog** [comment]
@tagforce please?

**Comment by TagForce** [comment]
@fernandog I have no idea about this one... I'll need to examine the code, but I'm *really* short on time.
I'll see if I can do this sometime tomorrow

**Comment by TagForce** [comment]
@jmf866 For what device are you trying to create metadata?

**Comment by jmf866** [comment]
I use JRiver Media Center for HTPC, which has it's own sidecar files in XML. It has a good scraper built in, but it won't do DVD order. JRiver will import NFO files with some modifications to the files first. So I choose Kodi in the dropdown for Metadata Type to generate episode metadata, and Mede8er to generate thumbnails because the filename format matches what JRiver uses.

I'm looking at these before importing into JRiver. The NFO files are correct every time, for either aired order or DVD order. Thumbnails are perfect when aired order is chosen. But with DVD order, the thumbnail is from the episode number in aired order instead of DVD order. This happens no matter what metadata type I choose, or what combination. Kodi, Kodi 12+, MediaBrowser, Mede8er, etc. All of them have this issue with thumbnails.

Here is an example scenario:
Set post processing metadata to anything that includes episode thumbnails.
Add the show Firefly using TheTVdB, set to DVD order and do a full update. Episode 1 Name should show as "Serenity" now instead of "The Train Job".
Place a file named "Firefly - S01E01.mkv" in the TV Download Dir.
Set episode 1 to skipped and run manual post process. Or wait for scheduled post process, it doesn't matter.
When post processing completes, check the new metadata and thumbnail files.

The NFO file (or XML depending on what you select) for the episode will correctly match up with DVD episode 1 (which is aired episode 11):
http://www.thetvdb.com/?tab=episode&seriesid=78874&seasonid=15791&id=297999&lid=7

But the thumbnail, although being named S01E01, will be an image of aired episode 1 instead of DVD episode 1:
http://www.thetvdb.com/?tab=episode&seriesid=78874&seasonid=15791&id=297989&lid=7

**Comment by TagForce** [comment]
Found it, and fixed it real quick... The function validateShow did not account for dvdorder... It does now... It's only ever called from generic.py once, when creating metadata, so shouldn't be a problem changing it.

I created the pull request for last week's develop, because I couldn't upgrade it right now, but I don't think helpers.py has changed, and it's only 2 added lines.

**Comment by abeloin** [comment]
@jmf866 PR merged into develop. Will be merge into master on Sunday.

**Comment by TagForce** [comment]
@jmf866 Do you have a link to metadata documentation for JRiver?
If you want, and can supply the link, you can add a feature request to add the metadata provider for JRiver. It would save you some time editing the files manually ;)

**Comment by jmf866** [comment]
@TagForce It works perfectly now, thanks!  I'll see if I can find a link to JRiver's metadata documentation.

**Comment by TagForce** [comment]
@jmf866 I'll close this issue... Open a new one for the feature request if you want.
