### ISSUE TITLE
[APP SUBMITTED]: No JSON object could be decoded

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#1134]
### INFO
Python Version: **2.7.8 (default, Oct 20 2014, 15:05:29) [GCC 4.9.1]**
Operating System: **Linux-3.16.0-33-generic-i686-with-Ubuntu-14.10-utopic**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@78fe58e34961026738a90544e11aa4b7308d6670
Link to Log: https://gist.github.com/4db658754fa43dae0921
### ERROR
```
FINDPROPERS :: [EZTV] :: Error while searching EZTV, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@matigonkas http://eztvapi.re/show/tt2346169 is empty

@abeloin we should check for empty return in EZTV

**Comment by abeloin** [comment]
@fernandog Yes we should

**Comment by fernandog** [comment]
@abeloin maybe we can add this here:

https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/providers/generic.py#L134

and not in eztv.

**Comment by abeloin** [comment]
https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/helpers.py#L1311

transform the the return into a if:
```
if not json:
    try:
        resp.content
    except Exception as e:
        logger.log(u"Unable to return content for " + url + ": " + traceback.format_exc(), logger.WARNING)
        return
else:
    try:
        resp.json()
    except Exception as e:
        logger.log(u"Unable to decode json data for  " + url + ": " + traceback.format_exc(), logger.WARNING)
        return {}
```

**Comment by fernandog** [comment]
@matigonkas can you use this new file SickRage/sickbeard/helpers.py ?

stop SR, use this one:
https://raw.githubusercontent.com/fernandog/SickRage/getURL_check_resp/sickbeard/helpers.py
save, start, test, report back please

**Comment by matigonkas** [comment]
@fernandog heres the log http://pastebin.com/pbqGj2fA

**Comment by abeloin** [comment]
@matigonkas You are not using the new code:
```
AA    return resp.content if not json else resp.json()
AA  File "/home/super******/SickRage/sickbeard/helpers.py", line 1311, in getURL
```

**Comment by matigonkas** [comment]
i thought that i had changed that file ,but well it should be changed now. http://pastebin.com/0AfPcz7m
@abeloin

**Comment by fernandog** [comment]
@abeloin that page is blank

http://eztvapi.re/show/tt1666727

**Comment by abeloin** [comment]
PR merged in develop
