### ISSUE TITLE
[APP SUBMITTED]: Connection error ('Connection aborted.', error(104, 'Connection reset by peer')) while loading URL http://services.tvrage.com/myfeeds/showinfo.php

### ISSUE THREAD

**Issue by larstomas** [SiCKRAGETV/sickrage-issues#1135]
### INFO
Python Version: **2.7.9 (default, Mar 23 2015, 00:07:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@345541ef6313f8f5d7ff45ef84647d44a2c29304
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: TVRage timed out, unable to update episodes from TVRage
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
TVRage timed out

**Comment by newkindofworld** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@27ded15e814bcbd47d06d9bf16d130f9d42ebd45
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: TVRage timed out, unable to update episodes from TVRage
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Peke** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@0769c527da9b41180618db6cc23039547a4be3d8
Link to Log: https://gist.github.com/320747fabcabbc70dd2c
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: error Connection error ('Connection aborted.', error(104, 'Connection reset by peer')) while loading URL http://services.tvrage.com/myfeeds/showinfo.php
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
