### ISSUE TITLE
Ignoring iTunes files

### ISSUE THREAD

**Issue by OskarPersson** [SiCKRAGETV/sickrage-issues#1136]
Sickrage ignores my iTunes files, can I do something in my settings to fix this?
![skarmavbild 2015-04-07 kl 18 43 23](https://cloud.githubusercontent.com/assets/935414/7031558/bcdaf6aa-dd6c-11e4-8c95-f83ff17e0738.png)

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/581
