### ISSUE TITLE
feature request ( torrent providers with Templateshares Ultimate script )

### ISSUE THREAD

**Issue by valantislevas** [SiCKRAGETV/sickrage-issues#1139]
hello.. many trackers uses Templateshares Script for the tracker from www.templateshares-ue.net if u make plugin that supports custom torrent provider for this script many people will be happy..

is it possible in near future to make it work?

thanks for your work !

**Comment by kotysoft** [comment]
Any kind of (json based?) custom provider adding option would be welcome! :+1: 
For example just like in Couchpotato

**Comment by abeloin** [comment]
Duplicate of #223 
@valantislevas You already asked previously no need to create a new issue. Any new request for this feature by you, will result in the original FR be removed and ignored in the future!
