### ISSUE TITLE
[APP SUBMITTED]: Unable to parse Top.Gear.S04.HDTV.XviD into a scene name. If it's a valid one log a bug.

### ISSUE THREAD

**Issue by mrj1987** [SiCKRAGETV/sickrage-issues#1140]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-29-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-74608 :: Unable to parse Top.Gear.S04.HDTV.XviD into a scene name. If it's a valid one log a bug.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@mrj1987 the name of the show in show page is only TOP GEAR or there's a year on it or a country string?
