### ISSUE TITLE
[APP SUBMITTED]: threads can only be started once

### ISSUE THREAD

**Issue by Thraxis** [SiCKRAGETV/sickrage-issues#1141]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@78fe58e34961026738a90544e11aa4b7308d6670
Link to Log: https://gist.github.com/c93a9cfd0dd73bef240a
### ERROR
```
Thread-23 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\GitHub\test\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\GitHub\test\SickRage\sickbeard\webserve.py", line 4709, in saveNotifications
    config.change_USE_TRAKT(use_trakt)
  File "C:\GitHub\test\SickRage\sickbeard\config.py", line 237, in change_USE_TRAKT
    sickbeard.traktCheckerScheduler.start()
  File "C:\Python27\lib\threading.py", line 739, in start
    raise RuntimeError("threads can only be started once")
RuntimeError: threads can only be started once

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Thraxis** [comment]
The scheduler changes currently in Dev breaks the saving of notifications.  In particular the USE_TRAKT and TRAKT_USE_ROLLING_DOWNLOAD.  

change_TRAKT_USE_ROLLING_DOWNLOAD no longer exists in the config.py file

**Comment by fernandog** [comment]
@Thraxis was it removed in the new scheduler PR?

**Comment by abeloin** [comment]
@Thraxis PR merged into develop

**Comment by abeloin** [comment]
@Thraxis Still having the issue?

**Comment by Thraxis** [comment]
@abeloin PR fixed the issue
