### ISSUE TITLE
ISSUE : No update on startup

### ISSUE THREAD

**Issue by tchirou** [SiCKRAGETV/sickrage-issues#1142]
Hello

BRANCH: (master) / COMMIT: (669046ea40a7a26a6121a1b07721f3c1c3cf5b10)
Python 2.7.6 / Win 8.1

Update shows on startup is checked. update_shows_on_start = 1 in config.ini

But there is no update.

Debug log : https://gist.github.com/tchirou/ac4d979df409ba08da0a

Thanks

**Comment by fernandog** [comment]
@tchirou use log filter and select in listbox "Show updater" - post results

**Comment by tchirou** [comment]
It's empty

**Comment by fernandog** [comment]
@tchirou can you switch to master please?

**Comment by tchirou** [comment]
I am already on master

**Comment by fernandog** [comment]
@tchirou comment updated. please read

**Comment by tchirou** [comment]
Still empty

**Comment by fernandog** [comment]
@tchirou edit show update hours to the next hour. If your time is 12:32 then set to 13. wait until 13:35 to update

**Comment by tchirou** [comment]
Yeah I already planned it a 21 which is in 26 minutes

**Comment by fernandog** [comment]
@tchirou it wont update 21:00 sharp.  it will be 21:34

**Comment by tchirou** [comment]
Alright

**Comment by fernandog** [comment]
@tchirou did you restarted after switch to develop?

**Comment by tchirou** [comment]
Yes

**Comment by abeloin** [comment]
Maybe related to #1043,

```
Ok, the issue is with the function network_timezones.update_network_dict() in sickbeard/showUpdater.py#46. Commenting the line allow showUpdater to continue.
```

**Comment by tchirou** [comment]
So should I do something or should I wait for you to get back to me ?

**Comment by fernandog** [comment]
@tchirou search your log for "timezones" using logsearch feature

**Comment by tchirou** [comment]
here it is

2015-04-08 20:35:53 DEBUG    MAIN :: AddNetworkTimezones upgrade not required
2015-04-08 20:35:53 DEBUG    MAIN :: Checking Add Network Timezones database upgrade

**Comment by tchirou** [comment]
after a restart at 20h35

**Comment by tchirou** [comment]
i have the "local" timezone checked in interface settings

**Comment by tchirou** [comment]
Empty showupdater log after 9:34 pm and scheduled update

**Comment by abeloin** [comment]
@tchirou Do you use trakt?

**Comment by tchirou** [comment]
I made a try for some hours but I chose to use kodi instead.
So I disabled trakt in SR but there is still my login info and the sync library checked.
Should I enable it, save, remove everything, save, disable it and then save and restart ?

**Comment by abeloin** [comment]
Can you disable trakt completly, stop SR and start SR and check if the update are done?

**Comment by tchirou** [comment]
I did what I suggested and no luck, no update

**Comment by abeloin** [comment]
You are on develop? If so can you send a screenshot of the status page?

**Comment by tchirou** [comment]
Fernandog asked to switch to develop, yes

**Comment by tchirou** [comment]
here you go 
https://www.dropbox.com/s/myjk5jpml60pk7y/status.jpg?dl=0

**Comment by abeloin** [comment]
Ok so "Update on startup"is check and on start show Queue is empty on the status page?

**Comment by tchirou** [comment]
Yes

**Comment by abeloin** [comment]
And you comment out: network_timezones.update_network_dict() in sickbeard/showUpdater.py#46?

**Comment by tchirou** [comment]
Nope
I asked if I should do it but fernandog asked me to check timezones 
So should I do it ?

**Comment by abeloin** [comment]
Wait, I'll post a patch of something I want you to try. Give 2 mins

**Comment by abeloin** [comment]
Ok here: https://copy.com/LznV9HrKZum4eCc2

**Comment by tchirou** [comment]
please remind me how i should proceed with this

**Comment by abeloin** [comment]
Save the file in SR folder. Stop SR
If you have Git for Windows, right on sickrage folder in explorer and choose Git Bash.
In the git bash:
* `git reset --hard`
* `patch -p1 < patch-20150409_showupdate.diff`
 If any hunk failed or rejected, post the results
If everything was ok, start sickrage

**Comment by tchirou** [comment]
it does not accept the <

**Comment by abeloin** [comment]
What the error?

**Comment by abeloin** [comment]
You are in in the mingw window, not in a windows cmd shell?

**Comment by tchirou** [comment]
in a windows powershell

**Comment by abeloin** [comment]
![Imgur](http://i.imgur.com/GibaXUc.png)

**Comment by tchirou** [comment]
well i usually launch git shell
i am going to look for your mingw32

**Comment by abeloin** [comment]
Usually via right click on folder:
![Imgur](http://i.imgur.com/xcwmKNN.png)

**Comment by tchirou** [comment]
i am installing the mingw thing but it downloads a lot of things

**Comment by abeloin** [comment]
Dont install mingw

**Comment by abeloin** [comment]
Try patch for windows: http://gnuwin32.sourceforge.net/packages/patch.htm

**Comment by tchirou** [comment]
alright its patched. I restarted but no update

**Comment by abeloin** [comment]
Think you can do some git bisect?

**Comment by tchirou** [comment]
I don't even begin to understand what you mean

**Comment by abeloin** [comment]
Ok git bisect: take a working version and a non working and testing version in between until were it stop working:

Git bisect(stop sickrage first and go to sickrage folder):
```
$ git bisect start
$ git bisect bad
$ git bisect good v4.0.14
```
* git will then tell tell you `Bisecting: x revisions left to test after this`.
* Start sickrage manually `python SickBeard.py --nolaunch`
* Check if ok:
  * If ok, stop sickrage(Ctrl-C) and type: `git bisect good`
  * If not ok, stop sickrage(Ctrl-C) and type: `git bisect bad`
* Repeat until you see `is first bad commit` take note of the commit id.
* At the end `git bisect reset` to return to the HEAD revision.

See this documentation on how to bisect: http://git-scm.com/book/en/v2/Git-Tools-Debugging-with-Git

**Comment by tchirou** [comment]
holy cow !
i am going to try just to be allowed to write I did it on my tombstone

**Comment by tchirou** [comment]
should i still be on develop ? shouldnt I disable auto update ? because at the first launch it updated to the last commit I think, which defeats the purpose no ?

**Comment by abeloin** [comment]
Yes auto-update should be disabled

**Comment by abeloin** [comment]
Good luck

**Comment by tchirou** [comment]
Ok 
![sans titre](https://cloud.githubusercontent.com/assets/6749420/7075605/9ee7745a-df03-11e4-9720-cc657bfa583a.jpg)
Except it won't let me reset

**Comment by abeloin** [comment]
What do you mean?

**Comment by tchirou** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/6749420/7075668/1f01a124-df04-11e4-8cc0-0f5af94ac5d0.jpg)

**Comment by abeloin** [comment]
Try `git reset --hard` if not `git reset --hard HEAD^1`

**Comment by abeloin** [comment]
And commit 415... is the culprit?

**Comment by tchirou** [comment]
yes

**Comment by tchirou** [comment]
I am lost...
![sans titre](https://cloud.githubusercontent.com/assets/6749420/7075788/f4359d00-df04-11e4-9a57-7fbbc10e231b.jpg)

**Comment by abeloin** [comment]
Try a few time: git reset --hard HEAD^1
Then : git bisect reset

**Comment by abeloin** [comment]
415 is the last working commit or the first non working commit?

**Comment by tchirou** [comment]
I kept doing it until it said 415 is the first bad commit

**Comment by tchirou** [comment]
What if I installed master from scratch with reimporting sickbeard.db, config.ini and the cache folder ?

**Comment by abeloin** [comment]
Give me the results of `git reflog`

**Comment by tchirou** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/6749420/7075987/607c6772-df06-11e4-85b5-5add6ed16a59.jpg)

**Comment by abeloin** [comment]
git reset --hard HEAD@{44}

**Comment by tchirou** [comment]
Ok. done. and what ?

**Comment by abeloin** [comment]
git bisect reset

**Comment by tchirou** [comment]
I managed to get out of bisect
I am now back at 8e03cae4e9d29d8d31a343b90ba20e08d35f541d

**Comment by tchirou** [comment]
Do you want a teamviewer ID ? because I think I mess things up more than I help you find what is wrong

**Comment by abeloin** [comment]
Ok now to confirm:
* `git checkout 84351236d08146413a887c6d955ab5cfd4258a48`
* Start sickrage manually `python SickBeard.py --nolaunch`
* Check if ok

**Comment by abeloin** [comment]
Ok

**Comment by tchirou** [comment]
Now I need to find how to send a pm through here :)

**Comment by abeloin** [comment]
sickrage.tv(funkylove) pm or irc pm

**Comment by tchirou** [comment]
pm sent :)

**Comment by abeloin** [comment]
Checking

**Comment by tchirou** [comment]
Standing ovation for @abeloin who intervened on my computer. It was like watching a neurosurgeon removing a very delicate tumor.
Many thanks !!!

**Comment by abeloin** [comment]
@tchirou Can you update to the latest version, and test again?

**Comment by tchirou** [comment]
I updated hours ago and it did not work
And now i can't even login and I don't know why...

**Comment by tchirou** [comment]
Ok so I managed to log again but no update
And I have these errors
2015-04-10 20:46:23 MAIN :: Check scene exceptions update failed. Unable to get URL: http://midgetspy.github.io/sb_tvdb_scene_exceptions/exceptions.txt
2015-04-10 20:46:23 MAIN :: Check scene exceptions update failed. Unable to get URL: https://raw.githubusercontent.com/echel0n/sb_tvrage_scene_exceptions/master/exceptions.txt

And these warnings 
2015-04-10 20:46:23 WARNING  DAILYSEARCHER :: Loading zoneinfo.txt failed, this can happen from time to time. Unable to get URL: https://raw.githubusercontent.com/Prinz23/sb_network_timezones/master/zoneinfo.txt
2015-04-10 20:46:23 WARNING  MAIN :: Loading zoneinfo.txt failed, this can happen from time to time. Unable to get URL: https://raw.githubusercontent.com/Prinz23/sb_network_timezones/master/zoneinfo.txt

**Comment by abeloin** [comment]
@tchirou Update again

**Comment by tchirou** [comment]
Meanwhile I installed a master version from scratch with my config.ini, sickbeard.db and images folder and everything works like a charm, including the update on startup
I am going to update the broken develop one

**Comment by abeloin** [comment]
Ok, could it be related to the cached.db and cache folder? Make backup first and try removing the whole cache folder then start SR. If it still doesn't work, stop SR delete cache folder and failed.db and start SR

**Comment by tchirou** [comment]
I renamed the cache folder to cache-test and started. Now I have SHOWQUEUE-REFRESH all over the place writing nfos and copying jpgs
Do you think it was it ? or is just a normal behavior cause there was nothing and it could freeze again after the first run ?

**Comment by tchirou** [comment]
Ok so new master and develop have finished their first run of update. I restarted both of them.
New master does not update on startup. Develop does update on startup.
So i will keep develop until you merge your fix with master. Can I hope sunday ?
Thanks again.

**Comment by abeloin** [comment]
@tchirou Can sent sent me a dir listing of the cache sessions folder?

**Comment by tchirou** [comment]
develop (working) : https://www.dropbox.com/s/02dzmfamgxjj9rr/develop.htm?dl=0
master (not working) : https://www.dropbox.com/s/xgsxjv9xo2iql27/master.htm?dl=0

**Comment by abeloin** [comment]
Ok and can you send me the one from the cache-test folder?

**Comment by tchirou** [comment]
Here you go : https://www.dropbox.com/s/vdz9laqje5ot9z6/develop-cache-test.htm?dl=0

**Comment by abeloin** [comment]
Thanks

**Comment by tchirou** [comment]
Hello
Can i switch to master ?
Thanks

**Comment by abeloin** [comment]
@tchirou Go for it. Closing the issue

**Comment by tchirou** [comment]
Thanks
