### ISSUE TITLE
[APP SUBMITTED]: None

### ISSUE THREAD

**Issue by mikaelnt** [SiCKRAGETV/sickrage-issues#1143]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-268009 :: Check scene exceptions update failed. Unable to get URL: http://midgetspy.github.io/sb_tvdb_scene_exceptions/exceptions.txt
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@mikaelnt intermittent issue. not an error
