### ISSUE TITLE
[APP SUBMITTED]: No upstream configured for branch 'master'

### ISSUE THREAD

**Issue by gcwillie1981** [SiCKRAGETV/sickrage-issues#1144]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c9a102608e37c4c6e24c595297af1add5677ef79
Link to Log: https://gist.github.com/f2234af4c4651cafc698
### ERROR
```
Thread-250 :: "C:\Program Files\Git\cmd\git.exe" rev-parse --verify --quiet "@{upstream}" returned : error: No upstream configured for branch 'master'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@gcwillie1981 how did you installed SR? it used to work before or it's a new install?

**Comment by gcwillie1981** [comment]
@fernandog Thanks for replying. I used the windows installer.

**Comment by fernandog** [comment]
@gcwillie1981 where did you get windows installer do SR? there isn't one available for that

**Comment by gcwillie1981** [comment]
@fernandog Apologies meant the git hub for windows.

**Comment by fernandog** [comment]
@gcwillie1981 did you followed this tutorial?

http://www.htpcguides.com/install-sickrage-windows-usenet-torrent-tv/

**Comment by abeloin** [comment]
@gcwillie1981 Please the result of those command in sickRage folder:
git branch -vv
git remote -v

**Comment by gcwillie1981** [comment]
@fernandog Yes followed all the instructions

@abeloin See below results

C:\SickRage>git branch -vv
  develop 78fe58e [origin/develop: behind 2] Merge branch 'abeloin-revert-pmc' i
nto develop
* master  669046e Merge pull request #1723 from abeloin/revert-pmc

C:\SickRage>git remote -v
origin  https://github.com/SiCKRAGETV/SickRage.git (fetch)
origin  https://github.com/SiCKRAGETV/SickRage.git (push)

C:\SickRage>

**Comment by abeloin** [comment]
@gcwillie1981 master is missing it's remote reference. Edit C:\SickRage\.git\config and make to add this
 ```
[branch "master"]
        remote = origin
        merge = refs/heads/master
```
then run git branch -vv, it should show something like this now:
`master 669046e [origin/master] Merge pull request #1723 from abeloin/revert-pmc`

**Comment by gcwillie1981** [comment]
@abeloin I'm assuming you mean adding that to the config.ini?

**Comment by gcwillie1981** [comment]
Also don't know if the below will help

C:\SickRage>git pull https://github.com/SiCKRAGETV/SickRage.git master
From https://github.com/SiCKRAGETV/SickRage
 * branch            master     -> FETCH_HEAD
Already up-to-date.

**Comment by abeloin** [comment]
No there is a file called config in .git folder: C:\SickRage\\.git\config

**Comment by gcwillie1981** [comment]
Hello have done as suggested and now no error.

Anything I need to check to confirm on latest version?

**Comment by abeloin** [comment]
Try a git pull
