### ISSUE TITLE
[APP SUBMITTED]: _doSearch() got an unexpected keyword argument 'epObj'

### ISSUE THREAD

**Issue by rogc** [SiCKRAGETV/sickrage-issues#1145]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.7+-armv6l-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
Link to Log: https://gist.github.com/6c407657a753e3783365
### ERROR
```
SEARCHQUEUE-BACKLOG-259063 :: [ThePirateBay] :: Error while searching ThePirateBay, skipping: _doSearch() got an unexpected keyword argument 'epObj'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
Please update SR and reboot SR

**Comment by rogc** [comment]
Thanks!
