### ISSUE TITLE
[APP SUBMITTED]: [Errno socket error] [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by FlyGuy94** [SiCKRAGETV/sickrage-issues#1146]
### INFO
Python Version: **2.7.9 (default, Mar 23 2015, 00:07:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@8a8c9b83711dc2c9c29eaf668f34ac5874696979
Link to Log: https://gist.github.com/0bdacb10c8eb24e8b1c3
### ERROR
```
POSTPROCESSER :: Error while trying to contact Plex Media Server: socket error : error [Errno 11] Resource temporarily unavailable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Check if your plex is running

**Comment by FlyGuy94** [comment]
Yeah I was figuring out how this submit errors buttons works. It seems it only submitted the last error and not the one before witch is interesting I tough I could atleast choose witch error I wanted to report I guess not.

**Comment by fernandog** [comment]
hit submit again. The next error should be used
