### ISSUE TITLE
use scene numbering issue

### ISSUE THREAD

**Issue by kdy1968** [SiCKRAGETV/sickrage-issues#1149]
SR Version:  BRANCH: (master) / COMMIT: (669046ea40a7a26a6121a1b07721f3c1c3cf5b10) 
SR Config file: /SickRage/sickRage_data/config.ini 
SR Database file: /SickRage/sickRage_data/sickbeard.db 
SR Cache Dir: /SickRage/sickRage_data/cache 
SR Log Dir: /SickRage/sickRage_data/Logs 
SR Arguments: ['-q', '--daemon', '--nolaunch', '--pidfile=/SickRage/pid', '--datadir=/SickRage/sickRage_data'] 
Python Version: 2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2] 

pawn stars nolonger downloading
set to use scene numbering
"Unable to find a download for: [Pawn Stars - 2015x20 - Crossing Chum]"
I would expect it to be looking for S12E20..versus 2015x20
Pawn Stars S12E20 Crossing Chum exists on provider
...

**Comment by abeloin** [comment]
Make sur search by airdate isn't enable in the show settings

**Comment by kdy1968** [comment]
its not checked,

**Comment by abeloin** [comment]
Post full debug log

**Comment by abeloin** [comment]
@kdy1968

**Comment by kdy1968** [comment]
went to restart after enabling debug and ...it snatched them right away...perhaps there was a setting or somthing that didnt stick until after restart ....i appreciate everyone's hard work/support...closing
