### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'getOverview'

### ISSUE THREAD

**Issue by pilothaz** [SiCKRAGETV/sickrage-issues#1150]
### INFO
Python Version: **2.7.8 (default, Dec 15 2014, 02:33:48) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
Link to Log: https://gist.github.com/986610805e61775815ef
### ERROR
```
Thread-39 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 1962, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 1922, in getEpisodes
    'overview': Overview.overviewStrings[showObj.getOverview(int(searchThread.segment.status or -1))]})
AttributeError: 'NoneType' object has no attribute 'getOverview'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@pilothaz what did you do?

**Comment by pilothaz** [comment]
Logged into webui, and saw all these. There was 383 of them. I reset it and
enabled debug, I am waiting on update.

**Comment by abeloin** [comment]
In which page?

**Comment by fernandog** [comment]
@pilothaz closed as we didn't received reply
