### ISSUE TITLE
[APP SUBMITTED]: Automatic post-processing attempted but dir Z:\Media\To Be Sorted doesn't exist

### ISSUE THREAD

**Issue by gregtotheizzo** [SiCKRAGETV/sickrage-issues#1151]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
Link to Log: https://gist.github.com/31d48f25e87ba26243df
### ERROR
```
POSTPROCESSER :: Automatic post-processing attempted but dir Z:\Media\To Be Sorted doesn't exist
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
Your PP folder doesn't exist: Z:\Media\To Be Sorted

**Comment by gregtotheizzo** [comment]
It does

Im running windows 8.1 and the z:\ is mapped and still has connection but sickrage has stopped seeing any network drives.

**Comment by abeloin** [comment]
Changed the way you start sickrage?

**Comment by gregtotheizzo** [comment]
No same way, running as windows service.  When I stop the service and launch on its on via Python I get the same issue regardless how it launched.

Windows sees z:\ and connects without issue however sickrage doesn't see any mapped drive.

Thank you

**Comment by TagForce** [comment]
@gregtotheizzo Mapped drives are dependent on the user session... A mapped drive which is mapped on a user administrator has no effect on a session for another user. Likewise, a mapped drive for the same user has no effect on other sessions of that user (ie, on the console a mapped drive for user administrator won't show up for a different session on the same machine for the same user).
Even though you may see the mapped drive, doesn't mean the session or user running SR sees it.

Besides that: SR only sees mapped drives that were mapped BEFORE SR starts. If you map the drives during the service startup for SR then you should at a timer to the process waiting for 10 seconds before actually starting SR. Otherwise, you should run the SR service as Automatic (Delayed).

**Comment by gregtotheizzo** [comment]
even closing all the instances and stopping all the instances of SickRage
running and starting up after verifying the network drives are up and
connectable doesn't work.

The same user running the SR service is the same user as the user im
logging in as. Since its a personal computer theres only one account on the
machine with guest and admin disabled by default in win vista+.

I appreciate the feedback but if you have additional troubleshooting steps
to try, that would be a great help.

Thank you

**Comment by abeloin** [comment]
@gregtotheizzo When you start python manually via non-admin console(cmd) you don't see the mapped drive?
* Open cmd.exe
* cd sickrage
* dir "Z:\Media\To Be Sorted"
* c:\python27\python.exe sickbeard.py --nolaunch

**Comment by gregtotheizzo** [comment]
that seemed to work:

10:11:11 INFO::POSTPROCESSER :: Processing Z:\Media\To Be
Sorted\Helix.S02E06.10
80p.WEB-DL.DD5.1.H.264-KiNGS[rarbg]\Helix.S02E06.1080p.WEB-DL.DD5.1.H.264-KiNGS.
mkv (None)

so should i remove the service from auto started and use another method?

What method would be the best for network shares?

thanks again!!

**Comment by abeloin** [comment]
Can you check the Log On tab in the service properties and make sure it run as your user and not the local system account?

**Comment by gregtotheizzo** [comment]
It's running as my user account not local system account.

**Comment by gregtotheizzo** [comment]
rebooted with the service set to delayed and same issue:

2015-04-09 12:49:56 POSTPROCESSER :: Automatic post-processing attempted
but dir Z:\Media\To Be Sorted doesn't exist

service is running with my credentials.

**Comment by abeloin** [comment]
What do you use to create the service

**Comment by gregtotheizzo** [comment]
I used NSSM

Any link to preferred method?

**Comment by abeloin** [comment]
Ok I use the same thing and it work. Your mapped drives have "reconnect at sign-in" enable?

![Imgur](http://i.imgur.com/a0FtmsQ.png)

**Comment by gregtotheizzo** [comment]
Yes of course, it's how utorrent is still able to pull torrents from my network drive Z:\

What's weird is that even disabling the service and manually staring the service after boot and network drive reconnects it still doesn't see mapped drives.

Manually starting via vbs script seems to work.

I just left work and appreciate the assistance. I'll play around with the settings and service then report back at a later time.

Thanks again

**Comment by fernandog** [comment]
@gregtotheizzo can we close this issue?

**Comment by gregtotheizzo** [comment]
The issue still persists, and all the steps haven't been able to resolve the issue but as a work around im just manually starting sickrage.

**Comment by TagForce** [comment]
@gregtotheizzo Well... You can try approaching this issue from a completely different angle:
Create a symbolic link (mklink.exe from cmd) somewhere in your current filesystem that points to the network share you want to use. You should, in theory, be able to simply open that symlink as a folder in SR.

If you're share is located at server1\data and you want to reference it as D:\Temp\Share all you need to do is type this command from D:\Temp
```
mklink /D Share \\server1\data
```

In SR D:\Temp\Share should show up as a folder, and you should be able to browse the whole share underneath it.

**Comment by gregtotheizzo** [comment]
that's worth a shot! I'll give it a go when im home from work. Manually starting a been ok as long as I remember to launch :)

Thanks again for all the help.

**Comment by abeloin** [comment]
Closing because no feedback for the last 10 days
