### ISSUE TITLE
[APP SUBMITTED]: None

### ISSUE THREAD

**Issue by seanbranam** [SiCKRAGETV/sickrage-issues#1152]
### INFO
Python Version: **2.7.8 (default, Dec 15 2014, 02:33:48) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-237831 :: Unable to parse Veep.Season.1.WEB-DL.480p.H264-20-40 into a scene name. If it's a valid one log a bug.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
What is the -20-40 supposed to mean anyways? I will go out on a ledge here and say the -20-40 at the end is probably why the name cant be parsed as all 3 issues reporting this have the same suffix.

**Comment by abeloin** [comment]
@miigotu If it's the case, then it can be added as rule in https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/providers/generic.py#L493 which clean the title coming from the provider

**Comment by Thraxis** [comment]
20-40 is the release group

**Comment by Electr0Fi** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-55-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@207bd7ac693e4beee0b72d4d3a05e0c7aca95300
Link to Log: https://gist.github.com/9278025ecd2f30c29492
### ERROR
```
Thread-24 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/aperture/.sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/home/aperture/.sickrage/sickbeard/webserve.py", line 1987, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "/home/aperture/.sickrage/sickbeard/webserve.py", line 1947, in getEpisodes
    'overview': Overview.overviewStrings[showObj.getOverview(int(searchThread.segment.status or -1))]})
KeyError: None

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
