### ISSUE TITLE
[APP SUBMITTED]: None

### ISSUE THREAD

**Issue by johnscrub** [SiCKRAGETV/sickrage-issues#1154]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
No Log available with ERRORS: 
### ERROR
```
TRAKTCHECKER :: Unable to create the folder H:\TV Shows\Heroes Reborn, can't add the show
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Thraxis** [comment]
Heroes Reborn is still in Development and does not have any Season / Episode information.  Even if it does create the folder it will continue to throw an error.

> 2015-04-08 18:49:06 SHOWQUEUE-ADD :: Show Heroes Reborn is on theTVDB but contains no season/episode data.

**Comment by johnscrub** [comment]
I am so sorry i did not mean to send that as an error it was the one after that.PLease accept my apologies.Great program am loving it!!
Date: Wed, 8 Apr 2015 19:05:51 -0700
