### ISSUE TITLE
[APP SUBMITTED]: None

### ISSUE THREAD

**Issue by johnscrub** [SiCKRAGETV/sickrage-issues#1155]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
No Log available with ERRORS: 
### ERROR
```
CHECKVERSION :: git symbolic-ref -q HEAD returned : fatal: bad config file line 1 in .git/config
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
Corrupted git config file, recreate via git clone
