### ISSUE TITLE
Web Setting for GZip Compression

### ISSUE THREAD

**Issue by kkotowick** [SiCKRAGETV/sickrage-issues#1156]
Branch: SickRage/master
Commit hash: 669046ea40a7a26a6121a1b07721f3c1c3cf5b10
Your operating system and python version: Windows Server 2012
What you did: Set auto-update
What happened: It overwrote my GZip settings
What you expected: It to respect my GZip settings

Because I use SickRage with a reverse proxy on Windows IIS, I have to disable GZip compression in order for it to work (going into webserverInit.py and changing the 'true' to 'false'). However, whenever SickRage updates itself, it overwrites that configuration change and sets it back to 'true' again. It would be very, very nice if GZip compression was a setting stored somewhere that won't get overwritten every time it grabs the new commit.

**Comment by abeloin** [comment]
You can set in your web.config:
```
<serverVariables>
        <set name="HTTP_Accept-Encoding" value="" />
</serverVariables>
```

See https://blogs.iis.net/carlosag/archive/2010/04/01/setting-up-a-reverse-proxy-using-iis-url-rewrite-and-arr.aspx

**Comment by miigotu** [comment]
Low priority but a simple fix. I'll bring the setting out into config.ini, but not into the web GUI since I think this will be extremely rarely used.

**Comment by JustMaier** [comment]
Hey thanks for this. I was in the same situation and this was a really helpful fix.

**Comment by kkotowick** [comment]
I'd like to re-open this issue. Although I see that the setting has now been moved to the config.ini file, it doesn't seem to be taking effect. Although I change the "web_use_gzip" setting to "False", it's still using gzip. Seems like it isn't loading the value from the config file properly, or not applying it properly?

**Comment by miigotu** [comment]
@kkotowick use web_use_gzip = 0

**Comment by kkotowick** [comment]
Ah, yes, that worked. If it can't handle "True" and "False" then, the default value in the repository should be changed from "True" to "1".

**Comment by miigotu** [comment]
@kkotowick already ahead of you. xD

@SiCKRAGETV/moderators 
Shouldnt we make check_setting_int convert "True" to 1 and False to "0" to make it work either way?
