### ISSUE TITLE
[APP SUBMITTED]: Unrar: No file extracted, check the parent folder and destination file permissions

### ISSUE THREAD

**Issue by FlyGuy94** [SiCKRAGETV/sickrage-issues#1158]
### INFO
Python Version: **2.7.9 (default, Mar 23 2015, 00:07:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@8e03cae4e9d29d8d31a343b90ba20e08d35f541d
Link to Log: https://gist.github.com/bd38878bd175e212f9e0
### ERROR
```
POSTPROCESSER :: Failed Unrar archive top.gear.us.109.dvdrip.subs-ncaxa.rar: Unrar: No file extracted, check the parent folder and destination file permissions.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by FlyGuy94** [comment]
Just unrared it manually. The file is fine and not corrupted..

**Comment by abeloin** [comment]
This rar doesn't contain any video file only subs

**Comment by Symbiot78** [comment]
Hi

I am seeing this exact error. This issue started showing up a while ago.. unfortunately I cannot say when but before this SR was unrar'ing fine and I have not made changes to permission of parent or similar.

**Comment by Symbiot78** [comment]
2015-05-28 08:20:13 ERROR    POSTPROCESSER :: Failed Unrar archive greys.anatomy.1101.720p-dimension.rar: Unrar: No file extracted, check the parent folder and destination file permissions.
AAGenericRARError
AA    raise GenericRARError
AA  File "/opt/sickbeard/lib/unrar2/unix.py", line 259, in _check_returncode
AA    self._check_returncode(proc.returncode)
AA  File "/opt/sickbeard/lib/unrar2/unix.py", line 70, in init
AA    RarFileImplementation.init(self, password)
AA  File "/opt/sickbeard/lib/unrar2/__init__.py", line 100, in __init__
AA    rar_handle = RarFile(os.path.join(path, archive))
AA  File "/opt/sickbeard/sickbeard/processTV.py", line 376, in unRAR
AATraceback (most recent call last):
2015-05-28 08:20:13 ERROR    POSTPROCESSER :: Failed Unrar archive greys.anatomy.1101.720p-dimension(1).rar: Unrar: Generic Error
