### ISSUE TITLE
[APP SUBMITTED]: Rarbg Too many requests per minute

### ISSUE THREAD

**Issue by Rouzax** [SiCKRAGETV/sickrage-issues#1159]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Rarbg Too many requests per minute.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Rouzax** [comment]
Not sure if this is my fault or if this requires an API change?

These are my search settings.
![image](https://cloud.githubusercontent.com/assets/4103090/7067212/c849c012-dec9-11e4-88d8-f659576609ff.png)

**Comment by abeloin** [comment]
Workaround in https://github.com/SiCKRAGETV/SickRage/pull/1728 which retry after a certain amount of time.

You can replace your copy of sickbeard/providers/rarbg.py by this one: https://raw.githubusercontent.com/SiCKRAGETV/SickRage/develop/sickbeard/providers/rarbg.py

**Comment by Rouzax** [comment]
I replaced the file and will let you know any results

**Comment by Rouzax** [comment]
I haven't had the error since I replaced the rarbg.py

**Comment by abeloin** [comment]
The PR will be merged on Sunday in master

**Comment by abeloin** [comment]
@Rouzax PR merged in master, please update

**Comment by Rouzax** [comment]
Already done, thanks.

**Comment by fernandog** [comment]
@Rouzax did it fixed?

**Comment by Rouzax** [comment]
I had the modified rarbg.py for 4 days and didn't encounter the error since then.

**Comment by abeloin** [comment]
@Rouzax Thanks
