### ISSUE TITLE
[Feature Request] Add new regex for shows named "Series 2 08of10"

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#1160]
MVGroup is a well know releaser of mainly documentaries that releases on EZTV
The feature request is to support its numbering which is like this "Ultimate Airport Dubai Series 2 08of10 720p x264 HDTV-MVGroup" it says the episode number in relation to the last one ( becouse they are documentaries they have its number of episodes already set ) 
Probably take the season number "Series 2" and the episode number 08 from "08of10" and ignore the "of10" 
Not sure if its possible but thanks in advanced

**Comment by hadees** [comment]
:+1:

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
