### ISSUE TITLE
Error Post processing mede8er

### ISSUE THREAD

**Issue by shadowjustice** [SiCKRAGETV/sickrage-issues#1166]
Hi,

I think the following fix is causing errors with me:

https://github.com/SiCKRAGETV/sickrage-issues/issues/927

**Branch: Master**
Commit hash: 669046ea40a7a26a6121a1b07721f3c1c3cf5b10

**Hardware**: Excito B3
Operating system:
Distributor ID: Debian
Description: Debian GNU/Linux 6.0.8 (squeeze)
Release: 6.0.8
Codename: squeeze

**Python version:**
Python 2.6.6 (r266:84292, Dec 27 2010, 21:57:32)
[GCC 4.4.5 20100902 (prerelease)] on linux2

**What did I do?**
Auto processing, manual post processing

**What I expect?**
Message with prowl with the message that the video is downloaded and renamed and stuff...

**What do I get?**

AATypeError: write() got an unexpected keyword argument 'xml_declaration'
AA data.write(nfo_file, encoding="utf-8", xml_declaration = True)
AA File "/home/programs/programs/sickbeard/sickbeard/metadata/mede8er.py", line 438, in write_ep_file

Full log:

http://pastebin.com/mwMXfiKJ

Error section:

http://pastebin.com/R1um1wFm

Third log:

http://pastebin.com/CmaBzx0B

**Comment by fernandog** [comment]
@shadowjustice full logs please

**Comment by shadowjustice** [comment]
Source post updated!

http://pastebin.com/eWyLrSN8

**Comment by shadowjustice** [comment]
On a side note I generate lots of logs :o


![image](https://cloud.githubusercontent.com/assets/4602808/7088138/d40fe2fa-df91-11e4-8a5d-25cf7d5a947d.png)

**Comment by TagForce** [comment]
Strange... data.write calls the write definition from the ElementTree class...
Which is defined as:
```
def write(self, file_or_filename,
              # keyword arguments
              encoding=None,
              xml_declaration=None,
              default_namespace=None,
              method=None):
```

**Comment by abeloin** [comment]
@shadowjustice Which notifier are active? Because in the tile it says mede8er but you says you expect a prowl notification.

**Comment by shadowjustice** [comment]
I checked it twice only Prowl is active

**Comment by abeloin** [comment]
Sorry I just realize it's failling while writing the metadata

**Comment by shadowjustice** [comment]
Even though I am a Programmer  of job I must admit that diving into the Python of sickrage feels a bit difficult.  Most of the reason lays in the fact that I have no knowledge of Python sadly. 

Verstuurd vanaf mijn iPhone

**Comment by Thraxis** [comment]
Like TagForce I can't find anything inherently wrong with the call that it would be giving an unexpected keyword.

**Comment by shadowjustice** [comment]
Shall I do a complete delete and download the code again ? If after the reset (without importing previous configuration) the error maybe would go away. Maybe something's wrong with the pyc's (don't know anything about perl as stated before). Are the pyc's synced with GitHub?

Verstuurd vanaf mijn iPhone

**Comment by miigotu** [comment]
No shadowjustice, .pyc files are "compiled" python scripts which are created at first run of a py script to speed up loading of the script on subsequent runs.  

From this [http://stackoverflow.com/a/15839646 | StackOverflow Answer] pyc files are 'supposed' to update themselves when the py changes, although I have noticed cases where they did not.
To make sure, from your SickRage dir, you could safely do:
 'find . -type f -name '*.pyc' -delete'

I am almost certain that this will not solve your issue, but it never hurts to try.

**Comment by miigotu** [comment]
Found the problem. See http://stackoverflow.com/a/19738566 as it is dependant on your version of python. This is why some people see the issue and some do not.

Working on a fix and will PR soon.

**Comment by miigotu** [comment]
Eh, ignore the #1744, accidentally created the PR to master.

**Comment by shadowjustice** [comment]
This afternoon i shall switch to develop and test it.

**Comment by miigotu** [comment]
Hmm, it is not pulled into official SR develop branch yet, but you could clone my fork and switch to the miigotu:fix-mede8er-elementtree-1166 and test it

**Comment by shadowjustice** [comment]
lol just pressed the button ...I'll check out your branch after I switched
to develop

**Comment by miigotu** [comment]
rename your current install dir like:
mv SickRage SickRage-Official
git clone git@github.com:miigotu/SickRage.git
cd SickRage
git fetch
git checkout fix-mede8er-elementtree-1166
git pull

then copy your databases and config.ini to this install, and run 'python SickBeard.py'

If all done right you should have a permanent warning that you aren't on the master branch or w/e, and your settings, shows should be there so you can test the fix out/

**Comment by miigotu** [comment]
Ahaha, sorry I'm definitely tired right now. Much easier to just make the change in the install you have.

Change line 393 in sickbeard/metadata/mede8er.py to 

data.write(nfo_file, encoding="UTF-8")

Notice UTF is in capitals, important.

**Comment by abeloin** [comment]
@shadowjustice @miigotu PR merged in develop, will be merged in master Sunday. Please test on Sunday after update

**Comment by shadowjustice** [comment]
It will be in the evening but I will test again.

**Comment by abeloin** [comment]
Merged in master please update and test

**Comment by shadowjustice** [comment]
Tested and approved XML format:

![image](https://cloud.githubusercontent.com/assets/4602808/7224140/8e44ef0a-e72e-11e4-99c0-a46ae80878c9.jpg)
