### ISSUE TITLE
[APP SUBMITTED]: None

### ISSUE THREAD

**Issue by stenavage** [SiCKRAGETV/sickrage-issues#1172]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
No Log available with ERRORS: 
### ERROR
```
CHECKVERSION :: git fetch origin returned : fatal: unable to access 'https://github.com/SiCKRAGETV/SickRage.git/': SSL read: error:00000000:lib(0):func(0):reason(0), errno 10054
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
The peer(github.com) closed the connection, retry
