### ISSUE TITLE
[Question] Trakt rolling frequency

### ISSUE THREAD

**Issue by gborri** [SiCKRAGETV/sickrage-issues#1174]
@abeloin i've seen that you have set frequency no less that 4 hours. I have a bit of confusion. the tracktChecker process that is more complex than trakt rolling is scheduled hourly. I had defined new process for trakt rolling just to have the possibility to schedule it more frequently than traktChecker.
Letting it start every 15 minutes means to make 2 query to trakt site, that's it. i think that is not so heavy load for it.

**Comment by abeloin** [comment]
I asked in a previous thread why does it need to run every 15 mins which you didn't answered. See: https://github.com/SiCKRAGETV/SickRage/pull/1711. So I went ahead and change the code to a minimum of 4 hours. The why maybe crystal clear for you but for me it isn't hence the reason I asked my question.

Also did had time to do the wiki page for that feature?

**Comment by gborri** [comment]
Not yet for the wiki. I have understood from your question that the point
was to change the default value not to block frequency to 4 hours. The
reason is that I not always have sick beard on and want to have start to
download the episode as soon as I ha e watched one. Four our later means
I'm sleeping and SickRage is off. This way it starts to download always
when started SickRage.

Giovanni
Il 10/apr/2015 19:03, "Alexandre Beloin" <notifications@github.com> ha
scritto:

**Comment by abeloin** [comment]
@gborri ok, then we should add an option to start trakt_rolling at startup like show updater. Also we can change from 4 hours to 1 hour, this way your 3 episodes buffer should be enough

**Comment by gborri** [comment]
"should be enough" depend on seeders....
