### ISSUE TITLE
Unable to manually search for better quality episode because quality of all found episodes is 'Unknown'

### ISSUE THREAD

**Issue by alaorath** [SiCKRAGETV/sickrage-issues#1175]
I may be going about this the wrong way, but I can't figure out if this is a bug or expected behavior.

The latest episode of Elementary downloaded with "poor" quality (under 200meg for 720p).  So after editing the list of providers down to only one, I forced a manual scan (by clicking the mangifying glass next to the episode).

An Error popped up indicating "No downloads were found
Couldn't find a download for Elementary - 3x19 - One Watson, One Holmes"

Checking the log file for more detail:
```
2015-04-10 13:31:33 INFO     SEARCHQUEUE-MANUAL-255316 :: [showrss] :: Performing episode search for Elementary
2015-04-10 13:31:33 DEBUG    SEARCHQUEUE-MANUAL-255316 :: [showrss] :: Checking if found episode 3x19 is wanted at quality Unknown
2015-04-10 13:31:33 DEBUG    SEARCHQUEUE-MANUAL-255316 :: [showrss] :: any,best = [4, 32, 128] [] and found 32768
2015-04-10 13:31:33 DEBUG    SEARCHQUEUE-MANUAL-255316 :: [showrss] :: Don't want this quality, ignoring found episode
2015-04-10 13:31:33 DEBUG    SEARCHQUEUE-MANUAL-255316 :: [showrss] :: Skipping Elementary.3x19.One.Watson,.One.Holmes.720p because we don't want an episode that's Unknown
```

I've tried:
* deleting the files from disk (re-scanning), then marking the episode as "Wanted" - same result
* editing the showrss feed from "user specific" the the most basic/generic one: http://showrss.info/feeds/all.rss
* double-checking the rss feed actually has a 720p version of the episode (it does, and the log indicates it's found... but as "Unknown" quality?!

I'm not sure what else to try... For this case, I've worked around the issue by manually downloading the episode directly, and using the "manual Post-process" with the option "Mark Dir/Files as priority download" to overwrite the offending episode.

**Comment by fernandog** [comment]
@alaorath what's your wanted quality in show setting?

**Comment by alaorath** [comment]
Originally it was set as 'HD720p', but I've tried also as 'HD'.

This is with the latest tagged build (v4.0.15)

I think maybe it's not parsing the showrss.info feed correctly (hence the "unknown" log statement, but I'm not sure.

**Comment by abeloin** [comment]
@alaorath Add `&raw=true` at the end of the rss url, it will display torrent name instead of a human readable one.

Ref: https://showrss.info/?cs=blog&id=46

**Comment by alaorath** [comment]
Seems like this would be the same as using the "all.rss" feed (I posted above) and setting the Custom Torrent Provider search element to 'showrss:rawtitle' but I'll give it a shot.

Either way, I figure it's user error and not a bug, I appreciate the quick reply. :)

**Comment by abeloin** [comment]
In another blog entry they were explaining that they removed rawtitle for the new interface and people were complaining about it.

Right or wrong, the important thing is that the issue is resolve and you can enjoy those tv show. :)
