### ISSUE TITLE
Search returns no results when multiple episodes of show are marked as "Wanted"

### ISSUE THREAD

**Issue by goatbased** [SiCKRAGETV/sickrage-issues#1176]
Hey fellas,
This one is a relatively recent issue that I've been tracking. I've noticed that when I select more than a single episode of a show and mark it as "Wanted," often it will go to backlog and search will never find it.

When I mark all of these as "ignored" or "skipped" and then one by one mark each episode to "Wanted," each episode is searched for, snatched, and downloaded. I just did this with Kroll Show a few minutes ago and have included my logs here.

Full steps to replicate this exact situation:
1) Episodes 7 & 8 are already downloaded and marked as such (though it doesn't seem to matter, it could be a whole season)
2) Mark all other episodes (in this example, episodes 1-6 and 9-11) in the season as "Wanted"
3) Backlog search is initiated. I can see it try each episode and then FALLBACK SEASON PACK SEARCH INITIATED ... in the log.  In both cases, nothing is snatched
4) Regardless of how long I wait for next backlog to run, nothing is snatched.

To resolve the issue, I've been issuing a "Wanted" to each and every episode that I'm looking for (which finds individual episodes without issue) but It would seem that there's some funky logic going on in the decision to choose full season or episode search.

I've replicated the issue with a number of settings in the providers. The logs I've included use Season search fallback: enabled and Season search mode: episodes only.

SR Version: 	BRANCH: (master) / COMMIT: (669046ea40a7a26a6121a1b07721f3c1c3cf5b10) 
Python Version:	2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]

Logs at https://www.dropbox.com/sh/5tqhb91yxsyw509/AACQCzeTP1byjnVXgPMZmawca?dl=0

Thanks!

**Comment by abeloin** [comment]
Some provider doesn't support season search, this will need to be fixed

**Comment by goatbased** [comment]
@abeloin Strange thing is, if I select only two episodes out of, let's say 10, in a season, it appears that SR attempts a season search instead of running episode search.

**Comment by abeloin** [comment]
Yes, if you look 1 episode it will search for show.s01e01 but 2 and more it will try s01 instead(assuming it will behave like a wild card). Some of the providers need to be redone because of that.

**Comment by goatbased** [comment]
Ah, gotcha. Makes sense.

**Comment by fernandog** [comment]
@goatbased what were the providers that caused this error?

**Comment by goatbased** [comment]
@fernandog When I attempted to run the bulk search on Kroll, I had KAT, Pirate Bay, RARBG, and a custom RSS feed for showrss.info enabled.  I realized that my logs disappeared from dropbox so I just put them back. Link to logs is at https://www.dropbox.com/sh/5tqhb91yxsyw509/AACQCzeTP1byjnVXgPMZmawca?dl=0

**Comment by fernandog** [comment]
@TagForce is this related to the season PR you did?

**Comment by TagForce** [comment]
@fernandog It might very well be... Especially since it finds episodes when you set 1 episode to wanted (which causes it to actually use the eponly search strings) makes me believe my PR will fix it.
