### ISSUE TITLE
[APP SUBMITTED]: None

### ISSUE THREAD

**Issue by jbrady21** [SiCKRAGETV/sickrage-issues#1178]
### INFO
Python Version: **2.6 (r26:66721, Oct  2 2008, 11:06:43) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-post2008Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-80379 :: Unable to parse The.Big.Bang.Theory.Season.4.HDTV.480p.H264-20-40 into a scene name. If it's a valid one log a bug.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
Dupe #1152
