### ISSUE TITLE
[Feature Request] Multithread searching & Backlogging

### ISSUE THREAD

**Issue by markheloking** [SiCKRAGETV/sickrage-issues#118]
I'd like to have multithreaded searching and backlogging so the whole process doesn't take ages like it does right now with a big database and a lot of providers.
Do a thread per provider that goes over all the shows (so you don't do 10 shows at the same time at a single provider, that would put too much strain on the server), and another threat (per show? one for all shows? not sure) that checks per-show if there is a result ready with a good enough quality and download that. For backlog you can first check if all providers finished for this episode and download the best quality (instead of the first it finds).

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
