### ISSUE TITLE
[Feature Request]  Add notification message for upcoming episode 

### ISSUE THREAD

**Issue by badloop** [SiCKRAGETV/sickrage-issues#1180]
Would love to be able to configure sickrage to notify me when an episode of one of my shows is coming up.  I would assume this would be configurable on a per show basis and allow for a configurable amount of time prior to the air date.  Example - Big Bang Theory notifies me 1 day before a new episode is going to air.  The Voice never notifies me because that stupid show is always on.  Etc.

**Comment by fernandog** [comment]
Did you try SeriesGuide?
there is notifications and a lot more stuff.

**Comment by WebSpider** [comment]
:-1:

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
