### ISSUE TITLE
[APP SUBMITTED]: column network_name is not unique

### ISSUE THREAD

**Issue by krash1220** [SiCKRAGETV/sickrage-issues#1182]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
Link to Log: https://gist.github.com/dded7f0f95dc441a052d
### ERROR
```
SHOWUPDATER :: Fatal error executing query: column network_name is not unique
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@krash1220 did you manually edited/change you database ?

**Comment by fernandog** [comment]
@abeloin do you know if is a database user problem or SR problem?

**Comment by krash1220** [comment]
I had so many errors that I just decided to start fresh. It was probably something I did.






Sent from Windows Mail





From: Fernando
Sent: ‎Monday‎, ‎April‎ ‎13‎, ‎2015 ‎11‎:‎42‎ ‎AM
To: SiCKRAGETV/sickrage-issues
Cc: krash1220





@krash1220 did you manually edited/change you database ?

**Comment by fernandog** [comment]
@krash1220 everything ok now?
