### ISSUE TITLE
[APP SUBMITTED]: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by Glider3** [SiCKRAGETV/sickrage-issues#1184]
### INFO
Python Version: **2.7.9 (default, Mar 22 2015, 23:46:21) [GCC 4.3.2]**
Operating System: **Linux-2.6.32.12-ppc-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
No Log available with ERRORS: 
### ERROR
```
Thread-194 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2828, in changeEpisodeStatuses
    self.setStatus(cur_indexer_id, '|'.join(to_change[cur_indexer_id]), newStatus, direct=True)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1690, in setStatus
    epObj = showObj.getEpisode(int(epInfo[0]), int(epInfo[1]))
ValueError: invalid literal for int() with base 10: ''

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
Please provide more logs and what were you trying to do in SR when this happened

**Comment by fernandog** [comment]
@Glider3 please do a full update in all your shows (use mass update)
