### ISSUE TITLE
[Rarbg] :: Unable to connect to Rarbg provider: error ('Connection aborted.', gaierror(-2, 'Name or service not known'))

### ISSUE THREAD

**Issue by Zzaap** [SiCKRAGETV/sickrage-issues#1186]
Python Version: 2.7.9 (default, Mar 23 2015, 00:29:05) [GCC 4.6.4]
Operating System: Linux-3.2.40-armv7l-with-glibc2.4
Locale: UTF-8
SR Version: 	BRANCH: (master) / COMMIT: (669046ea40a7a26a6121a1b07721f3c1c3cf5b10) 

NOTE: i have the patched rarbg.py from https://github.com/SiCKRAGETV/sickrage-issues/issues/1131

AA*onnectionError: ('*onnection aborted.', gaierror(-2, 'Name or service not known'))
AA    raise *onnectionError(err, request=request)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/requests/adapters.py", line 415, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/requests/sessions.py", line 573, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/requests/sessions.py", line 461, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/requests/sessions.py", line 473, in get
AA    response = self.session.get(self.urls['token'], timeout=30, verify=False)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/rarbg.py", line 110, in _doLogin
AATraceback (most recent call last):
2015-04-11 10:53:44 ERROR    SEAR*HQUEUE-DAILY-SEAR*H :: [Rarbg] :: Unable to connect to Rarbg provider: error ('*onnection aborted.', gaierror(-2, 'Name or service not known'))

**Comment by abeloin** [comment]
The message Name or service not known mean your DNS server wqas unablle to find and IP address for that name. Check that your machine has a working dns server to make queries to
