### ISSUE TITLE
[APP SUBMITTED]: None

### ISSUE THREAD

**Issue by larstomas** [SiCKRAGETV/sickrage-issues#1189]
### INFO
Python Version: **2.7.9 (default, Mar 23 2015, 00:07:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-REFRESH :: There was an error trying to retrieve the image, aborting
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
Retry refreshing the show
