### ISSUE TITLE
[APP SUBMITTED]: 

### ISSUE THREAD

**Issue by FlyGuy94** [SiCKRAGETV/sickrage-issues#1190]
### INFO
Python Version: **2.7.9 (default, Mar 23 2015, 00:07:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@5fa1ba2ecef0ddd5551898575c8d86bc67c9cce5
Link to Log: https://gist.github.com/e180fd0c484b2170aed4
### ERROR
```
POSTPROCESSER :: Failed Unrar archive marvels.daredevil.s01e07.720p.webrip.x264-2hd.rar: Unrar: Archive CRC Error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
Corrupted rar archive, please check your file manually. If file ok reopen issue

**Comment by FlyGuy94** [comment]
Thanks for the heads up the file is indeed corrupt.
