### ISSUE TITLE
[APP SUBMITTED]: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by pct00** [SiCKRAGETV/sickrage-issues#1191]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Unable to move file c:\intel\Stargate.Atlantis.S05E18.HDTV.XviD-LOL.avi to Z:\Stargate Atlantis\Stargate Atlantis - Season 05\Stargate Atlantis - S05E18 - SD TV - Identity.avi: [Errno 13] Permission denied
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
Check your permission

**Comment by pct00** [comment]
permissions were fine
i manually went to the dsestination folder and deleted file, after that sr was able to process?

**Comment by abeloin** [comment]
Maybe related to https://github.com/SiCKRAGETV/sickrage-issues/issues/793

**Comment by pct00** [comment]
seems to be the same issue,

i', not running sr as a service, just a normal process with my windows user that has permissions across the network

issue seems to be only when the file already exists at destination (could not confirm if it was same size or not)

running manually the post processing with the priority option, or manually deleting the destination file seems to solve "fix" the error, as in the file is processed successfully

**Comment by fernandog** [comment]
@TagForce does priority option force the copy/move even if the file already exists ?

**Comment by TagForce** [comment]
@fernandog Yes, if you select manual PP and check the force priority checkbox it will replace an existing file (no further checks, is_priority is set to true). If PP finds a download in snatch history for the current file, it will still check some stuff (is_priority is false means it will check if the status is one of snatched, or if the new_ep_quality > old_ep_quality and not unknown), but it will most likely be a priority download.

**Comment by fernandog** [comment]
@tagfore In this issue. What should we do?

**Comment by TagForce** [comment]
@fernandog I don't know... It should copy it, whether it's manual or automatic PP... There's no difference in the 2 code-paths (both simply call ProcessDir())

**Comment by fernandog** [comment]
@Tagforce shouldnt give "file already processed" instead of permission?

**Comment by TagForce** [comment]
@fernandog Probably not as both messages are in a completely different code-path. If it's trying to copy then it passed all the checks for it to be processed. Already processed comes way earlier in the processing run. If that doesn't return it's already processed, then it will continue to check if the file should really be copied/moved, and in the end it tries to copy/move the file, which throws this error.

**Comment by fernandog** [comment]
@pct00 do you always get this message or it was once?

**Comment by pct00** [comment]
@fernandog it always repeats until i "manually" fix it (deleting the destination file or forcing process with priority)

so if i leave the file on the folder for automatic post processing every 10 minutes it will try to process, fail, and give error

**Comment by fernandog** [comment]
@pct00 but if the file is in the destination, it was already processed. Are you using copy or move?

**Comment by fernandog** [comment]
@pct00 PP is set to move or copy?

**Comment by fernandog** [comment]
@TagForce 

if user downloaded a file and it's still seeding. User have PP to move. PP starts and move will fail. SR will fallback to copy. Next PP cycle, file it's not seeding anymore. SR tries to move. Move will fail because of permission.

Is that it ?
How to handle that?
When moving, SR checks if the file already exists or if is already PP?

**Comment by pct00** [comment]
@fernandog there is A file n the destination, a file i want to replace, 
SR downloaded a new file. after the download finished i manually move the new file to a "to process" folder so there are no problems of souce file being in use/seeding

my PP is set to move
