### ISSUE TITLE
[Feature Request] Change ShowUpdate process to use API latest updated shows

### ISSUE THREAD

**Issue by Thraxis** [SiCKRAGETV/sickrage-issues#1192]
The current show update process creates queries every show that could possibly have had an update and queries the indexers for that information.  Both TVDB and TVRage provide the API calls to get the updates that have occured since a specific time.

This would allow us to update all shows regardless of status every night as well as increase the speed of the check as it would only be requesting data from the indexers for the shows / episodes that have had a change.

http://services.tvrage.com/info.php?page=latest_updates
http://thetvdb.com/wiki/index.php?title=Programmers_API

**Comment by WebSpider** [comment]
We would need to start tracking in db when the last update was done. Since that's currently not in the DB schema, this would require a DB update, unless we 'abuse' xem's last update, that we do check.

**Comment by fernandog** [comment]
nice!

updates_day.xml
All updates within the last 24 hours
Uncompressed 161k

updates_day.zip
All updates within the last 24 hours
Compressed 20k

updates_week.xml
All updates within the last 7 days (One Week)
Uncompressed 600k

updates_week.zip
All updates within the last 7 days
Compressed 64k

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
