### ISSUE TITLE
[APP SUBMITTED]: No episode number found

### ISSUE THREAD

**Issue by noze2000** [SiCKRAGETV/sickrage-issues#1195]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-REFRESH :: No episode number found in /share/Disk 6/TV/Star Trek The Next Generation/Star Trek The Next Generation - Season 7/japhson-sttngs07e22-720p.mkv, ignoring it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@noze2000 do you have debug enabled in general settings?

**Comment by noze2000** [comment]
now i do:)

**Comment by fernandog** [comment]
@noze2000 your naming pattern seems wrong.

**Comment by noze2000** [comment]
I dont rename only move. Would that be an influence?

**Comment by fernandog** [comment]
@noze2000 how did you downloaded that? SR can't recognize the naming pattern

**Comment by noze2000** [comment]
Old show - old name I guess. Japhson was around back then i guess with this naming pattern. I guess I could manaually rename these and let sickrage do its thing.

**Comment by fernandog** [comment]
Rename and try again please

**Comment by noze2000** [comment]
yes that worked - as expected
