### ISSUE TITLE
FR: Subtitle options add hearing impaired.

### ISSUE THREAD

**Issue by NilsNojje** [SiCKRAGETV/sickrage-issues#1196]
An options to choose the type of subtitle would be nice.
I'd really like an option to enable or in my case, disable subtitles for hearing impaired.

**Comment by neoatomic** [comment]
@NilsNojje what do you mean with type.? .srt .sub or .idx ? Could you explain it a little better.?

**Comment by NilsNojje** [comment]
@neoatomic No thats not what I'm talking about.
Looking at for example http://www.opensubtitles.org/en/search/sublanguageid-eng/imdbid-4120726 .. some subs have a symbol indicating that the subtitle is for hearing impaired. As in the sub describe not only talk, but music and other sound events.

**Comment by neoatomic** [comment]
@NilsNojje thanks for the clarification.
In Sickrage we use Subliminal, and on the to-do list we are planning to overhaul/update it
to a newer version. So we will keep your request in mind.
 
However for functionality/features we are depended from the Subminimal developers. 
If you want to make sure this feature will be possible you can best do a feature request at there project page. https://github.com/Diaoul/subliminal

If you get any answer/feedback, could you than update this post.?

**Comment by NilsNojje** [comment]
@neoatomic It looks like the functionality is already there.
http://pythonhosted.org/subliminal/api/api.html  <--- Version 0.7.4
https://github.com/Diaoul/subliminal/issues/343

**Comment by fernandog** [comment]
so you have to wait we upgrade the versions
@abeloin

**Comment by neoatomic** [comment]
@NilsNojje Thanks for checking.Than this would be possible. 
However we first need to update subliminal as we now are running  .6.x if i recall right.
Currently cant say when that will be done, the developer we have tons of work and FR's to implement. But if you have any experience with coding Python.. We can use all help we can...

**Comment by jackiass** [comment]
Just chiming in to say this is also a feature I am missing a lot. Have no coding xp, so can't help, sorry.
