### ISSUE TITLE
Font color changed for dark theme

### ISSUE THREAD

**Issue by neoatomic** [SiCKRAGETV/sickrage-issues#1198]
Just updated, and noted that the font color has changed on some pages.
Looks like "History" and "Failed Downloads" pages are effected. See attached screen-shot. 
Needles to say black fonts on a black background are hard to read. :)

```

SR Version: 	BRANCH: (develop) / COMMIT: (10a5842596a43c8f0010e1312e8a385395c0eee7)
SR User:	sickbeard-custom
SR Locale:	('en_US', 'UTF-8')
SR Config file:	/usr/local/sickbeard-custom/var/config.ini
SR Database file:	/usr/local/sickbeard-custom/var/sickbeard.db
SR Cache Dir:	/usr/local/sickbeard-custom/var/cache
SR Log Dir:	/volumeUSB4/usbshare/Temp
SR Arguments:	['--daemon', '--pidfile', '/usr/local/sickbeard-custom/var/sickbeard-custom.pid', '--config', '/usr/local/sickbeard-custom/var/config.ini', '--datadir', '/usr/local/sickbeard-custom/var/', '--nolaunch']
Python Version:	2.7.9 (default, Mar 22 2015, 23:23:23) [GCC 4.6.4]
```

![sr](https://cloud.githubusercontent.com/assets/7928052/7105464/3e006f56-e11b-11e4-9f61-b357cc4d741d.png)

**Comment by Thraxis** [comment]
The back out of the original FR#1015 code should have fixed this, and the new PR https://github.com/SiCKRAGETV/SickRage/pull/1754 should get the column selector working correctly without stomping on other pages.

**Comment by fernandog** [comment]
PR reverted

**Comment by neoatomic** [comment]
Updated to SR Version: 	BRANCH: (develop) / COMMIT: (e917dc613ac17943dbe795331325c228c3d77f05) 
Now all is showing correctly again.
