### ISSUE TITLE
[APP SUBMITTED]: timed out

### ISSUE THREAD

**Issue by minzenmay** [SiCKRAGETV/sickrage-issues#1199]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
No Log available with ERRORS: 
### ERROR
```
FINDSUBTITLES :: Error occurred when downloading subtitles: timed out
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
As the errors says a simple timeout. 
Probably the site was off line or your Internet was off line for a moment.
