### ISSUE TITLE
[Feature Request]  Add login ability for kickass.to torrent provider

### ISSUE THREAD

**Issue by Dobbs84** [SiCKRAGETV/sickrage-issues#1200]
I would like to have my login for kickass.to to be used so can track the downloads and later leave feedback on the torrents. If the config could be added to enable login that would be the best way I believe. But if there is a easy way to do this manually in the code please let me know.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
