### ISSUE TITLE
[APP SUBMITTED]: None

### ISSUE THREAD

**Issue by krash1220** [SiCKRAGETV/sickrage-issues#1203]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
Link to Log: https://gist.github.com/968a9c6297c7ad0a8f05
### ERROR
```
SHOWQUEUE-ADD :: There was an error trying to retrieve the image, aborting
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@krash1220 do you have debug enabled in general settings?
