### ISSUE TITLE
Kodi: SR generated tag(indexer) in NFO are lost when re exported by third party tools

### ISSUE THREAD

**Issue by miigotu** [SiCKRAGETV/sickrage-issues#1205]
It should use the selected indexer on the right side, and ? should not appear. If Show Name is ?, you have to go through more screens to add the show.
On /addShows/existingShows/
![image](https://cloud.githubusercontent.com/assets/390379/7107728/a3b67838-e123-11e4-9491-9703dd5b3fe2.png)

I originally had `<indexer>` set in these nfo, it gets removed either by exporting the library from Kodi (to update watched status in nfo), or saving nfo with MediaElch.

Will fix and remove the need for `<indexer>` so that we don't need to worry about 3rd part applications breaking it.

**Comment by T-2000** [comment]
Ah my mistake,  I was viewing this topic as to viewing existing shows were information regarding to be aired episodes are missing information (episode title in this case) and not being shown in the TV show episode listing. If this happens the auto download will not work. I'm guessing this might be a known issue and I've posted under the wrong topic. Sorry about that!

**Comment by T-2000** [comment]
In fact it's similar behaviour as to issue #1157

**Comment by miigotu** [comment]
Unrelated issue, see #1157

**Comment by abeloin** [comment]
@miigotu Maybe I don't understand but this behavior is what I would expect. The column is label "Show Name (tvshow.nfo)", so if the info isn't available it will put a question mark and pass it to "add a new show" where you can choose the proper show name.

**Comment by Thraxis** [comment]
@abeloin The .nfo files created by sickrage include an <indexer></indexer> tag to along with the <id></id> tag it's non-standard and other programs tend to strip it out.  What it does is  sets the indexer used automatically which is supposed to make it easier for the add existing show to re-import a show that was removed.

**Comment by abeloin** [comment]
Ok, then why not use <id>and <episodeguide> has tag to store the required data?
```
<episodeguide>
        <url cache="73255.xml">http://www.thetvdb.com/api/1D62F2F90030C444/series/73255/all/en.zip</url>
</episodeguide>
<id>73255</id>
```

http://kodi.wiki/view/NFO_files/tvshows

**Comment by miigotu** [comment]
I've worked on this issue before, and it is only half fixed so far.

The problem is that is <indexer></indexer> is not set, sickrage is supposed to still be able to read <name> and other tags. The ? is from a protection feature to prevent assuming tvdb id or tvrage id and having the wrong show info downloaded. What should happen if indexer is missing is checking thetvdb using the id from the nfo and then checking against the <name> in the nfo. if it does not match, check tvrage, and if still does not match then the id is invalid and should be forced the user to interact.  IMHO <indexer> can be avoided altogether.

**Comment by TagForce** [comment]
Shouldn't we change the filename for the metadata file SR itself uses to store its info?
tvshow.nfo is used by other tools, so that'll always be a problematic name for SR to use.
sr_show.nfo is better, I think.

**Comment by miigotu** [comment]
@TagForce with this patch it is not necessary to even add `<indexer>` to the nfo, so if it is removed by a third party it will not hurt anything in SR. Adding a new file to people's library is extreme and not a good option.

**Comment by TagForce** [comment]
@miigotu The reason I came up with the extra filename is that not only KODI uses that file name, but also the Boxee box, for which we currently don't have a metadata handler but may add one in the future.

If we are using the tvshow.nfo for information we need to either:
- Make sure it only uses information that is compatible with all other metadata clients that use that file, so that if users select those in SR, it doesn't cause problems with those clients.
- Store the info elsewhere.

**Comment by miigotu** [comment]
@TagForce exactly, thats why my patch makes it possible for us to remove `<indexer>` tag from being created in the nfo at all, and therefore there is no extra information added to the nfo by sickrage.  That way we simply use the info that is already there.

As far as boxee box goes, it runs xbmc/kodi afaik, and uses the same nfo file structure.

**Comment by TagForce** [comment]
@miigotu I agree

**Comment by abeloin** [comment]
@miigotu Yes

**Comment by miigotu** [comment]
ok, ill work on a PR over the next week to rm `<indexer>` completly

**Comment by abeloin** [comment]
@miigotu I've put it as a tentative for 4.0.18, ok for you?

**Comment by miigotu** [comment]
@abeloin sure, I'll try to get some free time to do this in the next few days.

**Comment by miigotu** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1804
