### ISSUE TITLE
[APP SUBMITTED]: None

### ISSUE THREAD

**Issue by rodrigompaz** [SiCKRAGETV/sickrage-issues#1206]
### INFO
Python Version: **2.7.6 (default, Sep  9 2014, 15:04:36) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]**
Operating System: **Darwin-14.1.0-x86_64-i386-64bit**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
Link to Log: https://gist.github.com/c6fe8195f53aced46aaf
### ERROR
```
Thread-51 :: Failed to detect KODI version for '127.0.0.1:3000', check configuration and try again.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@rodrigompaz master = develop. no difference.

**Comment by Thraxis** [comment]
Are you using Plex Home Theater (PHT) ?

**Comment by rodrigompaz** [comment]
@Thraxis Nope, I'm on PMS..
