### ISSUE TITLE
[APP SUBMITTED]: No JSON object could be decoded

### ISSUE THREAD

**Issue by topper2830** [SiCKRAGETV/sickrage-issues#1210]
### INFO
Python Version: **2.7.9 (default, Mar 23 2015, 00:07:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@281409d366b228a455879e02b2d55d3967db29e4
Link to Log: https://gist.github.com/6fca829394fd6bfc989f
### ERROR
```
SEARCHQUEUE-MANUAL-80379 :: [Rarbg] :: Rarbg json load failed.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
@topper2830 Disable any proxy in rarbg configuration

**Comment by fernandog** [comment]
@abeloin should we force disable proxy for rarbg?

**Comment by fernandog** [comment]
@topper2830 please reply or will close
