### ISSUE TITLE
Redirect loop on loading SickRage

### ISSUE THREAD

**Issue by Arcanemagus** [SiCKRAGETV/sickrage-issues#1211]
Branch: Master
Commit hash: 281409d366b228a455879e02b2d55d3967db29e4
Your operating system and python version: FreeBSD, Python 2.7.9
What you did: Attempted to load the web interface
What happened: All browsers report a redirect loop
What you expected: The web interface

After updating to 4.0.15 I got a push telling me the following changes had been applied:
https://github.com/SiCKRAGETV/SickRage/compare/669046ea40a7a26a6121a1b07721f3c1c3cf5b10...281409d366b228a455879e02b2d55d3967db29e4

When loading the interface I now get an infinite redirect loop...
https://sickrage.localnet.local:8081/ redirects to /home/
https://sickrage.localnet.local:8081/home/ redirects to /

I'm currently attempting to debug this, but maybe somebody else will spot the cause first.

**Comment by Arcanemagus** [comment]
Well, after switching directories around to different copies of SickRage it seems to have disappeared. Closing this as it is no longer an issue.

**Comment by abeloin** [comment]
@Arcanemagus This situation can happen when you update SR without restarting. The template are compiled at runtime, so you can do modification on the fly. But for the python file SR needs to be restarted. So you ended up with a new version of the home page template and the old version of python code to generate the page. If the template request a variable that isn't provided by the old code still in memory, you end up with an error which redirect to / which redirect to home.

**Comment by Arcanemagus** [comment]
I thought the update process restarted the service automatically? I tested several browsers including 3 that had never accessed SR before, so a local cache wasn't the issue.

**Comment by abeloin** [comment]
Sometime the git pull pass but SR fail to restart.
It isn't a question of cache, but the difference between py and tmpl file processing.

Py file are generated when python start, so updating them later won't be reflected until you start the program again.

In case of tmpl, each time you accessed it , it can recompile the code if the file changed.

Can you see the issue arise? If a change in a tmpl file depend on the result of a new function in a py file and you access the tmpl before the program is restarted you access the old copy of the py.

Hence the error
