### ISSUE TITLE
[APP SUBMITTED]: u'\u2013'

### ISSUE THREAD

**Issue by Errodoma** [SiCKRAGETV/sickrage-issues#1213]
### INFO
Python Version: **2.7.8 (default, Oct 20 2014, 15:05:19) [GCC 4.9.1]**
Operating System: **Linux-3.16.0-34-generic-x86_64-with-Ubuntu-14.10-utopic**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@281409d366b228a455879e02b2d55d3967db29e4
Link to Log: https://gist.github.com/abd9892dd2e85986059b
### ERROR
```
SEARCHQUEUE-BACKLOG-74852 :: [NextGen] :: Error while searching NextGen, skipping: –
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Errodoma** [comment]
Additional log entries not in the submitted logs:

 AA
AAKeyError: u'\u2013'
AA    return ''.join(map(quoter, s))
AA  File "/usr/lib/python2.7/urllib.py", line 1288, in quote
AA    searchURL = self.urls['search'] % (urllib.quote(search_string), self.categories)
AA  File "/home/esben/.sickrage/sickbeard/providers/nextgen.py", line 200, in _doSearch
AA    itemList += self._doSearch(curString, 'eponly', len(episodes), epObj=epObj)
AA  File "/home/esben/.sickrage/sickbeard/providers/generic.py", line 293, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/home/esben/.sickrage/sickbeard/search.py", line 480, in searchProviders
AAKeyError: u'\u2013'
AA    return ''.join(map(quoter, s))
AA  File "/usr/lib/python2.7/urllib.py", line 1288, in quote
AA    searchURL = self.urls['search'] % (urllib.quote(search_string), self.categories)
AA  File "/home/esben/.sickrage/sickbeard/providers/nextgen.py", line 200, in _doSearch
AA    itemList += self._doSearch(curString, 'eponly', len(episodes), epObj=epObj)
AA  File "/home/esben/.sickrage/sickbeard/providers/generic.py", line 293, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/home/esben/.sickrage/sickbeard/search.py", line 480, in searchProviders
AATraceback (most recent call last):

**Comment by fernandog** [comment]
@Errodoma please set locale to UTF-8
