### ISSUE TITLE
When editing a show the info language defaults back to English.

### ISSUE THREAD

**Issue by neoatomic** [SiCKRAGETV/sickrage-issues#1217]
When editing a show the info language defaults back to English.
So when i have a show witch i have already setup for "nederlands" and i edit the show the drop-box jumps back to English.

```
SR Version: 	BRANCH: (develop) / COMMIT: (0025c000a29232574f9f273ddc0a6e11125a020b)
SR User:	sickbeard-custom
SR Locale:	('en_US', 'UTF-8')
SR Config file:	/usr/local/sickbeard-custom/var/config.ini
SR Database file:	/usr/local/sickbeard-custom/var/sickbeard.db
SR Cache Dir:	/usr/local/sickbeard-custom/var/cache
SR Log Dir:	/volumeUSB4/usbshare/Temp
SR Arguments:	['--daemon', '--pidfile', '/usr/local/sickbeard-custom/var/sickbeard-custom.pid', '--config', '/usr/local/sickbeard-custom/var/config.ini', '--datadir', '/usr/local/sickbeard-custom/var/', '--nolaunch']
Python Version:	2.7.9 (default, Mar 22 2015, 23:23:23) [GCC 4.6.4]
```

![1](https://cloud.githubusercontent.com/assets/7928052/7115432/f060bb4c-e1e8-11e4-8969-70674242c37f.png)
![2](https://cloud.githubusercontent.com/assets/7928052/7115433/f0663e6e-e1e8-11e4-90a8-b5acd4b7b601.png)

**Comment by abeloin** [comment]
@neoatomic Please test PR

**Comment by neoatomic** [comment]
@abeloin This fixed it. Thank you.

**Comment by abeloin** [comment]
PR merged, please update

**Comment by neoatomic** [comment]
@abeloin updated Develop, and PR still working fine/resolved.

**Comment by abeloin** [comment]
@neoatomic Thanks
