### ISSUE TITLE
Broken symbolic link raises an OSError exception

### ISSUE THREAD

**Issue by ElmerLastdrager** [SiCKRAGETV/sickrage-issues#1224]
When a series' directory contains a broken symlink (pointing to a non-existing file), an OSError is raised and the user is unable to view details of the series.

**Reproduce**:
1. add a show
2. create a broken symlink.
From the command line:
> $ cd DIRECTORY
> $ ln -s nowhere moo
> $ ls -l
> lrwxrwxrwx 1 x x  7 Apr 13 20:02 moo -> nowhere
> drwxrwxr-x 2 x x 14 Apr 12 20:50 Season 1
> $ $ file moo
> moo: broken symbolic link to `nowhere'
3. in SickRage, go to Shows -> Show List  and click on the show. Nothing will happen.

The logfile shows the following exception:
```
2015-04-13 19:18:31 Thread-36 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/x/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/home/x/SickRage/sickbeard/webserve.py", line 1254, in displayShow
    return t.respond()
  File "/home/x/SickRage/cache/cheetah/_xxx_gui_slick_interfaces_default_displayShow_tmpl.py", line 654, in respond
    _v = VFN(VFFSL(SL,"sickbeard.helpers",True),"pretty_filesize",False)(sickbeard.helpers.get_size(VFFSL(SL,"showLoc",True)[0])) # u'$sickbeard.helpers.pretty_filesize(sickbeard.helpers.get_size($showLoc[0]))' on line 246, col 46
  File "/home/x/SickRage/sickbeard/helpers.py", line 1412, in get_size
    total_size += ek.ek(os.path.getsize, fp)
  File "/home/x/SickRage/sickbeard/encodingKludge.py", line 58, in ek
    result = func(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
  File "/usr/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '/zzz/nowhere'
```

**Comment by fernandog** [comment]
@ElmerLastdrager getsize will get the space available in the location of the symlink or the physical file directory?

**Comment by ElmerLastdrager** [comment]
@fernandog Python's getsize will return the file size for a given path, thereby following symlinks. It does not return the available space.

In my case (I normally do not use symlinks), an old and broken symlink in the directory of the show caused this error.

**Comment by abeloin** [comment]
@ElmerLastdrager PR merged in develop, will be in master on Sunday
