### ISSUE TITLE
File delete confirmation

### ISSUE THREAD

**Issue by bobrap** [SiCKRAGETV/sickrage-issues#1226]
Do you think it would be possible to add a dialog box to confirm that you want to delete a file. Being the brilliant idiot I am, I was in mass update and wanted to remove a bunch of shows and checked delete instead of remove. Well, all gone now. An "Are you sure you big dummy?" would have stopped me from deleting all my files. Thanks.

**Comment by Thraxis** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1843
