### ISSUE TITLE
[APP SUBMITTED]: global name 'MULTI_EP_RESULT' is not defined

### ISSUE THREAD

**Issue by Nativedude** [SiCKRAGETV/sickrage-issues#1227]
### INFO
Python Version: **2.7.9 (default, Dec 11 2014, 04:42:00) [GCC 4.9.2]**
Operating System: **Linux-3.18.5-unRAID-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@281409d366b228a455879e02b2d55d3967db29e4
Link to Log: https://gist.github.com/b56dbfc5d68b3bc7d212
### ERROR
```
SEARCHQUEUE-BACKLOG-251085 :: [IPTorrents] :: Error while searching IPTorrents, skipping: global name 'MULTI_EP_RESULT' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by gborri** [comment]
@Nativedude see #1201 and SiCKRAGETV/SickRage@1758

**Comment by Nativedude** [comment]
Cool, I'll report back once I see it in develop and update.
Thanks

On Mon, Apr 13, 2015 at 5:10 PM, gborri <notifications@github.com> wrote:

> @Nativedude <https://github.com/Nativedude> see #1201
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/1201> and
> SiCKRAGETV/SickRage@1758
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/1227#issuecomment-92499679>
> .
>



-- 
Sincerely,
    Adam Michael Durham
    (757) 742-3261
