### ISSUE TITLE
[APP SUBMITTED]: None

### ISSUE THREAD

**Issue by isingthr4iam** [SiCKRAGETV/sickrage-issues#1234]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@281409d366b228a455879e02b2d55d3967db29e4
Link to Log: https://gist.github.com/7d30747eba62f8f5a930
### ERROR
```
Thread-56 :: git config remote.origin.url https://github.com/SiCKRAGETV/SickRage.git returned : error: could not lock config file .git/config: File exists, treat as error for now
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Either you have some git process already running that is locking it such as TortoiseGIT, XCode, GitX, etc, OR your permissions are screwed up, OR you interrupted git at some point, OR you checked out the repo with one user and then ran SR as a different user.

Try removing .git/config.lock if it exists, and double check your owner/permissions.

**Comment by fernandog** [comment]
@miigotu if you think its a support/question feel free to label

**Comment by abeloin** [comment]
No feedback from OP, clossing
