### ISSUE TITLE
Unable to parse to scene name

### ISSUE THREAD

**Issue by raymondtrueman** [SiCKRAGETV/sickrage-issues#1238]
SR Version:	BRANCH: (master) / COMMIT: (281409d366b228a455879e02b2d55d3967db29e4)
Python Version:	2.7.9 (default, Mar 23 2015, 00:06:48) [GCC 4.3.2]

Hi,

I got this error today:
2015-04-14 01:52:55 SEARCHQUEUE-BACKLOG-82696 :: Unable to parse Sons.Of.Anarchy.S02.720p.BluRay.x264.AVCHD into a scene name. If it's a valid one log a bug.

It seems valid to me, I'm not sure why it couldn't parse it and snatch it.

Please let me know if you need detailed logs, however I don't think its needed as the its very clear from the error message what the problem is

Thanks

**Comment by fernandog** [comment]
@raymondtrueman "Sons Of Anarchy" is the full name of the show or in the show page it appears with year or country?  If so add "Sons Of Anarchy" to scene exceptions

**Comment by Thraxis** [comment]
There is no episode number in that filename

**Comment by fernandog** [comment]
@Thraxis maybe it's a season pack but he needs to check scene exception

**Comment by Thraxis** [comment]
I'll post the fix tonight.  There's a broken RegEx

**Comment by raymondtrueman** [comment]
Thank you very much @Thraxis 
@fernandog The scene exceptions was the first thing I checked and it didn't have any but I also figured it didn't need any because on the show page the full name of the show is already correct as "Sons of Anarchy". There were never any year specification. And the release is a season pack yes

**Comment by Thraxis** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1773

Not going to say it will fix 100% of everything... but it should help with more matches that were failing before

**Comment by abeloin** [comment]
@raymondtrueman Please provide the full log of that search.

**Comment by raymondtrueman** [comment]
Unfortunately that search log is no longer available. When the error happens again I will post the log for you
