### ISSUE TITLE
[Feature Request] Add Mass update "info language" option

### ISSUE THREAD

**Issue by Diak** [SiCKRAGETV/sickrage-issues#1239]
Hi,

Can you add the possibility to mass update the "info language" of tv series please ?

I put in in French when i configured first my series and know i have to change them in english and i have lots of them...

Thanks.

**Comment by miigotu** [comment]
I have looked at the code for mass update/edit shows. I believe it could be improved and agree changing info language should be possible in that method.

imho, massEdit should use editShow in a for loop to make it easier to keep both able to change the same settings.

This will probably not be implemented in the near future, unless someone else decides to pick it up.

**Comment by fernandog** [comment]
@miigotu can you please check some open confirmed issues and try to fix any? We have A LOT of them

**Comment by Diak** [comment]
If it's in the roadmap it's good for me too ;)
Thanks for the answer by the way.

**Comment by sioban** [comment]
Hi, what is the status of this Feature Request ?

**Comment by WebSpider** [comment]
It is currently not planned by regular developers, who are currently focussing on improving performance for end users and lowering the load on indexers.

With the amount of users using SR, our impact on the indexers increases, so we have to start paying more attention to efficiency.

So: Don't expect this to be picked up automatically within 8 weeks. Feel free to develop this yourself and a PR, which we will happily accept!

**Comment by sioban** [comment]
Thanks for the answer.
I was asking as I've just installed SR in replacement of SB and I misconfigured the locale info parameter.
Guess I have to do it manually.

Regards

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
