### ISSUE TITLE
[Feature Request] Use FooTable (jQuery plugin) in HTML tables on smaller devices

### ISSUE THREAD

**Issue by dsoms** [SiCKRAGETV/sickrage-issues#124]
It would be awesome to use the jQuery plugin **FooTable** in HTML tables on mobile version.

http://themergency.com/footable/

Regards @dsoms

**Comment by Thraxis** [comment]
@fernandog @abeloin I believe the use of TableSorter has superseded this request... would the reflow widget be the suitable replacement? 

http://mottie.github.io/tablesorter/docs/example-widget-reflow.html

**Comment by fernandog** [comment]
What is reflow?

**Comment by Thraxis** [comment]
@fernandog Changes the table when on a small screen the examples on the link I posted should give you an idea

**Comment by abeloin** [comment]
@Thraxis Yes

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
