### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/home/bobm/downloads/Bates.Motel.S03E06.720p.HDTV.x264-KILLERS/Bates.Motel.S03E06.720p.HDTV.x264-KILLERS.mkv'

### ISSUE THREAD

**Issue by bmatulovich** [SiCKRAGETV/sickrage-issues#1240]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:38) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-49-generic-i686-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@281409d366b228a455879e02b2d55d3967db29e4
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Unable to move file /home/bobm/downloads/Bates.Motel.S03E06.720p.HDTV.x264-KILLERS/Bates.Motel.S03E06.720p.HDTV.x264-KILLERS.mkv to /media/bobm/Tv Shows/Bates Motel/Bates Motel - 3x06 - Norma Louise.mkv: [Errno 2] No such file or directory: '/home/bobm/downloads/Bates.Motel.S03E06.720p.HDTV.x264-KILLERS/Bates.Motel.S03E06.720p.HDTV.x264-KILLERS.mkv'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@bmatulovich check if the file was already moved
