### ISSUE TITLE
Anime Searching is not working

### ISSUE THREAD

**Issue by tutti21** [SiCKRAGETV/sickrage-issues#1244]
Hello,

I have 20 animes currently in sickrage, all update perfectly but Baby Steps not.

I added Baby Steps and it loaded Season 1 with no problem but when it tries to download Season 2 it find nothing.

Yes I have ticked annime and scene numbering on
have no filter on subgroup 
have tried it with no quality filter
I have set the find tvshows to TVDB

https://gist.github.com/tutti21/112661cacae903b3edf8

SR Version: 	BRANCH: (master) / COMMIT: (281409d366b228a455879e02b2d55d3967db29e4)
SR User:	media
SR Locale:	(None, None)
SR Config file:	/var/db/sickrage/config.ini
SR Database file:	/var/db/sickrage/sickbeard.db
SR Cache Dir:	/var/db/sickrage/cache
SR Log Dir:	/var/db/sickrage/Logs
SR Arguments:	['--datadir', '/var/db/sickrage', '-d', '--pidfile', '/var/run/sickrage/sickrage.pid', '-q', '--nolaunch']
Python Version:	2.7.8 (default, Dec 15 2014, 02:33:48) [GCC 4.2.1 20070831 patched [FreeBSD]]

FreeNAS-9.3-STABLE-201504100216

**Comment by abeloin** [comment]
The problem is that SR use thexem to know the season names: http://thexem.de/xem/show/2181

But the data is empty, you need to fill in the data on xem

**Comment by Thraxis** [comment]
The scene mapping to add season 2 is pending on XEM.

**Comment by tutti21** [comment]
Ok thx, I try that. Or waiting till its not pending anymore, and I now know whats the problem :)

**Comment by Thraxis** [comment]
@tutti21 Baby Steps Season 2 mapping was approved on http://thexem.de
