### ISSUE TITLE
chmod issue on NTFS network disk

### ISSUE THREAD

**Issue by mijnham** [SiCKRAGETV/sickrage-issues#1248]
Just want to register an issue I've encountered the last few days. I've running Sickrage (BRANCH: (master) / COMMIT: (281409d366b228a455879e02b2d55d3967db29e4) ) on a Synology NAS. Worked perfectly with my NTFS external HDD as post processing target location AS LONG AS it is attached via USB (local volume). However, since I moved the external HDD to another place in my network and mounted it to the Synology via CIFS (only way possible via DSM), I get the error below. 

I've deduced that this is because Sickrage thinks it's a Linux based disk and tries to do a chmod in the postprocessing. This is not working anymore due to the CIFS mount ('directory not found'). Could this error be removed somehow? It sounds like a false positive, everything is still working. 

One exception : If download station stores the file on the nas & Sickrage needs to move it to the mounted share, the process fails earlier for the same reason. But if download station stores the file directly on the mounted folder, the move operation is no problem - I just get the error below. 

Is there some way to detect that the CIFS mounted folder is ntfs and that chmod should not be done? 

Error:

Error in log: 
2015-04-14 07:48:19 POSTPROCESSER :: Failed to set permission for /volume2/Media/Ext/Series/The Blacklist/Season 01/The.Blacklist.S01E03.Wujing.1080p.WEB-DL.DD5.1.H.264-NTb.tbn to 666
2015-04-14 07:48:14 POSTPROCESSER :: Failed to set permission for /volume2/Media/Ext/Series/The Blacklist/Season 01/The.Blacklist.S01E03.Wujing.1080p.WEB-DL.DD5.1.H.264-NTb.nfo to 666

**Comment by Thraxis** [comment]
Try adding noperm to your mount options

**Comment by mijnham** [comment]
I'm not able to get a mount working via the CLI on the Synology. Even if I would get it working, Synology resets the fstab file on reboot, removing my custom mount. That's why I'm using the mount functionality in DSM but that one doesn't allow to add params like noperm. 

Or do I miss something?

**Comment by abeloin** [comment]
@mijnham See the following: http://forum.synology.com/enu/viewtopic.php?f=39&t=9352
