### ISSUE TITLE
web download

### ISSUE THREAD

**Issue by ugokanain** [SiCKRAGETV/sickrage-issues#1249]
Have noticed several sites dedicated to tv series. The way things go, this will probably be short lived, but could SR take advantage of this, and allow to dl from these sites?

**Comment by abeloin** [comment]
@fernandog Honestly, this should be closed as it's gonna be PITA to maintain(web scrapping changing site), support of download manager or download directly(which mean we have to implement a download manager from scratch)

**Comment by ugokanain** [comment]
SR doesn't need to dl the files. Rather take advantage there are sites that have the episodes, since many on nntp are being taken down. Recently lost my storage, and realized that it isn't as easy as it used to be. Something more in addition to nzbs and torrents

**Comment by abeloin** [comment]
@ugokanain Can you define "dedicated to tv series" and provide example? Maybe we don't have the definition.

**Comment by ugokanain** [comment]
http://www.boxtv.com/tv
http://serieszone.com
http://www.cbsnews.com/videos/topics/60-minutes/

**Comment by TagForce** [comment]
@ugokanain @fernandog @abeloin We shouldn't support those sites, for a few reasons:
- SR is, by definition, a search tool. It will not, itself, download anything other than a link to information.
Using these sites, it would need to download the files itself, which makes it a different kind of tool, subject to different kinds of scrutiny from all the organisations ending in 'Association of America' and their worldwide counterparts (like BREIN in the Netherlands). If we don't allow SR to download from them, then there's no point in doing anything with them. All the other information those sites provide is already in SR.

- Sites like these are untrustworthy by their very nature. Most of those types of sites do not allow direct downloading, require the use of a 'special' download manager, or use 'file cabinet'-sites that cap their download limits for non-paying customers. Not to mention all the damn shady advertisements usually found on them.

- The quality of the videos is questionable. One of the USPs of SickRage is the fact that it can download files in whatever quality you set it to download. These sites usually don't mention the quality in which a video is uploaded, and for the most part the quality is somewhere around the lowest quality SR supports.

- Most of those sites are rather limited in their offer. They only carry a few shows, or concentrate mostly on foreign tv shows (like boxtv.com focusses on Indian TV).

So... My recommendation would be to leave these sites out of SR.

**Comment by ugokanain** [comment]
This was just an idea, and those were examples. The trouble is that nntp is also not entirely reliable, since many parts go missing. Since SR already deals with nzb and torrents, it would be a last effort to find what you are looking for.

If you prefer, you can close this.
