### ISSUE TITLE
[APP SUBMITTED]: locale changed during initialization

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#1250]
### INFO
Python Version: **2.7.8 (default, Oct 20 2014, 15:05:29) [GCC 4.9.1]**
Operating System: **Linux-3.16.0-34-generic-i686-with-Ubuntu-14.10-utopic**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@b8bb0939a3eb11d7d3aae567bef76259549631d0
Link to Log: https://gist.github.com/c7d1815e451032aa938e
### ERROR
```
Thread-48 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/supergonkas/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/home/supergonkas/SickRage/sickbeard/webserve.py", line 3561, in index
    return t.respond()
  File "/home/supergonkas/SickRage/cache/cheetah/_home_supergonkas_SickRage_gui_slick_interfaces_default_history_tmpl.py", line 299, in respond
    curdatetime = VFN(VFFSL(SL,"datetime.datetime",True),"strptime",False)(str(VFFSL(SL,"hItem",True)["date"]), VFFSL(SL,"history.dateFormat",True))
  File "/usr/lib/python2.7/_strptime.py", line 300, in _strptime
    _TimeRE_cache = TimeRE()
  File "/usr/lib/python2.7/_strptime.py", line 188, in __init__
    self.locale_time = LocaleTime()
  File "/usr/lib/python2.7/_strptime.py", line 77, in __init__
    raise ValueError("locale changed during initialization")
ValueError: locale changed during initialization

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@matigonkas what did you do?

your locale is unknown. Try set to utf-8

**Comment by abeloin** [comment]
strptime isn't thread safe, so it need a lock. http://stackoverflow.com/questions/4625149/fixed-strptime-exception-with-thread-lock-but-slows-down-the-program

**Comment by matigonkas** [comment]
@fernandog isnt my locale already utf8? When it happen i wasnt doing anything iir, only refreshing the history page from time to time to see if some downloads would pop up
~$ locale
LANG=pt_PT.UTF-8
LANGUAGE=pt:pt_BR:en
LC_CTYPE="pt_PT.UTF-8"
LC_NUMERIC="pt_PT.UTF-8"
LC_TIME="pt_PT.UTF-8"
LC_COLLATE="pt_PT.UTF-8"
LC_MONETARY="pt_PT.UTF-8"
LC_MESSAGES="pt_PT.UTF-8"
LC_PAPER="pt_PT.UTF-8"
LC_NAME="pt_PT.UTF-8"
LC_ADDRESS="pt_PT.UTF-8"
LC_TELEPHONE="pt_PT.UTF-8"
LC_MEASUREMENT="pt_PT.UTF-8"
LC_IDENTIFICATION="pt_PT.UTF-8"
LC_ALL=

**Comment by fernandog** [comment]
@abeloin didn't get it. if is a thread issue, why this is the first time it happend?

**Comment by abeloin** [comment]
@fernandog That is the joy of thread safty issue, it's unpreditable

**Comment by abeloin** [comment]
@matigonkas I've just spotted an error in your local:
`LANGUAGE=pt:pt_BR:en`
change it to:
`LANGUAGE=pt_PT.UTF-8`
