### ISSUE TITLE
[APP SUBMITTED]: None

### ISSUE THREAD

**Issue by FusionAge** [SiCKRAGETV/sickrage-issues#1252]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:38) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-48-generic-i686-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@281409d366b228a455879e02b2d55d3967db29e4
Link to Log: https://gist.github.com/497282bfd9c374d28b46
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: Deluge: Authentication Failed
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Authentication Failed
