### ISSUE TITLE
Option to disable chmod setting permission on file copy/move

### ISSUE THREAD

**Issue by xInsertx** [SiCKRAGETV/sickrage-issues#1254]
Hello,

Can we have the option to disable setting permissions on file copy/move during post-processing. If i copy to a folder that inherits permissions; when it chmod's them they either break giving everyone access rather than the group or file my error log with Failed to set permission for /path/to/file.mkv to 664.

For example:
/path/to/file.mkv >> /path/to/kids/file.mkv # this would be fine because permission allow 'everyone' to read the files anyways
/path/to/file2.mkv >> /path/to/parents/file2.mkv # this breaks permissions for files granting everyone group read access.

Now if you take it a step further and use advance windows acl's it fails to set permissions completely and just spams your error log with:
Failed to set permission for /path/to/file.mkv to 664

this happens on any linux/bsd system i've tested using advance windows acl's that mount the local file system rather than mount_smbfs (which is not possible in all cases)

Due to the nature of symlink/hardlinks im unsure if you would want to change this; but for copy/move it makes sense.

Some Examples:

Freebsd Jail where you mount the filesystem rather than mount cifs share #error message
Freebsd Jail where you mount using mount_smbfs #breaks permissions
Docker where you internally mount the filesystem rather than cifs share #error message
Docker where you mount using mount_smbfs #breaks permissions
Ubuntu w/ advance windows acl's turned on & sickrage installed natively #breaks permissions

Hope that makes sense

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1248

**Comment by fernandog** [comment]
@TagForce what do you think?

**Comment by TagForce** [comment]
@fernandog Yes, we can make this optional... I'd rather work around the issue so that it can set permission though.

**Comment by abeloin** [comment]
Dupe https://github.com/SiCKRAGETV/sickrage-issues/issues/110
