### ISSUE TITLE
[APP SUBMITTED]: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:581)

### ISSUE THREAD

**Issue by ryanf86** [SiCKRAGETV/sickrage-issues#1256]
### INFO
Python Version: **2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]**
Operating System: **Darwin-14.3.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@281409d366b228a455879e02b2d55d3967db29e4
Link to Log: https://gist.github.com/9699c569fb59384dfe80
### ERROR
```
SEARCHQUEUE-MANUAL-294169 :: [Rarbg] :: Unable to connect to Rarbg provider: error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:581)
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@ryanf86 disable proxy for RARBG

**Comment by ryanf86** [comment]
Proxy is not enabled

Have enabled restarted, disabled and restarted again still getting the same error

**Comment by fernandog** [comment]
@ryanf86 please full read this. It's the same issue

https://github.com/SiCKRAGETV/sickrage-issues/issues/978
