### ISSUE TITLE
[Feature Request] Add support for Skin/Template/Theme

### ISSUE THREAD

**Issue by hive** [SiCKRAGETV/sickrage-issues#1259]
While the codebase looks like it has been split up into templates. (slick?). And then future broken down into interface/default.

There is no easy way to install a new 'skin'. 

While ideally the business logic wouldn't be in the templates, as a staring point it would be great if it was possible to create/install a new skin using the gui. Which would allow the overloading of the css/images/js folders. If possible it would be great if this was done by cascading from slick. 

# Stage 1 (Skin): 

**Objective :** User can switch skins easily.

**Example Usage :** User creates new skin called 'ice' with in the GUI, this allows for the user to switch to said theme, using the gui, all css/images/js gets loaded from gui/ice rather then gui/slick. 

**Reasoning :** This will allow the community to skin the site, improving the user experience, there are many many we developers/deisgners/frontend devs, out there not having to have python experience to skin will open up the  community resources available to the project.

# Stage 2 (Import) : 

**Objective :** Add the ability to import and export above skins.

**Example 1 :** Developer create a new theme, then is able to share it with the community. 

**Example 2 :** User goes on to website, can choose a new skin, and easily import it to the SickRage App. 

**Reason :** This will be the second  and most important stage in implementing and expanding the community

# Stage 3 (Theme): 

**Objective :** Remove business logic from templates, instead of using python for display logic introduce the use of partials loading to be done by controller. Potentially introduce well known/documented templating language. 

**Example :** Front end developer uses GUI to create a new theme, using just html,css,js they are then able to completely customise the UX (User experience). 

**Reasoning :** This full separation will allow the project to no longer rely on python devs to improve the project, this in turn will allow back end devs to focus their skill set on features, and front developers to then use their skill set to the best advantage, ie. creating the best possible UI/UX. 

*TLDNR: Allow themes be added easily, its good, means more people can help the project, gives best result, increases community.*

###Examples
![image](https://cloud.githubusercontent.com/assets/239140/7158863/54751d10-e3c1-11e4-8fbd-1bfea628719a.png)
![image](https://cloud.githubusercontent.com/assets/239140/7158913/d74ad78e-e3c1-11e4-9a33-45723b6586c3.png)
![image](https://cloud.githubusercontent.com/assets/239140/7158939/0bdc90e6-e3c2-11e4-984d-bdcbfdc6cf96.png)
![image](https://cloud.githubusercontent.com/assets/239140/7158992/60826274-e3c2-11e4-828e-d063b5699d10.png)

**Comment by OmgImAlexis** [comment]
@hive I'm still working on refactoring the gui, is there anything specific that you think would help this?

**Comment by MGaetan89** [comment]
I think we should wait for the translations before supporting new themes. Otherwise all themes would need to be updated again.

**Comment by hive** [comment]
Not if it's done correctly, fist stage of theme implementation would be the styling/scripts. Which would have no effect upon the html and consequently the i18n translations.

**Comment by hive** [comment]
Unfortunately I don't have an specifics to add that would be helpful, I'm a php back end developer, not Python. Sorry.

**Comment by OmgImAlexis** [comment]
@MGaetan89 if there's stuff I can do with separating the files now then we might as well. That's more of what I was getting at. I've already started moving all of the js to their own files instead of being in the mako ones. Other than redoing the file paths I think we're relatively close to having "theme support".

**Comment by MGaetan89** [comment]
I didn't look in detail at all your PR, but an other point to check in the JS, would be the proper separation between JS/markup. Meaning that the JS should work independently of the markup (so nothing like `$('div span.class p')`). I know you've been doing some refactoring to use data attributes, so that help.

**Comment by OmgImAlexis** [comment]
Yeah the data attributes should fix what you're saying. None of the js should be relying on the layout of the page as we're not really doing anything layout related. Obviously if the theme wanted to remove table formatting, etc. it could but if it's just cosmetic changes they should be able to change the classes, etc. and the js should still work.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
