### ISSUE TITLE
[Feature Request] Check if PP folder is a higher level of shows folder

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#1260]
Check if the "Show root directories" is a sub-folder of PP and don't let user save the PP folder. Like the renaming regex where the field gets red.

If the PP was already saved before this feature, don't run PP and give a ERROR asking user to change PP folder.

**Comment by fernandog** [comment]
@TagForce what do you think?

**Comment by TagForce** [comment]
@fernandog Agreed. Trying to think of a better way to warn users of their incorrect pp folder. Not running PP with an error in the log is going to be something that people will miss...

**Comment by fernandog** [comment]
@TagForce 

but if the actual user setup could cause problems, we should abort PP, isn't?
Maybe add a DIV like the "New update"

can we use this script to test if folders are parent?
looks like it's compatible with symbolic links.
http://stackoverflow.com/a/17624617

**Comment by fernandog** [comment]
@TagForce I did a test in windows and linuxs, seems ok.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
