### ISSUE TITLE
Redirection loop

### ISSUE THREAD

**Issue by beschoenen** [SiCKRAGETV/sickrage-issues#1261]
I just updated to the latest master and i'm getting a redirection loop. iI can see the login page, but after that it goes into the loop.
Sickrage is running on my synology.
Python: 2.7.9
Commit: 281409d366b228a455879e02b2d55d3967db29e4

It seems to be fixed on the develop branch, though
Commit: e64c9a0134ad5fa89f030148a72af91a9e5e18af

**Comment by fernandog** [comment]
@beschoenen
How did you updated? command line?
did you restarted?

**Comment by beschoenen** [comment]
Yes, via command line:
``git fetch``
``git checkout develop``

after going back to the master branch it worked again.

**Comment by fernandog** [comment]
Dont update that again.
we have UI for that.
