### ISSUE TITLE
[APP SUBMITTED]: <ProtocolError for api.opensubtitles.org/xml-rpc: 503 Service Unavailable>

### ISSUE THREAD

**Issue by DarkCompiled** [SiCKRAGETV/sickrage-issues#1262]
### INFO
Python Version: **2.7.9 (default, Mar 23 2015, 00:29:05) [GCC 4.6.4]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@281409d366b228a455879e02b2d55d3967db29e4
No Log available with ERRORS: 
### ERROR
```
Thread-50 :: Error occurred when downloading subtitles: <ProtocolError for api.opensubtitles.org/xml-rpc: 503 Service Unavailable>
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Service Unavailable
