### ISSUE TITLE
[Feature Request] Add support multi-season snatches

### ISSUE THREAD

**Issue by PhuriousGeorge** [SiCKRAGETV/sickrage-issues#1264]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:38) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-49-generic-i686-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@281409d366b228a455879e02b2d55d3967db29e4
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-79485 :: Unable to parse How.Its.Made.S01.S14.Complete.XviD into a scene name. If it's a valid one log a bug.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by PhuriousGeorge** [comment]
Apologies for the additional issues opened. I meant to just include them all here

2015-04-14 03:48:59 SEARCHQUEUE-BACKLOG-72879 :: Unable to parse Animaniacs.S05E26E23E25.DVDRip.XviD-DEiMOS into a scene name. If it's a valid one log a bug.
2015-04-14 03:41:24 SEARCHQUEUE-BACKLOG-72879 :: Unable to parse Animaniacs.S05E14E12E21E13.DVDRip.XviD-DEiMOS.Repost into a scene name. If it's a valid one log a bug.
2015-04-14 03:40:21 SEARCHQUEUE-BACKLOG-72879 :: Unable to parse Animaniacs.S05.DVDRip.XviD into a scene name. If it's a valid one log a bug.

**Comment by fernandog** [comment]
@SiCKRAGETV/moderators we are getting a lot of issues of:

Unable to parse **** into a scene name. If it's a valid one log a bug.

It seems it's a regex issue and/or bad naming episodes. Please close all of them and reference this issue. Let's keep this open

**Comment by TagForce** [comment]
@fernandog The error is coming from the getSeasonNZBs function in nzbSplitter.py

This line:
```
regex = '([\w\._\ ]+)[\. ]S%02d[\. ]([\w\._\-\ ]+)[\- ]([\w_\-\ ]+?)' % season
```

Is used to parse the name, but is not matching any of the files I'm trying to feed it using regex testers on the web...

**Comment by fernandog** [comment]
@TagForce I tested in regex101 and couldn't match either.

I'm trying to figure it out why so much issues don't have title. It appears as NONE. don't mind all my issues

**Comment by TagForce** [comment]
@fernandog No problem, I'm trying to find the root cause for this error, and seeing if this is a new issue, or if it's been happening a while... It may be related to changes in season_only searches.

**Comment by TagForce** [comment]
@fernandog @abeloin Doesn't seem to be an old issue (first issue with this was logged 8 days ago), but I can't find anything that would break this functionality (in fact, the regex.match function has been unchanged since SickRage was forked from SB). So, either something else has changed causing this function to be called more often, people are only now starting to submit this error now, or I'm completely blind.
Options 1 and 3 seem the most likely to me.

**Comment by miigotu** [comment]
How.Its.Made.S01.S14.Complete is invalid for SR atm because it only expects to DL individual episodes, or seasons, not complete series in one snatch.

Animaniacs.S05E14E12E21E1 <-- WTF are the episodes out of order for?

**Comment by Thraxis** [comment]
@fernandog @abeloin @TagForce To we have a list of filenames that you do want the RegEx to match against?  Or at least test examples.

At a minimum I believe you want to match the below?
Show Name.S01.Quality.ReleaseGroup
Show.Name.S01.Quality.ReleaseGroup

If that is the case replace that line of code with:
```python
regex = '^([\w-.\ ]+)[._-][sS]%02d[._-]([\w-\ ]+)[._-]?([\w-.\ ]+)?' % season
```

If you wish to match
Show.Name.S01.Quality.ReleaseGroup
Show.Name.S01E01E02E03.Quality.ReleaseGroup
Show.Name.S01E01E10.Quality.ReleaseGroup
Show.Name.S01-S14.Quality.ReleaseGroup

Then replace that line of code with:
```python
regex = '^([\w-.\ ]+)[._-][sS]%02d\w*[._-]([\w-\ ]+)[._-]?([\w-.\ ]+)?' % season
```

**Comment by fernandog** [comment]
I never saw a torrent with multiple seasons! Not supported - yet. We should change the log message. It invites user to open an issue when it should be a kind of Feature Request for REGEX.

**Comment by miigotu** [comment]
@Thraxis both of those regex are terribly incorrect.

**Comment by fernandog** [comment]
I can't help here. Don't know too much about regex.
We can add more then one regex to that part of the code so we can support multiple types of season pack files

**Comment by Thraxis** [comment]
Don't see how they are I've tested both and they match all test cases

If you're refering to the %02d it's for the season number replacement

**Comment by miigotu** [comment]
What im saying it they will match things that are not correct too.

**Comment by Thraxis** [comment]
And it's not the final regex for the search either
All it is a check for is if the file is a SceneName 

```python
regex = '(' + re.escape(showName) + '\.S%02d(?:[E0-9]+)\.[\w\._]+\-\w+' % season + ')'
```
This later regex is the one used to return results

showName being the first match group from the first regex and the only part used

**Comment by miigotu** [comment]
Yeah, but even if the regex was valid, it would return things like Oceans13.blah.blah.
Your regex doesnt even compute on pythex.org, even if you replace the %02d with a pure regex capture.

**Comment by miigotu** [comment]
Correct would be \W?([\w\.\ _]+)\W[Ss]([0-9]{1,2})
You would have to extract the season separate, as %02d is incorrect as well since it wont capture S1

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1288

**Comment by Thraxis** [comment]
I use https://regex101.com... unfortunately I neglected to switch the Regex engine from pcre (PHP) to python.

```python
regex = '(?:\[.+\])?\W?([\w.\ _-]+)\W[sS]\d?%d(?:\w*)\W([\w\ _-]+)\W([\w\ _-]+)' % season
```
Should match correctly now

And 

```python
regex = '(?:\[.+\])?\W?(' + re.escape(showName) + '\W[sS]\d?%d(?:[E0-9]+)\W[\w\._]+.+' % season + ')'
```

Should match the episode files within the nzb

**Comment by fernandog** [comment]
@abeloin @TagForce @miigotu @Thraxis 

should we add multiple regex to match this new kinds of season packs and multiple-packs?

**Comment by miigotu** [comment]
I think the original one works, it just needs to add `_` in the match groups.
As for adding different regex for multi season, I would just rather not touch this for now.

**Comment by Thraxis** [comment]
The . is just a . inside Regex character classes ( [ and ] ) Only the \ & and - have special meaning inside the  [ ].  It doesn't change anything to have it escaped or not

**Comment by miigotu** [comment]
I know regex well, xD. I've used it in almost all 16 languages I know.  Anyways, like I said this is a feature request, to support multi-season snatches, rather than a bug, and I think that any change to this should be extremely tested and should wait until a major feature milestone as it affects major core functionality. One miscalculated regex and we have a mass bug report/broken SR. The existing one has worked fine since SR forked, for the supported snatch types.

**Comment by fernandog** [comment]
cant we add them in order? 
First orignal regex, if didnt match try the second, etc...

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
