### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'getOverview'

### ISSUE THREAD

**Issue by mcmikev** [SiCKRAGETV/sickrage-issues#1273]
### INFO
Python Version: **2.7.9 (default, Mar 23 2015, 00:07:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@281409d366b228a455879e02b2d55d3967db29e4
No Log available with ERRORS: 
### ERROR
```
Thread-471 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1955, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1926, in getEpisodes
    'overview': Overview.overviewStrings[showObj.getOverview(int(searchThread.segment.status or -1))]})
AttributeError: 'NoneType' object has no attribute 'getOverview'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@mcmikev please full update all your tv-shows

**Comment by ripper1967** [comment]
do u mean a mass update of all show cause they was just updated 4 hours ago...

**Comment by fernandog** [comment]
@ripper1967 one of you show has a bad status. you need to FULL update (via mass update). Not update airtime

**Comment by ripper1967** [comment]
ok will try that
