### ISSUE TITLE
Adding support for chained SSL certificates (COMODO etc)

### ISSUE THREAD

**Issue by theemstra** [SiCKRAGETV/sickrage-issues#1274]
A lot of certificates are to be used with an intermediate certificate, but SickRage does not have a configuration option for that yet.

**Comment by abeloin** [comment]
@theemstra You need to chain all your certificates in one file and use that file.

https://support.comodo.com/index.php?/Knowledgebase/Article/View/643/0/how-do-i-make-my-own-bundle-file-from-crt-files
https://certificatechain.io/

**Comment by theemstra** [comment]
Great, I'll test this.
Maybe add those two links to documentation or to the GUI for referece, since there's no dedicated field name for a chained cert.

For ex:

Add your server certificate. Do you have a chained certificate, please select a certificate with the {full chain}[https://support.comodo.com/index.php?/Knowledgebase/Article/View/643/0/how-do-i-make-my-own-bundle-file-from-crt-files] in it.

**Comment by theemstra** [comment]
Works like a charm.
Also the website you provided is a real beauty, thanks, it will be shared!

Please concider the comment I made earlier.

**Comment by abeloin** [comment]
Will do
