### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'getOverview'

### ISSUE THREAD

**Issue by ripper1967** [SiCKRAGETV/sickrage-issues#1275]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@281409d366b228a455879e02b2d55d3967db29e4
Link to Log: https://gist.github.com/baf96981cd40c96dad98
### ERROR
```
Thread-39 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\Users\rusty\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\Users\rusty\SickRage\sickbeard\webserve.py", line 1966, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "C:\Users\rusty\SickRage\sickbeard\webserve.py", line 1926, in getEpisodes
    'overview': Overview.overviewStrings[showObj.getOverview(int(searchThread.segment.status or -1))]})
AttributeError: 'NoneType' object has no attribute 'getOverview'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@ripper1967 https://github.com/SiCKRAGETV/sickrage-issues/issues/1273
