### ISSUE TITLE
[Feature Request] Add Search for Multi Season Packs (s01-s07 packs)

### ISSUE THREAD

**Issue by broyuken** [SiCKRAGETV/sickrage-issues#1288]
Can you allow SickRage to search multi season upload packs? For example, if I want to download the show "Supernatural" it has to try to find 10 seperate torrents, one for each season. On my providers, they also have full show packs which have seasons 1-9 in one torrent and then individual episodes for the current season 10.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
