### ISSUE TITLE
[APP SUBMITTED]: 'WebRoot' object has no attribute 'api'

### ISSUE THREAD

**Issue by Thraxis** [SiCKRAGETV/sickrage-issues#129]
### INFO
Python Version: **2.7.3 (default, Mar 26 2013, 20:01:12) 
[GCC 4.4.4]**
Operating System: **Linux-3.9.6p-unRAID-i686-AMD_C-60_APU_with_Radeon-tm-_HD_Graphics-with-slackware-13.1.0**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@b2d5ef531bb07c291bf5c6860b8861bca01e1e08
### ERROR
```
TORNADO :: Failed doing webui request "api": Traceback (most recent call last):
  File "/usr/local/sickrage/sickbeard/webserve.py", line 216, in get
    method = getattr(self, route)
AttributeError: 'WebRoot' object has no attribute 'api'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@Thraxis is this still an issue?

**Comment by Thraxis** [comment]
Yes this is still a problem.

```
2015-01-24 18:13:32 DEBUG    TORNADO :: Failed doing webui request "api/********************************": Traceback (most recent call last):
AA
AAAttributeError: 'Home' object has no attribute 'api/********************************'
AA    method = getattr(self, route)
AA  File "/usr/local/sickrage/sickbeard/webserve.py", line 214, in get
2015-01-24 18:13:19 DEBUG    TORNADO :: Failed doing webui request "api/********************************": Traceback (most recent call last):
AA
AAAttributeError: 'Home' object has no attribute 'api/********************************'
AA    method = getattr(self, route)
AA  File "/usr/local/sickrage/sickbeard/webserve.py", line 214, in get
```

**Comment by fernandog** [comment]
@Thraxis can you try open localhost:8081/apibuilder? Test some API commands and see if works

**Comment by Thraxis** [comment]
Yes the API Builder works fine.   But whatever changes were made breaks sickbeard connect from communicating with sickrage

**Comment by fernandog** [comment]
@Thraxis isn't a problem with sickbeard connect?  The api has changed. I was added some others fields to it. Depending how sickbeard connect code is. it could'nt read the new api fields.

**Comment by fernandog** [comment]
looks like the app is abandoned:

https://chrome.google.com/webstore/detail/sickbeardconnect/ljfjkhejnkopmfdadafjoklibhggokpb/support?hl=en

"Doesn't work anymore
I tried it with Sickbeard and Sickrage with all the latest commits installed. Please update the app, as it is not working anymore!
Posted by Marco Mattei - Jan 11, 2015
Reply | Mark as spam

Yeah, is the extension being maintained? If not, maybe someone should fork it... Probably an easy fix. Just a wrong path or url or smthg.
Posted by Bjørn Husby - Jan 13, 2015"

**Comment by Thraxis** [comment]
Looking back into this from the plugin logs.  Sickrage is returning an error code 405 (Method Not allowed)  this is using a POST request.

**Comment by fernandog** [comment]
@Thraxis I see. SR is continuously changing. We can't help with a outdated app. Sorry.
Please try to contact sickbeard connect developer.

**Comment by morrison22** [comment]
I contacted the developer on reddit and hopefully he will fix it although its not looking promising as he said "I will not continue to develop the chrome plugin"  This is sad because this plugin was great.  I wish there was a way for the SickRage devs to modify code to let it work since chances are slim the developer is not going to update the app.  This tool was great man.

**Comment by Thraxis** [comment]
Well the basic change needed is to change from POST to GET in the helper.js

$.ajax( { type : "POST", url : apiUrl, data : params, dataType : 'json', success : function(data) {

changed to:

$.ajax( { type : "GET", url : apiUrl, data : params, dataType : 'json', success : function(data) {

makes it at least work.  Although it does then cause large numbers of errors in your log when checking some portions out. Fixing it will break compatability with sickbeard and sickgear.

code changes are in a fork at my github below.  

https://github.com/Thraxis/SickRageConnect

**Comment by morrison22** [comment]
Awesome..  It's functioning!!!  Thank you so much for making this happen.  I wish I knew more about programming so I could help with the errors it makes.  But it is definitely usable now!  Thank you again.

**Comment by morrison22** [comment]
Hi.  So I appriciate that you made SickRageConnect.  Its been working great, however now I have 1 issue.  It no longer shows MISSED EPISODES the next day, even if they did not download.  It used to show episodes that were not snatched.  This started happening when I upgraded OSX Yosemite to El Capitan Public Beta.  I am not sure if this is the cause or if there is something else I should check, or a quick fix.  Any ideas?
