### ISSUE TITLE
[APP SUBMITTED]: 'Logger' object has no attribute 'MESSAGE'

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#1290]
### INFO
Python Version: **2.7.8 (default, Oct 20 2014, 15:05:29) [GCC 4.9.1]**
Operating System: **Linux-3.16.0-34-generic-i686-with-Ubuntu-14.10-utopic**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@c484ba2a2b94ab11c33cdebaa414b8a7644e8654
Link to Log: https://gist.github.com/f0e8ec20945772a143a6
### ERROR
```
Thread-67 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/supergonkas/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/home/supergonkas/SickRage/sickbeard/webserve.py", line 1688, in updatePLEX
    if notifiers.plex_notifier.update_library():
  File "/home/supergonkas/SickRage/sickbeard/notifiers/plex.py", line 269, in update_library
    logger.log(u'PLEX: Updating all hosts with TV sections: ' + ', '.join(set(host_list)), logger.MESSAGE)
  File "/home/supergonkas/SickRage/sickbeard/logger.py", line 244, in __getattr__
    return getattr(self.instance, name)
AttributeError: 'Logger' object has no attribute 'MESSAGE'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by matigonkas** [comment]
i believe it happen when i updated SR after the merging of this PR https://github.com/SiCKRAGETV/SickRage/pull/1764

**Comment by fernandog** [comment]
@thraxis

**Comment by Thraxis** [comment]
I'll look into that It's probably in the client notification section as compared to the server notification one.   

I thought I'd caught all those

**Comment by Thraxis** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1783

**Comment by fernandog** [comment]
@matigonkas please update and report back

**Comment by matigonkas** [comment]
@fernandog  it seems to be good now

**Comment by fernandog** [comment]
@Thraxis thanks for the fast PR

**Comment by Thraxis** [comment]
Luckily it was one file to edit and I could edit it via web interface from work to PR
