### ISSUE TITLE
API Key for custom Newznab providers appearing in debug logs

### ISSUE THREAD

**Issue by drglove** [SiCKRAGETV/sickrage-issues#1292]
- Branch: Develop
- Commit hash: b8bb0939a3eb11d7d3aae567bef76259549631d0
- Your operating system and python version: Mac OSX 10.9.3, Python 2.7.8
- What you did: Debug logging enabled, backlog searched for an episode of Top Gear
- What happened: SickRage searched my custom Newznab provider, the "Found result" log message with the URL of the NZB contains the API key the request was initiated with
- What you expected: API key to be replaced with garbage characters in the log, like *****, just as in the initial request
- Link to a copy/paste of your logfile with clear debug info of the error on GIST: https://gist.github.com/drglove/3be96ffe61ec2a680bec

We may actually want to show the API key used in the request in the case of debug logs, but we should at least be consistent about (not) showing it across the logs. The search URL strikes out the API key but the URLs listed within the results do not have the API key replaced.

Note that in the Gist, I replaced my actual API key with 'abc123...'

**Comment by fernandog** [comment]
@drglove which provider?

check this: https://github.com/SiCKRAGETV/SickRage/pull/1401

**Comment by drglove** [comment]
@fernandog A custom provider, NZBGeek.
It's not stored as a key=value type in config.ini, but rather as an option in the string `newznab_data`

**Comment by fernandog** [comment]
@drglove I use it too. Why dont you add API to the proper field?
if you add the api on the url would be a lot difficult to mask it. Depends on each provider string.

**Comment by drglove** [comment]
@fernandog This is with the API appearing in the field as placed by the web UI.
![screenshot 2015-04-16 15 26 45](https://cloud.githubusercontent.com/assets/607460/7192745/3aa850dc-e44d-11e4-97c8-5252077e2245.png)

The relevant lines in my config.ini appear after entering the above:
```
...
[NZB_GEEK_VIG]
nzb_geek_vig = 1
nzb_geek_vig_search_mode = eponly
nzb_geek_vig_search_fallback = 0
nzb_geek_vig_enable_daily = 1
nzb_geek_vig_enable_backlog = 1
...
[Newznab]
newznab_data = "Sick Beard Index|http://lolo.sickbeard.com/|0|5030,5040|1|eponly|0|1|1!!!NZBs.org|https://nzbs.org/||5030,5040|0|eponly|0|1|1!!!Usenet-Crawler|https://www.usenet-crawler.com/||5030,5040|0|eponly|0|1|1!!!NZB Geek VIG|https://api.nzbgeek.info/|abc123...|5030,5040|1|eponly|0|1|1"
...
```

**Comment by Thraxis** [comment]
@fernandog The problem is that the URL in that message is coming from NZBGeek not the SickRage config variables so SR doesn't know to automatically mask the key.

Line 417 of generic.py

**Comment by drglove** [comment]
@Thraxis @fernandog Right, I see that. I would suggest that anytime a URL is logged from a response that it get passed through a quick scan to remove anything obvious from a select few, like 'apikey', 'api_key', otherwise I'd blame the provider.

**Comment by fernandog** [comment]
it's supposed to hide in log:

"Found result ------ at https://api.nzbgeek.info/api?t=get&id=32cf5040cdc3dcf30a9e2602255a5aa2&apikey=abc123....."

**Comment by Thraxis** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1840

re.sub regex was not taking into consideration that the api key might be at the end of the string not followed by an &.
