### ISSUE TITLE
[Feature Request] Add Move Associated files option for only subtitles

### ISSUE THREAD

**Issue by djoole** [SiCKRAGETV/sickrage-issues#1293]
At the moment, there is a "Move Associated Files
Move srr/srt/sfv/etc files with the episode when processed?" option in PP.

I think it would be better to being able to choose to move only subtitles.

I don't want my final dirs polluted by sfv files, but I would like to retrieve srt files released in the torrent.

**Comment by fernandog** [comment]
@djoole something like nzb categories?

**Comment by djoole** [comment]
@fernandog Are you talking about a SickRage feature?
Sorry I couldn't tell because I'm using only torrent.

**Comment by fernandog** [comment]
@djoole

a simple input field where you choose which you want SR to move . Like sync files.

@tagforce what do you think?

**Comment by TagForce** [comment]
@fernandog Maybe add a suboption to the move associated files to move subtitles only?
The function to find associated files already has a subtitles_only switch, so that shouldn't be too hard to implement.

**Comment by fernandog** [comment]
@tagforce ok!

**Comment by djoole** [comment]
I'm good with a sub option, as long as the subtitles file extension list is exhaustive (http://en.wikipedia.org/wiki/Subtitle_(captioning)#Subtitle_formats).

But I'm also good with a free field which let the user decide what to move...

Up to you!

**Comment by Zzaap** [comment]
Also, it would be nice if the associated files were case insensitive. 

Personally i would like it if it even parsed the subtitles files separately, so the files names could be a bit different and it would still associate them.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
