### ISSUE TITLE
[APP SUBMITTED]: 'ascii' codec can't encode character u'\xe5' in position 68: ordinal not in range(128)

### ISSUE THREAD

**Issue by ThomasDK81** [SiCKRAGETV/sickrage-issues#1295]
### INFO
Python Version: **2.7.8 (default, Dec 15 2014, 02:33:48) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@281409d366b228a455879e02b2d55d3967db29e4
Link to Log: https://gist.github.com/93b822fcc429dfda2cbd
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: ascii : /mnt/media/shares/tvshows/Lillemand/Season 1/Lillemand - S01E03 - Små sko.mkv : error 68 : error 69 : ordinal not in range(128)
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@ThomasDK81
Locale: unknown

Please set your locale to UTF-8

**Comment by ThomasDK81** [comment]
Thanks, but where?

**Comment by fernandog** [comment]
https://sickrage.tv/forums/forum/help-support/general-support/12825-ensuring-your-locale-s-are-set-properly-to-avoid-unicode-issues
