### ISSUE TITLE
[APP SUBMITTED]: Unrar: Archive CRC Error

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#1301]
### INFO
Python Version: **2.7.8 (default, Oct 20 2014, 15:05:29) [GCC 4.9.1]**
Operating System: **Linux-3.16.0-34-generic-i686-with-Ubuntu-14.10-utopic**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@370217622b360a45075a067f65353b7d8547fcf9
Link to Log: https://gist.github.com/bf35616ca709d4c7ef96
### ERROR
```
POSTPROCESSER :: Failed Unrar archive marvels.daredevil.s01e07.1080p.webrip.x264-2hd.rar: Unrar: Archive CRC Error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@matigonkas seems corrupt.

@TagForce empty title. "message" is also empty?

**Comment by matigonkas** [comment]
it seems to happen to every rar file 
https://github.com/SiCKRAGETV/sickrage-issues/issues/1302
https://github.com/SiCKRAGETV/sickrage-issues/issues/1303

**Comment by fernandog** [comment]
@matigonkas we haven't change anything with unrar. Are you sure they are not corrupted?

**Comment by oshimo** [comment]
I have been receiving the same error recently on almost all downloads..

2015-04-17 12:20:25 POSTPROCESSER :: Failed Unrar archive house.of.lies.s04e06.720p.hdtv.x264-immerse.rar: Unrar: Archive CRC Error

**Comment by fernandog** [comment]
@oshimo @matigonkas can you manually extract the rar? does it extract ok ? This error code come directly from unrar

**Comment by oshimo** [comment]
@fernandog yes, all I have been able to manually extract and move with no issue.

**Comment by oshimo** [comment]
This seems to be the case with almost all downloads for the past 2 days:

2015-04-17 12:38:20 POSTPROCESSER :: Failed Unrar archive vikings.s02e01.bdrip.x264-demand.rar: Unrar: No file extracted, check the parent folder and destination file permissions.
2015-04-17 12:37:19 POSTPROCESSER :: Failed Unrar archive spartacus.s03e08.720p.hdtv.x264-immerse.rar: Unrar: Archive CRC Error

Prior to this there were no issues

**Comment by fernandog** [comment]
@oshimo I'm asking again: can you **MANUALLY** extract it?

the other one is permission issues.

**Comment by fernandog** [comment]
@TagForce unrar error come comes from unrar. Do you know what may causing this?

**Comment by oshimo** [comment]
@fernandog yes, all I have been able to manually extract and move with no issue.

**Comment by fernandog** [comment]
@abeloin help with this one too

**Comment by TagForce** [comment]
@fernandog no idea. And I'm not able to check this today.

**Comment by abeloin** [comment]
@matigonkas Please run the following on your archive and post the results:
`unrar vta marvels.daredevil.s01e07.1080p.webrip.x264-2hd.rar`
`unrar t marvels.daredevil.s01e07.1080p.webrip.x264-2hd.rar`

@oshimo  Please run the following on your archive and post the results:
`unrar vta vikings.s02e01.bdrip.x264-demand.rar`
`unrar t vikings.s02e01.bdrip.x264-demand.rar`

**Comment by matigonkas** [comment]
@abeloin 
unrar vta marvels.daredevil.s01e07.1080p.webrip.x264-2hd.rar result :http://pastebin.com/2eASLcYc
unrar t marvels.daredevil.s01e07.1080p.webrip.x264-2hd.rar result: http://pastebin.com/y0YwBpH5

**Comment by cwallace** [comment]
I get this quite a bit, but have noticed it always happens when the post processor fires while the episode is still being downloaded. Once the download completes, post process runs fine.

**Comment by fernandog** [comment]
You must keep a separated folder for incomplete downloads and complete downloads (PP downloads)

**Comment by abeloin** [comment]
@matigonkas Can you update to the final release of unrar 5? Try to avoid beta version of unrar.

**Comment by abeloin** [comment]
@cwallace Never PP incomplete download if you don't use "sync File Extensions"

**Comment by matigonkas** [comment]
@abeloin how do i do it?

**Comment by abeloin** [comment]
Since i don't know how you install unrar on your Ubuntu 14.10 installation it's difficult to give you precise information.

Maybe this can help: http://howtoubuntu.org/things-to-do-after-installing-ubuntu-14-10-utopic-unicorn

**Comment by fernandog** [comment]
@matigonkas did you asked about PP folder or about unrar 5?

**Comment by matigonkas** [comment]
@fernandog  non beta unrar

**Comment by fernandog** [comment]
@matigonkas did you updated to 5? any issues so far after updating?

**Comment by matigonkas** [comment]
@fernandog  no I don't know how to update to a non beta version ,because on the latest version of the Ubuntu repo its a beta version
I also haven't been able to find any info on Google

**Comment by abeloin** [comment]
https://launchpad.net/~ricotz/+archive/ubuntu/unstable

**Comment by fernandog** [comment]
@matigonkas please report back

**Comment by fernandog** [comment]
no reply, closing
