### ISSUE TITLE
[APP SUBMITTED]: list.remove(x): x not in list

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#1305]
### INFO
Python Version: **2.7.8 (default, Oct 20 2014, 15:05:29) [GCC 4.9.1]**
Operating System: **Linux-3.16.0-34-generic-i686-with-Ubuntu-14.10-utopic**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@a2b7284697fbc3f99a937fd0803755cef28cae52
Link to Log: https://gist.github.com/56c0d1039e6ae5ec99d6
### ERROR
```
Thread-56 :: list.remove(x): x not in list
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by matigonkas** [comment]
this happened when i submited this error https://github.com/SiCKRAGETV/sickrage-issues/issues/1304

**Comment by fernandog** [comment]
@matigonkas what's the full log for this? Isn't there a traceback?

**Comment by matigonkas** [comment]
There wasnt any traceback whatsoever ,i dont have the log anymore but i remember that it was something like so:

"Thread-56 :: list.remove(x): x not in list"
"Submited your ticket 1304 blablabla"
"Submited your ticket 1303 blablabla"
etc

**Comment by fernandog** [comment]
@abeloin didn't find the code "list.remove(x)". help here?

**Comment by TagForce** [comment]
@fernandog
https://github.com/SiCKRAGETV/SickRage/blob/c9a102608e37c4c6e24c595297af1add5677ef79/sickbeard/logger.py#L226
That's the list.remove throwing the error...

@matigonkas did you hit clear errors after submitting?
If so, then that probably cleared the list before it was sent. 
Keep an eye out for more of these.

**Comment by matigonkas** [comment]
@TagForce No i didnt hit clear errors

**Comment by TagForce** [comment]
@matigonkas Ok, strange, because the error should be in that list... The code was recently updated to fix some titles that were None, but that was done in the creation of the error. 
I'll look into this...
Are you getting any empty lines with just a thread number in the log when you submit errors?

**Comment by matigonkas** [comment]
@TagForce  No i dont see any empty lines.
Also i just saw on the log for this error that there where 2 issues submited with the same timestamp could it has something to do with it?

**Comment by TagForce** [comment]
@matigonkas It should simply go through the entire list of errors and submit the newest one. Only UI errors will be submitted and added to that list, but it's a simple for loop that is broken out of by the return at the end:
```
for curError in sorted(classes.ErrorViewer.errors, key=lambda error: error.time, reverse=True)[:500]:
```

At the end there is a ```classes.ErrorViewer.errors.remove(curError)``` that removes the error from the error list. Now that I think about it, it may actually remove all instances of the exact same error at the exact same time, but I doubt it (it should be a memory reference that gets removed, and not anything that is the same).

**Comment by fernandog** [comment]
@TagForce confirmed issue?

**Comment by TagForce** [comment]
@fernandog Not as of yet, I've been unable to reproduce this so far, and nobody else seems to have encountered it.

**Comment by fernandog** [comment]
@matigonkas can you try to reproduce it again? Otherwise will close as we can't reproduce

**Comment by matigonkas** [comment]
I think i figured it out @TagForce  
When you have 2 or more errors and you try to click the submit button more than the number of errors, it will throw that error

**Comment by fernandog** [comment]
@tagforce we should disable button - or show spinning wheel in pointer - until issue is submitted

@matigonkas did you pressed 3 times without waiting the notification showing the issue was submitted?

**Comment by matigonkas** [comment]
@fernandog yes i believe i did

**Comment by fernandog** [comment]
@miigotu did you get this error while testing submitting issues?

**Comment by miigotu** [comment]
nope, not once

**Comment by fernandog** [comment]
@miigotu did you waited the notification appear before submitting the next one?

**Comment by miigotu** [comment]
yes, I waited. Maybe we need to add a global to the submitter and block it from being called again until the first one is finished?

**Comment by fernandog** [comment]
@miigotu I was thinking disabling the button using javascript until issue got submitted. But don't know how. is there another solution?

**Comment by miigotu** [comment]
sure, I could add a calss variable in logger like submitter_running = , initialize it to false, then at the start of submit_errors do something like
```
if submitter_running:
    return
submitter_running = True
```
and at the end:

```
submitter_running = False
```

**Comment by miigotu** [comment]
The problem arises because the log submitter takes awhile to complete the function because it has to read all of the logs, apply regex to every line, get issues from github, loop through each issue, and then either create a comment or submit a new issue. Could be 5 seconds or so, and people are impatient.

**Comment by fernandog** [comment]
@miigotu but how to tell user about the waiting?

**Comment by miigotu** [comment]
I'm sure I could figure out a way if I tried hard enough, but I think there are people here much more familiar with the js and ui code in general.

**Comment by miigotu** [comment]
I guess just a notification, set up the return from submit_errors to tell if it was processed or blocked, and notify accordingly from webserve.py

**Comment by miigotu** [comment]
@fernandog I'll see what I can whip up in the next half hour or so.

**Comment by miigotu** [comment]
@fernandog rawr.

**Comment by fernandog** [comment]
@matigonkas please update and try to reproduce please
