### ISSUE TITLE
Error returned status code is 404: Not Found for all show searches on IPTorrents

### ISSUE THREAD

**Issue by christiananguiano** [SiCKRAGETV/sickrage-issues#1309]
All of my searches have stopped working today on IPTorrents. It returns a 404 error in the URL for any show that I add and current ones.

Here's an example:

    
    18:27:06 INFO::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Performing episode search for Family Guy
    18:27:06 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: IPTorrents search page URL: https://iptorrents.eu/torrents/?l73=1&l78=1&l66=1&l65=1&l79=1&l5=1&l4=1&q=Family.Guy S13E14 &qf=ti;o=seeders
    18:27:07 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Requested url https://iptorrents.eu/torrents/?l73=1&l78=1&l66=1&l65=1&l79=1&l5=1&l4=1&q=Family.Guy S13E14 &qf=ti;o=seeders returned status code is 404: Not Found
    18:27:07 DEBUG::SEARCHQUEUE-MANUAL-75978 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
    18:27:07 DEBUG::SEARCHQUEUE-MANUAL-75978 :: formatting pattern: %SN - %Sx%0E - %EN -> Family Guy - 13x14 - JOLO
    18:27:07 DEBUG::SEARCHQUEUE-MANUAL-75978 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
    18:27:07 DEBUG::SEARCHQUEUE-MANUAL-75978 :: formatting pattern: %SN - %Sx%0E - %EN -> Family Guy - 13x14 - JOLO
    18:27:07 INFO::SEARCHQUEUE-MANUAL-75978 :: Unable to find a download for: [Family Guy - 13x14 - JOLO]

**Comment by fernandog** [comment]
@christiananguiano are you using develop?

**Comment by christiananguiano** [comment]
@fernandog I am not, but here's what happens on develop branch:


    18:37:21 INFO::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Performing episode search for Family Guy
    18:37:21 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: IPTorrents search page URL: https://iptorrents.eu/torrents/?l73=1&l78=1&l66=1&l65=1&l79=1&l5=1&l4=1&q=Family.Guy S13E14 &qf=ti;o=seeders
    18:37:21 WARNING::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Unknown exception while loading URL https://iptorrents.eu/torrents/?l73=1&l78=1&l66=1&l65=1&l79=1&l5=1&l4=1&q=Family.Guy S13E14 &qf=ti;o=seeders: Traceback (most recent call last):
      File "/var/www/sickrage/sickbeard/helpers.py", line 1300, in getURL
        resp.status_code) + ': ' + self.codeDescription(resp.status_code), logger.DEBUG)
    NameError: global name 'self' is not defined
    
    18:37:21 DEBUG::SEARCHQUEUE-MANUAL-75978 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
    18:37:21 DEBUG::SEARCHQUEUE-MANUAL-75978 :: formatting pattern: %SN - %Sx%0E - %EN -> Family Guy - 13x14 - JOLO
    18:37:21 DEBUG::SEARCHQUEUE-MANUAL-75978 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
    18:37:21 DEBUG::SEARCHQUEUE-MANUAL-75978 :: formatting pattern: %SN - %Sx%0E - %EN -> Family Guy - 13x14 - JOLO
    18:37:21 INFO::SEARCHQUEUE-MANUAL-75978 :: Unable to find a download for: [Family Guy - 13x14 - JOLO]

**Comment by fernandog** [comment]
@christiananguiano please update develop

Can you access https://iptorrents.eu/torrents ?

**Comment by christiananguiano** [comment]
It fixed the previous issue, now it gives me the 404 not found error again. 

    21:54:39 INFO::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Performing episode search for Family Guy
    21:54:40 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: IPTorrents search page URL: https://iptorrents.eu/torrents/?l73=1&l78=1&l66=1&l65=1&l79=1&l5=1&l4=1&q=Family.Guy S13E14 &qf=ti;o=seeders
    21:54:40 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Requested url https://iptorrents.eu/torrents/?l73=1&l78=1&l66=1&l65=1&l79=1&l5=1&l4=1&q=Family.Guy S13E14 &qf=ti;o=seeders returned status code is 404: Not Found
    21:54:40 DEBUG::SEARCHQUEUE-MANUAL-75978 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
    21:54:40 DEBUG::SEARCHQUEUE-MANUAL-75978 :: formatting pattern: %SN - %Sx%0E - %EN -> Family Guy - 13x14 - JOLO
    21:54:40 DEBUG::SEARCHQUEUE-MANUAL-75978 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
    21:54:40 DEBUG::SEARCHQUEUE-MANUAL-75978 :: formatting pattern: %SN - %Sx%0E - %EN -> Family Guy - 13x14 - JOLO
    21:54:40 INFO::SEARCHQUEUE-MANUAL-75978 :: Unable to find a download for: [Family Guy - 13x14 - JOLO]

And yes, I can access https://iptorrents.eu/torrents

![screen shot 2015-04-17 at 6 56 56 pm](https://cloud.githubusercontent.com/assets/6056646/7213443/8f883bd0-e533-11e4-95c1-35e1e08d4b6f.png)

**Comment by fernandog** [comment]
@christiananguiano try open the url showed in the log "Requested url"

**Comment by fernandog** [comment]
@abeloin this is why we need the url quote. To open the url (There is space on it)

https://iptorrents.eu/torrents/?l73=1&l78=1&l66=1&l65=1&l79=1&l5=1&l4=1&q=Family.Guy S13E14 &qf=ti;o=seeders

**Comment by christiananguiano** [comment]
The URL returns a 404. Removing the space returns a 404 as well.

![screen-shot-2015-04-17-at-7 16 17-pm](https://cloud.githubusercontent.com/assets/6056646/7213514/8b607330-e536-11e4-9652-9d6b3f9b928f.png)

**Comment by fernandog** [comment]
@christiananguiano they changed something

Make a simple search in all tvshows categories and post the URL please

**Comment by christiananguiano** [comment]
Here you go.
https://iptorrents.eu/t?l73=&q=Family+Guy&qf=#torrents

**Comment by fernandog** [comment]
@christiananguiano 

Try open the url in the log adding t after the slash and before question mark

**Comment by christiananguiano** [comment]
That gives a 404 as well.

![screen-shot-2015-04-17-at-7 33 35-pm](https://cloud.githubusercontent.com/assets/6056646/7213587/cfc9bbc4-e538-11e4-9db4-5f5373cadc9b.png)

**Comment by fernandog** [comment]
@christiananguiano try adding qf=#torrents to the end too

**Comment by christiananguiano** [comment]
404 error as well.

**Comment by fernandog** [comment]
@christiananguiano 

This:
https://iptorrents.eu/torrents/t?l73=1&l78=1&l66=1&l65=1&l79=1&l5=1&l4=1&q=Family.Guy S13E14 &qf=#torrents

**Comment by christiananguiano** [comment]
Same error. 

![screen-shot-2015-04-17-at-7 40 20-pm](https://cloud.githubusercontent.com/assets/6056646/7213619/b9c44d0c-e539-11e4-83b1-5388498efe18.png)

**Comment by fernandog** [comment]
@christiananguiano when you did a simple search in the site did you selected all tv shows categories?

**Comment by christiananguiano** [comment]
Yes, all TV show categories are checked during the search.

![screen shot 2015-04-17 at 7 43 33 pm](https://cloud.githubusercontent.com/assets/6056646/7213632/1d36e534-e53a-11e4-8e7b-839a389698bf.png)

**Comment by fernandog** [comment]
@christiananguiano please update and report back

**Comment by christiananguiano** [comment]
Same error. :(

![screen shot 2015-04-17 at 7 54 25 pm](https://cloud.githubusercontent.com/assets/6056646/7213681/9720bfc2-e53b-11e4-8a7c-739914b1c7a2.png)

**Comment by fernandog** [comment]
@christiananguiano post log with url please

**Comment by christiananguiano** [comment]
22:52:56 INFO::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Performing episode search for Family Guy
	 22:52:56 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: IPTorrents search page URL: https://iptorrents.eu/torrents/t?l73=&q=Family.Guy S13E14 	 &qf=#torrents;o=seeders
	 22:52:57 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Requested url https://iptorrents.eu/torrents/t?l73=&q=Family.Guy S13E14 	 &qf=#torrents;o=seeders returned status code is 404: Not Found
	 22:52:57 DEBUG::SEARCHQUEUE-MANUAL-75978 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
	 22:52:57 DEBUG::SEARCHQUEUE-MANUAL-75978 :: formatting pattern: %SN - %Sx%0E - %EN -> Family Guy - 13x14 - JOLO
	 22:52:57 DEBUG::SEARCHQUEUE-MANUAL-75978 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
	 22:52:57 DEBUG::SEARCHQUEUE-MANUAL-75978 :: formatting pattern: %SN - %Sx%0E - %EN -> Family Guy - 13x14 - JOLO
	 22:52:57 INFO::SEARCHQUEUE-MANUAL-75978 :: Unable to find a download for: [Family Guy - 13x14 - JOLO]

**Comment by fernandog** [comment]
@christiananguiano try open:

https://iptorrents.eu/torrents/t?l73=&q=Family.Guy S13E14 &qf=#torrents

**Comment by christiananguiano** [comment]
404 - Not Found

**Comment by fernandog** [comment]
@christiananguiano what's the difference between this url and url from:

![screen shot 2015-04-17 at 7 43 33 pm](https://cloud.githubusercontent.com/assets/6056646/7213632/1d36e534-e53a-11e4-8e7b-839a389698bf.png)

**Comment by christiananguiano** [comment]
If you remove /torrents/ it works.

**Comment by fernandog** [comment]
@christiananguiano damn!

**Comment by fernandog** [comment]
@christiananguiano 

try open https://iptorrents.eu/t?l73=&q=Family.Guy S13E14 &qf=#torrents;o=seeders

**Comment by christiananguiano** [comment]
That works too!

**Comment by fernandog** [comment]
@christiananguiano update and report back

**Comment by christiananguiano** [comment]
Awesome, it looks like it's working now! :)
Here's the full log. 

	23:10:24 INFO::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Performing episode search for Family Guy
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: IPTorrents search page URL: https://iptorrents.eu/t?l73=&q=Family.Guy S13E14 &qf=#torrents;o=seeders
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Found result: Family Guy S13E14 HDTV XviD-FUM (https://iptorrents.eu/details.php?id=1380236)
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Found result: Family Guy S13E14 720p HDTV DD5 1 MPEG2-TOPKEK (https://iptorrents.eu/details.php?id=1380079)
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Found result: Family Guy S13E14 480p HDTV x264-mSD (https://iptorrents.eu/details.php?id=1380073)
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Found result: Family Guy S13E14 720p HDTV x264-KILLERS (https://iptorrents.eu/details.php?id=1380048)
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Found result: Family Guy S13E14 HDTV x264-KILLERS (https://iptorrents.eu/details.php?id=1380047)
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Using ALL regexes
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Converted parsed result Family.Guy.S13E14.720p.HDTV.DD5.1.MPEG2-TOPKEK into Family Guy - S13E14 [ANIME VER: -1] [GROUP: TOPKEK] [ABD: False] [ANIME: False] [whichReg: ['standard']]
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Parsed Family.Guy.S13E14.720p.HDTV.DD5.1.MPEG2-TOPKEK into Family Guy - S13E14 [ANIME VER: -1] [GROUP: TOPKEK] [ABD: False] [ANIME: False] [whichReg: ['standard']]
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Checking if found episode 13x14 is wanted at quality RawHD TV
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: any,best = [16, 64, 256] [4, 8, 32, 128] and found 8
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Existing episode status: 5 (Skipped)
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Existing episode status is wanted/unaired/skipped, getting found episode
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Found result Family.Guy.S13E14.720p.HDTV.DD5.1.MPEG2-TOPKEK at https://iptorrents.eu/download.php/1380079/Family.Guy.S13E14.720p.HDTV.DD5.1.MPEG2-TOPKEK.torrent
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Single episode result.
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Using ALL regexes
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Converted parsed result Family.Guy.S13E14.720p.HDTV.x264-KILLERS into Family Guy - S13E14 [ANIME VER: -1] [GROUP: KILLERS] [ABD: False] [ANIME: False] [whichReg: ['standard']]
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Parsed Family.Guy.S13E14.720p.HDTV.x264-KILLERS into Family Guy - S13E14 [ANIME VER: -1] [GROUP: KILLERS] [ABD: False] [ANIME: False] [whichReg: ['standard']]
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Checking if found episode 13x14 is wanted at quality HD TV
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: any,best = [16, 64, 256] [4, 8, 32, 128] and found 4
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Existing episode status: 5 (Skipped)
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Existing episode status is wanted/unaired/skipped, getting found episode
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Found result Family.Guy.S13E14.720p.HDTV.x264-KILLERS at https://iptorrents.eu/download.php/1380048/Family.Guy.S13E14.720p.HDTV.x264-KILLERS.torrent
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Single episode result.
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Using ALL regexes
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Converted parsed result Family.Guy.S13E14.HDTV.XviD-FUM into Family Guy - S13E14 [ANIME VER: -1] [GROUP: FUM] [ABD: False] [ANIME: False] [whichReg: ['standard']]
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Parsed Family.Guy.S13E14.HDTV.XviD-FUM into Family Guy - S13E14 [ANIME VER: -1] [GROUP: FUM] [ABD: False] [ANIME: False] [whichReg: ['standard']]
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Checking if found episode 13x14 is wanted at quality SD TV
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: any,best = [16, 64, 256] [4, 8, 32, 128] and found 1
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Don't want this quality, ignoring found episode
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Ignoring result Family.Guy.S13E14.HDTV.XviD-FUM because we don't want an episode that is SD TV
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Using ALL regexes
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Converted parsed result Family.Guy.S13E14.480p.HDTV.x264-mSD into Family Guy - S13E14 [ANIME VER: -1] [GROUP: mSD] [ABD: False] [ANIME: False] [whichReg: ['standard']]
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Parsed Family.Guy.S13E14.480p.HDTV.x264-mSD into Family Guy - S13E14 [ANIME VER: -1] [GROUP: mSD] [ABD: False] [ANIME: False] [whichReg: ['standard']]
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Checking if found episode 13x14 is wanted at quality SD TV
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: any,best = [16, 64, 256] [4, 8, 32, 128] and found 1
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Don't want this quality, ignoring found episode
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Ignoring result Family.Guy.S13E14.480p.HDTV.x264-mSD because we don't want an episode that is SD TV
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Using ALL regexes
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Converted parsed result Family.Guy.S13E14.HDTV.x264-KILLERS into Family Guy - S13E14 [ANIME VER: -1] [GROUP: KILLERS] [ABD: False] [ANIME: False] [whichReg: ['standard']]
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Parsed Family.Guy.S13E14.HDTV.x264-KILLERS into Family Guy - S13E14 [ANIME VER: -1] [GROUP: KILLERS] [ABD: False] [ANIME: False] [whichReg: ['standard']]
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Checking if found episode 13x14 is wanted at quality SD TV
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: any,best = [16, 64, 256] [4, 8, 32, 128] and found 1
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Don't want this quality, ignoring found episode
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: [IPTorrents] :: Ignoring result Family.Guy.S13E14.HDTV.x264-KILLERS because we don't want an episode that is SD TV
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: The highest quality of any match is RawHD TV
	23:10:25 DEBUG::SEARCHQUEUE-MANUAL-75978 :: Picking the best result out of [u'Family.Guy.S13E14.720p.HDTV.DD5.1.MPEG2-TOPKEK', u'Family.Guy.S13E14.720p.HDTV.x264-KILLERS']
	23:10:26 INFO::SEARCHQUEUE-MANUAL-75978 :: Quality of Family.Guy.S13E14.720p.HDTV.DD5.1.MPEG2-TOPKEK is RawHD TV
	23:10:27 INFO::SEARCHQUEUE-MANUAL-75978 :: Quality of Family.Guy.S13E14.720p.HDTV.x264-KILLERS is HD TV
	23:10:27 DEBUG::SEARCHQUEUE-MANUAL-75978 :: Picked Family.Guy.S13E14.720p.HDTV.DD5.1.MPEG2-TOPKEK as the best
	23:10:27 DEBUG::SEARCHQUEUE-MANUAL-75978 :: Checking if we should keep searching after we've found Family.Guy.S13E14.720p.HDTV.DD5.1.MPEG2-TOPKEK
	23:10:27 INFO::SEARCHQUEUE-MANUAL-75978 :: Downloading Family.Guy.S13E14.720p.HDTV.DD5.1.MPEG2-TOPKEK from IPTorrents
	23:10:27 DEBUG::SEARCHQUEUE-MANUAL-75978 :: Calling rTorrent Client
	23:10:27 DEBUG::SEARCHQUEUE-MANUAL-75978 :: Checking if we should archive our first best quality match for for episode Family.Guy.S13E14.720p.HDTV.DD5.1.MPEG2-TOPKEK
	23:10:27 DEBUG::SEARCHQUEUE-MANUAL-75978 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN - %QN
	23:10:27 DEBUG::SEARCHQUEUE-MANUAL-75978 :: formatting pattern: %SN - %Sx%0E - %EN - %QN -> Family Guy - 13x14 - JOLO - RawHD TV
	23:10:27 DEBUG::SEARCHQUEUE-MANUAL-75978 :: Transaction with 1 queries executed

**Comment by abeloin** [comment]
@fernandog The space has nothing to do with this error. The requests library automatically quotes invalid character in a url.

**Comment by fernandog** [comment]
@abeloin I know. its easier to user copy url from log. Error was fixed
