### ISSUE TITLE
[APP SUBMITTED]: unpack requires a string argument of length 8

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#1312]
### INFO
Python Version: **2.7.8 (default, Oct 20 2014, 15:05:29) [GCC 4.9.1]**
Operating System: **Linux-3.16.0-34-generic-i686-with-Ubuntu-14.10-utopic**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@6ea3ae63640a78ef8280ff01ae02c7390de39781
Link to Log: https://gist.github.com/39f08d6a474baa71abd2
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: unpack requires a string argument of length 8
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by TagForce** [comment]
@matigonkas Can you post all the logs filtered on POSTPROCESSER?
It seems to be doing something, but from the posted logs it's completely unclear what and when it is doing it.

**Comment by fernandog** [comment]
@matigonkas please reply or will close

**Comment by matigonkas** [comment]
@TagForce i dont have those logs anymore
So it might be better to close it @fernandog

**Comment by fernandog** [comment]
@matigonkas did you get this once only?

**Comment by matigonkas** [comment]
@fernandog  I am not sure but I think that only happened that time
