### ISSUE TITLE
[Feature Request] Allow scene number field to override season for specials

### ISSUE THREAD

**Issue by smstarrant** [SiCKRAGETV/sickrage-issues#1313]
I have tried to manually edit the scene numbers for specials but they default back to 0x#.  I would like to be able to change the numbers.

BRANCH: (master) / COMMIT: (281409d366b228a455879e02b2d55d3967db29e4) 
2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]

**Comment by HenrikPoulsen** [comment]
Wish you could chose to turn the auto changing off for some shows. If I want it to search for episode 03 it should accept that and not modify it to be 3 (which breaks it for anime where the numbering restarts from 01 on season change)

**Comment by abeloin** [comment]
@HenrikPoulsen Try adding the anime show to xem instead. Have an example of a show?

**Comment by HenrikPoulsen** [comment]
@abeloin Never even heard of that before. What settings triggers sickrage to use it, or is it something I have to do manually? One of my many examples is Ace of Diamond, where season 2 is called Ace of Diamond S2. Sickrage won't play along at all and is completely stupid about not finding it or any other shows with new season names which the indexers just see as new seasons.

**Comment by abeloin** [comment]
It should be automatic, you should see a xem icon near thtvdb icon in the show's page.

Ref link http://thexem.de/xem/show/2223

**Comment by abeloin** [comment]
![Imgur](http://i.imgur.com/znMage3.png)

**Comment by HenrikPoulsen** [comment]
@abeloin OK thanks I will see if I can get that working. I must have touched something to mess it up. I don't get the extra scene names and when I search it still just seems to search with the wrong season name (the xem icon is present). And deleting the show doesn't seem to help because it still seems to save any settings I have done since my preferred groups comes back when readding the show >_>
This xem functionality should really be documented somewhere and how it is triggered and when etc. My confusion is high currently :)

**Comment by abeloin** [comment]
Make sure you selected, anime and scene numbering in the shows properties. Also do a force full update if the scene absolute isn't filled. The xem info is resfreshed every 24 hours(if I remember correctly).

**Comment by FritzSG** [comment]
I do not have the XEM icon present. How do I get that added? I have the same issue as described above.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
