### ISSUE TITLE
[APP SUBMITTED]: None

### ISSUE THREAD

**Issue by TheFuzzyOne87** [SiCKRAGETV/sickrage-issues#1315]
### INFO
Python Version: **2.7.9 (default, Mar 22 2015, 23:26:38) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@281409d366b228a455879e02b2d55d3967db29e4
Link to Log: https://gist.github.com/529ab55871be53af6a02
### ERROR
```
SHOWQUEUE-ADD :: No episode number found in /volume1/video/TV/Dr.Who/Season 4/Doctor Who - Voyage Of The Damned - Christmas Special 2007 - xvid.avi, ignoring it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
episode without number

**Comment by Thraxis** [comment]
It's a Special..  S0E07 

Doctor Who Christmas Specials are never released with a Season or Episode number by the Scene.  You have to add them manually.

**Comment by TheFuzzyOne87** [comment]
Really sorry about that, there was an actual error message I was trying to submit but I guess I sent the wrong one
