### ISSUE TITLE
Add trending show not working

### ISSUE THREAD

**Issue by cyberundertaker** [SiCKRAGETV/sickrage-issues#1316]
When trying to add trending show i get this message:
Trakt API did not return any results, please check your config.

SR doesn't give any error but from log i can see this:

2015-04-18 19:33:50 WARNING Thread-43 :: Could not connect to Trakt service: error 401 Client Error: Unauthorized
2015-04-18 19:33:50 WARNING Thread-43 :: Unauthorized. Please check your Trakt settings
2015-04-18 19:33:49 DEBUG Thread-43 :: trending blacklist name is empty

FYI:
SR Version: BRANCH: (develop) / COMMIT: (6ea3ae63640a78ef8280ff01ae02c7390de39781) 
Python Version: 2.7.6 (default, Nov 10 2013, 19:24:18) [MSC v.1500 32 bit (Intel)]
OS: Windows

**Comment by fernandog** [comment]
@Thraxis trakt already changed to PIN?

**Comment by Thraxis** [comment]
They've not announced anything about making the final shut-off of the Media Center auth yet.

https://medium.com/@trakt/api-changelog-9f4041819718

**Comment by TagForce** [comment]
@Thraxis With their trak(t)-records of changing stuff without notification or warnings in the past months, I wouldn't bet on it not being shut-down (even if by mistake).

**Comment by fernandog** [comment]
@cyberundertaker can you test it again? Here it's working

**Comment by cyberundertaker** [comment]
@fernandog no, still not working

Trakt API did not return any results, please check your config.

2015-04-22 19:23:53 WARNING  Thread-42 :: Could not connect to Trakt service: error 401 Client Error: Unauthorized
2015-04-22 19:23:53 WARNING  Thread-42 :: Unauthorized. Please check your Trakt settings

**Comment by fernandog** [comment]
@cyberundertaker make sure you user/pass/api is everything ok! do you have special char in your trakt password?

**Comment by cyberundertaker** [comment]
@fernandog i don't have a trakt account. it used to work ok, but since they changed their API it stopped working. so i guess my only option is to get trakt account and it should work ok?

**Comment by fernandog** [comment]
@cyberundertaker trending shows are powered by trakt

**Comment by cyberundertaker** [comment]
@fernandog i know, but it used to work without entering trakt user/pass...
btw, where to enter them?

**Comment by fernandog** [comment]
@cyberundertaker notifications - social

**Comment by cyberundertaker** [comment]
@fernandog  now it's working. thanks
