### ISSUE TITLE
[APP SUBMITTED]: No JSON object could be decoded

### ISSUE THREAD

**Issue by TheFuzzyOne87** [SiCKRAGETV/sickrage-issues#1318]
### INFO
Python Version: **2.7.9 (default, Mar 22 2015, 23:26:38) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@281409d366b228a455879e02b2d55d3967db29e4
Link to Log: https://gist.github.com/d70eb4f4f2e8daf9de25
### ERROR
```
SEARCHQUEUE-MANUAL-82696 :: [Rarbg] :: Rarbg json load failed.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@TheFuzzyOne87 disable proxy for rarbg

**Comment by TheFuzzyOne87** [comment]
Thanks @fernandog !!!
