### ISSUE TITLE
sickrage not seeing results from morethan.tv

### ISSUE THREAD

**Issue by cwallace** [SiCKRAGETV/sickrage-issues#1321]
SR Version:	BRANCH: (master) / COMMIT: (281409d366b228a455879e02b2d55d3967db29e4) 
SR User:	rtorrent
SR Locale:	(None, None)
SR Config file:	/opt/sickrage/config.ini
SR Database file:	/opt/sickrage/sickbeard.db
SR Cache Dir:	/opt/sickrage/cache
SR Log Dir:	/opt/sickrage/Logs
SR Arguments:	['-q', '--daemon', '--nolaunch', '--pidfile=/opt/sickrage/sickrage.pid', '--datadir=/opt/sickrage']
Python Version:	2.7.8 (default, Oct 20 2014, 15:05:19) [GCC 4.9.1]

Sickrage does not seem to be receiving or parsing results from morethan.tv

```
2015-04-19 04:28:49 INFO     SEARCHQUEUE-BACKLOG-281630 :: No needed episodes found during backlog search for: [Scorpion]
2015-04-19 04:28:49 DEBUG    SEARCHQUEUE-BACKLOG-281630 :: The Data returned from MoreThanTV do not contains any torrent
2015-04-19 04:28:49 DEBUG    SEARCHQUEUE-BACKLOG-281630 :: Search string: http://www.morethan.tv/torrents.php?tags_type=1&order_by=time&order_way=desc&action=basic&searchsubmit=1&searchstr=Scorpion S01E21 
2015-04-19 04:28:49 INFO     SEARCHQUEUE-BACKLOG-281630 :: Performing episode search for Scorpion
```

When visiting the search string in a browser, morethan.tv returns results:
http://i.imgur.com/eeRmWxl.png

**Comment by fernandog** [comment]
@cwallace open this url and print result

http://www.morethan.tv/torrents.php?tags_type=1&order_by=time&order_way=desc&action=basic&searchsubmit=1&searchstr=Scorpion S01E21

**Comment by cwallace** [comment]
I'm sorry what do you mean "print the result"?

**Comment by abeloin** [comment]
What is the result of opening this URl in your browser?

**Comment by cwallace** [comment]
I posted a screenshot of the results in OP.

**Comment by abeloin** [comment]
@cwallace I meant the source code as it must have change hence the `The Data returned from MoreThanTV do not contains any torrent`

**Comment by cwallace** [comment]
http://pastebin.com/C7ANnCUp

**Comment by roquemore92** [comment]
Just want to confirm that this is not just an issue for him. I'm having the same issue. All searches on morethan.tv, whether manual or daily give the same result as @cwallace

**Comment by abeloin** [comment]
@cwallace Thanks will check the code in the provider

**Comment by fernandog** [comment]
@Sparhawk76 can you check this? probably site has changed

**Comment by Sparhawk76** [comment]
Very minor change needed here, the site was changed to force https, Been busy on another higher priority project so haven't had the time to submit an updated script. Basically the URLs in the provider script have to have http changed to https.

**Comment by cwallace** [comment]
That was a stupid easy fix. Replaced all instances to https and it works great now. Thank you @Sparhawk76!
