### ISSUE TITLE
[APP SUBMITTED]: list index out of range

### ISSUE THREAD

**Issue by amzeus** [SiCKRAGETV/sickrage-issues#1323]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@281409d366b228a455879e02b2d55d3967db29e4
No Log available with ERRORS: 
### ERROR
```
DAILYSEARCHER :: Exception generated in thread DAILYSEARCHER: list index out of range
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@amzeus without logs we can't do anything. please post full logs
