### ISSUE TITLE
[APP SUBMITTED]: EOF occurred in violation of protocol (_ssl.c:581)

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#1324]
### INFO
Python Version: **2.7.8 (default, Oct 20 2014, 15:05:29) [GCC 4.9.1]**
Operating System: **Linux-3.16.0-34-generic-i686-with-Ubuntu-14.10-utopic**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@6ea3ae63640a78ef8280ff01ae02c7390de39781
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-MANUAL-271546 :: [Rarbg] :: Unable to connect to Rarbg provider: error EOF occurred in violation of protocol (_ssl.c:581)
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by matigonkas** [comment]
log when this happen https://gist.githubusercontent.com/matigonkas/d56b891037ecc2d39f75/raw/71fd1e3b0cf8244998dd0562a4fa4b629e76a370/gistfile1.txt

**Comment by abeloin** [comment]
Possible fix: 
http://stackoverflow.com/questions/14102416/python-requests-requests-exceptions-sslerror-errno-8-ssl-c504-eof-occurred

**Comment by fernandog** [comment]
@abeloin should we add

```
import ssl
from functools import wraps
def sslwrap(func):
    @wraps(func)
    def bar(*args, **kw):
        kw['ssl_version'] = ssl.PROTOCOL_TLSv1
        return func(*args, **kw)
    return bar

ssl.wrap_socket = sslwrap(ssl.wrap_socket)
```

here:
https://github.com/SiCKRAGETV/SickRage/blob/develop/SickBeard.py#L59

**Comment by fernandog** [comment]
@miigotu do you know why this regex don't match this ?

from log above:
2015-04-19 14:01:52 ERROR    SEARCHQUEUE-MANUAL-271546 :: [Rarbg] :: Unable to connect to Rarbg provider: error EOF occurred in violation of protocol (_ssl.c:581)

regex = "^(%s)\s*([A-Z]+)\s*(.+?)\s*\:\:\s*(.*)$" % curError.time

as regex didn't match, issue has not log in gist. We have a lot of issue without logs because of this

**Comment by miigotu** [comment]
Was confused, you didnt use tags...
You could try this:
`regex = "^(%s)\s*([A-Z]*)\s*([A-Z\-]*)\s*\:\:\s*(.*)$" % curError.time`

**Comment by fernandog** [comment]
@miigotu didn't match: https://regex101.com/r/uD9sT9/1

**Comment by miigotu** [comment]
`^(%s)\s*([A-Z]*)\s*([A-Z\-0-9]*)\s*::\s*(.*)$`
This does, you have to replace the %s to get it to compute, with valid regex or the string
swap %s with `[0-9\ \-:]*`

**Comment by miigotu** [comment]
The first one works too xD, the \ before : are optional there.

**Comment by miigotu** [comment]
@fernandog should I work on a pr for this?  I think there is a bug in the submitter as well.

**Comment by fernandog** [comment]
@miigotu ok!

**Comment by miigotu** [comment]
I might have the submitter not creating dupe issues, just commenting the matching issue with their log..... 0.o

**Comment by fernandog** [comment]
@miigotu sorry, didn't get it

**Comment by miigotu** [comment]
@fernandog how did you get the issue_submitter_test working on Mar 11?

**Comment by fernandog** [comment]
@miigotu just run. Didnt do anything else.

There is another issue with issue submitter:
https://github.com/SiCKRAGETV/sickrage-issues/issues/1282

Lets continue there.

**Comment by fernandog** [comment]
@abeloin should we change milestone?
