### ISSUE TITLE
Testing Plex Media Server notifications

### ISSUE THREAD

**Issue by CptChaos** [SiCKRAGETV/sickrage-issues#1325]
It's not a bug or something, so I can't give any logs or something.
I have a Plex Media Server setup and I've set it up that Sick Rage sends a notification to update the libraries after a download completes. I'd like to test that it's working, but somehow I also need the Plex Media client to be setup for it; which I don't use.

On PC I use the browser to manage and watch with Plex and on my TV, well... "There's an app for that!" ;) So I do not know if SR sends Plex Media Server a notification to update the libraries and even cannot test it.

I've got everything setup, including the token required for it to work.
So it would be nice if Plex Media Server could be tested without settings for Plex Media Client.

**Comment by Thraxis** [comment]
The Plex Notification settings in the next Master update will seperate the PMS and Plex Client testing and setup from each other. It is currently testing develop

**Comment by Thraxis** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1764

This was merged into Master and should be able to test now.

There will be some work to seperate Plex Media Server and Plex Media Client more but for now you can setup and test each seperately.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1364
