### ISSUE TITLE
[APP SUBMITTED]: [Error 2] The system cannot find the file specified: u'X:\\TV\\aaa to file\\The Brittas Empire[1991]\\The Brittas Empire_S02E02_Temple of the Body.avi'

### ISSUE THREAD

**Issue by amzeus** [SiCKRAGETV/sickrage-issues#1327]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@281409d366b228a455879e02b2d55d3967db29e4
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: error 2 : The system cannot find the file specified
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@amzeus check if the file was already PP and is in destination folder

**Comment by TagForce** [comment]
@amzeus Can you provide the full logs?

**Comment by fernandog** [comment]
@amzeus reply or will close
