### ISSUE TITLE
[APP SUBMITTED]: [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

### ISSUE THREAD

**Issue by FelipeSQ** [SiCKRAGETV/sickrage-issues#1329]
### INFO
Python Version: **2.7.3 (default, Apr 12 2012, 13:08:47) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@281409d366b228a455879e02b2d55d3967db29e4
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-79685 :: [TorrentDay] :: Error while searching TorrentDay, skipping: error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
Check issue #978, it can help

**Comment by FelipeSQ** [comment]
Hey, thank you very much! I will try that, but it seems to be the solution! Thanks for that!

**Comment by abeloin** [comment]
@FelipeSQ If it doesn't, reopen the issue

**Comment by konomimaster** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 31 2015, 15:16:49) [GCC 4.9.2]**
Operating System: **Linux-3.18.10-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/c1bc38c5159783aebc33
### ERROR
```
SEARCHQUEUE-BACKLOG-84947 :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by konomimaster** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 31 2015, 15:16:49) [GCC 4.9.2]**
Operating System: **Linux-3.18.10-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/7f52747d166bfd860a1c
### ERROR
```
SEARCHQUEUE-BACKLOG-84947 :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by konomimaster** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 31 2015, 15:16:49) [GCC 4.9.2]**
Operating System: **Linux-3.18.10-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/3d45d4841ab79d1b5760
### ERROR
```
SEARCHQUEUE-BACKLOG-73800 :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by d97** [comment]
### INFO
Python Version: **2.7.3 (default, Apr 12 2012, 13:08:47) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/ca58444c10c0a74c9267
### ERROR
```
SEARCHQUEUE-BACKLOG-23384 :: [TorrentDay] :: Error while searching TorrentDay, skipping: error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by konomimaster** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 31 2015, 15:16:49) [GCC 4.9.2]**
Operating System: **Linux-3.18.10-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/c58d9bf3c30b8b6757c3
### ERROR
```
SEARCHQUEUE-BACKLOG-80301 :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by konomimaster** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 31 2015, 15:16:49) [GCC 4.9.2]**
Operating System: **Linux-3.18.10-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-80301 :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by d97** [comment]
### INFO
Python Version: **2.7.3 (default, Apr 12 2012, 13:08:47) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/48752997537f4ce249f1
### ERROR
```
SEARCHQUEUE-MANUAL-262414 :: [TorrentDay] :: Error while searching TorrentDay, skipping: error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by d97** [comment]
### INFO
Python Version: **2.7.3 (default, Apr 12 2012, 13:08:47) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/83839f86b48b543584d1
### ERROR
```
SEARCHQUEUE-MANUAL-262414 :: [TorrentDay] :: Error while searching TorrentDay, skipping: error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by oodonnell** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 23 2014, 01:44:56) [GCC 4.6.3]**
Operating System: **Linux-3.0.101.RN_ARM.3-armv7l-with-debian-7.7**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/99a3d2d7e288f6029bf3
### ERROR
```
SEARCHQUEUE-MANUAL-258744 :: Unable to connect to SceneAccess provider: error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by oodonnell** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 23 2014, 01:44:56) [GCC 4.6.3]**
Operating System: **Linux-3.0.101.RN_ARM.3-armv7l-with-debian-7.7**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/35bcbbe834c010e92d68
### ERROR
```
SEARCHQUEUE-MANUAL-258744 :: [SceneAccess] :: Unable to connect to SceneAccess provider: error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by konomimaster** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 31 2015, 15:16:49) [GCC 4.9.2]**
Operating System: **Linux-3.18.10-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/f3a05a7007dbc6494dc9
### ERROR
```
SEARCHQUEUE-BACKLOG-73800 :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
please test develop branch. If no 'develop' appears in the list of branches, please enter github user and pass in SR settings

**Comment by d97** [comment]
### INFO
Python Version: **2.7.3 (default, Apr 12 2012, 13:08:47) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
No Log available with ERRORS: 
### ERROR
```
FINDPROPERS :: [TorrentDay] :: Error while searching TorrentDay, skipping: error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
For anyone that would like to do some test to help us debug this: https://github.com/SiCKRAGETV/sickrage-issues/issues/1231#issuecomment-97677808

**Comment by d97** [comment]
### INFO
Python Version: **2.7.3 (default, Apr 12 2012, 13:08:47) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/0ae0c4e00fa43a91d879
### ERROR
```
FINDPROPERS :: [TorrentDay] :: Error while searching TorrentDay, skipping: error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
See [SSL Errors](https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors) for help.

**Comment by d97** [comment]
### INFO
Python Version: **2.7.3 (default, Apr 12 2012, 13:08:47) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/a0433f4f59264c40c19b
### ERROR
```
FINDPROPERS :: [TorrentDay] :: Error while searching TorrentDay, skipping: error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
See [SSL Errors](https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors) for help.

**Comment by sickrage1** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.8+-armv7l-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
See [SSL Errors](https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors) for help.

**Comment by konomimaster** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 31 2015, 15:16:49) [GCC 4.9.2]**
Operating System: **Linux-3.18.10-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/4eca77edfca8879fe36c
### ERROR
```
SEARCHQUEUE-BACKLOG-73800 :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
See [SSL Errors](https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors) for help.

**Comment by FelipeSQ** [comment]
### INFO
Python Version: **2.7.3 (default, Apr 12 2012, 13:08:47) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@b6c028c9a78d6208066697da9c9518771cc75280
Link to Log: https://gist.github.com/0fec8debc402b24b377b
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TorrentDay] :: Unable to connect to TorrentDay provider: error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
@FelipeSQ  See [SSL Errors](https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors) for help.

**Comment by konomimaster** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 31 2015, 15:16:49) [GCC 4.9.2]**
Operating System: **Linux-3.18.10-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@7af9a845c324bd0b0698da0ae85b68b54568f6e1
Link to Log: https://gist.github.com/b23def21a9d4e8b8a5b0
### ERROR
```
SEARCHQUEUE-BACKLOG-75760 :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
@konomimaster See [SSL Errors](https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors) for help.

**Comment by ecoolaid** [comment]
### INFO
Python Version: **2.7.5 (default, Apr 10 2015, 08:09:14) [GCC 4.8.3 20140911 (Red Hat 4.8.3-7)]**
Operating System: **Linux-3.12.5-301.fc20.i686+PAE-i686-with-fedora-20-Heisenbug**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@7af9a845c324bd0b0698da0ae85b68b54568f6e1
Link to Log: https://gist.github.com/787bf44c06d85d85a336
### ERROR
```
SEARCHQUEUE-MANUAL-121361 :: [TorrentDay] :: Unable to connect to TorrentDay provider: error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by ecoolaid** [comment]
### INFO
Python Version: **2.7.5 (default, Apr 10 2015, 08:09:14) [GCC 4.8.3 20140911 (Red Hat 4.8.3-7)]**
Operating System: **Linux-3.12.5-301.fc20.i686+PAE-i686-with-fedora-20-Heisenbug**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@7af9a845c324bd0b0698da0ae85b68b54568f6e1
Link to Log: https://gist.github.com/0b9c162ad591e7d6e1b3
### ERROR
```
SEARCHQUEUE-MANUAL-121361 :: Unable to connect to TorrentDay provider: error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neives** [comment]
@miigotu Thanks, that solved my problem!

**Comment by konomimaster** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 31 2015, 15:16:49) [GCC 4.9.2]**
Operating System: **Linux-3.18.10-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@1c1f80877b22531fe73aef61fad784b140fef605
Link to Log: https://gist.github.com/087834faf5dd9744f14d
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by konomimaster** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 31 2015, 15:16:49) [GCC 4.9.2]**
Operating System: **Linux-3.18.10-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@1c1f80877b22531fe73aef61fad784b140fef605
Link to Log: https://gist.github.com/b93388977c4b32f0d350
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Update, error will give you a link now. Follow the instructions at the link.

**Comment by FelipeSQ** [comment]
Hey, miigotu, thank you very much for your response. Regarding that, I am currently using python 2.7 on my QNAP 212, and this is the message I get when starting SickRage manually with debug.

+ /opt/bin/python2.7 SickBeard.py --daemon --pidfile /tmp/SickBeard-TVRage.pid
SNI is disabled when the cryptography module is missing. You may encounter SSL errors!

Seems that the "import cryptography" is returning an error. I went to ipkg and tried installing openssl and pycrypto (the version available is the version 2.1.0-2) but that still doesn't seem to fix my problem. I tried installing the 3.2 version of Python available in there as well, but Sickrage says it needs either version 2.6 (with cheetah) or 2.7, so I am still stuck on this. Any tips or help is appreciated.

**Comment by miigotu** [comment]
cryptography is not the same as pycrypto. Either get cryptography, or update python to 2.7.9. I don't think there is currently a solution for this problem on QNAP, until they either make some packages with the headers from python-dev, libssl-dev, and libffi-dev, or provide a package that gives you a prebuilt cryptography, or a package with python 2.7.9.

**Comment by FelipeSQ** [comment]
Cool. I will keep an eye out to see when they will fix the released version of python. Thank you, very much.

**Comment by miigotu** [comment]
FelipeSQ, I have made a change, and I think you can get it working on QNAP if you update to develop branch, install pip, and do 
`pip install pyopenssl==0.13.1''

**Comment by FelipeSQ** [comment]
@miigotu. Perfect! I will try it tonoght when I get back home and will let you know the results! Thanks a bunch

**Comment by FelipeSQ** [comment]
I was able to install pip. When I tried to install pyopenssl, I had an error saying it couldn't find /opt/bin/gcc, I installed the gcc, and tried again following the easy steps there:http://git.io/vJrkM

The install went quite neat. I had to point to the right directory of my pip2.7, but worked like a charm.
But when I tried starting SickRage again, I got this message (that states the same thing, in the end)

SNI is disabled with pyOpenSSL >= 0.14 when the cryptography module is missing,
you will encounter SSL errors with HTTPS! To fix this issue:
pip install pyopenssl==0.13.1 (easy) or pip install cryptography (pita)

So either it couldn't find my installation of pyOpenSLL done through pip (pip was installed in my /opt/local/bin/ folder) whereas my python2.7 is installed on /opt/bin. And the local folder is not part of my PATH (tbh, these are just random question, I don't know if that would do anything to my problem).

PS: I also tried the (pita) mode :P But, as you can imagine, it failed with a problem that seems to be related to cffi.

If you have any other suggestions, I would gladly try them.

Cheers!
