### ISSUE TITLE
[Feature Request] Improve detection of quality labels of downloads without correct title

### ISSUE THREAD

**Issue by xInsertx** [SiCKRAGETV/sickrage-issues#1332]
With media that only has the resolution/quality in the name (ie: 720p or 1280x720) is this suppose to display Downloaded Unknown? Surely we can handle this abit better by saying the closet source type (maybe HDTV) or just label as 720p.

I raise this because after switching to sickrage for anime (which is wonderful since anime got its own rename field), often source is not included unless it's coming for dvd/bd; so the entire page is full of "Download Unknown". It does however detect SD correctly just nothing above it.

Example [SomeGroup] Some Anime - 01 [720p].mkv => Some.Anime.S01E01.720p.SomeGroup.mkv

The above would than be listed as Download Unknown.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
