### ISSUE TITLE
[APP SUBMITTED]: global name 'ServiceError' is not defined

### ISSUE THREAD

**Issue by andyblac** [SiCKRAGETV/sickrage-issues#1337]
### INFO
Python Version: **2.7.9 (default, Mar 23 2015, 00:07:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@057e85a3e32a44cf4912d02662dd3de9f9679d5e
Link to Log: https://gist.github.com/b946c6dc41db978a7a58
### ERROR
```
Thread-49 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickBeard/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickBeard/sickbeard/webserve.py", line 3007, in downloadSubtitleMissed
    subtitles = show.getEpisode(int(season), int(episode)).downloadSubtitles()
  File "/volume1/@appstore/sickrage/var/SickBeard/sickbeard/tv.py", line 1440, in downloadSubtitles
    except ServiceError as e:
NameError: global name 'ServiceError' is not defined

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
Fixed in master and develop. Update and test

**Comment by fernandog** [comment]
@andyblac please report if is fixed

**Comment by andyblac** [comment]
just done a git pull, and not noticeed the error, please close as fixed, i'll reopen if it happened again.

Thanks
Andy.
