### ISSUE TITLE
[APP SUBMITTED]: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by amzeus** [SiCKRAGETV/sickrage-issues#1338]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@a5dd1d93107d03b406d2a14f99bd29bfffc7c0d5
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Unable to copy file X:\TV\aaa to file\Auction Hunters - Season 1\Auction.Hunters.S01E06.HDTV.XviD-sHoTV.avi to Y:\Auction Hunters\Season 01\Auction Hunters - S01E06 - Weapons of Past Destruction.avi: error 13 : Permission denied
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
Please provide full debug logs

**Comment by fernandog** [comment]
@amzeus please post you full PP folder and your tv shows folder.

**Comment by fernandog** [comment]
@amzeus X: and Y: are different partitions? what are the filesystems of them? samba share, NFS? check permissions? user?

**Comment by fernandog** [comment]
@amzeus please reply or will close

**Comment by amzeus** [comment]
sorry for delay they are NAS shared drives (readynas 314) and permissions are fine, haven't changed since i had them when running SR in Ubuntu and it works fine for around 6 months then

**Comment by fernandog** [comment]
@amzeus so you keep your file seeding? or do you have Windows Indexer enabled?

**Comment by amzeus** [comment]
its a complected set up but heres the bit of the network that is related to this
U torrent is on xxx.xxx.xxx.006 it downloads the files and seeds to 1:1 when this is achieved they are then moved them to a nas xxx.xxx.xxx.101 drive X:

SR runs on an machine xxx.xxx.xxx.23 along side CP, MyLar, this machine access the x drive and SR catalogs the content from the Folder X:// TV (CP only access X:// Movies and mylar only x://Ebooks) both CP and Mylar are working fine.

i have no indexing or seeding on the x:// drive at all

**Comment by fernandog** [comment]
@amzeus maybe SR is trying to PP a file while utorrent is copying the file to X. 
do you always get this error or sometimes?

**Comment by amzeus** [comment]
the error the SR is setting show back to unaired rather than missed has only started since moving to windows to run SR, 

if i manually down load the file SR finds it and moves/copies it just fine. 

the error isnt really about the files that have been down loaded its about SR showing them on coming soon unitl the aired date then not snatching them or showing them as missed but going back to unaired

**Comment by fernandog** [comment]
If sometimes works and sometimes not, its not a SR issue. Its something outside SR.
how long does it take to utorrent move it?

**Comment by fernandog** [comment]
@TagForce cant we add the file lock check in PP? I posted a script in another issue. Did you saw it?

**Comment by TagForce** [comment]
@fernandog Haven't seen it yet, but I'll look for it.

**Comment by fernandog** [comment]
postest in STATs:

@TagForce what do you think add a check if the file is in use/locked in windows?

Permission denied can happen when the file that SR is trying to PP is still locked. Not only about permissions in destination folder. With this we can change the log error message.
http://blogs.blumetech.com/blumetechs-tech-blog/2011/05/python-file-locking-in-windows.html

**Comment by TagForce** [comment]
@fernandog Ok, weird stuff...
While testing the code to check for a file lock something strange happened.
The read lock check returns False (not locked) when the file is only accessible (as in, unreadable and unwritable), but when the file is completely inaccessible (REALLY unreadable and unwritable (??)) the verify_freespace check returns not enough free space because it's unable to even get the filesize.

**Comment by fernandog** [comment]
@TagForce isn't that correct? can't verify something that is locked

**Comment by TagForce** [comment]
@fernandog Yes, but I would want to log that, and not log that there's not enough free space available.
I fixed it. Verify_freespace is now preceeded by an isFileLocked check. isFileLocked will now also return True instead of False when os.path.isfile(filename) fails (which it will when a file is locked for reading).

**Comment by TagForce** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1821

Please test this

**Comment by fernandog** [comment]
@amzeus any more errors so far?

**Comment by srge1827** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/c4eeeff7fd56f42255cc
### ERROR
```
POSTPROCESSER :: Unable to move file E:\Post-Processing\Greys.Anatomy.S07E01.HDTV.XviD-LOL.avi to D:\Gianni\TV SHOWS\Grey's Anatomy\Season 07\Grey's Anatomy - S07E01 - With You I'm Born Again.avi: error 13 : Permission denied
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by reniers** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@cfe3b40b30ecec5c1838a5b6898bd79faf0ea762
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Unable to move file C:\Downloads\Completed Downloads\[ www.torrenting.com ] - The.Big.Bang.Theory.S08E24.HDTV.x264-LOL\the.big.bang.theory.824.hdtv-lol.mp4 to F:\Series\The Big Bang Theory\Season 8\The Big Bang Theory - 8x24 - The Commitment Determination.mp4: error 13 : Permission denied
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by pct00** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@50b81987274e704c6e1b9ffdbf1e436368ac2acd
Link to Log: https://gist.github.com/67083bbd3fdf7d5a588c
### ERROR
```
POSTPROCESSER :: Unable to move file c:\uTorrent\Complete\0----- TO PROCESS\Hawaii.Five-0.2010.S05E24.HDTV.x264-LOL.[VTV].mp4 to Z:\Hawaii Five-0\Hawaii Five-0 - Season 05\Hawaii Five-0 - S05E24 - SD TV - Luapo’i.mp4: error 13 : Permission denied
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by reniers** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@bf2baf309bd01683fdc06d57ece0b89d53b4a180
Link to Log: https://gist.github.com/ce51164fb175d7e6f001
### ERROR
```
Thread-80 :: Unable to copy file C:\Downloads\Completed Downloads\The.Flash.2014.S01E22.HDTV.x264-LOL[ettv]\the.flash.2014.122.hdtv-lol.mp4 to F:\Series\The Flash\Season 1\The Flash - 1x22 - Rogue Air.mp4: error 13 : Permission denied
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by flaifel** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@bf2baf309bd01683fdc06d57ece0b89d53b4a180
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Unable to move file E:\Download\Arrow.S03E23.720p.HDTV.X264-DIMENSION[rarbg]\Arrow.S03E23.720p.HDTV.X264-DIMENSION.mkv to H:\Tvshow\Arrow\Season 03\Arrow.S03E23.HDTV-DIMENSION.mkv: error 13 : Permission denied
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@amzeus @pct00 

did you received any of this messages?

"File is locked for reading/writing"
OR
"File is locked for reading"

no more "[Errno 13] Permission denied" errors?

**Comment by pct00** [comment]
@fernandog 
hi Fernando
still happens when the destination file already exists and is the same size as the file being processed

if i process manually i can see that is the reason of the error. if i run manually with the option to treat the files as priority download it works perfectly

the ep status in SR is snatched so shouldt the new downloaded version replace the old file also in automatic processing?

**Comment by miigotu** [comment]
Not if it is the same size, it assumes it is the same file.
