### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-DAILY-SEARCH :: No NZB/Torrent providers found or enabled in the sickrage config for daily searches. Please check your settings.

### ISSUE THREAD

**Issue by amzeus** [SiCKRAGETV/sickrage-issues#1339]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@a5dd1d93107d03b406d2a14f99bd29bfffc7c0d5
Link to Log: https://gist.github.com/f4bb33774b172744336c
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: No NZB/Torrent providers found or enabled in the sickrage config for daily searches. Please check your settings.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Please follow installation instructions in forum
