### ISSUE TITLE
[APP SUBMITTED]: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing: incorrect header check',))

### ISSUE THREAD

**Issue by krash1220** [SiCKRAGETV/sickrage-issues#1340]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@a5dd1d93107d03b406d2a14f99bd29bfffc7c0d5
Link to Log: https://gist.github.com/ef7d4646ab9bed3aae40
### ERROR
```
FINDPROPERS :: Unable to save the file: error ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing: incorrect header check',))
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
Using qbittorrent?

If so can you provide the qbittorrent version you are using? This error mean qbittorent return an answer compressed in gzip but the requests library wasn't able to decompress it.

**Comment by Thraxis** [comment]
@abeloin would this be of help?

**Comment by krash1220** [comment]
No I’m not using any torrent program.






Sent from Windows Mail





From: Alexandre Beloin
Sent: ‎Monday‎, ‎April‎ ‎20‎, ‎2015 ‎1‎:‎05‎ ‎PM
To: SiCKRAGETV/sickrage-issues
Cc: krash1220





Using qbittorrent?

If so can you provide the qbittorrent version you are using? This error mean qbittorent return an answer compressed in gzip but the requests library wasn't able to decompress it.

**Comment by krash1220** [comment]
This started right after I updated today. 



BRANCH: (master) / COMMIT: (a5dd1d93107d03b406d2a14f99bd29bfffc7c0d5) 


Sent from Windows Mail





From: Alexandre Beloin
Sent: ‎Monday‎, ‎April‎ ‎20‎, ‎2015 ‎1‎:‎05‎ ‎PM
To: SiCKRAGETV/sickrage-issues
Cc: krash1220





Using qbittorrent?

If so can you provide the qbittorrent version you are using? This error mean qbittorent return an answer compressed in gzip but the requests library wasn't able to decompress it.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1365

**Comment by fernandog** [comment]
@Thraxis we can try!

**Comment by fernandog** [comment]
@krash1220 are you using reverse proxy?

**Comment by krash1220** [comment]
no, no proxy






Sent from Windows Mail





From: Fernando
Sent: ‎Wednesday‎, ‎April‎ ‎22‎, ‎2015 ‎8‎:‎33‎ ‎AM
To: SiCKRAGETV/sickrage-issues
Cc: krash1220





@krash1220 are you using reverse proxy?

**Comment by fernandog** [comment]
@krash1220 do you always get this error? or only sometimes?

**Comment by krash1220** [comment]
sorry I got busy and forgot all about this. it stopped doing it after a couple of updates, haven’t gotten it since. thanks and sorry for not getting back sooner








Sent from Windows Mail





From: Fernando
Sent: ‎Thursday‎, ‎April‎ ‎23‎, ‎2015 ‎4‎:‎02‎ ‎PM
To: SiCKRAGETV/sickrage-issues
Cc: krash1220





@krash1220 do you always get this error? or only sometimes?

**Comment by fernandog** [comment]
Please reply if happens again

**Comment by hypertux001** [comment]
However this issue is happening to me as well and I am on the latest version.

**Comment by Djripper66** [comment]
mine is showing the same error and i have updated and that is the time frame 
2015-06-16 09:32:20 SEARCHQUEUE-BACKLOG-255316 :: Unable to save the file: error ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing: incorrect header check',))
2015-06-16 09:29:43 SEARCHQUEUE-BACKLOG-255316 :: Unable to save the file: error ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing: incorrect header check',))
2015-06-16 09:27:18 SEARCHQUEUE-BACKLOG-255316 :: Unable to save the file: error ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing: incorrect header check',))
2015-06-16 09:27:11 SEARCHQUEUE-BACKLOG-255316 :: Unable to save the file: error ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing: incorrect header check',))
2015-06-16 09:24:50 SEARCHQUEUE-BACKLOG-255316 :: Unable to save the file: error ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing: incorrect header check',))
at which im getting the errors i have submitted a ticket but thought i would let you know im getting the errors still. :) P.S. Im on synology.
