### ISSUE TITLE
Unable to process an episode

### ISSUE THREAD

**Issue by Alexwijn** [SiCKRAGETV/sickrage-issues#1341]
Problem: one of the episodes is unable to get processed by the auto-processing or when manually forcing it.

Python Version: 2.7.3 (default, Mar 18 2014, 05:13:23) 
[GCC 4.6.3]
Operating System: Linux-3.18.7+-armv6l-with-debian-7.8
Branch: master
Commit: SiCKRAGETV/SickRage@281409d

Log: 

    Processing folder /mnt/osmc/data/Downloads/Done/Forever.S01E02.Look.Before.You.Leap.720p.WEB-DL.DD5.1.H.264-ECI[rarbg]
    TV_DOWNLOAD_DIR: /mnt/osmc/data/Downloads/Done
    PostProcessing Path: /mnt/osmc/data/Downloads/Done/Forever.S01E02.Look.Before.You.Leap.720p.WEB-DL.DD5.1.H.264-ECI[rarbg]
    PostProcessing Dirs: []
    PostProcessing Files: ['Forever.S01E02.Look.Before.You.Leap.720p.WEB-DL.DD5.1.H.264-ECI.mkv', 'RARBG.com.txt', 'Forever.S01E02.Look.Before.You.Leap.720p.WEB-DL.DD5.1.H.264-ECI.srt']
    PostProcessing VideoFiles: ['Forever.S01E02.Look.Before.You.Leap.720p.WEB-DL.DD5.1.H.264-ECI.mkv']
    PostProcessing RarContent: []
    PostProcessing VideoInRar: []
    Processing /mnt/osmc/data/Downloads/Done/Forever.S01E02.Look.Before.You.Leap.720p.WEB-DL.DD5.1.H.264-ECI[rarbg]/Forever.S01E02.Look.Before.You.Leap.720p.WEB-DL.DD5.1.H.264-ECI.mkv (None)
    This show isn't in your list, you need to add it to SB before post-processing an episode
    Processing failed for /mnt/osmc/data/Downloads/Done/Forever.S01E02.Look.Before.You.Leap.720p.WEB-DL.DD5.1.H.264-ECI[rarbg]/Forever.S01E02.Look.Before.You.Leap.720p.WEB-DL.DD5.1.H.264-ECI.mkv: 
    Problem(s) during processing, failed the following files/folders: 
    [/mnt/osmc/data/Downloads/Done/Forever.S01E02.Look.Before.You.Leap.720p.WEB-DL.DD5.1.H.264-ECI[rarbg]/Forever.S01E02.Look.Before.You.Leap.720p.WEB-DL.DD5.1.H.264-ECI.mkv : Processing failed: ]

**Comment by fernandog** [comment]
@Alexwijn add Forever to scene exceptions

**Comment by Alexwijn** [comment]
Whoops...totally forgot about that
