### ISSUE TITLE
[Feature request] - Set permission of moved files to that of destination folder (Windows NTFS only)

### ISSUE THREAD

**Issue by Rouzax** [SiCKRAGETV/sickrage-issues#1342]
I know that CouchPotato and SickRage are different but a lot of the core functionality seems top be the same.

In my environment I have an issue with file move and NTFS permissions
![image](https://cloud.githubusercontent.com/assets/4103090/7236832/b4d6136a-e797-11e4-8711-d45cd6cb6116.png)
This has to do how Windows handles NTFS permissions during a move on the same physical disk.
A workaround is to set SickRage to Copy instead of move but this use a lot of extra time, process power and temporary space.

Would it be possible to have an option like CouchPotato?
![image](https://cloud.githubusercontent.com/assets/4103090/7236887/187f0804-e798-11e4-9fae-cd4142e124ec.png)
The code in question is located here
https://github.com/RuudBurger/CouchPotatoServer/blob/master/couchpotato/core/plugins/renamer.py
![image](https://cloud.githubusercontent.com/assets/4103090/7236959/9643dada-e798-11e4-8bd1-4789ec7c835b.png)

That would be very helpfull.

**Comment by Rouzax** [comment]
Any chance this might be included in the future?

**Comment by miigotu** [comment]
@Rouzax we are trying to avoid os dependant calls that aren't even available on all fersions of that OS.

icacls isn't always available.

Maybe you could add a post processing script?

**Comment by Rouzax** [comment]
It is available in Windows 8, Windows Server 2008, Windows Server 2012.
That makes sense although it is a shame :smile:

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
