### ISSUE TITLE
[APP SUBMITTED]: global name 'ServiceError' is not defined

### ISSUE THREAD

**Issue by bitzorro** [SiCKRAGETV/sickrage-issues#1343]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@a5dd1d93107d03b406d2a14f99bd29bfffc7c0d5
Link to Log: https://gist.github.com/5f4e6b2e7fc6a2d80b35
### ERROR
```
Thread-51 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 3007, in downloadSubtitleMissed
    subtitles = show.getEpisode(int(season), int(episode)).downloadSubtitles()
  File "C:\SickRage\sickbeard\tv.py", line 1440, in downloadSubtitles
    except ServiceError as e:
NameError: global name 'ServiceError' is not defined

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
Dupe https://github.com/SiCKRAGETV/sickrage-issues/issues/1337
