### ISSUE TITLE
[Feature request] Add login ability for fnt.nu

### ISSUE THREAD

**Issue by Audaly** [SiCKRAGETV/sickrage-issues#1346]
Can you please add fnt.nu as torrent provider?

This sickbeard fork has it: https://github.com/sarakha63/Sick-Beard

**Comment by maxcore** [comment]
+1

**Comment by WebSpider** [comment]
Was looking to see if I can pick it up, but the fork seems to have disappeared. Are there any other forks out there that have this code readily available?

**Comment by maxcore** [comment]
@WebSpider  load sickrage ? fnt is on

**Comment by WebSpider** [comment]
Then why is this issue still open?

**Comment by maxcore** [comment]
I dont know why is open
