### ISSUE TITLE
Plex notifications broken in latest update

### ISSUE THREAD

**Issue by Arcanemagus** [SiCKRAGETV/sickrage-issues#1348]
Plex Media Server notifications have been broken in the last major update (https://github.com/SiCKRAGETV/SickRage/compare/281409d366b228a455879e02b2d55d3967db29e4...057e85a3e32a44cf4912d02662dd3de9f9679d5e).

I believe it is something within this commit by @Thraxis https://github.com/SiCKRAGETV/SickRage/commit/4c9d9185b0c25d435a6bbb20efa60b1f4337a016 merged by @fernandog.

Although the test button in the settings shows a sucess, attempting a notification to Plex from the main page (or automatically on download) gives the following in the log:

    2015-04-20 16:46:13 DEBUG    Thread-124 :: PLEX: Updating all hosts with TV sections: 
    AAIOError: ('http error', 401, 'Unauthorized', <httplib.HTTPMessage instance at 0x81447ef38>)
    AA    raise IOError, ('http error', errcode, errmsg, headers)
    AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/urllib.py", line 381, in http_error_default
    AA    errcode, errmsg, headers)
    AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/urllib.py", line 683, in http_error_401
    AA    result = method(url, fp, errcode, errmsg, headers)
    AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/urllib.py", line 372, in http_error
    AA    return self.http_error(url, fp, errcode, errmsg, headers)
    AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/urllib.py", line 359, in open_http
    AA    return getattr(self, name)(url)
    AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/urllib.py", line 208, in open
    AA    return opener.open(url)
    AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/urllib.py", line 87, in urlopen
    AA    xml_tree = etree.parse(urllib.urlopen(url))
    AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/notifiers/plex.py", line 224, in update_library
    AATraceback (most recent call last):
    AACache-Control: no-cache
    AAX-Plex-Protocol: 1.0
    AAContent-Type: text/html
    2015-04-20 16:46:13 ERROR    Thread-124 :: PLEX: Error while trying to contact Plex Media Server: http error : error 401 : Unauthorized : error Content-Length: 91
    2015-04-20 16:45:50 DEBUG    Thread-143 :: PLEX: Updating all hosts with TV sections: plex.localnet.local:32400

The fun part is that it shows a notification that _appears_ like it succeeded, but checking the logs shows the error above, and the Plex server shows no updating in its logs. The notification shown is:

    Library update command sent to Plex Media Server host:...

Looking into the code now to see if I can get it fixed.

Oh and here is the SickRage info:

    SR Version:	BRANCH: (master) / COMMIT: (a5dd1d93107d03b406d2a14f99bd29bfffc7c0d5) 
    SR User:	media
    SR Locale:	(None, None)
    SR Config file:	/var/db/sickrage/config.ini
    SR Database file:	/var/db/sickrage/sickbeard.db
    SR Cache Dir:	/var/db/sickrage/cache
    SR Log Dir:	/var/db/sickrage/Logs
    SR Arguments:	['--datadir', '/var/db/sickrage', '-d', '--pidfile', '/var/run/sickrage/sickrage.pid', '-q', '--nolaunch']
    Python Version:	2.7.8 (default, Dec 15 2014, 02:33:48) [GCC 4.2.1 20070831 patched [FreeBSD]]

**Comment by abeloin** [comment]
error 401 : Unauthorized

Check your credential, and post your plex settings in SR.

**Comment by Arcanemagus** [comment]
Update:

Entering in the username and password actually is working currently, even though just the authentication token should be sufficient. Things are still not working properly though as, although it does cause the Plex server to update its libraries it displays the following notification:

    Unable to contact Plex Media Server host: plex.localnet.local:32400

The log only shows:

    2015-04-20 17:16:13 DEBUG    Thread-143 :: PLEX: Updating all hosts with TV sections: plex.localnet.local:32400
    2015-04-20 17:16:12 DEBUG    Thread-143 :: PLEX: fetching plex.tv credentials for user: ***********

**Comment by Thraxis** [comment]
@Arcanemagus I have run this against my test PMS today and for all five of the shows I had post process today the Plex notification worked without issue using the token.

If you use a token the only thing you will see in your log would be:
2015-04-20 19:14:32 DEBUG    Thread-50 :: PLEX: Updating all hosts with TV sections: localhost:32400

If you use the username and password you will see the two lines you mentioned. 

As for the following message
```
Unable to contact Plex Media Server host: plex.localnet.local:32400
```

As you discovered the MANUAL updatePlex function was not updated (my fault, I was concerned only with the post processing update library call) and it will need to be fixed to reflect the correct status of success / failure and the proper message to show on screen.

**Comment by Arcanemagus** [comment]
Automatic notifications were broken on my installation, hence why I even discovered this bug. I'm assuming you have your user/pass credentials entered into your settings as that is the only method that currently works on the master branch. If you only have the authentication token entered, as I do, notifications are entirely broken.

**Comment by Thraxis** [comment]
@Acanemagus You've got PlexPass I'm presuming

Lovely idiots that Plex is... If you don't have PlexPass then it could care less what you put into the Token field..  Which is why I didn't catch this in testing

**Comment by Arcanemagus** [comment]
@Thraxis that is... disturbing. I'm hoping with their promised security revamp due "soon" things like that will get fixed. (And yes, I managed to snag the lifetime PlexPass back before the price hike.)

**Comment by Thraxis** [comment]
@abeloin @fernandog PR#1808 and PR#1810 fix the issues.

**Comment by fernandog** [comment]
@Thraxis @Arcanemagus both merged

**Comment by Arcanemagus** [comment]
@fernandog Thanks!
