### ISSUE TITLE
[APP SUBMITTED]: 'ascii' codec can't encode character u'\xc9' in position 77: ordinal not in range(128)

### ISSUE THREAD

**Issue by Nibeck1309** [SiCKRAGETV/sickrage-issues#1351]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.7+-armv6l-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@975c0dd208c59cac8fd8a77a91da5d1dfc7235df
Link to Log: https://gist.github.com/46d60aa7ac97e7e7bd05
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: ascii : /media/media/Animes/One Piece/Season 17/One_Piece_-_S17E61_-_689_-_La_Grande_Évasion_!_Luffy_revient_de_la_mort_avec_un_Elephant_Gun_-_HD_TV.mp4 : error 77 : error 78 : ordinal not in range(128)
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@Nibeck1309 set your locale as utf-8 in linux
