### ISSUE TITLE
[APP SUBMITTED]: list index out of range

### ISSUE THREAD

**Issue by freddysmith1** [SiCKRAGETV/sickrage-issues#1354]
### INFO
Python Version: **2.7.9 (default, Mar 23 2015, 00:07:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@975c0dd208c59cac8fd8a77a91da5d1dfc7235df
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [SceneTime] :: Failed parsing SceneTime Traceback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/scenetime.py", line 198, in _doSearch
    seeders = int(cells[6].get_text())
IndexError: list index out of range

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@bjornhamra please check this. Can you fix it please?

**Comment by bjornhamra** [comment]
Unable to reproduce so far, but the error seems to indicate that the user is not presented with the same markup I am. Would love some more context, is that possible through the app bug reporting

Had a quick look at the markup, but it doesn't seem to have changed since the pull request.  Will generalizing the bs4 code a bit more to make it slightly more fault tolerant.

/B

**Comment by fernandog** [comment]
@freddysmith1 are you using proxy?

**Comment by freddysmith1** [comment]
No proxy

**Comment by fernandog** [comment]
@freddysmith1 can you check the logs and post the search string (show name + episode) before this error happend?

**Comment by fernandog** [comment]
@bjornhamra do you do any check if the return page is correct or if's empty or if is there some error?

**Comment by bjornhamra** [comment]
The only error checking is checking to see if div#torrenttable exists and the table inside it has more than one row. The error indicates that @freddysmith1's response contains a torrent table, but it somehow has less columns than usual, which I haven't been able to reproduce so far. Need logs/context from @freddysmith1. 

A quick work around would look something like this:

```
@@ -181,6 +181,9 @@

                         for result in torrent_rows[1:]:
                             cells = result.find_all('td')
+
+                            # Workaround for #1354 - ST returns awkward torrent tables
+                            if len(cells) > 8:
+                                    continue

                             link = cells[1].find('a');
```

.. but then again, I would very much like to know what is CAUSING it instead of just working around it.

**Comment by fernandog** [comment]
@freddysmith1 is there any option in the tracker that hides column or disable something ? - something like what we do in home and display show (widget column)

**Comment by freddysmith1** [comment]
@fernandog   where do i find the search string that you want?  in sickrage in the log section or in the log file itself in the sickrage folder?

**Comment by fernandog** [comment]
@freddysmith1 enable debug in general settings
then in viewlogs search for:  [SceneTime]

Post results in gist and post url here

**Comment by freddysmith1** [comment]
https://gist.github.com/freddysmith1/307b90326da83dd3045e

**Comment by fernandog** [comment]
@bjornhamra this is the url that created the error

https://www.scenetime.com/browse.php?search=Deadbeat.S02&c2=1&c43=13&c9=1&c63=1&c77=1&c79=1&c100=1&c101=1

**Comment by bjornhamra** [comment]
Does this happen on all your searches, or just some?

Open that browse URL in your browser, and then run the following in your javascript console:
   $("#torrenttable tr:nth-child(2) td").length

Does it return 8?

**Comment by freddysmith1** [comment]
@bjornhamra   just pasteing the $("#torrenttable tr:nth-child(2) td").length at the end of the url?   it doesnt seem to do anything?

**Comment by fernandog** [comment]
@freddysmith1 run in address bar:

javascript:window.alert($("#torrenttable tr:nth-child(2) td").length)

**Comment by bjornhamra** [comment]
...  ^ or that :)

**Comment by freddysmith1** [comment]
A spinning wheel thing comes up for a second and dissappears?

**Comment by fernandog** [comment]
@bjornhamra can you test the command above? did without testing =)

**Comment by bjornhamra** [comment]
Works as expected here.

@freddysmith1 make sure you're inside scenetime (Open the URL you provided), then in your address bar, remove the url and paste what @fernandog wrote. You should get a popup box with a number, hopefully.

**Comment by freddysmith1** [comment]
i get a 6?

**Comment by fernandog** [comment]
@freddysmith1 Send a full screen shot of that page

**Comment by freddysmith1** [comment]
![screen shot 2015-04-23 at 4 19 29 am](https://cloud.githubusercontent.com/assets/8336824/7282588/17c2a09a-e970-11e4-8607-f9a832364fd3.png)
![screen shot 2015-04-23 at 4 19 48 am](https://cloud.githubusercontent.com/assets/8336824/7282589/17c45c1e-e970-11e4-9eeb-86bfe675e0a9.png)

**Comment by bjornhamra** [comment]
Doh :D scroll down so we can see the actual torrent table!

**Comment by freddysmith1** [comment]
![screen shot 2015-04-23 at 4 27 42 am](https://cloud.githubusercontent.com/assets/8336824/7282744/2c1633a8-e971-11e4-8211-3d83bc881960.png)
![screen shot 2015-04-23 at 4 28 02 am](https://cloud.githubusercontent.com/assets/8336824/7282745/2c1c7d62-e971-11e4-8ce6-4978f31aa612.png)

**Comment by bjornhamra** [comment]
AHA! As I suspected. You're missing the 'Bookmark' and 'Download' columns for some reason (they should be between the "Name" and "Com." rows).

I will look into why this is happening and write a patch.

**Comment by fernandog** [comment]
@freddysmith1 @freddysmith1 isn't a setting in tracker to show/hide those columns?

**Comment by bjornhamra** [comment]
@fernandog @freddysmith1 please see pull request #1819: 

https://github.com/SiCKRAGETV/SickRage/pull/1819/commits

Hopefully this should fix it. Works for me, please test.

**Comment by fernandog** [comment]
@bjornhamra thanks!

**Comment by fernandog** [comment]
@freddysmith1 
please stop SR,
edit /SickRage/sickbeard/providers/scenetime.py
clean contents
paste this one
https://raw.githubusercontent.com/bjornhamra/SickRage/fix-scenetime-tables/sickbeard/providers/scenetime.py
save
restart SR
test

**Comment by freddysmith1** [comment]
testing now  will report back

**Comment by freddysmith1** [comment]
have tested it thru afew search cycles and no errors has come up so should be all good now

**Comment by kevinpawsey** [comment]
I am getting the same issue with SceneTime, but when I try and get the above script it is now showing "Not Found".

How soon is the commit going to be applied?  Would you like me to give it a test too?

**Comment by fernandog** [comment]
@freddysmith1 can you send the update file that you are using?

**Comment by freddysmith1** [comment]
give this one a try 
http://rg.to/file/e343a462d6418bab5ca92f81fc593196/scenetime.py.html

**Comment by kevinpawsey** [comment]
I am having problems downloading from that site... I keep getting "Error 404 session not found" after I go through the Captcha and everything, and then when I click to download the file it throws up the 404 error.
Sorry to be a nuisance.

**Comment by freddysmith1** [comment]
All good  what file server site do you usually  use?  Ill upload it onto that

**Comment by bjornhamra** [comment]
https://raw.githubusercontent.com/bjornhamra/SickRage/fix-scenetime-tableparsing/sickbeard/providers/scenetime.py

**Comment by kevinpawsey** [comment]
Thanks for your help Freddy... but I have just managed to open bjornhamra's link :)

Will let you know if the fix works for me too

**Comment by kevinpawsey** [comment]
Thank you for the fix... that seems to be working for me too :) :+1:
