### ISSUE TITLE
[Feature Request] Add per show rolling download option

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#1358]
Instead of having a global toogle for the rolling download feature make it per show 
Example :
For the show Bones which has nearly 200 epidodes i could like it so that i would only have 3-4 episodes for it but there are other shows which i would like to have the full collection ie Marvels Daredevil which  has  only ~10 episodes or other shows like Dommsday Preppers which has torrents with low seeders and take more than a day to download,or shows that i wanna have their full collection
//Matigonkas

**Comment by fernandog** [comment]
@matigonkas it' a major change in SR. won't do that soon.

**Comment by WebSpider** [comment]
@fernandog we could implement this by only allowing a limited number of episodes with 'snatched' state for a show

**Comment by miigotu** [comment]
Trakt rolling is going away soon. And I see this feature creating similar problems as that did.

**Comment by duramato** [comment]
@miigotu but something as @WebSpider  sugested would be doable? (ik it isnt the same as trakt rolling, but would work) as it would be independet of trakt and use the number of snatched episodes instead

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
