### ISSUE TITLE
[APP SUBMITTED]: local variable 'subtitles' referenced before assignment

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#1359]
### INFO
Python Version: **2.7.8 (default, Oct 20 2014, 15:05:29) [GCC 4.9.1]**
Operating System: **Linux-3.16.0-34-generic-i686-with-Ubuntu-14.10-utopic**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@2a0c39525e0baca0d7a491d9c78979cd2713a504
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: local variable 'subtitles' referenced before assignment
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by matigonkas** [comment]
error log https://gist.github.com/matigonkas/b0da5e23e63ec76f65a9

**Comment by TagForce** [comment]
@matigonkas @abeloin @fernandog Fixed it, waiting for it to be merged

**Comment by TagForce** [comment]
@fernandog It's a hotfix... So @abeloin or you should merge this in master, then develop...
The reason I hotfixed it is because it will now continue processing subtitles like one was downloaded, which isn't true, so stuff might mess up.

**Comment by fernandog** [comment]
@TagForce you can merge now too. check your email

**Comment by TagForce** [comment]
@fernandog Ok, this is scary... lol...
I'd rather not mess anything up :)
Maybe wait for @abeloin to do the hotfix while I sort my end out so I won't break anything.

**Comment by fernandog** [comment]
@abeloin won't have much time until 30th. and you are more experienced than me =)

**Comment by TagForce** [comment]
@fernandog lol, I'll see what I can do :)

**Comment by abeloin** [comment]
@TagForce Merge in master and develop
