### ISSUE TITLE
Seperate Plex Media Server and Plex Media Client in UI

### ISSUE THREAD

**Issue by bitzorro** [SiCKRAGETV/sickrage-issues#1364]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@975c0dd208c59cac8fd8a77a91da5d1dfc7235df
Link to Log: https://gist.github.com/5c270c4c93840bdc00fb
### ERROR
```
POSTPROCESSER :: PLEX: No host specified, check your settings
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@bitzorro what did you understand about the error message?

**Comment by bitzorro** [comment]
@fernandog 
looks like some thing is missing in the settings, but cant understand what? I have used the Notify plex for 6 months
and this error came with the last master update ! 
I did take a look in the settings and couldnt find anything missing.

Im only using it for notifying the server, no clients.

**Comment by fernandog** [comment]
@Thraxis can you help me with this? Don't use plex

**Comment by bitzorro** [comment]
When running test Plex media server it givs me :Successful test of Plex server(s) .

**Comment by fernandog** [comment]
@bitzorro send a full screen shot of your plex settings

**Comment by bitzorro** [comment]
![screenshot-192 168 0 191 8081 2015-04-22 15-10-30](https://cloud.githubusercontent.com/assets/10099360/7275085/21bf4918-e902-11e4-8d98-c07bbd3efd7b.png)

**Comment by fernandog** [comment]
@bitzorro why do you have "notify on download" enabled if "plex client ip port" is empty ?

**Comment by bitzorro** [comment]
@fernandog 
I noticed and removed it . 
If im not wrong that was a part of the server settings earlyer?

**Comment by fernandog** [comment]
@bitzorro don't know. don't use plex.

**Comment by TagForce** [comment]
@bitzorro Yes:
https://github.com/SiCKRAGETV/SickRage/pull/1764

**Comment by fernandog** [comment]
@TagForce do we have to remove anything from UI?

**Comment by TagForce** [comment]
@fernandog No, but it may be wise to seperate the PMS en PMC further by making them a seperate entity on the page.

**Comment by fernandog** [comment]
@Thraxis are you going to PR this until sunday? Otherwise I push to next milestone.
thanks!!

**Comment by CptChaos** [comment]
Another problem is that the Plex Auth tokens change quite fast. Maybe it's an idea for Plex Media Server, to require a username and password and make Sick Rage request tokens by itself through JSON or XML POST-calls to either https://plex.tv/users/sign_in.json or https://plex.tv/users/sign_in.xml respectively. More info on how to get tokens for Plex: https://forums.plex.tv/index.php/topic/129922-how-to-request-a-myplex-token-for-your-app/

**Comment by Thraxis** [comment]
The master branch has some bugs that were missed due to Plex only verifying the token if you are a Plex Pass member.  The fixes are in develop and should be available soon in master.   

@fernandog: I'll see if I can get this PR done tonight. Need to check if the Plex Media Clients need token / login as well

**Comment by Thraxis** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1849
