### ISSUE TITLE
[APP SUBMITTED]: 'int' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by levinzz** [SiCKRAGETV/sickrage-issues#1367]
### INFO
Python Version: **2.7.9 (default, Mar 22 2015, 23:23:28) [GCC 4.6.4]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@057e85a3e32a44cf4912d02662dd3de9f9679d5e
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-121361 :: Failed parsing T411 Traceback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/t411.py", line 186, in _doSearch
    torrent_name = torrent['name']
TypeError: 'int' object has no attribute '__getitem__'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@vanackej can you chack this please?

**Comment by vanackej** [comment]
I've made a quick code review, and made another test with my install at home, everything seems to be fine.

@levinzz Can you provide more details : Did it happen only once or does it always fail ? Maybe the t411 API was down or buggy when you had this error. If it happen again please provide the query string passed to t411, you can find it in debug logs.

**Comment by levinzz** [comment]
Well to be honest this didn't seem to cause any trouble. It was in the error list and I just pressed the "report" button. Since I restarted Sickrage a couple hours ago, it didn't happen again... t411 seems to be working just fine.
So I guess you can close the ticket and I'll ask to reopen if this ever happens again.

Thanks anyway

**Comment by fernandog** [comment]
@levinzz report if this happen again
