### ISSUE TITLE
Unable to postprocess (move) a specific episode

### ISSUE THREAD

**Issue by levinzz** [SiCKRAGETV/sickrage-issues#1370]
**INFO**

Python Version: 2.7.9 (default, Mar 22 2015, 23:23:28) [GCC 4.6.4]
Operating System: Linux-3.2.40-armv7l-with-glibc2.4
Locale: UTF-8
Branch: master
Commit: SiCKRAGETV/SickRage@057e85a

Postprocessing config:
```
TV Download Dir : /volume1/Downloads/Sickbeard
Process episode method : Move
Move associated files: checked
Sync file extensions: !sync,lftp-pget-status,part,bts
Postpone post processing: checked
Rename .nfo file: checked
Rename Episodes: checked
Scan and Process: checked
Auto Post-Processing Frequency : 720
Unpack: checked
Episode Naming Pattern: Custom    Saison %0S/%SN - S%0SE%0E - %EN
Metadata Type: KODI   (none checked)

(all the rest unchecked)
```

**ERROR**

```
2015-04-22 12:42:33 INFO     POSTPROCESSER :: [Daredevil.S01E13.VOSTFR.FASTSUB.720p.WEBRip.x264-SNEAkY : No processable items found in folder]
```
Whereas the folder contains the following files :
```
Daredevil.S01E13.720p.WEBRip.x264-SNEAkY.nfo
Daredevil.S01E13.VOSTFR.FASTSUB.720p.WEBRip.x264-SNEAkY.mkv
```

Other episodes from the same show and from other shows are correctly processed

Debug log : http://pastebin.com/C75u2Wc2

**Comment by TagForce** [comment]
@levinzz Post the debug logs from that PP pass (or another with the same issue).

No processable items found will be logged when the Dir is validated. One of the checks is if there's a video file, directory, or rarfile in it, and if the file/directory name can be parsed. If the parse fails for all of the present items it will log this error. 

So, either there's a problem with the showname (unlikely), or there's a problem with the entire filename. Either way, the log should show you what the problem is in the parse output.

**Comment by miigotu** [comment]
Check that the .avi is not actually a folder, containing a file of the same name but .avi.exe

I have seen this in my own logs and it was due to a fake torrent with an exe file

**Comment by levinzz** [comment]
I updated the issue with my debug log. 

I don't have VOSTFR in my exclude words list. The folder is valid and VLC has no problem reading the video file (.mkv)

As you can see in the debug log, 2 episodes from other shows were just processed without any issue.

Thank you

**Comment by TagForce** [comment]
@levinzz 
```
2015-04-20 14:26:31 DEBUG    POSTPROCESSER :: PostProcessing VideoFiles: []
2015-04-20 14:26:31 DEBUG    POSTPROCESSER :: PostProcessing Files: []
2015-04-20 14:26:31 DEBUG    POSTPROCESSER :: PostProcessing Dirs: ['Daredevil.S01E13.VOSTFR.FASTSUB.720p.WEBRip.x264-SNEAkY']
```
SR is not seeing the mkv inside the folder... Check permissions for the folder (can SR read the folder and file?), file properties (is the file hidden, does it have some weird attributes), and anything else that might cause SR to not see it.

Try to copy the file somewhere else manually, then delete the file from the folder, and copy it back (use copy, not move as move handles permissions differently and I want it to be a new file completely, not just the same file with a different Filetable record).

**Comment by levinzz** [comment]
Permissions for folder and files were empty (----------)

I tried copying to another folder and starting manual postprocess (force already processed files: checked). I also tried chmoding folder and files to 777. I also renamed both folder and files to shorter names (DaredevilS01E13)....all to no avail  :-(

**Comment by TagForce** [comment]
@levinzz Rename the file to Marvel's.Daredevil.S01E13.VOSTFR.FASTSUB.720p.WEBRip.x264-SNEAKy.mkv and try again...
Or add Marvel's Daredevil to your scene exceptions for that show.

**Comment by levinzz** [comment]
@TagForce Yup, renaming the file worked !

So the file needs to have the exact same name as the folder ? I'll let you guys decide if it's it an issue or a feature ;-)

Thanks a lot anyway !

```
Processing folder /volume1/Downloads/Sickbeard
TV_DOWNLOAD_DIR: /volume1/Downloads/Sickbeard
PostProcessing Path: /volume1/Downloads/Sickbeard
PostProcessing Dirs: ['DaredevilS01E13', 'Daredevil.S01E13.VOSTFR.FASTSUB.720p.WEBRip.x264-SNEAkY']
PostProcessing Files: []
PostProcessing VideoFiles: []
PostProcessing RarContent: []
PostProcessing VideoInRar: []
Processing folder DaredevilS01E13
Processing folder Daredevil.S01E13.VOSTFR.FASTSUB.720p.WEBRip.x264-SNEAkY
Processing folder /volume1/Downloads/Sickbeard/Daredevil.S01E13.VOSTFR.FASTSUB.720p.WEBRip.x264-SNEAkY
Found unwanted files: ['Daredevil.S01E13.720p.WEBRip.x264-SNEAkY.nfo']
Processing /volume1/Downloads/Sickbeard/Daredevil.S01E13.VOSTFR.FASTSUB.720p.WEBRip.x264-SNEAkY/Marvel's.Daredevil.S01E13.VOSTFR.FASTSUB.720p.WEBRip.x264-SNEAKy.mkv.mkv (None)
Retrieving episode object for 1x13
Snatch history had a quality in it, using that: 720p WEB-DL
SB snatched this episode and it is not processed before
Is ep a priority download: True
There is no existing file so there's no worries about replacing it
This download is marked a priority download so I'm going to replace an existing file if I find one
Found release name Marvel's.Daredevil.S01E13.VOSTFR.FASTSUB.720p.WEBRip.x264-SNEAKy
Destination folder for this episode: /volume1/Videos/Series/Marvel's Daredevil/Saison 01
No associated files were during this pass
Moving file from /volume1/Downloads/Sickbeard/Daredevil.S01E13.VOSTFR.FASTSUB.720p.WEBRip.x264-SNEAkY/Marvel's.Daredevil.S01E13.VOSTFR.FASTSUB.720p.WEBRip.x264-SNEAKy.mkv.mkv to /volume1/Videos/Series/Marvel's Daredevil/Saison 01/Marvel's Daredevil - S01E13 - Daredevil.mkv
Processing succeeded for /volume1/Downloads/Sickbeard/Daredevil.S01E13.VOSTFR.FASTSUB.720p.WEBRip.x264-SNEAkY/Marvel's.Daredevil.S01E13.VOSTFR.FASTSUB.720p.WEBRip.x264-SNEAKy.mkv.mkv
Deleting file Daredevil.S01E13.720p.WEBRip.x264-SNEAkY.nfo
Deleted folder: /volume1/Downloads/Sickbeard/Daredevil.S01E13.VOSTFR.FASTSUB.720p.WEBRip.x264-SNEAkY
Successfully processed
```

**Comment by TagForce** [comment]
@levinzz no, but the showname must be recognized as in in your list. SR names the show Marvel's Daredevil, so the file should be named like that, OR a scene exception needs to be added to the show in SR to tell it that Daredevil is really the show Marvel's Daredevil.
