### ISSUE TITLE
[APP SUBMITTED]: Unrar: Generic Error

### ISSUE THREAD

**Issue by noze2000** [SiCKRAGETV/sickrage-issues#1371]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@975c0dd208c59cac8fd8a77a91da5d1dfc7235df
Link to Log: https://gist.github.com/9d2eead94bbe6f2deb9f
### ERROR
```
Thread-46 :: Failed Unrar archive the.baconing.309.720p-dimension.rar: Unrar: Generic Error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@noze2000 check if rar is valid or is corrupt
