### ISSUE TITLE
[APP SUBMITTED]: POSTPROCESSER :: Automatic post-processing attempted but dir /mnt/Downloads/Complete/tv doesn't exist

### ISSUE THREAD

**Issue by TimothyVandenbrande** [SiCKRAGETV/sickrage-issues#1378]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-48-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@975c0dd208c59cac8fd8a77a91da5d1dfc7235df
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Automatic post-processing attempted but dir /mnt/Downloads/Complete/tv doesn't exist
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@TimothyVandenbrande you hdd is not mouted.
