### ISSUE TITLE
[APP SUBMITTED]: SHOWQUEUE-REFRESH :: There was an error trying to retrieve the image, aborting

### ISSUE THREAD

**Issue by larstomas** [SiCKRAGETV/sickrage-issues#1380]
### INFO
Python Version: **2.7.9 (default, Mar 23 2015, 00:07:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@975c0dd208c59cac8fd8a77a91da5d1dfc7235df
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-REFRESH :: There was an error trying to retrieve the image, aborting
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1189
