### ISSUE TITLE
[APP SUBMITTED]: Thread-97 :: You tried saving an invalid sports naming config, not saving your sports settings

### ISSUE THREAD

**Issue by broyuken** [SiCKRAGETV/sickrage-issues#1384]
I'm trying to set up my UFC PPV fights in Plex (using custom sports naming) but it appears that the air date is required. The issue with this is that plex doesn't match because of the date on the end. If I try to remove the date, sickrage gives the error below.

I currently have the naming convention as %EN - %AD but I would like it to just be %EN

### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-49-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@c1c519b720acfbbc5cec7c5a89c48053e9f1b980
Link to Log: https://gist.github.com/923e6070fbbe44e022b1
### ERROR
```
Thread-97 :: You tried saving an invalid sports naming config, not saving your sports settings
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by broyuken** [comment]
I was able to get it to recognize it by doing the following naming convention. My issue is resolved, but I am leaving this open because I believe this limitation should not exist.

%EN (%Y) %AD

**Comment by fernandog** [comment]
@broyuken which limitation?
