### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-DAILY-SEARCH :: No NZB/Torrent providers found or enabled in the sickrage config for daily searches. Please check your settings.

### ISSUE THREAD

**Issue by miigotu** [SiCKRAGETV/sickrage-issues#1394]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-49-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **build_tests**
Commit: SiCKRAGETV/SickRage@5754e31bc93933717a244773578651ddfd73ab07
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: No NZB/Torrent providers found or enabled in the sickrage config for daily searches. Please check your settings.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@miigotu see as we dont have logs. regex didnt matched

**Comment by miigotu** [comment]
@fernandog because I deleted that error from my sickrage.log trying to make it force the FAKE EXCEPTION, but it was still in `classes.ErrorViewer.errors`

**Comment by fernandog** [comment]
@miigotu can you try to reproduce this one with empty title?
