### ISSUE TITLE
SickRage ignores SD bluray rips when tagged as "bluray" rather than "bdrip"

### ISSUE THREAD

**Issue by gangrenejellybean** [SiCKRAGETV/sickrage-issues#1401]
It is an internal policy on BTN to tag SD bluray rips as "bluray" rather than "bdrip". From what I can tell, this is why SR is falling back to other providers for these releases, but I really want it to be able to get these from BTN when they're there.

Looking in sickbeard/common.py, I think my issues could be solved by simply adding "bluray" into the regex used here:

    elif checkName(["(dvdrip|b[r|d]rip)(.ws)?.(xvid|divx|x264)"], any) and not checkName(["(720|1080)[pi]"], all):
        return Quality.SDDVD

A similar modification might need to be done to the anime section above, but I don't do anime so am not sure of naming conventions for that.

Thanks for your time.

**Comment by neoatomic** [comment]
@gangrenejellybean If we add "bluray" wouldn't that mean that users who only want (real) "bluray" get SD bluray rips.? If that is the case we cant preform that change...

@TagForce Am i correct here with my assumption.?

**Comment by TagForce** [comment]
@neoatomic Hmmm... I think we should be good...
The ```(dvdrip|b[r|d]rip)(.ws)?.(xvid|divx|x264)``` check also includes a check if there's not ```(720|1080)[pi]``` in the filename.
The true HD Bluray rips requires 720p or 1080p in the filename like this:
```
checkName(["720p", "bluray|hddvd|b[r|d]rip", "x264"], all)
checkName(["1080p", "bluray|hddvd|b[r|d]rip", "x264"], all)
```
(I think this should be changed to 720[pi] and 1080[pi] respectively, but that's besides the point).

So I *think* we can add the bluray to the first regex to include it in the SDDVD quality match.

**Comment by fernandog** [comment]
me neither....

@miigotu can you help with this please?

**Comment by miigotu** [comment]
One sec, I'll change those two and pr.

**Comment by gangrenejellybean** [comment]
This should accomplish what you/I want:

    elif checkName(["(dvdrip|b[rd]rip|blu-?ray)(.ws)?.(xvid|divx|x264)"], any) and not checkName(["(720|1080)[pi]"], all):
        return Quality.SDDVD

I've removed an extraneous | from the regex, too.

**Comment by miigotu** [comment]
Already ahead of you @gangrenejellybean

**Comment by miigotu** [comment]
@TagForce I dont think we should change the other ones unless we get reports of names incorrectly parsed as unknown quality, or incorrectly parsed as something different. Looks can be deceiving.

**Comment by fernandog** [comment]
@gangrenejellybean merged in develop. please test and report back

**Comment by gangrenejellybean** [comment]
Posted a comment on the thread for the pull-request as I think there may be an issue with that patch.

I've manually patched locally and will report back my results. Might be a few hours, it's late here and bed is calling.

**Comment by miigotu** [comment]
@fernandog @gangrenejellybean SiCKRAGETV/SickRage/pull/1831

**Comment by gangrenejellybean** [comment]
Thanks for the new fix. Tested and it seems to do the job. Will report back again if there's any issues. Ditto for the api call warning patch for btn.py (with the later == fix)
