### ISSUE TITLE
[APP SUBMITTED]: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

### ISSUE THREAD

**Issue by Vastlee** [SiCKRAGETV/sickrage-issues#1403]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@975c0dd208c59cac8fd8a77a91da5d1dfc7235df
No Log available with ERRORS: 
### ERROR
```
FINDPROPERS :: [TorrentDay] :: Error while searching TorrentDay, skipping: error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@Vastlee 

 please try run in CMD:

Install Pip if you don't have it
https://www.youtube.com/watch?v=zPMr0lEMqpo

pip install --upgrade setuptools
pip install pyopenssl --upgrade

**Comment by laryan61** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/e583a1022358ce1b62b4
### ERROR
```
SEARCHQUEUE-RETRY-80379 :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Originalpug** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/897e16671c5e98a70bfc
### ERROR
```
SEARCHQUEUE-BACKLOG-271910 :: [TorrentDay] :: Error while searching TorrentDay, skipping: error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by papampi** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-51-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/faf90cbc0122550a7ab8
### ERROR
```
SEARCHQUEUE-BACKLOG-78988 :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by NilsNojje** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-34-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/75e6a7dce6c9a1186cac
### ERROR
```
FINDPROPERS :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by DeFropi** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-34-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-MANUAL-95441 :: [TorrentDay] :: Error while searching TorrentDay, skipping: error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by DeFropi** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-34-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-72108 :: [TorrentDay] :: Error while searching TorrentDay, skipping: error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
please test develop branch. If no 'develop' appears in the list of branches, please enter github user and pass in SR settings

**Comment by Originalpug** [comment]
Hi

Fixed this by updating python to 2.9 or something

**Comment by drohreo** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-49-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/f571ef7b276cf3d69148
### ERROR
```
SEARCHQUEUE-MANUAL-263365 :: [TorrentDay] :: Error while searching TorrentDay, skipping: error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by NilsNojje** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-34-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@d13424989ca89262adc93debbae90eda7e3fd34b
Link to Log: https://gist.github.com/90f61b45cecd78cdc3e8
### ERROR
```
SEARCHQUEUE-BACKLOG-263365 :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by LouisF410** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/01506b2fa0a61fe5b319
### ERROR
```
SEARCHQUEUE-BACKLOG-10461 :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by LouisF410** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-10461 :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
If anyone wants to help debug this, please see this: https://github.com/SiCKRAGETV/sickrage-issues/issues/1231#issuecomment-97677808

**Comment by mike19715** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/71be20b4475331a3d1f8
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by NilsNojje** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-34-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@9ce76e88cce835bfa8f307a73849862f9ac39651
Link to Log: https://gist.github.com/2f4ec6625cd43294306f
### ERROR
```
SEARCHQUEUE-BACKLOG-274431 :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by supersonek** [comment]
I'm getting the same error on the development branch.

**Comment by miigotu** [comment]
See [SSL Errors](https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors) for help.

**Comment by Prawna** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/a09a8c90b10e241a5264
### ERROR
```
SEARCHQUEUE-BACKLOG-274869 :: [TorrentDay] :: Error while searching TorrentDay, skipping: error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by firatuzman** [comment]
Finally got it working
Python version 2.7.6 (did not upgrade to 2.7.9)
Entering commands inside sickrage directory did the trick. Some of the installs I did while debugging may be unnecessary, but instructions from @xiolo finally got it working. No errors now
Read more in https://github.com/SiCKRAGETV/sickrage-issues/issues/1231

**Comment by supersonek** [comment]
Working like a charm now! thanks!

**Comment by surtin** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-51-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/da0182c6a535673785ae
### ERROR
```
SEARCHQUEUE-BACKLOG-247909 :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
See [THIS](https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors) for a solution to the ssl errors.

**Comment by larryd85** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@11796ea71472f509ff87d411f8b0cf74354fc72c
Link to Log: https://gist.github.com/383f11b13a39f0ee0a02
### ERROR
```
SEARCHQUEUE-BACKLOG-94571 :: [TorrentDay] :: Unable to connect to TorrentDay provider: error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
