### ISSUE TITLE
Fail to find/snatch some TV-Show torrent, when they exist (checked manually)

### ISSUE THREAD

**Issue by TheSquad** [SiCKRAGETV/sickrage-issues#1405]
- Branch : master
- Commit hash : c1c519b720acfbbc5cec7c5a89c48053e9f1b980
- Linux Debian x86_64
- Python 2.7.5+

I have set the quality to any, and checked manually on the Torrent provider, there is both HDTV 720p and SD releases.

Here the log about the search :
https://gist.github.com/TheSquad/8413eb45bd15ff4df271
https://gist.github.com/TheSquad/b317ed3ce274ff3513fe (Debug With Filter: "Royals")

And here's torrentLeech result for a manual search : "The Royals S01E01"

The Royals S01E01 720p HDTV X264-DIMENSION
The Royals S01E01 HDTV x264-LOL

Normally it should fit... since in the scene exception I have added : "The Royals" and the quality wanted is set to "any"
Plus TorrentLeech is not the only provider where I checked, they all have it... T411, piratebay, etc...

I don't know why this does not work, while other shows works perfectly...

**Comment by fernandog** [comment]
follow guidelines:
https://github.com/SiCKRAGETV/sickrage-issues/

**Comment by TheSquad** [comment]
Sorry I wasn't aware of the guideline

**Comment by TheSquad** [comment]
I have updated my first post, to fit the guidelines... thank you for noticing it @fernandog

**Comment by fernandog** [comment]
@TheSquad FULL logs please

**Comment by TheSquad** [comment]
@fernandog, sure ok, was just trying to help-out with "only" relevant things... I changed the gist url

**Comment by fernandog** [comment]
@TheSquad you are getting "timed out" accessing the tracker

**Comment by fernandog** [comment]
@TheSquad also your log don't show anything about Royal. Use searchLog feature and search for Royal, post result log in gist

**Comment by TheSquad** [comment]
@fernandog can you point me where I can find the searchLog feature please ?

**Comment by TheSquad** [comment]
@fernandog : The timeout issue is from today only (TorrentLeech is unreachable today for some reason), it has been 3 days since the issue occured (when TorrentLeech was reachable, no error logs about it, plus all the other show where snatched from it)

**Comment by fernandog** [comment]
@TheSquad go to view logs page in SR. There is a input field

**Comment by TheSquad** [comment]
@fernandog oh, I though you were talking about a feature that would write some verbose into the Log... I'm coming back to you when TorrentLeech is up and running.... Thank you for your help !

**Comment by TheSquad** [comment]
@fernandog I have pasted the log with filter : "The Royals"

**Comment by fernandog** [comment]
@TheSquad please filter again but select DEBUG in log level. If you don't have, please enable DEBUG in general settings

**Comment by TheSquad** [comment]
@fernandog done and updated, again thank you for the help !

**Comment by miigotu** [comment]
@TheSquad could you try switching to develop branch and seeing if you have the same problem?
Either that or wait until after the develop merges into master on sunday, and then update and try again.
I need to know that you have this issue with current code to begin troubleshooting it.

**Comment by TheSquad** [comment]
@miigotu switching to develop branch has fixed the issue, thank you !

**Comment by miigotu** [comment]
@TheSquad glad this past weeks work is paying off! You could switch back to master on sunday night/monday morning, as develop gets merged into master sunday. Then you don't get caught on any of the bugs that new code may create during the development week.
