### ISSUE TITLE
[APP SUBMITTED]: ('http error', 401, 'Unauthorized', <httplib.HTTPMessage instance at 0x513fcf8>)

### ISSUE THREAD

**Issue by sdgarland35** [SiCKRAGETV/sickrage-issues#1406]
### INFO
Python Version: **2.7.5+ (default, Feb 27 2014, 19:37:08) [GCC 4.8.1]**
Operating System: **Linux-3.11.0-12-generic-x86_64-with-LinuxMint-16-petra**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@c1c519b720acfbbc5cec7c5a89c48053e9f1b980
Link to Log: https://gist.github.com/0c96f4b0115ad818f352
### ERROR
```
Thread-34 :: PLEX: Error while trying to contact Plex Media Server: http error : error 401 : Unauthorized : error Content-Length: 91
Content-Type: text/html
X-Plex-Protocol: 1.0
Cache-Control: no-cache

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@sdgarland35 check your PLEX settings

**Comment by fernandog** [comment]
@Thraxis can we change 401 errors and other similar to WARNING instead or ERROR? So user don't open issues

**Comment by ripper1967** [comment]
had the same warning had to look for the new plex token ,replace it in sickrage reenter my password then it was fine

**Comment by sdgarland35** [comment]
I have checked the token and it matches what is configured in sickrage....I have gone over the Plex settings in sickrage and everything appears correct and the test plex server succeeds.
Not sure where else to look.

**Comment by Thraxis** [comment]
There is a fix for this issue in develop, it will be merged into master.

**Comment by fernandog** [comment]
@Thraxis 401 errors dont show as errors?

**Comment by Thraxis** [comment]
@fernandog The token not working issue, I'll do a PR to change the 401's to warnings

**Comment by fernandog** [comment]
@Thraxis is there another URL code error that we can suppress (error > warning) ?

**Comment by Thraxis** [comment]
These are the three logger.ERROR's in the plex notifier.  They can should probably all be set to logger.WARNING

https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/notifiers/plex.py#L60
https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/notifiers/plex.py#L227
https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/notifiers/plex.py#L263

**Comment by Thraxis** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1837
