### ISSUE TITLE
Change "Recommended Shows" to look like "Trending Shows"

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#1409]
Show posters instead of a simple list of shows.

**Comment by Thraxis** [comment]
Yeah.. that ones a bit of an annoyance that has been bothering me

**Comment by Thraxis** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1839

**Comment by fernandog** [comment]
Thanks!
