### ISSUE TITLE
Some network images need a name change.

### ISSUE THREAD

**Issue by 215** [SiCKRAGETV/sickrage-issues#1411]
completely non-pressing, but the tvdb has changed a few network names breaking some images in the gui. two that I know of are FOX and ABC, which are now FOX (US) and ABC (US). making copies of the images and appending (us) i.e. fox (us).png fixed the issue here, so they should be added to the repo.

**Comment by Thraxis** [comment]
ABC and Fox logo updates are already merged into develop.  I just submitted for Showcase (ca) and mtv (us)
