### ISSUE TITLE
[APP SUBMITTED]: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

### ISSUE THREAD

**Issue by LouisF410** [SiCKRAGETV/sickrage-issues#1412]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c1c519b720acfbbc5cec7c5a89c48053e9f1b980
Link to Log: https://gist.github.com/4ca9e5298f9f8ba6bb13
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@LouisF410 

 please try run in CMD:

Install Pip if you don't have it
https://www.youtube.com/watch?v=zPMr0lEMqpo

pip install --upgrade setuptools
pip install pyopenssl --upgrade

**Comment by LouisF410** [comment]
Installed pip.

Ran the commands and still have a issue with the provider.
