### ISSUE TITLE
Removed show reappears

### ISSUE THREAD

**Issue by matansh** [SiCKRAGETV/sickrage-issues#1413]
I'm running sickrage and everything works fine but one particular show just won't go away.
When i remove other shows they happily go away and don't come back.. 

At first i thought trakt was re-adding it, so i removed it from trakt and the next day it sneaked back to sickrage.. so im pretty clueless 

I've looked through the forums and issue tracker but did not find any thing talking about this kind of problem

**Comment by fernandog** [comment]
@matansh disable trakt and try again. Also follow guidelines

https://github.com/SiCKRAGETV/sickrage-issues
