### ISSUE TITLE
[APP SUBMITTED]: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

### ISSUE THREAD

**Issue by pct00** [SiCKRAGETV/sickrage-issues#1414]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@3b922e70dc4555cee8fcf76ba1901c7e073b4bf1
Link to Log: https://gist.github.com/a20747a0093f28f6a703
### ERROR
```
SEARCHQUEUE-BACKLOG-75930 :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@pct00 please try run in CMD:

Install Pip if you don't have it
https://www.youtube.com/watch?v=zPMr0lEMqpo

pip install --upgrade setuptools
pip install pyopenssl --upgrade

**Comment by fernandog** [comment]
@pct00 before you run that can you run?
´
python
>> import pkg_resources
>> pkg_resources.get_distribution("urllib3").version

post result here
