### ISSUE TITLE
[APP SUBMITTED]: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

### ISSUE THREAD

**Issue by pct00** [SiCKRAGETV/sickrage-issues#1415]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@3b922e70dc4555cee8fcf76ba1901c7e073b4bf1
Link to Log: https://gist.github.com/2aab381042fb4ddcb1b9
### ERROR
```
SEARCHQUEUE-BACKLOG-73255 :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@pct00 dont submit this again please.
