### ISSUE TITLE
[Feature Request] Check URLLIB3/pyopenssl version on update and warn user

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#1416]
to avoid SSL errors

My Linux:
>>> import pkg_resources
>>> pkg_resources.get_distribution("urllib3").version
'1.9.1'

My Windows:
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkg_resources
>>> pkg_resources.get_distribution("urllib3").version
'1.10.3'
>>>

**Comment by fernandog** [comment]
@miigotu good FR? otherwise will close

**Comment by miigotu** [comment]
Already do this, just not with pkg_resources
