### ISSUE TITLE
[Feature Request] Preview names of undownloaded episodes

### ISSUE THREAD

**Issue by tdev5** [SiCKRAGETV/sickrage-issues#1417]
Like the "Preview Rename" page, I'd like to be able to preview the names of shows I haven't downloaded / don't have yet. This would be especially useful for specials, as people name them all kinds of different ways, and it can be hard to match what I already have to the names sickrage expects.

Understandably, this may exclude certain categories (like quality) from the preview.

ETA:
BRANCH: (master)
COMMIT: (975c0dd208c59cac8fd8a77a91da5d1dfc7235df)

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
