### ISSUE TITLE
Feature request: show both downloaded and snatched status

### ISSUE THREAD

**Issue by tdev5** [SiCKRAGETV/sickrage-issues#1418]
Currently, when an episode has been downloaded, and a higher quality is snatched, only the snatched status shows on the show page, you don't see that you already have one. I'd rather see both.

The current method of showing only snatched (when true) is a real bummer when the download fails.

I see that currently there's one color per row. There would be many ways to display this info. Here's a suggestion:

- Separate columns for the two statuses.
- Generally still one color per row, except
- If (downloaded and snatched), use the quality color for the row, except use the snatched color in the snatched column in that row.

ETA:
BRANCH: (master)
COMMIT: (975c0dd208c59cac8fd8a77a91da5d1dfc7235df)

**Comment by selthius** [comment]
There is already a issue for this, which I submitted several weeks ago. #674
