### ISSUE TITLE
Feature request: add "collapse" buttons to episode overview

### ISSUE THREAD

**Issue by tdev5** [SiCKRAGETV/sickrage-issues#1419]
Manage menu --> Episode Status Management submenu; click Manage button

This takes you to a page with one row per show, and an "Expand" button in each row. Currently, when you click it, the show expands (duh), and the button disappears.

Instead of having the button disappear, it would be helpful if it was replaced with a "Collapse" button.

ETA:
BRANCH: (master)
COMMIT: (975c0dd208c59cac8fd8a77a91da5d1dfc7235df)

**Comment by fernandog** [comment]
@Thraxis can you check this? seems easy to fix.

**Comment by Thraxis** [comment]
I'll take a look, it should be pretty easy.

**Comment by Thraxis** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1851
