### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-MANUAL-79214 :: Unable to parse [subs4u].Mushishi.S2.16.(x264.720p.Ger into a scene name. If it's a valid one log a bug.

### ISSUE THREAD

**Issue by jdfalk** [SiCKRAGETV/sickrage-issues#1422]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@c1c519b720acfbbc5cec7c5a89c48053e9f1b980
Link to Log: https://gist.github.com/8311dd9df81c7e3b8dd1
### ERROR
```
SEARCHQUEUE-MANUAL-79214 :: Unable to parse [subs4u].Mushishi.S2.16.(x264.720p.Ger into a scene name. If it's a valid one log a bug.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Bad naming file
