### ISSUE TITLE
Windows Locale issues

### ISSUE THREAD

**Issue by kotysoft** [SiCKRAGETV/sickrage-issues#1425]
Previously I posted some comments in other threads scattered, but now I collected anything into 1 new issue, and researched what i could:

## Sickrage and running Environment
**OS:** Windows 7 Ultimate x64 Hungarian SP1
**SR Branch:** master
**SR commit:** c1c519b720acfbbc5cec7c5a89c48053e9f1b980
**SR user:** KOTY *-windows main administrator account*
**SR locale:** 'hu_HU', 'cp1250'
**Python version:** 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]

**Windows default command line code page:** 852
**Common special characters in my language:** ÁÉÍÓÖŐÚÜŰ áéíóöőúüű
**Browser using:** Google Chrome - Automatic char encoding: UTF-8

## Issue Scenario 1 
- **codepage untouched in cmd.exe (852)** when starting SickRage
- All characters displays and handled wrong:
  - *A cĂ©lszemĂ©ly*
  - instead of *A célszemély* 
- So writing wrong characters when creating new folders and unable to import existing TV shows containing hungarian characters
- Unable to search on TVDB (set search language correctly to Magyar - Hungarian)
  - No results found

**SR locale:** 'hu_HU', 'cp1250'

## Issue Scenario 2 
- **codepage changed to 65001 in cmd.exe (UTF-8?)** when starting SickRage, using `chcp 65001`
- All characters displaying and handling well:
  - *A célszemély*
  - Metadata and titles handling well
- Still unable to search on TVDB (set search language correctly to Magyar - Hungarian)
  - No results found
- SEARCH for **A célszemély** but stuck at **é**
**This error message only in command line**

````
13:20:47 INFO::SEARCHQUEUE-MANUAL-248742 :: Unable to find a download for: [A cĂTraceback (most recent call last):
  File "C:\Python27\lib\logging\__init__.py", line 870, in emit
    stream.write(ufs % msg)
IOError: [Errno 0] Error
Logged from file logger.py, line 142`
````
- Unable to browse directories containing special character:
````
2015-04-26 13:30:24 Thread-26 :: Failed doing webui callback: Traceback (most recent call last):
  File "c:\sickrage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "c:\sickrage\sickbeard\webserve.py", line 658, in index
    return json.dumps(foldersAtPath(path, True, bool(int(includeFiles))))
  File "c:\sickrage\sickbeard\browser.py", line 99, in foldersAtPath
    lambda x, y: cmp(os.path.basename(x['name']).lower(), os.path.basename(y['path']).lower()))
  File "c:\sickrage\sickbeard\browser.py", line 99, in <lambda>
    lambda x, y: cmp(os.path.basename(x['name']).lower(), os.path.basename(y['path']).lower()))
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf3 in position 3: unexpected end of data
````

- Unable to go to GENERAL SETTINGS:
````
2015-04-26 13:30:51 Thread-48 :: Failed doing webui callback: Traceback (most recent call last):
  File "c:\sickrage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "c:\sickrage\sickbeard\webserve.py", line 3670, in index
    return t.respond()
  File "c:\sickrage\cache\cheetah\_sickrage_gui_slick_interfaces_default_config_general_tmpl.py", line 642, in respond
    if _v is not None: write(_filter(_v, rawExpr=u'$datetime.datetime($datetime.datetime.now().year, 12, 31, 14, 30, 47).strftime($cur_preset)')) # from line 341, col 191.
  File "c:\sickrage\sickbeard\webserve.py", line 95, in filter
    logger.log(u'Unable to decode using {0}, trying utf-8. Error is: {1}'.format(sickbeard.SYS_ENCODING, ex(e)),logger.DEBUG)
  File "c:\sickrage\sickbeard\exceptions.py", line 49, in ex
    e_message = e_message + " : " + fixed_arg
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 9: invalid start byte
````

[FULL SR debug log from start to shutdown](http://pastebin.com/iUDqSkkp)

**SR locale:** 'hu_HU', 'cp1250'

## Issue Scenario 3
- **codepage changed to 1250 in cmd.exe** when starting SickRage, using `chcp 1250`
- **Same behaviour like at codepage 852**

## Currently
- Currently I'm trying to use 65001 because at least it can handles acutes in file names and metadata
- Renamed all of my folders to english names
- Hoping in english release names instead of hungarian names

**What should I do to can use SickRage on Windows just like I could on my old Synology device?**

Thanks in andvance
and thanks for your time

**Comment by fernandog** [comment]
copies from the other issue:

@abeloin if we remove the "continue" here and add a raise we get this:

https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/webserve.py#L2262

```
2015-04-24 14:59:44 DEBUG    TORNADO :: Failed doing webui request "searchIndexersForShowName": Traceback (most recent call last):
AAUnicodeDecodeError: 'utf8' codec can't decode bytes in position 1-2: invalid continuation byte
AA    return codecs.utf_8_decode(input, errors, True)
AA  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
AA    series = series.encode("utf-8")
AA  File "C:\Users\user\Documents\GitHub\SickRage\lib\tvdb_api\tvdb_api.py", line 679, in search
AA    allSeries = self.search(series)
AA  File "C:\Users\user\Documents\GitHub\SickRage\lib\tvdb_api\tvdb_api.py", line 691, in _getSeries
AA    selected_series = self._getSeries(key)
AA  File "C:\Users\user\Documents\GitHub\SickRage\lib\tvdb_api\tvdb_api.py", line 949, in __getitem__
AA    results.setdefault(indexer, []).extend(t[search_term])
AA  File "C:\Users\user\Documents\GitHub\SickRage\sickbeard\webserve.py", line 2259, in searchIndexersForShowName
AA    result = function(**kwargs)
AA  File "C:\Users\user\Documents\GitHub\SickRage\sickbeard\webserve.py", line 258, in async_call
AATraceback (most recent call last):
AAUnicodeDecodeError: 'utf8' codec can't decode bytes in position 1-2: invalid continuation byte
AA    return codecs.utf_8_decode(input, errors, True)
AA  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
AA    series = series.encode("utf-8")
AA  File "C:\Users\user\Documents\GitHub\SickRage\lib\tvdb_api\tvdb_api.py", line 679, in search
AA    allSeries = self.search(series)
AA  File "C:\Users\user\Documents\GitHub\SickRage\lib\tvdb_api\tvdb_api.py", line 691, in _getSeries
AA    selected_series = self._getSeries(key)
AA  File "C:\Users\user\Documents\GitHub\SickRage\lib\tvdb_api\tvdb_api.py", line 949, in __getitem__
AA    results.setdefault(indexer, []).extend(t[search_term])
AA  File "C:\Users\user\Documents\GitHub\SickRage\sickbeard\webserve.py", line 2259, in searchIndexersForShowName
AA    result = function(**kwargs)
AA  File "C:\Users\user\Documents\GitHub\SickRage\sickbeard\webserve.py", line 258, in async_call
```

**Comment by kotysoft** [comment]
Changed to
**Windows 2008 R2 x64 HUN
Python 2.7.10 x64**
problem still exist.

Can I help anything to solve it?

**Comment by fernandog** [comment]
Possible fix in develop

**Comment by miigotu** [comment]
@fernandog I merged to master already.

**Comment by kotysoft** [comment]
## SYSTEM
Windows 2008 R2 Server HUN
SR User: "Rendszergazda" (administrator)
Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
BRANCH: (master) / COMMIT: (a4f329fbc394e8939977bf9c43aa540f948fec75) 
Starting in command line, directly after `chcp 65001`

## Changes experienced
* Finally entering GENERAL SETTINGS not causing error and can enter into it :white_check_mark: 
* COMING EPISODES still not working :x: 
```
2015-07-09 19:06:37 Thread-102 :: Failed doing webui callback: Traceback (most recent call last):
  File "c:\SickRage\sickbeard\webserve.py", line 269, in async_call
    result = function(**kwargs)
  File "c:\SickRage\sickbeard\webserve.py", line 559, in comingEpisodes
    return t.respond()
  File "c:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_comingEpisodes_tmpl.py", line 732, in respond
    _v = VFN(VFN(VFN(VFN(VFSL([locals()]+SL+[globals(), builtin],"datetime.date",True),"fromordinal",False)(VFSL([locals()]+SL+[globals(), builtin],"cur_ep_airdate.toordinal",True)),"strftime",False)('%A'),"decode",False)(VFSL([locals()]+SL+[globals(), builtin],"sickbeard.SYS_ENCODING",True)),"capitalize",False)() # u"$datetime.date.fromordinal($cur_ep_airdate.toordinal).strftime('%A').decode($sickbeard.SYS_ENCODING).capitalize()" on line 364, col 29
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe1 in position 3: invalid continuation byte
```
* When browsing folders, finally a special character using foldername not freeze whole process, but that folder not showing up in the list. :wavy_dash:
* Still not find series on TVDB with special characters in the name :x:

**Comment by fernandog** [comment]
@kotysoft still an issue after all this updates?

**Comment by kotysoft** [comment]
## SYSTEM
Windows 2008 R2 Server HUN
SR User: "Rendszergazda" (administrator)
Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
BRANCH: (master) / COMMIT: (1ec701e4c12b41d1a34f01ad6091b1fec09967a3) 
Starting in command line, directly after `chcp 65001`

Maybe this helps to investigate: [my full sickrage folder .ZIP 100MB](http://amalon.hu/koty/sickrage.zip)


## Changes experienced
* COMING EPISODES still not working :x: 
```
2015-07-28 18:49:42 Thread-67 :: Failed doing webui callback: Traceback (most recent call last):
  File "c:\SickRage\sickbeard\webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "c:\SickRage\sickbeard\webserve.py", line 585, in comingEpisodes
    return t.respond()
  File "c:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_comingEpisodes_tmpl.py", line 732, in respond
    _v = VFN(VFN(VFN(VFN(VFSL([locals()]+SL+[globals(), builtin],"datetime.date",True),"fromordinal",False)(VFSL([locals()]+SL+[globals(), builtin],"cur_ep_airdate.toordinal",True)),"strftime",False)('%A'),"decode",False)(VFSL([locals()]+SL+[globals(), builtin],"sickbeard.SYS_ENCODING",True)),"capitalize",False)() # u"$datetime.date.fromordinal($cur_ep_airdate.toordinal).strftime('%A').decode($sickbeard.SYS_ENCODING).capitalize()" on line 364, col 29
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe1 in position 3: invalid continuation byte

```
* When browsing folders, finally a special character using foldername not freeze whole process, but that folder **IS** showing up in the list, **BUT UNABLE TO OPEN** for browse :wavy_dash:
* Still not find series on TVDB with special characters in the name :x: 

 Series not already on my list, correct language chosed on search, all indexers used, correctly spelled characters, tried with copy&paste also (from tvdb)
- Jóbarátok (Friends, HUN) http://thetvdb.com/?tab=series&id=79168&lid=19
- Vänner (Friends, SWE) http://thetvdb.com/?tab=series&id=79168&lid=8
- Munkaügyek (HUN) http://thetvdb.com/?tab=series&id=257433&lid=19
- Balfékek (Community, HUN) http://thetvdb.com/?tab=series&id=94571&lid=19

**Comment by miigotu** [comment]
@kotysoft with the new mako branch (now merged into develop), I can search all 4 of those shows and get a result and add them to SR. Please verify, and check coming episodes page.

**Comment by kotysoft** [comment]
Updated
BRANCH: (master) / COMMIT: (99ecfb5edcae4a8e5facff73f39ff1415a5e3e96) 

I just tested it again, but can't believe it: Still the same.
Maybe Am I missed something basic thing when installed?
Or the OS language is the problem...?
I don't know... It's too late today. Tomorrow evening I'll try it on another computer from scratch. Wait for it please.

**Comment by miigotu** [comment]
@kotysoft mako is only in develop branch, not master.

![image](https://cloud.githubusercontent.com/assets/390379/9156823/2dbe1fba-3e9c-11e5-854f-3847d1cf7ace.png)

**Comment by kotysoft** [comment]
Maybe something wrong with my Python... :\ Tomorrow evening will try on different OS, starting from scratch.

Is your server running under Windows?

Tried current develop branch, but did the same. Nothing found. "Coming episodes" get this error:

```
Error !
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe1 in position 3: invalid continuation byte
<% too_late_header = True %> % elif cur_ep_enddate >= today and cur_ep_airdate < next_week.date(): % if cur_ep_airdate == today.date(): <br /><h2 class="day">${datetime.date.fromordinal(cur_ep_airdate.toordinal()).strftime('%A').decode(sickbeard.SYS_ENCODING).capitalize()}<span style="font-size: 14px; vertical-align: top;">[Today]</span></h2> <% today_header = True %> % else: <br /><h2 class="day">${datetime.date.fromordinal(cur_ep_airdate.toordinal()).strftime('%A').decode(sickbeard.SYS_ENCODING).capitalize()}</h2> % endif % endif
C:\Python27\lib\encodings\utf_8.py, line 16:
return codecs.utf_8_decode(input, errors, True)
C:\SR\gui/slick/interfaces/default/comingEpisodes.mako, line 343:
<br /><h2 class="day">${datetime.date.fromordinal(cur_ep_airdate.toordinal()).strftime('%A').decode(sickbeard.SYS_ENCODING).capitalize()}<span style="font-size: 14px; vertical-align: top;">[Today]</span></h2>
C:\SR\lib\mako\runtime.py, line 853:
callable_(context, *args, **kwargs)
```

**Comment by kotysoft** [comment]
Today I completely removed SickRage, Python, Git from my Windows.
Only hungarian windows available here at home, so I kept trying on same OS
(Windows 2008 R2 Standard HU x64)

Followed this step-by-step:
http://www.htpcguides.com/install-sickrage-windows-usenet-torrent-tv/

Now tried with Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]
Last time I missed OpenSSL thing (maybe new update on linked site). Now I installed it.

* Cloned develop branch to an empty folder
* opened a CMD, and tried my brand new SickBeard.py with and without `chcp 65001` before running (in same console)
* situation unchanged.... :-(

**Comment by miigotu** [comment]
@kotysoft you still need `chcp 65001`

**Comment by ahmedtechinfo** [comment]
Hi I updated Sickrage through browser today and now i am getting the following error:-

</td> <td align="center"> <img src="${sbRoot}/images/${('no16.png", alt="No"', 'yes16.png", alt="Yes"')[int(curShow.paused) == 0 and curShow.status == 'Continuing']} width="16" height="16" /> </td> <td align="center"> <% display_status = curShow.status %> % if None is not display_status:
/usr/pbi/sickrage-amd64/share/sickrage/SickRage/gui/slick/interfaces/default/home.mako, line 818:
<img src="${sbRoot}/images/${('no16.png", alt="No"', 'yes16.png", alt="Yes"')[int(curShow.paused) == 0 and curShow.status == 'Continuing']} width="16" height="16" />
/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/mako/runtime.py, line 853:
callable_(context, *args, **kwargs)

I am using freenas and wont be able to tell u about commits since it is not running.

**Comment by saitoh183** [comment]
@miigotu 

I recently came across the same problem that i was unable to add a french TV show because the search would come up empty. I spoke to a user on IRC and when he would search, he was able to find the show.

this is the show in question : http://thetvdb.com/?tab=series&id=273086&lid=17

other User search result:
https://cloud.githubusercontent.com/assets/7928052/9384074/d96703c2-474d-11e5-8764-dd67d28b94cc.png

My search result:
http://snag.gy/LbV1C.jpg 

On Windows 2012r2 std

SR Version:	BRANCH: (master) / COMMIT: (7a432bd2eab0f74f89cdf330b0e1af342cf25030) 
SR User:	Administrator
SR Locale:	('en_CA', 'cp1252')
SR Config file:	E:\SickRage\config.ini
SR Database file:	E:\SickRage\sickbeard.db
SR Cache Dir:	E:\SickRage\cache
SR Log Dir:	E:\SickRage\Logs
SR Arguments:	['--nolaunch']
Python Version:	2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]

**Comment by maxcore** [comment]
![capture d ecran 2015-08-20 14 45 43](https://cloud.githubusercontent.com/assets/4043787/9392373/415c1ae8-474a-11e5-886f-93e81afdc652.png)

**Comment by saitoh183** [comment]
@maxcore 

You are not on windows...i know i linux it works

**Comment by miigotu** [comment]
@saitoh183  
"SR Locale: ('en_CA', 'cp1252')"
you need to set locale to utf-8 with `chcp 65001 just before each time SR starts (in the same script/terminal)

@ahmedtechinfo Your SR must not be totally up to date, as that line is at 823 currently not 818.

**Comment by saitoh183** [comment]
@miigotu 

How do we do that because i tried opening a cmd prompt and running chcp 65001 and then running Sickbeard.py from the same window and when i check the Local, it didnt change.

**Comment by saitoh183** [comment]
@miigotu 

![image](https://cloud.githubusercontent.com/assets/1534197/9393453/05473ac8-4750-11e5-9652-08ab1218ade0.png)

![image](https://cloud.githubusercontent.com/assets/1534197/9393470/1f7034a4-4750-11e5-85f7-b250ed912904.png)

**Comment by miigotu** [comment]
chcp 65001 && python SickBeard.py

**Comment by saitoh183** [comment]
@miigotu 

same result

![image](https://cloud.githubusercontent.com/assets/1534197/9393683/6162e1b2-4751-11e5-9e39-1bf11bbaa50d.png)
