### ISSUE TITLE
[APP SUBMITTED]: Thread-322 :: Refusing to change status of 1x3 to DOWNLOADED because it's not SNATCHED/DOWNLOADED

### ISSUE THREAD

**Issue by erickgrau** [SiCKRAGETV/sickrage-issues#1426]
### INFO
Python Version: **2.7.9rc1 (v2.7.9rc1:40eada278702, Nov 25 2014, 17:25:50) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]**
Operating System: **Darwin-14.3.0-x86_64-i386-64bit**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@c1c519b720acfbbc5cec7c5a89c48053e9f1b980
Link to Log: https://gist.github.com/bc5ff993c71b7386211a
### ERROR
```
Thread-322 :: Refusing to change status of 1x3 to DOWNLOADED because it's not SNATCHED/DOWNLOADED
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@erickgrau change to ignored than to downloaded

**Comment by fernandog** [comment]
I
