### ISSUE TITLE
Sickrage to Sickrage Connection

### ISSUE THREAD

**Issue by TehWardy** [SiCKRAGETV/sickrage-issues#1428]
Recently I found myself writing a ton of code to crawl a mates ftp server which basically contains his sickrage created library.

What if I could treat another sickrage instance like a torrent or usenet provider and share my library with a friend and he do the same perhaps using api keys for access?

SR knows what I have and knows what I don't, I only want to sync what I don't and how i get that is really irrelevant so my theory here is ... Another SR library is a perfect source right?

**Comment by apoapostolov** [comment]
Can't you do the same with Plex already?

**Comment by TehWardy** [comment]
Sort of, plex gives you access to stream / view someone elses library, what i'm talking about here is using another SR instance to copy the bits someone else has but that I am missing in to my own library. Although if you pay for Plex I understand you get the sync option that lets you build a playlist and sync it to a device, I guess that's similar to this in that I want to "sync to my downloads folder, stuff I'm missing"

**Comment by TehWardy** [comment]
Closed? Why? Could be a neat feature.
