### ISSUE TITLE
Sorting of Shows in Show List

### ISSUE THREAD

**Issue by DrewPBalls** [SiCKRAGETV/sickrage-issues#1429]
When I shutdown SickRage, all the shows are sorted alphabetically. When I re-open SickRage, the shows are in some random order, even though the sort arrow on the show category would indicate that the Shows are sorted in some non-random order.

Python Version:	2.7.9
SR Version: 	BRANCH: (master) 
Running on Windows 7 SP1 - 64-bit

**Comment by fernandog** [comment]
@Thraxis wasn't persistent?

**Comment by Thraxis** [comment]
@fernandog I'm not seeing this issue locally
@DrewPBalls Are you still seeing this problem?

**Comment by Thraxis** [comment]
It's been over 2 weeks with no other reports of this issue and no response.  Closing this one
