### ISSUE TITLE
Episodes with failed status allow snatching the same release again

### ISSUE THREAD

**Issue by miigotu** [SiCKRAGETV/sickrage-issues#1430]
If I have a snatch in my torrent client that has 0 seeders, and I mark it was failed in SR, the same exact release is snatched again.

It should ignore a search item that matches the failed _release_name.

https://gist.github.com/miigotu/5524a8e619ae61b1536e

Also is min seeders broken?

**Comment by fernandog** [comment]
@miigotu do you have failed downloads enabled ?

**Comment by miigotu** [comment]
I did not, IDK why that is off by default though lol.
