### ISSUE TITLE
[Feature Request] Per-show search frequency

### ISSUE THREAD

**Issue by nesler** [SiCKRAGETV/sickrage-issues#1433]
Hi,

Would it be possible to allow per-show daily search frequency settings?

Say, I have a couple show, that I'd like to poll for a lot more frequently than others (because I know they're gonna give me a good ratio :wink: ), and others are OK to just be searched every few hours.

Currently, I've set daily search frequency to 10 minutes, which performs OK, but seems a little unnecessary.

Maybe even limit daily seaches to be performed 12 hours prior to/after the TVDB-provided air-date? Or this is maybe already how it works?

Hope these ideas are worth something to others than myself :smile: 

(Opened a thread prior to creating this issue: https://sickrage.tv/forums/forum/main-category/feature-requests/22379-per-show-search-frequency)

**Comment by WebSpider** [comment]
This would mean we'd have to implement an update queue, similar to the other queues.Not simple..not impossible :)

**Comment by WebSpider** [comment]
We're actually going to do this differently: We're working on rewriting the daily search so that it will only request updates from shows the indexers tell us have been updated. This FR will therefore be closed.
