### ISSUE TITLE
Feature Request: Rss feed support

### ISSUE THREAD

**Issue by TehWardy** [SiCKRAGETV/sickrage-issues#1441]
Is this feature already in (i can't seem to find this anywhere)?

Basically I know of a few sites like http://showrss.info/ that allow you to subscribe to a listing of episodes for a show. 
It would be cool if SR could use RSS feeds as a source for torrent / nzb files in the same way that it already does with searching on indexing sites.

**Comment by palmfighter** [comment]
But you can add the RSS to SAB and then when finished have SR pick it up. Perhaps an idea for you?

**Comment by TehWardy** [comment]
At the moment I'm doing that with utorrebt but that don't know what files I need and sr goes and gets stuff and adds the same download to sab ... So I download most stuff that can be found on both twice ... Having that in Sr would stop that.

**Comment by fernandog** [comment]
why you would subscribe to a custom listing if SR already get a RSS feed from a tracker and does the listing itself?!

**Comment by TehWardy** [comment]
Can I add any arbritary rss feed for SR to search through when looking for episodes?
If so how?

**Comment by fernandog** [comment]
have you ever opened the provider settings page?

**Comment by TehWardy** [comment]
Yeh but it scared me so I closed it again ... Do the providers settings expect rss feeds as the target ? I figured it was sone other format or something.
