### ISSUE TITLE
[APP SUBMITTED]: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

### ISSUE THREAD

**Issue by maZuFC** [SiCKRAGETV/sickrage-issues#1442]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/129c69b03ff46abc746d
### ERROR
```
SEARCHQUEUE-MANUAL-75978 :: [TorrentDay] :: Error while searching TorrentDay, skipping: error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by maZuFC** [comment]
hey all

started getting this error message today and i cant figure out what it is... has anybody seen this or knows how to resolve it?


thanks!

**Comment by maZuFC** [comment]
hey Fernando... why did you close this?

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1231

**Comment by maZuFC** [comment]
thanks... ill check it out
