### ISSUE TITLE
[Feature Request] Add login option for Opensubtitles

### ISSUE THREAD

**Issue by palmfighter** [SiCKRAGETV/sickrage-issues#1443]
Would like to have a config where I can configure OpenSubtitles login details. I am a VIP there and would like to reuse this account to have more searches possible there.

**Comment by WebSpider** [comment]
@palmfighter do you have any documentation available there about the extra functions as a VIP? Just adding login support seems useless when not adding support for VIP options.

**Comment by palmfighter** [comment]
Let me check when back from holiday :) good point. 

Verstuurd vanaf mijn iPhone

**Comment by miigotu** [comment]
This will not happen in SR until subliminal is updated once again. We no longer customize libraries.

**Comment by WebSpider** [comment]
Subliminal seems to have an open issue for just this: Diaoul/subliminal#365 ... once they add login possibilities to opensubtitles, we can add the feature as well.

**Comment by WebSpider** [comment]
Subliminal has implemented this in their develop branch. I'll have a look at updating subliminal in SR so we can start supporting this.

**Comment by miigotu** [comment]
Just need to figure out how to handle the entry points for the providers. They install them with stevedore and setup.py in subliminal now

**Comment by miigotu** [comment]
Also, while your at it,  there is an Addic7ed login option too in subliminal dev

**Comment by palmfighter** [comment]
Great to see you guys are working on it!

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
