### ISSUE TITLE
[Feature Request] Add TorrentShack.me

### ISSUE THREAD

**Issue by Martijn085** [SiCKRAGETV/sickrage-issues#1447]
Could someone please add the private tracker: http://torrentshack.me

**Comment by Martijn085** [comment]
Any idea about when this feature request is carried out?

**Comment by fernandog** [comment]
lots of issues. no dev to code this

**Comment by jtwill** [comment]
Note that SickGear recently added Torrentshack, so the SG code can hopefully be used to jumpstart a SickRage implementation:

https://github.com/SickGear/SickGear/blob/develop/sickbeard/providers/torrentshack.py

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
