### ISSUE TITLE
tntvillage provider issue, incorrect filter in http string

### ISSUE THREAD

**Issue by vegeros** [SiCKRAGETV/sickrage-issues#1450]
Branch: master
Commit hash: 5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Your operating system and python version: mac os x 10.10, phyton 2.7

What you did
manual search for The Vampire Diaries - 6x03

What happened
no torrent found because the search string is not correct.
I see in the debug log: http://forum.tntvillage.scambioetico.org/?act=allreleases&st=0&cat=29&filter=**********
Instead of: http://forum.tntvillage.scambioetico.org/?act=allreleases&st=0&cat=29&filter=The Vampire Diaries S06E03 

What you expected
to find a torrent because it is present on the provider.

https://gist.github.com/vegeros/c5745cda9dcf923be9a1#file-gistfile1-txt

**Comment by Thraxis** [comment]
The log filter change to hide NZB api_key's is filtering the log line for the search.  I'll re-work the regex to try and prevent that.

**Comment by vegeros** [comment]
Ok, I have understood that. Now it is working fine, there was an issue on the provider itself.
Thanks a lot for your time and for your great work

**Comment by Thraxis** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1888
