### ISSUE TITLE
[APP SUBMITTED]: UNIQUE constraint failed: network_timezones.network_name

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#1451]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:34:55) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-15-generic-i686-with-Ubuntu-15.04-vivid**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@eaf8dff4bd23cbdcf8480e4351340140f00f90be
Link to Log: https://gist.github.com/ff7e754c3d2e4964d127
### ERROR
```
MAIN :: Fatal error executing query: UNIQUE constraint failed: network_timezones.network_name
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by matigonkas** [comment]
Traceback: 
```6:47 INFO SEARCHQUEUE-BACKLOG-79485 :: Building internal name cache for How It's Made 2015-04-27 22:56:47 INFO SEARCHQUEUE-BACKLOG-79485 :: No scene exceptions update needed AAIntegrityError: UNIQUE constraint failed: network_timezones.network_name AA return self.connection.cursor().execute(query, args) AA File "/home/super******/SickRage/sickbeard/db.py", line 79, in _execute AA return self._execute(query, args) AA File "/home/super******/SickRage/sickbeard/db.py", line 90, in execute AA sqlResult.append(self.execute(qu[0], qu[1], fetchall=fetchall)) AA File "/home/super******/SickRage/sickbeard/db.py", line 127, in mass_action AATraceback (most recent call last): 2015-04-27 22:56:46 ERROR MAIN :: Fatal error executing query: UNIQUE constraint failed: network_timezones.network_name 2015-04-27 22:56:25 INFO BACKLOG :: Seeing if we need anything from Man Finds Food 2015-04-27 22:56:25 INFO BACKLOG :: Seeing if we need anything from The Watch 2015-04-27 22:56:25 INFO BACKLOG :: Seeing if we need anything from The Pool Master 2015-04-27 22:56:25 INFO BACKLOG :: Seeing if we need anything from Impossible Engineering 2015-04-27 22:56:24 INFO BACKLOG :: Seeing if we need anything from Science of the Movies 2015-04-27 22:56:24 INFO BACKLOG :: Seeing if we nee ```

**Comment by TimVNL** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 23 2015, 00:07:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
No Log available with ERRORS: 
### ERROR
```
MAIN :: Fatal error executing query: UNIQUE constraint failed: network_timezones.network_name
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by bglover** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 23 2015, 00:07:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
No Log available with ERRORS: 
### ERROR
```
MAIN :: Fatal error executing query: UNIQUE constraint failed: network_timezones.network_name
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by nebbywan** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-34-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
No Log available with ERRORS: 
### ERROR
```
MAIN :: Fatal error executing query: UNIQUE constraint failed: network_timezones.network_name
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@matigonkas are you still having this issue?

**Comment by matigonkas** [comment]
No im not
