### ISSUE TITLE
Subtitle Settings and  other issues/features

### ISSUE THREAD

**Issue by Peke** [SiCKRAGETV/sickrage-issues#1452]
Currently there is number of issues when you setup what subtitles should SickRage search

Selection is based on language codes delivered from http://en.wikipedia.org/wiki/List_of_ISO_639-2_codes but flag codes are searched based on http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2 which can end up in number of false flags like for example my native Serbian where there is correct FLAG Icon "rs.png" but if you select Serbian you get "sr.png" which is completely wrong. I know it gets more complicated but here is clarification http://symbolcodes.tlt.psu.edu/bylanguage/serbocroatian.html#encode which comply with Approach from http://en.wikipedia.org/wiki/IETF_language_tag

Additionally multi subtitles are using http://en.wikipedia.org/wiki/ISO_639-2 instead of http://en.wikipedia.org/wiki/ISO_639-3 which is defacto standard.

Due the these issues/facts searches can return not just faulty empty result but also completely incorrect Subtitle. Solution for that would be again that for subtitle search plugins there is param where SickRage would be able to alter/enter correct format used by Subtitle plugin

Still there is number of apps that only understand EXACT filename without double extension (LNG extension) so defining default subtitle LNG should be cloned to ensure compatibility.

I'll be glad to hear your thoughts and also I'm willing to help as much as possible to implement things.

**Comment by neoatomic** [comment]
@Peke This is a know problem for some time.  
For subtitles SR uses subminimal. (Witch is an older version and getting outdated quickly.) 
Its on the to do list for a complete overhaul, but the developers are simply to busy to get started on this.

If you have experience with coding/python your help is more than welcome to get this starting.
The popularity of SR has gone trough the roof and we can use every help we can to make it even better. :)

**Comment by fernandog** [comment]
this FR is for subliminal. Not SR

**Comment by Peke** [comment]
More advanced knowledge of PY is on my to do list currently enhancing HTML5, JS, CSS3 and Ajax skills. I'll see if I can write simple script or even better an app in Delphi for easier implementation by devs. I'll look at least to make Small MySQL table and triggers to ease the search managing the list of Languages.

**Comment by neoatomic** [comment]
@Peke Feel free to create a PR if you think you can make an improvement to SR. 
We have a large list of feature requests on the issue tracker, there might be some that are of interest to you, if you want to try to enhance your skills. :)
