### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'whitelist'

### ISSUE THREAD

**Issue by gregtotheizzo** [SiCKRAGETV/sickrage-issues#1453]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-262980 :: [omgwtfnzbs] :: Error while searching omgwtfnzbs, skipping: 'NoneType' object has no attribute 'whitelist'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SamTwining** [comment]
Seconded:

Python Version: **2.7.8**
Operating System: **Ubuntu 14.4**
Branch: **master**
Commit: [SiCKRAGETV/SickRage@5ef5a0b](https://github.com/SiCKRAGETV/SickRage/commit/5ef5a0b27e27cf937011408cb55329d1bd21ce9d)

ERROR

```
2015-04-27 20:42:46 DEBUG    SEARCHQUEUE-BACKLOG-24504 :: [omgwtfnzbs] :: Attempting to add item to cache: IndyCar.Series.2015.Alabama.HDTV.x264-CHAMPiONS
2015-04-27 20:42:46 DEBUG    SEARCHQUEUE-BACKLOG-24504 :: [omgwtfnzbs] :: Using ALL regexes
2015-04-27 20:42:46 DEBUG    SEARCHQUEUE-BACKLOG-24504 :: [omgwtfnzbs] :: Unable to parse the filename IndyCar.Series.2015.Alabama.HDTV.x264-CHAMPiONS into a valid show
2015-04-27 20:42:46 DEBUG    SEARCHQUEUE-BACKLOG-24504 :: [omgwtfnzbs] :: Attempting to add item to cache: The.Block.AU.S10E55.PDTV.x264-FQM
2015-04-27 20:42:46 DEBUG    SEARCHQUEUE-BACKLOG-24504 :: [omgwtfnzbs] :: Using ALL regexes
2015-04-27 20:42:46 DEBUG    SEARCHQUEUE-BACKLOG-24504 :: [omgwtfnzbs] :: Unable to parse the filename The.Block.AU.S10E55.PDTV.x264-FQM into a valid show
2015-04-27 20:42:46 INFO     SEARCHQUEUE-BACKLOG-24504 :: [omgwtfnzbs] :: Performing episode search for Louie
2015-04-27 20:42:46 ERROR    SEARCHQUEUE-BACKLOG-24504 :: [omgwtfnzbs] :: Error while searching omgwtfnzbs, skipping: 'NoneType' object has no attribute 'whitelist'
Traceback (most recent call last):
  File "/home/maplest/sickrage_install/sickbeard/search.py", line 473, in searchProviders
    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
  File "/home/maplest/sickrage_install/sickbeard/providers/generic.py", line 292, in findSearchResults
    for curString in self._get_episode_search_strings(epObj):
  File "/home/maplest/sickrage_install/sickbeard/providers/omgwtfnzbs.py", line 99, in _get_episode_search_strings
    return [x for x in show_name_helpers.makeSceneSearchString(self.show, ep_obj)]
  File "/home/maplest/sickrage_install/sickbeard/show_name_helpers.py", line 240, in makeSceneSearchString
    if len(ep_obj.show.release_groups.whitelist) > 0:
AttributeError: 'NoneType' object has no attribute 'whitelist'
2015-04-27 20:42:46 DEBUG    SEARCHQUEUE-BACKLOG-24504 :: [omgwtfnzbs] :: Traceback (most recent call last):
  File "/home/maplest/sickrage_install/sickbeard/search.py", line 473, in searchProviders
    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
  File "/home/maplest/sickrage_install/sickbeard/providers/generic.py", line 292, in findSearchResults
    for curString in self._get_episode_search_strings(epObj):
  File "/home/maplest/sickrage_install/sickbeard/providers/omgwtfnzbs.py", line 99, in _get_episode_search_strings
    return [x for x in show_name_helpers.makeSceneSearchString(self.show, ep_obj)]
  File "/home/maplest/sickrage_install/sickbeard/show_name_helpers.py", line 240, in makeSceneSearchString
    if len(ep_obj.show.release_groups.whitelist) > 0:
AttributeError: 'NoneType' object has no attribute 'whitelist'

2015-04-27 20:42:46 WARNING  SEARCHQUEUE-BACKLOG-24504 :: No NZB/Torrent providers found or enabled in the sickrage config for backlog searches. Please check your settings.
2015-04-27 20:42:46 INFO     SEARCHQUEUE-BACKLOG-24504 :: No needed episodes found during backlog search for: [Louie]
```

**Comment by clearminds** [comment]
Same error here

**Comment by hulubi** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/1f0ffbcbfe83a0a391f3
### ERROR
```
SEARCHQUEUE-BACKLOG-79169 :: [omgwtfnzbs] :: Error while searching omgwtfnzbs, skipping: 'NoneType' object has no attribute 'whitelist'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by hulubi** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/91100189976dd14e1dba
### ERROR
```
SEARCHQUEUE-BACKLOG-72368 :: [omgwtfnzbs] :: Error while searching omgwtfnzbs, skipping: 'NoneType' object has no attribute 'whitelist'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by hulubi** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/14c4b7f6e197653938cb
### ERROR
```
SEARCHQUEUE-BACKLOG-75692 :: [omgwtfnzbs] :: Error while searching omgwtfnzbs, skipping: 'NoneType' object has no attribute 'whitelist'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@hulubi no need report every time.

**Comment by dave-tucker** [comment]
Was able to hack around this by adding the `if ep_obj.show.release_groups is not None:` before [this line](https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/show_name_helpers.py#L240)
Example:
``` python
if ep_obj.show.release_groups is not None:    
    if len(ep_obj.show.release_groups.whitelist) > 0:
...
```

**Comment by nekkidtruth** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-286971 :: [omgwtfnzbs] :: Error while searching omgwtfnzbs, skipping: 'NoneType' object has no attribute 'whitelist'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by falassiry** [comment]
Can confirm same issue on FreeNAS version including latest commits.

**Comment by hulubi** [comment]
if ep_obj.show.release_groups is not None:

Didn't fix it. Mine is qnap.

**Comment by MrEnigmamgine** [comment]
I had this error too.  I disabled OMGWTFNZBS from my search providers and it seems to have cleared the issue.

**Comment by nekkidtruth** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@1c1f80877b22531fe73aef61fad784b140fef605
Link to Log: https://gist.github.com/c4d4e808339b530f0ef9
### ERROR
```
SEARCHQUEUE-MANUAL-265766 :: [omgwtfnzbs] :: Error while searching omgwtfnzbs, skipping: 'NoneType' object has no attribute 'whitelist'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by nekkidtruth** [comment]
Any word on this issue? Resolution? Do we know what the issue is? Still happening and just updated again.

**Comment by fernandog** [comment]
@Thraxis can you fix this PR? your PR that created this error. thanks!

**Comment by Thraxis** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1889

**Comment by chimchild** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@cfe3b40b30ecec5c1838a5b6898bd79faf0ea762
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-MANUAL-248741 :: [omgwtfnzbs] :: Error while searching omgwtfnzbs, skipping: 'NoneType' object has no attribute 'whitelist'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by simonlock** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.11-v7+-armv7l-with-debian-7.8**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@cfe3b40b30ecec5c1838a5b6898bd79faf0ea762
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-262980 :: [omgwtfnzbs] :: Error while searching omgwtfnzbs, skipping: 'NoneType' object has no attribute 'whitelist'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by simonlock** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.11-v7+-armv7l-with-debian-7.8**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@cfe3b40b30ecec5c1838a5b6898bd79faf0ea762
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-262980 :: [omgwtfnzbs] :: Error while searching omgwtfnzbs, skipping: 'NoneType' object has no attribute 'whitelist'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by thecolorchanges** [comment]
### INFO
Python Version: **2.6.5 (r265:79063, Jul 24 2010, 21:39:31) [GCC 4.2.3]**
Operating System: **Linux-3.0.3-unRAID-i686-AMD_Athlon-tm-_II_Neo_N36L_Dual-Core_Processor-with-slackware-13.1.0**
Locale: UTF8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@50b81987274e704c6e1b9ffdbf1e436368ac2acd
Link to Log: https://gist.github.com/e1fdbffb1ff3310c4fc1
### ERROR
```
SEARCHQUEUE-MANUAL-196921 :: [omgwtfnzbs] :: Error while searching omgwtfnzbs, skipping: 'NoneType' object has no attribute 'whitelist'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by thecolorchanges** [comment]
Have been seeing this error popup quite frequently lately. 

Thanks,
 thecolorchanges
