### ISSUE TITLE
[APP SUBMITTED]: list modified during sort

### ISSUE THREAD

**Issue by Prawna** [SiCKRAGETV/sickrage-issues#1454]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE :: Exception generated in thread SHOWQUEUE: list modified during sort
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
@Prawna this report is invalid without a log, please post it [gist gist.github.com/prawna]  and link it here.

**Comment by fernandog** [comment]
@Prawna did you deleted any shows recently?
