### ISSUE TITLE
[APP SUBMITTED]: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing: incorrect header check',))

### ISSUE THREAD

**Issue by TimVNL** [SiCKRAGETV/sickrage-issues#1455]
### INFO
Python Version: **2.7.9 (default, Mar 23 2015, 00:07:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-262152 :: Unable to save the file: error ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing: incorrect header check',))
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@miigotu this one has no log. probably regex issue?

**Comment by miigotu** [comment]
This one is just a failed transfer of a zip, maybe a bad net connection. There is nothing we can do about this. Maybe it should be a warning and not an error.

**Comment by raver2046** [comment]
No it can be a missconfigured server. look at this warning .
2015-10-06 11:06:30 DEBUG    SEARCHQUEUE-MANUAL-276564 :: [BLUETIGERS] :: Content-Encoding was gzip, but content was not compressed. getURL: https://www.bluetigers.ca/torrents-search.php

Can we force a provider to disalow gzip request?

**Comment by miigotu** [comment]
Yes, we can remove gzip from the 'Accept-encoding' header we send.

**Comment by raver2046** [comment]
if you explain me where it can be done i will do it

**Comment by miigotu** [comment]
working on some tests for this in IRC.
