### ISSUE TITLE
[APP SUBMITTED]: [Errno 1] _ssl.c:492: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

### ISSUE THREAD

**Issue by mationic** [SiCKRAGETV/sickrage-issues#1457]
### INFO
Python Version: **2.6.6 (r266:84292, Jan 22 2014, 09:42:36) [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]**
Operating System: **Linux-2.6.32-042stab094.8-x86_64-with-centos-6.6-Final**
Locale: UTF8
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/377c02bf296775358df9
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:492: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by papampi** [comment]
got the same problem :
SR Version:	BRANCH: (master) / COMMIT: (5ef5a0b27e27cf937011408cb55329d1bd21ce9d) 
Python Version:	2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]
OS: Ubuntu 64 14.04 3.13.0-49
​[CODE]
SEARCHQUEUE-BACKLOG-78988 :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
[/CODE]

**Comment by neives** [comment]
Same error here:

BRANCH: (master) / COMMIT: (5ef5a0b27e27cf937011408cb55329d1bd21ce9d) 

Operating System: Raspbian - (Linux version 3.18.7+ (dc4@dc4-XPS13-9333) (gcc version 4.8.3 20140303 (prerelease)

Python 2.7.3 (default, Mar 18 2014, 05:13:23)

Locale: UTF8


2015-04-28 13:21:26 SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

**Comment by xiolo** [comment]
yep. same here on Ubuntu 12.04 and Xbian as well.  That's the openssl version that gained TLSv1.1 support, which is causing the remote server to close the connection. If Sickrage could force openssl to use SSLv3 instead of TLSv1.1 (-3 on openssl),that would fix sites such as rarbg and piratebay backlog searches

**Comment by mationic** [comment]
Could this be of help?

https://urllib3.readthedocs.org/en/latest/contrib.html

**Comment by fernandog** [comment]
@mationic 

stop SR
run in SSH
pip install --upgrade setuptools
pip install pyopenssl --upgrade
pip install urllib3 --upgrade

try again

**Comment by mationic** [comment]
just checked..  they were already up-to-date...
doesn't sickbeard use its own hardcorded modules anyway...?

**Comment by miigotu** [comment]
Check here if you can help us debug this: https://github.com/SiCKRAGETV/sickrage-issues/issues/1231#issuecomment-97677808

**Comment by hazell20** [comment]
### INFO
Python Version: **2.6.6 (r266:84292, Jan 22 2014, 09:42:36) [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]**
Operating System: **Linux-2.6.32-504.16.2.el6.x86_64-x86_64-with-centos-6.6-Final**
Locale: UTF8
Branch: **master**
Commit: SiCKRAGETV/SickRage@11796ea71472f509ff87d411f8b0cf74354fc72c
Link to Log: https://gist.github.com/c316f5352f50c188bb2b
### ERROR
```
SEARCHQUEUE-BACKLOG-78957 :: [TorrentDay] :: Unable to connect to TorrentDay provider: error [Errno 1] _ssl.c:492: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
