### ISSUE TITLE
SHOWQUEUE-REFRESH seems to hang/stop

### ISSUE THREAD

**Issue by pct00** [SiCKRAGETV/sickrage-issues#1458]
Python Version: 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]
Operating System: Windows-7-6.1.7601-SP1
Branch: develop
Commit: SiCKRAGETV/SickRage@5fd354c

hi

i have noticed this for a few "versions already"

SHOWQUEUE-REFRESH seems to hang in the middle of processing and doesnt update all shows. anyone else noticing the same issue?

i checked the log file but no errors seems to be logged.

**Comment by neoatomic** [comment]
@pct00 Please upload the full debug log. It shows what SR is doing even when there are no errors. 
The Developers need this to troubleshoot your problem.
