### ISSUE TITLE
[Feature Request] qBittorrent Allow high priority not working as it should.

### ISSUE THREAD

**Issue by papampi** [SiCKRAGETV/sickrage-issues#1459]
Posted this in forums, but thought its better to post it here too.

Does the "Allow high priority" should send recent aired episodes to top or just raise one level ?
if it should send to top then its not working as it should in qBittorrent,
it only raise one level not send them to top and for those like me with too many torrents in the list its useless.

**Comment by neoatomic** [comment]
@papampi 
Well, SR sends it as a high priority torrent. So if the other torrents are normal priority, the bandwidth will go first to the high priority torrent.
It has noting to do with starting the torrent or putting it on top of your list. Its about allocating resources.

**Comment by papampi** [comment]
Thanks for answering both in forum and here
![qb](https://cloud.githubusercontent.com/assets/1108483/7369008/3ae24434-edc3-11e4-8a4a-91e83c694582.jpg)
I think in qBittorrent its a bit different, when we give a torrent high priority it goes to top of the list, when we add priority it just move up one step.

**Comment by neoatomic** [comment]
@papampi I need to admit that i dont use qBittorrent. I was in the understanding that it worked like other clients.

@JustMaier Could you confirm if the torrents indeed need to be placed on top of the list when high priority in SR is used ?

**Comment by papampi** [comment]
@neoatomic in other torrent clients, if you have queuing enabled and you set to download max 5 torrents to download at a time and you have 20 in the list what will happen when SR add new torrents with high priority?
it just add them to the end of the list and wait till their turn comes up ?

**Comment by neoatomic** [comment]
@papampi  Yes, the torrent needs to be active. If you set your client to max 5 downloads it will do exactly that and download no more. So your torrent will be paused till only 4 downloads are running and then start.
As i mentioned before normally the priority is for allocating resources (bandwidth) for active downloads. But qBittorrent seems to function differently.?

For some clients it can have a different function. For Sabnzb we have recently implemented a new feature. When you have paused sabnzb and send a "forced high priority" nzb it will start downloading even if sabnzb is paused.
So it really depends on what the client software allows and how the code was designed in SickRage.
qBittorrent support is brand new in SickRage, and it might not be perfect yet.

We have to thank JustMaier, as he coded the qBittorrent addition for SickRage.
So hopefully he can give us some more information on how the high priority should behave.

**Comment by papampi** [comment]
I know its new and so very much thankful to all people who brought us this amazing software, 
so what I said could be useful in other clients which use queuing too.

**Comment by JustMaier** [comment]
Hey @neoatomic, Reading the `_set_torrent_priority` method, I assumed it was used to increase/decrease priority not send an item to the top of the queue. Right now it increases/decreases by 1 using [this api call](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation#increase-torrent-priority). Do I need to change it so it instead gives the maximal and minimal priority depending on whether it received a 1 or -1?

**Comment by neoatomic** [comment]
@JustMaier Than its working just fine.
Do you know if "maximal torrent priority" places the torrent on top of the list.? Like the user requests.? Cant find a clear explanation in the API guide...

If that is the case, it could be a useful addition to add the the qBittorrent settings page.
Adding a simple checkbox to set "force maximum priority" when sending the torrent to qBittorrent.
(We did something similar with sabnzb to bypass the paused function.)

@fernandog could you jump in and give us your view.?

**Comment by fernandog** [comment]
it's up to qbittorrent users. Don't use it. The only thing is labels and fields name must the aligned with the client

**Comment by JustMaier** [comment]
Sounds like a good idea @neoatomic I'll look into adding that as an option

**Comment by papampi** [comment]
That would be awesome @JustMaier , 
Thanks a lot, 
and sorry to give you guys more headache.

**Comment by neoatomic** [comment]
@JustMaier Where you able to look into this.?

**Comment by JustMaier** [comment]
I haven't looked at this yet, but I should have some time to do it this weekend.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
