### ISSUE TITLE
[APP SUBMITTED]: ordinal must be >= 1

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#1460]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-3.18.10-1-osmc-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@eaf8dff4bd23cbdcf8480e4351340140f00f90be
Link to Log: https://gist.github.com/5f609c403869e264d5c8
### ERROR
```
Thread-221 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 1282, in displayShow
    return t.respond()
  File "/home/osmc/SickRage/cache/cheetah/_home_osmc_SickRage_gui_slick_interfaces_default_displayShow_tmpl.py", line 1314, in respond
    _v =  VFN(VFFSL(SL,"sbdatetime.sbdatetime",True),"sbfdate",False)(VFN(VFFSL(SL,"sbdatetime.sbdatetime",True),"convert_to_setting",False)(VFN(VFFSL(SL,"network_timezones",True),"parse_date_time",False)(VFFSL(SL,"epResult",True)['airdate'],VFFSL(SL,"show.airs",True),VFFSL(SL,"show.network",True))))
  File "/home/osmc/SickRage/sickbeard/network_timezones.py", line 270, in parse_date_time
    te = datetime.datetime.fromordinal(helpers.tryInt(d))
ValueError: ordinal must be >= 1

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
any of you get this when try to open a show page?
using local air time - not network time.

**Comment by neoatomic** [comment]
@fernandog Was using network time.I set it to local time and did a restart. 
Open'd 4 shows and no errors.

**Comment by fernandog** [comment]
@neoatomic what is strange is the if XEM fails to load, then displayShow will fail to show the page

**Comment by TagForce** [comment]
@fernandog thexem.de is down, but my shows open normally... Well, apart from the fact that sometime during the night, the show 2 Broke Girls was renamed 2 Impoverished Girls (which is a scene name), but a full update fixed that (possibly due to thexem being down).

**Comment by fernandog** [comment]
@TagForce my shows page sometimes opens sometimes not

**Comment by fernandog** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-3.18.10-1-osmc-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@bde875f826e9bf1db5039e79936a52cfa4f359fa
Link to Log: https://gist.github.com/be721bad371763558409
### ERROR
```
Thread-208 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 1282, in displayShow
    return t.respond()
  File "/home/osmc/SickRage/cache/cheetah/_home_osmc_SickRage_gui_slick_interfaces_default_displayShow_tmpl.py", line 1314, in respond
    _v =  VFN(VFFSL(SL,"sbdatetime.sbdatetime",True),"sbfdate",False)(VFN(VFFSL(SL,"sbdatetime.sbdatetime",True),"convert_to_setting",False)(VFN(VFFSL(SL,"network_timezones",True),"parse_date_time",False)(VFFSL(SL,"epResult",True)['airdate'],VFFSL(SL,"show.airs",True),VFFSL(SL,"show.network",True))))
  File "/home/osmc/SickRage/sickbeard/network_timezones.py", line 270, in parse_date_time
    te = datetime.datetime.fromordinal(helpers.tryInt(d))
ValueError: ordinal must be >= 1

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-3.18.13-1-osmc-armv7l-with-debian-8.1**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@3565ec70dc924d8117f506983fc18a9351f487e4
Link to Log: https://gist.github.com/4454b2d23231b749c143
### ERROR
```
Thread-24 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 1296, in displayShow
    return t.respond()
  File "/home/osmc/SickRage/cache/cheetah/_home_osmc_SickRage_gui_slick_interfaces_default_displayShow_tmpl.py", line 1314, in respond
    _v =  VFN(VFFSL(SL,"sbdatetime.sbdatetime",True),"sbfdate",False)(VFN(VFFSL(SL,"sbdatetime.sbdatetime",True),"convert_to_setting",False)(VFN(VFFSL(SL,"network_timezones",True),"parse_date_time",False)(VFFSL(SL,"epResult",True)['airdate'],VFFSL(SL,"show.airs",True),VFFSL(SL,"show.network",True))))
  File "/home/osmc/SickRage/sickbeard/network_timezones.py", line 270, in parse_date_time
    te = datetime.datetime.fromordinal(helpers.tryInt(d))
ValueError: ordinal must be >= 1

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@miigotu again the same problem. If I send you my DB can you check if is DB related or not?

**Comment by miigotu** [comment]
Sure, I can check the db. We need to figure out where the bad val is getting added to the DB.

**Comment by fernandog** [comment]
haven't had this issue so far
