### ISSUE TITLE
Renaming of double episodes does not work correctly if episodes are not contiguous.

### ISSUE THREAD

**Issue by BionicSquidgy** [SiCKRAGETV/sickrage-issues#1461]
If the file is named as having two episodes that are joined, but do not follow each other in episodic numerical sequence, I think that the rename facility assumes that the file is a range and attempts to rename the file accordingly.

![image](https://cloud.githubusercontent.com/assets/12156282/7374251/0abd4af0-edc9-11e4-8a26-3bb1dfd78901.png)

**Comment by fernandog** [comment]
@BionicSquidgy IMO what is wrong is the naming pattern of the file. not SR

**Comment by BionicSquidgy** [comment]
You may be correct. The pattern looks okay though. I referenced this page http://kodi.wiki/view/TV_Shows#Multi-episode on formatting, and although the episodes are not contiguous, there is no preclusion mentioned. Note: I have noticed that Kodi doesn't handled the task very well either.
The reason for the numbering not being in numerical sequence is that these episode numbers given by TVDb that matched the titles of the two episodes in the video. I checked each one manually when it all went awry.
