### ISSUE TITLE
freshontv

### ISSUE THREAD

**Issue by dohtamoon** [SiCKRAGETV/sickrage-issues#1462]
hi i am new to SR - mainly pull tv shows from freshon. i am running SR on a streambox from bytesized. i have configured set up shows on SR, configured my user details for freshon. the problem is that no episodes are downloaded. Keep getting episode not found message - although the episode i am downloading is hosted on freshon. 

i have tried to add scene exception - no help. 

i apologise i am new here so if i need to do anything, then will need very simple step by step instructions. thanks in advance

**Comment by dohtamoon** [comment]
anybody?

**Comment by neoatomic** [comment]
Please follow the rules for posting an issue. Without data its impossible to troubleshoot.
https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket

Here you can find a good configuration guide for how to setup your settings. : 
http://www.htpcguides.com/configure-sickrage-usenet-torrent-tv/
