### ISSUE TITLE
[APP SUBMITTED]: _doSearch() got an unexpected keyword argument 'epObj'

### ISSUE THREAD

**Issue by Rock81** [SiCKRAGETV/sickrage-issues#1463]
### INFO
Python Version: **2.7.9 (default, Apr 16 2015, 21:44:36) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.3-RELEASE-p9-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/f5e5043dcc2e009ff0a8
### ERROR
```
SEARCHQUEUE-BACKLOG-83462 :: [Rarbg] :: Error while searching Rarbg, skipping: _doSearch() got an unexpected keyword argument 'epObj'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@abeloin issue?

**Comment by Rock81** [comment]
Hello i got this after i changed my rarbg.py with an updated one i found here..
my first issue was an ssl issue so i changed some things on my system, read it was a python issue.
So when that was good i got an other error. After google'ing i got on git to an updated/cleaned version of rarbg.py  so i copy pasted that into my sytem. It is searching and getting downloads from rarbg but my log still generates this error..

**Comment by fernandog** [comment]
Please use official update. Rarbg is working
