### ISSUE TITLE
[APP SUBMITTED]: CHECKVERSION :: We can't proceed with the update. New update has a old DB version. It's not possible to downgrade

### ISSUE THREAD

**Issue by kmarkou** [SiCKRAGETV/sickrage-issues#1466]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-46-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@c1c519b720acfbbc5cec7c5a89c48053e9f1b980
Link to Log: https://gist.github.com/c61e3942255687a71464
### ERROR
```
CHECKVERSION :: We can't proceed with the update. New update has a old DB version. It's not possible to downgrade
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by kmarkou** [comment]
hello 
this is the first issue that i submit.
sickrage cant auto update. if i try manual it updates without a problem.
i try master and dev with no luck

**Comment by miigotu** [comment]
You used someone else's fork or patch i assume, which upgraded your db version. The only solution is to remove your databases and recreate them.

**Comment by evonschu** [comment]
Hey so lately I've been getting this error too every time I try and update Sickrage.  Last time I backed up a copy of the database and then replaced the database with this and it resolved.  But then the next time I try to update its back again.  Any ideas how to fix this?  Rebuilding the DB for 1500 shows is not something I especially want to do.  

Thanks.

Runnin:
SR Version: 	BRANCH: (master) / COMMIT: (4d37c1352e1a27023ffd520a4da8ab0f024333e6)
SR Locale:	(None, None)
SR Config:	/Applications/SickRage-master/config.ini
SR Database:	/Applications/SickRage-master/sickbeard.db
SR Cache Dir:	/Applications/SickRage-master/cache
SR Log Dir:	/Applications/SickRage-master/Logs
SR Arguments:	[]
Python Version:	2.7.8 (v2.7.8:ee879c0ffa11, Jun 29 2014, 21:07:35) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

**Comment by miigotu** [comment]
@evonschu best you can do is enable kodi 12+ metadata so that the shows auto add back without intervention on rebuild. Next time dont use some idiots fork who upgrades database randomly.
