### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-176941 :: Unable to parse Sherlock.Season.2.BRRip.x264.720p-NPW into a scene name. If it's a valid one log a bug.

### ISSUE THREAD

**Issue by calimada** [SiCKRAGETV/sickrage-issues#1468]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-176941 :: Unable to parse Sherlock.Season.2.BRRip.x264.720p-NPW into a scene name. If it's a valid one log a bug.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Please add the full log.
