### ISSUE TITLE
[APP SUBMITTED]: [Errno 18] Invalid cross-device link

### ISSUE THREAD

**Issue by oodonnell** [SiCKRAGETV/sickrage-issues#1469]
### INFO
Python Version: **2.7.3 (default, Mar 23 2014, 01:44:56) [GCC 4.6.3]**
Operating System: **Linux-3.0.101.RN_ARM.3-armv7l-with-debian-7.7**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/e6adb8a7bc989563ded9
### ERROR
```
POSTPROCESSER :: Failed to create hardlink of /data/Transmission/Downloads/Gotham.S01E21.1080p.HDTV.X264-DIMENSION/Gotham.S01E21.1080p.HDTV.X264-DIMENSION.mkv at /data/Videos/Tv Series/Gotham/Gotham S01 E21.mkv: error 18 : Invalid cross-device link. Copying instead
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
You cannot make hard links from one partition to another. Either move your downloads to the same partition as your library, or use soft links.

**Comment by fernandog** [comment]
@miigotu is there a way to check this before use select PP method?

**Comment by miigotu** [comment]
There is sort of a way, its a little hacky imho tho.  Better to put a note on the UI in red saying that hard links must be to the same partition or w/e.

Anyways, as long as you have the download_dir and the shows_dir:
```
def canHardLink(src, dst):
    while not os.path.ismount(src):
        src = os.path.dirname(src)
    while no os.path.ismount(dst):
        dst = os.path.dirname(dst)
    return src == dst
```

**Comment by oodonnell** [comment]
sorry I have no idea why this was submitted until I just seen it in my emails, I got this error as I was trying to post process a file that had not been fully downloaded properly, sorry for this being a total waste of your time 

I had done a submit error on the SSL error and this must've popped in there by accident.
