### ISSUE TITLE
Going Clear will not add

### ISSUE THREAD

**Issue by berrmich** [SiCKRAGETV/sickrage-issues#1470]
I can not get Going Clear to add.  I can find it on the TVBD but it will not find it when I search that indexer.  It will find it on tvrage, however, when I try to add it I get:  2015-04-28 22:20:14 SHOWQUEUE-ADD :: Unable to find show ID:48214 on Indexer: TVRage

**Comment by miigotu** [comment]
Going Clear is not on theTVDB. See this:
http://thetvdb.com/?string=going+clear&searchseriesid=&tab=listseries&function=Search

It is on TVRage as `Going Clear: Scientology and the Prison of Belief`

It is incorrectly added on TVRage, the episode number is S01-#1 in their meta. Fix it there.

**Comment by miigotu** [comment]
AAtvrage_error: Connection error ('Connection aborted.', error(104, 'Connection reset by peer')) while loading URL http://services.tvrage.com/myfeeds/showinfo.php
AA    raise tvrage_error(e)
AA  File "/media/2TB/SickRage/lib/tvrage_api/tvrage_api.py", line 512, in _getetsrc
AA    self.config['params_seriesInfo']
AA  File "/media/2TB/SickRage/lib/tvrage_api/tvrage_api.py", line 603, in _getShowData
AA    self._getShowData(key, True)
AA  File "/media/2TB/SickRage/lib/tvrage_api/tvrage_api.py", line 684, in __getitem__
AA    s = t[self.indexer_id]
AA  File "/media/2TB/SickRage/sickbeard/show_queue.py", line 263, in run
AATraceback (most recent call last):
2015-04-29 19:11:42 ERROR    SHOWQUEUE-ADD :: Unable to find show ID:48214 on Indexer: TVRage
2015-04-29 19:06:57 INFO     SHOWQUEUE-ADD :: TVRage: {'apikey': 'Uhewg1Rr0o62fvZvUIZt', 'cache': '/media/2TB/SickRage/data/cache/indexers/TVRage', 'language': 'en'}
2015-04-29 19:06:57 INFO     SHOWQUEUE-ADD :: Starting to add show /media/2TB/Videos/Shows/Going Clear Scientology and the Prison of Belief

**Comment by fernandog** [comment]
@miigotu we should show only str(e) instead of traceback()

**Comment by miigotu** [comment]
@fernandog I agree, empty episode lists sometimes return from tvdb/tvrage and cause this. So I think we should also fix it where its returned empty. I saw a commit about it on SickGear I'll try to find it later.

**Comment by fernandog** [comment]
@miigotu please check with them if we can use the code please.

**Comment by miigotu** [comment]
@fernandog we dont need permission to use open source code, we just have to provide credit, and proper licenses.

**Comment by berrmich** [comment]
is there a way to manually add this show?

-Mike

**Comment by miigotu** [comment]
@berrmich yeah, fix the episode number on tvrage. s01x#1 is not valid.
