### ISSUE TITLE
[APP SUBMITTED]: 'utf8' codec can't decode byte 0x88 in position 1465: invalid start byte

### ISSUE THREAD

**Issue by dirkr07** [SiCKRAGETV/sickrage-issues#1474]
### INFO
Python Version: **2.7.9 (default, Mar 22 2015, 23:46:21) [GCC 4.3.2]**
Operating System: **Linux-2.6.32.12-ppc-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-264030 :: DownloadStation: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@dirkr07 use the "admin" account. If you create a new account be sure the permissions and a download folder for download station is set.
