### ISSUE TITLE
Existing episode not found by Sickrage

### ISSUE THREAD

**Issue by razlebol** [SiCKRAGETV/sickrage-issues#1475]
Added the file with the right name and structure in the tv show folder and Sickrage just won't reconize it as downloaded. 

For example, I have Californication - S03E01 - Wish You Were Here.mkv is the /Californication/Season 03/ folder and sickrage is not able to see that I have it.

**Comment by miigotu** [comment]
Select the show, and pick 'Force Full Update' at the top right of the screen. It will rescan episodes from disk.
