### ISSUE TITLE
[Feature Request] Replace higher "Initial Quality" with lower "Archive Quality"

### ISSUE THREAD

**Issue by kotysoft** [SiCKRAGETV/sickrage-issues#1479]
Hi,
Firstly thanks for your time to develop a kind of superb and useful thing, like SickRage!
And thanks for your time in advance to answer my question.

### What I did
- Set **CUSTOM** quality to a specific TV show.
- Set **INITIAL QUALITY** to *SD TV, SD DVD, HD TV, 1080p HD TV, 720p WEB-DL, 1080p WEB-DL, 720p BluRay, 1080p BluRay, Unknown*
- Set **ARCHIVE QUALITY** to *SD DVD, HD TV*
- **ARCHIVE ON FIRST MATCH:** true

### What I expect
- I'd like to download first available episode as soon as possible (in any quality)
- And then once *SD DVD* or *HDTV* available I'd like to replace the downloaded one with that, even if the first download is better quality than the archive one.

For example the first available quality is 1080p, SickRage downloading it, but I'd like to replace it with SD DVD quality.

### What happened
Sickrage ignoring the lower quality files:
- not snatching once available
- and when I download it manually, it's ignoring at manual postprocessing

## System informations
**Sickrage:** master / 5ef5a0b27e27cf937011408cb55329d1bd21ce9d
**Python:** 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
**OS:** Windows 7 Ultimate x64 HUN

**Comment by tppinheiro** [comment]
I'd like to join my voice for this feature as well. Very useful if you want to keep a small size, retail version of a show.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
