### ISSUE TITLE
[Question] Python on Synology NAS DSM 5.1 update 5

### ISSUE THREAD

**Issue by gborri** [SiCKRAGETV/sickrage-issues#1480]
hello all owner of synology HW. I have just bought one. I'm trying to install python 2.7.x but i can't find it. someone can help? thanks

**Comment by neoatomic** [comment]
@gborri 
http://www.htpcguides.com/screenshot-guide-to-install-sickrage-on-synology-nas/

**Comment by gborri** [comment]
@neoatomic

Thanks, but i can't find nor python neither git. I have installed
synocommunity source. I can only find python 3 and git server.

Il giorno ven 1 mag 2015 00:20 neoatomic <notifications@github.com> ha
scritto:

**Comment by neoatomic** [comment]
@gborri Git Server is the name of the official Synology pack. So not the correct one.

If you have added synocommunity correctly you need to look under "community" for py and git.
When they are not there, you ether have not added synocommunity or you have not set the option "Any publisher" under Trust Level. (see guide) 
Its very easy and straight forward. Must be one of those two.

**Comment by gborri** [comment]
no way. i have checked the config and seems ok. But i can find only version
3.

**Comment by neoatomic** [comment]
@gborri If you added Synocommunity correctly you should see sickbeard-custom under "community". Do you see it.? 
Can you post some screenshots.?

**Comment by gborri** [comment]
@neoatomic i don't know why but it's appeared....

**Comment by neoatomic** [comment]
@gborri Glad to hear, maybe there was some maintenance.?
Synology's are awesome devices, hope you enjoy yours. :)

**Comment by gborri** [comment]
@neoatomic thanks.
