### ISSUE TITLE
SickRage is downloading episodes i don't want to be dowloaded

### ISSUE THREAD

**Issue by trotskylenin** [SiCKRAGETV/sickrage-issues#1483]
Hello, this issue is strange, since that i don't get an error for it and can't provide of a significant data log... 
It's like SickRage is ignoring my default settings for some series. I noted that when some of the new episodes of Mythbusters started downloading automatically even if i set the default episode status option as "Skipped".
Is this an issue or just that SickRage has life on its own? :|
Hahaha just kidding.
Hope you can help me.

**Comment by selthius** [comment]
I believe that the default episode status is only considered when you are adding the show to Sickrage, whether or not it should look for the previous episodes. Sickrage will automatically download any new episodes that airs, because that is its job. If there is enough support for this it might be implemented, but for now i suggest you just remove the show when you aren't looking for new episodes.

**Comment by trotskylenin** [comment]
That's not what the option says:

![image](https://cloud.githubusercontent.com/assets/6507464/7442531/06f84dae-f0ec-11e4-9665-f0b0265363d5.png)

I migrated from the now defunct "Sickbeard The Pirate Bay" edition to SickRage and the both of them worked that way in the beginning (Skipping new episodes if the default option is set to "skipped")

**Comment by selthius** [comment]
Sorry, didn't bother actually checking since it has been like this as long as i remember. This should definitely be fixed. Hopefully someone can fix your problem as well.

**Comment by trotskylenin** [comment]
I would be glad to help. I'm going to try to fix it on my own when i have a time and send a pull request.
Even if i'm not a developer, I have some notions of programming in python so i think i can read the code and fix it eventually.

**Comment by fernandog** [comment]
@trotskylenin looks like the problem is here:

https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/tv.py#L109

can you stop SR, edit that file, change to WANTED, save, and test please?

**Comment by trotskylenin** [comment]
Hi Fernando, is there something i can do to help fixing this?

**Comment by Thraxis** [comment]
@fernandog @trotskylenin 

The section of code responsible for this is below:

https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/tv.py#L1756-L1790

It specifically only sets the default status if the status is UNKNOWN.  Which is already changed if he show is unaired / etc by the time it gets to that piece of code.

Could easily change it to set change the status regardless of if it is unknown or not.  Let me know and I can PR it

**Comment by trotskylenin** [comment]
It looks like that's the place where the bug is... i don't see anything wrong with the dailysearcher line that Fernando says.
Thank you very much Thraxis! PR it please.

**Comment by selthius** [comment]
There seems to be some inconsistency though. This option is being set when adding the show, with the text "Set the status of already aired episodes". This means that there should be two dropdowns, the one currently implemented which needs to be changed to just set the status of already aired episodes, and another to set a variable for whether or not this show should snatch new episodes.

**Comment by fernandog** [comment]
I have a paused show that everytime the unair episodes get's aired, SR change to SKIPPED.
another issue maybe?
My issue is related to the code I posted

**Comment by trotskylenin** [comment]
This is not the same problem @fernandog ... 
My shows aren't paused... that option works with Trakt integration too, that's why it changes to Skipped, and i think that behaviour is okey, because Skipped status should be the default one for unaired episodes when the show is paused.
My problem is the one that @selthius mentions, Sickrage is just considering the default episode status option for unaired episodes that gets aired when they're with UNKNOWN status - that is, never.

**Comment by fernandog** [comment]
@trotskylenin if is pause, when you unpause it won't download it because they are all SKIPPED. I think it should get the setting of "default ep status" for earch show (in my case, wanted)

**Comment by Thraxis** [comment]
If the show was paused it shouldn't be getting processed at all No updates, No status changes, No downloads (other then manual)

**Comment by Thraxis** [comment]
@fernandog Bit of a minor issue.  the default status on all my shows is currently "skipped"...  if I make the change as it in theory should be.  this is going to make a lot of peoples systems stop downloading without understanding why.  Might be able to add in a database update to make the default status "unaired" but will need some feedback on this

**Comment by trotskylenin** [comment]
@thraxis i'm a bit lost... are you talking about this issue or the one of @fernandog ? 
If you can set the default status for episodes when you add the show, then it's normal that if you chose Skipped then nothing should be automatically downloaded.

**Comment by trotskylenin** [comment]
@selthius you're right with that one... it's not pretty clear the "Set the status of already aired episodes." sentence when you add the show. Maybe it should be just "Set the default status for episodes."
I don't know if adding a second option to decide what to do just with unaired episodes should be needed... but could be proposed as a feature request.

**Comment by fernandog** [comment]
so what we should do with this one?

**Comment by fernandog** [comment]
I  think if you add a show and don't want any FUTURE download you should set as PAUSE
If you don't want the already aired episodes you should choose "SKIPPED" in the default ep status

the label "(this will set a default status to be applied to any newly added episodes)" is wrong. should be changed to the same label as in ADD SHOW "Set the status of already aired episodes"

**Comment by fernandog** [comment]
also this options shouldn't appear in "edit show" as there's no sense add it there. it only usefull when adding show

@miigotu what do you think?

**Comment by fernandog** [comment]
Feature request to set default status of the UNAIRED episodes

**Comment by trotskylenin** [comment]
@fernandog Yes, please. I think that would be great. The pause option is too much, i want to get updates of the show and more... i just don't want to download automatically every new episode... an option to set default status of Unaired episodes that gets aired is needed.

**Comment by OlleDenStore** [comment]
This is really annoying. The only way to get new shows to download automatically is to add them with default episode status: wanted, and then super quickly set all the old episodes to skipped before it SR starts downloading them. If you aren't fast enough you get stuck having to seed old episodes(at least with my search provider).
It would be great if this could be made a priority for the next update.

**Comment by fernandog** [comment]
@OlleDenStore set default to ignored. then go to show page set the ones (already aired) you want as wanted. new episodes will be set as wanted automatic by SR

**Comment by OlleDenStore** [comment]
Ok, I just tried that. I'll see tomorrow if it works. What concerns me a bit is that the default Ep status for the show is listed as Ignored when I check it under Manage -> Mass Update.
Thanks a lot for the quick response!
