### ISSUE TITLE
[APP SUBMITTED]: [Errno 1] _ssl.c:507: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

### ISSUE THREAD

**Issue by Imnotgoodathis** [SiCKRAGETV/sickrage-issues#1484]
### INFO
Python Version: **2.7.6 (default, Jan 29 2014, 07:56:46) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-281662 :: [TorrentDay] :: Error while searching TorrentDay, skipping: error [Errno 1] _ssl.c:507: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors
