### ISSUE TITLE
Can't browse dirs containing accented characters.

### ISSUE THREAD

**Issue by belima** [SiCKRAGETV/sickrage-issues#1486]
Python Version: 2.7.9
Operating System: Windows 8.1
Locale: ('pt_BR', 'cp1252')
Branch: master
Commit: SiCKRAGETV/SickRage@5ef5a0b
There's nothing related to this issue in sickrage.log

Hello everyone!
When trying to configure SR, I can't browse directories with accented characters in their names.
It's a problem to me since my user folder has an accented character in it's name and both my downloads and  TV Shows folder are inside my user dir.

e.g. When adding a New Show Root Directory, I can select "C:\", then "Users", but, when I click "Bê" (that's my user folder) nothing happens at all.

I tried with differente folders and the problem is def related to the accented chars..

I don't think it's some system related problem since I used Pistachito's SickBeard for a long time and never had problems concerning accented chars in folder names.

Hope you guys can help me ;)

**Comment by fernandog** [comment]
before run SR please run 

```
CHCP 65001
```

**Comment by belima** [comment]
Thanks for the answer, but it didn't work! =/
