### ISSUE TITLE
[APP SUBMITTED]: Failed Unrar archive the.goldbergs.2013.s02e22.proper.720p.hdtv.x264-fihtv.rar: Unrar: Archive CRC Error

### ISSUE THREAD

**Issue by bmatulovich** [SiCKRAGETV/sickrage-issues#1488]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:38) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-51-generic-i686-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/ff602d9e22812f2b922f
### ERROR
```
POSTPROCESSER :: Failed Unrar archive the.goldbergs.2013.s02e22.proper.720p.hdtv.x264-fihtv.rar: Unrar: Archive CRC Error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by firatuzman** [comment]
Possibly long full path + file name.  I recently got the CRC Error in windows while extracting a rar file for the same reason. If this is the case, not sickrage issue. Move the rar to a folder with shorter path and try again.
Hope this helps.

**Comment by bmatulovich** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:38) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-53-generic-i686-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@bf2baf309bd01683fdc06d57ece0b89d53b4a180
Link to Log: https://gist.github.com/11bc5fb969500fe0c012
### ERROR
```
POSTPROCESSER :: Failed Unrar archive the.goldbergs.2013.s02e22.proper.720p.hdtv.x264-fihtv.rar: Unrar: Archive CRC Error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
