### ISSUE TITLE
[APP SUBMITTED]: RSSFeeds instance has no attribute 'rssDB'

### ISSUE THREAD

**Issue by dragonrm** [SiCKRAGETV/sickrage-issues#1493]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.8+-armv6l-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/a027f2897001b552d80c
### ERROR
```
SEARCHQUEUE-BACKLOG-266189 :: [Sick Beard Index] :: Error while searching Sick Beard Index, skipping: RSSFeeds instance has no attribute 'rssDB'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1514

**Comment by miigotu** [comment]
Sick Beard Index is no longer working. Disable it and use some other nzb index.
