### ISSUE TITLE
[APP SUBMITTED]: Connection error ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host')) while loading URL http://services.tvrage.com/myfeeds/showinfo.php

### ISSUE THREAD

**Issue by valkhyr1** [SiCKRAGETV/sickrage-issues#1496]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: TVRage timed out, unable to update episodes from TVRage
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by pierre2013** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@1ec701e4c12b41d1a34f01ad6091b1fec09967a3
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: TVRage timed out, unable to update episodes from TVRage
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
