### ISSUE TITLE
[Feature Request] Replace Cheetah/Python 3.x Porting

### ISSUE THREAD

**Issue by miigotu** [SiCKRAGETV/sickrage-issues#1497]
I think it would be a strong move to start thinking about porting SickRage to Python 3.x.  Not only has the Python Core Dev Team officially stopped supporting 2.6, this would eliminate our SSL/SNI headaches, remove half of our self-distributed libs, and make for an overall smoother application.
We also would benefit from the fact that almost every distro has Python 3.x readily available, as well as new/better modules, and would have much less headache helping users get it installed optimally.

The main thing holding us back is Cheetah, which hasn't been updated in 5 years, does not support Python 3.x, and never will.  This will require our current web-ui templates to be either reworked, or rewritten to use a new templating engine.

Up for discussion would be which templating engine should we pick. It should have at least basic requirements:

* Actively Developed
* Fast and lightweight
* Simple to use
* Work with the newest Python 3.x version

My nominee: 
Jinja2:  Works with Python 2.6.x, 2.7.x and >= 3.3, used by Mozilla, SourceForge, Instagram so it will be actively worked on upstream. Since 2.7 is also supported, we don't need to make the bump to 3.x immediately. Anyone familiar with jinja2?

**Comment by Thraxis** [comment]
Pretty sure they already replaced Cheetah with Tornado....

**Comment by miigotu** [comment]
While you can use tornado to handle templates [(See Here)](http://tornado.readthedocs.org/en/latest/template.html), it doesn't cache templates, and doesn't parse cheetah templates directly. 

What you are probably thinking of is when they replaced CherryPy with Tornado (Good Move).

**Comment by miigotu** [comment]
@SiCKRAGETV/moderators Maybe we could add an 'experimental-broken' branch to work on this?

I decided that jinja2 is a no-go (at least for me) because the amount of work to switch over would be insane. You cant embed full python in jinja2 templates.

I have started swapping in mako, which I have switched out almost 100% in webserve.py (enough to load templates with mako), and have started in on home.tmpl after copying gui/slick to gui/mako.

Mako syntax is not too different, but its a lot of search/replace by regex, then manually going through the file, and then debugging. I need some help.

Mako is similar speed to cheetah, has caching and filters and whatnot, and is actually what the #2dev from Cheetah is using now.

**Comment by miigotu** [comment]
Also, after converting the cheetah templates to mako, we are pretty much python3 ready.

**Comment by fernandog** [comment]
the problem with that is Raspberry Pi OS (OSMC, Raspbmc, Raspian, OpenElec) don't support python3. Don't know about NAS but pretty sure they don't use python3 also

**Comment by neoatomic** [comment]
Synology has a python 3 package that can be installed. Out of the box only python2
But as most other projects (sabnzb, couchpatato.?) use python 2 you would be needing to install both versions as they are not backwards compatible if i recall correctly.?

I would definitely want echel0n input before we consider this change.

**Comment by miigotu** [comment]
@neoatomic with this change, it would run on 2.6, 2.7, and 3.x.

**Comment by miigotu** [comment]
python3 is a separate milestone. mako is working fairly well, yet we are still doing normal improvements. closed!
