### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-248736 :: Unable to load url http://dutplanet.net/239474, can't download season NZB

### ISSUE THREAD

**Issue by GodZZila** [SiCKRAGETV/sickrage-issues#1498]
### INFO
Python Version: **2.7.6 (default, Apr  3 2014, 09:45:36) [GCC 4.5.3]**
Operating System: **Linux-3.4.80-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-248736 :: Unable to load url http://dutplanet.net/239474, can't download season NZB
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
its a problem with that site
