### ISSUE TITLE
Error when opening a specific show

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#15]
<a href="https://github.com/Rido"><img src="https://avatars.githubusercontent.com/u/1889864?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Rido](https://github.com/Rido)**
_Tuesday Nov 25, 2014 at 20:32 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/951 (1 comment(s))_

----

Hi,

When I open an specific show I'm getting the following error: https://gist.github.com/Rido/f5c1f26d879974205fb8

What Branch? **Develop**
Latest Commit hash ** 468af14dfd03c043813b20afb3da97e33a7b29b9**
Your operating system, browser and python version **Synology with Python 2.7.8**
What you did? **Trying to open a show**
What happened? **I received an error**
What you expected? **I want to see the specific show page**

**Comment by fernandog** [comment]
@Rido still having this issue?

**Comment by fernandog** [comment]
@Rido please reply otherwise will close this
