### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by javelin4effect** [SiCKRAGETV/sickrage-issues#1503]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.14.37-grsec-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/92d14866bdb7f1c66e9a
### ERROR
```
Thread-62 :: Unable to run synoindex: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Either you dont have the synoindex executable, or you provided the wrong path to it. Check your system that it exists and set the right path.
