### ISSUE TITLE
Alignment issues on TV Show view page

### ISSUE THREAD

**Issue by adampetrovic** [SiCKRAGETV/sickrage-issues#1504]
The search icon used to be centered in the td. This bug was introduced by: https://github.com/SiCKRAGETV/SickRage/commit/97ec17384791fe9a58cf932d3d43100355e13391

![screen shot 2015-05-04 at 3 30 40 pm](https://cloud.githubusercontent.com/assets/88030/7449146/8da4a712-f272-11e4-9401-54d8ea12bac3.png)

**Comment by miigotu** [comment]
@adampetrovic Fixed, PR awaiting merge.
