### ISSUE TITLE
[APP SUBMITTED]: Thread-55 :: git pull -f origin master returned : From https://github.com/SiCKRAGETV/SickRage
 * branch            master     -> FETCH_HEAD
error: unable to create file autoProcessTV/lib/__init__.py (Permission denied)
Updating 1b453df..7af9a84

### ISSUE THREAD

**Issue by pavak1** [SiCKRAGETV/sickrage-issues#1506]
### INFO
Python Version: **2.7.6 (default, Jan 29 2014, 07:56:46) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.2-RELEASE-p10-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@1b453df9d404c38c4b17b72c7d977cce26c3c498
Link to Log: https://gist.github.com/442840a249743b2a6d31
### ERROR
```
Thread-55 :: git pull -f origin master returned : From https://github.com/SiCKRAGETV/SickRage
 * branch            master     -> FETCH_HEAD
error: unable to create file autoProcessTV/lib/__init__.py (Permission denied)
Updating 1b453df..7af9a84
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@miigotu problem with relative path or some permission user must check?

**Comment by miigotu** [comment]
Cloned as one user, and running SR as another user. Either run SR as the same user you cloned SR with, or recursively chown the source to the user you are running SR as.
