### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-75760 :: Check scene exceptions update failed. Unable to get URL: https://raw.githubusercontent.com/echel0n/sb_tvrage_scene_exceptions/master/exceptions.txt

### ISSUE THREAD

**Issue by hulubi** [SiCKRAGETV/sickrage-issues#1507]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@7af9a845c324bd0b0698da0ae85b68b54568f6e1
Link to Log: https://gist.github.com/4d75736093d7dbbef514
### ERROR
```
SEARCHQUEUE-BACKLOG-75760 :: Check scene exceptions update failed. Unable to get URL: https://raw.githubusercontent.com/echel0n/sb_tvrage_scene_exceptions/master/exceptions.txt
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
[SSL Errors](https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors)
Upgrade your modules using that info.
