### ISSUE TITLE
Inconsistent episode renaming

### ISSUE THREAD

**Issue by medariox** [SiCKRAGETV/sickrage-issues#1508]
Python Version: 2.7.9 (default, Apr 27 2015, 23:15:34) [GCC 4.8.2]
Operating System: Ubuntu 14.04 x64
Locale: unknown
Branch: master
Commit: SiCKRAGETV/SickRage@7af9a84

As 'Name Pattern' I use S%0S/%RN, it should result in S02/Show.Name.S02E03.HDTV.XviD-RLSGROUP.ext

Sometimes the episodes are named like this:
```
my.tv.show.204.hdtv-haha.mp4
```
and sometimes like this:
```
My.Tv.Show.S02E02.HDTV.x264-HAHA.mp4
```

Is %RN supposed to be like that? To my understanding it should always be Show.Name.S02E03.HDTV.XviD-RLSGROUP.ext, is this correct?

**Comment by EqUaTe** [comment]
Try this instead:
S%0S/%S.N.S%0SE%0E.%E.N.%Q.N-%RG

I get consistent results with the above.

**Comment by medariox** [comment]
Thanks for the suggestion @EqUaTe 
I had S%0S/%S.N.S%0SE%0E.%QN-%RG for for a while, sadly this results in (notice the space):
```
S02/Show.Name.S02E03.HD TV-RLSGROUP.ext
```
and you suggestion S%0S/%S.N.S%0SE%0E.%Q.N-%RG results in (notice the point in HDTV):
```
S02/Show.Name.S02E03.Ep.Name.HD.TV-RLSGROUP.ext
```
I know that's a bit nitpicking, but both solutions are not exactly what I'd would like to achieve.

You are right about %RN, it just keeps the original file name, which results in the inconsistency explained in my first post (not optimal).
A feature that could be implemented (don't even know why it isn't like that in the first place) is e.g. %QN, %SN being renamed to
```
HDTV, ShowName
```
instead of the default behavior which always contains a space, we could just use e.g. %Q^N, %S^N for the version version with space. Like that we could achieve more or less any kind of file renaming.

**Comment by EqUaTe** [comment]
Ok, I see where you're coming from now :)
Yeah, the . did annoy me to start with, but as Kodi tends to read the NFO and replace the file name with the ep name, I've kinda gotten used to ignoring it.

That being said, in the event I get a bit of time, I may take a look at modifying this feature and submitting a pull request.
It does make sense to me that %QN should not contain a space by default. Not sure what the dev team think, but if I get a pull request in I guess we'll find out :)

**Comment by medariox** [comment]
I'm glad to see that I'm not the only one bothered by this "issue". :)
I might try something myself in the next days, if I get some time.

**Comment by miigotu** [comment]
`%QN` Will still have a space in some qualities.
`%Q.N` Will now not have spaces in any HDTV or SDTV parts of quality strings. SD DVD for example would be SD.DVD though, which I think doesn't look as silly as `HD TV`, so I didn't change that one.

**Comment by medariox** [comment]
Thanks for the quick fix @miigotu !

**Comment by EqUaTe** [comment]
Nice one @miigotu . I agree that having %Q.N still put the dots in makes sense - otherwise it would just be a bit odd to have the option. Fairly sure I used that because I didn't want spaces, but it's from so long ago I don't really remember!

Sleep well :)

**Comment by miigotu** [comment]
@medariox I have to rewrite a bunch of junk in sickbeard/common.py for this to work. On the plus side, it doesnt seem to be very accurate determining qualities as it is, so I hope to improve that.

**Comment by miigotu** [comment]
@medariox maybe I have it, I hope I didn't break anything. SiCKRAGETV/SickRage#1885

**Comment by miigotu** [comment]
@medariox you can test this easily, with:

`curl -k -L https://github.com/SiCKRAGETV/SickRage/pull/1885.patch | git am`

After testing it, simply `git reset --hard` to return to pre-patched state.

**Comment by medariox** [comment]
Ok, I made some testing with your patch @miigotu 

Testing with this name pattern: S%0S/%S.N.S%0SE%0E.%QN-%RG

First file <b>my.tv.show.204.hdtv-haha.mp4</b> got renamed to:
```
My.Tv.Show.S02E04.HDTV-haha.mp4
```
The problems here: 
- Group is still lowercase, although %RG
- The show gets recognized as HDTV although it should be SDTV! (The title should still be HDTV, as it defines the file source!)
- Encoder information missing (x264) - I know this is not even supposed to be there, but a setting for encoder would be really good, like e.g. %EN

Second file <b>My.Tv.Show.S02E02.HDTV.x264-HAHA.mp4</b> got renamed to:
```
My.Tv.Show.S02E02.SDTV-HAHA.mp4
```
The problems here:
- The title got renamed to SDTV, this is wrong as it defines the source of the file. The category should still be SDTV.
- The encoder information got stripped (still need an encoder option here)

Problem with UI: 
- CSS seems to be broken with the patch (color):
![alt text](https://snapr.pw/i/428db89bf4.png "UI problem")

That's all I can report for now.

What I'd really like to achieve at least is proper scene naming, which looks like, e.g.:
```
My.Tv.Show.S02E02.HDTV.x264-HAHA.mp4
My.Tv.Show.S01E05.720p.HDTV.x264-HAHA
```
 
Thanks again Dustyn, I hope we can make this happen!

**Comment by Quiksmage** [comment]
I'm unsure if this re-opens the issue, but the older file name HD TV is no longer recognized in the postprocessor. It comes up as unknown. Fixing this would require me to change the name of every episode sickrage has named.

**Comment by miigotu** [comment]
i may have to revert that change....

**Comment by Quiksmage** [comment]
This only appears to affect "HD TV". I tested "SD TV" and it detects fine following the changes removing the space between both "HD TV" and "SD TV".

**Comment by miigotu** [comment]
Because SD is detected fine with just SD.

**Comment by Quiksmage** [comment]
gotcha

**Comment by miigotu** [comment]
Still trying to decide if any other issues are caused by my changing these quality names. If this is the only thing, I can just add another regex to detect "HD TV" when post/pre processing

**Comment by syd3n** [comment]
I am having the same issue with files that have "HD TV" in the name are being detected as unknown quality.

**Comment by miigotu** [comment]
@syd3n Those that arent re-processed are only ones that were previously renamed by SR correct? because "HD TV" is not a valid scene quality, only SR used that to get around a difficulty before. If it is just previously renamed files, on linux you can mass rename files easily.

**Comment by syd3n** [comment]
These were files that were previously post-processed by a different fork of Sickbeard that used "HD TV" in the file names to denote HDTV quality. I just switched to SickRage and am finding that all my files that are in "HD TV" quality are being detected as unknown.

I guess I can try to mass rename...but I have over 4000 files on various drives/folders, all of which have already been scraped into multiple media libraries for xbmc/kodi, etc.

If "HD TV" is not being used by SR as a valid scene quality by design and I have no other recourse, then I will go the mass rename route.

**Comment by miigotu** [comment]
@syd3n If you are on linux you can rename all files with the failed strings in one line:
`find /YourShowDir/ -type f -exec rename 's/HD TV/HDTV/' '{}' \;`
`find /YourShowDir/ -type f -exec rename 's/SD TV/SDTV/' '{}' \;`

**Comment by miigotu** [comment]
@syd3n Before renaming, be sure to export your library in kodi to separate files, to save watched status/etc. Rename, then clean and update library.

**Comment by syd3n** [comment]
will try that, thanks!
