### ISSUE TITLE
[APP SUBMITTED]: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by oodonnell** [SiCKRAGETV/sickrage-issues#1509]
### INFO
Python Version: **2.7.3 (default, Mar 23 2014, 01:44:56) [GCC 4.6.3]**
Operating System: **Linux-3.0.101.RN_ARM.4-armv7l-with-debian-7.8**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@944a1eb92c41139272fc6ab47822eb1be8091ded
Link to Log: https://gist.github.com/41958f4b898a5f922229
### ERROR
```
Thread-50 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/root/sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/home/root/sickrage/sickbeard/webserve.py", line 2860, in changeEpisodeStatuses
    self.setStatus(cur_indexer_id, '|'.join(to_change[cur_indexer_id]), newStatus, direct=True)
  File "/home/root/sickrage/sickbeard/webserve.py", line 1697, in setStatus
    epObj = showObj.getEpisode(int(epInfo[0]), int(epInfo[1]))
ValueError: invalid literal for int() with base 10: ''

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@oodonnell please full update all your tv-shows (mass update)
