### ISSUE TITLE
[APP SUBMITTED]: Thread-47 :: Local branch is ahead of master. Automatic update not possible.

### ISSUE THREAD

**Issue by oodonnell** [SiCKRAGETV/sickrage-issues#1510]
### INFO
Python Version: **2.7.3 (default, Mar 23 2014, 01:44:56) [GCC 4.6.3]**
Operating System: **Linux-3.0.101.RN_ARM.4-armv7l-with-debian-7.8**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@944a1eb92c41139272fc6ab47822eb1be8091ded
Link to Log: https://gist.github.com/adfd90d9cc34fda44dc5
### ERROR
```
Thread-47 :: Local branch is ahead of master. Automatic update not possible.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
This happened form using someone else's branch. Do this: 
```
git remote set-url origin https://github.com/SiCKRAGETV/SickRage.git
git fetch origin
git reset --hard bcde7b4f
git pull
```
