### ISSUE TITLE
[Feature request] Add Proxy Server PPTP/L2TP/SOCK Support

### ISSUE THREAD

**Issue by donk2901** [SiCKRAGETV/sickrage-issues#1511]
Hi I recently been having some issues with Open VPN and wanted rto ask how difficult it would be to add Proxy authentication to the Sickrage general configuration page. Since I am using PIA INternet access I would like to just place sickrage onto an authenticated proxy socks 5 rather then Open VPN the entire server. 

or how can i import into the config .ini i dont want to mess about to much incase i break it 

thanks in advance and keep up the good work guys

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
