### ISSUE TITLE
UnicodeDecodeError in log, but not in log error page : no downloads

### ISSUE THREAD

**Issue by djack42** [SiCKRAGETV/sickrage-issues#1512]
Automatic search and manual search fail for some time for me, no errors but each time i do a manual search on a released episode, the following error appears in log view but not in error view.
And no downloads.

From gist : https://gist.github.com/djack42/c5438dd9742767ea0553
*AAUnicodeDecodeError: 'utf8' codec can't decode byte 0xa9 in position 9062: invalid start byte
* SEARCHQUEUE-MANUAL-281623 :: [Rarbg] :: Error while searching Rarbg, skipping: UnicodeDecodeError('utf8', '<!DOCTYPE html PUBLIC 

Configuration
SR Version:	BRANCH: (master) / COMMIT: (7af9a845c324bd0b0698da0ae85b68b54568f6e1) 
SR User:	root
SR Locale:	('en_US', 'UTF-8')
SR Config file:	/opt/sickbeard/config.ini
SR Database file:	/opt/sickbeard/sickbeard.db
SR Cache Dir:	/opt/sickbeard/cache
SR Log Dir:	/opt/sickbeard/Logs
SR Arguments:	['-q', '--daemon', '--nolaunch', '--datadir=/opt/sickbeard']
Python Version:	2.7.9 (default, Apr 29 2015, 19:33:17) [GCC 4.8.3 20140401 (prerelease)]

**Comment by fernandog** [comment]
@djack42 disable proxy
