### ISSUE TITLE
Unable to find a download for since 1/5

### ISSUE THREAD

**Issue by sepperrs** [SiCKRAGETV/sickrage-issues#1514]
Hi all , 

ever since the latest update i've done , sickrage doesnt find any episode any longer. 
Nothing has changed on the configuration except for the update. 
The search actually does return a correct XML file , where i'll see the file i want to snatch. 

My log was set to debug and i see no errors , the search passes and it just returns nothing. 

branch : master
cur commit : 7af9a845c324bd0b0698da0ae85b68b54568f6e1
OS : Debian 7
python : Python 2.7.3

What happened : attempt to snatch episode
What you expected : result found

log:
https://gist.github.com/sepperrs/018376fe1dbf01698fac#file-gistfile1-txt

apoligies if this has already been reported.

**Comment by miigotu** [comment]
A. lolo.sickbeard.com is inoperational.
B. Your log file is incomplete.

**Comment by sepperrs** [comment]
You're correct on the lolo.sickbeard being inoperational. This is now disabled. 

About the log file , I dont really know what else would be useful , the debug mode is on , before that there's some subtitles being downloaded but nothing else.

I've done some further searching and it seems that there is a problem reading the XML file. 
I've configured a torrent provider and this works instantly.

Now someone using the same provides as I am , has the same issue. 
I've built a new debian(8) yesterday where i have the same result. 

i've added the manual search part that was listed and i've also added the XML file (without API key) if that helps you with the returned result. 

https://gist.github.com/sepperrs/398b65f03d08ea5366e7#file-gistfile1-txt

**Comment by miigotu** [comment]
I can't help as I dont have any nzb providers to test with, and your log doesnt have any errors (should be after the rss output).

**Comment by birt** [comment]
I have my own newznab instance running, I can create you an account if you want?

**Comment by miigotu** [comment]
hmm, you can if you like, but I might not be able to figure it out tonight.

**Comment by birt** [comment]
No hurry..might also come in handy to troubleshoot other probs later..

**Comment by miigotu** [comment]
@birt new to nzb here. Am I supposed to be able to log in to your index from sabnzbd+? Or am I only able to browse/snatch without buying a usenet provider account somewhere?

**Comment by miigotu** [comment]
NZB is being searched twice, 1 second apart. The first search has no query. Maybe its supposed to be that way but I noticed a request limit exceeded return from my indexer. 1407 minutes until I could search again?!?

**Comment by thepauk** [comment]
Maybe the same problem. No episodes are snatched!! (NZB's)
When I look at the "Coming episode" page I see the shows for the next day, but the morning after there are no shows for that day. All episodes that are available have the status "unaired" instead of "wanted". I can manually search for them but that's it. This is since a couple of days!!

**Comment by birt** [comment]
@miigotu yes site was very slow :-) working on improving that a bit..

what do you guys use to debug multithreaded python apps like sickrage?
I want to step through the code to see where it goes wrong...

@thepauk : that sounds exactly like the issue @sepperrs & me are experiencing..
what are you using as search providers? Also newznab-based?

**Comment by miigotu** [comment]
@birt the code is supposed to debug itself, as it is a scripting language, not a compiled language. We have unit testing to test common functionality, and when a bug is reported, we try and find where it could fail and do further checks by adding logging or other checks around that piece of code and re-running it. Then we try to add more exception/error handling in that section of code, and optimally add a unit test to make sure the error is fixed and does not happen again with code changes in the future.

**Comment by miigotu** [comment]
that rssDB error is different, as it's just because lolo.sickbeard.com is inoperational now.

**Comment by thepauk** [comment]
@birt: I'm using Usenet-Crawler, Sick Beard index and Womble's index. I think usenet-crawler is newznab-based!

**Comment by Thraxis** [comment]
I've had shows snatched from usenet-crawler each day for the past week

**Comment by Thraxis** [comment]
@migotu Hmm.. actually I'm not sure shows that haven't aired yet are searched for until after their airtime has passed.

https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/dailysearcher.py#L76-L85

This segment of code was added in November.. and looks to skip over the episode in the daily searcher until after the show has aired.  Leaving the status as UNAIRED until that time.

ie.  an hour long show that airs at 10pm would not be set as WANTED or searched for until after 11PM

**Comment by miigotu** [comment]
@Thraxis 
'Hmm.. actually I'm not sure shows that haven't aired yet are searched for until after their airtime has passed.'

That would be the desired behavior, no? ie: If it hasn't aired yet, how could it be on the index?

**Comment by thepauk** [comment]
At the moment sickrage hasn't snatched an episode in a week now!
All the episodes it's supposed to snatch, still have the status unaired. For example Arrow from 7-5-2015 still shows as unaired! Might reinstalling be effective or should I wait for a bugfix?

**Comment by miigotu** [comment]
maybe check that the date/time is set correct on the pc.. Snatching is working for everyone else.

**Comment by thepauk** [comment]
@miigotu: Date and time are okay. Snatching only works manually for me now. I think I am not the only one, otherwise this thread wouldn't be here? I am using phyton 2.7.9 could that be a problem?

**Comment by miigotu** [comment]
You said the status is still unaired, but that is different from the problem the OP had. They only had issues with NZB not snatching, not aired/unaired status. as Torrents were still working for them.

**Comment by thepauk** [comment]
I'm only using usenet (NZB's) not torrent.

**Comment by miigotu** [comment]
@thepauk that would not cause everything to stay unaired. It is a separate issue. ofc, we will look into it.

**Comment by thepauk** [comment]
@miigotu: Thanks! So python 2.7.9 can't be an issue then? Maybe some code works different with 2.7.8 then 2.7.9?

**Comment by thepauk** [comment]
@miigotu: This morning all my unaired episodes were snatched, without changing anything on my end. Let's see how tomorrow goes! I'll keep you updated!!

**Comment by ziedby** [comment]
Hi,
Confirmed on my side. I'm not able to snatch any available download for maybe a week.
How can I get more logs and more details ?

Many episodes are now waiting in my backlog. These episodes are available manually.
Thank you guys!

2015-05-11 22:10:00 INFO     SEARCHQUEUE-MANUAL-121361 :: Unable to find a download for: [Game of Thrones - 5x05 - Kill the Boy]
2015-05-11 22:09:39 INFO     SEARCHQUEUE-MANUAL-121361 :: [Sick Beard Index] :: Performing episode search for Game of Thrones
2015-05-11 22:08:51 INFO     SEARCHQUEUE-MANUAL-121361 :: [Nzbs.in] :: Performing episode search for Game of Thrones
2015-05-11 22:08:22 INFO     SEARCHQUEUE-MANUAL-121361 :: Building internal name cache for Game of Thrones
2015-05-11 22:08:22 INFO     SEARCHQUEUE-MANUAL-121361 :: No scene exceptions update needed
2015-05-11 22:08:20 INFO     SEARCHQUEUE-MANUAL-121361 :: Beginning manual search for: [Game of Thrones - 5x05 - Kill the Boy]

**Comment by miigotu** [comment]
Under general settings -> advanced tab, enable debug, and save, then make sure your sickrage is up to date, and restart it. I'm having a hard time trying to figure out where this could be going wrong without any errors in the logs, as the snatch tests and search tests are working. So let it do some searching and provide the full log from bootup.

**Comment by ziedby** [comment]
miigotu thank you!
Here the entire log file from the debug saved config to the fully restarted homepage.

https://gist.github.com/ziedby/f2c8fb03fc51b9b3525a#file-sickrage-log

Remaining episodes are for example:
Arrow S03E22
The Big Bang Theory S08E24
Grey's Anatomy S11E23
which are available for download.

**Comment by miigotu** [comment]
2015-05-12 00:25:09 DEBUG    MAIN :: Setter sets location to /volume1/Shows/The Big Bang Theory
2015-05-12 00:25:09 DEBUG    MAIN :: 80379: Finding the episode which airs next
2015-05-12 00:25:09 DEBUG    MAIN :: 80379: No episode found... need to implement a show status

**Comment by miigotu** [comment]
@ziedby what does it show for airdate and status for The Big Bang Theory S08E24?

**Comment by ziedby** [comment]
@miigotu here is the backlog: 
8x24 The Commitment Determination 	05/07/2015
Status:
Wanted

**Comment by miigotu** [comment]
not in backlog, in shows->big bang->

**Comment by thepauk** [comment]
I made a logfile too with debug mode on. Maybe helpfull. The shows Castle and The Originals were available but sickrage didn't "see" them. Status in shows was unaired. Manual search snatched them.

https://gist.github.com/thepauk/bfda157de939a51abdf0

**Comment by ziedby** [comment]
@miigotu in the show's page the episode is "wanted" with an airdate: 05/07/2015

**Comment by miigotu** [comment]
Try changing the log level to db, and post again from fresh boot. Im trying to rule out if it was my commit to update the initial schema.

**Comment by ziedby** [comment]
I have changed the log level to db and restarted SickRage.
Hope you'll find what you're looking for.

https://gist.github.com/ziedby/812cc5c2d1efba4030d7#file-file-sickrage-log-05122015

Do you want me to try something by changing some statuses, by emptying the backlog(ignore remaining episodes),... ?

Let me know.

**Comment by miigotu** [comment]
@ziedby that only has 'info' level logs.

**Comment by ziedby** [comment]
@miigotu Sorry my mistake. File updated.

https://gist.github.com/ziedby/812cc5c2d1efba4030d7#file-file-sickrage-log-05122015

**Comment by miigotu** [comment]
I think you guy's show queue is stuck on a show somewhere. Try going to manage->mass update, check the box at the top of the update column, and click submit at the bottom. Lets see what happens.

**Comment by ziedby** [comment]
OK Done.

https://gist.github.com/ziedby/50f27fda3b832709756c#file-sickrage-log-forceupdate

I'm not able to get more logs, I'm not having access to the ssh console from here.

**Comment by ziedby** [comment]
I manually downloaded the missing episodes as a test. I'll let you know...

**Comment by miigotu** [comment]
Auto show updater might be getting stuck here:
`2015-05-12 12:43:21 INFO     SHOWQUEUE-FORCE-UPDATE :: The show dir /volume1/Shows/Almost Human is missing, not bothering to change the episode statuses since it'd probably be invalid`

Remove that from your SR or create the show folder. If you plan to keep it, do a refresh/update for that show after creating the folder.

**Comment by ziedby** [comment]
Great! We had the same idea. I already deleted the show few hours before. 
I'll let you know...

Envoyé de mon iPhone

**Comment by ziedby** [comment]
SickRage is still unable to find any download.
Here another log file after a restart, without any episode left in the Backlog exept the last episode of GOT which I downloaded manually, but reset to Wanted for the test.

https://gist.github.com/ziedby/8f2b6bfc76f400d15a51#file-sickrage-log-1514

**Comment by miigotu** [comment]
@ziedby can you upload your database (privately) and message or email me the link? I need to see what the problem is with this:

```
2015-05-12 21:39:52 DEBUG    MAIN :: 80349: No episode found... need to implement a show status
2015-05-12 21:39:52 DEBUG    MAIN :: 80349: Finding the episode which airs next
```

It's no doubt why it isnt working, and both of you guys have this same error.

**Comment by thepauk** [comment]
@miigotu: I did some more testing, maybe related to the problem.
1. When i have shows for say 13 may I see them on 12 may but they're gone on 13 may. (status unaired). After a Massupdate the reappear as WANTED. Also they're back in the coming episode list.
2. My daily search is set to 15 min. But when I look at my log files I don't see it running. If I start it manually it says it's running, but doesn't show up in the logs. So I think dailysearch isn't working properly.
3. After the massupdate when all shows are properly set to wanted and I start a backlogsearch all shows available are SNATCHED

Seems like dailysearch isn't working, but backlogsearch is and massupdate properly sets the right shows to wanted for me.

If I can help in some way, let me know!!

**Comment by ziedby** [comment]
@miigotu db file sent by mail.

**Comment by miigotu** [comment]
@thepauk confirms my suspicions.
@ziedby thanks it will help for me to check your db structure.

**Comment by ziedby** [comment]
I'm having an issue for post-processing the Big Bang Theory missing episode.
It's maybe related to our download problem. I'm trying to fix it by re-scanning the show folder.

The raised error when I try to process the file via the Manual Post-Processing page:

2015-05-13 11:52:18 Thread-50 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2160, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 203, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 504, in process_media
    result.result = processor.process()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/postProcessor.py", line 855, in process
    old_ep_status, old_ep_quality = common.Quality.splitCompositeStatus(ep_obj.status)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/common.py", line 264, in splitCompositeStatus
    return (status - x * 100, x)
TypeError: unsupported operand type(s) for -: 'str' and 'int'

**Comment by miigotu** [comment]
Ok, so the first bug I thought to check, is just an incorrectly coded debug line:
```
2015-05-12 21:39:53 DEBUG    MAIN :: 259765: No episode found... need to implement a show status
2015-05-12 21:39:53 DEBUG    MAIN :: 259765: Finding the episode which airs next
```

Happens when there are no known future for that show. (Show has ended)

@ziedby  I'll check into that `TypeError: unsupported operand type(s) for -: 'str' and 'int'` next, maybe tomorrow.

**Comment by ziedby** [comment]
Comment from NZBs.in : 
API DisabledTuesday, April 28 2015 08:25:56 AM

Today seems to be a bad day for NZBs.in.

First the website was really slow, now the API crashed.

We are aware of the situation and we are working hard at restoring all services.
In the meantime, feel free to visit this page :D

Thanks for your patience.

Update: the api has been enabled, there's still some issues with the website

Update2: the api will be up and down for the next few hours.

Update3: The API is back up, the site seems stable for now. We'll keep monitoring everything closely.

Final Update: It appears SickRage was the problem. We decided to block requests coming from SickRage until we can find a fix that won't bring the website down.

**Comment by fernandog** [comment]
@ziedby sickrage is not the problem. the problem are the users using too much aggressive search frequency.

**Comment by miigotu** [comment]
Lol this?: `2. My daily search is set to 15 min`

**Comment by thepauk** [comment]
Why not? Then you can be sure that you have everything in the morning :-D.
By the way an extra update: The massupdate only works for one day. The next day I have to do it again for all the shows to get the status wanted!

**Comment by miigotu** [comment]
Try setting your search frequency to 30 or 40 mins. No show is 15 minutes long,so you are searching twice as much as necessary. Maybe tvdb or tvrage is throttling you too? Lol

**Comment by thepauk** [comment]
Ok. I will do that!!

**Comment by thepauk** [comment]
@miigotu: If I am one of the few people with this problem, maybe a reinstall is the best way to go, because it's not working at the moment without doing a massupdate every day and then restart or wait for the backlogsearch or doing everything manual.

What is the best way to reinstall everything? And which version of python should i use?
Any hints would be appreciated.

**Comment by thepauk** [comment]
@miigotu: I'm happy to say, that everything looks to be okay again. I didn't do a reinstall, so maybe an update from sickrage? Dailysearch is working again like before (every 40 min ;-)) and all missed eps have status wanted instead of unaired. They also show on the coming episode page! 

I'll keep an eye on it, because there aren't many episodes at the moment! If it was an update.....thanks!
