### ISSUE TITLE
Not getting recognized as SD TV

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#1515]
My SickRage just snatched an episode "The.Ellen.DeGeneres.Show.2015.05.04.Sofia.Vergara.SDTV.x264-[2Maverick]" the thing is when it snatches it gets the quality as Unknow but when it post Processes it sets it as SD TV ,the correct one.

**Comment by matigonkas** [comment]
log : https://gist.githubusercontent.com/matigonkas/2fdb0d9aa85f07aa9c36/raw/gistfile1.txt

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1885
