### ISSUE TITLE
[APP SUBMITTED]: CHECKVERSION :: git pull -f origin master returned : From https://github.com/SiCKRAGETV/SickRage
 * branch            master     -> FETCH_HEAD
error: unable to create file autoProcessTV/lib/__init__.py (Permission denied)
Updating 5ef5a0b..7af9a84

### ISSUE THREAD

**Issue by mcmikev** [SiCKRAGETV/sickrage-issues#1517]
### INFO
Python Version: **2.7.9 (default, Mar 23 2015, 00:07:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
No Log available with ERRORS: 
### ERROR
```
CHECKVERSION :: git pull -f origin master returned : From https://github.com/SiCKRAGETV/SickRage
 * branch            master     -> FETCH_HEAD
error: unable to create file autoProcessTV/lib/__init__.py (Permission denied)
Updating 5ef5a0b..7af9a84
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Permissions error. You aren't running SR as the same user:group as the user you cloned it with. So either run SR as the same user, or chown the entire source to the user:group SR runs as.
