### ISSUE TITLE
[APP SUBMITTED]: POSTPROCESSER :: Failed to detect KODI version for '192.168.1.117:8080', check configuration and try again.

### ISSUE THREAD

**Issue by Rock81** [SiCKRAGETV/sickrage-issues#1518]
### INFO
Python Version: **2.7.9 (default, Apr 16 2015, 21:44:36) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.3-RELEASE-p9-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@7af9a845c324bd0b0698da0ae85b68b54568f6e1
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Failed to detect KODI version for '192.168.1.117:8080', check configuration and try again.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by karl0ss** [comment]
I am also having the same issue with SickRage and Kodi 15, any way to fix this? as I see it has been closed?

Thanks

**Comment by Rock81** [comment]
I don't have this issue i accidentily posted this, it was in my error log.
But the simple fact was that my Kodi was not running at the moment of error, 
so it is not strange in my case that Sickrage couldn't reach my Kodi.
It does reach it when it is online.

**Comment by karl0ss** [comment]
I managed to sort the issue out as well, so this can be ignored..
