### ISSUE TITLE
[APP SUBMITTED]: __str__ returned non-string (type Error)

### ISSUE THREAD

**Issue by Rock81** [SiCKRAGETV/sickrage-issues#1519]
### INFO
Python Version: **2.7.9 (default, Apr 16 2015, 21:44:36) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.3-RELEASE-p9-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@1c1f80877b22531fe73aef61fad784b140fef605
Link to Log: https://gist.github.com/437d53abc0942f0687ab
### ERROR
```
SEARCHQUEUE-MANUAL-266883 :: [Rarbg] :: Error while searching Rarbg, skipping: __str__ returned non-string (type Error)
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by kilabyte** [comment]
I have the exact same issue with torrent day

**Comment by Rock81** [comment]
No solutions i still have the same errors according to kila i am not the only one...

**Comment by herbi3** [comment]
### INFO
Python Version: **2.7.10 (default, May 31 2015, 12:53:36) [GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)]**
Operating System: **Darwin-11.4.2-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@92bf581ba8a7d4f2f912db795ce571b6ad38c3c2
Link to Log: https://gist.github.com/7368359df6b4c184a30b
### ERROR
```
SEARCHQUEUE-BACKLOG-73388 :: [MoreThanTV] :: Error while searching MoreThanTV, skipping: __str__ returned non-string (type Error)
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by herbi3** [comment]
### INFO
Python Version: **2.7.10 (default, May 31 2015, 12:53:36) [GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)]**
Operating System: **Darwin-11.4.2-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@92bf581ba8a7d4f2f912db795ce571b6ad38c3c2
Link to Log: https://gist.github.com/8471420b01088b312478
### ERROR
```
SEARCHQUEUE-BACKLOG-79126 :: [TorrentDay] :: Error while searching TorrentDay, skipping: __str__ returned non-string (type Error)
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
no issues here. report again if it happen
