### ISSUE TITLE
[APP SUBMITTED]: 'FFILibrary' object has no attribute 'SSL_set_tlsext_host_name'

### ISSUE THREAD

**Issue by CryptoGir** [SiCKRAGETV/sickrage-issues#1520]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@11796ea71472f509ff87d411f8b0cf74354fc72c
Link to Log: https://gist.github.com/4c4ddb64f038341ed9f8
### ERROR
```
SEARCHQUEUE-BACKLOG-73388 :: [IPTorrents] :: Error while searching IPTorrents, skipping: 'FFILibrary' object has no attribute 'SSL_set_tlsext_host_name'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@miigotu related to ssl fix?

**Comment by miigotu** [comment]
Switch to develop and follow the instructions [Here](https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors)
