### ISSUE TITLE
Snatched torrent files not stored in specified location

### ISSUE THREAD

**Issue by jamezk** [SiCKRAGETV/sickrage-issues#1521]
Hi there,

After checking out v4.0.19 I attempted to set up and run SickRage but I've run into a problem.
When I add a specific show the UI asks me where to put the files which I specify as an absolute path e.g. /home/jamezk/torrents/

As a consequence the directory is created for the show is created but when the torrents are snatched they are not downloaded to this directory. After some searching I found they are actually stored in the application root dir instead.

Did I miss something fundamental in setup or is this a bug?

**Comment by fernandog** [comment]
https://sickrage.tv/forums/forum/help-support/general-support/14420-sickrage-installation-guides-windows-mac-osx-linux-raspberry-pi
