### ISSUE TITLE
[APP SUBMITTED]: [Errno bad handshake] [('SSL routines', 'SSL23_GET_SERVER_HELLO', 'sslv3 alert handshake failure')]

### ISSUE THREAD

**Issue by mrsplendid** [SiCKRAGETV/sickrage-issues#1523]
### INFO
Python Version: **2.6.6 (r266:84292, Dec 27 2010, 00:02:40) [GCC 4.4.5]**
Operating System: **Linux-2.6.32-5-486-i686-with-debian-6.0.10**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@11796ea71472f509ff87d411f8b0cf74354fc72c
Link to Log: https://gist.github.com/a8f17ee9b13e57af98ad
### ERROR
```
SEARCHQUEUE-MANUAL-264492 :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno bad handshake] [('SSL routines', 'SSL23_GET_SERVER_HELLO', 'sslv3 alert handshake failure')]
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors

**Comment by mrsplendid** [comment]
Did not work for me!

**Comment by miigotu** [comment]
Did you update and follow the new instructions on that page?

**Comment by miigotu** [comment]
You need to use develop branch too, until sunday.
