### ISSUE TITLE
Feature request: Implementing users with different access

### ISSUE THREAD

**Issue by selthius** [SiCKRAGETV/sickrage-issues#1524]
It would make it a lot easier to share the status on my episodes if I were able to give my guests read-only access to sickrage. I realize this might require some major changes, so a option could be to export or open the db as read-only every X minutes  and serve that as a separate webpage dedicated for guests.

Another alternative is to open it read-only for everyone, and provide a login option for those rare occasions that it is needed, since sickrage is automated.

These are just ideas, I assume that the moderators will make the final decision as to if and how to implement this.

**Comment by fernandog** [comment]
massive change in SR. won't do it
