### ISSUE TITLE
No suitable RAR unpacker installed Mac OS X

### ISSUE THREAD

**Issue by vegeros** [SiCKRAGETV/sickrage-issues#1527]
Branch: master
Commit hash: cfe3b40b30ecec5c1838a5b6898bd79faf0ea762
mac os x 10.10, phyton 2.7

Unpack is no longer working, but it worked in the past.
I have installed unrar from both brew and port as suggested in the FAQ but nothing happens

2015-05-06 10:22:24 Thread-30 :: Rar Not Supported: No suitable RAR unpacker installed

Can you suggest a way to fix this?
Thanks a lot

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues

**Comment by vegeros** [comment]
Debug Log file
https://gist.github.com/vegeros/38cc1047b55da2c5106f#file-gistfile1-txt

Please help

**Comment by XxUnkn0wnxX** [comment]
i think i found a fix m8:

if your on mac just do this:

brew install unrar
brew unlink unrar
brew link unrar --force --overwrite

then do: which unrar
it should say: /usr/local/bin/unrar
then
sudo ln -s /usr/local/bin/unrar /usr/bin/unrar

and done, restart sickrage and problem should be resolved.
