### ISSUE TITLE
Change backlog_frequency 720 to 60

### ISSUE THREAD

**Issue by skillfr** [SiCKRAGETV/sickrage-issues#1528]
Hello,
How to change the frequency to search for episode ??

---------------------------

Bonjour,
Comment changer la fréquence de rechercher des épisode ??

**Comment by fernandog** [comment]
@skillfr why? you have the dailysearch that does that.

**Comment by skillfr** [comment]
@fernandog sorry but SEARCHQUEUE-DAILY-SEARCH will not work !!

http://pastebin.com/SsMnWeyz

**Comment by fernandog** [comment]
@skillfr disable proxy for the provider

**Comment by skillfr** [comment]
@fernandog it is not activated

http://i.imgur.com/Xw1EMNe.png

**Comment by skillfr** [comment]
@fernandog 
if I use the menu : manage -> Backlog Overview -> button force backlog it's work !!
http://i.imgur.com/LKWfYYK.png
But it works with the command backlog_frequency

an idea ??

**Comment by skillfr** [comment]
??

**Comment by skillfr** [comment]
@fernandog  ??

**Comment by fernandog** [comment]
@skillfr the code is the same for both searches. my be a intermittent issue in provider

**Comment by skillfr** [comment]
ok
