### ISSUE TITLE
[APP SUBMITTED]: Thread-55 :: Refusing to change status of 1x14 to DOWNLOADED because it's not SNATCHED/DOWNLOADED

### ISSUE THREAD

**Issue by POgli** [SiCKRAGETV/sickrage-issues#1529]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@cfe3b40b30ecec5c1838a5b6898bd79faf0ea762
Link to Log: https://gist.github.com/22a25bda006f35ac5097
### ERROR
```
Thread-55 :: Refusing to change status of 1x14 to DOWNLOADED because it's not SNATCHED/DOWNLOADED
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
You cant set an episode to downloaded yourself.

**Comment by fernandog** [comment]
set first to ignored then to downloaded

**Comment by TekGamer** [comment]
setting shows to ignored then to downloaded just changes the status of the episode, it doesn't solve the problem of the shows that are not detected even on a rescan, and even if they are named properly.  The episode number still isn't bolded, and does not show the filename when you hover over it.  Force full update doesn't detected the missing shows that are filed in the correct folders and have the correct filenames either.
