### ISSUE TITLE
After update 0 Shows (0 Active) | 0  / 0 Episodes Downloaded

### ISSUE THREAD

**Issue by javelin4effect** [SiCKRAGETV/sickrage-issues#1530]
BRANCH: (master) / COMMIT: (cfe3b40b30ecec5c1838a5b6898bd79faf0ea762) 

My operating system and python version (windows 7 / Python Version:	2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2])

What I did was update sickrage as i normally do. 

What happened After the update, sickrage stopped working, i reinstalled it and no shows listed.  I attempted to use my all of my multiple backups to restore, but none will restore any shows.  Presently it is 0 Shows (0 Active) | 0  / 0 Episodes Downloaded

What I expected was nothing but the software to update as usual.

There is no error to Link a copy/paste of my logfile with clear debug info of the error on GIST

**Comment by miigotu** [comment]
@javelin4effect Is your init script a link from your SR dir? I moved the init scripts, and changed some variables in init.upstart and init.ubuntu

**Comment by javelin4effect** [comment]
Can you help me to understand what you mean.

My seedbox host provides this application that runs from their server that
access through a link.  Beyond that, it was working GREAT until the last
update.  Now it still shows  0 Shows (0 Active) | 0 / 0 Episodes
Downloaded.  It will not let me restore from any backup.

I have tried uninstalling and restarting my seedbox then reinstalling to
now avail.



On Fri, May 8, 2015 at 3:08 PM, Dustyn Gibson <notifications@github.com>
wrote:

> @javelin4effect <https://github.com/javelin4effect> Is your init script a
> link from your SR dir? I moved the init scripts, and changed some variables
> in init.upstart and init.ubuntu
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/1530#issuecomment-100111827>
> .
>



-- 
Warrant Officer Three

**Comment by miigotu** [comment]
If you know where your old databases are, you can check in general config at the bottom and see where data is being stored now. The path is shown next to "All non-absolute folder locations are relative to "

You could move your old databases and config.ini to that location.

I have no way to help you is you don't know anything about the configuration files that define how SR is started. You might have to ask the seedbox provider.

**Comment by javelin4effect** [comment]
is there information i can send you from the configuration file?

On Fri, May 8, 2015 at 8:16 PM, Dustyn Gibson <notifications@github.com>
wrote:

> If you know where your old databases are, you can check in general config
> at the bottom and see where data is being stored now. The path is shown
> next to "All non-absolute folder locations are relative to "
>
> You could move your old databases and config.ini to that location.
>
> I have no way to help you is you don't know anything about the
> configuration files that define how SR is started. You might have to ask
> the seedbox provider.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/1530#issuecomment-100197405>
> .
>



-- 
Warrant Officer Three

**Comment by miigotu** [comment]
yes, paste the contents of /etc/default/sickbeard and/or /etc/default/sickrage, and /etc/init/sickrage and/or /etc/init/sickbeard to http://gist.github.com or pastebin or somewhere

**Comment by javelin4effect** [comment]
as requestd

contents posted..

https://gist.github.com/javelin4effect/5d858cc90499914507ce

Folders

/autoprocessTV
/cache
/cache-20150508_052047
/cache-20150508_104100
/gui
/LIB
/Logs
/runscripts
/sickbeard
/tests
/tornado


as requested...



On Sat, May 9, 2015 at 1:13 AM, Dustyn Gibson <notifications@github.com>
wrote:

> yes, paste the contents of /etc/default/sickbeard and/or
> /etc/default/sickrage, and /etc/init/sickrage and/or /etc/init/sickbeard to
> http://gist.github.com or pastebin or somewhere
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/1530#issuecomment-100283736>
> .
>



-- 
Warrant Officer Three

**Comment by miigotu** [comment]
um you posted contents of changelog.md, not what I asked for lol.

**Comment by javelin4effect** [comment]
I am sorry, but you asked me to paste the contents of /etc/default/sickrage.
Is there specific file or folder you need?.

Folders

/autoprocessTV
/cache
/cache-20150508_052047
/cache-20150508_104100
/gui
/LIB
/Logs
/runscripts
/sickbeard
/tests
/tornado

Files

cache.db
cache.db-journal
CHANGES.md
config.ini
contributing.md
COPYING.txt
failed.db
failed.db-journal
googlecode_upload.py
readme.md
setup.py
sickbeard.db
sickbeard.db-journal
SickBeard.py
TODO.txt
updater.py

On Sat, May 9, 2015 at 7:11 AM, Dustyn Gibson <notifications@github.com>
wrote:

> um you posted contents of changelog.md, not what I asked for lol.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/1530#issuecomment-100380689>
> .
>



-- 
Warrant Officer Three

**Comment by miigotu** [comment]
The paths I gave you are supposed to be single files.  ie: /etc/default/sickbeard is a text based file.

**Comment by miigotu** [comment]
If those files are in those paths, then it seems whomever set SR up on your seedbox doesnt understand what specific paths are intended for on linux. /etc/default is for default service configuration files to be customized on a per machine basis. they are sourced from init scripts.

Technically there are only a few standard places SR should be installed if installed systemwide within the standard tree. `/opt/SickRage` or `/srv/SickRage` depending on your distribution.
The databases, config, and logs for SR should be placed under `/var/SickRage`

Then a service configuration file `/etc/default/sickrage` should be created with the variables properly set. Example of my `/etc/default/sickrage`:

```
SR_USER=XXXXXX
SR_HOME=/opt/SickRage
SR_DATA=/var/SickRage
```

Then copy the right service file from `runscritps` in the sickrage source to `/etc/init/sickrage.conf` (if you have upstart) or `/etc/init.d/sickrage` for sysV.

If using upstart, you have to edit the setuid and setgid in the script, to match the SR_USER. Also check at the top of the init script to make sure your variables are correct in `/etc/default/sickrage`

**Comment by javelin4effect** [comment]
Thanks for your patients.

SR worked for the past 3 months until the last SR update.  Now it does not
load at all.

I downloaded the SR folder looking for that path.  My sickrage is basically
a folder on the seedbox with all the file contained within as I listed.  I
accessed my seedbox to see if i could access the parent directory. i cant.

I am going to have to relay this information to my seedbox support and see
what information i get back.



On Sat, May 9, 2015 at 8:04 AM, Dustyn Gibson <notifications@github.com>
wrote:

> If those files are in those paths, then it seems whomever set SR up on
> your seedbox doesnt understand what specific paths are intended for on
> linux. /etc/default is for default service configuration files to be
> customized on a per machine basis. they are sourced from init scripts.
>
> Technically there are only a few standard places SR should be installed if
> installed systemwide within the standard tree. /opt/SickRage or
> /srv/SickRage depending on your distribution.
> The databases, config, and logs for SR should be placed under
> /var/SickRage
>
> Then a service configuration file /etc/default/sickrage should be created
> with the variables properly set. Example of my /etc/default/sickrage:
>
> SR_USER=XXXXXX
> SR_HOME=/opt/SickRage
> SR_DATA=/var/SickRage
>
> Then copy the right service file from runscritps in the sickrage source
> to /etc/init/sickrage.conf (if you have upstart) or /etc/init.d/sickrage
> for sysV.
>
> If using upstart, you have to edit the setuid and setgid in the script, to
> match the SR_USER. Also check at the top of the init script to make sure
> your variables are correct in /etc/default/sickrage
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/1530#issuecomment-100390995>
> .
>



-- 
Warrant Officer Three

**Comment by fernandog** [comment]
@miigotu related to relative PATHs?

**Comment by javelin4effect** [comment]
yes... i have asked them about the paths you referenced.

On Sat, May 9, 2015 at 8:22 PM, Fernando <notifications@github.com> wrote:

> @miigotu <https://github.com/miigotu> related to relative PATHs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/1530#issuecomment-100466894>
> .
>



-- 
Warrant Officer Three

**Comment by miigotu** [comment]
@fernandog no, the seedbox provider has sickrage installed improperly.

**Comment by javelin4effect** [comment]
As soon as they  disable trakt on my config, my sickrage starts to work. So
it is safe to assume, that the problem lies somewhere there

This error is produced when sickrage crashes with trakt enabled:

python[15873]: segfault at 0 ip 0000036d4085e67b sp 0000036d115135a8 error
6 in libffi.so.6.0.1[36d40859000+7000]

Can sickrage devs make some sense out of it.  I would like to relay the
resolution to the seedbox team.

At the beginning it was though the problem was with the cryptography
libraries of python, but when it all of them was reinstalled on my server,
it did not solve the problem

On Sun, May 10, 2015 at 1:10 AM, Dustyn Gibson <notifications@github.com>
wrote:

> @fernandog <https://github.com/fernandog> no, the seedbox provider has
> sickrage installed improperly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/1530#issuecomment-100510932>
> .
>



-- 
Warrant Officer Three

**Comment by miigotu** [comment]
@javelin4effect I would assume that segfault is due to the cryptography, pyOpenSSL, or libffi being installed when it was compiled/packaged for a different abi/api/architecture. It is most certainly not caused by sickrage itself.

Likely someone doesn't realize that although python code is system/architecture aspecific, some modules use specific versions of c headers to compile objects in order to interface (abi) with a shared library object on the system of the same version as those c headers.  If the python object is compiled with a different version of headers than the version of the installed shared library, you will have problems (segfaults) because the python object is trying to call symbols (functions) in the library at the incorrect locations in memory. 

Also, these compiled python objects are also architecture (processor type) specific. For example, a python module object built on an x86 processor will segfault if run on an arm processor.

This is why abi and platform (platform = os, architecture) is specified for wheel files, as wheels contain precompiled objects and bytecode. This is also why installing/building a python module with pip (.egg) is only to be done on the target itself.

I assume the header vs shared library versions may be the culprit here, if some calls to the library work, because it is possible that some functions remain linked at the same locations between library versions, while others are not.

**Comment by javelin4effect** [comment]
Thanks for you response, Can you offer a Takt substitute?

On Mon, May 11, 2015 at 8:26 PM, Dustyn Gibson <notifications@github.com>
wrote:

> @javelin4effect <https://github.com/javelin4effect> I would assume that
> segfault is due to the cryptography, pyOpenSSL, or libffi being installed
> when it was compiled/packaged for a different abi/api/architecture. It is
> most certainly not caused by sickrage itself.
>
> Likely someone doesn't realize that although python code is
> system/architecture aspecific, some modules use specific versions of c
> headers to compile objects in order to interface (abi) with a shared
> library object on the system of the same version as those c headers. If the
> python object is compiled with a different version of headers than the
> version of the installed shared library, you will have problems (segfaults)
> because the python object is trying to call symbols (functions) in the
> library at the incorrect locations in memory.
>
> Also, these compiled python objects are also architecture (processor type)
> specific. For example, a python module object built on an x86 processor
> will segfault if run on an arm processor.
>
> This is why abi and platform (platform = os, architecture) is specified
> for wheel files, as wheels contain precompiled objects and bytecode. This
> is also why installing/building a python module with pip (.egg) is only to
> be done on the target itself.
>
> I assume the header vs shared library versions may be the culprit here, if
> some calls to the library work, because it is possible that some functions
> remain linked at the same locations between library versions, while others
> are not.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/1530#issuecomment-100875047>
> .
>



-- 
Warrant Officer Three

**Comment by miigotu** [comment]
Sorry, but it is not a problem with trakt. It is a borked abi chain on the system.

**Comment by javelin4effect** [comment]
Right now the Sickrage is working.

If I setup trakt SR  stop working and will not be able to access my data
again.  I will need the seedbox crew to reload it.

On Mon, May 11, 2015 at 8:44 PM, Dustyn Gibson <notifications@github.com>
wrote:

> Sorry, but it is not a problem with trakt. It is a borked abi chain on the
> system.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/1530#issuecomment-100882235>
> .
>



-- 
Warrant Officer Three

**Comment by javelin4effect** [comment]
i just took a week to reload it, no one was able to resolve the problem.

On Tue, May 26, 2015 at 8:45 PM, neoatomic <notifications@github.com> wrote:

> Closed #1530 <https://github.com/SiCKRAGETV/sickrage-issues/issues/1530>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/1530#event-313683696>
> .
>



-- 
Warrant Officer Three
