### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by ntrantham** [SiCKRAGETV/sickrage-issues#1531]
### INFO
Python Version: **2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@cfe3b40b30ecec5c1838a5b6898bd79faf0ea762
Link to Log: https://gist.github.com/3f0b9cf89dffcd8da8e1
### ERROR
```
Thread-97 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 3746, in saveGeneral
    if not config.change_LOG_DIR(log_dir, web_log):
  File "C:\SickRage\sickbeard\config.py", line 89, in change_LOG_DIR
    abs_log_dir = os.path.normpath(os.path.join(sickbeard.DATA_DIR, log_dir))
  File "C:\Python27\lib\ntpath.py", line 73, in join
    elif isabs(b):
  File "C:\Python27\lib\ntpath.py", line 57, in isabs
    s = splitdrive(s)[1]
  File "C:\Python27\lib\ntpath.py", line 125, in splitdrive
    if p[1:2] == ':':
TypeError: 'NoneType' object has no attribute '__getitem__'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@ntrantham whats the content of LOG DIR setting?

**Comment by ntrantham** [comment]
C:\SickRage\Logs

I had already cleared the logs after submitting the errors.  I think it may have been related to another error posted about SickRage when you remove a show shortly before running a full update.
I am in the middle of converting to SickRage from SickBeard and had removed a couple of shows and re-added them (I selected the wrong TVdb show when adding them the first time.)

**Comment by fernandog** [comment]
@ntrantham  Just set "Logs". It already goes inside SickRage

**Comment by ntrantham** [comment]
It actually is set to 'Logs'

I just included the full path in my reply.

Sent from my iPhone

On May 6, 2015, at 12:00 PM, Fernando <notifications@github.com<mailto:notifications@github.com>> wrote:


@ntrantham<https://github.com/ntrantham> Just set "Logs". It already goes inside SickRage

**Comment by dkimbell13** [comment]
### INFO
Python Version: **2.7.8 (default, Jul  3 2014, 23:17:54) [GCC 4.8.2 20131219 (prerelease)]**
Operating System: **Linux-3.10.30-30-ARCH-armv7l-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@26e215e13029f423dc9e9a7a27d36b461fab9942
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-80441 :: Error while searching omgwtfnzbs, skipping: 'NoneType' object has no attribute '__getitem__'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dkimbell13** [comment]
### INFO
Python Version: **2.7.8 (default, Jul  3 2014, 23:17:54) [GCC 4.8.2 20131219 (prerelease)]**
Operating System: **Linux-3.10.30-30-ARCH-armv7l-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@799dd0c3193139f93d3180e2a4c9b981cb7d7894
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-80542 :: Error while searching omgwtfnzbs, skipping: 'NoneType' object has no attribute '__getitem__'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Xenocell12** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@92bf581ba8a7d4f2f912db795ce571b6ad38c3c2
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-75978 :: [omgwtfnzbs] :: Error while searching omgwtfnzbs, skipping: 'NoneType' object has no attribute '__getitem__'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dkimbell13** [comment]
### INFO
Python Version: **2.7.8 (default, Jul  3 2014, 23:17:54) [GCC 4.8.2 20131219 (prerelease)]**
Operating System: **Linux-3.10.30-30-ARCH-armv7l-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@799dd0c3193139f93d3180e2a4c9b981cb7d7894
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-80542 :: Error while searching omgwtfnzbs, skipping: 'NoneType' object has no attribute '__getitem__'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by mchrisley** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 23 2015, 00:07:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@e39fae0502b0993fd0163ea2f6888871426465be
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-82918 :: [omgwtfnzbs] :: Error while searching omgwtfnzbs, skipping: 'NoneType' object has no attribute '__getitem__'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by MasterAslan** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@42b8d5a9c71c87fcde301967b6254ef08c3093ac
Link to Log: https://gist.github.com/ab4a324182859769f712
### ERROR
```
SEARCHQUEUE-BACKLOG-24796 :: [omgwtfnzbs] :: Error while searching omgwtfnzbs, skipping: 'NoneType' object has no attribute '__getitem__'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by armss001** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@42b8d5a9c71c87fcde301967b6254ef08c3093ac
Link to Log: https://gist.github.com/fed6be4b3f3a9e23e2ee
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [NextGen] :: Failed to login:Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\nextgen.py", line 123, in _doLogin
    csrfraw = bs.find('form', attrs={'id': 'login'})['action']
TypeError: 'NoneType' object has no attribute '__getitem__'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by MasterAslan** [comment]
Let me know if you need any further info

**Comment by Xenocell12** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@42b8d5a9c71c87fcde301967b6254ef08c3093ac
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-75978 :: [omgwtfnzbs] :: Error while searching omgwtfnzbs, skipping: 'NoneType' object has no attribute '__getitem__'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Xenocell12** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@42b8d5a9c71c87fcde301967b6254ef08c3093ac
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-75978 :: [omgwtfnzbs] :: Error while searching omgwtfnzbs, skipping: 'NoneType' object has no attribute '__getitem__'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by simonlock** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.11-v7+-armv7l-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@42b8d5a9c71c87fcde301967b6254ef08c3093ac
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-262980 :: Error while searching omgwtfnzbs, skipping: 'NoneType' object has no attribute '__getitem__'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by phurious** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-53-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d185980c89055f7179deec708141710ce386a572
Link to Log: https://gist.github.com/5e3640bcb01706595a94
### ERROR
```
SEARCHQUEUE-MANUAL-281536 :: [omgwtfnzbs] :: Error while searching omgwtfnzbs, skipping: 'NoneType' object has no attribute '__getitem__'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by lembregtse** [comment]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:33:21) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-16-generic-x86_64-with-Ubuntu-15.04-vivid**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@f9246bcfdb95929e95e5f422d577fc9aa7d69953
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-MANUAL-71663 :: [omgwtfnzbs] :: Error while searching omgwtfnzbs, skipping: 'NoneType' object has no attribute '__getitem__'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by mintyphoenix** [comment]
### INFO

Python Version: **2.7.6 (default, Mar 22 2014, 22:59:38) [GCC 4.8.2]**
Operating System: **Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-24-generic i686)**
Locale: **('en_US', 'UTF-8')**
Branch: **master**
Commit: **SiCKRAGETV/SickRage@f9246bc**
Log with Errors (Traceback): https://gist.github.com/mintyphoenix/795eb05e711512982335#file-gistfile1-txt

### ERROR

    SEARCHQUEUE-BACKLOG-274431 :: [omgwtfnzbs] :: Error while searching omgwtfnzbs, skipping: 'NoneType' object has no attribute '__getitem__'

**Comment by fernandog** [comment]
@ntrantham check you log path setting. Must be Logs or anything else. Cant be empty
