### ISSUE TITLE
[APP SUBMITTED]: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/290831/en.xml

### ISSUE THREAD

**Issue by andyblac** [SiCKRAGETV/sickrage-issues#1532]
### INFO
Python Version: **2.7.9 (default, Mar 23 2015, 00:07:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@cfe3b40b30ecec5c1838a5b6898bd79faf0ea762
Link to Log: https://gist.github.com/d9f231ac44eaf2639544
### ERROR
```
SHOWQUEUE-ADD :: Unable to find show ID:290831 on Indexer: theTVDB
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
check thetvdb info for that show
