### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-255316 :: DownloadStation: Unable to send Torrent: Return code undefined

### ISSUE THREAD

**Issue by FlyGuy94** [SiCKRAGETV/sickrage-issues#1533]
### INFO
Python Version: **2.7.9 (default, Mar 23 2015, 00:07:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@cfe3b40b30ecec5c1838a5b6898bd79faf0ea762
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-255316 :: DownloadStation: Unable to send Torrent: Return code undefined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@FlyGuy94 Use the admin account and set a download location for download station.
