### ISSUE TITLE
[Feature Request] Add French torrent providers (Libertalia xthor, so-torrent, cpasbien etc.)

### ISSUE THREAD

**Issue by skillfr** [SiCKRAGETV/sickrage-issues#1534]
Hello,
Can you add French providers such as Libertalia xthor, so-torrent ??
Or just showing us how to add them without going through the RSS ??

----------------------------------------------------------------

Bonjour,
Pouvez vous ajouter des fournisseurs français telle que Libertalia, xthor, so-torrent ??
Ou tout simplement nous montré comment les ajouter sans passer par le flux RSS ??

**Comment by maxcore** [comment]
+1

**Comment by Nibeck1309** [comment]
ans torrent provider cpasbien

thanks

**Comment by thenamelessthing** [comment]
add frenchtorrentdb and bluetigers

**Comment by raver2046** [comment]
remove  so-torrent this provider doesn't exist

**Comment by neoatomic** [comment]
The providers Cpasbien & Libertalia & FrenchTorrentDB where added.
We have to thank @adaur for his hard work on coding/implementing those in SickRage.

https://github.com/SiCKRAGETV/SickRage/commit/70edd27f2e6cb7350f426d8c7c8dac2e83887d27
https://github.com/SiCKRAGETV/SickRage/commit/c58e54802472f6a5d3bad7752d57be3cfa43f771
https://github.com/SiCKRAGETV/SickRage/commit/548274a1f4ad7c1d4b956a69d46c7b539c4e48bc

**Comment by adaur** [comment]
Xthor is done.

https://github.com/SiCKRAGETV/SickRage/pull/2172
