### ISSUE TITLE
[Feature Request] Add "failed" parameter to postprocess api call

### ISSUE THREAD

**Issue by andreofgyn** [SiCKRAGETV/sickrage-issues#1536]
Currently the postprocess api call has a hard coded "failed" setting to false, please, add an "failed" parameter to allow report bad downloads via api.

**Comment by fernandog** [comment]
@andreofgyn can you point in the code that?

**Comment by andreofgyn** [comment]
Here:
https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/webapi.py#L1401

**Comment by fernandog** [comment]
@andreofgyn 

stop SR,
edit SickRage/sickbeard/webapi.py, clear contents, paste this one
https://raw.githubusercontent.com/fernandog/SickRage/api_failed_option/sickbeard/webapi.py
save,
start SR
test

the parameter is "failed"

It that won't work, more changed must be done and you will have to wait

**Comment by fernandog** [comment]
@TagForce thinking about this, will it set FAILED all files in the processdir?

**Comment by andreofgyn** [comment]
OK, it's working, I created a empty folder named "Penny Dreadful S01E03 720p HDTV x264-KILLERS"  on my process folder (!tvcompleto) and tested the 2 ways:

**1- wget 'http://xxxxx:7071/api/xxxxxx/?cmd=postprocess&failed=1' (the way you asked @TagForce)**

*-> Nothing found, it tried to process only the root folder (!tvcompleto), log:*

2015-05-06 16:11:23 INFO     TORNADO :: [!tvcompleto : Failed download]
2015-05-06 16:11:23 INFO     TORNADO :: I did encounter some unprocessable items: 
2015-05-06 16:11:23 INFO     TORNADO :: Successfully processed
2015-05-06 16:11:23 WARNING  TORNADO :: Failed Download Processing failed: (None, /c/xxxx/!tvcompleto): 
2015-05-06 16:11:23 INFO     TORNADO :: Folder name (!tvcompleto) appears to be a valid release name. Using it.
2015-05-06 16:11:23 INFO     TORNADO :: Failed download detected: (None, /c/xxxx/!tvcompleto)

**2- wget 'http://xxxxx:7071/api/xxxxxx/?cmd=postprocess&failed=1&path=/path/to/Penny Dreadful S01E03 720p HDTV x264-KILLERS/' (the way I expected to work)**

*-> Found the folder without problems, marked the episode as wanted and downloaded just fine, perfect, log:*

2015-05-06 16:13:17 INFO     SEARCHQUEUE-RETRY-265766 :: [NZB.su] :: Performing episode search for Penny Dreadful
2015-05-06 16:13:17 INFO     SEARCHQUEUE-RETRY-265766 :: Building internal name cache for Penny Dreadful
2015-05-06 16:13:17 INFO     SEARCHQUEUE-RETRY-265766 :: No scene exceptions update needed
2015-05-06 16:13:17 INFO     SEARCHQUEUE-RETRY-265766 :: Beginning failed download search for: [Penny Dreadful - 1x03 - Resurrection]
2015-05-06 16:13:17 WARNING  SEARCHQUEUE-RETRY-265766 :: WARNING: Episode not found in history. Setting it back to WANTED
2015-05-06 16:13:17 INFO     SEARCHQUEUE-RETRY-265766 :: Reverting episode (1, 3): Resurrection
2015-05-06 16:13:17 INFO     SEARCHQUEUE-RETRY-265766 :: Marking episode as bad: [Penny Dreadful - 1x03 - Resurrection]
2015-05-06 16:13:16 INFO     TORNADO :: [Penny Dreadful S01E03 720p HDTV x264-KILLERS : Failed download]
2015-05-06 16:13:16 INFO     TORNADO :: I did encounter some unprocessable items: 
2015-05-06 16:13:16 INFO     TORNADO :: Successfully processed
2015-05-06 16:13:16 INFO     TORNADO :: Failed Download Processing succeeded: (None, /c/xxx/!tvcompleto/Penny Dreadful S01E03 720p HDTV x264-KILLERS)
2015-05-06 16:13:16 INFO     TORNADO :: Folder name (Penny Dreadful S01E03 720p HDTV x264-KILLERS) appears to be a valid release name. Using it.
2015-05-06 16:13:16 INFO     TORNADO :: Failed download detected: (None, /c/xxxxx/!tvcompleto/Penny Dreadful S01E03 720p HDTV x264-KILLERS)

**I think it can be on master already :+1:**

**Comment by fernandog** [comment]
@TagForce thoughts?

**Comment by fernandog** [comment]
@andreofgyn can you try open API builder, check if the parameter appears there please

localhost:xxxx/apibuilder

**Comment by andreofgyn** [comment]
@fernandog I can view the "postprocess" call if I select "SickRage" and click go on the api builder, but what should I do to view the parameters of that call?

**Comment by andreofgyn** [comment]
But like I said, I'm positive that the parameter "failed" is working, I tested multiple times.

The only differente that I noted, is that doing via api, the postprocess needs a valid and existing release FOLDER to process the failed download and doing via web (like autoProcessTV.py does) it accepts any valid filename, existing or not.

I think that when failed=1, path shoud be processed simple as a "release name" (web and api), because some errors, like 403, makes nzbget not even create a file/folder. I think there is no need to sickrage test if a download is really bad or the path is valid if failed=1, what do you think?

**Comment by Hellowlol** [comment]
@andreofgyn try adding the parameter type=auto&failed=1

**Comment by andreofgyn** [comment]
@Hellowlol I tested and type auto or manual, the api still needs an existing path on the disk to process. 

I would like to inform only the episode release (like path=Penny Dreadful S01E03 720p HDTV x264-KILLERS), I think it's not currently supported, but it makes sense when failed=1.

When the parameter path doesn't exist on the disk, sickrage doesn't even generate any log of the api call.

**Comment by Hellowlol** [comment]
Im not really sure i understand your problem. Does it work correctly via the gui?

**Comment by fernandog** [comment]
@andreofgyn what if you set path to the root folder?

**Comment by andreofgyn** [comment]
It's not a problem, failed=1 it's working with @fernandog update, I'm only commenting about it's functionality, like:

-> postprocess failed=1 and path=Penny Dreadful S01E03 720p HDTV x264-KILLERS **(nothing, not even a log)**
-> postprocess failed=1 and path=/existing/path/to/Penny Dreadful S01E03 720p HDTV x264-KILLERS **(success)**

I think it should work both ways when failed=1.

**Comment by andreofgyn** [comment]
@fernandog if the folder "Penny Dreadful S01E03 720p HDTV x264-KILLERS" doesn't exist inside the root folder (for instance, nzbget downloaded nothing because a 403 error), nothing will happen, that is what I'm questioning.

**Comment by fernandog** [comment]
@andreofgyn but what I a episode don't have folder but only the video file?

**Comment by Hellowlol** [comment]
I think its working as intended then. The path parameter is the full path for the folder/filer. 
How should it find the file to process it it you only give it a name?

 If that where the case we should assume that all files are in the sickbeard.TV_DOWNLOAD_DIR. 
Thats just wrong, the idea is to be able to postprocess ANY folder

**Comment by fernandog** [comment]
@Hellowlol agree

**Comment by andreofgyn** [comment]
@Hellowlol @fernandog but if not a single file/folder was downloaded? With a information like failed=1 and path="Penny Dreadful S01E03 720p HDTV x264-KILLERS" sickrage has enough information to handle the failed download, if you do not agree, ok, but the information is suffice.

**Comment by fernandog** [comment]
hum but if you process any folder and the download is still on going, SR will think it has failed.
so we can't process "root" PP folder. Agree?

**Comment by andreofgyn** [comment]
@fernandog my idea is not process any folder, is more like:

**Situation 1:**
-> postprocess failed=1 and path="Penny Dreadful S01E03 720p HDTV x264-KILLERS"

Does path exist inside the root folder?

* Yes:
-> Handle failed download using the existing path inside the root folder, no problem here.

* No:
-> Handle failed download, but how? Threat path as title/release name and process, this information is suffice.

**Situation 2:**
-> postprocess failed=1 and path="/existing/path/to/out/of/the/root/folder/Penny Dreadful S01E03 720p HDTV x264-KILLERS"

Does path exist?

* Yes:
-> Handle failed download using the existing path, no problem here.
 
* No:
-> Handle failed download, but how? Threat path as title/release name and process, this information is suffice.

**Comment by Hellowlol** [comment]
So in other words you want to be able to manually set a single downloaded file as failed via the api?

**Comment by andreofgyn** [comment]
@Hellowlol the point is, if you are **expliciting informing SR that the download failed=1**, why SR must find if the path exist or even if it's a path (or file) to do something!? SR should only really care if the parameter path has a **valid scene name** and handle the failed download accordingly.

For failed=0 I agree and it's obvious that the path must be a existing one.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
