### ISSUE TITLE
Network Logos - Slick GUI Issue

### ISSUE THREAD

**Issue by alzeric** [SiCKRAGETV/sickrage-issues#1537]
I didn't know if this was the right place to leave this bug report.

in the new GUI "slick"  "the anime network" icon gets outputted to the HTML as "images/the anime network.png" which shows as a broken image, since that file does not exist.

Upon investigation there is a anime network logo in the images/network folder however it is named 'anime network.png'

**Quick fix is to rename the image file from "anime network.png" to "the anime network.png"

**Comment by fernandog** [comment]
@neoatomic please?
