### ISSUE TITLE
Unable to find a download for kickass torrent provider

### ISSUE THREAD

**Issue by figura4** [SiCKRAGETV/sickrage-issues#1539]
Since a couple of weeks I am unable to snatch any episodes using kickass torrent provider. 

The search is performed correctly, no errors reported. It simply doesn't find torrents that are there (I manually entered the search string reported in the log file and the correct results are there).

BRANCH: master
COMMIT: (cfe3b40b30ecec5c1838a5b6898bd79faf0ea762)
System: Qnap TS-253 Pro-8G NAS  
Python: 2.7.3
Log: https://gist.github.com/anonymous/e5d689a6d7c8a7fab962

**Comment by miigotu** [comment]
Kat works fine here for me, its the only provider I use.

**Comment by figura4** [comment]
I tried other torrent providers (EZTV, piratebay), and I get a similar behaviour.
Oddly enough, with EZTV I get the following log entry:

[EZTV] :: Unable to parse the filename The%20Blacklist%20S02E21%20HDTV%20XviD-FUM%5Bettv%5D into a valid show

Could it be a search result parsing problem?
