### ISSUE TITLE
sabToSickBeard.py parsing fails even though file name is a valid scene file name

### ISSUE THREAD

**Issue by maniac79** [SiCKRAGETV/sickrage-issues#1540]
Hi,

I noticed getting errors from sabToSickBeard.py for all episodes from the TV show Hawaii Five 0.

From the log:
Processing /volume1/download/sabnzbd/complete/tv/1/hawaii.five-0.2010.523.hdtv-lol.mp4 (None)
This show isn't in your list, you need to add it to SB before post-processing an episode
Processing failed for /volume1/download/sabnzbd/complete/tv/1/hawaii.five-0.2010.523.hdtv-lol.mp4:

The show is in the list.

I assume the parser has an issue with the "-0" part of the file name.

If additional information is required, kindly let me know.

**Comment by neoatomic** [comment]
Yes, please follow the guidelines for posting an issue. Without that data its almost impossible to troubleshoot.

https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket
