### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-273520 :: Check scene exceptions update failed. Unable to get URL: https://raw.githubusercontent.com/echel0n/sb_tvrage_scene_exceptions/master/exceptions.txt

### ISSUE THREAD

**Issue by hulubi** [SiCKRAGETV/sickrage-issues#1541]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@cfe3b40b30ecec5c1838a5b6898bd79faf0ea762
Link to Log: https://gist.github.com/00a5d94e31814852a793
### ERROR
```
SEARCHQUEUE-BACKLOG-273520 :: Check scene exceptions update failed. Unable to get URL: https://raw.githubusercontent.com/echel0n/sb_tvrage_scene_exceptions/master/exceptions.txt
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Your internet failed during the download of that file, but that url should be changed in the source anyways so I'll pr that anyways.

**Comment by hulubi** [comment]
That can't be right because the network is on i can pick up the file from the url. still i am getting this error.

**Comment by hulubi** [comment]
FYI i am using QNAP x86

**Comment by neoatomic** [comment]
If the error still exists than Its probably related to https://github.com/SiCKRAGETV/sickrage-issues/issues/1580
Please continue there so we have those QNAP SSL errors in one place.

**Comment by superketto** [comment]
i have found and half-solutions (QNAP ARM):

    uninstall from app market Python Qpkg
    from ssh following this step: ipkg update ipkg install python27 (2.7.3 !!) ipkg install py27-setuptools ipkg install gcc ipkg install openssl-dev
    now from the directory ../optware/ python bin (find by find) launch: curl https://bootstrap.pypa.io/get-pip.py -L -k | python2.7 and pip2.7 install -U setuptools pip pyopenssl==0.13.1

now ...everything is installed without errors, but when launch sickrage go out with the error " Python Disable", i try an add the python binary in opt/bin but nothing to do.
In the sickrage.sh reference is made to python.sh installed by QPKG.

Any idea?
bye

**Comment by miigotu** [comment]
@superketto The ipkg version of openssl-dev does not match the system openssl version. So that is going to fail even if you get it starting.
