### ISSUE TITLE
fr - metadata not in the right language

### ISSUE THREAD

**Issue by Nibeck1309** [SiCKRAGETV/sickrage-issues#1543]
Hello,

When I post-processing the series Championne à tout pris (in french), the content of all metadata and nfo are in english. I used thetvdb indexer.

My series folder is Championnes à tout prix

exemple of tvshow.nfo
<tvshow>
  <title>Make it or Break it</title>
  <rating>6.7</rating>
  <year>2009</year>
  <plot>Set in the realm of competitive gymnastics, this ABC Family drama project follows a group of teen Olympic hopefuls in training for the big event.</plot>
  <episodeguide>
    <url>http://thetvdb.com/api/F9C450E78D99172E/series/95751/all/en.zip</url>
  </episodeguide>
  <mpaa>TV-PG</mpaa>
  <id>95751</id>
  <genre>Drama</genre>
  <premiered>2009-06-22</premiered>
  <studio>ABC Family</studio>

I have this problem for other series

thanks

**Comment by neoatomic** [comment]
@Nibeck1309 There needs to be French info on thetvdb indexer. If there isn't it will fall back to English.
Noting the developers can do about that.

**Comment by Nibeck1309** [comment]
The series Championnes à tout prix are in french in thetvdb indexer (http://www.thetvdb.com/?tab=series&id=95751&lid=17) but the information put in nfo are in english.

**Comment by neoatomic** [comment]
Have you set the language to french in the show.? So all info that you see there is in french.? (Or English.?)
