### ISSUE TITLE
Anime Settings (Separate folder)

### ISSUE THREAD

**Issue by syrys** [SiCKRAGETV/sickrage-issues#1544]
Hey,

This is regarding anime downloads using Sickrage.

Anime download works great, but currently sickrage seems to download anime into /TV Shows folder.

My question is, when you add an anime to your list on sickrage (by checking the anime checkbox when adding the show), why does this not (or atleast have some setting) put the anime onto a "/Anime" folder instead of "/TV Shows". This should be a very simple post process action?

Can we have this as a feature? Im assuming its quite easy to add too?

If this feature already exists, please point me to the right direction :)

Cheers.

**Comment by Thraxis** [comment]
You can add and select more root folder locations in step 2 of "Add a new show" one can be set the default.  and the other can still be selected when adding anime or whatever.  

![image](https://cloud.githubusercontent.com/assets/1131905/7530449/6d640f28-f4fd-11e4-9ee5-5e3b29d4d43d.png)

**Comment by syrys** [comment]
ah you are indeed correct, how did i miss this.

On another note, it would still be nice if you could have separate defaults for Anime vs Tv Shows, and a very easy way to flag a show as anime (not sure if it can be done automatically?). Some food for thought?

These are just some nice to have features. Im just noticing that the features for anime section is lacking, but it still works great as it is :)
