### ISSUE TITLE
[APP SUBMITTED]: 'link'

### ISSUE THREAD

**Issue by jweese74** [SiCKRAGETV/sickrage-issues#1546]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@cfe3b40b30ecec5c1838a5b6898bd79faf0ea762
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-71663 :: [KickAssTorrents] :: Failed to parsing KickAssTorrents Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\kat.py", line 238, in _doSearch
    link = item['link']
  File "C:\SickRage\lib\feedparser\feedparser.py", line 353, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'link'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Without logs we cant do noting...
