### ISSUE TITLE
TorrentDay, skipping: str returned non-string (type Error)

### ISSUE THREAD

**Issue by kilabyte** [SiCKRAGETV/sickrage-issues#1551]
2015-05-08 11:35:29 SEARCHQUEUE-MANUAL-278518 :: [TorrentDay] :: Error while searching TorrentDay, skipping: __str__ returned non-string (type Error)

I have tried and been searching for hours on a fixed. Iv updated all my python and openssl still nothing.

SR Version:	BRANCH: (master) / COMMIT: (cfe3b40b30ecec5c1838a5b6898bd79faf0ea762) 
SR Locale:	('en_CA', 'UTF-8')
SR Config file:	/Applications/SickBeard/config.ini
SR Database file:	/Applications/SickBeard/sickbeard.db
SR Cache Dir:	/Applications/SickBeard/cache
SR Log Dir:	/Applications/SickBeard/Logs
SR Arguments:	[]
Python Version:	2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

**Comment by fernandog** [comment]
See: http://git.io/vJrkM
