### ISSUE TITLE
Torrage down, causing Failed Download Error

### ISSUE THREAD

**Issue by alzeric** [SiCKRAGETV/sickrage-issues#1552]
Appears that torrage.com is offline, making it impossible to magnet to torrent download.

Search Provider: The PirateBay
OS: Windows 7 Pro 64 bit
Python Ver: 2.7.9
SickRage Branch: Dev 
Reason Using Dev Branch: Only way The Piratebay will work, due to the SSL issue.

2015-05-08 14:12:21 WARNING  SEARCHQUEUE-BACKLOG-261557 :: Connection error ('Connection aborted.', gaierror(11004, 'getaddrinfo failed')) while loading URL http://torrage.com/torrent/da468814f986c4ca2801539d292958c41909e3eb.torrent
2015-05-08 14:11:06 INFO     SEARCHQUEUE-BACKLOG-261557 :: Downloading Masters.of.Sex.S02E02.HDTV.x264-ASAP. from ThePirateBay
2015-05-08 14:11:06 WARNING  SEARCHQUEUE-BACKLOG-261557 :: Failed to download result

Couldn't we handle Magnet to Torrent conversion locally, instead of relying on a 3rd party website?
Possibly something like this, 
https://github.com/danfolkes/Magnet2Torrent/blob/master/Magnet_To_Torrent2.py

I've not tested it, just offering this as an example I found plenty of other examples of this very function, however if we could offload relying on 3rd parties the more stable SickRage could become.

EDIT: Looks like Zoink.ch is down as well...
Quick fix
Edit
line 159,159,160

// Comment out 'http://torrage.com/torrent/' + torrent_hash.lower() + '.torrent',
// Save, Restart SickRage

                urls = [
                    #'http://torcache.net/torrent/' + torrent_hash + '.torrent',
                    #'http://zoink.ch/torrent/' + torrent_hash + '.torrent',
                    #'http://torrage.com/torrent/' + torrent_hash.lower() + '.torrent',
                    'http://btcache.me/torrent/' + torrent_hash + '.torrent',  #added new cache url, this was the only one I could find that successfully converted a magnet link
                ]

EDIT 2: I'm not a Python Guru or anything, actually know just enough to break things.  I did however make the edit below to the generic.py provider script. It incorporates py-libtorrent and the Magnet2Torrent function I was mentioning above.  I finally was able to get it to work reliably. Successfully takes the magnet links and saves them as a torrent file in your default download place (i use blackhole).  Feel free to taunt me, laugh, belittle or whatever it's a hack job for sure, if you guys want to use it or not feel free.  Possibly optimize it, if possible.

**Comment by miigotu** [comment]
I'll check into this. Good idea.

**Comment by miigotu** [comment]
Just looked at magnet_to_torrent2, it imports libtorrent. I think if we import that we should just be downloading the torrents directly within SR lol.

**Comment by miigotu** [comment]
btcache has a captcha. torcache is working.

**Comment by alzeric** [comment]
Yeh unfortunately there really isn't a way to generate a .torrent file without connecting to the swarm, which is why libtorrent a required import.

As far as torrenting directly with SR, it doesn't have to be that involved. Plus I don't believe that is the main idea behind SR anyways. (side note: i do realize you were being sarcastic lol) Being that it connects to the swarm each time it's a bit slower then the current method, however SR wouldn't be dependent upon a web service (cache website) that could go down at anytime.

Now AFAIK PirateBay is the only provider that has went 100% magnet files anyways, so I guess this problem is kinda confined to a small portion of SR's ability.  Honestly I'm surprised more tracker sites haven't went 100% magnet already, considering it's way less bandwidth and server resources on their end since there is nothing for the user to download (typical .torrent file is ~14k-28k, doesn't seem like alot but with a metric butt-ton of daily users constantly downloading .torrent files that adds up) it's just another URL like any other link on the page.

I was just offering an alternative solution.  Being that as far as public trackers go TPB pretty much has the most seeds/peers available.  When using KickAss i found that SR found results for most shows I added, however for backlog ep's the seeds were usually around the 0-5 range.  Now doing a search for the same quality/EP name manually on TPB I found results with 200 - 6000 seeds available for the exact same episode.

Which is what initially prompted me into trying to get everything working smoothly with TPB.

**Comment by miigotu** [comment]
I did commit a change that commented zoink and torrage, but torcache is working. Connecting to the swarm directly isnt an option, unless we were to build our own torrent client into SR (to make it worth importing libtorrent) because then end users would be required to run SR behind their VPN as well if they use one, and they might not realize they need to run SR behind the VPN.

**Comment by miigotu** [comment]
I'll close this now, as torrage/zoink are disabled in the tree now. Maybe we will look at adding some sort of libtorrent functionality in the future, but we can't do that now.

**Comment by giggio** [comment]
@miigotu I am having the same problem Torcache.net now. It seems they are deleting some torrents. I tried to manually upload 2 torrents that they are responding with 404, when I did that they answered with "deleted torrent".
Is there any work around on this? This is basically giving Torcache the decision of what I can download or not.

**Comment by giggio** [comment]
Here is what is going on with Torcache.net:
![torcache](https://cloud.githubusercontent.com/assets/334958/7995012/8a2bdcc0-0ae8-11e5-907e-1c18beed1fc6.png)
