### ISSUE TITLE
[APP SUBMITTED]: No JSON object could be decoded

### ISSUE THREAD

**Issue by Quiptix** [SiCKRAGETV/sickrage-issues#1554]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 10:19:51) [GCC 4.3.6]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@cfe3b40b30ecec5c1838a5b6898bd79faf0ea762
Link to Log: https://gist.github.com/63e45ce0a30dbfb513a2
### ERROR
```
FINDPROPERS :: [Rarbg] :: Rarbg json load failed.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by konomimaster** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 22 2015, 23:26:38) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@cfe3b40b30ecec5c1838a5b6898bd79faf0ea762
Link to Log: https://gist.github.com/daf3c768b4d94f9856ab
### ERROR
```
SEARCHQUEUE-BACKLOG-80301 :: [Rarbg] :: Rarbg json load failed.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rarbg** [comment]
@konomimaster @Quiptix disable your proxy for rarbg
@fernandog close this ticket :)

**Comment by fernandog** [comment]
we need to change the rarbg code and other providers code that uses JSON and remove html tags or other texts when using proxy. all providers that uses JSON and user enable proxy this happens

**Comment by fernandog** [comment]
@abeloin @miigotu do you see another (better) solution to get this URL results:
https://gist.github.com/fernandog/5804141590f0d84e3449
https://gist.github.com/fernandog/97495e035ca99d17e86b

and extract the JSON part using
this regex?
https://regex101.com/r/lK1bL9/1

this regex is for rabg only. others providers need to use another regex.

**Comment by miigotu** [comment]
@fernandog json should be parsed directly as json, no need for regex.

**Comment by miigotu** [comment]
Only regex might be to remove any surrounding html around the json object.

**Comment by rarbg** [comment]
@miigotu 
there is no need for proxy while connecting to the api. but /\[\{"f":(.+?)\}\]/s

**Comment by miigotu** [comment]
@rarbg some people have to use proxy to get by firewalls in places like universities.

**Comment by rarbg** [comment]
@miigotu 
Can you confirm that our API domain is in fact blocked by any university ?

**Comment by miigotu** [comment]
@rarbg I would rather assume that at least one case exists where some corporation or university does block it and make connecting to it through proxy work, than to assume it is not blocked anywhere by anyone before we disallow proxifying the connection to the api and potentially getting a flood of issue reports about it. =P

**Comment by rarbg** [comment]
@miigotu you are already being flooded with tickets about it not working through proxy.. why dont you just make the code try it without a proxy and if the response is not a json ( in this case if it cant get a token ) then try through a proxy , reg the json out from the response & etc ? or even the other way will work - try proxy first , then fallback for a normal request

**Comment by miigotu** [comment]
I'll have to actually try connecting myself through proxy and see what response i get. If there is no other way then a fallback is an acceptable/responsible solution, as long as I make the fallback optional to the user.  IE: Where they set proxy, add a check box to allow/disallow json to fallback to a normal request. 

I'm sure some people would like to know if they are connecting to torrent sites without proxy for any reason regardless of port/protocol if they are using a proxy to begin with, as there are many reasons someone might use a proxy. Some of us have tinfoil hats lawl.

**Comment by rarbg** [comment]
@miigotu believe me , my hat is bigger than yours :D

**Comment by fernandog** [comment]
@miigotu why can't we do a simple check. if proxy is enabled, use the regex to filter the JSON content? seems so easy.

@rarbg are you talking about something like this? I would add this to all providers. Always try normal and then proxy.
https://github.com/SiCKRAGETV/sickrage-issues/issues/869

The problems is that some private providers mat ban users when using diff IPs or proxy

**Comment by rarbg** [comment]
@fernandog yes , exactly :)

**Comment by fernandog** [comment]
@miigotu 

should we add the regex check here?
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/providers/rarbg.py#L286

https://github.com/SiCKRAGETV/sickrage-issues/issues/1554#issuecomment-101455160

**Comment by miigotu** [comment]
I'm still not 100% confident how I would like to proceed here, so I haven't made a move yet on it.  I tend to not make changes until I am confident it is the best course of action.

I need a log where this error occurs which has debug enabled, with the full log, as the ones app-submitted do not have the actual data dump, only a partial traceback. I'm not comfortable signing off on a regex that I cannot verify is correct myself.

**Comment by miigotu** [comment]
Ok, after investigating, some regex should fix this adequately.

**Comment by miigotu** [comment]
This is a pain. The proxies do not support ssl, so I have added a retry without https. I have also added a regex for the json data, to strip away the proxy's spam.  Waiting on my db to be populated for a test.

**Comment by miigotu** [comment]
@rarbg Did you know eztv.ch is hotlinking to your download.php?
```
https://eztv.ch/ep/131107/murder-in-the-first-s02e02-hdtv-x264-lol/
has a link to:
http://rarbg.to/download.php?id=9sq5j8n&f=Murder+in+the+First+S02E02+HDTV+x264-LOL+%5Beztv%5D-%5Brarbg.to%5D.torrent
```

**Comment by rarbg** [comment]
@miigotu 
Im aware , however i cant do anything about it.
1. Because hes linking from http -> https no referer is sent so i cant kill it by referer
2. Even if i ban the *eztv* with no ref , he immediately changes it to something else
So i cant do anything about it

**Comment by miigotu** [comment]
@rarbg Only allow download.php via https then? We only need the api via http.

**Comment by rarbg** [comment]
@miigotu 
Not all users use https ;)
