### ISSUE TITLE
Media Migration (Existing Media)

### ISSUE THREAD

**Issue by syrys** [SiCKRAGETV/sickrage-issues#1555]
So, im wanting to migrate a bunch of shows added to Sickrage that are stored in one location to another.

For example, lets say i have a show, "Simpsons", which is stored in "C:/Media/Simpsons", which is added to sickrage and works well. But one day, i wanted to move the show to "D:/Media/Simpsons". What is the easiest way to do this? Currently, i found that i have to copy paste the current media folder to the destination location, then goto sickrage and edit the show and point it to the new location. 

Does sickrage have the ability to move the show by it self?

What if i wanted to migrate 5, 10, even 50 shows at once? is there an easy way to do them all at once?

Cheers.

**Comment by fernandog** [comment]
No. No.

**Comment by syrys** [comment]
Can i request a feature for "moving" media? Im not sure if this was requested before, but it sounds like a super useful feature thats probably not too hard to implement?
