### ISSUE TITLE
Connectivity Issues

### ISSUE THREAD

**Issue by konomimaster** [SiCKRAGETV/sickrage-issues#1557]
Hi. 
I've just set up Sickrage on my Synology NAS and i'm having problems with Sickrage not being able to connect to torrentsites.

Branc: Master
Commit: cfe3b40b30ecec5c1838a5b6898bd79faf0ea762
OS: DSM 5.2-5532 (Synology NAS os)
Python Version: 2.7.9

The log looks like this:
https://gist.github.com/konomimaster/5a5aa6cad07030faad71#file-gistfile1-txt

**Comment by miigotu** [comment]
This works for everyone else, so it is a firewall or network connection issue outside of the scope of our support.

**Comment by konomimaster** [comment]
Which ports do Sickrage use for this?

**Comment by miigotu** [comment]
Not 100% sure of every port we use, but I assume at least 80, 8080, 443
