### ISSUE TITLE
Incorrect color coding of qualities

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#1558]
On the latest Developement version on the history page SDTV and HDTV are now black just like the N/A color instead of the usual red and green
also on the Shows page they are invisible only the text appears
I believe it was caused by :https://github.com/SiCKRAGETV/SickRage/pull/1885

**Comment by matigonkas** [comment]
![history page](https://cloud.githubusercontent.com/assets/10121067/7552369/a38169e6-f6a8-11e4-8fad-f6e933f0c2be.png)
![show page](https://cloud.githubusercontent.com/assets/10121067/7552370/a39bf374-f6a8-11e4-92e0-9231c9b0caf3.png)

**Comment by Thraxis** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1897
