### ISSUE TITLE
[APP SUBMITTED]: [Error 32] The process cannot access the file because it is being used by another process: u'K:\\uTorrent Completed\\RuPauls.Drag.Race.S07E08.Conjoined.Queens.1080p.WEB-DL.AAC2.0.H264-fabutrash.mp4'

### ISSUE THREAD

**Issue by gregtotheizzo** [SiCKRAGETV/sickrage-issues#1559]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@cfe3b40b30ecec5c1838a5b6898bd79faf0ea762
Link to Log: https://gist.github.com/edb01cc853bf02684365
### ERROR
```
POSTPROCESSER :: Unable to move file K:\uTorrent Completed\RuPauls.Drag.Race.S07E08.Conjoined.Queens.1080p.WEB-DL.AAC2.0.H264-fabutrash.mp4 to Z:\Media\TV Shows\RuPaul's Drag Race\7x08 - Conjoined Queens.mp4: error 32 : The process cannot access the file because it is being used by another process
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by alzeric** [comment]
This means uTorrent is still actively accessing the file and the handle hasn't been released.  This is not a SR issue.

If you have uTorrent setup to move files after completion (which is usually the only time I get this message) check to see if it's currently still being moved.  (if you are moving from one drive to another this process can take some time.  If you have the download folder and the move to after completed folder on the same Drive/Volume the move time usually is significantly reduced.

**Comment by miigotu** [comment]
Alzeric is correct. Either put your downloaded and completed dirs for utorrent on the same partition/drive or dramatically increase the time between post processing attempts.
