### ISSUE TITLE
Ignored Words not working

### ISSUE THREAD

**Issue by alzeric** [SiCKRAGETV/sickrage-issues#1560]
Branch: Dev
Python Ver: 2.7.9
OS: Win 7 Pro 64 Bit

As you can see the string SWESUB is listed as a ignore word
![r9ggzle](https://cloud.githubusercontent.com/assets/5651849/7552717/a54741fa-f68b-11e4-94da-21d668864aca.png)

However SR still considers it a result
![cnq6a7m](https://cloud.githubusercontent.com/assets/5651849/7552722/ed793a78-f68b-11e4-9b04-ffbb41787fc3.png)

![cnq6a7n](https://cloud.githubusercontent.com/assets/5651849/7552723/33475c7e-f68c-11e4-8a57-1e9522a39778.png)

**Comment by pct00** [comment]
seems to happen always on multi episode torrents

**Comment by fernandog** [comment]
@alzeric try remove the space after the comma

**Comment by pct00** [comment]
hi
still happens after latest update of develop branch

please let me know if you want logs

**Comment by Grincheux41** [comment]
Hi

I confirm it is not fixed, I am on the version 4.0.39 and it still happens :(
