### ISSUE TITLE
[APP SUBMITTED]: unsupported locale setting

### ISSUE THREAD

**Issue by thecolorchanges** [SiCKRAGETV/sickrage-issues#1561]
### INFO
Python Version: **2.6.5 (r265:79063, Jul 24 2010, 21:39:31) [GCC 4.2.3]**
Operating System: **Linux-3.0.3-unRAID-i686-AMD_Athlon-tm-_II_Neo_N36L_Dual-Core_Processor-with-slackware-13.1.0**
Locale: UTF8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@762bb1be47a1e027acd65af706c24ca5bdac794e
No Log available with ERRORS: 
### ERROR
```
MAIN :: Check scene exceptions update failed. Unable to get URL: https://raw.githubusercontent.com/SiCKRAGETV/sr_tvrage_scene_exceptions/master/exceptions.txt
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
SSL error https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors
Update python, 2.65 is outdated.
