### ISSUE TITLE
[APP SUBMITTED]: CHECKVERSION :: Local branch is ahead of master. Automatic update not possible.

### ISSUE THREAD

**Issue by milesje** [SiCKRAGETV/sickrage-issues#1562]
### INFO
Python Version: **2.7.6 (default, Sep  9 2014, 15:04:36) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]**
Operating System: **Darwin-14.1.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@46cf058b48c1770702e8fd0e4ebca238d3064a80
Link to Log: https://gist.github.com/03dde7e145e7b0f04be6
### ERROR
```
CHECKVERSION :: Local branch is ahead of master. Automatic update not possible.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
you started with someone else's fork/patch. rename your SR source, clone sickrage again, and copy in your sickbeard.db and config.ini.
