### ISSUE TITLE
[APP SUBMITTED]: no such column: rls_ignore_words

### ISSUE THREAD

**Issue by wordguy** [SiCKRAGETV/sickrage-issues#1564]
### INFO
Python Version: **2.7.6 (default, Nov 10 2013, 19:24:18) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@bf2baf309bd01683fdc06d57ece0b89d53b4a180
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-ADD :: DB error: no such column: rls_ignore_words

https://gist.github.com/d103b9222d4e0f82dc80.git
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by wordguy** [comment]
Everytime I try to add my existing shows I get the following error.
Log of error
<script src="https://gist.github.com/wordguy/d103b9222d4e0f82dc80.js"></script>

**Comment by miigotu** [comment]
Dont know how you did that, the column is created on fresh install and DB upgrade. Unless you know how to modify the database using sql queries, you will have to create the database from scratch.

**Comment by wordguy** [comment]
Ok thanks for the reply. How do I create the database from scratch?


Sent from my Samsung device

-------- Original message --------

**Comment by miigotu** [comment]
stop sickrage, `rm sickbeard.db*` and start sickrage. You will have to add all of your shows back to SR.
