### ISSUE TITLE
[APP SUBMITTED]: invalid literal for int() with base 10: '3/'

### ISSUE THREAD

**Issue by ntrantham** [SiCKRAGETV/sickrage-issues#1568]
### INFO
Python Version: **2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@bf2baf309bd01683fdc06d57ece0b89d53b4a180
No Log available with ERRORS: 
### ERROR
```
Thread-71 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 1668, in setStatus
    if not statusStrings.has_key(int(status)):
ValueError: invalid literal for int() with base 10: '3/'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Without logs we cant do anything...
