### ISSUE TITLE
[APP SUBMITTED]: HTTPSConnectionPool(host='www.torrentbytes.net', port=443): Max retries exceeded with url: /takelogin.php (Caused by ConnectTimeoutError(<lib.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f459a5ad990>, 'Connection to www.torrentbytes.net timed out. (connect timeout=30)'))

### ISSUE THREAD

**Issue by FlyGuy94** [SiCKRAGETV/sickrage-issues#1572]
### INFO
Python Version: **2.7.9 (default, Mar 23 2015, 00:07:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@bf2baf309bd01683fdc06d57ece0b89d53b4a180
Link to Log: https://gist.github.com/2f7d7dd6f48070c59cc5
### ERROR
```
SEARCHQUEUE-BACKLOG-220661 :: [TorrentBytes] :: Unable to connect to TorrentBytes provider: error HTTPSConnectionPool(host='www.torrentbytes.net', port=443): Max retries exceeded with url: /takelogin.php (Caused by ConnectTimeoutError(<lib.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f459a5ad990>, 'Connection to www.torrentbytes.net timed out. (connect timeout=30)'))
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by maxcore** [comment]
same here

**Comment by alzeric** [comment]
www.torrentbytes.net  appears to be down, which is why you are getting this error.
Simply means SR tried the set number of times to try to login, but was unsuccessful.

The reason it's unsuccessful is because the website / server is currently offline, this is a torrentbytes problem not a problem with SR.

**Comment by neoatomic** [comment]
@alzeric Thanks for reporting that the site is down.

I close this as we cant do anything about it till the site is back up again or gets a new domain.
