### ISSUE TITLE
Broken Funimation Channel logo

### ISSUE THREAD

**Issue by Trapizomba** [SiCKRAGETV/sickrage-issues#1574]
Funimation Channel logo not showing at home screen

**Comment by alzeric** [comment]
@Trapizomba You can temporarily fix this by going into your here
<path to SickRage>/gui/slick/images/network
Find "funimation.png" make a copy of this file and rename to copy to "funimation channel.png"

@neoatomic - FYI

**Comment by neoatomic** [comment]
@Trapizomba What is the exact name that is shown where the logo should be.? Is it "funimation channel" ? 
I need to know that to add the logo to SickRage.

**Comment by Trapizomba** [comment]
<div class="show" id="show245451" data-name="Appleseed XIII" data-date="5000000100.0" data-network="FUNimation Channel" data-progress="0">
