### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-125051 :: Unable to parse Shark.Week.2013.Top.Ten.Sharkdown.PROPER.HDTV.x264-W4F into a scene name. If it's a valid one log a bug.

### ISSUE THREAD

**Issue by 88keyz** [SiCKRAGETV/sickrage-issues#1575]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-52-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@bf2baf309bd01683fdc06d57ece0b89d53b4a180
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-125051 :: Unable to parse Shark.Week.2013.Top.Ten.Sharkdown.PROPER.HDTV.x264-W4F into a scene name. If it's a valid one log a bug.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Invalid scene name. There is no season, episode, absolute number, or anything else to parse in that name.
