### ISSUE TITLE
[APP SUBMITTED]: Failed Unrar archive Ray.Donovan.S01E04.720p.HDTV.x264-EVOLVE.part01.rar: Unrar: Archive CRC Error

### ISSUE THREAD

**Issue by calimada** [SiCKRAGETV/sickrage-issues#1577]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@bf2baf309bd01683fdc06d57ece0b89d53b4a180
Link to Log: https://gist.github.com/b999c841683ec313675b
### ERROR
```
POSTPROCESSER :: Failed Unrar archive Ray.Donovan.S01E04.720p.HDTV.x264-EVOLVE.part01.rar: Unrar: Archive CRC Error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Damaged/corrupt Rar file.
