### ISSUE TITLE
error when use a fix for "SSL Error" https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors in Qnap (ARM)

### ISSUE THREAD

**Issue by neo4matrix** [SiCKRAGETV/sickrage-issues#1580]
Hi, when i try to fix the Error SSL (https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors) in my qnap using the following command:

curl https://bootstrap.pypa.io/get-pip.py -L -k | python2.7

respond:
/tmp/tmpV20paz/pip.zip/pip/_vendor/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
Collecting pip
/tmp/tmpV20paz/pip.zip/pip/_vendor/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
/tmp/tmpV20paz/pip.zip/pip/_vendor/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.

  Could not find a version that satisfies the requirement pip (from versions: )
  No matching distribution found for pip

Why?thanks

**Comment by Tlabok** [comment]
This happens on a Qnap with Intel (439 Pro) as well.

I have been trying at least six different solutions over the past weeks, but they all fail somewhere along the line with different errors.

For now I have disabled the indexers that require ssl. Maybe someday we will get an updated Python package for Qnap, but I do not have high hopes.

**Comment by neo4matrix** [comment]
Try this guide:
http://gleenders.blogspot.it/2014/04/install-python-pip-on-qnap-nas.html

**Comment by Tlabok** [comment]
Thanks, but that is one of the solutions I already tried.

**Comment by neo4matrix** [comment]
What are the indexers to disable?

**Comment by Tlabok** [comment]
I my case, just rarbg.

**Comment by Tlabok** [comment]
You can disable all indexers, then turn them on one by one, each time performing a backlog search and waiting for the error.

**Comment by neo4matrix** [comment]
kickass work for you?

**Comment by Tlabok** [comment]
Yep.

**Comment by superketto** [comment]
Hi, i'm neo4matrix i have lost my account, then about the issue, i have found and half-solutions:
- uninstall from app market Python Qpkg
- from ssh following this step:
   ipkg update
   ipkg install python27 (2.7.3 !!)
   ipkg install py27-setuptools
   ipkg install gcc
   ipkg install openssl-dev
- now from the directory ../optware/ python  bin (find by find) launch:
  curl https://bootstrap.pypa.io/get-pip.py -L -k | python2.7
  and
   pip2.7 install -U setuptools pip pyopenssl==0.13.1

now ...everything is installed without errors, but when launch sickrage go out with the error " Python Disable", i try an add the python binary in opt/bin but nothing to do.
In the sickrage.sh reference is made to python.sh installed by QPKG.

Any idea?
bye

**Comment by rarbg** [comment]
@fernandog maybe the better approach here will be to allow the user to use the api without https ?

**Comment by miigotu** [comment]
@rarbg same as the proxy thing, we don't want traffic unencrypted without at least a warning and option to the user. These qnap errors are due to a bug in qnap and their lack of support to fix it.

**Comment by rarbg** [comment]
@miigotu i ment give them an option to choose if the api should fallback to http when https is not working

**Comment by miigotu** [comment]
Sure, as long as the providers will allow it. Many of them force SSL.

**Comment by rarbg** [comment]
@miigotu i think the option should be per provider anyways :)

**Comment by bartley69** [comment]
I'm also getting errors and unable to grab shows automatically or manually, any fixes working?

<pre>
2015-05-26 15:48:54 SEARCHQUEUE-MANUAL-2594 :: Check scene exceptions update failed. Unable to get URL: https://raw.githubusercontent.com/SiCKRAGETV/sr_tvrage_scene_exceptions/master/exceptions.txt
2015-05-26 15:36:57 SEARCHQUEUE-BACKLOG-248683 :: Check scene exceptions update failed. Unable to get URL: https://raw.githubusercontent.com/SiCKRAGETV/sr_tvrage_scene_exceptions/master/exceptions.txt
2015-05-26 15:36:37 SEARCHQUEUE-BACKLOG-2594 :: Check scene exceptions update failed. Unable to get URL: https://raw.githubusercontent.com/SiCKRAGETV/sr_tvrage_scene_exceptions/master/exceptions.txt
2015-05-26 15:36:24 MAIN :: Check scene exceptions update failed. Unable to get URL: https://raw.githubusercontent.com/SiCKRAGETV/sr_tvrage_scene_exceptions/master/exceptions.txt
</pre>

**Comment by miigotu** [comment]
@bartley69 As soon as fernandog gives admins access to the scene exceptions repo, I'll fix that.

**Comment by neoatomic** [comment]
Main wile the scene exceptions repo's have been added. So Error should be fixed.

**Comment by djerro123** [comment]
After many, many attempts to fix this issue on my QNAP TS-112P, i have finally found a dirty solution; i've downgraded my firmware back to 4.1.2 (jan 2015). The whole SSL issue is now 'gone'. this made me crazy, i had absolutely NO downloads anymore and had to do everything manually. Glad it works again :+1:

**Comment by neoatomic** [comment]
Thanks for letting us know.
Not sure if it helps but many users report that installing a newer/recent package also solves the SSL problems. http://apps.qnap.community/11-community/17-qsickrage

**Comment by rarbg** [comment]
Arent there vulnerabilites in this older 4.1.2 firmware? 

----- Original Message -----

**Comment by miigotu** [comment]
@rarbg heartbleed.
