### ISSUE TITLE
[Feature Request] Change Log of new Features from within Sickrage

### ISSUE THREAD

**Issue by Freakadude** [SiCKRAGETV/sickrage-issues#1583]
There are lots of updates to Sickrage which is great and you can check the commits based on the provided link before upgrading which is also fine yet not the most readable or obvious format if you are not a developer yourself.

Would it be possible to have within the Sickrage GUI a seperate Icon under the Tool menu where also the Server Status etc are or wherever else to have a menu where you could check major or minor feature additions that have been done in an update? I am not talking about bugfixes etc but often i wonder if there have been any new features added in a larger update for instance and its not that obvious if one is not starting to look through all the little menus to see that maybe there is a new menu entry somewhere or a new button or a new customizing feature or similar. 

I think for the average Joe user (like myself) it would help a lot if there would be a simple listing of newly added features under a separate menu in the GUI. E.g.: Update on 2015.05.10 - Added Feature Pause/Unpause button on individual show pages. Function: Pause or unpause shows.

Cheers

**Comment by tchirou** [comment]
I add my voice to this request

**Comment by MGaetan89** [comment]
This is a work in progress in SiCKRAGETV/SickRage#2086

**Comment by MGaetan89** [comment]
Should I close this?

There is now a "News" tab with SickRage message and a "Changelog" menu (in the right-most dropdown).
