### ISSUE TITLE
[Feature Request] correct way to request fanartPath in .tmpl file

### ISSUE THREAD

**Issue by Goeny** [SiCKRAGETV/sickrage-issues#1585]
I am working on a new template for Sickrage.
One of the features i want to build in are full-page backgrounds with fanart from the "opened" show.

Right now i am using ajax to request a fixed url from thetvdb and use that to display the fanart image.
Since Sickrage has the option to download fanart and banners and stuff, i am quite sure there is a better way on how to retrieve the show's fanart.

My current ajax code checks if the url exists, if not, add 1 to the last number in the filename and check it again. It does that until it finds an existing url and uses that to show the background.
```javascript
<script>
	\$(document).ready(function(){
		var fanartNumber = 1;
		
	    	function imageExists(url, callback) {
    			var img = new Image();
    			img.onload = function() { callback(true); };
    			img.onerror = function() { callback(false); };
    			img.src = url;
  		}

  		function validateImageURL(){
			var showID = $show.indexerid;
			var fanartURL = "http://thetvdb.com/banners/fanart/original/" + showID + "-" + fanartNumber + ".jpg";
        		var imageUrl = fanartURL;
      			imageExists(imageUrl, function(exists) {
	        		if(exists == true){
					$.backstretch(fanartURL, {fade:2000});
				}
				else{
					fanartNumber++;
					validateImageURL();
				}	
		      });
      		}
		validateImageURL();
	});
</script>
```

As i said, i am pretty sure there is something simple to use for the fanart url. Something like:
```$show.fanarturl``` but i simply don't know what i should use.

anyone who can help me with this one?

Here are some screenshots of current progress.
![homescreen](https://cloud.githubusercontent.com/assets/3872395/7595510/dbabab88-f8e7-11e4-8644-d5a06af69262.png)
![shield-details](https://cloud.githubusercontent.com/assets/3872395/7595509/dba9f702-f8e7-11e4-97ec-0a43190cd087.png)
![vikings-details](https://cloud.githubusercontent.com/assets/3872395/7595508/dba9816e-f8e7-11e4-9f48-df58fa31ec6c.png)

**Comment by Thraxis** [comment]
There currently isn't anything for that.  I have a UI branch where I updated the current UI to show the fanart in the background and I implemented adding fanart to the image cache and using a simliar call as to that used by the one to show the posters and banners.  I'll create a PR for that code piece.

**Comment by Thraxis** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1911

**Comment by MGaetan89** [comment]
Does SiCKRAGETV/SickRage#1911 fixed this issue?

**Comment by neoatomic** [comment]
@MGaetan89 Yes, that solved it. 
However i would like to keep this open as a place where @Goeny can ask questions if needed.
He is creating a completely new theme for SickRage. https://github.com/Goeny/slicker
Actually, this week i did install it, and i must say i was impressed. Still needs some work, but all functionality is there.

![naamloos](https://cloud.githubusercontent.com/assets/7928052/8638613/2ff3faac-28c1-11e5-9ae1-9190e488db9c.png)

@miigotu Do you see an way/possibility to add the theme to develop.? 
Or is to difficult when merging commits to Master.? Only disadvantage is that we might get an app submitted ticket if there is a problem with the theme. (all trough that should be minimal as end-users are using master.)

**Comment by MGaetan89** [comment]
Ok, I understand. It looks great indeed!

Maybe the theme feature could be refactor a bit. I didn't put too much thought in it, but why not use the following directory structure:

```
gui/
    default/
        css/
        images/
        interfaces/
        js/
    light/
    slicker/
    ...
```

`default` is the default theme (in this example, it is the `dark` variant of the current theme) and contains all the resources required by SickRage (images, CSS, JS and template files).
In the other folders (in the above example, `light` and `slicker`), only the resources that are different than in the `default` theme need to be defined (ie. in the same folder and with the same file name).
When loading a theme, the resources are first looked in the corresponding folder, then in the `default` folder.

If someone wants to add a new theme to its SickRage installation, he just needs to upload the theme folder in `gui` (maybe rename it to `themes` or `styles` to be more explicit?) and choose it in the settings. An option in the settings could also be added to upload that theme folder.

**Comment by neoatomic** [comment]
@MGaetan89 That would be better off course. The problem however is that the templates need to be redone. And to make it even more complicated, we want to replace Cheetha code by Mako. That is requirement if we want to make SickRage compatible for Python3. https://github.com/SiCKRAGETV/sickrage-issues/issues/1497
But we need someone that knows Mako, as none of us are familiar with it. :(

**Comment by MGaetan89** [comment]
I see. I think it would be better to do it in multiple steps.
At least 2: change template engine, then change directory structure (or the other way around).

I don't know Mako either, but I'd be glad to help on this. As @miigotu already started, maybe I can help you?

**Comment by miigotu** [comment]
1. We can add a branch for this new theme on the main repo, and people can collaborate on it in that branch by making all the PR they want.  However, all changes outside the theme folder will need to be aproved. 

slicker shoud stay in gui/slicker (there is already a way to change what theme is loaded that way)

2. We can add a mako branch, and we just need to get a set of base templates working and go from there. Once it is started and the site loads, I'm sure other people will jump in and help since there is code to use as examples.

**Comment by miigotu** [comment]
http://localhost:9090/showPoster/?show=259063&which=fanart

**Comment by miigotu** [comment]
Do you also need a url or is the cached image enough?

**Comment by miigotu** [comment]
@Goeny I have made a branch on SickRage for your theme progress (slicker branch), you can PR work there (even if it isnt working totally yet) and it will get merged, as it is YOURS. Supporting code outside the theme will need reviewed, but you can pr that also. This will let people be able to help you complete it, help with communication, and stop any weasted work from duplicated efforts.

This way, once it is ready, or if you decide to stop working on it, others can continue it and eventually it can be used in main sickrage.

**Comment by miigotu** [comment]
Going to close this though, conversation can still continue in closed topics and everyone who was a part of it still gets notified. (I hate mass open issues... call me O.C.D.)

**Comment by Goeny** [comment]
I will update some tmpl files in the next few days and PR slicker to the slicker branch so other people can work on it aswell if they want.

As i wrote before on the forum, i am very busy at my new job, working on lots of code. So i am kinda sick and tired of lines of code when i get home. So further development from my side will be at a very slow rate.
