### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-34891 :: Unknown failure sending NZB to sab. Return text is: error

### ISSUE THREAD

**Issue by DrakeJones** [SiCKRAGETV/sickrage-issues#1589]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@bf2baf309bd01683fdc06d57ece0b89d53b4a180
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-34891 :: Unknown failure sending NZB to sab. Return text is: error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
SAB is working fine here. Probably SAB was not running, or you have not configured SAB right.?
Here is a guide that might help. : 
http://www.htpcguides.com/configure-sickrage-usenet-torrent-tv/
