### ISSUE TITLE
sabToSickBeard.py (You need to install python requests library)

### ISSUE THREAD

**Issue by hadouk3n** [SiCKRAGETV/sickrage-issues#1590]
Hello,

I have tried and tried and tried some more to fix an issue that reared it's ugly head after I fixed an issue with sickrage not updating. I run a Synology DS415.

Sickrage does what it is supposed to and sends files to SABnzbd to download and there is absolutely no issue in files being downloaded, unpacked, repaired etc... But when it comes to post processing SABnzbd will not send the file back to sickrage to finalise. Instead it sits there and gives me the error 'Exit(1) you need to install python requests library'. I have followed the suggested fixes in here https://sickrage.tv/forums/forum/help-support/general-support/15355-autoprocess-script-you-need-to-install-python-requests-library but they did not work. To be more specific i used putty to SSH into my NAS and: 

cd /volume1/@appstore/python/bin 

./pip install requests

i also updated with the --update command and all looked well. It still shows up as the error and wont post process unless I manually do it in sickrage.

I'm hoping it's an easy fix that one of you guys can help me out with and any help would be appreciated.

Thanks

**Comment by MichelRabozee** [comment]
Hi,

maybe you installed the latest DSM 5.2-5565 ? If yes, the python sys.path changed. The easiest way to fix the path to the site-packages is to go to /usr/local and make a symlink (as root):
$ cd /usr/local
$ mkdir lib
$ cd lib
$ ln -s ../python/lib/python2.7/

and it should work !

**Comment by neoatomic** [comment]
As this is not directly a SickRage problem i'm going to close this.
