### ISSUE TITLE
Blackhole Torrent Downloads Not Working in Master

### ISSUE THREAD

**Issue by hilly2k2** [SiCKRAGETV/sickrage-issues#1594]
Torrents being sent to blackhole are being marked by multiple torrent clients as invalid torrent files, and will not download. Same torrents can be downloaded with no problem by going to torrent sites on the web and manually downloading. Also, switching to dev branch has eliminated this issue. Persists on master.

**Comment by hilly2k2** [comment]
switching to dev branch had eliminated this issue, while it persisted on master. Unfortunately, I had to do a clean install of SickRage after an OS upgrade, and now I can't switch to dev at all; I get the error: "Can't switch branch as this will result in a database downgrade" when I try. 

This is really frustrating, to say the least, and basically renders SickRage useless. 

I don't think the logs would be of any help in deciphering this, since they just show SR searching for, finding and then saving magnet links to the blackhole folder. As far as SickRage knows, it's done it's job, but as I say, uTorrent, Deluge, Transmission, Vuze, they all say that what SR is depositing in the blackhole folder is not a valid torrent file.

Another clue, perhaps: I can copy and paste the magnet link shown in SR's log and initiate the download in every client. For whatever reason, it's the files that SR is dropping into the blackhole folder that are the problem. They just are​n't seen as valid torrent files by any client.

**Comment by miigotu** [comment]
You used someone elses fork or patch which upgraded the database. I can't even begin to be responsible for someone elses code. Reinstall SR.

**Comment by hilly2k2** [comment]
I did not use anyone else's fork or patch. I've only ever used the official SickRage releases. And, as I said in the ticket, I have reinstalled SickRage, as part of a completely fresh OS install, in fact. And the problem persists.

**Comment by miigotu** [comment]
Switching to develop is not a downgrade. Maybe you cloned from a different fork?

**Comment by hilly2k2** [comment]
I've been on the official SR since the get go. 

When I reinstalled yesterday, I did so from the curl link that's listed in the install guide in the forums. That's official, yes?

**Comment by miigotu** [comment]
I rarely go to the forums, so I have no idea what install guide your are referring to. a simple `https://github.com/SiCKRAGETV/SickRage.git` in the folder you want the SickRage dir, and setting up the start script is sufficient.

**Comment by hilly2k2** [comment]
Yep. That's exactly the version I cloned.

**Comment by miigotu** [comment]
@hilly2k2 there is no change between master and develop at the time you reported this besides added network images and updated init scripts. Either way, develop will be merged into master tomorrow. If your install still says cant downgrade db, you will have to figure that out (you could monkeypatch mainDB.py MAX_VER, change the version in your DB, or recreate the database.)
