### ISSUE TITLE
[APP SUBMITTED]: failedDownloads() got an unexpected keyword argument '039'

### ISSUE THREAD

**Issue by onno-vos-dev** [SiCKRAGETV/sickrage-issues#1597]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-40-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@281409d366b228a455879e02b2d55d3967db29e4
Link to Log: https://gist.github.com/4a48e1cbb992a9662cb9
### ERROR
```
Thread-18 :: Failed doing webui callback: Traceback (most recent call last):
  File "/etc/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
TypeError: failedDownloads() got an unexpected keyword argument '039'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

// Edit:
Just to add to the stacktrace:
The show I'm trying to delete from my failedDownloads list is:
"Orange_Is_The_New_Black_S01E01_I_Wasn&039;t_Ready_720p_BluRay_x264_DEMAND"

(Notice the encoding issue of "&039;" in the middle of the filename. Doing a manual delete directly inside the failed-table works just fine by simply executing the following command in a terminal:
````
sqllite3 failed.db
sqlite> delete from failed where release = "Orange_Is_The_New_Black_S01E01_I_Wasn&039;t_Ready_720p_BluRay_x264_DEMAND"
````

Which leads me to believe that the function: 
[failedDownloads in webserve.py, line 3419!](https://github.com/SiCKRAGETV/SickRage/blob/5ef5a0b27e27cf937011408cb55329d1bd21ce9d/sickbeard/webserve.py#L3419) can be executed correctly. Unfortunately I do too little python and even less front-end coding to go much further than this at this point.

**Comment by fernandog** [comment]
@miigotu should't we convert to unicode or utf-8 here before INSERT in failed.db?

https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/failed_history.py#L80

**Comment by miigotu** [comment]
@fernandog No, it should be followed back up the chain and found where it doesnt start off as unicode or utf-8, so that nothing else uses an incorrect variable type. That way you potentially fix multiple encode/decode issues in one fix and prevent monkey patching.

**Comment by fernandog** [comment]
but how to follow back ? huge debug isn't?

**Comment by miigotu** [comment]
Depends how far you need to go back. Is it broken in prepareFailedName? what all calls logFailed? thats the first step, make sure prepareFailedName returns the same type passed to it, and that the name passed to logFailed is the correct type. If it is, find where the name was modified before that.

**Comment by fernandog** [comment]
but if his locale is UT8-8, can't be a missing unicode/utf-8 conversion! maybe the torrent downloader saved with &039 in the file name and SR catch it. is it possible?

**Comment by miigotu** [comment]
I think if you add single quotes around the ? in the sql statements this goes away. SQL is choking on & and ; thinking you are passing another sql instruction.
