### ISSUE TITLE
[Feature Suggestion] Auto Magnet/.Torrent Open

### ISSUE THREAD

**Issue by alzeric** [SiCKRAGETV/sickrage-issues#1598]
@miigotu 

I know we discussed the libtorrent library as a major draw back to try and eliminate requirement of torrent cache sites... how about a different approach.  Currently i've editted my build to utilize os.startfile(filename) at the start of the downloadResult function in generic.py.  

     def downloadResult(self, result):
          """
             Save the result to disk.
          """
          logger.log(u"Attempting to execute magnet link in Tixati")
          os.startfile(result.url)       
          return False
         ... #the rest of function (although not used since we're returning false above

And it's working flawlessly and as I intend for my uses. Now by doing this we are missing the file check feature but, there isn't any file check in place here.  

I do realize that os.startfile is a Win32 only command so how about something like this.

    import os, sys, subprocess

    def open_file(filename):
        if sys.platform == "win32":
            os.startfile(filename)
        else:
            opener ="open" if sys.platform == "darwin" else "xdg-open"
            subprocess.call([opener, filename])

This would attempt to detect the OS being used Win32/Mac/*nix and then try using the appropriate execute command, to open the magnet link automatically in each OS.

Now with something like this I think a setting in the GUI or settings file would be in order so users could explicitly choose to have them auto-open or not.

Going this route would do away with any requirements on libtorrent and keep it VPN friendly.

**Comment by miigotu** [comment]
1.) most torrent clients can add magnet links directly, over an rpc call.
2.) xdg-open only exists for specific desktops, we cant account for how every nix device handles openning uri schemes. For example, there is no uri-handler if there is no desktop, so you wouldnt be able to run that on a pi, nas, etc.

Solution is to save the magnet, and attempt to resolve it with a btcache site, otherwise call the rpc procedure to the configured client, and fail on black hole.

**Comment by miigotu** [comment]
Also, may people don't have their torrent client on that same device as SR ^

**Comment by alzeric** [comment]
Np I'll keep throwing out ideas as they come to me lol, i'm sure something may stick at one point or another ;)
