### ISSUE TITLE
[Feature Request] Add support for WWE/UFC shows

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#16]
<a href="https://github.com/Rick7C2"><img src="https://avatars.githubusercontent.com/u/1856877?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Rick7C2](https://github.com/Rick7C2)**
_Tuesday Nov 25, 2014 at 23:50 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/952 (7 comment(s))_

----

Shows affected

WWE Pay-Per-View on WWE Network
LOG: http://pastebin.com/UgdaRmas
File Wanted: WWE.Survivor.Series.2014.720p.x264.DigitalDelboy

WWE Pay-Per-View
LOG: http://pastebin.com/FNAaX6dv
File Wanted 1: WWE.Wrestlemania.XXX.WWE.Network.WEB-DL.H264-XWT 
File Wanted 2: WWE.Wrestlemania.April.6th.2014.PDTV.x264-Sir.Paul 
File Wanted 3: WWE.WrestleMania.30.PPV.HDTV.x264-KYR 
File Wanted 4: WWE.WrestleMania.2014.720p 

UFC Fight Night
LOG: http://pastebin.com/9yJLPKyC
File Wanted: UFC.Fight.Night.57.720p.HDTV.x264-KYR

UFC PPV Events
LOG: http://pastebin.com/bN2m5uaB
File Wanted: UFC.180.PPV.720p.HDTV.x264-Ebi

**Comment by Rick7C2** [comment]
Just checking back on this issue. Are there any updates?

**Comment by fernandog** [comment]
sorry. not yet

**Comment by Ockingshay** [comment]
What is the actual issue as to why it's not picking up the names? Do you need access to a specialised tracker like MMA Tracker?
Looking back at their releases, they are all named like UFC.181.PPV.720p.HDTV.x264-KYR

**Comment by fernandog** [comment]
@Ockingshay honestly I don't know

@abeloin can you check this issue please? Don't know if is a regex issue

**Comment by abeloin** [comment]
@fernandog Definitely not only a regex issue.

Firstly, of all if any of those episodes are in tvrage's special category, they won't be seen by sickrage as it doesn't currently support it.
Secondly, the sports category look for date not semi-absolute number.
Thirdly, trying to search by absolute number won't work without manually assigning the number and even with that it will to distinguish between Prelims and the main event.

In the end, Sickrage, in it's current state, is ill equip to handle those episodes.

**Comment by DonCorleon** [comment]
Couldn't it just do a search for the episode name?
eg. Instead of using the Series title and season/episode number or air date, just have a setting to use the actual episode name? that would work for UFC as far as PPV and Fight night...... just my 2 cents :P

**Comment by abeloin** [comment]
@DonCorleon Yes that would be the goal ultimately and it involve creating a new sports category with all the regex associated with it; changes to the Post-process and providers(To be able to search via name), the name tests, propers/repack, and all the other parts in the code not enumerated in this post.

As you can see it's not a simple quick fix that can be done overnight. If you are interested in coding this functionality in Sickrage, you are more than welcome to do so.

**Comment by broyuken** [comment]
Has there been any behind the scenes development on this issue? I have tried with and without "sports" being checked off on the show and nothing shows up.

**Comment by fernandog** [comment]
@broyuken nothing. and no plans for now

**Comment by hadees** [comment]
It would be really nice to just be able to add my own custom regex

**Comment by saitoh183** [comment]
@fernandog 

Any news on this yet? Wanted to make my friedns switch over to SR so he can finally get WWE content automated.

**Comment by fernandog** [comment]
no. tons of issues. devs don't have too much time to SR now. myself included

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
