### ISSUE TITLE
[Feature Request] New Post-Process Method?

### ISSUE THREAD

**Issue by xbullet** [SiCKRAGETV/sickrage-issues#160]
I'm looking for the implementation of a feature to more easily allow for external/remote post processing scripting for soft and hard linking when SickRage does not have native access to the file system it's writing to.

Please consider adding a new Post-Process method to SR that will output the /currdir/cur_file_name and /newdir/new_file_name to a text file (ie: in a JSON format, or with a colon as a delimiter or something along those lines) to a text file, ie:
'Move'
'Copy'
'Symlink'
'Hardlink'
'Output to text file (for external processing)'

This is useful for those who run SickRage in virtual machine or on a separate machine to where the file shares it's using are hosted -- essentially, consider the situation you don't have native/local access to the machines file system, so symbolic links/hard links can't be used.

I currently manually edit the post processor code every time I update SickRage to do this already, which outputs the above info to a text file, and I have written a python script I run in a cron on the host machine to create the links on the file system.

As an example:
--Windows (Host)
----File shares
---- Arch Linux VM (Guest)
------ SickRage, Deluge, etc, which utilize SMB/CIF shares for download and post-process storage

The inherent flaw with this set up is that it is not possible to create symlinks/hardlinks on the NTFS partition remotely (via the Guest) unless the hosts drive is natively used instead of a VDISK (this is a big no for me), or by using an SSH connection every time post-processing occurs (which would have to be implemented into SickRage and would be OS dependant anyway -- so not ideal).

Would you consider adding a such a feature? 

Thanks

**Comment by gborri** [comment]
@echel0n @fernandog @xbullet the main idea that has come up to me is to make SR run on OpenShift that is a cloud PAAS and it's free having SR istance on openshift run 24/24h 7/7d and a SR istance on your local mediacenter/nas/PC wakeup only when needed (watching episode, downloading episode, etc)

**Comment by xbullet** [comment]
@gborri @echel0n @fernandog 

Ideally, maybe design to allow for multiple instances of SickRage to be ran and then allow for each instance to have it's own dynamic set of tasks to be assigned.

Example:
Instance 1 (local): In charge of all local actions, including post processing, show management/mass editing, etc

Instance 2 (external): Externally hosted, in charge of other tasks such as show searching, subtitle searching, etc

Alternatively, we could ditch the above idea (if it's not easily adaptable to SickRage) and look at implementing a simple output (as in my original post) for people running SickRage with some scriptering knowledge to manipulate SickRage's post-processing output and perform their own actions.

**Comment by miigotu** [comment]
Best idea I had for this is to just use a notification and a new pp option. PP still look for the files and when it finds it send out a notification to an app listenning on your file host. Either way I still think this is a ridiculous circumstance. If you are downloading files to the vm and then copying them to the host why not just cut out the vm altogether? It isn't making anything safer.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
