### ISSUE TITLE
[APP SUBMITTED]: Thread-41 :: git ls-remote --heads  returned : fatal: Unable to find remote helper for 'https'

### ISSUE THREAD

**Issue by EugenSeverins** [SiCKRAGETV/sickrage-issues#1601]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@1c1f80877b22531fe73aef61fad784b140fef605
Link to Log: https://gist.github.com/6c8c31cb8c8b2e7dfa07
### ERROR
```
Thread-41 :: git ls-remote --heads  returned : fatal: Unable to find remote helper for 'https'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors
