### ISSUE TITLE
Anime Whitelist/Blacklist Entries

### ISSUE THREAD

**Issue by kcoyo** [SiCKRAGETV/sickrage-issues#1603]
BRANCH: (master) / COMMIT: (bf2baf309bd01683fdc06d57ece0b89d53b4a180) 
Windows 8.1 x64 using Python 2.7.9 

I can no longer add to an Anime's Fansub Group for Whitelist/Blacklist. When typing a text on the text field and clicking "Add to Whitelist" it goes in the column entry as blank. It is selectable but blank and does not save after submitting the changes. 

As a workaround I have been using "Required Words" (i.e., HorribleSubs).

**Comment by Thraxis** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1912

**Comment by kcoyo** [comment]
Thanks Thraxis for addressing the issue. However, still experiencing it. Checked on IE, FF, and Chrome on Windows, still the same behavior as mentioned. Restarted the service as well to no avail.

Checked my sickbeard/show_name_helpers.py file and see that I have the changes made on lines 203-207 and 242-246.

**Comment by Thraxis** [comment]
The fix is currently on in Develop until it gets merged into master.  If you're on the master branch you will not see it yet.  Also the fix had nothing to do with the show_name_helpers.py file that was a fix for a different issue.

**Comment by kcoyo** [comment]
Ah, will look out for it. Thank you!
