### ISSUE TITLE
[APP SUBMITTED]: SHOWQUEUE-ADD :: Check scene exceptions update failed. Unable to get URL: https://raw.githubusercontent.com/SiCKRAGETV/sr_tvrage_scene_exceptions/master/exceptions.txt

### ISSUE THREAD

**Issue by shinkytron** [SiCKRAGETV/sickrage-issues#1604]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@bf2baf309bd01683fdc06d57ece0b89d53b4a180
Link to Log: https://gist.github.com/be3e7c4a8b4066016f10
### ERROR
```
SHOWQUEUE-ADD :: Check scene exceptions update failed. Unable to get URL: https://raw.githubusercontent.com/SiCKRAGETV/sr_tvrage_scene_exceptions/master/exceptions.txt
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by shaikio** [comment]
I have this error pop up in my logs like every 3 minutes. On a QNAP.

**Comment by fferraro87** [comment]
i've same error

**Comment by shinkytron** [comment]
I have QNAP as well. Can this error be ignored?

**Comment by neoatomic** [comment]
The problem is an old version of Phyton or missing files for SSL. (HTTPS)
Here is a FAQ that might give some help how to solve those problems. Otherwise ask on the QNAP forums for an update/correct install method.
https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors
