### ISSUE TITLE
qbittorrent not receiving seed ratio from provider options

### ISSUE THREAD

**Issue by goatbased** [SiCKRAGETV/sickrage-issues#1605]
Hi guys, quick feature request here. I'm trying to ditch utorrent and think that qbittorrent may be a good candidate. It would be nice, however, if seed ratios configured on specific providers would make their way to the qbittorrent though. Currently, all torrents are set as "default" even though they were added by SickRage and all of my providers have custom thresholds set.

Happy to give more detail if you have questions!

**Comment by neoatomic** [comment]
@goatbased Looking at the API from qbittorrent that is not possible. So it cant be implemented by the SickRage developers.
