### ISSUE TITLE
Fresh install,  Unable to download shows off NZB

### ISSUE THREAD

**Issue by JeffWScott** [SiCKRAGETV/sickrage-issues#1606]
I'm new to Sickrage and have been using Sickbeard for over 5 years now.  I can't seem to get Sickrage to download anything.  The indexer I'm using is NZB.su.  I believe I have everything setup correctly (the same way Sickbeard is) but I it just keeps coming back telling me it couldn't find episodes.

Here is the log:
SEARCHQUEUE-MANUAL-194031 :: Unable to find a download for: [Bob's Burgers - 5x19 - Housetrap]
SEARCHQUEUE-MANUAL-194031 :: [nzb.su] :: Performing episode search for Bob's Burgers
SEARCHQUEUE-MANUAL-194031 :: Building internal name cache for Bob's Burgers
SEARCHQUEUE-MANUAL-194031 :: No scene exceptions update needed
SEARCHQUEUE-MANUAL-194031 :: Beginning manual search for: [Bob's Burgers - 5x19 - Housetrap]
POSTPROCESSER :: Successfully processed
POSTPROCESSER :: Successfully processed
POSTPROCESSER :: Successfully processed

I used that particular episode as a test because it downloaded fine, using NZB.su in my Sickbeard install.

Can I get more verbose logging?  I Turned on debug logs but that didn't get me anything more then what is above.

Thanks!

**Comment by neoatomic** [comment]
@JeffWScott . See if you have enabled daily and backlog search for nzb.su. And check if you have set the category's what should be searched for nzb.su.

Here is a good config guide that should get you started. : http://www.htpcguides.com/configure-sickrage-usenet-torrent-tv/

**Comment by JeffWScott** [comment]
Can you explain to me why I have to choose the categories?   You don't havr to do that  in SickBeard.   What are they  for? 

I did a test where I added the same show  to both sickbeard and sickrage and then set the newest episode to wanted.   Sickbeard grabbed it within seconds.  Sickrage failed  to find any episodes.   So strange.   

Sickrage wll snatch episodes only when booting up.   Which doesn't make a whole lot of sent to me.

**Comment by neoatomic** [comment]
Categories give you the opportunity to search more specific. Reduce search time and overall load.
And allows selecting other categories then the defealt ones. This is only for custom nzb providers. 

Maybe your search time is set to fast. So that the last search hasn't completed and already a new one starts.?
As Sickrage snatches on booting that shows its works and that it is a setting that is causing the problem.

**Comment by JeffWScott** [comment]
Okay thanks for answering my questions.  I haven't had a chance to follow that guide but I'll give it a shot.
