### ISSUE TITLE
Searches not preserving special characters

### ISSUE THREAD

**Issue by Pontation** [SiCKRAGETV/sickrage-issues#1611]
I added a swedish show named "Ack Värmland" but sickrage was unable to find episodes because when it forms the search query for the pirate bay it converts ä to a.

This is from the debug log:
[ThePirateBay] :: Search string: https://thepiratebay.se/search/Ack.Varmland%20S01E08%7C1x08%20/0/7/200

This doesn't generate any hits but if I modify the url manually by replacing the a with ä, it does:
https://thepiratebay.se/search/Ack.Värmland%20S01E08%7C1x08%20/0/7/200

**Comment by neoatomic** [comment]
This might fix it. : https://sickrage.tv/forums/forum/help-support/general-support/12825-ensuring-your-locale-s-are-set-properly-to-avoid-unicode-issues

But when possible prevent using special characters at all.
