### ISSUE TITLE
[APP SUBMITTED]: RSSFeeds instance has no attribute 'rssDB'

### ISSUE THREAD

**Issue by dragonrm** [SiCKRAGETV/sickrage-issues#1612]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.8+-armv6l-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@bf2baf309bd01683fdc06d57ece0b89d53b4a180
Link to Log: https://gist.github.com/40dc1e96956afeb1b02b
### ERROR
```
SEARCHQUEUE-BACKLOG-24504 :: [Usenet-Crawler] :: Error while searching Usenet-Crawler, skipping: RSSFeeds instance has no attribute 'rssDB'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1493
