### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-264108 :: Unknown failure sending NZB to sab. Return text is: error

### ISSUE THREAD

**Issue by DrakeJones** [SiCKRAGETV/sickrage-issues#1616]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@bf2baf309bd01683fdc06d57ece0b89d53b4a180
Link to Log: https://gist.github.com/1fc74f56caaaf2328c8d
### ERROR
```
SEARCHQUEUE-BACKLOG-264108 :: Unknown failure sending NZB to sab. Return text is: error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
SAB is working fine here. Check your settings.

**Comment by L3rd** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@29c97fb37688d31bfa4b765d309647bbaddb335a
Link to Log: https://gist.github.com/19ee83368753e1f4a42a
### ERROR
```
SEARCHQUEUE-MANUAL-153021 :: [NZBs.org] :: Unknown failure sending NZB to sab. Return text is: 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by DrakeJones** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@3c63ee88e6e6ef033d841986decf7a3086fad7fe
Link to Log: https://gist.github.com/f2b98f7de68a30e904a5
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: Unknown failure sending NZB to sab. Return text is: error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by DrakeJones** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@3c63ee88e6e6ef033d841986decf7a3086fad7fe
Link to Log: https://gist.github.com/004b75eec4128bbada27
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: Unknown failure sending NZB to sab. Return text is: error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by DrakeJones** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@3c63ee88e6e6ef033d841986decf7a3086fad7fe
Link to Log: https://gist.github.com/d0aa0b5e8dea051f0916
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: Unknown failure sending NZB to sab. Return text is: error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by DrakeJones** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@3c63ee88e6e6ef033d841986decf7a3086fad7fe
Link to Log: https://gist.github.com/f22ff65b985bee6e7283
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: Unknown failure sending NZB to sab. Return text is: error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by DrakeJones** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@3c63ee88e6e6ef033d841986decf7a3086fad7fe
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: Unknown failure sending NZB to sab. Return text is: error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by DrakeJones** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@3c63ee88e6e6ef033d841986decf7a3086fad7fe
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: Unknown failure sending NZB to sab. Return text is: error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by DrakeJones** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@3c63ee88e6e6ef033d841986decf7a3086fad7fe
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: Unknown failure sending NZB to sab. Return text is: error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by DrakeJones** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@3c63ee88e6e6ef033d841986decf7a3086fad7fe
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: Unknown failure sending NZB to sab. Return text is: error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
