### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-263203 :: Failed to detect KODI version for 'localhost:8080', check configuration and try again.

### ISSUE THREAD

**Issue by jweese74** [SiCKRAGETV/sickrage-issues#1620]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/1c74aa13772f935316ea
### ERROR
```
SEARCHQUEUE-BACKLOG-263203 :: Failed to detect KODI version for 'localhost:8080', check configuration and try again.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Do what the error says, and make sure its enabled in kodi.

**Comment by jweese74** [comment]
I left my SB open and my kid tapped the wrong button, my apologies - I
blame, wife error :)
