### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-72454 :: Check scene exceptions update failed. Unable to get URL: https://raw.githubusercontent.com/SiCKRAGETV/sr_tvrage_scene_exceptions/master/exceptions.txt

### ISSUE THREAD

**Issue by vbab** [SiCKRAGETV/sickrage-issues#1623]
### INFO
Python Version: **2.7.3 (default, Dec 18 2014, 19:10:20) [GCC 4.6.3]**
Operating System: **Linux-3.2.0-83-generic-x86_64-with-Ubuntu-12.04-precise**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/fbb541b7337108f9b85c
### ERROR
```
SEARCHQUEUE-BACKLOG-72454 :: Check scene exceptions update failed. Unable to get URL: https://raw.githubusercontent.com/SiCKRAGETV/sr_tvrage_scene_exceptions/master/exceptions.txt
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1580

**Comment by vbab** [comment]
i kind of got it working upgrading linux and the kernal to 14 04 ubuntu   but more problems came up and i ended up reinstalling everything.
