### ISSUE TITLE
Re-Direct Loop. [Failed doing webui callback: Traceback]

### ISSUE THREAD

**Issue by drcations** [SiCKRAGETV/sickrage-issues#1624]
BRANCH: (master) / COMMIT: (26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9) 
Your operating system and python version: Ubuntu Server 14.04.2 LTS / Python 2.7.6
What you did: Launched Sickbeard and opened a chrome page to it's webui
What happened: Redirect Loop error from Chrome
What you expected: I expected Sickrage's webui to open
Link to a copy/paste of your logfile with clear debug info of the error on GIST:
https://gist.github.com/drcations/dd325b3a2a9f24af4b24

- The issue does not occur when i am SSH'd into the box from my desktop PC. Not sure if that is relevant. 
- I have checked multiple posts regarding similar issue to this and tried multiple fixes, all to no avail.
- I had a similar issue with sickbeard a few months ago, and the fix then was to use an older python version *i think*.

**Comment by miigotu** [comment]
Check that the file /home/dave/.sickrage/gui/slick/interfaces/default/home.tmpl exists, if it does check read permissions. Maybe your source has the wrong permissions, or SR is running as the wrong user.

**Comment by miigotu** [comment]
If the file exists and permissions are right for the desired user, check the user SR is running as with
'ps aux | grep -i sick'

**Comment by drcations** [comment]
@miigotu Thanks. All permissions are correct and it is running under the correct user. Could you explain your second comment a little further please.

**Comment by miigotu** [comment]
If you enter in a terminal `ps aux | grep -i sick` it will show you what user and group SR is running as, to verify that it is running as the correct user.

**Comment by drcations** [comment]
@miigotu I see, yes it is running under the correct user. The issues persists unfortunately.

**Comment by miigotu** [comment]
restarted SR?

**Comment by drcations** [comment]
I have.

**Comment by drcations** [comment]
`-rwxrwx--- 1 dave dave 26332 May 18 11:46 /home/dave/.sickrage/gui/slick/interfaces/default/home.tmpl`

`dave     24731 20.0  2.9 2754080 118768 ?      Sl   17:39   1:20 /usr/bin/python SickBeard.py -q --daemon --nolaunch --pidfile=/var/run/sickbeard/sickbeard.pid --datadir=/home/dave/.sickrage/
dave     25270  0.0  0.0  11752  2228 pts/0    S+   17:46   0:00 grep --color=auto -i sick`

**Comment by miigotu** [comment]
Strange yours has more permissions than mine. How did it get to be 770? Mine is 600 (although I think 664 is more appropriate).
Cheetah may be ignoring it because it is executable.

`chmod 664  /home/dave/.sickrage/gui/slick/interfaces/default/*`

**Comment by drcations** [comment]
i set it to 770. Changed it to 664, restarted, still no love.

**Comment by miigotu** [comment]
I would try backing up your config and databases, and doing a freshly cloned install, then adding your databases and config back in.

**Comment by miigotu** [comment]
Maybe too the /home/dave/.sickrage/gui/slick/interfaces/default folder has wrong permissions? Cheetah needs to be able to list contents of that folder.

`ls -ld /home/dave/.sickrage/gui/slick/interfaces/default`
`chmod 664 /home/dave/.sickrage/gui/slick/interfaces/default`
(774 works too, but there is nothing executable inside anyways.)

**Comment by Thraxis** [comment]
@drcations could you clarify this:
"The issue does not occur when i am SSH'd into the box from my desktop PC. Not sure if that is relevant."

Are you saying that if you log onto the box running sickrage with SSH to your account, when you open sickrage in chrome on your desktop works fine?

You don't happen to have an encrypted home folder do you?

**Comment by miigotu** [comment]
@drcations If you do have an encrypted home folder, install SR in a more appropriate place, like /opt/SickRage or /srv/SickRage.

Installing it in a home folder doesn't really make sense anyway, as it is a system wide service, not one that only runs for one user. Likewise, SR should be run as it's own user (sickrage) and own group (sickrage), and be added to the dave group, and the user dave added to the sickrage group.

File and folder permissions in the SR source should be left as they are when cloned. You may have to reboot before the sickrage user has the right permissions for the dave group, and vice versa.

**Comment by drcations** [comment]
Thanks for the help guys.

I deleted SR and then re-installed it under a specific sickrage user in /opt/sickrage, loaded the backup and it *seems* to be working now. I will keep an eye on it.
