### ISSUE TITLE
SEARCHQUEUE-DAILY-SEARCH :: qbittorrent: Failed Sending Torrent

### ISSUE THREAD

**Issue by papampi** [SiCKRAGETV/sickrage-issues#1625]
It seems some thing is changed in qbittorent 3.2 and SR can't send torrent to client 

### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-53-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: qbittorrent: Failed Sending Torrent
```
---
#### log
````
AA. Error: list index out of range
AARelease Group: ASAP
AASize: -1
AAName: Penny.Dreadful.S02E03.HDTV.x264-ASAP
AAQuality: SDTV
AAEpisode: [<sickbeard.tv.TVEpisode object at 0x7f1f3c70c1d0>]
AAExtra Info:
AAIndexError: list index out of range
AA    result.hash = re.findall('urn:btih:([\w]{32,40})', result.url)[0]
AA  File "/opt/sickrage/sickbeard/clients/generic.py", line 148, in _get_torrent_hash
AA    result = self._get_torrent_hash(result)
AA  File "/opt/sickrage/sickbeard/clients/generic.py", line 186, in sendTORRENT
AATraceback (most recent call last):
2015-05-18 09:12:40 ERROR    SEARCHQUEUE-DAILY-SEARCH :: qbittorrent: Failed Sending Torrent
2015-05-18 09:12:40 INFO     SEARCHQUEUE-DAILY-SEARCH :: Downloading Penny.Dreadful.S02E03.HDTV.x264-ASAP from EZTV
AA. Error: list index out of range
AARelease Group: KILLERS
AASize: -1
AAName: Battle.Creek.S01E12.HDTV.x264-KILLERS
AAQuality: SDTV
AAEpisode: [<sickbeard.tv.TVEpisode object at 0x7f1f3d6b2390>]
AAExtra Info:
AAIndexError: list index out of range
AA    result.hash = re.findall('urn:btih:([\w]{32,40})', result.url)[0]
AA  File "/opt/sickrage/sickbeard/clients/generic.py", line 148, in _get_torrent_hash
AA    result = self._get_torrent_hash(result)
AA  File "/opt/sickrage/sickbeard/clients/generic.py", line 186, in sendTORRENT
AATraceback (most recent call last):
2015-05-18 09:12:40 ERROR    SEARCHQUEUE-DAILY-SEARCH :: qbittorrent: Failed Sending Torrent
2015-05-18 09:12:40 INFO     SEARCHQUEUE-DAILY-SEARCH :: Downloading Battle.Creek.S01E12.HDTV.x264-KILLERS from EZTV
AA. Error: list index out of range
````

**Comment by papampi** [comment]
it seems if you log into the qbittorrent 3.2 webGUI, then it works with no errors until the session expires. and it start to gives error again.

**Comment by papampi** [comment]
changed it to blackhole and now I get these errors : 

### Log
```
2015-05-18 13:21:35 WARNING  SEARCHQUEUE-DAILY-SEARCH :: Failed to download result
AAInvalidSchema: No connection adapters were found for 'magnet:?xt=urn:btih:&dn=%5Beztv%5D%20Battle%20Creek%20S01E11%20HDTV%20x264-2HD%20-%20240.05%20MB&tr=udp://open.demonii.com:1337&tr=udp://tracker.coppersurfer.tk:6969&tr=udp://tracker.leechers-paradise.org:6969&tr=udp://exodus.desync.com:6969&xl=251710669'
AA    raise InvalidSchema("No connection adapters were found for '%s'" % url)
AA  File "/opt/sickrage/lib/requests/sessions.py", line 646, in get_adapter
AA    adapter = self.get_adapter(url=request.url)
AA  File "/opt/sickrage/lib/requests/sessions.py", line 567, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/opt/sickrage/lib/requests/sessions.py", line 461, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/opt/sickrage/lib/requests/sessions.py", line 473, in get
AA    resp = session.get(url)
AA  File "/opt/sickrage/sickbeard/helpers.py", line 1348, in download_file
AATraceback (most recent call last):
2015-05-18 13:21:35 ERROR    SEARCHQUEUE-DAILY-SEARCH :: Unable to save the file: No connection adapters were found for 'magnet:?xt=urn:btih:&dn=%5Beztv%5D%20Battle%20Creek%20S01E11%20HDTV%20x264-2HD%20-%20240.05%20MB&tr=udp://open.demonii.com:1337&tr=udp://tracker.coppersurfer.tk:6969&tr=udp://tracker.leechers-paradise.org:6969&tr=udp://exodus.desync.com:6969&xl=251710669'
2015-05-18 13:21:35 INFO     SEARCHQUEUE-DAILY-SEARCH :: Downloading [eztv].Battle.Creek.S01E11.HDTV.x264-2HD from eztv-rss
2015-05-18 13:21:35 WARNING  SEARCHQUEUE-DAILY-SEARCH :: Failed to download result
AAInvalidSchema: No connection adapters were found for 'magnet:?xt=urn:btih:&dn=%5Beztv%5D%20The%20Royals%20S01E10%20HDTV%20x264-LOL%20-%20277.28%20MB&tr=udp://open.demonii.com:1337&tr=udp://tracker.coppersurfer.tk:6969&tr=udp://tracker.leechers-paradise.org:6969&tr=udp://exodus.desync.com:6969&xl=290749153'
AA    raise InvalidSchema("No connection adapters were found for '%s'" % url)
AA  File "/opt/sickrage/lib/requests/sessions.py", line 646, in get_adapter
AA    adapter = self.get_adapter(url=request.url)
AA  File "/opt/sickrage/lib/requests/sessions.py", line 567, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/opt/sickrage/lib/requests/sessions.py", line 461, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/opt/sickrage/lib/requests/sessions.py", line 473, in get
AA    resp = session.get(url)
AA  File "/opt/sickrage/sickbeard/helpers.py", line 1348, in download_file
AATraceback (most recent call last):
```

**Comment by papampi** [comment]
seems there is a problem with eztv-rss not the SR.
http://feeds.feedburner.com/eztv-rss-atom-feeds/?format=xml

**Comment by kcoyo** [comment]
When I upgraded qBittorrent to v3.2.0, I also had issues with SickRage sending the download over to the client. However, BlackHole worked for me. Did you setup qBittorrent to download .torrent files from a specific folder or restarted SR?

I downgraded qBittorrent to v3.1.12 as a workaround until a fix is in for the new version.

**Comment by papampi** [comment]
BlachHole works fine on all providers but [eztv-rss]( http://feeds.feedburner.com/eztv-rss-atom-feeds)
I think its because EZTV has been hijacked by scammers, and so this feed has been removed
https://torrentfreak.com/eztv-shuts-down-after-hostile-takeover-150518/

**Comment by neoatomic** [comment]
@papampi Your logs show the error when downloading from EZTV.
So please clarify if this also happens with other providers and post a new log. And this error is only happening with 3.2 and not with 3.1.?  Also did you check the qBittorrent forums if there are any rapports about this.?  

To me this sounds more like a bug from the new qBittorrent 3.2. and not the SR code.

**Comment by papampi** [comment]
@neoatomic Thanks for your input.
I just checked again after disabled EZTV and also disable authentication for local host and used 127.0.0.1 in SR settings for qb and there is no more errors.
qb 3.2 changed webui authentication and [Remote Torrent Adder](http://code.google.com/p/remote-torrent-adder/) also doesnt work as before on it.

**Comment by Quiksmage** [comment]
Hi, while you can disable authentication for local host, there should be a way around having it on, correct? There are apps that have been updated to work with the webui of qbittorrent since its update, so I assume the same would be possible here. This is the new default on 3.2.0 and is the stable release of qbittorrent. If not, I understand, but it would be nice to have it working. Thanks a lot for all of your hard work on sickrage!

**Comment by fernandog** [comment]
New issues will be auto added here

**Comment by Quiksmage** [comment]
The main issue with the workaround is that what if you cannot have your torrent client on the same machine as sickrage, it cannot work. The only other way to get it working is to enable black hole and specify a directory.

**Comment by fernandog** [comment]
seems resolved. not more issues report
