### ISSUE TITLE
[Feature Request] Disable schedules Show Update

### ISSUE THREAD

**Issue by gborri** [SiCKRAGETV/sickrage-issues#1626]
Show update is resource consuming and if enabled update on snatch i think is not usefull to make it work on time base. Configuration checkbox is more than welcome.

**Comment by jepadgett3** [comment]
I agree. Not sure why anyone would want to update everyday, but the option to disable, or set to once a month would be awesome.

**Comment by Koal4** [comment]
The problem with 'update on snatch'  is that you will miss the shows that are on break. Most of the times airdates are only released a couple of weeks in advance

**Comment by gborri** [comment]
@Koal4 I'm from italy and the shows are released far far after the US release date. What i have asked (and i think also @jepadgett3) is to have the possibility (upon configuration) to stop it. Todays it burn a lot of resources and make a lot of traffic not useful for us.

**Comment by Koal4** [comment]
I understand your "problem". But the thing is when you turn on the option 'update on snatch', and only rely on that option, sickrage will only update shows that are currently broadcasted on tv. When a show goes on a break, due season ending, it will not get the new airdates because at the time of the last episode the airdate wasn't even known @tvdb or tvrage.

**Comment by gborri** [comment]
@Koal4 you are right. But the point is that performing show update once a day is more than enough. what is needed is probably to have less frequent update (once a week? once a mounth?)

**Comment by papampi** [comment]
+1
updating all the shows every day is a total waste of resource and HDD life.

**Comment by papampi** [comment]
at least is there  a dirty way to disable this? 
it recently take longer time to update my huge collection of tv shows and it wont let daily search snatch shows until the update is finished.
I set the daily update to 23 and most of the time when I wake up at 7, its still updating

**Comment by WebSpider** [comment]
The dirty way is to comment lines 1419 and 1420 of sickbeard/__init__.py ... be aware: This will break automatic updates.

I'll put together a PR that adds a config option that does just this,so you can control it by editing the config.ini

**Comment by gborri** [comment]
If possibile make it work in a way in which can bee schedule also once a
Week or once a month.

Il giorno sab 25 lug 2015 02:49 Nils <notifications@github.com> ha scritto:

> The dirty way is to comment lines 1419 and 1420 of sickbeard/*init*.py
> ... be aware: This will break automatic updates.
>
> I'll put together a PR that adds a config option that does just this,so
> you can control it by editing the config.ini
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/1626#issuecomment-124780051>
> .
>
-- 

Giovanni

**Comment by papampi** [comment]
@WebSpider Thanks for the work around

**Comment by papampi** [comment]
what I did is, I made a crontab  to restart SR a min after it start showupdate

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
