### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-71656 :: Check scene exceptions update failed. Unable to get URL: https://raw.githubusercontent.com/SiCKRAGETV/sr_tvrage_scene_exceptions/master/exceptions.txt

### ISSUE THREAD

**Issue by LennyM8472** [SiCKRAGETV/sickrage-issues#1627]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/3d7f8089d5390fe74a1d
### ERROR
```
SEARCHQUEUE-BACKLOG-71656 :: Check scene exceptions update failed. Unable to get URL: https://raw.githubusercontent.com/SiCKRAGETV/sr_tvrage_scene_exceptions/master/exceptions.txt
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1580
