### ISSUE TITLE
Unifode characters in name pattern

### ISSUE THREAD

**Issue by skafte** [SiCKRAGETV/sickrage-issues#1629]
Characters like æ, ø, å (Danish characters) are not accepted as part of the naming pattern for post processing -> Episode Naming. Instead of an "æ" there will be a "Ã¦"

Both error and normal log are empty
BRANCH: (master) / COMMIT: (26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9) 
Python version: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
OS: Windows server 2012

**Comment by neoatomic** [comment]
Looks the same as https://github.com/SiCKRAGETV/sickrage-issues/issues/1611 please add the problem there so we have all info in one place.
