### ISSUE TITLE
Episode marked Archived after file has been deleted

### ISSUE THREAD

**Issue by theemstra** [SiCKRAGETV/sickrage-issues#1632]
The expected behavior of SickRage is that when a episode has been removed (= probably watched), it should be set to status 'Ignored', so it will not be measured in some counting statistics.
Since two updates back, this changed. Now after an episode is deleted, the episode is marked as Archived, by both manual post-processing and automatic post-processing.

**Comment by fernandog** [comment]
Check settings. change episode status when deleting

**Comment by theemstra** [comment]
Thanks, for future reference:

General Configuration -> Advanced Settings -> Default deleted episode status

Do note that this changed during a previous update
