### ISSUE TITLE
[APP SUBMITTED]: [Errno 13] Permission denied: u"D:\\Gianni\\TV SHOWS\\Grey's Anatomy\\Season 09\\Grey's Anatomy - S09E01 - Going Going Gone.mp4"

### ISSUE THREAD

**Issue by srge1827** [SiCKRAGETV/sickrage-issues#1633]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/7ad5626b5a4023d46a91
### ERROR
```
SHOWQUEUE-REFRESH :: File air date stamping failed(Permission denied). Check permissions for file: D:\Gianni\TV SHOWS\Grey's Anatomy\Season 09\Grey's Anatomy - S09E01 - Going Going Gone.mp4
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Check if the file was in use (seeding) or if the permissions are correctly set.
Otherwise look at the PP date/time renaming settings.
