### ISSUE TITLE
Seedbox error https://raw.githubusercontent.com/SiCKRAGETV/sr_tvrage_scene_exceptions/master/exceptions.txt

### ISSUE THREAD

**Issue by proddorp** [SiCKRAGETV/sickrage-issues#1634]
Hi there

I am getting the following errors
Check scene exceptions update failed. Unable to get URL: https://raw.githubusercontent.com/SiCKRAGETV/sr_tvrage_scene_exceptions/master/exceptions.txt
[TorrentLeech] :: Error while searching TorrentLeech, skipping: '_socketobject' object has no attribute 'set_tlsext_host_name'
[IPTorrents] :: Error while searching IPTorrents, skipping: '_socketobject' object has no attribute 'set_tlsext_host_name'

I am running SickRage on Seedbox (seedhost.eu) so too sure how to update python/not sure what to do.

**Comment by neoatomic** [comment]
SSL errors. check https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors
And https://github.com/SiCKRAGETV/sickrage-issues/issues/1580
