### ISSUE TITLE
[APP SUBMITTED]: Connection error ('Connection aborted.', error(104, 'Connection reset by peer')) while loading URL http://services.tvrage.com/myfeeds/episode_list.php

### ISSUE THREAD

**Issue by konomimaster** [SiCKRAGETV/sickrage-issues#1635]
### INFO
Python Version: **2.7.9 (default, Mar 22 2015, 23:26:38) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: error Connection error ('Connection aborted.', error(104, 'Connection reset by peer')) while loading URL http://services.tvrage.com/myfeeds/episode_list.php
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Connection problem. A reboot should be sufficient.
