### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-80348 :: Transmission: Authentication Failed

### ISSUE THREAD

**Issue by Advtech92** [SiCKRAGETV/sickrage-issues#1636]
### INFO
Python Version: **2.7.9 (default, Mar  8 2015, 00:52:26) [GCC 4.9.2]**
Operating System: **Linux-3.18.5-v7+-armv7l-with-debian-8.0**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/b74b4697eba56f372443
### ERROR
```
SEARCHQUEUE-BACKLOG-80348 :: Transmission: Authentication Failed
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Advtech92** [comment]
Tranmission issues seems to be related to submitting torrents to Transmission to start the new episode added. Manage Torrents was not working until I shut down the system, added the password directly to the config.ini in my sickrage build. Manage Torrents works now but still unable to add new torrents for download.

**Comment by neoatomic** [comment]
@Advtech92 If Transmission was broken i will suspect a lot more support tickets opened. So i suspect this is a problem locally with your install.

Are you using encrypted passwords for the config.ini.? I recall an old issue where those got corrupt for some weird reason.
If so disable encrypted passwords, shutdown SR and manually add the passwords to your config.ini.
See if that fixes the problem. Otherwise check the Transmission settings and permissions.

**Comment by Advtech92** [comment]
I did put the password manually into the config.ini. I'll have to see if it is still erroring

**Comment by Advtech92** [comment]
Turning off Encryption fixed it, any chances of a fix for that coming out?

**Comment by neoatomic** [comment]
The old encryption problem was fixed a few months back. You can try to switch it on again, maybe you encrypted before the fix.? 
Its a very basic encryption and when you switch devices etc it can not function correctly.

**Comment by Advtech92** [comment]
I found out the actual issue. It was the ip for transmission. I had it set to localhost:9090 due to my system tending to get a new ip when it rebooted. It worked for a while but I think an update stopped it working.  It works with the actual ip of the system

**Comment by klingac** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.7+-armv6l-with-debian-7.8**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-259669 :: [ThePirateBay] :: Transmission: Authentication Failed
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by klingac** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.7+-armv6l-with-debian-7.8**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: Transmission: Authentication Failed
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by klingac** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.7+-armv6l-with-debian-7.8**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: Transmission: Authentication Failed
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
