### ISSUE TITLE
[APP SUBMITTED]: no such column: absolute_number

### ISSUE THREAD

**Issue by wordguy** [SiCKRAGETV/sickrage-issues#1639]
### INFO
Python Version: **2.7.6 (default, Nov 10 2013, 19:24:18) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/53dff1bdb85591ee65b6
### ERROR
```
Thread-71 :: DB error: no such column: absolute_number
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@wordguy The error is "DB error: database is locked" meaning you haven't set the correct permissions or the database is corrupt.
