### ISSUE TITLE
[Suggestion] remove support of EZTV

### ISSUE THREAD

**Issue by Zzaap** [SiCKRAGETV/sickrage-issues#1640]
https://torrentfreak.com/eztv-shuts-down-after-hostile-takeover-150518/

TPB KAT and Rarbg all dissociated from EZTV

**Comment by papampi** [comment]
+1

**Comment by neoatomic** [comment]
@fernandog I suggest disabling this provider for now and see how it develops. ?
The last days i also see support tickets opened specific to this provider.

**Comment by fernandog** [comment]
@miigotu should we remove it now?

**Comment by miigotu** [comment]
Yes, I have wanted to remove it for some time now. Soo, maybe we should add ettv, as their releases are very similar anyways.
