### ISSUE TITLE
[Feature Request] Additional indexes to improve performance.

### ISSUE THREAD

**Issue by jfroebe** [SiCKRAGETV/sickrage-issues#1642]
I've created the indexes with rather generic names so you guys can rename to however you want them.   Hope this helps

SR Version: 	BRANCH: (master) / COMMIT: (26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9) 
Python Version:	2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]

CREATE INDEX history_ndx4 on history (action,date,showid);
CREATE INDEX history_ndx2 on history (showid, season, episode, quality);
CREATE INDEX imdb_info_ndx1 on imdb_info (indexer_id, imdb_id, last_update);
CREATE INDEX imdb_info_ndx2 on imdb_info (imdb_id, title);
CREATE INDEX indexer_mapping_ndx1 on indexer_mapping (indexer_id, mindexer_id);
CREATE INDEX indexer_mapping_ndx2 on indexer_mapping (mindexer_id, indexer);
CREATE INDEX tv_episodes_ndx1 on tv_episodes (showid, name);
CREATE INDEX tv_shows_ndx1 on tv_shows (indexer_id, show_id, show_name);
CREATE INDEX tv_shows_ndx2 on tv_shows (genre, show_name);
CREATE INDEX tv_shows_ndx3 on tv_shows (show_name, location);
CREATE INDEX xem_refresh_ndx1 on xem_refresh (indexer_id, indexer);
CREATE INDEX xem_refresh_ndx2 on xem_refresh (indexer_id, last_refreshed);

**Comment by miigotu** [comment]
I don't see why we need this, and we avoid changing the db unless absolutely necessary.

**Comment by jfroebe** [comment]
Changing the schema of a database should always be met with skepticism imo. :)

The indexes improve performance of sickrage/sickbeard by reducing the occurance of table scans. 

What I can recommend is apply the indexes on a test system with a list of a couple hundred tv shows and thousands of episodes.  Adding new or existing shows should be quicker moving from screen to screen as well as other areas such as editing shows.  If you see a benefit, consider adding them to the code line or upstream.  

Unfortunately SQLite doesn't provide any tool or mechanism to identify unused indexes or how often indexes are used.  So YMMV.

**Comment by miigotu** [comment]
@jfroebe I think I agree on adding these, as soon as I can double check them.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
