### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-281470 :: Check scene exceptions update failed. Unable to get URL: https://raw.githubusercontent.com/SiCKRAGETV/sr_tvrage_scene_exceptions/master/exceptions.txt

### ISSUE THREAD

**Issue by distracto** [SiCKRAGETV/sickrage-issues#1643]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/b31e0da09ebae5c9d2ac
### ERROR
```
SEARCHQUEUE-BACKLOG-281470 :: Check scene exceptions update failed. Unable to get URL: https://raw.githubusercontent.com/SiCKRAGETV/sr_tvrage_scene_exceptions/master/exceptions.txt
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1580
https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors

**Comment by MaDTaZ** [comment]
I have tried all the options and am still getting this error I am running lime mint 13
