### ISSUE TITLE
[Feature Request] Ability to add shows with no premiere date

### ISSUE THREAD

**Issue by yoharnu** [SiCKRAGETV/sickrage-issues#1644]
With all of the networks releasing their fall lineup and trailers, but not yet announcing premiere dates, it would be nice to be able to add the shows that sound interesting now instead of having to keep track of them somewhere else until a premiere date is announced.

~~Also, it may not be possible to add them after a premiere date is announced since episodes without a name are ignored. I suggest that episodes with a null name default to "TBA" or "TBD".~~

EDIT: As long as a show has a premiere date, the actual episodes do not need to have an episode name to add the show. In fact, the episodes don't even need to exist on TVDB.

**Comment by djack42** [comment]
The folders are created, but the shows aren't in the db.
A quick add existing shows later will allow to add them properly.

But i'd like them to be added in the db, a premiere date should not be mandatory.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
