### ISSUE TITLE
[APP SUBMITTED]: FINDSUBTITLES :: Not enough services selected. At least 1 service is required to search subtitles in the background

### ISSUE THREAD

**Issue by YoungChrisV** [SiCKRAGETV/sickrage-issues#1645]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/d16143c513b44a3bede7
### ERROR
```
FINDSUBTITLES :: Not enough services selected. At least 1 service is required to search subtitles in the background
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
If you enable subtitles you have to enable a subtitle provider also under "subtitle plugin". (opensubtitels etc..)

**Comment by Xexiz** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5391476827cf369a2d16a4e7ee8128f47a75f74c
Link to Log: https://gist.github.com/bb28815b07022124bdcb
### ERROR
```
FINDSUBTITLES :: Not enough services selected. At least 1 service is required to search subtitles in the background
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by XxUnkn0wnxX** [comment]
### INFO
Python Version: **2.7.10 (default, Sep 22 2015, 12:25:10) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)]**
Operating System: **Darwin-14.5.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@41dfcaeaf855297d6a478355746d6b769ca8b0da
Link to Log: https://gist.github.com/7d72b9cccf7fe28788aa
### ERROR
```
FINDSUBTITLES :: Not enough services selected. At least 1 service is required to search subtitles in the background
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by duramato** [comment]
@fernandog I'm gonna bet this is related to the subs not saving problem

**Comment by fernandog** [comment]
Yes. Thia happens with providers too. When user has only one provider and search fails

**Comment by ward0** [comment]
I'm having the same problem.

I created a topic on the forum aswell 

https://sickrage.tv/forums/forum/help-support/general-support/29878-subtitles-plugin-does-not-save-my-selected-plugins

![image](https://cloud.githubusercontent.com/assets/15545810/10868033/18e2dcd0-8081-11e5-8bbd-fa7121ae47d8.png)

![image](https://cloud.githubusercontent.com/assets/15545810/10868036/541e9eec-8081-11e5-8c3c-5cedeed7ccce.png)
after i click on save settings and i press F5 or go back into the menu again.

they are checked out.
