### ISSUE TITLE
[APP SUBMITTED]: no such column: absolute_number

### ISSUE THREAD

**Issue by wordguy** [SiCKRAGETV/sickrage-issues#1646]
### INFO
Python Version: **2.7.6 (default, Nov 10 2013, 19:24:18) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/1285036918a768f7dce6
### ERROR
```
Thread-31 :: DB error: no such column: absolute_number
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
database is locked

**Comment by wordguy** [comment]
How do I unlock the database?

Date: Wed, 20 May 2015 09:15:10 -0700
