### ISSUE TITLE
[APP SUBMITTED]: [Errno 40] Too many levels of symbolic links: '/home/downloader/tvshow/Person Of Interest/Season 4/Person.of.Interest.S04E21.Asylum.mkv'

### ISSUE THREAD

**Issue by artentica** [SiCKRAGETV/sickrage-issues#1648]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-48-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/a7606cf2880baf026119
### ERROR
```
Thread-30 :: Unable to get size for file /home/downloader/tvshow/Person Of Interest/Season 4/Person.of.Interest.S04E21.Asylum.mkv. Error msg is: [Errno 40] Too many levels of symbolic links: '/home/downloader/tvshow/Person Of Interest/Season 4/Person.of.Interest.S04E21.Asylum.mkv'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Symbiot78** [comment]
seeing the same issue. 
Have posted errors from SickRage interface.

**Comment by artentica** [comment]
Me finally it was beacause my symbolic was targetting himsel.

**Comment by neoatomic** [comment]
@artentica Thanks for letting us know what the problem was.
