### ISSUE TITLE
HDBits auth not working

### ISSUE THREAD

**Issue by innocuoussoul** [SiCKRAGETV/sickrage-issues#1651]
branch: master
commit:  26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
OS: Synology
What I did: Tried to download an episode via hdbits.org
What Happened: auth failed
What expected: it to work. 

https://gist.github.com/innocuoussoul/8eb089d4f349dd61a07e#file-gistfile1-txt
```
AAAuthException: Your authentication credentials for HDBits are incorrect, check your config.
AA    "Your authentication credentials for " + self.name + " are incorrect, check your config.")
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/hdbits.py", line 71, in _checkAuthFromData
AA    if self._checkAuthFromData(parsedJSON):
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/hdbits.py", line 107, in _doSearch
AA    for curString in self._get_season_search_strings(epObj):
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/generic.py", line 289, in findSearchResults
AA    break
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 480, in searchProviders
AATraceback (most recent call last):
2015-05-20 20:13:53 ERROR    SEARCHQUEUE-BACKLOG-281511 :: [HDBits] :: Authentication error: Your authentication credentials for HDBits are incorrect, check your config.
```

**Comment by neoatomic** [comment]
@innocuoussoul Are you using encrypted passwords for the config.ini.? If so try to disable it and add the user-name and password manually to your config.ini You can find those under : 

hdbits_username = ""
hdbits_passkey = ""

See if that fixes the problem.

**Comment by innocuoussoul** [comment]
doesn't fix the problem :(

**Comment by fernandog** [comment]
@innocuoussoul 
did you stoped SR before doing the changed to config.ini?

probably they changed something in their website

**Comment by innocuoussoul** [comment]
yeah, i did. and that could be the case. who is currently maintaining this provider in sickrage?

**Comment by neoatomic** [comment]
Not sure who coded the HDBits provider. But if you yourself are able to take a look at the code than that would be more than welcome.

**Comment by innocuoussoul** [comment]
I'm taken a look and I can't figure out the problem... is there anyone else that might be able to take a look?

**Comment by innocuoussoul** [comment]
If someone else has the bandwidth and the knowledge to take a look, I can assist in whatever way is necessary. Otherwise, this makes sickbeard kind of useless for me.

**Comment by neoatomic** [comment]
HDBits is a closed provider, meaning that we dont have access/account. So we cant even test...
If you can ask on there forums if they have changed anything for the authentication. And if so what they changed.

**Comment by neoatomic** [comment]
@innocuoussoul What DSM version are you running.? 5.2 or the older 4.2?
I just see that HDBits is using https. So it could be an SSL error.

**Comment by neoatomic** [comment]
@innocuoussoul have you still problems with HDbits.?

**Comment by innocuoussoul** [comment]
Nope this has been resolved. Thank you.
