### ISSUE TITLE
[APP SUBMITTED]: failedDownloads() got an unexpected keyword argument 'Sons_Extended_720p_CC_WEBRip_AAC2_0_x264_monkee|The_Good_Wife_S06E14_720p_HDTV_X264_DIMENSION|The_Good_Wife_S06E21_720p_HDTV_X264_DIMENSION|The_Walking_Dead_S05E13_720p_HDTV_x264_KILLERS|The_Walking_Dead_S05E13_1080p_HDTV_x264_BATV'

### ISSUE THREAD

**Issue by DrakeJones** [SiCKRAGETV/sickrage-issues#1653]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/a43cd3fddad5412b5885
### ERROR
```
Thread-26 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
TypeError: failedDownloads() got an unexpected keyword argument 'Sons_Extended_720p_CC_WEBRip_AAC2_0_x264_monkee|The_Good_Wife_S06E14_720p_HDTV_X264_DIMENSION|The_Good_Wife_S06E21_720p_HDTV_X264_DIMENSION|The_Walking_Dead_S05E13_720p_HDTV_x264_KILLERS|The_Walking_Dead_S05E13_1080p_HDTV_x264_BATV'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@DrakeJones Looks like a one time error. If you still receive the error than try to remove the failed.db

**Comment by DrakeJones** [comment]
Thank you. SickRage is good software. 
PS I posted to Newsbin's forum requesting better integration with SickRage. I think it would be a really great thing.
