### ISSUE TITLE
[APP SUBMITTED]: 'ascii' codec can't encode character u'\xea' in position 86: ordinal not in range(128)

### ISSUE THREAD

**Issue by Nibeck1309** [SiCKRAGETV/sickrage-issues#1655]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.7+-armv6l-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: ascii : /media/media/Animes/Kuroko no Basket/Season 01/Kuroko_no_Basket_-_S01E03_-_003_-_Vous_êtes_trop_forts_pour_nous__Parfait_-_SDTV.mp4 : error 86 : error 87 : ordinal not in range(128)
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

here the full log : http://pastebin.com/NTJn5uY9

my locale settings 

pi@BCFamily:~$ locale
LANG=fr_FR.UTF-8
LANGUAGE=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=fr_FR.UTF-8

root@BCFamily:~# locale
LANG=fr_FR.UTF-8
LANGUAGE=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=fr_FR.UTF-8

**Comment by neoatomic** [comment]
@Nibeck1309 I suspect that this "ê" character in _êtes_ is causing the error.
Also not sure why it says "Locale: unknown" Are you running SR on a QNAP.?

**Comment by Nibeck1309** [comment]
No, I run SR on Raspberry PI

**Comment by fernandog** [comment]
@Nibeck1309 post the contents of localhost:8081/config

sickrage service is running with which user?

**Comment by fernandog** [comment]
no reply. closing
