### ISSUE TITLE
[Feature Request] Add Torrent Search Provider Norbits.net

### ISSUE THREAD

**Issue by d00ziie** [SiCKRAGETV/sickrage-issues#1656]
Would be great to se NorBits as a Torrent Search Provider in SickRage.

1) NorBits
2) NB
3) http://norbits.net (also support SSL encryption)
4) Torrent 
5) Private

The tracker use passkey

**Comment by Hellowlol** [comment]
Example on how to search https://github.com/Hellowlol/HTPC-Manager/blob/master2/libs/ts/norbits.py

**Comment by WebSpider** [comment]
Looks like a HDBits clone

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
