### ISSUE TITLE
[APP SUBMITTED]: SHOWQUEUE-REFRESH :: There was an error trying to retrieve the image, aborting

### ISSUE THREAD

**Issue by oshotton** [SiCKRAGETV/sickrage-issues#1657]
### INFO
Python Version: **2.7.5 (default, Jun 17 2014, 18:11:42) [GCC 4.8.2 20140120 (Red Hat 4.8.2-16)]**
Operating System: **Linux-3.10.0-229.1.2.el7.x86_64-x86_64-with-centos-7.1.1503-Core**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/37390515b7b6c734b8c2
### ERROR
```
SHOWQUEUE-REFRESH :: There was an error trying to retrieve the image, aborting
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Thraxis** [comment]
This should probably be downgraded to a warning.  Generally happens when TVDB doesn't yet have an image (poster / banner) for a new show.

**Comment by oshotton** [comment]
Sounds good to me. Thought I would report it as it keeps logging repeatedly! :/

**Comment by razlebol** [comment]
### INFO
Python Version: **2.7.6 (default, Apr  3 2014, 09:45:36) [GCC 4.5.3]**
Operating System: **Linux-3.4.90-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-REFRESH :: There was an error trying to retrieve the image, aborting
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by razlebol** [comment]
### INFO
Python Version: **2.7.6 (default, Apr  3 2014, 09:45:36) [GCC 4.5.3]**
Operating System: **Linux-3.4.90-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-REFRESH :: There was an error trying to retrieve the image, aborting
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by razlebol** [comment]
### INFO
Python Version: **2.7.6 (default, Apr  3 2014, 09:45:36) [GCC 4.5.3]**
Operating System: **Linux-3.4.90-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-REFRESH :: There was an error trying to retrieve the image, aborting
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1929

**Comment by Talung** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-53-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@92bf581ba8a7d4f2f912db795ce571b6ad38c3c2
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-REFRESH :: There was an error trying to retrieve the image, aborting
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
