### ISSUE TITLE
[APP SUBMITTED]: 'utf8' codec can't decode byte 0xd0 in position 57: invalid continuation byte

### ISSUE THREAD

**Issue by dpinheiro** [SiCKRAGETV/sickrage-issues#1658]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-2.6.32-042stab094.8-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
No Log available with ERRORS: 
### ERROR
```
MAIN :: There was an error creating the show in /home/zeux/tvshows/The Big Bang Theory: 'utf8' codec can't decode byte 0xd0 in position 57: invalid continuation byte
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@dpinheiro We need logs to troubleshoot the error. If not this will be closed.
