### ISSUE TITLE
High RAM useage when fetching Log

### ISSUE THREAD

**Issue by Biomorph77** [SiCKRAGETV/sickrage-issues#1660]
Lately SR has taken some time to bring up the Log for me and have just noticed that during the time it 'thinks' the RAM use for the python.exe process jumps from 130MB it averages to 1-2GB.

This also then causes everything else to grind to a halt till the process finishes, or as is happening more often, it doesn't finish and so I have to end that process and restart SR.

**Comment by neoatomic** [comment]
@Biomorph77 That are indeed very high RAM numbers.
Uninstall SR and python. Do a clean install of both, and start a new sickbeard.db and config.ini

**Comment by fernandog** [comment]
If you are using searchLog or filter SR will read ALL log files. If you have too much log it will take time and RAM
