### ISSUE TITLE
SNI Is disabled with pyOpenSSL >= 0.14 when the cryptography module is missing - QNAP 

### ISSUE THREAD

**Issue by daniluvsuall** [SiCKRAGETV/sickrage-issues#1661]
Hi there,

I'm having some problems with SickRage since upgrading it the other week. I constantly get this eror when I restart SickRage, I am aware of the known issue and the suggested fix's but they're not working for me.

I'm running this on a QNAP TS-469 Pro, here is the output from a SickRage restart and the install of the pip commands it requests:

[~] # /etc/init.d/sickbeard-tvrage.sh restart
Restarting SickBeard-TVRage
Shutting down SickBeard-TVRage... 
 Waiting for SickBeard-TVRage to shut down: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, Done
SickBeard-TVRage prestartup checks...
 Checking for /opt...  Found!
Updating SickBeard-TVRage
HEAD is now at 26a1aae Merge branch 'develop'
Already up-to-date.
/root
Starting SickBeard-TVRage

SNI is disabled with pyOpenSSL >= 0.14 when the cryptography module is missing,
you will encounter SSL errors with HTTPS! To fix this issue:
pip install pyopenssl==0.13.1 (easy) or pip install cryptography (pita)
[~] # 
[~] # 
[~] # 
[~] # uname -a
Linux COUGAR 3.4.6 #1 SMP Wed Apr 8 04:30:01 CST 2015 x86_64 unknown
[~] # pip install pyopenssl==0.13.1 && pip install cryptography (pita)
-sh: syntax error near unexpected token `('
[~] # pip install pyopenssl==0.13.1 && pip install cryptography
Requirement already satisfied (use --upgrade to upgrade): pyopenssl==0.13.1 in /share/MD3_DATA/.qpkg/Optware/local/lib/python2.7/site-packages
Cleaning up...
Downloading/unpacking cryptography
  Downloading cryptography-0.9.tar.gz (302kB): 302kB downloaded
  Running setup.py egg_info for package cryptography
    
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
Downloading/unpacking idna (from cryptography)
  Downloading idna-2.0.tar.gz (135kB): 135kB downloaded
  Running setup.py egg_info for package idna
    
    warning: no previously-included files matching '*.pyc' found under directory 'tools'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
Downloading/unpacking pyasn1 (from cryptography)
  Downloading pyasn1-0.1.7.tar.gz (68kB): 68kB downloaded
  Running setup.py egg_info for package pyasn1
    
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in /share/MD3_DATA/.qpkg/Optware/local/lib/python2.7/site-packages/six-1.6.1-py2.7.egg (from cryptography)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /share/MD3_DATA/.qpkg/Optware/local/lib/python2.7/site-packages (from cryptography)
Downloading/unpacking enum34 (from cryptography)
  Downloading enum34-1.0.4.tar.gz
  Running setup.py egg_info for package enum34
    
Downloading/unpacking ipaddress (from cryptography)
  Downloading ipaddress-1.0.7.tar.gz
  Running setup.py egg_info for package ipaddress
    
Downloading/unpacking cffi>=0.8 (from cryptography)
  Downloading cffi-1.0.1.tar.gz (316kB): 316kB downloaded
  Running setup.py egg_info for package cffi
    
Downloading/unpacking pycparser (from cffi>=0.8->cryptography)
  Downloading pycparser-2.13.tar.gz (299kB): 299kB downloaded
  Running setup.py egg_info for package pycparser
    
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
Installing collected packages: cryptography, idna, pyasn1, enum34, ipaddress, cffi, pycparser
  Running setup.py install for cryptography
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip_build_admin/cryptography/setup.py", line 342, in <module>
        **keywords_with_side_effects(sys.argv)
      File "/opt/lib/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/opt/local/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/opt/local/lib/python2.7/site-packages/setuptools/dist.py", line 310, in fetch_build_eggs
        replace_conflicting=True,
      File "/opt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 830, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/opt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1075, in best_match
        return self.obtain(req, installer)
      File "/opt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1087, in obtain
        return installer(requirement)
      File "/opt/local/lib/python2.7/site-packages/setuptools/dist.py", line 375, in fetch_build_egg
        cmd.ensure_finalized()
      File "/opt/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "/opt/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 290, in finalize_options
        d + " (in --site-dirs) is not on sys.path"
    distutils.errors.DistutilsOptionError: /opt/local/lib/python2.5/site-packages (in --site-dirs) is not on sys.path
    Complete output from command /usr/bin/python -c "import setuptools;__file__='/tmp/pip_build_admin/cryptography/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-p0q0fJ-record/install-record.txt --single-version-externally-managed:
    Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip_build_admin/cryptography/setup.py", line 342, in <module>

    **keywords_with_side_effects(sys.argv)

  File "/opt/lib/python2.7/distutils/core.py", line 112, in setup

    _setup_distribution = dist = klass(attrs)

  File "/opt/local/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__

    self.fetch_build_eggs(attrs['setup_requires'])

  File "/opt/local/lib/python2.7/site-packages/setuptools/dist.py", line 310, in fetch_build_eggs

    replace_conflicting=True,

  File "/opt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 830, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/opt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1075, in best_match

    return self.obtain(req, installer)

  File "/opt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1087, in obtain

    return installer(requirement)

  File "/opt/local/lib/python2.7/site-packages/setuptools/dist.py", line 375, in fetch_build_egg

    cmd.ensure_finalized()

  File "/opt/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized

    self.finalize_options()

  File "/opt/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 290, in finalize_options

    d + " (in --site-dirs) is not on sys.path"

distutils.errors.DistutilsOptionError: /opt/local/lib/python2.5/site-packages (in --site-dirs) is not on sys.path

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools;__file__='/tmp/pip_build_admin/cryptography/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-p0q0fJ-record/install-record.txt --single-version-externally-managed failed with error code 1 in /tmp/pip_build_admin/cryptography
Storing complete log in /root/.pip/pip.log
[~] #

**Comment by neoatomic** [comment]
@daniluvsuall Those SSL errors are a specific QNAP bug, and only they can fix this...
 
https://github.com/SiCKRAGETV/sickrage-issues/issues/1580
https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors

**Comment by daniluvsuall** [comment]
Thanks for your help, okay.. I guess I shall just have to deal with it!
