### ISSUE TITLE
User-adoption boost

### ISSUE THREAD

**Issue by max484** [SiCKRAGETV/sickrage-issues#1662]
I hold a lot of respect to the developers and all the good people putting their time and talent into this project. 
In my opinion if Sickrage had a simple windows installer and a simple desktop shortcut to run it, it would contribute immensely to user adoption. It's a shame really because it is probably the number one reason why Sickrage is not considerably more popular. Having more users will open new opportunities for future development. 
Try sending a non developer friend a link to a Sickrage install page (which /where?) and see if they can go through the process of getting it to work. 
A landing page with a windows installer would give this project a huge push.
Thanks again for all the hard work you guys put into this project

**Comment by neoatomic** [comment]
@max484 Well you can always advice them to buy a Synology NAS, installs SR with a few clicks.  :)
But on a serious note, We have it on the to-do list to create packages for different platforms. https://github.com/SiCKRAGETV/sickrage-issues/issues/46
We will do that in the future.
