### ISSUE TITLE
DB restore not working

### ISSUE THREAD

**Issue by gborri** [SiCKRAGETV/sickrage-issues#1663]
if you try to restore to a previously version, the process seems to copy only the cache directory.

**Comment by gborri** [comment]
on last development

**Comment by neoatomic** [comment]
@gborri Can you be more specific.? Manually restoring, or using the SR "restore" function.?
Logs.? https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket

**Comment by gborri** [comment]
Using restore function. I happens that if i restore from scrach when restarting "restore" directory is managed (and deleted) but sickrage is empty.

**Comment by fernandog** [comment]
@gborri .gitignore tells SR to not delete the folder:

https://github.com/SiCKRAGETV/SickRage/blob/master/.gitignore#L5

check your .gitignore file
