### ISSUE TITLE
[APP SUBMITTED]: Failed Unrar archive Ray.Donovan.S01E04.720p.HDTV.x264-EVOLVE.part01.rar: Unrar: Archive CRC Error

### ISSUE THREAD

**Issue by calimada** [SiCKRAGETV/sickrage-issues#1665]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/5bcf7ccea8c69981b898
### ERROR
```
POSTPROCESSER :: Failed Unrar archive Ray.Donovan.S01E04.720p.HDTV.x264-EVOLVE.part01.rar: Unrar: Archive CRC Error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Damaged RAR or password protected.
