### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: Invalid username or password for TorrentLeech Check your settings

### ISSUE THREAD

**Issue by Peke** [SiCKRAGETV/sickrage-issues#1666]
### INFO
Python Version: **2.7.3 (default, Apr 12 2012, 20:25:04) [GCC 4.2.1]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.0**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/0185f6bba6ee7a296d21
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: Invalid username or password for TorrentLeech Check your settings
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@Peke The know SSL errors on the QNAP.
See : 
https://github.com/SiCKRAGETV/sickrage-issues/issues/1580
https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors

**Comment by Peke** [comment]
Damn Wrong Bug
