### ISSUE TITLE
[APP SUBMITTED]: 'charmap' codec can't encode characters in position 0-7: character maps to <undefined>

### ISSUE THREAD

**Issue by jojobean419** [SiCKRAGETV/sickrage-issues#1670]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7600**
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-114801 :: [oznzb] :: Error while searching oznzb, skipping: charmap :  227 : error 0 : error 8 : character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@jojobean419 Logs.? Without we cant troubleshoot and this will be closed.

**Comment by crowaust** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2008ServerR2-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@5d4bec2c6022a9e2d5ec934791cf80a0b2553a6f
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-114801 :: [Oznzb] :: Error while searching Oznzb, skipping: charmap : ãƒ•ã‚§ã‚¢ãƒªãƒ¼ãƒ†ã‚¤ãƒ« : error 0 : error 8 : character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by crowaust** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2008ServerR2-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@5d4bec2c6022a9e2d5ec934791cf80a0b2553a6f
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-114801 :: [Sick Beard Index] :: Error while searching Sick Beard Index, skipping: charmap : ãƒ•ã‚§ã‚¢ãƒªãƒ¼ãƒ†ã‚¤ãƒ« : error 0 : error 8 : character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by crowaust** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2008ServerR2-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@5d4bec2c6022a9e2d5ec934791cf80a0b2553a6f
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-114801 :: [Sick Beard Index] :: Error while searching Sick Beard Index, skipping: charmap : ãƒ•ã‚§ã‚¢ãƒªãƒ¼ãƒ†ã‚¤ãƒ« : error 0 : error 8 : character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by crowaust** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2008ServerR2-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@5d4bec2c6022a9e2d5ec934791cf80a0b2553a6f
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-114801 :: [Oznzb] :: Error while searching Oznzb, skipping: charmap : ãƒ•ã‚§ã‚¢ãƒªãƒ¼ãƒ†ã‚¤ãƒ« : error 0 : error 8 : character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
