### ISSUE TITLE
[Feature Request] Add Torrent Provider TitansOf.TV

### ISSUE THREAD

**Issue by jtwill** [SiCKRAGETV/sickrage-issues#1674]
How about adding new torrent search provider TitansOf.TV (ToTV)?

SIckGear already has it, so hopefully most of the code can be reused for SR:

https://github.com/SickGear/SickGear/blob/develop/sickbeard/providers/totv.py

**Comment by adaur** [comment]
Fixed: https://github.com/SiCKRAGETV/SickRage/pull/2129
