### ISSUE TITLE
Manually process (and define/link) an Episode

### ISSUE THREAD

**Issue by syrys** [SiCKRAGETV/sickrage-issues#1675]
So, i had an issue just earlier with a file. I have sickrage using qbittorrent using the blackhole feature, and it downloaded a specific torrent episode for an anime. But, it didnt process ir for some reason, so i decided to run a manual post process, which picked up the following issue:

```
PostProcessing Path: D:\Downloads\SickRage-BlackHole
PostProcessing Dirs: []
PostProcessing Files: [u'[HorribleSubs] World Trigger - 31 [1080p].mkv', u'[HorribleSubs].Danna.ga.Nani.wo.Itteiru.ka.Wakaranai.Ken.-.11.[1080p].mkv.torrent.invalid']
PostProcessing VideoFiles: [u'[HorribleSubs] World Trigger - 31 [1080p].mkv']
PostProcessing RarContent: []
PostProcessing VideoInRar: []
Processing D:\Downloads\SickRage-BlackHole\[HorribleSubs] World Trigger - 31 [1080p].mkv (None)
Don't have a season number, but this show appears to only have 1 season, setting season number to 1...
Not enough information to determine what episode this is
Quitting post-processing
Processing failed for D:\Downloads\SickRage-BlackHole\[HorribleSubs] World Trigger - 31 [1080p].mkv: 
Problem(s) during processing, failed the following files/folders: 
[D:\Downloads\SickRage-BlackHole\[HorribleSubs] World Trigger - 31 [1080p].mkv : Processing failed: ]
```

So my question is, i know this download is for the spicific show and specific episode. But the manual post process fails because it cannot automatically figure out which episode this is (no idea why?). Is there any way i can tell sickrage which episode this is and manually process it somehow?

Or... How else can i handle this?

Cheers,

**Comment by syrys** [comment]
ok, never mind, the issue fixed it self. After giving this above error for couple of hours. all of a sudden after posting the above issue, i just got an alert saying it was processed. Im unsure what the problem was and how it was fixed, but its fixed :)

For future reference, is there a manual way to tell sickrage that the episode is a specific file and to process that file as the said episode?

**Comment by neoatomic** [comment]
No, that would be to complex. Best to rename the file if it is not recognized.
