### ISSUE TITLE
Move, not copy and delete

### ISSUE THREAD

**Issue by brestfloda** [SiCKRAGETV/sickrage-issues#1676]
I'm using BRANCH: (master) / COMMIT: (26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9) running on Windows 8.1.

I've noticed that you copy-and-delete the files and don't use move. This results in excessive disk usage and i've seen several files get corrupted in this process. I'd be a happy camper if you could change it.

**Comment by neoatomic** [comment]
@brestfloda You can set SR to "Move" in the settings instead of "copy".

**Comment by brestfloda** [comment]
Is there another setting than Process Episode Method? Because that setting is set to Move, but it doesn't move, it performs a copy and then a delete. It is not the same action. A move of a file on the same disk is next to instantaneous and a copy is a horrible mess of poor performance.

**Comment by neoatomic** [comment]
No, thats all the settings there are.
However if you think you can improve the code, then feel free to submit a PR.
