### ISSUE TITLE
Not snatching My Little Pony S05E08

### ISSUE THREAD

**Issue by Theseus21** [SiCKRAGETV/sickrage-issues#1677]
Don't judge me.

Have My Little Pony in Sickrage, setup as SD quality. It can't pickup the latest release on OZNZB. Looking at the debug log:
  Unable to parse the filename my.little.pony.friendship.is.magic.s05e08.the.lost.treasure.of.griffonstone.hdtv.x264-w4f into a valid show

Looks like the filename should pass the check for SDTV:
 File name contains PDTV or HDTV or DSR or TVRIP, and is xvid or x264 or h264, but not 720[i/p] or 1080[i/p]

**Comment by neoatomic** [comment]
@Theseus21 Please follow the guidelines for posting an issue. https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket
Without logs we cant do anything.

**Comment by Theseus21** [comment]
Ok, sorry. 

I can reproduce by forcing backlog for the show.

Branch : Master
Commit hash : 26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Your operating system and python version : Windows 7. Python 2.7.9
What you did : Added My Little Pony. Added previously downloaded episodes to SickRage. S05E08 is the first automatic download for this series.
What happened : Did not find a match on oznzb, but I can find it if I search manually, or post the api call in a browser.
What you expected : Match my.little.pony.friendship.is.magic.s05e08.the.lost.treasure.of.griffonstone.hdtv.x264-w4f as SDTV download.

Log file starting from clicking force backlog
https://gist.github.com/Theseus21/39c5a7bcc6abd9439fdd

**Comment by neoatomic** [comment]
@Theseus21 Looks like the release name if different from the series name, thats why SR doesnt find it. Suspect that the " :  " character is the problem.

My Little Pony: Friendship is Magic
my.little.pony.friendship.is.magic

You need to add a scene exception that is identical to the release name on oznzb. (So without the " : " SickRage)
That should solve your problem.

**Comment by Theseus21** [comment]
@neoatomic 

Hi.

I have tried that, it did not make a difference. I copy pasted my.little.pony.friendship.is.magic out of my log to make sure there were no typos.

New logs 
https://gist.github.com/Theseus21/af9cdc6bd83000c8dba7

As an aside, shouldn't periods be treated as white space, since it seems to be a common convention? Or does that result in too many false matches?

**Comment by neoatomic** [comment]
@Theseus21 No, try to add it without the periods.

**Comment by Theseus21** [comment]
@neoatomic 
It was already pre-populated with an exception without periods or colons.

This is what the source for my exception list looked like with the last logs I had posted:

https://gist.github.com/Theseus21/2c49a433aa80a7a68cd0

**Comment by neoatomic** [comment]
@Theseus21 Strange, this should work...
Did you set the correct categories under OZNZB.? Daily and Backlog-search are enabled.?
Otherwise try another torrent/nzb provider to see if they work.

**Comment by Theseus21** [comment]
@neoatomic 
From what I can read in the logs (assuming I am reading them correctly), it is picking up the file from Oznzb, but just not matching it as I would expect. So I think the categories are correct ( they're set to 5030 and 5040 ). They are enabled, and it is also occurs when I force Backlog search.

I have posted the api call from the debug log in my browser and I can see hits being returned like.
my.little.pony.friendship.is.magic.s05e08.the.lost.treasure.of.griffonstone.hdtv.x264-w4f 

Is it maybe the 4 in -w4f messing it up ?

**Comment by neoatomic** [comment]
@Theseus21 No, dont think the  -w4f is a problem.

Normally the log should show if the quality setting is wrong, but it is worth a try.
Can you set the show to SD quality do a search and than the same with HDTV quality.? And post a new log.?

**Comment by Theseus21** [comment]
@neoatomic 
The previous logs were with the SD quality setting. Here is one using HD720 ( still didn't snatch ).

https://gist.github.com/Theseus21/b7e2bdd0934939a55e40

**Comment by neoatomic** [comment]
@Theseus21 I'm running out of ideas here... I'm going to open this again, and we have to wait till one of the developers joins in.

**Comment by Theseus21** [comment]
Ok, thanks.

I haven't been using sickRage for very long, so it might still be something configuration related I've messed up, but I have been reading through the wiki, and googling, and haven't seen what I might be doing wrong. It seems to me its getting as far as getting results from OZNzb, but just not matching them as I would expect.

**Comment by Theseus21** [comment]
Just an update, I've since downloaded the file manually, and it doesn't get picked up when it was in the processing folder as:
F:\Downloaded\my.little.pony.friendship.is.magic.s05e08.the.lost.treasure.of.griffonstone.hdtv.x264-w4f\my.little.pony.friendship.is.magic.s05e08.the.lost.treasure.of.griffonstone.hdtv.x264-w4f.mp4

(I processed F:\Downloaded )

However when I moved the file out of the subfolder, to 
F:\Downloaded\\my.little.pony.friendship.is.magic.s05e08.the.lost.treasure.of.griffonstone.hdtv.x264-w4f.mp4

it got picked up.

I then experimented a bit, and if seems to always fail if its in a subfolder, even if its just 1 letter long.

**Comment by fernandog** [comment]
@neoatomic so is it an issue?

**Comment by neoatomic** [comment]
@fernandog , I was not able to figure that out. Hope you are able to take a closer look why it didn't work.?

**Comment by fernandog** [comment]
@miigotu is there any limit for folder+file length?

**Comment by miigotu** [comment]
The parser parses that just fine.

```
>>> import os, sys
>>> sys.path.insert(1, os.path.abspath(os.path.join(os.path.dirname('.'), 'lib')))
>>> from sickbeard.name_parser import parser
>>> print parser.NameParser(True)._parse_string('my.little.pony.friendship.is.magic.s05e08.the.lost.treasure.of.griffonstone.hdtv.x264-w4f\my.little.pony.friendship.is.magic.s05e08.the.lost.treasure.of.griffonstone.hdtv.x264-w4f.mp4')
my little pony friendship is magic - S5E8 [ANIME VER: -1] [GROUP: w4f.mp4] [ABD: False] [ANIME: False] [whichReg: ['standard']]
```
Why are the names so messed up in your name cache?
```
27689 : 3 my little pony friendship is magic
27689 : 3 my little pony friendship is magic season 3 episode 12 games ponies play
27689 : 3 my little pony friendship is magic season 3 episode 13 magical mystery cure
27689 : my little pony friendship is magic
27689 : my little pony friendship is magic season 3 episode 12 games ponies play
27689 : my little pony friendship is magic season 3 episode 13 magical mystery cure
```
