### ISSUE TITLE
Approving TVRage scene exceptions PR's

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#1678]
When do scene exceptions get updated? 
https://github.com/SiCKRAGETV/sr_tvrage_scene_exceptions/pulls

**Comment by neoatomic** [comment]
@miigotu They aren't there, if i recall that repository isn't used at all. You will have to check the code for the actual URL that is used.

**Comment by matigonkas** [comment]
on the code its that the one thats being used https://github.com/SiCKRAGETV/SickRage/blob/bf2baf309bd01683fdc06d57ece0b89d53b4a180/sickbeard/indexers/indexer_config.py#L51

**Comment by neoatomic** [comment]
I took a look and you are indeed correct! My mistake... :(

The TVDB list we are retrieving from another Repo. :
https://github.com/SiCKRAGETV/SickRage/blob/bf2baf309bd01683fdc06d57ece0b89d53b4a180/sickbeard/indexers/indexer_config.py#L43

@fernandog Are you able to approve those PR's or has only echel0n the rights?

**Comment by miigotu** [comment]
@neoatomic echel0n doesnt have access to that repo afaik, we need @fernandog to fork it into SiCKRAGETV organization, and give admins access to the scene exceptions repos. Then we can snatch unmerged PR's from midgetspy's repo and merge them here.

**Comment by neoatomic** [comment]
@fernandog @miigotu . Could one of you approve those PR's so this can be closed.?

**Comment by miigotu** [comment]
Working on merging these, some rebases need done.
