### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-73387 :: Unable to parse Craig.Ferguson.2012.12.02.Henry.Winkler.Ariel.Tweto.720p.HDTV.x264-W4F into a scene name. If it's a valid one log a bug.

### ISSUE THREAD

**Issue by identd113** [SiCKRAGETV/sickrage-issues#1681]
### INFO
Python Version: **2.7.6 (default, Sep  9 2014, 15:04:36) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]**
Operating System: **Darwin-14.3.0-x86_64-i386-64bit**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-73387 :: Unable to parse Craig.Ferguson.2012.12.02.Henry.Winkler.Ariel.Tweto.720p.HDTV.x264-W4F into a scene name. If it's a valid one log a bug.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@identd113 It contains no season and episode number.
