### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/share/MD0_DATA/Download/transmission/completed/CSI.Cyber.S01E11.HDTV.x264-LOL.mp4'

### ISSUE THREAD

**Issue by Peke** [SiCKRAGETV/sickrage-issues#1682]
### INFO
Python Version: **2.7.3 (default, Apr 12 2012, 20:25:04) [GCC 4.2.1]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.0**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@Peke Logs.? Without we cant do anything. But looks like the file was removed before it could be processed. Maybe a failed download, or was moved by another application.

**Comment by Peke** [comment]
No New error logs Good call on closure THX.
