### ISSUE TITLE
[APP SUBMITTED]: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/44824/en.xml

### ISSUE THREAD

**Issue by Peke** [SiCKRAGETV/sickrage-issues#1683]
### INFO
Python Version: **2.7.3 (default, Apr 12 2012, 20:25:04) [GCC 4.2.1]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.0**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/17f2b5bdb3a48c05564c
### ERROR
```
SHOWQUEUE-ADD :: Unable to find show ID:44824 on Indexer: theTVDB
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Peke** [comment]
Show is incorrectly detected and can't be imported Actual ID is  295759 and After XML and NFO changes manually before readding the show all is OK SHOW Added

**Comment by neoatomic** [comment]
@Peke I just added "Supergirl" as a new show, and as an existing show. Both work fine here.
Looking at the log its shows the error happens during downloading. So you have a bad installation or SSL is again giving problems on your QNAP...
