### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-73141 :: Transmission: Unable to send Torrent: Return code undefined

### ISSUE THREAD

**Issue by Danny89530** [SiCKRAGETV/sickrage-issues#1686]
### INFO
Python Version: **2.7.3 (default, Mar 14 2014, 11:57:14) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-686-pae-i686-with-debian-7.8**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-73141 :: Transmission: Unable to send Torrent: Return code undefined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@Danny89530 no logs. 
But judging from you other issue SSL is to blame here. https://github.com/SiCKRAGETV/sickrage-issues/issues/1687

**Comment by Danny89530** [comment]
Hi
      Thanx for your fast response and sorry for blame, I thought that
      they were two different errors.
      Anyway, is possible to request to add a search provider?
      
      Thanx
    
    Il 25/05/15 13:23, neoatomic ha
      scritto:
    
    
      Closed #1686.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by neoatomic** [comment]
@Danny89530 If Transmission was broken that it would be flooded with opened issues. :)
Sure, you can create a feature request for the specific provider.

**Comment by Danny89530** [comment]
Can you guide me?
      I don't know where i have to add the feature request.
      I'm not so friendly with github.
      
      Thanx, again.
    
    Il 25/05/15 13:42, neoatomic ha
      scritto:
    
    
      @Danny89530 If Transmission was
        broken that it would be flooded with opened issues. :)
        Sure, you can create a feature request for the specific
        provider. 
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by neoatomic** [comment]
Just add a new issue and add [Feature Request] in front of it.

**Comment by nevski99** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 12 2015, 15:47:37) [GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]**
Operating System: **Linux-2.6.32-573.3.1.el6.x86_64-x86_64-with-centos-6.7-Final**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@9c10c8e3844297100f9cea6ea7a879a1ede1b2db
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-275278 :: [Rarbg] :: Transmission: Unable to send Torrent: Return code undefined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
