### ISSUE TITLE
[APP SUBMITTED]: ('Connection aborted.', error(111, 'Connessione rifiutata'))

### ISSUE THREAD

**Issue by Danny89530** [SiCKRAGETV/sickrage-issues#1687]
### INFO
Python Version: **2.7.3 (default, Mar 14 2014, 11:57:14) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-686-pae-i686-with-debian-7.8**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/c06f42d50a8ecd36e4e8
### ERROR
```
SEARCHQUEUE-MANUAL-79275 :: [TNTVillage] :: Unable to connect to TNTVillage provider: error ('Connection aborted.', error(111, 'Connessione rifiutata'))
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@Danny89530 SSL errors. Also update Phyton
If you cant disable the providers that use HTTPS.

``` error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1  ```

https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors
