### ISSUE TITLE
[Feature Request] CorsaroNero Provider

### ISSUE THREAD

**Issue by Danny89530** [SiCKRAGETV/sickrage-issues#1688]
Hi,
Just a request for adding the provider of Italian Torrent Searcher 'http://ilcorsaronero.info/'.

Thanx in advance

**Comment by gborri** [comment]
@Danny89530 do you know that sickrage now has built in TNTVillage provider(italian torrent)?

**Comment by Danny89530** [comment]
I know, but rarely SR snatch something.
Generally i've to found manually my episodes.

**Comment by gborri** [comment]
@Danny89530 it working so good for me. let me know what's wrong

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
