### ISSUE TITLE
Sickrage Won't Start

### ISSUE THREAD

**Issue by wordguy** [SiCKRAGETV/sickrage-issues#1690]
I can't get Sickrage to load or access the web GUI. I'm on Windows 7. Python 2.7.9

https://gist.github.com/wordguy/d9eb3af908780a0efb65#file-gistfile1-txt

<script src="https://gist.github.com/wordguy/d9eb3af908780a0efb65.js"></script>

<script src="https://gist.github.com/wordguy/d9eb3af908780a0efb65.js"></script

**Comment by neoatomic** [comment]
Remove everything and do a clean installation. Here is a guide that should get you started. : 

http://www.htpcguides.com/install-sickrage-windows-usenet-torrent-tv//
