### ISSUE TITLE
[APP SUBMITTED]: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by Danny89530** [SiCKRAGETV/sickrage-issues#1691]
### INFO
Python Version: **2.7.3 (default, Mar 14 2014, 11:57:14) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-686-pae-i686-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/980425741a6acc2b7f38
### ERROR
```
Thread-128 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1042, in testNMA
    result = notifiers.nma_notifier.test_notify(nma_api, nma_priority)
  File "/opt/sickrage/sickbeard/notifiers/nma.py", line 10, in test_notify
    force=True)
  File "/opt/sickrage/sickbeard/notifiers/nma.py", line 55, in _sendNMA
    response = p.push(title, event, message, priority=nma_priority, batch_mode=batch)
  File "/opt/sickrage/lib/pynma/pynma.py", line 94, in push
    res = self.callapi('POST', ADD_PATH, datas)
  File "/opt/sickrage/lib/pynma/pynma.py", line 108, in callapi
    http_handler.request(method, path, urlencode(args), headers)
  File "/usr/lib/python2.7/httplib.py", line 962, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 996, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 958, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 818, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 780, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1165, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib/python2.7/ssl.py", line 381, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 143, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 104] Connection reset by peer

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Same as https://github.com/SiCKRAGETV/sickrage-issues/issues/1687
Fix your SSL. or disable providers that use HTTPS.

**Comment by Danny89530** [comment]
I've this problem when SickRage send me a notification (NMA in my case).
This cause not updating the episodes status (from Wanted to Snatched).
I've alredy updated SSL yesterday.

**Comment by neoatomic** [comment]
The log shows SR is unable to setup a SSL connection. So clearly something is not installed/set correctly...
Maybe the certificate.?

``` 
 File "/usr/lib/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 104] Connection reset by peer
```

@fernandog As you run a RPi also, any idea what the problem can be.?

**Comment by Danny89530** [comment]
Just per info, that's no a RaspPi, the host is a VM running on ESXi 5.5.0U2

**Comment by neoatomic** [comment]
My mistake, did confuse you with another user... :( 
Hope one of the Dev's can join in, as i can only think of a SSL / certificate problem.

**Comment by ellorb** [comment]
To the Dev's: replacing API_SERVER = 'nma.usk.bz' with API_SERVER = 'www.notifymyandroid.com' in pynma.py resolves this error.

**Comment by Danny89530** [comment]
True story.
The above solution fixed the error.
Everything back to normally: also the ep's state changed from 'Wanted' to 'Snatched' now.

I think Dev's have to implement this fix in future releases.

**Comment by neoatomic** [comment]
@ellorb Thanks for letting us know. 
@Danny89530 I have submitted a PR so this should be fixed with the next update.

**Comment by EternallyBored** [comment]
### INFO
Python Version: **2.7.6 (default, Sep 15 2015, 20:06:23) [GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]**
Operating System: **Linux-2.6.32-042stab108.8-x86_64-with-centos-6.7-Final**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-75692 :: [ExtraTorrent] :: Error while searching ExtraTorrent, skipping: error 104 : Connection reset by peer
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
