### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/volume2/Download/TV Shows/Game.of.Thrones.S05E07.1080p.HDTV/Game.of.Thrones.S05E07.1080p.HDTV.x264-BATV.mkv'

### ISSUE THREAD

**Issue by francoistamigniau** [SiCKRAGETV/sickrage-issues#1692]
### INFO
Python Version: **2.7.9 (default, Mar 23 2015, 00:06:48) [GCC 4.3.2]**
Operating System: **Linux-2.6.32.12-ppc-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Unable to move file /volume2/Download/TV Shows/Game.of.Thrones.S05E07.1080p.HDTV/Game.of.Thrones.S05E07.1080p.HDTV.x264-BATV.mkv to /volume1/Series/Game Of Thrones/Season 5/Game of Thrones - S05E07 - The Gift.mkv: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
File was removed. But without logs we cant say more.
