### ISSUE TITLE
Unable to connect to TorrentDay provider - Pip command not found?

### ISSUE THREAD

**Issue by kendog819** [SiCKRAGETV/sickrage-issues#1693]
![image](https://cloud.githubusercontent.com/assets/11353628/7821810/5974dfee-03bf-11e5-9d79-424218b3472b.png)

![image](https://cloud.githubusercontent.com/assets/11353628/7821774/2c9f12a0-03bf-11e5-8b11-ea7176732c25.png)

![image](https://cloud.githubusercontent.com/assets/11353628/7821824/6f857172-03bf-11e5-890b-18d0836df7fa.png)

Any idea how to get this working properly? These error logs are driving me nuts..

![image](https://cloud.githubusercontent.com/assets/11353628/7821864/98209972-03bf-11e5-81c6-5437718c6228.png)

Thanks,
Ken

**Comment by neoatomic** [comment]
This is a QNAP problem that we cant fix. 
However i have read something about qpython2, and that it could solve this.

**Comment by kendog819** [comment]
"However i have read something about qpython2, and that it could solve this." 

Care to expand?

**Comment by neoatomic** [comment]
@kendog819 QNAP needs to get there devices updated to get this fixed. Its not SickRage related.

I read that a QNAP user was going to try qpython2. I suspect that this is a third party python package to get by the outdated QNAP version.?

**Comment by kendog819** [comment]
Well here is the temp fix for QNAP users. That fix posted on the linked page above should be removed since it doesn't work.

Replace:
![image](https://cloud.githubusercontent.com/assets/11353628/7840020/75fe1d8e-0463-11e5-831e-33f1443163c2.png)

With:
![image](https://cloud.githubusercontent.com/assets/11353628/7840033/8b45a57c-0463-11e5-85ef-347d18c4ef7a.png)
