### ISSUE TITLE
[APP SUBMITTED]: [Errno socket error] [Errno 111] Connection refused

### ISSUE THREAD

**Issue by mrmann** [SiCKRAGETV/sickrage-issues#1694]
### INFO
Python Version: **2.7.5 (default, Aug 29 2013, 19:15:20) [GCC 4.5.1]**
Operating System: **Linux-3.2.27-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
No Log available with ERRORS: 
### ERROR
```
Thread-62 :: Unable to connect to SAB: socket error : error [Errno 111] Connection refused
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@mrmann please post logs.

**Comment by toxic17** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-121361 :: [Usenet-Crawler] :: Unable to connect to SAB: socket error : error [Errno 111] Connection refused
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
