### ISSUE TITLE
Daily searcher error. 

### ISSUE THREAD

**Issue by jotavip** [SiCKRAGETV/sickrage-issues#1696]
Hi, my sickrage is installed on my QNAP 269 Pro and it is showing the following error since the latest update: 

`2015-05-26 22:32:33 WARNING  DAILYSEARCHER :: Loading zoneinfo.txt failed, this can happen from time to time. Unable to get URL: https://raw.githubusercontent.com/Prinz23/sb_network_timezones/master/zoneinfo.txt
AA
AAAttributeError: '_socketobject' object has no attribute 'set_tlsext_host_name'
AA    cnx.set_tlsext_host_name(server_hostname)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 296, in ssl_wrap_socket
AA    ssl_version=resolved_ssl_version)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connection.py", line 238, in connect
AA    conn.connect()
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 740, in _validate_conn
AA    self._validate_conn(conn)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 326, in _make_request
AA    body=body, headers=headers)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 529, in urlopen
AA    timeout=timeout
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/adapters.py", line 370, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/cachecontrol/adapter.py", line 34, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 573, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 461, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 473, in get
AA    return super(CacheControlSession, self).get(*args, **kw)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/cachecontrol/session.py", line 23, in get
AA    resp = session.get(url, timeout=timeout)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1294, in getURL
2015-05-26 22:32:33 WARNING  DAILYSEARCHER :: Unknown exception while loading URL https://raw.githubusercontent.com/Prinz23/sb_network_timezones/master/zoneinfo.txt: Traceback (most recent call last):
2015-05-26 22:32:33 WARNING  DAILYSEARCHER :: Updating network timezones failed, this can happen from time to time. URL: https://raw.githubusercontent.com/Prinz23/sb_network_timezones/master/network_timezones.txt
AA
AAAttributeError: '_socketobject' object has no attribute 'set_tlsext_host_name'
AA    cnx.set_tlsext_host_name(server_hostname)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 296, in ssl_wrap_socket
AA    ssl_version=resolved_ssl_version)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connection.py", line 238, in connect
AA    conn.connect()
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 740, in _validate_conn
AA    self._validate_conn(conn)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 326, in _make_request
AA    body=body, headers=headers)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 529, in urlopen
AA    timeout=timeout
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/adapters.py", line 370, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/cachecontrol/adapter.py", line 34, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 573, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 461, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 473, in get
AA    return super(CacheControlSession, self).get(*args, **kw)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/cachecontrol/session.py", line 23, in get
AA    resp = session.get(url, timeout=timeout)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1294, in getURL`

**Comment by neoatomic** [comment]
@jotavip The known QNAP SSL errors. Noting we can do about that. 
You have to ask QNAP to fix this.

https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors
https://github.com/SiCKRAGETV/sickrage-issues/issues/1580
