### ISSUE TITLE
[APP SUBMITTED]: [Errno 40] Too many levels of symbolic links: "/media/2A06DF4A06DF1623/media/serier/Marvel's Agents of S.H.I.E.L.D/Season 02/Marvel's Agents of S.H.I.E.L.D - S02E12 - Who You Really Are.mkv"

### ISSUE THREAD

**Issue by Symbiot78** [SiCKRAGETV/sickrage-issues#1697]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.16.0-0.bpo.4-amd64-x86_64-with-debian-7.8**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/524084e9e2ba8669bc2d
### ERROR
```
Thread-18 :: Unable to get size for file /media/2A06DF4A06DF1623/media/serier/Marvel's Agents of S.H.I.E.L.D/Season 02/Marvel's Agents of S.H.I.E.L.D - S02E12 - Who You Really Are.mkv. Error msg is: [Errno 40] Too many levels of symbolic links: "/media/2A06DF4A06DF1623/media/serier/Marvel's Agents of S.H.I.E.L.D/Season 02/Marvel's Agents of S.H.I.E.L.D - S02E12 - Who You Really Are.mkv"
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@Symbiot78 . see https://github.com/SiCKRAGETV/sickrage-issues/issues/1648 
You probably haven't setup symbolic links correctly.
