### ISSUE TITLE
[APP SUBMITTED]: too many SQL variables

### ISSUE THREAD

**Issue by mrmann** [SiCKRAGETV/sickrage-issues#1698]
### INFO
Python Version: **2.7.5 (default, Aug 29 2013, 19:15:20) [GCC 4.5.1]**
Operating System: **Linux-3.2.27-armv7l-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
No Log available with ERRORS: 
### ERROR
```
MAIN :: DB error: too many SQL variables
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@mrmann Please post logs.

**Comment by fernandog** [comment]
he probably try to mass update a lot of shows exceeding sqlite limit
