### ISSUE TITLE
[APP SUBMITTED]: [Errno 13] Permission denied: u'C:\\_Data\\TVSeries\\The Missing\\Season 01\\The Missing - S01E01 - Eden (720p.BluRay-7SinS).mkv'

### ISSUE THREAD

**Issue by Rouzax** [SiCKRAGETV/sickrage-issues#1699]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-REFRESH :: File air date stamping failed(Permission denied). Check permissions for file: C:\_Data\TVSeries\The Missing\Season 01\The Missing - S01E01 - Eden (720p.BluRay-7SinS).mkv
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Rouzax** [comment]
The permissions on the file and folder are exactly the same as any of the other files and folders where the date time can be changed successfully.

**Comment by neoatomic** [comment]
@Rouzax Logs.?
In the past there where some timestamp problems for 2012, but those where solved.:
https://sickrage.tv/forums/forum/help-support/general-support/17718-unable-to-modify-date-of-windows

Also this error clearly states its a Permission problem. And if it works on other files than is must be specific for this file. So leaves me to think the file was "in use" at the time. Probably seeding.? Still unzipping etc.

You can also disable time stamping. Go to Settings -> Post-Processing, and disable the option called "Change File Date"

**Comment by Rouzax** [comment]
Here is the log after a Full Update
http://pastebin.com/fvx4LUh8

The files are not in use, I do the seeding from a different location and the files in questions are unpacked copies.
Here are the permissions for a file in question and one were the update succeeds.

The Missing - Fails
![image](https://cloud.githubusercontent.com/assets/4103090/7834748/b507fa7c-0472-11e5-8ee2-39473a287d0d.png)

The Simpsons - OK
![image](https://cloud.githubusercontent.com/assets/4103090/7834778/fcadda68-0472-11e5-8cc6-e027ae7c95ca.png)

**Comment by neoatomic** [comment]
Vreemd... Geeft de eventvieuwer van 2012 nog iets van een melding.? (Probeer anders eens te loggen.)
Ik kan er geen andere verklaring voor geven dan dat het bestand in gebruik is.

Zet anders even de "Change File Date" functie bij PP uit. En kijk dan eens als de foumelding weg is.

**Comment by Rouzax** [comment]
There is nothing in the Event Log of the server.
If I look with Process Monitor there isn't any record trying to access the path of the series that fails.

It looks like there is an error in the script.
See the line from the log.
```
2015-05-27 13:10:55 DEBUG    SHOWQUEUE-REFRESH :: 282401: About to modify date of 'C:\_Data\TVSeries\The Missing\Season 01\The Missing - S01E01 - Eden (720p.BluRay-7SinS).mkv' to show air date okt 28,2014 (22:00)
2015-05-27 13:10:55 ERROR    SHOWQUEUE-REFRESH :: File air date stamping failed(Permission denied). Check permissions for file: C:\_Data\TVSeries\The Missing\Season 01\The Missing - S01E01 - Eden (720p.BluRay-7SinS).mkv
Traceback (most recent call last):
  File "C:\SickRage\sickbeard\helpers.py", line 1220, in touchFile
    with file(fname, 'a'):
IOError: [Errno 13] Permission denied: u'C:\\_Data\\TVSeries\\The Missing\\Season 01\\The Missing - S01E01 - Eden (720p.BluRay-7SinS).mkv'
2015-05-27 13:10:55 ERROR    SHOWQUEUE-REFRESH :: 282401: Unable to modify date of The Missing - S01E01 - Eden (720p.BluRay-7SinS).mkv to show air date okt 28,2014 (22:00)
None
```

To check if there was an file in use I tried to change the file name without any issue

**Comment by Rouzax** [comment]
I've found it :smiley: 
![image](https://cloud.githubusercontent.com/assets/4103090/7836725/b92ebf86-0482-11e5-9475-a8268ab9ab46.png)

Apparently the downloaded files were packed with the read only file attribute. :blush::flushed:

**Comment by Rouzax** [comment]
@neoatomic Hoe wist je dat ik nederlands ben?

**Comment by neoatomic** [comment]
Bij de email notificatie stond je naam. :)

Het lijkt erop dat een specifieke release groep dit doet.? Om het in de toekomst te voorkomen kun je bij "Ignored Words:" die naam invullen. Dan skipt SR die in de toekomst.
