### ISSUE TITLE
[APP SUBMITTED]: Error occurred when downloading subtitles: 

### ISSUE THREAD

**Issue by cgram23** [SiCKRAGETV/sickrage-issues#1703]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-38-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/229a9b5a5fdce51e7b26
### ERROR
```
FINDSUBTITLES :: Error occurred when downloading subtitles: 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@cgram23 Your log doesn't hold a "Traceback" so we cant see why it was unable to download.
Can you check your sickrage.log file and see if its more detailed than the part of the log you have posted.? Otherwise we are unable to look into it...

**Comment by cgram23** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-38-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/357ef1ed7a7fe25c890f
### ERROR
```
FINDSUBTITLES :: Error occurred when downloading subtitles: 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by cgram23** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-38-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/fa1623d87d6bc90f916a
### ERROR
```
FINDSUBTITLES :: Error occurred when downloading subtitles: 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by cgram23** [comment]
Here are the tracebacks seen in my logs:

AAStopIteration
AA    title2 = next(find_nodes(mtree2.match_tree, 'title'))
AA  File "/home/chris/.sickrage/lib/guessit/__init__.py", line 138, in _guess_filename
AA    result.append(_guess_filename(filename, filetype))
AA  File "/home/chris/.sickrage/lib/guessit/__init__.py", line 210, in guess_file_info
AA    guess = guessit.guess_file_info(path, 'autodetect')
AA  File "/home/chris/.sickrage/lib/subliminal/videos.py", line 85, in from_path
AA    video = Video.from_path(entry)
AA  File "/home/chris/.sickrage/lib/subliminal/videos.py", line 258, in scan
AA    scan_result.extend(scan(p, max_depth, scan_filter))
AA  File "/home/chris/.sickrage/lib/subliminal/core.py", line 59, in create_list_tasks
AA    tasks = create_list_tasks(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
AA  File "/home/chris/.sickrage/lib/subliminal/api.py", line 55, in list_subtitles
AA    subtitles_by_video = list_subtitles(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
AA  File "/home/chris/.sickrage/lib/subliminal/api.py", line 96, in download_subtitles
AA    multi=sickbeard.SUBTITLES_MULTI, cache_dir=sickbeard.CACHE_DIR)
AA  File "/home/chris/.sickrage/sickbeard/tv.py", line 1425, in downloadSubtitles
AATraceback (most recent call last):
2015-05-30 11:31:04 ERROR    FINDSUBTITLES :: Error occurred when downloading subtitles: 
2015-05-30 11:31:04 INFO     FINDSUBTITLES :: Checking for subtitles

**Comment by neoatomic** [comment]
Subtitles are downloading fine here. 
What subtitle providers are you using.? And was this a one time error, or do you get it every-time.?
Try to remove the cache folder and see if that solves it.

**Comment by mchrisley** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 23 2015, 00:07:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@42b8d5a9c71c87fcde301967b6254ef08c3093ac
Link to Log: https://gist.github.com/fb7f079f0556c48e067f
### ERROR
```
FINDSUBTITLES :: Error occurred when downloading subtitles: 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by JaredKotoff** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@42b8d5a9c71c87fcde301967b6254ef08c3093ac
No Log available with ERRORS: 
### ERROR
```
FINDSUBTITLES :: Error occurred when downloading subtitles: 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Again, What subtitle providers are you using.?

**Comment by JaredKotoff** [comment]
Opensubtitles and Thesubdb. 
Its not happening every time.
I still see this after deleting cache folder.

**Comment by gabestover** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-4.0.4-unRAID-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@e6c4cfd6546b74d5527361f6f0bdc3adc232bdb0
No Log available with ERRORS: 
### ERROR
```
FINDSUBTITLES :: Error occurred when downloading subtitles: 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
See: http://git.io/vJrkM
