### ISSUE TITLE
[Feature request] : Add notification on removing shows in Mass Update

### ISSUE THREAD

**Issue by bolemeus** [SiCKRAGETV/sickrage-issues#1704]
So I just deleted my entire collection thinking I was just removing them from the Sickbeard database.

Shouldn't there be a confirmation dialog when the user tries to delete shows in that screen? I'm kinda bummed I have to download everything again...

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!

**Comment by bolemeus** [comment]
I'll do that. It doesn't look like it exists there yet.
