### ISSUE TITLE
[SUGGESTION] Easy method to list shows with missing/incorrect diectories

### ISSUE THREAD

**Issue by NuclearDog33451** [SiCKRAGETV/sickrage-issues#1706]
Not sure if it would help many others but it would be nice if it was possible to easily list all shows with a missing directory path. Only reason I say is that if you forget to update the directory when you move or rename a show then it will fail to update. Not an issue with a small amount of shows but a pain to sort with a large show list.

**Comment by neoatomic** [comment]
Dont see a need for this. If you click on "add existing show" SR shows all the folders are shown that are not in use yet. Also why would you move change the folder anyway.? Better to setup SR correctly at the start if you need to store the files somewhere else...
