### ISSUE TITLE
[APP SUBMITTED]: 'module' object is not callable

### ISSUE THREAD

**Issue by rootwyrm** [SiCKRAGETV/sickrage-issues#1709]
### INFO
Python Version: **2.7.9 (default, May 16 2015, 23:17:47) [GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)]**
Operating System: **FreeBSD-10.1-RELEASE-p10-i386-32bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@92bf581ba8a7d4f2f912db795ce571b6ad38c3c2
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-MANUAL-70900 :: [NyaaTorrents] :: Error while searching NyaaTorrents, skipping: 'module' object is not callable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@rootwyrm please post logs or we are unable to look into it.
