### ISSUE TITLE
[APP SUBMITTED]: database disk image is malformed

### ISSUE THREAD

**Issue by Borgcustom** [SiCKRAGETV/sickrage-issues#1710]
### INFO
Python Version: **2.7.3 (default, Apr 10 2012, 23:24:47) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2008ServerR2-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@92bf581ba8a7d4f2f912db795ce571b6ad38c3c2
Link to Log: https://gist.github.com/38667fc20c4f541d9dfc
### ERROR
```
SEARCHQUEUE-MANUAL-167751 :: [nzb.su] :: Error while searching nzb.su, skipping: database disk image is malformed
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Borgcustom** [comment]
### INFO
Python Version: **2.7.3 (default, Apr 10 2012, 23:24:47) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2008ServerR2-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@92bf581ba8a7d4f2f912db795ce571b6ad38c3c2
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-290176 :: [nzb.su] :: Error while searching nzb.su, skipping: database disk image is malformed
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/549#issuecomment-72844385

**Comment by Borgcustom** [comment]
### INFO
Python Version: **2.7.3 (default, Apr 10 2012, 23:24:47) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2008ServerR2-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@e39fae0502b0993fd0163ea2f6888871426465be
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-MANUAL-267543 :: [nzb.su] :: Error while searching nzb.su, skipping: database disk image is malformed
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
