### ISSUE TITLE
KeyError: 'date' during SickRage start

### ISSUE THREAD

**Issue by Rouzax** [SiCKRAGETV/sickrage-issues#1711]
Not sure if this is an issue but with the latest version I get the following log messages:
http://pastebin.com/nC5nyXKm

SR Version:	BRANCH: (master) / COMMIT: 92bf581ba8a7d4f2f912db795ce571b6ad38c3c2 
SR User:	Download
SR Locale:	('nl_NL', 'cp1252')
SR Config file:	C:\Program Files (x86)\SickRage\config.ini
SR Database file:	C:\Program Files (x86)\SickRage\sickbeard.db
SR Cache Dir:	C:\Program Files (x86)\SickRage\cache
SR Log Dir:	C:\Program Files (x86)\SickRage\Logs
SR Arguments:	['--nolaunch']
Python Version:	2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]

**Comment by fernandog** [comment]
@miigotu new requests?

**Comment by miigotu** [comment]
@fernandog nope, we have seen this before. forking Prinz23/sb_network_timezones into the organization and giving access to admins will eliminate some more https calls though.  Maybe I can look into this one after some sleeeeeeep.

**Comment by neoatomic** [comment]
Prinz23/sb_network_timezones was forked and now using http instead of https. So this should be solved.
