### ISSUE TITLE
[APP SUBMITTED]: 422 {u'documentation_url': u'https://developer.github.com/v3/issues/#create-an-issue', u'message': u'Validation Failed', u'errors': [{u'field': u'title', u'message': u'title is too long', u'code': u'custom', u'resource': u'Issue'}]}

### ISSUE THREAD

**Issue by razlebol** [SiCKRAGETV/sickrage-issues#1712]
### INFO
Python Version: **2.7.6 (default, Apr  3 2014, 09:45:36) [GCC 4.5.3]**
Operating System: **Linux-3.4.90-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@92bf581ba8a7d4f2f912db795ce571b6ad38c3c2
Link to Log: https://gist.github.com/a2705c8af50f78bea2af
### ERROR
```
Thread-375 :: 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by stourwalk** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 26 2013, 20:01:12) [GCC 4.4.4]**
Operating System: **Linux-3.9.6p-unRAID-i686-AMD_Athlon-tm-_II_Neo_N36L_Dual-Core_Processor-with-slackware-13.1.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@92bf581ba8a7d4f2f912db795ce571b6ad38c3c2
Link to Log: https://gist.github.com/cf63bcd9be9fd512984d
### ERROR
```
Thread-383 :: 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by HakShak** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 22 2015, 23:26:38) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@92bf581ba8a7d4f2f912db795ce571b6ad38c3c2
Link to Log: https://gist.github.com/ec87828e34c6ff203ed0
### ERROR
```
Thread-41 :: 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by HakShak** [comment]
I can't tell if this is just GitHub complaining that the auto-app submit sometimes has giant titles because of the callstack? @stourwalk and I seem to have the same problem, but @razlebol 's log looks completely unrelated.

**Comment by pierre2013** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@92bf581ba8a7d4f2f912db795ce571b6ad38c3c2
Link to Log: https://gist.github.com/cc67feb25b5795dba699
### ERROR
```
Thread-36 :: 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by eph2112** [comment]
### INFO
Python Version: **2.7.8 (default, Dec 15 2014, 02:33:48) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@92bf581ba8a7d4f2f912db795ce571b6ad38c3c2
Link to Log: https://gist.github.com/29f5ed6dbe455f996c62
### ERROR
```
Thread-622 :: 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@miigotu strange as we already fixed this

**Comment by fernandog** [comment]
reopen if happens again
