### ISSUE TITLE
Sickrage and Yowsup doesn't play nice together

### ISSUE THREAD

**Issue by IamC8** [SiCKRAGETV/sickrage-issues#1713]
Hi, when I update yowsup (https://github.com/tgalal/yowsup), with python setup.py install , Sickrage start giving erros about ssl.
"https://raw.githubusercontent.com/SiCKRAGETV/sr_tvrage_scene_exceptions/master/exceptions.txt" cant be found. 
I then do 
wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py -O - | sudo python2
sudo pip install -U cryptography ndg-httpsclient pyopenssl
and Sickrage works again but now yowsup gives errors

Is there a way to have the two running on one computer?

**Comment by neoatomic** [comment]
We replaced that url with a HTTP link instead of HTTPS. That will prevent the error from showing. However you still should fix your ssl installation.
