### ISSUE TITLE
[APP SUBMITTED]: Your authentication credentials for Usenet-Crawler are missing, check your config.

### ISSUE THREAD

**Issue by emeljay42** [SiCKRAGETV/sickrage-issues#1716]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@92bf581ba8a7d4f2f912db795ce571b6ad38c3c2
No Log available with ERRORS: 
### ERROR
```
FINDPROPERS :: [Usenet-Crawler] :: Authentication error: Your authentication credentials for Usenet-Crawler are missing, check your config.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@emeljay42 Add the API key from your Usenet-Crawler account to SickRage.

**Comment by emeljay42** [comment]
Thank you
