### ISSUE TITLE
Auto Post-Processing: Buggy (sometimes doesnt happen)

### ISSUE THREAD

**Issue by syrys** [SiCKRAGETV/sickrage-issues#1717]
So, i have sickrage installed in a dedicated machine that i dont turn off very often (atleast dont plan on). I have the download method set to blackhole and uses qbittorrent to download the files and send the back to the blackhole folder.

So, the problem is, For most part, sick rage works just fine, but every so often, i notice that it hasent processed any files in a while. Specially this morning (and every couple of days), there were a lot of completed files on the blackhole folder, but they werent being processed. When this happens, i either restart the computer (which seems to trigger the post process job), or click manual post process and select the folder.

In the configuration options, i have "Auto Post-Processing Frequency" set to 1. 

What am i doing wrong and why does it not work properly? :(

**Comment by syrys** [comment]
In the error log, there isnt any relevant errors logged that sounds related either.

**Comment by neoatomic** [comment]
Follow the guidelines for posting an issue.: https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket
