### ISSUE TITLE
[APP SUBMITTED]: u'Robot.Chicken.S04E01.Help.Me.Dvdrip.Xvid'

### ISSUE THREAD

**Issue by Xenocell12** [SiCKRAGETV/sickrage-issues#1719]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@92bf581ba8a7d4f2f912db795ce571b6ad38c3c2
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-75734 :: [Usenet-Crawler] :: Error while searching Usenet-Crawler, skipping: Robot.Chicken.S04E01.Help.Me.Dvdrip.Xvid
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Please post logs, or we are unable to look into it.
