### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-72879 :: Unable to parse Animaniacs.S05E14E12E21E13.DVDRip.XviD-DEiMOS.Repost into a scene name. If it's a valid one log a bug.

### ISSUE THREAD

**Issue by PhuriousGeorge** [SiCKRAGETV/sickrage-issues#1721]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.18.6-aufs-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-72879 :: Unable to parse Animaniacs.S05E14E12E21E13.DVDRip.XviD-DEiMOS.Repost into a scene name. If it's a valid one log a bug.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
A episode number of S05E14E12E21E13 is clearly not correct.
