### ISSUE TITLE
Login Fail

### ISSUE THREAD

**Issue by Falci** [SiCKRAGETV/sickrage-issues#1722]
A few days ago I noticed that some series were outdated.
I have checked in SickRage, there were many errors related to authentication in Transmission.
I tried to change the settings, but it was always redirected to the page / home and a new error arose (something reladionado the webserver.py and uft-8 issues)

So I decided to try to update.
I used the link dento of SickRage, but he said he did not know the current version. I did not understand well.
I tried to upgrade by Kodi, but I'm not sure if all went well.

Now the SR ended the session and I can not log more.

I tried to make the step README.md this repo, but Kodi command line has not git (or apt-get)

How to proceed?

**Comment by neoatomic** [comment]
Follow the guidelines for posting an issue.: https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket

**Comment by Falci** [comment]
Thanks for quickly anwser, but I know just some informations:

- [ ] Branch
- [ ] Commit hash
- [x] Your operating system and python version
* OpenELEC (official) - Version: 5.0.8 (kernel: Linux 3.17.8)
* Kodi 14.2 Git: 7cc53a9
* Python 2.7.3 (from python -v)

- [x] What you did
* As the first post: updates

- [x] What happened
* Unable to login. No error messages

- [x] What you expected
* Be able to login and change the configuration

- [ ] Link to a copy/paste of your logfile with clear debug info of the error on GIST
* Unable to access UI
* I didn't find log file

**Comment by neoatomic** [comment]
@Falci Sounds like something went wrong updating and you ended up with a bad installation. Best to do a clean/fresh install of Sickrage. 
However i'm not familiar with OpenELEC, but if its a plug-in/package in OpenELEC, then there should be an author who can help you. Only thing i found was this guide. http://htpc15.blogspot.nl/2015/02/sickrage.html
Hope this helps.
