### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-97731 :: qbittorrent: Unable to send Torrent: Return code undefined

### ISSUE THREAD

**Issue by snakethejake81** [SiCKRAGETV/sickrage-issues#1723]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@92bf581ba8a7d4f2f912db795ce571b6ad38c3c2
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-97731 :: qbittorrent: Unable to send Torrent: Return code undefined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Please post logs. Or we are unable to look into it.

**Comment by neoatomic** [comment]
Also see https://github.com/SiCKRAGETV/sickrage-issues/issues/1625

**Comment by snakethejake81** [comment]
Sorry, didn't mean to submit this.  Thanks.
