### ISSUE TITLE
Deleted shows keep coming back

### ISSUE THREAD

**Issue by FlyGuy94** [SiCKRAGETV/sickrage-issues#1724]
Branch: both develop and master
Commit hash: 921adb1e2a3fb93e0ff9e5c74d88db963874d829
Your operating system and python version: Synology DSM 5.1 5022.3 pyton 2.7.9-13
What you did: I deleted 4 shows 
What happened: They came back after about 15 minutes.
What you expected: That they would not come back.
Link to a copy/paste of your logfile with clear debug info of the error: 
https://gist.github.com/FlyGuy94/5872219bf3055902093f
I have marked the shows I tried to delete. For some reason da vinci's deamons shows up twice?
![knipsel](https://cloud.githubusercontent.com/assets/11855105/7901730/01affee8-0797-11e5-8380-d2ff8b719474.PNG)

**Comment by miigotu** [comment]
@FlyGuy94 you have to remove them from your trakt watch list first. ie: you are removing them form SR, and trakt is telling SR you want it again.

**Comment by FlyGuy94** [comment]
That's annoying can't you make it so if you remove it from SR it also removes it from trakt?

**Comment by miigotu** [comment]
You could search for a feature request for this, and if there isn't one you can request it.
