### ISSUE TITLE
[APP SUBMITTED]: CHECKVERSION :: git fetch origin returned : fatal: unable to access 'https://github.com/SiCKRAGETV/SickRage.git/': GnuTLS recv error (-9): A TLS packet with unexpected length was received.

### ISSUE THREAD

**Issue by papampi** [SiCKRAGETV/sickrage-issues#1725]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-53-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@92bf581ba8a7d4f2f912db795ce571b6ad38c3c2
Link to Log: https://gist.github.com/761f7471eb1e4f0c091d
### ERROR
```
CHECKVERSION :: git fetch origin returned : fatal: unable to access 'https://github.com/SiCKRAGETV/SickRage.git/': GnuTLS recv error (-9): A TLS packet with unexpected length was received.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@papampi Do you get this error every time you try to check for an update.? Or was this a one time error.?

**Comment by papampi** [comment]
Not every time but every now and then it comes up
