### ISSUE TITLE
[APP SUBMITTED]: SHOWQUEUE-REFRESH :: No episode number found in /volume1/videos/Serien-EN/The Mentalist/Season 02/The.Mentalist-s02e21-18-5-4.avi, ignoring it

### ISSUE THREAD

**Issue by andrelung** [SiCKRAGETV/sickrage-issues#1727]
### INFO
Python Version: **2.7.9 (default, Mar 23 2015, 00:28:06) [GCC 4.6.4 20130405 (prerelease)]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@92bf581ba8a7d4f2f912db795ce571b6ad38c3c2
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-REFRESH :: No episode number found in /volume1/videos/Serien-EN/The Mentalist/Season 02/The.Mentalist-s02e21-18-5-4.avi, ignoring it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Looks like SR has problems recognizing the episode number for s02e21-18-5-4. 
You can try to remove the -18-5-4 and see if that solves it.
Should be a one time error.
