### ISSUE TITLE
Post Processing "Module object has no attribute Session"

### ISSUE THREAD

**Issue by ulrick65** [SiCKRAGETV/sickrage-issues#1731]
Branch - Master
Commit hash - (e39fae0502b0993fd0163ea2f6888871426465be) 
Operating system - Synology DSM
Python Version - 2.7.9-13

Updated SR about 3 days ago was the only change. Ever since this update autoProcess in SABNZBD has failed with "AttributeError: 'module' object has no attribute 'Session'".  It worked fine on a download that finished an hour or so before I upgraded to the latest commits 3 days ago...but fails everytime since.

I updated again today the latest commits to see if that would help, but still fails.

Everything works fine with the download, SR snatches, passes to SAB, SAB downloads, but then when the post processing happens on the TV episode (I use the standard "sabToSickBeard.py" script, no modifications) I get this error in the post processing script window:

Loading config from /volume1/@appstore/sickbeard-custom/var/SickBeard/autoProcessTV/autoProcessTV.cfg
Opening URL: http://localhost:8083/home/postprocess/processEpisode Traceback (most recent call last):
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/autoProcessTV/sabToSickBeard.py", line 29, in <module> autoProcessTV.processEpisode(sys.argv[1], sys.argv[2], sys.argv[7])
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/autoProcessTV/autoProcessTV.py", line 128, in processEpisode sess = requests.Session() 
AttributeError: 'module' object has no attribute 'Session'

The file is intact and looks find in the download folder....however, the file remains in the download folder and is not copied to its proper location. Any ideas what might be causing this? Was there something done in the last update that would have effected this? Everything was working perfectly until SR was updated about 3 days ago.

The SR log does not show anything about the post processing, it shows the file being passed to SAB, but then nothing after that and the episode never changes from "snatched" of course.

Here's my log

https://gist.github.com/14bdcb65fe1697bd2057.git

Any help would be much appreciated.

Thanks.

**Comment by andyj682** [comment]
Same thing's happening to me; also started this week. (See issue 1730.)

**Comment by sarsipius** [comment]
Same issue with me

**Comment by neoatomic** [comment]
@ulrick65 @sarsipius Please add your posts to https://github.com/SiCKRAGETV/sickrage-issues/issues/1730 so we have all in one central place.
