### ISSUE TITLE
[APP SUBMITTED]: 401 Client Error: Unauthorized

### ISSUE THREAD

**Issue by johnscrub** [SiCKRAGETV/sickrage-issues#1732]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@e39fae0502b0993fd0163ea2f6888871426465be
No Log available with ERRORS: 
### ERROR
```
Thread-143 :: Trakt: Unable to delete show: Ever After High. Error: error 401 Client Error: Unauthorized
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Thraxis** [comment]
Check your Trakt Notification settings as Trakt PIN authentication was introduced recently and you will need to re-authenticate with Trakt.

**Comment by johnscrub** [comment]
Yhanks!!!Date: Sun, 31 May 2015 18:10:25 -0700
