### ISSUE TITLE
BUG : Error while searching Sick Beard Index, skipping: charmap

### ISSUE THREAD

**Issue by tchirou** [SiCKRAGETV/sickrage-issues#1734]
Hello

SR Version:	BRANCH: (master) / COMMIT: (42b8d5a9c71c87fcde301967b6254ef08c3093ac) 
Python 2.7.6 : Win 8.1
SR Locale:	('fr_FR', 'cp1252')

I have 3 animes in the anime section : one piece, naruto and fairy tail, configured with anidb
I have each time errors when the backlog is running 

2015-06-01 09:32:49 SEARCHQUEUE-BACKLOG-114801 :: [Sick Beard Index] :: Error while searching Sick Beard Index, skipping: charmap :  60 : error 0 : error 8 : character maps to <undefined>
2015-06-01 09:32:48 SEARCHQUEUE-BACKLOG-114801 :: [Usenet-Crawler] :: Error while searching Usenet-Crawler, skipping: charmap :  60 : error 0 : error 8 : character maps to <undefined>

I remove the japanese characters from the exception list but each update writes them back and the erros come back.

My computer language is french.

Do you have an idea ?

Thanks

**Comment by neoatomic** [comment]
@tchirou So in short you get this error because of the Japanese characters in the exception list and they get overwritten with every update.?

@miigotu Are we also using an exception list specially for anidb.? Do we need to fork that also, so we can remove those Japanese character entry's?

**Comment by tchirou** [comment]
@neoatomic 

Yes. There is no snatch because of the error. So I proceed to remove the japanese characters from the exception list and then I can manually snatch without problem.
But the week after, I have the error again because the japanese characters come back with an update I suppose.

**Comment by miigotu** [comment]
@tchirou where is the exception list?

**Comment by miigotu** [comment]
@neoatomic Most likely we have a `.encode('utf-8')` somewhere, which breaks some languages.

**Comment by tchirou** [comment]
When you edit a show



Le 1 juin 2015 à 23:30, Dustyn Gibson <notifications@github.com> a écrit :

@tchirou <https://github.com/tchirou> where is the exception list?

—
Reply to this email directly or view it on GitHub
<https://github.com/SiCKRAGETV/sickrage-issues/issues/1734#issuecomment-107718129>
.

**Comment by tchirou** [comment]
Hello Everyone

Any sign of finding the culprit :) ?

Thanks

**Comment by miigotu** [comment]
@tchirou In the mean time, have you tried deleting cache.db? that is where exceptions are stored. Maybe they wont come back then?

**Comment by tchirou** [comment]
Nope but I am going to
I will let you know
Thanks

**Comment by tchirou** [comment]
Hello
I delete it but jamanese characters kepp coming back each time.
Any news on your side ?
Thanks

**Comment by neoatomic** [comment]
For what show, and what indexer (tvdb or tvrage) are you using.?

**Comment by tchirou** [comment]
One piece
Naruto shipuuden
Fairy tail

All tvdb but all anime so anidb too



Le 17 juin 2015 à 12:32, neoatomic <notifications@github.com> a écrit :

For what show, and what indexer (tvdb or tvrage) are you using.?

—
Reply to this email directly or view it on GitHub
<https://github.com/SiCKRAGETV/sickrage-issues/issues/1734#issuecomment-112748845>
.

**Comment by neoatomic** [comment]
Looking through the Scene exception list i cant find any of those shows. So those scene names must be added by the indexer anidb. http://anidb.net/perl-bin/animedb.pl?show=anime&aid=69
And indeed If you select "title" than some alternative names contain Japanese characters.

@miigotu Is it technical possible to block scene name updates from animedb.? Currently i don't see any other possibility's to fix this...
