### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-MANUAL-270693 :: uTorrent: Authentication Failed

### ISSUE THREAD

**Issue by amzeus** [SiCKRAGETV/sickrage-issues#1735]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/488277f678b816d3aa7e
### ERROR
```
SEARCHQUEUE-MANUAL-270693 :: uTorrent: Authentication Failed
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@amzeus Check you login/password/firewall for uTorrent.

**Comment by rh724** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@30435190ef8880901df555bcda0d46902ea81fb5
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-281622 :: [KickAssTorrents] :: uTorrent: Authentication Failed
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rh724** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@30435190ef8880901df555bcda0d46902ea81fb5
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-281622 :: [KickAssTorrents] :: uTorrent: Authentication Failed
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rh724** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@30435190ef8880901df555bcda0d46902ea81fb5
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-295647 :: [KickAssTorrents] :: uTorrent: Authentication Failed
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rh724** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@30435190ef8880901df555bcda0d46902ea81fb5
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-80117 :: [KickAssTorrents] :: uTorrent: Authentication Failed
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rh724** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@30435190ef8880901df555bcda0d46902ea81fb5
Link to Log: https://gist.github.com/34d2aa7212b2867be85f
### ERROR
```
SEARCHQUEUE-BACKLOG-80117 :: [KickAssTorrents] :: uTorrent: Authentication Failed
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rh724** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@30435190ef8880901df555bcda0d46902ea81fb5
Link to Log: https://gist.github.com/26b5bafc54983115b981
### ERROR
```
SEARCHQUEUE-MANUAL-80117 :: [KickAssTorrents] :: uTorrent: Authentication Failed
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rh724** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@136f531f93093a5287b588ca37e19c11153f47a4
Link to Log: https://gist.github.com/4f256f4c89aeb2a35814
### ERROR
```
SEARCHQUEUE-MANUAL-279201 :: [KickAssTorrents] :: uTorrent: Authentication Failed
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by alternativesurfer** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
Link to Log: https://gist.github.com/76c08f5f443d429ccc5f
### ERROR
```
SEARCHQUEUE-MANUAL-255316 :: [KickAssTorrents] :: uTorrent: Authentication Failed
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by alternativesurfer** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-MANUAL-255316 :: [KickAssTorrents] :: uTorrent: Authentication Failed
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
