### ISSUE TITLE
SickRage downloading the wrong torrent?

### ISSUE THREAD

**Issue by jyggen** [SiCKRAGETV/sickrage-issues#1736]
**Branch:** Master
**Commit:** https://github.com/SiCKRAGETV/SickRage/commit/e39fae0502b0993fd0163ea2f6888871426465be
**Operating System:** Linux 3.10.35 (Synology DS415+ running DSM 5.2-5565 Update 1)
**Python Version:** 2.7.9 (default, Apr 22 2015, 03:25:20) [GCC 4.6.3]

**What you did:**
Changed episode status of a season from `Skipped` to `Wanted`, and later from `Snatched` to `Wanted`.

**What happened:**
It seems like SickRage is downloading/sending the wrong torrent to Transmission even though the log says it's downloading another one (the one I'd prefer).

Two lines from the log highlighting the issue:

```
2015-06-01 11:31:13 INFO     SEARCHQUEUE-BACKLOG-269641 :: Downloading Chicago.PD.S01.720p.HDTV.X264-SCC from SceneAccess
2015-06-01 11:31:13 DEBUG    SEARCHQUEUE-BACKLOG-269641 :: Transmission: Response to POST request is {"arguments":{"torrent-added":{"hashString":"130669055ab65f0d624cbd2fa48d8770ecdd1a6a","id":235,"name":"Chicago.PD.S01.NTSC.DVDR-SCC"}},"result":"success"}
```

Worth noting is that it previously did the same thing but downloaded `Chicago.PD.S01.MULTISUBS.PAL.DVDR-SCC` instead. I changed the entire season back to Wanted and this time it downloaded `Chicago.PD.S01.NTSC.DVDR-SCC` instead (this search is what the log's from).

**What you expected:**
I expected `Chicago.PD.S01.720p.HDTV.X264-SCC` to show up in Transmission, but instead it started to download a DVDR release (despite me having DVDR, PAL and NTSC as ignored words, but that's another issue I guess).

**Full log:**
https://gist.github.com/jyggen/bb040c3e025a211d3cf4

**Comment by neoatomic** [comment]
@jyggen There seems to be a problem with BTN downloading wrong torrents, https://github.com/SiCKRAGETV/sickrage-issues/issues/1579 but in you are using SceneAccess correct.?

**Comment by jyggen** [comment]
@neoatomic In this case, yes I am.

**Comment by neoatomic** [comment]
@jyggen Do you have an invite for SceneAccess.? The Developers need to have an account so they can troubleshoot.

**Comment by jyggen** [comment]
I don't, sorry.

**Comment by miigotu** [comment]
@neoatomic @jyggen I have sceneaccess, was trying to keep a good ratio there but I'll do some poking around.

**Comment by Ockingshay** [comment]
good to see this is more widespread than btw and habits...in the sense that it improves the likelihood of this getting fixed. Any news miigotu?

**Comment by miigotu** [comment]
@jyggen For now, try using black hole method. From other reports this issue only happens when using a torrent client api.

Let me know if this also fixes it for you.

**Comment by miigotu** [comment]
I am going to close this, all further discovery will be posted in #1579
