### ISSUE TITLE
[Regression] autoProcessTV no longer working

### ISSUE THREAD

**Issue by surrealroad** [SiCKRAGETV/sickrage-issues#1739]
SR Version:	BRANCH: (master) / COMMIT: (42b8d5a9c71c87fcde301967b6254ef08c3093ac) 
SR User:	sickbeard-custom
SR Locale:	('en_US', 'UTF-8')

For the past 3 days (so the version above, and the previous master release), I've been getting `Exit(1) AttributeError: ’module’ object has no attribute ’Session’` on every episode of everything downloaded.

What you did:
Allowed SABnzbd 0.7.0 to forward downloads to SickRage to process them
What happened
Stack trace:
```
           Loading config from /usr/local/sickbeard-custom/var/SickBeard/autoProcessTV/autoProcessTV.cfg

Opening URL: http://localhost:8081/home/postprocess/processEpisode
Traceback (most recent call last):
  File "/usr/local/sickbeard-custom/var/SickBeard/autoProcessTV/sabToSickBeard.py", line 29, in <module>
    autoProcessTV.processEpisode(sys.argv[1], sys.argv[2], sys.argv[7])
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/autoProcessTV/autoProcessTV.py", line 128, in processEpisode
AttributeError: 'module' object has no attribute 'Session'
```
What you expected
TV show processed normally.

**Comment by neoatomic** [comment]
@yongbi85 Backup and Install the new Sickrage package from Synocommunity. See https://github.com/SiCKRAGETV/sickrage-issues/issues/1730 for more info.
