### ISSUE TITLE
[Feature Request] Add notice to GUI about cross-mount hard links

### ISSUE THREAD

**Issue by thisischrys** [SiCKRAGETV/sickrage-issues#1740]
SR Version:	BRANCH: (master) / COMMIT: (42b8d5a9c71c87fcde301967b6254ef08c3093ac) 
```
2015-06-02 11:42:03 Thread-113 :: Failed to create hardlink of /home/chris/Downloads/Complete/sickrage/Sons.of.Anarchy.S06E02.1080p.WEB-DL.DD5.1.H264-FX3 [PublicHD]/Sons.of.Anarchy.S06E02.1080p.WEB-DL.DD5.1.H264-FX3.mkv at /home/chris/Videos/Shows/Sons of Anarchy/Season 06/Sons of Anarchy - S06E02 - One One Six.mkv: error 1 : Operation not permitted. Copying instead
```
config file: http://pastebin.com/tScMzdVu
did a sudo su sickrage and that user can ln the files just fine from a terminal

**Comment by neoatomic** [comment]
@thisischrys The error clearly states : "Operation not permitted"
So check your file and account permissions.

**Comment by miigotu** [comment]
Maybe you are trying to create hard links from one hard drive or partition to a different one? Hard links only work within the same filesystem partition.

**Comment by fernandog** [comment]
We should add parent folder AND partition check for download dir and dest dir

**Comment by miigotu** [comment]
@fernandog yes, I had looked into this before, and found a python function that determines mount from a path we can use for this to compare that source and destination are on the same partition.

**Comment by miigotu** [comment]
@fernandog 
I found some complicated ways of doing this online, but I think this would work, it works on linux. (Rather do things my own way than copy pasta)
```
def permitHardLink(source, destination):
    for location in source, destination:
        if not os.path.exists(location):
            logger.log(u'Cannot hard link because the path does not exist: %s' % location, logger.DEBUG)
            return False

    if os.stat(source).st_dev == os.stat(destination).st_dev:
        return True

    logger.log(u'Cannot hard link because the paths are not on the same partition: %s and %s' % (source, destination), logger.DEBUG)
    return False
```
I didnt look at our code yet, looking into stdlib docs.

**Comment by fernandog** [comment]
@miigotu no problem.

we also need to check if dest dir is a parent of the download(PP) dir. It maybe cause PP issues. PP folder and dest folder shouldn't be parent. 

My ideia was to do the save behavior as the renaming (paint the field with red and don't allow to save the setting). What do you think?

**Comment by miigotu** [comment]
@fernandog I think its the other way around isn't it? Destination cannot be inside the PP folder, or it will try to process it again the next time.

**Comment by fernandog** [comment]
@miigotu sorry, yes!

**Comment by miigotu** [comment]
@thisischrys It would be helpful if you can respond to our comments. I am planning on working on this change next and want to make sure it solves your issue.

**Comment by thisischrys** [comment]
The problem was indeed that they were mounted on different locations. I've solved it by migrating my filesystem to btrfs.

**Comment by miigotu** [comment]
Cool, I still need to add a notice in the gui about cross-mount hard links and a check xD.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
