### ISSUE TITLE
[Feature Request] Add pause function for rTorrent 

### ISSUE THREAD

**Issue by jantjo** [SiCKRAGETV/sickrage-issues#1742]
when looking through the config.ini there is a flag that looks to add a .torrent to rtorrent in a paused state which is not available via the GUI.

config.ini
[TORRENT] 
torrent_paused = 1

When changing the flag from 0 to 1 the expected result would that it ads the torrent in a paused state which it doesn't. further look into rtorrent.py it doesn't look to be fully implemented.

**Comment by neoatomic** [comment]
@jantjo Feel free to make a PR and submit the changes.

**Comment by jantjo** [comment]
Im not really a dev so don't know the first thing about adding the code

**Comment by WebSpider** [comment]
I did a quick hack on https://github.com/WebSpider/SickRage/tree/dev-torrent_paused-for-rtorrent ... let me know if this works. as I do not have rTorrent set up currently, I cannot properly test it.

**Comment by jantjo** [comment]
I did look around but didn't see where to make the change... or is it just as stated above in the .ini files (so no gui at this point)?

**Comment by WebSpider** [comment]
Just add a torrent with the 'start torrents paused' option

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
