### ISSUE TITLE
[APP SUBMITTED]: 'link'

### ISSUE THREAD

**Issue by EirikUtvik** [SiCKRAGETV/sickrage-issues#1743]
### INFO
Python Version: **2.7.3 (default, Nov  5 2014, 11:18:35) [GCC 4.6.3]**
Operating System: **Linux-3.4.26-i686-with-glibc2.0**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@e39fae0502b0993fd0163ea2f6888871426465be
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-161511 :: [KickAssTorrents] :: Failed to parsing KickAssTorrents Traceback: Traceback (most recent call last):
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/sickbeard/providers/kat.py", line 238, in _doSearch
    link = item['link']
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/lib/feedparser/feedparser.py", line 353, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'link'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@EirikUtvik no one else reported this. are you still having this issue?

**Comment by pct00** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@347571fb55710163fe5958761bcc450045c4c3a5
Link to Log: https://gist.github.com/f713c0e039b489887216
### ERROR
```
SEARCHQUEUE-BACKLOG-79511 :: Failed to parsing KickAssTorrents Traceback: Traceback (most recent call last):
  File "C:\Users\Pedro\Desktop\SickRage-master\sickbeard\providers\kat.py", line 238, in _doSearch
    link = item['link']
  File "C:\Users\Pedro\Desktop\SickRage-master\lib\feedparser\feedparser.py", line 353, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'link'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@miigotu kat too (link key)

**Comment by miigotu** [comment]
got it, just don't know when this error can happen, unless it is on 0 results.
