### ISSUE TITLE
[APP SUBMITTED]: Thread-70 :: No Show Object found for show with indexerID: 81164

### ISSUE THREAD

**Issue by cgram23** [SiCKRAGETV/sickrage-issues#1744]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-38-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@42b8d5a9c71c87fcde301967b6254ef08c3093ac
No Log available with ERRORS: 
### ERROR
```
Thread-70 :: No Show Object found for show with indexerID: 81164
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@cgram23 Please provide logs. And what show is this? and on what indexer.?
