### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/var/opt/sickbeard/cache/indexers/theTVDB/92bf3d4a4d02979b3e19ee6cd7cdf8f25ce31d1257ce560b6b4e48b8'

### ISSUE THREAD

**Issue by Symbiot78** [SiCKRAGETV/sickrage-issues#1745]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.16.0-0.bpo.4-amd64-x86_64-with-debian-7.8**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@e39fae0502b0993fd0163ea2f6888871426465be
Link to Log: https://gist.github.com/6a60886563842d5cbb97
### ERROR
```
Thread-52 :: Zip creation error: [Errno 2] No such file or directory: '/var/opt/sickbeard/cache/indexers/theTVDB/92bf3d4a4d02979b3e19ee6cd7cdf8f25ce31d1257ce560b6b4e48b8'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Do a reboot. If you still get the error delete the cache folder.
