### ISSUE TITLE
Postprocessing of TV shows in sabnzbd fails using SickRage's sabToSickBeard script

### ISSUE THREAD

**Issue by baschinger** [SiCKRAGETV/sickrage-issues#1746]
Postprocessing of TV shows in sabnzbd fails with the following error:

Loading config from /usr/local/sickbeard-custom/var/SickBeard/autoProcessTV/autoProcessTV.cfg
Opening URL: http://localhost:8083/home/postprocess/processEpisode
Traceback (most recent call last):
  File "/usr/local/sickbeard-custom/var/SickBeard/autoProcessTV/sabToSickBeard.py", line 29, in <module>
    autoProcessTV.processEpisode(sys.argv[1], sys.argv[2], sys.argv[7])
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/autoProcessTV/autoProcessTV.py", line 128, in processEpisode
<code>
    sess = requests.Session()
</code>
AttributeError: 'module' object has no attribute 'Session'

**Comment by baschinger** [comment]
I'm running SickRage on a Synology NAS with python 2.7.9-13 provided by SynoCommunity

**Comment by neoatomic** [comment]
Backup and Install the new SickRage package on SynoCommunity.
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1730 for more info.

**Comment by baschinger** [comment]
Thanks and sorry for the redundant issue.
Worked like a charm!
