### ISSUE TITLE
When edit show language to a different from the default it goes back to default

### ISSUE THREAD

**Issue by BuSHari** [SiCKRAGETV/sickrage-issues#1747]
Hello,

My Default Indexer Language is set to English, but i have some shows that are in Hebrew, 
So when i change the Show to Hebrew the show is changed to Hebrew but when i get into the Edit page for that show again i see the Info Language is set back to Default language English.

So what i'm asking to be fixed, that when i'm changing a language of a specific show i want it to stay permanently in my chosen language and not my default language.

There is another issue that looks the same, but its not. https://github.com/SiCKRAGETV/sickrage-issues/issues/1217

Thanks for all the help

See attached photos

Default Indexer Language - English
![image](https://cloud.githubusercontent.com/assets/1271474/7955595/37079946-09e2-11e5-889d-17c3199d39ef.png)

I`m setting to Hebrew
![image](https://cloud.githubusercontent.com/assets/1271474/7955628/7d7df582-09e2-11e5-92c9-7231fa5e4b17.png)

Going back to the Edit page is revert back to English
![image](https://cloud.githubusercontent.com/assets/1271474/7955653/b9b4a212-09e2-11e5-93c4-c5d0742c5a7c.png)

Thanks,
Idan

**Comment by neoatomic** [comment]
@BuSHari This should indeed be fixed some time ago.
Could you do some tests to see if this is only for Hebrew or that it is also not working for other languages.?
And please fill in the remaining info that we need. https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket

@abeloin Any idea why is still falls back to English.?

**Comment by BuSHari** [comment]
Yes this is happening in other languages as well.

Here is my Info:
BRANCH: (master)
COMMIT: (42b8d5a9c71c87fcde301967b6254ef08c3093ac)
OS: Synology DSM 5.2
Python Version: 2.7.9

**Comment by fernandog** [comment]
there's no custom show language setting AFAIK (can't see that in the database - tv_shows table)
it will only get the indexer default language

@miigotu probaly we should remove this setting from editshow too

**Comment by miigotu** [comment]
This is one that needs fixed instead of removed. We need to check what the drop down is really supposed to do.

**Comment by fernandog** [comment]
There isnt a column in DB for custom setting per show. Not a fix but a FR

**Comment by fernandog** [comment]
Like KODI you set the default indexer language for all shows/movies

**Comment by miigotu** [comment]
Yes then comment it from the template, until we can add it another time.

**Comment by fernandog** [comment]
@miigotu my mistake. sorry. there is a column named LANG. All of mine shows are set as 'en'

**Comment by miigotu** [comment]
This is just a template problem. It does save. When you change the language and click save/submit the show is refreshed and the titles and info changes to the new language.

**Comment by miigotu** [comment]
@BuSHari this is because of the same issue as #1217 but SiCKRAGETV/SickRage/pull/1756 improperly fixed it.

We will look into it.

**Comment by miigotu** [comment]
Fixed in SiCKRAGETV/SickRage#1976
