### ISSUE TITLE
[APP SUBMITTED]: [Errno 1] Operation not permitted: '/mnt/usb1/shares/media/TV/Orphan Black/Season.03/Orphan.Black.S03E01.The.Weight.of.This.Combination.HDTV.mkv'

### ISSUE THREAD

**Issue by mulletman** [SiCKRAGETV/sickrage-issues#1748]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.11-v7+-armv7l-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@42b8d5a9c71c87fcde301967b6254ef08c3093ac
Link to Log: https://gist.github.com/e734bc84074f75ecb43b
### ERROR
```
POSTPROCESSER :: File air date stamping failed. The error is: 1 and the message is: Operation not permitted.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@mulletman  Check the permissions.
It that doesn't work : Go to Settings -> Post-Processing, and disable the option called "Change File Date"
