### ISSUE TITLE
[APP SUBMITTED]: SHOWQUEUE-REFRESH :: No episode number found in /volume1/TV Shows/Weeds/Season 4/04 04 04 04 weeds.404.hdtv-0tv.mp4, ignoring it

### ISSUE THREAD

**Issue by erickgrau** [SiCKRAGETV/sickrage-issues#1752]
### INFO
Python Version: **2.7.9 (default, Mar 23 2015, 00:07:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@42b8d5a9c71c87fcde301967b6254ef08c3093ac
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-REFRESH :: No episode number found in /volume1/TV Shows/Weeds/Season 4/04 04 04 04 weeds.404.hdtv-0tv.mp4, ignoring it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Poor naming of the file.
