### ISSUE TITLE
add existing shows fails -- the connection was reset

### ISSUE THREAD

**Issue by vbab** [SiCKRAGETV/sickrage-issues#1753]
when i try to add new shows it always fails if i try to add all shows.   i can get it to work if i do few hundred at a time.  with 14k shows that takes a long time to add checking 200 boxes at a time

I cannot see any timeout listed in the ini that might affect this.  Strange is that it works fine on sickbeard.

I have tried it on your program on ubuntu and mint  both linux give same problem  No errors show in the log even with debug on in ini        

When i mouse over the browser address bar  after it fails there is very long list of shows it looks like its trying to add all 14k shows to the browser line at same time.

i looked at the code   addExistingShow.js         but its just gibberish to me with no comments I am lost.
I hope someone can figure why asap   its a pain submiting shows 100 at a time.

**Comment by neoatomic** [comment]
Please explain better as i have no idea what you mean. 14k shows and 200 boxes.? 
Also follow the rules for opening an issue. https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket

**Comment by vbab** [comment]
i had to reinstall  when i do add existing shows it fails....
If i uncheck all the shows  then   only check 200 at a time  i can add them without problem.
no errors show up  even with debug on that i can see.   

there is something differnt between your code and sick beard i can add them all on sickbeard.
can i use the database from sickbeard on sick rage   if so  i can just add them on sickbeard snd move the database to sickrage then?

**Comment by vbab** [comment]
I tried to test it on my windows machine by mapping the linux drive to a drive in windows  but when i did add shows it did not see any shows on the mapped drive. 
next i tried setting the permissions on the linux box to 777   still did not work.     When i browse for folder i can see the shows  but when i get to were the submit button is active no shows ever appear on the list.   I am guessing this needs to be posted as a new issue.    I doubt people will be running this on a share anyway.        here is the error that did show up it may be a clue.


2015-06-04 14:29:07 Thread-40 :: Failed doing webui callback: Traceback (most recent call last):
  File "c:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "c:\SickRage\sickbeard\webserve.py", line 2316, in massAddTable
    return t.respond()
  File "c:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_home_massAddTable_tmpl.py", line 99, in respond
    show_id = VFSL([locals()]+SL+[globals(), builtin],"show_id",True) + '|' + VFSL([locals()]+SL+[globals(), builtin],"str",False)(VFSL([locals()]+SL+[globals(), builtin],"curDir",True)['existing_info'][0]) + '|' + VFSL([locals()]+SL+[globals(), builtin],"str",False)(VFSL([locals()]+SL+[globals(), builtin],"curDir",True)['existing_info'][1])
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u03c7' in position 3: character maps to <undefined>

**Comment by vbab** [comment]
on the linux box some errors do show  but they are errors in nfo and metadata. I used MediaCenterMaster to create my metadata and nfo.  they work with kodi and sickrage but i get errors on our program.
some errors are from parsing nfo
not well-formed (invalid token): line 22 column 12    <studio>A&E<studio>     12 seems to be 2nd <
invalid literal for int() with base 10: ' '
invalid literal for int() with base 10: "tt1234567"

**Comment by vbab** [comment]
sorry i am getting so many errors i don't know if they are related or if i need to create a case for each one.

**Comment by vbab** [comment]
ROBOCOPY C:\Source C:\Destination *.nfo *.xml /E  
I created a test folder with just directory structure and nfo and xml in it that gets lots of errors on sickrage.  the file is only 17k rar  I can send it if it will help..

**Comment by vbab** [comment]
oh  there is a add show    and also a add existing shows.    add existing shows has boxes next to each show.

**Comment by vbab** [comment]
Can you delete this thread I found flaws in my file system and naming when I get it all fixed i will post what the errors were.
