### ISSUE TITLE
[APP SUBMITTED]: POSTPROCESSER :: Failed to detect KODI version for '192.168.1.13', check configuration and try again.

### ISSUE THREAD

**Issue by str8lazy** [SiCKRAGETV/sickrage-issues#1754]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@42b8d5a9c71c87fcde301967b6254ef08c3093ac
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Failed to detect KODI version for '192.168.1.13', check configuration and try again.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
As the message says check your configuration settings.

**Comment by str8lazy** [comment]
Seems like there is something wrong with the submit button too....

Was sending the entirety of errors. The important ones being the lack of
access to update aired dated and the search error for omgwtfnzbs
