### ISSUE TITLE
No JSON object could be decoded (proxy setting)

### ISSUE THREAD

**Issue by mbnoimi** [SiCKRAGETV/sickrage-issues#1759]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-18-generic-x86_64-with-LinuxMint-17.1-rebecca**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@42b8d5a9c71c87fcde301967b6254ef08c3093ac
Link to Log: https://gist.github.com/f9a5a9febcf3a7b7f0f5
### ERROR
```
SEARCHQUEUE-BACKLOG-254243 :: [Rarbg] :: Rarbg json load failed.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by mbnoimi** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-18-generic-x86_64-with-LinuxMint-17.1-rebecca**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@42b8d5a9c71c87fcde301967b6254ef08c3093ac
Link to Log: https://gist.github.com/b932137d7ebade939df0
### ERROR
```
SEARCHQUEUE-BACKLOG-254243 :: [Rarbg] :: Rarbg json load failed.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by mbnoimi** [comment]
Same old story. I've problem with proxies. Most search providers reject TOR proxy so I used the embeded proxy list of SR but unfortunately it didn't work.

Any suggestions guys? In Turkey most torrent website are forbidden by court of law

**Comment by mbnoimi** [comment]
After setting embedded proxy config SR unable to fetch any new content.

**Comment by miigotu** [comment]
Please search before posting an issue. This is a known problem.
