### ISSUE TITLE
Parsing of release groups for expample DIMENSION[rarbg]

### ISSUE THREAD

**Issue by Rouzax** [SiCKRAGETV/sickrage-issues#1761]
In releases were they add for instance [rarbg] to the provider this causes SickRage to add that as a valid release group.
![image](https://cloud.githubusercontent.com/assets/4103090/8000390/4ae70856-0b5a-11e5-9095-2758d894f719.png)

Config
SR Version:	BRANCH: (master) / COMMIT: (42b8d5a9c71c87fcde301967b6254ef08c3093ac)
SR User:	Download
SR Locale:	('nl_NL', 'cp1252')
SR Config file:	C:\Program Files (x86)\SickRage\config.ini
SR Database file:	C:\Program Files (x86)\SickRage\sickbeard.db
SR Cache Dir:	C:\Program Files (x86)\SickRage\cache
SR Log Dir:	C:\Program Files (x86)\SickRage\Logs
SR Arguments:	['--nolaunch']
Python Version:	2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]

Log
http://pastebin.com/sWeJnwFm

The issue was solved but i still get it.
https://github.com/SiCKRAGETV/sickrage-issues/issues/1071

**Comment by miigotu** [comment]
On snatch it doesn't show release group under provider, it shows the site that provided it. On download, it will show the release group and release site. The previous fix that removed the [....] from the provider line will be reverted soon, as it breaks required/ignored words functionality.

**Comment by Rouzax** [comment]
Thanks, I did not know that.

**Comment by miigotu** [comment]
@Rouzax Maybe afterwards we can provide a better fix which works for all providers and does not break req/ign words. Atm, we cannot require ettv/rarbg/etc in the torrent name.

**Comment by Rouzax** [comment]
:+1:  no problem it is not the end of the world :smile:
