### ISSUE TITLE
SickRage not finding new "Strike Back" episodes

### ISSUE THREAD

**Issue by aerickson** [SiCKRAGETV/sickrage-issues#1762]
Particularly the season 5 shows.

branch: master
commit: 42b8d5a9c71c87fcde301967b6254ef08c3093ac
os: OS X 10.10.3
python:
  Python 2.7.8 (default, Oct 16 2014, 05:18:45) 
  [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.51)] on darwin
what I did: added show "Strike Back", searched for Season 5, Ep 1
what happened: SickRage failed to find episode. I searched on nzbs.org and found the episode.
what I expected: SickRage would download show
debug output:
  https://gist.github.com/aerickson/4152709e91298ca07dcb

tvdb link for show:
  http://thetvdb.com/?tab=season&seriesid=148581&seasonid=621186&lid=7

**Comment by Thraxis** [comment]
You may have to add "Strike Back Legacy" to the scene exceptions for that series

**Comment by miigotu** [comment]
If the exception works, let us know so we can add it to the default exceptions list.

**Comment by JesCR** [comment]
the exception works!

**Comment by miigotu** [comment]
https://github.com/SiCKRAGETV/sb_tvdb_scene_exceptions/commit/2914ac72c717849731ea94555ee3bb4a12be9051
