### ISSUE TITLE
Unable to connect to TorrentDay provider: See: http://git.io/vJrkM

### ISSUE THREAD

**Issue by thechengster** [SiCKRAGETV/sickrage-issues#1764]
I've tried to follow the instructions at http://git.io/vJrkM, but I still get the error. Here are my logs:

2015-06-05 17:24:04 INFO     SEARCHQUEUE-MANUAL-277165 :: Unable to find a download for: [Silicon Valley - 2x08 - White Hat-Black Hat]
AASSLError: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
AA    raise SSLError(e, request=request)
AA  File "/home/kai/.sickrage/lib/requests/adapters.py", line 431, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/home/kai/.sickrage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/home/kai/.sickrage/lib/requests/sessions.py", line 464, in request
AA    return self.request('POST', url, data=data, json=json, **kwargs)
AA  File "/home/kai/.sickrage/lib/requests/sessions.py", line 507, in post
AA    response = self.session.post(self.urls['login'], data=login_params, timeout=30, verify=False)
AA  File "/home/kai/.sickrage/sickbeard/providers/torrentday.py", line 100, in _doLogin
AATraceback (most recent call last):
2015-06-05 17:24:04 ERROR    SEARCHQUEUE-MANUAL-277165 :: [TorrentDay] :: Unable to connect to TorrentDay provider: See: http://git.io/vJrkM
2015-06-05 17:24:03 INFO     SEARCHQUEUE-MANUAL-277165 :: [TorrentDay] :: Performing episode search for Silicon Valley

**Comment by fernandog** [comment]
[TorrentDay] :: Unable to connect to TorrentDay provider: See: http://git.io/vJrkM
