### ISSUE TITLE
Windows SSL fixes

### ISSUE THREAD

**Issue by halcyonforever** [SiCKRAGETV/sickrage-issues#1766]
Are there any fixes for the ssl issues (Python PIP or openSSL) for windows?  everything I have found is for linux or the QNAP systems.

2015-06-05 21:00:00 SEARCHQUEUE-BACKLOG-85019 :: Unable to connect to ******** provider: See: http://git.io/vJrkM

AASSLError: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
AA    raise SSLError(e, request=request)
AA  File "C:\SickRage\lib\requests\adapters.py", line 431, in send
AA    r = adapter.send(request, **kwargs)
AA  File "C:\SickRage\lib\requests\sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "C:\SickRage\lib\requests\sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "C:\SickRage\lib\requests\sessions.py", line 476, in get
AA    response = self.session.get(self.urls['token'], timeout=30, verify=False, headers=self.headers)
AA  File "C:\SickRage\sickbeard\providers\rarbg.py", line 112, in _doLogin
AATraceback (most recent call last):

**Comment by neoatomic** [comment]
@halcyonforever Its indeed clearly a SSL error. 
Maybe this guide can help you setup SickRage correctly on Windows.
http://www.htpcguides.com/install-sickrage-windows-usenet-torrent-tv/

**Comment by halcyonforever** [comment]
thanks for the information.  Turns out the guide I followed did not include that step.  I did find however that if you install python 2.7.9 it has "The entirety of Python 3.4's ssl module has been backported for Python 2.7.9."
