### ISSUE TITLE
[APP SUBMITTED]: Series result returned zero

### ISSUE THREAD

**Issue by hulubi** [SiCKRAGETV/sickrage-issues#1769]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 10:19:51) [GCC 4.3.6]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@42b8d5a9c71c87fcde301967b6254ef08c3093ac
No Log available with ERRORS: 
### ERROR
```
Thread-88 :: Unable to connect to theTVDB while creating meta files - skipping - Series result returned zero
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Thetvdb intermittent connection issue
