### ISSUE TITLE
[APP SUBMITTED]: Thread-35 :: No Show Object found for show with indexerID: 35197

### ISSUE THREAD

**Issue by mikkelnl** [SiCKRAGETV/sickrage-issues#1774]
### INFO
Python Version: **2.7.3 (default, Mar 31 2015, 15:16:49) [GCC 4.9.2]**
Operating System: **Linux-3.18.10-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@42b8d5a9c71c87fcde301967b6254ef08c3093ac
Link to Log: https://gist.github.com/75a9363bc454611905bb
### ERROR
```
Thread-35 :: No Show Object found for show with indexerID: 35197
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
this show does not exist in the indexer
