### ISSUE TITLE
[APP SUBMITTED]: -1

### ISSUE THREAD

**Issue by MGaetan89** [SiCKRAGETV/sickrage-issues#1775]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:58:35) [GCC 4.6.4]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@42b8d5a9c71c87fcde301967b6254ef08c3093ac
Link to Log: https://gist.github.com/57caabc7edb919fbe897
### ERROR
```
TORNADO :: API :: error -1
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Sorry, Not enough info to troubleshoot the error....
(But my best guess is that the show was missing data from the indexer. Airdate etc.)
