### ISSUE TITLE
Show updater getting stuck

### ISSUE THREAD

**Issue by scythe000** [SiCKRAGETV/sickrage-issues#1778]
Hi guys, for the last 6 or so revisions at least, it looks like the show updates are getting stuck on Doctor Who. Sometimes after a restart, the shows before it will update, but it seems to keep getting stuck in the same spot.

Windows server 2012. Latest Dev branch (BRANCH: (develop) / COMMIT: (30152d845f630a744066c5b3c40914f98691883d) )
Python 2.7.9

https://paste.ee/p/2Q4Gp <--- logs

**Comment by scythe000** [comment]
Looking through the logs, it looks like its trying to parse a ton of garbage unrelated to my library.

**Comment by scythe000** [comment]
Anyone?

**Comment by scythe000** [comment]
I'm wondering if anyone else is having this issue @echel0n or @fernandog ?

**Comment by fernandog** [comment]
no issues here

check localhost:8081/home/status/ and check the show that is stucked in "Show Queue"

**Comment by scythe000** [comment]
It's Doctor Who. the show says:
The information on this page is in the process of being updated.

**Comment by fernandog** [comment]
@scythe000 maybe missing information in thetvdb

your log shows only "SEARCHQUEUE-DAILY-SEARCH". useless

**Comment by scythe000** [comment]
that log was after a restart. Want me to send over new logs?

**Comment by fernandog** [comment]
@scythe000 can you find out which season/episode it's stucking?

**Comment by fernandog** [comment]
@miigotu maybe we need to add some debug messages in show updater

**Comment by scythe000** [comment]
I looked through the logs, but couldn't tell. I'll look again.

**Comment by scythe000** [comment]
With log on db, here's exactly where it hangs:

`2015-06-17 10:08:32 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Loading all episodes from the DB
2015-06-17 10:08:32 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Loading all episodes from the database
2015-06-17 10:08:32 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 78804: Saving show info to database
2015-06-17 10:08:32 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 78804: Obtained info from IMDb ->{'rating': 8.9, 'votes': 124486, 'countries': u'UK', 'title': u'Doctor Who', 'genres': u'Adventure|Drama|Family|Mystery|Sci-Fi', 'imdb_id': u'tt0436992', 'country_codes': u'gb|ca', 'year': 2005, 'certificates': u'U', 'runtimes': u'45', 'akas': u'Doctor Who::Argentina (imdb display title), Spain (imdb display title)|\u0414\u043e\u043a\u0442\u043e\u0440 \u041a\u043e\u0439::Bulgaria (Bulgarian title)|\u0414\u043e\u043a\u0442\u043e\u0440 \u041a\u0442\u043e::Russia|Bac Si Vo Danh::Vietnam (imdb display title)|Doctor Who::Germany (imdb display title)|Doctor Who::Finland (imdb display title)|Doctor Who::France (imdb display title)|Doctor Who::Greece (imdb display title)|Doktor Hu::Serbia (imdb display title)|Doktor Who::Croatia (imdb display title)|Doktor Who::Poland (imdb display title)|Dokut\xe2 f\xfb::Japan (imdb display title)|Ki vagy, Doki?::Hungary (imdb display title)', 'last_update': 735766}
2015-06-17 10:08:15 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 78804: Loading show info from IMDb
2015-06-17 10:08:15 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Retrieving show info from IMDb
2015-06-17 10:08:14 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 78804: Loading show info from theTVDB
2015-06-17 10:08:14 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Retrieving show info from theTVDB
2015-06-17 10:08:14 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Beginning update of Doctor Who (2005)`

**Comment by miigotu** [comment]
How long have you let it sit and try to update the show info?

**Comment by scythe000** [comment]
days, if not longer.

**Comment by miigotu** [comment]
Tried removing the show from SR and adding it back?

**Comment by fernandog** [comment]
@miigotu I think it's some wrong or empty or missing information in thetvdb. there's tons of episodes.

**Comment by scythe000** [comment]
The only thing about removing and readding the show, is for that one in particular, there's a crap ton of info i'd need to reconfig. Especially for the hundreds of specials.

**Comment by Kumolo** [comment]
Hi,

I wasn't sure what's the best place to post, so it is now in the Forum _and_ here:

For some days (weeks?) My "Show Queue" gets stuck at 3 at night. All I can do is to restart SR. Please see attacged jpg for details. The show it stucks on varies, sometimes its is Simpsons, South Park or something different.

The log is quite interesting. Please note that the SHOWUPDATER takes exactly 0 seconds to complete:

>2015-06-17 03:00:13 INFO SHOWUPDATER :: Completed full update on all shows
>2015-06-17 03:00:13 INFO SHOWUPDATER :: Doing full update on all shows
2015-06-16 23:36:39 INFO SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2015-06-16 23:36:32 INFO SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
Full log says that no show is updated because: "Unable to update show: <UdoK: all shows> is in process of being updated by Post-processor or manually started, can't update again until it's done."

Would be happy to provide further info if needed. Log Snippet can be found here: http://pastebin.com/A7nTsm8F

and an Image how the status page looks is here: https://sickrage.tv/forums/filedata/fetch?photoid=24073

Thanks folks!

**Comment by scythe000** [comment]
@kumolo, Check your sickrage\cache\sessions folder and see if a lock file is in there while SR is stopped. if so, delete it.

**Comment by Kumolo** [comment]
Couldn't find any "*locked*" files. Neither when SR is running nor when it is stopped. I am running on Qnap and suppose this is the folder on my platform: 
>/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/cache/sessions

Looks like 
>0024eb3ca1359c0b26fe2e6e74e788268c5fdf1004e15de3e84ceea3  5ac59c0968ae168d77708e5d87c2ae497db534b6c0b58e6b019168d3  b213fb0b516c20d8a8d5922bd856807ab0c7cf931a4e5ba165c8865b

but nothing says lock or anything...

**Comment by fernandog** [comment]
stop SR, delete them, restart

**Comment by Kumolo** [comment]
Thanks. Have stopped SR and deleted all files inside 
>SickBeard-TVRage/config/cache/sessions

Have now changed "When to update shows" to 22 which is in 7 minutes at my time (Berlin, Germany).
Let's see what happens :-) Will report back.

**Comment by scythe000** [comment]
Do I have any options beyond deleting the show and losing all that config data I put in it?

**Comment by fernandog** [comment]
Need to think about it

**Comment by miigotu** [comment]
@scythe000 removing it from sickrage does not delete the files unless you tell it to. Also, if you have SR set to create some metadata it will add back very quickly.

**Comment by scythe000** [comment]
I understand that, I mean I have hundreds of entries, and have specific ones marked wanted/ignored/ etc.

**Comment by miigotu** [comment]
@scythe000 hundreds of entries for Dr Who 2005? xD there's like 100 episodes total for that show + specials.

Anyways, you could try deleting cache/rss/* cache/sessions/* cache/indexers/* and cache.db

**Comment by Kumolo** [comment]
Aater deleting my cache/sessions/*, Show Update went fine and this morning the Queue was empty :-) Many thanks for your help!

**Comment by miigotu** [comment]
@fernandog I think we need to find out why the cached sessions are not being removed automatically on startup like they are supposed to be.

**Comment by miigotu** [comment]
helpers.clearCache is run on boot and when the showUpdater is ran.

I think line 1427 of helpers.py is wrong, causing line 1429 to always be false.

**Comment by scythe000** [comment]
@miigotu thanks, that worked! I had only deleted the lock file before, so next time i'll know to delete all those other files. Thanks! it's been broken for weeks.

**Comment by miigotu** [comment]
Good to know @scythe000 
The function that is supposed to delete them is failing, without so much as a warning. I will fix it soonish.
