### ISSUE TITLE
API to know if there is an update available

### ISSUE THREAD

**Issue by MGaetan89** [SiCKRAGETV/sickrage-issues#1780]
It would be nice to have an API to know if an update is available for SickRage, and run the update.

I don't know how flexible that part is in SickRage, but the following information could be interesting to have:

- Current version
- Current Git hash
- Latest version
- Latest Git hash
- Number of commits between the current version and the latest version
- Changelog between the current version and the latest version

**Comment by fernandog** [comment]
@MGaetan89 just enable auto update

**Comment by MGaetan89** [comment]
I am working on an Android application for SickRage. So I can not change that setting for the user of my application nor force the user to enable auto update.

My goal was to provide as many features in my application as the web interface does.

**Comment by MGaetan89** [comment]
@fernandog That's a final no even considering my use case?

**Comment by fernandog** [comment]
Feel free to make a PR in develop

**Comment by MGaetan89** [comment]
I'll have to see how SR actually works, but I can try
