### ISSUE TITLE
Lektor type releases should be optional

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#1787]
Files with names like so ``Wayward Pines S01E01-E02 - Lektor PL - 720p.HDTV.XviD.AC3-H3Q[Pawulon]`` are dubbed over in another language than English, this one being polish as it's got ``PL`` after Lektor. I ended up with a few shows downloading incorrectly because of this.

**Comment by neoatomic** [comment]
You could add this to the ignore words for that specific show. That way SR will skip those results and not download. (If it is specific to this release group than just add "Pawulon" to the ignore words )

@fernandog As you tagged it as a feature request do you have another solution in mind.?

**Comment by fernandog** [comment]
No

**Comment by OmgImAlexis** [comment]
@fernandog can this be reopened?

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
