### ISSUE TITLE
Manual Post Processing using scene numbering

### ISSUE THREAD

**Issue by BenBeyond** [SiCKRAGETV/sickrage-issues#1788]
Trying to add Star Wars Rebels episodes manually.  Scene numbering differs from indexer (TVDB), and scene numbering is unchecked, but manual post processing will add the files based on scene numbering.  

Example: 
file is named Star.Wars.Rebels.S01E10.Vision.of.Hope.mkv
indexer says episode is S01E10
scene numbering says episode S01E10 is called Idiot's Array and is marked by the indexer as S01E09

Manual post processing will add the episode as S01E09 of the indexer numbering (S01E10 by scene numbering) and rename file to Star.Wars.Rebels.S01E09.Idiots.Array.mkv

This is especially frustrating because the last episode of the season is S01E13 by the indexer, but has no scene numbering, so SR doesn't know what to do with it...

**Comment by Thraxis** [comment]
It looks like thexem.de entry for Starwars Rebels is fairly messed up at the moment.  Does the scene releases fully match the TVDB and TVRAge releases?

**Comment by BenBeyond** [comment]
It is hard to tell since most of the scene releases do not include episode names, but I think they are following the scene numbering for most episodes.  The problem really comes in with the last episode, which doesn't have scene numbering so SR can't figure out where to put it or how to organize it.

**Comment by Thraxis** [comment]
I've submitted the changes to thexem.de for the show.  Hopefully it will get approved soon so you can fix things.

**Comment by BenBeyond** [comment]
Thanks for that, not sure why this show is so messed up.  And with a second season starting in about a week, it might get even worse...

So there is no way to force SR to use indexer numbering during manual post processing?

**Comment by fernandog** [comment]
@TagForce can you help me with this one ?
