### ISSUE TITLE
webapi CMD_ShowPause doesn't update database

### ISSUE THREAD

**Issue by sy6502a** [SiCKRAGETV/sickrage-issues#1789]
While working on an addon for Kodi/xbmc, I came across an issue where the SickRage webapi does not update the database for the "show.pause" command till SickRage restarts.  This causes the SickRage web interface to not show the "Coming Episodes" paused or not accurately.  And any addons retrieving the pause data will not be correct after a webapi "show.pause" command till after a restart.

My temporary fix was to edit "webapi.py" class CMD_ShowPause(ApiCall) to save the change to the database, by adding the calls "showObj.saveToDB()" before returning.

I'd like to request that this (or some other solution) be added to the webapi as a permanent fix.  You can see my changes in the last 6 lines of code below.

Thank you.

    class CMD_ShowPause(ApiCall):
        _help = {"desc": "set a show's paused state in sickrage",
                 "requiredParameters": {
                     "indexerid": {"desc": "unique id of a show"},
                 },
                 "optionalParameters": {
                     "tvdbid": {"desc": "thetvdb.com unique id of a show"},
                     "tvrageid": {"desc": "tvrage.com unique id of a show"},
                     "pause": {"desc": "set the pause state of the show"}
                 }
        }
    
        def __init__(self, args, kwargs):
            # required
            self.indexerid, args = self.check_params(args, kwargs, "indexerid", None, True, "int", [])
            # optional
            self.pause, args = self.check_params(args, kwargs, "pause", 0, False, "bool", [])
            # super, missing, help
            ApiCall.__init__(self, args, kwargs)
    
        def run(self):
            """ set a show's paused state in sickrage """
            showObj = sickbeard.helpers.findCertainShow(sickbeard.showList, int(self.indexerid))
            if not showObj:
                return _responds(RESULT_FAILURE, msg="Show not found")
    
            if self.pause:
                showObj.paused = 1
                showObj.saveToDB()
                return _responds(RESULT_SUCCESS, msg=str(showObj.name) + " has been paused")
            else:
                showObj.paused = 0
                showObj.saveToDB()
                return _responds(RESULT_SUCCESS, msg=str(showObj.name) + " has been unpaused")

**Comment by fernandog** [comment]
@sy6502a feel free to make a Pull request in develop branch

https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/webapi.py
