### ISSUE TITLE
[APP SUBMITTED]: saveNotifications() got an unexpected keyword argument 'layout'

### ISSUE THREAD

**Issue by EugenSeverins** [SiCKRAGETV/sickrage-issues#1790]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@f9246bcfdb95929e95e5f422d577fc9aa7d69953
Link to Log: https://gist.github.com/013651301dcf773b6063
### ERROR
```
Thread-39 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
TypeError: saveNotifications() got an unexpected keyword argument 'layout'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@EugenSeverins Are you using an notification client.? Try to disable that and see if it solves it.

**Comment by EugenSeverins** [comment]
The whole point is that a want to use both the Trakt notification as the
Kodi notifications. Disabling notification won't produce errors obviously

On Tue, 16 Jun 2015 at 13:40 neoatomic <notifications@github.com> wrote:

> @EugenSeverins <https://github.com/EugenSeverins> Are you using an
> notification client.? Try to disable that and see if it solves it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/1790#issuecomment-112393321>
> .
>
-- 
Groeten,

Eugen

**Comment by neoatomic** [comment]
Well, we first need to know what notifier is generating the errors. Once you have found out, check the  settings for that client.

However as you are using a QNAP there is a good change that its a SSL/https problem. So don't use Https.

**Comment by EugenSeverins** [comment]
The kodi notifier is working correctly, furthermore i have submitted
another issue concerning the trakt notifier, which does not work. It is
probably a ssl/https problem, but i do not know how to circumvent this. The
dont use ssl checkmark is on in the settings of the trakt notifier.

On Tue, 16 Jun 2015 at 14:01 neoatomic <notifications@github.com> wrote:

> Well, we first need to know what notifier is generating the errors. Once
> you have found out, check the settings for that client.
>
> However as you are using a QNAP there is a good change that its a
> SSL/https problem. So don't use Https.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/1790#issuecomment-112400998>
> .
>
-- 
Groeten,

Eugen

**Comment by neoatomic** [comment]
If you have setup all correctly and checked all than i'm affrayed that this is another (SSL) problem coming from QNAP not updating/maintaining there devices. From our side noting can be done about this... 

However i have read somewhere that it might be possible to install a third party Phyton Package that could solve the SSL errors. But don't know the details. Try to ask around on the QNAP forums, they might have found out a solution to fix the Python/SSL on QNAP devices.

**Comment by 4boys** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@f8eedd203011de46f61e7725cacd33de2146439c
Link to Log: https://gist.github.com/cc5075da5287755942f2
### ERROR
```
Thread-48 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 260, in async_call
    result = function(**kwargs)
TypeError: saveNotifications() got an unexpected keyword argument 'layout'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by distracto** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@e61aaf37645e360e5527b4d0b44a532dea63976c
Link to Log: https://gist.github.com/f3d6ad4000a74feac79b
### ERROR
```
Thread-37 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 251, in async_call
    result = function(**kwargs)
TypeError: saveNotifications() got an unexpected keyword argument 'layout'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by distracto** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@e61aaf37645e360e5527b4d0b44a532dea63976c
Link to Log: https://gist.github.com/af0c4e8632007cdd1ecc
### ERROR
```
Thread-38 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 251, in async_call
    result = function(**kwargs)
TypeError: saveNotifications() got an unexpected keyword argument 'layout'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by distracto** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@e61aaf37645e360e5527b4d0b44a532dea63976c
Link to Log: https://gist.github.com/847e11a053b0be9ade80
### ERROR
```
Thread-58 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 251, in async_call
    result = function(**kwargs)
TypeError: saveNotifications() got an unexpected keyword argument 'layout'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by distracto** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@e61aaf37645e360e5527b4d0b44a532dea63976c
Link to Log: https://gist.github.com/0d1df142d7e3a24db5e1
### ERROR
```
Thread-62 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 251, in async_call
    result = function(**kwargs)
TypeError: saveNotifications() got an unexpected keyword argument 'layout'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by distracto** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@e61aaf37645e360e5527b4d0b44a532dea63976c
Link to Log: https://gist.github.com/c792f6bd240b475cf574
### ERROR
```
Thread-59 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 251, in async_call
    result = function(**kwargs)
TypeError: saveNotifications() got an unexpected keyword argument 'layout'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by distracto** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@e61aaf37645e360e5527b4d0b44a532dea63976c
Link to Log: https://gist.github.com/14a681f56d703a47af14
### ERROR
```
Thread-34 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 251, in async_call
    result = function(**kwargs)
TypeError: saveNotifications() got an unexpected keyword argument 'layout'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by jamesjchapman** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
Link to Log: https://gist.github.com/849952e4288e216947cd
### ERROR
```
Thread-152 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 259, in async_call
    result = function(**kwargs)
TypeError: saveNotifications() got an unexpected keyword argument 'layout'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by jamesjchapman** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
Link to Log: https://gist.github.com/9e5703baeab6772f6ee1
### ERROR
```
Thread-140 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 259, in async_call
    result = function(**kwargs)
TypeError: saveNotifications() got an unexpected keyword argument 'layout'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
