### ISSUE TITLE
[APP SUBMITTED]: 403 Client Error: Forbidden

### ISSUE THREAD

**Issue by mbnoimi** [SiCKRAGETV/sickrage-issues#1791]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-18-generic-x86_64-with-LinuxMint-17.1-rebecca**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@f9246bcfdb95929e95e5f422d577fc9aa7d69953
Link to Log: https://gist.github.com/0624b6e3674e064b9ec8
### ERROR
```
SEARCHQUEUE-BACKLOG-79485 :: [Rarbg] :: Unable to connect to Rarbg provider: 403 Client Error: Forbidden
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
maybe i did'nt get an token. one time issue

**Comment by mbnoimi** [comment]
@fernandog 

> maybe i did'nt get an token. one time issue

I don't believe this one time issue. This issue related to #1794

**Comment by MickHussey** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.11+-armv6l-with-debian-7.8**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@56fd7a9447fb0e72398568be737c1f00b5bb07f4
Link to Log: https://gist.github.com/5269b59ffaf57e2ff51a
### ERROR
```
POSTPROCESSER :: Could not connect to Trakt. Code error: 403
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
