### ISSUE TITLE
Unable to find a download

### ISSUE THREAD

**Issue by chanlung** [SiCKRAGETV/sickrage-issues#1792]
SR Version:	 BRANCH: (master) / COMMIT: (f9246bcfdb95929e95e5f422d577fc9aa7d69953) 
Python Version:	2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]
Hardware and OS: Xbian on raspberry pi 2

---
Sickrage is unable to find a download for masterchef season 7 episodes.  I tried doing a manual episode search but logs says nothing found. When I do a manual search for "masterchef s07e01" I find it on kickass.
```
2015-06-10 01:51:44 INFO     SEARCHQUEUE-MANUAL-25606 :: Unable to find a download for: [Masterchef Australia - 7x01 - Auditions, Part 1]
2015-06-10 01:51:44 INFO     SEARCHQUEUE-MANUAL-25606 :: Performing season pack search for Masterchef Australia
2015-06-10 01:51:44 INFO     SEARCHQUEUE-MANUAL-25606 :: [Isohunt] :: Performing episode search for Masterchef Australia
2015-06-10 01:51:22 INFO     SEARCHQUEUE-MANUAL-25606 :: Performing season pack search for Masterchef Australia
2015-06-10 01:51:00 INFO     SEARCHQUEUE-MANUAL-25606 :: [AlphaRatio] :: Performing episode search for Masterchef Australia
2015-06-10 01:50:49 INFO     SEARCHQUEUE-MANUAL-25606 :: Performing season pack search for Masterchef Australia
2015-06-10 01:50:41 INFO     SEARCHQUEUE-MANUAL-25606 :: [KickAssTorrents] :: Performing episode search for Masterchef Australia
2015-06-10 01:50:40 INFO     SEARCHQUEUE-MANUAL-25606 :: Performing season pack search for Masterchef Australia
2015-06-10 01:50:39 INFO     SEARCHQUEUE-MANUAL-25606 :: [ThePirateBay] :: Performing episode search for Masterchef Australia
2015-06-10 01:50:39 INFO     SEARCHQUEUE-MANUAL-25606 :: Building internal name cache for Masterchef Australia
2015-06-10 01:50:39 INFO     SEARCHQUEUE-MANUAL-25606 :: Beginning manual search for: [Masterchef Australia - 7x01 - Auditions, Part 1]

```

**Comment by miigotu** [comment]
If you turn on debug logging, you will see why it is not accepting the one found on kickass

**Comment by miigotu** [comment]
Maybe you have quality for that show set to something other than SD? PDTV x264 is SD.

**Comment by shauntarves** [comment]
I am not sure this is related, but I am also having difficulty finding results. My instance of SR cannot find any episode results (using all usenet providers). In the debug logs, it shows the queries it's sending to the nzb indexes, all of which find results when executed manually.

If you try (in a browser) the exact query shown for the Sick Beard Index in the Pastebin log, you'll see you get xml with results back, yet SR doesn't think it found any.

http://pastebin.com/qBTBJic8

**Comment by miigotu** [comment]
@shauntarves What quality do you have Veep set to?

**Comment by miigotu** [comment]
99% of problems are that people don't understand the different combinations of quality tags in scene release names, and expect that things like "HDTV" all by itself is "HDTV" when it is not.

**Comment by shauntarves** [comment]
@miigotu I tried with both SD and HD720p, but even when I set it to ANY, it has the same result...the queries go out and fail to find matches even though matches are in the results. I'm new to this, so there very well might be something I'm missing, but I can't fathom what.

At this point, I'm simply trying a manual search for one episode - and even a recent episode (aired last week) fails.

**Comment by miigotu** [comment]
@shauntarves the matches are not there. The ones on the lolo.sickbeard indexer are 720p WEB-DL, not the same as HD720p or SD. Try a custom quality setting for 720p WEB-DL.

**Comment by miigotu** [comment]
I did find a bug with black-hole torrents being created with bad info, maybe this helps your issue?

**Comment by shauntarves** [comment]
@miigotu, how does that explain no matches even when I set the quality to Any? (See my above message...I tried SD, HD720p, and Any)

**Comment by miigotu** [comment]
@shauntarves try best instead of any. and try updating to latest dev branch.

**Comment by shauntarves** [comment]
@miigotu I switched to develop branch. There is no option for "Best" only "Custom", "SD", "HD720p", "HD1080p", "HD", and "Any".

However, I noticed this while watching the log on startup:

/Applications/SickRage/lib/imdb/parser/http/utils.py:472: UserWarning: unable to use "lxml": No module named lxml.html

is lxml a crucial library for parsing results?! Could the issue be as simple as that?

**Comment by shauntarves** [comment]
Also, in response to this message: "the matches are not there. The ones on the lolo.sickbeard indexer are 720p WEB-DL, not the same as HD720p or SD. Try a custom quality setting for 720p WEB-DL."

That's not true. The first item is 720 WEB-DL, but there are 2 other items in the results, one marked HDTV and one marked 720p

http://lolo.sickbeard.com/api?season=2&maxage=2500&cat=5030%2C5040&limit=100&attrs=rageid&offset=0&rid=28149&ep=10&t=tvsearch

**Comment by miigotu** [comment]
@shauntarves Provide full debug log, not just searchqueue.

**Comment by shauntarves** [comment]
I'm going to summarize this and paste logs one more time. I'm beginning to believe this actually has to do with the episode search string used with the (built-in) Sick Beard Index provider and the (custom) OZnzb provider.

In the pasted debug logs, pay special attention to the episode format string. There's a message like "Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN" Both of the nzb indexes it tries to query return items with episode names like S03E09.

If this is indeed the problem, how can it be rectified? I can't find anything in the SR configs to change the episode search style for either of those providers.

http://pastebin.com/0tuY7K0E

**Comment by miigotu** [comment]
@shauntarves thats not a full log bro. Upload it somehwere if you have to and pm me a link.

**Comment by shauntarves** [comment]
@miigotu emailed a link...contains clean startup and one manual search

**Comment by miigotu** [comment]
@shauntarves All of the episodes you don't have are set to skipped status. edit the show and set the default status to wanted, and then episode management page to mark them wanted.

**Comment by shauntarves** [comment]
@miigotu Already tried that, literally the exact same result. Can resend another log if you want to prove it. Is there nothing to the episode string format thought?

**Comment by miigotu** [comment]
No that log line is misleading, it makes it like 1x1 so the regex has an easier time converting it to the other possible known naming styles.

**Comment by miigotu** [comment]
And if you have a different log where you are trying to search for an episode that is not skipped status, let me know. S03E09 is the only one you searched for, but it has status 5, which is "skipped".

Also, it the network times always erroring for you on startup?

**Comment by shauntarves** [comment]
@miigotu A new version of the log is in the same place. Before shutting down SR, I changed all episodes I don't currently have to Wanted. This amounted to 2 shows (Arrested Development and Veep).

I then brought it back up to capture the timezone download failure, but I don't think it happened this time. The shutdown process starts at 06-12 10:05:04 in the log.

Also tried a manual search of the episode in the Wanted state at the end of the log.

**Comment by Sliferghost** [comment]
I believe I have similar problems. When going to the links provided in the log, the xml returned shows results. When I use the quality setting: "any", SR still believes there are no results.

**Comment by miigotu** [comment]
@shauntarves tried deleting cache.db and cache.db-journa if it exists, and the cache folder?

**Comment by miigotu** [comment]
And then restarting ofc.

**Comment by miigotu** [comment]
@shauntarves Don't know if you saw, but update to the commit I just pushed and at least newznab providers work again. I havent tested other nzb indexers, but they may work now again if they were broken.

**Comment by shauntarves** [comment]
Thanks. I'm on vacation and haven't been able to try any of these suggestions since Friday. I'll be back soon to see if anything works for me. Excellent news support guys; hope I can get this working.
