### ISSUE TITLE
[Feature Request] Make Search Providers work with TOR

### ISSUE THREAD

**Issue by mbnoimi** [SiCKRAGETV/sickrage-issues#1794]
Hi,

In my country ISPs forbid torrent websites so I use forced to use TOR (I can't pay VPS costs) but unfortunately most available Search Providers don't work with TOR because of CloudFlare dumb ass.

Does any one know a solution for this issue?

BTW, the following providers works fine with TOR:
- KickAssTorrents: https://kat.cr/
- TokyoToshokan: http://tokyotosho.info/
- NyaaTorrents: http://nyaa.se

**Comment by papampi** [comment]
I use tor+privoxy too, and I can confirm so many web sites use cloudflare captcha for tor, but piratebay, rarbg and kat.cr works fine with tor+privoxy.
how do you use tor ? is it direct socks to tor or its through privoxy or other proxy app ?

**Comment by mbnoimi** [comment]
@papampi 
>  how do you use tor ? is it direct socks to tor or its through privoxy or other proxy app ?

I'm using http proxy using polipo (it works fine)

> but piratebay, rarbg and kat.cr works fine with tor+privoxy.

Nope. piratebay and rarbg don't work at all... the log clarify that and browsing using Firefox does too
- piratebay: http://pix.toile-libre.org/upload/original/1434329072.png
- piratebay: http://pix.toile-libre.org/upload/original/1434329181.png
- rarbg: http://pix.toile-libre.org/upload/original/1434329205.png

**Comment by papampi** [comment]
Maybe I'm wrong then
I think there is nothing SR team can do with the cloudflare/tor captcha thingy...
but you can use vpn, many vpn providers block p2p and some dont.
check this post : http://torrentfreak.com/anonymous-vpn-service-provider-review-2015-150228/
I just started using privateinternetaccess and it seems very fast and stable and low price 
you can either set it up on your pc or router or ....

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!

**Comment by mbnoimi** [comment]
Come on! put a link to the suggestion please I found tens 203 opened suggestion!

**Comment by mbnoimi** [comment]
Using http://feathub.com is really bad choice because it has search about suggestions!

**Comment by mbnoimi** [comment]
I gave up searching about if this feature asked or not. I've added a new one at:
http://feathub.com/SiCKRAGETV/SickRage/+215
