### ISSUE TITLE
Problem with a show

### ISSUE THREAD

**Issue by rickytin** [SiCKRAGETV/sickrage-issues#1795]
I add the show Blindspot with TVDB indexer but it docent appear in the show list and every time I start SickRage it try to add the show but it can't add the show.
This is the log & error massage: SHOWQUEUE-ADD :: Unable to find show ID:295261 on Indexer: theTVDB
I would like to know if there is a way to delete the show from the database so everytime I open SickRage it dosent try to add the show.

Here I include link to 2 screenshot:

https://drive.google.com/open?id=0B_...&amp;authuser= 0
​https://drive.google.com/open?id=0B_...&amp;authuser= 0

Thanks for the help.

Ricky

**Comment by fernandog** [comment]
@rickytin do you use trakt in SR? remove from watchlist

**Comment by rickytin** [comment]
Thanks Fernando for the replay.
Yes I use Trakt with SickRage, the problem is that I have remove "Blindspot" form my watchlist in Trakt many times and when I open SickRage, SickRage added again to my watchlist in Trakt.

Also it would be nice if I delete a show from SickRage that it also get remove from my watchlist in Trakt. Sometimes I have to delete a couple of time the same show from SickRage and from my watchlist in Trakt.

Thanks again.

**Comment by fernandog** [comment]
@rickytin disable trakt in SR, restart, remove show from SR, remove from trakt. enabled trakt again

**Comment by miigotu** [comment]
@fernandog we need to add an option that defaults to removing a show from trakt when a show is deleted, and stop this issue from coming up.

**Comment by rickytin** [comment]
Thanks Fernando, I will try this when I get to home and miigotu yes it would be great.
Thanks Fernando and Miigotu for the time you spend making SickRage a better program.

Ricky

**Comment by rickytin** [comment]
I am still having a problem removing the show "Blindspot".
Fernandog I did what you suggest but the problem is in my SickRage show list I don't have the show "Blindspot" so I cant remove the show from there. I only know the problem because I see the Logs & Errors massage "2015-06-13 09:09:29 SHOWQUEUE-ADD :: Show Blindspot is on theTVDB but contains no season/episode data." 
It's not a big problem but it's strange.
Again thanks for the help.

**Comment by miigotu** [comment]
@rickytin maybe you have some other watch list enabled that re-adds it? I have noticed this happen once or twice to me before, but clicking remove the second time removed it.

**Comment by rickytin** [comment]
Miigotu thanks for the tip, finally the show Blindspot is not showing in SickRage.
Thanks Fernandog and Miigotu for all the help and remember that it would be nice to have the option to remove a show from trakt when a show is deleted in SickRage.
