### ISSUE TITLE
[APP SUBMITTED]: u'\xbd'

### ISSUE THREAD

**Issue by Trapizomba** [SiCKRAGETV/sickrage-issues#1796]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 06:12:10) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@f9246bcfdb95929e95e5f422d577fc9aa7d69953
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-7679 :: [NextGen] :: Error while searching NextGen, skipping: ½
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Trapizomba** [comment]
The TV Show is an Anime...
http://thetvdb.com/?tab=series&id=76932&lid=7
http://www.tvrage.com/ranma
http://www.tvrage.com/ranma-oav

**Comment by neoatomic** [comment]
@Trapizomba Please post logs. Cant see what is going wrong without them.

**Comment by Trapizomba** [comment]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 06:12:10) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@e6c4cfd6546b74d5527361f6f0bdc3adc232bdb0
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-1630 :: [NextGen] :: Error while searching NextGen, skipping: ½
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
https://sickrage.tv/forums/forum/help-support/general-support/12825-ensuring-your-locale-s-are-set-properly-to-avoid-unicode-issues

**Comment by fernandog** [comment]
set the locale to the user that you run SR. check the user in localhost:8081/config

**Comment by Trapizomba** [comment]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 06:12:10) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@e6c4cfd6546b74d5527361f6f0bdc3adc232bdb0
Link to Log: https://gist.github.com/a899887f8d63782fe35a
### ERROR
```
SEARCHQUEUE-BACKLOG-1630 :: [NextGen] :: Error while searching NextGen, skipping: ½
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
