### ISSUE TITLE
[Feature Request] Option to send replaced downloads to trash/recycle (instead of permanent deletion)

### ISSUE THREAD

**Issue by andyj682** [SiCKRAGETV/sickrage-issues#1798]
I'm running SickRage on a Synology NAS. I appreciate the option--which I think was added relatively recently?--to use trash/recycle instead of permanent deletion when I manually remove files or a show. But I'd much rather have this option for downloads that SickRage replaces, either with propers/repacks or with a higher quality. Every now and then SickRage will grab something it thinks is a proper or a better quality that I don't actually want, and I'd love to be able to just restore the old file from the recycle bin. Not super high priority, obviously, but I assume this would be relatively easy to implement if it's already been implemented in other scenarios.

**Comment by neoatomic** [comment]
Never used trash/recycle on my Synology, but this is a function of the Synology and hasn't anything to do with SickRage.

To use you have to setup your Synology share/folder for this function. See Synology help for this. : 
https://help.synology.com/dsm/?section=DSM&version=5.2&link=AdminCenter%2Ffile_share_create.html

**Comment by andyj682** [comment]
So what, then, is the expected effect of ticking "when using show 'Remove' and delete files" under "Send to trash for actions" in general settings? I'm assuming it means it'll use the trash instead of permanent delete when you choose to remove a show from the database and delete the files, right? And if this is implemented, why would it not be a valid feature request to simply extend that functionality to anytime SickRage deletes a file (e.g., when replacing an existing file with a proper/repack/better quality)? Or are you saying this is already the expected functionality and I just haven't configured my box correctly? (I'm skeptical if it's the latter, since I have the recycle function enabled and working fine on my TV folder.)

**Comment by neoatomic** [comment]
@andyj682 When you enable recycle bin on your Synology it should store the deleted files in a recycle bin as you can see in the help i posted above. That should include removed files for propers.
Do i understand you correctly that you have this setup right, and deleted files are still not stored in the recycle bin.?

@fernandog Don't think we have something in the code that prevents this from working.?

**Comment by fernandog** [comment]
Really dont know. Never used this feature

**Comment by andyj682** [comment]
@neoatomic @fernandog Yeah, no big deal. I guess maybe I'm not understanding the point of that option in SickRage, or something? I wouldn't have asked about extending it to cover other instances where it replaces/deletes files if the current option didn't already exist.
