### ISSUE TITLE
[APP SUBMITTED]: 'charmap' codec can't encode characters in position 0-10: character maps to <undefined>

### ISSUE THREAD

**Issue by Xenocell12** [SiCKRAGETV/sickrage-issues#1802]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@68c55eadbd502c63ae35e42ccc741509e94f3d6a
Link to Log: https://gist.github.com/6f54928080e4e9273abc
### ERROR
```
SEARCHQUEUE-MANUAL-70668 :: [Sick Beard Index] :: Error while searching Sick Beard Index, skipping: charmap :  4 : error 0 : error 11 : character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Xenocell12** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@68c55eadbd502c63ae35e42ccc741509e94f3d6a
Link to Log: https://gist.github.com/76668d0d7a3fd0c0eb19
### ERROR
```
SEARCHQUEUE-MANUAL-70668 :: [Usenet-Crawler] :: Error while searching Usenet-Crawler, skipping: charmap :  4 : error 0 : error 11 : character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Xenocell12** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@68c55eadbd502c63ae35e42ccc741509e94f3d6a
Link to Log: https://gist.github.com/6c43538b877c3fb9a4af
### ERROR
```
SEARCHQUEUE-MANUAL-70668 :: [Sick Beard Index] :: Error while searching Sick Beard Index, skipping: charmap :  6 : error 0 : error 11 : character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Xenocell12** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@68c55eadbd502c63ae35e42ccc741509e94f3d6a
Link to Log: https://gist.github.com/1dc78b1d5b18c06309fd
### ERROR
```
SEARCHQUEUE-MANUAL-70668 :: [Usenet-Crawler] :: Error while searching Usenet-Crawler, skipping: charmap :  6 : error 0 : error 11 : character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Xenocell12** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@68c55eadbd502c63ae35e42ccc741509e94f3d6a
Link to Log: https://gist.github.com/3a512612de6161dd5f9e
### ERROR
```
SEARCHQUEUE-MANUAL-70668 :: [OzNBZ] :: Error while searching OzNBZ, skipping: charmap :  6 : error 0 : error 11 : character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Xenocell12** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@68c55eadbd502c63ae35e42ccc741509e94f3d6a
Link to Log: https://gist.github.com/0eab3ac0b05774525449
### ERROR
```
SEARCHQUEUE-MANUAL-70668 :: [Sick Beard Index] :: Error while searching Sick Beard Index, skipping: charmap :  5 : error 0 : error 11 : character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Xenocell12** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@68c55eadbd502c63ae35e42ccc741509e94f3d6a
Link to Log: https://gist.github.com/2cdf504d838a4ace87e2
### ERROR
```
SEARCHQUEUE-MANUAL-70668 :: [OzNBZ] :: Error while searching OzNBZ, skipping: charmap :  7 : error 0 : error 11 : character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Xenocell12** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@68c55eadbd502c63ae35e42ccc741509e94f3d6a
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-MANUAL-70668 :: [Usenet-Crawler] :: Error while searching Usenet-Crawler, skipping: charmap :  5 : error 0 : error 11 : character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Xenocell12** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@68c55eadbd502c63ae35e42ccc741509e94f3d6a
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-MANUAL-70668 :: [OzNBZ] :: Error while searching OzNBZ, skipping: charmap :  5 : error 0 : error 11 : character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Xenocell12** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@68c55eadbd502c63ae35e42ccc741509e94f3d6a
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-MANUAL-70668 :: [OzNBZ] :: Error while searching OzNBZ, skipping: charmap :  4 : error 0 : error 11 : character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Xenocell12** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@68c55eadbd502c63ae35e42ccc741509e94f3d6a
Link to Log: https://gist.github.com/637a1a8b257290927496
### ERROR
```
SEARCHQUEUE-MANUAL-70668 :: [Sick Beard Index] :: Error while searching Sick Beard Index, skipping: charmap :  7 : error 0 : error 11 : character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Xenocell12** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@68c55eadbd502c63ae35e42ccc741509e94f3d6a
Link to Log: https://gist.github.com/358cbf6cf8ba9a0c1f17
### ERROR
```
SEARCHQUEUE-MANUAL-70668 :: [Usenet-Crawler] :: Error while searching Usenet-Crawler, skipping: charmap :  7 : error 0 : error 11 : character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
What language do you have set for cardcaptor sakura?
