### ISSUE TITLE
[APP SUBMITTED]: Thread-87 :: No Show Object found for show with indexerID: 70668

### ISSUE THREAD

**Issue by Xenocell12** [SiCKRAGETV/sickrage-issues#1803]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@68c55eadbd502c63ae35e42ccc741509e94f3d6a
Link to Log: https://gist.github.com/22f04dd8116f16fe4dd9
### ERROR
```
Thread-87 :: No Show Object found for show with indexerID: 70668
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@Xenocell12 did you recently deleted any shows?

**Comment by fernandog** [comment]
@Xenocell12 did you recently deleted any shows?

**Comment by neoatomic** [comment]
Looks to be the related to https://github.com/SiCKRAGETV/sickrage-issues/issues/1802 
Also seems to be specific for only one show. "Cardcaptor Sakura"  

Special characters or bad info from the indexer.?
@Xenocell12 Try to add the show with another indexer and see if that helps.

**Comment by miigotu** [comment]
@Xenocell12 what language is set for the show "Cardcaptor Sakura"?
