### ISSUE TITLE
Try searching 1x01 format if can't find S01E01 format

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#1804]
I noticed with a few shows such as Hannibal some episodes are uploaded as ``Hannibal 3x01`` instead of ``Hannibal S03E01`` and this ends up Sickrage not finding the episode.

Could Sickrage search for the other format if the first isn't found?

**Comment by miigotu** [comment]
It already does search multiple types of episode naming, and most of the time we use an api which doesnt use a normal search string, we just tell it we want tvdbid= season= and episode= and it gives us all results.

**Comment by OmgImAlexis** [comment]
So I'm assuming it could be that the episode didn't have the tvdvid assigned on kat.cr and that's causing the issue?
