### ISSUE TITLE
sabToSickBeard.exe does not work

### ISSUE THREAD

**Issue by Martijn085** [SiCKRAGETV/sickrage-issues#1806]
I use SABnzbd on my Windows server but sabToSickBeard.exe does not work with SickRage. Check also the SickRage forum: https://sickrage.tv/forums/forum/help-support/general-support/22262-sabtosickbeard-exe-py-no-longer-working

How to compile the Python script to .exe for Windows?

Or is there anyone with a up-to-date exe file?

**Comment by mckinnon81** [comment]
Hi;

Looking through that forum it looks like that you are having an issue with the python files.

Recommend download the latest update  - https://github.com/SiCKRAGETV/SickRage/archive/master.zip

Try copying old instance to a backup then install a fresh copy and setup and see if you can replicate the issue with a fresh copy downloaded above.

If you just need the py files try this - https://raw.githubusercontent.com/SiCKRAGETV/SickRage/master/autoProcessTV/autoProcessTV.py

Also as you have said you are running Windows. Do  you have python installed?

**Comment by Martijn085** [comment]
SickRage is up-to-date but does not run on Windows. 
My SickRage is running on my Synology Nas and SABnzd is running on my Windows machine.

With SickBeard (the original) the post process script works fine with sabtoSickbeard.exe but is not working with SickRage because of the login changes. So the sabtoSickbeard.exe must be updated to understand the login page of SickRage.

I have tried to run the python script from the Windows machine (with Python installed) but this is not working, i only get errors. Is there a way to update the sabtoSickbeard.exe to work with SickRage?

**Comment by mckinnon81** [comment]
Looks like you have the same issue as this - https://github.com/SiCKRAGETV/sickrage-issues/issues/452

Try heymoe suggestion on above page.

You can find those scripts here - https://github.com/clinton-hall/nzbToMedia

This may mean moving to something else rather that sabtosickbeard

**Comment by Martijn085** [comment]
Ok thanks. Will try that one and will let you know.

**Comment by Martijn085** [comment]
I have found the problem, you must have pywin installed to make the sickrage script to work. Now everything is working fine with the default sickrage script.
