### ISSUE TITLE
[APP SUBMITTED]: 401 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Bad credentials'}

### ISSUE THREAD

**Issue by greg4168** [SiCKRAGETV/sickrage-issues#1807]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@68c55eadbd502c63ae35e42ccc741509e94f3d6a
Link to Log: https://gist.github.com/810e699679d3ab639357
### ERROR
```
Thread-115 :: 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
wrong user/password

**Comment by greg4168** [comment]
Hi Fernando - I then resubmitted with a correct id/password.
