### ISSUE TITLE
Cannot download the messengers

### ISSUE THREAD

**Issue by Sliferghost** [SiCKRAGETV/sickrage-issues#1808]
Branch: master 68c55eadbd502c63ae35e42ccc741509e94f3d6a
System info: Windows 8.1, Python 2.7

SR has trouble finding two episodes of the show the messengers. I tried a lot of different configurations but all have the same behaviour, namely that it does not parse the results. The episodes in question are: s01e04 and s01e08.

I tried:
With exception list: The Messengers, the messengers, The Messengers 2015, the messengers 2015.
Enabled and disabled scene numbering.
With all the different quality settings.

The result is that it won't download the shows. I also checked the URLs SR visits and it does contain result(s) however SR won't "accept" them.

The log:
https://gist.github.com/Sliferghost/7a1504ad9b0441c8fb7d

**Comment by miigotu** [comment]
Works fine here: https://gist.github.com/miigotu/aee36bc065b86bcd536f

Quality settings wrong maybe? HDTV.x264 is actually SDTV.

**Comment by Sliferghost** [comment]
I tried with all the different quality settings. Even if I say quality "any" or "sd" it still won't parse the episode like in your log.

**Comment by miigotu** [comment]
Full log please, upload it somewhere. Global required/ignored words, show required/ignored words, or need to change the quality correct. It definitely works.

**Comment by Sliferghost** [comment]
I removed the show as I don't watch it anymore, however the same happens with the show Dark Matter. Again quality settings at "any".
See full log here: https://gist.github.com/Sliferghost/8620b0ac1a4448ef7288
Global required words: none
Global ignored words: german,french,core2hd,dutch,swedish,reenc,MrLss
Show required words: none
Show ignored words: none

I see, based on the directory, you use an unix based system and I use a windows based system. Could the problem be windows related?

**Comment by miigotu** [comment]
I don't think so, but anything is possible. We have hundreds of other windows (and linux) users who do not have this problem.

**Comment by Sliferghost** [comment]
Do you have anything else I could try?

**Comment by Sliferghost** [comment]
It seems like this user has a similar problem. 
https://sickrage.tv/forums/forum/help-support/general-support/23992-sickrage-not-finding-new-episode

**Comment by miigotu** [comment]
Again, need full log. Problems in early startup can make these things happen.

**Comment by Sliferghost** [comment]
See this link for the full log: https://gist.github.com/Sliferghost/8620b0ac1a4448ef7288#file-sr-complete-log

**Comment by Sliferghost** [comment]
Updated the Gist to also include shutdown behavior.

**Comment by miigotu** [comment]
@Sliferghost I can reproduce this now, with Dark Matter. I will try and debug it tonight.

**Comment by Sliferghost** [comment]
I see, please let me know when if you need anything else from me.

**Comment by miigotu** [comment]
@Sliferghost If you edit the show, and add an exception `Dark Matter` it snatches.

**Comment by miigotu** [comment]
This is definitelty problem. Knowing that a scene exception fixes it narrows the search radius drastically.

**Comment by Sliferghost** [comment]
For me it still does not work after adding the exception. It seems like we still have two different problems.

**Comment by Sliferghost** [comment]
Is there like a python debug mode I could run to see why it fails?

**Comment by miigotu** [comment]
You're right, this time it didn't work with scene exception either, just that 1 time.

**Comment by miigotu** [comment]
No, thats pretty much almost all of the debug we have, but since I can reproduce it I can debug it.

**Comment by miigotu** [comment]
Here is the problem, sick beard index has raised the time limit between requests. @fernandog This is the bozo exception you referenced.

SR updates the cache for daily search, and then right away tries to do the backlog search, and then falls back to another search for a season pack.

newznab provider returns:

```
{'feed': {}, 'status': 403, 'version': u'', 'encoding': u'utf-8', 'bozo': 1, 'headers': {'retry-after': '5', 'content-length': '395', 'x-cache': 'MISS', 'x-cdn-any-ip': '46.105.201.50', 'accept-ranges': 'bytes', 'x-cacheable': 'Not cacheable: not http 200', 'x-cdn-geo-ip': '46.105.194.229', 'connection': 'close', 'cache-control': 'no-cache, must-revalidate, post-check=0, pre-check=0', 'date': 'Sun, 14 Jun 2015 22:59:59 GMT', 'content-type': 'text/html; charset=utf-8', 'x-cdn-geo': 'dal'}, 'href': u'http://lolo.sickbeard.com/api?season=1&maxage=500&cat=5030%2C5040&q=Dark.Matter&limit=100&attrs=rageid&offset=0&ep=1&t=tvsearch', 'namespaces': {}, 'entries': [], 'bozo_exception': SAXParseException('XML declaration allowed only at the start of the document\n',)}
```

**Comment by miigotu** [comment]
Can anyone test sickbeard index using official sickbeard and give me the search urls from the log?

For now it seems backlog search is also searching the same as daily, then searching for the episode with another request.

Also, sickbeard index is not honoring the retry-after header it is sending.

**Comment by miigotu** [comment]
#1556 is true, which is causing your problem. As a temporary workaround, use a different indexer than Sick Beard Index. I assume womble's is either doing the same or didn't have Dark Matter in the index.

I have a way to bypass their limitting altogether, but I dont want to do that until I fix the reason they limitted us in the first place.

Basically, SR is so popular that we were hogging so many resources that their own app could not get results reliably.

**Comment by miigotu** [comment]
@Sliferghost can you update and try now please?

**Comment by Sliferghost** [comment]
@miigotu I will try in a second, also note: the problem is only when I do a manual search. When the daily search happens it does find the episode and downloads it. Thought I should mention that, going to try the new develop branch.

**Comment by fernandog** [comment]
@Sliferghost when you hit manual search how do you answer the two questions that pops in the screen?

**Comment by Sliferghost** [comment]
@miigotu not sure what you changed but all of a sudden a lot of things started to download so I guess the issue is fixed - including the missing episode of dark matter.

**Comment by Sliferghost** [comment]
@fernandog should I get questions? Because there are none when I press the magnifier glass.

**Comment by fernandog** [comment]
@Sliferghost when you press MS, the status is WANTED or SNATCHED? If is SNATCHED you must answer two questions

**Comment by Sliferghost** [comment]
@fernandog the status is "wanted". However the changes from @miigotu have fixed the issue so I suppose this issue can be closed.
