### ISSUE TITLE
[APP SUBMITTED]: global name 'WindowsError' is not defined

### ISSUE THREAD

**Issue by Jenks001** [SiCKRAGETV/sickrage-issues#1809]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-37-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@68c55eadbd502c63ae35e42ccc741509e94f3d6a
Link to Log: https://gist.github.com/98dbcf6a5328fb530410
### ERROR
```
Thread-64 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/jake/.sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/home/jake/.sickrage/sickbeard/webserve.py", line 2174, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/home/jake/.sickrage/sickbeard/processTV.py", line 250, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/home/jake/.sickrage/sickbeard/processTV.py", line 498, in process_media
    result.result = processor.process()
  File "/home/jake/.sickrage/sickbeard/postProcessor.py", line 1031, in process
    if helpers.isFileLocked(self.file_path, True):
  File "/home/jake/.sickrage/sickbeard/helpers.py", line 1587, in isFileLocked
    except WindowsError:
NameError: global name 'WindowsError' is not defined

```
---

Upon updating through the app i no longer have a dropdown box on the 'Shows' tab and manual post processing does nothing but bring this error. I am completely noob at all this so i will need step by step instructions, thanks.
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@miigotu hotfix?

**Comment by miigotu** [comment]
@Jenks001 The drop down was taken out on purpose, you have buttons for post processing and add shows at the top right of the shows page, and without a drop-down it saves one click to get back to the shows page.

As for the WindowsError, we need to fix that.

**Comment by miigotu** [comment]
IOError and WindowsError are aliases for OSError, hotfix coming.

**Comment by fernandog** [comment]
But we only want windows error isnt?

**Comment by miigotu** [comment]
No, we need to know if a file cannot be written to in linux also. This was discussed in the original PR. https://github.com/SiCKRAGETV/SickRage/pull/1821#commitcomment-10945898
