### ISSUE TITLE
Edit a show location after moving the folder : nfo files are recreated in the old path after next show update

### ISSUE THREAD

**Issue by djack42** [SiCKRAGETV/sickrage-issues#1811]
Configuration
SR Version:	BRANCH: (master) / COMMIT: (68c55eadbd502c63ae35e42ccc741509e94f3d6a) 
SR Locale:	('en_US', 'UTF-8')
Python Version:	2.7.9 (default, Apr 29 2015, 19:33:17) [GCC 4.8.3 20140401 (prerelease)]

I moved some shows one by one (folders)
Then i went to each show edit page to update location
After next show update, nfo files of missing episodes already downloaded are recreated in the old path (creating the show folder too).
These missing episodes are automatically deleted from disk when seen on my kodi media center.
Even if i set the episodes to archived, the nfo files are recreatd in the old path.

What is going on when a show is moved ? I already have a long date problem with mass update not working at all on my system, i have to do it one by one on the edit show page.
And i resinstalled everything again 4 weeks ago, so new DB.

Please, can you see why it's happening and why an archived episode has its nfo recreated ?

**Comment by miigotu** [comment]
On the edit show page, did you scroll all the way down and click submit after changing the location?

**Comment by djack42** [comment]
Yes.
New episodes are downloaded in the good path.
Only the nfo files of old deleted episodes are sometimes recreated in the old path.
It's not always happening.
It seems to me that there is a design flaw in the db, episodes should not have their full path stored. They should use the show's path instead. This redondancy shouldn't exists.
The bug might not even exists in the code anymore.
A db cleanup is required.

**Comment by fernandog** [comment]
@djack42 we did a lot of changes in nfo info and checks. maybe it's something related to the old code. will close. check if this happens with new episodes and send full logs
