### ISSUE TITLE
[Feature Request] History page limit

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#1812]
Abillity to change the default nº of items on the history page ,for example i would like to be show  250 items instead of the default 100

**Comment by neoatomic** [comment]
I try'd to add this some time ago. But got stuck on saving the setting, As an entry in config.ini needs to be made. However should be an easy fix for the Developers. 
https://github.com/SiCKRAGETV/SickRage/pull/1761

**Comment by neoatomic** [comment]
@WebSpider Thanks for adding. :)
