### ISSUE TITLE
[Feature Request] Access videos in non-default root directory remotely

### ISSUE THREAD

**Issue by MGaetan89** [SiCKRAGETV/sickrage-issues#1816]
If I try to access a downloaded video from `videos/path_to_my_video` it works fine if the video is in the default root directory.

But if the video is in an other root directory, then the video can not be found.

Is it possible to include non-default root directories in the `videos/` path?

**Comment by neoatomic** [comment]
Have you try'd to add a folder redirection.? Might do the trick if you have the correct permissions set.

**Comment by MGaetan89** [comment]
What do you mean by a folder redirection?

Shouldn't all the root folders defined in SickRage be accessible in `/videos/`?

**Comment by neoatomic** [comment]
They should indeed be accessible. So if you cant access the folders than likely the permissions aren't set correctly. (maybe the download client sets different permissions.?)

With folder redirection i mean create a sub folder and point it to another location on your disk/network.

**Comment by MGaetan89** [comment]
Only the default root folders is accessible. Any other folder is not. And from my understanding of the source, that's the desired effect. Can you confirm that?

**Comment by Thraxis** [comment]
I'm a bit confused by what your reference to a SR "videos" path.  SickRage will download and store shows to any path accessible on your system.  Each show could be set to it's own "root" path.  SickRage doesn't have a central "video" storage.

Are you trying to access this path via HTTP, NFS, SAMBA (Windows File Share), Locally?

Is this SickRage install a standalone SickRage install or was it installed as part of a MediaCenter system or as a plugin to Kodi / XBMC?

**Comment by MGaetan89** [comment]
I'm using SickRage on a Synology NAS, accessible locally and remotely.

Sorry of I wasn't clear. I am talking about this:
https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/webserveInit.py#L124
SickRage has an URL to allow access to a video file directly. But I think
it only uses the default root dir, not all root dirs.

**Comment by Thraxis** [comment]
Yes it is using only the first defined root directory... which is most likely the default one.

**Comment by MGaetan89** [comment]
Is it possible to changed that to test all root dirs?

**Comment by miigotu** [comment]
It is possible, now that we know what you actually mean lol. 
Any change should continue to provide the 1 root dir at the same url. (Always the default right? root dirs are reordered in the gui when you set a new default)
 
A new path should be added which defines a new location with a sublocation for each defined video root, created dynamically with a for loop.

something like:
```
/videodirs/0
/videodirs/1
/videodirs/2
```
https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/webserveInit.py#L36
https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/webserveInit.py#L124

**Comment by MGaetan89** [comment]
Wouldn't it be better to handle the root dirs internally instead of providing multiple URLs?
I'm building an Android app for SickRage with a streaming feature of the downloaded episodes. But I don't think there is a way to know in which root dir a specific video is, is there?

**Comment by miigotu** [comment]
Separate root directories are separate for a reason, otherwise people would just use the same folder.
You already would have to iterate over a directory list regardless, and i would assume you want the same behavior as SR or Kodi when it comes to this.

Query the number/paths of root dirs, iterate over each, done?

**Comment by miigotu** [comment]
Heh, would be even nicer to be able to add labels to each root dir, then you could call

`/videos/MyLabel/xxxxxx`

**Comment by MGaetan89** [comment]
I like the idea of having a label for each root dir too.

For my use case, it would be nice if the episode API would return the root
dir/alias/id (path would be the easiest) or whatever.
In my app I have a "play" button on the detail of each episode to stream it
if it was downloaded. Currently I'm using the default root dir. So it works
in most cases, but not all of them

On Jun 18, 2015 7:38 AM, "Dustyn Gibson" <notifications@github.com> wrote:
>
> Heh, would be even nicer to be able to add labels to each root dir, then
you could call

**Comment by miigotu** [comment]
I need to look into this better before I make an informed decision. I dont know how to even play files using the url yet lol. I haven't used the webapi much, but the code there is simple as it gets.

**Comment by MGaetan89** [comment]
The code is simple yes, but it leaves maybe too much work to the client app. If SickRage wants to change something about the `videos` path tomorrow, it may break something for all the client apps.
If the root dirs are handled internally, any changes are transparent for the client apps.

To use the `videos` path, you need to:
- Get the full path (with `full_path=1`) of the episode from the episode API (field `location` in the response)
- From that path, remove the appropriate root dir
- Append the resulting value to `videos/`. It will create a direct link to the video file ;)

The problem is that we don't know which root dir is used for each episode. So we have to loop through each root dir to see if it match. This has some edge cases, so I don't like (and use) that solution. For the moment, I only remove the default root dir. If the file is in an other one, too bad...

**Comment by miigotu** [comment]
`If SickRage wants to change something about the videos path tomorrow, it may break something for all the client apps.`

This is why I said I want to add a new separate path setup and calls, in order to not break current functionality.

Removing a root dir via api is not a good solution either, as you are actually changing the root dirs in SR that way, and breaking add show functionality inside SR for the user.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
