### ISSUE TITLE
[FR] Add "Low Quality" in Episode Status Managment

### ISSUE THREAD

**Issue by koper89** [SiCKRAGETV/sickrage-issues#1817]
Hi, 
From time to time i have to start from scratch and make new database, and after searching i found that i have a lot of unknown quality names. So to make it easier to change it would be nice to change all low quality status episodes in one action f.e. like in Episode Status Managment.

Best regards.

**Comment by neoatomic** [comment]
SickRage uses the information from the filename (or Database) to determinate what quality a file is. So when there is no info there and you create a new database the info is lost. 
So just add the info to the filename.

**Comment by koper89** [comment]
I know how sickrage resolve it but it's not what this request was about, it was mass managment according to episode status.

**Comment by fernandog** [comment]
We have tons of issues and FR.
Maybe will never be done

**Comment by miigotu** [comment]
We won't be adding a new status/quality, but we have an existing feature request for using mediainfo to detect quality directly from the file which will address this.
