### ISSUE TITLE
[APP SUBMITTED]: HTTPSConnectionPool(host='thepiratebay.gd', port=443): Read timed out.

### ISSUE THREAD

**Issue by wishx** [SiCKRAGETV/sickrage-issues#1819]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-24-generic-x86_64-with-LinuxMint-17-qiana**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@e6c4cfd6546b74d5527361f6f0bdc3adc232bdb0
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-70591 :: [ThePirateBay] :: Error while searching ThePirateBay, skipping: error HTTPSConnectionPool(host='thepiratebay.gd', port=443): Read timed out.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
As it says: time out
