### ISSUE TITLE
[APP SUBMITTED]: u'Orange.Is.The.New.Black.S03E04.WEBRip.x264-Abjex'

### ISSUE THREAD

**Issue by SpecialKeezie** [SiCKRAGETV/sickrage-issues#1821]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@d185980c89055f7179deec708141710ce386a572
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: Orange.Is.The.New.Black.S03E04.WEBRip.x264-Abjex
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@SpecialKeezie Please add logs. Without we cant do anything.

**Comment by fernandog** [comment]
no reply, closing
