### ISSUE TITLE
Can no longer add shows

### ISSUE THREAD

**Issue by andyblac** [SiCKRAGETV/sickrage-issues#1824]
SR Version:	BRANCH: (master) / COMMIT: (e6c4cfd6546b74d5527361f6f0bdc3adc232bdb0) 

the hover over 'Shows' no longer shows drop down menu, so there is no longer anyway to add shows etc.

**Comment by fernandog** [comment]
you need to enter Shows page then click "Add shows" then click the one that you want

@miigotu

**Comment by andyblac** [comment]
ahh, ok sorry did not see that at first.
