### ISSUE TITLE
Episode names with an apostrophe not postprocessing

### ISSUE THREAD

**Issue by dennisjanssen** [SiCKRAGETV/sickrage-issues#1826]
When having downloaded an episode with an apostrophe, the post processing seems to mess it up. It did so with a recent OITNB episode, now again with Game of Thrones:
```
2015-06-15 19:06:51 WARNING  POSTPROCESSER :: [/media/1TB-DISK/torrents/downloads/Game.of.Thrones.S05E10.HDTV.x264-KILLERS/Game.of.Thrones.S05E10.HDTV.x264-KILLERS.mp4 : Processing failed: Unable to move the files to their new home]
2015-06-15 19:06:51 WARNING  POSTPROCESSER :: Problem(s) during processing, failed the following files/folders:  
2015-06-15 19:06:51 WARNING  POSTPROCESSER :: Processing failed for /media/1TB-DISK/torrents/downloads/Game.of.Thrones.S05E10.HDTV.x264-KILLERS/Game.of.Thrones.S05E10.HDTV.x264-KILLERS.mp4: Unable to move the files to their new home
AAOSError: [Errno 22] Invalid argument: '/media/1TB-DISK/Series/Game of Thrones/Season 5/Game of Thrones - S05E10 - Mother\xe2\x80\x99s Mercy.mp4'
AA    fout = os.open(dst, WRITE_FLAGS)
AA  File "/home/osmc/sickbeard/lib/shutil_custom/__init__.py", line 42, in copyfile_custom
AA    result = func(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
AA  File "/home/osmc/sickbeard/sickbeard/encodingKludge.py", line 73, in ek
AA    ek.ek(shutil.copyfile, srcFile, destFile)
AA  File "/home/osmc/sickbeard/sickbeard/helpers.py", line 387, in copyFile
AA    copyFile(srcFile, destFile)
AA  File "/home/osmc/sickbeard/sickbeard/helpers.py", line 399, in moveFile
AA    helpers.moveFile(cur_file_path, new_file_path)
AA  File "/home/osmc/sickbeard/sickbeard/postProcessor.py", line 341, in _int_move
AATraceback (most recent call last):
2015-06-15 19:06:51 ERROR    POSTPROCESSER :: Unable to move file /media/1TB-DISK/torrents/downloads/Game.of.Thrones.S05E10.HDTV.x264-KILLERS/Game.of.Thrones.S05E10.HDTV.x264-KILLERS.mp4 to /media/1TB-DISK/Series/Game of Thrones/Season 5/Game of Thrones - S05E10 - Mother’s Mercy.mp4: error 22 : Invalid argument
2015-06-15 19:06:50 INFO     POSTPROCESSER :: Release name (game.of.thrones.s05e10.hdtv.x264-killers) found from file (game.of.thrones.s05e10.hdtv.x264-killers.nfo)
2015-06-15 19:06:49 INFO     POSTPROCESSER :: Processing /media/1TB-DISK/torrents/downloads/Game.of.Thrones.S05E10.HDTV.x264-KILLERS/Game.of.Thrones.S05E10.HDTV.x264-KILLERS.mp4 (None)
```
Anyone a clue what this might be? Is it something in the code or am I missing an option?

**Comment by fernandog** [comment]
https://sickrage.tv/forums/forum/help-support/general-support/12825-ensuring-your-locale-s-are-set-properly-to-avoid-unicode-issues

**Comment by dennisjanssen** [comment]
I tried that, but I'm still not getting it processed properly. When I run 'locale', this is what I get though:
osmc@osmc:~$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by fernandog** [comment]
@dennisjanssen 

add to your .bashrc file

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

save, reboot.

check if LANGUAGE has value

**Comment by dennisjanssen** [comment]
Strangely, it does when I run it as root, it doesn't when I run it as osmc. Any thoughts?

And thanks for your help already!

**Comment by fernandog** [comment]
are you changing the .bashrc file inside /home/osmc ?

**Comment by dennisjanssen** [comment]
Oops. I didn't, but I'm still getting the same error I'm afraid. Both locales are now showing up okay. Error is still showing this line: AAOSError: [Errno 22] Invalid argument: '/media/1TB-DISK/Series/Game of Thrones/Season 5/Game of Thrones - S05E10 - Mother\xe2\x80\x99s Mercy.mp4'
Which probably isn't okay?

**Comment by fernandog** [comment]
@miigotu do you know what is wrong?

**Comment by miigotu** [comment]
Does SR run as osmc user?

**Comment by dennisjanssen** [comment]
Now I'm looking at it, it's run from root. But the locales for root seem to be okay:
root@osmc:/# locale
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8

**Comment by miigotu** [comment]
@fernandog So there is someplace in code we need to make sure filenames are stored in unicode strings, and never use str(filename). Also, .encode('utf-8') is bad, as it breaks non unicode locales.

**Comment by fernandog** [comment]
@miigotu looks like an issue in PP. File downloaded ok

**Comment by miigotu** [comment]
line 15 of lib/shutil_custom/__init__.py, try adding:
```
src = u'' + src
dst = u'' + dst
```

**Comment by dennisjanssen** [comment]
Right above "for fn in [src, dst]:" ?

**Comment by miigotu** [comment]
No, do it right under the line starting with def

**Comment by dennisjanssen** [comment]
Afraid it didn't change anything, or I might just be doing it wrong.

Here's the logs at the moment:
2015-06-15 23:27:08 WARNING  Thread-16 :: [/media/1TB-DISK/torrents/downloads/Game.of.Thrones.S05E10.HDTV.x264-KILLERS[rarbg]/Game.of.Thrones.S05E10.HDTV.x264-KILLERS.mp4 : Processing failed: Unable to move the files to their new home]
2015-06-15 23:27:08 WARNING  Thread-16 :: Problem(s) during processing, failed the following files/folders:  
2015-06-15 23:27:08 WARNING  Thread-16 :: Processing failed for /media/1TB-DISK/torrents/downloads/Game.of.Thrones.S05E10.HDTV.x264-KILLERS[rarbg]/Game.of.Thrones.S05E10.HDTV.x264-KILLERS.mp4: Unable to move the files to their new home
AAOSError: [Errno 22] Invalid argument: '/media/1TB-DISK/Series/Game of Thrones/Season 5/Game of Thrones - S05E10 - Mother\xe2\x80\x99s Mercy.mp4'
AA    fout = os.open(dst, WRITE_FLAGS)
AA  File "/home/osmc/sickbeard/lib/shutil_custom/__init__.py", line 44, in copyfile_custom
AA    result = func(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
AA  File "/home/osmc/sickbeard/sickbeard/encodingKludge.py", line 73, in ek
AA    ek.ek(shutil.copyfile, srcFile, destFile)
AA  File "/home/osmc/sickbeard/sickbeard/helpers.py", line 387, in copyFile
AA    copyFile(srcFile, destFile)
AA  File "/home/osmc/sickbeard/sickbeard/helpers.py", line 399, in moveFile
AA    helpers.moveFile(cur_file_path, new_file_path)
AA  File "/home/osmc/sickbeard/sickbeard/postProcessor.py", line 341, in _int_move
AATraceback (most recent call last):
2015-06-15 23:27:08 ERROR    Thread-16 :: Unable to move file /media/1TB-DISK/torrents/downloads/Game.of.Thrones.S05E10.HDTV.x264-KILLERS[rarbg]/Game.of.Thrones.S05E10.HDTV.x264-KILLERS.mp4 to /media/1TB-DISK/Series/Game of Thrones/Season 5/Game of Thrones - S05E10 - Mother’s Mercy.mp4: error 22 : Invalid argument
2015-06-15 23:27:06 INFO     Thread-16 :: Processing /media/1TB-DISK/torrents/downloads/Game.of.Thrones.S05E10.HDTV.x264-KILLERS[rarbg]/Game.of.Thrones.S05E10.HDTV.x264-KILLERS.mp4 (None)
2015-06-15 23:27:06 INFO     Thread-16 :: PostProcessing Path: /media/1TB-DISK/torrents/downloads

**Comment by miigotu** [comment]
@dennisjanssen try this:

sickbeard/postProcessor.py, line 311

from
`                new_file_name = new_base_name + '.' + cur_extension`
to
`                new_file_name = u'' + new_base_name + '.' + cur_extension`

**Comment by dennisjanssen** [comment]
Still the same error I'm afraid. Or did I have to remove the previous change before trying this?

**Comment by miigotu** [comment]
doesn't matter, but best to go back to original anyways.

Last test for tonight:

in sickbeard/helpers.py, lines 389 and 396

the text 
`srcFile, destFile`
to
`u'' + srcFile, u'' + destFile`

and if that doesnt work, try adding a `#` in front of line 397
like this:
`       # fixSetGroupID(destFile)`

**Comment by dennisjanssen** [comment]
Made those changes, each time restarting SickRage and manually post-processing (I'm guessing that's using the same process as the automatic one?), but still getting the same error. Maybe I'm doing something wrong? Or would it help to check out another branch and try again?

**Comment by miigotu** [comment]
Your pp setting is move or copy? I will make a dummy Game.of.Thrones.S05E10.HDTV.x264-KILLERS.mp4 and try to debug it from here.

**Comment by dennisjanssen** [comment]
It's move. I'll check out another branch in the meantime and see if that changes anything. Thanks again for your thorough help!

**Comment by miigotu** [comment]
also, is it using tvrage indexer or tvdb?

**Comment by dennisjanssen** [comment]
Judging from the icon with GoT, it's TVDB.

**Comment by miigotu** [comment]
Ok, Let me mess around with it and make sure I can reproduce.

**Comment by miigotu** [comment]
Damn, it works perfect for me.
Paste the output of:
`ls -l /media/1TB-DISK/torrents/downloads/Game.of.Thrones.S05E10.HDTV.x264-KILLERS/Game.of.Thrones.S05E10.HDTV.x264-KILLERS.mp4`

`ls -ld /media/1TB-DISK/Series/Game of Thrones/Season 5`

**Comment by miigotu** [comment]
Just want to check this, even though since SR is running as root there should be no permissions issues.

**Comment by miigotu** [comment]
Also, S05E10 doesn't already exist in `/media/1TB-DISK/Series/Game of Thrones/Season 5/` right?

**Comment by dennisjanssen** [comment]
osmc@osmc:~$ ls -l /media/1TB-DISK/torrents/downloads/Game.of.Thrones.S05E10.HDTV.x264-KILLERS\[rarbg\]/Game.of.Thrones.S05E10.HDTV.x264-KILLERS.mp4 
-rw-rw-rw- 1 osmc osmc 439837573 Jun 15 22:09 /media/1TB-DISK/torrents/downloads/Game.of.Thrones.S05E10.HDTV.x264-KILLERS[rarbg]/Game.of.Thrones.S05E10.HDTV.x264-KILLERS.mp4

osmc@osmc:~$ ls -ld /media/1TB-DISK/Series/Game\ of\ Thrones/Season\ 5/
drwxrwxrwx 2 osmc osmc 32768 Jun  8 20:37 /media/1TB-DISK/Series/Game of Thrones/Season 5/

Does that help?

**Comment by dennisjanssen** [comment]
And nope, doesn't exist yet.

**Comment by dennisjanssen** [comment]
I run the post-processor manually and check all the boxes to force it to replace the file anyway, so I'm guessing that shouldn't be an issue?

**Comment by miigotu** [comment]
Yep, thats fine.

**Comment by miigotu** [comment]
Try this:
SickBeard.py, line 155
From:
`            sickbeard.SYS_ENCODING = locale.getpreferredencoding()`
To:
`            sickbeard.SYS_ENCODING = locale.getdefaultlocale()`

**Comment by miigotu** [comment]
Tired, can't think anymore. osmc has something broken but I want to work around it x.X

**Comment by dennisjanssen** [comment]
Now I can't seem to launch SickRage anymore. Getting this error:
Traceback (most recent call last):
  File "sickbeard/SickBeard.py", line 550, in <module>
    SickRage().start()
  File "sickbeard/SickBeard.py", line 176, in start
    "or find another way to force Python to use " + sickbeard.SYS_ENCODING + " for string encoding.")
TypeError: cannot concatenate 'str' and 'tuple' objects

**Comment by miigotu** [comment]
eh, just revert to a clean copy, I was tired and had you use an incorrect function there.

**Comment by dennisjanssen** [comment]
I tried to check the Git Reset checkmark but I'm not sure if that's doing anything. Is there a quick way to revert to a clean copy from the interface?

**Comment by fernandog** [comment]
@dennisjanssen no

just stop SR and run inside SickRage:
git reset --hard HEAD

**Comment by miigotu** [comment]
That wont remove the unstaged changes xD.

`git checkout -- .` is what you want, don;t forget the period at the end.

**Comment by dennisjanssen** [comment]
Okay, did that, and I checked if the changes reverted, which it did. Nothing changed on the error though, after restarting SickRage.

**Comment by miigotu** [comment]
let's make sure it's not an osmc problem first.
Try this in terminal:
`dd if=/dev/zero of='Downloads/Game of Thrones - S05E10 - Mother’s Mercy.mp4' bs=1 count=1`

**Comment by dennisjanssen** [comment]
I'm getting this: 
dd: failed to open ‘Downloads/Game of Thrones - S05E10 - Mother\’s Mercy.mp4’: No such file or directory

**Comment by miigotu** [comment]
oops:
`dd if=/dev/zero of='Game of Thrones - S05E10 - Mother’s Mercy.mp4' bs=1 count=1`
I guess you didnt have a Downloads directory there, xD

**Comment by dennisjanssen** [comment]
And the file is named differently on my end, since it still has to be renamed. I'm guessing that's done while moving it too. So I'll run dd if=/dev/zero of=/media/1TB-DISK/torrents/downloads/Game.of.Thrones.S05E10.HDTV.x264-KILLERS\[rarbg\]/Game.of.Thrones.S05E10.HDTV.x264-KILLERS.mp4 

Running...

dd: writing to ‘/media/1TB-DISK/torrents/downloads/Game.of.Thrones.S05E10.HDTV.x264-KILLERS[rarbg]/Game.of.Thrones.S05E10.HDTV.x264-KILLERS.mp4’: File too large
8388608+0 records in
8388607+1 records out
4294967295 bytes (4.3 GB) copied, 173.271 s, 24.8 MB/s

**Comment by miigotu** [comment]
nono, lol. The bug is because of the outfile. ie: the file with the new name.

I want to make sure osmc can create files with odd unicode characters in the filenames.

**Comment by miigotu** [comment]
Also, you just zero'd out your downloaded file tsk tsk.

**Comment by miigotu** [comment]
yay for 4.3GB of zeros

**Comment by dennisjanssen** [comment]
Crap :)
So... I need to rename the file? Do I try 'mv /media/1TB-DISK/torrents/downloads/Game.of.Thrones.S05E10.HDTV.x264-KILLERS[rarbg]/Game.of.Thrones.S05E10.HDTV.x264-KILLERS.mp4 /media/1TB-DISK/torrents/downloads/Game.of.Thrones.S05E10.HDTV.x264-KILLERS[rarbg]/Game of Thrones - S05E10 - Mother’s Mercy.mp4' ?

**Comment by dennisjanssen** [comment]
Okay, I guess not:
mv: target ‘Mercy.mp4’ is not a directory

**Comment by miigotu** [comment]
You are typing out what I wrote instead of copying and paste?

You cannot type the special apostrophe.

**Comment by dennisjanssen** [comment]
dd: failed to open ‘Game of Thrones - S05E10 - Mother\’s Mercy.mp4’: Invalid argument

I ran the command inside the folder the episode was in and got that back. But the file in that folder is named Game.of.Thrones.S05E10.HDTV.x264-KILLERS.mp4, so I'm not sure if that's normal or not?

**Comment by miigotu** [comment]
@dennisjanssen Tried to reproduce this lately? I think its fixed today with changes to ek.ek

**Comment by dennisjanssen** [comment]
"Moving file from /media/1TB-DISK/torrents/downloads/Game.of.Thrones.S05E10.HDTV.x264-KILLERS[ettv]/Game.of.Thrones.S05E10.HDTV.x264-KILLERS.mp4 to /media/1TB-DISK/Series/Game of Thrones/Season 5/Game of Thrones - S05E10 - Mother's Mercy.mp4
Processing succeeded for /media/1TB-DISK/torrents/downloads/Game.of.Thrones.S05E10.HDTV.x264-KILLERS[ettv]/Game.of.Thrones.S05E10.HDTV.x264-KILLERS.mp4"

Fixed it! Awesome work, guys, thanks for your enormous effort in this!
