### ISSUE TITLE
[APP SUBMITTED]: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by gtranche** [SiCKRAGETV/sickrage-issues#1827]
### INFO
Python Version: **2.6.6 (r266:84292, Jan 22 2014, 09:42:36) [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]**
Operating System: **Linux-2.6.32-279.19.1.el6.x86_64-x86_64-with-centos-6.6-Final**
Locale: UTF8
Branch: **master**
Commit: SiCKRAGETV/SickRage@e6c4cfd6546b74d5527361f6f0bdc3adc232bdb0
Link to Log: https://gist.github.com/29aee70f84a4b4351cef
### ERROR
```
SEARCHQUEUE-BACKLOG-272644 :: [T411] :: Error while searching T411, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@miigotu probaly related to https://github.com/SiCKRAGETV/sickrage-issues/issues/1814 ?

**Comment by gtranche** [comment]
Centos comes with an old version of pyOpenSSL, just remove the package ( yum remove pyOpenSSL )
Install pip ( yum -y install python-pip )
Install pyOpenssl ( ip install pyOpenSSL )
restart sickrage et it's ok.
You need some packages to compile pyOpenSSL (gcc,openssl-devel,libffi-devel)
