### ISSUE TITLE
TypeError: 'bool' object is not iterable

### ISSUE THREAD

**Issue by tjw1184** [SiCKRAGETV/sickrage-issues#1828]
On synology, receiving error quite often on retries after latest update
BRANCH: (master) / COMMIT: (e6c4cfd6546b74d5527361f6f0bdc3adc232bdb0) 
Python Version:	2.7.10 (default, Jun 3 2015, 20:43:13)

AA
AATypeError: 'bool' object is not iterable
AA    for curResult in individualResults:
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/search.py", line 576, in searchProviders
AA    searchResult = search.searchProviders(self.show, self.segment, True, self.downCurQuality)
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/search_queue.py", line 269, in run
2015-06-15 19:32:31 INFO     SEARCHQUEUE-RETRY-164301 :: Executed query: [SELECT episode FROM tv_episodes WHERE showid = XXXX AND season in  1]

**Comment by neoatomic** [comment]
No problems here on my Synology.
Please post a full log, i cant see what SR is doing here.

**Comment by fernandog** [comment]
no reply, closing
