### ISSUE TITLE
[Feature Request] Add Scheduled Automatic Backups

### ISSUE THREAD

**Issue by raymondtrueman** [SiCKRAGETV/sickrage-issues#1829]
Feature request to be able to provide a path and a schedule so that backups can automatically be created on a schedule to the path provided.

The user should also be able to specify how many backups to keep where-after old ones will be automatically deleted

**Comment by NicoLeOca** [comment]
+1

**Comment by royteeuwen** [comment]
+1

**Comment by OmgImAlexis** [comment]
+1

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
