### ISSUE TITLE
[APP SUBMITTED]: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by Twanislas** [SiCKRAGETV/sickrage-issues#1830]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@e6c4cfd6546b74d5527361f6f0bdc3adc232bdb0
Link to Log: https://gist.github.com/f8abdd15f8925f6ea22d
### ERROR
```
SEARCHQUEUE-BACKLOG-72108 :: [T411] :: Error while searching T411, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Sandrus** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@e6c4cfd6546b74d5527361f6f0bdc3adc232bdb0
Link to Log: https://gist.github.com/8f48b06dcb1fdc538e6e
### ERROR
```
SEARCHQUEUE-MANUAL-281537 :: [T411] :: Error while searching T411, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Problem looks to be the special characters. "Enquêtes spéciales" After that all other errors appear.
So prevent using special characters.

**Comment by fernandog** [comment]
before running SR, run "chcp 65001"

**Comment by Twanislas** [comment]
@neoatomic : So this is how you solve an issue ? Does that means that you don't even care about foreign languages ? At least Fernando came up with some hint towards a solution...

@fernandog : I did try that but it provokes some other errors, I'll try to grab more information as soon as I have time.

Anyway, thank you both for your consideration ! ;)

**Comment by miigotu** [comment]
If changing the codepage gave errors, it is a problem on your system, not sickrage.

**Comment by Twanislas** [comment]
Hi guys !

I use some vbs script I googled to start SickRage without having a terminal window open, adding the chcp makes it fail so I tried running it in a normal terminal window. It runs well except I cannot access shows pages anymore... Here is the error found in the logs :

```
2015-06-19 09:03:14 Thread-117 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickBeard\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickBeard\sickbeard\webserve.py", line 1296, in displayShow
    return t.respond()
  File "C:\SickBeard\cache\cheetah\_SickBeard_gui_slick_interfaces_default_displayShow_tmpl.py", line 1315, in respond
    if _v is not None: write(_filter(_v))
  File "C:\SickBeard\sickbeard\webserve.py", line 95, in filter
    logger.log(u'Unable to decode using {0}, trying utf-8. Error is: {1}'.format(sickbeard.SYS_ENCODING, ex(e)),logger.DEBUG)
  File "C:\SickBeard\sickbeard\exceptions.py", line 49, in ex
    e_message = e_message + " : " + fixed_arg
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 18: invalid continuation byte
```
@miigotu : that was the case with my vbs script, hence the test in a normal terminal. This error here is new for me :/

Still, I do not have anymore errors about "Enquêtes spéciales", which is a step forward :)

Thanks for your help !

**Comment by bioshock47** [comment]
Fernando, you mark
before running SR, run "chcp 65001"
How we can run chcp? I have a QNAP and i don't know how to run it.
Thanks
Regards
