### ISSUE TITLE
Show incorrectly matching episodes

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#1831]
### INFO
Python Version: 2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]
Operating System: Linux-3.13.0-48-generic-x86_64-with-Ubuntu-14.04-trusty
Locale: unknown
Branch: master
Commit: SiCKRAGETV/SickRage@e6c4cfd
Link to Log: https://gist.github.com/OmgImAlexis/57d59c77a959fc21932d

S01E02 is getting marked as S01E03 and it goes up from there by 2s so S01E03 is being seen as S01E05, I used the TheTVDB with filebot to name the files before they were processed and used TheTVDB as the provider when I added the show, the episode number and name also match up correctly on the show page on both TheTVDB and Sickrage but it then moves it to the incorrect episode when it post-processes.

**Comment by neoatomic** [comment]
@OmgImAlexis Have you try'd force full update under the show page.? It should refresh all data/files then.
Also take a look if you have scene numbering enabled/disabled. In the worst case you have to manually enter the episode numbers.

**Comment by OmgImAlexis** [comment]
As soon as I've backed up the files I'll have a try, I think it may have something to do with the fact that the show airs episodes as double episodes in a single slot so they're like ``episode 1a`` and then ``episode 1b`` but on TheTVDB, wikipedia, IMDB, etc. they're all listed as separate episodes.

I'm just guessing at that though, I have 80+ other shows and I've been using this since for months and months and never had a single issue even similar to this.

**Comment by OmgImAlexis** [comment]
Moving the shows to the completed folder then adding the show seems to have fixed it. There must be some weird issue with post processing.

**Comment by neoatomic** [comment]
Think the old names where still in the DB , so SR falls back on those.?
Anyway glad that solved it.

**Comment by OmgImAlexis** [comment]
I don't think so because the episodes were named like so ``Paw Patrol - S01E02 Pups Save a Train.mp4`` and were being picked up as 1x03 in the logs and then moved from the processing folder to the completed folder as ``Paw Patrol - S01E03 Pup Pup Boogie.mp4``. I'll turn on full logs tomorrow and backup my show and try to get some details for you guys. I'm hoping it's a Sickrage/beard issue and not a TheTVDB issue.
