### ISSUE TITLE
When using Web notifications only strings should be shown, not HTML

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#1832]
When Web notifications are enabled the notifications still show up with the ``p`` tag around the text. I'm pretty sure the only time I've seen this issue is when I'm deleting shows.

**Comment by fernandog** [comment]
what are you talking about?! I see no logs, no prints, nothing. What should we do with only this information?

**Comment by OmgImAlexis** [comment]
I didn't think it needed explaining but [this](http://i.imgur.com/vJgKt7z.png) is what I'm talking about.
At times I get those types of notifications with ``<p></p>`` tags wrapped around the contents of the message.

**Comment by fernandog** [comment]
We have tons of messages. We need to know which one has that

**Comment by OmgImAlexis** [comment]
I'll try and reproduce it, I know it was something to do with deleting a show. They pop up too quickly too see a lot of the time. :\

**Comment by neoatomic** [comment]
@OmgImAlexis Think i know what you mean. 
If i recall right it happens during an update. the notification say something like "<p> creating backup <p>.
Thought it was my (exotic) browser not handling the notification text correctly. But if more browsers have this it might be a code problem.
 
I'm currently running the newest commit so cant test...

**Comment by fernandog** [comment]
the UI notification don't send any HTML:

https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/versionChecker.py#L83

**Comment by miigotu** [comment]
./sickbeard/webserve.py:        ui.notifications.message('<b>%s</b> has been %s' % (showObj.name,('resumed', 'paused')[showObj.paused]))
./sickbeard/webserve.py:        ui.notifications.message('<b>%s</b> has been %s %s' %

**Comment by miigotu** [comment]
Grr, it didnt show up here.

**Comment by fernandog** [comment]
Bug / Issue then?

**Comment by miigotu** [comment]
Yep, no html should be in those.

**Comment by OmgImAlexis** [comment]
"<b>has been deleted with all related media</b>"

Found another.
https://github.com/SiCKRAGETV/SickRage/blob/52a6c31cdf545c4e2fd22925a92a3d0824c429cf/sickbeard/webserve.py#L1570

**Comment by miigotu** [comment]
@OmgImAlexis Make sure you are checking develop branch lol. Those were changed like 2 days ago xD
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/webserve.py#L1570
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/webserve.py#L1543
