### ISSUE TITLE
[APP SUBMITTED]: Thread-45 :: git fetch origin returned : error: Unable to append to .git/logs/refs/remotes/origin/master: Permission denied
From https://github.com/SiCKRAGETV/SickRage
 ! 42b8d5a..e6c4cfd  master     -> origin/master  (unable to update local ref)

### ISSUE THREAD

**Issue by demck85** [SiCKRAGETV/sickrage-issues#1833]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-38-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@42b8d5a9c71c87fcde301967b6254ef08c3093ac
Link to Log: https://gist.github.com/3b226eeecb1e80e808bd
### ERROR
```
Thread-45 :: git fetch origin returned : error: Unable to append to .git/logs/refs/remotes/origin/master: Permission denied
From https://github.com/SiCKRAGETV/SickRage
 ! 42b8d5a..e6c4cfd  master     -> origin/master  (unable to update local ref)
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1506#issuecomment-99586715
