### ISSUE TITLE
After the HTTPS Plex update Sickrage can no longer contact it

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#1834]
### INFO
Python Version: 2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]
Operating System: Linux-3.13.0-48-generic-x86_64-with-Ubuntu-14.04-trusty
Locale: unknown
Branch: master
Commit: SiCKRAGETV/SickRage@e6c4cfd
````
AA
AACache-Control: no-cache
AAX-Plex-Protocol: 1.0
AAConnection: close
AAContent-Type: text/html
2015-06-17 00:49:56 WARNING  Thread-45 :: PLEX: Error while trying to contact Plex Media Server: http error : error 401 : Unauthorized : error Content-Length: 91
````

**Comment by neoatomic** [comment]
@OmgImAlexis Try to re-add your account details. "Unauthorized" usually means bad user/password.
Also are you using encrypted passwords.? If so disable and add user-name/password. (You can also do this directly in the config.ini )

**Comment by OmgImAlexis** [comment]
Looks like Sickrage now requires the auth token to be filled in, this wasn't needed at all before the HTTPS update. I was using just the IP before now.

**Comment by OmgImAlexis** [comment]
For those that find this visit view-source:https://plex.tv/web/ after you've signed in, view the page source and then copy the text between the ``"`` on this line ``myPlexAccessToken`` then paste it to the Auth token section on the /config/notifications/ of Sickrage.

**Comment by neoatomic** [comment]
Ok, so in short. : The new Plex versions need the Token for HTTPS, but the older versions still work without it.
