### ISSUE TITLE
[APP SUBMITTED]: <urlopen error timed out>

### ISSUE THREAD

**Issue by razlebol** [SiCKRAGETV/sickrage-issues#1837]
### INFO
Python Version: **2.7.6 (default, Apr  3 2014, 09:45:36) [GCC 4.5.3]**
Operating System: **Linux-3.4.90-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@e6c4cfd6546b74d5527361f6f0bdc3adc232bdb0
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: error timed out
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
simple time out

**Comment by OmgImAlexis** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-57-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@89efb07b1e482a6c8b21b0ac4e18e069d25c856e
Link to Log: https://gist.github.com/cdc00f9e0c5245b7a475
### ERROR
```
Thread-216 :: Boxcar2 notification failed.error timed out
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by OmgImAlexis** [comment]
@miigotu @fernandog I'm getting this randomly from Boxcar2, seems to be a timeout issue with them and not anything to do with me. Kind of hard to reproduce as I get this as often with 1 episode being sent to Boxcar2 vs 100s being sent.

**Comment by OmgImAlexis** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-57-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@30435190ef8880901df555bcda0d46902ea81fb5
Link to Log: https://gist.github.com/1d884b5d0961506d6839
### ERROR
```
POSTPROCESSER :: Boxcar2 notification failed.error timed out
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@OmgImAlexis PP stopped because of that?

**Comment by OmgImAlexis** [comment]
@fernandog I think so, not sure. I woke up to 200+ warnings/errors.

**Comment by miigotu** [comment]
@OmgImAlexis according to your other bug report your internet was out for who knows how long.

**Comment by OmgImAlexis** [comment]
@miigotu it's still stopped PP from memory though. No fails on that should stop it, it should just skip the file/notification and keep going if it fails.

**Comment by miigotu** [comment]
That bug should have been fixed 2 days ago:
https://github.com/SiCKRAGETV/SickRage/commit/a1cc0cba3a3f1a7a225f329a1469a5b42e01fa26

**Comment by miigotu** [comment]
Actually I dont see the boxcar2 notifier called there. Will look further into it.
