### ISSUE TITLE
[APP SUBMITTED]: 'str' object does not support item assignment

### ISSUE THREAD

**Issue by andyblac** [SiCKRAGETV/sickrage-issues#1838]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@e6c4cfd6546b74d5527361f6f0bdc3adc232bdb0
Link to Log: https://gist.github.com/2279b7263d0ef679fcce
### ERROR
```
Thread-52 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 998, in getTraktToken
    response = trakt_api.traktToken(trakt_pin)
  File "/volume1/@appstore/sickrage/var/SickRage/lib/trakt/trakt.py", line 49, in traktToken
    resp = self.traktRequest('oauth/token', data=data,  headers=headers, url=self.auth_url , method='POST', count=count)
  File "/volume1/@appstore/sickrage/var/SickRage/lib/trakt/trakt.py", line 102, in traktRequest
    return self.traktRequest(path, data, url, method)
  File "/volume1/@appstore/sickrage/var/SickRage/lib/trakt/trakt.py", line 78, in traktRequest
    headers['Authorization'] = 'Bearer ' + sickbeard.TRAKT_ACCESS_TOKEN
TypeError: 'str' object does not support item assignment

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
"Unauthorized. Please check your Trakt settings"
As the errors says. Check you account settings for Trakt. And have you set the token.?

**Comment by miigotu** [comment]
Even though the bug is exposed by pekac, we should not be dumping to exception and traceback on misconfiguration. SiCKRAGETV/SickRage#1969 is intended to adress this, no?

**Comment by fernandog** [comment]
@miigotu yes

for TRAKT, TRAKT_ACCESS_TOKEN field it's mandatory. we shouln't run trakt code if it's empty

**Comment by miigotu** [comment]
Should be an easy fix then... somebody make a PR =P

**Comment by fernandog** [comment]
I can do it later.

**Comment by fernandog** [comment]
@Thraxis why do you are adding Bearer to the token? 
https://github.com/SiCKRAGETV/SickRage/blob/develop/lib/trakt/trakt.py#L78

You already check if token is none. so why this error in this issue?
thanks!

**Comment by miigotu** [comment]
You should be raising an exception. Currently it continues if there is no token. Something like this?
```
if None == sickbeard.TRAKT_ACCESS_TOKEN:
    raise traktException("No access token")

headers['Authorization'] = 'Bearer ' + sickbeard.TRAKT_ACCESS_TOKEN
```
