### ISSUE TITLE
[Feature Request] Replace path and line numbers with links with issue submitter

### ISSUE THREAD

**Issue by miigotu** [SiCKRAGETV/sickrage-issues#1839]
Parse tracebacks in issue submitter to links, to help debug faster.
`File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/common.py", line 264`
Becomes:
[sickbeard/common.py, Line 264](https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/common.py#L264)

**Comment by fernandog** [comment]
@miigotu shouldn't we set a initial value for status?

**Comment by miigotu** [comment]
-1 is status None, which cannot exist in the database, because when adding the episode the status is set. The purpose of -1 is to force an error when it is used before it is set

**Comment by fernandog** [comment]
@miigotu can this happen when user don't select option "default ep status" when adding show??

**Comment by miigotu** [comment]
Nope.  Besides, status is checked if it is -1 on [Line 259](https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/common.py#L259)

Something is passing status as a string instead of an int.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
