### ISSUE TITLE
[APP SUBMITTED]: CHECKVERSION :: git fetch origin returned : error: RPC failed; result=56, HTTP code = 0
fatal: The remote end hung up unexpectedly

### ISSUE THREAD

**Issue by ghiglie** [SiCKRAGETV/sickrage-issues#1840]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.19.4-unRAID-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@e6c4cfd6546b74d5527361f6f0bdc3adc232bdb0
Link to Log: https://gist.github.com/df42601412368c2b2c2c
### ERROR
```
CHECKVERSION :: git fetch origin returned : error: RPC failed; result=56, HTTP code = 0
fatal: The remote end hung up unexpectedly
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
github issues
