### ISSUE TITLE
Ignored Words not working #1560

### ISSUE THREAD

**Issue by pct00** [SiCKRAGETV/sickrage-issues#1841]
duplicate as i cant reopen...

still happening with latest dev version

**Comment by fernandog** [comment]
follow guidelines as always. you know without logs there's nothing we can do
post info and will repoen

**Comment by pct00** [comment]
Hi @fernandog 

full log with debug as requested on http://pastebin.com/e1GEKxCL


my config file ignore words
ignore_words = "german,french,core2hd,dutch,swedish,reenc,MrLss,vostfr,italian,www,vostfr,swesub,greman,ita,nl,FRENCH,SWESUB,www.,subtitulado,spanish,272p,ipod,norsub,swesubs,SWESUB,ChameE,Lektor"

**Comment by miigotu** [comment]
Found another ignored/required words bug, pushed a little while ago to develop.
