### ISSUE TITLE
[APP SUBMITTED]: int() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by dsoms** [SiCKRAGETV/sickrage-issues#1842]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-3.18.13-1-osmc-armv7l-with-debian-8.1**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@810b82110ce639ae07e49e5a8b80f90b714a28af
Link to Log: https://gist.github.com/e829b3fdc03e8f500d8b
### ERROR
```
Thread-51 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/osmc/.sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/home/osmc/.sickrage/sickbeard/webserve.py", line 1450, in editShow
    showObj.default_ep_status = int(defaultEpStatus)
TypeError: int() argument must be a string or a number, not 'NoneType'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@dsoms Open your config.ini file and post the value of the field default Ep Status

**Comment by fernandog** [comment]
@dsoms please update develop branch and try again please

**Comment by miigotu** [comment]
@fernandog I think this didn't need removed.

**Comment by dsoms** [comment]
@fernandog It works for me. Thanks!

**Comment by Coopeh** [comment]
I get this exact error when trying to add a Scene Exception. On the current develop branch.

**Comment by miigotu** [comment]
@Coopeh It cannot be the same traceback, because the line that caused that is commented out now.
Please provide us with your error and traceback from the log, thanks.

**Comment by Coopeh** [comment]
2015-06-22 23:25:55 Thread-479 :: Failed doing webui callback: Traceback (most recent call last):
  File "/Volumes/Macintosh HD/Media/Software/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/Volumes/Macintosh HD/Media/Software/SickRage/sickbeard/webserve.py", line 1450, in editShow
    #showObj.default_ep_status = int(defaultEpStatus)
TypeError: int() argument must be a string or a number, not 'NoneType'

Still the same line and includes the commented line also.

**Comment by miigotu** [comment]
@Coopeh delete cache/cheetah

**Comment by Coopeh** [comment]
Fixed, thanks.
