### ISSUE TITLE
[APP SUBMITTED]: 'link'

### ISSUE THREAD

**Issue by pct00** [SiCKRAGETV/sickrage-issues#1843]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@347571fb55710163fe5958761bcc450045c4c3a5
Link to Log: https://gist.github.com/e037e5495d3b23f50ac1
### ERROR
```
SEARCHQUEUE-BACKLOG-79511 :: Failed to parsing KickAssTorrents Traceback: Traceback (most recent call last):
  File "C:\Users\Pedro\Desktop\SickRage-master\sickbeard\providers\kat.py", line 238, in _doSearch
    link = item['link']
  File "C:\Users\Pedro\Desktop\SickRage-master\lib\feedparser\feedparser.py", line 353, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'link'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
please update

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1743
