### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/mnt/downloads/DONE/tvshow/Gravity Falls - S01E03 Headhunters.mkv'

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#1844]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-48-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@52a6c31cdf545c4e2fd22925a92a3d0824c429cf
No Log available with ERRORS: 
### ERROR
```
Thread-25 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/media/sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/home/media/sickrage/sickbeard/webserve.py", line 2174, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/home/media/sickrage/sickbeard/processTV.py", line 203, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/home/media/sickrage/sickbeard/processTV.py", line 498, in process_media
    result.result = processor.process()
  File "/home/media/sickrage/sickbeard/postProcessor.py", line 880, in process
    existing_file_status = self._checkForExistingFile(ep_obj.location)
  File "/home/media/sickrage/sickbeard/postProcessor.py", line 132, in _checkForExistingFile
    if ek.ek(os.path.getsize, existing_file) > ek.ek(os.path.getsize, self.file_path):
  File "/home/media/sickrage/sickbeard/encodingKludge.py", line 73, in ek
    result = func(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
  File "/usr/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '/mnt/downloads/DONE/tvshow/Gravity Falls - S01E03 Headhunters.mkv'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by OmgImAlexis** [comment]
Oops, I meant to comment on this.

I get this issue with files even if they exist, this usually only happens with files over 2GB. I don't have any issues at all with smaller files.

@miigotu Why was this closed?

**Comment by miigotu** [comment]
Either the file was already processed by the automatic post processor and you had a forced post process running, or the other way around, or you have permissions wrong.

**Comment by OmgImAlexis** [comment]
Is it possible for the automatic post processor to start while a manual one is running? If that's the case then that'd explain it.

**Comment by miigotu** [comment]
PP runs so often there really isnt any reason to run it manually beside impatience xD

**Comment by OmgImAlexis** [comment]
I'd rather get errors than have a house filled with angry people wanting the shows that just downloaded on Plex. haha
