### ISSUE TITLE
AttributeError: 'WebRoot' object has no attribute 'api

### ISSUE THREAD

**Issue by LennyM8472** [SiCKRAGETV/sickrage-issues#1845]
Hi,

can anybody give me some input what the problem here is?
I searched all settings and configs for the presumed key (802e82eff763d3d5f972410b7102beed), but can't find it anywhere.
```
2015-06-18 06:39:39 INFO     SEARCHQUEUE-BACKLOG-274894 :: Performing season pack search for The World’s Biggest Ship
AA
AAAttributeError: 'WebRoot' object has no attribute 'api/802e82eff763d3d5f972410b7102beed'
AA    method = getattr(self, route)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 241, in get
AA
AAAttributeError: 'WebRoot' object has no attribute 'api/802e82eff763d3d5f972410b7102beed'
AA    method = getattr(self, route)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 241, in get
```

**Comment by miigotu** [comment]
You have a custom newznab or torrent provider defined without a url maybe?

**Comment by LennyM8472** [comment]
I only have a single newznab provider - with url and different key.
I think the key belongs to an old provider / old newznab entry - but I can't find the entry/settings for it anywhere (in the dropdown is only my correct provider)?

Is there a way to manually delete the key or so? (802e82eff763d3d5f972410b7102beed)

thanks

**Comment by miigotu** [comment]
check your config.ini

**Comment by LennyM8472** [comment]
Hi locked again at the config.
The key is no where to find.
All other entries look correct.

Very strange.... where does the key come from?!

**Comment by neoatomic** [comment]
In the config.ini are all api keys stored so it must be located there. Or is an external program trying to access SickRage with that key.? And as you are using a QNAP don't use https in the provider url's. 

Otherwise you have to do a clean/fresh installation...

**Comment by LennyM8472** [comment]
this is really strange, I can't find the key in any config file. https is not in the provider address.
Any idea where to search next?

**Comment by neoatomic** [comment]
If the above suggestions doesn't work than the only thing i can think of is a bad installation.
So a clean install and start with a new config.ini and sickbeard.db will fix that.
Also next time follow the guideline for posting an issue.: 
https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket

**Comment by miigotu** [comment]
@LennyM8472 try deleting cache/indexers/* cache/sessions/* cache/rss/* and cache.db

**Comment by LennyM8472** [comment]
nope.... not working either.

Sooooo strange

**Comment by miigotu** [comment]
Is that hash in `http://dt.local:9999/config/general/` on the interface tab in the `API Key` field?

**Comment by LennyM8472** [comment]
miigotu what do you mean? where do I have to look for that?

**Comment by neoatomic** [comment]
Go to General Configuration --> Interface. 
Then browse down and look under API key if that is the mysterious api key.

**Comment by LennyM8472** [comment]
unfortunately not

**Comment by LennyM8472** [comment]
I now switched off all search providers and the log still gets the error message with the mysterious key.

2015-06-19 19:17:21 INFO     POSTPROCESSER :: Processing completed
2015-06-19 19:17:21 INFO     POSTPROCESSER :: PostProcessing Path: /share/MD0_DATA/Multimedia/Video/temp_transmission
AA
AAAttributeError: 'WebRoot' object has no attribute 'api/802e82eff763d3d5f972410b7102beed'
AA    method = getattr(self, route)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 241, in get
AA
AAAttributeError: 'WebRoot' object has no attribute 'api/802e82eff763d3d5f972410b7102beed'
AA    method = getattr(self, route)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 241, in get
AA
AAAttributeError: 'WebRoot' object has no attribute 'api/802e82eff763d3d5f972410b7102beed'
AA    method = getattr(self, route)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 241, in get
AA
AAAttributeError: 'WebRoot' object has no attribute 'api/802e82eff763d3d5f972410b7102beed'
AA    method = getattr(self, route)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 241, in get
AA
AAAttributeError: 'WebRoot' object has no attribute 'api/802e82eff763d3d5f972410b7102beed'
AA    method = getattr(self, route)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 241, in get
AA
AAAttributeError: 'WebRoot' object has no attribute 'api/802e82eff763d3d5f972410b7102beed'
AA    method = getattr(self, route)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 241, in get
AA
AAAttributeError: 'WebRoot' object has no attribute 'api/802e82eff763d3d5f972410b7102beed'
AA    method = getattr(self, route)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 241, in get
AA
AAAttributeError: 'WebRoot' object has no attribute 'api/802e82eff763d3d5f972410b7102beed'
AA    method = getattr(self, route)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 241, in get
AA
AAAttributeError: 'WebRoot' object has no attribute 'api/802e82eff763d3d5f972410b7102beed'
AA    method = getattr(self, route)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 241, in get
AA
AAAttributeError: 'WebRoot' object has no attribute 'api/802e82eff763d3d5f972410b7102beed'
AA    method = getattr(self, route)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 241, in get
2015-06-19 19:13:57 INFO     SEARCHQUEUE-BACKLOG-275150 :: No needed episodes found during backlog search for: [Save With Jamie]
2015-06-19 19:13:57 WARNING  SEARCHQUEUE-BACKLOG-275150 :: No NZB/Torrent providers found or enabled in the sickrage config for backlog searches. Please check your settings.
2015-06-19 19:13:57 INFO     SEARCHQUEUE-BACKLOG-275150 :: Building internal name cache for Save With Jamie
2015-06-19 19:13:57 INFO     SEARCHQUEUE-BACKLOG-275150 :: Beginning backlog search for: [Save With Jamie]
AA

**Comment by miigotu** [comment]
ssh into the QNAP, 
`find /share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage ! -name '*.pyo' ! -name '*.pyc' -type f -exec grep -i '802e82eff763d3d5f972410b7102beed' {} +`

**Comment by LennyM8472** [comment]
Hi I think I found the problem (no errors for a couple of hours).
It was indeed an external program with old credentials. Sick Beard Connect for Chrome.

Thanks for all the input.

Will revert if error returns

best regards
Lennart
