### ISSUE TITLE
[APP SUBMITTED]: CHECKVERSION :: git fetch origin returned : fatal: unable to access 'https://github.com/SiCKRAGETV/SickRage.git/': Couldn't resolve host 'github.com'

### ISSUE THREAD

**Issue by smokingunny** [SiCKRAGETV/sickrage-issues#1851]
### INFO
Python Version: **2.7.9 (default, Mar 22 2015, 23:43:57) [GCC 4.6.4]**
Operating System: **Linux-2.6.32.12-armv5tel-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@52a6c31cdf545c4e2fd22925a92a3d0824c429cf
Link to Log: https://gist.github.com/4874d5f92bb2192adace
### ERROR
```
CHECKVERSION :: git fetch origin returned : fatal: unable to access 'https://github.com/SiCKRAGETV/SickRage.git/': Couldn't resolve host 'github.com'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Not an issue
