### ISSUE TITLE
[APP SUBMITTED]: Thread-92 :: git ls-remote --heads origin returned : fatal: bad config file line 1 in .git/config

### ISSUE THREAD

**Issue by oconnellkj** [SiCKRAGETV/sickrage-issues#1853]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@e6c4cfd6546b74d5527361f6f0bdc3adc232bdb0
Link to Log: https://gist.github.com/2b8f2bccf52db575d23a
### ERROR
```
Thread-92 :: git ls-remote --heads origin returned : fatal: bad config file line 1 in .git/config
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
check that `C:\sickrage\.git\config` is not broken, has permissions, etc. This is not a sickrage file, it is created when you clone the repo with git.
