### ISSUE TITLE
[APP SUBMITTED]: 'ascii' codec can't encode characters in position 15-26: ordinal not in range(128)

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#1854]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:34:55) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-21-generic-i686-with-Ubuntu-15.04-vivid**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@ea1290ba0caa8ce4c6d9aa568552e6d4e8fef5bf
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: ascii : /media/ssd/DLL/Американский Папаша Сезон 4 WEB-DL 720p/American Dad S04 E16 WEB-DL 720p.mkv : error 15 : error 27 : ordinal not in range(128)
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@matigonkas Special characters are the problem. "Американский Папаша Сезон "
Try this. : 
https://sickrage.tv/forums/forum/help-support/general-support/12825-ensuring-your-locale-s-are-set-properly-to-avoid-unicode-issues

Also there are numerous issues here on github that you can lookup for more help/info.
