### ISSUE TITLE
Error while post-processing whole season (rtorrent)

### ISSUE THREAD

**Issue by frriction** [SiCKRAGETV/sickrage-issues#1855]
BRANCH: (master) / COMMIT: (52a6c31cdf545c4e2fd22925a92a3d0824c429cf) 
Operating system - Archlinux 
Python Version:	2.7.10 (default, May 30 2015, 02:17:57) [GCC 4.9.2 20150304 (prerelease)]

What I did
I am manually downloading required seasons torrent file and giving it to Rtorrent.
When Rtorrent finishes it calls for nzbtomedia script to post process that torrent.
I post process I am using  "Process Episode Method: Symlink"  and everything else is untick including rename. So Sickrage just copy file and create symlink. 

Everything runs fine until I receive following error while post-processing whole season and it stops post processing.

https://gist.github.com/882dbfa7d411b6a64e89
this is log from nzbtomedia
https://gist.github.com/1fd82286e8882a2dbe50

Here nzbtomedia config
https://gist.github.com/7bd48916571143781d4d

I have not enabled debug mode yet but I will post log with debug asap.

Thank You.

**Comment by neoatomic** [comment]
@frriction As your question is about post-processing with nzbtomedia its probably a better idea to directly ask on there repository?. : https://github.com/clinton-hall/nzbToMedia

**Comment by frriction** [comment]
@neoatomic I am getting error with Sickrage not nzbtomedia. nzbtomedia passes file to sickrage but sickrage fails while processing those files. Above log I have downloaded season with 24 episode so 23 files but only 11 files got processed and than there was that error.

**Comment by frriction** [comment]
@neoatomic if you see nzbtomedia log; from line 8 to almost to the end in that log is about sickrage.

**Comment by neoatomic** [comment]
@frriction I myself are not familiar with nzbtomedia, so cant troubleshoot this. Hopefully one of the Dev's can help out.
In the meantime try to disable the notifications, just to rule out that is causing the problem.

**Comment by frriction** [comment]
@neoatomic ok I did that, I had plex server, boxer and trakt activated.

**Comment by neoatomic** [comment]
@frriction Plex now needs the Token to be added for it to work. Has to do with a recent Plex update for https.

**Comment by frriction** [comment]
@neoatomic it was with token only.

**Comment by neoatomic** [comment]
@frriction Was worth a try to see it you maybe forgot to set the Token.
Still having this error after disabling the notifications.?

**Comment by frriction** [comment]
@neoatomic I ran into some other issues with my hdd just shorted everything out. I have slow internet so it will take a day to see if problem got solved or not. I will report back  asap.

**Comment by frriction** [comment]
case -1 (notification off)
I turned off all the notifications; no issue files moved and created symlink successfully.

case -2 (Boxcar2 notification)
I turned on Boxcar2 notification; no  issue moved and created symlink successfully for all the episodes in season and received notification on Boxcar2. 

case -3 (Boxcar2 + trakt notification)
Than I turned on trakt notification along side Boxcar2 notification; I encountered the error here is dbug log https://gist.github.com/a71c7cb6153162c26bef and here is nzbtomedia log https://gist.github.com/e0c99b6a92d00ef0a265

case -4 (Boxcar2 + plex server notification)
I turned off trakt and turned on plex server notification; no  issue moved and created symlink successfully for all the episodes in season and received notification on Boxcar2.

**Comment by neoatomic** [comment]
So we can conclude that the problem is the Trakt notifier. 
If you have checked the user-name/password/token than try to use http instead of https.

**Comment by frriction** [comment]
how do I do that?
by ticking "Disable SSL Verification"?

**Comment by neoatomic** [comment]
Yes, then it should use http.

**Comment by frriction** [comment]
ok I have Disable SSL Varification and error is still there.
here is debug log https://gist.github.com/d42f823716464ccb8c46
Now I have disable trakt notification until it get fixed.

**Comment by frriction** [comment]
I read debug log little carefully it seem boxcar2 is failing, please correct me if I am wrong.

**Comment by neoatomic** [comment]
Thats how i also read it. But as your testing pointed out it was Trakt, as boxcar2 had no issues.

**Comment by frriction** [comment]
I have disabled everything only kept boxcar2 activated and faced same error. So I believe it is boxcar2 only. As of this moment I have disabled boxcar2 and activated pushbullet+trakt I will report back if it I face same error or not.

**Comment by fernandog** [comment]
@frriction 
boxcar2 connection timed out.
use  the "test" button please to see ifs connecting OK.

**Comment by frriction** [comment]
it connects and receive notification until I get this error.

**Comment by fernandog** [comment]
so it's intermittent?

**Comment by frriction** [comment]
yes

**Comment by fernandog** [comment]
is there a timeout setting for boxcar2 in UI?

**Comment by frriction** [comment]
No, not for any any notification method.

**Comment by fernandog** [comment]
stop SR, edit config.ini and change socket timeout setting to 90, start SR. report back please

**Comment by frriction** [comment]
Ok I will do that It may take day or two.

**Comment by frriction** [comment]
@fernandog as per your request I have changed socket value to 90 
.I post processed same season again and again almost four times until I encounter error.
 here is log https://gist.github.com/8d2dce5779e5c1ee566b

**Comment by fernandog** [comment]
wait fix in master
