### ISSUE TITLE
[APP SUBMITTED]: locale changed during initialization

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#1857]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:34:55) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-21-generic-i686-with-Ubuntu-15.04-vivid**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@ea1290ba0caa8ce4c6d9aa568552e6d4e8fef5bf
No Log available with ERRORS: 
### ERROR
```
Thread-39 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/supergonkas/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/home/supergonkas/SickRage/sickbeard/webserve.py", line 3589, in index
    return t.respond()
  File "/home/supergonkas/SickRage/cache/cheetah/_home_supergonkas_SickRage_gui_slick_interfaces_default_history_tmpl.py", line 452, in respond
    curdatetime = VFN(VFFSL(SL,"datetime.datetime",True),"strptime",False)(str(VFFSL(SL,"hItem",True)["actions"][0]["time"]), VFFSL(SL,"history.dateFormat",True))
  File "/usr/lib/python2.7/_strptime.py", line 300, in _strptime
    _TimeRE_cache = TimeRE()
  File "/usr/lib/python2.7/_strptime.py", line 188, in __init__
    self.locale_time = LocaleTime()
  File "/usr/lib/python2.7/_strptime.py", line 77, in __init__
    raise ValueError("locale changed during initialization")
ValueError: locale changed during initialization

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by matigonkas** [comment]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:34:55) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-21-generic-i686-with-Ubuntu-15.04-vivid**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@ea1290ba0caa8ce4c6d9aa568552e6d4e8fef5bf
No Log available with ERRORS: 
### ERROR
```
Thread-36 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/supergonkas/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/home/supergonkas/SickRage/sickbeard/webserve.py", line 3589, in index
    return t.respond()
  File "/home/supergonkas/SickRage/cache/cheetah/_home_supergonkas_SickRage_gui_slick_interfaces_default_history_tmpl.py", line 452, in respond
    curdatetime = VFN(VFFSL(SL,"datetime.datetime",True),"strptime",False)(str(VFFSL(SL,"hItem",True)["actions"][0]["time"]), VFFSL(SL,"history.dateFormat",True))
  File "/usr/lib/python2.7/_strptime.py", line 300, in _strptime
    _TimeRE_cache = TimeRE()
  File "/usr/lib/python2.7/_strptime.py", line 188, in __init__
    self.locale_time = LocaleTime()
  File "/usr/lib/python2.7/_strptime.py", line 77, in __init__
    raise ValueError("locale changed during initialization")
ValueError: locale changed during initialization

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Stop SR, `rm -rf /home/supergonkas/SickRage/cache/cheetah`, start SR.

**Comment by matigonkas** [comment]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:34:55) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-21-generic-i686-with-Ubuntu-15.04-vivid**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@a7fa4c192ce9c3a1ff201c79bc6b42395f002a50
No Log available with ERRORS: 
### ERROR
```
Thread-37 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/supergonkas/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/home/supergonkas/SickRage/sickbeard/webserve.py", line 3589, in index
    return t.respond()
  File "/home/supergonkas/SickRage/cache/cheetah/_home_supergonkas_SickRage_gui_slick_interfaces_default_history_tmpl.py", line 452, in respond
    curdatetime = VFN(VFFSL(SL,"datetime.datetime",True),"strptime",False)(str(VFFSL(SL,"hItem",True)["actions"][0]["time"]), VFFSL(SL,"history.dateFormat",True))
  File "/usr/lib/python2.7/_strptime.py", line 300, in _strptime
    _TimeRE_cache = TimeRE()
  File "/usr/lib/python2.7/_strptime.py", line 188, in __init__
    self.locale_time = LocaleTime()
  File "/usr/lib/python2.7/_strptime.py", line 77, in __init__
    raise ValueError("locale changed during initialization")
ValueError: locale changed during initialization

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by matigonkas** [comment]
@miigotu  still happening

**Comment by fernandog** [comment]
@matigonkas still happening?

**Comment by matigonkas** [comment]
No not atm the but thing is this seems to happen sporadically and i dont know how to reproduce

**Comment by miigotu** [comment]
Go to the history page.

I think I thats the only place you see it.

**Comment by matigonkas** [comment]
just did that and didnt got any error ,so i dont know . Could it be  due to a specific release?

**Comment by fernandog** [comment]
related?

According to a previous Answer on StackOverflow, time.strptime is not thread-safe. Unfortunately, the error referenced in that question is different than the error you're experiencing.
Their solution was to call time.strptime prior to initializing any threads, and then subsequent calls to time.strptime in various threads will work
http://stackoverflow.com/questions/4625149/fixed-strptime-exception-with-thread-lock-but-slows-down-the-program

**Comment by miigotu** [comment]
It is because of threads, but the same fix will not work.
SR already calls setlocale at the start of the app, before threads exist.

Problem is converting times/dates to local time with sbdatetime.sbdatetime.sbfdate, sbdatetime.sbdatetime.sbfdatetime, sbdatetime.sbdatetime.sbftime

All which call setlocale and change the locale....

**Comment by matigonkas** [comment]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:34:55) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-21-generic-i686-with-Ubuntu-15.04-vivid**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@4f69f8b0c340e8e77a7eff6296124d6a39c5ec80
Link to Log: https://gist.github.com/1b7dc8da8bcd0fc5710c
### ERROR
```
Thread-35 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/supergonkas/SickRage/sickbeard/webserve.py", line 259, in async_call
    result = function(**kwargs)
  File "/home/supergonkas/SickRage/sickbeard/webserve.py", line 3588, in index
    return t.respond()
  File "/home/supergonkas/SickRage/cache/cheetah/_home_supergonkas_SickRage_gui_slick_interfaces_default_history_tmpl.py", line 447, in respond
    curdatetime = VFN(VFFSL(SL,"datetime.datetime",True),"strptime",False)(str(VFFSL(SL,"hItem",True)["actions"][0]["time"]), VFFSL(SL,"history.dateFormat",True))
  File "/usr/lib/python2.7/_strptime.py", line 300, in _strptime
    _TimeRE_cache = TimeRE()
  File "/usr/lib/python2.7/_strptime.py", line 188, in __init__
    self.locale_time = LocaleTime()
  File "/usr/lib/python2.7/_strptime.py", line 77, in __init__
    raise ValueError("locale changed during initialization")
ValueError: locale changed during initialization

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by matigonkas** [comment]
@miigotu happened again ,but still dont know how to reproduce it

**Comment by miigotu** [comment]
I do. =P. This cannot be easily fixed. It is because of time zone conversion in the ui using sbfdatetime. Turn off fuzzy dates and switch to network time (i think thats the right combo).

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:34:55) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-22-generic-i686-with-Ubuntu-15.04-vivid**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@3db87525c87034ec10878d50f96c183eca939252
No Log available with ERRORS: 
### ERROR
```
FINDSUBTITLES :: Exception generated in thread FINDSUBTITLES: locale changed during initialization
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@duramato do you still have this issue?

**Comment by duramato** [comment]
@fernandog no I don't think so , if I do I'll post here
