### ISSUE TITLE
[Request] Add extratorrent (ettv) to official torrent providers.

### ISSUE THREAD

**Issue by papampi** [SiCKRAGETV/sickrage-issues#1860]
since eztv is hacked and gone...
Is it possible to add extratorrent to official torrent providers so SB can search it for backlog too ?
I know we can use its rss feed ( http://extratorrent.cc/rss.xml?cid=8&type=last) but isnt it better to have it as an official provider ?

**Comment by neoatomic** [comment]
@papampi Please add your request here.  https://github.com/SiCKRAGETV/sickrage-issues/issues/1741 
And post the required details/info as ask.
