### ISSUE TITLE
Group name not being recognised

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#1862]
The group name of this torrent "VICE.S03E13.SDTV.x264-[2Maverick]" its not being recognised.
TBH all of 2maverick releases arent being recognised

**Comment by matigonkas** [comment]
correction, its being shown correctly , as "[2Maverick]" on the detailed history page but not on the compact one

**Comment by neoatomic** [comment]
@matigonkas Could you post a screen-shot from both pages.? 
(Had a quick peek through my detailed/compact list but all seems ok here.)

**Comment by matigonkas** [comment]
![screenshot_2015-06-20-23-04-32](https://cloud.githubusercontent.com/assets/10121067/8269461/02bcf77c-17a1-11e5-9c29-e8754df8e881.png)
![screenshot_2015-06-20-23-06-05](https://cloud.githubusercontent.com/assets/10121067/8269466/111a7826-17a1-11e5-9f1f-1b3dae588961.png)
@neoatomic. Its the vice episode the problematic one

**Comment by miigotu** [comment]
Found it =P
