### ISSUE TITLE
Fix donate button

### ISSUE THREAD

**Issue by Hellowlol** [SiCKRAGETV/sickrage-issues#1863]
Hi! @echel0n . Would you mind fixing the donate button so i can part with some $?

**Comment by miigotu** [comment]
echel0n is MIA for the past few months, and the donate button works afaik.

**Comment by Hellowlol** [comment]
Nope, I can't get pass enter username

**Comment by miigotu** [comment]
@Hellowlol this has been fixed-ish Until we come up with a better solution, the button now points to https://github.com/SiCKRAGETV/SickRage/wiki/Donations

**Comment by Hellowlol** [comment]
Thanks!
