### ISSUE TITLE
[APP SUBMITTED]: list.remove(x): x not in list

### ISSUE THREAD

**Issue by MasterAslan** [SiCKRAGETV/sickrage-issues#1865]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@68c55eadbd502c63ae35e42ccc741509e94f3d6a
Link to Log: https://gist.github.com/a7bc6bad5e15e012e59d
### ERROR
```
Thread-27 :: list.remove(x): x not in list
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Same as https://github.com/SiCKRAGETV/sickrage-issues/issues/1305 
(Fix not working correctly.? )

**Comment by fernandog** [comment]
@MasterAslan what exactly did you do to ?

**Comment by dirkr07** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  4 2015, 00:30:19) [GCC 4.3.2]**
Operating System: **Linux-2.6.32.12-ppc-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@1ec701e4c12b41d1a34f01ad6091b1fec09967a3
Link to Log: https://gist.github.com/dc2320a0d180aefc650a
### ERROR
```
Thread-65 :: list.remove(x): x not in list
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by joakim93** [comment]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@3fb81bd65d7710e59d6c89945a3be39d2dbfc386
No Log available with ERRORS: 
### ERROR
```
Thread-36 :: list.remove(x): x not in list
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by WebSpider** [comment]
We need debug logs to troubleshoot this.

**Comment by WebSpider** [comment]
No new logs,no new troubleshooting @joakim93

**Comment by racinrandall** [comment]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@657ffd7c4e61d32cecde009541cd25476579b254
Link to Log: https://gist.github.com/207c7d01b78dfb9fdef3
### ERROR
```
Thread-53 :: list.remove(x): x not in list
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by snapperhead** [comment]
### INFO
Python Version: **2.7.10 (default, Aug 22 2015, 20:33:39) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)]**
Operating System: **Darwin-15.0.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@1c57cce2d73d9775acb01f256e07d22a93f4c1f4
Link to Log: https://gist.github.com/a214105455149dac2895
### ERROR
```
Thread-46 :: Traceback (most recent call last):
  File "/Applications/SickRage/sickbeard/logger.py", line 303, in submit_errors
    classes.ErrorViewer.errors.remove(curError)
ValueError: list.remove(x): x not in list

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by OmgImAlexis** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-57-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@e1bf8412922d898878e98e5f4466492eb39c4456
No Log available with ERRORS: 
### ERROR
```
Thread-56 :: Traceback (most recent call last):
  File "/home/media/sickrage/sickbeard/logger.py", line 308, in submit_errors
    classes.ErrorViewer.errors.remove(curError)
ValueError: list.remove(x): x not in list

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
