### ISSUE TITLE
[Feature Request] "Preferred Words on Archive" & Option to "Snatch before Release"

### ISSUE THREAD

**Issue by mbxplex** [SiCKRAGETV/sickrage-issues#1867]
I apologize if these feature requests have already been made or if there is a way to set them up. 

Request 1 - "Preferred Words" Search on Archive:
Similar to the feature found in CP, I would like to see SR have a preferred words search box that applies to the Archived snatch. This would (or should) give people the ability to search for Uncensored episodes or to download from a specific uploader.

Request 2 - Snatch before Release:
I've read that this feature existed to certain extent, but when early releases would appear, they would a lot of times be fakes. But, I would still like to have the ability to choose myself whether or not to Snatch before a set release date per individual series. A lot of times, do to my location in the US, I will receive BBC or SoHo shows from uploaders prior to the "release date" set on SR.

**Comment by neoatomic** [comment]
@mbxplex Both have already be requested. https://github.com/SiCKRAGETV/sickrage-issues/issues/461 
But the Dev's haven't had the time to implement it yet.

**Comment by mbxplex** [comment]
@neoatomic thanks for the quick reply! Is there an open forum for the feature request described as "Snatch before Release" I can comment on?
