### ISSUE TITLE
Centos 7 - Web Restart issues

### ISSUE THREAD

**Issue by VDI-Tech-Guy** [SiCKRAGETV/sickrage-issues#1871]
Hey all, just wanted to let you know that i got Sickrage installed on Centos7 however it has one major issue with it that a lot of the other integration softwares have (sabnzbd, couchpotato, etc) the restart functionality i assume is using a init script (service sickrage start) type command as it doesn't work in Centos7 as they started using the systemctl based command structure. it seems the PID is used to kill the service as it shuts down just fine however a restart or update restart does not work appropriately i have to call the command directly (systemctl start sickrage) to start the service.

If theres any logs i can help provide to help with this let me know i used the following blog to get my centos7 version installed everything else seems to work fine just this 1 thing thats a nuisance and has to be done manually.

http://deviantengineer.com/2015/06/usenet-centos7/

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/blob/master/runscripts/init.systemd

**Comment by miigotu** [comment]
try removing the forking line and the --daemon

**Comment by fernandog** [comment]
this is my unit:

```
[Unit]
Description=SickRage Daemon
After=transmission.service nzbget.service network-online.target media-SAMSUNG.mount
Requires=udisks-glue.service transmission.service network-online.target

[Service]
Restart=on-failure
RestartSec=30
Nice=5
OOMScoreAdjust=-1000
User=osmc
Group=osmc
Type=forking
GuessMainPID=no
ExecStart=/usr/bin/python /home/osmc/SickRage/SickBeard.py -q --daemon --nolaunch

[Install]
WantedBy=multi-user.target

```

**Comment by miigotu** [comment]
Probably the GuessMainPID=no and Nice helps.

We include runscripts in SR source as a base/starting point for people to go on. If they want to submit improved versions then fine, but we are not experts in every operating system's service configurations.

If you want to run linux, learn what the files you create do, don't just follow some guide without understanding what it is doing -.-
