### ISSUE TITLE
[APP SUBMITTED]: 'utf8' codec can't decode byte 0xe9 in position 84: invalid continuation byte

### ISSUE THREAD

**Issue by Rouzax** [SiCKRAGETV/sickrage-issues#1872]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@52a6c31cdf545c4e2fd22925a92a3d0824c429cf
Link to Log: https://gist.github.com/eca6da7a4a8ec7079923
### ERROR
```
TORNADO :: API :: utf8 : 2015-06-22 14:03:25 DEBUG    SHOWQUEUE-REFRESH :: Parsed Penny Dreadful - S01E02 - Séance (HDTV-2HD)) into Penny Dreadful - S1E2 [ANIME VER: -1] [GROUP: 2HD))] [ABD: False] [ANIME: False] [whichReg: ['standard']]
 : error 84 : error 85 : invalid continuation byte
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Rouzax** [comment]
This might be an issue with DroidBeard. The Android app to connect to SickRage.

**Comment by neoatomic** [comment]
@Rouzax The special character in "Séance " is the problem.

**Comment by miigotu** [comment]
utf-16? -.-

**Comment by Rouzax** [comment]
Is this an issue with SickRage or DroidBeard?

**Comment by miigotu** [comment]
Most likely DroidBeard, as it is passing the string to sickrage, and sickrage is trying to decode it as utf8 so DroidBeard is passing an improperly encoded string.

**Comment by rastating** [comment]
Hey,

There's only one place in DroidBeard were show names are passed to the API, which is when calling the ```sb.searchtvdb``` method. Judging from the tag in the error log though (SHOWQUEUE-REFRESH) and the fact there is quality information in there, looks like the show already exists within the users SickRage installation, so possibly needs looking into in the SickRage code too.

I'll patch the code in DroidBeard anyway though that uses ```sb.searchtvdb```, just thought I'd let you guys know though in case you want to re-open this and investigate.

**Comment by miigotu** [comment]
@rastating Yes, it might be a problem in SR.

It is hard to tell from the traceback whether the api gets it and then can convert it completely or if it is erroring on the initial convert.

Best to just make sure your string can be converted to utf-8 before passing it anyways.

**Comment by miigotu** [comment]
@rastating I'm starting to think it is in SR, disregard.

@Rouzax you were forcing a refresh via api correct? If so, forcing the refresh from SR itself should do the same error. Can you check?

**Comment by Rouzax** [comment]
I did a force full update of Penny Dreadful but that did not trigger the error.
Think that the error occurred when I initialy opened the show Penny Dreadful in DroidBeard and it got the information the first time, could that be?

**Comment by miigotu** [comment]
Not sure. I can't reproduce it.

I added Penny dreadful and did searches via api with it as well as show refresh and update via api and gui.

No errors, even with tornado logging on.

**Comment by Rouzax** [comment]
Same here.
I just cleared all data of DroidBeard and uninstalled it. After I configured it again but it does not show this error any more :confused:
