### ISSUE TITLE
[Feature request] - Store link to Torrent page

### ISSUE THREAD

**Issue by Rouzax** [SiCKRAGETV/sickrage-issues#1873]
It would be nice to have SickRage record the link were it got the episode.
That way I can check the information on the torrent provider website without searching for the torrent.

**Comment by miigotu** [comment]
Impossible. More often than not we don't scrap pages, we us an api to the torrent site or an rss feed.

**Comment by Rouzax** [comment]
CouchPotato also uses the API's but there is a link to the torrent in there.
