### ISSUE TITLE
[APP SUBMITTED]: global name 'show_name_helpers' is not defined

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#1874]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-3.18.13-1-osmc-armv7l-with-debian-8.1**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@eee6f4eae4ade413e99c7d0eec6e61573181d2d7
Link to Log: https://gist.github.com/daa191940158f5fcfbbe
### ERROR
```
SEARCHQUEUE-MANUAL-271910 :: [Rarbg] :: Error while searching Rarbg, skipping: global name 'show_name_helpers' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
that's odd as this import appears in others files

https://github.com/SiCKRAGETV/SickRage/search?utf8=%E2%9C%93&q=from+sickbeard+import+show_name_helpers

**Comment by fernandog** [comment]
traceback:
```
AA
AANameError: global name 'show_name_helpers' is not defined
AA    if not show_name_helpers.filterBadReleases(curResult["name"]):
AA  File "/home/osmc/SickRage/sickbeard/tvcache.py", line 338, in findNeededEpisodes
AA    neededEps = self.findNeededEpisodes(episode, manualSearch, downCurQuality)
AA  File "/home/osmc/SickRage/sickbeard/tvcache.py", line 301, in searchCache
AA    cacheResult = self.cache.searchCache(epObj, manualSearch, downCurQuality)
AA  File "/home/osmc/SickRage/sickbeard/providers/generic.py", line 287, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/home/osmc/SickRage/sickbeard/search.py", line 471, in searchProviders
```

**Comment by miigotu** [comment]
missing import in sickbeard/tvcache.py
`from sickbeard import show_name_helpers`

pushing now.

**Comment by fernandog** [comment]
thanks!
