### ISSUE TITLE
No way to change default Ep Status on new additions

### ISSUE THREAD

**Issue by OlleDenStore** [SiCKRAGETV/sickrage-issues#1875]
After the latest update the option to set the default Ep Status seems to have disappeared.
When I choose edit on a show there is no longer a field that let's me change this. If I choose Mass Update there is a column that indicates the def. ep status for all shows and the edit option here has a field for changing it but it doesn't seem to do anything. This means that none of the newly added(after the update) shows are automatically downloaded. The old ones seem to work fine though.
Any and all help would be greatly appreciated.

/Olle

**Comment by fernandog** [comment]
read here:
https://github.com/SiCKRAGETV/sickrage-issues/issues/1483
