### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-261511 :: Unable to parse Daniel.Tiger's.Neighborhood.-.S01.SDTV-REPACK-CPM into a scene name. If it's a valid one log a bug.

### ISSUE THREAD

**Issue by phishin4dmb** [SiCKRAGETV/sickrage-issues#1876]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@52a6c31cdf545c4e2fd22925a92a3d0824c429cf
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-261511 :: Unable to parse Daniel.Tiger's.Neighborhood.-.S01.SDTV-REPACK-CPM into a scene name. If it's a valid one log a bug.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
bad naming pattern
