### ISSUE TITLE
Connection error ('Connection aborted.', gaierror(-2, 'Name or service not known'))

### ISSUE THREAD

**Issue by jizz** [SiCKRAGETV/sickrage-issues#1877]
Running in Docker with this container: https://registry.hub.docker.com/u/needo/sickrage/
SR Version:	BRANCH: (master) / COMMIT: (e6c4cfd6546b74d5527361f6f0bdc3adc232bdb0) 
Python Version:	2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]

Started happening about a week ago but only starting to investigate now.

Errors for anything that requires data to be fetched/refreshed:

eg:
19:24:21 WARNING::MAIN :: Connection error ('Connection aborted.', gaierror(-2, 'Name or service not known')) while loading URL http://sickragetv.github.io/sr_tvrage_scene_exceptions/exceptions.txt
stderr
2015-06-23 20:31:21 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Connection error ('Connection aborted.', gaierror(-2, 'Name or service not known')) while loading URL https://thepiratebay.gd/tv/latest/
2015-06-23 20:21:46 ERROR    SHOWQUEUE-REFRESH :: Unable to connect to theTVDB while creating meta files - skipping - error Connection error ('Connection aborted.', gaierror(-2, 'Name or service not known')) while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/79168/en.xml

Can ping these sites from with container.

**Comment by fernandog** [comment]
No internet on that moment. No issue

**Comment by jizz** [comment]
Hello, please excuse the typo in the last line. It was meant to read "can ping these sites fro within container"

There is an internet connection, I even copied the above log items externally from my network.

**Comment by fernandog** [comment]
@jizz is this happens ALWAYS or only happened once?

**Comment by jizz** [comment]
Always. Logs are littered with the same error. Nothing appears to have been fetched/updated since 16/6/15.

I've got logs dating back to the 14th, happy to start digging through them if you give me an idea of what would be useful.

**Comment by fernandog** [comment]
@miigotu SSL related?

@jizz enabled DEBUG in SR settings, force a search and than please send FULL logs

**Comment by jizz** [comment]
http://pastebin.com/VXwUtDAi

FYI, I can pull  http://sickragetv.github.io/sr_tvrage_scene_exceptions/exceptions.txt down into the container via wget

**Comment by miigotu** [comment]
@jizz stop SR and delete cache/sessions cache/rss cache/indexers and cache.db

When you start it back up it will take a few minutes before it is ready.

**Comment by jizz** [comment]
@miigotu No change. It's been running for over 30 minutes and I still see the same connection errors. New .db files have been created but they appear to be empty due to their size.

**Comment by fernandog** [comment]
@jizz did you enabled proxy host?

**Comment by jizz** [comment]
Nope, that setting is blank/disabled.

**Comment by miigotu** [comment]
firewall or some kind of restriction in the container? idk, this is out of my control. This is not a SR problem, it is an implementation issue.
