### ISSUE TITLE
Some shows are not found/recognized anymore

### ISSUE THREAD

**Issue by lendenrk** [SiCKRAGETV/sickrage-issues#1878]
Branch : master
Commit hash : 2d515e9aa4aea0ec1798289df691cd5e949828ed
Your operating system and python version : Debian 3.2.54-2 x86_64 GNU/Linux (Python 2.7.3)

The daily, the backlog and the manual searchs don't find or recognize some of the shows which were few days ago (In my case the shows are The Messengers and Ballers). Besides that, other shows still work fine and are sent to my downloader. I'm using two trackers and in the logs I can see that the episodes are found but the message "Unable to parse the filename **** into a valid show" comes up several times (and not just for my shows but also for the other shows retrieved from these trackers).

The log file will give more informations : https://gist.github.com/lendenrk/d59d57f140721632106d

In this case the line
[IPTorrents] :: Found result: Ballers 2015 S01E01 720p HDTV x264-KILLERS
should result with a new download, but few lines down, I get 
[IPTorrents] :: Unable to parse the filename Ballers.2015.S01E01.720p.HDTV.x264-KILLERS into a valid show

So the episode isn't snatched. I was hoping maybe the next update would fix it and since my sickrage got updated few hours ago and the problem is still there, I decided to create this issue.

Thank you

**Comment by miigotu** [comment]
"Unable to parse the filename **** into a valid show" is normal for shows that aren't in your list, because daily and cache updates just grab info about all of the newest releases and let SR sort through them.

The reason Ballers is not being recognized (if it is in your show list) is because you need a scene exception for it.

**Comment by miigotu** [comment]
Or there might be an issue, "Found result" shows the title without ".", and parser trying to use one with ".", so maybe it isnt matching releases it snatched itself.  I'll take a look tonight or tomorrow, as I have been hackalicous for like 2 days straight.

**Comment by fernandog** [comment]
@lendenrk you need to add "Ballers (2014)" to scene exceptions. Edit show and add it

**Comment by fernandog** [comment]
@lendenrk also for Messengers
The Messengers (2015)
The Messengers 2015

notice in your log that SR is searching for "Beginning backlog search for: [The Messengers (2015)]"

the results don't have the year

**Comment by miigotu** [comment]
Ballers 2015 xD

**Comment by fernandog** [comment]
updated

**Comment by eleonrk** [comment]
Ok, thank you guys for your answers.
