### ISSUE TITLE
[Feature Request]: Add ilovetorrents as a search provider.

### ISSUE THREAD

**Issue by ZulDemon** [SiCKRAGETV/sickrage-issues#1879]
1) ILoveTorrents
2) ILT
3) hxxps://www.ilovetorrents.me
4) Torrent
5) Private

I searched open and closed issues and didn't find this requested previously, so I thought I would ask. I am currently using custom RSS feeds, but would love to be able to backlog search. Thank you for the amazing work that you do!

**Comment by neoatomic** [comment]
@ZulDemon Please fill in the remaining questions. : 

To request a provider please post the following. :

Name :
URL :
What kind of provider.? : (Torrent, NZB, Subtitle, Indexer, download client.)
Open or Invite only? :
Does the website have a API available.? :
Is it language specific.? : (focused on a single language or country.)
Motivate why this provider needs to be added.? :

**Comment by ZulDemon** [comment]
Name : i love torrents
URL : https://www.ilovetorrents.me
What kind of provider.? : Torrent
Open or Invite only? : Invite only (have available)
Does the website have a API available.? : Not that I can find.
Is it language specific.? : English
Motivate why this provider needs to be added.? : Upon completion, unicorns will be re-born and there by granting all the ability to piss rainbows and shit leprechauns. Well to be more accurate, I'm not a very gifted programmer and I'm graciously asking someone much more capable to do something I can not. I'm selfish like that, buuuuuuttttt very grateful.

**Comment by piejanssens** [comment]
+1 - ILT is a great tracker. 
You can use CouchPotatoServers ILT support as a base to add this to SR :smile: 
https://github.com/RuudBurger/CouchPotatoServer/blob/master/couchpotato/core/media/_base/providers/torrent/ilovetorrents.py

**Comment by naikdipe** [comment]
+1 ... ILT is one of the best private trackers out there !!

**Comment by iki488** [comment]
+1 as well... it is a great private tracker!!

**Comment by k4n30** [comment]
(y)

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
