### ISSUE TITLE
Post Processing Issues

### ISSUE THREAD

**Issue by Vodka2014** [SiCKRAGETV/sickrage-issues#1881]
Hi,

Please see the below:

BRANCH: (master)
COMMIT: (207bd7ac693e4beee0b72d4d3a05e0c7aca95300) 
OpenElec RPI 2
Python Version:	2.7.3 (default, Mar 31 2015, 15:16:49) [GCC 4.9.2]

I have updated the system and now I am getting issues when post processing starts. The files just sit in the download folder and that is it.

It was working before the last 2 updates that I did.

Now - https://gist.github.com/Vodka2014/a40d84092cfdf142d8c9

Should Be - https://gist.github.com/Vodka2014/e406b097432437d7862e

Thanks

**Comment by Vodka2014** [comment]
Any update please ?

**Comment by Vodka2014** [comment]
Can someone please answer this. This is affecting post processing.

**Comment by fernandog** [comment]
<div class="ctrlHolder"><input class="inlay" name="username" type="text" placeholder="Username" autocomplete="off" /></div>
<div class="ctrlHolder"><input class="inlay" name="password"

update sabtonzb scripts. check forums. SR needs login

**Comment by Vodka2014** [comment]
@ fernandog Thanks for the info I will do this now and post the results.

**Comment by Vodka2014** [comment]
So my autoProcessTV.cfg is correct as it was working 100% before I did the upgrades. I use sabtosickbeard.py.

Any other advice please

**Comment by Vodka2014** [comment]
So found the issue but not resolved. If you add a username and password to SickRage it does not work. As soon as you remove it and reboot Post Processing works 100%.

**Comment by fernandog** [comment]
@neoatomic do you use PP? do you care to explain please?

**Comment by miigotu** [comment]
We need to update the autoProcessTV scripts in SR?

**Comment by fernandog** [comment]
https://sickrage.tv/forums/forum/help-support/general-support/22262-sabtosickbeard-exe-py-no-longer-working

**Comment by Vodka2014** [comment]
Thanks but this is what i have read and done and posted there already as well about the issue. If you want you can close this one out and i will use that form for all other coms.

Thanks again.

**Comment by miigotu** [comment]
@Vodka2014 Where did you get your sab2sickbeard scripts? You should be copying them from your sickrage source.

Does your autoProcessTV.cfg have your username and password in it?
https://github.com/SiCKRAGETV/SickRage/blob/master/autoProcessTV/autoProcessTV.cfg.sample

**Comment by Vodka2014** [comment]
I upgraded SickRage like i always do. My cfg was setup like this before i changed it,

[SickBeard]
host=localhost
port=8082
username=MYUSERNAME
password=MYPASSWORD
web_root=
ssl=1

**Comment by Vodka2014** [comment]
@miigotu I have never changed them from the original location. Yes mine looks like that now.

I had a username and password setup and it was working until I upgraded. Also i have SSL=1

**Comment by neoatomic** [comment]
@fernandog Yes, i use sabtosickbeard. 
its pretty simple, you just need to add your user-name/password/host/port to the script. And setup a category in SAB. ( http://www.htpcguides.com/configure-sickrage-usenet-torrent-tv/ )

@Vodka2014 Disable SSL (think its SSL=-1) and try again.
Looking at the logs it try's to processes a HTML page, so i'm thinking it gets an (ssl?) error on the url instead of getting the data from SAB, it processes the error page.?
(Just to make sure, those logs are from manual PP or from sabtosickbeard.?)

**Comment by Vodka2014** [comment]
@neoatomic yes I use sabtosickbeard and it was working all the time until I did the updates. This is why I posted this :) 

I will try and remove SSL and set it up and see what happens. and report back when I get a change to change this.

Thanks for the info and help all.

**Comment by Vodka2014** [comment]
UPDATE: I see there is a new commit to SickRage. I have updated it, added my username and password, ssl=1 to the .cfg , added it to SickRage (username and password), Restarted SickRage and SABNZDB.

So far all is looking 100% :)
