### ISSUE TITLE
[APP SUBMITTED]: Thread-471 :: git fetch origin returned : error: insufficient permission for adding an object to repository database .git/objects
fatal: failed to write object
fatal: unpack-objects failed

### ISSUE THREAD

**Issue by papampi** [SiCKRAGETV/sickrage-issues#1882]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-55-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@52a6c31cdf545c4e2fd22925a92a3d0824c429cf
Link to Log: https://gist.github.com/e395cad9161f985ba673
### ERROR
```
Thread-471 :: git fetch origin returned : error: insufficient permission for adding an object to repository database .git/objects
fatal: failed to write object
fatal: unpack-objects failed
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by papampi** [comment]
used to get updates automatically before, but now I have to run "sudo git pull" from command line.
seems like a permission problem came out of no where.

**Comment by miigotu** [comment]
From inside sickrage dir:
`sudo chown -R .git`
