### ISSUE TITLE
[APP SUBMITTED]: Thread-30 :: git config remote.origin.url https://github.com/SiCKRAGETV/SickRage.git returned : fatal: bad config file line 1 in .git/config

### ISSUE THREAD

**Issue by jstevenson72** [SiCKRAGETV/sickrage-issues#1883]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@d185980c89055f7179deec708141710ce386a572
Link to Log: https://gist.github.com/158fb320625d425a6eeb
### ERROR
```
Thread-30 :: git config remote.origin.url https://github.com/SiCKRAGETV/SickRage.git returned : fatal: bad config file line 1 in .git/config
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1853
