### ISSUE TITLE
Sickrage always picking dead torrents

### ISSUE THREAD

**Issue by boyahr** [SiCKRAGETV/sickrage-issues#1884]
I tried to download "Ergo proxy", but Sickrage always seems to pick the worst torrents available, even though torrents with lots of seeders are available, is there a way to fix this ?
``` 
2015-06-24 11:40:57 INFO     SEARCHQUEUE-BACKLOG-79228 :: Downloading [EngSubs]Ergo.Proxy.-.1-23.[BD][720p][MP4][AAC] from KickAssTorrents
2015-06-24 11:40:09 INFO     SEARCHQUEUE-BACKLOG-79228 :: Performing episode search for Ergo Proxy
2015-06-24 11:39:41 INFO     SEARCHQUEUE-BACKLOG-79228 :: [KickAssTorrents] :: Performing season pack search for Ergo Proxy
2015-06-24 11:39:14 INFO     SEARCHQUEUE-BACKLOG-79228 :: Performing episode search for Ergo Proxy
2015-06-24 11:39:12 INFO     SEARCHQUEUE-BACKLOG-79228 :: [ThePirateBay] :: Performing season pack search for Ergo Proxy
2015-06-24 11:38:16 INFO     SEARCHQUEUE-BACKLOG-79228 :: [NyaaTorrents] :: Performing season pack search for Ergo Proxy
2015-06-24 11:38:06 INFO     SHOWQUEUE-ADD :: Done cache check
2015-06-24 11:37:49 INFO     SEARCHQUEUE-BACKLOG-79228 :: Building internal name cache for Ergo Proxy
2015-06-24 11:37:49 INFO     SEARCHQUEUE-BACKLOG-79228 :: Beginning backlog search for: [Ergo Proxy]
```
For example, look on https://kat.cr/usearch/ergo%20proxy/ , the DeadFish version has lots of seeders, but the one selected by Sickrage litteraly has none.

**Comment by neoatomic** [comment]
@boyahr Please follow the guidelines for posing an issue. : 
https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket

**Comment by boyahr** [comment]
Sorry about that

Branch : master
Commit hash : 2d515e9aa4aea0ec1798289df691cd5e949828ed
Your operating system and python version :
- Synology DSM 5.2
- 2.7.10 (default, Jun 3 2015, 17:38:42) [GCC 4.6.4]

**Comment by neoatomic** [comment]
We need the full logs to troubleshoot otherwise we cant see what SR is trying to do.
Also the quality settings for that series. (Sd, hdtv etc.)

Meanwhile check under the KAT settings of SR if you can set a minimum of seeders/peers.
Also you could use "required words" to only pick torrents from quality release groups.
And if i recall correct, there is another option to only download from trusted unloaders. (in general those have the most users.)

**Comment by boyahr** [comment]
Ok, so I deleted all the info & files on "Ergo proxy", switched debug to 1 and restarted.  There was an update and the hash is now :
207bd7ac693e4beee0b72d4d3a05e0c7aca95300

I started again by adding a new show, asked for 720p but this time the backlog didn't even start to download a torrent : https://gist.github.com/boyahr/2823c56b7753f6cbb133

Here is a pic of the content of the folder and episodes status after waiting ~15min:
https://i.imgur.com/GIhoVHk.png

**Comment by neoatomic** [comment]
Your log shows an SSL error. Are you using a proxy or is the site blocked in your country.?

```
AASSLEOFError: EOF occurred in violation of protocol (_ssl.c:590)
AA File "<string>", line 3, in raise_exc_info
AA raise_exc_info(self._exc_info)
AA File "/volume1/@appstore/sickrage/var/SickRage/tornado/concurrent.py", line 209, in result
AA value = future.result()
AA File "/volume1/@appstore/sickrage/var/SickRage/tornado/gen.py", line 807, in run
AA quiet_exceptions=iostream.StreamClosedError)
AA File "/volume1/@appstore/sickrage/var/SickRage/tornado/http1connection.py", line 166, in _read_message
AA yielded = self.gen.throw(*sys.exc_info())
AA File "/volume1/@appstore/sickrage/var/SickRage/tornado/gen.py", line 810, in run
AA raise_exc_info(self._exc_info)
AA File "/volume1/@appstore/sickrage/var/SickRage/tornado/concurrent.py", line 209, in result
AA value = future.result()
AA File "/volume1/@appstore/sickrage/var/SickRage/tornado/gen.py", line 807, in run
AA ret = yield conn.read_response(request_delegate)
AA File "/volume1/@appstore/sickrage/var/SickRage/tornado/http1connection.py", line 691, in _server_request_loop 
```

**Comment by boyahr** [comment]
Those websites are blocked by dns in my country, but I set up the NAS to use OpenDNS ips (which bypasses), so I don't think it could be the cause (however, I'll try to use the proxy option later today).

The other reason could be that my NAS uses https, but my certificate never failed me until now (a free one by StartSSL).

**Comment by boyahr** [comment]
The SSL error repeated itself several times today, even though I set up the use of proxys for torrents.  I don't know what could be causing it.  Otherwise, backlogging seems to be working as it should, but I don't know if it's due to luck or not :P

**Comment by neoatomic** [comment]
What you can do is a clean install and start with with a new database/config.ini and see if that solves it. Maybe the installation got bad.? (Off course do a backup in case that doesn't solve it.)

I'm running a Synology myself and dont have any SSL problems, so it must be local/specific to your setup.
