### ISSUE TITLE
[APP SUBMITTED]: Thread-54 :: git rev-parse --verify --quiet "@{upstream}" returned : fatal: No upstream configured for branch 'master'

### ISSUE THREAD

**Issue by jstevenson72** [SiCKRAGETV/sickrage-issues#1885]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@207bd7ac693e4beee0b72d4d3a05e0c7aca95300
Link to Log: https://gist.github.com/5bee07ebcc1cc2858c58
### ERROR
```
Thread-54 :: git rev-parse --verify --quiet "@{upstream}" returned : fatal: No upstream configured for branch 'master'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1144
