### ISSUE TITLE
TVRage show status icon not showing correcly on frontpage.

### ISSUE THREAD

**Issue by neoatomic** [SiCKRAGETV/sickrage-issues#1886]
Came across a small bug. 
If you add a show with the TVRage indexer and it has the Show Status is "Returning Series" it shows as not active (red cross) on the main-page under the column "active"

TheTVDB uses Show Status: 	Continuing
TVRage    uses Show Status: 	Returning Series

So the template probably needs an tweak so that when it receives "Returning Series" it also gets a green "v" icon instead of a red cross.

![sr](https://cloud.githubusercontent.com/assets/7928052/8327376/300234c6-1a68-11e5-98a2-8728d099781e.png)

![sr1](https://cloud.githubusercontent.com/assets/7928052/8327427/9aee7ca4-1a68-11e5-8737-4d47a4fba10e.png)

Edit: ignore the red arrow. it was for another issue.

**Comment by fernandog** [comment]
fix label is when there a fix available

**Comment by fernandog** [comment]
the code seems ok. check it:
https://github.com/SiCKRAGETV/SickRage/blob/master/lib/tvrage_api/tvrage_api.py#L443

https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/databases/mainDB.py#L150

https://github.com/SiCKRAGETV/SickRage/blob/master/gui/slick/interfaces/default/inc_bottom.tmpl#L30

**Comment by neoatomic** [comment]
Strange, i just check the series and now it states  "Show Status: Continuing" ?!
( Just to be sure, lower/upper case characters are not a problem.? )

![sr2](https://cloud.githubusercontent.com/assets/7928052/8331312/cbfb58de-1a87-11e5-8399-139c078bf2a6.png)
