### ISSUE TITLE
sickrage doesn't find a tvshow (real time)

### ISSUE THREAD

**Issue by ShinobiX9X** [SiCKRAGETV/sickrage-issues#1887]
hi, for some reason, sickrage can't find a certain show.
here is the log:
https://gist.github.com/ShinobiX9X/7403e832b85977bb8bd6

BRANCH: (master) / COMMIT: (207bd7ac693e4beee0b72d4d3a05e0c7aca95300) 
freenas (jail) python i don't know
i added real time with bill maher
it can't find the torrent

**Comment by neoatomic** [comment]
https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket

**Comment by neoatomic** [comment]
@ShinobiX9X Enable "Air by date:" in the show and check if the show-name is the same as the title of the torrents. If not add a scene exception with the correct torrent name.
