### ISSUE TITLE
Separate NZBs for Show and Pars - SickRage appears to only get Pars

### ISSUE THREAD

**Issue by syaeger** [SiCKRAGETV/sickrage-issues#1888]
I'm just switching to SickRage from SickBeard, but so far, it appears as if every NZB file that SickRage has sent to SabNzbd has just been the show's Pars file NZB file.

So far, all of the shows have had separate posts on BinSearch.info for the show and the pars.  And the Show's NZB file was older than the Pars' NZB file.

The only evidence I have that this is what is happening is from post mortem examinations of the files in SabNzbd's `File/<SabNzbdDownloadTitle>`.  There are no mdeia files, only par files.  And from the contents of the NZB file in SabNzbd's `File/<SabNzbdDownloadTitle>/_ADMIN_/<SabNzbdDownloadTitle>.gz` file.  In all cases, the NZB files in the gz files, have been the NZB files for the show's Par files, not the NZB files for the show's media files.

I would suggest, if there are multiple matching NZB listings, that only differ after the [X/X] post counter, possibly combine all of them as one NZB file before submitting them to SabNzbd.

The last example of this that I encountered was America's Got Talent S10E05 [556739].
Post titles:
[#scnzb@efnet][556739] Americas.Got.Talent.S10E05.720p.WEBRip.x264-NBC [27/29] - "Americas.Got.Talent.S10E05.720p.WEBRip.x264-NBC.vol00+8.par2" yEnc (1/105)

[#scnzb@efnet][556739] Americas.Got.Talent.S10E05.720p.WEBRip.x264-NBC [1/29] - "americas.got.talent.s10e05.720p.webrip.x264-nbc.nfo" yEnc (1/1)

If my analysis of this problem is accurate, if someone can direct me where to look in the scripts, I can probably fix it...

On a side note, I really miss SickBeard's SabNzbd download titles.  Instead of just a numeric title, they used the show name and episode numbers.  It was nice to be able to glance at SabNzbd's download list to figure out what new shows were available.

**Comment by syaeger** [comment]
The file names in my last message were mangle during the post.  They should have been 
SabNzbd's "File/99999999/" and "File/99999999/ADMIN/99999999.nzb.gz.  With underscores around the ADMIN folder name.

**Comment by miigotu** [comment]
Which indexer is doing this?

**Comment by syaeger** [comment]
If by indexer you mean NZB Search provider, I only have BinSearch selected.

Good news, last night, a show downloaded almost correctly.

**Comment by fernandog** [comment]
or its fake releases or bad SabNzbd setup

**Comment by syaeger** [comment]
SabNzbd has been running fine on this machine, with manual downloads, SickBeard, and CouchPotato for years.  This is the SabNzbd stats line, since the last update

0 B Today    3.6 GB This week    36.4 GB This month    411.4 GB Total

I know the show release posts SickRage is choosing are valid.  I've been manually downloading the same post's NZB files for the show and the NZB files for the Par files, from the BinSearch.info web site.  And successfully retrieving the shows, by feeding the NZB files to the SabNzbd watch folder.

When the problem occurs, it is pretty obvious from SabNzbd's cache, that SIckRage didn't send SabNzbd the NZB file for the Show, it just sent SabNzbd the NZB file for the Show's Par files.

If I download the show's pars nzb file from BinSearch.info, and do a compare against the NZB file SickRage sent to SabNzbd, the files are virtually identical.  There are only 7 characters in one comment line, that are different...

This is the comment line in the NZB file from SickRage


This is the comment line in the NZB file downloaded directly from BinSearch.info's web site.


I originally thought it might be a timing issue.  Maybe the par file post arrived to BinSearch.info prior to the media file post (even though the BinSearch.info web site lists them in the correct order).  So I modified the _get_title_and_url routine in BinSearch.py file to log all the titles that SickRage receives from BinSearch.info.  And both the Par posts and Media posts were added to the cache.  (This turned out to be a really quick way to fill up a bunch of SickRage log files)

**Comment by syaeger** [comment]
Once again, I should have done a preview...

This is the line that was different in the NZB files... (with the angle brackets and comment exclamation mark removed)

This is the line from the SickRage NZB file (found in SabNzbd's temp folders)
-- NZB Generated by Binsearch.info --

This is the line from the Show's Par NZB file, from the BinSearch.info web site.
-- NZB Generated by Binsearch.info (fcgi) --

The only difference between the NZB files is the (fcgi), all the post references are identical.  So I'm pretty sure the NZB file that SickRage sent to SabNzbd is just the NZB file for the show's par files.

**Comment by miigotu** [comment]
use ``` ` ```and ``` ` ``` to wrap tags to prevent the markdown from parsing them out.

I'll look into this after a few other things are cleared up, as it is only a binsearch provider problem.

**Comment by syaeger** [comment]
Thanks!  

This is probably not the right place for this, but are any of the other SickRage supported NZB Search providers free?

**Comment by miigotu** [comment]
usenet-crawler, and some others.

**Comment by miigotu** [comment]
nzbcat has free invites right now.

https://nzb.cat/invites

**Comment by miigotu** [comment]
@fernandog

**Comment by fernandog** [comment]
Maybe we can add a new div about nzbcat and rarbg. What do you think?

**Comment by miigotu** [comment]
div?

**Comment by fernandog** [comment]
Yes. Im provider list. Label/div something like that

**Comment by miigotu** [comment]
Idk what you mean, they already show in the provider list for me in the ui. I do need to add an icon for nzbcat though.
