### ISSUE TITLE
[APP SUBMITTED]: Proper instance has no attribute 'resultType'

### ISSUE THREAD

**Issue by hulubi** [SiCKRAGETV/sickrage-issues#1890]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 10:19:51) [GCC 4.3.6]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@207bd7ac693e4beee0b72d4d3a05e0c7aca95300
No Log available with ERRORS: 
### ERROR
```
FINDPROPERS :: Exception generated in thread FINDPROPERS: Proper instance has no attribute 'resultType'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by eph2112** [comment]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@207bd7ac693e4beee0b72d4d3a05e0c7aca95300
No Log available with ERRORS: 
### ERROR
```
FINDPROPERS :: Exception generated in thread FINDPROPERS: Proper instance has no attribute 'resultType'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Was fixed on Develop.
Please switch to develop to test or wait till its on master.

https://github.com/SiCKRAGETV/SickRage/issues/2005

**Comment by klutchrider** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@207bd7ac693e4beee0b72d4d3a05e0c7aca95300
No Log available with ERRORS: 
### ERROR
```
FINDPROPERS :: Exception generated in thread FINDPROPERS: Proper instance has no attribute 'resultType'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Please update, master merged early and a new release due to massive amount of changes.
