### ISSUE TITLE
[Feature Request] Move+symlink post processing option

### ISSUE THREAD

**Issue by degtyarev708** [SiCKRAGETV/sickrage-issues#1891]
Currently the only space efficient way to organize while also keeping the seed (That I know of) is to symlink from the download folder to the organized series folder. This is great until you wish to start deleting shows or stop seeding, and it becomes fiddly at best with large libraries. Ideally, Id request an option to move the file, rename/organize it, and then sym/hardlink it back to the original torrent folder with the original name for seeding.

**Comment by fernandog** [comment]
don't see this happening any time soon. too complicated

**Comment by frriction** [comment]
well for me it is always what you described. 
say for tv torrent; I use rtorrent which download file in /media/pendrive/rtorrent/tv when download finishes rtorrent calls for nzbtomedia script this script calls sickrage to postprocess finished download. Sickrage copy file to destination(appropriate series and season) folder than it creates symlink to original download folder so rtorrent keep seeding. If I want to remove any torrent I just delete that symlink in original download folder.
side note - I do not rename any file I just keep original file name; I like it that way.

**Comment by miigotu** [comment]
@degtyarev708 If you just put your downloads/completed folder on the same partition as the library, and use hard links method, there is no issue. Delete file from downloads folder and it is still valid in the show library. This only uses the bytesize of the new filename/location per hardlink on the filesystem.
IE: `len('/your/new/path/filename.ext')`

Symlink would not work this way, unless you copy first like you said and create a reverse symlink

It would be easy to add a checkbox someday when you have:

move selected:
[ ] Create symlink with original filename at previous location?

or symlink selected:
[ ] Move and then create symlink with original filename at previous location?

This is not anywhere near a priority ofcourse, as there is easy enough ways to do this in a normal way.

**Comment by WebSpider** [comment]
I actually have implemented this using standard SR functionality:

1) Torrent client downloads to /download/series/complete
2) Torrent client fires off TorrentToMedia which hardlinks this in /postproc/series/
3) SickRage prostprocs this in /postproc/series, hardlinks in /media/series/Serie/Season/episode.mkv and cleans up /postproc/series
4) When the torrent is removed from the client, it gets removed from /download/series/complete, leaving the only copy in /media/series/...

If I'm reading your request correctly, this is what you want, right?

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
