### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by MGaetan89** [SiCKRAGETV/sickrage-issues#1893]
Changes have not been provided since version 4.0.18. Latest version is 4.0.28. Is it possible to update it?

https://github.com/SiCKRAGETV/SickRage/blob/master/CHANGES.md

**Comment by fernandog** [comment]
@MGaetan89 if you - or someone else - want to help:

https://github.com/SiCKRAGETV/SickRage/compare/v4.0.18...v4.0.19
https://github.com/SiCKRAGETV/SickRage/compare/v4.0.19...v4.0.20
etc...

Direct link to edit the file:
https://github.com/SiCKRAGETV/SickRage/edit/develop/CHANGES.md
