### ISSUE TITLE
[APP SUBMITTED]: Thread-57 :: No Show Object found for show with indexerID: 80337

### ISSUE THREAD

**Issue by stephert** [SiCKRAGETV/sickrage-issues#1895]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 13:42:00) [GCC 4.6.4]**
Operating System: **Linux-2.6.32.12-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@207bd7ac693e4beee0b72d4d3a05e0c7aca95300
Link to Log: https://gist.github.com/00e4a16540ba075d610b
### ERROR
```
Thread-57 :: No Show Object found for show with indexerID: 80337
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
This can happen if you remove a show.Try a restart and see if that solves it. 
If not try to remove the cache folder, and mass-update the shows.

**Comment by miigotu** [comment]
This can happen if you delete a show, but have the show's details page open in another tab or browser.

**Comment by fernandog** [comment]
Or the show is in search/update/refresh queue
