### ISSUE TITLE
[APP SUBMITTED]: an integer is required

### ISSUE THREAD

**Issue by maxcore** [SiCKRAGETV/sickrage-issues#1896]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@ad4e3939c3d2942a0e7ac887670bb97f10017d63
Link to Log: https://gist.github.com/48793307357c6a5d78c4
### ERROR
```
SHOWQUEUE-ADD :: Unable to find show ID:296299 on Indexer: theTVDB
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by maxcore** [comment]
'''''
AATypeError: an integer is required
AA    data = data.replace(u"&amp;", u"&")
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tvdb_api/tvdb_api.py", line 671, in _cleanData
AA    v = self._cleanData(v)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tvdb_api/tvdb_api.py", line 917, in _getShowData
AA    self._getShowData(key, self.config['language'], True)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tvdb_api/tvdb_api.py", line 948, in __getitem__
AA    s = t[self.indexer_id]
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/show_queue.py", line 263, in run
AATraceback (most recent call last):
2015-06-26 00:10:46 ERROR    SHOWQUEUE-ADD :: Unable to find show ID:296299 on Indexer: theTVDB 
'''

**Comment by neoatomic** [comment]
Probably the show is not added properly on the indexer. (Missing data like air-date etc.) 
Also might be related to. : https://github.com/SiCKRAGETV/sickrage-issues/issues/1895

**Comment by maxcore** [comment]
@neoatomic thx to reply

**Comment by Noktam** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.8**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@417086030799e8b255872b5c2c03fee8ca065167
Link to Log: https://gist.github.com/33554ba71d379288d02a
### ERROR
```
Thread-26 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 251, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 2156, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/opt/sickrage/sickbeard/processTV.py", line 273, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/opt/sickrage/sickbeard/processTV.py", line 555, in process_media
    result.result = processor.process()
  File "/opt/sickrage/sickbeard/postProcessor.py", line 1101, in process
    cur_ep.airdateModifyStamp()
  File "/opt/sickrage/sickbeard/tv.py", line 2539, in airdateModifyStamp
    filemtime = datetime.datetime.fromtimestamp(os.path.getmtime(self.location)).replace(network_timezones.sb_timezone)
TypeError: an integer is required

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
