### ISSUE TITLE
readme.md Broken!

### ISSUE THREAD

**Issue by Arcanemagus** [SiCKRAGETV/sickrage-issues#1898]
A recent commit (https://github.com/SiCKRAGETV/SickRage/commit/cbb37fc4d4a2666f67b49f03b50987f864b6d60d) broke the readme.md file for the project.

Since for some reason the correct file is named `readme.md` instead of the standard `README.md` when that commit created the `README.md` file github.com prefers it instead of the good one.

When checking out the project on Windows it continuously thinks there is a pending change since it keeps swapping the files as it isn't case sensitive.

The correct file can be found here: https://github.com/SiCKRAGETV/SickRage/blob/master/readme.md
The file from the broken commit is here: https://github.com/SiCKRAGETV/SickRage/blob/master/README.md

**Comment by Arcanemagus** [comment]
For reference this commit was part of https://github.com/SiCKRAGETV/SickRage/pull/2003.

**Comment by fernandog** [comment]
@miigotu can you revert only the readme change?

**Comment by miigotu** [comment]
That was already fixed, in both master and develop
