### ISSUE TITLE
NZBCat error snatching NZBs

### ISSUE THREAD

**Issue by jotavip** [SiCKRAGETV/sickrage-issues#1899]
Hi, I am using Sickrage in my QNAP 269 Pro, and I am having the following error when trying to search a release with the NZBCat indexer: 

Branch: master
Commit: ae2c0e8006
Operating System: QNAP, Python 2.7
```
2015-06-26 04:06:22 WARNING  SEARCHQUEUE-MANUAL-255326 :: Unknown exception in headURL https://nzb.cat/getnzb/a0004b5b41ea3d85a39a1b7203ba838cbaa2ac9e.nzb&i=2336&r=**********
2015-06-26 04:06:22 INFO     SEARCHQUEUE-MANUAL-255326 :: Quality of Defiance.S03E03.Broken.Bough.1080p.WEB-DL.DD5.1.H.264-ECI.English is 1080p WEB-DL
2015-06-26 04:06:19 INFO     SEARCHQUEUE-MANUAL-255326 :: [NZBCat] :: Performing episode search for Defiance
2015-06-26 04:06:19 INFO     SEARCHQUEUE-MANUAL-255326 :: Building internal name cache for Defiance
2015-06-26 04:06:19 INFO     SEARCHQUEUE-MANUAL-255326 :: Beginning manual search for: [Defiance - 3x03 - The Broken Bough]
```
I tried to reinstall sickrage from scratch, and it doesn't helped. My friend has a QNAP and he installed and configured Sickrage the same way as I did, and he isn't experiencing this error using NZBCat.

Anyone knows how to fix that? 

Thanks for the help

**Comment by neoatomic** [comment]
@jotavip Follow the guidelines for posting an issue. : 
https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket

**Comment by fernandog** [comment]
SSL issues

https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors

**Comment by jotavip** [comment]
@fernandog  Thanks for the reply

I tried the solution for QNAP from the SSL Error link, and it didn't worked. I receive the following error after using the curl command:

`</tmp/tmpWpn0I5/pip.zip/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
Collecting pip
/tmp/tmpWpn0I5/pip.zip/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
/tmp/tmpWpn0I5/pip.zip/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  Could not find a version that satisfies the requirement pip (from versions: )
No matching distribution found for pip>`

**Comment by fernandog** [comment]
@miigotu do you know what's going on?

**Comment by miigotu** [comment]
SSL problem, check qnap forums about a python 2.7.9 package.
