### ISSUE TITLE
Error in log when checking for update with no internet

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#19]
<a href="https://github.com/markheloking"><img src="https://avatars.githubusercontent.com/u/3192761?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [markheloking](https://github.com/markheloking)**
_Thursday Nov 27, 2014 at 08:40 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/963 (1 comment(s))_

----

Not exactly sure if it's an error since the error itself is correct, but maybe it should be a warning instead of an error? Right now my log is filling with errors because it's running on a laptop, so whenever I'm on the go, I get these messages a lot filling up my logs.

BRANCH: (master) / COMMIT: (e31db5359248814cd6d3836f47b5f8019641be5e) 
Win7 64bit (SP1), Chrome, python 2.7 with namemapper windows native 2.5

It gives me an error when trying to auto-check for updates because it can't contact github when no internet.
I expect it to check for internet (ping google or whatever), and when there's no internet it should skip the error (give a warning maybe?), because it's obvious there's no connection. This way there's no "Logs & Errors (100)", and makes it so we can differentiate between just no internet and an actual error.

```
2014-11-27 09:27:38 CHECKVERSION :: Unable to contact github, can't check for update: gaierror(11004, 'getaddrinfo failed')
```

**Comment by fernandog** [comment]
Fixed with:
```
        try:gh = Github(user_agent="SiCKRAGE").get_organization(GIT_ORG).get_repo(GIT_REPO)
        except:gh = None
```
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/__init__.py#L576

**Comment by markheloking** [comment]
Yesterday, these errors occured when I was out with my laptop (so not internet connection sometimes):

```
2015-03-19 11:03:41 CHECKVERSION :: Unable to contact github, can't check for update: gaierror(11004, 'getaddrinfo failed')
2015-03-18 22:40:26 CHECKVERSION :: Unable to contact github, can't check for update: gaierror(11004, 'getaddrinfo failed')
```

RIght now on BRANCH: (master) / COMMIT: (cc4896e96a27dda5cc9ed198209aa514bf68a4eb) , win 7 x64, python 2.7.8.

**Comment by fernandog** [comment]
@markheloking that error is not a system error. there's nothing to be merged in master about this issue

**Comment by markheloking** [comment]
So my issue is a new one? What are you saying?

**Comment by abeloin** [comment]
@markheloking I think what he meant to say is that it's reported as an error in the system but would should consider it as a warning.

The issue stem from the fact that we don't make distinction between system error and user error.

Example: Currently, if the post-process fail because of a permission issue it is currently treated as an error but in fact it should be treated as user error. The same thing happens here, the user should be notified that reaching github didn't work but shouldn't be in the system error.
