### ISSUE TITLE
[APP SUBMITTED]: cannot concatenate 'str' and 'NoneType' objects

### ISSUE THREAD

**Issue by StretchCell** [SiCKRAGETV/sickrage-issues#1903]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@ae2c0e8006bf0c8ec3d3379148a951847b2c5f39
Link to Log: https://gist.github.com/253a6cb85131576dd7eb
### ERROR
```
Thread-17 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 1147, in branchCheckout
    return self.update(sickbeard.PID)
  File "C:\SickRage\sickbeard\webserve.py", line 1131, in update
    if sickbeard.versionCheckScheduler.action.update():
  File "C:\SickRage\sickbeard\versionChecker.py", line 269, in update
    return self.updater.update()
  File "C:\SickRage\sickbeard\versionChecker.py", line 781, in update
    notifiers.notify_git_update(sickbeard.NEWEST_VERSION_STRING)
  File "C:\SickRage\sickbeard\notifiers\__init__.py", line 111, in notify_git_update
    n.notify_git_update(new_version)
  File "C:\SickRage\sickbeard\notifiers\plex.py", line 155, in notify_git_update
    self._notify_pmc(update_text + new_version, title)
TypeError: cannot concatenate 'str' and 'NoneType' objects

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
check your notifications settings for the provider you enabled. use the test button

**Comment by StretchCell** [comment]
Success: Connected and Authenticated
but still the same issue.

**Comment by neoatomic** [comment]
Looks like the log error and the posted error are not the same.?

@StretchCell Disable all notification clients  (plex etc.) And see if that solves it.
The error in the log looks like a special character problem.

Both errors can be the result of a bad installation. Here is a good guide for installing SR on a Windows machine. : 
http://www.htpcguides.com/install-sickrage-windows-usenet-torrent-tv/
