### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-MANUAL-259765 :: rTorrent: Unable to send Torrent: Return code undefined

### ISSUE THREAD

**Issue by HakShak** [SiCKRAGETV/sickrage-issues#1904]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 23:30:53) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@ae2c0e8006bf0c8ec3d3379148a951847b2c5f39
Link to Log: https://gist.github.com/feea9eca2795a626e6c3
### ERROR
```
SEARCHQUEUE-MANUAL-259765 :: rTorrent: Unable to send Torrent: Return code undefined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by HakShak** [comment]
This is a bit more interesting because nothing has changed in lib/rtorrent.

However, I do know when this was introduced: I upgraded from 2d515e9aa4aea0ec1798289df691cd5e949828ed to ae2c0e8006bf0c8ec3d3379148a951847b2c5f39

The other interesting part, is that the magnet gets sent to rtorrent, but it never gets started, nor labeled, nor put in the correct folder.

**Comment by raymondtrueman** [comment]
My shows aren't snatching due to this issue, it started today. Hopefully we can figure it out. I'm trying some debugging, but so far no luck

**Comment by fernandog** [comment]
disable proxy

**Comment by fernandog** [comment]
disable proxy

**Comment by HakShak** [comment]
Which proxy are you referring to?

**Comment by fernandog** [comment]
all: proxy host in General settings and proxy in providers settings

**Comment by HakShak** [comment]
I don't have any of those fields populated.

On an unrelated note, this *might* just be for manual searches. I've haven't updated and automatic searches have been able to properly snatch files.

**Comment by fernandog** [comment]
the code it's the same. maybe this torrent from issue was a bad one

**Comment by HakShak** [comment]
Unfortunately something is different, the daily search worked, then when I removed the file and did a manual search for the same torrent. The manual search added the torrent to rtorrent, but failed to start it with the exact same error as above.

**Comment by fernandog** [comment]
@HakShak 
enabled DEBUG in SR settings, stop SR, delete all files in /Logs folder, start SR, do that again, send full logs

**Comment by HakShak** [comment]
Done: http://pastebin.com/RdRLh0iT

**Comment by fernandog** [comment]
the only time is "Calling rTorrent Client" is in manual search.
there's no info about daily-search

please force a daily search in /manage/manageSearches/

**Comment by HakShak** [comment]
Not sure how to force an already downloaded file into daily search. I marked it as wanted and it just ended up in the back log. Any idea how to do that? I assume the entire idea here was to test a torrent that already downloaded successfully.

**Comment by fernandog** [comment]
use the manual search. go to show page and click the magnifying glass. anwser the pop questions

**Comment by HakShak** [comment]
Yes, I'm aware of that l, but you wanted a known working daily search. In order to get a known working daily search I would have to reset an existing download. When I posted the log with just the manual search you mentioned that you wanted to see it with a daily search.

In order to get a known working daily search in the log I would have to do something to unflag it as downloaded, bit once I do that it becomes a backlog search.

How do I force an already downloaded show into a daily search without it going into manual or backlog queues?

**Comment by fernandog** [comment]
when you MS, SR already clears everything. It set as WANTED and clear the previous release name from DB
