### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-DAILY-SEARCH :: rTorrent: Unable to send Torrent: Return code undefined

### ISSUE THREAD

**Issue by raymondtrueman** [SiCKRAGETV/sickrage-issues#1905]
### INFO
Python Version: **2.7.10 (default, Jun  4 2015, 01:18:03) [GCC 4.3.2]**
Operating System: **Linux-2.6.32.12-ppc-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@ae2c0e8006bf0c8ec3d3379148a951847b2c5f39
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: rTorrent: Unable to send Torrent: Return code undefined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by gormson** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.9**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@7b6040b3a706331bac4bf7ec5dc8b8d2845bf0b4
Link to Log: https://gist.github.com/44f2327b538d635e4911
### ERROR
```
SEARCHQUEUE-MANUAL-282670 :: [T411] :: rTorrent: Unable to send Torrent: Return code undefined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by gormson** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.9**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@7b6040b3a706331bac4bf7ec5dc8b8d2845bf0b4
Link to Log: https://gist.github.com/0a7e8c7fcf767892f560
### ERROR
```
SEARCHQUEUE-BACKLOG-282670 :: [T411] :: rTorrent: Unable to send Torrent: Return code undefined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
