### ISSUE TITLE
[APP SUBMITTED]: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/257049/en.xml

### ISSUE THREAD

**Issue by hadees** [SiCKRAGETV/sickrage-issues#1909]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-38-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@ae2c0e8006bf0c8ec3d3379148a951847b2c5f39
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-ADD :: Unable to find show ID:257049 on Indexer: theTVDB
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by hadees** [comment]
Basically it never stops trying to load this show and I have no way of deleting it.

**Comment by neoatomic** [comment]
It can happen when the show gets bad info from the indexer or when you remove that show.
Here are some things you can try. : 

* Do a reboot.
* See if you can re-add the show and than delete again.  
* Try mass-update and select "update" for all shows.
* Delete the cache folder

**Comment by hadees** [comment]
@neoatomic I followed your link and even though the artwork is showing up the series doesn't look right to me on TVDB.  There is no information or title.  I think it was deleted but there might still be an issue on their side.

**Comment by hadees** [comment]
I think the mass-update worked though, I'm fairly certain I was able to delete it.

**Comment by hadees** [comment]
Actually I'm wrong, i'm still having an issue with UFC Fight Night although i'm less certain that it's 257049

**Comment by hadees** [comment]
@neoatomic it looks like I might be having a problem with "Wet Hot American Summer: First Day of Camp" as well and that was a TV Rage show.  I'm wondering if the system is confused between TVRage and TVDB shows somehow.  I tried deleting the cache and it didn't help.

**Comment by neoatomic** [comment]
@hadees If removing those shows doesnt help than the database might got corrupted. Than you can only restore a backup (hope you made one?) or you have to create a new database from scratch...

**Comment by hadees** [comment]
@neoatomic I don't have a backup before that problem started but I assume the config and database are separate right? I'd rather not loose all my config settings but I'm alright clearing out all the shows and adding them via the file system again.

**Comment by fernandog** [comment]
Do you use trakt and have sync enabed?
if you do, remove that show from watchlist

**Comment by miigotu** [comment]
Deleting databases and cache won't reset your settings, just make sure you don't delete config.ini.

Make sure to create some metadata files for your shows from inside sickrage, so they add back in one click. (PP settings, metadata tab on ip:port/config/postProcessing/ enable a metadata type like kodi_12+ show metadata)

You can remove sickbeard.db.* cache/ and cache.db* to start with fresh databases and re-add all your shows.

First boot creating the cache may take 5 or so minutes.

**Comment by fernandog** [comment]
Show dont exist in indexer. Remove from watchlist
