### ISSUE TITLE
PDTV Question

### ISSUE THREAD

**Issue by Vodka2014** [SiCKRAGETV/sickrage-issues#1911]
Hi,

I have noticed that Masterchief is airing as PDTV and not SDTV. Is there any chance that PDTV can get added to the categories. 

If it can get added like:

PDTV
SDTV
SDTV + PDTV (SDTV Takes Priority Over PDTV But PDTV Will Still Download If There Is No SDTV)

Just a thought since I had to grab them manually.

Thanks

**Comment by miigotu** [comment]
Nope, PDTV without the 720p/1080i tag is SDTV. It is too much changes to add another quality at this time. We have much bigger things to worry about, sorry.
