### ISSUE TITLE
[Feature Request] Remove support for python 2.6

### ISSUE THREAD

**Issue by miigotu** [SiCKRAGETV/sickrage-issues#1915]
Updating libraries in SR is becoming difficult to do because of our current requirement of remaining compatible with Python 2.6. This requires constant patching of libraries which no longer support Python 2.6, and most of them have dropped 2.6 compatibility.

From PEP 361:
```
Python 2.6.9 is the final security-only source-only maintenance
release of the Python 2.6 series.  With its release on October 29,
2013, all official support for Python 2.6 has ended.  Python 2.6
is no longer being maintained for any purpose.
```

I need feedback from any users using SR who are locked into using Python 2.6.

**Comment by fernandog** [comment]
I agree

**Comment by MGaetan89** [comment]
I'm fine with it. What would be the new minimum supported version? 2.7?

**Comment by miigotu** [comment]
Yes

**Comment by MGaetan89** [comment]
That's fine for me

**Comment by fernandog** [comment]
@neoatomic NAS has already updated to > 2.6?

**Comment by MGaetan89** [comment]
Mine uses Python 2.7 (Synology DS414).

**Comment by neoatomic** [comment]
@fernandog  Yes, running Python Version: 2.7.10. (and Python 3 is also there.)
Software is very well supported/updated by Synology/community so i dont expect any problems for Synology users.

I'm also in favor of doping support for older versions, and when possible implement support for Python3 as miigotu suggested before. 

(Actually cant even remember the last time i saw an issue/ticket that had Py 2.6 running)

**Comment by fernandog** [comment]
about python3, for now I don't agree. RPI don't have it support. also KODI and CP still uses 2.7 so let's keep it until we see a moviment to PY3

**Comment by miigotu** [comment]
@fernandog when we add support for Py3, we will still support Py2.7, probably for years. The only thing that makes us not able to use Py3 atm is cheetah afaik, but switching to mako requires mass changes in the gui templates to convert them to mako.

**Comment by fernandog** [comment]
I see. thanks

**Comment by bartley69** [comment]
Python Version:	2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]

I think I'm fine :D

**Comment by Kybber** [comment]
Sickrage stopped working today on my CentOS 6.6 host. I assume the 2.7 requirement is the reason. CentOS 6.6 uses Python 2.6.6, and updating to Python 2.7 is not trivial since that will break the system, including yum. Python 2.7 therefore needs to be installed in non-standard ways such as described here: http://toomuchdata.com/2014/02/16/how-to-install-python-on-centos/

Also, the 2.7 requirement invalidates this howto by @miigotu : https://github.com/SiCKRAGETV/SickRage/wiki/Installation-Instructions

The problem I am experiencing happens then I start the service:
```
[root@secure sickrage]# service sickrage start
Starting sickbeard: Traceback (most recent call last):
  File "/opt/sickrage/SickBeard.py", line 89, in <module>
    import sickbeard
  File "/opt/sickrage/sickbeard/__init__.py", line 37, in <module>
    from sickbeard import providers, metadata, config, webserveInit
  File "/opt/sickrage/sickbeard/providers/__init__.py", line 59, in <module>
    import generic
  File "/opt/sickrage/sickbeard/providers/generic.py", line 32, in <module>
    from sickbeard import helpers, classes, logger, db
  File "/opt/sickrage/sickbeard/helpers.py", line 73, in <module>
    from sickbeard.subtitles import isValidLanguage
  File "/opt/sickrage/sickbeard/subtitles.py", line 29, in <module>
    import subliminal
  File "/opt/sickrage/lib/subliminal/__init__.py", line 9, in <module>
    from .api import list_subtitles, download_subtitles, download_best_subtitles                       , save_subtitles
  File "/opt/sickrage/lib/subliminal/api.py", line 9, in <module>
    from .providers import ProviderPool
  File "/opt/sickrage/lib/subliminal/providers/__init__.py", line 9, in <module>
    from ..video import Episode, Movie
  File "/opt/sickrage/lib/subliminal/video.py", line 10, in <module>
    import guessit
  File "/opt/sickrage/lib/guessit/__init__.py", line 88, in <module>
    from guessit.guess import Guess, smart_merge
  File "/opt/sickrage/lib/guessit/guess.py", line 29, in <module>
    from guessit.textutils import common_words
  File "/opt/sickrage/lib/guessit/textutils.py", line 250
    _camel_word2_set = {'is', 'to'}
                            ^
SyntaxError: invalid syntax
```
Anyway, I am assuming the error above is due to the 2.7 requirement, and will initiate an installation of 2.7 according to the link above to try and fix it. Or upgrade my server to CentOS 7, which will be a massive pita at this time.

**Comment by MGaetan89** [comment]
Python 2.6 is still supported for the moment.
I think this issue is related to https://github.com/SiCKRAGETV/SickRage/commit/b387dc9741697259d87abd3ffb741522fc4ed68d
Any idea @miigotu ?

**Comment by Kybber** [comment]
Nice catch, it certainly looks like that is the case. From https://docs.python.org/2/library/stdtypes.html:
    As of Python 2.7, non-empty sets (not frozensets) can be created by placing a comma-separated list of elements within braces, for example: {'jack', 'sjoerd'}, in addition to the set constructor.

I amended lib/guessit/textutils.py to use the set-constructor and that seems to be the only thing in need of fixing so far. 

Any chance lib/guessit/textutils.py could be reversed upstream to retain 2.6-support for now without requiring me (and other CentOS 6-users) to freeze and manually patch similar uses of set()?

**Comment by miigotu** [comment]
@Kybber installing python 2.7 will not break your system. Python 2.6 and 2.7 are independent of each other. You just don't want to change the python2 link to point to 2.7. Instead, install python 2.7 and change your startup of SickRage to start with the `python2.7` executable instead of the `python2` executable (actual names of the binaries).

**Comment by miigotu** [comment]
http://toomuchdata.com/2014/02/16/how-to-install-python-on-centos/

Python 2.6 will no longer be actively supporting in SR. If you have breakage because of that, monkey patch or get 2.7 somehow and make SR run with 2.7.
