### ISSUE TITLE
[APP SUBMITTED]: 'module' object has no attribute 'core'

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#1916]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:34:55) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-21-generic-i686-with-Ubuntu-15.04-vivid**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@0f0c920d22788a7609170f069f4283e2908ed430
Link to Log: https://gist.github.com/10a7fa08e2b60e00e958
### ERROR
```
FINDSUBTITLES :: Exception generated in thread FINDSUBTITLES: 'module' object has no attribute 'core'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by matigonkas** [comment]
traceback #2015-06-28 18:14:28 DEBUG    CHECKVERSION :: git symbolic-ref -q HEAD : returned successful
AAAttributeError: 'module' object has no attribute 'core'
AA    servicesMapping = dict([(x.lower(), x) for x in subliminal.core.SERVICES])
AA  File "/home/super******/SickRage/sickbeard/subtitles.py", line 33, in sortedServiceList
AA    return [x['name'] for x in sortedServiceList() if x['enabled']]
AA  File "/home/super******/SickRage/sickbeard/subtitles.py", line 54, in getEnabledServiceList
AA    if len(sickbeard.subtitles.getEnabledServiceList()) < 1:
AA  File "/home/super******/SickRage/sickbeard/subtitles.py", line 93, in run
AA    self.action.run(self.force)
AA  File "/home/super******/SickRage/sickbeard/scheduler.py", line 97, in run
AATraceback (most recent call last):
2015-06-28 18:14:28 ERROR    FINDSUBTITLES :: Exception generated in thread FINDSUBTITLES: 'module' object has no attribute 'core'

**Comment by miigotu** [comment]
Mid upgrade to new subliminal. Will try to finish tonight, otherwise I will revert.
