### ISSUE TITLE
Sickrage returning no results for any show

### ISSUE THREAD

**Issue by Ruddy2007** [SiCKRAGETV/sickrage-issues#1918]
Branch: Master
Commit hash: ae2c0e8006bf0c8ec3d3379148a951847b2c5f39
Operating system: Windows 7 (SP1)
Python version:  2.7.10
What you did: Search for any show.(usenet)
What happened: Get notification "No downloads were found".
What you expected: Downloads automatically start downloading for wanted episodes.
Link to log file: https://gist.github.com/Ruddy2007/30ff82ae0f23c2ccd577

So everything I search for returns no results at all. I have tried to reinstall everything, used the master and development builds, tried different providers and nothing has fixed this issue. Any help with this would be good, I can't seem to solve this by myself.

**Comment by miigotu** [comment]
Use a different indexer.

**Comment by Ruddy2007** [comment]
It turns out I was indeed reaching the limit for requests on the added indexers, but this does not explain why sick beard index was not working and still is not.

**Comment by miigotu** [comment]
Because Sick Beard Index blocks SR completely.

**Comment by Ruddy2007** [comment]
Thats odd as I know someone that it seems to work for. Anyway thanks for your help, everything seems to be working now.

**Comment by miigotu** [comment]
Sorry, Sick Beard Index is blocking backlog searching, the RSS/Daily is working I think.
