### ISSUE TITLE
[APP SUBMITTED]: ('Connection aborted.', gaierror(11001, 'getaddrinfo failed'))

### ISSUE THREAD

**Issue by mbxplex** [SiCKRAGETV/sickrage-issues#1919]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@ae2c0e8006bf0c8ec3d3379148a951847b2c5f39
Link to Log: https://gist.github.com/0a53980c656f40e0a08e
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [AlphaRatio] :: Unable to connect to AlphaRatio provider: error ('Connection aborted.', gaierror(11001, 'getaddrinfo failed'))
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Intermittent issue
