### ISSUE TITLE
Default EP Status missing?

### ISSUE THREAD

**Issue by Alexwijn** [SiCKRAGETV/sickrage-issues#1925]
To simply put it, the select box is not at the edit page to change the Default Episode Status since the last update.

**Some other info:**
Python Version: 2.7.9 (default, Mar 8 2015, 00:52:26) [GCC 4.9.2]
Operating System: Linux-3.18.11+-armv6l-with-debian-7.8
Locale: UTF-8
Branch: master
Commit: SiCKRAGETV/SickRage@ae2c0e8

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1483#issuecomment-112876883
