### ISSUE TITLE
"Debug code" adding in weird html element to show page

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#1927]
I noticed what looks like debug code being added to the show page(/home/displayShow?show=0000). I'm assuming it's not meant to be there and a ``#`` is missing? [Here](https://github.com/SiCKRAGETV/SickRage/blob/42b8d5a9c71c87fcde301967b6254ef08c3093ac/gui/slick/interfaces/default/displayShow.tmpl#L123-L135)'s the code where it's coming from.

``<sqlite3.row object="" at="" 0x7feb6c679190="">``

![sqlite](https://cloud.githubusercontent.com/assets/6525926/8408095/5e4718f4-1eac-11e5-9916-6fd1315c06c6.PNG)

**Comment by fernandog** [comment]
@OmgImAlexis 
what appears in UI?

**Comment by OmgImAlexis** [comment]
Nothing that I can see I just thought it may be a bug as ``sqlite3.row`` isn't a HTML element and seems to just be a typo.

**Comment by fernandog** [comment]
probaly this line:
https://github.com/SiCKRAGETV/SickRage/blob/develop/gui/slick/interfaces/default/displayShow.tmpl#L135

        #if not $sickbeard.DISPLAY_SHOW_SPECIALS and $season_special:
            $seasonResults.pop(-1)
        #end if

@miigotu probaly pop(-1) is showing  an sqlite3 object. what have to be done here?

**Comment by miigotu** [comment]
Not really a bug, but yes pop returns the object that is popped. It must use pop because it is a dict and we don't know the key name there, and pop is also atomic.

To prevent this showing up, you could do `#set x = $seasonResults.pop(-1);del $x`

**Comment by OmgImAlexis** [comment]
Would this also be from this? I'm using SiCKRAGETV/SickRage@010325315d75ed7aab47619b57106bcca6d280f6

![screen shot 2015-07-13 at 6 48 09 pm](https://cloud.githubusercontent.com/assets/6525926/8646593/4657f4f4-2990-11e5-9681-a856f32e7e9b.png)
![screen shot 2015-07-13 at 6 48 03 pm](https://cloud.githubusercontent.com/assets/6525926/8646595/469f5c9a-2990-11e5-8d58-8e498cf8c8e4.png)

**Comment by miigotu** [comment]
@OmgImAlexis that is what https://github.com/SiCKRAGETV/SickRage/commit/30d2d9ac2f0267ea27073e9b41b86aed326db8fb fixed, which is only on develop branch atm. You are on master so you don't have the fix yet.

**Comment by OmgImAlexis** [comment]
All's good, it wasn't coming up before so I wasn't sure if it was related.

**Comment by miigotu** [comment]
Yeah, a few days ago he did a fix for the same thing, but it was incorrect and caused the # to show. The next fix made it go away.

**Comment by OmgImAlexis** [comment]
Alright, thanks.
