### ISSUE TITLE
[APP SUBMITTED]: global name 'time' is not defined

### ISSUE THREAD

**Issue by udochrist** [SiCKRAGETV/sickrage-issues#1928]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@ae2c0e8006bf0c8ec3d3379148a951847b2c5f39
Link to Log: https://gist.github.com/08586ed23e384f17fbcc
### ERROR
```
FINDPROPERS :: Exception generated in thread FINDPROPERS: global name 'time' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1901
