### ISSUE TITLE
Exception generated in thread FINDPROPERS: global name 'time' is not defined

### ISSUE THREAD

**Issue by nrk666** [SiCKRAGETV/sickrage-issues#1929]
This may be related to recent work from #1825 : 

2015-06-29 01:01:52 FINDPROPERS :: Exception generated in thread FINDPROPERS: global name 'time' is not defined

Didn't seem to affect functionality at all, just appeared in the Error Log.

**Comment by fernandog** [comment]
@nrk666 please only open errors using the "submit errors" in SickRage button

enter github user/pass at advanced settings.
