### ISSUE TITLE
The wrong torrent is snatched

### ISSUE THREAD

**Issue by lendenrk** [SiCKRAGETV/sickrage-issues#1933]
Branch : master
Commit hash : ae2c0e8006bf0c8ec3d3379148a951847b2c5f39
Your operating system and python version : Debian 3.2.54-2 x86_64 GNU/Linux (Python 2.7.3)

As you will see in the [LOG]  (https://gist.github.com/lendenrk/8d39d0d52e6fd337fd43) file, a weird thing happened to me few minutes ago.
After I added "Sherlock" to my shows list, it started searching for the episodes.
The searcher found 4 results for the first season. My settings are waiting for 720p quality and one of 4 results was matching it. In brief, it logged that the 720p BluRay S01 pack (Sherlock.S01.720p.BluRay.DD5.1.x264-CtrlHD in logs) was snatched when actualy the "DVDRip" version (Sherlock.S01.DVDRip.XviD-HAGGiS in logs) was sent to my rTorrent.

I'm trying to understard how it could happen but I've nothing...

Thank you.

https://gist.github.com/lendenrk/8d39d0d52e6fd337fd43

**Comment by fernandog** [comment]
from your log:

Any,Best = [ HDTV, 720p WEB-DL, 720p BluRay ] [ None ] Found = [ 720p BluRay ]

you set [ HDTV, 720p WEB-DL, 720p BluRay ] 
SR will snatch any of thie qualities. If found HDTVfirst will snatch it but then bluray come up, SR will snatch it too. If you only ONE download for any of this qualities you must set "Archive first match"

https://github.com/SiCKRAGETV/SickRage/wiki/Quality%20Settings

**Comment by lendenrk** [comment]
Are  you sure this is it? Because in the logs I also see : 
"2015-06-29 20:05:17 INFO SEARCHQUEUE-BACKLOG-176941 :: Quality of Sherlock.S01.DVDRip.XviD-HAGGiS is SD DVD"
SD DVD is not in my wanted qualities and this the one which was sent.

**Comment by fernandog** [comment]
@lendenrk try disable SEASON search for all your providers and try again

**Comment by lendenrk** [comment]
@fernandog Unfortunately this test will not be conclusive since the season 1 is only available in pack and there aren't separated episodes for this show and season on this tracker (I checked manually).
