### ISSUE TITLE
Manual search adds to daily queue 

### ISSUE THREAD

**Issue by copekyle** [SiCKRAGETV/sickrage-issues#1934]
SR Version: 	BRANCH: (master) / COMMIT: (ae2c0e8006bf0c8ec3d3379148a951847b2c5f39) 
Python Version:	2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]

So sickrage has been running smooth and so I haven't had to do a manual search lately.  When I run the manual search, it adds it to the daily search queue and I still have to wait 10 minutes before that manual search executes.  Is this intended behavior?  Also, why don't the logs show useful info anymore?  I used to be able to see the search string and failed search results in the logs.  Now I only can see this line (yes DB verbose level).

2015-06-29 17:36:22 INFO     DAILYSEARCHER :: No new released episodes found ...
2015-06-29 17:36:22 INFO     DAILYSEARCHER :: Searching for new released episodes ...

I never show a manual search in the logs. (which supports my thought that they are just being added to the daily queue)

**Comment by miigotu** [comment]
enable debug.

**Comment by copekyle** [comment]
Debug is set to a 1 in the config.ini file. Is there anywhere else I'm supposed to enable it?

**Comment by miigotu** [comment]
give full debug logs where you try a manual search for a single episode and I will show you.

**Comment by copekyle** [comment]
I change my verbosity to DB.  I press for a manual search.  The manual search area says "queued" and nothing new is showing in log.  I then wait for about 8-10 minutes and the search executes.  The only thing added to the log (with verbosity DB selected) are these two lines:

2015-06-30 17:06:41 INFO     DAILYSEARCHER :: No new released episodes found ...
2015-06-30 17:06:41 INFO     DAILYSEARCHER :: Searching for new released episodes ...

I check my server status and it shows my "show queue" and "search queue" executing every 3 seconds. 
The last manual search to happen was on 6-28.  I found this by searching the log for "Manual"

2015-06-28 21:17:46 DEBUG    SEARCHQUEUE-MANUAL-281714 :: Internal name cache for Ballers set to: [ ballers ]
2015-06-28 21:17:46 INFO     SEARCHQUEUE-MANUAL-281714 :: Building internal name cache for Ballers
2015-06-28 21:17:46 DEBUG    SEARCHQUEUE-MANUAL-281714 :: No scene exceptions update needed
2015-06-28 21:17:46 INFO     SEARCHQUEUE-MANUAL-281714 :: Beginning manual search for: [Ballers - 1x02 - Raise Up]

SO it appears that manual search does not work anymore.

**Comment by miigotu** [comment]
2015-06-28 21:17:46 INFO SEARCHQUEUE-MANUAL-281714 :: Beginning manual search for: [Ballers - 1x02 - Raise Up]

this means it IS working.

**Comment by copekyle** [comment]
It WAS working on 6-28.... It's 6-30.... It is NO LONGER WORKING.

**Comment by miigotu** [comment]
Nothing has changed for that in those 2 days.

**Comment by copekyle** [comment]
Except that it no longer works. I've shown you logs that show the manual
search is no longer working. I don't know what else to do. I've been using
sick rage for almost 3 years. I'm not a noob.

**Comment by miigotu** [comment]
Actually you haven't provided full logs, like I asked, and you are pasting log excerpts in replies which is not the place to put logs. Use gist or pastie or something. Nothing is added to the daily search queue.

**Comment by copekyle** [comment]
Alright, lets try again.  I shutdown sickrage, and deleted all my logs so they could be as clean as possible for you.  After sickrage was up, I tried a manual search.  The first manual search worked perfectly, only there were no torrents snatched (because none were available).  After running the first manual search, I tried another manual search on another show, this time the log showed:
2015-06-30 21:22:04 DEBUG    Thread-49 :: Not adding item, it's already in the queue

So now, every time I press manual search, I get that entry in my log.  My SR is no longer snatching any available shows, it's like the manual search locked everything up.

Here are my full logs from starting up:
http://pastebin.com/VdFafVnh

**Comment by miigotu** [comment]
1. Stop spamming manual search.
2. It's already in the search queue, so you cannot search it again until the queue has completed.

**Comment by miigotu** [comment]
https://gist.github.com/miigotu/3cfe7cdbb7794aca1f76

**Comment by copekyle** [comment]
Ok? How often is the manual search queue executed? I woke up this morning
and tried one manual search and the log said it was already in the queue.

**Comment by miigotu** [comment]
Then something in your queue is stuck, preventing the queue from processing, check the wrench->status page

**Comment by copekyle** [comment]
I show nothing in the "show queue".  See screenshot of status page:
http://s14.postimg.org/n9my5vrs1/sickrage.png
