### ISSUE TITLE
Sickrage episodes snatched but not downloading

### ISSUE THREAD

**Issue by sissipher** [SiCKRAGETV/sickrage-issues#1935]
I am running Windows 2012 Server and using qbittorrent 3.1.9.2 as my torrent downloader
I am not showing any errors in the error logs.  

When I go to get a show (ex: falling skies) it says it is snatched but the download will not start.  I have waited over 24hrs for the show to start downloading.

Everything was working fine a few weeks ago.  In fact, it says I have 8 shows total that are snatched but none have downloaded.

thank you for your help in advance

**Comment by fernandog** [comment]
follow guidelines https://github.com/SiCKRAGETV/sickrage-issues
when you do will reopen

**Comment by sissipher** [comment]
I followed the guidelines.  However no logs are happening when I entered 1 for debug.  I rebooted the computer as well.  I am a software tester so please work with me.  I don't have any error logs and that is why I am confused.

Branch = (master)
Commit hash = /Commit: (ae2c0e8006bf0c8ec3d3379148a951847b2c5f39)
Your operating system and python version = OS Widows 2012 Server/Python 2.7.8
What you did = In Sickrage I clicked on Shows and then a show.  I went in and selected a show I did not have.  
What happened = It snatched the show.  It stayed snatched for over 24hrs and never downloaded.
What you expected = I expected the show to start downloading in qbittorrent v.3.1.9.2 as all other shows a month ago and previous did.

Please let me know if you need any more information.

I also ran to make sure I am up to date:

git remote add upstream https://github.com/SiCKRAGETV/SickRage.git
git fetch upstream
git checkout master
git reset --hard upstream/master
git pull

This ran with out issue.

Thank you
