### ISSUE TITLE
Does not snatch episode

### ISSUE THREAD

**Issue by Hobbabobba** [SiCKRAGETV/sickrage-issues#1939]
SR Version:	BRANCH: (master) / COMMIT: (ae2c0e8006bf0c8ec3d3379148a951847b2c5f39) 
SR User:	sickrage

I use a Synology Diskstation 415+,  DSM 5.2-5565 Update 2
Python Version:	2.7.10 (default, Jun 3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]

What i did: 
I added a new tv-series, set one of the episodes from "skipped" to "wanted"

What happend:
SR searched for the episode, gets some matches from my usenetindexer but refuses them 
Log-File says "No needed episodes found during backlog search for: [name of the show]"

What i expected:
SR will search for the episode, get the data from the indexer and send the nzb to the usenet-client for downloading

Here are my logfiles: 
https://gist.github.com/Hobbabobba/656fbdd2223d3d0dd770#file-sickrage-log-1
https://gist.github.com/Hobbabobba/656fbdd2223d3d0dd770#file-sickrage-log

**Comment by miigotu** [comment]
Obviously the link given by the indexer doesn't work.

**Comment by Hobbabobba** [comment]
You saved my day :) I did not use NZB Megasearch but tried the indexer itself and it works again!
Thanks!
