### ISSUE TITLE
[APP SUBMITTED]: cannot import name canonical_form

### ISSUE THREAD

**Issue by pct00** [SiCKRAGETV/sickrage-issues#1941]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@ae2c0e8006bf0c8ec3d3379148a951847b2c5f39
Link to Log: https://gist.github.com/46c547888757d3e10562
### ERROR
```
POSTPROCESSER :: Error occurred when downloading subtitles: cannot import name canonical_form
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@miigotu

**Comment by miigotu** [comment]
@fernandog This has nothing to do with the subtitles changes being made. He is on master.

This import doesnt even exist in the new guessit, so OP you might not get this error again if you are on a clean repo, or you can wait until the next merge to master when the new subtitle updates are complete.

**Comment by pct00** [comment]
@miigotu 
i did switch from dev to master and some garbage may have been left behind.
ill make a clean install over the weekend


thanks!
