### ISSUE TITLE
[APP SUBMITTED]: RSSFeeds instance has no attribute 'rssDB'

### ISSUE THREAD

**Issue by scythe000** [SiCKRAGETV/sickrage-issues#1942]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@ae2c0e8006bf0c8ec3d3379148a951847b2c5f39
Link to Log: https://gist.github.com/c9ac2a6b065c96ac33fd
### ERROR
```
FINDPROPERS :: [KickAssTorrents] :: Failed to parsing KickAssTorrents Traceback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\kat.py", line 242, in _doSearch
    entries = self.cache.getRSSFeed(searchURL)['entries']
  File "C:\SickRage\sickbeard\tvcache.py", line 159, in getRSSFeed
    handlers=handlers)
  File "C:\SickRage\sickbeard\rssfeeds.py", line 43, in getFeed
    self.rssDB.close()
AttributeError: RSSFeeds instance has no attribute 'rssDB'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@scythe000 do you always get this error or was a one time thing?

**Comment by scythe000** [comment]
I haven't seen it before, but I thought I would submit it just in case there was some kind of a change on their side (KAT) that needed to be implemented on our side.

Sent from my iPhone

On Jul 1, 2015, at 12:46 PM, Fernando <notifications@github.com<mailto:notifications@github.com>> wrote:


@scythe000<https://github.com/scythe000> do you always get this error or was a one time thing?

**Comment by fernandog** [comment]
no. it's not an issue. it was trying to close something that was already closed.

**Comment by Sarcas666** [comment]
### INFO
Python Version: **2.7.10 (default, Aug 22 2015, 20:33:39) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)]**
Operating System: **Darwin-15.0.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@29c97fb37688d31bfa4b765d309647bbaddb335a
Link to Log: https://gist.github.com/7ad24615996c544f09ea
### ERROR
```
SEARCHQUEUE-RETRY-83610 :: [Usenet-Crawler] :: Error while searching Usenet-Crawler, skipping: RSSFeeds instance has no attribute 'rssDB'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
