### ISSUE TITLE
Yosemite unrar stopped working 

### ISSUE THREAD

**Issue by bardic** [SiCKRAGETV/sickrage-issues#1943]
Hey, 

So details first  

Branch - Master
Commit hash -  ae2c0e8006bf0c8ec3d3379148a951847b2c5f39
Your operating system and python version - OSX 10.10.3 (14D136) - Python 2.7.8
What you did - Updated to Yosemite
What happened - Unrar stopped working
What you expected - Unrar to continue working

Log: https://gist.github.com/bardic/d78ace39b2d8d3430a27

I saw in the FAQ that I should install unrar with homebrew so I did, rebooted machine and still receiving the same error. This was working fine until the other day when I updated the machine to Yosemite. 

If I run the extract command myself "unrar e salem.103.720p-dimension.rar" the file is successfully extracted. 

Thanks.

**Comment by miigotu** [comment]
Path to unrar changed?

**Comment by bardic** [comment]
Not that I'm aware of.  I didn't originally have unrar  installed with brew. I only installed that because it stopped working.  I think it was just using whatever is in the unrar2 folder which is still there

**Comment by bardic** [comment]
Followed this guide (http://robertvenema.nl/journal/archive/howto-command-line-unrar-on-mac-os-x/) and installed unrar to /bin and it worked. I had done this past but I guess the update to Yosemite had removed it.
