### ISSUE TITLE
File is locked for reading/writing

### ISSUE THREAD

**Issue by PepsiBlue14** [SiCKRAGETV/sickrage-issues#1944]
I'm using BTSYNC and when the shows are done, SickRage can't process the file due to it being locked for reading/writing.

SR Version:	BRANCH: (master) / COMMIT: (ae2c0e8006bf0c8ec3d3379148a951847b2c5f39)  running on OMV 2.0
https://gist.github.com/PepsiBlue14/475fb4ff56be2367326b

**Comment by fernandog** [comment]
Other program is using thoss files

**Comment by PepsiBlue14** [comment]
I'm guessing you're saying that Btsync is 'using' those files. It's interesting that couchpotato doesn't seem to have this issue after the files are done downloading. Just providing this information to see if it could help determine what's keeping the files from being moved.

**Comment by fernandog** [comment]
SR will keep trying to PP until no lock
