### ISSUE TITLE
double episode doesnt match and also post processer it doesn't works

### ISSUE THREAD

**Issue by fferraro87** [SiCKRAGETV/sickrage-issues#1947]
BRANCH: (master) / COMMIT: (ae2c0e8006bf0c8ec3d3379148a951847b2c5f39) 
OS : Ubuntu 14.04
Python Version : 2.7.3

hi i've this question/problem everytime that i download a double episode like under.the.dome.s30102.hdtv etc etc the post processer doesnt recognize it, also i've to download this episodes manually because sickrage doesn't find this episode. so in this case how can i do?

GIST : https://gist.github.com/fferraro87/55642cdddb1d7c127cab

**Comment by fernandog** [comment]
s30102? Bad name ins't?

shoulw should be S**0**3E01E02

**Comment by fferraro87** [comment]
ok thanks now it works...but in this case that i've this filename, only solution is manually rename?

**Comment by fernandog** [comment]
Yes
