### ISSUE TITLE
Connection error [Errno bad handshake] [('SSL routines', 'SSL23_GET_SERVER_HELLO', None)] in headURL

### ISSUE THREAD

**Issue by cadgallar** [SiCKRAGETV/sickrage-issues#1948]
still having the same issue on a FreeNAS FreeBSD 9.2 / I am on the latest commit / master branch
I have tried every solution I could get my hands on but nothing seems to work. Tried all of this:
https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors#solutions

**Python**
Python 2.7.9 (default, Jul 2 2015, 01:11:49)
[GCC 4.2.1 20070831 patched [FreeBSD]] on freebsd9
Type "help", "copyright", "credits" or "license" for more information.
import ssl
ssl.OPENSSL_VERSION
'OpenSSL 1.0.2c 12 Jun 2015'

**my pip list:**
backports.ssl-match-hostname (3.4.0.2)
certifi (2015.4.28)
cffi (1.1.2)
Cheetah (2.4.4)
colorama (0.3.3)
cryptography (0.9.1)
enum34 (1.0.4)
html5lib (0.99999)
idna (2.0)
ipaddress (1.0.7)
Markdown (2.6.2)
ndg-httpsclient (0.4.0)
pip (7.1.0)
pyasn1 (0.1.8)
pycparser (2.14)
pyOpenSSL (0.13.1)
requests (2.6.0)
setuptools (18.0.1)
six (1.9.0)
urllib3 (1.10.4)
wheel (0.24.0)

I still get the following for NZBGeek:
**Connection error [Errno bad handshake] [('SSL routines', 'SSL23_GET_SERVER_HELLO', None)] in headURL https://api.nzbgeek.info/api**

Curl & WGET to the above API url work,both using OpenSSL 1.0.2 work from that box, just not SR.

**Comment by neoatomic** [comment]
@cadgallar As you are unable to setup ssl correctly, why not use http for nzbgeek.?

**Comment by cadgallar** [comment]
@neoatomic it auto redirects to the https connection, unless I am missing something here?

**Comment by neoatomic** [comment]
@cadgallar Check the url that you are using in search setting for nzbgeek. If it is http that it is indeed redirects to https.

**Comment by cadgallar** [comment]
@neoatomic  just checked it and it does still give me the same grief when I set it to http

**Comment by neoatomic** [comment]
@cadgallar If you use http and it still doesn't work that there is something else going-on.
Make sure the url is correct. ( if i recall correct nzbgeek needs an extension like /api or something to it.)

The thing is that nzbgeek is a invite/closed provider. So we have no possibility to even test anything...
Best to check there forums to make sure you have the correct url.

**Comment by cadgallar** [comment]
I get the issue with any SSL connection. I think my sickrage is using an older python version, but I can't seem to find out how to upgrade the python version used by SR

**Comment by neoatomic** [comment]
Sickrage uses the Python version that you have installed on your device. maybe nzbgeek changed something.? If you use http than you are not using SSL. And the connection should work.

**Comment by cadgallar** [comment]
@neoatomic  thanks, however it's not nzbgeek it's openssl & python on the freenas, the solutions in the link above fix the bug on qnap nas that I own, however i can't seem to fix the same bug on the freenas

**Comment by neoatomic** [comment]
@cadgallar sadly i cant help you out there. I'm not familiar with Freenas...

**Comment by cadgallar** [comment]
all good, thanks for trying ;)

**Comment by neoatomic** [comment]
Try the search function here on github. With a little luck the question was ask before.

**Comment by cadgallar** [comment]
one thing I just noticed: 

# python2.7 ssl_sni_tests.py
Traceback (most recent call last):
  File "ssl_sni_tests.py", line 26, in <module>
    from sickbeard.providers.torrentday import provider as torrentday
  File "/usr/pbi/sickbeard-amd64/share/sickbeard/Sick-Beard/sickbeard/__init__.py", line 37, in <module>
    from sickbeard import providers, metadata, config, webserveInit
  File "/usr/pbi/sickbeard-amd64/share/sickbeard/Sick-Beard/sickbeard/providers/__init__.py", line 51, in <module>
    import generic
  File "/usr/pbi/sickbeard-amd64/share/sickbeard/Sick-Beard/sickbeard/providers/generic.py", line 31, in <module>
    from sickbeard import helpers, classes, logger, db
  File "/usr/pbi/sickbeard-amd64/share/sickbeard/Sick-Beard/sickbeard/helpers.py", line 54, in <module>
    from sickbeard import db
  File "/usr/pbi/sickbeard-amd64/share/sickbeard/Sick-Beard/sickbeard/db.py", line 23, in <module>
    import sqlite3
  File "/usr/local/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/usr/local/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3


Could this be causing the issue?

**Comment by cadgallar** [comment]
I can confirm it was to do with python, have reinstalled python, py27-sqlite3 and it all works again..

**Comment by neoatomic** [comment]
Glad to hear that solved it for you. :)
