### ISSUE TITLE
Episodes snatching but not downloading

### ISSUE THREAD

**Issue by sissipher** [SiCKRAGETV/sickrage-issues#1949]
I followed the guidelines. However no logs are happening when I entered 1 for debug. I rebooted the computer as well. I am a software tester so please work with me. I don't have any error logs and that is why I am confused.

Branch = (master)
Commit hash = /Commit: (ae2c0e8006bf0c8ec3d3379148a951847b2c5f39)
Your operating system and python version = OS Widows 2012 Server/Python 2.7.8
What you did = In Sickrage I clicked on Shows and then a show. I went in and selected a show I did not have.

What happened = It snatched the show. It stayed snatched for over 24hrs and never downloaded.
What you expected = I expected the show to start downloading in qbittorrent v.3.1.9.2 as all other shows a month ago and previous did.

Please let me know if you need any more information.

I also ran to make sure I am up to date:

git remote add upstream https://github.com/SiCKRAGETV/SickRage.git
git fetch upstream
git checkout master
git reset --hard upstream/master
git pull

This ran with out issue.

Thank you

**Comment by neoatomic** [comment]
@sissipher We still need logs to see what SickRage is trying to do. Otherwise we are just speculating... 
However from what i gather you haven't setup SR with qbittorrent correctly. 
For testing you can use the black-hole method to narrow down where the problem lies. 

Also here is a quality guide how to install SR on Windows. make sure you follow the installation instructions exactly. : 
http://www.htpcguides.com/install-sickrage-windows-usenet-torrent-tv/
And here is one for configuration : 
http://www.htpcguides.com/configure-sickrage-usenet-torrent-tv/

**Comment by fernandog** [comment]
@sissipher sorry about asking but did you changed the log level when opening the log page?

**Comment by thejrose1984** [comment]
Having the same problem:
Branch = (master)
Commit hash = /Commit: (ae2c0e8006bf0c8ec3d3379148a951847b2c5f39)
Operating System: FreeBSD / FreeNAS 9.3
Python Version: Python 2.7.9

Have SickRage setup for backlog and set select shows for wanted as default status. Also tried manually searching episodes. Episodes would be snatched and sent to Sabnzbd, but the downloader would simply show that it's "trying to fetch" repeatedly. Only happens with SickRage and no other Python based web app on my FreeNAS.
Logs - http://pastebin.com/JDhxZWYP
![2015-07-04 17_31_03-htpc manager](https://cloud.githubusercontent.com/assets/7573083/8509549/08762982-2277-11e5-823f-c492cd6c2f43.png)

**Comment by neoatomic** [comment]
@thejrose1984 Try the blackhole method and see if it saves the nzb. 
Also for 6box.me use http instead of https in the URL.

**Comment by thejrose1984** [comment]
I can understand testing using "blackhole" over specifying sabnzbd, but what change 6box from https to http if it works in other applications?

**Comment by thejrose1984** [comment]
Tested using Blackhole and works fine. Issue appears to be when I send NZB files directly to Sabnzbd via SickRage. Please note the issue is SPECIFIC to SickRage as no other web application I run has this issue.

**Comment by thejrose1984** [comment]
Replacing HTTPS with HTTP on my indexers did nothing. Checked the logs and showed that shows were being searched but nothing snatched. Please fix,

**Comment by sissipher** [comment]
I re-setup qBittorrent and now I am receiving an error:

2015-07-06 20:17:50 searchqueue-manual-205281 : : qbittorrent: Unable to send Torrent: Return code undefined.

**Comment by sissipher** [comment]
You can close this out.  I uninstalled qbittorrent and went with transmission.  Everything is working again.  Thank you. 

I still find it a bit odd that I never did receive any errors even with debug set to 1.

**Comment by thejrose1984** [comment]
Why is this closed? I'm still showing issues connecting to Sabnzbd

**Comment by fernandog** [comment]
your issue it's not related to this one. open a new one and follow guidelines
