### ISSUE TITLE
Episode found, but not snatched

### ISSUE THREAD

**Issue by vinyli** [SiCKRAGETV/sickrage-issues#1956]
Branch: Master
Commit hash: (aa9c1bf1ca2bf3df9cd33fe4e798c8247dfe1881) 
Your operating system and python version: QTS 4.1.4 Python 2.7

My Sickrage is'n't snatching any episodes anymore.
In the log i posted are 2 search results which match my search critera:
 
SUITS.(2015).S05E01.H.264.(WEB-DL).DD5.1.1080p.NLSubs.-Q.o.Q-
and
Suits.S05E01.Denial.1080p.WEB-DL.DD5.1.H264 is 1080p

Sickrage is ignoring the second one based on 'Required Words=Q.o.Q.' which is good.
But the other one, with Q.o.Q. in it should be snatched, but is says 'no result picked'.
This is the problem with all my shows.
I don't understand why it isn't. I have already tried to e,pty the required words, but it doesn't snatch anything either.

Maybe it has something to do with the 'Episode has no release name' line?
I can't figure out what the problem. Can anyone help? I never had any problems with this.

My log:
https://gist.github.com/vinyli/48721b56e45c3f165691

**Comment by Lucienvg** [comment]
I have the same issue! Only with spotweb on nzbfinder.ws/spotweb/ and on my own server.
Nzbfinder.ws/ is working fine! Only you will not find the QoQ sposts there.

**Comment by fernandog** [comment]
@vinyli try adding:
 Q.o.Q-
-Q.o.Q-

**Comment by Lucienvg** [comment]
Same as you not snatching!

My log:
https://gist.github.com/Lucienvg/77b96940d6ca9e173dc1

**Comment by fernandog** [comment]
try adding ONLY:
 Q.o.Q

remove the others

**Comment by Lucienvg** [comment]
Same result!

Full debug log:
https://gist.github.com/Lucienvg/f0a75daf915809773af7

**Comment by fernandog** [comment]
Try adding the show name with year to excene exceptions

**Comment by Lucienvg** [comment]
It is already in there.
Scene Name:	Hannibal | HANNiBAL (2015)

2015-07-02 18:48:33 INFO     SEARCHQUEUE-MANUAL-259063 :: Quality of HANNiBAL.(2015).S03E01.H.264.(WEB-DL).DD5.1.1080p.NLSubs.-Q.o.Q- is 1080p WEB-DL
2015-07-02 18:48:33 INFO     SEARCHQUEUE-MANUAL-259063 :: Quality of HANNiBAL.(2015).S03E01.H.264.(WEB-DL).DD5.1.1080p.NLSubs.-Q.o.Q- is 1080p WEB-DL
2015-07-02 18:48:33 DEBUG    SEARCHQUEUE-MANUAL-259063 :: Picking the best result out of [u'HANNiBAL.(2015).S03E01.H.264.(WEB-DL).DD5.1.1080p.NLSubs.-Q.o.Q-', u'HANNiBAL.(2015).S03E01.H.264.(WEB-DL).DD5.1.1080p.NLSubs.-Q.o.Q-', u'Hannibal.S03E01.1080P.Hdtv.X264.Dimension', u'Hannibal.S03E01.1080P.Hdtv.X264.Dimension']
2015

**Comment by fernandog** [comment]
Empty required words and add NLSubs

**Comment by Lucienvg** [comment]
Same result no snatching!
Also when required words are empty it will not snatch any episode from spotweb on my own server or spotweb from nzbfinder.ws. It will snatch from nzbfinder.ws whithout the spotweb interface.

Haven't tried any other Newznab providers...

**Comment by fernandog** [comment]
probably SR can't fully recognize the naming pattern from this provider

**Comment by Lucienvg** [comment]
Well it was working before some updates.

**Comment by fernandog** [comment]
we haven't changed anything in regex, providers or required words.
https://github.com/SiCKRAGETV/SickRage/compare/v4.0.19...v4.0.20

**Comment by Lucienvg** [comment]
I am on a synology. will revert back to a fresh install. If that does not work, it must be a problem with spotweb! Last week there was also an update for spotweb.

**Comment by Hobbabobba** [comment]
I am on synology, too. Same problem. Strange: it just happens with nzbmegasearch, if i enter the indexer manually, everything works fine. if i use nzbmegasearch (which i did for month without problem and without any update for megasearch): no snatch.
https://gist.github.com/Hobbabobba/656fbdd2223d3d0dd770#file-sickrage-log
https://gist.github.com/Hobbabobba/656fbdd2223d3d0dd770#file-sickrage-log-1

I tried a fresh install, still the same problem.

**Comment by vinyli** [comment]
Thanks for all your reactions and help! But as Lucienvg says, it is not in the required words (even when it's empty it doesn't snatch anything) or in the scene name (i already added that). My search providers are all Spotweb. And as Lucienvg also says, it has always worked before. After some updates it was broken.

**Comment by Lucienvg** [comment]
Did a fresh install and the problem still persists. I also tested with sickbeard and sickbeard snatches without any problem from spotweb!

**Comment by miigotu** [comment]
This is because the url for the result is not valid. We now test the url to the download of the .nzb/.torrent before we select a result from the list of available results, in order to make sure the result is going to be able to be downloaded if we select it.

Maybe we need to add a log line when a result is skipped because the urls are not valid????

**Comment by Lucienvg** [comment]
When I submit this line in the browser:Search url: http://10.0.0.16/spotweb/api?apikey=**********&season=3&maxage=29&cat=5030%2C5040&q=HANNiBAL.2015&limit=100&attrs=rageid&offset=0&rid=30909&ep=1&t=tvsearch With the correct api key it will download the nzb! So url seems to be correct.

**Comment by miigotu** [comment]
Thats not a url to download an nzb.

**Comment by miigotu** [comment]
Anyways this is probably fixed in develop although I would not recommend switching to develop right now as there are major changes happenning there with subtitles and some things are broken.

**Comment by Lucienvg** [comment]
Thanks Miigotu for the answers.
Waiting for the major update, keep up the good work!

**Comment by vinyli** [comment]
Ok, thanks! Any idea when this update comes @miigotu? Becausnow i have to search for new episodes manually, or does someone have a temporarily solution? :-)

**Comment by miigotu** [comment]
This might make it work for you temporary:

sickbeard/helpers.py around line 1321 change
`resp = session.head(url, timeout=timeout)`
to
`resp = session.head(url, timeout=timeout, allow_redirects=True)`

and around line 1386:
`resp = session.get(url, timeout=timeout)`
to:
`resp = session.get(url, timeout=timeout, allow_redirects=True)`

**Comment by miigotu** [comment]
Note that these urls never worked before. The changes I made just let you see the log line saying it was checking them now.  

I moved the get/head request/urlcheck to later in the processing so that we weren't sending requests to providers for items we were going to rule out anyway for other reasons like wrong quality, ignore/required words, invalid release name, etc/

We just check the url last now, instead of before all of those other checks (so you see the log lines the check jumped ahead of)

**Comment by Lucienvg** [comment]
Changed your proposed lines. All episodes get snatched from spotweb!

**Comment by miigotu** [comment]
@Lucienvg great!

**Comment by vinyli** [comment]
Ok, i will change this too (if i can find some tim this weekend) and keep you posted if i do. Thanks @miigotu and @Lucienvg!

**Comment by miigotu** [comment]
Fixed in develop, but please don't switch to develop now because there is broken stuff there! Wait until next merge to master, or use the code changes i posted above.

**Comment by vinyli** [comment]
Thanx for all your work @miigotu!!

**Comment by vinyli** [comment]
I changed the lines as you suggested @miigotu, and it snatches again! Thanks again :-)!!

**Comment by vinyli** [comment]
@miigotu, i've updated to the latest version (commit ba8406163ad4ed0b6578cd6e76fdde3e69c28cf8)  and now it says 'URL check failed. Bad result from provider' and doesn't snatch the episode (or is this fixed in a later version?).

2015-07-10 08:20:28 INFO     SEARCHQUEUE-MANUAL-247808 :: Ignoring Suits.S05E02.Compensation.1080p.WEB-DL.DD5.1.H.264-S based on required words filter: QOQ,Qustom,Q.o.Q
2015-07-10 08:20:28 INFO     SEARCHQUEUE-MANUAL-247808 :: Quality of Suits.S05E02.Compensation.1080p.WEB-DL.DD5.1.H.264-S is 1080p WEB-DL
2015-07-10 08:20:28 INFO     SEARCHQUEUE-MANUAL-247808 :: Skipping SUITS.(2015).S05E02.H.264.(WEB-DL).DD5.1.1080p.NLSubs.-Q.o.Q-, URL check failed. Bad result from provider.

**Comment by miigotu** [comment]
It means the hash the provider gave is not available on any of the torrent cache sites (if it is a magnet) or it is a dead link.

**Comment by vinyli** [comment]
@miigotu: But the link (it's on Spotweb, NZB) is (still) available. This has always worked before, so i don't understand why is doesn't anymore. Before the update i changed what you said in the helper.py and it worked again. Now i've updated and it doesn't anymore.

@Lucienvg: Is it working for you after the update?

**Comment by miigotu** [comment]
@vinyli You are just seeing a NEW logline, to show when a item is skipped. give me the link. Is the spotweb indexer you are using public?

**Comment by miigotu** [comment]
BTW, the allow_redirects is still in the code, so that is not an issue here.

It is entirely possible that the search returned an item with title `SUITS.(2015).S05E02.H.264.(WEB-DL).DD5.1.1080p.NLSubs.-Q.o.Q-,` that has an invalid download link, but that there is a "re-added" version with the same title `SUITS.(2015).S05E02.H.264.(WEB-DL).DD5.1.1080p.NLSubs.-Q.o.Q-,` and a working link. Would you rather I not check the link before accepting it and snatching and then the NZB never gets downloaded anyways?

Flow is like this:
Search-> parse results for wanted quality,req/ignored words, is it in our show list, etc-> does the url given by search working? -yes? snatch -no? keep looking

We don't want to be accepting dead links as snatches. You are just seeing a dead link now.

**Comment by miigotu** [comment]
Unless ofc this is happening for EVERY item, but I doubt that.

**Comment by remybien** [comment]
I have the same issue with the provider torrent BitSoup, this issue is happening for every download. As a result, I have to download new releases manually now

The downloadlink for bitsoup is as follows: https://bitsoup.me/download.php/679408/Under.the.Dome.S03E04.1080p.HDTV.X264-DIMENSION.torrent?passkey=<passkey here>

I presume SickRage now checks for the .torrent extention on the link, which won't work in this case. The log displays the following message: Skipping Under.the.Dome.S03E04.1080p.HDTV.X264-DIMENSION, URL check failed. Bad result from provider.

**Comment by miigotu** [comment]
No, it doesnt check for .torrent. It literally sends an http head request to the provider and asks for headers. 404 = file does not exist. Is the `passkey=passkey_here` part missing from the log line?

**Comment by remybien** [comment]
I've sent you an e-mail with a log file excerpt. I'd rather not share it here because of the closed policy of the torrent provider

**Comment by vinyli** [comment]
@miigotu: yes, it's public. You only have to make a free account. This is the spot:

http://nzbstars.com/?sortdir=DESC&sortby=stamp&search%5Bvalue%5D%5B%5D=Title%3A%3D%3ADEF%3Asuits#/?page=getspot&messageid=v6LXkJ4fSAkbTKaVQHnmZ%40spot.net

And when i click on the button 'NZB to SabNZBd' it sends it to my SabNZB, so it still works.

When i paste my api key in the next link (from my Sickrage log) it downloads the nzb:

http://nzbstars.com/api?t=g&id=v6LXkJ4fSAkbTKaVQHnmZ@spot.net&apikey=**********

**Comment by vinyli** [comment]
@miigotu: i've sent you a e-mail withe the entire link, including my api.

**Comment by miigotu** [comment]
Try stopping SR, and deleting cache/sessions
@remybien from python command line, it is 301 redirect. I set session.allow_redirects=True and it is 200 (status ok)
Let me try with SickRage useragent.

**Comment by miigotu** [comment]
Found the problem...

**Comment by vinyli** [comment]
@miigotu: Great work! It snatches again. Thanks for your time and effort!

**Comment by remybien** [comment]
After updating sickrage wont restart, after some debugging this is the error it throws: (i'm running sickrage on a synology nas)

Traceback (most recent call last):
  File "/usr/local/sickbeard-custom/var/SickBeard/SickBeard.py", line 90, in <module>
    import sickbeard
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/__init__.py", line 37, in <module>
    from sickbeard import providers, metadata, config, webserveInit
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/__init__.py", line 54, in <module>
    import generic
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/generic.py", line 32, in <module>
    from sickbeard import helpers, classes, logger, db
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 60, in <module>
    from sickbeard.subtitles import isValidLanguage
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/subtitles.py", line 25, in <module>
    from sickbeard import helpers
ImportError: cannot import name helpers

**Comment by miigotu** [comment]
Already fixed, some weird import error

**Comment by remybien** [comment]
Thanks, I manually applied your ''Loopy import'' commit changes, started sickrage, enabled 'git reset' and updated to the latest commit. It now works and snatches new releases, thanks a lot for your help!
