### ISSUE TITLE
SR making multiple downloads for single episode on oznzb

### ISSUE THREAD

**Issue by bennyboi04** [SiCKRAGETV/sickrage-issues#1957]
SR Version:	BRANCH: (master) / COMMIT: (aa9c1bf1ca2bf3df9cd33fe4e798c8247dfe1881) 

When looking at 'rate my downloads' on oznzb each downloaded episode is showing as at least 3 api downloads but sabnzbd confirms only one download has actually been attempted, this kills my api dl limit.

Spoken to oznzb and they said they believed it was an issue with sr?

**Comment by miigotu** [comment]
It is not an issue with SR. Tell them that we use a "head" request to verify a file exists on the server before we actually get it. Ofc this looks like 2 requests, but it is in fact only to save them bandwidth and resources, as a head request tells the server to not send any content body.

Just googling now I found something that might explain it better:
http://www.pragmaticapi.com/blog/2013/02/14/restful-patterns-for-the-head-verb

Ask them to not count head requests in their api hits, we only do a head request for verifying download links before accepting them as a valid result, searches and list api calls are just normal get requests.
