### ISSUE TITLE
[APP SUBMITTED]: 'utf8' codec can't decode byte 0x8b in position 24: invalid start byte

### ISSUE THREAD

**Issue by fifou3101** [SiCKRAGETV/sickrage-issues#1958]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@aa9c1bf1ca2bf3df9cd33fe4e798c8247dfe1881
Link to Log: https://gist.github.com/8eee2c11db3653fc440c
### ERROR
```
SEARCHQUEUE-BACKLOG-274897 :: Deluge: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Disable proxy and it will probably work.
