### ISSUE TITLE
[APP SUBMITTED]: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/295619/en.xml

### ISSUE THREAD

**Issue by rcocchiararo** [SiCKRAGETV/sickrage-issues#1959]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@aa9c1bf1ca2bf3df9cd33fe4e798c8247dfe1881
Link to Log: https://gist.github.com/2c6de9c11ea525fc9ff4
### ERROR
```
SHOWQUEUE-ADD :: Unable to find show ID:295619 on Indexer: theTVDB
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rcocchiararo** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@aa9c1bf1ca2bf3df9cd33fe4e798c8247dfe1881
Link to Log: https://gist.github.com/dab9a66366ac432cd7b6
### ERROR
```
SHOWQUEUE-ADD :: Unable to find show ID:295619 on Indexer: theTVDB
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Thw show do not exist anymore in the indexer

**Comment by rcocchiararo** [comment]
What should i do then? i do not know what show it is complaining about.

El jue., 2 de jul. de 2015 a la(s) 7:28 p. m., Fernando <
notifications@github.com> escribió:

> Thw show do not exist anymore in the indexer
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/1959#issuecomment-118184681>
> .
>
-- 
--
Roberto Cocchiararo

**Comment by miigotu** [comment]
`2015-07-02 17:45:15 INFO     TRAKTCHECKER :: Adding show 295619`

Go to trakt and find whatever show is not in your SickRage library, which is on your trakt watchlist and remove it from the watchlist, or ignore it.

**Comment by miigotu** [comment]
@gborri

Maybe remove show from watchlist when this happens?
`2015-07-02 17:45:15 INFO TRAKTCHECKER :: Adding show 295619`
and later:
`SHOWQUEUE-ADD :: Unable to find show ID:295619 on Indexer: theTVDB`

Where the second log line is called, a call to trakt to remove from watchlist should fix this.

**Comment by fernandog** [comment]
@miigotu @gborri
this is a trakt issue that we need to fix.
when user addes a new show to trakt watchlist and thetvdb deletes that show and create a new one, this show remains in trakt as if it's a real show.

So I would do like this:

"SHOWQUEUE-ADD :: Unable to find show ID:295619 on Indexer: theTVDB. Removing this show from TRAKT watchlist"

**Comment by gborri** [comment]
@miigotu @fernandog sorry but I haven't understood thet point. The problem is related to the fact that thetvdb has changed id and trakt haven't? If so we need to open a bug on trakt. Removing from watchlist is not a solution to the problem, doesn't it?

**Comment by fernandog** [comment]
@gborri already contact trakt staff. BUT IMHO they can't remove a show from user watchlist without previous warning. So I don't know how they will handle that.

We can handle in our code. I vote for changing as @miigotu said

**Comment by miigotu** [comment]
`The problem is related to the fact that thetvdb has changed id and trakt haven't?` No, we aren't even sure if the ID ever existed on tvdb at all, or if trakt has double instances of the same show or what.

This will help in two ways:
`SHOWQUEUE-ADD :: Unable to find show ID:295619 on Indexer: theTVDB.`  <- warning not error
`295619: Removing theShowNameTraktGave from TRAKT show watchlist because the show id 295619 is invalid`  <- ERROR? (For now to help debug)

1. It will remove the offending show and prevent the error again
2. It will give us some show names to check and test on our own.

**Comment by fernandog** [comment]
I second that

**Comment by fernandog** [comment]
@gborri can you do that please?

**Comment by gborri** [comment]
@fernandog @miigotu personally i don't like the option to remove the show in watch list from user prospective. In fact if someone has added it is because he need it and removing was not likeable.
Thinking about the problem i have remembered that could happen that some show on thetvdb could disappear because of de-dup process. i like more the first option because the final user need to investigate the problem not avoid.

**Comment by gborri** [comment]
@miigotu what do you think?

**Comment by rcocchiararo** [comment]
Deffinitly knowing what show we need to look at, and leaving the actual
actions to us, seems the best way.

I still don't know what show it is, i have many :P

But i believe it is "saint seiya: sould of gold". Right now, there are like
5 or 6 matches for that show on Trakt...

El vie., 3 de jul. de 2015 a la(s) 11:30 a. m., gborri <
notifications@github.com> escribió:

> @miigotu <https://github.com/miigotu> what do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/1959#issuecomment-118363985>
> .
>
-- 
--
Roberto Cocchiararo

**Comment by fernandog** [comment]
@rcocchiararo so do you think SR should remove it for you or keep showing that message as a WARNING?

**Comment by rcocchiararo** [comment]
I believe a warning, with more info (just the id is not good for me, maybe
the folder name if it is not possible to tell me the actual show?)

El vie., 3 de jul. de 2015 a la(s) 11:43 a. m., Fernando <
notifications@github.com> escribió:

> @rcocchiararo <https://github.com/rcocchiararo> so do you think SR should
> remove it for you or keep showing that message as a WARNING?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/1959#issuecomment-118366101>
> .
>
-- 
--
Roberto Cocchiararo

**Comment by fernandog** [comment]
folder name not possible because the show isn't in SR yet. I think SR have only the ID. and if the ID is not valid, we can't get the show name from indexer. don't know if we can get the show name from TRAKT. @gborri do you know if is possible?

**Comment by rcocchiararo** [comment]
Today i noticed i had many of that show in Trackt, did some deleting and
adding, and now SR shows:

(loading)Loading... (F:\Videos\Series\Saint Seiya Soul of
Gold)(loading)Loading...
(F:\Videos\Series\Saint Seiya Soul Of Gold)(loading)Loading...
(F:\Videos\Series\Saint Seiya Soul Of Gold)

I think that it will eventually dissapear and show the error i reported.

El vie., 3 de jul. de 2015 a la(s) 11:48 a. m., Fernando <
notifications@github.com> escribió:

> folder name not possible because the show isn't in SR yet. I think SR have
> only the ID. and if the ID is not valid, we can't get the show name from
> indexer. don't know if we can get the show name from TRAKT. @gborri
> <https://github.com/gborri> do you know if is possible?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/1959#issuecomment-118366883>
> .
>
-- 
--
Roberto Cocchiararo

**Comment by miigotu** [comment]
I think it should warn you, tell you it is removing it, with the show name if possible, AND remove it from trakt watch list.

Regardless if you want the show or not, having that instance in trakt is useless because it cannot be added to any application, and no application can update watched status for it anyways. It is useless garbage so just tell the user and fix the problem.

**Comment by miigotu** [comment]
Ridic:
http://trakt.tv/search?utf8=%E2%9C%93&query=Saint+Seiya+Soul+of+Gold

**Comment by rcocchiararo** [comment]
miigotu is right, he bought me :P

But the waring should still appear.

ps: can i use the id SR shows to id it in trakt?

El vie., 3 de jul. de 2015 a la(s) 11:52 a. m., miigotu <
notifications@github.com> escribió:

> I think it should warn you, tell you it is removing it, with the show name
> if possible, AND remove it from trakt watch list.
>
> Regardless if you want the show or not, having that instance in trakt is
> useless because it cannot be added to any application, and no application
> can update watched status for it anyways. It is useless garbage so just
> tell the user and fix the problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/1959#issuecomment-118367654>
> .
>
-- 
--
Roberto Cocchiararo

**Comment by rcocchiararo** [comment]
UPDATE: SR deffinitly knew something about the show, because it was trying
to use a folder with it's name, and has now errored:

2015-07-02 23:52:29 SHOWQUEUE-ADD :: Unable to find show ID:294511 on
Indexer: theTVDB
2015-07-02 23:52:05 SHOWQUEUE-ADD :: Unable to find show ID:294511 on
Indexer: theTVDB
2015-07-02 23:51:41 SHOWQUEUE-ADD :: Unable to find show ID:296146 on
Indexer: theTVDB


El vie., 3 de jul. de 2015 a la(s) 11:54 a. m., miigotu <
notifications@github.com> escribió:

> Ridic:
> http://trakt.tv/search?utf8=%E2%9C%93&query=Saint+Seiya+Soul+of+Gold
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/1959#issuecomment-118368322>
> .
>
-- 
--
Roberto Cocchiararo

**Comment by miigotu** [comment]
No, @gborri needs to put the show name in the logged warning along with the show id.

`2015-07-03 07:53:15 WARNING :: TRAKT :: Removing invalid show from watchlist: "Saint Seiya Soul Of Gold" with tvdbid: 295619`

**Comment by fernandog** [comment]
Reply from TRAKT

we don’t auto remove if TVDB removes it. We also use TMDB data, so the TVDB is association would need to be updated there too.

**Comment by fernandog** [comment]
@rcocchiararo please stop SR
edit SickRage/sickbeard/show_queue.py, delete all contents and paste this one:
https://raw.githubusercontent.com/fernandog/SickRage/show_add_error/sickbeard/show_queue.py
save,
start,
see if is more clear the message/error

OR check here
https://github.com/SiCKRAGETV/SickRage/pull/2049/files

**Comment by rcocchiararo** [comment]
Either by doing the modification by hand, or by replacing all the content,
sickrage refuses to start with the new code.

El sáb., 4 de jul. de 2015 a la(s) 10:54 a. m., Fernando <
notifications@github.com> escribió:

> @rcocchiararo <https://github.com/rcocchiararo> please stop SR
> edit SickRage/sickbeard/show_queue.py, delete all contents and paste this
> one:
>
> https://raw.githubusercontent.com/fernandog/SickRage/show_add_error/sickbeard/show_queue.py
> save,
> start,
> see if is more clear the message/error
>
> OR check here
> https://github.com/SiCKRAGETV/SickRage/pull/2049/files
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/1959#issuecomment-118513898>
> .
>
-- 
--
Roberto Cocchiararo
