### ISSUE TITLE
Episodes Unaired set to Ignored

### ISSUE THREAD

**Issue by siddadav** [SiCKRAGETV/sickrage-issues#1960]
SR Version:	BRANCH: (master) / COMMIT: (aa9c1bf1ca2bf3df9cd33fe4e798c8247dfe1881) 
Python Version:	2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]

sickrage shows show as unaired, even past the air date, causing them not to download. example show is wayward pines, has future episodes set to unaired and when it has pasted the air date it is not downloading them.

There is no error in the logs.

**Comment by siddadav** [comment]
another episode is Hannibal, it will not download unless I click on the search 
![image](https://cloud.githubusercontent.com/assets/13157601/8489217/fdf2fa2e-2110-11e5-9bef-68285e38b062.png)

**Comment by fernandog** [comment]
@siddadav 
did you changed the hour SR updates? default is 3AM
do you keep your SR running 24/7 ? If you didn't change default update hour and you always shutdown your SR at 10PM, episodes will never be updated from Unaired to Wanted
