### ISSUE TITLE
not snatching from custom Newznab Providers

### ISSUE THREAD

**Issue by darkfire04** [SiCKRAGETV/sickrage-issues#1963]
SR Version: BRANCH: (master) / COMMIT: (aa9c1bf1ca2bf3df9cd33fe4e798c8247dfe1881) 
Kernel 2.6.31.8.duov2 on Netgear ReadyNas Duo v2 (Debian Squeeze armel)
Python Version: 2.7.10 (from source)

I've been using sick rage for about a month. I just recently noticed that I've only been able to grab releases using usenet grabber. I currently have nzbgeek and 6box set up as the first 2 search providers with usenet grabber as a fallback.

Checking the logs everything acts as though there was no output when the search was run. There isn't even any dump into the cache.db
LOG dump from the last manual search.
https://gist.github.com/darkfire04/5afc6adb034c2064421b

The problem is that when I take the search_url and run it on my own I actually get results with nzbgeek and 6box.  

quick grab from nzbgeek's api seach:
<newznab:response offset="0" total="2"/>
<item>
<title>Young.Justice.S02E10.1080p.BluRay.x264-DEIMOS</title>
####### REMOVED extra release info ########
</item>
<item>
<title>Young.Justice.S02E10.DVDRip.XviD-DEiMOS</title>
####### REMOVED extra release info ########
</item>

I can dump the full xml output if needed for debugging. Though it feels like there's something wrong with the url that's being generated for the search. Either that or the XML format is very different than what SR is expecting.

I wish I knew python to debug this, but I'm at the mercy of the community on this one.

Thanks guys!

**Comment by neoatomic** [comment]
@darkfire04 Your log shows "FALLBACK SEASON PACK SEARCH INITIATED ...: "
See if you maybe have enabled "Season search fallback" in the search settings for the providers.
Also check if you have set "season packs only" or "episodes only" under the settings.

**Comment by darkfire04** [comment]
I've currently got it set for episodes only. And then full season search as a fall back. 
However, I only changes that a day or two ago. If it'll help, I'll change the setting back to just eponly and create a second log dump.
On Jul 4, 2015 6:30 AM, neoatomic <notifications@github.com> wrote:@darkfire04 Your log shows "FALLBACK SEASON PACK SEARCH INITIATED ...: "
See if you maybe have enabled "Season search fallback" in the search settings for the providers.
Also check if you have set "season packs only" or "episodes only" under the settings.

**Comment by darkfire04** [comment]
Here's the new log dump with season fallback turned off.

https://gist.github.com/darkfire04/110eb4f3b2c6e045a7a1

**Comment by neoatomic** [comment]
@darkfire04 The minimum time between searches is 30 minutes .Your log shows that you search faster than that. That makes the log useless... 
```
 [nzbgeek] :: Last update was too soon, using old cache: today()-2015-07-04 19:54:29<0:30:00 
```
Also need to see the output of daily search or backlog search not manual search.

**Comment by darkfire04** [comment]
Just for the sake of trying... I ran the cache links via curl... what I got was interesting...

~# curl https://api.nzbgeek.info/api?apikey=[redacted]&maxage=4&attrs=rageid&t=tvsearch&cat=5030%2C5040%2C5060%2C5070
[6] 16947
[7] 16948
[8] 16949
[9] 16950
[5]   Done                    curl http://animenzb.com//rss?max=100
curl: (35) error:14077458:SSL routines:SSL23_GET_SERVER_HELLO:reason(1112)

~# curl -1 https://api.nzbgeek.info/api?apikey=[redacted]&maxage=4&attrs=rageid&t=tvsearch&cat=5030%2C5040%2C5060%2C5070
[1] 16951
[2] 16952
[3] 16953
[4] 16954

curl only likes TSL (makes sense with poodle/etc vulnerabilities)... the odd part is there's 0 xml output. If I use my local browser I get a full dump. This might just be something on my end :/

Just for testing sake I ran curl against animenzb

 ~# curl http://animenzb.com//rss?max=100&cat=anime
[1] 16962
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
	<channel>
		<title>All :: Fanzub</title>
		<link>http://www.fanzub.com/</link>
		<description>A Usenet Search Engine for Japanese Media</description>
... you get the point

**Comment by neoatomic** [comment]
@darkfire04 Do you need any more support, or can i close this issue.?
