### ISSUE TITLE
[Feature Request] Add "device name" option to pushover notifier

### ISSUE THREAD

**Issue by renini** [SiCKRAGETV/sickrage-issues#1965]
Hi in my setup i have multiple devices with the same pushover account, the pushover API allowed to differentiate, and only choose one device to notify.

This can be done by supplying the device name, would love to see this in a newer build.

see:
https://pushover.net/api

**Comment by miigotu** [comment]
@renini Done.

**Comment by renini** [comment]
Well done! thanks for the quick patch

**Comment by miigotu** [comment]
@renini did you confirm that it works? I could not test it =P

**Comment by renini** [comment]
Will do that tonigth and report back. Thnx

**Comment by renini** [comment]
@miigotu manage to test it earlier then tonight, works like a charm! thanks again

**Comment by miigotu** [comment]
Cool, glad it works.
