### ISSUE TITLE
[Feature Request] Hide ended shows from showlist

### ISSUE THREAD

**Issue by cvockrodt** [SiCKRAGETV/sickrage-issues#1966]
Branch: Any
Commit hash: 4a47a5cf7eff76f0d99a9c0f3b574027d1f56dd8
Your operating system and python version: Windows 8.1 python 2.7
What you did: Used SickRage
What happened: Normal operation
What you expected: Feature Request -

After using SR for a while, I've acquired a number of shows in my collection. I track my watching in trakt.tv and the ability to hide shows based on criteria such as completed, collected, watched, etc. is very nice. 

I wish there was a similar option on the SR "Shows" tab. The most obvious (to me) criteria for hiding shows in SR would be completed, ended, and 100% watched (this could be pulled from trakt.tv). The completed and ended information is already there in the page represented by the data-progress(0-100) and data-date(5000000100.0 = ended ) attributes in the show div. 

This would serve to de-clutter the shows page when you just want to see the shows that matter to you at the given moment.

**Comment by fernandog** [comment]
just use the filters.  hover the mouse in column "Status" and use the filter typing "Continuing". it auto save when you open page next time.

**Comment by cvockrodt** [comment]
I'm using the poster view... Second of all, if I use a table view (small poster, banner, simple), which I assume is tablesorter, the filter textboxes don't show up so I can't filter on anything.
