### ISSUE TITLE
Sickrage not snatching or downloading valid nzb's

### ISSUE THREAD

**Issue by celshof** [SiCKRAGETV/sickrage-issues#1967]
SR Version:	BRANCH: (master) / COMMIT: (4a47a5cf7eff76f0d99a9c0f3b574027d1f56dd8) 
OS: Ubuntu Server: Linux version 3.13.0-55-generic (buildd@brownie) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #94-Ubuntu SMP Thu Jun 18 00:27:10 UTC 2015
Python: 2.7.6

When searching for wanted episodes Sickrage seems to find correct versions, but it doesn't pick any of the results to start downloading.

Log: https://gist.github.com/celshof/d5864a709a70257c7878

**Comment by neoatomic** [comment]
@celshof Looks to be related to https://github.com/SiCKRAGETV/sickrage-issues/issues/1956
Try if that solution works for you.
