### ISSUE TITLE
Backlog not finding episodes

### ISSUE THREAD

**Issue by boyahr** [SiCKRAGETV/sickrage-issues#1968]
N.B. : I made a clean install a few days ago, as suggested in a previous thread.

Branch : master
Commit hash : 4a47a5cf7eff76f0d99a9c0f3b574027d1f56dd8
Your operating system and python version :
- Synology DSM 5.2
- Python 2.7.10 (default, Jun 3 2015, 17:38:42) [GCC 4.6.4]

What you did :
- First, I tried to download the latest episode of "Durarara!!", which came out yesterday, and starts the season 3.  This was the log afterwards : https://gist.github.com/boyahr/8f4664a3e2fb3f6ad089
- As it did not succeed,  (I restarted Sickrage and) I also sent to backlog a request for the first episode of the second season of "Eureka Seven", this was the log generated : https://gist.github.com/boyahr/6301719f4acf74b063d1

What happened :
As I asked for anime, I made sure to put NyaaTorrents as the first torrent provider.  I don't know why, but it seems Sickrage first looks for season packs (even though I only marked one episode at a time as wanted) and then (but I don't know if it's really working) for episodes.  To make sure it wasn't country-blocking related, I use the Interproxy.net (EU) proposed by Sickrage.

What you expected :
The torrents to be found and sent to Synology DS (which test succeeded).  I expected torrents from those list to be selected : 
- http://www.nyaa.se/?page=search&cats=0_0&filter=0&term=eureka
- http://www.nyaa.se/?page=search&cats=0_0&filter=0&term=durarara
- https://kat.cr/usearch/eureka%20seven/

**Comment by fernandog** [comment]
need to enable DEBUG in SR settings.
send new logs please

**Comment by boyahr** [comment]
Debug was enabled, I restarted Sickrage before the tests.
https://i.imgur.com/xOah8Se.png

**Comment by fernandog** [comment]
no DEBUG label in your logs.  you need to change "Minimum logging level to display:"

**Comment by boyahr** [comment]
Oh, never noticed more options were available, sorry :P

Anyway, here are the logs, I marked the previously wanted ep as "skipped", restarted sickrage, and tried to download them again : 
- Durarara!! Season 3 ep 1 : https://gist.github.com/boyahr/fdac70735d6d2b69f7b2

The thing is, this show has special name for every season, for example, season 2 had "shou" added in the show name, and season 3 should have "ten".  That's why I decided to try with something more generic, like Archer.  I asked for the 1st episode of the fourth season, hoping SR would at least download something from here : https://kat.cr/usearch/archer%20s04e01/

But here were the results : https://gist.github.com/boyahr/a0f4e4114b6ce92145dc

**Comment by fernandog** [comment]
First log
Episode already exists and the found episode has same/lower quality, ignoring found episode

Second
Archer is not an anime, skiping

**Comment by boyahr** [comment]
But that doesn't make sense, I don't have that episode (and I made sure it was marked as skipped before launching backlog), as for the second I don't see why SR would skip Archer because it is not an anime...

**Comment by fernandog** [comment]
when you press manual search you are asked two questions: mark as failed and download same quality. probably you answered 'no' in the second one.

**Comment by boyahr** [comment]
I didn't do a manual search, I just marked the episode as "wanted".  After your comment, though, I did one, where no downloads were found (there weren't any of the two questions you speak of, I just clicked on the magnifying glass)
https://gist.github.com/boyahr/028c748fbce0c5bcceed

**Comment by fernandog** [comment]
bad naming format 
2015-07-06 14:33:07 DEBUG    SEARCHQUEUE-MANUAL-133341 :: Failed to detect release group, invalid result
2015-07-06 14:33:07 DEBUG    SEARCHQUEUE-MANUAL-133341 :: Picking the best result out of [u'Durarara!!.X2.-.13.(1280x720.HEVC.AAC).mkv']

**Comment by boyahr** [comment]
So, what should I do to fix this ?  I'm not the one deciding the naming formats...

**Comment by fernandog** [comment]
Wait a new upload or manually download this one

**Comment by boyahr** [comment]
That's what I would do if I hadn't this issue every time, I showed you with Archer, and I just tried with South park s18e10, no downloads found either.
https://gist.github.com/boyahr/e9d89b52a76f0819aff8

**Comment by fernandog** [comment]
Try disabling all kinds of proxies.

**Comment by boyahr** [comment]
It seems to work better, thanks, I'll test it further this week and come back to you if any problem :)
