### ISSUE TITLE
[APP SUBMITTED]: Thread-2467 :: git rev-parse --verify --quiet "@{upstream}" returned : fatal: No upstream configured for branch 'master'

### ISSUE THREAD

**Issue by oconnellkj** [SiCKRAGETV/sickrage-issues#1969]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@e6c4cfd6546b74d5527361f6f0bdc3adc232bdb0
No Log available with ERRORS: 
### ERROR
```
Thread-2467 :: git rev-parse --verify --quiet "@{upstream}" returned : fatal: No upstream configured for branch 'master'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1144
