### ISSUE TITLE
Connection error hostname 'www.hostname.smth' doesn't match either of 'hostname.smth'

### ISSUE THREAD

**Issue by forerunnert** [SiCKRAGETV/sickrage-issues#1971]
Branch : master
Commit hash : 4892503a7d69200554bb0b2af8dd5137cdc7e6d0
Operating system and python version :

Debian 8.1
Python 2.7.9

What I did :
I upgraded my system from Debian 7 to Debian 8 and updated sickrage to the commit shown above.
I'm pretty sure these searches worked after the upgrades though, they may have broken after a sickrage update.

What happened :
Any search initiated fails with error:
SEARCHQUEUE-BACKLOG-47282 :: Connection error hostname 'www.hdts.ru' doesn't match either of 'hd-torrents.org', 'hd-torrents.me', 'hd-torrents.net', 'hdts-announce.ru', 'hdts.ru' in headURL https://www.hdts.ru/SomeTorrent

What I expected :
I expected working downloads :-) Probably a SSL CERT verification thing?

**Comment by fernandog** [comment]
@miigotu related to the new URL checks?

**Comment by miigotu** [comment]
@fernandog related to enabling ssl cert verification. =P This means it is working.
Can you change the urls in hdtorrents.py and just remove the `www.` from all of them?
Just put it in develop and I'll cherry-pick it to master.
