### ISSUE TITLE
Question / Issue - SickRage On OE v5.95.2

### ISSUE THREAD

**Issue by Vodka2014** [SiCKRAGETV/sickrage-issues#1972]
Hi All

It seems that you have removed " Remove pyOpenSSL from libs." This now now causing issues with SickRage on OpenElec v5.95.2 6.0. Beta 1

See: http://openelec.tv/forum/80-sabnzbd-suite/76914-openelec-6-beta-1-audo-sickrage-not-starting?start=15

Please let me know if this is going to be fixed or if there is a Repo that we can find this and install it.

Thanks

**Comment by fernandog** [comment]
@miigotu help here please?

**Comment by miigotu** [comment]
pyOpenSSL was only in the repo for like 2 days. OE can't support SickRage because you can't install cheetah (no pip or distutils)

**Comment by Vodka2014** [comment]
This was working 100% until v5.95.2. So what do you recommend how can i get this fixed.
