### ISSUE TITLE
[APP SUBMITTED]: CHECKVERSION :: git rev-parse --verify --quiet "@{upstream}" returned : fatal: No upstream configured for branch 'master'

### ISSUE THREAD

**Issue by oconnellkj** [SiCKRAGETV/sickrage-issues#1973]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@e6c4cfd6546b74d5527361f6f0bdc3adc232bdb0
No Log available with ERRORS: 
### ERROR
```
CHECKVERSION :: git rev-parse --verify --quiet "@{upstream}" returned : fatal: No upstream configured for branch 'master'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1144

**Comment by fernandog** [comment]
@miigotu is there something we can do to avoid this? this is the third issue I close

**Comment by miigotu** [comment]
Yep, we can do some checks on their setup, but I'm tired right now lol.
