### ISSUE TITLE
[Feature Request] Quality filters

### ISSUE THREAD

**Issue by boyahr** [SiCKRAGETV/sickrage-issues#1975]
I think a lot of people are confused as how SR handles the quality of the files it should download, for example when asking a 720p, I've seen several occurences where SR wouldn't find a 720p version and consider the download failed, when 1080p or other qualities were available.
I know it may suck to refer to other projects but I have to admire the way Couchpotato handles this.  It has a list of filters, for example, "Best" is the first filter, it has 720p and 1080p in it (it's customizable).  Couchpotato will then select the best torrent from the qualities of this filter.

https://i.imgur.com/fhoRvQb.png
https://i.imgur.com/qLOc0yF.png

I also know you can somehow manage qualities with ignore and required filters, but it doesn't really feel user-friendly.

I'm not asking for exactly the same thing, but an enhancement to make SR even more reliable.  Thanks for your consideration.

**Comment by OmgImAlexis** [comment]
I was going to make a feature request but I think it may fit in with this. Being in a country with limited download speed I really like the way Couchpotato handles downloads with an added size field. I'm fine with a 1080p copy but I really don't want to 2GB - 4GB one, if there was a way to restrict it to the 1GB - 2GB versions that a lot of people put out that'd be great.

**Comment by fernandog** [comment]
@OmgImAlexis just add to required words the release groups that provide that

**Comment by OmgImAlexis** [comment]
None of them provide it as far as I know, it's the compression that certain people upload. I've seen the same copy of a file from RARBG on kickasstorrents, one that's been compressed and one that's "raw" with about 2GB in size difference.

**Comment by fernandog** [comment]
all providers don't give that information. we can't change SR without ALL of them using some convention to it

**Comment by OmgImAlexis** [comment]
Alright just thought I'd mention it incase it was possible.

**Comment by rarbg** [comment]
@OmgImAlexis 
Sorry but if you actually READ what @fernandog you would be able to acomplish what you need.

**Comment by OmgImAlexis** [comment]
``Game of Thrones S05E10 Mothers Mercy 1080p WEB-DL DD5 1 H 264-RARBG [rarbg]``

@rarbg How exactly am I meant to set a required word for the file size to that? I get my files from kickasstorrents where random people have reupped releases from RARBG and most of the time they've recompressed the files. Sometimes I get a ~1GB 1080p file and sometimes I get a ~4GB.

Unless I'm missing something I don't see how I adding anything as a required word to a release group would get me the files I would prefer.

**Comment by fernandog** [comment]
4gb are 1080p HDTV. 
1gb are 1080p WEB-DL

You should use a custom quality in SR

**Comment by OmgImAlexis** [comment]
They are when people follow scene rules and name things correctly I've had loads(10+) of shows snatch SD episodes because they were named incorrectly as 720p or HDTV and a bunch of other issues. This is why I was hoping for a file size setting.  Also depending on the show the 1080p HDTV is at times a LOT lower res and lower file size than the WEB-DL. I mainly noticed the swapped size with Australian shows as the broadcasted show is in 720i and the web version is in 1080p or 720p.

Anyways, if it's not going to be added there's no point in filling this issue with other stuff that's not related.

**Comment by fernandog** [comment]
@OmgImAlexis 
you need a better provider! bad providers have bad naming, bad torrents and low seeds.
I suggest you to enable @rarbg (public) and keep in the top of the list. you won't have fakes or bad naming.

if providers don't tell us that information there's no way to know that!
SR will only know if downloads it, check it using mediainfo (big feature request in todo list - no duo data), mark as failed and download another. the bad side is that you have lot's of downloads until you get the one you want. is it worth??

**Comment by OmgImAlexis** [comment]
@fernandog From what I knew @rarbg was private, I must have been wrong about that. I'll definitely add that as my first provider then. I find a lot of the time SR gets the newest copy of the show so older shows end up with crappy recompressed versions from other users that've taken RARBG and run them through handbrake and reupped them without replacing the provider in the title with their handle. :-1: 

Yeah I get what you're saying, if providers all had the file size in their API it'd really help with this kind of thing but what can you do but wait till they get around to adding it if they even do that....

If I didn't live in Australia with a maximum of 20Mb/s down, 0.7Mb/s up I wouldn't care but speeds here are crap.

**Comment by rarbg** [comment]
@fernandog 
You can use the size in our api to add it as a functionality btw
@OmgImAlexis 
1. Rarbg is not private
2. Rarbg has a naming convention which is strict. There will never be a release returned in an unstrict naming convention on the api
3. There are no fakes.
If you are looking for specific quality you shouldnt use it like that.
You are not looking for quality anyways. Size / Res is not quality. Bitrate is....

About your web-dl example - again you are not looking for quality if you are downloading reencodes.
You better stick to SD HDTV , it will be much better. Most of the groups dont encode with quality in mind , especially the ones encoding web-dl from original web-dl sources.
Dont ever think that a 1080p 1g will produce a better quality than a SD 1g!

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
