### ISSUE TITLE
[APP SUBMITTED]: Thread-64 :: No Show Object found for show with indexerID: 104281

### ISSUE THREAD

**Issue by raver2046** [SiCKRAGETV/sickrage-issues#1976]
### INFO
Python Version: **2.7.3 (default, Apr 12 2012, 13:08:47) [GCC 4.2.3]**
Operating System: **Linux-3.0.8+-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@4a47a5cf7eff76f0d99a9c0f3b574027d1f56dd8
Link to Log: https://gist.github.com/3108dd8dcf1508756dc5
### ERROR
```
Thread-64 :: No Show Object found for show with indexerID: 104281
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Show ID do not exist in indexer anymore.
Remove this show ID from trakt watchlist or change the ID in .nfo if you added from .nfo
