### ISSUE TITLE
[APP SUBMITTED]: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by Jenks001** [SiCKRAGETV/sickrage-issues#1977]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-37-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@4a47a5cf7eff76f0d99a9c0f3b574027d1f56dd8
No Log available with ERRORS: 
### ERROR
```
Thread-28 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/jake/.sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/home/jake/.sickrage/sickbeard/webserve.py", line 2131, in fetch_releasegroups
    groups = anime.get_groups()
  File "/home/jake/.sickrage/lib/adba/aniDBAbstracter.py", line 167, in get_groups
    self.rawData = self.aniDB.groupstatus(aid=self.aid)
  File "/home/jake/.sickrage/lib/adba/__init__.py", line 581, in groupstatus
    return self.handle(GroupstatusCommand(aid, state), callback)
  File "/home/jake/.sickrage/lib/adba/__init__.py", line 115, in handle
    self.link.request(command)
  File "/home/jake/.sickrage/lib/adba/aniDBlink.py", line 218, in request
    self._send(command)
  File "/home/jake/.sickrage/lib/adba/aniDBlink.py", line 199, in _send
    self.sock.sendto(data, self.target)
  File "/usr/lib/python2.7/socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

```
---

This Only happens upon activation of aniDB in anime settings i cant even get it to restart until i turn AniDB off.
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@Jenks001 Can you enable debug=1 in the Sickrage settings and post a full log.? 
And as i dont use Animi its a little harder to troubleshoot for me, so please provide as much info as you can.

We had in the past a similar error reported but that was a one time error and didn't happen again after a reboot.

**Comment by neoatomic** [comment]
And also check your Animi shows if they have any Japanese/special characters in the Scene Exceptions field.

**Comment by Jenks001** [comment]
Fear not, seems to have sorted itself out upon my last pull.

**Comment by whomade** [comment]
### INFO
Python Version: **2.7.3 (default, Apr 12 2012, 20:25:04) [GCC 4.2.1]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.0**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@8ef2afee1e2906342da926ef65a1cba7c392cb39
No Log available with ERRORS: 
### ERROR
```
EVENT-QUEUE :: Exception generated in thread EVENT-QUEUE: error 9 : Bad file descriptor
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
