### ISSUE TITLE
[APP SUBMITTED]: Thread-91 :: git rev-parse --verify --quiet "@{upstream}" returned : fatal: Upstream branch 'refs/heads/master' not stored as a remote-tracking branch

### ISSUE THREAD

**Issue by oconnellkj** [SiCKRAGETV/sickrage-issues#1979]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@4a47a5cf7eff76f0d99a9c0f3b574027d1f56dd8
No Log available with ERRORS: 
### ERROR
```
Thread-91 :: git rev-parse --verify --quiet "@{upstream}" returned : fatal: Upstream branch 'refs/heads/master' not stored as a remote-tracking branch
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@miigotu another one but different.

**Comment by miigotu** [comment]
Its not that big of a deal, i'll get to it.
