### ISSUE TITLE
[Feature Request] Separate Columns on provider selection page

### ISSUE THREAD

**Issue by miigotu** [SiCKRAGETV/sickrage-issues#1982]
config/providers/

Would be nice if we could have the providers in 2 columns, one for torrents and one for nzb. Something like this: (I'm no gfx pro, just to give an idea)

![screenshot from 2015-07-07 01 35 43](https://cloud.githubusercontent.com/assets/390379/8542382/27d2b38e-244a-11e5-9eb5-998be08fa22e.png)

**Comment by neoatomic** [comment]
@miigotu If i recall right SR uses the orders of the providers to prioritize which indexers to pick first. 
When you create two separate columns you cant mix torrent and nzb indexers anymore.
So users cant say:  first pick "nzb indexer x" and as second "torrent indexer x".

Or you have to introduce a option to set the priority of the columns. So column 1 has priority over 2 etc. (primary search indexers and secondary search indexers columns.)

**Comment by miigotu** [comment]
@neoatomic who is to say an item from column 2 can't be dragged to column 1?  User can set their own order but also on a clean install they are separate and easier to find the one you want to add. As they are enabled they should float to the top of the left column, in the order user set or the order enabled otherwise.

We are getting so many providers that during development it gets anoying when I need to enable a provider, because its a long ass list. I can imagine this annoying a new user as well.

**Comment by neoatomic** [comment]
@miigotu Than i have misunderstood your FR. I thought you wanted to completely separate torrents from nzb indexers with two separate columns. :)

**Comment by fernandog** [comment]
We also need to add the private/public label. Thraxis didnt replied in the PR

**Comment by miigotu** [comment]
xD, the column is just way toooo long. And 2 columns makes it a nice opportunity to set the initial sorting that nzb on one side and torrent on the other, just for organization on fresh boot.

**Comment by fernandog** [comment]
what if you do like CP and put all providers in a matrix and only the enabled ones go to sorting list?

**Comment by miigotu** [comment]
IDK if major ui changes are worth it until we rewrite for mako.

**Comment by OmgImAlexis** [comment]
+1 This can be done once I redo that js in my next big PR

**Comment by fernandog** [comment]
@OmgImAlexis there's a lot of things after 'mako': https://github.com/SiCKRAGETV/sickrage-issues/milestones/mako

**Comment by OmgImAlexis** [comment]
@fernandog I want to do all of the js at once though and since I'm pretty sure I'm the main one touching it at the moment I thought I might as well do this when I do my cleanup and update of the current js. All good?

**Comment by fernandog** [comment]
np. just pointing the mako milestone

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
