### ISSUE TITLE
HOST in defaults

### ISSUE THREAD

**Issue by HazCod** [SiCKRAGETV/sickrage-issues#1984]
Is it possible to provide a HOST parameter in the defaults file to adjust the listening address on startup?

e.g. 0.0.0.0 or 127.0.0.1

**Comment by neoatomic** [comment]
You can check the config.ini file.
There should be a setting that you can edit. (Think its called web_host.?)

**Comment by HazCod** [comment]
Ahh, I currently haven't ran Sickrage yet so I don't have a config.ini yet. Will check.

**Comment by fernandog** [comment]
there is an option in UI too

**Comment by HazCod** [comment]
Yes, but I am writing a installation script [here](https://github.com/HazCod/Gunther/blob/master/setupDownloaders.sh#L22).

**Comment by neoatomic** [comment]
btw. Cool project you are working on. :)

**Comment by HazCod** [comment]
Thanks!
