### ISSUE TITLE
Connection Aborted error 10013

### ISSUE THREAD

**Issue by RadeoSuicide** [SiCKRAGETV/sickrage-issues#1985]
BRANCH: (master) / COMMIT: (4a47a5cf7eff76f0d99a9c0f3b574027d1f56dd8) 
Windows 8.1 64-Bit
Python 2.7.9
OpenSSL 1.0.1j
https://gist.github.com/anonymous/a1fd2e532beb59e43e75

I recently did a full SickRage reinstall after something broke. I re-added all of my shows and reconfigured my preferences and after forcing a backlog search it produced this error.

2015-07-07 20:58:10 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Connection error ('Connection aborted.', error(10013, 'An attempt was made to access a socket in a way forbidden by its access permissions')) in headURL http://torcache.net/torrent/7E524FA427852343C1E9E6D90A6368DF67CF5EBC.torrent

It then skips to the next search result and does the same thing. No torrent file is added to my uTorrent.

Help :)

**Comment by fernandog** [comment]
please send you IP to support@rarbg.com to make sure you are not banned/blocked

**Comment by RadeoSuicide** [comment]
i can access the site in my browser like normal though

**Comment by fernandog** [comment]
do you have proxy enabled for rarbg?

**Comment by fernandog** [comment]
also please enable DEBUG in SR settings and send new logs please

**Comment by RadeoSuicide** [comment]
nope

**Comment by RadeoSuicide** [comment]
ok

**Comment by RadeoSuicide** [comment]
https://gist.github.com/RadeoSuicide/32b77f753685e2eb711c

**Comment by fernandog** [comment]
@RadeoSuicide there's no DEBUG label in your log. change min log view please

**Comment by RadeoSuicide** [comment]
sorry forgot to click save changes

**Comment by RadeoSuicide** [comment]
ok try link again

**Comment by fernandog** [comment]
Send the link again please

**Comment by RadeoSuicide** [comment]
https://gist.github.com/RadeoSuicide/32b77f753685e2eb711c

**Comment by fernandog** [comment]
Try to open any URL started with http://torcache.net from your log

**Comment by RadeoSuicide** [comment]
yeah that works, it tries to download the .torrent file

**Comment by fernandog** [comment]
SR uses the same ip as your browser?

**Comment by RadeoSuicide** [comment]
how do i check that? im not running through any proxies if thats what you mean

**Comment by neoatomic** [comment]
Socket 10013 is generally caused by firewall/anti-virus software.

**Comment by RadeoSuicide** [comment]
ok i'll try my phone wifi and check my anti-virus

**Comment by RadeoSuicide** [comment]
i tried a different wifi network and that didnt work, i'll check the firewall

**Comment by RadeoSuicide** [comment]
it was my anti-virus, now i just need to figure out how to fix it. thanks for your help guys :)

**Comment by rarbg** [comment]
btw @fernandog we dont ban ips on the api :P that was before you implemented the api
