### ISSUE TITLE
One series with 2 different names (Original+Hungarian)

### ISSUE THREAD

**Issue by Merwenus** [SiCKRAGETV/sickrage-issues#1986]
I'm downloading series in Hungarian language. The original name is of the show is:
"Anger Management" but the Hun Dubbed version is sometimes titled as:
"Nyugi, Charlie"

That means sickrage doesn't find the hun dubbed files, because it think it is a different show.
SickBeard never had a problem with that, and simple did its job...
It should work with TheTVDB properly, or give us the ability for alternative_name.

Or did I miss an option somewhere?

**Comment by neoatomic** [comment]
Yep, you have to add a scene exception. You can do that by opening the show and click on "edit". There is a field called "scene exception" where you can fill in the alternate title.

**Comment by Merwenus** [comment]
Scene exception means a lot different thing in my mind, I mean Scene exception is like "Do not download anything from scene group Immerse"

And you say "scene exception" means "alternative showname"?

**Comment by neoatomic** [comment]
In SickRage it means a alternative name -> Scene name. :)
