### ISSUE TITLE
This Episode has no name in the TVDB

### ISSUE THREAD

**Issue by konomimaster** [SiCKRAGETV/sickrage-issues#1988]
I'm trying to import a serie from the TVDB. In the log in SR it says:
"This Episode (Name of episode) has no name in the TVDB"

The episodes is named "1", "2", "3" and so forth. 

It's the proper naming of the episodes and does so that a lot of the seasons doesn't show up in SR.

Link to TVDB: http://thetvdb.com/?tab=series&id=104951

SR Version:	BRANCH: (master) / COMMIT: (4a47a5cf7eff76f0d99a9c0f3b574027d1f56dd8) 
Synology Diskstation DSM 5.2-5592
Python Version:	2.7.10

**Comment by neoatomic** [comment]
@konomimaster You are wrong, there is no episode naming. : 
http://thetvdb.com/?tab=season&seriesid=104951&seasonid=612091&lid=7
(The numbers you are referring to are the episode numbers of tvdb.)

And that info is needed to add the show to SickRage. So the only way to solve that is to add the episode names to tvdb...
