### ISSUE TITLE
SickRage says "Downloaded Unknown" is higher quality than "Downloaded 720p WEB-DL"

### ISSUE THREAD

**Issue by Merwenus** [SiCKRAGETV/sickrage-issues#1989]
Found another bug.

Added an existed series to SickRage, all renamed like this (no quality in filename, nor in folder, 192MB size):
Anger Management - s02e65 - Charlie and the Lap Dance of Doom.mkv

Few hours later I downloaded manualy a better quality (720p is in the filename, not just in folder, 724MB size):
Anger Management - s02e65 - Charlie and the Lap Dance of Doom (720P WEBDL H264).mkv

But of course sickrage did nothing with the new file, so I manually force post processed. And got this in the log file

http://i.imgur.com/M67CUCu.png

Full Log file
https://gist.github.com/Merwenus/ccc341e6816a8369197d

The funny part of the log file:

Processing folder /volume1/Downloads/!/Anger.Management.S02E65.720p.WEB-DL.H.264.Hun.Eng-HHD
Found unwanted files: ['Anger Management - s02e65 - Charlie and the Lap Dance of Doom (720P WEBDL H264).nfo']
Processing /volume1/Downloads/!/Anger.Management.S02E65.720p.WEB-DL.H.264.Hun.Eng-HHD/Anger Management - s02e65 - Charlie and the Lap Dance of Doom (720P WEBDL H264).mkv (None)
Retrieving episode object for 2x65
Looking up quality for name Anger.Management.S02E65.720p.WEB-DL.H.264.Hun.Eng-HHD, got 720p WEB-DL
Is ep a priority download: False
File /volume1/Downloads/!Sorozat/HUN/Anger Management/Anger Management - s02e65 - Charlie and the Lap Dance of Doom.mkv is smaller than /volume1/Downloads/!/Anger.Management.S02E65.720p.WEB-DL.H.264.Hun.Eng-HHD/Anger Management - s02e65 - Charlie and the Lap Dance of Doom (720P WEBDL H264).mkv
********************************** Best part **********************************
File exists and new file quality is lower than existing, marking it unsafe to replace
********************************** Best part **********************************
Processing failed for /volume1/Downloads/!/Anger.Management.S02E65.720p.WEB-DL.H.264.Hun.Eng-HHD/Anger Management - s02e65 - Charlie and the Lap Dance of Doom (720P WEBDL H264).mkv:

**Comment by neoatomic** [comment]
@Merwenus Can you add this to your existing issue https://github.com/SiCKRAGETV/sickrage-issues/issues/1978 and close this.? Its better to have all related info/troubleshooting in one place.

**Comment by Merwenus** [comment]
I don't think they relate.
#1978 = Ignore quality in folder name when post processing
#1989 = Unkown is higher quality than 720p

**Comment by neoatomic** [comment]
I see your point. Then feel free to leave it open, they are linked now anyways. :) 
(But it can take some time before the Devs have time to look into this.)

**Comment by abeloin** [comment]
@Merwenus It isn't really a bug:
The line before the "Best part" is stating the new file is smaller than the old one. If the quality would have been something lower than 720p-web-dl, you would have received an error "File exists and new file is smaller, marking it unsafe to replace".

In this case, the quality is unknown *(it is the highest quality possible[https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/common.py#L89])* which mean when testing the quality new_file_quality < old_file_quality will return true and you will receive the error message "File exists and new file quality is lower than existing, marking it unsafe to replace". This is to prevent replacing file which we don't know the quality. (See https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/postProcessor.py#L887 for the logic).

Granted the message could be better.

**Comment by Merwenus** [comment]
Old file = The one already downloaded processed, and it is 192MB with Unknown Quality
New file = The one just downloaded with 720p in name and 700+MB

I see that unknown has class 15 and 720p has only class 5. BUT the quality is 99% all about file size (supposing I'm using a high quality torrent tracker). That means if the Old file is 192MB and the new one is 724MB that means the new file MUST be higher quality and should be overwritten.

Or at least SickBeard works like this I guess, or at least I've never had any problem with it before.

**Comment by abeloin** [comment]
@Merwenus Sorry, after reading your post I see that I misread the log line. If the quality in the DB would have been lower or equal to 720p-web-dl the file would have been replaced.

For the unknown part it doesn't change.

Sickbeard does the same thing when trying to replace an unknown quality in DB, it will output an error message: "Episode already exists in database and processed episode has unknown quality, marking it unsafe to replace" 
Here is the code part in SickBeard: https://github.com/midgetspy/Sick-Beard/blob/development/sickbeard/postProcessor.py#L667

**Comment by Merwenus** [comment]
Btw after I changed quality to "Downloaded SD" manually from "Downloaded Unknown" it processed immediately, so the unknown quality is buggy, or not works as it should.
The problem is I have 100+ Serieses, just added everything to my library, and every hungarian dubbed (renamed) episode is "unknown quality" that means I have to manually check every series and mark them as downloaded as SD or HD depends on size, this is what sickrage should do itself.

**Comment by fernandog** [comment]
This will be fixed with mediainfo

**Comment by abeloin** [comment]
@Merwenus Currently if the information isn't in the filename, SR assign it as Unknown as SB does also.

**Comment by miigotu** [comment]
`Is ep a priority download: False`

Its just a poorly written log line. You did not 'force' post process, you just ran to post process with the wrong checkmarks.

The log means "You already have an episode, and you did not tell me to replace existing episodes"

The gui information about this checkbox is wrong also: (which is the one you need to tick)
- [  ] Mark Dir/Files as priority download:	  (Check it to replace the file even if it exists at higher quality)

@fernandog can you change this `(Check it to replace the file even if it exists at higher quality)` to `(Check here to replace existing episodes while processing)`

This misinformation is from when I changed it to be able to set your archive quality to a lower quality. ie: any can be up to 1080p but you can set SD as your archive, so it can replace higher qualities with lower ones now depending on your quality settings. There are just still some remnants of poor log lines and gui infotips.

**Comment by fernandog** [comment]
what about "Check here to replace existing episodes while processing. It may replace your high quality one with a lower one"

**Comment by miigotu** [comment]
`Replace existing episodes while processing, regardless of quality`  ?

**Comment by miigotu** [comment]
IDC what it says as long as people understand that they need to check it or any episode you have will not be replaced by one in post processing folder

**Comment by miigotu** [comment]
Set the quality, like you said, or check the box for priority (force) in manual pp.
