### ISSUE TITLE
[Request] Rename ONLY Anime but nothing else

### ISSUE THREAD

**Issue by Merwenus** [SiCKRAGETV/sickrage-issues#1990]
I'm downloading English series with Hungarian Sub, Kodi needs original filename (with release group) to automatically download subtitles. So I don't want Sickrage to rename TV Series at all, just leave them as they are.

Otherwise my fiancee loves animes, and Kodi support only this format (like TheTVDB):
Fairy Tail s06e14 - 240.mkv

Every torrent site has this video:
[HorribleSubs] Fairy Tail S2 - 65 [1080p].mkv

Kodi doesn't like this, so I need something to rename from  's2 - 65'  to  's06e14'  (same episode, different numbering). For more information: http://thexem.de/xem/show/1626

I guess SickRage supports Absolute and scene numbering, and I think it can automatically rename to the proper one what Kodi can support, but I really don't want to rename anything else but Animes.

What should I change, to make it possible?

**Comment by fernandog** [comment]
in rename there is a section only for anime

**Comment by Merwenus** [comment]
I know, but the Post Process settings has only this:
* Rename Episodes (Rename episode using the Episode Naming settings?)

Won't it rename TV series too besides anime?

**Comment by fernandog** [comment]
did you try ???

**Comment by Merwenus** [comment]
So you say:
Post-Processing \ Rename Episodes (enabled)
Episode Naming \ Custom Anime (enabled)
http://i.imgur.com/EOZy4ab.png

Will ONLY rename Animes, and nothing else? Just because the Episode Naming is still enabled on the first row, and can't turn it off....
Single-EP Sample:
Show Name - 2x03 - Ep Name.ext 

I will try it out now.

**Comment by fernandog** [comment]
In rename tvshows use the option to keep originl filename

**Comment by Merwenus** [comment]
Which is where/how exactly? Because menu doesn't show "original filename" and custom doesn't have that option too.

**Comment by fernandog** [comment]
if you click the icon this will appear:

```
Meaning	Pattern	Result
Use lower case if you want lower case names (eg. %sn, %e.n, %q_n etc)
Show Name:	%SN	Show Name
 	%S.N	Show.Name
 	%S_N	Show_Name
Season Number:	%S	2
 	%0S	02
XEM Season Number:	%XMS	2
 	%0XMS	02
Episode Number:	%E	3
 	%0E	03
XEM Episode Number:	%XME	3
 	%0XME	03
Episode Name:	%EN	Episode Name
 	%E.N	Episode.Name
 	%E_N	Episode_Name
Quality:	%QN	720p BluRay
 	%Q.N	720p.BluRay
 	%Q_N	720p_BluRay
Release Name:	%RN	Show.Name.S02E03.HDTV.XviD-RLSGROUP
Release Group:	%RG	RLSGROUP
Release Type:	%RT	PROPER
```

just use "Release name" - %RN

**Comment by Merwenus** [comment]
Tested it for you, and it is not Original name.
%RG = %S.N.S%0SE%0E.%E.N-%RG

For example
Original filename what I want to leave as it is (Flexget renamed it)
Anger Management - s02e68 - Charlie Gets Between Sean and Jordan.mkv

Postprocessed filename with Custom / %RG
Anger.Management.S02E68.Charlie.Gets.Between.Sean.and.Jordan-SiCKRAGE.mkv

So it is NOT the original filename.

**Comment by fernandog** [comment]
@neoatomic do you use rename?

**Comment by neoatomic** [comment]
@fernandog No, never used it... 
I prefer the original names, so that i know what releases i have in my folders.

**Comment by miigotu** [comment]
@Merwenus why don't you just let SR handle downloading subtitles for you? What we have in develop handles subtitles even better than kodi itself.

**Comment by miigotu** [comment]
If kodi still relies on filenames for subtitles, you will want to use sickrage to handle it for you instead. we go by hash first, then we fall back to using the original file name (before it was renamed) just in case. This not only gets more results, but it gets much more accurate results and better synced subtitles.

**Comment by Merwenus** [comment]
@miigotu 
Again, closed, I guess its way easier than fix a bug/improve something.

Does SR has ANY quality Hungarian subtitle finder where I can download subtitle? (feliratok.info)
No, there isn't, that's why Kodi handles subtitle downloading, because it supports feliratok.info.

Kodi needs ep_number + rls_group, and thats why I need original name, to get 100% synced subtitles every time. And Flexget renames Hungarian dub shows, thats why I need it to let the way it is.

But as I wrote in the other post, started using SickBeard as main, and Sickrage for animes temporary, but since you guys clearly don't want to improve it I guess it will stay like that forever. But thanks for the helps in other posts. :)

**Comment by miigotu** [comment]
Flexget is so great, you use it to rename all of your other stuff, use it to rename your animes.

Your issues get closed because they are invalid, and you refuse to take anyone's advice. You claim SR is so buggy, then don't use it.

I probably fix 10 things a day and add at least 1 feature a day.  I am not going to spend days of my free time reworking half of SR (for free) to implement a ridiculous feature that nobody will use except you.

If you want it, write it yourself. Noone is stopping you from customizing it for yourself, but we are not here to slave code for you.

**Comment by neoatomic** [comment]
@Merwenus You may want to take a look at nzbtomedia. Gives you advanced options for PP. 

And please be respectful to the folks here, it takes a lot of time/effort to even look into your requests/questions. And all time we cant spent on other bugs/issues...
