### ISSUE TITLE
[APP SUBMITTED]: global name 'BaseSSLError' is not defined

### ISSUE THREAD

**Issue by mbxplex** [SiCKRAGETV/sickrage-issues#1991]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@4a47a5cf7eff76f0d99a9c0f3b574027d1f56dd8
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-212411 :: [Rarbg] :: Error while searching Rarbg, skipping: global name 'BaseSSLError' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@mbxplex Please provide logs.

**Comment by MGaetan89** [comment]
I had a look everywhere `BaseSSLError` is used, and it looks like it is created/imported every time.

**Comment by neoatomic** [comment]
@MGaetan89 Its probably related to https://github.com/SiCKRAGETV/sickrage-issues/issues/1852

@mbxplex Here is a good guide for installing SickRage on a windows machine. Please go trough it and check if you have installed everything correctly. (Especially the pyopenssl part.) :  http://www.htpcguides.com/install-sickrage-windows-usenet-torrent-tv/

**Comment by miigotu** [comment]
Fixed in develop.
