### ISSUE TITLE
Failed download handling is replacing/snatching existing quality episodes

### ISSUE THREAD

**Issue by ctrlbrk42** [SiCKRAGETV/sickrage-issues#1994]
If I have a 720p BluRay already downloaded successfully, but my Archive is 1080p BluRay, and SickBeard snatches the 1080p -- but it fails -- it then proceeds to snatch the 720p BluRay version due to the failed download handling -- even though it already was downloaded and is on the disk.

This happens all the time and is a waste of bandwidth, but I'm also concerned what would happen if the 720p BluRay were to fail, if it would then end up downloading a lower quality episode and replacing the 720p BluRay altogether.

I can provide further details if needed.

**Comment by fernandog** [comment]
know issue. In my case I only set 1080p Blueray. If takes to long, I set 720p and force search

**Comment by ctrlbrk42** [comment]
Not practical for me to do it manually.

209 Shows (114 Active) | 10684 (+344 Snatched)  / 22539 Episodes Downloaded (47.4%)

**Comment by fernandog** [comment]
when this happen don't mark as failed and do a "re-scan" in that show

**Comment by ctrlbrk42** [comment]
It's not practical for me to do manual intervention.

**Comment by ctrlbrk42** [comment]
Unfortunately, I just got confirmation that it does replace a higher quality episode.  So this is really terrible, I just lost a rare episode with a good quality because it was overwritten with a lower quality one.

You mentioned this is a known issue, can you please link me the main bug thread for this issue?

Thank you.

**Comment by miigotu** [comment]
@ctrlbrk42 don't clear/trim history on the history page.
If it doesnt find the previous episode in your history, it will mark it as wanted again rather than the old quality.
```
22:10:07 INFO::SEARCHQUEUE-RETRY-264586 :: Marking episode as bad: [Orange Is the New Black - 3x08 - Fear, and Other Smells]
22:10:07 DEBUG::SEARCHQUEUE-RETRY-264586 :: 264586: Saving episode details to database
22:10:07 DEBUG::SEARCHQUEUE-RETRY-264586 :: STATUS IS 6411
22:10:08 DEBUG::SEARCHQUEUE-RETRY-264586 :: Failed release found for season (3): (Orange_is_the_New_Black_S03E08_WEBRiP_x264_QCF)
22:10:08 INFO::SEARCHQUEUE-RETRY-264586 :: Reverting episode (3, 8): Fear, and Other Smells
22:10:08 WARNING::SEARCHQUEUE-RETRY-264586 :: WARNING: Episode not found in history. Setting it back to WANTED
22:10:08 DEBUG::SEARCHQUEUE-RETRY-264586 :: 264586: Saving episode details to database
22:10:08 DEBUG::SEARCHQUEUE-RETRY-264586 :: STATUS IS 3
```

**Comment by ctrlbrk42** [comment]
I have never trimmed it.  I converted from SB to SR, so new database.  I'm just asking that the failed download look at the existing quality on-disk before grabbing the same quality, or inferior quality.

**Comment by miigotu** [comment]
Without SR being what snatched it to begin with, it has no way of knowing it was there, what quality, what release name etc.

I'm not sure how this can be improved.

**Comment by Knuta86** [comment]
Sonarr handles this just fine without relying on snatched/downloaded history.
I have turned off failed download handling for this exact reason. It replaced 4 of my Blue Bloods 720p WEB's with HDTV because the 1080p WEB failed and then the 720p WEB failed when doing backlog.

**Comment by ctrlbrk42** [comment]
Hi miigotu, the database knows the quality.  Go to "shows", click on one.  It shows the quality right there of stuff on disk in the database, even though it wasn't snatched by SR (but by SB instead).  Makes no difference.

The bug is that it ignores this info, the failed download handling doesn't use the info from the database/disk, it just snatches if an episode fails, regardless if the same quality already exists, and worse --- it will replace the disk version with an inferior quality in the right circumstance.

The solution is simple - before a failed download snatch happens, check to see if the quality about to be snatched is superior to the quality already on the system.

**Comment by miigotu** [comment]
I'll do what I can to try and fix this asap. I don't see why it is doing this.

**Comment by ctrlbrk42** [comment]
Thank you very much.

**Comment by miigotu** [comment]
On the failed history page, are the sizes right?

**Comment by ctrlbrk42** [comment]
The sizes of the failed downloads are correct, yes.  But I want to make sure to not mix the issue --- the issue is:

1. Initial set to 720p WEB-DL and 1080p WEBl-DL. Archive set to 720p BluRay and 1080p Bluray.
2. Season 2 of some show has 720p BluRay for all episodes.  These were on disk when SR was installed, and were scanned and are in the database as 720p BluRay.
3. SR finds and snatches a 1080p BluRay episode, since it is superior quality.
4. That snatch fails to download, and triggers Failed Download handling.
5. The failed download handling then snatches the 720p BluRay, but why, because the 720p BluRay already exists.  Just because SR didn't download it doesn't mean it isn't in the SR database.
6. Worse yet, if the 720p BluRay also fails, then SR snatches the 1080p WEB-DL, and if successful, now deletes the 720p BluRay and replaces it with the 1080p WEB-DL.

**Comment by miigotu** [comment]
`Just because SR didn't download it doesn't mean it isn't in the SR database.`
Actually it does. It isn't in the snatch history for failed db, so it doesnt know the 'old_status' of the failed 'SNATCHED_BEST', so it just sets it back to wanted.

I understand the problem, but am still trying to figure out what to do about it.

**Comment by ctrlbrk42** [comment]
Hi miigotu, clearly you know better than me but I must say I am confused.   Let's say tomorrow you did a clean install of SR.  Your z:\videos directory stays, but you blow away your system partition and reinstall your favorite distro and then git pull and setup SR from scratch.

You then point it to z:\videos with your 100TB video collection and tell it to scan for shows.  It finds the shows and populates everything, including the quality of each episode.

This is the situation I am in.  Now the primary reason I switched to SR from SB was for its failed download handling.  But it's not working too well because of this "bug" or "catch 22" where you are saying failed downloads only work if SR was the one that downloaded it.

I have 22,528 episodes downloaded on my system right now, so am looking for an automated approach that can be trusted.

Thank you.

**Comment by miigotu** [comment]
If you notice, this issue is marked as a high priority bug, and I self assigned it, so trust me, it is at the top of my list.

**Comment by ctrlbrk42** [comment]
I greatly appreciate it.  I'm making a donation to SR right now, it's a great effort.

**Comment by ctrlbrk42** [comment]
Perhaps you can email me a private link to make a donation, as I can't access sickrage.tv due to SSL errors and don't have a forum account --- so the donation button in the app doesn't work or allow me to send you some money.

**Comment by miigotu** [comment]
When I get home. The donate button doesn't work because no one currebtly involved with SR has access to it.

**Comment by miigotu** [comment]
I can't find your email =P

**Comment by miigotu** [comment]
@ctrlbrk42 In a recent commit, the button now points to https://github.com/SiCKRAGETV/SickRage/wiki/Donations

**Comment by ctrlbrk42** [comment]
Thanks, donation made

**Comment by fernandog** [comment]
found it.
It was a long discussion:
https://github.com/SiCKRAGETV/sickrage-issues/issues/770#issuecomment-77584829

**Comment by fernandog** [comment]
forgot this was in the "big feature" list:

- [ ]  Improve manual search and PP: create previous_release_name and previous_status in DB. So if the better quality fails to download or PP, we get previous status and don't remove previous file ( # 770 )

**Comment by miigotu** [comment]
There is already that old_status in failed history. I have been thinking about it, and in snatchEpisode we need to failed.logSnatch as the previous episode I think. I think it is just logging the new snatch and shouldnt be.

**Comment by fernandog** [comment]
But not everybody has failed enabled.

**Comment by miigotu** [comment]
If failed is not enabled, then this issue never happens.

**Comment by fernandog** [comment]
Lol yes

**Comment by ctrlbrk42** [comment]
Sorry to be dense, do you mean this is corrected in the latest master?

**Comment by miigotu** [comment]
@ctrlbrk42 not yet, this is a complicated issue. He is just saying it is on our list for major features from a long time ago and that they had a discussion about it. I think that they came up with a not so good solution to that other problem before and it made this problem worse.

Until I decide in my head the absolute correct way to change it and test it, I won't commit changes for it, because a mistake make make it very much worse. Since it is already putting your library at risk, worse is not acceptable.

**Comment by miigotu** [comment]
Should be fixed in develop
