### ISSUE TITLE
[REQUEST] Add x265/HEVC to Quality Options

### ISSUE THREAD

**Issue by TuRDMaN** [SiCKRAGETV/sickrage-issues#1997]
I would love to see new quality options for x265/HEVC content. Actually, a checkbox for "Download only x265 releases" would probably be better, as adding x265 qualities in for 720p/1080p HDTV/WEB-DL/BluRay would really clutter up the box.
As of right now, I'm just putting x265 in the required words field.

**Comment by gborri** [comment]
related to #656

**Comment by neoatomic** [comment]
As its already requested in https://github.com/SiCKRAGETV/sickrage-issues/issues/656 i'm going to close this. 
(Please add any additional information to that feature request.)

**Comment by TuRDMaN** [comment]
Sorry, I did a search but didn't see that one!

**Comment by neoatomic** [comment]
No problem, it can happen. :)
