### ISSUE TITLE
Broken animation when updating/changing branche

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#20]
<a href="https://github.com/markheloking"><img src="https://avatars.githubusercontent.com/u/3192761?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [markheloking](https://github.com/markheloking)**
_Thursday Nov 27, 2014 at 09:32 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/965 (4 comment(s))_

----

The spin animation next to "Waiting for SickRage to shutdown" is broken/glitchy/pixelated.

BRANCH: (master) / COMMIT: (a67957d4f0aa9786d233aedc928d0d6096daaa80) 
Win7 x64, chrome 39, python 2.7 x86

When updating/changing branche, the spinning animation is very pixelated.
I expect the visuals to be non-corrupt looking.
No relevant logs, but it looks like this:
http://i.imgur.com/8sO8gyr.png

**Comment by abeloin** [comment]
@fernandog In develop branch, commit c62d8f2c799edd7daad5648f45276a3464d83a9e, it look like this:
![Imgur](http://i.imgur.com/drZn21J.png)

**Comment by fernandog** [comment]
light theme seems ok here

![sr-restart-icon](https://cloud.githubusercontent.com/assets/2620870/6190874/52e4ce60-b38c-11e4-8984-33042c82c6f7.png)

**Comment by markheloking** [comment]
This isn't fixed I believe. The actual restart was working from the beginning, but the restart that it did for an update is still unthemed. Can anyone confirm this is still the case? I'll try to confirm it myself if I have the time.

**Comment by fernandog** [comment]
@markheloking next update will be fixed because you didn't updated for a long time. updated code for this was in this update you just did

**Comment by TagForce** [comment]
@markheloking I fixed it, the fernando broke it, then he fixed it again.

**Comment by fernandog** [comment]
=)

**Comment by markheloking** [comment]
Lol, I totally forgot that the fix for the update theme was only after updating. Figures though. Thank you guys!
