### ISSUE TITLE
Default Episode Status not changing

### ISSUE THREAD

**Issue by squareflapjack** [SiCKRAGETV/sickrage-issues#2000]
SR Version:	BRANCH: (master) / COMMIT: (e2318076201cb9a0b4e6fb0bce7aa6504be524a3) 
SR User:	root
SR Locale:	(None, None)
SR Config file:	/opt/sickrage/config.ini
SR Database file:	/opt/sickrage/sickbeard.db
SR Cache Dir:	/opt/sickrage/cache
SR Log Dir:	/opt/sickrage/Logs
SR Arguments:	[]
Python Version:	2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]

Raspberry Pi B+ running Raspbmc latest version

I added several shows with Default Episode Status Skipped so that Sickrage would not try to download all the episodes.  Then I went to Mass Update and Edited the shows to change Default Episode status to Wanted.  The status did not change.  I tried restarting Sickrage and changing it again. Still no change.  I rebooted the Pi and tried again. Still shows Skipped for Default Episode Status.

This is what the log has
2015-07-08 13:03:36 DEBUG    Thread-69 :: 288928: Not saving show to db - record is not dirty
2015-07-08 13:03:36 DEBUG    Thread-69 :: 279201: Not saving show to db - record is not dirty
2015-07-08 13:03:35 DEBUG    Thread-69 :: 295760: Not saving show to db - record is not dirty

but the show page still shows Default Episode Status as Skipped and there is not an option to change the Default Episode Status when I try to edit from the show page itself.

**Comment by miigotu** [comment]
Default episode status is only for when you added the show. It does nothing after that.

**Comment by fernandog** [comment]
@miigotu we should remove it from mass update also. what do you think? users are using this setting wrong

**Comment by squareflapjack** [comment]
I use it all of the time to change the status?  It just stopped recently.  I add new shows as status skipped so that it won't load all the old episodes as wanted and suddenly fill up my downloading.  After the show is added to the database I changed the default status to wanted so that new episodes will be downloaded automatically.

**Comment by miigotu** [comment]
@squareflapjack new episodes will be downloaded regardless. That is why it changed, because new episodes are ALWAYS set to wanted.

**Comment by miigotu** [comment]
@fernandog I think this change needs undone, because it used to work that way. in dailysearcher it should be setting episodes to ep.show.default_episode_status or whatever it is, instead of to wanted.

**Comment by fernandog** [comment]
we need create a separate setting then
If user only what new episodes and not old ones.
A show with 10 seasons would be set as skipped and new ones as wanted.

**Comment by miigotu** [comment]
No need to add a separate setting, the same one can be used. We can make it in addshwo where initial setting = skipped/ignored, but a check box to auto change it to another setting, which shows another select box for after add = wanted/ignored/etc  Then if the box is checked, after adding the show automatically change the default_ep_status to the new setting.

IE: before the show is added it is for how to add the shows, after the show is added it is the setting for all NEW aired shows. we are just missing the part of automatically changing the setting after adding, and that it is not honored after adding right now.

**Comment by miigotu** [comment]
I'll work on it tonight, because someone broke it somewhere down the line anyways.

**Comment by fernandog** [comment]
ok. thanks. with your solution we don't need to change too much python code. only .tmp

**Comment by miigotu** [comment]
I will say though, this change will most likely not be in this merge to master, as I'm planning on merging to master tonight and that change wouldnt be tested enough.
