### ISSUE TITLE
[Info] new feature branch

### ISSUE THREAD

**Issue by gborri** [SiCKRAGETV/sickrage-issues#2001]
@miigotu what do you think about opening a new branch on which merging all new feature? in order to make people test it before merging on develop?

**Comment by miigotu** [comment]
That is the designation of what develop is for. Normal users are not supposed to use develop. Experimental and major changes will be in a feature branch.

If a feature is needed or at all wanted it is at the maintainers' discretion and responsibility to decide if it is a good candidate to be included in the project, and many are not good candidates.

The best way is to get feedback before starting a feature, or find a much requested feature to start working on, and then make sure it is a good candidate with a team member before starting to work on it.

For bugs that are confirmed, there is no question if it should be done, as all bug fixes that are proper fixes are good candidates. These are the easiest contributions normally, and are quickly merged
