### ISSUE TITLE
Episodes snatching but not downloading

### ISSUE THREAD

**Issue by thejrose1984** [SiCKRAGETV/sickrage-issues#2003]
Branch = (master)
Commit hash = /Commit: (ae2c0e8006bf0c8ec3d3379148a951847b2c5f39)
Operating System: FreeBSD / FreeNAS 9.3
Python Version: Python 2.7.9

Have SickRage setup for backlog and set select shows for wanted as default status. Also tried manually searching episodes. Episodes would be snatched and sent to Sabnzbd, but the downloader would simply show that it's "trying to fetch" repeatedly. Only happens with SickRage and no other Python based web app on my FreeNAS.
Logs - http://pastebin.com/JDhxZWYP
More Logs - http://pastebin.com/0tF48WyE
![8924f900-2277-11e5-897f-1b4ead517599](https://cloud.githubusercontent.com/assets/7573083/8571507/4778bc9a-2555-11e5-888e-a44eb2534e98.png)

**Comment by miigotu** [comment]
SR is returning nzb's that are too old atm in master (not honoring maxage). It is fixed in develop, and develop should be merged to master soon.
