### ISSUE TITLE
[Feature Request] Add client Premiumize.me cloud torrent downloader

### ISSUE THREAD

**Issue by piejanssens** [SiCKRAGETV/sickrage-issues#2004]
This is a FR to allow SR to send torrent downloads to Premiumize and downloading them.

The approach would be different than local downloaders because it's a cloud service.
Premiumize allows you to upload a magnet/torrent file and it will anonymously download the torrent (unless the files are already cached on their own servers) after this you can download the file from premiumize.me (HTTP).

Thus this would require SR to do the HTTP downloading part.

Premiumize has an API to be able to do what is described above.

**Comment by neoatomic** [comment]
This is a payed cloud download service. 
So its very hard to implement as we dont have accounts to even test. I will add it to the feature request list, but dont have to high hopes for getting this added anytime soon.

**Comment by miigotu** [comment]
The best that we could even do with this is sending the link to premiumize. SickRage isn't going to be doing any download management anytime soon.

**Comment by piejanssens** [comment]
I thought so too. That's why I'm planning to build the middleware in python to manage this. In and out will be the same as a torrent client.

**Comment by miigotu** [comment]
We don't build any downloading handling into SR. We only send a link or torrent file to a client and the client handles the downloading. Build the client into SR that sends the link to premiumize then automate flexget or some other automated or rss downloader to download the HTTP, and the SR will PP it.

Maybe someday we could build a multithreaded download client and torrent client right into SR but that comes with security and tracking risks and a whole slew of new things to think about, so it absolutely will not be allowed in the near future.
