### ISSUE TITLE
[APP SUBMITTED]: CHECKVERSION :: git symbolic-ref -q HEAD returned : fatal: bad config file line 1 in .git/config

### ISSUE THREAD

**Issue by wordguy** [SiCKRAGETV/sickrage-issues#2005]
### INFO
Python Version: **2.7.6 (default, Nov 10 2013, 19:24:18) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@4a47a5cf7eff76f0d99a9c0f3b574027d1f56dd8
Link to Log: https://gist.github.com/7e7049f37d8a303f2eb9
### ERROR
```
CHECKVERSION :: git symbolic-ref -q HEAD returned : fatal: bad config file line 1 in .git/config
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by MGaetan89** [comment]
What do you have in your `.git/config` file?

**Comment by wordguy** [comment]
Here it is: 

Any idea what is wrong?

[General]
git_autoissues = 0
git_username = wordguy
git_password = XXXXXXX
git_reset = 1
branch = master
git_remote = origin
git_remote_url = https://github.com/SiCKRAGETV/SickRage.git
cur_commit_hash = 4a47a5cf7eff76f0d99a9c0f3b574027d1f56dd8
cur_commit_branch = ""
config_version = 7
encryption_version = 0
encryption_secret = b5XUkzPGRxaIhRq1s4ysRoXQO+vYIUoviSiUF065vxE=
log_dir = Logs
log_nr = 5
log_size = 1048576
socket_timeout = None
web_port = 8081
web_host = 0.0.0.0
web_ipv6 = 0
web_log = 0
web_root = ""
web_username = DMcGillivray
web_password = XXXXXXX
web_cookie_secret = viE3sGbcQ0Cvz01OR7E+pikTGrqFUEOyms+0CrSQoG4=
web_use_gzip = 1
download_url = ""
localhost_ip = ""
cpu_preset = NORMAL
anon_redirect = http://dereferer.org/?
api_key = a3ba0a9dc49c39710c0c7e4dab3d72b8
debug = 0
enable_https = 0
https_cert = server.crt
https_key = server.key
handle_reverse_proxy = 0
use_nzbs = 1
use_torrents = 1
nzb_method = sabnzbd
torrent_method = transmission
usenet_retention = 2500
autopostprocesser_frequency = 5
dailysearch_frequency = 15
backlog_frequency = 720
update_frequency = 1
showupdate_hour = 15
download_propers = 1
randomize_providers = 0
check_propers_interval = 4h
allow_high_priority = 1
dailysearch_startup = 1
backlog_startup = 1
skip_removed_files = 0
quality_default = 3
status_default = 5
flatten_folders_default = 0
indexer_default = 2
indexer_timeout = 20
anime_default = 0
scene_default = 0
provider_order = oznzb nzbplanet nzb_is sick_beard_index torrenting_com kat_cr kickasstorrents thepiratebay nzbs_org hounddawgs hdbits alpharatio scenetime eztv btn rarbg torrentbytes speedcd tntvillage shazbat_tv animenzb animezb nyaatorrents morethantv binsearch omgwtfnzbs womble_s_index iptorrents ezrss torrentday sceneaccess bitsoup tokyotoshokan hdtorrents oldpiratebay freshontv nextgen t411 torrentleech usenet_crawler
version_notify = 1
auto_update = 1
notify_on_update = 1
naming_strip_year = 0
naming_pattern = Season %S/%SN - S%0SE%0E - %EN
naming_custom_abd = 0
naming_abd_pattern = %SN - %A.D - %EN
naming_custom_sports = 0
naming_sports_pattern = %SN - %A-D - %EN
naming_custom_anime = 0
naming_anime_pattern = Season %0S/%SN - S%0SE%0E - %EN
naming_multi_ep = 1
naming_anime_multi_ep = 1
naming_anime = 3
indexerDefaultLang = en
ep_default_deleted_status = 6
launch_browser = 1
update_shows_on_start = 1
update_shows_on_snatch = 0
trash_remove_show = 0
trash_rotate_logs = 0
sort_article = 0
proxy_setting = ""
proxy_indexers = 0
use_listview = 0
metadata_kodi = 0|0|0|0|0|0|0|0|0|0
metadata_kodi_12plus = 0|0|0|0|0|0|0|0|0|0
metadata_mediabrowser = 0|0|0|0|0|0|0|0|0|0
metadata_ps3 = 0|0|0|0|0|0|0|0|0|0
metadata_wdtv = 0|0|0|0|0|0|0|0|0|0
metadata_tivo = 0|0|0|0|0|0|0|0|0|0
metadata_mede8er = 0|0|0|0|0|0|0|0|0|0
backlog_days = 7
cache_dir = cache
root_dirs = 0|Z:\TV Shows|Y:\TV Shows 2
tv_download_dir = C:\CP Torrents\SickRage
keep_processed_dir = 0
process_method = move
del_rar_contents = 0
move_associated_files = 1
sync_files = "!sync,lftp-pget-status,part,bts,!qb"
postpone_if_sync_files = 1
nfo_rename = 1
process_automatically = 1
no_delete = 0
unpack = 1
rename_episodes = 0
airdate_episodes = 0
create_missing_show_dirs = 0
add_shows_wo_dir = 0
extra_scripts = ""
git_path = ""
ignore_words = "german,french,core2hd,dutch,swedish,reenc,MrLss"
require_words = ""
calendar_unprotected = 0
no_restart = 0
developer = 0
display_all_seasons = 1
[Blackhole]
nzb_dir = ""
torrent_dir = ""
[TORRENTING_COM]
torrenting_com = 1
torrenting_com_ratio = ""
torrenting_com_proxy = 0
torrenting_com_proxy_url = http://proxite.eu/
torrenting_com_search_mode = eponly
torrenting_com_search_fallback = 1
torrenting_com_enable_daily = 0
torrenting_com_enable_backlog = 1
[KAT_CR]
kat_cr = 1
kat_cr_ratio = ""
kat_cr_proxy = 0
kat_cr_proxy_url = http://proxite.eu/
kat_cr_search_mode = eponly
kat_cr_search_fallback = 1
kat_cr_enable_daily = 0
kat_cr_enable_backlog = 1
[KICKASSTORRENTS]
kickasstorrents = 1
kickasstorrents_confirmed = 1
kickasstorrents_ratio = ""
kickasstorrents_minseed = 5
kickasstorrents_minleech = 0
kickasstorrents_proxy = 0
kickasstorrents_proxy_url = http://proxite.eu/
kickasstorrents_search_mode = eponly
kickasstorrents_search_fallback = 0
kickasstorrents_enable_daily = 1
kickasstorrents_enable_backlog = 1
[THEPIRATEBAY]
thepiratebay = 1
thepiratebay_confirmed = 1
thepiratebay_ratio = ""
thepiratebay_minseed = 5
thepiratebay_minleech = 0
thepiratebay_proxy = 0
thepiratebay_proxy_url = http://proxite.eu/
thepiratebay_search_mode = eponly
thepiratebay_search_fallback = 0
thepiratebay_enable_daily = 1
thepiratebay_enable_backlog = 1
[HOUNDDAWGS]
hounddawgs = 0
hounddawgs_username = DMcGillivray
hounddawgs_password = XXXXXXX
hounddawgs_ratio = ""
hounddawgs_minseed = 0
hounddawgs_minleech = 0
hounddawgs_proxy = 0
hounddawgs_proxy_url = http://proxite.eu/
hounddawgs_search_mode = eponly
hounddawgs_search_fallback = 0
hounddawgs_enable_daily = 1
hounddawgs_enable_backlog = 1
[HDBITS]
hdbits = 0
hdbits_username = ""
hdbits_passkey = ""
hdbits_ratio = ""
hdbits_proxy = 0
hdbits_proxy_url = http://proxite.eu/
hdbits_search_mode = eponly
hdbits_search_fallback = 0
hdbits_enable_daily = 1
hdbits_enable_backlog = 1
[ALPHARATIO]
alpharatio = 0
alpharatio_username = ""
alpharatio_password = ""
alpharatio_ratio = ""
alpharatio_minseed = 0
alpharatio_minleech = 0
alpharatio_proxy = 0
alpharatio_proxy_url = http://proxite.eu/
alpharatio_search_mode = eponly
alpharatio_search_fallback = 0
alpharatio_enable_daily = 1
alpharatio_enable_backlog = 1
[SCENETIME]
scenetime = 0
scenetime_username = ""
scenetime_password = ""
scenetime_ratio = ""
scenetime_minseed = 0
scenetime_minleech = 0
scenetime_proxy = 0
scenetime_proxy_url = http://proxite.eu/
scenetime_search_mode = eponly
scenetime_search_fallback = 0
scenetime_enable_daily = 1
scenetime_enable_backlog = 1
[BTN]
btn = 0
btn_api_key = ""
btn_ratio = ""
btn_proxy = 0
btn_proxy_url = http://proxite.eu/
btn_search_mode = eponly
btn_search_fallback = 0
btn_enable_daily = 1
btn_enable_backlog = 1
[RARBG]
rarbg = 0
rarbg_ranked = 0
rarbg_sorting = seeders
rarbg_ratio = ""
rarbg_minseed = 0
rarbg_minleech = 0
rarbg_proxy = 0
rarbg_proxy_url = http://proxite.eu/
rarbg_search_mode = eponly
rarbg_search_fallback = 0
rarbg_enable_daily = 1
rarbg_enable_backlog = 1
[TORRENTBYTES]
torrentbytes = 0
torrentbytes_username = ""
torrentbytes_password = ""
torrentbytes_ratio = ""
torrentbytes_minseed = 0
torrentbytes_minleech = 0
torrentbytes_proxy = 0
torrentbytes_proxy_url = http://proxite.eu/
torrentbytes_search_mode = eponly
torrentbytes_search_fallback = 0
torrentbytes_enable_daily = 1
torrentbytes_enable_backlog = 1
[SPEEDCD]
speedcd = 0
speedcd_username = ""
speedcd_password = ""
speedcd_ratio = ""
speedcd_minseed = 0
speedcd_minleech = 0
speedcd_proxy = 0
speedcd_proxy_url = http://proxite.eu/
speedcd_freeleech = 0
speedcd_search_mode = eponly
speedcd_search_fallback = 0
speedcd_enable_daily = 1
speedcd_enable_backlog = 1
[TNTVILLAGE]
tntvillage = 0
tntvillage_username = ""
tntvillage_password = ""
tntvillage_ratio = ""
tntvillage_minseed = 0
tntvillage_minleech = 0
tntvillage_proxy = 0
tntvillage_proxy_url = http://proxite.eu/
tntvillage_search_mode = eponly
tntvillage_search_fallback = 0
tntvillage_enable_daily = 1
tntvillage_enable_backlog = 1
tntvillage_cat = 0
tntvillage_subtitle = 0
[SHAZBAT_TV]
shazbat_tv = 0
shazbat_tv_passkey = ""
shazbat_tv_ratio = ""
shazbat_tv_options = ""
shazbat_tv_proxy = 0
shazbat_tv_proxy_url = http://proxite.eu/
shazbat_tv_search_mode = eponly
shazbat_tv_search_fallback = 0
shazbat_tv_enable_daily = 1
shazbat_tv_enable_backlog = 1
[NYAATORRENTS]
nyaatorrents = 0
nyaatorrents_ratio = ""
nyaatorrents_proxy = 0
nyaatorrents_proxy_url = http://proxite.eu/
nyaatorrents_search_mode = eponly
nyaatorrents_search_fallback = 0
nyaatorrents_enable_daily = 1
nyaatorrents_enable_backlog = 1
[MORETHANTV]
morethantv = 0
morethantv_username = ""
morethantv_password = ""
morethantv_ratio = ""
morethantv_minseed = 0
morethantv_minleech = 0
morethantv_proxy = 0
morethantv_proxy_url = http://proxite.eu/
morethantv_freeleech = 0
morethantv_search_mode = eponly
morethantv_search_fallback = 0
morethantv_enable_daily = 1
morethantv_enable_backlog = 1
[IPTORRENTS]
iptorrents = 0
iptorrents_username = ""
iptorrents_password = ""
iptorrents_ratio = ""
iptorrents_proxy = 0
iptorrents_proxy_url = http://proxite.eu/
iptorrents_freeleech = 0
iptorrents_search_mode = eponly
iptorrents_search_fallback = 0
iptorrents_enable_daily = 1
iptorrents_enable_backlog = 1
[TORRENTDAY]
torrentday = 0
torrentday_username = ""
torrentday_password = ""
torrentday_ratio = ""
torrentday_minseed = 0
torrentday_minleech = 0
torrentday_proxy = 0
torrentday_proxy_url = http://proxite.eu/
torrentday_freeleech = 0
torrentday_search_mode = eponly
torrentday_search_fallback = 0
torrentday_enable_daily = 1
torrentday_enable_backlog = 1
[SCENEACCESS]
sceneaccess = 0
sceneaccess_username = ""
sceneaccess_password = ""
sceneaccess_ratio = ""
sceneaccess_minseed = 0
sceneaccess_minleech = 0
sceneaccess_proxy = 0
sceneaccess_proxy_url = http://proxite.eu/
sceneaccess_search_mode = eponly
sceneaccess_search_fallback = 0
sceneaccess_enable_daily = 1
sceneaccess_enable_backlog = 1
[BITSOUP]
bitsoup = 0
bitsoup_username = ""
bitsoup_password = ""
bitsoup_ratio = ""
bitsoup_minseed = 0
bitsoup_minleech = 0
bitsoup_proxy = 0
bitsoup_proxy_url = http://proxite.eu/
bitsoup_search_mode = eponly
bitsoup_search_fallback = 0
bitsoup_enable_daily = 1
bitsoup_enable_backlog = 1
[TOKYOTOSHOKAN]
tokyotoshokan = 0
tokyotoshokan_ratio = ""
tokyotoshokan_proxy = 0
tokyotoshokan_proxy_url = http://proxite.eu/
tokyotoshokan_search_mode = eponly
tokyotoshokan_search_fallback = 0
tokyotoshokan_enable_daily = 1
tokyotoshokan_enable_backlog = 1
[HDTORRENTS]
hdtorrents = 0
hdtorrents_username = ""
hdtorrents_password = ""
hdtorrents_ratio = ""
hdtorrents_minseed = 0
hdtorrents_minleech = 0
hdtorrents_proxy = 0
hdtorrents_proxy_url = http://proxite.eu/
hdtorrents_search_mode = eponly
hdtorrents_search_fallback = 0
hdtorrents_enable_daily = 1
hdtorrents_enable_backlog = 1
[FRESHONTV]
freshontv = 0
freshontv_username = ""
freshontv_password = ""
freshontv_ratio = ""
freshontv_minseed = 0
freshontv_minleech = 0
freshontv_proxy = 0
freshontv_proxy_url = http://proxite.eu/
freshontv_freeleech = 0
freshontv_search_mode = eponly
freshontv_search_fallback = 0
freshontv_enable_daily = 1
freshontv_enable_backlog = 1
[NEXTGEN]
nextgen = 0
nextgen_username = ""
nextgen_password = ""
nextgen_ratio = ""
nextgen_proxy = 0
nextgen_proxy_url = http://proxite.eu/
nextgen_search_mode = eponly
nextgen_search_fallback = 0
nextgen_enable_daily = 1
nextgen_enable_backlog = 1
[T411]
t411 = 0
t411_username = ""
t411_password = ""
t411_ratio = ""
t411_proxy = 0
t411_proxy_url = http://proxite.eu/
t411_search_mode = eponly
t411_search_fallback = 0
t411_enable_daily = 1
t411_enable_backlog = 1
[TORRENTLEECH]
torrentleech = 0
torrentleech_username = ""
torrentleech_password = ""
torrentleech_ratio = ""
torrentleech_minseed = 0
torrentleech_minleech = 0
torrentleech_proxy = 0
torrentleech_proxy_url = http://proxite.eu/
torrentleech_search_mode = eponly
torrentleech_search_fallback = 0
torrentleech_enable_daily = 1
torrentleech_enable_backlog = 1
[OZNZB]
oznzb = 1
oznzb_search_mode = eponly
oznzb_search_fallback = 1
oznzb_enable_daily = 1
oznzb_enable_backlog = 1
[NZBPLANET]
nzbplanet = 1
nzbplanet_search_mode = eponly
nzbplanet_search_fallback = 1
nzbplanet_enable_daily = 1
nzbplanet_enable_backlog = 0
[NZB_IS]
nzb_is = 1
nzb_is_search_mode = eponly
nzb_is_search_fallback = 1
nzb_is_enable_daily = 1
nzb_is_enable_backlog = 0
[SICK_BEARD_INDEX]
sick_beard_index = 1
sick_beard_index_search_mode = eponly
sick_beard_index_search_fallback = 1
sick_beard_index_enable_daily = 1
sick_beard_index_enable_backlog = 1
[NZBS_ORG]
nzbs_org = 0
nzbs_org_search_mode = eponly
nzbs_org_search_fallback = 0
nzbs_org_enable_daily = 1
nzbs_org_enable_backlog = 1
[ANIMENZB]
animenzb = 0
animenzb_search_mode = eponly
animenzb_search_fallback = 0
animenzb_enable_daily = 1
animenzb_enable_backlog = 1
[ANIMEZB]
animezb = 0
animezb_search_mode = eponly
animezb_search_fallback = 0
animezb_enable_daily = 1
animezb_enable_backlog = 1
[BINSEARCH]
binsearch = 0
binsearch_search_mode = eponly
binsearch_search_fallback = 0
binsearch_enable_daily = 1
binsearch_enable_backlog = 1
[OMGWTFNZBS]
omgwtfnzbs = 0
omgwtfnzbs_api_key = ""
omgwtfnzbs_username = ""
omgwtfnzbs_search_mode = eponly
omgwtfnzbs_search_fallback = 0
omgwtfnzbs_enable_daily = 1
omgwtfnzbs_enable_backlog = 1
[WOMBLE_S_INDEX]
womble_s_index = 0
womble_s_index_search_mode = eponly
womble_s_index_search_fallback = 0
womble_s_index_enable_daily = 1
womble_s_index_enable_backlog = 1
[USENET_CRAWLER]
usenet_crawler = 0
usenet_crawler_search_mode = eponly
usenet_crawler_search_fallback = 0
usenet_crawler_enable_daily = 1
usenet_crawler_enable_backlog = 1
[NZB_CAT]
nzb_cat = 0
nzb_cat_search_mode = eponly
nzb_cat_search_fallback = 0
nzb_cat_enable_daily = 1
nzb_cat_enable_backlog = 1
[NZBs]
nzbs = 0
nzbs_uid = ""
nzbs_hash = ""
[Newzbin]
newzbin = 0
newzbin_username = ""
newzbin_password = ""
[SABnzbd]
sab_username = DMcGillivray
sab_password = XXXXXXXX
sab_apikey = 2b77411ef8866b305cae72622593084f
sab_category = tv
sab_category_anime = anime
sab_host = https://localhost:9090/
sab_forced = 0
[NZBget]
nzbget_username = nzbget
nzbget_password = tegbzn6789
nzbget_category = tv
nzbget_category_anime = anime
nzbget_host = ""
nzbget_use_https = 0
nzbget_priority = 100
[TORRENT]
torrent_username = DMcGillivray
torrent_password = XXXXXXX
torrent_host = http://localhost:9091/
torrent_path = C:\CP Torrents\SickRage
torrent_seed_time = 0
torrent_paused = 0
torrent_high_bandwidth = 1
torrent_label = ""
torrent_label_anime = ""
torrent_verify_cert = 0
torrent_rpcurl = transmission
torrent_auth_type = none
[KODI]
use_kodi = 1
kodi_always_on = 1
kodi_notify_onsnatch = 0
kodi_notify_ondownload = 1
kodi_notify_onsubtitledownload = 0
kodi_update_library = 1
kodi_update_full = 0
kodi_update_onlyfirst = 0
kodi_host = 192.168.0.17:80
kodi_username = kodi
kodi_password = summer69
[Plex]
use_plex = 1
plex_notify_onsnatch = 0
plex_notify_ondownload = 0
plex_notify_onsubtitledownload = 0
plex_update_library = 1
plex_server_host = localhost:32400
plex_server_token = s3NL3PvxzPRhxMzSRxXg
plex_host = ""
plex_username = wordguy
plex_password = XXXXXXX
[Growl]
use_growl = 0
growl_notify_onsnatch = 0
growl_notify_ondownload = 0
growl_notify_onsubtitledownload = 0
growl_host = ""
growl_password = ""
[FreeMobile]
use_freemobile = 0
freemobile_notify_onsnatch = 0
freemobile_notify_ondownload = 0
freemobile_notify_onsubtitledownload = 0
freemobile_id = ""
freemobile_apikey = ""
[Prowl]
use_prowl = 0
prowl_notify_onsnatch = 0
prowl_notify_ondownload = 0
prowl_notify_onsubtitledownload = 0
prowl_api = ""
prowl_priority = 0
[Twitter]
use_twitter = 0
twitter_notify_onsnatch = 0
twitter_notify_ondownload = 0
twitter_notify_onsubtitledownload = 0
twitter_username = ""
twitter_password = ""
twitter_prefix = SickRage
[Boxcar]
use_boxcar = 0
boxcar_notify_onsnatch = 0
boxcar_notify_ondownload = 0
boxcar_notify_onsubtitledownload = 0
boxcar_username = ""
[Boxcar2]
use_boxcar2 = 0
boxcar2_notify_onsnatch = 0
boxcar2_notify_ondownload = 0
boxcar2_notify_onsubtitledownload = 0
boxcar2_accesstoken = ""
[Pushover]
use_pushover = 0
pushover_notify_onsnatch = 0
pushover_notify_ondownload = 0
pushover_notify_onsubtitledownload = 0
pushover_userkey = ""
pushover_apikey = ""
[Libnotify]
use_libnotify = 0
libnotify_notify_onsnatch = 0
libnotify_notify_ondownload = 0
libnotify_notify_onsubtitledownload = 0
[NMJ]
use_nmj = 0
nmj_host = ""
nmj_database = ""
nmj_mount = ""
[NMJv2]
use_nmjv2 = 0
nmjv2_host = ""
nmjv2_database = ""
nmjv2_dbloc = ""
[Synology]
use_synoindex = 0
[SynologyNotifier]
use_synologynotifier = 0
synologynotifier_notify_onsnatch = 0
synologynotifier_notify_ondownload = 0
synologynotifier_notify_onsubtitledownload = 0
[Trakt]
use_trakt = 0
trakt_username = ""
trakt_access_token = ""
trakt_refresh_token = ""
trakt_remove_watchlist = 0
trakt_remove_serieslist = 0
trakt_sync_watchlist = 0
trakt_method_add = 0
trakt_start_paused = 0
trakt_use_recommended = 0
trakt_sync = 0
trakt_sync_remove = 0
trakt_default_indexer = 1
trakt_disable_ssl_verify = 0
trakt_timeout = 30
trakt_blacklist_name = ""
trakt_use_rolling_download = 0
trakt_rolling_num_ep = 0
trakt_rolling_add_paused = 1
trakt_rolling_frequency = 8
[pyTivo]
use_pytivo = 0
pytivo_notify_onsnatch = 0
pytivo_notify_ondownload = 0
pytivo_notify_onsubtitledownload = 0
pyTivo_update_library = 0
pytivo_host = ""
pytivo_share_name = ""
pytivo_tivo_name = ""
[NMA]
use_nma = 0
nma_notify_onsnatch = 0
nma_notify_ondownload = 0
nma_notify_onsubtitledownload = 0
nma_api = ""
nma_priority = 0
[Pushalot]
use_pushalot = 0
pushalot_notify_onsnatch = 0
pushalot_notify_ondownload = 0
pushalot_notify_onsubtitledownload = 0
pushalot_authorizationtoken = ""
[Pushbullet]
use_pushbullet = 1
pushbullet_notify_onsnatch = 0
pushbullet_notify_ondownload = 1
pushbullet_notify_onsubtitledownload = 0
pushbullet_api = fgZV4T5OumiuhpC9kgfCpJY4ea4iErZm
pushbullet_device = ""
[Email]
use_email = 0
email_notify_onsnatch = 0
email_notify_ondownload = 0
email_notify_onsubtitledownload = 0
email_host = ""
email_port = 25
email_tls = 0
email_user = ""
email_password = ""
email_from = ""
email_list = ""
[Newznab]
newznab_data = "Sick Beard Index|http://lolo.sickbeard.com/|0|5030,5040|1|eponly|1|1|1!!!NZBs.org|https://nzbs.org/||5030,5040|0|eponly|0|1|1!!!Usenet-Crawler|https://www.usenet-crawler.com/||5030,5040|0|eponly|0|1|1!!!OZnzb|https://api.oznzb.com/|c27cfcb670c5d595ac8ff7e83e1c9625|5030,5040|1|eponly|1|1|1!!!NZBPlanet|https://api.nzbplanet.net/|30a7f9cbc25080badea54458bb89a743|5030,5040|1|eponly|1|1|0!!!NZB.is|https://api.nzb.is/|9225c3ebbc7bea33cef662613e7bdbc9|5030,5040|1|eponly|1|1|0"
[TorrentRss]
torrentrss_data = "Torrenting.com|https://www.torrenting.com/get_rss.php?feed=direct&user=wordguy&cat=4,5&passkey=1714cbac40f6aeb2c942820f19dc1f6a|uid=wordguy;pass=XXXXXX|title|1|eponly|1|0|1!!!Kat.cr|http://kat.cr/tv/?rss=1||title|1|eponly|1|0|1"
[GUI]
gui_name = slick
theme_name = dark
home_layout = poster
history_layout = detailed
display_show_specials = 1
coming_eps_layout = banner
coming_eps_display_paused = 0
coming_eps_sort = date
coming_eps_missed_range = 7
fuzzy_dating = 0
trim_zero = 0
date_preset = %x
time_preset = %I:%M:%S %p
timezone_display = network
poster_sortby = name
poster_sortdir = 1
filter_row = 0
[Subtitles]
use_subtitles = 0
subtitles_languages = ""
SUBTITLES_SERVICES_LIST = ""
SUBTITLES_SERVICES_ENABLED = ""
subtitles_dir = ""
subtitles_default = 0
subtitles_history = 0
embedded_subtitles_all = 0
subtitles_finder_frequency = 1
subtitles_multi = 1
[FailedDownloads]
use_failed_downloads = 1
delete_failed = 1
[ANIDB]
use_anidb = 0
anidb_username = ""
anidb_password = ""
anidb_use_mylist = 0
[ANIME]
anime_split_home = 0


Date: Wed, 8 Jul 2015 10:36:56 -0700

**Comment by fernandog** [comment]
@wordguy not this file SickRage/config but SickRage/.git/config

**Comment by wordguy** [comment]
Ah, ok. 

Not much:

       Only 'Null' repeated 332 times.                                                                                                                                                                                                                                                                                                                                     

Date: Wed, 8 Jul 2015 10:42:43 -0700
From: notifications@github.com
To: sickrage-issues@noreply.github.com
CC: davidmcgillivray@hotmail.com
Subject: Re: [sickrage-issues] [APP SUBMITTED]: CHECKVERSION :: git symbolic-ref -q HEAD returned : fatal: bad config file line 1 in .git/config (#2005)

@wordguy not this file SickRage/config but SickRage/.git/config


—
Reply to this email directly or view it on GitHub.

**Comment by fernandog** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.2.3-2-osmc-armv7l-with-debian-8.2**
Locale: UTF-8
Branch: ****
Commit: SiCKRAGETV/SickRage@27748a828277cd5a6cd4d8a07d16de7e53e6a1b4
Link to Log: https://gist.github.com/0e71aed661775dfd31ae
### ERROR
```
Thread-43 :: git symbolic-ref -q HEAD returned : 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
