### ISSUE TITLE
Newznab categories finder not include TV master category

### ISSUE THREAD

**Issue by TheAtlantis** [SiCKRAGETV/sickrage-issues#2006]
Hi, 

I have look an error / missing in the fonction : get_newznab_categories() into newznab.py.

In this : 
```
            for category in data.feed.categories:
                if category.get('name') == 'TV':
                        for subcat in category.subcats:
                            return_categories.append(subcat)
```

The main category "TV" is not  returned by the function. 
This has the consequence that the items in this category are not wanted, As this category is often used to store foreign language elements (like French...)

I purpose this to solve this issue. 
```
            for category in data.feed.categories:
                if category.get('name') == 'TV':
                        return_categories.append(category)
                        for subcat in category.subcats:
                            return_categories.append(subcat)
```
And... add 5000 category code to the default. 

Thanks a lot for your works. 

Michel from France

**Comment by fernandog** [comment]
@TheAtlantis did you test this?

**Comment by TheAtlantis** [comment]
@fernandog yes, I test with the last revision with OZNZB newznab and on synology nas. 

API request sample before : https://api.oznzb.com/api?apikey=**********&maxage=4&attrs=rageid&t=tvsearch&cat=5040%2C5050%2C5030%2C5060%2C5070

and after : https://api.oznzb.com/api?apikey=**********&maxage=4&attrs=rageid&t=tvsearch&cat=5000%2C5040%2C5050%2C5030%2C5060%2C5070

This "patch" grant the user to select TV (code 5000) main category from categories selection in Newznab search categories.

**Comment by fernandog** [comment]
Merged in develop.
