### ISSUE TITLE
Question - tvshow.nfo

### ISSUE THREAD

**Issue by Vodka2014** [SiCKRAGETV/sickrage-issues#2007]
Hi,

I am having some permission issues so it could not update all the tvshow.nfo files. If I do a mass update to all shows it will re-do the tvshow.nfo correct?

This is after I fixed all the permission issues on my Synology. 

Thanks

**Comment by miigotu** [comment]
Yes, if it has permissions it will rewrite the tvshow.nfo, as long as you have metadata creation enabled for kodi 12+.

**Comment by Vodka2014** [comment]
Thanks
