### ISSUE TITLE
Synology + SickRage HTTPS Error

### ISSUE THREAD

**Issue by Vodka2014** [SiCKRAGETV/sickrage-issues#2008]
Hi,

So I decided to install everything on my Synology and it is working 100% after a few tweaks and config changes etc....

I am thou getting this error:
```
/usr/local/python/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
InsecureRequestWarning)
/usr/local/python/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
InsecureRequestWarning)
/usr/local/python/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
InsecureRequestWarning) 
```

Post Processing is working and it is doing what it is meant to do but I want to try and get this fixed.

Any Idea on how I can fix this.

Thanks again.

**Comment by miigotu** [comment]
Without a proper log I don't know which connection is causing this warning, but certificate verification is enabled in develop. The only insecure certificates you should have are from nas or torrent clients, since those generally have self signed certificates.

**Comment by miigotu** [comment]
Can you provide more of the log?

**Comment by neoatomic** [comment]
@Vodka2014 You say that you installed everything on your Synology. Did you also migrate the config.ini and scikbeard.db?

@miigotu Log from https://github.com/SiCKRAGETV/sickrage-issues/issues/2011

https://gist.github.com/Vodka2014/7e76725ecf6992e69dff

Synology normally wont have any ssl problems. So maybe its the settings migrated from another machine/bad cert or using a proxy.? 

```
AASSLEOFError: EOF occurred in violation of protocol (_ssl.c:590)
AA File "<string>", line 3, in raise_exc_info
AA raise_exc_info(self._exc_info)
AA File "/volume5/@appstore/sickrage/var/SickRage/tornado/concurrent.py", line 209, in result
AA value = future.result()
AA File "/volume5/@appstore/sickrage/var/SickRage/tornado/gen.py", line 807, in run
AA quiet_exceptions=iostream.StreamClosedError)
AA File "/volume5/@appstore/sickrage/var/SickRage/tornado/http1connection.py", line 166, in _read_message
AA yielded = self.gen.throw(*sys.exc_info())
AA File "/volume5/@appstore/sickrage/var/SickRage/tornado/gen.py", line 810, in run
AA raise_exc_info(self._exc_info)
AA File "/volume5/@appstore/sickrage/var/SickRage/tornado/concurrent.py", line 209, in result
AA value = future.result()
AA File "/volume5/@appstore/sickrage/var/SickRage/tornado/gen.py", line 807, in run
AA ret = yield conn.read_response(request_delegate)
AA File "/volume5/@appstore/sickrage/var/SickRage/tornado/http1connection.py", line 691, in _server_request_loop
AATraceback (most recent call last):
AA2015-07-09 08:26:32 ERROR Uncaught exception 
```

**Comment by Vodka2014** [comment]
Well i tried the restore and it did not work. So i set everything up from the ground up.

**Comment by neoatomic** [comment]
@Vodka2014 The restore might have partial restored the backup. And could be causing the problems.

Can you backup and than remove SickRage from the package center and than reinstall.? We need to be sure that you have a fresh install without any old files from another machine.
And see if you can post the log with the errors so we can take a closer look.

**Comment by Vodka2014** [comment]
Sure. When i get back home later i will run a backup then uninstall and re-install and see what happens.

Let you know thanks.

**Comment by miigotu** [comment]
@Vodka2014 next time, don't open another issue, continue using the same issue for your questions since most of your issues are just setup/configuration/install problems and questions.

We don't need 1000 issues, and it makes it harder to track your progress.

**Comment by Vodka2014** [comment]
Sure i will keep everything to 1 Case.

**Comment by Vodka2014** [comment]
Here we go again where the restore function does NOT work. I ran a backup, uninstall, re-installed, added the restore, rebooted and blank.
....

**Comment by neoatomic** [comment]
@Vodka2014 The point was to NOT restore. As we need to be sure that its not the old config from your other device that is causing the problem.
Also are you using a proxy or similar in your setup.?

**Comment by Vodka2014** [comment]
Well it installed 100% the only issue is that it cannot update to the new version (It stated no updated needed). Before I removed it I saw 24 hours later that it was 159 Commits behind. 

I will installer and re-install again using the SickRage Installer on the SynoCommunity.

SickRage 
Version: 20150526-1

git://github.com/SiCKRAGETV/SickRage.git
master

Installed

Next

**Comment by neoatomic** [comment]
When you install SickRage form SynoCommunity it automatically downloads the latest version so that is normal. :)

Dont restore, but do a basic setup with only the essentials show/indexer/provider etc. and do a search.
See if it still gives errors.

**Comment by Vodka2014** [comment]
Ok will do. I have noticed that under Advanced Settings there is "Error: No branches found" is this normal if not can i manually fix this in the config ?

**Comment by miigotu** [comment]
@Vodka2014 The host key thing is my fault.

get to command line, in SR dir, and do git pull (it will ask you to accept the github ssh keyr)
once you accept the key it will work like normal for the updater at least.

I changed the url from https to ssh -.- I will switch it back.

**Comment by Vodka2014** [comment]
@miigotu Ok cool. Please can you list the steps for this if you do not mind.

**Comment by miigotu** [comment]
If you know where your config.ini is, you can stop sickrage (important) and find this key:
```
[General]
git_remote_url = git@github.com:SiCKRAGETV/SickRage.git
```
and change it to:

```
[General]
git_remote_url = https://github.com/SiCKRAGETV/SickRage.git
```

That should make it work once restarting SR.

**Comment by neoatomic** [comment]
@Vodka2014 First you need to enable SSH in DSM. 
If you go to configuration its the last option called terminal and snmpt. And then enable SSH service.
Than stop SickRage in the package center.
Now download WinSCP https://winscp.net/ and create a connection with your admin account. (File protocol is SCP)
You can find the config.ini under : /volume1/@appstore/sickrage/var
Than right click on config.ini and select edit and replace the like miigotu posted. 
And restart SickRage in the package center.

**Comment by miigotu** [comment]
SR needs to be stopped before editing the config.ini, or your changes get overwritten when restarting SR.

**Comment by miigotu** [comment]
btw, `InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
InsecureRequestWarning)`

is not an error, it just lets you know the certificate was not verified.

**Comment by Vodka2014** [comment]
I am now 4 commits behind and updated 100% I must state that the support for you all is tops and thanks for the help on this :) 

Now it is time to add a show and see how it behaves.

**Comment by miigotu** [comment]
I think that warning is from when SR contacts your client, because we do not verify certificates on clients since they are usually self-signed.

**Comment by Vodka2014** [comment]
Thanks. I am loading some shows to see if it will auto grab at 3AM. Will post again tomorrow. Thanks for the help all so far :)

**Comment by Vodka2014** [comment]
Morning, I have updated SickRage as i see there was some updates pushed out and again it is back to

https://gist.github.com/Vodka2014/7e76725ecf6992e69dff

**Comment by miigotu** [comment]
then it is a problem with your openssl. I cant even tell from your half log what connection is being attempted because you always only give me the error.

**Comment by neoatomic** [comment]
I'm running the exact same packages on my Synology and i don't a single problem. Also as Vodka2014 was having the same problems on another device i get more the impression that this is an external problem that is causing the issue. Proxy, banned/blocked site, bad DNS etc.

@Vodka2014 If you can post a FULL log we can take a last look if we can spot the problem. 
Also check your network. Are you using a proxy, and check you DNS server etc.

**Comment by miigotu** [comment]
@neoatomic Different software version on syno? different model? it makes a difference. maybe he is missing a package or broke some dependancy somehow. since yours works we just know that it can, nothing more =P

SSL cert verification could be causing this for him, but I don't want to disable verification in all of SR for it, I want to disable it in the provider/client that is causing it.  Without the full debug log I'm useless.

**Comment by neoatomic** [comment]
@miigotu  Hard to say off-course  But all is pulled from the Synocomunity repo so should be identical for all Syno users. (also py/openssl and git)
And as he had the same problems on another device (non Syno) i get the feeling that its an external factor that is causing the problem.

**Comment by miigotu** [comment]
Do you have to tell your Syno to install py/openssl? That is another problem it could be, missing pyOpenSSL

**Comment by neoatomic** [comment]
No, an additional python package is installed (separate from the already build-in OS package) when you install the Sickrage package from Synocummunity repo. All is automated and no manual configuration is required at all. 

Here are the versions of the modules according to the install.log. : 
(Including pycrypto and pyOpenSSL)
```
Python 2.7.10

System installed modules:
bcrypt==1.1.1
cffi==1.1.0
Cheetah==2.4.4
cryptography==0.9
enum34==1.0.4
idna==2.0
ipaddress==1.0.7
lxml==3.4.4
M2Crypto==0.22.3
MarkupSafe==0.23
msgpack-python==0.4.6
Pillow==2.8.1
PocketSphinx==0.8
pyalsa==1.0.29
pyasn1==0.1.7
PyAudio==0.2.8
pycparser==2.13
pycrypto==2.6.1
pycurl==7.19.5.1
pymongo==3.0.2
pyOpenSSL==0.15.1
PyYAML==3.11
pyzmq==14.6.0
six==1.9.0
SphinxBase==0.8
SQLAlchemy==1.0.4
Twisted==15.2.1
uWSGI==2.0.10
virtualenv==13.0.3
wheel==0.24.0
yenc==0.4.0
zope.interface==4.1.2
```

https://github.com/SynoCommunity/spksrc/tree/master/spk/sickrage/src
https://www.synology.com/en-global/releaseNote/DS211j

**Comment by miigotu** [comment]
Is he on 5.2-5592??

That setup is perfect! I wish QNAP was so easy. (cryptography + pyOpenSSL 15.1!!!!)

**Comment by Vodka2014** [comment]
Using same Python Version

**Comment by neoatomic** [comment]
Yep, like i mentioned before Synology is very well supported. Just awesome devices.

So when i see a Syno ticked being opened they have my special attention as its almost always a real bug or an end-user "problem". Installation/compability problems are almost excluded :)

@Vodka2014 Just to be sure check if you have updated to the latest DSM version.
And see my previous replays for some question i asked.

**Comment by Vodka2014** [comment]
Will do thanks a lot both of you :). I will check and test this weekend and post results on Monday.

**Comment by miigotu** [comment]
`almost excluded` unless they kill it by trying too hard =P

LOL, My parents used to call that `noaching`
In a sentence: "Stop noaching the cat"
Or: "Why did my anole die? Because you kept noaching it"

IDK if I'm spelling it right, we are PA Dutch so maybe it comes from that, never could find that word online or any dictionary.

**Comment by neoatomic** [comment]
Well a Synology hasn't root access out of the box, so they indeed need to try hard. :)

You have me completely riddled with `noaching` cant come up with a word even close to it. 
Need to think that over with a few beer's...

**Comment by miigotu** [comment]
Well with the way we talk its more like nochin lol, but idk.

**Comment by Vodka2014** [comment]
So with the 70+ Commits updates and tons of testing this is working like a charm :) the one issue with the SSL Cert in SABNZDB can get ignored since it is not causing any issues it is just a warning like @miigotu stated.

The other error was due to permissions on my folders on my NAS where user required R/W or SickRage could not access them. This was fixed and the errors went away

There are new issues now that it is not grabing shows like Ballers (Even thou I have added scene name to it) and Ray Donovan for some odd reason this was 11 days ago and my retention is set to 3000 so it should of grabbed it.

Thanks again to @miigotu & @neoatomic for the help on this :)

**Comment by Vodka2014** [comment]
@miigotu Like u stated keep it to 1 topic :)

For some odd reason (and i have updated to the latest SickRage) is not grabbing shows. Hannibal S03E08 is out but SickRage will not grab it. 

SEARCHQUEUE-MANUAL-259063 :: Unable to find a download for: [Hannibal - 3x08 - The Great Red Dragon]

**Comment by miigotu** [comment]
did you enable debug and check the log after it fails?

SR has no problems with snatching right now.

**Comment by neoatomic** [comment]
Probably a scene naming issue. Thinks its called "hanibal" & "haniball (2014) & "haniball (2015)" etc.

**Comment by Vodka2014** [comment]
Well it has started to do this now on 3 other shows as well.
MasterChef New Zealand, MasterChef Australia, MythBusters

It never used to do this and it is not Scene Names from what i can see

Site: Hannibal S03E08 HDTV x264-KILLERS
SickRage: Hannibal

Any ideas

**Comment by neoatomic** [comment]
Its hard to say without logs... Just make sure that the names of the show correspondent with those of the torrent/nzb files. If not add a scene exception so they do match.

**Comment by Vodka2014** [comment]
@neoatomic thanks for that. That is what i have been doing on a few shows and it works 100% it was just odd that everything hung. I will keep and eye out on it and if it happens again will try get some logs if it shows me any :) 

Is there a Wiki or Process Guide for users on how to setup SickRage on different platforms at all. As if not i might try write something for Synology and let u know take a look before it goes public. This might stop tons of the issue posts.

**Comment by neoatomic** [comment]
You can submit those scene exception also directly to one of the repository scene exception lists. That will help other users with the same problem.

I did update the Wiki page a little the last days so there is also a section with guides.
https://github.com/SiCKRAGETV/sickrage-issues/wiki

But you are always welcome to submit a guide of other help for the community. :)

**Comment by miigotu** [comment]
@Vodka2014 you can post guides in https://sickrage.tv/forums/forum/help-support/general-support
There is already a sticky there with some guides, but im not sure how up to date it is.

**Comment by Vodka2014** [comment]
Cool will take a look thanks

**Comment by Vodka2014** [comment]
Why is Fifth Gear Downloading S25E04 + E05 when on SickRage it is showing S26E0x

I have noticed this with Mythbusters as well. There is no errors at all in the logs it just looks at the date and then downloads it ?

So is this a bug ?

**Comment by miigotu** [comment]
Nope, its scene numbering working as it should.

**Comment by Vodka2014** [comment]
So that means what SickRage is showing and what is actually downloading are 2 different things ?
But in the end the shows are actually correct. Then why are the numbering wrong.
Sorry i am a bit lost on this :)
