### ISSUE TITLE
[Feature Request] monitor IRC network to download torrent

### ISSUE THREAD

**Issue by frriction** [SiCKRAGETV/sickrage-issues#2009]
Every private tracker announce new torrent on their irc network and it would be great feature for SR if it can monitor and download torrent through irc network.

I have seen on private tracker forum that most of people do not use SR just because it does not grab torrent as soon as it posted, and irc is fastest way to grab one.

I want this feature in SR just because I do not want to setup two different programs to achieve what I want, I have installed autodl-irssi but never setup. It is really really easy to add,remove or modify series in SR than in other programs.

There are two different projects which monitors irc network and grab torrents as soon as it get posted.
autodl-irssi https://github.com/autodl-community/autodl-irssi
pywhat https://github.com/jimrollenhagen/pywhatauto

**Comment by flightlevel** [comment]
I had the same problem, its hard to upload if you don't get in early. I'm not very good with Python, but have hacked together a script that I've been using for about a year for this purpose. It listens to the IRC channel and compares to the coming episodes in Sickrage, If it gets a match, it will get SickRage to search. All up, its only a few seconds delay from IRC announce which is fine for my use.
Script is setup for Freshon, but it wouldn't be hard to change.
https://gist.github.com/flightlevel/1c46f233bf0c80dbf3db

**Comment by neoatomic** [comment]
Interesting suggestion. 
Feel free to create a Pull Request if you are able to compile it.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
