### ISSUE TITLE
Synology + SickRage Grabbing Files Issues

### ISSUE THREAD

**Issue by Vodka2014** [SiCKRAGETV/sickrage-issues#2011]
Hi

I have issues with files getting grabbed. This is a clean install. All the searches do run thou.

BRANCH: (master)
COMMIT: (e2318076201cb9a0b4e6fb0bce7aa6504be524a3)
PYTHON: 2.7.10 (default, Jun 3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]
Synology DSM 5.0-4528 Update 2

https://gist.github.com/Vodka2014/7e76725ecf6992e69dff

Thanks

**Comment by neoatomic** [comment]
@Vodka2014 As your 2 issues are related. Please add the info to https://github.com/SiCKRAGETV/sickrage-issues/issues/2008 so we have all the information in one place.
