### ISSUE TITLE
[APP SUBMITTED]: [Error 5] Access is denied: u'C:\\Downloads\\Mr.Robot.S01E03.720p.HDTV.x264-IMMERSE\\mr.robot.s01e03.720p.hdtv.x264-immerse.sfv'

### ISSUE THREAD

**Issue by maZuFC** [SiCKRAGETV/sickrage-issues#2014]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@e2318076201cb9a0b4e6fb0bce7aa6504be524a3
Link to Log: https://gist.github.com/80c272b3ecdd0ddf8acf
### ERROR
```
POSTPROCESSER :: Unable to move file C:\Downloads\Mr.Robot.S01E03.720p.HDTV.x264-IMMERSE\mr.robot.s01e03.720p.hdtv.x264-immerse.sfv to T:\Mr. Robot\Season 01\Mr.Robot.S01E03.HDTV-IMMERSE.sfv: error 5 : Access is denied
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Looks like the permissions on that file are not allowing SR to move it. We have no control over permissions issue. Check your configuration (and that file)
