### ISSUE TITLE
[APP SUBMITTED]: global name 'url' is not defined

### ISSUE THREAD

**Issue by oceloti** [SiCKRAGETV/sickrage-issues#2015]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-55-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@a4f329fbc394e8939977bf9c43aa540f948fec75
No Log available with ERRORS: 
### ERROR
```
FINDPROPERS :: [IPTorrents] :: Error while searching IPTorrents, skipping: global name 'url' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by oceloti** [comment]
Within the Log itself, i noticed as below. This seems to be new for me as it was functional before updating 4a47a5cf7eff76f0d99a9c0f3b574027d1f56dd8...a4f329fbc394e8939977bf9c43aa540f948fec75

AA
AANameError: global name 'url' is not defined
AA    logger.log("Using proxy for url: " + url, logger.DEBUG)
AA  File "/opt/sickrage/sickbeard/helpers.py", line 1319, in _setUpSession
AA    session = _setUpSession(session, headers)
AA  File "/opt/sickrage/sickbeard/helpers.py", line 1378, in getURL
AA    parsedJSON = helpers.getURL(url, session=xem_session, json=True)
AA  File "/opt/sickrage/sickbeard/scene_exceptions.py", line 310, in _xem_exceptions_fetcher
AA    _xem_exceptions_fetcher()
AA  File "/opt/sickrage/sickbeard/scene_exceptions.py", line 211, in retrieve_exceptions
AA    sickbeard.scene_exceptions.retrieve_exceptions()
AA  File "/opt/sickrage/sickbeard/name_cache.py", line 87, in buildNameCache
AA    sickbeard.name_cache.buildNameCache(show)
AA  File "/opt/sickrage/sickbeard/search.py", line 436, in searchProviders
AA    searchResult = search.searchProviders(self.show, self.segment, False)
AA  File "/opt/sickrage/sickbeard/search_queue.py", line 221, in run

AA
AANameError: global name 'url' is not defined
AA    logger.log("Using proxy for url: " + url, logger.DEBUG)
AA  File "/opt/sickrage/sickbeard/helpers.py", line 1319, in _setUpSession
AA    session = _setUpSession(session, headers)
AA  File "/opt/sickrage/sickbeard/helpers.py", line 1378, in getURL
AA    session=self.session, json=json, proxyGlypeProxySSLwarning=self.proxyGlypeProxySSLwarning)
AA  File "/opt/sickrage/sickbeard/providers/generic.py", line 148, in getURL
AA    data = self.getURL(searchURL)
AA  File "/opt/sickrage/sickbeard/providers/iptorrents.py", line 353, in _doSearch
AA    for item in self._doSearch(searchString[0]):
AA  File "/opt/sickrage/sickbeard/providers/iptorrents.py", line 444, in findPropers
AA    curPropers = curProvider.findPropers(search_date)
AA  File "/opt/sickrage/sickbeard/properFinder.py", line 82, in _getProperList

**Comment by neoatomic** [comment]
@oceloti Dan you post the log itself so we can see whats happening.?

**Comment by nrk666** [comment]
Can confirm this error, and yes, I am using a proxy. 

BRANCH: (master) / COMMIT: (6da257136e24d6e08344c4fd2e2c662b2c874972)

Python Version:	2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]

Logfile : https://gist.github.com/nrk666/993683545a22177e7d48

I edited the log a little bit to remove some possibly identifying info, but nothing related to the error (mostly backlog searches and daily searches with a bunch of show names...) .

**Comment by nrk666** [comment]
Disabling the proxy made the error go away, and it found the show it was looking for, so this looks to only affect me if I am using a proxy.

**Comment by nrk666** [comment]
thanks bro

**Comment by miigotu** [comment]
np, this was a big update, so there are bound to be some hotfixes needed =P.

**Comment by oceloti** [comment]
BRANCH: (master) / COMMIT: (1153ba18112827eb0fa8c71f111e076aca186416) 
Hi,

I updated to include the above commit and now the error has manifested. I too am using a global proxy.

Thank you for this @miigotu 

2015-07-10 09:57:05 FINDPROPERS :: [IPTorrents] :: Error while searching IPTorrents, skipping: global name 'urllib2' is not defined
2015-07-10 09:57:01 FINDPROPERS :: [TorrentLeech] :: Error while searching TorrentLeech, skipping: global name 'urllib2' is not defined
2015-07-10 09:28:08 Thread-499 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 269, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 2184, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/opt/sickrage/sickbeard/processTV.py", line 251, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/opt/sickrage/sickbeard/processTV.py", line 491, in process_media
    result.result = processor.process()
  File "/opt/sickrage/sickbeard/postProcessor.py", line 1080, in process
    ep_obj.createMetaFiles()
  File "/opt/sickrage/sickbeard/tv.py", line 1998, in createMetaFiles
    self.createThumbnail()
  File "/opt/sickrage/sickbeard/tv.py", line 2017, in createThumbnail
    result = cur_provider.create_episode_thumb(self) or result
  File "/opt/sickrage/sickbeard/metadata/generic.py", line 332, in create_episode_thumb
    return self.save_thumbnail(ep_obj)
  File "/opt/sickrage/sickbeard/metadata/generic.py", line 506, in save_thumbnail
    thumb_data = metadata_helpers.getShowImage(thumb_url)
  File "/opt/sickrage/sickbeard/metadata/helpers.py", line 38, in getShowImage
    image_data = helpers.getURL(tempURL, session=meta_session)
  File "/opt/sickrage/sickbeard/helpers.py", line 1378, in getURL
    session = _setUpSession(session, headers)
  File "/opt/sickrage/sickbeard/helpers.py", line 1320, in _setUpSession
    scheme, address = urllib2.splittype(sickbeard.PROXY_SETTING)
NameError: global name 'urllib2' is not defined

2015-07-10 09:27:53 POSTPROCESSER :: Exception generated in thread POSTPROCESSER: global name 'urllib2' is not defined
