### ISSUE TITLE
[APP SUBMITTED]: global name 'release_name' is not defined

### ISSUE THREAD

**Issue by srholm** [SiCKRAGETV/sickrage-issues#2016]
### INFO
Python Version: **2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2008ServerR2-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@a4f329fbc394e8939977bf9c43aa540f948fec75
No Log available with ERRORS: 
### ERROR
```
FINDSUBTITLES :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\tv.py", line 1530, in downloadSubtitles
    new_path = path.replace(ek.ek(os.path.splitext, release_name)[0],
NameError: global name 'release_name' is not defined

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@srholm Can you post a log so we can see whats happening.?

@miigotu Sub error.

**Comment by srholm** [comment]
I since updated SickRage and lost the log. Sorry :-/
