### ISSUE TITLE
[APP SUBMITTED]: POSTPROCESSER :: Failed to detect KODI version for '192.168.241.99:80', check configuration and try again.

### ISSUE THREAD

**Issue by BruTTus** [SiCKRAGETV/sickrage-issues#2018]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 17:38:42) [GCC 4.6.4]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@a4f329fbc394e8939977bf9c43aa540f948fec75
Link to Log: https://gist.github.com/3ed108447c08105262e8
### ERROR
```
POSTPROCESSER :: Failed to detect KODI version for '192.168.241.99:80', check configuration and try again.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
This is not an error. It is a configuration problem.
One of the following:
1. SR was not connected to the same network as Kodi
2. Kodi was not on
3. Kodi was not connected to the network
4. Kodi was not configured to accept connections
5. SR has the wrong url/port/user/pass settings.

**Comment by BruTTus** [comment]
Sorry this is not the error that I want to inform.

**Comment by miigotu** [comment]
=P I am going to change that error into a warning later. It sets an error is "Always On" is set and kodi can't be reached.
