### ISSUE TITLE
[APP SUBMITTED]: global name 'release_name' is not defined

### ISSUE THREAD

**Issue by BruTTus** [SiCKRAGETV/sickrage-issues#2019]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 17:38:42) [GCC 4.6.4]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@a4f329fbc394e8939977bf9c43aa540f948fec75
Link to Log: https://gist.github.com/885bc491ce0953324e3f
### ERROR
```
FINDSUBTITLES :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/tv.py", line 1530, in downloadSubtitles
    new_path = path.replace(ek.ek(os.path.splitext, release_name)[0],
NameError: global name 'release_name' is not defined

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
This was fixed. https://github.com/SiCKRAGETV/sickrage-issues/issues/2016
Let SickRage check for updates.
