### ISSUE TITLE
[APP SUBMITTED]: global name 'newpath' is not defined

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#2021]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:34:55) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-22-generic-i686-with-Ubuntu-15.04-vivid**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@99616dba813fee24ff8d0c17f0d13deaf17c4b1d
Link to Log: https://gist.github.com/6a78aec4e0eadebcc019
### ERROR
```
POSTPROCESSER :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "/home/supergonkas/SickRage/sickbeard/tv.py", line 1532, in downloadSubtitles
    if ek.ek(os.path.exists, path) and not ek.ek(os.path.exists, newpath):
NameError: global name 'newpath' is not defined

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by devenashani** [comment]
### INFO
Python Version: **2.7.3 (default, Jul 13 2012, 04:03:47) [GCC 4.4.5]**
Operating System: **Linux-2.6.31.8.nv+v2-armv5tel-with-debian-6.0.3**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@ba8406163ad4ed0b6578cd6e76fdde3e69c28cf8
Link to Log: https://gist.github.com/6edfdd6c12370f724d08
### ERROR
```
POSTPROCESSER :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "/root/sickrage/sickbeard/tv.py", line 1532, in downloadSubtitles
    if ek.ek(os.path.exists, path) and not ek.ek(os.path.exists, newpath):
NameError: global name 'newpath' is not defined

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by devenashani** [comment]
### INFO
Python Version: **2.7.3 (default, Jul 13 2012, 04:03:47) [GCC 4.4.5]**
Operating System: **Linux-2.6.31.8.nv+v2-armv5tel-with-debian-6.0.3**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@ba8406163ad4ed0b6578cd6e76fdde3e69c28cf8
Link to Log: https://gist.github.com/7bada512d7e8f1287448
### ERROR
```
Thread-62 :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "/root/sickrage/sickbeard/tv.py", line 1532, in downloadSubtitles
    if ek.ek(os.path.exists, path) and not ek.ek(os.path.exists, newpath):
NameError: global name 'newpath' is not defined

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by devenashani** [comment]
### INFO
Python Version: **2.7.3 (default, Jul 13 2012, 04:03:47) [GCC 4.4.5]**
Operating System: **Linux-2.6.31.8.nv+v2-armv5tel-with-debian-6.0.3**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@ba8406163ad4ed0b6578cd6e76fdde3e69c28cf8
Link to Log: https://gist.github.com/87d2b697db372c4fada8
### ERROR
```
Thread-62 :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "/root/sickrage/sickbeard/tv.py", line 1532, in downloadSubtitles
    if ek.ek(os.path.exists, path) and not ek.ek(os.path.exists, newpath):
NameError: global name 'newpath' is not defined

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by devenashani** [comment]
### INFO
Python Version: **2.7.3 (default, Jul 13 2012, 04:03:47) [GCC 4.4.5]**
Operating System: **Linux-2.6.31.8.nv+v2-armv5tel-with-debian-6.0.3**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@ba8406163ad4ed0b6578cd6e76fdde3e69c28cf8
Link to Log: https://gist.github.com/a07afdd42d1a47b8fdc4
### ERROR
```
Thread-62 :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "/root/sickrage/sickbeard/tv.py", line 1532, in downloadSubtitles
    if ek.ek(os.path.exists, path) and not ek.ek(os.path.exists, newpath):
NameError: global name 'newpath' is not defined

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by frankij** [comment]
I have the same problem with subtitles, its not downloading them anymore:

2015-07-10 10:09:48 Thread-30 :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "/apps/SickRage/sickbeard/tv.py", line 1532, in downloadSubtitles
    if ek.ek(os.path.exists, path) and not ek.ek(os.path.exists, newpath):
NameError: global name 'newpath' is not defined

**Comment by pixatintes** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-55-generic-i686-athlon-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@e5feacc73533ca3a9c38546aa17549c047e26ac2
Link to Log: https://gist.github.com/70a7e4933d4d88d9c675
### ERROR
```
FINDSUBTITLES :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "/home/jordi/.sickbeard/sickbeard/tv.py", line 1532, in downloadSubtitles
    if ek.ek(os.path.exists, path) and not ek.ek(os.path.exists, newpath):
NameError: global name 'newpath' is not defined

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
We did a large update yesterday for the subtitle section. So not surprising that there are some small bugs. Know we are working on this issue. 

@miigotu
