### ISSUE TITLE
[APP SUBMITTED]: mismatched tag: line 6, column 2

### ISSUE THREAD

**Issue by johndoe86x** [SiCKRAGETV/sickrage-issues#2022]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.16.0-0.bpo.4-amd64-x86_64-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@ba8406163ad4ed0b6578cd6e76fdde3e69c28cf8
Link to Log: https://gist.github.com/6ce9017f8b33f8499513
### ERROR
```
Thread-61 :: PLEX: Error while trying to contact Plex Media Server: mismatched tag: line 6, column 2
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by johndoe86x** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.16.0-0.bpo.4-amd64-x86_64-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@ba8406163ad4ed0b6578cd6e76fdde3e69c28cf8
Link to Log: https://gist.github.com/28e104526753933c1776
### ERROR
```
Thread-24 :: PLEX: Error while trying to contact Plex Media Server: mismatched tag: line 6, column 2
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@johndoe86x Seems a torcache issue. Are you using an proxy.? If so try to disable and test again.

**Comment by miigotu** [comment]
Check your plex settings:

`Unauthorized`

**Comment by johndoe86x** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.16.0-0.bpo.4-amd64-x86_64-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@e21b2c296897986d68356f91ac98dbf3eeae55a3
Link to Log: https://gist.github.com/9c319b77a580cea58bee
### ERROR
```
Thread-33 :: PLEX: Error while trying to contact Plex Media Server: mismatched tag: line 6, column 2
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
