### ISSUE TITLE
[APP SUBMITTED]: [Error 32] The process cannot access the file because it is being used by another process: u'D:\\TV\\TV Shows\\Extant\\Season 02\\extant.202.hdtv-lol.mp4'

### ISSUE THREAD

**Issue by krash1220** [SiCKRAGETV/sickrage-issues#2025]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@ba8406163ad4ed0b6578cd6e76fdde3e69c28cf8
Link to Log: https://gist.github.com/7b4589a72caa8ac5f160
### ERROR
```
FINDSUBTITLES :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "D:\TV\SickRage\sickbeard\tv.py", line 1488, in downloadSubtitles
    ek.ek(os.unlink, vname)
  File "D:\TV\SickRage\sickbeard\encodingKludge.py", line 62, in ek
    result = func(*args, **kwargs)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'D:\\TV\\TV Shows\\Extant\\Season 02\\extant.202.hdtv-lol.mp4'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Guess you were manually searching for subtitles while the subtitle thread was downloading that same episode.
