### ISSUE TITLE
ImportError: cannot import name AbstractFileLock

### ISSUE THREAD

**Issue by forerunnert** [SiCKRAGETV/sickrage-issues#2027]
Branch: 
Master

Commit hash: 
ba8406163ad4ed0b6578cd6e76fdde3e69c28cf8

Your operating system and python version: 
Debian 8.1, python 2.7.9

What you did: 
I updated SickRage to latest commit (see hash above)

What happened:
SickRage doesn't start anymore.
Upon investigation I find this in the /var/log/syslog:

 Traceback (most recent call last):
Jul 10 06:30:09 computer sickbeard[11105]: File "SickBeard.py", line 33, in <module>
Jul 10 06:30:09 computer sickbeard[11105]: import lib.shutil_custom
Jul 10 06:30:09 computer sickbeard[11105]: ImportError: No module named lib.shutil_custom
Jul 10 06:33:18 computer sickbeard[11616]: Traceback (most recent call last):
Jul 10 06:33:18 computer sickbeard[11616]: File "SickBeard.py", line 90, in <module>
Jul 10 06:33:18 computer sickbeard[11616]: import sickbeard
Jul 10 06:33:18 computer sickbeard[11616]: File "/home/user/.sickbeard/sickbeard/__init__.py", line 37, in <module>
Jul 10 06:33:18 computer sickbeard[11616]: from sickbeard import providers, metadata, config, webserveInit
Jul 10 06:33:18 computer sickbeard[11616]: File "home/user/.sickbeard/sickbeard/providers/__init__.py", line 54, in <module>
Jul 10 06:33:18 computer sickbeard[11616]: import generic
Jul 10 06:33:18 computer sickbeard[11616]: File "home/user/.sickbeard/sickbeard/providers/generic.py", line 32, in <module>
Jul 10 06:33:18 computer sickbeard[11616]: from sickbeard import helpers, classes, logger, db
Jul 10 06:33:18 computer sickbeard[11616]: File "home/user/.sickbeard/sickbeard/helpers.py", line 45, in <module>
Jul 10 06:33:18 computer sickbeard[11616]: import subliminal
Jul 10 06:33:18 computer sickbeard[11616]: File "home/user/.sickbeard/lib/subliminal/__init__.py", line 10, in <module>
Jul 10 06:33:18 computer sickbeard[11616]: from .cache import MutexLock, region as cache_region
Jul 10 06:33:18 computer sickbeard[11616]: File "home/user/.sickbeard/lib/subliminal/cache.py", line 5, in <module>
Jul 10 06:33:18 computer sickbeard[11616]: from dogpile.cache.backends.file import AbstractFileLock  # @UnresolvedImport
Jul 10 06:33:18 computer sickbeard[11616]: ImportError: cannot import name AbstractFileLock
root@computer home/user/.sickbeard# ImportError: cannot import name AbstractFileLock ImportError: cannot import name AbstractFileLock

What you expected:
I expected a successful update.  I also checked out a new copy of SickRage, ran it with the same result so I don't think this issue is related to the failed update.

**Comment by miigotu** [comment]
Dont know what you did but that is not a problem with SR, it is your system.

this has been in SR for months:
`ImportError: No module named lib.shutil_custom`

Is your lib folder missing?

**Comment by miigotu** [comment]
https://github.com/SiCKRAGETV/SickRage/blob/master/lib/shutil_custom/__init__.py
https://github.com/SiCKRAGETV/SickRage/blob/master/lib/dogpile/cache/backends/file.py#L263

**Comment by miigotu** [comment]
Maybe you broke/changed $PYTHON_PATH ?

**Comment by forerunnert** [comment]
I also don't know what I did other than the SR update :-)

Funny thing is: there is a  file  ../lib/dogpile/cache/backends/file.py with a class AbstractFileLock in it. In fact other dogpile imports from cache.py seem to work ok...

I'll have another look  at the $PYTHON_PATH.

**Comment by miigotu** [comment]
Wherever you cloned the new sickrage source, cd into it and try starting it with `./SickBeard.py`

**Comment by forerunnert** [comment]
On a newly cloned sickrage source the error is the same.

If I change in ../lib/subliminal/cache.py
   from dogpile.cache.backends.file import AbstractFileLock  # @UnresolvedImport
into
   from lib.dogpile.cache.backends.file import AbstractFileLock  # @UnresolvedImport

then sickrage starts, no errors anymore (even with the other imports left at "dogpile..."

**Comment by miigotu** [comment]
What if you undo that and change this line:
sickbeard/subtitles.py:
subliminal.cache_region.configure('dogpile.cache.memory')
to
subliminal.cache_region.configure('lib.dogpile.cache.memory')

**Comment by miigotu** [comment]
(thats the only place we use dogpile -.-)

**Comment by forerunnert** [comment]
If I change the sickbeard/subtitles.py line and revert the /lib/subliminal/cache.py changes then I get the same import error 'ImportError: cannot import name AbstractFileLock'.

Additionally I replaced my /etc/init.d startup script and the /etc/default/sickrage file with the ones from the repository (since git doesn't update those), but the result is the same:
lib.dogpile.cache.backends.file import AbstractFileLock ==> everything ok
dogpile.cache.backends.file import AbstractFileLock ==>  'ImportError: cannot import name AbstractFileLock'

**Comment by miigotu** [comment]
strange.

**Comment by forerunnert** [comment]
strange indeed...

I'll have a closer look this weekend to see if I can figure this one out.
Thanks for the help!
