### ISSUE TITLE
[APP SUBMITTED]: global name 'release_name' is not defined

### ISSUE THREAD

**Issue by srholm** [SiCKRAGETV/sickrage-issues#2028]
### INFO
Python Version: **2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2008ServerR2-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@a4f329fbc394e8939977bf9c43aa540f948fec75
Link to Log: https://gist.github.com/cfd2d45a9d0886cd447a
### ERROR
```
Thread-122 :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\tv.py", line 1530, in downloadSubtitles
    new_path = path.replace(ek.ek(os.path.splitext, release_name)[0],
NameError: global name 'release_name' is not defined

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Its already fixed ^^
