### ISSUE TITLE
Unable to manually post-process and rename episodes

### ISSUE THREAD

**Issue by rEes9P** [SiCKRAGETV/sickrage-issues#2031]
Branch: master
Commit hash: 50e1c30a3f53fc623e70483f758c1a9f96ea38d1
OS: Mac OS X 10.10.4
Python: 2.7.6 (default, Sep 9 2014, 15:04:36) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]

I tried to manually rename some episodes of Batman. The Re-scan and Preview Rename options work fine but the files don't get renamed and I get the error messages I've linked to instead. Interestingly, I am able to rename some other shows just fine and the error seems to be confined to this particular show. I've never encountered this error before and have been able to successfully rename shows through the Re-scan > Preview Rename route. I'm not sure if this is related but just before this error occurred I had had a problem updating SickRage. The update went through once I checked the Git reset option in the GitHub settings.

I'm not very familiar with GitHub or Python and so please excuse me if there is any information missing here.

Error info
https://gist.github.com/8e88dcd96b674b499ed6.git

Debug log
https://gist.github.com/a7b86a2a1ad82fc6e64f.git

**Comment by rEes9P** [comment]
Thanks for the prompt response. I tried to update to the newer version that fixes the original issue but the update didn't go through successfully. SickRage wouldn't start after the update and so I tried to manually start it but couldn't. In Terminal I get the following error. I'd greatly appreciate help in solving this and being able to run SickRage again. Thanks.

https://gist.github.com/99bf07ed96d8e4fcfcff.git

**Comment by miigotu** [comment]
cd into the top SickRage dir, git pull

**Comment by rEes9P** [comment]
Thanks a ton. Works like a charm. One question though, I am now able to manually rename the show as I could others before the problem came up but now the subtitle files (.sub and .idx) are getting moved automatically. This is so even though I don't have the Move Associated Files option enabled in my settings. I was wondering why this is happening.

As an aside, it would be nice to have the option of moving only specified associated files over in case people want to save .sub and .idx files if they exist, for example, and don't want others moved over too.

**Comment by miigotu** [comment]
The move associated files option is for post processing downloads, not renaming files. Your download/postprocessing folder should not be inside your tv show library.
