### ISSUE TITLE
[APP SUBMITTED]: Thread-385 :: Retrieved version from http://github.com/SiCKRAGETV/SickRage/tarball/master is corrupt, can't update

### ISSUE THREAD

**Issue by Trapizomba** [SiCKRAGETV/sickrage-issues#2038]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 06:12:10) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@4a47a5cf7eff76f0d99a9c0f3b574027d1f56dd8
Link to Log: https://gist.github.com/17982c41060fed736014
### ERROR
```
Thread-385 :: Retrieved version from http://github.com/SiCKRAGETV/SickRage/tarball/master is corrupt, can't update
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Github had some issues earlier today. See if you can update now.
