### ISSUE TITLE
[APP SUBMITTED]: ('http protocol error', 0, 'got a bad status line', None)

### ISSUE THREAD

**Issue by Trapizomba** [SiCKRAGETV/sickrage-issues#2039]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 06:12:10) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@4a47a5cf7eff76f0d99a9c0f3b574027d1f56dd8
Link to Log: https://gist.github.com/632106f205d8fd964410
### ERROR
```
Thread-384 :: Error while trying to update: http protocol error : error 0 : got a bad status line
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Github had some issues/was down for a short moment.
Try again as see if you can update.
