### ISSUE TITLE
[APP SUBMITTED]: 'TVShow' object has no attribute 'title'

### ISSUE THREAD

**Issue by dsoms** [SiCKRAGETV/sickrage-issues#2041]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-3.18.13-1-osmc-armv7l-with-debian-8.1**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@be8b202eea7ad8063dc7f35e282654c81c5bf048
Link to Log: https://gist.github.com/7dd4f350b3a7cc6f05cd
### ERROR
```
FINDSUBTITLES :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "/home/osmc/.sickrage/sickbeard/tv.py", line 1506, in downloadSubtitles
    subs_new_path = ek.ek(os.path.join, sickbeard.SUBTITLES_DIR, self.show.title)
AttributeError: 'TVShow' object has no attribute 'title'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@miigotu Sub error.
