### ISSUE TITLE
[APP SUBMITTED]: column network_name is not unique

### ISSUE THREAD

**Issue by Molleke** [SiCKRAGETV/sickrage-issues#2042]
### INFO
Python Version: **2.7.6 (default, Nov 10 2013, 19:24:24) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@1cca40fb6df14ee7d2bc6d4fa3dcf5800fbf52b2
Link to Log: https://gist.github.com/fd551c64117484a093bf
### ERROR
```
SHOWUPDATER :: Fatal error executing query: column network_name is not unique
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Should already be fixed. Do an update.
