### ISSUE TITLE
remove special charters from search such as ",'

### ISSUE THREAD

**Issue by sbelongie** [SiCKRAGETV/sickrage-issues#2043]
when searching for an episode that has a 's in the name nothing is found.  This seems to be only an issue on some shows. Is it possible to search without the extra 's if nothing is found

**Comment by miigotu** [comment]
which provider? manual search? More info/proof/debug logs pls.

**Comment by neoatomic** [comment]
@sbelongie You can add a scene exception, but if this is a bug we like to know. 
Please follow the guideline for posting an issue. and give as much info as you can. : 
https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket

**Comment by sbelongie** [comment]
You are correct it looks like an exception can be added. I will submit for scene exception.

**Comment by fernandog** [comment]
@sbelongie add scene exception in SR (show page - edit)
