### ISSUE TITLE
[APP SUBMITTED]: list modified during sort

### ISSUE THREAD

**Issue by mbxplex** [SiCKRAGETV/sickrage-issues#2045]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@5926e2a25124c7d22f98895725464c67577c4ae7
Link to Log: https://gist.github.com/de04b3a40772ddf98cd2
### ERROR
```
SHOWQUEUE :: Exception generated in thread SHOWQUEUE: list modified during sort
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by mbxplex** [comment]
Not sure if this was related to #2012 but after a PC restart and update I received this error. 

@miigotu I know you were working on 2012 last night, do you think this error has anything to do with this?

**Comment by mbxplex** [comment]
This was in the log ... not sure if it will help.

AAValueError: list modified during sort
AA    self.queue.sort(cmp=sorter)
AA  File "C:\SickRage\sickbeard\generic_queue.py", line 86, in run
AA    self.action.run(self.force)
AA  File "C:\SickRage\sickbeard\scheduler.py", line 97, in run
AATraceback (most recent call last):

**Comment by fernandog** [comment]
Did you recently deleted any shows?

**Comment by mbxplex** [comment]
No, nothing has been deleted. The only thing I've done recently over the last 48 hours is add TV episodes manually to the 2 hard drives I own to stay up to date while the developers tended to #2012

**Comment by miigotu** [comment]
@fernandog The commit that fixed this a long time ago was lost when the switch from cherryPy to tornado.

Fixing!

**Comment by miigotu** [comment]
This commit was lost when switching to tornado: https://github.com/SiCKRAGETV/SickRage/commit/2c0f3a3dc3c15235b0987bde2946d13387d1bc10
My commit:
https://github.com/SiCKRAGETV/SickRage/commit/7f1761fcd235caafe8b257357579d2f558e4340c

Only found that because I didn't understand why there was a lock defined but it wasn't used lol. Blame ftw.
