### ISSUE TITLE
[APP SUBMITTED]: POSTPROCESSER :: There was an error trying to retrieve the image, aborting

### ISSUE THREAD

**Issue by brunis** [SiCKRAGETV/sickrage-issues#2046]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.18.4-x86_64-with-debian-8.1**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@92bf581ba8a7d4f2f912db795ce571b6ad38c3c2
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: There was an error trying to retrieve the image, aborting
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Simple timeout. should be a one time error.

**Comment by brunis** [comment]
i have 10's of thousands of these in my log..   i clear the log often so they don't go into the 100's of thousands ..  if you don't want to fix it can you at least add more data to the log entries so i can figure out locally what it's trying to do and which service it's trying to reach?

**Comment by neoatomic** [comment]
So its a repeating error.? Than we will need a full log with debug=1 enabled to see what SickRage is doing. And some more information on your setup/device.

**Comment by brunis** [comment]
i'd say a hundred thousand entries classifies as repeating..

thx, i'll run as debug from now on.

**Comment by miigotu** [comment]
Maybe file/folder permissions? makes the most sense.

**Comment by brunis** [comment]
I think this has been caused by permission issues as mentioned. It was also preventing updates from being installed or even checked. SickRage stalled forever when trying to shut it down and i had to kill it.. which then killed half the shows in my database. I'm being redirected to the front page in SickRage when i try to show them and these errors show up in the db:
2015-07-11 17:06:32 Thread-73 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 269, in async_call
    result = function(**kwargs)
  File "/opt/sickbeard/sickbeard/webserve.py", line 1194, in displayShow
    [showObj.indexerid]
  File "/opt/sickbeard/sickbeard/db.py", line 191, in select
    sqlResults = self.action(query, args, fetchall=True)
  File "/opt/sickbeard/sickbeard/db.py", line 168, in action
    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/sickbeard/sickbeard/db.py", line 84, in execute
    return self._execute(query, args).fetchall()
  File "/opt/sickbeard/sickbeard/db.py", line 77, in _execute
    return self.connection.cursor().execute(query, args)
DatabaseError: database disk image is malformed

Is there a way i can just clean my db or remove the corrupted shows somehow? ..i'd prefer not to have to wipe my install, i have a lot of custom torrent providers set up.

**Comment by fernandog** [comment]
@brunis 
https://github.com/SiCKRAGETV/sickrage-issues/issues/549#issuecomment-72844385

**Comment by brunis** [comment]
Thanks! Worked like a charm!

**Comment by fernandog** [comment]
@brunis this happens when you try to copy database (backup?) while SR is trying to update it
