### ISSUE TITLE
[APP SUBMITTED]: Thread-67 :: Unable to contact github, can't check for update

### ISSUE THREAD

**Issue by scherlund** [SiCKRAGETV/sickrage-issues#2047]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@a4f329fbc394e8939977bf9c43aa540f948fec75
Link to Log: https://gist.github.com/2c64492011ae75b50603
### ERROR
```
Thread-67 :: Unable to contact github, can't check for update
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
git config --replace-all remote.pjnr1997.url https://github.com/SiCKRAGETV/SickRage.git
