### ISSUE TITLE
[APP SUBMITTED]: global name 'release_name' is not defined

### ISSUE THREAD

**Issue by Basjuhhh** [SiCKRAGETV/sickrage-issues#2048]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@a4f329fbc394e8939977bf9c43aa540f948fec75
No Log available with ERRORS: 
### ERROR
```
FINDSUBTITLES :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/tv.py", line 1530, in downloadSubtitles
    new_path = path.replace(ek.ek(os.path.splitext, release_name)[0],
NameError: global name 'release_name' is not defined

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@Basjuhhh This is already fixed. https://github.com/SiCKRAGETV/SickRage/commit/c29493e5b4d6e60d44820056770385957e7109ae
Do an update.
