### ISSUE TITLE
[APP SUBMITTED]: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by HardbitCoded** [SiCKRAGETV/sickrage-issues#2049]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 23:30:12) [GCC 4.8.2]**
Operating System: **Linux-3.4.61+-armv7l-with-Linaro-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@287a0ebc6019586936e5cce377eaa9fbf7bb7845
Link to Log: https://gist.github.com/8c8040b0911fa59c2cbc
### ERROR
```
Thread-32 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/rui/SickRage/sickbeard/webserve.py", line 269, in async_call
    result = function(**kwargs)
  File "/home/rui/SickRage/sickbeard/webserve.py", line 4860, in index
    return t.respond()
  File "/home/rui/SickRage/cache/cheetah/_home_rui_SickRage_gui_slick_interfaces_default_config_subtitles_tmpl.py", line 288, in respond
    for curService in VFN(VFFSL(SL,"sickbeard.subtitles",True),"sortedServiceList",False)(): # generated from line 144, col 25
  File "/home/rui/SickRage/sickbeard/subtitles.py", line 58, in sortedServiceList
    'url': provider_urls[curService] if curService in provider_urls else lmgtfy % curService,
TypeError: not all arguments converted during string formatting

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
The error posted is different from the one in the log. Can you post the log that has this submitted error.? And can you recall the action that caused this.?

Also i see an SSL error for Rarbg in your log so check https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors .
