### ISSUE TITLE
Daily searcher doesn't find episode; manual search does

### ISSUE THREAD

**Issue by andyj682** [SiCKRAGETV/sickrage-issues#2051]
Is there any reason why the daily search process wouldn't find an episode (which aired 3 days ago), but then manually searching for the episode about 30 seconds after the daily search completes WOULD find it? This seems to be happening consistently for one particular show--never gets snatched until I manually search for the episode. It happens to be a show that doesn't seem to show up until several days after the air date--would that make a difference with what daily search looks for vs. backlog? If it sounds like something the daily searcher should be catching, I will post a log if/when it happens next week.

**Comment by miigotu** [comment]
Daily search only checks for stuff in the last 24 hours. Backlog finds stuff from before that.

**Comment by andyj682** [comment]
Didn't there used to be an option to customize the cutoff for backlog vs. daily or am I making that up?

**Comment by miigotu** [comment]
Nope, only how often the dailysearcher is run, or how often the backlog is run.

**Comment by fernandog** [comment]
There is the "backlog search days" setting but I never quite understood why limit backlog. Its hidden in config

**Comment by andyj682** [comment]
@miigotu @fernandog That's what I"m talking about--used to control how far back daily search goes (I think), but it's not even in the config file anymore. Anyway, that's kind of a bummer that I need to change backlog to run a lot more often to catch episodes that just happen to be a day or so late--seems like a waste of a lot of API hits on providers. Are we sure that's really the expected behavior?

**Comment by fernandog** [comment]
BSD Default is 7. So it theory (not sure) SR will always search episodes with max airdate of 7 days ago.

I set my backlog searcj frequency to the min value (740 I think)

**Comment by miigotu** [comment]
Backlog runs every 12 hours and 20 minutes (@fernandog why a random 740 instead of 720?)

**Comment by andyj682** [comment]
@fernandog This was kind of my original question, though. If daily search is supposed to go back 7 days, it should be finding these episodes I'm asking about, in which case maybe there's something weird going on. Was trying to clarify what that backlog cutoff was since it's not longer a user setting.

**Comment by miigotu** [comment]
backlog_days is not used anywhere.

```bash
miigotu@PC:~/Projects/SickRage $ find . -name '*.py' -exec grep 'backlog_days' {} +
./sickbeard/__init__.py:        BACKLOG_DAYS = check_setting_int(CFG, 'General', 'backlog_days', 7)
./sickbeard/__init__.py:    new_config['General']['backlog_days'] = int(BACKLOG_DAYS)
```

**Comment by miigotu** [comment]
EDIT: My bad case sensitive grep -.-

**Comment by miigotu** [comment]
```python
        if not which_shows and not curDate - self._lastBacklog >= self.cycleTime:
            logger.log(u"Running limited backlog on missed episodes " + str(sickbeard.BACKLOG_DAYS) + " day(s) and older only")
            fromDate = datetime.date.today() - datetime.timedelta(days=sickbeard.BACKLOG_DAYS)
```

This means that the normal backlog will search for everything older than 12 hours, but a forced backlog only searches for things older than 7 days

**Comment by miigotu** [comment]
@fernandog I found the 'paused show still downloading episodes' bug.

searchBacklog.py#L149 doesnt check for show.paused

**Comment by miigotu** [comment]
@andyj682 I'm afraid this is just the way it works. Daily checks every 40 minutes (by default) for episodes which aired in the last day, after that backlog checks every 12 hours (by default) for the episode.

**Comment by miigotu** [comment]
@andyj682 Is the default episode status for that show set to "Wanted" ?

https://github.com/SiCKRAGETV/sickrage-issues/issues/2056#issuecomment-120579646

**Comment by andyj682** [comment]
@miigotu Yeah, good to know. I had backlog set to run once a week, figuring it was only just needed for checking stuff like higher quality releases, but I'll set it to run once a day or so now. Stupid question: Is the breakdown of what time frame daily search covers vs. backlog written up anywhere? I didn't see it on the wiki but maybe I missed it. Would be useful for others to know, I bet. Could even just note it somewhere on the search options page, maybe?

**Comment by miigotu** [comment]
Daily is only for shows which aired within the last 24 hours (and sets the episodes airing the next day to default episode status)

Backlog is for everything else, after daily does not find it.

**Comment by fernandog** [comment]
@miigotu maybe related to an email I send you about parsing the name. dailysearch give me "unable to parse into a valid tv-show" but backlog succeeded download (because It did a exact search. didn't use the rss cache - which seems to have the parse issue

**Comment by fernandog** [comment]
@miigotu 
So I have an an episode aired last night at 20:00 (now it's 14:00) and it's already available in tracker, dailysearch would pick it?  or dailysearcher will only pick episodes with same air date as actual day and not last 24hrs. That part of code is confusing to me, sorry.
