### ISSUE TITLE
ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by konomimaster** [SiCKRAGETV/sickrage-issues#2052]
Hi.
I'm running Sickrage on my Synology NAS running DSM 6.3-5592 and java 2.7.10-14

When i've installed Sickrage it runs just fine (after i've changed permissions so that it can access my files) until around midnight.

Around midnight, og when i shutdown/restart my NAS i can't access Sickrage.
When i connect to the IP-adress as normally i get a ERR_CONNECTION_RESET error.
The funny thing though, is that i, through the synology packagecenter, can see the logs for Sickrage, which shows that it still runs.

This problem began for about 2-3 weeks ago. Before that it ran just fine.

Sickrage runs as an admin account, to make sure that there isn't any problems there. 
Couchpotato runs from the same account and i haven't got any problems there.

**Comment by neoatomic** [comment]
I'm a little confused by your post. Think you mean DSM 5.2? 
Also how have you installed SickRage if you use the admin account.? You should use the Synocommunity package.

And please follow the guidelines for posting an issue, so we have all the required information. :
https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket

**Comment by konomimaster** [comment]
Hi guys. 
I was on holiday so i hasn't answered, i'm sorry.

Yes, it's DSM 5.2-5592 i'm running. I don't know where i got the other number from.

I'm installing Sickrage from the Synocommunity repository.
But since i won't let everyone access my mediafiles i need to change some permissions for Sickrage to get read/write access to the folders.
I'm using this guide to do this (https://couchpota.to/forum/viewtopic.php?t=1477)

About a month ago this worked just fine, and the permission part works just fine too.

I've reinstalled the OS yesterday to see if it was a problem with the OS but it hasn't helped.

It installed just fine and after changing the permissions it had access to my files (as usual).

But yet again; around 24 hours after installation i can't access Sickrage and am given the "ERR_CONNECTION_RESET"-error.

ps. I can't access my sickrage install so therefore i can't give up my commit hash. I'm on the master branch each time.

**Comment by miigotu** [comment]
@konomimaster Get it to where you can access SR again, update SR from the ui, then when it comes back up go to manage->mass update and check the column "Update" then scroll all the way down and click submit.

**Comment by konomimaster** [comment]
I've reinstalled Sickrage and re-indexed my files. I'm on commit hash: 6831ae9131af765586c1d348cc1835f363f350ce

Now i've updated the shows ind the mass-update submenu.

**Comment by miigotu** [comment]
And the results?

**Comment by konomimaster** [comment]
It updated the shows, i guess.
The problem is that Sickrage gets unresponsive about 24 hours after the install, so i can say if it has helped yet.
But to be clear: Everytime i re-install Sickrage and re-index all the shows, so Sickrage is supposed to be totally up-to-date everytime. 

I will get back in about 24 hours to tell if has worked or not.

**Comment by neoatomic** [comment]
This doesn't make sense... 
Did you restore your backup.? Or start with a fresh config.ini and sickbeard.db.?

**Comment by konomimaster** [comment]
I've unintalled the program and installed it again. So a fresh config.ini and sickbeard.db i suppose.

**Comment by neoatomic** [comment]
Yes, but lots of users restore the (maybe bad) backup and have the same error. :)
If you can join IRC, i'm there right now. Will see if i can think of something thats wrong.

**Comment by konomimaster** [comment]
Thanks mate. 
I just sent you a message on the channel.

**Comment by Dimas-sc** [comment]
Did you solved the problem? I'm in the same situation

**Comment by konomimaster** [comment]
Yes i solved it with some help!
In my case it was a permission-problem.

I don't know if you've done the same stuff i have (manually changing permissions and such) but here's what i found out.

Sickrage, when you download it on Synology, is run by the user "Sickrage" which doesn't appear in your "users"-tab, which is fine.
The thing is that there is a user-group called something like "synocommunity-media-group", and the Sickrage user is a member of this group.
When you have downloaded Sickrage you just have to give the synocommunity-group read (and write if you want to) access to your media-drive, and Sickrage will get this automatically.

**Comment by miigotu** [comment]
`sc-media` group
