### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-MANUAL-293322 :: Torrent file content is empty

### ISSUE THREAD

**Issue by copekyle** [SiCKRAGETV/sickrage-issues#2053]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@67a09aa1fd52ec6ee1c685fd5f7e59e66693617b
Link to Log: https://gist.github.com/cfd543ea3b881a62827b
### ERROR
```
SEARCHQUEUE-MANUAL-293322 :: Torrent file content is empty
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Reopen if this happens again.
