### ISSUE TITLE
[APP SUBMITTED]: not a valid bencoded string

### ISSUE THREAD

**Issue by copekyle** [SiCKRAGETV/sickrage-issues#2054]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@e21b2c296897986d68356f91ac98dbf3eeae55a3
Link to Log: https://gist.github.com/e5cb8200ea12d396640b
### ERROR
```
SEARCHQUEUE-MANUAL-293322 :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Disable proxy and it should work fine. There is no way around this.

**Comment by copekyle** [comment]
Just checked all 4 of my providers, I do not have any of them set up to use proxy's... is there anywhere else I should check for proxys?

**Comment by fernandog** [comment]
Try to manually download that torrent.
maybe its a bad one. That is what this error is about

**Comment by miigotu** [comment]
@copekyle did you every have a proxy enabled before? delete cache/sessions
Also what about global proxy?

**Comment by copekyle** [comment]
I've never had a need for a proxy so I've never set them up. When you say
delete cache, do you mean the database cache file?

**Comment by miigotu** [comment]
no there is a folder named cache, where your databases are. and it has a folder inside called sessions. Delete the sessions folder and try again.
