### ISSUE TITLE
[APP SUBMITTED]: database or disk is full

### ISSUE THREAD

**Issue by megabitus98** [SiCKRAGETV/sickrage-issues#2058]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-43-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@34272fc4d4bae39aafa1cead087734ad1151b9e2
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-248035 :: [NyaaTorrents] :: Error while searching NyaaTorrents, skipping: database or disk is full
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Make some space on your disk.

**Comment by megabitus98** [comment]
I have space, 262.75 GB used, 834.27 GB total, 571.52 GB free space

**Comment by miigotu** [comment]
Then check permissions for data dir, downloads, databases, etc. Can;t debug this further without debug logs etc.

https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md
