### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/mnt/usbdata/subtitles/Person of Interest'

### ISSUE THREAD

**Issue by dsoms** [SiCKRAGETV/sickrage-issues#2060]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-3.18.13-1-osmc-armv7l-with-debian-8.1**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@67a09aa1fd52ec6ee1c685fd5f7e59e66693617b
Link to Log: https://gist.github.com/f9df81ca2637a4ba2eb6
### ERROR
```
FINDSUBTITLES :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "/home/osmc/.sickrage/sickbeard/tv.py", line 1516, in downloadSubtitles
    helpers.chmodAsParent(subs_new_path)
  File "/home/osmc/.sickrage/sickbeard/helpers.py", line 598, in chmodAsParent
    childPathStat = ek.ek(os.stat, childPath)
  File "/home/osmc/.sickrage/sickbeard/encodingKludge.py", line 64, in ek
    result = func(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
OSError: [Errno 2] No such file or directory: '/mnt/usbdata/subtitles/Person of Interest'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Don't manual post process while automatic post processor is running.
