### ISSUE TITLE
[APP SUBMITTED]: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by mogipogi** [SiCKRAGETV/sickrage-issues#2063]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@34272fc4d4bae39aafa1cead087734ad1151b9e2
Link to Log: https://gist.github.com/5d2a970df58d1e295e58
### ERROR
```
Thread-27 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 269, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 4860, in index
    return t.respond()
  File "C:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_config_subtitles_tmpl.py", line 288, in respond
    for curService in VFN(VFSL([locals()]+SL+[globals(), builtin],"sickbeard.subtitles",True),"sortedServiceList",False)(): # generated from line 144, col 25
  File "C:\SickRage\sickbeard\subtitles.py", line 58, in sortedServiceList
    'url': provider_urls[curService] if curService in provider_urls else (lmgtfy % curService),
TypeError: not all arguments converted during string formatting

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Azno** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
Link to Log: https://gist.github.com/e856d15093b0a2f0be07
### ERROR
```
SEARCHQUEUE-BACKLOG-126011 :: [KickAssTorrents] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "F:\\SickRage\\SickRage\\sickbeard\\providers\\kat.py", line 89, in _doSearch\n    searchURL = self.urls[\'search\'] % url_fmt_string + \'?\' + urlencode(self.search_params)\nTypeError: not all arguments converted during string formatting\n'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Azno** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
Link to Log: https://gist.github.com/176de457c70ac0b3ed9c
### ERROR
```
SEARCHQUEUE-BACKLOG-126011 :: [KickAssTorrents] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "F:\\SickRage\\SickRage\\sickbeard\\providers\\kat.py", line 89, in _doSearch\n    searchURL = self.urls[\'search\'] % url_fmt_string + \'?\' + urlencode(self.search_params)\nTypeError: not all arguments converted during string formatting\n'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Azno** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
Link to Log: https://gist.github.com/3bda2e83333b72526bab
### ERROR
```
SEARCHQUEUE-BACKLOG-126011 :: [KickAssTorrents] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "F:\\SickRage\\SickRage\\sickbeard\\providers\\kat.py", line 89, in _doSearch\n    searchURL = self.urls[\'search\'] % url_fmt_string + \'?\' + urlencode(self.search_params)\nTypeError: not all arguments converted during string formatting\n'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Azno** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
Link to Log: https://gist.github.com/75820e2395ffab03d5d1
### ERROR
```
SEARCHQUEUE-BACKLOG-126011 :: [KickAssTorrents] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "F:\\SickRage\\SickRage\\sickbeard\\providers\\kat.py", line 89, in _doSearch\n    searchURL = self.urls[\'search\'] % url_fmt_string + \'?\' + urlencode(self.search_params)\nTypeError: not all arguments converted during string formatting\n'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Azno** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
Link to Log: https://gist.github.com/9f0145952fb7ab2d06fe
### ERROR
```
SEARCHQUEUE-BACKLOG-126011 :: [KickAssTorrents] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "F:\\SickRage\\SickRage\\sickbeard\\providers\\kat.py", line 89, in _doSearch\n    searchURL = self.urls[\'search\'] % url_fmt_string + \'?\' + urlencode(self.search_params)\nTypeError: not all arguments converted during string formatting\n'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
