### ISSUE TITLE
[APP SUBMITTED]: requests>=2.0.1

### ISSUE THREAD

**Issue by mogipogi** [SiCKRAGETV/sickrage-issues#2064]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@25649f25806373d1a70608add3c00d1d371b71bf
Link to Log: https://gist.github.com/5cad71f7587479bdab2f
### ERROR
```
SHOWQUEUE-SUBTITLE :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\tv.py", line 1498, in downloadSubtitles
    foundSubs = subliminal.download_best_subtitles([video], languages=languages, providers=providers, single=not sickbeard.SUBTITLES_MULTI, hearing_impaired=False)
  File "C:\SickRage\lib\subliminal\api.py", line 74, in download_best_subtitles
    with ProviderPool(providers, provider_configs) as pp:
  File "C:\SickRage\lib\subliminal\providers\__init__.py", line 241, in __init__
    self.providers = dict([(p, provider_manager[p]) for p in (providers or provider_manager.available_providers)])
  File "C:\SickRage\lib\subliminal\providers\__init__.py", line 180, in __getitem__
    self.providers[ep.name] = ep.load()
  File "C:\SickRage\lib\pkg_resources.py", line 1953, in load
    if require: self.require(env, installer)
  File "C:\SickRage\lib\pkg_resources.py", line 1966, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "C:\SickRage\lib\pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
DistributionNotFound: requests>=2.0.1

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Requests 2.6.0 is in the lib folder, fix your install/setup.

**Comment by RoRoo1977** [comment]
Same issue here on a QNAP. How do I "Fix your install/setup" 

New git-clone ?

**Comment by mogipogi** [comment]
I first did a git reset. Did not work.
Did a new git clone. Did not work.

Then I upgraded all packages.

easy_install --upgrade requests

The next time I ran Sickrage I'd get a DistributionNotFound error for another package.
So I did the 'easy_install' for each package that gave me the DistributionNotFound error.

I'm not sure what started/caused the DistributionNotFound errors.

**Comment by miigotu** [comment]
has nothing to do with SR or requests or easy_install. Your PYTHON install is broken.

**Comment by RoRoo1977** [comment]
So my Python install breaks due to an update of Sickrage?? I don't believe so.
CouchPotato (incl. sub downloads) works perfectly.

**Comment by miigotu** [comment]
The update of SR only removed the lib. prefix from imports. It is done the proper way now. Your install also needs to be proper.

**Comment by RoRoo1977** [comment]
So.... I need to reinstall Python 2.7 on my qnap?
I'll give it a go

**Comment by RoRoo1977** [comment]
Reinstalled Python, same issue.
changed SR to development version just to check if things would change. No change, same error.

**Comment by miigotu** [comment]
you can try to clone fresh, idk what the problem is here. Works on other qnap.

**Comment by RoRoo1977** [comment]
Did a complete reinstall of SR (with qpkg), update to latest. Then restored the conf and db files from backup and looks like the subtitles are working again.
TY!

**Comment by erijling** [comment]
"easy_install --upgrade requests" solve my problem (unbutu 15.04) then rebooted SR
