### ISSUE TITLE
Trakt Blacklist

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#2066]
@gborri
Ive got a question,
how do i use the Trakt blacklist feature ? what is the "Name(slug)" metioned on the tooltip?

**Comment by gborri** [comment]
The slug is the name of list you find on url when you are into it. Normally is the name of the list in which you substitute the space with dash.

**Comment by matigonkas** [comment]
@gborri for example if i whant black list "The Big Bang Theory " it has as a trakt url ```http://www.trakt.tv/shows/the-big-bang-theory```   the slug whould be ```the-big-bang-theory``` ?

**Comment by gborri** [comment]
No. You have to create a custom list. The slug is referred to the list.
When you have configured you can use It in add trending show. If it's
proposed a sho you don't like you can remove from add trending show (that's
means that the show has been added to blacklist).

Il giorno sab 11 lug 2015 21:25 matigonkas <notifications@github.com> ha
scritto:

> @gborri <https://github.com/gborri> for example if i whant black list
> "The Big Bang Theory " it has as a trakt url
> http://www.trakt.tv/shows/the-big-bang-theory the slug whould be
> the-big-bang-theory ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/2066#issuecomment-120653517>
> .
>
-- 

Giovanni

**Comment by matigonkas** [comment]
i think i got it @gborri  
soo ive created a list on trakt called smtg its url is ```https://www.trakt.tv/users/*****/lists/smtg```  the "slug" is ```smtg``` ?

**Comment by gborri** [comment]
Yes

Il giorno dom 12 lug 2015 01:58 matigonkas <notifications@github.com> ha
scritto:

> i think i got it @gborri <https://github.com/gborri>
>
> soo ive created a list on trakt called smtg its url is
> https://www.trakt.tv/users/*****/lists/smtg the "slug" is smtg ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/2066#issuecomment-120673277>
> .
>
-- 

Giovanni

**Comment by fernandog** [comment]
@gborri so, is just the name of the list?

**Comment by miigotu** [comment]
Slug is technically the proper term, but nin web developers won't understand that. It should be in regular people language.

**Comment by gborri** [comment]
What's the best way to refer to it for you guys?

Il giorno dom 12 lug 2015 14:47 miigotu <notifications@github.com> ha
scritto:

> Slug is technically the proper term, but nin web developers won't
> understand that. It should be in regular people language.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/2066#issuecomment-120718686>
> .
>
-- 

Giovanni

**Comment by miigotu** [comment]
`List name` ? lol

**Comment by gborri** [comment]
Yes for description

Il giorno lun 13 lug 2015 01:08 miigotu <notifications@github.com> ha
scritto:

> List name ? lol
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/2066#issuecomment-120771716>
> .
>
-- 

Giovanni

**Comment by miigotu** [comment]
`Name(slug) of List on Trakt for blacklisting show on 'Add Trending Show' page`

That is descriptive enough imho, unless someone thinks something else is better.
