### ISSUE TITLE
[APP SUBMITTED]: CHECKVERSION :: Unable to contact github, can't check for update

### ISSUE THREAD

**Issue by scherlund** [SiCKRAGETV/sickrage-issues#2069]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@a4f329fbc394e8939977bf9c43aa540f948fec75
Link to Log: https://gist.github.com/94c91594903c85d9650b
### ERROR
```
CHECKVERSION :: Unable to contact github, can't check for update
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
github issue. try again later
