### ISSUE TITLE
[Feature Request] Add http://www.tusubtitulo.com/

### ISSUE THREAD

**Issue by interpeix** [SiCKRAGETV/sickrage-issues#2070]
Here is the official substitute of www.subtitulos.es (recently closed), ¿Could anybody add this provider to subliminal? It's seems that is the same source code.

Thanks in advance.

**Comment by neoatomic** [comment]
@interpeix Best to post this request directly at :  https://github.com/Diaoul/subliminal 
This week we updated subminimal to version 0.8 and we don't want to mess to much with the code anymore. That allows us to easier update an prevent conflicts/bugs etc.
