### ISSUE TITLE
Subtitle Directory mishandled

### ISSUE THREAD

**Issue by dsoms** [SiCKRAGETV/sickrage-issues#2071]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-3.18.13-1-osmc-armv7l-with-debian-8.1**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@14b77f164d7c097a1506e73aa840555f2b29b0e2
No Log available with ERRORS: 
### ERROR
```
FINDSUBTITLES :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "/home/osmc/.sickrage/sickbeard/tv.py", line 1516, in downloadSubtitles
    helpers.chmodAsParent(subs_new_path)
  File "/home/osmc/.sickrage/sickbeard/helpers.py", line 598, in chmodAsParent
    childPathStat = ek.ek(os.stat, childPath)
  File "/home/osmc/.sickrage/sickbeard/encodingKludge.py", line 64, in ek
    result = func(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
OSError: [Errno 2] No such file or directory: '/mnt/usbdata/subtitles/Justified'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Does the path exist?

**Comment by miigotu** [comment]
Either this is a one time error, you need to set your subtitle path correct, or you can try the new commits I posted.

**Comment by dsoms** [comment]
Hi @miigotu,

It is not working with the last commit https://github.com/SiCKRAGETV/SickRage/commit/bbe5aa2cf2eeff261503602eea393e3460389dea

The path doesn't exists because the script is trying to put the subtitle in **/mnt/usbdata/subtitles/Justified**, and the subtitles path in the configuration is **/mnt/usbdata/subtitles**.

The name of the TV show at the end is not necessary.

**Comment by miigotu** [comment]
If it is not inside a folder with the name of the show, and the show name is not in your episode name, how would it be distinguished?

Did it used to just dump a mass of srt files in that dir for all of your shows?
Why is this beneficial compared to just letting them in the same folder as each episode?

**Comment by dsoms** [comment]
Yes, I just dump a mass of srt files in that dir for all of my shows.

It has been running well until the latest changes in the subtitles scripts.

If is not possible to store the subtitles in a custom folder, I think it's necessary to change the label "Subtitle directory" to "TV shows directory" in subtitles settings, or remove it because is redundant.

**Comment by miigotu** [comment]
It is possible, I had just coded it wrong I think.

ATM, I have it creating a subfolder inside the season if it is a relative path:
setting `subtitles` = Shows/Game of Thrones/Season 05/subtitles/*.srt

and creating a folder for each show inside the subtitles dir if it is an abolute path.
setting `/media/Subtitles` = `/media/Subtitles/Game of Thrones/*.srt`

If  this isn't the right way I can change it really easily.

I think what you want is when setting an absolute path:
setting `/media/Subtitles` = `/media/Subtitles/*.srt`

Simple change if that is how it is supposed to go, there was some confusion when I rewrote that part.

**Comment by dsoms** [comment]
>I think what you want is when setting an absolute path:
>setting /media/Subtitles = /media/Subtitles/*.srt

Yes, that's I want.

Thanks!

**Comment by miigotu** [comment]
Fixed in develop. BTW if it matters, relative paths will no longer work, only absolute existing paths.

**Comment by dsoms** [comment]
It's working again!

Great work! Thank you very much @miigotu!

**Comment by medariox** [comment]
Is there any chance to have support for relative paths back? It was really handy.

**Comment by miigotu** [comment]
As in showdir/subsdir/subtitles.srt ?

**Comment by medariox** [comment]
Exactly. I was using that constantly. It would be awesome to have it back!

**Comment by miigotu** [comment]
It was actually kind of broken and difficult to make it work properly.

**Comment by medariox** [comment]
Was working just fine for me. Remember what was broken on your side?

That's how I had it set
![subs image](https://snapr.pw/i/ee3500bea7.png)
and it was placing the subs in showdir/Subs/subtitles.srt

**Comment by miigotu** [comment]
Yes, it worked to download them, but subliminal was not finding them when rescanning, IIRC, and every time the subtitle finder thread ran it tried to download every subtitle for every episode again.

Maybe sometime we can add it back, but not right now. Kinda sick of fixing bugs in subtitles code right now so I wont dare to change it and chance it exploding (again).

**Comment by medariox** [comment]
Hey @miigotu 

I had some time this weekend and really wanted to have the relative paths back.
Supports relative, absolute and also empty paths again now. I had SickRage running for a few days with the fix and didn't notice any problem with it, it might need some more testing (especially with different OS) tho. In that time I couldn't replicate the problem you had with the subtitles being downloaded multiple times.

Here is the fix: https://github.com/medariox/SickRage/commit/6ecf487b42327e2725558abef6653cd435a437d7
