### ISSUE TITLE
File is locked for reading/writing

### ISSUE THREAD

**Issue by pathsny** [SiCKRAGETV/sickrage-issues#2074]
I've been facing a problem with several files where even when I force postprocess I see the error "File is locked for reading/writing". For example.

2015-07-11 17:00:50 WARNING  Thread-19 :: Processing failed for /media/Incoming/TVSeries/The.Daily.Show.2015.06.25.Richard.Lewis.HDTV.x264-CROOKS.mp4: File is locked for reading/writing

sadly the relevant logs are not more granular than that even with debug set to 1.
http://pastebin.com/QuFRCXWu

running stat on the file does not reveal any information
"687931148 103586 -rw-rw-rw- 1 (921) path 4294967295 153205572 "Jul 11 13:30:49 2015" "Jul  4 14:10:03 2015" "Jul 11 16:36:23 2015" "Jul  4 13:59:59 2015" 131072 298877 0x800 The.Daily.Show.2015.06.25.Richard.Lewis.HDTV.x264-CROOKS.mp4"

I'm not sure how to figure out the cause.

details about sickrage
SR Version:	BRANCH: (master) / COMMIT: (25649f25806373d1a70608add3c00d1d371b71bf) 
SR User:	media
SR Locale:	(None, None)
SR Config file:	/var/db/sickrage/config.ini
SR Database file:	/var/db/sickrage/sickbeard.db
SR Cache Dir:	/var/db/sickrage/cache
SR Log Dir:	/var/db/sickrage/Logs
SR Arguments:	['--datadir', '/var/db/sickrage', '-d', '--pidfile', '/var/run/sickrage/sickrage.pid', '-q', '--nolaunch']
Python Version:	2.7.8 (default, Dec 15 2014, 02:33:48) [GCC 4.2.1 20070831 patched [FreeBSD]]

**Comment by miigotu** [comment]
I assume you have your post process folder set to the same place where incomplete downloads are?

Without the full log I can't tell if you are or not so I will give you the generic response for this problem.

You need to have your torrent client move completed downloads to a different folder, and post-process only from the complete downloads folder.

**Comment by pathsny** [comment]
This is not the case. my incomplete downloads are not in the same place as the post process folder.

**Comment by miigotu** [comment]
Full debug log is usually what we need. Have you verified there is not more than one instance of SR running? Is it only this file?

Try a mv on it and mv it back and see what happens:
```bash
mv The.Daily.Show.2015.06.25.Richard.Lewis.HDTV.x264-CROOKS-1.mp4
mv The.Daily.Show.2015.06.25.Richard.Lewis.HDTV.x264-CROOKS.mp4
```
You can also try:
`lsof The.Daily.Show.2015.06.25.Richard.Lewis.HDTV.x264-CROOKS.mp4`

**Comment by miigotu** [comment]
Have you tried turning it off and then back on? lol

**Comment by pathsny** [comment]
miigotu, I have restarted it several times and this is over several updates.
I just discovered a workaround that worked though surprisingly.

My torrents incomplete values go to media/incoming/Incomplete and when completed go to
media/incoming/TVSeries

When a file is stored directly as /media/incoming/TVseries/foo.mp4 I get this error.
When the torrent is a directory and I get media/incoming/TVSeries/foo/foo.mp4 then things work fine.

**Comment by miigotu** [comment]
check the permissions of `media/incoming/TVSeries`

**Comment by miigotu** [comment]
and of incoming ^

**Comment by pathsny** [comment]
The TVSeries directory does not have write permissions. Could that be the cause.

**Comment by miigotu** [comment]
Yes, parent folder needs to have permissions for rename files.

**Comment by pathsny** [comment]
ok cool, let me try that thanks
