### ISSUE TITLE
[APP SUBMITTED]: ('Connection aborted.', gaierror(-2, 'Name or service not known'))

### ISSUE THREAD

**Issue by megabitus98** [SiCKRAGETV/sickrage-issues#2076]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-43-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@508aad90bdf08b21877ecb93f73d93d023051727
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-79895 :: [AlphaRatio] :: Unable to connect to AlphaRatio provider: error ('Connection aborted.', gaierror(-2, 'Name or service not known'))
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
site must have been down temporarily.
