### ISSUE TITLE
sabToSickBeard.py no episodes found in folder

### ISSUE THREAD

**Issue by szafran81** [SiCKRAGETV/sickrage-issues#2077]
Hi,

I'm in the process of moving from SickBeard to SickRage. Now I'm trying to make SR sabToSickBeard.py work, and... well it doesn't:

```
szafran@NAS:~/.scripts/demony$ python /home/szafran/.sources/www/sickrage/autoProcessTV/sabToSickBeard.py "/home/szafran/Pobrane/Kompletne/seriale/.do-przerobienia/pojedyncze/A.to.Z.S01E05.720p.HDTV.X264-DIMENSION"
Loading config from /home/szafran/.sources/www/sickrage/autoProcessTV/autoProcessTV.cfg

Opening URL: http://localhost:8081/sr/home/postprocess/processEpisode
Processing folder /home/szafran/Pobrane/Kompletne/seriale/.do-przerobienia/pojedyncze/A.to.Z.S01E05.720p.HDTV.X264-DIMENSION
TV_DOWNLOAD_DIR:
PostProcessing Path: /home/szafran/Pobrane/Kompletne/seriale/.do-przerobienia/pojedyncze
PostProcessing Dirs: [u'A.to.Z.S01E05.720p.HDTV.X264-DIMENSION']
PostProcessing Files: []
PostProcessing VideoFiles: []
PostProcessing RarContent: []
PostProcessing VideoInRar: []
Processing folder A.to.Z.S01E05.720p.HDTV.X264-DIMENSION
A.to.Z.S01E05.720p.HDTV.X264-DIMENSION : No processable items found in folder
Processing completed
```

and the folder contains only the episode mkv file.

Any ideas what's wrong ?

**Comment by miigotu** [comment]
Is that episode set to wanted or skipped/ignored? also, is the default episode status for that show wanted?

**Comment by szafran81** [comment]
Episode was set to wanted, then SR snatched it (episode was properly set to snatched). Default for that show is wanted.

This was with the SR version that I got yesterday evening (CET) - sorry, but I don't remember the version. Just now I did an update (to BRANCH: (master) / COMMIT: (7a753b4ad5e0a540353432e7357801e70e8ae73e) ), and the script worked (with exactly the same setup and command line). So some change between yesterday and now made it work.

BTW where can I find the quality keywords that SR uses to determine the ep quality ? (it would be nice if it used the ep real resolution for that).

**Comment by miigotu** [comment]
https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/common.py#L179

It is a rather complicated guess, based on standard scene rules, and is fairly accurate when the title is not a lie.

It is a planned feature to move from mass regex in name detection to using guessit, and from using file name for quality to using mediainfo.

SickBeard does it the same way we do, only ours is a bit more advance and inclusive.

I am gonna close this now as you don;t have the problem anymore.

**Comment by szafran81** [comment]
Updated today to BRANCH: (master) / COMMIT: (010325315d75ed7aab47619b57106bcca6d280f6) and allready have 3 eps not recognized by SR (they weren't even recognized when I've put them in the proper dir and named them as the autorenamer should).

**Comment by miigotu** [comment]
1. Your post processing folder needs to be outside of your TV library, and your torrent client should only move downloads there once they are completed.

2. The show you want needs to have the episode set to wanted for post processor to pick it up. After your show is added, set the default status for the show to wanted, by editting the show (only if the show was added before the update almost a week ago, check the default status of all your shows to make sure it's what you want it to be)

3. If you rename files and put them in the show folder where it belongs, SickRage nor SickBeard will recognize it until you rescan the show from within SR/SB.

**Comment by szafran81** [comment]
1. It is, and I don't use torrent (only NZBs - and I use script to automate al that stuff - scripts that worked for a couple of years with SB without a glitch - but that doesnt matter since it's the postprocessing that doesnt recognize any video files - and it did after yesterdays update and it broke again after todays update). I moved the eps and renamed them manually after the postprocessor failed and did a rescan.
2. It has (I use SR for 2 days so the update thing doesn't concern me).
3. It didn't even after rescanning (I had to manually set the ep from snatched to downloaded).

**Comment by miigotu** [comment]
Is it possible your file is still in the process of being copied when the pp is run?

Absolutely nothing has changed in post processing over the last few days.

**Comment by szafran81** [comment]
I'm 99% (100% even) sure it isn't - since the program I wrote that takes care of recompression of each downloaded ep copies it to the right dir then flushes the mem stream and only then runs the pp script (even after it failed I've tried to launch the script manually as in the first post, so then the ep was copied for sure).

That's weird. Anyways I'll run some more tests with that script and come back with the results if it doesn't work correctly.
Thank you for your help.

**Comment by fernandog** [comment]
Did you check permissions?

**Comment by szafran81** [comment]
Didn't have to - everything was installed/compiled/runned using one user.

**Comment by fernandog** [comment]
but sickrage runs as different user. check your init script

**Comment by szafran81** [comment]
No it doesn't (at least not in my case). I do know how to config it.

**Comment by fernandog** [comment]
stop SR, edit SickRage/sickbeard/processTV.py,

and change to be like this (mind identation):
    videoFiles = filter(helpers.isMediaFile, allFiles)
    result.output += logHelper("Result of videoFiles: {0}".format(videofiles)), logger.DEBUG)
    allDirs.append(dirName)


change:
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/processTV.py#L340
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/processTV.py#L347
from 'pass' to 'raise'

save, start sr

didn't test. wrote code here.
it will display all videos found in the folder.

**Comment by szafran81** [comment]
Ok. Thanks. Will try that after I finish moving my series to SR.
