### ISSUE TITLE
Sometime Sickrage won't find the show that my provider have.

### ISSUE THREAD

**Issue by rickytin** [SiCKRAGETV/sickrage-issues#2078]
For example I have the show "Power" but SickRage won't find the last episode but if I go to the provider that I use most of the time "Nzbgeek" the show is there with the same quality I use.

Another problem is I like to use first NZB providers and then Torrent (Randomize Providers is not check) my NZB have the show but the show is downloaded by Torrent.

Thanks

**Comment by miigotu** [comment]
SR goes through a whole lot of checks and tests before it selects a result as good/valid and wanted, so you would have to show full debug logs to get any serious answer.

Likely the Usenet retention/maxage is not set right in your config or the URL to the nzb is invalid now. It also could be an issue with the nzb name or you misunderstand the qualities.

Can't help without debug logs.

**Comment by neoatomic** [comment]
@rickytin Please follow the guideline for posting an issue. : 
https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket
If you enable debug=1 in the Sickrage settings and post the log we will be able to take a look what is happening.

A reason could be that you need to add a scene exception to the show with the (scene) name that is used on the torrent site. (example "power (2015)" or just "power" )

**Comment by rickytin** [comment]
INFO

Python Version: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
Operating System: Windows-8-6.2.9200
Branch: master
Commit: SiCKRAGETV/SickRage@7a753b4
Link to Log: https://gist.github.com/87d5cb1fd207b35a9291

**Comment by neoatomic** [comment]
@rickytin The errors says : 
`Show name with ID 295944 don't exist in theTVDB anymore. Please change/delete your local .nfo file or remove it from your TRAKT watchlist`

Did you try this.?

**Comment by miigotu** [comment]
@gborri the show needs removed from the watch list or added to a blacklist when this happens. Just letting it continue to be an error until the user fixes it himself is unacceptable, that breaks the philosophy of total automation.
