### ISSUE TITLE
Initial scale on mobile device

### ISSUE THREAD

**Issue by MGaetan89** [SiCKRAGETV/sickrage-issues#2079]
It seems the `initial-scale=1` part of the following meta does not work (at least on Android):

```html
<meta name="viewport" content="width=device-width, initial-scale=1">
```

The following, however, seem to work (the same as in `apibuilder`):

```html
<meta name="viewport" content="width=device-width">
```

As I'm not an export in mobile web, maybe someone can confirm this, so I can send a PR?

**Comment by miigotu** [comment]
@MGaetan89 just pr it, with only this change, and if someone has issues with it it is 1 click to revert the merge.

**Comment by fernandog** [comment]
@MGaetan89 I like with this option:

		<meta name="viewport" content="width=device-width, user-scalable=no">

you can scroll but you can't zoom. Seems ok to me

**Comment by MGaetan89** [comment]
@fernandog I don't agree. Some pages display too many things. It would be too difficult to read without zooming.

**Comment by fernandog** [comment]
@MGaetan89 so our only solution is to don't let inc_top resize and make everything else resizeble

**Comment by MGaetan89** [comment]
Maybe yes. I will try to use the mobile version of SickRage to see exactly what it looks like and propose a proper solution.

**Comment by fernandog** [comment]
don't know how cheetah handles the page. I think it considers one only page and not three (top, middle, bottom)

@miigotu is that it ?

**Comment by miigotu** [comment]
I would just do this:
`<meta name="viewport" content="width=device-width">`
That way page is always loaded not zoomed.

Cheetah sees it as all one page when using includes, just like php.

**Comment by MGaetan89** [comment]
Ok, I will send a PR soon with just `<meta name="viewport" content="width=device-width">`.

But I don't understand why the `initial-scale` does not work...

**Comment by MGaetan89** [comment]
Closing, as SiCKRAGETV/SickRage#2095 was merged.
