### ISSUE TITLE
TokyoTosho - No DN in Magnets

### ISSUE THREAD

**Issue by Rawh** [SiCKRAGETV/sickrage-issues#2081]
Branch: Sickcommunity (unsure which branch, probably just master?)
Commit hash: version 20150526-1. Unsure which commit this is exactly. Could just ditch their install and go with a clone of the latest master, if that'll fix it :)
Your operating system and python version: DSM 5.2-5592 Synology; python 2.7.10-14
What you did: Added a few anime shows, configured the search engine to use tokyotosho.info, hit the search ep button.
What happened: Magnet links were offered as results, sickrage just gave error and did nothing.
What you expected: For sickrage to submit the magnet link to transmission, so it could download the torrent. 
Logfile: https://gist.github.com/Rawh/343d38150810f8f60dc0

**Comment by miigotu** [comment]
I can't even tell from the information you provided if you are running an official sickrage or a fork, let alone which version.

**Comment by Rawh** [comment]
According to the logs and the main page of Sickrage, I'm running:

SR Version:	BRANCH: (master) / COMMIT: (010325315d75ed7aab47619b57106bcca6d280f6) 
SR Arguments:	['--daemon', '--pidfile', '/usr/local/sickrage/var/sickrage.pid', '--config', '/usr/local/sickrage/var/config.ini', '--datadir', '/usr/local/sickrage/var/', '--nolaunch']
Python Version:	2.7.10 (default, Jun 3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]

**Comment by miigotu** [comment]
Please reproduce with debug=1 and post the full log to gist.

**Comment by Rawh** [comment]
Here's another with debug set to 1:

https://gist.github.com/Rawh/f6c6512ea86cdd6fe657

**Comment by fernandog** [comment]
@miigotu 
but if is a magnet link.....

"Without the http:// part, requests has no idea how to connect to the remote server."

http://stackoverflow.com/questions/15115328/python-requests-no-connection-adapters

**Comment by Rawh** [comment]
@fernandog: https://en.wikipedia.org/wiki/Magnet_URI_scheme

Simply put, I think you will need a protocol handler which understands magnet links, putting http:// in front will not solve this, as it listens to different parameters.

**Comment by fernandog** [comment]
the correct is to send this direct to the torrent client, not try to open it. maybe it's missing a check if magnet > sent to client instead of open the link

**Comment by miigotu** [comment]
Failing in the regex in _makeURL, becuase dn= is not in the magnet.

this line results in an exception:
`torrent_name = re.findall('dn=([^&]+)', result.url)[0]`

and the except does:
`urls = [result.url]`

@Rawh Most likely with the fix this provider will not find any results now. The only possibility is a dedicated provider, as the generic provider cannot handle magnets with no title in the magnet link.

**Comment by Rawh** [comment]
@miigotu Thanks for checking the issue out so quickly! :) TokyoToshokan is added as a default provider to Sickrage, that's why I selected it after the installation. I will give it another try and see if it finds correct results but maybe you also want to remove it from the default provider list, if it doesn't do anything anymore.

**Comment by miigotu** [comment]
@Rawh Did you change the magnet links in those logs?

VYYQZZYFFA7W7W2N3AK5S6EUQAGU2LMM isn't even a valid hash. magnet hashes are A-F 0-9 only.

**Comment by Rawh** [comment]
Why would I purposefully adjust logs, that makes no sense.

**Comment by miigotu** [comment]
(some people would think they shouldnt show what they are downloading)

Anyways, VYYQZZYFFA7W7W2N3AK5S6EUQAGU2LMM is base32 hash, so it is ok.

I have some ideas to make it work again when dn= is missing from the magnet.

**Comment by miigotu** [comment]
[HorribleSubs].Chaos.Dragon.-.02.[1080p]..mkv is the name gotten by the search

The actual name is:
[HorribleSubs] Chaos Dragon - 02 [1080p]. mkv

If I use the real name in the result.name I can use that when getting dn= from the magnet.

**Comment by Rawh** [comment]
You can try the url in transmission, it should start downloading the file.
I always used TT for manual downloads but sickrage makes it so much easier
to manage, sadly without using TT atm, but it's not a big loss as
Kickasstorrents and nyaa seem to work fine (albeit without the use of
magnet links) :-)

If I wanted to remain anonymous regarding my downloads,I wouldn't have
reported the issue.

**Comment by miigotu** [comment]
@Rawh Kickass uses magnets ^^

We just use a few torrent caching sites so we can verify the magnet is real before accepting it as valid.
I'll look into a way to fix it for TokyoTosho over the next few days.

**Comment by Rawh** [comment]
I stand corrected, never used it beside sickrage :-)

**Comment by Rawh** [comment]
@fernandog: What exactly does your "closed this in ..." mean? Did you clone the issue and wrote a workaround for it in your own dev/build?
