### ISSUE TITLE
Not showing Brazilian Portuguese subtitle option and showing Breton with the Brazilian Flag

### ISSUE THREAD

**Issue by luizpdlh** [SiCKRAGETV/sickrage-issues#2082]
I think this has been corrected once and it's now appearing again on the master branch. There are two different Portuguese languages, one of them is Portuguese from Portugal (marked on OpenSubtitles as pt) and the other is Portuguese from Brazil, or Brazilian Portuguese (marked on OpenSubtitles as pb).

Searching for portuguese (only shows Portuguese from Portugal - pt):
![screen shot 2015-07-12 at 7 22 29 pm](https://cloud.githubusercontent.com/assets/12464216/8640343/670f47bc-28cb-11e5-8970-681b81cc4073.png)

On the Subtitles Search page there's no option for the Brazilian Portuguese, however the Breton language (spoken in Lower Brittany) appears with the Brazilian flag.

Searching for br* shows Breton with the Brazilian flag:
![screen shot 2015-07-12 at 7 23 36 pm](https://cloud.githubusercontent.com/assets/12464216/8640347/8aff7bc4-28cb-11e5-82a4-47cea6de6ec3.png)

If I select Breton to try to download subs from OpenSubtitles or any other provider, it searches for "br" and doesn't return anything, as the Brazilian Portuguese subtitles are listed as "pb". If I select Portuguese, it will download subtitles from Portugal (pt).

Can you please add Brazilian Portuguese again, point it to "pb" wit the Brazilian flag, and correct the Breton flag?

Thank you.

**Comment by miigotu** [comment]
This is a limitation in subliminal right now, trying to find a workaround but it might not happen.

Even babelfish has a problem with this:
```python
>>> l = babelfish.Language
>>> l.fromietf('pt-BR')
<Language [pt-BR]>
>>> p = l.fromietf('pt-BR')
>>> p.alpha3
u'por'
>>> p.alpha2
u'pt'
>>> p = l.fromietf('pb')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "babelfish/language.py", line 124, in fromietf
    language = cls.fromalpha2(language_subtag)
  File "babelfish/language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "babelfish/converters/__init__.py", line 165, in reverse
    raise LanguageReverseError(code)
babelfish.exceptions.LanguageReverseError: u'pb'
>>> p = l.fromietf('pob')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "babelfish/language.py", line 126, in fromietf
    language = cls(language_subtag)
  File "babelfish/language.py", line 82, in __init__
    raise ValueError('%r is not a valid language' % language)
ValueError: u'pob' is not a valid language
>>> p = l.fromopensubtitles('pob')
>>> p.alpha2
u'pt'
>>> p.alpha3
u'por'
>>> p = l.fromopensubtitles('pb')
>>> p.alpha3
u'por'
>>> p.alpha2
u'pt'
>>>
```

**Comment by luizpdlh** [comment]
Interesting, thanks for looking at it @miigotu. It used to work before, not sure why they removed that fix. Should I open an issue on their git?

**Comment by miigotu** [comment]
@luizpdlh there is already an issue there about the unsupported pb code. If you can get him to tell you a way to get pr-BR subs to download through subliminal, I can make it as a workaround here.

**Comment by miigotu** [comment]
https://github.com/Diaoul/subliminal/issues/323

**Comment by Diaoul** [comment]
If you want opensubtitles code use the correct property.
```python
>>> l = babelfish.Language.fromietf('pt-BR')
>>> l.opensubtitles
u'pob'
```

**Comment by Diaoul** [comment]
This is described here: http://babelfish.readthedocs.org/en/latest/

**Comment by miigotu** [comment]
@Diaoul I can get the pob code in and out of babelfish, but how to get subliminal to download and save as pb or pob? afaik subliminal uses only the .alpha3 to do the searches right? l = babelfish.Language.fromietf('pt-BR').alpha3 is por

**Comment by miigotu** [comment]
@Diaoul should I be only using the languages with opensubtitles codes everywhere? I am currently using alpha3

**Comment by Diaoul** [comment]
Depends on what you're doing. Next release will save subtitles with IETF language in the filename so that might solve your issue.

**Comment by miigotu** [comment]
Basically, saving a list of ietf codes we want languages for, then having subliminal video.scan_subtitle_languages(video_path) comparing with our list to see what we still need, and creating objects .fromietf to download_best_subtitles and letting subliminal save them out (results in alpha2 in filename).

It's just a pain making all of these moving parts work when I finally got it working (after mass hours), and now I only have this pb/por problem.

If subliminal only searches for opensubtitles codes it woulda been easier, but then I would get less results, so the combo of ietf and opensubtitles i think is what is giving me the headache.

I guess all i need to know is if I create a pt-BR language object, and pass it to download_best_subtitles, it will download pb/pob or pt/por? it gets saved as .pt. by subliminal

**Comment by miigotu** [comment]
What is the list of codes I should be letting them choose from? Is this enough?
Currently I have: (because it was closest I could get to codes people already had stored from subliminal 0.6.x)
```python
[language for language in babelfish.LANGUAGE_MATRIX if hasattr(language, 'alpha2') and language.alpha2]
```
But maybe this is correct now?
```python
[babelfish.Language.fromopensubtitles(language) for language in babelfish.language_converters['opensubtitles'].codes if len(language) is 3]
```

**Comment by Diaoul** [comment]
It will download pt-BR (pob on opensubtitles) and save it as .pt.
Next version will save as .pt_BR. no avoid loosing information.

**Comment by fernandog** [comment]
@Diaoul kodi for example don't recognize pt_BR afaik

**Comment by miigotu** [comment]
@Diaoul Is only letting users select languages which have opensubtitles code the correct way? O would I be limiting people too much?

Yes, cannot have pt and pt-br subtitle at the same time right now xD. So saving as ietf will help (or opensubtitles code if that is all thats actually used)

```bash
05:52:06 DEBUG::Thread-42 :: history.logSubtitle thesubdb, por
05:52:06 DEBUG::Thread-42 :: history.logSubtitle opensubtitles, pob
```
```bash
miigotu@PC:~/Projects/SickRage $ ls Shows/Game\ of\ Thrones/Season\ 05/*.srt
Shows/Game of Thrones/Season 05/Game of Thrones - S05E02 - The House of Black and White.pt.srt
```

So I guess the final question is, which list of languages should I limit users to picking from our UI? only opensubtitles codes or do I need to piece two lists together or ?

I also have a feature request sometime, I can open a ticket for (a parameter to pass the original filename to scan_video when the file has been renamed)
