### ISSUE TITLE
[Feature request] Only store URL/ID in tvshow.nfo metadata

### ISSUE THREAD

**Issue by FuNK3Y** [SiCKRAGETV/sickrage-issues#2083]
It would be great if you could add an option to only save the URL in the tvshow.nfo metadata (http://kodi.wiki/view/NFO_files/TV_shows point 2).

I would like to let Kodi manage the metadata itself (in order to avoid unneeded files in the TV show folder), but if I enable the tvshow.nfo metadata it won't gather any additional info on the internet as there are already data present in the XML. Only storing the URL would solve the issue and make sure that Kodi will identify the correct show as it will be based on the URL instead of the name.

**Comment by miigotu** [comment]
This is not too difficult, but more involved than it sounds. We also have to change how SR parses tvshow.nfo (to be able to get the show id from the url) and to not error.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
