### ISSUE TITLE
[APP SUBMITTED]: not a valid bencoded string

### ISSUE THREAD

**Issue by ripper1967** [SiCKRAGETV/sickrage-issues#2084]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@7a753b4ad5e0a540353432e7357801e70e8ae73e
Link to Log: https://gist.github.com/8bbb317a9da16a404c77
### ERROR
```
SEARCHQUEUE-MANUAL-267777 :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
I'm disabling iteorrent for now until we figure this one out. We fixed an issue that caused this for torcache already, so it is not the same problem.
