### ISSUE TITLE
[APP SUBMITTED]: database disk image is malformed

### ISSUE THREAD

**Issue by rickytin** [SiCKRAGETV/sickrage-issues#2087]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@010325315d75ed7aab47619b57106bcca6d280f6
Link to Log: https://gist.github.com/415809e5a4abd851e762
### ERROR
```
Thread-194 :: Fatal error executing query: database disk image is malformed
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rickytin** [comment]
Shutdown SickRage, delete cache.db and start SickRage and now is working again.

**Comment by miigotu** [comment]
http://www.sqlite.org/howtocorrupt.html
