### ISSUE TITLE
[APP SUBMITTED]: expected string or buffer

### ISSUE THREAD

**Issue by vegeros** [SiCKRAGETV/sickrage-issues#2089]
### INFO
Python Version: **2.7.6 (default, Sep  9 2014, 15:04:36) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]**
Operating System: **Darwin-14.4.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@010325315d75ed7aab47619b57106bcca6d280f6
Link to Log: https://gist.github.com/402b3b596d6cd1123f53
### ERROR
```
SEARCHQUEUE-BACKLOG-255316 :: Failed parsing TNTVillage Traceback: Traceback (most recent call last):
  File "/Applications/SickRage/sickbeard/providers/tntvillage.py", line 439, in _doSearch
    if not self._is_italian(result) and not self.subtitle:
  File "/Applications/SickRage/sickbeard/providers/tntvillage.py", line 312, in _is_italian
    if not re.search(sub, name, re.I):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 142, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or buffer

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Fixed in develop

**Comment by blakadder** [comment]
### INFO
Python Version: **2.7.9 (default, Jan 16 2015, 11:00:00) [GCC 4.9.2]**
Operating System: **Linux-2.6.31.8-armv5tel-with-libc0**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@30435190ef8880901df555bcda0d46902ea81fb5
No Log available with ERRORS: 
### ERROR
```
CHECKVERSION :: Exception generated in thread CHECKVERSION: expected string or buffer
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by OmgImAlexis** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-57-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@30435190ef8880901df555bcda0d46902ea81fb5
Link to Log: https://gist.github.com/b7618fce93f1a94eae9c
### ERROR
```
CHECKVERSION :: Exception generated in thread CHECKVERSION: expected string or buffer
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by hennning** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@56fd7a9447fb0e72398568be737c1f00b5bb07f4
Link to Log: https://gist.github.com/a21384aaa6060f5728b6
### ERROR
```
CHECKVERSION :: Exception generated in thread CHECKVERSION: expected string or buffer
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by blakadder** [comment]
### INFO
Python Version: **2.7.9 (default, Jan 16 2015, 11:00:00) [GCC 4.9.2]**
Operating System: **Linux-2.6.31.8-armv5tel-with-libc0**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@56fd7a9447fb0e72398568be737c1f00b5bb07f4
No Log available with ERRORS: 
### ERROR
```
CHECKVERSION :: Exception generated in thread CHECKVERSION: expected string or buffer
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by megabitus98** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@3572446c66615e7876bf996e3eaf4d6d26400a7d
No Log available with ERRORS: 
### ERROR
```
CHECKVERSION :: Exception generated in thread CHECKVERSION: expected string or buffer
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Trapizomba** [comment]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 06:12:10) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@4028db3d7a2cc582b0f591d981ed3af344b4e75a
No Log available with ERRORS: 
### ERROR
```
CHECKVERSION :: Exception generated in thread CHECKVERSION: expected string or buffer
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by quindarious-gooch** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@5d4bec2c6022a9e2d5ec934791cf80a0b2553a6f
No Log available with ERRORS: 
### ERROR
```
CHECKVERSION :: Exception generated in thread CHECKVERSION: expected string or buffer
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Tazaz** [comment]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:33:21) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-31-generic-x86_64-with-Ubuntu-15.04-vivid**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@d0e3a1a60bf76ff86abfd861e79061b6bb2f4961
Link to Log: https://gist.github.com/9434ca3620f92ed3c01b
### ERROR
```
Thread-16 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 251, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1058, in updateCheck
    sickbeard.versionCheckScheduler.action.check_for_new_news(force=True)
  File "/opt/sickrage/sickbeard/versionChecker.py", line 297, in check_for_new_news
    dates= re.finditer(r'^####(\d{4}-\d{2}-\d{2})####$', news, re.M)
  File "/usr/lib/python2.7/re.py", line 190, in finditer
    return _compile(pattern, flags).finditer(string)
TypeError: expected string or buffer

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
