### ISSUE TITLE
[APP SUBMITTED]: CHECKVERSION :: No git specified, can't use git commands

### ISSUE THREAD

**Issue by kharn89** [SiCKRAGETV/sickrage-issues#2090]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: ****
Commit: SiCKRAGETV/SickRage@
Link to Log: https://gist.github.com/d6c5c374785365b869ae
### ERROR
```
CHECKVERSION :: No git specified, can't use git commands
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
installed git?
