### ISSUE TITLE
[APP SUBMITTED]: CHECKVERSION :: We can't proceed with the update. Unable to check remote DB version

### ISSUE THREAD

**Issue by sbelongie** [SiCKRAGETV/sickrage-issues#2091]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: ****
Commit: SiCKRAGETV/SickRage@d8bd1bd1ad374948abac04747dcf3fa08519f5b4
Link to Log: https://gist.github.com/fcb768fd5fcaa8b554c4
### ERROR
```
CHECKVERSION :: We can't proceed with the update. Unable to check remote DB version
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
intermittent issue

**Comment by drewcifernz** [comment]
Hi, I'm having this issue as well.   choosing "check for updates" will complete the update without issue, however I get this error whenever it tries to auto-update.

**Comment by fernandog** [comment]
@miigotu 

ssl issues with this?

https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/versionChecker.py#L197

**Comment by fernandog** [comment]
@drewcifernz please post full logs when this happen

**Comment by miigotu** [comment]
@fernandog yes, GH doesnt like when you load a file that way. That is exactly the reason we switched to gh_pages.

**Comment by fernandog** [comment]
but we need to get the database version from github, so what should we do ?

**Comment by miigotu** [comment]
need to get the newest commit hash by _check_github_for_update, then use cdn.rawgit with the hash.

**Comment by fernandog** [comment]
Why hash? Cache issues with cdn?

**Comment by fernandog** [comment]
What about branch?

**Comment by miigotu** [comment]
Yes, if you don't use the hash, the url is not unique each commit, and the page would always be the same when using cdn.rawgit.  Have to use cdn.rawgit or we get blocked, and cdn is cached forever.

**Comment by fernandog** [comment]
We need to store current github hash otherwise everytime we need it we must call "check updates". There is another code I did that calls that too.

**Comment by miigotu** [comment]
something like:
(need to set the object names)
```python
_check_github_for_update()
response = requests.get("https://cdn.rawgit.com/SICKRAGETV/SickRage/" + str(get_newest_commit_hash()) +"/sickbeard/databases/mainDB.py")
```

**Comment by fernandog** [comment]
@drewcifernz @sbelongie 

please test this:
stop SR
edit /SickRage/sickbeard/versionChecker.py
erase contents, paste this one: https://raw.githubusercontent.com/fernandog/SickRage/version_checker_ssl/sickbeard/versionChecker.py
save
start SR. see if fixes it

**Comment by fernandog** [comment]
@drewcifernz @sbelongie

please reply

**Comment by sbelongie** [comment]
No longer getting error.  Please close
