### ISSUE TITLE
[APP SUBMITTED]: '_socketobject' object has no attribute 'set_tlsext_host_name'

### ISSUE THREAD

**Issue by fferraro87** [SiCKRAGETV/sickrage-issues#2092]
### INFO
Python Version: **2.7.3 (default, Jun 22 2015, 19:33:41) [GCC 4.6.3]**
Operating System: **Linux-2.6.32-042stab102.9-x86_64-with-Ubuntu-12.04-precise**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@010325315d75ed7aab47619b57106bcca6d280f6
Link to Log: https://gist.github.com/1b50b14d6b8861216c8d
### ERROR
```
SEARCHQUEUE-MANUAL-292124 :: [MoreThanTV] :: Error while searching MoreThanTV, skipping: '_socketobject' object has no attribute 'set_tlsext_host_name'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1566
