### ISSUE TITLE
"No new released episodes found .." message appears even if found releases eps

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#2096]
What is the IF of this ELSE?

https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/dailysearcher.py#L107-L108

Seems wrong!
I got two new episodes from daily search but I still got "No new released episodes found ..."

```
2015-07-12 23:27:30 INFO     DAILYSEARCHER :: No new released episodes found ...
2015-07-12 23:27:30 INFO     DAILYSEARCHER :: New episode ***** - 2x05 - ***** airs today, setting to default episode status for this show: Wanted
2015-07-12 23:27:29 INFO     DAILYSEARCHER :: New episode ******** - 2x04 - **** airs today, setting to default episode status for this show: Wanted
2015-07-12 23:27:28 INFO     DAILYSEARCHER :: Searching for new released episodes ...
```

**Comment by fernandog** [comment]
@miigotu help me with this please?

**Comment by miigotu** [comment]
for loops can have an else, in cases of empty list in the for.

**Comment by fernandog** [comment]
but it's not working, isn't? sqlResults has results

**Comment by fernandog** [comment]
@miigotu misplaced?? shouldn't be:

        if len(sql_l) > 0:
            myDB = db.DBConnection()
            myDB.mass_action(sql_l)
        else:
            logger.log(u"No new released episodes found ...")

**Comment by miigotu** [comment]
Sure, but it does the exact same thing.

**Comment by miigotu** [comment]
for sqlEp in sqlResults:
    #this happens if len(sqlResults)
else:
    #this happens if not len(sqlResults)

**Comment by fernandog** [comment]
I see. But its not working. Will PR this change and see whats happening

**Comment by miigotu** [comment]
That syntax may not be portable, I don;t see it documented anywhere other than stackoverflow (and it works here)

try in terminal:

python
```python
for i in []:
    pass
else:
    print "Empty list"
```

**Comment by miigotu** [comment]
@fernandog ok, so I figured it out, your change will fix it.

the else is always called after the last item in the list:

```python
>>> for i in ['something', 'other']:
...     print i
... else:
...     print 'End of list'
... 
something
other
End of list
```

**Comment by fernandog** [comment]
ok! will commit. thanks!

**Comment by miigotu** [comment]
L108 Should be "Done checking for new episodes" or something like that, and then the else on L113
