### ISSUE TITLE
Issue with Post-Processing w/Plex Media Server Commands Enabled

### ISSUE THREAD

**Issue by alzeric** [SiCKRAGETV/sickrage-issues#2098]
**BRANCH: (master) / COMMIT: (010325315d75ed7aab47619b57106bcca6d280f6)**

    2015-07-13 13:38:09 Thread-27 :: Failed doing webui callback: Traceback (most recent call last):
      File "C:\SickRage-master\sickbeard\webserve.py", line 269, in async_call
        result = function(**kwargs)
      File "C:\SickRage-master\sickbeard\webserve.py", line 2182, in processEpisode
        is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
      File "C:\SickRage-master\sickbeard\processTV.py", line 204, in processDir
        process_media(path, [video], nzbName, process_method, force, is_priority, result)
      File "C:\SickRage-master\sickbeard\processTV.py", line 491, in process_media
        result.result = processor.process()
      File "C:\SickRage-master\sickbeard\postProcessor.py", line 1092, in process
        notifiers.plex_notifier.update_library(ep_obj)
      File "C:\SickRage-master\sickbeard\notifiers\plex.py", line 259, in update_library
        hosts_try = (hosts_all.copy(), hosts_match.copy())[len(hosts_match)]
    IndexError: tuple index out of range

Once I did a forced post-process the first item it began to process threw this error and the whole process stopped, and redirected the page back to the show listings.  After disabling Send Commands to Plex Media Server this error no longer was an issue and the items post-processed successfully.

(Tokens, Login, Server IP are all correct and the Test Button shows successful under the PMS settings section under notifications)

**Comment by fernandog** [comment]
@alzeric please send a screen shot of all plex settings (the two plex sections settings)

**Comment by alzeric** [comment]
Plex Media server is the only one being used, and Plex Home Theatre isn't even installed on my machines.

Sending plex commands isn't a huge issue for me, as Plex Automatically updates it's library anyways once the episodes are post-processed into their final destinaton.  However wanted to test it out and maybe others plan on using this feature, hence the reason of this ticket.

![sr_plex](https://cloud.githubusercontent.com/assets/5651849/8657947/56407c12-2966-11e5-88ed-8c168672caca.png)

**Comment by fernandog** [comment]
@alzeric enable "Send Commands to Plex " and send print of that too

**Comment by alzeric** [comment]
![sr_plex_2](https://cloud.githubusercontent.com/assets/5651849/8658025/028fe282-2967-11e5-95c9-6f3be93050e3.png)

**Comment by alzeric** [comment]
Here is a screenshot of the Console Window as well so you can see a better error message then the log.

![sr_plex_3](https://cloud.githubusercontent.com/assets/5651849/8658486/a467e774-2969-11e5-9c5f-f2dd4834b0a4.png)

**Comment by miigotu** [comment]
@alzeric Did something change in the plex api?

**Comment by miigotu** [comment]
@alzeric seems you have a show in two paths in plex, or 2 "Location"
Thats the only way this error can happen I think, by reading the code. (unless i'm missing something)

If there is more than 1 location for the show on any host,  len(hosts_match) is greater than len(hosts_all)

This might be a bug if it is normal to have a show in more than 1 location on plex.

**Comment by miigotu** [comment]
@alzeric have you checked this problem?

**Comment by fernandog** [comment]
@alzeric if you don't reply we will close

**Comment by alzeric** [comment]
Sorry was out of town yesterday, 

I did add a new drive to my setup over the weekend.  And set the new drive as the Default settings under "Add Show".

I had a blackhole on Drive K and moved it to Drive L once I got my expansion drive.  However this seems to be failing on any show, not just Face Off, which I did originally have on Drive K and moved that one to Drive L (however I updated all the paths in SR to account for the move, even did a restart of SR to make sure nothing was cached).  It also failed on the series Caprica (which was when I first noticed it) and that was never moved drives it always was on Drive L.

The Plex API never changed either, even double checked with the "How to find your API Key" link to make sure.  However the connect tests come back successful.

Plex does allow for drive spanning for any particular library so theoretically you could have 1/2 a season on one drive and 1/2 on another and it would appear as normal in Plex.  But i've not tested that at all.

**Comment by miigotu** [comment]
The problem with notifying plex has nothing to do with the location set in SickRage, but that the show has 2 locations on Plex.

**Comment by ripper1967** [comment]
they havent changed there plex api miigotu, but my api key had changed 2 days in a row on plex and not sure why, so if it was working and not now, I would guess your api key has changed,my sickrage to plex notification is working fine,

**Comment by miigotu** [comment]
@ripper1967 He has a show in plex at 2 different locations. When SR finds the show and parses it's locations it chokes because it doesn't make any sense. Just needs to move all the season and episodes of the show into the same location and rescan/clean plex library.

**Comment by alzeric** [comment]
Yeh I originally had Face off on my K drive under TV shows and then moved it to my L drive under Reality shows.  I didn't even think to rescan/clean the library.
