### ISSUE TITLE
[Improvement] Add silent hour for notification.

### ISSUE THREAD

**Issue by mac1202** [SiCKRAGETV/sickrage-issues#2100]
Hello everyone, first thanks for this amazing software.
I just got one little problem. I use the freemobile notification plugin to notified my girlfriend when sickrage get a new episode for her show. Unfortunately with the timezone difference between US and France she receive text message in the middle of the night which isn't cool. It will be nice to add an option to set a time interval during which sickrage doesn't send notification and queue them to send them at the appropriate time.

**Comment by fernandog** [comment]
@mac1202 I suggest you use NMA - Notify my Android - it has silent hours setting inside the app

don't know about other notifiers. probaly they have

**Comment by mac1202** [comment]
Thanks for your suggestion but my girlfriend phone is running windows mobile.

**Comment by fernandog** [comment]
@mac1202 

try:
**Pushalot**
Pushalot is a platform for receiving custom push notifications to connected devices running Windows Phone or Windows 8.

**Comment by mac1202** [comment]
Ok thanks you I get what i want with pushalot.
