### ISSUE TITLE
nzbToMedia won't post-process unless episode is marked as wanted

### ISSUE THREAD

**Issue by mannibis** [SiCKRAGETV/sickrage-issues#2101]
SR Version:	BRANCH: (master) / COMMIT: (010325315d75ed7aab47619b57106bcca6d280f6) 
OS: QNAP NAS

I use SickRage for post-processing only, and up until yesterday I was able to have past episodes marked as "Ignored" and I would download them and call nzbToSickBeard.py from NZBGet which would process the files via SickRage (rename, move, pushbullet alert, plex update).

After an update yesterday I noticed however that my post-processing was failing in NZBGet. I ran it over and over and it kept telling me (one of many examples):

nzbToSickBeard: [16:11:23] [POSTPROCESS]::SICKBEARD: Sons.of.Anarchy.S05E11.To.Thine.Own.Self.720p.BluRay.DD5.1.x264-NTb : No processable items found in folder

The file was in there and after an hour or so of debugging, I set the episode as wanted in SickRage and only then was it able to post-process. This was never the case before. I use DOGnzb's watchlist to snatch for me and then use SickRage to manage and post-process. But it seems as if I can no longer have episodes set to "Ignored" or "Skipped" and still have them post-process. I can't even have a "lesser" quality downloaded (where the episode shows up yellow meaning that it still hasn't found the proper archive quality). I literally have to set it to "Wanted" aka RED

Was this change intended? Do I have to set everything as wanted from now on? I wouldn't want to do this because setting an episode as wanted would trigger a backlog search from my providers, which I do not want to happen. 

Let me know if this is fixable, as it was all working perfectly before.

Thank you for your time

**Comment by miigotu** [comment]
Please let me know if latest develop fixes this, and comment back here. If it is still an issue I will re-open.

**Comment by mannibis** [comment]
Thanks, however "develop" is not an option in the Checkout Branch dropdown. All I can choose is master....Is there a way to do this manually without screwing up my install?

**Comment by mannibis** [comment]
Did it manually, and I believe that did the trick. I marked a downloaded episode as Ignored, redownloaded another release and it processed/replaced.

Thanks!

**Comment by mannibis** [comment]
Can you let me know when the fix is merged into master so I can switch branches?

**Comment by fernandog** [comment]
Already in master

**Comment by mannibis** [comment]
thank you
