### ISSUE TITLE
Handling of failed downloads not working, when nzbget and its intermediate dir. are on another machine

### ISSUE THREAD

**Issue by baschinger** [SiCKRAGETV/sickrage-issues#2102]
I am running the latest commit of the SickRage master branch on my Synology, and nzbget on a Ubuntu VM on my NUC. I also use the nzbToMedia post-processing scripts.

nzbget's workflow: Things are downloaded to and extracted on the NUC, and if both succeeds, the results are moved to a share on the NAS. Otherwise, everything stays in the intermediate folder on the NUC.

Hence, when a download fails, the folder on the share never gets created, and SickRage aborts post-processing with the message "Unable to figure out what folder to process.[...]".
In this constellation SickRage does not (and will not) have access to the intermediate folder on the NUC.

As a quick-fix I wrote a bash-script that creates the folder on the share, when a download fails. But it would be nice, if this issue were adressed at the source.
Using this script everything works fine, so it's not a configuration issue.

**Comment by miigotu** [comment]
"Unable to figure out what folder to process.[...]". is the correct response when the folder does not exist.

What do you want it to do anyways if there is nothing to process regardless?

**Comment by baschinger** [comment]
It should mark the download as failed. Right now all downloads that fail, remain in the snatched status.

Why does SickRage check for a folder, when it already knows, that the download has failed and there will be no files to post-process?

**Comment by miigotu** [comment]
Post Processor is a thread that has nothing to do with failed download handling, you should always pass it a folder that exists. IE: Post processor is designed to be passed a parent folder of completed downloads, not the actual download.

Make your completed downloads be moved to a folder that always exists.

always post-process for example:
someshare/Complete/

have shows moved into:
someshare/Complete/DownloadName

If the download fails DownloadName will not be there and will not be processed, but there will be no error.

**Comment by baschinger** [comment]
OK, I'll see if the nzbToMedia-script can be configured that way. Thank you
for the clarification and your quick responses.
Am 15.07.2015 8:04 vorm. schrieb "miigotu" <notifications@github.com>:
