### ISSUE TITLE
[APP SUBMITTED]: mismatched tag: line 6, column 2

### ISSUE THREAD

**Issue by johndoe86x** [SiCKRAGETV/sickrage-issues#2105]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.16.0-0.bpo.4-amd64-x86_64-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@c75f58a4134e579536e7db3a73d92d03c05a7153
Link to Log: https://gist.github.com/59560d38b6b24e689668
### ERROR
```
Thread-24 :: PLEX: Error while trying to contact Plex Media Server: mismatched tag: line 6, column 2
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
`http error : error 401 : Unauthorized`

This exception should be handled, BUT check your username/pw/token
