### ISSUE TITLE
[APP SUBMITTED]: cannot concatenate 'str' and 'NoneType' objects

### ISSUE THREAD

**Issue by Holbert** [SiCKRAGETV/sickrage-issues#2106]
### INFO
Python Version: **2.7.10 (default, May 26 2015, 04:16:29) [GCC 5.1.0]**
Operating System: **Linux-4.0.4-unRAID-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@c75f58a4134e579536e7db3a73d92d03c05a7153
Link to Log: https://gist.github.com/Holbert/31658ac7e5b36f9fa58c
### ERROR
```
Thread-58 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 269, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1158, in branchCheckout
    return self.update(sickbeard.PID)
  File "/opt/sickrage/sickbeard/webserve.py", line 1142, in update
    if sickbeard.versionCheckScheduler.action.update():
  File "/opt/sickrage/sickbeard/versionChecker.py", line 272, in update
    return self.updater.update()
  File "/opt/sickrage/sickbeard/versionChecker.py", line 814, in update
    notifiers.notify_git_update(sickbeard.NEWEST_VERSION_STRING)
  File "/opt/sickrage/sickbeard/notifiers/__init__.py", line 111, in notify_git_update
    n.notify_git_update(new_version)
  File "/opt/sickrage/sickbeard/notifiers/plex.py", line 154, in notify_git_update
    self._notify_pmc(update_text + new_version, title)
TypeError: cannot concatenate 'str' and 'NoneType' objects

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Holbert** [comment]
This seems to be the problem:
```
2015-07-13 23:01:11 ERROR    SEARCHQUEUE-DAILY-SEARCH :: Torrent file content is empty
```

**Comment by miigotu** [comment]
nope, two separate problems. git is not working on your device?

**Comment by fernandog** [comment]
@miigotu cachecontrol issue?

  File "/opt/sickrage/lib/cachecontrol/caches/file_cache.py", line 99, in set
    with self.lock_class(name) as lock:
  File "/opt/sickrage/lib/lockfile/__init__.py", line 238, in __enter__
    self.acquire()
  File "/opt/sickrage/lib/lockfile/linklockfile.py", line 34, in acquire
    raise LockFailed("%s" % e.strerror)
LockFailed: Function not implemented

**Comment by miigotu** [comment]
This should fix it, although the LockFailed might actually raise now.

**Comment by fernandog** [comment]
@miigotu 
check my commit. is that ok too? first error in this issue

**Comment by miigotu** [comment]
His error is because new_version is empty =P

**Comment by miigotu** [comment]
update_text + new_version
'str' + 'NoneType'

**Comment by Holbert** [comment]
Thanks for looking at this guys. I will update and test it out tonight and report back if I'm getting the same error.

**Comment by ming1981** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@0503591bdb856456bdd7709ce45a11fcd6ce1b26
No Log available with ERRORS: 
### ERROR
```
TORNADO :: API :: cannot concatenate 'str' and 'NoneType' objects
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by ming1981** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@297ccc3043957ffa96fa142035a9393845cdb024
No Log available with ERRORS: 
### ERROR
```
TORNADO :: API :: cannot concatenate 'str' and 'NoneType' objects
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by XxUnkn0wnxX** [comment]
### INFO
Python Version: **2.7.10 (default, Sep 23 2015, 04:34:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)]**
Operating System: **Darwin-15.0.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-257655 :: [TorrentProject] :: Error while searching TorrentProject, skipping: cannot concatenate 'str' and 'NoneType' objects
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
