### ISSUE TITLE
Unaired episodes being changed to skipped after show airs?

### ISSUE THREAD

**Issue by ruinit** [SiCKRAGETV/sickrage-issues#2107]
Recently I have noticed that a lot of shows are not snatched after the show airs? It seems to be changing the shows to skipped instead of wanted? Happened again last night show airs I go to check this morning why the shows didn't download and they are marked as skipped? Any ideas?

**Comment by fernandog** [comment]
@ruinit 
mass edit - change all your tv-shows "default ep status" to wante if you want unaired episodes to be 
downloaded

**Comment by ruinit** [comment]
oh ok something has changed.. thanks

**Comment by fernandog** [comment]
no. it was fixed! =)

**Comment by fire-ablaze** [comment]
Ferndog, it is not for adding a new show.  It is for existing show that have been getting snatched all along.  Lets say a  show is set to air on 7/14/2015.  When I wake up on 7/15/2015, the show has not been snatched, does not show in history.  When I go the the show's page it shows the episode status for 7/14/2015 as skipped.  how would a mass edit of change all skipped to wanted affect upcoming shows?

**Comment by BenBeyond** [comment]
Just wanted to chim in and say that I am also having this issue...

**Comment by fernandog** [comment]
first: check default ep status for all this shows
second: if is skipped change "default ep status" to wanted. NEW unaired episodes will have the status of "default ep status", in your case: wanted
third: change all skipped to wanted in the show page

**Comment by fire-ablaze** [comment]
it was explained better in another post that mass change edit to change default episode status from skipped to wanted will only affect FUTURE episodes.

**Comment by BenBeyond** [comment]
Did as fernandog stated, but this morning, no new episodes downloaded...

Checked the shows that I know should have been snatched, but the new episodes had changed to skipped.  Double-checked the settings for the shows and the default episode status is wanted.

**Comment by fernandog** [comment]
need full logs

**Comment by fernandog** [comment]
@BenBeyond 

check your logs for:

 DAILYSEARCHER :: New episode ****** airs today, setting to default episode status for this show: Wanted

**Comment by fire-ablaze** [comment]
worked for me.  Thanks Fernando G..
