### ISSUE TITLE
Search by Scene Numbering disabled but SR still searches by Scene numbering

### ISSUE THREAD

**Issue by BenBeyond** [SiCKRAGETV/sickrage-issues#2109]
SR Version:	BRANCH: (master) / COMMIT: (2bfdb0a92083aa969fbfada92471850379a01045) 
Python Version:	2.7.9

I have disabled the search by scene numbering for the show Steven Universe because SR was not finding the correct episodes on KAT. But when I had a look myself, i was able to find episodes, but they are being numbered using the indexers numbering.

But when I run a manual search for each of the wanted episodes, it is still using scene numbering to search for the episodes.

EDIT: previously have had issues with scene numbering and PP (https://github.com/SiCKRAGETV/sickrage-issues/issues/1788)

**Comment by fernandog** [comment]
you need to full update that show when you change scene numbering option

**Comment by BenBeyond** [comment]
Followed your instructions here, and it was working correctly until i updated SR, then reverted to scene numbering search even though scene numbering option is disabled.
