### ISSUE TITLE
Enable debug toggle from UI

### ISSUE THREAD

**Issue by piejanssens** [SiCKRAGETV/sickrage-issues#2110]
Enable switching on/off debug logging from log page.
Should not require a restart.

**Comment by fernandog** [comment]
why?

**Comment by piejanssens** [comment]
Because it's not convenient at the moment and because it's a small change.
On DSM you need to SSH, find the config file change it manually using 'vi' and start the application again using the package manager. Not really user friendly and not easy for the average user.
Maybe you just want to debug a certain process, like a force search for a single ep, in this case it's useless to print the entire debug for starting SR. You could just switch on debugging, press force search, switch off, and check your logs...

**Comment by fernandog** [comment]
there is already debug setting in UI

![2](https://cloud.githubusercontent.com/assets/2620870/8676438/cdc61d32-2a1f-11e5-98a9-4005079c6781.png)

**Comment by piejanssens** [comment]
Missed that. Thanks.
