### ISSUE TITLE
[APP SUBMITTED]: Thread-53 :: Errors: [u'New location <tt>Houdini</tt> does not exist']

### ISSUE THREAD

**Issue by sleepermjs** [SiCKRAGETV/sickrage-issues#2111]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-57-generic-i686-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@2bfdb0a92083aa969fbfada92471850379a01045
Link to Log: https://gist.github.com/2d5c6d9796caa800b588
### ERROR
```
Thread-53 :: Errors: [u'New location <tt>Houdini</tt> does not exist']
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by sleepermjs** [comment]
Attempting to delete a show via Mass Update I am receiving this error.

**Comment by fernandog** [comment]
"new location" - are you sure you tried to delete 

OR did you try to move location??

**Comment by sleepermjs** [comment]
Manage > Mass Update > Edit Selected > Root Directories * (Delete)... Is that the correct method?

**Comment by fernandog** [comment]
NO! you are trying to erase the show location!

option 1:
why don't you open show page and click the button "delete"
optin 2:
mass update > find column delete > check the ones you want to delete > click "submit" in the right botton corner
