### ISSUE TITLE
Weird log message 

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#2112]
@miigotu is that right?! a "formula" in the log message?

 Last update was too soon, using old cache: today()-2015-07-14 03:32:35<0:05:00

```
logger.log(u"Last update was too soon, using old cache: today()-" + str(self.lastUpdate) + "<" + str(datetime.timedelta(minutes=self.minTime)), logger.DEBUG)
```
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/tvcache.py#L234

**Comment by miigotu** [comment]
wrong quoting.

**Comment by miigotu** [comment]
I'll fix that one.

**Comment by miigotu** [comment]
@fernandog You can change it, its quick in the gui and I can't decide on a better way to write it:
`logger.log(u"Last update was too soon, using old cache: " + str(self.lastUpdate), logger.DEBUG)`

This is just a debug log to be able to know when the cache isn't updating properly.

**Comment by fernandog** [comment]
@miigotu 

what do you think?

`            logger.log(u"Last update was too soon, using old cache: {0}. Updated less then {1} minutes ago".format(str(self.lastUpdate),self.minTime), logger.DEBUG)`

minTime is always 10min

**Comment by miigotu** [comment]
Not always 10 mins xD. Each provider sets its own min time by overriding it in the cache section at the bottom of the provider.

datetime is not thread safe in SR right now, because locale can change intermittently with sbdatetime, so .format is not a good option.

**Comment by fernandog** [comment]
like this then?
            logger.log(u"Last update was too soon, using old cache: " + str(self.lastUpdate) + ". Updated less then " + str(self.minTime) + "minutes ago", logger.DEBUG)

**Comment by fernandog** [comment]
Last update was too soon, using old cache: 2015-07-14 16:37:46. Updated less then 5 minutes ago

**Comment by miigotu** [comment]
Perfect.
