### ISSUE TITLE
Unable to fix... database disk image is malformed!

### ISSUE THREAD

**Issue by mbnoimi** [SiCKRAGETV/sickrage-issues#2113]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-18-generic-x86_64-with-LinuxMint-17.1-rebecca**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@2bfdb0a92083aa969fbfada92471850379a01045
Link to Log: https://gist.github.com/fc4818ab39a75c54ba45
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Fatal error executing query: database disk image is malformed
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by mbnoimi** [comment]
I did as mentioned in this #549 but unfortunately it didn't fix the issue

P.S. I tried to delete whole sickbeard.db then let SR create a new one on restart but it ain't fix the issue too :(

**Comment by miigotu** [comment]
delete cache.db not sickbeard.sb
