### ISSUE TITLE
.torrent downloaded twice: the download fails

### ISSUE THREAD

**Issue by adaur** [SiCKRAGETV/sickrage-issues#2116]
Hi,

I want to add a provider that gives me an autoget URL to download the .torrent.

The problem is, this URL is valid for one request only... and SickRage seems to do at least one GET before download (file generic.py, __if self._verify_download(filename):__)

Is there a way to bypass this check? Thanks!

**Comment by miigotu** [comment]
SickRage does only 1 GET per snatch, but we do a HEAD request to verify that the link is valid.  Working around this breaks the way it is meant to work, and there is no way to make sure we are picking a working link.

**Comment by adaur** [comment]
I'm surprised to be the first having this problem. What about adding a constant like DISABLE_VERIFY and disable check if it is defined? We would keep compatibility, and you already done such fixes: https://github.com/SiCKRAGETV/SickRage/commit/2c05a0e87f8e8d70f4831423f4e0599d898619d3

If I find a solution, would it be merged?

**Comment by adaur** [comment]
Hm, maybe this commit would fix it after all. I'll let you know.

**Comment by miigotu** [comment]
That commit has nothing to do with your issue.

Your issue is here:
https://github.com/SiCKRAGETV/SickRage/blob/2c05a0e87f8e8d70f4831423f4e0599d898619d3/sickbeard/search.py#L242

**Comment by adaur** [comment]
Yes, not related directly but in the way the NO_DOWNLOAD_NAME is set.

**Comment by miigotu** [comment]
That was only because sometimes magnets do not have a download name in the magnet (against magnet specification).

This change does not hurt any providers that have dn= in their magnets. But if I don't check the url before selecting it, users will get a lot of download links that do not work, for only your benefit of one provider that gives you a one shot download link for no reason.

**Comment by adaur** [comment]
My idea was to add a constant in myprovider.py and skip the HEAD request if this parameter is set (and only in this case). Would you accept such a merge or should I find a workaround?

**Comment by fernandog** [comment]
@adaur 
or you could ask that provider to not consider a HEAD request as a download request

**Comment by adaur** [comment]
Indeed, but this is a private TK that will probably never integrate such a change.

**Comment by fernandog** [comment]
you could try

**Comment by miigotu** [comment]
maybe the link could be good for 30 seconds, or for 2 hits =P, or 1 head 1 get request, explain that we check links before downloading them, so that we dont prematurely ignore subsequent results by picking a dead link.

**Comment by adaur** [comment]
Yes, I will!

Otherwise I can get links formatted as http://www.domain.com/?section=DOWNLOAD&id=ID&uid=UID&get=1&hash=HASH

This time the download link is valid without a hit limit, but I always get a

2015-07-15 19:01:53 DEBUG    SEARCHQUEUE-MANUAL-175001 :: Result is not a valid torrent file

If I go to the link myself, I download the torrent right away, no matter if I load two or three times the URL. I think we could do something at the SickRage level here :)

**Comment by adaur** [comment]
I have found a workaround: putting

    def _verify_download(self, file_name=None):
        return True

in the provider file works. But it's not really clean :)

**Comment by miigotu** [comment]
This has nothing to do with _verify_download. That is only for a torrent file that is already downloaded.

**Comment by miigotu** [comment]
http://www.domain.com/?section=DOWNLOAD&id=ID&uid=UID&get=1&hash=HASH and why doesnt this work?
You could try this patch: https://gist.github.com/miigotu/fcd30bdcd4f8af028e5d

And show the content of the torrent file it downloads.

Other than that, without an account on this still unknown provider I cannot help.
