### ISSUE TITLE
Shows aren't downloaded, just put to "skipped" status.

### ISSUE THREAD

**Issue by Psychoteur** [SiCKRAGETV/sickrage-issues#2124]
SR Version:	BRANCH: (master) / COMMIT: (608c06810abb05ab6e9d07947c86d42b1b1a21c2) 
SR User:	media
SR Locale:	(None, None)
SR Config file:	/var/db/sickrage/config.ini
SR Database file:	/var/db/sickrage/sickbeard.db
SR Cache Dir:	/var/db/sickrage/cache
SR Log Dir:	/var/db/sickrage/Logs
SR Arguments:	['--datadir', '/var/db/sickrage', '-d', '--pidfile', '/var/run/sickrage/sickrage.pid', '-q', '--nolaunch']
Python Version:	2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]

Hello,

I've got an issue with sickrage for 7 days it doesn't download shows, just put shows in "skipped".
I've set 10 days retention for shows, so even the show aren't downloaded. They should appear inside "coming episodes" in red.

It happens very fast. I checked on Sunday with the show "Humans". Sickage sees the schedule, and almost past date the show is labeled with "skipped" status. 

If I go to the "general" section, select the show and do  manual search, the show is snatched and downloaded. 

I tried to change to 14 days but it still doesn't work.  

I've set debug mode and I don't see something relevant inside the logs. 
And I've to wait the next day to see any change in sickrage behaviour. 

Thanks.

**Comment by miigotu** [comment]
Edit the show, and set default status to wanted.

**Comment by Psychoteur** [comment]
Whoa, wait a second, sickrage is going nuts. I can't select a show anymore, got a lot of errors.


2015-07-15 11:50:54 Thread-129 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 1320, in displayShow
    return t.respond()
  File "/var/db/sickrage/cache/cheetah/_usr_pbi_sickrage_amd64_share_sickrage_SickRage_gui_slick_interfaces_default_displayShow_tmpl.py", line 1335, in respond
    for sub_lang in [VFN(VFFSL(SL,"subtitles",True),"fromietf",False)(x) for x in VFN(VFFSL(SL,"epResult",True)["subtitles"],"split",False)(',') if VFFSL(SL,"epResult",True)["subtitles"]]: # generated from line 581, col 13
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/subtitles.py", line 70, in fromietf
    return babelfish.Language.fromopensubtitles(language)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/babelfish/language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/babelfish/converters/opensubtitles.py", line 36, in reverse
    raise LanguageReverseError(opensubtitles)
LanguageReverseError: u'fra'

2015-07-15 11:50:48 Thread-137 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 1320, in displayShow
    return t.respond()
  File "/var/db/sickrage/cache/cheetah/_usr_pbi_sickrage_amd64_share_sickrage_SickRage_gui_slick_interfaces_default_displayShow_tmpl.py", line 1335, in respond
    for sub_lang in [VFN(VFFSL(SL,"subtitles",True),"fromietf",False)(x) for x in VFN(VFFSL(SL,"epResult",True)["subtitles"],"split",False)(',') if VFFSL(SL,"epResult",True)["subtitles"]]: # generated from line 581, col 13
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/subtitles.py", line 70, in fromietf
    return babelfish.Language.fromopensubtitles(language)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/babelfish/language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/babelfish/converters/opensubtitles.py", line 36, in reverse
    raise LanguageReverseError(opensubtitles)
LanguageReverseError: u'fra'

**Comment by miigotu** [comment]
stop SR, edit config.ini, find subtitles_languages= and remove all languages from there. The start SR and re-add your languages from the GUI.

We switched to opensubtitles codes.

**Comment by Psychoteur** [comment]
It doesn't work. I tried from someone else configuration. 
I did what you said before updating, shutdown sickrage. Up and check config.ini ... subtitles_languages=""

Same behaviour as mine, unable to select a show, same errors logs. 
The only difference with mine, the shows keep downloading as expected.

**Comment by miigotu** [comment]
Default episode status is for when new episodes areabout to air the next day, daily searcher changes them from unaired to default episode status. The ones that are already skipped you need to manually change to wanted.  You just need to set the default episode status so it doesn't keep happening.

As for the sybtitles error, try mass update and rescan all shows.

**Comment by Psychoteur** [comment]
Ok, but it's the way I've done it. I quite remember well since if you had a show with many seasons but only want the last one. You have to check "skipped" or "archived" and quick before it fills the queue.

Now, thinking about it, I know for a fact my coworker had to put "archived" when adding shows since it kept downloading old seasons, even after selected "archived".

If I follow I need to update every single subtitles files to have back the selection of show in general section ?

I've got like 85 shows .... 5 seasons x 24 episodes x 2 subtitles per episode ! 

I still don't get it why, the subtiles files are messing up the selection of a show ?

**Comment by miigotu** [comment]
When you add a show, you select how you want all previous episodes status to be. Before, after the show was added, all new episodes were then automatically wanted.

Now, after the show is first added, default status is automatically set to wanted, but you can change it to something else and it will respect your setting.

This becomes an issue and requires you to set the default episode status to wanted for the shows added before this change. When you add new shows from now on you won't have to do anything different than before.

The libraries handling subtitles were updated, and in that update one of the libraries had a complete rewrite. We also went through a period of trying different ways of implementing the new library.

Rescanning will not re-download all of your subtitles, it will just change the code for them we have in your database.

This is a good thing, because we now have much more accurate support for subtitles, and find them more often. Sync issues should be to a minimum now.

There are a few quirks to work out here and there, but all in all I think it is working pretty well.

**Comment by miigotu** [comment]
Also, archived is a downloaded state. Maybe your coworker had episodes with 'unknown' quality and SR was trying to replace them with a better quality since they had 'any' set as the wanted quality. All qualities are better than unknown from a programming perspective.

**Comment by Psychoteur** [comment]
Ok, for taking the time to explain. 

I'm still rebuilding my sickrage. First start, update, restart, put back my backup. And then I will start edit my shows. 

Let me back at you later. Sickrage is very helpful since I have very low bandwidth then it downloads during night. 

Well, I had the issue with 6x12 bones. Sickrage tried and retried to download the episode, even with being manually selected as skipped, archived. 

Yeah, you're right about "unknown" I remember telling him to put the quality of the episode into the name.

Programming, still learning ;)

**Comment by Psychoteur** [comment]
Ok, everything seems back to "normal". 

Thanks
