### ISSUE TITLE
[APP SUBMITTED]: u'nld'

### ISSUE THREAD

**Issue by Veldkornet** [SiCKRAGETV/sickrage-issues#2125]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 13:42:00) [GCC 4.6.4]**
Operating System: **Linux-2.6.32.12-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@608c06810abb05ab6e9d07947c86d42b1b1a21c2
Link to Log: https://gist.github.com/4478df847f2ec7d02dc2
### ERROR
```
Thread-22 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 1320, in displayShow
    return t.respond()
  File "/usr/local/sickrage/var/cache/cheetah/_usr_local_sickrage_var_SickRage_gui_slick_interfaces_default_displayShow_tmpl.py", line 1335, in respond
    for sub_lang in [VFN(VFFSL(SL,"subtitles",True),"fromietf",False)(x) for x in VFN(VFFSL(SL,"epResult",True)["subtitles"],"split",False)(',') if VFFSL(SL,"epResult",True)["subtitles"]]: # generated from line 581, col 13
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/subtitles.py", line 70, in fromietf
    return babelfish.Language.fromopensubtitles(language)
  File "/usr/local/sickrage/var/SickRage/lib/babelfish/language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "/usr/local/sickrage/var/SickRage/lib/babelfish/converters/opensubtitles.py", line 36, in reverse
    raise LanguageReverseError(opensubtitles)
LanguageReverseError: u'nld'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
shutdown sickrage, edit config and remove languages under `subtitles_languages=`, then re-add your subtitles from the gui.

**Comment by Veldkornet** [comment]
I did what you said, but it hasn't resolved the problem.
The only difference that I see is that in settings, subtitles, Dutch no longer has a flag, it's just a broken image icon. I suppose that's why 'nld' is referenced on the last line of the error (Netherlands ?)

**Comment by miigotu** [comment]
Can you go to `missed subtitle management` update subtitles that way? nld is in your db -.- I need to find a good way to make this auto-fixed.

**Comment by palmfighter** [comment]
tried the above, but doesn't fix..

**Comment by palmfighter** [comment]
O and the 2nd option, using missed subtitle management doesn't do anything...

**Comment by fernandog** [comment]
@palmfighter @Veldkornet 

shutdown sickrage, 
edit config and remove languages under subtitles_languages=
delete this folder \SickRage\cache\cheetah
go to "mass update":  update and rescan all shows

report back

**Comment by palmfighter** [comment]
thanks @fernandog running the update & rescan now.

**Comment by palmfighter** [comment]
@fernandog sorry this didn't fix it..

**Comment by Veldkornet** [comment]
Nope, me either.

**Comment by palmfighter** [comment]
any other ideas? Make a backup of the config, start fresh and import config? Would that work, or has the backup the database as well?

**Comment by palmfighter** [comment]
@fernandog if you want remote access please contact me as I can setup a remote session.

**Comment by fernandog** [comment]
@palmfighter @Veldkornet 

run in ssh, insider sickrage folder. must have sqlite3 installed

sqlite3 -cmd ".timeout 5000" sickbeard.db "select distinct subtitles from tv_episodes";

sqlite3 -cmd ".timeout 5000" sickbeard.db "select distinct subtitles from tv_shows";

post results

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/2138

**Comment by kefkekeyser** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 23:30:53) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@608c06810abb05ab6e9d07947c86d42b1b1a21c2
Link to Log: https://gist.github.com/a21cf3021bb1f94d3c3d
### ERROR
```
Thread-93 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1320, in displayShow
    return t.respond()
  File "/usr/local/sickbeard-custom/var/cache/cheetah/_usr_local_sickbeard_custom_var_SickBeard_gui_slick_interfaces_default_displayShow_tmpl.py", line 1335, in respond
    for sub_lang in [VFN(VFFSL(SL,"subtitles",True),"fromietf",False)(x) for x in VFN(VFFSL(SL,"epResult",True)["subtitles"],"split",False)(',') if VFFSL(SL,"epResult",True)["subtitles"]]: # generated from line 581, col 13
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/subtitles.py", line 70, in fromietf
    return babelfish.Language.fromopensubtitles(language)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/babelfish/language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/babelfish/converters/opensubtitles.py", line 36, in reverse
    raise LanguageReverseError(opensubtitles)
LanguageReverseError: u'nld'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by skalvaro** [comment]
Having the same issue. Here is my output of the sqlite3 commands:
```
sqlite> select distinct subtitles from tv_episodes;

dut
dut,eng
dut,eng,und
en
en,nl
en,und
eng
eng,nld
eng,nld,und
eng,und
nld
nld,und
und
sqlite> select distinct subtitles from tv_shows;
0
1
```
The empty row after the first command is indeed in the output, it is not a copy/paste error.

**Comment by palmfighter** [comment]
sqlite3 -cmd ".timeout 5000" sickbeard.db "select distinct subtitles from 
tv_episodes";

eng,nld,und
nld
eng,nld
nl,en,und
en,und
nld,und
und
eng,und
eng
nl
und,en,nl
en,nl
en,nl,pt
fr,en,nl,pt,es
fr,en,pt,es
sv,en,no,da
sv,en,nl,no,da
sv,en,und,no,da
en

sqlite3 -cmd ".timeout 5000" sickbeard.db "select distinct subtitles from 
tv_shows";
0

**Comment by kefkekeyser** [comment]
I did this:

edit config and remove languages under subtitles_languages=
delete this folder \SickRage\cache\cheetah
go to "mass update": update and rescan all shows

I'm now able to see the shows again and displayShow also works, but the icon for Dutch subtitles is replayed by an '?'

**Comment by renini** [comment]
i had the same issue, fixed changing the subtitle country names in sickbeard.db
sqlite3 sickbeard.db
select distinct subtitles from tv_episodes;
then, updated all 'old' entries, like nld and en to dut and eng
UPDATE tv_episodes SET subtitles = 'dut' WHERE subtitles = 'nld';
UPDATE tv_episodes SET subtitles = 'eng,dut' WHERE subtitles = 'eng,nld';
UPDATE tv_episodes SET subtitles = 'eng,dut,und' WHERE subtitles = 'eng,nld,und';
UPDATE tv_episodes SET subtitles = 'eng' WHERE subtitles = 'en';

now its working again

**Comment by palmfighter** [comment]
did you do an update first and when finished a rescan? or did you enable both columns at the same time before going for submit?

**Comment by palmfighter** [comment]
fixed using the updates from above! thanks @renini

**Comment by fernandog** [comment]
@palmfighter full re-scan one of the problematic tvshow and check if error happens again

**Comment by palmfighter** [comment]
don't see the problem reappearing..

**Comment by miigotu** [comment]
`I'm now able to see the shows again and displayShow also works, but the icon for Dutch subtitles is replayed by an '?'`

The flag image is just not copied to the new dir and name yet, but it is correct now.

**Comment by miigotu** [comment]
@fernandog We need someone to go through and find the missing flags and copy + rename them from images/flags/ to images/subtitles/flags/

**Comment by miigotu** [comment]
If you go into the subtitles settings and just add one letter to the input block (go through a - z one by one) you can see the flags that still need to be copied or are missing.

**Comment by fernandog** [comment]
@neoatomic can you do that please? you are the man of the icons/images/logos =)

**Comment by miigotu** [comment]
So far it seems only nld code has been popping up with this error converting, thats better than I thought it would be.

The one report of fra code is erroneous, as fra is a country code not a language code anyways.

**Comment by palmfighter** [comment]
screw the dutch ;) O sorry I am :) do all NL users need to run these commands to fix sql db?

**Comment by miigotu** [comment]
@palmfighter SQL commands are not required. You could simply do this https://github.com/SiCKRAGETV/sickrage-issues/issues/2125#issuecomment-121740934

**Comment by mstraa** [comment]
I'm french and it works with :
fra -> fr
eng,fra -> eng,fr
fra,eng -> fr,eng

I replaced und by "nothing", eng or fr.

Thanks for the quick help !

**Comment by palmfighter** [comment]
@miigotu that didn't fix it for me, so I had to go CLI and run the DB SQL commands provided here as well. More people had the same, that #2125 wasn't working

**Comment by miigotu** [comment]
One liner:
```sql
UPDATE tv_episodes SET subtitles = REPLACE(subtitles, 'nld', 'dut') WHERE subtitles LIKE '%nld%;
```

**Comment by miigotu** [comment]
As a side not, downgrading form this point is NOT RECOMMENDED after these changes.

**Comment by palmfighter** [comment]
guys, thanks for the quick help! Nice to see the community is that helpful! @miigotu you seem to be very active on the project lately, appreciated! Seems you are squashing a lot of bugs!

**Comment by miigotu** [comment]
And stirring up some confusion and breakage it seems sometimes lol. It is bound to happen from time to time with such major changes though.

**Comment by Modjor** [comment]
Thanks fernandog for redirecting me to this issue. 
So the issue also exists with French subtitles. Some "fra", "fre", "en" and "und" were present in my tv_episodes table. I ran the following sqlite queries:

UPDATE tv_episodes SET subtitles = 'fr' WHERE subtitles = 'fra';
UPDATE tv_episodes SET subtitles = 'eng,fr' WHERE subtitles = 'eng,fra';
UPDATE tv_episodes SET subtitles = 'eng,fr' WHERE subtitles = 'eng,fra,und';
UPDATE tv_episodes SET subtitles = 'eng' WHERE subtitles = 'en';
UPDATE tv_episodes SET subtitles = 'fr' WHERE subtitles = 'fra';
UPDATE tv_episodes SET subtitles = 'fr' WHERE subtitles = 'fre';

I'm sure you can do something much more clever - but my sql skills are quite limited, especially at this time of night ;)
I did not have to update show after that, just cleaning the var/cache/cheetah directory and restart sickrage.

Thanks!

**Comment by neoatomic** [comment]
@fernandog Submitted some missing flags. However unless you are a language expert and know all the flags, its impossible to add all the missing ones. Will try to add the most know/uses languages.

**Comment by miigotu** [comment]
Update to latest and the subtitles codes in your DB should be automatically fixed.

**Comment by Veldkornet** [comment]
@neoatomic Since you're busy updating the flags, could you update the flag for Afrikaans? It should be the flag of South Africa, and not... what ever it is at the moment...

**Comment by miigotu** [comment]
@Veldkornet can you find the flag in gui/slick/images/flags/ or gui/slick/images/subtitles/flags/ and give us the name of it? That is the easiest way to help.

**Comment by Veldkornet** [comment]
@miigotu 
Incorrect Flag -> https://github.com/SiCKRAGETV/SickRage/blob/master/gui/slick/images/subtitles/flags/afr.png

Correct Flag-> http://www.worldweatheronline.com/flags.ashx?isocode=ZA

The subtitle shortname is correct (afr), it's just using the flag of Afghanistan at the moment. 

I couldn't find the 2 letter country flag in https://github.com/SiCKRAGETV/SickRage/tree/master/gui/slick/images/flags
Although, the country code would be ZA, if it needs to be added there too.

**Comment by neoatomic** [comment]
@Veldkornet Fixed that for you. Should be corrected with the next update.

**Comment by Veldkornet** [comment]
Awesome, thanks! ;)
