### ISSUE TITLE
Permissions on downloaded subtitles

### ISSUE THREAD

**Issue by skalvaro** [SiCKRAGETV/sickrage-issues#2126]
SR Version: 	BRANCH: (master) / COMMIT: (2bfdb0a92083aa969fbfada92471850379a01045)
SR User:	sickrage
SR Locale:	('en_US', 'UTF-8')
SR Config file:	/var/lib/sickrage/config.ini
SR Database file:	/var/lib/sickrage/sickbeard.db
SR Cache Dir:	/var/lib/sickrage/cache
SR Log Dir:	/var/log/sickrage
SR Arguments:	['--daemon', '--nolaunch', '--pidfile=/var/run/sickrage/sickrage.pid', '--datadir=/var/lib/sickrage']
Python Version:	2.7.3 (default, Mar 11 2013, 22:38:13) [GCC 4.4.7 20120313 (Red Hat 4.4.7-3)]
OS: Linux media.*********.lan 2.6.32-504.23.4.el6.x86_64 #1 SMP Tue Jun 9 20:57:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

No errors are logged.

Permissions on newly downloaded subtitiles are only set for the owner and not the group.
It seems to me that inconsistencies exist in handling the creation of files and permissions.

I have different users setup for the different programs/scripts but all belong to the same group 'multimedia', that is why in my case permissions on group level need to be correct.

My show root folder permissions are set to 2770, file permissions should be 660.
Newly downloaded episode files are set correctly to 660.
Newly downloaded subtitle files get 600 as permissions while these should be 660 as currently other users (like plex user) can't read the file.

When adding a new show or downloading episodes the folders and files get the correct permissions:
```
2015-07-14 22:52:09 DEBUG    Thread-73 :: Setting permissions for /var/multimedia/series/The X-Files/Season 07 to 2770 as parent directory has 2770
```
Also the .nfo created by sickrage gets the correct permissions set in the show folder:
```
-rw-rw----. 1 sickrage multimedia  1589 Jul 11 22:56 tvshow.nfo
```
When subtitles are downloaded these get the incorrect 600 permissions:
```
-rw-------. 1 sickrage multimedia      32403 Jul 15 01:33 The X-files - S07E22 - Requiem - [720p WEB-DL].en.srt
-rw-rw----. 1 sickrage multimedia 1027286938 Jul 15 01:32 The X-files - S07E22 - Requiem - [720p WEB-DL].mp4
-rw-------. 1 sickrage multimedia      24434 Jul 15 01:33 The X-files - S07E22 - Requiem - [720p WEB-DL].nl.srt
```

It seems to have started from 10th of juli, but I'm not sure about it.

Of course I could run a post processing script to set the permissions but as it is the subtitle downloads I would have to run it as a cron job and set all permissions as wanted.

So the question is why are the permissions set correctly in one part of the program, like adding new shows will create the tvshow.nfo file with correct permissions and post-processing will move the files also with correct permissions, but set differently (incorrect imho) when downloading subtitles.

**Comment by miigotu** [comment]
I'll see what I can do, but this is an upstream problem.

**Comment by miigotu** [comment]
@skalvaro this is only evident because of a misconfiguration. Yes, we do fix permissions on other files, but only as a workaround for misconfigured setups.
1. What group is set for running SickBeard.py in your init script?
2. Are you writing over a share?

```bash
dusted@PC:~/Projects/SickRage $ ls Shows/Game\ of\ Thrones/Season\ 05/* -l
-rw-rw-r-- 1 dusted dusted 1296279700 Jul  1 10:08 Shows/Game of Thrones/Season 05/Game of Thrones - S05E02 - The House of Black and White.mkv
-rw-rw-r-- 1 dusted dusted      50112 Jul 14 04:08 Shows/Game of Thrones/Season 05/Game of Thrones - S05E02 - The House of Black and White.pt.srt
-rw-rw-r-- 1 dusted dusted      57823 Jul 13 08:39 Shows/Game of Thrones/Season 05/Game of Thrones - S05E03 - High Sparrow.en.srt
-rw-rw-r-- 1 dusted dusted  348693872 Jul  1 14:15 Shows/Game of Thrones/Season 05/Game of Thrones - S05E03 - High Sparrow.mp4
-rw-rw-r-- 1 dusted dusted      48538 Jul 13 08:39 Shows/Game of Thrones/Season 05/Game of Thrones - S05E03 - High Sparrow.pt.srt
-rw-rw-r-- 1 dusted dusted      39853 Jul 13 07:41 Shows/Game of Thrones/Season 05/Game of Thrones - S05E04 - Sons of the Harpy.en.srt
-rw-rw-r-- 1 dusted dusted  358482656 Jul  5 21:06 Shows/Game of Thrones/Season 05/Game of Thrones - S05E04 - Sons of the Harpy.mp4
-rw-rw-r-- 1 dusted dusted      39122 Jul 14 02:46 Shows/Game of Thrones/Season 05/Game of Thrones - S05E04 - Sons of the Harpy.pt.srt
-rw-rw-r-- 1 dusted dusted      35631 Jul 13 08:39 Shows/Game of Thrones/Season 05/Game of Thrones - S05E10 - Mother's Mercy.en.srt
-rw-rw-r-- 1 dusted dusted     140968 Jul  7 08:23 Shows/Game of Thrones/Season 05/Game of Thrones - S05E10 - Mother's Mercy.mp4
-rw-rw-r-- 1 dusted dusted      35577 Jul 14 02:44 Shows/Game of Thrones/Season 05/Game of Thrones - S05E10 - Mother's Mercy.pt.srt
```

**Comment by skalvaro** [comment]
@miigotu 
1. What group is set for running SickBeard.py in your init script?
```
[skalvaro@media ~]$ cat /etc/sysconfig/sickrage
SB_USER=sickrage
[root@media ~]# ps -aef | grep sickrage
sickrage   594     1  3 07:34 ?        00:12:55 /usr/bin/python2.7 /var/lib/sickrage/SickBeard.py --daemon --nolaunch --pidfile=/var/run/sickrage/sickrage.pid --datadir=/var/lib/sickrage
[skalvaro@media ~]$ groups sickrage
sickrage : multimedia
```
2. Are you writing over a share?
No, not writing over a share.

Has something in the code changed? I can't remember having this issue until lately.

What do you mean with upstream issue? Which component/provider would be the 'upstream' in this case?
[Hope it is not the notorious layer 8 :-)]

**Comment by miigotu** [comment]
`## SB_GROUP=        #$RUN_GROUP, group to run sickrage under, the default is sickrage`

**Comment by miigotu** [comment]
Also, show folder should be 775 or 770 (775 is easier to not have permissions problems.)

**Comment by miigotu** [comment]
ans season folder *

**Comment by miigotu** [comment]
No, when I said upstream, I was making an assumption that you were running SR as user sickrage and group multimedia. It should be creating files as the same user/group as the main program is run, if it is not we have issues. Also, by default the permissions of SickRage.py are 775, did you change that? those permissions permeate.

**Comment by miigotu** [comment]
I consider this a support/question, so we will fix your problem first, and then I will do the workaround so I can avoid this question in the future. I just soooo hate hacking around poorly configured installs in code.

**Comment by fernandog** [comment]
@miigotu if we do the parent checking while setting up folders, can't we also check for permissions issues? If parent or permission error, we don't let user save!

**Comment by miigotu** [comment]
@fernandog I'm pretty sure his parent is right, just SR is started with the wrong group, so it creates files as same group as SickRage is run as, and by default with a maximum of the same permissions SickRage.py has.

**Comment by fernandog** [comment]
but can't we check this too? sickrage.py permission against folder permission?

**Comment by miigotu** [comment]
@fernandog we shouldn't need to check it, you clone the source, and it already has the correct permissions. Users have to break it by changing permissions. Most of this issue is an isolated case, or we would have had this problem every day all day.

On the other hand, I could fixSetGroupID on all of the subtitles, but I want to avoid setting permissions on anything (it isn't necessary anywhere unless users are changing permissions of the source, even though we do it on downloads)

**Comment by skalvaro** [comment]
@miigotu @fernandog Thanks for looking into this.

Here is what I got so far:
SB_GROUP is from the debian init file, I'm running CentOS and the daemon function used in the init script does not accept group flags. I tried to use the solution as given on stackexchange but this did not change anything.

Show folder permissions is 2770 so these should be ok.

sickrage is running as user sickrage and that user has only 1 group assigned, that being multimedia.
The pidfile is created as below which seems to indicate the sickrage:multimedia as user:group.
```
-rw-------. 1 sickrage multimedia 5 Jul 15 21:07 sickrage.pid
```

I seem to have changed the permissions of SickBeard.py back in december 2014 (don't know why).
Stopped sickrage.
Changed permissions on SickBeard.py to the suggested 755.
Restarted sickrage.
Unfortunately this did not change anything.

When doing all these checks/tests I got an update notice, and updated but now I'm struggling with #2125.
As suggested there I removed all subtitle languages and the system is now doing the update and rescan. This can take some time (100+ shows and 9+TB) so I will have to wait until that one finishes before I can try to re-enable subtitle downloads.

references:
http://unix.stackexchange.com/questions/3376/how-do-i-set-the-group-gid-of-a-process-im-about-to-launch

**Comment by miigotu** [comment]
can you check the man pages on your machine for daemon and see if there is a --group option?

```bash
man daemon
/--group
```

**Comment by miigotu** [comment]
Try adding:

RUN_GROUP=${SR_GROUP-sickrage}

under where the /etc/default/sickrage is sourced,

then add to the daemon command (just after the --user):
--group=${RUN_GROUP}

See if that works.

**Comment by skalvaro** [comment]
@miigotu Thanks for looking into this. I will try your suggestion later today.
```
[root@media ~]# man daemon
No manual entry for daemon
```

**Comment by miigotu** [comment]
@skalvaro sorry, I did more reading up on freebsd, the daemon function is defined in /etc/init.d/functions on your system.

That superuser post suggests to try editing the daemon line in your init script to start like this:
`runuser -g ${SB_GROUP-sickrage}; daemon`

Either way I will start setting the group id on the subtitles soon, as a hack around this.

**Comment by skalvaro** [comment]
I tried changing the init script once more but that did not work, must have done something wrong.
I changed the permissions of python files on my SR install by comparing with a newly downloaded SR and restarted SR but it did not help.
 I'm currently using a cron job to check and if needed change the permissions.

**Comment by miigotu** [comment]
@skalvaro When I get around to it I will fix the group, but the permissions we'll have to see. If SickBeard.py is 755, all files should be created 644 or 755 by SR. Otherwise you have a umask issue somewhere.

**Comment by stappel** [comment]
same issue here. Have been using SickBread/SickRage for over an year. Never had any problems with subtitle files and permissions before. Only for the last week or so there is a permission problem.
Files are created with to restricted rights,

actions:
- set permissions on SickBeard.py to 775, restarted SickRage.
- removed some srt file and let Sickrage download it again:

[quote]
-rw-------    1 sickbear users        46425 Jul 21 08:44 Extant.S02E03.720p.HDTV.DD5.1.x264-SNEAkY.en.srt
-rw-rw-rw-    1 admin    users    2106327821 Jul 16 08:33 Extant.S02E03.720p.HDTV.DD5.1.x264-SNEAkY.mkv
[/quote]

Did not fixed it. Running on a Synology DS414.
SR Version: 	BRANCH: (master) / COMMIT: (ac27935188e351a7ffd869ff1555767987f62ce3)

**Comment by miigotu** [comment]
Hope that works, because it is all I can do.

**Comment by stappel** [comment]
Found the problem. Commit https://github.com/SiCKRAGETV/SickRage/commit/a2fc21dc47afdd299fe78485711f19db265062e9 (7 days ago) removed the helpers.chmodAsParent(subs_new_path).
I think that was an oversight.

**Comment by miigotu** [comment]
Nope, that was for the subtitle folder, when I was creating it, which it doesnt do anymore.

I have already fixed this in develop.

**Comment by skalvaro** [comment]
@miigotu I noticed that is was already in master branch so I updated and tested. I can confirm it works now. Thanks for all the effort and time.
```
SR Version: 	BRANCH: (master) / COMMIT: (eb6f4d46709f4b3dd337c56573feb5bac27b10a9) ```
