### ISSUE TITLE
Shows not downloaded put in "skipped"

### ISSUE THREAD

**Issue by Psychoteur** [SiCKRAGETV/sickrage-issues#2127]
Ok, I don't why my post was closed. 

My shows are in "wanted" by default. Sickrage is running for 6 months with that configuration.
I used much of my time doing select "skipped" for the all seasons I don't want. 

Now, I've destroy everything since sickrage seems on the fritz. We'll see what happens.

**Comment by miigotu** [comment]
Closed doesn't mean we can't see it.
