### ISSUE TITLE
SickRage downloading wrong season pack for HDBits and BTN

### ISSUE THREAD

**Issue by hennning** [SiCKRAGETV/sickrage-issues#2128]
SickRage is downloading the wrong season pack torrent. I have tried it on both Freenas and now on Windows, same issue. On Freenas I used Transmission and on Windows i'm using Deluge.

It seems to be the same issue as #1579 . Blackhole is downloading the correct one.
I wrote my issue in that ticket but just now realized that it's been closed so you probably won't see it there.

BRANCH: (master) / 
COMMIT: (608c06810abb05ab6e9d07947c86d42b1b1a21c2) 
Operating system: Windows 2012 R2 (And before also on Freenas, not using that anymore)
Python: 2.7

I choose an entire season of a series, let's say Homeland Season 3 and change it to Wanted.
It tells me it's downloading a 720p version from -CHD as I wanted to but instead it downloads a 1080p from -FraMeSToR at 108GB.

Logfile: https://gist.github.com/hennning/0277509161dddc83a7f9

**Comment by fernandog** [comment]
Because 1080p is better than 720p.
Change you quality settings to custom to only get 720p or add FraMeSToR to ignored words.

**Comment by hennning** [comment]
I have the preferred quality set to 720p in the show. Homeland --> Edit --> Quality. This should only download 720p versions, right?

Also the message SickRage gives me in the down right corner clearly says it's downloading a 720p version of Season 3 but when I enter Deluge it's downloading a 1080p version.

I have attached screenshots for you
![sickrage_error01](https://cloud.githubusercontent.com/assets/13292619/8697750/c7920290-2af7-11e5-8446-1d8f6d41eb43.jpg)
![sickrage_error02](https://cloud.githubusercontent.com/assets/13292619/8697751/c7943722-2af7-11e5-9858-0ccdc2d92120.jpg)

**Comment by hennning** [comment]
Also, if you read the log it clearly says 
2015-07-15 12:34:56 DEBUG    SEARCHQUEUE-BACKLOG-247897 :: Homeland.S03.1080p.BluRay.Remux.DTS-HD.MA5.1.H.264-FraMeSToR is a quality we know we don't want, rejecting it

**Comment by miigotu** [comment]
Just because an issue is closed does not mean you cannot ping a team member form it, or comment here and we can see it. Please don't keep opening issue after issue because you think we can't see closed issues.

**Comment by hennning** [comment]
Ok, I couldn't see it on the issues list anymore so I guessed you would not see any updates in it.

**Comment by miigotu** [comment]
If you remove `is:open` from the search bar on the issues page you see everything.

**Comment by miigotu** [comment]
Also, we get notifications whenever someone responds in an issue and we haven't responded yet (when we are a part of the conversation already or someone does @miigotu).

**Comment by hennning** [comment]
So, anything new here? Just wondering

**Comment by miigotu** [comment]
Can't reproduce, we need to wait for more reports or for one of us to stumble across the bug causing it.

**Comment by hennning** [comment]
Let me know if I can assist with anything
