### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by ripper1967** [SiCKRAGETV/sickrage-issues#2130]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@608c06810abb05ab6e9d07947c86d42b1b1a21c2
Link to Log: https://gist.github.com/03df5acb46651dfc2947
### ERROR
```
Thread-28 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\Users\rusty\SickRage\sickbeard\webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "C:\Users\rusty\SickRage\sickbeard\webserve.py", line 1320, in displayShow
    return t.respond()
  File "C:\Users\rusty\SickRage\cache\cheetah\_Users_rusty_SickRage_gui_slick_interfaces_default_displayShow_tmpl.py", line 704, in respond
    info_flag = VFN(VFN(VFFSL(SL,"subtitles",True),"fromietf",False)(VFFSL(SL,"show.lang",True)),"alpha3",True)
  File "C:\Users\rusty\SickRage\sickbeard\subtitles.py", line 70, in fromietf
    return babelfish.Language.fromopensubtitles(language)
  File "C:\Users\rusty\SickRage\lib\babelfish\language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "C:\Users\rusty\SickRage\lib\babelfish\converters\opensubtitles.py", line 29, in reverse
    if opensubtitles in self.from_opensubtitles:
  File "C:\Python27\lib\_abcoll.py", line 388, in __contains__
    self[key]
  File "C:\Users\rusty\SickRage\lib\babelfish\converters\__init__.py", line 46, in __getitem__
    return self._store[key.lower()][1]
AttributeError: 'NoneType' object has no attribute 'lower'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Please stop SR, edit config.ini, remove the line `subtitles_languages=` and start SR, then set your languages again, and go to `missed subtitle management` and see if you can rescan your subtitles.

**Comment by ripper1967** [comment]
i dont use subtitles.

**Comment by fernandog** [comment]
check it anyway

**Comment by miigotu** [comment]
`info_flag = VFN(VFN(VFFSL(SL,"subtitles",True),"fromietf",False)(VFFSL(SL,"show.lang",True)),"alpha3",True)`

I see, show lang is empty??

**Comment by ripper1967** [comment]
you mean under subtitles section? to rescan missing subtitles

**Comment by miigotu** [comment]
@ripper1967 ignore my previous instructions, I see now that the show info language is empty, and I don;t know how this is possible.

@fernandog how could show info language ever be empty?

**Comment by fernandog** [comment]
bad conversion between SickBeard database to SickRage db ?

**Comment by miigotu** [comment]
@ripper1967 did you just come from sick beard and not start with a fresh database?

**Comment by ripper1967** [comment]
no

**Comment by miigotu** [comment]
try mass update and rescan all shows, see if that helps.

**Comment by ripper1967** [comment]
ok will do, will let ya know.

**Comment by miigotu** [comment]
Also, try deleting this folder first: `C:\Users\rusty\SickRage\cache\cheetah`

**Comment by ripper1967** [comment]
will try that

**Comment by fernandog** [comment]
@ripper1967 so?

**Comment by ripper1967** [comment]
well its still updating have like 500 shows lol, but i would close it for now, it was coming up pretty quickly the first time i tryed it, i just did a mass update rescan and update with out deleting the folder cache\cheeta as i din`t notice you had said to delete it. so i  then deleted the folder and doing the update and rescan, it hasnt come up so far...but its still updating

**Comment by ripper1967** [comment]
ok can be closed no errors.

**Comment by Aesculapius** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-57-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@fe0111aa88dc6d65177f339e643ca971405f926f
Link to Log: https://gist.github.com/1708681bf98d0e74e49d
### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "/home/laurens/.sickrage/sickbeard/tv.py", line 1469, in downloadSubtitles
    foundSubs = subliminal.download_best_subtitles([video], languages=languages, providers=providers, single=not sickbeard.SUBTITLES_MULTI, hearing_impaired=False)
  File "/home/laurens/.sickrage/lib/subliminal/api.py", line 88, in download_best_subtitles
    for subtitle, score in sorted([(s, s.compute_score(video)) for s in video_subtitles],
  File "/home/laurens/.sickrage/lib/subliminal/subtitle.py", line 131, in compute_score
    initial_matches = self.compute_matches(video)
  File "/home/laurens/.sickrage/lib/subliminal/providers/addic7ed.py", line 45, in compute_matches
    if video.title and self.title.lower() == video.title.lower():
AttributeError: 'NoneType' object has no attribute 'lower'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by WebSpider** [comment]
Hi. We have encountered this issue before. Please read the solution here: https://github.com/SiCKRAGETV/sickrage-issues/issues/2130

**Comment by Aesculapius** [comment]
Well I've followed that advice and deleted the line about subtitle_languages. After that, I cannot startup sickrage anymore. Without throwing an error, I cannot find the process with `ps aux |grep sickrage`.

Or am I having a different issue?
