### ISSUE TITLE
Scene Numbering option ignored when creating new show.

### ISSUE THREAD

**Issue by Yogarine** [SiCKRAGETV/sickrage-issues#2131]
When adding a new show (i.e. Steven Universe), the fact that I haven't selected "Scene Numbering" is ignored. After adding the show the "Scene Numbering" option is enabled anyway.

After that, even when I disable the option by editing the show, the post-processor will still match episodes by scene numbering.

I've been having this issue for a while now. Not sure since when but it has been months.

See this gist for debug logs:
https://gist.github.com/Yogarine/d92b07ca2f788615299f

Current Version:
commit 608c06810abb05ab6e9d07947c86d42b1b1a21c2
Merge: 2bfdb0a 743e7d3
Author: Dustyn Gibson <miigotu@gmail.com>
Date:   Tue Jul 14 22:45:40 2015 -0700

    Merge branch 'develop'

**Comment by fernandog** [comment]
changing setting "Scene Numbering" needs full show update

**Comment by miigotu** [comment]
`After adding the show the "Scene Numbering" option is enabled anyway.`
Because SR automagically knows if this series' releases are released according to scene numbering. If you want to change it after, then change it, save the show, and full update on the show.

**Comment by Yogarine** [comment]
Ok, I performed a "Force Full Update" after disabling "Scene Numbering", and the episodes still get matched incorrectly.

I added two additional log excerpts to the gist:
https://gist.github.com/Yogarine/d92b07ca2f788615299f

**Comment by miigotu** [comment]
Steven Universe is not using scene numbering there. There are 49 episodes in season 1.

The releases you are getting are named wrong, or are scene numbered.

You tell it to not use scene numbering, so for example:
http://thetvdb.com/?tab=episode&seriesid=270701&seasonid=616370&id=5276628&lid=7

And SR names it as Historical Friction, correctly.

I think you misunderstand what scene numbering is.

**Comment by miigotu** [comment]
Many complete series packs have wrong names, because people use quirky renamers. Especially cartoons and older ones. They might be named according to DVD order ^

**Comment by Yogarine** [comment]
<img width="1195" alt="screenshot 2015-07-15 14 49 52" src="https://cloud.githubusercontent.com/assets/193043/8698739/cd2e6bcc-2b00-11e5-80b4-d6b9170d3062.png">
Here you can see the episodes, with their names and scene numbering.
Episode 17 and 18 are green because they were identified incorrectly.

The file names are:
Steven.Universe.S02E14.Cry.for.Help.720p.WEB-DL.AAC2.0.H.264-iT00NZ.mkv
Steven.Universe.S02E15.Keystone.Motel.720p.WEB-DL.AAC2.0.H.264-iT00NZ.mkv

As you can see these files use normal release numbering.

(Besides, Scene Releases 2x14 and 2x15 - S02E17 and S02E18 according to normal numbering - aren't even out yet.)

The only possible explanation is that the posts processor is ignoring this:
<img width="180" alt="screenshot 2015-07-15 14 57 51" src="https://cloud.githubusercontent.com/assets/193043/8698909/dea838a0-2b01-11e5-8e6a-29b131c24b73.png">

**Comment by Yogarine** [comment]
Just to be clear: this isn't specific to these episodes, other episodes with scene numbering have the same problem. These two are just an easy test case.

**Comment by miigotu** [comment]
Because the files are scene numbered, and you are trying to force them to non scene numbers. You don't understand we aren't using scene or non scene for renaming scene to normal, only to properly detect air dates and episode titles.

**Comment by Yogarine** [comment]
miigotu, The files are _not_ scene numbered. The scene numbers for these episodes would be 2x11 and 2x12.

Simply look at the the episode names in the list and in the files.
We're talking about hese episodes:
S02E14 - "Cry for Help": http://thetvdb.com/?tab=episode&seriesid=270701&seasonid=616370&id=5276619&lid=7
S02E15 - "Keystone Motel": http://thetvdb.com/?tab=episode&seriesid=270701&seasonid=616370&id=5276620&lid=7

As you can see the filenames of these episodes match both the episode number and the episode name.

**Comment by miigotu** [comment]
I'll test it myself when I get time. I really can't see how this is not working without mass public outcry from our 5000+ users but its possible I guess.

Other things are on the front burner for now though

**Comment by miigotu** [comment]
Good news. I found and fixed 3/4 of the problem. (Not committing until it is finished)

![image](https://cloud.githubusercontent.com/assets/390379/8702756/a546631c-2ace-11e5-8544-1fda09cbd780.png)

**Comment by miigotu** [comment]
Still need to fix this part:
`When adding a new show (i.e. Steven Universe), the fact that I haven't selected "Scene Numbering" is ignored. After adding the show the "Scene Numbering" option is enabled anyway.`

**Comment by Yogarine** [comment]
Awesome! Glad too this will be fixed soon, it has been bugging me for quite a while.

By the by, I wouldn't mind if you commit the Post Processing part separate from the Show Adding part.

**Comment by miigotu** [comment]
There is a branch issue-2131 with the "fix", but I don;t know if this is going to break other things yet, still need to think more about it and have it tested. 

So much potential for blowback here. Like, is there situations where some people don't have a show marked as scene numbering but sites have them released with scene numbering???? I don't want wrong episodes snatched and added as the wrong episode.

**Comment by Yogarine** [comment]
I guess it's one or more of the following:
1. people don't notice their episodes are messed up
2. not that much popular shows have scene numbering
3. the sources are scene numbered anyway
4. this issue is specific to certain shows, like Steven Universe (Haven't looked at the branch yet, so not sure what the problem was to begin with.)

**Comment by BenBeyond** [comment]
Just to add my 2 cent to this conversation, I am having the exact same problem as Yogarine with shows like Steven Universe and Star Wars Rebels.  I have posted a couple of issues about it too, but was not able to explain myself as well as Yogarine. 

Just wanted to add my name to the list so it doesn't seem like an isolated issue...

I look forward to getting the fix when it is released.

**Comment by miigotu** [comment]
I also found the other part of the problem BTW, just scared the changes will make some other problems

**Comment by miigotu** [comment]
I've decided to make the PR for this change, without the change for the show to be able to be added as the default status when an xem map exists.

I intend to add a note to the "scene numbering" checkbox when adding a show that says it may be overriden if a scene numbering exists, but you can go back and edit the show and set it how you want.

The only issue here is that the setting reverts to scene numbering if xem has a mapping if you full update on the show.

For now i think my fix is sufficient:

https://github.com/SiCKRAGETV/SickRage/pull/2110

**Comment by Yogarine** [comment]
I can confirm it's fixed in the develop branch.
