### ISSUE TITLE
[APP SUBMITTED]: near "WHERE": syntax error

### ISSUE THREAD

**Issue by ZulDemon** [SiCKRAGETV/sickrage-issues#2133]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@4d026d72e123a659c68049fec53ec22e2e1aab15
Link to Log: https://gist.github.com/8756305e052a2fe5bdd5
### ERROR
```
EVENT-QUEUE :: DB error: near "WHERE": syntax error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by ZulDemon** [comment]
Debug logs: http://pastebin.com/jVuPtj3H

I've tried multiple re-installs/restores, but I continue to get this error whenever shutting down. I'm guessing my DB is hosed.

**Comment by fernandog** [comment]
@ZulDemon save your config and move your databases outside SR folder. start SR

**Comment by ZulDemon** [comment]
I got it to work by:
Saving the dbs' to a backup folder.
Replacing all the files in c:\sickrage with a current master.
Manually editing the config.ini with:
     branch = master
     cur_commit_hash = [old hash]
     cur_commit_branch = master
Ran the update and everything seems to be ok now. Guess I got a little click happy with the submit button. Thanks. Keep up the good work.

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:34:55) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-26-generic-i686-with-Ubuntu-15.04-vivid**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@f15adac877b6f4c7f434f734ecf6824e87675ddc
Link to Log: https://gist.github.com/8c22004e0f5d68088b64
### ERROR
```
EVENT-QUEUE :: DB error: near "WHERE": syntax error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by duramato** [comment]
i am getting this everytime i update

**Comment by rrd911** [comment]
### INFO
Python Version: **2.7.6 (default, Apr  3 2014, 09:45:36) [GCC 4.5.3]**
Operating System: **Linux-3.10.71-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@37914618686ee70479da0fa4b2cca851fa49c5e2
Link to Log: https://gist.github.com/34742ec5e8b49a125efe
### ERROR
```
EVENT-QUEUE :: DB error: near "WHERE": syntax error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by scorpius023** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  4 2015, 00:34:17) [GCC 4.2.0]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@6d7fd7062f8d827f88c53994db696d81270c8354
Link to Log: https://gist.github.com/563d0418911727128ffb
### ERROR
```
EVENT-QUEUE :: DB error: near "WHERE": syntax error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by nigewri** [comment]
### INFO
Python Version: **2.7.10 (default, Jul 14 2015, 19:46:27) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]**
Operating System: **Darwin-14.5.0-x86_64-i386-64bit**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@56fd7a9447fb0e72398568be737c1f00b5bb07f4
No Log available with ERRORS: 
### ERROR
```
EVENT-QUEUE :: DB error: near "WHERE": syntax error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by nigewri** [comment]
### INFO
Python Version: **2.7.10 (default, Jul 14 2015, 19:46:27) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]**
Operating System: **Darwin-14.5.0-x86_64-i386-64bit**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@56fd7a9447fb0e72398568be737c1f00b5bb07f4
No Log available with ERRORS: 
### ERROR
```
EVENT-QUEUE :: Exception generated in thread EVENT-QUEUE: near "WHERE": syntax error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
No clue to this error?

Strange the DB level log does not show anymore the queries/SQL

**Comment by ROpdebee** [comment]
### INFO
Python Version: **2.7.10 (default, Aug 22 2015, 20:33:39) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)]**
Operating System: **Darwin-15.0.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@56fd7a9447fb0e72398568be737c1f00b5bb07f4
Link to Log: https://gist.github.com/7a54467f2ec5298f583e
### ERROR
```
SHOWQUEUE-ADD :: DB error: near "WHERE": syntax error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by ROpdebee** [comment]
### INFO
Python Version: **2.7.10 (default, Aug 22 2015, 20:33:39) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)]**
Operating System: **Darwin-15.0.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@56fd7a9447fb0e72398568be737c1f00b5bb07f4
Link to Log: https://gist.github.com/ffd871510a0f8863697c
### ERROR
```
SHOWQUEUE-ADD :: Error saving the show to the database: near "WHERE": syntax error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by ROpdebee** [comment]
### INFO
Python Version: **2.7.10 (default, Aug 22 2015, 20:33:39) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)]**
Operating System: **Darwin-15.0.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@56fd7a9447fb0e72398568be737c1f00b5bb07f4
Link to Log: https://gist.github.com/18c7cb8a05f34494aca3
### ERROR
```
SHOWQUEUE-ADD :: DB error: near "WHERE": syntax error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
