### ISSUE TITLE
WebAPI Fatal Error on CMD_SickBeardSearchTVDB

### ISSUE THREAD

**Issue by Hiltronix** [SiCKRAGETV/sickrage-issues#2134]
When doing a search for a show name using the SickRage WebAPI, non words cause fatal error results.

Examples:

https://192.168.0.115:8080/api/xxx/?cmd=sb.searchtvdb&lang=en&name=xxx
https://192.168.0.115:8080/api/xxx/?cmd=sb.searchtvdb&lang=en&name=cancan
https://192.168.0.115:8080/api/xxx/?cmd=sb.searchtvdb&lang=en&name=aaaaaaaaaaa

Results are:

	{
	    "data": {
	        "args": [], 
	        "error_msg": "'unicode' object has no attribute 'values'", 
	        "kwargs": {
	            "lang": "en", 
	            "name": "cancan"
	        }
	    }, 
	    "message": "SickRage encountered an internal error! Please report to the Devs", 
	    "result": "fatal"
	}

I think it should return the same results as when the search comes up empty.
Example:
https://192.168.0.115:8080/api/xxx/?cmd=sb.searchtvdb&lang=en&name=can you find what i want

	{
	    "data": {
	        "langid": 7, 
	        "results": []
	    }, 
	    "message": "", 
	    "result": "success"
	}

I'm running Python 2.7 64 bit.
SR Version: BRANCH: (master) / COMMIT: (2bfdb0a92083aa969fbfada92471850379a01045)
I don't have a suggested fix.
Thank you.

**Comment by fernandog** [comment]
@Hiltronix post logs in SR UI (you need to have debug enable in advanced settings) and log level DEBUG. post in gist

**Comment by Hiltronix** [comment]
Debug log segment with error:
https://gist.github.com/Hiltronix/888c0104b627a90caaea

**Comment by fernandog** [comment]
@MGaetan89 as you are changing webapi can you check this please?

**Comment by MGaetan89** [comment]
@fernandog I will have a look. I also had this issue, so I will try again to reproduce it and fix it.

**Comment by MGaetan89** [comment]
Seems to be working in the `development` branch.
But it is still broken in `master`.

**Comment by fernandog** [comment]
Strange. No chances in code and got fixed?

**Comment by MGaetan89** [comment]
Just check again, and I don't see anything that could have fixed it in the latest commit.
I will check again to be sure.

**Comment by MGaetan89** [comment]
I tried again:
- In my development environnement (`develop` branch) it is working fine
- In my real environnement (`master` branch) it is also working fine
I used @Hiltronix examples to try. Maybe it got fix with one of the unicode issue that was fixed recently?

@Hiltronix do you still have the issue?

**Comment by Hiltronix** [comment]
Yes, I can confirm it's now working as expected for me as well, on BRANCH: (master) / COMMIT: (ac27935188e351a7ffd869ff1555767987f62ce3) 

Thank you.
