### ISSUE TITLE
Country Flags in history page missing

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2135]
On the latest dev version country flags do not appear on the history page and on a shows page (the lang of the show) but on the showsp page the country flags of the subs do work

**Comment by miigotu** [comment]
Known issue, working through more important things first.

**Comment by MGaetan89** [comment]
The flag of the lang of the show is working again.
But I have nothing in my history to check the first point.

**Comment by duramato** [comment]
Yes i can also confirmado the flag on the shows page is working back again ,But on the history page isnt yet .

**Comment by fernandog** [comment]
@duramato please update and report back

**Comment by duramato** [comment]
@fernandog its now fixed ,thanks
