### ISSUE TITLE
Episodes named "HD.TV" are marked Unknown instead of HDTV.

### ISSUE THREAD

**Issue by ctrlbrk42** [SiCKRAGETV/sickrage-issues#2137]
Recently a lot of my shows are being named "HD.TV" and therefore are being skipped/not snatched or marked as "unknown" quality, instead of the normal HDTV (no dot).  How can I correct this so that the quality "HD.TV" will match "HDTV"?

I am using the latest master.  Below is a screenshot demonstrating the issue, but this is happening on many shows.

![2015-07-15_14-22-06](https://cloud.githubusercontent.com/assets/1001097/8707695/f77cd1b0-2afc-11e5-996a-2a08d080b708.png)

**Comment by ctrlbrk42** [comment]
I should point out the downloaded episodes in this example were with SB.  When I switched to SR, the download "names" for HDTV quality were no longer being matched correctly.

**Comment by miigotu** [comment]
We fixed it so that our renamer does not rename files to `HD.TV`

If you are using linux:
You can remove the show, then in terminal:

To see what will be renamed:
`find YOUR_SHOWS_ROOT -name '*HD.TV*' -exec rename -n -v 's/HD.TV/HDTV/' {} +`
To actually do the rename:
`find YOUR_SHOWS_ROOT -name '*HD.TV*' -exec rename -v 's/HD.TV/HDTV/' {} +`

**Comment by miigotu** [comment]
Actually you don;t even need to remove it from SR, just do the commands and then rescan the show.

**Comment by ctrlbrk42** [comment]
Hi, I may have done a poor job explaining this.  All the 'wanted' episodes in my screenshot, if I click search, no results are found.  I assumed this is because the uploaders are naming them "HD.TV" (with the dot) and therefore SR is not detecting it as HDTV quality.

All of the existing downloads in the screenshot were downloaded by SB, not SR.  SB detected them as HDTV resolution, but SR does not.

My question is, how can I modify the quality parameters so that "HD.TV" with the dot is included in "HDTV" resolution?  That would seem to be the required fix from my understanding.  

I say this because your proposed solution doesn't seem to impact the search problem with new episodes.  This is happening on many shows, and the pattern is the same -- recent episodes named "HD.TV" worked fine with SB, don't work in SR.

Thank you.

**Comment by fernandog** [comment]
which provider are you using that changed the name convention HDTV to HD.TV?

**Comment by ctrlbrk42** [comment]
![2015-07-16_10-18-04](https://cloud.githubusercontent.com/assets/1001097/8727178/fc1ba8fc-2ba3-11e5-888d-b9c8bc2e65b5.png)

To be clear, when I press 'search' on any of the wanted episodes, none are found.  I assume all providers are searched.  So my understanding is that the upload group changed from HDTV to HD.TV and therefore it is the same search results from any provider.  The issue is SR doesn't detect HD.TV as HDTV quality.  This is my understanding/assumption.

**Comment by fernandog** [comment]
@ctrlbrk42 
disable womble and sickbeard index. they are blocking SR application
enable debug log in SR advanced settings, stop SR, delete all files inside /SickRage/Logs, start SR
press manual search, send full logs in GIST

**Comment by ctrlbrk42** [comment]
Done, except I don't know how to do the last part (send full logs).  Sorry, please point me to where that is in SR.

**Comment by fernandog** [comment]
@ctrlbrk42 

![image](https://cloud.githubusercontent.com/assets/2620870/8728423/691d70ae-2bbb-11e5-8385-a797ea5b0414.png)

change "Minimum logging level to display:" to DEBUG
copy and paste in https://gist.github.com/
click "create secrete gist"
paste URL here

**Comment by ctrlbrk42** [comment]
Here are the logs zipped on my Google Drive, I will delete it in a minute please download.
https://drive.google.com/file/d/0ByGZ2IPlW-mEQ0prazNZVmRGUUU/view?usp=sharing

The show I searched for is same as reported in post 1, I searched several 'wanted' episodes that are definitely available to download.

Sorry i did not see your post until after I already restarted SR.  If the above logs don't work, tell me, I'll have to redo the whole process.

**Comment by fernandog** [comment]
@ctrlbrk42 

Are you sure this show exists in the provider?
I see no results of this show in your log


as you can see SR is working. It's downloading for Falllon
```
SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: Using cached parse result for: Jimmy.Fallon.2015.07.15.Amy.Schumer.720p.HDTV.x264-aAF
SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: Checking if found episode S02E106 is wanted at quality HDTV
SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: Any,Best = [ HDTV, 1080p HDTV ] [ None ] Found = [ HDTV ]
SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: Existing episode status: 3 (Wanted)
SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: Existing episode status is wanted/unaired/skipped, getting found episode
SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: Found result Jimmy.Fallon.2015.07.15.Amy.Schumer.720p.HDTV.x264-aAF at https://www.usenet-crawler.com/getnzb/21de1ef774a50dc8eb0c3d9a0a09c7b9.nzb&i=45411&r=**********
SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: Picking the best result out of [u'Jimmy.Fallon.2015.07.15.Amy.Schumer.720p.HDTV.x264-aAF']
SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: Quality of Jimmy.Fallon.2015.07.15.Amy.Schumer.720p.HDTV.x264-aAF is HDTV
SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: Picked Jimmy.Fallon.2015.07.15.Amy.Schumer.720p.HDTV.x264-aAF as the best
SEARCHQUEUE-DAILY-SEARCH :: Downloading Jimmy.Fallon.2015.07.15.Amy.Schumer.720p.HDTV.x264-aAF from Usenet-Crawler
SEARCHQUEUE-DAILY-SEARCH :: Sending NZB to SABnzbd
SEARCHQUEUE-DAILY-SEARCH :: URL: http://192.168.1.11:8080/api?ma_password=&apikey=**********&name=https%3A%2F%2Fwww.usenet-crawler.com%2Fgetnzb%2F21de1ef774a50dc8eb0c3d9a0a09c7b9.nzb%26i%3D45411%26r%3Dd9dde79c7647c17b192f96c7992c34f6&cat=sickbeard&priority=1&mode=addurl&ma_username=
SEARCHQUEUE-DAILY-SEARCH :: Result text from SAB: ok
SEARCHQUEUE-DAILY-SEARCH :: NZB sent to SAB successfully
```

**Comment by ctrlbrk42** [comment]
Here is usenet-crawler search results:
https://www.usenet-crawler.com/search?val=last%20week%20tonight%20john%20oliver&index=3

There are matches for my 'wanted' episodes.  I'm not sure where the problem really is, I assumed it was the 'HD.TV' issue but could be wrong.

S02E20 720p HDTV is a match for my quality settings, and I searched for it in the logs I sent, but yet no match found.  This is happening on several shows, I noticed all of them had the 'HD.TV' naming issue but maybe it's unrelated.  I didn't check all my shows.

Thank you for your help, greatly appreciate if you can help me solve this.

**Comment by fernandog** [comment]
but I see search results in your log
press manual search in one episode. wait a minute and check logs again.
try to find anything related to this show

**Comment by ctrlbrk42** [comment]
I agree with you, I even pasted the API url into Chrome with my API key and saw the XML had no results, but why is this happening.  The URL I posted above for a manual search shows all the shows I am missing and searched for, so where is the disconnect happening?

**Comment by ctrlbrk42** [comment]
FIXED IT!  I just edited the show and noticed it was 'air by date' checked, I unchecked that and it worked!  Let me try the other shows to see if the same problem has happened.

**Comment by ctrlbrk42** [comment]
Didn't work for other shows.  Example "Ballers".  Search finds no hits in SR, yet if I search manually on usenet-crawler all the missing episodes are there, and the quality matches.

**Comment by ctrlbrk42** [comment]
OK, enabled debug again and got the usenet-crawler URL.  Here is the problem:  &rid=20475

When I removed that from the query string, the XML file was populated with all the missing episodes.  I have no idea with rid is, but I assume you do.

Please help me :)

**Comment by ctrlbrk42** [comment]
For absolute clarity:
https://www.usenet-crawler.com/api?apikey=**********&season=1&maxage=12&cat=5030%2C5040&q=Ballers&limit=100&attrs=rageid&offset=0&rid=20475&ep=3&t=tvsearch

That is the URL from SR that produces zero results.  Remove the "&rid=20475" and the results are populated correctly.

**Comment by fernandog** [comment]
Thats is the indexer ID.
those results are NOT associated to the tvshow.
SR search using indexer id to find exactly results.
probably uploader didnt associated.

**Comment by ctrlbrk42** [comment]
Look here:
https://www.usenet-crawler.com/details/7ea66d1528433f232cfdbe3732e57a1d/Ballers%202015%20S01E03%20720p%20HDTV%20x264-0SEC

The image is coming from 'tvrage' with an ID of 104870.

I went to tvrage and did search:
http://www.tvrage.com/Ballers_2015/episode_list

Any insight?

**Comment by ctrlbrk42** [comment]
Let me correct, tvrage id 38517.  If I modify the URL to &rid=38517, the XML results are correct.

So now the question is, why is the ID wrong inside of SR?  When I click the links inside SR it shows only  thetvdb.com and the ID it shows matches that usenet-crawler id when you click the show details.  So why is SR searching for the wrong ID and using tvrage?

![2015-07-16_12-17-18](https://cloud.githubusercontent.com/assets/1001097/8730129/b528d72e-2bb4-11e5-8431-2e4061fce877.png)

I appreciate your help in trying to solve this, and I'll see if the same thing has happened on all the other shows once a solution is made.

**Comment by ctrlbrk42** [comment]
I deleted the entry, and then re-added it in SR.  Now it is downloading correctly.  I am guessing there was some sort of error on a couple dozen shows when I migrated from SB to SR, and somehow their ID's are wrong.

Thanks for pointing me in the right direction.

**Comment by miigotu** [comment]
Yep, wrong rage id was in your DB. Glad its working now.
