### ISSUE TITLE
Cannot display show anymore

### ISSUE THREAD

**Issue by Modjor** [SiCKRAGETV/sickrage-issues#2140]
Hi guys,

since the last update (done this morning), I can't display show anymore. when I click on a show from the showlist (or any place else), it always come back to the show list page.

I haven't dig into this yet, but seems to be related to the ui / browser and/or subtitles language (I'm in a mixed En/Fr environment)

Sickrage version: 
BRANCH: (master) / COMMIT: (608c06810abb05ab6e9d07947c86d42b1b1a21c2) 

Python Version:
2.7.9 (default, Mar 22 2015, 23:23:23) [GCC 4.6.4]

SR Locale: ('en_US', 'UTF-8')

Debug log:

2015-07-15 23:36:24 DEBUG    TORNADO :: Failed doing webui request "displayShow": Traceback (most recent call last):
AALanguageReverseError: u'fra'
AA    raise LanguageReverseError(opensubtitles)
AA  File "/usr/local/sickbeard-custom/var/SickBeard/lib/babelfish/converters/opensubtitles.py", line 36, in reverse
AA    return cls(*language_converters[converter].reverse(code))
AA  File "/usr/local/sickbeard-custom/var/SickBeard/lib/babelfish/language.py", line 110, in fromcode
AA    return babelfish.Language.fromopensubtitles(language)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/subtitles.py", line 70, in fromietf
AA    for sub_lang in [VFN(VFFSL(SL,"subtitles",True),"fromietf",False)(x) for x in VFN(VFFSL(SL,"epResult",True)["subtitles"],"split",False)(',') if VFFSL(SL,"epResult",True)["subtitles"]]: # generated from line 581, col 13
AA  File "/usr/local/sickbeard-custom/var/cache/cheetah/_usr_local_sickbeard_custom_var_SickBeard_gui_slick_interfaces_default_displayShow_tmpl.py", line 1335, in respond
AA    return t.respond()
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1320, in displayShow
AA    result = function(**kwargs)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 270, in async_call
AATraceback (most recent call last):
AALanguageReverseError: u'fra'
AA    raise LanguageReverseError(opensubtitles)
AA  File "/usr/local/sickbeard-custom/var/SickBeard/lib/babelfish/converters/opensubtitles.py", line 36, in reverse
AA    return cls(*language_converters[converter].reverse(code))
AA  File "/usr/local/sickbeard-custom/var/SickBeard/lib/babelfish/language.py", line 110, in fromcode
AA    return babelfish.Language.fromopensubtitles(language)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/subtitles.py", line 70, in fromietf
AA    for sub_lang in [VFN(VFFSL(SL,"subtitles",True),"fromietf",False)(x) for x in VFN(VFFSL(SL,"epResult",True)["subtitles"],"split",False)(',') if VFFSL(SL,"epResult",True)["subtitles"]]: # generated from line 581, col 13
AA  File "/usr/local/sickbeard-custom/var/cache/cheetah/_usr_local_sickbeard_custom_var_SickBeard_gui_slick_interfaces_default_displayShow_tmpl.py", line 1335, in respond
AA    return t.respond()
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1320, in displayShow
AA    result = function(**kwargs)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 270, in async_call
2015-07-15 23:36:24 ERROR    Thread-45 :: Failed doing webui callback: Traceback (most recent call last):

Thanks for the hard work! :)

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/2125
