### ISSUE TITLE
[APP SUBMITTED]: 422 {u'documentation_url': u'https://developer.github.com/v3/issues/#create-an-issue', u'message': u'Validation Failed', u'errors': [{u'field': u'title', u'message': u'title is too long', u'code': u'custom', u'resource': u'Issue'}]}

### ISSUE THREAD

**Issue by maxcore** [SiCKRAGETV/sickrage-issues#2142]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@608c06810abb05ab6e9d07947c86d42b1b1a21c2
Link to Log: https://gist.github.com/0f5e4cd721a0ca3414a0
### ERROR
```
Thread-86 :: 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
You have a file locked in your cache. Try deleting cache/indexers folder.

**Comment by maxcore** [comment]
@miigotu  is very strange my folder is already  empty...

**Comment by miigotu** [comment]
Because there is a hidden lock there or the folder itself is locked. You can delete the whole cache folder but you will need to update shows to get images back.
