### ISSUE TITLE
[APP SUBMITTED]: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/294511/en.xml

### ISSUE THREAD

**Issue by rcocchiararo** [SiCKRAGETV/sickrage-issues#2143]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@608c06810abb05ab6e9d07947c86d42b1b1a21c2
Link to Log: https://gist.github.com/aba2c5e264157b9f9b83
### ERROR
```
SHOWQUEUE-ADD :: Show name with ID 294511 don't exist in theTVDB anymore. Please change/delete your local .nfo file or remove it from your TRAKT watchlist
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Read the error

**Comment by rcocchiararo** [comment]
I read the error, i scroll the list of shows in my sickrage home, hover the
mouse over them, and i definitly have no show with that ID.

I searched sickrage home folder (i am in windows), and found no .nfo file
to edit/delete.

I am kinda lost T_T

El mié., 15 de jul. de 2015 a la(s) 8:04 p. m., Fernando <
notifications@github.com> escribió:

> Read the error
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/2143#issuecomment-121772594>
> .
>
-- 
--
Roberto Cocchiararo

**Comment by fernandog** [comment]
or remove it from your TRAKT watchlis
