### ISSUE TITLE
[APP SUBMITTED]: 504 Server Error: Gateway Time-out

### ISSUE THREAD

**Issue by kyleolsondesign** [SiCKRAGETV/sickrage-issues#2145]
### INFO
Python Version: **2.7.6 (default, Sep  9 2014, 15:04:36) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]**
Operating System: **Darwin-14.3.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/f6ed5badd0629009a5f4
### ERROR
```
Thread-378 :: Trakt: Unable to delete show: Powers (2015). Error: error 504 Server Error: Gateway Time-out
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Out of date install.
