### ISSUE TITLE
TASK: Update subliminal to 1.0

### ISSUE THREAD

**Issue by miigotu** [SiCKRAGETV/sickrage-issues#2147]
@Diaoul you're killing me, SOO MANY CHANGES to make this new version work, again! lol

I guess I now have to initialize the provider pool myself or I can't download_best_subtitles?

**Comment by Diaoul** [comment]
You can use `download_best_subtitles`, that's unchanged: http://subliminal.readthedocs.org/en/latest/usage.html#library

**Comment by miigotu** [comment]
I had just done a quick attempt, need to dig further. There is the diff of what I have done so far ^^

**Comment by miigotu** [comment]
I shoulda committed the library separate zzz, I'll have to rebase that later.

**Comment by Diaoul** [comment]
I'll improve the documentation section about library usage this evening and add a few doctests. Good examples is the most efficient way to get started.

**Comment by miigotu** [comment]
I am using download_best_subtitles still, here is the subliminal debug: (scan_video was passed english and spanish language objects, [video] was passed to download best subtitles)
https://gist.github.com/miigotu/e7079d2313629b6ba986

I will continue debugging it if you don't see anything obvious there.

**Comment by Diaoul** [comment]
I suppose this is the same as #465

**Comment by miigotu** [comment]
I think its not initializing the entry points in provider_manager because I'm not using the with like you do in cli, I can't even get names of the providers from provider_manager.names() (variable names might be wrong in this post, writing from my phone lol)

**Comment by Diaoul** [comment]
No, it's because there is no registered providers as you don't run setup.py to install the entry points.

**Comment by miigotu** [comment]
Aha. I'll get around to digging more as soon as I can, this is kinda low on the list since its not an easy update =p and 0.8.0 is working fairly well

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
