### ISSUE TITLE
UnboundLocalError: local variable 'resp' referenced before assignment

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#2148]
AA
AAUnboundLocalError: local variable 'resp' referenced before assignment
AA    if isinstance(resp, dict) and resp.get('status', False) == 'failure':
AA  File "/home/osmc/SickRage/lib/trakt/trakt.py", line 122, in traktRequest
AA    TraktShowWatchlist = self.trakt_api.traktRequest("sync/watchlist/shows")
AA  File "/home/osmc/SickRage/sickbeard/traktChecker.py", line 468, in _getShowWatchlist
AA    if self._getShowWatchlist():
AA  File "/home/osmc/SickRage/sickbeard/traktChecker.py", line 233, in syncWatchlist
AA    self.syncWatchlist()
AA  File "/home/osmc/SickRage/sickbeard/traktChecker.py", line 82, in run

**Comment by miigotu** [comment]
@fernandog I think thats from before you moved the return {} right?

**Comment by fernandog** [comment]
Maybe.  Will check logs again
