### ISSUE TITLE
ERR_CONNECTION_REFUSED on Web

### ISSUE THREAD

**Issue by neomvll** [SiCKRAGETV/sickrage-issues#2150]
Hi guys,
After last update (14 commits, I guess) I can't open my sickrage  on web.
I don't seen any errors on log too.
Service was restarted, as server too
I run Raspbian + Python 2.7.3.

**Comment by miigotu** [comment]
cd into SR directory, and do a manual `git pull`

**Comment by devenashani** [comment]
i too face the same problem but on ReadyNAS NV+ V2.

I tried updating manually through GIT but it says "Already up-to-date."

when i try to manually start sickrage through terminal i get below error

Starting SickBeard:PID file: /var/run/sickbeard/sickbeard.pid already exists. Exiting.
 failed!

**Comment by miigotu** [comment]
So remove /var/run/sickbeard/sickbeard.pid

That is not a SR bug but an init script bug =P

**Comment by devenashani** [comment]
i tried removing the file, but still the Web UI will not start.

Everything was working perfect till today's update (with 14 commits), so please check if something has changed.

**Comment by miigotu** [comment]
Still have an error?

**Comment by devenashani** [comment]
yes error still shows

**Comment by miigotu** [comment]
Then you didn't remove the pid file successfully.

Did you turn it off and then back on again? LOL

`sudo rm /var/run/sickbeard/sickbeard.pid`

**Comment by Tecjg** [comment]
@miigotu I have the same issue and I am removing the pid file correctly. I think SickRage is crashing during start up. For me it started with the last 6 commits: https://github.com/SiCKRAGETV/SickRage/compare/7a753b4ad5e0a540353432e7357801e70e8ae73e...2bfdb0a92083aa969fbfada92471850379a01045

**Comment by miigotu** [comment]
Let's move this to #2158
