### ISSUE TITLE
Sickrage Will Not Start after update

### ISSUE THREAD

**Issue by devenashani** [SiCKRAGETV/sickrage-issues#2151]
sickrage will not start after latest update, when i try to manually start from terminal i get below error

*********************************************************************************************************
Starting SickBeard:PID file: /var/run/sickbeard/sickbeard.pid already exists. Exiting.
failed!
*********************************************************************************************************

I am using ReadyNAS NV+ V2

**Comment by miigotu** [comment]
rm /var/run/sickbeard/sickbeard.pid (with root privileges)

Not a SR bug, its an init script bug.
