### ISSUE TITLE
Shows keep getting status "skipped" on airdate.

### ISSUE THREAD

**Issue by Paradoxx2015** [SiCKRAGETV/sickrage-issues#2154]
Shows in my list is getting stauts "skipped" on airdate. I´ll have to go inside each show and manual search the show on airdate.

SR Version:	BRANCH: (master) / COMMIT: (efdad7f24b806536abee630cd98211b6f64997b4) 
Python Version:	2.7.10 (default, Jun 3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]

config is set to do: Update shows on startup / snatched. 
<img width="734" alt="skjermbilde 2015-07-16 kl 08 32 04" src="https://cloud.githubusercontent.com/assets/13360967/8716841/2cfed73c-2b95-11e5-8faa-6a6a171f46c0.png">

**Comment by miigotu** [comment]
![image](https://cloud.githubusercontent.com/assets/390379/8721150/e4b28230-2b6c-11e5-833d-7397eb277a16.png)

Edit your shows and set the default episode status to the correct value.

**Comment by cr08** [comment]
I apologize for jumping in here but I just wanted a little clarification: Will setting this on existing shows via the Mass Update function set all previous episodes not downloaded as wanted or just future episodes? I don't wan't to set it and have my whole SickRage library try and grab this metric crap-ton of backlogged episodes.

**Comment by fernandog** [comment]
@cr08 mass update will change the "default ep status" settings for all shows. and this only affects the conversion from UNAIRED episodes to (default_ep_status) status

Then I suggest check episode by episode SKIPPED from the list (localhost:8081/manage/episodeStatuses?whichStatus=5)  and manually change them to WANTED - if you want them to be downloaded

**Comment by fernandog** [comment]
@cr08 and please make a sickbeard.db update!

**Comment by fernandog** [comment]
Sorry. Backup! Not update

**Comment by cr08** [comment]
Ok. Phew. Thought I missed something. Thanks once again! :)
