### ISSUE TITLE
"Ignored" status changes it self to "Skipped".

### ISSUE THREAD

**Issue by Paradoxx2015** [SiCKRAGETV/sickrage-issues#2155]
When trying to set status of a specific session from skipped to ignored it seems its changed.
When changing meny to manage -> Episode Status Management, and selecting filter to "Ignored", nothing is found.
So go back in to the specific series and session that was changed and se that the status is back to "Skipped".

SR Version:	BRANCH: (master) / COMMIT: (efdad7f24b806536abee630cd98211b6f64997b4) 
Python Version:	2.7.10 (default, Jun 3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]

**Comment by miigotu** [comment]
It is not instantly changed. When you change the status the show updates.
