### ISSUE TITLE
URL check failed. Bad result from provider.

### ISSUE THREAD

**Issue by garfin-au** [SiCKRAGETV/sickrage-issues#2156]
Hi, i thought i had this fixed y'day.. but alas, no its still/again misbehaving...

```
2015-07-16 16:57:25 INFO     SEARCHQUEUE-BACKLOG-294206 :: Skipping BattleBots.2015.S01E04.iNTERNAL.720p.HDTV.x264-W4F, URL check failed. Bad result from provider.
2015-07-16 16:57:25 WARNING  SEARCHQUEUE-BACKLOG-294206 :: Connection error to https://...
```

Seems to be on both my Newznab providers.. Unsure about Womble's / Sick Beard Indexers.. don't seem to be finding ep's on there either.

**Comment by miigotu** [comment]
@garfin-au womble fails ssl, and sick beard index blocks sickrage.

**Comment by garfin-au** [comment]
Hi again.. Mmm ok, so i'm dead in the water??  We got it working (briefly last night and it cleared what it could of the backlog..)  But seems to be broken again today.. (there was another 4 commits that were applied in autoupdate today.. related?)

**Comment by miigotu** [comment]
Not related to SR code. Occasionally sick beard index lets some requests through, same with womble. Try a better nzb indexer.

**Comment by garfin-au** [comment]
Hi , If it weren't for the fact that SickBeard (which i'm dearly trying to move away from) is still able to snatch from the same two 'other' providers, & yet running on same debian wheezy instance...

**Comment by miigotu** [comment]
It has nothing to do with SickRage code. SickBeard's SITE blocks us, intentionally, by user agent and other methods.

**Comment by garfin-au** [comment]
Sorry let me explain myself better..  SR & SB had 4 providers set, those being Womble's , SB Indexer , and 2 VIP NewsNab+ subscriptions... now for the sake of the test , i've turned off Womble's and SB Indexer on both SR & SB instances , so both are JUST using the two  2 VIP NewsNab+ subscriptions..

SB working fine.. SR is not.

**Comment by garfin-au** [comment]
```
SB Log:
Jul-16 21:27:57 INFO     SEARCHQUEUE-BACKLOG-294206 :: Downloading a result from VIG at https://api.vig.info/api?t=get&id=048ab7c0e54f8c1b34ec11edc29d41d4&apikey=******
Jul-16 21:27:57 INFO     SEARCHQUEUE-BACKLOG-294206 :: Quality of BattleBots.2015.S01E04.iNTERNAL.720p.HDTV.x264-W4F is HD TV
Jul-16 21:27:57 INFO     SEARCHQUEUE-BACKLOG-294206 :: Quality of BattleBots.2015.S01E04.iNTERNAL.720p.HDTV.x264-W4F is HD TV
Jul-16 21:27:37 INFO     SEARCHQUEUE-BACKLOG-294206 :: Searching for stuff we need from BattleBots (2015) season 1
Jul-16 21:27:36 INFO     CP Server Thread-11 :: Seeing if we need any episodes from BattleBots (2015) season 1
Jul-16 21:27:36 INFO     CP Server Thread-11 :: Sending backlog for BattleBots (2015) season 1 because some eps were set to wanted


SR Log:
2015-07-16 21:32:45 INFO     SEARCHQUEUE-BACKLOG-294206 :: No needed episodes found during backlog search for: [BattleBots (2015)]
2015-07-16 21:32:45 INFO     SEARCHQUEUE-BACKLOG-294206 :: Skipping BattleBots.2015.S01E04.iNTERNAL.720p.HDTV.x264-W4F, URL check failed. Bad result from provider.
2015-07-16 21:32:45 WARNING  SEARCHQUEUE-BACKLOG-294206 :: Connection error to https://www.fw.info/getnzb/ba8a6707ca978d2287acfc4d9300ce75.nzb&i=13&r=**********
2015-07-16 21:32:44 INFO     SEARCHQUEUE-BACKLOG-294206 :: Quality of BattleBots.2015.S01E04.iNTERNAL.720p.HDTV.x264-W4F is HDTV
2015-07-16 21:32:44 INFO     SEARCHQUEUE-BACKLOG-294206 :: [FW] :: Found result BattleBots.2015.S01E04.iNTERNAL.720p.HDTV.x264-W4F at https://www.fw.info/getnzb/ba8a6707ca978d2287acfc4d9300ce75.nzb&i=13&r=**********
2015-07-16 21:32:44 INFO     SEARCHQUEUE-BACKLOG-294206 :: [FW] :: Performing episode search for BattleBots (2015)
2015-07-16 21:32:40 INFO     SEARCHQUEUE-BACKLOG-294206 :: [VIG] :: Performing episode search for BattleBots (2015)
2015-07-16 21:32:40 INFO     SEARCHQUEUE-BACKLOG-294206 :: Building internal name cache for BattleBots (2015)
2015-07-16 21:32:40 INFO     SEARCHQUEUE-BACKLOG-294206 :: Beginning backlog search for: [BattleBots (2015)]
2015-07-16 21:32:38 INFO     Thread-54 :: Sending backlog for BattleBots (2015) season 1 because some eps were set to wanted
```

**Comment by miigotu** [comment]
try disabling ssl verify in config/general -> advanced.

**Comment by garfin-au** [comment]
it is.. (I've tried it both ways, just to be sure..)

**Comment by miigotu** [comment]
then you need pyopenSSL

**Comment by garfin-au** [comment]
Hi,

The other day under issue #1945 you had me..

```

Alternatively, you could:

sudo apt-get install build-essential libffi-dev python-dev sudo pip 
uninstall pyopenssl sudo pip install -U pyopenssl==0.13.1
That should build in the crypto extension.

```



Should I revert all that ?



------ Original Message ------

**Comment by miigotu** [comment]
`Connection error to https://www.fw.info/getnzb/ba8a6707ca978d2287acfc4d9300ce75.nzb&i=13&r=**********`

**Comment by miigotu** [comment]
I think your install is fine, it really must be something with the indexer.

**Comment by garfin-au** [comment]
My only concern is that i have an old SB instance on the same debian box,  that hasn't been upgraded in years, and THAT still works with those same indexers...  What i'm going to do , is roll back the debian box (thank goodness for VM's ..) to a snapshot taken 26th of last month..pretty sure all was good and happy with both SB & SR at that point. I guess i'll need to be quick at stopping SR when it boots so i can disable autoupdates...

**Comment by miigotu** [comment]
1. various indexers have limited or even blocked SR due to it's popularity causing delays on their site.
2. the only difference is our user-agent and that we do a head request before we try and download content. This head request is for the indexer's benefit, but some of them see it as a get request and then deny the subsequent get request. This is not a bug in SR, in fact SR is working better than most programs in that aspect, which is why their software does not understand this situation.

3. you can disable updates in config.ini

**Comment by garfin-au** [comment]
Re:1. I personally know one of the 2 indexers i use... he wouldn't have knowingly limited or blocked SR.. unless its a feature been added in a NewsNAB+ recent update, enabled by default.

Re:3 Yeah, I can easily start the deb box back up after rollback, with no network connectivity , while i tinker with config.ini  9% completed in rollback & counting.. i'll let you know how it goes in a couple of hours...  

How (what file) do i need to edit to disable the SSL Verify in this older version of SR ?

**Comment by miigotu** [comment]
I just made a change about ssl verifications (again)...You can try again, with and without the ssl verify. But when you toggle ssl verify, delete cache/sessions/*

**Comment by garfin-au** [comment]
I've just completed reverting back to the 25th June version with auto updates disabled.. (as well as Womble's & SB Indexers) ..  i'm 300+ commits behind, BUT it seems to be working..Just running an apt-get update&&apt-get dist-upgrade

**Comment by miigotu** [comment]
NP, if you arent having any problems or need any new features there is no reason to update from there anyways

**Comment by garfin-au** [comment]
Cheers.. again i'll closely monitor it over the next few days... next scheduled ep for it to grab is Sunday.. so i'll let you know Monday where things are at.

**Comment by garfin-au** [comment]
Thanks, seems to be all working again.its happily grabbing shows that my Newsnab providers have listed..One still backlogged, but neither have it listed yet.

**Comment by miigotu** [comment]
Just now tested the new fix @garfin-au or before i committed it? confused lol.

**Comment by garfin-au** [comment]
As we spoke above.. I reverted back to June 25th.. to which you responded.. miigotu commented 3 days ago
NP, if you aren't having any problems or need any new features there is no reason to update from there anyways.

So yes,  I've now been monitoring it for a few days on this 300+ commit behind version, and its working like a charm..Unless this suddenly stops functioning i wont be embarking on another auto-update 'pull' for the foreseeable future.

**Comment by miigotu** [comment]
@garfin-au I have just fixed newznab providers, tested with nzbgeek, thanks to the nzbgeek admins for the key.

**Comment by miigotu** [comment]
@garfin-au I will test SB Index, and Womble and Usenet-Crawler now.

**Comment by miigotu** [comment]
Negative, they still don't work. the reason the  June 25th works is because of the user-agent.

Removing sickBeard Index, Womble, and Usenet-Crawler from default providers next time I PR.
