### ISSUE TITLE
Sickrage keeps redownloading the same season, over and over and over again.

### ISSUE THREAD

**Issue by Smultie** [SiCKRAGETV/sickrage-issues#2157]
As the topic title says, I have one series (Gotham) where I have the complete season one in the quality I want (1080 Web-DL), but for some reason, it keeps redownloading.

    Branch           
    Commit hash
    Your operating system and python version   Debian Jessie, Python 2.7.9
    What you did                         Add a series, watch it download the eps in the proper quality once
    What happened                                                            
    What you expected
    Link to a copy/paste of your logfile with clear debug info of the error on GIST

**Comment by miigotu** [comment]
```
Branch           
Commit hash
Your operating system and python version   Debian Jessie, Python 2.7.9
What you did                         Add a series, watch it download the eps in the proper quality once
What happened                                                            
What you expected
Link to a copy/paste of your logfile with clear debug info of the error on GIST
```

**Comment by Smultie** [comment]
I'm sorry. Will fill in later!
