### ISSUE TITLE
Episodes getting set to "ignored" automatically

### ISSUE THREAD

**Issue by seiki** [SiCKRAGETV/sickrage-issues#2159]
I've found lately that some episodes are not being searched for because they're getting automatically set to ignored on the air date (they go from unaired to ignored).

 BRANCH: (master) / COMMIT: (712b6c656e10d30864ac478b996513609d6eeffd)

**Comment by miigotu** [comment]
Because your default episode status for that show is set to ignored. Edit the show(s) and set the default episode status to the correct value, and then set the previous episodes that were set to ignored to wanted.
