### ISSUE TITLE
Spanish indexer info characters

### ISSUE THREAD

**Issue by ajtudela** [SiCKRAGETV/sickrage-issues#2160]
I set my "Default Indexer Language" in Spanish, but when it retrieve the info from TheTVDB shows wrong characters:
- "Trabajando bajo presiÃƒÂ³n"

When it should be: 
- "Trabajando bajo presión"

https://dl.dropboxusercontent.com/u/11602465/Captura2.PNG

SR Version:	BRANCH: (master) / COMMIT: (efdad7f24b806536abee630cd98211b6f64997b4) 
SR User:	Alberto
SR Locale:	('es_ES', 'cp1252')
SR Config file:	C:\SickRage\config.ini
SR Database file:	C:\SickRage\sickbeard.db
SR Cache Dir:	C:\SickRage\cache
SR Log Dir:	C:\SickRage\Logs
SR Arguments:	[]
Python Version:	2.7.2 (default, Jun 12 2011, 15:08:59) [MSC v.1500 32 bit (Intel)]

https://gist.github.com/ajtudela/260758d6dbd94825dd65

**Comment by miigotu** [comment]
You need to change your codepage to utf-8, as all of the indexers use utf-8, not latin-1

If you do:
`chcp 65001`
before starting SickRage it should be correct.

**Comment by ajtudela** [comment]
I used WIndows, I don't know how

**Comment by ajtudela** [comment]
I used windows, It set as UTF-8

**Comment by ajtudela** [comment]
I did it, but it doesn't work
