### ISSUE TITLE
[APP SUBMITTED]: ('Connection aborted.', gaierror(-2, 'Name or service not known'))

### ISSUE THREAD

**Issue by hazell20** [SiCKRAGETV/sickrage-issues#2161]
### INFO
Python Version: **2.7.3 (default, Mar 14 2014, 11:57:14) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-686-pae-i686-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@92bf581ba8a7d4f2f912db795ce571b6ad38c3c2
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Speedcd] :: Unable to connect to Speedcd provider: error ('Connection aborted.', gaierror(-2, 'Name or service not known'))
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
not an issue
