### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/media/ssd/showdl/burn.notice.s01e10.dsr.xvid-xor.[VTV].avi'

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#2162]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:34:55) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-22-generic-i686-with-Ubuntu-15.04-vivid**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@949e35961272a0841f12ce7ba27040da12c693f2
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
did you started any manual PP lately?

**Comment by matigonkas** [comment]
yes

**Comment by fernandog** [comment]
That is. SR dont have PP queue. When auto PP tried to prpcess the dir, manual process alredy processed.
