### ISSUE TITLE
Missed Episodes Range being ignored after SR restart

### ISSUE THREAD

**Issue by nrk666** [SiCKRAGETV/sickrage-issues#2166]
BRANCH: (master) / COMMIT: (d70de9f823edfea55809f2779ed2871446e6080d) - Note, I just updated however, so if this has already been fixed, sorry to waste time. 

Python 2.7.6

When restarting SR for new updates, episodes that are airing that day (but haven't been downloaded yet) are set to "Skipped" even though they are still current. 

For example: 

1. Show X, Y, and Z are airing tonight, have status "Unaired", show up in "Coming Episodes"
2. I log into SR and notice there are new updates, possibly after air time, but before fetch of shows X, Y, Z. 
3. I apply the updates, SR is restarted. 
4. Show X, Y, and Z are no longer listed in "Coming Episodes" and their episode status are now set to "Skipped". 
5. There is a single line log entry that just says "DAILYSEARCHER :: New episode Some TV Show - 4x20 - Episode Title airs today, setting to default episode status for this show: Skipped".

So, I don't think its an actual code bug, but maybe a flow issue. If the episode was "Unaired" and restarting SR sets it to "Skipped" without honoring the "Missed Episodes Range" setting. Can this be changed to first check the "Missed Episodes Range" setting and if within "Missed Episodes Range", leave the status as it was?

**Comment by miigotu** [comment]
Check the new "News" page.

**Comment by nrk666** [comment]
I clicked it and it just says "Not Found".

**Comment by miigotu** [comment]
Maybe you have SSL problems? Its fetching from github over ssl

**Comment by miigotu** [comment]
BTW @fernandog we should check out rawgit.com

**Comment by nrk666** [comment]
Dunno man, I don't seem to be having any other SSL issues on any number of other sites, (including github, which I am obviously using right now, connected with https://) - I even disabled my Provider Proxy setting and restarted SR thinking that might be it, still says "Not Found".

**Comment by fernandog** [comment]
@nrk666 checkout develop please

**Comment by nrk666** [comment]
The news.md clearly says "We are upgrading Subliminal module and this may and will break your installation. Please avoid use develop branch until we fully tested everything unless you know what you are doing". 

So, I'd rather not checkout develop at the moment, I'll just live without News.

**Comment by fernandog** [comment]
wait a few minutes. master will be updated

**Comment by nrk666** [comment]
that's got it fixed, its showing up now. Thanks. For both fixing News and explaining the new default status situation. I'm all set now.
