### ISSUE TITLE
[APP SUBMITTED]: -1

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2170]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:34:55) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-22-generic-i686-with-Ubuntu-15.04-vivid**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@a49006a4d1613e65fcf4dc0cfd0c32a4085bad71
Link to Log: https://gist.github.com/1519bb0d2953ca610697
### ERROR
```
TORNADO :: API :: error -1
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Does it always do that for the simpsons or is this a one time thing?

**Comment by matigonkas** [comment]
@miigotu  everytime ,and its for all shows

**Comment by miigotu** [comment]
Rapid requests? What are you using that calls this api?

**Comment by matigonkas** [comment]
ShowsRage from MGaetan

**Comment by miigotu** [comment]
I see, that is still under development. Sure it isn't a problem there?

**Comment by fernandog** [comment]
others app works ok: DroidBeard and NZB360

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:34:55) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-22-generic-i686-with-Ubuntu-15.04-vivid**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@dd99b5bcd96d6fa1888decf7fa63cad01fe2c94f
Link to Log: https://gist.github.com/e39635b9ec98078d867a
### ERROR
```
TORNADO :: API :: error -1
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by MGaetan89** [comment]
Is there a way to find where the error is logged in SickRage?
Between the first log (4 days ago) and today's log, I changed the way I use the `show.stats` command. Before I sent one request for each show, but now I use chained calls to get all stats at once.
But the error is still here. Is there a way to find where it was logged?

**Comment by fernandog** [comment]
did you try to open SickRage/Logs files?

**Comment by MGaetan89** [comment]
I don't have this error in my logs, so I can't check.

**Comment by technazz** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@f7d55c141f2001dadbedb8d699513bfc2c51a667
Link to Log: https://gist.github.com/d16b8916b2df24d98505
### ERROR
```
TORNADO :: API :: error -1
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by technazz** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@41dfcaeaf855297d6a478355746d6b769ca8b0da
Link to Log: https://gist.github.com/651b3ca175216255bd0b
### ERROR
```
TORNADO :: API :: error -1
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
@technazz try removing Master Chef Junior and re-adding it.

**Comment by blakadder** [comment]
### INFO
Python Version: **2.7.9 (default, Jan 16 2015, 11:00:00) [GCC 4.9.2]**
Operating System: **Linux-2.6.31.8-armv5tel-with-libc0**
Locale: ISO8859-1
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
No Log available with ERRORS: 
### ERROR
```
TORNADO :: API :: error -1
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by blakadder** [comment]
### INFO
Python Version: **2.7.9 (default, Jan 16 2015, 11:00:00) [GCC 4.9.2]**
Operating System: **Linux-2.6.31.8-armv5tel-with-libc0**
Locale: ISO8859-1
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
No Log available with ERRORS: 
### ERROR
```
TORNADO :: API :: error -1
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by blakadder** [comment]
### INFO
Python Version: **2.7.9 (default, Jan 16 2015, 11:00:00) [GCC 4.9.2]**
Operating System: **Linux-2.6.31.8-armv5tel-with-libc0**
Locale: ISO8859-1
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
No Log available with ERRORS: 
### ERROR
```
TORNADO :: API :: error -1
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by distracto** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@f62dc65bef699a151f3d2892c61cc4fa6026e84b
No Log available with ERRORS: 
### ERROR
```
TORNADO :: API :: error -1
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by distracto** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@f62dc65bef699a151f3d2892c61cc4fa6026e84b
No Log available with ERRORS: 
### ERROR
```
TORNADO :: API :: error -1
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by distracto** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@f62dc65bef699a151f3d2892c61cc4fa6026e84b
No Log available with ERRORS: 
### ERROR
```
TORNADO :: API :: error -1
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by distracto** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@f62dc65bef699a151f3d2892c61cc4fa6026e84b
No Log available with ERRORS: 
### ERROR
```
TORNADO :: API :: error -1
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by distracto** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@f62dc65bef699a151f3d2892c61cc4fa6026e84b
No Log available with ERRORS: 
### ERROR
```
TORNADO :: API :: error -1
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by distracto** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@f62dc65bef699a151f3d2892c61cc4fa6026e84b
No Log available with ERRORS: 
### ERROR
```
TORNADO :: API :: error -1
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by distracto** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@f62dc65bef699a151f3d2892c61cc4fa6026e84b
No Log available with ERRORS: 
### ERROR
```
TORNADO :: API :: error -1
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by distracto** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
Link to Log: https://gist.github.com/c52bda2046ec11596657
### ERROR
```
TORNADO :: API :: error -1
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by victorclaessen** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.2**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
TORNADO :: API :: error -1
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
