### ISSUE TITLE
IPTorrents invalid certificate login and everything else fails

### ISSUE THREAD

**Issue by shamsalmon** [SiCKRAGETV/sickrage-issues#2171]
SR Version:	BRANCH: (master) / COMMIT: (13c75e4e6053ed5e6ec1a23a000d1771607f9f33) 
SR User:	---
SR Locale:	('en_US', 'cp1252')
SR Config file:	C:\SickRage\config.ini
SR Database file:	C:\SickRage\sickbeard.db
SR Cache Dir:	C:\SickRage\cache
SR Log Dir:	C:\SickRage\Logs
SR Arguments:	['--nolaunch']
Python Version:	2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]

Logs:
20:11:49 ERROR::SEARCHQUEUE-BACKLOG-281662 :: [IPTorrents] :: Unable to connect
to IPTorrents provider: error [SSL: CERTIFICATE_VERIFY_FAILED] certificate veri
y failed (_ssl.c:581)
Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\iptorrents.py", line 96, in _doLogin
    response = self.session.post(self.urls['login'], data=login_params, timeout
30)
  File "C:\SickRage\lib\requests\sessions.py", line 507, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\SickRage\lib\requests\sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\SickRage\lib\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\SickRage\lib\requests\adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:58
)
20:11:54 ERROR::SEARCHQUEUE-BACKLOG-281662 :: [IPTorrents] :: Unable to connect
to IPTorrents provider: error [SSL: CERTIFICATE_VERIFY_FAILED] certificate veri
y failed (_ssl.c:581)
Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\iptorrents.py", line 96, in _doLogin
    response = self.session.post(self.urls['login'], data=login_params, timeout
30)
  File "C:\SickRage\lib\requests\sessions.py", line 507, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\SickRage\lib\requests\sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\SickRage\lib\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\SickRage\lib\requests\adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:58
)
20:11:58 ERROR::SEARCHQUEUE-BACKLOG-281662 :: [IPTorrents] :: Unable to connect
to IPTorrents provider: error [SSL: CERTIFICATE_VERIFY_FAILED] certificate veri
y failed (_ssl.c:581)
Traceback (most recent call last):
  File "C:\SickRage\sickbeard\providers\iptorrents.py", line 96, in _doLogin
    response = self.session.post(self.urls['login'], data=login_params, timeout
30)
  File "C:\SickRage\lib\requests\sessions.py", line 507, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\SickRage\lib\requests\sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\SickRage\lib\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\SickRage\lib\requests\adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:58
)
20:11:58 INFO::SEARCHQUEUE-BACKLOG-281662 :: No needed episodes found during ba
klog search for: [Marvel's Daredevil]

**Comment by miigotu** [comment]
What system are you on?

You can disable ssl cert verification in config/general -> advanced tab.

**Comment by shamsalmon** [comment]
Did that and restarted sickrage with no results. Same issue. I can try commenting out the verify code and running it again.

**Comment by miigotu** [comment]
Actually, try changing it from:
` session.verify = certifi.where() if sickbeard.SSL_VERIFY else None`
to:
` session.verify = certifi.where() if sickbeard.SSL_VERIFY else False`

**Comment by miigotu** [comment]
Also, the problem might be that the session is still cached to disk after disabling the ssl verify, in cache/sessions/

Try without the change, with ssl verify unchecked, and after removing cache/sessions/

**Comment by shamsalmon** [comment]
Both didn't fix it, errors seems to be just an exception in adapters.py stemming from conn.urlopen if I'm reading it right. I don't code much in python though.

**Comment by miigotu** [comment]
Any proxy enabled? the certificate verify failed only happens if ssl verify is on (or on in the cached session)

You did stop SR and make the change and then start again right? You have to stop SR before every change and start it up after every change and test, including deleting the sessions

**Comment by shamsalmon** [comment]
Ok disregard that last commend. In adapters.py there is a call to self.cert_verify(conn, request.url, verify, cert) I just commented it out and it fixed everything. It seems like that should be read from the setting where I disabled SSL Verification but it doesn't seem like it is. Line 338 in adapters.py if you want to take a look yourself.

**Comment by shamsalmon** [comment]
Also yeah no proxy enabled or anything else. Made the change to cert_verify on adapters.py restarted and it fixed it.

**Comment by miigotu** [comment]
I'll check later, but my session.verify setting should be propagating through to the cert_verify function. UGH.

**Comment by shamsalmon** [comment]
Sorry bud I would take a look further but I am about to go afk. Thanks for contributing to SickRage though it's one the most time saving applications I have ever used. If I ever find the time away from my other projects I will be sure to contribute.

**Comment by Jiggywiggy** [comment]
Hello, I tried to open IPT today and all i get is an error saying the "invalid certificate login" I'm on MacOSX, I just updated the OS and Safari the other day but i'm sure it was working yesterday. How can i fix it?

**Comment by miigotu** [comment]
general settings on advanced tab, disable ssl cert verification.

**Comment by Jiggywiggy** [comment]
I can't find the disable SSL verification in safari preferences or keychain preferences. Can you be more specific please.

**Comment by miigotu** [comment]
SickRage config/general-> advanced
