### ISSUE TITLE
News Section Backlisted for abuse

### ISSUE THREAD

**Issue by devenashani** [SiCKRAGETV/sickrage-issues#2172]
news section shows following error

![sickrage - branch- master - news](https://cloud.githubusercontent.com/assets/2997303/8739818/6a36f016-2c5e-11e5-8fe6-ad34b7b18d71.png)

**Comment by LaurentDumont** [comment]
I just got that too.

I replaced the code in sickbeard/webserve.py line 2167 with \:

> http://cdn.rawgit.com/SiCKRAGETV/SickRage/develop/news.md

The original line is missing the "cdn" subdomain \:

> http://rawgit.com/SiCKRAGETV/SickRage/develop/news.md

**Comment by miigotu** [comment]
Negative. The CDN version is cached forever, so you wouldn't get any updated version. I have changed it to use the news.md in the source until we come up with a better solution.

**Comment by miigotu** [comment]
It was getting about a request a second BTW, that's why it was blacklisted =p

**Comment by miigotu** [comment]
SiCKRAGETV/SickRage/commits/ef12cae3dd6aa790bd5574ba246d223507b0305a

**Comment by LaurentDumont** [comment]
The FAQ does mention that if you change the file path, the content should be refreshed inside the cache.

"To ensure that the CDN always serves the version of the file you want, use a git tag or commit ref in the file's path instead of a branch name, and update the URL if you push a new version of the file."

**Comment by miigotu** [comment]
Yeah, meaning use a tag not a branch. Which is not up to date in real time, and you have to change the URL every time. URLs are cache forever on the cdn and are never refreshed.
