### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: 'news.md'

### ISSUE THREAD

**Issue by udochrist** [SiCKRAGETV/sickrage-issues#2173]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@71b3016de25280fe45f2aa1b779c3434e1979da6
Link to Log: https://gist.github.com/022399bed63c89d7762a
### ERROR
```
Thread-62 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2167, in index
    with open("news.md", "r") as newsfile:
IOError: [Errno 2] No such file or directory: 'news.md'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by lordxidious** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@71b3016de25280fe45f2aa1b779c3434e1979da6
No Log available with ERRORS: 
### ERROR
```
Thread-226 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 2167, in index
    with open("news.md", "r") as newsfile:
IOError: [Errno 2] No such file or directory: 'news.md'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by sverleysen** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 23:30:53) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@71b3016de25280fe45f2aa1b779c3434e1979da6
Link to Log: https://gist.github.com/5c1804e4aa657bbead77
### ERROR
```
Thread-68 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2167, in index
    with open("news.md", "r") as newsfile:
IOError: [Errno 2] No such file or directory: 'news.md'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Damn, need to add the path I guess cuz of the os.chdir

**Comment by Veldkornet** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 13:42:00) [GCC 4.6.4]**
Operating System: **Linux-2.6.32.12-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@71b3016de25280fe45f2aa1b779c3434e1979da6
Link to Log: https://gist.github.com/3a0f7a18c7a985bc97b8
### ERROR
```
Thread-70 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 2167, in index
    with open("news.md", "r") as newsfile:
IOError: [Errno 2] No such file or directory: 'news.md'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Vodka2014** [comment]
Same errors in the logs

**Comment by elRadix** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@71b3016de25280fe45f2aa1b779c3434e1979da6
Link to Log: https://gist.github.com/d3125b384e90a560fd8b
### ERROR
```
Thread-155 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2167, in index
    with open("news.md", "r") as newsfile:
IOError: [Errno 2] No such file or directory: 'news.md'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Vodka2014** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@71b3016de25280fe45f2aa1b779c3434e1979da6
Link to Log: https://gist.github.com/6e588fca5f169e6b46c7
### ERROR
```
Thread-55 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume5/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/volume5/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 2167, in index
    with open("news.md", "r") as newsfile:
IOError: [Errno 2] No such file or directory: 'news.md'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by palmfighter** [comment]
@miigotu @fernandog  Guys, is there no development branch anymore? A lot of stuff is now broken in main branch. Please test before release in development.

**Comment by miigotu** [comment]
@palmfighter things are tested, we have had to force rapid merges to master recently due to some late breakage reports, that needed fixed immediately.

**Comment by palmfighter** [comment]
@miigotu I appreciate what you guys are doing, the new NEWS page is a great addition!

**Comment by miigotu** [comment]
Also there is a changes page ^^ in the "wrench" dropdown.
