### ISSUE TITLE
[APP SUBMITTED]: No JSON object could be decoded

### ISSUE THREAD

**Issue by smokingunny** [SiCKRAGETV/sickrage-issues#2174]
### INFO
Python Version: **2.7.9 (default, Mar 22 2015, 23:43:57) [GCC 4.6.4]**
Operating System: **Linux-2.6.32.12-armv5tel-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@efdad7f24b806536abee630cd98211b6f64997b4
Link to Log: https://gist.github.com/b314a1740977d06a03a7
### ERROR
```
SEARCHQUEUE-BACKLOG-164541 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
disable proxy

**Comment by FlyGuy94** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@6831ae9131af765586c1d348cc1835f363f350ce
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-80273 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by FlyGuy94** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@6831ae9131af765586c1d348cc1835f363f350ce
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-81320 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by yeyeoke** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@a4f329fbc394e8939977bf9c43aa540f948fec75
Link to Log: https://gist.github.com/831fac103a8d235f42fd
### ERROR
```
FINDPROPERS :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by WebSpider** [comment]
Your software is like a month old. Please update first.

**Comment by didyouexpectthat** [comment]
I had this issue with torrentday as well. I resolved it by restarting my machine (I was running on Debian 7). I went as far as to change the URL that torrentday even connects to but it was still plaguing me. I was already on the latest from the git repo.

**Comment by kylliox** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5770d33ef96e619af764b452ea35ad33e5755add
Link to Log: https://gist.github.com/6bd1601fcc5b963e21af
### ERROR
```
FINDPROPERS :: [FrenchTorrentDB] :: Error while searching FrenchTorrentDB, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Grimmoire0** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@37914618686ee70479da0fa4b2cca851fa49c5e2
Link to Log: https://gist.github.com/51fe60a6138d828607ae
### ERROR
```
SEARCHQUEUE-MANUAL-264492 :: [T411] :: Error while searching T411, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by soapsud90** [comment]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.3-RELEASE-p26-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@efc2434c76dd476b0480ab1f0c395983a095fc07
Link to Log: https://gist.github.com/8d76d92c99cee31dc657
### ERROR
```
SEARCHQUEUE-BACKLOG-71326 :: [TorrentProject] :: Error while searching TorrentProject, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by WebSpider** [comment]
Torrentproject is having issues, i've seen dropping connections and incomplete replies all day.

-----Original Message-----

**Comment by adaur** [comment]
Ftdb is down atm, we don't know if and when they are coming back.

**Comment by fernandog** [comment]
@miigotu 

for this error we have:

**proxy adding html tags** (user is using proxy)
```
2015-10-10 17:53:25 ERROR    SEARCHQUEUE-BACKLOG-71326 :: [TorrentProject] :: Error while searching TorrentProject, skipping: No JSON object could be decoded
2015-10-10 17:53:20 DEBUG    SEARCHQUEUE-BACKLOG-71326 :: [TorrentProject] :: Proxified URL: http://interproxy.net/browse.php?u=https%3A%2F%2Ftorrentproject.se%2F%3Fs%3DRed%2520Dwarf%2520S09E03%26out%3Djson&b=32&f=norefer
```
**providers adding html tags**
like the T411 issue. we fixed only this provider

shouldn't we handle better the `No JSON object could be decoded` ?
maybe if we get this error and user has proxy enabled for it, we give a warning asking him to disable proxy. what do you think?

**Comment by soapsud90** [comment]
Can we not just demote the level of logging for this type of message? Such as INFO instead of ERROR, but make it switchable if we are interested in failing search providers to keep the ERROR/WARN level as it is now.

**Comment by fernandog** [comment]
@miigotu should we try:except here?

`return resp.content if not json else resp.json()`
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/helpers.py#L1653

**Comment by bckwltn** [comment]
### INFO
Python Version: **2.7.10 (default, Jul 14 2015, 19:46:27) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]**
Operating System: **Darwin-14.5.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@30435190ef8880901df555bcda0d46902ea81fb5
Link to Log: https://gist.github.com/1e6140d9df1e640184ce
### ERROR
```
SEARCHQUEUE-MANUAL-247824 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by bckwltn** [comment]
### INFO
Python Version: **2.7.10 (default, Jul 14 2015, 19:46:27) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]**
Operating System: **Darwin-14.5.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@30435190ef8880901df555bcda0d46902ea81fb5
Link to Log: https://gist.github.com/fc7b8b6a76591201e114
### ERROR
```
SEARCHQUEUE-MANUAL-264365 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by WebSpider** [comment]
Torrentproject is still having issues. Will see tonight if they have IRC to discuss.

**Comment by DomQuixote** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@136f531f93093a5287b588ca37e19c11153f47a4
Link to Log: https://gist.github.com/ba9604babb8f2d0d6a92
### ERROR
```
SEARCHQUEUE-BACKLOG-82283 :: [HDBits] :: Resulting JSON from provider isn't correct, not parsing it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by DomQuixote** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@136f531f93093a5287b588ca37e19c11153f47a4
Link to Log: https://gist.github.com/282781d1c99612a4a102
### ERROR
```
SEARCHQUEUE-BACKLOG-82283 :: [HDBits] :: Resulting JSON from provider isn't correct, not parsing it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by DomQuixote** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@136f531f93093a5287b588ca37e19c11153f47a4
Link to Log: https://gist.github.com/4dec0c62aeb269e1c78d
### ERROR
```
SEARCHQUEUE-BACKLOG-82283 :: [HDBits] :: Resulting JSON from provider isn't correct, not parsing it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rbnbrls** [comment]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5b5446030ea3c0a1e403cb3f1a02c804e20c2196
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-288799 :: [BitCannon] :: Error while searching BitCannon, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rbnbrls** [comment]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5b5446030ea3c0a1e403cb3f1a02c804e20c2196
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-288799 :: [BitCannon] :: Error while searching BitCannon, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rbnbrls** [comment]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5b5446030ea3c0a1e403cb3f1a02c804e20c2196
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-288799 :: [BitCannon] :: Error while searching BitCannon, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Lowmach1ne** [comment]
### INFO
Python Version: **2.7.10 (default, Nov  3 2015, 20:11:24) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]**
Operating System: **Linux-2.6.32-40-pve-x86_64-with-centos-7.1.1503-Core**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@78fdf429c6bdef4771edc8fa1bf5d73dc5dd55dc
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-281617 :: [FrenchTorrentDB] :: Error while searching FrenchTorrentDB, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Lowmach1ne** [comment]
### INFO
Python Version: **2.7.10 (default, Nov  3 2015, 20:11:24) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]**
Operating System: **Linux-2.6.32-40-pve-x86_64-with-centos-7.1.1503-Core**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@78fdf429c6bdef4771edc8fa1bf5d73dc5dd55dc
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-279227 :: [FrenchTorrentDB] :: Error while searching FrenchTorrentDB, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Lowmach1ne** [comment]
### INFO
Python Version: **2.7.10 (default, Nov  3 2015, 20:11:24) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]**
Operating System: **Linux-2.6.32-40-pve-x86_64-with-centos-7.1.1503-Core**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@78fdf429c6bdef4771edc8fa1bf5d73dc5dd55dc
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-295682 :: [FrenchTorrentDB] :: Error while searching FrenchTorrentDB, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Lowmach1ne** [comment]
### INFO
Python Version: **2.7.10 (default, Nov  3 2015, 20:11:24) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]**
Operating System: **Linux-2.6.32-40-pve-x86_64-with-centos-7.1.1503-Core**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@78fdf429c6bdef4771edc8fa1bf5d73dc5dd55dc
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-295681 :: [FrenchTorrentDB] :: Error while searching FrenchTorrentDB, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Lowmach1ne** [comment]
### INFO
Python Version: **2.7.10 (default, Nov  3 2015, 20:11:24) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]**
Operating System: **Linux-2.6.32-40-pve-x86_64-with-centos-7.1.1503-Core**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@78fdf429c6bdef4771edc8fa1bf5d73dc5dd55dc
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-295743 :: [FrenchTorrentDB] :: Error while searching FrenchTorrentDB, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Lowmach1ne** [comment]
### INFO
Python Version: **2.7.10 (default, Nov  3 2015, 20:11:24) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]**
Operating System: **Linux-2.6.32-40-pve-x86_64-with-centos-7.1.1503-Core**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@78fdf429c6bdef4771edc8fa1bf5d73dc5dd55dc
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-295680 :: [FrenchTorrentDB] :: Error while searching FrenchTorrentDB, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Lowmach1ne** [comment]
### INFO
Python Version: **2.7.10 (default, Nov  3 2015, 20:11:24) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]**
Operating System: **Linux-2.6.32-40-pve-x86_64-with-centos-7.1.1503-Core**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@78fdf429c6bdef4771edc8fa1bf5d73dc5dd55dc
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-265074 :: [FrenchTorrentDB] :: Error while searching FrenchTorrentDB, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Lowmach1ne** [comment]
### INFO
Python Version: **2.7.10 (default, Nov  3 2015, 20:11:24) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]**
Operating System: **Linux-2.6.32-40-pve-x86_64-with-centos-7.1.1503-Core**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@78fdf429c6bdef4771edc8fa1bf5d73dc5dd55dc
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-295829 :: [FrenchTorrentDB] :: Error while searching FrenchTorrentDB, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Lowmach1ne** [comment]
### INFO
Python Version: **2.7.10 (default, Nov  3 2015, 20:11:24) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]**
Operating System: **Linux-2.6.32-40-pve-x86_64-with-centos-7.1.1503-Core**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@78fdf429c6bdef4771edc8fa1bf5d73dc5dd55dc
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-72108 :: [FrenchTorrentDB] :: Error while searching FrenchTorrentDB, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Lowmach1ne** [comment]
### INFO
Python Version: **2.7.10 (default, Nov  3 2015, 20:11:24) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]**
Operating System: **Linux-2.6.32-40-pve-x86_64-with-centos-7.1.1503-Core**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@78fdf429c6bdef4771edc8fa1bf5d73dc5dd55dc
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-81670 :: [FrenchTorrentDB] :: Error while searching FrenchTorrentDB, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Lowmach1ne** [comment]
### INFO
Python Version: **2.7.10 (default, Nov  3 2015, 20:11:24) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]**
Operating System: **Linux-2.6.32-40-pve-x86_64-with-centos-7.1.1503-Core**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@78fdf429c6bdef4771edc8fa1bf5d73dc5dd55dc
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-279121 :: [FrenchTorrentDB] :: Error while searching FrenchTorrentDB, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rbnbrls** [comment]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@9f8ae2924808eaf9f64bb37e09bc45a76b43969c
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-74543 :: [BitCannon] :: Error while searching BitCannon, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Disable proxy
