### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: 'news.md'

### ISSUE THREAD

**Issue by NLEagle1** [SiCKRAGETV/sickrage-issues#2175]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@71b3016de25280fe45f2aa1b779c3434e1979da6
Link to Log: https://gist.github.com/c4510981b6943e0048e7
### ERROR
```
Thread-81 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 271, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 2167, in index
    with open("news.md", "r") as newsfile:
IOError: [Errno 2] No such file or directory: 'news.md'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by palmfighter** [comment]
fixed in latest commit.
SR Version:	BRANCH: (master) / COMMIT: (aaf6782aca63b017414db3e8083de018d8f0b5f5)
