### ISSUE TITLE
[APP SUBMITTED]: No suitable RAR unpacker installed

### ISSUE THREAD

**Issue by Sarcas666** [SiCKRAGETV/sickrage-issues#2180]
### INFO
Python Version: **2.7.6 (default, Sep  9 2014, 15:04:36) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]**
Operating System: **Darwin-14.4.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@0657d64e2d0d3feb159d0a41e9b3a407cf520618
No Log available with ERRORS: 
### ERROR
```
Thread-186 :: Rar Not Supported: No suitable RAR unpacker installed
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/wiki/Frequently%20Asked%20Questions#error-rar-not-supported-no-suitable-rar-unpacker-installed
