### ISSUE TITLE
Network Icon - Fox Crime

### ISSUE THREAD

**Issue by Veldkornet** [SiCKRAGETV/sickrage-issues#2181]
The network icon for "FOX Crime" is currently missing and shows a broken image icon. 
Could someone add it?

![screenshot 2015-07-17 22 14 34](https://cloud.githubusercontent.com/assets/10297361/8756291/b336380a-2cc0-11e5-9099-4787c0dbeb4f.png)

**Comment by fernandog** [comment]
@neoatomic

**Comment by neoatomic** [comment]
Added the Fox Crime logo. Should be fixed with the next update.
