### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-157631 :: Torrent file content is empty

### ISSUE THREAD

**Issue by megabitus98** [SiCKRAGETV/sickrage-issues#2182]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-43-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@0657d64e2d0d3feb159d0a41e9b3a407cf520618
Link to Log: https://gist.github.com/990414c6d335d4b967ff
### ERROR
```
SEARCHQUEUE-BACKLOG-157631 :: Torrent file content is empty
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@megabitus98 do you have proxy enabled for TPB?

try to manually download that torrent and add to your client. See if the torrent is ok

**Comment by megabitus98** [comment]
No, I have no proxy, I searched the torrent manually and added it and it works and in the logs I get this errors: 
2015-07-17 23:45:02 ERROR    SEARCHQUEUE-BACKLOG-157631 :: Torrent file content is empty
2015-07-17 23:45:02 WARNING  SEARCHQUEUE-BACKLOG-157631 :: Content-Encoding was gzip, but content was not compressed
2015-07-17 23:45:01 INFO     SEARCHQUEUE-BACKLOG-157631 :: Downloading Rookie.Blue.S05E11.1080p.WEB-DL.DD5.1.H.264-KiNGS[rartv] from Rarbg
AANone

**Comment by miigotu** [comment]
This is a bug with tpb site itself. especially RSS.

**Comment by miigotu** [comment]
tpb provider needs rewritten completely now.

**Comment by fernandog** [comment]
News until fix?

**Comment by miigotu** [comment]
It works sometimes, just not all of the time.

Change the log line from ERROR to WARNING or DEBUG
`Torrent file content is empty`

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/commit/95ac7be53e318d79033c886deb26b04a5a05903f

**Comment by fernandog** [comment]
@megabitus98 try use rarbg provider and disable TPB

**Comment by miigotu** [comment]
@fernandog there should probably be a tip under the post process method selection, saying recommended is hard link (if both places are on the same partition) and keep seeding.

rarbg needs more seeds lol

**Comment by miigotu** [comment]
This ERROR will now just be a warning, because there is nothing we can do about their site issues.
