### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by fantom1** [SiCKRAGETV/sickrage-issues#2183]
Can no longer display a show and get redirected back to the the list of shows.

2015-07-18 00:24:33 Thread-15 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1322, in displayShow
    return t.respond()
  File "/opt/sickbeard/cache/cheetah/_opt_sickrage_gui_slick_interfaces_default_displayShow_tmpl.py", line 704, in respond
    info_flag = VFN(VFN(VFFSL(SL,"subtitles",True),"fromietf",False)(VFFSL(SL,"show.lang",True)),"opensubtitles",True)
  File "/opt/sickrage/sickbeard/subtitles.py", line 70, in fromietf
    return babelfish.Language.fromopensubtitles(language)
  File "/opt/sickrage/lib/babelfish/language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "/opt/sickrage/lib/babelfish/converters/opensubtitles.py", line 29, in reverse
    if opensubtitles in self.from_opensubtitles:
  File "/usr/lib/python2.7/_abcoll.py", line 369, in __contains__
    self[key]
  File "/opt/sickrage/lib/babelfish/converters/__init__.py", line 46, in __getitem__
    return self._store[key.lower()][1]
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by fantom1** [comment]
Forgot to add:

SR Version: 	BRANCH: (master) / COMMIT: (0657d64e2d0d3feb159d0a41e9b3a407cf520618) 
Python Version:	2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]

**Comment by fantom1** [comment]
Tried with the most recent code and the the issue is still there

SR Version: 	BRANCH: (master) / COMMIT: (87d81ff0ace0d78065ccaf195cb247b742fb701a)

**Comment by fernandog** [comment]
@miigotu hotfix?

**Comment by miigotu** [comment]
No, because this error doesn't make sense.

Try deleting cache/cheetah

If that doesn't work, you could run some sql on your db and let SR refresh subs form your directories for all episodes:

To try that, stop SickRage, backup your DB, and run this from inside your SickRage dir:
```bash
sqlite3 sickbeard.db
```
then in the sqlite prompt:
```sql
UPDATE tv_episodes SET subtitles = '';
```
Start SickRage back up and see what happens.

**Comment by fantom1** [comment]
Tried both and the issues still exists for all the same shows. Anything else I could try and/or provide more info?

**Comment by miigotu** [comment]
Do these shows have any subtitles existing? Are you using multi-subs or no? Embedded subs enabled?

**Comment by fernandog** [comment]
@fantom1 did you stoped SR and deleted /SickRage/cache/cheetah folder??

**Comment by miigotu** [comment]
ah, wait, its the show info lang.

**Comment by fantom1** [comment]
stop
clear cache/cheeta
start

test

stop
manipulate the db
start

**Comment by miigotu** [comment]
@fantom1 can you try this?

edit gui/slick/interfaces/default/displayShow.tmpl:
findline 287 and change it from:
`#set $info_flag = $subtitles.fromietf($show.lang).opensubtitles`
to
`#set $info_flag = $subtitles.fromietf($show.lang).opensubtitles if $show.lang else ''` 

restart SR.

**Comment by fantom1** [comment]
Just checked that some of the shows that does not work has no single episode in them.

embedded_subtitles_all = 0

**Comment by fantom1** [comment]
Awesome; it works now after the code change. I am hoping this change will get committed.
Thanks for fixing this so quick.

**Comment by miigotu** [comment]
@fernandog can you commit that? i'll cherry-pick it to master when you're done.

**Comment by miigotu** [comment]
@fantom1 after the change is committed and before updating SR, you will need to `git reset --hard` from SR dir, or the update will fail.

**Comment by fantom1** [comment]
yup, thx.

**Comment by fernandog** [comment]
@miigotu 
hotfix isnt?

**Comment by miigotu** [comment]
doing it by commit to develop and then cherry pick to master is the same thing as the other hotfix method. It's easier and when merge to master you have no issues.
