### ISSUE TITLE
When airdate is 'never' don't set episode as SKIPPED but as UNAIRED

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#2184]
probably an issue as the code is:

```
            # if it hasn't aired yet set the status to UNAIRED
            if self.airdate >= datetime.date.today() and self.status in [SKIPPED, UNAIRED, UNKNOWN, WANTED]:
                logger.log(u"Episode airs in the future, marking it " + str(UNAIRED), logger.DEBUG)
                self.status = UNAIRED
```

but if aired is 'never' it will never meet this condition 

https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/tv.py#L1789-L1792

**Comment by miigotu** [comment]
I don't see a problem here.

**Comment by fernandog** [comment]
@miigotu its a consistence thing =)

**Comment by miigotu** [comment]
it sets episodes with airdate never to skipped, then when the ep gets an airdate it will change it to unaired or wanted again, even though it was skipped when it had no airdate.

Code is correct here, or it will break other places.

**Comment by miigotu** [comment]
@fernandog some episodes never air, and for example we don't want the ui showing we are missing episodes for episodes which will never air.

**Comment by fernandog** [comment]
if they never get aired, episode will be always UNAIRED. Skipped is something that got aired and SR didn't snatched

**Comment by miigotu** [comment]
try it, but I feel like something else is gonna break =P
