### ISSUE TITLE
"Archived" episodes never switch to "Ignored"

### ISSUE THREAD

**Issue by fantom1** [SiCKRAGETV/sickrage-issues#2186]
"Default deleted episode status == Ignored" does not seem to apply to "Archived" episodes: they remain "Archived" after the episodes are deleted.

**Comment by miigotu** [comment]
Thats what archive was originally intended for, files that are not in your library but you have had before and are just "archived" on another storage

**Comment by fantom1** [comment]
Hmm, I am using "Archived" to exclude files from backlog searches and thought the status would switch to "Ignored" once the episode is deleted. I guess I misunderstood then.

**Comment by miigotu** [comment]
Well where the confusion came about is that someone repurposed the status to mean it's quality was 'Best of your wanted qualities'

I'm not sure how I want to proceed with that, maybe it should stay a sort of hybrid of the two.

**Comment by fantom1** [comment]
For what I need I could use "Downloaded Unknown" then. It works just like I want...

**Comment by fernandog** [comment]
i think the archive is: I have, not in my shows dir, don't want to download anymore. just like you said.

@fantom1 to exclude from backlog search just set "archive on the first match"
read it here: https://github.com/SiCKRAGETV/SickRage/wiki/Quality-Settings
