### ISSUE TITLE
[APP SUBMITTED]: cannot import name RTorrent

### ISSUE THREAD

**Issue by scenejinx** [SiCKRAGETV/sickrage-issues#2188]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-57-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@e38274d6f33bc2e15092367a8e2aa6bee5e4da5f
Link to Log: https://gist.github.com/2a81e7f9b3f7fc46821c
### ERROR
```
Thread-41 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 814, in testTorrent
    client = clients.getClientIstance(torrent_method)
  File "/opt/sickrage/sickbeard/clients/__init__.py", line 118, in getClientIstance
    module = getClientModule(name)
  File "/opt/sickrage/sickbeard/clients/__init__.py", line 114, in getClientModule
    return __import__(prefix + name, fromlist=__all__)
  File "/opt/sickrage/sickbeard/clients/rtorrent.py", line 25, in <module>
    from rtorrent import RTorrent
ImportError: cannot import name RTorrent

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by scenejinx** [comment]
latest update broke rtorrent downloads, please look into it

**Comment by fernandog** [comment]
@miigotu 
https://github.com/SiCKRAGETV/SickRage/commit/762a0e4d8c14b0a2947adbfa72c91f4151966a5f#diff-d882e742959648fde7262b71641f12d9R25

**Comment by scenejinx** [comment]
btw, that error occurs when I test rtorrent connection

**Comment by fernandog** [comment]
will be fixed soon. sorry

**Comment by miigotu** [comment]
few minutes

**Comment by miigotu** [comment]
actually this one is a little more complicated. alot of lines to change.

**Comment by scenejinx** [comment]
yeah i had a feeling that would be the case lol

**Comment by miigotu** [comment]
https://github.com/SiCKRAGETV/SickRage/commit/53ce36a9dc336907f81d63e2d0d455c27d11b299

Test develop please before I merge to master.

**Comment by scenejinx** [comment]
ok will do

**Comment by miigotu** [comment]
@fernandog there may be a few import issues over the next week or so, because I removed lib from all of the import paths (necessary), and there are sometimes conflicts because for instance `import rtorrent` from inside `sickbeard/clients/rtorrent.py` tries to import itself as it's own directory is the first search path.

growl and trakt I had this issue with when I did the change also, so hopefully they are done now. (I had just to rename the trakt and growl libs to libtrakt and libgrowl)

**Comment by fernandog** [comment]
Travis build dont detect this import errors?

**Comment by scenejinx** [comment]
Its fixed? I cant switch to dev build for some reason, getting "Can't switch branch as this will result in a database downgrade"

**Comment by miigotu** [comment]
@fernandog nope, no tests call any notifiers or clients because they are dynamically loaded modules.

**Comment by miigotu** [comment]
@scenejinx how did your db get upgraded?

**Comment by miigotu** [comment]
Well, testing connection on each of the clients doesn't cause an import exception here, so pretty sure it is fine. Just gonna merge and cross my fingers.

**Comment by scenejinx** [comment]
not sure, i do remember being on dev build a while ago and was having trouble switching to master. now I cant remember exactly what I did but im guessin It didnt fix it lol

**Comment by miigotu** [comment]
On a build from some other fork apparently or you would never have that error. Your db is fooked lol.

**Comment by miigotu** [comment]
Either way, the changes are now released in master, along with a few other fixes.

**Comment by scenejinx** [comment]
Alright thanks, I'll give it a try now

**Comment by scenejinx** [comment]
Its still giving me the same error

**Comment by scenejinx** [comment]
and I tried on another sickrage server that i was hesitant to update, with the same result

**Comment by scenejinx** [comment]
![image](https://cloud.githubusercontent.com/assets/13388450/8759976/264442ec-2cfd-11e5-9e7f-3425bd1c1549.png)

**Comment by fernandog** [comment]
Open viewerror and post error please

**Comment by scenejinx** [comment]
2015-07-18 03:34:15 Thread-51 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 814, in testTorrent
    client = clients.getClientIstance(torrent_method)
  File "/opt/sickrage/sickbeard/clients/__init__.py", line 118, in getClientIstance
    module = getClientModule(name)
  File "/opt/sickrage/sickbeard/clients/__init__.py", line 114, in getClientModule
    return __import__(prefix + name + '_client', fromlist=__all__)
  File "/opt/sickrage/sickbeard/clients/rtorrent_client.py", line 25, in <module>
    from rtorrent import RTorrent
  File "/opt/sickrage/sickbeard/clients/rtorrent.py", line 25, in <module>
ImportError: cannot import name RTorrent

**Comment by scenejinx** [comment]
ImportError: cannot import name RTorrent
    from rtorrent import RTorrent
  File "/opt/sickrage/sickbeard/clients/rtorrent.py", line 25, in <module>
    return __import__(prefix + name, fromlist=__all__)
  File "/opt/sickrage/sickbeard/clients/__init__.py", line 114, in getClientModule
    module = getClientModule(name)
  File "/opt/sickrage/sickbeard/clients/__init__.py", line 118, in getClientIstance
    client = clients.getClientIstance(sickbeard.TORRENT_METHOD)()
  File "/opt/sickrage/sickbeard/search.py", line 137, in snatchEpisode
    self.success = search.snatchEpisode(searchResult[0])
  File "/opt/sickrage/sickbeard/search_queue.py", line 184, in run
2015-07-18 02:07:07 ERROR    Thread-56 :: Failed doing webui callback: Traceback (most recent call last):

**Comment by fernandog** [comment]
Are you sure you updated?
Stop SR. SSH,Enter sickrage folder and run:
git checkout master
git pull
start SR

**Comment by scenejinx** [comment]
It updated, but I will try that anyway

**Comment by scenejinx** [comment]
"Your branch is up-to-date with 'origin/master'."

**Comment by miigotu** [comment]
`File "/opt/sickrage/sickbeard/clients/rtorrent.py`

That doesnt even exist anymore, are you suuuuure? lol
try:

Stop SR
```
git remote show origin
git fetch origin
git reset --hard origin/master
git checkout master
git pull
```
Start SR


Show output from that

**Comment by miigotu** [comment]
Also, make sure the error you are seeing is from after the restart.

**Comment by scenejinx** [comment]
Interesting, I am sure that rtorrent.py was there before the update, now its gone on both SR servers

I ran;
root@SEEDBOX:/opt/sickrage# git reset --hard origin/master
HEAD is now at ea89758 Merge branch 'develop'
root@SEEDBOX:/opt/sickrage# git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
root@SEEDBOX:/opt/sickrage# git pull
Already up-to-date.

But rtorrent.py still isn't showing

**Comment by scenejinx** [comment]
oh you mean rtorrent.py doesn't exist now? But Im still getting that error after the restart

**Comment by miigotu** [comment]
try `rm sickbeard/clients/*.pyc`

**Comment by miigotu** [comment]
rtorrent.py was renamed to rtorrent_client.py

**Comment by scenejinx** [comment]
oh, it was that simple lol

**Comment by scenejinx** [comment]
all working fine now after those .pyc were removed

**Comment by miigotu** [comment]
strange.

**Comment by scenejinx** [comment]
shouldnt the update take care of that? or even the git reset

**Comment by miigotu** [comment]
I wish there was a way, but sadly no. git ignores the pyc completely, and they are supposed to be auto handled by your python interpreter

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/2226
