### ISSUE TITLE
Network Icons - Global, ABC (JA)

### ISSUE THREAD

**Issue by megabitus98** [SiCKRAGETV/sickrage-issues#2192]
The networks icon for Global, ABC (JA) are missing, could someone add them, please? 
![Image of Global](http://puu.sh/j3vkU/8f55b95370.png)
![Image of ABC](http://puu.sh/j3vmd/0ebcdab033.png)

**Comment by miigotu** [comment]
@neoatomic please?

**Comment by neoatomic** [comment]
@megabitus98 I added the logos for you. Should be fixed on the next update.

**Comment by miigotu** [comment]
Thanks @neoatomic
