### ISSUE TITLE
Repeated notifications for already downloaded TV episode

### ISSUE THREAD

**Issue by user020** [SiCKRAGETV/sickrage-issues#2194]
BRANCH: (master) / COMMIT: (ea897589698c18007ff0fd062b224d68d76d3bb5)
OS: Win7 x64 VM on ESXi 5.5 host
Python Version: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]

I have SickRage configured to send Pushbullet notifications to my Nexus 5 phone. I keep getting notifications about an episode I've already downloaded from BTN as part of a 1080p WEB-DL season pack (The Walking Dead S5E09 'What Happened And What's Going On'). I have the Initial quality show set to 1080p WEB-DL and Replace With set to 1080p Blu-Ray (which isn't available yet). The download location is a share on my Napp-It VM.

I get maybe 2-3 Pushbullet notifications per day saying that this particular episode has downloaded even though no new downloads show up in my torrent client (uTorrent 2.2.1). This is after adding the show through TVDb or TVrage. Even pausing or deleting/re-adding the show doesn't seem to stop the notifications for this particular episode and I've also tried clearing Pushbullet data on my phone.

Let me know if you require any more information e.g. log files.

![image_319](https://cloud.githubusercontent.com/assets/13383433/8761124/26da8e10-2d38-11e5-99b2-a205873cd5d2.jpg)

**Comment by neoatomic** [comment]
Please add a full log with debug=1 enabled so we can take a closer look.

**Comment by user020** [comment]
Here's my sickrage.log with debug=1 enabled, just after I received another notification for the episode at 11:56 AM (BST).

https://gist.github.com/user020/9c5a5ce7d5d8d27ec1ac#file-gistfile1-txt

**Comment by neoatomic** [comment]
@user020 Can it be that those episodes are still seeding.? ( so the files are in use.?)
Or that you have set the permissions wrong for that share.?

Every time SickRage scans your tv download folder and finds a episode it will sent a notification. But if SickRage cant move/delete the file they stay in the folder. And next time Sickrage scans the folder it finds the same episode and notifies you again.

**Comment by miigotu** [comment]
1. Why processing from a samba share?
2. Permissions from the samba share might be wrong
```
File T:\The Walking Dead\Season 2\The Walking Dead.S02E03.Save the Last One.mkv is the same size as \\192.168.1.9\public\Torrents\The.Walking.Dead.S02.BluRay.1080p.AC3.x264-CHD\The.Walking.Dead.S02E03.BluRay.1080p.AC3.x264-CHD.mkv
2015-07-18 11:56:55 DEBUG    POSTPROCESSER :: File exists and new file quality is lower than existing, marking it unsafe to replace

\\192.168.1.9\public\Torrents\The.Walking.Dead.S02.BluRay.1080p.AC3.x264-CHD\The.Walking.Dead.S02E03.BluRay.1080p.AC3.x264-CHD.mkv
```

**Comment by user020** [comment]
Yes the episodes are still seeding from a Samba share but I only keep receiving notifications for the one episode mentioned in my original post and *no others* even though they're all seeded from the same folder. I've been using this setup for about 6 months without any problems.

There doesn't appear to be anything abnormal about the episode file apart from the garbled title in the screenshot I attached - I downloaded it as part of a WEB-DL season pack and do not receive notifications for any other episodes in the pack.

**Comment by miigotu** [comment]
@user020 For some reason the initial PP of that episode failed, so it never got set in the DB that this file was already processed. Every PP run after that tries to process it again, since it doe not know it processed it before, but it also fails again because the file had already been moved to the destination. This loop happens every time the PP runs.

I suggest you rename the one in your Library, and let it successfully PP the one on your share, so that the processed file gets added to the db.

**Comment by user020** [comment]
The problem is still occurring unfortunately. I deleted the series in the library and let SickRage PP the season pack again from my downloaded torrent (see log and screenshot):

https://gist.github.com/user020/394690edf9b9bb10c2fe

![screen1](https://cloud.githubusercontent.com/assets/13383433/8803725/68cf57c6-2fc0-11e5-90cd-46f25a1cd3f3.PNG)

This completed successfully but I'm still getting multiple notifications for that single episode and no others:

![screen2](https://cloud.githubusercontent.com/assets/13383433/8803781/ce3b01d2-2fc0-11e5-9517-1fe9010e68ea.png)

**Comment by fernandog** [comment]
@miigotu probally SR is getting confused because that episode has special chars in EP name

@user020 please post the file name of that episode

**Comment by user020** [comment]
The filename when the torrent downloads is **The.Walking.Dead.S05E09.1080p.WEB-DL.DD5.1.H.264-Cyphanix.mkv**. After post-processing, this gets renamed to **The Walking Dead.S05E09.What Happened and What’s Going On.mkv**.

Those special characters shouldn't be in the episode name but for some reason, it's adding them to the episode title whether I add the show from the TVDb or TVrage in SR even though both sites have the correct episode name.

**Comment by miigotu** [comment]
locale?

**Comment by user020** [comment]
EN-GB (assuming you mean my machine's locale).

**Comment by miigotu** [comment]
I would try setting to en_utf-8

**Comment by user020** [comment]
Setting what to en_utf-8?

**Comment by fernandog** [comment]
He is windows. Dont know if is related

Try run before run SR:
chcp 65001

**Comment by miigotu** [comment]
maybe same problem as https://github.com/SiCKRAGETV/sickrage-issues/issues/2319 ?

**Comment by user020** [comment]
I ran chcp 65001 and updated to the latest Master branch (cc698786d1f440ca7017a36ed60831df78ebb391). Then, I disabled text_factory and the episode title is now scraped correctly at least. Will leave it for a few days to see if SR/Pushbullet give any further download notifications but I suspect there won't be. Thanks for the help!
