### ISSUE TITLE
Sickrage stop snatching from NZGGeek

### ISSUE THREAD

**Issue by rickytin** [SiCKRAGETV/sickrage-issues#2196]
Almost all my show are snatched from NzbGeek that it's my first provider and since 2 weeks ago it is snatching from my second provider.
I did a test in SickRage so I deselect all my provider except NzbGeek and it's not finding anything but all the shows are available in NzbGeek.

What can be the problem.

Here are my logs
https://gist.github.com/rickytin/ef436523cc740c6bb9ee

**Comment by rickytin** [comment]
I did another test and install Sonarr and use only NZGGeek as provider and in Sonarr is snatch the show.
So I don't know what can be the problem.
Any help would be appreciated.

**Comment by neoatomic** [comment]
@rickytin 
Your log says  `URL check failed. Bad result from provider` and ` Connection error to https://api.nzbgeek.info/ ` etc. 

So this is highly likely a SSL problem. See the below guide, especially the part about `Install pyOpenSSL` 
http://www.htpcguides.com/install-sickrage-windows-usenet-torrent-tv/

Also go to General -> Advanced settings and disable `Verify SSL Certs`
That should solve it.

```
2015-07-18 06:24:04 INFO     SEARCHQUEUE-MANUAL-259063 :: Quality of Hannibal.S03E05.1080p.WEB-DL-NZBgeek is 1080p WEB-DL
2015-07-18 06:24:04 WARNING  SEARCHQUEUE-MANUAL-259063 :: Connection error to https://api.nzbgeek.info/api?t=get&id=995bbf0ff12fb4c1e2c9de25e891b31b&apikey=**********
2015-07-18 06:24:04 INFO     SEARCHQUEUE-MANUAL-259063 :: Skipping Hannibal.S03E05.1080p.WEB-DL-NZBgeek, URL check failed. Bad result from provider.
```

**Comment by rickytin** [comment]
Thanks for the help Neoatomic
I have install pyOpenSSL that HTPCguides mention but I re downloaded and install it again and then did a restart of my computer, I disable verify SSL Certs and I also change from https to http, but sill it docent snatch from NzbGeek.
Here my logs:
https://gist.github.com/rickytin/e48c09ff7ea549127dc0

**Comment by neoatomic** [comment]
@rickytin The log doesn't contain a search for nzbgeek. So cant see if anything changed.

Do you know if you need to donate to NZBGeek to get an api key.? I see i have an account there but cant find the api key to test/replicate your problem.

**Comment by rickytin** [comment]
Again thanks for the help.
Yes I have a NZBGeek VIG Membership that expire next year. You find the Api Key in your NZBGeek account profile.
I try with different shows to see if it appear in the log.
https://gist.github.com/rickytin/f9abe710d021558866ca

**Comment by fernandog** [comment]
@miigotu what if provider don't accept a head request?

**Comment by fernandog** [comment]
contacted nzbgeek admin. waiting for a response

**Comment by miigotu** [comment]
If they don't accept head request, with apikey, they need to fix it. Explain it is for their benefit

**Comment by powaking** [comment]
When was the option to disable verify certificate added? I don't recall seeing that option there and I was having issues on my QNAP with my indexer (dognzb.cr). Disabling verification of certificate resolved my issue.

**Comment by miigotu** [comment]
@powaking see the changelog, released in master 3 days ago.
[full changelog](https://github.com/SiCKRAGETV/SickRage/compare/v4.0.31...v4.0.32)

**Comment by rickytin** [comment]
Thanks to al for the help, I contact nzbgeek and this is what they said:
1. SickRage recently made changes to the way it downloads the NZB file once it has found a match to verify it is a valid NZB file. 
The method SickRage is using is not supported by our API servers.
We will look into the method SickRage is using and consider updating the API servers.
2. The team at SickRage have made a small change for NZBgeek to allow the old method while we look to support the new method and test it.

A question, the change is in what version master or develop.

**Comment by tvann2182** [comment]
Master I also tried develop as I seen there was a fix in develop but this
also did not work so I switched back to master but this did not work either

**Comment by miigotu** [comment]
@rickytin this was fixed yesterday, it works, and has been tested.

**Comment by miigotu** [comment]
@tvann2182 @rickytin check that the categories are in the url: `&cat=5030,5040`

In your ini the categories might be missing under `newznab_data =`

Make sure the NZBGeek part there says:
NZBGeek|https://api.nzbgeek.info/|apikeyhere|5030,5040|0|eponly|0|1|1

NZBGeek is no longer a custom provider ^

**Comment by rickytin** [comment]
Thanks for the replay Miigotu, this morning I update SickRage and check what you mention but it didn't work for me. I check categories and they are ok but I am not sure what you mean with:
"Make sure the NZBGeek part there says:
NZBGeek|https://api.nzbgeek.info/|apikeyhere|5030,5040|0|eponly|0|1|1"

Thanks for the patience and help.

**Comment by fernandog** [comment]
@rickytin open your config.ini and search for NZBGeek|https://api.nzbgeek.info/ ............

**Comment by rickytin** [comment]
Ok thanks Fernandog, I will try it tonight.

**Comment by rickytin** [comment]
Thanks for the big patience but I verify in config.ini and make sure that the NZBGeek is writing exactly like this "NZBGeek|https://api.nzbgeek.info/|apikeyhere|5030,5040|0|eponly|0|1|1" obviously it have my Api Key but I still cant snatch from NZBGeek.

**Comment by miigotu** [comment]
You have a proxy enabled?

**Comment by fernandog** [comment]
@rickytin as always, need full logs with debug enabled in general settings

**Comment by rickytin** [comment]
Sorry Miigotu I don't know what you mean with proxy enabled.
Fernandog here is my full log:
 https://gist.github.com/rickytin/210d31207ff2aa9a9bfc

**Comment by miigotu** [comment]
@rickytin Also go to General -> Advanced settings and disable Verify SSL Certs

NZBGeek works 100% here.

**Comment by rickytin** [comment]
SSL it's disable and has always been disable.
By proxy, if you mean the proxy host in General -> Advanced settings it's blank so it's disable.
A question in config.ini there is this part:
[NZBGEEK]
nzbgeek = 1
nzbgeek_search_mode = eponly
nzbgeek_search_fallback = 1
nzbgeek_enable_daily = 1
nzbgeek_enable_backlog = 1

Should I change search_fallback to 0 or it's OK

**Comment by miigotu** [comment]
Changing search fallback will have no effect. I would double check your api key. This 100% works here, SSL/NoSSL, Proxy/NoProxy

**Comment by rickytin** [comment]
I triple check my api and it's OK. I don't know what else to do but thanks for the help.

**Comment by powaking** [comment]
Have you tried to remove the configuration for NZBgeek and then re-add it back in?

**Comment by fernandog** [comment]
@rickytin did you removed the custom nzb site for nzbgeek???

**Comment by fernandog** [comment]
there's an official provider for nzbgeek now

**Comment by rickytin** [comment]
No I didn't remove the costume nzbgeek, I will try it tonight and let everybody know.
Nice support and thank you all for the help.

**Comment by rickytin** [comment]
I am not able to delete nzbgeek from custom nzb, the delete button is not working

**Comment by rickytin** [comment]
Sorry for bothering again, I still can't delete the custom nzbgeek, I try to modify config.ini to remove the custom nzbgeek but with no luck.

**Comment by fernandog** [comment]
Button is disabled or what?

**Comment by rickytin** [comment]
Yes

**Comment by rickytin** [comment]
A screen capture:
https://drive.google.com/file/d/0B_U9joUtbqeMUW9FdzVOVHY4dkE/view?usp=sharing

**Comment by fernandog** [comment]
@rickytin check thoses errors. what are they?

**Comment by rickytin** [comment]
2015-07-23 08:07:01 SEARCHQUEUE-BACKLOG-148581 :: [NZBGeek] :: Authentication error: Your authentication credentials for NZBGeek are missing, check your config.

**Comment by fernandog** [comment]
so have Team viewer ? send me via IRC private

**Comment by rickytin** [comment]
Yes I have Team viewer, sorry I don't know how to send via IRC private

**Comment by fernandog** [comment]
click on my nickname and choose "message"

**Comment by rickytin** [comment]
I click your nickname and it take me to your github profile, I don't see message

**Comment by fernandog** [comment]
IRC!! open sickrage, click IRC tab!

**Comment by rickytin** [comment]
OK, I am connected

**Comment by rickytin** [comment]
Sorry but the nzbgeek custom is still there I restart SickRage but did not work

**Comment by fernandog** [comment]
try to delete again. add the api key again, remove and save

**Comment by rickytin** [comment]
I add my api but the delete button is not working

**Comment by fernandog** [comment]
Add api key. SAVE. Open provider settings again. Delete.

**Comment by rickytin** [comment]
After a few try I did delete nzbgeek from custom but I still cant download shows with NZBGeek.
I verify that the api is ok and I also verify that  config.ini  have the information that miigotu provide.

**Comment by fernandog** [comment]
see if you have that error in your log: 
global name 'params' is not defined

just fixed in develop

**Comment by rickytin** [comment]
I am in master so I am trying to change to develop but the update wasn't successful

**Comment by fernandog** [comment]
don't switch to develop

**Comment by rickytin** [comment]
Ok but I still have the download problem from NZBGeek

**Comment by fernandog** [comment]
You have to wait we merge into master

**Comment by rickytin** [comment]
Thinking that the SickRage I have is corrupted I did a test and install a fresh SickRage, then I add sabnzbd settings and NZBGeek but I still can't download from NZBGeek.
The Api was check and I also verify that config.ini have the information that miigotu provide.
I am the only one with this problem.

**Comment by rickytin** [comment]
Thanks Fernandog for all the help, I will wait for the merge into master.

Again thank you. Gracias

**Comment by rickytin** [comment]
It's frustrating, still not working for me I can't snatch from NZBGeek.

**Comment by fernandog** [comment]
Need logs

**Comment by miigotu** [comment]
@rickytin We've been asking for a week for a full log with DEBUG enabled. We cannot help you further without that.

**Comment by rickytin** [comment]
Here is my new log with debug, sorry I thought debug was already selected in advances settings.
https://gist.github.com/rickytin/318638554bed23b66558

**Comment by rickytin** [comment]
And thanks for your patience fernandog and @miigotu.

**Comment by miigotu** [comment]
@rickytin there are no searches in that log.

**Comment by edru** [comment]
Not to beat a dead horse but I am getting this from 3 different providers. NZB.su, DogNZB.cr, and Althub.co.za.

Seems to be impatcing every single provider I use.

**Comment by miigotu** [comment]
@edru SR is working perfectly fine. Make sure you are up to date, wait a day and see how it is working, and if you are still having issues, talk to your providers about them blocking SR.

We have fixed every possible issue and everything any provider has had an issue with, yet they choose to block still. NZBGeek and NZB.cat are supportive of SR, among others. I suggest using a SickRage friendly provider.

**Comment by edru** [comment]
I am using 3 that have worked ever since using sickrage. I left on vacation everything working fine and then came back 4 days later and I have countless errors.

Fully up to date, even did a hard reset and fetch.

http://pastebin.com/gwipaewe

Dont know what could have changed between Saturday and now.

**Comment by fognl** [comment]
Same issue here as edru, unable to perform backlog searches.  Here is a log of me attempting a backlog search on a couple of tv shows using nzbs.org and nzbgeek: http://pastebin.com/ndDbsA1c

**Comment by miigotu** [comment]
@fognl thats a totally diff problem. hotfix coming in a few seconds.

**Comment by miigotu** [comment]
@fognl pls update, hotfix applied.

**Comment by edru** [comment]
Just got a response from my main provider when asking if they blocked sickrage:

No.
Should be a similar setup on Sick Beard, are your settings correct?



altHUB team
admin@althub.co.za

---

Like I stated I was gone on vacation so no settings changed. 

If I restart it I get about 206 errors after the search on startup is finished.

**Comment by miigotu** [comment]
@edru did my hotfix fix your problem?

**Comment by rickytin** [comment]
I was on vacation and that why I haven't replay.
I update to the latest SickRage and everything is working perfect, NZBGeek is working again.
Edru I have altHUB and it's working in my system.
Again thanks Miigotu and Fernandog for all the help.

**Comment by edru** [comment]
@miigotu Seems to have fixed the issue. Flight home was canceled so got sucked into that BS last night after posting last night.

Verified it was up to date, and restarted. Everything seem sto be fine now. Really appreciate the fix!
