### ISSUE TITLE
Can't open a show's page

### ISSUE THREAD

**Issue by Saskya99** [SiCKRAGETV/sickrage-issues#2197]
When I try open a show page. I get this error :
```
2015-07-18 12:30:16 Thread-30 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1322, in displayShow
    return t.respond()
  File "/opt/sickrage/cache/cheetah/_opt_sickrage_gui_slick_interfaces_default_displayShow_tmpl.py", line 1335, in respond
    for sub_lang in [VFN(VFFSL(SL,"subtitles",True),"fromietf",False)(x) for x in VFN(VFFSL(SL,"epResult",True)["subtitles"],"split",False)(',') if VFFSL(SL,"epResult",True)["subtitles"]]: # generated from line 581, col 13
  File "/opt/sickrage/sickbeard/subtitles.py", line 70, in fromietf
    return babelfish.Language.fromopensubtitles(language)
  File "/opt/sickrage/lib/babelfish/language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "/opt/sickrage/lib/babelfish/converters/opensubtitles.py", line 36, in reverse
    raise LanguageReverseError(opensubtitles)
LanguageReverseError: u'fra'
```

**Comment by neoatomic** [comment]
@Saskya99 Have you updated to the newest version.? This was already fixed 2 days ago.
https://github.com/SiCKRAGETV/sickrage-issues/issues/2125#issuecomment-121795614

**Comment by Saskya99** [comment]
yes this morning... :/

**Comment by neoatomic** [comment]
@Saskya99 Can you add what version you are on and the other info as in the guidelines for posting an issue.? https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket

@miigotu Is there a reason why this bug can still be present after the fix.?

**Comment by Saskya99** [comment]
SR Version:	BRANCH: (master) / COMMIT: (ea897589698c18007ff0fd062b224d68d76d3bb5) 
Python Version:	2.7.9 (default, Mar 1 2015, 12:57:24) [GCC 4.9.2]
OS : debian jessie

**Comment by fernandog** [comment]
stop SR,
enter SR directory

run:

sqlite3 -cmd ".timeout 5000" sickbeard.db UPDATE tv_episodes SET subtitles = REPLACE(subtitles, 'fra', 'fr') WHERE subtitles LIKE '%fra%";

**Comment by Saskya99** [comment]
thanks 
no more errors :)

**Comment by miigotu** [comment]
@neoatomic because the FRA was added after the hard coded date I added in the check. I didn't want the tvcheck happening on every boot.
