### ISSUE TITLE
Accents and symbols in show names

### ISSUE THREAD

**Issue by RadeoSuicide** [SiCKRAGETV/sickrage-issues#2198]
BRANCH: (master) / COMMIT: (0657d64e2d0d3feb159d0a41e9b3a407cf520618) 
Windows 8.1 64-Bit
Python 2.7.9
OpenSSL 1.0.1j

https://gist.github.com/RadeoSuicide/6f350cfc4cfa35b76102

After adding Two and A Half Men to my sickrage as a new show, it pulled all of the usual info from theTVDB.
One of the episodes has an "é" in it;
Two.and.a.Half.Men.S12E08.Family.Bublé.Deep.Fried.Turkey
and another has an apostrophe in it " ' " and these two symbols show up in my sickrage just for these two episodes as ÃƒÂ© instead of "é" and Ã¢â‚¬â„¢ instead of " ' ".
This causes it to not recognise my episodes as they have the correct symbols in them.
Please help

**Comment by fernandog** [comment]
@RadeoSuicide before running SR run:  chcp 65001

**Comment by RadeoSuicide** [comment]
in command prompt? it says active code page 65001

**Comment by fernandog** [comment]
yes. run SR after that and check the accents

**Comment by RadeoSuicide** [comment]
nah still doesnt work, i tried doing a full update on two and a half men but its still not working

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1425

**Comment by RadeoSuicide** [comment]
how does that help me?
