### ISSUE TITLE
[APP SUBMITTED]: not a valid bencoded string

### ISSUE THREAD

**Issue by HotBlack77** [SiCKRAGETV/sickrage-issues#2199]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.8**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@ea897589698c18007ff0fd062b224d68d76d3bb5
Link to Log: https://gist.github.com/0ac177ffaf26d00ddb6c
### ERROR
```
SEARCHQUEUE-BACKLOG-292174 :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
disable proxy
