### ISSUE TITLE
[Feature Request]: Missing Episode List - Able to export...

### ISSUE THREAD

**Issue by allnerag** [SiCKRAGETV/sickrage-issues#2200]
Can we add a Feature to export all the missing episodes to a CSV, XML or similar type of file.  The missing file list needs to provide all the required fields for you to be able to give your friend to check if maybe have some of the files.  
File: Series, Season, Episode Number, Episode Name

**Comment by miigotu** [comment]
@allnerag Once again, this is outside the scope of SickRage. Just dump it from the db it is literally one command:
```sql
SELECT s.indexer, s.indexer_id, s.show_name, e.season, e.episode, e.name FROM tv_episodes as e INNER JOIN tv_shows AS s WHERE e.status = 5 AND e.showid = s.indexer_id;
```

Simple python to do this yourself:
https://gist.github.com/miigotu/82bca725b6021af4d2b2
