### ISSUE TITLE
[Feature Request] Hide IP's in log from Tornado API calls

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2201]
Abbility to censor all or only one IP adress from the log page

**Comment by fernandog** [comment]
why not use firewall?

**Comment by duramato** [comment]
@fernandog  what do you mean?

**Comment by fernandog** [comment]
block IP in firewall

**Comment by duramato** [comment]
@fernandog  sorry im not understanding, ie if im using an android app for sickrage my ip will appear there (on the logs)

**Comment by fernandog** [comment]
Ahh! sorry. you want to don't show IP in logs ? like api key? I get that now

**Comment by fernandog** [comment]
but how you will see the IP if is censored??

**Comment by duramato** [comment]
maybe have an abillity to censor only  a specific one ie my own ,and all others would be uncessored for ie know who did if someone  tempered my SR 
&/or have an option to just censor everything

**Comment by miigotu** [comment]
Lol why need to censor the ip?

**Comment by duramato** [comment]
@miigotu becouse ive noticed that when i submit a bug from within sr and the logs got my IP on there

**Comment by miigotu** [comment]
So you only need it when submitting an issue? I think that's better

**Comment by duramato** [comment]
@miigotu if you whant can be that way ,also ive noticed that the server IP adress also appears on the pushbullet logs

**Comment by miigotu** [comment]
Can you paste all of the log lines you can find that have ip's (you can change the ip lol), I need the examples to make sure I match regex properly

**Comment by fernandog** [comment]
we can do this in tornado (I think). if local ip, don't show, show only if external IP

**Comment by miigotu** [comment]
@fernandog go ahead if you want, Im going to sleep lol

**Comment by fernandog** [comment]
@duramato still need some examples of IP

**Comment by duramato** [comment]
```
2015-07-19 15:11:21 DEBUG    TORNADO :: API :: IPADRESS - gave correct API KEY. ACCESS GRANTED
```
IPADRESS=my ip adress
also i didnt found the pushbullet one ,may i was wrong

**Comment by fernandog** [comment]
@miigotu can we use this info and use regex?

```
There are three networks of IP addresses that are not used on the internet. Those are:
10.0.0.0/8
172.16.0.0/12
192.168.0.0/16
```
http://stackoverflow.com/a/9080240

**Comment by miigotu** [comment]
One we don't want to mask out is 
TORNADO :: API :: IPADRESS - gave incorrect API KEY. ACCESS DENIED

(if thats the right line, typing from memory)

**Comment by fernandog** [comment]
@duramato so you want to hide your REMOTE ip and not your local?

**Comment by fernandog** [comment]
@duramato done

**Comment by duramato** [comment]
thanks @fernandog

**Comment by fernandog** [comment]
@duramato IMO this is bad too cause you don't know if someone else logged in your SR with your pass

**Comment by duramato** [comment]
@fernandog  couldt then be made something like, if IP is x.x.x.x then it would show it on the log ,otherwise would show it

**Comment by miigotu** [comment]
Like a "trusted" ip list?

**Comment by fernandog** [comment]
but if you connect from your phone, IP it's not fixed!

**Comment by miigotu** [comment]
@fernandog then he doesn't need to hid the phone ip.

**Comment by fernandog** [comment]
@duramato you want to censor your local IP or remote? Isn't clear to me yet

**Comment by duramato** [comment]
Public IP ,becouse thats the one that threats my privacy 
Yeah it could be a trusted IP list ,But yeah on the phone they change from cell tower to cell tower

**Comment by miigotu** [comment]
I think leave it how it is for now, because if you see someone logged in with your api key and it was at a time when you didnt do it, you know to change user/pass/apikey

It shows IP only on failed attempt currently.

**Comment by fernandog** [comment]
as FR so I would add a notification when user logged in and show IP in notification
