### ISSUE TITLE
[Feature Request]: Able to compare two Sickrage's...

### ISSUE THREAD

**Issue by allnerag** [SiCKRAGETV/sickrage-issues#2202]
Will it be possible to add a feature to be able to compare two Sickrage's against each other over the internet. Then it will show what the one is missing vs the other one. It could also show what Series you do not have.

**Comment by fernandog** [comment]
sorry, can't do it

**Comment by miigotu** [comment]
@allnerag would be better to ask somebody creating an app the uses the api. Simple for them to grab the whole library from both instances and compare.

Try asking @MGaetan89 maybe

**Comment by MGaetan89** [comment]
I'm not planning to support multiple SickRage installations in my app yet (but it is planned).
But this could be interesting to add when I do.
@allnerag What do you want to compare exactly? Just the list of show? Maybe each season too, with the episode status/quality?

**Comment by miigotu** [comment]
@MGaetan89 I think he wants to see episodes instance A has that instance B doesnt, and vice versa

if A and B has ShowC:
A has ShowC Episode SxE1 but B doesn't and B wants it
B has ShowC Episode SxE2 but A doesn't and A wants it

There is extremely limited use cases for this, only if one wanted to know if they can get some of their missing episodes from a  friend.
