### ISSUE TITLE
[APP SUBMITTED]: Series result returned zero

### ISSUE THREAD

**Issue by scorpius023** [SiCKRAGETV/sickrage-issues#2204]
### INFO
Python Version: **2.7.10 (default, Jun  4 2015, 00:34:17) [GCC 4.2.0]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@ea897589698c18007ff0fd062b224d68d76d3bb5
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-ADD :: Show name with ID 0 don't exist in TVRage anymore. Please change/delete your local .nfo file or remove it from your TRAKT watchlist
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Lol either you have an nfo with <id>0</id> or trakt really has a show with ID 0?
