### ISSUE TITLE
Unable to open certain shows

### ISSUE THREAD

**Issue by mjsmjs** [SiCKRAGETV/sickrage-issues#2206]
Clicking on a show loads me back to http://localhost:8081/home/ from v4.0.32 on.
```
2015-07-19 03:49:01 Thread-15 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\Server\TV\SickRage-4.0.32\sickbeard\webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "C:\Server\TV\SickRage-4.0.32\sickbeard\webserve.py", line 1320, in displayShow
    return t.respond()
  File "C:\Server\TV\SickRage-4.0.32\cache\cheetah\_Server_TV_SickRage_4_0_32_gui_slick_interfaces_default_displayShow_tmpl.py", line 704, in respond
    info_flag = VFN(VFN(VFSL([locals()]+SL+[globals(), builtin],"subtitles",True),"fromietf",False)(VFSL([locals()]+SL+[globals(), builtin],"show.lang",True)),"alpha3",True)
  File "C:\Server\TV\SickRage-4.0.32\sickbeard\subtitles.py", line 70, in fromietf
    return babelfish.Language.fromopensubtitles(language)
  File "C:\Server\TV\SickRage-4.0.32\lib\babelfish\language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "C:\Server\TV\SickRage-4.0.32\lib\babelfish\converters\opensubtitles.py", line 36, in reverse
    raise LanguageReverseError(opensubtitles)
LanguageReverseError: u'0'
```

**Comment by miigotu** [comment]
@mjsmjs Dunno how you got '0' as the info language for your show, but a mass update and select that show should fix it

**Comment by mjsmjs** [comment]
That didn't work. Same error. V4.0.31 works fine but updating to the newest sends me to the home when going to friends and some others that I randomly tried.

**Comment by fernandog** [comment]
@mjsmjs  linux?

run in ssh, insider sickrage folder. must have sqlite3 installed

sqlite3 -cmd ".timeout 5000" sickbeard.db "select distinct subtitles from tv_episodes";

sqlite3 -cmd ".timeout 5000" sickbeard.db "select distinct subtitles from tv_shows";

post results

**Comment by mjsmjs** [comment]
windows 8.1

**Comment by fernandog** [comment]
download it and put in Windows folder

http://sqlite.org/2015/sqlite-shell-win32-x86-3081002.zip

**Comment by mjsmjs** [comment]
Did that already. still not getting it to run right.

**Comment by fernandog** [comment]
if you don't give more info then that I can't help you

**Comment by fernandog** [comment]
did you run all that commands I told you?

**Comment by mjsmjs** [comment]
I'm trying to. In sqlite3 i get a "near "sqlite3": syntax error

**Comment by mjsmjs** [comment]
In windows command prompt it does nothing. So I'm not sure what I am doing wrong.

**Comment by fernandog** [comment]
send screen shots of your CMD screen with this commands.
you must run it inside the folder where sickrage.db is

**Comment by mjsmjs** [comment]
![capture](https://cloud.githubusercontent.com/assets/1781830/8778225/8ee25d92-2eca-11e5-81bd-9cef8613766c.PNG)

**Comment by fernandog** [comment]
windows 10 changed something in CMD. here it works

run:
C:\Users\sickrage\Documents>sqlite3
SQLite version 3.8.10.2 2015-05-20 18:17:19
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.

sqlite> .open sickbeard.db

sqlite> select distinct subtitles from tv_episodes;

sqlite> select distinct subtitles from tv_shows;
0

**Comment by mjsmjs** [comment]
got 0 like yours

**Comment by mjsmjs** [comment]
![capture2](https://cloud.githubusercontent.com/assets/1781830/8778608/de2467fe-2ecc-11e5-82cc-1b3edcc32a5c.PNG)

**Comment by fernandog** [comment]
and you still have the issue?

**Comment by mjsmjs** [comment]
yes

2015-07-20 10:50:46 ERROR    Thread-16 :: Failed doing webui callback: Traceback (most recent call last):
2015-07-20 10:50:33 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2015-07-20 10:50:21 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
AAValueError: Invalid language 0, options are: ['da', 'fi', 'nl', 'de', 'it', 'es', 'fr', 'pl', 'hu', 'el', 'tr', 'ru', 'he', 'ja', 'pt', 'zh', 'cs', 'sl', 'hr', 'ko', 'en', 'sv', 'no']
AA    language, self.config['valid_languages']
AA  File "C:\Server\TV\SickRage-4.0.41\lib\tvdb_api\tvdb_api.py", line 516, in __init__
AA    return indexerConfig[self.indexerID]['module'](*args, **kwargs)
AA  File "C:\Server\TV\SickRage-4.0.41\sickbeard\indexers\indexer_api.py", line 33, in indexer
AA    t = sickbeard.indexerApi(ep_obj.show.indexer).indexer(**lINDEXER_API_PARMS)
AA  File "C:\Server\TV\SickRage-4.0.41\sickbeard\metadata\****_12plus.py", line 225, in _ep_data
AA    data = self._ep_data(ep_obj)
AA  File "C:\Server\TV\SickRage-4.0.41\sickbeard\metadata\generic.py", line 456, in write_ep_file
AA    return self.write_ep_file(ep_obj)
AA  File "C:\Server\TV\SickRage-4.0.41\sickbeard\metadata\generic.py", line 275, in create_episode_metadata
AA    result = cur_provider.create_episode_metadata(self) or result
AA  File "C:\Server\TV\SickRage-4.0.41\sickbeard\tv.py", line 1932, in createNFO
AA    self.createNFO()
AA  File "C:\Server\TV\SickRage-4.0.41\sickbeard\tv.py", line 1921, in createMetaFiles
AA    ep_obj.createMetaFiles()
AA  File "C:\Server\TV\SickRage-4.0.41\sickbeard\postProcessor.py", line 1080, in process
AA    result.result = processor.process()
AA  File "C:\Server\TV\SickRage-4.0.41\sickbeard\processTV.py", line 491, in process_media
AA    process_media(path, [video], nzbName, process_method, force, is_priority, result)
AA  File "C:\Server\TV\SickRage-4.0.41\sickbeard\processTV.py", line 204, in processDir
AA    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR)
AA  File "C:\Server\TV\SickRage-4.0.41\sickbeard\autoPostProcesser.py", line 50, in run
AA    self.action.run(self.force)
AA  File "C:\Server\TV\SickRage-4.0.41\sickbeard\scheduler.py", line 97, in run

**Comment by mjsmjs** [comment]
Just opened 5 random shows and only 1 would load. The rest redirect me back home

**Comment by fernandog** [comment]
@miigotu help here?

**Comment by miigotu** [comment]
its not subtitles, its them show info language @fernandog

**Comment by miigotu** [comment]
Try a full refresh on the shows,

**Comment by mjsmjs** [comment]
I've tried that already

**Comment by miigotu** [comment]
`UPDATE tv_shows SET lang = 'en' WHERE lang = 0 or lang = '0';`

**Comment by mjsmjs** [comment]
That fixed it. Thank you very much.
