### ISSUE TITLE
[Feature Request] Staggered Backlog Searches

### ISSUE THREAD

**Issue by Ockingshay** [SiCKRAGETV/sickrage-issues#2207]
Everyday i get 100s of [BTN] :: JSON-RPC protocol error while accessing BTN: error (-32002, u'Call Limit Exceeded') because when backlog runs BTN protects itself by after so many attempts blocking access. After a little while access is granted again.

I have 54 shows in my database, so it would be nice to set a limit on how many backlog searches sickrage does in 1 go (i.e. the first 10 shows) and then once it reaches that limit, wait for the predefined backlog frequency and then continue where it left off. (i.e. shows 11-20).... and so on.

**Comment by fernandog** [comment]
Why dont you pause some shows. Force backlog for other. Do this until backlog is empty and only dailysearch is needed.

This FR can take a while to be done. We have a lot of issues/bugs and more important FR

**Comment by Ockingshay** [comment]
because bluray 720p is the lowest best quality that doesn't add it to backlog and there are many long running shows that their early seasons will never hit bluray quality. 

Backlog needs a rethink in general, as it only really works for newer shows. Perhaps even defining archive quality per season would help alleviate the size of the backlog list. 

I never expected this fix quickly as the errors fortunately don't cause any lockout issues at BTN.

**Comment by fernandog** [comment]
if you want only the first available quality  then enable "Archive on the first match"
https://github.com/SiCKRAGETV/SickRage/wiki/Quality-Settings

**Comment by Ockingshay** [comment]
Family guy is a good example. I want the best quality for each season, but the early seasons are just dvd., where as the latest seasons are bluray. 

Archive on first match is good for shows that have already ended and are out on bluray. Any continuing TV shows always comes out in hdtv/webdl first and then bluray many months later. If I had archive on first match selected I would never get the bluray version. 

It's more complicated than first thought trying to satisfy all the permutations a backlog needs to consider.

**Comment by miigotu** [comment]
I think this just needs a sleep in between searches using cpu_presets

**Comment by miigotu** [comment]
Closing this for now because the commit I just added to develop is likely to fix this.

If it continues after this is moved to master (or continues on develop) let us know in this issue, and ping me

**Comment by mrmachine** [comment]
I think this is still an issue. See my comment on #1209
