### ISSUE TITLE
What sets a show as airbydate by default?

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2208]
``Last Week Tonight with John Oliver`` got set as AirByDate by default when I added it even though torrents only seem to go up with S00E00.

Who should I be contacting in correcting this? TheTVDB? or is it based on the genre of the show as it's a ``News``, ``Talk-Show`` and most of them are probably listed as such.

**Comment by miigotu** [comment]
show_queue.py L321

```python
            # be smartish about this
            if self.show.genre and "talk show" in self.show.genre.lower():
                self.show.air_by_date = 1
```

**Comment by miigotu** [comment]
not very smartish if you ask me =P

**Comment by fernandog** [comment]
lol

**Comment by fernandog** [comment]
i would disable this 'smartish'
