### ISSUE TITLE
Subtitles broken: FINDSUBTITLES :: Traceback (most recent call last)

### ISSUE THREAD

**Issue by tomkat83** [SiCKRAGETV/sickrage-issues#2209]
# Branch
Master
# Commit hash
f0ef24bf7dbd5ffa451bbdb8694448139d8c4631
(newest as of 2015.07.19)
# Your operating system and python version
Windows 7, 64bit. Python 2.7.10 32bit
# What you did
Sickrage searching for subtitle is broken. E.g. when using Mass update -> Search Subtitles for "Breaking Bad" (see log). Currently, NO subtitles at all are being downloaded. 
I already tried a fresh clean re-install of Sickrage from scratch. This did not help. 
# What happened
Error message:
```
2015-07-19 13:05:25 SHOWQUEUE-SUBTITLE :: Traceback (most recent call last):
  File "C:\DownloadChain\SickRage-master\sickbeard\tv.py", line 1474, in downloadSubtitles
    foundSubs = subliminal.download_best_subtitles([video], languages=languages, providers=providers, single=not sickbeard.SUBTITLES_MULTI, hearing_impaired=False)
  File "C:\DownloadChain\SickRage-master\lib\subliminal\api.py", line 74, in download_best_subtitles
    with ProviderPool(providers, provider_configs) as pp:
  File "C:\DownloadChain\SickRage-master\lib\subliminal\providers\__init__.py", line 241, in __init__
    self.providers = dict([(p, provider_manager[p]) for p in (providers or provider_manager.available_providers)])
  File "C:\DownloadChain\SickRage-master\lib\subliminal\providers\__init__.py", line 180, in __getitem__
    self.providers[ep.name] = ep.load()
  File "C:\DownloadChain\SickRage-master\lib\pkg_resources.py", line 1953, in load
    if require: self.require(env, installer)
  File "C:\DownloadChain\SickRage-master\lib\pkg_resources.py", line 1966, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "C:\DownloadChain\SickRage-master\lib\pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
DistributionNotFound: six
```
# What you expected
No error messages :-)
# Link to a copy/paste of your logfile with clear debug info of the error on GIST
https://gist.github.com/tomkat83/083833c983c0dbee8267

**Comment by miigotu** [comment]
six is in the lib folder. Something wrong with your setup.

**Comment by tomkat83** [comment]
Thanks for your feedback. How can that be if this is a completely new setup of sickrage from scratch? What can I do to fix this?

**Comment by miigotu** [comment]
It's not sickrage, its the python install.

**Comment by tomkat83** [comment]
Aha, thanks for pointing me in the right direction! Are these dependencies on python packages noted somewhere...?

However, it was not the "six" package. Easiest fix for windows python installation using pip:
```
pip uninstall subliminal
pip install subliminal
```

**Comment by miigotu** [comment]
@tomkat83 That is an incorrect fix. SickRage INCLUDES the libs, specific versions.

**Comment by tomkat83** [comment]
Well, it did work for me. Had an old version of subliminal installed via
pip. Maybe some old libs were used from python and not sickrage..?
Am 20.07.2015 23:11 schrieb "miigotu" <notifications@github.com>:

**Comment by miigotu** [comment]
We inset the SickRage/lib dir in the python path before the other python modules. However you installed SickRage isn't setting the right variables or something. Running it straight from python doesnt work.

**Comment by hglaude** [comment]
Hello,

I got the same issue after an improper install of subliminal on my system (Windows 7, python 2.7)
...
pip uninstall subliminal
pip install subliminal
...
Worked for me as well after a Sickrage restart of course ! Thanks
