### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by doccincy** [SiCKRAGETV/sickrage-issues#2210]
Can't update to newest version. SR tells me I am 12 commits behind. When I try to update, I get an error and the message that the config backup failed and the backup is aborted. From the error log:

2015-07-19 08:21:50 Thread-106 :: Zip creation error: Filesize would require ZIP64 extensions
2015-07-19 08:21:50 Thread-106 :: Config backup failed, aborting update

**Comment by fernandog** [comment]
@doccincy follow guidelines: https://github.com/SiCKRAGETV/sickrage-issues/

**Comment by fernandog** [comment]
@doccincy is this your topic ?  https://sickrage.tv/forums/forum/help-support/general-support/24316-updating-zip-creation-error-filesize-would-require-zip64-extensions

**Comment by doccincy** [comment]
Yes, looks like my issue. Will try the manual pull. Is there a fix for this
so that manual pulls are not required every time?

**Comment by fernandog** [comment]
Did you try that change in the code? Need to stop SR before change

**Comment by doccincy** [comment]
Yes. Appears to have worked. Thanks for your help!
