### ISSUE TITLE
Bravo network image file name mismatch

### ISSUE THREAD

**Issue by elrock** [SiCKRAGETV/sickrage-issues#2211]
BRANCH: (master) / COMMIT: (f0ef24bf7dbd5ffa451bbdb8694448139d8c4631)
Python version 2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]

Broken image link in web application -- image file is named bravo.png, while the web application links to the nonexistent "bravo (us).png".

**Comment by neoatomic** [comment]
@elrock I added the logo for you. Should be fixed with the next update. :)
