### ISSUE TITLE
[Feature Request] Add BeyondHD torrent provider

### ISSUE THREAD

**Issue by jtwill** [SiCKRAGETV/sickrage-issues#2213]
It would be great if SickRage could add the BeyondHD torrent provider.

SickGear already has support for BeyondHD, so hopefully that can provide a jumpstart for the SickRage implementation:

https://github.com/SickGear/SickGear/blob/develop/sickbeard/providers/beyondhd.py

**Comment by miigotu** [comment]
Seems fairly easy, sometime soonish maybe.

**Comment by adaur** [comment]
I can do this, but I'm not sure SickGear's devs will be happy about it hahaha.

Since this is a private tk, I'll need either an account or an invite code :)

**Comment by adaur** [comment]
@jtwill hi there

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
