### ISSUE TITLE
[APP SUBMITTED]: 'utf8' codec can't decode byte 0xf6 in position 17: invalid start byte

### ISSUE THREAD

**Issue by razlebol** [SiCKRAGETV/sickrage-issues#2214]
### INFO
Python Version: **2.7.6 (default, Apr  3 2014, 09:45:36) [GCC 4.5.3]**
Operating System: **Linux-3.4.90-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@f0ef24bf7dbd5ffa451bbdb8694448139d8c4631
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: utf8 : Futurama S06E15 Möbius Dick.mkv : error 17 : error 18 : invalid start byte
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
The special character in `Möbius` is the problem. Check your local settings.

**Comment by miigotu** [comment]
locale*

**Comment by miigotu** [comment]
Need the full debug log, it's possible a bad conversion is done somewhere, and that the string is already utf-8 when it is tried to be converted to utf-8
