### ISSUE TITLE
[APP SUBMITTED]: 401 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Bad credentials'}

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2215]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:34:55) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-22-generic-i686-with-Ubuntu-15.04-vivid**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@3db87525c87034ec10878d50f96c183eca939252
Link to Log: https://gist.github.com/042c4304b30ec78ec48b
### ERROR
```
Thread-62 :: 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by FlyGuy94** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@6831ae9131af765586c1d348cc1835f363f350ce
Link to Log: https://gist.github.com/20ec806bd8c17df2b84c
### ERROR
```
Thread-22 :: 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by devenashani** [comment]
### INFO
Python Version: **2.7.3 (default, Jul 13 2012, 04:03:47) [GCC 4.4.5]**
Operating System: **Linux-2.6.31.8.nv+v2-armv5tel-with-debian-6.0.3**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@6831ae9131af765586c1d348cc1835f363f350ce
Link to Log: https://gist.github.com/8298e0d7fcd66c79dfb4
### ERROR
```
Thread-21 :: 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by devenashani** [comment]
### INFO
Python Version: **2.7.3 (default, Jul 13 2012, 04:03:47) [GCC 4.4.5]**
Operating System: **Linux-2.6.31.8.nv+v2-armv5tel-with-debian-6.0.3**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@6831ae9131af765586c1d348cc1835f363f350ce
Link to Log: https://gist.github.com/08f5f5a85cc1eb27aeee
### ERROR
```
Thread-50 :: 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by raymondtrueman** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  4 2015, 01:18:03) [GCC 4.3.2]**
Operating System: **Linux-2.6.32.12-ppc-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@6831ae9131af765586c1d348cc1835f363f350ce
Link to Log: https://gist.github.com/387b6213cbeacc4a71c7
### ERROR
```
Thread-454 :: 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miiichael** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.2**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@d1118cb1c9114778535b85b7e59758fde57ad9a5
Link to Log: https://gist.github.com/b79a6999dafcb7e62ca2
### ERROR
```
Thread-38 :: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/logger.py", line 237, in submit_errors
    gist = gh.get_user().create_gist(True, {"sickrage.log": InputFileContent(paste_data)})
  File "/opt/sickrage/lib/github/AuthenticatedUser.py", line 473, in create_gist
    input=post_parameters
  File "/opt/sickrage/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/opt/sickrage/lib/github/Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
BadCredentialsException: 401 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Bad credentials'}

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by channouze** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-7**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@efc2434c76dd476b0480ab1f0c395983a095fc07
Link to Log: https://gist.github.com/9406a328cf603969f40e
### ERROR
```
Thread-24 :: Traceback (most recent call last):
  File "/home/sickrage/SickRage/sickbeard/logger.py", line 264, in submit_errors
    reports = gh.get_organization(gh_org).get_repo(gh_repo).get_issues(state="all")
  File "/home/sickrage/SickRage/lib/github/MainClass.py", line 188, in get_organization
    "/orgs/" + login
  File "/home/sickrage/SickRage/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/home/sickrage/SickRage/lib/github/Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
BadCredentialsException: 401 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Bad credentials'}

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by johnkillerbob** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-65-generic-i686-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@136f531f93093a5287b588ca37e19c11153f47a4
No Log available with ERRORS: 
### ERROR
```
Thread-29 :: Traceback (most recent call last):
  File "/home/john/.sickrage/sickbeard/logger.py", line 269, in submit_errors
    reports = gh.get_organization(gh_org).get_repo(gh_repo).get_issues(state="all")
  File "/home/john/.sickrage/lib/github/MainClass.py", line 188, in get_organization
    "/orgs/" + login
  File "/home/john/.sickrage/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/home/john/.sickrage/lib/github/Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
BadCredentialsException: 401 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Bad credentials'}

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by jstevenson72** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@d5a336dc0bf98249902ec3c455846624ac19387e
Link to Log: https://gist.github.com/ce9bcff3a76734d43d3d
### ERROR
```
Thread-58 :: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\logger.py", line 242, in submit_errors
    gist = gh.get_user().create_gist(True, {"sickrage.log": InputFileContent(paste_data)})
  File "C:\SickRage\SickRage\lib\github\AuthenticatedUser.py", line 473, in create_gist
    input=post_parameters
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickRage\SickRage\lib\github\Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
BadCredentialsException: 401 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Bad credentials'}

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Nomelas** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@4028db3d7a2cc582b0f591d981ed3af344b4e75a
Link to Log: https://gist.github.com/fc66066a0438fbd7da1a
### ERROR
```
Thread-19 :: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\logger.py", line 242, in submit_errors
    gist = gh.get_user().create_gist(True, {"sickrage.log": InputFileContent(paste_data)})
  File "C:\SickRage\lib\github\AuthenticatedUser.py", line 473, in create_gist
    input=post_parameters
  File "C:\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickRage\lib\github\Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
BadCredentialsException: 401 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Bad credentials'}

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Spippo** [comment]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@9f8ae2924808eaf9f64bb37e09bc45a76b43969c
Link to Log: https://gist.github.com/ac20299541db6d9042ac
### ERROR
```
Thread-21 :: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/logger.py", line 249, in submit_errors
    gist = gh.get_user().create_gist(True, {"sickrage.log": InputFileContent(paste_data)})
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/AuthenticatedUser.py", line 473, in create_gist
    input=post_parameters
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
BadCredentialsException: 401 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Bad credentials'}

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by wernerhp** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.11.10-03111006-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
Link to Log: https://gist.github.com/7190338017745018d22d
### ERROR
```
Thread-41 :: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/logger.py", line 249, in submit_errors
    gist = gh.get_user().create_gist(True, {"sickrage.log": InputFileContent(paste_data)})
  File "/opt/sickbeard/lib/github/AuthenticatedUser.py", line 473, in create_gist
    input=post_parameters
  File "/opt/sickbeard/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/opt/sickbeard/lib/github/Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
BadCredentialsException: 401 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Bad credentials'}

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by wernerhp** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.11.10-03111006-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
Link to Log: https://gist.github.com/1e0677a434802c3689c4
### ERROR
```
Thread-58 :: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/logger.py", line 276, in submit_errors
    reports = gh.get_organization(gh_org).get_repo(gh_repo).get_issues(state="all")
  File "/opt/sickbeard/lib/github/MainClass.py", line 188, in get_organization
    "/orgs/" + login
  File "/opt/sickbeard/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/opt/sickbeard/lib/github/Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
BadCredentialsException: 401 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Bad credentials'}

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by OmgImAlexis** [comment]
@fernandog some of these aren't providing tracebacks, that needs to be fixed and I think this may need to be added as a warning, not an error because they obviously fixed it as they've submitted to Github.

**Comment by hawkeye73** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2008ServerR2-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
Link to Log: https://gist.github.com/3007ae8e8b3c4f757a8c
### ERROR
```
Thread-40 :: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\logger.py", line 249, in submit_errors
    gist = gh.get_user().create_gist(True, {"sickrage.log": InputFileContent(paste_data)})
  File "C:\SickRage\lib\github\AuthenticatedUser.py", line 473, in create_gist
    input=post_parameters
  File "C:\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickRage\lib\github\Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
BadCredentialsException: 401 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Bad credentials'}

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by hawkeye73** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2008ServerR2-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
Link to Log: https://gist.github.com/e8d56d7286c33027259a
### ERROR
```
Thread-61 :: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\logger.py", line 276, in submit_errors
    reports = gh.get_organization(gh_org).get_repo(gh_repo).get_issues(state="all")
  File "C:\SickRage\lib\github\MainClass.py", line 188, in get_organization
    "/orgs/" + login
  File "C:\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickRage\lib\github\Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
BadCredentialsException: 401 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Bad credentials'}

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by TrueTenacity** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
Link to Log: https://gist.github.com/93d71aaca4055aeab49b
### ERROR
```
Thread-64 :: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\logger.py", line 276, in submit_errors
    reports = gh.get_organization(gh_org).get_repo(gh_repo).get_issues(state="all")
  File "C:\SickRage\lib\github\MainClass.py", line 188, in get_organization
    "/orgs/" + login
  File "C:\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickRage\lib\github\Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
BadCredentialsException: 401 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Bad credentials'}

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
