### ISSUE TITLE
[Feature Request] Episode quality set to "Any" and download from most seeded

### ISSUE THREAD

**Issue by mauirixxx** [SiCKRAGETV/sickrage-issues#2216]
Aloha, I have a TV show whose quality is set to any, and I guess the internal logic is to download the highest quality video available.

Would it be possible to get a sub option to allow you to choose between highest seeded OR highest quality?

**Comment by miigotu** [comment]
This is not a viable option, because many providers do not supply us with information about how many seeds are available, and most of them are not accurate about it if they do.

Also, nzb's do not have seeds, and we need to maintain equal support for both formats.

SD usually has the most seeds
