### ISSUE TITLE
Feature Request: Update restart behaviour

### ISSUE THREAD

**Issue by Rouzax** [SiCKRAGETV/sickrage-issues#222]
I'm running Sickrage as a Windows service with FireDaemon and that works as a charm. The only thing that causes issues are the update process.
As soon as I hit update from the Sickrage webpage it updates it self and restarts. However that is a new process so FireDaemon thinks Sickrage is not running and starts it up again.

Could there be a settings that during a upgrade it does not restart it self but does a shutdown?
That way my Firedaemon will restart the process.

**Comment by fernandog** [comment]
@Rouzax still an issue?

**Comment by abeloin** [comment]
It's limitation on firedaemon part, but we could add a `--norestart` options which would simply terminate sickrage instead of starting a new process

**Comment by TagForce** [comment]
@abeloin Why not add a checkbox to the github config page called "Shutdown on update". If true, then it skips the part where it launches a new process, which would cause it to silently just exit. Firedeamon would restart the service as soon as it goes down anyway, so the restart.tmpl page should still pick up on it, shouldn't it?

**Comment by Rouzax** [comment]
I still would like the feature, yes.
It is not so much a limitation of FireDaemon. FireDeamon will monitor the program it has started. When it crashes or stops running it will start it again.

@TagForce 
Yes the restart page still works.
What I do now is to start the upgrade and then when I see that SickRage is restarting it self I will kill all consoles that are running with Ctrl+C.
FireDeamon will see that the process is no longer running and start it again.

**Comment by Rouzax** [comment]
Just for clarification, this is hwo my service is configured.
![image](https://cloud.githubusercontent.com/assets/4103090/6726667/59315e8e-ce1a-11e4-9a9a-fcf4e1f8791b.png)
![image](https://cloud.githubusercontent.com/assets/4103090/6726687/7a18b80e-ce1a-11e4-81a6-674fd2ef88c2.png)
![image](https://cloud.githubusercontent.com/assets/4103090/6726693/864240d2-ce1a-11e4-81fa-1e7a5c412b72.png)

**Comment by Rouzax** [comment]
This is what happens no with an update.
![image](https://cloud.githubusercontent.com/assets/4103090/6726731/0e14432a-ce1b-11e4-95c4-2411610c6e7e.png)
One instance is from SIckRage restart and one is a restart from FireDeamon.

**Comment by fernandog** [comment]
@Rouzax What is flap detection ?

**Comment by fernandog** [comment]
Cant you change the 5000 to 60000 in restart setting?

**Comment by Rouzax** [comment]
See the user guide here:
http://mirror.firedaemon.com/FireDaemon-Pro/3.7.2660/FireDaemon-Users-Guide.pdf
![image](https://cloud.githubusercontent.com/assets/4103090/6728456/381c444c-ce2a-11e4-8958-a12a953c4189.png)

Can try it but I don't think it will work because FireDeamon creates a wrapper around the program. SickRage will start a new instance that is not inside that wrapper.

**Comment by TagForce** [comment]
@Rouzax Tadaaaaaaaaa :)

**Comment by fernandog** [comment]
so we can close this.

**Comment by fernandog** [comment]
@Tagforce

**Comment by TagForce** [comment]
@fernandog Yes, the function is added in above PR.

**Comment by Rouzax** [comment]
Awesome!

**Comment by Rouzax** [comment]
Just got the update of the Master with this Pr and it works as a charm.
Thank you very much :+1:  :bow:
