### ISSUE TITLE
[APP SUBMITTED]: invalid syntax (addic7ed.py, line 72)

### ISSUE THREAD

**Issue by skalvaro** [SiCKRAGETV/sickrage-issues#2221]
### INFO
Python Version: **2.6.6 (r266:84292, Jan 22 2014, 09:42:36) [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]**
Operating System: **Linux-2.6.32-504.30.3.el6.x86_64-x86_64-with-centos-6.6-Final**
Locale: UTF8
Branch: **master**
Commit: SiCKRAGETV/SickRage@f0ef24bf7dbd5ffa451bbdb8694448139d8c4631
Link to Log: https://gist.github.com/73ea67bebe4eef084e3f
### ERROR
```
Thread-33 :: Traceback (most recent call last):
  File "/var/lib/sickrage/sickbeard/tv.py", line 1474, in downloadSubtitles
    foundSubs = subliminal.download_best_subtitles([video], languages=languages, providers=providers, single=not sickbeard.SUBTITLES_MULTI, hearing_impaired=False)
  File "/var/lib/sickrage/lib/subliminal/api.py", line 74, in download_best_subtitles
    with ProviderPool(providers, provider_configs) as pp:
  File "/var/lib/sickrage/lib/subliminal/providers/__init__.py", line 241, in __init__
    self.providers = dict([(p, provider_manager[p]) for p in (providers or provider_manager.available_providers)])
  File "/var/lib/sickrage/lib/subliminal/providers/__init__.py", line 184, in __getitem__
    self.providers[ep.name] = ep.load(require=False)
  File "/var/lib/sickrage/lib/pkg_resources.py", line 1954, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/var/lib/sickrage/lib/subliminal/providers/addic7ed.py", line 72
    languages = {babelfish.Language('por', 'BR')} | {babelfish.Language(l)
                                                ^
SyntaxError: invalid syntax

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by skalvaro** [comment]
@miigotu ok, I will try to move to Python 2.7 You might want to update the dependencies on the github page as it still mentions Python 2.6.
```
To run SickRage from source you will need Python 2.6+, Cheetah 2.1.0+, and PyOpenSSL
```

**Comment by miigotu** [comment]
@skalvaro It is not a 100% requirement yet, as everything else works on 2.6, so we will change that when it gets a little worse (probably next subliminal update)

**Comment by skalvaro** [comment]
@miigotu ok. I fortunately can report back that the switch-over to Python 2.7 has succeeded and the subtitles are being downloaded again. Thank you for the support.

**Comment by fernandog** [comment]
@miigotu should we catch this error and warn about python 2.6 with subs enabled?

**Comment by miigotu** [comment]
I think we just need to make it a requirement soon to have 2.7.x
