### ISSUE TITLE
SickRage is gone. PLEASE HELP!

### ISSUE THREAD

**Issue by mbxplex** [SiCKRAGETV/sickrage-issues#2223]
@miigotu / @fernandog , if one of you could help me get SR back to it's original state in the easiest way possible it would be much appreciated. 

I honestly don't know what happened. I'm currently running, what is supposed to be, the OEM release of Windows 10 and an update was released that required me to restart my PC, which I did and ... boom, no Sickrage.vbs to load from. SR folder still remains, with SR content inside, just no SR application.

The update that installed, based on the Win Update screen, was just a security update and it only took 2-3 minutes to complete. So, it wasn't something that should have made a huge difference in my PC.

Name	Size	Date Modified
[parent directory]		
.git/		7/19/15, 8:25:28 AM
autoProcessTV/		7/9/15, 2:20:12 PM
backup/		7/18/15, 8:24:55 PM
cache/		6/5/15, 1:32:33 PM
gui/		6/5/15, 12:46:05 AM
lib/		7/18/15, 8:25:11 PM
Logs/		7/19/15, 4:56:32 PM
runscripts/		6/5/15, 12:46:16 AM
sickbeard/		7/18/15, 8:25:23 PM
tests/		7/17/15, 6:43:12 PM
tornado/		6/23/15, 3:06:42 PM
.gitattributes	1.3 kB	6/5/15, 12:46:04 AM
.gitignore	821 B	6/5/15, 12:46:04 AM
.travis.yml	295 B	7/9/15, 2:20:12 PM
cache.db	671 kB	7/19/15, 6:16:37 PM
CHANGES.md	99 B	7/18/15, 8:25:12 PM
config.ini	20.5 kB	7/18/15, 10:59:05 PM
contributing.md	6.0 kB	6/5/15, 12:46:05 AM
COPYING.txt	35.0 kB	6/5/15, 12:46:04 AM
failed.db	73.0 kB	7/15/15, 1:29:31 AM
googlecode_upload.py	9.0 kB	6/5/15, 12:46:05 AM
news.md	96 B	7/18/15, 8:25:12 PM
readme.md	2.5 kB	7/17/15, 6:43:11 PM
requirements.txt	28 B	6/24/15, 2:03:44 AM
setup.py	8.7 kB	7/17/15, 6:43:11 PM
sickbeard.bak	13.8 MB	7/18/15, 4:10:50 PM
sickbeard.db	12.5 MB	7/19/15, 5:39:13 PM
sickbeard.db.v0	24.0 kB	6/5/15, 2:20:19 AM
sickbeard.db.v10	24.0 kB	6/5/15, 1:37:35 AM
sickbeard.db.v13	24.0 kB	6/5/15, 2:35:10 AM
sickbeard.db.v14	24.0 kB	6/5/15, 2:50:02 AM
SickBeard.py	21.8 kB	7/17/15, 6:43:11 PM
TODO.txt	847 B	6/5/15, 12:46:04 AM
updater.py	2.8 kB	7/17/15, 6:43:12 PM

**Comment by miigotu** [comment]
Nothing in that folder was touched, your service and service loader is just gone. Install it however you did before.

**Comment by fernandog** [comment]
@mbxplex try run in CMD inside SickRage folder:
python SickBeard.py

**Comment by fernandog** [comment]
Maybe you lost Python folder from you $PATH in computer settings

**Comment by mbxplex** [comment]
@fernandog That worked! Thanks for the quick fix!

**Comment by fernandog** [comment]
Did you lost python path?
http://stackoverflow.com/questions/6318156/adding-python-path-on-windows-7

Your vbs is working now?
