### ISSUE TITLE
[APP SUBMITTED]: CHECKVERSION :: We can't proceed with the update. New update has a old DB version. It's not possible to downgrade

### ISSUE THREAD

**Issue by papampi** [SiCKRAGETV/sickrage-issues#2227]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-58-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@f0ef24bf7dbd5ffa451bbdb8694448139d8c4631
Link to Log: https://gist.github.com/4f8b68e9d42d207c5dfa
### ERROR
```
CHECKVERSION :: We can't proceed with the update. New update has a old DB version. It's not possible to downgrade
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by papampi** [comment]
update from web page and git pull works fine, but auto update always gives this error.

**Comment by fernandog** [comment]
@papampi 

SR compares MAX_DB_VERSION value in here:
https://raw.githubusercontent.com/SICKRAGETV/SickRage/master/sickbeard/databases/mainDB.py

with
DB version from your database

run inside SR folder when SR is shutdown:
sqlite3 -cmd ".timeout 5000" sickbeard.db "SELECT db_version FROM db_version";

MUST be equal. otherwise there's something wrong with your DB because we havent upgraded DB version

**Comment by papampi** [comment]
How do I know which version is my db ?
when I run 
sqlite3 -cmd ".timeout 5000" sickbeard.db "SELECT db_version FROM db_version";
inside sickrage it gives me 44

payam@payam-ubuntu:/opt/sickrage$ sqlite3 -cmd ".timeout 5000" sickbeard.db "SELECT db_version FROM db_version";
44

**Comment by fernandog** [comment]
your DB is 44. that's why. SR db is 42

were you using another fork?

**Comment by papampi** [comment]
nope, always used SR dev

**Comment by fernandog** [comment]
@papampi too much trouble start a new DB from scratch?

config.ini you can keep

**Comment by papampi** [comment]
so rm *.db inside sickrage ?

**Comment by fernandog** [comment]
stop SR, rename sickbeard.db to sickbeard.bak.
rename cache folder to cache-bak
delete logs folder to logs-bak
failed.db to failed.bak
cache.db to cache.bak

OR
rename SickRage folder to SickRage-old
git clone sickrage again and copy config.ini from SickRage-old to SickRage

**Comment by papampi** [comment]
@fernandog , Thnx.
