### ISSUE TITLE
[APP SUBMITTED]: [Errno bad handshake] [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]

### ISSUE THREAD

**Issue by DanGarion** [SiCKRAGETV/sickrage-issues#2228]
### INFO
Python Version: **2.7.6 (default, Apr  3 2014, 09:45:36) [GCC 4.5.3]**
Operating System: **Linux-3.10.71-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@00001a5045eda4384bcea01a64cb3775d4e658c4
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: Unable to connect to IPTorrents provider: error [Errno bad handshake] [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
config -> general -> advanced settings -> uncheck verify SSL certs.

**Comment by DanGarion** [comment]
This doesn't resolve my issue. I've unchecked verify SSL certs and errors continue.

**Comment by DanGarion** [comment]
![chrome legacy window 7222015 10213 pm](https://cloud.githubusercontent.com/assets/1666375/8835848/f6f37044-3071-11e5-8d59-3e49db2dc647.jpg)

**Comment by miigotu** [comment]
uncheck SSL, delete cache/sessions/*

**Comment by DanGarion** [comment]
So you are saying my setting is right, but I need to delete my cache from my browser...? That is why the application is getting SSL errors in the middle of the night when I'm not evening on it in my browser? I don't know of a "delete cache/sessions/*" section in SickRage.

I opened up Incognito Mode in my browser and I'm still experiencing the same issues.

2015-07-23 07:00:58 SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: Unable to connect to IPTorrents provider: error [Errno bad handshake] [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]

**Comment by fernandog** [comment]
stop SR, delete folder SickRage/cache/Sessions

**Comment by DanGarion** [comment]
Ok, I disabled the app and then I SSH'd into my device and deleted the /raid0/data/MOD_CONFIG/SICK/DATA/cache/sessions folder. And reenabled the app.

I'm still having the same error.

2015-07-23 08:57:13 SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: Unable to connect to IPTorrents provider: error [Errno bad handshake] [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')

**Comment by DanGarion** [comment]
Should I send in a new error report with all this information?

**Comment by fernandog** [comment]
no.  unchecking verify SSL certs should have fix it. only IPT with this issue?

**Comment by DanGarion** [comment]
Unchecking hasn't fixed the issue. I don't have any other sites I use. :( so that is the only one I'm able to test on.

**Comment by fernandog** [comment]
@DanGarion ado you have the latest master?

@miigotu IPT any clue what is going on?

**Comment by DanGarion** [comment]
Yes @fernandog I'm running 4.0.47 (2015-07-28) with the update to commits that I did this morning.

I'm not sure if this helps at all, but I checked my log after updating this morning with the most recent build and saw these. It might not at all be related, but I hadn't seen them before today.

AASSLError: [Errno bad handshake] [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]
AA    raise SSLError(e, request=request)
AA  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/lib/requests/adapters.py", line 431, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/lib/requests/sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/lib/requests/sessions.py", line 476, in get
AA    self.session.get(self.urls['login'], timeout=30)
AA  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/sickbeard/providers/iptorrents.py", line 96, in _doLogin
AATraceback (most recent call last):
2015-07-30 09:51:40 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: Unable to connect to IPTorrents provider: error [Errno bad handshake] [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]

**Comment by miigotu** [comment]
Your verify SSL certificates is still checked somehow, or you need to try deleting the cache/rss/* cache/sessions/* folders

**Comment by DanGarion** [comment]
Checking the config file itself.

ssl_verify = 0

I'll try deleting those folders and report back.

**Comment by DanGarion** [comment]
Unfortunately that doesn't appear to have fixed it.

I shut down SickRage, deleted the folders, and then restarted SickRage, still a no go.

**Comment by fernandog** [comment]
try enabling rarbg and disabling IPT

**Comment by DanGarion** [comment]
That seems to work. I was able to search and find a torrent to download. So it looks that it's IPT related...

**Comment by fernandog** [comment]
enable SSL check and see if still works

**Comment by DanGarion** [comment]
I enabled SSL and I get this error on rarbg

2015-07-30 11:20:22 WARNING  SEARCHQUEUE-MANUAL-255326 :: [Rarbg] :: Connection error to getURL https://torrentapi.org/pubapi_v2.php?mode=search&app_id=sickrage&search_tvdb=255326&search_string=Defiance S03E06&category=tv&limit=100&format=json&sort=seeders&token=zj4ftw2p5x Error: error [Errno bad handshake] [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]

**Comment by miigotu** [comment]
Rarbg has a good certificate. You need to get pyopenssl installed right I think.

**Comment by DanGarion** [comment]
That's going to be tough. I'm using a Thecus n5500 NAS Box. But I'll look into it. I'm no afraid of the command line just more afraid of breaking the box. :)

**Comment by DanGarion** [comment]
Just an FYI, looking at logs it appears this happen right around 6/28/15 - 7/2/15.

**Comment by DanGarion** [comment]
Just to add some more to this. I have gained accounts on a number of other torrent sites and I'm seeing the same issue even with SSL unchecked.

[FreshOnTV] :: Unable to connect to FreshOnTV provider: error [Errno bad handshake] [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]
[TorrentBytes] :: Unable to connect to TorrentBytes provider: error [Errno bad handshake] [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]
