### ISSUE TITLE
[Feature Request] Add greekleech.info and magico.info torrent providers

### ISSUE THREAD

**Issue by valantislevas** [SiCKRAGETV/sickrage-issues#223]
Many trackers uses Templateshares Ultimate Edition 2.2 http://templateshares-ue.net script website files for the tracker.. is possible to do something like a extension to use with custom tracker provider ?
To able to put in custom settings provider:

Link ( of the torrent tracker )
username 
password

because all templates of the tracker that using this files Templateshares is the same and many of them haven't RSS enabled..

thanks for all..

**Comment by kotysoft** [comment]
..or any kind of JSON based custom plugin written in Python, just like in couchpotato

**Comment by matigonkas** [comment]
If this ever happen , i would like to also work with btnext.com one of the most popular around here in Portugal

**Comment by neoatomic** [comment]
@valantislevas http://trellas.eu looks to be gone/down.?

**Comment by valantislevas** [comment]
@neoatomic the owner changes the name to magico.info

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
