### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/media/download/Person.of.Interest.S04E20.FASTSUB.VOSTFR.720p.HDTV.x264-FTX.mkv'

### ISSUE THREAD

**Issue by sirkazey** [SiCKRAGETV/sickrage-issues#2230]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.11-v7+-armv7l-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@ac27935188e351a7ffd869ff1555767987f62ce3
Link to Log: https://gist.github.com/ef5aca1d4abe16b60175
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@sirkazey manual PP running before auto PP. When PP starts manual PP already PP that folder
