### ISSUE TITLE
[Feature Request] Filter by Active on front page

### ISSUE THREAD

**Issue by wimpyrbx** [SiCKRAGETV/sickrage-issues#2234]
As a collection grows, one would have a huge list on the Shows "frontpage".
Would it be a possibility to be add the following feature?

Display:[All], [Active] or [Paused]

This way one could display only active, only paused, or all (like it's currently doing now)

/Wimp

**Comment by fernandog** [comment]
Just fill with 'yes|no' in thoses fields

**Comment by wimpyrbx** [comment]
Not sure how you mean;

I've mad an image to explain better.
http://www.fshare.it/image.jpeg?i=961437387x8

**Comment by fernandog** [comment]
Hover the mouse over column names. Input field will appear

**Comment by wimpyrbx** [comment]
Sorry fernandog, i am unable to find any input field when hovering over the columns :/
i've just updated to latest commit so should be up to date there.

**Comment by fernandog** [comment]
Enable filter in general settings

![screenshot_2015-07-20-07-14-37-1](https://cloud.githubusercontent.com/assets/2620870/8773973/270bd18c-2eaf-11e5-85cf-925875a15df8.png)

**Comment by fernandog** [comment]
Filter Row

Add a filter row to the show display on the home page

**Comment by wimpyrbx** [comment]
ahhh.. yes.. sorry! of course :)
Cheers! :+1:
