### ISSUE TITLE
Postprocess: calculate free space in the actual destination dir, not the default one

### ISSUE THREAD

**Issue by herrsimon** [SiCKRAGETV/sickrage-issues#2235]
Hello,

quick version:
In postprocessing, before moving/copying a new episode, please make Sickrage check for sufficient free space inside the actual destination folder (i.e. the folder where the episode would be put after renaming rules have been applied), not the default destination directory.

long version: 
I have Sickrage 4.0.39 installed on a virtual server with tight quota management. My tv shows reside on a separate fileserver, where each show is on a separate filesystem (this fileserver runs FreeBSD and the data is on ZFS). These tv-show folders are mounted separately from the fileserver under some root, say /mnt/tv, to the Sickrage server. In other words, the fs on the Sickrage server looks like /mnt/tv/show1, /mnt/tv/show2 etc., where show1, show2 etc. are separate filesystems on my fileserver. 
Under Sickrage, I have set the default destination folder to "/mnt/tv", but whenever adding a new show, I create the new filesystem on the fileserver manually. 
On the virtual server itself, there is very little free space available. Recently, I started getting "not enough free space" errors from postprocessing, which disappeared after I temporarily increased the quota of the Sickrage server. Therefore, I guess that the postprocess instance checks for sufficient free space directly at the default destination folder (in my case /mnt/tv, which is on the root of my Sickrage server), instead of checking the actual destination folder (for example /mnt/tv_show1/season1 or whatever filenaming rules are in place), which would reside on my fileserver and give correct values. 

Right now, I have resolved  the issue by setting the default destination folder to some already existing tv--show but it would be nice to properly fix this in Sickrage. Thank you very much!

**Comment by neoatomic** [comment]
We have indeed build-in a free-space check in post-processing. This is to prevent errors and the lost of files.
If i recall right it indeed does the check in main folder and not the sub folders. As you normally would expect that sub-folders are on the same disk and not redirected to another disk of share.

So in short your request is that the PP free space check can be done on the sub folders.

**Comment by miigotu** [comment]
@herrsimon If you change line 915 of sickbeard/postProcessor.py to:
`            if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps):`

does it fix your problem?

**Comment by herrsimon** [comment]
@miigotu  Yes, it works like a charm, thank you very much for this superfast fix! 

@neoatomic Exactly, this was my request.

**Comment by miigotu** [comment]
@neoatomic Previous check tested the library root dir for free space, now it checks the show folder itself.
