### ISSUE TITLE
[APP SUBMITTED]: CHECKVERSION :: git fetch origin returned : error: insufficient permission for adding an object to repository database .git/objects

fatal: failed to write object
fatal: unpack-objects failed

### ISSUE THREAD

**Issue by voyix** [SiCKRAGETV/sickrage-issues#2237]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.11-v7+-armv7l-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@aa9c1bf1ca2bf3df9cd33fe4e798c8247dfe1881
Link to Log: https://gist.github.com/1077a802045005a778a5
### ERROR
```
CHECKVERSION :: git fetch origin returned : error: insufficient permission for adding an object to repository database .git/objects

fatal: failed to write object
fatal: unpack-objects failed
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1882#issuecomment-114743527
