### ISSUE TITLE
Can't Restore Backup

### ISSUE THREAD

**Issue by ZMOT7S** [SiCKRAGETV/sickrage-issues#2238]
I was trying to update to the latest version yesterday. It failed so I used the Git Reset option and Sickbeard stalled during the restart. I waited about 15 minutes and nothing happened. I went to my seedbox client and manually restarted Sickbeard. When I went back to Sickbeard I get no connection "This Webpage Is Not Available." I had backed up Sickbeard so I uninstalled it from my seedbox and then reinstalled it. When I went to restore my backup, it said to restart Sickbeard. I restart Sickbeard and nothing happens. It's still a fresh install of Sickbeard. None of my settings are there. I've tried multiple times to uninstall/reinstall. I've tried 3 different backups and none of them do anything. I still just have a fresh version of Sickbeard with all default settings. 

Branch - Default Branch (Master I think)
Commit Hash - Sorry, I'm not sure what this is.
OS and Python Version - I'm on Windows 7. Sickbeard is hosted on my seedbox though. Seedboxes.cc is the site. Sorry, I'm not sure what they are using.
GIST Log - (Hope this is right) https://gist.github.com/ZMOT7S/e603b7587475a070fd55

**Comment by fernandog** [comment]
@ZMOT7S there's is nothing in your log about restore

stop SR, open your backup zip file. and unzip to SickRage folder

**Comment by ZMOT7S** [comment]
I did that and now most of my settings are there. So it seemed to partially work. All of my shows are missing though. Does it not keep that info in the back up? Should I post the log again?

**Comment by fernandog** [comment]
all info are in sickbeard.db

**Comment by ZMOT7S** [comment]
I see, everything looks good now. Thanks for the help!
