### ISSUE TITLE
[feature request] visible folder in showlist

### ISSUE THREAD

**Issue by wimpyrbx** [SiCKRAGETV/sickrage-issues#2240]
hi,

would it be possible to add this option?

D:\TV\ANIMATION\Show Name\Season 11\ShowName - S11E03 - Filename.mkv
to only display Season 11\ShowName - S11E03 - Filename.mkv

so.. remove parent folder. it's cluttering up the show view.

**Comment by fernandog** [comment]
where?? send a screenshot of your idea

**Comment by wimpyrbx** [comment]
http://www.fshare.it/image.jpeg?i=vx1437417k1

**Comment by wimpyrbx** [comment]
it would be excellent to be able to not display the full path here. to clean up the show page list.

**Comment by fernandog** [comment]
@wimpyrbx mine don't show

do you have more then one "Show root directories" in "General Configuration" - "Misc" ?

**Comment by wimpyrbx** [comment]
yes i have all the different folders i keep my TV shows in.
So for example i have:
* D:\TV\ANIMATIOn
* D:\TV\SCIFI
etc.

Kinda want to keep them in as I then can easily add existing shows as time progresses.
A basic "show/hide full path" option for Show Page would be excellent.

**Comment by fernandog** [comment]
@wimpyrbx without stopping SR

edit SickRage/gui/slick/interfaces/default/displayShow.tmpl, delete contents, past this one:

https://raw.githubusercontent.com/fernandog/SickRage/path_display_show/gui/slick/interfaces/default/displayShow.tmpl

Press full reload show page
report back

**Comment by wimpyrbx** [comment]
ok i fixed it by doing:
#set $filename = ntpath.basename($filename)
just before outputting $filename

that fixes my "issue", but would still be cool to have as option in general interface settings or somewhere :)

cheers!

**Comment by fernandog** [comment]
Please try my file

**Comment by wimpyrbx** [comment]
Nice one :+1: 
For my sake this can be closed as i've fixed my request with your help. Cheers!
However if anyone else would like to include this as a user option in settings to show/hide feel free.
Closing this for now.

**Comment by fernandog** [comment]
Path you can see in the top of the page
