### ISSUE TITLE
[Feature Request] Add known release groups list

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2242]
having an known release groups list,just like the removed words list .
This is usefull for the release groups (or individuals ) that dont follow the scene rules on naming releases but have the rg present on nthe file name . A good example of a filename is ```Ridiculousness S05E08 Chanel and Sterling XII (1280x720) [Phr0stY].mkv``` where  [Phr0stY] is the rg but since it isnt the correct naming wouldnt be detected, the known release groups list would fix this issue

**Comment by miigotu** [comment]
Not possible, release groups change too often.
Once guessit replaces name_parser we don't need a list anymore.

**Comment by duramato** [comment]
but for example whe take this release ```Burn Notice.S04E18.480p.vk007.mkv ```   couldnt it replace the ```.vk007```to ```-vk007```?

**Comment by miigotu** [comment]
Release groups don't release their files with many variations, they follow the naming convention as they understand it.
