### ISSUE TITLE
[APP SUBMITTED]: 'TVShow' object has no attribute 'show'

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2244]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:34:55) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-22-generic-i686-with-Ubuntu-15.04-vivid**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@a017c6e6eda57317a0be3dde9891789a169f97c4
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-RETRY-80270 :: [BTDigg] :: Error while searching BTDigg, skipping: 'TVShow' object has no attribute 'show'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@duramato Please add the logs.

**Comment by miigotu** [comment]
Fixed in develop.
