### ISSUE TITLE
[Feature Request] Selective Search by Provider

### ISSUE THREAD

**Issue by mbxplex** [SiCKRAGETV/sickrage-issues#2245]
Not sure if there is a current feature request currently open, as I did not find on via search, but I would like to see a feature that allowed me to select which shows are searched by which Providers. 

There are only a select amount of shows that I am not able to pull from an nzb site, and that is the ONLY reason I have certain providers like KickAss & SceneTime enabled. If I had the ability to only have those shows that I cannot get from the nzb sites pull from the torrent sites, it would make my life easier, as I do not prefer to download from torrent sites.

**Comment by neoatomic** [comment]
Its has been requested before.
The thing is that this will get very complex/confusing for users.
Its better to place the torrent providers at the bottom of your search providers list. Or use only nzb providers for daily searches and torrent providers for backlog searches.

**Comment by mbxplex** [comment]
@neoatomic The problem with this is I have my setup in this current configuration but a lot of my TV shows, considering I currently pull at any time 291 TV series, get added to torrent sites first so when  the daily search is  looking for new episodes, regardless of the torrent provider placement, it is still finding these EPs on the torrent sites first. 

I understand that it CAN become complex but SR can be a complex piece of software in general. So, if this is an option you only enable as a customary thing, the same way a "Required Word" is, but instead of adding to a list the way you do with the required words, you have the ability to check or uncheck certain providers that you want a show to be pulled from. It doesn't really sound that complicated to me ... When you go to an individual show's edit screen, all of the search providers you've selected during setup are listed and:

Option 1: They are all listed with check-marks listed next to them and you un-check the one's you do not want the show to be searched by. Or

Option 2: There is a double pane menu. On the left is the list of providers you've selected during setup and, very similar to setting up a custom nzb provider, you select 1 provider to move to the right pane so that show will ONLY be searched by that specific provider or by hold CTRL, you can select multiple providers to move to the right-pane.

**Comment by neoatomic** [comment]
Well it may sound not that complex to you but we need to look at it from a broader perspective. :)
And as i sad before, I'm skeptical about this request. But it will be considered by the Dev's.

**Comment by neoatomic** [comment]
@mbxplex As you have so many shows in your list, could you check if any network logos are missing.? 
(If you send me the exact names i will see if i can add those.)

**Comment by mbxplex** [comment]
@neoatomic sure! Let me take a look now.

**Comment by mbxplex** [comment]
@neoatomic all good on my end. I'll keep a look out. I'm US based and any new shows, usually on popular networks, are added to my database way ahead of their release date.

**Comment by mbxplex** [comment]
@neoatomic I lied ... "The Real Housewives of Melbourne" ... based on my google search It's a Bravo show ... It's also Australian based on a tv station called Arena, which does not have a logo

**Comment by mbxplex** [comment]
@neoatomic Also The FYI Network for the show "Epic Meal Empire" doesn't seem to be loading correctly or doesn't have a logo at all.

**Comment by mbxplex** [comment]
@neoatomic SoHo TV Logo for Wentworth seems to be missing or is extremely basic, but the logo is basic in general.

**Comment by mbxplex** [comment]
@neoatomic  Sorry for not seeing them the first time. They were easier to see when I organized by network. 

P.S. - Don't just me on Real Housewives!!!!! lol .. it's the girlfriends show (she basically runs my Plex Server)! :)

**Comment by neoatomic** [comment]
@mbxplex Thanks for checking. The logos will be fixed/added with the next update. :)

**Comment by mbxplex** [comment]
@neoatomic & @fernandog  , I'm not sure what else a large database can help with, but I'm currently in the process (made the order last night) of building a custom PC specifically for running a Plex Server that will host 8 x 6TB HDs with room for more. I will be transferring all my media over from my 10TB HDs along with the TV shows I have backed up (not included in SR) on my Google Drive and OneDrive accounts (Seinfeld, Dexter, Breaking Bad etc [all the greats]). 

On top of all the space, the custom PC will host 64GB of DDR4 RAM and an 8Core i7

**Comment by neoatomic** [comment]
@mbxplex Thats a very nice setup. However i'm wondering more how you will find the time to watch all those shows. :P

**Comment by fernandog** [comment]
I dont keep files. I wont re-watch everything

**Comment by mbxplex** [comment]
@neoatomic Between myself, the girlfriend, my roommate and the 20+ people I (used to) share my Plex Server with, the shows get watched very quickly and I have a lot of people who LOVE to re-watch shows over & over & over.  Plus, Plex also hosts a ton of movies, music, etc so it's people's Netflix, Hulu and Spotify all in one.

**Comment by mbxplex** [comment]
Plus I really don't like to delete things I don't think I can get back. I've watched myself delete a lot of TV shows and a couple months / a year later I'll have someone request the delete season / show back and I have a hard time getting it. So, that was probably one of the main reasons for the storage increase.

**Comment by mbxplex** [comment]
@fernandog  @neoatomic  @miigotu  I honestly don't know where to post this random question, never get answers on SR's main page and I'd honestly like the advice of the pro's over others so ...

Tut is a new show airing on FX and the other night, when it premiered for the first time, I noticed the first EP was pulled from an nzb site with a file name of Tut.Part.1 (bla bla bla). The point I'm trying to make is SR pulled this EP without a S01E01 or 1x1. How? (I also watched SR do it with another TV mini-series called The Spoils of Dying). 

The reason I ask is for another TV Series, HBO Documentary Film Series (aka HBO Documentaries). These doc's just don't pull. The main reason, I'm assuming, is because when they are posted, they are posted without without any sort of series tagging, but the documentary names always match. Any solution to this?

(I'll delete this comment since it doesn't apply but I'd love your guys input on this)

**Comment by miigotu** [comment]
@mbxplex Why would you prefer nzb over torrent? Torrents are usually way more reliable, for quality, non-corrupted, and less chance of malware/fakes.This is because i there is something wrong with the torrent, people simply stop seeding it (faster than scene can flag an nzb). An nzb provider might never even flag a bad nzb.

I think you have no idea how much code would have to be rewritten to make this FR. It is a SHIT TON. And with a shit ton of rewrite comes a shit ton of bugs.

**Comment by mbxplex** [comment]
@miigotu lol yea, I've established this FR is a LONGGGG shot. The idea popped into my head and I wrote it down. As for the NZBs, I prefer them over torrents because I can download at my maximum capacity, do not have to upload any specific amount and can move files to proper folders through SR without EVER having any issues.

**Comment by mbxplex** [comment]
@miigotu what about this HBO documentaries thing I just mentioned ... any ideas on that?

**Comment by miigotu** [comment]
@fernandog the documentaries thing he is talking about, is the same place the "smartish" code was.

**Comment by miigotu** [comment]
@mbxplex fernando already commented the code that does that, maybe try setting the show to air_by_date?

```python
            # be smartish about this
            #if self.show.genre and "talk show" in self.show.genre.lower():
            #    self.show.air_by_date = 1
            #if self.show.genre and "documentary" in self.show.genre.lower():
            #    self.show.air_by_date = 0
            #if self.show.classification and "sports" in self.show.classification.lower():
            #    self.show.sports = 1
```

**Comment by miigotu** [comment]
@mbxplex dunno bout you, but my torrents are downed at about 10MB/s

**Comment by mbxplex** [comment]
@miigotu I'll give the air-by-date a shot ... as for search providers, who's the top 3 at your list?

**Comment by fernandog** [comment]
Rarbg only.

**Comment by mbxplex** [comment]
@fernandog See, I feel like my collection is just too large to rely on one source like Rarbg

**Comment by miigotu** [comment]
Mostly use kat and rarbg, freeleech from a bunch of private ones as a last resort.

**Comment by mbxplex** [comment]
@miigotu idk why but the highest speeds I'll ever see off of kat or rarbg is 6MB/s .... and that's if I'm lucky!

**Comment by gabrielqduarte** [comment]
As requested to centralize similar requests, i'm gonna post here something i think would be great: To have the option to choose which rss feed to use to search for anime and TV Show, so that i can minimize the chances of getting incorrect shows or animes (with me, when sickrage download animes sometimes it happens to get the ep in the wrong language, thing that could be corrected simply by restricting which feed it should get animes, so that it doesn't try to search at, lets say, the pirate bay...)

**Comment by WebSpider** [comment]
Custom query URL can already be done with NZB. I agree it would be a good idea to allow overriding the torrent query URL, but we need to unify the torrent providers a bit, before we can do this.

In short: When we do this, we should do it for all torrent providers in one go, instead of adding to each provider.

-----Original Message-----

**Comment by miigotu** [comment]
I think he wants an option in each provider for:

[ ] - Enable this provider for anime searches

**Comment by gabrielqduarte** [comment]
Yes, is kinda like @miigotu said, but it would enable the provider ONLY for anime searches or only for TV shows (or, if both checkboxes are disabled, it would search both anime and tv shows)

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
