### ISSUE TITLE
[APP SUBMITTED]: RTorrent Still Broken in newest Release 

### ISSUE THREAD

**Issue by tvann2182** [SiCKRAGETV/sickrage-issues#2247]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 10:19:51) [GCC 4.3.6]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@ac27935188e351a7ffd869ff1555767987f62ce3
Link to Log: https://gist.github.com/3b0a4d2a7b4f7d2116af
### ERROR
```
Thread-36 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/sickbeard/webserve.py", line 814, in testTorrent
    client = clients.getClientIstance(torrent_method)
  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/sickbeard/clients/__init__.py", line 118, in getClientIstance
    module = getClientModule(name)
  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/sickbeard/clients/__init__.py", line 114, in getClientModule
    return __import__(prefix + name + '_client', fromlist=__all__)
  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/sickbeard/clients/rtorrent_client.py", line 26, in <module>
    from rtorrent.err import MethodError
ImportError: No module named err

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by tvann2182** [comment]
I have updated to the latest and i am using Rtorrent, i have followed the threads about running rm sickbeard/clients*.pyc and this still has not resolved my issue. i am running on QNAP i am not sure if this is also a contributing factor or not

**Comment by tvann2182** [comment]
also receiving the following when searching shows

AAImportError: No module named err
AA    from rtorrent.err import MethodError
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/sickbeard/clients/rtorrent_client.py", line 26, in <module>
AA    return __import__(prefix + name + '_client', fromlist=__all__)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/sickbeard/clients/__init__.py", line 114, in getClientModule
AA    module = getClientModule(name)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/sickbeard/clients/__init__.py", line 118, in getClientIstance
AA    client = clients.getClientIstance(sickbeard.TORRENT_METHOD)()
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/sickbeard/search.py", line 137, in snatchEpisode
AA    search.snatchEpisode(result)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/sickbeard/search_queue.py", line 227, in run

**Comment by adaur** [comment]
When I tried to connect to rTorrent, I would connect without issue but the torrents wouldn't start. I don't know if this is somehow related.

**Comment by miigotu** [comment]
`rm /share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/sickbeard/clients/*.pyc`

**Comment by tvann2182** [comment]
after running that command miigotu this still gives the same result of 

AAImportError: No module named err
AA    from rtorrent.err import MethodError
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/sickbeard/clients/rtorrent_client.py", line 26, in <module>
AA    return __import__(prefix + name + '_client', fromlist=__all__)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/sickbeard/clients/__init__.py", line 114, in getClientModule
AA    module = getClientModule(name)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/sickbeard/clients/__init__.py", line 118, in getClientIstance
AA    client = clients.getClientIstance(sickbeard.TORRENT_METHOD)()
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/sickbeard/search.py", line 137, in snatchEpisode
AA    self.success = search.snatchEpisode(searchResult[0])
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/sickbeard/search_queue.py", line 184, in run
2015-07-21 06:40:19 INFO     SEARCHQUEUE-MANUAL-157631 :: Downloading Rookie.Blue.S06E09.HDTV.x264-KILLERS from IPTorrents
2015-07-21 06:40:16 INFO     SEARCHQUEUE-MANUAL-157631 :: Quality of Rookie.Blue.S06E09.HDTV.x264-KILLERS is SDTV
2015-07-21 06:40:15 INFO     SEARCHQUEUE-MANUAL-157631 :: [IPTorrents] :: Performing episode search for Rookie Blue

**Comment by tvann2182** [comment]
so the issue is not resolved with running that command

**Comment by fernandog** [comment]
You need to stop SR before running it.

**Comment by tvann2182** [comment]
![image](https://cloud.githubusercontent.com/assets/13427261/8799543/c73d3eb0-2f78-11e5-8f88-2332a9fd194b.png)


i did exactly that and i am still encountering the same issue, it seems everytime i re-launch SR it re-creates the PYC files for generic, rtorrent and rtorrent_client

![image](https://cloud.githubusercontent.com/assets/13427261/8799571/0c7e0342-2f79-11e5-8c40-9b7a9e11670b.png)

**Comment by miigotu** [comment]
only __init__.py, and *_client.py should be there.

**Comment by tvann2182** [comment]
yes that is what is not making sense to me, every time i do the rm on the pyc when SR is turned off and then i start SR it recreates them. and the Rtorrent.py never got removed for some reason after the lastest update.

**Comment by tvann2182** [comment]
i just rm the rtorrent.py to try and fix the issue but that did not resolve it. i am still getting a new problem. 

AA
AANotImplementedError
AA    raise NotImplementedError()
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/lib/rtorrent/__init__.py", line 89, in _get_conn
AA    self._rpc_methods = self._get_conn().system.listMethods()
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/lib/rtorrent/__init__.py", line 150, in _update_rpc_methods
AA    return(self._rpc_methods or self._update_rpc_methods())
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/lib/rtorrent/__init__.py", line 161, in _get_rpc_methods
AA    assert "system.client_version" in self._get_rpc_methods(
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/lib/rtorrent/__init__.py", line 122, in _verify_conn
AA    self._verify_conn()
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/lib/rtorrent/__init__.py", line 83, in __init__
AA    self.auth = RTorrent(self.host, self.username, self.password, True, tp_kwargs=tp_kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/sickbeard/clients/rtorrent_client.py", line 50, in _get_auth
AA    if not self._get_auth():
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/sickbeard/clients/generic.py", line 177, in sendTORRENT
AA    dlResult = client.sendTORRENT(result)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/sickbeard/search.py", line 138, in snatchEpisode
AA    self.success = search.snatchEpisode(searchResult[0])
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/sickbeard/search_queue.py", line 184, in run
2015-07-21 07:32:15 INFO     SEARCHQUEUE-MANUAL-157631 :: Downloading Rookie.Blue.S06E09.HDTV.x264-KILLERS from IPTorrents
2015-07-21 07:32:14 INFO     SEARCHQUEUE-MANUAL-157631 :: Quality of Rookie.Blue.S06E09.HDTV.x264-KILLERS is SDTV
2015-07-21 07:32:12 INFO     SEARCHQUEUE-MANUAL-157631 :: [IPTorrents] :: Performing episode search for Rookie Blue

**Comment by miigotu** [comment]
1. It is supposed to recreate the pyc.
2. Some reason git did not remove them I don't know why.

Stop sickrage, delete these files:
```
sickbeard/clients/download_station.py
sickbeard/clients/utorrent.py
sickbeard/clients/generic.py
sickbeard/clients/qbittorrent.py
sickbeard/clients/transmission.py
sickbeard/clients/deluge.py
sickbeard/clients/rtorrent.py
sickbeard/clioents/*.pyc
```

**Comment by tvann2182** [comment]
i believe i have it resolved testing now

**Comment by miigotu** [comment]
Next time, use gist for logs/errors. A long paste here just makes it a PITA to follow conversation.

**Comment by tvann2182** [comment]
Ok, by RM the rtorrent.py and then resetting the SSL checkbox in rtorrent settings it is now up and runniing again. I appreciate all the help if i wouldnt have had someone to float ideas from i would have been lost. i have been looking at this for  2 days appreciate the help


it was the stuck rtorrent.py causing the issue and the pyc files

**Comment by tvann2182** [comment]
ok will do

**Comment by tvann2182** [comment]
so since i only use rtorrent should i remove the other torrent options?

**Comment by miigotu** [comment]
Doesn't matter, only matters if they are enabled.

**Comment by FuNK3Y** [comment]
Go get it working again here is what I did:
Stop sickrage
Enter the sickrage install folder
git pull
find -name *.pyc -delete
Restart sickrage

It worked fine after that

**Comment by arebokert** [comment]
I didn't have generic.py at all which gave me the error, git reset --hard and git pull made it work for me.
