### ISSUE TITLE
[APP SUBMITTED]: int() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by joakimvester** [SiCKRAGETV/sickrage-issues#2249]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: ****
Commit: SiCKRAGETV/SickRage@e2318076201cb9a0b4e6fb0bce7aa6504be524a3
Link to Log: https://gist.github.com/3c435927373c4274c7aa
### ERROR
```
Thread-63 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 1322, in displayShow
    return t.respond()
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/cache/cheetah/_share_CACHEDEV1_DATA__qpkg_SickBeard_TVRage_SickBeard_TVRage_gui_slick_interfaces_default_displayShow_tmpl.py", line 1148, in respond
    if int(VFFSL(SL,"epResult",True)["status"]) != VFFSL(SL,"UNAIRED",True): # generated from line 494, col 17
TypeError: int() argument must be a string or a number, not 'NoneType'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
not a SR branch. please use 'master' branch

**Comment by joakimvester** [comment]
Hi

I have a problem changing the branch version, as I get an error saying: "Error: No branches found."  when I want to use the drop-down menu in the General setting tab.  

What could cause this ?

**Comment by fernandog** [comment]
don't know. 

stop SR
enter sickrage folder
run:
git checkout master

**Comment by crowaust** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2008ServerR2-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@4028db3d7a2cc582b0f591d981ed3af344b4e75a
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-ADD :: Error searching dir for episodes: int() argument must be a string or a number, not 'NoneType'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
