### ISSUE TITLE
[Feature Request] Timeout for snatched episodes. (Basic failed download function)

### ISSUE THREAD

**Issue by neoatomic** [SiCKRAGETV/sickrage-issues#225]
From time to time SR snatches a nzb file that has a password set and the download fails.
If that happens SR leaves the episode on the status "snatched" indefinitely if you are not using mediatonzb/post processing.

As many users find setting-up post processing difficult, it might be an idea to implement a "timeout" for snatched files/episodes.
Meaning that when SR snatches an episode the download client has (for example)  24 hours to provide the file to SR.
If SR does not find/receive it within this time period the snatch status is reset to "wanted" and the failed nzb/torrent is written to the failed.db to not be used again.

With this function you would have a "basic" failed download function in SR even without using post-processing scripts.

**Comment by neoatomic** [comment]
Currently you need to have post processing setup for SabNZB to sent that to Sickrage.
Fernandog suggestion would make use op the build-in API to do that. So with this users dont have to setup anything. (at least for those basic functions)
However not all download clients support this, so a timer for snatched downloads would serve as a backup.

**Comment by bthusby** [comment]
Torrents should have a timer, or feedback when inactive for a while, to move on to the next torrent provider, or even better the next best torrent anywhere (i.e. also with the same provider if found best). Clean up, blacklist, and delete all partials from the attempt. Right now a torrent can stall for ever....

**Comment by markheloking** [comment]
I'm also experiencing this problem. This is the main reason I have torrents disabled right now.

**Comment by WebSpider** [comment]
+1

**Comment by fernandog** [comment]
For torrents the solution is a better or private provider.
NZB a possible solution is enabled failed and use NZBtoMedia.

Torrent the best solution is SR fetches if the torrent is stalled and mark as failed and get a new one.
nzb already there is the nzbtomedia.
@tagforce

**Comment by TagForce** [comment]
@fernandog Stalled downloads is already on the to do list. It needs 2 things, though.
- A new db field to store the torrent hash.
- A change in the torrentclient api's code to allow deleting the torrents and to  fetch information on them.

**Comment by fernandog** [comment]
@tagforce transmission allow it.
@abeloin what about deluge?

**Comment by abeloin** [comment]
Yes deluge support deleting torrent.

**Comment by TagForce** [comment]
@abeloin @fernandog uTorrent also allows this, I think this is a basic function of all API's. It just needs to be added to out client api code in a universal way.

We should also look at support for NZBs in this matter.

**Comment by fernandog** [comment]
@TagForce is there a proper issue for this? We are going to do a timeout OR we will check downloaders for failed/stalled episodes from time to time?

**Comment by TagForce** [comment]
We're going to have an internal timeout (configurable in hours) for snatches. This is all part of the torrent client 'overhaul', that will improve client API support.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
