### ISSUE TITLE
Snatched episodes while status is IGNORE

### ISSUE THREAD

**Issue by palmfighter** [SiCKRAGETV/sickrage-issues#2251]
**Branch:** 
Master
**Commit hash:** 
ac27935188e351a7ffd869ff1555767987f62ce3
**Your operating system and python version:** 
Synology NAS, 2.7.10 (default, Jun 3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]
**What happened:**
Status of a season is set to ignore, however SickRage still went on and downloaded the files -> snatched. I have deleted the show, added again, again set to ignore, but still it goes on and downloads the files
**What you expected:**
No snatches as episodes are on Ignored. I have this with 2 shows only. Not all

**Comment by miigotu** [comment]
@fernandog trakt nonsense?

Honestly, trakt is becoming more of a liability than an asset, just sayin.

**Comment by fernandog** [comment]
@palmfighter Logs?? 

Do you set as IGNORE after adding the show or when adding the show? If you set after maybe those ep are already in the queue

**Comment by palmfighter** [comment]
Hi, so I have tried many ways so far to see where the problem comes from. I set it to ignore multiple times, but still I get snatches. What I did just now is set them back to Ignore and Force the various searches / backlog / daily search / proper search, but nothing was triggered now. 

Sorry I don't have logging of this happening, when it happens again I will try to collect some logs.

**Comment by fernandog** [comment]
@palmfighter 
please answer this: Do you set as IGNORE after adding the show or when adding the show (in add show customize options)?

**Comment by palmfighter** [comment]
Hi, sorry I answered not before. So when I added the show, I set it to SKIPPED for old episodes and WANTED for new episodes. But the problem exists for weeks. Before I removed the show I was seeing it as well. Everytime I changed it to IGNORE and then within 24 hours I got SNATCHES again. So my last 'try' was removing it completely and adding it back again. At that time I chose SKIPPED for old episodes and made it a default setting.

**Comment by fernandog** [comment]
@palmfighter do you have the files in the show folder for this episodes you set to IGNORE?

**Comment by palmfighter** [comment]
@fernandog yes I do have files. F.e. Gotham.S01E01.HDTV-lol.mp4. 
Perhaps good to know the quality setting for this show is:
Quality:	Initial: 720p WEB-DL 
Replace with: 720p WEB-DL, 1080p WEB-DL

**Comment by fernandog** [comment]
@palmfighter as SR found the files, it changed the episode status! You should set ARCHIVED when you have the file and don't want anymore downloads or just enable "ARCHIVE IN THE FIRST MATCH"

https://github.com/SiCKRAGETV/SickRage/wiki/Quality-Settings

**Comment by palmfighter** [comment]
@fernandog thanks for the explanation, sorry for the hassle, so even when I tell to SKIP or IGNORE it still wants to download the new versions. I use it for some years now, but that wasn't clear to me at all. Thanks guys for helping out. I will set them to ARCHIVE and see what happens!

**Comment by palmfighter** [comment]
@fernandog sorry to come back on this. Now I have another issue when using the ARCHIVED setting. As my torrents are still being seeded from the folder that SR uses for processing it processes them again... So even when I change to ARCHIVE, the file is then processed again. Is this expected behaviour?

**Comment by fernandog** [comment]
do you use PP? hardlink?
don't use archive status. and without logs there's nothing we can do to debug

**Comment by fernandog** [comment]
there's no log saying it was downloaded again. only processed
is there any new torrent/nzb in your client?

**Comment by palmfighter** [comment]
@fernandog sorry for the confusion, I said downloaded again, I mentioned processed it again. Which I don't expect as the serie is set to finished / archived. So how do I stop from further processing again in my setup? I cannot use IGNORE / SKIPPED because the files are there and then it tries to download them again. If I set it to ARCHIVE it processes them again. I'm a bit confused now ;)

**Comment by fernandog** [comment]
@neoatomic if the episodes remains in PP folder, will SR processe it always until removed from PP folder? Sorry, don't use PP

**Comment by neoatomic** [comment]
I actuality use the sabtonzb script not the traditional PP method, and i dont use torrents at all. :) 

Yes, if its in the folder and you have setup SickRage to scan the folder than it will try to PP until its gone. The only thing thats stops PP if there is a !sync (or similar name ) present in the subfolder so that SickRage knows that the file is still in "use" and stops PP. You will have to check the torrent client for that function.

This is a guide and has a section on PP. Might help to clear some thing up. 
http://www.htpcguides.com/configure-sickrage-usenet-torrent-tv/

**Comment by palmfighter** [comment]
Hi @neoatomic @fernandog I read through the guides and nothing is new. Also the !sync file is clear to me. I use Transmission and as long as a file is being downloaded, the post-processor will not try to rename and move the file. The post-processor also knows if it already has moved / copied /  linked a file in most of the cases. I use hard-link because I like to seed for a long time for the sites I use. So far no issues whatsoever. The only thing now I run into is the ARCHIVE option. As soon as I enable this. Somehow SR will re-process the file and hard-links it again. So I guess there is a bug in the PP. It should ignore files in the PP folder IF there is already a file in the destination (home) folder and/or the episode is on ARCHIVE.

**Comment by neoatomic** [comment]
So if you set that episode to ignored/skipped its not picked up by PP in the TV download folder.? That only happens if you use the ARCHIVE option for that episode.?

**Comment by palmfighter** [comment]
So to make sure I am testing correct I have checked transmission which files it has for a series:
I have episodes 6,7,8,9,10, all 1080P HDTV, for episode 8 I also have a PROPER 720P version. 

- There is one bug I see now, as I change the episode 8 to SKIPPED again it tries to move the proper 720p version when the 1080P is in the destination folder (series folder) and moves the 1080P when the proper is in there.. this happens only ONE TIME. After that it is not trying to move again till I manually change the file to SKIPPED again. 
-> to workaround this issue I removed the 720P proper now from the transmission download so I am not bothered about that again, perhaps this is a very specific situation, but if you can fix that?

- It seems that the archive setting doesn't start the re-processing of earlier processed files now. I cannot seem to reproduce it. Not sure what happened before.
