### ISSUE TITLE
Can not change the value of "Backlog search frequency"

### ISSUE THREAD

**Issue by Kaoz52** [SiCKRAGETV/sickrage-issues#2256]
Sorry, I am french and bad English ... I use Google Trad. I put the original in French under the post.

Hi,

I have a problem, I'd change the "**Backlog search frequency**" in the "**Search Settings**".

I tried to change the value and restart but the value returns to 720.
I also tried to stop the daemon via Sickrage (/etc/init.d/sickrage stop) and change the "*config.ini*" but when I start sickrage and I go to "**Server Status**" remains 12h (720 minutes).
I check the "*config.ini*", it is well to 30 as shown. I think it's just a display problem but the first restart, the value is displayed again to 720 in the "*config.ini*".

Is there a way to change this?

For information, I want to change this value because the "**Daily search**" never find me anything.

Example this morning with the series "Ballers" I see on the tracker FTDB the last episode was mailed to 8:14, I'll see in Sickrage it is on "Wanted", since it is 9:35, he should have me find it. When I go to the logs, here's what I have:

```
2015-07-21 8:27:02 DAILYSEARCHER INFO :: No new episodes released found ...
2015-07-21 8:27:02 DAILYSEARCHER INFO :: Searching for new episodes released ...
```
And as soon as I do a manual search, he finds me directly episode ...
This is why I would like to reduce the "**Backlog search frequency**" which is much more effective.

Otherwise I have a Debian Dedibox 8. I have no "*Log (error)*" in Sickrage.

I hope I was clear enough, if anyone has a solution I am at your service!

Thank you in advance

--------------------------------------------------------------------------------------------------------------------------------------------

Salut,

J'ai un problème, j'aimerai modifier le "**Backlog search frequency**" dans "Search Settings".

J'ai essayé de changer la valeur et de redémarrer mais la valeur revient à 720. 
J'ai également essayé d'arrêter Sickrage via le daemon (/etc/init.d/sickrage stop) et de modifier le "*config.ini*" mais quand je démarre sickrage et que je vais dans "**Server Status**" il reste sur 12h (720 minutes). 
Je vérifie le "*config.ini*", il est bien à 30 comme indiqué. Je pense que c'est juste un problème d'affichage mais au premier redémarrage, la valeur est de nouveau affichée à 720 dans le "*config.ini*".

Est-ce qu'il y a un moyen de modifier cette valeur ?

Pour information, je souhaite modifier cette valeur car le "**Daily search**" ne me trouve jamais rien.

Exemple ce matin avec la Série "Ballers", Je vois sur le tracker FTDB que le dernier épisode a été posté à 8h14, je vais voir dans Sickrage, il est sur "Wanted", vu qu'il est 9h35, il aurait du me le trouver. Quand je vais voir les logs, voici ce que j'ai :

2015-07-21 08:27:02 INFO     DAILYSEARCHER :: No new released episodes found ...
2015-07-21 08:27:02 INFO     DAILYSEARCHER :: Searching for new released episodes ...

Et dès que je fais une recherche manuelle, il me trouve directement l'épisode... 
C'est pourquoi j'aimerai réduire le "**Backlog search frequency**" qui est beaucoup plus efficace.

Sinon j'ai une Dedibox sous Debian 8. Je n'ai aucun "Log (error)" dans Sickrage.

J'espère avoir été assez clair, si quelqu'un a une solution je suis à votre écoute !

Merci d'avance

**Comment by miigotu** [comment]
minimum value for backlog search is 720 minutes.
daily search had some bugs that should be fixed, at least in develop.
