### ISSUE TITLE
ShowQueue ADD does not result in high priority queue entry

### ISSUE THREAD

**Issue by coderbone** [SiCKRAGETV/sickrage-issues#2257]
In show_queue.py the following lines of code:

        # Process add show in priority
        self.priority = generic_queue.QueuePriorities.HIGH

Need to be moved down a few lines so that they are *after* ShowQueueItem.__init__ otherwise the priority gets set back to NORMAL

**Comment by neoatomic** [comment]
@coderbone Thanks for reporting. :) 

@miigotu 
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/show_queue.py#L219

**Comment by miigotu** [comment]
Thanks.
