### ISSUE TITLE
[APP SUBMITTED]: 'ascii' codec can't encode character u'\xea' in position 34: ordinal not in range(128)

### ISSUE THREAD

**Issue by Lowmach1ne** [SiCKRAGETV/sickrage-issues#2259]
### INFO
Python Version: **2.7.5 (default, Jun 17 2014, 18:11:42) [GCC 4.8.2 20140120 (Red Hat 4.8.2-16)]**
Operating System: **Linux-2.6.32-39-pve-x86_64-with-centos-7.1.1503-Core**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@ac27935188e351a7ffd869ff1555767987f62ce3
Link to Log: https://gist.github.com/b92487035b7777772377
### ERROR
```
SHOWQUEUE-REFRESH :: 81670: Could not refresh subtitles
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
please set locale to UTF-8 to the **user that runs SickRage**.
Check the user name in localhost:8081/config

https://sickrage.tv/forums/forum/help-support/general-support/12825-ensuring-your-locale-s-are-set-properly-to-avoid-unicode-issues
