### ISSUE TITLE
Add Persistent Collapse Expand Buttons to Subtitles management

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#2261]
Needs to be done similar as this PR:
https://github.com/SiCKRAGETV/SickRage/pull/1851/files

I'm not JS expert

**Comment by fernandog** [comment]
@MGaetan89 do you know JS?

**Comment by MGaetan89** [comment]
I do, but I don't use subtitles. So I have to set it up first to see what you want here :P

**Comment by fernandog** [comment]
the expand button works. but you can't collapse as this "collapse" button doesnt exists

**Comment by MGaetan89** [comment]
Ok, I will change that

**Comment by MGaetan89** [comment]
I just set up subtitles on my test installation and understand the request.
I will add that and send a PR soon.

**Comment by fernandog** [comment]
Thanks!

**Comment by MGaetan89** [comment]
Fix is in SiCKRAGETV/SickRage#2176

**Comment by fernandog** [comment]
thanks!
