### ISSUE TITLE
[APP SUBMITTED]: No module named err

### ISSUE THREAD

**Issue by Takayuki80** [SiCKRAGETV/sickrage-issues#2263]
### INFO
Python Version: **2.7.3 (default, Dec 18 2014, 19:10:20) [GCC 4.6.3]**
Operating System: **Linux-2.6.32-042stab102.9-x86_64-with-Ubuntu-12.04-precise**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@ac27935188e351a7ffd869ff1555767987f62ce3
Link to Log: https://gist.github.com/fe272c1a3885ae9b50d4
### ERROR
```
Thread-60 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/seeduser/sickrage_install/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/home/seeduser/sickrage_install/sickbeard/webserve.py", line 814, in testTorrent
    client = clients.getClientIstance(torrent_method)
  File "/home/seeduser/sickrage_install/sickbeard/clients/__init__.py", line 118, in getClientIstance
    module = getClientModule(name)
  File "/home/seeduser/sickrage_install/sickbeard/clients/__init__.py", line 114, in getClientModule
    return __import__(prefix + name + '_client', fromlist=__all__)
  File "/home/seeduser/sickrage_install/sickbeard/clients/rtorrent_client.py", line 26, in <module>
    from rtorrent.err import MethodError
ImportError: No module named err

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by adaur** [comment]
Possible duplicates:

https://github.com/SiCKRAGETV/sickrage-issues/issues/2247
https://github.com/SiCKRAGETV/sickrage-issues/issues/2188

**Comment by fernandog** [comment]
@miigotu hotfix?!

**Comment by miigotu** [comment]
@fernandog I don't know how I should hotfix git not removing files lol.

https://github.com/SiCKRAGETV/sickrage-issues/issues/2247#issuecomment-123275228

**Comment by fernandog** [comment]
@miigotu 
I thought it was another error. sorry.
git clean by default will fix that then. should we merge develop into master?

**Comment by miigotu** [comment]
@fernandog git reset --hard and git clean won't remove those, because they aren't tracked, and we cannot track them.
