### ISSUE TITLE
[APP SUBMITTED]: not a valid bencoded string

### ISSUE THREAD

**Issue by TheFuzzyOne87** [SiCKRAGETV/sickrage-issues#2264]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-43-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@0308a49dcb9bf9bef03ec49a897a8373b399398c
Link to Log: https://gist.github.com/5698dce6883450299f0f
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by TheFuzzyOne87** [comment]
I just this second migrated Sickrage from my Synology NAS device onto a small linux machine running Ubuntu and it seems like it now can't talk to download station on the NAS although when I test it from sickrage it says its successful

**Comment by fernandog** [comment]
Disable proxy please for provider please

**Comment by TheFuzzyOne87** [comment]
thanks @fernandog this looks like it made a difference

**Comment by Grimmoire0** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Grimmoire0** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: Transmission: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by ming1981** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by ming1981** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: Transmission: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by kriebb** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
Link to Log: https://gist.github.com/8bdfc8bb89d334ceb667
### ERROR
```
SEARCHQUEUE-BACKLOG-73141 :: [Cpasbien] :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by kriebb** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
Link to Log: https://gist.github.com/aefa79eb45a0c772ec45
### ERROR
```
SEARCHQUEUE-BACKLOG-73141 :: [Cpasbien] :: Transmission: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by kriebb** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-73141 :: [Cpasbien] :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by kriebb** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-73141 :: [Cpasbien] :: Transmission: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by kriebb** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-73141 :: [Cpasbien] :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by kriebb** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-73141 :: [Cpasbien] :: Transmission: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by kriebb** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-73141 :: [Cpasbien] :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by kriebb** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-73141 :: [Cpasbien] :: Transmission: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by kriebb** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-73141 :: [Cpasbien] :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by kriebb** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-73141 :: [Cpasbien] :: Transmission: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by kriebb** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-73141 :: [Cpasbien] :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by kriebb** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-73141 :: [Cpasbien] :: Transmission: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by kriebb** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-73141 :: [Cpasbien] :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by kriebb** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-73141 :: [Cpasbien] :: Transmission: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by kriebb** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-73141 :: [Cpasbien] :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by kriebb** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-73141 :: [Cpasbien] :: Transmission: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by kriebb** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-73141 :: [Cpasbien] :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by kriebb** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-73141 :: [Cpasbien] :: Transmission: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by kriebb** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-73141 :: [Cpasbien] :: Transmission: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by kriebb** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-73141 :: [Cpasbien] :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by kriebb** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-73141 :: [Cpasbien] :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by kriebb** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-73141 :: [Cpasbien] :: Transmission: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by kriebb** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-73141 :: [Cpasbien] :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by kriebb** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-73141 :: [Cpasbien] :: Transmission: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
