### ISSUE TITLE
Unable to find Dragon Ball Super Episodes

### ISSUE THREAD

**Issue by uonze** [SiCKRAGETV/sickrage-issues#2265]
Branch: (master)
Commit: 0308a49dcb9bf9bef03ec49a897a8373b399398c
Python Version: 2.7.3

Since Dragon Ball Super is in the Anime category in Kickass Torrents (the only search provider I'm using), I think this is the reason for SickRage not finding any episodes. Any workaround?

**Comment by miigotu** [comment]
Anime is a genre on kickass, not a category. https://kat.cr/tv/genre/anime/

What settings for anime/absolute numbering do you have for this show?

**Comment by trisk** [comment]
The anime-specific providers (Nyaa and TokyoTosho) cover most anime and are updated frequently, so you should always use them  for anime.

**Comment by uonze** [comment]
I didn't know I had to mark the show as Anime (or even I could do that). Reading the description of the Anime option it should solve the problem because the episode number on Kickass was 00X..

Thanks a lot for the help

**Comment by miigotu** [comment]
It used to auto-force it, but there were too many instances where xem said releases were put out using absolute numbering when they weren't, so we decided it was better that the user could control it.
