### ISSUE TITLE
Paused shows are downloading

### ISSUE THREAD

**Issue by Hiltronix** [SiCKRAGETV/sickrage-issues#2267]
I'm seeing shows that are marked as paused, but also set to wanted in "Default Ep Status" downloading new episodes.  I would have expected the paused parameter to take priority over future episodes being set to wanted.  Has anyone else noticed this?  

SR Version: BRANCH: (master) / COMMIT: (0308a49dcb9bf9bef03ec49a897a8373b399398c)

**Comment by miigotu** [comment]
May need to add some more accurate sql to daily searcher.

**Comment by miigotu** [comment]
@Hiltronix I'm confused as to what you are reporting.

Are you saying episodes are actually snatched when the show is paused or that the status is merely changing when it is paused?

Daily searcher and backlog search are both skipping any episodes that belong to a paused show already.

If you merely mean the status of the episode is being updated/changed to the proper status while it is paused then that is what is supposed to happen.

**Comment by fernandog** [comment]
I have lot's of paused shows. not downloads BUT episodes as changing to default_ep_status as it should

**Comment by miigotu** [comment]
@fernandog I agree they should change status to what they would be as if the show were not paused. I have checked the daily search, backlog search, etc, and all of it does honor paused parameter. Only need to check trakt I guess if this is really happening, just need the OP to clarify.

**Comment by Hiltronix** [comment]
@miigotu  I'm saying that I have shows that are set to paused being snatched and downloaded, the same as if they are not paused.  It started happening a few days ago, and I upgrade SickRage daily whenever new versions are pushed out.  

In the sqlite database "tv_shows" table, the paused shows I'm saying are being snatched and downloaded, are set to 1 for "paused" and set to 3 for "default_ep_status".

**Comment by miigotu** [comment]
Then it can only be a trakt issue.

**Comment by fernandog** [comment]
@Hiltronix do you have traktrolling enabled?

**Comment by Hiltronix** [comment]
I don't use trakt.  I don't even know where that setting is located.

**Comment by fernandog** [comment]
@Hiltronix please send full logs when the snatch is happening. make sure debug is enabled in general settings

**Comment by lendenrk** [comment]
Hi, I'm in the same situation here. I've several shows that are paused but they still are snatched and downloaded. Here are some logs from the last night. For example the show "Suits" is paused, but the episode was snatched and downloaded.

https://gist.github.com/lendenrk/9f02cfdf7b54634715a2

BRANCH: (master) / COMMIT: (eb6f4d46709f4b3dd337c56573feb5bac27b10a9)

**Comment by fernandog** [comment]
send full print of the show page please

**Comment by lendenrk** [comment]
done http://i.imgur.com/IsW9VON.png

**Comment by fernandog** [comment]
Did you forced manual search?

**Comment by lendenrk** [comment]
No, I did not. I was sleeping :)

**Comment by fernandog** [comment]
that's odd cause I have paused shows and they don't get downloaded.

stop SR,
delete SickRage/Logs
start
please mark that last ep of that show to WANTED
go to manage searchs
force backlog search and see if if snatches
force daily search and see if if snatches

**Comment by lendenrk** [comment]
So I did as you asked.
The episode wasn't snatched :/

**Comment by fernandog** [comment]
Monitor this shows in the next days/weeks

**Comment by Hiltronix** [comment]
Since the last update, one of the shows that did get snatched and downloaded on my system, did not do so yesterday.  One of them is due to air tonight, so I will watch for that between now and tomorrow.

However, I am seeing all the shows that I have paused, but are "continuing" show up in the "Coming Episodes" report at the top of the list as "Missed" and highlighted in pink.  I don't remember that being the case till recently.  Why should shows that are marked "paused" be displayed as missed?  I can see this being important to know if they weren't paused and didn't get downloaded.  But if the user pauses them, why show as missed in the Coming Episodes report?  Is that a new feature or have I not noticed till now?  Personally I would prefer to not see paused shows show as missed.

Thanks.

**Comment by fernandog** [comment]
https: //github.com/SiCKRAGETV/sickrage-issues/issues/589 first topic. it's the TODO list

**Comment by fernandog** [comment]
@Hiltronix 
there is a list box in the top right corned to hide PAUSED

**Comment by Hiltronix** [comment]
@fernandog Thanks for pointing out the list box filter!  Sometimes the obvious is the easiest to over look. :)

**Comment by lendenrk** [comment]
Well unfortunately I had the bad surprise this morning to see that two other shows that were paused yesterday (I checked) were snatched and downloaded last night.

I don't understand why. :/

**Comment by fernandog** [comment]
@lendenrk need full logs with debug enabled

**Comment by lendenrk** [comment]
@fernandog here are my logs 
https://gist.githubusercontent.com/lendenrk/8a8c98328ee7c0bd2772/raw/0f7f0790a11feecb3617761d317b15de5e9ed5dc/gistfile1.txt

"Under the Dome" at the begining and "Hannibal" were both snatched and downloaded, while they shouldn't as they are paused

**Comment by fernandog** [comment]
@lendenrk please use the log filter and filter: SEARCHQUEUE-DAILY-SEARCH

post results. there's too much postprocesser log lines

**Comment by lendenrk** [comment]
@fernandog done
https://gist.github.com/lendenrk/1e74fa39a512c0592e97

**Comment by fernandog** [comment]
@miigotu maybe this break something?

https://github.com/SiCKRAGETV/SickRage/commit/3c97dc8370525eb7a2e4721e9a4c9f594049d7fa

**Comment by miigotu** [comment]
@fernandog negative, _get_segments checks if the show is paused that the start of the function, and wantedEpisodes is only called form one place, and only `if not curShow.paused`

**Comment by Hiltronix** [comment]
@fernandog  I'm still having some issues with paused shows.  They are no longer downloading, but they are showing up in the backlog list when queried from the webapi.  They show up as "missed" in the web UI Backlog Overview.  

Up until recently, this was not the case.  Paused shows that did not get downloaded, did not show up in the webapi backlog.  Now actual backlogged shows, and missed paused shows, both show up in the webapi backlog.

For example when I query the webapi for a backlog like so:  
https://192.168.0.115:8080/api/xxx/?cmd=backlog  

As you pointed out before, I can hide them in the web UI be selecting "View Paused: Hidden", and that's fine, but I feel this is still a problem when retrieving this info using the the webapi.  I don't think missed shows should be considered backlog shows.

I am the author of a Kodi app that interacts with SickRage, and uses the api info.  So getting accurate info from the webapi is valuable to me.  I've been watching this for several days to make sure it wasn't a one time glitch.  I now have to manually change the episode status or each "missed" show that is "paused" to "skipped" so they are removed from the webapi backlog output.

Windows 7 64bit
Python 2.7 64bit
SR Version: BRANCH: (master) / COMMIT: (8fa7a4bb777c9192bd706115579e540eed8461b2)
