### ISSUE TITLE
Error: '_socketobject' object has no attribute 'set_tlsext_host_name'

### ISSUE THREAD

**Issue by linux4life1** [SiCKRAGETV/sickrage-issues#2268]
Centos 6.6 final

followed instructions at  https://github.com/SiCKRAGETV/SickRage/wiki/Installation%20Instructions

get this error in the logs. and no episodes are sent to NZBget

Error: '_socketobject' object has no attribute 'set_tlsext_host_name'

**Comment by miigotu** [comment]
```
sudo yum install python-pip
sudo pip install -U pyopenssl==0.13.1
```

**Comment by linux4life1** [comment]
[root@localhost ~]# yum install python-pip
Loaded plugins: fastestmirror, presto, refresh-packagekit, security
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirror.redsox.cc
 * epel: linux.mirrors.es.net
 * extras: mirrors.syringanetworks.net
 * rpmfusion-free-updates: mirror.redsox.cc
 * rpmfusion-nonfree-updates: mirror.redsox.cc
 * updates: linux.mirrors.es.net
Package python-pip-7.1.0-1.el6.noarch already installed and latest version
Nothing to do
[root@localhost ~]# pip install -U pyopenssl==0.13.1
-bash: /usr/bin/pip-python: No such file or directory

**Comment by linux4life1** [comment]
I hope you see that comment I just posted. because my issue was closed and it is not resolved.

**Comment by miigotu** [comment]
Google about using pip on CentOS.

Bottom line you need pyopenssl==0.13.1

You could try yum install python-openssl or yum install python-pyopenssl

**Comment by bioshock47** [comment]
Hello,

I have an issue, someone tell me to discuss about it here
i have this log
https://www.dropbox.com/s/jjyw1wzmf19zizm/Log%20sickrage.txt?dl=0

I have a QNAP NAS.

How can i fix this error i have? 

regards

**Comment by miigotu** [comment]
@bioshock47 check qnap forums about python 2.7.9 and pyopenssl
