### ISSUE TITLE
SR stops after latest update with trace error

### ISSUE THREAD

**Issue by zflash** [SiCKRAGETV/sickrage-issues#2269]
After last nights commit, SR crashes with the following error:

07:41:37 DEBUG::MAIN :: Retrieving the last check time from the DB
Traceback (most recent call last):
File "sickbeard.py", line 577, in <module>
SickRage().start()
File "sickbeard.py", line 346, in start
self.fix_clients_nonsense()
TypeError: fix_clients_nonsense() takes no arguments (1 given)

An git reset didn't work.

**Comment by zflash** [comment]
Fixed this on my install by reverting this change start SR, letting SR crash and resetting / pulling the git update again. Seemed to do the trick.

**Comment by miigotu** [comment]
just git pull is enough =P

**Comment by zflash** [comment]
Thanks. Didn't work this morning though, but on the other install I maintain, it did work :)
