### ISSUE TITLE
[APP SUBMITTED]: not enough arguments for format string

### ISSUE THREAD

**Issue by squareflapjack** [SiCKRAGETV/sickrage-issues#2271]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-43-generic-x86_64-with-elementary_OS-0.3-freya**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@067063484150e04202188b0b54b07a60a1fe4dc4
Link to Log: https://gist.github.com/f9871a763178bd4c5a36
### ERROR
```
SHOWQUEUE-ADD :: Error with theTVDB, not creating episode list: not enough arguments for format string
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by squareflapjack** [comment]
same as #2270 ?

**Comment by miigotu** [comment]
Same thing, will close the other one though because at least this one has a log.

**Comment by b225ccc** [comment]
A fix:

```
diff --git a/sickbeard/tv.py b/sickbeard/tv.py
index 7f48acf..44c04c0 100644
--- a/sickbeard/tv.py
+++ b/sickbeard/tv.py
@@ -1659,7 +1659,7 @@ class TVEpisode(object):
         if episode is None:
             episode = self.episode

-        logger.log(u"%s: Loading episode details from %s for episode S%02dE%02d" % (sickbeard.indexerApi(self.show.indexer).name, season, episode) , logger.DEBUG)
+        logger.log(u"%s: Loading episode details from %s for episode S%02dE%02d" % (self.show.indexerid, sickbeard.indexerApi(self.show.indexer).name, season, episode) , logger.DEBUG)

         indexer_lang = self.show.lang
```

**Comment by miigotu** [comment]
There were actually 3 broken log lines I found. Git pull.

**Comment by loucifer00** [comment]
I actually disabled sickbeard indexer and womblies with no effect btw.

**Comment by loucifer00** [comment]
and I’m a total n00b to all this, how do I implement the “fix”?

I’m on a mac osx btw.

**Comment by miigotu** [comment]
@loucifer00 what does SBI and womble have to do with this issue?

**Comment by miigotu** [comment]
@loucifer00 also what "fix" are you referring to?

**Comment by loucifer00** [comment]
b255ccc posted above, I’m going to bed...

thanks for the help!!!

**Comment by miigotu** [comment]
No need to apply any fix, it was committed to master before he posted that ^^

**Comment by miigotu** [comment]
Just cd into SR folder and `git reset --hard && git pull`
