### ISSUE TITLE
Failed doing webui request

### ISSUE THREAD

**Issue by bughatti** [SiCKRAGETV/sickrage-issues#2272]
SR Version:	BRANCH: (master) / COMMIT: (067063484150e04202188b0b54b07a60a1fe4dc4) 
SR User:	sickrage
SR Locale:	(None, None)
SR Config file:	/usr/local/sickrage/var/config.ini
SR Database file:	/usr/local/sickrage/var/sickbeard.db
SR Cache Dir:	/usr/local/sickrage/var/cache
SR Log Dir:	/usr/local/sickrage/var/Logs
SR Arguments:	['--daemon', '--pidfile', '/usr/local/sickrage/var/sickrage.pid', '--config', '/usr/local/sickrage/var/config.ini', '--datadir', '/usr/local/sickrage/var/']
Python Version:	2.7.10 (default, Jun 3 2015, 20:58:35) [GCC 4.6.4]

cur_commit_hash = 067063484150e04202188b0b54b07a60a1fe4dc4

DS414
CPU
MARVELL Armada XP MV78230
CPU clock rate
1.33 GHz
CPU cores
2
Total physical memory
1024 MB
DSM version
DSM 5.2-5592 Update 1
System time
2015-07-22 01:26:45

https://gist.github.com/bughatti/014d4816f367f7ffce22

Re installed sickrage this evening and above is the error I am getting now.

I have set debug to 1

I get the error when I try to setup Synology DS under torrent search.  I have also tried setting up transmission and it fails also

**Comment by miigotu** [comment]
```bash
cd YourSickRagefolder
git reset --hard
git pull
```

**Comment by bughatti** [comment]
B_Home_DS414> cd /volume1/@appstore/sickrage/
B_Home_DS414> dir
drwxr-xr-x    5 sickrage root          4096 Jul 22 01:06 .
drwxrwxrwx   20 root     root          4096 Jul 22 01:06 ..
drwxr-xr-x    3 sickrage root          4096 May 26 05:24 app
drwxr-xr-x    5 sickrage root          4096 Jul 22 01:06 env
drwxr-sr-x    5 sickrage root          4096 Jul 22 07:18 var
B_Home_DS414> git reset --hard
-ash: git: not found

**Comment by fernandog** [comment]
@neoatomic how to run git in nas?

**Comment by bughatti** [comment]
So I have git installed from synocommunity, but did not have it from synology official.  Once I installed synology official 2.3.5 I can now run git commands.

B_Home_DS414> git reset --hard
fatal: Not a git repository (or any parent up to mount point /volume1)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
B_Home_DS414>
B_Home_DS414> dir
drwxr-xr-x    6 sickrage root          4096 Jul 22 07:28 .
drwxrwxrwx   21 root     root          4096 Jul 22 07:24 ..
drwxr-xr-x    7 root     root          4096 Jul 22 07:28 .git
drwxr-xr-x    3 sickrage root          4096 May 26 05:24 app
drwxr-xr-x    5 sickrage root          4096 Jul 22 01:06 env
drwxr-sr-x    5 sickrage root          4096 Jul 22 07:19 var

B_Home_DS414> git init
Initialized empty Git repository in /volume1/@appstore/sickrage/.git/

B_Home_DS414> git reset --hard
B_Home_DS414> git pull
fatal: No remote repository specified.  Please, specify either a URL or a
remote name from which new revisions should be fetched.

What do I add to git pull

**Comment by fernandog** [comment]
you need to run this command INSIDE sickrage folder

**Comment by bughatti** [comment]
But I am in the sickrage folder, unless you mean in another way other than below


B_Home_DS414> cd /volume1/@appstore/sickrage/
B_Home_DS414> dir
drwxr-xr-x    6 sickrage root          4096 Jul 22 07:28 .
drwxrwxrwx   21 root     root          4096 Jul 22 07:24 ..
drwxr-xr-x    7 root     root          4096 Jul 22 07:28 .git
drwxr-xr-x    3 sickrage root          4096 May 26 05:24 app
drwxr-xr-x    5 sickrage root          4096 Jul 22 01:06 env
drwxr-sr-x    5 sickrage root          4096 Jul 22 07:19 var

**Comment by fernandog** [comment]
you need to run this in the same folder as sickbeard.db and SickBeard.py

**Comment by fernandog** [comment]
@neoatomic NAS has something different with folders?

**Comment by neoatomic** [comment]
Indeed the Git package from Synocommunity runs isolated from the root so can be tricky to run.
According to the forum this should work. But it might be better to just download the Sickrage zip and overwrite the old files if something is corrupt. U can use winSCP instead of command line.

```
If people ever got this issue:
SSH to your synology (enable ssh on your synology DS)
go to the sickrage folder /@appstore/sickrage/var/sickrage/ (can vary per person)
start command: git pull
if git can't be found: /usr/local/git/bin/git pull (if the git file is on the standard location)
```

**Comment by bughatti** [comment]
cd /volume1/@appstore/sickrage/var/SickRage/
git reset --hard
git pull

those worked, I am 3 commits behind now but my problem is solved

**Comment by fernandog** [comment]
@neoatomic thanks!
