### ISSUE TITLE
Ignored Words not working with multi episodes torrent

### ISSUE THREAD

**Issue by Grincheux41** [SiCKRAGETV/sickrage-issues#2274]
Hi,

I saw this issue : https://github.com/SiCKRAGETV/sickrage-issues/issues/1560
and it still happens.

exemple with my configuration :

![sans titre](https://cloud.githubusercontent.com/assets/8981964/8821195/2313bf96-305c-11e5-8b84-11c31f11e29f.png)

but in logs : 
2015-07-22 10:17:27 INFO     SEARCHQUEUE-MANUAL-248835 :: Downloading Once.Upon.A.Time.S04E22-E23.FiNAL.FASTSUB.VOSTFR.HDTV.XviD-ADDiCTiON from T411
2015-07-22 10:17:15 INFO     SEARCHQUEUE-MANUAL-248835 :: Performing episode search for Once Upon a Time
2015-07-22 10:17:02 INFO     SEARCHQUEUE-MANUAL-248835 :: [T411] :: Performing season pack search for Once Upon a Time

It seems that the problem occurs only for multi episodes torrent.

Hope I am clear.

Best regards.

**Comment by Grincheux41** [comment]
another precision : i am on version 4.0.39 (MASTER)

**Comment by miigotu** [comment]
@Grincheux41 This is an invalid report considering we have about 500 commits since v4.0.39.

Latest is v4.0.42

**Comment by Grincheux41** [comment]
Sorry, when I click on : "Check for update", it indicates to me "no update needed", and when I go to "changelog", I can see all changes until 4.0.39.

Where can I check my version please? there isn't this information in the footer, and that's a pity :)

**Comment by miigotu** [comment]
Changelog hasn't been updated, thats why we use commit hash from "Help & Info" menu item.

**Comment by Grincheux41** [comment]
thank you!

here it is!

SR Version:	BRANCH: (master) / COMMIT: (eb6f4d46709f4b3dd337c56573feb5bac27b10a9)

**Comment by miigotu** [comment]
So you are updated, now at least. Make sure there is no trailing space or comma on your ignored words list. They work here ^

**Comment by Grincheux41** [comment]
Ignore words : german,core2hd,dutch,swedish,reenc,MrLss,VOSTFR,vostfr
Require words : vf,french

There isn't any space.

I am pretty sure the problem ONLY happens on torrent with multi episode. 

For example, the sitcom "once upon a time" is available on my provider for every episode of season 4 but with "VOSTFR" in the name (which is a "ignored word" for me). And SickRage doesn't snatch any torrent... EXCEPT : the torrent Once.Upon.A.Time.S04E22-E23.FiNAL.FASTSUB.VOSTFR.HDTV.XviD-ADDiCTiON and Once.Upon.A.Time.S04E08-E09.FASTSUB.VOSTFR.HDTV.XviD-ADDiCTiON

I have the same behaviour with another sitcom (under the dome) for 1 torrent.

I am pretty sure there is a problem with torrents containing several episodes in one.

**Comment by miigotu** [comment]
Confirmed. There is no pickBestResult used in MULTI-EP results, will work on a fix tomorrow.

**Comment by miigotu** [comment]
Just so I remember my starting point tomorrow:
sickbeard/search.py:L604

**Comment by Grincheux41** [comment]
thanks a lot!

**Comment by miigotu** [comment]
This is a big find, thanks to you noticing it was only multi episode results.

It was only ruling out based on failed history, but not quality, ignored/required works, anime fansub/black/whitelist, badReleases etc.

It was also using getURL instead of headURL and not only wasting memory but also putting unnecessary strain on our providers.

`05:36:49 INFO::SEARCHQUEUE-MANUAL-248835 :: Ignoring Once.Upon.A.Time.S04E22-E23.FiNAL.FASTSUB.VOSTFR.HDTV.XviD-ADDiCTiON.avi[.D3K0.] based on ignored words filter: VOSTFR`

Works now.

**Comment by miigotu** [comment]
It is only in develop atm, so use develop or wait until merge to master.

**Comment by Grincheux41** [comment]
I am happy if I could help you to improve SickRage :)

I will wait for the merge, no problem. Thanks for your reactivity !

**Comment by adaur** [comment]
Funny that someone else reported this to me only a few days ago :)

https://github.com/adaur/SickRage/commit/c5d579af7d3476fd267b84c4639cbb51d450b34f#commitcomment-12236851

**Comment by Grincheux41** [comment]
did not see it when I looked for my problem! sorry :)

**Comment by adaur** [comment]
No, you were right to report it since he didn't
