### ISSUE TITLE
Shows getting set to unaired if not downloaded

### ISSUE THREAD

**Issue by boomertheweim** [SiCKRAGETV/sickrage-issues#2275]
So I had 3 shows queued last night, this morning they were set to unaired. I did a rescan and they are back as wanted.  Any suggestions?

**Comment by neoatomic** [comment]
@boomertheweim Follow the guidelines for posting an issue. : https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket

**Comment by neoatomic** [comment]
And check the news page in Sickrage. The part about Default Episode Status.
