### ISSUE TITLE
Updating: ZIP64 extensions required for large backup configs

### ISSUE THREAD

**Issue by gitowok** [SiCKRAGETV/sickrage-issues#2276]
Updating from web interface results in "Config backup failed, aborting"

From the log:
`2015-06-27 15:43:28 Thread-72 :: Zip creation error: Filesize would require ZIP64 extensions
2015-06-27 15:43:28 Thread-72 :: Config backup failed, aborting`

It appears I have some reasonably large sized sqlite databases for nzb providers in the rss directory under cache. Total size of that directory is 6.4GiB.

Is this database bloat something that sickrage should be cleaning up, or is it normal and required?
A simple fix would be simply enabling zip64 extensions.

More discussion [here](https://sickrage.tv/forums/forum/help-support/general-support/24316-updating-zip-creation-error-filesize-would-require-zip64-extensions)

**Comment by neoatomic** [comment]
Sound more like your installation got corrupt. Try to delete the cache folder and let it rebuild.

**Comment by gitowok** [comment]
Hi, will deleting this folder have any side effects, or will it seamlessly rebuild with no loss in data/search history etc.

**Comment by neoatomic** [comment]
@gitowok All important data is in the config.ini and sickbeard.db. The folder mainly contains cached information from searches, banners etc. You can also rename the folder to fake the delete, and replace it back if that didn't solve the problem.
But 6.5gb is an extremely large seize, and i cant imagine that SickRage would even run good/fast with that large of cache.

Also have you changed the code line like @miigotu asked in the forum?

On a site node, as you have 500 shows in your list could you do me a favor.? Can you check if there are any network logos missing.? And if so what the exact name is.?

**Comment by gitowok** [comment]
Hi, thanks for the detailed reply.

I've deleted cache/rss folder as that seems to be where the problem is, and restarted. I'll monitor it over the next few hours/days and see if the databases are growing incrementally in size again, which I assume could highlight some sort of garbage collection bug as the underlying issue here.

Re patching to enable 64bit extensions, as @miigotu has suggested - did you want me to test that? i'm reasonably confident it would allow web update to work - of course only one time - the update itself will clobber the change locally. It also wouldn't help identify the underlying issue with the database files getting really big (one in particular - oznzb.db was over 4GiB). Let me know if you want me to test the patch anyhow.

Re network logos missing, just a handful (with showname):
"MTV (UK)"  (Geordie Shore)
"LifeStyle"  (Grand Designs Australia)
"Kanal 5" (Heartless)
"Prime (NZ)"  (Killing Time)
"Logo"  (Rupauls Drag Race - http://thetvdb.com/?tab=series&id=85002)
"No Network"  (This is Littleton - http://thetvdb.com/?tab=series&id=278735)
"No Network" (Total Drama Pahkitew Island - http://thetvdb.com/?tab=series&id=283127)

Hope that helps

**Comment by neoatomic** [comment]
@gitowok No, leave the patch alone for now. Just needed to know if you had changed the line.
I think the oznzb had trotted/blocked SickRage searches, so it might be responseble for sending the garbage to your cache. If you still have the issue try to disable that provider.

And thanks for checking the network logos. Will try to fix those for you. :)

**Comment by gitowok** [comment]
Cool, no probs.

I would posit though that breakage caused by a provider's data, junk or not (or lack of) is a bug in sickrage that needs some further investigation.

I have backups of said db if anyone now or in the future wants to take a look.  

Also, as you can see from my forum directory listing post, this is not an issue isolated to one provider. sickbeard index and nzb.su look to be problemattic as well.

Regards

**Comment by neoatomic** [comment]
Sickbeard index you can remove, that isnt working anymore. As for nzb.su i cant tell. The problem is that those are closed providers and without invite/account we cant even test those...

**Comment by fernandog** [comment]
already fixed the zip error. wait merge into master

**Comment by miigotu** [comment]
It is already in master =P
