### ISSUE TITLE
Issue checking for updates after updating

### ISSUE THREAD

**Issue by add1ct3dd** [SiCKRAGETV/sickrage-issues#2277]
Here's the logs: 
```
2015-07-22 11:32:43 CHECKVERSION :: git fetch origin returned : error: unable to resolve reference refs/remotes/origin/develop: No such file or directory
From https://github.com/SiCKRAGETV/SickRage
 ! [new branch]      develop    -> origin/develop  (unable to update local ref)
2015-07-22 11:32:43 CHECKVERSION :: Unable to contact github, can't check for update
```

Using python2.7 on windows, everything was fine until it last updated, and now I get this error every time. I've ran both the "update fix" commands shown on the readme in this repo, neither helped sadly. (so I'm also using master branch).

**Comment by tchirou** [comment]
Same problem here on Win8/ master/ Pyhton 2.7.6
I shutdown, laucnhed a git checkout master and a git pull and the update came through

**Comment by neoatomic** [comment]
@add1ct3dd @tchirou Could you check your logs and search for `cur_commit = ` ? That shows the commit version from which you have updated. That will allow us to narrow down the commit that is causing this. It should look like this. : 

```
2015-07-22 11:27:22 DEBUG    Thread-34 :: cur_commit = 2d8a4643732d9591013c623b96c12ac1b0a29d84, newest_commit = 085fa35805f46388f4e7c8c2d137fcb50dba4d29, num_commits_behind = 27, num_commits_ahead = 0
```

**Comment by add1ct3dd** [comment]
I've just enabled debug and restarted, can't find cur_commit in any of the log - is there anything else I need to do to get that to show?

**Comment by neoatomic** [comment]
@add1ct3dd Have you try'd the sickrage.log file instead of the GUI.?

**Comment by add1ct3dd** [comment]
Yep that's the one I'm looking at :(

**Comment by tchirou** [comment]
Sorry I just have 5 logs with 1MB and the oldest one starts after the
successful git pull so I can't tell you



Le 22 juil. 2015 à 12:51, neoatomic <notifications@github.com> a écrit :

@add1ct3dd <https://github.com/add1ct3dd> @tchirou
<https://github.com/tchirou> Could you check your logs and search for
cur_commit
= ? That shows the commit version from which you have updated. That will
allow us to narrow down the commit that is causing this. It should look
like this. :

2015-07-22 11:27:22 DEBUG    Thread-34 :: cur_commit =
2d8a4643732d9591013c623b96c12ac1b0a29d84, newest_commit =
085fa35805f46388f4e7c8c2d137fcb50dba4d29, num_commits_behind = 27,
num_commits_ahead = 0

—
Reply to this email directly or view it on GitHub
<https://github.com/SiCKRAGETV/sickrage-issues/issues/2277#issuecomment-123662895>
.

**Comment by fernandog** [comment]
without logs there's nothing we can do.
please increase the number of logs and/or log size

**Comment by fernandog** [comment]
also you got "Unable to contact github, can't check for update"

github issue

**Comment by add1ct3dd** [comment]
That's after the previous error though, so is not a github issue.

 git fetch origin returned : error: unable to resolve reference refs/remotes/origin/develop: No such file or directory
From https://github.com/SiCKRAGETV/SickRage

Is the actual error.

**Comment by fernandog** [comment]
stop SR, rename your sickrage folder to sickrage-backup
run git clone ......... again
copy your config.ini, *.db, cache folder into this new SR folder
start SR

**Comment by add1ct3dd** [comment]
thanks, that fixed it :)

**Comment by jcharlier** [comment]
I've had this issue installing sickrage via AtoMiC-ToolKit. 
It runs git as root and then the webserver doesn't have permissions to change the git files.
Changing the permissions of the files solved the problem for me.

**Comment by add1ct3dd** [comment]
Not the same issue, this was on Windows with an administrator user :)

**Comment by jcharlier** [comment]
Oops! You're right, I didn't notice that.
