### ISSUE TITLE
[APP SUBMITTED]: Thread-74 :: No git specified, can't use git commands

### ISSUE THREAD

**Issue by ragmannl** [SiCKRAGETV/sickrage-issues#2278]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-4.1.1+-armv7l-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@f9246bcfdb95929e95e5f422d577fc9aa7d69953
Link to Log: https://gist.github.com/f1119f4c50d6e68f5178
### ERROR
```
Thread-74 :: No git specified, can't use git commands
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Have you checked your GIT installation.?
