### ISSUE TITLE
Feature request: allow setting torrents as a backup when Usenet fails or cannot be found.

### ISSUE THREAD

**Issue by psyciknz** [SiCKRAGETV/sickrage-issues#228]
The ability to set torrents as a backup for Usenet.

When Usenet fails then the torrent can be searched.
Or if after x days if not found with a. Usenet provider, then the torrents could be checked.

**Comment by timrettop** [comment]
+1

**Comment by twayz** [comment]
+1

**Comment by neoatomic** [comment]
You can set the order of providers already in the search providers list. Just enable them and drag/drop the providers in the order you like. ( So in your case start with NZB providers and end with torrent providers.)
Its already there. :P

**Comment by bthusby** [comment]
Yeah you kind of right... But still Torrents should have a timer to move on to the next torrent provider, or even better the next best torrent anywhere (i.e. also with the same provider if found best). Clean up, blacklist, and delete all partials from the attempt. Right now a torrent can stall for ever....

**Comment by neoatomic** [comment]
Well no point in requesting a feature that is already there. :) 
So this issue can be closed. @markheloking

The problem you are describing is something different, thats failed download handling of torrents.
I actually did a suggestion some time back to implement a simple timer for snatched files. You can read-up here. : 
https://github.com/SiCKRAGETV/sickrage-issues/issues/225

**Comment by psyciknz** [comment]
Wouldn't a priority be more for the torrents show up first, and the usenet might be a day or so later.  Simply changing the order of the provider will not work.

**Comment by neoatomic** [comment]
If you start with NZB providers and finish with Torrent providers than that is the order SickRage will search.
In addition you can try to use NZB providers for daily searches, and Torrent providers for backlog searches. And change the time between searches. 
Lots of options to accomplish this.

**Comment by fernandog** [comment]
@neoatomic good idea

**Comment by psyciknz** [comment]
So I tried @neoatomic's idea.  Had Daily search set to 120 and backlog set to 1800, providers are set with NZB at the top and Torrents below - with all torrents set to backlog only.  backlog on startup is off (server was restarted overnight).

So a new show started last night...machine start at about 5am and I can see a backlog search started at 5:55 (not 1800 minutes), in fact for the new show there is no daily search (since it wont find it anyway as stuff turns up the day after for me - show airing 5 Jan - will appear 6 Jan for me).

And the show was found by torrent

**Comment by markheloking** [comment]
So there's a problem that it's not using the backlog timer as it's supposed to?

**Comment by psyciknz** [comment]
It did seem to be.

Also what happens if an episode is snatched via torrent - the next daily search will that episode not be searched for? As its already snatched?

**Comment by fernandog** [comment]
@psyciknz depends on your Initial and Quality settings.
Read here https://github.com/SiCKRAGETV/SickRage/wiki/Quality-Settings
