### ISSUE TITLE
[Feature Request] HTTP proxy support for IRC KiwiIRC client

### ISSUE THREAD

**Issue by forkless** [SiCKRAGETV/sickrage-issues#2280]
Have to use browser HTTP proxy now, would be nice if there was an option to set the HTTP proxy for the IRC client in the interface.

**Comment by fernandog** [comment]
@forkless do you have global proxy enabled? do you want this proxy to be used there?

**Comment by forkless** [comment]
I have the global browser HTTP proxy enabled right now. However I would prefer to enable it on application level.

**Comment by miigotu** [comment]
It doesn't make sense to use a proxy for https connections.

**Comment by miigotu** [comment]
Proxies are not for anonymity, they are to get around blocks/bans. The provide no personal security.

**Comment by forkless** [comment]
That's exactly what proxies are for. To provide anonymity. There are instances where people want to prevent their reverse IP lookup from being exposed. This doesn't mean they can not be blocked/banned. 

I could request a cloak at Freenode but that requires services to be up and even with that the IP is not safeguarded and as you may know Tor/SASL services are blocked (for good reason).

Entering an IRC lobby with a reverse IP lookup that points to a (home run) SMTP/HTTP server for instance makes one a prime target for script kiddies and other forms of low-life to have a field day.

Yes, I realise I can use (and am using) a global proxy setting to work around the current shortcoming but it has its drawbacks (stale static content). 


PS. Don't get me wrong I get the abuse concern you may have, but adding an application level proxy support does not make one iota difference for the  administration of your IRC channel. Every browser already has a proxy option, I'm just asking to make it more granular.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
