### ISSUE TITLE
[APP SUBMITTED]: requests>=2.0.1

### ISSUE THREAD

**Issue by KoenDeMol** [SiCKRAGETV/sickrage-issues#2282]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 10:19:51) [GCC 4.3.6]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@eb6f4d46709f4b3dd337c56573feb5bac27b10a9
Link to Log: https://gist.github.com/0fb9e1c0d5e18c6a62f4
### ERROR
```
Thread-52 :: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/sickbeard/tv.py", line 1463, in downloadSubtitles
    foundSubs = subliminal.download_best_subtitles([video], languages=languages, providers=providers, single=not sickbeard.SUBTITLES_MULTI, hearing_impaired=False)
  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/lib/subliminal/api.py", line 74, in download_best_subtitles
    with ProviderPool(providers, provider_configs) as pp:
  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/lib/subliminal/providers/__init__.py", line 241, in __init__
    self.providers = dict([(p, provider_manager[p]) for p in (providers or provider_manager.available_providers)])
  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/lib/subliminal/providers/__init__.py", line 180, in __getitem__
    self.providers[ep.name] = ep.load()
  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/lib/pkg_resources.py", line 1953, in load
    if require: self.require(env, installer)
  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/lib/pkg_resources.py", line 1966, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/lib/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
DistributionNotFound: requests>=2.0.1

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by KoenDeMol** [comment]
Subtitle downloading was working before. Noticed today that since a while it 's not working anymore. Don't know how long ...

**Comment by miigotu** [comment]
Something wrong with that install, requests is in the lib folder at v2.6.0.
Try to back up, remove the package, reinstall the package, boot it and restore the backup.

**Comment by miigotu** [comment]
@KoenDeMol can you try something for me?

Someone changed my sys.path.insert again, 
Stop SR, open SickBeard.py, line 33
Try changing it from:
sys.path.insert(1, os.path.abspath(os.path.join(os.path.dirname(__file__), 'lib')))
to:
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), 'lib')))

save and start SR and try to reproduce the error.

**Comment by KoenDeMol** [comment]
Did that, same error though :(

The requests package can indeed be found in de lib folder...

**Comment by miigotu** [comment]
This is something about prefix or qnap and python path. I'm not sure how the caching/pathing works on QNAP.

Maybe need to export the python_path before running SR, with the path to the lib folder prepended.

export PYTHONPATH=/path/to/lib:$PYTHONPATH

**Comment by miigotu** [comment]
I'm really not sure how the drives and mounts are laid out on QNAP.
Why is it `/share/CACHEDEV1_DATA/.qpkg` and not `/share/HDA_DATA/.qpkg` or similar?

**Comment by KoenDeMol** [comment]
They do have some weird things, the QNap guys, but this one is actually ok .. the /share/CACHEDEV1_DATA is the first RAID volume (on which the system is installed) en /share/HDA_DATAx are the physical disks ...

I will try to export the python path as soon as my QNap rebooted (accidently pressed enter to quickly messing up the existing PYTHONPATH, so just to make sure I got everything right rebooting now ..)

**Comment by miigotu** [comment]
Ok I read up a bit, v2 share manager changed the mount points.

You are running SR from /share/.qpkg or /share/CACHEDEV1_DATA/.qpkg ?

**Comment by miigotu** [comment]
http://forum.qnap.com/viewtopic.php?f=11&t=88351#p394044

**Comment by KoenDeMol** [comment]
from /share/CACHEDEV1_DATA/.qpkg/SickRage

**Comment by miigotu** [comment]
To be honest, this pathing issue may also be a cause of the ssl problems on qnap, and why some people do not have the ssl problems.

**Comment by KoenDeMol** [comment]
about that forum link: the /share/FOLDER is only existing for shares that are actually configured (for example /share/downloads is a symlink to /share/CAHCEDEV1_DATA/downloads

But there is none for the .qpkg folder, so /share/.qpkg is not existing ..

Mine just rebooted, I will give it a try.  If this could also be the SSL problem, that would be a nice found ;-).  I 'm not sure though, because even wget-ing on SSL is not working :-s

**Comment by miigotu** [comment]
Tell me the contents of $PYTHONPATH after a reboot too, and If you can start SR from command line, add a line in SickBeard.py on line 34:
`print sys.path` and start it from command line and show what the path is then.

**Comment by miigotu** [comment]
Yes wget and curl don't work on qnap for SSL, but they both use environment variables to find system libs in order to work properly ^^

**Comment by neoatomic** [comment]
According to this doc there are 2 different paths for single and raid setups.

```
At installation a directory structure is created at the default QPKG location, which depends on whether it is
installed on a RAID volume or a single drive. The exact location is available in the
QDK_PATH
variable in the
system-wide configuration file, 
/etc/config/qdk.conf
, but it is usually 
/share/MD0_DATA/.qpkg/QDK
 on a
RAID system and 
/share/HDA_DATA/.qpkg/QDK
 on a single drive system.
``` 
http://download.qnap.com/dev/QDK_2.0.pdf

**Comment by miigotu** [comment]
@neoatomic Newer versions of qnap changed the mount layout.

http://forum.qnap.com/viewtopic.php?f=11&t=88351

**Comment by miigotu** [comment]
I would be interested in seeing `/etc/config/qdk.conf`

**Comment by KoenDeMol** [comment]
euhm ... $PYTHONPATH is empty after reboot .. hmmmm ...

I did the export, still same error.  Starting SR from command line, this is the output of sys.path:

['/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/lib', '/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage', '/share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages/setuptools-15.2-py2.7.egg', '/share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages/pip-6.1.1-py2.7.egg', '/share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages/logilab_astng-0.24.3-py2.7.egg', '/share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages/google_api_python_client-1.2-py2.7.egg', '/share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages/python_ldap-2.4.19-py2.7-linux-i686.egg', '/share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages/MySQL_python-1.2.5-py2.7-linux-i686.egg', '/share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages/kerberos-1.2.2-py2.7-linux-i686.egg', '/share/CACHEDEV1_DATA/.qpkg/QPython2/lib', '/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage', '/share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python27.zip', '/share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7', '/share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/plat-linux2', '/share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/lib-tk', '/share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/lib-old', '/share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/lib-dynload', '/share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages', '/share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages/PIL', '/share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages/newrelic-2.50.0.39']

**Comment by miigotu** [comment]
I can't believe noone has compiled cryptography for qnap properly yet =P `ipkg install gcc` unpack the headers, install cryptography with pip... lol


Anyways, that pathing is right for `sys.path.insert(0`

Checked permissions on lib folder and it's contents?

**Comment by miigotu** [comment]
Actually, why double SickRage?
`'/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage', `

**Comment by neoatomic** [comment]
Suspect they have in the first folder the installation/configuration files for the qnap (package). And the sub folder the actual SickRage files.?

**Comment by KoenDeMol** [comment]
I don't seem to have qdk.conf file ... What are you looking for in there?

Don't know why double SickRage, happened automatically during install.  But looking more deeply I see this is the same for all packages installed. In the first folder there is the shell-script to start/stop (and some other files), the package itself is installed one level deeper ..

**Comment by miigotu** [comment]
Where can I get a copy of this qpkg to look at?

**Comment by neoatomic** [comment]
Is there a /etc/config/sickrage.conf file.?

**Comment by KoenDeMol** [comment]
I tried to compile cryptography for QNap a while ago, but got stuck somewhere after trying things for over an hour. Then I found this distribution of QPythong (which is ridiculously large, but does the trick) ..

**Comment by neoatomic** [comment]
http://www.tweaking4all.nl/download/qnap/SickRage.qpkg

**Comment by KoenDeMol** [comment]
Going to eat something now, but if you like I can give you access to my QNap after ... no secrets there ;)

**Comment by miigotu** [comment]
=P, might be a healthy learning experience

**Comment by miigotu** [comment]
@KoenDeMol Did you get SR qpkg from here? http://apps.qnap.community/11-community/17-qsickrage

**Comment by KoenDeMol** [comment]
No, I can't find the forum anymore where I found the link, but it's v150505 by Stephane Guerithault.

@miigotu : I will give you access to my QNap. Will send you an e-mail ..

**Comment by miigotu** [comment]
@KoenDeMol that link I pasted is by v150708 by Stephane Guerithault. Updated 7 days ago

**Comment by miigotu** [comment]
If you still want to give me access, I'll take a look, or you can try the newer package first

**Comment by KoenDeMol** [comment]
Just sent you an e-mail with the details. You can look around there before I try the newer package.  In favour of the "healthy learning experience" ;-)

**Comment by miigotu** [comment]
Strangeness...

QPython2 has even it's own requests version installed (2.6.2)

**Comment by miigotu** [comment]
@KoenDeMol I'm in IRC if you want to talk while I play on your qnap.

**Comment by KoenDeMol** [comment]
Just send a message through mIRC to miigotu (guessing that is you?) ...

**Comment by KoenDeMol** [comment]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 10:19:51) [GCC 4.3.6]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@eb6f4d46709f4b3dd337c56573feb5bac27b10a9
Link to Log: https://gist.github.com/5a721b868edfaed6da04
### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/sickbeard/tv.py", line 1463, in downloadSubtitles
    foundSubs = subliminal.download_best_subtitles([video], languages=languages, providers=providers, single=not sickbeard.SUBTITLES_MULTI, hearing_impaired=False)
  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/lib/subliminal/api.py", line 74, in download_best_subtitles
    with ProviderPool(providers, provider_configs) as pp:
  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/lib/subliminal/providers/__init__.py", line 241, in __init__
    self.providers = dict([(p, provider_manager[p]) for p in (providers or provider_manager.available_providers)])
  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/lib/subliminal/providers/__init__.py", line 180, in __getitem__
    self.providers[ep.name] = ep.load()
  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/lib/pkg_resources.py", line 1953, in load
  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/lib/pkg_resources.py", line 1966, in require
  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/lib/pkg_resources.py", line 565, in resolve
DistributionNotFound: requests>=2.0.1

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by tvann2182** [comment]
I found the link you are looking for it can be found here

http://forum.qnap.com/viewtopic.php?f=320&t=109899&p=479958&sid=dcca4abf73b8a874db7ffa02225118fe
