### ISSUE TITLE
Show updater locking again

### ISSUE THREAD

**Issue by scythe000** [SiCKRAGETV/sickrage-issues#2283]
I learned from the last couple of times I opened this issue, and deleted the contents of the cache\sessions folder. No luck.

It freezes each time on the Bob's Burgers show update.

**Comment by fernandog** [comment]
as always and you know: https://github.com/SiCKRAGETV/sickrage-issues/

**Comment by scythe000** [comment]
SR Version: 	BRANCH: (master) / COMMIT: (eb6f4d46709f4b3dd337c56573feb5bac27b10a9)
SR User:	Administrator
SR Locale:	('en_US', 'cp1252')
SR Config file:	C:\SickRage\config.ini
SR Database file:	C:\SickRage\sickbeard.db
SR Cache Dir:	C:\SickRage\cache
SR Log Dir:	C:\SickRage\Logs
SR Arguments:	[]
Python Version:	2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]

**Comment by scythe000** [comment]
Os is Windows Server 2012 R2 Standard

**Comment by fernandog** [comment]
What is the most important thing??

**Comment by scythe000** [comment]
Oh, I did the git commands! :-)

**Comment by scythe000** [comment]
Sorry :-)

**Comment by fernandog** [comment]
LOGS!! full logs with debug enabled

**Comment by scythe000** [comment]
Agh!

**Comment by scythe000** [comment]
Here's the logs:
https://codeshare.io/xhv0o

**Comment by fernandog** [comment]
@scythe000 please upload in gist.

**Comment by scythe000** [comment]
https://gist.github.com/scythe000/774d536cb5017e3cc7f3

**Comment by fernandog** [comment]
@scythe000 don't look stucked. why do you say that?

**Comment by scythe000** [comment]
If I go to server status, the show queue stops at the same point and stays there indefinitely.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/commit/bc33ae41d114e8f4a54c0ef960a3b8d155b8079d

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/commit/5cf81621bfc26e0c7c19aec5bfe3b5b9e2302057

**Comment by fernandog** [comment]
@scythe000 
disable PP, subtitles search and everything else
use develop branch
stop SR, erase SickRage/Logs
start SR
try to reproduce error
post full logs

**Comment by scythe000** [comment]
Will do. I think I can do all this tonight.

**Comment by fernandog** [comment]
from logs last debug log message is 

"Loading all episodes from the database"
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/show_queue.py#L559

then it calls def loadEpisodesFromDB(self):
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/tv.py#L475

and in your log there's no more log messages
we should at least get:
            logger.log(u"Loading episode S%02dE%02d from the DB" % (curSeason, curEpisode), logger.DEBUG)

@scythe000 try with all threads disabled as I asked you. Let's see what's happening. maybe the other threads are making show update wait everything else to finishe

**Comment by scythe000** [comment]
New logs:
https://gist.github.com/scythe000/ac514d531dc55127117e

**Comment by scythe000** [comment]
How do I disable the other threads?

**Comment by fernandog** [comment]
disable PP and subtitle search as I asked you

**Comment by scythe000** [comment]
Sorry, is there a checkbpx to uncheck or something? I didn't see where to do it.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/commit/b904ceddf4d38532b29c7c591c4a7807ef82da41

**Comment by fernandog** [comment]
@scythe000 please update and try again


disable subtitle download http://localhost:8081/config/subtitles/

**Comment by fernandog** [comment]
@scythe000 still waiting

**Comment by scythe000** [comment]
Sorry, got slammed. Here: https://gist.github.com/scythe000/6e2eb7a57720535529b0
Looks like the same deal.

**Comment by fernandog** [comment]
I see no Burgers in log.

**Comment by scythe000** [comment]
It stops right before it, then.

Sent from my iPhone

On Jul 24, 2015, at 11:43 PM, Fernando <notifications@github.com<mailto:notifications@github.com>> wrote:


I see no Burgers in log.

**Comment by fernandog** [comment]
Need lost from "updating Burges" until 10min later.
No PP enable. No subtitle download enable.

**Comment by scythe000** [comment]
ok, it made two logs:
1st log:
https://gist.github.com/scythe000/80e7db4c11a23a5f0e86
2nd log:
https://gist.github.com/scythe000/648e5e0ef793c7705aa8

**Comment by scythe000** [comment]
just ran an update, and things are weird...the queue is totally empty immediately after restart.

**Comment by scythe000** [comment]
I added a show (Dark Matter) and it doesn't seem to be fetching any metadata.

**Comment by scythe000** [comment]
Restart fixed that after a few, but my show queue is still hanging.

**Comment by scythe000** [comment]
Well, I figured out how to fix the issue! I renamed cache folder to cache-old. I'm missing shows as far back as 6/26 :-/.

**Comment by scythe000** [comment]
@abeloin had given this tip on #1043 which helped. Any thoughts, @fernandog ?

**Comment by scythe000** [comment]
I kept clearing out just the sessions folder, but that wasn't enough.

**Comment by miigotu** [comment]
Its not just the sessions folder you need to clear. Its cache/indexers and cache/sessions for indexer lock, provider lock its also cache/RSS and cache.db.

From now on just stop SR properly and you won't have this issue.

**Comment by scythe000** [comment]
If selecting "shut down" from the sickrage menu is not shutting it down properly, please educate me.

Sent from my iPhone

On Aug 11, 2015, at 9:56 PM, miigotu <notifications@github.com<mailto:notifications@github.com>> wrote:


Its not just the sessions folder you need to clear. Its cache/indexers and cache/sessions for indexer lock, provider lock its also cache/RSS and cache.db.

From now on just stop SR properly and you won't have this issue.

**Comment by miigotu** [comment]
Perhaps power went out or pc crashed at some point?

**Comment by scythe000** [comment]
Ah, yeah I think there may have been a power outage during that time. I would think there might need to be some code added to check for leftover files from an improperly shut down instance.

Sent from my iPhone

On Aug 11, 2015, at 10:30 PM, miigotu <notifications@github.com<mailto:notifications@github.com>> wrote:


Perhaps power went out or pc crashed at some point?

**Comment by miigotu** [comment]
maybe a "clear cache" link/routine from the webui. Problem is we don't want users doing this when they dont need to, because it puts unnecessary strain on indexers and providers.

**Comment by scythe000** [comment]
Would it not be possible for there to be some sort of an auto check to see if an improper shutdown happened and then do an auto remediation? I don't know if those files and folders truly need to be deleted, or just repaired in some way.

Sent from my iPhone

On Aug 11, 2015, at 10:39 PM, miigotu <notifications@github.com<mailto:notifications@github.com>> wrote:


maybe a "clear cache" link/routine from the webui. Problem is we don't want users doing this when they dont need to, because it puts unnecessary strain on indexers and providers.

**Comment by WebSpider** [comment]
We could place a state file, to keep track, but like @miigotu said, if the cache gets cleared too easily, SickRage will start bothering indexers and providers with search questions, which could easily cause your IP to get rate-limited or banned for bad behaviour.

Careful, we need to be.
