### ISSUE TITLE
Cant run Sickbeard, Error (possibly after recent automatic update).

### ISSUE THREAD

**Issue by syrys** [SiCKRAGETV/sickrage-issues#2284]
Sickrage worked fine for me for the last few months or so, but since yesterday, it has been failing to load. 
This is the guide i used to follow to install it few months back: http://www.htpcguides.com/install-sickrage-windows-usenet-torrent-tv/

Im assuming one of the recent (automatic) updates broke it (last day or two)? If so, im unsure how to check what version its in, and how to roll back. Hopefully there is a way to back up my data (im assuming sickrage backs up automatically when updating).

Can someone help and guide me on how to fix this?

Error is below.

Python Version: 2.7.9
Operating System: Windows 8.1

````
> python c:\SickRage\SickBeard.py
````

````
Traceback (most recent call last):
  File "c:\SickRage\SickBeard.py", line 577, in <module>
    SickRage().start()
  File "c:\SickRage\SickBeard.py", line 346, in start
    self.fix_clients_nonsense()
TypeError: fix_clients_nonsense() takes no arguments (1 given)
````

**Comment by raymondtrueman** [comment]
Just to make sure you have a backup of your data look for the following 4 files in your root SickRage directory:
failed.db, sickbeard.db, cache.db, config.ini

Copy them somwhere else for safe keeping while you try and sort out this problem.

I would suggest re-installing SickRage from scratch and then copy (and overwrite) the above 4 files
back into your fresh install. If all goes well you should have a ll your data and config back with a working SickRage

**Comment by fernandog** [comment]
@syrys or enter SickRage folder and SSH and run "git pull"

otherwise not linux does as above

**Comment by hpbrad** [comment]
same issue for me  on windows 7 though
after auto update the web ui stuck on waiting for sickrage to restart  after a while i just killed the process and serve and restarted it but the web ui wont load
will try reinstalling if that worked for syrys

**Comment by syrys** [comment]
Files backed up. 
@fernandog did the git pull, and restarted, and this seem to have fixed the issue. Didn't need to use the backed up files at all. Im saying it fixed the issue at first glance since Sickrage ran just fine and the webUI loaded up with all my shows etc. Will update if there are any other issue.

@hpbrad, try what i did. backup the files mentioned earlier, heck backup the entire folder (thats what i did), then go a git pull on the Sickrage folder, then try start up sickrage.

Thanks for all the help guys :)

**Comment by raymondtrueman** [comment]
@hpbrad Hmm, it may have been busy updating still when you interrupted it and something went corrupt. Try a git pull or reinstall

**Comment by hpbrad** [comment]
gonna try the git pull... can anyone share the exact steps im still a little noob to the whole github stuff but ive got python 2.7.9 all setup (obvi)

thanks

**Comment by hpbrad** [comment]
nevermind figured it out  almost too easy lol

worked like a charm
