### ISSUE TITLE
[APP SUBMITTED]: No module named generic

### ISSUE THREAD

**Issue by larryd85** [SiCKRAGETV/sickrage-issues#2286]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@eb6f4d46709f4b3dd337c56573feb5bac27b10a9
Link to Log: https://gist.github.com/e76c9259ce2a6c1b1fc2
### ERROR
```
Thread-109 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 814, in testTorrent
    client = clients.getClientIstance(torrent_method)
  File "C:\SickRage\sickbeard\clients\__init__.py", line 118, in getClientIstance
    module = getClientModule(name)
  File "C:\SickRage\sickbeard\clients\__init__.py", line 114, in getClientModule
    return __import__(prefix + name + '_client', fromlist=__all__)
  File "C:\SickRage\sickbeard\clients\utorrent_client.py", line 23, in <module>
    from .generic import GenericClient
ImportError: No module named generic

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
See if this fixes the error. : 
https://github.com/SiCKRAGETV/sickrage-issues/issues/2247#issuecomment-123275228

**Comment by larryd85** [comment]
i backed up my config, deleted those files. SR wouldnt start back up for me and git pull wouldnt work either.... i just deleted the sickrage folder and re-installed it. restored my settings and im good to go now. its working.

thanks for a quick response.
