### ISSUE TITLE
No daily search, ep's stay skipped and are not shown in coming ep's

### ISSUE THREAD

**Issue by udochrist** [SiCKRAGETV/sickrage-issues#2288]
Daily search is again not working for me. Eps are not set to wanted but stay in skipped after they have reached their airdate. 

Coming ep menu does not show the eps (presumably because they are skipped).

To manually find all missing downloads takes a lot of searching and clicking in the gui. To support this I think it would be better if the "coming eps" show all current (with airdate in the last 7days) and "not downloaded" eps instead of the "wanted" ones. 

SR Version:	BRANCH: (master) / COMMIT: (eb6f4d46709f4b3dd337c56573feb5bac27b10a9)

**Comment by miigotu** [comment]
You need to edit your shows and set default episode status to wanted. Have you read the news tab?

**Comment by udochrist** [comment]
Can this be edited by batch? I don't want to change >100 shows individually.

**Comment by miigotu** [comment]
@udochrist 
manage->mass edit
check the box to select all shows in the top left corner of the table
scroll down and click edit
set default episode status
click submit
