### ISSUE TITLE
New aired shows marked as skipped

### ISSUE THREAD

**Issue by Koal4** [SiCKRAGETV/sickrage-issues#2290]
For the 2nd day in a row I noticed that SR hasn't downloaded any new shows that where released this night. When I check those shows / eps in SR I see that SR somehow marked them as skipped. No clue why it's doing that but all I can say is that before this week it was working fine. So I suspect that one of the latest updates is causing this issue.

The name of the shows that I had this issue are extant and mr robot

debug log: https://gist.github.com/Koal4/93248240f0d999a1d2c6

oh and a little feature request: Please make an option so we can download the complete debug log from the UI

**Comment by Mul-tiMedia** [comment]
Same problem here, and i cant find whats the reason for this!

**Comment by neoatomic** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored
