### ISSUE TITLE
Renaming Pattern Problem

### ISSUE THREAD

**Issue by tabouzeid** [SiCKRAGETV/sickrage-issues#2293]
Hey All, I've been trying to put in a custom naming pattern for my anime but when i try to put in %E it keels over and dies (i.e. a whole lot of html appears in the preview box) and %e is in the list of approved values

**Comment by neoatomic** [comment]
Please follow the guidelines for posting an issue. : https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket

**Comment by tabouzeid** [comment]
Branch - master
Commit hash - 0308a49dcb9bf9bef03ec49a897a8373b399398c
Your operating system and python version - BusyBox v1.6, Python - 2.7.10
What you did - Config -> Post Processing -> Episode Naming -> Custom Anime (checkbox) -> Custom Name Pattern Dropdown entry -> set value to "%SN - %E - %EN"
What happened - Huge html block in the example section beneath it
What you expected - the formatted example for the pattern i provided
Link to a copy/paste of your logfile with clear debug info of the error on GIST: https://gist.github.com/tabouzeid/53fabaedef2bf3aa9ecb

**Comment by neoatomic** [comment]
@tabouzeid I dont use anime myself what i get from the log is that the release group 'pre_sep' doesn't exist. Or is the %E information missing on the indexer for that show.?

**Comment by tabouzeid** [comment]
there isn't a release group called pre_sep, and as for the %E information... this is on the configuration page, it's not referring to an actual episode so there's no information to reference which could be missing, it is generating an example of what it would look like from a template, as far as i can see. Also the episode numbers are all there and the absolute episode numbers are there as well, they are displayed on the show page and they are applied when i renamed them using %0E so i'm not sure what's hapenning there.

**Comment by tabouzeid** [comment]
any updates for this?

**Comment by neoatomic** [comment]
@miigotu You know anything about the renaming schemes for Anime.? As i dont know anything about those...

**Comment by miigotu** [comment]
Many anime do not have episode number mapped, only absolute number.
