### ISSUE TITLE
Scan doesn't recognize eps that it renamed before

### ISSUE THREAD

**Issue by tabouzeid** [SiCKRAGETV/sickrage-issues#2294]
i renamed some episodes using %0E which gave ep numbers like 001, 002 etc. which is what i want. but then i had to delete and re-add a series and it couldn't properly match the files to their proper counterpart. So i tried to remove one of the 0's and it worked... i think that might be a bug (btw, i'm using absolute numbers)

**Comment by neoatomic** [comment]
Please follow the guidelines for posting an issue. : https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket

**Comment by tabouzeid** [comment]
Branch - master
Commit hash - 0308a49dcb9bf9bef03ec49a897a8373b399398c
Your operating system and python version - BusyBox v1.6, Python - 2.7.10
What you did - Config -> Post Processing -> Episode Naming -> Custom Anime (checkbox) -> Custom Name Pattern Dropdown entry -> set value to "%SN - %E - %EN"
What happened - Huge html block in the example section beneath it
What you expected - the formatted example for the pattern i provided
Link to a copy/paste of your logfile with clear debug info of the error on GIST: https://gist.github.com/tabouzeid/53fabaedef2bf3aa9ecb

**Comment by tabouzeid** [comment]
* Branch - master
* Commit hash - 0308a49dcb9bf9bef03ec49a897a8373b399398c
* Your operating system and python version - BusyBox v1.6, Python - 2.7.10
* What you did - removed an anime series and readded it as an existing show
* What happened - The matching from series name - absolute ep number - ep name to the sickrage ep list failed, it mapped to unknown non existant episodes which were blank. even though it had previously renamed them during post processing
* What you expected - Sickrage to properly recognize the episodes and match them to the database entries using the absolute episode number
* Link to a copy/paste of your logfile with clear debug info of the error on GIST: N/A

**Comment by neoatomic** [comment]
When you remove the show from SickRage it also deletes the rename history etc. from the database. So when your renamed files don't have the correct show-name/season/episode/quality names in the title you run the risk that they are not detected correctly. 

That seems to be the problem here. So next time better pause the show and dont delete it. Or add all the correct info to the titels.

**Comment by tabouzeid** [comment]
sickrage is the one that renamed the show... i didn't do it manually... i find it difficult to accept that it can't recognize shows that it renamed itself... also when i change the absolute episode number on the episode from 001 (which sickrage did, and i can't make it do 01) to 01 then it picks it up fine after i do a re-scan. and for anime series  i use the absolute ep numbers rather than the 'season x ep' num format, which sickrage also appears to support. If it can't recognize that on a scan then it should be a feature to add.

**Comment by neoatomic** [comment]
If you remove the show than the rename history is also removed from Sickrage. So if your titles are not uniform to standards SickRage wont recognize then.

**Comment by tabouzeid** [comment]
can you add the pattern to recognize the absolute episode numbering of the episode
