### ISSUE TITLE
Pushalot notification failed. Test from notification options works.

### ISSUE THREAD

**Issue by bricej13** [SiCKRAGETV/sickrage-issues#2295]
### Repro Steps
1. Setup Pushalot from the Notifications -> Device page
2. Add API Key
3. Enable Pushalot notifications for snatch/download
4. Send a Test notification (Note that it works)
5. Wait for a file to finish downloading

### Expected Result
Expected to get a Pushalot notification on my phone

### Actual Result
* No notification was recieved
* Got the following error: `2015-07-23 03:50:34 POSTPROCESSER :: Pushalot notification failed.`

### System Information
```
SR Version:	BRANCH: (master) / COMMIT: (eb6f4d46709f4b3dd337c56573feb5bac27b10a9) 
SR User:	sickrage
SR Locale:	(None, None)
SR Config file:	/opt/sickrage/config.ini
SR Database file:	/opt/sickrage/sickbeard.db
SR Cache Dir:	/opt/sickrage/cache
SR Log Dir:	/opt/sickrage/Logs
SR Arguments:	['-q', '--daemon', '--nolaunch', '--pidfile=/var/run/sickrage/sickrage.pid', '--datadir=/opt/sickrage']
Python Version:	2.7.3 (default, Mar 14 2014, 11:57:14) [GCC 4.7.2]
```
```
$ uname -a
Linux seedy 2.6.32-39-pve #1 SMP Fri May 8 11:27:35 CEST 2015 i686 GNU/Linux
$ cat /proc/version
Linux version 2.6.32-39-pve (root@lola) (gcc version 4.7.2 (Debian 4.7.2-5) ) #1 SMP Fri May 8 11:27:35 CEST 2015
```
### Logs
[Relevant Log files (GIST)](https://gist.github.com/bricej13/27ca7cafc311eee942df)

It appears `_sendPushalot()` that is unable to get the variable `sickbeard.PUSHALOT_AUTHORIZATIONTOKEN` in `sickbeard/notifiers/pushalot.py:64`

**Comment by fernandog** [comment]
[Errno -2] Name or service not known

Intermittent issue. Internet issue

**Comment by bricej13** [comment]
I failed to mention that it happened every time it attempted to send out a notification.

I was able to fix it by removing a trailing space from my Pushalot API key.

Thanks for all the hard work on the project!

**Comment by rd1** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: Pushalot notification failed.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rd1** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
Link to Log: https://gist.github.com/6ba122af9b139458bdc5
### ERROR
```
SEARCHQUEUE-MANUAL-71663 :: [Rarbg] :: Pushalot notification failed.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
