### ISSUE TITLE
Can't delete custom torrent provider if API key is empty

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#2296]
DELETE button is disable.
Need to enter something in the field, save then after that. delete button is enabled

https://github.com/SiCKRAGETV/sickrage-issues/issues/2196

**Comment by miigotu** [comment]
Should be a quick js fix. I'll look before I merge tonight.

**Comment by fernandog** [comment]
I couldnt reproduce. At user's sickrage button was disabled. Strange

**Comment by miigotu** [comment]
I think it is when you have old custom provider, and then enable built in provider, you cannot remove custom provider. But unless the issue keeps coming up shouldnt waste our time.
