### ISSUE TITLE
[APP SUBMITTED]: global name 'params' is not defined

### ISSUE THREAD

**Issue by hidefog** [SiCKRAGETV/sickrage-issues#2297]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-43-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@eb6f4d46709f4b3dd337c56573feb5bac27b10a9
Link to Log: https://gist.github.com/540299b9c67ae20f6553
### ERROR
```
SEARCHQUEUE-BACKLOG-102531 :: Error while searching NZBGeek, skipping: global name 'params' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by hidefog** [comment]
AA
AANameError: global name 'params' is not defined
AA    elif 'rid' in params:
AA  File "/opt/sickrage/sickbeard/providers/newznab.py", line 152, in _get_season_search_strings
AA    for curString in self._get_season_search_strings(epObj):
AA  File "/opt/sickrage/sickbeard/providers/generic.py", line 364, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/opt/sickrage/sickbeard/search.py", line 473, in searchProviders
AANameError: global name 'params' is not defined
AA    elif 'rid' in params:
AA  File "/opt/sickrage/sickbeard/providers/newznab.py", line 152, in _get_season_search_strings
AA    for curString in self._get_season_search_strings(epObj):
AA  File "/opt/sickrage/sickbeard/providers/generic.py", line 364, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/opt/sickrage/sickbeard/search.py", line 473, in searchProviders
AATraceback (most recent call last):
2015-07-23 13:05:11 ERROR    SEARCHQUEUE-BACKLOG-102531 :: Error while searching NZBGeek, skipping: global name 'params' is not defined

**Comment by fernandog** [comment]
@hidefog did you enabled proxy in nzbgeek?

**Comment by fernandog** [comment]
@miigotu

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/2196

**Comment by fernandog** [comment]
reopened to prevent new issues

**Comment by nibbew** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@9b5c30fc89d633f0366295fd7d2ee69541af8159
Link to Log: https://gist.github.com/7779fdafbbf36f65ce88
### ERROR
```
SEARCHQUEUE-BACKLOG-196981 :: [ozNZB] :: Error while searching ozNZB, skipping: global name 'params' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by nibbew** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@9b5c30fc89d633f0366295fd7d2ee69541af8159
Link to Log: https://gist.github.com/d307a3e1164221e79cce
### ERROR
```
SEARCHQUEUE-BACKLOG-196981 :: [NZB.Cat] :: Error while searching NZB.Cat, skipping: global name 'params' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
I don't have this issue with nzbgeek. Is was fixed @miigotu ?

**Comment by miigotu** [comment]
pretty sure.
