### ISSUE TITLE
 [Feature Request] not donwload italian releases on TNTvillage

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2298]
@gborri Having an option to not download italian releases ,like the italian subbed option

**Comment by adaur** [comment]
Why just italian? Can't you add a word to your required/ignored list?

A workaround would be to add the required/ignored list at the provider level, not just globally and per TV show.

**Comment by duramato** [comment]
It does seem to work quite right using it, also i like having releases that are double language ITA ENG And adding ITA to the ignored words would causr them to not download

**Comment by gborri** [comment]
@durando @adaur making it available for provider globally is simpler; making it available per sho is more difficult. the real point is what we want to do. whe want to have the possibility to chose only one language, we would like to have the possibility to choose a combination of language (for example: "(ITA and ENG) or ITA") i have not so many experience in programming and not in HTML to implement it. If someone want to help we can do it.

**Comment by fernandog** [comment]
@duramato 
sorry about asking but this provider is a italian provider isn't? so why enable it if you don't want subbed italian releases?!

**Comment by gborri** [comment]
@fernandog is an italian provider but you can find a lot of english version (rarely you can find some other languages). The content is qualified and certified.

**Comment by duramato** [comment]
@gborri what i would like is to  not download releases that are only italian, ITA ENG are ok  and only ENG are also okay
@fernandog i have it enabled becouse of the the releases that have 2 language tracks and the ones that are pure english becouse i really like their releases .I do the same thing for t411 since it has some good releases

**Comment by adaur** [comment]
What about my request? Would it be too hard to implement?

**Comment by fernandog** [comment]
@adaur it's up to @gborri as he added that provider

**Comment by fernandog** [comment]
@adaur "required/ignored list at the provider level" - not possible. A LOT of code changing

**Comment by WebSpider** [comment]
Well, not easy to do. I'm sure it can be done, so if someone sends in a pullreq with this feature in it ...

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
