### ISSUE TITLE
Generic module not found

### ISSUE THREAD

**Issue by stappel** [SiCKRAGETV/sickrage-issues#2302]
Error in log:
```
AA
AAImportError: No module named generic
AA    from .generic import GenericClient
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/clients/download_station_client.py", line 24, in <module>
AA    return __import__(prefix + name + '_client', fromlist=__all__)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/clients/__init__.py", line 114, in getClientModule
AA    module = getClientModule(name)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/clients/__init__.py", line 118, in getClientIstance
AA    client = clients.getClientIstance(sickbeard.TORRENT_METHOD)()
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 137, in snatchEpisode
AA    search.snatchEpisode(result)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search_queue.py", line 227, in run
2015-07-23 19:50:57 INFO     SEARCHQUEUE-BACKLOG-272127 :: Downloading Extant.S02E04.720p.HDTV.X264-DIMENSION[EtHD] from ThePirateBay
```
SR Version: 	BRANCH: (master) / COMMIT: (eb6f4d46709f4b3dd337c56573feb5bac27b10a9) 
Running on NAS (Synology)

**Comment by fernandog** [comment]
do this:
https://github.com/SiCKRAGETV/sickrage-issues/issues/2247#issuecomment-123275228

**Comment by fernandog** [comment]
if don't work, reply on that issue

**Comment by stappel** [comment]
removed files as stated in https://github.com/SiCKRAGETV/sickrage-issues/issues/2247#issuecomment-123275228. also had to remove generic.py

had to do a git reset --hard and git pull to get the files back and sickrage running again.

the code from https://github.com/SiCKRAGETV/SickRage/pull/2165/files 
does not work. if i put logger output in it as debug it shows it will check the existence of the files, but comes up false. even tho the files are in that folder.
