### ISSUE TITLE
[APP SUBMITTED]: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by freddysmith1** [SiCKRAGETV/sickrage-issues#231]
### INFO
Python Version: **2.7.8 (default, Dec 12 2014, 21:57:17) 
[GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Branch: **master**
Commit: SiCKRAGETV/SickRage@49ea8f5ac7841f6654509d48d72506923bc47c2a
Pastebin Log URL: http://pastebin.com/SyJuzHLY
### ERROR
```
Thread-53 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 374, in showPoster
    return self.redirect(static_image_path)
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 191, in redirect
    super(BaseHandler, self).redirect(url, permanent, status)
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/tornado/web.py", line 630, in redirect
    self.finish()
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/tornado/web.py", line 892, in finish
    self.flush(include_footers=True)
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/tornado/web.py", line 846, in flush
    start_line, self._headers, chunk, callback=callback)
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/tornado/http1connection.py", line 385, in write_headers
    self._pending_write = self.stream.write(data)
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/tornado/iostream.py", line 348, in write
    self._handle_write()
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/tornado/iostream.py", line 800, in _handle_write
    _merge_prefix(self._write_buffer, num_bytes)
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/tornado/iostream.py", line 1382, in _merge_prefix
    if len(deque) == 1 and len(deque[0]) <= size:
TypeError: object of type 'NoneType' has no len()

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@falcon15500 @freddysmith1 is this issue still happening? Can you try develop branch and report back please?

**Comment by fernandog** [comment]
@abeloin is this related to the fix you did about network?

**Comment by abeloin** [comment]
@fernandog No

**Comment by fernandog** [comment]
@abeloin to this this shouldn't we just change:

if len(deque) == 1 and len(deque[0]) <= size:

to 
if deque:
    if len(deque) == 1 and len(deque[0]) <= size:

**Comment by fernandog** [comment]
@falcon15500 @freddysmith1 try to use this file:
https://raw.githubusercontent.com/fernandog/SickRage/patch-20/tornado/iostream.py

change it in /SickRage/tornado/iostream.py
backup first.

**Comment by abeloin** [comment]
@fernandog Would it not be the other way around? As the remaining code will do nothing.
```
if not deque:
    return
```
But it is a bit in the code to catch it.

**Comment by fernandog** [comment]
@abeloin but why does it that checks and comparison with size? As I don't know I did that =)

**Comment by abeloin** [comment]
Look at the example provided:
```
"""Replace the first entries in a deque of strings with a single
string of up to size bytes.
>>> d = collections.deque(['abc', 'de', 'fghi', 'j'])
>>> _merge_prefix(d, 5); print(d)
deque(['abcde', 'fghi', 'j'])
Strings will be split as necessary to reach the desired size.
>>> _merge_prefix(d, 7); print(d)
deque(['abcdefg', 'hi', 'j'])
>>> _merge_prefix(d, 3); print(d)
deque(['abc', 'defg', 'hi', 'j'])
>>> _merge_prefix(d, 100); print(d)
deque(['abcdefghij'])
"""
```
It check if there's only one string provided, and if the size of that string is inferior or equal return as there is nothing to do.

**Comment by fernandog** [comment]
so we can do just what you wait? will close the PR and submit another.

**Comment by abeloin** [comment]
Don't delete:
```
if len(deque) == 1 and len(deque[0]) <= size:
```
put it before:
```
if not deque:
    return
if len(deque) == 1 and len(deque[0]) <= size:
```

**Comment by abeloin** [comment]
But this is a band-aid as the none type is floating around in will cause other issue. We need to find the cause of it.

**Comment by fernandog** [comment]
@abeloin will wait @echel0n then =)

**Comment by fernandog** [comment]
@freddysmith1 @falcon15500 how to reproduce it and test the fix?

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/528#issuecomment-72376359

**Comment by fernandog** [comment]
as @Hellowlol said here https://github.com/SiCKRAGETV/SickRage/pull/1247#issuecomment-71493899
we still need to find the None floating around the the program

waiting @echel0n

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/615#issuecomment-74532095

**Comment by fernandog** [comment]
how to trace this None? I think will see this a lot more...

**Comment by TagForce** [comment]
@fernandog Hah, we're both thinking the same thing... Colleague of mine is getting this same error.
One thing I noticed on almost all of the submitted errors is that the earliest common denominator is line 191 in Webserve.py...
Both permanent and status are given either by the default setting, or by the redirect function (if status is None then status = 302 if permanent else 301). So the only other variable that could mess up is url.

So my guess would be that the passed URL is either invalid, or empty, which creates a None somewhere else.

**Comment by fernandog** [comment]
I didn't understand but is it possible to reproduce? =)

**Comment by TagForce** [comment]
@fernandog Sadly, no... I never get this error. My colleague gets it everytime he does a mass update (update and rescan) on any show he has in his list. I'll ask him for his logs when he gets out of the meeting, or tomorrow (whichever time I speak to him comes first).

**Comment by echel0n** [comment]
Ok i'm looking into this issue just gotta load up the new lappy with my dev software so I can debug this, got some spare time on my hands that I can devote to this issue right now :)

**Comment by fernandog** [comment]
Another one
https://github.com/SiCKRAGETV/sickrage-issues/issues/672

**Comment by echel0n** [comment]
Sorry today got busyer then i thought will tackle this tomorrow.

**Comment by fernandog** [comment]
another one
https://github.com/SiCKRAGETV/sickrage-issues/issues/730

**Comment by OmgImAlexis** [comment]
@fernandog is it worth me submitting the 500+ I got last night with this error or do you guys have enough logs now?

**Comment by fernandog** [comment]
@OmgImAlexis don't bother. DEV still couldn't reproduce the error. He is still trying.

**Comment by OmgImAlexis** [comment]
@fernandog alright, well if you need any more logs just hit me up. I still get 50 - 1,000+ a night even when no one's accessing it and it's not downloading anything. :\

**Comment by OmgImAlexis** [comment]
Actually I just found another issue that seems to spit out the same error. I'm getting this when accessing the main sickrage page(/home) through the nginx proxy I have setup but I don't get it at all when accessing it via the IP address.

~~~
2015-02-23 23:57:59 Thread-86 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/media/sickrage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/home/media/sickrage/sickbeard/webserve.py", line 374, in showPoster
    return self.redirect(static_image_path)
  File "/home/media/sickrage/sickbeard/webserve.py", line 191, in redirect
    super(BaseHandler, self).redirect(url, permanent, status)
  File "/home/media/sickrage/tornado/web.py", line 630, in redirect
    self.finish()
  File "/home/media/sickrage/tornado/web.py", line 893, in finish
    self.request.finish()
  File "/home/media/sickrage/tornado/httputil.py", line 392, in finish
    self.connection.finish()
  File "/home/media/sickrage/tornado/http1connection.py", line 447, in finish
    self.stream.set_nodelay(True)
  File "/home/media/sickrage/tornado/iostream.py", line 1113, in set_nodelay
    socket.TCP_NODELAY, 1 if value else 0)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
  File "/usr/lib/python2.7/socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

2015-02-23 23:57:59 Thread-53 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/media/sickrage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/home/media/sickrage/sickbeard/webserve.py", line 374, in showPoster
    return self.redirect(static_image_path)
  File "/home/media/sickrage/sickbeard/webserve.py", line 191, in redirect
    super(BaseHandler, self).redirect(url, permanent, status)
  File "/home/media/sickrage/tornado/web.py", line 630, in redirect
    self.finish()
  File "/home/media/sickrage/tornado/web.py", line 892, in finish
    self.flush(include_footers=True)
  File "/home/media/sickrage/tornado/web.py", line 846, in flush
    start_line, self._headers, chunk, callback=callback)
  File "/home/media/sickrage/tornado/http1connection.py", line 385, in write_headers
    self._pending_write = self.stream.write(data)
  File "/home/media/sickrage/tornado/iostream.py", line 348, in write
    self._handle_write()
  File "/home/media/sickrage/tornado/iostream.py", line 800, in _handle_write
    _merge_prefix(self._write_buffer, num_bytes)
  File "/home/media/sickrage/tornado/iostream.py", line 1383, in _merge_prefix
    if len(deque) == 1 and len(deque[0]) <= size:
TypeError: object of type 'NoneType' has no len()
~~~

**Comment by joq3** [comment]
@OmgImAlexis I have noticed the same thing. When accessing SickRage trough my nginx reverse proxy I get this error. But not if I access it trough port number. Can you post your nginx reverse proxy setup, want to see if we have the same setup.

**Comment by OmgImAlexis** [comment]
@joq3 here you go.

~~~
upstream sickrage {
    server 127.0.0.1:8081;
}

server {
    listen 0.0.0.0:80;
    server_name sickrage.media.tardis;
    access_log /var/log/nginx/sickrage.log;

    # pass the request to the node.js server with the correct headers and much more can be added, see nginx config options
    location / {
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_set_header X-NginX-Proxy true;

      proxy_pass http://sickrage/;
      proxy_redirect off;
    }
 }
~~~

**Comment by Hellowlol** [comment]
@OmgImAlexis I'm no expert regarding nginx config, but i do have a working setup. The main difference between your config and mine is that proxy_pass http://ip:port in my setup.

**Comment by OmgImAlexis** [comment]
Can you access your sickrage without the Port though? I've got it like that so I can use a subdomain for each of my services like sickrage and couchpotato.

**Comment by Hellowlol** [comment]
Yeah. I access stuff like mydomain.com/sickrage mydomain.com/htpc etc

**Comment by Hellowlol** [comment]
Check out http://www.htpcguides.com/configure-sickrage-reverse-proxy-nginx/

**Comment by OmgImAlexis** [comment]
@Hellowlol That can't be the reason I've got the issue then as mine's exactly the same as yours just I'm using a subdomain instead of relative URLs.

**Comment by Hellowlol** [comment]
@OmgImAlexis Its not, your using proxy_pass is http://sickrage/ while the guide and myself have the proxy_path http://ip:port/sickrage

**Comment by OmgImAlexis** [comment]
Yeah that's the same thing. The one I'm using just references the section at the top.

**Comment by Hellowlol** [comment]
Tried dropping the last / in proxy_pass ?

**Comment by OmgImAlexis** [comment]
Same errors. I'll have a play around with it tomorrow and see if I can get the errors to go away. I have a feeling it's more to do with sickrage than nginx though.

**Comment by Hellowlol** [comment]
Ill drop my conf in a gist so you can compare when i get home from work.

**Comment by joq3** [comment]
Guys, I've setup a nginx redirect for both SickRage and CouchPotato, Sickrage gives me the above error. And Couchpotato gives me no images on the front page ( http://i.imgur.com/Qdhbsy3.png ) when accessing with nginx redirect, with port number it does work. I've set them up exactly the same. Maybe there is something missing?
I know this is the wrong thread, but can you also post you couchpotato nginx reverse or pm me it?
Thank  you!

Please note that I try to find what is wrong with Sickrage also, maybe they have something in common.

**Comment by OmgImAlexis** [comment]
Let's move to a new issue. 
https://github.com/SiCKRAGETV/sickrage-issues/issues/764

**Comment by abeloin** [comment]
@freddysmith1 @falcon15500 @OmgImAlexis @joq3 @Hellowlol Can you try this PR: https://github.com/SiCKRAGETV/SickRage/pull/1419 ?

**Comment by fernandog** [comment]
@freddysmith1 @falcon15500 @joq3 @Hellowlol please update develop branch. report bakc if is fixed

**Comment by Hellowlol** [comment]
@fernandog No issues to far regarding that bug, but i havnt been affected by it before as far as i remember. I did notice a other bug regarding abeloins fix for apikeys, but ill make a seperate issue about that.

**Comment by fernandog** [comment]
@Hellowlol ok! thanks

**Comment by fernandog** [comment]
@freddysmith1 @falcon15500 @joq3 please reply or will mark it as fixed
