### ISSUE TITLE
[APP SUBMITTED]: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by xxxscrabblexxx** [SiCKRAGETV/sickrage-issues#2311]
### INFO
Python Version: **2.7.3 (default, Apr 12 2012, 13:08:47) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@eb6f4d46709f4b3dd337c56573feb5bac27b10a9
Link to Log: https://gist.github.com/f6d460e17f9e1aacec9a
### ERROR
```
Thread-18 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/sickbeard/webserve.py", line 2956, in changeEpisodeStatuses
    self.setStatus(cur_indexer_id, '|'.join(to_change[cur_indexer_id]), newStatus, direct=True)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/sickbeard/webserve.py", line 1737, in setStatus
    epObj = showObj.getEpisode(int(epInfo[0]), int(epInfo[1]))
ValueError: invalid literal for int() with base 10: ''

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Log says : `No NZB/Torrent providers found or enabled in the sickrage config for daily searches. Please check your settings.`

Also what package are you using on your QNAP.? Qsickrage.? http://apps.qnap.community/11-community/17-qsickrage

**Comment by miigotu** [comment]
Fixed in develop.

**Comment by miigotu** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-58-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **submit-confirm**
Commit: SiCKRAGETV/SickRage@8e2939427d62807b7df935cd122a1dcd0ac6a80e
Link to Log: https://gist.github.com/4d0c773cbfa8546679e6
### ERROR
```
Thread-16 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/dusted/Projects/SickRage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/home/dusted/Projects/SickRage/sickbeard/webserve.py", line 1588, in deleteShow
    showObj = sickbeard.helpers.findCertainShow(sickbeard.showList, int(show))
ValueError: invalid literal for int() with base 10: ''

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-58-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **submit-confirm**
Commit: SiCKRAGETV/SickRage@8e2939427d62807b7df935cd122a1dcd0ac6a80e
Link to Log: https://gist.github.com/b8cc8e629965d82fcbd0
### ERROR
```
Thread-28 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/dusted/Projects/SickRage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/home/dusted/Projects/SickRage/sickbeard/webserve.py", line 1588, in deleteShow
    showObj = sickbeard.helpers.findCertainShow(sickbeard.showList, int(show))
ValueError: invalid literal for int() with base 10: ''

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@miigotu how did you reproduce it?

**Comment by miigotu** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-58-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **submit-confirm**
Commit: SiCKRAGETV/SickRage@8e2939427d62807b7df935cd122a1dcd0ac6a80e
Link to Log: https://gist.github.com/7ae1eeb538aff00c0de3
### ERROR
```
Thread-17 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/dusted/Projects/SickRage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/home/dusted/Projects/SickRage/sickbeard/webserve.py", line 1588, in deleteShow
    showObj = sickbeard.helpers.findCertainShow(sickbeard.showList, int(show))
ValueError: invalid literal for int() with base 10: ''

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-58-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **submit-confirm**
Commit: SiCKRAGETV/SickRage@8e2939427d62807b7df935cd122a1dcd0ac6a80e
Link to Log: https://gist.github.com/29e73cbbfaf57738b044
### ERROR
```
Thread-20 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/dusted/Projects/SickRage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/home/dusted/Projects/SickRage/sickbeard/webserve.py", line 1588, in deleteShow
    showObj = sickbeard.helpers.findCertainShow(sickbeard.showList, int(show))
ValueError: invalid literal for int() with base 10: ''

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-58-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **submit-confirm**
Commit: SiCKRAGETV/SickRage@8e2939427d62807b7df935cd122a1dcd0ac6a80e
Link to Log: https://gist.github.com/04bfa3b7d9b46ee01614
### ERROR
```
Thread-26 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/dusted/Projects/SickRage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/home/dusted/Projects/SickRage/sickbeard/webserve.py", line 1588, in deleteShow
    showObj = sickbeard.helpers.findCertainShow(sickbeard.showList, int(show))
ValueError: invalid literal for int() with base 10: ''

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
ignore these, I was creating an error for testing the submit errors popup.

**Comment by TATUMTOT** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@afac218339ac14bf03a8fda76df0318fcb4a5247
Link to Log: https://gist.github.com/44cbaf0900b2c6f80bcf
### ERROR
```
Thread-44 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/CE_CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/share/CE_CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 1348, in displayShow
    t.xem_absolute_numbering = get_xem_absolute_numbering_for_show(indexerid, indexer)
  File "/share/CE_CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/scene_numbering.py", line 453, in get_xem_absolute_numbering_for_show
    scene_absolute_number = int(row['scene_absolute_number'])
ValueError: invalid literal for int() with base 10: ''

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
@TATUMTOT use QSickrage package.

**Comment by TATUMTOT** [comment]
Downloading now!!! OMG could this also fix the SSL errors there we were having
