### ISSUE TITLE
non UTF?

### ISSUE THREAD

**Issue by wimpyrbx** [SiCKRAGETV/sickrage-issues#2314]
Recently i've seen quite a lot of this stuff:
when fetching series info from tvrage or thetvdb. some titles that have ' in them are shown with ’ instead (yes they look similar but are not)

’ !== '

example:
Pretty Little Liars S05E19:
TV-Rage: Pretty Isn’t The Point
SickRage: Pretty Isnâ€™t The

Am i overlooking something or is there an issue with UTF standards in SickRage?

The result now is that if i rename files via SickRage it will not display those episodes containing ' chars. I'm guessing this is the case for other chars as well, but i have no examples as of now.

**Comment by wimpyrbx** [comment]
Further info;

01:06:21 WARNING::Thread-45 :: Can't perform rename on D:\Pretty Little Liars\Season 05\Pretty Little Liars - S05E20 - Pretty IsnAƒÆ'A+â?TAƒâ? A¢â,¬â,¢AƒÆ'A¢â,¬Å¡Aƒâ?sA,A¢AƒÆ'A+â?TAƒâ?sA,A¢AƒÆ'A,A¢AƒA¢A¢â,¬Å¡A,A¬
Aƒâ?▌A,A¡AƒÆ'A¢â,¬Å¡Aƒâ?sA,A¬AƒÆ'A+â?TAƒâ?sA,A¢AƒÆ'A,A¢AƒA¢A¢â,¬Å¡A,A¬Aƒâ?▌A,A_AƒÆ'A¢â,¬Å¡Aƒâ?sA,A¢t The Point.mkv when it doesn't exist, skipping

nobody else experiencing strange names of episodes when getting info from tvrage and/or thetvdb?

**Comment by fernandog** [comment]
@miigotu another one

**Comment by miigotu** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/2187
