### ISSUE TITLE
JS error when restarting: Uncaught TypeError: $(...).tabs is not a function

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#2315]
Don't know which file is responsible for that:

:~/SickRage/gui$ grep -Ril ").tabs"
slick/interfaces/default/config_notifications.tmpl
slick/interfaces/default/config_search.tmpl
slick/interfaces/default/config_general.tmpl
slick/interfaces/default/config_backuprestore.tmpl
slick/interfaces/default/config_subtitles.tmpl
slick/interfaces/default/home_recommendedShows.tmpl
slick/interfaces/default/config_postProcessing.tmpl
slick/interfaces/default/home_addExistingShow.tmpl
slick/interfaces/default/home_trendingShows.tmpl
slick/interfaces/default/config_providers.tmpl
slick/js/addExistingShow.js
slick/js/script.js

**Comment by miigotu** [comment]
Should be fixed in mako.
