### ISSUE TITLE
I still can't snatch from NZBgeek

### ISSUE THREAD

**Issue by rickytin** [SiCKRAGETV/sickrage-issues#2316]
I update to latest SickRage master and I still can't snatch from NZBgeek.
Logs:
https://gist.github.com/rickytin/ea549ba7dce54daf8d4a

**Comment by fernandog** [comment]
@rickytin dont think you are using the latest code:

SR code shows the error number:
logger.log(u"Connection error in headURL %s. Error: %s " % (url, ex(e)), logger.WARNING)

you log shows only this:
Connection error in headURL https://api.nzbgeek.info/api?t=get&id=9e14b01c68b423c98decf8f5fae43680&apikey=**********

**Comment by rickytin** [comment]
It's frustrating, still not working for me I can't snatch from NZBGeek.

**Comment by fernandog** [comment]
Logs??

**Comment by rickytin** [comment]
https://gist.github.com/rickytin/09a3cce8ec43672cd706

**Comment by fernandog** [comment]
@miigotu still no head request?

Bad result from provider

**Comment by rickytin** [comment]
Here is my new log with debug, sorry I thought debug was already selected in advances settings.
https://gist.github.com/rickytin/318638554bed23b66558

**Comment by rickytin** [comment]
And thanks for your patience fernandog and @miigotu.

**Comment by miigotu** [comment]
there are no searches in that blog.

**Comment by rickytin** [comment]
A question, which log should I send. In SickRage application in logs Minimum logging level to display we have DB, Debug, Info, Warning and Error or should I go to SickRage log in my hard drive and copy the information of the latest log.

**Comment by rickytin** [comment]
This is Info log from SickRage:
https://gist.github.com/rickytin/7c31285a9f3fad678d4e

**Comment by rickytin** [comment]
This is Debug log from SickRage:
https://gist.github.com/rickytin/2e5c334de83a46075a13

**Comment by miigotu** [comment]
I would copy the log from hard drive, with debug enabled.

BUT you need to at least try a manual search to nzbgeek that fails, and THEN give me the log, otherwise there is no information about why the search to nzbgeek is failing.

**Comment by rickytin** [comment]
Log from hard drive with debug enabled.
I have 4 show missing so I did a manual search for this 4 shows.
Here is the log:
https://gist.github.com/rickytin/593e39046ccb7ea8acaf

**Comment by fernandog** [comment]
Cant understand why there is no URL error code:

Connection error in headURL https://api.nzbgeek.info/api?t=get&id=9b35a99022b3a339f6b3fe233c4f930b&apikey=**********

**Comment by miigotu** [comment]
@fernandog it is an ssl problem.

If you have no ssl errors, head requests are always 200 for nzbgeek atm, even with incorrect apikey or wrong guid.

I have sent them a new email about this always 200 problem, but it will not fix this issue.

**Comment by miigotu** [comment]
Re the response code from NZBgeek:

NZBGeeks says:
"I have just finished working on another issue and will get this done is the next few hours for you."

**Comment by miigotu** [comment]
BTW, @fernandog is right @rickytin. Your log says you have latest master, but the log lines are not from latest master.

Only can help with SSH or TeamViewer.
