### ISSUE TITLE
Transmission not working anymore

### ISSUE THREAD

**Issue by FuNK3Y** [SiCKRAGETV/sickrage-issues#2318]
There is some missing dependencies:
AA
AAImportError: No module named generic
AA    from .generic import GenericClient
AA  File "/opt/sickrage/sickbeard/clients/transmission_client.py", line 25, in <module>
AA    return __import__(prefix + name + '_client', fromlist=__all__)
AA  File "/opt/sickrage/sickbeard/clients/__init__.py", line 114, in getClientModule
AA    module = getClientModule(name)
AA  File "/opt/sickrage/sickbeard/clients/__init__.py", line 118, in getClientIstance
AA    client = clients.getClientIstance(sickbeard.TORRENT_METHOD)()
AA  File "/opt/sickrage/sickbeard/search.py", line 137, in snatchEpisode
AA    search.snatchEpisode(result)
AA  File "/opt/sickrage/sickbeard/search_queue.py", line 227, in run

It worked fine last time I checked

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/2273#issuecomment-123582683
