### ISSUE TITLE
Feature Request - Don't auto-update if SHOWQUEUE-FORCE-UPDATE is running or POST-PROCESSING

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#232]
If user set to auto update, don't update if SHOWQUEUE-FORCE-UPDATE is running OR the 03:00 AM update

Don't know how SR handle this.

**Comment by fernandog** [comment]
@abeloin what do you think about this?

**Comment by abeloin** [comment]
@fernandog Why not simply execute the following command before starting the update:
```
halt()
saveAll()
```
this way we aborting all threads(waiting for them to finish), save the db, update then restart.

**Comment by fernandog** [comment]
@abeloin hald the thread will make it re-start from where it stopped? or SR will update everything all over again? For example: updated 90 shows from 100. new update available > restart > update will start from show 1, not 90

**Comment by abeloin** [comment]
Start over as there is no notion of pausing thread in sickrage

**Comment by fernandog** [comment]
or abort update an wait next update check as first post. same for PP

**Comment by abeloin** [comment]
Then you should limit your check to dailySearchStatus and autoPostProcesserStatus as the other one aren't that long.
