### ISSUE TITLE
ImportError: No module named generic

### ISSUE THREAD

**Issue by coolbaughm** [SiCKRAGETV/sickrage-issues#2320]
AA
AAImportError: No module named generic
AA    from .generic import GenericClient
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/clients/transmission_client.py", line 25, in <module>
AA    return __import__(prefix + name + '_client', fromlist=__all__)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/clients/__init__.py", line 114, in getClientModule
AA    module = getClientModule(name)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/clients/__init__.py", line 118, in getClientIstance
AA    client = clients.getClientIstance(sickbeard.TORRENT_METHOD)()
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/search.py", line 137, in snatchEpisode
AA    self.success = search.snatchEpisode(searchResult[0])
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/search_queue.py", line 184, in run
2015-07-24 13:38:31 INFO     SEARCHQUEUE-MANUAL-281256 :: Downloading Complications.S01E07.HDTV.XviD-FUM[ettv] from KickAssTorrents

AA
AAImportError: No module named generic
AA    from .generic import GenericClient
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/clients/transmission_client.py", line 25, in <module>
AA    return __import__(prefix + name + '_client', fromlist=__all__)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/clients/__init__.py", line 114, in getClientModule
AA    module = getClientModule(name)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/clients/__init__.py", line 118, in getClientIstance
AA    client = clients.getClientIstance(sickbeard.TORRENT_METHOD)()
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/search.py", line 137, in snatchEpisode
AA    self.success = search.snatchEpisode(searchResult[0])
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/search_queue.py", line 184, in run
2015-07-24 13:24:34 INFO     SEARCHQUEUE-MANUAL-42422 :: Downloading Mr.Robot.S01E05.XviD-AFG from ThePirateBay

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/2302#issuecomment-124239083
