### ISSUE TITLE
[Feature Request] Hadouken Client Support?

### ISSUE THREAD

**Issue by jaimbo** [SiCKRAGETV/sickrage-issues#2324]
Could we possibly get support for this client? It seems to be a very promising fast lightweight and headless client for Windows.

Completely Open source: https://github.com/hadouken/hadouken
Seems to have a fair amount of documentation which should help in adding support: http://docs.hdkn.net/en/latest/

**Comment by miigotu** [comment]
I have written the code for this for you, but am currently fighting to compile it in ubuntu right now in order to test it.

**Comment by jaimbo** [comment]
Awesome, hopefully be able to give it a bash soon!

**Comment by miigotu** [comment]
I cant get the Hadouken to compile, fails on linking zzzz

**Comment by jaimbo** [comment]
You have any luck with this yet?

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
