### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-2725 :: Check scene exceptions update failed. Unable to get URL: https://raw.githubusercontent.com/echel0n/sb_tvrage_scene_exceptions/master/exceptions.txt

### ISSUE THREAD

**Issue by pistonrod8** [SiCKRAGETV/sickrage-issues#2326]
### INFO
Python Version: **2.7.3 (default, Jul 31 2014, 02:11:10) [GCC 4.5.4 20120201 (prerelease)]**
Operating System: **Linux-3.2.26-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@c1c519b720acfbbc5cec7c5a89c48053e9f1b980
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-2725 :: Check scene exceptions update failed. Unable to get URL: https://raw.githubusercontent.com/echel0n/sb_tvrage_scene_exceptions/master/exceptions.txt
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by WebSpider** [comment]
It would seem that you are on a release dating from April 22nd.You may want to upgrade, and check if the issue still exists.

Upgrading is possible using the Tools dropdown (on the right) and selecting "Check for updates"
