### ISSUE TITLE
Search not checking both and types

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2327]
When a show has a ``&`` in it's title should the search not check ``&`` and ``and``?
For now I've added it as a scene exception but it'd be nice to have it check both if one can't be found as I've noticed most of the time ``and`` gets used over ``&``.

**Comment by OmgImAlexis** [comment]
Actually even after adding the scene expection ``Penn and teller fool us`` I still don't get an episode snatched.

````
2015-07-25 12:25:59 INFO     SEARCHQUEUE-MANUAL-239851 :: Unable to find a download for: [Penn & Teller Fool Us - 2x03 - Shoot to Kill]
2015-07-25 12:25:56 INFO     SEARCHQUEUE-MANUAL-239851 :: [KickAssTorrents] :: Performing episode search for Penn & Teller: Fool Us
2015-07-25 12:25:56 INFO     SEARCHQUEUE-MANUAL-239851 :: Beginning manual search for: [Penn & Teller Fool Us - 2x03 - Shoot to Kill]
2015-07-25 12:25:49 INFO     Thread-32 :: Updating scene exceptions
2015-07-25 12:25:44 INFO     SEARCHQUEUE-BACKLOG-239851 :: No needed episodes found during backlog search for: [Penn & Teller: Fool Us]
2015-07-25 12:25:38 INFO     SEARCHQUEUE-BACKLOG-239851 :: [KickAssTorrents] :: Performing episode search for Penn & Teller: Fool Us
2015-07-25 12:25:38 INFO     SEARCHQUEUE-BACKLOG-239851 :: Beginning backlog search for: [Penn & Teller: Fool Us]
2015-07-25 12:25:36 INFO     SEARCHQUEUE-BACKLOG-239851 :: No needed episodes found during backlog search for: [Penn & Teller: Fool Us]
2015-07-25 12:25:26 INFO     SEARCHQUEUE-BACKLOG-239851 :: [KickAssTorrents] :: Performing episode search for Penn & Teller: Fool Us
2015-07-25 12:25:26 INFO     SEARCHQUEUE-BACKLOG-239851 :: Beginning backlog search for: [Penn & Teller: Fool Us]
````

**Comment by miigotu** [comment]
1. Debug is not enabled
2. Have you tried to search kickass yourself? the only 2 results for that episode on kickass are 720p web-dl, and your settings do not want that quality.

**Comment by OmgImAlexis** [comment]
1. I'll do that now.

2. I have my quality set as ``Initial: HDTV, 1080p WEB-DL, 720p BluRay, 1080p BluRay`` so it should snatch this ``Penn and Teller Fool Us S02E03 720p WEBRip AAC2 x264-BTN``. At least it did before the update that caused new episodes to be ``paused`` by default. I found that update caused a lot of my shows to either not snatch anything or say nothing could be snatched when I found a copy myself that should have been found, a lot of my shows I had to edit and save to get them to now download again.

3. Alright, just thought it may have been the reason it didn't see it as it's snatched versions like this before with the same quality settings on other shows.

**Comment by OmgImAlexis** [comment]
Okay, turns out after that update 720p Webrip was removed from my custom quality for some reason. Is there a way to change all shows to a new quality setting?

**Comment by miigotu** [comment]
manage->mass update, check "all" checkbox on top left corner, scroll down and click edit selected

**Comment by OmgImAlexis** [comment]
Okay, everything's fine now.

**Comment by OmgImAlexis** [comment]
@miigotu 

Not sure if this is a issue or I'm overlooking something. I've changed my quality to custom with these settings and now even if I've got something downloaded that's in the ``Replace with`` list it's marked as low quality. I was going on the assumption that if it's in the ``replace with`` list that it'd just stay as is. What I want is anything from HDTV - 1080p HDTV, WEB-DL or BluRay to replace it if it becomes available.

Initial: HDTV, 1080p HDTV, 720p WEB-DL, 1080p WEB-DL, 720p BluRay, 1080p BluRay 
Replace with: 1080p HDTV, 1080p WEB-DL, 1080p BluRay

**Comment by miigotu** [comment]
It will continue to replace the file until it reaches THE BEST QUALITY in the replace with list.

**Comment by OmgImAlexis** [comment]
What's the "best" quality though and should it really be listed as "low quality"?
According to the way it's currently set, 3851/3851 episodes are low quality even though around 90% of them are all 1080p WEB-DL or 1080p HDTV.

**Comment by fernandog** [comment]
until all of them are 1080p BluRay, SR will mark all other as low quality

https://github.com/SiCKRAGETV/SickRage/wiki/Quality-Settings

**Comment by OmgImAlexis** [comment]
Is it currently possible to have it settle for ANY out of the replace with list similar to how couchpotato handles it? or could it be possible to have this added as an option later on?

**Comment by fernandog** [comment]
Did you read ALL wiki?!

**Comment by OmgImAlexis** [comment]
Yes, sorry I typed this out halfway through reading. From what I can tell "Archive on First Match" should do what I want?
Does this fix the "low quality" issue though?

**Comment by OmgImAlexis** [comment]
Okay, this fixes the low quality issue I was talking about but I did just noticed you can't set archive on first match to be on the default for new shows.
