### ISSUE TITLE
[Feature Request] Multi-Episode Subtitles not being detected

### ISSUE THREAD

**Issue by renegaed** [SiCKRAGETV/sickrage-issues#2329]
Hi everyone,

I have the following Episode File:
`Show Name - S01E01-E02 - Episode Name SDTV.avi`
And it's corresponding Subtitle FIle:
`Show Name - S01E01-E02 - Episode Name SDTV.sub`

If I navigate to the show on Sickrage, the subtitle file has been detected for Episode 1 but is deemed missing for Episode 2.

SR Version: BRANCH: (master) / COMMIT: (fc0af7c295bd37f11370ca8527e55d81a6822c36) 
Python Version: 2.7.6
Running on: Ubuntu 14.04.2 LTS

Thanks.

**Comment by miigotu** [comment]
Currently SR is only using the `.srt` extension for subtitles.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
