### ISSUE TITLE
Episode Status Management WANTED SR Issue

### ISSUE THREAD

**Issue by mbxplex** [SiCKRAGETV/sickrage-issues#2330]
@miigotu @fernandog Just wanted to point this out to you guys. I am currently updated to the newest commit and when I go to Episode Status Management and view the WANTED episodes, this is how the page displays in both Google Chrome and Microsoft Edge (wanted to confirm in 2 different browsers).

![capture](https://cloud.githubusercontent.com/assets/12984486/8887753/b3dde71a-325d-11e5-96ac-45d538577d83.PNG)

**Comment by miigotu** [comment]
what commit is that?

**Comment by miigotu** [comment]
Nevermind, It was a boo-boo on my part, pushed a hotfix.
