### ISSUE TITLE
[Feature Request]  Add category selection for official newznab providers as in custom newznab providers

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#2334]
When using newznab SR scrip/code, user can't choose categories in provider settings
Only in "Custom Newznab Providers"

**Comment by miigotu** [comment]
+1

**Comment by fernandog** [comment]
when selecting/enabling NZBgeek provider, categories are empty in the config.ini
so it will never find anything in this provider

[Newznab]
newznab_data = "NZBGeek|https://api.nzbgeek.info/|****||1|eponly|0|1|1!!!

should be by default:

[Newznab]
newznab_data = "NZBGeek|https://api.nzbgeek.info/|****|5030,5040|1|eponly|0|1|1!!!

**Comment by fernandog** [comment]
it's strange as here it adds the CAT:
https://github.com/SiCKRAGETV/SickRage/pull/2146/files

but in my config.ini it was empty

**Comment by miigotu** [comment]
@fernandog its from when nzbgeek was a custom provider. starting with a fresh ini the categories are there. Im not quite sure why it fails with existing ini.

I have however started on this FR.

**Comment by fernandog** [comment]
thanks!

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
