### ISSUE TITLE
Align "Show Episodes" button in displayshow with Season number

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#2337]
At least for me it's confusing the button location

![image](https://cloud.githubusercontent.com/assets/2620870/8890296/ad825bd8-32d2-11e5-8e8d-af94383e458e.png)

**Comment by miigotu** [comment]
How do I see this button? I don't have that in my displayShow

**Comment by fernandog** [comment]
There is an option "collapse season" - something like that

**Comment by miigotu** [comment]
"Show all seasons"

Ugly without that =P

**Comment by MGaetan89** [comment]
I would also be nice if the first (last aired) season also have this button.

**Comment by fernandog** [comment]
But expanded by default.
this feature is for shows with lots of seasons and user does not need to see previous seasons if he doesnt want

**Comment by MGaetan89** [comment]
Yes, it should be open by default.
I will send a PR for that. It is easier to fix than #976

**Comment by MGaetan89** [comment]
PR sent SiCKRAGETV/SickRage#2200

**Comment by fernandog** [comment]
Thanks!
