### ISSUE TITLE
Starting date in recommendation shows incorrectly shown

### ISSUE THREAD

**Issue by Quiptix** [SiCKRAGETV/sickrage-issues#234]
SR Version:	BRANCH: (develop) / COMMIT: (785ffdcf2f58537cc47571e5c18cb954e9d0457e) 

when adding recommended shows the starting date is always somewhere in 1970.
Not sure whether Trakt provides incorrect info.

Example

Arrow (started on 19700116) [257655]

**Comment by fernandog** [comment]
@Quiptix is this still happening with TRAKT 2.0?

**Comment by Quiptix** [comment]
No, doesn't happen, however the Trakt timeouts are annoying...

**Comment by fernandog** [comment]
@Quiptix can you try this too?

**Comment by Quiptix** [comment]
@fernandog : What should I try?

**Comment by abeloin** [comment]
Apply the pull requests to test it.

**Comment by Quiptix** [comment]
For testing the date, that is quite impossible now.
Trending Shows are not shown with dates and recommendations is under development with trakt.tv and so disabled.

Timeouts still exist sometime. Not often, but 1 to 5 times a day

**Comment by fernandog** [comment]
@Quiptix develop updated. please test. also increase your TRAKT timeout (SR trakt settings)

**Comment by Quiptix** [comment]
@fernandog Done. Now somewhat sit and wait... (and sleep)

**Comment by Quiptix** [comment]
I have increased the Trakt timeout to 60 seconds and haven't encountered a timeout yet after almost 24 hours.
I will monitor this for another 24 hours to be sure.

**Comment by Quiptix** [comment]
HAve monitored this even longer. And no timeouts, so be able to set this helps!

**Comment by Quiptix** [comment]
Recommendations are working again at Trakt side. I get this:
```
Room Raiders (started on 20031001) [73354]
```
It is correct date, however not very pretty... Maybe a cosmetic change is in order.

**Comment by fernandog** [comment]
@Quiptix we are looking others things. this is cosmetic only

**Comment by Quiptix** [comment]
@fernandog What is it what you are looking for in this issue?

**Comment by fernandog** [comment]
@Quiptix sorry didn't understand you

**Comment by Quiptix** [comment]
@fernandog 
I'm afraid we don't understand each other then...
You said: "We are looking others things", so which others and/or things...

**Comment by fernandog** [comment]
all this issues: https://github.com/SiCKRAGETV/sickrage-issues/issues?q=is%3Aopen+is%3Aissue+label%3A%221%3A+Bug+%2F+issue%22

**Comment by Quiptix** [comment]
@fernandog Ok, fair enough!! :)

**Comment by fernandog** [comment]
@Quiptix feel free to help! =)

**Comment by Quiptix** [comment]
@fernandog Surely I want to, however I cannot dedicate the time I should dedicate to it...Probably in the near future and when I have a good IDE for Python on the Mac.
