### ISSUE TITLE
[APP SUBMITTED]: 401 Client Error: Unauthorized

### ISSUE THREAD

**Issue by squareflapjack** [SiCKRAGETV/sickrage-issues#2341]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-44-generic-x86_64-with-elementary_OS-0.3-freya**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@cc698786d1f440ca7017a36ed60831df78ebb391
Link to Log: https://gist.github.com/676ceb4b0ecac6b82690
### ERROR
```
Thread-99 :: Could not connect to Trakt. Code error: 401
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by squareflapjack** [comment]
When I go to the notifications page and click on the Test Trakt button, it says, "Test notice sent successfully to Trakt".
from the log...

AAHTTPError: 401 Client Error: Unauthorized
AA    raise HTTPError(http_error_msg, response=self)
AA  File "/opt/sickrage/lib/requests/models.py", line 834, in raise_for_status
AA    resp.raise_for_status()
AA  File "/opt/sickrage/lib/libtrakt/trakt.py", line 88, in traktRequest
AATraceback (most recent call last):

**Comment by neoatomic** [comment]
@squareflapjack See https://github.com/SiCKRAGETV/sickrage-issues/issues/1732
