### ISSUE TITLE
[Feature Request] Add option for making missing folders visible

### ISSUE THREAD

**Issue by noodles101** [SiCKRAGETV/sickrage-issues#2342]
Please make in the settings the options visible for missing folders.

Settings:
To have sickbeard auto-create folders during post-processing, set:
create_missing_show_dirs = 1

To have SickBeard skip the creation of show folders when you add a new show, set:
add_shows_wo_dir = 1

Details here:
https://code.google.com/p/sickbeard/issues/detail?id=136#c106

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!

**Comment by fernandog** [comment]
http://feathub.com/SiCKRAGETV/SickRage/+58
