### ISSUE TITLE
Sickrage Porcess stop

### ISSUE THREAD

**Issue by jms05** [SiCKRAGETV/sickrage-issues#2343]
Since January i'm running Sickrage on my windows PC (since April) on Windows 10 but in the past 4 or 5 days the Sickrage(python) process stops working every time (i actually with 53 shows), any idea and the web interface is very slow now

**Comment by miigotu** [comment]
Please follow the guidelines for posting an issue, and also make sure you are on the latest commit.

**Comment by neoatomic** [comment]
There where some problems on Windows installations where the sickbeard.db database could get very large. So you might check that.?
There is some more info about it on the news page in SickRage. (the strange characters post.)

And indeed follow the guidelines for posting an issue. : https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket

**Comment by jms05** [comment]
The sickrage folder on may windows is about 1.2GB, i deleted the folder (after backup) downloaded from github restored backup the same thing appens

**Comment by fernandog** [comment]
Read news tab in SR UI

**Comment by fernandog** [comment]
Check your database size
