### ISSUE TITLE
Sickrage running super slow... advice?

### ISSUE THREAD

**Issue by syrys** [SiCKRAGETV/sickrage-issues#2344]
Hey Guys, im having some strange behaviour today. Unsure if sickrage updated last night, but only thing i have done on the machine today was to install utorrent, and link sickrage to use utorrent. I had sickrage running (with qbittorrent) on the machine for months without any issue, but i wanted to try out utorrent today.

Anyhow, when i was trying to plug the utorrent info into sickrage, i realised the SickRage UI was loading pretty slow. Anyway, after few restarts later, sickrage was running even slower and slower... ie, minutes between clicking and the page actually loading.

So, i ran sickrage manually to see any errors were coming out (i realised the sickrage execution even took soo long, used to be pretty instant), there were some errors, but nothing that completely crashed the system. So i re-installed Python thinking maybe python screwed up and all that, did some updates etc to python 2.7.10, and still nothing. Everything running in extra slow mo. I have plenty of unused memory (75% free of 8gb), cpu load at about 35%.

On another note, i also have couchpotato installed on the machine, its also doing the same thing, its actually not even finish loading the app (im guessing its taking far too long to load). 

Any ideas? Yes i have stopped everything, closed all apps, ran things one at a time (only things i have installed on the box is plex, couchpotato, sickrage, chrome, utorrent, qb, and some small apps like dropbox etc...). I cannot to life of me figure out what is up. I can provide any logs if you want, if you think that would help (please let me know where and what to get you). This like is not a SickRage issue, but it could be or if not, someone might be able to help me with suggestions?

TY in advance.

Python Version: 2.7.9 and recently updated to 2.7.10
Operating System: Windows 8.1

**Comment by neoatomic** [comment]
There where some problems on Windows installations where the sickbeard.db database could get very large. So you might check that. 
There is some more info about it on the news page in SickRage. (the strange characters post.)

**Comment by syrys** [comment]
@neoatomic, oh yes, 7GB db file, goodie. cant even update, because it gives me an error saying couldnt backup the config file, so it stops the update. Let me do a backup and do a manual git pull.

**Comment by syrys** [comment]
````
please FULL update & refresh all your shows and force a mass rename after
````
Im not following the step "refresh all your shows", what do they mean by this, and how do i do this?

**Comment by fernandog** [comment]
Re-scan. Will update it soon in NEWs

**Comment by syrys** [comment]
what ever that happened during the day, all is running fast again, but my database file is still at a good 7GB. I have a backup DB file from like 4 days ago, and that is only 14MB (and no, i havent added 500x content into my db).

The size doesnt bother me, i have plenty of HDD space, just that im a little worried that this might get out of hand, or next time i restart, the db might take forever to open/index or what ever it needs to do.

**Comment by fernandog** [comment]
Please read NEWs

**Comment by syrys** [comment]
@fernandog, i have done all that was mentioned, im not sure what else you are referring to in the News section?

I mean, i dont have any noticeable issues anymore besides the HUGE database file.

**Comment by fernandog** [comment]
Did try to do that do reduce your DB size?
average is MB database. No GB

**Comment by syrys** [comment]
@fernandog
all i did was to follow the instructions from the News page. update, refresh, rename.
2 or 3 days ago, my db was 14MB, today my db was 7GB (7000MB, no its not a typo). Even after the update/refresh/rename, the db remains at 7GB. No new shows were added by me in the last 2-3 days.

**Comment by fernandog** [comment]
are you running the latest update of SR?

**Comment by syrys** [comment]
@fernandog
well, i updated, and there are no more updates. 

this look right?
````
SR Version:	BRANCH: (master) / COMMIT: (6831ae9131af765586c1d348cc1835f363f350ce) 
SR Locale:	('en_US', 'cp1252')
Python Version:	2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
````

**Comment by fernandog** [comment]
yes.
@miigotu windows user still need to run 'chcp 65001' ? or cp1252 is still valid?

**Comment by miigotu** [comment]
1252 is fine unless he has problems.

With the encoding changes we talked about earlier, no one will ever have to change locale. SO much work though

**Comment by fernandog** [comment]
@syrys are you sure you did all steps?  No SR crash while processing?

There is not reason to no work.

**Comment by syrys** [comment]
here is exactly what i did:

1. browse to the Sickrage folder on command line and execute "git pull".
2. run sickrage and wait for the UI to load
3. navigate to manage->massupdate on the menu, check update column header above all the shows (which ticks the update column on all shows), and click submit on bottom right.
4. after a while, navigate to massupdate screen again, then check the rescan column header, and click submit on the bottom right.
5. after another while, navigate to massupdate screen, check rename column header and click submit on the bottom right. 

NOTE:
1. when you check the update column header or rescan column header, it only checks the "continuing" shows, so any shows that are ended, you cant really check them.
2. i have no idea if the above steps passed or failed due to some error, is there an easy way to check?
3. i realised there was an update today, which i tried to do using the sickrage ui, but i get the following error (im sure i could simply use the git pull method to update if need be):
````
2015-07-28 14:32:51 Thread-245 :: Zip creation error: Filesize would require ZIP64 extensions
2015-07-28 14:32:51 Thread-245 :: Config backup failed, aborting update
````

**Comment by miigotu** [comment]
zib64 extensions were enabled like 3 weeks ago.

**Comment by syrys** [comment]
well, is there a way i can manually do it? or what do you recommend i do?

**Comment by miigotu** [comment]
You're using git for version control right?
Just open the git bash and cd to the SickRage dir and `git reset --hard && git pull`

**Comment by syrys** [comment]
ok, done that, now im doing the episode update/rescan/rename, will get back to you if this makes the DB smaller.

Not sure if this is worth mentioning, but at first glance, i saw an error on the command line when i started the update/rescan/rename processes:

````
18:14:26 INFO::SHOWQUEUE-FORCE-UPDATE :: Launching backlog for this show since w
e found missing episodes
18:14:48 WARNING::SEARCHQUEUE-BACKLOG-274431 :: Unknown exception in getURL http
://kat.cr/gotham-season-1-complete-1080p-web-dl-dd5-1-h-264-yfn-t10604525.html E
rror: Exceeded 30 redirects.
18:14:48 WARNING::SEARCHQUEUE-BACKLOG-274431 :: Traceback (most recent call last
):
  File "C:\SickRage\sickbeard\helpers.py", line 1364, in getURL
    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=sessio
n.verify)
  File "C:\SickRage\lib\requests\sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "C:\SickRage\lib\requests\sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\SickRage\lib\requests\sessions.py", line 602, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\SickRage\lib\requests\sessions.py", line 114, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects)
TooManyRedirects: Exceeded 30 redirects.
````
im assuming this is no biggie. ill update again in couple of hours.

**Comment by syrys** [comment]
still the db file is 7GB

**Comment by syrys** [comment]
on another note, now there there is another update today, that zip creating error is back (so i cannot do the updates still via the UI):

````
2015-07-30 07:13:43 CHECKVERSION :: Zip creation error: Filesize would require ZIP64 extensions
2015-07-30 07:13:43 CHECKVERSION :: Config backup failed, aborting update
````

**Comment by WebSpider** [comment]
Your zip64 error should be fixed since https://github.com/SiCKRAGETV/SickRage/commit/ebbd67fec6586fbb9f4d9122a17ddf1047a49147 ... Please check and confirm, thanks :)

**Comment by syrys** [comment]
@WebSpider Here is my helpers.py file:
https://www.dropbox.com/s/wc8tt7vu471hqfu/helpers.py?dl=0

`allowZip64=True` appears in one place, but not the others. 

What do you suggest i do?

**Comment by fernandog** [comment]
Update SR!

**Comment by WebSpider** [comment]
+1 on the update

**Comment by syrys** [comment]
updated using `git pull`, did the mass update, rescan, rename, database still at 7gb :(

````
SR Version:	BRANCH: (master) / COMMIT: (47b2d5651f0c7ef1d8d20523dee85bc950d17e14) 
SR Locale:	('en_US', 'cp1252')
````

**Comment by WebSpider** [comment]
The database probably has a lot of empty space in it now.

You can release this by stopping SR, going into the SR dir, opening the DB and issueing the VACUUM command like this:

````
sqlite3 .\sickbeard.db
VACUUM;
<wait until the prompt returns>
<CTRL-C>
````
Start SR again

**Comment by fernandog** [comment]
@WebSpider can we run this always before starting SR - or after db files > x MB/GB ? or isn't recommended?
