### ISSUE TITLE
[APP SUBMITTED]: POSTPROCESSER :: Automatic post-processing attempted but dir /mnt/downloads/DONE/tvshow doesn't exist

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2348]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-57-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@cc698786d1f440ca7017a36ed60831df78ebb391
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Automatic post-processing attempted but dir /mnt/downloads/DONE/tvshow doesn't exist
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by OmgImAlexis** [comment]
Since I use this in VirtualBox with rc.local mounting shared folders I find that sickrage gets started literally seconds before the drive mounts.
Is there anyway to possibly have this check delayed for virtual machines or something similar to that?

**Comment by miigotu** [comment]
put a delay in your SickRage init script.
