### ISSUE TITLE
[APP SUBMITTED]: No module named OpenSSL.version

### ISSUE THREAD

**Issue by j5james** [SiCKRAGETV/sickrage-issues#2349]
### INFO
Python Version: **2.7.3 (default, Mar 31 2015, 22:10:50) [GCC 4.9.2]**
Operating System: **Linux-3.17.8-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@
Link to Log: https://gist.github.com/67dcb985d58d1f1843d2
### ERROR
```
MAIN :: Check scene exceptions update failed. Unable to get URL: https://raw.githubusercontent.com/SiCKRAGETV/sr_tvrage_scene_exceptions/master/exceptions.txt
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Install Pyopenssl. 
In case you are using a qnap. : http://apps.qnap.community/11-community/17-qsickrage

**Comment by j5james** [comment]
Im using openelec, how do i do this?

**Comment by neoatomic** [comment]
Cant say for sure, as it also depends on your openelec version. etc.
Best to ask on the openelec forums. Did a quick search and there are multiple topics about how to add this.They probably have a package for that. Should not me to hard to find/install.

http://openelec.tv/forum/
