### ISSUE TITLE
Restore function not working

### ISSUE THREAD

**Issue by forza11** [SiCKRAGETV/sickrage-issues#2350]
BRANCH: (master) / COMMIT: (ac27935188e351a7ffd869ff1555767987f62ce3) 
Python Version: 2.7.10 (default, Jun 3 2015, 13:42:00) [GCC 4.6.4]
Synology 413j, DS5.2

I want to migrate from sickrage / sickbeard custom (A) to the sickrage (B) synology package. Both installs have the same commit version. I backed up install A, tried the restore but it failed due to wrong permissions. I changed those, import now works but nothing happens after the restart. 

I also tried to manually extract the .zip to a Restore folder and than reboot but the result is the same. 

Log file from the normal restore process: 
https://gist.github.com/forza11/59bd80849994ab5fc4e2

**Comment by miigotu** [comment]
@forza11 the built in restore function is creating zips that have paths in them. You just need the config file and the sickbeard.db, and copy over the ones in the new location (while SR is stopped)

**Comment by forza11** [comment]
thanks, I'll try that when i get home (missing a webconsole....)

**Comment by forza11** [comment]
I can't seem to get this to work. I tried copying the sickbeard.db and config file to the installation i tried to restore to earlier, but it fails to run the package after the 2 files are moved over. I edited all the permissions, also in the ' old' folder containing all the images etc. (just in case it wants to do something there). When that didnt work either i removed sickrage and installed it again, moved over the .db and config file to the new installation but again it fails to start. 

There isnt any log i can show so not sure where to look. Any ideas?

**Comment by miigotu** [comment]
try without the ini

**Comment by forza11** [comment]
This just doesn't seem to work, it fails to start if I only copy the dbase file. But i believe it won't work because all paths in the database are still pointing to the old location so a migration to a new install simply won't work with this system. I simply have to start from scratch.
