### ISSUE TITLE
[Feature Request] Unrar: extract directly in the TV Shows dir

### ISSUE THREAD

**Issue by Anthony25** [SiCKRAGETV/sickrage-issues#2351]
Hello,
When extracting, unrar uses the "TV Download Dir" as cache and then copies the extracted files in the TV Shows directory. Would it be possible to add an option to directly use the TV Shows dir when extracting the files (or use a cache directory) ?

In my setup, my torrents download dir is not writable for anyone except for the user "transmission", to protect the torrents which are seeding and avoid any modification. It's incompatible with how unrar is used in Sickrage, because it cannot write in it.

Thanks !

**Comment by neoatomic** [comment]
I'm a little skeptical about your request. Think its better to do all actions in 1 folder (the tv download dir) to prevent errors (permission and running out of space etc.) 
Also this would require some code changes that are not easy to do...

**Comment by Anthony25** [comment]
I see. Well if your goal is to prevent errors, doing it directly in the target path would do the trick too, even more than the actual way: anyway, if you don't have the permissions or the free space in this directory, you can't copy the extracted files in it.

But if it requires too many changes, I understand the "won't fix" ;)

**Comment by neoatomic** [comment]
@Anthony25 This would get very complicated to implement, and a good chance it would introduce a lot of new bugs.
But if you see a way, and are able to compile the code yourself you are always welcome sent a Pull Request.

**Comment by fernandog** [comment]
PP is the one that knows where to move/file file.
