### ISSUE TITLE
[Feature Request] Mass Update for Fansub Groups

### ISSUE THREAD

**Issue by lqid10t** [SiCKRAGETV/sickrage-issues#2353]
I just ran into this problem, where for some reason, all of my Fansub groups had been wiped out from all of my anime. Because of this, Sickrage started downloading higher quality BluRay formatted episodes in other languages. Can we get an option to Mass Update the Fansub groups in case this happens, or when we add a bunch of new anime?

**Comment by lqid10t** [comment]
Also, being able to choose from other Fansub groups you have already entered for other anime would be awesome.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
