### ISSUE TITLE
Duplicate downloads of the same episode from different providers

### ISSUE THREAD

**Issue by Rouzax** [SiCKRAGETV/sickrage-issues#2354]
SR Version:		BRANCH: (master) / COMMIT: (6831ae9131af765586c1d348cc1835f363f350ce) 
SR Locale:		('nl_NL', 'cp1252')
Python Version:	2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]
OS:				Windows Server 2012R2

With the latest Master GIT version there seem to be duplicate downloads:
![image](https://cloud.githubusercontent.com/assets/4103090/8900989/63ebf258-3445-11e5-88a8-43dee59b968c.png)

Link to log: https://gist.github.com/Rouzax/fff54eeac6ca05e08ea6

**Comment by Yellow1144** [comment]
SR is also snatching all today's already downloaded shows again as propers when no propers exist. According to the log it seems to be happening during a FindPropers event. I saw it in the log but so much is going on with SR now that file was overwritten before I could copy the log info.

**Comment by Morphello** [comment]
Can confirm this behavior as well. Proper search is downloading alternative versions (not propers) of the same episodes after completion. This is happening with the same provider.

SR Version: 	BRANCH: (master) / COMMIT: (6831ae9131af765586c1d348cc1835f363f350ce) 
Python Version:	2.7.9 (9c4588d731b7, Mar 23 2015, 20:00:36) [PyPy 2.5.1 with MSC v.1500 32 bit]

**Comment by neoatomic** [comment]
Ok, So this issue looks to be isolated to the Windows OS.
You all have `FindPropers` enabled.? 

@Yellow1144 @Morphello Can you also post logs with debug = 1 enabled in the settings.? 
The more info we have the easier to locate a problem

**Comment by Rouzax** [comment]
@neoatomic I have FindPropers enabled, let me know if you need anything.

**Comment by chimii** [comment]
This is happening to me , and I'm not running windows 

I also have FindPropers enabled

SR Version:	BRANCH: (master) / COMMIT: (6831ae9131af765586c1d348cc1835f363f350ce) 
SR User:	pi
SR Locale:	('en_GB', 'UTF-8')
SR Config file:	/home/pi/.sickrage/config.ini
SR Database file:	/home/pi/.sickrage/sickbeard.db
SR Cache Dir:	/home/pi/.sickrage/cache
SR Log Dir:	/home/pi/.sickrage/Logs
SR Arguments:	['-q', '--daemon', '--nolaunch', '--pidfile=/var/run/sickbeard/sickbeard.pid', '--datadir=/home/pi/.sickrage']
Python Version:	2.7.9 (default, Mar 8 2015, 00:52:26) [GCC 4.9.2]

This is debian 8 on a raspberry pi  

This is all I have on my Logs folder: https://dl.dropboxusercontent.com/u/4823640/sickrage.zip

I disabled findpropers to test tonight.

**Comment by Rouzax** [comment]
Just had a duplicate download for The Brink.
Log: https://gist.github.com/Rouzax/bbcab88aff2b51a4304b

**Comment by Yellow1144** [comment]
@neoatomic 
Yeah, I have Download Propers set. I do not have any log data as the relevant data was overwritten due to activity last night. I will have to wait for tonight's DLs to happen.

**Comment by miigotu** [comment]
Should be fixed in develop. When a non-proper is returned from the provider code you will get a warning log line and it will be skipped. Please tell me which providers you get this warning from so I can fix it directly in the provider.

**Comment by Rouzax** [comment]
@miigotu in my case it was TorrentDay and KickAss

**Comment by chimii** [comment]
My re-downloads are from KickAss,
