### ISSUE TITLE
Unable to start SickRage on Synology DiskStation DS412+

### ISSUE THREAD

**Issue by Valiante** [SiCKRAGETV/sickrage-issues#2356]
**INFO**

<pre>SR Version:       BRANCH: (master) / COMMIT: (365ceae509ce1c5a6c886e0471a9a4a18bddc49c) 
SR User:          sickrage
SR Locale:        (None, None)
SR Config file:   /usr/local/sickrage/var/config.ini
SR Database file: /usr/local/sickrage/var/sickbeard.db
SR Cache Dir:     /usr/local/sickrage/var/cache
SR Log Dir:       /usr/local/sickrage/var/Logs
SR Arguments:     ['--daemon', '--pidfile', '/usr/local/sickrage/var/sickrage.pid', '--config', '/usr/local/sickrage/var/config.ini', '--datadir', '/usr/local/sickrage/var/']
Python Version:   2.7.10</pre>

**LOG**

http://pastebin.com/W1gbM3PZ

**ISSUE**

I noticed today I was unable to browse to the SickRage web interface, getting a standard "page cannot be displayed" error in the browser.  I found in the Synology Package Center that SickRage is "Stopped".  If I click Action, Run it says "Loading..." for a few seconds, but remains "Stopped".

**Comment by neoatomic** [comment]
Probably the installation got corrupt. Can happen...
Easiest way is to backup the sickbeard.db and confg.ini file, and then remove/reinstall SickRage in the package center. (Or if you know how do a Git reset that also does reinstall SR).

When you have reinstalled SickRage shut it down in the package center, overwrite the 2 backup'd files and restart Sickrage. And all should be as it was before.

**Comment by Valiante** [comment]
Thanks.  I'm assuming the correct procedure for a Git reset is as per the **Before You Open An Issue** section on https://github.com/SiCKRAGETV/sickrage-issues?

<pre>git remote add upstream https://github.com/SiCKRAGETV/SickRage.git
git fetch upstream
git checkout master
git branch -u upstream/master
git reset --hard upstream/master
git pull</pre>

Perhaps I should have tried that...  before I opened an issue... :\

**Comment by neoatomic** [comment]
Normally yes, but on a Synology that can be a little tricky. Here is a short explanation.

```
SSH to your synology (enable ssh on your synology DSM)
go to the sickrage folder /@appstore/sickrage/var/sickrage/
start command: git pull
if git can't be found: /usr/local/git/bin/git pull (if the git file is on the standard location)
```

**Comment by Valiante** [comment]
I use GateOne Terminal Emulator from the SynoCommunity repository, which makes life a little easier.  I carried out all of the above with the full path to git, copied the two files back and rebooted.  SickRage is now back up and running.

Many thanks.
