### ISSUE TITLE
[APP SUBMITTED]: __str__ returned non-string (type SysCallError)

### ISSUE THREAD

**Issue by pablogiganti** [SiCKRAGETV/sickrage-issues#2358]
### INFO
Python Version: **2.7.10 (default, Jul  8 2015, 08:04:18) [GCC 4.3.6]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@8f6f619538d48af1c3429f2a2109b47fa737c5a7
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-75897 :: [TorrentLeech] :: Error while searching TorrentLeech, skipping: __str__ returned non-string (type SysCallError)
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@pablogiganti Please add logs. Without we cant do anything...

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:34:55) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-26-generic-i686-with-Ubuntu-15.04-vivid**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@28d7f48ff513ae739aebc337ce0005f76f9a4acd
Link to Log: https://gist.github.com/fce7a07fbc869ad9889e
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: __str__ returned non-string (type SysCallError)
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
@duramato that is a bug in SSL or OpenSSL. It means the client did not respond correctly, there was an ssl problem, or some other connection issue. We cant really fix it.

Fix your plex connection maybe?

**Comment by duramato** [comment]
@miigotu is on the same machine and isnt using https which is  odd if its a ssl issue 
also i use localhost:32400 for its ip

**Comment by alisonatwork** [comment]
@miigotu / @duramato I also have hit this error. I don't think it is an OpenSSL bug, I think it is a CacheControl or Request bug. Somewhere along the way, it is creating an object (probably response object) that has a __str__ representation that doesn't return a string but returns the OpenSSL exception instead. Then that throws a TypeError when we try to print it out, which we catch and pretend it's a SocketTimeout. At which point we lost the original exception.

**Comment by miigotu** [comment]
Its requests, passing back the underlying exception from socket wrapped as an argument in it's own exception

**Comment by alisonatwork** [comment]
That's what I initially thought, but when I ran the unit test passing ex(Exception(Exception())) it still worked fine. Also, calling str(Exception()) or Exception().__str__() did not show the same error. The only way I could trigger it was to explicitly override __str__ to return an exception instead of a string, which is a really big bug. But it's not in sickrage so meh :p
