### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/volume1/Torrent/the.vampire.diaries.601.hdtv-lol.mp4'

### ISSUE THREAD

**Issue by sverleysen** [SiCKRAGETV/sickrage-issues#2359]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 23:30:53) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@6831ae9131af765586c1d348cc1835f363f350ce
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@sverleysen have you manually started a PP?

**Comment by sverleysen** [comment]
Hi,

I did some PP today, but I didn't know if that triggered the error. I just
noticed the error.
Probably it was due to a PP.

2015-07-27 15:09 GMT+02:00 Fernando <notifications@github.com>:

**Comment by fernandog** [comment]
probably you started a manual PP and after that when auto PP started file was already PP
