### ISSUE TITLE
FINDPROPERS is pulling duplicates that are worse then the Initital snatch

### ISSUE THREAD

**Issue by mariothiel** [SiCKRAGETV/sickrage-issues#2361]
Hey guys since I added torrents to my sickrage setup I am having problems with it snatching duplicates of episodes, that I already have. SR Labels those as PROPER Releases, with no sign of them being that at all... No, those new releases are even worse then my old once. [I attached a log to pastebin] (http://pastebin.com/bkYLzXBg)

**Comment by neoatomic** [comment]
@mariothiel Its already reported. for now disable the findproper setting in the configuration. 
Please add the log etc to. https://github.com/SiCKRAGETV/sickrage-issues/issues/2354
