### ISSUE TITLE
XPenology; can't add full path for TV directory

### ISSUE THREAD

**Issue by PepsiBlue14** [SiCKRAGETV/sickrage-issues#2364]
I'm trying to add my existing TV directory but I can't click deep enough to select the root directory. The directory is located in:
/volume1/RAID/TV

But I can only navigate to /volume1/RAID

BRANCH: (master) / COMMIT: (ba5f61461bd5c0a2b7b05790a80cc74217859a4a)

**Comment by miigotu** [comment]
the permissions for your TV folder do not allow the user running SR to read it.

**Comment by PepsiBlue14** [comment]
Thanks for the quick response. How can I tell which user is running SR?

**Comment by miigotu** [comment]
`ps aux | grep -i sick`

**Comment by miigotu** [comment]
Or in the tools->help & info.

**Comment by PepsiBlue14** [comment]
Thanks. If I wanted to configure an account for SR to use, how would I configure SR to use my newly created account?

**Comment by miigotu** [comment]
I'm not sure how DSM works, but in the service configuration file.

**Comment by Vodka2014** [comment]
I had the same issue. So in your Synology you need to give ur whole drive VolumeX Read + Write Permissions for User. Once this is done you can access you data and set them up as a location.

as SickRage needs R+W to work on your folders.

**Comment by adaur** [comment]
Let us know if your issue isn't fixed after Vodka's instructions.

**Comment by PepsiBlue14** [comment]
I read in another forum that giving the sc-media group access would do the trick. That's what I ended up doing to fix the issue.
