### ISSUE TITLE
Images on the history page 404

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2365]
All images on the history page 404, [screenshot](https://cloud.githubusercontent.com/assets/6525926/8923949/26a328e8-353b-11e5-8f58-d6377d839f00.PNG).

### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-57-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@ba5f61461bd5c0a2b7b05790a80cc74217859a4a
No Log available with ERRORS: 
### ERROR
```
Traceback (most recent call last):
  File "/home/media/sickrage/tornado/web.py", line 1348, in _execute
    result = yield result
  File "/home/media/sickrage/tornado/gen.py", line 807, in run
    value = future.result()
  File "/home/media/sickrage/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "/home/media/sickrage/tornado/gen.py", line 212, in wrapper
    yielded = next(result)
  File "/home/media/sickrage/tornado/web.py", line 2126, in get
    self.root, absolute_path)
  File "/home/media/sickrage/tornado/web.py", line 2305, in validate_absolute_path
    raise HTTPError(404)
HTTPError: HTTP 404: Not Found
```

**Comment by neoatomic** [comment]
What is the link of the broken images.? 
Try a Git reset , with a little luck that would fix it.

**Comment by OmgImAlexis** [comment]
Anything that goes to a url similar to this ``/images/subtitles/ECI.png``.
I get this with the IP and dnsmasq so it's not that. I'll try a git reset and get back to you.
Also Rarbg, Kickass and ThePirateBay don't seem to be affected by this as they're showing up fine.

![urls](https://cloud.githubusercontent.com/assets/6525926/8927634/2e8fc1a8-355c-11e5-85e1-42b95e110f80.PNG)

**Comment by neoatomic** [comment]
Those links are not generated correctly and therefor not working. Not sure how that can even happen...
Did you modify any code, or are you using some external scripts.?

So see if a Git Reset helps, otherwise it might be a bug that we need to look into.

**Comment by OmgImAlexis** [comment]
Nope, it seems to be marking them as subtitles even though they're not. Really if anything they should be showing up as providers.
I'm running a completely stock install on the latest master commit.

Also I'm using dnsmasq for the ``media.tardis`` domain. They show up incorrectly when I connect to SickRage via IP too.

**Comment by fernandog** [comment]
@miigotu known issue isn't? It should ignore mkv files when list files (subtitle files)

**Comment by miigotu** [comment]
Not sure yet, I don't see this on mine.

**Comment by fernandog** [comment]
@OmgImAlexis does it show which javascript file this error happens?

**Comment by fernandog** [comment]
compact view or detailed view?

**Comment by miigotu** [comment]
@OmgImAlexis what status/action is this for? subtitled/snatched/downloaded ?

**Comment by miigotu** [comment]
We dont use images for release groups in "Downloaded" action:

![image](https://cloud.githubusercontent.com/assets/390379/8948170/f22476da-3558-11e5-9d8f-f417b9fe589a.png)

**Comment by fernandog** [comment]
if is that the issue we can stop SR trying to access those "images" as they don't exist

**Comment by miigotu** [comment]
It doesnt try to access them here.

**Comment by miigotu** [comment]
Possibly her history table in the db has somehow changed only the status column to snatched for items that are supposed to be action downloaded. That's the only explanation I can think of.

**Comment by OmgImAlexis** [comment]
Sorry I just got on, stupid emails didn't come through till now.

It seems to only show up for archived episodes, I never noticed it before but also never had archived episodes show up before so that kind of confirms that.
It's showing up in the history table in detailed layout. Let me know what else you need.

![t](https://cloud.githubusercontent.com/assets/6525926/8954905/119228a4-362c-11e5-910d-f36317899341.PNG)
![as](https://cloud.githubusercontent.com/assets/6525926/8954920/23172fb6-362c-11e5-9cee-11ff4e39ed39.PNG)

**Comment by miigotu** [comment]
K i found that, will commit in awhile.

**Comment by OmgImAlexis** [comment]
@miigotu alright.

I noticed with a Download Dimension gets capitalised and put inside of a <i> tag but with Archived it's only got a capital at the start and an icon.
Can we get that standardised, one way or the other?

**Comment by OmgImAlexis** [comment]
![see](https://cloud.githubusercontent.com/assets/6525926/8955843/a100d1b4-3633-11e5-8b17-fd34a854308e.PNG)

**Comment by miigotu** [comment]
Yes when I fix it it will look just like a Downloaded item.
