### ISSUE TITLE
Failed to backlog, cannot add wanted show to DL anymore (log inside)

### ISSUE THREAD

**Issue by CorB3n** [SiCKRAGETV/sickrage-issues#2367]
When SR trying to backlog missed episodes or when I click on Wanted on it, here is what I have in logs:
```
2015-07-27 21:35:05 INFO     POSTPROCESSER :: PostProcessing Path: /volume2/downloads/complete/_tv
AA
AAImportError: No module named generic
AA    from .generic import GenericClient
AA  File "/volume2/@appstore/sickrage/var/SickRage/sickbeard/clients/download_station_client.py", line 24, in <module>
AA    return __import__(prefix + name + '_client', fromlist=__all__)
AA  File "/volume2/@appstore/sickrage/var/SickRage/sickbeard/clients/__init__.py", line 114, in getClientModule
AA    module = getClientModule(name)
AA  File "/volume2/@appstore/sickrage/var/SickRage/sickbeard/clients/__init__.py", line 118, in getClientIstance
AA    client = clients.getClientIstance(sickbeard.TORRENT_METHOD)()
AA  File "/volume2/@appstore/sickrage/var/SickRage/sickbeard/search.py", line 137, in snatchEpisode
AA    self.success = search.snatchEpisode(result)
AA  File "/volume2/@appstore/sickrage/var/SickRage/sickbeard/search_queue.py", line 146, in run
2015-07-27 21:25:12 INFO     SEARCHQUEUE-DAILY-SEARCH :: Downloading Ballers.2015.S01E06.720p.HDTV.x264-0SEC[rartv] from Rarbg
```
(from bottom to top)

Stucked now, forced to go to website & download .torrent file.

**Comment by miigotu** [comment]
ssh in,
```
cd /volume2/@appstore/sickrage/var/SickRage
git reset --hard
git pull
```

**Comment by CorB3n** [comment]
No other way, into SR config for example ? I'm so weak on SSH look:

Could not chdir to home directory /var/services/homes/admin: No such file or directory

DiskStation> cd /volume2/@appstore/sickrage/var/SickRage
DiskStation> git reset --hard
-sh: git: not found

**Comment by neoatomic** [comment]
The other 2 options are copy over the files manually, but you still need to use ssh. (try winscp its more user friendly)
https://github.com/SiCKRAGETV/SickRage/archive/master.zip

Or the easy way,  backup and remove the SickRage package from the Package center and reinstall.

**Comment by CorB3n** [comment]
I tried this morning and completely fucked up my DSM, lol. Forced to full reinstall, very bad news & lot of time wasted. Good news is it's working now. Question is : isolated issue, or other ppl have it ? What was the problem ? Thks

**Comment by miigotu** [comment]
There was a commit awhile back that had to remove some stale pyc files and files that git did not remove fore some reason when I renamed then in a previous commit because those file were causing errors. The reason they weren't autoremoved by python itself was because the clients are loaded dynamically.

This commit to manually remove them in SR code accidentally also removed generic.py.
The next commit fixed that but users needed to git reset --hard and git pull in order to restore the missing generic.py if they happened to fall into the one commit where it was removed by accident.
