### ISSUE TITLE
Force Full Update not updating NFO files?

### ISSUE THREAD

**Issue by wimpyrbx** [SiCKRAGETV/sickrage-issues#2368]
For some reason it seems that Full Force Update does not replace information in NFO for episodes.
Is it not supposed to do that?

I manually edited a NFO and put in some bogus data and then did Force Full Update on the show. It ran through the update, but no change to the NFO file.

However if I delete the NFO and run a Force Full Update it will create a new NFO with updated information.

Am I overlooking something here?

**Comment by miigotu** [comment]
i assume someone did not want to overwrite watched states. maybe it can be improved.

**Comment by wimpyrbx** [comment]
with watched states what do you mean?

**Comment by miigotu** [comment]
Kodi saves whether you watched a video or not in the NFO when you export your library to separate files, so that when you re-import it still knows if you watched it already or not.

**Comment by wimpyrbx** [comment]
Yes well i've now tried with both watched and non-watched tags in the nfo and same result.

**Comment by miigotu** [comment]
You're misunderstanding what I'm saying. SickRage is not programmed to overwrite existing NFO because there may be information in the NFO that should not be overwritten. The watched status is only an example of some data that should not be overwritten.

**Comment by wimpyrbx** [comment]
ok so it might be that SR is not updating Episode Title in existing NFO files?
so to be 100% sure to get a show 100% refreshed from SR is to actually delete all NFO files before running "Force Full Update"?

One note here, when using a word like "Force" to a task like "Full Update" it kinda seems strange it does not overwrite existing information in NFO files?

**Comment by miigotu** [comment]
Full update has nothing to do with NFO files. It is forcing a full update of the SickRage database from the web indexers.

Regardless I'll look into adding the feature if updating existing NFO files.

**Comment by wimpyrbx** [comment]
cheers :+1:

**Comment by papampi** [comment]
@miigotu while you gonna work on NFO files is it possible to add missed tumbs or refresh old ones too ?

**Comment by miigotu** [comment]
I'll try and make it update all info possible, but it is gonna be awhile as this is not a priority atm.

**Comment by papampi** [comment]
no rush mate, thanks for every thing.

**Comment by wimpyrbx** [comment]
thanks for adding to the list. no rush as papami says.
love the activity on SR :+1:

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!

**Comment by fernandog** [comment]
@OmgImAlexis @miigotu I think this is the reason why it's not updating metadata:

https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/show_queue.py#L497

**Comment by miigotu** [comment]
@fernandog PR to uncomment that? I think @echel0n had that commented during his testing a fix over a year ago (so his meta wasnt overwritten while testing and it didnt take so long) and it accidentally got committed.
