### ISSUE TITLE
Calling Deluge Client - TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by PaulW** [SiCKRAGETV/sickrage-issues#2369]
Branch: Master
Commit Hash: 1ec701e4c12b41d1a34f01ad6091b1fec09967a3
OS: Debian 8.1 Jessie
Python: Python 2.7.9
What I did:  Performed any kind of search, whether backlog or manual.
What Happened:  Failed to connect to Deluge & upload the torrent.
What you expected:  Torrent to be uploaded to Deluge

Trying to perform either a Manual search or Backlog, SickRage will happily go off & connect to torrent sites, but then fail to connect to deluge & upload what it has found.

I've checked the connection between the VM running SickRage and the VM running Deluge, all of which are fine.  I can manually connect from the SR VM to Deluge via CURL, however, SR returns the following error:
```
2015-07-28 09:44:55 DEBUG    SEARCHQUEUE-MANUAL-80379 :: Calling Deluge Client
2015-07-28 09:44:55 DEBUG    SEARCHQUEUE-MANUAL-80379 :: Traceback (most recent call last):
  File "/opt/SickRage/sickbeard/search_queue.py", line 184, in run
    self.success = search.snatchEpisode(searchResult[0])
  File "/opt/SickRage/sickbeard/search.py", line 138, in snatchEpisode
    dlResult = client.sendTORRENT(result)
  File "/opt/SickRage/sickbeard/clients/generic.py", line 177, in sendTORRENT
    if not self._get_auth():
  File "/opt/SickRage/sickbeard/clients/deluge_client.py", line 68, in _get_auth
    if len(hosts) == 0:
TypeError: object of type 'NoneType' has no len()
```
I've removed all pre-compiled .pyc files, done a full fresh clone & copy but to no avail.

I'm not even seeing any attempted connection coming from SR to the Deluge host.  Nothing shows in any logs within Deluge indicating a connection attempt, or within the Apache layer either.  SR just fails completely when it's supposed to be connecting.

Checking the Connection within Settings, returns the following:

Error: Unable to connect to Deluge

Thanks

**Comment by PaulW** [comment]
Little more info.  I've increased the verbosity at which connections are logged, I can now see connections going from SR to Deluge, however it appears the initial GET is failing.

 - [28/Jul/2015:10:03:12 +0100] "GET /json HTTP/1.1" 405 4209 "-" "python-requests/2.6.0 CPython/2.7.9 Linux/3.16.0-4-amd64"
 - [28/Jul/2015:10:03:12 +0100] "POST /json HTTP/1.1" 200 520 "-" "python-requests/2.6.0 CPython/2.7.9 Linux/3.16.0-4-amd64"
 - [28/Jul/2015:10:03:12 +0100] "POST /json HTTP/1.1" 200 443 "-" "python-requests/2.6.0 CPython/2.7.9 Linux/3.16.0-4-amd64"
 - [28/Jul/2015:10:03:12 +0100] "POST /json HTTP/1.1" 200 443 "-" "python-requests/2.6.0 CPython/2.7.9 Linux/3.16.0-4-amd64"

Checking the webui logs, I can see the request:

[DEBUG   ] 10:12:35 json_api:255 json-request: {"params": ["*********"], "method": "auth.login", "id": 1}
[DEBUG   ] 10:12:35 auth:199 Received a password via the 1.2 auth method
[DEBUG   ] 10:12:35 auth:146 Creating session for admin
[DEBUG   ] 10:12:35 json_api:255 json-request: {"params": [], "method": "web.connected", "id": 10}
[DEBUG   ] 10:12:35 json_api:255 json-request: {"params": [], "method": "web.get_hosts", "id": 11}

No idea why this has suddenly stopped working...

**Comment by miigotu** [comment]
Remove the settings for it and re-add them. Delete cache/sessions/* (with SR stopped) and try again

**Comment by PaulW** [comment]
Unfortunately that doesn't resolve this, I get the same exact error.

I've even trie completely removing SR & doing a fresh install with no joy.  Looking at the logs, it looks as though this failed around the 25th of July, the only updates which are automatically applied are those associated with SR (I have the option selected to automatically update every 12 hours).  Nothing else (firewall, server, deluge, etc) has changed during this time.

**Comment by miigotu** [comment]
I'll have to install deluge and test it myself. Just the normal setup right?

**Comment by miigotu** [comment]
Ok, I have installed and tested with deluge, and it works just fine. Here is what I did:

I wasn;t sure about how to set up deluged so I tested with the gui version
`sudo apt-get install deluge deluge-web`

Opened deluge, went to preferenced->plugins and enabled web ui
went to webUI in left side of preferences and checked `Enable web interface`

checked in browser that the webui was working by going to http://localhost:8112 (I didnt change the port) and logged in using the default password "deluge"

Went to the search settings in SR and picked deluge and entered the http://localhost:8112 as the host and deluge as the password, clicked test, got "Connected and Authenticated", clicked SAVE.

Went and did a manual search and file successfully snatched and sent to deluge.

**Comment by miigotu** [comment]
Note I did not use the option in deluge webUI config "Enable SSL", because with that enabled even chrome cannot connect to the webUI.

**Comment by PaulW** [comment]
Unfortunately this is the same setup/config I have also tested, which does not work.  I'm wondering if there is some unknown dependency which I may be missing from the install?  Perhaps an issue with Debian 8.1 default install.

**Comment by miigotu** [comment]
Can you open the deluge web ui in a browser?

**Comment by PaulW** [comment]
Yes, I can connect via webui just fine.  I can also send manual REST requests just fine which receive responses.

It looks as though the following requests from SR return nothing:

{"params": [], "method": "web.connected", "id": 10}
{"params": [], "method": "web.get_hosts", "id": 11}

This is the results from deluge_client.py script:

POST: {"params": ["********"], "method": "auth.login", "id": 1}
RESP: {"id": 1, "result": true, "error": null}
POST: {"params": [], "method": "web.connected", "id": 10}
RESP:
POST: {"params": [], "method": "web.get_hosts", "id": 11}
RESP:

When manually doing a REST request, I get the following:

POST: {"params": ["********"], "method": "auth.login", "id": 1}
RESP: {"id": 1, "result": true, "error": null}
POST: {"params": [], "method": "web.connected", "id": 10}
RESP: {"id": 10, "result": true, "error": null}
POST: {"params": [], "method": "web.get_hosts", "id": 11}
RESP: {"id": 11, "result": [["250a0aac82f597b51fba1cfe62697afede2ded74", "127.0.0.1", 58846, "Offline"]], "error": null}

Also, with debugging turned on within deluge-web, when I manually perform the 'web.get_hosts' query, it logs the following:

[DEBUG   ] 10:55:34 json_api:255 json-request: {"params": [], "method": "web.get_hosts", "id": 11}
[DEBUG   ] 10:55:34 json_api:782 get_hosts called

However, when SR calls the same function, it misses the 'get_hosts called' line, and only lists the json-request with nothing else (no error, or confirmation of the function being called)

**Comment by PaulW** [comment]
# pip list
argparse (1.2.1)
cffi (0.8.6)
chardet (2.3.0)
Cheetah (2.4.4)
colorama (0.3.2)
cryptography (0.6.1)
defusedxml (0.4.1)
docutils (0.12)
html5lib (0.999)
ndg-httpsclient (0.3.2)
Pillow (2.6.1)
pip (1.5.6)
ply (3.4)
pyasn1 (0.1.7)
pycparser (2.10)
Pygments (2.0.1)
pyOpenSSL (0.13.1)
python-apt (0.9.3.11)
python-debian (0.1.27)
python-debianbts (1.11)
reportbug (6.6.3)
requests (2.4.3)
roman (2.0.0)
setuptools (5.5.1)
six (1.8.0)
SOAPpy (0.12.22)
urllib3 (1.9.1)
wheel (0.24.0)
wsgiref (0.1.2)
wstools (0.4.3)

**Comment by miigotu** [comment]
@PaulW you are using the wrong port. 58846 is not the webui port. The correct port is 8112. Make sure the SSL option in deluge webUI settings is unchecked and make the settings in SR look like this:

![image](https://cloud.githubusercontent.com/assets/390379/8955840/1b5f8bec-35a5-11e5-9d71-bc44b9283751.png)

**Comment by PaulW** [comment]
No I am connecting to 8112.  The JSON result mentioned above gives the list of available daemons to the WebUI Client, of which the daemon is running on 58846.  WebUI is set on 8112 and can be connected to just fine:

# curl http://localhost:8112
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
        <head>
                <title>Deluge: Web UI 1.3.11</title>
...etc...

**Comment by miigotu** [comment]
I guarantee this works in SR. I literally installed deluge and set this up to connect in less than 10 minutes. (first time I ever tried).

Did you only install deluge-web? You also need deluged. The web server still runs without deluged.
![image](https://cloud.githubusercontent.com/assets/390379/8956732/99f8e8a6-35ad-11e5-820e-c24161bf4ab8.png)

**Comment by PaulW** [comment]
Yes it's all installed & working just fine.

I'm wondering if it may be something related to Debian 8.1...  I'll try spin up a new VM with an older version on.

**Comment by fernandog** [comment]
Maybe deluge gui lost connection to daemon. This happened a lot to me in the past. Moved to transmission

**Comment by PaulW** [comment]
No connection is fine, going from the responses, it looks as though SR isn't preserving the sessions, but I've no idea why.

**Comment by miigotu** [comment]
I have no clue what to tell you, other than if I let it try and verify certificates or use SSL/HTTPS it fails.

**Comment by miigotu** [comment]
Have you tried turning it off and then back on again? HAHA

**Comment by PaulW** [comment]
LMAO Yes, I even checked to make sure it was plugged in :P

**Comment by PaulW** [comment]
*update* Not sorted out a VM as yet, instead I've decided to start work on a new client which connects directly to the Daemon and not via the WebUI.  At present it can authenticate & add torrents, but needs tidying up.

**Comment by PaulW** [comment]
https://github.com/PaulW/SickRage/commit/0ccbd2a1a53453160a5c965d060047b9e1706e35

I need to fully test file upload for torrents & add in methods for setting ratio's & download locations...
