### ISSUE TITLE
Could not connect to Trakt. Code error: 404

### ISSUE THREAD

**Issue by MoiZie** [SiCKRAGETV/sickrage-issues#2370]
Branch: master
Commit hash; 1ec701e4c12b41d1a34f01ad6091b1fec09967a3
Your operating system and python version; ubuntu 15.04, python 2.7.9 gcc4.9.2
What you did; install sickrage. connect trakt and supply PIN
What happened; Providing error messages: TRAKTCHECKER :: Could not connect to Trakt. Code error: 404
What you expected; no error messages, working connection.
GIST: https://gist.github.com/MoiZie/4d12016ff504475b2f2a

**Comment by MoiZie** [comment]
Additional GIST with debug=1 https://gist.github.com/MoiZie/b2dcda17698d56dc6cce

**Comment by MoiZie** [comment]
Hi, thank you for a quick response. I've noticed my current sickrage install has the fixed file installed, but I still have issues. The error changed though:

https://gist.github.com/MoiZie/044b659886d2c65bbd70

**Comment by fernandog** [comment]
@MoiZie FULL logs with debug enabled please

**Comment by miigotu** [comment]
@fernandog I think the show this is failing on he doesnt have imdbid.

**Comment by MoiZie** [comment]
https://gist.github.com/MoiZie/5e2802605ce9937e6cb6

**Comment by miigotu** [comment]
@MoiZie please update and recreate the error again (still with debug), we should now see the url that is failing.

**Comment by fernandog** [comment]
@miigotu  he is on master

**Comment by miigotu** [comment]
@fernandog thats why I cherry-picked to master for hotfix =P

**Comment by MoiZie** [comment]
You were right, missing show; 

2015-07-29 17:35:15 WARNING  TRAKTCHECKER :: Trakt error (404) the resource does not exist: https://api-v2launch.trakt.tv/shows/tt1322780/progress/watched

Which is 'Oceans', the 2008 tv-series. (sorry, currently in public transit, so can't get a debug log right now)

**Comment by MoiZie** [comment]
https://gist.github.com/MoiZie/b65be3268c5c958f3632

**Comment by miigotu** [comment]
If it isn't on trakt we can't do any better than to warn you.
