### ISSUE TITLE
[Feature Request] Add tooltips to settings for explanation

### ISSUE THREAD

**Issue by neoatomic** [SiCKRAGETV/sickrage-issues#2371]
I would like to add tool-tips for all the settings, so that users have some quick info on what the setting is/supposed to do.
So that when you hover over the settings name (or click on it) you get a short explanation.
See the below image for an example. 

![naamloos](https://cloud.githubusercontent.com/assets/7928052/8930941/b4708804-3532-11e5-96dc-032a1b4026c0.png)

If i see some examples on how to add a tool-tip to a template i will try to add those myself.

@MGaetan89 Are you familiar how to add those.?

**Comment by MGaetan89** [comment]
Bootstrap provides this feature: http://getbootstrap.com/javascript/#tooltips
It is used in SickRage, so no extra dependency is required.

**Comment by fernandog** [comment]
@neoatomic short explanation are in the page. long explanation we can redirect to FAQ

changing this before mako could not be a good idea. We can do it after mako

**Comment by neoatomic** [comment]
@fernandog Just need to know if its possible. Than i will make a doc with the explanations so we only have to copy/paste them in the Mako Templates. :)

**Comment by OmgImAlexis** [comment]
@neoatomic if you want to make the doc I can see about adding it soon.

**Comment by neoatomic** [comment]
@OmgImAlexis You probably can copy/paste the explanations from the wiki pages i made. https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained

Now we have many explanations as plain text on the page, but if we add that to tool-tips we should get a cleaner layout.
And maybe a "help" or "?" link at the bottom of every page to the correct wiki page.?

Just some idea's. But let's consider those changes when the templates are finished cleaning up.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
