### ISSUE TITLE
post-process menu not vissible from LOCALHOST, works fine with IP

### ISSUE THREAD

**Issue by thesatman** [SiCKRAGETV/sickrage-issues#2374]
post-process menu is not vissible from LOCALHOST, works fine with IP from both server and other PC's.

SR Version:	BRANCH: (master) / COMMIT: (1ec701e4c12b41d1a34f01ad6091b1fec09967a3) 
SR Locale:	('nb_NO', 'cp1252')
Python Version:	2.7.8 (default, Jul 2 2014, 19:48:49) [MSC v.1500 64 bit (AMD64)]

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md#submitting-a-bugissue-ticket

**Comment by thesatman** [comment]
Sorry, my mistake :). See above for Branch info

**Comment by miigotu** [comment]
resize the window a bit. There is currently a bootstrap css problem with the menu.
