### ISSUE TITLE
[APP SUBMITTED]: global name 're' is not defined

### ISSUE THREAD

**Issue by dirkr07** [SiCKRAGETV/sickrage-issues#2377]
### INFO
Python Version: **2.7.10 (default, Jun  4 2015, 00:30:19) [GCC 4.3.2]**
Operating System: **Linux-2.6.32.12-ppc-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@1ec701e4c12b41d1a34f01ad6091b1fec09967a3
Link to Log: https://gist.github.com/35e2fe01b5aa7f49ee4a
### ERROR
```
FINDPROPERS :: [Shazbat.tv] :: Exception generated in thread FINDPROPERS :: [Shazbat.tv]: global name 're' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
One sec, fixing now.

**Comment by Rouzax** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@1ec701e4c12b41d1a34f01ad6091b1fec09967a3
No Log available with ERRORS: 
### ERROR
```
FINDPROPERS :: [KickAssTorrents] :: Exception generated in thread FINDPROPERS :: [KickAssTorrents]: global name 're' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
@Rouzax that has already been fixed in develop.

**Comment by Rouzax** [comment]
Sorry, I did not know that.

**Comment by miigotu** [comment]
@Rouzax pushed to master now.

**Comment by OmgImAlexis** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-57-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@1ec701e4c12b41d1a34f01ad6091b1fec09967a3
No Log available with ERRORS: 
### ERROR
```
FINDPROPERS :: [KickAssTorrents] :: Exception generated in thread FINDPROPERS :: [KickAssTorrents]: global name 're' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by devenashani** [comment]
### INFO
Python Version: **2.7.3 (default, Jul 13 2012, 04:03:47) [GCC 4.4.5]**
Operating System: **Linux-2.6.31.8.nv+v2-armv5tel-with-debian-6.0.3**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@1ec701e4c12b41d1a34f01ad6091b1fec09967a3
Link to Log: https://gist.github.com/a66c76bc85056d6b9861
### ERROR
```
FINDPROPERS :: [KickAssTorrents] :: Exception generated in thread FINDPROPERS :: [KickAssTorrents]: global name 're' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
