### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-MANUAL-276562 :: Check scene exceptions update failed for theTVDB, Unable to get URL: http://thexem.de/map/allNames?origin=tvdb&seasonNumbers=1

### ISSUE THREAD

**Issue by ripper1967** [SiCKRAGETV/sickrage-issues#2379]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@1ec701e4c12b41d1a34f01ad6091b1fec09967a3
Link to Log: https://gist.github.com/bb5ed8e73ab422c4501c
### ERROR
```
SEARCHQUEUE-MANUAL-276562 :: Check scene exceptions update failed for theTVDB, Unable to get URL: http://thexem.de/map/allNames?origin=tvdb&seasonNumbers=1
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
already increase timeout for this.

https://github.com/SiCKRAGETV/SickRage/commit/8e2b08318f347456a6561adf251e8e9394897d99
