### ISSUE TITLE
Version checking is disabled, not checking for the newest version

### ISSUE THREAD

**Issue by papampi** [SiCKRAGETV/sickrage-issues#2382]
every now and then my SR stops checking for new version and when I do t manually it gives the the disabled message, checked general settings, "Check software updates" and "Automatically update" both have check marks.

2015-07-29 15:42:36 INFO     Thread-34 :: Version checking is disabled, not checking for the newest version

Ubuntu 14.04
SR Version:	BRANCH: (master) / COMMIT: (ebbd67fec6586fbb9f4d9122a17ddf1047a49147) 
SR Locale:	(None, None)
SR Config file:	/opt/sickrage/config.ini
SR Database file:	/opt/sickrage/sickbeard.db
SR Cache Dir:	/opt/sickrage/cache
SR Log Dir:	/opt/sickrage/Logs
SR Arguments:	['--nolaunch']
Python Version:	2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]

**Comment by papampi** [comment]
was looking at advanced settings and noticed in the branch version it shows : 
Error: No branches found. (in red)

could it be the problem ?

**Comment by papampi** [comment]
found this line in log too 
2015-07-29 16:05:21 WARNING  MAIN :: Unable to setup github properly, github will not be available. Error:

**Comment by miigotu** [comment]
When `Unable to setup github properly, github will not be available` occcurs, it is when github cannot be reached, either by the site being inaccessible, or a drop/ltimeout in your network.

This setup only happens once during SR boot up, and if it's not initialized we don't have the information about updates.

**Comment by fernandog** [comment]
will haven in general settings when listing available branches. If github can't be contacted you get this
