### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-MANUAL-261181 :: Check scene exceptions update failed for theTVDB, Unable to get URL: http://thexem.de/map/allNames?origin=tvdb&seasonNumbers=1

### ISSUE THREAD

**Issue by devenashani** [SiCKRAGETV/sickrage-issues#2383]
### INFO
Python Version: **2.7.3 (default, Jul 13 2012, 04:03:47) [GCC 4.4.5]**
Operating System: **Linux-2.6.31.8.nv+v2-armv5tel-with-debian-6.0.3**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@1ec701e4c12b41d1a34f01ad6091b1fec09967a3
Link to Log: https://gist.github.com/e23269a48685454caff4
### ERROR
```
SEARCHQUEUE-MANUAL-261181 :: Check scene exceptions update failed for theTVDB, Unable to get URL: http://thexem.de/map/allNames?origin=tvdb&seasonNumbers=1
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by aktavor69** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@136f531f93093a5287b588ca37e19c11153f47a4
No Log available with ERRORS: 
### ERROR
```
MAIN :: Check scene exceptions update failed for theTVDB, Unable to get URL: http://thexem.de/map/allNames?origin=tvdb&seasonNumbers=1
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
