### ISSUE TITLE
Torrent not sent to rTorrent

### ISSUE THREAD

**Issue by acecon** [SiCKRAGETV/sickrage-issues#2385]
- Master Branch
- Win 8.1 using Python 2.7.10
- Manuel Search on a Skipped Episode
- Found Torrent in IPTorrents, but didn't send to rTorrent Client
- https://gist.github.com/acecon/4438e595d555fa1ae88e

![rtorrentsetup](https://cloud.githubusercontent.com/assets/5316621/8959787/6e1b16d0-35d2-11e5-84b2-e458d816460f.png)

**Comment by fernandog** [comment]
@acecon 
are you sure you are using Python 7?

open cmd, type 'python' and see version

**Comment by frriction** [comment]
may be try removing "s" from "https" and just use "http" ?

**Comment by acecon** [comment]
yes, it's python 2.7 and the rTorrent setup is correct (see #625).

**Comment by acecon** [comment]
I also have pyOpenSSL-0.13-py2.7 installed. 
I believe this install fixed an issue I was previously having, so not sure if it's related to this issue.

**Comment by miigotu** [comment]
Try unchecking "Verify SSL Certs" in config/general->adavnced tab

**Comment by acecon** [comment]
- @miigotu, No fix by Unchecking "Verify SSL Certs" in General>Advanced tab
- Now it's showing a different debug log with OR without Check-marking "Verify SSL Certs" in General>Advanced tab

```
2015-07-29 22:16:31 INFO     SEARCHQUEUE-MANUAL-247808 :: Downloading Suits.S05E06.PROPER.HDTV.x264-DEFiNE from IPTorrents
2015-07-29 22:16:32 DEBUG    SEARCHQUEUE-MANUAL-247808 :: Calling rTorrent Client
2015-07-29 22:16:32 DEBUG    SEARCHQUEUE-MANUAL-247808 :: Tr***back (most recent call last):
  File "C:\Users\SRemote\SickRage\sickbeard\search_queue.py", line 184, in run
    self.success = search.snatchEpisode(searchResult[0])
  File "C:\Users\SRemote\SickRage\sickbeard\search.py", line 138, in snatchEpisode
    dlResult = client.sendTORRENT(result)
  File "C:\Users\SRemote\SickRage\sickbeard\clients\generic.py", line 177, in sendTORRENT
    if not self._get_auth():
  File "C:\Users\SRemote\SickRage\sickbeard\clients\rtorrent_client.py", line 50, in _get_auth
    self.auth = RTorrent(self.host, self.username, self.password, True, tp_kwargs=tp_kwargs)
  File "C:\Users\SRemote\SickRage\lib\rtorrent\__init__.py", line 83, in __init__
    self._verify_conn()
  File "C:\Users\SRemote\SickRage\lib\rtorrent\__init__.py", line 122, in _verify_conn
    assert "system.client_version" in self._get_rpc_methods(
  File "C:\Users\SRemote\SickRage\lib\rtorrent\__init__.py", line 161, in _get_rpc_methods
    return(self._rpc_methods or self._update_rpc_methods())
  File "C:\Users\SRemote\SickRage\lib\rtorrent\__init__.py", line 150, in _update_rpc_methods
    self._rpc_methods = self._get_conn().system.listMethods()
  File "C:\Python27\lib\xmlrpclib.py", line 1240, in __call__
    return self.__send(self.__name, args)
  File "C:\Python27\lib\xmlrpclib.py", line 1599, in __request
    verbose=self.__verbose
  File "C:\Users\SRemote\SickRage\lib\rtorrent\lib\xmlrpc\requests_transport.py", line 150, in request
    response.headers)
ProtocolError: <ProtocolError for https://63.142.240.16//rutorrent/plugins/httprpc/action.php: 401 Client Error: Authorization Required Tr***back (most recent call last):
  File "C:\Users\SRemote\SickRage\lib\rtorrent\lib\xmlrpc\requests_transport.py", line 145, in request
    response.raise_for_status()
  File "C:\Users\SRemote\SickRage\lib\requests\models.py", line 834, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 401 Client Error: Authorization Required
>
```

**Comment by miigotu** [comment]
`Authorization Required`
login failed.

I will install rtorrent and see if it works for me in a few hours.

**Comment by acecon** [comment]
No NEED.
I retyped in my password and stated it was "Connected & Authenticated".
I manual searched a Skipped Ep and torrent was successfully send to rTorrent Client.
**The little things matter!** :sweat_smile:

The Original issue (https://gist.github.com/acecon/4438e595d555fa1ae88e) was fixed somehow before  I posted the NEW issue 13 hours later.

I'm thinking it was due to:
- Upgrading Python 2.7.4 to Python 2.7.8 OR Python 2.7.10 *(I have 32-bit Python 2.7.8 installed now)*
- I uninstalled pyOpenSSL-0.13-py2.7 before installing Python 2.7.8 since this Python version's changelog states "The openssl version bundled in the Windows installer has been updated."
- pyOpenSSL is important because is seemed to have fixed an issue I was having for weeks prior to the issues on this thread.
- Possibly updating SR Master branch to COMMIT: (8fa7a4bb777c9192bd706115579e540eed8461b2) helped.

The NEW issue was fixed by simply retyping my rTorrent password in Search Settings>Torrent Search tab. 
I also kept "Verify SSL Cert" unchecked in both General>Advanced Settings & Search Settings>Torrent Search tabs.

Thanks

**Comment by miigotu** [comment]
Glad its working now.

**Comment by frriction** [comment]
@miigotu 
I normally use blackhole method, after seeing this issue I tried setting up rtorrent method and I got this.


http://pastebin.com/yeKnneMt

![Image of rtorrent setting]
(http://i.imgur.com/Du0FNuv.png)

```
SR Version:	BRANCH: (master) / COMMIT: (8fa7a4bb777c9192bd706115579e540eed8461b2) 
SR User:	pi
SR Locale:	('en_US', 'UTF-8')
SR Config file:	/media/pendrive/ccdl/config/SickRage/config.ini
SR Database file:	/media/pendrive/ccdl/Database/SickRage/sickbeard.db
SR Cache Dir:	/media/pendrive/ccdl/Database/SickRage/cache
SR Log Dir:	/media/pendrive/ccdl/Database/SickRage/Logs
SR Arguments:	['-q', '-d', '--pidfile', '/home/pi/.run/sickrage.pid', '--datadir', '/media/pendrive/ccdl/Database/SickRage/', '--nolaunch', '--config', '/media/pendrive/ccdl/config/SickRage/config.ini']
SR Web Root:	/sr
Python Version:	2.7.10 (default, May 30 2015, 02:17:57) [GCC 4.9.2 20150304 (prerelease)]
```
