### ISSUE TITLE
Air data off by one day for shows

### ISSUE THREAD

**Issue by EraYaN** [SiCKRAGETV/sickrage-issues#2386]
For the show Cool Japan Season 1: http://thetvdb.com/?tab=season&seriesid=255623&seasonid=486026&lid=7

SR Version: 	BRANCH: (master) / COMMIT: (23f36256e8af9383f4bc80ca3b2aca75148a8694)
SR Locale:	('nl_NL', 'cp1252')
Python Version:	2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]
Windows Server 2012 R2
    What you did: Added the Cool Japan show
    What happened: It downloaded all data (correctly it seems) Displays all airdates in season one (2011) one day early so episode 2011-01-08 becomes 2011-01-07. Post processing does use the correct date.
    What you expected: Correct date shown.
  (no log)

Now this show airs in the UTC+9 timezone and I'm in the UTC+2 (DST) timezone that might be the problem.

Screenshots:
http://i.imgur.com/XawNwuW.png (SickRage date)
http://i.imgur.com/IxTIRC6.png (theTVDB date)

EDIT: Is this a feature??

**Comment by fernandog** [comment]
in SR, do you have local or network time selected?

**Comment by EraYaN** [comment]
Fair enough, local time. So it's a feature. Well I had to fight with the post processor for way to long ;) Thanks for the quick reply though.
