### ISSUE TITLE
Master branch broken due to error in '/lib/guessit/textutils.py'

### ISSUE THREAD

**Issue by LanMan04** [SiCKRAGETV/sickrage-issues#2389]
SickRage will not start up, at all.  On the latest master branch version (updated around 13:00 GMT)  Here's a trace, ^ should be pointing to the comma in that last line:

````
Traceback (most recent call last):
  File "/usr/local/SickRage/SickBeard.py", line 89, in <module>
    import sickbeard
  File "/usr/local/SickRage/sickbeard/__init__.py", line 37, in <module>
    from sickbeard import providers, metadata, config, webserveInit
  File "/usr/local/SickRage/sickbeard/providers/__init__.py", line 59, in <module>
    import generic
  File "/usr/local/SickRage/sickbeard/providers/generic.py", line 32, in <module>
    from sickbeard import helpers, classes, logger, db
  File "/usr/local/SickRage/sickbeard/helpers.py", line 73, in <module>
    from sickbeard.subtitles import isValidLanguage
  File "/usr/local/SickRage/sickbeard/subtitles.py", line 29, in <module>
    import subliminal
  File "/usr/local/SickRage/lib/subliminal/__init__.py", line 9, in <module>
    from .api import list_subtitles, download_subtitles, download_best_subtitles, save_subtitles
  File "/usr/local/SickRage/lib/subliminal/api.py", line 9, in <module>
    from .providers import ProviderPool
  File "/usr/local/SickRage/lib/subliminal/providers/__init__.py", line 9, in <module>
    from ..video import Episode, Movie
  File "/usr/local/SickRage/lib/subliminal/video.py", line 10, in <module>
    import guessit
  File "/usr/local/SickRage/lib/guessit/__init__.py", line 88, in <module>
    from guessit.guess import Guess, smart_merge
  File "/usr/local/SickRage/lib/guessit/guess.py", line 29, in <module>
    from guessit.textutils import common_words
  File "/usr/local/SickRage/lib/guessit/textutils.py", line 250
    _camel_word2_set = {'is', 'to'}
                            ^
SyntaxError: invalid syntax
````

**Comment by fernandog** [comment]
@miigotu

**Comment by fernandog** [comment]
@LanMan04 why is your python version?

**Comment by LanMan04** [comment]
@fernandog 

2.6.6 (r266:84292, Nov 27 2010, 19:47:39) [GCC 4.5.1]

**Comment by fernandog** [comment]
@LanMan04 can you update to 2.7.9 ?

**Comment by drzoidberg33** [comment]
Broken here too. Python 2.6.6. is the latest in the Centos 6.6 repos.

"Fixed" mine by changing the two dicts to lists. Most probably will break other stuff though.

I'm guessing this is going to affect quite a few linux users.

**Comment by LanMan04** [comment]
Unsure.  Right now I'm running SickRage on an UnRAID NAS (version 5).  I'll slog through the forums and see if I can do that without breaking anything.

If there's no functional difference, can you revert that change?  Not familiar with python, not sure what the double-parens vs curly braces changes in terms of functionality.  I made that change and SR started up with no problems.

There are a LOT of people still running unRAID 5; this will break SR for all of them.

**Comment by LanMan04** [comment]
Basically, ALL of SickRage is 2.6.6-compatible except for this change.  Unless there's a good reason, can we keep it compatible with 2.6.6?

**Comment by fernandog** [comment]
Its updated an external library in SR. We will see what we can do

**Comment by drzoidberg33** [comment]
I see the library removed support for 2.6.

https://github.com/wackou/guessit/commit/7bbf9726b3a5009ccb942e5a8579ab3bad5b1950

**Comment by miigotu** [comment]
SickRage no longer supports python 2.6.

**Comment by fernandog** [comment]
https://sickrage.tv/forums/forum/help-support/general-support/25902-sickrage-not-starting-throwing-syntax-error-centos-5-6-install#post25915

**Comment by LanMan04** [comment]
@miigotu:  Due to one line in one external lib?  Lame.  Tons of people still use 2.6.6

**Comment by miigotu** [comment]
http://toomuchdata.com/2014/02/16/how-to-install-python-on-centos/

Its much more than 1 line. Just happens that is the only one that prevents startup.  Maybe 1% of SR users have python 2.6. There are ways to use python 2.7.x on unraid and centos

**Comment by drzoidberg33** [comment]
Thanks for the update. Guess it's time to upgrade anyway.

**Comment by drzoidberg33** [comment]
This worked for me on Centos 6.

First install python 2.7 using this guide as mentioned above: http://toomuchdata.com/2014/02/16/how-to-install-python-on-centos/ (I just used 2.7.10 instead of 2.7.6 in the guide).

If you are using an init script you will have to update that too as it calls your default path for python which you don't want to change system-wide.

I added a line to /etc/sysconfig/sickrage:

    PYTHON_BIN=/usr/local/bin/python2.7

Then added a python_bin variable in my init script in /etc/init.d/sickrage

    ## Edit user configuation in /etc/sysconfig/sickrage to change
    ## the defaults
    username=${SB_USER-sickrage}
    homedir=${SB_HOME-/opt/sickrage}
    datadir=${SB_DATA-/opt/sickrage}
    pidfile=${SB_PIDFILE-/var/run/sickrage/sickrage.pid}
    python_bin=${PYTHON_BIN-/usr/bin/python}
    nice=${SB_NICE-}
    ##

And changed the references to python to ${python_bin} in the start and stop functions:

    start() {
    	    # Start daemon.
            echo -n $"Starting $prog: "
            daemon --user=${username} --pidfile=${pidfile} ${nice} ${python_bin} ${homedir}/SickBeard.py ${options}
            RETVAL=$?
            echo
            [ $RETVAL -eq 0 ] && touch $lockfile
            return $RETVAL
    }
    
    stop() {
            echo -n $"Shutting down $prog: "
            killproc -p ${pidfile} ${python_bin}
            RETVAL=$?
            echo
	        [ $RETVAL -eq 0 ] && rm -f $lockfile
            return $RETVAL
    }

Working now.

**Comment by drzoidberg33** [comment]
Created a pull request for the above changes: https://github.com/SiCKRAGETV/SickRage/pull/2230

**Comment by Kybber** [comment]
Another, and perhaps safer and more correct way for CentOS, is to use [SCLs](http://wiki.centos.org/AdditionalResources/Repositories/SCL). It should work for CentOS 6.4 and up.

Do the following to install Python2.7 safely for your CentOS host:

    yum install centos-release-SCL
    yum install python27

Enable the python 2.7 SCL in the init-script by adding the following line to /etc/init.d/sickrage, before calling the damon in the start()-function:

    source /opt/rh/python27/enable

If you try to run sickrage now, it will most likely complain about openssl and cryptography, and may not work correctly. Do this to fix:

    scl enable python27 bash
    easy_install pip
    pip2.7 install pyopenssl==0.13.1
    exit
