### ISSUE TITLE
Server_request_loop

### ISSUE THREAD

**Issue by konomimaster** [SiCKRAGETV/sickrage-issues#2392]
I've run into this error message in the logs.

I can't open my install and i'm getting this error message: "err_connection_reset".

I'm on Synology DSM 5.2, master branch, Python 2.7.10.

I can't tell the hash since i can't access Sickrage. But i've done a clean install of it today so that narrows down the amount of possible commits.

![udklip2](https://cloud.githubusercontent.com/assets/11414629/8982801/d98deaee-36c4-11e5-9db6-2d1ea91fbad3.PNG)
![udklip3](https://cloud.githubusercontent.com/assets/11414629/8982802/d9ad3994-36c4-11e5-953b-0b4c924a1616.PNG)
![udklip1](https://cloud.githubusercontent.com/assets/11414629/8982803/d9af0c06-36c4-11e5-9932-689fe54294a1.PNG)

**Comment by adaur** [comment]
Hi,

It looks like an SSL issue. Can you try this?

https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors

**Comment by konomimaster** [comment]
When i input "openssl version" i get: OpenSSL 10.1p-fips 9 Jul 2015. 

I'm asked to make sure that i run OpenSSL 1.0.1. Is this the right version?

In the guide i'm asked to run some commands. My system doesn't recognize the command "apt-get" so i can't run them.

When i check my python-log i get that i'm running pyOpenSSL version 0.15.1.

I don't know what to get by this.
There was a recent update to my system upgrading the SSL versoin to 1.0.1p which might have done this.

**Comment by neoatomic** [comment]
@konomimaster Running a Synology myself and dont have a problem...
As you are on a Synology i dont think the problem lies within the Python package but somewhere else. 
Post the debug logs so we can see what SickRage is doing at the moment.
Are you using a proxy.? self singed certs.? or simulair.?
For now you can try to disable the option verify ssl cert in the settings. See if that helps.

**Comment by konomimaster** [comment]
Well i think i figured it out. 
I've manually added "https://" before the ip-adress for the install and now i can access it. 
It seems that since i've activated ssl on SR i can't access it without accessing it through https.
