### ISSUE TITLE
[APP SUBMITTED]: Thread-40 :: git version returned : 'git' is not recognized as an internal or external command,
operable program or batch file.

### ISSUE THREAD

**Issue by SunMar** [SiCKRAGETV/sickrage-issues#2394]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: ****
Commit: SiCKRAGETV/SickRage@8fa7a4bb777c9192bd706115579e540eed8461b2
Link to Log: https://gist.github.com/fc80acc85a07ce3aa4be
### ERROR
```
Thread-40 :: git version returned : 'git' is not recognized as an internal or external command,
operable program or batch file.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by sirPotstone** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: ****
Commit: SiCKRAGETV/SickRage@89efb07b1e482a6c8b21b0ac4e18e069d25c856e
Link to Log: https://gist.github.com/3d4c614caf9858fc850f
### ERROR
```
Thread-20 :: git version returned : 'git' is not recognized as an internal or external command,
operable program or batch file.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by sirPotstone** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: ****
Commit: SiCKRAGETV/SickRage@89efb07b1e482a6c8b21b0ac4e18e069d25c856e
No Log available with ERRORS: 
### ERROR
```
MAIN :: git version returned : 'git' is not recognized as an internal or external command,
operable program or batch file.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
