### ISSUE TITLE
SR randomly sets default status to "skipped"

### ISSUE THREAD

**Issue by SoWhy** [SiCKRAGETV/sickrage-issues#2396]
I just noticed that an episode of "Melissa & Joey" was not downloaded. When I checked the listing, it said "Default EP Status: Skipped". I didn't set that and I have no idea why it was set. I noticed it on a few other shows as well but with no discernible pattern. Apparently it doesn't matter which indexer is used. I cannot find any reason in the log file why this should happen but then again, I don't really know, what to look for. I'd be happy to provide more info if you tell me what you need.

**Comment by miigotu** [comment]
Please read the "News" page in SR top nav.
