### ISSUE TITLE
Sickrage suddenly stopped downloading new torrents

### ISSUE THREAD

**Issue by hennning** [SiCKRAGETV/sickrage-issues#2397]
Branch: master
Commit: 8fa7a4bb777c9192bd706115579e540eed8461b2
Operating System: Windows Server 2012 R2
Python. 2.7.10
What you did: Nothing
What happened: Nothing/Status stuck in queued
What you expected: Torrent gets downloaded and pulled to Deluge/Blackhole
Logs: https://gist.github.com/hennning/01573c9f30583e30c74f

In depth description:
Sickrage suddenly stopped downloading new series a few days ago. Last successful download was on 27th of July.
When I go to a show I've added and press the magnifying glass it sets the status to queued but nothing more happens. If I check an entire season and set status to wanted it changes the status to wanted but nothing downloads. If I restart SickRage the status is reset to whatever status the episode had before.

I have tried both with Deluge and Blackhole. The torrent providers I use is both HDBits and BTN.

I haven't touched my server in about two weeks. I have tried to restart the entire server but get the same problem.

**Comment by matansh** [comment]
Same thing is happening to me.. nothing gets downloaded and the daily searcher keeps logging "No new released episodes found ..." 
Luckily the post processor works so im back to manually adding torrents for now

**Comment by miigotu** [comment]
@matansh All major functions of SR are in working order currently. Have you read the news page?

**Comment by hennning** [comment]
@miigotu what do you mean? We do have a problem. It's not working for us.

**Comment by fernandog** [comment]
check if you have "So You Think You Can Dance US" and "So You Think You Can Dance (US)" in your show "scene exceptions"

**Comment by hennning** [comment]
So You Think You Can Dance (US) was not in exception list, it is now.
Restarted SickRage but still not working.

So you think you can dance is not the only show that's not working. No shows work as far as I know.

I tried clicking the magnifying glass on Brooklyn Nine-Nine S02E01 and it sets status to queued but nothing more happens. 
If I select the whole season and change status to "Wanted" I get a message telling me "Backlog was automatically started for the following seasons of "Brooklyn Nine-Nine"; *Season 2". It changes the status to Wanted but nothing gets downloaded.

I set Brooklyn Nine-Nine to Skipped (since it already was on Wanted) and then back to Wanted. This is the logs I got with db logging level display: https://gist.github.com/hennning/be6044e5b7679a3b0a3e

**Comment by fernandog** [comment]
without FULL logs there's nothing we can do

stop SR
delete all logs files from ~SickRage/Logs
start SR
manual search one episode
wait a minute or two
open log with debug level
past log in gist

**Comment by hennning** [comment]
Ok, sorry.
Here you go: https://gist.github.com/hennning/36a28236ba7b7a6d9678

**Comment by fernandog** [comment]
which show/episode should be downloaded but it was not?

**Comment by hennning** [comment]
Brooklyn Nine-Nine S02E01

**Comment by fernandog** [comment]
there's manual search info in your log.
did you pressed the manual search glass and wait a minute or two to view the logs?

**Comment by hennning** [comment]
Yes.
Here is a new log. https://gist.github.com/hennning/6977cbff14fa2664678a
In this I have done the following:
1. Stopped SickRage
2. Removed logs
3. Started SickRage
4. Entered the Show Zoo. This is a new show I just added today and have never downloaded any episodes of.
5. Episode 1-5 was marked as Wanted. But I pressed the magnifying glass on each episode and it change status to Queued.
6. Waited 2 minutes before opening the Log.

**Comment by fernandog** [comment]
2015-07-31 19:52:27 DEBUG    BACKLOG :: Nothing needs to be downloaded for Zoo, skipping

strange as there's still no manual search logs

**Comment by fernandog** [comment]
do you have: dailysearch and backlog search setting enabled at startup?

**Comment by hennning** [comment]
Yes, very. What's the next step?

**Comment by fernandog** [comment]
do you have: dailysearch and backlog search setting enabled at startup?

**Comment by hennning** [comment]
Yes

**Comment by fernandog** [comment]
read comment again. added more comments

**Comment by hennning** [comment]
Oh, ok. What is PP?

**Comment by fernandog** [comment]
postProcessor

**Comment by hennning** [comment]
Here is the new logs: https://gist.github.com/hennning/43d877b70312603a09f1
Now Zoo S01E01 status change to searching and not queued. It seems to be stuck on searching tough. All other episodes is Queued.

**Comment by fernandog** [comment]
check 'server status' in the last menu. see if there's something running

**Comment by hennning** [comment]
![sickrage_serverstatus](https://cloud.githubusercontent.com/assets/13292619/9014904/952d8baa-37c5-11e5-9058-abd16f6a722f.JPG)

**Comment by fernandog** [comment]
search for log again for: SEARCHQUEUE-MANUAL-283318

use the input field. post results

**Comment by hennning** [comment]
I don't really get what you wanted me to do?
If I search for SEARCHQUEUE-MANUAL-283318 in my log I get 3 hits:
2015-07-31 20:29:40 DEBUG    SEARCHQUEUE-MANUAL-283318 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
2015-07-31 20:29:40 DEBUG    SEARCHQUEUE-MANUAL-283318 :: formatting pattern: %SN - %Sx%0E - %EN -> Zoo - 1x01 - First Blood
2015-07-31 20:29:40 INFO     SEARCHQUEUE-MANUAL-283318 :: Beginning manual search for: [Zoo - 1x01 - First Blood]

But you already had that in my post on gist

**Comment by fernandog** [comment]
@hennning 
SEARCHQUEUE-MANUAL-283318 is not continuing.

I want you to disable POSTPROCESSOR, SUBTITLES SEARCH, DAILYSEARCH & BACKLOG search at startup, REFRESH shows at startup, delete logs and start a manual search for one episodes

find all entries for SEARCHQUEUE-MANUAL and post results

**Comment by hennning** [comment]
Those are the only entries with SEARCHQUEUE-MANUAL:
https://gist.github.com/hennning/6c834c2320ea2d196458

**Comment by fernandog** [comment]
please send a full print of this show

just some information: to disable PP just disable "Scan and Process" in PP settings

**Comment by hennning** [comment]
Is this the print you wanted?
![sickrage_zoo_series](https://cloud.githubusercontent.com/assets/13292619/9015644/90b46c06-37ca-11e5-86e9-7af5b0168936.JPG)

Tried again with disabled PP. Still just those 3 rows in the log about SEARCHQUEUE-MANUAL.

**Comment by fernandog** [comment]
the spinning wheel is still spinning after a while? or it back to 'wanted'?

**Comment by hennning** [comment]
It is still spinning. I have been restarting alot now while troubleshooting but for at least 10-15 min

**Comment by fernandog** [comment]
@miigotu any clue?

**Comment by hennning** [comment]
When I installed SickRage I used NSSM to create a windows service for SickRage. I don't know if that could impact any of this. When I shutdown SickRage I shut it down from the web, then restart the service.

That's the only thing I can think of with my installation that isn't standard.

**Comment by frederikprijck** [comment]
FYI: Me and a friend have been having the exact same issue after the last updates where installed.
A fix for us was: Uninstall SickRage and Re-install it. However, this is not a convenient solution for us.

**Comment by fernandog** [comment]
Please read news about default episode status

**Comment by frederikprijck** [comment]
How is this related to the issue ? Even manual searching doesn't work. I have changed nothing in SickRage, It have been working perfectly untill the last update.

If I select a few episodes of a show which was working perfectly and manually change their status to "WANTED", it's added to the backlog but it will never find or snatch an episode.
There are no errors occuring.

I just wanted to give you a headsup that the OP is not the only one suffering the issue.

**Comment by fernandog** [comment]
daily search / backlog search are working?

**Comment by frederikprijck** [comment]
Nothing is working. I have been unable to use SickRage since the last update. I have been manually downloading files without using SickRage :(

A friend confirmed that uninstalling and installing SickRage again fixes it. But I do not rly want to do this on my system.

**Comment by fernandog** [comment]
if re-installing works, there must be something wrong with your setup.

**Comment by frederikprijck** [comment]
Explain me why it did work for weeks before the update ? Saying something is wrong with my system is easy, realizing I know multiple people having the same issue, but they all reinstalled SickRage to fix it.

I refuse to reïnstall since I do not want to reconfigure all my shows etc. And I do think it's beneficial for you guys to know the cause. If everyone just reinstalls the program without contacting you you won't realise you may have broken something. And no, I am not saying you did. But there is definetly something wrong since the update.

**Comment by fernandog** [comment]
not your system. your SR setup

stop SR, and delete everything inside /SickRage/cache/ but not /images

**Comment by frederikprijck** [comment]
Cool, I will give that a try in 3 hours and I will let you know the result !
Thanks :-)

**Comment by hennning** [comment]
@fernandog I just tried deleting everything inside the cache folder except images and now everything seems to be working fine again.

As @frederikprijck said I haven't changed anything on my system, not even a reboot. Yet suddenly SR stopped working. There must have been something in an SR update that messed it up for some people and it's kinda worrisome that nothing of value got reported in the logs to troubleshoot the issue.

Anyway, the fix was easy and I'm happy as a clam again! Thanks

**Comment by frederikprijck** [comment]
Abit late, but didn't work for me.
I stopped SR.
I opened SSH and I deleted: 
/usr/local/SickRage/var/cache/cheetah
 /usr/local/SickRage/var/cache/rss
 /usr/local/SickRage/var/cache/sessions
 /usr/local/SickRage/var/cache/indexers

I restarted SR and still am unable to manualy download files.

I get the following output in the View Logs:
 AA
AAImportError: No module named generic
AA    from .generic import GenericClient
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/clients/download_station_client.py", line 24, in <module>
AA    return __import__(prefix + name + '_client', fromlist=__all__)
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/clients/__init__.py", line 114, in getClientModule
AA    module = getClientModule(name)
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/clients/__init__.py", line 118, in getClientIstance
AA    client = clients.getClientIstance(sickbeard.TORRENT_METHOD)()
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/search.py", line 137, in snatchEpisode
AA    self.success = search.snatchEpisode(searchResult[0])
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/search_queue.py", line 184, in run
2015-08-07 09:56:37 INFO     SEARCHQUEUE-MANUAL-247808 :: [ThePirateBay] :: Downloading Suits.S05E07.720p.HDTV.x264-KILLERS[EtHD] from ThePirateBay

**Comment by fernandog** [comment]
enter "/volume1/@appstore/sickrage/var/SickRage/" and reset and git pull
