### ISSUE TITLE
New show, recent epi (all on skipped): manual search is not setting epi to wanted

### ISSUE THREAD

**Issue by kooimens** [SiCKRAGETV/sickrage-issues#2398]
I added a new show and noticed that I missed a recent show (from 30-07-2015). It's on skipped right now (default, should be good). But when I manually search, nothing is found (not yet released, no problem). However, in the end the status is still on 'skipped' where it should be changed to wanted since I searched for it manually?

**Comment by miigotu** [comment]
searching for an episode manually should not change the status of the episode. If you want an episode set it to wanted.

**Comment by fernandog** [comment]
It changes to manually to do the manual search them get back to previous. Maybe we can make it permanent.

**Comment by kooimens** [comment]
@miigotu Why not? If I search for a particular episode it's pretty clear I 'want' it?

**Comment by fernandog** [comment]
@kooimens are you sure the status don't stay wanted? check your logs (debug level) and keep refreshing. see that it changes to wanted

**Comment by miigotu** [comment]
@fernandog I think it changes to default_ep_status, as it should.

**Comment by kooimens** [comment]
Checked logs at debug level, refreshed several times, no change. @miigotu I still don't get your point. Why should the status change to default if I search manually for an episode? I'm missing the logic here...

**Comment by miigotu** [comment]
When you click search you are saying "I want to search for this episode" NOT "I want to search for this episode and also change it's status to wanted"

They are two separate actions.

If it is set to wanted it is added to the backlog, and searched for until it is found. Performing a MANUAL SEARCH should not implicitly change the searched for item to a state that causes it to be repetitively searched for automatically.

The logic here is to be as precise and accurate in our handling of actions the user requests. Make 1 assumption (that the user wants it wanted) and you are no longer accurate.

~You asked us to manually search for an episode one time? OK - I will only search for it one time, and nothing more.~

**Comment by kooimens** [comment]
I agree the two actions should remain separated and that they are not the same from a developers perspective. However, from the users' perspective there is no real difference between a manual search and an episode you 'want'.

Furthermore, many third party apps making use of the sickrage API have options to search for an episode only. Just to make a clean and simple interface for it. The `change episode to status` is just too much for such an interface. In that perspective, searching for an episode and therefore changing it to status wanted could be useful as well.

I hope you get my point and try to see this issue as a serious one. An option to enable the behavior I requested would be useful, I think. I hope you can remove the label won't fix and reopen this issue.

**Comment by miigotu** [comment]
https://github.com/SynoCommunity/spksrc/pull/1802

I've limited my PR to only changing the permissions set, not ownership, as it seems they have quite a few packages chmod'd to the `root` group (doesnt make sense)
