### ISSUE TITLE
Torrents and Downloadstation Client

### ISSUE THREAD

**Issue by reiniervanrutten** [SiCKRAGETV/sickrage-issues#2399]
Hi there,

Sickrage is not connecting to download station anymore so it can download found torrents. This is the error that i found in the log:

AA
AAImportError: No module named generic
AA    from .generic import GenericClient
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/clients/download_station_client.py", line 24, in <module>
AA    return __import__(prefix + name + '_client', fromlist=__all__)
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/clients/__init__.py", line 114, in getClientModule
AA    module = getClientModule(name)
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/clients/__init__.py", line 118, in getClientIstance
AA    client = clients.getClientIstance(sickbeard.TORRENT_METHOD)()
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/search.py", line 137, in snatchEpisode
AA    self.success = search.snatchEpisode(searchResult[0])
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/search_queue.py", line 184, in run
2015-07-31 08:40:48 INFO     SEARCHQUEUE-MANUAL-73255 :: Downloading House.S05E23.720p.BluRay.x264-BRAVERY from KickAssTorrents
2015-07-31 08:40:48 INFO     SEARCHQUEUE-MANUAL-73255 :: Quality of House.S05E23.720p.BluRay.x264-BRAVERY is 720p BluRay
2015-07-31 08:40:39 INFO     SEARCHQUEUE-MANUAL-73255 :: [KickAssTorrents] :: Performing episode search for House

Here some extra info:
SR Version:	BRANCH: (master) / COMMIT: (27ded15e814bcbd47d06d9bf16d130f9d42ebd45) 
Synology 415+ with Sickrage package from synocommunity.

Also when testing the connection in the settings weird things happen:

AA
AAImportError: No module named generic
AA    from .generic import GenericClient
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/clients/download_station_client.py", line 24, in <module>
AA    return __import__(prefix + name + '_client', fromlist=__all__)
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/clients/__init__.py", line 114, in getClientModule
AA    module = getClientModule(name)
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/clients/__init__.py", line 118, in getClientIstance
AA    client = clients.getClientIstance(torrent_method)
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 825, in testTorrent
AA    result = function(**kwargs)
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 273, in async_call
AA    result = self.fn(*self.args, **self.kwargs)
AA  File "/usr/local/sickrage/var/SickRage/lib/concurrent/futures/thread.py", line 61, in run
AA    exec('raise exc_type, exc_value, traceback', {}, locals_)
AA  File "/usr/local/sickrage/var/SickRage/lib/concurrent/futures/_compat.py", line 107, in reraise
AA    reraise(self._exception, self._traceback)
AA  File "/usr/local/sickrage/var/SickRage/lib/concurrent/futures/_base.py", line 359, in __get_result
AA    return self.__get_result()
AA  File "/usr/local/sickrage/var/SickRage/lib/concurrent/futures/_base.py", line 400, in result
AA    value = future.result()
AA  File "/volume1/@appstore/sickrage/var/SickRage/tornado/gen.py", line 807, in run
AA    results = yield self.async_call(method)
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 258, in get
2015-07-31 08:50:55 DEBUG    TORNADO :: Failed doing webui request "testTorrent": Traceback (most recent call last):

Hopefully you can help me!
Thanks!

**Comment by miigotu** [comment]
back up the database and config, remove the package in DS, reinstall the package, and restore the DB and config.

**Comment by reiniervanrutten** [comment]
Worked. Had troubles with the restore tough, sickrage didn't use the backuped files in the zip. Had to manually put the extracted files from the zip in the /var/ dir.

Thanks for your help!
