### ISSUE TITLE
[Feature request] Show column for total show size

### ISSUE THREAD

**Issue by Aesculapius** [SiCKRAGETV/sickrage-issues#2401]
When viewing my show overview, I'd like to sort by 'Downloads', so I can quickly see what shows are missing how much.

![image](https://cloud.githubusercontent.com/assets/617061/9007347/a8f17c44-3790-11e5-8497-12389ca13324.png)

Now for some shows, I might decide to just get rid of them since I don't / won't watch it, and it could consume a lot of space in the meantime.

Would it be possible to show the total show size (as shown once you click a shows), as a seperate sortable column in the show overview?

![image](https://cloud.githubusercontent.com/assets/617061/9007374/d6f5c6ae-3790-11e5-8159-e8f54c8f4b33.png)

**Comment by fernandog** [comment]
that's easy to do BUT we are changing to mako templates. this kind of FR is frozen

but you can see show total size when you enter the show page


For future coding:

Size:
$sickbeard.helpers.pretty_filesize(sickbeard.helpers.get_size($showLoc[0]))

**Comment by OmgImAlexis** [comment]
@fernandog if this should be added let me know and I'll try to add it to the mako files once we're done.

@miigotu

**Comment by fernandog** [comment]
Im worried about performance.
Maybe take a while to load the page with this setting.

**Comment by OmgImAlexis** [comment]
Can't we cache the size when a new file gets added? That'll speed up displayShow and the home page.

**Comment by miigotu** [comment]
On fat32 the page would take like 10 minutes to load xD

**Comment by Aesculapius** [comment]
@fernandog I indeed was under the assumption that this value was cached or stored in db somewhere. I understand that it is calculated every time it is shown? That seems like a bad idea indeed to show for all shows. Is adding it to the db or caching it somehow complicated? Or should I open up a new request for that?

**Comment by fernandog** [comment]
don't need. we will think about this

**Comment by MGaetan89** [comment]
I sent a PR to include this https://github.com/SiCKRAGETV/SickRage/pull/2356

But I don't have enough shows to check for performance issue. If someone else can test my PR and give a feedback, that would be great.

**Comment by fernandog** [comment]
Didnt notice lag with 75 shows.

Sorting does not work. Need fix tablesorter

**Comment by MGaetan89** [comment]
I will have a look to fix the sorting.
It's good to know that performance may not be impacted by this :)

**Comment by miigotu** [comment]
Needs tested with shows on a fat32 partition, and with SR and shows on a separate machine using NFS/smb for access.

I suspect these both to have big perfermance problems.

**Comment by fernandog** [comment]
In the future with DB upgrade we can add a column in the DB and update with show refresh / PP

**Comment by miigotu** [comment]
@fernando, can you add a section to the issues stats which outlines desired db changes and which db/where? Any change that could be beneficial.

I want to do a db upgrade soon, but I want to make all of the db changes we need or could need in the future all in one db update.

**Comment by WebSpider** [comment]
Good idea to store this in db indeed.

-----Original Message-----
