### ISSUE TITLE
SickRage is sending an empty X-Plex-Client-Identifier header to Plex

### ISSUE THREAD

**Issue by mdelaossa** [SiCKRAGETV/sickrage-issues#2403]
Hey guys, just a heads up, Plex is making a change that will break notification functionality: you can't send an empty client identifier.

This happens because of `req.add_header('X-Plex-Client-Identifier', sickbeard.CUR_COMMIT_HASH)` in https://github.com/SiCKRAGETV/SickRage/blob/608c06810abb05ab6e9d07947c86d42b1b1a21c2/sickbeard/notifiers/plex.py#L200 

and you guys have set `CUR_COMMIT_HASH = None` in https://github.com/SiCKRAGETV/SickRage/blob/ce74c295a08daa8af0da8b27d9d6033eea77e63a/sickbeard/__init__.py#L119

**Comment by fernandog** [comment]
what you suggest doing?

**Comment by mdelaossa** [comment]
Up to you. You need to send a client identifier that's unique per user.
Maybe compute it on first run, or every time a user configured the Plex
notifier

**Comment by fernandog** [comment]
Anything unique?

**Comment by mdelaossa** [comment]
letters and numbers, sure

**Comment by miigotu** [comment]
@fernandog just set it to sickbeard.common.USER_AGENT (every machine has a unique user agent)

**Comment by mdelaossa** [comment]
Heads up: Plex is deploying this today in a few minutes. Expect your users to complain about failed sign ins

**Comment by fernandog** [comment]
@mdelaossa can you test please? develop branch

**Comment by miigotu** [comment]
It would have worked without changing it xD. commit hash is set from None to the commit hash in config immediately on boot. Either way, sending user-agent wont hurt I guess

**Comment by miigotu** [comment]
Actually, does the `X-Plex-Client-Identifier` need to be the same for every call, even across reboots? If so we need to add an md5 token just for this.

**Comment by Thraxis** [comment]
It should not be empty, it should be the hash of the current Git
release you are running.  The value is set in the version check
routine it's the same variable used to display the current version on
the General info page.

**Comment by miigotu** [comment]
I'm only curious about multiple users with different installs passing the same commit hash to plex.

This really should be an autogenerated md5 hash that is stored in the config and re-used every time for the call to plex. Just like our webapi key.

**Comment by fernandog** [comment]
@mdelaossa is it working? 

@Thraxis should we revert that then?

**Comment by mdelaossa** [comment]
I'm sorry, I don't use your product. This was only a courtesy notification.
I won't be testing

**Comment by fernandog** [comment]
@mdelaossa ok. thanks!

**Comment by WebSpider** [comment]
@Thraxis do you have a PLEX install to test this?
