### ISSUE TITLE
Error when trying to load RSS: must be string or buffer, not None

### ISSUE THREAD

**Issue by noze2000** [SiCKRAGETV/sickrage-issues#2407]
With the SSL error for several torrent sites when running SickRage on QNAP, i tried to add a torrent site that does not work with SickRage a the moment "manually" ie. add it is a custom search provider, using a TV RSS URL.

The error I get is "Error when trying to load RSS: must be string or buffer, not None"

This used to not be an issue in the past.

I tried this with multiple sites with same result.

Any idea what this may be?

**Comment by neoatomic** [comment]
You need to run a recent/updated package on your QNAP.
Give this one a try. :) http://apps.qnap.community/11-community/17-qsickrage

**Comment by noze2000** [comment]
thanks.

Did that and the torrent sites now work:)

...but the unrar error is now back:/
( unrar executable not found)

I foget how I fixed tht in the first place..

**Comment by miigotu** [comment]
try `ipkg install unrar`
