### ISSUE TITLE
Newznab provider usenet-crawler not finding Anime shows

### ISSUE THREAD

**Issue by KontiSR** [SiCKRAGETV/sickrage-issues#2408]
The nzb provider usenet-crawler is a newznab provider. But it seems they are not using the api as documented in "http://newznab.readthedocs.org/en/latest/misc/api/?highlight=rid".

The "newznab" like constructed search url is not finding the shows. 

But changing rid= to tvrage= and ep= to episode= doest find the entries.

An example of a working searchstring (just fill in your api key).
https://www.usenet-crawler.com/api?apikey=yourkey&maxage=4&cat=5070&q=Naruto.Shippuuden&limit=100&attrs=rageid,episode&offset=0&rageid=28090&episode=421&t=tvsearch

I'm willing to fix this myself. But i'd like to start a discussion on the approach, before starting on the solution?

Anyone willing to comment?

**Comment by WebSpider** [comment]
Feel free to fix this. And it would be nice if they would stick to their own docs ;)

**Comment by KontiSR** [comment]
yeah, I was in doubt of adding exceptions to NewznabProvider or creating a new provider.
Earlier I would have added the exceptions. Like I have in the past in sickbeard and sickrage. But I noticed allot has been cleaned up, also for the NewsznabProvider class. That maybe it's better to create a new one.

**Comment by miigotu** [comment]
I think if it is only these 2 changes, it's easier to just change the params when the provider is UC. We have too many separate providers to manage as it is xD

**Comment by KontiSR** [comment]
Should I put my CR against dev or master?

**Comment by miigotu** [comment]
Against develop

**Comment by autronix** [comment]
I had the same issue, here is what I did:

in sickbeard/providers/newznab.py

line 181 - padded episode with leading 0
```python
-params['ep'] = "%i" % int(ep_obj.scene_absolute_number if int(ep_obj.scene_absolute_number) > 0 else ep_obj.scene_episode)

+params['ep'] = "%02i" % int(ep_obj.scene_absolute_number if int(ep_obj.scene_absolute_number) > 0 else ep_obj.scene_episode)
```

lines 188-191 - replaced rid attribute with tvrage
```python
-if rid:
-params['rid'] = rid
-elif 'rid' in params:
-params.pop('rid')

+if rid:
+params['tvrage'] = rid
+elif 'tvrage' in params:
+params.pop('tvrage')
```

this changed allowed sickrage to snatch what I previously couldn't

**Comment by KontiSR** [comment]
Yes, that a comparable solution as what I have. Except for padding the episode does not work for me. I really need to pass the paramater episode in stead of ep. You can try that with the example i posted.

**Comment by miigotu** [comment]
`params['ep'] = "%02i" % int(ep_obj.scene_absolute_number if int(ep_obj.scene_absolute_number) > 0 else ep_obj.scene_episode)`

This does not pad the string with a leading zero, it forces it to 2 digits, so if the episode is `"1"`, it becomes `"01"`, if it is `"001"` if becomes `"01"`, but tell me what happens when you format `"201"` to `"%02i"`

**Comment by KontiSR** [comment]
Okay, so it only change single digit to two digit. 201 converts to 201. Still having doubts that this was the issue. As I was having issues with anime shows not downloading with eps numbered over 99.

**Comment by miigotu** [comment]
Agree, that change does nothing in they eyes of newznab afaik, because they trim leading zero.

**Comment by autronix** [comment]
@miigotu you make an excellent point, I copmletely neglected 100+ numbering, you are also correct in that padding does not affect the episode parameter.

However in my searches with both nzb.su and usenet-crawler (based on my debug logs) the episode parameter is not included in the API call and the actual episode number added to the search query like such (actual query with the modification I made to newznab.py):

``
https://www.usenet-crawler.com/api?apikey=******&maxage=8&cat=5030%2C5040%2C5070&q=God.Eater+03&limit=100&attrs=rageid&offset=0&tvrage=49260&t=tvsearch
``

In this scenario the actual leading zero yields a result in the search while the lack of it does not.

I am not entirely sure why my searches do not include the "episode" parameter and the ep number only reflected in the query.

The alternative proposed with the episode parameter also yields a result:

``
https://www.usenet-crawler.com/api?apikey=********&maxage=8&cat=5030%2C5040%2C5070&q=God.Eater&limit=100&attrs=rageid,episode&offset=0&tvrage=49260&episode=3&t=tvsearch
``

**Comment by KontiSR** [comment]
Hi autronix, maybe this fix now also works for you? Would you be willing to test?
You can follow the PR here: https://github.com/SiCKRAGETV/SickRage/pull/2261/files

**Comment by fernandog** [comment]
what about tvdb ?

**Comment by KontiSR** [comment]
Don't think newznab providers index on tvdb id's

**Comment by fernandog** [comment]
nzbgeek does

**Comment by KontiSR** [comment]
Yeah but the newznab api does not offer the possibility to search using tvdb id. Then maybe nzbgeek has implemented something them selves?

**Comment by fernandog** [comment]
@miigotu what do you think?

**Comment by KontiSR** [comment]
@miigotu What do you think of this?:
https://github.com/KontiSR/SickRage/commit/9ee199cc1564987511b1313be5409129b865663d

**Comment by miigotu** [comment]
@KontiSR no can do. First your commit doubles the amount of strings added. Second I am keeping it exactly as they asked me to make it for now.

**Comment by KontiSR** [comment]
@miigotu  My commit does not always doubles it. For example, in your current version, when you have for ex. 5 scene exceptions, and it doesn't get a result from the first search string, it will always go through 6 searches. In my version, it will add another 5 search strings. That's true, but it will also stop if it has a result at the the first scene exception.

**Comment by miigotu** [comment]
We don't want that right now. Using the exact same behavior as SB for now (except for a longer delay between requests).

**Comment by KontiSR** [comment]
That's fine with me.
