### ISSUE TITLE
Archive on first match doesn't seem to be triggered on manual pp

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2410]
@miigotu knows about this. Just adding it for reference.

**Comment by fernandog** [comment]
@OmgImAlexis still an issue? confirmed?

**Comment by OmgImAlexis** [comment]
You'll have to ask @miigotu I can't remember if he's fixed this yet and I don't use it anymore as it's still being worked on.

**Comment by WebSpider** [comment]
I'm using manual PP and archive first match works. Closing issue for now.
