### ISSUE TITLE
Auto postprocessing not working

### ISSUE THREAD

**Issue by angelda** [SiCKRAGETV/sickrage-issues#2411]
Hi,

For starters, I use the Synology Sickrage version: 
SR Version:	BRANCH: (master) / COMMIT: (477e80a6a748067e325c78aba3550f1887f39a4c) 
SR User:	sickbeard-custom
SR Locale:	('en_US', 'UTF-8')
SR Config file:	/usr/local/sickbeard-custom/var/config.ini
SR Database file:	/usr/local/sickbeard-custom/var/sickbeard.db
SR Cache Dir:	/usr/local/sickbeard-custom/var/cache
SR Log Dir:	/usr/local/sickbeard-custom/var/Logs
SR Arguments:	['--daemon', '--pidfile', '/usr/local/sickbeard-custom/var/sickbeard-custom.pid', '--config', '/usr/local/sickbeard-custom/var/config.ini', '--datadir', '/usr/local/sickbeard-custom/var/', '--nolaunch']
Python Version:	2.7.10 (default, Jun 3 2015, 13:42:00) [GCC 4.6.4]

What happens:
Since a few days, the autopostprocessing doesn't seem to be working anymore. Every episode downloaded stays in "Snatched" status and the files stay in the download folder as well. 
However, if I launch the manual postprocessing, the files are properly processed.

What I've done so far: 
I've activated the logs during the night and checked them this morning since a bunch of episodes have been downloaded (True Detective, Ballers, The Blink, The Strain, Halt and Catch Fire, Falling Skies) and I don't see anything related with the postprocess. I can see a lot of activity related with the parcing (including show that aren't on my showlist - I don't know if it's normal or not- ) and the downloading process going fine, but nothing seems to happen after.
logfile here:
http://we.tl/AopAEGjo5w

I didn't changed anything in the settings since a while ago.
Any idea if I doing something wrong or if it is a bug ?

**Comment by miigotu** [comment]
It doesnt even try to post process, this tells me the post processor "scan and process" is not enabled. Please check post processor settings.

**Comment by angelda** [comment]
Hi miigotu,

Thanks for handling the ticket.
I checked the setting and the scan and process is enabled.
I looked at the config.ini file and I also can see "process_automatically = 1"
Did a restart (just in case) and still nothing.
I'm out of idea unfortunately.

**Comment by fernandog** [comment]
send a screen shot of all your PP settings please

**Comment by angelda** [comment]
Hi,

I've just made a complete restart of the Synology and the auto postprocessing is now currently running and the files are getting processed.
I can't explain how, but the issue seems resolved for now, so I close the ticket.

Thanks a lot for your time anyway, it's very appreciated.
