### ISSUE TITLE
[Feature Request] Storing Scene named episodes in Scene numbered Season folder.

### ISSUE THREAD

**Issue by gitowok** [SiCKRAGETV/sickrage-issues#2412]
When a show is set to use scene filename (ie not rename), and set to use scene numbering for searches in "Edit" show (and a Full update done), the episode gets stored in the wrong Season folder.

For example this file: 
`Top.Gear.US.S05E10.Appalachian.Trail.720p.HDTV.x264-DHD.mkv`
is recognised as tvdb 4x20, and gets stored in Folder "Season 04", like this:
`Moving file from /home/nzbworker/Downloads/sickbeard-auto-pull/Top.Gear.US.S05E10.Appalachian.Trail.720p.HDTV.x264-DHD.mkv to /mnt/video/episode/Top Gear US/Season 04/Top.Gear.US.S05E10.Appalachian.Trail.720p.HDTV.x264-DHD.mkv`

Here is what it then looks like in the web UI:
![20150804-sickrage-non-scenenumbered-listing-example](https://cloud.githubusercontent.com/assets/2197441/9038893/6a68db4c-3a2a-11e5-8546-99d9cb618ca7.png)

It would be brilliant if there were an option to use scene numbering in the web UI as well as storage, but failing that, could we have an option to use scene Season folders?

Many thanks!

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
