### ISSUE TITLE
Show "News updated" message and add a config with last read news

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#2413]
so when user open news page, we updated the config field with for example: 2015-08-03 and next page loading the message won't show up.
When we update news.md, SR will check the config date with news.md date and show the warning again

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
