### ISSUE TITLE
Multiple SR instances

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2414]
hello ,i ve got a little question is it possible for me to have multiple SR instances on the same machine ,each one with a init.d script?
if it is how can i do it?

**Comment by fernandog** [comment]
can't. because of the port. Can't have two webservers in the same port

**Comment by duramato** [comment]
but cant i have one running on 8081 and other on 1337 ?

**Comment by fernandog** [comment]
that you can
