### ISSUE TITLE
unable to connect to torrent clients

### ISSUE THREAD

**Issue by RackerJack** [SiCKRAGETV/sickrage-issues#2416]
Error: Unable to get Transmission Authentication, check your config!

Branch  `master`
Commit hash `47b2d5651f0c7ef1d8d20523dee85bc950d17e14`
Your operating system and python version `centos 6.6 python 2.7.10`
What you did tried to `add transmission under search settings with custom rpc uri`
What happened `Error: Unable to get Transmission Authentication, check your config!`
What you expected `connection success`
Link to a copy/paste of your logfile with clear debug info of the error on GIST
`debug logs option enabled but nothing valid pointing to this error`

```
2015-08-03 22:46:01 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2015-08-03 22:46:00 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2015-08-03 22:45:58 INFO     DAILYSEARCHER :: No new released episodes found ...
2015-08-03 22:45:57 INFO     MAIN :: Building internal name cache for all shows
2015-08-03 22:45:57 INFO     CHECKVERSION :: Checking for updates using SOURCE
2015-08-03 22:45:57 INFO     DAILYSEARCHER :: Searching for new released episodes ...
2015-08-03 22:45:57 INFO     TORNADO :: Starting SickRage on http://0.0.0.0:5051/
2015-08-03 22:45:57 INFO     MAIN :: Forcing web server to port 5051
```

transmission settings.json

```
{
    "alt-speed-down": 50, 
    "alt-speed-enabled": false, 
    "alt-speed-time-begin": 540, 
    "alt-speed-time-day": 127, 
    "alt-speed-time-enabled": false, 
    "alt-speed-time-end": 1020, 
    "alt-speed-up": 50, 
    "bind-address-ipv4": "0.0.0.0", 
    "bind-address-ipv6": "::", 
    "blocklist-enabled": false, 
    "blocklist-url": "http://www.example.com/blocklist", 
    "cache-size-mb": 4, 
    "dht-enabled": true, 
    "download-dir": "/srv/media/", 
    "download-queue-enabled": true, 
    "download-queue-size": 5, 
    "encryption": 1, 
    "idle-seeding-limit": 30, 
    "idle-seeding-limit-enabled": false, 
    "incomplete-dir": "/srv/opt/transmission/Downloads/", 
    "incomplete-dir-enabled": false, 
    "lpd-enabled": false, 
    "message-level": 2, 
    "peer-congestion-algorithm": "", 
    "peer-id-ttl-hours": 6, 
    "peer-limit-global": 200, 
    "peer-limit-per-torrent": 50, 
    "peer-port": 51413, 
    "peer-port-random-high": 65535, 
    "peer-port-random-low": 49152, 
    "peer-port-random-on-start": false, 
    "peer-socket-tos": "default", 
    "pex-enabled": true, 
    "port-forwarding-enabled": true, 
    "preallocation": 1, 
    "prefetch-enabled": 1, 
    "queue-stalled-enabled": true, 
    "queue-stalled-minutes": 30, 
    "ratio-limit": 2, 
    "ratio-limit-enabled": true, 
    "rename-partial-files": true, 
    "rpc-authentication-required": false, 
    "rpc-bind-address": "0.0.0.0", 
    "rpc-enabled": true, 
    "rpc-password": "", 
    "rpc-port": 9091, 
    "rpc-url": "/torrent/", 
    "rpc-username": "cloud", 
    "rpc-whitelist": "127.0.0.1", 
    "rpc-whitelist-enabled": false, 
    "scrape-paused-torrents-enabled": true, 
    "script-torrent-done-enabled": false, 
    "script-torrent-done-filename": "", 
    "seed-queue-enabled": false, 
    "seed-queue-size": 10, 
    "speed-limit-down": 100, 
    "speed-limit-down-enabled": false, 
    "speed-limit-up": 100, 
    "speed-limit-up-enabled": false, 
    "start-added-torrents": true, 
    "trash-original-torrent-files": false, 
    "umask": 18, 
    "upload-slots-per-torrent": 14, 
    "utp-enabled": true, 
    "watch-dir": "/srv/opt/transmission/", 
    "watch-dir-enabled": true
}
```

**Comment by RackerJack** [comment]
also tried with deluge no success

**Comment by fernandog** [comment]
Please post full screen of transmission settings

**Comment by RackerJack** [comment]
hi

@fernandog 
i have posted the settings.json for transmission im not sure what you mean?

**Comment by RackerJack** [comment]
ill also mention couchpotato does not have an issue connecting

**Comment by neoatomic** [comment]
@RackerJack Shutdown Sickrage. Go in your SickRage folder to : *\SickRage\sickbeard\clients
Remove all the *.pyc files and overwrite all the *.py files with the one's form the same folder below. 
https://github.com/SiCKRAGETV/SickRage/archive/master.zip
Restart Sickrage. See if that solvs your problem.

**Comment by RackerJack** [comment]
@neoatomic unfortunately this did not fix the issue

**Comment by fernandog** [comment]
you need to enable debug logs in advanced settings and send FULL logs

read here: https://github.com/SiCKRAGETV/sickrage-issues

**Comment by RackerJack** [comment]
```
[root@srv0a sickrage-5051]# ps aux | grep -i sick
501      10581  2.9  0.2 4965832 80416 ?       Sl   14:37   0:03 python2.7 SickBeard.py --port=5051
root     10689  0.0  0.0 103244   896 pts/0    S+   14:39   0:00 grep -i sick
[root@srv0a sickrage-5051]# ps aux | grep -i sick
root     10691  0.0  0.0 103244   896 pts/0    S+   14:39   0:00 grep -i sick
[root@srv0a clients]# rm -rf *.pyc
[root@srv0a clients]# ll
total 16664
-rw-r--r-- 1 root root     8023 Aug  3 16:21 deluge_client.py
-rw-r--r-- 1 root root     2684 Aug  3 16:21 download_station_client.py
-rw-r--r-- 1 root root     9459 Aug  3 16:21 generic.py
-rw-r--r-- 1 root root     3669 Aug  3 16:21 __init__.py
-rw-r--r-- 1 root root     2436 Aug  3 16:21 qbittorrent_client.py
-rw-r--r-- 1 root root     5233 Aug  3 16:21 rtorrent_client.py
-rw-r--r-- 1 root root     5278 Aug  3 16:21 transmission_client.py
-rw-r--r-- 1 root root     4471 Aug  3 16:21 utorrent_client.py
[root@srv0a clients]# wget https://github.com/SiCKRAGETV/SickRage/archive/master.zip && unzip master.zip -d sick1
--SNIP---
[root@srv0a clients]# mv sick1/SickRage-master/sickbeard/clients/* .
mv: overwrite `./deluge_client.py'? y
mv: overwrite `./download_station_client.py'? y
mv: overwrite `./generic.py'? y
mv: overwrite `./__init__.py'? y
mv: overwrite `./qbittorrent_client.py'? y
mv: overwrite `./rtorrent_client.py'? y
mv: overwrite `./transmission_client.py'? y
mv: overwrite `./utorrent_client.py'? y
[root@srv0a clients]# rm -rf master.zip sick1/
[root@srv0a clients]# cd ../../
[root@srv0a sickrage-5051]# su -c 'nohup python2.7 SickBeard.py --port=5051 &' -s /bin/bash transmission
[root@srv0a sickrage-5051]# nohup: appending output to `nohup.out'

[root@srv0a sickrage-5051]# 
```
test connection = 
Error: Unable to get Transmission Authentication, check your config!

**Comment by RackerJack** [comment]
@fernandog debug logs are on
```
[root@srv0a sickrage-5051]# grep debug config.ini
debug = 1
```
theres just nothing in there

**Comment by fernandog** [comment]
so in log views set min level to DEBUG and send full logs

also you don't need to check config.ini. You can read here as I already asked you:
https://github.com/SiCKRAGETV/sickrage-issues#enabling-detailed-debugging-for-logs

**Comment by RackerJack** [comment]
where do i go to see setting log views? 

debug logging is enabled as per

general > advanced 
Enable debug is checked

here is the log file 
http://sprunge.us/iSEf

but theres nothing obvious in there

**Comment by fernandog** [comment]
you have a lot of errors:

```
2015-08-04 11:53:12 ERROR    SEARCHQUEUE-MANUAL-266883 :: [HDBits] :: Authentication error: Your authentication credentials for HDBits are incorrect, check your config.
```

is that so hard to find?!

http://localhost:8081/errorlogs/viewlog/

check menus! and read some tutorials about how to proper setup SR

**Comment by RackerJack** [comment]
@fernandog do you see any errors related to the issue i am facing??

no

# debug logs option enabled but nothing valid pointing to this error

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by fernandog** [comment]
does not matter! send full logs after "testing connectino" in transmission
and send full screen shot of your transmission settings in SR

**Comment by RackerJack** [comment]
transmission settings:
http://screencloud.net/v/vsqL

new log file from restart and after testing connection:
http://sprunge.us/YHBN

**Comment by fernandog** [comment]
there is no "transmission" in your log
check your log again for the same error as in UI

**Comment by fernandog** [comment]
did you tried localhost instead of 127...?

**Comment by RackerJack** [comment]
hi

ive tried with localhost same issue

im not sure why theres no log entries for the same i see in the ui

even after spamming the test button a few times nothing shows up in the logs

**Comment by fernandog** [comment]
do you have teamviewer? send me via IRC

**Comment by fernandog** [comment]
click my name, choose message and send user/pass

**Comment by RackerJack** [comment]
ill message you on irc when i get home

**Comment by RackerJack** [comment]
will you be available today?

**Comment by fernandog** [comment]
now I can

**Comment by RackerJack** [comment]
im home at 6pm BST ill try get you then

**Comment by RackerJack** [comment]
heres the things i have tried

changing the RPC bind address (localhost / VPN ip address)

```
jack@home:~$ curl -XPOST http://10.8.0.21:9091/torrent/rpc/
{"arguments":{},"result":"no method name"}
jack@home:~$ curl -I -XPOST http://10.8.0.21:9091/torrent/rpc/
HTTP/1.1 200 OK
Server: Transmission
Content-Type: application/json; charset=UTF-8
Date: Wed, 05 Aug 2015 20:45:46 GMT
Content-Length: 43
```
no issues reaching this from my home pc to the server over the vpn like wise with using the vpn ip on the server and localhost

```
[root@srv0a opt]# curl -I -XPOST http://10.8.0.21:9091/torrent/rpc/
HTTP/1.1 200 OK
Server: Transmission
Content-Type: application/json; charset=UTF-8
Date: Wed, 05 Aug 2015 20:48:43 GMT
Content-Length: 43

[root@srv0a opt]# curl -I -XPOST http://127.0.0.1:9091/torrent/rpc/
HTTP/1.1 200 OK
Server: Transmission
Content-Type: application/json; charset=UTF-8
Date: Wed, 05 Aug 2015 20:48:51 GMT
Content-Length: 43
```

i have tried enabling rpc auth with username / pass SR still does not connect ( i can connect to transmission web-ui with these details)

the issue is definitely with SR as i have no issues with couchpotato no issues with network connectivity

**Comment by fernandog** [comment]
@RackerJack try instead of localhost/127..

sudo ifconfig <- ip of wlan0 or eth0 form that, not tun0 or localhost

**Comment by fernandog** [comment]
@RackerJack also try instead of just torrent: torrent/rpc

**Comment by fernandog** [comment]
@miigotu already adds the /rtc

https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/clients/transmission_client.py#L42

**Comment by miigotu** [comment]
it doesnt work for me without adding rpc

**Comment by fernandog** [comment]
but that code is pretty simple. remove slashes and add /rpc

**Comment by miigotu** [comment]
If users follow most of the guides and use a local redirect or something like nginx they need it.  my rpc url in SR settings is just rpc

**Comment by fernandog** [comment]
but how does it work in couchpotato? same settings: "localhost" and "torrent"?

Did you see the CP issue about not connecting and how they fix it?

**Comment by miigotu** [comment]
Nope I dont know what CP issue you are talking about, but pretty sure it has nothing to do with our code.

**Comment by fernandog** [comment]
@RackerJack so? did you try all that??

**Comment by RackerJack** [comment]
i have used the public ip (after opening the firewall) no luck
i have used
torrent_verify_cert = 0
and
torrent_verify_cert = 1
no luck

i have tried the rpc url as `torrent/rpc` no luck

**Comment by RackerJack** [comment]
i even strace'ed the process and compared the "test connection" from cp and sr they both look the sameish... but its hard to interpret strace

**Comment by fernandog** [comment]
@RackerJack what about this?

https://github.com/SiCKRAGETV/sickrage-issues/issues/2416#issuecomment-128191163

**Comment by fernandog** [comment]
@RackerJack it used to work to you. You changed something in your config

https://github.com/SiCKRAGETV/sickrage-issues/issues/264#issuecomment-72188046

**Comment by RackerJack** [comment]
yes this is on a different server

**Comment by fernandog** [comment]
so SR is working and it's something in your setup

**Comment by RackerJack** [comment]
but that doesnt explain why cp works on the new server and sr doesnt

**Comment by fernandog** [comment]
@RackerJack 

search your log for (debug must be enabled and min log view: DEBUG: 

DEBUG    Thread :: Transmission: Requested a POST connection to url http://localhost:xxxx/transmission/rpc with Params= {} Data={"arguments": {}, "method": "session-get"}

**Comment by RackerJack** [comment]
nothing like that in there

[root@srv0a Logs]# grep Requested sickrage.log
[root@srv0a Logs]#

**Comment by fernandog** [comment]
You need to add * before and after Requested

Use log search in SR also

**Comment by RackerJack** [comment]
hrm it must be something with my setup.... i copied the same sickrage dir from the working server and i get the same thing

let me know if you get another issue like this

consider this solved
