### ISSUE TITLE
Add a Show is no longer present

### ISSUE THREAD

**Issue by donbrew** [SiCKRAGETV/sickrage-issues#2417]
Branch: [master]
Commit hash: don't know, whatever github gave me 10 minutes ago
Your operating system and python version:  Windows 7 Ultimate Python 2.7
What you did:  nothing
What happened: nothing
What you expected:  want to add a new show

SickRage has been working fine for months.  All of a sudden there is no way to Add a New Show.  I uninstalled and re installed.  "Shows" does not have a dropdown.
![sickrage](https://cloud.githubusercontent.com/assets/13632411/9049136/e37346bc-3a0c-11e5-83bf-7803a230340b.PNG)

**Comment by neoatomic** [comment]
![1](https://cloud.githubusercontent.com/assets/7928052/9049905/b18c6cf6-3a47-11e5-97d4-7feb246e13d4.png)

**Comment by donbrew** [comment]
AHHH, it does not show when the browser window is in full screen.

![sr1](https://cloud.githubusercontent.com/assets/13632411/9059374/6d1db9b4-3a77-11e5-8c6d-92ec6121090a.PNG)
![sr2](https://cloud.githubusercontent.com/assets/13632411/9059376/73b8f432-3a77-11e5-8c02-c3401aabff90.PNG)
