### ISSUE TITLE
[APP SUBMITTED]: 'charmap' codec can't encode character u'\u200b' in position 52: character maps to <undefined>

### ISSUE THREAD

**Issue by mbxplex** [SiCKRAGETV/sickrage-issues#2418]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@47b2d5651f0c7ef1d8d20523dee85bc950d17e14
Link to Log: https://gist.github.com/dffa5d31d3fc9a906ebf
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: charmap : Download Finished : Conan (2010) - 2015x96 - Ice-T &â€‹ Coco, Jimmy Pardo - HDTV : error 52 : error 53 : character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Special character `&​` is the problem. Check your Locale.

**Comment by neoatomic** [comment]
@fernandog Cant we change this error into a warning that the user needs to check there locale.?` 'charmap' codec can't `

**Comment by fernandog** [comment]
need to create a special code for this.
with python3 this will be fixed
