### ISSUE TITLE
Anime Downloading/Naming issue

### ISSUE THREAD

**Issue by syrys** [SiCKRAGETV/sickrage-issues#2419]
I just discovered an issue with anime naming/parsing happening with sickrage, and im not entirely sure if there is any setting i can use to fix this. Most of the blame should probably be targeted towards the anime it self and their stupid naming conventions, but i cant really ask them to change it :(

Using the latest sickrage on windows 8.1

So the anime in question is `Fairy Tail`.

`Fairy tail` has about 250 episodes. According to sickrage, its divided into 6 seasons (suppose chapters? i dont know), but according to most providers its divided into 2 seasons, and for others, its 1 long season.

For example, the latest episode is
````
Fairy Tail 244
or Fairy Tail S2 69
or theTVDB: Fairy Tail Season 6 Episode 18 (http://thetvdb.com/?tab=season&seriesid=114801&seasonid=617624&lid=7)
````
The issue is, When you download a file like `Fairy Tail S2 69` (this is the way most torrents list it as), it assumes This is `Fairy Tail 69` which is incorrect.

how would i go about fixing this without manually downloading and renaming every time?

**Comment by bb12489** [comment]
This is also been an issue for me recently. however it seemed to of scrapped just fine into my library previously. I think it's only been the last 3-4 episodes of S2 when this issue started.

**Comment by KontiSR** [comment]
I have configured the show as an Anime and I have enabled the option "scene numbering".
Also fairy tail is depending on the mapping of the scene numbering to absolute numbering. And for that the website/service www.thexem.de is used. Altough I also don't know exactly how that works.

I suspect that new episodes need to be added there manually. When new episodes haven't been added to thexem yet, sickrage could also have troubles finding them.

But I'd just start with setting the Anime and Scene numbering, and go from there.

**Comment by KontiSR** [comment]
Hmm okay, I think i'm on to some bugs. I commented on them here. I'll do some more testing.
Problem currently is that someone made changes to the whitelisting logic, which I suspect broke it.

See my comments: https://github.com/SiCKRAGETV/SickRage/commit/1ea2229f9660d6e05ceda8636b75b111f40a5ffd

That would have impacted tokyotosho and nyatorrent. If found another issue, where nyatorrent, isn't using the proper Scene Exception season names.

Nyatorrent could still be an issue, I think the regex has issues with naming nya uses. Have to dive in the regexes for that.

You can try my fixes on my fork. I've cherry picked the commits that I have tested Fairy Tail with. It's based on SICKRAGETV/develop

**Comment by syrys** [comment]
yeah, same here. Worked fine couple of months back. I think last few epesodes, naming conventions may have changed :(

**Comment by h3llrais3r** [comment]
There was a problem with the xem refresh functionality.
It should have been fixed with my PR https://github.com/SiCKRAGETV/SickRage/pull/2208, which has already been merged in master.

**Comment by neoatomic** [comment]
@h3llrais3r Thanks for the PR and updating the issue.

@syrys Can you verify if its solved now.?
