### ISSUE TITLE
rTorrent: Unable to send Torrent: Return code undefined

### ISSUE THREAD

**Issue by AdamWhite** [SiCKRAGETV/sickrage-issues#242]
Using Qnap 453 Pro x86.
rTorrent: 0.9.2-0513

From SickRage:
SR Version: 	BRANCH: (master) / COMMIT: (49ea8f5ac7841f6654509d48d72506923bc47c2a)
SR Config file:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/config.ini
SR Database file:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/sickbeard.db
SR Cache Dir:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/cache
SR Arguments:	['--daemon', '--datadir', '/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config', '--pidfile', '/tmp/SickBeard-TVRage.pid', '--nolaunch']
SR Web Root:	
Python Version:	2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]

rTorrent Host:Port: <nasip>:6009
rTorrent Username: <rTorrentUser>
rTorrent Password: <rTorrentUserPassword>
Add Label To Torrent: TV
Add label to torrent for anime: Anime
Download files location: /share/Download/sabnzbd/complete/TV

Test connection result: Success: Connected and Authenticated

Error that shows in the logs when attempting to add a torrent to rTorrent via automated search:
```
2014-12-21 09:45:21 SEARCHQUEUE-BACKLOG-152831 :: rTorrent: Unable to send Torrent: Return code undefined
```

If I can provide any further information please let me know

**Comment by Semsettin** [comment]
I get the same error "rTorrent: Unable to send Torrent: Return code undefined".

Using Synology DS415+
rtorrent/0.9.4/0.13.4	


2015-01-14 23:38:08 DEBUG    SEARCHQUEUE-BACKLOG-263365 :: Calling rTorrent Client
2015-01-14 23:38:17 DEBUG    TORNADO :: Failed doing webui request "api/a58c7abdff16013d2817124287e6286e": Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 214, in get
    method = getattr(self, route)
AttributeError: 'WebRoot' object has no attribute 'api/a58c7abdff16013d2817124287e6286e'

2015-01-14 23:38:37 DEBUG    TORNADO :: Failed doing webui request "api/a58c7abdff16013d2817124287e6286e": Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 214, in get
    method = getattr(self, route)
AttributeError: 'WebRoot' object has no attribute 'api/a58c7abdff16013d2817124287e6286e'

2015-01-14 23:38:39 ERROR    SEARCHQUEUE-BACKLOG-263365 :: rTorrent: Unable to send Torrent: Return code undefined
None
2015-01-14 23:38:57 DEBUG    TORNADO :: Failed doing webui request "api/a58c7abdff16013d2817124287e6286e": Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 214, in get
    method = getattr(self, route)
AttributeError: 'WebRoot' object has no attribute 'api/a58c7abdff16013d2817124287e6286e'

2015-01-14 23:38:57 DEBUG    TORNADO :: Failed doing webui request "api/a58c7abdff16013d2817124287e6286e": Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 214, in get
    method = getattr(self, route)
AttributeError: 'WebRoot' object has no attribute 'api/a58c7abdff16013d2817124287e6286e'

**Comment by nytemyst** [comment]
I'm having the exact same issue any update on this?

**Comment by fernandog** [comment]
@AdamWhite @Semsettin @nytemyst 

is this still happening in the latest DEVELOP version?

**Comment by abeloin** [comment]
Question: 
* What is the schema used to connect to rtorrent? scgi or http(s)
* If you use authentication on http, which type? Basic or Digest

**Comment by nytemyst** [comment]
Does not work on the latest develop version
used both scgi and http.
There's no option for basic or digest.

**Comment by abeloin** [comment]
@nytemyst For http I'm looking for which type the web server is asking.

**Comment by nytemyst** [comment]
I'm using a seedbox so i'm not sure where i would be able to find that information. I guess i can email them and see the response I get.

**Comment by abeloin** [comment]
@nytemyst no need for now as the rtorrent library in sickrage doesn't handle https connection and scgi is only good for local connection.

To check for the authorization type login, while you try to open rutorrent's webpage check in developer network console the next request after the one were you get a 401 error. If you digest or nonce it's digest.

**Comment by abeloin** [comment]
@AdamWhite @Semsettin Is your rtorrent on the same machine as sickrage?

**Comment by AdamWhite** [comment]
It is. Though it may be configured to talk via no-ip address. Will check
tomorrow when I am home.

On Sunday, January 25, 2015, Alexandre Beloin <notifications@github.com>
wrote:

> @AdamWhite <https://github.com/AdamWhite> @Semsettin
> <https://github.com/Semsettin> Is your rtorrent on the same machine as
> sickrage?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/242#issuecomment-71390716>
> .
>


-- 
Sent from Gmail Mobile

**Comment by abeloin** [comment]
@AdamWhite And your host: port is: scgi://localhost:6009/ ?

**Comment by AdamWhite** [comment]
Will let you know  tomorrow. I am on my phone and have no access to the to
my NAS to check for you.

On Sunday, January 25, 2015, Alexandre Beloin <notifications@github.com>
wrote:

> @AdamWhite <https://github.com/AdamWhite> And your host: port is:
> scgi://localhost:6009/ ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/242#issuecomment-71391337>
> .
>


-- 
Sent from Gmail Mobile

**Comment by abeloin** [comment]
@fernandog This pull request SiCKRAGETV/SickRage#1244 should help resolve issues regarding the http part of connection to rtorrent.

**Comment by fernandog** [comment]
Thanks!!

**Comment by fernandog** [comment]
That PR is huge! thanks a lot =)

**Comment by AdamWhite** [comment]
Just an update, my connection is http://<ip>:6009


-- 
Adam White

On 26 January 2015 at 09:31:27, Fernando (notifications@github.com) wrote:

That PR is huge! thanks a lot =)

**Comment by abeloin** [comment]
@AdamWhite ok, since you sickrage and rtorrent are on the same machine you should use scgi instead(no username and password). Look in your .rtorrent.rc for a line starting with:
```
scgi_port = localhost:6009
```
to confirm your port is 6009.

**Comment by abeloin** [comment]
@fernandog I had to update the requests library to use disable_warnings and this is why it is so big. If you look at the second commit, which is the were the real changes are, it's rather small. The good thing is that I didn't had to create an xml transport adapter from scratch since it's the one I use to check and transfer files from a seedbox.

**Comment by fernandog** [comment]
@abeloin I see. I thought you wrote all of that =)

**Comment by abeloin** [comment]
@fernandog I'm not that good ;)

**Comment by baskinghobo** [comment]
Same issue here which sucks because i notice btsync+black hole is a lot slower then directly through rtorrent.

**Comment by AdamWhite** [comment]
I've changed to scgi:// and thats working, so thanks for that.. I've also moved to the development branch and i am liking the change to the progress bars. However still getting the same issue mentioned above, and the issues persists, I had to wait a few days for the error to show in the logs, thought @abeloin's fix may not have been merged into the dev branch yet. So looking forward to seeing the results!

**Comment by abeloin** [comment]
@AdamWhite Can you apply this [pull request 1244](SiCKRAGETV/SickRage#1244)(Not included in the dev branch) and let me know if you still see the "Return code undefined"

**Comment by abeloin** [comment]
@AdamWhite Did you try applying the pull request?

**Comment by AdamWhite** [comment]
Sorry no, I meant to respond, I don't know now to, sickrage is on my NAS and I can only SSH into the folder which has sickrage. I've been hoping that it would be pulled into the develop branch so I can update and test. If I set sickrage to use your PR via the UI, let me know and i'll give it a test

**Comment by fernandog** [comment]
@AdamWhite no reply = close issue

**Comment by AdamWhite** [comment]
@fernandog did you not see my response before you closed the issue?

**Comment by fernandog** [comment]
We need confirm its working before merge it.

**Comment by AdamWhite** [comment]
I'm happy to test it, I just need to know how

**Comment by fernandog** [comment]
Stop SR, edit your local file, start SR

**Comment by AdamWhite** [comment]
OK, but you say edit my local file... edit it to what? how do I pull and merge the PR onto my installed version of SR?

**Comment by abeloin** [comment]
If sickrage folder on the nas is under git control, you could simply download a diff of the pull request from https://github.com/SiCKRAGETV/SickRage/pull/1244.diff on the nas.
* Stop sickrage
* Apply it with ```patch -p1 < path/to/1244.diff``` inside sickrage's folder.
* Start sickrage

To revert after(be careful with the rm -rf command, make sure you the good path):
* Stop sickrage
```
rm -rf path/to/sickrage/lib/requests/*
git checkout develop
```
* Start sickrage

**Comment by AdamWhite** [comment]
Thanks I will give this a go and let you know by tomorrow.

**Comment by AdamWhite** [comment]
So i've downloaded the patch, doing git apply path/to/1244.dff

diff was applied with this warning:
1244.diff:16: space before tab in indent.
#set $selected = $html_selected if $sickbeard.TORRENT_AUTH_TYPE == $authvalue else ''
warning: 1 line adds whitespace errors.
if I do a git status it shows a chunk of modified files.

But the webpage for sickrage just won't load, if i remove the diff and go back to a clean develop branch, the webpage comes up.

**Comment by abeloin** [comment]
Try adding ```-l ``` to the patch option. It will ignore whitespace

This is my result on develop, fresh git clone then git checkout develop:
```
[SickRage]$ patch -p1 -l < 1244.diff 
patching file gui/slick/interfaces/default/config_search.tmpl
patching file gui/slick/js/configSearch.js
patching file lib/requests/__init__.py
patching file lib/requests/adapters.py
patching file lib/requests/api.py
patching file lib/requests/auth.py
patching file lib/requests/certs.py
patching file lib/requests/compat.py
patching file lib/requests/cookies.py
patching file lib/requests/exceptions.py
patching file lib/requests/models.py
patching file lib/requests/packages/__init__.py
patching file lib/requests/packages/chardet/__init__.py
patching file lib/requests/packages/chardet/chardetect.py
patching file lib/requests/packages/chardet/jpcntx.py
patching file lib/requests/packages/chardet/latin1prober.py
patching file lib/requests/packages/chardet/mbcssm.py
patching file lib/requests/packages/chardet/sjisprober.py
patching file lib/requests/packages/chardet/universaldetector.py
patching file lib/requests/packages/urllib3/__init__.py
patching file lib/requests/packages/urllib3/_collections.py
patching file lib/requests/packages/urllib3/connection.py
patching file lib/requests/packages/urllib3/connectionpool.py
patching file lib/requests/packages/urllib3/contrib/ntlmpool.py
patching file lib/requests/packages/urllib3/contrib/pyopenssl.py
patching file lib/requests/packages/urllib3/exceptions.py
patching file lib/requests/packages/urllib3/fields.py
patching file lib/requests/packages/urllib3/filepost.py
patching file lib/requests/packages/urllib3/packages/ordered_dict.py
patching file lib/requests/packages/urllib3/packages/ssl_match_hostname/__init__.py
patching file lib/requests/packages/urllib3/poolmanager.py
patching file lib/requests/packages/urllib3/request.py
patching file lib/requests/packages/urllib3/response.py
patching file lib/requests/packages/urllib3/util.py
patching file lib/requests/packages/urllib3/util/__init__.py
patching file lib/requests/packages/urllib3/util/connection.py
patching file lib/requests/packages/urllib3/util/request.py
patching file lib/requests/packages/urllib3/util/response.py
patching file lib/requests/packages/urllib3/util/retry.py
patching file lib/requests/packages/urllib3/util/ssl_.py
patching file lib/requests/packages/urllib3/util/timeout.py
patching file lib/requests/packages/urllib3/util/url.py
patching file lib/requests/sessions.py
patching file lib/requests/status_codes.py
patching file lib/requests/structures.py
patching file lib/requests/utils.py
patching file lib/rtorrent/__init__.py
patching file lib/rtorrent/lib/xmlrpc/requests_transport.py
patching file sickbeard/__init__.py
patching file sickbeard/clients/rtorrent.py
patching file sickbeard/webserve.py
```

**Comment by AdamWhite** [comment]
@abeloin My nas doesn't have the patch command, the only equivalent that I can find is "git apply" even with setting --ignore-whitespace I still get the same issue.   Happy to follow any advice to test this correctly

**Comment by AdamWhite** [comment]
@abeloin i've installed patch via "ipkg install patch" and run "patch -p1 -l < /path/to/1244.diff" (without the quotation marks)

which patches with no errors, however the webpage still won't come up, i've looked in the logs and I get no errors. I'm at a loss as to what to do

**Comment by abeloin** [comment]
@AdamWhite When you started sickrage after the patch did it generate a log at all in Logs/sickrage.log? What do you mean the web page won't come up? Invalid address, timeout?

My guess would be there's an error and sickrage won't start. Have you tried running sickrage manually?

**Comment by AdamWhite** [comment]
I checked all the sickbeard and sickrage.log files and none were at the time of the start.  as for the webpage not coming up, its an instant timeout as if there wasn't anything listening on that port. i'll give it another go now, check logs and see if i can start it manually

**Comment by abeloin** [comment]
Definitely an error at startup.

**Comment by AdamWhite** [comment]
re-applied the patch. 
same issue the webpage instantly failed to load on port 7073. 
attempted to load SickBeard.py manually... failed
install coreutils via "ipkg install coreutils"
ran sick rage via "nohup python SickBeard.py"
which outputted to a file, the error i get is: The Python module Cheetah is required

**Comment by abeloin** [comment]
@AdamWhite Have you set the proper permissions for the user running sickrage? As you probably run the patch command as root.

**Comment by abeloin** [comment]
@AdamWhite You need to install cheetah

**Comment by AdamWhite** [comment]
yeah the user has the permissions, i'm running ssh via the same user. 

As for cheetah, as SickRage works without the patch, why suddenly do I require cheetah? now to find out how to get cheetah installed on a qnap nas

**Comment by abeloin** [comment]
Look for which version of python you have: ipkg list_installed

if 2.7:
```
ipkg install py27-cheetah
```

Ref: http://www.sickbeard.com/forums/viewtopic.php?f=4&t=5437

**Comment by AdamWhite** [comment]
If only it was that easy, the fix is to do "python setup.py install" 
unfortunately that returns "The Python module py2exe is required"

I have to assume that the creator of this ipkg has done something special... otherwise sickrage would have never worked and by manually applying this pack i've undone something specifically in place to ensure sickrage works on the qnap

**Comment by abeloin** [comment]
@AdamWhite Looking some doc you can have multiple version of python on your device. Make sure you specify the good one: e.g.
```
/usr/local/python/bin/python2.7 /volume1/@appstore/sickbeard/SickBeard.py --daemon
```

**Comment by abeloin** [comment]
If not revert and wait for the pull request to be merged in develop

**Comment by AdamWhite** [comment]
Think i'll have to revert i'm afraid @abeloin I've tried to above, which pointed me at the installed version of python on my nas, same issues, tried to run  path/to/python path/to/sickrage/setup.py install
then trying to run SickBeard.py the same as above.

That failed, but I noticed in my sickrage install there is a Repository folder and within that is Python, so i tried the above again, this time using the Python within the Repository folder.

Unfortunately no success, thank you for baring with me through this. I'm sorry I couldn't be of help.

**Comment by abeloin** [comment]
@AdamWhite Don't worries, we just have have to wait it is merged into develop, now that's the easy part ;)

**Comment by abeloin** [comment]
Pull requests merged in develop

**Comment by fernandog** [comment]
@AAdamWhite please update and report back

**Comment by AdamWhite** [comment]
Will do!
-- 
Adam White

On 16 February 2015 at 14:03:43, Fernando (notifications@github.com) wrote:

@AAdamWhite please update and report back

**Comment by AdamWhite** [comment]
I've tried to test this however no luck as of yet. everytime I click "test connection" for rtorrent I get connection failed, however using the same settings couchpotato connects and passes torrents in with no problems. I've told sickrage to do back log searches etc, so i'll continue to monitor, however as it stands it seems one of the 115 commits I pulled is preventing me from talking to rtorrent.

**Comment by abeloin** [comment]
@AdamWhite What is your connection string?

**Comment by AdamWhite** [comment]
scgi://localhost:5000 (checked the rtorrent file and that port is correct for scgi) tried over http under port 6009 and same issue. this worked before the pull, well worked.... as in I got the error when sickrage tried to talk to rtorrent. 

user/pass sent via http auth "basic" 

the http version is using the NAS's ip on the local network, the same settings as couchpotato

**Comment by abeloin** [comment]
@AdamWhite I've tested with both in scgi and https, here's the results:
![scgi](http://i.imgur.com/o9sDJ0x.png)
![Imgur](http://i.imgur.com/uPQjciD.png)

**Comment by AdamWhite** [comment]
I copied your scgi settings ( essentially removing the user/pass) and it's
working. As for the http. I didn't have the url formatted like yours. I
attempted it but got a 404. None the less will start a search and feedback
my results

On Monday, February 16, 2015, Alexandre Beloin <notifications@github.com>
wrote:

> @AdamWhite <https://github.com/AdamWhite> I've tested with both in scgi
> and https, here's the results:
> [image: scgi]
> <https://camo.githubusercontent.com/3e9eed3c8af8da51370e7741cb372835a9f22ec7/687474703a2f2f692e696d6775722e636f6d2f6f3973444a30782e706e67>
> [image: Imgur]
> <https://camo.githubusercontent.com/982a6efa68e2636dc6503a24364b87e6ee60d917/687474703a2f2f692e696d6775722e636f6d2f7550516a6369442e706e67>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/242#issuecomment-74566447>
> .
>


-- 
Sent from Gmail Mobile

**Comment by abeloin** [comment]
For http it depend on how you installed rutorrent: if it is installed at the server's root then as it is in the screenshot. If not, you must pre-pend the directory it residee.g.: http://domain.local/rutorrent + /plugins...

**Comment by AdamWhite** [comment]
@abeloin I've tested this and it works, to test I disabled the nzb searching, and suddenly I got torrents being added to rTorrent, no errors in sickrage. The only thing to note that doesn't affect this ticket is that although a label was specified within sickrage, the torrent wasn't added under that label. 

Well done and thank you

**Comment by abeloin** [comment]
@AdamWhite I've just tried labeling and it work in rutorrent 3.6 rev2404.

Did you fill both label fields?

**Comment by AdamWhite** [comment]
Yeah both label fields filled in.

However this is rTorrent 0.9.2-0513 which is the latest version of rTorrent available on the qnap site.

**Comment by fernandog** [comment]
@AdamWhite isn't possible to update?

**Comment by AdamWhite** [comment]
The system is new its a qnap 453pro.

But there was some confusion. The rTorrent (the engine) is as about 0.9.2-0513 which is the latest.
The web front end is ruTorrent V3.6 rev 2404.

I'll try changing the labels later and see if there is any difference.

**Comment by abeloin** [comment]
@AdamWhite If i still doesn't work, please provide a copy of log where it send the info to rutorrent.

**Comment by AdamWhite** [comment]
After changing the label within sick rage, I can confirm that it’s working 100% well done! and thank you
-- 
Adam White

On 19 February 2015 at 16:20:06, Alexandre Beloin (notifications@github.com) wrote:

@AdamWhite If i still doesn't work, please provide a copy of log where it send the info to rutorrent.

**Comment by ahaghgoo** [comment]
Hi Adam, I'm wondering how you could hope someone who just got a QNAP NAS on how you applied the patch from @abeloin?  Thanks for the consideration!

**Comment by abeloin** [comment]
@ahaghgoo The patch is in the current version of Sickrage

**Comment by ahaghgoo** [comment]
Thanks @abeloin.  I reviewed everything to make sure I'm up to date but I'm still experiencing this issue. Below's the relevant general info; if there's any additional info that's needed please let me know.  Thanks again for the consideration!  

----
##Configuration
SR Version:	BRANCH: (master) / COMMIT: (ff7aee90fd26db93cc571be1cb5c62a6fcf08e19) 
SR User:	admin
SR Locale:	(None, None)
SR Config file:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/config.ini
SR Database file:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/sickbeard.db
SR Cache Dir:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/cache
SR Log Dir:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/Logs
SR Arguments:	['--daemon', '--datadir', '/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config', '--pidfile', '/tmp/SickBeard-TVRage.pid']
Python Version:	2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]

--

## Log

2015-04-03 17:32:06 ERROR    SEARCHQUEUE-BACKLOG-72231 :: rTorrent: Unable to send Torrent: Return code undefined
2015-04-03 17:31:36 INFO     SEARCHQUEUE-BACKLOG-72231 :: Downloading *************.2015.03.20.720p.HDTV.x264-BATV from BTN
2015-04-03 17:31:25 ERROR    SEARCHQUEUE-BACKLOG-94571 :: rTorrent: Unable to send Torrent: Return code undefined
2015-04-03 17:30:55 INFO     SEARCHQUEUE-BACKLOG-94571 :: Downloading *************.S05.1080p.WEB-DL.DD5.1.H.264-BS from BTN

**Comment by abeloin** [comment]
@ahaghgoo Open a new issue, it's going to be easier to track. My guess it's related to https://github.com/SiCKRAGETV/sickrage-issues/issues/1061 which a pull requests was merged in develop but not in master. The merge develop to master should be done on Sunday

**Comment by ahaghgoo** [comment]
Oh awesome!  Thanks for the heads up!  I'll open a new issue for this in the meantime.
