### ISSUE TITLE
Error searching for a show (adding new show)

### ISSUE THREAD

**Issue by syrys** [SiCKRAGETV/sickrage-issues#2420]
Im trying to add a new show (all indexers, tvRage and theTVDB), and my sickrage console shows the following error. Obviously the search page just times out `search timed out, try again or try another indexer`

Command line error:
````
Connection error ('Connection aborted.', error(10054, 'An existing connection wa
s forcibly closed by the remote host')) while loading URL http://services.tvrage
.com/feeds/search.php, Retrying in 3 seconds...
````

Sickrage Details:
````
SR Version:	BRANCH: (master) / COMMIT: (47b2d5651f0c7ef1d8d20523dee85bc950d17e14) 
````

**Comment by fernandog** [comment]
tvrage issue

**Comment by syrys** [comment]
@fernandog yes, i guessed as much, but shouldnt SickRage not completely stop the search, but continue the search with the other providers, and possibly return some error msg to the frontend saying ("Error searching in tvRage"), yet display any results from theTVDB?

the response message is so un-informative, its actually misleading. heck, sickrage didnt even bother to search try all the indexers.

**Comment by fernandog** [comment]
" Retrying in 3 seconds..."

**Comment by syrys** [comment]
im assuming it was retrying the "tvrage" AGAIN in 3 seconds (i cannot confierm it did or not, logs/console does not show a retry), not theTVDB. It gave absolutely no results, and if it tried theTVDB, it would have. I havent touched it since, but i can do more tests if needed to confirm.

**Comment by swarmier** [comment]
Couldn't/shouldn't there be logic in the search function if tvrage errors out to continue to TVDB?  tvrage is having an issue again and switching to TVDB versus "all indexes" resolved.  Unfortunately it took me an hour of tinkering to get there.

**Comment by WebSpider** [comment]
That would assume there is unique mapping between the indexers and identical, unconflicting content.

This is not the world we live in :)

-----Original Message-----
