### ISSUE TITLE
[Feature Request] HEVC as different quality type

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2421]
Depending on how HEVC file are compressed a lot of the time 720p copies are worse than a H.264 copy. It'd be nice to have an option to differentiate between them so you could do something like have a 1080p HEVC download at the start but a H.264 replace it.

**Comment by OmgImAlexis** [comment]
I don't want to have that though. I don't mind getting a HEVC compressed version on first scan but I'd like it to be replaced.

**Comment by fernandog** [comment]
Cant imagine doing this without a rewrite of all quality code @miigotu

**Comment by miigotu** [comment]
Pretty major change for this stage. I would rather wait until hachoir is used for proper quality detection of downloaded files

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
