### ISSUE TITLE
[Feature Request] Kodi "Clean command" after Deleting show

### ISSUE THREAD

**Issue by tonyschuite** [SiCKRAGETV/sickrage-issues#2422]
After deleting show, can Kodi be notified to clean its library?
Preferably per show.

somthing like this:
curl -i -X POST -d "{\"jsonrpc\": \"2.0\", \"method\": \"VideoLibrary.Clean\",\"params\": {\"directory\": \"Directory/of/show/\"}, \"id\": 1}" -H "content-type:application/json" http://xbmc:xbmc@localhost:8080/jsonrpc

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
