### ISSUE TITLE
[Feature Request] Add date range to episode status management

### ISSUE THREAD

**Issue by kingfenix** [SiCKRAGETV/sickrage-issues#2426]
In the episode status management screen, when choosing to view "skipped" status, could we also have the capability of a date range? for example....show me any episodes with status of skipped that aired between June 1st and July 1st 2015.

Thanks,
Doug

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
