### ISSUE TITLE
Snatching unaired episodes found on search providers

### ISSUE THREAD

**Issue by nevafuse** [SiCKRAGETV/sickrage-issues#2427]
Appears to be caused by the wantedEpisodes method in search.py.  The if block on line 338 seems correct.  Maybe there's an issue with splitCompositeStatus in common.py which isn't converting unaired statuses correctly.

Here are the logs (w/ detailed info removed)...
INFO     SEARCHQUEUE-DAILY-SEARCH :: Downloading .... from ...
INFO     SEARCHQUEUE-DAILY-SEARCH :: [...] :: Quality of ... is SDTV
INFO     SEARCHQUEUE-DAILY-SEARCH :: [...] :: Found result ... at magnet:?xt=...

**Comment by fernandog** [comment]
full logs please

**Comment by miigotu** [comment]
@fernandog this is because of cache working again I think. Need full debug logs.

@nevafuse full debug logs, also if this is tpb, enable verified option to prevent this.

**Comment by miigotu** [comment]
If minseed is set to something responsible like anything > 10, or enable confirmed/verified/ranked in the provider this issue doesnt happen.

RSS/Cache search just searches for all new torrents, if they match a show in your show list they are added to the cache, no matter what the status is.

**Comment by nevafuse** [comment]
Turned on debug, enabled confirmed/ranked/verified users, upgraded to latest master & restarted.

Didn't realize you could set minseed, I'll set that next.

I see the code in ty.py on line 1265.  Looks like it was written to purposely download unaired episodes.  I personally think it should check the airdate but I'm assuming maybe it was set this way in case the airdate is wrong or the episode(s) are re-released.  Would be nice to at least have an option (assuming one does't already exist).

INFO     SEARCHQUEUE-DAILY-SEARCH :: Downloading [episode1_version1] from ThePirateBay
INFO     SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Found result [episode1_version1] at [magnet_link]
DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: [showid]: Loading episode details from DB for episode [episode1]
DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: [showid]: An object for episode [SXXE01] didn't exist in the cache, trying to create it
DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Existing episode status is wanted/unaired/skipped, getting found episode
DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Existing episode status: 1 (Unaired)
DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Any,Best = [ SDTV, SD DVD ] [ None ] Found = [ SDTV ]
DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Checking if found episode [episode1] is wanted at quality SDTV

**Comment by miigotu** [comment]
This should fix it, good job investigating, thanks for saving me some trouble.

This code btw, has not changed since SR fork began. Not sure why it was that way to begin with, just didn't cause problems because rss was broken for torrents.
