### ISSUE TITLE
Post Process is not alive!

### ISSUE THREAD

**Issue by Grincheux41** [SiCKRAGETV/sickrage-issues#2428]
Hi all !

I've got a problem with the automic function "post processing".

If I go to the page "Status", in the table "Scheduler", I can see my process "Post Process" with the column "Alive" at "False"... 

I restart SickRage, and I go back to the page "Status". My process is alive with the countdown with next run at 10m... and 10m after, the process is started!

BUT... after several minutes, it is stopped, with the column "Alive" at "False"...

I can see the apparition of an error in "View Log (Errors)" : 
2015-08-06 00:41:10 POSTPROCESSER :: Exception generated in thread POSTPROCESSER: utf8 : Un Homme idéal (2015) [1080p] Bluray x264-PopHD.mkv : error 11 : error 12 : invalid continuation byte

For your information, I have now this error, but sooner in the evening, I had different types of errors... for example (I do not remember exactly) : "no such file or directory, error code 2"...
Or another with a different file... At each time, I removed the file and restart again!

I cleant my folder of finished torrents because I had a lot of broken symbolic link.... and now I have this new error...

At the end of my reflexion I have a question : is it possible that a recent commit has modified the behaviour of sickrage in case of an error while reading a file in order to post process it (and in that case, SickRage stop the process!)?
I hope I am clear... I ask this because this problem is new for me. Sickrage has ran OK during several days/weeks before...

**Comment by miigotu** [comment]
please enable debug logging, restart and reproduce the error, and then put the log on gist for us.

**Comment by Grincheux41** [comment]
After an update (20 commits late), I reproduce the problem : 

the error : 
2015-08-06 14:17:02 POSTPROCESSER :: Exception generated in thread POSTPROCESSER: utf8 : Un Homme idéal (2015) [1080p] Bluray x264-PopHD.mkv : error 11 : error 12 : invalid continuation byte

logs : 
2015-08-06 14:17:02 ERROR    POSTPROCESSER :: Exception generated in thread POSTPROCESSER: utf8 : Un Homme idéal (2015) [1080p] Bluray x264-PopHD.mkv : error 11 : error 12 : invalid continuation byte
Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/scheduler.py", line 97, in run
    self.action.run(self.force)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/autoPostProcesser.py", line 50, in run
    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/processTV.py", line 204, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/processTV.py", line 485, in process_media
    if already_postprocessed(processPath, cur_video_file, force, result):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/processTV.py", line 471, in already_postprocessed
    sqlResult = myDB.select(search_sql, [u'%' + videofile])
  File "/usr/local/sickrage/env/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 11: invalid continuation byte

**Comment by miigotu** [comment]
I guess your locale is latin-1?

**Comment by Grincheux41** [comment]
Maybe... but please, do not focus on the error itself. Why does a file in error stop the whole post-processing action?

For several weeks I had several files with this kind of error, and it was not a problem for the others files! For now, I have files which are not processed at all (and these are not in error! these are not concerned by the message above!).

I hope you understand my aim :)

**Comment by miigotu** [comment]
switch to utf-8 and you have no problem. exception kills the thread.

**Comment by Grincheux41** [comment]
ok it's a good solution (I will do so)... but this behavior is new? no?

**Comment by miigotu** [comment]
Nope, has always happened.

**Comment by Grincheux41** [comment]
ok maybe I am a new user... but for "sick beard" it's not the case.

thanks for your help!

**Comment by Grincheux41** [comment]
would it be better to evolve the behaviour? (sorry to insist...)

for example : I use method "symbolic link" in order to seed my files even if it's downloaded...

But, once I have watched the season, I delete it... and of course I just delete the folder with the season... So now, I will have to go to the "torrent folder" in order to delete the symbolic link too? If not, Sickrage won't be able to post process all my downloaded files! :'(

Can you just log a "WARNING" instead of killing the process?

**Comment by WebSpider** [comment]
@Grincheux41 Evolving behaviour is always good. However, we tend to keep feature requests separated from questions/issues to keep it clear for devs how to prioritize their time. If you have specific suggestions, please open a new issue decribing the suggestion (on the symlinking)

Switching to UTF8 is recommended anyways if you're using non-ascii filenames, so we're not going to change this behaviour now.

**Comment by Thoughtscape2014** [comment]
Hi guys, I know this is 'closed' but how do you 'switch to utf8? I seem to have the same problem but have no idea what you mean by this. Cheers, Mick.

**Comment by WebSpider** [comment]
Search this issue tracker for 'chcp', should give you all the info you need!
