### ISSUE TITLE
[APP SUBMITTED]: 'charmap' codec can't encode character u'\u016b' in position 11: character maps to <undefined>

### ISSUE THREAD

**Issue by bb12489** [SiCKRAGETV/sickrage-issues#2429]
### INFO
Python Version: **2.7.7 (default, Jun  1 2014, 14:21:57) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@47b2d5651f0c7ef1d8d20523dee85bc950d17e14
Link to Log: https://gist.github.com/72a174ffd8294f833e96
### ERROR
```
SEARCHQUEUE-BACKLOG-79604 :: [Usenet-Crawler] :: Error while searching Usenet-Crawler, skipping: charmap : Burakku.RagÅ«n : error 11 : error 12 : character maps to <undefined>
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
A special character in the name is the problem.`Burakku.RagÅ«n`
Check your locale or remove any names/scene exceptions with special characters.
