### ISSUE TITLE
Daily Searcher Setting Snatched as Wanted

### ISSUE THREAD

**Issue by LameDufus** [SiCKRAGETV/sickrage-issues#2431]
I have noticed Sickrage grabbing multiple copies of the same show.  It appears that the Daily Searcher is setting a show as wanted after it was marked as snatched.  This also happens when I manually mark it as archived.  See the logs below:
``` 
2015-08-04 21:08:05 INFO     SEARCHQUEUE-DAILY-SEARCH :: Sending NZB to SABnzbd
2015-08-04 21:08:05 INFO     SEARCHQUEUE-DAILY-SEARCH :: Downloading Zoo.S01E06.1080p.HDTV.X264-DIMENSION
2015-08-04 21:07:25 INFO     DAILYSEARCHER :: New episode Zoo - 1x06 - This Is What It Sounds Like airs today, setting to default episode status for this show: Wanted
2015-08-04 21:07:25 INFO     DAILYSEARCHER :: Searching for new released episodes ...
2015-08-04 20:53:24 INFO     SEARCHQUEUE-DAILY-SEARCH :: Sending NZB to SABnzbd
2015-08-04 20:53:24 INFO     SEARCHQUEUE-DAILY-SEARCH :: Downloading Zoo.S01E06.1080p.HDTV.X264-DIMENSION
``` 
At the moment, I set SABnzbd to discard duplicates, but this is more of a band aid rather than fix.  I couldn't find any related issues, but can't imagine I am alone with this issue.  Thanks in advance.

BRANCH: (master) / COMMIT: (47b2d5651f0c7ef1d8d20523dee85bc950d17e14)

This is also happening on the newest commit released today.
 BRANCH: (master) / COMMIT: (9b5c30fc89d633f0366295fd7d2ee69541af8159)

**Comment by LameDufus** [comment]
Checking the logs further, this may be due to "Update shows on snatch" being enabled as the newly snatched episode is refreshed into wanted.  I have disabled it and will report back in a few days the results.

**Comment by miigotu** [comment]
Either way, full debug logs are required to debug this, whether it is from update on snatch or not.

**Comment by LameDufus** [comment]
Turning off "Update shows on snatch" appears to have fixed the multiple snatches.  It should be easy to reproduce by enabling this feature and setting the search to ~15 minutes.  The logs from my server are already flushed so I can't provide them without turning the feature back on.  For now I am happy and I will close this on Monday if no other problems arise.

Thanks for the hard work.

**Comment by fernandog** [comment]
here is the code. It's a simple show update action. Maybe it's in the wrong place and should be call before some other code

https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/search.py#L184-L188

**Comment by miigotu** [comment]
prolly just need to savetodb before update @fernandog

**Comment by fernandog** [comment]
but where does it do right now?

**Comment by LameDufus** [comment]
Since I disabled "Update shows on snatch" there have been no duplicates.  I did try enabling it again to get a a debug log, but the logs of the first snatch were flushed.  It should be easy to reproduce, so I am not going to try again.  You can close this issue if you think there is not a bug and it was something on my side.

**Comment by miigotu** [comment]
@fernandog is there a reason we need the option to "update shows on snatch" at all?

**Comment by WebSpider** [comment]
@miigotu it's from this PR:

SiCKRAGETV/SickRage#1375

Seems @gborri had an issue with foreign shows?

**Comment by miigotu** [comment]
I think I want to remove that. It's useless and puts too much strain on meta indexers.

**Comment by gborri** [comment]
@miigotu the reason Is related to foreign language update on tvdb. When a release is available on torrent, SR start to download and when finished the naming of filename is in English. It happens often that just before the release has found on torrent the naming is updated on tbd. Having this feature the naming of file will be correct.

**Comment by gborri** [comment]
@miigotu i need it and i think someone else too

**Comment by miigotu** [comment]
rescan/rename later also changes the file name, just like for the rest of us. It is not ok to cater to a small subset of users for a feature that merely increases strain on meta indexers more than tenfold.

You need to realize that users small wishes are not the only thing we need to worry about, we also need to worry about being mindful of the stress we put on indexers/providers, etc.
