### ISSUE TITLE
[Feature Request] Port SickRAGE to android

### ISSUE THREAD

**Issue by dmarcelino** [SiCKRAGETV/sickrage-issues#2437]
This has previously been brought up in the forum thread: [Android port/fork](https://sickrage.tv/forums/forum/main-category/feedback-suggestions/21016-android-port-fork).

Given the [dozens of android TV boxes](http://www.geekbuying.com/category/Android-TV-Boxes-1547) available, some with powerful processing power (e.g. the [NVIDIA Shield Android TV](http://www.anandtech.com/show/9289/the-nvidia-shield-android-tv-review)) it would be interesting to port SickRAGE to android. This would enable some people to move SickRAGE from their laptops/desktops into their TV boxes.

This probably doesn't require any changes to the current SickRAGE code but instead a new project that would provide the means and libraries to run SickRAGE on android, like @emileb did in [SickbeardOnAndroid](https://github.com/emileb/SickbeardOnAndroid).

I've already tried [Buildozer](http://kivy.org/docs/guide/packaging-android.html) but without success. Also tried [QPython](http://qpython.com) but Cheetah wouldn't install on my android phone. Now I'm focusing my efforts in [kivy](http://kivy.org) but no luck yet. I'll update this issue if I do make any progress.

It would be great to hear feedback about this. Is it possible someone has already done this? Unfortunately I'm a Python beginner so my progress has been slow.

**Comment by fernandog** [comment]
we won't need cheetah soon (next days/weeks)
external libs only pyopenssl

**Comment by dmarcelino** [comment]
Ah, that will probably make my life easier! I'll try QPython again after that change.

**Comment by emileb** [comment]
If it runs on Python 2.7 what I have done for Sickbeard *should* work. The project is kind of complicated though and a bit of a mess!

**Comment by fernandog** [comment]
you can try this branch: https://github.com/SiCKRAGETV/SickRage/tree/mako

don't need cheetah

**Comment by dmarcelino** [comment]
> If it runs on Python 2.7 what I have done for Sickbeard should work. The project is kind of complicated though and a bit of a mess!

Yeah... I wasn't able to build the sickbeard apk... :blush:

**Comment by dmarcelino** [comment]
> you can try this branch: https://github.com/SiCKRAGETV/SickRage/tree/mako

I'll try that later, thanks!

**Comment by emileb** [comment]
How's your Android knowledge? Really the problem is one of knowing Android
pretty well, I didn't know Python (still don't) when I did Sickbeard on
Android.
I might refactor it into a single Android Studio project sometime, should
be cleaner!

**Comment by dmarcelino** [comment]
Not great I'm afraid, all my android development was done through Titanium Studio (javascript) :)

> I might refactor it into a single Android Studio project sometime, should be cleaner!

That should help tremendously! It would be great if you could do that.

**Comment by neoatomic** [comment]
I like the idea.! Especially as most media-boxes run Android. It would open up Sickrage for a large group of new users. :+1:

**Comment by fernandog** [comment]
@neoatomic omg, tons of new issues lol

**Comment by miigotu** [comment]
@dmarcelino the new mako branch does not require cheetah, and you dont need to install mako. Maybe that helps?

**Comment by dmarcelino** [comment]
So, here's what I've done:

1. Checked out the mako branch
2. Renamed SickBeard.py -> main.py
3. Copied the sickrage entire folder to /sdcard/com.hipipal.qpyplus/projects (QPython's project folder)
3. Tried to run through QPython but it failed due to l.46 -> unresolved import
4. commented out l.45 and l.46
4. Ran it again and got the following error:

```
projects/SickRage/main.py && exit            <
Traceback (most recent call last):
  File "/storage/emulated/0/com.hipipal.qpyplus/projects/SickRage/main.py", line 76, in <module>
    import sickbeard
  File "/storage/emulated/0/com.hipipal.qpyplus/projects/SickRage/sickbeard/__init__.py", line 37, in <module>
    from sickbeard import providers, metadata, config, webserveInit
  File "/storage/emulated/0/com.hipipal.qpyplus/projects/SickRage/sickbeard/providers/__init__.py", line 59, in <module>
    import generic
  File "/storage/emulated/0/com.hipipal.qpyplus/projects/SickRage/sickbeard/providers/generic.py", line 40, in <module>
    from hachoir_parser import createParser
  File "/storage/emulated/0/com.hipipal.qpyplus/projects/SickRage/lib/hachoir_parser/__init__.py", line 2, in <module>
    from hachoir_parser.parser import ValidateError, HachoirParser, Parser
  File "/storage/emulated/0/com.hipipal.qpyplus/projects/SickRage/lib/hachoir_parser/parser.py", line 2, in <module>
    from hachoir_core.field import Parser as GenericParser
  File "/storage/emulated/0/com.hipipal.qpyplus/projects/SickRage/lib/hachoir_core/field/__init__.py", line 2, in <module>
    from hachoir_core.field.field import Field, FieldError, MissingField, joinPath
  File "/storage/emulated/0/com.hipipal.qpyplus/projects/SickRage/lib/hachoir_core/field/field.py", line 6, in <module>
    from hachoir_core.stream import InputFieldStream
  File "/storage/emulated/0/com.hipipal.qpyplus/projects/SickRage/lib/hachoir_core/stream/__init__.py", line 1, in <module>
    from hachoir_core.endian import BIG_ENDIAN, LITTLE_ENDIAN
  File "/storage/emulated/0/com.hipipal.qpyplus/projects/SickRage/lib/hachoir_core/endian.py", line 5, in <module>
    from hachoir_core.i18n import _
  File "/storage/emulated/0/com.hipipal.qpyplus/projects/SickRage/lib/hachoir_core/i18n.py", line 163, in <module>
    (set(u"©®éêè\xE0ç€".encode("ISO-8859-15")), "ISO-8859-15"),
LookupError: unknown encoding: ISO-8859-15
```

**Comment by fernandog** [comment]
strange hachoir  don't use utf-8

**Comment by miigotu** [comment]
@fernandog Its not hachoir, its fail porting.

**Comment by neoatomic** [comment]
@dmarcelino Still trying to port.? Any luck/news.?

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
