### ISSUE TITLE
Manual postprocessing folders with [] in its name

### ISSUE THREAD

**Issue by chromeboy23** [SiCKRAGETV/sickrage-issues#2438]
When you manual postprocess a folder with '[xxx] in its name', and xxx can be anything and the folder contains a .srt file the srt file is nog being postprocessed.

For example

Seriesname.S05E07.HDTV.x264-ASAP[ettv]:

Seriesname.S05E07.HDTV.x264-ASAP.mp4
Seriesname.S05E07.HDTV.x264-ASAP.srt

the .srt file is not postprocessed and moved to the correct destination. The .mp4 file is postprocessed correctly.

**Comment by chromeboy23** [comment]
what is its duplicate issue?

**Comment by miigotu** [comment]
It means you didn't search issues before opening a new one, and it has already been reported before.

**Comment by chromeboy23** [comment]
Sorry for the inconvenience.
I know what it means... i just didn't find it when I searced for it... so I was wondering... what is the original issue called / issue number

**Comment by miigotu** [comment]
#1578

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1571

**Comment by miigotu** [comment]
Sorry lol. On mobile ATM.

**Comment by chromeboy23** [comment]
ok thanks!
