### ISSUE TITLE
[Feature Request] Different label for backlog shows vs new shows in torrent client

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2439]
As title says.

**Comment by WebSpider** [comment]
Offcourse, this is only when client supports labels via API, and this is implemented in the client in SR.
Currently only deluge iirc?

**Comment by OmgImAlexis** [comment]
uTorrent supports it too.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
