### ISSUE TITLE
[Feature Request] Add Paused to Status column in Shows List

### ISSUE THREAD

**Issue by Hansaplast** [SiCKRAGETV/sickrage-issues#2441]
I apologize if this has been requested/asked for before - I could not find any issues related to this.

Is it possible to add "Paused" to the "Status" column in the "Shows list"?

I have paused quite a few shows, that have been completed and the show itself has been ended.
(or is this not the correct way to keep them out of the backlog?)

Keep up the good work :+1:

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
