### ISSUE TITLE
Shows remain status unaired after airdate

### ISSUE THREAD

**Issue by zflash** [SiCKRAGETV/sickrage-issues#2442]
The shows remains at status "unaired", so not skipped or something else. All shows have default setting Wanted. It's affecting all shows and it's happening since a couple of days. a Restart does not make a difference, since the shows remain status unaired. Also changed all shows to default archived and back to wanted. No difference.

Example of shows:
Mr. robot
Hell on Wheels
Mistresses
Under the dome

SR Version:	BRANCH: (master) / COMMIT: (afac218339ac14bf03a8fda76df0318fcb4a5247) 
Windows 7
Python 2.7

Logging shows absolutely nothing regarding changing states of shows even with debug mode on.

Edit: After I do a "Force full update" on a show, the missing episode changes it state to wanted! Before that, it's not even in the backlog since the status unaired is a future state.

Edit2: My config settings regarding this feature:

dailysearch_frequency = 30
backlog_frequency = 720
update_frequency = 12
showupdate_hour = 7
download_propers = 0
randomize_providers = 0
check_propers_interval = 15m
allow_high_priority = 1
dailysearch_startup = 1
backlog_startup = 1

**Comment by miigotu** [comment]
Stop SR and try deleting cache.db, cache/rss cache/indexers, cache/sessions

**Comment by zflash** [comment]
Ok, just did this and 1 show that was still unaired with date 8-8-2015, was set to wanted and snatched. I'll update what happens tomorrow when 2 more shows have passed the airdate.

(just curious: how is the cache clearing seem to fix this?)

**Comment by miigotu** [comment]
dirty shutdowns. always make sure to stop SR properly.

**Comment by zflash** [comment]
Yes, this morning 2 shows that were aired yesterday are being set to status wanted and were getting snatched. Thanks for the info!
