### ISSUE TITLE
Subtitle finder

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2444]
dev branch commit :fe12730f2796b267957cb04ef3e994d53cf49d1c
Out of nowhere SR started downloading numerous languiagves when i only have afrikans ,english and portuguese selected 
it seems to be downloading all languages it can find ,but only on opensubtitles ,maybe an api issue?
log: http://pastebin.com/AvF2WfZN

**Comment by remybien** [comment]
Same issue here, for now I have disabled subtitle downloader. For me all subtitles also came from opensubtitles. Updated sickrage yesterday to the newest version, problem only started occurring 20/30 minutes ago. Might be an issue with the opensubtitles website itself

**Comment by duramato** [comment]
ive just disabled the opensubtitles provider for now as i still want subs

**Comment by remybien** [comment]
That might be a better idea, I'll do the same

**Comment by miigotu** [comment]
@Diaoul any news about a glitch with opensubtitles?

**Comment by Psychoteur** [comment]
Same error, here, on two different installations ;)

**Comment by neoatomic** [comment]
Spoke to another user yesterday. He used 2 sub languages and used the _EN language extensions for the .srt.
So wondering if you are using the same settings. (For me all is running fine, but i'm only using 1 language.)

**Comment by miigotu** [comment]
Must be resolved? closing.

**Comment by duramato** [comment]
Yeah it seems might have been an open subtitles api error

**Comment by miigotu** [comment]
It was.
