### ISSUE TITLE
[APP SUBMITTED]: SHOWQUEUE-ADD :: Show xxxx is on theTVDB but contains no season/episode data.

### ISSUE THREAD

**Issue by Rouzax** [SiCKRAGETV/sickrage-issues#2445]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@99ecfb5edcae4a8e5facff73f39ff1415a5e3e96
Link to Log: https://gist.github.com/c245c6855dceac0b90a1
### ERROR
```
SHOWQUEUE-ADD :: Show Vinyl is on theTVDB but contains no season/episode data.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

Would be nice if it is possible to add the show and when more info is added to thetvdb update that in SickRage.

**Comment by neoatomic** [comment]
When there isn't all the season/episode data on the indexer there is no point in adding the show. If we allow the adding of the show anyway, the users will get lots of errors etc. And SickRage will behave very strange/downloads wrong files. (And after hours trouble shooting an support ticked we find out that the indexer is the problem...)

The problem needs to be solved at the source, and that is the indexer. So the user need to update the data there, so its correct.

**Comment by Rouzax** [comment]
@neoatomic 
It makes sense what you are saying but a lot of the time a new show is announced and there is no further information available at that time. In this case the show Vinyl on HBO.
There is a trailer and it will premier in 2016 but that is all we know for now, so there is no way to update TheTVDB yet.

**Comment by neoatomic** [comment]
You can add temporary info on the indexer if they allow it. Than you could add the show to SR.
But from our side i don't want incomplete shows added, simply to much negatives that it will course...

**Comment by sweatherlyuk** [comment]
I also would like to request this feature.

Sickbeard deals with adding a show where the indexer does not yet know the episodes, it seems to add the show and once the episodes are known it ill update the show with the episodes without any manual intervention and without errors being reported.

If Sickbeard can deal with this scenario I wonder why it's difficult for SickRage to and why "when there isn't all the season/episode data on the indexer there is no point in adding the show. If we allow the adding of the show anyway, the users will get lots of errors etc." as this is not happening in Sickbeard.

It's a shame as SickRage is superior in every other aspect.
