### ISSUE TITLE
Episodes Randomly Being Ignored as Unknown

### ISSUE THREAD

**Issue by Digital-Jedi** [SiCKRAGETV/sickrage-issues#2446]
BRANCH: (master) / COMMIT: (99ecfb5edcae4a8e5facff73f39ff1415a5e3e96)
Win 8.1 / Python 2.7.9

**What you did**
I noticed that some search results are periodically ignored with the *"we don't want an episode that is unknown"* message. I had read this had to do with the quality available not matching what I have set, so I set the quality of this show to Any. However, I noticed the last Rachel Maddow episode from last week hadn't downloaded, so I did a Force Full Update as well as trying to set the episode to Wanted again. 

**What happened** 
Still, even with the quality at Any, the episode is ignored.
>2015-08-10 15:41:26 INFO     SEARCHQUEUE-BACKLOG-181561 :: [ThePirateBay] :: No needed episodes found during backlog search for: [The Rachel Maddow Show]
2015-08-10 15:41:26 INFO     SEARCHQUEUE-BACKLOG-181561 :: [ThePirateBay] :: Performing episode search for The Rachel Maddow Show
2015-08-10 15:41:26 INFO     SEARCHQUEUE-BACKLOG-181561 :: [KickAssTorrents] :: Ignoring result The.Rachel.Maddow.Show.2015.07.08.360p.mp4 because we don't want an episode that is Unknown
2015-08-10 15:41:25 INFO     SEARCHQUEUE-BACKLOG-181561 :: [KickAssTorrents] :: Performing episode search for The Rachel Maddow Show
2015-08-10 15:41:25 INFO     SEARCHQUEUE-BACKLOG-181561 :: Beginning backlog search for: [The Rachel Maddow Show]
2015-08-10 15:41:23 INFO     Thread-41 :: Sending backlog for The Rachel Maddow Show season 2015 because some eps were set to wanted

I don't really have an Error Log, but here's [today's log file](https://gist.github.com/Digital-Jedi/55f7267d36d86f815aaa) since I started up SickRage today. You can see the few times I've tried resetting the episode to wanted. I can't say that this is unique to this show, but I can say that it seems to happen randomly some days with random episodes. Where days later I just have to go get the episode manually.

**Comment by miigotu** [comment]
That episode IS unknown quality, and is air-by-date.

1. Do you have that show set for air-by-date?
2. sickrage will not download episodes of unknown quality, by design, even if "any quality" is selected.

**Comment by Digital-Jedi** [comment]
Yes, it's set to air-by-date. So far this is the first episode it's ignored. How would I go about snatching the torrent regardless of quality, since it's not really an issue for me in this case?

**Comment by miigotu** [comment]
Guess you'll have to download it manually. 360p is not a real quality, it is a youtube half-HD quality. SR will not support those.  They are easily watched on youtube or gotten from youtube with youtube-dl. https://www.youtube.com/channel/UCY9e337l96a9FHj7TQChsXA

**Comment by Digital-Jedi** [comment]
That sorta defeats the purpose of "Any", doesn't it? 

I suppose I can submit this as a feature request, then? Surely news shows and series that are largely disposable should have a way of downloading without worrying about the quality. Would I do a separate bug report?
