### ISSUE TITLE
[APP SUBMITTED]: u'ces'

### ISSUE THREAD

**Issue by ovizii** [SiCKRAGETV/sickrage-issues#2447]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@99ecfb5edcae4a8e5facff73f39ff1415a5e3e96
Link to Log: https://gist.github.com/14dbe0f91bca76296b5b
### ERROR
```
Thread-47 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 1350, in displayShow
    return t.respond()
  File "/var/db/sickrage/cache/cheetah/_usr_pbi_sickrage_amd64_share_sickrage_SickRage_gui_slick_interfaces_default_displayShow_tmpl.py", line 1372, in respond
    for sub_lang in [VFN(VFFSL(SL,"subtitles",True),"fromietf",False)(x) for x in VFN(VFFSL(SL,"epResult",True)["subtitles"],"split",False)(',') if VFFSL(SL,"epResult",True)["subtitles"]]: # generated from line 592, col 13
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/subtitles.py", line 72, in fromietf
    return babelfish.Language.fromopensubtitles(language)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/babelfish/language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/babelfish/converters/opensubtitles.py", line 36, in reverse
    raise LanguageReverseError(opensubtitles)
LanguageReverseError: u'ces'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by ovizii** [comment]
The error happens the moment I go to shows and click on any show. I keep getting redirected to the shows overview and cannot see any show's details. This happened right after I updated to the latest version.

**Comment by fernandog** [comment]
@ovizii 

 if you are using linux:
stop SR,
enter SR directory

run:

must have sqlite3 installed

sqlite3 -cmd ".timeout 5000" sickbeard.db UPDATE tv_episodes SET subtitles = REPLACE(subtitles, 'ces', 'cs') WHERE subtitles LIKE '%ces%";

**Comment by miigotu** [comment]
@fernandog thats incorrect.

```sql
sqlite3 -cmd ".timeout 5000" sickbeard.db UPDATE tv_episodes SET subtitles = REPLACE(subtitles, 'ces', 'cze') WHERE subtitles LIKE '%ces%";
```

**Comment by ovizii** [comment]
I'm on freeBSD, I'll use the second command and let you know. 
actually here it is and I'm really clueless what's the problem here:
    root@sickrage_1:/ # sqlite3 -cmd ".timeout 5000" sickbeard.db UPDATE tv_episodes SET subtitles = REPLACE(subtitles, 'ces', 'cze') WHERE subtitles LIKE '%ces%";
Unmatched '.

**Comment by miigotu** [comment]
@ovizii do it separate:

```bash
cd your/db/location
sqlite3 sickbeard.db
```
in the sqlite3 prompt (the .tables is to verify you are using the right db, if no tables show up you werent in the same dir as sickbeard.db):
```sql
.tables
UPDATE tv_episodes SET subtitles = REPLACE(subtitles, 'ces', 'cze') WHERE subtitles LIKE '%ces%";
```

**Comment by ovizii** [comment]
thanks. I must still be doing something wrong:

`root@sickrage_1:/ # cd /var/db/sickrage/
root@sickrage_1:/var/db/sickrage # sqlite3 sickbeard.db
SQLite version 3.8.10.2 2015-05-20 18:17:19
Enter ".help" for usage hints.
sqlite> .tables
blacklist        imdb_info        scene_numbering  whitelist
db_version       indexer_mapping  tv_episodes      xem_refresh
history          info             tv_shows
sqlite> UPDATE tv_episodes SET subtitles = REPLACE(subtitles, 'ces', 'cze') WHERE subtitles LIKE '%ces%";
   ...>`

and it hangs there until I press CTRL+C

**Comment by miigotu** [comment]
It didn't complete the command and go back to an sqlite3 prompt?

**Comment by ovizii** [comment]
it just hung there until I pressed CTRL+C - is it supposed to take ultra long? I'll give it another try after work.

**Comment by ovizii** [comment]
sorry for not updating this ticket, I tried again, same problem but after the latest SR update it seems to be all working fine now.

**Comment by miigotu** [comment]
as long as it is working now, that's all that matters xD
