### ISSUE TITLE
Error to download torrent files with the character 'Ñ'.

### ISSUE THREAD

**Issue by pixatintes** [SiCKRAGETV/sickrage-issues#2449]
Hi, I use ubuntu linux 14.04, 
SR Version: 	BRANCH: (master) / COMMIT: (47b2d5651f0c7ef1d8d20523dee85bc950d17e14)
SR User:	jordi
SR Locale:	(None, None)
SR Config file:	/home/jordi/.sickbeard/config.ini
SR Database file:	/home/jordi/.sickbeard/sickbeard.db
SR Cache Dir:	/home/jordi/.sickbeard/cache
SR Log Dir:	/home/jordi/.sickbeard/Logs
SR Arguments:	['-q', '--daemon', '--nolaunch', '--pidfile=/var/run/sickbeard/sickbeard.pid', '--datadir=/home/jordi/.sickbeard/']
Python Version:	2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]

I have a issue when SiCKRage try to download a torrent with the character 'Ñ'. I put a filter to try to find spanish tv shows ('spanish, español, castellano'). It works fine cause the result is god, but it return a writting error (Problem setting permissions or writing file to:) downloading the torrent.
I don't have problems with the other files, so it's not a premission or writting problem.

~dont put logs here~

**Comment by miigotu** [comment]
is your locale set to utf-8? have you tried the develop branch?

**Comment by pixatintes** [comment]
Yes, locales is set to uft-8;
LANG=ca_ES.UTF-8
LANGUAGE=ca:en

Here, you can see the debug log: https://gist.github.com/anonymous/5bf0064850a35f4ee9e8

**Comment by pixatintes** [comment]
I have just tested again and now it works fine. I tried two different shows and both ok.
Now sickrage recognize SR locale correctly, before was SR Locale: (None, None)

SR Version: 	BRANCH: (master) / COMMIT: (5770d33ef96e619af764b452ea35ad33e5755add)
SR User:	jordi
SR Locale:	('ca_ES', 'UTF-8')
SR Config file:	/home/jordi/.sickbeard/config.ini
SR Database file:	/home/jordi/.sickbeard/sickbeard.db
SR Cache Dir:	/home/jordi/.sickbeard/cache
SR Log Dir:	/home/jordi/.sickbeard/Logs
SR Arguments:	['-q', '--daemon', '--nolaunch', '--pidfile=/var/run/sickbeard/sickbeard.pid', '--datadir=/home/jordi/.sickbeard/']
Python Version:	2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]

https://gist.github.com/pixatintes/7e95ae9f493f345be1f3

Maybe it was only a error for me, I thought that it was a bug.
If I find something more I will post it.

Thanks for all.
