### ISSUE TITLE
Mede8er XML not correct - <CAST>

### ISSUE THREAD

**Issue by Puni123** [SiCKRAGETV/sickrage-issues#2452]
As i am not a programmer i hope i can explain the problem well enough.
I used TVRenamer to generate my XMLs for the Mede8er 600.
Now i´d like to use the XMLs generated by Sickrage.
It appeas to me, that the XMLs generated are not fully correct.

An example:
This is what is being generated by TVRenamer:
![tvrenamer](https://cloud.githubusercontent.com/assets/13752086/9204429/8c349d04-405d-11e5-9ba6-7f3572f4b888.gif)

Sickbeard generates this:
![sickrage](https://cloud.githubusercontent.com/assets/13752086/9204486/e737fc6e-405d-11e5-8d31-bada55f001f4.gif)

Appart from the missing "runtime" and "genre" - which isn´t incorrect, but just missing - one can see, that there is something wrong with the CAST-Tag. It isn´t opened, but just gets closed and the contents is missing.

Would it be possible to fix this or even additionally add the other missing fields into the XML?

**Comment by Puni123** [comment]
As i am not a programmer i hope i can explain the problem well enough.
I used TVRenamer to generate my XMLs for the Mede8er 600.
Now i´d like to use the XMLs generated by Sickrage.
It appeas to me, that the XMLs generated are not fully correct.

An example:
This is what is being generated by TVRenamer:
![tvrenamer](https://cloud.githubusercontent.com/assets/13752086/9204429/8c349d04-405d-11e5-9ba6-7f3572f4b888.gif)

Sickbeard generates this:
![sickrage](https://cloud.githubusercontent.com/assets/13752086/9204486/e737fc6e-405d-11e5-8d31-bada55f001f4.gif)

Appart from the missing "Rating", "runtime" and "genre" - which isn´t incorrect, but just missing - one can see, that there is something wrong with the CAST-Tag. It isn´t opened, but just gets closed and the contents is missing.

Would it be possible to fix this or even additionally add the other missing fields into the XML?

**Comment by miigotu** [comment]
that cast tag is an xml open and close tag in one, hence the />

**Comment by Puni123** [comment]
Thanks for the clarification. Then it seems as if sickrage isn't getting any actors.

**Comment by thezoggy** [comment]
@Puni123 note that SB only spits out fields if theres data set on tvdb... 
https://github.com/midgetspy/Sick-Beard/blob/development/sickbeard/metadata/mede8er.py#L309

this is done to prevent metadata overriding the app itself (parsing file to get runtime or scraping from site later on).

**Comment by Puni123** [comment]
Maybe a stupid question, but how can i activate/use zap2it?

**Comment by Puni123** [comment]
One other thing - when looking into the tvdb, mr. robot has actors.
I took a look where tvrenamer gets its information - it´s also the tvdb.

Nobody else has the problem not getting any cast in their xml?

**Comment by miigotu** [comment]
@Puni123 more like nobody cares, since the client still loads actors from the web and displays them whether they are in the xml or not, and it is more accurate this way.

**Comment by kb0815** [comment]
Hi,
I recently switched from beard to rage and I'd care,.. or would find it nice, if this section of the xml would be filled. 

Since mede8er as such is incapable of loading this infos from the web, or rather it is largly a by hand thing, which includes a fair amount of waiting with mede8er writing the xml (not updating on access), I too would like to have ready to use metadata.
There is no plex or something similar in my network; no additional "intelligent" server or client, only a file server and a mede8er which connects via smb/nfs. Because,... why should there be? It's all there, apart from <cast>.

**Comment by fernandog** [comment]
SB code is similar to SR. So don't know what's wrong

SB
```
                if myShow["_actors"] is not None:
                    for actor in myShow['_actors']:
                        cur_actor_name_text = actor['name']

                        if cur_actor_name_text is not None and cur_actor_name_text.strip():
                            cur_actor = etree.SubElement(cast, "actor")
                            cur_actor.text = cur_actor_name_text.strip()
```


SR:
```
        if getattr(myShow, '_actors', None) is not None:
            for actor in myShow['_actors']:
                cur_actor_name_text = getattr(actor, 'name', None)
                if cur_actor_name_text != None and cur_actor_name_text.strip():
                    cur_actor = etree.SubElement(cast, "actor")
                    cur_actor.text = cur_actor_name_text.strip()
```

**Comment by fernandog** [comment]
@miigotu is this fixed with that PR about NFO?

**Comment by miigotu** [comment]
I dont know. what I fixed was in kodi12+.

However:
`cur_actor_name_text = getattr(actor, 'name', None)` is not the same as `cur_actor_name_text = actor['name']`

The first one checks `actor.name` which does not exist, the second `actor['name']` is correct. Is that code from mede8er.py? i can fix it if so.

**Comment by fernandog** [comment]
@miigotu are you going to PR/fix this one? easy fix?

**Comment by miigotu** [comment]
Easy enough, but its a bunch of lines. I will fix it soon.

**Comment by miigotu** [comment]
This is already fixed...
