### ISSUE TITLE
No CSS via reverse proxy

### ISSUE THREAD

**Issue by 0x24D** [SiCKRAGETV/sickrage-issues#2458]
Branch: Master
Commit hash: 0769c527da9b41180618db6cc23039547a4be3d8
Your operating system and python version: Ubuntu 15.04/Python 2.7.9
What you did: Accessed sickrage through reverse proxy (setup in apache)
What happened: The page loaded but there is no css. Only black text on a white background.
What you expected: The page to load normally (black and blue) like it does when accessing without the reverse proxy.

I had a reverse proxy setup before and it worked fine, but for some reason it does not work now.

**Comment by WebSpider** [comment]
I have this setup working with nginx just fine. Please post debug logs, enable tornado logs, catch a missed CSS request and add them as gist, as well as your apache reverse proxy config.

**Comment by xDanneee** [comment]
Here is the debug log: https://gist.github.com/xDanneee/48361a08b3357b75a84b

My reverse proxy config is here: https://gist.github.com/xDanneee/13514f44a84d669a38c7

**Comment by WebSpider** [comment]
Can you set web_root to /home, restart SR and try again?

-----Original Message-----

**Comment by xDanneee** [comment]
There is still no css.

**Comment by thezoggy** [comment]
you need to set web_root in your config (with sr shutdown)

**Comment by xDanneee** [comment]
Ah, I misunderstood what @WebSpider meant. I have set the web root as /home and when I go to ip:8081 I get the following error:
````
Traceback (most recent call last):
  File "/opt/sickrage/tornado/web.py", line 1323, in _execute
    result = self.prepare()
  File "/opt/sickrage/tornado/web.py", line 2014, in prepare
    raise HTTPError(self._status_code)
HTTPError: HTTP 404: Not Found
````
When I go to ip:8081/home I receive ````The page isn't redirecting properly````

**Comment by WebSpider** [comment]
You should now go to ip:8081/home

**Comment by xDanneee** [comment]
Going to ip:8081/home gives the error ```` The page isn't redirecting properly.```` Going through the reverse proxy works but with no css.

**Comment by WebSpider** [comment]
You do have "Reverse proxy headers" set in Config >General > Interface ?

**Comment by xDanneee** [comment]
I didn't, I do now but it doesn't change anything.

**Comment by thezoggy** [comment]
https://github.com/midgetspy/Sick-Beard/wiki/Reverse-Proxy
