### ISSUE TITLE
qBittorrent 3.2.3 (Windows) not working

### ISSUE THREAD

**Issue by bkvamme** [SiCKRAGETV/sickrage-issues#2459]
Hi, 

Details: 
BRANCH: (master) 
COMMIT: (0769c527da9b41180618db6cc23039547a4be3d8) 
OS: Ubuntu 14.04.1
Python: 2.7.6

What I did: 
Added qBittorrent settings to Search Settings, waited for a torrent to be found in the backlog. 

What happened: 
A torrent was found, and it attempted to add it to qBittorrent, and failed. 

What I expected: 
A torrent was found, and would be added successfully to qBittorrent. 

Details:
I have qBittorrent 3.2.3 installed on one of my Windows machines to server as an autodownloader for SickRage and CouchPotato. SickRage is not able to connect to the qBittorrent WebUI, and I have to use the blackhole to get torrents working. I am assuming that this is due to qBittorrent 3.2.3 for Windows no longer uses the "pop-up" type authentification, but relies on username/password fields on a website instead as shown in the picture. 
![untitled](https://cloud.githubusercontent.com/assets/6065192/9224834/cb7505e6-4105-11e5-9e31-3d9986678b6f.png)

I suspect that this behavior is specific to the Windows version, as I tried to install qBittorrent on my Ubuntu VM, and the WebUI on the Ubuntu qBittorrent it used the "pop-up" type authentification instead. 

If I click on "Manage Torrents" in the Show section, it opens up a page with the qBittorrent WebUI loaded in a frame. I have to enter un/pw in the login window in the frame to gain access, it does not logon automatically.

**Comment by WebSpider** [comment]
Thanks for the report. Do you have debug logs available, so we can see the error that is being thrown?

**Comment by bkvamme** [comment]
Hi,
Did not have debugging enabled, but have now and will try to get the
related issue out from the log!

**Comment by miigotu** [comment]
In SR where you set qbittorrent download location, remove trailing slash on downloads ad location and double check username and password

**Comment by neoatomic** [comment]
Qbittorrent version 3.2 changed the login process, and only pre 3.2 versions where working. https://github.com/SiCKRAGETV/sickrage-issues/issues/1625 
Not sure if it was fixed, but give a version before 3.2 a try and see if that works.

**Comment by WebSpider** [comment]
New authentication method is documented somewhat in https://gist.github.com/pmzqla/7e5733dbecfc50ee4ecd/861099d74a0a979c1ce080593a9590c96217f924#file-web-api-documentation-L325 ... seems basic cookie auth.

**Comment by miigotu** [comment]
@WebSpider I see you added links to the docs. Are you working on this or should I?

**Comment by WebSpider** [comment]
@miigotu havent started on it yet, just did some research

**Comment by miigotu** [comment]
It seems really easy, its just http basic auth. mhttp://docs.python-requests.org/en/latest/user/authentication/

**Comment by WebSpider** [comment]
It used to be basic http auth, the documentation in https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation#authorization says. However that also says in the top header of the page that is has been overhauled in version 3.2.0 and they still need to update the docs.

**Comment by WebSpider** [comment]
This has become session/cookie based now, and all API commands have changed.

Basically, the qbittorrent client needs a proper overhaul.

Since I don't use qbittorrent myself atm, it will be low on my list of things.

**Comment by papampi** [comment]
I have qb 3.2.0 on ubuntu 14.04, it uses the new webui login page 
and SR works flawless with 127.0.0.1 : port 
I remember when it first came out I had problem with the ip of 192.168.x.x
have you disabled authentication for localhost in qb web setting, it may solve the problem.

**Comment by WebSpider** [comment]
That would indeed solve it for the case SR and qWT run on the same box. In all other cases, we still need to switch to cookie usage.

**Comment by RadeoSuicide** [comment]
I use Win 10, latest master sickrage and qBittorent 3.2.4 and it works fine on port 8083
