### ISSUE TITLE
[APP SUBMITTED]: CHECKVERSION :: We can't proceed with the update. Unable to check remote DB version

### ISSUE THREAD

**Issue by DrakeJones** [SiCKRAGETV/sickrage-issues#2460]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: ****
Commit: SiCKRAGETV/SickRage@cc698786d1f440ca7017a36ed60831df78ebb391
No Log available with ERRORS: 
### ERROR
```
CHECKVERSION :: We can't proceed with the update. Unable to check remote DB version
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by WebSpider** [comment]
This error can occur for multiple reasons, possibly having to do with your connectivity to github.

Can you please enable debug, put the log displaying the issue in a gist, and let us know?
