### ISSUE TITLE
[Feature request] Add shorthash to useragent for indexers to detect multiple installs

### ISSUE THREAD

**Issue by thezoggy** [SiCKRAGETV/sickrage-issues#2461]
seeing some users hitting 2x when calling requests...
![sickrage](http://zoggy.net/splunk41-masked.png)

i would assume its because they have older version? multiple instances? 

any chance to adjust user agent to include something that helps figure that out?
something like SR's process id? version? etc

**Comment by WebSpider** [comment]
We could add the branch/version they are running to the User-Agent, unless that breaks things in API .. @miigotu @fernandog ?

**Comment by miigotu** [comment]
Should add pid and branch. Meter tonight I'll look

**Comment by miigotu** [comment]
@thezoggy is this for all or just some IP? Maybe is just after indexer cache clear?

**Comment by thezoggy** [comment]
@miigotu note that i said 'some' users not all. now I can guess at the cause.. but without seeing pid (to know if the requests are coming from same useragent+pid) or version (see if its outdated/legacy) or what.. I can only assume the reason. 195 requests in 15mins while not excessive to the point I would ban, but it was pretty apparent that half of them are unneeded.. as the data isnt going to be different <1sec after the last successful call of the exact same request.

**Comment by miigotu** [comment]
at least if we add pid/branch it will also rule out legacy SR if it is sending the new UA

**Comment by miigotu** [comment]
@thezoggy looking at this again, the UUID at the end of the UA string is initialized every SR start, so this cannot be multiple instances. It is possible some users have a cached session with wrong owner/permissions from starting SR with a different user and the normal user cannot update/delete the session file.

So, adding PID will not distinguish anything.  I'm thinking we need the shorthash of the commit, that should distinguish how old the install is and even make knowing branch irrelevant?
