### ISSUE TITLE
[APP SUBMITTED]: CHECKVERSION :: We can't proceed with the update. Unable to check remote DB version

### ISSUE THREAD

**Issue by DrakeJones** [SiCKRAGETV/sickrage-issues#2462]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: ****
Commit: SiCKRAGETV/SickRage@cc698786d1f440ca7017a36ed60831df78ebb391
Link to Log: https://gist.github.com/9018c56d21be5e03e1d5
### ERROR
```
CHECKVERSION :: We can't proceed with the update. Unable to check remote DB version
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by MaNIaC-Semal** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.1**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@4db41da61c3e4639a19613a3e4f0dfeef9831fc0
Link to Log: https://gist.github.com/e341b2c2c8449dee7a68
### ERROR
```
CHECKVERSION :: We can't proceed with the update. Unable to check remote DB version
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by DrakeJones** [comment]
I had to reinstall the app. The problem is resolved.
