### ISSUE TITLE
[APP SUBMITTED]: [Errno 13] Permission denied: '/volume1/backup/sickrage/sickrage-20150813163925.zip'

### ISSUE THREAD

**Issue by LysanderM** [SiCKRAGETV/sickrage-issues#2464]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 17:38:42) [GCC 4.6.4]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@0285f4dffb7b64cef72e4e3ae43f00c79d510ccf
Link to Log: https://gist.github.com/ca15d2ae5255ae0a90f1
### ERROR
```
Thread-47 :: Zip creation error: [Errno 13] Permission denied: '/volume1/backup/sickrage/sickrage-20150813163925.zip'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by WebSpider** [comment]
Sickrage doesn't have access to the folder /volume1/backup.

**Comment by LysanderM** [comment]
Well, that's obvious.. But this error was actually not occuring before Aug 2nd and the eight other backups since. Could there be some kind of changes or sth?

**Comment by WebSpider** [comment]
So what are the effective permissions on
````
/volume1/backup/sickrage
````

**Comment by neoatomic** [comment]
@LysanderM Check the permissions of the sc-media group.

**Comment by Vodka2014** [comment]
SickRage needs R+W Permissions. Try adding users R+W permissions this should fix this.
