### ISSUE TITLE
[Bug] Copied Posters. (Super Simple Fix)

### ISSUE THREAD

**Issue by Tobai** [SiCKRAGETV/sickrage-issues#2468]
Local media assets are not copied to the correct cache folder for the gui.  From image_cache.py, poster_path(self, indexer_id) should use self._thumbnails_dir() instead of self._cache_dir()

Posters are located inside subdirectory thumbnails.  Files should go into
/home/x/.sickrage/cache/images/**thumbnails**/ instead of just /home/x/.sickrage/cache/images/

Fanart and Banners would most likely need as well but I had no local media assets to confirm.

Logs:
SHOWQUEUE-REFRESH :: Copying from /media/TV/WWE Monday Night RAW/poster.jpg to /home/x/.sickrage/cache/images/6659.poster.jpg
SHOWQUEUE-REFRESH :: Performing refresh on WWE Monday Night RAW
SHOWQUEUE-REFRESH :: Copying from /media/TV/WWE Superstars/poster.jpg to /home/x/.sickrage/cache/images/22359.poster.jpg
SHOWQUEUE-REFRESH :: Performing refresh on WWE Superstars
SHOWQUEUE-REFRESH :: Copying from /media/TV/WWE SmackDown!/poster.jpg to /home/x/.sickrage/cache/images/6655.poster.jpg
SHOWQUEUE-REFRESH :: Performing refresh on WWE SmackDown!

Using TVRage (as no sports on TheTVDB).

Manually moving id.posters.jpg into thumbnails directory fixes broken images on show list.  No rescanning required.

SR Version:	BRANCH: (master) / COMMIT: (89efb07b1e482a6c8b21b0ac4e18e069d25c856e) 
Thanks.

**Comment by miigotu** [comment]
Since when are there broken images in the show list? lol

**Comment by Tobai** [comment]
If you read.... maybe if you are using TVRage as they don't have posters available that sickrage can pull from.  Since TheTVDB doesn't do sports (like WWE) using tvrage for sports would make perfect sense, right?

Instead of trying to figure out how to utilize TVRage indexer while still pulling TheTVDB posters in Sickrage, may as well just let the program pull that information from the local media assets folder.jpg if it exists.  No point in duplicating work if another media player has them available (like Kodi, EMM)

**Comment by miigotu** [comment]
I'll have to look into it further, as I've never seen an image not work already, and there must be a reason for the 2 different folders. The images in thumbnails are different sizes than the images folder.

**Comment by Tobai** [comment]
Ah, thanks.

Is it possibly something else (another function) that's supposed to take that image.jpg and create that thumbnail.jpg?  For whatever reason, this was a new install (used only for TVRage's sports) and after adding several WWE weekly titles in, no posters were showing up on SR's show list.  All boxes showed the generic Sickrage default image when no art is found.  It's not a broken image, just when something is missing.

That's when I looked through the logs and noticed that it actually did copy the poster.jpg files from my media library to the ~/sickrage/cache/images directory.  But the gui is pulling the images from ~/sickrage/cache/images/thumbnails directory.  I tried the normal steps, restarted, rescanned, force rescanned and such without any changes.  So I just moved those jpgs into the subdirectory, reloaded the show list and everything showed up as expected.

Hopefully nothing else was broke doing that.  Just as a note, if I do add the series using TheTVDB indexer, posters DO show up, as expected as TheTVDB does have info/posters on them but just not updated show information.  And without the current episode information, sickrage would be useless in trying to search for current shows.

**Comment by miigotu** [comment]
Not sure, haven't visited that part of code lately, but we also should be grabbing missing images from tvdb. We already have the ids cross mapped.

**Comment by WebSpider** [comment]
Do you have an example show, so I can dive into it?

-----Original Message-----

**Comment by miigotu** [comment]
WWE Monday Night RAW from tvrage

**Comment by Tobai** [comment]
Here, I did a completely new 100% clean install just to test and to be sure it wasn't a setting or some conflict.  Installed Ubuntu Server 14.04.3 in a test VM.  All done as root, but it's a test VM.

Just for reference:

 # apt-get update
 # apt-get upgrade
 # apt-get install git python-cheetah
 # git clone https://github.com/SiCKRAGETV/SickRage .sickrage
 # cd .sickrage
 # python ./SickBeard.py

http://vm-ip:8081/
Added WWE Monday Night Raw using TVRage
INFO     SHOWQUEUE-ADD :: Starting to add show /root/WWE Monday Night RAW

No poster image when browsing Show list or displayShow.  Expected as no posters exists on TVRage.com.

Put a sample poster.jpg inside show root's directory (as Kodi/EMM and some other media managers do):
 # curl -o "/root/WWE Monday Night RAW/poster.jpg" "http://thetvdb.com/banners/posters/76779-3.jpg"

Rescan Show.
SHOWQUEUE-REFRESH :: Copying from /root/WWE Monday Night RAW/poster.jpg to /root/.sickrage/cache/images/6659.poster.jpg
SHOWQUEUE-REFRESH :: Thumbnails cache dir didn't exist, creating it at /root/.sickrage/cache/images/thumbnails
SHOWQUEUE-REFRESH :: Image cache dir didn't exist, creating it at /root/.sickrage/cache/images
SHOWQUEUE-REFRESH :: Performing refresh on WWE Monday Night RAW

Still no poster inside ./cache/images/thumbnails but poster exists inside ./cache/images directory.

 # mv ~/.sickrage/cache/images/6659.poster.jpg ~/.sickrage/cache/images/thumbnails/

Refresh page and poster shows now.  I hope this helps.

BRANCH: (master) / COMMIT: (89efb07b1e482a6c8b21b0ac4e18e069d25c856e)

**Comment by Tobai** [comment]
I should have added this as well.

If you originally added the show via TheTVDB, the posters *WOULD* have been downloaded correctly to images/thumbnails.  So if you removed that show and readded it again using TVRage (instead of TheTVDB), the posters you've seen were probably from first cache matches.

I tried adding WWE Friday Night Smackdown via TheTVDB First to the same VM above.  It successfully grabbed the posters and images.  Removed the show and added it via RageTV afterwards but it kept the thumbnails it originally pulled down.

It does say:
INFO     Thread-33 :: Attempt to delete cache file /root/.sickrage/cache/images/75640.fanart.jpg
INFO     Thread-33 :: Attempt to delete cache file /root/.sickrage/cache/images/75640.banner.jpg
INFO     Thread-33 :: Attempt to delete cache file /root/.sickrage/cache/images/75640.poster.jpg

But the images were never actually deleted and were still available in the thumbnails directory even with the show now removed.  So adding the show a 2nd time using TVRage, makes it look like posters are working with TVRage when it was actually the original TheTVDB's posters you are looking at and not TVRage's or your Local Media Assets.

**Comment by Thraxis** [comment]
@Tobai @miigotu  

This is not a bug, this is working as designed.   SR does not generate thumbnail images, it pulls them from the indexer if they are available.  Yes if a Poster, Banner of Fanart is available in the show folder it will copy it to the cache.  But there are no existing thumbnails for it to pull into the thumbnail cache and pulling a Poster / Banner / Fanart image into the thumbnail cache folder is a waste of space and a waste of bandwidth when viewing the pages as instead of small quick to load thumbnails your downloading fullsize posters and the browser is scaling them down to display.

**Comment by miigotu** [comment]
@Thraxis so what uses the images in cache/images ? these are already existing locally in the show dir and copied to cache/images, so why cant we scale these and put them in the cache/images/thumbnails to avoid a request to the indexer altogether?

**Comment by Thraxis** [comment]
the cache/images are used in displayShow page for one thing as for scaling and putting images into the cache/images/thumbnails folder?  Nothing at all stops you from doing it.  For whatever reason SR currently grabs the thumbnails from the indexer... if they are available.

**Comment by Tobai** [comment]
@Thraxis Just for clarification, if no images exists online (when using TVRage), SR will grab the local asset folder.jpg to the images directory but it won't use it (as it's not in the expected thumbnails directory)?

Strange.  It's already, 'wasting space' since SR would have copied it from your local asset directory.  As for wasted bandwidth, it is true that it's larger but if you are inside your own network or localhost, I wouldn't think that would be a big deal.  And even if you are remotely accessing it, it's pulled once and it's cached in your browser.  I would think if a user is pulling down complete TV shows, a single large poster image wouldn't be breaking the bandwidth bank.

Ironicly, if you use TVRage's as an indexer first instead of TheTVDB, Sickrage *WILL* pull down posters that TVRage has.  Mostly the mainstream popular ones.  These posters are put in the correct  thumbnails directory and are not resized at all.  Just a quick scan brings up a default poster sizes like these:

1.2M Breaking Bad
1.2M Dexter
980K DS9
670K Family Guy
430K Firefly
470K GoT
810K House
740K Scrubs
800K Smallville
650K TNG
560K The Big Bang Theory
600K The Walking Dead

Which are all larger then the normal TheTVDB posters and thus defeats the reasoning of having small thumbnails already.  Especially considering when they pull down the posters and banners as well.  Regardless, thanks for taking the time to look into things.  For those curious, if bandwidth is a concern you can always resize your images on the commandline (using imagemagik).  You'll lose image quality tho.
$ convert -resize 50% id.poster.jpg new.id.poster.jpg

FFIW, I compared the images from TheTVDB to the ones available from TVRage and the higher quality ones looks so much cleaner imo.  I guess I'll just keep the larger sizes for my viewing.  Unless you believe it will cause some other issues down the road?

Since it's not considered a bug, I guess this post can be ignored.  Thanks!

**Comment by Vodka2014** [comment]
I have the same issue with some shows of mine. Thanks for this tip it will solve the blank spaces :)
