### ISSUE TITLE
[Feature Request] Torznab Support

### ISSUE THREAD

**Issue by zone117x** [SiCKRAGETV/sickrage-issues#2469]
[Jackett](https://github.com/zone117x/Jackett) is an app that can provide a newznab-like endpoint (called [torznab](https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer)) for a ton of trackers. Its used with Sonarr, CouchPotato, and Mylar. 

Sickrage *almost* supports using a torznab provider. When adding a usenet newznab provider, you can use the Jackett torznab endpoint and Sickrage successful queries it for releases, but Sickrage renames the .torrent file downloads to .nzb files. 

All thats required to get this working is adding a torznab option for torrent providers just like the newznab one.

**Comment by neoatomic** [comment]
@zone117x Nice project you have created/setup. 
I like the idea of adding support for it in SickRage. Lets see what the others think. :)

**Comment by miigotu** [comment]
@zone117x I like this request. Question though, does jackett ever just return a magnet?

**Comment by zone117x** [comment]
@miigotu Yeah a [few of the trackers](https://github.com/zone117x/Jackett/search?utf8=%E2%9C%93&q=src%2FJackett%2FIndexers+in%3Apath+magnet+in%3Afile&type=Code) only support magnet. Is that not yet supported in Sickrage? It should be possible in most torrent clients' APIs since Sonarr supports it.

**Comment by Taloth** [comment]
Hey guys, if we're going forward with this it might be a good idea to get the various developers together (Headphones and CouchPotato, if they're interested) so we can look over the spec.
Originally only Sonarr used it and I had direct contact with those ppl actually using it, so changing the spec was easy.
We should look it over, see if anything else needs to be added to be future-proof.

There are some differences with newznab but I tried to stick as close to the original spec as possible.In particular it allows indexer to specify whether they support rid via an optional attribute in caps.

**Comment by miigotu** [comment]
@zone117x the ones returning a magnet should already work in SR, and it will either save as .torrent or send the magnet to client.

**Comment by vipkid** [comment]
I support this idea

**Comment by bootldrDNB** [comment]
That is a really good idea. :D

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!

**Comment by flightlevel** [comment]
http://feathub.com/SiCKRAGETV/SickRage/+125
