### ISSUE TITLE
sickRage crash when adding a search provider

### ISSUE THREAD

**Issue by mrmann** [SiCKRAGETV/sickrage-issues#2470]
hi,

new "installtaion" , when i'm adding shows (existing) everything works fine,

when i'm adding a seach provide (any search provider, torrent or news) the process quit with no errors in logs...

debug log show nothing..
log file:
https://gist.github.com/mrmann/bc7fe966f115125526f5

i'm on Master branch and updated from the UI and manually but with no success.

running on Drobo5N:
Linux Drobo5N 3.2.27 #1 SMP Wed May 27 10:54:24 PDT 2015 armv7l GNU/Linux

python version 2.7
running the service as root

any ideas?

**Comment by mrmann** [comment]
python -v output:
# python -v
# installing zipimport hook
import zipimport # builtin
# installed zipimport hook
# /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/site.pyc matches /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/site.py
import site # precompiled from /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/site.pyc
# /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/os.pyc matches /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/os.py
import os # precompiled from /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/os.pyc
import errno # builtin
import posix # builtin
# /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/posixpath.pyc matches /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/posixpath.py
import posixpath # precompiled from /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/posixpath.pyc
# /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/stat.pyc matches /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/stat.py
import stat # precompiled from /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/stat.pyc
# /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/genericpath.pyc matches /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/genericpath.py
import genericpath # precompiled from /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/genericpath.pyc
# /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/warnings.pyc matches /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/warnings.py
import warnings # precompiled from /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/warnings.pyc
# /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/linecache.pyc matches /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/linecache.py
import linecache # precompiled from /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/linecache.pyc
# /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/types.pyc matches /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/types.py
import types # precompiled from /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/types.pyc
# /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/UserDict.pyc matches /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/UserDict.py
import UserDict # precompiled from /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/UserDict.pyc
# /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/_abcoll.pyc matches /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/_abcoll.py
import _abcoll # precompiled from /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/_abcoll.pyc
# /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/abc.pyc matches /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/abc.py
import abc # precompiled from /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/abc.pyc
# /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/_weakrefset.pyc matches /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/_weakrefset.py
import _weakrefset # precompiled from /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/_weakrefset.pyc
import _weakref # builtin
# /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/copy_reg.pyc matches /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/copy_reg.py
import copy_reg # precompiled from /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/copy_reg.pyc
# /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/traceback.pyc matches /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/traceback.py
import traceback # precompiled from /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/traceback.pyc
# /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/sysconfig.pyc matches /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/sysconfig.py
import sysconfig # precompiled from /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/sysconfig.pyc
# /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/re.pyc matches /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/re.py
import re # precompiled from /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/re.pyc
# /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/sre_compile.pyc matches /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/sre_compile.py
import sre_compile # precompiled from /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/sre_compile.pyc
import _sre # builtin
# /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/sre_parse.pyc matches /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/sre_parse.py
import sre_parse # precompiled from /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/sre_parse.pyc
# /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/sre_constants.pyc matches /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/sre_constants.py
import sre_constants # precompiled from /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/sre_constants.pyc
# /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/_sysconfigdata.pyc matches /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/_sysconfigdata.py
import _sysconfigdata # precompiled from /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/_sysconfigdata.pyc
# zipimport: found 64 names in /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/site-packages/Markdown-2.3.1-py2.7.egg
# zipimport: found 157 names in /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/site-packages/setuptools-8.0.4-py2.7.egg
# zipimport: found 11 names in /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/site-packages/yenc-0.4.0-py2.7-linux-armv7l.egg
import encodings # directory /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/encodings
# /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/encodings/__init__.pyc matches /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/encodings/__init__.py
import encodings # precompiled from /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/encodings/__init__.pyc
# /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/codecs.pyc matches /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/codecs.py
import codecs # precompiled from /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/codecs.pyc
import _codecs # builtin
# /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/encodings/aliases.pyc matches /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/encodings/aliases.py
import encodings.aliases # precompiled from /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/encodings/aliases.pyc
# /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/encodings/ascii.pyc matches /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/encodings/ascii.py
import encodings.ascii # precompiled from /mnt/DroboFS/Shares/DroboApps/python2/lib/python2.7/encodings/ascii.pyc
Python 2.7.5 (default, Aug 29 2013, 19:15:20)
[GCC 4.5.1] on linux2
Type "help", "copyright", "credits" or "license" for more information.

**Comment by WebSpider** [comment]
Curious: Nothing in the logfiles.

Can you check your system logfiles? Maybe your Drobo was low on memory and decided to kill a process to keep itself alive.

**Comment by miigotu** [comment]
@WebSpider @mrmann notice everything is doubled in the log? you have 2 instances of sickrage started, and they were started simultaneously or the second one would have bailed.

**Comment by mrmann** [comment]
@WebSpider, even when i close everything else sickrage will fail to start, if i disable all search providers from the config.ini file, then sickRage works fine (adding shows from existing folders and new shows)
@miigotu , the log was when i started the services twice,one after another.

here is the clean log of a single invoke:
https://gist.github.com/mrmann/4edcf98102bf554ea870
