### ISSUE TITLE
Error when loading Coming Episodes

### ISSUE THREAD

**Issue by Molleke** [SiCKRAGETV/sickrage-issues#2471]
In the latest development branche I get the following error when I want to load the Coming Episodes page:

Error !
TypeError: an integer is required
% if cur_ep_airdate == today.date() and not today_header: <div class="comingepheader"> <br /><h2 class="day">${datetime.date.fromordinal(cur_ep_airdate.toordinal).strftime('%A').decode(sickbeard.SYS_ENCODING).capitalize()} <span style="font-size: 14px; vertical-align: top;">[Today]</span></h2> <% today_header = True %> % endif % if run_time: % if cur_ep_enddate < today: <% show_div = 'ep_listing listing-overdue' %>
f:\Program Files (x86)\SickRage-develop\gui/slick/interfaces/default/comingEpisodes.mako, line 355:
<br /><h2 class="day">${datetime.date.fromordinal(cur_ep_airdate.toordinal).strftime('%A').decode(sickbeard.SYS_ENCODING).capitalize()} <span style="font-size: 14px; vertical-align: top;">[Today]</span></h2>
f:\Program Files (x86)\SickRage-develop\lib\mako\runtime.py, line 853:
callable_(context, *args, **kwargs)

**Comment by miigotu** [comment]
os and other info is needed.
