### ISSUE TITLE
Your connection is not private

### ISSUE THREAD

**Issue by wisdomtooth** [SiCKRAGETV/sickrage-issues#2473]
Your connection is not private

Attackers might be trying to steal your information from sickrage.tv (for example, passwords, messages, or credit cards). NET::ERR_CERT_DATE_INVALID
  Automatically report details of possible security incidents to Google. Privacy policy

**Comment by ripper1967** [comment]
is the date and time correct on your computer?

**Comment by miigotu** [comment]
Its an expired SSL cert on the forum.

**Comment by WebSpider** [comment]
Right.

I need to fix that.

-----Original Message-----

**Comment by WebSpider** [comment]
The SSL cert for sickrage.tv has been updated. Feel safe! =)
