### ISSUE TITLE
Show Status Not Updating

### ISSUE THREAD

**Issue by Vodka2014** [SiCKRAGETV/sickrage-issues#2475]
Hi,

So far it is just this show that has a status of Ended, I checked TVDB and it is on Season 8. Why is this not checking the site and changing the status in SickRage.

Randy Jackson Presents: America's Best Dance Crew
Quality: 	SD
Originally Airs: 	Thursday 9:00 PM on MTV (US)
Show Status: 	Ended
Default EP Status: 	Wanted

Thanks

**Comment by WebSpider** [comment]
Have you paused the show?

-----Original Message-----

**Comment by Thraxis** [comment]
@Vodka2015

Open the the show page and do a [ Force Full Update ]

When a show has ended SR will stop checking for updates to the show as there shouldn't be any.

Looking at TheTVDB I see that Season 7 of that show was in 2012, when it was cancelled, and it just started again in July of 2015.   After you do the Full Update the status of the show should no longer be Ended.


@WebSpider  This relates to your FR
https://github.com/SiCKRAGETV/sickrage-issues/issues/2472

As well as one I submitted a while back
https://github.com/SiCKRAGETV/sickrage-issues/issues/1192

**Comment by WebSpider** [comment]
@Thraxis thanks. I'm currently thinking about what a better strategy would be to handle/detect/look for indexer updates. Obviously, ended shows may need an update too..

**Comment by Vodka2014** [comment]
@Thraxis

Thanks will be doing this now. and let you know.

**Comment by Vodka2014** [comment]
Thanks :) that has now solved it.

Quality: 	SD
Originally Airs: 	Thursday 9:00 PM on MTV (US)
Show Status: 	Continuing
Default EP Status: 	Wanted
Scene Name:	Randy Jackson Presents: America's Best Dance Crew

So Should SickRage not do a full update on shows once a week to make sure they are correct or a status update check only. I do not mind doing this manually but Automation is much better :)
