### ISSUE TITLE
View popular shows page error

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2477]
When trying to open the View popular shows page i get the following message ```Fetching of IMDB Data failed. Are you online? ``` and nothing appears on the logs..
And yes i am online and can even ping imdb.com with a response

**Comment by flightlevel** [comment]
Its got some sort of hotlinking problem.
https://github.com/SiCKRAGETV/SickRage/commit/9e4a29f3a4e61f22c4ec81737996b2a4cc39d0ab

**Comment by miigotu** [comment]
Known issue.

**Comment by WebSpider** [comment]
This is indeed a known issue, the submitter of the code is working on it... right @jonathanendersby ? :)

**Comment by jonathanendersby** [comment]
Fix coming in a few hours... Apologies for the delay, was on holiday in the mountains for a week!

**Comment by miigotu** [comment]
https://github.com/SiCKRAGETV/SickRage/commit/28d7f48ff513ae739aebc337ce0005f76f9a4acd

**Comment by miigotu** [comment]
It is a bit slow loading the page. We will work out a way to improve that, but at least it should work!

**Comment by duramato** [comment]
The page now opens and shows the posters,thanks

**Comment by didyouexpectthat** [comment]
So, I loaded up the latest pull from git, but not seeing the View Popular Movies anymore. 
root@nas-6E-3A-08:/apps/sickrage# git show
commit 3fb81bd65d7710e59d6c89945a3be39d2dbfc386
Merge: f78ff1a 28d7f48
Author: Dustyn Gibson <miigotu@gmail.com>
Date:   Tue Aug 25 00:07:56 2015 -0700

    Merge branch 'develop'
![image](https://cloud.githubusercontent.com/assets/1329077/9470878/d06f840c-4b02-11e5-9d3e-6b57274c0f08.png)

**Comment by flightlevel** [comment]
@didyouexpectthat 
Try restarting SR and then go to the Add Shows page and hit CTRL + F5 to refresh.
If that doesn't work, maybe try stop SR, clear the contents of your cache folder (Config > Help & Info for location) and then start SR.

**Comment by didyouexpectthat** [comment]
@flightlevel Thanks for the follow up.
I have restarted SR. I have changed computers to rule out cache. I've also stopped SR, renamed cache folder to something else and let it rebuild, and started SR, and went back to the Add Shows page, and it is still not there.

root@nas-6E-3A-08:/apps/sickrage# du -hsc cache cache.old
244K    cache
1.1G    cache.old
root@nas-6E-3A-08:/apps/sickrage# systemctl status sickrage
sickrage.service - SickRage Daemon
          Loaded: loaded (/lib/systemd/system/sickrage.service; enabled)
          Active: active (running) since Tue, 25 Aug 2015 19:17:56 -0700; 2min 9s ago
         Process: 25120 ExecStart=/usr/bin/python /apps/sickrage/SickBeard.py -q --daemon --nolaunch --datadir=/apps/sickrage (code=exited, status=0/SUCCESS)
          CGroup: name=systemd:/system/sickrage.service
                  └ 25132 /usr/bin/python /apps/sickrage/SickBeard.py -q --daemon --nolaunch --datadir=/apps/sickrage

I am not sure what I'm going to do about it. I'll probably try redoing SickRage and see if that helps.

**Comment by didyouexpectthat** [comment]
I even git cloned the repo again and then replaced all the files from the repo over my existing install and then started SR and I still don't see it. Kind of weird :P

**Comment by miigotu** [comment]
@didyouexpectthat check your config.ini for use_imdbpular

**Comment by didyouexpectthat** [comment]
That was it.
Changed it to 1.
root@nas-6E-3A-08:~# cat /apps/sickrage/config.ini | grep imdb
use_imdb_popular = 1

Thanks.

**Comment by Kumolo** [comment]
@miigotu still not working on my side. I am getting 

"Fetching of IMDB Data failed. Are you online?
Exception:
malformed start tag, at line 112, column 459"

I stopped SR, moved cache folder (keeping "images" though) and restarted SR. Commit 3fb81bd65d7710e59d6c89945a3be39d2dbfc386. Any idea what is wrong with my setup?

**Comment by miigotu** [comment]
@Kumolo what happens if you visit imdb in your browser first?

**Comment by Kumolo** [comment]
@miigotu working fine (http://www.imdb.com/) using Chrome or IE

**Comment by miigotu** [comment]
@Kumolo I mean visit imdb on your browser, and then visit the imdbpopular page in SR in the same browser window.

**Comment by Kumolo** [comment]
@miigotu No success either. Here is what I did:
-In Chrome Tab 1 goto IMDB --> OK. Same Tab go back to SR popular ---> Fail
-In Chrome Tab 1  goto IMDB --> OK. Leave Tab 1 open and open Tab 2 go to SR popular ---> Fail

By the way, also, I logged out of IMDB which didn't change anything.

**Comment by miigotu** [comment]
@Kumolo try deleting cache/sessions, then going to `http://www.imdb.com/search/title?at=0&sort=moviemeter&title_type=tv_series&year=2014,2016`, then opening the imdbpopular page.

**Comment by Kumolo** [comment]
@miigotu still not working. Tried same browser tab and new tab as above. Something must be broken here. 

Also noticed that again (had this for some days now), since last night 03:28 Show Queue is stuck again (observed in server status). Last time I had this it helped deleting the cache, but that doesn't help this time.

**Comment by Kumolo** [comment]
@miigotu This issue still there after rebooting the NAS: Exception Malformed start tag, at line 112, column 456

**Comment by flightlevel** [comment]
@Kumolo What version of python are you running?
Is it an x86 QNAP and which qpkg are you running?

**Comment by Kumolo** [comment]
@flightlevel : Python Version:	2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]

Yes it is x86 NAS TS-451. Qpkg = Clinton Hall V141024. 

Thanks.

**Comment by miigotu** [comment]
@kumolo there is a newer package for qnap x86. QSickrage by qnap_Stephanie. it is the only fully working version ATM.

**Comment by Kumolo** [comment]
@miigotu Thanks mate. Moved to Stephanes qpkg and now popular shows are displayed :-) Anyway, if there is Python incompatibility, I am wondering if this can't  be detected and logged?

**Comment by miigotu** [comment]
@Kumolo if it were that easy I would be doing it. In fact I tried many times and even had code to do just that in SR up until today, which fails horribly. Noone knows for sure what is missing from the other package that causes the failure, so we dont know for sure what to check.

**Comment by Kumolo** [comment]
Understood. Thanks for your hard work @miigotu

**Comment by AubreyKloppers** [comment]
This morning this is happening to me after the upgrade...

**Comment by Kawalskint** [comment]
Fetching of IMDB Data failed. Are you online?
Exception: 'NoneType' object has no attribute 'contents'

BRANCH: (master) / COMMIT: (29105fd42b203393cc2393d683a3d11b74a0c752)
Windows 8.1

**Comment by toxic17** [comment]
Popular Shows

Fetching of IMDB Data failed. Are you online?
Exception:
'NoneType' object has no attribute 'groups'

**Comment by miigotu** [comment]
Can you guys confirm my fix please?

**Comment by AubreyKloppers** [comment]
4.0.64 - Nope, still there...

**Comment by MGaetan89** [comment]
I think the fix is still in `develop`, so you have to change branch to check.

**Comment by miigotu** [comment]
@AubreyKloppers please try v4.0.65

**Comment by Kawalskint** [comment]
4.0.65 (2015-09-21)
BRANCH: (master) / COMMIT: (484634d14db2072b62e12fa3f3d4efe684ffc66e) 
Windows 8.1

Works, but now broken images. See error log message:

Thread-70 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 274, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 681, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 115, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 328, in __init__
    self.callable_ = self.module.render_body
AttributeError: 'module' object has no attribute 'render_body'

**Comment by miigotu** [comment]
Stop SR, Clean your cache/mako folder and cache/sessions folder.

**Comment by AubreyKloppers** [comment]
Thank you!  I can confirm this working 100%!

**Comment by toxic17** [comment]
I updated to last update and all seems to be working now.

BRANCH: (master) / COMMIT: (657ffd7c4e61d32cecde009541cd25476579b254)

**Comment by joelang1699** [comment]
Fetching of IMDB Data failed. Are you online?
Exception:
malformed start tag, at line 112, column 391


SR Version:	BRANCH: (master) / COMMIT: (5d4bec2c6022a9e2d5ec934791cf80a0b2553a6f)
