### ISSUE TITLE
[Feature Request] Add ability to change (quality) downloading order

### ISSUE THREAD

**Issue by ct3z1** [SiCKRAGETV/sickrage-issues#2478]
Please add the ability to download shows in the order of lowest quality first (instead of highest quality first). For example, if show quality is set to custom and includes SD TV, SD DVD and HD TV, it would try to download the SD TV version before the SD DVD or HD TV version. 

Also, please add the ability to snatch the smallest file first. For example, If show quality is set to HD TV and there are two files available, one 700MB and the other 1GB, it would try to download the 700MB file before the 1GB.

**Comment by miigotu** [comment]
@ct3z1 this is already possible, sort of. I have SDTV, SDDVD, HDTV in initial quality list, and SDTV in preferred list.

This will be improved in the future, but there are some very important changes way up on the list from this.

**Comment by WebSpider** [comment]
You can do this already with custom qualities and archive first match.
