### ISSUE TITLE
Need help with develop->master changelog for merge

### ISSUE THREAD

**Issue by miigotu** [SiCKRAGETV/sickrage-issues#2479]
Due to the mass commits during the switch to mako, we have about 300 commits to sift through to make the changelog for the merge to master.

There were mass conflicts and squash was not viable for the mako->develop merge, so the commit log is flooded with mako changes.

Can we start building a list of fixes/changes/lib updates between master/develop so that I can merge to master SOON? We (mostly @WebSpider and myself) are starting on some big changes again and we cannot go too far without first merging.

**Comment by flightlevel** [comment]
Here is my attempt

* Changed: Major change to mako templates from cheetah
* Added: Mako added to library
* Fixed: Rarbg hotfix, switched to http from https
* Updated: Wiki URL in post processing
* Added: Prevent robots from indexing SR pages
* Fixed: Subtitle page wasn't showing selected subtitles
* Updated: Hachoir library updated
* Fixed: Bug when generating meta images
* Updated: Version checker
* Added: View popular shows on IMDB
* Added: Free disk space calculator
* Added: Send tweets via direct message
* Fixed: Backslash that some torrent clients didn't like
* Added: New torrent client deluge daemon
* Removed: Animezb provider
* Added: Missing network logos
* Updated: Pynma to version 1.0
* Fixed: Bug when loading coming episodes
* Updated: Improved nyaa torrent provider
* Updated: Added sounds to pushover notifications
* Fixed: Stop backlog search on show updates
