### ISSUE TITLE
Mako Runtime Error

### ISSUE THREAD

**Issue by mannibis** [SiCKRAGETV/sickrage-issues#2480]
I recently tried to update my master branch (it said it was 340 commits behind) and upon startup it gives me a Mako Runtime Error as such:

Error !

AttributeError: 'module' object has no attribute 'layout'

<% fuzzydate = 'airdate' %> % if sickbeard.FUZZY_DATING: fuzzyMoment({ dtInline : ${('true', 'false')['poster' in sickbeard.layout]}, containerClass : '.${fuzzydate}', dateHasTime : false, dateFormat : '${sickbeard.DATE_PRESET}', timeFormat : '${sickbeard.TIME_PRESET}', trimZero : ${('false', 'true')[bool(sickbeard.TRIM_ZERO)]}
/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/gui/slick/interfaces/default/home.mako, line 309:
dtInline : ${('true', 'false')['poster' in sickbeard.layout]},
/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/runtime.py, line 853:
callable_(context, *args, **kwargs)

This happened with even when changing to the develop branch. Since I cant open the app, I cannot tell you the commit I'm on but this is from the ssh command line:
commit Updating 743e7d3..d460e71

I also run this on a QNAP NAS.

**Comment by Arcanemagus** [comment]
Hitting this with the latest master branch as well, rolling back to v4.0.50 fixed it for me.

**Comment by OmgImAlexis** [comment]
For now turn off fuzzydates, it's getting fixed as we speak. All other pages apart from /home/ should work.

8081/config/general/

**Comment by zflash** [comment]
Same goes for starting the "Manage Torrents" 

2015-08-17 06:47:34 ERROR    Thread-89 :: Failed doing webui callback: Traceback (most recent call last):
AA
AACompileException: 'import *' is not supported, since all identifier names must be explicitly declared.  Please use the form 'from  import , , ...' instead. in file 'c:\sickrage\gui/slick/interfaces/default/manage_torrents.mako' at line: 1 char: 1

**Comment by miigotu** [comment]
Home is fixed in both master and develop if you can update or git pull.

Manage torrents will be fixed in develop in about 2 minutes, master will need to wait until next merge for that fix.
