### ISSUE TITLE
[Feature Request] Add ability to change/add own thumbnails/posters

### ISSUE THREAD

**Issue by S4BRE** [SiCKRAGETV/sickrage-issues#2481]
Provide the ability to change or add our own thumbnails/posters for show.

**Comment by OmgImAlexis** [comment]
Going to add this on, the ability to switch between all of the posters/banners and TheTVDB/TVRage provide instead of just the first one that's returned by their API.

**Comment by neoatomic** [comment]
Was already requested. 

@OmgImAlexis As you plan working on it, i will leave this open for feedback. :)


Related FR's.:

https://github.com/SiCKRAGETV/sickrage-issues/issues/280
https://github.com/SiCKRAGETV/sickrage-issues/issues/304
https://github.com/SiCKRAGETV/sickrage-issues/issues/749
https://github.com/SiCKRAGETV/sickrage-issues/issues/750

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
