### ISSUE TITLE
sickrage.tv needs a new SSL cert

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2482]
![screen shot 2015-08-17 at 4 31 19 pm](https://cloud.githubusercontent.com/assets/6525926/9299683/80e271c0-44fd-11e5-9166-bbd2b302327e.png)

**Comment by WebSpider** [comment]
Duplicate: Sickragetv/sickrage-issues#2473

-----Original Message-----
