### ISSUE TITLE
Updating Error

### ISSUE THREAD

**Issue by Vodka2014** [SiCKRAGETV/sickrage-issues#2483]
Hi,

SR Version: 	BRANCH: (master) / COMMIT: (6758e3e6283948544234cfccaadc4369441cdf07)
SR User:	sickrage
SR Locale:	(None, None)
SR Config file:	/usr/local/sickrage/var/config.ini
SR Database file:	/usr/local/sickrage/var/sickbeard.db
SR Cache Dir:	/usr/local/sickrage/var/cache
SR Log Dir:	/usr/local/sickrage/var/Logs
SR Arguments:	['--daemon', '--pidfile', '/usr/local/sickrage/var/sickrage.pid', '--config', '/usr/local/sickrage/var/config.ini', '--datadir', '/usr/local/sickrage/var/', '--nolaunch']
Python Version:	2.7.10 (default, Jun 3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]

So for some odd reason it should be 332 Commits behind but i update often.

I got these errors on updating:

https://gist.github.com/Vodka2014/cd9c6497ee40869af850

Thanks

**Comment by flightlevel** [comment]
Have you tried running the below?

git remote add upstream https://github.com/SiCKRAGETV/SickRage.git
git fetch upstream
git checkout master
git branch -u upstream/master
git reset --hard upstream/master
git pull

and then restarting

**Comment by Vodka2014** [comment]
This is installed on my Synology NAS.

**Comment by miigotu** [comment]
restart yoour nas.

**Comment by Vodka2014** [comment]
Just so you know i did the last 2 updates and it worked 100% no errors or issues. So i do not know why this 1 out of how many causes this. 

And no i did not reboot my NAS.
