### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character u'\u03c0' in position 66: character maps to <undefined>

### ISSUE THREAD

**Issue by BodoWitcha** [SiCKRAGETV/sickrage-issues#2485]
When opening the show "Persons of Interest" in SickRage under Windows 10 with Chrome as broswr it returned the following error:
Error !

UnicodeEncodeError: 'charmap' codec can't encode character u'\u03c0' in position 66: character maps to <undefined>

% endif <% curSeason = int(epResult["season"]) %> % endif <% epLoc = str(epResult["location"]) %> <tr class="${Overview.overviewStrings[epCats[epStr]]} season-${curSeason} seasonstyle"> <td class="col-checkbox"> % if int(epResult["status"]) != UNAIRED: <input type="checkbox" class="epCheck" id="${str(epResult["season"])+'x'+str(epResult["episode"])}" name="${str(epResult["season"]) +"x"+str(epResult["episode"])}" /> % endif

C:\Python27\lib\encodings\cp1252.py, line 12:
return codecs.charmap_encode(input,errors,encoding_table)

C:\SickRage\gui/slick/interfaces/default/displayShow.mako, line 466:
<% epLoc = str(epResult["location"]) %>
C:\SickRage\lib\mako\runtime.py, line 853:
callable_(context, *args, **kwargs)

The u'\u03c0' is the Unicode Character 'GREEK SMALL LETTER PI' (U+03C0)

The browser used is Chrome with has the url http://localhost:8081/home/displayShow?show=248742

The error is reoccurs each time this show is opened (reproducable)
The error can be reproduced by creating and/or renaming a file with a UCS character (e.g. π as in Person.of.Interest.S02E11.2πR.mkv) and
using a non UCS locale.

When I was browsing the SickRage.db file I found in the tv_episodes table the following row:
"17816"	"17816"	"248742"	"4427770"	"1"	"2πR"	"2"	"11"	"Finch goes under cover to protect a youth who reminds him of himself; Carter goes on a dangerous mission for the FBI."	"734871"	"0"	"0"	"404"	"W:\Series\Person of Interest\Season 02\Person.of.Interest.S02E11.2πR.mkv"	"250225279"	""	""	"0"	"0001-01-01 00:00:00"	"0"	"NULL"	"NULL"	"0"	"NULL"	"0"	""

and in the directory W:\Series\Person of Interest\Season 02 or \\NAS-1\eSATADisk1\Series\Person of Interest\Season 02
Person.of.Interest.S02E11.2πR.mkv

------------------------------------- My Windows 10 installation data ------------

>SR Version:	BRANCH: (master) / COMMIT: (6758e3e6283948544234cfccaadc4369441cdf07) 
>SR User:	Bob
>SR Locale:	('nl_NL', 'cp1252')
>SR Config file:	C:\SickRage\config.ini
>SR Database file:	C:\SickRage\sickbeard.db
>SR Cache Dir:	C:\SickRage\cache
>SR Log Dir:	C:\SickRage\Logs
>SR Arguments:	[]
> Python Version:	2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]

 ---
When I open the web page from QNAP TS-550Pro+, where I have also installed Sickrage, the above mentioned issue did not occur.
http://nas-1:29989/home/displayShow?show=248742
------------------------------------- QNAP NAS TS559Pro+ -------------------------

>SR Version:	BRANCH: (master) / COMMIT: (6758e3e6283948544234cfccaadc4369441cdf07) 
>SR User:	admin
>SR Locale:	('en_US', 'UTF-8')
>SR Config file:	/share/MD0_DATA/.qpkg/QSickRage/SickRage/CONFIG/sickbeard.conf
>SR Database file:	/share/MD0_DATA/.qpkg/QSickRage/SickRage/DATAS/sickbeard.db
>SR Cache Dir:	/share/MD0_DATA/.qpkg/QSickRage/SickRage/DATAS/cache
>SR Log Dir:	/share/MD0_DATA/.qpkg/QSickRage/SickRage/DATAS/Logs
>SR Arguments:	['-d', '-p', '29989', '--datadir', >'/share/MD0_DATA/.qpkg/QSickRage/SickRage/DATAS', '--config', >'/share/MD0_DATA/.qpkg/QSickRage/SickRage/CONFIG/sickbeard.conf', '--nolaunch']
> Python Version:	2.7.10 (default, Jul 8 2015, 08:04:18) [GCC 4.3.6]

---
Reminder: The imortant differences are in the locale ('nl_NL', 'cp1252' <---> 'en_US', 'UTF-8') and Operating System (Windows 10 and QNAP Linux)

I have insufficient knowledge to solve the issue, but I hope that the description gives the clues where the source of the issue lies.
* User setting of the locale ?
* displaying a UCS character to locale equivalent e.g __π__ to __p__
*   ???

**Comment by h3llrais3r** [comment]
Sorry for hijacking, but I have a similar issue with the latest version on master branch.
It's a mako runtime error, apparently related to character encoding.

![image](https://cloud.githubusercontent.com/assets/1945295/9314180/9b78854a-4527-11e5-98d1-d303ce9aed3c.png)

![image](https://cloud.githubusercontent.com/assets/1945295/9314187/a8132882-4527-11e5-9830-b179faf2711e.png)

I have the error when trying to open the show 'Hannibal'. Other shows seems fine.
I know hannibal a some episodes which french characters in it...

**Comment by miigotu** [comment]
cp1252 does not work with unicode/latin-1, you need to chcp 65001. This has nothing to do with mako.

![image](https://cloud.githubusercontent.com/assets/390379/9317922/ab37eb9e-44f3-11e5-93ac-5b37ec1b498f.png)

**Comment by BodoWitcha** [comment]
@miigotu - just telling what not work and only telling that I need xxxxx does not solve for me and any further reader how to resolve the issue.
Further I do not agree with the statement "This has nothing to do with mako".
Either mako should accept cp1252 and fail graceful (e.g replace untranslatable characters into █ ) or give a solution how fix it (confugation, setup, etc). Allowing it to fail as reported is a bug.

**Comment by miigotu** [comment]
No, the previous behaviour where it was allowed was a bug, and still is. we just no longer mask the bug because we want to fix it. The real problem is the repetitive encoding/decoding throughout SR. It will be fixed in the near future and have proper unicode handling, however for the time being you must set the system encoding properly.

**Comment by h3llrais3r** [comment]
And how can we change the locale for SickRage only?

**Comment by miigotu** [comment]
chcp 65001 just before starting SR (in your script or w/e) will ONLY change codepage for that shell.

**Comment by h3llrais3r** [comment]
thanks! I'll try it out this evening!

**Comment by BodoWitcha** [comment]
To test the circumvention for the code page page I have tried the following.
1. Open the windows command prompt
`Microsoft Windows [Version 10.0.10240]`
`(c) 2015 Microsoft Corporation. Alle rechten voorbehouden.`

2. Entered the change code page command
`C:\Users\Bob>chcp 65001`
`Active code page: 65001`

3. Start SickRage and added the redirect debug output to a log file to avoid screen output
`C:\Users\Bob>python c:\SickRage\SickBeard.py 2>SickRageDebug.log`
`Starting up SickRage master from c:\SickRage\config.ini`

4. Opened the Chrome web browser with the SickRage server URL `http://localhost:8081/`

5. Checked the info setting using Settings->Help & Info. Part of result is shown hereafter (with the latest commit from the master branch):

`SR Version:	BRANCH: (master) / COMMIT: (fe0111aa88dc6d65177f339e643ca971405f926f) `
`SR User:	Bob`
`SR Locale:	('nl_NL', 'cp1252')`
`SR Config file:	c:\SickRage\config.ini`
`SR Database file:	c:\SickRage\sickbeard.db`
`SR Cache Dir:	c:\SickRage\cache`
`SR Log Dir:	c:\SickRage\Logs`
`SR Arguments:	[]`
`Python Version:	2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]`

6 .Opened the TV Shows overview in the browser and clicked on the __TV Show Person of Interest__ which resulted in a new error:

 
`Error !`

`UnicodeDecodeError: 'utf8' codec can't decode bytes in position 66-67: invalid continuation byte`

`<td align="center"><img src="${sbRoot}/images/${("nfo-no.gif", "nfo.gif")[epResult["hasnfo"]]}" alt="${("N", "Y")[epResult["hasnfo"]]}" width="23" height="11" /></td> <td align="center"><img src="${sbRoot}/images/${("tbn-no.gif", "tbn.gif")[epResult["hastbn"]]}" alt="${("N", "Y")[epResult["hastbn"]]}" width="23" height="11" /></td> <td align="center"> <% if epLoc and show._location and epLoc.lower().startswith(show._location.lower()): epLoc = epLoc[len(show._location)+1:] if epLoc != '' and epLoc != None: text = '<span title="' + epLoc + '" class="addQTip">' + str(epResult['episode']) + "</span>"`

`C:\Python27\lib\encodings\utf_8.py, line 16:`
`return codecs.utf_8_decode(input, errors, True)`
`c:\SickRage\gui/slick/interfaces/default/displayShow.mako, line 476:`
`<%`
`c:\SickRage\lib\mako\runtime.py, line 853:`
`callable_(context, *args, **kwargs)`

The circumvention suggested with the MASTER branch does result in a different but similar issue

Resetting the branch to the one used yesterday which that commit

`SR Version:	BRANCH: () / COMMIT: (6758e3e6283948544234cfccaadc4369441cdf07)`
`SR User:	Bob`
`SR Locale:	('nl_NL', 'cp1252')`
`SR Config file:	c:\SickRage\config.ini`
`SR Database file:	c:\SickRage\sickbeard.db`
`SR Cache Dir:	c:\SickRage\cache`
`SR Log Dir:	c:\SickRage\Logs`
`SR Arguments:	[]`
`Python Version:	2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]`

resulted in the same, but different, error.

Using the original setting for the code page
`C:\Users\Bob>chcp`
`Active code page: 850`

`C:\Users\Bob>python c:\SickRage\SickBeard.py 2>SickRageDebug.log`
`Starting up SickRage  from c:\SickRage\config.ini`
resulted in the issue as started in this thread for both commits 6758e3e6283948544234cfccaadc4369441cdf07 and  e0111aa88dc6d65177f339e643ca971405f926f.

The suggested circumvention does not work for me.

**Comment by h3llrais3r** [comment]
@miigotu Adding the show without any files also works with cp1252...
I think it's related to the fact that in the database the paths already exists in cp1252. 
So just switching the codepage will not help (confirmed by @BodoWitcha)
Perhaps starting with a clean database and re-adding all the shows could work...
Still need to test this...

**Comment by BodoWitcha** [comment]
@h3llrais3r A good idea.
I used the mass update to __remove__ the show and used the __Add existing show__ to (re)add the show while chcp 65001 (UCS-8) code page was active.
Now the circumvention works!

**Comment by h3llrais3r** [comment]
Indeed it works, but did you have a look at the logging?
For me, there are a lot of errors that the files with those characters cannot be found...

**Comment by miigotu** [comment]
changing to chcp 65001 and doing mass update to force update should also work. Nothing is going to change with this behavior any time soon.

**Comment by BodoWitcha** [comment]
@h3llrais3r  Because I read your comment in issue #2504 I reviewed the log with this as result.
These are the errors after the 2 items were readded:

_De syntaxis van de bestandsnaam, mapnaam of volumenaam is onjuist (Dutch->English: The syntax of the file name, directory name or volume label is incorrect)_

_Het systeem kan het opgegeven bestand niet vinden (Dutch->English: 
The system can not find the file specified)_

__This is the relevant part of the log:__

`2015-08-19 20:57:40 Thread-57 :: Unable to get size for file W:\Series\The Simpsons\Season 12\The.Simpsons.S12E09.HOM?-thumb.jpg Error: error 123 : De syntaxis van de bestandsnaam, mapnaam of volumenaam is onjuist`
        `2015-08-19 20:57:40 Thread-57 :: Unable to get size for file W:\Series\The Simpsons\Season 12\The.Simpsons.S12E09.HOM?.nfo Error: error 123 : De syntaxis van de bestandsnaam, mapnaam of volumenaam is onjuist`
        `2015-08-19 20:57:40 Thread-57 :: Unable to get size for file W:\Series\The Simpsons\Season 12\The.Simpsons.S12E09.HOM?.tbn Error: error 123 : De syntaxis van de bestandsnaam, mapnaam of volumenaam is onjuist`
        `2015-08-19 20:57:40 Thread-57 :: Unable to get size for file W:\Series\The Simpsons\Season 12\The.Simpsons.S12E09.HOM?.ts Error: error 123 : De syntaxis van de bestandsnaam, mapnaam of volumenaam is onjuist`
        `2015-08-19 20:50:42 Thread-53 :: Unable to get size for file W:\Series\The Simpsons\Season 12\The.Simpsons.S12E09.HOM?-thumb.jpg Error: error 123 : De syntaxis van de bestandsnaam, mapnaam of volumenaam is onjuist`
        `2015-08-19 20:50:42 Thread-53 :: Unable to get size for file W:\Series\The Simpsons\Season 12\The.Simpsons.S12E09.HOM?.nfo Error: error 123 : De syntaxis van de bestandsnaam, mapnaam of volumenaam is onjuist`
        `2015-08-19 20:50:42 Thread-53 :: Unable to get size for file W:\Series\The Simpsons\Season 12\The.Simpsons.S12E09.HOM?.ts Error: error 123 : De syntaxis van de bestandsnaam, mapnaam of volumenaam is onjuist`
        `2015-08-19 20:50:14 Thread-48 :: Unable to get size for file W:\Series\The Simpsons\Season 12\The.Simpsons.S12E09.HOM?-thumb.jpg Error: error 123 : De syntaxis van de bestandsnaam, mapnaam of volumenaam is onjuist`
        `2015-08-19 20:50:14 Thread-48 :: Unable to get size for file W:\Series\The Simpsons\Season 12\The.Simpsons.S12E09.HOM?.nfo Error: error 123 : De syntaxis van de bestandsnaam, mapnaam of volumenaam is onjuist`
        `2015-08-19 20:50:14 Thread-48 :: Unable to get size for file W:\Series\The Simpsons\Season 12\The.Simpsons.S12E09.HOM?.ts Error: error 123 : De syntaxis van de bestandsnaam, mapnaam of volumenaam is onjuist`
        `2015-08-19 20:40:32 Thread-36 :: Unable to get size for file W:\Series\Person of Interest\Season 02\Person.of.Interest.S02E11.2pR-thumb.jpg Error: error 2 : Het systeem kan het opgegeven bestand niet vinden`
        `2015-08-19 20:40:32 Thread-36 :: Unable to get size for file W:\Series\Person of Interest\Season 02\Person.of.Interest.S02E11.2pR.mkv Error: error 2 : Het systeem kan het opgegeven bestand niet vinden`
        `2015-08-19 20:40:32 Thread-36 :: Unable to get size for file W:\Series\Person of Interest\Season 02\Person.of.Interest.S02E11.2pR.nfo Error: error 2 : Het systeem kan het opgegeven bestand niet vinden`
        `2015-08-19 20:40:32 Thread-36 :: Unable to get size for file W:\Series\Person of Interest\Season 02\Person.of.Interest.S02E11.2pR.tbn Error: error 2 : Het systeem kan het opgegeven bestand niet vinden`
        `2015-08-19 20:40:06 Thread-58 :: Unable to get size for file W:\Series\Person of Interest\Season 02\Person.of.Interest.S02E11.2pR-thumb.jpg Error: error 2 : Het systeem kan het opgegeven bestand niet vinden`
        `2015-08-19 20:40:06 Thread-58 :: Unable to get size for file W:\Series\Person of Interest\Season 02\Person.of.Interest.S02E11.2pR.mkv Error: error 2 : Het systeem kan het opgegeven bestand niet vinden`
        `2015-08-19 20:40:06 Thread-58 :: Unable to get size for file W:\Series\Person of Interest\Season 02\Person.of.Interest.S02E11.2pR.nfo Error: error 2 : Het systeem kan het opgegeven bestand niet vinden`
        `2015-08-19 20:40:06 Thread-58 :: Unable to get size for file W:\Series\Person of Interest\Season 02\Person.of.Interest.S02E11.2pR.tbn Error: error 2 : Het systeem kan het opgegeven bestand niet vinden`

**Comment by h3llrais3r** [comment]
Those are indeed the errors, so according to me there is still a problem?
