### ISSUE TITLE
In Application Git Update removes start script

### ISSUE THREAD

**Issue by Quiptix** [SiCKRAGETV/sickrage-issues#2490]
BRANCH: (master) / COMMIT: (2c4bfe44c0f9a37533cfdaea3dc28fdb85cf2e4b) 
QNAP (Clinton base package), Python 2.7.9

Since sometime a GIT update in the Sickrage also removes the QNAP specific start script in the HOME of Sickrage. This behavior is new to me. In previous commits of this branch this behavior was as suspected.

Is this by design or an error or avoidable by setting?

**Comment by WebSpider** [comment]
If the script is placed in the sickrage basedir and not in git, performing a clean pull will remove that file.

**Comment by Quiptix** [comment]
@WebSpider , I know GIT, however this behavior was not present until a couple of weeks/days ago. It seems related to the config, because you cannot set git_reset = 0 in the interface anymore.
If this intended, fair enough, but very unconvenient.

**Comment by Quiptix** [comment]
I found the commit. It is forced from webserve.py 
Took me days. Then again, if intended fair enough...

**Comment by neoatomic** [comment]
@Quiptix On a side note, you need this package. http://apps.qnap.community/11-community/17-qsickrage 
(Clinton's package can have SSL problems as it didn't contain the correct python modules.)

**Comment by Quiptix** [comment]
@neoatomic I worked around that by changing to another Python qpkg. (QPython2).
However I can do this, if an upgrade/crossgrade won't give much problems. I have a reasonably large library.

**Comment by miigotu** [comment]
@Quiptix what start script needs put in the base directory of SR? Qnap has proper locations for qnap serivce config files.

**Comment by WebSpider** [comment]
Quiptix save your sickbeard.db,failed.db and config.ini, that should be all the pertinent information ... install the new package, copy the files in, and start SR

**Comment by Quiptix** [comment]
It was a bit more difficult, because the restore function doesn't work as advertised.
But I'm up and running with the new package. Thanks. Will close this!
