### ISSUE TITLE
Mako Runtime Error after latest update

### ISSUE THREAD

**Issue by autronix** [SiCKRAGETV/sickrage-issues#2491]
After performing automatic update from within the SR interface I was prompted with this message when attempting to access the page:

SR had been working fine until I made the update and stopped working immediately after.

![image](https://cloud.githubusercontent.com/assets/2739878/9313515/4fe8f62c-44f1-11e5-972e-a1d704e85f17.png)

**Comment by autronix** [comment]
I attempted downloading the latest master and reloading backup, the error remains.

Reverting to 4.0.51 and reloading backup got it working again.

**Comment by h3llrais3r** [comment]
Sorry for hijacking, but I have a similar issue with the latest version on master branch.
For me it's also a mako runtime error, but apparently related to character encoding.

![image](https://cloud.githubusercontent.com/assets/1945295/9314180/9b78854a-4527-11e5-98d1-d303ce9aed3c.png)

![image](https://cloud.githubusercontent.com/assets/1945295/9314187/a8132882-4527-11e5-9830-b179faf2711e.png)

I can create a new issue if needed.

**Comment by miigotu** [comment]
There is not a single reference in code to any trakt rolling.

**Comment by autronix** [comment]
Here is the video of the issue as it happens: https://youtu.be/dXHMUk18V8M
