### ISSUE TITLE
Backlog search is grabbing the lowest preferred quality available instead of the highest

### ISSUE THREAD

**Issue by atj20** [SiCKRAGETV/sickrage-issues#2493]
Branch: master

Commit hash: 2c4bfe44c0f9a37533cfdaea3dc28fdb85cf2e4b

Your operating system and python version: synology 413j and python 2.7.10

What you did: Trying to backlog a new show, with several different quality options using custom quality.  In this instance, SD DVD all the way up to 1080p bluray was selected as "preferred", with archive on first match NOT selected. 

![2](https://cloud.githubusercontent.com/assets/13839052/9313898/930739ec-451d-11e5-9bd3-699c731f1538.JPG)

What happened:  Sickrage finds several of the preferred qualities while searching, but seems to pick the lowest among them rather than the highest. ie it picks and grabs the SD DVD version rather than the 1080p version that was available. This was working not long ago as I used it to backlog a few shows and it worked great. However I have since tried it again by setting some of these shows to "wanted" and it again grabs the lowest available selection - its almost like the quality list is just upside down.

What you expected: I thought custom quality was supposed to pick the highest available and keep searching until your highest selection was found. In this case, it should've seen the 1080p Bluray and grabbed that. 

Log at the time of searching:  https://gist.github.com/atj20/ec5c07c62f7c5b7b2467#file-log-txt

**Comment by miigotu** [comment]
@atj20 your log and report are invalid without full DEBUG log.

**Comment by atj20** [comment]
@miigotu that link should now have DEBUG log in it - is that enough information? Thanks

**Comment by miigotu** [comment]
```
2015-08-17 23:03:53 DEBUG    SEARCHQUEUE-BACKLOG-269613 :: [FreshOnTV] :: Picked Fargo.S01.BDRip.x264-DEMAND as the best
2015-08-17 23:03:53 DEBUG    SEARCHQUEUE-BACKLOG-269613 :: [FreshOnTV] :: The highest quality of any match is 1080p BluRay
```

```
2015-08-17 23:03:53 DEBUG    SEARCHQUEUE-BACKLOG-269613 :: [FreshOnTV] :: Checking if we should keep searching after we've found Fargo.S01.BDRip.x264-DEMAND
2015-08-17 23:03:53 INFO     SEARCHQUEUE-BACKLOG-269613 :: [FreshOnTV] :: Downloading Fargo.S01.BDRip.x264-DEMAND from FreshOnTV
2015-08-17 23:03:53 INFO     SEARCHQUEUE-BACKLOG-269613 :: [FreshOnTV] :: Downloading a result from FreshOnTV at https://freshon.tv/download.php?id=137703&type=torrent
```

**Comment by atj20** [comment]
Hi @miigotu - Sorry, but I'm probably being a bit stupid here - what am I doing wrong? I've asked it to find bluray 1080p, it found it but chose that DEMAND release which is SD DVD instead?

**Comment by WebSpider** [comment]
It's a BDRip,not SD DVD:

Similar to DVD-Rip, only the source is a Blu-ray Disc. A BD/BRRip in DVD-Rip size often looks better than a same-size DVD rip because encoders have better source material. A common misconception among downloaders is that BDRip and BRRip are the same thing. They differ in that a BDRip comes directly from the Blu-ray source, while a BRRip is encoded from a pre-release, usually from a 1080p BDRip from another group. BDRips are available in DVD-Rip sized releases (commonly 700 MB and 1.4 GB) encoded in Xvid or x264, as well as larger DVD5 or DVD9 (often 4.5 GB or larger, depending on length and quality) sized releases encoded in x264.

**Comment by miigotu** [comment]
Regardless, the release grabbed by SR was 1080p Bluray.

**Comment by atj20** [comment]
I appreciate that, but SR treats BDRips that aren't specified as 1080p the same as SD DVD - the quality section of the Wiki states this. While they are better than standard DVD rips, they are still very much near the bottom of the quality ladder.  In this example, if I remove SD DVD from the list of preferred formats and leave HDTV as the lowest quality in the list, then SR picks HDTV as the best option.  It always picks the lowest quality option in the "preferred" list - it seems to be picking in reverse order for some reason.

**Comment by atj20** [comment]
@miigotu No it wasn't - earlier in the logs you can see it work out the following:

Quality of Fargo.S01.BDRip.x264-DEMAND is SD DVD

Then later it says:

Picked Fargo.S01.BDRip.x264-DEMAND as the best
The highest quality of any match is 1080p BluRay

**Comment by atj20** [comment]
Just to demonstrate this, here is another log i just did.  This time the lowest quality preferred was 720p WEB-DL. It found all the same sources, but this time it picked 720p WEB-DL to grab, even though this is the lowest quality. 

https://gist.github.com/atj20/85b8f5acbada06642f44#file-720p-web-dl-txt

I've tried it with other shows as well - some of which were working a week ago when I backlogged them but now are having the same issue. I'm sure it must be a setting that i've accidentally changed but would appreciate some help.
Thanks

**Comment by miigotu** [comment]
Remove SD-DVD from preferred quality and put it in initial quality.

**Comment by atj20** [comment]
I just removed it completely to try that.  Here's what i set in quality:

Initial: SDTV, HDTV
Replace with: 720p WEB-DL, 1080p WEB-DL, 720p BluRay, 1080p BluRay

It searched all the same releases, but this time it chose 720p WEB-DL and ignored that there was a 1080p Bluray to grab.

**Comment by miigotu** [comment]
@atj20 can you come on irc? I think I might see the issue in code (and its my fault, when I fixed another much bigger issue). I'd like to get you to test some code changes before I risk them in the repo

**Comment by atj20** [comment]
@miigotu Sorry - i'd gone to bed before you wrote that! I'm currently idling on IRC and happy to help.

**Comment by pkoutsias** [comment]
I seem to have the same issue (720p HDTV preferred over 720p BDRip)
Initial: SDTV, SD DVD, 720p HDTV, 1080p HDTV, 720p WEB-DL, 1080p WEB-DL, 720p BluRay, 1080p BluRay
Replace with: 720p HDTV, 720p WEB-DL, 720p BluRay

I can try to produce some debug logs if needed

**Comment by pkoutsias** [comment]
Here is a debug log with the issue, I hope it helps
```
Quality of The.Killing.S04.1080p.BluRay.x264-ROVERS is 1080p BluRay
Quality of The.Killing.S04.720p.BluRay.x264-DEMAND is 720p BluRay
Quality of The.Killing.US.S04.1080p.WEB-DL.DD5.1.H.264-K is 1080p WEB-DL
Quality of The.Killing.US.S04.1080p.WEB-DL.DD5.1.H.264-K is 1080p WEB-DL
Quality of The.Killing.US.S04.720p.WEB-DL.DD5.1.H.264-K is 720p WEB-DL
Quality of The.Killing.US.S04.720p.WEB-DL.DD5.1.H.264-K is 720p WEB-DL
Quality of The.Killing.S04.WEBRip.AAC2.0.H.264-Abjex is SDTV
Picked The.Killing.US.S04.720p.WEB-DL.DD5.1.H.264-K as the best
```
