### ISSUE TITLE
[APP SUBMITTED]: [Errno 16] Device or resource busy: '/media/tv_complete/Dragons - 1x15 - Twinsanity.mp4'

### ISSUE THREAD

**Issue by rrd911** [SiCKRAGETV/sickrage-issues#2496]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-61-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@2c4bfe44c0f9a37533cfdaea3dc28fdb85cf2e4b
Link to Log: https://gist.github.com/05c59f8ee2d3b47f1ed4
### ERROR
```
Thread-17 :: Unable to move file /media/tv_complete/Dragons - 1x15 - Twinsanity.mp4 to /media/littleray/Dragons Riders of Berk/Dragons - 1x15 - Twinsanity.mp4: error 16 : Device or resource busy
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rrd911** [comment]
After the latest update I started seeing the above error in my error log. I wasn't getting that error before the latest update

**Comment by miigotu** [comment]
This has nothing to do with the update. The file is still in use/seeding.

**Comment by rrd911** [comment]
Don't know how you can say it's not due to an issue with the update. I did not have these errors before the latest release and now I get them on every file. Now the file in question is supposed to replace an existing file when I use the manual post process method and select 
Mark Dir/Files as priority download  (Check it to replace the file even if it exists at higher quality)

AA    result = func(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
AA  File "/home/raydias/sickrage/sickbeard/encodingKludge.py", line 70, in ek
AA    ek.ek(os.unlink, srcFile)
AA  File "/home/raydias/sickrage/sickbeard/helpers.py", line 435, in moveFile
AA    helpers.moveFile(cur_file_path, new_file_path)
AA  File "/home/raydias/sickrage/sickbeard/postProcessor.py", line 342, in _int_move
AATraceback (most recent call last):

**Comment by miigotu** [comment]
Its trying to delete the source file, in your download dir, and the file is still in use.

**Comment by rrd911** [comment]
nothing would be accessing that file other than the post processing from sickrage. And like I stated before I updated to the Commit: SiCKRAGETV/SickRage@2c4bfe4 I did not have this issue. A little frustrating.

**Comment by miigotu** [comment]
The torrent/nzb client would be who still has the file open.

**Comment by rrd911** [comment]
So after researching and looking at other issues posted for sickrage I did the following which so far has resolved the issue.

Found the following
https://github.com/SiCKRAGETV/sickrage-issues/issues/2534


Stoped SR, open sickbeard/common.py and comment lines 262-264 like this:

#        quality = Quality.qualityFromFileMeta(name)
#        if quality != Quality.UNKNOWN:
#            return quality
Start SR and try that again.

Files that would fail are now being post processed successfully.
