### ISSUE TITLE
[Feature Request] Print 'Shows list'

### ISSUE THREAD

**Issue by vere-tech** [SiCKRAGETV/sickrage-issues#2498]
Hi all, great work with this project!

I was asked the other day what shows I had in my library, in detail, and I thought I'd print a copy of the 'Shows' screen however it doesn't layout the page very well for printing, some information even missing.
It would be nice to see a 'Print View' button where it would open a new window where the layout had printing in mind or an export to PDF?

Keep up the great work!
Ed

**Comment by MGaetan89** [comment]
The print view can be optimized. What do you think about the "Simple" layout on the list of shows as a reference, but only with the table of shows (so no top navigation bar)?

**Comment by vere-tech** [comment]
The "Simple" view would be a good reference, with the inclusion of the show size's in GB, if that could be optimized to be able to print without the table getting mixed up, would be awesome! Friends could read the Print out and see how much space their USB would need to be to get a copy.

**Comment by MGaetan89** [comment]
Good idea to include the show's size. I have to check if that info is available.
I will try to come up with something in the coming days.

**Comment by WebSpider** [comment]
Linking this to #34

**Comment by vere-tech** [comment]
Awesome MG, i didnt realise a similar topic was there, thanks for linking it webspider

**Comment by miigotu** [comment]
@MGaetan89 should just be a css fix no? `@media print{`

**Comment by MGaetan89** [comment]
@miigotu yes, CSS should be enough I think

**Comment by MGaetan89** [comment]
@miigotu I think I'll do more than just adding CSS. IMO, only the "Simple" layout is good for printing.
So, as @vere-tech suggested, I'll add a "Print" button, next to "Add show" and "Post-Processing", that opens a new tab with the simple layout and print CSS.

**Comment by MGaetan89** [comment]
I'm almost done. For the moment I display all data in the table:
- Previous episode
- Next episode
- Show
- Network
- Quality
- Downloads
- Active
- Status

I don't know if "Previous episode" is necessary. If I don't include it, I could use that space to display the show total size (as soon as I find how to get that information).

What do you think?

Currently, it looks like that:
<img width="467" alt="Print show list" src="https://cloud.githubusercontent.com/assets/1009664/9429427/c52e50de-49cf-11e5-9070-ad7c081be9ab.png">

**Comment by miigotu** [comment]
@MGaetan89 Im not sure Im a fan of that PR since it adds another page for us to maintain. Good css should be enough to make the main page printable, regardless of the layout.

Also that way normal print dialog or system print dialog will work fine and we dont need a "print" button in the UI.

**Comment by miigotu** [comment]
http://benfrain.com/create-print-styles-using-css3-media-queries/

**Comment by MGaetan89** [comment]
Ok, I'll try to make it work with CSS only

**Comment by MGaetan89** [comment]
@vere-tech The PR is almost done. However, I did not include the "Total show size" information as you suggested. For the moment, I only improve the current layouts to be printable.
I will try to send an other PR to include an option to show/hide the "Total show size", so it can be included in the print view as well (from the existing "Select Column" menu).

**Comment by WebSpider** [comment]
Please make sure the show size doesn't do recursive/multiple file system calls. This will slow the view down enormously, especially on networked file systems.

-----Original Message-----

**Comment by MGaetan89** [comment]
I didn't look yet how to get that information. But if it is too complicated, I won't include it.

**Comment by vere-tech** [comment]
@MGaetan89 thanks heaps for doing this, i will make good use of it and im sure others will too. @WebSpider and @MGaetan89, each shows size in "GB" is displayed when viewing a specific show. Is that information stored somewhere that it can be referenced to display on the print screen, or is it gathered every time a show is viewed? if its the later i can see your point @WebSpider

**Comment by MGaetan89** [comment]
It's computed every time it is required.

**Comment by vere-tech** [comment]
stuff that, hah. Dont worry about it bro. i agree with @WebSpider
