### ISSUE TITLE
Mako Runtime Error - 'module' object has no attribute

### ISSUE THREAD

**Issue by autronix** [SiCKRAGETV/sickrage-issues#2499]
Previous issue was closed while bug persists: https://github.com/SiCKRAGETV/sickrage-issues/issues/2491

Nothing done out of the ordinary, no custom code running, just plain update process by following the automated results in the error - stock installation and reloading the backup does the same.

Here is the video of the issue as it happens when I update: https://youtu.be/dXHMUk18V8M
Here are the log entries associated with the update: https://gist.github.com/autronix/4c419111f56b467b97d2

After performing automatic update from within the SR interface I was prompted with this message when attempting to access the page:

SR had been working fine until I made the update and stopped working immediately after.

Here is the error text:
``
Error ! AttributeError: 'module' object has no attribute 'TRAKT_USE_ROLLING_DOWNLOAD' </td> <td align="center"> <img src="${sbRoot}/images/${('no16.png", alt="No"', 'yes16.png", alt="Yes"')[int(curShow.paused) == 0 and curShow.status == 'Continuing']} width="16" height="16" /> </td> <td align="center"> <% display_status = curShow.status %> % if None is not display_status: C:\Program Files (ext)\SickRage-master\gui/slick/interfaces/default/home.mako, line 818: <img src="${sbRoot}/images/${('no16.png", alt="No"', 'yes16.png", alt="Yes"')[int(curShow.paused) == 0 and curShow.status == 'Continuing']} width="16" height="16" /> C:\Program Files (ext)\SickRage-master\lib\mako\runtime.py, line 853: callable_(context, *args, **kwargs)
``

I attempted downloading the latest master and reloading backup, the error remains.

Reverting to 4.0.51 and reloading backup got it working again.

**Comment by miigotu** [comment]
Stop opening duplicates. Delete cache/mako
