### ISSUE TITLE
SickRage can't see my Mapped Network Drives

### ISSUE THREAD

**Issue by mbxplex** [SiCKRAGETV/sickrage-issues#2501]
I recently reformatted my laptop and reinstalled SickRage.

After following the guide again, I try to point SR at the Y & Z drives, like before but it doesn't see them. What am I doing wrong. 

SR Version:	BRANCH: (master) / COMMIT: (2c4bfe44c0f9a37533cfdaea3dc28fdb85cf2e4b) 
SR User:	DESKTOP-UCG5H3A$
SR Locale:	('en_US', 'cp1252')
SR Config file:	C:\SickRage\config.ini
SR Database file:	C:\SickRage\sickbeard.db
SR Cache Dir:	C:\SickRage\cache
SR Log Dir:	C:\SickRage\Logs
SR Arguments:	[]
Python Version:	2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
OS: Windows 10 Home

**Comment by mbxplex** [comment]
![capture](https://cloud.githubusercontent.com/assets/12984486/9320566/a33fbc7e-4529-11e5-9655-39302c22f29d.PNG)

**Comment by miigotu** [comment]
check "replace all child object permissions..."

Opening a SR issue for problems with your setup/permissions doesnt make sense. It is not an issue with SR.

**Comment by mbxplex** [comment]
@miigotu At the time I didn't realize that, since SR was the only thing not seeing the hard drives ... and still is unfortunately :( 

and that didn't work either. This problem I just can't figure out and no one can seem to either.

**Comment by mbxplex** [comment]
@miigotu someone suggested this in the IRC chat ... would this work?

srforums|67294I wonder if you could just enter the UNC (\\192.168.0.1\TVShows etc) path in the config file? Maybe check with a dev first before trying

**Comment by snoopyowns** [comment]
I had the same issue except it was during a Windows 10 upgrade. I run Sickrage under administrator, so what worked for me was to run a CMD prompt in administrator, then map the drive using a net use. Restarted SickRage and it worked. Good luck.
