### ISSUE TITLE
Add build tool intergration

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2502]

**Comment by WebSpider** [comment]
Sounds like a sane optimization. Where can I read up on the build tools? I'm not much into web optimizations but would love to pick up :)

**Comment by OmgImAlexis** [comment]
Coming from nodejs, [this](http://gruntjs.com/) is what I'm use to. I'm sure there's something similar for python.

**Comment by OmgImAlexis** [comment]
@WebSpider this looks like a good place to start.

http://swiftbend.com/blog/?page_id=79

**Comment by WebSpider** [comment]
That should provide me enough google keywords, thanks :)

-----Original Message-----

**Comment by OmgImAlexis** [comment]
I think even if we just get the library file minified it'll help. That way they can be served with a cache header so only things that actually get updated can be reserved. I don't see any reason to reserve jQuery and all the other libraries when they're never going to change unless we update them and in that case we could use a cache breaker(google that) and set it to be the same as the commit instead of the pid. That way when SR is updated it'll refresh those files.

**Comment by MGaetan89** [comment]
An other optimization would be to used a CSS sprite to contain all SickRage icons, instead of having one file for each icons.
By quickly looking at the `images/` I also noticed that some icons look quite similar to each other. So this may be an other optimization step.

**Comment by MGaetan89** [comment]
I'm working on a PR (SiCKRAGETV/SickRage#2336) to remove duplicated CSS rules. That should this PR a bit.

**Comment by MGaetan89** [comment]
Quick update about this:
- I just submitted a new PR to improve CSS (https://github.com/SiCKRAGETV/SickRage/pull/2372)
- I will soon submit an other one to update the dependencies (Bootstrap at least) and use the minified version of jQuery
- More can probably be done (merging and minifying all CSS files). But we already made progress right now :)

I think some improvements can be made with the images. I will have a look once I'm done with CSS.

**Comment by OmgImAlexis** [comment]
@MGaetan89 One thing I wanted to test was images vs using data URIs or possibly using python to convert the images to data URIs on the fly.

**Comment by MGaetan89** [comment]
That sounds like a good idea.
Last time I checked, some images look similar, but were in different files. So I wanted to see if it is possible to use the same image everywhere, to be more consistent. It should help you too to use data URIs ;)

**Comment by OmgImAlexis** [comment]
Looks like this may help along with bower to get all of our required libraries added and minified into a single file.

https://github.com/cyberdelia/django-pipeline
