### ISSUE TITLE
[Feature Request] Send cache headers on all images

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2503]
At the moment from what I can tell there's no cache control headers sent, if they were it could drastically reduce the amount of files being downloaded per page. This is extremely helpful for people using this from a remote location.

**Comment by WebSpider** [comment]
It looks like cache-control is built into Tornado these days. This may be a very quick fix.

**Comment by WebSpider** [comment]
Upon closer look: Not so quick, we have to adjust all mako files which have images in them.

**Comment by WebSpider** [comment]
Preliminary patch in WebSpider/SickRage dev-setup_cachecontrol branch

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
