### ISSUE TITLE
Could not refresh subtitles

### ISSUE THREAD

**Issue by mcm84** [SiCKRAGETV/sickrage-issues#2505]
Hi,

The subtitles search has stopped awhile ago without any evident reason (from my point of view). 

System info : 
- BRANCH : (master) 
- COMMIT hash: (6758e3e6283948544234cfccaadc4369441cdf07) 
- Version : 4.0.51 (2015-08-16)
- Python version : 2.7.9 (default, Mar 1 2015, 13:48:22) [GCC 4.9.2]
- OS : OSMC

I haven't found any errors like this in the issues tracking. I have tons of error like this one :
```
2015-08-18 05:58:46 ERROR    SHOWQUEUE-REFRESH :: 264954: Could not refresh subtitles
AA
AAUnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 10: ordinal not in range(128)
AA    for p in os.listdir(dirpath):
AA  File "/opt/sickrage/lib/subliminal/video.py", line 180, in scan_subtitle_languages
AA    languages = subliminal.video.scan_subtitle_languages(video_path)
AA  File "/opt/sickrage/sickbeard/subtitles.py", line 98, in subtitlesLanguages
AA    self.subtitles = subtitles.subtitlesLanguages(self.location)
AA  File "/opt/sickrage/sickbeard/tv.py", line 1428, in refreshSubtitles
AA    curEpisode.refreshSubtitles()
AA  File "/opt/sickrage/sickbeard/tv.py", line 460, in loadEpisodesFromDir
```

**Comment by WebSpider** [comment]
It looks like you have an invalid character in a directory name ... possibly a recently added show? 
DEBUG logs may tell you which show it is.

**Comment by mcm84** [comment]
With the debug enabled, I can see that I have the message for all my shows :(
I am french an I have an accentuated char in the folder that contains my shows (/mnt/NAS/Séries/).
I might be the problem her ? Al I can add is that when I deployed Sickrage I didn't have this problem..

Thanx :)

**Comment by neoatomic** [comment]
@mcm84 The special characters are the problem. (probably the `Séries` folder) 
Check/Change your locale to utf-8.

**Comment by mcm84** [comment]
Thanks guys! I have changed the folder's name and everything is working again :)
