### ISSUE TITLE
Subtitles are downloaded for one show only 

### ISSUE THREAD

**Issue by anonvoy** [SiCKRAGETV/sickrage-issues#2506]
I installed Sickrage several weeks ago in early June, got everything to run, and subtitle download worked perfectly. But for several weeks now, subtitles are not downloaded anymore, except for one show. My subtitle settings are set to search subtitles, subtitle language English, and four of the subtitle plugins are activated (I unchecked Opensubtitles several weeks ago, too many bad subtitles from that source). I don't use a separate subtitle directory or any scripts, frequency is set to 1, and of the remaining options, only "Log downloaded Subtitle on History page?" is checked. Sickrage version is "BRANCH: (master) / COMMIT: (fe0111aa88dc6d65177f339e643ca971405f926f)", Python 2.7.10 (2.7.10 (default, May 24 2015, 14:46:10) [GCC]) on Linux (64-bit). **All** shows have subtitles checked.

The show which **is** subtitled is "Deutschland 83", a German-language show broadcast in that language in the US. For that show, English subtitles are downloaded; instantly when I did "Download missed subtitles for selected episodes", and with at least 2 of the 4 subtitle search providers (addic7ed and thesubdb) as a source. But no subtitles are downloaded for any of the other shows (which are British or American TV shows). That has been the case since sometime in July or so (sorry, the History page only extended back to August 1 when I first started to investigate this matter).

Any idea what is causing this undesirable behavior? Do I have some setting wrong, or is there a bug in Sickrage? Log is at https://gist.github.com/anonvoy/976e50106b3538ff6eb3.  I see a lot of "Exception caught in subliminal.scan_video" messages in that log. Sorry, I don't have any logs with successful subtitle downloads anymore.

**Comment by WebSpider** [comment]
Hm, we currently don't log that much detail in DEBUG logging. Will increase the logging a bit, so we can see what's going on.

**Comment by WebSpider** [comment]
In the mean time, rename the cache files to something different and restart SR please, maybe you have cache corruption.

**Comment by WebSpider** [comment]
This seems very similar to #2505

**Comment by anonvoy** [comment]
I renamed the cache files and restarted SR. Still no subtitle downloads and still the same error messages:

    2015-08-20 20:06:15 INFO     SHOWQUEUE-SUBTITLE :: Downloading subtitles for Glitch (2015)
    2015-08-20 20:06:15 DEBUG    SHOWQUEUE-SUBTITLE :: 296550: Downloading subtitles
    2015-08-20 20:06:15 DEBUG    SHOWQUEUE-SUBTITLE :: 296550: Downloading subtitles for S01E01
    2015-08-20 20:06:15 DEBUG    SHOWQUEUE-SUBTITLE :: 296550: Exception caught in subliminal.scan_video for S01E01
    2015-08-20 20:06:15 DEBUG    SHOWQUEUE-SUBTITLE :: 296550: Downloading subtitles for S01E02
    2015-08-20 20:06:15 DEBUG    SHOWQUEUE-SUBTITLE :: 296550: Exception caught in subliminal.scan_video for S01E02
    2015-08-20 20:06:15 DEBUG    SHOWQUEUE-SUBTITLE :: 296550: Downloading subtitles for S01E03
    2015-08-20 20:06:15 DEBUG    SHOWQUEUE-SUBTITLE :: 296550: Exception caught in subliminal.scan_video for S01E03
    2015-08-20 20:06:15 DEBUG    SHOWQUEUE-SUBTITLE :: 296550: Downloading subtitles for S01E04
    2015-08-20 20:06:15 DEBUG    SHOWQUEUE-SUBTITLE :: 296550: Exception caught in subliminal.scan_video for S01E04
    2015-08-20 20:06:15 DEBUG    SHOWQUEUE-SUBTITLE :: 296550: Downloading subtitles for S01E05
    2015-08-20 20:06:15 DEBUG    SHOWQUEUE-SUBTITLE :: 296550: Exception caught in subliminal.scan_video for S01E05
    2015-08-20 20:06:15 DEBUG    SHOWQUEUE-SUBTITLE :: 296550: Downloading subtitles for S01E06
    2015-08-20 20:06:15 DEBUG    SHOWQUEUE-SUBTITLE :: 296550: Exception caught in subliminal.scan_video for S01E06

**Comment by anonvoy** [comment]
Any progress with this? The problem persists. Right now, no subtitles at all are downloaded (the one show that **was** subtitled has ended). Same error messages in logs, I don't note any increased logging as was mentioned.

**Comment by miigotu** [comment]
@anonvoy I think your naming pattern is funky maybe. How are your files named?

**Comment by anonvoy** [comment]
I use the name pattern "Show Name - 2x03 - Ep Name.ext". No additional options. I haven't changed that since I installed SR.

**Comment by anonvoy** [comment]
Is there any way to see why there are all those "Exception caught in subliminal.scan_video" errors? Is there a log anywhere for subliminal.scan_video?

**Comment by miigotu** [comment]
@anonvoy I was just going to say exactly that. After the dallas game (and maybe after the broncos game) I will add exception info there so you can see exactly why it is failing.

**Comment by anonvoy** [comment]
**@miigotu** I got the subtitle download working again, but it is not working 100% as it should IMO. After you inquired about the name pattern, I decided to experiment with it and tried custom patterns. With some of them, subtitles are downloaded effortlessly (new episodes or via mass update), namely

     %SN - %Sx%0E - %EN - %QN

and

    %SN - %Sx%0E - %EN.


Unfortunately, both place all episodes directly in the series folder, not in the season subfolders I want. So I tried

    %0S/ %SN - %Sx%0E - %EN - %QN

and

    %0S/ %SN - %Sx%0E - %EN.

Those placed the episodes directly in the season subfolders as I wanted, but no subtitles were downloaded, with the usual errors in the logs.

So it seems the subtitle download only works when the episodes are **not** in season subfolders. Strangely, that is and was not the case with the one series mentioned in my first post for which the subtitle download worked, *Deutschland 83*. The episodes are (and were)  in a season subfolder there.

**Comment by miigotu** [comment]
Mine works with season sub folders.

Season %0S/ %SN - %0SE%0E - %EN.ext

**Comment by anonvoy** [comment]
Yes, as soon as I put a "Season" in front of my name pattern, like

Season %0S/ %SN - %Sx%0E - %EN - %QN,

subtitle download works here too. So it seems season folders that have only numbers in the title are what is problematic.

**Comment by miigotu** [comment]
It needs at least an S as in S01 or Season 01 for the folder name.

**Comment by anonvoy** [comment]
With the latest SR revision from today, subtitle downloads started working again even if the season subfolder names are numbers only. Thanks for whatever changes were made.

**Comment by miigotu** [comment]
@anonvoy yes, I have updated guessit again. Good to know.
