### ISSUE TITLE
[APP SUBMITTED]: addExistingShows() got an unexpected keyword argument 'show'

### ISSUE THREAD

**Issue by mbxplex** [SiCKRAGETV/sickrage-issues#2509]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@fe0111aa88dc6d65177f339e643ca971405f926f
Link to Log: https://gist.github.com/cc21aa43ef0611dfd2d9
### ERROR
```
Thread-67 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 260, in async_call
    result = function(**kwargs)
TypeError: addExistingShows() got an unexpected keyword argument 'show'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by WebSpider** [comment]
That logfile doesn't contain the actual error. Can you please enable debugging and add a logfile that contains the error, plus what happened before and after?

**Comment by neoatomic** [comment]
@mbxplex Probably the cache that is causing this. Remove the cache folder and let SR build a fresh one.

**Comment by MGaetan89** [comment]
Shouldn't we add a "Clear cache" option somewhere in the settings?
Or maybe automatically clear the cache after an update?
It seems it is a common suggestion to fix issues.

**Comment by MGaetan89** [comment]
What show/path did you try to add?

**Comment by miigotu** [comment]
He gets no help.

**Comment by mbxplex** [comment]
@miigotu  ... sorry I haven't responded or sent you that donation yet. I just got out of the hospital today. I was involved in a pretty shitty car accident ... broke 2 ribs, severe concussion and some pretty bad facial damage. 

Sending donation of $100 tomorrow now that I'm out. Sorry again for the delay.

**Comment by miigotu** [comment]
22 days in hospital? 0.o. Anyways, today is almost over. Not mad, but this one is more of a payment than a donation, because I did work for you for a pre-set amount =P.

**Comment by mbxplex** [comment]
Yea, it was a long time! I also have epilepsy and I had a couple seizures in the hospital from the head trauma. 

I transferred money from my Vanguard account, and it was supposed to come through today but it looks like tomorrow. Expect a payment tomorrow... sorry for the mayhem! I'm all over the place since this accident!

**Comment by miigotu** [comment]
Np. Hope you're ok though.

**Comment by mbxplex** [comment]
@miigotu Not going to be able to go back to work for awhile but, all-in-all, I'm alive and home now!

I'll msg you on IRC once I send that over. I feel horrible ... didn't want you to think I blew you off! Not like that at all ... just waiting for my money to come through!

**Comment by WebSpider** [comment]
@mbxplex All the best to you! Good part of not going to work is you have more time to appreciate SR and help it get even better! ;)

**Comment by miigotu** [comment]
Glad I didn't hold my breath or anything lol.

**Comment by miigotu** [comment]
@mbxplex Hey, it's no big deal man, I can wait. Just throw me something when you can.

**Comment by mbxplex** [comment]
@miigotu I'm having a lot of issues right now ... with EVERYTHING! :( 

PNC overdrafted me 4,000 F*cking times, so I closed my account after paying them like 200$ in OD fees, I had 2 more seizures and my insurance is trying not to cover a certain portion of my hospital bills.

I have an appointment next week with fifth third to open a new account and a start a new job tomorrow working behind the desk at national tire and battery for my cousin so I will be sending you money as soon as I can. My life got superf*cked and I'm trying to bounce back. I will be sending you an overdraft fee as well for taking so long to pay you for your assistance ... just bare with me. I have  bill collectors calling me multiple times a day because I fell behind on my bills when I was in the hospital.

**Comment by miigotu** [comment]
Take your time man, I've been in some bad situations myself so I understand.
