### ISSUE TITLE
[APP SUBMITTED]: getDBcompare() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by technazz** [SiCKRAGETV/sickrage-issues#2510]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@fe0111aa88dc6d65177f339e643ca971405f926f
Link to Log: https://gist.github.com/c5c377543f03309ba3aa
### ERROR
```
Thread-165 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRagemaster\sickbeard\webserve.py", line 260, in async_call
    result = function(**kwargs)
  File "C:\SickRagemaster\sickbeard\webserve.py", line 1202, in getDBcompare
    db_status = checkversion.getDBcompare(branchDest)
TypeError: getDBcompare() takes exactly 1 argument (2 given)

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by technazz** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@fe0111aa88dc6d65177f339e643ca971405f926f
Link to Log: https://gist.github.com/bc26d2ad4d5514da2f39
### ERROR
```
Thread-187 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRagemaster\sickbeard\webserve.py", line 260, in async_call
    result = function(**kwargs)
  File "C:\SickRagemaster\sickbeard\webserve.py", line 1202, in getDBcompare
    db_status = checkversion.getDBcompare(branchDest)
TypeError: getDBcompare() takes exactly 1 argument (2 given)

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
@fernandog missed a few...

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/commit/06b9304cebc84e978f6a92ddde99813b1ffe5c67

**Comment by fernandog** [comment]
@miigotu what should I do with this?

https://github.com/SiCKRAGETV/SickRage/blob/develop/gui/slick/js/config.js#L71

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/commit/4238c5d7a845fe57e9cb01dee7694b55ad856824

**Comment by fernandog** [comment]
@miigotu getting this:

don't know how to fix it

```
        2015-08-19 12:46:10 Thread-13 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 260, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 1202, in getDBcompare
    db_status = checkversion.getDBcompare()
  File "/home/osmc/SickRage/sickbeard/versionChecker.py", line 197, in getDBcompare
    response = requests.get("http://cdn.rawgit.com/SICKRAGETV/SickRage/" + str(self._newest_commit_hash) +"/sickbeard/databases/mainDB.py")
AttributeError: CheckVersion instance has no attribute '_newest_commit_hash'
```

**Comment by miigotu** [comment]
@fernandog I committed a fix for that last error. Its `self.updater.get_newest_commit_hash()`
