### ISSUE TITLE
After SR update, SR no longer starts (AttributeError)

### ISSUE THREAD

**Issue by loungebob** [SiCKRAGETV/sickrage-issues#2515]
SR told me I'm 11 commits behind, so I updated. It seemed to restart after config save and update but then the below page loaded and now I cant get it to start anymore. Tried manually restarting the SR service, the SR.py file. nothing.

Error !

AttributeError: 'module' object has no attribute 'TRAKT_USE_ROLLING_DOWNLOAD'

</td> <td align="center"> <img src="${sbRoot}/images/${('no16.png", alt="No"', 'yes16.png", alt="Yes"')[int(curShow.paused) == 0 and curShow.status == 'Continuing']} width="16" height="16" /> </td> <td align="center"> <% display_status = curShow.status %> % if None is not display_status: 

F:\Mediaserver\SickRage\gui/slick/interfaces/default/home.mako, line 818:

<img src="${sbRoot}/images/${('no16.png", alt="No"', 'yes16.png", alt="Yes"')[int(curShow.paused) == 0 and curShow.status == 'Continuing']} width="16" height="16" />

F:\Mediaserver\SickRage\lib\mako\runtime.py, line 853:

callable_(context, *args, **kwargs)

**Comment by Plokip8** [comment]
Had the exact same problem. Only on the homepage (/home). Other pages (/news, /comingEpisodes, etc) worked. Did some searching. Removed the local folder "\cache\mako" in the directory you installed sickrage (for me c:\program files\SickRage). And then restarted SickRage. Everything worked again.

**Comment by loungebob** [comment]
You're brilliant! Thanks mate, that seemed to have solved it.

**Comment by snoopyowns** [comment]
Nice Plokip8. Thanks for the info. I too had this problem. As a temporary measure I just re-added in the TRAKT use rolling download line that was removed in a previous commit.
