### ISSUE TITLE
trackt.tv show duplication

### ISSUE THREAD

**Issue by mgaulton** [SiCKRAGETV/sickrage-issues#2516]
I've noticed that if I have a show added as TVRage and i turn on trackt syncing, it creates duplicates of the shows, using the tvdb show id. Not sure if there's a way to avoid this, but its kind of annoying.

BRANCH: (master) / COMMIT: (fe0111aa88dc6d65177f339e643ca971405f926f) 
Opensuse 13.2 x64 
What you did: Enabled Trakt sync
What happened: Show Duplication
What you expected: Existing shows should not have duped.
Link to a copy/paste of your logfile with clear debug info of the error on GIST

**Comment by WebSpider** [comment]
Can you please provide debug logs?

**Comment by neoatomic** [comment]
@mgaulton Without logs we cant do anything and this will be closed.
