### ISSUE TITLE
SR is downloading old/deleted episodes marked as archived

### ISSUE THREAD

**Issue by er2or** [SiCKRAGETV/sickrage-issues#2518]
SR is downloading episodes marked as archived

Branch : master
Commit hash : fe0111a
Your operating system and python version : QNAP NAS, python 2.7
What happened : SR suddenly started downloading old(deleted/moved) episodes that were marked as Archived (Defiance S02E07,E10)
What you did : deleted the DB and created a new one, reinstalled sickrage QPKG package, tried to mark old episodes as Ignored (few commits back, and SR was randomly downloading these too)
What you expected : SR not downloading old Archived episodes

https://gist.github.com/er2or/a466133a76f6ef1e283d#file-sickrage-txt

**Comment by miigotu** [comment]
`SEARCHQUEUE-MANUAL-255326 :: Beginning manual search for: [Defiance - 2x10 - Bottom of the World]`
`SEARCHQUEUE-MANUAL-255326 :: Beginning manual search for: [Defiance - 2x07 - If You Could See Her Through My Eyes]`

If you click the magnifying glass and force a search it is going to download it regardless of status.

**Comment by er2or** [comment]
But this is not the case. I'm the only user. At it's worst it started downloading 200 episodes overnight

**Comment by miigotu** [comment]
Maybe your SR is accessible from the internet? The only way a manual search can be started is from clicking the magnifying glass.

Set a login for SR.
