### ISSUE TITLE
Search scene numbering

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2520]
@miigotu  btdigg doesnt seem to be respecting scene numbering in the searches ,any clue why? 
log: http://pastebin.com/xSnHqP6H

**Comment by miigotu** [comment]
@duramato I see nothing in that log...

**Comment by duramato** [comment]
@miigotu look at the last search and compare btdigg search string with for example tntvillage or rarbg

**Comment by miigotu** [comment]
They are all searching for the same episode numbers -.-

**Comment by duramato** [comment]
Not sure if  I'm just confused but look at this line ```https://api.btdigg.org/api/private-341ada3245790954/s02?q=Selling.Big S02E01&p=0&order=1``` and this one ```http://forum.tntvillage.scambioetico.org/?act=allreleases&st=0&cat=0&filter=Selling Big S01E06```  the btdigg one ```Selling.Big S02E01``` and tntvillage for example ```Selling Big S01E06``` which is the correct numbering

**Comment by miigotu** [comment]
btdigg provider code is disgusting. There is however a branch for provider cleanup/rewrite which I haven't gotten started on yet.
