### ISSUE TITLE
Error after last upgrade

### ISSUE THREAD

**Issue by Danny89530** [SiCKRAGETV/sickrage-issues#2521]
This error appears after upgrading to the last commits.
Inside the log is reported only the login event

![schermata 2015-08-20 alle 11 41 41](https://cloud.githubusercontent.com/assets/3729455/9380442/730389c4-4730-11e5-9455-7d7508407400.PNG)

**Comment by WebSpider** [comment]
Stop SR,

 

Delete cache\mako folder

 

Restart SR

**Comment by Danny89530** [comment]
It works now.
Thank you!
