### ISSUE TITLE
[Feature Request] Archive on first match of any in replacement list

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2523]
Currently I'm using this for all of my shows. What'd I'd like is to have it archive an episode when it matches ANY in the "Replace with" group.

Initial: HDTV, 720p WEB-DL, 1080p WEB-DL, 720p BluRay, 1080p BluRay
Replace with: 1080p WEB-DL, 1080p BluRay

@miigotu We talked about this but I'm not sure what we decided on.

**Comment by WebSpider** [comment]
To my knowledge, this is how it works when you have custom quality, and archive on first match checked?

**Comment by miigotu** [comment]
@OmgImAlexis you should only have a quality in either initial OR preferred list. Then archive on first match might work properly.

This whole quality management should be replaced soon as I don't like how inflexible it is anyways.

**Comment by OmgImAlexis** [comment]
@WebSpider @miigotu tried both and it doesn't seem to work the way I want. Archive on first match just archives after it downloads ANY quality in either initial or required.

**Comment by WebSpider** [comment]
That is what I would expect!

What would you expect?

-----Original Message-----

**Comment by OmgImAlexis** [comment]
Talked to @miigotu on IRC. What I was hoping for and what I originally assumed was it would archive on first match of ANY in only the replace list. The reason I thought it'd do that was because of the way CP handles this.

**Comment by fernandog** [comment]
archived feature: I would like an option to instead of SR changing (PP or refresh) status from "Snatched" to "Downloaded 1080p web-dl" , change straight to "Archived 1080p web-dl" from "snatched"- if this is the best quality. Otherwise user will have to manually change all "Downloaded" to "Archived"

**Comment by OmgImAlexis** [comment]
That's how it's "should" work in my opinion and that's what I was expecting it to do, like I said this is how CP handles it and it makes more sense than how it was before.

**Comment by miigotu** [comment]
@fernandog thats exactly how it will work once the feature is finished. It is nearly there.

Archive on first match will make it archive the first whether it is initial or preferred list, but if it is ANY of the preferred it will be archived always.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
