### ISSUE TITLE
[Feature Request] Add support for adding shows via TVDBid

### ISSUE THREAD

**Issue by saitoh183** [SiCKRAGETV/sickrage-issues#2524]
I recently came across a problem that i was unable to add a french TV show because the search would come up empty. I spoke to a user on IRC and when he would search, he was able to find the show.

this is the show in question : http://thetvdb.com/?tab=series&id=273086&lid=17
Users search result:
https://cloud.githubusercontent.com/assets/7928052/9384074/d96703c2-474d-11e5-8764-dd67d28b94cc.png

My search result:
http://snag.gy/LbV1C.jpg

He is on Linux and i am on Windows. My only possible explanation is the SR Local setting is causing the problem. mine is set to en 'CA', 'cp1252' 

If we were able to search by TVDBID then i think this wouldnt be a issue.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
