### ISSUE TITLE
[Feature Request] Auto detect flat folders when adding existing shows

### ISSUE THREAD

**Issue by miigotu** [SiCKRAGETV/sickrage-issues#2527]
In adding existing shows, the checkbox in the add show options should be hidden, and we should auto-detect if the show has flat folders and set the value accordingly.

If a show has videos with a valid name in the top level of the show dir, and does not have videos in a Season*/ folder then it must be flat folders

**Comment by WebSpider** [comment]
Off course taking into account naming patterns, since I'm using Show/S01/episode.original.name.mkv for instance

-----Original Message-----

**Comment by miigotu** [comment]
Basically if there are videos in the top level of the show dir, that parse to match the show, it is flat folders no?

**Comment by WebSpider** [comment]
I'd say if there are videos in the root and there are no videos in any subfolders

-----Original Message-----

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
