### ISSUE TITLE
Pushover sound resets to default after update

### ISSUE THREAD

**Issue by Talung** [SiCKRAGETV/sickrage-issues#2529]
SR Version:	BRANCH: (master) / COMMIT: (5770d33ef96e619af764b452ea35ad33e5755add)

I use pushover notifications to notify me when a show has downloaded.  Everything works as intended including the "Pushover notification sound".  However, every time sickrage does an update (I have it set to automagically update) it resets the sound to the default Pushover sound. I then need to manually set it to the sound I want.

Another issue is having an option to NOT send a sound allowing it to use pushover defaults.  The "Pushover" sound overrides the device default sounds.  I believe the "device sound" option should be the default.

**Comment by Mickroz** [comment]
i have the same problem, sickrage isn't using my sound selected in the app for new notifications but instead uses the default pushover sound.
I have a custom sound, not 1 implemented in pushover, and therefor cannot set it in sickrage notification settings for pushover.

**Comment by Talung** [comment]
BRANCH: (master) / COMMIT: (4db41da61c3e4639a19613a3e4f0dfeef9831fc0) 

After update it is still defaulting to the "Pushover" sound and not the sound I selected.  The "Device Specific" sound is working as expected.
