### ISSUE TITLE
from Shows list:   click certain shows and an error occurs ...

### ISSUE THREAD

**Issue by ThePOO** [SiCKRAGETV/sickrage-issues#2530]
BRANCH: (master) / COMMIT: (5770d33ef96e619af764b452ea35ad33e5755add) 
2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
Windows 7 64-bit sp1

Below I have listed three shows:   Grimm, Hannibal, Recitfy ... and their errors when selecting them from the Shows list.

Grimm and Rectify have been on my Shows list for a long time, as was Hannibal.    I first encountered the Hannibal error a short while ago and completely removed it from SR (I moved the actual shows to a temp location first) ... then I re-added Hannibal and the exact same error occurs as before when selecting Hannibal from the Shows list.    After this I then checked ALL my shows and found that Grimm and Rectify produced very similar errors as well.

Here's hoping for a speedy fix ... and a hearty thanks to the developers.

***** Grimm *****

Error !

UnicodeEncodeError: 'charmap' codec can't encode character u'\u0301' in position 71: character maps to <undefined>

% endif <% curSeason = int(epResult["season"]) %> % endif <% epLoc = str(epResult["location"]) %> <tr class="${Overview.overviewStrings[epCats[epStr]]} season-${curSeason} seasonstyle"> <td class="col-checkbox"> % if int(epResult["status"]) != UNAIRED: <input type="checkbox" class="epCheck" id="${str(epResult["season"])+'x'+str(epResult["episode"])}" name="${str(epResult["season"]) +"x"+str(epResult["episode"])}" /> % endif
C:\Python27\lib\encodings\cp1252.py, line 12:
return codecs.charmap_encode(input,errors,encoding_table)
C:\SickRage\gui/slick/interfaces/default/displayShow.mako, line 466:
<% epLoc = str(epResult["location"]) %>
C:\SickRage\lib\mako\runtime.py, line 853:
callable_(context, *args, **kwargs)

***** Hannibal *****

Error !

UnicodeEncodeError: 'charmap' codec can't encode character u'\u014d' in position 59: character maps to <undefined>

% endif <% curSeason = int(epResult["season"]) %> % endif <% epLoc = str(epResult["location"]) %> <tr class="${Overview.overviewStrings[epCats[epStr]]} season-${curSeason} seasonstyle"> <td class="col-checkbox"> % if int(epResult["status"]) != UNAIRED: <input type="checkbox" class="epCheck" id="${str(epResult["season"])+'x'+str(epResult["episode"])}" name="${str(epResult["season"]) +"x"+str(epResult["episode"])}" /> % endif
C:\Python27\lib\encodings\cp1252.py, line 12:
return codecs.charmap_encode(input,errors,encoding_table)
C:\SickRage\gui/slick/interfaces/default/displayShow.mako, line 466:
<% epLoc = str(epResult["location"]) %>
C:\SickRage\lib\mako\runtime.py, line 853:
callable_(context, *args, **kwargs)

***** Rectify *****

Error !

UnicodeEncodeError: 'charmap' codec can't encode character u'\ufeff' in position 56: character maps to <undefined>

% endif <% curSeason = int(epResult["season"]) %> % endif <% epLoc = str(epResult["location"]) %> <tr class="${Overview.overviewStrings[epCats[epStr]]} season-${curSeason} seasonstyle"> <td class="col-checkbox"> % if int(epResult["status"]) != UNAIRED: <input type="checkbox" class="epCheck" id="${str(epResult["season"])+'x'+str(epResult["episode"])}" name="${str(epResult["season"]) +"x"+str(epResult["episode"])}" /> % endif
C:\Python27\lib\encodings\cp1252.py, line 12:
return codecs.charmap_encode(input,errors,encoding_table)
C:\SickRage\gui/slick/interfaces/default/displayShow.mako, line 466:
<% epLoc = str(epResult["location"]) %>
C:\SickRage\lib\mako\runtime.py, line 853:
callable_(context, *args, **kwargs)

**Comment by WebSpider** [comment]
Duplicate #2504
