### ISSUE TITLE
Show status and show update scheduling ...

### ISSUE THREAD

**Issue by ThePOO** [SiCKRAGETV/sickrage-issues#2531]
BRANCH: (master) / COMMIT: (5770d33ef96e619af764b452ea35ad33e5755add) 
2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
Windows 7 64-bit sp1

Example:    Let's say a show airs today at 8:00pm and is 1 hour long.    At 9:05pm I look at coming episodes and the show appears in "pink" as it should.    Just after midnight I check the coming episodes and the show no longer appears at all.   When checking the shows list the episode shows as Aired Yesterday with a status of Unaired?????   It should be status of Wanted and should still be on the coming episodes list.    I have my shows update set to occur at 1am --- well, that never occurs ------ that was broken by an update weeks ago.     When I manually use Mass Update and update all shows the example episode re-appears back on the coming episodes list in "pink" ... on the shows list it then shows as Aired Yesterday with a status of Wanted.

1.   Please fix the shows update scheduler to run on time
2.   Please fix the handling of show status/coming episodes list issues

It is really late at night -- I hope I was clear here.    Anyway, thanks.

**Comment by WebSpider** [comment]
I am suspecting we are missing some saves to database here.

**Comment by ThePOO** [comment]
I set up the basic system for myself and months later set up the same thing for a friend.    He is having the same issues I am with shows .... they appear pink before midnight, disappear after midnight, show as aired yesterday/unaired --- then re-appear pink only after you do a forced update.    It is a reproducible in our experience.    This only started happening many, many, many months after we started using the software and appears to have begun to be happening only after some updates some time ago .... 
I'm sorry I'm so nebulous about time-frames .... when I first noticed the problem I thought only I had the issue .... .then about 2 months later checked with my friend --- shazamm, he's having the same issue .....

I'm considering re-installation of the program and make all my settings and re-add all my shows .... that's gonna hurt!     But, if there's a cure that'd be nice.

**Comment by miigotu** [comment]
@ThePOO both installs you are comparing for the issue have a common denominator (you installed it), so that information doesn't really give any validity to the issue. You must be open to the possibility that you configured something wrong (on both machines).

I would suggest clearing out your cache/sessions and cache/indexers folders to start.

@WebSpider the info is explicitly saved to db on show update, and show updater most certainly runs on time as far as I can see. The issue of 0 is also fixed for updating at exactly midnight.

**Comment by ThePOO** [comment]
Clearing cache/sessions and cache/indexers folders now ... I will let you know how it all turns out just after midnight tomorrow night.    Thanks.

**Comment by doopsuiker** [comment]
I have the same issue.
I installed Sickrage with all default settings and added one show and set the show update time at 1 am.
At 1 am, the show updater didn't start running.

Running version 4.0.51 on Windows 10 with Python 2.7.10

**Comment by ThePOO** [comment]
Some positive progress!    Kudos to miigotu for his suggestion .... I cleared out my c:\sickrage\cache\sessions and c:\sickrage\cache\indexers folders and now my Show Updater launched promptly at 1:00am as scheduled.     That is once again working like a champ!

Now, for the continuing weird part.    A show at 8:00pm finishes in an hour.   That show then appears on the coming episodes list in pink, as it should.    Promptly at midnight the show disappears from the coming episodes.    When the Show Updater runs that show that went missing on the episodes list re-appears.    The show then attains an aired Yesterday and status Wanted (status stays at unaired until the Show Updater runs.    I have 160 shows that get evaluated at 1:00am and that process takes more than 3 hours to complete.    I'm running with a quad core processor, SSD for drive C:, and have sickrage set to Low to use more processor.    It still seems off that shows drop off the coming episodes at midnight.

Anyway, 1 problem solved --- my Show Updater now runs on schedule.    1 oddity remains -- shows dropping off the coming episodes list at midnight, when my contention is that they should not.    AND, once aired their status should change to Wanted, rather than unaired ------ because they HAVE aired.

Good night folks, be back tomorrow to see if anyone has comments about the remaining oddity above.

**Comment by miigotu** [comment]
Maybe you need to switch network time -> local time or vice versa.

**Comment by ThePOO** [comment]
Oh, hey ...  thanks for your suggestion ... worked like a champ .... shows are being updated.    Still have the remaining oddity though.       I'm a real new subscriber to this forum .... so new that I haven't looked at my profile yet.   <smile>    Perhaps it would be, indeed, time for me to look and make appropriate changes to my profile. 

Again, much thanks for your suggestion about the cache folders .. that worked on both installations.

**Comment by ThePOO** [comment]
I looked at my profile .. didn't change anything.
I looked at my configuration for SR and I have it set for Local time.    How would that setting have anything to do with shows dropping off the coming episodes list at midnight?     (of course I'll change the setting to Network and see if that fixes it)

**Comment by ThePOO** [comment]
Be back tomorrow ...

**Comment by miigotu** [comment]
@ThePOO didnt understand what you were talking about profile? Anyways, if your time is 3 hours diff from show time there might be an issue with when the show is changed to wanted from unaired and drops off the coming episodes. It might be thinking it is the wrong time ^.

**Comment by ThePOO** [comment]
As suggested, I changed my timezone from Local to Network .... it behaves exactly
the same as it was when set to Local.

** 11:00pm ...

Each episode that is pink in the Coming Episodes screen shows as
Airdate=Today and Status=Unaired on their respective program listing
pages.  
The shows -should- read Airdate=Today, Status=Wanted
and be pink.    This used to be the normal behavior.

** Midnight ...

All the pink episodes on the Coming Episodes screen have disappeared.
All those episodes now read Airdate=Yesterday and Status=Unaired on their respective
program listing pages.
The shows -should- read Airdate=Yesterday, Status=Wanted
and be pink.     Again, this used to be the normal behavior.


The Shows Update task kicked off 00:00:02  ............... that's completely fixed.

** 00:20am ...

The first "missing" episode has returned to the Coming Shows page and is again pink.
That show is also pink on its program listing page with Airdate=Yesterday, Status=Wanted.
Exactly as it should be, in the end.
---

The shows disappearing from the Coming Episodes and the incorrect
status and coloration of the shows on the program listing pages remain
outstanding oddities.

Anyway, those are my observations for tonight ... At least the Show Update occurs on schedule,
my shows get set to Status=Wanted, and subsequently will get snatched in due time.

I rest .....

**Comment by Thraxis** [comment]
Open the show page. In the top block what does it say for:  Default EP Status:

If it does not say "Wanted" edit the show and set the Default Episode Status to Wanted.

**Comment by ThePOO** [comment]
Just following the news item you mention I did do the Mass update on, or about the 17th, to ensure all my shows status were set to Wanted.

I just checked all my shows on their show pages and every one has the Default Episode Status=Wanted.    I then checked the Mass update page and they all are listed as Wanted.

Just for good measure I did a mass edit and re-asserted my desire for all Default Episode Status to be Wanted.

I then re-checked every shows page and they reflect Wanted.    The Mass update page says they are all Wanted.

This evening I will, again, watch the status of my shows on the Coming Episodes and show pages.   I'll also see what happens to all the statuses just after midnight, etc.

Realizing how delicate databases can be at times I'm in hopes that all is repaired by the above actions and everything returns to its former standard behavior.   <smile>

And, in case I haven't said it enough ---- THANKS TO EVERYONE WHO HAS PARTICIPATED IN MY QUEST!

**Comment by ThePOO** [comment]
okay, dokey.    No change tonight.    Everything is exactly as was experienced 24 hours ago.

My Shows Updater ran on time --- check.
My episodes -will- be showing correctly in the Coming Episodes and Show pages as soon as the Shows Updater does its job on them.     And, for now that satisfies me.     The episodes status are only being incorrectly displayed, or not at all, for as long as it takes for my Shows Updater to run at midnight, which now takes about 2 hours tops --- for 167 shows, +/-        Subsequently, shows get snatched in due time and that keeps me happy.
Not perfect, but darn close and like horseshoes sometimes close is enough.
Thanks for all the help, see you cool cats later.
Can someone close this thread for now and put this one to sleep ... I do hope others may benefit from this series of events here --- the cure for my Show Updater running, and running on time was perfect.
