### ISSUE TITLE
Thecus SSL errors Torrent sites

### ISSUE THREAD

**Issue by pentium3nl** [SiCKRAGETV/sickrage-issues#2532]
BRANCH: (master) / COMMIT: (5770d33ef96e619af764b452ea35ad33e5755add) 
Linux 3.0.93 #1 SMP PREEMPT Wed Aug 28 18:50:38 CST 2013 x86_64 GNU/Linux (Thecus)
Python Version:	2.7.6 (default, Apr 3 2014, 09:45:36) [GCC 4.5.3]
SR Arguments:	['-d', '-p', '8081', '--datadir', '/raid/data/MOD_CONFIG/SICK/DATA', '--config', '/raid/data/MOD_CONFIG/SICK/CONF/sickbeard.conf', '--nolaunch']

I added IPTorrents and Torrentleech for searing episodes. It worked till mid june when i received the following errors:

```
2015-08-21 09:15:13 SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: Unable to connect to IPTorrents provider: error [Errno bad handshake] [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]
        2015-08-21 09:15:13 SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: Unable to connect to TorrentLeech provider: error [Errno bad handshake] [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]
```
Disabling this option, did not work for me:
Verify SSL Certificates (Disable this for broken SSL installs (Like QNAP)

I expected for it to search for episodes wich it didn't.
Im not the only one with this error as reported on the website from Thecus:
http://forum.thecus.com/viewtopic.php?f=36&t=8251&start=130

Debug Logging:
```
2015-08-21 09:42:22 INFO     SEARCHQUEUE-BACKLOG-110381 :: [Usenet-Crawler] :: Performing episode search for Archer (2009)
2015-08-21 09:42:22 INFO     SEARCHQUEUE-BACKLOG-110381 :: [Womble's Index] :: Performing episode search for Archer (2009)
AASSLError: [Errno bad handshake] [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]
AA    raise SSLError(e, request=request)
AA  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/lib/requests/adapters.py", line 431, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/lib/requests/sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/lib/requests/sessions.py", line 476, in get
AA    self.session.get(self.urls['login'], timeout=30)
AA  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/sickbeard/providers/iptorrents.py", line 96, in _doLogin
AATraceback (most recent call last):
2015-08-21 09:42:22 ERROR    SEARCHQUEUE-BACKLOG-110381 :: [IPTorrents] :: Unable to connect to IPTorrents provider: error [Errno bad handshake] [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]
2015-08-21 09:42:22 INFO     SEARCHQUEUE-BACKLOG-110381 :: [IPTorrents] :: Performing episode search for Archer (2009)
2015-08-21 09:42:21 INFO     SEARCHQUEUE-BACKLOG-110381 :: [KickAssTorrents] :: Performing episode search for Archer (2009)
AASSLError: [Errno bad handshake] [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]
AA    raise SSLError(e, request=request)
AA  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/lib/requests/adapters.py", line 431, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/lib/requests/sessions.py", line 464, in request
AA    return self.request('POST', url, data=data, json=json, **kwargs)
AA  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/lib/requests/sessions.py", line 507, in post
AA    response = self.session.post(self.urls['login'], data=login_params, timeout=30)
AA  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/sickbeard/providers/torrentleech.py", line 95, in _doLogin
AATraceback (most recent call last):
2015-08-21 09:42:21 ERROR    SEARCHQUEUE-BACKLOG-110381 :: [TorrentLeech] :: Unable to connect to TorrentLeech provider: error [Errno bad handshake] [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]
2015-08-21 09:42:21 INFO     SEARCHQUEUE-BACKLOG-110381 :: [TorrentLeech] :: Performing episode search for Archer (2009)
2015-08-21 09:42:21 INFO     SEARCHQUEUE-BACKLOG-110381 :: Beginning backlog search for: [Archer (2009)]
2015-08-21 09:41:42 INFO     Thread-128 :: Sending backlog for Archer (2009) season 1 because some eps were set to wanted
```
Can you please help me as i want to use torrents as well. KickAssTorrents works just fine as that one doesn't use SSL.

**Comment by WebSpider** [comment]
Disable SSL Verify in Config > General Advanced

**Comment by pentium3nl** [comment]
Dear Webspider,

Thank you for your reply. I already disabled this option as it didnt work for me:

Verify SSL Certificates (Disable this for broken SSL installs (Like QNAP)

**Comment by neoatomic** [comment]
@pentium3nl Are you using the latest package.? 

If the verify SSL Certs doesn't work than its highly likely a package problem or Python isn't setup correctly. Python needs to include the PyOpenSSL, and cryptography modules. If those are not included you get SSL problems...

**Comment by pentium3nl** [comment]
Dear Neoatomic, Sorry for the slightly later response but ive been on holiday. I have the Python 2 and 3 installed on the following links: 
http://www.fajo.de/main/en/thecus/modules/python2 
http://www.fajo.de/main/en/thecus/modules/python3

Couchpotato is using the same modules without any problems. The python packages are no longer updated, so that could be another problem as well.

**Comment by neoatomic** [comment]
You only need Python2 for SickRage.

Sadly we have no control over your Python installation or the installation package that u use to install SickRage. So from our side we cant do anything about that....
Maybe you can contact the person who created the package.?

You have to somehow update the Python installation to be able to use SSL/Https connections. 
(Or change the URL in the code to HTTP instead of HTTPS.)

**Comment by pentium3nl** [comment]
I also notice that Sickrage is using their own Python:
Python 2.7.6 (default, Apr  3 2014, 09:45:36)

instead of the one installed:
Python 2.7.3 (default, Dec 26 2012, 10:19:28)

can you explain that?

**Comment by pentium3nl** [comment]
HTTP is not supported with some of the Torrent sites.

**Comment by neoatomic** [comment]
Yes, probably the person that created the installation package decided to use his own version of Python (that doesn't have the correct modules included as i explained above.) for the SickRage installation.

**Comment by pentium3nl** [comment]
So also the python in the sickrage package if compiled by someone else?

**Comment by neoatomic** [comment]
Indeed. SickRage doesn't include Python. The person who created the package added it there.
And that Python package is outdated/does not have all the modules installed for HTTPS.

**Comment by pentium3nl** [comment]
Can you tell me what has been changed in the end of June till the beginning of July that gave me these troubles? In the changelog i see in Change: Enable SSL certificate verification 4.0.30

**Comment by neoatomic** [comment]
You can check the commits for more details/reason about any change we make.

If you think that change is the problem, you can rollback your SickRage version.
(However we cant give ANY support on an outdated SickRage version, and there may be security risks.)
But again, an outdated Python version is giving you those problems, that is what needs to be fixed.

**Comment by pentium3nl** [comment]
Thank you very much, i will try to see if i can get it working again.

**Comment by pentium3nl** [comment]
Dear Neoatomic,

I tested the Python version in order to execute a request for torrentleech perfectly under version 2.7.6:

>>> import requests
>>> requests.get('https://torrentleech.org')
<Response [200]>
>>> requests.get('https://torrentleech.org', verify=False)
<Response [200]>

With a normal response, shouldn't this mean it should work?

**Comment by pentium3nl** [comment]
Here the response (was filtered in the message):

Response [200]

**Comment by miigotu** [comment]
Add verify=True and see it fails. Just uncheck verify SSL certs in config/general on the advanced tab. Then stop SickRage and delete cache/sessions folder.

**Comment by pentium3nl** [comment]
miigotu, got the following response:

Python 2.7.6 (default, Apr  3 2014, 09:45:36)
[GCC 4.5.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.get('https://torrentleech.org', verify=True)
Response [200]

The verify is taking about 15 seconds where the False is giving an response immediately.
I will check that option and empty cache, see if that works.

**Comment by pentium3nl** [comment]
Still the same errors in sickrage with clearing the cache folder

**Comment by miigotu** [comment]
@pentium3nl you unchecked "Verify SSL Certs" in SR settings, saved, then shut down SR, THEN cleared the cache/sessions, cache/rss, cache.db, and cache/indexers ?

Without "Verify SSL Certs" checked there is no reason you should get an error about 'certificate verify failed'

**Comment by pentium3nl** [comment]
Miigotu, I unchecked that option and verified it in the config file as ssl_verify = 0. Stopped sickrage, moved the folder cache entirely  far away from the folder to cache.old, mkdir cache en moved the cache.db far away to cache.db.old and started Sickrage.

I also noticed when i change the line 92 of torrentleech.py by hand from:
response = self.session.post(self.urls['login'], data=login_params, timeout=30)
to
response = self.session.post(self.urls['login'], data=login_params, timeout=60, verify=False)
It will actually login but then failes on the following error:
2015-09-03 00:42:43 WARNING  SEARCHQUEUE-BACKLOG-73141 :: [TorrentLeech] :: Connection timed out accessing getURL https://torrentleech.org/torrents/browse/index/categories/2,26,27,32 Error: error HTTPSConnectionPool(host='torrentleech.org', port=443): Read timed out. (read timeout=30)
So i guess that verify=false has to be set somewhere else as well, and as the config file isn't setting it.

IPTorrents on the other hand doesnt mind the new setting and works now as expected:
2015-09-03 00:46:09 INFO     SEARCHQUEUE-BACKLOG-73141 :: [IPTorrents] :: Performing episode search for American Dad!

line 96+97:
            self.session.get(self.urls['login'], timeout=30, verify=False)
            response = self.session.post(self.urls['login'], data=login_params, timeout=30, verify=False)

added the verify=False

**Comment by miigotu** [comment]
aha! from that I see why it is failing mostly.

I need to fix those so they dont use self.session.post directly, otherwisem the session is not cached for auto cookie handling with cache control. Ill try and look at it later.

**Comment by pentium3nl** [comment]
And then the verify=false will also work? Otherwise i have to reset the configuration files every commit by hand :). Glad that you found something you can work with, you made me a happy leecher today.

**Comment by DanGarion** [comment]
Just glad you guys decided to take another look at this after my closed ticket! Very happy to see we are getting somewhere on this!

**Comment by miigotu** [comment]
@pentium3nl yes the global verify setting will work then. getURL works for post also, and does the actual handling for session caching and verify setting.

**Comment by miigotu** [comment]
@pentium3nl if that doesnt fix it then ur SOL xD.

**Comment by pentium3nl** [comment]
Thank you very much miigotu! I can also confirm that the change to TorrentLeech is also working, the timeouts where caused by TorrentLeech being down. Now it even snatched some episodes :)

IPTorrents is also snatching again.

**Comment by pentium3nl** [comment]
Dear Miigotu,

sorry i have to reopen this issue. I see that IPTorrents is not entirely fixed:

            self.session.get(self.urls['login'], timeout=30)
            response = self.getURL(self.urls['login'],  post_data=login_params, timeout=30)

It is still performing a self.session.get and after a self.getURL.
Here i still see the same error in the logs:
        2015-09-08 18:14:24 SEARCHQUEUE-BACKLOG-73141 :: [IPTorrents] :: Unable to connect to IPTorrents provider: error [Errno bad handshake] [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]

Torrentleech is now giving a new error with the modifications:
        2015-09-08 18:15:49 SEARCHQUEUE-BACKLOG-75692 :: [TorrentLeech] :: Error while searching TorrentLeech, skipping: maximum recursion depth exceeded

**Comment by miigotu** [comment]
there are multiple issues open for the same thing. Ill let you know when this is finally fixed.

**Comment by pentium3nl** [comment]
Thank you very much

**Comment by pentium3nl** [comment]
Small update from my side on this issue. From this point a developer at Thecus updated Python to 	version 2.7.10 (default, Sep 12 2015, 06:17:44) [GCC 4.7.2]. With this i can confirm that everything is working as it should.

This would mean that when a fix on the verify comes out im unable to test it anymore. I still think this fix is important as Qnap (and possible more) users would still have this issue.

**Comment by WebSpider** [comment]
Since we have multiple issues for the same, this one is Thecus specific and Thecus fixed their python, im closing this one. We are tracking qnap, faulty syno packages etc elsewhere
