### ISSUE TITLE
[APP SUBMITTED]: 'ascii' codec can't encode character u'\xe8' in position 83: ordinal not in range(128)

### ISSUE THREAD

**Issue by hardware** [SiCKRAGETV/sickrage-issues#2535]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-59-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5770d33ef96e619af764b452ea35ad33e5755add
Link to Log: https://gist.github.com/33fd3a731a7427edd9be
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: ascii : /var/medias/complete-downloads/X-Files.S09.(+bonus).FRENCH.DVDRip.Xvid.AC3/Bonus/Scènes coupées/X-Files.S09E15 N'abandonnez jamais.avi : error 83 : error 84 : ordinal not in range(128)
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Problem are the special characters. `Scènes coupées` 
Check/Change your locale to utf-8.

**Comment by hardware** [comment]
It's already the case, I will ignore this error, thx.
