### ISSUE TITLE
[Feature Request] Wait timer before searching for new episode to avoid downloading SD and then replacement

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2542]
I have an issue where SR will snatch a copy of a show as soon as it's on my provider but then an hour or so later it'll find a better copy and the first isn't even downloaded so I end up downloading both copies and wasting bandwidth. If there was an option to delay the search for maybe an hour after it first finds a release it'd fix this issue.

Even better would be to have SR stop and remove the first copy and then add the new copy to the downloader of choice, e.g. uTorrent.

**Comment by WebSpider** [comment]
For now, we could skip an episode if it is in Snatched state, later to be replaced by stopping/removing the torrent using API calls to the client?

We need to do some groundwork before client torrent removal can be done safely.

**Comment by OmgImAlexis** [comment]
That won't really help because it'll still pull down both versions and replace the lower quality.

I think an option to wait x hours when only a low quality version is found would help. For example, wait 1 hour if an episode is found in the first list. If in an hour or maybe even the next time it searches if it doesn't find a higher quality version it just pulls that one down.

**Comment by miigotu** [comment]
There are a few things we have to do before we can improve providers/clients in this way.

1. Make db able to downgrade/upgrade intelligently
2. Make a list of all db changes we sort of need now and might need in the future, so that we can make them all in one db version bump. (like storing hash/magnet in sickbeard.db and other places)

This is one of those "it would be nice" but is not an immediate need. We have other things we need to work out still that are proving to be quite major/difficult.

**Comment by miigotu** [comment]
@OmgImAlexis wouldnt increasing your daily search interval mitigate this problem?

**Comment by OmgImAlexis** [comment]
Nope, a lot of the shows I've got the SD goes up about 10 - 20 minutes before the HD. If I change it to for example 3 hours then it may pick up the SD and then wait 3 hours before finding the HD. Doesn't fix the issue. :disappointed:

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
