### ISSUE TITLE
[Feature Request] Implement sports scene rules (they are specific per sport)

### ISSUE THREAD

**Issue by WebSpider** [SiCKRAGETV/sickrage-issues#2544]
https://scenerules.org/t.html?id=2009_X264_SPORTS.nfo

Unless guessit has plans to implement sports detection, @toilal ?

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
