### ISSUE TITLE
Encoding Error UTF-8

### ISSUE THREAD

**Issue by georgeh12** [SiCKRAGETV/sickrage-issues#2548]
1. Branch
BRANCH: (master)
1. Commit hash
COMMIT: (5770d33ef96e619af764b452ea35ad33e5755add) 
1. Your operating system and python version
Windows 10, Python 2.7 (r27:82525, Jul 4 2010, 07:43:08) [MSC v.1500 64 bit (AMD64)]
1. What you did
Opened the show "Hannibal" on NBC, scraped using tvDB
1. What happened
Mako runtime error having to do with UTF-8 encoding
1. What you expected
Other shows do not have this issue. The UTF-8 character causing this issue must be specific to the Hannibal show.
1. Link to a copy/paste of your logfile with clear debug info of the error on GIST
No errors appeared in the log file:  
https://gist.github.com/georgeh12/c1640505b46fce98844a  
This is the line referenced (commenting the line removed the error, but I'm not sure of other side affects):
https://github.com/SiCKRAGETV/SickRage/blob/master/gui/slick/interfaces/default/displayShow.mako#L466

**Comment by miigotu** [comment]
This is a duplicate, but about your error with L466, what happens if you just make it 
```python
<% epLoc = epResult["location"] %>
```

?

**Comment by miigotu** [comment]
@OmgImAlexis we need to eliminate as many str() calls in mako as we can. especially if they are strings containing names, paths, etc. numbers only wont cause issues, but str() might can be replaced with unicode(), or left out entirely

**Comment by OmgImAlexis** [comment]
Alright, sounds good.
