### ISSUE TITLE
How can i initiate postprocess from curl?

### ISSUE THREAD

**Issue by SickrageDK** [SiCKRAGETV/sickrage-issues#2550]
Hi,

How can i initiate an automate postprocessing by using curl?
I expect there is some api key for this, but cant figure out the URL.

**Comment by miigotu** [comment]
`http://ip:port/api/your_api_key/?cmd=postprocess&force_replace=1&is_priority=1&path=/path/to/process`

More info:
`http://ipl:port/api/your_api_key/?cmd=help&subject=postprocess`

**Comment by WebSpider** [comment]
@clinton-hall fyi ... Postprocessing is now also in API!

**Comment by miigotu** [comment]
@WebSpider always has I think, or at least for a very long time. but it is missing from apibuilder, and also the comment is outdated in source.

**Comment by clinton-hall** [comment]
So the api takes all parameters that the postprosess call takes... failed, dir, force, process_method, delete_on.
Last time I looked I didn't think all options could be passed.

**Comment by miigotu** [comment]
@clinton-hall The comment in the source is incomplete. I think only failed was missing some time ago and was added.

**Comment by clinton-hall** [comment]
Thanks,

I'll look to add api for SickRage to nzbToMedia

**Comment by SickrageDK** [comment]
Thanks for the help :)

**Comment by miigotu** [comment]
Added that "help" text for failed param, not sure how accurate that description really is... got it from webUI
https://github.com/SiCKRAGETV/SickRage/commit/5cf18bef8cb1719d99ad4269db924f0bea785904
