### ISSUE TITLE
Vimeo Network Icon Missing

### ISSUE THREAD

**Issue by play3rZA** [SiCKRAGETV/sickrage-issues#2553]
Hi guys,

I saw something a couple of days ago about a rework of the network logos, but couldn't find it now... *Found it (Decide about "Overhaul the network logos system" PR 1408) 
In any case, it seems as if the icon for Vimeo is missing. Not that it's really a network, but something is set to air on it..

![image](https://cloud.githubusercontent.com/assets/13823183/9451658/3d347d2a-4ab0-11e5-85a4-ea771051f67b.png)

**Comment by neoatomic** [comment]
@play3rZA Should be added with the next update.
