### ISSUE TITLE
'multiResult' season pack error

### ISSUE THREAD

**Issue by demitrix** [SiCKRAGETV/sickrage-issues#2554]
When trying to seach for a season pack the following error occurs.

AA
AAUnboundLocalError: local variable 'multiResult' referenced before assignment
AA    logger.log(u"Seeing if we want to bother with multi-episode result " + multiResult.name, logger.DEBUG)
AA  File "C:\SickRage\sickbeard\search.py", line 596, in searchProviders
AA    searchResult = search.searchProviders(self.show, self.segment, False)
AA  File "C:\SickRage\sickbeard\search_queue.py", line 222, in run

**Comment by demitrix** [comment]
Line 596 of search.py has a missing _ is should read

 logger.log(u"Seeing if we want to bother with multi-episode result " + _multiResult.name, logger.DEBUG)

instead of

 logger.log(u"Seeing if we want to bother with multi-episode result " + multiResult.name, logger.DEBUG)

**Comment by miigotu** [comment]
Typo, will fix when I get home from work.
