### ISSUE TITLE
[Feature request] When use "Download proper", continue to seed original download

### ISSUE THREAD

**Issue by thenamelessthing** [SiCKRAGETV/sickrage-issues#2560]
It will be better if we can continue to seed torrent when a proper version is detected and downloaded (at least until minimum ratio was reached) Actually I must download torrent again to remove the hit&run warning I obtain because of this...

**Comment by miigotu** [comment]
@thenamelessthing I think you just need to configure SR better. If you use hard links it should unlink the link in the library and link the proper, so then you still have the original and the proper in the completed downloads.

does it not work this way? because it should.

**Comment by thenamelessthing** [comment]
Actually I was use "copy" mode. I change it to "hardlink". I will confirm you if it's okay.

**Comment by miigotu** [comment]
@thenamelessthing with copy mode it most definitely does not delete anything in the completed downloads directory, regardless of how many new versions of an episode you download.
