### ISSUE TITLE
Archive not seeing "best" on all snatched files

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2562]
SR seems to only see 1080p WEB-DL as "best" sometimes instead of all of the time meaning it'll only sometimes get archived, I'm not sure if this may be because some of the episodes were snatched before the last patch but it may be the reason it's showing up like this.

![screen shot 2015-08-26 at 4 50 58 pm](https://cloud.githubusercontent.com/assets/6525926/9487711/7000d096-4c13-11e5-8586-87737e4c67b8.png)

**Comment by WebSpider** [comment]
The episode state is not constantly updated, only when processing a new event for that episode.

This would be due to the fact that you had previous episodes before the patch, the way I see it.

-----Original Message-----

**Comment by OmgImAlexis** [comment]
@WebSpider is there anyway to see when episode 9 was snatched currently?

**Comment by WebSpider** [comment]
Check the history tab

-----Original Message-----

**Comment by OmgImAlexis** [comment]
It gets wiped when you update and I've updated 5 or so times in the last few days because of patches miigotu and I have been working on.

**Comment by OmgImAlexis** [comment]
Okay, just confirmed this. @miigotu any ideas?

![screen shot 2015-08-28 at 7 50 23 pm](https://cloud.githubusercontent.com/assets/6525926/9544264/3f486fb6-4dbe-11e5-9a25-dfe593620474.png)

**Comment by OmgImAlexis** [comment]
Here's the process page, https://gist.github.com/OmgImAlexis/56ee69803e083fe9f80a.

**Comment by fernandog** [comment]
@OmgImAlexis still an issue?

**Comment by OmgImAlexis** [comment]
Seems to be fixed from what I've seen.
