### ISSUE TITLE
[Feature Request] setup.py and proper invocation

### ISSUE THREAD

**Issue by WebSpider** [SiCKRAGETV/sickrage-issues#2563]
From the closing comments of  SiCKRAGETV/SickRage#2350

 "try and find a way to move the majority of SickBeard.py into the module to it is properly distributable...

Will need to write a proper setup.py sometime maybe xD."

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
