### ISSUE TITLE
[APP SUBMITTED]: failedDownloads() got an unexpected keyword argument '24_720p_WEB_DL_DD5_1_H264_NFHD|Criminal_Minds_S08E01_720p_HDTV_X264_DIMENSION|Criminal_Minds_S08E01_720p_WEB_DL_DD5_1_H_264_NFHD|Criminal_Minds_S08E02_720p_HDTV_X264_DIMENSION|Criminal_Minds_S08E06_720p_HDTV_X264_DIMENSION|Criminal_Minds_S08E08_720p_HDTV_X264_DIMENSION|Criminal_Minds_S08E14_720p_HDTV_X264_DIMENSION|Criminal_Minds_S09E14_720p_WEB_DL_DD5_1_H_264_CtrlHD|Criminal_Minds_S09E15_720p_WEB'

### ISSUE THREAD

**Issue by joakim93** [SiCKRAGETV/sickrage-issues#2564]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@3fb81bd65d7710e59d6c89945a3be39d2dbfc386
Link to Log: https://gist.github.com/02262df38dbfa7a9352a
### ERROR
```
Thread-46 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 260, in async_call
    result = function(**kwargs)
TypeError: failedDownloads() got an unexpected keyword argument '24_720p_WEB_DL_DD5_1_H264_NFHD|Criminal_Minds_S08E01_720p_HDTV_X264_DIMENSION|Criminal_Minds_S08E01_720p_WEB_DL_DD5_1_H_264_NFHD|Criminal_Minds_S08E02_720p_HDTV_X264_DIMENSION|Criminal_Minds_S08E06_720p_HDTV_X264_DIMENSION|Criminal_Minds_S08E08_720p_HDTV_X264_DIMENSION|Criminal_Minds_S08E14_720p_HDTV_X264_DIMENSION|Criminal_Minds_S09E14_720p_WEB_DL_DD5_1_H_264_CtrlHD|Criminal_Minds_S09E15_720p_WEB'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by joakim93** [comment]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@3fb81bd65d7710e59d6c89945a3be39d2dbfc386
Link to Log: https://gist.github.com/373158d480e6b8446629
### ERROR
```
Thread-44 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 260, in async_call
    result = function(**kwargs)
TypeError: failedDownloads() got an unexpected keyword argument '24_720p_WEB_DL_DD5_1_H264_NFHD|Criminal_Minds_S08E01_720p_HDTV_X264_DIMENSION|Criminal_Minds_S08E01_720p_WEB_DL_DD5_1_H_264_NFHD|Criminal_Minds_S08E02_720p_HDTV_X264_DIMENSION|Criminal_Minds_S08E06_720p_HDTV_X264_DIMENSION|Criminal_Minds_S08E08_720p_HDTV_X264_DIMENSION|Criminal_Minds_S08E14_720p_HDTV_X264_DIMENSION|Criminal_Minds_S09E14_720p_WEB_DL_DD5_1_H_264_CtrlHD|Criminal_Minds_S09E15_720p_WEB'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by joakim93** [comment]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@3fb81bd65d7710e59d6c89945a3be39d2dbfc386
No Log available with ERRORS: 
### ERROR
```
Thread-44 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 260, in async_call
    result = function(**kwargs)
TypeError: failedDownloads() got an unexpected keyword argument '24_720p_WEB_DL_DD5_1_H264_NFHD|Criminal_Minds_S08E01_720p_HDTV_X264_DIMENSION|Criminal_Minds_S08E01_720p_WEB_DL_DD5_1_H_264_NFHD|Criminal_Minds_S08E02_720p_HDTV_X264_DIMENSION|Criminal_Minds_S08E06_720p_HDTV_X264_DIMENSION|Criminal_Minds_S08E08_720p_HDTV_X264_DIMENSION|Criminal_Minds_S08E14_720p_HDTV_X264_DIMENSION|Criminal_Minds_S09E14_720p_WEB_DL_DD5_1_H_264_CtrlHD|Criminal_Minds_S09E15_720p_WEB'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by joakim93** [comment]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@3fb81bd65d7710e59d6c89945a3be39d2dbfc386
Link to Log: https://gist.github.com/cf198c0b9e57239f583f
### ERROR
```
Thread-16 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 260, in async_call
    result = function(**kwargs)
TypeError: failedDownloads() got an unexpected keyword argument '24_720p_WEB_DL_DD5_1_H264_NFHD|Criminal_Minds_S08E01_720p_HDTV_X264_DIMENSION|Criminal_Minds_S08E01_720p_WEB_DL_DD5_1_H_264_NFHD|Criminal_Minds_S08E02_720p_HDTV_X264_DIMENSION|Criminal_Minds_S08E06_720p_HDTV_X264_DIMENSION|Criminal_Minds_S08E08_720p_HDTV_X264_DIMENSION|Criminal_Minds_S08E14_720p_HDTV_X264_DIMENSION|Criminal_Minds_S09E14_720p_WEB_DL_DD5_1_H_264_CtrlHD|Criminal_Minds_S09E15_720p_WEB'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by joakim93** [comment]
2015-08-27 03:07:12 DEBUG    TORNADO :: Failed doing webui request "failedDownloads": Traceback (most recent call last):
AATypeError: failedDownloads() got an unexpected keyword argument '24_720p_WEB_DL_DD5_1_H264_NFHD|Criminal_Minds_S08E02_720p_HDTV_X264_DIMENSION|Criminal_Minds_S08E14_720p_HDTV_X264_DIMENSION|Criminal_Minds_S09E14_720p_WEB_DL_DD5_1_H_264_CtrlHD|Criminal_Minds_S09E15_720p_WEB_DL_DD5_1_H_264_CtrlHD|Criminal_Minds_S09E16_720p_WEB_DL_DD5_1_H_264_CtrlHD|Criminal_Minds_S09E17_720p_WEB_DL_DD5_1_H_264_CtrlHD|Criminal_Minds_S09E19_720p_WEB_DL_DD5_1_H_264_CtrlHD|Criminal_M'
AA    result = function(**kwargs)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 260, in async_call
AATraceback (most recent call last):
AATypeError: failedDownloads() got an unexpected keyword argument '24_720p_WEB_DL_DD5_1_H264_NFHD|Criminal_Minds_S08E02_720p_HDTV_X264_DIMENSION|Criminal_Minds_S08E14_720p_HDTV_X264_DIMENSION|Criminal_Minds_S09E14_720p_WEB_DL_DD5_1_H_264_CtrlHD|Criminal_Minds_S09E15_720p_WEB_DL_DD5_1_H_264_CtrlHD|Criminal_Minds_S09E16_720p_WEB_DL_DD5_1_H_264_CtrlHD|Criminal_Minds_S09E17_720p_WEB_DL_DD5_1_H_264_CtrlHD|Criminal_Minds_S09E19_720p_WEB_DL_DD5_1_H_264_CtrlHD|Criminal_M'
AA    result = function(**kwargs)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 260, in async_call
2015-08-27 03:07:12 ERROR    Thread-39 :: Failed doing webui callback: Traceback (most recent call last):

Thats what it says in debug log. I tried to delete the failed downloads list.

**Comment by neoatomic** [comment]
Well that would be my next suggestion to remove the failed.db file. Maybe it got corrupted.
You can find that file in your SickRage folder.

**Comment by joakim93** [comment]
yeah that did the trick thanks
