### ISSUE TITLE
Scream show not being processed

### ISSUE THREAD

**Issue by andreofgyn** [SiCKRAGETV/sickrage-issues#2565]
The Scream show is not being detected, since it has been named by everyone as SCREAM THE TV SERIES. Sickrage doesn't find or post process the episodes named like SCREAM.THE.TV.SERIES.SXXEXX.HDTV.X264-XXX.

Maybe the "the tv series" part before the episode number can be ignored for every show.

**Comment by WebSpider** [comment]
Probably should be added to scene exceptions.

**Comment by andreofgyn** [comment]
@WebSpider yeah, adding ""scream.the.tv.series" to the exceptions list did the trick, thanks.
