### ISSUE TITLE
TorrentLeech login error

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2568]
i am getting this error when searching on torrent leech
Im not sure what is the problem but can be related with my password ,it has the letter ç in it
```
2015-08-26 22:49:39 DEBUG    SEARCHQUEUE-MANUAL-290312 :: [TorrentLeech] :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
AA
AATypeError: __str__ returned non-string (type SysCallError)
AA    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
AA  File "/home/super******/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
AA    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
AA  File "/home/super******/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
AA    body=body, headers=headers)
AA  File "/home/super******/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
AA    timeout=timeout
AA  File "/home/super******/SickRage/lib/requests/adapters.py", line 370, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/home/super******/SickRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/home/super******/SickRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('POST', url, data=data, json=json, **kwargs)
AA  File "/home/super******/SickRage/lib/requests/sessions.py", line 507, in post
AA    response = self.session.post(self.urls['login'], data=login_params, timeout=30)
AA  File "/home/super******/SickRage/sickbeard/providers/torrentleech.py", line 95, in _doLogin
AA    if not self._doLogin():
AA  File "/home/super******/SickRage/sickbeard/providers/torrentleech.py", line 161, in _doSearch
AA    itemList += self._doSearch(curString, search_mode, len(episodes), epObj=epObj)
AA  File "/home/super******/SickRage/sickbeard/providers/generic.py", line 351, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/home/super******/SickRage/sickbeard/search.py", line 463, in searchProviders
2015-08-26 22:49:39 DEBUG    SEARCHQUEUE-MANUAL-290312 :: [TorrentLeech] :: Traceback (most recent call last):
AATypeError: __str__ returned non-string (type SysCallError)
AA    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
AA  File "/home/super******/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
AA    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
AA  File "/home/super******/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
AA    body=body, headers=headers)
AA  File "/home/super******/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
AA    timeout=timeout
AA  File "/home/super******/SickRage/lib/requests/adapters.py", line 370, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/home/super******/SickRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/home/super******/SickRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('POST', url, data=data, json=json, **kwargs)
AA  File "/home/super******/SickRage/lib/requests/sessions.py", line 507, in post
AA    response = self.session.post(self.urls['login'], data=login_params, timeout=30)
AA  File "/home/super******/SickRage/sickbeard/providers/torrentleech.py", line 95, in _doLogin
AA    if not self._doLogin():
AA  File "/home/super******/SickRage/sickbeard/providers/torrentleech.py", line 161, in _doSearch
AA    itemList += self._doSearch(curString, search_mode, len(episodes), epObj=epObj)
AA  File "/home/super******/SickRage/sickbeard/providers/generic.py", line 351, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/home/super******/SickRage/sickbeard/search.py", line 463, in searchProviders
AATraceback (most recent call last):
2015-08-26 22:49:37 ERROR    SEARCHQUEUE-MANUAL-290312 :: [TorrentLeech] :: Error while searching TorrentLeech, skipping: __str__ returned non-string (type SysCallError)
2015-08-26 22:49:21 DEBUG    SEARCHQUEUE-MANUAL-290312 :: [TorrentLeech] :: search_strings = [{'Episode': [u'How.We.Got.Here S01E12 ']}]
2015-08-26 22:49:21 INFO     SEARCHQUEUE-MANUAL-290312 :: [TorrentLeech] :: Performing episode search for How We Got Here
```

**Comment by WebSpider** [comment]
Torrentleech seems to be timing out on the webrequest.
Are you able to perform manual searches using the site's website?

**Comment by duramato** [comment]
@WebSpider yes i am

**Comment by duramato** [comment]
@WebSpider not it isnt giving that error anymore just ```2015-08-27 19:38:39 ERROR    SEARCHQUEUE-MANUAL-290312 :: [TorrentLeech] :: Invalid username or password for TorrentLeech Check your settings
2015-08-27 19:38:39 DEBUG    SEARCHQUEUE-MANUAL-290312 :: [TorrentLeech] :: search_strings = [{'Episode': [u'How.We.Got.Here S01E09 ']}]
2015-08-27 19:38:39 INFO     SEARCHQUEUE-MANUAL-290312 :: [TorrentLeech] :: Performing episode search for How We Got Here```

**Comment by WebSpider** [comment]
I'm not seeing weirdness in the code, and don't have a tl account to troubleshoot.

@miigotu do you have an account there?

**Comment by miigotu** [comment]
@WebSpider nope, i have 4 private trackers, and they are a hell of a lot of work just keeping the accounts open because I dont use them lol. I just set up a good ratio and never use em xD.

**Comment by duramato** [comment]
@WebSpider & @miigotu they had an open summer invite code util like 6h ago but well...
If you want i can borrow you the login details to one of you in order for you to test

**Comment by neoatomic** [comment]
@duramato Can you change the password to not include the `ç` so we know that isn't the problem.?

**Comment by miigotu** [comment]
@duramato can you check it again with develop please.

**Comment by duramato** [comment]
@miigotu ```
2015-09-07 01:39:55 DEBUG    SEARCHQUEUE-MANUAL-294206 :: [TorrentLeech] :: Traceback (most recent call last):
AAAttributeError: 'NoneType' object has no attribute 'text'
AA    if re.search('Invalid Username/password', response.text) \
AA  File "/home/super******/SickRage/sickbeard/providers/torrentleech.py", line 93, in _doLogin
AA    if not self._doLogin():
AA  File "/home/super******/SickRage/sickbeard/providers/torrentleech.py", line 154, in _doSearch
AA    itemList += self._doSearch(curString, search_mode, len(episodes), epObj=epObj)
AA  File "/home/super******/SickRage/sickbeard/providers/generic.py", line 351, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/home/super******/SickRage/sickbeard/search.py", line 462, in searchProviders
AATraceback (most recent call last):```

**Comment by miigotu** [comment]
I can fix that error, but the login is still failing ^

**Comment by miigotu** [comment]
Actually, update and retry please.

**Comment by miigotu** [comment]
@duramato you alive still? xD

**Comment by duramato** [comment]
yeah @miigotu :P now im getting this http://pastebin.com/XHk4aJav

**Comment by miigotu** [comment]
sigh, lost on it atm. Ill try again another time xD

**Comment by duramato** [comment]
@MGaetan89 that did not fixed it ,at least for me

**Comment by MGaetan89** [comment]
Sorry, it was closed automatically when I updated my SickRage fork...

**Comment by flightlevel** [comment]
@duramato Can you confirm this is fixed with latest version

**Comment by duramato** [comment]
@flightlevel  No it isnt

**Comment by flightlevel** [comment]
@duramato 
Same error as your last one?

**Comment by duramato** [comment]
Yes it just says ```
2015-08-27 19:38:39 ERROR SEARCHQUEUE-MANUAL-290312 :: [TorrentLeech] :: Invalid username or password for TorrentLeech Check your settings```

**Comment by miigotu** [comment]
Its not a SR bug then apparently. If you cant even change your PW on their site because of the special character that proves it is a problem on their end I think.

**Comment by duramato** [comment]
but i believe sr cant handle the special car. too 
isnt this related https://github.com/SiCKRAGETV/sickrage-issues/issues/2745 ?

**Comment by jasonb92** [comment]
torrent leech have advised me it may be something to do with the SR Locale... sick rage is working on my seedbox and the SR Locale is ('en_US', 'UTF-8') however on my NAS where its not working the SR Locale os (None.None) could this be the problem in regards to the special character?

**Comment by WebSpider** [comment]
Yes, it could be very likely.
The locale is determined by the OS however, and we inherit it.

Which NAS do you use?

-----Original Message-----

**Comment by jasonb92** [comment]
I have a QNAP I can't seem to work out how to check it

**Comment by WebSpider** [comment]
Google tells me this:  http://forum.qnap.com/viewtopic.php?t=1304

Closing this issue now, as the bug is in the python settings, not in SR

**Comment by duramato** [comment]
@WebSpider why closing? @jasonb92 issue isnt related to mine furthermore my locale is pt_PT.UTF-8
