### ISSUE TITLE
 implement a feature to allow user to override the built-in url for providers

### ISSUE THREAD

**Issue by MLWALK3R** [SiCKRAGETV/sickrage-issues#2569]
implement a feature to allow user to override the built-in url for providers, as mentioned on the PR https://github.com/SiCKRAGETV/SickRage/pull/2352

**Comment by neoatomic** [comment]
There is already a FR for this. : https://github.com/SiCKRAGETV/sickrage-issues/issues/1381
Please update the issue there if there is anything missing.

**Comment by miigotu** [comment]
Locked to force conversation in #1381 so we dont have to topic jump to keep up, and dont need to update 10 topics when it is fixed.
