### ISSUE TITLE
[APP SUBMITTED]: database disk image is malformed

### ISSUE THREAD

**Issue by aschnabl** [SiCKRAGETV/sickrage-issues#2570]
### INFO
Python Version: **2.7.3 (default, Mar 31 2015, 15:16:49) [GCC 4.9.2]**
Operating System: **Linux-3.18.10-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-79264 :: Error while searching OZNZB, skipping: database disk image is malformed
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@aschnabl Remove/rename the cache folder and cache.db. Then let SR build a fresh one. (force full update)

**Comment by aschnabl** [comment]
Tried that, and no good. Any other suggestions? Only started this week.

**Comment by fernandog** [comment]
@aschnabl if you search you will find the answer

https://github.com/SiCKRAGETV/sickrage-issues/search?q=database+disk+image+is+malformed&type=Issues&utf8=%E2%9C%93
