### ISSUE TITLE
[REQUEST] Reject & Remove Downloads Based on File Types During Post Processing

### ISSUE THREAD

**Issue by ethanmcdonald** [SiCKRAGETV/sickrage-issues#2572]
Often times certain files are not rejected before because the video is encapsulated in a Torrent download.
The details may be not available till the entire Torrent is finished.
Afterwards the result of the Torrent is Post Processed with a file of an unwanted file type, like a WMV.

I would be nice if while a torrent begins Post Processing, that the torrent files could be scanned for unwanted file types.
If the unwanted file type is found then the whole download would be removed and the episode would be set back to wanted.
This action would of coarse blacklist the torrent that originated the bad download to begin with.

BTW, I'm suggesting this as Post Process task, as it my assumption that SickRage is unable to retrieve the entire file contents of Torrents before download.

**Comment by WebSpider** [comment]
We are able to do something here: If we snatch the torrent, we could see if the files associated are unwanted.

If the torrent contains a rar, we are dead in the water however.

Also, if its a magnet, this won't work either.

-----Original Message-----

**Comment by neoatomic** [comment]
@WebSpider I'm skeptical about putting any time in this... 
https://github.com/SiCKRAGETV/sickrage-issues/issues/2566#issuecomment-135361792

**Comment by miigotu** [comment]
@WebSpider wmv goes against scene rules. if it is wmv it must be a very old release, and there is no other release for it.

I've instructed in the past to set a sane number of min seeders, check verified box in provider options, and blacklist consistently fail rls groups.

However, this is such a rare case that OP just needs to understand that SR cannot be 100% perfect for everyone

Spending hours coding something to prevent the download of a file some users (<10%) might not be able to play, which occurs maybe once every 200 downloads is not a good use of resources.

**Comment by WebSpider** [comment]
I replied before my first coffee.

I don't want to support anything which is against scene rules. It opens up the door for a million possible permutation of file naming.
