### ISSUE TITLE
[APP SUBMITTED]: failedDownloads() got an unexpected keyword argument '24_720p_WEB_DL_DD5_1_H264_NFHD|The_Big_Bang_Theory_S07E16_720p_bluray_x264_demand|The_Big_Bang_Theory_S07E09_720p_bluray_x264_demand|The_Big_Bang_Theory_S07E18_720p_bluray_x264_demand|Elementary_S03E24_1080p_HDTV_X264_DIMENSION|The_Big_Bang_Theory_S07E23_720p_bluray_x264_demand'

### ISSUE THREAD

**Issue by joakim93** [SiCKRAGETV/sickrage-issues#2574]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@3fb81bd65d7710e59d6c89945a3be39d2dbfc386
No Log available with ERRORS: 
### ERROR
```
Thread-38 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 260, in async_call
    result = function(**kwargs)
TypeError: failedDownloads() got an unexpected keyword argument '24_720p_WEB_DL_DD5_1_H264_NFHD|The_Big_Bang_Theory_S07E16_720p_bluray_x264_demand|The_Big_Bang_Theory_S07E09_720p_bluray_x264_demand|The_Big_Bang_Theory_S07E18_720p_bluray_x264_demand|Elementary_S03E24_1080p_HDTV_X264_DIMENSION|The_Big_Bang_Theory_S07E23_720p_bluray_x264_demand'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@joakim93 We need logs, without them we cant do anything...
Also can you give some information what you where doing when you got he error.?

**Comment by neoatomic** [comment]
Same as https://github.com/SiCKRAGETV/sickrage-issues/issues/2564
Please provide the info there so we have all in 1 place.
