### ISSUE TITLE
[APP SUBMITTED]: [Errno 36] File name too long: "/media/USBDisk/shares/completed/serietv/I Griffin/Season 07/I Griffin - S07E01E02E03E04E05E06E07E08E09E10E11E12E13E14E15E16 - Essere galancani non paga & Il disco perduto & La macchina del tempo & Aiuto, ho dimenticato Stewie! & Il nuovo Brian & Ritorno sui banchi & I soliti idioti & L'esperimento & Peter si \xc3\xa8 fatto un nuovo amico & Lois, giornalista d'assalto & Not All Dogs Go to Heaven & 420 & Oggi spopolo, domani chiss\xc3\xa0 & Brian innamorato & Sulle tracce del passato & Fondatore di Quahog.avi"

### ISSUE THREAD

**Issue by blast1987** [SiCKRAGETV/sickrage-issues#2575]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-4.1.6-v7+-armv7l-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@3fb81bd65d7710e59d6c89945a3be39d2dbfc386
Link to Log: https://gist.github.com/7509e70e6afa3a2f5de2
### ERROR
```
POSTPROCESSER :: Unable to move file /media/USBDisk/shares/completed/serietvNotTagged/I Griffin S07e01-16/10 - Lois, giornalista d'assalto.avi to /media/USBDisk/shares/completed/serietv/I Griffin/Season 07/I Griffin - S07E01E02E03E04E05E06E07E08E09E10E11E12E13E14E15E16 - Essere galancani non paga & Il disco perduto & La macchina del tempo & Aiuto, ho dimenticato Stewie! & Il nuovo Brian & Ritorno sui banchi & I soliti idioti & L'esperimento & Peter si è fatto un nuovo amico & Lois, giornalista d'assalto & Not All Dogs Go to Heaven & 420 & Oggi spopolo, domani chissà & Brian innamorato & Sulle tracce del passato & Fondatore di Quahog.avi: error 36 : File name too long
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by blast1987** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-4.1.6-v7+-armv7l-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@3fb81bd65d7710e59d6c89945a3be39d2dbfc386
Link to Log: https://gist.github.com/612aa307ebe23a0f887e
### ERROR
```
Thread-20 :: Unable to move file /media/USBDisk/shares/completed/serietvNotTagged/I Griffin S07e01-16/10 - Lois, giornalista d'assalto.avi to /media/USBDisk/shares/completed/serietv/I Griffin/Season 07/I Griffin - S07E01E02E03E04E05E06E07E08E09E10E11E12E13E14E15E16 - Essere galancani non paga & Il disco perduto & La macchina del tempo & Aiuto, ho dimenticato Stewie! & Il nuovo Brian & Ritorno sui banchi & I soliti idioti & L'esperimento & Peter si è fatto un nuovo amico & Lois, giornalista d'assalto & Not All Dogs Go to Heaven & 420 & Oggi spopolo, domani chissà & Brian innamorato & Sulle tracce del passato & Fondatore di Quahog.avi: error 36 : File name too long
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@blast1987 Read the log : 
```
[Errno 36] File name too long <<<<<<
I Griffin - S07E01E02E03E04E05E06E07E08E09E10E11E12E13E14E15E16 - Essere galancani non paga & Il disco perduto & La macchina del tempo & Aiuto, ho dimenticato Stewie! & Il nuovo Brian & Ritorno sui banchi & I soliti idioti & L'esperimento & Peter si \xc3\xa8 fatto un nuovo amico & Lois, giornalista d'assalto & Not All Dogs Go to Heaven & 420 & Oggi spopolo, domani chiss\xc3\xa0 & Brian innamorato & Sulle tracce del passato & Fondatore di Quahog.avi"
```
And also no valid episode name.

**Comment by blast1987** [comment]
The episode downloaded has the correct name, the problem is during post processing, does sickrage find wrong episode name (from theTVDB for example) and try to set this long wrong name? Is there a way to fix this?

**Comment by neoatomic** [comment]
@blast1987 Its the naming of the file that is bad. The e01-16 normally indicates a multi episode, and that is what SR detects correctly. Problem lies here with the unloader that is not following proper naming for his file...

`I Griffin S07e01-16/14` to `I Griffin - S07E01E02E03E04E05E06E07E08E09E10E11E12E13E14E15E16 `

If you putt a space between the 1 and - than it should be detected correctly. (or remove the -16/14 completely)
