### ISSUE TITLE
HDTV download

### ISSUE THREAD

**Issue by ezar** [SiCKRAGETV/sickrage-issues#2576]
I configure this for use HD profile.

But ignore results like this:
2015-08-27 10:09:00 INFO SEARCHQUEUE-MANUAL-255316 :: [Rarbg] :: Ignoring result Elementary.S03E18.720p.HDTV.X264-DIMENSION[rartv] because we don't want an episode that is HDTV

Why dont download this torrent?

Regards.

**Comment by neoatomic** [comment]
Follow the guidelines for posting an issue.
https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket

**Comment by miigotu** [comment]
@ezar there are a few reasons. Likely this case is because it is already snatched at a same or higher quality, or the file exists at a same or higher quality.
