### ISSUE TITLE
[Feature Request] Display total show size on shows listing

### ISSUE THREAD

**Issue by MGaetan89** [SiCKRAGETV/sickrage-issues#2578]
Following issue #2498.

Include a new column to display the "Total show size" in the shows listing. This should be configurable in the "Select Column" menu.

**Comment by MGaetan89** [comment]
@WebSpider 
I implemented it on my dev SickRage, and it doesn't seem to slow it down (I only have 2 shows with actual files).
Is there an easy way to measure the time it takes to compute the show size?

**Comment by fernandog** [comment]
Make a PR. Will test it and other can test too

**Comment by MGaetan89** [comment]
I will in a moment.

**Comment by MGaetan89** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/2356
Here is the PR.

**Comment by MGaetan89** [comment]
I didn't noticed there were already an issue for that #2401.
I'm closing this in favorite of the other issue.

**Comment by WebSpider** [comment]
Add basic microsecond timers around the calls, add them up and log it in debug?

-----Original Message-----

**Comment by MGaetan89** [comment]
So simple :p Thanks
