### ISSUE TITLE
Sickrage Snatchs but does not Download 

### ISSUE THREAD

**Issue by fnbf21** [SiCKRAGETV/sickrage-issues#2579]
Hello everyone,

I decided today to install sickrage on my new Debian 7 server. Unfortunately, sickrage is not able to download  any torrent. Each time I search an episode, sickrage is able to snatch it, but after that the download won't start.

In the log file I obtain : 2015-08-27 22:47:45 INFO     SEARCHQUEUE-MANUAL-80379 :: [ThePirateBay] :: Saved result to /home/xxxxx/Torrent/xxxxx.720p.HDTV.x264.AAC.torrent

Did I miss something ? 

Thank for your help, and ask me if you need any information.

**Comment by MGaetan89** [comment]
Is your torrent software configured to automatically download torrent files in `/home/xxxxx/Torrent/`? SickRage does not download any episode itself. It only gets the torrent files, so third-party software can get the episode. SickRage can then organize the downloaded episode according to your settings.

**Comment by WebSpider** [comment]
You have your torrent client set to black hole, which is expected behavior. Either tell SR how to integrate with your torrent client, or set your torrent client up for black hole pickup.

-----Original Message-----

**Comment by fnbf21** [comment]
Hi, I found the error, for some reason Transmission was not able to start. I removed it and install it again, and everything is fine.

Thanks ;)
