### ISSUE TITLE
Bots to validate issues/PRs

### ISSUE THREAD

**Issue by MGaetan89** [SiCKRAGETV/sickrage-issues#2580]
To help manage issues and PRs, we could use bots that run automatically on each new issue/comment and new PRs.

For issue:
- [x] Check that log are provided ([original comment](https://github.com/SiCKRAGETV/sickrage-issues/issues/885#issuecomment-87432970)) -> comment to request logs

For PR:
- [x] Check that the destination branch is not `master` ([original comment](https://github.com/SiCKRAGETV/sickrage-issues/issues/885#issuecomment-135552421)) -> close PR and comment to explain why
- [ ] Mark new PRs as "DO NOT MERGE"

**Comment by OmgImAlexis** [comment]
Also automark as [DO NOT MERGE] for PR that're on any branch apart from Master.

**Comment by miigotu** [comment]
I've wanted to do this forever, but only owners can configure that.

@fernandog

**Comment by WebSpider** [comment]
I just forked CouchPotatoBot for this, and can run it on one of my boxes once properly adjusted.

**Comment by miigotu** [comment]
@WebSpider the bot is run on github itself afaik, and can only be added/run by an owner of the org.

**Comment by WebSpider** [comment]
Actually, the way CP implemented it, it's callbacks and event handlers to nodejs. You have to setup the event handling as repo owner, that's true.

**Comment by miigotu** [comment]
@fernandog we need you to do that....

**Comment by fernandog** [comment]
what exactly I need to do ?

**Comment by miigotu** [comment]
It depends on how we want to implement the bot.  If it is a github built-in service it is easier. If it is couchpotatoBot it needs a webhook enabled sending payload to the bot, and the bot has to have an account with privileges. Moderator if it is only managing issues, or Admin if it is also managing PR.

https://github.com/SiCKRAGETV/SickRage/settings/hooks

**Comment by WebSpider** [comment]
@miigotu what service is a GitHub standard bot? I've looked but couldn't find any, so I forked cpbot.

-----Original Message-----

**Comment by miigotu** [comment]
@WebSpider I haven't gone through the list completely, but surely there must be at least one wouldn't you think?

**Comment by WebSpider** [comment]
I've set up a bot that can be used to do this. 
Check out WebSpider/SickRageBot#5 for some examples.

We basically need to fix a few more things to get this running:

- [ ] Set up an account for the bot to run under: Done -> SiCKRAGEB0T
- [ ] Set up proper permissions for this account: Not needed yet, labels are future music
- [ ] Set up the webhook per repository
- [ ] Run the bot: Done, it can run on a VPS of @WebSpider
- [ ] Change bot messages: Just PR the bot repo :+1:

**Comment by fernandog** [comment]
@WebSpider 

what should I input here:

![image](https://cloud.githubusercontent.com/assets/2620870/10122926/7ba86b84-64ff-11e5-8cb1-ca180b15c131.png)

**Comment by fernandog** [comment]
webhoot created

**Comment by OmgImAlexis** [comment]
Is it possible for the bot to check the user before commenting so for "approved" users we don't get comments when we don't need them, this would apply for anyone on the sickrage teams as we put in PRs upto 2 - 5 times a day and don't really need to meet the bots expectations each time we submit a PR.

**Comment by WebSpider** [comment]
@OmgImAlexis I need to look for the GitHub calls to make in node.js, but if its in the API, it should be possible

**Comment by WebSpider** [comment]
Also, I need to find out how to make it respond to more than one repo, lol

**Comment by WebSpider** [comment]
For the bot to be able to use labels and close issues, it needs more permissions.

**Comment by fernandog** [comment]
Whats the user of bot? Will add as moderator

**Comment by fernandog** [comment]
@WebSpider try now. moderator for sickrage-issues and admin for SickRage

**Comment by miigotu** [comment]
@fernandog Please fork https://github.com/WebSpider/SickRageBot into SiCKRAGETV. If users know where it is they are more likely to PR to it, and there is no better place to get noticed than right in the Org.

@WebSpider after that could you change the server to clone from there?

@OmgImAlexis the bot is in node, you probably can do all kinds of fun stuff with that.

**Comment by WebSpider** [comment]
Yeah Sure, 

-----Original Message-----

**Comment by fernandog** [comment]
Forkek

**Comment by WebSpider** [comment]
I will be setting up the bot to auto-checkout master and restart when needed, initially at an interval of 4h.

-----Original Message-----

**Comment by miigotu** [comment]
@WebSpider I think once it can follow multiple repos, it should follow it's own repo.

AKA: His own repo gets a webhook for push/merge, he comments on the PR and says something like "Thanks for proposing an update to my logic, I will update automatically if this is merged", and then comments on the PR again when it is merged and says "Loading... Loading... Loading..." and then git pulls and restarts, and comments something like `root@SiCKRAGEB0T:~#`

LOL

**Comment by OmgImAlexis** [comment]
`Please make sure use gist for the logs or put them in a https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting.`

Something like that needs to be added to it. I'll have a look through the code tomorrow and see if I can change a few things.

**Comment by OmgImAlexis** [comment]
@WebSpider why was this closed since we're using this for discussion about @SiCKRAGEB0T?

**Comment by WebSpider** [comment]
I was under the impression this issue was about getting such a bot, which was done, and therefore I closed the issue.

If you want to keep it open, fine by me :)

**Comment by OmgImAlexis** [comment]
Yeah I'd like this to be used for all discussions about it so everyone's up to date about what's going on. :+1:

**Comment by miigotu** [comment]
Doesnt mean we need to keep it open. All team members get a notification about any comments here anyways. We are working to get a 0 count of open issues, there is no reason to keep discussions open.
