### ISSUE TITLE
[APP SUBMITTED]: 'C__SickRage_gui_slick_interfaces_default_home_mako'

### ISSUE THREAD

**Issue by johnscrub** [SiCKRAGETV/sickrage-issues#2581]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@3fb81bd65d7710e59d6c89945a3be39d2dbfc386
Link to Log: https://gist.github.com/53228def9980acff7b95
### ERROR
```
Thread-44 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 260, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 739, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 109, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 380, in _compile_from_file
    del sys.modules[self.module_id]
KeyError: 'C__SickRage_gui_slick_interfaces_default_home_mako'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by flightlevel** [comment]
Have you tried clearing your cache? eg. https://github.com/SiCKRAGETV/sickrage-issues/issues/2507

**Comment by johnscrub** [comment]
I am sorry did not see this was an reported issue and solved.I personally have not tried this and cannot say it works..is there a way to see reported errors or a link you can send me to check them??I dont want to cause anymore  work for you guys/girls than  i need to..thanks again for your time!!Date: Thu, 27 Aug 2015 17:15:44 -0700

**Comment by WebSpider** [comment]
Just enter keywords of your error in the sickrage-issues repository search field. That way you search through all open and closed issues.
