### ISSUE TITLE
[Feature Request] Sort homepage before rendering

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2582]
If we sort the homepage using python then we can render the table instantly on page load instead of waiting for jQuery, if the user wants to change the layout it'd be done with jQuery and saved like normal.

**Comment by miigotu** [comment]
@OmgImAlexis should be fairly easy.

**Comment by miigotu** [comment]
If I sort the list before rendering home.mako, can you handle the jquery part @OmgImAlexis?

That's probably the fastest way to make thus happen, as I would probably have a trial and error session with the js...

**Comment by OmgImAlexis** [comment]
Yep, sounds good. I'm still waiting for the PR (https://github.com/SiCKRAGETV/SickRage/pull/2336) that @MGaetan89 is doing though, not sure if he's going to touch the js after all of the CSS or not.

**Comment by MGaetan89** [comment]
I'm mostly working on the CSS part for the moment, and maybe on the images afterwards.
I'm not sure how much I can do about JS yet. One start would be to put all the JS out of the `mako`s file and inside a `js` file, so the browser can load them separately.

**Comment by OmgImAlexis** [comment]
Alright, I'll take a look at all of the js then. Starting on the homepage I should be able to get most of the js to js files and just use the SR api to check if things need to be run instead of using python if statments and inline js. Have a look at [this](https://github.com/SiCKRAGETV/sickrage-issues/issues/2584) for progress on it.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
