### ISSUE TITLE
[Feature Request] Replace the inline progressbar functions with a single jQuery function and call it on pageload

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2584]
For example on the homepage this is added for EVERY show, when you've got 100 or so shows like I do then it's 100 x 22 lines instead of a single function.

````
$(function() {
    $("#progressbar269593").progressbar({ value: 74 });
    $("#progressbar269593").append( "<div class='progressbarText' title='Downloaded: 20&#013;Snatched: 7&#013;Total: 27'>20+7 / 27</div>" )
    classvalue = 74
    if (classvalue<20) {
        classtoadd = "progress-20"
    }
    if (classvalue>=20 && classvalue<40) {
        classtoadd = "progress-40"
    }
    if (classvalue>=40 && classvalue<80) {
        classtoadd = "progress-60"
    }
    if (classvalue>=80 && classvalue<100) {
        classtoadd = "progress-80"
    }
    if (classvalue==100) {
        classtoadd = "progress-100"
    }
    $("#progressbar269593 > .ui-progressbar-value").addClass(classtoadd);
});
````

**Comment by OmgImAlexis** [comment]
I'm working on this but I don't have permission to assign this to me.

**Comment by MGaetan89** [comment]
:+1: Maybe check if it is used elsewhere to use the same function everywhere.

I assigned this to you ;)

**Comment by OmgImAlexis** [comment]
This looks like it'll work, just need to make changes to the mako files.

````
$('.progressbar').each(function(progressbar){
    var showId = $(this).data('show-id');
    var percentage = $(this).data('progress-percentage');
    var text = '<div class="progressbarText" title="' + $(this).data('progress-tip') + '">' + $(this).data('progress-text') + '</div>';
    var classToAdd = percentage > 80 ? 100 : percentage > 40 ? 60 : percentage > 20 ? 40 : 20;
    $(this).progressbar({ value:  percentage });
    $(this).append(text);
    $(this).find('.ui-progressbar-value').addClass('progress-' + classToAdd);
});
````

**Comment by MGaetan89** [comment]
You forget the case `progress-80`.
Try using a variable instead of calling `$(this)`. It will reduce jQuery's work. As you said, 100 shows call this function, which uses `$(this)` 7 times.

A small improvement compared to the current behaviour, why not use [Bootstrap tooltip](http://getbootstrap.com/javascript/#tooltips) instead of the default one?

**Comment by OmgImAlexis** [comment]
`$(this)` and setting a var in the scope that it's in uses about the same amount of resources and `$(this)` looks cleaner, plus just with this it's reduced the loading time by about another second on my 100+ show install.

I don't want to add anything that uses bootstrap as I've talked to @miigotu and I really want to get away from using it all together as it's not really something that should be used for more than just quick mockups. It'd also help with the whole theming thing we're trying to do.

**Comment by OmgImAlexis** [comment]
Fixed that https://github.com/OmgImAlexis/SickRage/commit/bb49662dc5a7beb9193538a02b05f4fac194bd92

**Comment by WebSpider** [comment]
While we're talking theming, have you guys seen CouchPotato's new theme?

-----Original Message-----

**Comment by OmgImAlexis** [comment]
@WebSpider no? Link?

**Comment by WebSpider** [comment]
Hmm, i will setup a test cp today, so we can have a look.

For now: https://couchpota.to/updates/changelog.html

It looks sleek.

-----Original Message-----

**Comment by OmgImAlexis** [comment]
Oh wow, that does look nice. I'm still ~400 commits behind master as I have to keep editing main.py to add support for YIFY torrents.

**Comment by MGaetan89** [comment]
@OmgImAlexis But `$(this)` will recreate a new jQuery object every time, no ? I understand for Bootstrap ;)

**Comment by OmgImAlexis** [comment]
@MGaetan89 yes but the performance is negligible and for the tiny bit of performance increase it's not worth sacrificing the clean code.

**Comment by OmgImAlexis** [comment]
Just compared this to my production install and it's reduced the pageload by 3,000 lines from ~8,000 to ~5,000.

**Comment by MGaetan89** [comment]
@OmgImAlexis Ok, so I'm fine with your solution :)

**Comment by OmgImAlexis** [comment]
Can this be changed to needs testing or be merged into dev?

**Comment by miigotu** [comment]
@OmgImAlexis I would merge but the branch is not up to date. You need to rebase upstream/develop
