### ISSUE TITLE
Episodes status isn't updating to wanted

### ISSUE THREAD

**Issue by Molleke** [SiCKRAGETV/sickrage-issues#2585]
Lateley in the development branche the status of the episodes stays Unaired on the day it has aired. It should go to the status Wanted but it doesn't anymore. Therefore episodes that are aired don't get searched for. 

![knipsel](https://cloud.githubusercontent.com/assets/12209079/9541097/429b0b5a-4d65-11e5-9507-84e9d9b41ea4.PNG)

![knipsel](https://cloud.githubusercontent.com/assets/12209079/9541133/8078de3e-4d65-11e5-9ec0-0554f43a34d3.PNG)

**Comment by WebSpider** [comment]
What is your default episode status?

**Comment by Molleke** [comment]
Default status is "Wanted".
I checked the status again and now it is changed to "Wanted" by the daily searcher thread. So there is a delay in changing the status. This didn't happen before. So I quess this issue can be closed.
