### ISSUE TITLE
Unable to request authorization for Twitter notifications

### ISSUE THREAD

**Issue by sfgrabowski** [SiCKRAGETV/sickrage-issues#2588]
BRANCH: (master) / COMMIT: (3fb81bd65d7710e59d6c89945a3be39d2dbfc386)
OS: Ubuntu 12.04.5
Python: 2.7.3

Issue: I am unable to activate my twitter account in the SickRage notification settings. It used to work perfectly, but I am now getting the errors in my log that you can see below:

https://gist.github.com/sfgrabowski/6d485b66a177cdeae998

The last successful tweet was sent on 20th August. I've tried multiple browsers, on different OSes, but I either get no page or a new blank tab when selecting the 'Request Authorization' button. I'm wondering if this is a change on twitter's server as Couchpotato doesn't work anymore.

**Comment by WebSpider** [comment]
Can you please include debug log? Current log looks like error log.

**Comment by sfgrabowski** [comment]
I have activated the debug option but I am unable to capture the event in the log file. What should I filter the log by?

**Comment by WebSpider** [comment]
Set minimum log leverl to display to 'DEBUG'.

**Comment by sfgrabowski** [comment]
Apologies but this is the best I could do...

Here is the error log showing a problem with twitter at 2015-08-28 18:32:46:
https://gist.github.com/sfgrabowski/cc0d38be794047bc3128

But this event does not even appear in the debug log:
https://gist.github.com/sfgrabowski/2ea919bcb19395631594

I also seem to be kicking up some other problems looking in the log; could these be related? It was all working fine a week ago.

**Comment by WebSpider** [comment]
Im not seeing any similar issue report in https://github.com/RuudBurger/CouchPotatoServer .. are you sure this is not your local install causing the problem, for instance because you are out of API calls, or your IP has been banned?

Also, I cannot reproduce, I can send tweets just fine?

**Comment by sfgrabowski** [comment]
I didn't think about my IP -- I'm using a VPN so refreshing that seems to have solved the problems. Apologies for the hassle

**Comment by WebSpider** [comment]
Thanks for providing is with feedback, next time we'll start with pointing this issue out to other people reporting the same problem :)
