### ISSUE TITLE
[REQUEST] New Canada Network Logo TV in color

### ISSUE THREAD

**Issue by maxcore** [SiCKRAGETV/sickrage-issues#259]
![radio canada](https://cloud.githubusercontent.com/assets/4043787/5520960/60c10cca-8960-11e4-8f8b-4673eb926e33.png)
![src](https://cloud.githubusercontent.com/assets/4043787/5520962/60c5f08c-8960-11e4-9068-938876f40060.png)
![tele-quebec](https://cloud.githubusercontent.com/assets/4043787/5520961/60c5479a-8960-11e4-928c-9dabee2db2c8.png)
![tva](https://cloud.githubusercontent.com/assets/4043787/5520963/60dce09e-8960-11e4-8b57-157cfa34ad53.png)
![v](https://cloud.githubusercontent.com/assets/4043787/5520964/60dd0664-8960-11e4-9835-74cb02d98329.png)

https://www.dropbox.com/s/64s9nv4a57mdqoe/logo.zip?dl=0

**Comment by markheloking** [comment]
Closing this as it should be fixed with https://github.com/SiCKRAGETV/SickRage/pull/1153.
