### ISSUE TITLE
Displayshow - Episodes from collapsed season not selected when checking "select all" checkbox

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#2592]
IMO it needs to be uncollpased and then check all episodes

![image](https://cloud.githubusercontent.com/assets/2620870/9552007/40cbf41c-4d8b-11e5-9aa7-a4c891014dab.png)

**Comment by MGaetan89** [comment]
The real issue is [this line](https://github.com/SiCKRAGETV/SickRage/blob/master/gui/slick/js/displayShow.js#L50).
It only checks episode that are visible. I will update this as you suggested: display the season, and then check the appropriate episodes.

**Comment by fernandog** [comment]
Thanks!
