### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-75340 :: [Dognzb] :: Unable to parse Prison.Break.S4D6.MULTiSUBS.PAL.DVDR-REWIND into a scene name. If it's a valid one log a bug.

### ISSUE THREAD

**Issue by joakim93** [SiCKRAGETV/sickrage-issues#2593]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@3fb81bd65d7710e59d6c89945a3be39d2dbfc386
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-75340 :: [Dognzb] :: Unable to parse Prison.Break.S4D6.MULTiSUBS.PAL.DVDR-REWIND into a scene name. If it's a valid one log a bug.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Its not a valid scene name.
