### ISSUE TITLE
[Feature Request] 2160p support as quality

### ISSUE THREAD

**Issue by WebSpider** [SiCKRAGETV/sickrage-issues#2595]
Now that the 4k-rip of Breaking Bad S01E01 is out there, we should start adding 4k/2160p as quality.

https://torrentfreak.com/first-netflix-4k-content-leaks-to-torrent-sites-150828/

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!

**Comment by Ashkaan** [comment]
I didn't see it on there, so I added it.

http://feathub.com/SiCKRAGETV/SickRage/+264

Please Vote Up!!
