### ISSUE TITLE
[Feature Request] Coming Episodes: set episodes as skipped/wanted

### ISSUE THREAD

**Issue by benfishbus** [SiCKRAGETV/sickrage-issues#2596]
Would be really handy to have a button or dropdown for changing status of missed/upcoming episodes on the Coming Episodes screen.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
