### ISSUE TITLE
Multi Episode file not correctly assigned to ep

### ISSUE THREAD

**Issue by udochrist** [SiCKRAGETV/sickrage-issues#2597]
![image](https://cloud.githubusercontent.com/assets/869637/9563707/890931d8-4e8d-11e5-9d7a-9515d31b29e7.jpg)

On the rename screen :
The ep file is named S01E01-E03. The ep02 is however not shown in the list.

**Comment by neoatomic** [comment]
The `S01E01-E3` means episode E01, E02, E03. That is why there is no E02 in your list.

**Comment by udochrist** [comment]
That is the precise point why I would expect a ep2 to be shown if e01 an e03 are displayed.

**Comment by udochrist** [comment]
Or better. There should only be one entry for the 1-3 eps and not two

**Comment by neoatomic** [comment]
That is a know issue of the regex, and if i recall right there should be an Feature Request to  improve the recognition of multiple episode files. So its already on the to do list. (but's a long list... :) )
