### ISSUE TITLE
Disallowing certain codecs

### ISSUE THREAD

**Issue by jamesla** [SiCKRAGETV/sickrage-issues#2598]
Hi I downloaded a show using the SD profile however it's grabbing this specific show using the .wmv which my tv doesn't support, is there anyway to blacklist certain file formats?

**Comment by miigotu** [comment]
There is not, what are some of the release names of these files? (the torrent/nzb name not the file name)

**Comment by neoatomic** [comment]
Mostly those are form a bad up-loader/release group. See if you can add that name to the `ignore Words.` Or Enable only downloads form Trusted/Verified up-loaders in the provider settings.

Also checkout the NZBtoMedia scripts for Post Processing, those include a media check during PP.
