### ISSUE TITLE
[Feature Request] Priority should always be the UI / multi-theading

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#26]
<a href="https://github.com/djack42"><img src="https://avatars.githubusercontent.com/u/9913996?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [djack42](https://github.com/djack42)**
_Sunday Nov 30, 2014 at 16:24 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/992 (4 comment(s))_

----

When a user is using the ui, his actions should always be executed in priority before anything background.
Adding a show should be done before a background refresh that could take a hour...
Manually triggering a refresh on a show should be added in front of the queue.
I feel it's not the case and on a big library, this behavior is not user friendly.
this is often frustrating to ask the app specificaly for something and nothing is done right now !

latest revision on develop branch.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
