### ISSUE TITLE
[Feature Request] Considerations for a new theme

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2604]
Since I want to remove all of Bootstrap at some stage I thought we might as well move from the old Bootstrap-esque theme to a newer, cleaner style. I'm all up for ideas on this. Of course we could always just replicate the current theme without Bootstrap but I think if we're going to remove it we might as well give SickRage a new look.

![screen shot 2015-08-31 at 1 21 15 am](https://cloud.githubusercontent.com/assets/6525926/9568080/b8dacee8-4f7e-11e5-8445-030318744726.png)

**Comment by MGaetan89** [comment]
There's already a new theme planned: https://github.com/SiCKRAGETV/SickRage/tree/slicker/gui/slicker
Why not remove Bootstrap from there? And why remove it altogether?

**Comment by WebSpider** [comment]
I'm pretty impressed by the CouchPotato v3 theme. The flick-switches and only icons for the main menu items look good.

-----Original Message-----

**Comment by miigotu** [comment]
The icon only thing is a good direction for international applications, as there is less lost in translation. English and other languages are on the same playing field then and that's a plus

**Comment by OmgImAlexis** [comment]
@MGaetan89 the new theme is soooo different, I was thinking of making this basically the same but just less like Bootstrap and with a sidebar. Also the other theme still hasn't been converted to mako and will take a LONG time to do so as it also needs all of the recent changes we've made on this theme.

@WebSpider that's kind of what I was going for but with the same colours we're already using in SickRage.

@miigotu we could have it like this when you hover over the sidebar but then you're not it'll just show a smaller one with just icons that's like 50px wide or something.

**Comment by neoatomic** [comment]
Think optimizing the Slick theme is the smartest thing to do, before thinking about redoing the theme itself.
Also we have same FR's related to the theme, so it might be a good idea to go through them to see whats possible. (and if not close them)

https://sickrage.tv/forums/forum/help-support/general-support/22882-new-theme-fanart?p=23187#post23187

Here is one of those FR's to make it easier to let users create there own Theme. 
https://github.com/SiCKRAGETV/sickrage-issues/issues/1259
(And maybe investigate if multi-language support is possible for the future.?)

**Comment by OmgImAlexis** [comment]
@neoatomic is that slicker in the forums? https://github.com/SiCKRAGETV/SickRage/pull/2324

I think you're right, we need to discuss how we're going with the theme though as @miigotu and I wanted to change the file structure but he also said he wants to do a major release soon so should I hold out till then and just focus on cleaning this one up? I'll have a look at that FR.

That reminds me, @MGaetan89 there's a lot of inline styles. Did you want to try adding them to the new CSS stylesheets you've been working on?

Multi-language sounds like a good idea, but that means all text would need to be rendered from variables in language files. If someone wants to look at adding that I'll redo all of the files to use them. We'd also need translators but I'm guessing if we can get English working others will be able to just duplicate the language file and change it to their language and submit a PR.

**Comment by MGaetan89** [comment]
@OmgImAlexis I did not plan to do that yet. I agree it should be change, but I think there are more important improvements to do.
If we are going to support multiple languages, I can provide the French translation.

**Comment by OmgImAlexis** [comment]
@MGaetan89 Yeah I agree, just thought I'd mention it while you're still working on it.
I'm thinking the inline styles may be part of the reason for https://github.com/SiCKRAGETV/sickrage-issues/issues/2381

**Comment by neoatomic** [comment]
@OmgImAlexis Yes, thats Goeny's Slicker theme. But the images are outdated as he has redone the whole theme after his last post.

Think we have had 2-3 users that where planning/creating a theme but got stuck because the Slick theme didn't let them easily create there own Theme. (and it might happen also to Slicker?...) So if we possible, i hope we can make some improvements there. It also encourages users to contribute. 

Multi-Language we dont have to implement anytime soon, but might be a good idea to consider/prep the theme to allow that in the future. Same for other features we might want to implement on a later date.

**Comment by miigotu** [comment]
I think we need to stay on the track we are on now and continue refining slick for now. Translation will be simpler/cleaner to add to a clean/lean theme.

for now unicode sandwich, and post processor rewrite are the only major changes outside the theme that are planned before major release. (and might not make it into this release even).
