### ISSUE TITLE
Not requiring logins?! Logout doesn't do anything...?

### ISSUE THREAD

**Issue by skipmeister123** [SiCKRAGETV/sickrage-issues#2606]
I'm not sure when this started happening, but I can browse my SickRage install without logging in (eg, private browsing, using someone elses' computer...).  If I try to log out, it redirects back to the show list, and I'm still able to make changes.

**Comment by miigotu** [comment]
go check that your username and password are set. login still works.

**Comment by skipmeister123** [comment]
Maybe I'm missing something, but I couldn't find where to set it. I
remember having to log in before. I'm not sure when this started happening.

**Comment by miigotu** [comment]
config/general/ on the interface tab, "HTTP username/password"

**Comment by skipmeister123** [comment]
AH! Yeah, it's empty. I wonder when that happened. Thanks! Looks like I'm just dumb. :)

--  
Hans Kokx
