### ISSUE TITLE
[Feature Request] Add Seed time to torrent providers

### ISSUE THREAD

**Issue by jiBYo** [SiCKRAGETV/sickrage-issues#2607]
Can we please have seed time per tracker? If you could add the option for seed time per episode or season for btn that would be even better but seed time per tracker would be good.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
