### ISSUE TITLE
Missing network icons.

### ISSUE THREAD

**Issue by elit3ge** [SiCKRAGETV/sickrage-issues#2611]
Hinterland - S4/C
![hinterland](https://cloud.githubusercontent.com/assets/1644699/9577740/4e0194ea-5027-11e5-94d8-7787c92d2530.PNG)

Utopia (AU) - ABC (AU)
![utopia](https://cloud.githubusercontent.com/assets/1644699/9577742/4e04bd28-5027-11e5-9bf9-9ecb2d2cbbc0.PNG)

Digimon - Toon Disney
![toon disney](https://cloud.githubusercontent.com/assets/1644699/9577741/4e025114-5027-11e5-9559-02cdd645a948.PNG)

Swift and Shift Couriers - SBS (AU)
![swift and shift](https://cloud.githubusercontent.com/assets/1644699/9577743/4e0f090e-5027-11e5-8dda-8875da841714.PNG)

**Comment by neoatomic** [comment]
@elit3ge Should be fixed on the next update.

(However i wasn't able to add the S4/C logo due to the `/` in the name, the file system doesn't except that.Only way to solve that is changing the network name on thetvdb)

**Comment by miigotu** [comment]
@neoatomic I think if you add a directory in the images/network folder `s4` and put a file `c.png` in it, it would show up xD.

**Comment by neoatomic** [comment]
@miigotu That worked. :)
