### ISSUE TITLE
Failed Unrar archive time data '2000-01-01 00:00' does not match format '%d-%m-%y %H:%M'

### ISSUE THREAD

**Issue by zarkroc** [SiCKRAGETV/sickrage-issues#2613]
Something broke during the debian update of unrar to version 1:5.3.2-1 older version still works fine to use.Looking at the changelog for unrar it states the following for 5.30 beta 1:  3. Console RAR "l" and "v" commands display file time in YYYY-MM-DD format.
```
2015-08-31 15:11:58 ERROR    POSTPROCESSER :: Failed Unrar archive orange.is.the.new.black.s03e07.720p.webrip.x264-2hd.rar: time data '2015-06-14 06:52' does not match format '%d-%m-%y %H:%M'
AAValueError: time data '2000-01-01 00:00' does not match format '%d-%m-%y %H:%M'
AA    (data_string, format))
AA  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
AA    return _strptime(data_string, format)[0]
AA  File "/usr/lib/python2.7/_strptime.py", line 467, in _strptime_time
AA    data['datetime'] = time.strptime(fields[2]+" "+fields[3], '%d-%m-%y %H:%M')
AA  File "/home/***/sickrage/lib/unrar2/unix.py", line 179, in infoiter
AA    for params in RarFileImplementation.infoiter(self):
AA  File "/home/***/sickrage/lib/unrar2/__init__.py", line 120, in infoiter
AA    return list(self.infoiter())
AA  File "/home/***/sickrage/lib/unrar2/__init__.py", line 125, in infolist
AA    for file_in_archive in [os.path.basename(x.filename) for x in rar_handle.infolist() if not x.isdir]:
AA  File "/home/***/sickrage/sickbeard/processTV.py", line 380, in unRAR
AATraceback (most recent call last):
```

**Comment by WebSpider** [comment]
Since we're using an external library for unrar, this will likely have to go upstream. Will confirm in a few hours

**Comment by renini** [comment]
i have the same issue, i think after installing: unrar:amd64 (5.2.7-0.1, 5.3.2-1) on debian

**Comment by WebSpider** [comment]
Yeah, rar output seems to have changed:

````
BLACKBOX> unrar l some.rar

UNRAR 5.01 freeware      Copyright (c) 1993-2013 Alexander Roshal

Archive: some.rar
Details: RAR 4, volume

 Attributes      Size    Date   Time   Name
----------- ---------  -------- -----  ----
 -rw-r--r-- 1110074492  13-08-15 16:53  some.mkv
----------- ---------  -------- -----  ----
           1110074492  volume 1        1
````

Unrar output used to be '%d-%m-%y %H:%M', apparently this has changed.
Short term workaround: Keep unrar downrev in your install. Will open an issue with py-unrar2 to see if this can be solved upstream.

**Comment by renini** [comment]
Is it possible to install the old unrar binary next to the current one so that sickrage uses that as a temporary workaround?

**Comment by WebSpider** [comment]
Thanks for letting us know, will use this for others that are having the same issue, until we can update the library

**Comment by OmgImAlexis** [comment]
@WebSpider has this been updated/fixed?

**Comment by WebSpider** [comment]
No, This is still upstream. The lib seems somewhat dead tbh.

**Comment by OmgImAlexis** [comment]
Maybe we need to look into using another library then?

**Comment by miigotu** [comment]
We might look into switching to a different lib. However I have updated to the latest version and patched it locally for now, so this is fixed.
