### ISSUE TITLE
[APP SUBMITTED]: CHECKVERSION :: Unable to contact github, can't check for update

### ISSUE THREAD

**Issue by c0derMick** [SiCKRAGETV/sickrage-issues#2614]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@ea897589698c18007ff0fd062b224d68d76d3bb5
Link to Log: https://gist.github.com/c6b133ff9a19e176def8
### ERROR
```
CHECKVERSION :: Unable to contact github, can't check for update
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Github was probably down for a moment, or you had no ISP connection. etc.

**Comment by WebSpider** [comment]
Your git seems to be corrupted. 
Possibly do a git reset, which you can find in settings with auto update.

-----Original Message-----

**Comment by c0derMick** [comment]
That makes sense.  I'm new to this and could use a little help.  I'm running this on a Synology NAS, which is basically linux for the underlying OS.  When I tried to run through the steps found here, https://github.com/SiCKRAGETV/sickrage-issues, I couldn't run the git command.  It seems like it's not part of the path, but of course I don't know where it's installed because it's all done through the web UI.  Any help would be appreciated.

**Comment by WebSpider** [comment]
If you're using Syno:

1) Install git from SynoCommunity
2) Install SickRage from SynoCommunity
3) git path is /usr/local/git/bin/git

If it doesn't work, copy config.ini and sickbeard.db. Reinstall SickRage and copy the files back into /usr/local/sickrage/var

**Comment by c0derMick** [comment]
@WebSpider Thanks, I removed and reinstalled; that did the trick.  Copying those files made the recovery super simple.
