### ISSUE TITLE
[SUBTITLE] -- Exception caught in subliminal.scan_video

### ISSUE THREAD

**Issue by pATYbulaire** [SiCKRAGETV/sickrage-issues#2615]
Hello Guys,

Few information:

SR Version:	BRANCH: (master) / COMMIT: (4db41da61c3e4639a19613a3e4f0dfeef9831fc0) 
SR User:	pATYbulaire
SR Locale:	('fr_FR', 'cp1252')
SR Config file:	D:\Downloads\SickRage\config.ini
SR Database file:	D:\Downloads\SickRage\sickbeard.db
SR Cache Dir:	D:\Downloads\SickRage\cache
SR Log Dir:	D:\Downloads\SickRage\Logs
SR Arguments:	['--nolaunch']
Python Version:	2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]
OS Version : Windows 8 Enterprise 64 Bits

Could you please help me on this situation ?

Tyring to download a french srt for following release name:

2015-08-31 17:22:02 INFO Thread-59 :: Release name (fear.the.walking.dead.s01e02.720p.hdtv.x264-killers) found from file (fear.the.walking.dead.s01e02.720p.hdtv.x264-killers.nfo)

Existing there:

http://www.podnapisi.net/subtitles/f...15-S01E02/_Ls9
(SR configured to use podnapisi)

Getting the following DEBUG level error:

2015-08-31 17:36:21 DEBUG Thread-69 :: 290853: Exception caught in subliminal.scan_video for S01E02
2015-08-31 17:36:21 DEBUG Thread-69 :: 290853: Downloading subtitles for S01E02
2015-08-31 17:30:19 DEBUG Thread-27 :: 290853: Exception caught in subliminal.scan_video for S01E02
2015-08-31 17:30:18 DEBUG Thread-27 :: 290853: Downloading subtitles for S01E02

Worked like a charm on S01E01 without any action from me.

Tried:

- Restart
- Update : was a bit late on this point.
- Hack nfo/mkv filenames...

Question:

- Any way we could see the regex used during podnapisi API use ?
- Anything else ?

Thanks.

**Comment by miigotu** [comment]
1. Please don't open duplicate issues, find the existing ones and use those.
2. It doesn't use a regex really, it uses the hash of the actual file
3. It is most likely your naming pattern. If you have them in subfolders make sure the naming pattern has `Season` or `S` before the season number, as in `Season 01/` or `S01/`

**Comment by miigotu** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/2506
