### ISSUE TITLE
Latest gui on iPad shows mostly the menu bar

### ISSUE THREAD

**Issue by udochrist** [SiCKRAGETV/sickrage-issues#2618]
![image](https://cloud.githubusercontent.com/assets/869637/9585800/4ff4825c-5019-11e5-897a-63ea91207767.jpg)
After today's update the main menu bar takes roughly 1/3 of the screen in landscape mode on an iPad. No more burger menu like before. 

SR Version:	BRANCH: (master) / COMMIT: (4db41da61c3e4639a19613a3e4f0dfeef9831fc0)

**Comment by miigotu** [comment]
@MGaetan89 I forgot there were some customizations in bootstrap, specifically min-width and max-width for navbar collapse.

The standard version collapses at 768 to burger, our custom I think was up to 1068 or something like that because of the poorly done navbar not working right.

**Comment by MGaetan89** [comment]
Ok, will check this and update Bootstrap.

**Comment by udochrist** [comment]
It also seems that the navbar is not constant in width. Sometimes the support button is on the same line, sometimes not

**Comment by nrk666** [comment]
Heh, came to post this same bug, I can confirm this as of SR Version:	BRANCH: (master) / COMMIT: (4db41da61c3e4639a19613a3e4f0dfeef9831fc0) on both ipad2 and ipad3.

**Comment by MGaetan89** [comment]
I just sent a PR to fix this: https://github.com/SiCKRAGETV/SickRage/pull/2396

**Comment by MGaetan89** [comment]
The PR was merge.
So this should be fixed in the next version.
