### ISSUE TITLE
[Feature Request] Introduction of Season Names for Anime

### ISSUE THREAD

**Issue by Fenikkusu** [SiCKRAGETV/sickrage-issues#2623]
I've had this issue a good number of times already.

In the case of Anime, often times the Seasons have different names (IE: SAO, SAO II), but are considered part of the same series based off TVDB/TVRage. This causes issues in that when post-processing occurs, files will be named based off the enclosing show, not the actual show name. (IE: Season 02/SAO - S2E1 instead of Season 02/SAO II)

If seasons had names, the name could be used for the folder when using folder based seasons. Additionally, the Season Name could be used in File Naming. IE: SAO/SAO/S1E01, SAO/SAO II/S2E01.

This also creates issues when loading existing shows, as I am forced to manually rename all the files for the additional seasons (named based off the season named) and move them so that SR finds them properly.

This could be populated from TVRage/TVDB as an additional feature.

**Comment by kvloover** [comment]
Another good example:
Working! (S1)
Working!! (S2)
Working!!! (S3)

This can even cause S3 episodes to end up in a S1 folder and being shown as such on the show overview page.

**Comment by Quiksmage** [comment]
Another thing I would add, if this were to be implemented, is the ability to define this as we would for "scene names" so that we can make something work on a season by season basis if auto-populated ones didn't work. There's a decent amount of anime shows this season that don't even download because they can't be found (rss auto-dl saves the day here).

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
