### ISSUE TITLE
Windows installer for SickRage

### ISSUE THREAD

**Issue by VinceVal** [SiCKRAGETV/sickrage-issues#2624]
Suggested SickRage to a buddy of mine who runs Windows and he didn't want to hassle with Git/Python/etc... Any interest in an easier installer for Windows users? I'd be happy to work on something to make the process a bit easier for our Windows buddies.

**Comment by WebSpider** [comment]
I would be all for it, as long as we don't have to provide seperate windows versions for all releases, like SB used to do.

-----Original Message-----

**Comment by VinceVal** [comment]
I was thinking something more along the lines of pulling in a copy of git, python, dependencies, etc and letting the built in git updater handle the updates. Really more just bootstrapping the process so the user doesn't have to install stuff separately. I'd also like to keep everything in a separate directory as to not interfere with any globally installed Git/Python.

**Comment by WebSpider** [comment]
:+1:

**Comment by neoatomic** [comment]
We talked about doing this a few weeks back. So it would be more than welcome if you are able to create an installer. 

Here are some guides related to the windows installation that might help you.
(However we dont need Cheetah anymore, so that part you can leave out.)

http://www.htpcguides.com/install-sickrage-windows-usenet-torrent-tv/
http://www.htpcguides.com/create-sickrage-system-service-windows-versions/
http://www.htpcguides.com/create-sickrage-windows-system-service-v2/
https://sickrage.tv/forums/forum/help-support/general-support/3076-installing-sickrage-on-windows

**Comment by VinceVal** [comment]
Cool. I have some experience here, so I'll get something whipped up. Thanks for the links!

**Comment by VinceVal** [comment]
OK, I've completed a first stab of the installer. It is hosted (for now, at least) [here](https://github.com/VinceVal/SickRageInstaller). I would appreciate any feedback. At this point, the only platform I've tested it on is Windows 7 64-bit.

Let me know what you think!

**Comment by VinceVal** [comment]
Just tested on my Windows 10 64-bit box and it worked there too.

One known issue with the way the service is running with NSSM is that you can't actually shut SickRage down using the Web UI. NSSM will just restart it. What would probably be ideal is if SickRage could exit with different exit codes depending on the scenario. NSSM can take different actions depending on the process' exit code.

**Comment by WebSpider** [comment]
Do you have relevant documentation on NSSM, so we can make needed changes in SR?

Also, where can I download a version to test with?

-----Original Message-----

**Comment by VinceVal** [comment]
NSSM doesn't have any specific requirements. It allows you to define different behaviors (restart or exit) depending on the return code of the process. The default behavior of NSSM is to restart the process no matter what.

What might make sense would be to configure NSSM to restart SR for all return codes except zero. I'm guessing if SR crashed for some reason, it would terminate with a non-zero code and NSSM could re-start it.

The caveat with this scenario is that NSSM does extra cleanup when the process exits, including killing all of its sub-processes. This means restarting SR from within itself can't be done because the newly started process will get killed by NSSM when the original process exits. One option I can think of would be to have SR just exit with a non-zero code instead of restarting itself. NSSM would then restart it. Maybe an option or command line flag to tell SR to exit with a specific code when "restarting"?

Anyway, hopefully that makes sense. You can grab SickRageInstaller from https://github.com/VinceVal/SickRageInstaller/releases.

**Comment by OmgImAlexis** [comment]
@VinceVal would this not work for the restarting issue? /config/general/
![screen shot 2015-09-06 at 5 25 00 pm](https://cloud.githubusercontent.com/assets/6525926/9703239/48ccee90-54bc-11e5-9c15-f9d65cc7088e.png)

**Comment by VinceVal** [comment]
@OmgImAlexis Yes, that is half of the solution. The other half would be to use a non-zero return code for these "restarts" so we can configure to be able to see the difference between an exit and a restart -- if we event want it. Basically we're talking about making it able to shutdown the service from the web UI instead of having to stop the Windows service.

**Comment by miigotu** [comment]
@VinceVal :+1: :+1: :+1: 

This is exactly the installer I was describing to @neoatomic like a week about with inno.

Not sure if you should have this line`DelTree(PythonPath + '\Scripts',      True,  True, True)` as that is where easy_install is, and you might be better off letting that there incase users need to install other packages, maybe even for other apps that will eventually use their python install.  The same might be true for the Tools folder, but Im not sure whats in there.

OpenSSl doesn't need installed separate from pyOpenSSL does it? I would suggest doing some requests with an ssl enabled url that needs SNI to work, to make sure pyOpenSSL is working.

**Comment by VinceVal** [comment]
@miigotu thanks for the feedback.

The idea is that this Python folder is private to SR. Users shouldn't be installing anything else in there. It doesn't get added to the user's PATH or integrated with the shell. The CleanPython() function tries to replicate doing a minimal install through the interactive MSI. I couldn't figure out a way to deselect the features when doing an administrative (/a) install, so I just delete the files...

As for OpenSSL, I think everything gets installed. pyOpenSSL's directory has a copy of libeay32.dll and ssleay32.dll. I've confirmed SR can now be put into SSL mode and it will start a functioning HTTPS server, but I have not done any testing with SNI enabled hosts.

**Comment by fernandog** [comment]
Can you 'set chcp 65001' before running SR?

**Comment by VinceVal** [comment]
@fernandog What is the best way for me to test whether the code page is taking effect correctly?

**Comment by fernandog** [comment]
try adding a show with special chars. don't know another way

**Comment by neoatomic** [comment]
@VinceVal Thanks again for providing us with this installer. :+1: 

I updated the WiKi and made a entry for the installer.

https://github.com/SiCKRAGETV/sickrage-issues/wiki/SickRage-Windows-Installer

(Only thing i noted was that the create shortcut is not checked by defealt.? )

And here is a show that has issues with special characters on windows.
https://github.com/SiCKRAGETV/sickrage-issues/issues/2556

**Comment by WebSpider** [comment]
Yup, add Aeon Flux for instance

-----Original Message-----

**Comment by WebSpider** [comment]
@VinceVal do you plan to update this installer from time to time?

Would like to add it to contrib/ either as submodule (link) or store your work there more permanently, whichever suits you best.

-----Original Message-----

**Comment by VinceVal** [comment]
@WebSpider yes, I don't mind maintaining the installer. I would prefer to keep write access to the repo if that's OK, but I'm up for whatever you guys want to do.

**Comment by VinceVal** [comment]
Regarding the special chars, I'll check this out tonight... Thanks for the examples!

**Comment by neoatomic** [comment]
@VinceVal I used the installer a couple of times now, it really works smooth/nice.!

However one small thing, in a future release would it be possible to add an option/field to chose the branch.?

**Comment by OmgImAlexis** [comment]
@neoatomic doing that especially with an OS like Windows will likely get people install develop without knowing what they're doing, if this is added please please please add a warning.

**Comment by neoatomic** [comment]
Off-course, the text field would be pre populated with `master` and a warning to not change that unless asked. :) (But even without that, i dont think it will course any problems.)
Its just a pain to switch every-time after the install to develop.

**Comment by WebSpider** [comment]
@VinceVal I will add a link to your repository as a submodule in /contrib .. that way you can keep it up to date yourself with all permissions you have in your own repository, and we can still include it in our project.

**Comment by OmgImAlexis** [comment]
@neoatomic I also noticed there isn't an option to change branches to anything but master in SickRage after install, @VinceVal I'm assuming it's because of an option you used with cloning it?

**Comment by fernandog** [comment]
@OmgImAlexis by design, if user don't enter github account, he can't switch to develop because he won't be able to submit issues.

**Comment by OmgImAlexis** [comment]
Oh... right. @fernandog I'll add mine in now. I didn't know that.

**Comment by VinceVal** [comment]
Cool, I think I can come up with a nice way to select the branch when installing. I had actually thought about this but had concerns similar to @OmgImAlexis and didn't know if anybody wanted that feature anyway.

**Comment by fernandog** [comment]
@VinceVal is it possible to add a hidden setting in the config.ini saying the user installed with your isntaller? like 'windows_installer = true'
this way when user reports an issue we can add this info in issue detail

@miigotu what do you think?

**Comment by miigotu** [comment]
config.ini doesn't exist yet. would require a command line parameter, and I'm not sure it would be terribly useful. If we go to the extent of creating an INI the cooler option would be to add github username and password right from the installer, and some other common initial settings, sort of like a wizard. Not sure if anything too fancy would be optimal because things in SR could change and that adds maintenance to have to update the installer more too.

**Comment by fernandog** [comment]
@VinceVal how to do ask/set SR port if there's no config.ini while installing?

**Comment by VinceVal** [comment]
My early versions of the installer created a bare-bones config.ini (to set the git.exe path). I have since switched to using NSSU to add git to the path.

It would certainly be possible to seed the config.ini file at install time. The main side-effect I saw when doing this was SR didn't create it's default config.ini until you actually went in and saved something. I don't think this caused any problems though.

I am considering adding a step during the install wizard where you can select the branch you want to install and also input your GitHub credentials...

@fernandog to answer your question, SR has a command-line option to specify the web server port.

**Comment by miigotu** [comment]
If adding some command line options (for say just the first boot) helps make this easier, I could make that happen.

**Comment by neoatomic** [comment]
@VinceVal In case you haven't seen this post/issue. 
https://sickrage.tv/forums/forum/help-support/general-support/27533-windows-installer-for-32bit#post27533

**Comment by VinceVal** [comment]
Fixed the NSSM issue on 32-bit machines. Was installing opposite bitness NSSM. Oops.

**Comment by fernandog** [comment]
command line override the config then or update it?

**Comment by VinceVal** [comment]
Sorry, what are you referring to?

**Comment by WebSpider** [comment]
@VinceVal do we still need this topic open, or do you consider the installer complete for now?

**Comment by VinceVal** [comment]
I think we can close it. I haven't heard very much on the installer which I assume is a good thing.

**Comment by miigotu** [comment]
is the chcp handled in the installer yet? need any CLI args added to SR? and about the return value of exit?

**Comment by VinceVal** [comment]
At some point I'll probably open a PR for the exit code stuff.

CHCP is NOT handled yet. I tried to reproduce this a while back so I could make sure my fixes were working, but I couldn't seem to get it working, even when just running it from the command prompt. I'll take a look again.

I've opened a couple issues for these at VinceVal/SickRageInstaller#4 and VinceVal/SickRageInstaller#5.

**Comment by miigotu** [comment]
@VinceVal Honestly I think that the return code is correct already, and the service should just not restart on a status 0 (errorlevel is ok, we wanted to shut it down)

Also should make sure that SR is not started in daemon mode (-d or --daemon)

**Comment by VinceVal** [comment]
@miigotu, refer to my post above:

> NSSM doesn't have any specific requirements. It allows you to define different behaviors (restart or exit) depending on the return code of the process. The default behavior of NSSM is to restart the process no matter what.
> 
> What might make sense would be to configure NSSM to restart SR for all return codes except zero. I'm guessing if SR crashed for some reason, it would terminate with a non-zero code and NSSM could re-start it.
> 
> The caveat with this scenario is that NSSM does extra cleanup when the process exits, including killing all of its sub-processes. This means restarting SR from within itself can't be done because the newly started process will get killed by NSSM when the original process exits. One option I can think of would be to have SR just exit with a non-zero code instead of restarting itself. NSSM would then restart it. Maybe an option or command line flag to tell SR to exit with a specific code when "restarting"?
> 
> Anyway, hopefully that makes sense.

So.... If we want SR to be able to both exit and restart from the web GUI, we need to do *something*.

I would propose exiting with a return code of 1 (or anything non-zero) when SR wants to be restarted. Since there's already an option (no_restart) that does half of this, maybe we create a command line parameter like --no-restart-exit-code=N so you could specify the exit code you want to see for restarts.

Ideas?

**Comment by OmgImAlexis** [comment]
@VinceVal can this discussion please be moved to the issue tracker for the windows installer, trying to clear out issues not related directly to SickRage.
