### ISSUE TITLE
Strange tabs layout

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#2625]
Has anyone seen this?
Fonts are different too.

![image](https://cloud.githubusercontent.com/assets/2620870/9593592/cb60a3fa-5026-11e5-91b5-0d870644b97d.png)

@miigotu @MGaetan89 @OmgImAlexis

**Comment by OmgImAlexis** [comment]
@fernandog is this on the dev branch? I'm still on master.

**Comment by neoatomic** [comment]
Fonts are indeed a little different. (Thinker.)

**Comment by fernandog** [comment]
Develop

**Comment by miigotu** [comment]
@OmgImAlexis makes no difference I made a release yesterday.

**Comment by MGaetan89** [comment]
Will check.
Maybe the font definitions in `style.css` and `light.css` were different somewhere, and I removed something I shouldn't have.

**Comment by MGaetan89** [comment]
The issue is somewhere else, because the fonts changed in the dark style too. I'm investigating.

**Comment by fernandog** [comment]
@MGaetan89 any news on this one? thanks

**Comment by MGaetan89** [comment]
Not yet, still looking at it.

**Comment by MGaetan89** [comment]
Looks like I needed to override some jQuery-UI styles.
Done in https://github.com/SiCKRAGETV/SickRage/pull/2405

**Comment by MGaetan89** [comment]
The fix is available in `develop`.

**Comment by fernandog** [comment]
hasn't changed

BRANCH: (develop) / COMMIT: (2982ade92e8ce0b58657103cedb3cb9b2ff3924e)

**Comment by miigotu** [comment]
@fernandog did you force refresh? ctrl+f5 or ctrl+shift+f5 ?

**Comment by fernandog** [comment]
had to delete /cache/mako
thanks
