### ISSUE TITLE
[Feature Request] Coming Episodes - Add column filter widget

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#2626]
don't allow "Search" column to be unselected
we can also remove the "Sort by" and the list box. User can filter in the table (tablesorter)

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!

**Comment by fernandog** [comment]
@VinceVal when this is done I will add more colums like "ends" and "run time"

![image](https://cloud.githubusercontent.com/assets/2620870/10327584/5aa50cd0-6c7f-11e5-9595-df6b43a5c915.png)
