### ISSUE TITLE
[Feature Request] Add language flag to audio track in mkv 

### ISSUE THREAD

**Issue by NicoLeOca** [SiCKRAGETV/sickrage-issues#2627]
Hi,

Most shows downloaded from scene basically have no flag for their audio tracks.
Would it be possible for SR to change the audio track's language automatically depending on the show's origin and on settings we enter?
It's a bit like automating Mkvtoolnix in the PP.

Looking forward to reading your comments about it.

BTW, I am suprised not to see it being part of the Scene rules

**Comment by WebSpider** [comment]
Interesting suggestion.

Can't use mkvtoolnix as this would introduce an external binary dependency, something we're trying to avoid.

Alternative might be the enzyme library by @diaoul 

-----Original Message-----

**Comment by Diaoul** [comment]
Currently enzyme doesn't support writing metadata. That could be a nice
addition.

**Comment by WebSpider** [comment]
Speaking for myself, i'm not a big fan of modifying stuff we downloaded to add metadata or transcode for instance.

We already write metadata in kodi NFO's for instance, which would be fine.

-----Original Message-----

**Comment by NicoLeOca** [comment]
I use Plex
and it's mainly based on users' language preferences for subtitles in mobile and cloud sync.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
