### ISSUE TITLE
[APP SUBMITTED]: 403 {u'documentation_url': u'https://help.github.com/articles/locking-conversations/', u'message': u'Unable to create comment because issue is locked.'}

### ISSUE THREAD

**Issue by sverleysen** [SiCKRAGETV/sickrage-issues#2629]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 23:30:53) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@4db41da61c3e4639a19613a3e4f0dfeef9831fc0
Link to Log: https://gist.github.com/87cf89d48e7a5ded1ceb
### ERROR
```
Thread-105 :: 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:34:55) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-26-generic-i686-with-Ubuntu-15.04-vivid**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@3570d673ef9aed3a9ed5c17f9b076387ebbcbd65
No Log available with ERRORS: 
### ERROR
```
Thread-15 :: 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by MGaetan89** [comment]
@miigotu That's what happens when you try to reuse an issue that is locked :p

**Comment by fernandog** [comment]
SR issue submitter does this automagicly. We should unlock the issue

**Comment by miigotu** [comment]
The issue is locked for a reason. We have maybe 2 or 3 locked issues atm that I can probably unlock now, as long as the argumentative people arent paying attention...

**Comment by MGaetan89** [comment]
Does GitHub API give a way to know if the existing issue is locked? So we can create a new one when the existing is locked.
I understand that issues are lock for a reason, so it might be better to use a new one.

**Comment by miigotu** [comment]
im sure there is, Ill look into it.
