### ISSUE TITLE
[Feature Request] Allow search by year

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2630]
Add search by episode year much like the search by date .Usefull for yearly aired shows like the MVA ,BMA or tge comedy central roasts par example

**Comment by WebSpider** [comment]
Are there scene rules for this?

-----Original Message-----

**Comment by duramato** [comment]
@WebSpider  i Believe there are scene rules ive been searching and found this https://scenerules.org/t.html?id=2012_1080pTV.nfo
its a long text ik ,so i use the find function with "year" as query and found ```Using just the year is only permitted if the event is once per year ``` and later on it gives an example ```WWE.WrestleMania.2010.PPV.1080p.HDTV.x264-GROUP```

**Comment by duramato** [comment]
Also a quick torretz search seems to back my finding https://torrentz.eu/search?q=MTV+Video+Music+Awards (in there ,there is some releases that dont follow scene rules such as 2maverick

**Comment by neoatomic** [comment]
This has been requested before and declined. The issue here is that its considered more a `movie` than a `series`. Therefore not something we are adding.

But would like to have @miigotu option, if we consider the FR or close it.

**Comment by miigotu** [comment]
When a series is set to air-by-date and your indexer is enabled for season pack, it does search by year, as the season IS the year.

**Comment by WebSpider** [comment]
@duramato can you check the suggested setup ?

**Comment by miigotu** [comment]
Also, setting a show to "sports" searches seasons by year.

**Comment by duramato** [comment]
@miigotu that does not work this shows as they don't have any seasons

**Comment by miigotu** [comment]
@duramato it does. It uses the year as the season.

https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/providers/kat.py#L74
https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/providers/kat.py#L93
https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/providers/kat.py#L95

It is the same in all of the providers.

**Comment by duramato** [comment]
Im not understanding ,what do I do ? set it as sport and enable season pack only ? for a providetr like kat

**Comment by miigotu** [comment]
or air-by-date. season search fallback should help too.

**Comment by duramato** [comment]
And then I do a season search or episode search?

**Comment by miigotu** [comment]
episode search will search full date like `2015 9 2`, season search will search with just `2015`

**Comment by duramato** [comment]
The thing is it only has 1 season so does it work that way?

**Comment by miigotu** [comment]
Yes.

**Comment by duramato** [comment]
ive tryed ,but didnt worked
