### ISSUE TITLE
ImportError: No module named event_queue

### ISSUE THREAD

**Issue by ronilaukkarinen** [SiCKRAGETV/sickrage-issues#2634]
Hello. Just installed fedora 22 and getting this:

````
[11:51:55] [59.0°C] rolle SickRage $ python SickBeard.py --nolaunch
Traceback (most recent call last):
  File "SickBeard.py", line 81, in <module>
    from sickbeard.event_queue import Events
ImportError: No module named event_queue
````

Have been trying to solve but can't find anything about it. What's up?

**Comment by miigotu** [comment]
Something wrong with your setup or install. sickbeard/event_queue.py is definitely there.

**Comment by ronilaukkarinen** [comment]
Yeah, maybe incomplete backup or something... Solved it with these commands:

````
git reset --hard
git clean -f
git pull
````

Don't know details about the files so thanks for pointing me to the right direction, it works now.
