### ISSUE TITLE
[Feature Request] Add provider hd-bits.com

### ISSUE THREAD

**Issue by piejanssens** [SiCKRAGETV/sickrage-issues#2635]
https://www.hd-bits.com (reg open for now)

Note this is a different site than https://hdbits.org which is already supported by SR.

**Comment by WebSpider** [comment]
I have setup an account, so we can work on this when we cleaned up providers

**Comment by miigotu** [comment]
I've also created an account.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
