### ISSUE TITLE
post processing won't ignore failed download

### ISSUE THREAD

**Issue by joakim93** [SiCKRAGETV/sickrage-issues#2637]
Python Version: 2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]
Operating System: FreeBSD-9.1-RELEASE-amd64-64bit-ELF
Locale: unknown
Branch: master

I noticed that it grabs the same files every time when the backlog scans. and then i pulled this from the log and it notices that it fails but it won't go to the failed list. It does this with every episode in the pacific show. Log file for the post process:
https://gist.github.com/joakim93/be40098ab57369a4bf02#file-post-process
Here is the part when it downloads it : 
https://gist.github.com/joakim93/be40098ab57369a4bf02#file-download
Here is the log from sabnzd: https://gist.github.com/joakim93/be40098ab57369a4bf02#file-sabnzb

**Comment by miigotu** [comment]
@joakim93 its failing to login to SR.
