### ISSUE TITLE
Failed status is selectable without FDH enabled

### ISSUE THREAD

**Issue by laughinggoose** [SiCKRAGETV/sickrage-issues#2638]
Branch: master
commit: 4db41da61c3e4639a19613a3e4f0dfeef9831fc0
operating system: 32 bit Ubuntu server
python version: 2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]

SickRage automatically snatched a file and sent it to SabNZB. The download failed while in Sab (not enough repair blocks). The episode remains as Snatched in SickRage. I tried doing manual search including current video quality and it snatched the same file that fails. I tried setting the episode status from snatched to failed. SR once again snatched the file that fails.

I would expect SR to ignore files that were snatched and then marked as failed.

Log: https://gist.github.com/laughinggoose/08ea84f634c16ed9fb4d

**Comment by fernandog** [comment]
Did you enabled Failed downloads in SR??

**Comment by fernandog** [comment]
Wheb you manual search you are asked to mark as failed.

**Comment by laughinggoose** [comment]
I just enabled failed downloads and tried again. It's working!

What's the point of the failed status if you don't have failed downloads enabled? It just sets episode status to wanted, which grabs the same file as before. Could you maybe put in a warning about this?

**Comment by miigotu** [comment]
Its a bug that failed is showing without failed enabled. Will try and fix one day soon

**Comment by WebSpider** [comment]
Oh.Lol,we doublefixed it.

**Comment by fernandog** [comment]
know how to fix webapi ? if you do, will close my PR

**Comment by miigotu** [comment]
fixed in develop.

**Comment by darklow** [comment]
Now after these changes and PR i cannot use api anymore as i was using it before.
I was using API and updating status to Archived once i have processed it on my app (after post-processing script), and now i got error:
```
param: 'status' with given value: 'archived' is out of allowed range '['wanted', 'skipped', 'ignored', 'failed']
```
I tried enabling "Use Failed Downloads - Use Failed Download Handling"
But nothing changed and i still got same error.
