### ISSUE TITLE
[Issue] TraktChecker does not sync nor add shows

### ISSUE THREAD

**Issue by Dpons039** [SiCKRAGETV/sickrage-issues#2639]
**Branch**
Master
**Commit hash**
4db41da61c3e4639a19613a3e4f0dfeef9831fc0
**System**
Synology NAS 415+
**Python Version**
2.7.10 (default, Jun 3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]
**What you did**
Setup the Notification and configure the Token and add watchlist shows on Trakt
**What happened**
Does not sync the watchlist nor add shows on my watchlist
**What you expected**
The above.

Error messages:
```AA
AATypeError: expected string or buffer
AA    return _compile(pattern, flags).sub(repl, string, count)
AA  File "/usr/local/sickrage/env/lib/python2.7/re.py", line 155, in sub
AA    name = re.sub(r'[\\/\*]', '-', name)
AA  File "/volume1/@****tore/sickrage/var/SickRage/sickbeard/helpers.py", line 264, in sanitizeFileName
AA    showPath = ek.ek(os.path.join, location, helpers.sanitizeFileName(name))
AA  File "/volume1/@****tore/sickrage/var/SickRage/sickbeard/traktChecker.py", line 420, in addDefaultShow
AA    self.addDefaultShow(indexer, indexer_id, show['title'], WANTED)
AA  File "/volume1/@****tore/sickrage/var/SickRage/sickbeard/traktChecker.py", line 355, in updateShows
AA    self.updateShows()
AA  File "/volume1/@****tore/sickrage/var/SickRage/sickbeard/traktChecker.py", line 241, in syncWatchlist
AA    self.syncWatchlist()
AA  File "/volume1/@****tore/sickrage/var/SickRage/sickbeard/traktChecker.py", line 84, in run
2015-09-02 22:45:56 INFO     TRAKTCHECKER :: Adding show 253527
AA
AATypeError: expected string or buffer
AA    return _compile(pattern, flags).sub(repl, string, count)
AA  File "/usr/local/sickrage/env/lib/python2.7/re.py", line 155, in sub
AA    name = re.sub(r'[\\/\*]', '-', name)
AA  File "/volume1/@****tore/sickrage/var/SickRage/sickbeard/helpers.py", line 264, in sanitizeFileName
AA    showPath = ek.ek(os.path.join, location, helpers.sanitizeFileName(name))
AA  File "/volume1/@****tore/sickrage/var/SickRage/sickbeard/traktChecker.py", line 420, in addDefaultShow
AA    self.addDefaultShow(indexer, indexer_id, show['title'], WANTED)
AA  File "/volume1/@****tore/sickrage/var/SickRage/sickbeard/traktChecker.py", line 355, in updateShows
AA    self.updateShows()
AA  File "/volume1/@****tore/sickrage/var/SickRage/sickbeard/traktChecker.py", line 241, in syncWatchlist
AA    self.syncWatchlist()
AA  File "/volume1/@****tore/sickrage/var/SickRage/sickbeard/traktChecker.py", line 84, in run
2015-09-02 21:46:05 INFO     TRAKTCHECKER :: Adding show 253527
```

**Comment by miigotu** [comment]
@fernandog From blame I came across this pr: https://github.com/SiCKRAGETV/SickRage/commit/109855b46796cecbd0bf0e4546600fc7b803974a

Seems a possible intriduction of a bunch of trakt issues.

@Dpons039 not sure why you are getting this error yet.

**Comment by fernandog** [comment]
I added two shows to trakt and they were added OK to SR.

**Comment by miigotu** [comment]
About that PR I meant wheb the shows keep getting added back after delete xD

**Comment by Dpons039** [comment]
I have been doing some research, it seems that the Scripts attempts to add a show that is Watchlisted on Trakt with an invalid TheTVdb, this causes the script to fail and probably to stop processing the remaining shows on the watchlist.

2015-09-03 08:46:00 INFO     TRAKTCHECKER :: Adding show 253527

In this cases, the script should write an error message at the "View Log (Errors)" instead of "view log" informing that the show is not valid or does not appear to be listed on TheTVdb and continue the process.

**Comment by miigotu** [comment]
It should not write an error, as it is not a bug in SR causing it. We do not want bug reports of trakt having wrong id's, and in fact we do skip a show if it is not on tvdb and remove it form the watchlist even.

**Comment by Dpons039** [comment]
@miigotu Okay, that's good to know! Any clue why wasn't performing that this time?

**Comment by miigotu** [comment]
Not sure, maybe the new code for that which gborri added was also buggy. Low priority though

**Comment by Dpons039** [comment]
I can confirm that once that show has been removed from the Trakt Watchlist, the script correctly processed all the shows and added about 15 shows to SR that were pending.
