### ISSUE TITLE
transmission with custom rpc

### ISSUE THREAD

**Issue by RackerJack** [SiCKRAGETV/sickrage-issues#264]
Hi

I have transmissions RPC url listening at /torrent/rpc i have changed sickbeard/clients/transmission.py:33
`self.url = self.host + 'torrent/rpc'`
 to reflect this and tried to add the client to sickrage via the web ui but i still get "Error: Unable to get Transmission Authentication, check your config!" 
there is no username and password currently configured on transmission 

also transmission is listening on 0.0.0.0 in the web ui i have put http://localhost:9091/ and also tried http://127.0.0.1:9091/

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1218

**Comment by fernandog** [comment]
@RackerJack  please update SR and report back please. Fix was merged

**Comment by RackerJack** [comment]
Hi

this issue was fixed by abeloin

i now have the ability to change the rpc path in the web gui and auth with out password to that rpc url
