### ISSUE TITLE
Error when set home screen view to small poster

### ISSUE THREAD

**Issue by saitoh183** [SiCKRAGETV/sickrage-issues#2640]
Sickrage info:

SR Version:	BRANCH: (master) / COMMIT: (4db41da61c3e4639a19613a3e4f0dfeef9831fc0) 
SR User:	Administrator
SR Locale:	('en_CA', 'cp1252')
SR Config file:	E:\Sickrage\config.ini
SR Database file:	E:\Sickrage\sickbeard.db
SR Cache Dir:	E:\Sickrage\cache
SR Log Dir:	E:\Sickrage\Logs
SR Arguments:	[]
Python Version:	2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]

I set the view to small poster and i get:

![image](https://cloud.githubusercontent.com/assets/1534197/9647464/580a26b6-51ab-11e5-851b-94bce1751698.png)

i had to shutdown and open the config.ini to set it back to banner

**Comment by flightlevel** [comment]
If you stop Sickrage, clear your cache folder and then restart sickrage, does the same thing happen?

**Comment by WebSpider** [comment]
When you delete the entire cache folder, you should force full update.
Generally, deleting just cache/mako instead is enough

**Comment by saitoh183** [comment]
I will do this tomorrow and post back because my list is over 350 shows.  So a full update will be long I'm guessing

**Comment by flightlevel** [comment]
If you just delete cache/mako like @WebSpider noted, you won't have to do full update.

**Comment by saitoh183** [comment]
yup that cleared it right up...thanks
