### ISSUE TITLE
Add show title bar disappears

### ISSUE THREAD

**Issue by dpeart** [SiCKRAGETV/sickrage-issues#2641]
I was trying to add a new show and the title bar that contains add show was gone.  I finally found that if you have the web browser width set such that the main title gets placed underneath the SickRage icon, then the add show bar gets covered up.

It isn't obvious where it went.  I'm running the latest build of Chrome.

![image](https://cloud.githubusercontent.com/assets/5182846/9647498/3d52e1ee-51a3-11e5-8a5c-6fe421afeef6.png)

**Comment by flightlevel** [comment]
Known issue https://github.com/SiCKRAGETV/sickrage-issues/issues/2618
