### ISSUE TITLE
[Feature Request] IMDB popular shows page

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2642]
Make trhe IMDB popular shows page as beautifull  as the Add recommed shows and the Add trending shows

**Comment by WebSpider** [comment]
Ping @jonathanendersby

**Comment by flightlevel** [comment]
Where do you find 'Add recommed shows and the Add trending shows' in SickRage (sounds useful), I can't see that option?

**Comment by duramato** [comment]
@flightlevel you need to have trakt enabled

**Comment by WebSpider** [comment]
Yup, need Trakt account set up for that. I don't think you need SR Trakt sync, just the account details

**Comment by OmgImAlexis** [comment]
Adding onto this, both pages need the isotope js redone so it's loaded correctly. @MGaetan89 or I will move this to the inc_bottom when we get a chance so if you're working on this keep that in mind.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
