### ISSUE TITLE
[Feature request] Allow post processing of stand-alone subtitle files

### ISSUE THREAD

**Issue by Joshfindit** [SiCKRAGETV/sickrage-issues#2644]
For example:

Add `Hanako.to.Anne.EP008.jp.srt` to the watch folder, and it names then moves it to be right next to `Hanako & Anne - S01E08 - What is the English？.mkv`

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
