### ISSUE TITLE
[APP SUBMITTED]: argument of type 'int' is not iterable

### ISSUE THREAD

**Issue by phishin4dmb** [SiCKRAGETV/sickrage-issues#2645]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@4db41da61c3e4639a19613a3e4f0dfeef9831fc0
Link to Log: https://gist.github.com/b225ff69c76b4bac53c8
### ERROR
```
Thread-33 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 260, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 3429, in massUpdate
    sickbeard.showQueueScheduler.action.removeShow(showObj)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/show_queue.py", line 152, in removeShow
    if self._isInQueue(show, ShowQueueActions.REMOVE):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/show_queue.py", line 42, in _isInQueue
    return show.indexerid in [x.show.indexerid for x in self.queue if x.action_id in actions]
TypeError: argument of type 'int' is not iterable

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@phishin4dmb Where u using Trakt.? 
Can you give some more info on what you where doing.?

**Comment by phishin4dmb** [comment]
Trakt was the issue and I believe it has been fixed in the last release. Yet to test. 




Thanks. 



--
Sincerely
Steve Reynolds
(714) 820-8200

One of the bonuses of living on the edge is that the view is more spectacular and your experiences more extreme. You never know what is at the bottom, find out!

**Comment by Al-25** [comment]
Hello,
Having the issue too and not using trakt.
SR Version: 	BRANCH: (master) / COMMIT: (f8eedd203011de46f61e7725cacd33de2146439c).
Don't hesitate if you need more info !

**Comment by phishin4dmb** [comment]
All:




So it seemed to all stem from me imputing my own API in The config file. After the I generated a new API it was all good. 









--
Sincerely
Steve Reynolds
(714) 820-8200

One of the bonuses of living on the edge is that the view is more spectacular and your experiences more extreme. You never know what is at the bottom, find out!

**Comment by Al-25** [comment]
Hello  phishin4dmb,

What do you mean by " imputing my own API in The config file" ?

**Comment by WebSpider** [comment]
He probably meant changing the API key in the config file.

Thanks for the feedback @phishin4dmb

**Comment by Cliff1980** [comment]
Same Issue, not using Trakt it is unchecked

**Comment by Al-25** [comment]
Change the API key (General Configuration->Interface, section Web Interface, click on "generate") then restart sickrage.
It solved the problem for me.

**Comment by Cliff1980** [comment]
Many thanks AI-25 worked a charm :)
