### ISSUE TITLE
[APP SUBMITTED]: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183

### ISSUE THREAD

**Issue by mattperry1976** [SiCKRAGETV/sickrage-issues#2648]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:33:21) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-28-generic-x86_64-with-Ubuntu-15.04-vivid**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@4db41da61c3e4639a19613a3e4f0dfeef9831fc0
Link to Log: https://gist.github.com/d8e83c357e7eebc4ee62
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by WebSpider** [comment]
Please post debug log

**Comment by WebSpider** [comment]
Just submitted a fix. It will be added to develop in a bit.
