### ISSUE TITLE
History Limit Not Worknig

### ISSUE THREAD

**Issue by DrakeJones** [SiCKRAGETV/sickrage-issues#2649]
History Limit is fix/stuck at 100. Will not show "200" "500" or "All".

**Comment by WebSpider** [comment]
I'll have a look at it tonight, as im mobile now. Can someone confirm It's working or not for them in the mean time?

**Comment by duramato** [comment]
its also not working for me on the compact and detailed views

**Comment by MGaetan89** [comment]
Yes, it's broken for me too.
The API version is working. I guess there is something wrong in the interface.
I'll check that.

**Comment by fernandog** [comment]
+1 not working here also

**Comment by MGaetan89** [comment]
I found the issue. I'm working on it.

**Comment by WebSpider** [comment]
Thanks. For some reason Im having trouble accessing GitHub using ssh and http. Mail notifications work fine.

-----Original Message-----

**Comment by fernandog** [comment]
with this change, it doesn't save to config the last history selected

**Comment by WebSpider** [comment]
This has been merged into the develop branch. Please check if this works for you!

**Comment by OmgImAlexis** [comment]
This is working fine on master(just merged dev).

**Comment by DrakeJones** [comment]
Gee, updated and Sickrage is totally broken. Just me? 

Windows CMD Output: 
C:\Users\Administrator>"C:\Users\Administrator\Desktop\SickRage python.lnk"
22:43:08 DEBUG::MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S02E03 [GROUP: RLSGROUP] [ABD: Fals
22:43:08 DEBUG::MAIN :: Episode has no release group, replacing it with 'RLSGROUP'
22:43:08 DEBUG::MAIN :: formatting pattern: %SN - %Sx%0E - %EN -> Show Name - 2x03 - Ep Name
22:43:08 DEBUG::MAIN :: Trying to parse Show Name - 2x03 - Ep Name.ext
22:43:08 DEBUG::MAIN :: Parsed Show Name - 2x03 - Ep Name.ext into Show Name - S02E03 [ABD: False] [ANIME: False] [whic
22:43:08 DEBUG::MAIN :: The name Show Name - 2x03 - Ep Name.ext parsed into Show Name - S02E03 [ABD: False] [ANIME: Fal
22:43:08 DEBUG::MAIN :: Checking database structure...sickbeard.db
22:43:08 DEBUG::MAIN :: Checking Initial Schema database upgrade
22:43:08 DEBUG::MAIN :: InitialSchema upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Size And Scene Name Fields database upgrade
22:43:08 DEBUG::MAIN :: AddSizeAndSceneNameFields upgrade not required
22:43:08 DEBUG::MAIN :: Checking Rename Season Folders database upgrade
22:43:08 DEBUG::MAIN :: RenameSeasonFolders upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add1080p And Raw Qualities database upgrade
22:43:08 DEBUG::MAIN :: Add1080pAndRawHDQualities upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Showid Tvdbid Index database upgrade
22:43:08 DEBUG::MAIN :: AddShowidTvdbidIndex upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Last Update database upgrade
22:43:08 DEBUG::MAIN :: AddLastUpdateTVDB upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Increase To15 database upgrade
22:43:08 DEBUG::MAIN :: AddDBIncreaseTo15 upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Db Info database upgrade
22:43:08 DEBUG::MAIN :: AddIMDbInfo upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Proper Naming Support database upgrade
22:43:08 DEBUG::MAIN :: AddProperNamingSupport upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Email Subscription Table database upgrade
22:43:08 DEBUG::MAIN :: AddEmailSubscriptionTable upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Proper Search database upgrade
22:43:08 DEBUG::MAIN :: AddProperSearch upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Dvd Order Option database upgrade
22:43:08 DEBUG::MAIN :: AddDvdOrderOption upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Subtitles Support database upgrade
22:43:08 DEBUG::MAIN :: AddSubtitlesSupport upgrade not required
22:43:08 DEBUG::MAIN :: Checking Convert Shows To Indexer Scheme database upgrade
22:43:08 DEBUG::MAIN :: ConvertTVShowsToIndexerScheme upgrade not required
22:43:08 DEBUG::MAIN :: Checking Convert Episodes To Indexer Scheme database upgrade
22:43:08 DEBUG::MAIN :: ConvertTVEpisodesToIndexerScheme upgrade not required
22:43:08 DEBUG::MAIN :: Checking Convert Info To Indexer Scheme database upgrade
22:43:08 DEBUG::MAIN :: ConvertIMDBInfoToIndexerScheme upgrade not required
22:43:08 DEBUG::MAIN :: Checking Convert Info To Indexer Scheme database upgrade
22:43:08 DEBUG::MAIN :: ConvertInfoToIndexerScheme upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Archive First Match Option database upgrade
22:43:08 DEBUG::MAIN :: AddArchiveFirstMatchOption upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Scene Numbering database upgrade
22:43:08 DEBUG::MAIN :: AddSceneNumbering upgrade not required
22:43:08 DEBUG::MAIN :: Checking Convert Indexer To Integer database upgrade
22:43:08 DEBUG::MAIN :: ConvertIndexerToInteger upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Require And Ignore Words database upgrade
22:43:08 DEBUG::MAIN :: AddRequireAndIgnoreWords upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Sports Option database upgrade
22:43:08 DEBUG::MAIN :: AddSportsOption upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Scene Numbering To Tv Episodes database upgrade
22:43:08 DEBUG::MAIN :: AddSceneNumberingToTvEpisodes upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Anime Show database upgrade
22:43:08 DEBUG::MAIN :: AddAnimeTVShow upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Absolute Numbering database upgrade
22:43:08 DEBUG::MAIN :: AddAbsoluteNumbering upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Scene Absolute Numbering database upgrade
22:43:08 DEBUG::MAIN :: AddSceneAbsoluteNumbering upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Anime Blacklist Whitelist database upgrade
22:43:08 DEBUG::MAIN :: AddAnimeBlacklistWhitelist upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Scene Absolute Numbering database upgrade
22:43:08 DEBUG::MAIN :: AddSceneAbsoluteNumbering upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Xem Refresh database upgrade
22:43:08 DEBUG::MAIN :: AddXemRefresh upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Scene To Tv Shows database upgrade
22:43:08 DEBUG::MAIN :: AddSceneToTvShows upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Indexer Mapping database upgrade
22:43:08 DEBUG::MAIN :: AddIndexerMapping upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Version To Tv Episodes database upgrade
22:43:08 DEBUG::MAIN :: AddVersionToTvEpisodes upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Default Ep Status To Tv Shows database upgrade
22:43:08 DEBUG::MAIN :: AddDefaultEpStatusToTvShows upgrade not required
22:43:08 DEBUG::MAIN :: Checking Alter Shows Field Types database upgrade
22:43:08 DEBUG::MAIN :: AlterTVShowsFieldTypes upgrade not required
22:43:08 DEBUG::MAIN :: Checking database structure...cache.db
22:43:08 DEBUG::MAIN :: Checking Initial Schema database upgrade
22:43:08 DEBUG::MAIN :: InitialSchema upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Scene Exceptions database upgrade
22:43:08 DEBUG::MAIN :: AddSceneExceptions upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Scene Name Cache database upgrade
22:43:08 DEBUG::MAIN :: AddSceneNameCache upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Network Timezones database upgrade
22:43:08 DEBUG::MAIN :: AddNetworkTimezones upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Last Search database upgrade
22:43:08 DEBUG::MAIN :: AddLastSearch upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Scene Exceptions Seasons database upgrade
22:43:08 DEBUG::MAIN :: AddSceneExceptionsSeasons upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Scene Exceptions Custom database upgrade
22:43:08 DEBUG::MAIN :: AddSceneExceptionsCustom upgrade not required
22:43:08 DEBUG::MAIN :: Checking Add Scene Exceptions Refresh database upgrade
22:43:08 DEBUG::MAIN :: AddSceneExceptionsRefresh upgrade not required
22:43:08 DEBUG::MAIN :: Checking database structure...failed.db
22:43:08 DEBUG::MAIN :: Checking Initial Schema database upgrade
22:43:08 DEBUG::MAIN :: InitialSchema upgrade not required
22:43:09 DEBUG::MAIN :: Checking Size And Provider database upgrade
22:43:09 DEBUG::MAIN :: SizeAndProvider upgrade not required
22:43:09 DEBUG::MAIN :: Checking History database upgrade
22:43:09 DEBUG::MAIN :: History upgrade not required
22:43:09 DEBUG::MAIN :: Checking History Status database upgrade
22:43:09 DEBUG::MAIN :: HistoryStatus upgrade not required
22:43:09 INFO::MAIN :: Checking for shows with tvrage id's, since tvrage is gone
22:43:09 WARNING::MAIN :: Found 70 shows with TVRage ID', FIXING!
22:43:09 INFO::MAIN :: Mapping Dr. G: Medical Examiner to tvdb id 250448
22:43:09 ERROR::MAIN :: Fatal error executing query: column indexer_id is not unique
Traceback (most recent call last):
  File "c:\SickRage\sickbeard\db.py", line 168, in action
    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "c:\SickRage\sickbeard\db.py", line 88, in execute
    return self._execute(query, args)
  File "c:\SickRage\sickbeard\db.py", line 76, in _execute
    return self.connection.cursor().execute(query)
IntegrityError: column indexer_id is not unique
Traceback (most recent call last):
  File "c:\SickRage\SickBeard.py", line 522, in <module>
    SickRage().start()
  File "c:\SickRage\SickBeard.py", line 295, in start
    sickbeard.initialize(consoleLogging=self.consoleLogging)
  File "c:\SickRage\sickbeard\__init__.py", line 1308, in initialize
    db.sanityCheckDatabase(myDB, mainDB.MainSanityCheck)
  File "c:\SickRage\sickbeard\db.py", line 254, in sanityCheckDatabase
    sanity_check(connection).check()
  File "c:\SickRage\sickbeard\databases\mainDB.py", line 46, in check
    self.convert_tvrage_to_tvdb()
  File "c:\SickRage\sickbeard\databases\mainDB.py", line 77, in convert_tvrage_to_tvdb
    (INDEXER_TVDB, mapping[0]['mindexer_id'], tvrage_show['indexer_id'])
  File "c:\SickRage\sickbeard\db.py", line 168, in action
    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "c:\SickRage\sickbeard\db.py", line 88, in execute
    return self._execute(query, args)
  File "c:\SickRage\sickbeard\db.py", line 76, in _execute
    return self.connection.cursor().execute(query)
sqlite3.IntegrityError: column indexer_id is not unique
--------------------------------------------------------

Tried 
git remote add upstream https://github.com/SiCKRAGETV/SickRage.git
git fetch upstream
git checkout master
git branch -u upstream/master
git reset --hard upstream/master
git pull

No Joy.

**Comment by OmgImAlexis** [comment]
@DrakeJones that's got nothing todo with this issue. It's also should be fixed in master, you'd know that if you'd commented on an issue about it instead of this random one.

**Comment by DrakeJones** [comment]
Sorry for pissing you off. I'll keep my comments to myself self from now on.
