### ISSUE TITLE
[Feature Request] Option to Air Date column to History page

### ISSUE THREAD

**Issue by DrakeJones** [SiCKRAGETV/sickrage-issues#2650]
Select Column feature on History Page would be nice. I would like to see Air Date of downloaded shows.

**Comment by DrakeJones** [comment]
Adjustable width and Select Column feature on all pages, particularly "History" Page would be nice. I would like to see Air Date of downloaded shows on History Page especially.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
