### ISSUE TITLE
[APP SUBMITTED]: SHOWQUEUE-FORCE-UPDATE :: No data returned from TVRage, unable to update this show

### ISSUE THREAD

**Issue by technazz** [SiCKRAGETV/sickrage-issues#2652]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@4db41da61c3e4639a19613a3e4f0dfeef9831fc0
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: No data returned from TVRage, unable to update this show
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by technazz** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@f8eedd203011de46f61e7725cacd33de2146439c
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: No data returned from TVRage, unable to update this show
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by OmgImAlexis** [comment]
@miigotu TVRage is down, what do we do?

**Comment by WebSpider** [comment]
Handle the error, live with it if it's temporary ... Such teh interwebs ?

-----Original Message-----

**Comment by OmgImAlexis** [comment]
@WebSpider @miigotu said it looks like it won't be coming back up at all.

**Comment by WebSpider** [comment]
Hm. Need to see what's up there. Would be a shame if it died, and we could have done something to help

**Comment by miigotu** [comment]
@WebSpider I was contacted a few weeks back by the sysadmin, who said the owner had been trying to shut it down for awhile (paranoia, "people in the network") and that he had already diverted a shutdown order to their data center. He said he was quitting as the sysadmin a few weeks after he contacted me and that he wouldn't be able to avoid the shutdown anymore.

I plan to wait a few days to see if it has actually shut down or if it is just a temporary outage.

After the grace period, if it is necessary we will add a db sanity check for any shows using tvrage as indexer, and convert it to a tvdb id and change the indexer value. We will then strip out all support for tvrage.

I do not think that adding a replacement is optimal. tvdb + xem is enough to get our scene numbering, and having only one indexer simplifies our code and maintenance/stability quite a bit. Even a whole repo of scene exceptions goes away. Also, tvmaze or other replacements would not have any mapping on xem.

**Comment by fernandog** [comment]
still down

**Comment by WebSpider** [comment]
That's a shame, really, shutting down a perfectly good service like that.

I'm trying to avoid us from missing information that is not available when we're out of TVRage, and thus leaving the user with a less complete SR because of it.

I'll walk by the code to make sure we're not missing anything.

-----Original Message-----

**Comment by WebSpider** [comment]
PS: If anyone has a TVRage backup, I could run that under indexer.sickerage.tv off course ;)

-----Original Message-----

**Comment by OmgImAlexis** [comment]
@WebSpider I've still got a copy of the last backup they posted publicly.

**Comment by WebSpider** [comment]
Ok, the application too by any chance? ;)

-----Original Message-----

**Comment by OmgImAlexis** [comment]
I wish, the whole backend would need to be recreated. If this was something that was actually wanted it wouldn't be too hard to get a quick node backend setup with redis at least then we'd have our own...

**Comment by OmgImAlexis** [comment]
Looks like I must have deleted the one from tvrage. :cry: all I can find is my copy of the "thetvdb" api dump.
