### ISSUE TITLE
Deleting a show (files including) causes flood of error messages

### ISSUE THREAD

**Issue by forkless** [SiCKRAGETV/sickrage-issues#2654]
Deleting a show from the details page of said show is causing a flood of errors (20.000 lines per day)

2015-09-05 01:55:58 Thread-77 :: No Show Object found for show with indexerID: 277169

The show is physically removed from the storage however the database still seems to think it's there I guess.

**Comment by fernandog** [comment]
remove this show with thetvdb or tvrageid 277169 from trakt. It's no longer a valid ID in the indexer

**Comment by forkless** [comment]
I don't have Trakt active, nor is it on my Trakt library.
