### ISSUE TITLE
[Feature Request] Move mako to inheritance model

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2657]
If we move from what we've got now it'll help a LOT with theming and it'll also mean cleaner code.
Have a look [here](http://docs.makotemplates.org/en/latest/inheritance.html) for what I mean.

Basically what we'll have something called `main.mako` in a layouts directory and we'd reference it and override it for every page.
````
## home.mako
<%inherit file="./layouts/main.mako"/>

<%block name="header">
    this is some header content
</%block>

<%block name="scripts">
    <script type="text/javascript" src="/js/file.js"></script>
</%block>

this is the body content.
````

````
## main.mako
<html>
    <body>
        <div class="header">
            <%block name="header"/>
        </div>

        ${self.body()}

        <div class="footer">
            <%block name="footer">
                this is the footer
            </%block>
        </div>
        <script type="text/javascript" src="${sbRoot}/js/lib/jquery-1.11.2.min.js?${sbPID}"></script>
        <script type="text/javascript" src="${sbRoot}/js/lib/bootstrap.min.js?${sbPID}"></script>
        <script type="text/javascript" src="${sbRoot}/js/lib/bootstrap-hover-dropdown.min.js?${sbPID}"></script>
        <script type="text/javascript" src="${sbRoot}/js/lib/jquery-ui-1.10.4.custom.min.js?${sbPID}"></script>
        <%block name="scripts">
        </%block>
    </body>
</html>
````

I've only just read over this so I could be mistaking how this works @miigotu @WebSpider can one of you confirm I'm right or wrong?

**Comment by miigotu** [comment]
@OmgImAlexis yes eventually we want to move to that. at first it was "just make it work"

**Comment by OmgImAlexis** [comment]
Well if this works like I described I'd be happy to move everything from including inc_top and inc_bottom to this. The main reason I want this is for theme development(WOO!) and so I can get the js using blocks meaning we can add js to any file and it'd automatically be added to the bottom just by putting it in the `<%block name="scripts"></%block>` section.

**Comment by MGaetan89** [comment]
We could also use the `%def`  instructions to reuse components (se the PR about custom qualities).

**Comment by WebSpider** [comment]
Yes, this is the way forward for me is well. Just have to make theme developers understand that they have to follow this way of working as well, to prevent spaghetti. When a new feature is exposed to the GUI, it should be inheritable first, after which a theme can pick up on the inheritance, instead of the other way around.

Also: Currently the code for theme selection is based around the file system path. We should do a short evaluation if this is still the best way forward.

**Comment by OmgImAlexis** [comment]
@WebSpider @miigotu and I were talking about file paths for themes and we're still not sure what the best way to go about it would be.

We really need a discussion on the directory structure for themes.

**Comment by miigotu** [comment]
@WebSpider :+1: 

@OmgImAlexis and I have been discussing this for awhile now, not sure if you heard much of it.
1. Newly created themes need to be able to use existing base images/js/css, but also override them and use their own, or parts of the base css/js and override it with customizations without touching the base files

We discussed eliminating the "slick" folder and moving all subfolders up a level, and then renaming "default" to slick. We are unsure if this is the best option to acheive point 1 ^

@OmgImAlexis is working on some changes to the folder layout now, so hopefully this works out.

**Comment by miigotu** [comment]
Tbh, its starting to feel like the entire folder layout, and theme loading needs reworked, as well as the backend code in webserveInit for the staticHandler.

**Comment by OmgImAlexis** [comment]
Inheritance and a new image loading function seem to help.

Before: ![screen shot 2015-09-05 at 8 45 05 pm](https://cloud.githubusercontent.com/assets/6525926/9698992/059d4b90-540f-11e5-9ac5-b7b18d26aab5.png)

After: ![screen shot 2015-09-05 at 8 43 24 pm](https://cloud.githubusercontent.com/assets/6525926/9698987/dbcf40f2-540e-11e5-924b-55a312ec50eb.png)

**Comment by fernandog** [comment]
nice
