### ISSUE TITLE
[Feature Request] Add socket.io/websocket api

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2658]
If we added in a socket.io/websocket api as well as the normal api then we wouldn't need to poll for new messages and waste bandwidth and loading time. We also wouldn't need to refresh the page every 5 minutes like we currently do.

**Comment by WebSpider** [comment]
Duplicate of your own #2586

**Comment by OmgImAlexis** [comment]
Oops. Didn't think I had opened an issue on this yet.
