### ISSUE TITLE
Problem with IPTorrents

### ISSUE THREAD

**Issue by Darksci** [SiCKRAGETV/sickrage-issues#2659]
So I think this started ever since ISPs started blocking some of these sites.
I am on the master branch and whenever it tries to connect to IPT it gives this error in the logs:

SEARCHQUEUE-MANUAL-73141 :: [IPTorrents] :: Unable to connect to IPTorrents provider: error [SSL: SSLV3_ALERT_ILLEGAL_PARAMETER] sslv3 alert illegal parameter (_ssl.c:581)

So I am unable to connect to grab any information. I have tried switching SSL verify ON and OFF but that doesn't do anything.

**Comment by miigotu** [comment]
Update your distro if it is linux. This problem was fixed in 2012.

If you are on windows, install newer version of OpenSSL.

**Comment by coolius** [comment]
I'm also getting this error with Ubuntu Server 14.04 LTS which is only a year old. Is there anything else that could be causing it?

**Comment by Darksci** [comment]
I am on Windows but I never had OpenSSL installed. It only stopped working after the ISPs started blocking some of the sites.

**Comment by coolius** [comment]
interestingly TorrentDay still works through Sickrage even though I cannot access it in my browser. IPT does not work in either.

**Comment by Darksci** [comment]
I am not the only one I see. Is there anyway I can check the code to see the endpoint for IPT?

**Comment by miigotu** [comment]
sickbeard/providers/iptorrents.py

**Comment by Darksci** [comment]
Ok checking the endpoint it seems its using "https://iptorrents.eu/torrents"
This is blocked. The alternative is "https://ipt.rocks/torrents"

**Comment by Darksci** [comment]
Do I need to recompile the python file?

**Comment by Darksci** [comment]
Ok great. So I removed the compile file and changes the source file: 
iptorrents.py

        self.urls = {'base_url': 'https://ipt.rocks',
                'login': 'https://ipt.rocks/torrents/',
                'search': 'https://ipt.rocks/t?%s%s&q=%s&qf=#torrents',
        }

Restarted the service. Service recompiled the file.
And now its connecting to IPT with no problem.

**Comment by WebSpider** [comment]
This may be blocked for you, but not for me..

-----Original Message-----

**Comment by Darksci** [comment]
I know, but IPT are aware that ISP's have blocked them, which is why they released another domain.

**Comment by miigotu** [comment]
This is already a feature request to allow selecting the url from a dropdown or overriding it via a text input box.

**Comment by coolius** [comment]
is this #1381? Is there a timeline when this can be expected? It is only going to get worse with more and more ISPs blocking torrent sites and people moving to mirrors.

**Comment by miigotu** [comment]
Yes, any further discussion/updates should be in #1381
