### ISSUE TITLE
Pushover sound still resets to default after update

### ISSUE THREAD

**Issue by Talung** [SiCKRAGETV/sickrage-issues#2663]
BRANCH: (master) / COMMIT: (f8eedd203011de46f61e7725cacd33de2146439c) 

This is a continuation of  issue #2529  Not sure how to get it re-opened, so created a new issue.
https://github.com/SiCKRAGETV/sickrage-issues/issues/2529

After update it is still defaulting to the "Pushover" sound and not the sound I selected. The "Device Specific" sound is working as expected.

ie. Main issue not fixed.. additional feature is working though.

**Comment by WebSpider** [comment]
Hi Talung,

Just to get a good understanding: Basically the only sounds that are working are Pushover and Custom, right?

Just so I know what to try and reproduce


-----Original Message-----

**Comment by Talung** [comment]
Sorry was sleeping.

It doesn't matter what sound you select. they all work.  However, after an update, it will always default to the "Pushover" sound.  After seeing the "Fix typo prevents sound from saving..", I tried just restarting sickrage and can confirm that it does the same thing.

So nothing to do with update and all to do with saving/loading the sound selecting in the config.ini.

Thanks

**Comment by WebSpider** [comment]
The fix hasn't been committed yet, where did you try it from?

**Comment by Talung** [comment]
Not tried it.. just confirmed that it was a saving/loading issue and not due to the upgrade system.  Sorry for the confusion.  ie.  A restart resets it on BRANCH: (master) / COMMIT: (f8eedd203011de46f61e7725cacd33de2146439c)

**Comment by WebSpider** [comment]
Hi @fernandog is there a reason why u closed the issue without merging into sickragetv/develop? Is there a problem with the PR?

**Comment by OmgImAlexis** [comment]
@WebSpider isn't it already merged? https://github.com/SiCKRAGETV/SickRage/commit/e07f4028d3c12dd34bf747a7e214c1aba0c867ed

**Comment by WebSpider** [comment]
Ah, it is indeed! More coffee.
