### ISSUE TITLE
Episodes change from Wanted to Skipped at midnight on some episodes. 

### ISSUE THREAD

**Issue by fatgeek** [SiCKRAGETV/sickrage-issues#2664]
I have a strange issue where on some shows the episode status will change from wanted to skipped at midnight on it's air date. This doesn't happen for all shows. It also isn't consistent per show. It was happening to all shows prior to the update on 2015-07-16. I made the changes required by that update, changing the default status. 

I did some searching and can't find anyone else with this issue. Let me know if you need logs or anything and I'll follow up.

**Comment by WebSpider** [comment]
It would be great if you could follow the guidelines on how to submit an issue, so we have more relevant info to go on. Especially we're going to need debug info as SR makes this mistake, which may be difficult as it's intermittent.

**Comment by fatgeek** [comment]
Ok,

Branch: Master BRANCH: (master) 
Commit hash: COMMIT: (f8eedd203011de46f61e7725cacd33de2146439c) 
Your operating system and python version:
    OS: Ubuntu 14.04.3 LTS (server)
    Python: Python 2.7.6

As for the logs, I hadn't realized that they had wrapped and I didn't have any from the midnight timeframe. Here are the logs for about an hour before and after midnight:  https://gist.github.com/fatgeek/8ffe66be47f89b1c1907

I have a cron job running at midnight now that'll copy the logs, so I'll have the around midnight logs should someone need them.

**Comment by fernandog** [comment]
Increase log size in SR and/or number of log files

**Comment by SirDev** [comment]
Fatgeek, I don't have any logs either (turned them on now) but I have the exact same problem: some series are set to "skipped" on the air date, thus not automatically searching + downloading them. I've had this since july just like @fatgeek says. I will try and find logs that support this :)

Branch: BRANCH: (master) 
COMMIT: (5391476827cf369a2d16a4e7ee8128f47a75f74c)
Operating system: Raspbian
Python version: 2.7.3

**Comment by miigotu** [comment]
@SirDev please read the news page in SR navbar, about default ep status.

**Comment by SirDev** [comment]
This fixed my problem. Sorry for not reading the news. Thanks!

2015-09-23 13:52 GMT+02:00 miigotu <notifications@github.com>:

> @SirDev <https://github.com/SirDev> please read the news page in SR
> navbar, about default ep status.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/2664#issuecomment-142577184>
> .
>



-- 

*Erik J. Hoeksma*
