### ISSUE TITLE
Detecting Wrong Quality

### ISSUE THREAD

**Issue by elit3ge** [SiCKRAGETV/sickrage-issues#2665]
I have been running SickRage on another persons computer for a while now, computer shit itself had to reinstall windows etc etc. Now my issue I am having now is, when a show is downloaded it is either SD or DVD depending which is out. In the folders with the shows in them the shows are renamed to SD.TV or SD.DVD. When I have re added all the shows and SickRage has done a scan on the folders it is telling me that all my SD.DVDs are SD.TV. Hopefully this is easily fixed as SickRage is going to re download all the files again and write of the top of them.

Windows 7 x64
Master
Py Latest x64

**Comment by miigotu** [comment]
SB used to name files with those funky quality names, and SR did for a long time also. We dont anymore because it breaks stuff.

You could find a way to bulk rename in windows.

In linux it would be like:
```bash
find fileDir -type f -exec rename -nv 's/SD\.\(TV\|DVD\)/SD$1/' {} +
```

**Comment by miigotu** [comment]
I guess you could also manually change the status of each ep in SR also, and then do a rename from there.

**Comment by elit3ge** [comment]
@miigotu They were previously named by SickRage, for this person they hadn't used SickBeard at all.

**Comment by miigotu** [comment]
@elit3ge ` and SR did for a long time also. We dont anymore because it breaks stuff.`

**Comment by elit3ge** [comment]
@miigotu My bad, sorry. Found out they got alot of stuff from a person who still uses SickBeard. That explains alot.
