### ISSUE TITLE
Discovery shows rarely find matches, last year or so...

### ISSUE THREAD

**Issue by camxx** [SiCKRAGETV/sickrage-issues#2666]
At least three Discovery shows have begun to rarely find matches, starting around 12 months ago, SickBeard and SickRage both seem to suffer from this.

These shows include but are not limited to: Mythbusters, Street Outlaws, Fast 'n' Loud.

It seems that whatever convention most indexers follow to list this show differs from the convention TVRage and TheTVDB follow, this results in matches rarely (if at all) being found.

Enabling scene numbering and forcing a full update doesn't seem to help either - Xem integration not working?

**Comment by OmgImAlexis** [comment]
@camxx why is this closed?

**Comment by camxx** [comment]
Restarting the SickRage service caused *something* to fall in to place and I assume scene numbering kicked in.
