### ISSUE TITLE
Remove logout from menu when no login details are provided

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2667]

**Comment by WebSpider** [comment]
Since we only have one u/p combination, what would this add opposed to closing the browser?

**Comment by OmgImAlexis** [comment]
What do you mean? When you've got login details added you're required to login but if you don't there's no reason to have "logout" in the menu since you don't actually login in the first place.

**Comment by WebSpider** [comment]
I misread! Removing comment :)

**Comment by OmgImAlexis** [comment]
I'll probably add this after my PR gets merged into develop.
