### ISSUE TITLE
[APP SUBMITTED]: Thread-24 :: No Show Object found for show with indexerID: 73388

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2668]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-57-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@f8eedd203011de46f61e7725cacd33de2146439c
Link to Log: https://gist.github.com/a4daef311dce8e8ab8bf
### ERROR
```
Thread-24 :: No Show Object found for show with indexerID: 73388
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by OmgImAlexis** [comment]
I added Mythbusters and then removed it, something's not getting cleaned up after a show's removed.

**Comment by miigotu** [comment]
Seems it was still adding episode information when you removed it. low priority as it is much better than it used to be.

**Comment by OmgImAlexis** [comment]
I removed this about an hour after the show was loaded. It shouldn't still be adding anything, should it?

**Comment by miigotu** [comment]
depends if one of the sites we get meta from is timing out or answering slow.

**Comment by fernandog** [comment]
Info Cached?

**Comment by miigotu** [comment]
there was no cache, because your pr deleted it @fernandog lol

**Comment by fernandog** [comment]
I mean getURL.
we still sync with trakt watchlist isnt?

**Comment by miigotu** [comment]
@fernandog you are confusing me. deleting a show removes it from the watchlist
