### ISSUE TITLE
Manual Post Processing Missing

### ISSUE THREAD

**Issue by DJ747** [SiCKRAGETV/sickrage-issues#2674]
When using on a tablet there is no button to get to manual post processing anymore. I went on the PC and found the link to it and when typed in the page loads fine, just doesn't have the button to get to it.

Thanks

**Comment by fernandog** [comment]
screenshot?

**Comment by MGaetan89** [comment]
Maybe related to https://github.com/SiCKRAGETV/sickrage-issues/issues/2618?

**Comment by miigotu** [comment]
@DJ747 this was already fixed in develop.
