### ISSUE TITLE
Manual search opens a new tab instead of keep in same page

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#2677]
Result is: {"result": "success"}

@MGaetan89 @OmgImAlexis

**Comment by MGaetan89** [comment]
I don't understand the issue and how to reproduce it.
Can you detail a bit?

**Comment by fernandog** [comment]
Press manual search for any episode in /comingepisodes

Didnt check MS in Displayshow

**Comment by OmgImAlexis** [comment]
@fernandog testing on https://github.com/SiCKRAGETV/SickRage/commit/8cacddbcb155352142744e87ac681759beaf363b the manual search at the end of each row seems to work just as it always did. Maybe we need some more info on this?

**Comment by fernandog** [comment]
@OmglmAlexis

https://www.dropbox.com/s/4owg9kavaw937oq/SCR_20150907_113503.mp4?dl=0

**Comment by OmgImAlexis** [comment]
Ah, got it.

**Comment by fernandog** [comment]
working. thanks
