### ISSUE TITLE
Return page info via JSON

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2679]
@MGaetan89 When you're done with the API stuff let me know and I'll do this, basically we'd just use the api to check things like what layout the user has selected, etc. and then we can do logic in javascript instead of having crap like this in the mako files.

````
% if not sickbeard.SORT_ARTICLE:
            return (s || '').replace(/^(The|A|An)\s/i, '')
% else:
            return (s || '')
% endif
````

**Comment by MGaetan89** [comment]
No problem.
I think this will rather be new classes in `sickrage.*` module, rather than a specific API, as it is UI related and not feature related.

**Comment by OmgImAlexis** [comment]
Sounds good, if possible could we expose the same data from mako to api endpoints? For example everything the home.mako gets we also get access to via js under a /home/ endpoint?

This would help not only with the current js but also if we ever wanted to move to a single page app like CP.

**Comment by MGaetan89** [comment]
Technically, we can do everything we want :)

**Comment by OmgImAlexis** [comment]
@MGaetan89 would it be possible for you to add a something to each page where if we send a header asking for html we get that like normal but if we send one for JSON we get that back instead? This way we can just use a normal get request to the current page and get back a reply that we can work easily with.

**Comment by MGaetan89** [comment]
Should be possible.
