### ISSUE TITLE
[Feature Request] Allow link between snatched and download

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2681]
This is a bit hard to explain, if a show gets snatched with a unknown quality and after the download finishes it detects SDTV, or other quality for that matter, either by its size or by the resolution the snatched and downloaded wont appear linked

**Comment by duramato** [comment]
![captura de ecra de 2015-09-07 19 38 13](https://cloud.githubusercontent.com/assets/10121067/9721695/2c700d5e-5598-11e5-9f44-308b9ff122aa.png)
SS of what im talking , look at the last 2 the snatched and the downloaded arent on the same line (like the ones on the Black Ops show for example)

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
