### ISSUE TITLE
Error shuttung down SR in terminal.

### ISSUE THREAD

**Issue by miigotu** [SiCKRAGETV/sickrage-issues#2683]
```
Traceback (most recent call last):
  File "./SickBeard.py", line 522, in <module>
    SickRage().start()
  File "./SickBeard.py", line 374, in start
    time.sleep(1)
  File "/home/dusted/Projects/SickRage/sickbeard/__init__.py", line 1579, in sig_handler
    if isinstance(signum, None):
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types
```

@MGaetan89 is this from you? xD

**Comment by fernandog** [comment]
Did I close this?!  Sure not

**Comment by MGaetan89** [comment]
It happens to me as well sometimes. When I update my fork, GitHub closes
some issues if the commit message is "Fix #someIssueID"

**Comment by miigotu** [comment]
Because you have develop set as your default branch. When a person with committer rights on the repo pushes a commit with a message like that to their default repo it closes it. (GitHub "Feature")

I name issues like that so that when I merge to master it autocloses the issues fixed in that release.
