### ISSUE TITLE
Can't access WebUI interface after a while

### ISSUE THREAD

**Issue by psychiktv** [SiCKRAGETV/sickrage-issues#2684]
BRANCH: (master) / COMMIT: (f8eedd203011de46f61e7725cacd33de2146439c) 
Python Version:	2.7.9 (default, Feb 10 2015, 03:28:08) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]

It started yesterday after adding a new show, wayward pines, then I am only able to access the webui a short period of time after having rebooted SR via the terminal. but every other background activities are still working
https://gist.github.com/psychiktv/2af44f1e1cb15c7c1106

**Comment by flightlevel** [comment]
TVRage has closed down recently. Highly likely its related to TVRage going by your log. 
Looks like a fix for TVRage isn't too far away https://github.com/SiCKRAGETV/SickRage/pull/2443

**Comment by WebSpider** [comment]
There is a temporary fix in develop which just ignores TVRage shows.

Maybe you can port it to master @fernandog ?

-----Original Message-----

**Comment by miigotu** [comment]
Will be merging develop to master sometime tonight. Fixed in develop.
