### ISSUE TITLE
Clear API documentation on the wiki

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2686]

**Comment by MGaetan89** [comment]
I was planning on reworking the API builder some day.
Something with a proper documentation (maybe like [SickBeard](http://sickbeard.com/api/)) and an example of request and response.

**Comment by OmgImAlexis** [comment]
@MGaetan89 either we could do something they did or use a site like readthedocs.org either way we need something better than the apibuilder because as it stands it's ugly and not really user or developer friendly. Also document will help for when we make changes as we would be able to list if a command, etc. has changed between major versions which would help people that use it update their code easier.

**Comment by OmgImAlexis** [comment]
I was thinking we could also if possible redo the api structure to something a little more uniform such as ``/api/cmd/command_here?other_needed_stuff&api_key=api_keyhere`` then we could use ``/api/views/home?session_key=session_key`` to have access to the layout api as I suggested before.

**Comment by miigotu** [comment]
We can't change the way the api currently works, or the command names.

We can add to it, make command alias' (I dont like that we have to use sb. prefix for some) or make another way of accessing it as long as the original one still works properly.

There are a lot of plugins, apps, etc that work by using the api, and some were not even designed for use with SR, only for SB.

**Comment by OmgImAlexis** [comment]
@miigotu we can, it's just not the best idea... We're going to have to eventually since the way it's laid out at the moment is just plain wrong and doesn't really help with future development. Like I said if we get documentation going and it breaks apps, etc. then at least the developers will be able to workout how to fix it.

**Comment by WebSpider** [comment]
If we're not happy with the current API, we imo should create an apiv2 and deprecate this one.

New features only get corresponding API calls in the new API, and we encourage devs to switch over because the new API is better/faster/documented/nicer to apps, etc


-----Original Message-----

**Comment by OmgImAlexis** [comment]
@WebSpider that sounds like the best option. The old API seems just so hacked together.

**Comment by miigotu** [comment]
For now, noone may touch it while it and webserve are being refactored, or I WILL kill you.

Lets get the current projects finished and ironed out before we look ahead, and please don't touch anything someone else is working in atm xD.

I agree to make an api v2, and to deprecate the old one (but it needs to start intact for a long deprecation period)

**Comment by OmgImAlexis** [comment]
@miigotu how about once they're refactored we add in `/api/v2/` with all of the stuff I want added and then we can work on deprecating the old one, once it's basically no longer used we can move `/api/v2` to `/api/`?

**Comment by MGaetan89** [comment]
If we create a new API, we should use and keep the format `/api/v2/` so developers can explicitly decide which version they want.
When we create a new API version, we deprecate the old one, and remove it after some (long enough) time.
