### ISSUE TITLE
[APP SUBMITTED]: Thread-19 :: Checkout branch couldn't compare DB version.

### ISSUE THREAD

**Issue by Al-25** [SiCKRAGETV/sickrage-issues#2687]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-62-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@f8eedd203011de46f61e7725cacd33de2146439c
Link to Log: https://gist.github.com/8bfbaaf6f79b664898ad
### ERROR
```
Thread-19 :: Checkout branch couldn't compare DB version.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by OmgImAlexis** [comment]
Duplicate https://github.com/SiCKRAGETV/sickrage-issues/issues/2571

**Comment by Grimmoire0** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@37914618686ee70479da0fa4b2cca851fa49c5e2
Link to Log: https://gist.github.com/3441dfa255e118fc17fc
### ERROR
```
Thread-19 :: Checkout branch couldn't compare DB version.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
