### ISSUE TITLE
[APP SUBMITTED]: Thread-24 :: "/bin/git" rev-parse --verify --quiet "@{upstream}" returned : fatal: Upstream branch 'refs/heads/master' not stored as a remote-tracking branch

### ISSUE THREAD

**Issue by knarfje** [SiCKRAGETV/sickrage-issues#2688]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 09:20:02) [GCC 4.1.1]**
Operating System: **Linux-2.6.21.1-qnap-armv5tejl-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@bf2baf309bd01683fdc06d57ece0b89d53b4a180
Link to Log: https://gist.github.com/19df873266de90ad81d4
### ERROR
```
Thread-24 :: "/bin/git" rev-parse --verify --quiet "@{upstream}" returned : fatal: Upstream branch 'refs/heads/master' not stored as a remote-tracking branch
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by flightlevel** [comment]
@knarfje 
Are you still experiencing this problem?

**Comment by knarfje** [comment]
No I’ve solved this issue. The problem now is that apparently i’m using an older OpenSLL version.
I’ll have to upgrade my NAS to fix that.

Thanks for your response.
Frank
