### ISSUE TITLE
Custom Newznab Categorie Bug

### ISSUE THREAD

**Issue by wizzardking** [SiCKRAGETV/sickrage-issues#269]
Branch: Master
Last commit: 33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8
System: Qnap NAS
Python: 2.7

I have added two different Custom Newznab Providers and wanted to add some categories.
On the settings it has two fields for adding the categorie numbers, the left one is empty and on the right one i can only chose between 5030 and 5040.

For normal users 5030 and 5040 (SD TV & HD TV) is enaugh. But i want to Download german files, and those are in a categorie called "foreign". But i can not select this categorie. I have tried to manually change the config.ini file for the correct categories, but after that SR can not start anymore.
On the second provider it has two SDTV and HDTV Categories. One for german and one for english" but there i can also just select 5030 and 5040.

I would be realy happy if you could look in trough this or add a field for manually add categorie numbers.

**Comment by fernandog** [comment]
@wizzardking did you test the new develop update? Its fixed. Can you confirm?
