### ISSUE TITLE
[APP SUBMITTED]: SHOWQUEUE-ADD :: Check scene exceptions update failed. Unable to get URL: https://raw.githubusercontent.com/SiCKRAGETV/sr_tvrage_scene_exceptions/master/exceptions.txt

### ISSUE THREAD

**Issue by kumz14** [SiCKRAGETV/sickrage-issues#2690]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.3-RELEASE-p25-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@
Link to Log: https://gist.github.com/7c28aa854aff057a4a34
### ERROR
```
SHOWQUEUE-ADD :: Check scene exceptions update failed. Unable to get URL: https://raw.githubusercontent.com/SiCKRAGETV/sr_tvrage_scene_exceptions/master/exceptions.txt
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by WebSpider** [comment]
There is an error in the URL, this should be https://raw.githubusercontent.com/SiCKRAGETV/sr_tvrage_scene_exceptions/gh-pages/exceptions.txt

I suspect we won't be fixing this anymore, since TVRage has been shut down by it's owner and we're removing support for it.

**Comment by flightlevel** [comment]
@kumz14 
TVRage is now closed, If you update your SickRage, I reckon this should go away.
