### ISSUE TITLE
[Feature Request] Add pagination to history

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2691]

**Comment by WebSpider** [comment]
Maybe move this to feathub? :)

**Comment by miigotu** [comment]
Even contributors must follow rules! lol

**Comment by OmgImAlexis** [comment]
We need a tag for stuff devs are working on, that's why I hadn't removed this one.

**Comment by miigotu** [comment]
The idea is that even if it is your own FR, it should go on FH, to encourage us devs to go there more often and see the other requests.

Ofc as a dev it might end up being your own FR you work on first, and thats ok, but the principal reasoning for FH remains true for everyone.
