### ISSUE TITLE
[Feature request] Add a possibility to choose which rss feed to use for TV Shows and Anime

### ISSUE THREAD

**Issue by gabrielqduarte** [SiCKRAGETV/sickrage-issues#2692]
As an user, i think it would be nice to have the option to choose which rss feed to use to search for anime and TV Show, so that i can minimize the chances of getting incorrect shows or animes (with me, when sickrage download animes sometimes it happens to get the ep in the wrong language, thing that could be corrected simply by restricting which feed it should get animes, so that it doesn't try to search at, lets say, the pirate bay...)

**Comment by neoatomic** [comment]
@gabrielqduarte Sounds similar to https://github.com/SiCKRAGETV/sickrage-issues/issues/2245 could you add your request there, so we have all in 1 feature request.?

**Comment by gabrielqduarte** [comment]
Actually it really could be accomplished with selective search by provider, although i guess it would take longer for the user to configure.. 

I'm gonna post it there anyway :)

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
