### ISSUE TITLE
[Feature Request] Add anonymous statistic collection

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2695]
To workout what browsers and OSs we really need to focus on it'd help if we had some stats for install such as what OS they're running, the amount of RAM and their browser version.

**Comment by WebSpider** [comment]
If someone can write a collector for this, I can run it on the sickrage.tv forum host.

 

Van: X O [mailto:notifications@github.com] 
Verzonden: dinsdag 8 september 2015 20:31
Aan: SiCKRAGETV/sickrage-issues <sickrage-issues@noreply.github.com>
Onderwerp: [sickrage-issues] [Feature Request] Add anonymous statistic collection (#2695)

 

To workout what browsers and OSs we really need to focus on it'd help if we had some stats for install such as what OS they're running, the amount of RAM and their browser version.

**Comment by MGaetan89** [comment]
Which information do we want/need?
- OS type and version
- Browser type and version
- RAM

When do we want to get/send those information?
- When SickRage starts? I guess that would be the most appropriate option
- Every time SickRage is opened?
- Every page load? (I hope not, just listing it as a possibility)

**Comment by OmgImAlexis** [comment]
@MGaetan89 once a day on open, so we just log last date it was set and if it's hasn't sent it today send it. That should be enough to get basic stats going, the main thing I want to know is if we're able to update a lot of the js to only work with newer browsers, if we've got a lot of older ones then we're going to have to accommodate that.

**Comment by flightlevel** [comment]
Would also be good to know which Search Providers people are actually using. SR is supporting a LOT of different search providers,

**Comment by OmgImAlexis** [comment]
That too, @flightlevel I meant to ask are you a mod? Someone on IRC said you were a backup account of one of the mods. :confused:

**Comment by flightlevel** [comment]
Nope, definitely not a mod, just bored at work!

**Comment by OmgImAlexis** [comment]
Well welcome, glad you're helping out.

**Comment by duramato** [comment]
Will this info be available for the end users ?

**Comment by OmgImAlexis** [comment]
@duramato I'd like it to

**Comment by WebSpider** [comment]
You will only know browser type when a browser connects to the webui, so maybe upon login/session start report the browser?

-----Original Message-----

**Comment by WebSpider** [comment]
I dont see any good reason to keep this private, when sufficiently anonimized.

-----Original Message-----

**Comment by OmgImAlexis** [comment]
@WebSpider my idea would work, right? Use the webui to start it and just check if they've sent or not. This way we should get an update per user once a day - once a week.

**Comment by flightlevel** [comment]
Will we need another database table https://github.com/SiCKRAGETV/sickrage-issues/issues/2589 so that info like browser used or provider used can be stored and then transmitted at a certain frequency.
I think its better to transmit info periodically rather than login/session so that SR addicts don't bias the info. There has been times when I haven't touched SR for ages, not because I wasn't using it, just because it was doing its job smoothly in the background.

**Comment by OmgImAlexis** [comment]
Actually, that sounds like a good idea and maybe we could have a background thread for this. I'm sure adding another one from stats shouldn't be too hard.

**Comment by WebSpider** [comment]
A few concerns:

- Don't we slow down the UI too much when logging this info
- We need to keep the database impact limited, if at all
- Adding another thread will increase memory footprint again. With SR needing 2GB of RAM on my system at least, I think we eat enough memory

**Comment by OmgImAlexis** [comment]
@WebSpider we definitely need to look into fixing the threads then. There shouldn't be any reason SR uses that much. Mine only uses about 200MB of RAM even when processing loads of shows.

**Comment by MGaetan89** [comment]
One more data we could send: Python version.
So we know when we can move forward with minimum Python support.
