### ISSUE TITLE
TypeError: 'Undefined' object is not callable

### ISSUE THREAD

**Issue by ezar** [SiCKRAGETV/sickrage-issues#2698]
Error when accessing to config/notifications

BRANCH: (master) / COMMIT: (c9729676cdbd2af5b04337b239bb3a843f5feaa4) 
Python Version: 2.7.9 (default, Mar 8 2015, 00:52:26) [GCC 4.9.2]

Error:
/opt/sickrage/gui/slick/views/config_notifications.mako, line 39:
<h3><a href="${anon_url('http://kodi.tv/')}" rel="noreferrer" onclick="window.open(this.href, '_blank'); return false;">KODI</a></h3>
/opt/sickrage/gui/slick/views/layouts/main.mako, line 210:
/opt/sickrage/lib/mako/runtime.py, line 853:
callable_(context, *args, **kwargs)

**Comment by neoatomic** [comment]
@ezar Looks identical to https://github.com/SiCKRAGETV/sickrage-issues/issues/2696 . Could you add the details there so we have all in one place.?

**Comment by d00ziie** [comment]
I have the same issue: on the news version ofc.

Mako Runtime Error
Error !

TypeError: 'Undefined' object is not callable

<div class="component-group-desc"> <img class="notifier-icon" src="${sbRoot}/images/notifiers/kodi.png" alt="" title="KODI" /> <h3><a href="${anon_url('http://kodi.tv/')}" rel="noreferrer" onclick="window.open(this.href, '_blank'); return false;">KODI</a></h3> <p>A free and open source cross-platform media center and home entertainment system software with a 10-foot user interface designed for the living-room TV.</p> </div> <fieldset class="component-group-list"> <div class="field-pair"> <label class="clearfix" for="use_kodi">
/home/disk7/fenix/sickrage/gui/slick/views/config_notifications.mako, line 39:
<h3><a href="${anon_url('http://kodi.tv/')}" rel="noreferrer" onclick="window.open(this.href, '_blank'); return false;">KODI</a></h3>
/home/disk7/fenix/sickrage/gui/slick/views/layouts/main.mako, line 210:
/home/disk7/fenix/sickrage/lib/mako/runtime.py, line 853:
callable_(context, *args, **kwargs)
