### ISSUE TITLE
[Feature Request] Subtitles: option to disable Hearing Impaired subs

### ISSUE THREAD

**Issue by voidzero** [SiCKRAGETV/sickrage-issues#2699]
Addic7ed has subtitles for the hearing impaired that contain extras, for example '[Horse whinnying]". They also have subs without this.

It would be nice if SickRage allows to select a preference for either of these.

**Comment by neoatomic** [comment]
@voidzero Not sure if that would be possible as we relay on a third party app to download the subtitles. I'm sure @miigotu would be able to shed some light on that.

**Comment by miigotu** [comment]
subliminal has the option, just need to ad the ui option in SR.

**Comment by kcoyo** [comment]
Thanks for suggesting this feature!

To add to this thread, how does the module work? Does it download the most updated subtitle? I also use addic7ed. I notice that when a new episode comes out, sometimes the initial subtitles have capitalization and a few errors. Manually downloading the most updated subtitles have been my workaround.

**Comment by miigotu** [comment]
It downloads the best match for the video. The site only allows for one with each hash for each language in either hearing impaired or not, so it is always the most up to date one that matches.

If however you already have say eng subs for an episode, and it is updated on the site, SR is not searching for a new eng subtitle since you already have one.

**Comment by medariox** [comment]
If you are hearing impaired and don't want to wait for GUI option, you can modify this tiny bit of code: https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/tv.py#L1468-L1469

Just change "hearing_impaired=False" to "hearing_impaired=True" and it should download the hearing impaired version of the subtitles.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
