### ISSUE TITLE
[Feature Request] Add nzbclub/nzbindex/nzb.to Providers

### ISSUE THREAD

**Issue by wizzardking** [SiCKRAGETV/sickrage-issues#270]
Hi,

Is it possible to integrate the following Providers from the cytec SickBeard Fork to SickRage:
nzbclub
nzbindex
nzb.to

Nzbindex and nzbclub do not need an api or an account, so i think those would be really good to see them also in sickrage. Also nzb.to are invite only, but it is one of the best providers for german stuff.
And the providers are already written for sickbeard in the cytec fork.

https://github.com/cytec/Sick-Beard/

**Comment by fernandog** [comment]
@wizzardking it's available

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
