### ISSUE TITLE
SickRage WebUI not functioning after latest update

### ISSUE THREAD

**Issue by josurr** [SiCKRAGETV/sickrage-issues#2703]
chrome/Edge/FireFox reporting redirect loops on all websites used by SR.

http://pastebin.com/BTTK8NAE

Logs point at the webserv.py and the various files under /tornado as being the cause(s).

Tried backing up existing install directory and starting fresh with just the various .db files copied into the root of the new install directory and still unable to get into the WebUI.

**Comment by MGaetan89** [comment]
@miigotu The module `resource` may not exists on Windows. How can we check if it is available before using it? (It is used in `layouts/main.mako`)

**Comment by veen1981** [comment]
Same issue here after updating to latest commit. Still cannot access webUI in IE, Edge, Chrome or Firefox. Tried a clean install with no config, cache or DB copied and same issue.

**Comment by miigotu** [comment]
Fixing now. One sec.
