### ISSUE TITLE
Images not showing up in WebUI

### ISSUE THREAD

**Issue by brampower** [SiCKRAGETV/sickrage-issues#2705]
Hey guys,

Something went horribly wrong while updating so I decided to just remove my DB and Config.ini and start over.

When adding a show however, all of the images (banner, network logo etc) do not show up in the WebUI. They do get moved to cache/images, but for some reason the WebUI won't show them.

This is what my WebUI looks like:
![bug2](https://cloud.githubusercontent.com/assets/5423856/9749877/221c1aec-565f-11e5-9522-51558118510c.jpg)

An example of the image URL in the WebUI is: 
http://localhost:8081/showPoster/?show=266189&which=poster_thumb

When going to that URL directly in my browser I see the following:
![bug1](https://cloud.githubusercontent.com/assets/5423856/9749823/bb356b1c-565e-11e5-9935-1375a02fcbca.jpg)

My log file:
https://www.dropbox.com/s/agrj48iyj9ei7k5/sickrage.log?dl=0

Please let me know if you guys need anything else!

**Comment by OmgImAlexis** [comment]
@MGaetan89 that'd be the classes issue. This is being looked into.

**Comment by brampower** [comment]
@OmgImAlexis Okay, thanks! Anything I can do myself to temporarily fix this while waiting for an update?

**Comment by OmgImAlexis** [comment]
@brampower try deleting the cache directory and restart SR. Nothing else I can suggest, sorry.

**Comment by brampower** [comment]
@OmgImAlexis Tried that, unfortunately didn't work. No problem, looks like I'll have to wait for an update. Thanks again!

**Comment by OmgImAlexis** [comment]
Duplicate https://github.com/SiCKRAGETV/sickrage-issues/issues/2708
