### ISSUE TITLE
Error searching for new shows using all indexers

### ISSUE THREAD

**Issue by Nolsen84** [SiCKRAGETV/sickrage-issues#2706]
It looks like due to TVrage being down, when you search for a new show using the "all indexers"  option you get no results instead of just getting the tvdb results. In a side note, any idea what's going on with TVrage? Is been down for 3 or 4 days.

**Comment by flightlevel** [comment]
TVRage has closed down. If you update your SickRage, all your TV shows will automatically be converted to TVDB
