### ISSUE TITLE
[APP SUBMITTED]: 2

### ISSUE THREAD

**Issue by didyouexpectthat** [SiCKRAGETV/sickrage-issues#2710]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-2.6.32-40-pve-x86_64-with-debian-8.2**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@9df4588e371248751bd60c4c02a90ea979199f43
Link to Log: https://gist.github.com/4c62fa152594c42b86a2
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: error 2
```

Currently on master.
```
From https://github.com/SiCKRAGETV/SickRage
   f8eedd2..9df4588  master     -> upstream/master
   61043c0..f98726f  develop    -> upstream/develop
Updating f8eedd2..9df4588
```

Start up SickRage, noticed an error right off of the bat. 

---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by flightlevel** [comment]
Are you using SSL @didyouexpectthat ?

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:34:55) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-26-generic-i686-with-Ubuntu-15.04-vivid**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@378f9818cb06867f777fa06a5bb03fba469b8ebd
Link to Log: https://gist.github.com/017907d65f789aa554e3
### ERROR
```
Thread-17 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/supergonkas/SickRage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/home/supergonkas/SickRage/sickbeard/webserve.py", line 1295, in displayShow
    xem_numbering=get_xem_numbering_for_show(indexerid, indexer),
  File "/home/supergonkas/SickRage/sickbeard/scene_numbering.py", line 380, in get_xem_numbering_for_show
    xem_refresh(indexer_id, indexer)
  File "/home/supergonkas/SickRage/sickbeard/scene_numbering.py", line 480, in xem_refresh
    u'Looking up XEM scene mapping for show %s on %s' % (indexer_id, sickbeard.indexerApi(indexer).name,),
  File "/home/supergonkas/SickRage/sickbeard/indexers/indexer_api.py", line 49, in name
    return indexerConfig[self.indexerID]['name']
KeyError: 2

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by didyouexpectthat** [comment]
Yeah, I am using SSL (https) to access SickRage.

**Comment by flightlevel** [comment]
@didyouexpectthat 
Try without it, to see if thats what is causing it

**Comment by rmilyard** [comment]
I don't use SSL and getting same error.

**Comment by didyouexpectthat** [comment]
I didn't see mine again after rebooting the client with SSL turned on. I turned of SSL and still don't see my specific error. My output looks a little different than duramato's.

**Comment by flightlevel** [comment]
@rmilyard @didyouexpectthat 
Can you confirm issue is fixed with the latest update?

**Comment by WebSpider** [comment]
It also occurs if you use a provider/search engine that uses ssl

-----Original Message-----

**Comment by rmilyard** [comment]
Looks like it's fixed. Only think now is missing banners.

**Comment by didyouexpectthat** [comment]
I've been running on bb16d3a3e4d3462a73b944c6e7d9384798774ffd pretty much all day and haven't seen this error come back.
