### ISSUE TITLE
[Feature Request] Automated cache clearing

### ISSUE THREAD

**Issue by flightlevel** [SiCKRAGETV/sickrage-issues#2712]
Should there be an easier way to clear the cache for end users? eg. Some NAS devices you need to SSH in, not that easy for some. A button in the Config section for the user to clear the cache.

When updating, should all the cache (except images) folders be deleted as part of the update?

Should the mako and session cache folders be removed when the user restarts SR? First thing most people do when there is a problem is to restart and you would expect the session to reset with a restart.

Just ideas

**Comment by WebSpider** [comment]
It's something we need to do after starting first time when updated, and new since we cut over from cheetah to mako.
 
We can't do this while shutting down after git pulling, since the restart template is mako too, we'd be removing the leg we stand on.

-----Original Message-----
