### ISSUE TITLE
SR does not find nzb

### ISSUE THREAD

**Issue by Hobbabobba** [SiCKRAGETV/sickrage-issues#2713]
BRANCH: (master) / COMMIT: (5a102de0672f658e119f3d45135ca95355d7453b) 

I mark an episode as wanted, but SR doesn´t find a nzb on nzb megasearch and/or dog.
If i search manually from the same indexer,  i find some nzbs to match the criteria. Neither nzb megasearch nor my dog settings changed.

If I enter the indexer manually, SR will find the episode and snatch it.

Logs: https://gist.github.com/Hobbabobba/69e5ee29614c4a48d562

**Comment by neoatomic** [comment]
@Hobbabobba Did you donate to dognzb for a premium/VIP account.? 
Because a normal account is only a "trail" account for 10 days.

Need some more info about your config. And what show etc you are trying to download.

**Comment by Hobbabobba** [comment]
I am using SR on Synology and paid for a VIP account with dog. The settings for dog and nzb megasearch (adress and API key) are working on Couch Potato and headphones. Just SR has a problem.

I tried a manual search for Continuum S03E10 (and some other episodes from Walking dead, but the manual search for Continuum in logged). If I set die episode status to "wanted" it gives me the same problem "No needed episodes found"

**Comment by neoatomic** [comment]
@Hobbabobba  I dont see any dognzb searches in the log. Make sure you have enabled the provider and also daily and backlog search is enabled for dognzb.

For your Mega provider something weird is going on. Seems it doesn't return the correct data.

```
2015-09-09 08:33:09 INFO     SEARCHQUEUE-BACKLOG-258171 :: [mega] :: Tell your newznab provider to fix their bloody newznab responses
```

If you copy the below url into your web-browser and add the API key (where the ********** are) do you then get a result.?
(or even better is there a way to get an API for the developers to test.? Otherwise we are just guessing what go's wrong here.)

```
https://flask-oestringer.rhcloud.com/api?apikey=**********&season=3&maxage=466&cat=5030%2C5040&q=Continuum&limit=100&t=tvsearch&offset=0&ep=10
```

**Comment by Hobbabobba** [comment]
I copied the mega-Link into Chrome and got very strange results: around 10 hits, but no hits from "Continuum", just other shows. At least now i understand, why SR says no episode found...

How can I send you an API key to the mega indexer?

**Comment by neoatomic** [comment]
If its your private server than please generate a few api keys for the dev's. You can sent them to me with a pm on IRC. Dont think any of us has a nzbmegasearch provider in the list yet, and they come in handy for testing.

In case you only have your personal api key, than just hang on till @miigotu has some time to see if anything can be done from our side. (But as you might know he is currently working on some urgent fixes.)
