### ISSUE TITLE
Make runtime error TypeError: argument of type 'Undefined' is not iterable

### ISSUE THREAD

**Issue by konomimaster** [SiCKRAGETV/sickrage-issues#2714]
I'm on master, commit 5a102de0672f658e119f3d45135ca95355d7453b,  running on Synology NAS DSM 5.2-5592 Update 4 and python version 2.7.10-14.

I opened mass-update and tried changing settings for a number of series at once and i got a white screen with this message:

Error !

TypeError: argument of type 'Undefined' is not iterable

<% anyQualityList = filter(lambda x: x > common.Quality.NONE, common.Quality.qualityStrings) %> <select id="anyQualities" name="anyQualities" multiple="multiple" size="${len(anyQualityList)}"> % for curQuality in sorted(anyQualityList): <option value="${curQuality}" ${('', 'selected="selected"')[curQuality in anyQualities]}>${common.Quality.qualityStrings[curQuality]}</option> % endfor </select> </div> <div class="manageCustom pull-left"> <h4>Archive</h4>
/usr/local/sickrage/var/SickRage/gui/slick/views/manage_massEdit.mako, line 59:
<option value="${curQuality}" ${('', 'selected="selected"')[curQuality in anyQualities]}>${common.Quality.qualityStrings[curQuality]}</option>
/usr/local/sickrage/var/SickRage/gui/slick/views/layouts/main.mako, line 217:
/usr/local/sickrage/var/SickRage/lib/mako/runtime.py, line 853:
callable_(context, *args, **kwargs)

**Comment by OmgImAlexis** [comment]
I'll fix this in a bit when I fix the rest of the import and variable issues. Tag me if this doesn't get closed in the next 6 hours.

**Comment by yowser7** [comment]
https://github.com/OmgImAlexis: This has been happening to me as well

![screenshot from 2015-09-09 10 28 32](https://cloud.githubusercontent.com/assets/8518470/9764537/9e19eeca-56dd-11e5-8d88-c75b99af26d1.png)

**Comment by OmgImAlexis** [comment]
@yowser7 @konomimaster have you guys updated?

**Comment by konomimaster** [comment]
The update fixed it for me.
