### ISSUE TITLE
Update removes sickbeard.sh on QNAP NAS

### ISSUE THREAD

**Issue by DerRudi074** [SiCKRAGETV/sickrage-issues#2715]
Hi I'm using the following SickRage.qpkg:

http://tiny.cc/sick-rage

The package get's the latest version from GIT and installs it. It works fine until I do an update of SickRage. During the update the sickbeard.sh file is removed. This file is needed by the QNAP Nas devices to start SickRage after a server restart. 

Could you please change the update proces so it doesn't remove existing files? Or at least this file?

Thanks!

**Comment by neoatomic** [comment]
@DerRudi074 You need to use this package.

http://apps.qnap.community/11-community/17-qsickrage

Clearly there is something wrong with the package you are currently using. And we dont have control over how those packages are build/working.

**Comment by WebSpider** [comment]
When you change package, be sure to save your current config
Ini and sickbeard.db ... Put them back into the new package before starting it, and perform a full update.

**Comment by DerRudi074** [comment]
The suggested package doesn't work on ARM qnap's so I'm still using the version I have now... I don't mind copying back the sickbeard.sh after an update as long as it works :) Thanks for the help so far...

**Comment by WebSpider** [comment]
Unfortunately, the package is setup wrong, as sickbeard.sh should not be inside the SR git tree. 

Please contact the package creator/supporter on this, there is very little we can do from within SR, we need the source tree to stay predictible.
