### ISSUE TITLE
[Feature Request] Use PDTV as HDTV for Australian shows

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2716]
Australian shows are usually listed as PDTV which means they don't get picked up by SickRage. They only ones I've seen like this are the equivalent to HDTV, can we either add PDTV or when the show is listed as having Australia as the country we could search for PDTV for HDTV?

@miigotu

**Comment by duramato** [comment]
@OmgImAlexis does it the correct naming?
```SD TV

    File name contains PDTV or HDTV or DSR or TVRIP, and is xvid or x264 or h264, but not 720[i/p] or 1080[i/p]
    or;
    File name contains web.dl or webrip, or is xvid or x264 or h264, but not 720[i/p] or 1080[i/p]
```

```SD TV

    File name contains PDTV or HDTV or DSR or TVRIP, and is xvid or x264 or h264, but not 720[i/p] or 1080[i/p]
    or;
    File name contains web.dl or webrip, or is xvid or x264 or h264, but not 720[i/p] or 1080[i/p]
```

**Comment by miigotu** [comment]
I can add PDTV as an alias of HDTV in the regex like [ph]dtv, but the filename would still need 720p and [hx]264

**Comment by OmgImAlexis** [comment]
The files are showing up as SDTV, they're not really SD considering they're 576p which is classed as HD here and considering we're one of the one places that has PDTV released that should be fine.

**Comment by OmgImAlexis** [comment]
@miigotu test file. `The.Block.s11e02.WS.PDTV.x264.BF1.mkv`

**Comment by miigotu** [comment]
@OmgImAlexis so just need to remove the hr. from that regex I guess? Is that file really 720p?

**Comment by OmgImAlexis** [comment]
It's HDTV, 576p which is Australian HD(567p, 720p, 1080p).

**Comment by WebSpider** [comment]
Scene rules say it's not an alias, but a seperate category:

```
  Source Naming:                                                             ª
ª   - Valid source names are HDTV, AHDTV, PDTV, and DSR.                      ª
ª   - WS and FS tags are banned.                                              ª
ª   - Source Definitons:                                                      ª
ª     - 720p/1080i/1080p shall be tagged HDTV or AHDTV (depending on capture  ª
ª       method). In the case of upscaled content airing on HD channel, use    ª
ª       PDTV tag.                                                             ª
ª     - 576i/576p shall be tagged PDTV.                                       ª
ª     - 480i shall be tagged DSR.                                             ª
ª   - HD video taken from the decoded HD output of a set-top box (e.g.        ª
ª     component, DVI, HDMI) must be tagged in dirname as AHDTV. Decoded       ª
ª     output of PDTV or DSR sources is banned. Releases taken from a natively ª
ª     recorded transport stream shall be tagged as HDTV, PDTV, or DSR.        ª
ª     - AHDTV captures must be done at the native format of the channel, e.g. ª
ª       720p or 1080i.                                                        ª
```

**Comment by miigotu** [comment]
`- WS and FS tags are banned.`

**Comment by elit3ge** [comment]
@OmgImAlexis I wouldn't really class it as HD, half the time it's grainy. There is only 2 or 3 channels that are actually HD.

**Comment by OmgImAlexis** [comment]
@elit3ge most of the east coast gets 720p on their channels, also you can get grainy 1080p that's got nothing to do with it.

**Comment by elit3ge** [comment]
@OmgImAlexis I live in Wollongong, the only HD channels we get are SBS HD, ABC 24, 7Mate, GEM and ONE. To me these aren't the main channels people watch.

**Comment by OmgImAlexis** [comment]
@elit3ge 7, 9 and 10 all have 720p streams somewhere on the east coast as I've had shows popup in that quality with the logos still on the channels. There's also the versions they put online they're 720p - 1080p.

**Comment by flightlevel** [comment]
@elit3ge Yep
No HD on FTA in Aus. 70's reruns on second channels don't count.
Hopefully this changes next year http://mumbrella.com.au/government-set-to-allow-tv-networks-to-broadcast-their-primary-channels-in-hd-313029
The footy looks so much better in HD on foxtel
@OmgImAlexis 
All the main channels are terrible 576i
https://en.wikipedia.org/wiki/List_of_digital_television_channels_in_Australia

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
