### ISSUE TITLE
After update BRANCH: (master) / COMMIT: (5a102de0672f658e119f3d45135ca95355d7453b) 

### ISSUE THREAD

**Issue by jheredianet** [SiCKRAGETV/sickrage-issues#2718]
No images (posters) are being shown. In the Cache folder, I can see clearly that there are all the posters and banners images of the shows.

This is what I see in the log. I'm using Windows and Phyton 2.7

AATypeError: showPoster() got an unexpected keyword argument 'amp'
AA    result = function(**kwargs)
AA  File "D:\Apps\SickRage\sickbeard\webserve.py", line 272, in async_call
AA    result = self.fn(*self.args, **self.kwargs)
AA  File "D:\Apps\SickRage\lib\concurrent\futures\thread.py", line 61, in run
AA    exec('raise exc_type, exc_value, traceback', {}, locals_)
AA  File "D:\Apps\SickRage\lib\concurrent\futures\_compat.py", line 107, in reraise
AA    reraise(self._exception, self._traceback)
AA  File "D:\Apps\SickRage\lib\concurrent\futures\_base.py", line 359, in __get_result
AA    return self.__get_result()
AA  File "D:\Apps\SickRage\lib\concurrent\futures\_base.py", line 400, in result
AA    value = future.result()
AA  File "D:\Apps\SickRage\tornado\gen.py", line 807, in run
AA    results = yield self.async_call(method)
AA  File "D:\Apps\SickRage\sickbeard\webserve.py", line 257, in get
AATypeError: showPoster() got an unexpected keyword argument 'amp'
AA    result = function(**kwargs)
AA  File "D:\Apps\SickRage\sickbeard\webserve.py", line 272, in async_call
AATraceback (most recent call last):
AATypeError: showPoster() got an unexpected keyword argument 'amp'
AA    result = function(**kwargs)
AA  File "D:\Apps\SickRage\sickbeard\webserve.py", line 272, in async_call

**Comment by underdog79** [comment]
I have the same issue; SOME shows have their Poster, but not all. All the network icons are broken.
For one show the poster is broken, and if I click this show Sickrage logs the following error:

  2015-09-09 14:05:39 Thread-22 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 1295, in displayShow
    xem_numbering=get_xem_numbering_for_show(indexerid, indexer),
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/scene_numbering.py", line 380, in get_xem_numbering_for_show
    xem_refresh(indexer_id, indexer)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/scene_numbering.py", line 480, in xem_refresh
    u'Looking up XEM scene mapping for show %s on %s' % (indexer_id, sickbeard.indexerApi(indexer).name,),
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/indexers/indexer_api.py", line 49, in name
    return indexerConfig[self.indexerID]['name']
KeyError: 2

**Comment by neoatomic** [comment]
Problem is known. Please add the logs and other info to the issue below, so we have all in one place.
https://github.com/SiCKRAGETV/sickrage-issues/issues/2708
