### ISSUE TITLE
History page not displaying downloaded subtitles anymore 

### ISSUE THREAD

**Issue by medariox** [SiCKRAGETV/sickrage-issues#2719]
## INFO
Python Version: 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
Operating System: Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-45-generic x86_64)
Locale: UTF-8
BRANCH: master
COMMIT: 5a102de0672f658e119f3d45135ca95355d7453b

## ISSUE
The history page doesn't display the downloaded subtitles anymore, even tho the option is selected. The downloaded subtitles are still being logged as always, as I can see from the debug logs - they are just not being displayed. Should be easy to replicate and most probably OS independent.

This is the commit that might have broken the feature: https://github.com/SiCKRAGETV/SickRage/commit/cf7f70c0f541ad609c9fc074eb97460e29756f69

**Comment by anonvoy** [comment]
I can confirm that *the history page doesn't display the downloaded subtitles anymore, even tho the option is selected.*

**Comment by flightlevel** [comment]
@fernandog Do you use subtitles? If so, can you have a look

**Comment by fernandog** [comment]
I dont.
@duramato please?

**Comment by duramato** [comment]
@flightlevel ,@fernandog I believe I can confirm it as ive been getting notification but noting on the history page
But give 5 minutes to test it better

**Comment by MGaetan89** [comment]
I can check that. I refactored the history part, so I may have remove something without noticing it.

**Comment by MGaetan89** [comment]
I found the issue. I will fix it and submit a PR so it can be included in the next version.

**Comment by MGaetan89** [comment]
Fix pending: https://github.com/SiCKRAGETV/SickRage/pull/2474

**Comment by MGaetan89** [comment]
PR was merged.
The history page will be back to normal in the next version.
