### ISSUE TITLE
Subtitle selection is disabled automatically, disabling subtitle downloads

### ISSUE THREAD

**Issue by neojoe666** [SiCKRAGETV/sickrage-issues#2720]
Hello,

I just installed and configured sickrage, I was previously using sickbeard.

I have a problem with downloading french subtitles. I didn't have any problem with sickbeard.
For any subtitle I try to download, I get these messages :
2015-09-09 14:14:22 DEBUG    Thread-54 :: 249882: No subtitles found for S04E01 on any provider
2015-09-09 14:14:19 DEBUG    Thread-54 :: 249882: Downloading subtitles for S04E01

I tried for the same episode with sickbeard and no problem. I activated the plugins Addic7ed and Opensubtitles.
With sickbeard I had messages telling me on which provider it was looking for. Here it's like it didn't look on any.
Any idea ?

Thanks

**Comment by neojoe666** [comment]
I juste noticed that after going back to the home page and back in the subtitles plugins, they get unchecked !
I check again some plugins, save changes several times and it unchecks itself again later... It isn't always but I noticed it a few times.

**Comment by OmgImAlexis** [comment]
@neojoe666 can you open up your [browsers console](http://webmasters.stackexchange.com/a/77337/35889) and let me know if there's anything in there on the plugins page?

**Comment by neojoe666** [comment]
No, I don't see anything

**Comment by anonvoy** [comment]
Yes, the checks in the checkboxes of the subtitle plugins disappear mysteriously, even after checking them again. In my case, (English) subtitles are still downloaded though.

**Comment by fernandog** [comment]
@duramato do you have this too (above comment)?

**Comment by duramato** [comment]
@fernandog no i do not have that problem 
Does the log say anything after you check the box , and saved?

**Comment by anonvoy** [comment]
Cannot find anything. But feel free to look through https://gist.github.com/anonvoy/3842a43f864c9ff965b6#file-sickrage_log_anonvoy_201508-log :-)

**Comment by snow3461** [comment]
Hi there,

I can confirm the checkboxes disappearing and config.ini is modified, after a while (maybe after a baklog search, not sure).

When I check  the checkboxes for subtitles provider and click *Save changes*, I have the notifications in my web browser, but nothing appears in log files (normal?).

**Comment by duramato** [comment]
@fernandog just experienced this ,right after i removed a language from my subtitle settings

**Comment by fernandog** [comment]
@duramato 
probably a mako issue
can you easily reproduce it? what are the states before and after?

**Comment by duramato** [comment]
@fernadog at the subtitles setting page add/remove a language ,save refresh the page and go to the providers tab and they should be unchecked..

**Comment by fernandog** [comment]
when you remove ALL languages or when you remove one and keep another?

**Comment by duramato** [comment]
@fernandog if you remove 1 ,or even if you add one it unselects all providers

**Comment by WebSpider** [comment]
I cannot reproduce this on SiCKRAGETV/SickRage@f913285d1decce196c6054c43507582fb2a2a7ee, is this issue still valid?

**Comment by duramato** [comment]
@WebSpider yes it is

**Comment by miigotu** [comment]
@duramato Yep, confirmed.

Save languages and providers checked. refresh page. change languages and save. refresh. check providers.

**Comment by OmgImAlexis** [comment]
Is this still a problem after adding the config.js back?

**Comment by miigotu** [comment]
Fixed.
