### ISSUE TITLE
Slow to load Shows (Home) page

### ISSUE THREAD

**Issue by crazyasyou** [SiCKRAGETV/sickrage-issues#2723]
I have two SR installed one windows and one linux (both on well spec servers, so no CPU or RAM issues) they have both started to load the shows/home page very slowly on the last update. All other pages and tasks are near instant. Has something change on how the home page is built/collates information in the background?

**Comment by mgaulton** [comment]
I've noticed the same thing after update to latest

**Comment by fernandog** [comment]
what is the filesystem of windows and linux?
home page now gets the size of all shows.

**Comment by neoatomic** [comment]
Just tested and it loads fast here, but i have only 27 shows.
You could try to rename the cache folder and let SickRage build a new one, maybe something got bad there.

We are in the process of modifying the templates to speed them up and allow the implementation of a new theme.

**Comment by crazyasyou** [comment]
Already delete the cache folder (apart from images) before I posted with no effect. The file system for the windows 2008 server is NTFS and linux server is ext3 for the OS but the TV shows folder is a mount to another windows server with a NTFS file system. If the show/home page scans the filesystem everytime it loads to calculate the size that might explain it (seems odd it would not be scanned once and stored per show in the DB)

**Comment by fernandog** [comment]
We will do that in the future

**Comment by crazyasyou** [comment]
Thinking about the new show file size display would it be a good idea to capture the size of each episode during postprocessing or full scans and store it per episode in the DB so that when its needed all thats happening is a bit of DB query and math?

**Comment by mgaulton** [comment]
@fernandog I'm on a linux system, remotely accessing a NAS with a few hundred shows :) Can I disable that lookup?

**Comment by fernandog** [comment]
@mgaulton how much time does it take to load?

**Comment by mgaulton** [comment]
Honestly, more than 2 minutes that i know of, i was getting distracted
after that and just letting it run in the background. I can try it and
give you something more accurate in a bit.

**Comment by fernandog** [comment]
please do. and let us know

**Comment by mgaulton** [comment]
Just to be sure, i performed and update to below.
SickRage Updated To Commit#: 8abad2c4fc72f1610881aea9c2520ce4175911ab

I then started the load and it seems much better now.

**Comment by OmgImAlexis** [comment]
@fernandog we'll get the stats enabled for all users ASAP. I have a feeling this is the size lookup, it's being done on every page load and with just 100 shows added about 200ms - 300ms of load time with fast NAS drives. If yours are a tad slower or you've got a load of shows then this will be a lot worse. @MGaetan89 maybe we can disable the column for now until it can be added to the database?

**Comment by fernandog** [comment]
I would add as an option for now.

**Comment by miigotu** [comment]
@OmgImAlexis the size column is definitely the cause. it all depends on the file system. On a new age file system, getting total size is just done by counting through some pointers, on fat32/ntfs is is much more involved. Please disable this column in code, until we have the total_size column in the DB on the next DB upgrade.

**Comment by OmgImAlexis** [comment]
Can we either pull my changes and test or can someone with 200+ shows or a fat32 install try https://github.com/SiCKRAGETV/SickRage/pull/2470 for me?

**Comment by mgaulton** [comment]
FYi this caused a marked improvement for loading
