### ISSUE TITLE
Item processed with wrong episode number

### ISSUE THREAD

**Issue by pyr02k1** [SiCKRAGETV/sickrage-issues#2724]
Not sure why it's occurring, and I've only noticed happening on Portlandia at the moment and I haven't checked through others just yet. I've disabled automatic processing at the moment, at least until I have a moment to test further.

System is Debian 8 running ZFSonLinux for storage side. No issues with anything else server side. System is reasonably up to date (within the last 3 days or so).

```
SR Version: 	BRANCH: (master) / COMMIT: (9edd012e9ab013265b3631706e3aea5673146ae4)
SR Locale:	('en_US', 'UTF-8')
SR Config file:	/usr/share/sickrage/config.ini
SR Database file:	/usr/share/sickrage/sickbeard.db
SR Cache Dir:	/usr/share/sickrage/cache
SR Log Dir:	/usr/share/sickrage/Logs
SR Arguments:	['-q', '--daemon', '--nolaunch', '--pidfile=/usr/share/sickrage/sickrage.pid', '--datadir=/usr/share/sickrage']
Python Version:	2.7.9 (default, Mar 1 2015, 12:57:24) [GCC 4.9.2]
```

Please ignore the RAR errors. The files are already unpacked
https://gist.github.com/pyr02k1/15b68750c9672687a029
GIST above is Logs for Ep 3x1 and 3x11 from manual post process as well as debug logs from 3x1 and 3x11.

I'll have to update in a bit with whether this is the only show affected by this

**Comment by pyr02k1** [comment]
Quick follow up, as promised. 

Lost Girl, single episode in it's own folder, no issues. Brooklyn Nine-Nine, same layout as Portlandia (Main Downloaded Folder > Season Subfolder > Episode Subfolder), no issues.

Reran Portlandia 3x11 with nothing inside of the subfolder (No Subs, Proof or Sample subfolders and no rar files), same result, processed as 3x10.
https://gist.github.com/pyr02k1/8b436c3758d0efcdb950

**Comment by miigotu** [comment]
Scene numbering.....

**Comment by pyr02k1** [comment]
If it's all right with you... I'm going to go stick my head in a bucket now. Thanks for pointing out my blindness. Must have hit that when adding it yesterday.

**Comment by miigotu** [comment]
ok lol.
