### ISSUE TITLE
No images after updating

### ISSUE THREAD

**Issue by TheClaus** [SiCKRAGETV/sickrage-issues#2725]
BRANCH: (master) / COMMIT: (9edd012e9ab013265b3631706e3aea5673146ae4) 
Windows 10 / Python 2.7.10(64bit)
I was 166 commits behind and updated to latest master build and now I see no images for shows.  Everything shows broken image thumbnail.  Have done all the steps before submitting the bug.  

https://gist.github.com/fc2eb0db96d056ac2cef.git

**Comment by duramato** [comment]
@TheClaus Is it still happening ? if not try and update the shows

**Comment by TheClaus** [comment]
Updated and issue resolved.  Thanks
