### ISSUE TITLE
Problem sending to tracker

### ISSUE THREAD

**Issue by Tazer** [SiCKRAGETV/sickrage-issues#2726]
Having some problems with latest version: 8abad2c4fc72f1610881aea9c2520ce4175911ab

 qbittorrent: Unable to send Torrent: Return code undefined

**Comment by flightlevel** [comment]
@Tazer 
There was a problem with some providers, but now fixed.
Can you update to the latest version, restart qbittrorent and report back with the results

**Comment by Tazer** [comment]
Still same result @flightlevel , any clues ?

**Comment by fernandog** [comment]
@Tazer please make sure that torrent isn't already in the client. we can't handle this for now as the client doesn't reply a correct return code.

**Comment by Tazer** [comment]
@fernandog Tried to clear all of the torrents from qBittorent (3.2.3) still same error, Is there some log I can check, to see more details about the error ? (or enable some debugging on qBittorrent maybe)

**Comment by fernandog** [comment]
Need full logs as mentioned here:

https://github.com/SiCKRAGETV/sickrage-issues

**Comment by Tazer** [comment]
Feels lik it's not giving much (have turned on debug logging)

https://gist.github.com/Tazer/ae5ee86905c7558224c5 , it just says the error.

**Comment by Tazer** [comment]
Solved my problems with just using drop folder
