### ISSUE TITLE
[APP SUBMITTED]: [Errno 111] Ligação recusada

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2727]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:34:55) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-26-generic-i686-with-Ubuntu-15.04-vivid**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@0af10956fd818520c7a551b628557b978b4e1e02
Link to Log: https://gist.github.com/a43609331e040ccbcd5c
### ERROR
```
Thread-13 :: error 111 : Ligação recusada
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by OmgImAlexis** [comment]
English: Connection refused

**Comment by miigotu** [comment]
aka you are spamming the issue submitter too damn much.
