### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-MANUAL-272127 :: [HDTorrents] :: Could not find table of torrents mainblockcontenttt

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#2729]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.1.5-1-osmc-armv7l-with-debian-8.2**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@7bab0f59ef98d490b89efcf79130687e758d3769
Link to Log: https://gist.github.com/1132c1dc122e904b1d5b
### ERROR
```
SEARCHQUEUE-MANUAL-272127 :: [HDTorrents] :: Could not find table of torrents mainblockcontenttt
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Can we close this as a pr was merged.?
