### ISSUE TITLE
[Feature Request] Backup location

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2730]
Add the ability to set a path for the backup on update to be saved

**Comment by fernandog** [comment]
I wouldnt change this (permissions, mounting, FS issues)
You can choose path of manual backup

**Comment by OmgImAlexis** [comment]
Also the ability to have backups emailed to you would help.

**Comment by WebSpider** [comment]
I prefer to offer the backup as download via browser as alternative. Sending via email is a bad idea, email is not meant for file transfers.

**Comment by OmgImAlexis** [comment]
@WebSpider email shouldn't be too hard and for people like me that use a spare gmail account for backups like this it'd be a nice feature. Currently all of my emails get zipped from my main account and emailed to my backup gmail to store incase of emergency adding Sickrage to that would be great.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
