### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'mount'

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2732]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:34:55) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-26-generic-i686-with-Ubuntu-15.04-vivid**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@f15adac877b6f4c7f434f734ecf6824e87675ddc
Link to Log: https://gist.github.com/e3f169680dace8d48a89
### ERROR
```
SEARCHQUEUE-MANUAL-75340 :: [AlphaRatio] :: Unable to connect to AlphaRatio provider.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by mescribe0** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.2**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@bb16d3a3e4d3462a73b944c6e7d9384798774ffd
Link to Log: https://gist.github.com/4a1d5a9d120c76838226
### ERROR
```
SEARCHQUEUE-MANUAL-71663 :: [T411] :: Error while searching T411, skipping: 'NoneType' object has no attribute 'mount'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Grimmoire0** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@bb16d3a3e4d3462a73b944c6e7d9384798774ffd
Link to Log: https://gist.github.com/bdcff95d62add855ec84
### ERROR
```
SEARCHQUEUE-MANUAL-264492 :: [T411] :: Error while searching T411, skipping: 'NoneType' object has no attribute 'mount'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Grimmoire0** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@37914618686ee70479da0fa4b2cca851fa49c5e2
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-MANUAL-277462 :: [T411] :: Error while searching T411, skipping: 'NoneType' object has no attribute 'mount'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Grimmoire0** [comment]
the commit https://github.com/SiCKRAGETV/SickRage/commit/334d794cbffc83a3747a9598f06dd020d74ab49a#diff-2e6e70e7ccf840bb7c52a3a35ef2f47b introduce this error.

Rollback the "sickbeard/providers/t411.py" file, this error disapear.

**Comment by flightlevel** [comment]
@mescribe0 @Grimmoire0 
T411 is being looked at in this issue https://github.com/SiCKRAGETV/sickrage-issues/issues/2782
Keep this issue to Alpharatio
@duramato Are you still having problems with AlphaRatio

**Comment by duramato** [comment]
@flightlevel yes and with TNTvillage too

**Comment by miigotu** [comment]
Ugh, line 87 needs to be self.getURL, not helpers.getURL. making PR now.

**Comment by miigotu** [comment]
That t411 nonetype is fixed in master and develop. Dont know if it fixes the auth or not.

**Comment by mescribe0** [comment]
The fix works fine for me. Thanks.

**Comment by scoony** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-32-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@7694b70047796dc0c9c812300a090f78a4240f46
Link to Log: https://gist.github.com/02604ad65d966affc11d
### ERROR
```
SEARCHQUEUE-MANUAL-146711 :: [T411] :: Error while searching T411, skipping: 'NoneType' object has no attribute 'mount'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Grimmoire0** [comment]
Greats !! Works for me too ! Thx all
