### ISSUE TITLE
Error while searching IPT and TD

### ISSUE THREAD

**Issue by kendog819** [SiCKRAGETV/sickrage-issues#2734]
![image](https://cloud.githubusercontent.com/assets/11353628/9775908/3d5020e8-5721-11e5-9776-821f15015779.png)

![image](https://cloud.githubusercontent.com/assets/11353628/9775889/1106f3a4-5721-11e5-9be2-3872a13b5fdf.png)

**Comment by kendog819** [comment]
@miigotu 

What was done here? You put a fix tag, then closed it, and no responses?

**Comment by miigotu** [comment]
Because it is fixed, do I really need to be that social? xD

**Comment by kendog819** [comment]
![image](https://cloud.githubusercontent.com/assets/11353628/9791087/58515c0a-57a7-11e5-8533-6f7aca4f02e5.png)

Yes, being social could be helpful.

**Comment by miigotu** [comment]
I guess you should enable debug and/or check your username and password.

**Comment by kendog819** [comment]
Check my username/password..lol

`2015-09-10 10:19:41 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: Unable to connect to IPTorrents provider.
AA
AAAttributeError: '_socketobject' object has no attribute 'set_tlsext_host_name'
AA    cnx.set_tlsext_host_name(server_hostname)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 296, in ssl_wrap_socket
AA    ssl_version=resolved_ssl_version)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connection.py", line 238, in connect
AA    conn.connect()
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 762, in _validate_conn
AA    self._validate_conn(conn)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
AA    body=body, headers=headers)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
AA    timeout=timeout
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/adapters.py", line 370, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/cachecontrol/adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('POST', url, data=data, json=json, **kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 507, in post
AA    resp = session.post(url, data=post_data, timeout=timeout, allow_redirects=True, verify=session.verify)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1376, in getURL
2015-09-10 10:19:41 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: Traceback (most recent call last):
2015-09-10 10:19:41 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: Unknown exception in getURL https://iptorrents.eu/torrents/ Error: '_socketobject' object has no attribute 'set_tlsext_host_name'
AA
AAAttributeError: '_socketobject' object has no attribute 'set_tlsext_host_name'
AA    cnx.set_tlsext_host_name(server_hostname)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 296, in ssl_wrap_socket
AA    ssl_version=resolved_ssl_version)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connection.py", line 238, in connect
AA    conn.connect()
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 762, in _validate_conn
AA    self._validate_conn(conn)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
AA    body=body, headers=headers)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
AA    timeout=timeout
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/adapters.py", line 370, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/cachecontrol/adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 476, in get
AA    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1378, in getURL
2015-09-10 10:19:40 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: Traceback (most recent call last):
AANone`

**Comment by WebSpider** [comment]
SNI

**Comment by kendog819** [comment]
SNI ?

**Comment by miigotu** [comment]
try going to config/general on the advanced tab, and unchecked verify SSL certs. then stop SR and delete cache/sessions

**Comment by miigotu** [comment]
@kendog8 this is an error from qnap, not SR.

**Comment by miigotu** [comment]
also is this the right package? the one from qnap Stephanie?

**Comment by kendog819** [comment]
Idk who qnap stephanie is, Ive been running this package for 6 months though.

**Comment by kendog819** [comment]
And as stated in the other thread that you closed prematurely, SSL is unchecked.

**Comment by miigotu** [comment]
" closed prematurely" Dude, you are opening duplicate threads for something that is not a problem with SR. 

SEARCH THE ISSUES BEFORE YOU OPEN ANOTHER ISSUE.

back up, uninstall, install the qnap stephanie package (QSickRage), restore.
