### ISSUE TITLE
Restoring backup completes but still blank install.

### ISSUE THREAD

**Issue by ZMOT7S** [SiCKRAGETV/sickrage-issues#2738]
Branch: Master 
Commit hash: Not sure what this is. Explain and I will check.
Your operating system and python version: Linux (on seedbox) Not sure how to see the python version on seedbox either.
What you did: Loaded the zip file for the restore, it said click reset. I clicked reset and waited. It said restore successful. 
What happened: Nothing. It was the same default install.
What you expected: For my settings and info to be restored. 
Link to a copy/paste of your logfile with clear debug info of the error on GIST: https://gist.github.com/ZMOT7S/8f8cade4ae8840560ad7

**Comment by flightlevel** [comment]
@ZMOT7S 
Stop SickRage
Delete your cache folder
Copy the sickbeard.db and config.ini files from your backup zip to your sickrage folder so that the current one gets overwritten
Start SR

**Comment by ZMOT7S** [comment]
@flightlevel thanks for the info. That worked out great!!!

**Comment by flightlevel** [comment]
@ZMOT7S 
All your show data is in sickbeard.db - so that definitely worked.
All your settings are stored in config.ini. - something went wrong there.
Either it didn't copy across or there was a problem with the backup.
Try opening config.ini from your backup in notepad and just scroll down to see if your settings are there so we can see if the settings are actually there.

**Comment by ZMOT7S** [comment]
@flightlevel I do see my settings and login info, etc in the config file. It said the overwrite was successful but didn't show it in SickRage. I don't see any errors in the log.

**Comment by flightlevel** [comment]
@ZMOT7S 
That's the only place the settings can come from.
Stop SR, Delete the existing config.ini, copy config.ini from backup, start SR

**Comment by miigotu** [comment]
SR must be stopped before copying in the config.ini.

**Comment by ZMOT7S** [comment]
That seem to have worked. Thanks for the help guys. First major problem I've had in the months I've been using SR.

**Comment by fernandog** [comment]
@ZMOT7S tested a restore in linux and it worked.

did you setup SR to have database and config file to be insider sickrage folder or outside ?

**Comment by ZMOT7S** [comment]
@fernandog I don't remember setting it up but it is inside the main sickrage folder, no subfolder.
