### ISSUE TITLE
Indexer only includes the TVDB

### ISSUE THREAD

**Issue by erickgrau** [SiCKRAGETV/sickrage-issues#2739]
After last update, I now noticed I only have 1 indexer - some shows are no longer found since its missing the ragedb

**Comment by flightlevel** [comment]
@erickgrau 
TVRage has closed down. 
If you look in your log file, you'll be able to see which shows were converted from TVRage to the TVDB.
If a show is missing or incorrect, delete the incorrect show if needed and then add the show again (it will be added with TVDB as the indexer)

**Comment by erickgrau** [comment]
Thank you
