### ISSUE TITLE
Error when using nzbToMedia.py with Sabnzbd

### ISSUE THREAD

**Issue by josurr** [SiCKRAGETV/sickrage-issues#2740]
setup nzbToMedia as per Clinton's wiki, but receiving the following error in Sabnzbd when trying to use it for post-download processing:

http://pastebin.com/MwGkfX9b

let me know if there is more data needed

**Comment by WebSpider** [comment]
For support on nzbToMedia please go to http://github/clinton-hall/nzbToMedia

**Comment by flightlevel** [comment]
These might be helpful

https://github.com/clinton-hall/nzbToMedia/issues/477

https://github.com/clinton-hall/nzbToMedia/issues/603
