### ISSUE TITLE
[APP SUBMITTED]: Loaded module _opt_sickrage_gui_slick_views_home_mako not found in sys.modules

### ISSUE THREAD

**Issue by dedado** [SiCKRAGETV/sickrage-issues#2741]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.1.6+-armv7l-with-debian-8.2**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@bb16d3a3e4d3462a73b944c6e7d9384798774ffd
Link to Log: https://gist.github.com/9f6e97189ee9cb565857
### ERROR
```
Thread-13 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 715, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/opt/sickrage/sickbeard/webserve.py", line 113, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/opt/sickrage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/opt/sickrage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/opt/sickrage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _opt_sickrage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by flightlevel** [comment]
@dedado 

Have you tried clearing your cache?

-Find the location of your cache folder by going to Config -> Help & Info in SickRage
-STOP SickRage and give it a chance to shutdown
-Delete all the folders in the cache folder except images folder
-Start SR

Let us know the result

**Comment by flightlevel** [comment]
@dedado 

Update your SR before trying the above as well, you're on an older version

**Comment by dedado** [comment]
I will try to delete the caches and shutdown. Thanks for the quick support. I will let you know.

But I use the sick rage update tool to be on the head of the master branch. This issue only appears after the update. 

How can I be on the head release without switching to develop branch?

Thanks

**Comment by dedado** [comment]
I was on the head already. Removing the cache solved the problem. Thanks @flightlevel , you give very quick and efective support

**Comment by flightlevel** [comment]
That was good. When you update sometimes the cache can cause problems. A more permanent solution is being looked at

**Comment by firatuzman** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-45-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5391476827cf369a2d16a4e7ee8128f47a75f74c
Link to Log: https://gist.github.com/d25b3664276b2a5488ee
### ERROR
```
Thread-14 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 274, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 681, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/opt/sickrage/sickbeard/webserve.py", line 115, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/opt/sickrage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/opt/sickrage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/opt/sickrage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _opt_sickrage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by OmgImAlexis** [comment]
@firatuzman can you confirm the above fix works?

**Comment by firatuzman** [comment]
@OmgImAlexis I am getting this message recently after updating. I clear it and its gone. I don't see it anymore until a new update comes and I update.
Now I did as told. I can only confirm after a new update comes.

**Comment by OmgImAlexis** [comment]
@SiCKRAGETV/moderators this may be a bug.

**Comment by flightlevel** [comment]
Definitely a bug. More info here https://github.com/SiCKRAGETV/sickrage-issues/issues/2781 Its been reported many times, but new issues get created each report because the title contains the users path.
Error shouldn't have usability implications for the user, just annoying.

**Comment by NilsNojje** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-25-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@0beda92f71145d448f8f784042a8d631448a0394
Link to Log: https://gist.github.com/4249bac24430906b6b43
### ERROR
```
Thread-14 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/opt/sickrage/sickbeard/webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/opt/sickrage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/opt/sickrage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/opt/sickrage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _opt_sickrage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by firatuzman** [comment]
@OmgImAlexis @flightlevel Sickrage updated and there is no error. Above fix seems to work for me.
