### ISSUE TITLE
Italian airdate

### ISSUE THREAD

**Issue by serramat** [SiCKRAGETV/sickrage-issues#2742]
If TNTVillage is selected as a search provider, when a new show is added it could help to have an option asking if you want to rely on the italian air dates or the english ones. Those can be found on wikipedia.

**Comment by WebSpider** [comment]
We have that option already, network times.

Config > General > Timezone

-----Original Message-----

**Comment by serramat** [comment]
I've changed the timezone from network to local but anything changed. I would like, for example, that Under the Dome S03E09 Airdate 08/09/2015 (italian tv) instead of 14/08/2015 (CBS).

**Comment by flightlevel** [comment]
What's the reason for this? To wait for the subtitles?

**Comment by serramat** [comment]
Because some TV Shows I prefer to watch in Italian while others I want to watch with original language.

**Comment by flightlevel** [comment]
I understand now.
Try correcting the date on tvdb http://thetvdb.com/?tab=season&seriesid=264492&seasonid=609547&lid=15 and let us know if that fixes the problem.

**Comment by serramat** [comment]
I've changed the title of 3x10 and airdate from 3x09 to 3x13 but in my sickrage the problem isn't fixed. 

http://thetvdb.com/?tab=season&seriesid=264492&seasonid=609547&lid=15
![utd](https://cloud.githubusercontent.com/assets/11733072/9809487/e1c7c3e0-5868-11e5-880c-a7ba65245fe6.PNG)

**Comment by serramat** [comment]
I have "Force Full Update" again and now both title and date are changed, thanks.

**Comment by flightlevel** [comment]
Good result
