### ISSUE TITLE
Exception caught in subliminal.scan_video for S0xExx

### ISSUE THREAD

**Issue by snow3461** [SiCKRAGETV/sickrage-issues#2743]
Hello guys,

I have a similar problem to  #2615 or #2506. No subtitles have been downloaded for some time now, so I started looking into it.

# ENV Infos:
SR Version: 	BRANCH: (master) / COMMIT: (bb16d3a3e4d3462a73b944c6e7d9384798774ffd)
SR User:	sickbeard
SR Locale:	(None, None)
SR Config file:	/home/sickbeard/.sickbeard/config.ini
SR Database file:	/home/sickbeard/.sickbeard/sickbeard.db
SR Cache Dir:	/home/sickbeard/.sickbeard/cache
SR Log Dir:	/home/sickbeard/.sickbeard/Logs
SR Arguments:	['-q', '--daemon', '--nolaunch', '--pidfile=/var/run/sickbeard/sickbeard.pid', '--datadir=/home/sickbeard/.sickbeard', '--config=/home/sickbeard/.sickbeard/config.ini']
SR Web Root:	/sickbeard
Python Version:	2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]
OS:Debian GNU/Linux 7.6.0 _Wheezy

# Debug INFO
Here are the DEBUG INFOs after asking to search for subtitles of one show (via **Mass Update**): 

    2015-09-10 11:09:17 INFO     SHOWQUEUE-SUBTITLE :: Downloading subtitles for Fear the Walking Dead
    2015-09-10 11:09:17 DEBUG    SHOWQUEUE-SUBTITLE :: 290853: Downloading subtitles
    2015-09-10 11:09:17 DEBUG    SHOWQUEUE-SUBTITLE :: 290853: Downloading subtitles for S01E01
    2015-09-10 11:09:17 DEBUG    SHOWQUEUE-SUBTITLE :: 290853: Exception caught in subliminal.scan_video for S01E01
    2015-09-10 11:09:17 DEBUG    SHOWQUEUE-SUBTITLE :: 290853: Downloading subtitles for S01E02
    2015-09-10 11:09:17 DEBUG    SHOWQUEUE-SUBTITLE :: 290853: Exception caught in subliminal.scan_video for S01E02

I have absolutely no subtitles downloaded if I launch a search for subtitle (either via **Mass Update**, or **Missed Subtitled Management**)

# What I tried so far:
* rename subliminal cache files, restart SR, no success, same error..
* checking naming pattern : `Season %S/%S.N.S%0SE%0E.%Q.N-%RG`, and has been for almost a year.
* checked for weird char in pathnames like accents and space : there are some, but locale on OS is fr_FR.UTF8. Not sure why SR Locale say `(None,None)` though...is that a problem?

**Comment by WebSpider** [comment]
Please add debug logs

**Comment by snow3461** [comment]
Ok, that is weird....but I belive it is fixed.

I don't know exactly what I did that fixed it...
I checked permissions on tvshows root directories, and did fix somes files permissions

Now, SR Locale reports `fr_FR,UTF8` but did nothing to change it...

I sucessfully downloaded all missing subtitles using **Missed Subtitle Management** and the log show nothing but successfull attempt.

One thing : subtitles do not show in **History** when using **Missed Subtitle Management** ?? (option is checked in parameters)

**Comment by OmgImAlexis** [comment]
@snow3461 we're aware of the history issue.

**Comment by flightlevel** [comment]
@snow3461 Closing this issue as you've resolved your subtitle downloading issue.
We'll keep the history problem under one issue, refer to https://github.com/SiCKRAGETV/sickrage-issues/issues/2719

**Comment by snow3461** [comment]
Thank you guys, keep up the good work !
