### ISSUE TITLE
Can't get https working.

### ISSUE THREAD

**Issue by dellhem** [SiCKRAGETV/sickrage-issues#2744]
Hey.

I have setup my Synology NAS with https and wanted to do the same with Sickrage. I can't get it to work, though. It just falls back to http.

Yes there's a "permission denied" message. But the files have chmod 777.
It's the same files used for the NAS, with root as owner.

Log with debug enabled: http://pastebin.com/nmANe9Pp

**Comment by neoatomic** [comment]
@WebSpider Did you ever setup the certs for SickRage on your Syno.? Never done that myself...

From what i can see in the log the path seems incorrect and no permissions. 
`[Errno 13] Permission denied: '/usr/syno/etc/ssl/ssl.key/server.key'`

**Comment by dellhem** [comment]
Hey. Thanks for you reply.

I can assure you that the path is correct and the permissions are set to 777 for both the .crt and .key.
Where is the default path for SickRage? I can try and cp them and change owner.

**Comment by WebSpider** [comment]
@neoatmic no, im using nginx as a proxy before SR, which does SSL instead. Also, system ssl keys should be protected to be read. You will have to generate your own SSL keys for syno.

I think we do that by default when you enable the SSL option.

-----Original Message-----

**Comment by dellhem** [comment]
Solved:

AAIOError: [Errno 13] Permission denied: '/usr/syno/etc/ssl/ssl.key/server.key'

The files had correct permissions, but not the directories.
The directory /usr/syno/etc/ssl/ssl.key/ had chmod 700.. 
Changed to the same as /usr/syno/etc/ssl/ssl.crt/, 755, and then it works sym-linked.

Sorry about this =)
