### ISSUE TITLE
Not allowed to use symbol in cookie for custom provider, TL requires it.

### ISSUE THREAD

**Issue by tobidoo** [SiCKRAGETV/sickrage-issues#2745]
Trying to set up Torrentleech (TL) as a Custom Torrent Provider. 
TL requires a symbol in their passwords.
Sickrage doesn't allow it. I get that "cookie is wrongly formatted"

Tried several symbols like £ * _ . but none works.

Oh, it's on Freenas.

**Comment by WebSpider** [comment]
Please submit issues with all data present: https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md

**Comment by miigotu** [comment]
why would you set torrentleech as a custom provider when we have a built in provider?

**Comment by OmgImAlexis** [comment]
Closing as you should be using the built in version of torrentleech.
