### ISSUE TITLE
[Feature Request]: Custom search per show/season

### ISSUE THREAD

**Issue by kvloover** [SiCKRAGETV/sickrage-issues#2749]
I believe alot of headaches with not finding torrents that are there can be fixed by allowing users to have a custom search schema for searches.

Allow to set one per season of a show.
- Easily get oddly named sequels
- Hardcode that certain text in the search string at a given spot (not just name).

The default method is good, but being able to divert from it is the holy grail imho.

**Comment by OmgImAlexis** [comment]
Do you mean something like scene exceptions which is already in SickRage?

**Comment by flightlevel** [comment]
Have you seen https://github.com/SiCKRAGETV/sb_tvdb_scene_exceptions
The big advantage of doing it this way is that if one person fixes it, it works for the whole community, rat here than everyone doing their own thing. Your suggestion is going to be complicated for a lot of users. Sick rage is already pretty complex

**Comment by kvloover** [comment]
It's different from scene exceprtions in the sense that it would allow custom search strings being build instead of a different name for the show overal and still using the fixed search string building.

My suggestion would be adding an option on editing the show/season to 'use custom search' and the. Providing a custom schema for the search string. This would then be similar to the custom show names on postprocessing. As an optional setting it will not make sickrage more difficult, but it will allow people to override the default search with something else if needed.

Say you have the show sword art online: (pseudo code)
Season one : sao %e0 
Season two : sao II %e0
Season three : sao III %e0

Or say you have a show aquarion
Season one: aquarion %
Season two: aquarion evolve %
Season three: aquarion logos %

Or a more generic shownaming
Show S%s - %e0

Overriding the default search string allows for many fixes depending on the needs of the users.
This is probably most useful for anime, but would also fix oddly tv shows.

**Comment by duramato** [comment]
@kvloover anime can have per season scene name on xem, you should give it a try

**Comment by kvloover** [comment]
Unfortunately registration is closed (and is every time I check) so I can't change it there.
If it would fix all my problems, one could ignore this request.

However it might be useful for somebody else in other cases.

**Comment by kvloover** [comment]
Well for the life of me scene numbering is not working with torrents atleast.(even properly configured on xem)
So I'd still want to submit this as a change-request :)
