### ISSUE TITLE
GUI Posters missing & unable to delete shows

### ISSUE THREAD

**Issue by Pseudomax** [SiCKRAGETV/sickrage-issues#2750]
Hi

I have been using SickRage for about 9 months now successfully. However about a month ago I decided to upgrade to get my free install of Windows 10. This broke my network and my QNAP NAS speeds went from 10+ MB/sec down to less than 1 MB/sec. After spending some time on the phone to QNAP they convince me that it wasn't their system so I decided to clean reinstall Windows 10 (as the last time was an upgrade). As such, I have had to reinstall SickRage and I now have 2 issues.

1. All the shows are present but I have a broken link with the posters (all images in fact). And unlike getting the default SickRage image when a show's poster is unavailable ... I rather get the browser broken link. Some help to fix this would be very appreciated.

2. This is actually a problem that has existed since I originally installed SickRage. If I try to delete a show it reappears continually. So I delete it (including the media & the NZB) but it reappears within a few minutes. I took the opportunity of the fresh install to delete the media and folders of shows I didn't want but that doesn't fix it. I have disabled Trakt sync as I thought maybe this was causing it ... but they still keep appearing.

Any help gratefully received!

Pseudomax
![screenshot](https://cloud.githubusercontent.com/assets/14224195/9799977/4cff81fa-5802-11e5-9a53-722f6f0c4d71.png)

**Comment by MGaetan89** [comment]
The images issue is already being tracked here https://github.com/SiCKRAGETV/sickrage-issues/issues/2708

For your second issue, I don't know. I don't have that issue. As I am not using Trakt, it might be related to that.

**Comment by flightlevel** [comment]
@Pseudomax 
Re issue 2
Can you enable debug, restart SR, wait 10 minutes, delete a show, wait for it to come back and then post the log

**Comment by Sacrilegium** [comment]
I noticed that #2708 has been closed.  Is the images issue considered to be resolved?  It's still not working for me.  I'm on Windows 7 and have only ever used the Master branch.  I stopped SR, deleted cache.db, restarted SR and forced a full update on all shows.  Still no posters and no network icons.

**Comment by rooT-5oh8** [comment]
Currently experiencing this issue as well, patiently waiting for a solution.

**Comment by OmgImAlexis** [comment]
@Sacrilegium it's fixed in develop, develop will be merged into master soon. Please just patiently until then.

**Comment by Sacrilegium** [comment]
Awesome, thanks OmgImAlexis.

**Comment by Pseudomax** [comment]
Firstly ... just to second Sacrilegium ... the broken image links to the poster is fixed with the most recent update!! Many thanks and credit to those involved ... very efficient!

I am currently logging the delete error and will post the logs when complete ...

**Comment by Pseudomax** [comment]
Oddly the shows seem to stay deleted now?!

Clearly a good thing but not sure what I (or you) did?!

**Comment by Pseudomax** [comment]
Hi, just to say that the issue reappeared when I re selected sync with Trakt. Could I suggest a priority given to SickRage so actively deleting from SickRage is prioritized over any reference in Trakt.
