### ISSUE TITLE
Show Not Correct

### ISSUE THREAD

**Issue by Vodka2014** [SiCKRAGETV/sickrage-issues#2751]
Hi,

Mythbusters are set to 2015EXX where it should be S15E00. I have changed everything to match TVDB now but it will not grab from the index sites.

When i find it and get it manually it saves to Season 15\Mythbusters S15E00 xxxxxx

Scene Numbering is enabled by default on the show.

Thanks

**Comment by WebSpider** [comment]
Please open issues with all relevant data present.

https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md
