### ISSUE TITLE
Dont show 'update available' DIV while showing restart.mako...

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#2753]
... because user already hit "update".

**Comment by fernandog** [comment]
@OmgImAlexis I tried do this but I couldn't. With cheetah this didn't happen. Maybe because the change with inc_top

**Comment by OmgImAlexis** [comment]
@fernandog what's the sickbeard var that gets updated when they click it? I'll need to check if that's been set to true and hide the div.

**Comment by fernandog** [comment]
i think a better way is check if restart.mako is loaded and add a kind of 'hide' parameter in the div

**Comment by OmgImAlexis** [comment]
So in restart.mako just add CSS to `display: none;` on the update dialog?

**Comment by fernandog** [comment]
not familiar with CSS/HTML. 
how to check the restart.mako is loaded?

**Comment by OmgImAlexis** [comment]
Done https://github.com/SiCKRAGETV/SickRage/pull/2509

**Comment by fernandog** [comment]
thanks
