### ISSUE TITLE
[Feature Request] Report incorrect file match

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2754]
I'd like to have an option somewhere possibly in history where people can report incorrect file name matches so we can get them fixed in guessit.

**Comment by didyouexpectthat** [comment]
Would this be related?
```
2015-09-10 22:14:49 INFO     SEARCHQUEUE-MANUAL-264492 :: [IPTorrents] :: Ignoring result Under.the.Dome.S03E13.HDTV.x264-LOL because we don't want an episode that is SDTV
```

But in guessit...

```
# guessit Under.the.Dome.S03E13.HDTV.x264-LOL/
For: Under.the.Dome.S03E13.HDTV.x264-LOL/
GuessIt found: {
    [1.00] "releaseGroup": "LOL",
    [0.60] "episodeNumber": 13,
    [1.00] "videoCodec": "h264",
    [0.60] "format": "HDTV",
    [0.42] "series": "Under the Dome",
    [1.00] "type": "episode",
    [0.60] "season": 3
}
```

**Comment by OmgImAlexis** [comment]
@didyouexpectthat yes this would be part of it, the more shows we can find that have issues the better guessit will get.

**Comment by flightlevel** [comment]
@OmgImAlexis 
Pretty sure we are only using guessit for subtitles at the moment. 
Still using the sickbeard name parser for other stuff https://github.com/SiCKRAGETV/SickRage/blob/c9729676cdbd2af5b04337b239bb3a843f5feaa4/sickbeard/name_parser/regexes.py
@didyouexpectthat 
That example isn't named properly. You can't tell its HD unless it's got a quality in the name eg 720p, 1080p. How does the parser know it's not 480?

**Comment by OmgImAlexis** [comment]
@flightlevel yeah, I didn't realise we hadn't switched over yet. It'd still be a good idea especially after we first switch so we can get them fixed ASAP.

HDTV is 720p or 1080p, we mark it as 720p unless otherwise specified. It shouldn't be seeing it as SDTV anyways, I have a feeling that's one of the directory bugs though, it should be okay if it was tested on a file with the same name.

**Comment by didyouexpectthat** [comment]
@OmgImAlexis I get different results when using guessit. I didn't actually have the file so I was just using guessit to find out more information.
For instance, if I just use guessit to just put in the name of the download (without extension), then it doesn't recognize much. If I add a / or an extension, it recognizes more of the details of the file. Just what I've noticed.
I put a few examples here: https://github.com/SiCKRAGETV/sickrage-issues/issues/2765

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
