### ISSUE TITLE
Colour TV Channel Icon Request

### ISSUE THREAD

**Issue by devenashani** [SiCKRAGETV/sickrage-issues#2756]
Hello,

Icon for TV channel Colours from india is missing, would appreciate if this could be added.

below is the link to official website of the channel also the image of logo is attached for reference

http://colors.in.com/in/

![image](https://cloud.githubusercontent.com/assets/2997303/9811808/2664e446-5897-11e5-97e9-26de259b9504.png)

**Comment by flightlevel** [comment]
@devenashani 
Could you give an example from tvdb of a show from this network

**Comment by neoatomic** [comment]
@devenashani Should be added with the next update.

https://github.com/SiCKRAGETV/SickRage/pull/2481

http://thetvdb.com/?tab=series&id=273192&lid=13
