### ISSUE TITLE
Not sending NZB to SABnzbd

### ISSUE THREAD

**Issue by mogodon** [SiCKRAGETV/sickrage-issues#2758]
Since last week no shows are sending the NZB successfully to SABnzbd either as a daily search or as a manual search. Error returned from SABnzbd is blank.  Direct sending of NZBs from indexer page to SABnzbd works as does Sickbeard.

Running:
SickRage 4.0.55 (2015-08-31)
BRANCH: (master)
COMMIT: (bb16d3a3e4d3462a73b944c6e7d9384798774ffd
SABnzbd 0.8.0
QNAP NAS Firmware 4.2.0 build 20150902
Python 2.7.9

This log shows the daily episode search which picks up the latest episode of Under the dome.  I expected it to send the nzb from usenet crawler to SABZBD
https://gist.github.com/mogodon/0727019198129667268e

On this particular log I ran a manual search from the show screen for the latest episode of Under the dome.  I expected it to send the nzb from usenet crawler to SABZBD
https://gist.github.com/anonymous/812fa93a2a4b687c053e

I've ruled out the SSL issue with QNAP as I have deselected the tick box on sickrage and also fixed sabnzbd.py to allow https.  Tested and working via Sickbeard.

Any help would be appreciated.

**Comment by neoatomic** [comment]
@mogodon Firstly you need this package, the one you currently use is not working properly. 

http://apps.qnap.community/11-community/17-qsickrage

I'm pretty sure that this is the main cause of your problem. 
Also you can disable woobles provider that doesn't work anymore. (and was actually removed from sickrage)
I'm using SABNZB myself with SickRage, and all is working fine here.

**Comment by mogodon** [comment]
Thank you I shall try that one. 

I think I'm using Clinton Hill's optware free version which I thought was the correct one. What are prereq of the one on the link?

**Comment by WebSpider** [comment]
Prereq of qsickrage is intel cpu

-----Original Message-----

**Comment by neoatomic** [comment]
Indeed, if you have a ARM based QNAP than the Package wont work. And the only way to get it working than is to somehow update the Python for the SickBeard-TVRage package...

**Comment by mogodon** [comment]
Yes I have an x86 NAS. Just about to back up my settings on SickRage and remove/install the qpkgs

**Comment by mogodon** [comment]
I can confirm that switching to qpkg above has solved my issues. Thanks all.
