### ISSUE TITLE
Unable to send torrents from BTN to Transmission

### ISSUE THREAD

**Issue by samesong** [SiCKRAGETV/sickrage-issues#2759]
Branch: master
Commit hash: bb16d3a3e4d3462a73b944c6e7d9384798774ffd
Your operating system and python version: 2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]
What you did: Attempted to search for and download a season pack
What happened: The following error was returned:
2015-09-11 22:38:58 SEARCHQUEUE-BACKLOG-82696 :: [BTN] :: Transmission: Unable to send Torrent: Return code undefined
What you expected: The torrent file to be passed to Transmission
Link to a copy/paste of your logfile with clear debug info of the error on GIST:
http://pastebin.com/GiiY9MAZ

edit: user ravno in IRC said he fixed the issue using the following code, but I have yet to verify:
http://pastebin.com/N7E8wqgh and http://pastebin.com/n4mgqRs9

**Comment by neoatomic** [comment]
@samesong We need full debug logs to see whats happening. without them we can do anything...
For the error itself it might be an SSL issue.
And did you modify any code.?

**Comment by miigotu** [comment]
I tested using his btn account, and it snatches fine. Related to his connection to his client.

**Comment by OmgImAlexis** [comment]
Closing as this seems to be a user related issue, we'll reopen it you can give us more details.
