### ISSUE TITLE
Feature Request: Configurable logfile sizes and number

### ISSUE THREAD

**Issue by TagForce** [SiCKRAGETV/sickrage-issues#276]
With the new logging code in place, maybe it's possible to make the number of log files and the max size of the logfiles configurable through the settings page?

I ask because I love verbose logging, especially when stuff goes wrong. At the moment, though, there's only 5 logfiles of 1MB each. This means that usually they're filled up within 6 hours. On days with a lot of releases even shorter.

I would like to be able to change the amount of logging saved so that I can keep about a week's worth of logs, for debugging purposes, without having to manually move them somewhere.

Browsing through the code, there's already variables in place to handle the number of logfiles and maximum size, so I imagine it won't be too much of a problem to implement a config.ini setting for those.

Keep up the great work.

**Comment by fernandog** [comment]
@TagForce is it possible to add a filter as I said above? can you do it?

**Comment by TagForce** [comment]
@fernandog I'm not really a python programmer. I can find stuff using the debug function in PyDev for Eclipse, and when the code's not too hard I can fix it, or have it do stuff a bit different. I have a programmer's logical mindset, so to speak, but I'm not a professional programmer, and so far, aside from SR I have no experience with Python whatsoever. I'm learning quickly, though.

The filters that you're talking about are a rather big change in the way SR displays logs. I can have a look and see if I can do anything with it, but I can make no promisses. Time is going to be an issue as well. I'm doing this in what little spare time I have. So, I'll have a look, but don't let that stop anyone from doing it themselves. Probably end up with better code and quicker implementation that way.

I suppose one would usually set the logfile size to something like 1 or 2MB, instead of 10kb. SR has always displayed only the latest log file, which is one of the reasons I wanted to be able to change the size and number. Now, displaying 25 logs of 10MB each in SR is going to be a no-go, so we need to apply some logic to what to display.

**Comment by fernandog** [comment]
I didn't set my log to 10kb. 
Image the sickrage just created a new log file (after the previous one is 1024kb), this new log file is almost empty so won't know anything in the UI

**Comment by TagForce** [comment]
True. So, basically, you'd want SR to display an X amount of lines from the logfiles, regardless if those are all in the first logfile, the first 2 logfiles, or across all X amount of logfiles you have.

**Comment by fernandog** [comment]
yes.
About the filter, I don't know how to code html/template, so if you send me the new template file and a new field in the config>general I do the rest (simple text field)

**Comment by fernandog** [comment]
@TagForce 
@abeloin - can you help me too?

I did this but there's an error that logFilter is not defined.
BUT I defined at viewlogs.tmpl. Why webserve can't read this variable from the UI?

viewlogs.tmpl
```
<div class="h2footer pull-right">Minimum logging level to display: 
<select name="minLevel" id="minLevel" class="form-control form-control-inline input-sm">
#set $levels = $reverseNames.keys()
$levels.sort(lambda x,y: cmp($reverseNames[$x], $reverseNames[$y]))
#for $level in $levels:
<option value="$reverseNames[$level]" #if $minLevel == $reverseNames[$level] then "selected=\"selected\"" else ""#>$level.title()</option>
#end for
</select>
<select name="logFilter" id="logFilter" class="form-control form-control-inline input-sm">
<option value="ALL">ALL</option>
<option value="DAILYSEARCH">DAILYSEARCH</option>
<option value="BACKLOGSEARCH">BACKLOGSEARCH</option>
<option value="SHOWUPDATE">SHOWUPDATE</option>
<option value="VERSIONCHECK">VERSIONCHECK</option>
<option value="SHOWQUEUE">SHOWQUEUE</option>
<option value="SEARCHQUEUE">SEARCHQUEUE</option>
<option value="PROPERFINDER">PROPERFINDER</option>
<option value="AUTOPOSTPROCESSER">AUTOPOSTPROCESSER</option>
<option value="SUBTITLESFINDER">SUBTITLESFINDER</option>
<option value="TRAKTCHECKER">TRAKTCHECKER</option>
<option value="EVENTS">EVENTS</option>
</select>
</div>
```

webserve.py
```
        for x in reversed(data):

            x = ek.ss(x)
            match = re.match(regex, x)

            if match:
                level = match.group(7)
                threadName = match.group(8)
                if level not in logger.reverseNames:
                    lastLine = False
                    continue

                if logger.reverseNames[level] >= minLevel and logFilter in threadName:
                    lastLine = True
                    finalData.append(x)
                else:
                    lastLine = False
                    continue

            elif lastLine:
                finalData.append("AA" + x)

            numLines += 1
```

TO-DO: check if listbox is ALL, if true, don't filter anything.

**Comment by abeloin** [comment]
@fernandog Will look into it later today

**Comment by TagForce** [comment]
I think it works the other way around.
You need to define in webserve.py and you feed that into the template.

As far as I can tell (and that's not very far, I admit) all the template does is feed a variable into the viewlog function and display the loglines that come out of it.

In the case of the minLevel value, that is set as a parameter to the viewlog function. So it is already defined. There's no definition for the logFilter value (yet).

You need to code what you want returned from the function first. Make sure you can hardcode the values in the function and that they return what you want (without any listboxes and additions to the template). When it does what you want, then you can add listboxes to the template and have the template page pass the values for your variables back to webserve.py.

**Comment by fernandog** [comment]
@TagForce I already code template and the webserve. It's all ready. I only need to logFilter to get the value from the UI

**Comment by TagForce** [comment]
I have no idea how to do that, but if I have time I'll dive into this later tonight.

This is where my lack of Python experience comes up. It works, but I have no idea how exactly it goes about and does it. Stepping through the code using the debugger helps somewhat, but all of a sudden there's a value there that I did not expect and have no idea how it got there, even when going through the code line by line. Oh well. If I have time I'll dive into this deeper.

**Comment by abeloin** [comment]
@fernandog For logFilter you need to add it to the t.respond() in webserve.py. Also to get the value back it need to be defined in viewlog function parameters.

Check this diff http://pastebin.com/AcJBFftH , it's a working log filter based on your code posted earlier.

**Comment by fernandog** [comment]
@abeloin thanks! worked. I only had to change 

```
if logger.reverseNames[level] >= minLevel and (logFilter == 'None' or logFilter in logName):
```
to 

```
if logger.reverseNames[level] >= minLevel and (logFilter == 'NONE' or logFilter in logName):
```

Now I will add the provider as filters. like [TORRENTDAY] or [NZBGEEK]

**Comment by abeloin** [comment]
@fernandog Oops, forgot to change that on pastebin.

**Comment by fernandog** [comment]
@abeloin check this out:

https://github.com/fernandog/SickRage/commit/ae8fc97c87928a884a7857d3e05b2e0206a6775f

User can now free search for text (case sensitive). For example see all logs from a specific provider or find anything related to on tv-show

The only thing I couldn't do is add javascript logic. Spent all day trying to do it but I coudln't
For example:
-if there's any text in logSearch, disable minLevel and logFilter and set them to default: INFO and NONE.
-If logSearch input text is cleared then enable minLevel and logFilter again

**Comment by abeloin** [comment]
@fernandog Nice.
> The only thing I couldn't do is add javascript logic. Spent all day trying to do it but I coudln't
Don't forget the page is reloaded every time a change occur on #minLevel, #logFilter, #logSearch, so you could simply add the logic in viewlog() and send via t.respond and put conditional in the tmpl to disable the select tag.

I've updated http://pastebin.com/AcJBFftH to show you an example.

**Comment by fernandog** [comment]
@abeloin 

why this code do not work?

```
function(){
    \$('#minLevel, #logFilter,#logSearch').change(function(){
        url = '$sbRoot/errorlogs/viewlog/?minLevel='+\$('select[name=minLevel]').val()+'&logFilter='+\$('select[name=logFilter]').val()+'&logSearch='+\$('#logSearch').val()
        window.location.href = url
    });
    if ( $('#logSearch').val().length == 0 ) { 
        document.getElementById("logFilter").selectedIndex = 6
        // Change to "NONE"
        document.getElementById("minLevel").selectedIndex = 2
        // Change to "INFO"
        document.getElementById("minLevel").disabled=false;
        document.getElementById("logFilter").disabled=false;

     } else { 
        document.getElementById("minLevel").disabled=true;
        document.getElementById("logFilter").disabled=true;     
     }  
});
```

**Comment by abeloin** [comment]
@fernandog you need to use jquery's .on('change', ...) or .change() on logsearch:

```
\$('#logSearch').change(function() {
    if ( \$('#logSearch').val().length == 0 ) {
        \$('#logFilter option[value=SEARCHQUEUE]').prop('selected', true); 
        \$('#minLevel option[value=zzzthevalue]').prop('selected', true); 
        \$('#minLevel').prop('disabled', false);
        \$('#logFilter').prop('disabled', false);
    } else {
        \$('#minLevel').prop('disabled', true);
        \$('#logFilter').prop('disabled', true);
    }
});
```
You should use the select option value or name instead of index value, it's easier to debug.

Ps: Don't forget to escape the $ sign in a tmpl.

**Comment by fernandog** [comment]
@abeloin thanks! worked. did you received the TD invite?

**Comment by abeloin** [comment]
@fernandog Yes currently registering.

**Comment by fernandog** [comment]
@TagForce @markheloking @abeloin can you test it too? any feedbacks?

**Comment by abeloin** [comment]
@fernandog I've put some comment in https://github.com/SiCKRAGETV/sickrage-issues/issues/276#issuecomment-71113806

**Comment by TagForce** [comment]
I'll test it later today.

Still only shows the logs from the current logfile, right?
I suppose, if you want to make it really configurable, there needs to be a provision for it to open sickrage.log.X files if sickrage.log.Y reaches <EOF>.
Then you can also add a config option for the number of lines to display (currently hardcoded to 500), and have the auto-refresh rate set to something more useful than 10 minutes or configurable as well.

**Comment by TagForce** [comment]
@fernandog Left you a comment on your commit.
Basically, it works just fine, and is a welcome addition. However, the thread list should sort in such a way that the None option is always on the top, and has a more descriptive display string.

I've added the change to the comment, but make sure you change the other occurences of 'None' as well.

**Comment by fernandog** [comment]
@TagForce  please update SR and report back please. Fix was merged

**Comment by TagForce** [comment]
@fernandog Uhmmm... https://github.com/SiCKRAGETV/SickRage/issues/1229 is still open?
I don't see your change merged into my now fully updated production server.

**Comment by fernandog** [comment]
Yes. But yours did

**Comment by TagForce** [comment]
Mine was merged 2 weeks ago. We're just waiting for your PR to be merged now :)
(mine works fine, btw, I've had it at 25 files of 10MB for a while now)

**Comment by fernandog** [comment]
I prefer 3MB. My RPI can't handle too large log files (together with my search feature)

**Comment by fernandog** [comment]
@TagForce 

just added a new feature that fetches from all logfiles. Will always show 500 lines. but if you use the new  searchLog or searchFilter, it will fetch from all files (limit of 500 lines of result).

Also if SR justed rotated the file, sickrage.log will have only a few lines. With this, it will fetch the next logfile to complete 500 lines

https://github.com/SiCKRAGETV/SickRage/pull/1448
