### ISSUE TITLE
Unable to use tracker HDbits

### ISSUE THREAD

**Issue by samesong** [SiCKRAGETV/sickrage-issues#2760]
Branch: master
Commit hash: bb16d3a3e4d3462a73b944c6e7d9384798774ffd
Your operating system and python version: 2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]
What you did: Attempted to perform a search using the HDBits tracker
What happened: The following error was returned: [HDBits] :: Unknown exception in getURL https://hdbits.org/api/torrents Error: string indices must be integers, not str
What you expected: HDBits to return results

**Comment by neoatomic** [comment]
@samesong We need full debug logs to see whats happening. without them we can do anything...
For the error itself it might be an SSL issue.

**Comment by flightlevel** [comment]
Pretty sure that it was @samesong working through this with @miigotu on IRC

**Comment by miigotu** [comment]
yes, this one is my fault. working on a fix for it by tomorrow

**Comment by miigotu** [comment]
Fixed.

**Comment by samesong** [comment]
Thank you miigotu!
