### ISSUE TITLE
Can't delete or remove show from GUI

### ISSUE THREAD

**Issue by Al-25** [SiCKRAGETV/sickrage-issues#2764]
Hello,

I encounter an issue with the latest version.When i try to delete or remove a show using Manage->Mass Update menu, nothing happened when i click on submit (but it works if i try to update or rescan).
Nothing in the log even in debug.
Below my configuration : 
SR Version: 	BRANCH: (master) / COMMIT: (37914618686ee70479da0fa4b2cca851fa49c5e2)
SR User:	vmulti
SR Locale:	(None, None)
SR Config file:	/home/vmulti/Sickrage/config.ini
SR Database file:	/home/vmulti/Sickrage/sickbeard.db
SR Cache Dir:	/home/vmulti/Sickrage/cache
SR Log Dir:	/home/vmulti/Sickrage/Logs
SR Arguments:	['-q', '--daemon', '--nolaunch', '--pidfile=/var/run/sickbeard/sickbeard.pid', '--datadir=/home/vmulti/Sickrage/', '\xe2\x80\x93config=/home/vmulti/Sickrage/config.ini']
Python Version:	2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]

Kr,

**Comment by WebSpider** [comment]
I am having a similar problem when adding a show on latest master on Syno: No automatic refresh after the action is done

**Comment by ryanneufeld** [comment]
I am also unable to remove shows.

**Comment by fernandog** [comment]
@Al-25 @ryanneufeld do you still have this issue?

**Comment by Al-25** [comment]
For me "remove" is working now but "delete" not yet !

**Comment by fernandog** [comment]
@Al-25 post errors about deleting shows

**Comment by miigotu** [comment]
@Al-25 for delete shows, it never pops up the window to ask you if you want to delete the files? Or is there some error or just not actually doing the delete of the files?

**Comment by Al-25** [comment]
@miigotu : no popup actually

**Comment by OmgImAlexis** [comment]
@Al-25 one of the last commits to develop should fix that so just wait till that's merged into master.

**Comment by Al-25** [comment]
Perfect :) ! Thanks !

**Comment by miigotu** [comment]
@Al-25 that actually should already be in master
