### ISSUE TITLE
SSL Error.

### ISSUE THREAD

**Issue by Vodka2014** [SiCKRAGETV/sickrage-issues#2766]
Please see the below:

SR Version:	BRANCH: (master)
COMMIT: 37914618686ee70479da0fa4b2cca851fa49c5e2
Python Version:	2.7.10 (default, Jun 3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]

Branch: master
Commit hash: 37914618686ee70479da0fa4b2cca851fa49c5e2
Your operating system and python version: Synology DSM 5.2 / Python Version: 2.7.10
What you did: Updated From bb16d3a3e4d3462a73b944c6e7d9384798774ffd To 37914618686ee70479da0fa4b2cca851fa49c5e2
What happened: Got Errors In Logs
What you expected: https://gist.github.com/Vodka2014/fa8a10d3aedfdfe457b4

Apologies, Will check this now and update

**Comment by neoatomic** [comment]
@Vodka2014 Please follow the guidelines.  https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket

Concerning the log thats an SSL error, but cant see where you where connection to. 
There is a setting called `Verify SSL Certs` under the advanced setting tab. If you disable that it should work. But would like the know where the ssl error comes from.

**Comment by Vodka2014** [comment]
Well it is on my Synology that i have installed SickRage and have had SSL on all the time so i do not know what has broken

**Comment by Vodka2014** [comment]
So i removed the settings saved and rebooted and all was clear, Then i enabled it again and rebooted and https://gist.github.com/Vodka2014/ff4457923b1153e3df80

**Comment by WebSpider** [comment]
Unknown CA in the error -> turn SSL verify off

**Comment by Vodka2014** [comment]
@WebSpider It used to work as is so what has changed ?

**Comment by WebSpider** [comment]
Would you happen to know which commit it still worked for you?

Would make looking for the needle a bit less haystackery ;)

-----Original Message-----

**Comment by Vodka2014** [comment]
@WebSpider I was on bb16d3a3e4d3462a73b944c6e7d9384798774ffd before i updated and all was ok. I can try and revert back if needed just will need the process since the Backup/Restore option does not work that well.

**Comment by WebSpider** [comment]
Nothing was changed between these commits that have anything to do with SSL handling. Weird.

**Comment by miigotu** [comment]
Set a real title to this or I must close it, thanks.

**Comment by Vodka2014** [comment]
Well i see there was a new commit today and i have updated and no errors where seen in the logs. So i have no clue why this started and ended.
