### ISSUE TITLE
Scene numbers not working

### ISSUE THREAD

**Issue by kvloover** [SiCKRAGETV/sickrage-issues#2768]
BRANCH: (master) 
COMMIT: (37914618686ee70479da0fa4b2cca851fa49c5e2) 
Python Version: 2.7.10 (default, Jul 14 2015, 19:46:27)
 [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
OSX Yosemite 10.10.5 

So I have multiple anime's that span multiple seasons and are no longer downloading through torrents.
When they were freshly added they did manage to download some of their second/third seasons. But since a week now none appear to be working.

Example show:
http://thexem.de/xem/show/2479
Sickrage has found the show on tvdb and xem.
Scene numbers are corresponding to xem.

Searching for an episode in season 3 yields no results. Upon inspecting logs the providers are searched using either "Wagnaria!! 3x10" or "Wagnaria 36" respectively scene and non-scene options. It needs to search for "Working!!! 10" (season 3 alias on xem and absolute scene number on xem)

https://gist.github.com/kvloover/bd5f5901098a2427ea4b

**Comment by kvloover** [comment]
So appears it is being properly searched on in the provider kat, but nyaa is staying quiet.

After adding "Working!!!" to exception list (Trying to download S03E10) it says it's not the correct one.
https://gist.github.com/kvloover/81402e804c0b7d83b3f9

Trying to download S01E10 snatches, but mistakenly thinks it's season 1 instead of season 3 as defined on XEM.

**Comment by kvloover** [comment]
Another log trying to find Aquarion Logos 10 (S3E10)

**Comment by duramato** [comment]
@kvloover is Anime checked on that show?
