### ISSUE TITLE
Default <keep> when using mass update

### ISSUE THREAD

**Issue by didyouexpectthat** [SiCKRAGETV/sickrage-issues#2769]
If I want to change a bunch of shows, I have to change the settings all to `<keep>` otherwise it will auto choose enabled or disabled (and Wanted for default episode status).
![image](https://cloud.githubusercontent.com/assets/1329077/9827784/f1a00174-589a-11e5-84f7-0599d2c77965.png)
In SR, it would be more plausible to have it automatically default to `<Keep>` instead of this strange array. 
![image](https://cloud.githubusercontent.com/assets/1329077/9827791/0aa273d2-589b-11e5-8f3a-65b513498c20.png)

**Comment by fernandog** [comment]
it used to be 'keep' IF you choose more than one show and they could have different status. after mako it changed, maybe its a bug.
@OmgImAlexis can you check that please?

**Comment by OmgImAlexis** [comment]
I'll have a look in a bit, I suspect you're right we rewrote a lot of those options as they broke in mako.

**Comment by fernandog** [comment]
@didyouexpectthat do you have any shows that the two options are different?

I did a test here: paused on show and mass edit this paused show with a non-paused show. The field in mass edit appeared as 'disabled" - should be 'keep'

@OmgImAlexis this code get the status from the first show only?
```
            <option value="disable" ${('', 'selected="selected"')[not bool(paused_value)]}>disable</option>
```

**Comment by fernandog** [comment]
the original cheetah file:
https://github.com/SiCKRAGETV/SickRage/blob/0a078d7acb4326ae0a35268d888016cbd585ac49/gui/slick/interfaces/default/manage_massEdit.tmpl#L108-L110

**Comment by OmgImAlexis** [comment]
@fernandog `paused_value` might be from an import.

Shouldn't everything just be `<keep>` by default?

**Comment by fernandog** [comment]
Problem with 'keep' by default is that user dont know the setting value

IMO if all settings are the same them show the setting. Otherwise show 'keep'

Not sure if worked like this before. Thats why I asked about that variable

**Comment by OmgImAlexis** [comment]
I have no clue where the variable came from, I'm assuming an import @miigotu any ideas?

The thing is the user doesn't really need to know, if we're showing them a value I'd assume that's what it's being changed to. If it's `<keep>` then I'd assume it's not changing which is how it should be.

**Comment by miigotu** [comment]
paused_value is set in webserve, https://github.com/SiCKRAGETV/SickRage/blob/0a078d7acb4326ae0a35268d888016cbd585ac49/sickbeard/webserve.py#L3259

Still is:
https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/webserve.py#L3161

**Comment by fernandog** [comment]
@OmgImAlexis found the issue. paused value can be None if at least one show has diff setting

![image](https://cloud.githubusercontent.com/assets/2620870/10181458/b2f7cd14-66ee-11e5-9aa2-a8a9e98ae8d6.png)
