### ISSUE TITLE
Setting file timestamp not supported on Synology DS

### ISSUE THREAD

**Issue by key134** [SiCKRAGETV/sickrage-issues#277]
Branch: sickrage master
Commit (cause): ed0e7e47168aa297458ead10b9f98d7e893f0aca
Commit (my current one): 33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8
OS & Python version: Synology DSM 5.1-5004, Python 2.7.8
What I did: normal update ran and threw an error per file in my DB when trying to set the timestamp
What happened: errors were thrown in the log
What I expected: fail silently when the system does not support the timestamp change feature. This causing commit is not actually the problem, it just shows the error. I didn't even know it was trying this before. The error is thrown properly in the log that the OS doesn't support the option.
Pastebin: http://pastebin.com/rKAHCasR

**Comment by kinetix63** [comment]
Am getting these issues too, and it seemed to start after the most recent upgrade. Thousands of "2014-12-28 03:52:03 SHOWQUEUE-REFRESH :: 258107: Unable to modify date of XXXXXX.XXX to show air date May 26,2013 (21:30)" errors in the log.

Running DSM 5.1.5021 Update 2, and Python 2.7.8-11.

Disabled this feature for now to prevent errors. Seems to happen every time a full backlog scan is performed.

**Comment by key134** [comment]
How do you disable the feature? I just changed my local copy to write to the debug log instead of error log when this exception is raised.

**Comment by kinetix63** [comment]
@key134 - Go to Settings -> Post-Processing, and disable the option called "Change File Date"

**Comment by megapearl** [comment]
Same problem here on FreeBSD 10, I disabled it, and that fixed the problem for me.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/277

**Comment by fernandog** [comment]
@abeloin I couldn't find the another issue about it. this can't be fixed, isn't?

**Comment by key134** [comment]
At least lower it to a warning or raise the exception earlier on and handle the "system doesn't support this function". This error is not useful and the option is defaulted to on. Turning it off is a good workaround but it isn't really fixed.

**Comment by fernandog** [comment]
as you said: the error is thrown properly in the log that the OS doesn't support the option.

**Comment by key134** [comment]
Hmm you are right. I guess I just wondered if the error should be thrown after that or if the function should just break.

**Comment by abeloin** [comment]
@fernandog Pull request https://github.com/SiCKRAGETV/SickRage/pull/1295 further define why it doesn't work.
In this case, I don't think we should change the behavior as people using this feature want to be notified when it doesn't work. This setting is not enabled by default.

**Comment by abeloin** [comment]
@fernandog The log error @key134 mention is this one: https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/tv.py#L2547

**Comment by brimur** [comment]
@fernandog @abeloin Sorry to drag up an old issue but I recently moved SR off my Synology NAS and onto a ubuntu machine and I am seeing this issue on some episodes of only 3 of my shows. As in only errors for those 3 shows are in the logs. I'm happy enough to just turn it off but I was wondering if you guys had any idea why it is only those shows and not all the shows. Every folder and file in the TV Shows folder has the same 777 permissions btw.
