### ISSUE TITLE
Filename issues again

### ISSUE THREAD

**Issue by wimpyrbx** [SiCKRAGETV/sickrage-issues#2770]
i have gotten, after couple of days ago, an influx of these errors.

2015-09-11 12:31:33 Thread-47 :: Unable to get size for file D:\TV\SERIES\Hawaii Five-0\Season 05\Hawaii Five-0 - S05E20 - 'Ike Hanau.nfo Error: error 2 : The system cannot find the file specified

i've tried to manually rename and see what SR does when i try to rename back.

00:39:24 INFO::Thread-52 :: Renaming file from D:\TV\SERIES\Hawaii Five-0\Season 05\Hawaii Five-0 - S05E20 - Ike Hanau.mkv to D:\TV\SERIES\Hawaii Five-0\Season 05\Hawaii Five-0 - S05E20 - 'Ike H─ünau.mkv

problem here is that "à ü è" etc are not tackled well by SR it seems. when fetching info from thetvdb the title for this specific episode is " 'Ike Hānau ", but when SR tries to rename, or look for the file, it looks for " 'Ike H─ünau " for some reason.

any tips? is this a bug? i've gotten like a thousand from alot of different shows.

**Comment by wimpyrbx** [comment]
WindowsError: [Error 2] The system cannot find the file specified: u"D:\\TV\\SERIES\\Hawaii Five-0\\Season 05\\Hawaii Five-0 - S05E20 - 'Ike Hanau.tbn"
00:42:07 DEBUG::Thread-26 :: Traceback (most recent call last):
  File "C:\SR\sickbeard\helpers.py", line 1476, in get_size
    total_size += ek.ek(os.path.getsize, fp)
  File "C:\SR\sickbeard\encodingKludge.py", line 68, in ek
    result = func(*args, **kwargs)
  File "C:\Python27\lib\genericpath.py", line 49, in getsize
    return os.stat(filename).st_size

**Comment by wimpyrbx** [comment]
ok it seems to be related to issue SR had with NFOs a while back. deleting the NFO and doing a full update fixed it it seems.

still, would be a nice option to be able to force NFO rewrite on Full Update to update information in the NFOs without having to delete them manually.

**Comment by neoatomic** [comment]
Those encoding issues are a pain with Windows... There is another isseu open about it, and we plan to see if anything can be improved there. But it can take a wile, as we currently have more urgent things to fix...
