### ISSUE TITLE
History page refresh

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2772]
Since the change to mako, if i select for exable the debug log ,and refresh the page it returns to info .Previosly it would retain the selected log level

**Comment by OmgImAlexis** [comment]
@duramato this is a known issue I'm fixing it, please remind me if it's not fixed within the next few days.

**Comment by OmgImAlexis** [comment]
@duramato does this fix it? https://github.com/SiCKRAGETV/SickRage/pull/2484

**Comment by duramato** [comment]
@OmgImAlexis yes it fixed ,thanks!
