### ISSUE TITLE
Embedded subtitles not detected

### ISSUE THREAD

**Issue by NicoLeOca** [SiCKRAGETV/sickrage-issues#2774]
Hi,
Can you please investigate and let me know what's wrong?

Branch : master
Commit hash : 37914618686ee70479da0fa4b2cca851fa49c5e2 (Sr is uptodate)
Your operating system and python version : Synology DSM with Python 2.7.10

What you did:
manually added a couple of media

What happened
for a few of them, embedded subtitles were not detected:
The.Mindy.Project.S03E08.Diary.of.a.Mad.Indian.Woman.720p.WEB-DL.DD5.1.H.264-SA89
The.Mindy.Project.S03E19.720p.HDTV.x264-IMMERSE
The.Mindy.Project.S03E20.720p.HDTV.x264-IMMERSE
none of the subs are forced

What you expected
SR to detect the very subtitles

Link to a copy/paste of your logfile with clear debug info of the error on GIST:
https://gist.github.com/NicoLeOca/c0e4f6acb0260147953c

**Comment by neoatomic** [comment]
Are the embedded subtitles not detected for only those files, or all files that have embedded subtitles?

**Comment by WebSpider** [comment]
Do we detect embedded subtitles? Cool.

**Comment by NicoLeOca** [comment]
@neoatomic 
those were the only ones with embedded subtitles within the whole season I got from different sources
But I also have the issue with other shows/media.
finding examples is doable if necessary.

@WebSpider 
SR is supposed to if you set it up properly

**Comment by NicoLeOca** [comment]
@neoatomic 
in fact, I easily found another one
The.Knick.S01E01.BluRay.720p.DTS.x264-EPiC
SR didn't detect embedded subtitles for the whole season realeased by EPIC actually

**Comment by miigotu** [comment]
We did detect embedded subtitles until a recent PR. https://github.com/SiCKRAGETV/SickRage/pull/2453

**Comment by NicoLeOca** [comment]
Thank you @miigotu 
Looking forward to see it fixed but it's clear it isn't a high priority.
It's better to have twice the proper subtitles than none.

**Comment by miigotu** [comment]
@NicoLeOca actually, do you have this option checked or no?
![image](https://cloud.githubusercontent.com/assets/390379/9831529/140bbffc-5911-11e5-9572-cb10b7c1bc46.png)

**Comment by NicoLeOca** [comment]
@miigotu 
unchecked

**Comment by NicoLeOca** [comment]
@miigotu 
I'll consider that here is the proper thread to talk about subtitles then.

Would it be possible for SR to differenciate forced subtitles and possibly add an additionnal option to not consider them?

**Comment by miigotu** [comment]
It already does.

**Comment by miigotu** [comment]
if by "forced" subtitles you mean ones that are embedded into the mkv/mp4 container anyways. Subtitles that are muxed into the video stream itself we cannot detect.

**Comment by NicoLeOca** [comment]
Yes I meant the ones that are embedded and tagged as "forced", not those which are burnt into the video.

good if it does the job already. sorry if I didn't really noticed as no embedded subtitles are recognized at the moment

**Comment by medariox** [comment]
@miigotu Is most probably right. @NicoLeOca can you please set subtiles=False to subtitles=True and see if that works? Sadly setting subtitles to True has other downsides, but let's see if that's the problem first. I will gladly look into the problem asap.

**Comment by NicoLeOca** [comment]
@mediarox
I am not sure to understand.
Subtitles are enabled.
Embedded are as well as the checkbox is unchecked

here is an extract from the config file:
use_subtitles = 1
subtitles_languages = eng
SUBTITLES_SERVICES_LIST = "thesubdb,podnapisi,addic7ed,opensubtitles,tvsubtitles"
SUBTITLES_SERVICES_ENABLED = 0|0|1|1|1
subtitles_dir = ""
subtitles_default = 1
subtitles_history = 1
embedded_subtitles_all = 0
subtitles_finder_frequency = 1
subtitles_multi = 1
subtitles_extra_scripts = ""

which one do you want me to change?

**Comment by mediarox** [comment]
@NicoLeOca please use @medariox instead :)

**Comment by NicoLeOca** [comment]
oups! :-P

**Comment by medariox** [comment]
@NicoLeOca 
Sorry for not being very clear in my previous message.
It would be great if you could modify this line of code: https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/tv.py#L1460
in your sickrage folder /sickbeard/tv.py
Where it says "subtiles=False" to "subtitles=True", restart SickRage and see if that solves the problem, as I'm currently unable to find a file with embedded subtitles.

**Comment by NicoLeOca** [comment]
@medariox 
It has fixed it
another log:
https://gist.github.com/27e377583e17eb8b7985.git

**Comment by NicoLeOca** [comment]
@medariox 
sorry a typo here
I isn't fixed

**Comment by medariox** [comment]
I know what the issue is now. Will commit a PR later today or tomorrow. Thanks for the bug report @NicoLeOca

**Comment by medariox** [comment]
So, just submitted a PR that fixes the bug.

A few things that I'd like to clarify:
- Support for embedded subtitles most probably never really worked, as the logic behind it was completely ineffective.
- Some embedded subtitles are not being correctly recognized by subliminal (actually enzyme: https://github.com/Diaoul/enzyme) and will be tagged as "und" (undefined), in that case the correct subtitle will be downloaded. There is nothing we can do to solve this, I guess it depends on how the subtitle has been embedded.
- The embedded subtitles can now be effectively ignored (probably never really worked either)

**Comment by NicoLeOca** [comment]
Thank you @medariox 
I'll give a try later today, without much expections then.

**Comment by miigotu** [comment]
@medariox it did work before, because it was only scanned one time, with the proper path to the video.

**Comment by medariox** [comment]
Well, I wouldn't be that negative. From what I can see scene groups (e.g. IMMERSE) do it properly as they have strict standards and rules, so most embedded subtitles should be correctly recognized.

@miigotu You sure about that? The only function that was being used before was subliminal.video.scan_subtitle_languages and that does not work for video files, as it only scans directories. I might be wrong, but from the old code there was no way it could have worked properly.

**Comment by miigotu** [comment]
idk. don't care really as long as its working now =¶

**Comment by NicoLeOca** [comment]
Hi,

It isn't fixed unfortunately.
After I updated to last master yesterday, it downloaded all subtitles where there were embedded subtitles previously detected
here is the log
https://gist.github.com/c82e1eac30eef58cb204.git

**Comment by miigotu** [comment]
@medariox

**Comment by medariox** [comment]
@NicoLeOca 
Please tell me a few releases that don't work for you.

**Comment by NicoLeOca** [comment]
@medariox 
these as mentionned above:
The.Mindy.Project.S03E08.Diary.of.a.Mad.Indian.Woman.720p.WEB-DL.DD5.1.H.264-SA89
The.Mindy.Project.S03E19.720p.HDTV.x264-IMMERSE
The.Mindy.Project.S03E20.720p.HDTV.x264-IMMERSE

also those 2 had subtitles downloaded after last update.
downton.abbey.s01e01.720p.bluray.x264-shortbrehd
Hell.on.Wheels.S01E01.720p.BluRay.X264-REWARD

**Comment by NicoLeOca** [comment]
@medariox 
I had this error two during last night:
 2015-09-21 03:20:44 SHOWQUEUE-REFRESH :: 295980: Could not refresh subtitles

**Comment by medariox** [comment]
@NicoLeOca 
I can confirm it was still buggy, sorry for that. I have it fixed for good now and will commit a PR later today.
About the error: most probably you are using a relative path and never downloaded a subtitle for a show, that causes SickRage to ignore the creation of the subtitle folder. The consequence is that the folder is missing and that's why SickRage is complaining. I don't think it is a good idea to suppress the error, so either you create the folder yourself (keeping it empty, if you like) or you just download at least one subtitle for every show while you are using relative paths.

**Comment by medariox** [comment]
@NicoLeOca Just submitted a PR that should fix the bug. Let me know how it works for you.

**Comment by NicoLeOca** [comment]
@medariox 
Hi, It's getting better.

These are ok:
The.Mindy.Project.S03E19.720p.HDTV.x264-IMMERSE
The.Mindy.Project.S03E20.720p.HDTV.x264-IMMERSE

2 other cases:
1. embedded not detected:
Hell.on.Wheels.S01E01.720p.BluRay.X264-REWARD
downton.abbey.s01e01.720p.bluray.x264-shortbrehd

2. embedded detected but language not recognized
The.Mindy.Project.S03E08.Diary.of.a.Mad.Indian.Woman.720p.WEB-DL.DD5.1.H.264-SA89
The.Mindy.Project.S02E19.Think.Like.a.Peter.720p.WEB-DL.DD5.1.H.264
and many others as well

here is the log:
https://gist.github.com/5b468cbde9e21965b8f3.git

**Comment by miigotu** [comment]
and you wonder why I removed relative paths and simplified the process.... I had subtitles not generating any new issues.

**Comment by NicoLeOca** [comment]
these exact same files used to work

**Comment by medariox** [comment]
@NicoLeOca 
Yes, as I already said the subtitles have to be properly embedded or they will be recognized as "und" by subliminal. Again, it is very unlikely that it ever worked as expected. Subliminal didn't change, if the subtitles are not being recognized now, I don't see how they used be recognized in the past. Are other embedded subtitles being correctly recognized?

@miigotu 
This has nothing to do with relative paths. Embedded subtitle recognition most probably just never really worked.

**Comment by medariox** [comment]
Ok, I installed the newest CLI version of subliminal (1.0.1) and it confirms my doubts: embedded subtitle recognition didn't work before. It works now, but only for files that are properly embedded of course. That's the only way subliminal is going to recognize them, otherwise they will be tagged as "und" (undefined) or not recognized at all. There is nothing that can be done about this, maybe you can ask in https://github.com/Diaoul/subliminal for support.

To test with the CLi version: pip install subliminal
subliminal download -l en The.Mindy.Project.S03E08.Diary.of.a.Mad.Indian.Woman.720p.WEB-DL.DD5.1.H.264-SA89 
Subtitle is downloaded (aka embedded subtitle is not recognized)

subliminal download -l en The.Mindy.Project.S03E19.720p.HDTV.x264-IMMERSE
Subtitle is not downloaded (aka the embedded subtitle is correctly recognized)

**Comment by miigotu** [comment]
@medariox they did work before but OK. we handled und.

**Comment by medariox** [comment]
@miigotu 
What do you mean by that? Did you ignore und or replaced it with the wanted language? I don't see how that can be properly handled tbh, but if it was there it can be surely reintroduced...

**Comment by NicoLeOca** [comment]
Maybe @Diaoul can comment and help us here.
I thought that enzyme was the one to get video metadata
https://github.com/Diaoul/enzyme

**Comment by Diaoul** [comment]
und means the subtitle track in mkv doesn't have a language defined.
Use mkvinfo and compare with what subliminal/enzyme recognize. If there is an error report it to enzyme.

**Comment by miigotu** [comment]
@medariox could check the release_name

**Comment by NicoLeOca** [comment]
The.Mindy.Project.S03E08.Diary.of.a.Mad.Indian.Woman.720p.WEB-DL.DD5.1.H.264-SA89 

Sickrage:
![image](https://cloud.githubusercontent.com/assets/9487685/10106769/eb7c5e74-63b6-11e5-8cdc-61544b44b799.png)

Mkvtoolnix:
![image](https://cloud.githubusercontent.com/assets/9487685/10106867/74c4ad6c-63b7-11e5-9bd8-ffc61dc5c857.png)

Files:
![image](https://cloud.githubusercontent.com/assets/9487685/10106878/89c8e94e-63b7-11e5-96d0-03c57bd71aff.png)

**Comment by medariox** [comment]
@miigotu So what can we do with the release name? I really have no clue here.
@NicoLeOca Seems like no language is defined? What does the IMMERSE release look like?

**Comment by miigotu** [comment]
@medariox in his file there if you look up from where he has highlighted on the left, it shows the sub lang defined as `eng` which is proper.

**Comment by medariox** [comment]
@miigotu Yeah, seen that, but I don't know if it is enough for enzyme to correctly recognize it. So I guess there is something wrong with subliminal/enzyme, since the newest CLI version doesn't recognize it as well.

**Comment by NicoLeOca** [comment]
@medariox 
@miigotu 
Guys I must apologize here.
I just noticed that I was still on master.
a couple of restart ago, I switched to develop from the UI though...
My bad I didn't check then

And I try to switch to develop now with no success..

**Comment by NicoLeOca** [comment]
I now got the 2 branches in parallel so that I can run a few tests
so from now on, I can tell I run
BRANCH: (develop) / COMMIT: (535762723ec6572413b9a49f197b6392eb7e0da8) 
I set up SR to download french subtitles in develop, instead of english in master.
It should help me to get more information.

And it starts well:
there are no embedded subtitles in these videos
![image](https://cloud.githubusercontent.com/assets/9487685/10113063/fbd2646a-63e0-11e5-9bd7-85069f5a3801.png)
![image](https://cloud.githubusercontent.com/assets/9487685/10113077/1c2f37ba-63e1-11e5-9c1a-a743362e061e.png)

Where does the french flag come from?!? :-)
It drives me crazy

**Comment by NicoLeOca** [comment]
deleted and added the show changing language code from 2 to 3 letters in external subtitles

hell.on.wheels.s03e01.720p.bluray.x264-reward.en.srt
to
hell.on.wheels.s03e01.720p.bluray.x264-reward.eng.srt

still the french flag instead of the Union Jack...

**Comment by Diaoul** [comment]
There is no language defined in the MKV so there is nothing enzyme can do. The screenshot from @NicoLeOca can confirm that.
The fact that you see eng grayed out is in case you want to add this element, the combobox defaults to the eng language.

So enzyme parses this correctly and subliminal does its job with the information it has.

**Comment by miigotu** [comment]
agreed

**Comment by NicoLeOca** [comment]
I do agree too
the last screenshots decribe an issue which has nothing to do with embedded subtitles.
It would need to be fixed prior to more tests around embedded.

Do you have ideas for a workaround?
@medariox  I understand it isn't of high priority, let me know if you are willing to carry out some further investigations; I'll do my best to support

**Comment by medariox** [comment]
Thank you Diaoul for finally clarifying this.

@NicoLeOca 
I would like to help you, but I don't really understand what you did to get to that point.
Can you please start fresh with master and explain your steps to get to that point?

**Comment by NicoLeOca** [comment]
@medariox 
I erased everything and installed SR again
BRANCH: (master) / COMMIT: (41dfcaeaf855297d6a478355746d6b769ca8b0da) 
I set up SR to dl subtitles in french
Then added a show:
![image](https://cloud.githubusercontent.com/assets/9487685/10118276/f7165208-6474-11e5-8c7c-2eaa102a8aba.png)

and got this:
![image](https://cloud.githubusercontent.com/assets/9487685/10118306/2165fb58-6475-11e5-8d74-78cccb9cd5aa.png)

here is the log file.
https://gist.github.com/b4dfe923f09e6fba778a.git

FYI : to make sure, I did it twice; and the issue twice...

**Comment by medariox** [comment]
@NicoLeOca 
So what's exactly the problem here? SR is downloading the subs in EN instead of FR?
I need to know:
- What are you trying to achieve?
- What result do you get?
- What do you actually expect?

**Comment by NicoLeOca** [comment]
@medariox 
external subtitles were there before I add the show into SR.
and SR recognize them as french dispite the language code in the filename

**Comment by medariox** [comment]
@NicoLeOca 
The code in the file name has nothing to do with the actual subtitle language. You have to look inside the subtitle file. Are these really EN or rather FR subtitles?

**Comment by NicoLeOca** [comment]
@medariox 
You sure?
It's the first time I hear that and I didn't find anything in the subs
here it is, if you want to have a look yourself:
https://gist.github.com/4c6e553cabab80407b8b.git

**Comment by miigotu** [comment]
The subtitle file is done by the filename, the video is done by the tags in the file (not the name)

**Comment by miigotu** [comment]
@NicoLeOca if SR cant detect the language correctly, and you have only one language selected, it will assume it is your selected language (to avoid ?)

**Comment by NicoLeOca** [comment]
@miigotu 
it might be very useful for SR to detect the language of the subtitles.
But why SR doesn't detect the language code in the file name?
As far as I remember SR used to do it

**Comment by miigotu** [comment]
It does.

**Comment by miigotu** [comment]
unless @medariox broke it =P. there is no indication of a language INSIDE of a subtitle file itself. The file name is all we have and is parsed by subliminal.

**Comment by NicoLeOca** [comment]
He tries to get rid of me :-P

SR didn't detect the language code in the filenames above.

**Comment by NicoLeOca** [comment]
that might explain the issue when there are embedded and external subtiles (like earlier in this conversation)

**Comment by medariox** [comment]
Is it my fault if people code this kind of crap? https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/subtitles.py#L117-L118 
I mean... I don't even know how that has ever worked out until now. If you have one language you want, then it is always going to be it? Very strange thinking right there. Anyway, I did honestly think that subliminal had a more clever way of determining the subtitle language, but I was obviously wrong.

I will submit a PR later today or tomorrow with the two lines removed (that also explains why it was no problem with multiple subtitle languages).

**Comment by miigotu** [comment]
That hack was not a big issue before detecting embeded languages that way. If a subtitle file was in the subs folder and was the only one, and the user had only one selected, it was assumed SR downloaded it and that it was the language the user wanted.

This is because of people complaining about getting a '?' in their subtitle list and history.

**Comment by medariox** [comment]
@miigotu 
If the '?' is a problem we should trim it from https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/subtitles.py#L108
That way it won't brake the rest of the subtitle recognition... but, is it really a problem?

**Comment by NicoLeOca** [comment]
There are a couple of issues regarding subtitles (external and embedded).
Fixing the language code recognition in filenames is a first step in the process to have something proper.
it depends on your other priorities.

**Comment by medariox** [comment]
@NicoLeOca 
Which issues? Code recognition is working fine for only one subtitle language now as well. Update your develop branch.

**Comment by NicoLeOca** [comment]
I saw your commit but as you didn't know it was enough to fix it.
Develop updated and I do confirm that language code in filename is properly recognized now

Thank you @medariox 

as it is fixed now, I can carry on a few tests regarding this:
https://github.com/SiCKRAGETV/sickrage-issues/issues/2774#issuecomment-143282841

**Comment by NicoLeOca** [comment]
The.Mindy.Project.S03E19.720p.HDTV.x264-IMMERSE
The.Mindy.Project.S03E20.720p.HDTV.x264-IMMERSE

the subtitles detection is strange:
both have embedded subtitles, but only one of them has an external srt file:
![image](https://cloud.githubusercontent.com/assets/9487685/10124837/70da1192-6560-11e5-8f9d-e9d00143d948.png)

but I get this:
![image](https://cloud.githubusercontent.com/assets/9487685/10124833/5d65426c-6560-11e5-8d93-67edde9156e3.png)

Which subtitles are not detected for the 19th episode? embedded or external

logs: https://gist.github.com/5f744671b158c3d284f0.git

**Comment by miigotu** [comment]
@NicoLeOca if ep 19 also has english it is only going to show each language once. You're getting a little picky now.

**Comment by NicoLeOca** [comment]
thank you @miigotu 
this was just a question, not a request nor a complain.. ;-)

**Comment by NicoLeOca** [comment]
FYI, I just noticed that only the 2 letters language code was identified in filenames, not the 3 letters.

Episode 1 and 2: 3 letters code
Episode 3 and 4: 2 letters code

![image](https://cloud.githubusercontent.com/assets/9487685/10125358/574de648-6571-11e5-9fa8-a4be06e46ab2.png)
![image](https://cloud.githubusercontent.com/assets/9487685/10125362/6d27e96e-6571-11e5-8be1-db83f37346be.png)

**Comment by miigotu** [comment]
Do your subtitles download? Stop worrying about it so much for now. It is being rewritten again for the next subliminal version anyways so fixing it now doesnt really help.

**Comment by NicoLeOca** [comment]
they do and always did.
I only tried to understand why detection of embedded subtitles wasn't accurate.
It is linked more to enzyme which won't be updated with subliminal.

I am stuck anyway. I can't make further tests and I can't help more. I'd love to know how to code...

Thank you @medariox for what you've done already

**Comment by medariox** [comment]
@NicoLeOca 
Once again this is a limitation of subliminal and there is nothing that can be done about it.
```
subliminal.video.scan_subtitle_languages(path)
```
scan_subtitle_languages takes only alpha2 extensions. Another thing that I don't understand how it was supposed to work in the past.

**Comment by NicoLeOca** [comment]
I don't know if the 3 letters code used to work. I never tried before.
I tested it by mistake so I shared the results
