### ISSUE TITLE
[Feature Request] Differenciate and ignore forced subtitles

### ISSUE THREAD

**Issue by NicoLeOca** [SiCKRAGETV/sickrage-issues#2775]
Hi,

This one is for those who watch tvshows in foreign language, but with full subtitles (if you are not fluent in this very language).
In this case, forced subtitles are of no use for you.

Would it be possible for SR to detect it and download the full subtitles consequently?

Regards

NicoLeOca

**Comment by WebSpider** [comment]
Personally,I just add "subs" and "subbed" to ignorelist and enable subtitle downloader ... so I'd say we already do this :)

**Comment by miigotu** [comment]
We already have a subtitle downloader thread.
