### ISSUE TITLE
Hounddawgs provider seems broken

### ISSUE THREAD

**Issue by InterCast** [SiCKRAGETV/sickrage-issues#2776]
Branch: master
Commit hash: 2e08ee65e83f74f9958d9305b697ad27c0820cc5
Your operating system and python version: Windows Server 2012R2 Standard, Python version 2.7.10
What you did: Tried searhing manually for a torrent I know exists on that given provider
What happened: The error in logfile "The Data returned from HoundDawgs do not contains any torrent"
What you expected: The provider to find, and snatch the torrent.
Link to a copy/paste of your logfile with clear debug info of the error on GIST: https://gist.github.com/InterCast/083dac7d2adcb0ea89c9

I took the liberty to change the default error message, to the full returned data value, as mentioned by fernandog in issue 1019, to speed up the process.

It seems to me like it returnes the logon page, in HTML format.

**Comment by fernandog** [comment]
@InterCast still an issue? without a account we can't fix it

**Comment by InterCast** [comment]
@fernandog Sorry, I totally forgot about this. I created this issue, because I'm not the best in python and therefore gave others the opportunity to help out. In addition to that, I'm pretty green in terms of GitHub, and protocols here.
But - to answer your question, NO, the issue has resolved itself in the meantime. I don't know if you changed the useragent, or the website changed the way it interprets the useragent reported by SR. 
Close up here.
