### ISSUE TITLE
Sickrage user agent broken against rarbg/torrrentapi

### ISSUE THREAD

**Issue by rarbg** [SiCKRAGETV/sickrage-issues#2778]
Hey guys
@fernandog @abeloin @miigotu
Can you please fix the user agent sickrage sends to torrentapi ?
Currently something is very broken , the user agent im seeing in logs is very long and messed up
string "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.1 Safari/537.36Mozilla/5.0 (Windows NT 6.3; rv:36.0) Gecko/20100101 Firefox/36.0Mozilla/5.0 (X11; Linux i586; rv:31.0) Gecko/20100101 Firefox/31.0Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.75.14 (KHTML, like Gecko) Version/7.0.3 Safari/7046A194AMozilla/5.0 (iPad; CPU OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5355d Safari/8536.25Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; AS; rv:11.0) like GeckoMozilla/5.0 (compatible, MSIE 11, Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko"
:>

**Comment by miigotu** [comment]
will check this later. seems all of the potential user agents are getting sent rather than just one.

this is from a commit I did the other day to add uniformity among logins to providers.

**Comment by rarbg** [comment]
@miigotu 
Thanks! Can you switch it to the previous sickrage one when you have time?

**Comment by miigotu** [comment]
Yes I will override it in rarbg provider.

**Comment by rarbg** [comment]
Thank you

**Comment by flightlevel** [comment]
This should be fixed now https://github.com/SiCKRAGETV/SickRage/commit/e1e4c284e10f13cebf4277bbd6924d6d5085d1ce

**Comment by rarbg** [comment]
Thank you :)

**Comment by miigotu** [comment]
yeah NP, just trying to make all of the providers more uniform, and most of them require a browser UA so I made the torrent providers' default UA a random browser string. Overriding for individual providers is easier this way and needs less overrides.

**Comment by rarbg** [comment]
sending random uas from the same ip to providers behind cloudflare will simply make cloudflare popup captcha checks for bot prevention :)

**Comment by miigotu** [comment]
it only changes the UA on a restart so I think it might be OK. they are actual real UA's for chrome, IE, Firefox, and safari.
