### ISSUE TITLE
[APP SUBMITTED]: Thread-43 :: Checkout branch couldn't compare DB version.

### ISSUE THREAD

**Issue by AcerTravel** [SiCKRAGETV/sickrage-issues#2779]
### INFO
Python Version: **2.7.10 (default, Jul  8 2015, 08:04:18) [GCC 4.3.6]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@2e08ee65e83f74f9958d9305b697ad27c0820cc5
Link to Log: https://gist.github.com/74e7f15c22db72af8e7b
### ERROR
```
Thread-43 :: Checkout branch couldn't compare DB version.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by WebSpider** [comment]
How did you install SR?

**Comment by miigotu** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/2501

**Comment by kendog819** [comment]
@miigotu @WebSpider 

I am having this same problem. On both the qpkg install and using windows installer, separate machines.

Are we just waiting on the fix to get pushed to master?

Thanks

**Comment by crow50** [comment]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@df074006606f9185acb8bf07098dc545f2357b26
Link to Log: https://gist.github.com/0f0872ee415087409da0
### ERROR
```
Thread-32 :: Checkout branch couldn't compare DB version.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
