### ISSUE TITLE
Trouble manually post-processing file that does in fact exist (Error: No processable items found in folder)

### ISSUE THREAD

**Issue by rEes9P** [SiCKRAGETV/sickrage-issues#2780]
**Branch:** master
**Commit hash:** 2e08ee65e83f74f9958d9305b697ad27c0820cc5
**OS:** Mac OS X 10.10.5
**Python version:** 2.7.10 (default, Jul 14 2015, 19:46:27) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
**What I did:** Tried to manually post-process some episodes
**What happened:** I get the error message "No processable items found in folder". There is a .mkv file in the folder and I have checked to see that it plays without any issues.
**What I expected:** I expected the episodes to post-process successfully.
**Debug log:** https://gist.github.com/rEes9P/6049695ce31615f25b89

I remember running into a similar situation earlier, which was then fixed. A recent update seems to have again altered/broken some of the post-processing functions.  When I ran into a similar problem earlier I was asked to set the episode status to wanted. At the moment the default episode status for the show is set to wanted and the episode status for the episodes in question is also set to wanted.

**Comment by WebSpider** [comment]
Please post the contents of the folder The.Pacific.2010.EP01.BluRay.720p.DTS.x264-CHD

**Comment by rEes9P** [comment]
Thank you for your help, WebSpider. The folder The.Pacific.2010.EP01.BluRay.720p.DTS.x264-CHD only contains one file, The.Pacific.2010.EP01.BluRay.720p.DTS.x264-CHD.mkv. The folder The.Pacific.2010.EP02.BluRay.720p.DTS.x264-CHD contains The.Pacific.2010.EP02.BluRay.720p.DTS.x264-CHD.mkv and so on for all the other episodes too.

**Comment by miigotu** [comment]
SR requires a season in the filename if not using absolute numbering.

**Comment by rEes9P** [comment]
I changed the filename of the episode 1 folder and file to The.Pacific.2010.S01E01.BluRay.720p.DTS.x264-CHD (the file has a .mkv extension) in order to include the season number and now get the *This show isn't in your list, you need to add it to SB before post-processing an episode* error. Here is the debug log.
https://gist.github.com/rEes9P/e09cfe06390ca0efcb3c

I mentioned this error in another issue filing (https://github.com/SiCKRAGETV/sickrage-issues/issues/2761) which was closed. I wonder if they are related.

**Comment by miigotu** [comment]
then The Pacific 2010 isn't in your show list

**Comment by rEes9P** [comment]
I do have The Pacific in my show list but it is listed as The Pacific and not The Pacific (2010). Could that be the reason? When I do a search for a new show The Pacific (2010) does not come up as one of the options.

**Comment by flightlevel** [comment]
@rEes9P 
Have you tried adding a scene exception?
https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained#shows-edit-button
https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering

So under scene exceptions you would add
The Pacific
The Pacific 2010

**Comment by miigotu** [comment]
Actually, you don't add the name of the show you already have, you just add:

The Pacific 2010

If you add both names to scene exceptions SR would search for The Pacific string twice.

**Comment by flightlevel** [comment]
@miigotu 
Are you sure? In SR it says it overrides http://imgur.com/L0wyWeM

**Comment by miigotu** [comment]
I'll look at it, but AFAIK from recollection of the code it does append on most providers

**Comment by rEes9P** [comment]
I added The Pacific 2010 to my scene exception list. I am now getting the *No processable items found in folder* error again.

Just to be sure, I have the default episode status is wanted, as is the status of the individual episodes in question. I also renamed episode 1, as mentioned above, to contain the season number in the folder and file name.

Here is the latest debug log.
https://gist.github.com/rEes9P/88e40a87c6e17708848f

**Comment by flightlevel** [comment]
Can you put all the video files in one folder and then give us a list of the filenames in the folder

**Comment by rEes9P** [comment]
I put all the video files in one folder and tried to manually post-process that just to see if it worked and it did! Here is the debug log.
https://gist.github.com/rEes9P/8fb14cbbcc10073824d3

Episode 1 was the only episode that had the season number mentioned. It would be nice to not have to manually put all the files in one folder. I am wondering why SickRage didn't deal with this as it does with other shows.

**Comment by flightlevel** [comment]
@rEes9P 
Good that you didn't have to rename them in the end.

Its definitely a strange one. SR does iterate through the sub folders.
From your first log, you can see that its is bombing out at the `ValidateDir()` method. https://github.com/SiCKRAGETV/SickRage/blob/c9729676cdbd2af5b04337b239bb3a843f5feaa4/sickbeard/processTV.py#L360 Need someone smarter than me to figure out why

**Comment by rEes9P** [comment]
@flightlevel 

Each folder contained only one file, the .mkv. Each file was named in the format The.Pacific.2010.EP02.BluRay.720p.DTS.x264-CHD.mkv and so on and so forth.
