### ISSUE TITLE
[Feature Request] Bulk Notification for Snatching Season Packs

### ISSUE THREAD

**Issue by Megagator** [SiCKRAGETV/sickrage-issues#2783]
Currently, when a season of a show is snatched, a "Started Download..." notification is sent for each episode of the season. Instead, one notification should be sent for the whole season. 
Similarly, on post-processing of that season, just one notification should be sent on completion instead of one for each episode

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
