### ISSUE TITLE
[APP SUBMITTED]: SHOWQUEUE-ADD :: Check scene exceptions update failed. Unable to get URL: https://raw.githubusercontent.com/SiCKRAGETV/sr_tvrage_scene_exceptions/master/exceptions.txt

### ISSUE THREAD

**Issue by pichorra** [SiCKRAGETV/sickrage-issues#2784]
### INFO
Python Version: **2.7.3 (default, Mar 31 2015, 15:16:49) [GCC 4.9.2]**
Operating System: **Linux-3.18.10-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@
Link to Log: https://gist.github.com/11b723a4bd162d983a8f
### ERROR
```
SHOWQUEUE-ADD :: Check scene exceptions update failed. Unable to get URL: https://raw.githubusercontent.com/SiCKRAGETV/sr_tvrage_scene_exceptions/master/exceptions.txt
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by WebSpider** [comment]
Please make sure that you are up-to-date, and et us know which commit you are on

**Comment by pichorra** [comment]
hello, you wonder if the stickrage this date?

2015-09-12 17:54 GMT-03:00 Nils <notifications@github.com>:

**Comment by flightlevel** [comment]
@pichorra If your SickRage is looking for tvrage you must be on an old version.
Click Check for updates in SickRage and then update.

**Comment by pichorra** [comment]
Thanks for the quick responses.
However when I update it, it does not work anymore.
the installation is recent, I used the repository.lsellens repository in openelec.

**Comment by flightlevel** [comment]
"However when I update it, it does not work anymore."
Is not helpful.

If you are getting that error, you are on an old version, we can only help if you are on the latest version
