### ISSUE TITLE
Latest update caused SR to sh*t the bed

### ISSUE THREAD

**Issue by richbutler1** [SiCKRAGETV/sickrage-issues#2785]
Error on reboot.  Just did a routine update through UI.  Was all caught up except for ~30+ commits as of 9/12/15 9:30pm EST
OS: Win8.1 with GIT and all dependencies

Prior update started generating large # of errors, don't have them.  This prompted me to update to pull most recent commits hoping to resolve.

Error on reload of home page:
Window Title: Mako Runtime Error

Error !
KeyError: ('C__SickRage_gui_slick_views_home_mako', '__anon_0x35a4070')
<%inherit file="/layouts/main.mako"/> <%! import sickbeard import calendar from sickbeard.common import SKIPPED, WANTED, UNAIRED, ARCHIVED, IGNORED, SNATCHED, SNATCHED_PROPER, SNATCHED_BEST, FAILED from sickbeard.common import Quality, qualityPresets, qualityPresetStrings from sickbeard import db, sbdatetime, network_timezones
C:\SickRage\gui/slick/views/home.mako, line 2:
<%!
C:\SickRage\gui/slick/views/home.mako, line 43:
<%block name="scripts">
C:\SickRage\gui/slick/views/layouts/main.mako, line 319:
<script type="text/javascript">
C:\SickRage\lib\mako\runtime.py, line 853:
callable_(context, *args, **kwargs)

**Comment by OmgImAlexis** [comment]
Delete /cache/mako and restart SR, if you're missing images then do a full update on all of your shows.

**Comment by richbutler1** [comment]
Thx Alexis, deleting mako cache folder did the trick.
