### ISSUE TITLE
After updating via Audo, SickRage is no longer working

### ISSUE THREAD

**Issue by chavezoz** [SiCKRAGETV/sickrage-issues#2786]
* Branch - master
* Commit hash - 287a0ebc6019586936e5cce377eaa9fbf7bb7845
* Your operating system and python version - openElec 5.0.8 / python 2.7.3
* What you did - Auto update via Audo add-on
* What happened - SB won't start up. Automatically or manually.
* What you expected - SB to start.
* Log file - https://gist.github.com/chavezoz/e53fc97ab47233b394c4

Reported here as well with more details around the issue: http://openelec.tv/forum/80-sabnzbd-suite/78152-unable-to-bring-up-sickrage-page-after-autoupdate?start=15#147595

**Comment by flightlevel** [comment]
You're missing distutils.util

Never used openelec but try running
sudo apt-get install python-distutils

Or google how to install distutils

**Comment by miigotu** [comment]
openelec doesn't have apt-get. only option is to update to a recent Milhouse build of openelec
