### ISSUE TITLE
[Develop] Display fuzzy dates showing but setting is disabled.

### ISSUE THREAD

**Issue by neoatomic** [SiCKRAGETV/sickrage-issues#2796]
Currently the show overview page, shows `fuzzy dates` even when disabled in the setting.

![naamloos](https://cloud.githubusercontent.com/assets/7928052/9837562/4e278cd8-5a43-11e5-917d-e0a0b9d20a6f.png)

```
SR Version: 	BRANCH: (develop) / COMMIT: (101edeeabd517eef205ab366450f784aa3d0b367)
SR User:	sickrage
SR Locale:	(None, None)
SR Config file:	/usr/local/sickrage/var/config.ini
SR Database file:	/usr/local/sickrage/var/sickbeard.db
SR Cache Dir:	/usr/local/sickrage/var/cache
SR Log Dir:	/volumeUSB1/usbshare/Temp
SR Arguments:	['--daemon', '--pidfile', '/usr/local/sickrage/var/sickrage.pid', '--config', '/usr/local/sickrage/var/config.ini', '--datadir', '/usr/local/sickrage/var/', '--nolaunch']
Python Version:	2.7.10 (default, Jun 3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]
```

**Comment by neoatomic** [comment]
@OmgImAlexis https://github.com/SiCKRAGETV/SickRage/commit/d1056059c94316352d760439d146e268f75c82b0 ?

**Comment by OmgImAlexis** [comment]
Yep, we need to enforce either tabs or spaces. It's a indenting bug. Fixed in my dev branch, will be merged within a few days.

**Comment by miigotu** [comment]
spaces! everywhere!

**Comment by OmgImAlexis** [comment]
@miigotu is there anything in Travis to force spaces instead of tabs?

**Comment by miigotu** [comment]
Travis doesn't change code. need to make SR lintable and then we can have Travis run lint and check for tabs.

I guess we could have Travis grep for any tabs and fail the build by grep output but thats suboptimal

**Comment by neoatomic** [comment]
@OmgImAlexis I see that the fuzzy dates are also not named/showing correctly.
They say `26 day ago` etc. but should be `26 day to go` (till airing) 
Almost if the naming for the `Prev ep` column is used in the `next ep` column.

![1](https://cloud.githubusercontent.com/assets/7928052/9889708/179f29ae-5bfc-11e5-8ee8-9d5e8f39e06a.png)

**Comment by OmgImAlexis** [comment]
@neoatomic this "should" be fixed on https://github.com/SiCKRAGETV/SickRage/pull/2507 let me know if it isn't.

**Comment by OmgImAlexis** [comment]
@neoatomic can you confirm yours looks like this now?

![screen shot 2015-09-16 at 8 51 51 am](https://cloud.githubusercontent.com/assets/6525926/9892879/4c8b75a4-5c52-11e5-823d-9f2589b80f0c.png)

**Comment by neoatomic** [comment]
@OmgImAlexis Needed to clean my maco/sessions folders before it worked.
Looks like all is fine now. Thanks. :)
