### ISSUE TITLE
Tabulation of Shows page is buggy

### ISSUE THREAD

**Issue by CentristOuevre** [SiCKRAGETV/sickrage-issues#2798]
**Branch**: Master
**Commit hash**: (7694b70047796dc0c9c812300a090f78a4240f46) 
**OS**: debian wheezy armhf (Raspberry Pi Model B)
**Python version**: 2.7.3
![sickragetabulationbug](https://cloud.githubusercontent.com/assets/3770412/9837884/61ae235a-5a45-11e5-9501-e62e4df9487e.png)

**Comment by fernandog** [comment]
Fixed in develop. Wait next release
