### ISSUE TITLE
[APP SUBMITTED]: Loaded module _usr_local_Sick_Rage_gui_slick_views_home_mako not found in sys.modules

### ISSUE THREAD

**Issue by MyCatHasEyes** [SiCKRAGETV/sickrage-issues#2799]
### INFO
Python Version: **2.7.6 (default, Aug 30 2015, 13:18:25) [GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]**
Operating System: **Linux-2.6.32-573.1.1.el6.x86_64-x86_64-with-centos-6.7-Final**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@7694b70047796dc0c9c812300a090f78a4240f46
Link to Log: https://gist.github.com/ca9c7e61b5d19fdac351
### ERROR
```
Thread-14 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/local/Sick-Rage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/usr/local/Sick-Rage/sickbeard/webserve.py", line 718, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/usr/local/Sick-Rage/sickbeard/webserve.py", line 113, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/local/Sick-Rage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/local/Sick-Rage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/usr/local/Sick-Rage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _usr_local_Sick_Rage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by flightlevel** [comment]
Same as https://github.com/SiCKRAGETV/sickrage-issues/issues/2790

Have you tried clearing your cache?

-Find the location of your cache folder by going to Config -> Help & Info in SickRage
-STOP SickRage and give it a chance to shutdown
-Delete all the folders in the cache folder except images folder
-Start SR

**Comment by mikeo999** [comment]
Problem is still active

https://github.com/SiCKRAGETV/sickrage-issues/issues/2781
