### ISSUE TITLE
[Feature Request] Set priorities for individual search priorities (torrent vs. nzb)

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#28]
<a href="https://github.com/chqp"><img src="https://avatars.githubusercontent.com/u/9638994?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [chqp](https://github.com/chqp)**
_Monday Dec 01, 2014 at 03:12 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/996 (10 comment(s))_

----

an option to define general and show-based search rules/priorities would be helpful. ie. whether SB should focus on torrents or nzbs first.

**Comment by SickrageDK** [comment]
Really hope this functionality will be implemented

**Comment by SickrageDK** [comment]
anyone looking into this?

**Comment by fernandog** [comment]
@SickrageDK no. fixing bugs (a lot ) first. we need a stable master first. if you want to help pick a open confirmed issue and try to make a PR

**Comment by dirkr07** [comment]
Just to add interrest. Would love the "provider/show" option!

**Comment by xbiggyl** [comment]
+1
IMO the only missing feature.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
