### ISSUE TITLE
View Popular Shows button missing from Add Show button

### ISSUE THREAD

**Issue by JeremiahGillis** [SiCKRAGETV/sickrage-issues#2800]
The popular shows button from the Add Show button is missing. I am running 4.0.58 (2015-09-09) on FreeBSD. I don't see anything in the changelog mentioning that it was removed or disabled for now. Can anyone else confirm my issue? I restarted SR, but the button is still missing.

BRANCH: (master) / COMMIT: (7694b70047796dc0c9c812300a090f78a4240f46)
Python Version:	2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]
OS: FreeNAS 9.3.1, FreeBSD

**Comment by neoatomic** [comment]
Just checked, and indeed the button is missing.

**Comment by miigotu** [comment]
use_imdb_popular=1 in INI.

**Comment by flightlevel** [comment]
Should this be even an option? If so, shouldn't it default to =1 otherwise no one will know about it.

**Comment by miigotu** [comment]
once it is past incubation yes. but not until then.

**Comment by flightlevel** [comment]
No worries, didn't realise it was still being tested.

**Comment by JeremiahGillis** [comment]
I didn't either. I used it the other day, then I noticed that the button disappeared when I tried to use it today.

Then I went to https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained which shows the button. If I really need it, I can change the INI since you showed me where it is.

Thanks

**Comment by AubreyKloppers** [comment]
@miigotu thanks for the guide.  I found this most useful in my testing a week ago.  I am now live and actually missed the little bugger ;)

**Comment by WebSpider** [comment]
This is weird. The ini value defaults to 1, and we have no code that I know of which disables this feature?

-----Original Message-----

**Comment by miigotu** [comment]
@WebSpider strange yes. I see it was added to the saveNotifications method in webserve.py, with a default value of None, and saves a 0 to config when saving notifications. (How that got there idk)
