### ISSUE TITLE
Random blank column on homepage.

### ISSUE THREAD

**Issue by danielmason30** [SiCKRAGETV/sickrage-issues#2803]
![2015-09-14 00_28_39-sickrage - branch_ master - home](https://cloud.githubusercontent.com/assets/11175151/9839616/a23bafdc-5a77-11e5-8362-bcf310165790.png)

On Firefox 41.0b9 Windows 10

**Comment by WebSpider** [comment]
Please make sure you add all the needed data from https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md

We need it to see for instance which version you are running.

**Comment by danielmason30** [comment]
![2015-09-16 23_46_07-sickrage - branch_ master - configuration](https://cloud.githubusercontent.com/assets/11175151/9920559/2707901c-5ccd-11e5-88d7-ccf43fc700a4.png)

I have latest master version.
