### ISSUE TITLE
[Feature Request] Allow downloads before airtime on specific shows and/or providers

### ISSUE THREAD

**Issue by jtwill** [SiCKRAGETV/sickrage-issues#2805]
I have had several shows not download until the backlog check because they leaked before the official airtime (or the official airtime was wrong, like for some web broadcast shows).

I realize that for some cases it may be useful to prevent downloading shows before the official airtime, but I find it to be harmful more than helpful. I find it quite annoying to have a show not download simply because SickRage thinks it has not officially aired yet.

SickRage should have a user configurable setting for whether it will download a show before its official airtime. Ideally, it would be a per-show configuration item, but I would settle for a global setting that applies to all shows.

**Comment by neoatomic** [comment]
This will only cause fake episodes to be downloaded, and unnecessary hammering the search providers.
Also if a episode is leaked early (witch happens rarely) than this should be changed on the indexers side so SR knows that it can start searching.

**Comment by WebSpider** [comment]
We may want to think about letting users provide feedback to indexers through us, to make it easier for them to indicate the indexer is faulty, and should be updated.

This would be a separate feature, off course.

**Comment by jtwill** [comment]
> This will only cause fake episodes to be downloaded,

That is not correct. While occasionally a fake episode may be downloaded, that is less frequent compared to the times when real episodes get downloaded before the airtime that SickRage thinks it is. I have had SickRage not download real episodes when they were posted three times already in the past week. It is a real problem. When I used to use SickBeard, it would always download episodes when they were posted, and fake episodes were very rare compared to "early" real episodes.

Besides, I said it should be an OPTION. If a user finds too many fake episodes being downloaded, they can always turn it off.

> unnecessary hammering the search providers.

I'm not sure what you mean. I'm talking about cases where, during the regular check for shows to download, that there IS a show found, but SickRage simply does not download it because it thinks it is before the airtime. How does this cause "unnecessary hammering"?

**Comment by OmgImAlexis** [comment]
We could always add at least for now a leaked_show list similar to exception so shows that are known as leaked such as ones that appear on torrentfreak can be downloaded.

Something that would be nice is an experimental section of the config for things like this, we could add them to the config.ini but not in the webui and if enough users want/use it then we can add it in for everyone else.

**Comment by jtwill** [comment]
I think adding a list of shows to config.ini would be a hassle and few people would do it. That would be a shame, because the problem is much larger than neoatomic's casual dismissal would seem to indicate. I'm not talking about just pilots or whatever that leak early, and I'm not just talking about shows where they get posted a week early on demand, nor just about Netflix shows where they all show up at once and often before the airtime SickRage expects (although those are both cases where SickBeard should at least provide users the OPTION of getting the show early). I'm also talking about cases where the show posts hours before the airtime and SickRage declines to download it because it is a few hours early. Then I have to wait until the backlog search catches it many hours after airtime.

If any developers do not believe me about the real problem here, then I suggest an experimental setting (like OmgImAlexis mentioned) in config.ini, but rather than listing shows, just have a global setting that removes the override where SickRage finds a show but does not download it because it is before the airtime. If this is enabled, also add logging so we can count how many times this happens. Then we can compare the number of early episodes downloaded against the number of fake episodes downloaded. I think you will find that the ratio of early episodes to fake episodes is quite favorable.

It is really a shame that SickRage is inferior to SickBeard on this issue. One of the things I really like about SickBeard is that I can often watch shows before they are officially broadcast. Makes me feel like a VIP! :-)  But with SickRage, the shows are often not downloaded until many hours AFTER the official broadcast (when backlog search finds them). This makes me very annoyed. Why should SickRage refuse to download perfectly good shows, and actually end up being hours LATE in downloading them, just because a developer has an irrational fear of fake episodes and thinks users should not be given the option to choose whether they are willing to risk a few fake episodes in order to get other episodes early (or at least, not late).

**Comment by jtwill** [comment]
I should add that if you just use quality torrent providers (and avoid NZB indexers), you can drastically reduce the chance of downloading a fake episode.

Considering that SickRage has such good torrent support compared to SickBeard, it is unfortunate that SickRage then hobbles itself by refusing to download early episodes. I am sorely tempted to go back to SickBeard (even though it is just barely maintained these days) just because of this one issue. I don't understand why SickRage developers would immediately shoot down the request of just having an OPTION for users to allow SickRage to download early episodes. It does not seem to be an unreasonable request, nor terribly difficult to implement.

**Comment by OmgImAlexis** [comment]
@neoatomic reopening this for now, I want to try this out. Keep in mind tvdb doesn't like changing shit if they don't agree which means if air dates aren't right and they don't like that you want to change them then there's nothing users can do. That's an issue in itself, if this helps fix that then good. Obviously this feature will only be enabled in a config.ini property until I can get it fully working. I'm also thinking of only enabling it with certain providers that we know can be trusted like BTN and rarbg.

**Comment by fernandog** [comment]
I just check a show that airs 10pm. Now is 23:39pm and its still as unaired. I thought the dailysearcher also converted unaired to wanted. Strange.

**Comment by jtwill** [comment]
I think the first thing to work out is whether enabling early-episode downloading should be a per-show setting, a per-provider setting, or a global setting. How does the implementation difficulty differ among those possibilities?

Another possibility would be to enable or disable it for NZB indexers separately from torrent providers. The NZB indexers would be more vulnerable to fake episodes than torrent providers, so I guess some people might want to disable it for NZB, and enable it for torrents.

**Comment by jtwill** [comment]
frenandog:
Do you have timezone (General config / Interface / timezone ) set to "local" or to "network"?

OmgImAlexis:
Should the timezone setting make a difference as to whether SR considers it an early download?

**Comment by OmgImAlexis** [comment]
@jtwill torrent providers are just as prone, GOT for example had fakes on all my of trackers for months before they released the newest season.

I'd suggest we add it per provider, as a global option and then per show as an override. This is how most settings should be already.

I'm pretty sure timezones don't come into effect for anything todo with downloads. Shows on tvdb should all have their times set as UTC, the same goes for SR checking if downloads are available.

One thing I want to keep in mind is that checking if a show is released means a LOT more hits to providers as we'd be checking every show that's enabled to see if a new episode is available instead of just ones we know are definitely released.

**Comment by jtwill** [comment]
OmgImAlexis:

I agree that the SR timezone setting SHOULD not make a difference. But I was wondering if there was a bug where it did make a difference.

The SR setting from timezone, by how it is described, sounds like it should only affect the display time in the user interface. But could there be a bug in the code where a piece of code mistakenly uses the wrong time, depending on how timezone is set, when it checks whether to download an episode?

As for more checking with providers, I must have misunderstood how the regular search (I am NOT talking about the backlog search now) works. I thought that SR just queried the providers for ALL episodes posted since the last check. For example, if the search interval was set to 10 minutes, then it could query all shows posted in the last 10 minutes. Then SR just looks at that list to see if any of the shows that it has as "wanted" are on that list. If that was how SR did it, that adding a check for any unaired episodes on the list would not result in any additional searches for the providers.

But it sounds like you are saying that SR searches individually for all the wanted episodes? A separate query for each episode?

In that case, I can see how it would increase the number of queries a lot if SR queried for every single unaired episode.

But I know that SickBeard downloaded episodes for me weeks early. How was it doing it? Surely it was not running a query for every single unaired episode every 10 minutes. If it was doing that, I think it would have been banned on a lot of my trackers.

So maybe the question we need to answer is how SickBeard is able to efficiently look for early episodes? Maybe it is using the method I mentioned above?

**Comment by jtwill** [comment]
By the way, I want to clarify the various types of early episodes that I would ideally like SickRage to download as soon as possible after they are posted. Note that when I use the word "airtime" below, I mean the time that SickRage thinks the show is supposed to air:

1) Episodes that post a few hours before the airtime, either because they were capped from an early uplink, or because the airtime is wrong by a few hours

2) Episodes that post up to 24 hours before the airtime, usually because they are "web broadcast" shows that post a whole season at once, and the listed airtime may be inaccurate by nearly 24 hours

3) Episodes that post a few days early, possibly because a satellite uplink was available a few days early, or because it airs a different day of the week (earlier) in another country

4) Episodes that post about a week early because they are made available on-demand the week before the airtime.

5) Episodes that post weeks or months before airtime. These are usually pilots that leak early.

I mention these categories because I used SickBeard for years before I switched to SickRage, and SickBeard downloaded shows early for me in all of those categories.

Ideally, I'd like to see SR download all of these categories early, just like SickBeard. But I listed them in order of priority, with (1) being the most important, in my opinion.

**Comment by OmgImAlexis** [comment]
1. This would include shows where the person updating tvdb is in another timezone from the uploaded version.
2. This would include Netflix shows, I think we should actually add a check if it's a Netflix, Amazon, etc. show and attempt to pull down ALL episodes in the season as they're almost always released this way.
3. Same as first, this happens a lot when Australians set the date/time on tvdb and it's an American show as it's released there about 12 - 15 hours before we get it which with timezones puts it an entire day out of sync.

**Comment by miigotu** [comment]
For one, we dont need this issue unlocked to discuss it as developers.
Second ANY chance of a fake release is unacceptable.

Timezone is the cause of it "being a few hours off", and regardless it should be at most 40 minutes between daily searches before it would snatch it.

Accuracy far outweighs the super low odds of getting an episode early. This is not like movies where leaks happen often.

We cannot allow SR to be that careless, when it has access to overwrite and modify your entire library if it wishes.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
