### ISSUE TITLE
[APP SUBMITTED]: global name 'searchURL' is not defined

### ISSUE THREAD

**Issue by remybien** [SiCKRAGETV/sickrage-issues#2806]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@7694b70047796dc0c9c812300a090f78a4240f46
Link to Log: https://gist.github.com/b24a7824dc944999a1e2
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [BitSoup] :: Failed parsing BitSoup Traceback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/bitsoup.py", line 205, in _doSearch
    logger.log(u"Found result: " + title.replace(' ','.') + " (" + searchURL + ")", logger.DEBUG)
NameError: global name 'searchURL' is not defined

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by flightlevel** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/2804
