### ISSUE TITLE
low quality snatched episode don't appear at backlog. Shouldn't appear?

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#281]
Shouldn't an episode with status SNATCHED but low quality appear at BACKLOG to keep searching for the best quality ?

It will only appear at BACKLOG if the status is DOWNLOADED (low quality) - yellow

@markheloking @neoatomic @Hellowlol @echel0n can you confirm/test please?

thanks!

**Comment by fernandog** [comment]
Doing some tests the code should be:

```
            elif epStatus in (SNATCHED_BEST,SNATCHED,SNATCHED_PROPER) and curQuality == maxBestQuality:
                return Overview.SNATCHED
```

**Comment by markheloking** [comment]
@fernandog can you make a pull request for this?

**Comment by fernandog** [comment]
@markheloking can you tell me if I do a PR changing line 10 and 11 of webserve.py for example and then create another PR changing line 500-510 of webserve.py, will create a kind of conflict or something? I have a PR waiting to be merged that's why I didn't do a PR for this issue

**Comment by markheloking** [comment]
If I'm correct github is smart enough to handle that. Just try and see what happens (you can look at the file changes after/while creating a pull request). If you don't like it, just retract the pull-request.
