### ISSUE TITLE
Archived (Quality)

### ISSUE THREAD

**Issue by Quiksmage** [SiCKRAGETV/sickrage-issues#2811]
I noticed this feature was added recently and I can't wait to put it to use with old shows that have higher qualities on only newer seasons.

When I try to use any of the qualities I get the error 
"Error
Invalid status"

using the old "Archived" still works as do all other qualities.

I assume this is just because it is new, but I wanted to make sure it was noted if not already.

**Comment by strike84** [comment]
Just tried that myself and get the same result, nothing in the log about it tho.

**Comment by miigotu** [comment]
This is known, and an existing issue exists.  This feature is still incomplete for compound archived status'.
