### ISSUE TITLE
Can't add fansub group to whitelist

### ISSUE THREAD

**Issue by Quiksmage** [SiCKRAGETV/sickrage-issues#2813]
When trying to add a fansub group to the whitelist, nothing happens.

I select a group in the middle and click add to whitelist, but nothing moves over. This used to work, so I think I'm doing it correctly.

**Comment by WebSpider** [comment]
@mgaetan89 @omgimalexis this looks like GUI related
@quiksmage can you please follow the guidelines for submitting a new issue, so we have all relevant info to solve this quickly if it is indeed a bug

**Comment by Quiksmage** [comment]
Branch: master
    
Commit hash: 7694b70047796dc0c9c812300a090f78a4240f46
   
Your operating system and python version: Windows server 2012 R2/ Python 2.7.9 x64
    
What you did: Tried to add a fansub to whitelist from either selecting from the anidb created ones or adding one manually.
    
What happened: Nothing was added to whitelist. also appears as though you can't add to blacklist.
    
What you expected: Adding of group to either whitelist or blacklist.
   
 Link to a copy/paste of your logfile with clear debug info of the error on GIST: There appears to be no log entries when selecting the buttons.

**Comment by gonfreecs64** [comment]
Hi,

**BRANCH:** master
**COMMIT:** b7edb8a61473b140f002bea11174af47ab738bbb
**Python Version:**	2.7.3
**OS:** Raspbian GNU/Linux 7

same bug, no log

**Comment by Greg0rz** [comment]
Just got around to updating SickRage and I am now having this issue as well.  I want to say its something with jQuery not being properly included.

blackwhite.js?2812:34 
Uncaught ReferenceError: $ is not defined

**Comment by OmgImAlexis** [comment]
There's  a fix for the blackwhite.js in develop.
