### ISSUE TITLE
Active and Status columns off by one

### ISSUE THREAD

**Issue by hjbotha** [SiCKRAGETV/sickrage-issues#2814]
In banner, poster and simple views, the Active column is blank and Active and Status values are pushed off one column to the right.

Screenshot: http://i.imgur.com/4xVeEZY.png

Branch: Master
Commit: 7694b70047796dc0c9c812300a090f78a4240f46
OS: Windows 10 x64
Python: 2.7.8 x64

Tried in Chrome, Firefox, Internet Explorer and MS Edge, all the same. Same in Light and Dark themes.

**Comment by MGaetan89** [comment]
This is fixed in `develop`. It will be available in the next update.
