### ISSUE TITLE
Define quality profile

### ISSUE THREAD

**Issue by Drempelaar** [SiCKRAGETV/sickrage-issues#2815]
It would be nice if its possible to setup a minimum and maximum size (quality profile) just to ensure the right files are downloaded. Lets me honest, nobody needs a 54G 1 episode file.

What do you think?

**Comment by Drempelaar** [comment]
Is that already on the roadmap?

**Comment by flightlevel** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/95
Its not as easy as it sounds
