### ISSUE TITLE
Cannot set download directory in post-processing

### ISSUE THREAD

**Issue by Miyamoto65** [SiCKRAGETV/sickrage-issues#2818]
![untitled](https://cloud.githubusercontent.com/assets/14292242/9874879/bf48ef7e-5ba1-11e5-89ae-7defcd016a19.jpg)

Hi,
I have Sickrage 4.0.61 installed on my Synology box DSM 5.1-5592 Update 4.
When I try to go to the post processing to set a download directory for it to look for files coming from my Synology Download station, ... it will not click open the sub folders.

e.g. it will only click to volume1/video, and not volume1/video/0_Download
So it looks like video is an empty directory when it (obviously) has loads of files in it.
I tried to remove permissions to my userid to that directory, and then re-add them but it didn't seem to do anything.
Is this a problem with Sickrage or maybe synology?

**Comment by miigotu** [comment]
you need to grant rw permissions to the sc-media group for the directory, not just your user id.

**Comment by Miyamoto65** [comment]
Hi Yes I can confirm I had already done that for sc-media group as well and can confirm that sc-media has read/write permissions not only to video/o_Download but all of the video share.

**Comment by miigotu** [comment]
reboot the nas?

**Comment by Miyamoto65** [comment]
hmm... that didn't work.. (I had already rebooted it at various times but did it one more time for good measure)
If you are confident that this symptom is caused by permissions, then do you think I need to SSH to the nasbox and do some permissioning manually... do you know what code the permissions should be?  (e.g. 700 or something?)

**Comment by miigotu** [comment]
644 for files and 755 for the folders.

is the user SR runs under in the sc-media group?

im almost certain it is permissions

**Comment by Miyamoto65** [comment]
bizarre.. the sc-media group has a user called "sickrage" .. which itself doesn't exist as a user.  Do I need to create that user as well?  Or should I just add my own userid to that group.

**Comment by miigotu** [comment]
maybe try backing up and reinstalling the SickRage package first

**Comment by Miyamoto65** [comment]
what do you know!!.. it worked! thanks Miigotu
