### ISSUE TITLE
Revisit SickRage logo and Name

### ISSUE THREAD

**Issue by sammcj** [SiCKRAGETV/sickrage-issues#2819]
I'm not sure if this is a touchy subject or not, but has any thought been given to replacing the SickRage logo?

I'm not sure that the current logo relates to or represents the application in any way.

This:
![image_51](https://cloud.githubusercontent.com/assets/862951/9875887/3e2dda22-5bf5-11e5-93b5-b62af6c38241.png)
Doesn't make me think of TV Series or usenet.

**Comment by neoatomic** [comment]
@sammcj Yes, we are looking for a better alternative. :) 
https://sickrage.tv/forums/forum/main-category/latest-news/1347-logo-designer-needed

Do you have something specific in mind.?

**Comment by flightlevel** [comment]
I don't think the logo is too bad even though its unrelated, its the name that's shocking!
I've told a few people about SR and ALL have said something along the lines of "Sounds weird"
With the rewrite that's going on SR will soon have little to do with SICKbeard and tvRAGE is obviously gone. In English you pretty much couldn't pick two worse words. Sick doesn't have great connotations and rage makes you think of pulling your hair out. The whole idea of SR is to make things easier.
Plus, SR has come along way from when it was just Sickbeard with TVRage.

**Comment by sammcj** [comment]
+1 on the name, it sounds like someone going on a meth binge or something.

**Comment by WebSpider** [comment]
Please feel free to suggest a new name and logo :+1:

**Comment by sammcj** [comment]
If you keep SickRage I'd suggest the following as a logo (clearly I am joking):

![](http://img.gawkerassets.com/img/193gkpsivmrvtjpg/original.jpg)

**Comment by OmgImAlexis** [comment]
Closed as this isn't an issue and we can still discuss it with the issue closed.
