### ISSUE TITLE
No Coming Episode Page due to "mktime argument" all other pages working...

### ISSUE THREAD

**Issue by nigewri** [SiCKRAGETV/sickrage-issues#282]
Hi Dev's...

ISSUE
SickRage serves the below as a webpage on the Coming Episodes Page... All other pages are working e.g. Config, Logs etc... SickRage is still snatching etc

SYSTEM INFO
Python Version: 2.7.6 (default, Sep 9 2014, 15:04:36) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
Operating System: OSX 10.10.2
BRANCH: (develop) / COMMIT: (68e4acaf3730a114ccabc9585d8958676257142d) 
Pastebin WebPage URL: http://pastebin.com/mUgk9PL0
Pastebin Log URL: http://pastebin.com/Pbw2FZMD

BTW the submit errors function / button on log screen not working

Thanks for your assistance

**Comment by abeloin** [comment]
Pastebin logs don't exist anymore

**Comment by fernandog** [comment]
@nigewri

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/249
