### ISSUE TITLE
[APP SUBMITTED]: [Errno 13] Permission denied: '/volume1/video/series/Banshee/Banshee.S03E10.We.All.Pay.Eventually.1080p.HD.TV.BATV.fr.srt'

### ISSUE THREAD

**Issue by newkindofworld** [SiCKRAGETV/sickrage-issues#2820]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@7694b70047796dc0c9c812300a090f78a4240f46
Link to Log: https://gist.github.com/66de749844ebee07b819
### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/tv.py", line 1488, in downloadSubtitles
    subliminal.save_subtitles(foundSubs, directory=subs_new_path, single=not sickbeard.SUBTITLES_MULTI)
  File "/usr/local/sickrage/var/SickRage/lib/subliminal/api.py", line 133, in save_subtitles
    with io.open(subtitle_path, 'wb') as f:
IOError: [Errno 13] Permission denied: '/volume1/video/series/Banshee/Banshee.S03E10.We.All.Pay.Eventually.1080p.HD.TV.BATV.fr.srt'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
SR user must have write permission to /volume1/video/series/

Check user in localhost:8081/config

**Comment by newkindofworld** [comment]
Thanks for the quick reply !
Never changer anything, worked before, but I'll check the permission.
I'm running on synology nas.

**Comment by neoatomic** [comment]
Maybe file is in use, or gone bad. 
Just remove it and let SR download a new sub.
