### ISSUE TITLE
Failure to log into TorrentDay

### ISSUE THREAD

**Issue by kro138** [SiCKRAGETV/sickrage-issues#2821]
Branch Master
    Commit hash 7694b70047796dc0c9c812300a090f78a4240f46
    Your operating system and python version QNAP 4.1.4 Python 2.7
    What you did No changes, but can log into the website fine
    What happened Started getting errors that SickRAge couldn't connect to TorrentDay
    What you expected Business as per normal
    Link to a copy/paste of your logfile with clear debug info of the error on GIST

 2015-09-15 10:25:36 SEARCHQUEUE-DAILY-SEARCH :: [TorrentDay] :: Unable to connect to TorrentDay provider.
        2015-09-15 09:45:40 SEARCHQUEUE-DAILY-SEARCH :: [TorrentDay] :: Unable to connect to TorrentDay provider.

**Comment by kro138** [comment]
Looks like I may have done 2 updates to SickRage in that time. Not sure if the problem lies with a commit or change to Torrent Site.

Thanks!

**Comment by flightlevel** [comment]
@kro138 
We need the log file with Debug turned on to see what happening
https://github.com/SiCKRAGETV/sickrage-issues#enabling-detailed-debugging-for-logs

**Comment by kro138** [comment]
https://gist.github.com/kro138/c95b68c2692bd35ecbaa

**Comment by flightlevel** [comment]
@kro138 
What model QNAP are you using?

**Comment by neoatomic** [comment]
@kro138 SSL errors. The package you are currently using is outdated/broken.
Use this package http://apps.qnap.community/11-community/17-qsickrage

**Comment by kro138** [comment]
After installing the provided qpgk I'm am again able to log in to torrentday.

Thanks!
