### ISSUE TITLE
[Feature Request] Search special episodes

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2823]
Make speacial episodes searchable ,as there isnt even a icon to search 
Why would i want to do it? 
becouse there are shows which have them mapped on xem and others i might just add the numbering mannually

**Comment by flightlevel** [comment]
@duramato  
True, it would work sometimes.But, I think it would fail more often than not. Its not that common to see specials named ShowName.S00E**
If you turned this on, could you imagine all the errors being reported "SR not finding special ####!"
If you implement a feature, its got to have a fair chance of working regularly, not just occasionally.

**Comment by duramato** [comment]
It would be the same as now ,if it hasn't the correct naming it wount find it simply ,and there are some shows that the scene does differently from the indexers

**Comment by OmgImAlexis** [comment]
@duramato 99% of specials are named completely different from the scene.

**Comment by duramato** [comment]
@OmgImAlexis What about the ones that have mapping on xem?

**Comment by OmgImAlexis** [comment]
It doesn't matter if they have mappings or not, SR searches providers for `S00EXX` if the episode isn't like that which almost none are then it won't find anything. There's no point in spamming providers to find things that we know aren't going to be found.

**Comment by duramato** [comment]
@OmgImAlexis actually it searching with the correct strings ie if I set it to wanted

**Comment by duramato** [comment]
@OmgImAlexis also it can already be searched by setting to wanted ,why not add the "magnifying glass" to allow a manual search?

**Comment by flightlevel** [comment]
@duramato 
Because the magnifying glass isn't going to work the majority of the time. As a user, you have a fair expectation that clicking on something it will work, this won't.

**Comment by duramato** [comment]
Then why not add only the magnifying glass only if it has scene mapping? Because if it has its because there are releases for it

**Comment by OmgImAlexis** [comment]
Also just because one show and/or episode works doesn't mean most shows do and without over 80% working there's no point in adding it.

For instance NONE of my Dr Who ones work. That show alone has over 145 specials, that's 145 episodes that don't work with it.

**Comment by duramato** [comment]
@OmgImAlexis ie Fast n Loud has ,so does Marvel Hulk and the agents of smash,Pawn stars also has .
Those are the ones I have on my library and there are more for sure
