### ISSUE TITLE
[Feature Request] Move Show (+ mass update move)

### ISSUE THREAD

**Issue by syrys** [SiCKRAGETV/sickrage-issues#2825]
Im not sure if such feature exists, if so please let me know how/where. If not, this should be a fairly simple feature anyway, maybe?

So, what im looking for is a way to move a show. Say, from 1 HDD to another (or just if you are fiddling with folder structures). Ofcorse i can easily copy paste the folder and go into sickrage and edit the destination/root folder name on the show. But would be great if sickrage can handle the entire migration. Easier for users, since there is less chance of doing mistakes.

**Comment by flightlevel** [comment]
@syrys 
You can basically do this now.
Copy the shows you want in your OS to new destination
From SR > Manage > Mass update > Tick Edit for all shows moved > You can change root directory for all your selected shows in one go.

As far as SR doing the moving for you. Its a lot more difficult than it sounds. If all the data was just staying on the same HDD a move would be instant. But like in your example of copying to a different HDD (or even over network), this could take a verrry long time to copy, especially with a lot of shows. Your OS is better for these sorts of things than a web GUI

**Comment by mgaulton** [comment]
@flightlevel Out of curiosity, is there a command line way of updating? I've tried the mass edit a couple times recently and it doesn't seem to work. I'd have to try again to produce logs. I have a volume of anime that needs to be moved to free up space.

**Comment by fernandog** [comment]
@mgaulton you can try edit your DB, but I only recommend if you know what you are doing...

**Comment by syrys** [comment]
@mgaulton i tried the mass edit for a whole bunch of shows last night. worked just fine. Butthe catch is, you need to find the matching folders from the source and manually move to the destination.

i recon sickrage should add some functionality to display the source location on the mass update page. even better, some easier ways to bulk select shows to edit (ie. select all anime, or select all anime in E: drive etc).

@flightlevel you are right, such copying will take a long time, and the OS is better at doing it BUT... OS doesnt have the metadata/tags that is available on SR. here is a scenario. imagine someone added all their media to a Shows folder, and later wanted to seperate their TV Shows and Anime, and imagine if they have a large number of shows/anime. Imagine how hard this migration would be? you have to look up names of anime, manually search the source folder for it, then manually move each folder (then do the mass update on SR). Maybe someone should look into making a (mass) migration tool?

**Comment by mgaulton** [comment]
@flightlevel @fernandog The issue i seem to be having is that the mass update says that it worked, doesn't' give any feedback and when i go back in, the folder entries are still there.  I'll try it again later and see if its putting anything in the logs.
