### ISSUE TITLE
[Feature Request] Cache all static content

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2826]
Is there a reason we don't cache these and/or force them not to be cached?

![screen shot 2015-09-16 at 9 49 59 am](https://cloud.githubusercontent.com/assets/6525926/9893525/77eac7ee-5c58-11e5-9ece-62918a967fe6.png)
![screen shot 2015-09-16 at 9 50 18 am](https://cloud.githubusercontent.com/assets/6525926/9893528/81d4bf8a-5c58-11e5-8e99-911c5c6357e2.png)
![screen shot 2015-09-16 at 9 49 52 am](https://cloud.githubusercontent.com/assets/6525926/9893535/894c2258-5c58-11e5-989c-b91b428e2c3f.png)

**Comment by OmgImAlexis** [comment]
Related to https://github.com/SiCKRAGETV/sickrage-issues/issues/2503 and https://github.com/SiCKRAGETV/sickrage-issues/issues/2502

**Comment by miigotu** [comment]
Told you like 50 times static_url/static_path is not working in tornado webserveInit lol. They ARE cached, just without a cache breaker/expiration so etags are used for refresh.

**Comment by OmgImAlexis** [comment]
I thought it had been fixed by now. Is there no way to just force a cache header until it can be fixed?

**Comment by miigotu** [comment]
We could, but there is no breaker so it would cache too aggressively then.

**Comment by OmgImAlexis** [comment]
Those files are all libraries aren't they? Libraries can be cached forever for all I care.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
