### ISSUE TITLE
Sickrage not matching an episode that I have scene numbering enabled for. Why?

### ISSUE THREAD

**Issue by suprdave23** [SiCKRAGETV/sickrage-issues#2828]
Latest version of SR, just did a git pull 15 minutes ago.

Master branch
commit b7edb8a61473b140f002bea11174af47ab738bbb
Windows 7, Python 2.7.10

Indexer has it listed as s06e01. I have enabled scene numbering as "8x1". The episode exists and it is seeing the exact one I want it to download, but then it says "doesn't seem to be a valid episode that we are trying to snatch, ignoring". Super frustrating! I have this show set to download "Any" quality.

Please help me figure this out, thank you! Logs below.

https://gist.github.com/suprdave23/37f051de44a5117e62c4#file-gistfile1-txt

**Comment by neoatomic** [comment]
Follow the guidelines. https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket

**Comment by suprdave23** [comment]
Updated with more info.

**Comment by suprdave23** [comment]
I found my issue, I had numbered the episode as one that had already existed. Typo'd the 8, meant for it to be a 9. After changing it to "9x1" it snatched it.

Can I make a request for there to be more verbose logging when this issue happens? IE, "Episode 8x1 seems to already exist, skipping snatch" or something similar :+1: )
