### ISSUE TITLE
ImportError - missing module on restart of SickRage

### ISSUE THREAD

**Issue by gerbil42** [SiCKRAGETV/sickrage-issues#2829]
Seems that every time I reset SickRage I get an ImportError about a missing module:

>2015-09-15 22:39:08 Thread-32 :: Failed doing webui callback: Traceback (most recent call last):
  File "D:\SickRage\sickbeard\webserve.py", line 272, in async_call
  result = function(**kwargs)
  File "D:\SickRage\sickbeard\webserve.py", line 718, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "D:\SickRage\sickbeard\webserve.py", line 113, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "D:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "D:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "D:\SickRage\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module D__SickRage_gui_slick_views_home_mako not found in sys.modules

Server 2012 R2
BRANCH: (master) / COMMIT: (b7edb8a61473b140f002bea11174af47ab738bbb)
Python Version:	2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]

**Comment by OmgImAlexis** [comment]
Duplicate https://github.com/SiCKRAGETV/sickrage-issues/issues/2735

**Comment by gerbil42** [comment]
Weird - I searched for the importerror line but didn't find any matches.

Thanks!

**Comment by OmgImAlexis** [comment]
It's different as your install is in the D drive, not C.
