### ISSUE TITLE
Auto-updated / database upgrade is cleaning the database

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#283]
Everytime I set to auto-update my database get's cleaned

**PLEASE BACKUP** your entire SickRage folder before testing this!

I'm RPI user.
Can someone with RPI confirm please?

```
SR Version:	BRANCH: (develop) / COMMIT: (972ee14216a6146e69fa909355791380d4c4e1bf) 
SR Config file:	/home/pi/SickRage/config.ini
SR Database file:	/home/pi/SickRage/sickbeard.db
SR Cache Dir:	/home/pi/SickRage/cache
SR Arguments:	['-q', '--daemon', '--nolaunch', '--pidfile=/var/run/sickrage/sickrage.pid', '--datadir=/home/pi/SickRage']
SR Web Root:	
Python Version:	2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]
```

Log1 - updating
10:02:54 INFO::CHECKVERSION :: Update was successful!:
http://pastebin.com/1RksBMWW 

Log2 - restarting after update:
http://pastebin.com/TN1hZiA7
10:03:56 INFO::MAIN :: Proceeding with upgrade

There's no "Loading show info from database"

Tested again:
Full log:
http://pastebin.com/yJ8fMLPL

There was no backup.
"10:28:19 INFO::MAIN :: Backing up database before upgrade"

also sickbeard.db is 26.624 bytes

![dbs-after](https://cloud.githubusercontent.com/assets/2620870/5548452/c77e1418-8b58-11e4-865d-c93daa9e13d4.png)

**Comment by markheloking** [comment]
Closing this issue as it should be fixed. Please reopen if the issue persists.
