### ISSUE TITLE
[Feature Request] syslog for sickrage

### ISSUE THREAD

**Issue by Drempelaar** [SiCKRAGETV/sickrage-issues#2831]
I was thinking it would be great to have syslog capability in sickrage. This ensures all logs are saved and rotated accordingly. For debugging reasons I think this feature would be very nice because the logging can fill up quickly.

Example:

```python
import logging
import logging.handlers

my_logger = logging.getLogger('MyLogger')
my_logger.setLevel(logging.DEBUG)

handler = logging.handlers.SysLogHandler(address = '/dev/log')

my_logger.addHandler(handler)

my_logger.debug('this is debug')
my_logger.critical('this is critical')
```

**Comment by miigotu** [comment]
Errors already go to syslog.
