### ISSUE TITLE
[Feature Request] English search string

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2832]
If i add show using any laguage other than english it will change its tittle and consequently the search string
So if the show info isnt english add a scene naming exception with the original tittle OR make the search strings the original title

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
