### ISSUE TITLE
Updating SickBeard - Lost /home/sickbeard

### ISSUE THREAD

**Issue by AubreyKloppers** [SiCKRAGETV/sickrage-issues#2833]
Hi Guys
I read something similar on #2788 - I just did an upgrade on my OpenMediaVault system, which upgraded/updated SickBeard to 1.0.10.  

This immediately gave me an APACHE2 default page!!!

I then did a: 
*# update-rc.d -f apache2 remove
 # service nginx restart*
which got me to a blank slate sickrage.  All of my content missing...

I uninstalled and re-installed SickRage and with the restore I get *Successfully extracted restore files to /var/opt/sickbeard/restore
Restart sickrage to complete the restore.* 

I thought the /home/sickbeard directory would have been used for the restore.  Anyhow, when I restart, the entire system is still a blank slate.  My INI files are correct.

I can, however, push the entire structure from my backup to /var/opt/sickbeard, which gets the content back...

BUT, I do not think the system is suppose to do this.

I have even uninstalled and purged the sickrage package, cleaned the apt cache, but now, the system diverts to /var/opt/sickbeard as the home directory.

I believe something went wrong...

ps - I saw on the OMV Forum a guy struggling with the same issue: http://forums.openmediavault.org/index.php/Thread/9006-Sickbeard-config-crashes-webUI/?postID=92593
It seems the SickBear 1.0.10 upgrade broke sickrage...  Are they (SickBeard) trying to say something?

**Comment by AubreyKloppers** [comment]
I believe I found the culprit in:
*OMV_SICKBEARD1_DATA_PATH=${CP_DATA-/var/opt/sickbeard}*
set with the:
*/usr/share/openmediavault/mkconf/sickbeard*
script.

Now, how do I reverse to 1.0.9 of SickBeard?

**Comment by OmgImAlexis** [comment]
This is sickRAGE not sickBEARD.

**Comment by AubreyKloppers** [comment]
@OmgImAlexis How can you close this?  When you install SickRage on OMV, you have to do it via the git built into SickBeard...  The auto-update of the system then breaks SickRage...

**Comment by OmgImAlexis** [comment]
I don't know what you're on about, sickbeard and sickrage don't work together at ALL. OMV should have a plugin specifically for sickrage.

@miigotu @neoatomic any ideas?

**Comment by miigotu** [comment]
considering SickRage is on version 4.0.61...

**Comment by AubreyKloppers** [comment]
Installing SickRage on OMV is from the FORK of SickBeard.  To do this, you have to install SickRage pointing sickBeard's REPOSITORY to the github of SickRage's git.  Please take a moment to read this: 
*https://aubreykloppers.wordpress.com/2015/08/27/installing-sickrage-tv-downloader-on-omv/*
![sb](https://cloud.githubusercontent.com/assets/14271008/9926513/691e73b4-5d16-11e5-85d2-25e564f80be9.png)

I would also like to point out that I was realy under the impression that SickRage was a SUB-Structure (Child) of SickBeard...

This is my current system info:
![sr](https://cloud.githubusercontent.com/assets/14271008/9926549/a3991a08-5d16-11e5-8083-19367dadb677.png)

Thank you and sorry for the long posts, I really would like this resolved...

kind regards
Aubrey Kloppers

**Comment by miigotu** [comment]
this lost settings problem is already fixed in the latest master and develop. install, update, add settings and shows, and the problem shouldn't happen again.

**Comment by AubreyKloppers** [comment]
@miigotu Does this mean that my system will revert back to /home/sick... from /var/opt/sick... when the next update happens?

**Comment by miigotu** [comment]
I have no control over where you put your config or point SR to look for config. Check the service configuration for that.

The self.clean() fix makes it so that config left inside the SR source dir does not get deleted.
