### ISSUE TITLE
_parse_string only send the best regex result to the indexers

### ISSUE THREAD

**Issue by gonfreecs64** [SiCKRAGETV/sickrage-issues#2834]
Hi,

**BRANCH:** master
**COMMIT:** b7edb8a61473b140f002bea11174af47ab738bbb
**Python Version:**	2.7.3
**OS:** Raspbian GNU/Linux 7
**What i did :** I manually downloaded the file *[Kaerizaki-Fansub]_One_Piece_709_[VOSTFR][HD_1280x720].mp4* and waited, with a hot cofee and youtube stuff playing on my 2nd screen
**What happened:** The file has not been parsed neither moved at all
**What you expected:**I expected the postprocessor to parse the file and put it in my show directory

Here is my /opt/sickrage/bin/Logs/sickrage.log :
https://gist.github.com/gonfreecs64/a36a0eaa9deffc259b86

The name parser regexes (/opt/sickrage/bin/sickbeard/name_parser/regexes.py) contains a valid parser named *'anime_Kaerizaki-Fansub'*
I successfully tested it separately.

Thanks for help!

**Comment by gonfreecs64** [comment]
**Problem identified:**
The function **_parse_string(self, name)** try all the regex's against the name (*[Kaerizaki-Fansub]One_Piece_709[VOSTFR][HD_1280x720]* for me)
When more than one regex match, only the one with the best score is kept and sent to the helper function **helpers.get_show(bestResult.series_name, self.tryIndexers, self.trySceneExceptions)**

In my case the regex with the best score is not the good one => the regex used do not pass the real show name => indexers do not find any valid show => the file is not processed at all.

**Solution:**
I managed to handle this by modifying the **_parse_string(self, name)** function with a loop to send all show names (by descending score) to **helpers.get_show** until a valid show is found or no anymore names is available in the parsed list.

I am a pretty bad developer so i will not commit anything as i really do not understand this python code correctly, but i think the more the parser list will grow, the more this problem will appear.

Hope it helps.

**Comment by miigotu** [comment]
@gonfreecs64 is One Piece set as an anime in the settings for that show?

**Comment by gonfreecs64** [comment]
@miigotu Yes. This show was in my show list before and set as an Anime.
But it changes nothing. This setting is not checked while postprocessing downloaded files.
All regexes are used. And i understand that because there is no way to know what the file is before parsing it.
