### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by vlsoft** [SiCKRAGETV/sickrage-issues#2839]
hello

i have error with the provider "Libertalia". 

2015-09-17 12:12:39 WARNING  SEARCHQUEUE-BACKLOG-164041 :: [Libertalia] :: Connection error to getURL https://libertalia.me/login.php Error: error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

SR Version:	BRANCH: (master) / COMMIT: (b7edb8a61473b140f002bea11174af47ab738bbb) 
Python Version:	2.7.10 (default, Aug 19 2015, 09:18:54) [GCC 4.6.3]

thank your for help.

**Comment by bobbysteel** [comment]
Their certificate is expired. Seems pretty clearly the fault of Libertalia.

**Comment by miigotu** [comment]
You can disable cert verification in config/general on the advanced page, save, stop SR, clear out cache/sessions, and start SR. It should then work without verifying the cert.
