### ISSUE TITLE
WdLxtV thumbnails tvshows folder.jpg

### ISSUE THREAD

**Issue by TiagoDM** [SiCKRAGETV/sickrage-issues#284]
Is there any chance to permanently change the thumbnails created to WDTv (mine is WDLxTv, alternative firmware) from "folder.jpg" to ".folder.jpg"?

What is happening is that whether i change the file \metadata\wdtv.py, changing all "folder.jpg" to ".folder.jpg", whenever i get an update, i always have to change it again, restart sickrage and delete all created "folder.jpg" in my hard drive tvshows folder.

That way, when i watch the tvshows on WDLxTV, i don't have to see the image (like an extra tvshow) in the play list.

Thanks and merry christmas,

Tiago

**Comment by neoatomic** [comment]
So you are using Post processing with meta data type WDTV to add all the images and data for your media player.? 
Why should the filename be ".folder.jpg" and not the normal "folder.jpg" ?  Wouldn't this mean that the images don't work for other WDTV users anymore.?
Please explain a little more detailed what your goal is, and why the filename should be changed.

**Comment by TiagoDM** [comment]
Sorry, I probabily didnt explain well. For instance when im browsing the
tvshows folder in wdlxtv i can also see images jpg, not only the tvshows
AVI MKV, etc... files thumbnailed (the thumb file folder.jpg is placed in
same dir as the tvshow/seasonXX). The ideal situation was if browsing movie
files i only would be able to see AVI,MKV,mp4,etc.. And i dont, i also see
jpg files. For having this issue right, I change it every time i update to
.folder.jpg because that way when im browsing tvshows folder only the
tvshow file thumbnailed appears on the list instead of a plus jpg file.
Wdlxtv is linux and the dot (.) starting files are hidden, so, if everytime
i update, wdtv.py were right, this way i could update and not edit wdtv.py
everytime and restart sickrage. This probabily wouldnt affect others as
.folder.jpg is a crossplatform name (not hidden in other platformas
probabily) and this only would apply to wdtv owners.

Thank you,

Tiago

A sex, 2/01/2015, 12:55, neoatomic <notifications@github.com> escreveu:

**Comment by neoatomic** [comment]
Ok, so in short you want the folder.jpg files to be hidden. As those jpg's otherwise are showing up in your WDtv movie play list.

Doesnt Wdlxtv have an option to remove the jpegs from the play list.? I suspect more Wdlxtv users would have this problem then.?
It sounds to me that you are taking the long route by trying to fix this in SickRage as this is in reality a problem/limitation of Wdlxtv.

If renaming hasn't any consequences for other platforms it might be an option, but we will have to wait till echel0n is back for his input.

**Comment by TiagoDM** [comment]
I really tried before but it seems its a software bug in wdlxtv showing the
pictures in videos folders... Thanks anyway it would be awesome if echel0n
could make the change

A sex, 2/01/2015, 18:29, neoatomic <notifications@github.com> escreveu:

**Comment by TiagoDM** [comment]
Hi. Is there any development in my issue? 

As you see in this wdlxtv post, even the admin says that changing folder.jpg to .folder.jpg is the way to go...

http://forum.wdlxtv.com/viewtopic.php?f=3&t=7263

...so no harm will be made in the other SickRage users

Thank you

**Comment by fernandog** [comment]
@TiagoDM I suggest create an script and add it to CRONTAB (linux)

**Comment by TiagoDM** [comment]
ok... i'll do it (but im in windows, not linux).

**Comment by fernandog** [comment]
@TiagoDM 

create a rename.bat with this:

```
cd MAIN_FOLDER
for /R %x in (*.jpg) do rename "%~dpx%~nx.jpg" ".%~nx.jpg"
```

Add it to schedule task
http://windows.microsoft.com/en-us/windows/schedule-task#1TC=windows-7

**Comment by TiagoDM** [comment]
thankx!

2015-02-12 17:59 GMT+00:00 Fernando <notifications@github.com>:

> Closed #284 <https://github.com/SiCKRAGETV/sickrage-issues/issues/284>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/284#event-234852738>
> .
>



-- 
________________________________________
Tiago Marques

**Comment by fernandog** [comment]
Worked?

**Comment by TiagoDM** [comment]
Went to play soccer but i got the idea. Hadnt the chance to try yet but asa
i can, i will post the resullt.

A qui, 12/02/2015, 18:42, Fernando <notifications@github.com> escreveu:

**Comment by TiagoDM** [comment]
Probabily i will try to modify the script to run weater sickrage has an
update and change wdtv.py replacing all folder.jpg to .folder.Jpg

A qui, 12/02/2015, 22:10, Tiago Marques <tiago.dmarques@gmail.com> escreveu:
