### ISSUE TITLE
Memory resources maxed out on Synology Python

### ISSUE THREAD

**Issue by deathnite** [SiCKRAGETV/sickrage-issues#2840]
Branch: Master
Commit hash: b7edb8a61473b140f002bea11174af47ab738bbb
Your operating system and python version: DSM 5.2-5592 Update 4 / 2.7.10-14
What you did: Copied files and folder structure from existing DS1512+ to new DS412+.
Installed Sickrage package and commenced adding shows with same naming settings.
What happened: 
At idle the 'python' process sleeps at 78.1 MB
After about 8 shows imported the resource monitor shows the 'python' process at about 25% CPU and memory usage starting around 78MB and increases rapidly to over 750MB before the system becomes unstable.
Also performing Manual Post-Processing also results in the same behavior of increases rapidly to over 750MB before the system becomes unstable.
Stopping/Starting the Sickrage package is the only way gain stability

What you expected
Link to a copy/paste of your logfile with clear debug info of the error on GIST
https://gist.github.com/deathnite/85d03becc058afa8e188

My DS1512+ on Commit Hash b7edb8a61473b140f002bea11174af47ab738bbb is not exhibiting these same issues.

**Comment by richard5mith** [comment]
I was going to post a new issue after commenting on #2755, but this is the exactly the same setup as me. DS412+ with the same version of the DSM OS.

I have renamed the cache folder and had it build a new one, but it made no difference.

**Comment by neoatomic** [comment]
Plese add the info to https://github.com/SiCKRAGETV/sickrage-issues/issues/2755 so we have all the info in 1 place. No point in opening multiple issues for the same problem.
