### ISSUE TITLE
[Feature Request] Download all of the season when show is listed as being on Netflix instead of just ep 1

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2842]
For shows that're on Netflix at times the season has different air dates per episode even though the whole season goes up at once.

**Comment by miigotu** [comment]
If they have different airdates, they are always in the past. Netflix original series have the same airdate.

**Comment by OmgImAlexis** [comment]
Not always, I had this issue with the latest OITNB it downloaded ep 1 - 5 fine but all the rest had the next day as the airdate.

**Comment by miigotu** [comment]
http://thetvdb.com/?tab=season&seriesid=264586&seasonid=602818&lid=7

Airdates are all the same for each season of OITNB on thetvdb.

**Comment by OmgImAlexis** [comment]
They are now.. also this may have been an issue that was related to tvrage. Going to close it then.

**Comment by miigotu** [comment]
tvrage had hella inaccuracies, so makes sense. Also another reason im not anxious to add another potential source of bad info.
