### ISSUE TITLE
Getting shows to post-process into a single directory rather than individual shows

### ISSUE THREAD

**Issue by Miyamoto65** [SiCKRAGETV/sickrage-issues#2843]
Hi All.  This isn't so much an issue as a question/feature request.
When I create a show, it creates a subdirectory in the parent folder.   I would like to have all new shows go to "Unwatched" directory, and then I can move them manually to final resting place after watching them.  That way I can identify which ones I haven't seen yet etc.   Is there a way to do this?

Thanks all

**Comment by miigotu** [comment]
Negative. Also, if you use a media player like Kodi it keeps track of your watched and unwatched episodes.

**Comment by Miyamoto65** [comment]
thanks again for the fast comment Miigotu.   So given I am playing the content form a Synology Box on my Samsung Smart TV and using Synology Media Share... I guess my plan is to put all the subfolders in "Unwatched", and then move manually episodes out.   Final question.... if I have watched all of the episodes in a particular Series, and then I delete the folder (e.g. over summer when there are no new episodes)... will the next download automatically create the folder again, or will Sickrage crash?  (Or will it just create the folder again immediately)

**Comment by miigotu** [comment]
Dont delete the show folder itself, just the contents, and it wont choke afaik.
