### ISSUE TITLE
Displayshow page bricked for one show: UnicodeDecodeError on Required Keyword

### ISSUE THREAD

**Issue by codemann8** [SiCKRAGETV/sickrage-issues#2844]
SR Version:	BRANCH: (master) / COMMIT: (b7edb8a61473b140f002bea11174af47ab738bbb) 
SR Locale:	('en_US', 'cp1252')
SR Arguments:	[]
OS Version:       Windows Server 2012 SP1
Python Version:	2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]

What you did: I tried adding a Required Keyword for a show (typing in with keyboard, not copy and paste)
What happened: displayShow page now permanently became bricked (error pasted below) for this show (cannot edit any settings for this show anymore)
What you expected: For it to work without error
Log:      Nothing shows up in log, even at DB level

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 35: character maps to <undefined>

% else: <tr><td class="showLegend"><span style="color: red;">Location: </span></td><td><span style="color: red;">${showLoc[0]}</span> (Missing)</td></tr> % endif <tr><td class="showLegend">Scene Name:</td><td>${(show.name, " | ".join(show.exceptions))[show.exceptions != 0]}</td></tr> % if show.rls_require_words: <tr><td class="showLegend">Required Words: </td><td>${show.rls_require_words}</td></tr> % endif % if show.rls_ignore_words:
C:\Program Files\Python\Python27\lib\encodings\cp1252.py, line 15:
return codecs.charmap_decode(input,errors,decoding_table)
C:\Program Files (x86)\SickRage\gui/slick/views/displayShow.mako, line 233:
<tr><td class="showLegend">Scene Name:</td><td>${(show.name, " | ".join(show.exceptions))[show.exceptions != 0]}</td></tr>
C:\Program Files (x86)\SickRage\gui/slick/views/layouts/main.mako, line 217:
C:\Program Files (x86)\SickRage\lib\mako\runtime.py, line 853:
callable_(context, *args, **kwargs)

**Comment by miigotu** [comment]
This has the same cause and solution as your other issue, so marked dupe and closing.

**Comment by codemann8** [comment]
This did fix the issue, but every time I Sumbit a change on the Edit page for this specific Show, this bricks the show.  Running the chcp cmd fixes it, but kind of annoying it keeps happening.

**Comment by miigotu** [comment]
Make your service/startup script ALWAYS run SR that way
