### ISSUE TITLE
Unable to delete show - No TrackT

### ISSUE THREAD

**Issue by codemann8** [SiCKRAGETV/sickrage-issues#2845]
SR Version:	BRANCH: (master) / COMMIT: (b7edb8a61473b140f002bea11174af47ab738bbb) 
SR Locale:	('en_US', 'cp1252')
SR Arguments:	[]
Python Version:	2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]

I'm unable to delete a show, it shows the error (below) and this is what the log says (also below). In fact, I've also deleted the media folder manually just in case there was an issue there.  I'm not using TrackT nor have a ever. I've seen other people with this same issue, but only when TrackT is used, I am not however.

Error
Unable to delete show: Sound FΧ

Log:
2015-09-18 03:16:07 WARNING  Thread-66 :: Unable to delete show: Sound FÎ§. Error: argument of type 'int' is not iterable

**Comment by miigotu** [comment]
Stop SR, in command prompt and in your SR folder run `chcp 65001 && python SickBeard.py`

Then delete it.

**Comment by miigotu** [comment]
SiCKRAGETV/sickrage-issues/issues/2844

**Comment by lendenrk** [comment]
I've the same issue, but I'm running SR on Linux, what I replace "chcp 65001" with?

**Comment by codemann8** [comment]
This did fix the issue, but every time I Sumbit a change on the Edit page for this specific Show, this bricks the show.  Running the chcp cmd fixes it, but kind of annoying it keeps happening.

**Comment by miigotu** [comment]
@lendenrk that doesnt tell me anything, because surely your problem is not the same. DEBUG LOGS!
