### ISSUE TITLE
Provider Cpasbien don't seem to work !

### ISSUE THREAD

**Issue by Sylrob434** [SiCKRAGETV/sickrage-issues#2846]
Sickrage never found my tv show I added french to the required words and I always have to download the tv episode manually when it is available on cpasbien here is the result of the search in the log all episode for all show are the same ! 

015-09-17 22:06:53 INFO     SEARCHQUEUE-BACKLOG-264492 :: [Cpasbien] :: Ignoring result under.the.dome.s02e13.final.french.hdtv because we don't want an episode that is Unknown

It you need something else let me know !

**Comment by neoatomic** [comment]
@Sylrob434 It does not have a valid quality in the title. (no `720p` or `x264` etc)
Here you can read more. :

https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-names-to-recognize-the-quality-of-a-file

**Comment by Sylrob434** [comment]
Sorry for the post just realised that few seconds ago and put all my tv show to quality any !

**Comment by fernandog** [comment]
@Sylrob434 are you getting snatches from Cpasbien  ?

**Comment by bandit33000** [comment]
Dear all,

Same issue here, did you solved it ? how ?
