### ISSUE TITLE
[Feature Request] Retention period for WATCHED shows.

### ISSUE THREAD

**Issue by AubreyKloppers** [SiCKRAGETV/sickrage-issues#2847]
Is it possible to build in a Retention Period for Shows?  This is actually 2 requests.  
* Could a flag be added to a series that if an episode of the show has been watched the episode gets deleted after $RETENTION_PERIOD?
* Could an OPTION be added to delete the TORR/NEWZ after $RETENTION (i.e. Set Retention to 2 weeks and after 2 weeks of sharing the item gets deleted...)

Thank you
Aubrey Kloppers (aka cyber7)

**Comment by OmgImAlexis** [comment]
How would we know if it's been watched? SickRage just downloads shows.

**Comment by neoatomic** [comment]
Thats something your media player should do. Not SickRage.

**Comment by miigotu** [comment]
After the next db upgrade, it might be possible, but I dont think it is a good feature and will be prone to failure.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
