### ISSUE TITLE
Column values not in the right column's 

### ISSUE THREAD

**Issue by cmodijk** [SiCKRAGETV/sickrage-issues#2849]
I'm using the latest master and the `active` en `status` seems to be in the wrong position (see the printscreen) 

BRANCH: (master) / COMMIT: (b7edb8a61473b140f002bea11174af47ab738bbb) 

<img width="466" alt="schermafbeelding 2015-09-18 om 18 21 54" src="https://cloud.githubusercontent.com/assets/771041/9964793/99f81bd0-5e32-11e5-9f49-bd6d45ea0e67.png">

**Comment by neoatomic** [comment]
@cmodijk Its working fine here on the Develop Branch. So this should be fixed with then next update.
