### ISSUE TITLE
[Feature Request] RawHD to "Any" quality setting

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2850]
When using the Any quality setting it doesnt inclued RawHD,my feature request is to add it

**Comment by miigotu** [comment]
It is left out on purpose. If you need it use custom.

**Comment by duramato** [comment]
But why ? To my understanding Any should also included RawHD as its any quality

**Comment by miigotu** [comment]
Because it is terrible, and many devices cannot play it. In fact "Unknown" was only recently added to Any quality and will probably be reverted.

If there is a rawHD available, which is technically a scene source only format (another reason why), there is an HD quality available too.

**Comment by duramato** [comment]
Oh I see ,why not maybe have it as a single quality preset because the only way to search it now is with a costum quality preset
