### ISSUE TITLE
Unable to add fansub group to lists

### ISSUE THREAD

**Issue by codemann8** [SiCKRAGETV/sickrage-issues#2851]
SR Version: BRANCH: (master) / COMMIT: (b7edb8a61473b140f002bea11174af47ab738bbb) 
SR Locale: ('en_US', 'cp1252')
SR Arguments: []
Python Version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]

First, no groups show under the available group (I guess I would expect there to be a pre-defined list of past fansubs that it may have found, but then again I'm not sure what sources you're using to pull this list).  Anyways, that's fine, so I go to manually add one to the whitelist, when I click Add to Whitelist, nothing happens, what am I doing wrong?

**Comment by Quiksmage** [comment]
current ticket.:https://github.com/SiCKRAGETV/sickrage-issues/issues/2813

It pulls pre-defined list from anidb. You have to make an account there for that.

**Comment by codemann8** [comment]
Ok, I did not know I had to connect to an account somewhere. But, aside from that, can I manually add a fansub group without an account? It seems like I should be able to put in anything I'd like no matter what.

**Comment by Quiksmage** [comment]
yes, you can. However, it's broken right now and there's an existing ticket for it which I linked above :). I would post your information in there.

**Comment by codemann8** [comment]
My bad, I'm usually good about checking for existing issues.  I see now, I'll wait for the next update.
