### ISSUE TITLE
[BUG] Wrong quality pill color

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2852]
When snatching RawHD the color pill on the show page is grey instead of orange .If i refresh the page it breafly shows orange while its loading ,but when it finishes loading it turns grey.
The color pill on the history page is orange

**Comment by fernandog** [comment]
@VinceVal can you check this one please?

**Comment by fernandog** [comment]
@duramato please test in develop

**Comment by miigotu** [comment]
Closing, comment if it is not fixed.
