### ISSUE TITLE
NameError: global name 'display_staus' is not defined

### ISSUE THREAD

**Issue by zephyr2206** [SiCKRAGETV/sickrage-issues#2853]
BRANCH: (master) / COMMIT: (b7edb8a61473b140f002bea11174af47ab738bbb) 
Windows Server 2008 R2 / Python 2.7.8

Any page with  /home in URL get this error.
EDIT: /home/displayShow?show=XXXXXX works for some reason.

Error !
NameError: global name 'display_staus' is not defined
elif re.search('(?i)(?:nded)', curShow.status): display_status = 'Ended' %> ${display_status} </td> </tr> % endfor </tbody> </table>
C:\SickRage\gui/slick/views/home.mako, line 796:
${display_status}
C:\SickRage\gui/slick/views/layouts/main.mako, line 217:
C:\SickRage\lib\mako\runtime.py, line 853:
callable_(context, *args, **kwargs)

I have no clue what this is, but i see that the first line says "display_staus". I guess this should be "display_status"?
Tried clearing cache, restarting SR/Server, GIT reset

**Comment by fernandog** [comment]
are you still having this issue? code is correct. There's no reference to display_staus

**Comment by zephyr2206** [comment]
Updated to BRANCH: (master) / COMMIT: (29105fd42b203393cc2393d683a3d11b74a0c752)

Issue is now gone.
