### ISSUE TITLE
[Feature Request] Allow to change maxage setting

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2856]
When using NZBs on sickrage the maxage setting on the wzab api its set 500 which is not always enough ,cant it be increased to something higher?

**Comment by miigotu** [comment]
Set it to what ever you want it to be.

![image](https://cloud.githubusercontent.com/assets/390379/9979063/886c36de-5f0a-11e5-83ad-df6659104703.png)
