### ISSUE TITLE
Include articles ("The", "A", "An") when sorting show lists not working

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#2857]
setting it's not working

**Comment by OmgImAlexis** [comment]
@fernandog how is it currently sorting them? @MGaetan89 could that be from when you changed the table sorting?

**Comment by MGaetan89** [comment]
Looks like it's working for me.

@fernandog Did it fail in `master` or `develop`? What is your current result?

**Comment by fernandog** [comment]
@OmgImAlexis @MGaetan89 
develop. enabling/disabling makes no difference. Delete cache/mako and browser cache

before JS renders the page (grey background) the sort appears ok. but when It renders, sort it's not ok

![image](https://cloud.githubusercontent.com/assets/2620870/9976571/db53c0d4-5ebe-11e5-9055-51a71bcb2ef5.png)

**Comment by OmgImAlexis** [comment]
What are you expecting? I'm guessing you want it to sort all of the shows starting with `the` together?

**Comment by fernandog** [comment]
to include the articles in the sorting.

**Comment by OmgImAlexis** [comment]
If you can give me an example of what you mean I can probably fix it, it's most likely an error from when I moved the js to it's own file.

**Comment by fernandog** [comment]
As the setting says: include articles in the sort

Today it remove the articles while sorting

**Comment by OmgImAlexis** [comment]
Okay so they should be grouped by `the`, `an` and `a` if the setting is on, right?

**Comment by fernandog** [comment]
Yes.

**Comment by miigotu** [comment]
seems it includes articles when sorting for me. maybe the option is just reversed? not sure what mine is set to

**Comment by OmgImAlexis** [comment]
Yep, it's inverted. Not sure how that happened.
