### ISSUE TITLE
No way to select develop branch after installing with Windows Installer.

### ISSUE THREAD

**Issue by kendog819** [SiCKRAGETV/sickrage-issues#2858]
Title says it all. 

Installed yesterday using the windows installer, when I try to switch over to develop by clicking the dropdown, there is only the option for MASTER available. 

I only want to switch over to develop because there has been changes made within the last couple days that got KickAssTorrents working, and it hasn't been pushed thru to Master yet. I'd like to use it.

How do I go about getting the DEVELOP option available to me?

Thanks,
Ken

**Comment by fernandog** [comment]
you only need to enter github user/password to be able to switch to develop branch

**Comment by kendog819** [comment]
Thanks @fernandog
