### ISSUE TITLE
[APP SUBMITTED]: SHOWQUEUE-ADD :: Could not connect to trakt service, aborting library check

### ISSUE THREAD

**Issue by technazz** [SiCKRAGETV/sickrage-issues#2859]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@b7edb8a61473b140f002bea11174af47ab738bbb
Link to Log: https://gist.github.com/fb140816f7cccbf01b86
### ERROR
```
SHOWQUEUE-ADD :: Could not connect to trakt service, aborting library check
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
trakt issue. try again later
