### ISSUE TITLE
Cannot Add New Show

### ISSUE THREAD

**Issue by thadius856** [SiCKRAGETV/sickrage-issues#286]
BRANCH: (develop) / COMMIT: (8b84e4f4bc6cdebdc605438e9e75d15f1133d65e)

Since last update, I cannot add a new show. At the top of the Add Show page once I search on TVRage:

"Adding show Marco Polo into unknown dir."

I have 3 dir's listed and one set as default. Add Show is greyed out as a result.

Nothing interesting in the Logs to show. :\

**Comment by markheloking** [comment]
Also having this issue. I have this in combination with the search (for the show name) timing out when I select [ALL] for the providers.

**Comment by flashburn2012** [comment]
I just ran into this issue today with Marvel's Agent Carter. Yesterday I added two shows with no issues.

**Comment by fernandog** [comment]
@thadius856 @freddysmith1 @udochrist @Bolt82 @d4n3sh @markheloking 

I figure it out. Before click "Search" button, you **must** select the folder in the folders list (yes, should be select by default - will try to fix it)
If you don't select it, the "Adding show **** into unknown dir." appear

We have to wait echelon permanent fix it.

**Comment by fernandog** [comment]
Can you test it ?
@thadius856 @freddysmith1 @udochrist @Bolt82 @d4n3sh @markheloking

use this file
https://raw.githubusercontent.com/fernandog/SickRage/patch-16/gui/slick/interfaces/default/inc_rootDirs.tmpl

**Comment by BKSteve** [comment]
Tested- Total result NOT good.

1. It does enable the 'Add New Show' functionality to work and I am able to add new shows.

2. It does some how affect the 'General Configuration > Show root directories'
*The list of directories within the config.ini is not read properly if there are multiple, in that it doesn't display all of them even though they are in the config.ini file.
*With multiple root directories it also forgets the default as well.

Have reverted to the old 'inc_rootDirs.tmpl'

**Comment by fernandog** [comment]
@BKSteve 

can you test this please?

https://github.com/fernandog/SickRage/blob/patch-18/gui/slick/interfaces/default/inc_rootDirs.tmpl

**Comment by thadius856** [comment]
Fernando, the workaround you described does it fix it. However, none of the
"Parent folders" are marked as default in the Add Shows page, even though
I've double-checked on the settings page. The "Set as Default *" button on
the Add Shows page doesn't seem to do anything either.

I'm away from home and without my SSH keys, so I'm unable to test the
template file for you at the moment.

**Comment by fernandog** [comment]
@thadius856 javascript must be enabled to set the first one as the default

**Comment by fernandog** [comment]
@thadius856 you must edit your file SickRage/slick/interfaces/default/inc_rootDirs.tmpl to this one:
https://github.com/fernandog/SickRage/blob/patch-18/gui/slick/interfaces/default/inc_rootDirs.tmpl

**Comment by markheloking** [comment]
@fernandog can you make a pullrequest out of that file as well?

**Comment by fernandog** [comment]
@markheloking already did and it was merged. closing
