### ISSUE TITLE
Popular Shows Fetching of IMDB Data failed. Are you online?

### ISSUE THREAD

**Issue by Kawalskint** [SiCKRAGETV/sickrage-issues#2860]
Cannot view Popular Shows

Fetching of IMDB Data failed. Are you online?
Exception: 'NoneType' object has no attribute 'contents'

BRANCH: (master) / COMMIT: (29105fd42b203393cc2393d683a3d11b74a0c752)
Windows 8.1

**Comment by Kawalskint** [comment]
Seems to be a known issue at https://github.com/SiCKRAGETV/sickrage-issues/issues/2477

**Comment by kailia** [comment]
+1
