### ISSUE TITLE
Fetching of IMDB Data failed. Are you online?

### ISSUE THREAD

**Issue by Drempelaar** [SiCKRAGETV/sickrage-issues#2862]
BRANCH: (master)
COMMIT: (29105fd42b203393cc2393d683a3d11b74a0c752) 
PYTHON: 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
OS: Ubuntu 14.04.3 LTS

Getting error on page http://192.168.1.10:XXXX/home/addShows/popularShows/

<img width="561" alt="screen shot 2015-09-19 at 15 31 13" src="https://cloud.githubusercontent.com/assets/14020815/9976411/8d02ccb6-5ee3-11e5-9240-bd07529f788c.png">

**Comment by neoatomic** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/2830
