### ISSUE TITLE
[APP SUBMITTED]: Loaded module _home_osmc_SickRage_gui_slick_views_home_mako not found in sys.modules

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#2863]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.1.5-1-osmc-armv7l-with-debian-8.2**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@1c2ab324cadc92e12f7d7a64944305fdf208a5b7
Link to Log: https://gist.github.com/8a6a4d39232b06f47aeb
### ERROR
```
Thread-43 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 680, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 114, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/home/osmc/SickRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/osmc/SickRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/home/osmc/SickRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _home_osmc_SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
deleting cache/mako does not help

**Comment by fernandog** [comment]
this happens when I open /home, then /comingepisodes then /home again

**Comment by fernandog** [comment]
If Its duplicate why issue submitter didnt use the original issue?

**Comment by miigotu** [comment]
because the files have changed paths, and not everyone has their SR in the same path anyways. the path is in the title.

**Comment by fernandog** [comment]
None has a fix. What should I do?

**Comment by miigotu** [comment]
wait just like everyone else is. if we had a solution it would already be fixed.

**Comment by WebSpider** [comment]
Because the file path is different in your install


-----Original Message-----

**Comment by fernandog** [comment]
Ops. Sorry
