### ISSUE TITLE
Can't switch to Develop because of DB error

### ISSUE THREAD

**Issue by kendog819** [SiCKRAGETV/sickrage-issues#2866]
![image](https://cloud.githubusercontent.com/assets/11353628/9977083/06fa9bd6-5ec9-11e5-8b0b-bccb28887a80.png)
I been having issues using several torrent providers (torcache issue), which supposedly is fixed in the develop branch, but I can't use the develop branch..lol 

I'm getting this error:

![image](https://cloud.githubusercontent.com/assets/11353628/9977089/6baac330-5ec9-11e5-8960-afcaca8e62a5.png)

It looks like a fix for this was added to develop about 5 days ago: https://github.com/SiCKRAGETV/SickRage/pull/2501

But regardless, I still can't do much with sickrage. Is there a master branch getting pushed thru soon?

**Comment by neoatomic** [comment]
Just wait till its merged on master.
If you really cant wait than fill in your github account in sickrage and than you can switch to develop.

**Comment by kendog819** [comment]
@neoatomic 

My account is filled in. I just stated that when I try to switch, that I get the error I posted above.

What am I supposed to do here??

**Comment by neoatomic** [comment]
You probably did a wrong git command.? or the db has not the right permissions.? 
Do a search here on github for solutions. If you cant than just wait till its merged to master.

**Comment by kendog819** [comment]
This has worked for months and just stopped working within the last couple weeks. Why are u blaming this on something I did? I did "Do a search" And I provided the link to the page I found with others having the same issue. 

I would like to use sickrage, but 3 of the 4 sites Im trying to use are giving me the torcache error when trying to download. This is supposedly fixed in develop. But I can'tget develop to work.

Can you help me get into develop? I have barely been able to use sickrage in almost a week,
