### ISSUE TITLE
[feature request]save magnet links to files for black hole

### ISSUE THREAD

**Issue by PopovK** [SiCKRAGETV/sickrage-issues#2867]
This suggestion is related to the "Could not download from <btCache>" problem preventing to get a torrent file, as the website is actively redirecting connections to another webpage.

For the record, previous and related issues : 
https://github.com/SiCKRAGETV/sickrage-issues/issues/2835 (latest fix, currently working)
https://github.com/SiCKRAGETV/sickrage-issues/issues/1552
https://github.com/SiCKRAGETV/sickrage-issues/issues/1932

It might be that most of affected users are using the black hole method for torrent search.
Also, it appears some clients (deluge, for example) are already able to parse a .magnet file as a text file, containing the magnet link , and using it properly.
Others are able to do the same with the help of a simple script.

So, the suggestion would be to add to the "Search Settings" => "Torrent search" panel those options for the black hole selection :
- choice to save a magnet link to a text file (1 file per link to prevent a possible buffer/race with reusing the same file)
- file extention choice (.magnet as default)
- use it as fallback if no torrent file is available nor downloadable, or as primary choice when both are possible.

It would give a valid workaround if the btcache redirection rises again, without the need for a libbitorrent requirement to handle a magnet=>torrent conversion
Thoughts ?

**Comment by miigotu** [comment]
1.) This adds more configuration, for something that will not work for most clients. If it needs a script to work what makes you think a user could set up a script (and the SR settings) if they cant even figure out how to connect their client to SR?
2.) We want to encourage connecting SR directly to the client, not black hole, which ALWAYS works with magnets.
