### ISSUE TITLE
Timeout on Add New Show with TVdb

### ISSUE THREAD

**Issue by adrienkohlbecker** [SiCKRAGETV/sickrage-issues#2869]
Hello,

I'm getting a timeout when I try to add a new show : `search timed out, try again or try another indexer`
I'm running the latest master at the time of writing: sickragetv/sickrage@44835360ea335b80bf74ff71c43dde0f4e486a56
The os is Ubuntu Trusty, via Docker. Here is the Dockerfile and config: https://github.com/kohlby/sickrage
This is a brand new install, so it may or may not be related to my environment. 
Here is the debug log, no mention of an exception: http://pastebin.com/Z5jFJnKw
I've confirmed that the tvdb api responds in my container by doing a manual search using curl.

Best,

**Comment by adrienkohlbecker** [comment]
And a screenshot of how it looks like in the UI:
<img width="1612" alt="screenshot 2015-09-20 05 12 28" src="https://cloud.githubusercontent.com/assets/70469/9979072/46725c8a-5f56-11e5-9945-678308083be9.png">

**Comment by miigotu** [comment]
pyopenssl installed?

**Comment by adrienkohlbecker** [comment]
Yes, here is my `pip list`
```
root@a9aa4e9f20fa:/opt/sickrage# pip list
argparse (1.2.1)
chardet (2.0.1)
Cheetah (2.4.4)
colorama (0.2.5)
html5lib (0.999)
Mako (1.0.2)
MarkupSafe (0.23)
pip (1.5.4)
pyOpenSSL (0.13.1)
requests (2.2.1)
setuptools (3.3)
six (1.5.2)
urllib3 (1.7.1)
wheel (0.24.0)
wsgiref (0.1.2)
```

**Comment by miigotu** [comment]
Python version?

**Comment by adrienkohlbecker** [comment]
2.7.6

**Comment by miigotu** [comment]
You also need to `pip install -U pyasn1 ndg-httpsclient`

**Comment by adrienkohlbecker** [comment]
Done, but I'm still getting a timeout

**Comment by miigotu** [comment]
Did you try turning it off and then back on again? LOL
It may be the docker you are using. There is another issue on here somewhere that was solved by using a different docker (possibly older?)

![image](https://cloud.githubusercontent.com/assets/390379/9979133/b8154a84-5f0e-11e5-8f65-874b2c82014d.png)

**Comment by adrienkohlbecker** [comment]
So I've found #563 which mentioned an issue with hard links, and I think I've figured it out.
I was mounting the data directory as a volume, and without the volume, everything works.
Any idea why a hard link would be needed for the search?

**Comment by adrienkohlbecker** [comment]
That is to say if it's really an issue with hard links and not another issue related to the volume

**Comment by miigotu** [comment]
hard links are used in cache control library for request caching

**Comment by adrienkohlbecker** [comment]
Is there a way to disable it?

**Comment by miigotu** [comment]
disable the library that handles web requests? lol

**Comment by adrienkohlbecker** [comment]
I mean either disable the cache or switch to another implementation than hardlinks

**Comment by miigotu** [comment]
its not our library, we just use it. there are no other options.
