### ISSUE TITLE
[APP SUBMITTED]: 403 {u'documentation_url': u'https://developer.github.com/v3/issues/#create-an-issue', u'message': u'At least one email address must be verified to do that.'}

### ISSUE THREAD

**Issue by kevins7189** [SiCKRAGETV/sickrage-issues#2871]
### INFO
Python Version: **2.7.8 (default, Jul  5 2015, 14:16:16) [GCC 4.9.2 20150212 (Red Hat 4.9.2-6)]**
Operating System: **Linux-4.1.5-100.fc21.x86_64-x86_64-with-fedora-21-Twenty_One**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@44835360ea335b80bf74ff71c43dde0f4e486a56
Link to Log: https://gist.github.com/fa0deedeed72de22e6fc
### ERROR
```
Thread-21 :: 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
verify your email for github.
