### ISSUE TITLE
KeyError on update

### ISSUE THREAD

**Issue by larrym** [SiCKRAGETV/sickrage-issues#2875]
While updating SR on Windows:

Error !
KeyError: ('C__SickRage_gui_slick_views_comingEpisodes_mako', '__anon_0x4f1f828L')
<%inherit file="/layouts/main.mako"/> <%! import sickbeard from sickbeard.helpers import anon_url from sickbeard import sbdatetime import datetime import time
C:\SickRage\gui/slick/views/comingEpisodes.mako, line 2:
<%!
C:\SickRage\gui/slick/views/comingEpisodes.mako, line 10:
<%block name="metas">
C:\SickRage\gui/slick/views/layouts/main.mako, line 46:
<meta data-var="sickbeard.FUZZY_DATING" data-content="${sickbeard.FUZZY_DATING}">
C:\SickRage\lib\mako\runtime.py, line 853:
callable_(context, *args, **kwargs)

**Comment by neoatomic** [comment]
https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket

**Comment by larrym** [comment]
I am sorry.

Branch: master
Tag & hash: v4.0.64-0-g6d7fd70
Windows 2012
Python: 2.7.8
Cause of error: Push Update Button in UI
What happened: KeyError appeared in browser 
What exptected: Go back to Coming Episodes
Logfile: ??

At the time of the KeyError, the Enable Debug checkbox was checked. However, I could not find any occurrence of 'KeyError' in the Logs directory. To make sure, I copied the Logs directory to an 
environment containing a bash shell and 'grep -r KeyError *' - showed no results.

Is it possible that this error was not logged?
