### ISSUE TITLE
Bug: Jump to Season dropdown repeats the word 'Specials' instead of each season number

### ISSUE THREAD

**Issue by kailia** [SiCKRAGETV/sickrage-issues#2876]
On shows with many seasons (e.g The Daily Show, Nova, Saturday Night Live, ...) the list of seasons is a drop-down. But the list shows Season 0, then repeats the word "specials" as many times as there are seasons. Clicking on one of them does jump to the season number that should be there, so it's only the labels that are incorrect.
Running SR 4.0.64 (6d7fd70), tested on FireFox 40.0.3 (Win), Chrome 46.0.2490.33 x64 Beta (Win) and Chrome 46.0.2490.33 x64 (OSX).
![screenshot 2015-09-20 15 47 56](https://cloud.githubusercontent.com/assets/14361400/9980998/245b239e-5faf-11e5-949c-ccaa27b8a55e.png)

**Comment by MGaetan89** [comment]
I confirm this.
I will have a look to find the issue.

**Comment by MGaetan89** [comment]
Found the bug. It will be fixed in the next release of SickRage.

**Comment by MGaetan89** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/2543
