### ISSUE TITLE
IPTorrents new domain name

### ISSUE THREAD

**Issue by flightlevel** [SiCKRAGETV/sickrage-issues#288]
IPTorrents has changed its url.

Email announcement from IPTorrents

"
Most of our users can still access us from the old site address ( www.iptorrents.com ) could all UK users please clear your browser cache, and update your bookmark to https://iptorrents.eu this is our NEW SSL secured link and avoids the restrictions/blocks from UK isp's

Our new domain name is: https://iptorrents.eu
"

**Comment by fernandog** [comment]
fixed on DEVELOP
