### ISSUE TITLE
[BUG] History page limit saving

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2881]
The history page limit isnt saving 
Just change to i.e. 500 and leave  page and return,it will be back at 100

**Comment by fernandog** [comment]
as @WebSpider said, it will only save when shutdown SR. 
IMO I would save always when load the history page

**Comment by WebSpider** [comment]
It will set the config value correctly in memory, which is saved when shutting down SR.

The issue could arise that SR crashes after changing the value, which would leave this, and many other config values unsaved after change.

I guess a call to save the cfg couldn't hurt, but we'd have to start doing that on _many_ occasions then, when changing anything in config basically.

-----Original Message-----

**Comment by fernandog** [comment]
All config pages have a 'save changes'
Dont recall another settings that are saved only in shutdown

**Comment by WebSpider** [comment]
I'll look it up!

-----Original Message-----

**Comment by fernandog** [comment]
I also would add 10, 25, 50 to history limits

**Comment by duramato** [comment]
@fernandog thanks your pr made it work again :) ,the only limit that doesn work is ALL not sure if its fixable

**Comment by fernandog** [comment]
All takes a lot of time. Mine is working

**Comment by duramato** [comment]
@fernandog can the time be improved?

**Comment by fernandog** [comment]
No. Its fetching ALL your history.

**Comment by OmgImAlexis** [comment]
@duramato we plan on adding in pagination to it later on and that'll fix the time issues. https://github.com/SiCKRAGETV/sickrage-issues/issues/2691

**Comment by fernandog** [comment]
@duramato what is the point of fetching all your history?

**Comment by duramato** [comment]
@fernandog can be usefull ,imagine i want to check what was the torrent it downloaded ,or when
