### ISSUE TITLE
Show empire (2015) can't be found

### ISSUE THREAD

**Issue by Drempelaar** [SiCKRAGETV/sickrage-issues#2886]
The show Empire is released this year according to the IMDB Popular list. However when trying to add it, it can not be found.

**Comment by Drempelaar** [comment]
Also something strange with the show Lucifer. 2 released found but with an "invalid start date". 2015 can not be found.

**Comment by neoatomic** [comment]
@Drempelaar Search on `Empire (2015)` 
Problem is here that there are more `Empire` named shows and theTVdb doesnt know you need the 2015 show.

For Lucifer i'm not sure what you mean. The show airs 2016, and currently only a "unaired" plot is released.

**Comment by Drempelaar** [comment]
@neoatomic 

The popular summary shows: 
Lucifer 8.7/10 (7,347 votes)
Satan takes up residence in Los Angeles. - Released 2015

When trying to add this show it cant be found

<img width="975" alt="screen shot 2015-09-21 at 17 23 28" src="https://cloud.githubusercontent.com/assets/14020815/9996076/b1269f3e-6085-11e5-9fd6-c952221fbf82.png">

**Comment by neoatomic** [comment]
@Drempelaar Its the first of the two results. If you open it you will see its the correct show.
The date is just a fake added on thetvdb. (2001-01-01) They add a fictional date until an official air-date is released, and than change it.

**Comment by Drempelaar** [comment]
@neoatomic that explains. Thanks!
