### ISSUE TITLE
Error: No branches found.

### ISSUE THREAD

**Issue by kendog819** [SiCKRAGETV/sickrage-issues#2891]
![image](https://cloud.githubusercontent.com/assets/11353628/9997789/141c72fa-605c-11e5-92b4-52d4eb006d7f.png)

Noticed this after updating SickBeard.py, after sickrage broke from previous update.

**Comment by fernandog** [comment]
@kendog819 do you have the setting 'Check software updates' enabled?!

also please read guidelines: https://github.com/SiCKRAGETV/sickrage-issues/

**Comment by kendog819** [comment]
![image](https://cloud.githubusercontent.com/assets/11353628/9998878/68c715e4-6061-11e5-8c37-773f5c39f47a.png)

Yes, check software updates is enabled.

**Comment by kendog819** [comment]
@fernandog  Any other suggestions?

**Comment by fernandog** [comment]
No errors in log?

**Comment by kendog819** [comment]
Ok, the last update seems to have sorted out the branches missing. But I still cannot switch to develop. When I try to restart after selecting "develop" and saving I get this error in the log:

![image](https://cloud.githubusercontent.com/assets/11353628/10034070/adec5094-615b-11e5-9d2e-6fc30df5cb2f.png)

**Comment by fernandog** [comment]
@miigotu ideas?

**Comment by miigotu** [comment]
try clicking the tools->check for updates before switching branched.

**Comment by kendog819** [comment]
"No updates needed" followed by same error in log.

**Comment by kendog819** [comment]
![image](https://cloud.githubusercontent.com/assets/11353628/10036135/2cc15134-6171-11e5-80f5-3b95012b461e.png)

**Comment by miigotu** [comment]
Definitely don't need any more screenshots of your settings, and it won't get solved any faster by opening more than one issue about the same problem. If you need to switch branched use git directly for now.

**Comment by kendog819** [comment]
There isn't more than one issue opened.....sir.

**Comment by miigotu** [comment]
can't update. can't switch to develop. no branches found. yes, all the same issue, which was reported before you opened any issues.

**Comment by kendog819** [comment]
Those all sound like separate issues to me, sir.  And if they were reported prior, why not say that in the 1st place? Instead of telling me to "try clicking the tools->check for updates before switching branched.".

When new updates come out, and I still have the same issues, after u KEEP closing my threads when I am having problems, I will continue to keep reporting the problem.

Thanks

**Comment by kendog819** [comment]
![image](https://cloud.githubusercontent.com/assets/11353628/10047481/6425dc2e-61dc-11e5-9f9f-c84a37140e0c.png)

Now what more info can I provide to help get this issue sorted?

**Comment by miigotu** [comment]
1.) Just because an issue is closed does not mean no further conversation can happen. closed does not mean fixed.
2.) Your other issues are closed because you are opening duplicates.
3.) The same exact error on 2 different architectures are the same bug
4.) A new update does not mean every fucking bug is fixed in SR.

**Comment by OmgImAlexis** [comment]
@miigotu 4.) If only it was that easy... :cry:

**Comment by miigotu** [comment]
Just getting a little short with patience for these people who think their issues must be resolved before everyone elses. What makes them think they get special treatment/priority? There are issues that have been open for months and users who wait patiently for the issue to get worked out, that are GRATEFUL that SR even exists.
