### ISSUE TITLE
[APP SUBMITTED]: cannot concatenate 'str' and 'TVShow' objects

### ISSUE THREAD

**Issue by stacimail** [SiCKRAGETV/sickrage-issues#2892]
Brand new, fresh install, one show added...

When pressing "edit" on show:

### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 21:59:41) [GCC 4.6.4 20130405 (prerelease)]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@e37a760bd10b8ef34051001226ee43b5cf59c222
Link to Log: https://gist.github.com/4cc86168e3a589de84a2
### ERROR

<img width="1117" alt="screen shot 2015-09-21 at 12 01 53 pm" src="https://cloud.githubusercontent.com/assets/10871411/9998809/a42c1c46-6058-11e5-8002-4cca45007ad4.png">

---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by stacimail** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 21:59:41) [GCC 4.6.4 20130405 (prerelease)]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@e37a760bd10b8ef34051001226ee43b5cf59c222
Link to Log: https://gist.github.com/f0605864c86b7eff9870
### ERROR
```
Thread-58 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 274, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 1495, in togglePause
    return self.redirect("/home/displayShow?show=" + show)
TypeError: cannot concatenate 'str' and 'TVShow' objects

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Did a clean install on Windows, added a show, and indeed when hitting the Edit or Pause button i get an error.
`SR Version:  BRANCH: (master) / COMMIT: (e37a760bd10b8ef34051001226ee43b5cf59c222)  `

Also tested my Syno with Develop and the edit button works fine there.However hiting `pause` gives the `TypeError: cannot concatenate 'str' and 'TVShow' objects`error. 

http://pastebin.com/FEmpWCAs

**Comment by miigotu** [comment]
@neoatomic a little late, its been hotfixed ^

**Comment by neoatomic** [comment]
@miigotu You fix bugs faster as i can test. :P

**Comment by stacimail** [comment]
pause/resume working perfect now, thanks! Any update on the first error "cannot import name exceptions"?

**Comment by miigotu** [comment]
Stop SR, delete cache/mako, Start SR.

**Comment by fernandog** [comment]
Havent we added the deletion of mako folder when updating?
@webspider did afaik

**Comment by stacimail** [comment]
deleted mako folder, restarted...no change

**Comment by miigotu** [comment]
Booyah

**Comment by stacimail** [comment]
fixed! You made my day @miigotu :+1:

**Comment by Jeffoz** [comment]
@stacimail it's fixed :)
