### ISSUE TITLE
Selecting two or more titles at the same time and clicking Wanted causes error.

### ISSUE THREAD

**Issue by comarkm** [SiCKRAGETV/sickrage-issues#2893]
I've been testing this for a couple of weeks and get the same result consistently.  When selecting two titles or more at the same time and changing their status to wanted I get the following error.  I do not get this when selecting one, changing it's status to wanted and then repeating for the next one.

AA
AAIndexError: list index out of range
AA    if not result.extraInfo[0].wantEpisode(season, epNo, result.quality):
AA  File "/opt/sickrage/sickbeard/nzbSplitter.py", line 185, in splitResult
AA    individualResults = nzbSplitter.splitResult(bestSeasonResult)
AA  File "/opt/sickrage/sickbeard/search.py", line 585, in searchProviders
AA    searchResult = search.searchProviders(self.show, self.segment, False)
AA  File "/opt/sickrage/sickbeard/search_queue.py", line 221, in run

Thanks,
Mark

**Comment by OmgImAlexis** [comment]
@MGaetan89 @miigotu

**Comment by MGaetan89** [comment]
I just tested on my SickRage and I did not get any error.
@OmgImAlexis Do you have this error too?
@miigotu Any idea?

**Comment by miigotu** [comment]
@MGaetan89 did you test with nzb and season only? Seems from his log that is what he has set.

**Comment by MGaetan89** [comment]
Ah, missed that. No, I am not using nzb.

**Comment by OmgImAlexis** [comment]
@MGaetan89 nah, I don't use either of those settings.

**Comment by fernandog** [comment]
@comarkm do you still have this issue?

**Comment by comarkm** [comment]
I can confirm that it's fixed by the latest updates.  I just verified that
it is working correctly.

Thanks,
Mark
