### ISSUE TITLE
ApiBuilder is broken

### ISSUE THREAD

**Issue by MGaetan89** [SiCKRAGETV/sickrage-issues#2894]
<img width="570" alt="capture d ecran 2015-09-21 a 19 57 01" src="https://cloud.githubusercontent.com/assets/1009664/10000229/2316c85c-609b-11e5-9e9c-7c2e76975386.png">

Everything is empty.
I guess it's from https://github.com/SiCKRAGETV/SickRage/commit/40368980f8d6e7cf071e2eb7adf6c0b29678988e

@OmgImAlexis

**Comment by MGaetan89** [comment]
I'm working on a new API builder, so this might not need to be fixed if no one else complain.
I'll try to send a PR in the next couple of days with the results of my experiments :)

**Comment by OmgImAlexis** [comment]
Yeah probably my fault, loads of that code looked like it was only just held together. If the API builder is still being used let me know and I can fix it up, otherwise we'll just wait for your PR.

**Comment by MGaetan89** [comment]
I use it from time to time, but I can use the API directly for the moment.
Let's see if other users need it. Otherwise we can wait for my PR. It shouldn't take too long.

**Comment by OmgImAlexis** [comment]
To be honest anyone that's using it should be okay with waiting as they'd be developers themselves.

**Comment by MGaetan89** [comment]
Totally agree :)

**Comment by MGaetan89** [comment]
It's still a WIP, but here is a preview of the new API builder.

What's new so far:
- New design, so it is better integrated in SickRage user interface
- Much better performance! Seriously, the current API builder does way too many SQL queries when it starts. For the moment, I only need 2
- Each argument is (well, will be) clearly documented. The existing documentation should be improved in some places, but that's an other issue
- The list of commands is automatically retrieved from `webapi`. So there is no need to update the API builder when a new command is available
- The response time is display for each call. This way we can see if a command takes too much time for what it does

What's coming:
- Customize the parameters of each command, in a smarter way than the current API builder
- Add a link in *Config* > *General* > *Interface* to the API builder. There is no reason anymore to hide it
- Support dark theme. Currently, it does not display tables well (or maybe I'm just using the wrong classes, as the shows list displays just fine)
- Restore currently available options: debug/profile/jsonp. Help is no longer necessary, as it is displayed directly on the page

<img width="1271" alt="API builder" src="https://cloud.githubusercontent.com/assets/1009664/10029237/2e5b2c0e-6171-11e5-9052-2659f47a168e.png">

If someone wants to try it, I can commit it on my fork or submit a PR (depending on what you prefer). But keep in mind that, as I said, I'm still working on it, and not everything is ready.

**Comment by miigotu** [comment]
this works with the existing api right? I like it so far.

**Comment by MGaetan89** [comment]
Yes, I am only updating the API builder interface and features. The API itself remains the same.

**Comment by fernandog** [comment]
@MGaetan89 can we close this?

**Comment by MGaetan89** [comment]
Yes. I forgot about this ticket...
