### ISSUE TITLE
Sorting by previous episode date uses first integer instead of date

### ISSUE THREAD

**Issue by topper59** [SiCKRAGETV/sickrage-issues#2895]
When you sort by the "Prev Ep"  tab on the Shows page, it sorts it by the first integer of the date. Mine are being sorted by month and when I change the date format to begin with the day, it sorts by day. A simple fix seeing as the "Next Ep" sorts properly.

Master branch commit: 044081bebc62cf2318e747afd15adf778c56c2c8
Python 2.7.8
Running on FreeNAS

**Comment by OmgImAlexis** [comment]
Fixed: https://github.com/SiCKRAGETV/SickRage/pull/2564
