### ISSUE TITLE
[BUG] Debug Logging Cannot Be Turned Off

### ISSUE THREAD

**Issue by gmusgrave** [SiCKRAGETV/sickrage-issues#2897]
At one point I checked "*Enable debug logs*" under __*Settings | General | Advanced Settings*__, and debug information started to be written to the logs. This is what I would expect.

After resolving an issue, I unchecked this box. 

However, debug info is still being written to the logs (making them rather large and verbose). I've looked at config.ini, and the line "*debug = 0*" is present, so I don't understand why this is happening.

**Comment by miigotu** [comment]
The logs ALWAYS have had debug on. The setting is just for the log viewer in the web ui.
