### ISSUE TITLE
[BUG] SR Appears to Not Always Recognise Correct Quality

### ISSUE THREAD

**Issue by gmusgrave** [SiCKRAGETV/sickrage-issues#2899]
SR doesn't always seem to detect the quality of a download.

Refer to the following from my log:

`SEARCHQUEUE-BACKLOG-77075 :: [KickAssTorrents] :: Quality of Jeopardy!.S2015E153.2015-09-14.mp4.(HDTV.720p)-Vader85 is Unknown`

I would have expected it to identify this as 720p HDTV. It didn't download this because of this apparent quality mismatch.

**Comment by fernandog** [comment]
that one dont follow scene naming pattern

**Comment by miigotu** [comment]
There is no codec in the name either. If the ( ) were not there, this is SDTV.
