### ISSUE TITLE
[Feature Request]  Individual source selection for "wanted" items

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#29]
<a href="https://github.com/chqp"><img src="https://avatars.githubusercontent.com/u/9638994?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [chqp](https://github.com/chqp)**
_Monday Dec 01, 2014 at 03:23 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/997 (5 comment(s))_

----

sometimes it would be helpful to be able to see all sources SB finds for "wanted"-items and to choose the preferred source manually. this would make handling of failed downloads even easier.

in some cases i'd also love to see a "get them all"-option in which SB tries to fetch ALL sources for a "wanted"-item following a predefined pattern including delays.

**Comment by raymondtrueman** [comment]
#883 and this issue seem to be duplicates of each other @fernandog

**Comment by raymondtrueman** [comment]
#833

**Comment by WebSpider** [comment]
Closing this, as the duplicate is better documented and motivated.
