### ISSUE TITLE
KODI notification settings reset/cleared after update

### ISSUE THREAD

**Issue by frdfsnlght** [SiCKRAGETV/sickrage-issues#290]
Branch: master
Commit hash: 33e95870e0
Your operating system and python version: Ubuntu 3.13.0-43 (XBMbuntu) , python 2.7.6
What you did: updated via web interface by clicking the "Update Now" link
What happened: all the KODI notification settings were set back to defaults and KODI notifications were turned off
What you expected: all the KODI notification settings to remain at what I set them to before the update

No logs for this one. This has always happened for me whenever updating (at least the last 3 or 4 updates), but I'm just getting around to reporting it. I don't use any other notification methods so I can't tell if any of those also get reset.

**Comment by abeloin** [comment]
Ref fixed in commit https://github.com/SiCKRAGETV/SickRage/commit/eff83dd745f30ed1f62991f0216b37444440c559 which was merged on 2014/12/21
