### ISSUE TITLE
actors missing

### ISSUE THREAD

**Issue by AubreyKloppers** [SiCKRAGETV/sickrage-issues#2900]
No actor information available when scanning a show into SickRage.  Is there a setting missing?

kind regards
Aubrey Kloppers (aka cyber7)

**Comment by daveyboy37** [comment]
No there isn't a setting missing.
SickRage isn't a media manager... Not really sure why it would have actors names tbh..

**Comment by fernandog** [comment]
SR only add actors to .nfo file (when you choose to create it). Read wiki

**Comment by miigotu** [comment]
Actors were not being written on new nfo creation. Just found the problem and fixed it (at least for me)

**Comment by miigotu** [comment]
@AubreyKloppers to get actors in your nfo's, you would have to delete the nfo and force a full update of the show. It still does not update existing nfo (needs some more complex logic for that to work)

**Comment by AubreyKloppers** [comment]
@miigotu Please could you tell me where to find the setting you refer to?

kind regards
Aubrey

**Comment by fernandog** [comment]
@miigotu Forced update should delete and create another.

**Comment by AubreyKloppers** [comment]
@fernandog Please could you tell me where the setting is to enable actor downloads?  (Into the .inf file...)

**Comment by fernandog** [comment]
no setting. it auto creates
please backup one show .nfo, remove from show folder and force update. See if works.
