### ISSUE TITLE
[Feature Request] IMDB score column on overview page

### ISSUE THREAD

**Issue by NicoLeOca** [SiCKRAGETV/sickrage-issues#2901]
Hi,

I'd be interested to see a column with the IMDB score.
Maybe after you put back the volume on HDD column. :-)

Keep up the good work!

**Comment by MGaetan89** [comment]
I'm a bit confused by "overview page" and "column". Do you mean the overview of a show or the list of shows?

Because the overview of a show already has this information:
<img width="330" alt="capture d ecran 2015-09-21 a 22 09 33" src="https://cloud.githubusercontent.com/assets/1009664/10003605/7b7ea836-60ad-11e5-805d-861f80470644.png">

**Comment by NicoLeOca** [comment]
Sorry if I wasn't clear, I meant here:

![image](https://cloud.githubusercontent.com/assets/9487685/10003676/f8ec51ce-60ad-11e5-9142-344b3b926057.png)

**Comment by NicoLeOca** [comment]
It may fair to say that we all have different kind of information we would like to be displayed.
Could we have a column selector setting then? :-)

**Comment by MGaetan89** [comment]
Ok, so this needs to be implemented.

The column selector is already available. It is just above the table, on the left of the layout selector and the search box.

**Comment by NicoLeOca** [comment]
Thank you @MGaetan89 
it's amazing I've never seen it before..

Depending on how hard it is to code; could we also have other pieces of information diplayed here:
![image](https://cloud.githubusercontent.com/assets/9487685/10004199/c355e2c0-60b0-11e5-996b-2b43abe73dfc.png)

i specifically think about:
duration
genres
size - please add it back :-)
and maybe a direct link to imdb hidden behind the score

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
