### ISSUE TITLE
Anime (Whitelist <> Available Groups <> Blacklist) Not working, Javascript Error

### ISSUE THREAD

**Issue by meffect** [SiCKRAGETV/sickrage-issues#2902]
```
me@vm-upvr:~/.sickrage$ git branch
* master
me@vm-upvr:~/.sickrage$ git rev-parse HEAD
657ffd7c4e61d32cecde009541cd25476579b254
me@vm-upvr:~/.sickrage$
```

```
me@vm-upvr:~/.sickrage$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
me@vm-upvr:~/.sickrage$ python --version
Python 2.7.6
me@vm-upvr:~/.sickrage$
```

Javascript File: blackwhite.js

Error line 34

Uncaught ReferenceError: $ is not defined

![](http://i.imgur.com/G6vnbK9.png)

![](http://i.imgur.com/xgMf7C4.png)

probable reason why:

script type="text/javascript" src="/js/blackwhite.js?6135"

is called before 

script type="text/javascript" src="/js/lib/jquery-1.11.2.min.js?6135" in the HTML

when you inspect source on the page html

picture of html source showing issue: 

![](http://i.imgur.com/m6USIyD.png)

**Comment by OmgImAlexis** [comment]
@meffect for reference if you see anything like this again tag me.

**Comment by meffect** [comment]
kk

**Comment by OmgImAlexis** [comment]
Fixed: https://github.com/SiCKRAGETV/SickRage/pull/2563
