### ISSUE TITLE
[APP SUBMITTED]: 'utf8' codec can't decode byte 0xe0 in position 34: invalid continuation byte

### ISSUE THREAD

**Issue by racinrandall** [SiCKRAGETV/sickrage-issues#2903]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@657ffd7c4e61d32cecde009541cd25476579b254
Link to Log: https://gist.github.com/c668286072cc6ae4f2a1
### ERROR
```
Thread-49 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 274, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 2170, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 269, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 540, in process_media
    if already_postprocessed(processPath, cur_video_file, force, result):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 515, in already_postprocessed
    sqlResult = myDB.select(search_sql, [u'%' + videofile])
  File "/usr/pbi/sickrage-amd64/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe0 in position 34: invalid continuation byte

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Please set your locale UTF-8.
Read wiki / forum sticky

**Comment by OmgImAlexis** [comment]
@fernandog since this is a reoccurring issue should we not have local set to `UTF-8` by default on new installs?

**Comment by fernandog** [comment]
@OmgImAlexis didn't undestand sorry. User should do this in his S.O. 

@miigotu will fix all this encode/decode issues soon with python3 if I understand right.

**Comment by miigotu** [comment]
@OmgImAlexis we cannot control what locale users have set on their machine.

@fernandog big unicode sandwich first, thats what fixes it.

**Comment by racinrandall** [comment]
FreeNAS is set to UTF-8.  The Jail that SickRage is running in is also set to UTF-8.  Not sure where else to change this.  I get the error when I do a manual post processing due to Auto post processing keeps failing .

**Comment by fernandog** [comment]
@racinrandall your Locale: unknown. See issue info

**Comment by racinrandall** [comment]
I see where that is and on the WebUI under help and info it shows locale as (none:none).  I just don't see anything on any of the config pages to change that.  I also opened up the config.ini file and didn't see a locale setting in there either.

**Comment by fernandog** [comment]
see in localhost:8081/config the user SR is running
then check if that user has utf-8 locale set

**Comment by racinrandall** [comment]
The user is a Daemon account.  It does not allow me to log in as that user to check the locale for that account.  
media:*:816:816:Media Plugins Daemon:/nonexistent:/usr/sbin/nologin

Checking the locale logged in as root give me the following:
LANG=en_US.UTF-8                                                                
LC_CTYPE="en_US.UTF-8"                                                          
LC_COLLATE="en_US.UTF-8"                                                        
LC_TIME="en_US.UTF-8"                                                           
LC_NUMERIC="en_US.UTF-8"                                                        
LC_MONETARY="en_US.UTF-8"                                                       
LC_MESSAGES="en_US.UTF-8"                                                       
LC_ALL=

**Comment by fernandog** [comment]
you should set LC_ALL as utf-8

**Comment by OmgImAlexis** [comment]
@miigotu can we not just change the locale for SickRage using ENV?

For example for English, or maybe something like a warning asking if they'd like their locale changed to `their_language.UTF-8`?
````
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
````

**Comment by racinrandall** [comment]
@fernandog Unfortunately that is a little over my knowledge level.  I don't have much knowledge on BSD and the stuff I find online about changing the locale don't seem to be working on my FreeNAS setup.

I have bigger problems with auto post processing I need to fix before I come back to this one.

**Comment by fernandog** [comment]
@neoatomic help here? how he can set the 'exports' in NAS? I do this by adding in .bashrc

**Comment by racinrandall** [comment]
I removed the one file that was giving SickRage problems from my download folder and I was able to manually post process the rest of the files in that folder.  Not sure what was up with that one download.

**Comment by miigotu** [comment]
@OmgImAlexis it doesnt matter what the encoding is set to really. In python2 the defaultEncoding is ALWAYS ascii. SR is currently using a hack (from SB) that reloads sys and forces changing the encoding. This is very bad and is a major reason we need to simply make the unicode conversion happen and remove this hack.

Any other workaround is simply making it more difficult to fix.
