### ISSUE TITLE
[Issue]  Sickrage will not open

### ISSUE THREAD

**Issue by sjay1** [SiCKRAGETV/sickrage-issues#2904]
Hi,

Last night Sickrage just randomly closed (when I was on Couchpotato) and it will not reopen. I dismissed it last night as something that will be alright after a reboot, but it still does not work.

So far, I have done the following:

git remote add upstream https://github.com/SiCKRAGETV/SickRage.git
git fetch upstream
git checkout master
git branch -u upstream/master
git reset --hard upstream/master
git pull

(Running on Windows 7 with Python 2.7.10 which I also just did a fresh reinstall)

And still nothing has changed

As soon as I open Sickbeard (and Open With: python.exe not pythonw.exe), the CMD flashes then instantly disappears. The python process opens in task manager and then also disappears.

Here is the last data from the:
-Sickrage>Logs>sickrage file most recently: http://pastebin.com/q0S46KGG
-Sickrage>Logs>sickrage.log http://pastebin.com/E8DBVsxf

I have no idea what to do or how to fix it: any instructions or assistance would be appreciated.

Any other information needed I'll happily reply with.

Thanks

**Comment by miigotu** [comment]
try and do a git pull again

**Comment by sjay1** [comment]
@miigotu 

http://puu.sh/kk78e/1cd0d55cce.png

git pull done.

**Comment by miigotu** [comment]
teamviewer?

**Comment by sjay1** [comment]
That could be good

How do I provide details?

**Comment by miigotu** [comment]
irc or my email miigotu@gmail

**Comment by sjay1** [comment]
emailed details

**Comment by miigotu** [comment]
Fixed

**Comment by sjay1** [comment]
thanks @miigotu 

great help, appreciate it
