### ISSUE TITLE
[APP SUBMITTED]: Commit hash wrong length: 4 hash: None

### ISSUE THREAD

**Issue by NicoLeOca** [SiCKRAGETV/sickrage-issues#2905]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 23:30:53) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@657ffd7c4e61d32cecde009541cd25476579b254
Link to Log: https://gist.github.com/59ceb4db371ccec3f8e8
### ERROR
```
Thread-48 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 274, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1130, in getDBcompare
    db_status = checkversion.getDBcompare()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/versionChecker.py", line 203, in getDBcompare
    assert len(cur_hash) is 40, "Commit hash wrong length: %s hash: %s" % (len(cur_hash), cur_hash)
AssertionError: Commit hash wrong length: 4 hash: None

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@NicoLeOca 
do you have "check updates" enabled?

**Comment by NicoLeOca** [comment]
Yes it is, every 12 hours 
Automatic update unchecked

**Comment by WebSpider** [comment]
Can you use the commandline to perform a 
```
git pull origin master
```
Looks like something went wrong with your git repository

**Comment by XxUnkn0wnxX** [comment]
getting same issue on my Mac OS:

      2015-09-24 16:34:45 Thread-18 :: Failed doing webui callback: Traceback (most recent call last):
  File "/Users/USER/Apps/SickRage/sickbeard/webserve.py", line 274, in async_call
    result = function(**kwargs)
  File "/Users/USER/Apps/SickRage/sickbeard/webserve.py", line 1130, in getDBcompare
    db_status = checkversion.getDBcompare()
  File "/Users/USER/Apps/SickRage/sickbeard/versionChecker.py", line 203, in getDBcompare
    assert len(cur_hash) is 40, "Commit hash wrong length: %s hash: %s" % (len(cur_hash), cur_hash)
AssertionError: Commit hash wrong length: 4 hash: None

        2015-09-24 16:33:59 Thread-15 :: Failed doing webui callback: Traceback (most recent call last):
  File "/Users/USER/Apps/SickRage/sickbeard/webserve.py", line 274, in async_call
    result = function(**kwargs)
  File "/Users/USER/Apps/SickRage/sickbeard/webserve.py", line 1130, in getDBcompare
    db_status = checkversion.getDBcompare()
  File "/Users/USER/Apps/SickRage/sickbeard/versionChecker.py", line 203, in getDBcompare
    assert len(cur_hash) is 40, "Commit hash wrong length: %s hash: %s" % (len(cur_hash), cur_hash)
AssertionError: Commit hash wrong length: 4 hash: None

when click the checkout Branch button in general advanced settings
it is set to master. i also have a user set up in Github options set there..

also i am running SickRage as my own user not root so set all perms on all files with my user including git folder...

**Comment by NicoLeOca** [comment]
for some reason, I have not having this issue anymore

**Comment by fernandog** [comment]
What did you do?

**Comment by NicoLeOca** [comment]
Hi @fernandog 
I don't really know unfortunatelly.
I updated SR while I way away from home and now it's gone.

**Comment by jacquesbens** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@f913285d1decce196c6054c43507582fb2a2a7ee
Link to Log: https://gist.github.com/1ba94c17c0401679032f
### ERROR
```
Thread-29 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 275, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 1131, in getDBcompare
    db_status = checkversion.getDBcompare()
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/versionChecker.py", line 203, in getDBcompare
    assert len(cur_hash) is 40, "Commit hash wrong length: %s hash: %s" % (len(cur_hash), cur_hash)
AssertionError: Commit hash wrong length: 4 hash: None

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Rouzax** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@f913285d1decce196c6054c43507582fb2a2a7ee
No Log available with ERRORS: 
### ERROR
```
Thread-20 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\Program Files (x86)\SickRage\sickbeard\webserve.py", line 275, in async_call
    result = function(**kwargs)
  File "C:\Program Files (x86)\SickRage\sickbeard\webserve.py", line 1131, in getDBcompare
    db_status = checkversion.getDBcompare()
  File "C:\Program Files (x86)\SickRage\sickbeard\versionChecker.py", line 203, in getDBcompare
    assert len(cur_hash) is 40, "Commit hash wrong length: %s hash: %s" % (len(cur_hash), cur_hash)
AssertionError: Commit hash wrong length: 4 hash: None

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by ThomasDK81** [comment]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.3-RELEASE-p25-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@5aac5803f2e1df3385a5cb19580b8fd6b4eb6191
Link to Log: https://gist.github.com/7f3ac68e8e4170488959
### ERROR
```
Thread-37 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 275, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 1131, in getDBcompare
    db_status = checkversion.getDBcompare()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/versionChecker.py", line 203, in getDBcompare
    assert len(cur_hash) is 40, "Commit hash wrong length: %s hash: %s" % (len(cur_hash), cur_hash)
AssertionError: Commit hash wrong length: 4 hash: None

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
@fernandog you need to remove that raise.

**Comment by WebSpider** [comment]
Reading up on this, it indeed seems silly to compare if it is 6 chars, as the commit-hash abbrev has a dynamic length. It should not be 0, that would be safer.

http://blog.cuviper.com/2013/11/10/how-short-can-git-abbreviate/

**Comment by fernandog** [comment]
If remove that raise we will get return 'error' in JSON. And we still have the unable to check DB issue. That wont solve the problem. Need to fix the bug instead.

**Comment by WebSpider** [comment]
We need to compare if commit hash is between 0 and 40 I guess

-----Original Message-----

**Comment by fernandog** [comment]
User commit hash len is 4. What is min len in git?

**Comment by miigotu** [comment]
The len is 4 because it is literally the string "None".

It needs to check if `_need_update` before the db check, to `populate cur_commit_hash`

**Comment by miigotu** [comment]
and it is supposed to return error, because the update failed. the raise is breaking the proper function of it whether the other problem is fixed or not. (which is likely just a git/github issue itself)

**Comment by fernandog** [comment]
after the fix, we remove the raise and add a logger.log with ex(e)

**Comment by fernandog** [comment]
@miigotu 
its strange as the user has 'check updates' enabled: https://github.com/SiCKRAGETV/sickrage-issues/issues/2905#issuecomment-142505511

so you suggestion is toadd
`self.updater.need_update()`

before this line?
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/versionChecker.py#L202

**Comment by fernandog** [comment]
@NicoLeOca stop SR, edit SickRage/sickbeard/versionChecker.py, delete contents and paste this one:

https://raw.githubusercontent.com/fernandog/SickRage/4a0caa5954c9e533da70d69b2496e3dff29cb143/sickbeard/versionChecker.py

save, start SR, try to reproduce the error please, report back

**Comment by miigotu** [comment]
so you suggestion is toadd
`self.updater.need_update()`

yes. update check might not have ran yet.

**Comment by NicoLeOca** [comment]
@fernandog 
As mentionned above, I wasn't having the issue anymore.
And I can't get it with this versionchecker.py.

here is the log:
https://gist.github.com/b65ca7ad6e27607c9ed0.git

Anything else you want me to try?

**Comment by miigotu** [comment]
@NicoLeOca nope, good to go.

**Comment by ThomasDK81** [comment]
It seems to have fixed it.
I can't reproduce it.

Thanks!
