### ISSUE TITLE
AttributeError: 'module' object has no attribute 'USE_IMDB_POPULAR'

### ISSUE THREAD

**Issue by cwallen19803** [SiCKRAGETV/sickrage-issues#2906]
SR Version:            BRANCH: (master) / COMMIT: (657ffd7c4e61d32cecde009541cd25476579b254) 
Python Version:	2.7 (r27:82525, Jul 4 2010, 07:43:08) [MSC v.1500 64 bit (AMD64)]
OS: Windows 10

From Show List Page, click Add Shows

Begin Error:
Error !

AttributeError: 'module' object has no attribute 'USE_IMDB_POPULAR'

% endif <a href="${sbRoot}/home/addShows/popularShows/" id="btnNewShow" class="btn btn-large"> <div class="button"><div class="icon-addtrendingshow"></div></div> <div class="buttontext"> <h3>View Popular Shows</h3> <p>View IMDB's list of the most popular shows. This feature uses IMDB's MOVIEMeter algorithm to identify popular TV Series.</p> </div> </a>
C:\SickRage\gui/slick/views/home_addShows.mako, line 47:
<div class="button"><div class="icon-addtrendingshow"></div></div>
C:\SickRage\gui/slick/views/layouts/main.mako, line 220:
C:\SickRage\lib\mako\runtime.py, line 853:
callable_(context, *args, **kwargs)
End error:

There is nothing on the log, debug or otherwise, during the time frame this error occurred.  For instance, the error occurred at 7:33 and the last log entry was 7:25.  Debug was enabled.

**Comment by miigotu** [comment]
Stop SR, delete cache/mako, Start SR.

**Comment by cwallen19803** [comment]
Yes.  Thank you.  I noticed that after installing updates for BRANCH: (master) / COMMIT: (5391476827cf369a2d16a4e7ee8128f47a75f74c) that folder reappears.  The original issue, however, remains fixed.

**Comment by miigotu** [comment]
It is supposed to reappear. It is the cache for mako.
