### ISSUE TITLE
[Bug] Notifications not working on Chrome for Android

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2909]
The notifications don't seem to work on chrome for Android
It seems that "webkit notifications are different on mobile chrome." 
@MGaetan89

**Comment by OmgImAlexis** [comment]
@duramato I don't think that's true, the API should be the same with the desktop and the mobile version.
http://caniuse.com/#feat=notifications

**Comment by duramato** [comment]
@OmgImAlexis It was miigotu who told me that

**Comment by MGaetan89** [comment]
I have no idea how mobile web-notifications work, so can't help you here :/

**Comment by OmgImAlexis** [comment]
@MGaetan89 just tested using Mozilla's official test and it doesn't work at all. So it may be a bug with Chrome on Android or it may not be fully available yet. https://developer.mozilla.org/en-US/demos/detail/html5-notifications

**Comment by OmgImAlexis** [comment]
Closing this as it's an issue with Chrome or the web notifications API and not SR.

**Comment by miigotu** [comment]
Might have been due to some missing js files anyways?

**Comment by OmgImAlexis** [comment]
@miigotu nope, tested the Mozilla one and it's broken on that and that's the "official" test. If theirs is broken we've got no hope.

**Comment by miigotu** [comment]
Alright. Feels silly because notifications work on my desktop.

**Comment by duramato** [comment]
@OmgImAlexis Firefox works fine for me on Android..

**Comment by OmgImAlexis** [comment]
@duramato then it's a chrome issue on Android, still something we can't change.

**Comment by fernandog** [comment]
I dont get any notification in android (enabled)
