### ISSUE TITLE
Auto Post Processing not working

### ISSUE THREAD

**Issue by racinrandall** [SiCKRAGETV/sickrage-issues#2912]
For some reason the auto post processing quit working on my system.  This is a new install on a FreeNAS system I just setup last week.  This is my first time using SickRage.  It was running just fine for a few days then auto post processing quit working.  Manual post processing works fine.  When I pull up the server status page it shows that Post Process is not alive but enabled and active. (pic included).  I updated Sickrage last night and Auto Post Processing worked for about 10 minutes then crapped out again.

Any ideas?
I still haven't figured out how to fix my locale issue, but I don't think they are related.

SR Version:	BRANCH: (master) / COMMIT: (f7d55c141f2001dadbedb8d699513bfc2c51a667) 
SR User:	media
SR Locale:	(None, None)
SR Config:	/var/db/sickrage/config.ini
SR Database:	/var/db/sickrage/sickbeard.db
SR Cache Dir:	/var/db/sickrage/cache
SR Log Dir:	/var/db/sickrage/Logs
SR Arguments:	['--datadir', '/var/db/sickrage', '-d', '--pidfile', '/var/run/sickrage/sickrage.pid', '-q', '--nolaunch']
Python Version:	2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]

![image](https://cloud.githubusercontent.com/assets/14680706/10021074/c8f495e0-610b-11e5-8375-b331e318860e.png)

**Comment by neoatomic** [comment]
We need full debug logs, so we can take a look.
But its probbebly a permission/setup issue on your system. (Used a installation package.?)

Try manual post-processing, see if that works. And empty your `tv download dir` to ensure it isn't a bad file.

**Comment by racinrandall** [comment]
Manual post processing does work as mentioned in opening post.  The Auto Post Processing did at one time work and I have not changed any permissions since it has worked.  The download directory is 777 and all files placed in there are 777.
Here is the most recent log file.  https://gist.github.com/46034a469acb23f262fd.git

**Comment by miigotu** [comment]
All that is in that log is your daily search. Restart SR and the thread should be alive until PP runs. We need it with debug from the start of auto post processing til it dies.

**Comment by racinrandall** [comment]
I restarted SR and for some reason the PP shows as alive.  Not sure why it works this restart and not on the previous one.  I will let it run until it fails again then repost the log file.

**Comment by racinrandall** [comment]
SR pulled the same file I was having problems with a UTF-8 encoding issue.  It seems whenever SR encounters this file for PP it stops the auto PP schedule.

**Comment by racinrandall** [comment]
PP runs, but doesn't move files still.
https://gist.github.com/aeab06d3398e3a5fcf91.git

**Comment by WebSpider** [comment]
Looks like this is the same issue as #2952 .. closing this for now, as the other thread contains more info
