### ISSUE TITLE
[APP SUBMITTED]: Thread-57 :: No git specified, can't use git commands

### ISSUE THREAD

**Issue by evakq8r** [SiCKRAGETV/sickrage-issues#2913]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/f9e556160f12a77e0e93
### ERROR
```
Thread-57 :: No git specified, can't use git commands
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
use windows installer and/or read wiki pages

**Comment by miigotu** [comment]
Or install git, and add git to the system path.
