### ISSUE TITLE
Adding shows from webapi don't take into account the initial ep status

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#2914]
@MGaetan89 
as apibuilder broken I can't check if addshow accepts the two status as parameter (status_default, and status_default_after)

they are missing here and SKIPPED is hardcoded:
 sickbeard.showQueueScheduler.action.addShow(int(indexer), int(self.indexerid), self.location, SKIPPED, newQuality, int(self.flatten_folders))

https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/webapi.py#L1980

Add shows need two status: 

def addShow(self, indexer, indexer_id, showDir, default_status=None, quality=None, flatten_folders=None,lang=None, subtitles=None, anime=None, scene=None, paused=None, blacklist=None, whitelist=None, default_status_after=None):

https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/show_queue.py#L142

IMO default_status_after and default_status default values in DEF should be 
sickbeard.status_default
sickbeard.status_default_after

also this status are missing here:
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/show_queue.py#L343

@miigotu agree?

**Comment by miigotu** [comment]
In that last one they are not missing.
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/show_queue.py#L354
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/show_queue.py#L466

show_queue.py is correct.

**Comment by fernandog** [comment]
So only webapi needs to be fixed.
Maybe this can me fixed with a common addShow class

**Comment by miigotu** [comment]
Thats exactly what he is working on already. Patience.

**Comment by fernandog** [comment]
Lol Just pointing errors

**Comment by MGaetan89** [comment]
The add new show command seem to be correct, right? https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/webapi.py#L2147
It's only an issue when adding an existing show.
I will have a look to refactor that after I'm done with the API builder.

**Comment by MGaetan89** [comment]
I created a new "API" label here. Feel free to use it so I can easily see which issues concern the API.

**Comment by miigotu** [comment]
Yep, looks like only addShowExisting

**Comment by MGaetan89** [comment]
This should be fixed with https://github.com/SiCKRAGETV/SickRage/pull/3153

Now default SickRage configuration is used when adding an existing show.

**Comment by fernandog** [comment]
Thanks
