### ISSUE TITLE
Adding the possibility to change the (searching pattern) name of a tv show already added for more accurate results 

### ISSUE THREAD

**Issue by GVA-W** [SiCKRAGETV/sickrage-issues#2915]
There should be the possibility to change the searching pattern name of a TV Show afterward (or maybe just the possibility of adding the release date somewhere).

Like : The Flash (2014) (started on 2014-10-07) [theTVDB]

Why ? Because some tv show are remake, or have a common name and doesn't have the year of their release embeded in the title, like : Power (started on 2014-06-07) [theTVDB]   ---  http://www.imdb.com/title/tt3281796/

And it causes some problemes with sickbeard, especially when this rule is applied : Allowed: 720p HDTV, HDTV 1080p, 720p WEB-DL 1080p WEB-DL --- Preferred: 720p HDTV 

Sickrage is searching : Beginning manual search for: [Power - 2x03 - We're Like Any Other Couple]
BUT it should search : Power 2014 - 2x03 - We're Like Any Other Couple for a more acurrate research (behind the scene it's : power.s02e03...... it should be power.2014.s02e03)

With that, it only can find (and download) the WEB-DL version... I don't know why. Even when the HDTV versions are available on kickass and rarb

**Comment by fernandog** [comment]
Edit show
Add scene exceptions: Power 2014

Please read wiki
