### ISSUE TITLE
Looping crash right at start-up, cannot access GUI

### ISSUE THREAD

**Issue by LanMan04** [SiCKRAGETV/sickrage-issues#2916]
Branch: 
master

Commit hash:
Latest?  Unknown, cannot check.

Your operating system and python version: 
UnRAID 6.0.1, Python 2.7.9

What you did: 
Tried to access GUI

What happened: 
GUI inaccessible, "connection reset" when accessing webpage.  It appears SickRage is crashing after being alive for less than a second, then is re-spawned only to crash over and over again. Crash appears to be:
```
2015-09-22 09:59:52,908 DEBG 'sickrage' stderr output:
Traceback (most recent call last):
  File "/opt/sickrage/SickBeard.py", line 555, in <module>

2015-09-22 09:59:52,908 DEBG 'sickrage' stderr output:
    SickRage().start()
  File "/opt/sickrage/SickBeard.py", line 324, in start

2015-09-22 09:59:52,908 DEBG 'sickrage' stderr output:
    self.fix_clients_nonsense()
  File "/opt/sickrage/SickBeard.py", line 142, in fix_clients_nonsense
    filename = ek(os.path.join, sickbeard.PROG_DIR, file)
  File "/opt/sickrage/sickrage/helper/encoding.py", line 39, in ek
    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
  File "/usr/lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
AttributeError: type object 'file' has no attribute 'startswith'
```
What you expected: 
Be able to access the GUI.  Have SickRage run without almost instantly crashing.

Link to a copy/paste of your logfile with clear debug info of the error on GIST:
https://gist.github.com/LanMan04/6f442e0430d5e3844a64

**Comment by miigotu** [comment]
git pull.

**Comment by LanMan04** [comment]
Can't, git isn't available within Docker container.  Can't do a git pull using the "real" path at the OS level because this:

```
fatal: Not a git repository (or any parent up to mount point /mnt/user)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

**Comment by miigotu** [comment]
Open SickBeard.py, find line 142:
`filename = ek(os.path.join, sickbeard.PROG_DIR, file)` 
and make it:
`filename = ek(os.path.join, sickbeard.PROG_DIR, filename)`

Restart SR.

**Comment by LanMan04** [comment]
Fixed!  Thank you, sir!

**Comment by mrkake** [comment]
Had this problem too. Fixed it. Appreciate all that you do but still really sad/confused how a breaking change can make it to master branch.

**Comment by OmgImAlexis** [comment]
@mrkake a lot of the "breaking changes" that've been happening lately are to stop them from happening in the future. We've come from a bunch of hacked together code to what SR is today. :+1:
