### ISSUE TITLE
BTdigg API Issue

### ISSUE THREAD

**Issue by kendog819** [SiCKRAGETV/sickrage-issues#2918]
Not sure if you guys want these issues reported here or not, but in case you want to remove from SR (if this is even an issue), just wanted to let someone know. When clicking the favicon:

![image](https://cloud.githubusercontent.com/assets/11353628/10034190/a3c226c4-615c-11e5-8d71-3f4c5039c66e.png)

**Comment by miigotu** [comment]
1.) that's the incorrect URL, 2.) we don't use btdig api AFAIK.

**Comment by duramato** [comment]
@miigotu whe do use the btdigg api 
Also it just links to that url on sr instead of btdigg.org

**Comment by kendog819** [comment]
So it should still work properly? Someone just linked it to the wrong url?

**Comment by duramato** [comment]
It is working properly (isn't it? :p ) , the link just points to that page

**Comment by miigotu** [comment]
this guy just opened the URL without parameters and expects it to give results.

**Comment by miigotu** [comment]
@kendog18 its an api, not a website.

**Comment by kendog819** [comment]
WTF are you talking about miigotu? Someone linked the BTdigg icon to the api, instead of thewebsite like every other icon on the providers pade.  Please read before you comment, and stop trying to make me look like a dumbass, it's working in reverse for you.

**Comment by duramato** [comment]
@kendog819 its linked because its the URL sr uses for searching ,and it normal to look that way (its an api not an end user website) if you give it right params it will return the right result

**Comment by kendog819** [comment]
I've clicked every icon on that page and it takes me to the website, I was under the assumption that's what it was supposed to do. Either way, the way miigotu speaks to people (me) is extremely rude. 

![image](https://cloud.githubusercontent.com/assets/11353628/10035746/c8cc85a4-616b-11e5-98a6-61acb3fc94e2.png)


I'm sorry we can't all be on your level of expertise, sir. Forgive me.

**Comment by kendog819** [comment]
@duramato  I didn't test the provider. I was just looking thru the changes and checking the public providers out, and noticed what I thought may have been a bug. Now I feel deterred from posting anymore when I have to be spoken down to from "this guy"

**Comment by OmgImAlexis** [comment]
@kendog819 he wasn't speaking down to you, the way he was speaking is the way most developers including me speak.

**Comment by kendog819** [comment]
I work with developers for a living, and if any of them ever spoke to me like that, they would be missing some teeth. Keyboard warriors gonna keyboard warrior though.

**Comment by OmgImAlexis** [comment]
Considering you don't even have a single project on Github I doubt that, anyways if you don't like how he speaks to you then move on. Locking this to stop more shit.

**Comment by miigotu** [comment]
"I didn't test the provider" and are not a developer but are posting bug reports based on your lack of understanding whatn an api is. Of course you will get a response basically telling you that you are an idiot, because by posting a bug about something that is not a bug is like calling us idiots.

"Now I feel deterred from posting anymore"
Then I have accomplished a good thing, avoiding phony bug reports from someone who didnt even test or experience a bug.
