### ISSUE TITLE
[Feature Request] Add support for parsing TVRage specials

### ISSUE THREAD

**Issue by blahblah57** [SiCKRAGETV/sickrage-issues#292]
When I'm in a show's page I do not see Specials anywhere. They're not in the list and in the jump to season drop down they don't appear either. 

I don't see the Christmas specials in the the Upcoming Episodes either.

Is there a setting for specials I'm missing?

**Comment by drglove** [comment]
I've also noticed that same thing with Top Gear. TVRage displays the shows as a part of Season 22 which does not appear in the season list. Forcing a full update does not change the behaviour.
- Added Top Gear (2002) with TVRage as indexer to Sick Rage
- All seasons show in Sick Rage except for Season 22
- Expected the specials that TVRage claim to be part of Season 22 to be displayed

**Comment by fernandog** [comment]
@drglove @blahblah57 can you provide the missing info otherwise will close the issue.

**Comment by blahblah57** [comment]
BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8) 
OS: Windows 8.1 Pro 
Python 2.7.3
Specials are not shown or Doctor Who or Top Gear. The ones I have manually downloaded are shown, but the rest are not. Both TVDB and TVRage are aware of the numerous specials. Forcing a full update does not fix it.
Debug Log: http://pastebin.com/XSF6paJi

**Comment by abeloin** [comment]
@fernandog This affect only people using TVRAGE as their metadata provider. Currently the api in sickrage doesn't parse special.

**Comment by fernandog** [comment]
@abeloin so we should add this comment when adding shows using TVRAGE so user's can choose not having specials or not. What do you think?

**Comment by abeloin** [comment]
@fernandog Yes

**Comment by abeloin** [comment]
@fernandog Notice added in pull request SiCKRAGETV/SickRage#1235

**Comment by fernandog** [comment]
@abeloin thanks

**Comment by drglove** [comment]
This is a limitation in the Sickrage API, not the TVRage API right?
Wouldn't a fix for this include modifying Sickrage to use the special information from the metadata handed out by TVRage?

**Comment by abeloin** [comment]
@drglove Yes and yes but I don't know when it will be fixed by Echelon so, for the time being, a notice has been put in place to inform user's of the current limitation.

**Comment by fernandog** [comment]
@abeloin I think we can close the notice PR !

**Comment by abeloin** [comment]
@fernandog Honestly, I wouldn't as this pull requests is untested and there's still issues to resolve as per drglove comments(e.g. special are stored in the season directly, keep track of special).
I would prefer pushing the notice in master and continue improving this pull request and fully tested but that is my personal opinion.

**Comment by fernandog** [comment]
@abeloin good point!

**Comment by drglove** [comment]
This doesn't help to fetch the shows, in order to do that we need to have a proper episode number to search on (or some way to ignore it.) If there are any ideas on how to handle episodes that don't have an episode number, I'm all ears.

**Comment by fernandog** [comment]
@drglove special isn't S00 ? I don't like put them on 'Specials' folder

http://thetvdb.com/wiki/index.php/Special_Episodes

don't find anything related to XEM

**Comment by drglove** [comment]
@fernandog No, TVRage seems to handle things differently. Here's an excerpt of the result from the request that SickRage hits:
```
<Show>
...
<EpisodeList>
<Season>...</Season>

<Special>
<episode><season>21</season><airdate>2014-05-25</airdate> <link>http://www.tvrage.com/Top_Gear/episodes/1065562553</link><title>The Best of Top Gear (2)</title><summary>More highlights are shown from the series.</summary>  <rating>8</rating> </episode>
...
</Special>

</EpisodeList>
</Show>
```

The entire output is here http://pastebin.com/mH860063
It's incredibly minimal, and I don't readily see any way to get an absolute numbering of the episodes from TVRage. Mind you that there are a few episodes that do list season 0, although they're duplicated in season 22 (the "Patagonia Specials").

**Comment by fernandog** [comment]
If the indexer is not regular updated we can have more issues here. Will worth the effort?

**Comment by drglove** [comment]
@fernandog Not sure, at this point it's a design decision which I will leave up to you guys, since any solution at this point is a workaround TVRage's limited API.

**Comment by fernandog** [comment]
its up to @echel0n to decide

**Comment by flightlevel** [comment]
Closing issue as TVRage closed down
