### ISSUE TITLE
why were useful wiki pages destroyed?

### ISSUE THREAD

**Issue by tdev5** [SiCKRAGETV/sickrage-issues#2920]
Several useful wiki pages were destroyed. Why? Where is the info to be found?

1494e38fff3150dd680dd9855d4daf8ba7485c8a - Post Processing
15d1d30982805bb8c174fb511de0ff69848ce990 - Installation Instructions
2433bdd03c3b37cffe48ff5efb79ce95eb60697e - FAQ
a75bbf85621b7dd30e29dfe3871478b1b9f70efd - Episode Status
73e092493d8fcd88c6d9a38d677ed89c7190ceb2
ac571bab1e2c22cc9ead871225bc49e5f90def2a
8d76fd245056074599982cdb4d2c7d1ff5b29635

**Comment by fernandog** [comment]
Read SR news tab
