### ISSUE TITLE
[Meta] Issue tags

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2921]
What is "fix" for?
Should "fix" be "fixed"?
Can we get js and mako tags so we can differentiate between bugs between the two?

@SiCKRAGETV/moderators

**Comment by fernandog** [comment]
I set 'fix' when there is a fix available

I created a mako milestone related to mako issues/FR

Feel free to create another

**Comment by OmgImAlexis** [comment]
I figured before making any more I'd check what going on with them.

Would you be alright with "fixed" instead of "fix"? If you use "fix" it just sounds like the issue itself is the fix.

**Comment by fernandog** [comment]
Done
