### ISSUE TITLE
Episodes get recognised as SDTV

### ISSUE THREAD

**Issue by Drempelaar** [SiCKRAGETV/sickrage-issues#2923]
Today I did a rebuild of the database and several episodes where recognised as SDTV while the filename says its 720p.BluRay
<img width="1472" alt="screen shot 2015-09-23 at 13 51 10" src="https://cloud.githubusercontent.com/assets/14020815/10044585/7b23641c-61fc-11e5-8c5f-e6ad4008d5fc.png">

**Comment by neoatomic** [comment]
`x264` Is missing.

https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-names-to-recognize-the-quality-of-a-file

**Comment by Drempelaar** [comment]
Ok but I've selected one of the default rename scheme's. Shouldn't it be forced on those as well?
<img width="988" alt="screen shot 2015-09-23 at 15 24 10" src="https://cloud.githubusercontent.com/assets/14020815/10046150/532adbba-6207-11e5-8675-478183cc0e21.png">

**Comment by neoatomic** [comment]
You are free to pick the renaming you want.

However if you start/create a new database you lose all the renaming information that you did for those files.SickRage won't know the quality, and will scan the titles/files for a quality. 
We use scene standards to determinate that. Witch (in your case) need to include `x264`.

Thats the risk or renaming files...

**Comment by Drempelaar** [comment]
Hmm I see but could you explain the difference between the other downloads? these are detected a such while the names are somewhat the same. 

<img width="1249" alt="screen shot 2015-09-23 at 15 38 00" src="https://cloud.githubusercontent.com/assets/14020815/10046476/31c81c24-6209-11e5-9e6e-f15624117a65.png">

**Comment by neoatomic** [comment]
If no quality can be found a scan is done for the resolution of the file.
