### ISSUE TITLE
Selections on the "Shows" Page unable to reorganize by anything other than Alpha

### ISSUE THREAD

**Issue by neoaoshi** [SiCKRAGETV/sickrage-issues#2926]
The way Shows organize is stuck in Alphabetic organization. You can no longer click on Next Ep, Previous Ep, Show, Network, Quality, Downloads, Active, or Status. Even the Select Column button isnt working.

**Comment by OmgImAlexis** [comment]
https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket

**Comment by neoaoshi** [comment]
Branch: (master) / COMMIT: (484634d14db2072b62e12fa3f3d4efe684ffc66e) 
Your operating system and python version: Windows 7 64bit, Python 2.7
What you did: Updated to the latest version pushed to the front page of Sickrage
What happened: The way Shows organize is stuck in Alphabetic organization. You can no longer click on Next Ep, Previous Ep, Show, Network, Quality, Downloads, Active, or Status. Even the Select Column button isnt working.
What you expected: For no changes to the Shows page that reduce functionality
Link to a copy/paste of your logfile with clear debug info of the error on GIST: will post later.

**Comment by OmgImAlexis** [comment]
Can you update to the latest master and see if that fixes it? I'm not sure how far behind you are but I'm on `5391476827cf369a2d16a4e7ee8128f47a75f74c` and I don't have any issues at all with that.

**Comment by neoaoshi** [comment]
The latest update solved it!
