### ISSUE TITLE
History page don't work when changing limit

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2928]
When trying to set a limit on the history page ,it doesnt set refreshes the page and sets the limit back to 100 with following error
```
AAAttributeError: 'History' object has no attribute '${sbRoot}/history'
AA    method = getattr(self, route)
AA  File "/home/home/SickRage/sickbeard/webserve.py", line 257, in get
```

@MGaetan89

**Comment by MGaetan89** [comment]
I don't have that issue. It works fine for me

**Comment by fernandog** [comment]
mine don't work either. I'm redirected to my default page (comingEpisodes)

**Comment by WebSpider** [comment]
Which release does this bug exist in?

**Comment by WebSpider** [comment]
Duplicate of #2881 also created by @duramato

**Comment by fernandog** [comment]
Different issue

**Comment by duramato** [comment]
@WebSpider no ,that one is for the saving of limit while this one is the limit not working at all

**Comment by OmgImAlexis** [comment]
Does this fix it? https://github.com/SiCKRAGETV/SickRage/pull/2587

**Comment by fernandog** [comment]
Now its working! Thanks

**Comment by duramato** [comment]
@fernandog &  @OmgImAlexis  still not working for me

**Comment by OmgImAlexis** [comment]
@duramato have you updated? I don't have an issues at all on my dev install.

**Comment by fernandog** [comment]
PR another fix to history limit. now it will save setting on change

**Comment by duramato** [comment]
@fernandog & @OmgImAlexis its now fixed ,but it was fernandog pr who fixed not yours :P

**Comment by fernandog** [comment]
@OmgImAlexis fixed the JS issue loading the URL.
