### ISSUE TITLE
[Feature Request] When uploading a torrent to Transmission upload to show directory

### ISSUE THREAD

**Issue by wezzlewoo** [SiCKRAGETV/sickrage-issues#2929]
Example:
Torrent Client: Transmission
Default Trans DIR /mnt/downloads
SickRage Downloaded files location: /mnt/downloads/TV
Show Location /mnt/downloads/TV/Rick.and.Morty

When the scan is done is it possible to preserve the show location and pass that to transmission as the download directory?

**Comment by wezzlewoo** [comment]
If this is something not enabled, I'd be wiling to look into the implementation. I'm not familiar with the process you guys use for user contribution.

**Comment by WebSpider** [comment]
That is not the way SR was intended to work.

The way it's supposed to work is:

1) Show gets added to SR, specifying show_dir in root_dirs (ie /mnt/TV/Airwolf). This is where media will end up
2) SR snatches shows, send them to clients according to client settings. Clients are supposed to download the file and either
    a) run a script as post-download to hand the result to SR or
    b) drop the file in a TV_DOWNLOAD_DIR (config.ini setting) and configure automatic postprocessing in SR
3) The postprocesser is ran by the post-download script, or automatically at intervals scanning TV_DOWNLOAD_DIR

I'm personally using the post-download script by clinton-hall, found in http://github.com/clinton-hall/nzbToMedia which has TorrentToMedia,py, that supports transmission and sickrage just fine.
