### ISSUE TITLE
No 'Set Default Episode Status' in Mass Edit/Add Show

### ISSUE THREAD

**Issue by NanNans** [SiCKRAGETV/sickrage-issues#293]
The ability to change the default new-episode status to "wanted" was something I'd been dreaming of for a long time, so thanks so much to those who worked on it! It works a treat, but there are still some places in the ui where it hasn't been integrated alongside other show behavior options:

-The mass edit page: it certainly belongs here, as every other show option is included
-The add show page: though not all options are available on this page, I think the default EP status makes such a difference in the way searches are handled that it makes sense to be able to control it on a per-show level as they are added

Hope that all makes sense. Thanks!

**Comment by Drempelaar** [comment]
Was this implemented?
