### ISSUE TITLE
Timezones: should we remove 'network' time zone?

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#2930]
Local timezone makes the dailysearch convert from UNAIRED>WANTED minutes after the show REALLY aired. This don't happen with network timezone. As dailysearcher will convert hours later or hours earlier (depends on user timezone)

@SiCKRAGETV/moderators  Should we keep network time zone? What's the use for it?

**Comment by WebSpider** [comment]
If i read the code correctly, we use network timezones to calculate when a show REALLY airs, for instance in 

https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/dailysearcher.py#L52
https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/tv.py#L2606

**Comment by miigotu** [comment]
@WebSpider airdates are fully qualified with timezone. It is universal, so there is no need to convert anything by when considering times. network timezones is only necessary to show the correct network icon afaik.

Ofc we use it more than needed and are trying to fix that.

**Comment by miigotu** [comment]
Also, we had some issues in the past, because of sbdatetime and the changed locale during initialization.
