### ISSUE TITLE
[Feature request]  Allow/disallow Daily/Backlog searching during a time-frame

### ISSUE THREAD

**Issue by ThePOO** [SiCKRAGETV/sickrage-issues#2931]
I'd like to see a field added where we could specify a time-range like 1800-2330.   And a check box to indicate allow or disallow.
The purpose would be to control when SR is able to perform Daily/Backlog searches (or not).
.... and, of course, the search time interval would then start relative to the allowed time-frame.

**Comment by fernandog** [comment]
why you want that?

**Comment by ThePOO** [comment]
So I can avoid downloading until later.   This way there are usually several more choices available from multiple sources for any given episode ...... SR then excels at choosing the best of alternatives.     Otherwise it's all too often that a lesser grade quality gets selected .... I'd rather SR wait a while for the better fruit to hang on the tree, as it were .........

**Comment by WebSpider** [comment]
This makes sense for NZB, but not for Torrent, since you would typically integrate better with a torrent provider to choose stuff you like (minseed, minleech, etc)

I think it would be better implemented by using already existing code: Using custom quality settings, setting initial to any, archive to the quality you want, and activating archive first match

**Comment by ThePOO** [comment]
please read my edit  ... and sorry for the extra large type --- the editor did that, not me.
My point was that my method assured both 1080p -and- 720p versions are typically available at the time episodes are evaluated.    At that point SR selects the highest available content at that time ... one download and done.      Worked like magic, until SR was changed.

**Comment by ThePOO** [comment]
And, it makes sense for both NZN and torrent files ...

**Comment by ThePOO** [comment]
NZB .... dang.     rushing here and I'm getting some of the old, get off the computer and help with hanging drapes here ... sigh.

**Comment by fernandog** [comment]
just disable dailysearch for the provider. enabled only backlog search

**Comment by ThePOO** [comment]
The problem is that you can't definitively keep Daily or Backlog from scanning too soon after broadcast and then are likely to get less than desired results.
Currently I accept only searches with results containing 1080p or 720p in their description.   Typically waiting about 4 hours after broadcast time yields a really good result.

My solution, just today, is to restart SR with a batch just after the last broadcast ends for the day.    I have the SR Daily set for 240 (Backlog ends up 720 --- and I don't care about that because I never have any backlogs to download anyway).     23:00 re-start SR.   00:00 Shows update   03:00 SR scans for shows to download.     07:00 another scan    11:00 another scan  ..... and so on ... it works.

But---- I'd rather keep the entire logic inside SR and not have to invent a method to force SR's behavior.

**Comment by ThePOO** [comment]
really have to tend to the drapes ... sorry.

**Comment by fernandog** [comment]
So you are saying backlog search frequency should be relative to airdate not last dailysearcher?

**Comment by ThePOO** [comment]
no, not at all.
Tell ya what, I'll just keep forcing SR to do what I need.     I just love what SR does in selecting the best available quality {honoring my restrictions of "Any", 1080p,720p}, at the time episodes are assessed.     I just needed to make sure WHEN assessments occur are made.     I found a cludgy solution, I'll just stick with that for now.     Thanks anyway.

**Comment by ThePOO** [comment]
the drapes look great.     I have a workable solution for now ..... please close this request.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
