### ISSUE TITLE
[APP SUBMITTED]: Thread-91 :: You tried saving an invalid anime naming config, not saving your naming settings

### ISSUE THREAD

**Issue by kossboss** [SiCKRAGETV/sickrage-issues#2932]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-4.1.7.x86_64.1-x86_64-with-debian-7.9**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@5391476827cf369a2d16a4e7ee8128f47a75f74c
Link to Log: https://gist.github.com/7b30f615d810493d4d39
### ERROR
```
Thread-91 :: You tried saving an invalid anime naming config, not saving your naming settings
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by kossboss** [comment]
Episode Naming For Anime Absolute Only not working

"Add Absolute Number Works" feature works

*Custom Format: s%0Se%0E-%e_n
*Multi-Episode Style: Extend (Limited)
*Single-EP Anime Sample: s02e03-003-ep_name.ext
*Multi-EP Anime sample: s02e03-04-003-004-ep_name.ext

Changing to "Only Absolute Number" shows preview but fails on save with error

I got error notification
Here is error from Logs tab:
* 2015-09-23 13:39:12 Thread-91 :: You tried saving an invalid anime naming config, not saving your naming settings
* 2015-09-23 13:39:12 Thread-91 :: You tried saving an invalid anime naming config, not saving your naming settings

*Custom Format is still: s%0Se%0E-%e_n
*Preview shows this, which is what I want
*Single-EP Anime Sample: 003-ep_name.ext
*Multi-EP Anime sample: 003-004-ep_name.ext

Thanks for the help
- kossboss

**Comment by kossboss** [comment]
My System: I have a ReadyNAS Ultra 4 Running ReadyNAS 6.4.0 Firmware.

**Comment by kossboss** [comment]
You mentioned in my other issue that me running as root is not recommended as it wasnt audited that way. I hope this is not caused by me running at as root :/ I really want to switch to none root, but I cant or it will cause hinderences with my storage devices interface.

**Comment by WebSpider** [comment]
This is not caused by running your system as root, but still it is bad practise :)

As for your issue: Have you tried any other combination, to see if that works?

**Comment by kossboss** [comment]
I tried a few combos I couldnt get it to work. If there was an Absolute Episode number RegEx that would probably make it work as well. I saw someone submitted that in FeatHub. But given the current tools it should still work and not give me an error (I mean its showing me what I want * but its just not doing it), am I right?

what I  want:
*Custom Format is still: s%0Se%0E-%e_n
*Preview shows this, which is what I want
*Single-EP Anime Sample: 003-ep_name.ext
*Multi-EP Anime sample: 003-004-ep_name.ext

**Comment by miigotu** [comment]
@kossboss there is an absolute number regex. We need to get through exposing them in the gui.

There is `%AB` (absolute number) and `%XAB` (xem absolute number). However, the multi-ep example doesnt work in the gui for it, not sure if it would work in practice.

**Comment by miigotu** [comment]
I think I can fix that multi-ep problem

**Comment by miigotu** [comment]
eh, maybe.. that code is a mess

**Comment by kossboss** [comment]
@miigotu Thanks for help. I was able to get this running like so. Do you think this is a good format that will work with rename standards?
![image](https://cloud.githubusercontent.com/assets/2777198/10177513/62a9dde6-66af-11e5-9c9a-10ac8e8a9672.png)
*NOTE TO OTHERS: the rule is %AB_s%0Se%0E-%e_n, the **%AB** is the regex for absolute numbers and **s%0Se%0E** is for the regular season & episode. If we were to do **Add** or **Only** with Absolute number then we would get this regex to **s%0Se%0E** to also or only have absolute numbers, which would be redundant with the **%AB**, so I set the checkbox to "No Absolute Number" (so that it doesnt attach the absolute number to the **s%0Se%0E** regex). Also the Multi Episode style was set to repeat, it just looks best this way (in my opinion)*

**Comment by kossboss** [comment]
i think you can close this, I got it fixed. unless your keeping it open for other reasons.
