### ISSUE TITLE
[Feature Request] Add New Shows that use underscore or dash for spaces

### ISSUE THREAD

**Issue by kossboss** [SiCKRAGETV/sickrage-issues#2933]
---------- Info --------

SR Version:	BRANCH: (master) / COMMIT: (5391476827cf369a2d16a4e7ee8128f47a75f74c) 
SR User:	root
SR Locale:	('en_US', 'UTF-8')
SR Config:	/apps/sickrage/config.ini
SR Database:	/apps/sickrage/sickbeard.db
SR Cache Dir:	/apps/sickrage/cache
SR Log Dir:	/apps/sickrage/Logs
SR Arguments:	['-q', '--daemon', '--nolaunch']
Python Version:	2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]

---------- What is the issue --------

I have folders with TV shows that use _ or - instead of spaces. Infact I prefer that as im a heavy linux user and I hate using backspacing for spaces, it just looks wierd.

So anyhow I have a folder with existing TV Shows /some/folder/tv. I point Add Existing Shows at that folder. It finds all of my Shows there. I.e. Spartacus, Breaking-Bad, etc... Spartacus works as its 1 word and TVDB finds it. However shows with multiple words which I spaced with dashes or underscores like this "Breaking-Bad" are not found via TvDB. So I manually have to go in and change it to "Breaking Bad" & it finds it thru TvDB. All I have to do is manually edit that text field.

Its not too big of a deal, so this would be a low priority feature request. 

Here is a gif of the situation: http://imgur.com/0kX48iU

------- Logs -----

No logs as this is feature request.

**Comment by WebSpider** [comment]
* Please dont run SR as root, we have not audited the code not to behave badly, and you could end up losing control of your system
* This is not too hard to implement, but indeed, low prio. Could be implemented in webserve.py:L2193 (sanitizeFilename)

**Comment by kossboss** [comment]
Sounds good, I will consider that. The only issue is that my ReadyNAS OS creates any other users in the interface, and I dont like the way it looks. So far running as root everything works great. My only issue is just that anime-naming in the other issue & just this feature request. Everything else is flawless.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
