### ISSUE TITLE
[APP SUBMITTED]: Insufficient data to process the guess

### ISSUE THREAD

**Issue by sverleysen** [SiCKRAGETV/sickrage-issues#2936]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5391476827cf369a2d16a4e7ee8128f47a75f74c
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-REFRESH :: 74608: Could not refresh subtitles
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dirkr07** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  4 2015, 00:30:19) [GCC 4.3.2]**
Operating System: **Linux-2.6.32.12-ppc-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@5391476827cf369a2d16a4e7ee8128f47a75f74c
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-REFRESH :: 247897: Could not refresh subtitles
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dirkr07** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  4 2015, 00:30:19) [GCC 4.3.2]**
Operating System: **Linux-2.6.32.12-ppc-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@41dfcaeaf855297d6a478355746d6b769ca8b0da
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-REFRESH :: 247897: Could not refresh subtitles
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by medariox** [comment]
```
ValueError: Insufficient data to process the guess
```
Means that your episode file name is missing some parameters that are required by GuessIt to determine its properties. Make sure that the files have both season and episode number in the name.
Same issue as here: https://github.com/SiCKRAGETV/sickrage-issues/issues/2950#issuecomment-143417245

**Comment by DeFropi** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-43-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@41dfcaeaf855297d6a478355746d6b769ca8b0da
Link to Log: https://gist.github.com/f0f09508327261104d41
### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "/home/defropi/.sickrage/sickbeard/tv.py", line 1460, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/home/defropi/.sickrage/sickbeard/tv.py", line 1438, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/home/defropi/.sickrage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/home/defropi/.sickrage/lib/subliminal/video.py", line 203, in scan_video
    video = Video.fromguess(path, guessit.guess_file_info(path))
  File "/home/defropi/.sickrage/lib/subliminal/video.py", line 65, in fromguess
    return Episode.fromguess(name, guess)
  File "/home/defropi/.sickrage/lib/subliminal/video.py", line 114, in fromguess
    raise ValueError('Insufficient data to process the guess')
ValueError: Insufficient data to process the guess

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Inervo** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 23:30:53) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@f913285d1decce196c6054c43507582fb2a2a7ee
Link to Log: https://gist.github.com/e951831ddaa759c10e99
### ERROR
```
Thread-15 :: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/tv.py", line 1472, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/tv.py", line 1446, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/usr/local/sickrage/var/SickRage/lib/subliminal/video.py", line 203, in scan_video
    video = Video.fromguess(path, guessit.guess_file_info(path))
  File "/usr/local/sickrage/var/SickRage/lib/subliminal/video.py", line 65, in fromguess
    return Episode.fromguess(name, guess)
  File "/usr/local/sickrage/var/SickRage/lib/subliminal/video.py", line 114, in fromguess
    raise ValueError('Insufficient data to process the guess')
ValueError: Insufficient data to process the guess

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by oconnellkj** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@5aac5803f2e1df3385a5cb19580b8fd6b4eb6191
No Log available with ERRORS: 
### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\tv.py", line 1472, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "C:\SickRage\sickbeard\tv.py", line 1446, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "C:\SickRage\sickbeard\subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "C:\SickRage\lib\subliminal\video.py", line 203, in scan_video
    video = Video.fromguess(path, guessit.guess_file_info(path))
  File "C:\SickRage\lib\subliminal\video.py", line 65, in fromguess
    return Episode.fromguess(name, guess)
  File "C:\SickRage\lib\subliminal\video.py", line 114, in fromguess
    raise ValueError('Insufficient data to process the guess')
ValueError: Insufficient data to process the guess

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by medariox** [comment]
@miigotu 
This can be closed, as we do not use pass the video_path to GuessIt anymore.
