### ISSUE TITLE
Cannot restore after update

### ISSUE THREAD

**Issue by MikeyMan83** [SiCKRAGETV/sickrage-issues#2937]
Hello, 

After some update issues, i've deleted and installed the whole sicrage package on my synology.
Before i dit this, i created a backup.

Now after installation i'm trying to restore, and get the following message:

Successfully extracted restore files to /usr/local/sickbeard-custom/var/restore
Restart sickrage to complete the restore.

however, there is no restore folder in the /usr/local/sickbeard-custom/var/ dir.
Also, nothing happens after restart.

Anyone can help me?

**Comment by MikeyMan83** [comment]
Manually extracted the file to /usr/local/sickbeard-custom/var/restore , no luck.

**Comment by MikeyMan83** [comment]
Got a little further, after placing the files in the restore folder; i get a lot of permission denied errors.

**Comment by miigotu** [comment]
sickbeard-custom is the wrong package. There is a SickRage package.

**Comment by MikeyMan83** [comment]
I see that now... Always had the Sickbeard custom working until now.
I'll install the sickrage package and try to restore.

**Comment by MikeyMan83** [comment]
Just installed and tried to restore, still no luck.
I certainly hope i don't have to make all my settings again :-1:

**Comment by miigotu** [comment]
your settings are there, look at the port SR is running on....

**Comment by MikeyMan83** [comment]
I saw that, SR is now running at 8899, but all my settings are empty.

**Comment by miigotu** [comment]
stop SR, copy config.INI and sickbeard.db from the backup to /usr/local/SickRage/var/

**Comment by MikeyMan83** [comment]
Had to change the port number in config.ini, but seems to work! That might be something to fix in the restore functionality?
Hope i can use the backup and restore from now.

**Comment by fernandog** [comment]
@neoatomic 
why SR is extracting to /usr/local/sickbeard-custom/var/ instead of /usr/local/SickRage/var/

do you have this issue?

**Comment by fernandog** [comment]
@MikeyMan83  please send a screen shot of you localhost:8081/config page please

**Comment by MikeyMan83** [comment]
It is working now, i have changed to the Sickrage package, and manually restored the dbases.
More trouble than i expected, but no issue now.

**Comment by neoatomic** [comment]
@fernandog You can install sickrage with 2 different packages on the Synology.
sickbeard-custom is the old package/way where you manually need to enter the repo and install python etc.. The new sickrage package does all that automatically. But both work fine.

@MikeyMan83 Both packages use a different port. And if you restored the old config.ini you also have your old port back.

The restore doesn't work anymore, since you added the cache folder to it, at least for me. Probably something to do with the build of the installation package/jail.
With the old way of just using the config.ini and sickbeard.db worked without problems.

**Comment by MikeyMan83** [comment]
Don't know if it makes sense, but with the old port in the ini, i couldn't access SB.

Will the restore function be fixed? Otherwise might as well remove it?

**Comment by neoatomic** [comment]
@MikeyMan83 That indeed doesn't make sense. You probbebly forgot to shutdown SR wile overwriting.?

My comments about the restore (not working for Syno users) where not directed at you.

**Comment by MikeyMan83** [comment]
Not really keen on trying again, but i did have SR shut down during the process... Even restarted several times. Only when i changed the port in the ini, i could gain access.

**Comment by fernandog** [comment]
Check the port in the backup config.ini
Maybe you backup has a old setting when you changed port

**Comment by fernandog** [comment]
Also waiting the screebshot

**Comment by MikeyMan83** [comment]
Which screenshot would you like? It's working fine now? 

I've got nothing configured on port 8081 on my pc or synology

**Comment by fernandog** [comment]
@MikeyMan83 

https://github.com/SiCKRAGETV/sickrage-issues/issues/2937#issuecomment-142915711

**Comment by MikeyMan83** [comment]
@fernandog please read my comments: i have nothing installed on port 8081 on my PC or my Synology.
- Sickbeard-Custom was installed on port 8083, but is now deleted.
- The sickrage package now listens to 8899, but is working fine now.

I for the life of me can't figure out how i can help you?

**Comment by fernandog** [comment]
Does not matter the port!! But the content of the page

Please send a screen shot of you localhost:xxxx/config page please

**Comment by MikeyMan83** [comment]
![sickrage](https://cloud.githubusercontent.com/assets/6270724/10078129/b36abdce-62e3-11e5-9a21-3a5810051502.png)

**Comment by fernandog** [comment]
@neoatomic cache folder is correct. Restore should work. What error do you get?

**Comment by neoatomic** [comment]
No errors, if i recall correct a backup folder is created but the files are not restored from there.
I have explained that in length in the past, so there should be an issue about that. 
Will see if i can dig that up tomorrow.

**Comment by miigotu** [comment]
cache doesn't need to be backed up, and should not be.

**Comment by miigotu** [comment]
maybe cache/images but nothing more

**Comment by neoatomic** [comment]
@miigotu Agree with that. 
Opped at the time to not include the cache folder or make it so users can manually check those folders to be included.

Personally i only want sickbeard.db/config.ini/failed.db thats it. And maybe an manual check-box option to add cache/images and cache/rss 
(The reason for images where the manually added tvrage banners, but those are not needed anymore. :P)

**Comment by fernandog** [comment]
We first need to know WHY it does not work for NAS.

**Comment by fernandog** [comment]
Manual backup ok. User can choose.
But auto backup should be everything

**Comment by neoatomic** [comment]
Found them : 
https://github.com/SiCKRAGETV/sickrage-issues/issues/665#issuecomment-75037587
https://github.com/SiCKRAGETV/sickrage-issues/issues/243#issuecomment-68358137
https://github.com/SiCKRAGETV/sickrage-issues/issues?utf8=%E2%9C%93&q=backup+restore+synology

**Comment by miigotu** [comment]
Its not just on nas, I have to guide users on manual restore all the time on windows, linux, qnap, syno, thecus, rpi

**Comment by fernandog** [comment]
It tested in rpi, windows and linux. It working.
Im sure its only NAS

**Comment by fernandog** [comment]
Unless we see some error logs theres no point to change anything. User might doing something wrong

Like the issue about check DB upgrade. Issue wasnt github or db version check but checkversion.

**Comment by miigotu** [comment]
The point of backup is to save the user from losing settings and his show list. Cache items are automatically replaced if they are lost (aside from images, but first refresh fixes that)

1.) Why backup more than you need to
2.) Why backup cache if it causes issues and is unnecessary. It just complicates things for no reason.

**Comment by miigotu** [comment]
Honestly, I think the problem is the zip64 extensions, which are only necessary because the cache can become too large to backup without zip64.

**Comment by fernandog** [comment]
We had lot of complains about images not being in the backup

**Comment by miigotu** [comment]
Found what I think is the bug. Will post once I run blame on it.

**Comment by miigotu** [comment]
abeloin did it! lol

**Comment by MikeyMan83** [comment]
Did i see correctly that this is already in the master branch?

I'm willing to try out....

**Comment by miigotu** [comment]
yes, I hotfixed to both

**Comment by MikeyMan83** [comment]
Just tried it. Backup ==> remove package ==> install package ==> Restore

Working like a charm!

**Comment by fernandog** [comment]
thanks @miigotu!
