### ISSUE TITLE
home.mako progressbar total?

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2938]
If everyone's okay with it can we make the `progressbar` on home.mako use the total minus the skipped episodes, I've got a few shows with the first 10 seasons marked as skipped and the skipped episodes are added to the total meaning it shows up as only 5% instead of close to 90%.

@SiCKRAGETV/moderators

**Comment by miigotu** [comment]
I guess you should mark the episodes as ignored instead of skipped. There is  difference.

**Comment by OmgImAlexis** [comment]
The progressbar should only show the total of the episodes it's going to download though, no?

**Comment by fernandog** [comment]
@OmgImAlexis see this:

https://github.com/SiCKRAGETV/sickrage-issues/wiki/Episode-Status

**Comment by OmgImAlexis** [comment]
Well out of the "is not wanted for download", is that progressbar not for the downloads though? If it's not wanted for download then why would it matter on the progressbar? That should be just for the ones you want.

**Comment by fernandog** [comment]
we can change that text. it's really old.
but what matter is skipped is included in total episode count as miigotu said

**Comment by OmgImAlexis** [comment]
Well if we are changing it I vote to have that exclude the skipped count, in my mind that count should only be episodes that are downloaded out of the episodes we want downloaded. Skipped and ignored episodes shouldn't be counted at all for the progressbar.

**Comment by miigotu** [comment]
then what is the point of having skipped and ignored status?

**Comment by fernandog** [comment]
@OmgImAlexis 
You should use IGNORED not SKIPPED.

**Comment by OmgImAlexis** [comment]
Well what's the difference between the two? They both sound exactly the same.

**Comment by fernandog** [comment]
No. ignored = you don't want at all. skipped, as it says, it was skipped and you will want in the future

**Comment by miigotu** [comment]
ignored also in case you have it on backup media...

TBH I dont think it makes too much sense to have both, it does cause confusion.

**Comment by fernandog** [comment]
its a BIG change. users use this status since sickbeard. if you want to change we should ask users first as what happens with the status in user's db if we remove it?
I think its not worth the trouble.

**Comment by miigotu** [comment]
The status would be converted to the other one.

The discrepancy here is that usually you want the total to be the total of all existing episodes for that show, but you also want to know how many you have vs how many you want (ie: how many wanted are missing vs how many missing total)

It should not be changed until we can figure out a good way to retain all of this information with only one status

**Comment by OmgImAlexis** [comment]
Closing this for now until we workout what we're doing.
