### ISSUE TITLE
[Feature Request] Add soupbit.me support

### ISSUE THREAD

**Issue by hassanm12** [SiCKRAGETV/sickrage-issues#2939]
It's basically a mirror of bitsoup but allows people in the UK to access it without a proxy.

**Comment by hassanm12** [comment]
[Feature request{

**Comment by neoatomic** [comment]
No point in adding mirrors. Use a proxy/vpn or other to access bitsoup.
Also there is already an feature request to enable users to change the URL for the provider. That would solve this.
