### ISSUE TITLE
New To SickRage Getting few errors i cannot seem to solve

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [SiCKRAGETV/sickrage-issues#2940]
i have migrated from sickbeard.

first of all i am only getting this error with ThePirateBay:

2015-09-24 21:23:05 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Connection error to getURL https://thepiratebay.gd/tv/latest/ Error: error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)

i have read this: https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors

and have installed latest python 2 & 3 PKG from python site
my OS is Mac OS
i have installed openSSL via homebrew and properly set the paths and Symlinks
OpenSSL 1.0.2d 9 Jul 2015
Python 2.7.10

Modules Installed:
PyOpenSSL
PyCrypto
Mako

not sure if it is my issue or a TPB issue..

also when sickrage sends a NZB to SAB they always show up like this instead of the Name Of the episode: http://puu.sh/kmnfd.png i noticed it grabbed these via binsearch.

**Comment by neoatomic** [comment]
If you have correctly installed PyOpenSSL & PyCrypto you shouldn't get any SSL errors. (so i doubt its correct...)
Mako is not needed.

If you dont get those setup correctly, you can try. : 
Go to Setting --> General --> Advanced Settings ---> Disable Verify SSL Certs

**Comment by XxUnkn0wnxX** [comment]
still getting same issue with toggling Verify SSL Certs off & i re-isntalled and Re-Linked Python and OpenSSL via homebrew 

also using NZBtoMedia with sickrage and i keep getting this:

[WARNING]::MAIN: Failed to locate 7zip. Transcosing of disk images and extraction of .7z files will not be possible!

i have p7zip installed and when i do which 7z it show: /usr/local/bin/7z
but i cannot find anywhere in autoProcessMedia.cfg that refers to 7z Path to place /usr/local/bin/

like i did with: ffmpeg_path = /usr/local/bin/

**Comment by neoatomic** [comment]
Well its clearly an SSL error, meaning you have not installed it correctly or TPB is blocked/you are using a proxy.
Sure you are not using an old sickrage version.? Cant think of any other reason. (except if you modified code yourself...)

Concerning NZBtoMedia i cant tell, best to ask how to solve that at there repository.

**Comment by XxUnkn0wnxX** [comment]
well i ran a test coz all my system stuff is in /usr/bin so i did:
sudo ln -sf /usr/local/bin/openssl /usr/bin/openssl
sudo ln -sf /usr/local/bin/c_rehash /usr/bin/c_rehash

and temporary replaced the system openssl with the one from homebrew ver 1.0.2d and i still got TPB error.

i don't like messing in usr/bin as that's apple defaults.. the next thing i was willing to do is find the openssl path in the Sickrage files and replace it there with the 1.02 path but haven't found much luck finding that.

**Comment by neoatomic** [comment]
Its not worth messing up your installation for this. Just disable TPB and pick another like RAGRB or Kickass ect.

**Comment by XxUnkn0wnxX** [comment]
i think i fixed it or it at optimal point.. i had to many python installs so when sickRage ran from the Sickbeard.py #!/usr/bin/env python2.7 it was pointing to another install not the homebrew one with pyopenssl installed

after some reading the "#!/usr/bin/env" refers to using the user's path? the ENV? / as in grabs the first matching excitable found in the .bash_profile or the /etc/paths which i have set to /usr/local/bin with all the symlinks to hombrew Celler

and when i do which python & python2.7 it points to the Hombrew one
