### ISSUE TITLE
Possibility to preserve 264 handle during post rename

### ISSUE THREAD

**Issue by Drempelaar** [SiCKRAGETV/sickrage-issues#2941]
It would be nice to see the possibility to rename files with the x/h 264 handle in the filename as it is required for proper quality detection by sickrage. When searching in the post processing menu the 264 handle can not be selected in the custom rename option. 

So far I could test only when using %RN the x264 handle is preserved

<img width="979" alt="screen shot 2015-09-24 at 13 38 32" src="https://cloud.githubusercontent.com/assets/14020815/10072422/d095fa16-62c1-11e5-83a0-572dbf47e8cd.png">

related: https://github.com/SiCKRAGETV/sickrage-issues/issues/2923

**Comment by fernandog** [comment]
i think it's an issue, isn't?

**Comment by miigotu** [comment]
"as it is required for proper quality detection by sickrage"

It is not required to properly detect the quality anymore afaik.

**Comment by fernandog** [comment]
But it is needed to detect HDTV as we are always saying to users. Isnt?

**Comment by miigotu** [comment]
not anymore since I use hachoir to detect screen size and source. just needs bluray if its bluray and webdl if its webdl. size isn't even needed in filename anymore.

**Comment by fernandog** [comment]
I see. Thanks.
My first issue to sickbeard years ago was that nzb was not being downloaded because there was not code info. Some uploaders still dont add code.

**Comment by fernandog** [comment]
Lol
http://sickbeard.com/forums/viewtopic.php?f=4&t=7119

**Comment by miigotu** [comment]
for search/download it matters, just not for existing files we can scan, and for rescanning in your library.

**Comment by Drempelaar** [comment]
Right so the ticket I referred to is still an issue?

**Comment by miigotu** [comment]
@Drempelaar Nope, for existing files they will get detected correctly now without codec.

**Comment by miigotu** [comment]
Since the other added feature of detecting quality correctly this is no longer causing any issues and is merely cosmetic now, I'm classing it a FR.

Please add it to [![Feature Requests](https://cloud.githubusercontent.com/assets/390379/10127973/045b3a96-6560-11e5-9b20-31a2032956b2.png)](http://feathub.com/SiCKRAGETV/SickRage)
