### ISSUE TITLE
JS issue: View logs / Search lot not working

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#2942]
@OmgImAlexis @MGaetan89 

when searching or filtering URL its:

localhost:8001/errorlogs/viewlog/$%7BsbRoot%7D/errorlogs/viewlog/?minLevel=5&logFilter=<NONE>&logSearch=1080p

but should be

localhost:8081/errorlogs/viewlog/?minLevel=5&logFilter=<NONE>&logSearch=1080p

SR Version:	BRANCH: (develop) / COMMIT: (e1dd04f20537d625e0fb4aebfa8c7cd5d94f8a18) 
SR User:	osmc
SR Locale:	('pt_BR', 'UTF-8')
SR Config:	/home/osmc/SickRage/config.ini
SR Database:	/home/osmc/SickRage/sickbeard.db
SR Cache Dir:	/home/osmc/SickRage/cache
SR Log Dir:	/home/osmc/SickRage/Logs
SR Arguments:	['-q', '--daemon', '--nolaunch']
Python Version:	2.7.9 (default, Mar 1 2015, 13:48:22) [GCC 4.9.2]

**Comment by OmgImAlexis** [comment]
That'd be my fault. Where is that?

**Comment by fernandog** [comment]
menu viewlogs

**Comment by OmgImAlexis** [comment]
Is this in develop or master?

**Comment by fernandog** [comment]
sorry!
always develop =)

**Comment by fernandog** [comment]
thanks!

**Comment by fernandog** [comment]
@OmgImAlexis issue persist

AA
AAAttributeError: 'ErrorLogs' object has no attribute 'viewlog/${sbRoot}/errorlogs/viewlog'
AA    method = getattr(self, route)
AA  File "/home/osmc/SickRage/sickbeard/webserve.py", line 257, in get

this is the same error from history page changing limit.
maybe that PR about JS should be reverted.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/2928

**Comment by OmgImAlexis** [comment]
@fernandog that doesn't sound like a js issue.

**Comment by fernandog** [comment]
but JS that loads the URL that webserve reads isnt?

**Comment by OmgImAlexis** [comment]
Let me know how to reproduce it and what page it's on and I'll have a look but honestly that looks like a python issue from the limited details you gave.

**Comment by OmgImAlexis** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/2587

**Comment by fernandog** [comment]
You only need to check logs and input something in the search log input field. Page does not load. Search does not work.
