### ISSUE TITLE
AttributeError: 'module' object has no attribute 'USE_IMDB_POPULAR'

### ISSUE THREAD

**Issue by tutti21** [SiCKRAGETV/sickrage-issues#2943]
SR Version: 	BRANCH: (master) / COMMIT: (5391476827cf369a2d16a4e7ee8128f47a75f74c) 
Python Version:	2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]
FreeNAS 9.3

pressing add show and a error occurs
press add show and add a show? :)

Error !
AttributeError: 'module' object has no attribute 'USE_IMDB_POPULAR'
% endif <a href="${sbRoot}/home/addShows/popularShows/" id="btnNewShow" class="btn btn-large"> <div class="button"><div class="icon-addtrendingshow"></div></div> <div class="buttontext"> <h3>View Popular Shows</h3> <p>View IMDB's list of the most popular shows. This feature uses IMDB's MOVIEMeter algorithm to identify popular TV Series.</p> </div> </a>
/usr/pbi/sickrage-amd64/share/sickrage/SickRage/gui/slick/views/home_addShows.mako, line 47:
<div class="button"><div class="icon-addtrendingshow"></div></div>
/usr/pbi/sickrage-amd64/share/sickrage/SickRage/gui/slick/views/layouts/main.mako, line 220:
/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/mako/runtime.py, line 853:
callable_(context, *args, **kwargs)

someone stated to delete the cache/mako folder

but I'm not so good with freebsd what do I need to do?

root@sickrage_1:/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/mako # ls   
__init__.py     cache.pyc       exceptions.pyc  lookup.pyc      runtime.py      
__init__.pyc    cmd.py          ext             parsetree.py    runtime.pyc     
_ast_util.py    codegen.py      filters.py      parsetree.pyc   template.py     
_ast_util.pyc   codegen.pyc     filters.pyc     pygen.py        template.pyc    
ast.py          compat.py       lexer.py        pygen.pyc       util.py         
ast.pyc         compat.pyc      lexer.pyc       pyparser.py     util.pyc        
cache.py        exceptions.py   lookup.py       pyparser.pyc                    

here perhaps?

or here root@sickrage_1:/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/cachecontrol
                                                                      
__init__.py             compat.py               patch_requests.py               
__init__.pyc            compat.pyc              serialize.py                    
adapter.py              controller.py           serialize.pyc                   
adapter.pyc             controller.pyc          session.py                      
cache.py                filewrapper.py          session.pyc                     
cache.pyc               filewrapper.pyc         wrapper.py                      
caches                  heuristics.py           wrapper.pyc                     
root@sickrage_1:/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/cachecontrol
 # ls caches                                                                    
__init__.py     __init__.pyc    file_cache.py   file_cache.pyc  redis_cache.py  

or is that even my problem?

**Comment by neoatomic** [comment]
Update. Was solved days ago...

**Comment by tutti21** [comment]
So it was fixed but not merged into the master?

**Comment by tutti21** [comment]
Ah, you want me to update? I did today and  right after I got this error so what did I do wrong ?

**Comment by neoatomic** [comment]
@tutti21 Fix was merged 3 days ago into master. So it should work.
https://github.com/SiCKRAGETV/SickRage/commit/90ea5d1d49158312fa310350532de228ae7fdb87

What you can try is to remove the `sessions` & `mako` folder in your Cache folder.
Maybe that is preventing it from working correctly,.
