### ISSUE TITLE
Prevent mp4 files from being snatched

### ISSUE THREAD

**Issue by Drempelaar** [SiCKRAGETV/sickrage-issues#2944]
Is there some way I can prevent mp4 files from being downloaded? I really only want mkv files but somehow mp4 files are sometimes downloaded as well.

**Comment by fernandog** [comment]
Which provider are you using?

**Comment by Drempelaar** [comment]
Usenetcrawler

**Comment by fernandog** [comment]
We cant know the real extension in nzbs. Nzbname is not necessary the video filename

**Comment by Drempelaar** [comment]
would it be a good idea to implement file size criteria and link it to the various qualities?

**Comment by fernandog** [comment]
Already requested. Wont do.
