### ISSUE TITLE
Web interface not loading and missing info in log.

### ISSUE THREAD

**Issue by razlebol** [SiCKRAGETV/sickrage-issues#2945]
I don't have access to the webui anymore and the log don't show much information at all.

Here is the full content of the log after I restart the program

https://gist.github.com/razlebol/b028694310a9f309462e

**Comment by miigotu** [comment]
Have you tried a manual git pull?

**Comment by razlebol** [comment]
Not yet because I'm using a package on thecus. I could try it though.

**Comment by miigotu** [comment]
nope, will be fine. you could also back up your db and INI and rei stall the package.

**Comment by razlebol** [comment]
Well that fixed it.. Now I feel stupid.

Not sure what went wrong. Thank you.

**Comment by razlebol** [comment]
It did break the auto update though. I get this error now.
https://gist.github.com/razlebol/b722d197a44e917f8d92

**Comment by razlebol** [comment]
Had to specify where the git file was and I think it's ok now. Thanks.
