### ISSUE TITLE
Unable to find a download 

### ISSUE THREAD

**Issue by vandrad** [SiCKRAGETV/sickrage-issues#2947]
Branch - master
Commit hash - d227a29e5a88ba91c29c8c5adde7e039a6804243 - (I think)
OS - debian Open media vault - Python 2.7.3

I have not run an update for a long time and decided to do it a few days ago and I was 2k ish commits behind. So I ran the update and since then I am not able to get sickrage to download anything. I tried removing and installing from scratch but that has not changed anything. Not automatically downloading or working with manual search.

I have waited a few days as I thought maybe it was an issue with providers but nothing has changed. It is no longer working for TPB or KAT.

http://pastebin.com/8cgZkHfk

Any advice will be greatly appreciated.

Thank you in advance

**Comment by neoatomic** [comment]
Try to rename/remove the cache folder. See if that helps.
(To re-download the banners/posters do a mass update. Or wait till SR does it itself.)

**Comment by vandrad** [comment]
Thanks for your response. I have renamed the cache folder and cache.db and it has still not made a difference. Do you have any further suggestions? 

Thanks.

**Comment by neoatomic** [comment]
Not with the current information.
See if you can post a full debug log so we can take a look what SR is doing.

**Comment by vandrad** [comment]
This is the whole log due to me trying to do a fresh install. I am sorry that this is not very long but is this what you are looking for.

Thanks

http://pastebin.com/FPrsw8Lv

**Comment by neoatomic** [comment]
It only includes the `SHOWQUEUE-FORCE-UPDATE` witch isn't helpfully. 
Need the daily and backlog search.

**Comment by vandrad** [comment]
ok. I will wait till tomorrow to get the new log unless there is a way to run then before hand?

Thanks.

**Comment by neoatomic** [comment]
manage--> manage search.
But its bedtime for me here. Will see it tomorrow.

**Comment by vandrad** [comment]
Hi, Here are 2 but I reliased that I manually got all the shows so I will most likely have to wait untill the weekend. Didn't think about it. 

Sorry, will do them soon. Thanks again for your help.
http://pastebin.com/jxzfdExN   

http://pastebin.com/YnRVaJtt

**Comment by vandrad** [comment]
Hi neoatomic,

Here is the full debug log after I manually run the daily and backlog searches.

http://pastebin.com/4eQPf47j

Please let me know if you need anything else from me.

Thanks

**Comment by neoatomic** [comment]
@vandrad The logs contain : 
`Last update was too soon, using old cache: 2015-09-24 21:39:14. Updated less then 20 minutes ago`

So Sickrage is not actually searching the TPB, as the time between searches is to quick.
And that prevents me from seeing why noting is snatched...

**Comment by vandrad** [comment]
I just checked the episode search settings and 'Daily search frequency' is set to 40 and 'Backlog search frequency' is set to 720

I just tried to run the backlog search again and the same message appeared. Should I just keep trying or is there a way around this?

On the logs below i did notice one thing which may be a problem.

SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Requested getURL https://thepiratebay.se/tv/latest/ returned status code is 404: Not Found

i tried to ping TPB on my debian box and for the following results
PING thepiratebay.se (199.27.135.242) 56(84) bytes of data.
64 bytes from cf-199-27-135-242.cloudflare.com (199.27.135.242): icmp_req=1 ttl=55 time=230 ms
64 bytes from cf-199-27-135-242.cloudflare.com (199.27.135.242): icmp_req=2 ttl=55 time=229 ms
64 bytes from cf-199-27-135-242.cloudflare.com (199.27.135.242): icmp_req=3 ttl=55 time=234 ms
64 bytes from cf-199-27-135-242.cloudflare.com (199.27.135.242): icmp_req=4 ttl=55 time=229 ms
64 bytes from cf-199-27-135-242.cloudflare.com (199.27.135.242): icmp_req=5 ttl=55 time=235 ms
64 bytes from cf-199-27-135-242.cloudflare.com (199.27.135.242): icmp_req=6 ttl=55 time=234 ms

and I am able to go to that link in my browser on my laptop.

http://pastebin.com/43a4Sxzr 

Thanks.

**Comment by vandrad** [comment]
I just ran 'curl --head https://thepiratebay.se/tv/latest/' and got the following response so it looks like it is working just being redirected with 302.

HTTP/1.1 302 Moved Temporarily
Server: cloudflare-nginx
Date: Tue, 29 Sep 2015 07:10:54 GMT
Content-Type: text/html
Connection: keep-alive
Set-Cookie: __cfduid=d86f5878ed402ea9805fc9914134a2d531443510653; expires=Wed, 28-Sep-16 07:10:53 GMT; path=/; domain=.thepiratebay.se; HttpOnly
Set-Cookie: PHPSESSID=201db0cd8cb8428da6534f4616affee8; path=/; domain=.thepiratebay.se
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: private, max-age=10800, pre-check=10800
Last-Modified: Sun, 01 Feb 2015 10:47:17 GMT
Set-Cookie: language=en_EN; expires=Wed, 28-Sep-2016 07:10:51 GMT; path=/; domain=.thepiratebay.se
Location: https://thepiratebay.gd/tv/latest/
CF-RAY: 22d5deed708902fd-LHR

**Comment by miigotu** [comment]
Known issue, and it is being worked on. Please search (including closed issues) next time before reporting.

**Comment by miigotu** [comment]
Sorry, wrong post comment. Anyways, this is known, and the problem causing it is known. It is also being worked on.

**Comment by vandrad** [comment]
No problem. Thanks for the update. If there is anything I am able to help with or you need further information please let me know.

**Comment by miigotu** [comment]
It has been fixed in develop, although TPB provider is going to be rewritten right now.

I wouls suggest also trying extratorrent and kickass providers, they are working GREAT.

**Comment by vandrad** [comment]
Great thanks miigotu. I don't see extra torrent in the list or providers. Do I need to use a custom provider to use it?

**Comment by miigotu** [comment]
Nope, it is only in develop right now, we added it about 10 hours ago or so.

**Comment by vandrad** [comment]
ok. thanks again.
