### ISSUE TITLE
High CPU load (Sickrage on Synology)

### ISSUE THREAD

**Issue by forza11** [SiCKRAGETV/sickrage-issues#2949]
SR: BRANCH: (master) / COMMIT: (5391476827cf369a2d16a4e7ee8128f47a75f74c) 
DSM 5.2-5592 Update 3

I moved from Sickbeard-Custom to Sickrage about a month ago. Not a migration, i just started from scratch. Ever since I did that the CPU load from my Synology 413j is constantly maxed out, the python process uses everything available (so it seems). 

important to mention:
- No searchers are active
- CPU throttling doesn't make a difference
- By disabling Sickrage while Couchpotato is enabled, the process load returns to normal
- By disabling Couchpotato (other app using python) while Sickrage is enabled, it remains maxed out.

I'm not sure where to look for a cause so any help is welcome.

Log after reboot/update: https://gist.github.com/forza11/ebdfb7d452686a6c9b5f

CPU load from a day
![sickrage](https://cloud.githubusercontent.com/assets/4203947/10084522/2d00b97a-6304-11e5-8500-6ae0983894b3.png)

**Comment by fernandog** [comment]
Do you have subtitles search enabled for all shows? If you do. Disable subtitles for now and report back

**Comment by neoatomic** [comment]
@forza11 Sounds the same as issue https://github.com/SiCKRAGETV/sickrage-issues/issues/2755#issuecomment-141094892
Could you add all the information there, so we have all in one place.?

Do you rename the episodes.? As you have started a new DB the renaming data gets lost, and therefor if the files are not named correctly SR will do a scan of the file itself. You can read more about that in https://github.com/SiCKRAGETV/sickrage-issues/issues/2755#issuecomment-141094892

**Comment by Zipties** [comment]
I have a similar issue on a windows system (quad core xeon) The python process is always at a steady 25%. I do not have subtitles enabled. I do have a few shows with unknown qualities. THey got dropped in a bugged update a few months back.

**Comment by fernandog** [comment]
Not searching:
![not-searching](https://cloud.githubusercontent.com/assets/2620870/10523037/b9a203b6-734e-11e5-9519-0b6c59673233.png)

Searching
![searching](https://cloud.githubusercontent.com/assets/2620870/10523040/bd5ca678-734e-11e5-9806-5e1c0ce90246.png)

**Comment by fernandog** [comment]
@miigotu 

cpu in RPI reaches 167%
only 4 providers in dailysearcher
findpropers enabled
subtitle search disabled
PP enabled

![image](https://cloud.githubusercontent.com/assets/2620870/10938327/519c333a-82e0-11e5-8474-7de0ae1647b5.png)

**Comment by Zipties** [comment]
The issue for me was the post process scanner. It would freeze up scanning a directory and hog CPU resources until the cache was deleted, then do it again.
