### ISSUE TITLE
[APP SUBMITTED]: 79216: Could not refresh subtitles

### ISSUE THREAD

**Issue by francisconora** [SiCKRAGETV/sickrage-issues#2950]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 18:49:44) [GCC 4.6.4]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@5391476827cf369a2d16a4e7ee8128f47a75f74c
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-REFRESH :: 79216: Could not refresh subtitles
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by medariox** [comment]
Most probably you are using a relative path and never downloaded a subtitle for a show, that causes SickRage to ignore the creation of the subtitle folder. The consequence is that the folder is missing and that's why SickRage is complaining. I don't think it is a good idea to suppress the error, so either you create the folder yourself (keeping it empty, if you like) or you just download at least one subtitle for every show while you are using relative paths.

**Comment by NicoLeOca** [comment]
Hi @medariox 
you mentionned it in the other thread about subtitles but I am not really sure to understand what you mean.
I got the same issue as @francisconora 
What do you mean by relative path?
What is the subtitle folder you talk about?
BTW, I confirm that SR downloads subtitles in my case, very well, I must say

**Comment by medariox** [comment]
Go to: Subtitles Settings > Subtitles Search > Subtitle Directory
![directory](https://snapr.pw/i/08c30acc77.png)

What does this setting look like for you?

**Comment by NicoLeOca** [comment]
it's empty as I want the sub to be next to its video

**Comment by medariox** [comment]
Ok, then you have to make sure that every show, for every season, you have set in SickRage has been downloaded at least once or, alternatively, you could create the missing folder yourself.

E.g.: If you have the show Bones, you have to make sure that all season folders are also there and that the permissions are set correctly:
Bones/S01/
Bones/S02/
Bones/S03/
etc.

If you think you have that and it still doesn't work for you, please post a debug log with the mentioned error.

**Comment by NicoLeOca** [comment]
it's wierd! why is that so complicated?
when you have 50 shows..
and what about deleted seasons? You got to keep an empty folder?

**Comment by medariox** [comment]
No, it is just for shows you want to have subtitles for.
Most probably you have a show with a season, which SickRage never downloaded an episode for. You just have to make sure that the season folder of the shows you want are there.

**Comment by NicoLeOca** [comment]
no sure here but the case you describe represents 100% of the situations I face.
SR only downloads subtitles once it detects an episode with no subs.
And an episode is detected by SR only if it is sorted out properly : showname/seasonnumber/

**Comment by medariox** [comment]
@NicoLeOca Not sure what you mean. Just make sure that all the show>season folders exists.

**Comment by NicoLeOca** [comment]
they exist
I found the incriminated files
there are 6 of them and all were downloaded and processed by SR a couple of weeks ago.
Show.Me.A.Hero.Part.*.720p.HDTV.x264-KILLERS

and I got this logs for each of them
https://gist.github.com/943f1981bc8292fbbc53.git

**Comment by NicoLeOca** [comment]
I also checked the rights as well as you suggested
![image](https://cloud.githubusercontent.com/assets/9487685/10116618/9c677228-6439-11e5-9bd4-3d4a961faffa.png)

Since I moved to nzbtomedia, post-process doesn't work anymore; I also tried to see if it could have some sort of influence; that explains the 2 left columns

**Comment by NicoLeOca** [comment]
SR Version:	BRANCH: (master) / COMMIT: (070e1ba55b74f2d5cbf41602c690cdf55fb0576c)

**Comment by NicoLeOca** [comment]
same issue with
BRANCH: (develop) / COMMIT: (535762723ec6572413b9a49f197b6392eb7e0da8)

**Comment by medariox** [comment]
@NicoLeOca 
This is no folder problem of course.
```
raise ValueError('Insufficient data to process the guess')
ValueError: Insufficient data to process the guess
```
Guess it can't properly process the files, because it needs a season and episode. Rename the file like that e.g.: Show.Me.A.Hero.S01E03.720p.HDTV.x264-KILLERS

**Comment by NicoLeOca** [comment]
@medariox 
it seems to have fixed the issue
strangely those episodes were dl by SR

Thank you for your help

**Comment by didyouexpectthat** [comment]
I also have this error flooding my error log.

```
sickrage.log:2015-09-27 22:00:52 DEBUG    FINDSUBTITLES :: 72073: Downloading subtitles for S07E23
sickrage.log:2015-09-27 22:00:52 INFO     FINDSUBTITLES :: Error occurred when downloading subtitles for: /tv/Star Trek - Deep Space 9/s07e23.avi
sickrage.log:2015-09-27 22:00:52 ERROR    FINDSUBTITLES :: Traceback (most recent call last):
sickrage.log:2015-09-27 22:00:52 DEBUG    FINDSUBTITLES :: Downloading subtitles for episode 7x24 of show Star Trek: Deep Space Nine
sickrage.log:2015-09-27 22:00:52 DEBUG    FINDSUBTITLES :: 72073: An object for episode S07E24 didn't exist in the cache, trying to create it
sickrage.log:2015-09-27 22:00:52 DEBUG    FINDSUBTITLES :: 72073: Loading episode details from DB for episode Star Trek: Deep Space Nine S07E24
sickrage.log:2015-09-27 22:00:52 DEBUG    FINDSUBTITLES :: Setter sets location to /tv/Star Trek - Deep Space 9/s07e24.avi
sickrage.log:2015-09-27 22:00:52 DEBUG    FINDSUBTITLES :: Checking if /tv/Star Trek - Deep Space 9/s07e24.nfo exists: True
```

```
        2015-09-27 22:00:52 FINDSUBTITLES :: Traceback (most recent call last):
  File "/usr/share/sickrage/sickbeard/tv.py", line 1460, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/usr/share/sickrage/sickbeard/tv.py", line 1438, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/usr/share/sickrage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/usr/share/sickrage/lib/subliminal/video.py", line 203, in scan_video
    video = Video.fromguess(path, guessit.guess_file_info(path))
  File "/usr/share/sickrage/lib/subliminal/video.py", line 65, in fromguess
    return Episode.fromguess(name, guess)
  File "/usr/share/sickrage/lib/subliminal/video.py", line 114, in fromguess
    raise ValueError('Insufficient data to process the guess')
ValueError: Insufficient data to process the guess
```

I know I use non-scene-standard naming scheme, but didn't used to spam me like it does now.
