### ISSUE TITLE
[Feature Request] Add special episode parsing

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2951]
Simple feature request ,add special episode parsing
This can be acomplished prety easily by using the same method as sonarr (or similiar)
What it does:
Take this release ```Drugs Inc S06 Special Bad Boys HDTV XviD-AFG```
It uses show name and episode name to determine if its the episode whe want ,the if its 
it checks to see if it has a SXX and a SPECIAL tag
if all of the above are met ,its a valid release

Also scene rules about specials:
```
23:29:06 <•_zoggy_> │  Directory Naming:                                                          │
23:29:07 <•_zoggy_> │   - Show.Name.SXXEXX.Episode.title.720p.HDTV.x264-GROUP                     │
23:29:07 <•_zoggy_> │     Episode title is optional                                               │
23:29:07 <•_zoggy_> │     Episode title  is  required  on  some  shows   that  dont  have  SxxExx```

**Comment by WebSpider** [comment]
@duramato I've been looking into Sonarr but unfortunately it's written in a language that's new to me. Do you have any idea where their name parsing is done, so I can have a look at their code?

**Comment by duramato** [comment]
@WebSpider no sorry ,but if  find ill say something

**Comment by duramato** [comment]
@WebSpider ;)
```
23:36:51 <•_zoggy_> https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core.Test/TvTests/EpisodeServiceTests/FindEpisodeByTitleFixture.cs
23:37:28 <•_zoggy_> parses both show.name.title and show.name.s##.special.title`
```

**Comment by thezoggy** [comment]
```
[05:22pm] <@_zoggy_> searching for show (rage id or string) + string 'bad boys'
[05:22pm] <@_zoggy_> you may get 'Drugs Inc S06 Special Bad Boys HDTV XviD-AFG'
[05:22pm] <@_zoggy_> you parse show for starters.. to make sure its safe to continue, then your left with 'S06 Special Bad Boys HDTV XviD-AFG'
[05:23pm] <@_zoggy_> parse out 's## special ' to find what specials exists... then your left with: 'Bad Boys HDTV XviD-AFG'
[05:23pm] <@_zoggy_> parse out ep title, 'Bad Boys' match that against what ep titles you have.. you see its a match, thus thats the ep you want
[05:24pm] <@_zoggy_> you can do things to clean up titles (source/releases) to make it easier to match
```

**Comment by miigotu** [comment]
I think S06E00 would already work. I'm sure it can be improved if it already does work though.

**Comment by duramato** [comment]
@miigotu not sure if that already works ,how does SR know its s06 .afaik it thinks special ep are s00eXX, hence this FR which propuses to include ep name in count

**Comment by miigotu** [comment]
There is a difference between season specials and show specials, S00Exx was the tvrage way of naming specials.

tvdb uses SxxE00, and most specials on providers are named that way. There is nothing preventing specials from being mapped on thexem AFAIK as well.

IMHO, we should support both methods, S00Exx as a show special, and SxxE00 as a season special.

Thus is extremely low priority, as we are in a perpetual bugfix stage for now and refactoring. That is not to say a PR won't be accepted (or incubated) but the main team members have large tasks currently for refactoring and fixing the bugs created or found during that refactoring.

**Comment by duramato** [comment]
@miigotu sr just adds all SxxE00 to the specials season ,correct?

**Comment by thezoggy** [comment]
Tvdb only officially does s00e##, people can add an ep0 but that quickly gets nuked/moved. The scene can release in a few different ways, almost never will it be what tvdb specials are numbered - as usually the tvdb info isnt added until after its released..  But anyways, people try to add specials to xem which won't magically fix sr, and when I pointed out that sonarr handles them without too much fuss (specific scenario mentioned before) it sparked this conversation 

-----Original Message-----

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
