### ISSUE TITLE
Postprocessing stopped working (Auto and manual)

### ISSUE THREAD

**Issue by thesmj** [SiCKRAGETV/sickrage-issues#2952]
Windows version BRANCH: (master) / COMMIT: (070e1ba55b74f2d5cbf41602c690cdf55fb0576c). Python 2.7.10.

As of last night, Sickrage suddenly stopped postprocessing. Even manual PP claims it doesn't see anything to process.

Here is the log I see when trying a manual PP:
```
Postprocessing results
Processing folder D:\TV Torrents\UTFinished
TV_DOWNLOAD_DIR: D:\TV Torrents\UTFinished
PostProcessing Path: D:\TV Torrents\UTFinished
PostProcessing Dirs: [u'Fresh.Off.the.Boat.S02E01.720p.HDTV.X264-DIMENSION', u'Masters.of.Sex.S03E09.720p.HDTV.X264-DIMENSION', u'Masters.of.Sex.S03E11.720p.HDTV.X264-DIMENSION', u'Ray.Donovan.S03E09.720p.HDTV.X264-DIMENSION', u'Rectify.S03E04.720p.HDTV.x264-BATV', u'Rick.and.Morty.S02E08.720p.HDTV.x264-BATV', u'South.Park.S19E02.720p.HDTV.x264-KILLERS', u'The.Big.Bang.Theory.S09E01.720p.HDTV.X264-DIMENSION', u'The.League.S07E03.720p.HDTV.x264-KILLERS', u'Youre.the.Worst.S02E03.720p.HDTV.X264-DIMENSION']
PostProcessing Files: [u'Thumbs.db']
PostProcessing VideoFiles: []
PostProcessing RarContent: []
PostProcessing VideoInRar: []
Processing folder Fresh.Off.the.Boat.S02E01.720p.HDTV.X264-DIMENSION
Fresh.Off.the.Boat.S02E01.720p.HDTV.X264-DIMENSION : No processable items found in folder
Processing folder Masters.of.Sex.S03E09.720p.HDTV.X264-DIMENSION
Masters.of.Sex.S03E09.720p.HDTV.X264-DIMENSION : No processable items found in folder
Processing folder Masters.of.Sex.S03E11.720p.HDTV.X264-DIMENSION
Masters.of.Sex.S03E11.720p.HDTV.X264-DIMENSION : No processable items found in folder
Processing folder Ray.Donovan.S03E09.720p.HDTV.X264-DIMENSION
Ray.Donovan.S03E09.720p.HDTV.X264-DIMENSION : No processable items found in folder
Processing folder Rectify.S03E04.720p.HDTV.x264-BATV
Rectify.S03E04.720p.HDTV.x264-BATV : No processable items found in folder
Processing folder Rick.and.Morty.S02E08.720p.HDTV.x264-BATV
Rick.and.Morty.S02E08.720p.HDTV.x264-BATV : No processable items found in folder
Processing folder South.Park.S19E02.720p.HDTV.x264-KILLERS
South.Park.S19E02.720p.HDTV.x264-KILLERS : No processable items found in folder
Processing folder The.Big.Bang.Theory.S09E01.720p.HDTV.X264-DIMENSION
The.Big.Bang.Theory.S09E01.720p.HDTV.X264-DIMENSION : No processable items found in folder
Processing folder The.League.S07E03.720p.HDTV.x264-KILLERS
The.League.S07E03.720p.HDTV.x264-KILLERS : No processable items found in folder
Processing folder Youre.the.Worst.S02E03.720p.HDTV.X264-DIMENSION
Youre.the.Worst.S02E03.720p.HDTV.X264-DIMENSION : No processable items found in folder
Processing completed
```
There are files (RARs) in all of these folders, and the only thing I have done since it last worked and I first noticed it had stopped working is connect using the ShowsRage app. I doubt would cause these issues, but I thought it would be worth mentioning.

**Comment by thesmj** [comment]
An update: I ran the manual PP in one of the show's download folders (South.Park.S19E02.720p.HDTV.x264-KILLERS) and it was successful. So, it seems as though SR cannot process shows when starting from the parent folder where uTorrent dumps the downloads after finishing.

**Comment by pdid** [comment]
My auto post processing isn't working either. Manual is fine. Running sickrage on a readynas using linux. The log shows no post processing items.

**Comment by OmgImAlexis** [comment]
Same for me, @MGaetan89 did you break auto pp with one of your last PRs?

**Comment by OmgImAlexis** [comment]
@SiCKRAGETV/moderators

**Comment by OmgImAlexis** [comment]
Auto SR doesn't seem to be trying to download anything either, manual searching works but auto hasn't grabbed anything for me since sometime last night. I had about 5 shows in "missed" when I just checked, manually searching worked fine.

**Comment by WebSpider** [comment]
Are your queues full? /home/status ..

-----Original Message-----

**Comment by OmgImAlexis** [comment]
Mine are completely empty.

This has never happened before and I'm almost certain it was because of one of the refactoring PRs that @MGaetan89 had merged.

**Comment by fernandog** [comment]
Can you do a git blame?
Dont use PP

**Comment by OmgImAlexis** [comment]
@fernandog no clue which PR it was, there was quite a few over the last few days.

**Comment by thesmj** [comment]
I just want to reiterate that both auto and manual PP aren't working for me when scanning the downloaded directory. Manual only works if I search in the show's download folder.

So, files get dumped into D:\TV Torrents\UTFinished. Manual\Auto PP can see the folders, but claims to not see anything in them. If I manually scan one of the downloaded show's folders like D:\TV Torrents\UTFinished\South.Park.S19E02.720p.HDTV.x264-KILLERS, the RAR files are seen and processed.

**Comment by MGaetan89** [comment]
I didn't touch the PP, ever. So I don't think I broke it.
I've been focused on the API builder the last few days.

**Comment by miigotu** [comment]
@MGaetan89 I think it's referring to airdates possibly.

**Comment by WebSpider** [comment]
I'm using TorrentToMedia and this continues to work properly, had a bunch of new series starters downloaded overnight

**Comment by thesmj** [comment]
@miigotu  - Wouldn't the episodes not be snatched to begin with if it were an issue of airdates?

**Comment by miigotu** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/2952#issuecomment-143169986

**Comment by thesmj** [comment]
I see. However, snatches have been working just fine for me. It almost seems like it's a problem with the way the post processor traverses folders.

**Comment by miigotu** [comment]
Post processing has also been working for me, so this isnt as simple as it sounds.

**Comment by miigotu** [comment]
Everyone should double check their settings. restores from backup were not working before last night so its also possible an old restore happened due to a `restore` folder that was never processed a LONG time ago.

**Comment by thesmj** [comment]
@miigotu  - I triple-checked all PP and general settings before creating this issue. Everything looks to be correct. Furthermore, all TV shows are marked as "Wanted" as they should be.

**Comment by miigotu** [comment]
Just throwing ideas out here, no clue what is causing it.

**Comment by daveyboy37** [comment]
Just to add to this. I was quite surprised to see this. I have had and am still having a very heavy day with SickRage. I haven't had a failed post process all day.

**Comment by miigotu** [comment]
@thesmj have you verified the folders/files permissions?

**Comment by thesmj** [comment]
@miigotu I can and will as soon as I am able tonight. But, I can't imagine why or how this would have changed at any point without me doing so. And even still, it wouldn't cause the symptoms I'm seeing without preventing both utorrent from reading/writing to the folders and SR from PP anywhere within them.

**Comment by miigotu** [comment]
it might be u torrent that is setting the permissions different. we have to check all possible causes.

**Comment by pdid** [comment]
Just to add a little more info from my setup. I'm using the master branch and use transmission (readynas edition) to download. My auto post process hasn't worked for a few weeks now. I'll go into my NAS settings and make sure everything is up to date. Nothing else has changed.

**Comment by OmgImAlexis** [comment]
@miigotu using master and haven't restored or anything lately, it's all worked fine until about 2 days ago.

**Comment by thesmj** [comment]
@miigotu I checked folder permissions. Everything is how it should be.

**Comment by thesmj** [comment]
And now it seems like snatching has stopped working as well.

**Comment by pdid** [comment]
I've rolled back to an earlier version of Sickrage and everything working as it should now. I'll stick with this version for the time being. Thanks

**Comment by fernandog** [comment]
Which version?

**Comment by duramato** [comment]
I'm also getting a wierd problem with post processing ,but not sure if related 
Only seems to happen to torrent downloads ,sr snatches the torrent ,transmission downloads it and when sr post process it delete the download without moving it to the show location
(Will post logs later)

**Comment by pdid** [comment]
BRANCH: (master) / COMMIT: (3fb81bd65d7710e59d6c89945a3be39d2dbfc386) 

This was restored from I backup I did on the 20th August.

**Comment by thesmj** [comment]
I tried backing up my current config and deleting/reinstalling SR. Then restoring the config. Same issue. No snatching or PP from root TV download folder.

Used shadow copy to roll back to previous versions (over a week's worth). Same issue.

**Comment by thesmj** [comment]
I noticed something interesting - snatching and auto PP still works, but only at ~3:30 AM. And it's only snatching from Torrentleech - the others seem to be ignored.

**Comment by fernandog** [comment]
@miigotu maybe SR its not creating shows cache?

**Comment by OmgImAlexis** [comment]
@fernandog mine seems to pp fine now, it's just auto snatching that's not working.

**Comment by fernandog** [comment]
@thesmj please stop SR. Delete SickRage/Logs folder. Start SR. After 1min or so go to Logs files and search for:
Building internal name for <showname>

**Comment by fernandog** [comment]
Also:
Internal name cache for

**Comment by thesmj** [comment]
@fernandog I did as you asked. I don't see either of those text strings anywhere.

Here's the log after running for several minutes: http://pastebin.com/GVTwMhSu

**Comment by fernandog** [comment]
@thesmj how do you run SR? what's the full command ?

**Comment by thesmj** [comment]
I'm running it as a Windows service using this process:
http://www.htpcguides.com/create-sickrage-windows-system-service-v2/

**Comment by fernandog** [comment]
do you have teamViewer? send it via PM in IRC

**Comment by miigotu** [comment]
It shouldnt build the name cache until the first queue action or search.

**Comment by fernandog** [comment]
disconnected from his PC, no name cache at all. nothing.

**Comment by fernandog** [comment]
@miigotu name cache are created at startup

https://github.com/SiCKRAGETV/SickRage/blob/develop/SickBeard.py#L382

**Comment by miigotu** [comment]
either way, search and pp works here.

**Comment by fernandog** [comment]
@thesmj @pdid stop SR, delete cache.db, start SR. check if PP/snatch is working now

**Comment by fernandog** [comment]
@thesmj do you still have a backup of your cache.db ?

**Comment by thesmj** [comment]
I might. Would that be included in the SR backup .zip?

**Comment by fernandog** [comment]
yes.
did it worked deleting cache.db?

**Comment by thesmj** [comment]
Didn't get a chance to try it. I will in a few hours.

**Comment by thesmj** [comment]
Ok, I shut down SR, deleted the cache.db file, and launched it again. I waited a few minutes and set a few episodes of a show to "Wanted" and waited. 

2015-10-02 20:10:53 INFO     DAILYSEARCHER :: No new released episodes found ...
2015-10-02 20:10:53 INFO     DAILYSEARCHER :: Searching for new released episodes ...
2015-10-02 20:04:18 INFO     SEARCHQUEUE-BACKLOG-295721 :: Beginning backlog search for: [The Muppets]
2015-10-02 20:04:17 INFO     Thread-49 :: Sending backlog for The Muppets season 1 because some eps were set to wanted

I guess it didn't work.

**Comment by fernandog** [comment]
@thesmj try again to find 'Building internal name for' in logs

are you sure there's ep available for this show?

**Comment by thesmj** [comment]
The word "Building" doesn't even show up in the log file. However the cache.db file itself has returned.

Yes, there are two episodes available. I downloaded them manually. We'll see if SR picks them up after they finish.

**Comment by fernandog** [comment]
did you use the logSearch input?

**Comment by thesmj** [comment]
I opened the file in notepad and searched there. However I'm not seeing it in logsearch either.

**Comment by fernandog** [comment]
deleting cache.db should fix it. maybe your log rotated. wait to see it if auto snatch

**Comment by thesmj** [comment]
It would have auto snatched by now. Auto PP isn't picking up the finished downloads either.

So far it's behaving exactly as it had before.

**Comment by fernandog** [comment]
can you try a new install using only your config.ini from actual sickrage?
rename your SickRage folder to SickRage-backup

**Comment by thesmj** [comment]
Sure. Just a moment.

**Comment by thesmj** [comment]
It's launching with the original ini now. Looks like it's building a new internal cache.

So far I've seen this error pop up:
2015-10-02 21:01:00 MAIN :: Check scene exceptions update failed for theTVDB, Unable to get URL: http://thexem.de/map/allNames?origin=tvdb&seasonNumbers=1&language=us

**Comment by fernandog** [comment]
No more details on that error?

**Comment by thesmj** [comment]
Here's part of the log surrounding the error:

2015-10-02 21:01:01 DEBUG    MAIN :: Transaction with 2182 queries executed
2015-10-02 21:01:00 INFO     MAIN :: Updating timezone info with new one: zoneinfo-2015d.tar.gz
2015-10-02 21:01:00 INFO     MAIN :: Building internal name cache for all shows
2015-10-02 21:01:00 DEBUG    MAIN :: Updated scene exceptions
2015-10-02 21:01:00 DEBUG    MAIN :: Transaction with 713 queries executed
2015-10-02 21:01:00 INFO     MAIN :: Checking for scene exception updates for AniDB
AANone
2015-10-02 21:01:00 ERROR    MAIN :: Check scene exceptions update failed for theTVDB, Unable to get URL: http://thexem.de/map/allNames?origin=tvdb&seasonNumbers=1&language=us
2015-10-02 21:01:00 WARNING  MAIN :: Connection error to getURL http://thexem.de/map/allNames?origin=tvdb&seasonNumbers=1&language=us Error: error ('Connection aborted.', error(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2015-10-02 21:00:39 DEBUG    CHECKVERSION :: cur_commit = 4d37c1352e1a27023ffd520a4da8ab0f024333e6, newest_commit = 4d37c1352e1a27023ffd520a4da8ab0f024333e6, num_commits_behind = 0, num_commits_ahead = 0
2015-10-02 21:00:39 DEBUG    CHECKVERSION :: git rev-list --left-right "@{upstream}"...HEAD : returned successful
2015-10-02 21:00:39 DEBUG    CHECKVERSION :: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in c:\SickRage
2015-10-02 21:00:39 DEBUG    CHECKVERSION :: git rev-parse --verify --quiet "@{upstream}" : returned successful
2015-10-02 21:00:39 DEBUG    CHECKVERSION :: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in c:\SickRage
2015-10-02 21:00:39 DEBUG    CHECKVERSION :: git fetch origin : returned successful
2015-10-02 21:00:39 INFO     MAIN :: Checking for XEM scene exception updates for theTVDB
2015-10-02 21:00:38 DEBUG    CHECKVERSION :: Executing git fetch origin with your shell in c:\SickRage
2015-10-02 21:00:38 DEBUG    CHECKVERSION :: git config remote.origin.pushurl https://github.com/******@gmail.com/SickRage.git : returned successful
2015-10-02 21:00:38 DEBUG    CHECKVERSION :: Executing git config remote.origin.pushurl https://github.com/******@gmail.com/SickRage.git with your shell in c:\SickRage
2015-10-02 21:00:38 DEBUG    CHECKVERSION :: git config remote.origin.url https://github.com/SiCKRAGETV/SickRage.git : returned successful
2015-10-02 21:00:38 DEBUG    CHECKVERSION :: Executing git config remote.origin.url https://github.com/SiCKRAGETV/SickRage.git with your shell in c:\SickRage
2015-10-02 21:00:38 DEBUG    CHECKVERSION :: git rev-parse HEAD : returned successful
2015-10-02 21:00:38 DEBUG    CHECKVERSION :: Executing git rev-parse HEAD with your shell in c:\SickRage
2015-10-02 21:00:38 DEBUG    CHECKVERSION :: git symbolic-ref -q HEAD : returned successful
2015-10-02 21:00:38 DEBUG    CHECKVERSION :: Executing git symbolic-ref -q HEAD with your shell in c:\SickRage
2015-10-02 21:00:38 INFO     MAIN :: Checking for scene exception updates for theTVDB
2015-10-02 21:00:38 DEBUG    CHECKVERSION :: Starting new thread: CHECKVERSION
2015-10-02 21:00:38 INFO     TORNADO :: Starting SickRage on http://0.0.0.0:8083/

**Comment by fernandog** [comment]
PP  processed ok? Did you re-added shows?

**Comment by thesmj** [comment]
The shows are loading in now. I'll let you know what happens to PP.

**Comment by thesmj** [comment]
Looks like auto PP is working now.

I just remembered something - I believe it was around the time this issue started I deleted some shows as they had ended. Would it be possible for that to cause corruption somehow?

**Comment by fernandog** [comment]
don't know. will close this then.
