### ISSUE TITLE
[Feature Request] Option to skip mutli episode files

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2953]

**Comment by fernandog** [comment]
The problem is that some shows premier are released S02E01-E02 as uploader dont split into two files. The double episodes. And they could stay forever as missed for you

**Comment by OmgImAlexis** [comment]
Not always, most of the time there's at least 1 other person that has been uploaded the copy in either a lower quality usually 720p which I have in my list of allowed or even better in 1080p. If there was an option to skip the multi episode files it could grab either the 720p or 1080p like normal as it'd just skip this one. Usually I do this manually.

**Comment by fernandog** [comment]
We can request a new column in cache.db - when parsing filename check if is multi.

**Comment by OmgImAlexis** [comment]
Sounds good. Also we'd need to add two options to the gui, "skip multi-episodes" and "prefer single-episodes". Skip would just ignore them and prefer would check if there was a single, if not it'd grab the multi.

**Comment by fernandog** [comment]
Can you add this to DB upgrade issue please?

**Comment by OmgImAlexis** [comment]
Will do.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
