### ISSUE TITLE
[APP SUBMITTED]: unrecognized token: "6box"

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2954]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-28-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@45d9009b88b88ace885ab2fb1135eea06ac2cd54
Link to Log: https://gist.github.com/38c13574862b14a9a064
### ERROR
```
SEARCHQUEUE-MANUAL-250738 :: [6Box] :: DB error: unrecognized token: "6box"
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Its an old bug, you cant add a provider that starts with a number. use `sixbox` and its solved.

**Comment by miigotu** [comment]
I think I can fix this.

**Comment by miigotu** [comment]
boom.
