### ISSUE TITLE
Sickrage On Local Network (and more?)

### ISSUE THREAD

**Issue by sjay1** [SiCKRAGETV/sickrage-issues#2956]
Hi,

Recently my Sickrage installation was reinstalled as a service (which it was not previously) and I am now unable to access SR on my local network, only my computer that it is hosted on.

I am wondering how to set it up so that I can again access it on my local network (and possible even outside my LAN?)

Thanks

**Comment by neoatomic** [comment]
Here you can read more about that. https://github.com/SiCKRAGETV/sickrage-issues/issues/2763

**Comment by sjay1** [comment]
Hi,

I just tried these steps.

At first I thought it was a different issue but I looked.

I made my service a Network Service but it still is not findable on the local network.

Thanks
