### ISSUE TITLE
[APP SUBMITTED]: 403 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'At least one email address must be verified to do that.'}

### ISSUE THREAD

**Issue by Peanut-Afl** [SiCKRAGETV/sickrage-issues#2957]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-Vista-6.0.6002-SP2**
Branch: **master**
Commit: SiCKRAGETV/SickRage@070e1ba55b74f2d5cbf41602c690cdf55fb0576c
Link to Log: https://gist.github.com/41d2771f0010e747b964
### ERROR
```
Thread-59 :: 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
please verify your github email account

**Comment by rh724** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@30435190ef8880901df555bcda0d46902ea81fb5
Link to Log: https://gist.github.com/677a06af2484ac3d663f
### ERROR
```
Thread-281 :: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\logger.py", line 288, in submit_errors
    if report.create_comment(message):
  File "C:\SickRage\lib\github\Issue.py", line 247, in create_comment
    input=post_parameters
  File "C:\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickRage\lib\github\Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 403 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'At least one email address must be verified to do that.'}

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
