### ISSUE TITLE
SR Can't Find A Torrent That Exists

### ISSUE THREAD

**Issue by gmusgrave** [SiCKRAGETV/sickrage-issues#2960]
My track record with bug reports hasn't been great. My reports seem to deeply offend the powers that be, I get slammed, and then the issue is shut down before I can even respond. However, I'll try again. 

**Branch**: master 

**Commit**: 9edd012e9ab013265b3631706e3aea5673146ae4

**OS**: Windows 7 

**Python Version**: 2.7.10

**What I believe went wrong**: a show that airs each weekday has been downloading successfully for days until this morning.

**What I did**: since it didn't download overnight as usual, I went to the "*Backlog Overview*" screen and did a "*Force Backlog*." 

**What happened**: it processed the backlog request, and found no episodes.

**What I expected to happen**: it would find the show and snatch it.

I checked the log file right after seeing that the episode wasn't found (I'm talking about the physical log files, and not the log screen in the GUI), and saw that it had checked all of my search providers, in order, and had not found a match. 

I know that this show appears regularly on KickAssTorrents, so I checked their indexer, and found the episode there.

The log entries for the KickAssTorrents portion of the backlog search were as follows:
> 2015-09-25 08:57:06 INFO     SEARCHQUEUE-BACKLOG-77075 :: [KickAssTorrents] :: Performing episode search for Jeopardy!
> 2015-09-25 08:57:06 DEBUG    SEARCHQUEUE-BACKLOG-77075 :: [KickAssTorrents] :: search_strings = [{'Episode': [u'Jeopardy S2015E161|2015x161 category:tv', u'Jeopardy S2015E161|2015x161 category:tv']}]
> 2015-09-25 08:57:06 DEBUG    SEARCHQUEUE-BACKLOG-77075 :: [KickAssTorrents] :: Search string: https://kat.cr/usearch/Jeopardy+S2015E161%7C2015x161+category%3Atv/?field=seeders&sorder=desc&rss=1
> 2015-09-25 08:57:08 DEBUG    SEARCHQUEUE-BACKLOG-77075 :: [KickAssTorrents] :: Search string: https://kat.cr/usearch/Jeopardy+S2015E161%7C2015x161+category%3Atv/?field=seeders&sorder=desc&rss=1

I copied and pasted the search string URL from the log entries above into my browser, and it returned a match: "*Jeopardy! S2015E161 2015-09-24 mp4 (HDTV 720p)-Vader85*". This is exactly the format all of the previous episodes that have successfully downloaded have been in (only the episode number and date are different). This file was posted to KickAssTorrents at 22:50 on Sep 24. At the time I did this forced backlog check, it had been there for nine hours.

A short time ago (about three hours after the first try), I tried a second forced backlog with exactly the same results. The log entries were identical except for the timestamps. I checked KickAssTorrents, and the torrent still exists. I've now downloaded it manually.

It is entirely possible that this is not a bug, but just my misunderstanding of how the program is supposed to operate. Please understand that this posting is not meant to offend anyone. This is a genuine problem for me, and I am just trying to understand how this works, or how it should work, so please have a little patience.

Thank you.

**Comment by SiCKRAGEB0T** [comment]
Most likely the search provider settings are keeping SR from accepting the torrent as a valid torrent. Have a look at SR > Config > Search Providers > Provider Options to see if you dont have incorrect minseed/minleech etc.

**Comment by WebSpider** [comment]
Most likely the search provider settings are keeping SR from accepting the torrent as a valid torrent. Have a look at SR > Config > Search Providers > Provider Options to see if you dont have incorrect minseed/minleech etc.

**Comment by gmusgrave** [comment]
I have minseed at '5', and I **believe** there were more seeders than this, but I can't swear to it. 

I've now reduced this to '3', and I'll see what happens tomorrow. I'll pay closer attention to the number of seeders when I check this tomorrow. 

Since it has worked perfectly for the past few days, this **is** a possibility. If that turns out to be the problem, I'll post back and close the issue. Thanks!

**Comment by gmusgrave** [comment]
Sorry for the delay in responding, but the one guy who posts Jeopardy! episodes had to go out of town, and Fridays didn't get posted until this morning.

Friday's episode downloaded fine. So while I, unfortunately, don't know how many seeders there were when SickRage checked the torrent, I will assume that **WebSpider** has identified the problem as there being too few seeders. It seems likely, since every other episode has downloaded.

Thank you **WebSpider**. I wouldn't have known to check this setting, and this may help me troubleshoot other issues in future.

I'll now close this issue.

**Comment by gmusgrave** [comment]
It's happened again, searching for the latest episode of the same show, Jeopardy! This is found on KickAssTorrents, and here are the log entries around the failed KickAssTorrents search:

> 2015-10-06 10:41:50 DEBUG    SEARCHQUEUE-BACKLOG-77075 :: [NZBis] :: Search url: http://nzb.is/api?apikey=**********&season=2015&maxage=2&cat=5030%2C5040&q=Jeopardy&limit=100&t=tvsearch&offset=0&ep=168
> 2015-10-06 10:41:51 INFO     SEARCHQUEUE-BACKLOG-77075 :: [KickAssTorrents] :: Performing episode search for Jeopardy!
> 2015-10-06 10:41:52 DEBUG    SEARCHQUEUE-BACKLOG-77075 :: [KickAssTorrents] :: search_strings = [{'Episode': [u'Jeopardy S2015E168|2015x168 category:tv', u'Jeopardy S2015E168|2015x168 category:tv']}]
> 2015-10-06 10:41:52 DEBUG    SEARCHQUEUE-BACKLOG-77075 :: [KickAssTorrents] :: Search string: https://kat.cr/usearch/Jeopardy+S2015E168%7C2015x168+category%3Atv/?field=seeders&sorder=desc&rss=1
> 2015-10-06 10:41:53 DEBUG    SEARCHQUEUE-BACKLOG-77075 :: [KickAssTorrents] :: Search string: **https://kat.cr/usearch/Jeopardy+S2015E168%7C2015x168+category%3Atv/?field=seeders&sorder=desc&rss=1**
> 2015-10-06 10:41:54 INFO     SEARCHQUEUE-BACKLOG-77075 :: [ThePirateBay] :: Performing episode search for Jeopardy!

When I enter the search URL bolded above into a browser it returns: **S2015E168 2015-10-05 mp4 (HDTV 720p)-Vader85**

The minseed parm is not the problem. I have minseed set to 3, and there are currently 48 seeders.

Between the first report and this one, it has successfully downloaded every episode. 

Any other suggestions?

**Comment by miigotu** [comment]
@gmusgrave 
```
        <torrent:seeds>0</torrent:seeds>
        <torrent:peers>0</torrent:peers>
```

**Comment by gmusgrave** [comment]
@miigotu 
That solved it! Thank you!
Can you please explain this to me? I don't understand the minseed setting. If it was set to '3' and there were '48' seeds, why didn't it download? What does this number actually mean?
Thanks again...

**Comment by miigotu** [comment]
There are many reasons a torrent can be skipped, not limited to minseed, quality, and required/ignored words.
