### ISSUE TITLE
TORNADO :: API :: error 18

### ISSUE THREAD

**Issue by MGaetan89** [SiCKRAGETV/sickrage-issues#2961]
[An issue](https://github.com/MGaetan89/ShowsRage/issues/14) has been reported on my application project, but I think it concerns SickRage.
Here is the error:
```
AAKeyError: 18
AA    episode_status_counts_total[status] += 1
AA  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/webapi.py", line 2666, in run
AA    curOutDict = func(curArgs, curKwargs).run()
AA  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/webapi.py", line 205, in call_dispatcher
AA    outDict = _call_dispatcher(args, kwargs)
AA  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/webapi.py", line 135, in get
AATraceback (most recent call last):
TORNADO :: API :: error 18
TORNADO :: API :: show.stats: curKwargs {'indexerid': '76290'}
```

So it concerns the `show.stats` API command, and here is the [corresponding code](https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/webapi.py#L2618-L2666).
From my understanding, the error happens [line 2666](https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/webapi.py#L2666), because `status` does not exist in `episode_status_counts_total` (`status` value in 18?).
`episode_status_counts_total` is initialized [line 2628](https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/webapi.py#L2628).

Now, on which side is the issue. On the initialization (did we forget a status?) or on the increment side (did we forget a case before the final `else`?)?

**Comment by miigotu** [comment]
18 isn't a valid status at all. Maybe someone using it with SB or another fork?

**Comment by MGaetan89** [comment]
I'm not sure if 18 is supposed to be a status. It was more a suggestion.
But according to the original issue, this is happening on SickRage.

**Comment by miigotu** [comment]
standalone status' go up to 12
composite status are all > 100

Seems that a wrong call is being made somewhere or the quality needs split, as the only place I can find 18 as a value is a compund quality, as in for quality settings of a show, which parses into HDTV and FULLHDTV (720p and 1080p HDTV)

```python
>>> import sys
>>> sys.path.insert(1,'lib')
>>> from sickbeard import common
>>> common.Quality.qualityStrings[18]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 18
>>> common.Quality.splitQuality(18)
([2, 16], [])
>>>
```

**Comment by miigotu** [comment]
@MGaetan89 is this still happening with latest develop?

**Comment by MGaetan89** [comment]
@miigotu I am not having this issue. I have to check with the original poster on my project. Was it merge in `master` since you asked?

**Comment by miigotu** [comment]
Ive made a release to master last night.

**Comment by MGaetan89** [comment]
Ok, I will ask for news on my side and give you a feedback as soon as I have an answer.

**Comment by MGaetan89** [comment]
Yes, apparently it is still happening with the latest version.
I have the [`API :: error 6`](https://github.com/SiCKRAGETV/sickrage-issues/issues/2992) issue, but I will change all my `Archived` to see if it fixes it.

**Comment by miigotu** [comment]
6 is a real status, but is not allowed so that makes sense. 18 makes no sense.

**Comment by miigotu** [comment]
18 can only be a show's quality setting, not an episode's status+quality

**Comment by miigotu** [comment]
Api error 6 has been addressed, 18 idk wtf they have going on. Gonna close this for now.

@MGaetan89 you coming back? =P

**Comment by MGaetan89** [comment]
It seems it is fixed in one of the latest SickRage version.
