### ISSUE TITLE
SMB mounts do not show up

### ISSUE THREAD

**Issue by vkehayas** [SiCKRAGETV/sickrage-issues#2963]
Hello,

My transmission setup is working on a local NAS (WD MyBookLive).
While the share where the downloads are placed is accessed by the system that SR runs (Windows 7), the share does not appear in the listed drives in SR.
The network share is SMB and accesible. Restarting SR has no effect.

*Branch*: master
*Commit hash*:41dfcaeaf855297d6a478355746d6b769ca8b0da
*Your operating system and python version*:Windows 7 Pro SP1, Python 2.7.10
*What you did*: Go to 'Post-Processing', Click 'Browse' for 'TV Download Dir' and move all the way up where the mounted disks should be listed.
*What happened*: All local drives appear correctly but none of the mounted SMB network shares.
*What you expected*: For the network shares to appear. This was possible when using junalmeida's SB branch, or through CouchPotato.
*Link to a copy/paste of your logfile with clear debug info of the error on GIST*: Not applicable

**Comment by neoatomic** [comment]
Probably using the windows installer.? Or  running SR as a service.? 
Here you can read more. https://github.com/SiCKRAGETV/sickrage-issues/issues/2763
