### ISSUE TITLE
Show's downloading when set to paused.

### ISSUE THREAD

**Issue by tonedau** [SiCKRAGETV/sickrage-issues#2966]
I have recently moved from Sickbeard to SickRage and the shows that I have paused for downloading are still getting downloaded.  According to the log they are getting manually downloaded and not snatched.  The problem with that is that no-one was at home when the show was supposedly manually downloaded.

Log is here - https://gist.github.com/tonedau/9c909780963c09916617
BRANCH: (master) / COMMIT: (070e1ba55b74f2d5cbf41602c690cdf55fb0576c) 
OS: Windows 10

Can anyone shed any light?

**Comment by neoatomic** [comment]
Pausing a show does stop the downloading not the post-processing. So if SickRage finds an episode in your `tv download dir` it will processes that anyway. How they ended up in your PP folder i cant tell.
(Also if SR downloaded them you should see that in the history.)
