### ISSUE TITLE
Torrent Search Propers getting errors

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [SiCKRAGETV/sickrage-issues#2968]
Branch Is Master
Commit: 41dfcaeaf855297d6a478355746d6b769ca8b0da
Mac Os Yosemite 10.10.5
Python 2.7.10

here is the log:
https://gist.github.com/XxUnkn0wnxX/5811f79c9866b3e7baa2

each time sickrage does a torrent search for PROPERS i get errors as shown in the log and i have especially gotten a few errors such as:
````
ATypeError: __str__ returned non-string (type Error)
AA    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
AA  File "/Users/Admin/Apps/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
AA    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
AA  File "/Users/Admin/Apps/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
AA    body=body, headers=headers)
AA  File "/Users/Admin/Apps/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
AA    timeout=timeout
AA  File "/Users/Admin/Apps/SickRage/lib/requests/adapters.py", line 370, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/Users/Admin/Apps/SickRage/lib/cachecontrol/adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/Users/Admin/Apps/SickRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/Users/Admin/Apps/SickRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/Users/Admin/Apps/SickRage/lib/requests/sessions.py", line 476, in get
AA    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
AA  File "/Users/Admin/Apps/SickRage/sickbeard/helpers.py", line 1621, in getURL
````
as show within the log.

Detailed Debug Log: https://gist.github.com/XxUnkn0wnxX/837f7b833060c3296529

**Comment by OmgImAlexis** [comment]
Again, please use the guide on the issue tracker readme. https://github.com/SiCKRAGETV/sickrage-issues

**Comment by XxUnkn0wnxX** [comment]
i have i have included a log with debugger on & necessary info about my system, Commit & branch + OS

and explained what is happening to the best of my knowledge.

**Comment by OmgImAlexis** [comment]
Okay, that's better.

**Comment by neoatomic** [comment]
Pretty sure this isn't Python 2.7.10. 
Seems u are using  # Python 2.6.?

**Comment by XxUnkn0wnxX** [comment]
ah ya dam just noticed this: ['/usr/bin/python', '/Users/ADMIN/Apps/SickRage/SickBeard.py', '-d', '--nolaunch']

it suppose to be this 
'/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python', '/Users/ADMIN/Apps/SickRage/SickBeard.py', '--nolaunch']

i was using a apple script to run this in the background so i guest it wasn't following my bash path rules..

**Comment by neoatomic** [comment]
@XxUnkn0wnxX There where some improvements made to TPB. See if its fixed now.

**Comment by miigotu** [comment]
It is fixed, since last night. If you still get the error comment back. closing for now.
