### ISSUE TITLE
Post Processing Very Slow On Mac

### ISSUE THREAD

**Issue by eli-jordan** [SiCKRAGETV/sickrage-issues#297]
For some reason shutil.copyfile is very slow on recent versions of MacOS (I believer since OSX Mavericks). This causes post processing of files, i.e. copying them to an external volume, to take excessively long. 

There is an issue pen with sickbeard here https://code.google.com/p/sickbeard/issues/detail?id=2381 for the same issue. I have added the workaround mentioned there, and it makes the post processing significantly faster. I was hoping something like this could be added to the main repo.

in SickRage/sickbeard/helper.py (copyFile function)
e.g.

if isMac() || isLinux()
    os.system('cp "%s" %s"' % (srcDir, destDir))
else if isWindows()
    //something for windows? maybe just the default using shutil.copyfile
else
    ek.ek(shutil.copyfile, srcFile, destFile)

But, I don't know anything about python, so don't know how to do this properly.

**Comment by abeloin** [comment]
@eli-jordan Another alternative, simply use shutil.copyfileobj directly. This way you can specify the buffer size(default 16k) directly.

**Comment by markheloking** [comment]
Closing since it's merged now.
