### ISSUE TITLE
"This show isn't in your list, you need to add it to SB before post-processing an episode"

### ISSUE THREAD

**Issue by samdchuck** [SiCKRAGETV/sickrage-issues#2970]
So Hawaii Five-0 is back and it's still not post processing like last season.
It snatches ok, but post processing pretends it's not in my library.

Log: https://gist.github.com/samdchuck/3e58ca9d7691ec2c19b6
OS: DSM 5.2-5592 Update 4
SR Version: BRANCH: (master) / COMMIT: (41dfcaeaf855297d6a478355746d6b769ca8b0da)
Python Version: 2.7.10 (default, Jun 3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]

**Comment by neoatomic** [comment]
`Hawaii.Five-0` isn't recognized. Check your scene exceptions, and add it.

**Comment by miigotu** [comment]
It is trying to parse `hawaii five 0 2010`, this is the scene exception to add.

**Comment by ruinit** [comment]
was just coming in here to report same issue. Yes if you remove 2010 out of the title it processes fine. Just need to figure out a way to delete the year stamp

**Comment by neoatomic** [comment]
@ruinit If you add a scene exception `hawaii five 0` does it then process with the `2010` in the title.?

**Comment by miigotu** [comment]
have you tried adding the exception: `hawaii five 0 2010`

**Comment by Dohnerd** [comment]
Stripping the year in post processing works.

**Comment by samdchuck** [comment]
Weird could have sword I already did that last season. Any way works now, thanks.

**Comment by ruinit** [comment]
can't get this to work because the date is not in parentheses

Remove the TV show's year when renaming the file?
 
Only applies to shows that have year inside parentheses

**Comment by miigotu** [comment]
3 log lines that just say it failed dont tell me anything. Do you have the scene exception set?

**Comment by ruinit** [comment]
guess when I read scene exception I think of avoid downloads that have 2010 in the filename? Is that not how it works? I added scene exception 2010 do I add the whole name? Hawaii 5 O 2010?

**Comment by ruinit** [comment]
ok apparently you have to add exception like this for it to work. Hawaii.Five-0.2010. Thanks for the help guess I learned something new here.

**Comment by miigotu** [comment]
https://github.com/SiCKRAGETV/sb_tvdb_scene_exceptions/pull/20/files

**Comment by miigotu** [comment]
Just added it to the default exceptions list..

Exceptions mean when the release is not the normal name, there is an exception where it should still match.
