### ISSUE TITLE
I want to fix Libertalia, but I don't know how

### ISSUE THREAD

**Issue by adaur** [SiCKRAGETV/sickrage-issues#2971]
Hi folks,

Libertalia now uses a self-signed SSL certificate (which is a non-sense, but I can't change it :))

So SR complains everytime it tries to reach the login page:

2015-09-26 12:13:40 WARNING  SEARCHQUEUE-MANUAL-248835 :: [Libertalia] :: Connection error to getURL https://libertalia.me/login.php Error: error [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

I know there is a setting to disable SSL checking, but since it has to be disabled to make Libertalia works, it makes more sense to disable it at the provider level.

I tried this but it didn't work:

        disableSSL = {'Verify': False}

        logger.log('Performing authentication to Libertalia', logger.DEBUG)
        response = self.getURL(self.url + '/login.php',  post_data=login_params, params=disableSSL)

What should I do ?

Thanks!

**Comment by OmgImAlexis** [comment]
@adaur any chance you can get in contact with the admin? Wosign does free 1 - 3 year SSL certs.

**Comment by adaur** [comment]
No chance, he claims he is safer with his own certificate (yeah, I think he doesn't know much about security :))

**Comment by OmgImAlexis** [comment]
Well at the moment there's nothing you can do then, either turn on disable check for all certs or live without that site. :disappointed:

**Comment by adaur** [comment]
Are you sure? getURL takes an argument called params, calling the helpers file which takes an other params array:

def getURL(self, url, post_data=None, params=None, timeout=30, json=False):
calls
def getURL(url, post_data=None, params={}, headers={}, timeout=30, session=None, json=False, proxyGlypeProxySSLwarning=None):

    if params and isinstance(params, (list, dict)):
        for param in params:
            if isinstance(params[param], unicode):
                params[param] = params[param].encode('utf-8')

    session.params = params


            resp = session.post(url, data=post_data, timeout=timeout, allow_redirects=True, verify=session.verify)
        else:
            resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)

is there anyway that I can bypass the verify=session.verify ?

**Comment by OmgImAlexis** [comment]
@miigotu

**Comment by miigotu** [comment]
You would have to add parameters to both getURL method definitions

**Comment by adaur** [comment]
Never mind, users will have to disable SSL check.

**Comment by maxcore** [comment]
@adaur where we disable SSL check ?
