### ISSUE TITLE
[Meta] Add Sickrage to feathub

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2972]
@fernandog Please? :heart:

**Comment by fernandog** [comment]
[![Feature Requests](http://feathub.com/SiCKRAGETV/sickrage-issues?format=svg)](http://feathub.com/SiCKRAGETV/sickrage-issues)

**Comment by OmgImAlexis** [comment]
:cry:

**Comment by fernandog** [comment]
Who this works?!
What happens with all FR we already have?

**Comment by OmgImAlexis** [comment]
@miigotu You can answer that.

**Comment by miigotu** [comment]
We will move them all there, and sort them, and close them here (including future ones)

@fernandog I also need you to add the webhook for the SR bot for issues, and to make the bot a moderator (you could add me back to mods too). I have the info for the bot that is running on bot.sickrage.tv

**Comment by OmgImAlexis** [comment]
@fernandog can you please make @miigotu admin or mod so he can redo it using sickrage? It's annoying having to wait for you to get online to do things like this.

**Comment by miigotu** [comment]
http://feathub.com/SiCKRAGETV/sickrage-issues/+2

Have to be owner, its the only way to have those powers. Being an owner cannot hurt the project in any way no matter what happens. Owners cant remove Founders or anything like that -.-.

**Comment by fernandog** [comment]
@echel0n you asked me to not include anyone in SickRage repo. What should we do to make this work?

**Comment by miigotu** [comment]
Ask @echel0n about it directly and explain why. He was on irc and we talked but he hasnt been back since to finish our talks.

**Comment by fernandog** [comment]
```
[![Feature Requests](http://feathub.com/fernandog/SickRage?format=svg)](http://feathub.com/fernandog/SickRage)
```

**Comment by fernandog** [comment]
```
[![Feature Requests](http://feathub.com/SiCKRAGETV/SickRage?format=svg)](http://feathub.com/SiCKRAGETV/SickRage)
```

**Comment by miigotu** [comment]
I think we should write a standard post to every FR on here and close them. Users should add it on feathub if they really want it, after verifying the FR is not on FH yet. This helps us weed out FR that arent important anymore, and prevents us from having to do the work ourselves.

We have switch to using feathub for feature requests. If this feature is still important to anyone, please check that it has not been added and add it [![HERE](http://feathub.com/SiCKRAGETV/SickRage?format=svg)] http://feathub.com/SiCKRAGETV/SickRage)

Make sure to vote!

**Comment by OmgImAlexis** [comment]
If someone wants to write up a post I'll copy and paste it to the 220+ feature requests.
