### ISSUE TITLE
NZBtoMedia Wiki Missing Some Info (Sickbeard API Key missing)

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [SiCKRAGETV/sickrage-issues#2975]
@neoatomic 
well this in regarding to this post here: https://github.com/clinton-hall/nzbToMedia/issues/835

but after reading NZBtoMedia Config file more clearly:

in "nzbToSickBeard.py" it import nzbToMedia so it imports "nzbToMedia.py"

and reading over the config file: ###### SabNZBD (You must edit this if your using nzbToMedia.py with SabNZBD)

i noticed the Wiki Here: https://github.com/SiCKRAGETV/sickrage-issues/wiki/NZBtoMedia#configure-autoprocessmediacfg-for-sabnzbd

has missing info about 
[Nzb]
    ###### clientAgent - Supported clients: sabnzbd, nzbget
    clientAgent = sabnzbd
    ###### SabNZBD (You must edit this if your using nzbToMedia.py with SabNZBD)
    sabnzbd_host = localhost
    sabnzbd_port = 8080
    sabnzbd_apikey = 
    ###### Enter the default path to your default download directory (non-category downloads). this directory is protected by safe_mode.
    default_downloadDirectory = ""

the wiki only refers to the "[SickBeard]" section

i started getting API errors in SabNZB till i configured the "sabnzbd_apikey = " in the "[Nzb]" section.

i suggest this to be included in the Wiki Guide to prevent further posts such as this and to reduce errors.

**Comment by miigotu** [comment]
@neoatomic

**Comment by neoatomic** [comment]
Indeed forgot to add that part. :( (Just added it) 
Thanks for letting me know.

**Comment by XxUnkn0wnxX** [comment]
@neoatomic
i would i also like to mention this:

SABIP:SABPORT/config/switches/
the setting called "Check before download" i use this not to waste time and bandwidth but time to time i get a check that is like 0.0% or 56% of 100% and this stops the download before it even happens so Failed Downloading with NZBtoMedia would fail right? because in order for Sickrage to grab another release the NZBtoMedia script has to be run & this Check kills it.

is there a way to have this check both on and run the post process script even if the download doesnt happen? or a way for sickrage to detect this? i suggest support for something like this be built in.

but for now i would assume i would need to turn of this Check?

**Comment by neoatomic** [comment]
Dont think the script would run in that situation. If that is indeed the case it would be a nice improvement for nzbget. Try opening a ticket/issue on there repo and see what comes out of it.

**Comment by XxUnkn0wnxX** [comment]
i just noticed this: i had the "Post-Process Only Verified Jobs" turned off so the script runs but with "Post-Process Only Verified Jobs" on then it does run the script at all.
