### ISSUE TITLE
[BUG]Wierd Trending shows page

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2976]
The Add trending shows  its completly f. up ,the recommend shows page is as bad but not ok
what im  talking : 
![image](https://cloud.githubusercontent.com/assets/10121067/10120073/b4b2d872-64a2-11e5-9a5a-28c141e72ae6.png)

And (this one its normal to only have 2 ,becouse the other 3 are blacklisted): 
![image](https://cloud.githubusercontent.com/assets/10121067/10120076/e8d403ba-64a2-11e5-8faf-cf71158f800c.png)

**Comment by OmgImAlexis** [comment]
This is a known issue and had a issue open about it, I can't remember what the issue number is but I'm closing this one.

**Comment by duramato** [comment]
@OmgImAlexis Sorry didnt doun any ,if you find it could you like it here please?

**Comment by OmgImAlexis** [comment]
Sure.
