### ISSUE TITLE
[APP SUBMITTED]: Failed Unrar archive stephen.colbert.150923.720p-uav.part01.rar: Unrar: Archive CRC Error

### ISSUE THREAD

**Issue by docwho76** [SiCKRAGETV/sickrage-issues#2977]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@41dfcaeaf855297d6a478355746d6b769ca8b0da
Link to Log: https://gist.github.com/6a5306ceb6cf309762f3
### ERROR
```
POSTPROCESSER :: Failed Unrar archive stephen.colbert.150923.720p-uav.part01.rar: Unrar: Archive CRC Error
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by docwho76** [comment]
There was a PAR2 file, but it didnt have enough redundant blocks to recover. Wouldn't it be better to capture this and automatically mark the download as failed and auto-retry

**Comment by miigotu** [comment]
Feature requests are not allowed on the issue tracker anymore. We are still working on ways of notifying users of this change. For now I will just give you a copy-paste of the notice we have added to all past FR:


We have switched to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
