### ISSUE TITLE
Breakup large mako files into partials

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2978]
In files like `home.mako` we have different sets of layouts that are used depending on the layout it'll be a lot cleaner if all of the layouts were in separate files and in the home file it just included the needed one depending on the layout. We could also move the `inc_*` files into a partials directory and rename them accordingly.

@SiCKRAGETV/moderators

**Comment by WebSpider** [comment]
Will this influence performance ?

**Comment by miigotu** [comment]
Shh, dont add FR tags or ppl will think we can put FR here.

I think we should work on breaking down the larger ones that have nearly dupe code over and over first. providers, notifiers, clients and then the other settings ones that have similar code.

maybe some def blocks like:

notifier_item, provider_item, client_item.

then in the mako:
(include the def)
```
% for _notifier in some_notifiers_list:
    notifier_item(_notifier, some, args, here)
% endif
```

**Comment by OmgImAlexis** [comment]
I think you're right, a mix of partials and defs would really help. The more modular the better for performance and maintenance, it'll even help with merging as people could work on the separate files without bumping into each other.

**Comment by WebSpider** [comment]
As long as we don't make it too complex to develop your own theme by splitting this, it sounds like a good idea.

**Comment by miigotu** [comment]
Breaking it up makes it simpler to develop new themes, because the themes will be able to just use pieces from the original theme without including things they don't need. They will be able to re-use the same sql, js, defs, w/e and when we update those things the new theme wont break.
