### ISSUE TITLE
Archived Custom Quality Setting, Invalid Status Error

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [SiCKRAGETV/sickrage-issues#2979]
OS System: Mac OS Yosemite 10.10.5
Python Version: 2.7.10
Branch: Master
Commit: 41dfcaeaf855297d6a478355746d6b769ca8b0da

now when i Mass or set an individual episode to Archived 720p HDTV, WEB-DL etc it give me Invalid Status Error:

![Image](http://puu.sh/kpLvz.png)
![Image](http://puu.sh/kpLz9.png)

now sadly i cannot include a log as this error doesnt produce an notice or error anywhere in the log.

**Comment by daveyboy37** [comment]
@XxUnkn0wnxX 

Hey. Yeah apparently this a kind of "place holder" for the upcoming feature.
The feature itself isn't added yet.

**Comment by miigotu** [comment]
@daveyboy37 @XxUnkn0wnxX This is fixed already in develop (and should be finished barring any more found bugs)

**Comment by XxUnkn0wnxX** [comment]
ye just noticed changes got transferred to Master... (prefer the stable builds over develop...)
