### ISSUE TITLE
No episode number found

### ISSUE THREAD

**Issue by RadeoSuicide** [SiCKRAGETV/sickrage-issues#2980]
SR Version:	BRANCH: (master) / COMMIT: (41dfcaeaf855297d6a478355746d6b769ca8b0da) 
Python Version:	2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Windows 10

After theTVDB changed MythBusters from season 01, 02 etc to season 2003, 2004 I altered my MythBusters filenames to make sure that I was the same as theTVDB. After doing this, I rescanned mythbusters on Sickrage and it only found half of the seasons on my hard drive. They are all named and filed exactly the same. I have no idea whats causing this. Also since I have no idea where to put specials, i tried to mark the specials manually to downloaded and it wont let me.

https://gist.github.com/RadeoSuicide/c394e5711080350998fb

**Comment by OmgImAlexis** [comment]
?

**Comment by RadeoSuicide** [comment]
sorry i accidently posted blank

**Comment by RadeoSuicide** [comment]
i would post a debug log but i keep getting a mako runtime error

**Comment by OmgImAlexis** [comment]
What mako error? Want to open another issue for that.

**Comment by RadeoSuicide** [comment]
ok

**Comment by fernandog** [comment]
@RadeoSuicide please always use the error submitt button for submit errors

to enable just add github user/pass in SR settings
