### ISSUE TITLE
No episode number found

### ISSUE THREAD

**Issue by RadeoSuicide** [SiCKRAGETV/sickrage-issues#2981]
SR Version: BRANCH: (master) / COMMIT: (41dfcaeaf855297d6a478355746d6b769ca8b0da) 
Python Version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Windows 10

After theTVDB changed MythBusters from season 01, 02 etc to season 2003, 2004 I altered my MythBusters filenames to make sure that I was the same as theTVDB. After doing this, I rescanned mythbusters on Sickrage and it only found half of the seasons on my hard drive. They are all named and filed exactly the same. I have no idea whats causing this. Also since I have no idea where to put specials, i tried to mark the specials manually to downloaded and it wont let me.

https://gist.github.com/RadeoSuicide/c394e5711080350998fb

**Comment by RadeoSuicide** [comment]
Nevermind im an idiot

**Comment by fernandog** [comment]
share your finds so other users can know
