### ISSUE TITLE
Mako runtime error at log - unicode error

### ISSUE THREAD

**Issue by RadeoSuicide** [SiCKRAGETV/sickrage-issues#2982]
SR Version: BRANCH: (master) / COMMIT: (41dfcaeaf855297d6a478355746d6b769ca8b0da) 
Python Version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Windows 10

When trying to load debug logs or leaving the log page open for 10 seconds plus gives me this.
https://gist.github.com/RadeoSuicide/146373348b82d8529b12

**Comment by fernandog** [comment]
@RadeoSuicide again: please use submit error button !

**Comment by RadeoSuicide** [comment]
err ok

**Comment by fernandog** [comment]
I see now. the error is in LOG view. sorry

**Comment by fernandog** [comment]
@RadeoSuicide stop SR, before start SR run: `chcp 65001`

**Comment by RadeoSuicide** [comment]
ok i'll try that

**Comment by RadeoSuicide** [comment]
nope it still produces same error

**Comment by RadeoSuicide** [comment]
any idea about my other issue?

**Comment by fernandog** [comment]
no. that naming is strange. S2015E01 - never saw this. maybe others did

**Comment by fernandog** [comment]
@OmgImAlexis any way to convert loglines variable to unicode? never saw that error. even running chcp 65001

**Comment by OmgImAlexis** [comment]
@fernandog ask @miigotu I'm clueless about the unicode issues.

**Comment by WebSpider** [comment]
I'm not sure, but I think concatenating the empty string in https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/webserve.py#L5006 is the culprit here?

**Comment by miigotu** [comment]
I think it could be here:
https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/webserve.py#L4957

finalData.append("AA" + x)

x is unicode (or should be) and concatenating to a bytes string, so it is implicitly encoded to ascii

**Comment by fernandog** [comment]
I think it's showing a special char for any thread/process in SR (subtitles, PP, search, etc)
$loglines it's all logs lines from SR. could be anything

**Comment by miigotu** [comment]
Everything in the UI is rendered as unicode. It is a backend problem, and a rare one because most of the time the log has no problems diplaying non ascii unicode in the log page.

This supports my theory that it this is only when a traceback has non-ascii

**Comment by fernandog** [comment]
What if user disable print log in CMD?

**Comment by miigotu** [comment]
what? idk how that relates to a gui unicode error.

**Comment by fernandog** [comment]
He is windows 10. He runs SR in console

**Comment by WebSpider** [comment]
@miigotu it wouldnt hurt to wrap the "AA" in unicode, imo. Will PR if you agree.

**Comment by fernandog** [comment]
the AA afaik is how SR kwows there's a traceback
Im 100% sure it's not the AA

**Comment by miigotu** [comment]
@WebSpider yes, it needs to be `finalData.append(u"AA" + x)`

Can you first verify that x is unicode by checking type(x) or repr(x)? (doesnt need to be in pr, just verify what I'm reading about x coming from codecs.open)
