### ISSUE TITLE
[APP SUBMITTED]: 'ascii' codec can't encode character u'\xf3' in position 77: ordinal not in range(128)

### ISSUE THREAD

**Issue by mus6677** [SiCKRAGETV/sickrage-issues#2983]
### INFO
Python Version: **2.7.3 (default, Sep  4 2013, 13:54:56) [GCC 4.6.4 20120731 (prerelease)]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@41dfcaeaf855297d6a478355746d6b769ca8b0da
Link to Log: https://gist.github.com/ed8fce440ec4cc82ef17
### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "/mnt/HD/HD_a2/Share_A/sickbeard/sickbeard/tv.py", line 1460, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/mnt/HD/HD_a2/Share_A/sickbeard/sickbeard/tv.py", line 1438, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/mnt/HD/HD_a2/Share_A/sickbeard/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/mnt/HD/HD_a2/Share_A/sickbeard/lib/subliminal/video.py", line 204, in scan_video
    video.size = os.path.getsize(path)
  File "/usr/local/modules/python27/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 77: ordinal not in range(128)

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@mus6677 

check if user running SR is using UTF-8 locale (specially LC_ALL). you can see the SR user at localhost:xxxx/config

Read here:
https://sickrage.tv/forums/forum/help-support/general-support/12825-ensuring-your-locale-s-are-set-properly-to-avoid-unicode-issues

**Comment by fernandog** [comment]
@miigotu second issue related to subtitles

**Comment by dogeatdog** [comment]
Similar issue appeared in my logs after the latest update as well : 
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 68: ordinal not in range(128)

Possible solution : http://stackoverflow.com/questions/15364266/ascii-codec-cant-encode-character-at-position-ord-not-in-range128

**Comment by neoatomic** [comment]
@mus6677 @dogeatdog There was a fix submitted to maser. Update and see if its solved.
