### ISSUE TITLE
FEATURE REQUEST: Allow to change status of Backlogs in Episode Status Management

### ISSUE THREAD

**Issue by kossboss** [SiCKRAGETV/sickrage-issues#2985]
- Add two more status to query "Backlog: Low Quality" and "Backlog: Wanted"
- From there people can change "Backlog: Low Quality" episodes to something like "Downloaded 1080p" or "Archived" or whichever new status so that the episode doesnt get snatched & downloaded
- From there pepole can change "Backlog: Wanted" episodes to something like "Downloaded 1080p" or "Archived" or whichever new status setting so that the episodes dont get snatched & downloaded.

Why? Currently im having alot of episodes being downloaded which I have in 720p quality, they are being redownloaded as 1080p. Even though on my allowed and prefered qualities are set like this:
http://ram.kossboss.com/wp-content/uploads/2015/09/61ff987f2b787f01dd8ca9f99562caff.png
Maybe im misunderstanding the way it works. Even if I am this feature would still help out alot.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
