### ISSUE TITLE
FEATURE REQUEST: mass update preffered and allowed quality for tv shows

### ISSUE THREAD

**Issue by kossboss** [SiCKRAGETV/sickrage-issues#2986]
- mass update prefered and allowed quality for each tv show
- currently only way is to change each tvshow one by one or you can change several with my trick (see link below)

basically convert the functionality in this link into the sickrage gui:
http://ram.kossboss.com/mass-change-sickbeard-sickrage-qualities-via-sqlite/

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!

**Comment by kossboss** [comment]
Just did that: http://feathub.com/SiCKRAGETV/SickRage/+63
