### ISSUE TITLE
Api Builder - 'subtitles' with given value: '1' could not be parsed into 'bool'

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2988]
On the latest dev if i try to open /apibuilder i get
```
Error !

ApiError: param: 'subtitles' with given value: '1' could not be parsed into 'bool'

<div id="content"> <div class="panel-group" id="commands_list"> % for command in sorted(commands): <% command_id = command.replace('.', '-') help = commands[command]((), {'help': 1}).run() %> <div class="panel panel-default"> <div class="panel-heading">
/home/home/SickRage/sickbeard/webapi.py, line 430:
type) + "'")
/home/home/SickRage/sickbeard/webapi.py, line 383:
default = self._check_param_type(default, key, type)
/home/home/SickRage/sickbeard/webapi.py, line 2065:
False, "bool", [])
/home/home/SickRage/gui/slick/views/apiBuilder.mako, line 98:
<%
/home/home/SickRage/lib/mako/runtime.py, line 853:
callable_(context, *args, **kwargs)
```

**Comment by MGaetan89** [comment]
I just pull latest `develop` and ran it, and the API builder works fine.
Did you try to run one of the command?

**Comment by duramato** [comment]
@MGaetan89 dont know any command out of my now ,i just tryied to see the api builder and got that also cleaned mako cache just to be jure and the same

**Comment by fernandog** [comment]
I don't have this issue but I don't have subtitles enabled
@MGaetan89 do you?

**Comment by fernandog** [comment]
ops. got one error now

@MGaetan89 
Run backlog command:
2015-09-27 17:38:00 TORNADO :: API :: global name 'ARCHIVED' is not defined

**Comment by MGaetan89** [comment]
@fernandog Your error might be because I removed the `ARCHIVED` import, because it was not used when I did the PR: https://github.com/SiCKRAGETV/SickRage/pull/2581/files#diff-357efeabeb6d6921e8196af70c431beb Maybe some other PR used it and that cause the error.

I'm not using subtitles either. But by looking at the code, I guess the error comes from [this line](https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/webapi.py#L2065), because `int(sickbeard.ANIME_DEFAULT)` is probably failing.

**Comment by fernandog** [comment]
miigotu did 2 PR about archived

**Comment by MGaetan89** [comment]
@fernandog I tried the backlog command too, and I don't have any issue. I check the code of `webserve` and `ARCHIVED` is still not used there. Only `Quality. ARCHIVED`.

For @duramato's bug, I will enable subtitles to test it and fix it.

**Comment by miigotu** [comment]
@MGaetan89 Ive fixed the ARCHIVED import in develop.

**Comment by MGaetan89** [comment]
@miigotu Thanks. I will fix the other bug in a moment.

**Comment by MGaetan89** [comment]
Fix in https://github.com/SiCKRAGETV/SickRage/pull/2653

**Comment by MGaetan89** [comment]
Should be fixed in `develop`.
