### ISSUE TITLE
Episode missing from episode list after downloading better quality

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#3]
Branch: Master (tested Develop aswell)
Latest commit: https://github.com/SiCKRAGETV/SickRage/commit/6270f25176768fbc8512aea59df30baa4d526e8e (https://github.com/SiCKRAGETV/SickRage/commit/be0e3ab83666c86f29eb22fc22e1919f117084b7)
OS: Synology DSM 5.1, running Python 2.7.8

Steps I took to reproduce;
1. Download episode of series in "lower" quality (for instance HDTV) outside of SickRage
2. Have this episode properly loaded in SickRage, manually setting it to "Downloaded (HDTV)".
3. Edit the series settings to the following (what I used when I noticed the bug);
.* Initial: HD TV, 720p WEB-DL, 720p BluRay.
.* Replace with: 720p WEB-DL, 720p BluRay.
.* Archive First Match: Yes.
4. Reboot SickRage to make SickRage notice the lower quality and start searching (and downloading) a better quality.
5. Wait until the file has been downloaded and post-processed by SickRage.
6. Go to SickRage main menu, and click on the series you "upgraded" the episode for.

You should now notice that the whole episode is missing from the episode list, asin if episode 1 of series 4 is "upgraded", this whole row would be missing from the episode list.

Debug log: http://pastebin.com/0RBRhbGj

Workaround;
Using "Force Full Update" button makes the episodes reappear, but not showing the quality. It's basically like the script "finds" the files on disk, and then adds them as unknown quality to the episode list.

**Comment by fernandog** [comment]
@Tagforce can you confirm this is really an issue?

**Comment by TagForce** [comment]
@fernandog  I'll have to look at this.

**Comment by fernandog** [comment]
@TagForce it's before that commits that changed the snatch status

**Comment by TagForce** [comment]
@fernandog Seperate issue. It looks like something gets messed up in the db if you manually set an episode to a status and quality, and then force SR to find a better quality.
The only way for it to not display the episode is for it to fail on loading it from the db, or corrupt it in memory while changing it.

**Comment by fernandog** [comment]
@EmielH can you try a new install? Stop SR, Rename you sickbeard.db to sickbeard.bak. also cache.db to cache.bak and cache directory to cache.bak

**Comment by EmielH** [comment]
I'll try! I haven't seen this happen in quite a while, so I'll have to use the reproduction steps that are shown above.

**Comment by fernandog** [comment]
@EmielH let me know when you test it.

**Comment by thebeastygecko** [comment]
Hi, I only downloaded SickRage a few days ago, so my install is relatively fresh, and this has been happening to me as well.

**Comment by fernandog** [comment]
@thebeastygecko please stop SR, edit config.ini and set **skip_removed_files = 1**
please report back

**Comment by thebeastygecko** [comment]
I went to check and skip_removed_files was already set to 1, and yet when shows are updated to better quality the episodes still go missing. Is it possible that this has to do with initial HDTV -> WEB-DL? I have similar quality settings as the OP for this bug report.

Thanks

**Comment by fernandog** [comment]
the HDTV are missing or the web-dl?

**Comment by thebeastygecko** [comment]
The episode is missing once updated by the WEB-DL. And by pattern do you mean Season X/Show - SXXEXX - Episode.ext? Those are the naming rules I have.

**Comment by fernandog** [comment]
PP deletes the lower quality file.

**Comment by thebeastygecko** [comment]
Oh sorry for the confusion: I know that, the issue is that the entry for the episode in the list on sick rage disappears.

**Comment by fernandog** [comment]
@thebeastygecko please send a full log

/SickRage/Logs/sickrage.log 
use pastebin.com
