### ISSUE TITLE
Search timeout - Can't add new shows

### ISSUE THREAD

**Issue by gabryk91** [SiCKRAGETV/sickrage-issues#302]
When I use Add new shows or Add trending shows or Add reccomended shows SB shows the page but without results, sometimes it says something about a searching timeout.

Also the combobox for selecting release language now shows only "en" (FIXED)

A slightly better outcome is obtained by selecting theTVDB instead of all search indexers, in this case at least SB find the show, but then the blu button on the bottom of the page is not enabled, so you can't really add the show.

**Comment by nervling** [comment]
I'm experience this as well. 

SR Version:	BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8) 
python 2.7.3, OS: unRaid

I should add that this always times out for me, and it seems to affect adding an existing show as well because it tries to search tvdb/tvrage for my existing metadata files.

Logs don't seem to have anything interesting, even with debug: 1. Let me know if there is anything else I can provide.

**Comment by jpmurray** [comment]
Adding my voice to this. Although, to the contrary of @markheloking , adding an existing show won'y cut it. I tried with tvrage and tvdb and both of them won't work. I just scourged every log I have, and there is nothing that stands out as special (will be coming back to comment if anything out of the ordinary happens).

BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8) running on a Synology NAS with community's Python package version 2.7.8-11.

**Comment by BKSteve** [comment]
I have the "Add New Show" issue, and it is only related to the fact that I can't get the final "Add Show" button at the bottom of the "Add New Show" page to change.
Following @markheloking advice and creating the directory for the new show in the folder structure (blank/empty folder) and then doing "Add Existing Shows" did in fact enable me to add the new series I wanted. So for me this work around did function.

SR Version: 	BRANCH: (develop) / COMMIT: (8b84e4f4bc6cdebdc605438e9e75d15f1133d65e)
SR Cache Dir:	/usr/local/sickbeard-custom/var/cache
Python Version:	2.7.8 (default, Dec 12 2014, 21:20:40)

**Comment by oliverwoodings** [comment]
Experiencing this too (the disabled close button issue) on develop, fine on master. I also have some random 'aeou' text at the top of the screen, and it looks drastically different to how it does on master.

Screenshot of how it looks to me:
![screen shot 2015-01-05 at 21 11 20](https://cloud.githubusercontent.com/assets/621323/5620012/72a75eb0-951f-11e4-9527-f3cbd648c655.png)

**Comment by markheloking** [comment]
We'll need to wait for @echel0n to return from his vacation.

**Comment by fernandog** [comment]
Can you test it ?
@markheloking @gabryk91 @Jaimar @nervling @jpmurray 

use this file
https://raw.githubusercontent.com/fernandog/SickRage/patch-16/gui/slick/interfaces/default/inc_rootDirs.tmpl

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/286

**Comment by nervling** [comment]
AFAIK, nothing has changed in my setup, but this is working for me now.

**Comment by nervling** [comment]
Sorry false alarm, but I have made a fair amount of progress in finding the cause.

I'm running Unraid, and what I've found is that if sickrage's cache directory is set to be stored on the disk along with the config files, search times out. However, if I store it with the temporary files (these might only exist in RAM/temporary USB stick files, not sure how Unraid does this), things work. Interestingly on the normal sickbeard branch I have cache setup and search works fine. I'm guessing that sickrage/sickbeard handle cacheing differently at least for indexing? Any ideas what the cause may be?

This is may specific to Unraid, not sure. Looks like other people have hit this issue before though https://sickrage.tv/forums/forum/help-support/bug-issue-reports/7236-add-new-show-times-out-and-crashes-sickrage/. I can file a separate bug if these seem unrelated to those more familiar with the code.

**Comment by fernandog** [comment]
you **must** pick the parent folder before click "add"

**Comment by nervling** [comment]
I'm not sure what you mean. I have a parent folder added and what not, the search just times out due to the cache.

**Comment by fernandog** [comment]
@nervling  there's two issues in this issue:
- can't add folders because dir shows as unknown
- timeout

I'm talking about the first one

**Comment by nervling** [comment]
I realize, I'm talking about the second, so your advice didn't make sense
to me :).

**Comment by Rawa** [comment]
Experiencing the exact same issue as @oliverwoodings

**Comment by gabryk91** [comment]
Actually there is another issue here: before when adding a new show I can
choose the subtitles language by the combo box, now the same combo box
shows only "en" and to change language I have to add show, then edit it and
change language (on the edit page the combo box has all languages as was
before)
Il 12/gen/2015 01:44 "Rawa" <notifications@github.com> ha scritto:

**Comment by fernandog** [comment]
@gabryk91 can you please add another issue?

**Comment by fernandog** [comment]
@nervling 

can you check your config.ini the "indexer_timeout = 30" ?
Mine is set to 30.

Are you using proxy server to the indexers?
proxy_setting = 
proxy_indexers =

**Comment by nervling** [comment]
I've tried setting it to 30, didn't help. I am not using a proxy.

**Comment by markheloking** [comment]
This issue is not persisting on the master branch. Switching solved it for me.

**Comment by gabryk91** [comment]
I'm lost. A while ago it was suggested to switch to the develop branch,
because apparently the master would be merged into develop at some point
and the master would be eliminated. Now... what branch should be used?
Il 18/gen/2015 13:24 "markheloking" <notifications@github.com> ha scritto:

**Comment by markheloking** [comment]
Generally: the development branch. The problem is that @echel0n has been away for a few weeks now (since someone said he became a father & needs some personal time). That's why fixes aren't as fast as they used to be, so the last few weeks aren't a really good example for what branch to use.

**Comment by fernandog** [comment]
@gabryk91 can you confirm this timeout is still happening after latest update?

**Comment by gabryk91** [comment]
It happens only if all indexes is selected, if I select tvdb it find the show immediately and then all the procedure is working fine.

**Comment by colinramsay** [comment]
This still seems to happen for me, on both master and develop branches.

**Comment by fernandog** [comment]
FULL logs

**Comment by colinramsay** [comment]
As per other comments, there's nothing in the SickRage logs that sheds any light on what is going on.

**Comment by abeloin** [comment]
@colinramsay If you select TVDB does it work? If not, are using unraid?

**Comment by colinramsay** [comment]
This is on a Raspberry Pi 2 with OSMC. I'm currently on the develop branch and it still doesn't work with just TVDB.

**Comment by abeloin** [comment]
Can you try this url(replace the localhost with your sickrage url:
```
http://localhost:8081/home/addShows/searchIndexersForShowName?search_term=how%20it%27s%20made&lang=en&indexer=1
```

**Comment by colinramsay** [comment]
Right, that's interesting. If I request that, it just spins for eternity. Looking at the Ajax request that normally issues this from the UI, it fails after 20 seconds - which I assume is the jQuery timeout length - and then causes the error message to be shown. The server-side action just continues (seemingly) forever.

**Comment by abeloin** [comment]
Can you try this pull requests: https://github.com/SiCKRAGETV/SickRage/pull/1287 it should resolve your issue.

Ref: Look like same issue as SiCKRAGETV/sickrage-issues#563

**Comment by colinramsay** [comment]
I now get the following in my log:

```
LockFailed: Function not implemented
    raise LockFailed("%s" % e.strerror)
File "/media/bigdaddy/SickRage/lib/lockfile/linklockfile.py", line 34, in acquire
```

**Comment by abeloin** [comment]
Do you get any result from the url?
Like:
```
{"results": [["theTVDB", 1, "http://thetvdb.com/?tab=series&id=", 79485, "How It's Made", "2001-01-06"]], "langid": 7}
```

**Comment by abeloin** [comment]
Forgot to ask, in front of 'LockFailed: Function not implemented' what's the type of log(INFO, DEBUG, ERROR) and does it have a traceback?

**Comment by colinramsay** [comment]
I actually do now, but it's just:

    {"results": [], "langid": 7}

Since the code is now throwing an exception which is caught and swallowed silently:

https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/webserve.py#L2049

Here's more of the log:

http://pastebin.com/a1LUYgaG

**Comment by abeloin** [comment]
Try searching in add show

**Comment by colinramsay** [comment]
Still doesn't work.

**Comment by abeloin** [comment]
Can you try using just tvdb

**Comment by colinramsay** [comment]
Nothing:

http://pastebin.com/5tk1yVTv

**Comment by abeloin** [comment]
Can you try add this commit: https://github.com/abeloin/SickRage/commit/71d5f940c559d56907824051b561ee09a0dd48a8?

**Comment by colinramsay** [comment]
That's got it :smiley:

**Comment by abeloin** [comment]
Sorry, I'm not sure to understand. I would be tempted to read it as "That's it" but it's the "got" that leave me perplex.

**Comment by colinramsay** [comment]
Sorry. That fixed it!

**Comment by abeloin** [comment]
Good. I'm not sure when the PR will be merge into the develop branch but you'll be notified via this thread when it will.

**Comment by colinramsay** [comment]
Cool, thanks for your help.

**Comment by fernandog** [comment]
@abeloin will this PR be added to develop too?

**Comment by abeloin** [comment]
Pull request was merge earlier: https://github.com/SiCKRAGETV/SickRage/pull/1287

**Comment by fernandog** [comment]
@gabryk91 develop updated. please test and report back

**Comment by colinramsay** [comment]
Fixed for me on latest `develop`.
