### ISSUE TITLE
displayShow.mako, line 479

### ISSUE THREAD

**Issue by cocker80** [SiCKRAGETV/sickrage-issues#3026]
Hi,
When clicking on any of my shows i get the following error ...
```
Error !

MemoryError:

</td> <td class="col-name]"> % if epResult['location']: <% filename = epResult['location'] for rootDir in sickbeard.ROOT_DIRS.split('|'): if not rootDir.startswith('/'): filename = filename.replace('\\','\\\\') %>
d:\MSYS\home\Lee\SickBeard\gui/slick/views/displayShow.mako, line 479:
<%
d:\MSYS\home\Lee\SickBeard\gui/slick/views/layouts/main.mako, line 220:
d:\MSYS\home\Lee\SickBeard\lib\mako\runtime.py, line 853:
callable_(context, *args, **kwargs)
```

I have shut down SR and deleted the cache\mako directory but to no avail, any ideas?

SR Version: BRANCH: (master) / COMMIT: (5aac5803f2e1df3385a5cb19580b8fd6b4eb6191) 
Python Version: 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]
OS : Windows 10 Pro

**Comment by miigotu** [comment]
add memory to your pc/vm? xD

**Comment by OmgImAlexis** [comment]
@miigotu we might want to test it later to see the amount of episodes per GB of RAM and add it to the requirements as a suggestion.

**Comment by miigotu** [comment]
Im not even sure that is the cause. I was kinda baiting th OP into telling me he has 16GB of ram or something lol.

**Comment by cocker80** [comment]
The PC has 16gb of RAM and swap of 3gb, it's only happened in the last couple of days. If i revert back to SickRage-4.0.66 it works fine but anything above i the same issue.

**Comment by miigotu** [comment]
@cocker80 since noone else has reported this we have to assume it is something in your setup.

Are you in a docker or vm or something that limits your memory? How big are your databases? Have you Stopped SR and deleted the cache folders contents (except the cache/images folder) and cache.db?

**Comment by cocker80** [comment]
It running on "Real" hardware not a VM, like i say its been running fine previously but it looks like this commit has caused the problem...

https://github.com/SiCKRAGETV/SickRage/commit/83853d8170626a0784759b5cd101d226871139ec#diff-3a9e689c8230966780b2688544445f9f

**Comment by miigotu** [comment]
@cocker80 correct commit!

notice the mixed path separators here:
`d:\MSYS\home\Lee\SickBeard\gui/slick/views/layouts/main.mako`

Although I can revert that change to make it work, this mixed sep is caused by msys -.-

Can I ask why you are running through msys rather than using the SR installer?

**Comment by cocker80** [comment]
I can see what you mean by the mixed "slashes" but i dont think MSYS is the problem. The "d:\MSYS\home\Lee" location is just where i clone to, SickRage is then run from a windows service. 

To prove that MSYS is not causing the problem i have...
-copied the "SickRage" directory to the root of the "C:" drive 
-opened a command prompt and set the PATH using "set PATH=c:\python27"
-ensured that no msys command can run i.e. 'git' is not recognized as an internal or external command, operable program or batch file.
-Issued "python SickBeard.py"

The same result still occurs...

Error !

MemoryError:

</td> <td class="col-name]"> % if epResult['location']: <% filename = epResult['location'] for rootDir in sickbeard.ROOT_DIRS.split('|'): if not rootDir.startswith('/'): filename = filename.replace('\\','\\\\') %>
C:\SickRage\gui/slick/views/displayShow.mako, line 479:
<%
C:\SickRage\gui/slick/views/layouts/main.mako, line 220:
C:\SickRage\lib\mako\runtime.py, line 853:
callable_(context, *args, **kwargs)

I have downloaded the SickRage Installer 0.3 and installed it. That give the similar errro but with some more details...
Error !
MemoryError: 
if not rootDir.startswith('/'): filename = filename.replace('\\','\\\\') %> ${basename(filename)} % endif </td> <td class="col-ep"> % if epResult["file_size"]: <% file_size = sickbeard.helpers.pretty_filesize(epResult["file_size"]) %> 
C:\SickRage\Python\lib\ntpath.py, line 189:
head2 = head2[:-1]
C:\SickRage\Python\lib\ntpath.py, line 208:
return split(p)[1]
C:\SickRage\SickRage\gui/slick/views/displayShow.mako, line 485:
${basename(filename)} 
C:\SickRage\SickRage\gui/slick/views/layouts/main.mako, line 220:
C:\SickRage\SickRage\lib\mako\runtime.py, line 853:
callable_(context, *args, **kwargs)

**Comment by miigotu** [comment]
Copying it wouldnt remove the error. The paths were set and stored in your DB using msys, so you have patchs in your db with mixed slashes. I will fix it, as it seems to be a silly method there in displayShow anyways. like wtf do rootDirs have to do with displaying that episode location properly?...

**Comment by miigotu** [comment]
@cocker80 could you try making this change and tell me is it works?

```diff
diff --git a/gui/slick/views/displayShow.mako b/gui/slick/views/displayShow.mako
index fc25ef1..4096e7c 100644
--- a/gui/slick/views/displayShow.mako
+++ b/gui/slick/views/displayShow.mako
@@ -2,7 +2,7 @@
 <%!
     import datetime
     import urllib
-    from os.path import basename
+    import ntpath
     import sickbeard
     from sickbeard import subtitles, sbdatetime, network_timezones
     import sickbeard.helpers
@@ -475,15 +475,7 @@
             ${epResult["name"]}
             </td>
             <td class="col-name]">
-                % if epResult['location']:
-                    <%
-                    filename = epResult['location']
-                    for rootDir in sickbeard.ROOT_DIRS.split('|'):
-                        if not rootDir.startswith('/'):
-                            filename = filename.replace('\\','\\\\')
-                    %>
-                    ${basename(filename)}
-                % endif
+                ${ntpath.basename(epResult['location'].replace('\\','\\\\'))}
             </td>
             <td class="col-ep">
                 % if epResult["file_size"]:
```

**Comment by miigotu** [comment]
Im also unsure about my changes to the backup/restore of config and cache. Wonder if you can verify that is working still?

On restore, everything is extracted to a folder called `restore` so you would need to backup, then do the restore, and before shutting down move your cache folder, config.ini, and all of your db's out of place and see if when you start it up if everything is restored.

**Comment by cocker80** [comment]
The patch sorted out the "MemoryError:" and the restore procedured worked form me...

Restore: restoring DB and config.ini SUCCESSFUL!
10:55:10 INFO::MAIN :: Restore: restoring cache successful

Miggotu Cheers for your help, Lee.

**Comment by miigotu** [comment]
@cocker80 nice, and all of your info and settings were correct after startup? Just want to verify before I push the commit for displayShow

**Comment by cocker80** [comment]
Yes i can confirm that my settings are correct, artwork is present, and all shows are available.

**Comment by miigotu** [comment]
Thank you, hotfixing to master now.
