### ISSUE TITLE
[APP SUBMITTED]: invalid literal for int() with base 10: '---'

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [SiCKRAGETV/sickrage-issues#3029]
### INFO
Python Version: **2.7.10 (default, Sep 22 2015, 12:25:10) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)]**
Operating System: **Darwin-14.5.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5aac5803f2e1df3385a5cb19580b8fd6b4eb6191
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [ExtraTorrent] :: Failed parsing ExtraTorrent Traceback: Traceback (most recent call last):
  File "/Users/ovidijus/Apps/SickRage/sickbeard/providers/extratorrent.py", line 126, in _doSearch
    seeders = int(item['seeders'])
ValueError: invalid literal for int() with base 10: '---'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@duramato

**Comment by duramato** [comment]
For reference https://github.com/SiCKRAGETV/SickRage/pull/2655
