### ISSUE TITLE
Downloads column only 1 progressbar

### ISSUE THREAD

**Issue by sn3akz** [SiCKRAGETV/sickrage-issues#303]
Much like issue #272 my downloads column only shows the first progressbar. I have NO Anime shows and the split-list option in anime settings is disabled.

Running on OpenELEC 4.97.2
commit: 33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8 on Master branch
Python 2.7.3

![screenshot from 2014-12-30 10 56 51](https://cloud.githubusercontent.com/assets/1746312/5577529/5b043352-9013-11e4-81b2-bb08ee009c27.png)

Debug log (restart): http://sprunge.us/YPPF

Resulting HTML of columns: http://pastebin.com/5cHGM5Kk

**Comment by sn3akz** [comment]
The file names are all like:
8 Out of 10 Cats - S15E01 - Jack Dee, Claudia Winkleman, David O'Doherty, Josh Widdicombe.mp4
8 Out of 10 Cats - S15E04 - Tess Daly, Stephen Mangan, Kian Egan, Tony Law.mp4
8 Out of 10 Cats - S15E02 - Richard Bacon, Gemma Collins, Katherine Ryan, Henning Wehn.mp4
8 Out of 10 Cats - S15E05 - David O'Doherty, Krishnan Guru-Murthy, Jamelia, Paul Foot.mp4
8 Out of 10 Cats - S15E03 - Joe Wilkinson, Rachel Riley, Chris Ramsey and Tina Malone.mp4      
8 Out of 10 Cats - S15E06 - Alex Jones, Joe Wilkinson, Danny Dyer, Miles Jupp.mp4

So I can imagine something with escaping quotes in filenames is not going the way it should ;)

**Comment by sn3akz** [comment]
Succeeded to replicate bug on develop SHA 8b84e4f4bc6cdebdc605438e9e75d15f1133d65e. Looks like it's a problem related to my files? It's a CIFS mount on a NAS.

![screenshot from 2015-01-02 14 38 38](https://cloud.githubusercontent.com/assets/1746312/5596393/30924cfe-928d-11e4-8e56-3a31fd8305af.png)

**Comment by neoatomic** [comment]
I think i know this bug. In the past i had something similar. If you did set an x amount of episodes to skipped the process bar showed a question-mark (?) instead op the number of episodes. (now seemingly there is no bar at all.?)
Never found the problem, but it looked to me that if you go past a certain % this happens.

Hope your tests will show some pattern so the developers can pinpoint and fix it.

**Comment by markheloking** [comment]
@sn3akz please use [markdown](https://guides.github.com/features/mastering-markdown/) in the future.

**Comment by sn3akz** [comment]
Fix merged into develop. Thanks all!
