### ISSUE TITLE
viewlogs.mako is auto-refreshing (1min) while SR is still searching the log

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#3030]
This happens when you have a lot of logs and use the logFilter or logSearch features

**Comment by OmgImAlexis** [comment]
@fernandog personally I think we should just remove the js refreshes, thoughts?

**Comment by fernandog** [comment]
I like the refreshes but not in viewlogs.

**Comment by OmgImAlexis** [comment]
What's the point for them though? If you don't see something then refresh, I don't know why anyone would leave a window open for more than a few minutes, once you're finished with a page you usually close it.

**Comment by fernandog** [comment]
I keep comingEpisodes open. To see status changing.
NP. Remove it then

**Comment by miigotu** [comment]
@OmgImAlexis I thought we were working on moving towards ajax to handle that without a refresh?

**Comment by OmgImAlexis** [comment]
@miigotu yeah I was but I'm still waiting for the new api as I was going to ask for socket.io or something similar to be added, ajax is alright for now but I'd rather sockets so we only update when it's actually updated on the server.

Just switch to ajax for now? I can add a comment to each section so we can easily find and switch over to sockets later.

**Comment by miigotu** [comment]
I just think ajax is the simpler solution for now, comments are ok.
