### ISSUE TITLE
Kickass search not returning result

### ISSUE THREAD

**Issue by systemloc** [SiCKRAGETV/sickrage-issues#3033]
Slackware 14.1
Python 2.7.5
BRANCH: (master) / COMMIT: (78e5416c12423ed6c35c0bac9a091ed3fba93261) 

I manually searched a show episode. Kickass Torrents is my first search provider. Logs show kickass site was searched. There is a torrent for the show available on kickass, but no results were returned in sickrage.

Debugging is made more difficult due to the sparse debug output and lack of an actual search URL.
Logfile output below. Link to working torrent desired on kickass below.

Logfile output:
http://pastebin.com/aVmU2dCU

https://kat.cr/cutthroat-kitchen-s09e12-we-came-we-see-sawed-we-conquered-480p-hdtv-x264-rmteam-mkv-t11331539.html

**Comment by fernandog** [comment]
Need fu logs. Also check you minSeed / minLeecher setting in KAT

**Comment by miigotu** [comment]
With 3 lines of log output I can't help you.

The url SR is using there is this correct and returns the result:
https://kat.cr/usearch/?q=Cutthroat.Kitchen+S09E12%7C9x12&field=seeders&rss=1&category=tv&sorder=desc

Maybe stop SR, and clear your cache.db and cache folder of everything except cache/images

**Comment by miigotu** [comment]
Quality is unknown.

```python
>>> import sys; sys.path.insert(1,'lib'); import sickbeard
>>> from sickbeard.common import Quality
>>> p = sickbeard.name_parser.parser.NameParser()
>>>Quality.qualityStrings[p._parse_string(u'Cutthroat.Kitchen.S09E12 We Came We See-Sawed We Conquered 480p.HDTV.x264-RMTeam.mkv').quality]
```

**Comment by fernandog** [comment]
What if you replace spaces with dot?

**Comment by miigotu** [comment]
has nothing to do with dots. we dont recognize 480p

**Comment by fernandog** [comment]
https://en.m.wikipedia.org/wiki/480p

480p does not qualify as high-definition television (HDTV); it is considered enhanced-definition television (EDTV).

**Comment by miigotu** [comment]
That is irrelevent.

My test must be fail. Might have to add the show to my list.

```
>>> Quality.qualityStrings[p._parse_string(u'Cutthroat.Kitchen.S09E12.720p.HDTV.x264').quality]
'Unknown'
```

**Comment by miigotu** [comment]
forgot to `_compile_regexes`

**Comment by miigotu** [comment]
Lets not clutter the report with nonsense. Just confusing the OP.

**Comment by systemloc** [comment]
Ok...

First, my quality is custom for preferred: SDTV, and allowed is EVERYTHING. So unknown quality should still be downloaded. This raises a side issue that 480p should be recognized as something. I would suggest it be recognized as SDTV.

Next, there are plenty of seeds for my min of 5.

Next, I tried shutting down, removing cache.db and the contents of the cache directory and retrying. No change in result. I also included gratuitous and unedited log contents:
http://pastebin.com/pdE9XF7M

**Comment by systemloc** [comment]
I don't see in the logs where sickrage parses, acknowledges, or finds that torrent. I've got DEBUG logging turned on. Is there a way to increase the logging level further? I can post any additional data you request.

**Comment by miigotu** [comment]
@systemloc we have all of the info you can provide. Please wait until we figure it out or have more questions, thanks.

**Comment by miigotu** [comment]
https://github.com/martinblech/xmltodict/issues/111 (point 2) is the problem. hotfixing.
