### ISSUE TITLE
web_root parameter not working

### ISSUE THREAD

**Issue by Kyah** [SiCKRAGETV/sickrage-issues#3035]
Alpine Linux 3.2 Dockerized
Python 2.7.10
BRANCH: (master) / COMMIT: (1c3577ae6df29cad345f64d23647d0a2d8a4e008) 

I'm moving my Sickbeard setup to SickRage and want to use the web_root param to be able to access my sickrage on myhost/series/home instead of myhost/home but it does not seems to work. For now, when i go to myhost/series/home I get redirected to myhost/home and get an error in the log

The error i get in the logs :
AA
AAAttributeError: 'WebRoot' object has no attribute 'series/home'
AA    method = getattr(self, route)
AA  File "/sickrage/sickbeard/webserve.py", line 258, in get
AA
AAAttributeError: 'WebRoot' object has no attribute 'series'
AA    method = getattr(self, route)
AA  File "/sickrage/sickbeard/webserve.py", line 258, in get

My config.ini line : 
web_root = /series

**Comment by fernandog** [comment]
Did you try without / ?

**Comment by Kyah** [comment]
Yes, and I got the same error

**Comment by OmgImAlexis** [comment]
Should be working, mine works on dev and master fine. Keep in mind you need to stop SR, change the config.ini and then start it.

**Comment by Kyah** [comment]
Damn nevermind, wrong configuration inside my docker filesystems, I was editing the wrong config.ini
