### ISSUE TITLE
Mako Runtime error "22" invalid arguement

### ISSUE THREAD

**Issue by Hansica** [SiCKRAGETV/sickrage-issues#3036]
When I click on a show on a specific show (only this one), program closes with this error

% else: Never % endif <span class="sort_data">${date.isoformat('T')}</span> </td> <td> % if sickbeard.DOWNLOAD_URL and epResult['location']: <%
C:\SickRage\lib\dateutil\tz.py, line 152:
return time.localtime(timestamp+time.timezone).tm_isdst
C:\SickRage\lib\dateutil\tz.py, line 108:
if self._isdst(dt):
C:\SickRage\gui/slick/views/displayShow.mako, line 493:
<span class="sort_data">${date.isoformat('T')}</span>
C:\SickRage\gui/slick/views/layouts/main.mako, line 220:
C:\SickRage\lib\mako\runtime.py, line 853:
callable_(context, *args, **kwargs)

this is my SR info

Configuration
SR Version:	BRANCH: (master) / COMMIT: (1c3577ae6df29cad345f64d23647d0a2d8a4e008) 
SR User:	media_center
SR Locale:	('en_US', 'cp1252')
SR Config:	C:\SickRage\config.ini
SR Database:	C:\SickRage\sickbeard.db
SR Cache Dir:	C:\SickRage\cache
SR Log Dir:	C:\SickRage\Logs
SR Arguments:	['--nolaunch']
Python Version:	2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]

**Comment by Hansica** [comment]
apologize for my ignorance, but tried searching every possible key word and cannot find where open or closed issue exists.

**Comment by OmgImAlexis** [comment]
@fernandog please reference the original issue if you tag it as a duplicate. https://github.com/SiCKRAGETV/sickrage-issues/issues/3007

**Comment by Hansica** [comment]
Found the thread and Got it all fixed. Thanks so much for putting up with
an old newbie.
