### ISSUE TITLE
[Feature Request] Use custom images stored in the show folder as banner/poster

### ISSUE THREAD

**Issue by bthusby** [SiCKRAGETV/sickrage-issues#304]
Feature Request:

Any plans to make SickRage automatically find posters/banners in the show folder and put them in the cache/thumbnail folders when added manually due to missing scraped art? It could be done when doing a 'force full update' for the show.

This must of course co-exist and be compatible with formats that XBMC needs.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
