### ISSUE TITLE
ValueError: (22, 'Invalid argument') with show NBA

### ISSUE THREAD

**Issue by Bart274** [SiCKRAGETV/sickrage-issues#3040]
Hi,

I just added a new show on tvdb.com in order to get NBA games automatically through SickRage, but I get the following error after I navigate to the added show.
I want to use this show: http://thetvdb.com/index.php?id=301326

![knipsel](https://cloud.githubusercontent.com/assets/1118630/10196979/d3d314ec-6795-11e5-9483-de7f15d8bbfd.JPG)

**Comment by miigotu** [comment]
Use the search feature.
