### ISSUE TITLE
Sickrage stops logging after a day

### ISSUE THREAD

**Issue by datalektiker** [SiCKRAGETV/sickrage-issues#308]
Sickrage stops logging my events after a day or so. When I check the log in the Web UI it just stops refreshing it after an unknown amount of time. If I get any error messages they show up in the error log but the default log is frozen. It doesn't change even if i restart the service through the Web UI restart function. Reboot solves it. Should say that everything else works just fine and it's still running and doing what it's supposed to, i just can't keep an eye on what it's doing in the log.

BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8) 
Windows 7 (64)
Python version 2.7

**Comment by cvockrodt** [comment]
I'm pretty sure I've been seeing this too. I've been cycling my server often though, so it hasn't been an issue.
