### ISSUE TITLE
Sorting of shows table is not remembered

### ISSUE THREAD

**Issue by tchirou** [SiCKRAGETV/sickrage-issues#3086]
BRANCH: (master) / COMMIT: (0b2254c884f833bbb54b8c7e6f6231f4d61557d0)  Python : 2.7.6 Win 8.1 Chrome, ios safari, OS X safari
Hello
The shows list page is sorted with ended shows then show name. When I choose to sort by active first, it works but the setting is not stored anymore. So if I clear my cache or if I access Sickrage with another browser, it goes back to ended sorting. I guarantee this was working until last week I think.
Many thanks for your help

**Comment by gerbil42** [comment]
I updated to 0b2254c884f833bbb54b8c7e6f6231f4d61557d0 a couple minutes ago and was unable to sort by Next Ep column.  Related?

The arrow changed directions on click of the column header, but it made no difference in the sorting of shows.

**Comment by OmgImAlexis** [comment]
@gerbil42 that's been fixed. SiCKRAGETV/SickRage#2730

**Comment by gerbil42** [comment]
Good to know - still new to Git, but it looks like it's currently in develop, correct?
Next time develop merges to Master, it should be fixed for Master?

**Comment by OmgImAlexis** [comment]
@gerbil42 correct, that should be either in a few days or at the end of the week.

**Comment by OmgImAlexis** [comment]
@miigotu please don't close this

**Comment by miigotu** [comment]
@OmgImAlexis he says that the fix worked. (He didnt restart after the update, didnt work until it restarted)

**Comment by tchirou** [comment]
I think he had a different issue than mine

**Comment by miigotu** [comment]
@OmgImAlexis @tchirou Ouch sorry, I somehow missed that it wasnt the OP saying it was fixed.

**Comment by tchirou** [comment]
No worries

**Comment by OmgImAlexis** [comment]
@fernandog did this get fixed or did you close this because of what @miigotu said?

**Comment by fernandog** [comment]
I tested here and its working. Afaik @VinceVal fixed

**Comment by tchirou** [comment]
Sorry guys but it does not work for me with e1bf8412922d898878e98e5f4466492eb39c4456
Tested with windows chrome and iOS Safari after several restarts. Each time I clear the cache and I log again, shows are sorted by ended status no matter what.

BTW, if failed to automatically update, I had to manually git pulled the update. There are a bunch of errors after each restart : https://gist.github.com/tchirou/0dac7b87976a6893451a

**Comment by OmgImAlexis** [comment]
Delete cache/mako if it's just been fixed you won't see it if your mako files are still cached.

**Comment by tchirou** [comment]
Ok I shut it down, deleted the mako folder, restarted.
Weirdly enough, it works with iOS safari but not with windows chrome, Internet Explorer and Firefox nor with OS X Safari. tried with 2 different windows computers and a virtual machine.

**Comment by fernandog** [comment]
Here works with chrome. Check if cookies are blocked.

**Comment by tchirou** [comment]
I did not change my config. Everything is authorised during the session but when I close the browser, my config deletes all local data. (click&clean chrome extension).
When you say it works with yours, do you delete all the browser cache as i do ?
