### ISSUE TITLE
Error "mktime argument out of range" related to user TZ Setting

### ISSUE THREAD

**Issue by JPengelley** [SiCKRAGETV/sickrage-issues#3095]
Is anyone else having trouble with the error 
“Exception generated in thread CHECKVERSION: mktime argument out of range”? 
I see this on a new install (by hand or the new Windows Installer)
It's the same on several machines & Operating Systems) and I get the error at turn on with or w/o data. 

Changing my TZ from +8 to UTC (or -8) Fixes the problem. 
Changing it to Sydney (+10 +1hr Daylight Saving) does NOT. 

I image you can reproduce this by setting your TZ to +8 and restarting SR

The error started yesterday and so did Daylight Saving in Aust, so this might be a new bug. 
Any suggestions would be very much appreciated. 

btw - First post and I must add that I love SR so much and my thanks to all those who made it possible
---------------------------------------------------------------------------------------------------------------------------------------

=============================================================================
2015-10-04 21:14:47 INFO     DAILYSEARCHER :: Searching for new released episodes ...
AAOverflowError: mktime argument out of range
AA    last_read = time.mktime(time.strptime(sickbeard.NEWS_LAST_READ, '%Y-%m-%d'))
AA  File "C:\SickRage\SickRage\sickbeard\versionChecker.py", line 296, in check_for_new_news
AA    self.check_for_new_news(force)
AA  File "C:\SickRage\SickRage\sickbeard\versionChecker.py", line 83, in run
AA    self.action.run(self.force)
AA  File "C:\SickRage\SickRage\sickbeard\scheduler.py", line 105, in run
AATraceback (most recent call last):
2015-10-04 20:34:51 ERROR    CHECKVERSION :: Exception generated in thread CHECKVERSION: mktime argument out of range
2015-10-04 20:34:46 INFO     MAIN :: Building internal name cache for all shows
2015-10-04 20:34:46 INFO     CHECKVERSION :: Checking for updates using GIT
=============================================================================

JPengelley

**Comment by VinceVal** [comment]
This is related to the new news checker. I'll take a look.

**Comment by miigotu** [comment]
@VinceVal I think you should be using datetime instead of the time module.

**Comment by VinceVal** [comment]
@miigotu I think you're right. It looks like this issue is specific to timezones with a positive offset AND platforms that don't support negative timestamps -- like Windows.

**Comment by Kwart1001** [comment]
Same error message here. Thanks for looking in to it.

**Comment by VinceVal** [comment]
@Kwart1001 what timezone and OS are you?

**Comment by miigotu** [comment]
@VinceVal if you switch it to use calendar.timegm() instead of time.mktime() it will ignore timezone afaik.
