### ISSUE TITLE
[APP SUBMITTED]: 'ascii' codec can't encode character u'\u2026' in position 53: ordinal not in range(128)

### ISSUE THREAD

**Issue by ColdIce1** [SiCKRAGETV/sickrage-issues#3098]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.3-RELEASE-p25-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@8985c2f3d5376227aa7603cb9aad574f4341ab33
Link to Log: https://gist.github.com/50b5dd67ffccd284e899
### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 1503, in downloadSubtitles
    subliminal.save_subtitles(foundSubs, directory=subs_path, single=not sickbeard.SUBTITLES_MULTI)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/subliminal/api.py", line 133, in save_subtitles
    with io.open(subtitle_path, 'wb') as f:
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 53: ordinal not in range(128)

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@ColdIce1 please set locale to UTF-8 to user that runs SR. Check /config page in SR
