### ISSUE TITLE
Warning after today's update:  Unknown exception in getURL https://kat.cr/tv/ Error: '_socketobject' object has no attribute 'set_tlsext_host_name' / ssl_sni_test.py reports no errors.

### ISSUE THREAD

**Issue by doczong** [SiCKRAGETV/sickrage-issues#3099]
New warning appearing after today's update.

Unable to upgrade to PyOpenSSL-0.15.1, as there is no cryptography on Qnap (ARM Marvel based).  Tried compiling cffi as well, however that was a no go (missing unavailable libffi-dev).  Nothing available in old Optware or new Qnapware.

Running PyOpenSSL-0.13.1, PyASN1-1.0.8, and ndg-httpsclient-0.4.0

Version: 	BRANCH: (master) / COMMIT: (0b2254c884f833bbb54b8c7e6f6231f4d61557d0) 
Python:  2.7.10 (default, Aug 1 2015, 10:32:01) [GCC 4.8.3]

Verify SSL Certs in config/general is unchecked.

Is this a problem with KAT?  Do I need to worry about this while waiting for the ability to move up to the new PyOpenSSL?

I understand and have been all over the OpenSSL page here (and should be meeting the requirements):  https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors  I have also been all over https://github.com/SiCKRAGETV/sickrage-issues/issues/1566

````
2015-10-04 18:34:01 SEARCHQUEUE-DAILY-SEARCH :: [KickAssTorrents] :: Unknown exception in getURL https://kat.cr/tv/ Error: '_socketobject' object has no attribute 'set_tlsext_host_name'
2015-10-04 18:34:01 SEARCHQUEUE-DAILY-SEARCH :: [KickAssTorrents] :: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1622, in getURL
    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 762, in _validate_conn
    conn.connect()
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 296, in ssl_wrap_socket
    cnx.set_tlsext_host_name(server_hostname)
AttributeError: '_socketobject' object has no attribute 'set_tlsext_host_name'
```

This is the output of the snl_ssi_tests.py

```

python ssl_sni_tests.py
test_SNI_URLS (__main__.SNI_Tests) ...
Checking Womble's Index
Checking BTN
Checking ThePirateBay
Checking KickAssTorrents
Checking TorrentLeech
Checking SceneAccess
Checking HDTorrents
Checking TorrentDay
Checking HDBits
Checking HoundDawgs
Checking IPTorrents
Checking omgwtfnzbs
Checking NextGen
Checking Speedcd
Checking NyaaTorrents
Checking AnimeNZB
Checking TorrentBytes
Checking FrenchTorrentDB
Checking FreshOnTV
Checking TitansOfTV
Checking Libertalia
Checking MoreThanTV
Checking BitSoup
Checking T411
Checking TokyoToshokan
Checking AlphaRatio
Checking Shazbat.tv
Checking Rarbg
Checking TNTVillage
Checking BinSearch
Checking BLUETIGERS
Checking Cpasbien
Checking FNT
Checking Xthor
Checking SceneTime
Checking BTDigg
Checking Strike
Checking TransmitTheNet
Checking TvChaosUK
Checking TorrentProject
Checking ExtraTorrent
ok

----------------------------------------------------------------------
Ran 1 test in 34.851s

OK
```

And this is the current version of Python packages installed:

```
Cheetah (2.4.4)
lxml (3.2.3)
Mako (1.0.2)
Markdown (2.6.2)
MarkupSafe (0.23)
ndg-httpsclient (0.4.0)
pip (7.1.2)
pyasn1 (0.1.8)
pycurl (7.19.5.1)
pyOpenSSL (0.13.1)
requests (2.6.0)
setuptools (18.3.2)
wheel (0.26.0)
yenc (0.4.0)
```

And this is what is available in my runtime:

```
opkg list-installed
alsa-lib - 1.0.29-1
ffmpeg - 2.8-1
findutils - 4.5.14-1
libbz2 - 1.0.6-2
libc - 2.20-8b
libcurl - 7.43.0-1
libdb47 - 4.7.25.4.NC-5
libffi - 3.0.13-1
libffmpeg-full - 2.8-1
libgcc - 4.8.3-8b
libgdbm - 1.11-1
libncurses - 5.9-2
libopenssl - 1.0.2d-1
libpcre - 8.37-2
libpthread - 2.20-8b
librt - 2.20-8b
libsqlite3 - 3081101-1
libstdcpp - 4.8.3-8b
libxml2 - 2.9.2-3
libxslt - 1.1.28-2
locales - 2.20-8b
pyopenssl - 0.13.1-1
python - 2.7.10-6
python-base - 2.7.10-6
python-codecs - 2.7.10-6
python-compiler - 2.7.10-6
python-ctypes - 2.7.10-6
python-curl - 7.19.5.1-1
python-db - 2.7.10-6
python-decimal - 2.7.10-6
python-distutils - 2.7.10-6
python-email - 2.7.10-6
python-gdbm - 2.7.10-6
python-light - 2.7.10-6
python-logging - 2.7.10-6
python-multiprocessing - 2.7.10-6
python-ncurses - 2.7.10-6
python-openssl - 2.7.10-6
python-pydoc - 2.7.10-6
python-sqlite3 - 2.7.10-6
python-unittest - 2.7.10-6
python-xml - 2.7.10-6
qnapware - 2.6.1-5
terminfo - 5.9-2
wget - 1.16.3-1
zlib - 1.2.8-1
```

**Comment by miigotu** [comment]
You are missing headers. Libffi-dev libssl-dev (libopenssl-dev?) And python-dev

**Comment by doczong** [comment]
Those are not available on Qnap (ARM, QTS 3.8), at least not via the package manager.

I can get an ancient copy of libopenssl-dev (0.9.8-v2).... but libffi-dev and libssl-dev are not available.  I'm also stuck with gcc-4.2.3.

So yeah, I know why I can't compile cffi and upgrade to PyOpenSSL-0.15.  The issue I am now seeing after todays' update, which was not there yesterday, is the "downgraded" PyOpenSSL-0.13.1 + PyASN + ndg-httpsclient is now throwing the "ssl" error, with KAT (TPB is not throwing the error) that is referenced here: https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors

Anyhow, just wanting to make you aware that based on the "SSL-Error" page above, with those requirements fulfilled, that error is popping up again, and wondering if there is a solution for using the "downgraded" PyOpenSSL-0.13.1 if that is what we're stuck with.

Also, it looks like cross compiling cffi is impossible as well as per your same page above.

**Comment by miigotu** [comment]
It has been said many times that Qnap ARM it is impossible to get a fully working setup at this time. You MUST disable ssl verify in config/general advanced, stop SR, and delete cache/sessions and cache/rss and cache.db.

Having pyopenSSL installed without libssl, libffi, python-dev, libssl-dev and libffi-dev only makes it worse because pyOpenSSL simply cannot work without them.

**Comment by doczong** [comment]
Hi Migotu.  

Thanks (and don't get me wrong, I appreciate the hard work), I edited my post to indicate that "Verify SSL Certificates (Disable this for broken SSL installs (Like QNAP)" is actually disabled/unchecked.

PyOpenSSL0.13.1 is working great as an FYI.  I just can't compile anything without the "-dev" packages.  I am working on getting the libffi-dev working from source now.  libffi-3.0.13 is installed.  

libssl* and python-dev are simply not available.

Anyhow, delete cache/sessions and cache/rss and cache.db and see how that goes.

I just thought I would bring it to your attention because as per all your documentation, everything in theory should be setup correctly with the correct versions (older versions mind you, but still should be good with the "downgrade") but now that error appeared.

I'll post back just as an FYI on a yay/nay if the cache clear worked or not.

Cheers,
M

**Comment by doczong** [comment]
Hi Migotu,

Update to the last update:

"Verify SSL Certificates (Disable this for broken SSL installs (Like QNAP)"  is/was disabled/unchecked.

Stopped SR, Deleted cache/sessions and cache/rss and cache.db and started SR.  Then issued a "Force Daily Search"

No change the error came back.  Again, I just want to emphasize that this error was not there until today.  Only after I updated this morning (GMT -5) did that error appear with KAT.  Up until today the error did not appear/exist.

**Comment by doczong** [comment]
Nevermind, I looked at my logs prior to the upgrade, and the error with KAT is there.

I guess it just was not as prominent.  I'll have to await a package update or continue screwing with getting the binaries created somehow.

**Comment by miigotu** [comment]
@doczong -dev packages are platform agnostic, they just need to be exact matches of the version you have installed.

Also, whatever pyOpenSSL and others you have installed have to had been compiled for the exact version of libssl, libffi, and python you have instealled or the ABI doesnt match exactly. If there is a mismatch there is a possibility they may work for some functions, but not others.

**Comment by doczong** [comment]
@miigotu thanks brother.  It's been about 15 years (like, early slackware days) since I have had to compile anything in *nix.  I've become too dependant on SLES and RHEL package managers.

Thanks for the clarification re the "-dev" releases having to be the same version, I will attempt to gather the versions for the compiled binaries that I currently have installed.  I'll also check and see if I can't get something uploaded to the Entware/Qnapware repository if I can manage to get those compiled and working properly as you mentioned re the ABI and exact versions.

As a note: I have literally given up on trying to cross compile to ARMv5TEL... my goal now is to build on box.  Hopefully my ancient gcc-4.2.3 is up to the task.
