### ISSUE TITLE
Feature request: Quickly change desired show quality

### ISSUE THREAD

**Issue by mushroomman** [SiCKRAGETV/sickrage-issues#310]
I am looking for a way to quickly change quality of a show. Right now process is to click on show name, click edit, change the quality and then save. Each step takes a while on ARM QNAP devices. Can the quality label be made clickable and able to directly affect the desired show quality?

**Comment by WebSpider** [comment]
Trying to figure out how this should work with custom quality settings / archive in the UI ... anyone got any suggestions?

**Comment by fernandog** [comment]
Changing quality shouldnt be a common/daily/weekly thing to do. you set one time and maybe when a new season comes with new quality. if you must keep changing quality the or your provider its not good or you didnt choose initial/archive proper.

**Comment by abeloin** [comment]
You can change multiple shows quality via the mass update page using the edit selected button.

**Comment by markheloking** [comment]
Thanks @abeloin!
