### ISSUE TITLE
Check if issue is locked before submit

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#3101]
@miigotu from what I see here:

https://developer.github.com/v3/issues/#response-1

imo I would add here:
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/logger.py#L267

```
                for report in reports:
                    if title_Error == report.title:
                        if not report.locked:
                            comment = report.create_comment(message)
                            if comment:
                                issue_id = report.number
                                self.log('Commented on existing issue #%s successfully!' % issue_id)
                                issue_found = True
                            break
                        else:
                                self.log('Issue #%s is locked. Can't submitt' % issue_id)
                                return
```

but return what?

**Comment by fernandog** [comment]
maybe return issue 0000

and check here if is 0000 and show ui.notification
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/webserve.py#L5010

**Comment by OmgImAlexis** [comment]
@fernandog ideally the issue shouldn't be locked if there's a chance that it could come up again.

**Comment by fernandog** [comment]
Using phone sorry

**Comment by fernandog** [comment]
@OmgImAlexis issue is that an user submited at least 5 issues. The same. Spamming issue and notifications

**Comment by OmgImAlexis** [comment]
@fernandog we probably need to do a check to see if they've submitted that issue within the last n hours. If it's submitted we warn them that submitting multiple times may have their account blocked from submitting further issues as it's considered spam, etc?

**Comment by fernandog** [comment]
@OmgImAlexis 

https://github.com/SiCKRAGETV/sickrage-issues/issues/1437#issuecomment-145401054

**Comment by miigotu** [comment]
Regardless the locked check needs to be in the issue submitter. Otherwise it makes another error. We can then notify them it is locked and just return the issue # for them to check, with a link to it.
