### ISSUE TITLE
No Downloads Were Found

### ISSUE THREAD

**Issue by sapper6fd** [SiCKRAGETV/sickrage-issues#3103]
Hey guys.  

For the past few days now I've been unable to grab anything.  Everything is coming up as Missed and when trying to manually pull something that's available, I'm told No Downloads Were Available. 

My logfile is [here](http://pastebin.com/3ePD0Re9) 
COMMIT: (8985c2f3d5376227aa7603cb9aad574f4341ab33). 
OS: WS2008 R2
Python version 2.7.6

This seems to have happened after I updated to the latest version.  Since that occured, nothing has downloaded.  Any ideas why?

**Comment by miigotu** [comment]
Please try using the installer for windows. Just copy your settings.ini and cache/images and sickbeard.db into the Data folder in the install location afterwards. It will handle your service installation and everything,

https://github.com/VinceVal/SickRageInstaller/releases

Alternatively, make sure your pyopenSSL is working, or go to config/general on the advanced tab and disable `Verify SSL Certs`, then stop sickrage, and delete everything in the cache folder except the images folder, and removing cache.db before restarting.

**Comment by miigotu** [comment]
Also, check your log about "discarding torrent because...."
