### ISSUE TITLE
log errors when unreachable broken

### ISSUE THREAD

**Issue by Koal4** [SiCKRAGETV/sickrage-issues#3104]
The setting to supress error messages that the Kodi client is offline is not working anymore. 

2015-10-05 07:23:02 Thread-157 :: Warning: Couldn't contact KODI HTTP at http://192.168.1.111:180/kodiCmds/kodiHttp/?command=Help 
2015-10-05 07:23:02 Thread-157 :: Failed to detect KODI version for '192.168.1.111:180', check configuration and try again.
2015-10-05 07:22:59 Thread-157 :: Error while trying to retrieve KODI API version for 192.168.1.111:180: error [Errno 113] No route to host

This has worked fine until saturday/sunday when the latest update was pushed. The option log errors when unreachable broken is still turned off but it is spamming these kind of error messages again.

**Comment by neoatomic** [comment]
If you had taken the time to read up how to properly report an issue and supplying all the necessary info... : 
https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md

Try to remove/rename the cache folder and let SR build a fresh one. If that doesn't work that its something local related to your setup/network.

**Comment by Koal4** [comment]
First let me explain my frustration a bit. A few weeks/months back I also posted some issues which didn't get a respond. Then 2 weeks ago I also posted this issue immediately the day after some updates where introduced and this issue was introduced. At that time I didn't get a response while newer issues did get a response. This kept on going for some days. Then appereantly 1,5 week later I noticed a notice from github basically saying that my account was flagged as a bot (for god know why) and if that wasn't the case I had to contact github support for that. For me it was unclear that other ppl (like you) couldn't read my findings because to me it looked like it was posted successfully and visible for every one while it wasn't.

Then your answer about suppliying all info is semi correct but in this case I dont see any reason to post a debug log because the errors that are posted are basically correct. The problem is that the function ' log errors when unreachable ?' is not working. Whent the checkbox is off notifications still spams the warninglog. This was introduced 2 weeks ago when you probably changed the function 'view warnings / view log'. Also this step is very easy to reproduce by turning of that function and fill in an ip address that is not correct and press the button 'test kodi' under notications. As you can see after a refresh the errors are still visible in the warning/log. 

Just to please you i let SR rebuild my cache.db file and cache folder. But this didn't resolved my issue which I was kind of expecting tbh. This was somehing that could be tested very easily by any dev tbh and I highly doubt this is a local issue becase for me it stopped working after the updates from weekend 3-4 oct. 


SR Version:	BRANCH: (master) / COMMIT: (7045417b59bb23cbc2426e2e1f7b0e59f21a87fb)

**Comment by fernandog** [comment]
@Koal4 

so if KODI_ALWAYS_ON is ENABLED you don't want too see the warning?

if so, the code is wrong

if should be `if not sickbeard.KODI_ALWAYS_ON:`
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/notifiers/kodi.py#L575

**Comment by neoatomic** [comment]
@Koal4 First let me explain something. We are all volunteers here, and we put a lot of our free time in helping users and developing SickRage for FREE.
And for sure its not a RIGHT to get support here, consider that more a gift from all the good people here who simply want to help others. Hope that gets you thinking a little...

We need logs to see how you have setup/working SR, we cant know that from a few log lines.
Just follow the guidelines like everyone else does.

**Comment by Koal4** [comment]
@fernandog No, I don't think so.
Basically I had this option turned off. Because in my situation my kodi client isn't running 24/7 so SR occasionally downloads new shows and spammed the log/warnings in SR. By turning this option off it stops giving me warnings when a show was downloaded when my Kodi client was offline. This function has stopped and it doesn't matter if the option is turned on or off. It keeps on giving me warnings whenever a show was downloaded. I prefer to have SR update my kodi client whenever it is turned but when it's turned off I don't want to see the errors. As mentioned before this always worked fine untill the weekend of Oct 4-5. 

I hope it's a bit clear now. Otherwise I can just advise you turn on kodi notifications. Turn off your kodi client or fill in a random IP and test the kodi connection


@neoatomic Let's just agree to disagree. I don't think you understand my situation completely. And I certainly don't think it's a right to get support here. In the past I've reported several issues and also tested workaround and fixes before it even went in the master branch. But before making such statement also think about users (like me or any other ppl) who are taking their time and effort to post bugs and test fixes also in their free time. There are enough users out there who starts flaming on other forums about how shitty a(fill in a random product or dev) could be.

And for now I want to focus on the issue please.

**Comment by Koal4** [comment]
Small update.

I had an older SR installation running on my old HTPC and I completely upgraded it to the latest version. I experience exacle the same problem and it's very issue to reproduce by doing the steps I mentioned above. Now I certainly know it is not a local issue. 

So again I would appreciate it if this can be re-opened so that it can be fixed @neoatomic @fernandog

**Comment by fernandog** [comment]
What is the exact message that you dont want?

**Comment by Koal4** [comment]
@fernandog 
Lol.

It's not about the message that I don't want. What I'm trying to explain is that this option is not working anymore how it was intended.

" Always on | log errors when unreachable ?"

This option is made to log errors when Kodi client is not reachable. 

When turned on it should always log errors when it cannot detect your kodi client.
When turned off it ignore errors when your Kodi client is not reachable for whatever reason.

Now it's working like the checkbox is always on. It is reported errors always

[img]http://imgur.com/bOROoxx[/img]

**Comment by fernandog** [comment]
Wrong image

**Comment by Koal4** [comment]
img tag messed it up but it's working now. Image just for reference as the error messages are basically correct.

**Comment by miigotu** [comment]
This is fixed last night, https://github.com/SiCKRAGETV/SickRage/commit/9e00354545b81d96007afe1a3c02da852b0f10e1

**Comment by Koal4** [comment]
@miigotu Thanks

However it is still giving me an that it can't detect my Kodi version.

-2015-10-22 19:33:15 Thread-35 :: Failed to detect KODI version for '192.168.1.111:180', check configuration and try again.

So we went from 3 to 2 warning messagens and now only this one is left

**Comment by miigotu** [comment]
Thats only in test notify, it overrides that setting in that case so you know the test fails. In actual use it will not log that.

**Comment by Koal4** [comment]
Owke, that makes sense in a way why it is showing now.

Anyway thanks for looking into, really appreciate it
