### ISSUE TITLE
Problem with browsing specific show

### ISSUE THREAD

**Issue by 03397** [SiCKRAGETV/sickrage-issues#3107]
After I have upgraded to the newest version(0beda92f71145d448f8f784042a8d631448a0394)  I am facing two different issues

When I click the 24 show I am getting the following errors.

Error !

IndexError: tuple index out of range

<input type="checkbox" class="epCheck" id="${str(epResult["season"])+'x'+str(epResult["episode"])}" name="${str(epResult["season"]) +"x"+str(epResult["episode"])}" /> % endif </td> <td align="center"><img src="${srRoot}/images/${("nfo-no.gif", "nfo.gif")[epResult["hasnfo"]]}" alt="${("N", "Y")[epResult["hasnfo"]]}" width="23" height="11" /></td> <td align="center"><img src="${srRoot}/images/${("tbn-no.gif", "tbn.gif")[epResult["hastbn"]]}" alt="${("N", "Y")[epResult["hastbn"]]}" width="23" height="11" /></td> <td align="center"> <% text = str(epResult['episode']) if epLoc != '' and epLoc != None:
/share/MD0_DATA/.qpkg/SickRage/gui/slick/views/displayShow.mako, line 431:
<td align="center"><img src="${srRoot}/images/${("nfo-no.gif", "nfo.gif")[epResult["hasnfo"]]}" alt="${("N", "Y")[epResult["hasnfo"]]}" width="23" height="11" /></td>
/share/MD0_DATA/.qpkg/SickRage/gui/slick/views/layouts/main.mako, line 274:
/share/MD0_DATA/.qpkg/SickRage/lib/mako/runtime.py, line 853:
callable_(context, *args, **kwargs)

I do not know if other shows have the same issue.
The second error message is when sickrage restarts

2015-10-05 10:14:23 INFO     MAIN :: Changing status from Archived to Archived (Unknown) for 76290: S06E01 at äkirjat::Finland+Drama|Fantasy|Horror|Mystery|Romance|ThrillerUSAusTV-148.0AANone
2015-10-05 10:14:23 ERROR    MAIN :: Found 1 shows with bare archived status, attempting automatic conversion...

I do not know which show this is since I do not have any show from finland.

**Comment by miigotu** [comment]
That changing status is for 24: http://thetvdb.com/?tab=series&id=76290 S06E01

**Comment by 03397** [comment]
So these two errors  are related? 
24 is as archive for one year now.

**Comment by miigotu** [comment]
@03397 Archived status does not exist anymore. It is now qualified with the quality of the file "Archived (SDTV)" for example.

On boot, if any episodes are found with the old style status, they are automatically converted.

However, the conversion exposes the reason why you have the error loading the page.

This is set as the location for that episode (and is a corruption, not caused by this conversion): `äkirjat::Finland+Drama|Fantasy|Horror|Mystery|Romance|ThrillerUSAusTV-148.0��AANone`

You either need to rebuild your DB or run some SQL on it to correct that.

**Comment by 03397** [comment]
@miigotu 
You were right. However, the problem is not just that show but to all the shows hat I have archived episodes.

I need to remove and add all shows in order to solve this problem,
The think is I can see the archive next to each episode displayed correctly but when I restart the problem is displayed at the next tv show with the archived episode.

**Comment by miigotu** [comment]
@03397 if you boot the latest version of SR it converts the archived status, and never needs to do it again. It changes the status in the db.

**Comment by 03397** [comment]
@miigotu 
What do you mean by  boot?
I am restarting Sickrage, I can see the error message but the status is changed like I mentioned before.
If the status is changed as per the new changes why do I keep getting a warning about this problem?

**Comment by miigotu** [comment]
start

The second warning in displayShow is because the location of the file is corrupt.
`I need to remove and add all shows in order to solve this problem` <- yes for the ones with that error at least.
