### ISSUE TITLE
Error during update

### ISSUE THREAD

**Issue by Lucas033** [SiCKRAGETV/sickrage-issues#3110]
I use sickrage on a synology 713, BRANCH: (master) / COMMIT: (0beda92f71145d448f8f784042a8d631448a0394) .
I updated sickrage today and got the next error

Error !AttributeError: 'module' object has no attribute 'SHOWS_RECENT'

<li><a href="${srRoot}/home/"><i class="menu-icon-home"></i>&nbsp;Show List</a></li> <li><a href="${srRoot}/home/addShows/"><i class="menu-icon-addshow"></i>&nbsp;Add Shows</a></li> <li><a href="${srRoot}/home/postprocess/"><i class="menu-icon-postprocess"></i>&nbsp;Manual Post-Processing</a></li> % if sickbeard.SHOWS_RECENT: <li role="separator" class="divider"></li> % for recentShow in sickbeard.SHOWS_RECENT: <li><a href="${srRoot}/home/displayShow/?show=${recentShow['indexerid']}"><i class="menu-icon-addshow"></i>&nbsp;${recentShow['name']|trim,h}</a></li> % endfor % endif

/usr/local/sickrage/var/SickRage/gui/slick/views/layouts/main.mako, line 120:

% if sickbeard.SHOWS_RECENT:

/usr/local/sickrage/var/SickRage/lib/mako/runtime.py, line 853:

callable_(context, *args, **kwargs)

**Comment by Lucas033** [comment]
The synology runs on the latest DSM 5.2-5592 Update 4 and phyton 2.7.10-14 from synocommunity

**Comment by mathewcalvin** [comment]
I am also having this issue, starting about 24 hours ago.  I did a clean reinstall 1 day ago and everything worked fine again until I updated to the latest batch of commits (23 commits) about an hour ago, and I got @Lucas033 's issue about ` 'module' object has no attribute 'SHOWS_RECENT' ` now my module has crashed entirely and will not start.  My sickrage page now simply returns ` ERR: Connection Refused `

**Comment by miigotu** [comment]
Stop package, delete cache/mako, start package.
