### ISSUE TITLE
PirateBay provider returns incorrect magnet links

### ISSUE THREAD

**Issue by swamp12** [SiCKRAGETV/sickrage-issues#317]
Due to an error(probably latest site switch) in the PirateBay provider, the search results contain the wrong magnet links; the magnet link of the result item + 1 is returned. And first search result is skipped.

The following patch fixes this:

    --- thepiratebay.py.org 2014-12-28 14:45:11.601525844 +0100
    +++ thepiratebay.py     2015-01-01 22:19:30.077525845 +0100
    @@ -65,7 +65,7 @@
     
             self.searchurl = self.url + 'search.php?q=%s&Torrent_sort=seeders.desc' # order by seed
     
    -        self.re_title_url = '/torrent/(?P<id>\d+)/(?P<title>.*?)//1".+?(?P<url>magnet.*?)//1".+?(?P<seeders>\d+)</td>.+?(?P<leechers>\d+)</td>'
    +        self.re_title_url = 'href=\'(?P<url>magnet:.*?)//1\'.+?/torrent/(?P<id>\d+)/(?P<title>.*?)//1".+?(?P<seeders>\d+)</td>.+?(?P<leechers>\d+)</td>'
     
         def isEnabled(self):
             return self.enabled

**Comment by fernandog** [comment]
TPB official is down. Let's wait until Feb 01

**Comment by swamp12** [comment]
Currently TBP provider is configured to a working mirror: 

    self.urls = {'base_url': 'https://oldpiratebay.org/'}

I assume quite some people still have this provider enabled(especially the ones with auto Sickrage update) and will receive incorrect search results. Resulting in stalled/slow downloads or even incorrect downloads; for example with foreign language audio. I suggest until then to either disable/remove TBP plugin until Feb 01, or apply above patch or similar to make it work correctly for the time being. Please re-open.
