### ISSUE TITLE
[Feature Request] Anime split display under mass update

### ISSUE THREAD

**Issue by mgaulton** [SiCKRAGETV/sickrage-issues#318]
I'd like to see the ability to have split sections in mass update when using the split display option for anime vs normal shows. I find that i manage anime with different options but i have to pick through the list to find them.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
