### ISSUE TITLE
Missing Some Network Images/Icons

### ISSUE THREAD

**Issue by Digital-Jedi** [SiCKRAGETV/sickrage-issues#320]
Just noticing that some network icons are missing. Specifically, the OWN network and something called  "internet.png", which tries to display for some fan series, but isn't loaded for some reason.

**Comment by neoatomic** [comment]
Is "OWN network" the exact name that is displayed in the show-list.?
Not sure what you mean with "Internet.png" , its not a network name for sure but maybe they didn't set this right at TVDB or TVRage for the particular series.

**Comment by Digital-Jedi** [comment]
Depending on which search result I pick, I either get "oprah winfrey network.png" or "own.png". It appears the two databases list them differently. Once I found the images folder, I went ahead and created this under both names:
![own](https://cloud.githubusercontent.com/assets/3283774/5602065/64b0af24-9302-11e4-9b12-eac99e260b8f.png) Not sure if that's as clean as the one's you usually make, but it's there if you'd like. The other one does appear to be the result of TheTVDB's entry. They usually leave the network field blank for fan series, but instead put "Internet" for this particular show.

**Comment by fernandog** [comment]
print screen?

**Comment by neoatomic** [comment]
I have added the logos for you.

If you like you can create a logo for "Internet" also. (but it needs to be universal so not the OWN logo as it will apply for other shows also. )

As this issue is fixed please close it, so the developers can move on to other problems/issues.

**Comment by Digital-Jedi** [comment]
Thanks. I did, in fact, add a little web icon I designed myself. Anyone is welcome to it, too, if they'd like.
![internet](https://cloud.githubusercontent.com/assets/3283774/5603373/a114f4cc-9350-11e4-94e0-233942a6cfd0.png)
