### ISSUE TITLE
Feature request: Progress bar - extra color for 100%

### ISSUE THREAD

**Issue by sn3akz** [SiCKRAGETV/sickrage-issues#322]
Based on this old issue https://sickrage.tv/forums/forum/main-category/feature-requests/10012-change-the-downloads-bar-color I would like to propose an extra color for the progress bar when you have ALL episodes (so a 100%)

I had 15 minutes to spare, so I scripted it ;) I could post a pull request if this is a feature more people want.

![screenshot from 2015-01-02 16 38 59](https://cloud.githubusercontent.com/assets/1746312/5597171/0ce37786-929e-11e4-8096-bb5df800b725.png)

**Comment by neoatomic** [comment]
Thanks for contributing.
Personally i find it a usefully addition. As you already have coded it, just make a pull request and we let echel0n make the final call when he is back from his well deserved holiday.

**Comment by RabidWolf** [comment]
It would be good if this was customisable in the config options so we could set our own colours. :-)

**Comment by sn3akz** [comment]
But then we would have to make all colors customizable. And since it are gradients, you would have to select 2 colors for each status, resulting in 10 colors to pick. Along with the not-so-user-friendly format of hex RGB color coding, I don't think a lot of users want to customize the colors.

However, I welcome suggestions on the current shade of green. I think I want it just a little more bright.

**Comment by fernandog** [comment]
@sn3akz do a PR in the develop branch.

**Comment by sn3akz** [comment]
@fernandog Done! :)

**Comment by markheloking** [comment]
I would also like to see this implemented. Thanks @sn3akz for this contribution!

**Comment by fernandog** [comment]
@sn3akz 
I tested and it's working but I didn't like the new green color. Low contrast with the number inside the bar

**Comment by sn3akz** [comment]
True... I saw it myself, but a darker color is a bit out of line with the rest. Maybe a complete different color? 

I'm more than open for suggestions (or color codes ;) )
