### ISSUE TITLE
[APP SUBMITTED]: 0

### ISSUE THREAD

**Issue by maju147** [SiCKRAGETV/sickrage-issues#3229]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.11-v7+-armv7l-with-debian-7.8**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@c0a1e4335dac26e97d4375ad2c56f2aeb836a7a8
Link to Log: https://gist.github.com/037f9c2235f37c296134
### ERROR
```
SEARCHQUEUE-MANUAL-248841 :: [BTN] :: Error while searching BTN, skipping: error 0
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by maju147** [comment]
Since yesterday I cant search manually for any episode, I get:
2015-10-09 18:03:21 SEARCHQUEUE-MANUAL-248841 :: [BTN] :: No NZB/Torrent providers found or enabled in the sickrage config for backlog searches. Please check your settings.

But backlog search is enabled. From the debugging log:

2015-10-09 18:03:21 ERROR    SEARCHQUEUE-MANUAL-248841 :: [BTN] :: No NZB/Torrent providers found or enabled in the sickrage config for backlog searches. Please check your settings.
AA
AAKeyError: 0
AA    quality = Quality.sceneQuality(item[0], anime)
AA  File "/home/****/.sickrage/sickbeard/providers/generic.py", line 552, in getQuality
AA    quality = self.getQuality(item, anime=show.is_anime)
AA  File "/home/****/.sickrage/sickbeard/providers/btn.py", line 343, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/home/****/.sickrage/sickbeard/search.py", line 488, in searchProviders
2015-10-09 18:03:21 ERROR    SEARCHQUEUE-MANUAL-248841 :: [BTN] :: Error while searching BTN, skipping: error 0

**Comment by aspehals** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c0a1e4335dac26e97d4375ad2c56f2aeb836a7a8
Link to Log: https://gist.github.com/ae05bfdd0cbea93a4655
### ERROR
```
SEARCHQUEUE-BACKLOG-261690 :: [BTN] :: Error while searching BTN, skipping: error 0
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Quiksmage** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@2b6f83243f117d32b0cb8d574f4812699f6fc08d
Link to Log: https://gist.github.com/d70faa4446321d76b959
### ERROR
```
SEARCHQUEUE-MANUAL-79824 :: [NyaaTorrents] :: Error while searching NyaaTorrents, skipping: error 0
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@miigotu BTN and NyaaTorrents. any clue??

**Comment by miigotu** [comment]
You removed getQuality and _get_size and _get_title_and_url for these and their item format is not right.

**Comment by fernandog** [comment]
I can fix this only tomorrow.
Should I re-add DEFs?

**Comment by miigotu** [comment]
for now in these ones, until their item format can be worked out right.

**Comment by Sin-Deus** [comment]
### INFO
Python Version: **2.7.8 (default, Dec 15 2014, 02:33:48) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@85df569d8d7b60c9e2453aea355df8ec5e8f1d62
Link to Log: https://gist.github.com/6a86e3363139084bb462
### ERROR
```
SEARCHQUEUE-MANUAL-299497 :: [NyaaTorrents] :: Error while searching NyaaTorrents, skipping: error 0
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@miigotu the only thing i remove from btn is image:

```
    def imageName(self):
        return 'btn.png'
```

**Comment by fernandog** [comment]
from nyaatorrents. seems ok!

```
    def _get_title_and_url(self, item):
        return generic.TorrentProvider._get_title_and_url(self, item)

    def imageName(self):
        return 'nyaatorrents.png'

    def getQuality(self, item, anime=False):
        title = item.get('title')
        quality = Quality.sceneQuality(title, anime)
        return quality
```

**Comment by fernandog** [comment]
generic:

```
    def getQuality(self, item, anime=False):
        (title, url) = self._get_title_and_url(item)
        quality = Quality.sceneQuality(title, anime)
        return quality

    def _get_title_and_url(self, item):

        title = item[0]
        download_url = item[1]

        if title:
            title = self._clean_title_from_provider(title)
        if download_url:
            download_url = download_url.replace('&amp;', '&')

        return (title, download_url)
```

**Comment by miigotu** [comment]
Nyaa needs this added back and it should be fine.
```
def getQuality(self, item, anime=False):
        title = item.get('title')
        quality = Quality.sceneQuality(title, anime)
        return quality
```

**Comment by fernandog** [comment]
what's the diff from generic's getQuality ?

**Comment by miigotu** [comment]
One is parsing a dict, one is parsing a list

**Comment by megabitus98** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@d1118cb1c9114778535b85b7e59758fde57ad9a5
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-299516 :: [NyaaTorrents] :: Error while searching NyaaTorrents, skipping: error 0
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by IceFreak66** [comment]
I have the exact same problem on the HDBits provider

##### INFO
Python Version: ## 2.7.9 
Operating System: Debian 8.2
Locale: UTF-8
Branch: master

##### ERROR
```
2015-10-10 10:38:49 INFO     SEARCHQUEUE-MANUAL-250487 :: [HDBits] :: Unable to find a download for: [American Horror Story - 5x01 - Checking In]
AAKeyError: 0
AA    quality = Quality.sceneQuality(item[0], anime)
AA  File "/root/sickrage/sickbeard/providers/generic.py", line 552, in getQuality
AA    quality = self.getQuality(item, anime=show.is_anime)
AA  File "/root/sickrage/sickbeard/providers/generic.py", line 370, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/root/sickrage/sickbeard/search.py", line 488, in searchProviders
AATraceback (most recent call last):
2015-10-10 10:38:49 ERROR    SEARCHQUEUE-MANUAL-250487 :: [HDBits] :: No NZB/Torrent providers found or enabled in the sickrage config for backlog searches. Please check your settings.
```

**Comment by IceFreak66** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d1118cb1c9114778535b85b7e59758fde57ad9a5
Link to Log: https://gist.github.com/3d2f074dc4ac15f14429
### ERROR
```
SEARCHQUEUE-MANUAL-257655 :: [HDBits] :: Error while searching HDBits, skipping: error 0
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by IceFreak66** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d1118cb1c9114778535b85b7e59758fde57ad9a5
Link to Log: https://gist.github.com/d93619e216c71504be71
### ERROR
```
SEARCHQUEUE-MANUAL-257655 :: [HDBits] :: Error while searching HDBits, skipping: error 0
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by IceFreak66** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d1118cb1c9114778535b85b7e59758fde57ad9a5
Link to Log: https://gist.github.com/9000fdab5eb08b7da731
### ERROR
```
SEARCHQUEUE-MANUAL-257655 :: [HDBits] :: Error while searching HDBits, skipping: error 0
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by IceFreak66** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d1118cb1c9114778535b85b7e59758fde57ad9a5
Link to Log: https://gist.github.com/bb3a02d2222d149d397d
### ERROR
```
SEARCHQUEUE-MANUAL-257655 :: [HDBits] :: Error while searching HDBits, skipping: error 0
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by IceFreak66** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d1118cb1c9114778535b85b7e59758fde57ad9a5
Link to Log: https://gist.github.com/268d33568138a4d79297
### ERROR
```
SEARCHQUEUE-MANUAL-257655 :: [HDBits] :: Error while searching HDBits, skipping: error 0
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by ElBob** [comment]
Exact same error as IceFreak66 here,

Python Version:	 2.7.10
Operating System:   OS X 10.11
Branch:                    Master

**Comment by fernandog** [comment]
@miigotu HDbits never had the getQuality, so what's wrong?

**Comment by miigotu** [comment]
Because you changes getQuality in generic.

**Comment by fernandog** [comment]
So need same quality as nyma?

**Comment by fernandog** [comment]
Dont recall changin quality in generic

**Comment by ElBob** [comment]
Now we've got "2015-10-11 19:58:30 SEARCHQUEUE-BACKLOG-110381 :: [HDBits] :: Error while searching HDBits, skipping: global name 'Quality' is not defined"

**Comment by miigotu** [comment]
@fernandog from sickbeard.common import Quality

**Comment by fernandog** [comment]
Done

**Comment by ElBob** [comment]
Ok, next error is:

    AAKeyError: 2
    AA    size = item[2]
    AA  File "/Applications/SickRage/sickbeard/providers/generic.py", line 570, in _get_size
    AA    result.size = self._get_size(item)
    AA  File "/Applications/SickRage/sickbeard/providers/generic.py", line 498, in findSearchResults
    AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
    AA  File "/Applications/SickRage/sickbeard/search.py", line 488, in searchProviders
    AATraceback (most recent call last):
    2015-10-12 10:34:11 ERROR    SEARCHQUEUE-BACKLOG-110381 :: [HDBits] :: No NZB/Torrent providers found or enabled in the sickrage config for backlog searches. Please check your settings.

**Comment by ElBob** [comment]
@fernandog @miigotu Got it to work with by adding this to hdbits.py. The API returns size in bytes, so I think this should be correct. I'm not super experienced with git, so if one of you wants to add this to the file, it should fix it.

    def _get_size(self, item):

        size = item['size']
        if not size:
            size = -1

        return size

**Comment by miigotu** [comment]
Ill have to fix it in a more general way when I get around to it. @ElBob The fix for this was immediately apparent to me, was waiting to see who would fix it.  Sorry you could easily see the problem and fix it before the person who changed the code to begin with. Just shows their PR's need even more scrutinized if they change stuff they dont understand.

**Comment by fernandog** [comment]
@ElBob sorry delay response. I knew what was the issue but its holiday here and Im travelling. Will PR tomorrow. Thanks for your patience.

@miigotu pacience... I dont spend all my free hours here.

**Comment by miigotu** [comment]
You should never have added get_size to generic.TorrentProvider. it was overridden in providers that support it intentionally. Most torrent providers don't support it.

**Comment by fernandog** [comment]
The ones that dont support we agree to set size = -1
My PR had a lot of commits and one was specific of moving size/quality to generic.
Will leave providers improv to your for now.

**Comment by miigotu** [comment]
Either way, the solution now is not to keep adding these back to providers but check the type if item and handle it accordingly in generic

**Comment by miigotu** [comment]
This problem us why I had started in providers changes like 3 time and did not merge them. The PRs got too big and too difficult to follow so there was no way to know for sure there was no problems. We need to do them one at a time.

**Comment by miigotu** [comment]
@ElBob can you try in develop please? Thanks.

**Comment by ElBob** [comment]
@miigotu That worked, good solution!

**Comment by bb12489** [comment]
### INFO
Python Version: **2.7.7 (default, Jun  1 2014, 14:21:57) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@136f531f93093a5287b588ca37e19c11153f47a4
Link to Log: https://gist.github.com/c0f77ee928d600c26287
### ERROR
```
SEARCHQUEUE-BACKLOG-299497 :: [AnimeNZB] :: Error while searching AnimeNZB, skipping: error 0
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by bb12489** [comment]
### INFO
Python Version: **2.7.7 (default, Jun  1 2014, 14:21:57) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@136f531f93093a5287b588ca37e19c11153f47a4
Link to Log: https://gist.github.com/1195e990c784e93bba21
### ERROR
```
SEARCHQUEUE-BACKLOG-299506 :: [AnimeNZB] :: Error while searching AnimeNZB, skipping: error 0
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by bb12489** [comment]
### INFO
Python Version: **2.7.7 (default, Jun  1 2014, 14:21:57) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@136f531f93093a5287b588ca37e19c11153f47a4
Link to Log: https://gist.github.com/3ec1fcac555783f8b1b1
### ERROR
```
SEARCHQUEUE-BACKLOG-293996 :: [AnimeNZB] :: Error while searching AnimeNZB, skipping: error 0
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Need to check animenzb

**Comment by fernandog** [comment]
@bb12489 do you still have this error?

**Comment by miigotu** [comment]
This should be fixed with my latest round of provider fixes.
