### ISSUE TITLE
Problem with "Change Show" Navigation 

### ISSUE THREAD

**Issue by heymoe** [SiCKRAGETV/sickrage-issues#326]
Branch: develop
Commit hash: 8b84e4f4bc6cdebdc605438e9e75d15f1133d65e
Your operating system and python version: CentOS Linux, Python v2.6.8

What you did:
* View a show via Show List, Coming Episodes, History, etc..
* Once the Show's page loads, click on the "Change Show" previous, next link or select another show from the drop down.

What happened:
* I receive a Error page and the logs show this as the error:

2015-01-03 03:08:37 Thread-401 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1048, in displayShow
    showObj = sickbeard.helpers.findCertainShow(sickbeard.showList, int(show))
ValueError: invalid literal for int() with base 10: 'undefined'

The URL that the browser tries to access is something like this:
* https://192.168.1.4:8080/home/displayShow?show=undefined

It looks like the code that is generating the "Change Show" links and pull-down isn't actually putting show's id # in the link / pull-down code.

What you expected:
* I expected the Show Page for the previous, next or the selected show from the drop down to load
* The problem does not exist in the master branch: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8)

**Comment by pcspecialist** [comment]
I have the exact same problem under Windows 7, Python Version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1160
