### ISSUE TITLE
Sickrage can't send notifications to https plex

### ISSUE THREAD

**Issue by tchabaud** [SiCKRAGETV/sickrage-issues#3286]
Hi,

I've an issue which seems like this one (https://github.com/SiCKRAGETV/sickrage-issues/issues/1834), but with a different error message : 

```
2015-10-14 04:41:01 ERROR    POSTPROCESSER :: PLEX: Error while trying to contact Plex Media Server: http protocol error : error 0 : got a bad status line
Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/notifiers/plex.py", line 224, in update_library
    xml_tree = etree.parse(urllib.urlopen(url))
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 357, in open_http
    'got a bad status line', None)
IOError: ('http protocol error', 0, 'got a bad status line', None)
```

I've tried with only account token, account token and user/password and only user/password, and I always get this error.

I'm using master branch, with python 2.7.10 on Archlinux

Is there a fix or workaround please ?

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by neoatomic** [comment]
Have Plex setup without Token and all is working fine here. No Errors.
Try `Shutting down SickRage and removing the cache/mako & cache/sessions folders.` See if that solves it.

**Comment by fernandog** [comment]
@tchabaud please send a screen shot of your PLEX settings

**Comment by tchabaud** [comment]
I've tried to stop sickrage, remove *cache/mako* and *cache/session*, and restart, no effect.

Here's my current Plex notifications settings :

![sickrage-plex](https://cloud.githubusercontent.com/assets/2120966/10496460/339841a0-72c1-11e5-886f-3bf529b5358a.png)

@neoatomic : how can I get which SR version I'm using ? I tried *Settings* -> *Server status* but can't find the version.

**Comment by OmgImAlexis** [comment]
@tchabaud :disappointed: use the IP address for plex....

**Comment by tchabaud** [comment]
With the IP I have a different message, but same error : 

```
2015-10-15 05:03:57 DEBUG    Thread-21 :: PLEX: fetching plex.tv credentials for user: ***************
2015-10-15 05:03:57 DEBUG    Thread-21 :: PLEX: Error parsing plex.tv response: Invalid header value 'Basic XXXXXXXX[...]XXXXXXXXXXXXXXXXXXXXXXXXXXX'
2015-10-15 05:03:57 ERROR    Thread-21 :: PLEX: Error while trying to contact Plex Media Server: http protocol error : error 0 : got a bad status line
Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/notifiers/plex.py", line 224, in update_library
    xml_tree = etree.parse(urllib.urlopen(url))
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 357, in open_http
    'got a bad status line', None)
IOError: ('http protocol error', 0, 'got a bad status line', None)
2015-10-15 05:03:57 DEBUG    Thread-21 :: PLEX: Updating all hosts with TV sections: 
```

I have this error with or without setting the token.

![sickrage-plex2](https://cloud.githubusercontent.com/assets/2120966/10505220/66783414-730b-11e5-9879-f1f6cd724a1a.png)

**Comment by OmgImAlexis** [comment]
That's probably because the newer Plex versions don't allow basic auth anymore. I'd suggest using the IP address and the auth token, that's what Plex themselves recommend and that's what I've been using for the last year or so.

**Comment by didyouexpectthat** [comment]
I just noticed this one in my logs today. I use IP address and token.
```2015-10-15 08:00:50 POSTPROCESSER :: PLEX: Error while trying to contact Plex Media Server: http protocol error : error 0 : got a bad status line```

![image](https://cloud.githubusercontent.com/assets/1329077/10517771/431c750e-7313-11e5-9093-7e1b032d300f.png)

**Comment by fernandog** [comment]
Can we query that informartion on plex?

**Comment by OmgImAlexis** [comment]
@fernandog we should always be checking with https, there's really no reason to use http since Plex is switching to just https and removing http support within the year.

**Comment by fernandog** [comment]
@OmgImAlexis 
so make https only will fix this?

**Comment by OmgImAlexis** [comment]
@fernandog if not it'll at least help diagnose what's going on.

**Comment by tchabaud** [comment]
@OmgImAlexis : Tried with only auth token and ip address, and still have same error.

I forgot to mention that I'm using Plex Media Server version 0.9.12.13 with secure connections setting set to *required*.

**Comment by didyouexpectthat** [comment]
@tchabaud Try making the changes to the file listed in https://github.com/fernandog/SickRage/commit/44cda3127077dd91deab891982fec4dca4edfa22 and see if that helps.

**Comment by OmgImAlexis** [comment]
@tchabaud running verison `0.9.12.13` and I've tried it with required and prefered, it seems to work both times. Maybe there's something we're missing..
Hopefully the patch that @fernandog added fixes it.

**Comment by neoatomic** [comment]
Got an SSL error today for the Plex update.

Long story short : HTTPS is not enabled/available by default on Plex server.
To enable you need to create an account on the Plex website and login with that account on your local Plex server. Only after that HTTPS is available on your LOCALE Plex server...

However i'm not to keen to have my local library linked to there website etc. Just want to run it standalone locally. And as Plex server and SR are running on my Syno, (on my local network) there is really no need for HTTPS.

I get the impression that they are forcing users to use an account so they subscribe to there (payed) premium stuff.

@OmgImAlexis Probably they are removing http for authentication with the PLEX account to there website.? 

At this point i would prefer to just use http, so i can ditch the hole account stuff that they are pushing.

```
2015-10-16 15:13:20 ERROR    Thread-56 :: PLEX: Error while trying to contact Plex Media Server: socket error : error EOF occurred in violation of protocol (_ssl.c:590)
Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/notifiers/plex.py", line 224, in update_library
    xml_tree = etree.parse(urllib.urlopen(url))
  File "/usr/local/python/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/local/python/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/local/python/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/usr/local/python/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/usr/local/python/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/usr/local/python/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/usr/local/python/lib/python2.7/httplib.py", line 1274, in connect
    server_hostname=server_hostname)
  File "/usr/local/python/lib/python2.7/ssl.py", line 352, in wrap_socket
    _context=self)
  File "/usr/local/python/lib/python2.7/ssl.py", line 579, in __init__
    self.do_handshake()
  File "/usr/local/python/lib/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] EOF occurred in violation of protocol (_ssl.c:590)
```

**Comment by OmgImAlexis** [comment]
@neoatomic well we're going to have to work out something because people that've got a plex account won't be able to use http at all soon and people that don't use a plex account which is honestly probably very low won't have https like you said.

Also they don't really "force" people to get an account or subscribe to their premium service, having a plex account just makes it easier for them since you can do things like use the plex.tv https services, etc.

**Comment by neoatomic** [comment]
@OmgImAlexis Well, i dont need/want those "services" thats the point...
And from Plex issues opened in the past, i'm pretty sure that a good amount of users doesn't use a Plex account. 
 
I would like to know what they are exactly planning to remove. I think that is probbebly the  authentication between Plex Server/clients and there website/Plex-Account.
In that case http locally should not be effected and will work fine. Than the best solution would be to add https (for plex) as an optional setting inside SR. (with a warning that a Plex account is required then.)

**Comment by tchabaud** [comment]
@fernandog : Thanks a lot, I added your patch to plex.py and it solves the problem for me (I'm only using token in settings, login/password are not needed).

@OmgImAlexis : Thanks for your help.

**Comment by docwho76** [comment]
I am having this problem on between sickrage and plex. Recent changes to sickrage seem to have broken this?

2015-10-16 20:25:53 DEBUG    Thread-27 :: PLEX: Updating all hosts with TV sections: 
AASSLError: ('The read operation timed out',)
AA    v = self._sslobj.read(len or 1024)
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/ssl.py", line 608, in read
AA    return self.read(buflen)
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/ssl.py", line 714, in recv
AA    data = self._sock.recv(left)
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/socket.py", line 380, in read
AA  File "", line 38, in parse
AA  File "", line 62, in parse
AA    xml_tree = etree.parse(urllib.urlopen(url))
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/notifiers/plex.py", line 224, in update_library
AATraceback (most recent call last):
2015-10-16 20:25:53 ERROR    Thread-27 :: PLEX: Error while trying to contact Plex Media Server: The read operation timed out

I'm on Plex 0.9.12.8.1362-4601e39 on FreeNAS

SR Version:	BRANCH: (master) / COMMIT: (d5a336dc0bf98249902ec3c455846624ac19387e) 
SR User:	media
SR Locale:	(None, None)
SR Config:	/var/db/sickrage/config.ini
SR Database:	/var/db/sickrage/sickbeard.db
SR Cache Dir:	/var/db/sickrage/cache
SR Log Dir:	/var/db/sickrage/Logs
SR Arguments:	['--datadir', '/var/db/sickrage', '-d', '--pidfile', '/var/run/sickrage/sickrage.pid', '-q', '--nolaunch']
Python Version:	2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]

I have tried removing the username/password from my SR PMS config, doesnt work.
I tried checking the PMS token to see if it had changed, it had not.

Any thoughts?

**Comment by docwho76** [comment]
Upgraded to Plex 0.9.12.13.1464-4ccd2ca and SR still cant talk to PMS for library updates.

Tried with just the token as well as no token, but username/password information filled in.

SR is configured to talk via an IP:port combo, no DNS names being used.

**Comment by nucshuco** [comment]
Freenas 9.3.1
the latest update to sickrage broke the plex notification. rolled back works fine.

AASSLError: ('The read operation timed out',)
AA    v = self._sslobj.read(len or 1024)
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/ssl.py", line 608, in read
AA    return self.read(buflen)
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/ssl.py", line 714, in recv
AA    data = self._sock.recv(left)
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/socket.py", line 380, in read
AA  File "", line 38, in parse
AA  File "", line 62, in parse
AA    xml_tree = etree.parse(urllib.urlopen(url))
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/notifiers/plex.py", line 224, in update_library
AATraceback (most recent call last):
2015-10-16 21:58:51 ERROR    Thread-23 :: PLEX: Error while trying to contact Plex Media Server: The read operation timed out

![plex](https://cloud.githubusercontent.com/assets/8262089/10557123/eeae956a-7452-11e5-9676-a8168ab3d23e.JPG)

**Comment by OmgImAlexis** [comment]
You guys need to stop using both the username/password and the token. It's one or the other, I wouldn't be surprised if that's part of the issue.

**Comment by nucshuco** [comment]
i tested it both ways still dosen't work.

**Comment by fernandog** [comment]
@OmgImAlexis @miigotu what should we do? That PR cause more 'issues'

Maybe for now try https except http ?

**Comment by OmgImAlexis** [comment]
@fernandog we either need to add an option to ask if they're using a plex.tv account if they are use https and if not use http or we can try https and if that fails try http? That's not really a good idea though as that means if https is failing for some reason then we're sending stuff over plain text when we really shouldn't be at all. :disappointed:

**Comment by fernandog** [comment]
@miigotu what do you think?

**Comment by OmgImAlexis** [comment]
Looks like the issue is if it's on an internal or external network. https seems to ONLY work on an external network, maybe we need to have a checkbox for that instead? Currently ONLY http works for localhost.

**Comment by miigotu** [comment]
maybe should add a checkbox setting to "use https" and then catch the exception with a log saying to try toggling https setting?

**Comment by OmgImAlexis** [comment]
@miigotu sounds like a good idea. Can we get the fix reverted, no installs using localhost work at the moment.

**Comment by fernandog** [comment]
who can PR that? I don't have plex

**Comment by job7777** [comment]
@fernandog 
fernandog commented a day ago
who can PR that? I don't have plex

You don't have PLEX and you made changes :(

**Comment by miigotu** [comment]
:+1:

**Comment by fernandog** [comment]
lol said a fake profile : Joined on 18 Oct 2015
THAT is a child game kkkkkkkk

**Comment by miigotu** [comment]
@fernandog I dont have time for that stuff, really, stop doing drugs.

**Comment by fernandog** [comment]
who blamed you?!

**Comment by miigotu** [comment]
@fernandog so if you weren't accusing me, then you are acknowledging that other people have an issue with the stuff you break? KCoolThx.

**Comment by job7777** [comment]
I made the profile just for that. I don’t understand why you would push that out without testing on PLEX first. It’s an easy test.

**Comment by fernandog** [comment]
talking about things broken... like the issue filter feature that was supposed to work but not.
tons of same issues everyday when I should reply, not open new.
But that's ok. I never pointed out others mistakes. We are here to make it work. 
wont reply anymore. please anybody feel free to PR and fix it, as this repo is open source.

**Comment by miigotu** [comment]
Those issues are from your lack of understanding of encoding, when you decided to change 32 providers drastically in one PR.
