### ISSUE TITLE
Anime Absolute Number bug

### ISSUE THREAD

**Issue by WarB3asT** [SiCKRAGETV/sickrage-issues#329]
BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8)
Python Version:	2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]

This happens when i want to enable Only Absolute Number (Only applies to animes)
and it shows me an error in episode naming pattern.
My name pattern in episode naming is %Sx%0E. %SN - %EN
and my anime name pattern is %Sx%0E. %SN - %EN

2015-01-04 04:40:32 Thread-50 :: You tried saving an invalid anime naming config, not saving your naming settings
2015-01-04 04:40:32 Thread-50 :: You tried saving an invalid anime naming config, not saving your naming settings

**Comment by fernandog** [comment]
@WarB3asT what is that dot after %0E?

**Comment by WarB3asT** [comment]
@fernandog 
It's a dot to rename to something like this

Single-EP Sample:
2x03. Show Name - Ep Name.ext

Multi-EP sample:
2x03x04x05. Show Name - Ep Name.ext

and it's working... the problem is when i enable Only Absolute Number in anime... it shows me a error not in the anime but in the episode naming.

**Comment by fernandog** [comment]
this happens with all animes or just one?
does this anime have all data? Maybe some data is missing to rename.
At the anime page, is there a column showing the absolute number?

**Comment by WarB3asT** [comment]
@fernandog 
It happens to all animes. Yes i have all data(absolute number too).

With absolute i can't save the config.

Without Absolute Number
![noabsolute](https://cloud.githubusercontent.com/assets/7808460/5614625/ce9f478a-94ea-11e4-9a21-cb63f867b9d9.png)

With Absolute Number
![absolute](https://cloud.githubusercontent.com/assets/7808460/5614624/ce955dba-94ea-11e4-92b6-4a875bafe418.png)

**Comment by fernandog** [comment]
@WarB3asT try add one variable at time. Try to find the one that is causing the issue.

**Comment by WarB3asT** [comment]
When i choose a default naming pattern for anime and episode from the combobox, they work except the ones 2x03 - Ep Name and S02E03 - Ep Name. Any combination with one of those patterns result in a error like before.

If i use the pattern i want (%Sx%0E. %SN - %EN) and add something before like Test
(Test %Sx%0E. %SN - %EN) it works... so maybe the problem is when using only absolute number the pattern can't start with a number or a %?

**Comment by fernandog** [comment]
let's wait @echel0n then.

**Comment by abeloin** [comment]
@WarB3asT Is Flatten Folders checked?

**Comment by WarB3asT** [comment]
@abeloin In some of my animes i have Flat Folders check, but not all of them.

**Comment by abeloin** [comment]
@WarB3asT Ok, first there's a bug in the JavaScript which highlighted the wrong section when the anime pattern is invalid and and the tooltip aren't shown.

Check the log after the text become red, you will see the validating results, example [name pattern: %Sx%0E. %SN - %EN](http://pastebin.com/LnCCnhVM).

In this case, the invalid regex is "bare":
```
The name Show Name.003-004.Ep Name.ext parsed into Show Name 003 - S0E4 [ANIME VER: -1] [ABD: False] [ANIME: False] [whichReg: ['bare']] 
Unable to parse 003. Show Name - Ep Name.ext, not valid
```

**Comment by abeloin** [comment]
@WarB3asT Can you try the develop branch and apply [this commit](https://github.com/abeloin/SickRage/commit/ec860e502b6dfa6e60834bd372ad46977f34a7d4)?

**Comment by abeloin** [comment]
@WarB3asT Small reminder, if you had time to try the commit?

**Comment by WarB3asT** [comment]
Sorry for the wait, but i couldn't test this early.

When i choose only anime, now it shows the error in the anime box (saving will show me the same error as before).

With 'Only absolute number' checked if i write something in the anime box and like %Sx%0E. asd %SN - %EN and then remove the 'asd' (nothing changes) and save... it will show both anime and tvshows box in red.

One question wouldn't be easier if there was a Pattern for absolute order? Something like %AB

**Comment by abeloin** [comment]
@WarB3asT The commit was for fixing an invalid anime pattern being shown in non anime input box.

CHeck your log when the anime box become red you should see all the regex being tested and find the ones that are not valid e.g.: ```The name Show Name.003-004.Ep Name.ext parsed into Show Name 003 - S0E4 [ANIME VER: -1] [ABD: False] [ANIME: False] [whichReg: ['bare']] 
Unable to parse 003. Show Name - Ep Name.ext, not valid```

**Comment by WarB3asT** [comment]
@abeloin A few of them are being reported as 'not valid'.
http://pastebin.com/9V03ZTG1

**Comment by fernandog** [comment]
@abeloin your local commit fixes it?

**Comment by abeloin** [comment]
It fix the output of the anime error in the tv section.

In his case it fail in the bare regex which I'm triyng to figure out why it wont.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/332

**Comment by fernandog** [comment]
@abeloin any news on this one?

**Comment by abeloin** [comment]
@fernandog We need to create a new anime regex and placed before anime_bare:
```
    ('anime_WarB3asT',
     # 003. Show Name - Ep Name.ext
     # 003-004. Show Name - Ep Name.ext
     '''
     ^(?P<ep_ab_num>\d{3,4})(-(?P<extra_ab_ep_num>\d{3,4}))?\.\s+(?P<series_name>.+?)\s-\s.*
     '''),
```

**Comment by abeloin** [comment]
@WarB3asT Can you try this PR https://github.com/SiCKRAGETV/SickRage/pull/1645

**Comment by fernandog** [comment]
@WarB3asT you have an anime regex with your name. what a honor! =)

**Comment by WarB3asT** [comment]
@fernandog Its a great honor indeed! =)
@abeloin Tested and its working like a charm :D

**Comment by fernandog** [comment]
@WarB3asT fix will be in master next sunday

**Comment by hackedbellini** [comment]
Just updated to the latest version, tied removing and adding some animes again, but I still have the issue described [here](https://github.com/SiCKRAGETV/sickrage-issues/issues/332) (the issue that was marked as duplicated of this one and closed).

**Comment by abeloin** [comment]
@hackedbellini I've reopen your issue and removed the duplicate status
