### ISSUE TITLE
Authentication conflicts with couchpotato

### ISSUE THREAD

**Issue by hackedbellini** [SiCKRAGETV/sickrage-issues#331]
I have both sickrage (master branch) and couchpotato installed on my server here. I use authentication on both, using the same username.

I noticed that if I open both on the same browser, after doing a login in one, it will logout of the other.

Ex:

1) Open and login in sickrage
2) Open and login in couchpotato.
3) Try to navigate on sickrage again... It will redirect to the login page.

After that, if I login on sickrage again, it will loose the couchpotato's login.

This didn't happen on sickbeard (I'm a long sickbeard user who just migrated to your fork =P)

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/214

**Comment by fernandog** [comment]
@Abeloin is there a way to fix this?

**Comment by abeloin** [comment]
We just have to rename our cookie name from user to something like sickrage.

**Comment by abeloin** [comment]
@fernandog Reopen? 

@hackedbellini Can you try this commit https://github.com/abeloin/SickRage/commit/d0152e898cd049d3a37863efec1db8a3c1e763c4 it should fix your issue?

**Comment by fernandog** [comment]
@abeloin fixed! Thanks!

**Comment by abeloin** [comment]
@fernandog Couchpotato should do the same

**Comment by timrettop** [comment]
@abeloin Confirmed fix resolves this issue for me as well! 

Thanks!

**Comment by abeloin** [comment]
@timrettop Thank you for testing and the feedback.
