### ISSUE TITLE
É encoding issue

### ISSUE THREAD

**Issue by maxcore** [SiCKRAGETV/sickrage-issues#3318]
A old bug comeback with the caracter 'É'

My show is Les enfants de la télé : 
tvdb show number : 193731

![capture d ecran 2015-10-15 15 43 01](https://cloud.githubusercontent.com/assets/4043787/10525671/ff0be80e-7353-11e5-85b0-a8f8ef9b815d.png)

![capture d ecran 2015-10-15 15 49 18](https://cloud.githubusercontent.com/assets/4043787/10525733/5fbc0e5e-7354-11e5-8689-c5b829bdbb29.png)

My config : 

![capture d ecran 2015-10-15 15 47 53](https://cloud.githubusercontent.com/assets/4043787/10525696/21e7e724-7354-11e5-8f60-241555b1b95b.png)

````
AAKeyError: u'\xe9'
AA    return ''.join(map(quoter, s))
AA  File "/usr/local/python/lib/python2.7/urllib.py", line 1303, in quote
AA    searchURL = self.urlsearch % (urllib.quote(search_string), self.categories)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/xthor.py", line 100, in _doSearch
AA    itemList += self._doSearch(curString, search_mode, len(episodes), epObj=epObj)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/generic.py", line 357, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 491, in searchProviders
2015-10-15 21:25:57 ERROR    SEARCHQUEUE-BACKLOG-193731 :: [Xthor] :: Error while searching Xthor, skipping: é
2015-10-15 21:25:57 INFO     SEARCHQUEUE-BACKLOG-193731 :: [Xthor] :: Performing season pack search for Les enfants de la tÃ©lÃ©

```
thx you

**Comment by fernandog** [comment]
@maxcore try please:

stop SR
git checkout 3baef95a
start SR,
full update one show that has wrong char
see if works

**Comment by maxcore** [comment]
@fernandog i am on synology . i need to do this in ssh console ?

**Comment by maxcore** [comment]
@miigotu 
we can close this issus fixed from https://github.com/SiCKRAGETV/sickrage-issues/issues/3339#issuecomment-148868362
