### ISSUE TITLE
[Feature Request] Add regex for Animes absolute number 

### ISSUE THREAD

**Issue by hackedbellini** [SiCKRAGETV/sickrage-issues#332]
I asked my animes to be renamed as ```%SN EPS%0SE%0E``` which gives me ```Show Name EP003.ext``` after checking the ```Only Absolute Number``` option.

I have an already existing anime library named exactly like that. But when I try to add them as existing tv shows (marking the "anime" option in it before adding), all the episodes get recognized as season 01.

So, for example, an anime with 10 season 1 episodes and 12 season 2 episodes got recognized like: The first 10 were the real season 1, and the next 12 as extra season 1 episodes, making it a 22 season 1 episodes.

**Comment by fernandog** [comment]
full logs (pastebin) ? Branch? printscreens? OS?

**Comment by markheloking** [comment]
Please use the issue guidelines when posting an issue. This way the dev team is able to debug your problem. Don't forget to use 

[markdown](https://guides.github.com/features/mastering-markdown/) on any code and log you want to post in-line.

- [ ] Branch
- [ ] Commit hash
- [ ] Operating system and python version
- [x] What did you do?
- [x] What happened?
- [x] What did you expect?
- [ ] Link to a copy/paste of your logfile with clear debug info of the error on [pastebin](http://pastebin.com/) (or in-line 

using [markdown](https://guides.github.com/features/mastering-markdown/) for small snippets)

**Comment by hackedbellini** [comment]
Well, here are some more info about the issue:

* Branch: master
* Commit hash: 33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8 (master's HEAD)
* Operating system and python version: Debian Jessie/Sid, Python 2.7.8
* Log: Here is the related log for this issue (please tell me if you need something else): http://paste.debian.net/139552/
* Screenshots: Here is a screenshot of me adding the existing anime show (http://postimg.org/image/3kup75nrl/) and another one of the recognized existing episodes (http://postimg.org/image/auazpbf1j/)

All the episodes on the screenshot are filled in season 01, even though the show recognized 8 episodes, all with their respective absolute numbers. Also, note that after the absolute number became to differ from the season number, the absolute number was considered '0'.

You can see how I asked sickrage to rename my animes on the first post of the issue. For example, this one is named ("Saint Seiya EP001.avi", "Saint Seiya EP002.avi" and so on), which should have matched.

**Comment by nexulh** [comment]
I've got a similar issue. It seems "normal" regexes scores higher than "anime" regexes for certain episodes anime episodes (specifically those that I've named "Show - 123" with 123 being the absolute episode number), thus it chooses a "normal" regex ("bare") as the best match, which includes season as a part, which fucks up the indexing. 

For hackedbellini though, it seems the anime regexes doesn't allow "E" in front of the episode number, thus only matches normal regexes (which does allow it). 

I guess the solution would be to give  "ep_ab_num" a higher score if it's found, as it's only used in anime regexes, and those are only used when having marked a show as an anime. Or just remove the normal regexes from consideration when the show is an anime (in the NameParser._compile_regexes function). 

To solve for hackedbellini's problem though, one would have to modify the anime regexes a bit (or convince hackedbellini to not use "E" or "EP" in front of episode numbers).

**Comment by hackedbellini** [comment]
@nexulh I'm using 'EPXXX' because of kodi's (old xbmc) naming convention for absolute episode numbers, as explained in this link: http://kodi.wiki/view/Naming_video_files/TV_shows#Single_episode

Without the EP, it would consider, for example, 'Some TV Show 102' to be Season 01 Episode 02 and not the absolute 102 episode.

I tried changing ```%SN EPS%0SE%0E``` to ```%SN EP%0E``` to see if that would solve the problem, but sickrage said the syntax wasn't valid...

But based on your feedback, maybe there should be an option (e.g. ```%A``` and ```%0A```) to match absolute episodes, instead of checking an option that "magically" changes the ```S%0SE%0E``` to it? Just a suggestion...

**Comment by nexulh** [comment]
@hackedbellini When looking through the code for the renamer I found that it supports "%AB" which translates to the absolute episode number. It doesn't currently support multi-ep filenames for %AB, so I'm looking at adding that functionality. From the looks of the code, it seems to be a one-line change. 
Btw, does Kodi require all episodes to be listed in the filename (like: "EP001-EP002-EP003"), or does it support "ranges" ("EP001-EP003", EP002 included in that range)? It isn't very explicit in the examples it gives on the page you linked to.

There's still the problem of getting the parser to support the "EP" prefix that kodi requires for absolute episode numbers. It might be a bit more involved because of the division between "normal" and "anime" code-wise, but I'll see if I can figure it out.

**Comment by nexulh** [comment]
Regarding my last reply... I might have underestimated the changes required to make the first alternative usable (with %AB). Requires some consideration regarding "special" episodes and other corner cases. 
If one uses the build in "Add absolute number" or "Only absolute number" options in the renamer, if it's a "special" episode (which are considered as part of "season 0") the renamer doesn't add absolute numbers to the filename at all (I'm guessing because they usually don't have absolute episode numbers). This cornercase would be fairly bothersome to handle if one uses %AB in the pattern. 

Also, I'm guessing the verification of the pattern goes through the matchers in sickbeard/name_parser/*? I had a bit of trouble making changes which didn't match any patterns in there at least. So the name_parser side of things is probably better to start making changes. 
I'll see if I can make some progress at it.

**Comment by hackedbellini** [comment]
@nexulh regarding your question: Don't know about ranges, but kodi supports lists like EP001_002_003 or EP001-002-003 (maybe more, but I haven't tested)

**Comment by hackedbellini** [comment]
Btw, not only that... just tried to make sickrage rename on post-processing some anime I just downloaded. The anime had 252 episodes, and was named like "Anime Name 001", "Anime Name 002", "Anime Name 003-004" and so on.

Sickrage created a mess. It considered some of those episodes to be from season 0, and all number greater than 99 to be of season 1 (so 101 became S01E01).

I tried than renaming everything to "Anime Name EP001" (putting the EP in front of it) and call post-processing again... This time it said there wasn't enough information on those episodes to check what number it was.

So, the problem is even deeper than my description... The problem is not just the recognizing existing library, but adding new too. And most animes I know use absolute numbers and that naming convention ("Anime Name 001").

**Comment by nexulh** [comment]
@hackedbellini Yeah, that's the major source of pain I think. I've modified the regexes in my local code to accept EPxxx style filenames and it seems to work, but I haven't found a way to verify that I didn't break something else. 
I'll make a pull request tomorrow for the code I've changed and maybe one of the project developers can take a look at it.

**Comment by fernandog** [comment]
@nexulh any news? everything ok?

**Comment by hackedbellini** [comment]
@fernandog I just tested this and the issue is still present on latest develop.

**Comment by abeloin** [comment]
@hackedbellini Currently SR doesn't support the EP naming scheme

**Comment by hackedbellini** [comment]
@abeloin I see. The problem is, kodi expects absolute number episodes to be names ```EPxxx```, as you can see [here](http://kodi.wiki/view/Anime) and [here](http://kodi.wiki/view/Naming_video_files/TV_shows#Single_episode).

This is very common for animes, but can also happen for tv shows.

Having said that, with the work that has been done on #329 , isn't anything I can do in the mean time, while this issue is not implemented?

**Comment by abeloin** [comment]
@hackedbellini I'm currently looking if adding a regex to detect EP001=<ep_abs_num> is enough or do we need to make a bigger change for it to work.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
