### ISSUE TITLE
automatic update from http server fail on kodi 14.0

### ISSUE THREAD

**Issue by gasoiline** [SiCKRAGETV/sickrage-issues#334]
I got the following error log when trying to update from http sever by clicking hyperlink "update now".
any clue? is it a right issue? I amlaunching sickrage as user transmission not root biut it used to work before I switched to Kodi.
looking inot the update script I can see that it only deals with kodi version up to 12, for greater version it fires the error message below ... is V12+ not supported?

log:
http://pastebin.com/8j2vfBXy

**Comment by fernandog** [comment]
stop SR, enter SR folder and run:

```
git reset --hard HEAD
```

then

```
git pull
```

**Comment by markheloking** [comment]
@gasoiline please use [markdown](https://guides.github.com/features/mastering-markdown/) for code snippets/small logs, and [pastebin](http://pastebin.com/) for large logs.

Please use the issue guidelines when posting an issue. This way the dev team is able to debug your problem. Don't forget to use [markdown](https://guides.github.com/features/mastering-markdown/) on any code and log you want to post in-line.

- [ ] Branch
- [ ] Commit hash
- [ ] Operating system and python version
- [x] What did you do?
- [x] What happened?
- [x] What did you expect?
- [x] Link to a copy/paste of your logfile with clear debug info of the error on PASTBIN (or in-line using [markdown](https://guides.github.com/features/mastering-markdown/) for small snippets)
