### ISSUE TITLE
[Fanart] Submit Logo for Super Écran channel Network

### ISSUE THREAD

**Issue by maxcore** [SiCKRAGETV/sickrage-issues#3343]
![super ecran](https://cloud.githubusercontent.com/assets/4043787/10556732/521fddc8-745a-11e5-9a04-0560f4c207c1.png)

Download link :https://www.dropbox.com/s/9i92c582c9zlv7y/Super%20%C3%89cran.png?dl=0

https://fr.wikipedia.org/wiki/Super_%C3%89cran

**Comment by fernandog** [comment]
@neoatomic

**Comment by neoatomic** [comment]
Sadly special characters are not supported for network logos. So `Écran isn't possible...

**Comment by maxcore** [comment]
Why Télé-Québec is approved ? i a make the logo last years and not problem with sickrage ?

**Comment by neoatomic** [comment]
@maxcore Network logos with special characters are not supported. However we implemented a hack-around to allow 3 logos with special characters, and those 3 slots are already taken. 
Probably the `Télé-Québec` is one of them.

Maybe @miigotu can think of another solution to improve the network logo system, but currently there is no solution for the special character network logos...

**Comment by maxcore** [comment]
@neoatomic 

check this : https://github.com/abeloin/SickRage/commit/a3a706dd74a1a860af4b73484665491c287b6173

**Comment by fernandog** [comment]
@maxcore try adding ecran image with è to your `SickRage/gui/slick/images/network` and see if works

**Comment by neoatomic** [comment]
@maxcore Thats indeed what i was referring to.
I see the change is for a `e` character, so with a little luck it might also work here. But you will have to test this locally on your sickrage installation.

**Comment by maxcore** [comment]
@neoatomic @fernandog  ok thx i test.

**Comment by fernandog** [comment]
@neoatomic that change was done in cheetah. we are not doing anything like that in mako

**Comment by fernandog** [comment]
@maxcore did it worked?

**Comment by maxcore** [comment]
@fernandog @neoatomic 

work -> super ecran.png with this name

![capture d ecran 2015-10-17 12 58 48](https://cloud.githubusercontent.com/assets/4043787/10560115/f175253a-74ce-11e5-8403-b4c24f0655f3.png)

**Comment by fernandog** [comment]
thanks!

**Comment by neoatomic** [comment]
@maxcore Already tested myself earlier today. And indeed the hack to convert the `é` still works.
Logo will be added with the next update.

**Comment by maxcore** [comment]
@neoatomic thx you ! ;)
