### ISSUE TITLE
Shows never get set to wanted?

### ISSUE THREAD

**Issue by TheDeathly** [SiCKRAGETV/sickrage-issues#335]
My shows arent updating from unaired to wanted even though its been well over an hour? Is there a way to change the update frequency that it checks? I have to manually click the search option for it to look for anything. :(

BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8)

**Comment by fernandog** [comment]
your SR runs 24/7? It updates everyday at 03:00AM.
Go to settings and change the "Search frequency"

**Comment by TheDeathly** [comment]
Yeah it runs on a ubuntu box. Daily search frequency is set at 15 minutes.
Is there a way to make it update at a different time than 3 AM? I use
torrents and it sucks getting it late and missing out on all the seeding.

**Comment by fernandog** [comment]
no. 
have you enabled daily and backlog searches for all your provider?

**Comment by TheDeathly** [comment]
I only use BTN and its at 720. Can i change the refresh time in the python files?

**Comment by fernandog** [comment]
no need.
mine works and my Backlog is also 720.
are you using local time or network time?

**Comment by TheDeathly** [comment]
Using network time. I didn't actually let it run till 3AM to see if it
switched from unaired to aired. I'd really rather it would update like this
(show time) + (run length) = update time. So if it runs for 40 minutes at
9PM. it would mark the show "wanted" at 9:40 and then daily searches would
start looking for it on BTN.

but I don't know how plausible that is.

**Comment by fernandog** [comment]
SR must run 24/7
you can enable the "update at startup"

**Comment by TheDeathly** [comment]
It does. It's on a ubuntu server and that's checked. I'll see what happens
tonight i guess. i can send you the .config file if you wanted.

**Comment by TheDeathly** [comment]
A weird thing i saw too is, on the "Coming Episodes" tab, it showed the episodes as "missed" in red. but still considered them unaired. restarting SB didn't mark them to aired either. I had to manually search for them to switch.

**Comment by fernandog** [comment]
if "update at startup" and "backlog search at startup" are enable everytime you start SR those unaired will become wanted.
you should keep SR runnnig 24/7.

**Comment by TheDeathly** [comment]
So If a show airs at 9PM and it isn't wanted by 10:30 I can restart SB and it should mark it as wanted?

**Comment by TheDeathly** [comment]
They are indeed checked. I know I should, but if it means updating the
shows quicker. I'll just restart it every day at 10 and 11 to get the shows
wanted. I don't want to wait till 3AM for them to update.
