### ISSUE TITLE
Client default_host not populating input field

### ISSUE THREAD

**Issue by cvockrodt** [SiCKRAGETV/sickrage-issues#336]
default_host values not being populated into host field on the Torrent Search tab in Search Settings (possibly both Torrent and NZB tabs) 
The default_host values are in \sickbeard\clients\_init_.py
Branch - Master :: Commit - 33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8

**Comment by markheloking** [comment]
Please use the issue guidelines when posting an issue. This way the dev team is able to debug your problem. Don't forget to use [markdown](https://guides.github.com/features/mastering-markdown/) on any code and log you want to post in-line.

- [x] Branch
- [x] Commit hash
- [ ] Operating system and python version
- [ ] What did you do? (in this case: what is your setup like?)
- [x] What happened?
- [ ] What did you expect?
- [x] Link to a copy/paste of your logfile with clear debug info of the error on PASTBIN (or in-line using [markdown](https://guides.github.com/features/mastering-markdown/) for small snippets)

**Comment by cvockrodt** [comment]
Hi, sorry for not fully complying with the guidelines. Here included is the rest of the information which I hope is enough information. 

I am running Windows 8.1 w/ python 2.7.8

I expect, when rtorrent is selected from the dropdown of clients, that "scgi://localhost:5000" should populate the host:port input field. The full map of default hosts are as follows:
                'utorrent': 'http://localhost:8000',
                'transmission': 'http://localhost:9091',
                'deluge': 'http://localhost:8112',
                'download_station': 'http://localhost:5000',
                'rtorrent': 'scgi://localhost:5000'
Instead, no matter what client is selected in the dropdown, "http://localhost:8000" is what populates the input field.

**Comment by fernandog** [comment]
@cvockrodt can you test this on develop branch and report back?

**Comment by cvockrodt** [comment]
@fernandog I just cloned the develop branch and tried it out. The input field is now just empty.

**Comment by abeloin** [comment]
@fernandog @cvockrodt The default_host dict is not used anywhere in the code and, looking into the git history, was like that since the first commit

**Comment by cvockrodt** [comment]
@abeloin Yeah I never said it used to work, just saying if we have a default_host dict, we should be using it right?

**Comment by abeloin** [comment]
@cvockrodt Yes and no ;) meaning I would recommend removing the code from __init__.py and use it in config_search.tmpl instead.

**Comment by fernandog** [comment]
@abeloin @cvockrodt what should we do to fix it?

**Comment by abeloin** [comment]
@fernandog This should be a classified as improvement. It would require adding default value for host field depending on the selected client.

**Comment by abeloin** [comment]
@fernandog Forgot to mention I'm waiting for the rtorrent pull request to be merge before doing any changes as it will modify config_search.tmpl which is also modified by the pull request.

**Comment by abeloin** [comment]
Added pull request even if rtorrent's pull request is not merge.

**Comment by cvockrodt** [comment]
So looking at that pull request, it seems like you've added the correct host:ports but only to the description that shows below the input field. Am I crazy?

**Comment by fernandog** [comment]
@cvockrodt what did you expect?

**Comment by abeloin** [comment]
@cvockrodt Yes, I only added them as a description. I thought about it and I think it is better to force the user to enter the url and show an error if empty than, to autofill and get connection failed error in the log. 

It doesn't show an error yet but it will with searchProviders/searchSetting overhaul patch I'll submit later.

**Comment by fernandog** [comment]
@cvockrodt develop updated. please test and report back
