### ISSUE TITLE
[Feature Request] Add put.io client support

### ISSUE THREAD

**Issue by cvockrodt** [SiCKRAGETV/sickrage-issues#337]
Add put.io as a torrent client in SR. I would like for SickRage to automatically upload torrents to my put.io account. There is an Oauth API available at https://put.io/v2/docs/files.html#upload

Branch: Master && Commit: 33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8

**Comment by cvockrodt** [comment]
I've noticed that Couchpotato has put.io functionality, but looking at the .py files, it doesn't seem trivial to copy their implementation. It does seem doable though.. I'm hoping there's someone out there that has worked on both projects that might be able to make sense of it.

**Comment by OmgImAlexis** [comment]
@fernandog Where would I be looking to try and add this in?

**Comment by cvockrodt** [comment]
in /sickbeard/clients/ there are .py files for each client (utorrent, transmission, etc.) so I think the meat of the put.io client stuff should also go there. 

For reference, and I know couchpotato is a little different, but here is couchpotato's main.py for put.io
https://github.com/RuudBurger/CouchPotatoServer/blob/master/couchpotato/core/downloaders/putio/main.py

**Comment by krash1220** [comment]
I would so love it if it was possible. I only use put.io now and I have to manually upload and download all my shows. I used nzb's for awhile but half of even the current shows there were too many files missing. I don't have that problem with torrents. I would even more money for this feature. It would make getting my shows so much easier.

**Comment by cvockrodt** [comment]
@krash1220 in the meantime, I've written a simple .vbs script that seems to work fine. It uses curl to upload to put.io using your oauth key. https://github.com/cvockrodt/put.io-uploader

There's a little bit of setup but if you can get sickrage running i'm sure you'll have no problem. 

Also you can use a download manager to automatically download your files to your computer. 

I still want put.io integration in sickrage, but for now, this has been working for me. Now if put.io only supported labels...

**Comment by krash1220** [comment]
Thank you, cvockrodt but I'm using linux mint, I don't even have windows installed anymore. But it's a great idea. Maybe someone could make a linux script?

**Comment by cvockrodt** [comment]
If mint has watch (a command line util), you could write the same script in fewer lines and less headache in a different language (sh, bash, python, etc.). It'd probably take 5 minutes.

**Comment by krash1220** [comment]
I'm sure mint does have some kind of watch command, I don't have a problem using terminal commands but I'm not good at making scripts. I'm going to see what I can find on the internet. Thank you for your help.

**Comment by krash1220** [comment]
cvockrodt,I just got a laptop with windows 8 on it and I have tried to get your uploader script to work but the log file is always empty. I installed curl and put it in the systems folder but I was getting errors so I put it the directory with your script and it runs but like I said the log file is empty. What am I doing wrong? This is driving me crazy because I really want to be able to upload my torrents without having to upload every single one manually.

**Comment by krash1220** [comment]
okay it did start working but it didn't upload the torrent file to my put.io account?

**Comment by abeloin** [comment]
Please refrain from using this thread for @cvockrodt client support. Post an issue here: https://github.com/cvockrodt/put.io-uploader

**Comment by WebSpider** [comment]
I'm looking at put.io and if we can implement this, and I am a bit curious: How would we detect from put.io that a download has finished, so we can postprocess ?

**Comment by miigotu** [comment]
@WebSpider Ive been given a put.io account by put.io admin, and there is a python library that handles sync. My plan is to start with just a "client" that sends it to put.io, and we can flesh it out after that part works.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
