### ISSUE TITLE
OSX 10.11 rar executable not found

### ISSUE THREAD

**Issue by phirestalker** [SiCKRAGETV/sickrage-issues#3378]
branch: master
commit 65515c5cf7b3468e15b5f3a3d9a1fd603ba4dafb
OSX 10.11
Python 2.7.10
What I did:
	I checked the box to unpack on the post processing settings page.
What Happened:
	It gave the error “rar executable not found”
What I expected:
	not that
How to reproduce:
	just click the box

Log: https://gist.github.com/94fab9cf76588dc18d25.git

I have installed "UNRAR 5.30 beta 5 freeware      Copyright (c) 1993-2015 Alexander Roshal" in /usr/local/bin. I am unable to add any files to /usr/bin as the new version of osx forbids it even for the root user.

**Comment by miigotu** [comment]
It doesnt need to be in /usr/bin. It just needs to be in your path.

**Comment by phirestalker** [comment]
Still doesn't work
it is in the path

**Comment by miigotu** [comment]
`ls -l /usr/local/bin/rar`
`ls -l /usr/local/bin/unrar`

Try searching the issues about El Capitan and the solution.

**Comment by phirestalker** [comment]
$ ls -l /usr/local/bin/unrar
-rwxr-xr-x  1 root  wheel  318380 Oct 11 15:19 /usr/local/bin/unrar
$ ls -l /usr/local/bin/rar
-rwxr-xr-x  1 root  wheel  570952 Oct 11 15:19 /usr/local/bin/rar

I tried searching the forums for unrar and here, but I will try searching for el capitan
