### ISSUE TITLE
unable to change episodes from skipped to downloaded ect.

### ISSUE THREAD

**Issue by chrism2014** [SiCKRAGETV/sickrage-issues#338]
BRANCH: (develop) / COMMIT: (8b84e4f4bc6cdebdc605438e9e75d15f1133d65e) 
PYTHON VERSION 2.6.5 (r265:79063, Sep 26 2013, 18:48:04) [GCC 4.4.3]
OS ubuntu 10.04

pastebin http://pastebin.com/iptJ4uin

i am unabe to change the status of episodes from skipped to downloaded ect.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/285
