### ISSUE TITLE
[Feature Request] Add support for Subscene.com

### ISSUE THREAD

**Issue by spirro** [SiCKRAGETV/sickrage-issues#339]
I'd love to add subtitle support using Subscene.com. I tend to find this more reliable than others, such as opensubtitles.org.

**Comment by vipkid** [comment]
I also support this feature request, much more accurate for subtitles.

**Comment by markheloking** [comment]
There is also the possibility to search for subtitles using hash/md5. I'm unsure whether this is already the used method and whether or not the different providers have capabilities for this.

**Comment by dmarcelino** [comment]
:+1: for Subscene.com

**Comment by bitzorro** [comment]
+1 for subscene.com

**Comment by dmarcelino** [comment]
I believe SickRAGE uses subliminal for downloading subtitles, so I've created the issue Diaoul/subliminal#431 on subliminal's repo. Fingers crossed.

**Comment by neoatomic** [comment]
Glad to say that this week we updated subliminal to newest version 0.8.
This should bring a substantial improvement over the older version we where using.

However to allow easier updating in the future we decided to not modify the original subliminal code anymore.
In short that means that we wont be add any new subtitle providers our-selfs.
So if you still would like this provider added, than please post the request directly for the subliminal developers at. : https://github.com/Diaoul/subliminal
If its added in subliminal it will automatically be added to SickRage to. :)
