### ISSUE TITLE
[Feature Request] Add option to export shows/episodes list.

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#34]
<a href="https://github.com/chqp"><img src="https://avatars.githubusercontent.com/u/9638994?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [chqp](https://github.com/chqp)**
_Wednesday Dec 03, 2014 at 10:00 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/1014 (3 comment(s))_

----

a simple text/pdf export option (shows, #episodes, etc...) with a few column filters might be helpful sometimes and would be rather easy to realize compared to other issues.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
