### ISSUE TITLE
Unrar Failure- manual postprocessing

### ISSUE THREAD

**Issue by BKSteve** [SiCKRAGETV/sickrage-issues#340]
When unpacking TV Packs with Manual Post Processing there are sometimes errors in the unrar process. It seems like the file is moved in it's partially extracted form, or the parts are deleted before complete extraction and then whatever is the result is moved to the show directory and renamed to the proper series file name. But this is a guess.
If I unrar the episode manually from my DSM Filemanager it extracts correctly.
The following error and debug log are for information, the fault is not easily reproducible.

Error:
```
2015-01-05 17:26:30 ERROR    Thread-29 :: Failed Unrar archive resurrection.us.s01e06.dvdrip.x264-demand.rar: 
2015-01-05 17:26:13 ERROR    Thread-29 :: Failed Unrar archive resurrection.us.s01e04.dvdrip.x264-demand.rar:
```

Debug Log:
http://pastebin.com/DEqnig7i

SR Version: 	BRANCH: (develop) / COMMIT: (8b84e4f4bc6cdebdc605438e9e75d15f1133d65e)
SR Config file:	/usr/local/sickbeard-custom/var/config.ini
Python Version:	2.7.8 (default, Dec 12 2014, 21:20:40)

Update:
SR is running on Synology DS412+ with DSM 5.1-5021 Update 2.
additional info: The TV Pack is downloaded into a main directory, sub dir for series name, and with it's multiple episodes in sub-subdirs, these contain the rar parts. This main directory is then selected in manual post processing and executed.

**Comment by markheloking** [comment]
Please use the issue guidelines when posting an issue. This way the dev team is able to debug your problem. Don't forget to use [markdown](https://guides.github.com/features/mastering-markdown/) on any code and log you want to post in-line.

- [x] Branch
- [x] Commit hash
- [ ] Operating system and python version
- [ ] What did you do?
- [x] What happened?
- [x] What did you expect?
- [x] Link to a copy/paste of your logfile with clear debug info of the error on [pastebin](http://pastebin.com/) (or in-line using [markdown](https://guides.github.com/features/mastering-markdown/) for small snippets)

Please use [markdown](https://guides.github.com/features/mastering-markdown/) for small snipets of log only. Full logs always go on [pastebin](pastebin.com)

**Comment by markheloking** [comment]
Please also note that the dev is on vacation, so fixes take longer than expected.

**Comment by BKSteve** [comment]
Firstly - Everyone deserves and needs vacation time and I truly appreciate the dev's efforts and I hope is enjoying the break.

Second - This error is easily worked around by unrar-ing the episodes manually or by simple batch before post processing.

**Comment by markheloking** [comment]
That's why I marked it low priority, seeing as there are more troubling bugs in the tracker right now.

**Comment by fernandog** [comment]
@BKSteve did you try develop branch?

**Comment by fernandog** [comment]
when reply, will reopen
