### ISSUE TITLE
Incorrect path to github repo in Qnap .qpkg

### ISSUE THREAD

**Issue by bertenvdb** [SiCKRAGETV/sickrage-issues#341]
A couple of weeks ago, the dev branch was becoming pretty unusable (to me) because of a number of bugs. So I switched back to master in settings, restarted and ... ended up with no SickRage at all. It just won't start anymore.

So I removed SickRage from my QNAP nas through the web gui. After a lot of searching I found just one link to a Qnap .qpkg file. It's in the SR faq and points to a dropbox file. https://sickrage.tv/forums/forum/help-support/frequently-asked-questions-faq/1288-frequently-asked-questions-answered
Unfortunately, the file is from june 2014 and still uses echel0n/SickRage instead of the new SICKRAGETV/SickRage. 

This appears in my QNAP log: 
>SickBeard-TVRage 140428 installation failed. Could not git clone git://github.com/echel0n/SickBeard-TVRage.git

So can someone please create a new package?

**Comment by Tlabok** [comment]
http://forum.qnap.com/viewtopic.php?f=223&t=35015
This contains links to the most recent qpkg.

**Comment by neoatomic** [comment]
Currently there are no official SickRage packages.
You need to manually install SickRage, or request the developer op that unofficial package to compile a new one.

**Comment by bertenvdb** [comment]
Manual install gave me so many errors I didn't even bother exploring that option any further. 
I'm having exams the next 2 weeks, so I guess I'll have to try to live a few weeks or so without SR. It's just now SR is (temporarily) gone for me that I realise how much it means to me ... :-)

**Comment by Tlabok** [comment]
Not sure what to make of this info. I am running the current version just fine using the qpkg I refered to earlier.

**Comment by bertenvdb** [comment]
You're absolutely right @Tlabok!
I searched the Qnap Forums and only found SickBeard and didn't properly read the topic.
Following your link I now have SR finally up and running again. Thanks!
