### ISSUE TITLE
[Feature Request] Add italiansubs.net 

### ISSUE THREAD

**Issue by t3rm1nal** [SiCKRAGETV/sickrage-issues#342]
https://sickrage.tv/forums/forum/help-support/general-support/61-web-scraper-for-itasa

as old thread...I repost here :)

hope someone can do something for this...

**Comment by markheloking** [comment]
Please post relevant info from the thread instead of just a link (no extra unnecessary work for the busy developers). From the link provided:

@t3rm1nal on 05-06-2014, 07:26 AM
> A "standard" account can download the same file for 10 times. So you (developer) should ask for itasa api access. They have a lot of external services that use theirs api.

@echel0n on 11-20-2014, 01:50 AM
> Ok I will request API access and see if we can't put this issue to bed

**Comment by neoatomic** [comment]
@t3rm1nal 
Glad to say that this week we updated subliminal to newest version 0.8.
This should bring a substantial improvement over the older version we where using.

However to allow easier updating in the future we decided to not modify the original subliminal code anymore.
In short that means that we wont be add any new subtitle providers our-selfs.
So if you still would like this provider added, than please post the request directly for the subliminal developers at. : https://github.com/Diaoul/subliminal
If its added in subliminal it will automatically be added to SickRage to. :)
