### ISSUE TITLE
Per show email notification don't save emails to DB.

### ISSUE THREAD

**Issue by CoRpO** [SiCKRAGETV/sickrage-issues#347]
BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8) 

Sickrage is missing the needed code to save the emails the Show notification list.
Code correctly loads what's in the DB when changing show, sending the emails is also working but the UI miss the logic to save what's inputed.

(I've written the missing code, on my way to make a pull request)

**Comment by fernandog** [comment]
@CoRpO are you going to do a PR to develop branch? thanks

**Comment by CoRpO** [comment]
Yes I'm going to do it soon

**Comment by fernandog** [comment]
@CoRpO did you PR to develop branch?

**Comment by CoRpO** [comment]
@fernandog yes, and it has been merged since : https://github.com/SiCKRAGETV/SickRage/pull/1174
