### ISSUE TITLE
Path with accents are unproperly supported

### ISSUE THREAD

**Issue by trebonius2** [SiCKRAGETV/sickrage-issues#348]
D:\Vidéos\ ... will be transformed in D:\VidÃ©os, and then the search in the folder is not properly working.

**Comment by markheloking** [comment]
Please use the issue guidelines when posting an issue. This way the dev team is able to debug your problem. Don't forget to use [markdown](https://guides.github.com/features/mastering-markdown/) on any code and log you want to post in-line.

- [ ] Branch
- [ ] Commit hash
- [ ] Operating system and python version
- [x] What did you do?
- [x] What happened?
- [x] What did you expect?
- [ ] Link to a copy/paste of your logfile with clear debug info of the error on [pastebin](http://pastebin.com/) (or in-line using [markdown](https://guides.github.com/features/mastering-markdown/) for small snippets)

**Comment by fernandog** [comment]
@trebonius2 please set your OS language to UTF-8

**Comment by abeloin** [comment]
PR https://github.com/SiCKRAGETV/SickRage/pull/1385 and https://github.com/SiCKRAGETV/SickRage/pull/1387 and https://github.com/SiCKRAGETV/SickRage/pull/1388 should help resolve this issue
