### ISSUE TITLE
Manage Torrents redirects to wrong IP adress

### ISSUE THREAD

**Issue by gielie** [SiCKRAGETV/sickrage-issues#349]
BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8) 
Python Version:	2.7.8 (default, Dec 12 2014, 21:57:17) 
OS= Synology NAS 415play

When you want to Manage Torrents from whitin SR it redirects to an Internal (192) ip adres. If you are on your own network it works fine but outside your network it doesnt. 
It should redirect to the adress youre using at that time.

**Comment by gielie** [comment]
i found out that it uses the setting from the torrent app, if i set this to the adress used form the outside instead of localhost it works.

**Comment by markheloking** [comment]
There was already an issue posted for this if I remember correctly, though I'm unable to find it right now. @fernandog?

Please use the issue guidelines when posting an issue. This way the dev team is able to debug your problem. Don't forget to use [markdown](https://guides.github.com/features/mastering-markdown/) on any code and log you want to post in-line.

- [ ] Branch
- [ ] Commit hash
- [ ] Operating system and python version
- [x] What did you do?
- [x] What happened?
- [x] What did you expect?
- [ ] Link to a copy/paste of your logfile with clear debug info of the error on [pastebin](http://pastebin.com/) (or in-line using [markdown](https://guides.github.com/features/mastering-markdown/) for small snippets)

**Comment by fernandog** [comment]
@gielie as an alternative edit your config.ini file and add your external ip or dyndns info to locahost_ip

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/205

**Comment by raymondtrueman** [comment]
I would also love to have this resolved. 
@fernandog, @gielie did provide all the info needed in his post. There is no log paste needed because there is no error. A solution is required to make the "Manage Torrent" function work outside a users local network. I believe you can remove the "More Info Needed" tag. Unless a developer has a specific question

**Comment by raymondtrueman** [comment]
I would love to have this resolved as well

**Comment by fernandog** [comment]
@raymondtrueman as an alternative edit your config.ini file and add your external ip or dyndns info to locahost_ip.
this will only work if you don't use reverse proxy

**Comment by fernandog** [comment]
@abeloin do you think use javascript to get the location.host when remote access and compare with webui_url hostname si if' location.host not in webui_url then then use location.host. With this when remote access you can view "manage torrents". It's there a better solution?

**Comment by abeloin** [comment]
@fernandog Can he simply change is TORRENT_HOST to a dynamicdns name?

**Comment by fernandog** [comment]
@abeloin but when you local access there's no point to use dynamicdns. just for remote. that's why my idea is to get the location.host. we can know if is remote or not.

**Comment by abeloin** [comment]
@fernandog Try this, I didn't test it but it should work
```
<script type="text/javascript" charset="utf-8">
<!--
var originalUrl = $('#extFrame').prop('src')
a = document.createElement('a');
a.href = originalUrl
var newUrl = window.location.protocol + "//" + window.location.host + a.pathname + a.search
$('#extFrame').prop('src', newUrl)
//-->
</script>
```

By the any decent consumer router in the last 5 years can do SNAT, DNAT on the packet so it doesn't get out onto the internet(Because the router is intelligent enough to see the packet destination is for himself).

**Comment by fernandog** [comment]
@abeloin will this work with user/pass in the URL?

**Comment by abeloin** [comment]
No it won't you'll have to substring it from originalUrl

**Comment by abeloin** [comment]
Redone it using a regex:
```
<script type="text/javascript" charset="utf-8">
<!--
$(document).ready(function () {
	var parse_url = /^(?:([A-Za-z]+):)?(\/{0,3})(([0-9.\-A-Za-z]+):([0-9.\-A-Za-z]+)\@)?([0-9.\-A-Za-z]+)(?::(\d+))?(?:\/([^?#]*))?(?:\?([^#]*))?(?:#(.*))?$/;
	var originalUrl = $('#extFrame').prop('src')
	var result = parse_url.exec(originalUrl);

	var newUrl = window.location.protocol + "//";

	// Do we have a user:pass@?
	if (result[3] !== undefined) {
		newUrl += result[3];
	}
	newUrl += window.location.host + "/"

	// Do we have a path?
	if (result[8] !== undefined) {
		newUrl += result[8];
	}

	// Do we have parameter?
	if (result[9] !== undefined) {
		newUrl += result[9];
	}
	$('#extFrame').prop('src', newUrl)
	document.getElementById('FrameID').contentWindow.location.reload(true);
});
//-->
</script>
```

**Comment by fernandog** [comment]
@raymondtrueman are you on linux?

 can you try this commit ?

stop SR,
SSH
enter SickRage directory
wget --no-check-certificate https://github.com/SiCKRAGETV/SickRage/pull/1413.patch
patch -p1 <1413.patch
start SR
test

**Comment by raymondtrueman** [comment]
@fernandog I tried it on my Synology NAS but it seems it doesnt support the patch command or Im doing it wrong...

/volume1/@appstore/sickbeard-custom/var/SickBeard$ patch -p1 <1413.patch
/bin/sh: patch: not found

**Comment by fernandog** [comment]
try: 
/usr/bin/patch

**Comment by raymondtrueman** [comment]
Nope, still not

**Comment by raymondtrueman** [comment]
@fernandog  Ok, so I guess you discarded the changes you made and this won't get fixed?

**Comment by fernandog** [comment]
Security issues. Will be removed in the future this feature
