### ISSUE TITLE
[Feature Request] Add multi language download support

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#35]
<a href="https://github.com/chqp"><img src="https://avatars.githubusercontent.com/u/9638994?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [chqp](https://github.com/chqp)**
_Wednesday Dec 03, 2014 at 10:13 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/1015 (2 comment(s))_

----

some shows are known to be hard to understand in the original language and it's a different experience if you have to read subtitles. So since language skills can be very different at home, it would be helpful to allow to define at least a secondary language SR should try to download additionally.

primary language = the setting already in place
secondary language = to define in case you think it is going to be needed. (i don't know if anyone would need more than 2 languages but i guess so.)

Another aspect:
this way, the problem of missing episodes would also be relieved further. unlike in the suggestion above (where you want ALL episodes in 2 or more languages), you could set language priorities for just one complete set of episodes too. 
ie: In case SR doesn't find some episodes in the primary language, it could try to find and download them in another language you understand. (thats better than not having the episode at all)

**Comment by Xexiz** [comment]
Yes, I second the Feature Request. It would be great to be able to download a serie in 2 languages (English for me, French for my family). Might be a bit tricky though since French torrent most of the time require share ratio (t411).

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!

**Comment by Xexiz** [comment]
Thanks for letting me know. I just did :+1: 
http://feathub.com/SiCKRAGETV/SickRage/+54
