### ISSUE TITLE
Thread-116 :: Error getting html for dognzb.cr

### ISSUE THREAD

**Issue by quipe** [SiCKRAGETV/sickrage-issues#350]
I see this error in de log when trying to add categories for dognzb. As a result no categories are listed in the configuration page of Newznab provider dognzb.

This results in SickRage not able to perform a search on dognzb since it sends an empty category list ( &cat= ) in the search URL which returns a 'missing parameter' error. 
Eg.: 

```python

SEARCHQUEUE-RETRY-270633 :: [DOGNzb] :: Search url: https://api.dognzb.cr/api?apikey=*****&season=1&maxage=900&cat=&q=NAME_HERE&limit=100&attrs=rageid&offset=0&ep=3&t=tvsearch

```

When executing a curl on the commandline of the system which is running sickrage I do get a proper XML returned by  the same URL:

```xml
xxxxx@homeserver:~$ curl "https://api.dognzb.cr//api?apikey=xxxxx&t=caps"
<?xml version="1.0" encoding="utf-8" ?> 
			<caps>
			  <!-- server information -->
			  <server appversion="0.2.3p" version="0.1" title="DOGnzb" email="noreply@dognzb.cr" url="http://dognzb.cr/" />
			  <limits max="100" default="100" />
			  <retention days="2283" />
			  <searching>
				  <search available="yes" />
				  <tv-search available="yes" />
				  <movie-search available="yes" />
				  <audio-search available="yes" />
			  </searching>
		
			  <categories>
				
						 <category id="5000" name="TV">
							<subcat id="5020" name="Foreign" />
							<subcat id="5030" name="SD" />
							<subcat id="5040".............
```

[https://api.dognzb.cr//api?apikey=xxxxx&t=caps]

**Comment by markheloking** [comment]
Please use the issue guidelines when posting an issue. This way the dev team is able to debug your problem. Don't forget to use [markdown](https://guides.github.com/features/mastering-markdown/) on any code and log you want to post in-line.

- [ ] Branch
- [ ] Commit hash
- [ ] Operating system and python version
- [x] What did you do?
- [x] What happened?
- [x] What did you expect?
- [x] Link to a copy/paste of your logfile with clear debug info of the error on [pastebin](http://pastebin.com/) (or in-line using [markdown](https://guides.github.com/features/mastering-markdown/) for small snippets)

Please use markdown instead of bbcode/whatever system (don't use `<code>`).

**Comment by quipe** [comment]
Sorry, overlooked that one

SickRage version: BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8) 
Phyton version: 2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]
OS: Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-43-generic x86_64)

**Comment by fernandog** [comment]
@quipe did you try to edit the provider and select the category?


![category](https://cloud.githubusercontent.com/assets/2620870/5685524/1fe561f8-9822-11e4-98f4-2ff234197db4.png)

**Comment by quipe** [comment]
I did, only mine looked like this:

![schermafbeelding 2015-01-10 om 13 21 04](https://cloud.githubusercontent.com/assets/10433210/5691538/e87edca8-98cb-11e4-981b-7703d905101c.png)

So no categories listed.

I thought maybe the problem may be the double slash in the caps URL. So I edited the URL in the config.ini file by hand since the extra slash seems to be added by sickrage. After that, restarted sickrage for the changes to take effect and voila the two categories from your screencap were also listed in my config. Now the query URL is also performed correct, with categories.

The strange thing is that the double slashes are back after making a random change in the config, but the 2 categories kept being shown in my config.

Still getting the

```
Thread-116 :: Error getting html for [https://api.dognzb.cr//api?apikey=xxxxx&t=caps]
```

in the log but doesn't seem to cause a problem anymore. But I am not sure what has fixed the empty categories list.

**Comment by fernandog** [comment]
@quipe try add only https://api.dognzb.cr to the URL (without the slash) because SR already add it.

**Comment by quipe** [comment]
Already did that. Still ends up with the double slash in the log. Looks like SR adds a slash to https://api.dognzb.cr as wel as to the api/... suffix part

**Comment by fernandog** [comment]
@quipe strange thing is that with nzbgeek works.

**Comment by cytec** [comment]
i have a temp fix for that now but had to change a lot of settings and request json as output format which afaik isn't supported by all indexers atm...

so i gonna have a deeper look again if i got some more time

**Comment by fernandog** [comment]
@quipe categories problem was fixed on DEVELOP branch. please test and report back
