### ISSUE TITLE
Quality settings missing 720p HDTV

### ISSUE THREAD

**Issue by halmmar** [SiCKRAGETV/sickrage-issues#351]
According to [Quality-Settings](https://github.com/SiCKRAGETV/SickRage/wiki/Quality-Settings), "HDTV" means "720p" or "hr.ws.pdtv.x264". But when searching for torrents, entries like "Show.S00E00.HDTV.x264-GROUP.mp4" are matched and downloaded. These are 480p re-encodings.

I would have set my custom filter to contain 720p or 1080p, but it needs to match all given words so that does not work to force only HDTV and not 480p files as is common at the moment. A minimum file size would also have been an acceptable filter as that gets rid of matching iphone rips, etc.

**Comment by markheloking** [comment]
Please use the issue guidelines when posting an issue. This way the dev team is able to debug your problem. Don't forget to use [markdown](https://guides.github.com/features/mastering-markdown/) on any code and log you want to post in-line.

- [ ] Branch
- [ ] Commit hash
- [ ] Operating system and python version
- [ ] What did you do?
- [ ] What happened?
- [ ] What did you expect?
- [ ] Link to a copy/paste of your logfile with clear debug info of the error on [pastebin](http://pastebin.com/) (or in-line using [markdown](https://guides.github.com/features/mastering-markdown/) for small snippets)

You are stating the feature, just as mentioned on the wiki page. What is the problem you're experiencing?

**Comment by halmmar** [comment]
Branch: master
Commit: 33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8
OS: Ubuntu 14.10, Python 2.7.6

Upon further inspection, there simply seems to be a bug when selecting which torrent to download.
I get the message in the notifications that a torrent with name ...720p... has been snatched.

However, the magnet link sent to the client is a torrent that the log says was unwanted and was supposed to be filtered out (no 720p in the name; the magnet link in the log is correct, but is not the one sent to transmission).

So, it seems the bug just triggers when there is an acceptable torrent and another one of unacceptable quality. The email sent to me says it snatched an HD TV torrent, but once downloaded decides it is unknown or SD TV.

The log-file seems to have been rotated out though. I will see if I can find this happening again.

**Comment by halmmar** [comment]
Snipped log:
```
2015-01-10 10:15:19 :: Converted parsed result X-3x01-720p-HDTV-x264 ...
2015-01-10 10:15:19 :: Converted parsed result X-3x01-HDTV-x264 ...
2015-01-10 10:30:26 :: Picked X-720p-HDTV-x264 as the best
2015-01-10 10:30:26 :: Transmission: Response to POST request ... X-3x01-HDTV-x264
```

**Comment by fernandog** [comment]
@halmmar what provider are you using?

**Comment by halmmar** [comment]
TPB and KA. Happens with both, but TPB more often than KA.

**Comment by fernandog** [comment]
@halmmar TPB it's not supported anymore.have you changed the code of the tpb file?

**Comment by halmmar** [comment]
No, I am simply using the stock master branch. The TPB plugin uses oldpiratebay.org. Anyway, the same error occurs for KA. Or are you saying having TPB enabled causes other providers to behave badly?
Why is the plugin not disabled on the master branch if it is known to be behaving badly?

**Comment by fernandog** [comment]
because it was merged without proper testing.

KAT is working.
please send full logs as requested otherwise issue will kept closed.
