### ISSUE TITLE
[APP SUBMITTED]: year=1 is before 1900; the datetime strftime() methods require year >= 1900

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#3512]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-31-generic-i686-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@9e455a9d148bc36d727fb518c02c85558be628c1
No Log available with ERRORS: 
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
No log, and no clue what you did to cause this error.

**Comment by rjohnsen65** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-i686-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@57b043be95f462fa39296de970e0070d6307455d
Link to Log: https://gist.github.com/5d130ea16d66f9b818b8
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rjohnsen65** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-i686-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@57b043be95f462fa39296de970e0070d6307455d
Link to Log: https://gist.github.com/4ce4d4c1f2f58fe80fb5
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rjohnsen65** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-i686-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@57b043be95f462fa39296de970e0070d6307455d
Link to Log: https://gist.github.com/4969db6542342eda37d4
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rjohnsen65** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-i686-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@57b043be95f462fa39296de970e0070d6307455d
Link to Log: https://gist.github.com/8309e8b7515907d8f2bf
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rjohnsen65** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-i686-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@57b043be95f462fa39296de970e0070d6307455d
Link to Log: https://gist.github.com/177045835ce858a37f74
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rjohnsen65** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-i686-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@57b043be95f462fa39296de970e0070d6307455d
Link to Log: https://gist.github.com/c11b06521fd24155a08c
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rjohnsen65** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-i686-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@57b043be95f462fa39296de970e0070d6307455d
Link to Log: https://gist.github.com/b910e20e07309ba3de2e
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rjohnsen65** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-i686-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@57b043be95f462fa39296de970e0070d6307455d
Link to Log: https://gist.github.com/5fa872775f311794d0de
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rjohnsen65** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-i686-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@57b043be95f462fa39296de970e0070d6307455d
Link to Log: https://gist.github.com/580bf850efe13bcb4fa8
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rjohnsen65** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-i686-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@57b043be95f462fa39296de970e0070d6307455d
Link to Log: https://gist.github.com/05192e916fd2a06e83a7
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rjohnsen65** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-i686-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@57b043be95f462fa39296de970e0070d6307455d
Link to Log: https://gist.github.com/8e94dbba874a5f5a7daa
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rjohnsen65** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-i686-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@57b043be95f462fa39296de970e0070d6307455d
Link to Log: https://gist.github.com/a0f231aa57bf897a8cfc
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rjohnsen65** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-i686-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@57b043be95f462fa39296de970e0070d6307455d
Link to Log: https://gist.github.com/dbe119ecda68bb5f2d97
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rjohnsen65** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-i686-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@57b043be95f462fa39296de970e0070d6307455d
Link to Log: https://gist.github.com/398ed78be67b17661070
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rjohnsen65** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-i686-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@57b043be95f462fa39296de970e0070d6307455d
Link to Log: https://gist.github.com/9f9cb9b1673ab7e374c8
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rjohnsen65** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-i686-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@57b043be95f462fa39296de970e0070d6307455d
Link to Log: https://gist.github.com/d474c24cd2a83bdfc3eb
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rjohnsen65** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-i686-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@57b043be95f462fa39296de970e0070d6307455d
Link to Log: https://gist.github.com/e587dac8c9c033a1232b
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rjohnsen65** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-i686-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@57b043be95f462fa39296de970e0070d6307455d
Link to Log: https://gist.github.com/9ecdbbfe5b591015964c
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rjohnsen65** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-i686-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@57b043be95f462fa39296de970e0070d6307455d
Link to Log: https://gist.github.com/0b9f6c814c01ad4967b1
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rjohnsen65** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-i686-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@57b043be95f462fa39296de970e0070d6307455d
Link to Log: https://gist.github.com/e995c2a3221e022a8fe5
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by duramato** [comment]
@rjohnsen65 do you know how that error happened?

**Comment by fernandog** [comment]
@MGaetan89

**Comment by juju35** [comment]
### INFO
Python Version: **2.7.10 (default, Oct 14 2015, 16:09:02) [GCC 5.2.1 20151010]**
Operating System: **Linux-4.2.0-16-generic-x86_64-with-Ubuntu-15.10-wily**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@57b043be95f462fa39296de970e0070d6307455d
Link to Log: https://gist.github.com/e881808bd496b7d962e1
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by juju35** [comment]
### INFO
Python Version: **2.7.10 (default, Oct 14 2015, 16:09:02) [GCC 5.2.1 20151010]**
Operating System: **Linux-4.2.0-16-generic-x86_64-with-Ubuntu-15.10-wily**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@57b043be95f462fa39296de970e0070d6307455d
Link to Log: https://gist.github.com/9e0eeb34e8e77a6cee4f
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by juju35** [comment]
### INFO
Python Version: **2.7.10 (default, Oct 14 2015, 16:09:02) [GCC 5.2.1 20151010]**
Operating System: **Linux-4.2.0-16-generic-x86_64-with-Ubuntu-15.10-wily**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@57b043be95f462fa39296de970e0070d6307455d
Link to Log: https://gist.github.com/f8ca4e336abd08125d68
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by juju35** [comment]
### INFO
Python Version: **2.7.10 (default, Oct 14 2015, 16:09:02) [GCC 5.2.1 20151010]**
Operating System: **Linux-4.2.0-16-generic-x86_64-with-Ubuntu-15.10-wily**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@57b043be95f462fa39296de970e0070d6307455d
Link to Log: https://gist.github.com/bdecf222f21da18f31c2
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by juju35** [comment]
### INFO
Python Version: **2.7.10 (default, Oct 14 2015, 16:09:02) [GCC 5.2.1 20151010]**
Operating System: **Linux-4.2.0-16-generic-x86_64-with-Ubuntu-15.10-wily**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@57b043be95f462fa39296de970e0070d6307455d
Link to Log: https://gist.github.com/f93046cab97f45336e34
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by juju35** [comment]
### INFO
Python Version: **2.7.10 (default, Oct 14 2015, 16:09:02) [GCC 5.2.1 20151010]**
Operating System: **Linux-4.2.0-16-generic-x86_64-with-Ubuntu-15.10-wily**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@57b043be95f462fa39296de970e0070d6307455d
Link to Log: https://gist.github.com/21a1a9f675891a23f78e
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Ok so I know what this one is from xD. This exception was always happening but was being swallowed due the the return being inside of the finally. I fixed it so that it WOULD throw in the case of an exception, because it was the source of some of our "hidden" bugs.

http://grokbase.com/t/python/python-ideas/097hhg7ecp/make-return-inside-a-finally-a-syntaxerror

I will look into how to fix this newly exposed problem properly.

**Comment by juju35** [comment]
### INFO
Python Version: **2.7.10 (default, Oct 14 2015, 16:09:02) [GCC 5.2.1 20151010]**
Operating System: **Linux-4.2.0-16-generic-x86_64-with-Ubuntu-15.10-wily**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@503153272dfc0903b764a76d8bcfa989ba283a9f
Link to Log: https://gist.github.com/41da4ea5528ef6b5c7b3
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by juju35** [comment]
### INFO
Python Version: **2.7.10 (default, Oct 14 2015, 16:09:02) [GCC 5.2.1 20151010]**
Operating System: **Linux-4.2.0-16-generic-x86_64-with-Ubuntu-15.10-wily**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@503153272dfc0903b764a76d8bcfa989ba283a9f
Link to Log: https://gist.github.com/38d7c1a7caaf4ac87e8e
### ERROR
```
TORNADO :: API :: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
