### ISSUE TITLE
Long snatchtime after release

### ISSUE THREAD

**Issue by zaffe86** [SiCKRAGETV/sickrage-issues#352]
Is there a reason why my episodes don't get snatched and downloaded 2-3 hours after they have been released on example torrentleech? I have daily search frequency set at 11 mins and still the episodes is released say 2 am, and gets snatched like 5 am?

**Comment by markheloking** [comment]
Please use the issue guidelines when posting an issue. This way the dev team is able to debug your problem. Don't forget to use [markdown](https://guides.github.com/features/mastering-markdown/) on any code and log you want to post in-line.

- [ ] Branch
- [ ] Commit hash
- [ ] Operating system and python version
- [x] What did you do?
- [x] What happened?
- [x] What did you expect?
- [ ] Link to a copy/paste of your logfile with clear debug info of the error on [pastebin](http://pastebin.com/) (or in-line using [markdown](https://guides.github.com/features/mastering-markdown/) for small snippets)

**Comment by zaffe86** [comment]
python version 2.7.8 (default, Dec 12 2014, 21:04:21) [GCC 4.7.3 20130102 (prerelease)]
banch: BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8) 
Operating system is a synology :)
Theres no errors in the logfile but it dosnt see the release for 1-2 hours after its up..

**Comment by fernandog** [comment]
@zaffe86 SR must run 24/7. It updates everyday at 3:00am and it's not possible to change this.
an alternative is to enable "update shows at startup" and "backlog search at startup". but will take some time to update everything. that's way it updates at 3:00am
