### ISSUE TITLE
snatchend and completely downloaded show gets removed after/while post processing

### ISSUE THREAD

**Issue by totalcarnage** [SiCKRAGETV/sickrage-issues#354]
hi, 

first of all:
this usefull programm realy saved me a lot of time and was what i've just been looking for.
and i really appreciate all the work you guys have put in this project!

BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8)
Synology DSM 5.1-5021 Update 2

What i did:
Automatic downloading and post processing usualy works fine.
SR Downloads the files into „/folder/folder/A“ then comes the post processing and renames andmoves the file into „/another/folder/show/season/file“

What happened:
Automatic snatching and downloading works. But the file is gone after post processing. Ist neither in the temporary downloading folder nor is it in its final destination folder

What i expected:
The file to be renamed and moved into the correct folder like it was usualy done

Ps.: this doesn’t happen with every file but it feels like it is happening more and more.

Log/error log:
Sorry, i cant find any information regarding the last file it happened with in the logs.

**Comment by fernandog** [comment]
@totalcarnage did you looked in the sickrage.log at /SickRage/Logs?
without log there's nothing we can do

**Comment by totalcarnage** [comment]
a new log was just created with another file which got removed after/while post processing:

2015-01-08 17:40:46 POSTPROCESSER :: Failed creating /volume1/video/Serien/Legit/Legit (2013) - Season 2/ : error 13 : Permission denied
2015-01-08 17:40:46 POSTPROCESSER :: Unable to move file /volume1/down/Legit.S02E07.HDTV.x264-KILLERS[rarbg]/legit.s02e07.hdtv.x264-killers.mp4 to /volume1/video/Serien/Legit/Legit (2013) - Season 2/Legit.2013.S02E07.Afghanistan.mp4: [Errno 2] No such file or directory: '/volume1/video/Serien/Legit/Legit (2013) - Season 2/Legit.2013.S02E07.Afghanistan.mp4'

**Comment by fernandog** [comment]
@totalcarnage  **error 13 : Permission denied**

**Comment by totalcarnage** [comment]
ok, seems logical, i'll try.

do you know why the file is deleted instead of just leave it in the initial download folder?

**Comment by fernandog** [comment]
@totalcarnage OS can't move so the file is lost

**Comment by totalcarnage** [comment]
ok, this helps me a lot fernandog
thank you!

**Comment by totalcarnage** [comment]
hi, the users group now have read/write rights to the temporary download folder and the destination folder after post processing but i'm still gettin the error 13 : permission denied

i've set the rights to the whole group in DSM 5.1 because i assumed whatever the sickrage user is caled would be a part of the "users" group. 
- i cant find any user which would seem to be connected to sickrage.

**Comment by fernandog** [comment]
check /etc/default/sickbeard or /etc/default/sickbeard for SB-USER

my sickbeard file
```
SB_USER=pi
SB_HOME=/home/pi/SickRage
SB_DATA=/home/pi/SickRage
RUN_AT_STARTUP="YES"
```

**Comment by totalcarnage** [comment]
there is no "default" folder in /etc.
would it be possible to let all the sickrage stuff be managed by the root user instead of an own sickrage created user ? if so, what would it take (and where) to edit do let all that be handled by the root user.

...i'm asking because i guess there wouldnt be any permission problems if the root user is handling those files.

**Comment by fernandog** [comment]
@totalcarnage you must have that file.
please follow this tutorial:
https://sickrage.tv/forums/forum/help-support/general-support/14420-sickrage-installation-guides-windows-mac-osx-linux-raspberry-pi
