### ISSUE TITLE
[Feature Request] Add option to manually redownload subtitles

### ISSUE THREAD

**Issue by pateretou** [SiCKRAGETV/sickrage-issues#355]
Hi

some time for some show it is useful to force a "download again" of a subtitle.
For example some show names matches with "old" show name (example : "new girls" sometime match with an old "girl" animated movie) and sickrage download an inappropriate subtitle. 
Or sometime the subtitles is bad and a new version is available later.

So it should be very useful to be able to force a download again a subtitle.

Thank you for your support!

**Comment by mcadam** [comment]
+1

**Comment by pct00** [comment]
+1

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
