### ISSUE TITLE
Show "Forever" : lot of issues to find episode and subtitles

### ISSUE THREAD

**Issue by pateretou** [SiCKRAGETV/sickrage-issues#356]
Hello

for the show "Forever" (this one: http://www.tvrage.com/forever-2014 ) I had some difficulties to find episodes and subtitles.
It's seems the issue is because sickrage tries to find "forever 2014" instead of "forever" (the tracker don't reference as "forever 2014"

What can I do to avoid this issue?

**Comment by neoatomic** [comment]
Add a scene exception in the show with the name that is on the tracker.

**Comment by pateretou** [comment]
Thank for the tip but it's not applied to the subtittle

**Comment by neoatomic** [comment]
For subtitles you will have to rename the files to the names that are used with the subtitle provider. 
You can do that with post-processing naming or with NZBtoMedia.
