### ISSUE TITLE
Feature request: provider per-show

### ISSUE THREAD

**Issue by CentristOuevre** [SiCKRAGETV/sickrage-issues#357]
Please add an option to a show's settings which would allow the user to pick a specific provider/set of providers for a show.

It would be useful in the case where you know a certain provider is going to have the quality/regular uploads for a show you like, and therefore SickRage doesn't need to search anywhere else for it and potentially return an unsatisfactory copy of an episode.

Do it the same way you can specify a scene via "scene exceptions".

**Comment by SickrageDK** [comment]
+1

**Comment by markheloking** [comment]
This is already mentioned in https://github.com/SiCKRAGETV/sickrage-issues/issues/28, but this will increase awareness around this feature.

**Comment by whipcracker** [comment]
Signed up just to say that this is an excellent feature to be added, if/when possible!

I primarily use 1 x torrent provider, but there's a separate torrent provider that is centered around UK TV shows and seems to have the show I'm after (Strictly Come Dancing - for the Mrs)

Would love to be able to "Edit" the show and maybe select which provider this show can use to try and grab the episodes, if at all possible :)

**Comment by neoatomic** [comment]
feature requests need to go here. : http://feathub.com/SiCKRAGETV/SickRage
See if you can create one if it isn't requested yet. :)
