### ISSUE TITLE
‘ascii’ codec can’t encode character: ordinal not in range(128)

### ISSUE THREAD

**Issue by danyboy666** [SiCKRAGETV/sickrage-issues#3572]
Ok here it goes again. I've tried figuring out as much as i can but after 6 hours on this i give up I need some help.

BRANCH: (master) 
COMMIT: (5f496885827bf88e4b24a4c94dc163dd016b2bca) 
python : 2.7.6 (default, Jun 22 2015, 17:58:13)
linux distro :  3.13.0-67-generic #110-Ubuntu SMP Fri Oct 23 13:24:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Note :  I updated my system after the first occurence of this error without avail. 

Python sys : 

>>> import sys
>>> sys.getfilesystemencoding()
'UTF-8'
>>> sys.getdefaultencoding()
'ascii'

system locale : en_CA.UTF-8
language en_CA

locale output : 
LANG=en_CA.UTF-8
LANGUAGE=en_CA:en
LC_CTYPE="en_CA.UTF-8"
LC_NUMERIC="en_CA.UTF-8"
LC_TIME="en_CA.UTF-8"
LC_COLLATE="en_CA.UTF-8"
LC_MONETARY="en_CA.UTF-8"
LC_MESSAGES="en_CA.UTF-8"
LC_PAPER="en_CA.UTF-8"
LC_NAME="en_CA.UTF-8"
LC_ADDRESS="en_CA.UTF-8"
LC_TELEPHONE="en_CA.UTF-8"
LC_MEASUREMENT="en_CA.UTF-8"
LC_IDENTIFICATION="en_CA.UTF-8"
LC_ALL=en_CA.UTF-8

locale -a output : 

C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
POSIX

Occurence : Trying to add a new show in DB
Expect : Add the show "Ma mère cuisine mieux que la tienne"

ERROR log : 
2015-11-05 20:07:13 Thread-45 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/SickRage/sickbeard/webserve.py", line 259, in async_call
    result = function(**kwargs)
  File "/opt/SickRage/sickbeard/webserve.py", line 2659, in addNewShow
    helpers.chmodAsParent(show_dir)
  File "/opt/SickRage/sickbeard/helpers.py", line 757, in chmodAsParent
    childPathStat = os.stat(childPath)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 48: ordinal not in range(128)

sup notes :

The initial issue was because SR was enable to download a release which had some ascii chars in it. I've tried (No logs available for that one sorry) edit: here's part of that initial issue i recovered from my google search.

SEARCHQUEUE-DAILY-SEARCH :: Problem setting permissions or writing file to

I know this initial issue was related to ascii encoding which is why I tried fixing with https://sickrage.tv/forums/forum/help-support/general-support/12825-ensuring-your-locale-s-are-set-properly-to-avoid-unicode-issues

Warning logs : https://gist.github.com/danyboy666/f14b2d73bbd307d9bd69

This appear to have happened right after i tried the manipulation from that link wich completely broke my install.

**Comment by Lowmach1ne** [comment]
we have the same problem https://github.com/SiCKRAGETV/sickrage-issues/issues/3554

**Comment by danyboy666** [comment]
Yeah that's exaclty when I saw that thread that i gave up lol... I'm really hoping this is something that can be fixed within SR. I just hate dealing with locale problems.

**Comment by Lowmach1ne** [comment]
I think I have the solution
===================

Change this

# /usr/local/share/sickrage/SickBeard.py
```python
#!/usr/bin/env python2.7
# Author: Nic Wolfe <nic@wolfeden.ca>
# URL: http://code.google.com/p/sickbeard/
#
# This file is part of SickRage.
```

By this
```python
#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
# Author: Nic Wolfe <nic@wolfeden.ca>
# URL: http://code.google.com/p/sickbeard/
#
# This file is part of SickRage.
```

```python
# -*- coding: utf-8 -*-
```

**Comment by danyboy666** [comment]
I gave it a try it but doesn't correct the problem

**Comment by danyboy666** [comment]
Oh well it seems the problem was with my locapython install.

after doing these steps my issue was solved.

import sys
reload(sys)
sys.setdefaultencoding('utf8')

**Comment by Lowmach1ne** [comment]
Weird, but we have solved our problem both of us ^^

**Comment by danyboy666** [comment]
Yeah I'm still tying to work out my initial problem still not sure this will fix it though. It has to do with relseases with ascii chars sent to deluge. I fixed the deluge issue the other day with the deluge people but i think now the problem is when SR send the accentuated release to deluge's blackhole deluge normalized the title so it's no longer reconized by SR and fails.

**Comment by danyboy666** [comment]
Everything seems to be working as it should. I guess that python manipulation did the trick for me.

**Comment by shaahid1** [comment]
I have been dealing with the same issue and I've finally resolved it. I am running SickRage as its own user on Ubuntu and starting it using an Upstart script. After I added the following lines beginning with 'env' to the script everything has been working flawlessly!


#
#. upstart script located at /etc/init/sickrage.conf
#

setuid sickrage
setgid media

env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
env LANG=en_US.UTF-8
env HOME=/var/lib/sickrage
env LANGUAGE=en_US.UTF-8

start on runlevel [2345]
stop on runlevel [016]

respawn

exec python /var/lib/sickrage/SickRageServer/SickBeard.py
