### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-81848 :: [NZBGeek] :: Unknown result type, unable to download it

### ISSUE THREAD

**Issue by dkimbell13** [SiCKRAGETV/sickrage-issues#3597]
### INFO
Python Version: **2.7.8 (default, Jul  3 2014, 23:17:54) [GCC 4.8.2 20131219 (prerelease)]**
Operating System: **Linux-3.10.30-30-ARCH-armv7l-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@083611306e8947ad64c7c22b79e4db6874f730ae
Link to Log: https://gist.github.com/f30d623783b0479b3027
### ERROR
```
SEARCHQUEUE-BACKLOG-81848 :: [NZBGeek] :: Unknown result type, unable to download it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by dkimbell13** [comment]
### INFO
Python Version: **2.7.8 (default, Jul  3 2014, 23:17:54) [GCC 4.8.2 20131219 (prerelease)]**
Operating System: **Linux-3.10.30-30-ARCH-armv7l-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@083611306e8947ad64c7c22b79e4db6874f730ae
Link to Log: https://gist.github.com/f432397d12fed58d733a
### ERROR
```
SEARCHQUEUE-MANUAL-248835 :: [NZBGeek] :: Unknown result type, unable to download it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dkimbell13** [comment]
### INFO
Python Version: **2.7.8 (default, Jul  3 2014, 23:17:54) [GCC 4.8.2 20131219 (prerelease)]**
Operating System: **Linux-3.10.30-30-ARCH-armv7l-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@083611306e8947ad64c7c22b79e4db6874f730ae
Link to Log: https://gist.github.com/781263bbbeb9f3654739
### ERROR
```
SEARCHQUEUE-MANUAL-281709 :: [NZBGeek] :: Unknown result type, unable to download it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dkimbell13** [comment]
### INFO
Python Version: **2.7.8 (default, Jul  3 2014, 23:17:54) [GCC 4.8.2 20131219 (prerelease)]**
Operating System: **Linux-3.10.30-30-ARCH-armv7l-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@083611306e8947ad64c7c22b79e4db6874f730ae
Link to Log: https://gist.github.com/c496c2d8f43f557f8be0
### ERROR
```
SEARCHQUEUE-MANUAL-248835 :: [NZBGeek] :: Unknown result type, unable to download it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dkimbell13** [comment]
### INFO
Python Version: **2.7.8 (default, Jul  3 2014, 23:17:54) [GCC 4.8.2 20131219 (prerelease)]**
Operating System: **Linux-3.10.30-30-ARCH-armv7l-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@083611306e8947ad64c7c22b79e4db6874f730ae
Link to Log: https://gist.github.com/caa0acdb596077a897a2
### ERROR
```
SEARCHQUEUE-MANUAL-281709 :: [NZBGeek] :: Unknown result type, unable to download it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dkimbell13** [comment]
### INFO
Python Version: **2.7.8 (default, Jul  3 2014, 23:17:54) [GCC 4.8.2 20131219 (prerelease)]**
Operating System: **Linux-3.10.30-30-ARCH-armv7l-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@083611306e8947ad64c7c22b79e4db6874f730ae
Link to Log: https://gist.github.com/d111abd9256898b0c7b5
### ERROR
```
SEARCHQUEUE-MANUAL-248835 :: [NZBGeek] :: Unknown result type, unable to download it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dkimbell13** [comment]
### INFO
Python Version: **2.7.8 (default, Jul  3 2014, 23:17:54) [GCC 4.8.2 20131219 (prerelease)]**
Operating System: **Linux-3.10.30-30-ARCH-armv7l-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@083611306e8947ad64c7c22b79e4db6874f730ae
Link to Log: https://gist.github.com/6544db2a2f96a1324aef
### ERROR
```
SEARCHQUEUE-MANUAL-281709 :: [NZBGeek] :: Unknown result type, unable to download it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dkimbell13** [comment]
### INFO
Python Version: **2.7.8 (default, Jul  3 2014, 23:17:54) [GCC 4.8.2 20131219 (prerelease)]**
Operating System: **Linux-3.10.30-30-ARCH-armv7l-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@083611306e8947ad64c7c22b79e4db6874f730ae
Link to Log: https://gist.github.com/e2e110afdf99c0e648e0
### ERROR
```
SEARCHQUEUE-MANUAL-248835 :: [NZBGeek] :: Unknown result type, unable to download it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dkimbell13** [comment]
### INFO
Python Version: **2.7.8 (default, Jul  3 2014, 23:17:54) [GCC 4.8.2 20131219 (prerelease)]**
Operating System: **Linux-3.10.30-30-ARCH-armv7l-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@083611306e8947ad64c7c22b79e4db6874f730ae
Link to Log: https://gist.github.com/b2cd299cc6609888d40f
### ERROR
```
SEARCHQUEUE-MANUAL-281709 :: [NZBGeek] :: Unknown result type, unable to download it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dkimbell13** [comment]
### INFO
Python Version: **2.7.8 (default, Jul  3 2014, 23:17:54) [GCC 4.8.2 20131219 (prerelease)]**
Operating System: **Linux-3.10.30-30-ARCH-armv7l-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@083611306e8947ad64c7c22b79e4db6874f730ae
Link to Log: https://gist.github.com/81af779f825bee1ad457
### ERROR
```
SEARCHQUEUE-MANUAL-153021 :: [NZBGeek] :: Unknown result type, unable to download it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dkimbell13** [comment]
### INFO
Python Version: **2.7.8 (default, Jul  3 2014, 23:17:54) [GCC 4.8.2 20131219 (prerelease)]**
Operating System: **Linux-3.10.30-30-ARCH-armv7l-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@083611306e8947ad64c7c22b79e4db6874f730ae
Link to Log: https://gist.github.com/6106ab8cd0ffe18b4f7c
### ERROR
```
SEARCHQUEUE-MANUAL-248835 :: [NZBGeek] :: Unknown result type, unable to download it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dkimbell13** [comment]
### INFO
Python Version: **2.7.8 (default, Jul  3 2014, 23:17:54) [GCC 4.8.2 20131219 (prerelease)]**
Operating System: **Linux-3.10.30-30-ARCH-armv7l-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@083611306e8947ad64c7c22b79e4db6874f730ae
Link to Log: https://gist.github.com/3d428b5013cf3b1ccbc2
### ERROR
```
SEARCHQUEUE-MANUAL-281709 :: [NZBGeek] :: Unknown result type, unable to download it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dkimbell13** [comment]
### INFO
Python Version: **2.7.8 (default, Jul  3 2014, 23:17:54) [GCC 4.8.2 20131219 (prerelease)]**
Operating System: **Linux-3.10.30-30-ARCH-armv7l-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@083611306e8947ad64c7c22b79e4db6874f730ae
Link to Log: https://gist.github.com/69dedafc777de7860481
### ERROR
```
SEARCHQUEUE-MANUAL-95491 :: [NZBGeek] :: Unknown result type, unable to download it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dkimbell13** [comment]
### INFO
Python Version: **2.7.8 (default, Jul  3 2014, 23:17:54) [GCC 4.8.2 20131219 (prerelease)]**
Operating System: **Linux-3.10.30-30-ARCH-armv7l-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@083611306e8947ad64c7c22b79e4db6874f730ae
Link to Log: https://gist.github.com/df09193a3eda51ec34c6
### ERROR
```
SEARCHQUEUE-MANUAL-153021 :: [NZBGeek] :: Unknown result type, unable to download it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dkimbell13** [comment]
### INFO
Python Version: **2.7.8 (default, Jul  3 2014, 23:17:54) [GCC 4.8.2 20131219 (prerelease)]**
Operating System: **Linux-3.10.30-30-ARCH-armv7l-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@083611306e8947ad64c7c22b79e4db6874f730ae
Link to Log: https://gist.github.com/891012e654ec5219314a
### ERROR
```
SEARCHQUEUE-BACKLOG-153021 :: [NZBGeek] :: Unknown result type, unable to download it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dkimbell13** [comment]
### INFO
Python Version: **2.7.8 (default, Jul  3 2014, 23:17:54) [GCC 4.8.2 20131219 (prerelease)]**
Operating System: **Linux-3.10.30-30-ARCH-armv7l-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@083611306e8947ad64c7c22b79e4db6874f730ae
Link to Log: https://gist.github.com/eb22555f8acb78c37356
### ERROR
```
SEARCHQUEUE-BACKLOG-95491 :: [NZBGeek] :: Unknown result type, unable to download it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dkimbell13** [comment]
### INFO
Python Version: **2.7.8 (default, Jul  3 2014, 23:17:54) [GCC 4.8.2 20131219 (prerelease)]**
Operating System: **Linux-3.10.30-30-ARCH-armv7l-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@083611306e8947ad64c7c22b79e4db6874f730ae
Link to Log: https://gist.github.com/67e45d60c40c9fdebded
### ERROR
```
SEARCHQUEUE-BACKLOG-276312 :: [NZBGeek] :: Unknown result type, unable to download it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dkimbell13** [comment]
### INFO
Python Version: **2.7.8 (default, Jul  3 2014, 23:17:54) [GCC 4.8.2 20131219 (prerelease)]**
Operating System: **Linux-3.10.30-30-ARCH-armv7l-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@083611306e8947ad64c7c22b79e4db6874f730ae
Link to Log: https://gist.github.com/9dc749a3bb6fc296611f
### ERROR
```
SEARCHQUEUE-MANUAL-248835 :: [NZBGeek] :: Unknown result type, unable to download it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dkimbell13** [comment]
### INFO
Python Version: **2.7.8 (default, Jul  3 2014, 23:17:54) [GCC 4.8.2 20131219 (prerelease)]**
Operating System: **Linux-3.10.30-30-ARCH-armv7l-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@083611306e8947ad64c7c22b79e4db6874f730ae
Link to Log: https://gist.github.com/530e76227b8654785057
### ERROR
```
SEARCHQUEUE-MANUAL-281709 :: [NZBGeek] :: Unknown result type, unable to download it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dkimbell13** [comment]
### INFO
Python Version: **2.7.8 (default, Jul  3 2014, 23:17:54) [GCC 4.8.2 20131219 (prerelease)]**
Operating System: **Linux-3.10.30-30-ARCH-armv7l-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@083611306e8947ad64c7c22b79e4db6874f730ae
Link to Log: https://gist.github.com/dd63d7543d6a84fd977e
### ERROR
```
SEARCHQUEUE-MANUAL-95491 :: [NZBGeek] :: Unknown result type, unable to download it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dkimbell13** [comment]
### INFO
Python Version: **2.7.8 (default, Jul  3 2014, 23:17:54) [GCC 4.8.2 20131219 (prerelease)]**
Operating System: **Linux-3.10.30-30-ARCH-armv7l-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@083611306e8947ad64c7c22b79e4db6874f730ae
Link to Log: https://gist.github.com/a5bb44ae26dfc8f11db0
### ERROR
```
SEARCHQUEUE-MANUAL-153021 :: [NZBGeek] :: Unknown result type, unable to download it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dkimbell13** [comment]
### INFO
Python Version: **2.7.8 (default, Jul  3 2014, 23:17:54) [GCC 4.8.2 20131219 (prerelease)]**
Operating System: **Linux-3.10.30-30-ARCH-armv7l-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@083611306e8947ad64c7c22b79e4db6874f730ae
Link to Log: https://gist.github.com/beeabc662fb92cab59a1
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: Unknown result type, unable to download it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dkimbell13** [comment]
### INFO
Python Version: **2.7.8 (default, Jul  3 2014, 23:17:54) [GCC 4.8.2 20131219 (prerelease)]**
Operating System: **Linux-3.10.30-30-ARCH-armv7l-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@083611306e8947ad64c7c22b79e4db6874f730ae
Link to Log: https://gist.github.com/a385f18132d3d37322fb
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: Unknown result type, unable to download it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
develop is in limbo atm, but this error is fixed at least
