### ISSUE TITLE
processTV.py not thread safe

### ISSUE THREAD

**Issue by swamp12** [SiCKRAGETV/sickrage-issues#360]
Concurrent web API requests to processTV.py each run in a separate thread, but because of using global variables, the results are unpredictable. The logging(returnStr) is messed up and failure conditions(process_result) are mixed up.

It is not safe to have multiple downloaders simultaneously make use the post-processing API of Sickrage. Note that the API supports both NZB's as well as Torrents.

Suggested solution: don't use globals but use function parameters. 

    $ grep global processTV.py
    global returnStr, process_result
    global process_result, returnStr
    global process_result, returnStr
    global process_result, returnStr
    global returnStr
    global process_result, returnStr
    global returnStr

Reproduction:
    $ for i in `seq 1 3`; do wget -O out.$i "http://HOSTNAME:PORT/home/postprocess/processEpisode?quiet=1&dir=%2Ftmp"& done; echo

Output:
Notice the multiple "Successfully processed" lines in the output. Above is a simplified example. With real simultaneous post-process requests, the results are very mixed up. Output lines of separate requests ending up in the output of unrelated other requests.

    out.1:
    Processing folder /tmp
    TV_DOWNLOAD_DIR: ...
    PostProcessing Path: /
    PostProcessing Dirs: [u'tmp']
    PostProcessing Files: []
    PostProcessing VideoFiles: []
    PostProcessing RarContent: []
    PostProcessing VideoInRar: []
    Processing folder tmp
    Successfully processed
    Successfully processed
    Successfully processed

    out.2:
    Processing folder /tmp
    TV_DOWNLOAD_DIR: ...
    PostProcessing Path: /
    PostProcessing Dirs: [u'tmp']
    PostProcessing Files: []
    PostProcessing VideoFiles: []
    PostProcessing RarContent: []
    PostProcessing VideoInRar: []
    Processing folder tmp
    Successfully processed
    Successfully processed

    out.3:
    Processing folder /tmp
    TV_DOWNLOAD_DIR: ...
    PostProcessing Path: /
    PostProcessing Dirs: [u'tmp']
    PostProcessing Files: []
    PostProcessing VideoFiles: []
    PostProcessing RarContent: []
    PostProcessing VideoInRar: []
    Processing folder tmp
    Successfully processed

**Comment by fernandog** [comment]
@swamp12  I think you should wait the WGET response, read the result, if is "Successfully processed" then go to the next episode. You script runs wget and don't wait for nothing. Maybe it's a racing condition.

**Comment by swamp12** [comment]
Thanks for your response. In above WGET scenario I tried to simulate, in a easy reproducible manner, the situation I have here. I have an NZB downloader and a Torrent downloader, which both at any time may access the Sickrage post-processing web API. And then at the same time I go to the Manual post processing page. This means that from 3 different sources(browser, NZB and torrent) calls are made to the processTV API.

When they do at roughly the same time(like the WGET in above example), the results are like described above. 

Like mentioned, this is caused by use of globals in processTV.py, which makes processTV not thread safe. Globals are shared among all threads and not limited to one thread. It can easily be fixed by not using these globals, but pass the data(returnStr and process_result) from function to function manually. I can create a patch if you would like.

**Comment by fernandog** [comment]
@swamp12 can you try to fix it? Do a Pull Request to develop branch if you know how to fix it

**Comment by swamp12** [comment]
No problem. I'll provide a fix and will do a pull request.

**Comment by markheloking** [comment]
Closing as this is merged and assumed fixed.
