### ISSUE TITLE
Can't delete TV Show - TRAKT error

### ISSUE THREAD

**Issue by geek2009** [SiCKRAGETV/sickrage-issues#362]
I am trying to delete a TV show and get the following error:

http://pastebin.com/raw.php?i=pdXU3f1m

I am running Windows 7.

SR Version: BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8) 

Python Version: 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]

**Comment by fernandog** [comment]
@geek2009 
did you make sure the show was deleted despite the error?
this error is at trakt only

**Comment by yongbi85** [comment]
Ok I have encountered this error often, uncheck the trakt notification in social and try again to remove the show, it will work.

But yes it is a bug, i had to uncheck to trakt notification to be able to remove some shows (and it was before trakt changed their website so it is not linked to their change)

**Comment by geek2009** [comment]
Fixed. Good call yongbi85.

**Comment by fernandog** [comment]
@yongbi85 the error that you got was "503 Server Error: Service Unavailable "
Trakt was under heavy use.

**Comment by itsmarkw** [comment]
I'm getting the same error, even after disabling Trakt notifications. I cannot delete a show at all.

**Comment by markheloking** [comment]
It seems the issue is persistent then. Reopening the issue.

**Comment by fernandog** [comment]
@itsmarkw is impossible to get the error if you disabled trakt. please confirm it's disabled, stop SR, open the config.ini and make sure trakt is disable

```
[Trakt]
use_trakt = 0
```
