### ISSUE TITLE
postprocessor fails after 1 episode

### ISSUE THREAD

**Issue by jimmybund** [SiCKRAGETV/sickrage-issues#363]
My post-processor is set to catch files in D:\TV\DOWNLOADS, rename them, and move them to the respective show folder in D:\TV. It will succeed in doing this for 1 episode every cycle (it's set to act every 10 minutes), but it won't proceed to do the rest. So if there's 10 files in the downloads folder, it will do 1 every 10 minutes (taking 100 minutes), giving me the following error in the log each time: "syntax error: line 2, column 0". The same thing happens if I do a manual post-process, each time I click it'll do one episode, I can hit back and do it again manually and it'll do 1 episode each time.

Branch: MASTER
Commit hash: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8) 
Your operating system and python version: Windows 7 64-bit, python 2.7.9

Link to a copy/paste of my logs & errors:
http://pastebin.com/dbUqh2iD

**Comment by fernandog** [comment]
@jimmybund still having this issue? did you tried DEVELOP branch?  config>advanged>github

**Comment by jimmybund** [comment]
I am still having this issue, but no I have not tried the DEVELOP branch.
Let me know and I could give it a shot.

**Comment by fernandog** [comment]
Try it please

**Comment by fernandog** [comment]
@jimmybund please update to develop branch and report back

**Comment by jimmybund** [comment]
Will do. I am away from home until Tuesday and will do then.

**Comment by TagForce** [comment]
@jimmybund Also try turning off your Plex notifications...
Errors indicate it fails that, and not the actual Post Processing.

Let us know, Plex has had some updates I think, so it could very well be fixed.

**Comment by jimmybund** [comment]
Updated to the DEVELOP branch and still got the error:

2015-02-17 01:50:22 POSTPROCESSER :: Exception generated in thread POSTPROCESSER: syntax error: line 2, column 0
2015-02-17 01:20:22 POSTPROCESSER :: Exception generated in thread POSTPROCESSER: syntax error: line 2, column 0

BRANCH: (develop) / COMMIT: (1ad9ed453985f1fccdcd7eac97970cef1cb324c1) 
Windows 7 64-bit, python 2.7.9

Going to try turning off plex notifications on the DEVELOP branch now.

**Comment by fernandog** [comment]
Worked?

**Comment by abeloin** [comment]
I think it's related to the fact that https://github.com/SiCKRAGETV/SickRage/pull/1190 was merged in master only.

**Comment by jimmybund** [comment]
DEVELOP branch with plex notifications turned off did work! No more errors.
Should I go back to master now?

On Tue, Feb 17, 2015 at 12:47 PM, Alexandre Beloin <notifications@github.com

**Comment by abeloin** [comment]
What is your plex config?

**Comment by jimmybund** [comment]
What exactly do you need to know? I'm running the latest Plex Media Server on the same Windows PC that I'm running Sickrage. Version 0.9.11.7
