### ISSUE TITLE
KODI Notifications - failure to detect KODI version

### ISSUE THREAD

**Issue by raymondtrueman** [SiCKRAGETV/sickrage-issues#364]
BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8) 
Python Version:  2.7.8 (default, Dec 12 2014, 22:38:36) [GCC 4.3.2]
OS: Linux (Synology DiskStation Manager 5.3)

I am running Gotham 13.2 and my notifications just stopped working. I tested the KODI web interface in my web browser and it works. So I am not sure why I'm getting this error. This is the exact error in the log:

`2015-01-09 05:50:33 Thread-38 :: Failed to detect KODI version for '192.168.1.103:60000', check configuration and try again.`

I am pretty sure the configuration is correct because it used to work

**Comment by fernandog** [comment]
@raymondtrueman password is wrong. check your KODI user/pass/port/ip and this settings at SR

**Comment by raymondtrueman** [comment]
I double checked all of it and also in KODI's settings. Its correct. When I test in SickRage I get 
`Test KODI notice failed`

**Comment by raymondtrueman** [comment]
@fernandog, I found the problem. Windows marked my local network as "Unidentified Network", automatically making it a public network. This caused Windows Firewall to block any connections coming in to KODI. I fixed the Unidentified Network problem and then it started working again. Thanks for your help
