### ISSUE TITLE
"Manage Torrents" missing from the Manage menu

### ISSUE THREAD

**Issue by raymondtrueman** [SiCKRAGETV/sickrage-issues#365]
SR Version: BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8) 
Python Version: 2.7.8 (default, Dec 12 2014, 22:38:36) [GCC 4.3.2]
OS: Linux (Synology DiskStation Manager 5.3)

**Comment by fernandog** [comment]
@raymondtrueman 
Did you enabled torrent search?
please send print screens

**Comment by raymondtrueman** [comment]
Yes @fernandog torrent search is enabled

![Menu](http://s3.postimg.org/nv95o7h77/Menu.jpg)
![Torrent Search](http://s28.postimg.org/girtbuf59/torrentsearch.jpg)

**Comment by raymondtrueman** [comment]
Found the problem. I had HTTPS enabled for SickRage, but my Synology was on HTTP. Switched the Synology to HTTPS and the menu item appeared. It is this piece of code on line 2518 of webserve.py that checks for this:

``` if sickbeard.USE_TORRENTS and sickbeard.TORRENT_METHOD != 'blackhole' \
                and (sickbeard.ENABLE_HTTPS and sickbeard.TORRENT_HOST[:5] == 'https'
                     or not sickbeard.ENABLE_HTTPS and sickbeard.TORRENT_HOST[:5] == 'http:'):```

However issue #349 still poses problems with this feature
