### ISSUE TITLE
[Feature Request] Adding more link methods during PP

### ISSUE THREAD

**Issue by devster31** [SiCKRAGETV/sickrage-issues#367]
Hi, I'm quite new here, I'd like to suggest adding a new postprocessing method to include a generic 'Link' option that first tries to do Hard Links, then falls back to Symlinks and then to copy.

Would that be a useful feature?

**Comment by neoatomic** [comment]
Duplicate/related to https://github.com/SiCKRAGETV/sickrage-issues/issues/40
