### ISSUE TITLE
Previously working shows not displaying - "invalid literal"

### ISSUE THREAD

**Issue by Wickemu** [SiCKRAGETV/sickrage-issues#369]
I'm getting this error with three shows:
```python
There was an error creating the show in /media/tv/Cosmos A Spacetime Odyssey: invalid literal for int() with base 10: 'en'
There was an error creating the show in /media/tv/Friends: invalid literal for int() with base 10: 'en'
There was an error creating the show in /media/tv/Star Trek The Next Generation: invalid literal for int() with base 10: 'en'
```
Any idea what's causing this and how I can fix it?

**Comment by fernandog** [comment]
@Wickemu did you try to change an episode status?

**Comment by fernandog** [comment]
@Wickemu can you fully explain step by step? all values you set for all fields

**Comment by Wickemu** [comment]
Fernando,




None of these shows had been touched in months - I didn’t even realize that they had gone missing until I attempted to update my Star Trek files by moving 1080p Blu-Ray files into the Download directory and then investigating when they were not automatically copied.  




If I recall correctly, these were the only TV shows in my collection who had a quality requirement of 1080p Blu-Ray, not HD, 1080p HD, or anything like that.  As it is, I am unable to check or change this parameter as far as I am aware.



Thanks,     Jack

**Comment by markheloking** [comment]
Please use the issue guidelines when posting an issue. This way the dev team is able to debug your problem. Don't forget to use [markdown](https://guides.github.com/features/mastering-markdown/) on any code and log you want to post in-line.

- [ ] Branch
- [ ] Commit hash
- [ ] Operating system and python version
- [x] What did you do?
- [x] What happened?
- [x] What did you expect?
- [ ] Link to a copy/paste of your logfile with clear debug info of the error on [pastebin](http://pastebin.com/) (or in-line using [markdown](https://guides.github.com/features/mastering-markdown/) for small snippets)

**Comment by fernandog** [comment]
@Wickemu still having this issues with the latest update? have you tried DEVELOP branch?

**Comment by fernandog** [comment]
no reply. closing
