### ISSUE TITLE
Amazing open source project

### ISSUE THREAD

**Issue by ikriz** [SiCKRAGETV/sickrage-issues#3709]

**Comment by loonielongbottom** [comment]
Hi,

Could you explain please what happened? I am out of the loop.

**Comment by ikriz** [comment]
https://wvvw.me/mirror/sickrage/

**Comment by miigotu** [comment]
We havent moved on, we moved the entire project (and team) to https://github.com/SickRage/SickRage so that ech couldnt disrupt the progress ever again.
