### ISSUE TITLE
Unable to parse How.I.Met.Your.Mother.S02.720p.HDTV.x264 into a scene name.

### ISSUE THREAD

**Issue by kingmotley** [SiCKRAGETV/sickrage-issues#371]
Unable to parse How.I.Met.Your.Mother.S02.720p.HDTV.x264 into a scene name.

**Comment by fernandog** [comment]
@kingmotley 
https://github.com/SiCKRAGETV/sickrage-issues

SUBMITTING A BUG/ISSUE TICKET

(DO NOT POST ANYTHING THAT CONTAINS YOUR LOGIN INFORMATION OR API KEY)
Please include the following when opening a new ticket:

Branch
Commit hash
Your operating system and python version
What you did
What happened
What you expected
Link to a copy/paste of your logfile with clear debug info of the error on PASTBIN
ENABLING DETAILED DEBUGGING FOR LOGS

Shutdown SickRage
Edit config.ini and set debug to 1 then save config
Start SickRage and wait for error to occure again
