### ISSUE TITLE
[APP SUBMITTED]: CHECKVERSION :: git fetch origin returned : From https://github.com/SiCKRAGETV/SickRage
   80c2a23..7ab0c80  develop    -> origin/develop
error: Unable to append to .git/logs/refs/remotes/origin/unicode-fix: Permission denied
error: Cannot update the ref 'refs/remotes/origin/unicode-fix'.
 ! ca14008..d0e4786  unicode-fix -> origin/unicode-fix  (unable to update local ref)

### ISSUE THREAD

**Issue by DonZalmrol** [SiCKRAGETV/sickrage-issues#3733]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
No Log available with ERRORS: 
### ERROR
```
CHECKVERSION :: git fetch origin returned : From https://github.com/SiCKRAGETV/SickRage
   80c2a23..7ab0c80  develop    -> origin/develop
error: Unable to append to .git/logs/refs/remotes/origin/unicode-fix: Permission denied
error: Cannot update the ref 'refs/remotes/origin/unicode-fix'.
 ! ca14008..d0e4786  unicode-fix -> origin/unicode-fix  (unable to update local ref)
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by labrys** [comment]
@DonZalmrol if you have the time, join us in IRC at #sickrage-issues and we'll see if we can help you out.

**Comment by DonZalmrol** [comment]
@labrys afraid I don't have IRC. I'm running sickrage on my Synology NAS. Could something have changed the rights for the sickrage user?

**Comment by labrys** [comment]
possibly... the link i posted [IRC](https://kiwiirc.com/client/irc.freenode.net/?theme=basic#sickrage-issues) is a web based IRC client.

**Comment by DonZalmrol** [comment]
Thx, on it now.

**Comment by DonZalmrol** [comment]
Fixed issue with help of Labrys
