### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-70327 :: [NZBGeek] :: Unable to parse Buffy.the.Vampire.Slayer.s05.2000.dvdrip.x264 into a scene name. If it's a valid one log a bug.

### ISSUE THREAD

**Issue by sickrageuser42** [SiCKRAGETV/sickrage-issues#3750]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-53-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
Link to Log: https://gist.github.com/ad5be9f1dc822499cb2d
### ERROR
```
SEARCHQUEUE-BACKLOG-70327 :: [NZBGeek] :: Unable to parse Buffy.the.Vampire.Slayer.s05.2000.dvdrip.x264 into a scene name. If it's a valid one log a bug.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by labrys** [comment]
`Buffy.the.Vampire.Slayer.s05.2000.dvdrip.x264` Is not a valid name, as there is no episode number.

**Comment by PotatoeyCouch** [comment]
It's a season pack?

**Comment by duramato** [comment]
@PotatoeyCouch yeah it seems like soo https://torrentz.eu/b376f6c3725ca31b52dc9e3dc6ab5bf054ccef6f
but the 2000 doesnt have any reason to be there in the name :P

**Comment by sickrageuser42** [comment]
Hmm, true, I don't think there was a remake of the series another year so the year shouldn't have been added. Oh well.
