### ISSUE TITLE
Not snatching automatically, but manual snatch works

### ISSUE THREAD

**Issue by POEDaley** [SiCKRAGETV/sickrage-issues#3759]
Hello,

In the last couple weeks, I've really been struggling with sickrage and it not snatching properly.  Sometimes when I clear out the cache and restart it, it will work temporarily.  Also, click on the magnifying glass next to an episode will search out the episode just fine and snatch it.

It worked very well for quite a long time. This just started happening recently and not sure what could have prompted it.

Everything else seems to work just fine, but it's not snatching new episodes by itself anymore

Does anyone have any ideas, or where to look for where the problems is?

Thanks in advance

SR Version:	BRANCH: (master) / COMMIT: (1e8a1a0ede9b386f25e243c1c4e3814a520bd325) 
Python Version:	2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]

**Comment by pithoi** [comment]
@POEDaley that commit is for the other SickRage repository at https://github.com/SickRage/SickRage.  You should post on their issue tracker https://github.com/SickRage/sickrage-issues

**Comment by POEDaley** [comment]
Rats.

Sorry about that.  Thanks for the help.
