### ISSUE TITLE
Relative path un-supported for the automatic post-processing "TV Download Dir"

### ISSUE THREAD

**Issue by heetbeet** [SiCKRAGETV/sickrage-issues#376]
The "TV Download Dir" under Settings->Post Processing (found under sickbeard.TV_DOWNLOAD_DIR in the source) does not support relative paths. This is in conflict with the message displayed at the bottom of the Settings->Post Processing page:
"All non-absolute folder locations are relative to C:\sickrage\SickRage"

All other directories I have tested are allowed to be relative paths.

There is a check for relative paths done in this file https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/autoPostProcesser.py under line 37. If a relative path is found, an error message is logged and the post-processing is stopped:
"Automatic post-processing attempted but dir ..\\..\Downloads is relative (and probably not what you really want to process)"

This issue may be fixed by removing the GUI message—"All non-absolute folder locations are relative to C:\sickrage\SickRage"—to not confuse the user into thinking relative paths are supported, or by allow relative paths. I would prefer the latter since I see no reason for relative paths to be supported in all the other cases, but not in this particular case. It is also useful behavior for a movable/portable setup.

**Comment by kingmotley** [comment]
What did you put in for your relative path?

**Comment by heetbeet** [comment]
In my config file the following is set:
root_dirs = 0|..\Downloads\sic_complete
tv_download_dir = ..\..\Downloads\ut_complete

The root_dirs works out of the box, but the tv_download_dir works only when removing the check:
`if not ek.ek(os.path.isabs, sickbeard.TV_DOWNLOAD_DIR):`
from https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/autoPostProcesser.py

**Comment by fernandog** [comment]
@TagForce thoughts?

**Comment by TagForce** [comment]
Simple fix... Comment out lines 35 through 39 in autoPostProcessor.py.

However... This makes your TV Download folder part of the SickRage folder structure... If something fails you'd have to remove the entire SickRage folder for it to clone again, including the location where your downloads went.

Relative paths are supported, but not really a good idea.
