### ISSUE TITLE
[Feature Request] Support for Award Shows (Search by name and year only)

### ISSUE THREAD

**Issue by raymondtrueman** [SiCKRAGETV/sickrage-issues#377]
This is a feature request to support awards shows because at the moment award shows are not snatched.
On most torrent trackers and NZB indexers they are not named as S01E01 format and also not by an air-by-date format like 01-01-2014.
They are simply named by their year because they are annually broadcast. 
For example: Billboard Music Awards 2014
Now this is already all contained in the episode name on theTVDB and TVRage, so the search only has to search for the episode name and disregard its season numbers, episode numbers and air dates

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
