### ISSUE TITLE
tvshow.nfo shows unreadable characters when adding non-english shows

### ISSUE THREAD

**Issue by VioletVivirand** [SiCKRAGETV/sickrage-issues#378]
When I try to add shows that are not english (e.g. Japanese)
![2015-01-11 1 31 44](https://cloud.githubusercontent.com/assets/2352887/5692483/e77bc31e-9931-11e4-8073-bb074a83e0db.png)

The tvshow.nfo shows unreadable characters
![2015-01-11 1 32 30](https://cloud.githubusercontent.com/assets/2352887/5692484/f91d5c0e-9931-11e4-8e9d-fc873c1e9d73.png)

**Comment by fernandog** [comment]
@VioletVivirand  please update SickRage

**Comment by VioletVivirand** [comment]
Well... I clicked Check for Updates and it showed No Updates Needed.
SR Version:	BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8)

**Comment by markheloking** [comment]
@VioletVivirand latest version as of right now is BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb). Please update and report back.
