### ISSUE TITLE
[Feature Request] Add editshow call to API.

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#38]
<a href="https://github.com/Hellowlol"><img src="https://avatars.githubusercontent.com/u/1214134?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hellowlol](https://github.com/Hellowlol)**
_Wednesday Dec 03, 2014 at 16:01 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/1019 (11 comment(s))_

----

Would have been awesome if we could edit the same settings as in the gui

**Comment by miigotu** [comment]
@MGaetan89 interested in making this happen? might be nice for your app...

**Comment by fernandog** [comment]
today we can only change quality

**Comment by MGaetan89** [comment]
@miigotu If you are talking about [merging the API and the web UI](https://github.com/SiCKRAGETV/sickrage-issues/issues/38#issuecomment-66940967), it will happen with #2567 
About the edit show API command, I think it's best to way when the merging is done so we can simply reuse what's already done for the web part.

**Comment by miigotu** [comment]
@MGaetan89 agreed. I made that comment before we decided to combine/simplify webserve/webapi

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
