### ISSUE TITLE
[Feature Request] Option to Re-encode subtitles to UTF-8 for beter support

### ISSUE THREAD

**Issue by aidik** [SiCKRAGETV/sickrage-issues#380]
Most of the players are not supporting local charsets, but support UTF-8. So I'm proposing adding a feature which will allow users to automatically re-encode subtitles to UTF-8.

I'm currently doing it by using this script:

```shell
#!/bin/sh
for f in ./*.cs.srt; do
echo "$f"
enconv -x UTF-8 -L cs "$f"
done
```

I believe that Python has it's own ways how to detect used charset and how to change it, so using enca will not be necessary.

Thank you for considering implementation of this feature.

**Comment by WebSpider** [comment]
If i read this correctly, you are proposing we automatically alter downloaded files. 
IMO, that is not what SR is for.

**Comment by WebSpider** [comment]
This feature to me would be better off in https://github.com/clinton-hall/nzbToMedia .. which also does transcoding of movies for instance

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
