### ISSUE TITLE
Size file settings

### ISSUE THREAD

**Issue by rickytin** [SiCKRAGETV/sickrage-issues#383]
It would be nice to have a setting that limit the size of a episode downloaded.
From example download a HD show that go from 750mb to 2.5GB.
Yesterday SickRage download a episode that it was 6.7Gb and it was to big for my computer to play.

**Comment by fernandog** [comment]
@rickytin maybe it was a full season pack not a single episode.

**Comment by rickytin** [comment]
Thanks fernandog, it was only one episode in Blu-Ray 1080p (TV Show The Americans). I have to delete the episode and search for a new one with a lower size.

**Comment by fernandog** [comment]
@rickytin why don't you use custom qualities? That way you can ignore blu-ray and lower HD qualities
