### ISSUE TITLE
Post Processing results.. not picking up show

### ISSUE THREAD

**Issue by ladygaming** [SiCKRAGETV/sickrage-issues#385]
added to: 
Exception List: reign

did a manual post processing.... and getting this

Postprocessing results
```
Processing folder D:\_MEDIA\DL
TV_DOWNLOAD_DIR: D:\_MEDIA\DL
PostProcessing Path: D:\_MEDIA\DL
PostProcessing Dirs: []
PostProcessing Files: []
PostProcessing VideoFiles: []
PostProcessing RarContent: []
PostProcessing VideoInRar: []
Successfully processed
Processing D:\_MEDIA\reign.s01e04.720p.hdtv.x264-killers.mkv (None)
This show isn't in your list, you need to add it to SB before post-processing an episode
Processing failed for D:\_MEDIA\reign.s01e04.720p.hdtv.x264-killers.mkv: 
Processing folder DL
```

**Comment by fernandog** [comment]
@ladygaming add "Reign" to the scene exception (edit show page)

**Comment by ChadScott** [comment]
I'm seeing the same issue and I can't make heads or tails of it. I've tried adding the name of the show as a scene exception but it doesn't help. An example on my side:

```
Processing /srv/Plex/SickRage/Top Gear - [17x03] - 2011.07.10 [720p x264 by FoV].mkv (None)
This show isn't in your list, you need to add it to SB before post-processing an episode
```

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/25

**Comment by fernandog** [comment]
@ChadScott why there's an underscore in your path "D:_MEDIA\" ?

**Comment by ChadScott** [comment]
It's not. My volume is under /srv.

**Comment by fernandog** [comment]
@ChadScott 
SR is trying to open "D:_MEDIA\reign.s01e04.720p.hdtv.x264-killers.mkv"

this path is accessible? I neve saw a path with "_"

**Comment by fernandog** [comment]
@ChadScott provide full logs. use pastebin

**Comment by ladygaming** [comment]
SR is trying to open "D:_MEDIA\reign.s01e04.720p.hdtv.x264-killers.mkv"

D:\_media\ 

is right, i have a _media folder. 

I have no issues with SickBeard picking up this folder, i have all sorts of issues with SR unfortunately. 

For now i went back to SB until i can figure out the issues that SR is giving me.

**Comment by mauirixxx** [comment]
I'm running into this issue with the show "Pretty Little Liars" - SR will find it and send it to Transmission, but it refuses to process the file afterwards UNLESS I rename the file from "pretty.little.liars" to "Pretty Little Liars"

Looking at the logs (relevant section pasted here: http://pastebin.com/BqXjr0ZT ) it looks like SR is trying to process a tv show literally named "tv" ??

What's odd is that's the only show it does that with.

**Comment by markheloking** [comment]
Please use the issue guidelines when posting an issue. This way the dev team is able to debug your problem. Don't forget to use [markdown](https://guides.github.com/features/mastering-markdown/) on any code and log you want to post in-line.

- [ ] Branch
- [ ] Commit hash
- [ ] Operating system and python version
- [x] What did you do?
- [x] What happened?
- [x] What did you expect?
- [x] Link to a copy/paste of your logfile with clear debug info of the error on [pastebin](http://pastebin.com/) (or in-line using [markdown](https://guides.github.com/features/mastering-markdown/) for small snippets)

**Comment by Bokaii** [comment]
@fernandog Do you mean that using underscore in folder names could cause issues? I am having a similiar problem and I also them in some folders.

Is Sickrage using underscore as wildcards for some reason?

**Comment by Bokaii** [comment]
Apparently my issue had something to do with issue #307 which I also was having even though it was labelled as "fixed" on the Commit I was using.

If I tried to do a restart of Sickrage it would stop, but not start again. After manually restarting Sickrage both the General config page and the manual post processing would work, even though it looked like no update was made to SR.
