### ISSUE TITLE
SickRage Renamer doesn't recognise release-groups properly

### ISSUE THREAD

**Issue by TagForce** [SiCKRAGETV/sickrage-issues#389]
Figured I'd leave this one here.

When renaming episodes, SR wants to rename all the release groups to SiCKRAGE unless the RG name is preceded by a quality followed by a '-'.

So when trying to rename a file called \maindir\Showname\SeasonXX\Showname.EpisodeNR.EpisodeName.ReleaseGroup.Ext it will get renamed to Showname.EpisodeNR.EpisodeName.SiCKRAGE.Ext...
However, when the name is Showname.EpisodeNR.EpisodeName.Quality-ReleaseGroup.Ext it will get renamed properly. (for instance: NCIS.S04E03.Another.One.hdtv-LOL.mp4 will work, but NCIS.S04E03.Another.One.LOL.mp4 will rename to NCIS.S04E03.Another.One.SiCKRAGE.mp4.
This occurs even when the releasegroup field in the DB is correctly filled.

**Comment by fernandog** [comment]
@TagForce SickRage REGEX needs the '-' to know that after that char is the release group.
Othewise there's no way to tell what's the release group

**Comment by TagForce** [comment]
@fernandog
Well, SR does know what the releasegroup is, otherwise it would not attempt to rename it SiCKRAGE.
Besides that, the information is in the database as soon as the scene_release is downloaded. It populates the release_group field in the database perfectly fine. It's just that that specific piece of information is never ever used again for anything as far as I can tell.

So, yeah... Seems like the intention of using it was there, it was just never implemented.

Feature Request, indeed... Use the release_group field in the database to solve unknown release groups, and only when that fails resort to using SiCKRAGE as a generic.

**Comment by TagForce** [comment]
As this is a duplicate of #391 I will close this one. It was my own, and has been fixed by an as-yet unmerged PR.
