### ISSUE TITLE
After air-time of the episode, it is not automatically set to "wanted"

### ISSUE THREAD

**Issue by ajtudela** [SiCKRAGETV/sickrage-issues#390]
In the latest conmmit BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8)  when  the air date pass, the episode doesn't set to wanted

**Comment by fernandog** [comment]
@ajtudela SR must run 24/7. It updates everyday at 3:00am and it's not possible to change this.
an alternative is to enable "update shows at startup" and "backlog search at startup". but will take some time to update everything. that's way it updates at 3:00am
