### ISSUE TITLE
When adding a show: languages dropdown shows only "en"

### ISSUE THREAD

**Issue by gabryk91** [SiCKRAGETV/sickrage-issues#392]
As stated on issue #302 

Before, when adding a new show, I can choose the subtitles language by the dropdown, now the same dropdown shows only "en" and to change language I have to add show, then edit it and change language (on the edit page the dropdown has all languages as was before).
This odd behaviour apparently begin at the time of issue #302.

Latest commit, develop, win 8 x64. No log needed i think.

**Comment by fernandog** [comment]
@gabryk91 this happens in the SickBeard official branch too. It's a feature request then.

**Comment by gabryk91** [comment]
No, it is a request for reintroducing a feature that exists before.
Before when adding a new show the dropdown shown a full list of languages
as the same dropdown currently present in the edit page.
Suddenly after a commit the languages disappeared except for "en".
Il 12/gen/2015 20:33 "Fernando" <notifications@github.com> ha scritto:

**Comment by abeloin** [comment]
Try applying pull request SiCKRAGETV/SickRage#1192, I think it will solve your issue.

**Comment by gabryk91** [comment]
Ok, the pull request works. Can it be merged in the main release?

**Comment by markheloking** [comment]
The release schedule is set as it is. Features will be implemented into development first, and only every release there will be a new release candidate, and after that it will be merged/rebased into the master branch.
This is to improve the stability of the master branch.

**Comment by markheloking** [comment]
Closing since this is fixed in the development branch.
