### ISSUE TITLE
invalid literal for int() with base 10: 'undefined'

### ISSUE THREAD

**Issue by meokey** [SiCKRAGETV/sickrage-issues#393]
SR Version:	BRANCH: (develop) / COMMIT: (32da0199f2690b8b04349ebd495c6a7ad5a2b2f4) 
SR Config file:	/usr/share/SickRage/config.ini
SR Database file:	/usr/share/SickRage/sickbeard.db
SR Cache Dir:	/usr/share/SickRage/cache
SR Arguments:	['--daemon', '--nolaunch', '--pidfile=/var/run/sickbeard/sickrage.pid', '--datadir=/usr/share/SickRage']
SR Web Root:	
Python Version:	2.6.6 (r266:84292, Jan 22 2014, 09:42:36) [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]

It happened when I was trying to change the mark from "Skipped" to "Wanted" for the show. And the Manual Post-Processing script skipped the downloaded video files for this show while I have none in the media repository.

Error

invalid literal for int() with base 10: 'undefined'

Traceback

Traceback (most recent call last): 
File "/usr/share/SickRage/tornado/web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback)) 
File "/usr/share/SickRage/tornado/stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs) 
File "/usr/share/SickRage/tornado/concurrent.py", line 226, in lambda future: callback(future.result())) 
File "/usr/share/SickRage/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result() 
File "/usr/share/SickRage/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "/usr/share/SickRage/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "/usr/share/SickRage/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "/usr/share/SickRage/sickbeard/webserve.py", line 230, in async_call result = function(**kwargs) 
File "/usr/share/SickRage/sickbeard/webserve.py", line 1548, in setStatus if not statusStrings.has_key(int(status)): 
ValueError: invalid literal for int() with base 10: 'undefined' 

Request Info

body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /home/setStatus?show=252571&eps=2x16|2x15|2x14|2x13|2x12|2x11|2x10|2x9|2x8|2x7|2x6|2x5|2x4|2x3|2x2|2x1|1x10|1x9|1x8|1x7|1x6|1x5|1x4|1x3|1x2|1x1|0x1&status=undefined
query_arguments: {'status': ['undefined'], 'eps': ['2x16|2x15|2x14|2x13|2x12|2x11|2x10|2x9|2x8|2x7|2x6|2x5|2x4|2x3|2x2|2x1|1x10|1x9|1x8|1x7|1x6|1x5|1x4|1x3|1x2|1x1|0x1'], 'show': ['252571']}
_start_time: 1421090867.98
headers: {'Accept-Language': 'en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4', 'Accept-Encoding': 'gzip, deflate, sdch', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2267.0 Safari/537.36', 'Dnt': '1', 'Host': 'vhost:8080', 'Referer': 'http://vhost:8080/home/displayShow?show=252571', 'Cookie': 'plushHistPerPage=9999999; plushContainerWidth=100%25; plushMultiOps=1; plushNoTopMenu=0; snatched_view2=list; soon_view2=thumbs; late_view2=list; wanted_view2=details; PPA_ID=3d5t0nmeo57rsv7jbo76nnhl55; webfx-tree-cookie-persistence=wfxt-4+wfxt-6; user="2|1:0|10:1420834048|4:user|44:NzdkNGU3ODQ3MmZlMjE5ZTMwMDc1Nzk4NzliNjM2ZDY=|f321397f6a5d170078e68793ffdc46875826267adc23d53b9b5bd9c5ac01fc8d"'}
host: vhost:8080
version: HTTP/1.1
arguments: {'status': 'undefined', 'eps': '2x16|2x15|2x14|2x13|2x12|2x11|2x10|2x9|2x8|2x7|2x6|2x5|2x4|2x3|2x2|2x1|1x10|1x9|1x8|1x7|1x6|1x5|1x4|1x3|1x2|1x1|0x1', 'show': '252571'}
_finish_time: None
query: show=252571&eps=2x16|2x15|2x14|2x13|2x12|2x11|2x10|2x9|2x8|2x7|2x6|2x5|2x4|2x3|2x2|2x1|1x10|1x9|1x8|1x7|1x6|1x5|1x4|1x3|1x2|1x1|0x1&status=undefined
path: /home/setStatus
_cookies: Set-Cookie: PPA_ID=3d5t0nmeo57rsv7jbo76nnhl55 Set-Cookie: late_view2=list Set-Cookie: plushContainerWidth=100%25 Set-Cookie: plushHistPerPage=9999999 Set-Cookie: plushMultiOps=1 Set-Cookie: plushNoTopMenu=0 Set-Cookie: snatched_view2=list Set-Cookie: soon_view2=thumbs Set-Cookie: user="2|1:0|10:1420834048|4:user|44:NzdkNGU3ODQ3MmZlMjE5ZTMwMDc1Nzk4NzliNjM2ZDY=|f321397f6a5d170078e68793ffdc46875826267adc23d53b9b5bd9c5ac01fc8d" Set-Cookie: wanted_view2=details Set-Cookie: webfx-tree-cookie-persistence=wfxt-4+wfxt-6
method: GET
remote_ip: 192.168.0.200

View Log(Errors)

**Comment by meokey** [comment]
Hi Fernando,

Sorry I now realize that it's a duplicate post but how can I pull the fix?
I'm using Develop. Thank you.

Best Regards,
Biao

**Comment by fernandog** [comment]
You can edit your local file. See the first issue about it.
