### ISSUE TITLE
Logging just stops

### ISSUE THREAD

**Issue by matmat07** [SiCKRAGETV/sickrage-issues#395]
This happened a couple of time. I'm not sure what cause it, I think it's trying to add a show.

Anyway, I restarted client, and C:\SickRage\Logs\sickrage.log just won't change anymore. I can see cpu usage spike, so something is hapenning.

**Comment by fernandog** [comment]
@matmat07 did you change the log level to DEBUG in the UI?

**Comment by matmat07** [comment]
Yes I did. Also, shouldn't that be automatic when viewing the file directly? I mean, I guess the default viewing mode just skip some lines right?

On Jan 13, 2015 6:09 AM, Fernando <notifications@github.com> wrote:
@matmat07 did you change the log level to DEBUG in the UI?

---

**Comment by fernandog** [comment]
@matmat07 SR will only show one log file. If your log file is only 10kb, it will show only a few lines. It does not show all files from /SickRage/Logs

**Comment by matmat07** [comment]
I've only got that one and the .5 one. Also, they are both exactly 1,024KB.

**Comment by fernandog** [comment]
@matmat07 stop SR, delete them and restart. monitor the log files.

**Comment by matmat07** [comment]
That worked. Any ideas why it happened? Or something I could change to make sure it won't again?

On Jan 14, 2015 5:33 AM, Fernando <notifications@github.com> wrote:
@matmat07 stop SR, delete them and restart. monitor the log files.

---

**Comment by fernandog** [comment]
maybe SR didn't find the other numbers and got lost creating the log
