### ISSUE TITLE
[Feature Request] Add globalsearch support from usenetserver.com

### ISSUE THREAD

**Issue by rickytin** [SiCKRAGETV/sickrage-issues#398]
I have a Usenetserver account and I would like to know if there is a way to add the globalsearch from usenetserver as a provider.

Thanks for the help.

**Comment by markheloking** [comment]
Located over at https://www.usenetserver.com/ I believe.

**Comment by educatedwarrior** [comment]
Please add this.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
