### ISSUE TITLE
regex parsing for quality seems incorrect on backlog search

### ISSUE THREAD

**Issue by rui-nar** [SiCKRAGETV/sickrage-issues#399]
Hi

When running a backlog search on a show for which I have requested HD720 quality I get:
>2015-01-13 16:33:12 DEBUG    SEARCHQUEUE-BACKLOG-83610 :: [KickAssTorrents] :: Ignoring result Glee.Season.5.Episode.3.720p.HDTV.-.GlowGaze because we don't want an episode that is Unknown
>2015-01-13 16:33:12 DEBUG    SEARCHQUEUE-BACKLOG-83610 :: [KickAssTorrents] :: Don't want this quality, ignoring found episode
>2015-01-13 16:33:12 DEBUG    SEARCHQUEUE-BACKLOG-83610 :: [KickAssTorrents] :: any,best = [4, 32, 128] [] and found 32768
>2015-01-13 16:33:12 DEBUG    SEARCHQUEUE-BACKLOG-83610 :: [KickAssTorrents] :: Checking if found episode 5x3 is wanted at quality Unknown
>2015-01-13 16:33:12 DEBUG    SEARCHQUEUE-BACKLOG-83610 :: [KickAssTorrents] :: Using cached parse result for: Glee.Season.5.Episode.3.720p.HDTV.-.GlowGaze
where the episode is being ignored.

The following case is also not reading the quality correctly:
>2015-01-13 16:33:12 DEBUG    SEARCHQUEUE-BACKLOG-83610 :: [KickAssTorrents] :: Ignoring result Glee.S05E07.HDTV.x264-LOL[ettv] because we don't want an episode that is SD TV
>2015-01-13 16:33:12 DEBUG    SEARCHQUEUE-BACKLOG-83610 :: [KickAssTorrents] :: Don't want this quality, ignoring found episode
>2015-01-13 16:33:12 DEBUG    SEARCHQUEUE-BACKLOG-83610 :: [KickAssTorrents] :: any,best = [4, 32, 128] [] and found 1
>2015-01-13 16:33:12 DEBUG    SEARCHQUEUE-BACKLOG-83610 :: [KickAssTorrents] :: Checking if found episode 5x7 is wanted at quality SD TV
>2015-01-13 16:33:12 DEBUG    SEARCHQUEUE-BACKLOG-83610 :: [KickAssTorrents] :: Parsed Glee.S05E07.HDTV.x264-LOL[ettv] into Glee - S5E7 [ANIME VER: -1] [GROUP: LOL[ettv]] [ABD: False] [ANIME: False] [whichReg: ['standard']]

My configuration (I hope I'm at the latest develop version) and full logs follow. Should you need anything else let me know.

Cheers and congrats on the great work so far.
Rui

SR Version:BRANCH: (develop) / COMMIT: (8b84e4f4bc6cdebdc605438e9e75d15f1133d65e) 
SR Config file:/usr/local/sickbeard-custom/var/config.iniSR
Database file:/usr/local/sickbeard-custom/var/sickbeard.dbSR 
Cache Dir:/usr/local/sickbeard-custom/var/cacheSR 
Arguments:['--daemon', '--pidfile', '/usr/local/sickbeard-custom/var/sickbeard-custom.pid', '--config', '/usr/local/sickbeard-custom/var/config.ini', '--datadir', '/usr/local/sickbeard-custom/var/']

Source https://github.com/SiCKRAGETV/SickRage/

My logs: http://pastebin.com/ejkXTSdz

**Comment by fernandog** [comment]
@rui-nar that torrents are missing the "x264". this info is needed to know the quality

**Comment by rui-nar** [comment]
Hi @fernandog

On the first example there's 720p.HDTV which i was under the impression should be enough.

On the second example there's x264 on the filename:
Glee.S05E07.HDTV.x264-LOL[ettv]

Cheers 
Rui

**Comment by fernandog** [comment]
yes. but is SDTV and seems your wanted quality is HD

**Comment by rui-nar** [comment]
@fernandog: sorry for my misunderstanding. I went through the doc and got it working using custom quality with a combination of qualities. Thanks again, you can close this issue.

**Comment by rui-nar** [comment]
@fernandog: btw, awesome support on your side, quick and effective.
