### ISSUE TITLE
[Feature Request] Add implement _moveAndHardlink

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#40]
<a href="https://github.com/shadowcode0"><img src="https://avatars.githubusercontent.com/u/10085295?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [shadowcode0](https://github.com/shadowcode0)**
_Friday Dec 05, 2014 at 10:19 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/1023 (1 comment(s))_

----

Hello!

I noticed that the symbolic link option in post-processing actually moves the file(s) and places a symbolic link at the origin. I think that's a great idea, however the 'hardlink' option doesn't work in the same way (it's a direct hardlink of [src]->[dst], and that's throwing a bit of a spanner in things).

I was wondering if there's a reason for that, or if I should go ahead and implement it and issue a pull request.

Cheers,
SC

References:
  https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/postProcessor.py#L968

**Comment by WebSpider** [comment]
What about making the symlink option configurable:

either: 1) Move media to Show dir and symlink from download dir to show dir (as current)
or 2) Keep media in download dir and symlink from show dir to download dir?

Sounds to me like it would be a simple fix, and is applicable to just about any situation

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
