### ISSUE TITLE
Add Existing Show - Search fails due to underscores for spaces

### ISSUE THREAD

**Issue by Thr3d** [SiCKRAGETV/sickrage-issues#400]
Request for search to work with underscores substituted for spaces in show names.

Example
Black_Lagoon
Search Results: No results found, try a different search.

Black Lagoon
Black Lagoon (started on 2006-04-09) [theTVDB]

**Comment by eXistenZNL** [comment]
This also happens with "Greys Anatomy" (which is more managable filesystem wise)  => "Grey's Anatomy".

Don't know how far the creators are willing to go to make our lives easy and how SickRage should know the right spelling though.

**Comment by fernandog** [comment]
@Thr3d sorry I'm asking but why are you searching with "_"? Why would you type it instead of space?

**Comment by Thr3d** [comment]
I'm adding existing shows. Its pretty typical for most *inux users to use _ in substitution for spaces as it doesn't require escaping the space to type in a directory or file name.

And example of that with an ls
 ls ./media/Black_Lagoon/  # This can be completed with autocomplete and no escaping
 vs
 ls ./media/Black\ Lagoon/

**Comment by fernandog** [comment]
@Thr3d now I understood. You want to create the folder with underscore.

you can first create the folder, then add existing shows. SR will keep your folder.

**Comment by Thr3d** [comment]
True, thats more or less whats already been done by adding the existing shows since they already exist.
However this was a major pain due to having to remove a few hundred underscores for searching all of my tv shows. (recently migrated to SickRage)

**Comment by eXistenZNL** [comment]
Also, ZSH (+ Oh-My-ZSH)'s autocomplete can cope much better with spaces / autocompletion than Bash. Should fix your problems.
