### ISSUE TITLE
Can't go into SickRage UI on ASUSTOR running the latest ADM version

### ISSUE THREAD

**Issue by EirikUtvik** [SiCKRAGETV/sickrage-issues#402]
Log:
http://pastebin.com/hRNqRnXd
No errors as far as I can see.

Running ADM 2.3.0.RD51
SickRage v20141223

Had just installed SickRage on my NAS (Asustor 304T), tried to get into the UI, but get into the browser error page instead saying that the webpage isnt available.

**Comment by fernandog** [comment]
@EirikUtvik 
try enter SickRage folder and running "python SickBeard.py"
see the messages and possible errors

**Comment by EirikUtvik** [comment]
There are no errors then either, but just found out the problem I think. When I click on SickRage on my ADM dashboard it takes me to "IP:7073", but it seems SickRage is starting on port 8081. I got in on that port at least. Typo perhaps?

**Comment by EirikUtvik** [comment]
"/usr/local/AppCentral/python/lib/python2.7/site-packages/Cheetah/Compiler.py:1509: UserWarning:
You don't have the C version of NameMapper installed! I'm disabling Cheetah's useStackFrames option as it is painfully slow with the Python version of NameMapper. You should get a copy of Cheetah with the compiled C version of NameMapper.
  "\nYou don't have the C version of NameMapper installed! "
^Z[1]+  Stopped                    python SickBeard.py
"

Also got this though.

**Comment by EirikUtvik** [comment]
And I can't access it when starting it from ADM. Only when starting it manually.

**Comment by fernandog** [comment]
so it's not a SR issue. it's your startup script.

**Comment by EirikUtvik** [comment]
I installed this - The problem could be with that package I guess.
http://www.asustor.com/apps/app_detail?id=210

**Comment by fernandog** [comment]
@EirikUtvik try this: https://sickrage.tv/forums/forum/help-support/general-support/14420-sickrage-installation-guides-windows-mac-osx-linux-raspberry-pi

**Comment by EirikUtvik** [comment]
Can't install it like that. Might corrupt the ADM installation.

**Comment by fernandog** [comment]
i can't help you furthur than that. sorry

**Comment by abeloin** [comment]
@EirikUtvik If you still have the issue, I see there is an update from January 25th that might help you.

http://www.asustor.com/apps/app_detail?id=210

**Comment by EirikUtvik** [comment]
I installed the latest one and it worked great. Thanks a lot for the link, abeloin.
