### ISSUE TITLE
Change quality of all tv shows

### ISSUE THREAD

**Issue by rui-nar** [SiCKRAGETV/sickrage-issues#403]
Hi
I have 66 tv shows, is there a way/ place to change the quality of all the shows without having to do it one by one?
Thanks

**Comment by eXistenZNL** [comment]
This is not a bug nor an issue, and could have been asked on IRC imho :)

Anyway, go to Manage -> Mass Update, select all shows in the top left, click Edit selected in the bottom left, select the new quality, and save. Yay SickRage for making our lives easy.

**Comment by rui-nar** [comment]
Awesome, than you so much. 

I'm not much of an IRC user ... I wouldn't even know where to start :p

Thanks for this
