### ISSUE TITLE
[Feature Request] Anime: Add options for the fansub groups

### ISSUE THREAD

**Issue by John-Gee** [SiCKRAGETV/sickrage-issues#405]
The easy ones:
-The ability to specify the fansub group in the last tab of the add new show (where we specify the quality we want).
That would be very helpful, as now I have to first add the show, then wait, then add the fansub group, hopefully before it found anything, if not I may have to cancel that download and re-search...

- Another useful option would be global denied groups specified in global options, unless I specify them as whitelist for a show never download them (yes I am thinking of horriblesubs)

The more difficult one:
- An option to let SickRage pick up one fansub group and stick to it, most of the times I don't really care which group it is, but I do want to only have one group (if possible). Having SickRage just randomly pick episode is usually a waste of bandwidth till I realize I forgot to specify a group.

One way it could work would be:
1- Pick the highest rated (english) fansub group on anidb
2- See if we have everything available for that group
3- if yes, go with it and stick to it, if no go back to 1- and pick the next one
(4- if no group has all available, ask the user, or just go back to mixing the groups, but the least that is feasible).

**Comment by TuRDMaN** [comment]
Just chiming in to say that I agree with all of these suggestions, and they would greatly improve my experience with SickRage!

**Comment by John-Gee** [comment]
If you see any improvement that can be made to my suggestions, feel free to specify them as well.

**Comment by yongbi85** [comment]
I would add it would be nice to have a system of download and archive based on fansub group too for anime.
For example I want sickrage to download the release of HorribleSubs first so I can watch it, but I want him to get UTW or Hatsuyuki or w/e release as archived fansub group.

**Comment by John-Gee** [comment]
That's actually pretty fair indeed!

**Comment by tutti21** [comment]
I would like this feature too, that I can select a default subgroup or so.

**Comment by John-Gee** [comment]
I've just realized you added the first part already, thank you so much for this!

**Comment by mbxplex** [comment]
Hey guys, I am new to SickRage and I noticed this feature listed at the bottom when adding a new show and I was very interested in how the Whitelist / Blacklist feature works ... 

Can someone explain the purpose of Whitelist / Blacklist if you have the time? 

Thanks!

**Comment by fernandog** [comment]
@Thraxis develop that. maybe he can explain

**Comment by mbxplex** [comment]
Hey @Thraxis , would you mind explaining how this works and the options I would have by using this feature? At first, I thought it would allow me to use "preferred words" to pull by but I don't believe that's the case.

**Comment by John-Gee** [comment]
I don't think this bug tracker is really the place for that kind of question...
But in simple terms, words on the whitelist are required for an episode to be picked up, and words on the blacklist will prevent the episode from being picked up.

**Comment by mbxplex** [comment]
@John-Gee thanks for the reply. 

So, are whitelist words the same as required words?

**Comment by John-Gee** [comment]
That's at least how I use it.

As for future questions, I think the sickrage forums would be a better place than a bug tracker.
(https://sickrage.tv/forums/forum/)

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!

**Comment by John-Gee** [comment]
I've recreated it at http://feathub.com/SiCKRAGETV/SickRage/+51, including yongbi85's suggestion. 
Please vote :)
