### ISSUE TITLE
No nfo written

### ISSUE THREAD

**Issue by John-Gee** [SiCKRAGETV/sickrage-issues#406]
Not sure what is happening, but for a few days SickRage has stopped writing new nfos, both for new shows or for new episodes of current shows. I am on latest master.
I see this in the log "SHOWQUEUE-ADD :: 279980: Writing NFOs for show" but nothing seems to come out of it...
I don't see any error in the error log.

Thanks!

**Comment by John-Gee** [comment]
Oh it seems to be because the XMBC profile got renamed to Kodi, by looking at my current settings, there was nothing set for Kodi, so please in future scenarios please import from the previous profile if possible.
Thanks

**Comment by markheloking** [comment]
@John-Gee please use markdown and the issue posting guidelines in the future.

**Comment by John-Gee** [comment]
I will, I apologize for this.
