### ISSUE TITLE
SickRage failing to unrar, leaving the rar thinking it was processed.

### ISSUE THREAD

**Issue by jleeh** [SiCKRAGETV/sickrage-issues#409]
Branch: develop
Commit: 0bb84466d06ca068e09d5f8bc2bbb828c598963a
OS/Python: Centos 6.6/2.6.6 (r266:84292, Jan 22 2014, 09:42:36) [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]
What I did: Nothing, related to post processing shows which are rar'd
What happened: When trying to extract the rar archive, it fails to do so, but SickRage thinks it does so it tries to move the file and reports that there's no file there. If I then extract the rar manually, it thinks it's already processed the show and skips it.
What I expected: Correct unraring and post processing.

Post-Processing Log:
Packed Releases detected: ['futurama.s07e01.bdrip.xvid-demand.rar']
Unpacking archive: futurama.s07e01.bdrip.xvid-demand.rar
You're trying to post process a video that's already been processed, skipping
Archive file already post-processed, extraction skipped: futurama.s07e01.bdrip.xvid-demand.avi

I lost the errors, when updating the version which didn't rectify the issue. The logs would show that it unpacked the file and give a 'Error 2: No such file or directory' after unpacking.

**Comment by fernandog** [comment]
need full logs
