### ISSUE TITLE
Read quality from metadata

### ISSUE THREAD

**Issue by JonScaife** [SiCKRAGETV/sickrage-issues#410]
I have my TV episodes named without the quality in the filename.  This leads to SickRage showing them all as "unknown" quality.  However, I use a different program to scan the actual files, and add information on the file quality to the metadata which is [filename].xml in my case.  When doing a rescan or full update it would be great if there was an option to get SickRage to read and use this data.
There are various possible fields, e.g...
  &lt;VideoBitrate&gt;4098000&lt;/VideoBitrate&gt;
  &lt;VideoCodec&gt;x264&lt;/VideoCodec&gt;
  &lt;VideoCodecType&gt;H.264&lt;/VideoCodecType&gt;
  &lt;VideoCodecRaw&gt;AVC&lt;/VideoCodecRaw&gt;
  &lt;VideoHeight&gt;720&lt;/VideoHeight&gt;
  &lt;VideoQuality&gt;Great (720p HD)&lt;/VideoQuality&gt;
  &lt;VideoWidth&gt;1280&lt;/VideoWidth&gt;

**Comment by pct00** [comment]
would be even better if sickrage could do it without external programs to check quality :)

**Comment by JonScaife** [comment]
Absolutely agree, but small steps.  I figured implementing this would be a lot easier.  Analysing files and working out the quality has been mentioned before and is much more complex.

**Comment by markheloking** [comment]
I believe sickrage already uses mediainfo to check the quality of the videos, but I might be incorrect on that part.

**Comment by wripet** [comment]
I definitely doesn't. Or if it does, it does it terribly wrong.

**Comment by Grubs** [comment]
I like this option too! I recently moved from SickBeard to SickRage. I had to copy the quality across for 250 shows and it wasn't the greatest thing I've ever done! While it picks up HD / SD ok it doesn't remember the 720p WEB-DL / HDTV / 720p BluRay  or SDTV / SD DVD etc... would be nice if it added these to the metadata when it creates them too!

**Comment by fernandog** [comment]
@Tagforce before using media info, isn't possible to read metadata before - if exists?

**Comment by TagForce** [comment]
@fernandog I think this was an earlier FR as well. Just so that in case of a database failure SR would be able to get the critical DB info from nfo files in the folders. I have it on my to do for future improvements.

**Comment by fernandog** [comment]
@Tagforce what about the .nfo that comes with the torrent? There is quality info there. Isnt?

**Comment by TagForce** [comment]
@fernandog that would require a new parser. Is an option but harder to implement

**Comment by fernandog** [comment]
@JonScaife we will implement mediainfo in the future. closing this
