### ISSUE TITLE
Subtitles not working in latest develop version

### ISSUE THREAD

**Issue by krash1220** [SiCKRAGETV/sickrage-issues#411]
I'm on Linux Mint 17 and decided to try the latest develop version but I can't configure subtitles. It let's me choose subtitle plugins, I choose Opensubtitles and Addic7ed but when I go to Subtitles search and choose Search subtitles, it won't let me choose a language, it's just a empty black box with no search feature and when I go back to subtitle plugins the ones I checked are unchecked. I tried using the same config file that I use with master but it still won't work.

**Comment by fernandog** [comment]
follow the guidelines: https://github.com/SiCKRAGETV/sickrage-issues/issues
