### ISSUE TITLE
sickrage not deleting lower quality thumbs

### ISSUE THREAD

**Issue by wripet** [SiCKRAGETV/sickrage-issues#412]
When SR downloads and postprocesses a higher quality of an episode, it doesn't remove the lower quality thumb-files.

For instance: HD quality was present, (HD thumb, HD nfo, HD video), after postprocessing the 1080p edition, a 1080p nfo, a 1080p thumb and a correctly renamed 1080p video file existed, the HD nfo file and HD video file got deleted, but the HD thumb.jpg remained. Happens with all higher quality replacements of episodes.

Logfile:
http://pastebin.com/Yzp87r3S

**Comment by fernandog** [comment]
@wripet 
feature request or BUG?

**Comment by wripet** [comment]
Bug of course. It should remove lower quality thumbs, but it doesn't.

**Comment by markheloking** [comment]
Please use the issue guidelines when posting an issue. This way the dev team is able to debug your problem. Don't forget to use [markdown](https://guides.github.com/features/mastering-markdown/) on any code and log you want to post in-line.

- [ ] Branch
- [ ] Commit hash
- [ ] Operating system and python version
- [x] What did you do?
- [x] What happened?
- [x] What did you expect?
- [x] Link to a copy/paste of your logfile with clear debug info of the error on [pastebin](http://pastebin.com/) (or in-line using [markdown](https://guides.github.com/features/mastering-markdown/) for small snippets)

**Comment by fernandog** [comment]
@wripet reply please or will close this issue
