### ISSUE TITLE
Episode info: Tooltip not shown anymore

### ISSUE THREAD

**Issue by abeloin** [SiCKRAGETV/sickrage-issues#415]
Branch: Develop
Commit hash: 0bb84466d06ca068e09d5f8bc2bbb828c598963a
Linux, Python 2.7.5

Tooltip aren't shown anymore for episode info.
JS Console Error: TypeError: r.browser is undefined

**Comment by fernandog** [comment]
@abeloin 

If I open SR coming episodes (Chrome) I got this in the javascript console:
```
 Failed to load resource: net::ERR_CACHE_MISS
```

is this related?

**Comment by abeloin** [comment]
It's an issue with Chrome which is fixed in version 40.
See https://code.google.com/p/chromium/issues/detail?id=424599#c23 for more info.
