### ISSUE TITLE
Plex notification fails on current Plex Media Server 0.9.11.4

### ISSUE THREAD

**Issue by oztiks** [SiCKRAGETV/sickrage-issues#419]
https://sickrage.tv/forums/forum/help-support/bug-issue-reports/11123-issue-new-pms-update-breaks-plex-notification-library-refresh

It appears a change in PMS now requires a token based authentication system vs just username+password. If you update to 0.9.11.4, notifications from SickRage to Plex will fail. (Authentication error).

It looks like someone has written a script for nzbget that might be a good base for the updated plex notifier for sickrage.

http://nzbget.net/forum/viewtopic.php?f=8&t=1393

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1190

**Comment by markheloking** [comment]
Closing since this should be fixed with the latest pull. Please report back if the issue persists.
