### ISSUE TITLE
Problem downloading subtitles: STATUS 404

### ISSUE THREAD

**Issue by rui-nar** [SiCKRAGETV/sickrage-issues#423]
Hi
I can't seem to download any subtitles, I'm getting a "status 404": http://pastebin.com/0mfrkLAz

Here's the subtitle section of the /usr/local/sickbeard-custom/var/config.ini:
Subtitles]
use_subtitles = 1
subtitles_languages = en
SUBTITLES_SERVICES_LIST = "itasa,subtitulos,tvsubtitles,opensubtitles,addic7ed,usub,subscenter,thesubdb,subswiki"
SUBTITLES_SERVICES_ENABLED = 0|0|1|1|0|1|1|1|1
subtitles_dir = ""
subtitles_default = 1
subtitles_history = 1
subtitles_finder_frequency = 1
subtitles_multi = 1

By the way, in the GUI i'm seeing all subtitle providers as active and no language in the language box even though the config above should apply ... Right ?

And here's my config:
SR Version:BRANCH: (develop) / COMMIT: (0bb84466d06ca068e09d5f8bc2bbb828c598963a)
SR Config file:/usr/local/sickbeard-custom/var/config.ini
SR Database file:/usr/local/sickbeard-custom/var/sickbeard.db
SR Cache Dir:/usr/local/sickbeard-custom/var/cache
SR Arguments:['--daemon', '--pidfile', '/usr/local/sickbeard-custom/var/sickbeard-custom.pid', '--config', '/usr/local/sickbeard-custom/var/config.ini', '--datadir', '/usr/local/sickbeard-custom/var/']
SR Web Root:Python Version:2.7.8 (default, Dec 12 2014, 21:20:40) [GCC 4.7.3 20130102 (prerelease)] 
Homepage http://www.sickrage.tv/ 
Forums http://sickrage.tv/forums/ 
Source https://github.com/SiCKRAGETV/SickRage/

**Comment by fernandog** [comment]
@rui-nar please remove your password from the LOG

can you download that subtitle using the browser? 
maybe that file was removed from the subtitle server

**Comment by fernandog** [comment]
@rui-nar also don't enable a lot of subtitle services otherwise you will get high cpu usage

**Comment by rui-nar** [comment]
@fernandog thanks for the remark on the pwd, don't know how I managed to copy all accorss (that's the limitations of the smartphone). I changed the pastebin link to a new one without the pwd.

To answer your quesiton, if sickrage follows the order of the providers as in the config.ini file then tvsubtitles should be one used in that case the answer is "yes", the files exist and are downloadable (just tried).

**Comment by fernandog** [comment]
@rui-nar it's strange because looks like its working for another episodes. the status it's not 404. Maybe it's some problem with the subtitle provider.

**Comment by rui-nar** [comment]
@fernandog if I disable a provider do I need to restart for that change to take effect? I'll try disabling tvsubtitles and see ...

**Comment by fernandog** [comment]
I don't think so.

**Comment by rui-nar** [comment]
hi again @fernandog , sorry fpr taking so long t answer.

I confirm that something weird is going on with the subtitles config section.
To start with, I can't save any changes I do to the languages and providers, ie, I can save but the changes are not kept. To test providers I've been modifying the config.ini file and then restarting sickrage.

even disabling tvsubtitles, the first provider on the list, I still get the STATUS IS 404 error and no subtitles are downloaded 


2015-01-17 18:03:44 DEBUG    SHOWQUEUE-SUBTITLE :: 210841: Downloading subtitles for episode 2x13
2015-01-17 18:03:44 DEBUG    SHOWQUEUE-SUBTITLE :: 210841: Saving episode details to database
2015-01-17 18:03:44 DEBUG    SHOWQUEUE-SUBTITLE :: STATUS IS 404
2015-01-17 18:03:44 DEBUG    SHOWQUEUE-SUBTITLE :: 210841: No subtitles downloaded for episode 2x13

do you need me to test anything else ?

btw, is the subtitles retrieval process different between the one used in standard post-processing and the one used when clicking the "Download Subtitles" button on the show page ?

thanks

**Comment by abeloin** [comment]
@rui-nar 
Try applying SiCKRAGETV/SickRage/pull/1192 , it should fix the issue of not been able to save changes in the config section.

By the way, "STATUS IS 404" is not an HTTP 404, it's the episode status in the db(first 4 = Downloaded)

Also looking at the files searched in the log provided, it look like it truly cannot find a sub for that file hash.

Example: Alphas.S02E04.720p.HDTV.x264-IMMERSE.mkv
* opensubtitle(http://www.opensubtitles.org/en/search/sublanguageid-all/imdbid-2156046):
 *No release for immerse in english.
* tvsubtile(http://www.tvsubtitles.net/episode-40192.html):
 * Only available in Greek
* subswiki(http://www.subswiki.com/serie/Alphas/2/4/When_push_comes_to_shove_):
 * Spanish only
* subscenter(http://subscenter.cinemast.com/he/subtitle/series/alphas/2/4/):
 * Hebrew
* u-sub(http://www.u-sub.net/)
 * French only

**Comment by fernandog** [comment]
thanks @abeloin

**Comment by rui-nar** [comment]
Yes, thanks everybody for the help.

Just a newbie question, what would the git command line be to pull the #1192 commit to my local copy?

Thanks
Rui

**Comment by abeloin** [comment]
@rui-nar 
git cherry-pick 28f75bf91dd21aaef62b1dd517ee4d1668d85dd1

**Comment by rui-nar** [comment]
thanks @abeloin but I'm getting:
DiskStation> /usr/local/git/bin/git cherry-pick 28f75bf91dd21aaef62b1dd517ee4d1668d85dd1
fatal: bad object 28f75bf91dd21aaef62b1dd517ee4d1668d85dd1

can you assist ?

**Comment by abeloin** [comment]
@rui-nar You need to run the command inside sickrage folder, but there's need for it anymore as pull request SiCKRAGETV/SickRage#1192 is now in the develop branch.

So just force a check update in sickrage and make sure your on the latest commit.
