### ISSUE TITLE
Need to replace TVTorrents Provider with Shazbat.tv

### ISSUE THREAD

**Issue by ryanf86** [SiCKRAGETV/sickrage-issues#425]
Now that TVTorrents.com is no longer in use and they have now moved onto http://www.shazbat.tv/login the python script for this site needs to be updated.

I have provided a copy of the rss feed for the new site with my passkey removed.

http://www.shazbat.tv/rss/recent?passkey=[private]

Are you able to make the necessary changes?

I have attempted to add this as a custom provider but all i get back in the log is below. Not sure why it cannot find and snatch episodes because when i add the rss to uTorrent they show up and can be downloaded:

```
SR Version: BRANCH: (develop) / COMMIT: (0bb84466d06ca068e09d5f8bc2bbb828c598963a) 
SR Config file: /Users/ryan/SickRage/config.ini
SR Database file: /Users/ryan/SickRage/sickbeard.db
SR Cache Dir: /Users/ryan/SickRage/cache
SR Arguments: []
SR Web Root:

Python Version: 2.7.6 (default, Sep 9 2014, 15:04:36) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
OS Version: OSX 10.10.2
```

```
2015-01-16 12:34:22 INFO     SEARCHQUEUE-MANUAL-269653 :: Unable to find a download for: [The Goldbergs (2013) - 2x11 - The Darryl Dawkins Dance]
2015-01-16 12:34:22 INFO     SEARCHQUEUE-MANUAL-269653 :: [SHAZBAT.TV] :: Performing episode search for The Goldbergs (2013)
2015-01-16 12:34:22 INFO     SEARCHQUEUE-MANUAL-269653 :: Building internal name cache for The Goldbergs (2013)
2015-01-16 12:34:22 INFO     SEARCHQUEUE-MANUAL-269653 :: No scene exceptions update needed
2015-01-16 12:34:22 INFO     SEARCHQUEUE-MANUAL-269653 :: Beginning manual search for: [The Goldbergs (2013) - 2x11 - The Darryl Dawkins Dance]
2015-01-16 12:33:49 INFO     SEARCHQUEUE-MANUAL-250078 :: Unable to find a download for: [Web Therapy (2011) - 4x10 - Lies and Alibis]
2015-01-16 12:33:49 INFO     SEARCHQUEUE-MANUAL-250078 :: [SHAZBAT.TV] :: Performing episode search for Web Therapy (2011)
2015-01-16 12:33:49 INFO     SEARCHQUEUE-MANUAL-250078 :: Building internal name cache for Web Therapy (2011)
2015-01-16 12:33:49 INFO     SEARCHQUEUE-MANUAL-250078 :: No scene exceptions update needed
2015-01-16 12:33:49 INFO     SEARCHQUEUE-MANUAL-250078 :: Beginning manual search for: [Web Therapy (2011) - 4x10 - Lies and Alibis]
```

**Comment by Jamyn** [comment]
Right now, any access to http://www.shazbat.tv/ is returning 403 (Forbidden). Sounds like they're still not quite stable.

**Comment by datagutt** [comment]
@Jamyn http://www.shazbat.tv/login works just fine. Looks like only front page returns 403.
Though, not all tvtorrents.com accounts have access to shazbat.tv. Mine is non-working for example.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1199

**Comment by ryanf86** [comment]
@lussierj 

I saw your post over at issue https://github.com/SiCKRAGETV/sickrage-issues/issues/328#issuecomment-69821517  and in your log you have Shazbat Recent & Followed. Where you able to add your RSS link and get Sickrage to snatch episode from there?

**Comment by andofrjando** [comment]
I don't think you'll be able to use the RSS feed for Shazbat for the time being due to Sickrage issue #47: Custom Torrent Providers. If you look closely in your Sickrage settings, after you add http://www.shazbat.tv/rss/recent?passkey=########, you'll notice Sickrage is inserting a "/" in front of the "?". This changes the URL to http://www.shazbat.tv/rss/recent/?passkey=########, which is resulting in a HTTP404 response.

**Comment by fernandog** [comment]
@Abeloin is this easy to fix, isn't? if url endswith ? then don't add the slash

**Comment by abeloin** [comment]
Let me check

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/providers/rsstorrent.py

here its replaces/remove. but don't add

**Comment by abeloin** [comment]
@fernandog It do it's a dict push to self.urls and that regular expression remove if there a slash at the end

I'm unable to replicate the behavior in master and develop:
```
2015-02-11 09:52:28 DEBUG    Thread-49 :: TorrentRssCache cache update URL: http://yukinrss.net/doki-bt.rss?passkey=12345678
```

**Comment by andofrjando** [comment]
Is this it? https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/config.py#L330

**Comment by abeloin** [comment]
That's use in webserve.py for nzb and torrent providers.

For rss, it's call:
* TorrentRssCache._getRSSData()
  * https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/providers/rsstorrent.py#L168
* TVCache.getRSSFeed()
  * https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/tvcache.py#L142
* RSSFeeds.getFeed():
  * https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/rssfeeds.py#L38
* Which call feedcache

**Comment by abeloin** [comment]
@andofrjando Have you put the passkey into the cookies section? It should be entered into the url only:
![Imgur](http://i.imgur.com/ZXe6HCk.png)

**Comment by andofrjando** [comment]
Definitely in the URL, just like in your screen shot. Using the master branch, as soon as you hit save, then reload the page, the slash is put in. I have just tested this: https://github.com/SiCKRAGETV/SickRage/commit/82da3171cdf1e963fd72825aa50a6a97af0e6867 on the master branch, and it has solved the issue.

**Comment by abeloin** [comment]
Your entirely right, my apologies. I forgot to reset my master branch I use, which included some patches while I was debugging something else.

Clean_url is called in https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/webserve.py#L4169

**Comment by andofrjando** [comment]
No problems. :)

**Comment by dirkr07** [comment]
Did I miss the part where you guys provided a fix or am I just not knowledgeable enough? :)
Still hoping both the custom providers get fixed and Shazbat get added!..

**Comment by andofrjando** [comment]
Here is the fix for getting custom torrent providers to work:
In your Sickrage installation folder, go into the sickbeard folder, and find the file config.py. Open it in a text editor. Go to line number 329, where it has this code:
```
        if not path.endswith('/'):
            basename, ext = ek.ek(os.path.splitext, ek.ek(os.path.basename, path))  # @UnusedVariable
            if not ext:
                path = path + '/'
```
replace those lines with this:
```
        if not path:
            path = path + '/'
```
It is really important that there are 8 spaces at the start of ```if not path:``` and 12 spaces at the start of ```path = path + '/'```
Save the file, and restart Sickrage. You should now be able to add the RSS feed for a custom torrent provider without the URL getting accidentally altered by Sickrage. You will also need to add ```&fname=true``` on to the end of the URL.
Editing the config.py file is just a temporary fix. Until this fix is included in the official Sickrage master brach (it is currently included in the development branch) then Sickrage updates, may overwrite your changes. In this case you may have to go and make those line changes again. You'll be able to tell if it's been overwritten by looking at the feed URL in you Sickrage custom torrent provider settings and seeing if that naughty ```/``` has been automatically added in front of the ```?```

**Comment by dirkr07** [comment]
Thanks for the detailed description!

**Comment by fernandog** [comment]
the main feature request of @ryanf86 is still open.

can someone that is using MASTER branch AND have a Shazbat.tv login, please change the url of TVTorrents in the /providers directory to the Shazbat.tv url and see if works?

**Comment by andofrjando** [comment]
I have a Shazbat login, and have made the changes to introduce this feature request. I'll be making a pull request into the develop branch shortly.

**Comment by fernandog** [comment]
@andofrjando fully tested?

**Comment by andofrjando** [comment]
I have tested it and is working. Bear with me though, this is the first time I've made a contribution to a open source project. :)

**Comment by fernandog** [comment]
@andofrjando no problem! welcome! I'm new to this too. a couple of years =)

**Comment by andofrjando** [comment]
Okay, pull request submitted. :) Thanks for the help!

**Comment by fernandog** [comment]
@dirkr07 @andofrjando @ryanf86 develop updated. please test and report back

**Comment by andofrjando** [comment]
Working for me.
