### ISSUE TITLE
Request: Add subtitleseeker.com to subtitle plugins

### ISSUE THREAD

**Issue by Ivdbroek85** [SiCKRAGETV/sickrage-issues#426]
Im sorry if this is suggested before, but it would be great if subtitleseeker.com would be added to the plugins.
Its a big website, with loads of subtitles and always quick.
They have a decent api to work with if it helps.
http://www.api.subtitleseeker.com/

**Comment by fernandog** [comment]
request to subtitle developer. Not SR
