### ISSUE TITLE
API error: 'NoneType' object has no attribute 'values'

### ISSUE THREAD

**Issue by rastating** [SiCKRAGETV/sickrage-issues#432]
I develop an application that interfaces with Sick Beard and I have been getting quite a few error reports from users using SickRage with the following output from the ```shows``` API call:

```
{
    "data": {
        "args": [], 
        "error_msg": "'NoneType' object has no attribute 'values'", 
        "kwargs": {}
    }, 
    "message": "SickRage encountered an internal error! Please report to the Devs", 
    "result": "fatal"
}
```

I haven't experienced it personally, but thought I'd report it as I've seen this error report cropping up quite a bit.

**Comment by markheloking** [comment]
Please use the issue guidelines when posting an issue. This way the dev team is able to debug your problem. Don't forget to use [markdown](https://guides.github.com/features/mastering-markdown/) on any code and log you want to post in-line.

- [ ] Branch
- [ ] Commit hash
- [ ] Operating system and python version
- [ ] What did you do?
- [x] What happened?
- [x] What did you expect?
- [ ] Link to a copy/paste of your logfile with clear debug info of the error on [pastebin](http://pastebin.com/) (or in-line using [markdown](https://guides.github.com/features/mastering-markdown/) for small snippets)

**Comment by rastating** [comment]
@markheloking - unfortunately as I mentioned, the error reports are from other people, I have not personally experienced this issue, but I am seeing it crop up quite a lot in automated error reporting.

The above output from SickRage is the only information I have to offer - from the looks of it, something is trying to access a property called ```values``` before the object has been initialised. The API function in question is ```shows``` which can be found here: https://github.com/SiCKRAGETV/SickRage/blob/3147ff2ae59a9557dd5e70e6a45044e423a9d7c8/sickbeard/webapi.py#L2721

To clarify how the URI would look, it would be like this: ```http://ADDRESS_AND_PORT_HERE/api/USERS_API_KEY_HERE/?cmd=shows```

**Comment by markheloking** [comment]
Please check with your users for some information concerning the version & branch they're using. A lot of pullrequest have gone through in the last few hours.

**Comment by rastating** [comment]
The error reports are anonymous unfortunately, so I have no means of further contact. If anyone contacts me directly and reports it I'll be sure to ask them for the extra information.

**Comment by markheloking** [comment]
The dev is very busy (just became a father), so it might take a while for an error like this (with not a lot of info) to get resolved. Just a heads-up.

**Comment by rastating** [comment]
No problem - like I said, not something I've experienced personally, but wanted to give you guys a head's up that it seems to be happening in case no one has reported it before. Congratulations to he dev on becoming a big-daddy dev :)

**Comment by fernandog** [comment]
@rastating please post the URL that you are trying to open.

also try the localhost:8081/apibuilder

Mine is working:
![shows-api](https://cloud.githubusercontent.com/assets/2620870/5799703/94f0833c-9fbc-11e4-905f-9e5cc30c3217.png)

**Comment by rastating** [comment]
@fernandog - the URL is ```http://ADDRESS_AND_PORT_HERE/api/USERS_API_KEY_HERE/?cmd=shows```. I have not experienced this first hand - it has always worked for me, I just saw the error as part of an automated error report for another program, so no extra info as to what version the user was running.

**Comment by fernandog** [comment]
@rastating that another is doing something wrong then. unless we know the URL its calling, there's nothing we can do. API is working as should.
