### ISSUE TITLE
episode download progress on mass update page

### ISSUE THREAD

**Issue by HarleyCarter1234** [SiCKRAGETV/sickrage-issues#433]
Is it possible to add the episode download progress to the mass update page?

I've got loads of shows on the system and it would be very useful to be able to use this to quickly remove all series that have ended, and that i've got 100% of the episodes downloaded .... basically all series that will never need to grab another episode

**Comment by markheloking** [comment]
I would also very much like this feature.

**Comment by HarleyCarter1234** [comment]
good stuff .. i was hoping I wasn't just missing some other easy way of removing those

**Comment by fernandog** [comment]
waiting to be merged. closing as it's working the commit

**Comment by HarleyCarter1234** [comment]
where can I see the commit that relates to this? The thing that lars linked doesn't seem to be relevant

**Comment by fernandog** [comment]
because GIT shows the changed lines. to view entire file you must click "VIEW" on each file

**Comment by HarleyCarter1234** [comment]
that's fine, but are you saying that the commits linked above from Lars are fixing this and that is why it's closed? Or, there are some more commits somewhere else to add this. The stuff from Lars doesn't look like it has anything to do with the issue unless i'm missing something

Default Episode Status is not relevant to the problem here ... or i'll wait and see when it's merged

Thanks for the updates

**Comment by fernandog** [comment]
@HarleyCarter1234 sorry. What you want is already merge in the develop branch

**Comment by HarleyCarter1234** [comment]
any news on when this is likely to be in the master branch? Not sure whether to switch to dev branch for this
