### ISSUE TITLE
No downloads were found

### ISSUE THREAD

**Issue by lucianot54** [SiCKRAGETV/sickrage-issues#434]
I use DownloadStation to download t411 torrent and i have all episodes snatched but there is nothing sent to my nas. I'm trying to investigate but if you have a trick i'm interesting.

I used the last dev branch. Where i can check for the Torrent Search in the code?

Edit:
My synology use the URL to download and with t411, to download the torrent, i need an authentification...

**Comment by markheloking** [comment]
Please use the issue guidelines when posting an issue. This way the dev team is able to debug your problem. Don't forget to use [markdown](https://guides.github.com/features/mastering-markdown/) on any code and log you want to post in-line.

- [x] Branch
- [ ] Commit hash
- [ ] Operating system and python version
- [x] What did you do?
- [x] What happened?
- [x] What did you expect?
- [ ] Link to a copy/paste of your logfile with clear debug info of the error on [pastebin](http://pastebin.com/) (or in-line using [markdown](https://guides.github.com/features/mastering-markdown/) for small snippets)

**Comment by fernandog** [comment]
@lucianot54 did you tested your torrent download at SR? Ther's a "Test connection" button

**Comment by fernandog** [comment]
no reply. closing
