### ISSUE TITLE
Next Show button not working on details page

### ISSUE THREAD

**Issue by udochrist** [SiCKRAGETV/sickrage-issues#436]
BRANCH: (develop) / COMMIT: (ce997c79fe83e0899450f01df2dfc38608935f4c) 

Page navigation seems to have an error currently. I can perfectly use the left arrow button to get to the "previous show", pressing the right arrow button does however not navigate to the next show on the show details page. navigation by dropdown is working.

No Errors or else in any log files to report for this one.

**Comment by abeloin** [comment]
Is there an error in the browser's developer console?

**Comment by fernandog** [comment]
mine is working.

**Comment by udochrist** [comment]
chrome is working for me too.,safari is not working. 
i get 404's for /js/lib/jquery.qtip.min.js.map when i press the next button

**Comment by abeloin** [comment]
The map file error is normal it is for debug purpose.

I know it might be a stupid question, is the currently displayed show in safari the last one in the list?

**Comment by udochrist** [comment]
No. Regardless which show I chose. It looks like safari is reloading the page however. And it was working before the int() value bug end of last year.

**Comment by abeloin** [comment]
@udochrist Try this pull request SiCKRAGETV/SickRage#1200 it should fix the issue. Tested on Yosemite 10.10.1.

**Comment by fernandog** [comment]
@udochrist  please update SR and report back please. Fix was merged

**Comment by udochrist** [comment]
Still working after the merge
