### ISSUE TITLE
No downloads were found.

### ISSUE THREAD

**Issue by bitzorro** [SiCKRAGETV/sickrage-issues#439]
Ive added this show to my library:http://trakt.tv/shows/the-heavy-water-war-stopping-hitler-s-atomic-bomb.  I have kickass enabled as one off my providers and the show can be found when at kickass, and the quality is set to : any in SickRage but no results when sickrage searches for it.

**Comment by fernandog** [comment]
@bitzorro you won't find it. Have you tried searching using browser? 
I suggest manually download this one
