### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Session' in autoProcessTV.py

### ISSUE THREAD

**Issue by meokey** [SiCKRAGETV/sickrage-issues#442]
SABnzbd (v0.7.20) throw out the error message after successful downloading.

the setting is like High +delete sabToSickBeard.py /path/to/repository

*** ***
*** update using the issue guidelines ***
Branch: 
SR Version:	BRANCH: (develop) / COMMIT: (8a740bc1065677c4c555bf465d65c83472a7784c) 
SR Config file:	/usr/share/SickRage/config.ini
SR Database file:	/usr/share/SickRage/sickbeard.db
SR Cache Dir:	/usr/share/SickRage/cache
SR Arguments:	['--daemon', '--nolaunch', '--pidfile=/var/run/sickbeard/sickrage.pid', '--datadir=/usr/share/SickRage']
SR Web Root:	
Python Version:	2.6.6 (r266:84292, Jan 22 2014, 09:42:36) [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]

What did you do? What happened?
When I check SABnzbd, I see the error message below

What did you expect?
Hopefully it will be fixed asap

*** ***

Loading config from /usr/share/SickRage/autoProcessTV/autoProcessTV.cfg

Opening URL: http://localhost:8080/home/postprocess/processEpisode
```python
Traceback (most recent call last):
  File "/usr/share/SickRage/autoProcessTV/sabToSickBeard.py", line 29, in <module>
    autoProcessTV.processEpisode(sys.argv[1], sys.argv[2], sys.argv[7])
  File "/usr/share/SickRage/autoProcessTV/autoProcessTV.py", line 128, in processEpisode
    sess = requests.Session()
AttributeError: 'module' object has no attribute 'Session'
```

**Comment by markheloking** [comment]
Please use the issue guidelines when posting an issue. This way the dev team is able to debug your problem. Don't forget to use [markdown](https://guides.github.com/features/mastering-markdown/) on any code and log you want to post in-line.

- [ ] Branch
- [ ] Commit hash
- [ ] Operating system and python version
- [x] What did you do?
- [x] What happened?
- [x] What did you expect?
- [ ] Link to a copy/paste of your logfile with clear debug info of the error on [pastebin](http://pastebin.com/) (or in-line using [markdown](https://guides.github.com/features/mastering-markdown/) for small snippets)

**Comment by abeloin** [comment]
@meokey 
The commit id seem invalid(https://github.com/SiCKRAGETV/SickRage/commit/8a740bc1065677c4c555bf465d65c83472a7784c) when was the last time you updated sickrage?

Do you have requests installed?
If so, can you type each of the following commands in the python interpreter and reply the results?
```
import requests
print dir(requests)
print requests.__version__
```

**Comment by fernandog** [comment]
closing as we didn't received a reply.

**Comment by meokey** [comment]
sorry, I didn't see the reply.

here is the update.

SR Version:	BRANCH: (develop) / COMMIT: (f0bd05894c741443f131658d76652990cb3fff9f) 
SR Config file:	/usr/share/SickRage/config.ini
SR Database file:	/usr/share/SickRage/sickbeard.db
SR Cache Dir:	/usr/share/SickRage/cache
SR Arguments:	['--daemon', '--nolaunch', '--pidfile=/var/run/sickbeard/sickrage.pid', '--datadir=/usr/share/SickRage']
SR Web Root:	
Python Version:	2.6.6 (r266:84292, Jan 22 2014, 09:42:36) [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]


Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> print dir(requests)
['ConnectionError', 'HTTPError', 'NullHandler', 'PreparedRequest', 'Request', 'RequestException', 'Response', 'Session', 'Timeout', 'TooManyRedirects', 'URLRequired', '__author__', '__build__', '__builtins__', '__copyright__', '__doc__', '__file__', '__license__', '__name__', '__package__', '__path__', '__title__', '__version__', 'adapters', 'api', 'auth', 'certs', 'codes', 'compat', 'cookies', 'delete', 'exceptions', 'get', 'head', 'hooks', 'logging', 'models', 'options', 'packages', 'patch', 'post', 'put', 'request', 'session', 'sessions', 'status_codes', 'structures', 'utils']
>>> print requests.__version__
2.2.1
>>>

**Comment by meokey** [comment]
error message in SABnzbd:

Loading config from /usr/share/SickRage/autoProcessTV/autoProcessTV.cfg

Opening URL: http://localhost:8080/home/postprocess/processEpisode
Traceback (most recent call last):
  File "/usr/share/SickRage/autoProcessTV/sabToSickBeard.py", line 29, in <module>
    autoProcessTV.processEpisode(sys.argv[1], sys.argv[2], sys.argv[7])
  File "/usr/share/SickRage/autoProcessTV/autoProcessTV.py", line 128, in processEpisode
    sess = requests.Session()
AttributeError: 'module' object has no attribute 'Session'

**Comment by meokey** [comment]
I upgraded Requests to 2.5.1, restart SickRage and SABnzbd. same error

Installed /usr/lib/python2.6/site-packages/requests-2.5.1-py2.6.egg
Processing dependencies for requests==2.5.1
Finished processing dependencies for requests==2.5.1
[bill@vHost requests-2.5.1]$ python
Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> print dir(requests)
['ConnectionError', 'HTTPError', 'NullHandler', 'PreparedRequest', 'Request', 'RequestException', 'Response', 'Session', 'Timeout', 'TooManyRedirects', 'URLRequired', '__author__', '__build__', '__builtins__', '__copyright__', '__doc__', '__file__', '__license__', '__name__', '__package__', '__path__', '__title__', '__version__', 'adapters', 'api', 'auth', 'certs', 'codes', 'compat', 'cookies', 'delete', 'exceptions', 'get', 'head', 'hooks', 'logging', 'models', 'options', 'packages', 'patch', 'post', 'put', 'request', 'session', 'sessions', 'status_codes', 'structures', 'utils']
>>> print requests.__version__
2.5.1
>>> exit()

**Comment by abeloin** [comment]
@meokey Again the commit branch provided seem invalid(https://github.com/SiCKRAGETV/SickRage/commit/f0bd05894c741443f131658d76652990cb3fff9f). Are you sure your using sickrage repo?

Do you have a file named requests.py in the same folder as autoProcessTV.py?

Could you put your autoProcessTV.py on pastebin since I'm unable to see the source(invalid commit)?

**Comment by meokey** [comment]
I guess I'm using the correct branch, but how I can check? 

[.git]$ pwd
/usr/share/SickRage/.git
[.git]$ sudo more config
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        fetch = +refs/heads/*:refs/remotes/origin/*
        url = https://github.com/SiCKRAGETV/SickRage.git
[branch "master"]
        remote = origin
        merge = refs/heads/master
[branch "develop"]
        remote = origin
        merge = refs/heads/develop



[SickRage]$ cd autoProcessTV/
[autoProcessTV]$ ls -l
总用量 48
-rw-r--r--. 1 SickBeard Downloader   93 Jan 12 09:58 autoProcessTV.cfg
-rw-------. 1 SickBeard Downloader   72 Jan  9 23:59 autoProcessTV.cfg.sample
-rwxr-xr-x. 1 SickBeard Downloader 4400 Jan  9 23:59 autoProcessTV.py
-rwxrwxr--. 1 SickBeard Downloader 3236 Jan 13 13:45 autoProcessTV.pyc
-rwxr-x---. 1 SickBeard Downloader  972 Jan  9 23:59 hellaToSickBeard.py
drwxr-xr-x. 3 SickBeard Downloader 4096 Jan  9 14:07 lib
-rwxr-x---. 1 SickBeard Downloader 7285 Jan  9 23:59 mediaToSickbeard.py
-rwxr-x---. 1 SickBeard Downloader 1138 Jan  9 23:59 sabToSickBeard.py
-rwxrwxr--. 1 SickBeard Downloader  490 Jan 13 13:49 sabToSickBeard.pyc
-rwxr-x---. 1 SickBeard Downloader  374 Jan  9 23:59 setup.py
[autoProcessTV]$ ls lib
requests
[autoProcessTV]$ ls lib/requests/
adapters.py  auth.py     certs.py   cookies.py     hooks.py     models.py  sessions.py      structures.py
api.py       cacert.pem  compat.py  exceptions.py  __init__.py  packages   status_codes.py  utils.py

and here is the codes of autoProcessTV.py::

#!/usr/bin/env python

# Author: Nic Wolfe <nic@wolfeden.ca>
# URL: http://code.google.com/p/sickbeard/
#
# This file is part of SickRage.
#
# SickRage is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# SickRage is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with SickRage.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import with_statement

import os.path
import sys

sys.path.insert(1, os.path.abspath(os.path.join(os.path.dirname(__file__), 'lib')))

try:
    import requests
except ImportError:
    print ("You need to install python requests library")
    sys.exit(1)

# Try importing Python 2 modules using new names
try:
    import ConfigParser as configparser
    import urllib2
    from urllib import urlencode

# On error import Python 3 modules
except ImportError:
    import configparser
    import urllib.request as urllib2
    from urllib.parse import urlencode

def processEpisode(dir_to_process, org_NZB_name=None, status=None):
    # Default values
    host = "localhost"
    port = "8081"
    username = ""
    password = ""
    ssl = 0
    web_root = "/"

    default_url = host + ":" + port + web_root
    if ssl:
        default_url = "https://" + default_url
    else:
        default_url = "http://" + default_url

    # Get values from config_file
    config = configparser.RawConfigParser()
    config_filename = os.path.join(os.path.dirname(sys.argv[0]), "autoProcessTV.cfg")

    if not os.path.isfile(config_filename):
        print ("ERROR: " + config_filename + " doesn\'t exist")
        print ("copy /rename " + config_filename + ".sample and edit\n")
        print ("Trying default url: " + default_url + "\n")

    else:
        try:
            print ("Loading config from " + config_filename + "\n")

            with open(config_filename, "r") as fp:
                config.readfp(fp)

            # Replace default values with config_file values
            host = config.get("SickBeard", "host")
            port = config.get("SickBeard", "port")
            username = config.get("SickBeard", "username")
            password = config.get("SickBeard", "password")

            try:
                ssl = int(config.get("SickBeard", "ssl"))

            except (configparser.NoOptionError, ValueError):
                pass

            try:
                web_root = config.get("SickBeard", "web_root")
                if not web_root.startswith("/"):
                    web_root = "/" + web_root

                if not web_root.endswith("/"):
                    web_root = web_root + "/"

            except configparser.NoOptionError:
                pass

        except EnvironmentError:
            e = sys.exc_info()[1]
            print ("Could not read configuration file: " + str(e))
            # There was a config_file, don't use default values but exit
            sys.exit(1)

    params = {}

    params['quiet'] = 1

    params['dir'] = dir_to_process
    if org_NZB_name != None:
        params['nzbName'] = org_NZB_name

    if status != None:
        params['failed'] = status

    if ssl:
        protocol = "https://"
    else:
        protocol = "http://"

    url = protocol + host + ":" + port + web_root + "home/postprocess/processEpisode"
    login_url = protocol + host + ":" + port + web_root + "login"

    print ("Opening URL: " + url)

    try:
        sess = requests.Session()
        sess.post(login_url, data={'username': username, 'password': password}, stream=True, verify=False)
        result = sess.get(url, params=params, stream=True, verify=False)

        for line in result.iter_lines():
            if line:
                print (line.strip())

    except IOError:
        e = sys.exc_info()[1]
        print ("Unable to open URL: " + str(e))
        sys.exit(1)


if __name__ == "__main__":
    print ("This module is supposed to be used as import in other scripts and not run standalone.")
    print ("Use sabToSickBeard instead.")
    sys.exit(1)

**Comment by abeloin** [comment]
Please don't paste the whole file in here, use pastebin

**Comment by meokey** [comment]
sorry, I'm not familar with this tool. I guess this is it?

http://pastebin.com/XNvDuEBf

**Comment by abeloin** [comment]
Thanks, could you also edit your previous comment and remove the file content?

Can you try ```git log``` and give me the first log entry?

**Comment by meokey** [comment]
commit f0bd05894c741443f131658d76652990cb3fff9f
Merge: 8a740bc 91cb8d8
Author: root <root@vHost.(none)>
Date:   Wed Jan 21 18:09:10 2015 -0500

    Merge branch 'develop' of https://github.com/SiCKRAGETV/SickRage into develop

commit 91cb8d885ca278e5829ed53d856d578c8ee8cbe0
Merge: 653851e e123a19
Author: echel0n <echel0n@users.noreply.github.com>
Date:   Sun Jan 18 18:57:10 2015 -0800

    Merge pull request #1196 from markheloking/patch-2

    Update TODO.txt

commit 653851e2a4022f7254da40e07da9aa74fad536ed
Merge: ff7d53e 28f75bf
Author: echel0n <echel0n@users.noreply.github.com>
Date:   Sun Jan 18 18:56:43 2015 -0800

    Merge pull request #1197 from abeloin/patch-default_ep_status

**Comment by abeloin** [comment]
ok, your using your own git repo.

Can you try this in the python interpreter:
```
import requests
t = requests.Session()
t.get('http://google.com')
```

**Comment by meokey** [comment]
How can I correct it? Thanks.


Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> t = requests.Session()
>>> t.get('http://google.com')
<Response [200]>

**Comment by abeloin** [comment]
Try a git config -l 
```
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/SiCKRAGETV/SickRage.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
branch.develop.remote=origin
branch.develop.merge=refs/heads/develop
```
If the result look the same for the remote and branch, you could try a ```git reset --hard``` but it will remove the commit you made.

**Comment by meokey** [comment]
it's the following. I didn't make any commit before. so git reset --hard will fix this?

$ git config -l
user.email=**********@gmail.com
user.name=meokey
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=https://github.com/SiCKRAGETV/SickRage.git
branch.master.remote=origin
branch.master.merge=refs/heads/master
branch.develop.remote=origin
branch.develop.merge=refs/heads/develop

**Comment by meokey** [comment]
is this correct now?

$ git reset --hard
HEAD is now at f0bd058 Merge branch 'develop' of https://github.com/SiCKRAGETV/SickRage into develop

$git pull
Already up-to-date.
$ git log
commit f0bd05894c741443f131658d76652990cb3fff9f
Merge: 8a740bc 91cb8d8
Author: root <root@vHost.(none)>
Date:   Wed Jan 21 18:09:10 2015 -0500

    Merge branch 'develop' of https://github.com/SiCKRAGETV/SickRage into develop

commit 91cb8d885ca278e5829ed53d856d578c8ee8cbe0
Merge: 653851e e123a19
Author: echel0n <echel0n@users.noreply.github.com>
Date:   Sun Jan 18 18:57:10 2015 -0800

    Merge pull request #1196 from markheloking/patch-2

    Update TODO.txt

**Comment by abeloin** [comment]
You forgot to press enter the google.com line but it is ok.
Yes it should fix the issue with the invalid commit
Can you try adding this to autoProcessTV.py right after line 29 ```import requests```:
```
print requests.__file__
```

**Comment by abeloin** [comment]
For Git: you will need to do a ```git reset --soft HEAD^``` instead

**Comment by meokey** [comment]
I'm restarting SABnzbd and trying to download something. I will report back shortly. Thank you very much @abeloin .

**Comment by meokey** [comment]
$ git reset --soft HEAD^
$ git log
commit 8a740bc1065677c4c555bf465d65c83472a7784c
Merge: 6730ea3 0bb8446
Author: root <root@vHost.(none)>
Date:   Tue Jan 13 22:51:10 2015 -0500

    Merge branch 'develop' of https://github.com/SiCKRAGETV/SickRage into develop

commit 0bb84466d06ca068e09d5f8bc2bbb828c598963a
Merge: ad3cd8f 8ae08af
Author: echel0n <echel0n@users.noreply.github.com>
Date:   Tue Jan 13 19:50:43 2015 -0800

    Merge pull request #1182 from lucianot54/patch-1

    Fix for https://github.com/SiCKRAGETV/sickrage-issues/issues/178

commit ad3cd8fb5ecba5fa3cbcb887546748446eacc4d6
Merge: f45f191 82da317
Author: echel0n <echel0n@users.noreply.github.com>
Date:   Tue Jan 13 19:50:33 2015 -0800

    Merge pull request #1180 from anthonyryan1/develop

$ git pull
Removing gui/slick/css/lib/jquery.qtip-2.0.1.min.css
Removing gui/slick/images/providers/tvtorrents.png
Removing gui/slick/js/lib/jquery.qtip-2.0.1.min.js
Removing gui/slick/js/lib/jquery.qtip-2012-04-26.min.js
Removing sickbeard/providers/tvtorrents.py
error: insufficient permission for adding an object to repository database .git/objects

Merge made by recursive.
error: Trying to write ref refs/heads/develop with nonexistant object 243da8bb9d441374f4c23a3c53bbde6118a38fea
fatal: Cannot update the ref 'HEAD'.

**Comment by abeloin** [comment]
For Git: make sure the permissions are set properly for .git

**Comment by meokey** [comment]
sorry, my bad... some files are owned by root

now it seems good on pulling the commits?

$ git reset --soft HEAD^
$ git log
commit 6730ea3e72ff42330a05a5082527d038648f8cbb
Merge: 8c64aea fa3b1cb
Author: root <root@vHost.(none)>
Date:   Tue Jan 13 22:50:06 2015 -0500

    Merge branch 'develop' of https://github.com/SiCKRAGETV/SickRage into develop

commit fa3b1cb3cb3590adccd24723458c51fc07c9d15c
Merge: 3f0bd5f 32da019
Author: echel0n <echel0n@users.noreply.github.com>
Date:   Tue Jan 13 19:50:03 2015 -0800

    Merge pull request #1178 from fernandog/patch-18

    Fix issue showing 'unknown dir' when adding shows

$ git pull
Removing gui/slick/css/lib/jquery.qtip-2.0.1.min.css
Removing gui/slick/images/providers/tvtorrents.png
Removing gui/slick/js/lib/jquery.qtip-2.0.1.min.js
Removing gui/slick/js/lib/jquery.qtip-2012-04-26.min.js
Removing sickbeard/providers/tvtorrents.py
Merge made by recursive.
 .gitignore                                         |    4 +
 TODO.txt                                           |    2 +-
 gui/slick/css/lib/jquery.qtip-2.0.1.min.css        |    1 -
 gui/slick/css/lib/jquery.qtip-2.2.1.min.css        |    3 +
 gui/slick/images/providers/tvtorrents.png          |  Bin 703 -> 0 bytes
 gui/slick/interfaces/default/config_general.tmpl   |   12 ++
 gui/slick/interfaces/default/config_providers.tmpl |   33 ----
 gui/slick/interfaces/default/displayShow.tmpl      |   19 ++
 gui/slick/interfaces/default/editShow.tmpl         |   12 +-
 gui/slick/interfaces/default/inc_top.tmpl          |    4 +-
 gui/slick/js/ajaxEpSearch.js                       |    3 -
 gui/slick/js/configSubtitles.js                    |    6 +-
 gui/slick/js/lib/jquery.qtip-2.0.1.min.js          |    2 -
 gui/slick/js/lib/jquery.qtip-2.2.1.min.js          |    5 +
 gui/slick/js/lib/jquery.qtip-2012-04-26.min.js     |   13 --
 gui/slick/js/newShow.js                            |    2 +-
 gui/slick/js/recommendedShows.js                   |    2 +-
 sickbeard/__init__.py                              |    9 +-
 sickbeard/config.py                                |    6 +-
 sickbeard/helpers.py                               |   12 ++-
 sickbeard/processTV.py                             |  173 ++++++++++----------
 sickbeard/providers/__init__.py                    |    1 -
 sickbeard/providers/tvtorrents.py                  |  103 ------------
 sickbeard/search.py                                |    5 +-
 sickbeard/tv.py                                    |    2 +-
 sickbeard/webapi.py                                |    1 +
 sickbeard/webserve.py                              |    5 +-
 tests/config_tests.py                              |   20 +++
 28 files changed, 189 insertions(+), 271 deletions(-)
 delete mode 100644 gui/slick/css/lib/jquery.qtip-2.0.1.min.css
 create mode 100644 gui/slick/css/lib/jquery.qtip-2.2.1.min.css
 delete mode 100644 gui/slick/images/providers/tvtorrents.png
 delete mode 100644 gui/slick/js/lib/jquery.qtip-2.0.1.min.js
 create mode 100644 gui/slick/js/lib/jquery.qtip-2.2.1.min.js
 delete mode 100644 gui/slick/js/lib/jquery.qtip-2012-04-26.min.js
 delete mode 100644 sickbeard/providers/tvtorrents.py
 create mode 100644 tests/config_tests.py
$ git log
commit 49753895d8151f55487b060ec4363d080022e4cb
Merge: 6730ea3 91cb8d8
Author: meokey <******@gmail.com>
Date:   Tue Jan 27 11:57:21 2015 -0500

    Merge branch 'develop' of https://github.com/SiCKRAGETV/SickRage into develop

commit 91cb8d885ca278e5829ed53d856d578c8ee8cbe0
Merge: 653851e e123a19
Author: echel0n <echel0n@users.noreply.github.com>
Date:   Sun Jan 18 18:57:10 2015 -0800

    Merge pull request #1196 from markheloking/patch-2

    Update TODO.txt

**Comment by meokey** [comment]
trying SABnzbd....

**Comment by meokey** [comment]
update: SABnzbd processed successfully!
Thank you very much @abeloin for helping me correct this!

**Comment by abeloin** [comment]
I did nothing at all! The last line I had you add was to give us the imported requests library location.
But I'm glad it is working now

**Comment by styx67** [comment]
I have the same problem than @meokey in January. It started with commit c16b2c1c769a2c7c8d93707ff44ac00894501c6f on April 30.

Branch: master
Commit hash: 207bd7ac693e4beee0b72d4d3a05e0c7aca95300
Python version : 2.7.10

below is the log with debug informations I put in autoProcessTV.py :

print requests.__file__
print dir(requests)
print requests.__name__
print requests.__doc__

http://pastebin.com/qFVpck2x

Thank you in advance for the help.
