### ISSUE TITLE
FreeNAS: Symlink Post-Processing Fails Across Datasets

### ISSUE THREAD

**Issue by gctrullinger** [SiCKRAGETV/sickrage-issues#443]
**Branch:** master
**Commit hash:** 401cb666016e45b42fe675bafdf7908ad6c2b9bb
**Operating system and python version:** FreeNAS-9.3-STABLE with Python 2.7.6

**What did you do?**
Set my Post-Processing method to Symlink.

**What happened?**
The `moveAndSymlinkFile` function in helpers.py would fail (and revert to copying) on the call to `ek.ek(os.rename, srcFile, destFile)` because my library is in a different dataset than my download folder, and `os.rename` doesn't work across datasets.  I temporarily fixed this in my install by passing `shutil.move` as the first parameter in place of `os.rename`.

**Comment by abeloin** [comment]
@gctrullinger A [fix was merged in develop](https://github.com/SiCKRAGETV/SickRage/pull/1243) which resolve this issue.

Related to #485
