### ISSUE TITLE
Feature Request: Issue indicator

### ISSUE THREAD

**Issue by mgaulton** [SiCKRAGETV/sickrage-issues#444]
I'd like to request that there be some very obvious indicator from the main show list that there is an issue with a show. My biggest concern is when the folder is missing, unless you know and go into the show or stumble across it, there's no way to tell. This is mostly a concern with new shows or shows that have been moved from another location.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/295

**Comment by fernandog** [comment]
@Tagforce could PP check this? or it already does?

**Comment by TagForce** [comment]
@fernandog It does check for the existence of the show folder. But it has no way of passing that information to the homepage.  It should already log errors when a folder is missing.

**Comment by fernandog** [comment]
Ok. Will close this
