### ISSUE TITLE
Wrong country flags shown in displayShow for show with country code CA

### ISSUE THREAD

**Issue by abeloin** [SiCKRAGETV/sickrage-issues#447]
Branch: Develop
Commit hash: 91cb8d885ca278e5829ed53d856d578c8ee8cbe0
Linux, Python 2.7.5

It show the flag of Catalonia instead of Canada.

Ex: The Bridge, Doctor Who (2005)

**Comment by fernandog** [comment]
check this out:

There are many ISO for language codes, both 2 and 3-letters are supported by Subliminal. However, language codes do not match country codes and hence flags. For examble en (eng) language is often represented as US flag and not UK flag.

https://github.com/SiCKRAGETV/sickrage-issues/issues/96

**Comment by abeloin** [comment]
@fernandog 

The problem is that displayShow.tmpl -> imdb countrycode function use to same flags as Subliminal, see: 
https://github.com/SiCKRAGETV/SickRage/blob/develop/gui/slick/interfaces/default/displayShow.tmpl#L169

![Country Flags](http://i.imgur.com/HWD7xrR.jpg)

**Comment by markheloking** [comment]
Closing this to continue the discussion over at https://github.com/SiCKRAGETV/sickrage-issues/issues/96.
