### ISSUE TITLE
Trakt creates duplicate shows

### ISSUE THREAD

**Issue by mgaulton** [SiCKRAGETV/sickrage-issues#448]
I noticed something interesting and wondering if its expected behaviour. I have a bunch of shows already added in SR, on Trakt, they are also in my wishlist. For some reasons, when I recently enabled the Trakt integration, it created duplicate shows in the show list and created folders with a different case, same name. For example, I had Ncis and it created NCIS. I expected that the processes would check the show list to ensure dupes don't get created.

**Comment by fernandog** [comment]
@mgaulton please follow the guidelines:

https://github.com/SiCKRAGETV/sickrage-issues

**Comment by markheloking** [comment]
Please use the issue guidelines when posting an issue. This way the dev team is able to debug your problem. Don't forget to use [markdown](https://guides.github.com/features/mastering-markdown/) on any code and log you want to post in-line.

- [ ] Branch
- [ ] Commit hash
- [ ] Operating system and python version
- [x] What did you do?
- [x] What happened?
- [x] What did you expect?
- [ ] Link to a copy/paste of your logfile with clear debug info of the error on [pastebin](http://pastebin.com/) (or in-line using [markdown](https://guides.github.com/features/mastering-markdown/) for small snippets)

**Comment by fernandog** [comment]
@mgaulton closing as we didn't received a reply
