### ISSUE TITLE
[Feature Request] 'Archive' quality override the initial quality to download lower qualities

### ISSUE THREAD

**Issue by Grubs** [SiCKRAGETV/sickrage-issues#449]
With a number of shows I like to use the following quality settings:

Initial: HD TV, 720p WEB-DL
Replace with: SD DVD

I download the first HD release that comes out and watch the show. Then when the DVDRiP/BDRiP come out I like to archive them.

I'm guessing SickRage sees I have a 'higher' quality version and it never tries to download the SD DVD version. Is there a way to fix this?

**Comment by fernandog** [comment]
@Grubs please follow the guidelines:
https://github.com/SiCKRAGETV/sickrage-issues/

 I never saw an SD DVD. Show me in your log an SD DVD release please and SR didn't snatched

**Comment by Grubs** [comment]
Maybe it's more of a future request. i.e. a box you can tick to say 'Download archive quality file even if it exists at higher quality'

So as I mentioned in my initial post I have my quality settings set as follows:

Initial: HD TV, 720p WEB-DL - Replace with: SD DVD

I'll use the first show I found as an example. I download Glee (for my wife haha) 

Initial: Glee.S04E01.720p.HDTV.X264-DIMENSION

When the season is finished and the DVD/BluRay are released I'd just like to archive the SD DVD version.

Archive: Glee.S04E01.BDRip.X264-DEMAND

This never gets downloaded as I believe SickRage sees it as lower quality. Maybe what you have set as your 'Archive' quality should always override the initial quality?

I just did another test. I removed all of Glee.S05 and left my settings as above. Have done a rescan etc and just set them all to Skipped. I did a manual search and it chose Glee.S05E01.720p.WEB-DL.DD5.1.H.264-ECI instead of my archive quality version which would be Glee.S05E01.DVDRip.X264-REWARD

Also as an additional note I also noticed this in SickBeard which I have been using for a number of years. I only just migrated my 250+ shows across to SickRage along with the quality settings etc and made a list of seasons where I needed to update the archive quality as it hadn't been auto downloaded.

Another thing to note is I only every have 1 archive quality set.

Thoughts?

**Comment by fernandog** [comment]
@Grubs we don't judge. don't worry =)

this change is against everything in SR. DEV should analyse this but IMO we shouldn't add this feature.
SD is too bad for this new TVs. why don't you archive the HDTV? size is really small

**Comment by Grubs** [comment]
Well with 250+ shows and almost every episode of each show I have to draw the line somewhere. I have over 8TB of TV already so I only archive 720p/1080p of shows I think are worth it. Glee isn't one of them :) It's generally 3-4x the size. So the saving is worth it to me. I would like to have everything in HD!!! I actually find the BDRiP/DVDRiP's not to bad on my 58" Samsung Plasma via Kodi. I get all my shows in HD haha... the Mrs isn't so fussy

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
