### ISSUE TITLE
POSTPROCESSER stops running

### ISSUE THREAD

**Issue by peon420** [SiCKRAGETV/sickrage-issues#450]
Branch: Master
Commit Hash: (401cb666016e45b42fe675bafdf7908ad6c2b9bb)
OS: Win 7 pro 64bit
Python Version: 2.7.3 (default, Apr 10 2012, 23:24:47) [MSC v.1500 64 bit (AMD64)

I'm having a problem with automatic post processing. When I first start sickrage the post processing will work fine, but at some point it stops. Usually a day or so after starting sickrage. During the time when this is happening there are no "POSTPROCESSER" entries in the log. If I restart sickrage, post processing will resume and the backlog of completed downloads will process. Generally it will also process new downloads for about a day, then it stops again. 

I'm not sure when this started but everything was running fine for months before I had a problem. I have auto updates turned on and the problem may have coincided with an update. 

I have the post processing set to run every 10 minutes. Below is a log for an hour period with no POSTPROCESSER entries. I'm not sure if it will be of any help but it at least proves that post processing isn't running. 

http://pastebin.com/eHHN2RbV

**Comment by fernandog** [comment]
@peon420 there's nothing in your LOG related to PP

**Comment by peon420** [comment]
Yes, that's part of the problem. The post processing just seems to stop entirely and there are no entries for it in the log. The only reason I posted the log was to show that there are no POSTPROCESSER entries in the log for over an hour. Normally there would be entries at least every 10 minutes. 

So the post processing process seems to stop entirely. After I restart sickrage it will run again for a day or so then stop again. 

Whenever I notice the problem I go back through my log but it never goes back far enough to see exactly when the post processing stops.

**Comment by abeloin** [comment]
@peon420 Try to look for "Exception generated in thread"(without the quotes) and increase your log size in config.ini

**Comment by peon420** [comment]
Thanks, will do. Can you tell me what are the variable names to increase log size and rotation?

**Comment by abeloin** [comment]
@peon420 
log_nr = 5
log_size = 10485760

**Comment by fernandog** [comment]
@peon420 keep in mind that if you increase too much your log for example 10MB you could have trouble auto-submiting issues to GITHUB. I don't know how the auto-submit handles the upload of the log to pastebin.

**Comment by fernandog** [comment]
@peon420 any updates? otherwise will close this issue

**Comment by peon420** [comment]
Sickrage has been up for about 4 days straight now and post processing is still running. I haven't had it stop since I posted the issue. My only theory is that something in my download folder was causing the problem and I have now removed it. I did clean up a number of torrents that I had finished seeding. 

My problem seems similar to this thread which also suggested it may have been a problem download causing it to stop. https://sickrage.tv/forums/forum/main-category/main-forum/9991-postprocessing-not-happening 

I wasn't able to increase the log file size or the number of files kept either through the GUi or by adding those variables to my config.ini. Are those options available in the current master? Because they don't show in my GUI under config > General > misc

Thanks for the help guys and I will report back if it happens again and I can catch it in the log.

**Comment by peon420** [comment]
Hi,

Just an update on this. Post processing stopped again today. This time I have managed to track down the time in the log where it stopped. No errors in the log. It tries to unrar a file and that's the last log entry for POSTPROCESSER. 

But, the show it stops on (Blackish) is not a show I download. There was one small corrupt .rar file for that show inside the folder for The 100 S02E12. Looks like a mistake by the uploader. 

2015-02-13 07:22:58 DEBUG    POSTPROCESSER :: You're trying to post process a video that's already been processed, skipping
2015-02-13 07:22:58 DEBUG    POSTPROCESSER :: Archive file already post-processed, extraction skipped: The.100.S02E11.720p.HDTV.x264-KILLERS.mkv
2015-02-13 07:22:58 DEBUG    POSTPROCESSER :: UnRar content: []
2015-02-13 07:22:58 DEBUG    POSTPROCESSER :: You're trying to post process a video that's already been processed, skipping
2015-02-13 07:22:58 DEBUG    POSTPROCESSER :: Packed Releases detected: [u'blackish.113.720p-dimension.rar', u'the.100.212.720p-dimension.rar']
2015-02-13 07:22:58 DEBUG    POSTPROCESSER :: Unpacking archive: blackish.113.720p-dimension.rar

**Comment by fernandog** [comment]
Maybe a fake release?

**Comment by abeloin** [comment]
@peon420 Are you still on the master branch? If so can you switch to develop. It contain an updated version of unrar2.

Also you should consider upgrading python to 2.7.8(not 2.7.9 there issue with SSL) as 2.7.3 is rather old.
