### ISSUE TITLE
Pushover Notifications use absolute numbering for all shows

### ISSUE THREAD

**Issue by amanimmortal** [SiCKRAGETV/sickrage-issues#453]
When I receive a pushover notification I get it in absolute numbering for all of my shows. Did a search everywhere I could think and didn't see it raised as an issue.

I have anime set to absolute numbering. However all of my regular shows are set to use Example.S02E03. 

Pushover is notifying me of them as Example - 031. This makes it hard to identify which regular TV episode I have just gotten, be it a backlog or a new ep for the day.

**Comment by abeloin** [comment]
@amanimmortal Found the issue and submitted a pull request to fix it.

**Comment by fernandog** [comment]
@amanimmortal  please update SR and report back please. Fix was merged

**Comment by abeloin** [comment]
@fernandog Tested with a fresh copy of the develop branch and now work as expected.
