### ISSUE TITLE
Info Language is defaulted to DE

### ISSUE THREAD

**Issue by hrigteri** [SiCKRAGETV/sickrage-issues#454]
I moved from SickBeard to SickRage. So I have added existing series to my show list and all of them are defaulted to DE; the first in the pick list for "Info Language"

So this is making all show info, show names, episode names, broadcast network, all metadata... all.. in German.

I have modified all by hand to EN for English; but the network broadcast name is sitll for everything Pro Sieben or RTL Crime or whatever German network broadcasts the show.
Since I am not German I hate it.
How to change this ?

**Comment by abeloin** [comment]
Please use the issue guidelines when posting an issue. This way the dev team is able to debug your problem. Don't forget to use markdown on any code and log you want to post in-line.

- [x] Branch
- [x] Commit hash
- [x] Operating system and python version
- [x] What did you do?
- [x] What happened?
- [x] What did you expect?
- [x] Link to a copy/paste of your logfile with clear debug info of the error on PASTBIN (or in-line using markdown for small snippets)

**Comment by fernandog** [comment]
@abeloin isn't this relate to the fix about jquery?

**Comment by markheloking** [comment]
@abeloin thanks for using my template. Please *do* use the tickboxes so that the users know what is still missing. I've edited your post with my "latest version" of the template I'm using.

**Comment by abeloin** [comment]
@fernandog Not sure as if jquery wasn't working it would default to en, see https://github.com/SiCKRAGETV/SickRage/blob/master/gui/slick/interfaces/default/home_newShow.tmpl#L57 and if it was working getIndexerLanguages should put in en in front, see https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/webserve.py#L2015

@markheloking Thanks for the info

**Comment by hrigteri** [comment]
I'm on Synology DS213+ 
SickRage version 20150103-1
Python 2.7.8-11

no idea where to get the log file from. I turned off SickRage and switched back to SickBeard so it does not process my series into German stuff and renames the episodes. in the UI the metadata of all my shows is shown as German, German episode names, names of German networks who broadcast the series.

the log I see in my Synology package manager shows only search queue statements and findsubtitles.

**Comment by abeloin** [comment]
@hrigteri Log are usually available inside sickrage/Logs. The most recent one should be named sickrage.log.

It would be useful to provide the branch and commit to help us help you(Gears -> Help & Info). Also could you provide a screenshot of add existing show page were it defaulted to DE?

**Comment by hrigteri** [comment]
SR Version:	BRANCH: (master) / COMMIT: (69b169078ff6e9a98ead3d6bdec705ba351cdd7f) 
![rage1](https://cloud.githubusercontent.com/assets/10645578/5889078/9ce037f0-a416-11e4-9bd3-c644669b8289.jpg)
![rage2](https://cloud.githubusercontent.com/assets/10645578/5889077/9cdfc31a-a416-11e4-883d-9250104d3f0d.jpg)

**Comment by hrigteri** [comment]
when I opened the edit show the first time it looked like that Info Language "de".
not empty/null. but value "de". I've had to manually change all shows into "en" :(

on the show info page it was also showing a german flag and all meta data in german. 
after manually changing it to "en", only the flag has changed , meta data still in german. 

how to change that, or trigger a change??

**Comment by abeloin** [comment]
From the commit number your using Cytec's fork , this is why everything is defaulted to german!!!

Download sickrage from https://github.com/SiCKRAGETV and it will resolve your issue.

**Comment by abeloin** [comment]
By the way, make sure when you add existing or new show that language en is selected:
[Imgur](http://i.imgur.com/bvT07HR.png)
