### ISSUE TITLE
Unrar not found - Use unar

### ISSUE THREAD

**Issue by DavidVentura** [SiCKRAGETV/sickrage-issues#455]
Hi, I use unar on my sistem instead of unrar, which is the default on debian-based systems.
Please add an option to use unar or fall back to unar if unrar is not present. At the moment I'm modifying unix.py to replace 'unrar' with 'unar' when I update the repo

**Comment by fernandog** [comment]
@DavidVentura why don't you create a symblink unrar to unar passing all arguments? is'nt easier?
