### ISSUE TITLE
Google calendar misses some shows

### ISSUE THREAD

**Issue by tchirou** [SiCKRAGETV/sickrage-issues#456]
Hello

BRANCH: (develop) / COMMIT: (91cb8d885ca278e5829ed53d856d578c8ee8cbe0)
Python 2.7.6 / Win 8.1

Unprotected Calendar option is checked

Some shows are missing in my google calendar comparing to the "coming episodes" list

I don't know if a debug file is relevant.

Many thanks

**Comment by fernandog** [comment]
@tchirou follow guidelines: https://github.com/SiCKRAGETV/sickrage-issues/

and some screenshots

**Comment by tchirou** [comment]
I already followed the guidelines
What more do you need ? a full debug log starting from when ? When I search calendar or webcal, it does not find anything. And there is no error.
Here are the screenshots for next saturday for example :
![coming episodes](https://cloud.githubusercontent.com/assets/6749420/5854268/38fa539c-a22c-11e4-81e9-a2090cc4a84b.jpg)
![calendar](https://cloud.githubusercontent.com/assets/6749420/5854271/3d64d560-a22c-11e4-9945-f36e4ef19500.jpg)

**Comment by fernandog** [comment]
@tchirou please confirm that those shows are not paused

**Comment by tchirou** [comment]
They are not. Moreover, paused shows don't appear in the coming episodes list.

**Comment by fernandog** [comment]
@tchirou I couldn't add my calendar. 
You only added webcal://IP:PORT/calendar to the calendar app?

**Comment by tchirou** [comment]
Yes I did 
I don't know if you meant you added it and it did not work of if you couldn't find how to do it, which is a little tricky the first time. If it is the second case, here is how to dot it. Don't take it wrong if you meant the first case.
In google calendar, on the left, you have "Other agendas" with a little arrow on the righ. You click on itand then you have "add  a URL"

**Comment by fernandog** [comment]
@tchirou I did that. google says it's not a valid URL. strange.

**Comment by tchirou** [comment]
Yeah so I think it's broken
For the record, the missing shows are shows I added in the past few months, whereas the others have been added way earlier. Maybe it's a clue.
The furthest I can see a show on the calendar is the beginning of april.

**Comment by fernandog** [comment]
@tchirou google say he couldn't process the feed

**Comment by tchirou** [comment]
Couldn't it be related to the new login webui ?

**Comment by Rafkat** [comment]
Confirming, I've got same issue - shows added within last months won't appear in Google Calendar.

**Comment by abeloin** [comment]
Try calling the calendar directly in a browser: http://sickrage.local:8081/calendar

**Comment by tchirou** [comment]
Yep it gives calendar code including the missing shows



Le 23 janv. 2015 à 22:59, Alexandre Beloin <notifications@github.com> a
écrit :

Try calling the calendar directly in a browser:
http://sickrage.local:8081/calendar

—
Reply to this email directly or view it on GitHub
<https://github.com/SiCKRAGETV/sickrage-issues/issues/456#issuecomment-71273741>
.

**Comment by Rafkat** [comment]
Yep, it shows code for me as well.

**Comment by abeloin** [comment]
@tchirou Try to force refresh your google calendar. Maybe it is not accessible by google?

**Comment by abeloin** [comment]
@Rafkat If you see the missing show, try to force refresh your google calendar. Maybe it is not accessible by google?

**Comment by tchirou** [comment]
How do you do that? I don't see this option



Le 23 janv. 2015 à 23:22, Alexandre Beloin <notifications@github.com> a
écrit :

@tchirou <https://github.com/tchirou> Try to force refresh your google
calendar. Maybe it is not accessible by google?

—
Reply to this email directly or view it on GitHub
<https://github.com/SiCKRAGETV/sickrage-issues/issues/456#issuecomment-71276689>
.

**Comment by Rafkat** [comment]
I've done refreshing several times within last month, however this didn't help. :(
I've removed this calendar and re-added it but with same list of the shows :-/

**Comment by abeloin** [comment]
@tchirou Try this: https://www.binarysludge.com/2012/02/01/how-to-force-refresh-google-calendar/ it may work.

**Comment by abeloin** [comment]
@Rafkat Your sickrage instance is accessible from the internet?

**Comment by tchirou** [comment]
I tried adding new calendars with ?nocache and &nocache but it gave me
errors



Le 23 janv. 2015 à 23:35, Alexandre Beloin <notifications@github.com> a
écrit :

@tchirou <https://github.com/tchirou> Try this:
https://www.binarysludge.com/2012/02/01/how-to-force-refresh-google-calendar/
it may work.

—
Reply to this email directly or view it on GitHub
<https://github.com/SiCKRAGETV/sickrage-issues/issues/456#issuecomment-71278335>
.

**Comment by Rafkat** [comment]
@Rafkat Your sickrage instance is accessible from the internet?

Yep, I can see it without problem

**Comment by abeloin** [comment]
@tchirou ok

**Comment by abeloin** [comment]
@tchirou @Rafkat There's not much I can do here, it's a google calendar issue :(

Ongoing discussions on google about sync issue:
https://productforums.google.com/forum/#!topic/calendar/ixQnzHmWDSk%5B326-350-false%5D

**Comment by Rafkat** [comment]
@tchirou anyway thank you for your assistance

**Comment by Rafkat** [comment]
@abeloin sorry was 4u

**Comment by tchirou** [comment]
I don't think a Google calendar sync problem as stated in the thread you
gave  is related to ours as it is quite old and started long before we got
a problem

Besides :
- When I try to reach the calendar with the browser from outside, I get the
login page
- When I try to add the calendar from outside to outlook, I got an error

I may be wrong, but I think the new login process tampers with the way
sickrage used to unprotect the calendar to let it be reachable from third
party calendar apps or web apps
So no more updates for old shows added prior the new login process setup or
even new shows added after the new login process setup
Just my 2 cents



Le 24 janv. 2015 à 00:43, Rafkat <notifications@github.com> a écrit :

@abeloin <https://github.com/abeloin> sorry was 4u

—
Reply to this email directly or view it on GitHub
<https://github.com/SiCKRAGETV/sickrage-issues/issues/456#issuecomment-71286061>
.

**Comment by tchirou** [comment]
And thank your for your help of course mon pote :)

**Comment by abeloin** [comment]
@tchirou Ok I assumed you were able to connect without error to it. My bad!

**Comment by abeloin** [comment]
@tchirou This pull request will fix your issue when it will be merge.

**Comment by abeloin** [comment]
@Rafkat Do you use SIckrage authentication? If so try your external calendar url again without login first. If you see a login request page this pull request will fix your issue when it will be merge.

**Comment by tchirou** [comment]
Many thanks !!!

**Comment by Rafkat** [comment]
@abeloin Yes, I see a login request, as you mentioned. Thanks a lot for the fix!!!

**Comment by timrettop** [comment]
@abeloin Thanks for this, works perfectly!

**Comment by tchirou** [comment]
Can I manually modify the files and have no problem with the next update ?

**Comment by fernandog** [comment]
@tchirou you can modifybut when an update is available you'll have to SSH and:
stop SR
git checkout develop
git reset --hard HEAD
start SR

**Comment by tchirou** [comment]
Ok so do I need to disable automatic updates to prevent problems ? 
To sum it up 
I disable automatic updates
I stop SR
I modify the files
I start SR
whenever SR says there is a new version, I stop SR and do what you advise
Is that alright ?
It will keep my config.ini and my sickbeard.db, right ?

**Comment by fernandog** [comment]
yes
backup them from time to time (the the backup feature of SR)

**Comment by tchirou** [comment]
Ok thanks
I use goodsync and Dropbox to backup the whole folder regularly 
Do you have any clue about when the next update will be published ?

**Comment by fernandog** [comment]
no. dev is way for a while

**Comment by tchirou** [comment]
yeah I heard the good news
So I imported the url on another gmail adress and all the shows are displayed
So I confirm that the fixs works
Many thanks @abeloin 
waiting for the google refresh now
Do I close ?

**Comment by fernandog** [comment]
@tchirou  please update SR and report back please. Fix was merged

**Comment by tchirou** [comment]
Well I updated but I need to add a new show and wait for it to appear to see if this works
I will get back to you asap

**Comment by tchirou** [comment]
It works. The new show just appeared
Issue solved
Many thanks

**Comment by Rafkat** [comment]
I can confirm that it works 4me as well! Thanks a lot, guys!!!

**Comment by timrettop** [comment]
@fernandog I also confirm this works great, thanks!!

**Comment by tchirou** [comment]
Hello

Python 2.7.6 / Win 8.1
Unprotected Calendar option is checked
Branch devlop and master as explained below

There are new problems with coming episodes, webcal and google calendar.

I had switched to master and several problems appeared 
- Some shows were missing in the google calendar as Marvel's agents of shield wehere as they are in the coming episodes list and in the http://sickrage:port/calendar list
- Some shows (most of them) were duplicated many times in the ios calendar : 3 or 4 or 5 or more times in the same day

So I switched to develop yesterday
- Some shows which were missing now are now appearing (Marvel's agents) in google calendar but others are now missing ( Empire, the slap). Empire and the slap are in the coming episodes list but only the slap is in the http://sickrage:port/calendar. Empire is not.

So I am lost as nothing works except the coming episodes list.

Thanks

**Comment by tchirou** [comment]
Addendum 

Weirdly enough, Empire (2015) has a continuing but not active status in the show list and a "New series" status in the show page. It has been added with the tvrage indexer.

**Comment by abeloin** [comment]
The difference between master and develop is negligible as develop was merged last Sunday.

> Some shows were missing in the google calendar as Marvel's agents of shield wehere as they are in the coming episodes list and in the http://sickrage:port/calendar list

That's is a Google refresh issue to which Sickrage can't do anything.

Maybe related to the duplicate in ios: http://apple.stackexchange.com/questions/71258/duplicate-google-calendar-entries-in-ipad-calendar-app

**Comment by tchirou** [comment]
Yet I have switched twice since monday : from master to dev to master to dev. Each dev got Marvel's and each master didn't. When I say it is missing, I am looking at google calendar on the web, not through ios calendar app.

**Comment by abeloin** [comment]
Is it in the output from http://127.0.0.1:8081/calendar ?

**Comment by tchirou** [comment]
In http://127.0.0.1:8081/calendar, empire is missing but not marvel
In Google calendar (inside gmail), with dev marvel and empire and some others are missing. With master, empire and some others are missing but not marvel

**Comment by abeloin** [comment]
Ref: https://github.com/SiCKRAGETV/SickRage/compare/master...develop

**Comment by tchirou** [comment]
Sorry but I don't get what you want me to understand 😔

**Comment by abeloin** [comment]
Sorry it's a reference for me to check all commits between master and develop to see what could affect some show not showing in the calendar output.

**Comment by tchirou** [comment]
Oh ok thanks

**Comment by tchirou** [comment]
To clarify :
In coming list : all shows are in it including empire but shows for
23rd of March are not
The calendar output is the same for master and dev : marvel is in it,
the slap is in it (including 13 (yes 13, not 23) of March), the good
wife is in it (including the one airing on the 23rd of March), empire
is not
In google calendar :
- with dev : marvel is in it, the slap is in it sometimes but not
always (13 of March is not for example), the good wife is in it,
empire is not
- with master : marvel is not, I don't know about the others as I only
checked marvel at the time
For testing purposes, I added the webcal to 2 gmail and both gives the
same output in GC
So it is mess and I don't see a pattern

**Comment by fernandog** [comment]
@tchirou do you use TRAKT? Have you thought about getting the calendar from there?

**Comment by tchirou** [comment]
No I don't use it but I didn't give it a thought
Is it possible to import the list from sr ? Because I have 76 active shows



Le 12 mars 2015 à 19:38, Fernando <notifications@github.com> a écrit :

@tchirou <https://github.com/tchirou> do you use TRAKT? Have you thought
about getting the calendar from there?

—
Reply to this email directly or view it on GitHub
<https://github.com/SiCKRAGETV/sickrage-issues/issues/456#issuecomment-78561343>
.

**Comment by tchirou** [comment]
I have kodi on a HTPC with SR on it but I don't use the library
I use a western digital live player with usb HDDs
SR is on the HTPC and post process the files on the HDDs through the
local network

**Comment by tchirou** [comment]
well I checked it
iCal feed are for VIP only and costs 15$ a year
webcal and GC does it for free and it is my main use to get each morning an email with the shows of the day before :(

**Comment by abeloin** [comment]
@tchirou First, I want to see if it's an issue in sickrage or google calendar:

TVDB provider, from feed directly, sickrage-dev

Empire 2015
* March 11: s01e10
* March 18: s01e11e12

Marvel's Agents of S.H.I.E.L.D.:
* March 10: s02e12
* March 17: s02e13
* March 24: s02e14
* March 31: s02e15
* April 07: s02e16

The Slap (US):
* March 12: s01e05
* March 19: s01e06
* March 26: s01e07

**Comment by abeloin** [comment]
Same data in master

TVDB provider, from feed directly, sickrage-master

Empire 2015
* March 11: s01e10
* March 18: s01e11e12

Marvel's Agents of S.H.I.E.L.D.:
* March 10: s02e12
* March 17: s02e13
* March 24: s02e14
* March 31: s02e15
* April 07: s02e16

The Slap (US):
* March 12: s01e05
* March 19: s01e06
* March 26: s01e07

**Comment by abeloin** [comment]
Can you send me dump of the content of your webcal?

**Comment by tchirou** [comment]
Dev : https://www.dropbox.com/s/cq1288s9hyl3opn/dev.txt?dl=0
Master : https://www.dropbox.com/s/ma9em6bo7mq4gpu/master.txt?dl=0
Compared them with a dedicated software : exact match

**Comment by abeloin** [comment]
Ok so a can stop looking for an issue inserted in develop. Will look at the log.

**Comment by tchirou** [comment]
News flash : I deactivated the sickrage calendar through google on my iphone this morning. This afternoon, Google calendar on web refreshed with all the missing shows. I don't know if this is related.
I also import the webcal directly in the ios calendar from SR through safari and it is fine. Same with oulook.
I just reactivated the SR calendar through google on my iphone to check if the shows will disappear again.
I will let you know.

**Comment by fernandog** [comment]
@tchirou 

https://twitter.com/trakt/status/576406262088220673

**Comment by tchirou** [comment]
Interesting
Thanks

**Comment by abeloin** [comment]
So it's Google related

**Comment by tchirou** [comment]
I discovered I had created a trakt profile 1 year ago. I had added manually 24 shows.
I went into SR > notification > trakt yesterday and filled the info.
But so far it just added to the trakt collection the last 3 shows that I added in SR (which has 92 shows - 79 active).
Is the trakt API working for you ?

**Comment by fernandog** [comment]
don't used that feature. SR library (only watching) <> Trakt library (all)
@gborri do you know how this sync works?

**Comment by gborri** [comment]
@tchirou if you enable sync watchlist all the show on SR will be inserted on watchlist. If you add to watchlist a show it will add on SR. For the library is different: an episode will be added on library when Post process manage a file that has been downloaded. If you want to put entire library on trakt (and you have fiscally on kodi for example) you need to add to kodi the traktv addon

**Comment by tchirou** [comment]
Ok 
Do i need to activate the library on Kodi for tv and movies right ? It won't scrobble the folders with no scrapper ?
When the first sync is done, Can I deactivate the add on and only rely on SR to update trakt ? I don't use kodi to watch but a wd tv live player.
Thanks for your feedback

**Comment by gborri** [comment]
I'm not sure about ,the scrobbling but for sure you can activate it and
then deactivate and let SR update it on Download. The value to use the
plugin is that it mark also episode as watched.

Giovanni
Il 14/mar/2015 11:31 "tchirou" <notifications@github.com> ha scritto:

**Comment by tchirou** [comment]
Just to let everyone know : my google calendar seems to be alright now. Don't know if it google who fixed things of it is alexandre and fernandogs fixes to the timezone and updater things. Thanks anyway.

**Comment by fernandog** [comment]
@tchirou probably google
