### ISSUE TITLE
displayShow - Language  does not exist

### ISSUE THREAD

**Issue by Captsha** [SiCKRAGETV/sickrage-issues#457]
Hello,

I try to display some TVShow, and I have an error with this traceback: 

```python
2015-01-22 11:14:47 Thread-50 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/opt/sickbeard/sickbeard/webserve.py", line 1165, in displayShow
    return t.respond()
  File "/home/sickbeard/.sickbeard/cache/cheetah/_opt_sickbeard_gui_slick_interfaces_default_displayShow_tmpl.py", line 1154, in respond
  File "/opt/sickbeard/lib/subliminal/language.py", line 1034, in __init__
    items.append(Language(i, languages=languages, strict=strict))
  File "/opt/sickbeard/lib/subliminal/language.py", line 884, in __init__
    raise ValueError('Language %s does not exist' % language)
ValueError: Language  does not exist
```

I have this error only for some specific TVShow. I tried to remove one and to add the TVShow again but same error.
All of my TVShow are configured with TheTVDB database.
I suspect a problem on the sickrage database or directly with the library subliminal.
On my subtitle configuration, I have added 2 languages (in config.ini : subtitles_languages = "fr,en").

Because I see 2 spaces on "ValueError: Language  does not exist", I suspect that he try to found the language None or something like that. But I am unable to know if it's a problem with subliminal or sickrage.

Tell me if you need more details for debug.

Thanks in advance,

**Comment by fernandog** [comment]
@Captsha try setting only FR or only EN. See if you can reproduce the error with only one language

**Comment by Captsha** [comment]
I just tried and I have the same problem for each. If I disable subtitle module, I can display my TVShow.

**Comment by Captsha** [comment]
Also, another strange point, one file from the traceback didn't exist. Because it's seem the cache, I don't think it's relevant, but I prefer to specify it:

```
# ls /home/sickbeard/.sickbeard/cache/cheetah/_opt_sickbeard_gui_slick_interfaces_default_displayShow_tmpl.py
ls: cannot access /home/sickbeard/.sickbeard/cache/cheetah/_opt_sickbeard_gui_slick_interfaces_default_displayShow_tmpl.py: No such file or directory
# ls /home/sickbeard/.sickbeard/cache/cheetah
_opt_sickbeard_gui_slick_interfaces_default_comingEpisodes_tmpl.py  _opt_sickbeard_gui_slick_interfaces_default_config_general_tmpl.py        _opt_sickbeard_gui_slick_interfaces_default_config_providers_tmpl.py
_opt_sickbeard_gui_slick_interfaces_default_config_anime_tmpl.py    _opt_sickbeard_gui_slick_interfaces_default_config_notifications_tmpl.py  _opt_sickbeard_gui_slick_interfaces_default_manage_subtitleMissed_tmpl.py
```

**Comment by fernandog** [comment]
@Captsha what provider are you using? Try opensubtitles (just to debug)

@abeloin can you check this out please?

**Comment by markheloking** [comment]
Please use the issue guidelines when posting an issue. This way the dev team is able to debug your problem. Don't forget to use [markdown](https://guides.github.com/features/mastering-markdown/) on any code and log you want to post in-line.

- [ ] Branch
- [ ] Commit hash
- [ ] Operating system and python version
- [x] What did you do?
- [x] What happened?
- [x] What did you expect?
- [ ] Link to a copy/paste of your logfile with clear debug info of the error on [pastebin](http://pastebin.com/) (or in-line using [markdown](https://guides.github.com/features/mastering-markdown/) for small snippets)

**Comment by Captsha** [comment]
- [x] Branch: master
- [x] Commit hash : 401cb666016e45b42fe675bafdf7908ad6c2b9bb
- [x] OS: Debian 7.8; Python 2.7.3
- [x] logfile : http://pastebin.com/UYFrwWvu (I have enable debug but nothing relevant during the problem reproduction)

I hope everything is correct now.
Rgds

**Comment by abeloin** [comment]
@Captsha Can you run this query in sqlite3 on sickbeard.db and post the result?
```
SELECT subtitles FROM tv_episodes WHERE showid=258171 AND subtitles IS NOT NULL AND subtitles IS NOT '';
```

**Comment by Captsha** [comment]
``` sql
sqlite> SELECT subtitles FROM tv_episodes WHERE showid=258171 AND subtitles IS NOT NULL AND subtitles IS NOT '';
fr,en
...
fr,en
,fr,en
fr,en
...
en
```

Seem because of this result ',fr,en'. I suppose they have an explode somewhere with the sep ',' and the elem is null.

Just for this specific episode I did an update

``` sql
sqlite> UPDATE tv_episodes SET subtitles="fr,en" WHERE showid=258171 AND subtitles=",fr,en";
```

And it's working for this show.

I think this behavior appear because I change the episode naming synthax.
For finish, I run this, for fix my problem to all TVShow.

``` sql
sqlite> UPDATE tv_episodes SET subtitles="" WHERE subtitles LIKE ",%";
```

But I suppose a simple "Mass Update" -> "Rescan" or "Update" will solve my problem too.

Thanks for your help.

**Comment by abeloin** [comment]
Yes a mass update -> update would have solve your issue.

**Comment by fernandog** [comment]
@Captsha issue resolved?

**Comment by Captsha** [comment]
@fernandog : If it's possible, I suggest to add an clause for ignore empty language on displayShow step. So the error will be skipped. Or if it's on subliminal library, this is another story.
But as you want, I know how to fix that.
Thanks for everyone anyway

**Comment by fernandog** [comment]
@Captsha would be a fix to displayShow.tmpl? If yes, let's try.
But we need to reproduce the steps to make sure it's a SR issue and not subliminal.

**Comment by Captsha** [comment]
@fernandog : I succeed to solve it by this way:

```
--- a/gui/slick/interfaces/default/displayShow.tmpl
+++ b/gui/slick/interfaces/default/displayShow.tmpl
@@ -474,7 +474,7 @@
                #if $sickbeard.USE_SUBTITLES and $show.subtitles:
                        <td class="col-subtitles" align="center">
                #if $epResult["subtitles"]:
-               #for $sub_lang in subliminal.language.language_list([x.strip() for x in $epResult["subtitles"].split(',')]):
+               #for $sub_lang in subliminal.language.language_list([x.strip() for x in $epResult["subtitles"].split(',') if x != ""]):
         #if sub_lang.alpha2 != ""
                <img src="$sbRoot/images/flags/${sub_lang.alpha2}.png" width="16" height="11" alt="${sub_lang}" />
                #end if
```

Also, the root cause is why I have a comma on the database, but this something more complicate for me to know where is the problem :-)
I'm not an expert, so I hope my diff is correct.

Thanls

**Comment by fernandog** [comment]
@Captsha Can you do a PR?
How to reproduce the error?

**Comment by Captsha** [comment]
@fernandog : It's my first PR, so I hope that I did it correctly.
For reproduce the problem, I did an update on the database, like before but this time, for add a comma.

**Comment by abeloin** [comment]
@fernandog We should at least put an error log entry, advising the user to do a "Force Full Refresh" to fix the issue. It's not a good idea to silence it.

**Comment by abeloin** [comment]
@Captsha Your pull request should be against the develop branch not master.

**Comment by fernandog** [comment]
@abeloin so we need to do another check for null and log a message (warning). Not in the template file.

**Comment by abeloin** [comment]
@fernandog Why shouldn't we do the log warning in the template?

**Comment by fernandog** [comment]
Is it possible? Just import logger?

**Comment by abeloin** [comment]
Yes, something like this should work:
```
#from sickbeard import logger
...
#if $epResult["subtitles"].startswith(','):
    $logger.log('Invalid language subtitles found, please do a "Force Full Refresh" on show {name}(id={id})'.format(id=$show.indexerid, name=$show.name), logger.ERROR)
#end if

```

**Comment by fernandog** [comment]
What if it is like this: fr,,en?

**Comment by fernandog** [comment]
Isnt possible to add a ELSE?

for $sub_lang in subliminal.language.language_list([x.strip() for x in $epResult["subtitles"].split(',') if x != ""]):

**Comment by abeloin** [comment]
Then use:
```#if re.match('(^,+|,,+|,$)', $epResult["subtitles"]):```

**Comment by abeloin** [comment]
Add an else where?

**Comment by fernandog** [comment]
@abeloin 

for $sub_lang in subliminal.language.language_list([x.strip() for x in $epResult["subtitles"].split(',') if x != "" else logger.log('Invalid language subtitles found, please do a "Force Full Refresh" on show {name}(id={id})'.format(id=$show.indexerid, name=$show.name), logger.WARNING)]):

not ERROR otherwise user can submit to issue tracker

**Comment by abeloin** [comment]
ok

**Comment by fernandog** [comment]
will it work? of I can't add that ELSE?

**Comment by abeloin** [comment]
Sorry, still not fully awake. Nope it won't work and here's the results:
```
for sub_lang in subliminal.language.language_list([x.strip() for x in VFN(VFFSL(SL,"epResult",True)["subtitles"],"split",False)(',') if x != "" else logger.log('Invalid language subtitles found, please do a "Force Full Refresh" on show {name}(id={id})'.format(id=VFFSL(SL,"show.indexerid",True), name=VFFSL(SL,"show.name",True)), logger.WARNING)]): # generated from line 500, col 5
^
SyntaxError: invalid syntax 
```

**Comment by fernandog** [comment]
@abeloin ops. missing the # before "for"

**Comment by abeloin** [comment]
@fernandog No, it's there. This is from the webpage(Cheetah compiled version), hence the ```# generated from line 500, col 5``` at the end.

But it won't work as the list comprehensions needs to return something.

**Comment by Captsha** [comment]
Sorry for my late answer, I have made different test to know exactly where is the root cause. Because it's the first time I'm looking on the code, I lost time to debug.
So, about the first PR, it's a workaround for do not have the bug on the display page. The real problem, is why we have this string on the database.
The problem appears when the refresh and maybe another function is made. Who will update all information on the database.
When the parsing is made with subliminal for subtitles, a clause exist for check if the string is not null but it's another variable who is added on a list, so this one should be added in the clause too.
Here is what I'm talking:

``` python
diff --git a/sickbeard/subtitles.py b/sickbeard/subtitles.py
index 7079121..dce6158 100644
--- a/sickbeard/subtitles.py
+++ b/sickbeard/subtitles.py
@@ -71,7 +71,7 @@ def subtitlesLanguages(video_path):
     subtitles = video.scan()
     languages = set()
     for subtitle in subtitles:
-        if subtitle.language:
+        if subtitle.language and subtitle.language.alpha2:
             languages.add(subtitle.language.alpha2)
         else:
             languages.add(SINGLE)
```

I'm alone with this behavior certainly because I have a personal workaround for my subtitles.
For example, I have the show name : 'toto.avi', so I should have toto.en.srt. Because my TV didn't manage '$country.srt', I have a cron script who will make an copy for create 'toto.srt'. So, sickbeard should say it's an unknown subtitle: 'und'. After, I don't know why the variable alpha2 is empty.

Are you agree about my diff ? Let's me know if I create a new PR with that.

**Comment by fernandog** [comment]
we should have an option to NOT add language name to subtitles and then make a PR adding "No language" to drop down list and do the proper checks. I think this error was cause by your modification in files. Not a SR error. Will tag as "feature request"

**Comment by fernandog** [comment]
@Captsha did you try to enable ""append language code to subtitles filenames" at subtitle search?
Why are you running a script if you have this option?

**Comment by Captsha** [comment]
Because I use more than 1 language, so I have enable this option.
Like here:

```
TOTO.avi
TOTO.en.srt
TOTO.fr.srt
```

So, I have my own script who will copy the TOTO.fr.srt to TOTO.srt
It's just that I have a specific usage.
If I disable this function, I didn't have my second subtitle.

Maybe the feature should be:

- If they have more than 2 languages and the option "Append language codes to subtitle filenames?" is disable, so the first "Subtitle Languages" will be named "TOTO.srt" and all other will contain the country on the filename

**Comment by fernandog** [comment]
I will PR this:
```
  #for $sub_lang in subliminal.language.language_list([x.strip() for x in $epResult["subtitles"].split(',') if x != ""]):
```
Its a good code check

**Comment by dmarcelino** [comment]
Today I've also hit this same issue, using `SR Version:
BRANCH: (develop) / COMMIT: (435d62eba47eae99baaf652129d7dfdefd389e29)`.

My db output:
```
sqlite3 sickbeard.db
sqlite> SELECT subtitles FROM tv_episodes WHERE showid=279831 AND subtitles IS NOT NULL AND subtitles IS NOT '';
,en
und
,en
und
und
,en
,en
und
und
,en
und
und
und
und
```

I've fixed it using:
```
sqlite> UPDATE tv_episodes SET subtitles="en" WHERE showid=279831 AND subtitles=",en";
```

**Comment by Captsha** [comment]
I have created a PR with the modification do I did in my side and commented before.
When both PR will be validated, this problem should be resolved.

**Comment by fernandog** [comment]
@Captsha develop updated. please test and report back

**Comment by dmarcelino** [comment]
@Captsha, @fernandog, just pulled the latest from develop and the show that was causing me issues is now loading fine. Thanks to all involved!
