### ISSUE TITLE
AutoProcess/Post Processing no longer working

### ISSUE THREAD

**Issue by amgreenwalt** [SiCKRAGETV/sickrage-issues#458]
SR Version: BRANCH: (master)
COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb)
OS: Windows Server 2008 R2
Python: 2.7.8
SABnzbd Output: http://pastebin.com/z3U7G4VK

My AutoProcess also stopped working but with Windows Server 2008 I am not sure how to fix it. SABnzbd does not give me any errors but my shows are not getting processed. I turned on Debug for SickRage but when the download was finished and the script was run there were no logs in SickRage, like it never received the request. I have rebooted my server, updated Sickrage multiple times, and cannot figure out why this stopped working.

**Comment by amgreenwalt** [comment]
Also tried installing from scratch and re-adding all my shows and still not working.

**Comment by abeloin** [comment]
The pastebin html is the login page, have you set the username and pasword in your cfg file?

**Comment by amgreenwalt** [comment]
Yes, the "host", "port", "username" & "password" are all filled out and correct.  "Web_root" has always been blank & "ssl" has always been set to 0 (zero).  None of this has changed in the past year.

**Comment by abeloin** [comment]
Can you check the username and password because SR will redirect to the login page on wrong credential.

If the credential are good, try replacing your autoProcessTV.py by this [one](http://pastebin.com/DN642PvA). It should give us more info.

**Comment by amgreenwalt** [comment]
Verified my credentials were correct.  I actually got my post processing working again by installing nzbtomefia.
https://github.com/clinton-hall/nzbToMedia

**Comment by abeloin** [comment]
ok

**Comment by abeloin** [comment]
@fernandog You can close this issue
