### ISSUE TITLE
[Feature Request] Begin building .deb packages for debian/ubuntu releases

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#46]
<a href="https://github.com/jdfalk"><img src="https://avatars.githubusercontent.com/u/1310106?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jdfalk](https://github.com/jdfalk)**
_Saturday Dec 06, 2014 at 18:51 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/1033 (2 comment(s))_

----

I see you have regular releases of source code from your master branch, if possible it seems like regular binary / binary-src releases would be a good next step to further adoption and increase the user base and assistance. I would propose:
- [ ] deb for debian
- [ ] deb-src for debian
- [ ] deb for ubuntu
- [ ] deb-src for ubuntu

More likely you would want to put that up on launchpad for the ubuntu stuff, or at least submit to launchpad so you can quickly have people add it directly in ubuntu.

**Comment by miigotu** [comment]
Debian will not allow a package in the official repositories if we include any libs, and I think no one should host a package repository hosting it either if the libs are included. We can move towards not having the libs in and splitting them into a separate package for non debian users, but setup.py needs to do what it is supposed to do. There are specific rules and guidelines for packaging for linux operating systems.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
