### ISSUE TITLE
[Feature Request]  Add Preferred words for search. (in addition to Required and Ignore words)

### ISSUE THREAD

**Issue by kooimens** [SiCKRAGETV/sickrage-issues#461]
Would be great to have an option like this. Just like couchpotato and headphones do.

**Comment by fernandog** [comment]
@kooimens can you elaborate?

**Comment by kooimens** [comment]
As search settings I can specify, `Require words` or `Ignored words`. An option to specify `Preferred words` make sense in cases where I want to add for example a language+subs to prefer downloading releases with those words over releases without them. I use this option with couchpotato and that's working great. It seems to work with scores. The NZB with the highest total score will be selected for download, but I'm not sure sickrage is working the same way.

**Comment by fernandog** [comment]
thanks

**Comment by fernandog** [comment]
@Toilal feel like doing this?

**Comment by Toilal** [comment]
Why not ! next week I could spend some time on this.

**Comment by Toilal** [comment]
In couchpotato, score is attached to word, but also to download provider. So it's a preferred word feature, but also a preferred download provider.

**Comment by Toilal** [comment]
Also, in CouchPotato, words can be defined as set, and I think it's a good idea. Example for required words:

> Release should contain at least one set of words. Sets are separated by "," and each word within a set must be separated with "&".

**Comment by Toilal** [comment]
What should prime between preferred provider and preferred word ?

**Comment by fernandog** [comment]
preferred word.
preferred provider already exists.

**Comment by Ockingshay** [comment]
looking forward to this, thanks

**Comment by andreofgyn** [comment]
+1

**Comment by liquefry** [comment]
I would love this one as well

**Comment by DJElementDC** [comment]
+1 - this would be awesome in being able to search for keywords in releases that you trust.

**Comment by kurosh** [comment]
Ditto, would love this feature.  Any update on expected ETA?

**Comment by mbxplex** [comment]
Sorry for reposting feature requests guys #1867 .... I have to ask though, would this feature be identical to CouchPotato or is there an ability to implement it into an "archived search" like I mentioned in #1867 . The reason I ask is, I would like SR to eventually the "preferred word" once it becomes available, even after the first download of a file has taken place (without the preferred word found).

**Comment by andyj682** [comment]
Just wanted to +1 this one--would be super helpful especially when snatching old shows, since you could effectively prefer scene groups over other releases that show up over time. @fernandog any idea whether it's still in the works?

**Comment by Morphy99** [comment]
+1 for this, wasting a lot of time with old shows having articles missing when there are preferred downloads which I could tell to sr to snatch first

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
