### ISSUE TITLE
[APP SUBMITTED]: 422 {u'documentation_url': u'https://developer.github.com/v3/gists/#create-a-gist', u'message': u'Validation Failed', u'errors': [{u'field': u'files', u'code': u'missing_field', u'resource': u'Gist'}]}

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#462]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) 
[GCC 4.6.3]**
Operating System: **Linux-3.12.31-armv6l-with-debian-7.6**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@91cb8d885ca278e5829ed53d856d578c8ee8cbe0
Link to Log: https://gist.github.com/46378501be489335e75b
### ERROR
```
Thread-19 :: 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
@fernandog Should be fixed with SiCKRAGETV/SickRage#1233

**Comment by fernandog** [comment]
@abeloin great!
