### ISSUE TITLE
Feature request: Option to define maximum bitrate for downloads

### ISSUE THREAD

**Issue by lbjb** [SiCKRAGETV/sickrage-issues#463]
With some TVs and device hardware unable to support decoding higher bitrate videos, it would be useful to be able to skip downloads if the bitrate is over a certain threshold. Assuming the size of the completed download is available during the search stage, and the length of the episode should be available from the metadata, the bitrate could be fairly crudely worked out based on these, which would probably be sufficient for this control.

**Comment by fernandog** [comment]
@lbjb isn't possible to get all this info while searching
