### ISSUE TITLE
If multiple quality levels are defined for archive quality, existing downloads will be marked as poor quality if they don't meet the maximum of these

### ISSUE THREAD

**Issue by lbjb** [SiCKRAGETV/sickrage-issues#464]
I have a show with the profile quality set as HD. Almost everything was downloaded at 720p but some episodes were difficult to get.

I edited the show settings to set a custom quality level. For the initial level, I selected all qualities, and for archive, I selected all apart from SDTV and SDDVD.

I assumed this would mean anything would be grabbed initially, then 720p or better once available, and that my pre-existing 720p downloads would be unaffected since they matched one of the qualities in the archive selection. 

What actually happened was that all existing 720p downloads were marked as being poor quality because they weren't 1080p.

Not sure if this is a bug or if I'm incorrectly using these options, but if these selections are intended as "at least x quality" then they should be radio buttons (so that only one, mimimum, quality can be selected for each) instead of a combo box allowing multiple selections (which I assumed to mean "any of the following").

**Comment by Tlabok** [comment]
AFAIK you can stop the search after the first quality in your Archive selection is hit by selecting the Archive First Match setting for a show.

Unfortunately this is not reflected in the Backlog Overview, which keeps showing the episodes as Low Quality even after Archive First Match has been fulfilled.

Also, the Archive First Match setting is not available in the Add Show dialogue, so every added show has to be edited.

**Comment by fernandog** [comment]
@lbjb please read

https://github.com/SiCKRAGETV/SickRage/wiki/Quality-Settings

**Comment by lbjb** [comment]
Ah OK sorry - just a case of RTFM for me then...

Though it'd be nice to have this when adding a show, as @Tlabok suggests, and have the status reflected in the backlog.

**Comment by lbjb** [comment]
Actually I see @Tlabok has opened #474 so I'll close this one.
