### ISSUE TITLE
[APP SUBMITTED]: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by abeloin** [SiCKRAGETV/sickrage-issues#468]
### INFO
Python Version: **2.7.5 (default, Nov  3 2014, 14:26:24) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-7)]**
Operating System: **Linux-3.17.7-200.fc20.x86_64-x86_64-with-fedora-20-Heisenbug**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@91cb8d885ca278e5829ed53d856d578c8ee8cbe0
### ERROR
```
Thread-45 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/SickRage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/opt/SickRage/sickbeard/webserve.py", line 578, in calendar
    episode['description'].splitlines()[0] + '\r\n'
TypeError: coercing to Unicode: need string or buffer, NoneType found

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@abeloin did you fix the auto-submit issue?

**Comment by abeloin** [comment]
@fernandog Still working on it

**Comment by fernandog** [comment]
@abeloin can we close this one?

**Comment by abeloin** [comment]
Yes fixed with pull request 1230
