### ISSUE TITLE
Custom Torrent Providers 

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#47]
<a href="https://github.com/agentxan"><img src="https://avatars.githubusercontent.com/u/5567553?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [agentxan](https://github.com/agentxan)**
_Sunday Dec 07, 2014 at 04:50 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/1037 (1 comment(s))_

----

When I add the url it is adding a / which makes the link return a 404 error.
Correct Link
http://www.*******.***/rss/recent?passkey=**********************************************
Link after saving
http://www.*******.***/rss/recent/?passkey=**********************************************

If i go to the config file and fix the link it works until it is overwritten on the next save.

**Comment by dirkr07** [comment]
@echel0n dont mean to be pushy but any update on thisone?

**Comment by markheloking** [comment]
@echel0n is on vacation right now. We expect him to be pretty busy when he returns as well, so issues with medium and low priority might not get fixed for a while since there are quite a few serious bugs right now.

**Comment by fernandog** [comment]
fixed on DEVELOP
