### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'close'

### ISSUE THREAD

**Issue by abeloin** [SiCKRAGETV/sickrage-issues#471]
### INFO
Python Version: **2.7.5 (default, Nov  3 2014, 14:26:24) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-7)]**
Operating System: **Linux-3.17.7-200.fc20.x86_64-x86_64-with-fedora-20-Heisenbug**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@91cb8d885ca278e5829ed53d856d578c8ee8cbe0
Link to Log: https://gist.github.com/df614014babea7dec5a4
### ERROR
```
Thread-55 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/SickRage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/opt/SickRage/sickbeard/webserve.py", line 374, in showPoster
    return self.redirect(static_image_path)
  File "/opt/SickRage/sickbeard/webserve.py", line 191, in redirect
    super(BaseHandler, self).redirect(url, permanent, status)
  File "/opt/SickRage/tornado/web.py", line 630, in redirect
    self.finish()
  File "/opt/SickRage/tornado/web.py", line 893, in finish
    self.request.finish()
  File "/opt/SickRage/tornado/httputil.py", line 392, in finish
    self.connection.finish()
  File "/opt/SickRage/tornado/http1connection.py", line 451, in finish
    self._pending_write.add_done_callback(self._finish_request)
  File "/opt/SickRage/tornado/concurrent.py", line 135, in add_done_callback
    fn(self)
  File "/opt/SickRage/tornado/http1connection.py", line 480, in _finish_request
    self.close()
  File "/opt/SickRage/tornado/http1connection.py", line 293, in close
    self.stream.close()
  File "/opt/SickRage/tornado/iostream.py", line 386, in close
    self.close_fd()
  File "/opt/SickRage/tornado/iostream.py", line 937, in close_fd
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
This is a test

**Comment by fernandog** [comment]
@abeloin what did you do to generate this error? 

This https://github.com/SiCKRAGETV/sickrage-issues/issues/258 has the same error message

**Comment by abeloin** [comment]
@fernandog Display the show list with poster, refresh the page a multiple time in a very short interval.
I use a reverse proxy to access sickrage so it can be a factor.

For this and len none type the common root is always:
```
  File "/opt/SickRage/sickbeard/webserve.py", line 191, in redirect
    super(BaseHandler, self).redirect(url, permanent, status)
```
It look like ioloop is losing the file descriptor in between the initial call and the redirect reply.

**Comment by fernandog** [comment]
@abeloin I understand nothing in the last line. It's like Chinese to me =) I'm not in that advanced level.

**Comment by fernandog** [comment]
@abeloin that fix isn't good? Why close a door that's is already closed?

**Comment by abeloin** [comment]
I've been reading Tornado's manual as I've never work with it before. 

From what I can understand the call are made asynchronously and ioloop is used to track those requests. So if the os detect the port is closed it remove the request from ioloop as SR it processing the request it could result in the error we are seeing. But it need further investigation.

I bet echelon could fix this is eyes closed. ;)

**Comment by abeloin** [comment]
I'm not familiar with that reference:
Why close a door that's is already closed?

**Comment by fernandog** [comment]
@abeloin the code is trying to close a connection that is already closed, isn't? that's why I check if is open before close it
