### ISSUE TITLE
[Feature Request] Show "snatched" episodes in "Coming Episodes" list.

### ISSUE THREAD

**Issue by xios01** [SiCKRAGETV/sickrage-issues#473]
Just curious if this would be possible... To Leave "snatched" but not yet "downloaded" episodes visible in "Coming Episodes" list? Or at least make it option?

Possibly change color of "snatched" item(s) to yellow....

Thank You!

**Comment by fernandog** [comment]
@xios01 

why don't you see the snatched episodes here:
http://localhost:8081/manage/episodeStatuses?whichStatus=2

**Comment by xios01** [comment]
@fernandog,
   Yep, i do that quite often.  However, i always check Coming Episodes first, and then have to do the 5 additional clicks to see what was snatched and never completed downloading.

  It would just be more convenient, and user friendly, to have that in one location. A simple one stop shop for pending episodes and their status.   Once the episode's status changes to "downloaded" they no longer show on the Coming Episodes list.

Thank you...

**Comment by fernandog** [comment]
@xios01 coming episodes need to be re-written as it only reads the airdate of the episode. just checked the code. Not easy. Don't get hopes on this.
