### ISSUE TITLE
Feature request: In Backlog Overview, make Wanted: and Low Quality: clickable filters and/or remove episodes when Archive First Match is met

### ISSUE THREAD

**Issue by Tlabok** [SiCKRAGETV/sickrage-issues#474]
I use Backlog Overview to see which recent episodes are missing, but the many Low Quality episodes make it hard to find the Wanted episodes.

Most of my shows have HD as initial quality and 1080p HD TV and 1080p WEB-DL as archive quality settings, with *Archive First Match* selected.

If a 1080p HD TV version is downloaded, the episode remains in the Backlog Overview even though the WEB-DL version is no longer being searched for. I think episodes should be removed from the Backlog Overview when Archive First Match is met.

An alternative (or additional feature) would be to make the existing Wanted: and Low Quality: buttons in Backlog Overview into clickable filters.

**Comment by fernandog** [comment]
@Tlabok can you try again ? This was fixed

**Comment by Tlabok** [comment]
@fernandog 
Thanks for this and all your other work.

I do believe this issue was solved, although I have changed most of my shows to either HD or 1080 HD to avoid the use of "Archive first match" altogether because of another (minor) issue which still remains (last seen a few days ago):

Episodes for shows with Archive First Match ticked disappear from the displayShow list after they are downloaded, and only appear again by performing a Force Full Update.
 
(I have no debug info, as there is no error reported.)

**Comment by fernandog** [comment]
Will close this. please open another about the displayshow (with screen shots)
