### ISSUE TITLE
Accessing calendar: 'latin-1' codec can't encode character

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#475]
**How to reproduce:**
- Open localhost:8081/calendar

NO logs available. As there were no log, couldn't auto-submit issue.

```
SR Version:	BRANCH: (develop) / COMMIT: (91cb8d885ca278e5829ed53d856d578c8ee8cbe0) 
SR Config file:	/home/pi/SickRage/config.ini
SR Database file:	/home/pi/SickRage/sickbeard.db
SR Cache Dir:	/home/pi/SickRage/cache
SR Arguments:	['-q', '--daemon', '--nolaunch', '--pidfile=/var/run/sickrage/sickrage.pid', '--datadir=/home/pi/SickRage']
SR Web Root:	
Python Version:	2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]


```

ERROR
'latin-1' codec can't encode character u'\u2019' in position 124: ordinal not in range(256)

Traceback
```
Traceback (most recent call last): 
File "/home/pi/SickRage/tornado/web.py", line 1336, in _execute result = method(*self.path_args, **self.path_kwargs) 
File "/home/pi/SickRage/sickbeard/webserve.py", line 530, in get self.calendar_auth() 
File "/home/pi/SickRage/tornado/web.py", line 2615, in wrapper return method(self, *args, **kwargs) 
File "/home/pi/SickRage/sickbeard/webserve.py", line 534, in calendar_auth self.write(self.calendar()) 
File "/home/pi/SickRage/sickbeard/webserve.py", line 592, in calendar episode['description'].splitlines()[0]) 
UnicodeEncodeError: 'latin-1' codec can't encode character u'\u2019' in position 124: ordinal not in range(256) 
```

```

pi@raspbmc:~$ locale -a
C
C.UTF-8
en_US.utf8
POSIX
pt_BR
pt_BR.iso88591
pt_BR.utf8
pi@raspbmc:~$
```

**Comment by fernandog** [comment]
@abeloin

**Comment by abeloin** [comment]
@fernandog What's the results of locale without a?

**Comment by abeloin** [comment]
There's a character(Unicode Character 'RIGHT SINGLE QUOTATION MARK' (U+2019)) in one of the description which cannot be encoded into the latin-1 charset as it is not presnt.

**Comment by fernandog** [comment]
```
lpi@raspbmc:~$ locale
LANG=pt_BR
LANGUAGE=pt_BR
LC_CTYPE="pt_BR"
LC_NUMERIC="pt_BR"
LC_TIME="pt_BR"
LC_COLLATE="pt_BR"
LC_MONETARY="pt_BR"
LC_MESSAGES="pt_BR"
LC_PAPER="pt_BR"
LC_NAME="pt_BR"
LC_ADDRESS="pt_BR"
LC_TELEPHONE="pt_BR"
LC_MEASUREMENT="pt_BR"
LC_IDENTIFICATION="pt_BR"
LC_ALL=pt_BR
```

**Comment by abeloin** [comment]
Is it possible for you to switch from pt_br to pt_BR.utf8?

**Comment by fernandog** [comment]
@abeloin If I change it, I won't be able to create files with special chars like á é í ó ú ç ã õ and etc. Am I correct?

**Comment by abeloin** [comment]
No, you will be able to use any accented character. It will simply use the utf-8 char map instead of latin-1(ISO 8859-1).

As an example, I'm using fr_CA.utf8 and I have access to all accent used in French àéèêöïç and can also use áíóúãõ ...

**Comment by fernandog** [comment]
thanks! will try.

**Comment by abeloin** [comment]
For you info: https://wiki.archlinux.org/index.php/Locale

**Comment by fernandog** [comment]
@abeloin opening calendar (http://localhost:8081/calendar is taking a lot of CPU.
CPU MEM COMMAND
83,9 13,5 /usr/bin/python SickBeard.py 

do you get that too?

**Comment by abeloin** [comment]
Yes, generating my calendar take around 70-80 sec on a Core i7 960(~200 shows).

I thinking maybe caching the results for a small period of time would be a good idea to help prevent abuse?

**Comment by fernandog** [comment]
imagine that on as raspberry pi. =)

**Comment by abeloin** [comment]
Patience is a virtue, in this case a long one ;)

**Comment by fernandog** [comment]
yes. but Google/Outlook don't wait that long. took 4 minutes to all info show up in the browser
but this is a low priority for me.
