### ISSUE TITLE
[Feature Request] Add description for shows to show/theme

### ISSUE THREAD

**Issue by cherma22** [SiCKRAGETV/sickrage-issues#476]
Often when I'm reviewing older shows in my SickRage, or new, unaired shows, I forget what the show is about. Having the description for the show as it is found on the provider would be very handy

**Comment by abeloin** [comment]
You could click on the tvdb or tvrage logo on the right side to the stars rating system, which will bring you to the indexer's tv show main page with description.

**Comment by fernandog** [comment]
it's easier to do click the indexers logo.

**Comment by andyblac** [comment]
or hover over '?' icon in the list.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
