### ISSUE TITLE
adding new show just says loading

### ISSUE THREAD

**Issue by duelistjp** [SiCKRAGETV/sickrage-issues#478]
I'm sorry if this doesn't meet guidelines I could not find them.  the sticky said to post issues here and to follow guidelines but oh well.  I'm using the current builds I have tested with both developer branch and master branch.  I add a show and it takes me back to the show list and it is on the bottom saying Loading...(FILEPATH)  i left it overnight last night and when I woke up and refreshed the page it still had the same message so i've tried troubleshooting it the past couple hours but no luck

**Comment by abeloin** [comment]
Please use the issue guidelines when posting an issue. This way the dev team is able to debug your problem. Don't forget to use [markdown](https://guides.github.com/features/mastering-markdown/) on any code and log you want to post in-line.

- [x] Branch
- [ ] Commit hash
- [ ] Operating system and python version
- [x] What did you do?
- [x] What happened?
- [x] What did you expect?
- [ ] Link to a copy/paste of your logfile with clear debug info of the error on [pastebin](http://pastebin.com/) (or in-line using [markdown](https://guides.github.com/features/mastering-markdown/) for small snippets)

**Comment by abeloin** [comment]
A log would be helpful.

**Comment by duelistjp** [comment]
the 4th time appears to be the charm.  the 4th time deleting sickrage entirely and restoring d i was allowed to add the show.  probably just as well.  could not for the life of me figure out what part of the logfile you needed

**Comment by abeloin** [comment]
@duelistjp Glad to know it is working now. As for the log, it would have been lines around the same time you added the show but it isn't necessary anymore.

**Comment by fernandog** [comment]
log file:  /SickRage/Logs/sickrage.log 
and sickrage.log1 log2 ...

Are you able to access the indexer from your browser?
Maybe SR could not connect to the indexer site and won't be able to get the information
