### ISSUE TITLE
GingaDaddy provider issues

### ISSUE THREAD

**Issue by netohugo** [SiCKRAGETV/sickrage-issues#479]
Guys, I'm having a problem with the GingaDaddy provider. I configured this way on "Search Providers -> Configure Custom Newznab Providers"

Name: GingaDaddy
Site URL: https://www.gingadaddy.com/
API Key: e35xxxxxxxx
Enable daily searches: yes
Enable backlog searches: yes

The entire log and config is in: https://www.dropbox.com/sh/t03tjso2o68y2ek/AABgDlwij0a5LmvOCcF6POhja?dl=0

Thanks

**Comment by abeloin** [comment]
Extracted from log:
```
2015-01-24 15:43:38 ERROR    SEARCHQUEUE-BACKLOG-73255 :: [Ginga] :: Error while searching Ginga, skipping: newznab_attr
Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tvcache.py", line 127, in updateCache
    ci = self._parseItem(item)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/newznab.py", line 432, in _parseItem
    for attr in item['newznab_attr'] if isinstance(item['newznab_attr'], list) else [item['newznab_attr']]:
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/feedparser/feedparser.py", line 375, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'newznab_attr'
2015-01-24 15:43:38 DEBUG    SEARCHQUEUE-BACKLOG-73255 :: [Ginga] :: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tvcache.py", line 127, in updateCache
    ci = self._parseItem(item)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/newznab.py", line 432, in _parseItem
    for attr in item['newznab_attr'] if isinstance(item['newznab_attr'], list) else [item['newznab_attr']]:
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/feedparser/feedparser.py", line 375, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'newznab_attr'
```

**Comment by abeloin** [comment]
@netohugo The feed doesn't contain any newznab attributes. Wrong url?

A newznab feed should always with something like this:
```
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:newznab="http://www.newznab.com/DTD/2010/feeds/attributes/" version="2.0">
```

**Comment by netohugo** [comment]
Thanks for reply @abeloin 

Possibly not Alexandre. See the picture below the form that put the attributes in the SR.
![config ginga](https://cloud.githubusercontent.com/assets/10686762/5889307/9066cac6-a406-11e4-9e7c-67105854249b.jpg)

Does the SR is not saving on his configurations? I should manual change something on /var/db/sickrage/config.ini?

At this point the Ginga settings in 'config.ini' are:

[Ginga]
ginga = 1
ginga_search_mode = eponly
ginga_search_fallback = 0
ginga_enable_daily = 1
ginga_enable_backlog = 1

Thanks...

**Comment by abeloin** [comment]
@netohugo Everything look good except the categories are missing on the left side.

From pillone/usntssearch#23, it look like Ginga as is own api which is not newznab compatible.

**Comment by netohugo** [comment]
Thanks for reply @abeloin !

But it's weird.. look at the post 30 June 2013 from @pillone.... It's seems that SR has the support for GingaDaddy, even for the comum users (not VIP, that is my case)...

only if that "I will release the update soon" is not sooooo soon .... lol

tomato, tomahto... let's wainting for other clue... thanks anyway

**Comment by abeloin** [comment]
@netohugo I think you misunderstood, that post it's for another software called NZB Metasearch. They added Ginga to it and is a provider for SB, CP.

**Comment by netohugo** [comment]
Sorry @abeloin....
after a few cold beers and the kids screaming through all the house it's gets hard ...
My fault, sorry

**Comment by abeloin** [comment]
@netohugo Don't worry, there's no need to be sorry for that. Hopefully those cold beers were refreshing? ;)

For CP with GD, did it found results?

**Comment by netohugo** [comment]
@abeloin this week i'm out of my home... i'm proceed these on the weekend and i'll return the feedback ...

**Comment by abeloin** [comment]
@netohugo Any good news?

**Comment by abeloin** [comment]
@fernandog I think you can close this issue.
