### ISSUE TITLE
[Feature Request] Adding more controle for Backlog search.

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#48]
<a href="https://github.com/Quiptix"><img src="https://avatars.githubusercontent.com/u/8403842?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Quiptix](https://github.com/Quiptix)**
_Sunday Dec 07, 2014 at 17:03 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/1038 (5 comment(s))_

----

I would be happy with slightly better control of backlog searches. I want to control when SR should consider a episode being back logged.
With this control you can also fulfill other functional desires like giving priority to a download channel.

Backlog and daily searches both search for episodes which are wanted from day zero. I want to control that backlog searches only searches for episodes that are longer than x days wanted. Something like minimal age wanted in days for backlog searches.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
