### ISSUE TITLE
Letter Я causes error 123

### ISSUE THREAD

**Issue by sgtwtf** [SiCKRAGETV/sickrage-issues#481]
there is an episode of the Simpsons entitled HOMEЯ.

That Я on the end causes an error "[Error 123] The filename, directory name, or volume label syntax is incorrect: "

I had to remove to episode to get SR to finish adding all the episodes then have it post process the file.
Once done the show is named properly. However  when i click to view the show from any SR page i get that white error page.
SR Version:	BRANCH: (develop) / COMMIT: (91cb8d885ca278e5829ed53d856d578c8ee8cbe0)

**Comment by fernandog** [comment]
@sgtwtf please post the result of SSH:

```
locale
```

**Comment by sgtwtf** [comment]
this is running on a Linux system

**Comment by fernandog** [comment]
ok.
please follow the guidelines then: https://github.com/SiCKRAGETV/sickrage-issues

**Comment by fernandog** [comment]
check you OS language settings. Make sure its UTF-8

**Comment by sgtwtf** [comment]
os = Win7
PY VER=2.7

CLOSE Ticket please. 

I had restarted it but never shut it down all the way. upon reboot it is fine now.

Thank you for the help.

L O V E  THIS program.
