### ISSUE TITLE
uTorrent 2.2.1 Labels and Seed Time are not Added to Torrent

### ISSUE THREAD

**Issue by Greg0rz** [SiCKRAGETV/sickrage-issues#483]
Using uTorrent 2.2.1, no labels or seed time are applied to the torrent.  The issues are described in depth in this thread:
https://sickrage.tv/forums/forum/help-support/general-support/11626-sickrage-latest-version-utorrent-2-2-1-cannot-apply-label

**Comment by fernandog** [comment]
please past here all infos and follow the guidelines: https://github.com/SiCKRAGETV/sickrage-issues

**Comment by Greg0rz** [comment]
SR Version:	BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb) 
SR Config file:	C:\SickRage-master\config.ini
SR Database file:	C:\SickRage-master\sickbeard.db
SR Cache Dir:	C:\SickRage-master\cache
SR Arguments:	[]
SR Web Root:	
Python Version:	2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]

Operating System: Windows Server 2012 R2

**Comment by fernandog** [comment]
@Greg0rz please post full logs

**Comment by Greg0rz** [comment]
2014-12-10 13:08:22 SEARCHQUEUE-MANUAL-280329 :: uTorrent: Unable to set the label for Torrent 2014-12-10 13:08:22 SEARCHQUEUE-MANUAL-280329 :: uTorrent: Unable to connect error HTTPConnectionPool(host='localhost', port=9090): Max retries exceeded with url: /gui/?action=setprops&s=seed_override&hash=7ee22741a463 ddc950b7d48b10bfaf7ee6f97942&token=HYpZoTRm6li7-oTojTXL6ggSHmPWgkcRhwVdhTMc9LjLtNieQxnWNw6MiFQ%3D& v=1 (Caused by : [Errno 10054] An existing connection was forcibly closed by the remote host) 2014-12-10 13:08:22 SEARCHQUEUE-MANUAL-280329 :: uTorrent: Unable to set the seed time for Torrent

**Comment by fernandog** [comment]
@Greg0rz FULL logs. DEV need the DEBUG part of the log.

**Comment by Greg0rz** [comment]
This is pretty much all that it gives you.  All of the relevant information is available in the thread posted above

**Comment by fernandog** [comment]
@Greg0rz 

can you try this file?
https://raw.githubusercontent.com/junalmeida/Sick-Beard/7c3d8262736b39fda1ed761c62e17106c06cde8e/sickbeard/downloaders/utorrent.py

backup your /SickRage/sickbeard/clients/utorrent.py and paste that one.

It's from another fork, owner @junalmeida and utorrent coded by @VeNoMouS. 

If they let we can use it.

**Comment by VeNoMouS** [comment]
Your more than welcome to use if you want... addtionally it requires bencode to calc the hash correctly...

**Comment by fernandog** [comment]
Our bencode is the same as yours. Except two commented lines.

**Comment by fernandog** [comment]
@Greg0rz waiting your feedback

**Comment by Greg0rz** [comment]
Sorry, had to travel for a bit.  

Replaced the file.  Having trouble actually getting files to pull down from Nyaa. It gets to downloading, and just never actually downloads the .torrent file.  No showing of attempting to hit the http download url or anything.  This is the last log:

2015-01-30 22:35:47 DEBUG    SEARCHQUEUE-MANUAL-272309 :: Traceback (most recent call last):
2015-01-30 22:35:47 INFO     SEARCHQUEUE-MANUAL-272309 :: Downloading [BakedFish].Yowamushi.Pedal:.Grande.Road.-.15.[720p][AAC].mp4 from NyaaTorrents

**Comment by fernandog** [comment]
@Greg0rz please try other provider and a normal tv-show

**Comment by Greg0rz** [comment]
Same issue.  I think the provider python file might have messed it up.

2015-01-31 15:46:42 DEBUG    SEARCHQUEUE-MANUAL-269586 :: Traceback (most recent call last):
2015-01-31 15:46:42 INFO     SEARCHQUEUE-MANUAL-269586 :: Downloading Brooklyn.Nine-Nine.S02E14.720p.WEB-DL.DD5.1.H.264-NTb from BTN
2015-01-31 15:46:42 DEBUG    SEARCHQUEUE-MANUAL-269586 :: Checking if we should keep searching after we've found Brooklyn.Nine-Nine.S02E14.720p.WEB-DL.DD5.1.H.264-NTb
2015-01-31 15:46:41 DEBUG    SEARCHQUEUE-MANUAL-269586 :: Picked Brooklyn.Nine-Nine.S02E14.720p.WEB-DL.DD5.1.H.264-NTb as the best

**Comment by fernandog** [comment]
Sorry. Could not understand what you mean.

**Comment by Greg0rz** [comment]
Sorry I misspoke.  I think changing the uTorrent.py file has messed up the process of getting torrents.  
Just put back the original uTorrent.py and now .torrent files from every provider are being properly downloaded and inserted into uTorrent (albeit without labels).

**Comment by fernandog** [comment]
So Labels and Seed Time are still not working with SR utorrent.py version?

**Comment by Greg0rz** [comment]
Using the utorrent.py provided above, torrent files never even made it to uTorrent.

Going back to the old one that comes with sickrage, torrents work again. (both from nyaa and from btn)

**Comment by fernandog** [comment]
So can we close the issue?

**Comment by Greg0rz** [comment]
What I'm saying is the new utorrent.py did not work at all.  So essentially the problem is right back where it started

**Comment by VeNoMouS** [comment]
This is due to the way sickrage init's its class for their uTorrent code .. it wont work just copying the file over the top , as my code isn't in a class its static functions.. but you can make mod's to the current class based on my source... if I find some time this afternoon I'll post a somewhat fix if I can..

**Comment by fernandog** [comment]
Thanks!

**Comment by VeNoMouS** [comment]
I need to test this when im at home.. but the problem could be here..

```
def _add_torrent_file(self, result):

        params = {'action': 'add-file'}
        files = {'torrent_file': (result.name + '.torrent', result.content)}
        return self._request(method='post', params=params, files=files)
```

The file label is being defined with result.name, where as I don't define the name I allow uTorrent to work it out itself and simply send the file, I control everything via the hash...

```
          params = {'token': auth, 'action': 'add-file'}
            files = {'torrent_file': ("", tsession.content)}
            if not _sendRequest(session,params,files,"Add-File"):
                return False
            torrent_hash = _TorrentHash(torrent.url,tsession.content)
```

I'll test the theory tonight with your default, then without result.name in it...

**Comment by VeNoMouS** [comment]
Also... I need to check if your token is staying valid, after each call... because I discovered some messy stuff with uTorrents auth token... something along the line of each api call required a new token or something... I'll test that idea again... if your reusing or dropping the token (cant remember which was the problem) uTorrent might just be rejecting the request..

**Comment by VeNoMouS** [comment]
Hrm....

This is an example from my code with labeling etc (not via sickbeard.. just some haxed code)...
![My Code Example](http://i.imgur.com/7e9Tfu3.png)

And this is an example of labeling using sickrage..
![SickRage Exampe](http://i.imgur.com/IbEuyD6.png)


As you can see both labels were set.. Can you please supply the URL you were trying to access for said failed torrent..

**Comment by VeNoMouS** [comment]
Hrrm... interesting... found a version of uTorrent 2.2.1 and ran that under wine... my temp hacked up code worked fine... how ever on the exact same url... SickRage Failed...

**Comment by VeNoMouS** [comment]
Ok worked it out... @fernandog , your adding the token last... if you move it to the second param it works in 2.2.1... 

Example
```
def _add_torrent_uri(self, result):
        params = {'action': 'add-url','token': self.auth, 's': result.url}
        return self._request(params=params)
```

Rather than params.update() in your _request.. I defined it as the second param in the dict.. uTorrent 2.2.1 seems to require it in a specific order... even tho dict's arent really "ordered"... weird.. but if you do that it fixes the issue with 2.2.1

Hope that helps.

**Comment by fernandog** [comment]
@abeloin can you help me with this if you have the time? I'm away from home for a few days. thanks

**Comment by abeloin** [comment]
@fernandog Yes

**Comment by abeloin** [comment]
@fernandog This [commit](https://github.com/abeloin/SickRage/commit/0ae4384f33d7ebb70e39d47dddd3c5aea6fc49b2) should fix the issue, it place the token as the first param.
@Greg0rz Can you try [this commit](https://github.com/abeloin/SickRage/commit/0ae4384f33d7ebb70e39d47dddd3c5aea6fc49b2)?

**Comment by VeNoMouS** [comment]
@abeloin I tested and can confirm this works.

**Comment by abeloin** [comment]
@VeNoMouS Thank You

**Comment by abeloin** [comment]
@fernandog Pull request created https://github.com/SiCKRAGETV/SickRage/pull/1282

**Comment by fernandog** [comment]
thanks!

**Comment by Greg0rz** [comment]
Can confirm this worked in a 2012 R2 VM w/ the commit & 2.2.1.

Thanks for the hard work guys!

**Comment by abeloin** [comment]
@Greg0rz Thank you for the testing

**Comment by fernandog** [comment]
@Greg0rz  develop updated. please test and report back

**Comment by abeloin** [comment]
@Greg0rz Any news?

**Comment by Greg0rz** [comment]
Suddenly this is working w/o me even intervening. Not sure if you guys updated something in the master.  I haven't touched anything and am on version:
BRANCH: (master) / COMMIT: (ac153cf2320b3b6d0a8aa9a1b1646a51347581d6) 


Will test further pending a reply.

**Comment by fernandog** [comment]
@Greg0rz yes, master got updated. you have other issues to reply too.

**Comment by Greg0rz** [comment]
Okay.  Functionality seems to be working well in master, so you can probably close this.

**Comment by abeloin** [comment]
Thank You for the teststing
