### ISSUE TITLE
POSTPROCESS fails to create symlinks

### ISSUE THREAD

**Issue by xoxojackie** [SiCKRAGETV/sickrage-issues#485]
**Branch:** Dev, also tried with Master
**Commit hash:** 91cb8d885ca278e5829ed53d856d578c8ee8cbe0
**Your operating system and python version:** Ubuntu 14.10, Python 2.7
**What you did:** Post-processed an episode with the option to symlink selected, both manually and automatically
**What happened:** symbolic link failed, file copied instead.
**What you expected:** a symlink

It would appear that SR is attempting to make a hardlink instead of a symlink, which would definitely not work because I'm working with two different file systems. I am able to create the symlink manually using the "ln -sf" command. It won't symlink any episode of any show.

**Link to a copy/paste of your logfile** http://pastebin.com/f9c38hfs

**Comment by fernandog** [comment]
please post your "Process Episode Method:" setting at http://localhost:8081/config/postProcessing/

**Comment by xoxojackie** [comment]
It's set to "Symbolic Link"
![image](https://cloud.githubusercontent.com/assets/10625767/5892952/416e0d02-a498-11e4-8e2e-6cdeb70b0df6.png)

**Comment by fernandog** [comment]
@abeloin do you undestand about this?

**Comment by abeloin** [comment]
Yes, let me look at the code.

**Comment by abeloin** [comment]
@fernandog It's failing because os.rename try to rename(move) the file across different partition.

**Comment by fernandog** [comment]
So why is that a problem? its a common thin isnt? Isnt supposed to just symlink?

**Comment by abeloin** [comment]
@fernandog You can't rename a file to a "different drive". Not really as people don't usually have multiple drive. It suppose to move the file to the destination dir then symlink it back to the source dir.

**Comment by abeloin** [comment]
@xoxojackie This pull request should resolve your issue.

**Comment by xoxojackie** [comment]
Changed the lines from your pull myself locally, and it's working great now.

Thanks for working on what I guess is a unique case. I appreciate it!
