### ISSUE TITLE
SickRage .deb package for netgear readynas 102

### ISSUE THREAD

**Issue by RHYSTICGON** [SiCKRAGETV/sickrage-issues#486]
Hello I was wondering if its possible to develop or list the steps I would need to go through to develop a .deb package for sickrage to run on a netgear ReadyNAS 102. 

The os running on the nas is ReadyOS 6.2.2 currently there is a sickbeard alpha piratebay fork available for it through the available apps section. While this works its missing a few key features primarily a preferred words listing for the episodes it searches for. 

I would try to install this through ssh however Putty does not acknowledge root as a user with the admin password saying access denied. and utilizing the regular admin user I connect but get installed signed off. Thus I have no way of getting root access to run commands on the ReadyNAS. 

Any help would be most appreciated.

**Comment by ziggyke** [comment]
You firts have to enable root in the settings on your NAS. Then afterwards you can login with the user "root" by ssh with the same password that has been set on the user "admin". Hopes this can help you further now you've root permission on your NAS.

**Comment by mmmonster** [comment]
I am all for this. 
The TPB fork of Sickbeard is pretty useless these days. Hasn't been an update for a while, and I think support as finished. It's no longer working as well as I'd like.

I have played around with SickRage on my pc and I like it. I've looked into getting it onto my ReadyNAS 102 too but didn't really know where to start and have found little information. The latest search brought me here. And I'm glad to see others are trying too.

My SSH skills are fairly basic. I can SSH in with putty. But don't really know where to go from there without instruction.

I did learn something useful though;
if you want to mount the root directory of your NAS as a drive on Windows put the following command in cmd prompt. Just replace the drive letter (I chose 'n' for nas) and your NAS IP address. Once entered it will prompt you for a password, which will be your admin password.

net use n: \\192.168.1.111\data /user:admin

I found sickbeard in .apps folder. I tried replacing SickRage straight over TPB fork trying to trick the NAS, but it ran into errors when I tried to launch it. Not even sure if that would work.

Anyway, if someone is capable of either making an installable app for the NAS. Or some fairly clear instructions on how to get it going. I'll put a bounty of $10 to transfer over PayPal to you (just provide your email). Would save me a headache and a bunch of time.

**Comment by ioax** [comment]
prerequisit: Python installed

Enter as root on your readynas
cd /home
mkdir sickrage
git clone git://github.com/echel0n/SickRage.git sickrage
cd sickrage
/usr/bin/python SickBeard.py --nolaunch &

on your browser <mynas>:8081    <mynnas> can be your NAS name or the NAS ip

issue: every time you boot or reboot your NAS you need to login as root go to /home/sickrage  and do /usr/bin/python SickBeard.py --nolaunch &

**Comment by fernandog** [comment]
@ioax is this a new issue? If so, open another one please

**Comment by TheWoollyBully** [comment]
I created a [deb](https://github.com/TheWoollyBully/sickragern6/releases/download/v0.1/sickragern6-0.1.deb) package. It will install SickRage on your ReadyNas and provide controls through the admin frontview.  Its all on github at [TheWoollyBully/sickragern6
](https://github.com/TheWoollyBully/sickragern6)
enjoy!

**Comment by fernandog** [comment]
@TheWoollyBully what was the commit hash from you build the deb?

**Comment by TheWoollyBully** [comment]
43854607ecfce849d8dc6f95995850abb54bb444

**Comment by neoatomic** [comment]
As theWoollyBully was able to create a deb package for Readynas we can close this FR.
Thanks for your contribution.

**Comment by TheWoollyBully** [comment]
Glad to help.
