### ISSUE TITLE
Add file size

### ISSUE THREAD

**Issue by kristofferbas** [SiCKRAGETV/sickrage-issues#487]
Would be great to be able to see the size of downloaded files. Sometimes lower quality files are marked as higher, and to see the file size in SickRage and be able to download a new file is easier than to check all the files manually.

**Comment by TagForce** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1248

New PR. It is now an option under General -> GUI
Also changed the min-width for the Name column when Display Filesizes is selected to make sure it wraps at the same moment on small-screen browsers (ie. Mobile devices)

**Comment by fernandog** [comment]
@TagForce nice! thanks!

**Comment by kristofferbas** [comment]
Great! Thanks!

**Comment by fernandog** [comment]
@kristofferbas  please update SR and report back please. Fix was merged

**Comment by kristofferbas** [comment]
@fernandog works great from here, thanks!
