### ISSUE TITLE
SickRage returns an invalid charset as header response with API requests

### ISSUE THREAD

**Issue by timkatgert** [SiCKRAGETV/sickrage-issues#488]
I've created an android app to easy manage all kinds of usenet services but with SickRage I'm getting charset UTF-8 errors. I've Sickbeard running with it's API and there is no problem at all.

The Content Type I'm getting returned is: Content-Type: application/json;charset=UTF-8' (Notice the ' at the end)
and the content-type from Sickbeard is: Content-Type: application/json;charset=UTF-8 (without the ' ).

![image](https://cloud.githubusercontent.com/assets/6659118/5892963/51205396-a4d3-11e4-93fa-2bb8284fd614.png)

**Comment by abeloin** [comment]
@timkatgert This pull request should resolve your issue.

**Comment by timkatgert** [comment]
Thanks alot!
