### ISSUE TITLE
Wanted Group/Unwanted Group Being Ignored by Anime Search

### ISSUE THREAD

**Issue by Greg0rz** [SiCKRAGETV/sickrage-issues#489]
PC:
Windows Server 2012 R2

SickRage Configuration:
SR Version:	BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb) 
SR Config file:	C:\SickRage-master\config.ini
SR Database file:	C:\SickRage-master\sickbeard.db
SR Cache Dir:	C:\SickRage-master\cache
SR Arguments:	[]
SR Web Root:	
Python Version:	2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]

What Happened:
Added blacklisted and whitelisted wanted groups.  The search/downloader proceeds to grab one that is within the blacklist.  Previously, I had only whitelisted HorribleSubs, but it was still downloading [BakedFish].  Added BakedFish to blacklist, but still downloading this release.

Show Configuration:
http://i.imgur.com/loEGv69.png

Debug Logs:
http://pastebin.com/bgfmCNAY

**Comment by abeloin** [comment]
Fixed in develop https://github.com/SiCKRAGETV/SickRage/commit/7796f06b944512d811a2e0929cdf5930e379b2b8
Not merge in master yet.
