### ISSUE TITLE
Webserver not working with web_root

### ISSUE THREAD

**Issue by josh4trunks** [SiCKRAGETV/sickrage-issues#490]
Branch ~ master
commit ~ 401cb666016e45b42fe675bafdf7908ad6c2b9bb
OS ~ FreeNAS, python2.7
What I did ~ web_root = /sickrage, browse to http://server:8081/
What happened ~
```
Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/tornado/web.py", line 1313, in _execute
    result = self.prepare()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/tornado/web.py", line 2002, in prepare
    raise HTTPError(self._status_code)
HTTPError: HTTP 404: Not Found
```
Instead of the usual re-direct

**Comment by fernandog** [comment]
@josh4trunks what if you open http://server:8081/sickrage?

**Comment by josh4trunks** [comment]
it works, so it just seems to be the redirect that is no longer working

**Comment by fernandog** [comment]
@abeloin do you know how to fix it?
thanks and sorry If I'm bothering you

**Comment by abeloin** [comment]
@josh4trunks if you try http://server:8081/sickrage/this_is_invalid_path it does redirect?

**Comment by fernandog** [comment]
@abeloin just tested and it redirects

for example: http://localhost:8081/sickrage/homeeeee/ to http://localhost:8081/sickrage/home/

**Comment by abeloin** [comment]
@fernandog That is what I thought, now the question is what is the expected behavior? Did Sickrage redirected to the webroot when the path is on the left side of the webroot before?

**Comment by fernandog** [comment]
@abeloin I would do a check: if webroot then redirect to /webroot/home otherwise just /home. This only happens when there's nothing just IP:port

**Comment by abeloin** [comment]
@fernandog If you try http://localhost:8081/invalidname it redirect to http://localhost:8081/sickrage/home/ ?

**Comment by fernandog** [comment]
no

**Comment by abeloin** [comment]
@fernando Looking at this more carefully, I don't think we should change the behavior. Webroot seems to be mainly used for reverse proxy on the same dns name. Also by default, on new installation, the webroot is /.
