### ISSUE TITLE
[Bug]: Setting episode status to "skipped" but still downloading episodes

### ISSUE THREAD

**Issue by paparen** [SiCKRAGETV/sickrage-issues#492]
I changed the default episode status to skipped and changed each show individually to skipped, but sickrage still downloads the episodes.
running:
BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb
on synology

**Comment by fernandog** [comment]
You should set as IGNORED or ARCHIVED.

**Comment by fernandog** [comment]
you can also PAUSE an entire show.
