### ISSUE TITLE
Request - Add option to filter "Unknow" quality on show page

### ISSUE THREAD

**Issue by pct00** [SiCKRAGETV/sickrage-issues#493]
Is it possible to add a filter for the episodes with quality Unknown to the show page ?

![image](https://cloud.githubusercontent.com/assets/10249098/5900411/c1509b20-a560-11e4-91a8-eefe96ded963.png)

**Comment by fernandog** [comment]
@pct00 don't they appear as "Low quality" ?

**Comment by fernandog** [comment]
@pct00 

stop SR
edit /SickRage/tv.py
change line 1278 from:

```
            elif curQuality < maxBestQuality:
```

to
```
            elif curQuality < maxBestQuality or epStatus == UNKNOWN:
```

start SR
let me know if works.
mind the identation!

**Comment by pct00** [comment]
@fernandog hi, thanks for the fast reply. 
the episodes show up as regular downloaded episodes...
tonight when i get home i'll make the changes and update this issue after a few days of testing

**Comment by fernandog** [comment]
@pct00 ok! keep in mind that all UNKNOWN episodes will appear as BACKLOG and SR will try to find better qualities until it finds!

**Comment by pct00** [comment]
@fernandog doesn't seem to be working, tried a re-scan ,full update, removing and adding a show again but the episodes with qlty unknow don't count to the low quality, they remain as downloaded
backlog also doesnt process them since they are considerered "ok" i guess

**Comment by fernandog** [comment]
@pct00 have you changed both lines?

**Comment by pct00** [comment]
@fernandog i need to start paying attention and read the full comments.... only had made 1 of the changes. restarting now after making both changes and will let you know. sorry....

**Comment by pct00** [comment]
@fernandog still not luck after changing both lines, tried the same procedures, re-scan, full update. remove and add again running backlog and daily searches

also tried this time deleting associated .NFO files and doing it again but still no changes

**Comment by fernandog** [comment]
@pct00 now it's working:

Try that change please

**Comment by pct00** [comment]
@fernandog working well, thanks! :)

**Comment by fernandog** [comment]
@pct00 we need testing. let me know in a few days if everything is ok.

**Comment by pct00** [comment]
@fernandog Hi, after a few days already runnig the behaviour is different from what i think you expected
the episodes are now classified as low quality, but the backlog processes doesnt try to find downloads for them, either the manual backlog, automatic backlogs etc

**Comment by fernandog** [comment]
@pct00 but it appears as low quality and you wanted?

**Comment by fernandog** [comment]
@pct00  please update SR and report back please. Fix was merged
