### ISSUE TITLE
Feature Request: Torrent provider Ztuga

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#494]
Ztuga its a Portuguese private tracker ,that at the moment is open to the public, and having it in SR would be a great addition .Why this and not other? Well this one has something called karma points which are gained sonelely by seeding torrents (every hour=1karma point AFAIK) that can be used to "purchase" goodies like free leech for everybody on the tracker, gaining more ratio ,more upload count ,etc
Its URL: http://ztuga.com 
PS it is in Portuguese, but for those who don't speak pt (and can develop the provider to add to sr) a quick botton right click on chrome and then translate should do the trick .

**Comment by fernandog** [comment]
@matigonkas now that you added  TPBT, you can add this one too, can't you?

**Comment by matigonkas** [comment]
well @fernandog  i am not any python expert but i see if i can make it happen :)

**Comment by matigonkas** [comment]
the Ztuga website got closed due to court afaik so there isnt anymore use for this FR
