### ISSUE TITLE
[Feature Request] Archive on first match missing from new show defaults

### ISSUE THREAD

**Issue by distracto** [SiCKRAGETV/sickrage-issues#495]
Would it be possible to add the option to archive on first match when adding a new show? currently i either have to select the archive to be the same as the first match and then go into the edit page of the show to set archive as first match.

i prefer to have shows set to archive as first matched so i can tell which ones i want to archive or not. setting the archive the same as first matched does not give me that visibility in mass edits. does that make any sense? hope so

thanks

**Comment by fernandog** [comment]
@distracto we can do that after changing templates to MAKO

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
