### ISSUE TITLE
Backlog Search Failing on all shows.

### ISSUE THREAD

**Issue by alexkoon** [SiCKRAGETV/sickrage-issues#497]
When trying to force a backlog individually or en mass - I get the following per show.

    2015-01-26 20:37:03 INFO     SEARCHQUEUE-BACKLOG-258602 :: Beginning backlog search for: [SHOW_NAME]
    2015-01-26 20:37:04 DEBUG    SEARCHQUEUE-BACKLOG-258602 :: Traceback (most recent call last):
      File "/share/MD0_DATA/.qpkg/Optware/usr/sickrage/sickbeard/search_queue.py", line 220, in run
    searchResult = search.searchProviders(self.show, self.segment, False)
      File "/share/MD0_DATA/.qpkg/Optware/usr/sickrage/sickbeard/search.py", line 445, in searchProviders
    sickbeard.name_cache.buildNameCache(show)
      File "/share/MD0_DATA/.qpkg/Optware/usr/sickrage/sickbeard/name_cache.py", line 91, in buildNameCache
    sickbeard.scene_exceptions.retrieve_exceptions()
      File "/share/MD0_DATA/.qpkg/Optware/usr/sickrage/sickbeard/scene_exceptions.py", line 232, in retrieve_exceptions
    cur_exception, curSeason = cur_exception_dict.items()[0]
    AttributeError: 'list' object has no attribute 'items'

**Comment by fernandog** [comment]
Please use the issue guidelines when posting an issue. This way the dev team is able to debug your problem. Don't forget to use [markdown](https://guides.github.com/features/mastering-markdown/) on any code and log you want to post in-line.

- [ ] Branch
- [ ] Commit hash
- [ ] Operating system and python version
- [x] What did you do?
- [x] What happened?
- [x] What did you expect?
- [ ] Link to a copy/paste of your logfile with clear debug info of the error on [pastebin](http://pastebin.com/) (or in-line using [markdown](https://guides.github.com/features/mastering-markdown/) for small snippets)

**Comment by alexkoon** [comment]
As requested:
- Execute backlog search, per show as well as en mass (Manage / Manage Searches / Force).
- No issues seen in gui. But no shows were captured and processed to sab.
- Expected some backlog episodes to be found and processed - none were. Errors found in log and an example pasted above - this happens to all shows.

**Comment by fernandog** [comment]
you must send the others:  branch, commit hash, LOG

localhost:8081/config you get the first 3.

**Comment by alexkoon** [comment]
BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb) 

What is LOG? Or do you mean the log file when this occurred?

**Comment by fernandog** [comment]
@alexkoon can you post the contents of the field "scene exception" for that show you renamed "SHOW NAME" in the log?

**Comment by alexkoon** [comment]
A few examples

[Blue Bloods]
[Castle (2009)]
[Parenthood (2010)]
[Instance Mom]
[Veep]

**Comment by fernandog** [comment]
I need the contents of field SCENE EXCEPTIONS of this show. Read my post again please.

**Comment by alexkoon** [comment]
Take [Parenthood (2010)] for example - I have the following exceptions

Parenthood
Parenthood 2010
Parenthood (2010)

Note: This was a migration from Sickbeard to Sickrage lately - not sure if this contributes to the issue I am seeing.

**Comment by fernandog** [comment]
@alexkoon send a print of the show page having problem

**Comment by alexkoon** [comment]
![sickrage](https://cloud.githubusercontent.com/assets/1433798/5917229/4d6075d4-a612-11e4-8a9d-69d289f6de32.png)
Ignore the blue line!

**Comment by fernandog** [comment]
@alexkoon stop SR, rename cache.db to cache.bkp and restart SR

**Comment by alexkoon** [comment]
All good. Thanks for the help.
