### ISSUE TITLE
SickRage not loading on limited internet connection

### ISSUE THREAD

**Issue by renelux** [SiCKRAGETV/sickrage-issues#500]
I am located in China and some websites can't be accessed without VPN, since a few days I noticed that SickRage also stopped working if I am not connected to VPN.

Are there certain URL's being called when we load a page? Maybe something from Google or any of the social media websites? If so is this nessecary can it be done in the background or even completely optional?

**Comment by renelux** [comment]
When disabling the Plex notification it works without issues again. I think that this commit https://github.com/SiCKRAGETV/SickRage/commit/03b17d63e0f3d2374abea66fd3002253cd8ff52d has introduced this bug.

**Comment by fernandog** [comment]
@vandalon

**Comment by fernandog** [comment]
@renelux isn't a intermittent issue? try enabling Plex notifications again please

if do not work:

Please use the issue guidelines when posting an issue. This way the dev team is able to debug your problem. Don't forget to use [markdown](https://guides.github.com/features/mastering-markdown/) on any code and log you want to post in-line.

- [ ] Branch
- [ ] Commit hash
- [ ] Operating system and python version
- [ ] What did you do?
- [ ] What happened?
- [ ] What did you expect?
- [ ] Link to a copy/paste of your logfile with clear debug info of the error on [pastebin](http://pastebin.com/) (or in-line using [markdown](https://guides.github.com/features/mastering-markdown/) for small snippets)

you provided non of them!
