### ISSUE TITLE
[Feature Request]  Add option to set delay time for a nzb provider

### ISSUE THREAD

**Issue by Tlabok** [SiCKRAGETV/sickrage-issues#501]
I regularly find incomplete nzb downloads in sabnzbd, which can be completed by clicking Retry and/or manually deleting the first few archive parts. These nzb's are always from the same nzb provider, which appears to be ahead of my usenet servers.

The problem could be solved by adding an adjustable time delay in Provider Options for sending nzb's to the download application.

Making the daily search start time adjustable could be an alternative, but I'm not sure if that will ever be implemented.

**Comment by Tlabok** [comment]
Duplicate as in the alternative I mentioned? I think they are two different options; one is a global setting while my request is per provider.

I may be wrong, but I searched and did not find this request anywhere.

**Comment by Tlabok** [comment]
@fernandog 
This is not a support / question, but a feature request.

**Comment by neoatomic** [comment]
@Tlabok I'm going to close this FR as i dont see a way to get this implemented.
