### ISSUE TITLE
Adding Custom Newznab Provider does not properly populate categories

### ISSUE THREAD

**Issue by thermodyn** [SiCKRAGETV/sickrage-issues#503]
Branch: BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb) 

When adding Custom Newznab Providers - Search Categories do not update and save.  
Left and Right box remains blank when update categories is pressed.  

This causes a malformed URL when searching for episodes (cat is blank):
https://api.dognzb.cr/api?apikey=api_key_removed&season=1&maxage=1100&cat=&q=Gotham&limit=100&attrs=rageid&offset=0&ep=13&t=tvsearch

After messing around - it eventually updates itself somehow and searching starts to work with a proper URL.
https://api.dognzb.cr/api?apikey=api_key_removed&season=1&maxage=1100&cat=5030%2C5040&limit=100&attrs=rageid&offset=0&rid=38049&ep=13&t=tvsearch

If you leave the screen - i.e. go to home and back to provider options - categories is populated and can be saved.

Cannot select categories in the left box ever though which is potentially a problem.

Forum post with more information: 
https://sickrage.tv/forums/forum/help-support/general-support/17367-possible-problem-with-custom-newsnab-providers

**Comment by fernandog** [comment]
@thermodyn can you try the develop branch please?

**Comment by thermodyn** [comment]
This will sound stupid - but how do you switch branches?  

I am on linux and installed with:
sudo git clone https://github.com/echel0n/SickRage.git /var/sickbeard

**Comment by fernandog** [comment]
first, backup your entire /SickRage folder
then open General config http://loalhost:8081/config/general/
go to 'Advanced Settings' - 'Github' - 'Branch version'

**Comment by abeloin** [comment]
@fernandog See my comment https://github.com/SiCKRAGETV/sickrage-issues/issues/361#issuecomment-71483671 on the empty categories

**Comment by fernandog** [comment]
@abeloin. maybe the javascript or code it's not running when the page is open. It only runs after. Just guessing here. In the forum 2 others said the categories was filled when they exit the page and go back again

**Comment by thermodyn** [comment]
Ok, using BRANCH: (develop) / COMMIT: (91cb8d885ca278e5829ed53d856d578c8ee8cbe0) 

Working with OzNZB this time.

Add new custom newznab provider, add info, update categories, right and left category boxes blank, save changes, both blank, update categories, blank, home screen and back - right and left are now populated properly.  

Deleted another provider that was already set up.  Switch back to OzNZB details right side blank, left side had 5030, 5040, pressing update - both sides now blank.  

Go to home screen, back to search providers, right side has 5030, 5040, left side is blank.

**Comment by fernandog** [comment]
@thermodyn @abeloin 

I think I figure it out.

Started a clean SR
Enabled NZB search
Opened "Configure Custom Newznab Providers"
Added Provider name, Site URL and API key

now its the catch:
Dont' click "Update category" before click "Add".
You must click "Add" first the click "Updade categories"
Then you can select categories and then finaly SAVE

Some users may click "Add" then "Save". This way no category were selected

I would remove this block from the script that prevent the update of categories if the show isn't Added"

Suggestions?

**Comment by thermodyn** [comment]
I just tested on master - this doesn't work.  

On the development branch this is the case though.  
>Dont' click "Update category" before click "Add".
>You must click "Add" first the click "Updade categories"
>Then you can select categories and then finaly SAVE

**Comment by fernandog** [comment]
maybe related with the jquery update?

**Comment by abeloin** [comment]
@fernandog The whole configProviders.js page needs a good overhaul.

**Comment by fernandog** [comment]
@abeloin what if we call the "Add" button when "Update Categories" is clicked?
Is it difficult?

**Comment by abeloin** [comment]
@fernandog Have a look at this commit https://github.com/abeloin/SickRage/commit/6e435a77de80adcc399bcddd7863681a02f765ee. It's not complete but the part for the "Custom Newznab Provider" is working.

**Comment by fernandog** [comment]
@abeloin are you re-writing everything?

**Comment by abeloin** [comment]
@fernandog No, just adding the missing code to make it work.

**Comment by fernandog** [comment]
Ok! Will study cause Im new to JS.

**Comment by fernandog** [comment]
@abeloin I updated the code. add settings. didn't click "add". clicked "update categories". nothing happens.

**Comment by abeloin** [comment]
@fernandog You shouldn't be able to see the categories until you press add for a new item.

**Comment by abeloin** [comment]
@fernandog Almost done

**Comment by minipulator** [comment]
New to SR, @fernandog your instructions from Jan 27th worked for me.  Appreciated.

**Comment by fernandog** [comment]
@abeloin will you commit https://github.com/abeloin/SickRage/commit/6e435a77de80adcc399bcddd7863681a02f765ee this soon when it's ready? thanks!

**Comment by abeloin** [comment]
@fernandog Yes, I will. It's taking me longer than expected to finish it.

**Comment by fernandog** [comment]
@abeloin any updates on this? are you overhauling this?

**Comment by abeloin** [comment]
I should have a PR later on today

**Comment by fernandog** [comment]
@abeloin we should add this to master too

**Comment by fernandog** [comment]
@thermodyn fix merged in develop
