### ISSUE TITLE
post-process hangs when trying to create Kodi episode metadata.

### ISSUE THREAD

**Issue by clinton-hall** [SiCKRAGETV/sickrage-issues#505]
This occurs with develop branch.
```
SR Version:	BRANCH: (develop) / COMMIT: (91cb8d885ca278e5829ed53d856d578c8ee8cbe0) 
```
Running on Linux (Asustor NAS) with Python 2.7.3 `Python 2.7.3 (default, Dec 27 2013, 16:02:20)
[GCC 4.6.3] on linux2`

The postprocessing is called via nzbToMedia, and since the postprocess event never completes, the request is not closed and therefore NZBGet also hangs...

Debug logging shows the last entry is  `2015-01-28 16:06:23 DEBUG    Thread-45 :: Metadata provider KODI creating episode metadata for CSI Crime Scene Investigation - 15x16 - The Last Ride`... note that the video is moved/renamed but the .nfo is NOT created. 

Log is here http://pastebin.com/Sqv33W2W

**Comment by clinton-hall** [comment]
I just checked the commits, and nothing has changed since this last worked... I suspect this may be related to a metadata server that isn't responding?

**Comment by TagForce** [comment]
Is the provider for that show TVRage?
I've noticed that TVRage is throwing some
```Unable to look up show on TVRage, not downloading images: error Connection error HTTPConnectionPool(host='services.tvrage.com', port=80): Max retries exceeded with url: /myfeeds/episode_list.php?key=Uhewg1Rr0o62fvZvUIZt&sid=36199 (Caused by : [Errno 104] Connection reset by peer) while loading URL http://services.tvrage.com/myfeeds/episode_list.php```
errors, which would account for it not being able to fetch episode information for metadata.

**Comment by fernandog** [comment]
Blocked ip? Can you access from browser?

**Comment by TagForce** [comment]
Yeah, it works fine. It's just throwing out those errors every once in a while, like TVRage is having some issues. Haven't seen them in a while now, though.

Clinton, could you try again?

**Comment by fernandog** [comment]
Im on phone but will check if http 503 error could generate this

**Comment by clinton-hall** [comment]
I believe the 3 shows that experienced this yesterday were all using thetvdb. 
one show was CSI, which downloaded an eppisode 3 days ago and generated the .nfo without issue.
I should have a few more downloads later today, so I'll try and find out if these work (it was a temporary issue), or if the problem is still present.

**Comment by clinton-hall** [comment]
ok... turns out TMDB / XEM is not working for me...
I added a new show... it is stuck at `Loading` on the shows page and I cannot access this show to edit it etc... No show banner, no info. Just `Loading`
Here are logs showing adding the show
```
2015-01-29 10:58:18 DEBUG    Thread-54 :: Empty lookup result - no XEM data for show 73940 on theTVDB
2015-01-29 10:58:16 DEBUG    Thread-54 :: Looking up XEM scene mapping using for show 73940 on theTVDB
2015-01-29 10:56:29 DEBUG    Thread-40 :: Setting permissions for /volume1/Public/TV/The Walking Dead to 777 as parent directory has 777
2015-01-29 10:56:12 DEBUG    Thread-60 :: Searching for Show with searchterm: the walking dead on Indexer: theTVDB
```

**Comment by clinton-hall** [comment]
Restarted SickRage and added the same show with TVRage.... worked fine...
So the issue is something with theTVDB lookups?

**Comment by clinton-hall** [comment]
With Episode Metatdata disabled (no Season##\filename.nfo) two episodes have successfully processed.

**Comment by fernandog** [comment]
@clinton-hall using proxy for indexers?

**Comment by clinton-hall** [comment]
No proxies set here.
I can try restarting my NAS and router etc... If I am the only person experiencing this, then it sounds like my system is being stupid ;)

**Comment by fernandog** [comment]
I had a problem in the past with SSL and restarting router+RPI fixed

**Comment by clinton-hall** [comment]
I restarted my Router and NAS, SickRage also updated... I can now add shows from TheTVDB so I have re-enabled episode metadata and will see what happens when shows download.

**Comment by clinton-hall** [comment]
yep... all working good again now...

Something went funny with my DNS/CACHE...

Thanks for the help.
