### ISSUE TITLE
[Feature Request] Add BaconBits's torrent provider

### ISSUE THREAD

**Issue by Vastlee** [SiCKRAGETV/sickrage-issues#506]
Or at least that is what appears to be happening. Here an example of the errors:

```
DEBUG SEARCHQUEUE-MANUAL-164541 :: [baconBits] :: Unable to parse the filename QI.-.S12E15.[HDTV./.x264./.AC3./.MKV./.720p] into a valid show
DEBUG SEARCHQUEUE-MANUAL-164541 :: [baconBits] :: Using ALL regexes
DEBUG SEARCHQUEUE-MANUAL-164541 :: [baconBits] :: Attempting to add item to cache: QI.-.S12E15.[HDTV./.x264./.AC3./.MKV./.720p]
DEBUG SEARCHQUEUE-MANUAL-164541 :: [baconBits] :: Unable to parse the filename Helix.S02E01.[HDTV./.x264./.AC3./.MKV./.720p] into a valid show
DEBUG SEARCHQUEUE-MANUAL-164541 :: [baconBits] :: Using ALL regexes
DEBUG SEARCHQUEUE-MANUAL-164541 :: [baconBits] :: Attempting to add item to cache: Helix.S02E01.[HDTV./.x264./.AC3./.MKV./.720p]
DEBUG SEARCHQUEUE-MANUAL-164541 :: [baconBits] :: Unable to parse the filename Hawaii.Five-O.S05E12.[HDTV./.x264./.AC-3./.MKV./.720p] into a valid show
DEBUG SEARCHQUEUE-MANUAL-164541 :: [baconBits] :: Using ALL regexes
DEBUG SEARCHQUEUE-MANUAL-164541 :: [baconBits] :: Attempting to add item to cache: Hawaii.Five-O.S05E12.[HDTV./.x264./.AC-3./.MKV./.720p]
DEBUG SEARCHQUEUE-MANUAL-164541 :: [baconBits] :: Unable to parse the filename Girl.Meets.World.S01E18.[WEB-DL./.H.264./.AC3./.MKV./.720p] into a valid show
DEBUG SEARCHQUEUE-MANUAL-164541 :: [baconBits] :: Using ALL regexes
DEBUG SEARCHQUEUE-MANUAL-164541 :: [baconBits] :: Attempting to add item to cache: Girl.Meets.World.S01E18.[WEB-DL./.H.264./.AC3./.MKV./.720p]
DEBUG SEARCHQUEUE-MANUAL-164541 :: [baconBits] :: Unable to parse the filename Hawaii.Five-O.S05E12.[HDTV./.x264./.AC-3./.MKV./.720p] into a valid show
DEBUG SEARCHQUEUE-MANUAL-164541 :: [baconBits] :: Using ALL regexes
DEBUG SEARCHQUEUE-MANUAL-164541 :: [baconBits] :: Attempting to add item to cache: Hawaii.Five-O.S05E12.[HDTV./.x264./.AC-3./.MKV./.720p]
DEBUG SEARCHQUEUE-MANUAL-164541 :: [baconBits] :: Unable to parse the filename Hawaii.Five-0.S05E12.[.HDTV./.x264./.AAC./.MP4./.576p.] into a valid show
DEBUG SEARCHQUEUE-MANUAL-164541 :: [baconBits] :: Using ALL regexes
DEBUG SEARCHQUEUE-MANUAL-164541 :: [baconBits] :: Attempting to add item to cache: Hawaii.Five-0.S05E12.[.HDTV./.x264./.AAC./.MP4./.576p.]
DEBUG SEARCHQUEUE-MANUAL-164541 :: [baconBits] :: Unable to parse the filename Shark.Tank.-.Season.1.[PDTV./.XVID./.MP3./.AVI./.SD] into a valid show
```

**Comment by flightlevel** [comment]
Are all those TV shows in the above log in YOUR own SickRage collection of shows?

I get heaps of those in debug view, even though the show is named correctly. I always thought it was just because they were shows NOT in my database.
eg. 
```
2015-01-28 21:07:41 DEBUG    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Unable to parse the filename The.Flash.2014.S01E11.480p.HDTV.x264-mSD into a valid show
```
There is no way for SickRage to parse the above filename as there would be no way for SickRage to know that 'The Flash' is a TV show or gibberish unless the show is added to my collection.ie. SickRage doesn't know every TV ever produced.

**Comment by fernandog** [comment]
Please use the issue guidelines when posting an issue. This way the dev team is able to debug your problem. Don't forget to use [markdown](https://guides.github.com/features/mastering-markdown/) on any code and log you want to post in-line.

- [ ] Branch
- [ ] Commit hash
- [ ] Operating system and python version
- [ ] What did you do?
- [X] What happened?
- [ ] What did you expect?
- [ ] Link to a copy/paste of your logfile with clear debug info of the error on [pastebin](http://pastebin.com/) (or in-line using [markdown](https://guides.github.com/features/mastering-markdown/) for small snippets)

**Comment by fernandog** [comment]
@flightlevel
Try adding "The Flash 2014" to scene exceptions

**Comment by abeloin** [comment]
@Vastlee Can you provide a raw version of your rss data with the apikey data remove?

We added the ability to choose the rss title in the data, so maybe there is way to choose a format SR can understand: https://github.com/SiCKRAGETV/SickRage/pull/1335

**Comment by fernandog** [comment]
@Vastlee please reply or will close this

**Comment by Vastlee** [comment]
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<channel>
		<title>TV show Torrents :: baconBits</title>
		<link>http://baconbits.org/</link>
		<description>RSS feed for all new TV show torrents.</description>
		<language>en-us</language>
		<lastBuildDate>Wed, 08 Apr 2015 11:38:10 +0000</lastBuildDate>
		<docs>http://blogs.law.harvard.edu/tech/rss</docs>
		<generator>Gazelle Feed Class</generator>
		<item>
			<title><![CDATA[The Musketeers Season 2 [Blu-ray / X264 / DTS / MKV / 1080p] ]]></title>
			<description><![CDATA[Title:The Musketeers Season 2 [Blu-ray / X264 / DTS / MKV / 1080p]

TV Series Description:

Set on the streets of 17th century Paris, series gives a contemporary take on the classic story about a group of highly trained soldiers and bodyguards assigned to protect King and country.

Episodes:

1. Keep your friends close
2. An ordinary man
3. The good traitor
4. Emilie
5. The return
6. Through a glass darkly
7. A Marriage of Inconvenience
8. The prodigal Father
9. The accused
10. Trial and Punishment

Links:

IMDB
WIKI

Screenshots:


















    the.musketeers.s02e01.1080p.bluray.x264-shortbrehd.mkv

(View raw mediainfo)


    
     
        General
        
            Container: Matroska
            Size: 4.37 GiB
            Duration: 58mn 38s
            Bitrate: 10.7 Mbps
        
    

    &nbsp;

    
    
        Video
        
            Codec: x264
            Profile: High@L4.1
            Resolution: 1920 x 1080
            DAR: 16:9
            Bitrate: 9 161 Kbps
            Duration: Unknown
        
    

    &nbsp;

    
     
        Audio
        
                    2 ch
            English            DTS            @ 1 509 Kbps            
                
    





    
        
            (+)
                        Encode does not meet high quality encoding requirements
                    
    
    
                    Encoding Settings:
            
                                    cabac = 1
                                    mixed_ref = 1
                                    analyse = 0x3:0x133 or 0x3:0x113
                                    subme = 9, 10, or 11
                                    trellis = 2
                                    me = umh, esa or tesa
                                    rc = crf or 2pass
                                    bframes =&gt; 3
                                    ref between 4 and 6
                                    me_range =&gt; 16
                                    bitrate &gt; 8000
                            
            
                
                    Warnings:
            
                                    The field &quot;Duration&quot; is wanted in the &quot;Video&quot; section.
                            
                    



    
General
Complete name                            : /home/ironworm/rtorrent/downloads/Musketeers/Upload/The.Musketeers.S02.1080p.BluRay.x264-SHORTBREHD/the.musketeers.s02e01.1080p.bluray.x264-shortbrehd.mkv
Format                                   : Matroska
Format version                           : Version 2
File size                                : 4.37 GiB
Duration                                 : 58mn 38s
Overall bit rate                         : 10.7 Mbps
Writing application                      : mkvmerge v6.6.0 (&#39;The Edge Of The In Between&#39;) built on Dec 1 2013 17:55:00
Writing library                          : libebml v1.3.0 + libmatroska v1.4.1

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Bit rate                                 : 9 161 Kbps
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Original frame rate                      : 25.000 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.177
Writing library                          : x264 core 146 r2538 121396c
Encoding settings                        : cabac=1 / ref=4 / deblock=1:-2:-2 / analyse=0x3:0x113 / me=umh / subme=8 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=6 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=50 / rc=2pass / mbtree=1 / bitrate=9161 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ip_ratio=1.40 / aq=1:1.00
Language                                 : English
Default                                  : Yes
Forced                                   : No

Audio
ID                                       : 2
Format                                   : DTS
Format/Info                              : Digital Theater Systems
Mode                                     : 16
Format settings, Endianness              : Big
Codec ID                                 : A_DTS
Duration                                 : 58mn 38s
Bit rate mode                            : Constant
Bit rate                                 : 1 509 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Bit depth                                : 24 bits
Compression mode                         : Lossy
Stream size                              : 633 MiB (14%)
Language                                 : English
Default                                  : Yes
Forced                                   : No

Menu
00:00:00.000                             : en:00:00:00.000
00:07:56.920                             : en:00:07:56.920
00:18:56.560                             : en:00:18:56.560
00:28:32.040                             : en:00:28:32.040
00:38:14.680                             : en:00:38:14.680
00:50:40.120                             : en:00:50:40.120



]]></description>
			<pubDate>Wed, 08 Apr 2015 11:20:52 +0000</pubDate>
			<link>http://baconbits.org/torrents.php?action=download&amp;authkey=<myauthkey>&amp;torrent_pass=<mytorrentpass>&amp;id=<myid></link>
			<guid>http://baconbits.org/torrents.php?action=download&amp;authkey=<myauthkey>&amp;torrent_pass=<mytorrentpass>&amp;id=<myid></guid>
			<comments>http://baconbits.org/torrents.php?id=<myid></comments>
			<category><![CDATA[Adventure, Drama]]></category>
			<dc:creator>Badur</dc:creator>
		</item>
	</channel>
</rss>

**Comment by Vastlee** [comment]
And a pastebin of it since this is picking up the xml stuff

http://pastebin.com/Du2G7ftj

**Comment by neoatomic** [comment]
@fernandog Does this issue need a bug/issue label.? Of can it even be closed.?

**Comment by fernandog** [comment]
Keep open.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
