### ISSUE TITLE
SickRage cannot update to develop branch

### ISSUE THREAD

**Issue by baskinghobo** [SiCKRAGETV/sickrage-issues#507]
Master Branch
Commit hash - sorry i don't know what this is.
Windows 8 x64 and python 2.7.8 x64
SickRage cannot update to develop branch through the SickRage Ui and there is no info in the error log.
Debug log - http://pastebin.com/zx0H38ff

**Comment by fernandog** [comment]
2015-01-28 23:30:11 INFO     CHECKVERSION :: No update needed

**Comment by fernandog** [comment]
2015-01-28 23:30:11 INFO     CHECKVERSION :: No update needed

**Comment by TagForce** [comment]
Are you sure you're on the master branch? The logs give you the current commit for the develop branche, so it should be on develop now.
You need to restart SR for it to show the new branch, though.

**Comment by baskinghobo** [comment]
Hmm how do i check? When i first installed sickrage i used this guide- http://www.htpcguides.com/install-sickrage-windows-usenet-torrent-tv/ which should install as master branch. I then updated it to dev branch and it was successful at shutting down but not starting again so i just closed the tab and reopened it and sickrage said update failed.

**Comment by TagForce** [comment]
In Config -> Help & Info (in the menu on the homepage) it says which Branch and Commit you're on.
(http://sickrageurl/config)

**Comment by baskinghobo** [comment]
ok seems like i am on develop version. thanks i will close this now
