### ISSUE TITLE
season errata and directory structure

### ISSUE THREAD

**Issue by tarnalcock** [SiCKRAGETV/sickrage-issues#508]
Hi Guys,

As per https://sickrage.tv/forums/forum/help-support/general-support/17396-season-errata-and-folder-formats

I have recently configured SR and added all of my existing shows.

Firstly all the shows are contained in a ../Series/ or ../Anime/ folder within a ../Watch folder. So I added both Series & Anime as watch folders in SR.

Then I went through each show in each of those folders and set my defaults etc in the add wizard.

I set my episode naming mask to Season %0S/%0Sx%0E - %EN/%0E %EN.

This works beautifully except for the fact that all season/episode specific banners, episode thumbs and posters etc are still stored in the show's root rather than under their relevant folders.
To give an example - Doctor Who (2005) lives in D:/Personal/Watch/Series/Doctor Who (2005)/ and the structure thereafter is as follows:
>../Doctor Who (2005)/
>>banner.jpg
>>fanart.jpg
>>folder.jpg
>>poster.jpg
>>season01-banner.jpg
>>1x01 - EpisodeName-thumb.jpg
>>tvshow.nfo
>>season01.tbn
>>/Season 01/
>>>/EP 01x01/
>>>>EP01.mp4
>>>>EP01.nfo
>>>>EP01.tbn

Surely season/episode specific items should be in the folders, like so:
>../Doctor Who (2005)/
>>banner.jpg
>>fanart.jpg
>>folder.jpg
>>poster.jpg
>>tvshow.nfo
>>/Season 01/
>>>season01.tbn
>>>season01-banner.jpg
>>>/01x01 EP Name/
>>>>EP01.mp4
>>>>EP01.nfo
>>>>EP01.tbn
>>>>1x01 - EpisodeName-thumb.jpg​

Maybe I am missing something here, or just being too OCD. I like the folder structure I am currently using as it is human readable, not too cluttered and clearly defined.

I see, however that SR prefers a 'Flat Folder' structure and even goes so far as to indicate whether a show is contained as such.

Is flat folder somehow better or preferable? Am I correct in assuming that 'Flat Folder' means everything gets lumped together in one folder?

Is the aforementioned storage scheme necessary (i.e. having season/episode specific thumbs and tbn files in the root rather in their specific folders)?

I am running SR on Windows 8.1 64x alongside Kodi, integrated with uTorrent and all is harmonious.

I do however plan to port this to my Linux based media center once I get internet at home and have finalized my ideal setup.

**Comment by TagForce** [comment]
There is currently a Pull Request that fixes at least part of this issue. I don't exactly know how SR handles episode folders within Season folders, but at least the episode files not renaming properly is fixed. I'll check to see what it does when I place the episodes in a seperate folder.

**Comment by tarnalcock** [comment]
Thank you for the clarification @TagForce. Much appreciated. The naming conventions seemed fairly ok on my side I did not notice any glaring mistakes.
