### ISSUE TITLE
[APP SUBMITTED]: 'list' object has no attribute 'scene_season'

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#509]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) 
[GCC 4.6.3]**
Operating System: **Linux-3.12.31-armv6l-with-debian-7.6**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@91cb8d885ca278e5829ed53d856d578c8ee8cbe0
Link to Log: https://gist.github.com/3cfb64aac488dad7ac0e
### ERROR
```
SEARCHQUEUE-RETRY-259765 :: [TorrentDay] :: Error while searching TorrentDay, skipping: 'list' object has no attribute 'scene_season'
SEARCHQUEUE-RETRY-259765 :: [HDTorrents] :: Error while searching HDTorrents, skipping: 'list' object has no attribute 'scene_season'
SEARCHQUEUE-RETRY-259765 :: [NZBgeek VIG] :: Error while searching NZBgeek VIG, skipping: 'list' object has no attribute 'scene_season'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@TagForce this happened when I merged your PR correcting failed downloads. I enabled failed downloads but not PP. All providers give this error

**Comment by TagForce** [comment]
@fernandog You don't need to enable failed download handling for the pulldown to work. I'm not sure if this is related to my fix for setting episodes to failed, but it could be. It's the same kind of error (getting a list, when a single instance is expected), though.
Strange that I do not see this behavior.

**Comment by TagForce** [comment]
@fernandog
line 267 of search_queue.py: 
change
searchResult = search.searchProviders(self.show, self.segment, True)

to
searchResult = search.searchProviders(self.show, self.segment[0], True)

tell me if that fixes it.

**Comment by TagForce** [comment]
@fernandog
Check something else for me as well, if you can. I'm on mobile so can't test myself.

On a clean develop branch (without my fix):
webserve.py line 1657:
change
cur_failed_queue_item = search_queue.FailedQueueItem(showObj, [segment])

to 
cur_failed_queue_item = search_queue.FailedQueueItem(showObj, segment)

and check if that fixes all of it.
I think it will. It passes segment as a list, while the same line for WANTED episodes passes it just as a variable.

**Comment by fernandog** [comment]
@TagForce sorry. I'm very busy these last days. My newborn is going to school Will try that soon. sorry

**Comment by TagForce** [comment]
No problem. I've tested it myself and it seems to work. Resubmitted the PR.

**Comment by fernandog** [comment]
thanks!
