### ISSUE TITLE
'Sort with...'   option in setting not working correctly

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#51]
<a href="https://github.com/andyblac"><img src="https://avatars.githubusercontent.com/u/77936?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [andyblac](https://github.com/andyblac)**
_Monday Dec 08, 2014 at 10:54 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/1047 (3 comment(s))_

----

BRANCH: (develop) / COMMIT: (882950f66192a9500a112cb27e52d52a15031e8c) 

when sorting the list by anything other than NAME, the config option 'Sort with "The", "A", "An"' is being ignored, thus resulting in the list grouping all 'THE, A', etc together.

see screen shots,

the first png show that the list is sorting title correctly ignoring 'The ' from tile, i.e. 'The 100' is at top of list as it is sorted just by '100'.
![01-sorted by name](https://cloud.githubusercontent.com/assets/77936/5338003/1a66e7fc-7ec7-11e4-9bd3-08fde85e5dff.png)

02 png shows the list sorted by 'Downloads' it first groups all the needed Episodes together, then all the completed are grouped together, but whilst it is sorted by the title by A-Z all the 'A, The' etc are not being ignored, as you see 'the show 'The 100' is not at top.
![02 sorted by downloads](https://cloud.githubusercontent.com/assets/77936/5338104/4c0d88be-7ec8-11e4-9138-65f256659616.png)

png 03 as you all the 'The' are grouped together, this should not be the case.
![03 sorted by downloads](https://cloud.githubusercontent.com/assets/77936/5338121/6e0b36a0-7ec8-11e4-8e9f-27d25fb12263.png)

here is settings screen.
![settings](https://cloud.githubusercontent.com/assets/77936/5338154/c84d051c-7ec8-11e4-9ae6-740cbe059a3e.png)

**Comment by abeloin** [comment]
@fernandog 
Tablesorter limitation.
Workaround:
1. Click header 'Download'.
2. Shift-Click header 'Show'.
3. Again, Shift-Click header 'Show'.

See Tip in https://mottie.github.io/tablesorter/docs/index.html#Demo for more info

**Comment by abeloin** [comment]
@gregpardo Submitted a pull request with a fix. See SiCKRAGETV/SickRage#1217

**Comment by fernandog** [comment]
@abeloin thanks again! I will ask @echel0n to put you in issue-tracker group and in the sickrage code too). I'm sure he will appreciate the help coding !

**Comment by markheloking** [comment]
@fernandog I'm sure he'd appreciate the help on the team in the tracker. Not sure how keen he is to add people with write permission to the branches since the last debacle with adam and supremicus. Would be nice though since he's away this much, so we can merge the prs and stuff.

**Comment by fernandog** [comment]
@markheloking I didn't know that.

I know we must update the wiki ASAP.

**Comment by markheloking** [comment]
@fernandog I agree we should have someone that's able to do stuff when @echel0n is away, although it should be someone that uses caution (as to not introduce bad bugs while @echel0n is away). It would also enable us to edit the wiki page, although we can also do that by moving it from the main fork to the issue fork (because we cán write over there).
Have you been able to contact @echel0n?

**Comment by fernandog** [comment]
@andyblac  please update SR and report back please. Fix was merged

**Comment by andyblac** [comment]
jusr reclone develop branch sorting is just same not working, to test click on 'Downloads' to sort via that, all the 'The'' are stil' grouped together.

![screen shot 2015-01-30 at 00 12 34](https://cloud.githubusercontent.com/assets/77936/5968882/c1d7aa78-a814-11e4-83d8-8b310ba259f9.png)


![screen shot 2015-01-30 at 00 11 55](https://cloud.githubusercontent.com/assets/77936/5968874/a6a7c9d6-a814-11e4-940f-d923f6f5775e.png)

**Comment by fernandog** [comment]
did you tried:
1. Click header 'Download'.
2. Shift-Click header 'Show'.
3. Again, Shift-Click header 'Show'.

**Comment by fernandog** [comment]
@andyblac tested here and it's working

![sort](https://cloud.githubusercontent.com/assets/2620870/5969007/832a564a-a805-11e4-8f34-90127bca5a38.png)

**Comment by andyblac** [comment]
with dark skin ??

**Comment by abeloin** [comment]
@andyblac I think fernandog's message was meant to gregpardo.
@gregpardo please update SR and report back please. Fix was merged

**Comment by fernandog** [comment]
No. @andyblac cloned the new version and said it not working.
@abeloin cache should be cleanned?

**Comment by abeloin** [comment]
@fernandog But the pull requests SiCKRAGETV/SickRage#1217 is for gregpardo issue. For andyblac, I'm currently testing using [sortAppend](http://mottie.github.io/tablesorter/docs/example-option-sort-append.html)

**Comment by andyblac** [comment]
@fernandog that looks like you are sorting name, that works and not the issue, try sorting via DOWNLOADS, then name is not sorted correctly ie all the 'The' are grouped together.

**Comment by abeloin** [comment]
@andyblac Can you try this commit https://github.com/abeloin/SickRage/commit/f79951832eaa8e7fc644c16b216f7d568fba2f43? With it you don't need to use the shift key.

**Comment by andyblac** [comment]
@abeloin yes that works :+1:

**Comment by abeloin** [comment]
@andyblac Done
@fernandog See SiCKRAGETV/SickRage#1276 fix OP issue

**Comment by fernandog** [comment]
Thanks!
