### ISSUE TITLE
Add support to send notification to multiple devices on Pushbullet

### ISSUE THREAD

**Issue by edgard** [SiCKRAGETV/sickrage-issues#511]
Currently we are limited to send to only one device. It would be awesome if we have something like CouchPotato that provides the option to send all or to a list of devices we wanted.

**Comment by oresot** [comment]
+1

It would be great to push to our contacts too (I'm not alone at home). With the pushbullet api you get the contacts "iden" as if they were just another device, so both things could be solved at the sime time.

**Comment by Arcanemagus** [comment]
@oresot With the Pushbullet API sending to all of your _own_ devices is done by simply omitting the target. This does not send to your contacts though, it seems they need to be manually specified to receive a message.

To do what you are asking would require resending the message to each desired recipient. You should probably create a new feature request for that as it is beyond the scope of this request.

**Comment by fernandog** [comment]
@edgard develop updated. please test and report back

**Comment by edgard** [comment]
Perfect! Just tested and both 'All' or individual devices are working as intended.

Good job! Thanks guys!

**Comment by elRadix** [comment]
Can you please add channel support by adding channel_tag like in CouchPotato ?
