### ISSUE TITLE
[Feature Request] Re-snach downloads that have taken longer then X days

### ISSUE THREAD

**Issue by BrandonOCasey** [SiCKRAGETV/sickrage-issues#512]
Right now I end up having a lot of downloads that either loose seeders to the point where I cannot download at all, or never had any seeders to being with. I think it would be safe to say if I have yet to download a file in X days that it should be searched for again.

**Comment by wripet** [comment]
Imo it would be better to deal with those downloads marking them as stalled. Procedure could be the following: If DL is idle for X days, mark it as stalled, if SR sees a stalled download, mark that one as failed, delete it from the download history and the downloader, pick the next best download from the history. NzbToMedia might support that in the upcoming future: https://github.com/clinton-hall/nzbToMedia/issues/666

**Comment by TagForce** [comment]
@fernandog @abeloin Now that develop is becoming more and more stable, and there's only a couple of issues left that need attention, I'm going to start development of this feature request.

My idea for the first version is a new thread (DownloadFlowCheck) which does the following:
- check the episode list for episodes set to snatched
- look up the date for the snatch in the history db
- if the date is earlier than now - DownloadTimeThreshold (configurable in settings in hours) then when FailedDownloads is enabled run FailedDownload for that episode (gets added to the failed downloads and put back to wanted), else set the status back to wanted so it resnatches it.
- Notify the user which downloads were deemed stalled (single notification) and tell them to check their downloaders for errors.

This should work in the most basic form. Then when some more feature requests are added to SR concerning torrentclient support, we can expand on this setup by actually telling the download client to stop the concerning torrents/NZBs so it effectively cleans up after itself.

Any thoughts?

**Comment by fernandog** [comment]
@TagForce @abeloin what if PP is disabled? We must separete failed feature from PP. Otherwise we can't do failed via API or manually via displayshow. Set manually as failed should trigger the add the failed release to failed.db and snatch another one.

**Comment by TagForce** [comment]
@fernandog Failed download has nothing to do with PP. And you can of course turn this option off entirely, much like subtitle downloads (it simply will only be scheduled if StaleDownloads is true).

Failed downloads only work on episode statusses. If you set an episode to failed, it will add the download to the failed.db and simply set the status back to Wanted, or snatched if it can immediately find an alternative download in the cache.

PP only checks folders (either the one set in TV_DOWNLOAD, or entered in the PP page, or passed through the api) for files it can convert into a downloaded episode. It does not set any episode to failed, and even if it does, it wouldn't interfere with the Stale Check as those statusses would be reflected in the DB as well. You should only run stale checking once or twice per day anyway.

**Comment by fernandog** [comment]
@TagForce to me it's confusing as failed is inside PP settings. If you are sure it's PP independent we should create a new tab called "Failed downloads" - to add this new FR settings too

there's a lot of people that don't use PP and have all eps as snatched and not downloaded. This should be opt-in. default off.

**Comment by TagForce** [comment]
@fernandog It is a part of a PP run, but it has no bearing on the actual post processing... I'm not checking failed downloads, I'm only checking stale downloads (that never finish downloading, so are never PP'd)

Failed Downloads only checks for folders that start with _UNDERSIZED_ or _FAILED_.
My check will only check those for which this condition is not true.

**Comment by fernandog** [comment]
@TagForce as a user who don't user PP, can I enabled "failed" but not PP? if I mark manually as failed in displayshow, will it add to failed.db and try to snatch another release?

**Comment by TagForce** [comment]
@fernandog Yes, that should work. Marking as failed does not use any part of the PP process.

**Comment by fernandog** [comment]
so cant we duplicate this setting or create a sub group inside PP tab? like github settings

**Comment by TagForce** [comment]
@fernandog We could, but wouldn't it be overkill to add a new section for 2 checkboxes?
If you imagine Failed Download handling as the automatic handling of failed downloads (from SabNZBd, no other clients as far as I know) then it should be part of PP, as the validateDir routine is called within a PP run and that checks for failed download folders. The unfortunate part is that the same setting also enables/disables marking an episode bad manually, so that might confuse someone.

**Comment by fernandog** [comment]
@TagForce 
just enabled failed downloads, set manually as failed 
Don't worked. Downloaded the same release. Failed db is 4096 bytes

all my /config/postProcessing/ settings are empty or disabled

**WARNING: Episode not found in history. Setting it back to WANTED**
DEBUG logs are related about about this history/failed

```
2015-02-27 11:15:11 INFO     SEARCHQUEUE-RETRY-248682 :: NMA: Notification sent to NotifyMyAndroid
2015-02-27 11:15:07 INFO     SEARCHQUEUE-RETRY-248682 :: Downloading ****] from Rarbg
2015-02-27 11:15:07 INFO     SEARCHQUEUE-RETRY-248682 :: Quality of **** is 1080p WEB-DL
2015-02-27 11:15:00 INFO     SEARCHQUEUE-RETRY-248682 :: [Rarbg] :: Performing episode search for ****
2015-02-27 11:13:59 INFO     SEARCHQUEUE-RETRY-248682 :: Building internal name cache for ****
2015-02-27 11:13:37 INFO     SEARCHQUEUE-RETRY-248682 :: Beginning failed download search for: [**** - 4x16 - ****]
2015-02-27 11:13:34 WARNING  SEARCHQUEUE-RETRY-248682 :: WARNING: Episode not found in history. Setting it back to WANTED
2015-02-27 11:13:34 INFO     SEARCHQUEUE-RETRY-248682 :: Reverting episode (4, 16): ***
2015-02-27 11:13:33 INFO     SEARCHQUEUE-RETRY-248682 :: Marking episode as bad: [**** - 4x16 - ****]
2015-02-27 11:13:33 INFO     Thread-193 :: Retrying Search for **** season 4 because some eps were set to failed
```

**Comment by TagForce** [comment]
@fernandog An episode needs to be in the history table for it to be marked as bad. I see the setting it back to Wanted as well at times.

**Comment by fernandog** [comment]
@TagForce but that episode is!

![1](https://cloud.githubusercontent.com/assets/2620870/6418730/3012ecd6-be96-11e4-994d-e6eead151b00.png)

or it's a different table?

**Comment by TagForce** [comment]
Is there anything under manage - Failed Downloads?

**Comment by fernandog** [comment]
@TagForce nothing. empty table

**Comment by fernandog** [comment]
@TagForce i thinkg the PP that get's the bad release and provider and insert into failed.db

**Comment by fernandog** [comment]
@TagForce I show up in the history only for episodes snatched AFTER I enabled failed downloads. we should add this to setting description. Also say it can work even if PP is disabled. Cause this setting is inside PP settings and it's confusing

**Comment by neoatomic** [comment]
@fernandog This issue looks duplicate with https://github.com/SiCKRAGETV/sickrage-issues/issues/225 
Can i close this.?

**Comment by fernandog** [comment]
Keep both open. Has a lof of discussion here

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
