### ISSUE TITLE
Feature Request: Set time delay when to look for an episode

### ISSUE THREAD

**Issue by mik11231** [SiCKRAGETV/sickrage-issues#513]
I've been experiencing a bunch of fakes getting downloaded because the search tries to search for a show as soon as it airs. I know some people actually like that, and some would prefer it to happen earlier even. I would prefer it happens later and i don't mind waiting another couple of hours after a release to ensure i get a proper copy. 
Would it be possible to add either a global setting (search for episodes X hours in relation to air time (positive numbers for after air time and negative numbers for before air time) or the same setting but on a show by show basis so that people can set the search time for whatever works for them?

Thank You

**Comment by fernandog** [comment]
Disable daily search for all providers.

**Comment by mik11231** [comment]
wouldn't that make it an entire day wait in some cases? and what about shows that air at or close to the time backlog happens? the point of this isnt to delay by a lot it's to either delay by a littler or even have the search happen earlier than it normally would

**Comment by neoatomic** [comment]
Same as https://github.com/SiCKRAGETV/sickrage-issues/issues/501
