### ISSUE TITLE
[Feature Request] Show and link unrecognised files to an episode

### ISSUE THREAD

**Issue by Al-25** [SiCKRAGETV/sickrage-issues#516]
This request is not from me but i would definitly like to see it in sickrage : 

See : https://sickrage.tv/forums/forum/main-category/feature-requests/5462-manually-map-files-to-episodesv

"From time to time I download a special or some other episode that doesn't get detected by SR. The only way to fix this is to go and rename the file enough for SR to know what the file is. It would be very useful if SR allowed me to select undetected files and map them manually to episodes. It would save me the trouble of first going to SR to find out the actual identifier for the show, then heading back to the file and renaming the file (paying attention to the required format) and then going back to SR to rescan.

One stop solution would be lovely. "

**Comment by nytemyst** [comment]
I would love this as well.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
