### ISSUE TITLE
[Feature Request] Add Web-rip quality

### ISSUE THREAD

**Issue by kristofferbas** [SiCKRAGETV/sickrage-issues#517]
I have noticed that SickRage sometimes finds Web-rips and displays them as Web-dl (which is what I want to download). Would be nice to have web-rip as a quality in SR too.

Thanks!

**Comment by fernandog** [comment]
as alternative add web-rip as Required Words

**Comment by kristofferbas** [comment]
Ah, good idea!

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
