### ISSUE TITLE
Feature Request: API Request - Initiate Post Processing

### ISSUE THREAD

**Issue by JacksonB** [SiCKRAGETV/sickrage-issues#518]
I'd like to be able to initiate a post-processing pass through an API call.

Default would be to use the existing post-processing settings. Optional arguments could be the manual post-processing setting

    ?cmd=SickRage.PostProcess

    ?cmd=SickRage.PostProcess&path=home.user.downloads.new&method=move&force=true&priority=false
​
With the length of time that a post-processing request could take I don't think it is valuable to return anything. Also PostProcess requests that are handled while an existing one is running should queue up another immediately following.

This would allow external tools to initiate post-processing without making multiple requests to deal with handling cookies, certificates and saving the user's password somewhere.

**Comment by fernandog** [comment]
See this:
https://sickrage.tv/forums/forum/help-support/general-support/16679-resolved-post-processing-url-no-longer-working-%60http-403-forbidden

**Comment by mbausch** [comment]
fernandog, that's a useful thread but I hope you don't consider the matter settled.  I've seen JacksonB's posts in a couple different places today and everyone keeps pointing to this other, non-api solution for his request to have an api call implemented.  I agree with him that a solution which uses the api key is vastly superior to a call which has to incorporate the username and password.  Add to that, now you have to make two calls to perform one task, it's less secure AND a somewhat bigger pain.

**Comment by Hellowlol** [comment]
The api command shouldnt return any data.

See https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/webapi.py#L1401

**Comment by Hellowlol** [comment]
@fernandog this feature request already exist in the api

**Comment by Thraxis** [comment]
As per Hellowlol this is already in the API

**Comment by andreofgyn** [comment]
In the postprocess api call, "failed" is hardcoded to False, why not add a "failed" parameter in the api to allow report bad downloads?

**Comment by Hellowlol** [comment]
It should, it's a oversight on my end.

**Comment by andreofgyn** [comment]
Humm, ok, should I open a ticket?

**Comment by Hellowlol** [comment]
Yes
