### ISSUE TITLE
RSSFeeds instance has no attribute 'rssDB'

### ISSUE THREAD

**Issue by kristofferbas** [SiCKRAGETV/sickrage-issues#519]
Have been getting these error with searching OZnzb the last couple of days. Is this a problem with SR or is it something I have done wrong?

Branch: develop
Commit hash: 91cb8d885ca278e5829ed53d856d578c8ee8cbe0
Your operating system and python version: Mac OSX Yosemite, Python2.7
Link to a copy/paste of your logfile with clear debug info of the error on PASTEBIN: http://pastebin.com/9YLjZcAw

```
AAAttributeError: RSSFeeds instance has no attribute 'rssDB'
AA    self.rssDB.close()
AA  File "/Applications/SickRage/sickbeard/rssfeeds.py", line 43, in getFeed
AA    return RSSFeeds(self.providerID).getFeed(self.provider.proxy._buildURL(url), post_data, self.provider.headers, items)
AA  File "/Applications/SickRage/sickbeard/tvcache.py", line 142, in getRSSFeed
AA    data = self.cache.getRSSFeed(search_url)
AA  File "/Applications/SickRage/sickbeard/providers/newznab.py", line 277, in _doSearch
AA    itemList += self._doSearch(curString, search_mode, len(episodes))
AA  File "/Applications/SickRage/sickbeard/providers/generic.py", line 286, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch)
AA  File "/Applications/SickRage/sickbeard/search.py", line 469, in searchProviders
2015-01-29 21:02:29 ERROR    SEARCHQUEUE-BACKLOG-75710 :: [OzNZB] :: Error while searching OzNZB, skipping: RSSFeeds instance has no attribute 'rssDB'
```

**Comment by TagForce** [comment]
@kristofferbas Please update to the latest develop release. You're about 88 commits behind at the moment :)

Let us know if that fixes the issue, or not.

**Comment by kristofferbas** [comment]
Updated but still didn't work. Deleated oznzb.db in cache/rss and now everything seems fine again :)

**Comment by fernandog** [comment]
@kristofferbas so can I close this issue ?

**Comment by kristofferbas** [comment]
@fernandog Yes, everything works now. Thanks!
