### ISSUE TITLE
[Feature Request] Add option to set failed/wanted over API

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#52]
<a href="https://github.com/fernandog"><img src="https://avatars.githubusercontent.com/u/2620870?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [fernandog](https://github.com/fernandog)**
_Monday Dec 08, 2014 at 11:20 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/1048 (2 comment(s))_

----

Ability to manually (via API) set an episode as failed/wanted and add it to the failed db without have post-processing enabled. This way I can set failed NZB and Torrents. Will be easier to setup "failed" feature. Without PP SR don't have to scan the folder as the API already tell's its failed)
I don't use PP because I have some scripts that move the video after the subtitle were downloaded. My subtitle provider won't be added to SR. I use periscope.

@Hellowlol what do you think?

**Comment by raymondtrueman** [comment]
This would greatly help me as I have a SeedBox with SabNZBd running on it. I can then use this feature of the API in my post downloading script to go and fail the download in SickRage. SickRage should then add the failed snatch to the failed db. Then set the status back to downloaded if a previous file for the episode exists or set it back to wanted if it doesn't exist. This would be one step closer to have an unattended solution. At the moment I have to watch SickRage like a baby to make sure it properly "fails" failed snatches so they can be retried on a different provider/quality

**Comment by MGaetan89** [comment]
This can already be done by using `/?cmd=episode.setstatus&indexerid=1234&season=1&status= failed|wanted`.

Is something else required here?

**Comment by Hellowlol** [comment]
a episodenumber?

**Comment by raymondtrueman** [comment]
I doubt it will write it to the failed database. I could be wrong. Also in a "post download" script how will I know what the showindexerid is? I suppose I can use the API to query it somehow

**Comment by MGaetan89** [comment]
@Hellowlol here is the doc for the `episode.setstatus` command. You can use it to change the status of a specific episode (see the optional `episode` parameter).
```json
{
    "data": {
        "optionalParameters": {
            "episode": {
                "allowedValues": "see desc", 
                "defaultValue": null, 
                "desc": "the episode number"
            }, 
            "force": {
                "allowedValues": [
                    0, 
                    1
                ], 
                "defaultValue": 0, 
                "desc": "should we replace existing (downloaded) episodes or not"
            }, 
            "tvdbid": {
                "desc": "thetvdb.com unique id of a show"
            }, 
            "tvrageid": {
                "desc": "tvrage.com unique id of a show"
            }
        }, 
        "requiredParameters": {
            "indexerid": {
                "desc": "unique id of a show"
            }, 
            "season": {
                "desc": "the season number"
            }, 
            "status": {
                "allowedValues": [
                    "wanted", 
                    "skipped", 
                    "archived", 
                    "ignored", 
                    "failed"
                ], 
                "defaultValue": null, 
                "desc": "the status values: wanted, skipped, archived, ignored, failed"
            }
        }
    }, 
    "message": "No description available", 
    "result": "success"
}
```

@raymondtrueman I don't know if it updates the failed database. I can check.
I'm not sure how you can get the indexerid. What information do you have in your post download script?

**Comment by raymondtrueman** [comment]
@MGaetan89 Thanks, please check for me. I will have to have a look at my current script and get back to you, haven't looked at it in ages

**Comment by MGaetan89** [comment]
https://github.com/MGaetan89/SickRage/blob/develop/sickbeard/webapi.py#L956

I'm not 100% sure, but looks likes nothing is done about the failed database. If I'm right, it should probably be added.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
