### ISSUE TITLE
Sickrage stops working randomly

### ISSUE THREAD

**Issue by sikko1** [SiCKRAGETV/sickrage-issues#524]
I installed Sickrage on Ubuntu 14.04(init.d), it works but after +- 30 minutes, it stops with working 
 When I start the service again manually (/etc/init.d/sickrage start), it stops again after 30 minutes.
I looked into the logs, and every time I got this error => 

*** glibc detected *** python: free(): invalid pointer: 0x9feda008 ***
Aborted

Can someone help me please, why I get this error and Sickrage stops with working.
Python 2.7.3
[GCC 4.6.3]
Thank you everyone

**Comment by fernandog** [comment]
Please use the issue guidelines when posting an issue. This way the dev team is able to debug your problem. Don't forget to use [markdown](https://guides.github.com/features/mastering-markdown/) on any code and log you want to post in-line.

- [ ] Branch
- [ ] Commit hash
- [X] Operating system and python version
- [ ] What did you do?
- [x] What happened?
- [] What did you expect?
- [ ] Link to a copy/paste of your logfile with clear debug info of the error on [pastebin](http://pastebin.com/) (or in-line using [markdown](https://guides.github.com/features/mastering-markdown/) for small snippets)

**Comment by fernandog** [comment]
no responde. closing
