### ISSUE TITLE
Log filled with "TypeError: zip argument #1 must support iteration"

### ISSUE THREAD

**Issue by lbjb** [SiCKRAGETV/sickrage-issues#527]
Branch: develop
    Commit hash: c62d8f2c799edd7daad5648f45276a3464d83a9e
    Your operating system and python version: FreeBSD 9.2-RELEASE-p9, Python 2.7
    What you did: Normal operation - processing show backlog
    What happened: Thousands of errors logged
    What you expected:
    Link to a copy/paste of your logfile with clear debug info of the error on PASTBIN: http://pastebin.com/KFet6DZW

**Comment by abeloin** [comment]
Which specific version of python do you have?

**Comment by lbjb** [comment]
>>> print (sys.version)
2.7.6 (default, Feb  6 2014, 13:32:45)
[GCC 4.2.1 20070831 patched [FreeBSD]]

**Comment by abeloin** [comment]
Can you try this commit https://github.com/TagForce/SickRage/commit/eedb42085b2d64a2f0aa51d269dff1fff11c4984?

**Comment by abeloin** [comment]
Scratch that, can you try reverting SiCKRAGETV/SickRage#1258?

**Comment by lbjb** [comment]
Happy enough to give this a try - can you give instructions on how to do that? Thanks.

**Comment by abeloin** [comment]
Here we go

* Stop sickrage
* Dowload: https://github.com/SiCKRAGETV/SickRage/pull/1258.diff
* Command line: ```git apply -R 1258.diff```
* Start sickrage
* Test again

If it doesn't resolve the issue, run this in command line to remove the changes:
```git checkout develop```

**Comment by fernandog** [comment]
@lbjb any luck?

**Comment by lbjb** [comment]
Sorry - just getting round to trying this tonight.  Change applied and currently testing. So far, so good. Will report back when it's been running a while longer.

**Comment by abeloin** [comment]
@lbjb Apply SiCKRAGETV/SickRage#1292 instead(fix for 1258):

* Stop sickrage
* Dowload: https://github.com/SiCKRAGETV/SickRage/pull/1292.diff
* Command line: ```git apply 1292.diff```
* Start sickrage
* Test again

If it doesn't resolve the issue, run this in command line to remove the changes(stop sickrage first):
```git checkout develop```

**Comment by lbjb** [comment]
OK - trying that now

**Comment by lbjb** [comment]
Looks good so far.

**Comment by fernandog** [comment]
@lbjb  develop updated. please test and report back

**Comment by abeloin** [comment]
@lbjb Any news?

**Comment by lbjb** [comment]
All good on dev branch. No more of these logs. Cheers.

**Comment by abeloin** [comment]
Thank you
