### ISSUE TITLE
Failed doing webui callback

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#528]
Branch: master
Commit hash: SiCKRAGETV/SickRage@401cb666016e45b42fe675bafdf7908ad6c2b9bb
OS: Ubuntu 14.04 64bit
Python: 2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]
Pastebin: http://pastebin.com/raw.php?i=4E7XHRvz

This happens overnight and also when I'm running the manual post processing. I have no clue what the reason for it is and sickrage seems to work fine even with this error. I've been getting it since I updated to this commit.

**Comment by fernandog** [comment]
Please use develop branch and report back

**Comment by OmgImAlexis** [comment]
@fernandog I'm running the development branch now and I'll report back in a few days.

**Comment by OmgImAlexis** [comment]
Everything's the same but I'm using the dev branch with commit SiCKRAGETV/SickRage@c62d8f2c799edd7daad5648f45276a3464d83a9e
http://pastebin.com/raw.php?i=dED80f6e

**Comment by fernandog** [comment]
Stop SR. 
Change this file as in here
https://github.com/SiCKRAGETV/SickRage/pull/1247/files
Start SR.
report back

**Comment by OmgImAlexis** [comment]
That seems to have fixed it but I'll leave it overnight(it's 5AM here) and get back to you tomorrow if it's all well.

**Comment by fernandog** [comment]
Did you run manual PP and got no error?

**Comment by OmgImAlexis** [comment]
I ran a manual post-process last night and nothing came up but I just got up and I've got 13 copies of this error so it may not have really fixed much. Usually I get the no len() error 2 - 5 times in a night and I got this one 13 times. http://pastebin.com/raw.php?i=NRZ4LKid

**Comment by fernandog** [comment]
closing it's duplicate. see the other discussions
