### ISSUE TITLE
Improved failure handling

### ISSUE THREAD

**Issue by TehWardy** [SiCKRAGETV/sickrage-issues#529]
When using sickbeard / sickrage combined with sab it would be really helpful if it could automatically try the next item from the results found during nzb searches in the event that sickbeard has a history item showing a fail. 

With torrents  or if sab API does not offer an option to look through the history maybe a timeframe could be specified during which a snatched item is still considered to be actively downloading if it hasn't already been post processed after which the system would consider the download failed and add the next item to the queue.

The biggest issue here is that nzb indexers are not updated when 1 chunk of the entire binary is taken down for whatever reason thus breaking the download.

With torrenting it's easy to see if the whole thing is available on the network newsgroups don't have this luxury.
It may be possible if using torrent providers to automatically remove torrents when there are no connectable seeds left with some deeper torrent client api integration.

**Comment by neoatomic** [comment]
Your request looks similar to https://github.com/SiCKRAGETV/sickrage-issues/issues/52 and https://github.com/SiCKRAGETV/sickrage-issues/issues/225 
So i'm going to close this and link it to those FR's. So we have all in one place.
