### ISSUE TITLE
[Feature Request] Disk space check before move to smb share

### ISSUE THREAD

**Issue by djack42** [SiCKRAGETV/sickrage-issues#530]
SR Version:
BRANCH: (develop)
COMMIT: (c62d8f2c799edd7daad5648f45276a3464d83a9e)
Os : geexbox linux
Python Version:	2.7.1 (r271:86832, Aug 23 2014, 08:54:18) [GCC 4.8.3 20140401 (prerelease)]

When the postprocess move the files to a samba share, if there isn't enough disk space to move the episode, the file is partialy Moved and treated as processed successfully. And nothing tells that the file is truncated until viewing it (the worst annoying way....).

This is wrong, the move should not be done in the first place if there is not enough room and the files should stay in the postprocess folder.
Even better, to be sure everything will be ok, the size of the episode file plus a few MB should be availlable on the share.
A crc check between source and destination could be a good way to ensure that the move operation is done successfully.

**Comment by fernandog** [comment]
@TagForce can we stop PP is target folder/share/hdd don't have enough space? 

today, how SR handle the enough space in PP?

**Comment by TagForce** [comment]
@fernandog Right now it doesn't handle it at all... I'll see if I can check it before a copy or move.

**Comment by fernandog** [comment]
@TagForce do you think it's a good idea ? If not, let it go and we will close this

**Comment by TagForce** [comment]
@fernandog I did a quick search and it doesn't seem too hard to implement for basic systems. It's a good idea to check this is apparently failing to move causes corruptions. It's always a good idea to try to prevent those.

**Comment by neoatomic** [comment]
@fernandog The disk space check was implemented some time ago if i recall correctly.?

**Comment by fernandog** [comment]
AFAIK yes.

Added Free Space check in PP before deleting files 
https://github.com/SiCKRAGETV/SickRage/pull/1629
