### ISSUE TITLE
Unable to save the file: error 2 : No such file or directory

### ISSUE THREAD

**Issue by jrmsuper** [SiCKRAGETV/sickrage-issues#531]
I see this has been previous issue but I have had no success at finding a resolution. I have no idea what to do and it's really frustrating. 

I have SickRage fully installed but when SickRage snatches a torrent it does not send the file to rTorrent to download. I am using SickRage / rTorrent / WhatBox. Do I have to connect with scgi??

2015-02-01 06:43:11 SEARCHQUEUE-MANUAL-161511 :: Unable to save the file: error 2 : No such file or directory

**Comment by abeloin** [comment]
In sickrage, the rtorrent lib is limited to scgi(local) or http(with or without basic auth).

There's currently a [pull request](https://github.com/SiCKRAGETV/SickRage/pull/1244) for the develop branch which add https(basic and digest auth) to the rtorrent branch which should help you if you have httprpc plugin in rutorrent.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/242
