### ISSUE TITLE
Show Count in footer

### ISSUE THREAD

**Issue by markeynz** [SiCKRAGETV/sickrage-issues#532]
HI

The show count in the footer appears to be maxed out at 1024.I think because of this, the number of shows and downloaded shows is also incorrect.

**Comment by abeloin** [comment]
Looking at the code there's nothing indicating a max value:
```
#set $shows_total = len($sickbeard.showList)
```

**Comment by markeynz** [comment]
Hmm, even adding another 3 shows today, and its still sat at 1024.  I know no python but can read a bit of code so will look :)

**Comment by markeynz** [comment]
Error on my behalf, I forgot to include subfolders of my TV dir as separate directories.  So obviously it didnt recurse the folder and pick them up when adding the root folder :)
