### ISSUE TITLE
Episodes are not snatched right away anymore

### ISSUE THREAD

**Issue by tchirou** [SiCKRAGETV/sickrage-issues#534]
Hello

BRANCH: (develop) / COMMIT: (c62d8f2c799edd7daad5648f45276a3464d83a9e)
Python 2.7.6 / Win 8.1
Episodes are not paused, default ep status is "wanted" for all. They appear in the coming episodes list.
Update shows on startup is checked. PC is not 24/7 on but it never was, I did not change its behavior. I am in GMT+1 and shows are displayed in Local timezone.

Until the major december problems and for a whole year, when I started up the PC in the morning, as soon as SR (develop branch) started, wanted episodes aired few hours before were snatched instantly. 

Now, they are snatched dozens of minutes later, if ever. Sometimes I need to restart SR to allow snatching.

Exemple this morning : I started the PC at 8:20am. There was one episode only in the coming episode list : the blacklist. The episode was snatched at 9:26am (more than 1 hour later).
Besides, 5 logs were created, which seems a lot to me for less than 90 minutes of running.

Here is the one with the snatch : https://www.dropbox.com/s/jcra79gabhz05dz/sickrage.log?dl=0
(file too big for pastebin)

Has the search behavior been modified on purpose or is there something buggy ?

Please just don't answer "SR must run 24/7" because as I said, it never did and it used to work like a charm.

Many thanks

**Comment by abeloin** [comment]
What is your dailysearch_frequency value in config.ini?

**Comment by tchirou** [comment]
60min

**Comment by abeloin** [comment]
It explain why it took an hour to find the show as the daily search is run every 60 mins.

Can you try setting "Update shows on startup" in config General->Misc, and see if it helps.

**Comment by tchirou** [comment]
Yeah but when everythong was going well, it tried to snatch on startup because it already knew what was aired the day before
Update shows on startup is already checked.

**Comment by abeloin** [comment]
What is your backlog_startup value in config.ini?

**Comment by tchirou** [comment]
720min

**Comment by abeloin** [comment]
You're sure?

**Comment by tchirou** [comment]
Or 1, I don't know which one you meant.
Daily search is at 1 too

**Comment by tchirou** [comment]
Well I mean I read too fast and gave you the backlog_frequency

**Comment by abeloin** [comment]
Can you make sure both options have a value of 1(you will need to stop sickrage first):
```
dailysearch_startup = 1
backlog_startup = 1
```

**Comment by tchirou** [comment]
Yes they are

**Comment by abeloin** [comment]
ok, can you try with "Update shows on startup" not checked?

**Comment by tchirou** [comment]
To be honest, I noticed the strange behavior a while ago and I tested with ou without before deciding to post an issue
When it worked last year, it was checked.
I am going to unckeck it and we will see tomorrow

**Comment by tchirou** [comment]
So can you tell me if your SR snatches them right away at startup ?
Because I thought for one minute that this might have been changed on purpose.

**Comment by abeloin** [comment]
Yes, it do snatch right away. 

If it doesn't work, I'll need a log from when sickrage start to see what tasks are running.

**Comment by tchirou** [comment]
Alright. I stopped SR and deleted all the logs so it will be fresh clean tomorrow.
Thanks

**Comment by abeloin** [comment]
No need to wait until tomorrow, send me the last file from that restart(e.g.: sickrage.log.1, the one with the biggest number)

**Comment by tchirou** [comment]
To be clear 
do you want the logs from this morning with "update shows on startup" checked the the snatch of the blacklist ?
Or do you want that I start SR now after deleting the log files with "updates show on startup" unchecked ?

**Comment by abeloin** [comment]
Second one, take the log after a minute or 2.

**Comment by tchirou** [comment]
Here you go : http://pastebin.com/Q41f1KrX

**Comment by abeloin** [comment]
Ok good the BACKLOG and SEARCHQUEUE-DAILY-SEARCH are running at the begining of sickrage.
Tomorrow, check in the log after you started sickrage for:
```
BACKLOG :: Seeing if we need anything from State of Affairs
SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from State of Affairs
```

**Comment by tchirou** [comment]
Ok thanks

**Comment by tchirou** [comment]
Hello
So "update shows at startup" disabled.
No snatch at all
Here is the log : http://pastebin.com/xhnW2Gtg
It does not find anything in the daily search nor the backlog search
They are not in the backlog overview either.
In each show page, the episodes are "unaired".

I hope I don't have to set a fresh SR from scratch...

**Comment by benhopperau** [comment]
I seem to be having the same issue. The shows information appears to be out of date where the Airdate is Never and the status is skipped. Then if I check TVDB all of the information is there. I can then run a "Force Full Update" and then all of the episodes are available. At that time it then snatches the missing episodes. Let me know what other information you need.
Branch: master
Commit hash: 401cb666016e45b42fe675bafdf7908ad6c2b9bb
OS: Win 8.1 w python 2.7
Config:
dailysearch_frequency = 300
backlog_frequency = 720
dailysearch_startup = 1
backlog_startup = 1

**Comment by fernandog** [comment]
if you dont run 24/7 you must enable "update shows at startup". Otherwise SR wont change unaired to wanted

**Comment by tchirou** [comment]
Yeah but Alexandre told to test with "update at startup disabled"
It does not work one way or the other

**Comment by benhopperau** [comment]
I do run 24/7 and dont normally have that checked. Although it doesn't appear to make any difference, when I start SR it still doesn't update the shows.

**Comment by tchirou** [comment]
Moreover the daily search snatched the episodes 60 minutes later (dailysearch_frequency = 60)  whereas there was no update between.

**Comment by tchirou** [comment]
I ajust cloned a new develop SR. I configured it from scratch and add the existing shows, so no corrupt db files. I put it on another port.
I will run the new SR tomorrow to test the behavior.

**Comment by tchirou** [comment]
One question though : 

To avoid to have all the previous seasons in the wanted status; I choose "Archived" in the initial status of missing episodes in the "Add show" screen.
So on each show page, the default EP status is "Archived". Which I found a little confusing as to me, it means "I don't want to download the episodes of this show" and has the same function than "Paused".

Maybe it should be renamed to "Status of missing episodes" ?
Or is there something wrong and it uses the same info (status_default) to define the missing episodes status when adding the show and the unaired episodes status?

Do we agree that the unaired episodes would be transformed in "wanted" even though the default ep status is on "Archived" as long as the show is not paused ?

**Comment by tchirou** [comment]
It is all the more confusing as when you edit a show, there is 

`Default Episode Status:
(this will set a default status to be applied to any newly added episodes)`

**Comment by abeloin** [comment]
Yes it will be changed to wanted by the daily searcher.

**Comment by tchirou** [comment]
Ok so we will see

I keep thinking that "Default EP status" in the show page and "Default Episode Status: (this will set a default status to be applied to any newly added episodes)" in the edit show page should be modified as it is really confusing.

**Comment by abeloin** [comment]
@benhopperau Put a sane value in dailysearch_frequency because right now it check for wanted episode every 5 hour. The default is 40

**Comment by abeloin** [comment]
@tchirou Yes I agree with you.

**Comment by abeloin** [comment]
@tchirou Can you patch you SR with [this diff](https://gist.github.com/abeloin/69d6b1609ad794fbaf62)? It add a line to log when the dailysearcher change the status of and episode to wanted.

**Comment by tchirou** [comment]
I just add the whole thing somewhere in dailysearcher.py ?
Sorry, coding is not my strong suit

**Comment by tchirou** [comment]
The green line I mean ?

**Comment by tchirou** [comment]
Do I need to delete dailysearcher.pyc ?

**Comment by abeloin** [comment]
1. Save the file as wanted.diff at the root of sickrage.
2. At the command line:
```
patch -p1 < wanted.diff
```
It should tell you it patched the file successfully.
3. Restart sickrage.

**Comment by tchirou** [comment]
Nope I have an error
Au caractère Ligne:1 : 11
+ patch -p1 < wanted.diff
+           ~
L'opérateur « < » est réservé à une utilisation future
    + CategoryInfo          : ParserError: (:) [], Par
    + FullyQualifiedErrorId : RedirectionNotSupported

**Comment by abeloin** [comment]
Oops my bad, I thought you were on Linux. 
In sickbeard\dailysearcher.py around line 94, paste this before sql_l.append(ep.get_sql()):
```
                logger.log(u"Set status to wanted for " + show.name + ".S" + str(sqlEp["season"]) + "E" + str(sqlEp["episode"]))
```

**Comment by tchirou** [comment]
No worries
Ok done. Do I need to delete dailysearcher.pyc ? I seem to recall it bugged the whole thing when I manually modify the .py

**Comment by tchirou** [comment]
Well I don't know if I made a mistake but when I launch sickbeard.py, pythonw.exe starts and stops immediately.
What git command should I use to repair the ***** I did ?

**Comment by abeloin** [comment]
Make sure your indentation is the same as sql_l.append(ep.get_sql()) for logger.log(u"Set status. Use space no tab
```
            ep = show.getEpisode(int(sqlEp["season"]), int(sqlEp["episode"]))
            with ep.lock:
                if ep.show.paused:
                    ep.status = common.SKIPPED
                else:
                    ep.status = common.WANTED

                logger.log(u"Set status to wanted for " + show.name + ".S" + str(sqlEp["season"]) + "E" + str(sqlEp["episode"]))
                sql_l.append(ep.get_sql())
        else:
            logger.log(u"No new released episodes found ...")
```

**Comment by abeloin** [comment]
If not then:
```
git checkout sickbeard/dailysearcher.py
```
should restore the file

**Comment by tchirou** [comment]
Well I modified it again and it works. Thanks

**Comment by benhopperau** [comment]
Im thinking I might have had a dodgy DB. I tried running a full update on a few shows last night and 3 of them worked but then the 4th just sat there at:
 "INFO     SHOWQUEUE-FORCE-UPDATE :: Loading all episodes from the DB"
 It didn't progress any further after hours. I then restarted SR and removed and tried to re-add the show but it then wouldn't add:
2015-02-03 21:31:05 INFO     SHOWQUEUE-ADD :: theTVDB: {'useZip': True, 'apikey': 'xxxxxxxxx', 'cache': 'C:\\Utils\\SickRage\\cache\\indexers\\theTVDB', 'language': 'en'}

I have now cloned a new copy of the master branch and tried adding the show in there and it works fine. So I'm not sure if the DB is dodgy and that was causing the show updates to fail, hence not getting new show info from TVDB?

This may be a different issue to the OP, do you want me to create a new thread?

**Comment by abeloin** [comment]
@benhopperau Check issue SiCKRAGETV/sickrage-issues#480, maybe related?

**Comment by benhopperau** [comment]
@abeloin thanks, that's exactly what was happening. I believe there are two issues here, but I'm sure if they are related. I didn't actually look to check if there was an issue reported for the "New Shows Stuck Loading". Im not sure if my issue is actually the same as the OP any more, what do you think?

**Comment by abeloin** [comment]
@benhopperau For the airdate is never, that can happen if the show was updated on thetvdb after the full update task was run(every day at 3 am). If it does that to every show then open a new issue

As for the issue "New Shows Stuck Loading", we should continue on the other thread.

**Comment by tchirou** [comment]
Hello

It did not work, much to my surprise as I thought it was my previous install which was messed up.
Snatch occurred 60 minutes after the startup : https://www.dropbox.com/s/pnj20ihaknx32dv/log.txt?dl=0

I am pretty disappointed to have spent time to do a fresh install yesterday :-(

Could it be related to the fact that I am in GMT+1 and with a local timezone ?

**Comment by abeloin** [comment]
@tchirou I don't know for the timezone. Can you try running sickrage(git checkout) with this tree https://github.com/SiCKRAGETV/SickRage/tree/477b0806b0c2b7d0c96186aa51b2e77cdd4b0bd1? It's dated from November 2014, before some changes to the daily searcher and around the time you told its stopped working.

As work around for waiting 60 minutes, you can go to menu Manage->Manage Searches->Force DailySearch.

**Comment by tchirou** [comment]
Hello
Can you give me the command to do that please ?
Thanks

**Comment by tchirou** [comment]
Weirdly enough, I started the computer to do what you suggested but before I do anything (SR is auto started at launch), 6 episodes out of 7 were snatched right waway, except Arrow.
The log : https://www.dropbox.com/s/guz40h84cfdppjs/log2.txt?dl=0
What do you think ?
I am tempted to not touch anything and wait tomorrow.

**Comment by abeloin** [comment]
Ok, sickrage failed to update the timezone:
```
2015-02-05 08:37:20 WARNING  DAILYSEARCHER :: Unknown exception while loading URL https://raw.githubusercontent.com/Prinz23/sb_network_timezones/master/network_timezones.txt
```
then
```
2015-02-05 08:37:20 DEBUG    DAILYSEARCHER :: 281697: An object for episode 1x15 didn't exist in the cache, trying to create it
2015-02-05 08:37:20 DEBUG    DAILYSEARCHER :: 281697: Loading episode details from DB for episode 1x15
2015-02-05 08:37:20 INFO     DAILYSEARCHER :: Set status to wanted for Stalker.S1E15
2015-02-05 08:37:20 DEBUG    DAILYSEARCHER :: 268592: An object for episode 2x11 didn't exist in the cache, trying to create it
2015-02-05 08:37:20 DEBUG    DAILYSEARCHER :: 268592: Loading episode details from DB for episode 2x11
2015-02-05 08:37:20 INFO     DAILYSEARCHER :: Set status to wanted for The 100.S2E11
2015-02-05 08:37:20 DEBUG    DAILYSEARCHER :: 269641: An object for episode 2x13 didn't exist in the cache, trying to create it
2015-02-05 08:37:20 DEBUG    DAILYSEARCHER :: 269641: Loading episode details from DB for episode 2x13
2015-02-05 08:37:20 INFO     DAILYSEARCHER :: Set status to wanted for Chicago P.D..S2E13
2015-02-05 08:37:20 DEBUG    DAILYSEARCHER :: 261690: An object for episode 3x2 didn't exist in the cache, trying to create it
2015-02-05 08:37:20 DEBUG    DAILYSEARCHER :: 261690: Loading episode details from DB for episode 3x2
2015-02-05 08:37:20 INFO     DAILYSEARCHER :: Set status to wanted for The Americans (2013).S3E2
2015-02-05 08:37:20 DEBUG    DAILYSEARCHER :: 257655: An object for episode 3x12 didn't exist in the cache, trying to create it
2015-02-05 08:37:20 DEBUG    DAILYSEARCHER :: 257655: Loading episode details from DB for episode 3x12
2015-02-05 08:37:20 INFO     DAILYSEARCHER :: Set status to wanted for Arrow.S3E12
2015-02-05 08:37:20 DEBUG    DAILYSEARCHER :: 247808: An object for episode 4x12 didn't exist in the cache, trying to create it
2015-02-05 08:37:20 DEBUG    DAILYSEARCHER :: 247808: Loading episode details from DB for episode 4x12
2015-02-05 08:37:20 INFO     DAILYSEARCHER :: Set status to wanted for Suits.S4E12
2015-02-05 08:37:20 DEBUG    DAILYSEARCHER :: 95011: An object for episode 6x13 didn't exist in the cache, trying to create it
2015-02-05 08:37:20 DEBUG    DAILYSEARCHER :: 95011: Loading episode details from DB for episode 6x13
2015-02-05 08:37:20 INFO     DAILYSEARCHER :: Set status to wanted for Modern Family.S6E13
2015-02-05 08:37:20 INFO     DAILYSEARCHER :: No new released episodes found ...
```
I'll check the code for the timezone

**Comment by abeloin** [comment]
@tchirou Can you change the line 52 in sickbeard/dailysearcher.py from:
```
curDate = (datetime.date.today() - datetime.timedelta(days=2)).toordinal()
```
to
```
curDate = (datetime.date.today() + datetime.timedelta(days=2)).toordinal()
```
Then restart sickrage

**Comment by abeloin** [comment]
@tchirou Any news?

**Comment by tchirou** [comment]
Hi
Friday was not good at startup. I modified as you told me Friday afternoon.
Saturday morning was a breeze : 3 snatched out of free. But I am away
skiing this weekend so I can't check the log.
I will report back tomorrow with the Sunday evening shows to check if
there is a good pattern on the way.
Many thanks

**Comment by abeloin** [comment]
Ok, have fun skiing :)

**Comment by tchirou** [comment]
Hello
So far, so good, everything is now snatched right away
Will I need to disable auto update and do a git reset --hard HEAD when the commit is merged ?
Many thanks for your help

**Comment by abeloin** [comment]
No need to disable the auto-update, it will simply fail(with a error in the log).
At that moment stop sickrage and do a git reset --hard, git pull.

**Comment by abeloin** [comment]
@fernandog Pull request SiCKRAGETV/SickRage#1293 resolve the issue.

**Comment by fernandog** [comment]
@tchirou  develop updated. please test and report back

**Comment by tchirou** [comment]
Hello
Reset done but after today's snatching. I will report back tomorrow.
Glad that Alexandre got enough trust to be able to author.

**Comment by tchirou** [comment]
Working nicely 
Thanks everyone

**Comment by rd1** [comment]
i'm having the same problem, none of the episodes i've set up a couple days ago to be aired tonite  have been snatched. on the show page it says aired 4 hours ago and no snatch. just wanted.

i had to do it manually. looking in logs, lots of "findPropers returned a non-proper, report this"

please see log here https://www.dropbox.com/s/pz5xxwilc4g145z/sickrage.log.1?dl=0

**Comment by miigotu** [comment]
@rd1 you have an assload of errors in that log. Your snatching is not working because you have the wrong qnap package installed.

As for the non-propers, it is not an error, just lets you know to tell us. i can fix this:
`WARNING  FINDPROPERS :: [Rarbg] :: findPropers returned a non-proper, we have caught and skipped it but please report this`

**Comment by rd1** [comment]
i downloaded from here https://sickrage.tv/forums/forum/help-support/frequently-asked-questions-faq/1288-frequently-asked-questions-answered

and of course the link for qnap now is down. is there another place to download from?

**Comment by miigotu** [comment]
@rd1 https://github.com/SiCKRAGETV/sickrage-issues/wiki/Sickrage-installation-packages

**Comment by rd1** [comment]
thanks for the link but the app manager on my nas rejected the package , it's the wrong architecture, this is built for the x86 cpu.

the other version installed fine and worked fine up to today. so obvi an update gone out today or yesterday is the cause.

**Comment by rd1** [comment]
reinstalled git python and the Sw app from my link above, things work fine now.

**Comment by miigotu** [comment]
@rd1 try shutting down and removing cache.db

**Comment by rd1** [comment]
ok , cache.db the one in /config right ?

but after shutting it down the question is: how do i restart it after its off ? 

novice here obvi.

**Comment by miigotu** [comment]
yes. you just start it how you normally do ?

**Comment by rd1** [comment]
i`m using the web frontend for the SR app on my qnap, the normal way is just to launch my browser.

but if i shut it down through the SR menu, how will i restart it after ?

**Comment by miigotu** [comment]
go in qnap web ui and start the package.

**Comment by rd1** [comment]
ok in the same way i shut it down, the menu will show up and allow to start. understood.

thank you for the help, i'll proceed and see if future shows start up.

**Comment by rd1** [comment]
no go. i have to click each episode for it to search and download. Something in the code for automated downloads is broken but in manual downloads it works. 

will post this problem at qnap forum, hoping clinton hall will see it and make a new pkg with latest everything.

SR Version:	BRANCH: (master) / COMMIT: (8985c2f3d5376227aa7603cb9aad574f4341ab33)  (updated 10mins ago)
Python Version:	2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]
