### ISSUE TITLE
New shows stuck to loading (same as #480)

### ISSUE THREAD

**Issue by ameic** [SiCKRAGETV/sickrage-issues#535]
BRANCH: Master
COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb)
Operating system: W7 SP1
Python Version:	2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]
What you did: tryed to add new show
What happened: show is stuck at loading and never adds
What you expected: show to be added on list

Hi, I have the exact same issue as Bloom SN, also nothing in logs (debug on). An empty directory is created for the TV Show I add but contains no files

Link to prev issue;
https://github.com/SiCKRAGETV/sickrage-issues/issues/480#issuecomment-71376976

I deleted the SR db and was able to create a new one and added shows over several days, everything worked fine for a week or so, now I am again unable to add shows, they just get stuck at ...loading.

I've tried with 3 different TV shows with various naming structures, some have a few seasons others have lots, reset SR, rebooted PC etc. still no luck.

Not really keen on creating another DB.

Regards,

Gareth.

**Comment by fernandog** [comment]
post full logs in #480

**Comment by ameic** [comment]
Hi, thanks for responding. I had a brain wave and removed all of my shows and eventually it's started working again, so it looks like one or some of the shows is causing trouble. I'll add them all one by one and If I find out which one it is I'll post logs as advised. Cheers.
