### ISSUE TITLE
BUG: Retrying search episode after failing download fails

### ISSUE THREAD

**Issue by Quiptix** [SiCKRAGETV/sickrage-issues#536]
Version SR: BRANCH: (develop) / COMMIT: (c62d8f2c799edd7daad5648f45276a3464d83a9e) 

When a episode fails to download in nzbget and nzbtomedia sends the failed request SR doesn't search for a next possible download. I can discover this log message which seems related to the issue.

```
2015-02-02 19:10:39 DEBUG    SEARCHQUEUE-RETRY-269578 :: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/search_queue.py", line 253, in run
    for epObj in self.segment:
TypeError: 'TVEpisode' object is not iterable
```

NAS: QNAP 
OS: Linux QNAP 3.4.6 #1 SMP Sat Nov 1 09:17:08 CST 2014 x86_64 unknown
Python: 2.7.3 (default, Apr 12 2012, 20:25:04) [GCC 4.2.1]

**Comment by abeloin** [comment]
You'll need to provide a more complete log of the issue.
* Complete log from sickrage with debug=1 in the config file.
* Complete log from nzbtomedia with log_debug = 1 in autoProcessMedia.cfg

**Comment by Quiptix** [comment]
Will do this this weekend

**Comment by Quiptix** [comment]
Please find the logs in PasteBin:
http://pastebin.com/0tdcqqAf 
http://pastebin.com/Ef95W7YV 

I see more iteration errors before the actual error, probably when clicking through the GUI.

**Comment by abeloin** [comment]
Related to #527

**Comment by abeloin** [comment]
Can you try this commit https://github.com/TagForce/SickRage/commit/eedb42085b2d64a2f0aa51d269dff1fff11c4984?

**Comment by Quiptix** [comment]
I'm a bit rusty on Git commands. How do I do that?

**Comment by abeloin** [comment]
* Download: https://github.com/TagForce/SickRage/commit/eedb42085b2d64a2f0aa51d269dff1fff11c4984.patch
* Command line: ```git am eedb42085b2d64a2f0aa51d269dff1fff11c4984.patch```

**Comment by brando56894** [comment]
I have the same error on FreeBSD (FreeNAS) 9.3, I applied that patch but it didn't fix the error.

error log: http://pastebin.com/vMz6gvBg

**Comment by abeloin** [comment]
@brando56894 Not exactly the same. Revert the patch you just applied.

Can you revert [this pull request](https://github.com/SiCKRAGETV/SickRage/pull/1258/) that was merged into develop on your copy, restart sickrage and try again

**Comment by Quiptix** [comment]
Unfortunately I get another or as far I can tell the same error with the included patch:
```
2015-02-08 15:09:03 Thread-64 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/webserve.py", line 1857, in getManualSearchStatus
    if not [i for i, j in zip(searchThread.segment[0], episodes) if i.indexerid == j['episodeindexid']]:
TypeError: 'TVEpisode' object does not support indexing
```

**Comment by Quiptix** [comment]
How to I reverse the patch, because it seems that no episodes at all are found by clicking on the hourglass.

**Comment by abeloin** [comment]
git reset --hard HEAD^

**Comment by abeloin** [comment]
@Quiptix Can you try revert applying this pull request:
* Dowload: https://github.com/SiCKRAGETV/SickRage/pull/1258.diff
* Command line: ``` git apply -R 1258.diff ```
* Restart sickrage and try again?

**Comment by Quiptix** [comment]
@abeloin Is this possibly a fix for the problem, or only for reverting the previous attempt?

**Comment by abeloin** [comment]
@Quiptix A change(PR 1258) was introduce in the last develop branch merge which I think could be related to the issue. I want to see if the issue was introduce by that pull request.

**Comment by Quiptix** [comment]
It is already failing in the receiving call from nzbToMedia:
On line 253 of search_queue.py . So it looks more related to the first attempt, however nog sure whether multiple episodes could by handled in one single call.
Very important: The episode is never marker as bad/failed, which is one af the very first things that is done when such a call is received.
I understand what you are saying. My Python skills are also very rusty (just like Git), however I'm getting a hang to it again...
Since a very recent development commit this must be introduced.

**Comment by abeloin** [comment]
Ok so PR1258 didn't help. ```git reset --hard HEAD``` should revert everything to develop.

Can you try the branch before all the changes from 10 days ago:
* Make sure 'Automatically update' is uncheck in config->general.
* Stop Sickrage.
* Run the following command in sickrage root:
```git checkout 91cb8d885ca278e5829ed53d856d578c8ee8cbe0```
* Start sickrage.
* Test again

**Comment by Quiptix** [comment]
Ik have looked at the diff and applied it, however that change was already in the develop HEAD.
Luckily I can read the code quite happily. It seems that somebody already acknowledged that the segment was no list and parsed the Episode, which then it iterated again, which cannot be done as it was no list parsed at all.

Ik will revert back to 10 days again and test again!

**Comment by abeloin** [comment]
Ok but I wanted you to revert those changes in [this comment](https://github.com/SiCKRAGETV/sickrage-issues/issues/536#issuecomment-73414192) that why I put the -R switch.

In develop currently:
```
cur_failed_queue_item = search_queue.FailedQueueItem(parsed.show, segment)
```
after reverting the patch:
```
cur_failed_queue_item = search_queue.FailedQueueItem(parsed.show, [segment])
```
Anyhow it will be reverted with the git checkout 91cb8d885ca278e5829ed53d856d578c8ee8cbe0

**Comment by Quiptix** [comment]
With the branch reverting 10 days back, it works again. 
I noticed that I forgot the -R in your statement with the patch.
I can try that again if needed.

**Comment by abeloin** [comment]
Yes:
* Stop sickrage
* Go back to develop: ```git checkout develop```
* Apply the revert diff: ```git apply -R 1258.diff``` (Don't forget the -R ;) )
* Start sickrage
* test again

**Comment by Quiptix** [comment]
I probably owe you an apology ...
I restarted SR with my init.d script which does a hard reset to HEAD. So I'm not sure that my very first attempt with git am was a goed try, so I'm going to do that one again!!! Working my way back to where we are...

**Comment by abeloin** [comment]
No worries, everybody has the right to learn.

For TagForce/SickRage@eedb420 no need as brando56894 tried it yesterday and it didn't work.

Try the PR1258

**Comment by Quiptix** [comment]
```
2015-02-08 22:27:52 DEBUG    Thread-43 :: 250487: An object for episode 1x1 didn't exist in the cache, trying to create it
2015-02-08 22:27:52 DEBUG    Thread-43 :: 250487: Loading episode details from DB for episode 1x1
2015-02-08 22:27:52 ERROR    Thread-29 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/webserve.py", line 1834, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/webserve.py", line 1819, in getEpisodes
    for epObj in searchThread.segment[0]:
TypeError: 'TVEpisode' object is not iterable
Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/webserve.py", line 1834, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/webserve.py", line 1819, in getEpisodes
    for epObj in searchThread.segment[0]:
TypeError: 'TVEpisode' object is not iterable
2015-02-08 22:27:52 ERROR    Uncaught exception GET /home/getManualSearchStatus?show=250487 (192.168.202.146)
HTTPServerRequest(protocol='http', host='192.168.202.6:7073', method='GET', uri='/home/getManualSearchStatus?show=250487', version='HTTP/1.1', remote_ip='192.168.202.146', headers={'Accept-Language': 'nl-nl', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.202.6:7073', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://192.168.202.6:7073/home/displayShow?show=250487', 'Cookie': '_ga=GA1.1.2126292986.1420496990; advanced_toggle_checked=1; compact_display_state=false; dsAgreeLaw=1; filter=all; late_view2=list; manage_view2=list; snatched_view2=list; soon_view2=thumbs; suggestions_charts_menu_selected=suggestions; wanted_view2=list'})
Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/tornado/web.py", line 1292, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/tornado/stack_context.py", line 314, in wrapped
    ret = fn(*args, **kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/tornado/concurrent.py", line 226, in <lambda>
    lambda future: callback(future.result()))
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/lib/concurrent/futures/_base.py", line 400, in result
    return self.__get_result()
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/lib/concurrent/futures/_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/lib/concurrent/futures/_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/lib/concurrent/futures/thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/webserve.py", line 1834, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/webserve.py", line 1819, in getEpisodes
    for epObj in searchThread.segment[0]:
TypeError: 'TVEpisode' object is not iterable
2015-02-08 22:27:53 DEBUG    SEARCHQUEUE-RETRY-250487 :: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/search_queue.py", line 253, in run
    for epObj in self.segment[0]:
TypeError: 'TVEpisode' object is not iterable
```
Oke, then I double confirmed it...

Next step the reversed patch

**Comment by Quiptix** [comment]
The reversed patch gives back to lost functionality.
Automatic processing of failed downloads as manually marked failed episodes works as advertised. And no extra error messages. So it seems that patch 1258 needs to be reverted

**Comment by abeloin** [comment]
Thank for your patience in debugging this issue. Leave the change in place until the branch develop is updated.

**Comment by Quiptix** [comment]
I will... Also thanks to you...
(Also nice to dust off my git and python skills)

(I should be programming again)

**Comment by abeloin** [comment]
@TagForce @fernandog Pull request SiCKRAGETV/SickRage#1258 caused this issue, so it's no good. Also think it's releated to issue #527

**Comment by TagForce** [comment]
@abeloin I'm not seeing this error... Is it only when using nzbtomedia? Reverting this PR would break the failed search with other TypeError messages again, so I'd rather fix this one issue with zip expecting an iterable argument. This could simply be done by checking if segment is a list, and if not, make it a list. However, when I run through the code, segment should always be a list of episodes, even if it's just one.

Strange though, that I do not see any of these errors. I'm not using nzbtomedia, so maybe that's it.

I think it may be solved by changing line 70 in failedProcessor.py to 
cur_failed_queue_item = search_queue.FailedQueueItem(parsed.show, [segment])

segment = parsed.show.getEpisode(parsed.season_number, episode) would make segment an EpObj, and not a list. Passing it as a list to FailedQueueItem would cause segment[0] to be the epObj which zip expects.

**Comment by Quiptix** [comment]
@TagForce 
The problem occurs with nzbToMedia AND manual marking the episode as failed. So I would not point to nzbToMedia.
You can also reproduce this when marking a episode as failed/bad manually in the GUI. For the test (and now time being) I have reverted 1258, so line 70 tells what you are suggesting. Every other development is still in my SR
Which other TypeError were supposed to be fixed with this fix? Maybe I can be of any help here?

At the moment I do not experience any error on searching and retrying fails (manually or automatically)

**Comment by TagForce** [comment]
@Quiptix https://github.com/SiCKRAGETV/sickrage-issues/issues/499
But I think that particular error is caused only by one erroneous pass-as-a-list, rather than the 2 I changed. I think the one in failedProcessor.py should be reverted, but the one in webserve.py is correct.
The one in failedProcessor now passes a failed episode object as a single episode object, while the underlying functions expect a list. The one in webserve.py now passes an episode list, rather than a list of episode lists.

Strange thing is that I do not see these errors. I did see the list type has no attribute 'prettyName' errors which are now gone.

**Comment by abeloin** [comment]
@TagForce Here's the call nzbtomedia make to sickrage which caused the error from Quiptix log:
```
2015-02-07 22:58:35 DEBUG   ::SICKBEARD: Opening URL: http://localhost:7073/home/postprocess/processEpisode with params: {'nzbName': 'American.Horror.Story.S01E01.720p.WEB-DL.H.264-NERDS', 'quiet': 1, 'failed': 1, 'process_method': 'move', 'dir': '/share/Download/nzbget/dst/tv/American.Horror.Story.S01E01.720p.WEB-DL.H.264-NERDS'}
```
I must admit that, yesterday, I didn't check for the cause of the issue further other than PR1258 being the culprit.

**Comment by Quiptix** [comment]
On which event the code in web serve.py is called? When doing a multiple mark and not a single bad mark?
I could test a partial revert of the solution of 1258, if needed.
Only by reading the code I can agree with @TagForce

**Comment by abeloin** [comment]
@Quiptix You should try it and let us know of the results

**Comment by Quiptix** [comment]
I have tested it with a partial revert of 1258. I manually removed the [] in webserve.py . This code is indeed when marking multiple episodes as failed in the GUI. With brackets I get an error and not de desired behavior. Without the brackets functionality is normal.

I left the reverted patch 1258 in failedProcessor.py and that seems to work fine still. So IMHO 1258 only needs to be reverted on webserve.py

**Comment by abeloin** [comment]
Good

**Comment by brando56894** [comment]
Reverting that fixed my error

**Comment by TagForce** [comment]
@Quiptix @brando56894 @abeloin 
Can you guys check if commiting this PR from the current develop develop branch fixes the problems?

https://github.com/SiCKRAGETV/SickRage/pull/1292

It reverts the changes to failedProcessor.py which should, in theory, fix the issues with single failed episodes.

Thanks for pointing this out.

**Comment by Quiptix** [comment]
I will later this evening.

Vincent van Wichen

2015-02-10 10:08 GMT+01:00 TagForce <notifications@github.com>:

**Comment by Quiptix** [comment]
I have tested this quite thoroughly.
It works as advertised!
IMHO merge it with the development HEAD.

**Comment by TagForce** [comment]
We'll have to wait for echel0n to merge the PRs.

**Comment by freddyfinn** [comment]
I can also confirm this is now working.

**Comment by fernandog** [comment]
@Quiptix develop updated. please test and report back

**Comment by Quiptix** [comment]
Just updated and tested. Verdict: OK !!
