### ISSUE TITLE
Scene Exceptions not picked up in search url

### ISSUE THREAD

**Issue by ee0u4179** [SiCKRAGETV/sickrage-issues#538]
Python 2.7.3 (default, Feb 1 2015, 17:42:35) [GCC 4.9.2]
Openelec 5.0
Lenovo Q190

I'm using the version of Sickrage that is included with Audo.

Scene exceptions don't seem to be picked up in dognzb search url (hence returning no results).

Show name - Air Crash Investigation - Mayday

Scene Exception - Air Crash Investigation

Search url = Search url: https://api.dognzb.cr/api?apikey=&season=13&maxage=2100&cat=5030%2C5040&q=Air.Crash.Investigation.Mayday&limit=100&attrs=rageid&offset=0&ep=5&t=tvsearch

So no results found.

Pastebin link:

http://pastebin.com/y1WBK91h

**Comment by fernandog** [comment]
Commit hash?
localhost:8081/config

**Comment by ee0u4179** [comment]
BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb)

**Comment by fernandog** [comment]
@ee0u4179 send a print of this tv-show in the dognzb? How is the full name on it?
