### ISSUE TITLE
Unpack during post-processing leaves files behind

### ISSUE THREAD

**Issue by rflagler** [SiCKRAGETV/sickrage-issues#539]
In post-processing, most people will leave torrents to seed and therefore set "Process Episode Method" to copy; however, if you have a torrent that is compressed, the unpack method will extract the episode within the torrent directory and then copy it to the final destination. This leaves files behind that never get cleaned up without manual intervention.

I feel like there should be 2 "Process Episode Method" settings. 1 for "packed" episodes and 1 for "non-packed" episodes.

**Comment by agentq15** [comment]
+1 
Really need this too. Annoying to have to keep track of what has been downloaded for a manual clean up later.

**Comment by abeloin** [comment]
@rflagler @agentq15 Can you try this pull request https://github.com/SiCKRAGETV/SickRage/pull/1327 ?

**Comment by rflagler** [comment]
@abeloin I'll try to test it out. I'm pretty new to git so I'm trying to figure out how to switch from the master branch to the dev with this specific pull request. I'll let you know once I've figured that out and have tested this.

**Comment by agentq15** [comment]
I tried to change to developer branch in the settings but the option didn't show up.
Maybe that's not the way to test it.

**Comment by rflagler** [comment]
@agentq15 Here's what I had to do. (I'm on Ubuntu and was using the master, or I think I was, the webpage doesn't seem to show your branch accurately)

I had it cloned in /opt/SickRage and did the following
service sickbeard stop
mv /opt/SickRage /opt/SickRage_master
git clone -b develop git://github.com/echel0n/SickRage.git
cd /opt/SickRage
git fetch origin refs/pull/1327/head:pull_1327
git checkout pull_1327
service sickbeard start

And that did it for me. In the options I had the ability to select "Delete RAR Contents". I'm just waiting for something to pull down tonight so I can see if it actually works.

**Comment by agentq15** [comment]
@rflagler my installation is on my seedbox so can't really control it that way.
Can't you just do a manual post process on something you already downloaded to test?

**Comment by abeloin** [comment]
@agentq15 
* Download the PR: https://github.com/SiCKRAGETV/SickRage/pull/1327.diff
* Stop sickrage
*In sickrage folder in a commanline:
```patch -p1 < 1327.diff```
* Start sickrage

**Comment by abeloin** [comment]
@agentq15 Without adding the pull request you will have to wait until it is merged in develop.

**Comment by rflagler** [comment]
@agentq15 I'd rather test is in the exact manner that I'd use it to validate that it works as expected.

**Comment by agentq15** [comment]
@abeloin Okey so I did what you told me over ssh and got this error after
Error

cannot find 'DELRARCONTENTS' while searching for 'sickbeard.DELRARCONTENTS'

**Comment by abeloin** [comment]
@agentq15 I need more context to that error line. Where did it happen?

**Comment by agentq15** [comment]
@abeloin Just pressed post processing in the settings menu and it showed a white error screen.

**Comment by abeloin** [comment]
@agentq15 There's only that line on that page, anything else?
If nothing else on the page can you check your log file for the relevant error and send it via pastebin?

**Comment by agentq15** [comment]
@abeloin Here is what's on the white page http://pastebin.com/Q54MBvDP

**Comment by abeloin** [comment]
@agentq15 Did you restart sickrage?

**Comment by agentq15** [comment]
@abeloin nope but did now and that fixed it. I see theDelete RAR contents button now :)

**Comment by agentq15** [comment]
@abeloin So it deletes the file but it does it before it is moved so the move fails.

**Comment by abeloin** [comment]
@agentq15 Can you provide the error from log as it contain more info?

**Comment by agentq15** [comment]
@abeloin Sure, log on debug: http://pastebin.com/cjWFYVKQ
It deletes the file before moving.

**Comment by abeloin** [comment]
@TagForce Can you check this error, it look like the files are deleted before it is copied?

**Comment by TagForce** [comment]
@agentq15 @abeloin 
In ProcessTV.py
move line 181 down to after the for videos... loop so that it reads:

```elif sickbeard.DELRARCONTENTS and videoInRar:```
```result.result = process_media(path, videoInRar, nzbName, process_method, force, is_priority, result)```
```for video in set(videoFiles) - set(videoInRar):```
```result.result = process_media(path, [video], nzbName, process_method, force, is_priority, result)```
```delete_files(path, rarContent, result)```

That's the only thing I can think of atm. Tested it this afternoon and went fine. Mine went through the subfolder loop though. Above is the only difference between those two loops.

**Comment by TagForce** [comment]
@agentq15 uhmmm...
What folder are you trying to post process and where should it copy the file?
It looks like you're trying to post process a root folder of the destination folder.
It's trying to replace the existing videofile in the destination folder with the one it just unpacked.
But both files are at the same location. So deleting the destination file actually deletes the file it just unpacked.

**Comment by agentq15** [comment]
@TagForce No the destination folder is not a root folder. The destination folder is named "unpacked" where every show is supposed to go after unpacking. Then it's automatically downloaded from there to my server at home.

**Comment by TagForce** [comment]
@agentq15 but is the destination folder a subfolder of the folder you're post processing?
From you logs it seems like it.
Pp folder ./downloads/
Destination folder ./downloads/unpacked/
It's deleting the file from a normal pp function that hasn't changed.

**Comment by TagForce** [comment]
@abeloin @fernandog https://github.com/SiCKRAGETV/sickrage-issues/issues/627

issue exists before applying the PR.
@agentq15 what post process settings do you use?

**Comment by agentq15** [comment]
@TagForce All downloads gets downloaded to /downloads/<show-name>/files.rar and are unpacked to /downloads/unpacked/

I use the Copy setting if that's what you mean? No renaming of files.

**Comment by rflagler** [comment]
@abeloin @TagForce This worked as expected for me. Thanks guys!

**Comment by agentq15** [comment]
@TagForce It works with normal automatic Pp but not the manual which was what I tried before.
Thanks for the help!

**Comment by abeloin** [comment]
@TagForce Manual PP use a different path in the code?

**Comment by abeloin** [comment]
@TagForce

**Comment by TagForce** [comment]
@abeloin @agentq15 Sorry, away for the weekend (unexpectedly).
No, both Automatic and Manual Postprocessing execute the ProcessDir function in ProcessTV.py.

I tested it with manual PP, and it worked for me.

**Comment by abeloin** [comment]
@TagForce So I can merge the PR?

**Comment by TagForce** [comment]
@abeloin Yes... But you already did :) Where are you at? Because I was deep asleep 14 hours ago.

**Comment by abeloin** [comment]
@TagForce Canada

**Comment by TagForce** [comment]
That explains a lot... Shouldn't you be asleep now?

**Comment by abeloin** [comment]
It's 6:40 in the morning :)

**Comment by fernandog** [comment]
Just left my wife and kid at work/school. good morning! =)

**Comment by fernandog** [comment]
@rflagler please update and report back. fix was merged into develop

**Comment by froxic** [comment]
Hi any update to initial request? Im asking since im Asustor NAS user, and I dont have option to switch to delevop branch. After the file is extracted and copied to destination, it also stays in directory where it was extracted. And I must manually delete it.

So any ETA for adding this feature into master branch? Thank you for info!
