### ISSUE TITLE
Feature Request: Add to Trakt.tv Collection

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#54]
<a href="https://github.com/Lynx2504"><img src="https://avatars.githubusercontent.com/u/5137829?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Lynx2504](https://github.com/Lynx2504)**
_Monday Dec 08, 2014 at 12:54 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/1050 (6 comment(s))_

----

As requested in forum thread (https://sickrage.tv/forums/forum/main-category/feature-requests/14234-trakt-tv-notifications-add-to-collection?_=1418041624918), I would like to see some functionality which adds a downloaded episode to your Trakt.tv collection (see: http://trakt.tv/user/{username}/library/shows/collection). 
This way you can see which episodes are ready to watch directly from Trakt.tv (or any app which uses Trakt, I personally use SeriesGuide for Android). 

I have some experience with the Trakt.tv api and I think it should be possible using: https://trakt.tv/api-docs/show-episode-library. A checkbox to enable this option could be added to the Notifications > Social > Trakt.

If anyone needs any more information, just let me know.

Thanks!

**Comment by fernandog** [comment]
@LinuxBozo  is this working with that commits of TRAKT 2.0?

**Comment by LinuxBozo** [comment]
@fernandog Yep. The code that does it is here: https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/notifiers/trakt.py#L42
