### ISSUE TITLE
Unable to find show ID:XXXXX on Indexer: TVRage

### ISSUE THREAD

**Issue by SoWhy** [SiCKRAGETV/sickrage-issues#541]
When I try to add new currently in-development shows (namely "Dr. Ken" and "The King of 7B") which exist on TVRage, SickRage will find them but fails to add them to the database with

> ERROR    SHOWQUEUE-ADD :: Unable to find show ID:47575 on Indexer: TVRage
> ERROR    SHOWQUEUE-ADD :: Unable to find show ID:37966 on Indexer: TVRage

the only information in the log (even with debug = 1 set).

I checked the API manually and you can get results (e. g. using http://services.tvrage.com/feeds/episode_list.php?sid=47575). 

I redownloaded the whole repo and restarted, switched from master to dev and back, but nothing changed.

BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb) 
running on Debian 3.13.7 with Python 2.7.8

**Comment by abeloin** [comment]
This [pull request](SiCKRAGETV/SickRage#1285)(for the develop branch) will give you clearer information on why, both shows, aren't added to sickrage. The pull request will eventually be merged into the master branch.

In this case, here's the result for both shows after applying the pull request:
```ERROR    SHOWQUEUE-ADD :: Show Dr. Ken is on TVRage but contains no season/episode data.```
```ERROR    SHOWQUEUE-ADD :: Show The King of 7B is on TVRage but contains no season/episode data.```

**Comment by SoWhy** [comment]
That is a good improvement to the logging system. Nevertheless, it raises the question why I can't add shows that have no episode data (yet). I like to have them so SR automatically downloads stuff once it exists

**Comment by fernandog** [comment]
Nice!!!

**Comment by abeloin** [comment]
@SoWhy My guess is sickrage/sickbeard was built assuming all shows must have a season/episode. Changing it could be a challenging task if it's the case.

@fernandog Applied also to tvdb as I managed to find a [show on tvdb](http://thetvdb.com/?tab=series&id=283086&lid=7) with no episode.

**Comment by fernandog** [comment]
@SoWhy develop updated. please test and report back.

**Comment by SoWhy** [comment]
Checked it. The error messages appear as you said.
