### ISSUE TITLE
[Feature Request] Add Twitter notification

### ISSUE THREAD

**Issue by dejh0n** [SiCKRAGETV/sickrage-issues#542]
Hi, I'd like to request that SickRage get direct message support in twitter.

I know SickBeard has this function already as I have used it before switching to SickRage.

I managed to change the twitter prefix in the config.ini file as described in the comments on this page: http://smithjw.squarespace.com/journal/2011/11/12/getting-sick-beard-to-reply-you-on-twitter.html

**Comment by MGaetan89** [comment]
It's already available:
<img width="980" alt="Twitter notifications" src="https://cloud.githubusercontent.com/assets/1009664/8580420/d81dee68-25ba-11e5-9369-101ae83ced60.png">

**Comment by dejh0n** [comment]
No it's not available: I have asked for DM posting. Maybe read the feature request correctly before you comment

Deon Nothnagel

**Comment by MGaetan89** [comment]
I'm just trying to help here. No need to attack ...

What do you mean by DM? The existing feature send you a notification on Twitter on snatch/download/subtitle download.

**Comment by neoatomic** [comment]
@dejh0n Made the same error reading your FR. 
Direct messages are private messages in Twitter. Correct.?

**Comment by dejh0n** [comment]
Yes, correct. 

As linked is the article on how to add the function in SickBeard you can also DM (direct message) yourself. 

You can also DM yourself in couch potato which I also use. 

Dejh0n

**Comment by MGaetan89** [comment]
I think that's what @dejh0n is talking about https://dev.twitter.com/rest/reference/post/direct_messages/new

It could be a new option in the Twitter configuration to switch between DM and Tweets.

@dejh0n the article does not exist anymore.

**Comment by WebSpider** [comment]
Added in develop branch.
