### ISSUE TITLE
Post Processing Error

### ISSUE THREAD

**Issue by silentknight509** [SiCKRAGETV/sickrage-issues#543]
When i run a manual post process, I get the following error. I run this, because not all of the shows in my /torrents/data/ directory seem to processing into my /media/TV Shows folder. 

I have looked, and believe all the settings are correct. 

Processing folder */torrents/data
TV_DOWNLOAD_DIR: */torrents/data
Trying to use folder */torrents/data/data
Unable to figure out what folder to process. If your downloader and SickRage aren't on the same PC make sure you fill out your TV download dir in the config.

**Comment by abeloin** [comment]
@silentknight509 First see this link for submitting a ticket: https://github.com/SiCKRAGETV/sickrage-issues

Secondly, why are you using * in your path, it's a wildcard?

**Comment by fernandog** [comment]
@silentknight509 when reply, will reopen.
