### ISSUE TITLE
Previously downloaded torrents not getting re-downloaded

### ISSUE THREAD

**Issue by gazzer82** [SiCKRAGETV/sickrage-issues#544]
Hi,

I have sickrage setup with rtorrent on whatbox. Due to a corruption of the database i had to remove my sickrage install and start again.

In the process of resolving the issues i manually removes some torrents from rutorrent. Now when i re-add those tv shows to sickrage, it shows them as wanted but they never appear in rutorrent and i never get a notification that they have been snatched.

I assume something is cached somewhere and either rtorrent or sickrage thinks it has already been downloaded, but i can't find anything anywhere on the server. The only cached torrent files i can see in the hidden rtorrent folders are the ones that are actually still valid and seeding, nothing for the ones that where manually removed.

Any ideas what i can do to clear the blockage?

Thanks

Gareth

BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb)

ruTorrent - v3.6

**Comment by gazzer82** [comment]
Python version - 2.7.9 (default, Dec 28 2014, 22:25:30) [GCC 4.7.3]

**Comment by abeloin** [comment]
Need some log of when an episode is being snatched to rutorrent.  See the following link on how to activate debug log: https://github.com/SiCKRAGETV/sickrage-issues

Also currently rtorrent in sickrage only support scgi:// and http:// protocol only.

**Comment by fernandog** [comment]
@gazzer82 when reply, will reopen
