### ISSUE TITLE
Post Processing Issues with Special Chracters

### ISSUE THREAD

**Issue by tconkle** [SiCKRAGETV/sickrage-issues#546]
I am running Sickrage on Ubuntu 14.04/

SR Version:	BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb) 
SR Config file:	/opt/sickrage/config.ini
SR Database file:	/opt/sickrage/sickbeard.db
SR Cache Dir:	/opt/sickrage/cache
SR Arguments:	[]
SR Web Root:	
Python Version:	2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]

When i run a Post Processing on the episodes of Pokemon I get an error and it bombs out.  

Here is the log:

2015-02-03 18:54:23 Thread-78 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1994, in processEpisode
    is_priority=is_priority, failed=failed, type=type)
  File "/opt/sickrage/sickbeard/processTV.py", line 180, in processDir
    process_result = process_media(path, [video], nzbName, process_method, force, is_priority)
  File "/opt/sickrage/sickbeard/processTV.py", line 407, in process_media
    process_result = processor.process()
  File "/opt/sickrage/sickbeard/postProcessor.py", line 1001, in process
    cur_ep.airdateModifyStamp()
  File "/opt/sickrage/sickbeard/tv.py", line 2495, in airdateModifyStamp
    filemtime = datetime.datetime.fromtimestamp(os.path.getmtime(self.location))
  File "/usr/lib/python2.7/genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 29: ordinal not in range(128)

How can I get around this?  I really don;t want to manually rename all 800+ files.

Thanks in advanced,

Todd...

**Comment by abeloin** [comment]
Make sure your system use UFT8 to avoid encoding issue, see:
https://sickrage.tv/forums/forum/help-support/general-support/12825-ensuring-your-locale-s-are-set-properly-to-avoid-unicode-issues

**Comment by tconkle** [comment]
I just ran a manual Post Processing on the 2nd season of Nashville and the issue seems to still be happening.  

It looks like anything with an apostrophe (i.e "You’re No Angel Yourself") is showing up as  "Nashville S02E04 Youâ€™re No Angel Yourself.mp4".  

I've ran through the steps in the referenced forum post and even rebooted to no avail.  

Any thoughts would be greatly appreciated.  I really hate manually renaming these.

Thanks 

Todd...

**Comment by fernandog** [comment]
@tconkle linux?

SSH and post the result of

```
 locale
```

you should see something like this:

```
~$ locale
LANG=pt_BR.utf8
LANGUAGE=pt_BR.ISO-8859-1
LC_CTYPE="pt_BR.utf8"
LC_NUMERIC="pt_BR.utf8"
LC_TIME="pt_BR.utf8"
LC_COLLATE="pt_BR.utf8"
LC_MONETARY="pt_BR.utf8"
LC_MESSAGES="pt_BR.utf8"
LC_PAPER="pt_BR.utf8"
LC_NAME="pt_BR.utf8"
LC_ADDRESS="pt_BR.utf8"
LC_TELEPHONE="pt_BR.utf8"
LC_MEASUREMENT="pt_BR.utf8"
LC_IDENTIFICATION="pt_BR.utf8"
LC_ALL=pt_BR.utf8
```

**Comment by tconkle** [comment]
Yep Linux.

LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8

This is my result.  I'm not seeing anything that sticks out.

Todd...

On Thu, Feb 12, 2015 at 11:44 AM, Fernando <notifications@github.com> wrote:

> @tconkle <https://github.com/tconkle> linux?
>
> SSH and post the result of
>
>  locale
>
> you should see something like this:
>
> ~$ locale
> LANG=pt_BR.utf8
> LANGUAGE=pt_BR.ISO-8859-1
> LC_CTYPE="pt_BR.utf8"
> LC_NUMERIC="pt_BR.utf8"
> LC_TIME="pt_BR.utf8"
> LC_COLLATE="pt_BR.utf8"
> LC_MONETARY="pt_BR.utf8"
> LC_MESSAGES="pt_BR.utf8"
> LC_PAPER="pt_BR.utf8"
> LC_NAME="pt_BR.utf8"
> LC_ADDRESS="pt_BR.utf8"
> LC_TELEPHONE="pt_BR.utf8"
> LC_MEASUREMENT="pt_BR.utf8"
> LC_IDENTIFICATION="pt_BR.utf8"
> LC_ALL=pt_BR.utf8
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/546#issuecomment-74105016>
> .
>



-- 


Todd Conkle
LinkedIn Profile <http://www.linkedin.com/in/conkle>

**Comment by fernandog** [comment]
@Tagforce have you seen this happen even with UTF-8?

**Comment by TagForce** [comment]
Personally no. Apostrophe's seem to be handled correctly here.

**Comment by abeloin** [comment]
@tconkle Have you tried as the user running sickrage?

**Comment by fernandog** [comment]
@Abeloin this locale could be different from user to user? did'nt know that.
so he should check the locale of the user set in /etc/default/sickrage or sickbeard?

**Comment by abeloin** [comment]
Yes, local can be set globally then overridden locally(user). E.g.: System locale is Posix and user is en_US.UTF-8

**Comment by tconkle** [comment]
I've checked in /etc/default/sickbeard

SB_USER=todd
SB_HOME=/home/todd/sickrage/
SB_DATA=/home/todd/sickrage/
SB_OPTS=–config=/home/todd/sickrage/config.ini

That is my user account

On Thu, Feb 12, 2015 at 1:48 PM, Alexandre Beloin <notifications@github.com>
wrote:

> Yes, local can be set globally then overridden locally(user). E.g.: System
> locale is Posix and user is en_US.UTF-8
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/546#issuecomment-74127970>
> .
>



-- 


Todd Conkle
LinkedIn Profile <http://www.linkedin.com/in/conkle>

**Comment by abeloin** [comment]
@tconkle Can you try disabling "Change File Date" in the post process config and try again?

**Comment by tconkle** [comment]
That worked.  It's not bombing out but it's still doing weird things with
the apostrophe.  "Nashville S02E04 Youâ€™re No Angel Yourself.mp4"

SO it sounds like it's when it's trying to set the date on the file it
bombs because of the odd characters.

On Thu, Feb 12, 2015 at 4:26 PM, Alexandre Beloin <notifications@github.com>
wrote:

> @tconkle <https://github.com/tconkle> Can you try disabling "Change File
> Date" in the post process config and try again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/546#issuecomment-74156143>
> .
>



-- 


Todd Conkle
LinkedIn Profile <http://www.linkedin.com/in/conkle>

**Comment by abeloin** [comment]
"Nashville S02E04 Youâ€™re No Angel Yourself.mp4" is how he write it in the file system?

What is the file system where you save that episode? ext4, smb, xfs, ...

**Comment by tconkle** [comment]
It's ext4.

On Thu, Feb 12, 2015 at 6:26 PM, Alexandre Beloin <notifications@github.com>
wrote:

> "Nashville S02E04 Youâ€™re No Angel Yourself.mp4" is how he write it in
> the file system?
>
> What is the file system where you save that episode? ext4, smb, xfs, ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/546#issuecomment-74175825>
> .
>



-- 


Todd Conkle
LinkedIn Profile <http://www.linkedin.com/in/conkle>

**Comment by fernandog** [comment]
Ssh and run:
touch Nashville.S02E04.You're.No.Angel.Yourself.720p.test

then run: ls
see how appears in the screeb
