### ISSUE TITLE
[Feature Request] Failed Download Processing Re-Downloading Current Quality

### ISSUE THREAD

**Issue by tjw1184** [SiCKRAGETV/sickrage-issues#547]
SR Version: 	BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb
Python Version:	2.7.8 (default, Dec 12 2014, 21:20:40) [GCC 4.7.3 20130102 (prerelease)
Running on Synology NAS

Currently have custom quality settings, basically any for initial release and 720p web-dl\bluray for archive.  Sometimes I'll have a low quality episode and it will find a newer one (i.e. web d-l) and try to download it.  Web d-l will fail, it will detect failure and search for a new version.  I've had all copies of web d-l fail and it will then add a hdtv nzb to download.  The problem here is that it is now downloading the same quality for the show as I already have (as the initial download was hdtv).  

Is this an expected behavior for the failed download processing (it will keep downloading and reducing qualities until it succeeds - even if that is equal to or lower than the episode's current quality?

Also, is there a way to display the current quality of a downloaded episode when it's been snatched (i.e. display hdtv in a current column when a 1080p is snatched) to see what quality you currently have?

**Comment by fernandog** [comment]
@tjw1184 stop SR, backup your entire SickRage folder, start SR, switch to DEVELOP branch at Config>Advanced>Github 
Report back

**Comment by tjw1184** [comment]
I switched to the develop branch, haven't been able to reproduce yet.  Noticed another odd behavior on downloaded files where it seems to throw out perfectly good files - in this case the show is at quality 720p web-dl so the one below was snatched and should have over written it.  From post processing script:

```
           Loading config from /usr/local/sabnzbd/var/scripts/autoProcessTV.cfg

Opening URL: http://localhost:8083/home/postprocess/processEpisode
Processing folder /volume1/Media/sabnzbd/complete/SHOW S03E07 1080p WEB-DL DD5 1 H 264-NTb
TV_DOWNLOAD_DIR: /volume1/Media/sabnzbd/complete
PostProcessing Path: /volume1/Media/sabnzbd/complete
PostProcessing Dirs: [u'SHOW S03E07 1080p WEB-DL DD5 1 H 264-NTb']
PostProcessing Files: []
PostProcessing VideoFiles: []
PostProcessing RarContent: []
PostProcessing VideoInRar: []
Processing folder SHOW S03E07 1080p WEB-DL DD5 1 H 264-NTb
You're trying to post process a video that's already been processed, skipping
Deleting file Bayer Balance 009000185649993.nfo
Deleting file Bayer Balance 009000185649993.nzb
Deleted folder: /volume1/Media/sabnzbd/complete/SHOW S03E07 1080p WEB-DL DD5 1 H 264-NTb
Successfully processed
```

**Comment by tjw1184** [comment]
I've now gotten a couple episodes to fail.  The handling for failed processing now seems to be broken.  The logs will show that it was handled successfully, and it will show up under manage searches - but when it completes it won't show up under history and it doesn't show under manage->failed downloads (even when I set the limit to all).  It seems that it isn't properly handing the failed downloads (4-5 so far).  The episodes the failed downloads refer to are also staying in the snatched state:

```
2015-02-07 10:47:32 DEBUG    Thread-69 :: Checking if /volume1/MyTVShows/SHOW/Season 05/SHOW- S05E06 - NAME- SD TV.mp4.cover.jpg exists: True
2015-02-07 10:47:32 INFO     Thread-69 :: Failed Download Processing succeeded: (SHOW.S05E06.1080p.BluRay.x264-HD4U.nzb, /volume1/Media/sabnzbd/incomplete/SHOW.S05E06.1080p.BluRay.x264-HD4U)
2015-02-07 10:47:32 INFO     Thread-69 :: Successfully processed
```

SR Version: 	BRANCH: (develop) / COMMIT: (c62d8f2c799edd7daad5648f45276a3464d83a9e)

**Comment by fernandog** [comment]
@Tagforce any clue?

**Comment by TagForce** [comment]
Check my latest PR. Should fix it.

**Comment by TagForce** [comment]
@tjw1184 Can you try if implementing this PR on your install fixes the issues for failed downloads?
https://github.com/SiCKRAGETV/SickRage/pull/1292

I made a boo-boo with one of my previous PRs and changed one too many occurences of a variable, breaking single failed downloads.

**Comment by tjw1184** [comment]
@tagforce, how do I apply the single pr?

**Comment by tjw1184** [comment]
Looked at the diff for the PR and saw it was just two changes to manually applied them.  That seemed to fix the broken failed download processing.

After testing, the original issue seems to remain though.  An example I often get is an episode that is at 720p quality.  It snatches one at 1080p, but that episode fails downloading.  It then processes the failed download and re-downloads the episode at 720p.

**Comment by fernandog** [comment]
Its correct I guess. When it downloads the 1080p SR loses the information about previous download.

**Comment by tjw1184** [comment]
@fernandog, could you mark this as a feature request then?  It has happened many times they I've redownloaded a 720 bluray after a 1080 bluray snatch fails which replaces the 720 bluray that already exists.

Also, there was one instance where I had a 720 bluray and it snatched a 1080 bluray.  The 1080 failed, it grabbed a 720 bluray which also failed - it ended up snatching a web-dl and appeared to replace the 720 bluray with the web-dl that it completed downloading.  Does a failed download snatch have priority over whatever is already downloaded (even if the existing copy has better quality)?

**Comment by fernandog** [comment]
@TagForce @tjw1184 one solution is to check if there is the previous snatched file and dont re-download. Just do a show refresh.

**Comment by tjw1184** [comment]
@fernandog, that sounds like a reasonable solution.  I'm assuming the show refresh would get triggered immediately after the failed download (so you don't have to wait for the next backlog).

**Comment by raymondtrueman** [comment]
I'm also experiencing this problem and would love a solution

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
