### ISSUE TITLE
FINDPROPERS :: [Dutplanet] :: Error while searching Dutplanet, skipping: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by GodZZila** [SiCKRAGETV/sickrage-issues#548]
SR Version:BRANCH: (develop) / COMMIT: (c62d8f2c799edd7daad5648f45276a3464d83a9e) 
Python version : 2.7.3
Thecus OS 5.0 Running on Thecus N7700ProV2

This issue appears 2 month ago. I Tought it will be a general error and will be fixed in future versions. cause i run a develop version. But now two months later the error still exicst

The Error:

015-02-04 11:47:05 FINDPROPERS :: [Dutplanet] :: Error while searching Dutplanet, skipping: 'NoneType' object has no attribute '__getitem__'
2015-02-04 11:32:04 FINDPROPERS :: [Dutplanet] :: Error while searching Dutplanet, skipping: 'NoneType' object has no attribute '__getitem__'

**Comment by abeloin** [comment]
You need to provide a complete log of the error which can be hosted on pastebin.com

See this link on how to enable debug log: https://github.com/SiCKRAGETV/sickrage-issues

**Comment by fernandog** [comment]
@GodZZila when reply, will reopen

**Comment by GodZZila** [comment]
Dear Fernadog. Here i got the debug log

[url]http://www.ronald-online.nl/sickrage.log[/url]

**Comment by abeloin** [comment]
@GodZZila Can you try applying this pull request: SiCKRAGETV/SickRage#1283 and if it fix the issue?

**Comment by GodZZila** [comment]
Still no luck. After new master update.


AA
AATypeError: 'NoneType' object has no attribute '__getitem__'
AA    result_date = datetime.datetime(*item['published_parsed'][0:6])
AA  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/sickbeard/providers/newznab.py", line 362, in findPropers
AA    curPropers = curProvider.findPropers(search_date)
AA  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/sickbeard/properFinder.py", line 85, in _getProperList
AATypeError: 'NoneType' object has no attribute '__getitem__'
AA    result_date = datetime.datetime(*item['published_parsed'][0:6])
AA  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/sickbeard/providers/newznab.py", line 362, in findPropers
AA    curPropers = curProvider.findPropers(search_date)
AA  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/sickbeard/properFinder.py", line 85, in _getProperList
AATraceback (most recent call last):
2015-03-31 10:05:10 ERROR    FINDPROPERS :: [Dutplanet] :: Error while searching Dutplanet, skipping: 'NoneType' object has no attribute '__getitem__'
2015-03-31 10:05:10 INFO     FINDPROPERS :: [Dutplanet] :: Searching for any new PROPER releases from Dutplanet
2015-03-31 10:05:10 INFO     FINDPROPERS :: Beginning the search for new propers

**Comment by GodZZila** [comment]
Still no luck. I've used the last master.
BRANCH: (master) / COMMIT: (26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9) 

AA
AATypeError: 'NoneType' object has no attribute '__getitem__'
AA    result_date = datetime.datetime(*item['published_parsed'][0:6])
AA  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/sickbeard/providers/newznab.py", line 362, in findPropers
AA    curPropers = curProvider.findPropers(search_date)
AA  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/sickbeard/properFinder.py", line 81, in _getProperList
AATypeError: 'NoneType' object has no attribute '__getitem__'
AA    result_date = datetime.datetime(*item['published_parsed'][0:6])
AA  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/sickbeard/providers/newznab.py", line 362, in findPropers
AA    curPropers = curProvider.findPropers(search_date)
AA  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/sickbeard/properFinder.py", line 81, in _getProperList
AATraceback (most recent call last):
2015-05-26 10:34:09 ERROR    FINDPROPERS :: [Dutplanet] :: Error while searching Dutplanet, skipping: 'NoneType' object has no attribute '__getitem__'
2015-05-26 10:34:08 INFO     FINDPROPERS :: [Dutplanet] :: Searching for any new PROPER releases from Dutplanet
