### ISSUE TITLE
Post-processing move files disappear 

### ISSUE THREAD

**Issue by Psychoteur** [SiCKRAGETV/sickrage-issues#552]
Hello, 
if I choose "move" as post-processing. There are a lot of files lost in the process. I don't see a pattern on why ? 

This morning, 3 files downloaded, only 1 made it to its directory. The two others simply vanished.

**Comment by fernandog** [comment]
follow guidelines: https://github.com/SiCKRAGETV/sickrage-issues

**Comment by fernandog** [comment]
@Psychoteur try change to COPY instead of MOVE.

**Comment by Psychoteur** [comment]
Hello,
that's what I did,  but it's not practical since I've to check my queue and delete things by hand. 
 
Thanks.
 
Date: Mon, 9 Feb 2015 07:37:58 -0800

**Comment by fernandog** [comment]
Follow guidelines

**Comment by Psychoteur** [comment]
Sorry, it was a quick answer since I'm at work and I will not have time to
  post a proper issue report before Sunday.
 
Again sorry. 
Date: Fri, 13 Feb 2015 06:24:57 -0800
