### ISSUE TITLE
cannot restore config file

### ISSUE THREAD

**Issue by Ferlez** [SiCKRAGETV/sickrage-issues#553]
after 100% CPU on my Synology 213j I reinstalled and tried to restore from the sameday backup file I get nothing... It says

"Successfully extracted restore files to /usr/local/sickbeard-custom/var/restore
Restart sickrage to complete the restore."

I restart SG and its still as before...

**Comment by fernandog** [comment]
stop SR, unzip the contents of the backup in the SR folder, restart SR

please send full logs

**Comment by Ferlez** [comment]
thx, copied the files and got it back. saved me 2 days of work :)

thx!
