### ISSUE TITLE
[Feature Request]  Manage Episode Status with Air Date

### ISSUE THREAD

**Issue by thermodyn** [SiCKRAGETV/sickrage-issues#555]
In the Manage - Episode Status Management 

It would be very useful to be able to pull out specific episodes where the status is skipped but where there is an air date in the past.  This sometimes happens if the air date is not updated at the right time and the episode misses the download window.

So I would like to either add a filter to select status skipped and air date is in the past. This would allow me to easy change the status to wanted instead of manually going through all my shows periodically.

When you hit the expand show to show each episode - add the air date information for each episode instead of just Season, Episode and Title.  If you could add a button to fire off a manual search - even better.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
