### ISSUE TITLE
Flash (2014) Renaming Ignores Season Folder

### ISSUE THREAD

**Issue by mannibis** [SiCKRAGETV/sickrage-issues#556]
I have this issue with The Flash (2014) specifically. Even though my naming pattern specifies a Season Folder as such: Season %S/%SN - S%0SE%0E - %EN, SickRage just renames the episode and dumps it into the root directory without a season folder. 

Looking at it via Preview Rename yields the same result (I move them into a season folder, and it tells me to Rename it back to the original root folder locations). This is only happening with the Flash. At first I thought it could be related to the fact that it has a year in the show name, but Legends (2014) does not have this issue.

The Flash was added using TVDB, not TVRage. 

Screenshot of Preview Rename: http://i.imgur.com/Vz7nybS.png

Any ideas?

**Comment by abeloin** [comment]
Check in the show settings if 'Flatten files (no folders)' is activated

**Comment by mannibis** [comment]
Wow. Yes it was and I have no idea how that ended up checked




Thank you

**Comment by abeloin** [comment]
@mannibis You're welcome
