### ISSUE TITLE
Getting A LOT of false positive Snatch's of late

### ISSUE THREAD

**Issue by phoniclynx** [SiCKRAGETV/sickrage-issues#557]
Getting quite a few snatch and downloads that are false positives which SickRage can not actually parse

Typically the archive has a large file and an extension with a .LNK file as the of the title followed by a folder with a title called RARBG.com.txt (in almost all cases) and inside that folder a file typically called RARBG.com.mp4. If you try and play that file in something like VLC it fails as its not a valid video file.

I have had this occur on over 10+ occasions so far and it's wasting my download limit.

Synology NAS Version
SR Version:	BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb) 
Python Version:	2.7.8 (default, Dec 12 2014, 20:09:05) [GCC 4.6.4]

**Comment by fernandog** [comment]
Disable the provider that has the fakes

**Comment by phoniclynx** [comment]
I'm not sure how to do that? Where am I going to go do that? Iposted this
in the forum and had my topic closed and told to come put it on here.

**Comment by phoniclynx** [comment]
I have no way of telling who the provider is?

**Comment by fernandog** [comment]
are you using TPB?

**Comment by phoniclynx** [comment]
Yes

**Comment by fernandog** [comment]
please disable it. Wait an update to TPB. Use KAT instead
