### ISSUE TITLE
Just updated to python 2.7.8.11 - SickRage will no longer start

### ISSUE THREAD

**Issue by jpacione** [SiCKRAGETV/sickrage-issues#559]
Any suggestions?

**Comment by abeloin** [comment]
You need to provide more info, see this link https://github.com/SiCKRAGETV/sickrage-issues

**Comment by jpacione** [comment]
sorry.

Branch: main

OS: DSM 5.1-5022 Update 1
Python version: 2.7.8-11

I had everything working fine, but my SABNZBD and Python were needing update.  So I updated Python, then SAB.  SAB came back up, but SickRage did not.  Error is simply "Failed to run the package service"

There is nothing in the log file for SickRage through the UI.  I'm not a Unix guy, so not sure what else I need to provide?  I can ssh into the NAS, and navigate, so if you point me in the right direction, I'm happy to provide more information.  100% sure it was upgrading Python that broke this.

**Comment by jpacione** [comment]
nevermind - I uninstalled it Sickrage and reinstalled, and it's now working.  Thankfully I backed up the config!
