### ISSUE TITLE
[Feature Request] Anime: Absolute number new option

### ISSUE THREAD

**Issue by John-Gee** [SiCKRAGETV/sickrage-issues#560]
Hello,

I'd like to have a new option for Absolute Numbers, to only put it if it's useful information.

Meaning in a single season show, the absolute number is the same as the episode number, then there is no point in having "SN - S01E03 - 03 - EN.ext".
It's nothing important, but I think it would look a bit better without the duplication information.
(Maybe also allow this to be the case for the first season of shows?)

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
