### ISSUE TITLE
TV show does not start downloading, although it can be found in the indexer

### ISSUE THREAD

**Issue by spockfish** [SiCKRAGETV/sickrage-issues#561]
BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb) 
Synology, Chrome browser, Python 2.7.8

I added 'Foo Fighters Sonic Highway', and it fails to download although the show can be found with the used indexer (dognzb).

In debug mode there are a lot of messages stating:

2015-01-25 12:55:10 DEBUG SHOWQUEUE-FORCE-UPDATE :: Not touching status because we have no ep file, the airdate is in the past, and the status is 3

This is exactly the same issue I had like in #64 with the 'Tonight Show'.

**Comment by abeloin** [comment]
Please provide, via pastebin, a full sickrage log including the search results from dognzb

**Comment by fernandog** [comment]
@spockfish when you reply, I will reopen
