### ISSUE TITLE
Feature Request: Post Processing continue to next folder on error

### ISSUE THREAD

**Issue by nytemyst** [SiCKRAGETV/sickrage-issues#562]
Either on post processing or doing a manual post process it will completely stop if an error is found or sync files. So until that issue is resolved it doesn't move on to the next files which probably don't have any issues. Possible to add an option to continue on to the next item on error?

**Comment by TagForce** [comment]
@nytemyst It should only break out of the entire PP run when it encounters syncfiles or if the folder you're trying to PP does not exist or can't be accessed.
That's the only time the ProcessDir function returns a value other than at the end of the run.
It should continue on other errors.

Can you provide a log with an example of another error that halts PP completely?

I think encountering .sync files should halt PP as you cannot be sure that subfolders do not belong to the set of files still syncing.

**Comment by TagForce** [comment]
Closing this Feature request, as it is in the process of being fixed in here: https://github.com/SiCKRAGETV/sickrage-issues/issues/695

Changing the syncfiles detection and handling will automatically implement this feature request.
