### ISSUE TITLE
Post Process and Folder Settings??

### ISSUE THREAD

**Issue by PapaFatHead** [SiCKRAGETV/sickrage-issues#565]
I'm new to using SR but I'm having a problem with a few things.

Show root directories: What setting does this need to be? 

TV Download Dir:  What setting does this need to be? 

SR does download the file requested via my client (rtorrent) with no problems, once the file completes post processing is not moving the file to the folder created for that show.

Please advise..

**Comment by TagForce** [comment]
Show Root: The folder in which your shows reside.
TV Download: Where your download client puts the finished download. 

Show us a log of a post process run.

**Comment by fernandog** [comment]
@PapaFatHead when reply, will reopen.
