### ISSUE TITLE
Feature Request: ignore "Unknown" values of %EN for episode names when PostProcessing

### ISSUE THREAD

**Issue by alaorath** [SiCKRAGETV/sickrage-issues#567]
I'm using custom renaming with the following string:
"Season %S/%S.N.S%0SE%0E.%E.N.(%QN)"

In some cases, the episode name (%E.N) results in "Unknown".  In these rare cases, it would be nice to simply eliminate the episode name (effectively "Season %S/%S.N.S%0SE%0E.(%QN)")

**Comment by TagForce** [comment]
Can you provide an example? Episode names are taken directly from the indexer. They are not parsed from the download. 
If a file has no season/episode in it SickRage won't PP it. So an unknown episode name should never happen, unless it's unknown at tvdb or tvrage as well.

**Comment by alaorath** [comment]
Unfortunately I've manually renamed the specific examples I found, and the log files have long been over-written...

`find . -type f -name '*unknown*.*'`
no results.
