### ISSUE TITLE
Downloaded episodes are not video files, but folders filled with useless files

### ISSUE THREAD

**Issue by MVallee** [SiCKRAGETV/sickrage-issues#569]
I keep getting some episodes that download but turn out to not be video files.

The episode will get snatched but then doesn't get moved with post process. I'll go check where the video files download to and there will be a folder there that's named with the scene name of the download (right down to the .mp4). When you open the folder there are some weird files inside. Usually one with the scene name ending in ".mp4.lnk" that is only a few KB in size and then always one called "RARBG.com.txt" and a video file named "RARBG.com.mp4". That video file is usually the size the episode should be but it will not open or play at all. I end up having to delete the folders and re-downlaod the episode. Has happened at least 10-15 times in the last few weeks and I just had a friend tell me that also had this issue.

Any idea what's going on?

BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb) 
OS X 10.8.5 Python 2.7.2

**Comment by fernandog** [comment]
fake release. SR can't do anything. are you using TPB? disable it for now.

**Comment by MVallee** [comment]
Ya I am using TPB but in the "History" it always shows that the episodes are snatched from Kickass Torrents, as that is listed as my top priority. I'll try disabling TPB and see if it fixes things.

**Comment by fernandog** [comment]
set "only trusted/verified" or something similar in KAT/TPB/etc.. providers

**Comment by MVallee** [comment]
Ya I have had that set for both KAT and TPB.

**Comment by fernandog** [comment]
send the link of a torrent that has this issue

**Comment by Thraxis** [comment]
Verified status isn't working for Kickass at the moment, there is a fix waiting to be applied for that

https://github.com/SiCKRAGETV/SickRage/pull/1278

**Comment by MVallee** [comment]
It just happened again last night with Modern Family and Arrow. Both shows were snatched from KAT. I don't know how to get the link to the torrent file but its still listed in Transmission. @fernandog If you can let me know how to get the link I'll post it here. 

If verified status isn't working like @Thraxis said then it probably is fake releases getting snatched. Any idea when the fix will be applied? I have limited download usage from my ISP so these fake downloads are killing my usage. I attached a screen shot of the folders that download instead of the video files.

![screenshot_15](https://cloud.githubusercontent.com/assets/4130908/6171116/f1da4a68-b2a6-11e4-8451-ff6fcade6d7d.png)

**Comment by fernandog** [comment]
@MVallee add mp4 to the IGNORED words.

I could not find this torrents with mp4 here:
http://www.rarbg.com/torrents.php?search=arrow+s03e13
I think all this are fakes

**Comment by MVallee** [comment]
If I add "mp4" to ignored words, won't it ignore real downloads? Many of the shows that get snatched show up in Transmission ending in ".mp4" but are real. 

Here's a screen cap that shows Arrow (the fake release) in Transmission along with Better Call Saul which was a real release.

![screenshot_16](https://cloud.githubusercontent.com/assets/4130908/6171530/361686b8-b2a9-11e4-8d24-bce8855c446f.png)

**Comment by fernandog** [comment]
@MVallee no. there's also the EZTV releases. they are more reliable
