### ISSUE TITLE
No downloads were found

### ISSUE THREAD

**Issue by Gieffe** [SiCKRAGETV/sickrage-issues#570]
Hello,

 I'm not able to snatch  anything. Everytime I get "no downloads were found". I'm using latest master version of sickrage running on  DSM 5.1-5022 Update 2. I use only torrents as search providers.

log file: http://pastebin.com/W5XnGVDn 

Regards

**Comment by Gieffe** [comment]
Python version 2.7.8-11

**Comment by Zwooosh** [comment]
Same issue here. 
Tested with Family Guy and Better Call Saul (both have episodes available, neither will download).

**Comment by dirkr07** [comment]
Your log shows you are using only TPB and Kickass as your search providers.
TPB has been down for quite some time now (or in limbo) and kickass.so has been taken down (domainname only) and an issue has been raised already to change the url in the provider settings.

**Comment by Zwooosh** [comment]
Yes thank you. After manually changing the providers everything started working again.

**Comment by lsborg** [comment]
I'm having the same issue, which providers are working?

**Comment by lsborg** [comment]
All public providers are failing: 
ThePirateBay
KickAssTorrents
NyaaTorrents
EZRSS
TokyoToshokan
NextGen

**Comment by abeloin** [comment]
@lsborg You better create a new issue as this one is closed

**Comment by lsborg** [comment]
haha, i didn't noticed it. 

Thanks, @abeloin!
