### ISSUE TITLE
Kickass.so has been shutdown

### ISSUE THREAD

**Issue by moust4ki** [SiCKRAGETV/sickrage-issues#571]
Could you change the URL to kickass.to as the .so is down?
Thanks

**Comment by fernandog** [comment]
waiting to be merged

**Comment by InfamousBlade** [comment]
For now you guys can manually edit SickRage-master\sickbeard\providers\kat.py. All you have to do is change one line.

**Comment by taj693** [comment]
How do you access the provides in openelec. Can't find them

**Comment by mikkelnl** [comment]
@taj693 It's located here: 
/storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/sickbeard/providers

**Comment by dmarcelino** [comment]
+1 for SiCKRAGETV/SickRage#1264 to be merged to both `master` and `develop`.

**Comment by Tlabok** [comment]
I agree that merging is a priority. I can't manually update, as my Qnap package automatically restores the default SR installation files after a restart.

**Comment by fernandog** [comment]
@echel0n

**Comment by brimur** [comment]
As a temp workaround just create a custome provier called KAT and use this as the RSS string... 
````
http://katproxy.com/usearch/category%3Atv/?field=seeders&sorder=desc&rss=1
````

**Comment by alaorath** [comment]
After editing the kat.py file, do you also need to recompile the .pyc?

**Comment by fernandog** [comment]
Stop SR, edit kat.py, restart SR. Just thst

**Comment by ion-storm** [comment]
confirmed, editing line:
self.urls = {'base_url': 'http://kickass.so/'} 
changing it to:
self.urls = {'base_url': 'http://kickass.to/'}
fixes the problem, thanks guys

**Comment by pwolstenholme** [comment]
For Synology, the provider file can be found here:

/var/packages/sickbeard-custom/target/var/SickBeard/sickbeard/providers

Edit the file by typing ```vi kat.py```. Press the <kbd>i</kbd> key once to start editing the file. When you're done, press <kbd>esc</kbd> then type ```:wq``` to save and quit.

There's more help editing files here: http://www.cs.colostate.edu/helpdocs/vi.html

**Comment by Nmisis21** [comment]
Does anyone know where to find the providers folder in FreeNAS?

It doesn't appear to be the same as the ones stated or I'm not looking properly.

I've tried looking in the Jail via SSH, but am having no luck locating it.

**Comment by fernandog** [comment]
@moust4ki  develop updated. please test and report back

**Comment by Arcanemagus** [comment]
If you don't specifically need a response from @moust4ki, https://github.com/SiCKRAGETV/SickRage/pull/1264 has been working perfectly fine for me on the develop branch for a week or two.
