### ISSUE TITLE
Wrong searchstring 

### ISSUE THREAD

**Issue by wurzel89** [SiCKRAGETV/sickrage-issues#573]
Hi,

I was setting up Sickrage for the first time and I cant find the mistake I did.
https://oldpiratebay.org/search.php?q=The.Simpsons%20S26E13%7C26x13%20&Torrent_sort=seeders.desc 
It is searching Season and Ep twice. Also how do I manually add Piratebay since it is on again?

Greetings

**Comment by geek2009** [comment]
+1 Would like to see Pirate Bay support again. Might not hurt to keep oldpiratebay.org as a backup provider though.
