### ISSUE TITLE
Feature Request: Home Page - Show List Filtering

### ISSUE THREAD

**Issue by randellhodges** [SiCKRAGETV/sickrage-issues#574]
I have a lot of TV shows and the home page, even in simple layout can be a big overwhelming. It would be nice, if we could add some filtered views and set one as a default. For example, I am mainly interested in shows that I am missing an episode. I typically just sort by "Downloads" which puts those I'm interested at the top, but I still have to "process it" in my head, so to speak.

**Comment by fernandog** [comment]
try: 
http://localhost:80xx/manage/backlogOverview/

**Comment by Thraxis** [comment]
@randellhodges @fernandog Does the new FilterRow option (enabled in the general settings) meet your needs for this functionality?

**Comment by fernandog** [comment]
@Thraxis exact values dont work. Like 100 or 100=

**Comment by freeminders** [comment]
Thanks! This helps out a lot.  Is there a way we could have the filter persist? For instance, 99.99% of the time, I only want to see shows < 100% downloaded. It would be nice if I could enter that as a filter and whenever I hit the page, be it in the same session, or if I close the browser and come back, it still has that filter applied?

**Comment by Thraxis** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1826

I did not check into the persist filter, but I do believe that is possible

**Comment by fernandog** [comment]
@Thraxis if you are going persist filter will keep this open

**Comment by Thraxis** [comment]
Yeah I'll add the persisted filter(s) tonight

**Comment by fernandog** [comment]
@Thraxis merged. Seems ok! Will do some more tests

**Comment by Thraxis** [comment]
@fernandog If you can think of any other filter options for the episode percent done let me know..  I have to write those in by hand as the built-in options don't work for the hack I used to restore both the weighted sorting and filtering by percent

**Comment by fernandog** [comment]
merged
