### ISSUE TITLE
is there a reason why it uses the show name instead of the rageId to search?

### ISSUE THREAD

**Issue by danielb2** [SiCKRAGETV/sickrage-issues#575]
This is the question I was asked:

> is there a reason why it uses the show name instead of the rageId to search

I had no answer for this. Is it supposed to? Do I have something wrong with my settings, or is it just not supported?

If it's not supported, it would appear as if sickbeard does. Can sickrage be released with that patch?

**Comment by fernandog** [comment]
it uses rageid for NZB.
