### ISSUE TITLE
TypeError: 'TVEpisode' object does not support indexing

### ISSUE THREAD

**Issue by brando56894** [SiCKRAGETV/sickrage-issues#579]
Debug Log: http://pastebin.com/pphGZ04e

SickRage Develop Branch

I wasn't really sure how to revert commits (tried once and it seemed to work but didn't actually change the code) so I just reverted #1258 manually (https://github.com/SiCKRAGETV/SickRage/pull/1258/files?diff=unified) by removing the [] around segment

FreeBSD 9.3, Python 2.7

**Comment by abeloin** [comment]
Switching from the forum,

There's a new pull request that revert part of 1258, it's 1292

* Stop Sickrage
* Revert any changes: ```git reset --hard```
* Apply this new pull request: https://github.com/SiCKRAGETV/SickRage/pull/1292.diff
* Start sickrage
* Try a failed download
* Post the log

**Comment by brando56894** [comment]
I'm pretty much a newbie to git, how to I apply the pull request?

**Comment by fernandog** [comment]
```
cd SickRage
git reset --hard
wget --no-check-certificate https://github.com/SiCKRAGETV/SickRage/pull/1292.diff
patch -p1 < 1292.patch
```

**Comment by brando56894** [comment]
Thanks.

Still the same error: http://pastebin.com/CZ8GNVw9

Not sure if everything happened correctly because I did get these messages

root@Template:/usenet/SickRage # git reset --hard
HEAD is now at 2cb2949 Revert "Fix for 'List type has no attribute' on setting failed"

root@Template:/usenet/SickRage # patch -p1 < 1292.diff
Patching file sickbeard/failedProcessor.py using Plan A...
Reversed (or previously applied) patch detected!  Assume -R? [y]
Hunk #1 succeeded at 67.
done

**Comment by abeloin** [comment]
@brando56894 Reopen the issue.

When you did git reset hard it have bring you back to commit c62d8f2c799edd7daad5648f45276a3464d83a9e. Can you provide me the result of ```git log```?

**Comment by abeloin** [comment]
@brando56894 Develop branch updated with the mentioned fix, please update.

**Comment by abeloin** [comment]
@brando56894 Any news?

**Comment by fernandog** [comment]
@brando56894 please reply or we will close this issue
