### ISSUE TITLE
Show with Named Seasons not parsing correctly from XEM

### ISSUE THREAD

**Issue by ncybernee** [SiCKRAGETV/sickrage-issues#582]
Dev Branch
Commit c62d8f2c799edd7daad5648f45276a3464d83a9e
FreeNAS jail (FreeBSD) , python 2.7.5

Anime with named seasons, Anime and Scene checked, is not recognized by XEM Exception names
http://thexem.de/xem/show/1847 : Tokyo Ghoul Season 2 = Tokyo Ghoul Root A

If I'm understanding correctly, SickRage should recognize the following based on the mapping given by XEM: http://pastebin.com/XFhDENi2

**Comment by ncybernee** [comment]
Happening on searching and post-processing

**Comment by abeloin** [comment]
Can you try this: do a force update on the show, wait until complete then restart sickrage. Try to post process your file again.

**Comment by fernandog** [comment]
@ncybernee please reply
