### ISSUE TITLE
Network Logos & TV Shows Posters

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#583]
Hello,
There are some networks that dont have a proper logo, which i have made and resised to use within SickRage ,BUT i dont know on how to make a Pull Request ,so is there someone i can give the files so that he can make a PR with them. 
Also ,ive found out that there are some shows that dont have a poster is there any way i can add it manually to sickrage (or is it possible to someone add it as a feature?)
//Gonkas

**Comment by matigonkas** [comment]
![quest](https://cloud.githubusercontent.com/assets/10121067/6148805/37285b10-b1fc-11e4-93a0-2c728f195b3f.png)
![tvi](https://cloud.githubusercontent.com/assets/10121067/6148806/37402fba-b1fc-11e4-8356-a5a279f9e73c.png)

These are the network logos if anyone could make a PR with them it would be awesome ;)

**Comment by abeloin** [comment]
You need to include the network name

**Comment by matigonkas** [comment]
Sorry the top one is "quest" and the bottom is "tvi" also there is a logo for "national geographic" but there isnt for "national geographic channel"

**Comment by abeloin** [comment]
To confirm, in thetvdb their name are quest and tvi?

**Comment by matigonkas** [comment]
i havnt found quest tv shows in thetvdb only on tvrage ,but yes those are their names

**Comment by abeloin** [comment]
Do you have any show in sickrage that are from that network?

**Comment by matigonkas** [comment]
yes http://www.tvrage.com/the-rise-of-the-nazi-party for quest and http://thetvdb.com/?tab=series&id=256115 for tvi

**Comment by abeloin** [comment]
Exactly what I needed to test them.

I couldn't find 'Jardins Proibidos' in the tvdb ;)

**Comment by neoatomic** [comment]
@matigonkas , Thank you for providing the logos. I just added them for you.

@fernandog This can be closed.
