### ISSUE TITLE
Unpacking with the sickrage freenas pbi fails even when unrar is installed

### ISSUE THREAD

**Issue by amblique** [SiCKRAGETV/sickrage-issues#585]
I have installed the sickrage plugin in freenas 9.3.
I installed unrar via pkg install unrar, it's version 5.2
I have updated sickrage to the development branch as of a day ago.
I have copied the rar executable from /usr/local/bin of the sickrage jail to the lib/unrar2 folder

When i select the unpacking option in the sickrage UI it doesn't present the error dialog, indicating that it has found the unrar executable.

When I run the postprocessor it reports an error on file copy of the mp4. Further inspection of this shows that the mp4 is never actually successfully created by the call to unrar the archives.

I don't think the unrar implementation actually causes the post processor to error out, so i have been unable to get any more detailed logs than that.

I have puttied into the freenas machine (the root machine not the jail) and run "python test_unrar2.py" in the lib/unrar2 folder and it errors out in the call to unrar. if I change the command from ('unrar', 'rar') to ('/usr/local/bin/unrar','rar') then running "python test_unrar2.py" in the freenas shell session (not the jail shell) actually works, but running the postprocessor still fails.

It looks like it might be a permission or access issue directly related with how sickrage is installed in the pbi jail.

I think the unix.py implementation should do more to interrogate the location of unrar to ensure it can execute it correctly, or at least save the location it found it in when i originally checked the unpack option.

**Comment by amblique** [comment]
FYI, this is the error reported by running the test_unrar2.py script

Traceback (most recent call last):
  File "test_UnRAR2.py", line 20, in <module>
    rarc = UnRAR2.RarFile('test.rar')
  File "/mnt/shares/jails/sickrage_1/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/unrar2/__init__.py", line 100, in __init__
    RarFileImplementation.init(self, password)
  File "/mnt/shares/jails/sickrage_1/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/unrar2/unix.py", line 67, in init
    stdoutdata, stderrdata = self.call('v', []).communicate()
  File "/mnt/shares/jails/sickrage_1/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/unrar2/unix.py", line 121, in call
    return call_unrar([cmd]+soptions+['--',self.archiveName]+files)
  File "/mnt/shares/jails/sickrage_1/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/unrar2/unix.py", line 50, in call_unrar
    raise UnpackerNotInstalled("No suitable RAR unpacker installed")
unrar2.unix.UnpackerNotInstalled: No suitable RAR unpacker installed

**Comment by abeloin** [comment]
If /usr/local/bin/ isn't in your path variable then this is why test_unrar2.py doesn't find it.

Can you post the full log of when that mp4 was post-processed ?

**Comment by amblique** [comment]
Hi abeloin,

Running unrar like this inside the jail shell and inside the root system shell works fine. So this means the unrar binary is in the path. This would probably also explain why the settings ui doesn't complain when I check the unpack checkbox.

Log file doesn't say much, see below:

```
Processing folder /mnt/downloads/download-file
TV_DOWNLOAD_DIR: /mnt/downloads
PostProcessing Path: /mnt/downloads/download-file
PostProcessing Dirs: []
Packed Releases detected: ['download-file.rar']
Unpacking archive: download-file.rar
UnRar content: ['download-file.mp4']
PostProcessing Files: ['download-file.r02', 'download-file.r08', 'download-file.r11', 'download-file.r23', 'download-file.r16', 'download-file.r05', 'download-file.r01', 'download-file.r12', 'download-file.r18', 'download-file.r20', 'download-file.r15', 'download-file.r06', 'download-file.r04', 'download-file.rar', 'download-file.r17', 'download-file.r10', 'download-file.nfo', 'download-file.r22', 'download-file.r09', 'download-file.r03', 'download-file.r07', 'download-file.r14', 'download-file.r19', 'download-file.r13', 'download-file.r21', 'download-file.sfv', 'download-file.r00', 'download-file.mp4']
PostProcessing VideoFiles: ['download-file.mp4']
PostProcessing RarContent: ['download-file.mp4']
PostProcessing VideoInRar: ['download-file.mp4']
Processing /mnt/downloads/download-file/download-file.mp4 (None)
Retrieving episode object for 6x13
Snatch history had a quality in it, using that: Unknown
Is ep a priority download: True
There is no existing file so there's no worries about replacing it
This download is marked a priority download so I'm going to replace an existing file if I find one
Found release name download-file
Destination folder for this episode: /mnt/download/download-file
Copying file from /mnt/downloads/download-file/download-file.mp4 to /mnt/download/download-file/download-file.mp4
Processing failed for /mnt/downloads/download-file/download-file.mp4: Unable to move the files to their new home
Problem(s) during processing
```

**Comment by abeloin** [comment]
How to get the full log after the the post-process failed:
1. Go to 'Logs & Errors' in the top menu.
2. Click View Log
3. On the right side select 'Debug' in the 'Minimum logging level to display' drop down list.
4. Look for multiple lines with 'POSTPROCESSER' in it.
5. Copy all the related line to pastebin
6. If none, put the file Logs/sickrage.log on pastebin.

By the way, 'Unable to move the files to their new home' is oserror  usually associated with file permissions issue(destination)

**Comment by amblique** [comment]
That is the log with the log level set to DEBUG already.

I logged this issue specifically because it's the unrar activity failing (and the failure not being detected) that is triggering the  'Unable to move the files to their new home' error. The file can't be copied because it doesn't exist. It doesn't exist because the unrar call doesn't actually succeed, but the error is either not raised or not caught. However if you run a shell in the jail and run unrar from the command line it works fine.

I seriously thing it has something to do with the environment (python or shell of the service) that the sickrage install is running under in the freenas pbi.

**Comment by abeloin** [comment]
What you are showing me look like a lot more like the report printed in the web page after you run a 'Manual Post-Processing' then what is in the log file.

Anyhow, here some of thing I would check:
* Run an ```unrar -t download-file.rar``` to confirm the archive is valid and without error.
* Check who's the user running sickrage in jail. [Accessing a jail using ssh](http://doc.freenas.org/9.3/freenas_jails.html#accessing-a-jail-using-ssh)
* Make sure that user a rw access to download-file.rar folder..
* Login via ssh into your jail as the user running sickrage, cd to download-file.rar folder, run ```unrar x download-file.rar```
* Add ```import pdb; pdb.set_trace()``` in lib/unrar2/unix.py at the beginning of extract() and pull the content of stdoutdata and stderrdata value which the unrar command results.

**Comment by amblique** [comment]
Re-installed the plugin. Installed unrar with pkg install unrar, not pkg_add -r unrar.
Now it works.

Thanks for your help guys
