### ISSUE TITLE
Torrents not adding to ruTorrent - `rTorrent: Unable to send Torrent: Return code undefined`

### ISSUE THREAD

**Issue by nathanu** [SiCKRAGETV/sickrage-issues#587]
I have SickRage and ruTorrent running on a Feral seedbox, where do i start troubleshooting this? The authentication test in Search Settings is successful but my shows arent getting downloaded.

`SEARCHQUEUE-BACKLOG-75805 :: rTorrent: Unable to send Torrent: Return code undefined`

**Comment by nathanu** [comment]
Any details where i can look for this?

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/242
