### ISSUE TITLE
[Feature Request] S02E03-07 torrent

### ISSUE THREAD

**Issue by gborri** [SiCKRAGETV/sickrage-issues#588]
Would be great if it will be the possibility to get a valid torrent file E03-07 for torrent episode E04.

**Comment by neoatomic** [comment]
@gborri Can you be more specific with your request.?

**Comment by fernandog** [comment]
Too complicate I think.
This torrent has ep 4 5 6 and 7.
He only wants ep 4.

Its a kind of uncomplete season torrent
