### ISSUE TITLE
KAT and TPB addresses do not work

### ISSUE THREAD

**Issue by brimur** [SiCKRAGETV/sickrage-issues#591]
The addresses below are the ones used to check TPB and KAT but neither of these work. The KAT one does not seem to exist, maybe its a typo and should be kickass.to and the oldpiratebay.org does not seem to return anything. I had to setup a custom KAT provider to get anything.

[ThePirateBay] :: Search string: https://oldpiratebay.org/tv/latest/ 
[KickAssTorrents] :: Search string: http://kickass.so/

**Comment by fernandog** [comment]
Duplicate.
