### ISSUE TITLE
No downloads were found Couldn't find a download for xxxx

### ISSUE THREAD

**Issue by danielb2** [SiCKRAGETV/sickrage-issues#592]
`No downloads were found Couldn't find a download for xxxx` that's all I see these days.  I tried downloading a fresh install with fresh database, put all my indexes in, but I get nothing.  No show works.  I should at least get something with the included indexers, I should think, but nothing with them, nor with other newznab ones.

I've tried both master and develop, but master doesn't work at all due to config page not working and what not. 

    FreeBSD luffy 10.1-RELEASE FreeBSD 10.1-RELEASE #0 r274401: Tue Nov 11 21:02:49 UTC 2014

I suspect this is a FreeBSD issue because otherwise I'd hear more noise. 

Help appreciated.

**Comment by fernandog** [comment]
TPB and KAT moved to another URL.
Add another provider

**Comment by itsikavidan** [comment]
You could just modify the provider URL under <SickRagenstallPath>\sickbeard\providers\<ProviderName>.py
In the file you should find the self.urls attribute, change the URL to the updated one and restart SR.

I guess that in the next release it will be fixed, but until than this should work

**Comment by ShinobiX9X** [comment]
I did so in .../providers/providersname.py and it does work fine now.
KAT: http://kickass.to/
TPB: https://thepiratebay.se

**Comment by danielb2** [comment]
Would you reopen this please? I don't use torrents, and it's simply not working with ANY providers. I have over five ones in there.  It worked fine until I updated.   As I said, it doesn't even work with a fresh install.

**Comment by fernandog** [comment]
Follow guidelines then. Post full logs and all info

**Comment by danielb2** [comment]
Fair enough. Coming up.

**Comment by danielb2** [comment]
**Branch:**  `develop`

**Commit hash:** `401cb666016e45b42fe675bafdf7908ad6c2b9bb`

**Your operating system and python version:**

``` bash
$ python --version
Python 2.7.9
$ uname -a
FreeBSD luffy 10.1-RELEASE FreeBSD 10.1-RELEASE #0 r274401: Tue Nov 11 21:02:49 UTC 2014     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
```

**What you did:**

I searched for `Elfen Lied` or any other show

**What happened:**

Episode was not found despite being available. I tired multiple providers

**What you expected:**

I expected an episode to be found.

**Link to a copy/paste of your logfile with clear debug info of the error on PASTBIN:**

I'm using gist because it's easier. But if that sucks, let me know and I'll change it: https://gist.github.com/danielb2/b7af7df1dadd186b7c66

**Comment by fernandog** [comment]
```
2015-02-13 09:46:17 ERROR    SEARCHQUEUE-DAILY-SEARCH :: No NZB/Torrent providers found or enabled in the sickrage config for daily searches. Please check your settings.
```

please ENABLE at least one search provider settings

**Comment by danielb2** [comment]
This is what I have. What am I missing?

![screen shot 2015-02-13 at 10 37 51 am](https://cloud.githubusercontent.com/assets/26678/6193023/6130000e-b36c-11e4-955c-9210e8cd14be.png)
![screen shot 2015-02-13 at 10 37 47 am](https://cloud.githubusercontent.com/assets/26678/6193025/636e9be6-b36c-11e4-9ace-46482313be7e.png)
![screen shot 2015-02-13 at 10 37 42 am](https://cloud.githubusercontent.com/assets/26678/6193027/663be3b0-b36c-11e4-9beb-5d2e7913d362.png)
![screen shot 2015-02-13 at 10 37 35 am](https://cloud.githubusercontent.com/assets/26678/6193029/697500e8-b36c-11e4-9cc9-8d89e535f50d.png)

**Comment by danielb2** [comment]
[config.ini](https://gist.github.com/danielb2/b41f3973a06c18c65d7e)

**Comment by fernandog** [comment]
that's strange
try enable nzbs.org

**Comment by danielb2** [comment]
Do you have a way I can get an account there?   AS mentioned, I have several newznab accounts, but none of them work either. The result is the same

**Comment by fernandog** [comment]
which one do you have? did you try custom newznab provider?

**Comment by danielb2** [comment]
http://nzbid.org/  for example

**Comment by danielb2** [comment]
If you have another one that you'd like me to try that's not closed, I'd be happy to put it in.

**Comment by fernandog** [comment]
@danielb2 try this one: https://www.oznzb.com/register

**Comment by danielb2** [comment]
Here it is with oznzb.com  https://gist.github.com/danielb2/0672b56341a026912770

**Comment by danielb2** [comment]
Hello? And since this is an issue, can you change from closed to open?

**Comment by abeloin** [comment]
@danielb2 The issue is the selected provider in your screenshot doesn't support backlog search(notice the * after the name) hence the "No NZB/Torrent providers found or enabled..."

As for oznzb, there's an error:
```2015-02-13 14:55:01 DEBUG    Thread-50 :: Error getting html for [https://api.oznzb.com//api?apikey=blahblah&t=caps]```

Have you selected and updated the the newznab categories in the providers options?

**Comment by danielb2** [comment]
> The issue is the selected provider in your screenshot doesn't support backlog search(notice the * after the name) hence the "No NZB/Torrent providers found or enabled..."

What about for the sickbeard index tho?

> As for oznzb, there's an error:

That's because originally, I was using an old API url (api.oznzb.com vs simply oznzb.com)

I have four or five different newznabs, and none of them work.

And yes, I've tried updating the newznab categories. 

Anything else you can think of me trying? Some other specific newznab service?

**Comment by abeloin** [comment]
NZBs.org is also missing it's credential:
```
2015-02-13 14:53:51 ERROR    SEARCHQUEUE-MANUAL-75941 :: [NZBs.org] :: Authentication error: Your authentication credentials for NZBs.org are missing, check your config.
Traceback (most recent call last):
  File "/usr/home/daniel/tmp/SickRage/sickbeard/search.py", line 483, in searchProviders
    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch)
  File "/usr/home/daniel/tmp/SickRage/sickbeard/providers/generic.py", line 257, in findSearchResults
    self._checkAuth()
  File "/usr/home/daniel/tmp/SickRage/sickbeard/providers/newznab.py", line 220, in _checkAuth
    raise AuthException("Your authentication credentials for " + self.name + " are missing, check your config.")
AuthException: Your authentication credentials for NZBs.org are missing, check your config.
```

**Comment by danielb2** [comment]
I don't have nzbs.org and it's not checked so not sure why it's trying that.

**Comment by abeloin** [comment]
Looking at the results(the url directly) of oznzb and sickbeard from the last log, there's simply no results from both providers. This is why you're not getting results for that particular show.

I tried [opennzb](http://opennzb.net/api?apikey=0&maxage=500&cat=5030%2C5040%2C5070&q=Elfen.Lied+1&limit=100&attrs=rageid&offset=0&t=tvsearch) and there's some releases.

Try adding opennzb:
![Imgur](http://i.imgur.com/ngGsEja.png)

**Comment by danielb2** [comment]
I tried adding opennzb.net Check the result:   https://gist.github.com/danielb2/8c3ad220e5771fc6a642


note that line 968 does have the same search for the release you got there

**Comment by abeloin** [comment]
There's not much I can do here, you set the show to look for SDTV and SDDVD(any,best = [1, 2] []) and there's none available. There's episodes available in HDTV, Bluray.

So in the end, your system is now correctly configured to do backlog but there's no episodes available for the requested quality.

**Comment by danielb2** [comment]
2015-02-19 07:44:42 INFO     SEARCHQUEUE-MANUAL-95011 :: Unable to find a download for: [Modern Family - 6x15 - 015 - Fight or Flight]
2015-02-19 07:44:42 DEBUG    SEARCHQUEUE-MANUAL-95011 :: formatting pattern: %SN - %Sx%0E - %EN -> Modern Family - 6x15 - 015 - Fight or Flight
2015-02-19 07:44:42 DEBUG    SEARCHQUEUE-MANUAL-95011 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
2015-02-19 07:44:42 DEBUG    SEARCHQUEUE-MANUAL-95011 :: formatting pattern: %SN - %Sx%0E - %EN -> Modern Family - 6x15 - 015 - Fight or Flight
2015-02-19 07:44:42 DEBUG    SEARCHQUEUE-MANUAL-95011 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
2015-02-19 07:44:41 DEBUG    SEARCHQUEUE-MANUAL-95011 :: [nzbndx.com] :: Search url: https://www.nzbndx.com/api?apikey=key&season=6&maxage=500&cat=5030%2C5040&q=Modern.Family&limit=100&attrs=rageid&offset=0&ep=15&t=tvsearch


Here's a result which returns results, but doesn't actually end up finding any results.

I set the quality to "any" but still nothing.

**Comment by abeloin** [comment]
Can you provide the whole log for SEARCHQUEUE-MANUAL-95011?

**Comment by danielb2** [comment]
https://gist.github.com/danielb2/da2a8ad513e2e7b1dc52

**Comment by abeloin** [comment]
Look at the log, none of the providers returned results. This is why there's no results.

When data isfound and returned from a provider it will show like this:
```
2015-02-18 15:52:58 DEBUG    SEARCHQUEUE-MANUAL-75941 :: [http://opennzb.net] :: Using ALL regexes
2015-02-18 15:52:58 DEBUG    SEARCHQUEUE-MANUAL-75941 :: [http://opennzb.net] :: Using cached parse result for: [Coalgirls]_Elfen_Lied_07_(1280x720_Blu-ray_FLAC)_[EC89D12D].mkv
2015-02-18 15:52:58 DEBUG    SEARCHQUEUE-MANUAL-75941 :: [http://opennzb.net] :: The result [Coalgirls]_Elfen_Lied_07_(1280x720_Blu-ray_FLAC)_[EC89D12D].mkv doesn't seem to be a valid episode that we are trying to snatch, ignoring
2015-02-18 15:52:58 DEBUG    SEARCHQUEUE-MANUAL-75941 :: [http://opennzb.net] :: Adding item from search to cache: [Coalgirls]_Elfen_Lied_07_(1280x720_Blu-ray_FLAC)_[EC89D12D].mkv
2015-02-18 15:52:58 DEBUG    SEARCHQUEUE-MANUAL-75941 :: [http://opennzb.net] :: Added RSS item: [[Coalgirls]_Elfen_Lied_07_(1280x720_Blu-ray_FLAC)_[EC89D12D].mkv] to cache: [http___opennzb_net]
```

**Comment by abeloin** [comment]
In the end if the provider doesn't have it or it's older than 500 days, sickrage won't be able to fetch it.

**Comment by danielb2** [comment]
That's not what I found at all. The https://nzbs.in/api?apikey=key&season=6&maxage=500&cat=5030%2C5040&q=Modern.Family&limit=100&attrs=rageid&offset=0&ep=15&t=tvsearch

This query provides results. But it still shows up as not having found anything. Why is that?  I can go download this one manually if I chose, but that defeats the purpose.

Also, I have used sickbeard for _10 years_ (according to when I signed up on the forums) without a problem like this.   When I switched to sickrage, I had no issues. However, ever since I had to do an upgrade due to the SSL problems, this issue has persisted.

If I had just tried sickrage, and I had this issue, I would never have switched, and that would have been that. But I'd say I'm rather experienced with the software at this point, and this is unexpected.

Make sense?

**Comment by abeloin** [comment]
Update to the latest version of sickrage, as the information provided in your previous comment points to an old version of the master's branch(2015-01-17) and not develop.
> Branch: develop
>Commit hash: 401cb666016e45b42fe675bafdf7908ad6c2b9bb

**Comment by danielb2** [comment]
Alright it works now, but it must have been a string of unfortunate events. I have my own branch in which I keep my config.ini file. I just did a rebase to develop and now it works. Oddly enough I just rebased to develop prior to opening this ticket.  In order to debug with elfen lied, I had used a completely fresh install, but I guess elfen lied was just a bad example.

**Comment by danielb2** [comment]
Oh, and thanks for helping me work through this. Much appreciated.

**Comment by abeloin** [comment]
It's unfortunate that I didn't see that you were running 2.7.9 before as I would have ask you to make sure your branch is up to date. But in end, success is success albeit a little longer than anticipated.

Main issue for future reference: This is related to python 2.7.9 enabling SSL certificate by default, see [PEP-476](https://www.python.org/dev/peps/pep-0476/ )

It is temporarily fixed via commit https://github.com/SiCKRAGETV/SickRage/commit/ad3a54ba51c875de2830c9ee0b913326078978d2 which is in master and develop.

**Comment by danielb2** [comment]
So I remember the sequence now. I know for sure I had rebased my branch because without the changes, the config page didn't work at all on FreeBSD. The SSL had already been solved. There must have been something else. Regardless, it's nice to have things back to normal :)

**Comment by CanyonMonkey** [comment]
This is the first  time I've used GitHub so I apologise for any etiquette errors (like reviving old threads!). 
I followed 
http://www.htpcguides.com/install-sickrage-windows-usenet-torrent-tv/ 
to set-up SickRage and I have the same problem described above. 

I have installed Python 2.7.9  so I assume that's the issue! I just don't understand what I'm supposed to do to correct it. Please could someone give me a bit of a dummies guide? The 'check for updates' option in SickRage tells me I'm up to date.

Thanks for taking the time to read this post and thanks even more if you reply!!

**Comment by fernandog** [comment]
Please read wiki/faq

https://github.com/SiCKRAGETV/sickrage-issues/wiki
