### ISSUE TITLE
Feature Request: gracefully handle exception thrown when an episode no longer exists after being fully processed

### ISSUE THREAD

**Issue by alaorath** [SiCKRAGETV/sickrage-issues#594]
I have two folders for TV shows - "normal" ones, and my wife's CSI crap.  :)

Since she deletes episodes after watching them... it causes a huge problem for the web page of that show (it throws an exception).

The only work-around I've found is to manually recreate a zero-byte file with the same name, refresh the show page, change the episode to "IGNORED", then finally delete the zero-byte episode.

To Reproduce:
After finishing processing (so the episode shows as "downloaded"), delete the file and refresh the show page.

**Comment by fernandog** [comment]
I also delete and there is no exception.
Stop SR, edit config.ini and set to 1 skip_removed or something like that.

**Comment by alaorath** [comment]
Confirmed **skip_removed_files = 1** works fine.

Closing.
