### ISSUE TITLE
init.debian is using "return" in the case statement for "restart" option only (should be exit)

### ISSUE THREAD

**Issue by alaorath** [SiCKRAGETV/sickrage-issues#595]
Line 147 should be:
exit $?

```
143     restart|force-reload)
144         stop_sickbeard
145         sleep 2
146         start_sickbeard
147         #return $?
               exit $?
148         ;;
```

**Comment by fernandog** [comment]
@alaorath what works for you?

**Comment by alaorath** [comment]
I changed line 147 to 'exit $?' and that eliminated the error with restarting...


Existing master:
    $ sudo /etc/init.d/sickbeard restart
    /etc/init.d/sickbeard: line 148: return: can only 'return' from a function or sourced script
    $

After changing line 147:
    $ sudo /etc/init.d/sickbeard restart
    $

**Comment by fernandog** [comment]
@alaorath 

click the pencil, edit the file, insert a title and make a pull request
https://github.com/SiCKRAGETV/SickRage/blob/develop/init.debian

always do this in **DEVELOP** branch

can you check other init scripts for the same error?

**Comment by alaorath** [comment]
Checked the others, didn't see anything obvious (but I'm not really familiar with non-Debian init scripts).

**Comment by abeloin** [comment]
PR was merged
