### ISSUE TITLE
Adding custom provider creates error popup "Not a valid bencoded string"

### ISSUE THREAD

**Issue by SpecialKeezie** [SiCKRAGETV/sickrage-issues#596]
Hi, i have searched high and low and cannot find an answer to this question

Here is what it says in the debug log:
http://pastebin.com/PyVFXuHs

BRANCH: (develop)
COMMIT: (c62d8f2c799edd7daad5648f45276a3464d83a9e) 
Python 2.7.9
Windows 8

I completely reinstalled SickRage from scratch a couple days ago after updating Python and moving SickRage to a new drive. I added a couple of custom feeds to the provider list, and they appeared on the list just fine. The next day i opened SR and noticed they were missing. I tried re-adding them, and i keep getting an error that pops up on the screen. 

![capture](https://cloud.githubusercontent.com/assets/10748821/6196064/98130464-b3a2-11e4-9d3e-777aa4ff0518.JPG)

This happens with any feed that i try to add. It appears that it's trying to open the .torrent file that is first in the RSS feed. according to the custom_torrent.html in the cache folder that is

**Comment by fernandog** [comment]
what about http://extratorrent.cc/rss.xml?type=popular&cid=8

**Comment by SpecialKeezie** [comment]
tried it, as well as the link without the cookies and i get a different error "no items found in rss feed". Here is the log when trying it that way

http://pastebin.com/m0Hph4r3

i've tried many other addresses for other providers, no matter what i get one of the two errors

**Comment by fernandog** [comment]
@SpecialKeezie Try RARBG if does not work is something on your setup

http://rarbg.com/rssdd.php

**Comment by abeloin** [comment]
@SpecialKeezie I see that you have python 2.7.9, can you try applying this commit and restart sickrage:

https://github.com/SiCKRAGETV/SickRage/pull/1304/files

**Comment by fernandog** [comment]
@SpecialKeezie any luck?

**Comment by SpecialKeezie** [comment]
Sorry just got home from work. The RARBG link actually worked! I looked for a link to their RSS feed last night and couldn't find it, so thank you for providing that

@abeloin , i will try applying that commit. I'm relatively new to GitHub, although no stranger to copying/pasting code, what would be the easiest way to apply the fix? pasting the change into the actual file, or is there a way to actually download the appropriate sickbeard.py file with the fix?

**Comment by abeloin** [comment]
@SpecialKeezie 

* Stop sickrage
* Open a SickRage.py in notepad.
* Insert the following at line 52:
```
if sys.version_info >= (2, 7, 9):
    import ssl
    ssl._create_default_https_context = ssl._create_unverified_context

```
* Start sickrage and test

**Comment by SpecialKeezie** [comment]
@abeloin Added the commit, tried adding Extra Torrent again (since i knew it was one that for sure gave the error every time), and lo and behold it works now. Thank you so much for your help
