### ISSUE TITLE
Scene numbering not updating.

### ISSUE THREAD

**Issue by Alebran** [SiCKRAGETV/sickrage-issues#597]
I have two shows (Pawn Stars and Bar Rescue) that require scene numbering, the problem is that the scene numbering hasn't been updated for the last few shows which has caused them to not get picked up. See attached image.

![pawn stars](https://cloud.githubusercontent.com/assets/11000898/6198031/76751d22-b3ae-11e4-98a1-2572e97dbd09.jpg)

I am in the developmental branch
BRANCH: (develop) / COMMIT: (c62d8f2c799edd7daad5648f45276a3464d83a9e)

**Comment by abeloin** [comment]
The scene numbering is handled by [theXEM module](http://thexem.de).

Looking at XEM website it stop at 12x6 so until they update their data it will stay like this. You can create an account and update the data if you want.

Ref:
* http://thexem.de/xem/show/1759
* http://thexem.de/xem/show/1737
