### ISSUE TITLE
 Error Sending Tweet: error [{u'message': u'Status is over 140 characters.', u'code': 186}]

### ISSUE THREAD

**Issue by iamascientician** [SiCKRAGETV/sickrage-issues#598]
I am getting the following error during post processing:

 Error Sending Tweet: error [{u'message': u'Status is over 140 characters.', u'code': 186}]

SR Version:  BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8) 
Python Version: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/
