### ISSUE TITLE
Unable to match Hawaii Five-0 Regex on Fetching from RSS and PostProcessing

### ISSUE THREAD

**Issue by tcraib** [SiCKRAGETV/sickrage-issues#599]
Sick Rage is unable to match the Hawaii Five-0 regex when looking at an RSS feed and when attempting to PostProcess the downloaded file. The Post procesing says completed successfully but the file is not moved and renamed to the correct location but remains in the download folder.

Looking at the RRS feed Debug Log:
>2015-02-14 11:13:06 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Nzb.is] :: Unable to parse the filename Hawaii.Five-0.2010.S05E15.HDTV.x264-LOL into a valid show
>2015-02-14 11:13:06 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Nzb.is] :: Using ALL regexes
>2015-02-14 11:13:06 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Nzb.is] :: Attempting to add item from RSS to cache: Hawaii.Five-0.2010.S05E15.HDTV.x264-LOL

>2015-02-14 11:13:05 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [SceneTime] :: Unable to parse the filename Hawaii.Five-0.2010.S05E15.720p.HDTV.X264-DIMENSION into a valid show
>2015-02-14 11:13:05 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [SceneTime] :: Using ALL regexes
>2015-02-14 11:13:05 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [SceneTime] :: Attempting to add item to cache: Hawaii.Five-0.2010.S05E15.720p.HDTV.X264-DIMENSION

Looking at PostProcessing DebugLog
>2015-02-14 11:39:35 DEBUG    Thread-563 :: Using ALL regexes
>2015-02-14 11:39:35 DEBUG    Thread-563 :: Using ALL regexes
>2015-02-14 11:39:35 DEBUG    Thread-563 :: Processing folder Hawaii.Five-0.2010.S05E15.HDTV.XviD-AFG
>2015-02-14 11:39:35 DEBUG    Thread-563 :: PostProcessing VideoInRar: []
>2015-02-14 11:39:35 DEBUG    Thread-563 :: PostProcessing RarContent: []
>2015-02-14 11:39:35 DEBUG    Thread-563 :: PostProcessing VideoFiles: []
>2015-02-14 11:39:35 DEBUG    Thread-563 :: PostProcessing Files: []
>2015-02-14 11:39:35 DEBUG    Thread-563 :: PostProcessing Dirs: ['Hawaii.Five-0.2010.S05E15.HDTV.XviD-AFG']

**Comment by abeloin** [comment]
Please consult the following on what to provide when opening an issue: https://github.com/SiCKRAGETV/sickrage-issues
* Please provide complete logs. 
* What's the scene name exceptions for that show? You should have at least 'Hawaii Five-0 2010'
