### ISSUE TITLE
Sickrage doesn't download found nzbs from Usenet Crawler

### ISSUE THREAD

**Issue by Gobbomaster** [SiCKRAGETV/sickrage-issues#601]
Hi,

Episodes are currently not downloaded when using Usenet Crawler. A manual search results in the following log. As you can see the provided links are valid and yield results, I can't find out why none of the nzbs are actually downloaded.

Log
http://pastebin.com/W4BDd3Uj

Software:
BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb) 
Python Version:	2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]

**Comment by fernandog** [comment]
Please follow guidelines
 https://github.com/SiCKRAGETV/sickrage-issues/issues

**Comment by Gobbomaster** [comment]
Did I still miss things?

**Comment by fernandog** [comment]
No

**Comment by fernandog** [comment]
what qualities are you searching for?
Can you provider the XML result of the search URLl? I don't have an API for that indexer.

**Comment by neoatomic** [comment]
Add an API key. Looks like to be missing.

**Comment by fernandog** [comment]
@neoatomic I think he removed to post the log. If not we need to add a check for empty API

**Comment by Gobbomaster** [comment]
I don't see any option to put in an API under Search Providers - Provider Options. Used the standard Usenet-Crawler.

There are no required or ignored words for this show. Where can I check if I have proper enabled? Don't think I did, since I have to ask.

I'm searching for 720p, so it seems to me that there are six viable candidates.

**Comment by fernandog** [comment]
Enable Usenet-Crawler, go to Provider Options and refresh page
![1](https://cloud.githubusercontent.com/assets/2620870/6216815/941ff58e-b5f4-11e4-9053-02df94c974fe.png)

**Comment by Thraxis** [comment]
I use Usenet-Crawler and I have been getting shows from it.  More often then not the show grabs from a torrent source first, but I do still have shows that sometimes get snatched via Usenet-Crawler

**Comment by fernandog** [comment]
Do you have an api? Just need to register.

**Comment by fernandog** [comment]
now UC says: parameter missing. You need an API

**Comment by Gobbomaster** [comment]
Updated to the last version. Now the API field appeared (already filled), but nzbds are being snatched. Thanks!

**Comment by phirestalker** [comment]
> I use Usenet-Crawler and I have been getting shows from it. More often then not the show grabs from a torrent source first, but I do still have shows that sometimes get snatched via Usenet-Crawler

I have also noticed this BUG. I have the NZB search providers at the top in the priority list and STILL it grabs torrents first without even searching NZBs. Does anyone know how to fix this BUG??
