### ISSUE TITLE
Unable to connect to TorrentBytes provider

### ISSUE THREAD

**Issue by lsborg** [SiCKRAGETV/sickrage-issues#604]
First of all, thanks for providing SickRage! 

After realizing the open trackers are not working, I joined TorrentBytes and on the first try, after joining and configuring the provider, I got the error: 

    2015-02-14 17:53:27 SEARCHQUEUE-BACKLOG-269650 :: [TorrentBytes] :: Unable to connect to TorrentBytes provider: error HTTPSConnectionPool(host='www.torrentbytes.net', port=443): Max retries exceeded with url: /takelogin.php (Caused by : [Errno 110] Connection timed out)
 
BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb) 
Ubuntu LTS 12.04
Python Version:	2.6.5 (r265:79063, Feb 27 2014, 19:43:51) [GCC 4.4.3]
[debug log](http://pastebin.com/aeyBq88h)

ps: I checked all the open trackers and nothing is being snatched. Should I create another issue for this? The trackers are: 
ThePirateBay
KickAssTorrents
NyaaTorrents
EZRSS
TokyoToshokan
NextGen

**Comment by fernandog** [comment]
@lsborg [Errno 110] Connection timed out

maybe the site is having some problems

**Comment by lsborg** [comment]
It is accessible via browser (https://www.torrentbytes.net/takelogin.php, i get a 200 on a simple GET). I'm not using a proxy.

**Comment by lsborg** [comment]
Is [this](https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/providers/torrentbytes.py) timeout in seconds or milliseconds? 

    response = self.session.post(self.urls['login'], data=login_params, timeout=30, verify=False)

**Comment by fernandog** [comment]
Seconds

**Comment by fernandog** [comment]
Can you login in the browser?

**Comment by lsborg** [comment]
yes.

**Comment by fernandog** [comment]
"4 failed login attempts within 30 minutes will get your ip banned for 24 hours ! 
"

your browser and SR shares the same IP?

**Comment by lsborg** [comment]
Not the same IP. SR is in a server.

**Comment by lsborg** [comment]
I just logged in via browser. It should have zeroed my failed attempts.

**Comment by fernandog** [comment]
No. Ban is IP not username

**Comment by abeloin** [comment]
Try wget or curl to torrentbytes from your server.

**Comment by lsborg** [comment]
Got 200.

**Comment by abeloin** [comment]
Have you tried wget or curl with https://www.torrentbytes.net/takelogin.php?

**Comment by lsborg** [comment]
wget gave me 200, i also did a curl -d which worked.

**Comment by abeloin** [comment]
Ok, looking at the code it look like they change some code:
* Change the value of line 84 from 'submit' to 'Log in!'

**Comment by lsborg** [comment]
Part of the response, using curl: 

>03:55:54.932638 < HTTP/1.1 302 Moved Temporarily
>03:55:54.932710 < Server: nginx/1.7.4
>03:55:54.932743 < Date: Sat, 14 Feb 2015 21:59:36 GMT
>03:55:54.932779 < Content-Type: text/html
>03:55:54.932814 < Transfer-Encoding: chunked
>03:55:54.932848 < Connection: keep-alive

I tested and it made no difference. Unless curl keeps the auth cookies, does it?

**Comment by abeloin** [comment]
> I tested and it made no difference. Unless curl keeps the auth cookies, does it?
 I don't think so

**Comment by lsborg** [comment]
I used: 

>curl -v --trace-time -d "username=user&password=pass&login=submit" https://www.torrentbytes.net/takelogin.php

**Comment by abeloin** [comment]
Ok but you need to change the login parameter to 'Log in!' as per my previous comment.

**Comment by lsborg** [comment]
It worked, but i don't get how?! Why haven't curl failed??

**Comment by abeloin** [comment]
Because it return a blank page if the validation fail because it's missing the returnto = "/" in the parameters.

**Comment by fernandog** [comment]
@lsborg  develop updated. please test and report back

**Comment by lsborg** [comment]
@fernandog, it is working. 
Got upstream/develop from commit 431d04de4a4072d64e05d34b6a81e1ba963106ac. Added torrentbytes provider, a show and successfully snatched an episode.
