### ISSUE TITLE
Email does not work after download is finished

### ISSUE THREAD

**Issue by Hit-Bug** [SiCKRAGETV/sickrage-issues#605]
I have a server running freenas and sickrage in a jail running the normal PBI. I have everything working but the email is not functioning as it should be, I'm on the master branch, I don't know how to get the commit hash, the python version is 2.7.8 and what I did is install sickrage from freenas plugins, set it up  through the settings in sickrage and that's it. What I expected was that the email would work but it fails as displayed in the error logs LINK: http://pastebin.com/Jjbycn8E and there is weird error here, I tried the dev branch when I searched for a solution but that failed miserably, logs for that here LINK: http://pastebin.com/JVgcn3aj

**Comment by abeloin** [comment]
Sickrage is trying to connect to the smtp server but it doesn't reply in the allotted time hence the time out.

Check your settings in sickrage's email notifications section.

**Comment by Hit-Bug** [comment]
The settings are fine, the test email passes. Problem persists

**Comment by abeloin** [comment]
I've tested it with master and dev with gmail and it worked as intended.

Maybe your provider limit the number of emails you can send per short amount of time? What's your smtp provider?

**Comment by Hit-Bug** [comment]
My provider is my own service, there is no limit.

**Comment by fernandog** [comment]
@Hit-Bug are you on develop or master?

**Comment by fernandog** [comment]
"TypeError: object of type 'NoneType' has no len()" error. this is duplicate

**Comment by abeloin** [comment]
@Hit-Bug Can you check you smtp server log when you get a time out? Check if your smtp reject the connection.

**Comment by Hit-Bug** [comment]
Config.ini as in sickrage?, the mail server is fine since it both works with receiving and sending messages.

**Comment by Hit-Bug** [comment]
If so, where would I find it?

**Comment by fernandog** [comment]
SickRage/config.ini

**Comment by Hit-Bug** [comment]
Ok, I found the problem, sickrage did not like port 587, so I used port 26 with TLS and it worked
