### ISSUE TITLE
"Waiting for SickRage to start again" - endeless loop

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#609]
I checked for updated and click "update"
NO logs available

Performing Restart
Waiting for SickRage to shut down: OK 
Waiting for SickRage to start again: LOOP

Chrome developer tools:
 Failed to load resource: net::ERR_CONNECTION_REFUSED
http://ip:port/home/is_alive/?callback=jQuery1112007155770272947848_1424046820294&_=1424046820298

```
SR Version:	BRANCH: (develop) / COMMIT: (20a56d6edf4b41afafd195cac196d81f3ca09629) 
SR Config file:	/home/pi/SickRage/config.ini
SR Database file:	/home/pi/SickRage/sickbeard.db
SR Cache Dir:	/home/pi/SickRage/cache
SR Arguments:	['-q', '--daemon', '--nolaunch', '--pidfile=/var/run/sickrage/sickrage.pid', '--datadir=/home/pi/SickRage']
SR Web Root:	
Python Version:	2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]
```

**Comment by abeloin** [comment]
Confirmed. The system is up but the page doesn't refresh.

**Comment by fernandog** [comment]
@abeloin this should work! I don't know why but it don't. Maybe the ERR_CONNECTION_REFUSED is because of the new login page?

**Comment by abeloin** [comment]
Do you use firefox or chrome?

**Comment by fernandog** [comment]
Chrome

**Comment by fernandog** [comment]
@abeloin I can confirm it's a user/pass issue:

don't work:
http://localhost:8081/home/is_alive/?callback=jQuery ....bunch of number

work:
http://user:pass@localhost:8081/home/is_alive/?callback=jQuery ....bunch of number
jQuery111205912409231532365_1425068147201({"msg": "19748"});

**Comment by abeloin** [comment]
@fernandog Can you test the PR?

**Comment by abeloin** [comment]
@OmgImAlexis Can you test this PR: https://github.com/SiCKRAGETV/SickRage/pull/1435 ?

**Comment by OmgImAlexis** [comment]
@abeloin Fixed!

**Comment by maxcore** [comment]
yep working good !!!

**Comment by abeloin** [comment]
Thanks for the testing
