### ISSUE TITLE
[Feature Request] Set limit for max number of downloaded episodes.

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#61]
<a href="https://github.com/sy6502a"><img src="https://avatars.githubusercontent.com/u/5231556?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sy6502a](https://github.com/sy6502a)**
_Monday Dec 08, 2014 at 23:34 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/1061 (10 comment(s))_

----

Are there any plans to add a per show option to limit how many episodes are retained per show?

This is a fairly common feature on many DVRs.  It's often a setting in individual show recording options called "Keep at most: x". "x" being the maximum number of shows you ever want to keep for this show name.

Let's say you have 3 episodes of a show. If there were a option to limit the max retained shows (Keep at most: x) where "x" for this particular show is set to only 3, then when SickRage adds a new episode (4th show) it would delete the oldest of the 4. So you would only ever have the 3 newest episodes.

I see this as being an option on the "Edit" page of each individual show, where for example you could set a numeric value manually or from a drop down, where "All" would be the default.  SickRage would delete the oldest shows beyond this value located in the "Location" directory for this show, either using the file date or the SxxExx string in the filename.

This "Keep at most: x" option is a feature I currently have on my SageTV setup and have come quite used to.  For me, it's invaluable in helping to limit my hard drive filling up with shows I don't watch for one reason or another, and having to tediously delete manually.

Thanks for your consideration.

**Comment by gborri** [comment]
@markheloking hello i'm trying to make pull request for every change in my repo.
first one is pull #1311

**Comment by fernandog** [comment]
@gborri can we close this?

**Comment by gborri** [comment]
@fernarnandog I think you could close; but please, just to be sure, ask to
the person that have open it.

**Comment by fernandog** [comment]
@sy6502a check the feature @gborri implemented (I'm still waiting for the wiki explaining it)

**Comment by sy6502a** [comment]
@fernandog Thanks for the message.  I've reviewed the whole thread again.  I can't say I've can follow how the feature will be implemented. From the comments, it seems to have morphed from my original request to possibly using a service (that I don't use) called Trakt, or possibly no longer downloading new episodes if the old ones weren't watched.  Unless I'm not following.  And I don't think this feature has been pushed out yet, from what I can tell.  

My request was to continue to download new episodes, and delete old ones, so you always retain X number of newest episodes.  That's the standard DVR feature often called "Keep at Most" that I'm used to.  But one comment implied that it will do the reverse, stop downloading if old shows aren't watched.  I guess I'll wait to see what gets implemented.

I actually wrote a script in Python that does what I need.  Checks on a regular basis all my episode directories, and deletes episodes based on settings in an ".ini" file found in that directory.  Will delete episodes older than X days, or retain only the newest X number of episodes.  It also purges orphaned meta data files if the actual video file has been deleted.

You can close the thread when you like.  I'll check for the feature when it's pushed out, and see how it's been implemented.  

Thanks.

**Comment by gborri** [comment]
@sy6592a i think that delete file not watched is not useful.
@fernandog to bypass trakt plugin we have to implement #1063 and a plugin for mediacenter software for change status on sickrage upon episode watched.

**Comment by fernandog** [comment]
removed from SR
