### ISSUE TITLE
[APP SUBMITTED]: 'uid'

### ISSUE THREAD

**Issue by polysa** [SiCKRAGETV/sickrage-issues#613]
### INFO
Python Version: **2.7.6 (default, Nov 10 2013, 19:24:24) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@93f0f0ad1fa278afb17f73d47c099b82a766dede
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [FreshOnTV] :: Unable to obtain cookie for FreshOnTV
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@polysa can you senf full logs please?

**Comment by flightlevel** [comment]
Fair chance its related to 
https://github.com/SiCKRAGETV/sickrage-issues/issues/504

**Comment by fernandog** [comment]
Sure! @abeloin can we merge this one? https://github.com/SiCKRAGETV/SickRage/pull/1326

**Comment by abeloin** [comment]
@fernandog Merged in develop

**Comment by fernandog** [comment]
@polysa update and report back
