### ISSUE TITLE
[Synology] Restore from menu not working

### ISSUE THREAD

**Issue by dirkr07** [SiCKRAGETV/sickrage-issues#614]
Due to some manual changes of the files I was unable to run the auto update. To be quick I took a backup of my environment (through the menu) and re-installed from scratch (discarding my changes and going immediately to the latest commit)

However, when trying to restore my backup I get the message stating the files have been unzipped properly to the /restore folder (which I verified) and that I should restart SR to apply the changes.

When I restart however, no files are changed and I'm left with a blank/fresh install.

I can manually copy the sickrage.db & config.ini file through SSH and then chmod/chown the rights. This seems to work as a workarround.

The logs do not seem to show anything about failures to copy the files over.

I'm on BRANCH: (master) / COMMIT: (93f0f0ad1fa278afb17f73d47c099b82a766dede) 
Python version: 2.7.8 (default, Dec 12 2014, 22:18:04) [GCC 4.3.2]

**Comment by fernandog** [comment]
When you restored did you checked the restored file permissions? Did you restored cache folder too?

**Comment by dirkr07** [comment]
The files in the restore folder are set to 600 

-rw-------    1 sickbear root         14176 Feb 16 13:55 config.ini
-rw-------    1 sickbear root       4968448 Feb 16 13:55 sickbeard.db

After the restart that SR asks (after the decompression) the files in the main folder are still on their original rights but have not been changed.

![image](https://cloud.githubusercontent.com/assets/10185229/6212651/0eb35bfe-b5e8-11e4-8881-5baed58d6b60.png)

I did not restore the cache folder, I just used the builtin backup/restore functionality which does not include the cache.
After I manually copy the files from the restore folder and adjust the rights/owner my db and config are back.

**Comment by fernandog** [comment]
The new backup function backup cache folder

**Comment by dirkr07** [comment]
But how would that impact the config and db file not being overwritten with the correct file?
After I manually restore the files it's fine again and I didn't touch any cache folder. 

Sure now it's re-downloading all the info but I don't mind that.

**Comment by abeloin** [comment]
Look in log file for: Restore FAILED! or Restore successful...

**Comment by dirkr07** [comment]
For due dilligence I did another restore (on my already updated install) and nothing seems to happen.
I had the message "shutting down"
Then the message "waiting to start again" and after a few minutes I just refreshed the page.

Within the logs I got the following 

2015-02-16 16:31:20 INFO     EVENT-QUEUE :: Restarting SickRage with ['/usr/local/sickbeard-custom/env/bin/python', '/usr/local/sickbeard-custom/var/SickBeard/SickBeard.py', '--daemon', '--pidfile', '/usr/local/sickbeard-custom/var/sickbeard-custom.pid', '--config', '/usr/local/sickbeard-custom/var/config.ini', '--datadir', '/usr/local/sickbeard-custom/var/', '--nolaunch']

So I'm sure the restart went through.
However, nothing comes up with "Restore"/"Failed"/successfull in it so I'm guessing it's just not doing anything (besides restarting)

I have no idea what the trigger is for SR to copy these files over but I'm guessing the trigger is not triggered/set on restart?

**Comment by abeloin** [comment]
SickBeard.py Line 265 It check if a folder named restore exists then proceed to restore

**Comment by fernandog** [comment]
@abeloin 
I tested on a windows and it restores to SickRage/restore
It extracts with absolute path not relative. So all cache folder files are together with sickrage.db and config.ini in /restore

**Comment by dirkr07** [comment]
@fernandog Maybe I misrepresented the issue. The files are extracted to the /restore folder but after a restart its not copying/moving them to the real directory

**Comment by abeloin** [comment]
@fernandog PR https://github.com/SiCKRAGETV/SickRage/pull/1164 broke the restore process

**Comment by fernandog** [comment]
@abeloin I don't think so. I only added more files to the ZIP. I didn't changed the restore process

**Comment by dirkr07** [comment]
Guess i'm not imagining things then. 
So I guess bug confirmed? :)

**Comment by abeloin** [comment]
It does in the console. Have a look at https://github.com/SiCKRAGETV/SickRage/blob/develop/SickBeard.py#L450 That's the restore function. It try to backup the file first which fail as the cache file doesn't exist in sickrage's root. Also the files are extracted from the zip are without path.

**Comment by fernandog** [comment]
the backup runs ok. My zip has the cache folder and config.ini sickbeard.db
the problem is the restore it self.
I would just move everything to SickRage folder with the condition that zip file its absolute path.

**Comment by fernandog** [comment]
@abeloin

**Comment by abeloin** [comment]
@fernandog It will still fail in the restore function in SickBeard.py as it need to be modified also.

**Comment by fernandog** [comment]
@abeloin I extract the zip into /Restore and it worked. SR made a directory cache.bak and everything working. The problem is the SR don't extract with absolute path. If you change this, will work.

**Comment by dirkr07** [comment]
Is it of significance that my backup is from before the cache folder was included and the restore after it was added?

**Comment by fernandog** [comment]
@dirkr07 yes. should have worked. the change was only in the backup feature.

**Comment by abeloin** [comment]
@dirkr07 Can you test this commit: https://github.com/abeloin/SickRage/commit/97ade6ad6c90ead4f87f631c30fe3d81d348b349 ?
You'll need to switch the dev branch to test it.

**Comment by abeloin** [comment]
@fernandog Added new commit(Added failed.db and cache.db) to branch https://github.com/abeloin/SickRage/tree/patch-backup_restore

**Comment by fernandog** [comment]
@abeloin worked! thanks!

**Comment by abeloin** [comment]
@fernandog PR created https://github.com/SiCKRAGETV/SickRage/pull/1345

**Comment by FoxBJK** [comment]
I realize this bug was closed months ago, but I'm having this exact same issue. I ran a backup on my OS X machine running SR, and tried to restore onto my Synology. Exactly like everyone's describing above, the backup archive gets unzipped successfully, but by the time SR restarts, the "restore" folder is gone but my settings are not back in place.

Nothing in the logs for SR, not sure where to check on the Synology for any logs. Let me know what you need and I'll provide it.
