### ISSUE TITLE
Download status categorie showing blue color instead of green

### ISSUE THREAD

**Issue by Koal4** [SiCKRAGETV/sickrage-issues#617]
Hi,

The latest update introduced a small bug (at least that's what I think). The downloads categorie is showing the blue color with the light skin. I checked the dark skin and it's still green there.

![sickrage](https://cloud.githubusercontent.com/assets/10795027/6217287/b805be16-b612-11e4-875a-7aa850c47dd1.png)

**Comment by fernandog** [comment]
not a issue. now when is 100% its blue. green is for incomplete

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/322

**Comment by Koal4** [comment]
I'm sorry but why are my 100% shows in the dark theme green and not blue like you suggest.

Also I prefer green as it was always green in the past. Green is kind of the silent color symbol of 'everything is ok' / 'accepted'. See the green checkmarks or even the green comment button below ;
)

**Comment by fernandog** [comment]
Because in the light theme font is black. And a darker green there is no contrast in with the font. You can try to modify as you please. its good we will merge

**Comment by Koal4** [comment]
Sorry again but i kinda disagree as this wasn't an issue with older versions so don't understand the need to change it now. Also  2 different colors are used now in different themes what makes it extra confusing. If it were up to me those colors should be the same in every theme you use.

**Comment by fernandog** [comment]
there was no 100% before. So we need new color

**Comment by Koal4** [comment]
Well sorry but i still disagree with you there.

Green color with a black font wasn't an issue with older versions. Besides that there are probably 10000 different colors green too choose from if needed. I find it highly unlikely that you cant find a matching color from there but then again it never was a problem in the past.

What I"m trying to make a point here is that you use 2 different colors for the same function in 2 different themes. Also the color blue doens't make me feel that something is 100% done/complete like the color green gives. Like i said earlier if a color is used to show something is 100% done mostly the color green is choosen and the color red is used to show something it was not done 100%. 

Also the color blue is used in the episode list for 'skipped' episodes. I hope you understand what i'm trying to address here. If you want to use colors to highlight certain progress then use the same color everywhere. The point of using colors is to show the user quickly what is good and what might be wrong. In this scenario it will be are all shows grabbed/proper quality/missing episodes etc etc

**Comment by fernandog** [comment]
@Koal4 can you test it? stop SR, replace that file, start again

**Comment by fernandog** [comment]
@Koal4 merged in develop. please try and report back

**Comment by Koal4** [comment]
@fernandog wasn't at home earlier so i just tested this and it works fine and looks normal again, thanks for this and listening :)
