### ISSUE TITLE
Check scene exceptions update failed

### ISSUE THREAD

**Issue by mbnoimi** [SiCKRAGETV/sickrage-issues#619]
I get this error after updating to recent version:

`````
2015-02-17 00:18:49 SEARCHQUEUE-BACKLOG-259765 :: Check scene exceptions update failed. Unable to get URL: http://midgetspy.github.io/sb_tvdb_scene_exceptions/exceptions.txt
`````

- SR Version: 	BRANCH: (master) / COMMIT: (93f0f0ad1fa278afb17f73d47c099b82a766dede)
- SR Arguments:	['--nolaunch']
- Python Version:	2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]
- OS: Linux Mint Cinnamon x64  version 17

**Comment by mbnoimi** [comment]
BTW, I could access [exceptions file](http://midgetspy.github.io/sb_tvdb_scene_exceptions/exceptions.txt) manually using the browser.

**Comment by fernandog** [comment]
maybe timeout thing. my git is really slow now.
did it happen again?
