### ISSUE TITLE
"Improved rTorrent support." broke my rTorrent Connection.

### ISSUE THREAD

**Issue by acecon** [SiCKRAGETV/sickrage-issues#625]
Develop Branch
Issue with commit:
"3166f29d345141062a9ec971f4349570e1b134ce"

Unfortunately, there were no error logs displayed. I also have debug enabled.
The Info log would say:
"INFO SEARCHQUEUE-DAILY-SEARCH :: Downloading xxxx from IPTorrents."
and nothing else would happen.

In the Torrent Search tab in Settings, I would get a connection error after pressing the 'Test Connection' button.

My rTorrent host:port: 
"https://xx.xx.xx.xx:80/rutorrent/plugins/httprpc/action.php"
I chose various options in the Torrent Search settings to make it work but to no avail.

I reverted back to commit:
"90aff1d6c9da7d870a0c3b8fe0b55a8490d9c3ac"
Connection to rTorrent is working again.

**Comment by fernandog** [comment]
@acecon please send FULL logs so we can trace the error from test connection

**Comment by abeloin** [comment]
@acecon Are you using http or https? Because your string contain https and port 80 whch is strange.

My guess is that you are using http as https was not supported before(previous implementation ignored the https and converted it to http):
* Fix the url to http://xx.xx.xx.xx:80/rutorrent/plugins/httprpc/action.php
* If you use authentication, set to Basic. If not leave to none
* Enter user/pass if auth set to Basic

**Comment by acecon** [comment]
@abeloin I removed the 's' in https & the port #, & chose Basic authentication.

http://xx.xx.xx.xx/rutorrent/plugins/httprpc/action.php

That solved the issue.

I knew https & port 80 was a strange combination, but I think it was the only way I was able to connect to rTorrent while still using SSL when I first set this up. I never did check whether or not sickrage sent snatched torrents to rTorrent with https.

I replaced port 80 with 443 using https but still received connection error, so I removed port # altogether & just kept http.

So what steps should I take if I want sickrage to send snatched torrents using ssl?
I am able to log into ruTorrent with https in my browser.

**Comment by abeloin** [comment]
In your web browser, type https://xx.xx.xx.xx/rutorrent/plugins/httprpc/action.php: it should ask you for your username and password(maybe unsecured connection first if certificate is self-signed). You should see the word false in your browser.

1. Use https://xx.xx.xx.xx/rutorrent/plugins/httprpc/action.php
2. If you use self-signed ssl uncheck verify SSL
3. Choose basic as your authentication.
4. Enter username and password
![Imgur](http://i.imgur.com/uPQjciD.png)

**Comment by acecon** [comment]
I added back https, did not specify a port #, & unchecked "verify certificate".

Problem Solved!

I guess I assumed Verify Certificate had to be checked for self-signed certificates.

Thanks @abeloin

**Comment by abeloin** [comment]
Verify certificate is for a certificate that is signed by a recognized entity which self-signed aren't.
