### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: u'Z:\\done\\The.Originals.S02E14.HDTV.x264-LOL[rarbg]\\the.originals.214.hdtv-lol.mp4'

### ISSUE THREAD

**Issue by bitzorro** [SiCKRAGETV/sickrage-issues#627]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **fernandog-double-quote**
Commit: SiCKRAGETV/SickRage@aeef329bff80f4f2b64261e12c631792d6119b2b
### ERROR
```
POSTPROCESSER :: Unable to copy file Z:\done\The.Originals.S02E14.HDTV.x264-LOL[rarbg]\the.originals.214.hdtv-lol.mp4 to Z:\Multimedia\movies\Tv Serier\The Originals\Season 02\the.originals.214.hdtv-lol.mp4: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by TagForce** [comment]
@bitzorro Can you tell me what settings you use for post processing?
Is delete rar contents on?
What Process Method do you use?

**Comment by bitzorro** [comment]
Im not using delete rar contents, post processing is set to copy every 100 min.

**Comment by fernandog** [comment]
@bitzorro why did you change the branch to this one? that branch does not exist anymore.

**Comment by fernandog** [comment]
@bitzorro is this path correct? 
"Z:\Multimedia\movies\Tv Serier\" ?

**Comment by fernandog** [comment]
@bitzorro please reply or we will close

**Comment by bitzorro** [comment]
Yes the path is correct, the sam error came again to day.
the torrent was in rar, after unpacking it doesnt move the file And the same error occour.
using the latest develop branch.

@fernandog

**Comment by fernandog** [comment]
@bitzorro
reply this please
https://github.com/SiCKRAGETV/sickrage-issues/issues/627#issuecomment-74637726

**Comment by bitzorro** [comment]
?

@fernandog

**Comment by fernandog** [comment]
@bitzorro Can you tell me what settings you use for post processing? What Process Method do you use?

**Comment by bitzorro** [comment]
Only unpack and copy.

**Comment by fernandog** [comment]
@bitzorro do you use transmission?
do you have enabled transmission option to add .part to incomplete files?
do you have a separated folder to incomplete and complet at transmission (you should)

**Comment by bitzorro** [comment]
Im using Utorrent and separated folders.

**Comment by fernandog** [comment]
@TagForce your new PR fixes this too?

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1417

**Comment by fernandog** [comment]
@bitzorro can update develop and try again?
