### ISSUE TITLE
Sickrage .ignore?

### ISSUE THREAD

**Issue by TimVNL** [SiCKRAGETV/sickrage-issues#628]
I have both Sickrage and Couchpotato installed on my Synology NAS but I have a issue if a episode is downloaded by sickrage a .ignore is add to the folder what results in episode not being moved....

I have to following settings actove in Post Processing in Sickrage:
- move Associated Files
- Postpone post processing
- Rename .nfo file
- Rename Episodes
- Scan and Process

What am I doing wrong? Is Couchpotato causing a conflict because it's auto post processing also?

SR Version:	BRANCH: (master) / COMMIT: (93f0f0ad1fa278afb17f73d47c099b82a766dede)

**Comment by fernandog** [comment]
@TagForce is the postpone setting?

**Comment by TagForce** [comment]
@TimVNL @fernandog No. As far as I know SR doesn't respond to .ignore files.
Can you provide a log of a post process run?

**Comment by TimVNL** [comment]
Can't find any logs... Can it be that Couchpotato is generating them?

**Comment by TagForce** [comment]
@TimVNL The ignore files? Most definitely generated by CP.
The logs? No, SR generates logs and if you have Scan and Process checked in the config, it should generate post processing entries in the log every 'scan frequency' minutes. Check the logs and errors page for them.
By default the logs are stored in %SICKRAGE%/logs folder.Upload the one containing the entries (or the part that has the entries) to pastebin. We can probably figure out where it goes wrong by the messages it generates.

**Comment by TimVNL** [comment]
Will look into it today..... But if CP generates .ignore files does Sickrage still moves the file?

**Comment by TagForce** [comment]
@TimVNL This line tells SR what a syncfile is:
if extension == '!sync' or extension == 'lftp-pget-status' or extension == 'part' or extension == 'bts':

As you can see there's no .ignore in the list, so it should simply ignore the file and continue Post Processing.

**Comment by TimVNL** [comment]
Here is a log from this night https://gist.githubusercontent.com/TimVNL/96534280d61dfaf01f58/raw/Sickrage-log20150219

Again is I stop and start Sickrage Post Processing... Should I try the develop branch?

**Comment by abeloin** [comment]
Extracted the relevant information:
```
2015-02-18 23:10:08 DEBUG    POSTPROCESSER :: File /volume1/Video/T.V. Series/The Simpsons/S26E14 - My Fare Lady.mkv is larger than /volume1/Downloads/The.Simpsons.S26E14.HDTV.x264-LOL[ettv]/the.simpsons.2614.hdtv-lol.mp4
2015-02-18 23:10:08 DEBUG    POSTPROCESSER :: File exists and new file is smaller, marking it unsafe to replace
2015-02-18 23:10:08 WARNING  POSTPROCESSER :: Processing failed for /volume1/Downloads/The.Simpsons.S26E14.HDTV.x264-LOL[ettv]/the.simpsons.2614.hdtv-lol.mp4: 
```

The file already exists

**Comment by TimVNL** [comment]
Nevermind this log Sickrage did't start a download until 6:00 new log following...

 New Log not needed it'a working again for now all I disabled the Propers function that seems te be the issue...

Will monitor if it keeps working... Fixed for now.

Still want to see the log file here it is for the complete info: https://gist.github.com/TimVNL/9412f0678a8ec24f1df6
