### ISSUE TITLE
Default EP Status: not working

### ISSUE THREAD

**Issue by wizzardking** [SiCKRAGETV/sickrage-issues#629]
branch: tested with master & develop
Commit: the newest commits on 17.2.15
Os: linux (intel qnap x86_64)

If I edit a Serie and change the "Default EP Status" to "ignored", when the ep releasedate is received the new episode will still be added as Wanted in SR.

**Comment by fernandog** [comment]
that's the expected result. 
SR uses the default ep status when adding a new tv-show
you must set IGNORE the ones that you don't want
