### ISSUE TITLE
ThePirateBay season search is broken

### ISSUE THREAD

**Issue by yaymuffins** [SiCKRAGETV/sickrage-issues#631]
Hello, 

Since yesterday it seem like ThePirateBay doesn't have a file list anymore, as a result, I get tons of error saying "2015-02-17 10:57:01 SEARCHQUEUE-BACKLOG-2594 :: [ThePirateBay] :: Unable to get the torrent file list for "NameOfTheTorrent"

Branch: Master
Commit: 93f0f0ad1fa278afb17f73d47c099b82a766dede
Debian 7.8 / Python 2.7.3
I added a new show and expected SR to start download it.

**Comment by hoefs** [comment]
Have the same issue!

**Comment by Wyth** [comment]
I just installed sickrage yesterday, so I figured it was something I did. But I've been running into this ever since then too.

**Comment by fernandog** [comment]
@mwarnaar do you have this issue too ? as you PR TPB new code

**Comment by mwarnaar** [comment]
Yeah I get this as well.
The pirate bay's `ajax_details_filelist.php` call only seems to return "File list not available.", so season search mode will not do much using TPB at the moment.
See SiCKRAGETV/SickRage#1359.

**Comment by fernandog** [comment]
@yaymuffins @hoefs please update and report back

**Comment by raymondtrueman** [comment]
Hi @fernandog - Has this issue been solved? I am getting the same error messages since I enabled Pirate Bay

**Comment by fernandog** [comment]
@raymondtrueman fixed on develop

**Comment by raymondtrueman** [comment]
So I can use the new TPB provider or should I switch to the old one?
@fernandog

**Comment by fernandog** [comment]
new TPB is already on master
but new tpb don't work with season mode. so apply this to your local file:
https://github.com/SiCKRAGETV/SickRage/pull/1359/files
