### ISSUE TITLE
freshon.tv - backlog processing skipping episodes

### ISSUE THREAD

**Issue by happypaps** [SiCKRAGETV/sickrage-issues#632]
hello!
new user here, and loving SR so far. I have run into an issue when i'm processing backlogged episodes where not all the eps are snatched. Show in question is Marvel's Agents of S.H.I.E.L.D S02, Reviewing the debug log SR searches for the episodes which only results in eps 6-10 being found which are then downloaded. Auto and manual backlog processing then states "no needed episodes found", even though eps 1-5 are still listed as "wanted". Second attempt was with show Supernatural S10, SR snatched the last 4 episodes and the first episode, all other still marked "wanted" with "no episodes needed" message after auto and manual processing. I'm using freshon.tv as my provider and manually searching the site itself using the same search terms as SR I found all the wanted eps I was missing. Can't determine any rhyme or reason in regards to ep# or air date. Since the functionality is partly there I'm wondering if this is the result of some setting that I'm overlooking. Can anyone help? Posted SR info below, let me know if you need any other info. 

SR Version: BRANCH: (master) / COMMIT: (93f0f0ad1fa278afb17f73d47c099b82a766dede) 
SR Config file: C:\SickRage\config.ini 
SR Database file: C:\SickRage\sickbeard.db 
SR Cache Dir: C:\SickRage\cache 
SR Arguments: [] 
SR Web Root:  
Python Version: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]

**Comment by fernandog** [comment]
Add "Agents of S.H.I.E.L.D" and "Marvels Agents of S.H.I.E.L.D" to scene exceptions.

**Comment by happypaps** [comment]
thanks for your help fernandog. unfortunately I already explored this as a potential solution. these are my current exceptions for this show:
Marvel Agents Of SHIELD | Agents of S H I E L D | Marvels Agents of S H I E L D | Marvel's Agents of S.H.I.E.L.D | Marvel's Agents of SHIELD | Marvel's Agents of S H I E L D

I had the same issue with the shows grimm, and supernatural. both of which shouldn't require exceptions. I also did a manual search on the site itself which resulted in all needed episodes. It does appear that the backlog will only d/l ~4-5 episodes on its own until it results in "no needed episodes"

**Comment by happypaps** [comment]
here's my debug log after trying to manually process backlog for show Supernatural
http://pastebin.com/tZLGwUng

in reviewing freshon.tv search results I noticed that the only episodes downloaded by SR were results from the first page of results. is this the issue?

**Comment by happypaps** [comment]
here are screen caps of the search results using the SR backlog search terms. it does seem that SR is only pulling results from the first page and ignoring subsequent pages. is this a known issue?


![capture1](https://cloud.githubusercontent.com/assets/11044891/6230847/6646d49a-b688-11e4-907a-bf4c272e467d.PNG)
![capture2](https://cloud.githubusercontent.com/assets/11044891/6230846/6646b4c4-b688-11e4-8a28-2522d0000b47.PNG)
![capture3](https://cloud.githubusercontent.com/assets/11044891/6230849/6648f7d4-b688-11e4-99a0-205c0e3bc085.PNG)
![capture4](https://cloud.githubusercontent.com/assets/11044891/6230848/664879da-b688-11e4-8ec9-8a34b32b94be.PNG)
![capture5](https://cloud.githubusercontent.com/assets/11044891/6230850/66495760-b688-11e4-96b9-5206bf1ea15e.PNG)

**Comment by abeloin** [comment]
@happypaps That depend on how the provider was implemented

**Comment by happypaps** [comment]
could you explain? implemented when I added the provider to SR? or how its implemented in SR itself?

**Comment by abeloin** [comment]
In SR itself, I would have to look at the code but my guess it's pulling the first page only.

**Comment by flightlevel** [comment]
@happypaps  Login to Freshon via your web browser, then go to Profile. Change the number of torrents per page from 15 to 100.

**Comment by happypaps** [comment]
@flightlevel thanks for that tip! i wasn't even aware of this setting on the site. unfortunately i'm a new user and still at TV User status, stuck at 15 results per page. Once my user status switches over at 4 weeks this should help with this issue. Per @abeloin this may be able to be fixed in SR itself so whichever works is fine by me :)

**Comment by fernandog** [comment]
@nielsenj can you make the provider to use more than just one page?

**Comment by nielsenj** [comment]
If there is an example in an existing provider; i simply re-implemented one to make this.

Python isn't my strong suit.

**Comment by abeloin** [comment]
TNTVillage use page

**Comment by flightlevel** [comment]
@happypaps Can you give this update a go
https://github.com/SiCKRAGETV/SickRage/pull/1394

**Comment by happypaps** [comment]
@flightlevel will do! do i have to wait until this is merged into the dev build?

**Comment by fernandog** [comment]
@flightlevel can you add multi page to RARBG too??

**Comment by fernandog** [comment]
@happypaps no

stop SR
SSH/cmd and run:
cd SickRage
wget --no-check-certificate https://github.com/SiCKRAGETV/SickRage/pull/1395.patch
patch -p1 > 1395.patch
start SR
try to reproduce the error

**Comment by happypaps** [comment]
after entering the command "patch -p1 < 1395.patch"

i get this error 

"patching file sickbeard/providers/freshontv.py
Assertion failed: hunk, file ../patch-2.5.9-src/patch.c, line 354

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information."

i downloaded and installed gnu wget and gnuwin patch prior to attempting to install this patch. i'm pretty clueless when it comes to command line interface...

**Comment by fernandog** [comment]
@happypaps windows user?

open SickRage/sickbeard/providers/freshontv.pyfreshontv.py and paste this:
https://raw.githubusercontent.com/SiCKRAGETV/SickRage/a04d7b4dd71e00eae08f8846a53b6cafb63129ef/sickbeard/providers/freshontv.py

**Comment by happypaps** [comment]
@fernandog yup. any idea what I was doing wrong? 

I restarted my SickRage service following the failed update and the issue has resolved despite the errors. After your reply I performed the update manually as you described and the issue was still resolved. SickRage is accessing all pages on freshon.tv and all my backlog shows downloaded. thanks for everyone's help!
