### ISSUE TITLE
KAT backlog search is not working after upgrade

### ISSUE THREAD

**Issue by hoefs** [SiCKRAGETV/sickrage-issues#634]
I have updated to the latest version on my Synology DS411 and afterwards manual search and backlog search are not downloading anymore. I always get no

SR Version:	BRANCH: (master) / COMMIT: (93f0f0ad1fa278afb17f73d47c099b82a766dede) 
SR Config file:	/usr/local/sickbeard-custom/var/config.ini
SR Database file:	/usr/local/sickbeard-custom/var/sickbeard.db
SR Cache Dir:	/usr/local/sickbeard-custom/var/cache
SR Arguments:	['--daemon', '--pidfile', '/usr/local/sickbeard-custom/var/sickbeard-custom.pid', '--config', '/usr/local/sickbeard-custom/var/config.ini', '--datadir', '/usr/local/sickbeard-custom/var/', '--nolaunch']
SR Web Root:	
Python Version:	2.7.8 (default, Dec 12 2014, 20:09:05) [GCC 4.6.4]

examples:
http://pastebin.com/yFP9swsY

http://pastebin.com/uqyvj3V3

I will never find manual searches or backlog searches, new episodes were downloaded over the night. I have added Brooklyn Nine-nine to test, but it can't find any files...

**Comment by hoefs** [comment]
update1:

http://pastebin.com/M5A82XQV

and

http://pastebin.com/L7vDqYaW

Seems like it is a proxy issue, after troubleshooting and changing my DNS servers and removing all the proxy settings, the downloads start working again.

**Comment by hoefs** [comment]
Update2:

normal downloads are working without proxy. (proxy implementation seems broken)

season downloads seem broken in both ways (season torrents are not seen as season packs and skipped in debug logs)

**Comment by fernandog** [comment]
@hoefs check you provider settings for season mode

**Comment by hoefs** [comment]
I have tried both modes, only "episodes only" mode works, "season packs only" mode does not download anything, also I have fallback enabled.

**Comment by fernandog** [comment]
which provider?

**Comment by hoefs** [comment]
TBP and KAT
with proxy = both of them aren't downloading anything
without proxy = only single episode is working

![screen shot 2015-02-19 at 16 58 58](https://cloud.githubusercontent.com/assets/7440522/6270238/b67330e0-b858-11e4-9bd9-37fbc9e31a70.png)

**Comment by fernandog** [comment]
are you sure KAT does not work season download?

**Comment by hoefs** [comment]
2015-02-19 17:04:28 INFO     SEARCHQUEUE-BACKLOG-269586 :: FALLBACK SEASON PACK SEARCH INITIATED ...
2015-02-19 17:04:28 INFO     SEARCHQUEUE-BACKLOG-269586 :: Performing season pack search for Brooklyn Nine-Nine
2015-02-19 17:04:28 DEBUG    SEARCHQUEUE-BACKLOG-269586 :: Search string: https://kickass.to/usearch/Brooklyn+Nine+Nine+S01+-S01E+category%3Atv/?field=seeders&sorder=desc&rss=1
2015-02-19 17:05:14 DEBUG    SEARCHQUEUE-BACKLOG-269586 :: Result Brooklyn Nine Nine Season 1 Complete 720p.Web.Dl.Sujaidr have 11 episode and episodes retrived in torrent are 22
2015-02-19 17:05:14 DEBUG    SEARCHQUEUE-BACKLOG-269586 :: Result Brooklyn Nine Nine Season 1 Complete 720p.Web.Dl.Sujaidr Seem to be a Single Episode or MultiSeason torrent, skipping result...


checked the torrent, has 25 files, sickrage only sees 11... (for all btw)

**Comment by hoefs** [comment]
ok, I am wrong, it searches for 11 files and sees 22 in torrent... but why?

**Comment by hoefs** [comment]
http://pastebin.com/uwDudW6M

![screen shot 2015-02-19 at 17 14 04](https://cloud.githubusercontent.com/assets/7440522/6270494/ba1de8d2-b85a-11e4-8dd3-951992e0c047.png)

**Comment by fernandog** [comment]
Check your backlog search setting. It limits how far is a backlog search

**Comment by hoefs** [comment]
@fernandog I have never changed that setting and it always worked. When you look close at the logs, you will see that it finds season packs, but sickrage looks for 11 episodes and the torrent contains 22 episodes. The 22 is correct... but why does sickrage only wants 11?

Result Brooklyn Nine Nine Season 1 Complete 720p.Web.Dl.Sujaidr have 11 episode and episodes retrived in torrent are 22

![screen shot 2015-02-19 at 18 55 24](https://cloud.githubusercontent.com/assets/7440522/6272591/0c05c472-b869-11e4-8dbc-064e36c5f379.png)

**Comment by fernandog** [comment]
@hoefs 
so it's only searching episodes from year 2014?
can you make a test and set WANTED another episode from another show that airdate year is 2013?

**Comment by hoefs** [comment]
@fernandog here is the complete search
http://pastebin.com/htsfsqgm

the problem is not that it does not fins episodes... it does not want to download season packs. It finds the season packs, but the amount of files is always wrong in the torrent season pack...

**Comment by fernandog** [comment]
read my above comment. season search for TPB is not working.

**Comment by hoefs** [comment]
@fernandog I disabled TPB... I only use KAT and it does not download season packs!!!!

**Comment by fernandog** [comment]
@hoefs can you make a test and set WANTED another episode from another show that airdate year is 2013? I think the problem is not recognizing episodes from 2013

**Comment by hoefs** [comment]
I will try to download another old season from 2013 with only KAT

**Comment by hoefs** [comment]
backlog + wanted = 2013
![screen shot 2015-02-19 at 19 24 25](https://cloud.githubusercontent.com/assets/7440522/6273089/f0d01e6a-b86c-11e4-99dd-465bc2790034.png)

**Comment by hoefs** [comment]
backlog for complete season 4 for "The Good Wife" downloads a season pack...

error seems to be only with "Brooklyn Nine Nine" 11 instead of 22 episodes

**Comment by fernandog** [comment]
so it's not an issue with SR, isn't?

**Comment by hoefs** [comment]
@fernandog 2 seasons started to download with backlog and KAT (2012 and 2013)

Looks like an issue with the episode count in "Brooklyn Nine Nine"

**Comment by fernandog** [comment]
@hoefs SR code don't distinguish tv-shows. If its working for one, then there's must be an issue with that tv-show. Maybe the show name as different in 2013 (scene exception)

**Comment by hoefs** [comment]
@fernandog it is indeed an issue with that show, you can close this
