### ISSUE TITLE
Feature Request: Link to snatched Torrent location in history

### ISSUE THREAD

**Issue by snowwing** [SiCKRAGETV/sickrage-issues#635]
for Torrent providers it would be nice to be able to click through to the site url of the snatched torrent from the history tab (e.g. in the Kat rss search this would be the link url). This would make it easier to confirm that the snatched episode is a good version (check comments, etc.).

**Comment by neoatomic** [comment]
In many cases this wont be possible as we are generally not using "normal" links to get torrents etc.
Also it has not much use, as the torrent is already downloaded at that point.

**Comment by matigonkas** [comment]
@neoatomic could this be possible fron the torrent hash?? By ie link it to torrentz

**Comment by neoatomic** [comment]
@matigonkas It probably depends on the method used. But don't think its word the time the Dev's need to put into this. 
But if you see a possibility than feel free to give it a shot and submit a PR.
