### ISSUE TITLE
[APP SUBMITTED]: int() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by SimonKberg** [SiCKRAGETV/sickrage-issues#637]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) 
[GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.8**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@1ad9ed453985f1fccdcd7eac97970cef1cb324c1
Link to Log: https://gist.github.com/fd0b898e1564a5b5bd02
### ERROR
```
Thread-28 :: Failed doing webui callback: Traceback (most recent call last):
  File "/media/sdk1/home/simonkberg/.sickrage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/media/sdk1/home/simonkberg/.sickrage/sickbeard/webserve.py", line 2251, in getRecommendedShows
    for show in recommendedlist if not helpers.findCertainShow(sickbeard.showList, [
  File "/media/sdk1/home/simonkberg/.sickrage/sickbeard/webserve.py", line 2252, in <genexpr>
    int(show['ids'][indexers[sickbeard.TRAKT_DEFAULT_INDEXER - 1]])])))
TypeError: int() argument must be a string or a number, not 'NoneType'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@SimonKberg do you have trakt enabled, with api, username, password and etc. Everything set?

**Comment by fernandog** [comment]
@SimonKberg please reply or we will close this issue

**Comment by SimonKberg** [comment]
Sorry, yes - everything is set and the test runs successfully.

**Comment by fernandog** [comment]
Screen shot please

**Comment by SimonKberg** [comment]
![2015-02-19 16_49_11-sickrage - branch_ develop - config - notifications](https://cloud.githubusercontent.com/assets/173085/6270061/849f49ec-b857-11e4-8cab-5df805c17ba0.png)

**Comment by fernandog** [comment]
@SimonKberg not TRAKT! KODI!

**Comment by SimonKberg** [comment]
![2015-02-19 16_56_50-sickrage - branch_ develop - config - notifications](https://cloud.githubusercontent.com/assets/173085/6270194/7d17a768-b858-11e4-82dc-aaf8899942e5.png)

**Comment by fernandog** [comment]
@abeloin can you check this one?

**Comment by abeloin** [comment]
@SimonKberg What were you doing in sickrage when you got the error?

**Comment by fernandog** [comment]
@SimonKberg please reply or we will close

**Comment by faidwen** [comment]
I think I just posted a similar issue as this.  Looks almost identical.  I received it when doing a manual search for an UPCOMING SHOW.

2015-02-20 08:58:59 Thread-96 :: Failed doing webui callback: Traceback (most recent call last):
  File "/root/.sickrage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/root/.sickrage/sickbeard/webserve.py", line 1864, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "/root/.sickrage/sickbeard/webserve.py", line 1827, in getEpisodes
    showObj = sickbeard.helpers.findCertainShow(sickbeard.showList, int(show))
ValueError: invalid literal for int() with base 10: 'undefined'

BRANCH: (develop) / COMMIT: (55d0d213e48909ca5944260e937be72b693a7b8b) 
Python 	2.6.6 (r266:84292, Jan 22 2014, 09:42:36) [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]

**Comment by fernandog** [comment]
@faidwen Please update your SR

**Comment by faidwen** [comment]
fernandog, I am showing 55d0d213e48909ca5944260e937be72b693a7b8b as the most recent commit.  Am I missing something?

OOOOH NOW I SEE A NEW VERSION LOL!!!!  sneaky & thanks!

**Comment by fernandog** [comment]
Latest develop is
ac153cf2320b3b6d0a8aa9a1b1646a51347581d6 not 55d0d213e48909ca5944260e937be72b693a7b8b

**Comment by faidwen** [comment]
I see master as ac153cf2320b3b6d0a8aa9a1b1646a51347581d6
and develop as 55d0d213e48909ca5944260e937be72b693a7b8b

**Comment by faidwen** [comment]
develop

commit 55d0d213e48909ca5944260e937be72b693a7b8b 2 parents ada694b + 27ac4ca
Alexandre Beloin abeloin authored 13 hours ago

AND


    master
    (#1)

commit ac153cf2320b3b6d0a8aa9a1b1646a51347581d6 1 parent 93f0f0a
Fernando fernandog authored a day ago

**Comment by fernandog** [comment]
Do a refresh on that show. This is a old issue that was fixed

**Comment by faidwen** [comment]
It is not just one show, it occurs with ANY shows from the webui when pressing manual search from COMING EPISODES.

BRANCH: (develop) / COMMIT: (b10f36e8d72545b4db22e7c07a4f7fea484e24a0) 

Also, the line in question that appears to be causing the issue, was added in line 1827 from https://github.com/SiCKRAGETV/SickRage/pull/1350

**Comment by fernandog** [comment]
@faidwen again: don't hijack others issues!
will delete your comment in 5min. please move it

**Comment by abeloin** [comment]
Must have updated sickrage without resting it.

**Comment by fernandog** [comment]
I would auto restard when switching brances. SR already auto restart when updating

**Comment by abeloin** [comment]
Added the todo list ;)
