### ISSUE TITLE
WEB-DL 720p and 1080p

### ISSUE THREAD

**Issue by Alexwijn** [SiCKRAGETV/sickrage-issues#638]
I got a custom quality prefences with the following:
> Initial: SD TV, HD TV 
> Replace with: 720p WEB-DL

But for some reason he also downloads 1080p WEB-DL versions. I do not want those versions since they uses more disk space and 720p looks fine to me on my TV.

**Comment by fernandog** [comment]
Logs? Show page screen shot?

**Comment by Alexwijn** [comment]
Here you go:
http://imgur.com/e7a2rJB

**Comment by fernandog** [comment]
Which providers do you have enabled?
Please send full logs

**Comment by Alexwijn** [comment]
I used EZTV, Kickass and OldPirateBay (in that order). I do not have any logs that I still have for that date. For some reason all I got is logs from 2015-02-17 17:57:58.

**Comment by fernandog** [comment]
Try disable oldpiratebay. Some users report wrong search strings.
we still need logs. Get in /SickRage/Logs/sickrage.log
use pastebin.com

**Comment by Alexwijn** [comment]
http://pastebin.com/CKPb2gKd

**Comment by fernandog** [comment]
Maybe you were using the old code of oldpiratebay. its was buggy.

**Comment by Alexwijn** [comment]
I guess, I just disabled it to make sure. Any chance I can make sickrage replace 1080p with 720p version automatically?

**Comment by fernandog** [comment]
Just do a manual search. but you must delete manually those files
