### ISSUE TITLE
how to shut this error off

### ISSUE THREAD

**Issue by ripper1967** [SiCKRAGETV/sickrage-issues#639]
SR Python Version: 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)] Version:  BRANCH: (develop) / COMMIT: (b29f5122fc557fc2bab7ed907d3a76221fb58535) 
windows 7 64 bit
How do I shut this error off? I do not run Https

C:\Users\Rusty\SickRage\lib\requests\packages\urllib3\connectionpool.py:747: Ins
ecureRequestWarning: Unverified HTTPS request is being made. Adding certificate
verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest
/security.html

**Comment by fernandog** [comment]
@ripper1967 please send full logs

@abeloin new requests lib?

**Comment by abeloin** [comment]
Yes, it can disable via:
```
import urllib3
urllib3.disable_warnings()
```
I'll make a PR for it.

**Comment by ripper1967** [comment]
Ok Thank You..

**Comment by abeloin** [comment]
Fixed in the dev branch
