### ISSUE TITLE
[APP SUBMITTED]: <ProtocolError for api.opensubtitles.org/xml-rpc: 503 Service Unavailable>

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#640]
### INFO
Python Version: **2.7.8 (default, Oct 20 2014, 15:05:29) 
[GCC 4.9.1]**
Operating System: **Linux-3.16.0-30-generic-i686-with-Ubuntu-14.10-utopic**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@b29f5122fc557fc2bab7ed907d3a76221fb58535
Link to Log: https://gist.github.com/913aaf025a2689fa2e54
### ERROR
```
FINDSUBTITLES :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "/home/supergonkas/sickrage_install/sickbeard/tv.py", line 1399, in downloadSubtitles
    multi=sickbeard.SUBTITLES_MULTI, cache_dir=sickbeard.CACHE_DIR)
  File "/home/supergonkas/sickrage_install/lib/subliminal/api.py", line 95, in download_subtitles
    subtitles_by_video = list_subtitles(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "/home/supergonkas/sickrage_install/lib/subliminal/api.py", line 62, in list_subtitles
    service_instance.terminate()
  File "/home/supergonkas/sickrage_install/lib/subliminal/services/opensubtitles.py", line 103, in terminate
    raise ServiceError(str(e))
ServiceError: <ProtocolError for api.opensubtitles.org/xml-rpc: 503 Service Unavailable>

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
No need to report this error, it's telling you opensubtitles is unavailable.

**Comment by fernandog** [comment]
@matigonkas 
 can you try this?

https://github.com/SiCKRAGETV/SickRage/pull/1348/files

stop SR, edit that file, change it, save it and restart SR

**Comment by matigonkas** [comment]
I changed the file according to the pull request,but now i dont know if its possible to make openSubtitles unacessible or if i just need to whait for it to become unreacheble, and check the logs...

**Comment by fernandog** [comment]
you have to wait until the 503 error appears
