### ISSUE TITLE
Sickrage slow when loading pages

### ISSUE THREAD

**Issue by ceesvanegmond** [SiCKRAGETV/sickrage-issues#642]
Hello everyone,

I'm experiencing a few problems when using Sickrage.

Branch: Master
Commit hash: 93f0f0ad1fa278afb17f73d47c099b82a766dede
Your operating system and python version SynologyDSM (latest), Python 2.7.9, SynologyDS414j
What you did: Just open any page in sickrage (homepage, showdetailpage, error page)

What happened: 
It takes a while to load, it strikes me that the assets that are loaded (see screenshot) are also pretty slow on loading. Sometimes i have to wait 30 to 60 seconds for an page to load. 
![schermafbeelding 2015-02-17 om 23 28 11](https://cloud.githubusercontent.com/assets/883497/6238596/abdada1e-b6fc-11e4-9270-19cc207f26a4.png)

What you expected: Faster page load

Question: How is it possible for an browser.css for example take 2 seconds to load? This has to be an instant load of the asset right?

When looking at another application (NZBget for instance), i don't have that problem at all, so the memory/speed of my NAS isn't the problem i guess

**Comment by abeloin** [comment]
What the cpu usage on your Synology? Have a look at your load average as it look like to me the system is struggling. Do you have any subtitles enabled? As they chew up a lot of cpu ressources.

**Comment by ceesvanegmond** [comment]
I have subtitles enabled.

EDIT: I just disabled the subtitles plugin, though i still have the problem.
I have looked in to the CPU/MEM usage (screenshot)
![schermafbeelding 2015-02-18 om 08 44 35](https://cloud.githubusercontent.com/assets/883497/6243843/747d66c4-b74a-11e4-9645-1de4c0e10a73.png)

I guess the CPU/MEM couldn't be the problem, their usage isn't that big.

**Comment by abeloin** [comment]
Definitely a CPU bound issue. The load average is over your CPU capacity(2 CPU = load average 2.00 = 100% usage) for more than 15 minutes. Also in your screenshot the cpu usage for sickrage is high.

**Comment by abeloin** [comment]
After disabling the subtitles, is the cpu usage lower? If not, please provide your sickrage.log via pastebin as to see what's using that much cpu.

**Comment by ceesvanegmond** [comment]
The CPU is a little bit lower when subtitles disabled
http://pastebin.com/Gk3JqxYz

**Comment by fernandog** [comment]
@ceesvanegmond you did a mass update didnt you? This take a log time and CPU

**Comment by Thraxis** [comment]
Looking at the CPU/MEM screenshot...  Why are you running so many instances of Sickrage?
You have 13 seperate instances showing in that shot.

**Comment by abeloin** [comment]
@Thraxis Those are all threads used by the process sickrage. By default top and htop lists each thread of a process separately which can be disable by typing H.

**Comment by Thraxis** [comment]
Been a while since I last used htop... and I tend to look by single process not by thread.  Just verified with my system running htop with threads on and saw it starts a large number of threads when loading the page.

**Comment by Nibeck1309** [comment]
Hello,

I have the same problem.
I used SickRage on Raspberry Pi B and I used Raspbian OS

my SickRage configuration 

SR Version:	 BRANCH: (develop) / COMMIT: (9226ae9ad5ba58499f69968da524f0873427f455) 
SR Config file:	/media/media/Config_Files/sickrage/config.ini
SR Database file:	/media/media/Config_Files/sickrage/sickbeard.db
SR Cache Dir:	/media/media/Config_Files/sickrage/cache
SR Arguments:	['-q', '--daemon', '--nolaunch', '--pidfile=/media/media/Config_Files/sickrage/sickbeard.pid', '--datadir=/media/media/Config_Files/sickrage', '--config=/media/media/Config_Files/sickrage/config.ini']
SR Web Root:	
Python Version:	2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]

this is my htop process run

![capture du 2015-02-27 09 57 52](https://cloud.githubusercontent.com/assets/11226474/6409660/1ede984a-be67-11e4-94d7-4aee1d842012.png)

this is my final line logs 

![capture du 2015-02-27 10 00 15](https://cloud.githubusercontent.com/assets/11226474/6409721/7a10e0e2-be67-11e4-8938-0c1c5ef40d4c.png)


I want edit a show page and the page is very slow to open over than 10 min.

Thanks for your work

**Comment by fernandog** [comment]
disable auto update show at startup.backlog search at startup and subtitle module is the best solution.
I'm using RPI and not getting any problems.

**Comment by Nibeck1309** [comment]
thanks fernandog for this configuration option.
You used dev or master version ?

**Comment by fernandog** [comment]
Dev

**Comment by Nibeck1309** [comment]
thanks
