### ISSUE TITLE
Web Page on iPad doesn't work

### ISSUE THREAD

**Issue by iguyking** [SiCKRAGETV/sickrage-issues#643]
Branch - Master
Commit hash - 93f0f0ad1fa278afb17f73d47c099b82a766dede
Your operating system and python version - Ubuntu 14.04
What you did - Updated to latest git release 
What happened - 
-- Viewing the webpage on an iPad no longer works nice and simple.   Now it looks like it does on the desktop/full version.  In doing that, you can't actually see anything on the top and you can't add shows for example because the view is blocked by the header. 

It worked fine apparently 275 commits earlier than the hash noted above.   Something changed since then that took the iPad friendly interface away. 

What you expected - 

I expected to continue to have a simple /condensed interface on the iPad.

**Comment by abeloin** [comment]
Can you provide a screenshot?

**Comment by iguyking** [comment]
Attached is the way it looks now on the ipad.  I don't have an older one showing a functional view.  In here you can see that you can't see the add shows options or any buttons near the top of the page.  This is at the top of the web page, I can't scroll up any more.
![image](https://cloud.githubusercontent.com/assets/5004028/6261210/7bde60fa-b7b1-11e4-86ae-b8912343577f.jpg)

**Comment by abeloin** [comment]
@iguyking A fix was pushed into the developement branch.

**Comment by fernandog** [comment]
@iguyking is it ok now?

**Comment by iguyking** [comment]
I just updated and it looks the same as before.  No change on my ipad.   

What other info do you need to help diagnose or fix?

**Comment by abeloin** [comment]
The fix is in develop branch

**Comment by iguyking** [comment]
This is fixed now in release.   Thanks.
