### ISSUE TITLE
[Feature Request] Add remove torrent to uTorrent client.

### ISSUE THREAD

**Issue by ChaosTherum** [SiCKRAGETV/sickrage-issues#644]
When using CouchPotato I noticed that they had the option of removing a torrent once it was completed. This would be really great to have in SickRage.

Another thing I'm not even sure if this is possible but it would be great if we could also set a directory to move the data to once completed. I know it's doable in the main program but it would be nice to have a separate folder for SickRage from my regular complete folder.

**Comment by andonevris** [comment]
You can use the "add label to torrent" setting and completed downloads will be put into a sub-folder with that name

**Comment by ChaosTherum** [comment]
Yeah I know that you can but that would Just allow you to have that little extra confidence that it was going to work. I have had that function in utorrent fail to work. Just doesn't move it when it is finished.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
