### ISSUE TITLE
Missing logo network

### ISSUE THREAD

**Issue by maxcore** [SiCKRAGETV/sickrage-issues#645]
Missing canada network logo thx

https://www.dropbox.com/s/valzy8uco890tv7/logo-network.zip?dl=0

enjoy

**Comment by neoatomic** [comment]
@maxcore Thanks for the logo's.
We need the exact network names for both logos that are shown in the show overview.
Also normally we use transparent backgrounds in the logos, but i see that with those two logos that could give problems. Need to give that some thoughts how to solve...

**Comment by maxcore** [comment]
oh i see thx i redo the logo with transparent backgrounds , and i name the logo with the good name on tvdb

**Comment by maxcore** [comment]
https://www.dropbox.com/s/goqumrnwtnae5j8/Network%20Logo%20Proper.zip?dl=0
Proper Logo

@neoatomic 
For 
addikTV
and
Séries+

thx !

**Comment by neoatomic** [comment]
@maxcore I have added the logos for you. Thank you for creating and posting them.

However as the logos are mainly in black they might not show as nice/good on the dark Sickrage theme. If that is the case than please supply another logo.

**Comment by maxcore** [comment]
@neoatomic 
yep i will work on it , i forget for the black background .

**Comment by fernandog** [comment]
@maxcore any updates?

**Comment by maxcore** [comment]
am work on it but you can close it
