### ISSUE TITLE
[APP SUBMITTED]: You tried saving an invalid sports naming config, not saving your sports settings

### ISSUE THREAD

**Issue by mike19715** [SiCKRAGETV/sickrage-issues#647]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@93f0f0ad1fa278afb17f73d47c099b82a766dede
Link to Log: https://gist.github.com/55d614f465397e93a39e
### ERROR
```
Thread-52 :: You tried saving an invalid sports naming config, not saving your sports settings
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
Need more info, what's the sport string your trying to save?

**Comment by mike19715** [comment]
I actually recieve this error message every time I make a change to post processing and save it to the config.  It has been happening for awhile and can't seem to find the cause.

**Comment by abeloin** [comment]
To resolve:
1. Go to post process config
2. Switch to Episode Naming tab
3. Check Custom Sports
4. Change from custom to the 1st one in the drop down list.
5. Uncheck Custom Sports
6. Click Save Changes

**Comment by fernandog** [comment]
no reply
