### ISSUE TITLE
Not finding shows with providers usenet-crawler, nzb finder, sick beard index, womble's index

### ISSUE THREAD

**Issue by educatedwarrior** [SiCKRAGETV/sickrage-issues#651]
Branch  - master
Commit hash  - just did update
Your operating system and python version  -  Freenas
What you did  - Season Episode search not working
What happened  - not finding show
What you expected  - find show and download
Link to a copy/paste of your logfile with clear debug info of the error on PASTEBIN

SUBMIT
 https://www.usenet-crawler.com/api?apikey=xxxxxxxxxxxxxxxxxxxxxxxxx
5ce6f6dcc45&season=28&maxage=2375&cat=5030%2C5040&limit=100&attrs=rageid&offset=0&rid=5631&ep=25&t=tvsearch

This is an api call to usenet-crawler.  I manual executed it using my api key and it didn't return any results.   When I do a manual search on through the website the episode is there.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/
