### ISSUE TITLE
[APP SUBMITTED]: <ProtocolError for api.opensubtitles.org/xml-rpc: 503 Service Unavailable>

### ISSUE THREAD

**Issue by Psychoteur** [SiCKRAGETV/sickrage-issues#653]
### INFO
Python Version: **2.7.8 (default, Dec 15 2014, 02:33:48) 
[GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Branch: **master**
Commit: SiCKRAGETV/SickRage@93f0f0ad1fa278afb17f73d47c099b82a766dede
### ERROR
```
POSTPROCESSER :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 1399, in downloadSubtitles
    multi=sickbeard.SUBTITLES_MULTI, cache_dir=sickbeard.CACHE_DIR)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/subliminal/api.py", line 95, in download_subtitles
    subtitles_by_video = list_subtitles(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/subliminal/api.py", line 62, in list_subtitles
    service_instance.terminate()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/subliminal/services/opensubtitles.py", line 103, in terminate
    raise ServiceError(str(e))
ServiceError: <ProtocolError for api.opensubtitles.org/xml-rpc: 503 Service Unavailable>

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@abeloin 
We should handle this traceback more will come

**Comment by fernandog** [comment]
@Psychoteur can you try this?

https://github.com/SiCKRAGETV/SickRage/pull/1348/files

stop SR, edit that file, change it, save it and restart SR

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/640

**Comment by fernandog** [comment]
please try the above fix
@matigonkas @pct00

**Comment by pct00** [comment]
@fernandog different issue from the one i reported, mine is related to encoding of the downloaded subtitle files not with timeout/access problem

**Comment by fernandog** [comment]
@pct00
Here your issue:
https://github.com/SiCKRAGETV/sickrage-issues/issues/244

**Comment by fernandog** [comment]
update available for this issue

**Comment by matigonkas** [comment]
@fernandog  i can confirm it (i know its a bit late but still...)     i just got this
2015-02-20 19:17:54 POSTPROCESSER :: Error occurred when downloading subtitles: 
Also could it be possible to have something like "opensubtitles not reacheable" where the traceback was?

**Comment by fernandog** [comment]
so its working. It not showing that huge error.

**Comment by matigonkas** [comment]
yes it is working , thanks for the fix :)
