### ISSUE TITLE
ImportError: cannot import name ProtocolError

### ISSUE THREAD

**Issue by cptjhmiller** [SiCKRAGETV/sickrage-issues#655]
##### Branch
Master

##### Operating system and python version
Debian Wheezy
Python 2.7.3 (default, Mar 13 2014, 11:03:55)

##### What I did
Switch from develop version to master version.

##### ERROR

    Traceback (most recent call last):
    File "SickBeard.py", line 62, in <module>
    import sickbeard
      File "/opt/sickbeard2/sickbeard/__init__.py", line 33, in <module>
    from sickbeard import providers, metadata, config, webserveInit
      File "/opt/sickbeard2/sickbeard/providers/__init__.py", line 46, in <module>
    import generic
      File "/opt/sickbeard2/sickbeard/providers/generic.py", line 29, in <module>
    import requests
      File "/opt/sickbeard2/lib/requests/__init__.py", line 58, in <module>
    from . import utils
      File "/opt/sickbeard2/lib/requests/utils.py", line 25, in <module>
    from .compat import parse_http_list as _parse_list_header
      File "/opt/sickbeard2/lib/requests/compat.py", line 7, in <module>
    from .packages import chardet
     File "/opt/sickbeard2/lib/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
      File "/opt/sickbeard2/lib/requests/packages/urllib3/__init__.py", line 16, in <module>
    from .connectionpool import (
      File "/opt/sickbeard2/lib/requests/packages/urllib3/connectionpool.py", line 33, in <module>
    from .connection import (
      File "/opt/sickbeard2/lib/requests/packages/urllib3/connection.py", line 41, in <module>
    from .util import (
      File "/opt/sickbeard2/lib/requests/packages/urllib3/util/__init__.py", line 18, in <module>

    File "/opt/sickbeard2/lib/requests/packages/urllib3/util/retry.py", line 4, in <module>
    ImportError: cannot import name ProtocolError

##### INFO
On the master version the file `/opt/sickbeard2/lib/requests/packages/urllib3/util/retry.py` is not there and so i get the above error. The Dev version has the file and so i do not get the error, just warnings.

    10:44:46 INFO::MAIN :: Trying to clean cache folder /var/opt/sickbeard2/cache
    10:44:47 INFO::MAIN :: Checking database structure...
    10:44:47 INFO::MAIN :: Checking database structure...
    10:44:47 INFO::MAIN :: Checking database structure...
    10:44:47 INFO::MAIN :: No duplicate show, check passed
    10:44:47 INFO::MAIN :: No duplicate episode, check passed
    10:44:47 INFO::MAIN :: No orphan episodes, check passed
    10:44:47 INFO::MAIN :: No UNAIRED episodes, check passed
    10:44:47 INFO::MAIN :: No MALFORMED episode statuses, check passed
    10:44:47 INFO::MAIN :: Loading initial show list
    10:44:47 INFO::TORNADO :: Starting SickRage on http://0.0.0.0:8082/
    Starting up SickRage develop from /var/opt/sickbeard2/config.ini
    10:44:47 INFO::DAILYSEARCHER :: Searching for new released episodes ...
    10:44:47 INFO::CHECKVERSION :: Checking for updates using GIT
    10:44:47 INFO::MAIN :: No scene exceptions update needed
    10:44:47 INFO::MAIN :: Building internal name cache for all shows
    /opt/sickbeard2/lib/requests/packages/urllib3/connectionpool.py:747: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
      InsecureRequestWarning)
    /opt/sickbeard2/lib/requests/packages/urllib3/connectionpool.py:747: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
      InsecureRequestWarning)
    /opt/sickbeard2/lib/requests/packages/urllib3/connectionpool.py:747: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
      InsecureRequestWarning)
    /opt/sickbeard2/lib/requests/packages/urllib3/connectionpool.py:747: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
      InsecureRequestWarning)
    10:44:47 INFO::DAILYSEARCHER :: No new released episodes found ...
    10:44:48 INFO::CHECKVERSION :: No update needed
    10:44:50 INFO::SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
    10:44:50 ERROR::SEARCHQUEUE-DAILY-SEARCH :: No NZB/Torrent providers found or enabled in the sickrage config for daily searches. Please check your settings.
    None
    10:44:50 INFO::SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found`

**Comment by abeloin** [comment]
We upgraded the requests library in develop.
I don't know why git doesn't want to restore the proper files for the request library when switching back to master.

Remove all file inside lib/requests/ then do a git reset --hard

**Comment by fernandog** [comment]
@cptjhmiller any news?

**Comment by cptjhmiller** [comment]
It adds some files back but not the `lib/requests/packages/urllib3/util/` folder.

**Comment by abeloin** [comment]
Tested and working:
1. `rm -rf lib/requests`
2. `git reset --hard origin/master`
3. `python SickBread --nolauch`

**Comment by cptjhmiller** [comment]
It does work. I checked for the creation of the urllib3/util/ not if it would start, I did try later and found that this folder is not used in the master branch. Goto busy with other things and forgot to post back, sorry.

**Comment by abeloin** [comment]
Thanks
