### ISSUE TITLE
[Feature Request] Add h265 quality format

### ISSUE THREAD

**Issue by gborri** [SiCKRAGETV/sickrage-issues#656]
could be usefull to differentiate hd video in h265 format (low disk space).

**Comment by gborri** [comment]
@fernandog could you reopen this?

**Comment by fernandog** [comment]
Its open

**Comment by fernandog** [comment]
i closed one. There is not point have 2 FR

**Comment by gborri** [comment]
@fernandog sorry, I've made a mistake. i don't know why i have seen also this one was closed.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
