### ISSUE TITLE
[Feature Request] Mark download as bad and retry also when failed download is disabled

### ISSUE THREAD

**Issue by gborri** [SiCKRAGETV/sickrage-issues#657]
the message "Mark download as bad and retry" appear also when failed download is disabled.

**Comment by TagForce** [comment]
Failed download handling is only for automated failed download handling. Manual failed download handling is not controlled with the setting. If a snatched or downloaded episode is searched for again, the current snatched or downloaded episode will still be set to failed and a new one will be downloaded (if found).

At least, that is what I understand to be true.

**Comment by gborri** [comment]
@TagForce i don't agree with your point.
Failed download means from my poit of view that i have a problem with a torrent that is being downloaded or are in the way to be downloaded (snatched). the problem persist not related to the process that started the download of the file. That means that if i have downloaded it manually and the file is corrupted on torrent provider i would like to download another version the will work and it does not depend if i have downloaded it mauanlly or via backlog search or via daily search.
For example i have snatched an episode via backlog search and the file has a problem i would like to get it manually (the backlog process doesn't thake it in charge anymore).
But the problem for wich i have open the issue is: if i have failed downloading handling disable why if i press the manual search icons the second time it ask me to mark it as failed? what's the purpose of this?

**Comment by gborri** [comment]
@fernandog could you reopen it?

**Comment by fernandog** [comment]
I agree with you.  This is a feature request I would like it too

Its not a bug IMO but a bad choic of words in the popup.

**Comment by TagForce** [comment]
@gborri I just checked, and it doesn't?
When Failed downloads is disabled, the link will always point to http://SRHome/SearchEpisode, and won't show the popup.
Whereas turning it on and clicking the search button on a snatched or downloaded episode points to http://SRHome/RetryEpisode

**Comment by gborri** [comment]
@TagForce it happens.
the scenario is: add show, start snatch for an episode, the episode is not foud, try again and the popup appear

**Comment by fernandog** [comment]
@TagForce @abeloin 
it does not check for anything. 
https://github.com/SiCKRAGETV/SickRage/blob/e8405b35d6d8fc0bc1909c18e2e528e68cdc0cde/gui/slick/js/ajaxEpSearch.js#L132

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
