### ISSUE TITLE
KAT Search URL Error

### ISSUE THREAD

**Issue by Roebuck** [SiCKRAGETV/sickrage-issues#660]
KAT searching seems to be using the wrong URL (Or something in my setup is generating the wrong URL)

Searching for Person Of Interest S04E15 in HD always returns nil results using the URL 
http://kickass.proxy.pm/usearch/Person.of.Interest+S04E15%7C4x15+category%3Atv/?field=seeders&sorder=desc&rss=1

Remove the %7C4x15 and the correct results are returned
http://kickass.proxy.pm/usearch/Person.of.Interest+S04E15+category%3Atv/?field=seeders&sorder=desc&rss=1

Whats generating the %7C4x15 portion of the URL? (Same URL is generated via Manual Search or Backlog search)

Debug Log:
http://pastebin.com/pkY4WiLJ

Using Latest Pull from Dev Branch
Python version 2.7.8 on Win 7

**Comment by Thraxis** [comment]
Your proxy is not working correctly, the %7C is the URL encode of the pipe symbol '|'. This is telling it to search for Person of Interest S04E15 OR 4x15 

If you search directly at kickass.to the search string works as it should, returning an RSS feed as it should.

http://kickass.to/usearch/Person.of.Interest+S04E15%7C4x15+category%3Atv/?field=seeders&sorder=desc&rss=1

Your proxy is also not returning an RSS feed but instead is returning a webpage for the search that does work.

**Comment by Roebuck** [comment]
Thanks! Should have spotted that!
