### ISSUE TITLE
Fatal error executing query: database disk image is malformed

### ISSUE THREAD

**Issue by Rafkat** [SiCKRAGETV/sickrage-issues#663]
Branch: Develop
Commit hash: 270dc3659973a1ef0110ec40e06ba039722dd44e
Operating system: Synology DSM
Python version: 2.7.8 (default, Dec 12 2014, 21:20:40) [GCC 4.7.3 20130102 (prerelease)]

What you did: Updated to the last branch releases

What happened: Error appears in the Error log, though app is still functioning as expected. I suspect that this errors related to the Fargo show added recently with "Set the initial status of missing episodes" option set to "Archived". When I'm in the show, I cannot see the list of the 1st season episodes. FYI: I've had this show's folder on  the disk, but without any episodes in it.

What you expected: No errors in log!

Error:

2015-02-18 23:52:30 SHOWQUEUE-FORCE-UPDATE :: Fatal error executing query: database disk image is malformed
2015-02-18 23:52:10 BACKLOG :: Fatal error executing query: database disk image is malformed
2015-02-18 23:52:10 BACKLOG :: Exception generated in thread BACKLOG: database disk image is malformed

Debug error log:
2015-02-19 00:02:45 INFO     SHOWQUEUE-FORCE-UPDATE :: Beginning update of Fargo
AADatabaseError: database disk image is malformed
AA    raise e
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/db.py", line 92, in execute
AA    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/db.py", line 170, in action
AATraceback (most recent call last):
2015-02-19 00:02:43 ERROR    SHOWQUEUE-FORCE-UPDATE :: Fatal error executing query: database disk image is malformed

**Comment by abeloin** [comment]
It look like a corrupt database. Try running a "pragma integrity_check;" inside the db with sqlite3

**Comment by fernandog** [comment]
@Rafkat 

install sqlite3 if not already installed.
Stop SickRage
cd into your SickRage directory
Run the commands

```
mv sickbeard.db sickbeard.db.bak
```

```
sqlite3 sickbeard.db.bak .dump | sqlite3  sickbeard.db
```

Restart sickrage

https://github.com/SiCKRAGETV/sickrage-issues/issues/549
http://sickbeard.com/forums/viewtopic.php?f=4&t=4648#p21409
