### ISSUE TITLE
Sickrage failed to start after recent git update of develop (SyntaxError: tntvillage.py)

### ISSUE THREAD

**Issue by heymoe** [SiCKRAGETV/sickrage-issues#664]
System / Setup Info:
=============================================================
Branch : develop
Commit hash : 25bbe786468fd6669d6247470bcfa00fa571eb3e
Operating system and python version : Linux (CentOS v5.11), Python v2.6

What you did:
==============================================================
Upgraded from COMMIT: 226a7148d267bf4548044b45aef40d444807834c to: 25bbe786468fd6669d6247470bcfa00fa571eb3e

What happened:
==============================================================
Tried to start Sickrage after the update but it failed to start. I received the following error:

Starting sickrage: Traceback (most recent call last):
  File "/opt/sickrage/SickBeard.py", line 62, in <module>
    import sickbeard
  File "/opt/sickrage/sickbeard/__init__.py", line 35, in <module>
    from providers import ezrss, btn, newznab, womble, thepiratebay, oldpiratebay, torrentleech, kat, iptorrents, \
  File "/opt/sickrage/sickbeard/providers/tntvillage.py", line 88
    ' Versione 720p',
                    ^
SyntaxError: invalid syntax

What you expected:
===============================================================
Expected Sickrage to start again :)

This seems to be related to this recent commit: 270dc3659973a1ef0110ec40e06ba039722dd44e

**Comment by abeloin** [comment]
Can you try a git reset --hard?

**Comment by heymoe** [comment]
After failing to start earlier I reverted back to the previous version that was working with this command:

git reset --hard 226a714

and Sickrage started back up, no problems.

So to try what you requested, I first did a:

# git pull
Updating 226a714..25bbe78
Fast-forward
 SickBeard.py                                           |  23 ++--
 gui/slick/images/providers/tntvillage.png              | Bin 0 -> 1150 bytes
 gui/slick/interfaces/default/config_notifications.tmpl |  14 +++
 gui/slick/interfaces/default/config_providers.tmpl     |  27 +++++
 gui/slick/interfaces/default/inc_top.tmpl              |   2 +
 sickbeard/__init__.py                                  |  45 +++++++-
 sickbeard/helpers.py                                   |  28 +++++
 sickbeard/notifiers/plex.py                            |   4 +
 sickbeard/providers/__init__.py                        |   1 +
 sickbeard/providers/rarbg.py                           |   2 +-
 sickbeard/providers/tntvillage.py                      | 485 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 sickbeard/webserve.py                                  |  33 ++++--
 12 files changed, 643 insertions(+), 21 deletions(-)
 create mode 100644 gui/slick/images/providers/tntvillage.png
 create mode 100644 sickbeard/providers/tntvillage.py

Then your requested: 

# git reset --hard    
HEAD is now at 25bbe78 Merge pull request #1345 from abeloin/patch-backup_restore

Upon starting Sickrage, I get the same error:

Starting sickrage: Traceback (most recent call last):
  File "/opt/sickrage/SickBeard.py", line 62, in <module>
    import sickbeard
  File "/opt/sickrage/sickbeard/__init__.py", line 35, in <module>
    from providers import ezrss, btn, newznab, womble, thepiratebay, oldpiratebay, torrentleech, kat, iptorrents, \
  File "/opt/sickrage/sickbeard/providers/tntvillage.py", line 88
    ' Versione 720p',
                    ^
SyntaxError: invalid syntax

**Comment by faidwen** [comment]
Same issue here, reverted to previous version without TNTVILLAGE error.  All fine.

Thanks

**Comment by abeloin** [comment]
@faidwen Python 2.6?

**Comment by faidwen** [comment]
Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2

**Comment by abeloin** [comment]
Can you try replacing the file tntvillage.py by this one https://gist.github.com/abeloin/3a322f5073ec919c10f2 ?

**Comment by faidwen** [comment]
I took the raw from that page and wget to tntvillage.py in the providers directory and received the following error on restart :  
Executing /etc/rc.d/init.d/sickrage start ..

Starting sickrage: Traceback (most recent call last):
  File "/root/.sickrage/SickBeard.py", line 62, in <module>
    import sickbeard
  File "/root/.sickrage/sickbeard/__init__.py", line 35, in <module>
    from providers import ezrss, btn, newznab, womble, thepiratebay, oldpiratebay, torrentleech, kat, iptorrents, \
  File "/root/.sickrage/sickbeard/providers/tntvillage.py", line 90
    ' Versione 720p',
                    ^
SyntaxError: invalid syntax
[FAILED]

**Comment by abeloin** [comment]
I've updated the gist can you try the new version.

**Comment by faidwen** [comment]
Executing /etc/rc.d/init.d/sickrage start ..

Starting sickrage: Traceback (most recent call last):
  File "/root/.sickrage/SickBeard.py", line 62, in <module>
    import sickbeard
  File "/root/.sickrage/sickbeard/__init__.py", line 35, in <module>
    from providers import ezrss, btn, newznab, womble, thepiratebay, oldpiratebay, torrentleech, kat, iptorrents, \
  File "/root/.sickrage/sickbeard/providers/tntvillage.py", line 89
    self.hdtext = {" Versione 720p", " V 720p", " V HEVC", " V  HEVC", " Versione 1080p", " 720p HEVC", " Ver 720", " 720p HEVC"}
                                   ^
SyntaxError: invalid syntax
[FAILED]

**Comment by abeloin** [comment]
Could you try again, I've put a new version?

**Comment by faidwen** [comment]
Executing /etc/rc.d/init.d/sickrage start ..

Starting sickrage: Traceback (most recent call last):
  File "/root/.sickrage/SickBeard.py", line 62, in <module>
    import sickbeard
  File "/root/.sickrage/sickbeard/__init__.py", line 35, in <module>
    from providers import ezrss, btn, newznab, womble, thepiratebay, oldpiratebay, torrentleech, kat, iptorrents, \
  File "/root/.sickrage/sickbeard/providers/tntvillage.py", line 88
    'Versione 720p',
                   ^
SyntaxError: invalid syntax
[FAILED]

**Comment by faidwen** [comment]
This is one of those strange little syntax ones...  Is it something from a previous line?

**Comment by abeloin** [comment]
Can you try again, I've updated the gist?

**Comment by faidwen** [comment]
Executing /etc/rc.d/init.d/sickrage start ..

Starting sickrage: [  OK  ]

**Comment by faidwen** [comment]
*CLAP CLAP*  Good show!   Seriously, brackets!

**Comment by abeloin** [comment]
Dict without keys. My guess is that python 2.6 doesn't do the conversion to list.
```
>>> test = {'temp1', 'temp2', 'temp3'}
>>> test
set(['temp3', 'temp2', 'temp1'])
>>> test1 = {1:'temp1', 2:'temp2', 3:'temp3'}
>>> test1
{1: 'temp1', 2: 'temp2', 3: 'temp3'}
>>> test2 = ['temp1', 'temp2', 'temp3']
>>> test2
['temp1', 'temp2', 'temp3']

**Comment by abeloin** [comment]
PR pushed in develop branch.

@faidwen @heymoe Please update your develop branch

**Comment by faidwen** [comment]
Makes sense, works perfectly, thank you for speedy update / fix!

**Comment by heymoe** [comment]
Well looks like I missed out on a lot of fun. I just updated to commit: cadfd9b98410563467760b1dd5c4bd5e92644f50

and Sickrage started right up. Thanks for the fix!

**Comment by freddysmith1** [comment]
im still having trouble getting it to run,  ive tried to update to the latest update using git pull but no luck,  on a synology
