### ISSUE TITLE
Restore previous backup file using new restore method - Synology  failed to run package 

### ISSUE THREAD

**Issue by freddysmith1** [SiCKRAGETV/sickrage-issues#665]
using latest update i get a failed to run package when trying to run sickrage,   have tried git pull, git reset,  checkout master  checkout dev with no luck yet

**Comment by fernandog** [comment]
Error message?

**Comment by freddysmith1** [comment]
just managed to get it running again by going back to a very early dev build

**Comment by fernandog** [comment]
@freddysmith1 this don't help us. The issue still exists and others will have it.

**Comment by freddysmith1** [comment]
i didnt get any error message to provide  just synology says "failed to run package"  when trying to run it,   any way to find any logs to provide?

**Comment by fernandog** [comment]
really?
there's a LOG / View log in the menu bellow sickbeard logo

**Comment by freddysmith1** [comment]
that was the first thing i tried before even posting but 
![untitled](https://cloud.githubusercontent.com/assets/8336824/6265486/c4d3f888-b87e-11e4-8bf9-b74bb7c9e61c.jpg)

**Comment by fernandog** [comment]
ok. sorry! Don't know where to look then.

**Comment by freddysmith1** [comment]
maybe a future feature request would be to include a log file  says on the link the app has to include one http://forum.synology.com/enu/viewtopic.php?f=39&t=69983


im not exactly sure how to? lol

**Comment by neoatomic** [comment]
Confirmed. SR doesn't boot after today's update.
Normally you can also start SR from the package center of the Synology (above screen shot) but also there you cant start it anymore.
SR log shows. : 

```
2015-02-19 12:07:15 INFO     EVENT-QUEUE :: Shutting down Tornado
2015-02-19 12:07:15 INFO     EVENT-QUEUE :: Restarting SickRage with ['/usr/local/sickbeard-custom/env/bin/python', '/usr/local/sickbeard-custom/var/SickBeard/SickBeard.py', '--daemon', '--pidfile', '/usr/local/sickbeard-custom/var/sickbeard-custom.pid', '--config', '/usr/local/sickbeard-custom/var/config.ini', '--datadir', '/usr/local/sickbeard-custom/var/', '--nolaunch']
2015-02-19 12:07:24 ERROR    MAIN :: Restore: restoring cache failed
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/__init__.py", line 651, in restoreCache
    shutil.move(srcDir, dstDir)
  File "/usr/local/python/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/local/python/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/local/python/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/usr/local/sickbeard-custom/var/restore/cache'
2015-02-19 12:17:21 ERROR    MAIN :: Restore: restoring cache failed
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/__init__.py", line 651, in restoreCache
    shutil.move(srcDir, dstDir)
  File "/usr/local/python/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/local/python/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/local/python/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/usr/local/sickbeard-custom/var/restore/cache'

```

**Comment by freddysmith1** [comment]
are you using a synology aswell?  if so how did you get log file?  

if i use git reset --hard 226a714 i can get it started again but nothing else works

**Comment by fernandog** [comment]
@neoatomic did you tried to restore SR settings?

**Comment by neoatomic** [comment]
@freddysmith1 Indeed using a Synlogoy.
Sickrage creates a log names "sickrage.log" its located in the Sickrage folder.
/volume1/@appstore/sickbeard-custom/var/SickBeard/ 

@fernandog No, did not use restore/backup for at least a month. So SR seems to try to restore the cache folder without using that function.

I just note that there are 2 cache folders in "/usr/local/sickbeard-custom/var "
cache-20150219_120724
cache-20150219_121721
Also /usr/local/sickbeard-custom/var/restore is not empty.
Let me remove those and report back.

**Comment by fernandog** [comment]
maybe you tried restore and in the past and the "restore" folder remained.
so when SR starts and finds a "restore" folder it thinks a restore is needed

**Comment by freddysmith1** [comment]
@neoatomic  anyway you can give a dummy guide of how to access the log file lol  i tried ssh into diskstation and then cd /volume1/@appstore/sickbeard-custom/var/SickBeard/   but then im lost at what to do

**Comment by fernandog** [comment]
@freddysmith1 insidete the SickBeard there's a folde called "Logs", find sickrage.log

**Comment by neoatomic** [comment]
@fernandog 
I removed the two cache folders and the restore folder. Now SR starts again.
However i lost my (normal) cache folder. So now SR is downloading all the banners etc...
Lets hope that id did not overwrite my config.ini & sickbeard.db...

```
2015-02-19 12:36:22 INFO     MAIN :: Trying to clean cache folder /usr/local/sickbeard-custom/var/cache
2015-02-19 12:36:22 DEBUG    MAIN :: Using NORMAL regexs
```
Would it be a idea to create a 1 time PR to check if there is an old restore folder.? otherwise you will be having a lot of issues opening on Github today.

**Comment by neoatomic** [comment]
@freddysmith1 It should be located at : /volume1/@appstore/sickbeard-custom/var/Logs/sickrage.log
I use WinSCP to acces the Synology and to view the log.

**Comment by fernandog** [comment]
@neoatomic restore folder was empty?

**Comment by neoatomic** [comment]
@fernandog 
No. Config.ini  sickbeard.db and failed.db if i recall right. (4-5 files)

**Comment by fernandog** [comment]
so I was a previous attempt of restore

**Comment by neoatomic** [comment]
@fernandog Yes, and the folder remained with the files. And with the fix yesterday the backup/restore function started working correctly again and finding the old files in the restore folder.

So if there are new issues opened, users need (for safety) first backup and then empty there restore folder. After that they can start Sickrage in the packet center of the Synology.
Also they can use WinSCP as alternative to regular ssh for removal of the restore folder. (its GUI based.)

**Comment by fernandog** [comment]
@neoatomic in fact SR was trying to restore a previous versions of backup withe no cache folder.

**Comment by freddysmith1** [comment]
2015-02-19 23:01:38 ERROR    MAIN :: Restore: restoring cache failed
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/__init__.py", line 651, in restoreCache
    shutil.move(srcDir, dstDir)
  File "/usr/local/python/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/local/python/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/local/python/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/usr/local/sickbeard-custom/var/restore/cache'
 

i have finally found the log file,  was using putty to access diskstation in command which is what threw me off  but now using winscp on mac with wine woo,   

looks like our problem are pretty much the same,

**Comment by fernandog** [comment]
this commit fixed it.

**Comment by freddysmith1** [comment]
@fernandog   maybe in the readme file you can put down the instructions of how to access the sickrage.log file on synology,  i had no idea how to do it untill tonight and im sure afew others would be the same

**Comment by fernandog** [comment]
@neoatomic can you create some instructions with screenshots?

**Comment by neoatomic** [comment]
@fernandog You could add something like this to the readme : 

```
Note: Synology users can use WinSCP to gain access/browse to the root where Sickrage is installed.
          /volume1/@appstore/sickbeard-custom/var/Logs/sickrage.log
```

The thing is that over regular FTP Synology users cant access the root where Sickrage is installed. So they use the command-line. WinSCP has a GUI interface that makes it more user friendly to troubleshoot.

**Comment by abeloin** [comment]
Fix pushed to develop, please update.

**Comment by neoatomic** [comment]
Just updated. SR is running fine.
But as i already removed the restore folder, i cant test the fix itself.

**Comment by abeloin** [comment]
@neoatomic You can try with empty restore folder

**Comment by neoatomic** [comment]
Tested with a empty restore folder, and after a restart the folder is gone. No errors.

After that i copy d my config.ini and sickbeard.db in the restore folder. Just to see what would happen. It did not restore them but gave this error. 
However it did remove my original config.ini and sickbeard.db. cache.db and failed.db

So that got me thinking. Would it be better to let SR rename the old config.ini etc. to config.bak. ?
So in-case the restore fails a user can restore/rename the config.bak.to config.ini?

```
2015-02-19 17:22:56 ERROR    EVENT-QUEUE :: DB error: attempt to write a readonly database
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/db.py", line 170, in action
    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/db.py", line 92, in execute
    raise e
OperationalError: attempt to write a readonly database
```

**Comment by abeloin** [comment]
It should already do this.

**Comment by fernandog** [comment]
@abeloin the restore process should keep permissions, shouldn't it? It's strange the "OperationalError: attempt to write a readonly database" error

**Comment by abeloin** [comment]
@neoatomic Are you sure you're at the latest commit in the develop branch?
I just tried like you did and it failed without deleting files.

**Comment by abeloin** [comment]
@neoatomic Can you provide me with the content of your sickrage directory with their permission(dir -lah)

**Comment by abeloin** [comment]
@fernandog That is a tricky situation in certain cases: move keeps the permissions and create inherit from the parent.

**Comment by neoatomic** [comment]
Ok, just did test some more.
Did a restore in the webui and SR again doesn't start.

(files after pushing the restore button)
![1](https://cloud.githubusercontent.com/assets/7928052/6272576/efe7945a-b868-11e4-8b97-e563f18a7cab.jpg)

(files after pushing the restart button)
![2 restart](https://cloud.githubusercontent.com/assets/7928052/6272575/eba757d6-b868-11e4-99dd-edc916403fb1.png)

As SR doesn't start i deleted the cache-xxxxxxxx and restore folder.
And SR does start again...

```
BRANCH: (develop) / COMMIT: (0499069d2903757ea5044e32e841567420a99b34) 
```

**Comment by abeloin** [comment]
Logs?

**Comment by neoatomic** [comment]
http://pastebin.com/QiQZLXPW

**Comment by abeloin** [comment]
@neoatomic Can you try applying this commit https://github.com/abeloin/SickRage/commit/3a0fa9068a678b6a5f143b88f08c42a39c419702 ?

Try redoing the restore with config.ini and sickbeard.db and it will create 2 files: update.log and restore.log

**Comment by neoatomic** [comment]
Replaced the SickBeard.py with the new one but SR doesnt want to start. :(
If i restore the origional SickBeard.py it runs ok.

**Comment by abeloin** [comment]
Did it create the files in DATA_DIR?

**Comment by neoatomic** [comment]
No. Sickrage didnt start...

**Comment by abeloin** [comment]
Can you manually start it via SSH?

**Comment by neoatomic** [comment]
Probably, but i dont know the command. 
Could you post it.?

**Comment by abeloin** [comment]
Where is your SickBeard.py located?

**Comment by neoatomic** [comment]
/volume1/@appstore/sickbeard-custom/var/SickBeard/SickBeard.py

**Comment by abeloin** [comment]
python /volume1/@appstore/sickbeard-custom/var/SickBeard/SickBeard.py --nolaunch --datadir=/volume1/@appstore/sickbeard-custom/var

**Comment by neoatomic** [comment]
Get this error :

```
/volume1/@appstore/sickbeard-custom/var/SickBeard$ python /volume1/@appstore/sickbeard-custom/var/SickBeard/SickBeard.py --nolaunch --datadir=/volume1/@appstore/sickbeard-custom/var
The Python module Cheetah is required
```

**Comment by neoatomic** [comment]
I tried this line : 

```
/volume1/@appstore/sickbeard-custom/var/SickBeard$ python /volume1/@appstore/sickbeard-custom/var/SickBeard/SickBeard.py --nolaunch --datadir=/volume1/@appstore/sickbeard-custom/var
The Python module Cheetah is required
/volume1/@appstore/sickbeard-custom/var/SickBeard$ /usr/local/sickbeard-custom/env/bin/python /usr/local/sickbeard-custom/var/SickBeard/SickBeard.py --daemon --pidfile /usr/local/sickbeard-custom/var/sickbeard-custom.pid --config /usr/local/sickbeard-custom/var/config.ini --datadir /usr/local/sickbea
Traceback (most recent call last):
  File "/usr/local/sickbeard-custom/var/SickBeard/SickBeard.py", line 542, in <module>
    SickRage().start()
  File "/usr/local/sickbeard-custom/var/SickBeard/SickBeard.py", line 281, in start
    fh.write('Closing Log\n')
UnboundLocalError: local variable 'fh' referenced before assignment
```

**Comment by abeloin** [comment]
Apply this cpy of SickBeard.py
 https://github.com/abeloin/SickRage/blob/ceb112e20dd662f1acdf0e9b8e6e9488e1acfa4e/SickBeard.py

**Comment by neoatomic** [comment]
Now i get this  one :

```
/volume1/@appstore/sickbeard-custom/var/SickBeard$ /usr/local/sickbeard-custom/env/bin/python /usr/local/sickbeard-custom/var/SickBeard/SickBeard.py --daemon --pidfile /usr/local/sickbeard-custom/var/sickbeard-custom.pid --config /usr/local/sickbeard-custom/var/config.ini --datadir /usr/local/sickbea
Traceback (most recent call last):
  File "/usr/local/sickbeard-custom/var/SickBeard/SickBeard.py", line 542, in <module>
    SickRage().start()
  File "/usr/local/sickbeard-custom/var/SickBeard/SickBeard.py", line 291, in start
    sickbeard.initialize(consoleLogging=self.consoleLogging)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/__init__.py", line 662, in initialize
    os.rmdir(os.path.join(DATA_DIR, 'restore'))
OSError: [Errno 39] Directory not empty: '/usr/local/sickbea/restore'
```

**Comment by abeloin** [comment]
your datadir string is incomplete in your command

**Comment by neoatomic** [comment]
I give up... Cant get it to run correctly...
A update.log was created but the only entry was "Closing Log"
I restored the original SickBeard.py and SR is starting again.

**Comment by fernandog** [comment]
@neoatomic --datadir /usr/local/sickbea

**Comment by neoatomic** [comment]
Did correct that, but didn't help...
Now i'm reinstalling for the third time to have a clean install.
Restoring is just not working for me. (again needed to remove the restore folder to get SR to boot)
I would like to tank you both for your help/support. Sorry that i could not help better with troubleshooting.

**Comment by abeloin** [comment]
@neoatomic No restore.log?

**Comment by abeloin** [comment]
@neoatomic I just figure out why it didn't work from your previous comment:
https://github.com/abeloin/SickRage/blob/patch-testing/sickbeard/__init__.py#L662

If you want to test.
