### ISSUE TITLE
Quality of downloaded shows not being detected correctly - "UNKNOWN"

### ISSUE THREAD

**Issue by andonevris** [SiCKRAGETV/sickrage-issues#666]
Since the last update sickrage is having problems detecting the quality of shows, it is reporting them as unknown.

It seems to be happening with mkv files mainly, I will need to wait for more shows to come in to test other formats but maybe others with the issue can confirm?

**Comment by fernandog** [comment]
@andonevris 
follow guidelines.
https://github.com/SiCKRAGETV/sickrage-issues/

I think I will increase the size of the "BEFORE OPEN AN ISSUE"

**Comment by andonevris** [comment]
Why did you close this, I am working on getting the info you need

Itchy trigger finger!

**Comment by fernandog** [comment]
when you reply I will open. rules are rules =)
When almost all issues don't follow guidelines you must do this. sorry

**Comment by andonevris** [comment]
OK this can remain closed.  I was under the impression that sickrage scanned the file itself to pick up the quality but from my research and looking at the logs this seems not to be the case it seems it's using the original filename to determine quality instead.  

It looks like MKVs without quality info in the filename are set as unknown, mp4 and others default to SDTV which seems inconsistent but I can live with it.

So it looks like this is not a bug but a "feature"

Cheers
