### ISSUE TITLE
Feature Request: make backup before sickrage update

### ISSUE THREAD

**Issue by gborri** [SiCKRAGETV/sickrage-issues#667]
I think that would be useful to start a backup process just before upgrading sickrage sw

**Comment by fernandog** [comment]
We have to add a setting to the config "Default backup directory". It's not that fast
It's a nice FR but now we are fixing things first.

**Comment by fernandog** [comment]
@gborri done! say thanks to @abeloin. nicely done!

**Comment by gborri** [comment]
@abeloin thanks.
