### ISSUE TITLE
[Mass Update][Subtitles] Box grayed out for most TV Shows

### ISSUE THREAD

**Issue by brimur** [SiCKRAGETV/sickrage-issues#668]
I cannot enable subtitle download for all Tv Shows. Ticking the box at the top only ticks some of the TV shows, the ones that are not grayed out. Going into any of the TV Shows that are grayed out I can enable subtitles.

**Comment by fernandog** [comment]
Screen shot please.

**Comment by fernandog** [comment]
The greys are paused?

**Comment by brimur** [comment]
No not paused.

http://i.imgur.com/swdct7e.png

**Comment by fernandog** [comment]
@brimur can you post the page code? 

Chrome: right mouse button, page code

**Comment by brimur** [comment]
If you need more let me know but this is what a typical line looks like...

````
<td align="center"><input type="checkbox" class="subtitleCheck" id="subtitle-101501" disabled="disabled" /></td>
````

**Comment by fernandog** [comment]
@brimur not an issue

		#if not $curShow.subtitles or $sickbeard.showQueueScheduler.action.isBeingSubtitled($curShow) or $sickbeard.showQueueScheduler.action.isInSubtitleQueue($curShow):
			#set $curSubtitle_disabled = "disabled=\"disabled\" "

if subtitle is queue to download it disables it

**Comment by brimur** [comment]
I don't understand what you mean. What is the solution to the problem? If I go into any of those shows Subtitles is not enabled so why would they be queued to download? How do I enable them through mass update?

**Comment by fernandog** [comment]
@brimur so if the show does not have subtitle enable you should enable in the show page not in mass update. 

If you don't want this try disable javascript and try to select them

**Comment by brimur** [comment]
Ok so is that a bug or a feature request since its already in the mass update but doesn't work? Would you know the SQL to enable that say using sqlite3? Thanks
