### ISSUE TITLE
Trakt error in logs

### ISSUE THREAD

**Issue by hoefs** [SiCKRAGETV/sickrage-issues#669]
Configuration
SR Version:	BRANCH: (master) / COMMIT: (ac153cf2320b3b6d0a8aa9a1b1646a51347581d6) 
SR Config file:	/usr/local/sickbeard-custom/var/config.ini
SR Database file:	/usr/local/sickbeard-custom/var/sickbeard.db
SR Cache Dir:	/usr/local/sickbeard-custom/var/cache
SR Arguments:	['--daemon', '--pidfile', '/usr/local/sickbeard-custom/var/sickbeard-custom.pid', '--config', '/usr/local/sickbeard-custom/var/config.ini', '--datadir', '/usr/local/sickbeard-custom/var/', '--nolaunch']
SR Web Root:	
Python Version:	2.7.8 (default, Dec 12 2014, 20:09:05) [GCC 4.6.4]

```
2015-02-19 17:45:41 DEBUG    TRAKTCHECKER :: Traceback (most recent call last):
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/traktChecker.py", line 55, in run
    self.syncLibrary()
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/traktChecker.py", line 83, in syncLibrary
    self.addShowToTraktLibrary(myShow)
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/traktChecker.py", line 120, in addShowToTraktLibrary
    if not self.findShow(show_obj.indexer, show_obj.indexerid):
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/traktChecker.py", line 63, in findShow
    library = self.trakt_api.traktRequest("sync/collection/shows") or []
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/lib/trakt/trakt.py", line 86, in traktRequest
    raise traktException(e)
traktException: 500 Server Error: Internal Server Error
```

**Comment by hoefs** [comment]
http://pastebin.com/yb05G9ze

**Comment by fernandog** [comment]
@hoefs please use develop

**Comment by fernandog** [comment]
@abeloin we still need to remove the RAISE from the code and change to log.logger WARNING

https://github.com/SiCKRAGETV/SickRage/pull/1330

**Comment by hoefs** [comment]
extra question: How can you sync your complete library with trakt? now it only adds the newly downloaded to trakt...

**Comment by fernandog** [comment]
can you try this?
stop SR, edit that file, paste the contents with this one
https://raw.githubusercontent.com/fernandog/SickRage/trakt_not_raise/lib/trakt/trakt.py
save and restart SR
test for a day or two and let me know

**Comment by hoefs** [comment]
replaced trakt.py

running SR, will report back

**Comment by TagForce** [comment]
@hoefs It should do just that when you enable Settings -> Notifications -> Social -> Trakt -> Sync Libraries.
It did for me.

**Comment by fernandog** [comment]
@TagForce does it sync entire library even for fully watched shows or just in-progress or not watched tv-shows?

**Comment by fernandog** [comment]
@hoefs please update and report back. fix was merged

**Comment by fernandog** [comment]
@hoefs
