### ISSUE TITLE
Removed scene exceptions keep being re-added

### ISSUE THREAD

**Issue by SunMar** [SiCKRAGETV/sickrage-issues#670]
Hi,

Whenever I remove some scene exceptions from a show they reappear a while later, it seems like SickRage keeps them up-to-date or something and with that re-adds any removed exceptions.

An example where I want to remove a scene exception is for the BCC show QI. There are two versions of the same episode, there's QI which is ~30m long and there's QI XL which is an extended version ~45m long.

For this show QI XL is among the scene exception list, but I don't want it to grab QI XL, I only want the standard version, not the extended one. However I can't seem to get rid of the QI XL names.

Sincerely,

SunMar.

Running SickRage on Windows 7 with Python 2.7.9 using the develop branch (commit hash 0499069d2903757ea5044e32e841567420a99b34).

**Comment by TagForce** [comment]
@SunMar SR looks up the scene_exceptions from http://midgetspy.github.io/sb_tvdb_scene_exceptions/exceptions.txt on every startup, when adding a show, when performing an episode search on providers.
So, yeah, if QI XL is one of the scene exceptions in that file it will be re-added.

I'll mark this a low priority feature request, with the feature request being adding the posibility of entering scene exception names that should never be used. That will be a change in the db, so might take a while to get done.

**Comment by SunMar** [comment]
I think it might be better to add an option that disables updating of the scene exceptions. It could be a show option.

If you can point me to the files where the scene exception update is done I can see if I can implement this feature myself.

**Comment by fernandog** [comment]
@SunMar you are trying to fix a fix that is simple to fix. Keep scene exceptions as it is and add "QI XL" to the ignored words. simple!

**Comment by SunMar** [comment]
Heh, d'oh!

Does ignored words respect word boundaries?

**Comment by fernandog** [comment]
sorry, didn't understand.

**Comment by TagForce** [comment]
@SunMar I have no idea... Just try, or check what the names of the releases are you're trying to avoid... Changes are they are named QI.XL which will work in ignored words.
