### ISSUE TITLE
oldpiratebay.org/tv/latest/ returned status code is 404

### ISSUE THREAD

**Issue by hoefs** [SiCKRAGETV/sickrage-issues#671]
SR Version:	BRANCH: (master) / COMMIT: (ac153cf2320b3b6d0a8aa9a1b1646a51347581d6) 
SR Config file:	/usr/local/sickbeard-custom/var/config.ini
SR Database file:	/usr/local/sickbeard-custom/var/sickbeard.db
SR Cache Dir:	/usr/local/sickbeard-custom/var/cache
SR Arguments:	['--daemon', '--pidfile', '/usr/local/sickbeard-custom/var/sickbeard-custom.pid', '--config', '/usr/local/sickbeard-custom/var/config.ini', '--datadir', '/usr/local/sickbeard-custom/var/']
SR Web Root:	
Python Version:	2.7.8 (default, Dec 12 2014, 20:09:05) [GCC 4.6.4]

2015-02-19 20:45:29 DEBUG    SEARCHQUEUE-MANUAL-276525 :: [OldPirateBay] :: Search string: https://oldpiratebay.org/tv/latest/
2015-02-19 20:45:29 DEBUG    SEARCHQUEUE-MANUAL-276525 :: [OldPirateBay] :: Requested url https://oldpiratebay.org/tv/latest/ returned status code is 404: Not Found

![screen shot 2015-02-19 at 20 49 30](https://cloud.githubusercontent.com/assets/7440522/6274594/e2ff9516-b878-11e4-86f5-53a11d519c1e.png)

**Comment by fernandog** [comment]
@hoefs 
it not our problem. Or does is seems so?
what did you expect?

**Comment by abeloin** [comment]
@hoefs This should fix the issue, can you try it?

**Comment by fernandog** [comment]
@hoefs any luck?

**Comment by hoefs** [comment]
how can I test the fix? (btw not at home for the moment...)

**Comment by fernandog** [comment]
stop SR, edit that file, change, save, start SR

**Comment by fernandog** [comment]
@hoefs please update and report back.

**Comment by fernandog** [comment]
@hoefs
