### ISSUE TITLE
low quality episodes being added to backlog when show quality is "any"

### ISSUE THREAD

**Issue by jaybone2012** [SiCKRAGETV/sickrage-issues#673]
Synology Diskstation DSM 5.1
SR Version:	BRANCH: (master) / COMMIT: (93f0f0ad1fa278afb17f73d47c099b82a766dede) 
Python Version:	2.7.8 (default, Dec 12 2014, 21:20:40) [GCC 4.7.3 20130102 (prerelease)]

Hey guys

I have a show that I have set to quality "Any".

I am happy with whatever quality is downloaded I don't care if HD or SD or Unknown or whatever, once i get a release and SickRage processes it I am done, full stop.

I have just discovered now that my backlog is full of all of these episodes from this show that are "Low Quality", presumably this means SickRage is still searching for a better quality?

Is there a way to deal with this other than setting them all to skipped? Do i need to explicitly set a quality other than "Any", iuf so what if SickRage does not recognize the quality and becomes unknown?

I don't want the backlog searching for these episodes, like i said before I am happy with the low quality for this particular show.

I do not have any archive settings configured.

**Comment by fernandog** [comment]
set "archive first match" for this show

**Comment by TagForce** [comment]
@jaybone2012 Are these episodes showing in the backlog Overview, or are they actually showing up in the logs as being searched for in the backlog?

If it's only in the backlog overview: that'll be overhauled so it actually only shows what's in the backlog instead of guessing which episodes are by checking the status and quality.

**Comment by jaybone2012** [comment]
They appear in the backlog overview even when archive on first match is selcted.

I am forcing backlog search now and will check the logs to see if they are being searched.

**Comment by jaybone2012** [comment]
Ok so logs say that nothing is required from this show.

I will wait for the backlog to be overhauled so it only shows what's in the backlog.

Cheers guys for the fast responses.

**Comment by fernandog** [comment]
@jaybone2012 now it only show wanted. and if first match is enabled, also does not show

**Comment by dkrowie** [comment]
Same problem here - anyway to force sickrage to see the wuaity of the show and thus remove from backlog?

**Comment by fernandog** [comment]
Re-scan show

**Comment by dkrowie** [comment]
didnt fix it .. even brand new shows which sickrage snatched and processed i.e. better call saul are appearing as download (unknown)

**Comment by fernandog** [comment]
enable Archive first match
