### ISSUE TITLE
[Feature Request] Search by absolute number for episode. No season (regex)

### ISSUE THREAD

**Issue by educatedwarrior** [SiCKRAGETV/sickrage-issues#677]
Branch  - master
Commit hash - 93f0f0ad1fa278afb17f73d47c099b82a766dede
Your operating system and python version - Freenas and Python 2.7.9

What you did  -   tried to download episode manually.
What happened  -   Unable to find download using search provider API. 
What you expected - The shows exist but are not found

Link to a copy/paste of your logfile with clear debug info of the error on PASTEBIN - http://pastebin.com/84aYS3qB

Below are specific api searches contained in the detail pastebin above that are not working.

```
2015-02-19 21:03:00 DEBUG    SEARCHQUEUE-MANUAL-79838 :: [NZBgeek] :: Search url: https://api.nzbgeek.info/api?apikey=&season=28&maxage=2375&cat=5030%2C5040&q=The.Bold.and.the.Beautiful&limit=100&attrs=rageid&offset=0&ep=32&t=tvsearch

2015-02-19 21:03:11 DEBUG    SEARCHQUEUE-MANUAL-79838 :: [Usenet-Crawler] :: Search url: https://www.usenet-crawler.com/api?apikey=&season=28&maxage=2375&cat=5030%2C5040&limit=100&attrs=rageid&offset=0&rid=5631&ep=32&t=tvsearch
```

**Comment by abeloin** [comment]
What is your full python version?

**Comment by educatedwarrior** [comment]
Python 2.7.9 (default, Jan 28 2015, 23:06:19)

**Comment by abeloin** [comment]
If you try this query in your browser, do you get any results(don't forget to add your api ky):
```https://api.nzbgeek.info/api?apikey=&season=28&maxage=2375&cat=5030%2C5040&q=The.Bold.and.the.Beautiful&limit=100&attrs=rageid&offset=0&ep=32&t=tvsearch```

**Comment by educatedwarrior** [comment]
For usenet-crawler I get the following.

 <rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:newznab="http://www.newznab.com/DTD/2010/feeds/attributes/" version="2.0">
<channel>
<atom:link href="https://www.usenet-crawler.com/api?apikey=&season=28&maxage=2375&cat=5030%2C5040&q=The.Bold.and.the.Beautiful&limit=100&attrs=rageid&offset=0&ep=32&t=tvsearch" rel="self" type="application/rss+xml"/>
<title>usenet-crawler</title>
<description>usenet-crawler Feed</description>
<link>https://www.usenet-crawler.com/</link>
<language>en-gb</language>
<webMaster>info@usenet-crawler.com (usenet-crawler)</webMaster>
<category/>
<image>
<url>
https://www.usenet-crawler.com/views/images/logo.png
</url>
<title>usenet-crawler</title>
<link>https://www.usenet-crawler.com/</link>
<description>Visit usenet-crawler - A quick usenet indexer</description>
</image>
<newznab:response offset="0" total="0"/>
</channel>
</rss>

**Comment by abeloin** [comment]
Is the show configure, to search by airdate? If not enable and redo a search

**Comment by educatedwarrior** [comment]
http://pastebin.com/dsa1REQb

**Comment by educatedwarrior** [comment]
I got the same exact response using your api url above (api key included).

**Comment by abeloin** [comment]
Ok so no results. You should do the same with your other newznab provider. But my hope aren't high.

Looking at the results from search engine, no wonder sickrage is having difficulties with that show:
* BB-25-09-2014
* The.Bold.And.The.Beautiful.-.E6903.-.Woensdag.03-09-2014
* The.Bold.And.The.Beautiful.-.S28.Ep7013.-.11.Febr.2015
* B&B-S27ep6858-ep6880

**Comment by educatedwarrior** [comment]
Results are very clean on usernet-crawler.  Check this out.

https://www.usenet-crawler.com/search?val=bold%20and%20the%20beautiful&index=3

The Bold And The Beautiful - S28 Ep7015 - 13 Febr 2015
The Bold And The Beautiful - S28 Ep7014 - 12 Febr 2015

**Comment by abeloin** [comment]
But the trouble is that air date search is done with "YYYY/mm/dd" not "dd Mmmm YYYY" which some weird results:
```
Parsed The.Bold.And.The.Beautiful.-.S28.Ep7013.-.11.Febr.2015 into The Bold And The Beautiful - S28 [ANIME VER: -1] [ABD: False] [ANIME: False] [whichReg: ['season_only']]
```

**Comment by educatedwarrior** [comment]
Why isn't it finding it by season and episode.   It looks clearly labelled in the reports.  Is it because the prefix for episode is EP   .   I was wondering for an api call , wouldn't the web api just look for the episode number and the prefix wouldn't matter?

**Comment by educatedwarrior** [comment]
I wonder if there is a bug in the Newsnab api since I believe there are all using the same backend web server?   I'm just brainstorming ... take what I say with a grain of salt.

**Comment by educatedwarrior** [comment]
Let me know whatever else you would like me to check, I'm unclear on how to proceed.  Thx

**Comment by abeloin** [comment]
It may look clearly label to you but not to newznab and sickrage.

The naming for those episode are bad, they use the season and the absolute number.

In usenet-crawler, all the recent episodes I've looked are all Season 01 Episode 701 so this is why you will never get any result searching via SxxExx.

**Comment by educatedwarrior** [comment]
Okay, I understand what you are saying now.  How about an option to search by absolute number.  That would be the ticket.  I agree, that is bad numbering.

**Comment by abeloin** [comment]
You can try set the show as anime which is absolute numbering but I don't it will work with the tvdb as nobody entered the absolute number, maybe with tvrage.

**Comment by educatedwarrior** [comment]
I'll give it a try later and let you know.  Tomorrow.  Going to bed for work tomorrow.

**Comment by educatedwarrior** [comment]
So I deleted the show, then re-added it as Anime.  Still not finding the show. 

Here is the log.  
http://pastebin.com/VGNJ1nG4

**Comment by fernandog** [comment]
@educatedwarrior there's nothing we can do if the uploader does not uses the correct name pattern

**Comment by educatedwarrior** [comment]
@fernandog  what about new feature request for custom search?  If I was able to substitute absolute number for episode number in the original search, I would be good to go.

**Comment by fernandog** [comment]
You need to create a new regex. Or wait DEVs create

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
