### ISSUE TITLE
[Feature Request] Update subliminal to v0.8

### ISSUE THREAD

**Issue by SunMar** [SiCKRAGETV/sickrage-issues#680]
Hi,

The subliminal version used is an old version (v0.6.3), there have been quite a few improvements in the new subliminal so it'd be nice if it can be updated to the newest version.

This is not easy though because 0.7 is not backwards compatible. 0.8 is current in development but also breaks backwards compatibility. In that regard it's probably easier to go directly to 0.8-dev. This is also done by the subliminal plugin for Plex.

I'm working on this myself atm (don't have a working version yet), it's a challange because subliminal has switched to using alpha3 instead of alpha2 and there are a lot of dependencies. The main reason for adding this issue is to see if there's anybody else also working on this and ask where best to go when I have questions regarding the code base.

Sincerely,

SunMar.

**Comment by fernandog** [comment]
@SunMar can you read all this?
https://github.com/SiCKRAGETV/sickrage-issues/issues/386

**Comment by fernandog** [comment]
when you say alpha2 means language with only two letter? Its strange cause KODI and everything else uses the 3 letter

**Comment by SunMar** [comment]
Yeah, the subtitle information saved in the database and what is used to save file extensions and such uses a two-letter language code, but in Subliminal 0.7 they switched to using a 3-letter language code to be more ISO-compatible (at least that's what I was able to discern, since I'm new to both SickRage and Subliminal I could be wrong about this).

I'll read the other issue as well.

**Comment by fernandog** [comment]
ok! 3-letter is better! This change and the issue change (DB update) must be done. But we won' merge any time soon. we are fixing bug first but you can try start making some tests
@TagForce @abeloin

**Comment by SunMar** [comment]
As I'm writing it right now a DB update wouldn't be neccesary (as of yet). Subliminal switched from an internal Language class to using a seperate library called Babelfish (by the same author). I'm simply rewriting the calls that instantiate subliminal.Language to use babelfish.Language.fromietf() which if it receives a 2-letter code converts it to a 3-letter code. That's something neccesary for the subtitle files (still want to support ".en.srt"), and I'm also using that for data from the config and database so that no migration/update is neccesary. Any codes that are saved are written back as 3-letter codes in both the config and the database.

**Comment by fernandog** [comment]
but what about saving the language in the history if user don't want the language in the filename? that info should be saved in the history(DB)

**Comment by SunMar** [comment]
It is. If I'm not mistaken it's in the subtitles column of tv_episodes, that's a comma separated list of subtitles downloaded. Currently that list is in 2-letter codes but I'm simply having those codes converted to a 3-letter code when it's read, that also means that when its saved back its saved as 3-letter code. It makes the change backwards compatible (no database or config update/migration needed), though it can cause some forward compatibility issues. Subliminal 0.6 supports 3-letter codes so that's not an issue, but the flags depend on a 2-letter code so I can see an issue there if people were to switch between versions. 

But for that comment I was mostly thinking about subtitles included in a torrent. If a torrent includes a ".en.srt" file then SickRage needs to detect it as English and not default to Undetermined simply because it's not a 3-letter code.

**Comment by fernandog** [comment]
I think that column it for not that. Can you confirm?
https://github.com/SiCKRAGETV/sickrage-issues/issues/386#issuecomment-74547479

**Comment by SunMar** [comment]
I think that column stores the downloaded subtitles, so it knows which subtitles to keep searching for in the backlog when you have multiple subtitle languages enabled, it however does not match a subtitle to a file, so in the history view it tries to base it on the filename and that fails somewhere. I'll see if I can find the cause when I have some time, hopefully over the weekend.

**Comment by fernandog** [comment]
@SunMar 

"I'm working on this myself atm (don't have a working version yet),"

any news on this?

**Comment by DisasteR** [comment]
neoatomic as you are working on the upgrade can you also add per provider user account management.
As this is a subliminal available feature.

thanks

**Comment by MGaetan89** [comment]
This was done a few days ago, no?
https://github.com/SiCKRAGETV/SickRage/commit/d8c80a49ede636a1b9d235713dd04f796f3bedcd

**Comment by fernandog** [comment]
0.7 AFAIK

**Comment by MGaetan89** [comment]
The `__init__.py` file says `0.8.0-dev`: https://github.com/SiCKRAGETV/SickRage/blob/develop/lib/subliminal/__init__.py

**Comment by neoatomic** [comment]
Indeed its the latest version 0.8 :)

Its currently in the Develop branch and we are dong the last tests before rolling it out to master.
We have to thank @miigotu for making this possible.

**Comment by fernandog** [comment]
yeah! thanks!

**Comment by neoatomic** [comment]
The subliminal 0.8 update was rolled out yesterday to master. :)
