### ISSUE TITLE
[APP SUBMITTED]: coercing to Unicode: need string or buffer, instance found

### ISSUE THREAD

**Issue by rickytin** [SiCKRAGETV/sickrage-issues#681]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@ac153cf2320b3b6d0a8aa9a1b1646a51347581d6
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: coercing to Unicode: need string or buffer, instance found
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/658
