### ISSUE TITLE
Error on manual search from web on upcoming shows.

### ISSUE THREAD

**Issue by faidwen** [SiCKRAGETV/sickrage-issues#684]
-----
 BRANCH: (develop) / COMMIT: (55d0d213e48909ca5944260e937be72b693a7b8b) 
 Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36) [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]
-----
  File "/root/.sickrage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/root/.sickrage/sickbeard/webserve.py", line 1864, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "/root/.sickrage/sickbeard/webserve.py", line 1827, in getEpisodes
    showObj = sickbeard.helpers.findCertainShow(sickbeard.showList, int(show))
ValueError: invalid literal for int() with base 10: 'undefined'

(no idea why python version is bolded LOL)

**Comment by fernandog** [comment]
Please update SR

**Comment by faidwen** [comment]
KK thanks

**Comment by faidwen** [comment]
fernandog, how is this not the most recent commit??

**Comment by faidwen** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/637

**Comment by fernandog** [comment]
Dont hijack others issue

**Comment by faidwen** [comment]
Well, I guess even though this is closed, I will continue to post on it in the hopes that someone will realize that it is the same issue as https://github.com/SiCKRAGETV/sickrage-issues/issues/637 except that we aren't passing in the Trakt info, instead we are passing in the manual show information, but that SHOW in the following line is obviously NONE or at least not convertible into an integer.

def getManualSearchStatus(self, show=None, season=None):
def getEpisodes(searchThread, searchstatus):
results = []
+ showObj = sickbeard.helpers.findCertainShow(sickbeard.showList, int(show))

Also, there may be issues between the two Python versions IE: mine is 2.6 whereas there's is 2.7, hence the differing error results.

This code was JUST changed by Abeloin in https://github.com/SiCKRAGETV/SickRage/commit/794b30eca0028d369d43c31e6115f4e1255259b4 and the issue is around line 1827 and the INT(SHOW) portion.  show=None.   Seeing as this was JUST changed within the last 14 hours, I don't see how this is an OLD issue.

Obviously you folks know more than I do, but I was just trying to help, and give you AS MUCH information as humanly possible.  I apologize in advance if it was unwarranted and / or not helpful.

**Comment by fernandog** [comment]
Main issue:
https://github.com/SiCKRAGETV/sickrage-issues/issues/285

https://github.com/SiCKRAGETV/sickrage-issues/issues/210
https://github.com/SiCKRAGETV/sickrage-issues/issues/344
https://github.com/SiCKRAGETV/sickrage-issues/issues/374
https://github.com/SiCKRAGETV/sickrage-issues/issues/393
https://github.com/SiCKRAGETV/sickrage-issues/issues/381

feel free to read all of them

do a full refresh for all your tv-shows

**Comment by faidwen** [comment]
Thank you fernandog, I will try that now.

**Comment by abeloin** [comment]
What were you doing when that error happend?

**Comment by abeloin** [comment]
@faidwen Can you provide more log of that error?

**Comment by faidwen** [comment]
I have refreshed ALL shows (rescanned them all).

In UPCOMING EPISODES I clicked on manual search for a show.

**Comment by fernandog** [comment]
@faidwen error still persists?  can you please send a full log?  use pastebin.com

**Comment by faidwen** [comment]
2015-02-20 13:27:05 ERROR    Thread-274 :: Failed doing webui callback: Traceback (most recent call last):
AAValueError: invalid literal for int() with base 10: 'undefined'
AA    showObj = sickbeard.helpers.findCertainShow(sickbeard.showList, int(show))
AA  File "/****/.sickrage/sickbeard/webserve.py", line 1828, in getEpisodes
AA    episodes += getEpisodes(searchThread, searchstatus)
AA  File "/****/.sickrage/sickbeard/webserve.py", line 1865, in getManualSearchStatus
AA    result = function(**kwargs)
AA  File "/****/.sickrage/sickbeard/webserve.py", line 230, in async_call
AA    result = self.fn(*self.args, **self.kwargs)
AA  File "/****/.sickrage/lib/concurrent/futures/thread.py", line 61, in run
AA    exec('raise exc_type, exc_value, traceback', {}, locals_)
AA  File "/****/.sickrage/lib/concurrent/futures/_compat.py", line 107, in reraise
AA    reraise(self._exception, self._traceback)
AA  File "/****/.sickrage/lib/concurrent/futures/_base.py", line 359, in __get_result
AA    return self.__get_result()
AA  File "/****/.sickrage/lib/concurrent/futures/_base.py", line 400, in result
AA    lambda future: callback(future.result()))
AA  File "/****/.sickrage/tornado/concurrent.py", line 226, in 
AA    ret = fn(*args, **kwargs)
AA  File "/****/.sickrage/tornado/stack_context.py", line 314, in wrapped
AA    raise_exc_info((type, value, traceback))
AA  File "/****/.sickrage/tornado/web.py", line 1292, in _stack_context_handle_exception
AATraceback (most recent call last):
AAHTTPServerRequest(protocol='http', host='192.168.255.166:8081', method='GET', uri='/home/getManualSearchStatus?show=undefined', version='HTTP/1.1', remote_ip='192.168.255.100', headers={'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.255.166:8081', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://192.168.255.166:8081/comingEpisodes/', 'Cookie': 'plushContainerWidth=100%25; plushMultiOps=1; plushNoTopMenu=0; snatched_view2=list; soon_view2=thumbs; suggestions_charts_menu_selected=charts; late_view2=list; advanced_toggle_checked=1; manage_view2=details; wanted_view2=details; plushHistPerPage=10'})
AA2015-02-20 13:27:02 ERROR    Uncaught exception GET /home/getManualSearchStatus?show=undefined (192.168.255.100)

**Comment by faidwen** [comment]
Yes, one moment and I will upload the log.

http://pastebin.com/62AEWW1Y

**Comment by fernandog** [comment]
@faidwen please update and report back

**Comment by faidwen** [comment]
I am still receiving the following error with the new code on version BRANCH: (develop) / COMMIT: (dc6e4c6816c3d2226e019fdab656005dd8f6c9f5) 

2015-02-20 20:57:31 Thread-15 :: Failed doing webui callback: Traceback (most recent call last):
  File "/root/.sickrage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/root/.sickrage/sickbeard/webserve.py", line 1873, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "/root/.sickrage/sickbeard/webserve.py", line 1833, in getEpisodes
    showObj = sickbeard.helpers.findCertainShow(sickbeard.showList, int(show))
ValueError: invalid literal for int() with base 10: 'undefined'


I added a line to log what show was when it hit this area, and it is returning the following:

logger.log(u"**** Show = !" + show + "!", logger.WARNING)

2015-02-20 20:57:31 WARNING  Thread-15 :: **** Show = !undefined!

But I might be calling the logger incorrectly......  Hope this helps.

**Comment by fernandog** [comment]
@faidwen what are the steps to reproduce it? I can't!

**Comment by fernandog** [comment]
@faidwen I reverted boths commits. the original and my possible fix. 
update and report back please

**Comment by faidwen** [comment]
Perplexing, I will keep trying to troubleshoot.

Most recent log http://pastebin.com/V2sRDeRr

THANK you for your patience1

**Comment by fernandog** [comment]
@faidwen we merged a new code to "displayshow" page. can you test it?
