### ISSUE TITLE
[APP SUBMITTED]: invalid literal for int() with base 10: 'undefined'

### ISSUE THREAD

**Issue by djack42** [SiCKRAGETV/sickrage-issues#692]
### INFO
Python Version: **2.7.1 (r271:86832, Aug 23 2014, 08:54:18) 
[GCC 4.8.3 20140401 (prerelease)]**
Operating System: **Linux-3.14.14-armv7l-with-glibc2.4**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@62f45524eb9f1e3762a22af0bcd576e4285bad52
Link to Log: https://gist.github.com/80a08370433103aa2fb3
### ERROR
```
Thread-62 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1864, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "/opt/sickrage/sickbeard/webserve.py", line 1827, in getEpisodes
    showObj = sickbeard.helpers.findCertainShow(sickbeard.showList, int(show))
ValueError: invalid literal for int() with base 10: 'undefined'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@abeloin another one

**Comment by djack42** [comment]
Better log :

AAValueError: invalid literal for int() with base 10: 'undefined'
AA    showObj = sickbeard.helpers.findCertainShow(sickbeard.showList, int(show))
AA  File "/opt/sickrage/sickbeard/webserve.py", line 1827, in getEpisodes
AA    episodes += getEpisodes(searchThread, searchstatus)
AA  File "/opt/sickrage/sickbeard/webserve.py", line 1864, in getManualSearchStatus
AA    result = function(**kwargs)
AA  File "/opt/sickrage/sickbeard/webserve.py", line 230, in async_call
AA    result = self.fn(*self.args, **self.kwargs)
AA  File "/opt/sickbeard/lib/concurrent/futures/thread.py", line 61, in run
AA    exec('raise exc_type, exc_value, traceback', {}, locals_)
AA  File "/opt/sickbeard/lib/concurrent/futures/_compat.py", line 107, in reraise
AA    reraise(self._exception, self._traceback)
AA  File "/opt/sickbeard/lib/concurrent/futures/_base.py", line 359, in __get_result
AA    return self.__get_result()
AA  File "/opt/sickbeard/lib/concurrent/futures/_base.py", line 400, in result
AA    lambda future: callback(future.result()))
AA  File "/opt/sickrage/tornado/concurrent.py", line 226, in 
AA    ret = fn(*args, **kwargs)
AA  File "/opt/sickrage/tornado/stack_context.py", line 314, in wrapped
AA    raise_exc_info((type, value, traceback))
AA  File "/opt/sickrage/tornado/web.py", line 1292, in _stack_context_handle_exception
AATraceback (most recent call last):
AAHTTPServerRequest(protocol='http', host='192.168.1.50:8081', method='GET', uri='/home/getManualSearchStatus?show=undefined', version='HTTP/1.1', remote_ip='192.168.1.29', headers={'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'Host': '192.168.1.50:8081', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Linux; Android 4.4.4; Nexus 7 Build/KTU84Q) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.109 Safari/537.36', 'Dnt': '1', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://192.168.1.50:8081/comingEpisodes/'})
AA2015-02-21 00:22:26 ERROR    Uncaught exception GET /home/getManualSearchStatus?show=undefined (192.168.1.29)
2015-02-21 00:22:26 DEBUG    SEARCHQUEUE-MANUAL-279827 :: [Rarbg] :: Rarbg downloading url :https://rarbg.com/torrents.php?search=Aldnoah.Zero.19&category[]=18;41

**Comment by fernandog** [comment]
@djack42  please update and report back

**Comment by djack42** [comment]
Updated and triggered manual searches on the sames episodes and it seems it is fixed. Thx
I got the following error though :
2015-02-21 10:43:56 SEARCHQUEUE-MANUAL-114801 :: [Rarbg] :: Error while searching Rarbg, skipping: フ
Should i report it ?
