### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/mnt/tv/Modern Family/Season 6/Modern Family S06E15 Fight or Flight SD TV.mp4'

### ISSUE THREAD

**Issue by Kallb123** [SiCKRAGETV/sickrage-issues#696]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:38) 
[GCC 4.8.2]**
Operating System: **Linux-3.13.0-32-generic-i686-athlon-with-Ubuntu-14.04-trusty**
Branch: **master**
Commit: SiCKRAGETV/SickRage@ac153cf2320b3b6d0a8aa9a1b1646a51347581d6
Link to Log: https://gist.github.com/dcf0aedaa48e2b5ee28a
### ERROR
```
Thread-22 :: Unable to copy file /mnt/downloads/tv/Modern.Family.S06E15.HDTV.x264-LOL.mp4 to /mnt/tv/Modern Family/Season 6/Modern Family S06E15 Fight or Flight SD TV.mp4: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@Kallb123 can you send a screen shot of your PP settings?

**Comment by Kallb123** [comment]
Fails to process any episodes, manually or automatically. It's set to Copy, S&P every 10 mins. No Unpacking (it was enabled but I disabled it to test).

After exploring a bit more, I can see the files in Putty and Windows, but I can't open the files in VLC like I should be able to. May not be a SR issue, but a Transmission error. This is all (6) completed downloads though.

**Comment by Kallb123** [comment]
@fernandog http://i.imgur.com/4bOZ4ge.png

Below that is unchecked items.

**Comment by fernandog** [comment]
@Kallb123 maybe transmission is still moving them?
do you have transmission option to add .part to incomplete files?
do you have a separated folder to incomplete and complet at transmission (you should)

**Comment by Kallb123** [comment]
@fernandog 
1. I don't think so as all items have appeared, not like it's stuck copying one.
2. I'm not sure where the option is, but I observed .part being added via putty when I looked in the incomplete directory.
3. Yep.

Here's a screenshot of completed downloads: http://i.imgur.com/dVE4tqW.png
They won't even open in VLC via samba. Thought it might be permissions, but I've set 777 just to test and still nothing.

**Comment by fernandog** [comment]
that's strange!
but M@dern f@mily is there and this issue is about it

**Comment by Kallb123** [comment]
@fernandog It is. It's happening with every file listed there too. Maybe ownership permissions issue? That's what Windows says: 
http://i.imgur.com/3qMTSVi.png

**Comment by Kallb123** [comment]
Not sure if it helps, but almost all the folders involved are being mapped onto virtual machines. Pretty sure it's set up right as I can move files back and forth between host and client, just transmission is outputting them strange.

**Comment by fernandog** [comment]
@TagForce any thoughts?

**Comment by abeloin** [comment]
@Kallb123 Can you provide the following:
* User running Transmission
* Group membership for that user
* User running SickRage
* Group membership for that user
* File permission,owner and group for /mnt/downloads/tv/Modern.Family.S06E15.HDTV.x264-LOL.mp4
* File permission,owner and group for /mnt/tv/Modern Family/Season 6/

**Comment by fernandog** [comment]
@Kallb123 can you check if this torrent file there were a folder with the name of the episode and the episode itself inside it? Maybe PP up the file one level and delete the folder.
@TagForce can this happen?

**Comment by Kallb123** [comment]
@fernandog there's a variety of different torrents, some within folders, some files directly inside "downloads". All are failing. 

I'm sure it's something to do with permissions and it being a virtual machine. I'll provide the details @abelion asked for later today.

**Comment by Kallb123** [comment]
@abeloin and @fernandog 

The details are as follows:
1. debian-transmission is the one running transmission
2. debian-transmission belongs only to a group called debian-transmission
3. Looking at the results of a top command, it appears python is the process doing the hard work of SR. The user is kallum.
4. kallum belongs to: kallum adm cdrom sudo dip plugdev lpadmin sambashare
5. ls -l outputs: -rwxrwxrwx 1 kallum  users
6. ls -l outputs: drwxrwxrwx 2 kallum users

With this being running in a virtual machine, /mnt/tv/Modern Family/Season 6/ is actually /mnt/disk2/TV Shows/Modern Family/Season 6/ on the host and has permissions as follows: drwxrwxrwx 2 kallum users

Both the host and virtual machine have the main user of kallum. It was on the host that I did chmod and chown. There is a second virtual machine with the exact same setup, except it runs Plex. The drives/directories are setup the same. Plex has no problem playing any of my existing library. I just need to get SR/Transmission (or the permissions) working.

**Comment by Kallb123** [comment]
It seems I missed a big part on installing tranmission. I needed to add kallum tothe group debian-transmission, set the folders to be owned by debian-transmission, and set transmission's umask setting to 2 instead of 18.

This has allowed me to view the files in Windows VLC (via samba share). This hasn't managed to allow SR to PP the files. I've redownloaded some of the files, forced processing of already processed files, but still errors. How can I be sure that SR is using the user kallum to run? I can only really see Python eating CPU when I mess with SR , so I assumed it was that process.

**Comment by fernandog** [comment]
Check /etc/default/sickrage or sickbeard

**Comment by Kallb123** [comment]
@fernandog The home directories show 'kallum' is running SR, as I thought.

I appear to be running into problems with the VMs. I can't make folders in the mounted directories without sudo. So it might be that the destination doesn't exist because it can't create the file.

**Comment by fernandog** [comment]
Do you know why its not supported?
@Tagforce @abeloin i think SR should test writing to PP folder before "accept" it and save it

**Comment by fernandog** [comment]
@Kallb123 try rsync instead of cp

**Comment by fernandog** [comment]
@Kallb123 any kucky?

**Comment by Kallb123** [comment]
@fernandog sorry, I didn't try rsync yet. I've found out that the disks having these problems are ReiserFS. It doesn't seem to play nicely with VMs. I can't mkdir or cp if the destination is on ReiserFS drive. Is it worth testing rsync? I'm in the process of shuffling data on 1 disk to format the other etc...

**Comment by fernandog** [comment]
Try please! If rsync works will help others.

**Comment by Kallb123** [comment]
@fernandog 
rsync -avz show.mp4 /mnt/tv/
sending incremental file list
show.mp4
rsync: mkstemp "/mnt/tv/.show.mp4.bEI0N4" failed: Operation not supported (95)

sent 128,859,843 bytes  received 154 bytes  9,545,184.96 bytes/sec
total size is 129,273,698  speedup is 1.00
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.0]


show.mp4 doesn't show up in /mnt/tv :(

**Comment by fernandog** [comment]
@Tagforce @abeloin i think SR should test writing to PP folder before "accept" it and save it. And tell user he can't PP to that folder "Operation not supported by your OS and setup"

**Comment by Kallb123** [comment]
@fernandog I like that idea. "No such file or directory" is so generic. I thought it was talking about the source file, but it was actually that it couldn't create the target file in my case.

**Comment by fernandog** [comment]
the target are a ftp?
see this:
http://www.jotschi.de/Uncategorized/2012/04/17/rsync-to-ftp-operation-not-supported-95.html

can you try that solution?

**Comment by Kallb123** [comment]
@fernandog Not FTP, just another disk within the same PC. It was using ReiserFS and being mapped into a VM. One of those things doesn't like to the other, so I'm in the process of shuffling data around to format my drives to LVM/ext4.

**Comment by fernandog** [comment]
@Kallb123 but can you try that solution?

**Comment by Kallb123** [comment]
@fernandog not really, my drives are being formatted :P I highly doubt it would work anything as it was temp files that refused to be made, but any file in general.

**Comment by abeloin** [comment]
@Kallb123 Definitelly a permissions issue as per the results of your previous comments https://github.com/SiCKRAGETV/sickrage-issues/issues/696#issuecomment-75377036
But if 5 an  6 are both owned by kallum and sickrage run as kallum there shouldn't be any error. Check your sickrage startup script to see which user is running sickrage.

In the end, you should have both user share the same group so they can access the files.

**Comment by Kallb123** [comment]
@abeloin I'm a noob to VMs and it's taking a while to get my head around the permissions. I'm getting there. I'm also in the process of formatting as ext4 instead of ReiserFS, going to take till tomorrow morning to transfer files to backup though. I have 1 drive as ext4 and I seem to have the ability to mkdir/nano without using sudo from within VM and permissions on host seem good too.

**Comment by fernandog** [comment]
@abeloin
what about this
https://github.com/SiCKRAGETV/sickrage-issues/issues/696#issuecomment-75398524
maybe change the log message to permissions warning. What do you think?

**Comment by abeloin** [comment]
@Kallb123 This is part of script that create the basic structure I use. It can give you idea on how-to implement your structure so that all authorized users can have access to the file. https://gist.github.com/abeloin/cbe1235eec3a9d7899a4

**Comment by abeloin** [comment]
@fernandog yes

**Comment by abeloin** [comment]
@fernandog It already check if the folder exist:
```
2015-02-21 01:37:50 DEBUG    Thread-22 :: Checking if the path /mnt/tv/12 Monkeys/Season 1 already exists
```
But the weird thing is that it failed on the chmod not on the copy, like you have write access on the destination but not read or list.

**Comment by fernandog** [comment]
Is that possible?!
check if exists if diff from move/copy a dummy file isnt?

**Comment by abeloin** [comment]
If the permission on the folder doesn't contain r but only x that can happen

**Comment by Kallb123** [comment]
@abeloin @fernandog 
My setup was awful. The disks were using ReiserFS and mapped through to the VM that SR was operating in. The permissions were a mess.
I've formatted to LVM/ext4, got the users and permissions setup in a way where everything works, and SR is working perfectly (as well as Transmission).

So, not sure how you want to handle the error, but my specific problem is solved.

**Comment by fernandog** [comment]
@abeloin can we test permission and test cp/mv a dummy file before accepting the PP folder? What do you think? We need to avoid this kind of issues in the future.

**Comment by abeloin** [comment]
Has for more test I think it's unnecessary(since this a edge case) but we can be more descriptive about why it failed. 
e.g:
```
2015-02-21 01:37:50 ERROR Thread-22 :: Unable to copy file /mnt/test.mp4 to /mnt/tv/test.mp4: error 2 : No such file or directory 
```
to
```
2015-02-21 01:37:50 ERROR Thread-22 :: Unable to copy file /mnt/test.mp4 to /mnt/tv/test.mp4: Failed to copy permissions
```

**Comment by abeloin** [comment]
@fernandog @TagForce By the way I think we should ask ourselves if these "error" should be reclassified as warning as they are not issue with sickrage but issue on how the user setup their system

**Comment by fernandog** [comment]
Yes. Warning. Agree.

**Comment by Kallb123** [comment]
@abeloin @fernandog  I know you weren't asking me, but as a user, if the action fails it should throw an error.

**Comment by fernandog** [comment]
error is something SR should fix.
warning not.

**Comment by Kallb123** [comment]
But at warning level there would be no indicator (top right error) that anything went wrong, I would likely delete the sources files and then wonder why I can't watch latest episode. As a user I need to see PP failed for an episode, whether it's SR fault or mine. If SR doesn't tell me (I'm not scouring logs constantly for warning level) then I'll not know.

**Comment by abeloin** [comment]
@Kallb123 It depend on how you classify an error, in this case it is a user_error not a software_error. So you should not be able to submit an issue to github.
So they should be consider as a warning for the system but as an error for the user.

**Comment by Kallb123** [comment]
@abeloin That sounds good, as long as I get a little (1) in my "Logs & Errors". I agree that it shouldn't be reportable to GitHub.
