### ISSUE TITLE
[APP SUBMITTED]: exception: access violation writing 0x00003EA0

### ISSUE THREAD

**Issue by bitzorro** [SiCKRAGETV/sickrage-issues#698]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@62f45524eb9f1e3762a22af0bcd576e4285bad52
### ERROR
```
POSTPROCESSER :: Failed Unrar archive the.flash.2014.114.hdtv-lol.rar: exception: access violation writing 0x00003EA0
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Can you confirm permissions ?

**Comment by bitzorro** [comment]
Absolutly nothing wrong with permissions, been running the same system for 6 months.

**Comment by fernandog** [comment]
Is it possible to try again the same file?

**Comment by bitzorro** [comment]
cant really tell wy this Error pops up ? the file have been auto-processed and is playable in my library!

**Comment by bitzorro** [comment]
And just now it gave me the same Error again.

**Comment by fernandog** [comment]
same file or different one?
can you post a full debug log?

**Comment by bitzorro** [comment]
Same file ! il try to post the debug log later, my son is using the machine for gaming :) im not allowed to touch it right now...

**Comment by fernandog** [comment]
=) no problem! I get it.

**Comment by abeloin** [comment]
Related to this?
https://github.com/SiCKRAGETV/sickrage-issues/issues/451

**Comment by bitzorro** [comment]
@fernandog 
there is nothing in the debug-logs for the past 3 days!
here is the logg:   http://pastebin.com/Jjdcd4fw

**Comment by fernandog** [comment]
See abeloin comment please

**Comment by bitzorro** [comment]
@abeloin   @fernandog 
Exeppt from this message: exception: access violation writing 0x00003EA0
 I cant say its related to #451

**Comment by abeloin** [comment]
@bitzorro 

Open a command line and go to the folder lib/unrar2/
Try running test_UNRAR2.py(replace to your python path):
```
c:\python27\python.exe test_UNRAR2.py
```

Tell me the results

**Comment by bitzorro** [comment]
@abeloin  im no data genius...  This is the path to my unrar2: c:\python27\python.exe test_UNRAR2.py
Can you please give me the exact command to run in the cmd ?

This command    C:\Windows\system32>c:\python27\python.exe test_UNRAR2.py


gave this reult:
c:\python27\python.exe: can't open file 'test_UNRAR2.py': [Errno 2] No such file
 or directory

i dont thing im doing it right.?

regards bitzorro.

**Comment by fernandog** [comment]
@bitzorro 

c:\python27\python.exe /SickRage/lib/unrar2/test_UNRAR2.py

**Comment by bitzorro** [comment]
@abeloin  
@abeloin 
ok here is the message from cmd:
C:\Windows\system32>c:\python27\python.exe /SickRage/lib/unrar2/test_UNRAR2.py
Traceback (most recent call last):
  File "/SickRage/lib/unrar2/test_UNRAR2.py", line 20, in <module>
    rarc = UnRAR2.RarFile('test.rar')
  File "C:\SickRage\lib\unrar2\__init__.py", line 100, in __init__
    RarFileImplementation.init(self, password)
  File "C:\SickRage\lib\unrar2\windows.py", line 244, in init
    RARSetCallback(self._handle, self.c_callback, 1)
WindowsError: exception: access violation writing 0x00003EA0

**Comment by bitzorro** [comment]
@fernandog

**Comment by fernandog** [comment]
That rar is passworded. Maybe fake release. Can you try to unrar in desktop?

**Comment by bitzorro** [comment]
@fernandog @abeloin 
the Error keeps on coming back, this is from themost recent log:2015-02-22 09:53:06 POSTPROCESSER :: Failed Unrar archive the.flash.2014.114.hdtv-lol.rar: exception: access violation writing 0x00003EA0

The strange thing about it, is that the episode is unpacked to my library and the source and torrent is deleted several days ago !

**Comment by fernandog** [comment]
maybe the .rar file as not deleted

**Comment by abeloin** [comment]
@bitzorro Some more questions:
Windows x32 or x64?
Python x32 or x64?
Winrar installed?

**Comment by bitzorro** [comment]
@abeloin

Windows x32 
Python  x32
winrar installed.

**Comment by abeloin** [comment]
Can you edit lib\unrar2\windows.py and insert before line 75(unrar = ctype):
```
    print("First ctypes")
```
then re-run ```c:\python27\python.exe /SickRage/lib/unrar2/test_UNRAR2.py``` and let me know if you see "First ctypes"

**Comment by bitzorro** [comment]
@abeloin 

This is how my windows.py  looks after edit, is this correct?

    unrar = First ctypes.WinDLL(os.path.join(os.path.split(__file__)[0], 'UnRARDLL', dll_name))
except WindowsError:
    unrar = ctypes.WinDLL(dll_name)


And this is the message cmd givs me .

C:\Users\alex gamecenter>c:\python27\python.exe /SickRage/lib/unrar2/test_UNRAR2
.py
Traceback (most recent call last):
  File "/SickRage/lib/unrar2/test_UNRAR2.py", line 6, in <module>
    import unrar2 as UnRAR2
  File "C:\SickRage\lib\unrar2\__init__.py", line 45, in <module>
    from windows import RarFileImplementation
  File "C:\SickRage\lib\unrar2\windows.py", line 75
    unrar = First ctypes.WinDLL(os.path.join(os.path.split(__file__)[0], 'UnRARD
LL', dll_name))
                       ^
SyntaxError: invalid syntax

C:\Users\alex gamecenter>

**Comment by abeloin** [comment]
Here what it should after adding the line:
```
...
try:
    print("First ctypes")
    unrar = ctypes.WinDLL(os.path.join(os.path.split(__file__)[0], 'UnRARDLL', dll_name))
except WindowsError:
    unrar = ctypes.WinDLL(dll_name)
...
```

**Comment by bitzorro** [comment]
@abeloin 
Ok, same result as earlyer i think ?

C:\Windows\system32>c:\python27\python.exe /SickRage/lib/unrar2/test_UNRAR2.py
First ctypes
Traceback (most recent call last):
  File "/SickRage/lib/unrar2/test_UNRAR2.py", line 20, in <module>
    rarc = UnRAR2.RarFile('test.rar')
  File "C:\SickRage\lib\unrar2\__init__.py", line 100, in __init__
    RarFileImplementation.init(self, password)
  File "C:\SickRage\lib\unrar2\windows.py", line 245, in init
    RARSetCallback(self._handle, self.c_callback, 1)
WindowsError: exception: access violation writing 0x00003EA0

**Comment by abeloin** [comment]
Is winrar listed in the PATH variable?

**Comment by bitzorro** [comment]
@abeloin 
I dont even know what that is ?

**Comment by fernandog** [comment]
Do you have WinRar/UNRAR installed?

Open CMD and type unrar. Report back

**Comment by bitzorro** [comment]
@fernandog  @abeloin 

im realy sorry guys, ive made a fool of my self!
i found the  .rar files that i was sure that was deleted !
i have now deleted it and the error isnt coming up again.
Sorry for taking up your time, i know you have big things to deal with!
Anyway, really happy about the great job you are doing for Sickrage and ous/users!
And thanks for really trying to help me.

Regards bitzorro

**Comment by bitzorro** [comment]
@fernandog  @abeloin 
Please close this, no issue!

**Comment by fernandog** [comment]
What really happened?

**Comment by bitzorro** [comment]
@fernandog 
i thougt that .rar file that was giving me Errors in the logs was deleted, but after searching in my folders i found the .rar file and deleted it!
and no more errors !  :)

**Comment by fernandog** [comment]
Was it a fake release?

**Comment by bitzorro** [comment]
@fernandog
sorry i newer tested it in winrar, but sickrage have post-proscessed the rars and the episode is in my library and working.

**Comment by fernandog** [comment]
@abeloin is there something we can do to prevent this in the future? it's an user-error, not system-error.

**Comment by bitzorro** [comment]
@fernandog 
I will absolutly test the file if it happens again, and let you know.

**Comment by fernandog** [comment]
Maybe SR was trying to extract again the same file and was denied

**Comment by abeloin** [comment]
@fernandog It's system error, it's unable to load unrar.dll

**Comment by abeloin** [comment]
@fernandog I don't know how to prevent it in the future
