### ISSUE TITLE
[Feature Request] Add archive option to manual post process

### ISSUE THREAD

**Issue by antoniong** [SiCKRAGETV/sickrage-issues#699]
Sometimes I had to manually add an episode. Next I do a rescan. Problem is that the manually added episode often is not in the same quality as I have set in SR. As a result this episode stays in Backlog because the quality differs. Now I have to correct this myself.

It would be a nice feature when SR discovers a new episode that has been manually added that SR would accept this as the final and not add it to the Backlog.

An even better solution would be when SR upon searching for episodes in the backlog would detect that the particular episode is already there and then remove it from backlog.

Incase not everybody would like this to be a default feature it could be activating by setting or unsetting a checkbox.

**Comment by xstefanx** [comment]
I'd be interested in a way to give SR the direct link to the download and let it handle things from there for episodes like this. That way PP can take place and for those of us on torrents, seeding and proper renaming can take place and SR see's the download all with one manual action for those you have to get manually anyway.

**Comment by Thraxis** [comment]
I'm confused.  Isn't this exactly the situation that Manual Post-Processing is designed to take care of?

**Comment by abeloin** [comment]
@xstefanx Set your show "Archive on first match" and manually PP the episode with force.

**Comment by OmgImAlexis** [comment]
I think the easiest way to "add" this would be to just add an option to the manual post process to archive the files it finds, just like we have the force option.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
