### ISSUE TITLE
Downloads column is empty when only series of anime

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#7]
<a href="https://github.com/h3llrais3r"><img src="https://avatars.githubusercontent.com/u/1945295?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [h3llrais3r](https://github.com/h3llrais3r)**
_Thursday Nov 20, 2014 at 17:52 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/926 (6 comment(s))_

----

Branch: master

last commit: 36c7831

OS: windows 7 and 8

browser: Chrome

Python: 2.7.6

What I've done:
I've updated to the latest version.

What I expected:
View the number of downloads in the downloads folder with a progress bar

What happened:
Downloads column is always empty in the show (anime) list

**Comment by fernandog** [comment]
@h3llrais3r @markheloking @xInsertx  is this still happening?

**Comment by abeloin** [comment]
@h3llrais3r @Chaotic @Arcanemagus @skmagiik @xInsertx Can you try this pull request https://github.com/SiCKRAGETV/SickRage/pull/1306 ? It should fix the issue.

**Comment by Arcanemagus** [comment]
@abeloin That did the trick, thanks!

**Comment by fernandog** [comment]
@h3llrais3r develop updated. please test and report back

**Comment by h3llrais3r** [comment]
I confirm it's working now! Thanks! :+1:
