### ISSUE TITLE
[APP SUBMITTED]: u'\u30d5'

### ISSUE THREAD

**Issue by djack42** [SiCKRAGETV/sickrage-issues#700]
### INFO
Python Version: **2.7.1 (r271:86832, Aug 23 2014, 08:54:18) 
[GCC 4.8.3 20140401 (prerelease)]**
Operating System: **Linux-3.14.14-armv7l-with-glibc2.4**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@fbcadb278054808639884dca5804d544bbc0a675
Link to Log: https://gist.github.com/250d268999f0b741b3f2
### ERROR
```
SEARCHQUEUE-MANUAL-114801 :: [Rarbg] :: Error while searching Rarbg, skipping: フ
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by djack42** [comment]
Sorry for the bad log, i just updated my config file. It will be ok now.

AA
AAKeyError: u'\u30d5'
AA  File "/usr/lib/python2.7/urllib.py", line 1238, in quote
AA    searchURL = self.urls['search'] % (urllib.quote(search_string), sc)
AA  File "/opt/sickrage/sickbeard/providers/rarbg.py", line 174, in _doSearch
AA    itemList += self._doSearch(curString, 'eponly', len(episodes))
AA  File "/opt/sickrage/sickbeard/providers/generic.py", line 290, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch)
AA  File "/opt/sickrage/sickbeard/search.py", line 476, in searchProviders
2015-02-21 10:51:38 DEBUG    SEARCHQUEUE-MANUAL-114801 :: [Rarbg] :: Traceback (most recent call last):
AAKeyError: u'\u30d5'
AA  File "/usr/lib/python2.7/urllib.py", line 1238, in quote
AA    searchURL = self.urls['search'] % (urllib.quote(search_string), sc)
AA  File "/opt/sickrage/sickbeard/providers/rarbg.py", line 174, in _doSearch
AA    itemList += self._doSearch(curString, 'eponly', len(episodes))
AA  File "/opt/sickrage/sickbeard/providers/generic.py", line 290, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch)
AA  File "/opt/sickrage/sickbeard/search.py", line 476, in searchProviders
AATraceback (most recent call last):
2015-02-21 10:51:38 ERROR    SEARCHQUEUE-MANUAL-114801 :: [Rarbg] :: Error while searching Rarbg, skipping: フ
2015-02-21 10:51:38 INFO     SEARCHQUEUE-MANUAL-114801 :: [Rarbg] :: Performing episode search for Fairy Tail

**Comment by fernandog** [comment]
@CoRpO is there a way to handle this error? Thanks

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1403

**Comment by fernandog** [comment]
@djack42 please update and test it please

**Comment by djack42** [comment]
Ok, no more error while manual searching for the same episode of fairy tail.
Thx

**Comment by Tazaz** [comment]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:33:21) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-30-generic-x86_64-with-Ubuntu-15.04-vivid**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@30435190ef8880901df555bcda0d46902ea81fb5
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-114801 :: [TorrentLeech] :: Error while searching TorrentLeech, skipping: フ
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Tazaz** [comment]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:33:21) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-30-generic-x86_64-with-Ubuntu-15.04-vivid**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@30435190ef8880901df555bcda0d46902ea81fb5
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-114801 :: [TorrentLeech] :: Error while searching TorrentLeech, skipping: フ
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@miigotu that's odd. all last issues without logs....

**Comment by duramato** [comment]
@fernandog similiar error here , 
```
AA
AAKeyError: u'\xe4'
AA    return ''.join(map(quoter, s))
AA  File "/usr/lib/python2.7/urllib.py", line 1288, in quote
AA    searchURL = self.urls['api'] + "?s=%s&out=json" % quote(search_string)
AA  File "/home/home/SickRage/sickbeard/providers/torrentproject.py", line 62, in _doSearch
AA    itemList += self._doSearch(curString, search_mode, len(episodes), epObj=epObj)
AA  File "/home/home/SickRage/sickbeard/providers/generic.py", line 357, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/home/home/SickRage/sickbeard/search.py", line 491, in searchProviders
2015-10-14 23:31:34 ERROR    SEARCHQUEUE-MANUAL-293174 :: [TorrentProject] :: Error while searching TorrentProject, skipping: ä
```

**Comment by fernandog** [comment]
return ''.join(map(quoter, s))

@miigotu should we add  return ''.join(map(quoter, s.decode(utf-8))) ?

**Comment by miigotu** [comment]
It would be `s.encode(utf-8)`

**Comment by Tazaz** [comment]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:33:21) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-30-generic-x86_64-with-Ubuntu-15.04-vivid**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@136f531f93093a5287b588ca37e19c11153f47a4
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-114801 :: [TorrentLeech] :: Error while searching TorrentLeech, skipping: フ
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
@fernandog this log line in tvcache.py is missing a traceback line after it like the others in search.py and properFinder.  Can you make the tvcache.py one the same please?

**Comment by fernandog** [comment]
Ok.
At least torrentproject got fixed with encode utf8
How to proceed with others providers?

**Comment by miigotu** [comment]
@fernandog fix torrentleech the same way, but only torrentleech.
