### ISSUE TITLE
post process file renaming

### ISSUE THREAD

**Issue by TehWardy** [SiCKRAGETV/sickrage-issues#701]
Recently I decided I wanted to change the way files were named / organised in my existing libs so i changed the naming expression in the post process options and then ticked all the rename boxes in the mass update page and kicked it off.

It doesn't appear to have done anything.
Any ideas?

**Comment by fernandog** [comment]
I think it does not rename already PP files

**Comment by TehWardy** [comment]
Odd ... sickbeard did when I did this before i'm sure of it because I had an existing lib when I started using sickbeard and it reshuffled everything for me sorting out naming and folder structure on the existing files for each show as I added them.

Would it work if I removed all the shows the re-add them to sickrage?

**Comment by fernandog** [comment]
@TagForce can you confirm please?

**Comment by TehWardy** [comment]
Wierd ... took its time but it appears to have done it over night.
It works exactly as I explained.

Assuming that makes sense ... You can close this if you want @fernandog (mark as complete or something)
