### ISSUE TITLE
Pushover Notifications not working.

### ISSUE THREAD

**Issue by Hanky2** [SiCKRAGETV/sickrage-issues#702]
Unsure if anyone else uses Pushover, but since i went from the standard SickBeard repo to SickRage I have not been able to make it work. The interface on sickrage says that it was successfully sendt but it never reaches my phone. There are two fields that require a Pushover key and User key, which is essentially the same. You only need one key.
Thank you for looking into it

**Comment by fernandog** [comment]
Follow guidelines
