### ISSUE TITLE
[APP SUBMITTED]: execv() arg 2 must contain only strings

### ISSUE THREAD

**Issue by Psychoteur** [SiCKRAGETV/sickrage-issues#704]
### INFO
Python Version: **2.7.8 (default, Dec 15 2014, 02:33:48) 
[GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Branch: **master**
Commit: SiCKRAGETV/SickRage@ac153cf2320b3b6d0a8aa9a1b1646a51347581d6
Link to Log: https://gist.github.com/7734215cf9214285bd58
### ERROR
```
POSTPROCESSER :: Failed to detect KODI version for '192.168.178.21:3005', check configuration and try again.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
check configuration and try again.

**Comment by Psychoteur** [comment]
I totally forgot about that one. I slipped on the report button, sorry.
