### ISSUE TITLE
Post Processing Folders

### ISSUE THREAD

**Issue by TehWardy** [SiCKRAGETV/sickrage-issues#709]
If I have a folder with say 10 files in it and 1 of them already exists in my library I find that that post processing sees the one that exists and then won't process the whole folder because of it.

Could this be improved so that each file is taken on it's own evalutation process and acted on accordingly so that all I end up with are files that truely can't be processed instead of some that can and others that can't.

Perhaps a post processing option to automatically delete / remove un-needed / duplicate files might be useful here to allow the processing to continue going forward?

**Comment by TagForce** [comment]
@TehWardy Yes, better way of handling failed items in PP is definitely wanted.

**Comment by fernandog** [comment]
@TagForce that PR is for this FR, isn't?

**Comment by TagForce** [comment]
Among others, yes. Should be fixed.
