### ISSUE TITLE
Does find episodes from "$#*! My Dad Says"

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#71]
<a href="https://github.com/luxmoggy"><img src="https://avatars.githubusercontent.com/u/2471320?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [luxmoggy](https://github.com/luxmoggy)**
_Wednesday Dec 10, 2014 at 19:27 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/1076 (3 comment(s))_

----

I am migrating from SickBeard to SickRage. I am reimporting some of the old series. So that I can use the set file time.
When doing a manual post process of the TV series. It returns that the TV show is one of the listed shows. But I have added it just before.

**Comment by luxmoggy** [comment]
Hello I found another show with the issue. 
Hawaii.Five-0.2010

**Comment by markheloking** [comment]
There's no $ in there though, is there? What character does it fail to get correctly?

**Comment by luxmoggy** [comment]
On this one it is the '-'

**Comment by fernandog** [comment]
@luxmoggy still an issue?
