### ISSUE TITLE
[APP SUBMITTED]: HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out.

### ISSUE THREAD

**Issue by ThePieMan** [SiCKRAGETV/sickrage-issues#710]
### INFO
Python Version: **2.7.3 (default, Apr 10 2012, 23:24:47) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@ac153cf2320b3b6d0a8aa9a1b1646a51347581d6
Link to Log: https://gist.github.com/9aca10697a01e9f9dc21
### ERROR
```
TORNADO :: API :: error HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Increase trakt timeout

**Comment by ThePieMan** [comment]
Ah ha - I was wondering why / how Trakt was breaking and interrupting my
post-processing, but it's because the notification process is tied to the
post-processing, isn't it?

i.e. The post-processor just goes one by one, and triggers the notification
process along the way, and if the notification process fails, it just
interrupts/ends the whole post-processing string, even if there are
episodes left to be post-processed (ex. Season pack)

Am I correct?

Thanks for the quick reply fernandog!

**Comment by fernandog** [comment]
Develop branch suppress the error and show a log instead. its working
