### ISSUE TITLE
Remove Country code from srt subtitle file name

### ISSUE THREAD

**Issue by felipesalomao** [SiCKRAGETV/sickrage-issues#712]
Hi, it download subtitles perfectly, but aways add country code in srt file name, example, if i download arrow S02E05, it will download 2 files: Arrow S02E05.MKV (Video) and Arrow S02E05.pb.mkv (Subtitle), problem is that all my players (TV, iPad) only recoginize subtitle if it have exactly name (both subtitle and video file), so i have aways to edit name by hand, removing .pb from subtitle file..

How solve it ? I could edit code if need to make it work.. Thanks

**Comment by fernandog** [comment]
disable it in subtitle settings

**Comment by felipesalomao** [comment]
Thank you, i not see that option before, now looking better, i found..
