### ISSUE TITLE
Add most used portuguese brazil subtitle provider (Legendas . tv )

### ISSUE THREAD

**Issue by felipesalomao** [SiCKRAGETV/sickrage-issues#713]
Hi there, most used subtitle provider in brazil is legendas . tv , it has only perfect subtitles and fast. 98% of brazilians use it.. Also make too many portuguese (portugal) subtitles, all with awesome quality and fast. Would be awesome support it on sickrage.

Already exist API wich make development more easy, if need i can ask git hub url owner to support you if have some kind of doubt

https://github.com/gustavosf/api. legendas . tv

Here is script to download subtitles for this website (not know if its working because last updated 3 months ago):
https://github.com/fjcaetano/legendas . tv-downloader

it would be awesome to have legendas . tv as a subtitle provider... it always has the right subtitle, unlike opensubtitles that is always a struggle to get the right one, generally out of sync or its a english subtitle translated with google tranlator (or both) :s

Really thanks for your awesome work !

**Comment by fernandog** [comment]
Owner of subtitles module (diaoul) wont add it because need user/pass

**Comment by felipesalomao** [comment]
That so sad :(
I dont understand why not simple hard encode user/pass.. Or we could enter our own user / pass like we already do with private torrent providers.. Fernando, you also is from brazil, right ?! If yes, you know how legendas.tv is important for brazillians.. All another sites like opensubtitle, addict7d, download subtitles without quality, out of sync, translated by google translator or even both.. hehehe

Periscope (similar to subliminal) have legendas.tv plugin too.. Why not use it instead subliminal or port their plugin to subliminal (i think that should be 95% same code).. 
See here: https://github.com/fernandog/periscope/tree/master/periscope/plugins

Thank you a lot for your awesome work making sickrage better..

**Comment by fernandog** [comment]
Use o meu fork do periscope no crontab de hora em hora no seu diretorio de download. Quando o SR fizer o PP ele leva a legenda junto. Faco assim

**Comment by felipesalomao** [comment]
Acabei de perceber só agora que o fork é seu.. rsrs
Tenho NAS da qnap, ele baixa para pasta /download, dai um script simples meu transfere tudo que é série ou filme para a pasta /multimedia/organizar e chama o post process do sickrage (apontado para essa pasta), dai processa e por sua vez joga para /multimedia/serie/nome da serie/Temporada X/Epsodio S0XE0X.mkv..
Ou seja,ele renomea o arquivo, como o script saberia qual é o tipo do arquivo (sempre baixo 720p dimension ou killers e web-dl 1080p).. quais dos diretorios deveria colocar no contab ? Poderia me ajudar ? Entendo bem pouco de código, só o suficiente para fazer um pequeno script bash que utilizo para notiicar por push downloads concluidos o transmission, transferir conteudos, etc.. 
Sempre instalei tudo no NAS via QPKG (executável que faz tudo).. Meu usuário no skype é felipesalomao2.. Abs

**Comment by fernandog** [comment]
Tem que baixar a legenda ANTES de processar

Baixe e Instale o periscope (python setup install.py)
coloque usuario e senha no arquivo de config do periscope
rode o seguinte comando 
/usr/local/bin/periscope -l pt-br "/downlod"'
Legenda baixa
mova para organizar.

**Comment by fernandog** [comment]
http://www.vivaolinux.com.br/artigo/Usando-cron-e-crontab-para-agendar-tarefas?pagina=2

**Comment by fernandog** [comment]
@felipesalomao conseguiu?

**Comment by fernandog** [comment]
@felipesalomao

**Comment by acdesouza** [comment]
Would like to know more? Diaoul/subliminal#432

**Comment by abeloin** [comment]
@felipesalomao Please use English only.
