### ISSUE TITLE
[APP SUBMITTED]: Connection error HTTPConnectionPool(host='services.tvrage.com', port=80): Max retries exceeded with url: /myfeeds/episode_list.php?key=Uhewg1Rr0o62fvZvUIZt&sid=41032 (Caused by <class 'socket.error'>: [Errno 10054] An existing connection was forcibly closed by the remote host) while loading URL http://services.tvrage.com/myfeeds/episode_list.php

### ISSUE THREAD

**Issue by stervis** [SiCKRAGETV/sickrage-issues#714]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@ac153cf2320b3b6d0a8aa9a1b1646a51347581d6
### ERROR
```
SHOWQUEUE-REFRESH :: Unable to look up show on TVRage, not downloading images: error Connection error HTTPConnectionPool(host='services.tvrage.com', port=80): Max retries exceeded with url: /myfeeds/episode_list.php?key=Uhewg1Rr0o62fvZvUIZt&sid=41032 (Caused by <class 'socket.error'>: [Errno 10054] An existing connection was forcibly closed by the remote host) while loading URL http://services.tvrage.com/myfeeds/episode_list.php
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Banned?

**Comment by abeloin** [comment]
[Errno 10054] An existing connection was forcibly closed by the remote host. = The remote host is dropping the connection. = Overload?

**Comment by stervis** [comment]
I wouldn't know. Don't think I am banned... maybe I have the 'refresh' time
too low? But i am quite sure I didnt change it.

On 22 February 2015 at 02:37, Alexandre Beloin <notifications@github.com>
wrote:

> [Errno 10054] An existing connection was forcibly closed by the remote
> host. = The remote host is dropping the connection. = Overload?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/714#issuecomment-75413688>
> .
>



-- 
Met vriendelijke groeten,

Stephan Vorstenberg

**Comment by fernandog** [comment]
What is your refresh value?

**Comment by fernandog** [comment]
https://github.com/ckreutzer/python-tvrage/issues/9

**Comment by stervis** [comment]
Check the screenshot


On 22 February 2015 at 12:37, Fernando <notifications@github.com> wrote:

> ckreutzer/python-tvrage#9
> <https://github.com/ckreutzer/python-tvrage/issues/9>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/714#issuecomment-75431470>
> .
>



-- 
Met vriendelijke groeten,

Stephan Vorstenberg

**Comment by fernandog** [comment]
Server(services.tvrage.com) is overloaded
