### ISSUE TITLE
[APP SUBMITTED]: HTTPSConnectionPool(host='sceneaccess.eu', port=443): Max retries exceeded with url: /login (Caused by <class 'socket.gaierror'>: [Errno 11004] getaddrinfo failed)

### ISSUE THREAD

**Issue by ThePieMan** [SiCKRAGETV/sickrage-issues#715]
### INFO
Python Version: **2.7.3 (default, Apr 10 2012, 23:24:47) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@ac153cf2320b3b6d0a8aa9a1b1646a51347581d6
Link to Log: https://gist.github.com/f3f50c71de127b0d93e0
### ERROR
```
SEARCHQUEUE-MANUAL-273761 :: [SceneAccess] :: Unable to connect to SceneAccess provider: error HTTPSConnectionPool(host='sceneaccess.eu', port=443): Max retries exceeded with url: /login (Caused by <class 'socket.gaierror'>: [Errno 11004] getaddrinfo failed)
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Too many wrong user/pass attempts isnt?

**Comment by ThePieMan** [comment]
I don't think so - user/pass info is correct because I get hits from SCC
frequently. However, I get frequent SR errors related to this tracker alone
fairly often too.

**Comment by fernandog** [comment]
maybe too many access in a short period of time.
What's your search frequency?

**Comment by abeloin** [comment]
[Errno 11004] getaddrinfo failed = DNS error = Unable to translate to IP

**Comment by fernandog** [comment]
Can we handle this traceback > log.logger debug message? It not the first one I see

**Comment by abeloin** [comment]
@fernandog Yes see https://github.com/SiCKRAGETV/SickRage/pull/1389

**Comment by fernandog** [comment]
thanks!

**Comment by fernandog** [comment]
@ThePieMan please update and report back

**Comment by ThePieMan** [comment]
Trying to checkout the Dev branch (I run Master pretty much
exclusively) and running into issues. I'll work at it and get back to you.

**Comment by fernandog** [comment]
@ThePieMan any lucky?

**Comment by ThePieMan** [comment]
Yes, looks like I'm limited to timeout errors for SCC now, and I haven't
seen any more of the other errors that particular provider was throwing.
Thanks!

**Comment by fernandog** [comment]
Stop SR, Edit config.ini and edit socket timeout. Something like that. See if helps.
