### ISSUE TITLE
.nfo file not cleaned up for Archive releases

### ISSUE THREAD

**Issue by SunMar** [SiCKRAGETV/sickrage-issues#716]
I've got HDTV set for Initial and 720p WEB-DL for Archive on my of my shows, and I noticed that after it downloads the WEB-DL version, the video file for the Initial HDTV is cleaned up, but an .nfo is not. I haven't checked if subtitle files are not cleaned up either.

Running on develop branch (fbcadb278054808639884dca5804d544bbc0a675) on Windows 7.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues

follow guidelines

**Comment by SunMar** [comment]
Oops, missed the Python version which is 2.7.9, sorry. There is no error to include a log of, what are you missing?

**Comment by fernandog** [comment]
SUBMITTING A BUG/ISSUE TICKET

(DO NOT POST ANYTHING THAT CONTAINS YOUR LOGIN INFORMATION OR API KEY)
Please include the following when opening a new ticket:

Branch
Commit hash
Your operating system and python version
What you did
What happened
What you expected
Link to a copy/paste of your logfile with clear debug info of the error on PASTEBIN

**Comment by SunMar** [comment]
All that information is included my post, please tell me what I'm doing wrong. Do you want it specifically in that format? Or do you want a log regardless of whether there is an error? If so please note that in the guidelines as such, because I'm lost ... :(. I'll try to reproduce the issue to see If I can get something from the log file. If you can give a pointer where in the code this is handled I also don't mind diving into it myself.

Branch: develop
Commit hash: fbcadb278054808639884dca5804d544bbc0a675
Your operation system and python version: Windows 7 / Python 2.7.9
What you did: I've got HDTV set for Initial and 720p WEB-DL for Archive on my of my shows.
What happened: I noticed that after it downloads the WEB-DL version, the video file for the Initial HDTV is cleaned up, but an .nfo is not.
What you expected: The .nfo is removed as well.

**Comment by fernandog** [comment]
Without full logs we cant debug.

**Comment by fernandog** [comment]
Are you there there isnt an option to remove .nfo and other files

**Comment by SunMar** [comment]
Hmm, when an Initial download is replaced with an Archive download I would expect any associated files to be removed as well. Lingering .nfo/.srt and such aren't really useful.

**Comment by SunMar** [comment]
In the Post-Processing section I don't see an option for it. There only option I see is "Move Associated Files" which moves nfo/srt/etc to the TV Show directory. To be honest I don't really care for the nfo, but I do want to keep subtitle files if they're included.

There is a "Rename .nfo file" option, but from the description that doesn't really have anything to do with removed files when they're replaced.

In General and Search Settings I can't really find anything other than "replace original download with Proper or Repack if nuked" concerning replacing different qualities.

**Comment by fernandog** [comment]
You have to disable "Move Associated Files" in order to delete .nfo and .srt

**Comment by SunMar** [comment]
Huh? If Move Associated Files is disabled it doesn't copy nfo/srt at all from the Download directory, then there's not an nfo to delete in the TV Shows directory. That's something different and not what's wrong here.

I'm talking about when an Archive quality is downloaded to replace the Initial quality. The mkv/nfo/srt are all properly moved from the Downloads directory to the TV Shows directory when the Initial is downloaded. When the Archive quality is downloaded it does the same for that quality, but it also removes the mkv of the Initial download, only not the nfo. When it cleans up the Initial quality because it found a better quality, it should also clean up associated files and not just the mkv. Note that I have episode renaming enabled, so all files have the same base name, based on that it should be able to detect associated files.

I was unable to reproduce the issue because of some other SR issues that got in the way concerning re-downloading episodes, will have to wait for it to happen again I'm afraid before I can post a log.

**Comment by fernandog** [comment]
I see. PP should remove old .mkv AND associated files
@Tagforce agree?
