### ISSUE TITLE
Manual Postprocessing deletes file before move

### ISSUE THREAD

**Issue by stevehaley** [SiCKRAGETV/sickrage-issues#717]
File gets deleted before move 
Processing folder I:\_New_TV
TV_DOWNLOAD_DIR: I:\_New_TV
PostProcessing Path: I:\_New_TV
PostProcessing Dirs: []
PostProcessing Files: [u'Sleepy.Hollow.S02E05.The.Weeping.Lady.mkv']
PostProcessing VideoFiles: [u'Sleepy.Hollow.S02E05.The.Weeping.Lady.mkv']
PostProcessing RarContent: []
PostProcessing VideoInRar: []
Processing I:\_New_TV\Sleepy.Hollow.S02E05.The.Weeping.Lady.mkv (None)
Retrieving episode object for 2x5
Snatch history had a quality in it, using that: Unknown
Is ep a priority download: False
File I:\_TV Series\Sleepy Hollow\Season 02\Sleepy.Hollow.S02E05.The.Weeping.Lady.mkv doesn't exist so there's no worries about replacing it
Deleting file I:\_New_TV\Sleepy.Hollow.S02E05.The.Weeping.Lady.mkv
Destination folder for this episode: I:\_TV Series\Sleepy Hollow\Season 02
Moving file from I:\_New_TV\Sleepy.Hollow.S02E05.The.Weeping.Lady.mkv to I:\_TV Series\Sleepy Hollow\Season 02\Sleepy.Hollow.S02E05.The.Weeping.Lady.mkv
Unable to move file I:\_New_TV\Sleepy.Hollow.S02E05.The.Weeping.Lady.mkv to I:\_TV Series\Sleepy Hollow\Season 02\Sleepy.Hollow.S02E05.The.Weeping.Lady.mkv: [Errno 2] No such file or directory: u'I:\\_New_TV\\Sleepy.Hollow.S02E05.The.Weeping.Lady.mkv'
Processing failed for I:\_New_TV\Sleepy.Hollow.S02E05.The.Weeping.Lady.mkv: Unable to move the files to their new home
Problem(s) during processing

**Comment by fernandog** [comment]
follow guidelines
https://github.com/SiCKRAGETV/sickrage-issues/
