### ISSUE TITLE
Issue with RSS

### ISSUE THREAD

**Issue by Hit-Bug** [SiCKRAGETV/sickrage-issues#719]
Sickrage for about a week refused to read the rss feeds, I checked the feeds myself and the said episodes are there but it would not see it, it just comes back with "Couldn't find a download for ". I did a fresh reinstall and still nothing, I'm on BRANCH: (master) / COMMIT: (ac153cf2320b3b6d0a8aa9a1b1646a51347581d6) , python 2.7.8, using FreeNAS-9.3-STABLE-201412091831. Sickrage install by pbi 9.3.1 then updated inside jail with commits.

Log Here: http://pastebin.com/78pwe8r9

**Comment by abeloin** [comment]
Please provide log with debug not just info. Thank You

**Comment by Hit-Bug** [comment]
http://pastebin.com/6W0YqRtN

**Comment by abeloin** [comment]
What what is selected quality for that show?

By the way, why not using the nyaa provider with horriblesubs in the whitelist?

**Comment by abeloin** [comment]
Can you try adding this regex it will solve the issue? https://github.com/SiCKRAGETV/SickRage/pull/1386

Ref: The show is detected as "Aldnoah Zero - " and not "Aldnoah Zero"
```
Converted parsed result [HorribleSubs].Aldnoah.Zero.-.19.[1080p] into Aldnoah Zero -  [ABS: [19]] [ANIME VER: 1] [GROUP: HorribleSubs] [ABD: False] [ANIME: True] [whichReg: ['anime_ultimate']]
```

**Comment by Hit-Bug** [comment]
I'll will try this, one minute

**Comment by Hit-Bug** [comment]
It already had Aldnoah Zero in the exceptions so that's not it, I cannot find the white list option when adding Nyaa from sickrage. Trying the regex now, one minute

**Comment by abeloin** [comment]
The whitelist is per show, edit the show and scroll to the bottom.

**Comment by Hit-Bug** [comment]
Ok, how to do I do this regex?

**Comment by Hit-Bug** [comment]
And the whilte list doesn't show, I know I saw it before but I think it's not loading

**Comment by abeloin** [comment]
2 choices:
* Replace the whole file by this one: https://raw.githubusercontent.com/abeloin/SickRage/patch-anime_regex/sickbeard/name_parser/regexes.py

* Download the patch: https://github.com/SiCKRAGETV/SickRage/pull/1386.patch and apply it with ```patch -p1 < 1386.patch```

**Comment by Hit-Bug** [comment]
Ok, which file is it? Can you give me the directory?

**Comment by abeloin** [comment]
For that you need to enter your anime account in config->anime.

To add one manually, look under the whitelist there's a text line(fill it with the group name) and on the right a button named 'Add to whitelist' which you click.

**Comment by abeloin** [comment]
sickbeard/name_parser/regexes.py

**Comment by Hit-Bug** [comment]
Sickrage is in a jail, I'm running freenas

**Comment by abeloin** [comment]
For that I can't help you as I have never worked with free nas. Have you searched on the internet?

**Comment by abeloin** [comment]
If you don't find, you can add "Aldnoah Zero - " to the scene exception in the show until the regex is merged into master.

**Comment by Hit-Bug** [comment]
There's not much information for a freenas build, when using sickrage. I've told you that it already has that exception

**Comment by abeloin** [comment]
Just to confirm, with the dash?

**Comment by Hit-Bug** [comment]
It's "Aldnoah Zero" NOT "Aldnoah.Zero"

**Comment by abeloin** [comment]
!?! I'm talking about the dash sign -

**Comment by Hit-Bug** [comment]
Ok, what did you want to confirm with the dash?

**Comment by Hit-Bug** [comment]
My bad, didn't read "If you don't find, you can add "Aldnoah Zero - ""

**Comment by Hit-Bug** [comment]
Ok, I've tried that and still no download

**Comment by abeloin** [comment]
Sometime the scene exception aren't refreshed at the same time as the show update, can you restart sickrage?

**Comment by Hit-Bug** [comment]
Ok, one sec

**Comment by Hit-Bug** [comment]
It didn't want to shutdown so I restarted it from freenas control panel, still no download

**Comment by Hit-Bug** [comment]
Funny enough, everything worked on the sickrage pbi 9.3.0

**Comment by abeloin** [comment]
Is the show set to anime?

**Comment by Hit-Bug** [comment]
No, doesn't that option allow the absolute number only?

**Comment by abeloin** [comment]
Yes, which you want in anime

**Comment by abeloin** [comment]
Your config for that should be like this:
![Imgur](http://i.imgur.com/AqYWsAR.jpg)

**Comment by Hit-Bug** [comment]
Changed the option, now it's stuck at queued.

**Comment by abeloin** [comment]
It's ok. let it process the queue.

**Comment by Hit-Bug** [comment]
It doesn't take this long though, it's still stuck at queued

**Comment by Hit-Bug** [comment]
It usually takes not longer than 10 seconds to pull the link.

**Comment by abeloin** [comment]
Have a look at your log it must be doing some search.

**Comment by Hit-Bug** [comment]
Ok, it works now, thanks for the help, still has trouble shutting down/restarting though

**Comment by fernandog** [comment]
@Hit-Bug please update and report back

**Comment by Hit-Bug** [comment]
On the shutdown/restart problem?

**Comment by fernandog** [comment]
No. To test the merged solution. You tested manually changing files. Shutdown restart already has an open issue

**Comment by Hit-Bug** [comment]
I didn't use that method, all it was is the the anime option that needed to be ticked since it used the absolute number as the marker not the usual seasonXepisode.
