### ISSUE TITLE
episode detection fails for shows that are stored by airdate

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#72]
<a href="https://github.com/majello"><img src="https://avatars.githubusercontent.com/u/555196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [majello](https://github.com/majello)**
_Thursday Dec 11, 2014 at 00:28 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/1078 (1 comment(s))_

----

when importing a show from the filesystem, if the show is using airdates in the naming pattern instead of season/episode, and there is a special on the same date, episodes from the main season are identified as specials. 

this even happens if the path includes season information (naming pattern: Season %0S/%SN - %A-D - %EN)

possible fixes: pick up the season from the path, or exclude season 0 for shows that are by airdate. 

thanks for picking up the good work, btw.

**Comment by fernandog** [comment]
@TagForce feature request or issue?

**Comment by TagForce** [comment]
@fernandog Sorry, I missed this one earlier... Definitely an issue. Removing the fix pending label as nobody is working on this at the moment.

**Comment by fernandog** [comment]
fix pending means that there's no PR or code change in progress. It's correct to keep the "fix pending"

**Comment by abeloin** [comment]
@majello Can you provide show example were this happen?

**Comment by fernandog** [comment]
@majello fix will be in master next sunday
