### ISSUE TITLE
[APP SUBMITTED]: HTTPSConnectionPool(host='sceneaccess.eu', port=443): Read timed out.

### ISSUE THREAD

**Issue by ThePieMan** [SiCKRAGETV/sickrage-issues#720]
### INFO
Python Version: **2.7.3 (default, Apr 10 2012, 23:24:47) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@ac153cf2320b3b6d0a8aa9a1b1646a51347581d6
### ERROR
```
FINDPROPERS :: [SceneAccess] :: Error while searching SceneAccess, skipping: error HTTPSConnectionPool(host='sceneaccess.eu', port=443): Read timed out.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/715
