### ISSUE TITLE
[APP SUBMITTED]: [Error 145] The directory is not empty: u'C:\\Users\\chris\\Sick-Beard-ThePirateBay\\sr-update\\SiCKRAGETV-SickRage-652c9f3\\lib\\feedparser\\tests\\wellformed\\atom10'

### ISSUE THREAD

**Issue by Cmtahm** [SiCKRAGETV/sickrage-issues#726]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@652c9f33f92b3c74c0256bb3aafae5e8dc014c89
Link to Log: https://gist.github.com/fc7c6e19d58632b62a7b
### ERROR
```
Thread-68 :: Error while trying to update: error 145 : The directory is not empty
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
what's the meaning of thie folder ?C:\Users\chris\Sick-Beard-ThePirateBay\sr-update ?

please clone sickrage and don't re-use "Sick-Beard-ThePirateBay" folder
