### ISSUE TITLE
[APP SUBMITTED]: cannot find 'SHOWUPDATE_HOUR'

### ISSUE THREAD

**Issue by ThePieMan** [SiCKRAGETV/sickrage-issues#727]
### INFO
Python Version: **2.7.3 (default, Apr 10 2012, 23:24:47) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@b2790f920e879714836f05053eff9f815d0867c7
### ERROR
```
Thread-214 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\MyPrograms\SickRage\sickbeard\webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "C:\MyPrograms\SickRage\sickbeard\webserve.py", line 3446, in index
    def index(self):
  File "C:\MyPrograms\SickRage\cache\cheetah\cheetah__MyPrograms_SickRage_gui_slick_interfaces_default_config_general_tmpl_1424626780_78_58630.py", line 185, in respond
    _v = VFSL([locals()]+SL+[globals(), builtin],"sickbeard.SHOWUPDATE_HOUR",True) # u'$sickbeard.SHOWUPDATE_HOUR' on line 70, col 80
  File "C:\Python27\lib\site-packages\Cheetah\NameMapper.py", line 245, in valueFromSearchList
    executeCallables=executeCallables)
  File "C:\Python27\lib\site-packages\Cheetah\NameMapper.py", line 226, in _valueForName
    _raiseNotFoundException(key, obj)
  File "C:\Python27\lib\site-packages\Cheetah\NameMapper.py", line 167, in _raiseNotFoundException
    raise NotFound(excString)
NotFound: cannot find 'SHOWUPDATE_HOUR'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@TagForce is that your new commit about changing SR update time?

**Comment by abeloin** [comment]
Usually happen when updating Sickrage and not restarting it.

**Comment by ThePieMan** [comment]
Correct - I checked out the Dev branch and was just expecting it'd throw SR
through a restart automatically. It did not, and this was the result.

Unless there are plans for a checkout to restart SR automatically, I'd
consider this a known issue / non-issue and close

TPM

**Comment by abeloin** [comment]
How did you do your checkout? Via command line or the sickrage interface?

**Comment by ThePieMan** [comment]
Interface. Selected Dev and hit checkout. It must have worked, but it
didn't restart itself so it was throwing errors all over the place. Once I
restarted it manually SR showed Dev branch in the info page and the errors
stopped

**Comment by abeloin** [comment]
Which is normal, if you read underneath the button "Checkout branch" you will see the following text:

select branch to use (restart required)

;)
