### ISSUE TITLE
Wrong or Unsync'ed Subtitles downloaded

### ISSUE THREAD

**Issue by bthusby** [SiCKRAGETV/sickrage-issues#732]
Quite often SickRage downloads unusable subtitles. I just want sync'ed subtitles to be downloaded automatically. I have no idea why wrong subtitles are downloaded, but e.g. Kodi shows some of the available subtitles as Sync'ed in their internal subtitle add-on. Any way to just download Sync'ed subtitles in SickRage?

**Comment by TagForce** [comment]
@bthusby I have no idea why it downloads unsynced subs... Subliminal tries to get the correct subs by using the filehash. It could be that it doesn't work properly. Subliminal should probably be updated to a newer version, but that requires a lot of changes. Subliminal was rewritten completely and most of the function calls would need to be changed.

Will probably happen in the future.

**Comment by bthusby** [comment]
Thanks! Fingers crossed for newest version of Subliminal :)

**Comment by BoGu5** [comment]
I don't think subliminal is the problem. I ran into this bug when selecting all scrapers. When I only select opensubtitles I don't get false positives. I think the problem lies in the webscraper subtitle plugins.

**Comment by bthusby** [comment]
Ok, I will try using only opensubtitle for a while and see if it improves.. :) So only sync'ed subtitles will be downloaded then?

**Comment by TagForce** [comment]
@BoGu5 It depends on which scrapers are used. If the scraper doesn't support filehashes, then the chances of it giving you wrong subs is greater. Still Subliminal has improved over time, and updating it to the new version is something we should do sometime in the future. It does require a lot of code-rewriting, though.

**Comment by neoatomic** [comment]
Try to use opensubtitels and addic7ed. Tvsubtitels also gives problems for me with out off sync subs.
Also we have on the to do list to update Subliminal , so that should also improve the results.
