### ISSUE TITLE
[Feature Request] Per Show setting for Notifications

### ISSUE THREAD

**Issue by Freakadude** [SiCKRAGETV/sickrage-issues#734]
It would be cool to have a simple switch/box per show profile where you can set if you wish to receive notifications (snatched, downloaded, etc) or not e.g. via Pushbullet. 
If i remember correctly this individual setup was already included in Sickbeard so i am wondering why this is actually absent here but would love to also see it here.

Thanks

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
