### ISSUE TITLE
[APP SUBMITTED]: coercing to Unicode: need string or buffer, instance found

### ISSUE THREAD

**Issue by rickytin** [SiCKRAGETV/sickrage-issues#738]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@2d8aad80cdfb8983832206af445039de0decded9
### ERROR
```
CHECKVERSION :: Exception generated in thread CHECKVERSION: coercing to Unicode: need string or buffer, instance found
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
Can you provide more info from the log(e.g.: traceback)?

**Comment by rickytin** [comment]
For the past 4 update to SickRage Master I haven't bean able to do and install and restart successfully, it always say that the installation fail. I have auto update so I shutdown SickRage and when it start it dose the update.
Because today I try to update to the latest version and it fail I submit my error, here is my log 
https://gist.github.com/rickytin/f3fb967f33955105d0f2

**Comment by fernandog** [comment]
@rickytin
did you read this?
https://github.com/SiCKRAGETV/sickrage-issues/
