### ISSUE TITLE
[APP SUBMITTED]: Unable to parse doctor.who.4x11.ws.pdtv.xvid-angelic

### ISSUE THREAD

**Issue by dkimbell13** [SiCKRAGETV/sickrage-issues#741]
### INFO
Python Version: **2.7.8 (default, Jul  3 2014, 23:17:54) 
[GCC 4.8.2 20131219 (prerelease)]**
Operating System: **Linux-3.10.30-30-ARCH-armv7l-with-glibc2.4**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@b2790f920e879714836f05053eff9f815d0867c7
### ERROR
```
SHOWQUEUE-REFRESH :: No episode number found in /home/nzbget/media/TV Shows/Doctor Who[2005]/Season 0/Doctor.Who.2005.2013.Christmas.Special.The.Time.of.The.Doctor.1080p.HDTV.DD5.1.H.264-NB.mkv, ignoring it
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
Not an error
