### ISSUE TITLE
[APP SUBMITTED]: Connection error ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host')) while loading URL http://services.tvrage.com/myfeeds/showinfo.php

### ISSUE THREAD

**Issue by SpecialKeezie** [SiCKRAGETV/sickrage-issues#742]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@3e288f3bb51f634df2000673d64e4f2c7d8fd4ac
Link to Log: https://gist.github.com/0cd83108b9b7932e4668
### ERROR
```
SHOWQUEUE-REFRESH :: Unable to look up show on TVRage, not downloading images: error Connection error ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host')) while loading URL http://services.tvrage.com/myfeeds/showinfo.php
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
Server(services.tvrage.com) is overloaded

**Comment by fernandog** [comment]
@abeloin 
what is the ex(e)?

```
        except (sickbeard.indexer_error, IOError), e:
            logger.log(u"Unable to look up show on " + sickbeard.indexerApi(
                show_obj.indexer).name + ", not downloading images: " + ex(e), logger.ERROR)
            return None
```

can't we catch this error(10054) and show "Service is overloaded" ?
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/metadata/generic.py#L770

**Comment by abeloin** [comment]
Have a look in sickbeard/exceptions.py#L21 is a function that return a unicode string from the error.
What we could do is log the message as warning and put the ex(e) as a debug message
