### ISSUE TITLE
Sickrage sometimes gets stuck in a loop when updating, or processing files from Sabnzbd

### ISSUE THREAD

**Issue by kestnuts** [SiCKRAGETV/sickrage-issues#743]
Branch : Master 
Commit hash : 2d8aad80cdfb8983832206af445039de0decded9
OS and Python Version : Win7 Pro, python 2.7.8
This happens when Sickrage is trying to update to a new version, and when trying to process an episode downloaded with Sabnzbd. It appears to be intermmitent. This doesn't appear in the error log, it only appears in the command window for sickbeard.py. It flashes by too fast to read, but I took a screenshot :

![image](https://cloud.githubusercontent.com/assets/11171753/6344348/41ccba0c-bbc5-11e4-8e49-5762499af479.png)

**Comment by icebal** [comment]
this is also happening to me, copied/pasted below:
Traceback (most recent call last):
  File "C:\Python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "C:\Python27\lib\logging\handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being
used by another process
Logged from file logger.py, line 136

**Comment by fernandog** [comment]
@kestnuts @icebal in the next PP run, does it PP ok?

**Comment by kestnuts** [comment]
@fernandog I checked, and while sabnzbd still shows that post processing failed with the following error message : 
 ("Opening URL: http://localhost:8081/home/postprocess/processEpisode
Unable to open URL: HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /home/postprocess/processEpisode?nzbName=Doctor.Who.2005.S08E07.BDRip.x264-TASTETV.nzb&failed=0&quiet=1&dir=E%3A%5CDownloads%5Ccomplete (Caused by <class 'httplib.BadStatusLine'>: '')
The episode appears as downloaded in sick beard and is in the correct folder on my hard drive. So...yes?

**Comment by fernandog** [comment]
@kestnuts SR changed the way you login to the page. Are you using the latest version sabnzbd postprocess (nzbtomedia)?

**Comment by fernandog** [comment]
@abeloin do you know why there's no SR exception but only python exception?

**Comment by kestnuts** [comment]
I've been using the sabtosickbeard script.Where can I find the nzbtomedia script?

**Comment by fernandog** [comment]
https://github.com/clinton-hall/nzbToMedia

**Comment by icebal** [comment]
i was able to successfully PP with both old and new ToSickbeard scripts, but the loop is still going. SR and ToMedia scripts are updated to newest versions

**Comment by icebal** [comment]
upon further testing, i am unable to add any new shows while the loop is going, the show gets stuck at Loading..."SHOW NAME"

**Comment by abeloin** [comment]
@fernandog This is the result of the log file being lock some other process and sickrage wanting to write to the log. That write operation fail so it generate an exception which in turn wants to be written in the log. Creating a endless loop until the file is release.

To further debug the issue I would need the log just before the loop started

**Comment by icebal** [comment]
whats your file hosting site of choice? ill throw the log up there.

**Comment by icebal** [comment]
uploaded to dev-host:
http://d-h.st/mbb

**Comment by abeloin** [comment]
Thanks for the Logs. The next it happen can you look at the process list in the task manager if there's 2 instance of python.

**Comment by icebal** [comment]
i have many instances of python running, but only one pointing to sickrage. the others are PlexScriptHost and the instances used by Sabnzbd++ and CouchPotato. i still  have not restarted SickRage since i tested  the PP process.

**Comment by abeloin** [comment]
Ok then the next time you restart sickrage watch if there's another sickrage process running. As there's a process locking one of the sickrage.log files when it try to rotate the log

**Comment by pct00** [comment]
also have this problem
it only happens sometimes, i guess when the log file is in use but SR tries to rotate it

i only use python for sickrage and only torrents

**Comment by abeloin** [comment]
@pct00 When it will happen check if there 2 sickrages process

**Comment by pct00** [comment]
@abeloin was able to force this behaviour with a mass update.
only 1 process running

![image](https://cloud.githubusercontent.com/assets/10249098/6419076/2df330ca-beb2-11e4-92ef-cdf3db7887b4.png)

**Comment by pct00** [comment]
additional info
only 2 log files on SR logs dir when it happens, and the sickrage.log stops growing

![image](https://cloud.githubusercontent.com/assets/10249098/6419115/8279e4ea-beb2-11e4-8ee5-e27f8722937c.png)

**Comment by fernandog** [comment]
@abeloin maybe it's the log rotation as you said. could be it. can you check the creation timestamp of the log and compare with te error in CMD?

**Comment by fernandog** [comment]
@pct00 ?

**Comment by abeloin** [comment]
@pct00 Can you check the open handle on sickrage.log

Use one of the tools used in the q/a here http://serverfault.com/questions/1966/how-do-you-find-what-process-is-holding-a-file-open-in-windows

* Process explorer
* handle
* openfiles
* unlocker

**Comment by fernandog** [comment]
@pct00 please reply, we are doing our best here and we need the feedback to make sure it's fixed.

@kestnuts can you check your Log folder and tell use the all files inside it?

**Comment by icebal** [comment]
my log file shows sickrage.log and sickrage.log.1-5 and i only have one open handle on the log file, and that is one process of python for sickrage

**Comment by icebal** [comment]
preforming a mass update  doesnt force the issue. have not seen the issue since i last posted actually

**Comment by pct00** [comment]
@fernandog i didn't reply earlier because it didn't happen again over the weekend. i was not able to force it again even with mass updates.

however today i just updated SR. logged in remotelly just now to my home computer and it seems to be happening again. later when i get home i will use process explorer to see if any other process is locking the log files. can't do it now cause the access is desperatly slow...

can confirm once again only 1 python.exe process is running and on the SR logs folder i have "sickrage.log" and "sickrage.log.5" files and the .5 file is and old one with date of yesterday, so before the update.
the .log file has the timestamp of today a bit after i made the update so it seems to be stuck on this file and not rotating to the new file

**Comment by icebal** [comment]
@pct00 were you downloading a large amount at the time of it? i was going on 1.7TB with Sab, sickRage wasnt able to keep up and was getting backlogged.

**Comment by pct00** [comment]
@icebal i only use torrents so i dont think that's the issue, i think when sr restarts for the update it keeps a open handle on the main log file and when it gets full and tries to rename it it fails

**Comment by fernandog** [comment]
@pct00 stop SR, delete all logs files and start. that should fix

**Comment by pct00** [comment]
@fernandog hi, yes. that solves the problem but i wanted to confirm the source of the error for you guys :)

**Comment by fernandog** [comment]
@pct00 SR loses itself with non-sequential logs

**Comment by kestnuts** [comment]
@fernandog sorry for the late reply, this week has been very busy for me. My log folder also only had sickrage.log and sickrage.log.1-5. I'm going to try deleting them and restarting sickrage and see if that solves the problem.

**Comment by fernandog** [comment]
@kestnuts is error persists will re-open. waiting your feedback

**Comment by icebal** [comment]
found a cause for this, changing the number of log files automatically makes SR name the first archived log the highest number. so starting out fresh with a log number of 10, it will only have sickrage.log and sickrage.log.10

**Comment by fernandog** [comment]
@TagForce bug?

**Comment by icebal** [comment]
yeah, at least one of the root issues of above.

**Comment by TagForce** [comment]
@fernandog If it is, it's a bug in Python logging, because all I did was pass the number of logfiles to the python logging system, instead of a hardcoded '5'.

**Comment by fernandog** [comment]
@TagForce maybe when changing log number, we should delete previous log files.

**Comment by icebal** [comment]
it does delete previous logs, just starts out at the biggest one

**Comment by fernandog** [comment]
@TagForce can we do this in SR or it's a python change ?
http://bugs.python.org/issue4749#msg89212

**Comment by TagForce** [comment]
@fernandog Depends... I think SR spawns new threads, not new processes. If so, then it won't help.

@icebal It creates both the .log and the .log.<LOG_NR> files?
That has to be a bug in the logging system, or something on your system. It shouldn't do that, and I really never told it to create anything. Instead of passing a 5 to the logging system, it now passes a integer variable.

**Comment by icebal** [comment]
it creates the .log, then when it gets full the first .log.* it creates is .log.10, instead of .log.1

**Comment by fernandog** [comment]
try set your number of logs to 9. see what happens

**Comment by icebal** [comment]
ok, changing it to 9 does the same thing, it skips to .log.9. i can stop it by unlocking the .log file, Sickrage then creates the correct .log.1 file and is fine from there on.

**Comment by icebal** [comment]
this is now happening anytime i restart Sickrage. all log files get cleared, Sickrage starts Sickrage.log, then archives it as Sickrage.log.9, then the error loops

**Comment by fernandog** [comment]
change number of logs to 1, change size to 52428800 (50mb),  stop SR, delete all logs from /Logs, start again

**Comment by icebal** [comment]
not getting any errors so far, but it is doubling up newly added shows.example below:
![image](https://cloud.githubusercontent.com/assets/946581/6468927/457ddea4-c19e-11e4-9e37-f238380739d6.png)

**Comment by icebal** [comment]
i doubt this has anything to do with the logs, but it only happened when i changed it to 50mb and only 1 log

**Comment by icebal** [comment]
loop happened again, log is in http://pastebin.com/LTjPeWDz
to be clear this is the iteration of 1 log file sized at 50mb

**Comment by TagForce** [comment]
@icebal ßet your number of logs to 0 and size to 10mb. Test it and let us know

**Comment by freddyfinn** [comment]
@TagForce that worked .  I left the file size at default and changed logs to 0.  I was able to update without error. As soon as I changed the logs to 0 log.5 was generated.

**Comment by fernandog** [comment]
@TagForce can we force number of log to 0 in WIN platform ?

**Comment by TagForce** [comment]
i think i may have an idea what causes this...  viewlogs never closes the logs after reading.

**Comment by fernandog** [comment]
and windows exclusively lock the file

**Comment by TagForce** [comment]
@fernandog precisely. And that may just cause all these log rotation issues we're seeing lately.

**Comment by fernandog** [comment]
@TagForce 

https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/webserve.py#L4990

```
        for i in range (1 , int(sickbeard.LOG_NR)):
            if os.path.isfile(logger.logFile + "." + str(i)) and (len(data) <= maxLines):
                with ek.ek(codecs.open, *[logger.logFile + "." + str(i), 'r', 'utf-8']) as f:
                        data += Get_Data(minLevel, f.readlines(), len(data), regex, logFilter, logSearch, maxLines)
                        f.close
```

**Comment by TagForce** [comment]
It should close the file after the with clause. on windows it doesn't, I think.
Probably change it all from codec.open to using io.open... But need to make sure that's the issue first.

**Comment by fernandog** [comment]
@TagForce should I make a PR like I said above?

**Comment by kestnuts** [comment]
Hey all, updated to the new version of Sickrage tonight, and this pesky loop is back again. This time it happened while doing an episode search. See below : 
![image](https://cloud.githubusercontent.com/assets/11171753/6549747/d4f95208-c5ee-11e4-8d7e-149b36b11f5b.png)

**Comment by fernandog** [comment]
@kestnuts please set number of log to 0 (zero). Restart

**Comment by TagForce** [comment]
@fernandog @abeloin I think I may have found the issue...
This problem only occurs on multi-processed python applications, which SR is not...
However... When updating or hitting the 'restart' option, SR will indeed spawn a new process of itself.
When hitting shutdown, SR stops, but it will keep a copy of sickrage.log open. It only shows on Windows because it will have an exclusive file lock on the file for writing. Linux behaves slightly different (no exclusive locks). This means that the file can still be opened for writing, but will not have an exclusive lock on it, but deleting or renaming the file will not work due to the old exclusive lock still being in place.

If that is indeed the case (and it looks like it is), then a simple solution would be to shutdown the logger before exiting SR, which releases the logfile. I've added this to the logger class and halt() function. That 'should' fix the problems with logs not rotating.

https://github.com/SiCKRAGETV/SickRage/pull/1506

If you receive this message after restarting SR on windows and the above PR was implemented in it, then you may need to reboot the entire system for the filelock to be released (or use a file unlocker tool on it).

**Comment by fernandog** [comment]
@TagForce thanks!

**Comment by fernandog** [comment]
merged

**Comment by abeloin** [comment]
Ok

**Comment by pct00** [comment]
thanks all !

**Comment by fernandog** [comment]
@pct00 did you test the develop branch? is it working?

**Comment by Greg0rz** [comment]
Having the same issues (logs stop updating due to something holding up the log) in master branch. 

Is this fix only included in Develop branch?

**Comment by fernandog** [comment]
@kestnuts please update and report back (develop)

@Greg0rz only develop. Sunday on master if develop users confirm its working

**Comment by Greg0rz** [comment]
@fernandog Cool.  Will take a look at this tomorrow and report back if nobody else has.  Thanks.

**Comment by fernandog** [comment]
@Greg0rz any news on this?

**Comment by Greg0rz** [comment]
Have not had any lock issues yet. I will try to add some more content today
and see if I run into any problems.

**Comment by fernandog** [comment]
@Greg0rz  please confirm its fixed so we can merge into master!

**Comment by Greg0rz** [comment]
So I haven't had the issue yet.  Obviously can only confirm I have the problem if I have the problem, but it has not happened yet...
