### ISSUE TITLE
[Feature Request] Add justseed.it client

### ISSUE THREAD

**Issue by jack-o-lantern** [SiCKRAGETV/sickrage-issues#745]
Site is www.justseed.it i use it for all my stuff i currently tried to develop an interface but failed miserably.

wish i had more time to learn all this but gotta work =( so.....

25$ donation to the developer that commits the change! if other are interested or know a way to setup a pool for features i am in!

Here is a bloke that is having good success on git hub with python based
 tool
https://github.com/TouchTone/pyjsit

There are a set of tools they provide in JAR files

http://justseed.it/utilities/index.csp

and they have an exstensive API

http://justseed.it/api/index.csp

**Comment by neoatomic** [comment]
The developers are currently doing mainly bug and stability fixes.To get max stability out of SickRage.
Larger feature requests are mostly on hold because of that. Also i see that currently justseed.it is in beta/testing phase.?

**Comment by jack-o-lantern** [comment]
no worries no rush just to see if the community wants in! i was actually
just gonna have one of my in house developers do it but i don't like to
"cross streams"

On Tue, Feb 24, 2015 at 5:21 AM, neoatomic <notifications@github.com> wrote:

> The developers are currently doing mainly bug and stability fixes.To get
> max stability out of SickRage.
> Larger feature requests are mostly on hold because of that. Also i see
> that currently justseed.it is in beta/testing phase.?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/745#issuecomment-75731702>
> .
>



-- 
Regards,

Joe Villar
SAP Basis Administrator

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
