### ISSUE TITLE
https warning

### ISSUE THREAD

**Issue by ripper1967** [SiCKRAGETV/sickrage-issues#748]
Hi I was still getting the insecure error
C:\Users\ripper1967\SickRage\lib\requests\packages \urllib3\connectionpool.py:747: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html

So I downloaded master branch, the error was gone,so I then moved connectionpool.py from the master branch: SickRage\lib\requests\packages\urllib3 \connectionpool.py to the develop branch SickRage\lib\requests\packages\urllib3\connectionpool.py and error all fixed I don't know how to do a PR ,just thought you might like to look into what the difference is, between the master connectionpool.py and dev one..

**Comment by fernandog** [comment]
@abeloin it was merged to develop. Wanst it?

**Comment by ripper1967** [comment]
how to shut this error off #639  that pr didn't fix it,Like I said I just copied the master branch,connectionpool.py into my dev branch and the error quit along with a couple others,,i  have had zero warnings or errors since,

**Comment by ripper1967** [comment]
I wonder if it has something to do with my version of python? I am at 2.7.9 most are at 2.7.8

**Comment by fernandog** [comment]
@ripper1967 did you restarted with switched branch?

**Comment by ripper1967** [comment]
yes I am fine as long as I run the master as soon as I update to dev branch I get that warning, then I just copy the master branch connectionpool.py to dev and I am  fine after that

**Comment by abeloin** [comment]
@fernandog Let me check but I think what is happening here is when a thread new thread is started the disable warning is not transferered

**Comment by abeloin** [comment]
@ripper1967 Can you try this pull request? It should resolve the issue.
https://github.com/SiCKRAGETV/SickRage/pull/1409

**Comment by ripper1967** [comment]
yes that pull request did fix it,confirmed fixed after I get the pull lol

**Comment by abeloin** [comment]
@ripper1967 Thanks for the testing
