### ISSUE TITLE
[Feature Request] Ability to edit posters and banners.

### ISSUE THREAD

**Issue by maronsen** [SiCKRAGETV/sickrage-issues#749]
hi, Add the ability to edit the images for shows, both posters and banners in the edit page for each show, where you edit the quality and everything else about a show. :+1: 

What I was thinking was having a button you would click and an overlay opens like the jQuery overlay and then it shows all poster images available for that show from Thetvdb or Tvrage. The images are rendered/loaded on page, displayed and you can select one and save and that image is then the new poster image, same for banners, and an option underneeth to enter a web url to an image if you want a custom one. check out plex media servers implementation of this 
![screen shot 2015-02-24 at 19 32 48](https://cloud.githubusercontent.com/assets/7189809/6356205/118ade2c-bc5c-11e4-993d-e418aa6e4873.png)
![screen shot 2015-02-24 at 19 33 13](https://cloud.githubusercontent.com/assets/7189809/6356206/118b6dba-bc5c-11e4-847b-034791868f3e.png)
![screen shot 2015-02-24 at 19 33 25](https://cloud.githubusercontent.com/assets/7189809/6356207/118eb02e-bc5c-11e4-8c0a-03612fa8ec74.png)

**Comment by neoatomic** [comment]
I suggested this a time ago. Its related to : https://github.com/SiCKRAGETV/sickrage-issues/issues/33

https://sickrage.tv/forums/forum/main-category/feature-requests/9273-tv-rage-index-banners?p=9338#post9338

@fernandog Do you want this FR to remain open.?

**Comment by fernandog** [comment]
IMO as I said in a PR, when TVRAGE is selected, SR should get ONLY banner froms thetvdb and other infos from tvrage. Better solution, isn't?

**Comment by maronsen** [comment]
What i was thinking was having a button you would click and a overlay opens like the jquery overlay and then it shows all posters available for that show from thetvdb and you can select one and save and that image is then the new poster image, same for banners, and an option underneeth to enter a web url to a image if you want a custom one.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
