### ISSUE TITLE
[Feature Request] Adding support for TVRage posters/banners and choosing them.

### ISSUE THREAD

**Issue by neoatomic** [SiCKRAGETV/sickrage-issues#750]
As TVRage doesn't support banners/posters for shows, it would be nice to grab them from TVDB instead.
But to do this the ID from TVRage needs to be converted to the TVDB ID. As the API will need it.?
Would this be possible to do with XEM.? As both id's are present there.?

Also TVDB has in most cases more than one banner/poster on there website. 
Many users would like the ability to select between those posters/banners.
If the TVDB API has the ability to download more then one banner/poster it could be done like this.
Let SR download and rename the banners like 24670-1.banner.png, 24670-2.banner.png, 24670-3.banner.png etc.
Add a drop-box to the edit page where the user can select the banner. 
So linking like :  banner-1 = id-1.banner.png, banner-2 = id-2.banner.png, banner-3 = id-3.banner.png etc.

Old issue : https://github.com/SiCKRAGETV/sickrage-issues/issues/33

**Comment by fernandog** [comment]
@neoatomic do you think this can work for specials too and not just banners?

**Comment by neoatomic** [comment]
@fernandog Cant say....
If it is possible with XEM to convert the id from TVRage to TVDB you might be able to use that id to call the TVDB api for the specials. But need to add that i'm not a coder/programmer so cant tell if that is technically possible....
http://thexem.de/doc

**Comment by fernandog** [comment]
@neoatomic Im asking because I don't use tvrage. don't know if they have specials data

**Comment by neoatomic** [comment]
@fernandog Yes tvrage has specials.
http://www.tvrage.com/Storage_Wars/episode_list/all  (bottom of page)

**Comment by neoatomic** [comment]
@fernandog I did some thinking on how to fix this banner problem. And it also might be a solution for your specials problem.?

Lets say :

A users adds a TVRage show but after the quality question he gets an additional settings screen. (lets call it banner and specials support for TVRage)
This screens tells the user that TVRage doenst support Banners/posters and specials. 
And if he wishes those he needs to select the SAME show from a list that is shown. (This list is generated from the search results on TVDB.)
The user selects the correct show and finishes adding it.
At this point you have the TVRage id and theTVDB id. Let SR write both ID's to the DB and call the TVDB API for the banners/posters and specials.

**Comment by fernandog** [comment]
@neoatomic did you read this discussion here? https://github.com/SiCKRAGETV/SickRage/issues/1252

**Comment by neoatomic** [comment]
@fernandog Did a quick read, but i dont understand how they get the data from both TVRage and TVDB without having both ID's. But if that solutions works for the banners it would be great.

**Comment by fernandog** [comment]
there's no solution yet. that user is still thinking how to do that.

**Comment by flightlevel** [comment]
Closing issue as TVRage closed down
