### ISSUE TITLE
[APP SUBMITTED]: database disk image is malformed

### ISSUE THREAD

**Issue by Alexwijn** [SiCKRAGETV/sickrage-issues#751]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) 
[GCC 4.6.3]**
Operating System: **Linux-3.18.7+-armv6l-with-debian-7.8**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@3e288f3bb51f634df2000673d64e4f2c7d8fd4ac
Link to Log: https://gist.github.com/e9604bac297003391d3f
### ERROR
```
POSTPROCESSER :: Fatal error executing query: database disk image is malformed
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/549#issuecomment-72844385
