### ISSUE TITLE
Feature request: episode size limits

### ISSUE THREAD

**Issue by tjw1184** [SiCKRAGETV/sickrage-issues#756]
Allow size limits to be specified for episodes (ignored for season searches) per quality type.  Occasionally some nzbs are corrupt and too small (<100MB) or an entire season gets marked as a specific episode.  Allows throwing out the files before they get downloaded and marked failed.  could roll out with very large defaults (100mb-10000mb for all) or make it optional to turn on.

i.e.

720p web-dl -- sizes 200MB-2000MB
1080p bluray - sizes 500MB-8000MB
....

**Comment by fernandog** [comment]
@tjw1184 you could use a good provider to avoid this

**Comment by neoatomic** [comment]
Already requested.https://github.com/SiCKRAGETV/sickrage-issues/issues/95
