### ISSUE TITLE
Changing Show Quality (in Show>Edit) Has No Effect

### ISSUE THREAD

**Issue by cdunford** [SiCKRAGETV/sickrage-issues#758]
Branch: master
Commit: 2d8aad80cdfb8983832206af445039de0decded9
OS: Ubuntu 14.10 (Linux dunford-nas 3.16.0-29-generic #39-Ubuntu SMP Mon Dec 15 22:27:29 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux)
Python: Python 2.7.8

Description:

After I added several shows to a new database (I am migrating from sickbeard), the quality was not set how I wanted for several shows (it was set to HD for some shows which are older and would only be available in SD). I proceeded to do the following:

1. Select the show on the main show list page
2. Click the "edit" button on the top right of the show page
3. Change the Quality (Preferred quality of episodes to be download) to be "Any" instead of "HD"
4. Press the submit button at the bottom of the page

The quality for the show does not change on the show page or on the main show listing page.

http://pastebin.com/UgwkmtKh

**Comment by abeloin** [comment]
Just tried it on master it does work as intended.
Looking at your log, it show the show being saved successfully.
Can you provide screenshot of the editShow and of the show?
