### ISSUE TITLE
wrong search name string

### ISSUE THREAD

**Issue by tommehh** [SiCKRAGETV/sickrage-issues#761]
I am opening an issue based on a previous one: #361 

Name being used for search:
2015-01-09 02:39:28 INFO     SEARCHQUEUE-MANUAL-274431 :: Unable to find a download for: [Gotham - 1x11 - Rogues' Gallery]

Name available at all trackers:
 Gotham - S01E11

I tried the following but that did not work for me!

-------------------------------------------------------------------------
Jagomeister  commented on Jan 9: Easy fix go to 
 /sickbeard/sickbeard/providers/{provider.py}
 eg. /sickbeard/sickbeard/providers/scc.py for SceneAccess
 in the method _get_episode_search_strings(self, ep_obj, add_string='')

you will see sickbeard.config.naming_ep_type[2]
 change that to sickbeard.config.naming_ep_type[1]
----------------------------------------------------------------------------

Any other suggestions?

**Comment by abeloin** [comment]
Logs please

**Comment by tommehh** [comment]
http://pastebin.com/AKy7AW2d

**Comment by abeloin** [comment]
Can you provide branch and commit?

**Comment by abeloin** [comment]
If you try this url do you see results?
https://kickass.to/usearch/Gotham+S01E11%7C1x11+category%3Atv/?field=seeders&sorder=desc&rss=1

**Comment by fernandog** [comment]
@abeloin isn't the apostrophe (Rogues' Gallery) that is making SR not matching the result?

**Comment by abeloin** [comment]
I don't think so as not getting any results at all.

**Comment by tommehh** [comment]
im on master branch (but also tried dev, same results), fully updated.

the webpage gives no results, "webpage not available" , dont i need to setup a different proxy?

**Comment by abeloin** [comment]
Activate a proxy in the search provider options as KAT is blocked where you live.

**Comment by tommehh** [comment]
Thank you guys, setting 'http://katproxy.com' in KAT.py did the trick!
weird that i wasnt able to fix this earlier with a different proxy...
