### ISSUE TITLE
"Change File Date" don't use the local timezone.

### ISSUE THREAD

**Issue by Noktam** [SiCKRAGETV/sickrage-issues#762]
When i use the "Change file date" checkbox to change the date of the show according to airdate, it don't seems to use the local timezone.

**Comment by fernandog** [comment]
@abeloini issue or feature request?

**Comment by Noktam** [comment]
Or maybe it's the other way arround, it use the local timezone to store the timestamp of the file, when timestamp should be UTC time.
Anyway, a ls -l on system with GTM+1 for a video aired at 24/02 22h at New York should be listed as 25/02 07h.

**Comment by abeloin** [comment]
It depend on the Time Zone setting in the User Interface section in the config. If it is set to local then it will be converted.
![Imgur](http://i.imgur.com/ExGxPRG.png)

**Comment by Noktam** [comment]
The date of a file should not be converted, a timestamp is always UTC time.
So it's usefull on the calendar to see the date of the next episode in your local time, but if you change the date of the file using local timezone, for me on GTM+1, it will set a file date that's few hours before the show actually aired.

**Comment by abeloin** [comment]
Timestamp maybe saved in UTC but they are displayed in your timezone GMT+1. When Python change the ctime and mtime it save them as GMT+1 which your OS then convert to UTC(NTFS and Linux but not FAT). This way applications don't need to be time zone aware.

In this case, when you set the timezone to local Sickrage take the station time zone and your time zone, add or subtract the difference and update the time as GMT+1 on the file. Which afterward the OS converted to UTC.

So for example, let says there's a show playing on 2015-02-26 at 20:30 GMT-5 , the file will be timestamp 2015-02-27 at 02:30 GMT+1. Both of which give you 2015-02-27 at 01:30 GMT.

**Comment by Noktam** [comment]
Ok. I'm a little confuse, so i admit i could be wrong but i find awkward than on my system, an ls on a file where the date was modified by sickrage show me the date in the station time zone not mine, even if my timezone is set to local on sickrage.

To give a practical exemple :
My system is on Central European time.
( date +%Z give me CET )

Sickrage timezone is set to local.
On my sickrage calendar, for my next episode (so E05) of Better call saul, i have :
Next Episode: S01E05 - Alpine Shepherd Boy
Airs: Tuesday, 03. Mar 2015, 04:00 on AMC
 
Better Call saul S01E04 was aired on 2015-02-23 22h00 on AMC, station time (so GMT-8 i suppose).
That's 2015-02-24 04:00 on my local time (at least, that's what sickrage says on the next episode date)

stat Better.Call.Saul.S01E04.720p.HDTV.x264-DIMENSION.mkv :
  File: `Better.Call.Saul.S01E04.720p.HDTV.x264-DIMENSION.mkv'
  Size: 832364930       Blocks: 1625728    IO Block: 4096   regular file
Device: 802h/2050d      Inode: 12451860    Links: 3
Access: (0777/-rwxrwxrwx)  Uid: ( 1001/    plex)   Gid: ( 1001/    plex)
Access: 2015-02-27 03:34:16.091400291 +0100
Modify: 2015-02-23 22:00:00.000000000 +0100
Change: 2015-02-27 04:30:03.213111931 +0100

On my system, a ls show me : Feb 23 22:00  Better.Call.Saul.S01E04.720p.HDTV.x264-DIMENSION.mkv
Yep,on my country, at 22h on GTM+1, the show was not even aired.

It would be more logical if a ls tell me that the file was created on 2015-02-24 04:00, no ?
For exemple, i have a crontab who delete subtitles and download proper subs 24h after the show was aired. (The first subs -specially in a foreign language- who are availiable are not always the best, so you could add that to the feature list btw :p )
So yep, i could (and i do) add few more hours, but i can't think otherwise that's kinda ugly and akward.

**Comment by abeloin** [comment]
Mmm, better call saul is not a good example since I'm on the same time zone.

Dia no Ace works for me 2015-02-15 8:30 GMT-9
```
stat Ace\ of\ Diamond\ -\ S01E69\ -\ Can\'t\ Lose.mkv 
  Fichier : « Ace of Diamond - S01E69 - Can't Lose.mkv »
   Taille : 100 	Blocs : 522800     Blocs d'E/S : 4096   fichier
Périphérique : fd02h/64770d	Inœud : 9047028     Liens : 1
Accès : (0644/-rw-r--r--)  UID : ( 1000/ abeloin)   GID : ( 1000/ abeloin)
 Accès : 2015-02-26 03:29:41.629203108 -0500
Modif. : 2015-02-14 18:30:00.000000000 -0500
Changt : 2015-02-26 03:29:31.558373560 -0500
  Créé : -
```

Let me recheck the code

**Comment by Noktam** [comment]
Thanks for looking at it, i have the same problem with ace of Diamond.
Ace of diamond is 8h30 on tokyo time (so GTM+9) right ?
http://www.tv-tokyo.co.jp.e.ck.hp.transer.com/program/detail/22856_201503010830.html

 ls -l
 Feb 15 08:30 [HorribleSubs].Ace.of.Diamond.-.69.[480p].mkv

stat "[HorribleSubs].Ace.of.Diamond.-.69.[480p].mkv"
  File: `[HorribleSubs].Ace.of.Diamond.-.69.[480p].mkv'
  Size: 156072787       Blocks: 304832     IO Block: 4096   regular file
Device: 802h/2050d      Inode: 12451927    Links: 2
Access: (0666/-rw-rw-rw-)  Uid: ( 1001/    plex)   Gid: ( 1001/    plex)
Access: 2015-02-27 06:09:57.536472560 +0100
Modify: 2015-02-15 08:30:00.000000000 +0100
Change: 2015-02-27 06:09:55.816500502 +0100

**Comment by abeloin** [comment]
Can you try this PR https://github.com/SiCKRAGETV/SickRage/pull/1428 ?

I found out why it was working on my test setup, it wasn't it in reality as I forced the date from network time to local system wide to debug a bug in another issue and I forgot to remove it and this is why I was under the impression it was working.

**Comment by abeloin** [comment]
@Noktam Have you tried the PR?
