### ISSUE TITLE
[Feature Request] Get the anidb_id on the show api call

### ISSUE THREAD

**Issue by Noktam** [SiCKRAGETV/sickrage-issues#763]
Hi, can we get anidb_id returned on the show api call, like /api/1234/?cmd=show&tvdbid=79349 ?

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
