### ISSUE TITLE
[Errno 2] No such file or directory: u'D:\\Torrents\\Completed\\

### ISSUE THREAD

**Issue by suprdave23** [SiCKRAGETV/sickrage-issues#765]
* Branch
BRANCH: (master)

* Commit hash
COMMIT: (2d8aad80cdfb8983832206af445039de0decded9)

* Your operating system and python version
Windows 7 x64, Python 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]

* What you did
Ran manual post processing with "Force already Post Processed Dir/Files" and "Mark Dir/Files as priority download" checked. The video file that was in the "Completed" directory was the same as the file that was in the "TV Shows" directory (where post processing is configured to move the file). 

* What happened
The video file was deleted out of the "Completed" directory before being moved. As a result, an error occurs when SR tries to move the file as it has already deleted it. The video file was also deleted out of my "TV Shows" directory.

* What you expected
The video file to be moved from the "Completed" directory to the "TV Shows" directory, not be deleted before being moved, nor the file it was replacing to be deleted before knowing that the move is going to be successful. As a result I ended up with no video files at all!

* Link to a copy/paste of your logfile with clear debug info of the error on PASTEBIN
http://pastebin.com/KNJUweTB

```
09:58:48 DEBUG::Thread-59 :: Moving file from D:\Torrents\Completed\The.American
s.2013.S03E03.720p.HDTV.x264-KILLERS.mkv to D:\TV Shows\The Americans\The.Americ
ans.2013.S03E03.720p.HDTV.x264-KILLERS.mkv
09:58:48 ERROR::Thread-59 :: Unable to move file D:\Torrents\Completed\The.Ameri
cans.2013.S03E03.720p.HDTV.x264-KILLERS.mkv to D:\TV Shows\The Americans\The.Ame
ricans.2013.S03E03.720p.HDTV.x264-KILLERS.mkv: [Errno 2] No such file or directo
ry: u'D:\\Torrents\\Completed\\The.Americans.2013.S03E03.720p.HDTV.x264-KILLERS.
mkv'
Traceback (most recent call last):
  File "c:\sickrage\sickbeard\postProcessor.py", line 319, in _int_move
    helpers.moveFile(cur_file_path, new_file_path)
  File "c:\sickrage\sickbeard\helpers.py", line 361, in moveFile
    ek.ek(shutil.move, srcFile, destFile)
  File "c:\sickrage\sickbeard\encodingKludge.py", line 56, in ek
    result = func(*args, **kwargs)
  File "C:\Python27\lib\shutil.py", line 302, in move
    copy2(src, real_dst)
  File "C:\Python27\lib\shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "C:\Python27\lib\shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
```

**Comment by fernandog** [comment]
@TagForce @abeloin will shutil copy fail if it has to move directory+file? shoudl'nt we use copytree?

**Comment by fernandog** [comment]
@suprdave23 sickrage has enough permissions to write to that folder?

**Comment by suprdave23** [comment]
Hi fernandog,

It does, the user the process is running as has full control over the D:\Torrents folder and all subfolders / files as well as the directory it is moving the files into (D:\TV Shows)

**Comment by fernandog** [comment]
@suprdave23 this mkv is in which folder now?
D:\Torrents\Completed\ or D:\TV Shows\The Americans\ ?

can you send the print of the folders permissions/users?

**Comment by TagForce** [comment]
@fernandog @abeloin I think I may have found the issue...
To fix the renamer, it also looks for associated files in the subfolders of whatever folder it is trying to rename files from. However, the same function is used for post processing...
This means that if it looks for associated files for any videofile in the root of the TV Download folder, it will also list files in its subfolders, which are then prone to be deleted when the associated files are deleted.

Working on fixing that as we speak (by changing the function calls to include subfolders = true when running from rename).

**Comment by suprdave23** [comment]
TV Download Dir is "D:\Torrents\Completed". Utorrent is configured to place finished downloads in that directory. 

The configured location for "The Americans", and where post-processing is trying to move the file to is "D:\TV Shows\The Americans".

The video file existed in both areas, I chose the appropriate options (I thought) for overwriting the file via manual post processing.

Here's a permissions print for both paths:

![capture](https://cloud.githubusercontent.com/assets/11187813/6374979/d919ef50-bcd9-11e4-9e3f-54653871a8da.PNG)
![capture2](https://cloud.githubusercontent.com/assets/11187813/6374984/dd0e5d08-bcd9-11e4-8439-9ce27a9513f4.PNG)

**Comment by fernandog** [comment]
how are you running SR? as "media" user?
this D:/ is a HDD or ftp or what?

**Comment by TagForce** [comment]
https://github.com/TagForce/SickRage/commit/b0133e5eb83ddbc95f8619feb24e72b0c1a4918d
Should fix it... If you're on the latest develop, just update those 3 files with the ones in the commit.

**Comment by suprdave23** [comment]
@fernandog
Yes, SR is running as the "media" user. D: is a hard drive.

@TagForce
Thanks! I'm on whatever came out of the master branch, I'll see if I can figure out how to update to the develop branch and test post processing again.

**Comment by suprdave23** [comment]
@TagForce Looks like it is working well now, the file is getting moved correctly, thank you for that!

I did notice though that at the end of the post processing run it says "Problems during processing", but the log is not showing any warnings or errors. Here's the pastebin link for the latest log: http://pastebin.com/aaJuRaRR

**Comment by TagForce** [comment]
@suprdave23 Yes, that is something I'm still looking at. It also caused RAR contents not to be deleted.
Apparently some variable doesn't get set properly.

**Comment by suprdave23** [comment]
Okay no problem. Let me know once you believe you're fixed it and I'll be happy to test it again.
