### ISSUE TITLE
Email notification does not include "Date" header - Some email clients get confused and make the received date "12/31/1969"

### ISSUE THREAD

**Issue by suprdave23** [SiCKRAGETV/sickrage-issues#766]
Branch
BRANCH: (master)

Commit hash
COMMIT: (2d8aad80cdfb8983832206af445039de0decded9)

Your operating system and python version
Windows 7 x64, Python 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]

What you did
Generated a test email message

What happened
Test email message was sent, however "Date" is not one of the headers SR sends the email with. As a result, some email clients that rely on this header default to a wrong date/time for when the email was sent.

What you expected
"Date" header to be included so that all email clients can parse the message properly and put it in the right order in the user's inbox.

Link to a copy/paste of your logfile with clear debug info of the error on PASTEBIN
http://pastebin.com/8TcKTpVw

**Comment by abeloin** [comment]
PR pushed

**Comment by suprdave23** [comment]
Thanks, works well!  I really appreciate the fast turn around times!
