### ISSUE TITLE
Prefer season packs but download individual episodes of current season (BTN)

### ISSUE THREAD

**Issue by mtosic** [SiCKRAGETV/sickrage-issues#767]
BRANCH: (master)
COMMIT: (2d8aad80cdfb8983832206af445039de0decded9) 
Python Version: 2.7.8
OS: Windows 8.1

What I expected:
I've added BTN as search provider and I want following behavior when I add a show (to minimize number of torrents snatched):
1. Download season packs of previous seasons
2. Download individual episodes (up-to-date) of current season (if it's currently airing / not completed yet)

What I did:
Provider setting for BTN are:
1. Season search mode: Season pack only
2. Season search fallback: Checked

What happened:
1. It sets all episodes for all seasons to "Wanted"
2. It downloads season packs for previous seasons
3. If current season is airing, status of individual episodes remain in "Wanted" and don't get downloaded
4.  If press manual search on specific wanted episode, it gets snatched, but that defeats the purpose of automation

![sickrage-helix](https://cloud.githubusercontent.com/assets/953687/6376962/73ab365e-bd21-11e4-917d-5e2caefe85d2.PNG)

Log (with debug=0):
2015-02-25 18:51:59 INFO     SEARCHQUEUE-BACKLOG-265912 :: FALLBACK EPISODE SEARCH INITIATED ...
2015-02-25 18:51:59 INFO     SEARCHQUEUE-BACKLOG-265912 :: Performing episode search for Helix
2015-02-25 18:51:59 INFO     SEARCHQUEUE-BACKLOG-265912 :: No needed episodes found during backlog search for: [Helix]

**Comment by abeloin** [comment]
Please provide the debug log from sickrage.log.
In sickrage.log find this line `2015-02-25 18:51:59 INFO SEARCHQUEUE-BACKLOG-265912 :: FALLBACK EPISODE SEARCH INITIATED ...` and copy all the SEARCHQUEUE-BACKLOG-265912 into pastebin.

**Comment by mtosic** [comment]
Here is the pastebin:
http://pastebin.com/raw.php?i=mayBv0Zt

**Comment by abeloin** [comment]
There's no more line then that? You should have 'Search string' at least
```
2015-02-25 12:26:55 INFO     SEARCHQUEUE-BACKLOG-164501 :: [KickAssTorrents] :: Performing episode search for Mike & Molly
2015-02-25 12:26:55 DEBUG    SEARCHQUEUE-BACKLOG-164501 :: [KickAssTorrents] :: Search string: https://kickass.to/usearch/Mike+%26+Molly+S04+-S04E+category%3Atv/?field=seeders&sorder=desc&rss=1
2015-02-25 12:26:56 DEBUG    SEARCHQUEUE-BACKLOG-164501 :: [KickAssTorrents] :: Search string: https://kickass.to/usearch/Mike+%26+Molly+Season+4+-Ep%2A+category%3Atv/?field=seeders&sorder=desc&rss=1
2015-02-25 12:26:57 DEBUG    SEARCHQUEUE-BACKLOG-164501 :: [KickAssTorrents] :: Using ALL regexes
```

**Comment by mtosic** [comment]
No, that's all. I've set debug=1 in config.ini.
Do you want me to force backlog search?

**Comment by abeloin** [comment]
Try it and send the logs

**Comment by mtosic** [comment]
Did it, here is the log, but can't see any new info.
http://pastebin.com/raw.php?i=TtwFtUZ4

**Comment by abeloin** [comment]
Do you have on log when btn was updated: 2015-02-25 20:51:51?

**Comment by mtosic** [comment]
Here it is: http://pastebin.com/raw.php?i=fihdEnmR
It seems like it wants to add random shows to cache.

**Comment by abeloin** [comment]
Do you have backlog enable for btn?

**Comment by abeloin** [comment]
> It seems like it wants to add random shows to cache.
That's normal it's the daily search

**Comment by mtosic** [comment]
Yes. following is enabled for BTN search provider:
1. Enable daily searches
2. Enable backlog searches
3. Season search fallback
4. Season search mode: season packs only

**Comment by abeloin** [comment]
Can you add this in between line 130-131 of sickbeard/providers/btn.py and restart sickrage:
```
                    logger.log(u"Torrent found: {0}".format(str(torrent_info)), logger.DEBUG)
```
It will log every time a torrent is found.

**Comment by mtosic** [comment]
Here you go: http://pastebin.com/raw.php?i=xUNnYkb2
I cannot find any line with "torrent found" for Helix series (id: 265912).

**Comment by abeloin** [comment]
You need to force a backlog

**Comment by mtosic** [comment]
Did it: http://pastebin.com/raw.php?i=y5NUdGwd
Now I have torrents found, but seems like BTN is returning random shows.

**Comment by mtosic** [comment]
I think I've discovered what causes the problem.
I've written my first PHP program to test the provider :)

Also, I've added line to catch search params which are sent to BTN provider.
Here are the results:
http://pastebin.com/raw.php?i=WdU073fT

Problem is that sickrage is sending same parameters when it falls back on episode search.
Then nothing is found and nothing can be downloaded.

    2015-02-26 05:00:19 INFO     SEARCHQUEUE-BACKLOG-265912 :: [BTN] :: Performing season pack search for Helix
    2015-02-26 05:00:19 DEBUG    SEARCHQUEUE-BACKLOG-265912 :: [BTN] :: Params sent: {'category': 'Season', 'tvdb': 265912, 'name': 'Season 2'}
    2015-02-26 05:00:19 INFO     SEARCHQUEUE-BACKLOG-265912 :: FALLBACK EPISODE SEARCH INITIATED ...
    2015-02-26 05:00:19 INFO     SEARCHQUEUE-BACKLOG-265912 :: Performing episode search for Helix
    2015-02-26 05:00:19 DEBUG    SEARCHQUEUE-BACKLOG-265912 :: Params sent: {'category': 'Season', 'tvdb': 265912, 'name': 'Season 2'}
    2015-02-26 05:00:20 INFO     SEARCHQUEUE-BACKLOG-265912 :: No needed episodes found during backlog search for: [Helix]

**Comment by abeloin** [comment]
Nice catch :smiley: 
The issue is with the code in generic.py:
```
            if len(episodes) > 1:
                # get season search results
                for curString in self._get_season_search_strings(epObj):
                    itemList += self._doSearch(curString, search_mode, len(episodes))
            else:
                # get single episode search results
                for curString in self._get_episode_search_strings(epObj):
                    itemList += self._doSearch(curString, 'eponly', len(episodes))
```
A custom findSearchResults() will need to be included in btn.

**Comment by abeloin** [comment]
@mtosic Can you try applying this pull request https://github.com/SiCKRAGETV/SickRage/pull/1420 and try again?

**Comment by mtosic** [comment]
I'm not so experienced with Git.
Can you tell me what do I need to type in command line to apply that pull request?

**Comment by fernandog** [comment]
@mtosic linux?
stop SR,
SSH
enter SickRage folder
wget --no-check-certificate https://github.com/SiCKRAGETV/SickRage/pull/1420.patch
patch -p1 <1420.patch
start SR
try to reproduce

**Comment by mtosic** [comment]
its windows :)

**Comment by fernandog** [comment]
@mtosic 
stop SR
edit your /SickRage/sickbeard/providers/btn.py file, erase it contents and past this one:
https://raw.githubusercontent.com/abeloin/SickRage/patch-btn/sickbeard/providers/btn.py
save,
start SR

**Comment by mtosic** [comment]
Yes, I know I can do it this way...I have git shell installed, that's how i pulled SickRage in first place.
Thought there is some git command to do it easily.

Will try this way and report results.

**Comment by fernandog** [comment]
for windows I don't know. I tried once the patch command and it didn't worked

**Comment by mtosic** [comment]
We have some progress, but it still doesn't work correcty.
I needed episodes 1-6 from season 2, but it only snatched the first one.

On force backlog it again searches only for first episode in season.
I've added params which are sent to torrent provider:
http://pastebin.com/raw.php?i=55KbbpjE

When it fallbacks on episode search, it always sends S02E01 param.

It seems like it doesn't search for other 'Wanted' episodes in backlog.

**Comment by fernandog** [comment]
check you search settings and report the backlog search days value

**Comment by mtosic** [comment]
Baclog search day is: 7.

**Comment by fernandog** [comment]
change it to 30 and try again

**Comment by mtosic** [comment]
Can I ask what does that value mean? Does it look for the airdate in backlog and snatches all with
"Wanted" and Airdate>=Today()-BacklogSearchDaySettings.

Cause it snatched episode from 16.1.2015, but it didn't snatch newer ones (last is on 20.2.2015).

**Comment by fernandog** [comment]
can you check if BTN already have the 20.2.2015 ep available?

**Comment by mtosic** [comment]
Picture says more then 1000 words:
![sr_helix](https://cloud.githubusercontent.com/assets/953687/6392547/0468899e-bdc2-11e4-9b1b-9a9f8eee4403.JPG)

It always searches for the first episode in season. I would say that backlog search setting does nothing here, because it snatched first and oldest episode from season, but it can't snatch 5 newer ones.

All are available on BTN.

**Comment by fernandog** [comment]
send full logs after changing to 60 and the new code please

**Comment by mtosic** [comment]
Changed it to 60, did a forced backlog search, behaviour is still the same.
Here is the log: http://pastebin.com/raw.php?i=NQpTp43X

**Comment by abeloin** [comment]
@mtosic Can you put this into a file named `datadump.py` in Sickrage root, open a command line and run it via python `python.exe datadump.py` and give me the results.
```
from lib import jsonrpclib

apikey = ''
results_per_page=1000
offset=0
params = {'category': 'Season', 'tvdb': 265912, 'name': 'Season 2'}

server = jsonrpclib.Server('http://api.btnapps.net/')
parsedJSON = {}

parsedJSON = server.getTorrents(apikey, params, int(results_per_page), int(offset))

with open('datadump.txt', 'w') as fh:
    fh.write(parsedJSON)
```

**Comment by mtosic** [comment]
I wrote exactly the same helper script yesterday in Visual Studio (I'm C#/.NET dev, so I don't have much exp with python).

Result is empty, which is expected, because that season is airing (not finished yet).
Do you want me to try with some other params?

**Comment by abeloin** [comment]
Ok, can you try replacing btn.py with this copy:
https://raw.githubusercontent.com/abeloin/SickRage/patch-btn/sickbeard/providers/btn.py

**Comment by mtosic** [comment]
It works now, congrats and thank you so much!

P.S. if you need any dev help, I could maybe contribute, just need to pick up python syntax a bit :)

**Comment by abeloin** [comment]
You are welcome to submit some pull request anytime you want.

@fernandog I will post the PR later on.

**Comment by abeloin** [comment]
PR done

**Comment by fernandog** [comment]
@mtosic please update and report back

**Comment by fernandog** [comment]
@mtosic are you having issues like this in BTN?

https://sickrage.tv/forums/forum/help-support/general-support/20797-problem-downloading-from-btn
