### ISSUE TITLE
[Post processing] Remove leftovers

### ISSUE THREAD

**Issue by Alexwijn** [SiCKRAGETV/sickrage-issues#768]
When Sickrage is done post processing and he processed a torrent that has multiple files inside of it that are not videos files he will not delete those files. He only moves the video file.

Is it possible to have a setting to remove the entire folder and it contents after successfully moved the video file and that he sure there are no other video files left?

**Comment by fernandog** [comment]
@TagForce your new PR does that, doesn't it?

**Comment by TagForce** [comment]
@fernandog @Alexwijn No, mine does this only for files that are in a Rar file. Other files should already be deleted if process method is move. It does this the safest way possible, so files might get left.
I could add a "cleanup" option that deletes everything in the TV_DOWNLOAD folder when PP was successful.  But it's risky.

**Comment by OmgImAlexis** [comment]
@TagForce For now what about one that just deletes files by extension such as txt, png, jpeg and srt(for those that don't use subs). For people like me that'd help get rid of most of the unwanted stuff from public trackers.

**Comment by fernandog** [comment]
I would change the move associated files to a comma separeted list (Like sync files). Extension not in the list would be removed

**Comment by TagForce** [comment]
@fernandog This should no longer be needed. When Post Processing earlier there was a mistake in assigning result.result resulting in there always being an error in Post Processing, causing it to skip over the deletion of files. This has been fixed a couple of weeks ago.
Now, when processing is succesful for a folder, it will do the following to unwanted files:
```notwantedfiles = x for x in filelist if x not in videofiles (every file in the folder that is not a videofile)
if process_method != "move" or not result.result (if we move a file, and that was succesful)
delete_files(processPath, notwantedfiles, result) (delete all the files in notwantedfiles list, and update result with info from that action)

This means that anything left should be deleted.

**Comment by fernandog** [comment]
@TagForce but if I want to trash all EXCEPT subtitles for example?

**Comment by TagForce** [comment]
@fernandog Your FR asks to not do PP when there's no srt file associated with the video file. No srt means no processing means no deletion of anything. Once the srt is there, it will be processed and everything will be deleted. Mind you that SR will delete everything that is not a videofile, this includes srt files and RAR files. So it doesn't make a distinction between the kind of file it is. It's all or nothing.
