### ISSUE TITLE
[APP SUBMITTED]: Connection error ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host')) while loading URL http://services.tvrage.com/myfeeds/episode_list.php

### ISSUE THREAD

**Issue by SpecialKeezie** [SiCKRAGETV/sickrage-issues#771]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@7c6fe7fcbe9a8ccdb8d90a252f8680f2af7fa7ec
### ERROR
```
SHOWQUEUE-REFRESH :: Unable to look up show on TVRage, not downloading images: error Connection error ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host')) while loading URL http://services.tvrage.com/myfeeds/episode_list.php
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Server(services.tvrage.com) is overloaded
