### ISSUE TITLE
[APP SUBMITTED]: list.remove(x): x not in list

### ISSUE THREAD

**Issue by SpecialKeezie** [SiCKRAGETV/sickrage-issues#772]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@7c6fe7fcbe9a8ccdb8d90a252f8680f2af7fa7ec
Link to Log: https://gist.github.com/b8858167de02bd35bcfa
### ERROR
```
Thread-361 :: list.remove(x): x not in list
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
Need more info.

**Comment by fernandog** [comment]
@SpecialKeezie reply please or will close

**Comment by fernandog** [comment]
@TagForce is a real issue or something user did wrong?

**Comment by SpecialKeezie** [comment]
i'll be completely honest here, i didn't mean to submit this. i was checking error logs and must have accidentally pressed the submit button. i'm not sure why this error came up or what i was doing immediately before it happened. it has not come up again. i apologize
