### ISSUE TITLE
Type error in kodi.py

### ISSUE THREAD

**Issue by Tsaukpaetra** [SiCKRAGETV/sickrage-issues#775]
Just in case this hasn't been noticed, the file /sickbeard/notifiers/kodi.py has a type error on line 400. It should read like so:

    logger.log(u"Unable to decode JSON: " + response.read(), logger.WARNING)

At the moment, it reads:

    logger.log(u"Unable to decode JSON: " + response, logger.WARNING)

This results in an error, because the variable response is apparently an "instance" and not a string.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1371/files

**Comment by fernandog** [comment]
update and report back

**Comment by Tsaukpaetra** [comment]
Oh I didn't realize this was in the develop branch. That does work.  ;)
