### ISSUE TITLE
fatal: bad config file line 1 in .git/config

### ISSUE THREAD

**Issue by mjccox** [SiCKRAGETV/sickrage-issues#776]
Sickrage is great! ... super stable and never fails!.... almost....

Getting this error all the time... Any way to fix it?

CHECKVERSION :: git symbolic-ref -q HEAD returned : fatal: bad config file line 1 in .git/config

**Comment by abeloin** [comment]
Your git config file is corrupted. If you have a backup of that file you can replace it if not you will to clone sickrage again.

See google: https://www.google.ca/search?q=fatal:+bad+config+file+line+1+in+.git/config for more info.
