### ISSUE TITLE
Manually modified scene numbering is not being used for searches

### ISSUE THREAD

**Issue by suprdave23** [SiCKRAGETV/sickrage-issues#777]
This is on the latest develop branch that I pulled yesterday. I don't have commit number as my config was restored :)

I have the show "19 kids and counting" added to my show list. I updated the scene numbering for s15e01 to "10x1" as this is the actual numbering being used on KAT. The show has "Scene numbering" checked. However backlog searches and manual searches are not using this numbering, so as a result the episode is not being found. If I leave the show and come back, my modified scene number stays there, so I do believe it was updated.

In the debug log it shows the search string being used is "http://.....19.kids.and.counting%20S15E01.....", so it is clear that it is ignoring my scene numbering setting.

Please advise on how to correct this. Thanks!

**Comment by fernandog** [comment]
FULL log please

**Comment by suprdave23** [comment]
@fernandog  In the process of setting debug to 1 in my config and starting SR back up, it searched the right episode numbering this time and grabbed it. I could see in the debug output the search string was looking for my modified scene number this time.

It looks like changing scene numbers requires a restart of SR?

If you still want the log I can grab it for you, didn't include it on this reply since my problem appears to be fixed after a restart.

**Comment by fernandog** [comment]
don't know.  no need if your issue is resolved

**Comment by abeloin** [comment]
@suprdave23 Can you test this PR: https://github.com/SiCKRAGETV/SickRage/pull/1422

**Comment by suprdave23** [comment]
@abeloin Thanks for the update! I pulled it down and ti seems to be doing fine. Will reply back on this ticket if I notice this problem any further
