### ISSUE TITLE
subtitle errors after fresh install

### ISSUE THREAD

**Issue by scythe000** [SiCKRAGETV/sickrage-issues#778]
Running on Windows Server 2012. I had to reinstall, and followed the tutorial to a T:
BRANCH: (master) / COMMIT: (2d8aad80cdfb8983832206af445039de0decded9) 

Getting these errors constantly, although subtitling seems to be working:

```
2015-02-26 08:23:01 FINDSUBTITLES :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "c:\SickRage\sickbeard\tv.py", line 1399, in downloadSubtitles
    multi=sickbeard.SUBTITLES_MULTI, cache_dir=sickbeard.CACHE_DIR)
  File "c:\SickRage\lib\subliminal\api.py", line 95, in download_subtitles
    subtitles_by_video = list_subtitles(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "c:\SickRage\lib\subliminal\api.py", line 54, in list_subtitles
    tasks = create_list_tasks(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "c:\SickRage\lib\subliminal\core.py", line 58, in create_list_tasks
    scan_result.extend(scan(p, max_depth, scan_filter))
  File "c:\SickRage\lib\subliminal\videos.py", line 247, in scan
    return [(video, video.scan())]
  File "c:\SickRage\lib\subliminal\videos.py", line 140, in scan
    results.extend([subtitles.EmbeddedSubtitle.from_enzyme(self.path, s) for s in video_infos.subtitles])
  File "c:\SickRage\lib\subliminal\subtitles.py", line 75, in from_enzyme
    language = Language(subtitle.language, strict=False)
  File "c:\SickRage\lib\subliminal\language.py", line 856, in __init__
    for regexp in [r.match(language) for r in self.with_country_regexps]:
TypeError: expected string or buffer
```
Here's the log:

http://pastebin.com/8X3g7PUD

**Comment by fernandog** [comment]
send a print of your subtitle settings

**Comment by scythe000** [comment]
![screenshot 2015-02-26 08 49 39](https://cloud.githubusercontent.com/assets/1904522/6396655/8a6b0770-bd94-11e4-8ce7-5f321880b41b.png)

**Comment by fernandog** [comment]
@scythe000 which plugins are enabled?

**Comment by scythe000** [comment]
Tvsubtitles and Opensubtitles.

**Comment by fernandog** [comment]
@abeloin do you know whats wrong?

**Comment by abeloin** [comment]
@scythe000 Can you show me the content of The Simpsons' season 4?

`Downloading subtitles for episode 4x3 of show The Simpsons`

**Comment by scythe000** [comment]
![screenshot 2015-02-26 09 20 02](https://cloud.githubusercontent.com/assets/1904522/6397326/c0625348-bd98-11e4-8677-256c248cc371.png)

**Comment by abeloin** [comment]
Sorry I meant the content on the hard drive from Windows Explorer.

**Comment by scythe000** [comment]
![new bitmap image](https://cloud.githubusercontent.com/assets/1904522/6397774/0f88071c-bd9c-11e4-9cce-9df5a235e2ea.jpg)

**Comment by abeloin** [comment]
What is the fullname for S04E03 as I can see it completely in the screenshot?

**Comment by scythe000** [comment]
Simpsons 04x03 - Homer the Heretic [rl-dvd].ogm

**Comment by abeloin** [comment]
Ok can you update your screenshot so that I can see all the filename?

**Comment by scythe000** [comment]
![new bitmap image 2](https://cloud.githubusercontent.com/assets/1904522/6398852/5b7fb122-bda3-11e4-8789-c9490ce733ef.jpg)

**Comment by abeloin** [comment]
Can you try renaming the file `Simpsons 04x03 - Homer the Heretic [rl-dvd].ogm` to `Simpsons 04x03 - Homer the Heretic [rl].ogm`, do a rescan in the show and retry the subtiles?

**Comment by scythe000** [comment]
ok, did that and got this:

10:44:31 INFO::SHOWQUEUE-REFRESH :: Performing refresh on The Simpsons
10:44:31 INFO::SHOWQUEUE-REFRESH :: 71663: Loading all episodes from the show di
rectory E:\TV Series\The Simpsons
10:44:54 ERROR::SHOWQUEUE-REFRESH :: 71663: Could not refresh subtitles
Traceback (most recent call last):
  File "c:\SickRage\sickbeard\tv.py", line 445, in loadEpisodesFromDir
    curEpisode.refreshSubtitles()
  File "c:\SickRage\sickbeard\tv.py", line 1380, in refreshSubtitles
    self.subtitles = subtitles.subtitlesLanguages(self.location)
  File "c:\SickRage\sickbeard\subtitles.py", line 71, in subtitlesLanguages
    subtitles = video.scan()
  File "c:\SickRage\lib\subliminal\videos.py", line 140, in scan
    results.extend([subtitles.EmbeddedSubtitle.from_enzyme(self.path, s) for s i
n video_infos.subtitles])
  File "c:\SickRage\lib\subliminal\subtitles.py", line 75, in from_enzyme
    language = Language(subtitle.language, strict=False)
  File "c:\SickRage\lib\subliminal\language.py", line 856, in __init__
    for regexp in [r.match(language) for r in self.with_country_regexps]:
TypeError: expected string or buffer

**Comment by abeloin** [comment]
Can you check in the "The Simpsons" folder and all subfolder for subtitle files and check that the last 2 2 letters before the dot are en(en.srt)

**Comment by scythe000** [comment]
Yes, all srt files in that folder end in en.srt

**Comment by abeloin** [comment]
@TagForce Have you ever seen this?

**Comment by abeloin** [comment]
@scythe000 Can you try switching to develop branch?

**Comment by scythe000** [comment]
Sure thing. How do I do that? :-)

**Comment by scythe000** [comment]
Do I just "git checkout develop"?

**Comment by abeloin** [comment]
Or in the Web ui in config -> general -> Advanced setting. Choose develop and click Checkout

**Comment by scythe000** [comment]
Wow, that's awesome. Also I can set the portable git path, which is nice because it changes every few months.

**Comment by scythe000** [comment]
It sees 5 updates, but I get this:
`2015-02-26 17:05:37 CHECKVERSION :: "C:\Users\Administrator\AppData\Local\GitHub\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\libexec\git-core\git.exe" pull -f origin develop returned : fatal: 'pull' appears to be a git command, but we were not
able to execute it. Maybe git-pull is broken?`

**Comment by abeloin** [comment]
Did you set the `Git executable path` underneath to your git executable?

**Comment by scythe000** [comment]
Yep: C:\Users\Administrator\AppData\Local\GitHub\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\libexec\git-core\git.exe

matches C:\Users\Administrator\AppData\Local\GitHub\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\libexec\git-core\git.exe

**Comment by scythe000** [comment]
I've got Git in my system path, so I tried deleting the path from SR. It finds Git at the same path, but gives the same error.

**Comment by abeloin** [comment]
It would seem your git install is broken.

**Comment by scythe000** [comment]
It's freshly installed as of last night. I'll run a manual pull.

**Comment by scythe000** [comment]
ok:
`C:\>cd SickRage

C:\SickRage>git pull
Updating fdd1f63..edb337f
Fast-forward
 sickbeard/providers/btn.py   | 203 +++++++++++++++++++++++++++++++++++++++++++
 sickbeard/scene_numbering.py |   5 ++
 2 files changed, 208 insertions(+)

C:\SickRage>,

**Comment by abeloin** [comment]
Maybe it's because you use the portable version?

**Comment by abeloin** [comment]
`git checkout develop`
restart sickrage

**Comment by scythe000** [comment]
Done. Error on launch is 
`2015-02-26 17:27:27 FINDSUBTITLES :: Error occurred when downloading subtitles: expected string or buffer`

**Comment by abeloin** [comment]
Are you comfortable with using the pdb to debug the issue?

**Comment by scythe000** [comment]
I'm happy to learn!

**Comment by scythe000** [comment]
However I can help out the project, I'll do it, haha.

**Comment by scythe000** [comment]
I'm also open to setting up a remote session, if that's easier for you.

**Comment by abeloin** [comment]
It is not that complicated, you need to launch sickrage manually from the command line.

* Insert `import pdb; pdb.set_trace()` in between line 74-75 of c:\SickRage\lib\subliminal\subtitles.py:
```
    def from_enzyme(cls, path, subtitle):
        import pdb; pdb.set_trace()
        language = Language(subtitle.language, strict=False)
        return cls(path, language, subtitle.trackno)
```
* Launch sickrage in a command line:
`python SickBeard.py --nolaunch -q`

* On the command line, you should see something like this after it start to find subtitle:
```
> .../subtitles.py(75)from_enzyme()
->
```
Now the fun part:
* Type `p path`
* Wait until the ```->``` is shown again.
* Type `p subtitle.language`
* Wait until the ```->``` is shown again.
* Type c
* If you see the ```->``` re-start from "Type `p path`"
* If you get the error, take the value of path and subtitle.language just before the error and post it here.

You can use the arrow to reuse a previous command

**Comment by abeloin** [comment]
If you have too much difficulty, will setup a team viewer session.

**Comment by scythe000** [comment]
Not sure if I'm doing it right

`C:\SickRage>python SickBeard.py --nolaunch -q
> c:\sickrage\lib\subliminal\subtitles.py(76)from_enzyme()
-> language = Language(subtitle.language, strict=False)
(Pdb) p path
u'E:\\TV Series\\The Simpsons\\Simpsons Season 04 - Complete [rl]\\Simpsons 04x0
3 - Homer the Heretic [rl].ogm'
(Pdb) p subtitle.language
None
(Pdb) c
`

**Comment by scythe000** [comment]
just gave me the Cheetah warning...

**Comment by scythe000** [comment]
Seems to just be sitting there

**Comment by abeloin** [comment]
ok let me check

**Comment by abeloin** [comment]
`CTRL-C` to terminate
Instead of pressing c, press n until you see again:
```
c:\sickrage\lib\subliminal\subtitles.py(76)from_enzyme()
```
then 
Type p path
Wait until the -> is shown again.
Type p subtitle.language

**Comment by scythe000** [comment]
Ok, ctrl-c killed everything. I'll follow the steps and press n instead of c.

**Comment by scythe000** [comment]
How's this?
`C:\SickRage>python SickBeard.py --nolaunch -q
> c:\sickrage\lib\subliminal\subtitles.py(76)from_enzyme()
-> language = Language(subtitle.language, strict=False)
(Pdb) p path
u'E:\\TV Series\\The Simpsons\\Simpsons Season 04 - Complete [rl]\\Simpsons 04x0
3 - Homer the Heretic [rl].ogm'
(Pdb) p subtitle.language
None
(Pdb) n
TypeError: 'expected string or buffer'
> c:\sickrage\lib\subliminal\subtitles.py(76)from_enzyme()
-> language = Language(subtitle.language, strict=False)
(Pdb) p path
u'E:\\TV Series\\The Simpsons\\Simpsons Season 04 - Complete [rl]\\Simpsons 04x0
3 - Homer the Heretic [rl].ogm'
(Pdb) p subtitle.language
None
(Pdb)`

**Comment by scythe000** [comment]
I think it thinks no language is set.

**Comment by abeloin** [comment]
Ok I think it's trying to extract the language for the ogm, give me a sec I'm checking the code

**Comment by abeloin** [comment]
Is their a subtitle inside `E:\\TV Series\\The Simpsons\\Simpsons Season 04 - Complete [rl]\\Simpsons 04x03 - Homer the Heretic [rl].ogm`?

**Comment by scythe000** [comment]
Aha, yes VLC says 3 tracks.

**Comment by abeloin** [comment]
Can you get a report of those track from vlc or MediaInfo

**Comment by scythe000** [comment]
![new bitmap image](https://cloud.githubusercontent.com/assets/1904522/6406454/dbdd8384-bde5-11e4-98f9-d655b34484f0.jpg)

**Comment by abeloin** [comment]
It would seem there's no language defined

**Comment by scythe000** [comment]
So...poorly coded OGM file is making SR throw errors?

**Comment by scythe000** [comment]
I'm just finishing up at a training conference at Microsoft's Irvine HQ...gotta run for now, but I'll be home in about 3 hours or so, and can t/s further.

**Comment by abeloin** [comment]
It's the subliminal library

**Comment by scythe000** [comment]
Got it. So, not much we can do, other then raise a bug over on their github, right?

Sent from my iPhone

On Feb 26, 2015, at 6:43 PM, Alexandre Beloin <notifications@github.com<mailto:notifications@github.com>> wrote:


It's the subliminal library

**Comment by abeloin** [comment]
Not really an option as we are using a very old version, and their new version is a complete rewrite which is incompatible with the old one. Someone is in the process of adapting sickrage to the new version. So for the time being subliminal fixes are done internally

**Comment by scythe000** [comment]
Well, I'm glad I was able to help us get to the bottom of this! Sorry it was so much trouble :-)

Sent from my iPhone

On Feb 26, 2015, at 6:47 PM, Alexandre Beloin <notifications@github.com<mailto:notifications@github.com>> wrote:


Not really an option as we are using a very old version, and their new version is a complete rewrite which is incompatible with the old one. Someone is in the process of adapting sickrage to the new version. So for the time being subliminal fixes are done internally

**Comment by abeloin** [comment]
Can you test this PR https://github.com/SiCKRAGETV/SickRage/pull/1427 ?

**Comment by scythe000** [comment]
Manually edit the file? Or can I pull this patch with git?

**Comment by scythe000** [comment]
Hey found something else, found 8 subtitles appeared in my sickrage folder
![new bitmap image](https://cloud.githubusercontent.com/assets/1904522/6407788/5aed5ecc-bdfc-11e4-9e7e-1d5850a44a21.jpg)

**Comment by scythe000** [comment]
I just edited the .py file manually. Looks like that did it!

I did just get this error:

'2015-02-26 21:16:55 CHECKVERSION :: git fetch origin returned : fatal: unable to access 'https://github.com/SiCKRAGETV/SickRage.git/': Could not resolve host: github.com
2015-02-26 21:16:55 CHECKVERSION :: Unable to contact github, can't check for update'

**Comment by scythe000** [comment]
But no subtitle errors!

**Comment by abeloin** [comment]
Looking at the time stamp it was earlier today that happened before you switch to develop which include a fix for that. You can remove those files.

DNS error temporairy on your side

Good

**Comment by abeloin** [comment]
For ref: ogm File Structure:
```
UTF-8
|       type: OGG Media
|    subtype: 
|       mime: application/ogm
|    encoder: Xiph.Org libVorbis I 20020717
+-- Video Track #1
|    |     length: 1377
|    |    bitrate: 24
|    |      codec: XVID
|    |      width: 480
|    |     height: 360
|    |        fps: 23
+-- Audio Track #1
|    |   channels: 0
|    | samplerate: 44100
|    |     length: 1378
|    |    bitrate: 952238081
+-- Audio Track #2
|    |   channels: 0
|    | samplerate: 44100
|    |     length: 1378
|    |    bitrate: 854523905
+-- Subtitle #1
|    +-- Subtitle #2
|    +-- Subtitle #3
|    
```

**Comment by abeloin** [comment]
PR merged
