### ISSUE TITLE
isohunt.to rss url

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#78]
<a href="https://github.com/pickettwayne"><img src="https://avatars.githubusercontent.com/u/3720390?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pickettwayne](https://github.com/pickettwayne)**
_Friday Dec 12, 2014 at 13:15 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/1097 (0 comment(s))_

----

The rss url for isohunt is not being recognised by sickrage. Regards

**Comment by fernandog** [comment]
closing as I didn't received an reply
