### ISSUE TITLE
[Feature Request] moving "complete" and ended shows to a separate section.

### ISSUE THREAD

**Issue by Etheral** [SiCKRAGETV/sickrage-issues#781]
so I have a few shows in sick rage that have ended and I have all the episodes for and some that I don't. would it be possible to have a separate section at the bottom (like with anime) that shows that have ended and have all episodes downloaded are moved to? it would make glancing over shows to check things a bit faster. 

I know I could remove them but if a show gets a reboot/optioned I don't want to have to re-add them etc.

Thanks,

**Comment by pct00** [comment]
+1

**Comment by freddysmith1** [comment]
+1

**Comment by vlsoft** [comment]
+1 .

**Comment by abeloin** [comment]
@freddysmith1 When a show is "Ended" it isn't refresh every-time. Only the last 10 recently ended shows, and 10 shows that haven't been refresh in the last 90 days are refreshed.

See https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/showUpdater.py#L52 for more info

**Comment by saitoh183** [comment]
+1

**Comment by maxcore** [comment]
+1

**Comment by Thraxis** [comment]
Would this be a request for something similar to the anime split option but instead a split of non-active?  The other question is would the new filter option with being able to filter for active, continuing, etc. cover this request?

**Comment by Etheral** [comment]
@Thraxis the original intention was for something like the anime split but a filtering option could also work although it's not exactly like filtering for continuing or ended.
if it was to feature as a filter I would word it as "incomplete" or "up to date" and filter out shows that had all available episodes.

**Comment by abeloin** [comment]
@Etheral The filter allow you to filter on any column, so you choose active and <100 % complete

**Comment by Etheral** [comment]
Well in that case I think I'm happy.
I'm running sickrage on my openelec microserver and I'm away from home on contract work at the moment so I haven't had a chance to update/try out the new filter options.

**Comment by LauwS** [comment]
+1

**Comment by pct00** [comment]
hi guys
is the split option not possible

the filter works but it would be nice to have the split option to see all the shows "sorted" without having to filter all the time

**Comment by fernandog** [comment]
Filter is saved. Dont need to filter everytime.
