### ISSUE TITLE
[APP SUBMITTED]: Cannot find attribute 'contentrating'

### ISSUE THREAD

**Issue by jiBYo** [SiCKRAGETV/sickrage-issues#782]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@2d8aad80cdfb8983832206af445039de0decded9
Link to Log: https://gist.github.com/59ce9b04b36496aafc05
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: Cannot find attribute 'contentrating'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by TagForce** [comment]
@fernandog @abeloin It seems like the Mede8ter metadata creator wants to fill out a contentrating attribute, but tvrage doesn't supply one. I'm experiencing the same issue on my testrig when testing a fix to https://github.com/SiCKRAGETV/sickrage-issues/issues/780

**Comment by TagForce** [comment]
@abeloin @jiBYo https://github.com/SiCKRAGETV/SickRage/pull/1430 fixes this issue.

**Comment by abeloin** [comment]
PR Merged
@TagForce Can you you update and test?

**Comment by TagForce** [comment]
@abeloin It works on my dev and production rigs

**Comment by abeloin** [comment]
Thanks for the testing
