### ISSUE TITLE
[Feature Request] Choose torrent with highest seeders/peers

### ISSUE THREAD

**Issue by suprdave23** [SiCKRAGETV/sickrage-issues#786]
Feature request.

Super frustrating to have a torrent that has 400 seeders, but have SR choose to grab the one with 3!

**Comment by neoatomic** [comment]
![naamloos](https://cloud.githubusercontent.com/assets/7928052/6417275/b79cb70c-beac-11e4-9101-1e69650c12d2.jpg)

**Comment by suprdave23** [comment]
Hi neoatomic,

Thanks but this isn't the same thing. 

If I am searching the backlog for an old episode, 2 torrents could come up, one with 1 seeder and 1 with 5. If I had the minimum seeders at "10" in order to ensure when new episodes come out it grabs an active one, it wouldn't find either of them. 

SR should have all of the information regarding how many seeders/leechers a torrent has. It should be able to rank them in descending order and choose the one that both:

A. Meets the quality requirements
B. Has the most seeds out of these that meet the quality requirements.

**Comment by fernandog** [comment]
@suprdave23 maybe that one is trusted/verified. SR order search result by seeders

**Comment by suprdave23** [comment]
@fernandog I have "Confirmed download" *unchecked* in all of my provider options. 

As an example, I enabled "Any" for the quality for Duck Dynasty. I then manually searched (clicked the magnifying glass icon) s07e01. It chose to download "Duck.Dynasty.S07E01.720p.HDTV.x264-KILLERS[rartv]" which was the second highest one with seeders, not the first. 

The URL it says it was using to search is: https://kickass.to/usearch/Duck.Dynasty+S07E01%7C7x01+category%3Atv/?field=seeders&sorder=desc&rss=1

Logs can be found here: http://pastebin.com/ieHkaJ0W

Why did it not choose the one that had the most seeds? I see the search string is sorting by seeders desc, but it didn't choose the one that was at the top.

Thanks for the help!

**Comment by fernandog** [comment]
which one should be downloaded in your opinion?

**Comment by suprdave23** [comment]
@fernandog The one that had the most seeds, "Duck Dynasty.S07E01.Glory is the Reward of Mallard.mp4 (HDTV 1080)".

I see now in the logs it couldn't parse "HDTV 1080" as a quality, and flagged it as "Unknown". That might be the reason why it didn't choose it, however if that's the case "Any" quality really should mean "I don't care about the quality, just choose the one that has the most seeds".

**Comment by fernandog** [comment]
```
13:05:31 INFO::SEARCHQUEUE-MANUAL-256825 :: Quality of Duck.Dynasty.S07E01.Glory.is.the.Reward.of.Mallard.mp4.(HDTV.1080) is Unknown
```

the torrent does not have the proper naming convention

the others results:
```
13:05:30 INFO::SEARCHQUEUE-MANUAL-256825 :: Quality of Duck.Dynasty.S07E01.720p.HDTV.x264-KILLERS[rartv] is HD TV
13:05:30 INFO::SEARCHQUEUE-MANUAL-256825 :: Quality of Duck.Dynasty.S07E01.720p.HDTV.x264-KILLERS is HD TV
13:05:30 INFO::SEARCHQUEUE-MANUAL-256825 :: Quality of Duck.Dynasty.S07E01.720p.HDTV.x264-KILLERS is HD TV
13:05:31 INFO::SEARCHQUEUE-MANUAL-256825 :: Quality of Duck.Dynasty.S07E01.HDTV.x264-KILLERS[rartv] is SD TV
13:05:31 INFO::SEARCHQUEUE-MANUAL-256825 :: Quality of Duck.Dynasty.S07E01.HDTV.XviD-AFG is SD TV
13:05:31 INFO::SEARCHQUEUE-MANUAL-256825 :: Quality of Duck.Dynasty.S07E01.Glory.is.the.Reward.of.Mallard.HDTV.XviD-AFG is SD TV
13:05:31 INFO::SEARCHQUEUE-MANUAL-256825 :: Quality of Duck.Dynasty.S07E01.HDTV.x264-KILLERS[ettv] is SD TV
13:05:31 INFO::SEARCHQUEUE-MANUAL-256825 :: Quality of Duck.Dynasty.S07E01.Glory.is.the.Reward.of.Mallard.HDTV.XviD-AFG is SD TV
13:05:31 INFO::SEARCHQUEUE-MANUAL-256825 :: Quality of Duck.Dynasty.S07E01.HDTV.x264-KILLERS is SD TV
13:05:31 INFO::SEARCHQUEUE-MANUAL-256825 :: Quality of Duck.Dynasty.S07E01.HDTV.x264-KILLERS is SD TV
13:05:31 INFO::SEARCHQUEUE-MANUAL-256825 :: Quality of Duck.Dynasty.S07E01.Glory.is.the.Reward.of.Mallard.720p.HDTV.x26 is Unknown
13:05:31 INFO::SEARCHQUEUE-MANUAL-256825 :: Quality of Duck.Dynasty.S07E01.Glory.is.the.Reward.of.Mallard.480p.HDTV.x26 is Unknown
13:05:31 INFO::SEARCHQUEUE-MANUAL-256825 :: Quality of Duck.Dynasty.S07E01.Glory.is.the.Reward.of.Mallard.720p.HDTV.x26 is Unknow
```

**Comment by suprdave23** [comment]
Right. However "Any" quality really should mean "I don't care about the quality, just choose the one that has the most seeds". Unknown quality shouldn't be a factor in that case in my opinion.

**Comment by fernandog** [comment]
ANY quality is different from UNKNOWN. Any quality should be from 480p to 1080. Unknown is nothing!

**Comment by suprdave23** [comment]
Okay. Is there an option for allowing Unknown qualities then? If there's a lot of seeders on a file, it's clear it's a legit file that plays. Failure to parse a quality string should not equal "ignore the file".

**Comment by fernandog** [comment]
downloading unknown you can get a lot of fakes

**Comment by suprdave23** [comment]
Understandable, but unlikely for older episodes.

I did see that "Unknown" is a quality you can select in "Custom" quality settings. So, I chose "Custom", selected every single quality including "Unknown", and repeated the search. It still ignored that episode that has the most seeds and went with the next one that it could parse the quality settings for.

I believe I have found a bug. Even with "Unknown" selected as a quality setting it is still not downloading the one that has the most seeds.

**Comment by fernandog** [comment]
full LOGs again please

@abeloin cache related too?

**Comment by suprdave23** [comment]
Logs: http://pastebin.com/t60GNZiH

**Comment by suprdave23** [comment]
@abeloin @fernandog 

Any updates on this yet? I am eager to test any fixes! :)

**Comment by abeloin** [comment]
@suprdave23 There's no bug here, sickrage doesn't refine it search by most seeders after it check for quality. If you choose all qualities, it will pick the best quality regardless of the numbers of seeders.

**Comment by suprdave23** [comment]
@abeloin OK thanks for clearing that up. Can this be considered for a future version? It seems like making this behavior (choose the best quality *with* the best seed number) the default would make sense.

**Comment by abeloin** [comment]
Yes it is the feature request.

**Comment by peterjeliot** [comment]
I'd like to add my +1 to this feature request. SickRage keeps picking junk torrents that never download, when I just want it to pick the most highly seeded torrent regardless of quality. I don't care what quality it is, I just want the episode.

With Adventure Time, there is usually only one well-seeded torrent on Kickass Torrents, but SickRage always manages to pick one that can't even download the metadata. It used to work okay, but now SickRage is nearly useless for automatic downloading...

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
