### ISSUE TITLE
[APP SUBMITTED]: execv() arg 2 must contain only strings

### ISSUE THREAD

**Issue by SwordX04** [SiCKRAGETV/sickrage-issues#787]
### INFO
Python Version: **2.7.3 (default, Dec 27 2013, 16:05:18) 
[GCC 4.6.3]**
Operating System: **Linux-3.4.26-i686-with-glibc2.3**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@35ff96e54cb9c4efc7c6d204fc8bdc1ca58ec04e
Link to Log: https://gist.github.com/fe6a9e6814d4f771a3fd
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: execv() arg 2 must contain only strings
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@Tagforce

**Comment by abeloin** [comment]
My guess is that the cp subprocess is unable to convert the é in série.

You could try PR https://github.com/SiCKRAGETV/SickRage/pull/1308

**Comment by SwordX04** [comment]
@abeloin Thanks, I replace 'é' by 'e' for my folder's name and it's fine.

**Comment by abeloin** [comment]
@SwordX04 PR SiCKRAGETV/SickRage#1308 should fix this when it will be merged

**Comment by fernandog** [comment]
@SwordX04 any luck?
