### ISSUE TITLE
Add New Show - Continually Loading...

### ISSUE THREAD

**Issue by egmaf** [SiCKRAGETV/sickrage-issues#791]
In short: After adding a new show (new or existing), the show list shows "(loading) | Loading... (tv_shows_deault_folder\tv_show_name)" for this show. All previously added shows are in the list as they should be, all future added show have the problem. 

I am on BRANCH: (master) / COMMIT: (2d8aad80cdfb8983832206af445039de0decded9),
running Python Version: 2.7.3 (default, Apr 10 2012, 23:24:47) [MSC v.1500 64 bit (AMD64)] on a Windows 8.1 machine.

Someone else posted a perfect description here: https://sickrage.tv/forums/forum/help-support/bug-issue-reports/10795-add-new-show-continually-loading
and this seems to be the same issue: https://sickrage.tv/forums/forum/help-support/general-support/16979-new-shows-stuck-to-loading

**Comment by abeloin** [comment]
Can you provide debug logs when this happen?

**Comment by egmaf** [comment]
After weeks of fiddling, something I did resolved it (for now)….

Might be disabling IPv6, or disabling Hamachi (VPN), or one of thousands of things that I’m sure I tried before without effect!

 

I’ll let you know when it returns

 

Thanks
