### ISSUE TITLE
[Feature Request] Add "Quality" to failed.db

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#792]
Add "Quality" column to failed.db. Needs to upgrade the DB

Today in history UI, it shows N/D quality

SHOW - S00E00	Failed	 PROVIDER N/A 
SHOW - S00E00	Snatched	 PROVIDER	HD TV

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
