### ISSUE TITLE
[APP SUBMITTED]: coercing to Unicode: need string or buffer, HTTPError found

### ISSUE THREAD

**Issue by hoefs** [SiCKRAGETV/sickrage-issues#795]
### INFO
Python Version: **2.7.8 (default, Dec 12 2014, 20:09:05) 
[GCC 4.6.4]**
Operating System: **Linux-2.6.32.12-armv5tel-with-glibc2.4**
Branch: **master**
Commit: SiCKRAGETV/SickRage@2d8aad80cdfb8983832206af445039de0decded9
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: coercing to Unicode: need string or buffer, HTTPError found
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
Can you provide more log?
