### ISSUE TITLE
[APP SUBMITTED]: <sickbeard.tv.TVEpisode object at 0x9d6a1f8c>

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#799]
### INFO
Python Version: **2.7.8 (default, Oct 20 2014, 15:05:29) 
[GCC 4.9.1]**
Operating System: **Linux-3.16.0-30-generic-i686-with-Ubuntu-14.10-utopic**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@583da987e4309ce009374b10e76fbf1fb1fada78
### ERROR
```
SEARCHQUEUE-BACKLOG-79771 :: [KickAssTorrents] :: Error while searching KickAssTorrents, skipping: error Air Crash Investigation - Mayday - 14x8 - Inner City Carnage
location: 
description: On 4 November 2008, an official Mexican Interior Ministry Learjet 45 crashes in central Mexico City. Mexican Secretary of the Interior Juan Camilo Mouriño, who was aboard the plane, was killed in the crash, along with the other seven people on board and eight people on the ground. The plane crashed in rush-hour traffic at Las Lomas. The plane crashed due to a loss of control from wake turbulence.
subtitles: 
subtitles_searchcount: 0
subtitles_lastsearch: 0001-01-01 00:00:00
airdate: 735646 (2015-02-17)
hasnfo: False
hastbn: False
status: 3

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@matigonkas please send full logs

**Comment by fernandog** [comment]
@mwarnaar KAT its not working with file lists too?

https://github.com/SiCKRAGETV/SickRage/pull/1359

**Comment by matigonkas** [comment]
I cant find the logs of that error anymore and it didnt happen anymore ,probably it was only a insolated case.
