### ISSUE TITLE
[Feature Request] Add MediaBrowser notification support

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#8]
<a href="https://github.com/josh4trunks"><img src="https://avatars.githubusercontent.com/u/1018807?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [josh4trunks](https://github.com/josh4trunks)**
_Friday Nov 21, 2014 at 01:15 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/927 (0 comment(s))_

----

Can we get notification support for MediaBrowser?

I believe @LukePulverenti can give you whatever API info you need for this.

Thanks

**Comment by SamJongenelen** [comment]
+1 here

**Comment by SamJongenelen** [comment]
Note: MediaBrowser is now called Emby

**Comment by josh4trunks** [comment]
Hey @LukePulverenti I started looking into implementing this, though I'm not very proficient in python (or anything language really).

Am I correct that the below URLs are what SickRage would need to request? Thanks!

----

* Series Added (full library scan)
/emby/Library/Series/Added?tvdbid=xxx
Headers
    * X-Emby-Token = API_Key

* Series Updated (series folder library scan)
/emby/Library/Series/Updated?tvdbid=xxx
Headers
    * X-Emby-Token = API_Key

* Notification
/emby/Notifications/Admin
Headers
    * X-Emby-Token = API_Key
    * ContentType = "application/json"
```Body:
{
Name: "SickRage",
Description:"xxx",
ImageUrl: "https://raw.githubusercontent.com/SiCKRAGETV/SickRage/master/gui/slick/images/sickrage-shark-mascot.png"
}
```

**Comment by LukePulverenti** [comment]
Yes although I think you can skip notifications because users can already configure notifications for new content. Also, identifying by tvdb id is what sickbeard wanted, although truthfully I'd prefer to go provider agnostic and have you just supply the actual folder path. but whatever you prefer is fine.

**Comment by josh4trunks** [comment]
Ok, sounds good. So to confirm we don't have the path option right now?

**Comment by LukePulverenti** [comment]
It's not currently there, no. Another way we could do this is you could have it supply all known provider id's on the query string, which would make it more resilient to different libraries. So for example, &tvdbid=xxx&imdbid=xxx&tvrageid=xxx. You can do that now and it will function immediately but will just ignore the extra id's, which i'll support for the next release.

**Comment by josh4trunks** [comment]
Ahh great. Ok, I'm not sure when I'd be able to get to this as I'm basically learning as I go. But, I wanted to make our end goal a little more clear incase others with the skills to do this felt inclined.

**Comment by SamJongenelen** [comment]
Hey guys, thank you for taking this up. I had already started forking and tinkering. However i have 0 experience with Python (I'm a C# developer..)  I've had my Emby classes ready (copied from Plex Notify class) but I cant get the new notifier to show up in the webpage.. Ah well, great that you're working on it GL

**Comment by josh4trunks** [comment]
@LukePulverenti or @echel0n 
Mind pointing me in the right direction what I'm doing wrong here?
https://github.com/josh4trunks/SickRage/blob/0a7210c2d1d482a965397fb089721dea34fc9732/sickbeard/notifiers/emby.py
* note - on my running copy I am editing sickbeard/\__init\__.py to set my EMBY related variable for now

I get this error in SickRage
```EMBY: Warning: Couldn't contact Emby at http://127.0.0.1:8096/mediabrowser/Library/Series/Updated?tvdbid=289590```
And this error in Emby
```Error - NotFoundHttpHandler: 192.168.2.27:8096 Request not found: /emby/Library/Series/Updated?tvdbid=289590```

**Comment by josh4trunks** [comment]
TODO

* [ ] Get post-processing initially communicating
* [ ] Add GUI components to set options
* [ ] \(If required\) Add hook to request "/emby/Library/Series/Added"
    * note - test what emby does when it is told about a new episode for a series it doesn't yet have in it's library. If this doesn't work, this step needs to be done

**Comment by josh4trunks** [comment]
@LukePulverenti I got this partially working but need to get the GUI stuff in then I'll submit my PR.

Here's some notes I have from working through this.
* The API doesn't seem to recognize X-Emby-Token so I had to revert to using X-MediaBrowser-Token
* Whenever I call "/emby/Library/Series/Updated?tvdbid=xxx" the whole library is scanned. I can't seem to get Emby to only see new media for the show I specify. This might cause issues for systems that are low powered/slow storage & have large libraries.
* There are definitely ways to get the show path in SickRage that could be passed to Emby's API if you wanted to implement this. The only issue I see with this are when Emby and SickRage see the media files not using the exact same path. A workaround Emby could implement would be to just do a full library rescan if the path it received doesn't exist.

**Comment by SamJongenelen** [comment]
Please note that Emby could use UNC paths (even for local playback), to facilitate upnp/dlna streaming. Perhaps the TV show path should be configurable?

**Comment by josh4trunks** [comment]
@echel0n @miigotu
My branch to add Emby notification support is complete here.
https://github.com/josh4trunks/SickRage/tree/emby_notify
I can rebase off the develop branch then submit a PR if that makes things easier.

But... there is an issue I can't seem to solve. I can never get my Emby related settings to stick between SR restarts. I see the settings getting written into config.ini, but every time I restart SR the settings are defaulted in the WebUI. Mind taking a look so I can get this fixed? Thanks!

**Comment by miigotu** [comment]
I can try to look at this sometime soon. wish this came a bit sooner as we are about halfway through the switch to mako. Will need to modify the templates a bit.

Should not bee too hard to find out why the settings arent staying. Does it work when the settings are set?

**Comment by josh4trunks** [comment]
Everything works as expected until SR is (re)started.

Even though it's saving the correct values in the config.ini it doesn't seem to be loading them, because the "Update Emby" button isn't showing on the home page. Then when I browse to the notification config page, the emby settings are all reset. If I save or stop SR at that point the emby values in config.ini are also reset.

**Comment by miigotu** [comment]
Gotta finish switching mako in for cheetah in webserve.py in the mako branch and then I will look at it.
https://github.com/SiCKRAGETV/SickRage/commits/mako

**Comment by josh4trunks** [comment]
k, no problem. Thanks in advanced for looking

**Comment by josh4trunks** [comment]
@miigotu I figured out the saving issue and fixed it.
Tell me what to do to get this merged. I can reapply the changes when master/develop is ready.

**Comment by miigotu** [comment]
@josh4trunks You can rebase to develop and PR to develop now If you want. All of the work I am doing is in a separate branch.

**Comment by josh4trunks** [comment]
great, I'll work on that soon
