### ISSUE TITLE
Post Processing fails to run, must be called manually

### ISSUE THREAD

**Issue by AnalogJ** [SiCKRAGETV/sickrage-issues#803]
I have my post processsing set to copy, not move. I have about 6TB of media in a folder that sickrage is watching, and for some reason when new shows are downloaded, sickrage does not automatically detect them. Instead I must manually kick off a post process job. 

Do you think the issue is due to the number of files in the watch folder?  or does it have something to do with the fact that I'm using a kind of symlink (my watch folder is actually a symlink to a directory on a greyhole drive)

**Comment by fernandog** [comment]
follow guidelines:
https://github.com/SiCKRAGETV/sickrage-issues
