### ISSUE TITLE
Application update check not working

### ISSUE THREAD

**Issue by djack42** [SiCKRAGETV/sickrage-issues#805]
SR Version:	BRANCH: (develop) / COMMIT: (35ff96e54cb9c4efc7c6d204fc8bdc1ca58ec04e) 
SR Arguments:	['-q', '--daemon', '--nolaunch', '--datadir=/opt/sickbeard']
Python Version:	2.7.1 (r271:86832, Feb 20 2015, 08:10:01) [GCC 4.8.3 20140401 (prerelease)]
Os : geexbox armv7

The update check fail to detect new commits (at this time : 583da987e4309ce009374b10e76fbf1fb1fada78)
In general configuration > advance settings > github, the branch combobox become empty (no list or selection), but in the config file, i have everything set properly (see below).
I recently reinstalled everything, importing my settings and database (the import was not working properly btw, i'll try again and sunmit an issue...).

[General]
git_autoissues = 0
git_username = djack42
git_password = *****
git_reset = 0
branch = develop
git_remote = origin
git_remote_url = https://github.com/SiCKRAGETV/SickRage.git
cur_commit_hash = 35ff96e54cb9c4efc7c6d204fc8bdc1ca58ec04e
cur_commit_branch = develop

**Comment by abeloin** [comment]
Please provide a log from sickrage.log

**Comment by djack42** [comment]
2015-03-01 20:56:56 INFO     Thread-50 :: Version checking is disabled, not checking for the newest version

But my config says otherwise

**Comment by abeloin** [comment]
Please ensure version_notify is 1(you can change it in the ui-->config->general->updates)

**Comment by djack42** [comment]
Config file :
version_notify = 1
auto_update = 0
notify_on_update = 1

Everything in the ipdate section of the gui is displayed accordingly.
Trying unset then set again doens't repair the github combobox, another manual check update did the same, nothing. a reboot isn't good either.

**Comment by djack42** [comment]
It's not the first time i have this problem since i reinstalled.
I installed from an outdated version (the package is old) then i did a manual update and gone to develop branch. I'm not sure what version it was but i can look into it if necessary.
Maybe the problem is due to the initial update, something missing.

**Comment by abeloin** [comment]
Is there's a .git folder in Sickrage folder? Have you tried restarting sickrage?

**Comment by djack42** [comment]
Restarting from the menu is not working automaticaly, the app is shutmdown but not restarting, i must start the service again manualy.
And then, the update notification is there. The github combo is filled.
But it's not the first time and the problem will occur again soon.

**Comment by abeloin** [comment]
For the restart a patch was pushed yesterday in develop.
Has for the dropdown list, I think it's because sickrage unable to connect to github at startup which result in the github object being non-disponible. I'll add a log line so it's easier to see.

**Comment by djack42** [comment]
Ok, i will update and close the issue in a few days if i can't reporduce
Thx

**Comment by abeloin** [comment]
Try applying this PR, https://github.com/SiCKRAGETV/SickRage/pull/1443 then look in the log for a warning containing `Unable to setup github properly, github will not be available. Error:`

**Comment by djack42** [comment]
It is actually possible that the network is not yet available when the sickrage service is starting, i''ll try a server reboot.

**Comment by djack42** [comment]
Ok, i can try to apply the pr cause i have no git binary installed on my server and can't install one.
But i tried a reboot and it happened again. The case is not occuring on a sickrage restart. So i guess you are probably right.
The network is not yet up when the service starts.
Sickrage should probably wait at init for the network to go live (w/ timeout obviously).

**Comment by abeloin** [comment]
It's the job of the init script you use to start sickrage to do that.

**Comment by abeloin** [comment]
geebox use what as init?

**Comment by abeloin** [comment]
opkg is the package manager for geebox:
```
opkg update
opkg list
opkg install git
```

**Comment by djack42** [comment]
Systemd, it is set with target multi-user for sickrage. But i noticed some network issues after target network.

Opkg for geexbox has no git package, this is a very limited os for media center

**Comment by abeloin** [comment]
If that doesn't work, replace sickbeard/__init__.py by the content of this file https://raw.githubusercontent.com/abeloin/SickRage/patch-gh_log/sickbeard/__init__.py

**Comment by abeloin** [comment]
Do you use `network-online.target` or `network.target`? You should use the former and not the later.

**Comment by djack42** [comment]
If i do that (network-online.target), my server wont start if there is no network online and that would be a problem.
The geexbox systemd setup is not that good, sickrage is wanted by the multi-user target.
And the network manager is changed when xbmc is started.
Anyway, i'd prefer avoid modifying those files as i'm not sure to do it properly.
I'll go with a manual restart of sickrage i guess until the problem is corrected on the geexbox side.
I will submit an issue and let them fix it properly.

The warning is in my log :
1970-01-01 01:00:11 WARNING  MAIN :: Unable to setup github properly, github will not be available. Error: error 4 : non-recoverable failure in name resolution.

**Comment by abeloin** [comment]
Why would it prevent your server to start when the target is specified it sickrage unit file?

Anyway it's your call, but you should at least change multi-user to network.

Here my config to give you an idea:
```
[Unit]
Description=SickRage Daemon

[Service]
User=sickrage
Group=media

Type=forking
GuessMainPID=no
ExecStart=/usr/bin/python /opt/SR/SickBeard.py -q --daemon --nolaunch --datadir=/opt/SR

[Install]
WantedBy=network-online.target
```
