### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/mnt/Downloads/done/deluge/Brooklyn.Nine-Nine.S02E17.720p.HDTV.X264-DIMENSION/Brooklyn.Nine-Nine.S02E17.720p.HDTV.X264-DIMENSION.mkv'

### ISSUE THREAD

**Issue by abeloin** [SiCKRAGETV/sickrage-issues#807]
### INFO
Python Version: **2.7.5 (default, Nov  3 2014, 14:26:24) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-7)]**
Operating System: **Linux-3.17.8-200.fc20.x86_64-x86_64-with-fedora-20-Heisenbug**
Branch: **production-stage**
Commit: SiCKRAGETV/SickRage@2baf79dc76cf78552bd192b7cf3c3b4a9fc97400
### ERROR
```
POSTPROCESSER :: Unable to move file /mnt/Downloads/done/deluge/Brooklyn.Nine-Nine.S02E17.720p.HDTV.X264-DIMENSION/Brooklyn.Nine-Nine.S02E17.720p.HDTV.X264-DIMENSION.mkv to /mnt/Media/TVSeries/Brooklyn Nine-Nine/Season 2/Brooklyn Nine-Nine.S02E17.Boyle-Linetti Wedding.mkv: [Errno 2] No such file or directory: '/mnt/Downloads/done/deluge/Brooklyn.Nine-Nine.S02E17.720p.HDTV.X264-DIMENSION/Brooklyn.Nine-Nine.S02E17.720p.HDTV.X264-DIMENSION.mkv'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
From rar archive that is incomplete. Sickrage think the rar extracted successfully.

**Comment by TagForce** [comment]
@abeloin 
Wouldn't adding the following to processTV line 362 (right before return unpacked_files) keep SR from throwing this error?

```
    for unpacked in unpacked_files:
        if not os.path.isfile(os.path.join(path, unpacked)):
            unpacked_files.remove(unpacked);
```

**Comment by fernandog** [comment]
Isnt possible to get unrar status after unpack? Or error codes?

**Comment by TagForce** [comment]
the unrar implementation doesn't supply a status other than Incorrect Password or Failed Unrar archive if anything really bad happens that would raise an exception. If it fails to unRar a file for any less serious error it will simply pass an empty filename back. Unfortunately, SR uses the info_list extracted from the RAR header to fill the unpacked_files variable. If any file fails to extract and doesn't raise an exception, it will still be added to unpacked_files.

My check simply runs through all the unpacked files it THINKS it extracted, and checks if they really exist (and thus WERE extracted), if not, it will remove it from the list of files it extracted.

**Comment by abeloin** [comment]
I forget to add this:
https://sickrage.tv/forums/forum/help-support/bug-issue-reports/9570-unpack-fails-to-detect-corrupt-or-missing-rar-files-from-split-archives

**Comment by TagForce** [comment]
Or that. I don't like messing with 3rd party libraries. Makes updating them less straightforward.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1451
