### ISSUE TITLE
[Feature Request] Add demonoid and bitsnoop

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#81]
<a href="https://github.com/miigotu"><img src="https://avatars.githubusercontent.com/u/390379?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [miigotu](https://github.com/miigotu)**
_Friday Dec 12, 2014 at 14:09 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/1100 (0 comment(s))_

----

Please add these two providers. If you dont have the time I will take a crack at them in twoo weeks or so. I'd also work on the private ones but I need invites to some.

https://bitsnoop.unblocked.pw/info/api.html
also has an rss search:
http://bitsnoop.com/search/video/dexter/c/d/1/?fmt=rss
supports advanced search:
http://bitsnoop.com/search/video/this+that+exact_string+has_this+OR+has_that+OR+has_other+-unwanted_word/c/d/1/?fmt=rss
use /s/d/1 for sort by seeders/decending, the /1 is page number. 
/a/d/1 age
/c/d/1 rating/health
/z/d/1 size

http://www.demonoid.pw/api.php

**Comment by Thraxis** [comment]
@miigotu Found this earlier today: https://github.com/medariox/Sick-Beard/commit/83b572cbf137b62cbdccc9c3682b342ba7442ddf

**Comment by miigotu** [comment]
@Thraxis thanks, might be awhile til I get around to it xD, but I noticed that guy also added the demonoid.py provider to the sickbeard/ dir also by accident.

**Comment by matigonkas** [comment]
Really looking forword for Bitsnoop ,any news on it?

**Comment by miigotu** [comment]
No time lately to work at this, been spending too much time trying to get ssl working for qnap users. Supposed to be qnap's job but w/e lol.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
