### ISSUE TITLE
[APP SUBMITTED]: invalid literal for int() with base 10: '0.1'

### ISSUE THREAD

**Issue by ByronTudhope** [SiCKRAGETV/sickrage-issues#811]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2]**
Operating System: **Linux-3.13.0-43-generic-x86_64-with-Ubuntu-14.04-trusty**
Branch: **master**
Commit: SiCKRAGETV/SickRage@2d8aad80cdfb8983832206af445039de0decded9
Link to Log: https://gist.github.com/d30c0e2fb72e7ec2592a
### ERROR
```
Thread-36 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/byron/.sickrage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/home/byron/.sickrage/sickbeard/webserve.py", line 4365, in saveProviders
    sickbeard.save_config()
  File "/home/byron/.sickrage/sickbeard/__init__.py", line 1679, in save_config
    new_config['TORRENT']['torrent_seed_time'] = int(TORRENT_SEED_TIME)
ValueError: invalid literal for int() with base 10: '0.1'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@ByronTudhope how a seed time of 0.1 would work?  your torrent download accepts it?
