### ISSUE TITLE
API with non-english airs field (weekday name)

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#813]
API with non-english airdate / airs field.
Today it's show in non-english and it's not compatible with third party apps
the intention is only change the API, not UI (coming episodes page)

@Hellowlol, is this a problem for you in HTPC-Manager ? any thoughts?

**Comment by Hellowlol** [comment]
Im not really sure what you what you talking about to be honest? Do mean that the show airtime i based on the users timezone and not the networks?

**Comment by fernandog** [comment]
{
                "airdate": "2015-02-16", 
                "airs": "segunda 12:00 ",

Segunda = monday

I ask you because you use a lot API, dont you?

**Comment by fernandog** [comment]
Not timezone but weekday name

**Comment by Hellowlol** [comment]
Yes, i use the api alot :) Ah, honestly i havnt noticed. Most of my shows are English. Does this happen even if you set the lang to english while adding the show? If thats the case i would prefer english. On a side note, i would be nice if there was a addtitional field with airtime_epoch: 12312312313 so it could be parsed manually from third party aps

**Comment by fernandog** [comment]
All my shows are english. But my locale is pt-br.utf-8

Third party apps (nzb360) says we have to change the code. No then.

**Comment by fernandog** [comment]
The airtime is ok. Need to change the title. Its the airs (weekday) the problem

**Comment by Hellowlol** [comment]
yeah, but we add a airtime from epoch nzb360 can parse this however they want

**Comment by abeloin** [comment]
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/webapi.py#L794

**Comment by fernandog** [comment]
dateFormat = "%Y-%m-%d"

ep['airdate'] = sbdatetime.sbdatetime.sbfdate(dtEpisodeAirs, d_preset=dateFormat

I think its not there

**Comment by abeloin** [comment]
L788: ep['airs'] = sbdatetime.sbdatetime.sbftime(dtEpisodeAirs, t_preset=timeFormat).lstrip('0').replace(' 0',
                                                                                                               ' ')

**Comment by abeloin** [comment]
For some reason L133 in sbdatetime.py is not working in your system:
locale.setlocale(locale.LC_TIME, 'en_US')

**Comment by abeloin** [comment]
But why output the time in such format? We should output using ISO-8601:
date: YYYY-MM-DD
time: hh:mm
timezone: +0:00
day: N (integer)

this way it is easy to parse for computer

**Comment by Hellowlol** [comment]
What about adding airs_utc: "Mon, 2 Mar 2015 15:33:02 UTC " ?

**Comment by abeloin** [comment]
Yes but no English at all.
airs_utc = "2015-03-02T15:33:02.00Z" <-- iso-8601
and I just realised we already have a weekday field:
"weekday": 6

**Comment by abeloin** [comment]
@fernandog Can you test this PR https://github.com/SiCKRAGETV/SickRage/pull/1447

**Comment by fernandog** [comment]
it's working
```
            {
                "airdate": "2015-03-09", 
                "airs": "Monday 9:00 PM", 
```
