### ISSUE TITLE
Last Man on Earth - all episode set to "Snatched". What happened here?

### ISSUE THREAD

**Issue by suprdave23** [SiCKRAGETV/sickrage-issues#814]
I only have a small amount of logs to provide. Hoping some light can be shed on how to prevent this anyway.

I added the new show "The last man on earth" to download. s01e01 downloaded last night. It also grabbed "The Last Man on Earth 1964 PROPER 1080p BluRay X264-AMIABLE" last night for some reason. Then when I looked at the show list, every episode was set to "Snatched".

![capture](https://cloud.githubusercontent.com/assets/11187813/6446162/acfed4b4-c0ce-11e4-86c7-594dae335da7.PNG)

Any ideas how this could have happened? How do I properly recover from this so that I can continue to get the next episodes, and prevent this from reoccurring? 

Logs:
```
2015-03-02 04:05:29 INFO     SEARCHQUEUE-BACKLOG-281622 :: [KickAssTorrents] :: Performing episode search for The Last Man on Earth
2015-03-02 04:05:29 DEBUG    SEARCHQUEUE-BACKLOG-281622 :: [KickAssTorrents] :: Search string: https://kickass.to/usearch/The.Last.Man.on.Earth+S01E02%7C1x02+category%3Atv/?field=seeders&sorder=desc&rss=1
2015-03-02 04:05:29 INFO     SEARCHQUEUE-BACKLOG-281622 :: [ThePirateBay] :: Performing episode search for The Last Man on Earth
2015-03-02 04:05:29 DEBUG    SEARCHQUEUE-BACKLOG-281622 :: [ThePirateBay] :: Search string: https://thepiratebay.se/search/The.Last.Man.on.Earth%20S01E02%7C1x02%20/0/7/200
2015-03-02 04:05:32 INFO     SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Performing episode search for The Last Man on Earth
2015-03-02 04:05:32 DEBUG    SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Search string: https://oldpiratebay.org/search.php?q=The.Last.Man.on.Earth%20S01E02%7C1x02%20&Torrent_sort=seeders.desc
2015-03-02 04:05:38 DEBUG    SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Using ALL regexes
2015-03-02 04:05:38 DEBUG    SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Converted parsed result The-Last-Man-on-Earth-1964-1080p-BrRip-x264-YIFY into The-Last-Man-on-Earth -  [ABS: [196]] [ANIME VER: 1] [ABD: False] [ANIME: True] [whichReg: ['anime_bare']]
2015-03-02 04:05:38 DEBUG    SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Parsed The-Last-Man-on-Earth-1964-1080p-BrRip-x264-YIFY into The-Last-Man-on-Earth -  [ABS: [196]] [ANIME VER: 1] [ABD: False] [ANIME: True] [whichReg: ['anime_bare']]
2015-03-02 04:05:38 DEBUG    SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Found result The-Last-Man-on-Earth-1964-1080p-BrRip-x264-YIFY at magnet:?xt=urn:btih:14b7f833d496fd7761be92adf2ba1d0231e39dd8&dn=The+Last+Man+on+Earth+(1964)+1080p+BrRip+x264+-+YIFY&xl=1323080195&dl=1323080195

```

**Comment by fernandog** [comment]
@suprdave23 can you send a print of this show folder?  we still need FULL logs and everything else asked here: https://github.com/SiCKRAGETV/sickrage-issues/

**Comment by suprdave23** [comment]
I am running latest dev branch, just updated. 

I'm able to consistently reproduce the results. The buffer is too much for me to be able to grab all of it from the command window, but I see what the issue is, it thinks the movie is a full season and processes it accordingly:

11:48:53 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Using ALL regexes
11:48:53 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Using cached parse result for: The-Last-Man-on-Earth-1964-Ubaldo-Ragona-Extras
11:48:53 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Found result The-Last-Man-on-Earth-1964-Ubaldo-Ragona-Extras at magnet:?xt=urn:btih:4326861ac5c42fa8dc86f67846c857fd2f71062f&dn=The+Last+Man+on+Earth+(1964)+Ubaldo+Ragona+[+Extras]&xl=917655552&dl=917655552
11:48:53 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Separating full season result to check for later
11:48:53 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Using ALL regexes
11:48:53 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Unable to parse the filename The-Last-Man-on-Earth-Deliverance into a valid show
11:48:53 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Using ALL regexes
11:48:53 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Unable to parse the filename The-Last-Mans-on-Earth-2015-HDRip-XviD-AC3-EVO into a valid show
11:48:54 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Using ALL regexes
11:48:54 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Unable to parse the filename The-Last-Mans-on-Earth-2015-HDRip-XviD-AC3-EVO into a valid show
11:48:54 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Using ALL regexes
11:48:54 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Unable to parse the filename The-Last-Mans-on-Earth-2015-HDRip-XviD-AC3-EVO into a valid show
11:48:54 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Using ALL regexes
11:48:54 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Unable to parse the filename The-Last-Girlfriend-on-Earth-And-Other-Love-Stories-Simon-Rich-AZW3-EPUB-MOBI-01001001 into a valid show
11:48:54 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Using ALL regexes
11:48:54 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Unable to parse the filename The-Last-Girlfriend-on-Earth-pdf into a valid show
11:48:54 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Using ALL regexes
11:48:54 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Unable to parse the filename The-last-man-on-planet-Earth-avi into a valid show
11:48:54 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Using ALL regexes
11:48:54 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Unable to parse the filename The-Last-Man-On-Planet-Earth-1999-mp4 into a valid show
11:48:54 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Using ALL regexes
11:48:54 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Unable to parse the filename MT-Music-Temple-Marilyn-Manson-The-Last-Tour-on-Earth-UK-Bonus-CD into a valid show
11:48:54 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Using ALL regexes
11:48:54 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Unable to parse the filename Y-The-Last-Man-Book-One-2014-Digital-Monafekk-Empire-cb into a valid show
11:48:55 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Using ALL regexes
11:48:55 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Unable to parse the filename Man-on-Earth-Climate-Change-Through-the-Ages-2009-Part-1 into a valid show
11:48:55 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Using ALL regexes
11:48:55 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Unable to parse the filename Noah-amp-the-Whale-Last-Night-On-Earth-MP3-2011 into a valid show
11:48:55 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Using ALL regexes
11:48:55 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Unable to parse the filename The-Twilight-Zone-DVDR-PAL-Season-1-disc-5 into a valid show
11:48:55 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Using ALL regexes
11:48:55 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Unable to parse the filename The-Man-From-Earth-2007-1080p-x264-THUGLiNE into a valid show
11:48:55 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Using ALL regexes
11:48:55 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Using cached parse result for: The-Last-Man-On-earth-1964-1080p-mp4
11:48:55 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Found result The-Last-Man-On-earth-1964-1080p-mp4 at magnet:?xt=urn:btih:0c02a7ee35af73c84b55ec3006506c381b915b3e&dn=The+Last+Man+On+earth+-+1964+1080p.mp4&xl=2719994464&dl=2719994464&tr=udp://open.demonii.com:1337/announce&tr=udp://tra
cker.publicbt.com:80/announce&tr=udp://tracker.openbittorrent.com:80/announce&tr=udp://tracker.istole.it:80/announce
11:48:55 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Separating full season result to check for later
11:48:55 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Using ALL regexes
11:48:55 DEBUG::SEARCHQUEUE-BACKLOG-281622 :: [OldPirateBay] :: Unable to parse the filename The-Last-man-on-earth-Xvid-SER into a valid show


Is this expected? Is there a way of telling it to ignore season packs? I am also able to prevent this by making "1964" as an ignored word for the show.

**Comment by fernandog** [comment]
@suprdave23 SR thinks the movie file is a season pack but it shouldn't.

@TagForce is that it?

**Comment by TagForce** [comment]
@suprdave23 @fernandog Yes. I think so. It happens when shows and movies have the same name. Especially when you have Absolute numbering turned on, since it will match the year to an episode or season.
Try to add movie releasegroups to the ignore list. There's lists of them available on the web

**Comment by suprdave23** [comment]
@TagForce Yeah, I just put "1964" in the ignore list. Might be worth including that as a default for future installs for this particular show, I see no reason why that string would be in any of the TV show releases.
