### ISSUE TITLE
[APP SUBMITTED]: HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out. (read timeout=30)

### ISSUE THREAD

**Issue by mcmikev** [SiCKRAGETV/sickrage-issues#815]
### INFO
Python Version: **2.7.8 (default, Dec 12 2014, 22:58:35) 
[GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@68cd0fa18e3ae75a368728aeaaae7913caf13db4
Link to Log: https://gist.github.com/c82812b0e1425a86785e
### ERROR
```
Thread-226 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 257, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1511, in deleteShow
    sickbeard.traktCheckerScheduler.action.removeShowFromTraktLibrary(showObj)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/traktChecker.py", line 106, in removeShowFromTraktLibrary
    self.trakt_api.traktRequest("sync/collection/remove", data, method='POST')
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/trakt/trakt.py", line 76, in traktRequest
    raise traktException(e)
traktException: HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out. (read timeout=30)

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@mcmikev increase trakt timeout

**Comment by fernandog** [comment]
@abeloin strange it didn't catch the exception:

https://github.com/SiCKRAGETV/SickRage/pull/1330

**Comment by mcmikev** [comment]
@fernandog I have increaed the timeout from 30 to 120. Will see if this fixes my issue.

Thanks

**Comment by fernandog** [comment]
tra

**Comment by abeloin** [comment]
@fernandog it's not the same thing. It the traceback from webserve.py#L253

**Comment by fernandog** [comment]
@abeloin t

Should we change to
```
 logger.log('Failed doing webui callback: %s' % repr(e), logger.ERROR)
```

to show only this:
"HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out."
