### ISSUE TITLE
Rescan is not changing any status

### ISSUE THREAD

**Issue by Alexwijn** [SiCKRAGETV/sickrage-issues#816]
I'm trying to rescan an entire TV Show because I accidentally set everything to archive but not all episodes should be. When the rescan is complete no status has been changed. I try to manually change the status to ignored or unknown and then rescan but nothing happened either.

How can I let sickrage scan the episodes and update the status without reimporting the TV Show because I do not want to download the missing seasons.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues

**Comment by Alexwijn** [comment]
This is the logs when I started attempting to rescan untill now: http://pastebin.com/6M3Wksxm

**Comment by fernandog** [comment]
how hard is to read the page.??

SUBMITTING A BUG/ISSUE TICKET
(DO NOT POST ANYTHING THAT CONTAINS YOUR LOGIN INFORMATION OR API KEY)
Please include the following when opening a new ticket:
Branch
Commit hash
Your operating system and python version
What you did
What happened
What you expected
Link to a copy/paste of your logfile with clear debug info of the error on PASTEBIN

**Comment by Alexwijn** [comment]
Branch: DEVELOP
Commit hash: 68cd0fa18e3ae75a368728aeaaae7913caf13db4
Your operating system: RaspBian (Hardware: Raspberry B)
Python version: 2.7.3

**Comment by fernandog** [comment]
there's already that. But for ERROR messages only
auto submit issue. check config. must enter git user/pass

**Comment by Alexwijn** [comment]
Exacly. For ERROR messages only. I'm referring to non-errors like this issue.

**Comment by fernandog** [comment]
did you tried remove the show WITHOUT deleting data and re-add ?

**Comment by Alexwijn** [comment]
Not yet, but I wanted to prevent that to safe time and trouble if it starts
to download everything again.
Op 2 mrt. 2015 21:37 schreef "Fernando" <notifications@github.com>:

**Comment by fernandog** [comment]
it won't start download everything again IF all files are still in the folder

**Comment by Alexwijn** [comment]
I do not have seasons, that's why. There are 7 seasons and I only got the
last 2 seasons.
Op 2 mrt. 2015 21:58 schreef "Fernando" <notifications@github.com>:

**Comment by fernandog** [comment]
re-add the show, the existing episodes will be marked as downloaded.
The missing episodes will depend on the selected status while adding the tv-show

**Comment by Alexwijn** [comment]
Alright, I guess there is no other way.
Op 2 mrt. 2015 22:01 schreef "Fernando" <notifications@github.com>:
