### ISSUE TITLE
[APP SUBMITTED]: 'season'

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#817]
### INFO
Python Version: **2.7.8 (default, Oct 20 2014, 15:05:29) 
[GCC 4.9.1]**
Operating System: **Linux-3.16.0-30-generic-i686-with-Ubuntu-14.10-utopic**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@68cd0fa18e3ae75a368728aeaaae7913caf13db4
Link to Log: https://gist.github.com/8e1ea019b9dccd9fff93
### ERROR
```
SHOWQUEUE-ADD :: Unable to find show ID:46444 on Indexer: TVRage
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by matigonkas** [comment]
I got the following error as a notification "Unable to look up the show in /media/ssd/Shows/Hitler the Junkie on TVRage using ID 46444, not using the NFO. Delete .nfo and try adding manually again." when i tryed adding the show "Hitler the Junkie" http://www.tvrage.com/shows/id-46444

**Comment by fernandog** [comment]
probably a timeout issue. did you try again?

**Comment by fernandog** [comment]
@matigonkas seems you didn't had internet that time: 

```
[Errno -2] Name or service not known>
```

**Comment by matigonkas** [comment]
Yes tryed it again, happened the same thing again :/

**Comment by fernandog** [comment]
can you access rarbg in browser? browser uses the same internet from SR?

**Comment by matigonkas** [comment]
Yes i can acess rarbg from the browser where SR is ,but why rarbg would influese the adding of the show? Also it seems to only happen to that specific show ( could you try adding it yourself ? )

**Comment by fernandog** [comment]
I saw another error in your log

**Comment by fernandog** [comment]
@matigonkas if you check TVRAGE there's no information about any episodes.

**Comment by matigonkas** [comment]
@fernandog I Just went ahead and pruposed a review to the TVRAGE page of that show ,so that isntead of being considered as a special episode S01E(special) its S01E01 , and its working now! Thanks:)
