### ISSUE TITLE
[Feature Request] Add support for subtitles from sous-titres.eu

### ISSUE THREAD

**Issue by seijmo** [SiCKRAGETV/sickrage-issues#819]
Hi, 

I used to use a fork of sickbeard before discovering sickrage. I love the work you do but I miss a feature from the fork I used : The support from website sous-titres.eu for french and english subtitles.

Is there any way that you can add it to sickrage?
Here is the link to the code if it helps https://github.com/sarakha63/Sick-Beard/blob/development/lib/subliminal/services/soustitreseu.py

Thanks in advance

**Comment by miigotu** [comment]
No can do. Please submit this feature request to subliminal: https://github.com/Diaoul/subliminal

We do not want to modify libraries.
