### ISSUE TITLE
Help & Info tab broke when using localhost

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#82]
<a href="https://github.com/copekyle"><img src="https://avatars.githubusercontent.com/u/10146057?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [copekyle](https://github.com/copekyle)**
_Friday Dec 12, 2014 at 16:16 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/1102 (0 comment(s))_

----

BRANCH: (develop) / COMMIT: (40b8e2d64dd9df65cc09e8b2c56f5e24d8ed098e) 

When I try to access the /config page using localhost, it redirects me back to /home.  But if I use my dynamic dns address on the local machine, I can access /config.

Here are the steps:
I type in "http://localhost:8081/config/" and I am redirected to "http://localhost:8081/home/".  If I click on the tab for "Help & Info" I'm also redirected to the home page.  I have also tried this by typing in my local IP address directly ("http://192.168.1.25:8081/config/")

If I type in "http://mynoipaddress.no-ip.biz:8081/config/" then I am taken to the Configuration Page.

**Comment by fernandog** [comment]
@copekyle still an issue? are you using web root? try develop branch.

**Comment by copekyle** [comment]
No longer an issue using the Development branch.
