### ISSUE TITLE
Daemon mode - Sickrage stops working overnight on Mac 10.8.5

### ISSUE THREAD

**Issue by chrisric** [SiCKRAGETV/sickrage-issues#821]
Hi Everyone,

I'm guessing this is something simple I am missing, I installed Sickrage on my Mac Mini 10.8.5 about a week ago and it works perfectly during the day. No issues that I can see until 3am - 4am, some process must kick off that is failing but I don't see it in the log.

My setup details:

SR Version: BRANCH: (develop) / COMMIT: (e7349b3ad2127d6b4bb1976235a2b490935c6a81) 
Python Version: 2.7.2 (default, Oct 11 2012, 20:14:37) [GCC 4.2.1 Compatible Apple Clang 4.0 (tags/Apple/clang-418.0.60)]
OS: Mac 10.8.5
Sickrage Log: http://pastebin.com/hu2StuHX

I have done a Git reset as suggested but it made no difference. The log does not update after 3am - 4am and the web gui is unresponsive too. The only way to recover is to kill the process and start it up again.

Everything work fine until whatever happens between 3am - 4am.

Thank you the help.

-Chris

**Comment by abeloin** [comment]
It's the shows refresh that start at 3 am.

I would recommend updating to the latest version of python 2.7.9 first.

**Comment by chrisric** [comment]
Thanks for reviewing. I updated python to 2.7.9 and sickrage to the latest dev release.

I will report back tomorrow.

SR Version: BRANCH: (develop) / COMMIT: (68cd0fa18e3ae75a368728aeaaae7913caf13db4)
Python Version: 2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

**Comment by chrisric** [comment]
Same issue happened overnight, I uploaded all the logs. It seems to be logging a crazy amount, maybe that's just debug.

I upgraded to latest develop release again this morning, should I keep doing that or keep with the same version until the problem is found?

What other debug options are there?

https://drive.google.com/file/d/0B8JFLK_cWhrbamM1eUZsZThMd2c/view?usp=sharing

Thanks.

-Chris

**Comment by chrisric** [comment]
I moved back to master branch, probably should have tried this first... Will share results tomorrow.

SR Version: BRANCH: (master) / COMMIT: (e8405b35d6d8fc0bc1909c18e2e528e68cdc0cde)
Python Version: 2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

**Comment by TagForce** [comment]
Can you change the time at which the show_update runs? Config General -> When to update shows.
Change that to 5 a.m and see if SR stops logging at 5 a.m instead of 3 a.m. It currently requires a restart.

**Comment by chrisric** [comment]
Same issue happened on master... I've changed the update time to 5am as suggested. Will report back tomorrow. Thanks.

SR Version: BRANCH: (master) / COMMIT: (8f631d52ffd464fb0731b6d9ee562a4a3d525a0a) 
Python Version:	2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

**Comment by fernandog** [comment]
@TagForce maybe out of memory problems? I used to have this problems with my raspberry pi.

**Comment by chrisric** [comment]
@TagForce:
Same problem and it happened at 3am again not 5am which is what I configured. (showupdate_hour = 5) Thoughts?

New logs are below, they show much the same... 
https://drive.google.com/file/d/0B8JFLK_cWhrbbzNnY1ZpLXdjZ2c/view?usp=sharing

@fernandog It's a Mac Mini with 8GB of RAM, only runs Kodi and SickRage. Most RAM i've seen it use is 5GB. I'll run a script to log memory usage tonight though. I think it unlikely the issue though.

This issue must be specific to my machine as no one else is impacted, any thoughts on further debugging? Is there a way to run SickRage and all it's sub scripts in verbose debug mode or something?

Now running:
SR Version: BRANCH: (master) / COMMIT: (495b040ffadd5386f52f343bba13dfb017a92035) 
Python Version:	2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

Thanks.

**Comment by fernandog** [comment]
both times it crashed AFTER full update. 
```
2015-03-06 03:13:14 INFO     SHOWUPDATER :: Completed full update on all shows
2015-03-06 10:28:23 INFO     MAIN :: Trying to clean cache folder /Users/admin/SickRage/cache
```

```
2015-03-07 03:30:07 INFO     SHOWUPDATER :: Completed full update on all shows
2015-03-07 10:16:22 INFO     MAIN :: Trying to clean cache folder /Users/admin/SickRage/cache
```

@chrisric how do you run SickRage?

**Comment by chrisric** [comment]
@fernandog - Thanks for taking a look.

I start SickRage as per below, I will wrap it in a script when it's stable.
/usr/local/bin//pythonw2.7 SickBeard.py -d

I noticed that the python process is hung a 100% CPU, it went to 100% CPU at 2:05am last night.

The system.log shows 1000's of Kodi DEBUG lines and errors, I will quit Kodi tonight and see if python dies again.

SR Version: BRANCH: (master) / COMMIT: (558684cca7605dc4c2c3058d1f92e13f23881bd3) 
Python Version:	2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

Thanks.

**Comment by fernandog** [comment]
Try disable subtitle search. There is an issue that it uses high cpu

Change CPU throttle to HIGH in advanced settings

What is your search frequency? Suggest you to reduce it too

**Comment by chrisric** [comment]
I don't use subtitle search, I will set CPU throttling to high and my daily search frequency is 30min. I will change daily search to 60min. Backlog search is 24hrs.

Will advise results tomorrow.

Thanks.

**Comment by chrisric** [comment]
The only thing running last night was SickRage, the 100% CPU issue started at 5:11am. This lines up with the end of SHOWUPDATER according to the log. The system log shows nothing of interest for the night.

Logs, lsof, sample:
https://drive.google.com/file/d/0B8JFLK_cWhrbVHlpNnd3Qy1lWUU/view?usp=sharing

I got a lsof and sample snapshot of the python process before I killed it, I don't know what I'm looking at. I hope someone can understand it... Maybe it will help.

Is there a way to debug the SHOWUPDATER script in more detail?

SR Version: BRANCH: (master) / COMMIT: (74e48176ebd63a89b2968f79b80c56e52e29dc24) 
Python Version:	2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

Thanks for the help.

**Comment by fernandog** [comment]
@chrisric SHOWUPDATER  ended. That debug is the last message

@TagForce do you know what is going on?

**Comment by abeloin** [comment]
@chrisric Can you try running sickrage without the -d option and use the -q option?

**Comment by chrisric** [comment]
@abeloin Sure, I will run it tonight and capture output if there is any. Thanks.

**Comment by TagForce** [comment]
@chrisric @fernandog @abeloin I did find an inconsistency with the PostProcesser class in autoPostProcesser.py, but I don't see how it can be related.
It sets self.amActive to true when it starts the run, but if there's no TV_DOWNLOAD_DIR or if TV_DOWNLOAD_DIR is not an absolute path, it will simply return and never set self.amActive to False.

As for this problem... I see nothing in the logs that can explain what is going on... CPU usage skyrockets after the show_update finishes. And the only thing I see in the latest logs is that it is doing a TRAKT something, but that doesn't show up in earlier logs.

I have no idea what causes this (and it annoys me to bits).

**Comment by fernandog** [comment]
@TagForce that amActive it's only used when auto updating. IF amActive = True, don't update. But I will add amActive false before returns

**Comment by chrisric** [comment]
I started SickRage with "-q" last night and left it to run in a terminal. I didn't check if the web gui was accessible at that time (Sorry) but the log was updating so I figured it was all good.

This morning the python process was NOT at 100% CPU, the log was still updating. The log actually rolled-over from the show updating process so we can't see anything before that process started. I'll make the logs larger so this doesn't happen again.

The web gui was NOT accessible this morning, I don't know if it should be though... It looks like SickRage is still running though as the daily search was happening.

I have uploaded the logs and the output from the terminal.

https://drive.google.com/file/d/0B8JFLK_cWhrbUzYyUDhXcjA3Wjg/view?usp=sharing

SR Version: BRANCH: (master) / COMMIT: (019a8b363d65db598d85173d457fa40aed6328fc)
Python Version:	2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

Thanks.

**Comment by fernandog** [comment]
@abeloin, so as in windows, OSX can run as a Daemon?

SickBeard.py
```
        if sys.platform == 'win32':
            help_msg += "    -d          --daemon            Running as real daemon is not supported on Windows\n"
            help_msg += "                                    On Windows, --daemon is substituted with: --quiet --nolaunch\n"
```

**Comment by abeloin** [comment]
@chrisric Can you:
* Stop sickrage
* Remove the pound sign(and on extra space) in sickbeard/logger.py#L77 in front of `logging.getLogger('tornado.access'),`
* Add these 2 other loggers:
  * `logging.getLogger('tornado.application'),`
  * `logging.getLogger('tornado.general'),`
* Save the file
* Start sickrage
* When you don't have access, send the logs.

This should help us see what is going on in tornado

**Comment by abeloin** [comment]
@fernandog I think we should disable daemon mode in OSX until it is fully tested.

**Comment by chrisric** [comment]
@abeloin All done, I can see web access is being logged now. I will report back if/when it fails. Thanks.

**Comment by fernandog** [comment]
@chrisric can you do a test for me?

please run:
```
python
import sys; sys.platform
`` 

and report back the result?

**Comment by fernandog** [comment]
@chrisric 

I think @abeloin told you here https://github.com/SiCKRAGETV/sickrage-issues/issues/821#issuecomment-78428437 to add thoses lines, and run SR in daemon mode (with -d)  so we can debug what's going on.. Is that it?

**Comment by fernandog** [comment]
merged in develop

**Comment by chrisric** [comment]
@fernandog Here you go:
```>>> import sys; sys.platform```
``` 'darwin' ```

My understanding is/was that @abeloin wanted to run the extra logging with "-q" to find out why the web server stopped responding.

I can run with "-d" later today if you want, let me know.

Thanks.

**Comment by abeloin** [comment]
@chrisric the -d option is now disable on osx with that merge

**Comment by fernandog** [comment]
@abeloin after the update, he needs to add https://github.com/SiCKRAGETV/sickrage-issues/issues/821#issuecomment-78428437 again, isn't?

**Comment by abeloin** [comment]
@fernandog I don't think he's updated is branch since yesterday as it take a day to cause the issue.
@chrisric Did you updated your branch since your message 9 hours ago?

**Comment by chrisric** [comment]
@abeloin No, I was still running the below branch last night. The web server didn't fail last night either, I will monitor for a few nights/days to confirm. Hopefully it was a one off failure/issue.

SR Version: BRANCH: (master) / COMMIT: (019a8b363d65db598d85173d457fa40aed6328fc)
Python Version:	2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

I will upgrade the the latest master branch today.

Thanks.

**Comment by abeloin** [comment]
@chrisric Don't forget to re-apply https://github.com/SiCKRAGETV/sickrage-issues/issues/821#issuecomment-78428437 if you do upgrade

**Comment by chrisric** [comment]
@abeloin All good, added logging back in.

Now running:
SR Version: BRANCH: (master) / COMMIT: (3b399f16126c2566028312ecedcbb0a0d47d3dfa) 
Python Version: 2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

FYI, "-d" still works on the above version. Maybe I misunderstood but I thought it would be disabled.

I'm running SR with "-q" though as suggested.

Thanks.

**Comment by abeloin** [comment]
@chrisric The flag is disabled internally in Sickrage program

**Comment by fernandog** [comment]
@abeloin @chrisric only in develop is disabled. he is using master.

**Comment by chrisric** [comment]
@fernandog Of course, I totally spaced the dev branch.

@abeloin Web server survived again last night, should I disable logging and see if it dies? I doubt logging would be stopping it from dying though... Seem strange to have a one off failure is all.

I plan to run SR within "screen" until "daemon" mode is fixed. I know its low/zero priority :)

@TagForce @abeloin @fernandog Thanks for all the support on this. If you need any OSX testing done in the future just let me know.

**Comment by fernandog** [comment]
@chrisric try to run as you used to AND with that change in the code abeloin asked

**Comment by chrisric** [comment]
@fernandog I set showupdater time to 5pm rather than wait over night, started SR with -d and it hung as per usual with -d option..

Web server was unresponsive and produced no logs after process went to 100% CPU.

All logs are below.
https://drive.google.com/file/d/0B8JFLK_cWhrbNWV0YzAwelFFM3c/view?usp=sharing

SR Version: BRANCH: (master) / COMMIT: (3b399f16126c2566028312ecedcbb0a0d47d3dfa)
Python Version: 2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

Thanks.

**Comment by fernandog** [comment]
@abeloin should we keep this open and try to fix daemon or close as we disabled daemon for MAC/OSX?

**Comment by abeloin** [comment]
@fernandog I don't have a mac to debug, so it's kinda difficult to debug. Maybe put it as a feature request? If not then closing for the moment
