### ISSUE TITLE
Numbers in Configure Custom Newznab Providers

### ISSUE THREAD

**Issue by richmobile** [SiCKRAGETV/sickrage-issues#822]
Having numbers in provider name causes token error in searches.
This was fixed in sickbeard.
http://i.imgur.com/4N7bmXf.png

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues

**Comment by richmobile** [comment]
Then why do other users have this issue? I run 6box and have used teamviewer to walk someone through the error, and duplicated it on my end. having the provider name set to '6box'  (https://6box.me/) gets the favicon to show up, but rss token errors on searching. I dont know what they did to fix it.

**Comment by thezoggy** [comment]
they dont have the code fix to handle if a provider starts with a number. yes they are based off sb code and updated.. but really old sb code. hence they dont have a lot of fixes that is in midget's repo. also with all their changes.. they have introduced plenty of their own bugs.

**Comment by thezoggy** [comment]
fix from 2013 - https://github.com/midgetspy/Sick-Beard/commit/57c7c74baab1975ca2bd18005ddb4a13d8efa6ae

**Comment by richmobile** [comment]
Hey thanks zoggy.

**Comment by fernandog** [comment]
I said the code from the old TPB branch

**Comment by fernandog** [comment]
Will check this
