### ISSUE TITLE
[Feature Request] Allow download of episodes with missing airdate

### ISSUE THREAD

**Issue by Cancerman** [SiCKRAGETV/sickrage-issues#828]
There are a lot of shows, particularly documentaries, that are missing the airdates on thetvdb.com. Sickrage seems to default this airdate to "Never." The episodes aren't being counted and displayed properly when looking at the downloads column on the show list page. Examples attached.

![airdate1 - copy](https://cloud.githubusercontent.com/assets/10470171/6459209/cb9def56-c149-11e4-8870-9e660783b85e.jpg)
![airdate2 - copy](https://cloud.githubusercontent.com/assets/10470171/6459210/cb9f595e-c149-11e4-9877-de023b5284b8.jpg)

BRANCH: (master) / COMMIT: (2d8aad80cdfb8983832206af445039de0decded9) 
Linux Mint 17
Python 2.7.6

**Comment by fernandog** [comment]
@Cancerman 

does your SR run 24/7 ? It updates this infos every 03:00 AM
there's a new feature that allow user to change the hours to update so user don't need to keep SR overnight

**Comment by Cancerman** [comment]
SR runs 24/7. Without looking at code, it appears that SR isn't properly handling a null airdate that it receives from theTVDB.com. This only happens when theTVDB indexer does not have information for when an episode originally aired. See the link below.

Situation Critical: 
http://www.thetvdb.com/?tab=seasonall&id=84046&lid=7

**Comment by fernandog** [comment]
@Cancerman without any airdate SR should block add the show, don't you think?

**Comment by Cancerman** [comment]
The show exists and I have all of the episodes. However, no one filled in the airdate information on theTVDB indexer. SR wrongly assumes the episode never aired and does not count it. 

What SR should do is recognize I have the file already. If it matches the file I have but cannot find the original airdate, then it should set the airdate to unknown instead of never. It should also display that I have 13 of 13 episodes when looking at the show list page. Currently the show list page displays a progress bar with ? when it should say 13/13.

**Comment by fernandog** [comment]
did you tried do a refresh on that show?

**Comment by Cancerman** [comment]
I just tried again after the update. Still has a "?" progress bar on the show list. This isn't show specific either, I have at least 30 different series that display incorrectly on the show list page.

**Comment by fernandog** [comment]
check other series, see if they have airdates.
we don't have any issues about ? progress bar

**Comment by Cancerman** [comment]
The airdate for the shows i'm having problems with show up as a 1 in the database. 

Here is the bug:
gui/slick/interfaces/default/home.tmpl
code block lines 25-33


#set $sql_statement += '(SELECT COUNT(*) FROM tv_episodes WHERE showid=tv_eps.showid AND season > 0 AND episode > 0 AND airdate > 1 AND status IN ' + $status_quality + ') AS ep_snatched, '

#set $sql_statement += '(SELECT COUNT(*) FROM tv_episodes WHERE showid=tv_eps.showid AND season > 0 AND episode > 0 AND airdate > 1 AND status IN ' + $status_download + ') AS ep_downloaded, '

**Comment by fernandog** [comment]
Bug or by design? If you remove airdate> 1 how it shows in UI? What about other shows?

**Comment by abeloin** [comment]
It's by design, because you don't usually include what will be aired in the future(assumed with no airdate). Here it's bit us in the rear because these shows aren't properly filled in the tvdb.

**Comment by fernandog** [comment]
so there's nothing we can do =(

**Comment by Cancerman** [comment]
It makes sense in the ep_snatched sql as an extra way to filter out potential oddities. the ep_downloaded sql and the sql that grabs the total are the problem. For example: If the episode is downloaded and in my collection...why do we care what the airdate is set to? 

I'll try to work on this when I have some free time.

**Comment by fernandog** [comment]
@Cancerman I think I agree with you

the "airdate > 1" can be removed from ep_downloaded - the episode could be downloaded in another way or manually put in the folder
```
#set $sql_statement += '(SELECT COUNT(*) FROM tv_episodes WHERE showid=tv_eps.showid AND season > 0 AND episode > 0 AND airdate > 1 AND status IN ' + $status_download + ') AS ep_downloaded, '
```

try remove and see what happens

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
