### ISSUE TITLE
debug log entries with debug=0 in config.ini?

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#83]
<a href="https://github.com/perler"><img src="https://avatars.githubusercontent.com/u/623092?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [perler](https://github.com/perler)**
_Friday Dec 12, 2014 at 17:24 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/1103 (2 comment(s))_

----

platform: ubuntu 14.04
branch: master
commit: a67957d4f0aa9786d233aedc928d0d6096daaa80

is it normal, that when debug=0 is set in the config.ini I get these lines in /Logs/sickrage.log:

    2014-12-12 18:10:57 DEBUG    FINDSUBTITLES :: TITLES: [u'The Ascent of Money', u'Safe As Houses', u'1x05']                                           
    2014-12-12 18:10:57 DB       FINDSUBTITLES :: sickbeard.db: SELECT notify_list FROM tv_shows WHERE show_name = ? with args (u'The Ascent of Money',) 
    2014-12-12 18:10:57 DB       FINDSUBTITLES :: sickbeard.db: SELECT notify_list FROM tv_shows WHERE show_name = ? with args (u'Safe As Houses',)      
    2014-12-12 18:10:57 DB       FINDSUBTITLES :: sickbeard.db: SELECT notify_list FROM tv_shows WHERE show_name = ? with args (u'1x05',)                
    2014-12-12 18:10:57 DEBUG

**Comment by alaorath** [comment]
Came across this defect searching for a solution to the same.  I've double-checked my settings and added --config=/opt/sickbeard/config.ini to my launch script... still getting DEBUG log statements.

Makes it difficult to self-troubleshoot since all 5 log files wrap in less than 8 hours.

**Comment by abeloin** [comment]
Looking at the code config.ini only apply to console logging, file logging is always debug

**Comment by alaorath** [comment]
@abeloin, that explains it.

Alternative I came up with... I manually edited the number of (and size) of the log files generated in logger.py:

`115             rfh = logging.handlers.RotatingFileHandler(self.logFile, maxBytes=1024 * 1024 * 5, backupCount=    10, encoding='utf-8')`

Or I could merge your logger change #276 into my install... if I knew how to grab a commit.  :grinning:

**Comment by abeloin** [comment]
@alaorath Also you could change line 117 from:
```
rfh.setLevel(DEBUG)
```
to
```
rfh.setLevel(INFO if not self.debugLogging else DEBUG)
```
which would only log info in the log when debug=0

As for #276 if it's github commit append .diff to the commit url, it will give you a diff file that you can patch.

**Comment by fernandog** [comment]
@abeloin I would'nt change this otherwise the auto submit issue won't work properly.

**Comment by abeloin** [comment]
@fernandog That's a given :wink:

**Comment by fernandog** [comment]
@abeloin we are still waiting your fix for the auto submit issue =(
