### ISSUE TITLE
uTorrent: Failed Sending Torrent

### ISSUE THREAD

**Issue by blazem** [SiCKRAGETV/sickrage-issues#830]
Hi there,

I am having issues with the search sending result torrent to uTorrent.

I'm using master Branch on windows 7. Chrome browser. Python 2.7.9

Log:

2015-03-03 23:11:46 DEBUG    SEARCHQUEUE-MANUAL-272118 :: uTorrent: Exception raised when sending torrent: not a valid bencoded string
AABTFailure: not a valid bencoded string
AA    raise BTFailure("not a valid bencoded string")
AA  File "C:\Users\***\Sick-Beard-ThePirateBay\lib\bencode\bencode.py", line 68, in bdecode
AA    info = bdecode(result.content)["info"]
AA  File "C:\Users\***\Sick-Beard-ThePirateBay\sickbeard\clients\generic.py", line 151, in _get_torrent_hash
AA    result = self._get_torrent_hash(result)
AA  File "C:\Users\***\Sick-Beard-ThePirateBay\sickbeard\clients\generic.py", line 171, in sendTORRENT
AATraceback (most recent call last):
2015-03-03 23:11:46 ERROR    SEARCHQUEUE-MANUAL-272118 :: uTorrent: Failed Sending Torrent
2015-03-03 23:11:46 DEBUG    SEARCHQUEUE-MANUAL-272118 :: Calling uTorrent Client

Cheers in advance.

**Comment by fernandog** [comment]
@blazem 

Please include the following when opening a new ticket:

**Branch**
**Commit hash**
**Your operating system and python version**
What you did
What happened
What you expected
Link to a copy/paste of your logfile with clear debug info of the error on PASTEBIN

**Comment by fernandog** [comment]
@blazem also please send your utorrent version

**Comment by fernandog** [comment]
@blazem that torrent is buggy

**Comment by fernandog** [comment]
@blazem can you do a test for me?

stop SR,
edit SickRage/sickbeard/clients/generic.py
clear contents and paste this one:
https://raw.githubusercontent.com/fernandog/SickRage/remove_traceback_generic_py/sickbeard/clients/generic.py

try to reproduce the error and post the log message error please

**Comment by blazem** [comment]
Hi @fernandog I have tried what you asked and got the following:

AA. Error: not a valid bencoded string
AARelease Group: LOL
AASize: -1
AAName: Better.Call.Saul.S01E05.HDTV.x264-LOL
AAQuality: SD TV
AAEpisode: []
AAExtra Info:
2015-03-07 12:14:58 DEBUG    SEARCHQUEUE-MANUAL-273181 :: uTorrent: Exception raised when sending torrent: IPTorrents @ https://iptorrents.eu/download.php/1340041/Better.Call.Saul.S01E05.HDTV.x264-LOL.torrent
AABTFailure: not a valid bencoded string
AA    raise BTFailure("not a valid bencoded string")
AA  File "C:\Users\***\Sick-Beard-ThePirateBay\lib\bencode\bencode.py", line 68, in bdecode
AA    info = bdecode(result.content)["info"]
AA  File "C:\Users\***\Sick-Beard-ThePirateBay\sickbeard\clients\generic.py", line 151, in _get_torrent_hash
AA    result = self._get_torrent_hash(result)
AA  File "C:\Users\***\Sick-Beard-ThePirateBay\sickbeard\clients\generic.py", line 171, in sendTORRENT
AATraceback (most recent call last):
2015-03-07 12:14:58 ERROR    SEARCHQUEUE-MANUAL-273181 :: uTorrent: Failed Sending Torrent
2015-03-07 12:14:58 DEBUG    SEARCHQUEUE-MANUAL-273181 :: Calling uTorrent Client
2015-03-07 12:14:58 INFO     SEARCHQUEUE-MANUAL-273181 :: Downloading Better.Call.Saul.S01E05.HDTV.x264-LOL from IPTorrents

**Comment by blazem** [comment]
Its not for all torrents either, some others have had no issues.

**Comment by fernandog** [comment]
@Abeloin there is no INFO in content. Is that right? Buggy torrent of IPT changed something?

(result.content)["info"]

**Comment by abeloin** [comment]
Without access to the torrent file is difficult to say, but it look like the dictionary that describes the file(s) of the torrent is corrupted.

**Comment by fernandog** [comment]
it dictionary it's not in SR. I asked him to add.
@blazem can you save that torrent and put in dropbox or something equivalent?

**Comment by blazem** [comment]
Alright, I figured it out. Upon trying to manually obtain the torrent file, it turns out that my seed ratio is too poor on that provider to access the download.

I removed that site from the provider list and we are back on track.

Thanks for your help anyway guys, I hope I haven't wasted anyone's time.
Good to know for future potential similar errors.
