### ISSUE TITLE
AttributeError: 'module' object has no attribute '_create_unverified_context'

### ISSUE THREAD

**Issue by jacobwvandijk** [SiCKRAGETV/sickrage-issues#831]
I'm running windows 8.1 professional with python  2.7.6 and cheetah 2.4.4. Starting sickrage from cmd with admin privileges by typing 'python sickbeard.py' results in

File "SickRage\sickbeard.py", line 55, in <module>
    ssl._create_default_https_context = ssl._create_unverified_context
AttributeError: 'module' object has no attribute '_create_unverified_context'

I have slashed out these lines and than everything seems okay.

**Comment by TagForce** [comment]
@jacobwvandijk 
It should only run that code when you're on Python 2.7.9 or higher.
Are you sure you have no other installed python interpreter that gets run when issuing that command?
Please try it using an absolute path to the python.exe (ie: C:\Python27\bin\python.exe sickbeard.py)

**Comment by jacobwvandijk** [comment]
I made a mistake. It's python 2.7.9. There is no other python installed.

**Comment by fernandog** [comment]
@jacobwvandijk please run in CMD:

```
python --version
```

post result.

run:
```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```

post result

**Comment by TagForce** [comment]
@jacobwvandijk 
Can you change the line from 
```ssl._create_default_https_context = ssl._create_unverified_context```
to
```
if hasattr(ssl, '_create_unverified_context'): 
    ssl._create_default_https_context = ssl._create_unverified_context
```
and then check if it works?

both attributes are supposed to be in the ssl lib for Python 2.7.9, but apparently they're not always.

**Comment by jacobwvandijk** [comment]
@fernandog 
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Windows\system32>python --version
Python 2.7.9

C:\Windows\system32>import ssl ssl._create_default_https_context = ssl._create_u
nverified_context
'import' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\system32>python import ssl ssl._create_default_https_context = ssl._c
reate_unverified_context
python: can't open file 'import': [Errno 2] No such file or directory

Not sure how to run the the import command. From within python I get a 'syntax error' .

**Comment by jacobwvandijk** [comment]
Did not want to close the usue, whoops.

**Comment by fernandog** [comment]
@jacobwvandijk 

first run: import ssh
then run: ssl._create_default_https_context = ssl._create_unverified_context

**Comment by jacobwvandijk** [comment]
@TagForce 
Your suggestion works. No exceptions and Schrage is showing up 😄.

**Comment by jacobwvandijk** [comment]
@fernandog 
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

D:\Program Files\SickRage>python
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> ssl._create_default_https_context = ssl._create_unverified_context
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute '_create_unverified_context'
>>>

**Comment by fernandog** [comment]
@TagForce are you going to PR that?

**Comment by jacobwvandijk** [comment]
Thank you guys. Just walked over from sick beard today. Quite some activity around here, superb.

**Comment by abeloin** [comment]
@fernandog @TagForce 
He's getting this error because is path variable are improperly set: it missing the dlls and lib folder.

By adding hasattr, the monkeypatch isn't in place on is system so none of is search with unverified ssl will work

@jacobwvandijk See http://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows-7 on how to properly set python in path

**Comment by jacobwvandijk** [comment]
@abeloin 
Since I started this issue i'll look into it and let you guys know.

**Comment by jacobwvandijk** [comment]
@abeloin 
Since ssl seems to be part of python 2.7.6+ I do not have to add anything to the python path. But it obviously couldn't find the module. I removed all of it and set it up again et voilà it works without tweaking sickbeard.py. Thanks for your help and this community is going for quality.
