### ISSUE TITLE
[Feature Request] Add syncfile 'extensions' that are in the middle of the filename

### ISSUE THREAD

**Issue by TagForce** [SiCKRAGETV/sickrage-issues#832]
Some programs might use filename patterns that add a 'synchronisation' token in the middle of the filename (not at the end, but like somefile.syncthing.mkv).
Right now is_Syncfile only catches extensions.

**Comment by achmeed** [comment]
Hi, any status on this? I saw a pullrequest was closed due to the changes of ignore files, but these only works if filename ends with something else, not if it starts

https://github.com/SiCKRAGETV/SickRage/pull/1432

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
