### ISSUE TITLE
[Feature Request] Add a frame similar to couchpotato for manual download

### ISSUE THREAD

**Issue by exadeci** [SiCKRAGETV/sickrage-issues#833]
Lately I'm having issues with torrents that are active but not or barely not seeded it would be nice that instead of doing whatever manual search does that it displayed a list of available torrents for the episode, the same way couchpotato does for movies:
![capture d ecran 2015-03-03 a 13 40 29](https://cloud.githubusercontent.com/assets/1394130/6462769/622ae43a-c1ac-11e4-86c0-f2ec1b89a69e.png)

That would fix several manual download issues.

**Comment by abeloin** [comment]
That or set the minimum number of seeders in the provider config.

**Comment by exadeci** [comment]
One of the benefits of this element is that if the user is trying to download only in 1080p a tv show that never got a better format than dvdrip he will see it. 
A minimum number of seeders would need a behavior allowing it to fallback to lower quality of at least <parameter>, that could be for example for an episode that got out for more than n days.

It could create another suggestion that's adding a IFTT system to sickrage :smile:

**Comment by raymondtrueman** [comment]
This would be amazing. To select your download from all the downloads found on all the different providers you have configured would really make SickRage powerful especially in cases where SickRage snatches the wrong download or you want to override its choice with another release of your choice. You are no longer bound by what SickRage thinks is the best release for you

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
