### ISSUE TITLE
[Feature Request] Pause/Unpause button directly from Show page

### ISSUE THREAD

**Issue by Freakadude** [SiCKRAGETV/sickrage-issues#835]
Currently pausing and unpausing a show can be done by going through the Edit button on the individual shows subpages. Would it be possible to add a dedicated button for Pause/Unpause on each shows summary page? Its a little thing really but having to go through the Edit screen seems like an unecessary step for a quick edit function like pausing and unpausing a show.

If it can be added great if not its not the end of the world :)

**Comment by gborri** [comment]
i'd like to suggest to make it available directly from homepage....

**Comment by Thraxis** [comment]
@fernandog @abeloin @TagForce Low hanging fruit...  Would there be objections to this being added to both the home page as well as to the displayShow page?

**Comment by abeloin** [comment]
The mass edit page provide the equivalent for the home page. Also I think the home page should be considered as status page not and editing page.

As for the display show page, we could use bootstrap toggle buttons(http://getbootstrap.com/javascript/#buttons) and replace the X and check mark with toggle buttons.

**Comment by fernandog** [comment]
@abeloin I would only change PAUSE. Others needs full update to work and user can do something wrong clicking in the wrong place.

**Comment by Thraxis** [comment]
So really just the making the pause on the display show page available instead of a full stop edit.

**Comment by gborri** [comment]
@thraxis @abeloin the pause\unpause button on he page is useful to start and stop rolling download without entering on the show itself. Probabily what have @abeloin suggested could be applied also on home page. What do you think?

**Comment by fernandog** [comment]
Home page is not for editing.

**Comment by gborri** [comment]
For this purpose i think is not editing, is starting a process and is one
click less.

Giovanni
Il 12/apr/2015 18:54, "Fernando" <notifications@github.com> ha scritto:

**Comment by abeloin** [comment]
@gborri mass edit page can do that

**Comment by gborri** [comment]
@abeloin i had not find a way to do it from mass edit. how can i make it
work?

**Comment by fernandog** [comment]
Select first checkbox column and click EDIT

**Comment by gborri** [comment]
@fernandog @thraxis @abeloin the pause\unpause button on he page is useful to start and stop rolling download without entering on the show itself. Probabily what have @abeloin suggested could be applied also on home page. What do you think?

**Comment by fernandog** [comment]
Nope
