### ISSUE TITLE
Edit/add subtitles from the mass update

### ISSUE THREAD

**Issue by Hellowlol** [SiCKRAGETV/sickrage-issues#836]
Hey! It would be great if it was possible to edit/add subtitles from the mass edit page. Normally id fix simple things like this myself, but i cant wrap my head around cheetah..

**Comment by fernandog** [comment]
@Hellowlol 

can you confirm this is not an issue?

issue # 997

looks like it grey out subtitle when subtitle it's not enabled or queue to download.
Is that why you wanted? enabled/disable instead of just show if is enable/disable?

**Comment by Hellowlol** [comment]
Ill check when i get home from work.

**Comment by Hellowlol** [comment]
I want to enable/disable it from the mass edit. Right now i have to go thru 800 ish shows and manually set to subtitles to active.

**Comment by fernandog** [comment]
@Hellowlol but do you agree that if subtitle is queue to download or downloading, you won't be able to disable it? Are you sure this does not work today?! why we have a "Subtitle" column with checkbox there?

**Comment by Hellowlol** [comment]
Well it does work, but only if the subtitles is enabled.... So its kinda pointless, you can only disable stuff not enable. It belongs there are its a easy way to edit all shows, like i said before, enabling subtitles for all shows are a very tedious task.

So if subtitles is enabled, is checked, if not unchecked. It should be that simple.

**Comment by fernandog** [comment]
@Hellowlol do you accept enabling subtitles using the first column "edit" ?  that column subtitle will be renamed to "Search subtitles" - force search. 

What about a column indicating enable/disabled for subtitles? will be better to select/unselect the shows you want. What do you think?

**Comment by Hellowlol** [comment]
Honestly I didn't try the edit inside mass update. As long as i can just mark all shows, press edit, set subtile to enable and press save that's more then enough. I'm happy with current solution and I think renaming that column is wise. 

Sorry for making  fuzz about nothing.
