### ISSUE TITLE
[APP SUBMITTED]: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by nyquist10** [SiCKRAGETV/sickrage-issues#837]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) 
[GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.6**
Branch: **master**
Commit: SiCKRAGETV/SickRage@2d8aad80cdfb8983832206af445039de0decded9
### ERROR
```
CHECKVERSION :: Unable to contact github, can't check for update: gaierror(-2, 'Name or service not known')
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
not an error.  try again in a few minutes and check your internet where SR is installed
