### ISSUE TITLE
Add qbittorrent support

### ISSUE THREAD

**Issue by Jaerin** [SiCKRAGETV/sickrage-issues#838]
qbittorrent (http://www.qbittorrent.org/) is the latest micro-client without all the bloat.  Would be nice to have integrated support.  Looks like it might be similar to rTorrent

**Comment by unabatedshagie** [comment]
I'd love to be able to ditch uTorrent for qbittorrent.

**Comment by captain0bvious** [comment]
Please add qbitorrent support so I can label my tvshows for processing.

**Comment by Symbiot78** [comment]
yes please..!

**Comment by sirbishop** [comment]
this would be wonderful!  qBittorrent works on linux and windows very well and has a full feature set!

**Comment by afarazit** [comment]
Haven't used utorrent for years, please add support for the awesome qbittorrent

**Comment by elBradford** [comment]
I'd love qbittorrent as well - it's the only linux torrent client that natively supports binding to an interface adapter by adapter name (ie tun0) to make sure all torrent traffic goes over a VPN. I'd love to ditch the black hole thing, since I have to then process the files myself.

**Comment by donisewell** [comment]
I'd love to see this as well. It'd be a big help to those trying to migrate away from uTorrent.

**Comment by papampi** [comment]
+1 on this.

**Comment by Rouzax** [comment]
:+1:  on this
Especially with the new on uTorrent regarding: https://torrentfreak.com/utorrent-quietly-installs-riskware-bitcoin-miner-users-report-150306/

**Comment by fernandog** [comment]
@Jaerin @unabatedshagie @captain0bvious @Symbiot78 @sirbishop @afarazit @elBradford @donisewell @Rouzax 

merged in DEVELOP.
Any of you are using develop? we have some issues in the branch but if you want to try....feel free. Make backup.

**Comment by Jaerin** [comment]
Did you guys check the build after committing that?

D:\Programs\SickRage>SickBeard.py
Traceback (most recent call last):
  File "D:\Programs\SickRage\SickBeard.py", line 69, in <module>
    import sickbeard
  File "D:\Programs\SickRage\sickbeard\__init__.py", line 37, in <module>
    from sickbeard import providers, metadata, config, webserveInit
  File "D:\Programs\SickRage\sickbeard\providers\__init__.py", line 54, in <modu
le>
    import generic
  File "D:\Programs\SickRage\sickbeard\providers\generic.py", line 31, in <modul
e>
    from sickbeard import helpers, classes, logger, db
  File "D:\Programs\SickRage\sickbeard\helpers.py", line 57, in <module>
    from sickbeard import clients
  File "D:\Programs\SickRage\sickbeard\clients\__init__.py", line 73
    418: 'I'm a teapot',
            ^
SyntaxError: invalid syntax

**Comment by Jaerin** [comment]
Something not working with this pull

    D:\Programs\SickRage>sickbeard.py
    Traceback (most recent call last):
      File "D:\Programs\SickRage\SickBeard.py", line 69, in <module>
        import sickbeard
      File "D:\Programs\SickRage\sickbeard\__init__.py", line 37, in <module>
        from sickbeard import providers, metadata, config, webserveInit
      File "D:\Programs\SickRage\sickbeard\providers\__init__.py", line 54, in <module>
        import generic
      File "D:\Programs\SickRage\sickbeard\providers\generic.py", line 31, in <module>
        from sickbeard import helpers, classes, logger, db
      File "D:\Programs\SickRage\sickbeard\helpers.py", line 57, in <module>
        from sickbeard import clients
      File "D:\Programs\SickRage\sickbeard\clients\__init__.py", line 73
        418: 'I'm a teapot',
                ^
    SyntaxError: invalid syntax

**Comment by fernandog** [comment]
@Jaerin please update. already fixed

**Comment by Jaerin** [comment]
I'm not sure what the problem was, but I had to completely remove my previous repository entirely and clone a new one.  I tried doing a full hard reset on it and it just continued to give me the above errors.

Must have been something cached in the .git because I even wiped out and rechecked out the files under the old repository and it gave the same issues.

**Comment by fernandog** [comment]
@Jaerin maybe take some time for you to get the update. 

But is it working now?

**Comment by fernandog** [comment]
@Jaerin everything working??

**Comment by Clockyx82** [comment]
@fernandog when do you expect this to land in the stable?

**Comment by fernandog** [comment]
probaly sunday. we need to confirm qbittorrent is working. that's why I'm asking users to test it

**Comment by Jaerin** [comment]
Yes it appears to be working.  Now to get qbittorrent to add the labels to the API so we can use that and it will be perfect replacement for uTorrent.

**Comment by afarazit** [comment]
It seems to be working for me as well. Thanks @fernandog

**Comment by emzero** [comment]
When can be expected to have this merged into the master branch?

**Comment by Rouzax** [comment]
If you look three comments above you, you can see that fernandog said probably Sunday :smile:

**Comment by emzero** [comment]
Oh sorry, didn't see it. Thanks!

**Comment by papampi** [comment]
Awesome job, Thanks
it adds torrents to qbittorrent but it does not show up fetched in history and in error log I get this : 
2015-04-20 15:23:24 SEARCHQUEUE-DAILY-SEARCH :: qbittorrent: Unable to send Torrent: Return code undefined

any idea ?

**Comment by abeloin** [comment]
@papampi Can you provide the qbittorrent version you are using? This error mean qbittorent return an answer compressed in gzip but the requests library wasn't able to decompress it.

**Comment by papampi** [comment]
its 3.1.12 with ubuntu 14.04

**Comment by papampi** [comment]
seems like it has no problems on daily search torrents and that was the only error appeared.

**Comment by syrys** [comment]
Is there any update on adding labels to qbittorrent downloads?

**Comment by JustMaier** [comment]
Hey @syrys, Adding labels via the web api isn't supported in qbittorrent yet. You can voice your opinion on that here: [Feature Request](https://github.com/qbittorrent/qBittorrent/issues/44)

**Comment by Rouzax** [comment]
See https://github.com/qbittorrent/qBittorrent/pull/2558

**Comment by Rouzax** [comment]
Setting the label through the API will probably be implemented in version 3.3
See: https://github.com/qbittorrent/qBittorrent/pull/3444
