### ISSUE TITLE
FR: rename required indicator

### ISSUE THREAD

**Issue by mgaulton** [SiCKRAGETV/sickrage-issues#839]
I would like to request the option to have some sort of indicator on a show entry in the list when there are items that need renaming. OR an overall "Manage Rename Status" interface similar to manage episode status.

**Comment by TagForce** [comment]
I've been thinking about how to do this. Only feasible way I can think of is to run a daily scheduler that scans all the shows and episodes and marks them as "rename needed", which can be read by the showlist and displayShow pages.

**Comment by mgaulton** [comment]
The logic to mark then as needing rename is already there. I think
your approach would work.

**Comment by neoatomic** [comment]
Was already requested here : https://github.com/SiCKRAGETV/sickrage-issues/issues/516
