### ISSUE TITLE
[Inquiry/Request]Why don't we see file names

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#84]
<a href="https://github.com/MrsAngelD"><img src="https://avatars.githubusercontent.com/u/2045159?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [MrsAngelD](https://github.com/MrsAngelD)**
_Friday Dec 12, 2014 at 18:52 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/1104 (2 comment(s))_

----

In Sickbeard when viewing a show it shows you the filenames of each file

someshow - s01e01.mkv

however I see that this isn't the case in sickrage and I was wondering if there was a reason for this. I would really like the option to view the filenames if possible.

**Comment by abeloin** [comment]
@markheloking Fixed with pull request SiCKRAGETV/SickRage#1187 which was merge into develop.
