### ISSUE TITLE
Unknown User / Password on Sickrage

### ISSUE THREAD

**Issue by bmatulovich** [SiCKRAGETV/sickrage-issues#841]
I ran a search for this problem and scoured the internet for the answer. I am sorry if this is a repeat question somewhere. I am new to both Ubuntu and Sickrage. I say this because I need any help to be brought down to layman terms if possible.

I am not sure how this happened but when I Closed out of Sickrage then opened it back up again i was prompted to enter a username and password. When I initially set Sickrage up I did not set it to request this information. I stopped the script from the terminal and ran a config.ini (Included below) and it shows that i do not have a web user or password assigned. Am i looking in the correct location for this and how do i fix it. 

Please Help

[General]
git_autoissues = 0
git_username = ""
git_password = ""
git_reset = 0
branch = master
git_remote = origin
git_remote_url = https://github.com/SiCKRAGETV/SickRage.git
cur_commit_hash = 49ea8f5ac7841f6654509d48d72506923bc47c2a
cur_commit_branch = ""
config_version = 5
encryption_version = 0
log_dir = Logs
socket_timeout = None
web_port = 8081
web_host = 0.0.0.0
web_ipv6 = 0
web_log = 0
web_root = ""
web_username = ""
web_password = ""
play_videos = 0
localhost_ip = ""

**Comment by fernandog** [comment]
@bmatulovich clear you browser cookies for sickrage site and clear cache please

**Comment by bmatulovich** [comment]
I did these things and they did not work. Do you have any other ideas?Fernando <notifications@github.com> wrote:@bmatulovich clear you browser cookies for sickrage site and clear cache please

**Comment by abeloin** [comment]
Can you try to rename your config.ini to config.ini.bak and start sickrage again to see if it ask for a user/pass?

**Comment by bmatulovich** [comment]
I can try that but i am not certain how to change the name of a file. What is the command line for that or how would i do that in ubuntu. I am new to linux.

Thank you for your helpAlexandre Beloin <notifications@github.com> wrote:Can you try to rename your config.ini to config.ini.bak and start sickrage again to see if it ask for a user/pass?

**Comment by fernandog** [comment]
stop SR
```
mv config.ini config.bak
```

**Comment by bmatulovich** [comment]
When i use this command i get 

mv: cannot stat 'config.ini' : no such file or directory

Again i am very new to linux. Can you give me step by step instrucrions to accomplish this Fernando <notifications@github.com> wrote:stop SR

mv config.ini config.bak

**Comment by fernandog** [comment]
@bmatulovich obviously you need to enter /SickRage folder

**Comment by bmatulovich** [comment]
So i ran this :

Mv ~/.sickrage/config.ini. Sickrage/config.bak and the result is the same. Must enter user name and password. Anything else Fernando <notifications@github.com> wrote:@bmatulovich obviously you need to enter /SickRage folder

**Comment by fernandog** [comment]
stop SR
cd SickRage
mv config.ini config.bak

**Comment by TagForce** [comment]
@bmatulovich linux is very case-sensitive
Stop SR
use 'cd' to change to your sickrage folder...
use 'ls' to show the files in it. when you see config.ini in the list do
mv config.ini config.bak
if you get a permissions error add sudo in front of the command 'sudo mv config.ini config.bak'
It will ask for your password.
'ls' again to verify there's now a config.bak
start SR

**Comment by bmatulovich** [comment]
I am very sorry about this but this tells  me, 

Mv: cannot stat 'config.ini': no such file or directory
However if i put in the command
Sudo gedit ~/.sickrage/config.ini 

it pulls up the entire configuration file. About 9 pages worth.
What am i missing in your command

 mv config.ini config.bak

Fernando <notifications@github.com> wrote:stop SR
cd SickRage
mv config.ini config.bak

**Comment by abeloin** [comment]
`mv ~/.sickrage/config.ini ~/.sickrage/config.ini.bak`

**Comment by bmatulovich** [comment]
Tagforce,

I followed your instructions exact. when i put the ls in the terminal it gives me all of these files. I do not have and config.ini file in here. Does this make any sense?

autoProcessTV         gui           init.solaris11  setup.py      tornado
CHANGES.md            init.debian   init.systemd    sickbeard     updater.py
contributing.md       init.fedora   init.ubuntu     SickBeard.py
COPYING.txt           init.freebsd  lib             tests
googlecode_upload.py  init.gentoo   readme.md       TODO.txt

**Comment by bmatulovich** [comment]
O.K. So i figured out I must have 2 Sickrage and 1 file ~/.sickrage. So i changed directory to the latter. and i had a config.ini and a config.ini~ file. i changed both of these to .bak and bak~ restarted sickbeard with the same result. user name and password. I went back to the file and ran ls command and this is what is in there.
autoProcessTV         gui             readme.md         sickbeard.db.v38
cache                 init.debian     setup.py          sickbeard.db.v39
cache.db              init.fedora     sickbeard         sickbeard.db.v40
CHANGES.md            init.freebsd    sickbeard.db      sickbeard.db.v41
config.bak            init.gentoo     sickbeard.db.v32  sickbeard.db.v42
config.bak~           init.solaris11  sickbeard.db.v33  SickBeard.py
contributing.md       init.systemd    sickbeard.db.v34  tests
COPYING.txt           init.ubuntu     sickbeard.db.v35  TODO.txt
failed.db             lib             sickbeard.db.v36  tornado
googlecode_upload.py  Logs            sickbeard.db.v37  updater.py

Any other thoughts? 

Thanks to all for your assistance

**Comment by TagForce** [comment]
how do you start sickrage?
we need to make sure we're looking at the correct files

**Comment by bmatulovich** [comment]
it starts automatically but to start and stop it manually i use 
sudo service sickrage start/stop

Is this what you mean?

**Comment by abeloin** [comment]
What is your OS, and what is the command to launch sickrage in your init file

**Comment by bmatulovich** [comment]
OS is UBUNTU 

I followed an online tutorial from HTC Beginner. Here is the script i used

sudo cp ~/.sickrage/init.ubuntu /etc/init.d/sickrage
sudo chmod +x /etc/init.d/sickrage

**Comment by abeloin** [comment]
What is the content of the following folder:
`/opt/sickbeard`

**Comment by bmatulovich** [comment]
Here is the contents of that folder. The more i get into this it looks like a sloppy install. I am wondering if i should just uninstall all instances of sickrage and delete all file directories then do a new fresh clean install. What do you think? if you agree do you have a recommended install guide? 


bobm@MediaServer:~/sickrage$ cd /opt/sickrage
bobm@MediaServer:/opt/sickrage$ l
~/
autoProcessTV/
cache/
cache.db
CHANGES.md
config.ini
contributing.md
COPYING.txt
Curb.your.Enthusiasm.S06E01.PDTV.XviD-NoTV.torrent
Curb.your.Enthusiasm.S06E02.PDTV.XviD-NoTV.torrent
Curb.your.Enthusiasm.S06E03.PDTV.XviD-NoTV.torrent
Curb.your.Enthusiasm.S06E04.PDTV.XviD-NoTV.torrent
Curb.your.Enthusiasm.S06E05.PROPER.PDTV.XviD-NoTV.torrent
Curb.Your.Enthusiasm.S06E06.PDTV.XviD-XOR.torrent
Curb.your.Enthusiasm.S06E07.PROPER.PDTV.XviD.NoTV.torrent
Curb.your.Enthusiasm.S06E08.PDTV.XviD-NoTV.torrent
Curb.your.Enthusiasm.S06E09.PDTV.XviD-NoTV.torrent
Curb.your.Enthusiasm.S06E10.Repack.PDTV.XviD-NoTV.torrent
failed.db
googlecode_upload.py
gui/
init.debian*
init.fedora*
init.freebsd*
init.gentoo*
init.solaris11*
init.systemd*
init.ubuntu*
lib/
Logs/
Louie.S04E04.Elevator.Part.1.720p.WEB-DL.DD5.1.H.264-BS.[PublicHD].torrent
Louie.S04E07.HDTV.x264-LOL.[eztv].torrent
New.Girl.S04E15.The.Crawl.720p.WEB-DL.2CH.x265.HEVC-PSA.torrent
readme.md
setup.py
sickbeard/
sickbeard.db
sickbeard.db.v32
sickbeard.db.v33
sickbeard.db.v34
sickbeard.db.v35
sickbeard.db.v36
sickbeard.db.v37
sickbeard.db.v38
sickbeard.db.v39
sickbeard.db.v40
sickbeard.db.v41
sickbeard.db.v42
SickBeard.py*
tests/
The.Blacklist.S02E13.720p.HDTV.X264-DIMENSION[rarbg].torrent
The.Goldbergs.2013.S02E12.Cowboy.Country.720p.WEB-DL.2CH.x265.HEVC-PSA.torrent
TODO.txt
tornado/
True.Detective.S01E06.720p.HDTV.X264-2HD.[P2PDL].torrent
updater.py
bobm@MediaServer:/opt/sickrage$ ls
~
autoProcessTV
cache
cache.db
CHANGES.md
config.ini
contributing.md
COPYING.txt
Curb.your.Enthusiasm.S06E01.PDTV.XviD-NoTV.torrent
Curb.your.Enthusiasm.S06E02.PDTV.XviD-NoTV.torrent
Curb.your.Enthusiasm.S06E03.PDTV.XviD-NoTV.torrent
Curb.your.Enthusiasm.S06E04.PDTV.XviD-NoTV.torrent
Curb.your.Enthusiasm.S06E05.PROPER.PDTV.XviD-NoTV.torrent
Curb.Your.Enthusiasm.S06E06.PDTV.XviD-XOR.torrent
Curb.your.Enthusiasm.S06E07.PROPER.PDTV.XviD.NoTV.torrent
Curb.your.Enthusiasm.S06E08.PDTV.XviD-NoTV.torrent
Curb.your.Enthusiasm.S06E09.PDTV.XviD-NoTV.torrent
Curb.your.Enthusiasm.S06E10.Repack.PDTV.XviD-NoTV.torrent
failed.db
googlecode_upload.py
gui
init.debian
init.fedora
init.freebsd
init.gentoo
init.solaris11
init.systemd
init.ubuntu
lib
Logs
Louie.S04E04.Elevator.Part.1.720p.WEB-DL.DD5.1.H.264-BS.[PublicHD].torrent
Louie.S04E07.HDTV.x264-LOL.[eztv].torrent
New.Girl.S04E15.The.Crawl.720p.WEB-DL.2CH.x265.HEVC-PSA.torrent
readme.md
setup.py
sickbeard
sickbeard.db
sickbeard.db.v32
sickbeard.db.v33
sickbeard.db.v34
sickbeard.db.v35
sickbeard.db.v36
sickbeard.db.v37
sickbeard.db.v38
sickbeard.db.v39
sickbeard.db.v40
sickbeard.db.v41
sickbeard.db.v42
SickBeard.py
tests
The.Blacklist.S02E13.720p.HDTV.X264-DIMENSION[rarbg].torrent
The.Goldbergs.2013.S02E12.Cowboy.Country.720p.WEB-DL.2CH.x265.HEVC-PSA.torrent
TODO.txt
tornado
True.Detective.S01E06.720p.HDTV.X264-2HD.[P2PDL].torrent
updater.py
bobm@MediaServer:/opt/sickrage$ ls
~
autoProcessTV
cache
cache.db
CHANGES.md
config.ini
contributing.md
COPYING.txt
Curb.your.Enthusiasm.S06E01.PDTV.XviD-NoTV.torrent
Curb.your.Enthusiasm.S06E02.PDTV.XviD-NoTV.torrent
Curb.your.Enthusiasm.S06E03.PDTV.XviD-NoTV.torrent
Curb.your.Enthusiasm.S06E04.PDTV.XviD-NoTV.torrent
Curb.your.Enthusiasm.S06E05.PROPER.PDTV.XviD-NoTV.torrent
Curb.Your.Enthusiasm.S06E06.PDTV.XviD-XOR.torrent
Curb.your.Enthusiasm.S06E07.PROPER.PDTV.XviD.NoTV.torrent
Curb.your.Enthusiasm.S06E08.PDTV.XviD-NoTV.torrent
Curb.your.Enthusiasm.S06E09.PDTV.XviD-NoTV.torrent
Curb.your.Enthusiasm.S06E10.Repack.PDTV.XviD-NoTV.torrent
failed.db
googlecode_upload.py
gui
init.debian
init.fedora
init.freebsd
init.gentoo
init.solaris11
init.systemd
init.ubuntu
lib
Logs
Louie.S04E04.Elevator.Part.1.720p.WEB-DL.DD5.1.H.264-BS.[PublicHD].torrent
Louie.S04E07.HDTV.x264-LOL.[eztv].torrent
New.Girl.S04E15.The.Crawl.720p.WEB-DL.2CH.x265.HEVC-PSA.torrent
readme.md
setup.py
sickbeard
sickbeard.db
sickbeard.db.v32
sickbeard.db.v33
sickbeard.db.v34
sickbeard.db.v35
sickbeard.db.v36
sickbeard.db.v37
sickbeard.db.v38
sickbeard.db.v39
sickbeard.db.v40
sickbeard.db.v41
sickbeard.db.v42
SickBeard.py
tests
The.Blacklist.S02E13.720p.HDTV.X264-DIMENSION[rarbg].torrent
The.Goldbergs.2013.S02E12.Cowboy.Country.720p.WEB-DL.2CH.x265.HEVC-PSA.torrent
TODO.txt
tornado
True.Detective.S01E06.720p.HDTV.X264-2HD.[P2PDL].torrent
updater.py
bobm@MediaServer:/opt/sickrage$

**Comment by abeloin** [comment]
Open /opt/sickrage/config.ini in vi or the text editor of your choice and check the value of:
web_username = ""
web_password = ""

**Comment by bmatulovich** [comment]
I picked up on that config.ini file and checked it out. It did have user and password in that field. I'm not sure how it got there but i took it out and it opened right up. Thank you for your patience and working with me on this.

One more question. If i can be so bold. Is there an easy way for me to delete all of the other instances of sickrage files and registries that are not being used?

**Comment by abeloin** [comment]
Not really, you'll have to do it manually.

**Comment by bmatulovich** [comment]
Thanks again.
