### ISSUE TITLE
Hell's Kitchen doesn't show up on "Coming Episodes" page

### ISSUE THREAD

**Issue by suprdave23** [SiCKRAGETV/sickrage-issues#843]
Running latest dev pull from yesterday.

I just got notified that Hell's Kitchen s14e01 downloaded. I was very surprised as I did not remember seeing it on the "Coming Episodes" page. I took a look, and sure enough it did download and the air-date is correct, however it does not show anywhere on the "Coming Episodes" page while all of my other TV shows do.

Is there an option I am missing somewhere for this series to make it show up on the "Coming Episodes" page?

There is nothing in the debug logs showing any errors when I load the Coming Episodes page (or any info at all related to this page).

**Comment by fernandog** [comment]
is it paused?

**Comment by suprdave23** [comment]
@fernandog No the show status is "Continuing". 

If you add this show to your running copy does it have the same issue?

**Comment by fernandog** [comment]
Send a full screenshot of the show page please

**Comment by suprdave23** [comment]
Here you go, but I just realized that since the date has passed that the show aired, the coming episodes page isn't going to list it anymore.

Would setting the episode to "Skipped" make it show up as "missed" under Coming Episodes, and I could test it that way?

![capture1](https://cloud.githubusercontent.com/assets/11187813/6487186/4af38d2c-c255-11e4-94f4-08536e27d489.PNG)

![capture2](https://cloud.githubusercontent.com/assets/11187813/6487188/520481d4-c255-11e4-92f7-9bcc7c97dd2c.PNG)

**Comment by fernandog** [comment]
to appear at coming episodes you must set as wanted. but after that SR will start to search for it. you must be quick to open coming episodes

**Comment by suprdave23** [comment]
Thanks! I tested it and it does show up in the "list style" as missed when I do that. Must just be that tvdb/tvrage are slow at picking up when the new episodes are going to be released, and it came out as available the day the episode aired, which would explain why the Coming Episodes page did not let me know new episodes are coming out for this show.
