### ISSUE TITLE
[APP SUBMITTED]: cannot find 'logNameFilters'

### ISSUE THREAD

**Issue by paparen** [SiCKRAGETV/sickrage-issues#845]
### INFO
Python Version: **2.7.8 (default, Dec 12 2014, 21:04:21) 
[GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Branch: **master**
Commit: SiCKRAGETV/SickRage@e8405b35d6d8fc0bc1909c18e2e528e68cdc0cde
Link to Log: https://gist.github.com/4d3ed433c6788b881978
### ERROR
```
Thread-26 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 230, in async_call
    self.io_loop = IOLoop.current()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 4784, in viewlog
    sickbeard.subtitlesFinderScheduler.stop.set()
  File "/usr/local/sickbeard-custom/var/cache/cheetah/cheetah__usr_local_sickbeard_custom_var_SickBeard_gui_slick_interfaces_default_viewlogs_tmpl_1425452322_21_18494.py", line 201, in respond
    for logNameFilter in sorted(VFFSL(SL,"logNameFilters",True)): # generated from line 81, col 1
NotFound: cannot find 'logNameFilters'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by TagForce** [comment]
@paparen 
- Stop SR
- Delete all contents of the /usr/local/sickbeard-custom/var/cache/cheetah/ folder
- Start SR

It looks like it's using an outdated cached template.
It will rebuild the cache once it is deleted.

Report back if this has solved the issue. (by going to the View Logs page).

**Comment by abeloin** [comment]
@TagForce This happen because he's updating Sickrage and at the same time a request from a web page accessing the log came in using the new tmpl code hence the error.

A restart will resolve the issue.

**Comment by TagForce** [comment]
@abeloin you mean updating while SR is running?
I think he did that after the error.

**Comment by abeloin** [comment]
To get this error, you to have to old code in python running and the new code in the tmpl at the same time.

**Comment by TagForce** [comment]
@abeloin So, this is a fluke...
@paparen Restart if this is still current...
