### ISSUE TITLE
[APP SUBMITTED]: 'sqlite3.Row' object does not support item assignment

### ISSUE THREAD

**Issue by Thraxis** [SiCKRAGETV/sickrage-issues#846]
### INFO
Python Version: **2.7.3 (default, Mar 26 2013, 20:01:12) 
[GCC 4.4.4]**
Operating System: **Linux-3.9.6p-unRAID-i686-AMD_C-60_APU_with_Radeon-tm-_HD_Graphics-with-slackware-13.1.0**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@af20b6e90506c49280ca7f17eb13d1f647cf502c
### ERROR
```
TORNADO :: API :: 'sqlite3.Row' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Thraxis** [comment]
A bit more information on this..  This occurs when using my updated SickBeardConnect to (SickRageConnect) chrome plugin.

Below is the full error trace

```python
2015-03-04 00:15:54 ERROR    TORNADO :: API :: 'sqlite3.Row' object does not support item assignment
Traceback (most recent call last):
  File "/usr/local/sickrage/sickbeard/webapi.py", line 116, in get
    outDict = _call_dispatcher(args, kwargs)
  File "/usr/local/sickrage/sickbeard/webapi.py", line 186, in call_dispatcher
    curOutDict = func(curArgs, curKwargs).run()
  File "/usr/local/sickrage/sickbeard/webapi.py", line 763, in run
    ep['airs'] = str(ep['airs']).replace('am', ' AM').replace('pm', ' PM').replace('  ', ' ')
TypeError: 'sqlite3.Row' object does not support item assignment
```

**Comment by fernandog** [comment]
are you using SR modified code to make SC Works?

**Comment by fernandog** [comment]
@Thraxis check if any of your shows don't have "airs" filled

**Comment by abeloin** [comment]
@Thraxis What are the parameters in the api call?

**Comment by fernandog** [comment]
@Thraxis try to reproduce using APIbuilder

**Comment by abeloin** [comment]
Duplicate bug #211 #212

**Comment by abeloin** [comment]
Able to reproduce with:

/api/[apikey]/?cmd=future&sort=date&type=later

**Comment by abeloin** [comment]
Unable to reproduce anymore

**Comment by fernandog** [comment]
@abeloin do you have any backup?? hehehe

**Comment by abeloin** [comment]
I have the object list dump:
https://gist.github.com/abeloin/9c5b47c96ed764c0d628

**Comment by fernandog** [comment]
@abeloin 

some shows are 24hrs time format, others's don't. that's the only diff in "airs"
```
  'airs': u'Daily 11:15',
  'airs': u'Sunday 8:30 AM',
  'airs': u'Sunday 3:30 AM',
  'airs': u'Daily 11:15',
  'airs': u'Daily 9:30 PM',
  'airs': u'Tuesday 9:00 PM',
  'airs': u'Tuesday 9:00 PM',
  'airs': u'Daily 11:15',
  'airs': u'Daily 9:30 PM',
  'airs': u'Daily 11:15',
  'airs': u'Daily 11:15',
  'airs': u'Daily 9:30 PM',
  'airs': u'Daily 11:15',
  'airs': u'Saturday 17:30',
  'airs': u'Saturday 5:30 PM',
  'airs': u'Sunday 20:00',
  'airs': u'Sunday 8:30 AM',
  'airs': u'Sunday 8:00 PM',
  'airs': u'Monday 8:30 PM',
  'airs': u'Monday 10:00 PM',
  'airs': u'Daily 9:30 PM',
  'airs': u'Daily 9:30 PM',
  'airs': u'Saturday 9:00 PM',

```

**Comment by abeloin** [comment]
Yep but it's failling

**Comment by fernandog** [comment]
@abeloin any news on this? did you succeeded debug it?

**Comment by abeloin** [comment]
No, I'm unable to reproduce it at all even the data I collected.
@Thraxis Do you still have the issue?

**Comment by fernandog** [comment]
I think its an invalid date from indexer. Like the PR you did and I to Home and coming episode tmpl

**Comment by abeloin** [comment]
No the error mean the sql object ep['airs'] unable to write to the result to itself. Maybe duplicate the variable?

**Comment by Thraxis** [comment]
@abeloin I do get the error still.  But it is not replicating in a consistent manner.  The only suggestion I could make would be add a log entry for the show name that it is working on to give a better idea on what is actually causing the issue. 

I haven't released the my  SickRageConnect to the chrome webstore yet so right now I'm also the only directly affected user in that regard.  But even for me it's not generating thousands or even hundreds of errors.  I'm seeing less than 10 for this problem in 3-4 days.  This with a fairly good sized set of shows as well:

338 Shows (107 Active) | 9112 (+1 snatched) / 10935 Episodes Downloaded

**Comment by abeloin** [comment]
Is it possible to get a copy of SickRageConnect?

**Comment by Thraxis** [comment]
https://github.com/Thraxis/SickRageConnect

You can run it in chrome using developer mode, check out from github, run chrome, goto manage extensions, check "Developer Mode" then click "Load Unpacked Extension" and browse to where you checked out the extension.

I do have a packed version of the extension, but chrome will not load it each session unless it is in the web store.

**Comment by fernandog** [comment]
@Thraxis can you stop your SR and change your local webapi.py file to use this one?

https://github.com/fernandog/SickRage/commit/e1066c30492729cc24a0df5616d7bed399fbb153

will add some debug messages as you sair earlier
I think if it runs ok the problematic episode will have a empty value after  "API :: ep[airs] after replace ="

**Comment by Thraxis** [comment]
@fernandog I added the logging code and made a couple changes as noted on your PR.   I have not gotten a repeat of the error yet.  But I the logging should track this down easier if / when it happens again.  I'll keep running with this modified version of the webapi.py

**Comment by fernandog** [comment]
@Thraxis 

"SELECT airdate, airs, episode, name AS 'ep_name', description AS 'ep_plot', network, season, showid AS 'indexerid'

indexerid = showid

no problem! let's wait the error appear.

**Comment by fernandog** [comment]
@Thraxis please disable auto-updated and disable "git reset" in settings. otherwise git reset will override this change

**Comment by Thraxis** [comment]
@fernandog I keep both of those disabled as a practice anyway

And you missed the part further down in the code:

for ep in sql_results:

The sql result sets is pulled as rows name ep and each element is an array item in that row.  That's why there is an ep['airs']  and why you have to use ep['indexerid'] instead of just indexerid.

(that and it spat an error out when I first tested your code as is)

**Comment by Thraxis** [comment]
@abeloin I've not had a replication of the error yet since adding in the logging code.  But I have a theory  that might pan out by tomorrow on what triggers the error and why we may not be seeing it now when we did earlier.  

I have a suspicion that this may be related to "missed" episodes.  I currently do not have any, but I did last week when this happened. I tend to have at least one between Sunday / Monday so I am hoping to get a verification tonight

**Comment by Thraxis** [comment]
And no joy on that suspicion.   I'll keep running the extended logging in the hope that I can catch it and get more information on where this is coming from.

**Comment by fernandog** [comment]
@Thraxis do you have a backup from last 5-7 days?

**Comment by Thraxis** [comment]
@fernandog  Unfortunately my only viable backups are from March 7 and March 8, after the code was added in to backup on update.

**Comment by Thraxis** [comment]
Looks like I got a replication of this error twice tonight.  But later it worked fine for the same show.

http://pastebin.com/hZ7rsydH

Did a google search on the error and found this on stackoverflow as a way to prevent that error to begin with.

http://stackoverflow.com/questions/3380360/replacing-value-in-all-cursor-rows

**Comment by Thraxis** [comment]
@fernandog , @abeloin 
I made the change recommended from the stackoverflow solution to my webapi.py

Specifically, changing line 753 from

```python
        for ep in sql_results:
```
To
```python
        dict_results = [dict(row) for row in sql_results]
        for ep in dict_results:
```

It's working as expected so likely need a bit of a bake in to make sure the error is actually fixed (and me to get off my ass and make a PR)

**Comment by fernandog** [comment]
@Thraxis so it's not only with ep_airs ?

**Comment by Thraxis** [comment]
@fernandog 
No it's with everything that is in the ep rows.  It looks like the sql_results are already supposed to be returned as a dict and not an sqlite3.row .  The fix I used just makes that change outside the db.py file (for the db.connection)  where the assignment should be happening.

**Comment by Thraxis** [comment]
OK I've put in a log check for the three queries that are concatenated to produce the episode list.  Each one should be returning dict results not sqlite3.row.  If they return an sqlite3.row something is changing the row_factory in the middle of the run.

**Comment by fernandog** [comment]
Still working?

**Comment by Thraxis** [comment]
@fernandog  Yes I can do a PR for the fix... I'm still trying to track down why this is happening though.  None of the rows should even be a sqlite3.row at that point.

**Comment by fernandog** [comment]
@Thraxis any news on the error?

**Comment by Thraxis** [comment]
Posted the PR for the fix for this.

**Comment by devenashani** [comment]
### INFO
Python Version: **2.7.3 (default, Jul 13 2012, 04:03:47) [GCC 4.4.5]**
Operating System: **Linux-2.6.31.8.nv+v2-armv5tel-with-debian-6.0.3**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@4db41da61c3e4639a19613a3e4f0dfeef9831fc0
No Log available with ERRORS: 
### ERROR
```
TORNADO :: API :: 'sqlite3.Row' object does not support item assignment
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by WebSpider** [comment]
Please post debug logs, thanks

**Comment by fernandog** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.1.5-1-osmc-armv7l-with-debian-8.2**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@1c2ab324cadc92e12f7d7a64944305fdf208a5b7
Link to Log: https://gist.github.com/2d0011d4d09bd4d5dc11
### ERROR
```
Thread-20 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 473, in comingEpisodes
    results = ComingEpisodes.get_coming_episodes(ComingEpisodes.categories, sickbeard.COMING_EPS_SORT, False)
  File "/home/osmc/SickRage/sickrage/show/ComingEpisodes.py", line 118, in get_coming_episodes
    parse_date_time(item['airdate'], item['airs'], item['network']))
TypeError: 'sqlite3.Row' object does not support item assignment

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@MGaetan89 do you have this too?

**Comment by MGaetan89** [comment]
I will check if I have that too.
But I know I removed `dict_results = [dict(row) for row in sql_results]` in favor of `DBConnection(row_type='dict')`. Maybe that did not work...

**Comment by miigotu** [comment]
sqlite3.Row is immutable, thats why it was returning a copy before.

**Comment by MGaetan89** [comment]
Indeed, but doesn't `DBConnection(row_type='dict')` take care of that? I will add the missing conversion to fix that.

**Comment by miigotu** [comment]
row_type='dict' I couldnt find any documentation for, but from the error it shows that it is only available for reading not writing (immutable). A complete copy to a new dict like it was doing makes it mutable and then can be reused for a query.

**Comment by MGaetan89** [comment]
Ok. PR is ready :)
