### ISSUE TITLE
Problem adding existing shows

### ISSUE THREAD

**Issue by thesmackdown** [SiCKRAGETV/sickrage-issues#847]
![screen](https://cloud.githubusercontent.com/assets/10361372/6484258/ef04d116-c23f-11e4-9356-e8cd56587a76.png)
I had a weird issue the other day where the database became corrupted and changed about 1/3 of my shows to 'ignored'.  I removed the problem shows but now when I am trying to add them back I am getting the current show table instead of a list of shows to add.

```
2015-03-04 07:16:55 Thread-194 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 257, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 2324, in massAddTable
    return t.respond()
  File "C:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_home_massAddTable_tmpl.py", line 99, in respond
    show_id = VFSL([locals()]+SL+[globals(), builtin],"show_id",True) + '|' + VFSL([locals()]+SL+[globals(), builtin],"str",False)(VFSL([locals()]+SL+[globals(), builtin],"curDir",True)['existing_info'][0]) + '|' + VFSL([locals()]+SL+[globals(), builtin],"str",False)(VFSL([locals()]+SL+[globals(), builtin],"curDir",True)['existing_info'][1])
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\x86' in position 1: character maps to 
```

BRANCH: (develop) / COMMIT: (f51551dc5530c7d4a39431d1f71da8e9723d5892)

**Comment by abeloin** [comment]
Do you have a show with accent or foreign characters?

**Comment by thesmackdown** [comment]
I did.  Changed the names and am still getting this error.

**Comment by abeloin** [comment]
Try adding `chcp 65001` in the same command line running sickrage.

**Comment by thesmackdown** [comment]
Tried it.  Still no luck.

**Comment by abeloin** [comment]
Does the error say:
`File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode` or
`File "C:\Python27\lib\encodings\cp65001.py", line 12, in encode` ?

**Comment by thesmackdown** [comment]
File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode

**Comment by abeloin** [comment]
Then you didn't run the command properly. I don't know how you start sickrage but manually it look like this with the other comand:
```
c:\> chcp 65001
c:\> python Sickbeard.py --nolaunch
```

**Comment by thesmackdown** [comment]
Yup.  I wasn't doing it that way.  Problem solved!
