### ISSUE TITLE
Connection Timeout

### ISSUE THREAD

**Issue by cwerdam** [SiCKRAGETV/sickrage-issues#851]
When I put my Deluge informations and the Sickrage I get  this messege on my logs: 
-----------------------------------------------------------------------------------------------------------------------
The errors is just like this: 2015-03-04 16:00:52 SEARCHQUEUE-BACKLOG-267907 :: Deluge: Connection Timeout HTTPConnectionPool(host='localhost', port=8085): Read timed out. (read timeout=120)

**Comment by fernandog** [comment]
@cwerdam does deluge needs user/pass to access? did you tested the connection when added deluge settings?

**Comment by cwerdam** [comment]
Yes, I put the username and pass on Sickrage. Deluge is works only with the
pass, but I put my username.

Em qua, 4 de mar de 2015 16:40, Fernando <notifications@github.com>
escreveu:

**Comment by fernandog** [comment]
@cwerdam deluge does not need user?
