### ISSUE TITLE
Update RARBG to use API and min seeders / leechers / ranked torrents

### ISSUE THREAD

**Issue by simonwicks** [SiCKRAGETV/sickrage-issues#853]
I've only just noticed Rarbg was a provider after updating today, not sure if that's just me being blind before though. 

But, there doesn't seem to be an option to set min seeders / leechers like there is for something like KAT. 

Is it possible to add this?
When I added RBG as a provider today it went off and found about 50 downloads I'd not managed to find on other providers, but they all have so few seeders it'll take about a year to get everything.

Thanks. 

Using Synology

SR Version:	BRANCH: (master) / COMMIT: (e8405b35d6d8fc0bc1909c18e2e528e68cdc0cde) 

Python Version:	2.7.8 (default, Dec 12 2014, 22:38:36) [GCC 4.3.2]

**Comment by fernandog** [comment]
@corpo

**Comment by CoRpO** [comment]
@fernandog this is planned to be done

**Comment by ochawkeye** [comment]
Planned to be done across the board for providers or for RARBG?

**Comment by CoRpO** [comment]
Just for RARBG, by me

**Comment by simonwicks** [comment]
Could it not be an option to be set across them all?

It's extra steps for the user to replicate the same numbers for each provider when you can do it once and it apply to all maybe?

I personally wouldn't see a use for have 10 min on one and 40 in on another for example.

**Comment by fernandog** [comment]
@simonwicks others have. Private trackers vs public trackers

**Comment by rarbg** [comment]
Also pasting the link to the public api docs here https://rarbg.com/pubapi/apidocs.txt

**Comment by fernandog** [comment]
@rarbg thanks! How did you found us? Kat was having rss issues and we told all users to use rarbg

**Comment by rarbg** [comment]
@fernandog believe it or not random luck :)

**Comment by fernandog** [comment]
@rarbg nice! thanks! Is it possible to fetch more than 7 days? 
Do you know how SickRage works? 
We have daily searches and backlog searches
Daily search are for episodes currently airing.
backlog search is when you add a tv-show from 2011 and you need to download it. If 7 days it's the limit, SR won't fetch anything from rarbg.

**Comment by rarbg** [comment]
@fernandog No idea how SickRage actually works , thanks for explaining , can you tell me if sickrage knows the imdb tt when you add a new show or is the "add" actually just a search ?

**Comment by fernandog** [comment]
@rarbg torrents we search by string ( showname S00E00). as not all torrents providers have the hability to use tvrage ID or thetvdb id. BUT all shows from SR has an indexer ID

**Comment by TagForce** [comment]
@rarbg No, SR doesn't actually use the imdb tt for its internal workings. It uses tvdb and tvrage IDs for that. However, it does get the imdb tt from those, and does get information from imdb when adding the show.

**Comment by rarbg** [comment]
@TagForce  @fernandog 
So instead of removing the limit on search by string can i just give you an extra option where you can search by imdb tt(already working) / tvdb / tvrage id that is unlimited in back searching in our database?

**Comment by fernandog** [comment]
@rarbg the site scraping works like that: we search only by showname

**Comment by rarbg** [comment]
Ok. Api docs updated.
1. Now you can search also by tvdb + tvrage
2. Removed limit restrictions on imdb / tvdb / tvrage searches

**Comment by fernandog** [comment]
@rarbg thanks! did you noticed an increase in web traffic recently?

**Comment by simonwicks** [comment]
Glad all this has come about from my feature / bug ! :)

**Comment by rarbg** [comment]
@fernandog 
no :) nothing unusual , no spikes .. i guess not a lot of users switched to us ?

**Comment by fernandog** [comment]
@rarbg can you implement an optional "minimal seeders" and "minimal leechers" in API - if is not too trouble.

**Comment by rarbg** [comment]
@fernandog 
Done + Api docs updated :)

**Comment by abeloin** [comment]
@fernandog Yes, we need to change the code for that.

**Comment by fernandog** [comment]
@rarbg thanks!

**Comment by rarbg** [comment]
@fernandog np :)

**Comment by CoRpO** [comment]
Cooool, an API :) I was not very proud of my "I bypassed your JS/cookie protection and I hope you won't change the keys too often ..."
Thank you @rarbg ! I'll update the RARBG provider ASAP

**Comment by rarbg** [comment]
great @CoRpO 
Ill also create a domain specificly for the api today too , in order to not be affected of the UK blocks

**Comment by rarbg** [comment]
@CoRpO @fernandog 
api docs updated with the new domain :)

**Comment by fernandog** [comment]
@CoRpO any news updating rarbg to use API ? thanks!

**Comment by CoRpO** [comment]
@fernandog i'll have a look at it this weekend, needs a full rewrite

**Comment by fernandog** [comment]
@CoRpO if you need testing or something let me know.

**Comment by CoRpO** [comment]
@fernandog I'm just overloaded of work atm :/

**Comment by fernandog** [comment]
@CoRpO no problem. RARBG is still working as it is. take your time

**Comment by simonwicks** [comment]
@fernandog It's actually stopped working for me for some reason. 
It was fine up until 2 updates ago (beginning of this week maybe), now it doesn't seem to find any results anymore.

I'm at work right now, but I'll try to supply a failing search on my end paired with the actual results on RBG later on.

I'd not changed any settings, but have since tried different proxy's in the provider settings and no luck. 

I've been manually grabbing them since as figured this new system would solve it. I don't see any other reports of it not working by anyone else, so figured something must be up on my end. But as I'd not changed anything I'm a bit stumped as to what could be causing it at the moment,

**Comment by fernandog** [comment]
@simonwicks please open a new issue and follow guidelines

**Comment by fernandog** [comment]
@CoRpO any updates with new RARBG code?

**Comment by abeloin** [comment]
@rarbg Using min_seeders or min_leechers result in a error response, example:
`https://torrentapi.org/pubapi.php?mode=search&search_tvdb=273181&search_string=Better%20Call%20Saul%20S01E07&token=0khxu9y7r3&category=18;41&sort=last&limit=100&format=json&ranked=1&min_seeders=50`

Any idea why?

**Comment by rarbg** [comment]
Fixed. Sorry about that! 

----- Original Message -----

**Comment by abeloin** [comment]
@rarbg Thanks for the fast reply

**Comment by rarbg** [comment]
@abeloin 
Can you please modify the user agent on the get_token call ? 
What im seeing is :
get token - python-requests/2.5.1 CPython/2.7.3 Linux/3.18.8+
everything else - SickRage/(Linux; 3.18.8+; XXX)

**Comment by fernandog** [comment]
@rarbg can you check if is working? Just forced a search in rarbg. 

Tuesday, 14 April 17 : 45 : 15 (GMT + 1:00)

**Comment by rarbg** [comment]
Confirmed working , got a token request with user agent
SickRage/(Linux; 3.18.10-1-osmc; 66efded2-XXX) 

----- Original Message -----
