### ISSUE TITLE
[Feature Request] Receive news notifications from sickrage

### ISSUE THREAD

**Issue by abeloin** [SiCKRAGETV/sickrage-issues#854]
It would be interesting to receive update notifications on new features, broken provider, ... via sickrage in a notification center.

**Comment by fernandog** [comment]
+1

**Comment by tchirou** [comment]
+1000
A brief summary of each update with new features and major bug fixes would be great !

**Comment by fernandog** [comment]
@tchirou for now:
https://sickrage.tv/forums/forum/main-category/latest-news/19525-enjoy-the-new-update-tons-of-bug-fixes-and-a-lot-of-new-features?p=20592#post20592

**Comment by tchirou** [comment]
Oh ok nice
Is this master or dev ?

**Comment by fernandog** [comment]
@tchirou always master. remember master is being updated every week?

**Comment by tchirou** [comment]
oh I did not realize there was a planned release schedule
Great to know

**Comment by fernandog** [comment]
@abeloin done
