### ISSUE TITLE
RSS-Custom

### ISSUE THREAD

**Issue by maxcore** [SiCKRAGETV/sickrage-issues#855]
I use the Master branch and in the last 2 days my custom rss was disappeared. I re add the provider and when i refresh the provider disappeared . I don't have log to prof this , but am alone with this problem ?

**Comment by abeloin** [comment]
After clicking on Add, did you click on Save Change?

**Comment by maxcore** [comment]
yes ! when i go in the provider option to set the Ratio i save it and go on Provider Priorities and the providers has disappeared.

**Comment by abeloin** [comment]
I'm unable to reproduce the issue, here's a screencast when trying to replicate the issue:
https://copy.com/yvlz0FEyWsY8XPGe

**Comment by maxcore** [comment]
i think i have a permission issues on my synology nas .... i will close the issues i think the problem was from my nas and not the sickrage ... thx for your reply

**Comment by maxcore** [comment]
@abeloin normal ?

https://www.dropbox.com/s/z7l0g5irk61sgxz/vlc-output.ts?dl=0

**Comment by fernandog** [comment]
@maxcore after it's missing, does it appear in provider options list?

**Comment by maxcore** [comment]
no

**Comment by fernandog** [comment]
@maxcore can you send the config.ini provider contents (removing passwords and etc) when you save the second custom provider?

mine is: torrentrss_data = RARBG-RSS|http://rarbg.com/rssdd.php||0|eponly|0|0|0

but only one

**Comment by maxcore** [comment]
[TorrentRss]
torrentrss_data = ""

is empty

**Comment by fernandog** [comment]
@maxcore 

please test:
- stop SR
- set config.ini torrentrss_data = ""
- start SR
- add one provider save, change settings
- add second provider, save, change settings
- go to provider order page, fully refresh
- check it

**Comment by abeloin** [comment]
Are you able to change any other settings in the other providers which are successfully saved? config.ini read only? Log message?

**Comment by maxcore** [comment]
https://www.dropbox.com/s/qeiyc4t1wlph0x7/config.ini?dl=0

**Comment by fernandog** [comment]
@maxcore read my previous comment

**Comment by maxcore** [comment]
@fernandog yes i do it now

**Comment by maxcore** [comment]
Not working , when i go to add the second provider in Configure Custom Torrents Provider  the list is empty , only -- Add New Provider --

**Comment by fernandog** [comment]
can you check your config.ini permission?
try change any other setting in SR and save it

**Comment by fernandog** [comment]
@maxcore any lucky?

**Comment by maxcore** [comment]
@fernandog the same i give 0777 to the config.ini and the same happen

**Comment by fernandog** [comment]
@maxcore javascript enabled? adblocks? I'm out of options =)

master branch is fully updated. nothing different from develop about providers

**Comment by maxcore** [comment]
i have test on browser without adblock and javascript is enable , i have test on synology and my mac , the same thing happen ..

**Comment by abeloin** [comment]
No log message? Did you tried changing some other setting from another provider? Open the developer tools in your browser to see if there some javascript error.

**Comment by maxcore** [comment]
@abeloin 

jquery-1.11.2.min.js?19616:3 Resource interpreted as Font but transferred with MIME type text/html: "http://192.168.0.125:8899/css/fonts/OpenSans-Regular-webfont.woff".
jquery-1.11.2.min.js?19616:3 Resource interpreted as Font but transferred with MIME type text/html: "http://192.168.0.125:8899/css/fonts/OpenSans-Semibold-webfont.woff".
configProviders.js?19616:165 Uncaught TypeError: Cannot read property '1' of undefined
(index):228 GET http://192.168.0.125:8899/js/lib/jquery.qtip.min.js.map 404 (Not Found)

**Comment by maxcore** [comment]
![capture d ecran 2015-03-05 13 45 11](https://cloud.githubusercontent.com/assets/4043787/6511902/e78095e8-c33d-11e4-8b36-05c9f9b0256d.png)

**Comment by fernandog** [comment]
@maxcore 

try this provider:

RARBG-RSS
http://rarbg.com/rssdd.php

see if you can reproduce

**Comment by maxcore** [comment]
![capture d ecran 2015-03-05 14 00 24](https://cloud.githubusercontent.com/assets/4043787/6512210/0c16f04e-c340-11e4-9a77-9a2dffbe9d47.png)

@fernandog 
the same

**Comment by abeloin** [comment]
What is the content of the line from configProviders.js?

**Comment by maxcore** [comment]
@abeloin @fernandog i find it !!! i need to enable NZB Search and after the provider stay on the config !!!

**Comment by maxcore** [comment]
i don't use NZB but i will enable it

**Comment by fernandog** [comment]
strange that you need to enable NZB to use custom torrent.  I have enabled. this maybe javascript error

**Comment by maxcore** [comment]
its from me or is from sickrage java error ?

**Comment by abeloin** [comment]
@maxcore What is the content of the line from configProviders.js?

**Comment by maxcore** [comment]
@abeloin how i do that ?

**Comment by abeloin** [comment]
@maxcore Update your branch a Pr was pushed

**Comment by maxcore** [comment]
@abeloin Confirmed ! working ! thx you for your help!!!

**Comment by maxcore** [comment]
quebecois rlzzz ;)
