### ISSUE TITLE
Post Processing Move Associated Files not working

### ISSUE THREAD

**Issue by phdelodder** [SiCKRAGETV/sickrage-issues#856]
The post process doesn't move the associated files like srt. The srt file remains in the Download Dir.

**Comment by TagForce** [comment]
Please... Logs and examples...
'It doesn't work' isn't really helpful.
Follow the guidelines here: https://github.com/SiCKRAGETV/sickrage-issues
This will ensure that we have enough information to look for the actual problem and try to fix it.

As for moving associated files:
It only moves files that have the exact same name as the video file. So if your subs have a language code in them it won't move them.

**Comment by phdelodder** [comment]
Branch : master
Commit hash : e8405b35d6d8fc0bc1909c18e2e528e68cdc0cde
Your operating system and python version : ubuntu 14.10 2.7.8 (default, Oct 20 2014, 15:05:19) [GCC 4.9.1]
What you did place mkv and srt in post processing folder 
![selection_007](https://cloud.githubusercontent.com/assets/7259755/6501831/8c2858b8-c31d-11e4-87c1-a87d22c6bae0.jpg)

What happened only mkv copied
What you expected mkv and srt should be copied 
Link to a copy/paste of your logfile with clear debug info of the error on PASTEBIN


Logs:
Postprocessing results
Processing folder /media/data1/New/Done
TV_DOWNLOAD_DIR: /media/data1/New/Done
PostProcessing Path: /media/data1/New/Done
PostProcessing Dirs: []
PostProcessing Files: ['Two.and.a.Half.Men.S12E02.720p.HDTV.X264-DIMENSION.srt', 'Two.and.a.Half.Men.S12E02.720p.HDTV.X264-DIMENSION.mkv']
PostProcessing VideoFiles: ['Two.and.a.Half.Men.S12E02.720p.HDTV.X264-DIMENSION.mkv']
PostProcessing RarContent: []
PostProcessing VideoInRar: []
Processing /media/data1/New/Done/Two.and.a.Half.Men.S12E02.720p.HDTV.X264-DIMENSION.mkv (None)
Retrieving episode object for 12x2
Snatch history had a quality in it, using that: HD TV
Is ep a priority download: False
File /media/data/Videos/Series/Two and a Half Men/Season 12/Two.and.a.Half.Men.S12E02.720p.HDTV.X264-DIMENSION.mkv doesn't exist so there's no worries about replacing it
Found release name Two.and.a.Half.Men.S12E02.720p.HDTV.X264-DIMENSION
Destination folder for this episode: /media/data/Videos/Series/Two and a Half Men/Season 12
Moving file from /media/data1/New/Done/Two.and.a.Half.Men.S12E02.720p.HDTV.X264-DIMENSION.mkv to /media/data/Videos/Series/Two and a Half Men/Season 12/Two.and.a.Half.Men.S12E02.720p.HDTV.X264-DIMENSION.mkv
Processing succeeded for /media/data1/New/Done/Two.and.a.Half.Men.S12E02.720p.HDTV.X264-DIMENSION.mkv
Problem(s) during processing

http://pastebin.com/vR4hNBjG

**Comment by TagForce** [comment]
@phdelodder Thanks. It should move the srt as well, I'll look into this.

**Comment by TagForce** [comment]
@phdelodder This only happens in master. In develop the srt is moved fine.
Since we're running catch-up on fixes to be merged into master, I suggest you wait a little while for the next merge into master (which should be somewhere in the next couple of days), and then try again.
There've been some fixes to the post-processing methods.

**Comment by fernandog** [comment]
@Tagforce our idea is to merge develop onto master once a week.

**Comment by TagForce** [comment]
@fernandog That's the next couple of days :)

**Comment by fernandog** [comment]
Just telling you what abeloin and I decided (via IM). Merge every sunday.

**Comment by phdelodder** [comment]
I'll test it again when the merge on sunday is done. Thanks @TagForce  for the quick replies!

**Comment by fernandog** [comment]
@phdelodder worked?

**Comment by phdelodder** [comment]
Yes it works

**Comment by valantislevas** [comment]
i also have this problem on

SR Version:	BRANCH: (master) / COMMIT: (bf2baf309bd01683fdc06d57ece0b89d53b4a180)
