### ISSUE TITLE
PushBullet update notification throws an error on Content-length header

### ISSUE THREAD

**Issue by TagForce** [SiCKRAGETV/sickrage-issues#857]
On updating develop branch to latest commit:

2015-03-05 09:06:58 ERROR    Thread-186 :: Pushbullet notification failed.
AA
AA  
POST requests require a Content-length header.  That’s all we know.
AA  

411. That’s an error.
AA  
AA

**Comment by TagForce** [comment]
notify_git_update is missing a value for notificationType on the call to _sendPushbullet which defaults it to None...

**Comment by TagForce** [comment]
Hopefully fixed in:
https://github.com/SiCKRAGETV/SickRage/pull/1481

**Comment by abeloin** [comment]
PR Merged

**Comment by TagForce** [comment]
@abeloin Updating now, so if you commit something else later today I can check if that fixes it for real.

**Comment by TagForce** [comment]
Works. I now get no error on updating and a nice pushbullet notification that SR was updated.
