### ISSUE TITLE
[APP SUBMITTED]: Failed Unrar archive (0): Unrar: No file to extract, file already exist?

### ISSUE THREAD

**Issue by frederoni** [SiCKRAGETV/sickrage-issues#858]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2]**
Operating System: **Linux-3.13.0-46-generic-x86_64-with-Ubuntu-14.04-trusty**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@59b2535c41390ccd3d6e13dd0463d58da8b86ced
### ERROR
```
POSTPROCESSER :: Failed Unrar archive (0): Unrar: No file to extract, file already exist?
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@frederoni can you extract that file yourself? does it extract ok?

please send full logs

**Comment by frederoni** [comment]
It was actually another bug I tried to file. Didn't know it automatically selected the first one. Issue closed.

**Comment by fernandog** [comment]
@frederoni did you resolved this? what was the problem?

**Comment by frederoni** [comment]
@fernandog corrupt rar file. The issue I tried to file was unicode support for downloading subtitles.

**Comment by fernandog** [comment]
I found a bug in the log message. fixed. 
It should show the filename.

**Comment by abeloin** [comment]
PR merged
