### ISSUE TITLE
[APP SUBMITTED]: local variable 'fout' referenced before assignment

### ISSUE THREAD

**Issue by ripper1967** [SiCKRAGETV/sickrage-issues#859]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@59b2535c41390ccd3d6e13dd0463d58da8b86ced
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: local variable 'fout' referenced before assignment
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@abeloin 

```
    try:
        fin = os.open(src, READ_FLAGS)
        fout = os.open(dst, WRITE_FLAGS)
        for x in iter(lambda: os.read(fin, BUFFER_SIZE), ""):
            os.write(fout, x)
    except Exception as e:
        raise e
    finally:
        os.close(fin)
        os.close(fout)
```

I don't see the error
https://github.com/SiCKRAGETV/SickRage/blob/develop/lib/shutil_custom/__init__.py#L40

**Comment by abeloin** [comment]
@ripper1967 Can you provide the log section when this event happend?

**Comment by TagForce** [comment]
@abeloin If ```fin = os.open(src, READ_FLAGS)``` throws an exception fout would never be initialized, but is still referenced in the finally clause

**Comment by ripper1967** [comment]
yes  http://pastebin.com/qXBEJMTV but it it not throwing that error at the moment

**Comment by abeloin** [comment]
@TagForce Yes it just need a try except pass at the end.

I wanted to know where it failed to see why the file wasn't there but still tried it.

**Comment by abeloin** [comment]
@ripper1967 PR merged please update

**Comment by ripper1967** [comment]
confirmed fixed
