### ISSUE TITLE
config.ini "git_password =" not encrypted.

### ISSUE THREAD

**Issue by neoatomic** [SiCKRAGETV/sickrage-issues#860]
I just noted that the "git_password =" in the config.ini in not encrypted. 
it shows the plain password even when the encrypt passwords setting is enabled.

```
SR Version: 	BRANCH: (develop) / COMMIT: (3e0ccb95aad2ed19a827b8ff936a32cb9fb98756) 
Python Version:	2.7.8 (default, Dec 12 2014, 20:25:54) [GCC 4.6.4]
```

**Comment by fernandog** [comment]
did you shutdown/start SR after enabled this option?

**Comment by neoatomic** [comment]
Yes, the other passwords are encrypted, only "git_password" not.
Let me try to disable the encryption and then enable it again.

**Comment by neoatomic** [comment]
@fernandog Thanks for the quick fix.

**Comment by fernandog** [comment]
@neoatomic fixed and merged. please update and report back

**Comment by neoatomic** [comment]
Updated.
But i needed to disable the encryption and then enable it again before  "git_password" was encrypted.
Thanks.

**Comment by neoatomic** [comment]
@fernandog The last week i was experiencing slowness with my SR install. I just discovered the problem.
My config.ini was 34mb large. Seems that encrypting the git password was looping.?
It created 453000 lines for just the encrypted git password...
So it seems that there is something wrong with the code. Could you take a look at it.?

**Comment by fernandog** [comment]
@neoatomic

Please follow guidelines!
Just kidding

**Comment by abeloin** [comment]
BTW looking at the code for encrypting password, it's machine specific. So if you move your config.ini to another machine all the password will be wrong if they are encrypted.

**Comment by abeloin** [comment]
@neoatomic See https://github.com/SiCKRAGETV/sickrage-issues/issues/1011
