### ISSUE TITLE
Send torrent to client, fail detection 

### ISSUE THREAD

**Issue by Alexwijn** [SiCKRAGETV/sickrage-issues#862]
If Sickrage send a torrent to for example Transmission and it fails because he did not respond in time because he is to busy downloading, will he retry again or will it be "forgotten" and being kept in snatched. 

I noticed because some episodes are marked as snatched but can't find it in the post processing folder or in the queue if Transmission. 

Can't give you any logs because it's older than a day. (Already increased the log size to prevent this in the future.) 

I'm on the master branch since the develop branch don't like me there. The big warning irritated me. I'm also using the latest version.

**Comment by fernandog** [comment]
@Alexwijn maybe it's a buggy torrent. 

https://github.com/SiCKRAGETV/sickrage-issues/issues/830

check your logs and see if you find a DEBUG message: "uTorrent: Failed Sending Torrent"
is usually a not magnet torrent. Almost 90% of providers use magnet links

**Comment by Alexwijn** [comment]
But will he retry if there is an connection problem with the client?

**Comment by fernandog** [comment]
@TagForce in the case the correct is not set as SNATCHED, isn't?

**Comment by TagForce** [comment]
@fernandog Actually don't know how it handles that. I think it's time to look into searching and snatching

**Comment by ripper1967** [comment]
If my utorrent fails or times out sickrage just leaves the show as wanted then it searches again for it on the next backlog...it does not add it to snatched..

**Comment by fernandog** [comment]
@ripper1967 thanks!
