### ISSUE TITLE
[APP SUBMITTED]: [Errno 13] Permission denied: u'J:\\tv\\The Odd Couple (2015)\\Season 01\\The.Odd.Couple.2015.S01E03.SD.TV-LOL.mp4'

### ISSUE THREAD

**Issue by ripper1967** [SiCKRAGETV/sickrage-issues#868]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@495b040ffadd5386f52f343bba13dfb017a92035
Link to Log: https://gist.github.com/00f2a2cd81b5e30e3912
### ERROR
```
Thread-24 :: Unable to move file G:\completed  tv\The.Odd.Couple.2015.S01E03.HDTV.x264-LOL.mp4 to J:\tv\The Odd Couple (2015)\Season 01\The.Odd.Couple.2015.S01E03.SD.TV-LOL.mp4: [Errno 13] Permission denied: u'J:\\tv\\The Odd Couple (2015)\\Season 01\\The.Odd.Couple.2015.S01E03.SD.TV-LOL.mp4'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by ripper1967** [comment]
here is debug http://pastebin.com/HCSPuDiT

**Comment by fernandog** [comment]
@ripper1967 its an issue in your setup. Check target permission.

**Comment by ripper1967** [comment]
Ok thank you... You can close this I thought it was , just wanted to confirm it before I changed permissions on the network drive..
