### ISSUE TITLE
[Feature Request] First try original provider url, if fails/exception use proxy

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#869]
This way we don't need to enable/disable proxy for each provider.
User don't need to be worried if is down in his country or whatever happens and keep changing settings
SR will always try proxy if SR gets this error:
and If even proxy returns error than provider must be down. and show a proper message to user so he can disable that provider

```
[Errno 10061] No connection could be made because the target machine actively refused it
```

or timeout error

we can also try scrapper http://www.downforeveryoneorjustme.com/provider_url
```
It's not just you! URL looks down from here.
It's just you. URL is up.
```

and if is down, show a warning or something in the provider list

@TagForce @abeloin

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
