### ISSUE TITLE
Auto Post Processing Woes

### ISSUE THREAD

**Issue by kendog819** [SiCKRAGETV/sickrage-issues#870]
BRANCH: (master) / COMMIT: (495b040ffadd5386f52f343bba13dfb017a92035) 
Qnap TS-451 - Python Version: 2.7.3 (default, Apr 12 2012, 20:25:04) [GCC 4.2.1]

Basically nothing gets Auto PP'd I have to manually do everything. Once in a while a show here or there will go thru.

Original Thread: https://sickrage.tv/forums/forum/help-support/general-support/19482-post-processing-problems

Log: http://pastebin.com/LGEM0vdM

Thanks,
Ken

**Comment by fernandog** [comment]
check your renaming patter

from log:
```
POSTPROCESSER :: Analyzing name u'.@__thumb adefaultScandal.US.S04E02.HDTV.XviD-AFG.avi'
POSTPROCESSER :: Analyzing name u'/share/CACHEDEV1_DATA/Download/Scandal.US.S04E02.HDTV.XviD-AFG/.@__thumb/adefaultScandal.US.S04E02.HDTV.XviD-AFG.avi'
```
it's a weird filename

**Comment by TagForce** [comment]
@kendog819 Does that folder actually exist like that?

.@__thumb?

It's the name of the downloaded file, not the destination file.

**Comment by TagForce** [comment]
Check your downloader... it seems like it's messing up the filenames. or still copying the file

**Comment by kendog819** [comment]
I have no clue what the .@__thumb is. 

I use transmission

My renaming looks like this: 

Season %0S/%Sx%0E %EN  -  Season 02/2x03 Ep Name.ext

**Comment by fernandog** [comment]
send a print please. Tree view

**Comment by kendog819** [comment]
![image](https://cloud.githubusercontent.com/assets/11353628/6530972/4b742194-c403-11e4-9ef4-c50fa21c9a3f.png)

**Comment by kendog819** [comment]
![image](https://cloud.githubusercontent.com/assets/11353628/6531028/b55c5a2c-c403-11e4-94bf-5083a006465d.png)

**Comment by kendog819** [comment]
![image](https://cloud.githubusercontent.com/assets/11353628/6531036/cbea0636-c403-11e4-9889-27ff7af1912f.png)

**Comment by kendog819** [comment]
![image](https://cloud.githubusercontent.com/assets/11353628/6531057/fbc1da14-c403-11e4-8123-0331cd9b4168.png)

**Comment by fernandog** [comment]
@kendog819 do you have hidden folders? enable the setting to show them and re-send print

**Comment by kendog819** [comment]
I have no clue how to do that

**Comment by fernandog** [comment]
@TagForce is he has a hidden folder like that, PP may try to move it there. And as the folder name is strange, SR get's lost in regex

@kendog819 http://blogs.msdn.com/b/zxue/archive/2012/03/08/win8-howto-19-show-hidden-files-folders-and-drives.aspx

**Comment by kendog819** [comment]
![image](https://cloud.githubusercontent.com/assets/11353628/6531152/e7230ea6-c404-11e4-8323-82fca2a547c2.png)
Was already checked :-/

**Comment by fernandog** [comment]
@abeloin is this a javascript error?! really strange

**Comment by kendog819** [comment]
The @__thumb is a Qnap thing.

https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=.%40__thumb%20qnap

**Comment by kendog819** [comment]
I enabled showing hidden folders on there too though, and still don't see it.......

**Comment by kendog819** [comment]
If anyone wants to teamview me, It can be setup.

**Comment by kendog819** [comment]
![image](https://cloud.githubusercontent.com/assets/11353628/6532132/4617b87e-c40c-11e4-9fc2-8c7fab4de6a5.png)
Is there any way of telling SR to not look at certain folders?

**Comment by TagForce** [comment]
it should already. it ignores folders starting with a .
I'll look into this. Explicitly ignoring those folders needs to happen.

**Comment by kendog819** [comment]
Thanks TagForce, I appreciate the help! :)

**Comment by kendog819** [comment]
Any updates?

**Comment by TagForce** [comment]
@kendog819 Still trying to find where this goes wrong. It already skips hidden folders in validate_dir...

**Comment by fernandog** [comment]
@TagForce but a folder with starting with @ it's not a really hidden folder, isn't ? In explorer - screenshot - this folder don't show up.

@kendog819 can you SSH, enter this folder and run: 
```
ls -la
```

and post results?

**Comment by kendog819** [comment]
@fernandog 

I have Putty. But really no clue what to do or how to use it. I can login to my NAS, that is about the extent of my knowledge, Also, it is not one specific folder from my understanding. The .@__thumbs is in every tv show's folder.

If you can direct me a little better, or want to teamview me, we can set that up.

Thanks!

**Comment by fernandog** [comment]
open putty, acess the nas with user/password
when the prompt appear run:
```
cd "/share/CACHEDEV1_DATA/Download/Scandal.US.S04E02.HDTV.XviD-AFG/"
```
then:
```
ln -a
```

**Comment by kendog819** [comment]
![image](https://cloud.githubusercontent.com/assets/11353628/6547013/66e0efa4-c5a0-11e4-82ac-244f65bdbd1a.png)

**Comment by kendog819** [comment]
![image](https://cloud.githubusercontent.com/assets/11353628/6547018/ae11a026-c5a0-11e4-9b37-30b7216c253e.png)

**Comment by abeloin** [comment]
Maybe I'm wrong but nothing in get_path_dir_files prevent hidden folder.
You can see the proof in the image from previous comment https://github.com/SiCKRAGETV/sickrage-issues/issues/870#issuecomment-77608488

**Comment by fernandog** [comment]
@abeloin what about this:

https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/helpers.py#L960

**Comment by abeloin** [comment]
It's validating Scandal.US.S04E02.HDTV.XviD-AFG but not the folder underneath when it's in the walk that is why it's working on a manual PP but fail on on auto PP

**Comment by kendog819** [comment]
Is there a way to resolve this?

**Comment by abeloin** [comment]
Yes, we are in the process of fixing the issue. A pull requests will be submitted in develop and then merge in master after testing.

**Comment by kendog819** [comment]
There is a way of me using the develop, right?

**Comment by fernandog** [comment]
Yes. But there is no fix available yet

**Comment by kendog819** [comment]
Sorry, i'm very new here. Will it be posted in here when there is a fix?

**Comment by abeloin** [comment]
Yes you will get a notification when there's a fix

**Comment by TagForce** [comment]
@abeloin are you fixing this, or should I add the validate_dir check to the dirs it gets from the walk?

**Comment by TagForce** [comment]
@kendog819 @abeloin @fernandog Please test this commit...
It looks like it's working on my test rig, but it needs to be well tested on a production machine as well.

https://github.com/SiCKRAGETV/SickRage/pull/1505

It adds a validate dir check to each folder it is actually processing, rather than just the subfolder it's about to process.
It also changes the delete folder to only delete folders which are empty.
@fernandog @abeloin I think this may actually also fix some other "file does not exist" errors in post processing. If a file was processed in a subfolder of the TV_DOWNLOAD folder with multiple files in it, it would delete the folder after processing the first file if it was not in a RAR file, and process Method is 'move'

**Comment by abeloin** [comment]
@TagForce 
> are you fixing this, or should I add the validate_dir check to the dirs it gets from the walk?

Not anymore ;)

Will test and report back

**Comment by fernandog** [comment]
@Tagforce about this "It also changes the delete folder to only delete folders which are empty." - If there is associated files there? Will they be removed before the empty check?

**Comment by TagForce** [comment]
@fernandog Yes, this only affects deletion of folders. In other words, if process_method is 'move'. And that will delete associated files anyway, since they are moved. If process_method <> 'move' no files or folders will be deleted.

**Comment by kendog819** [comment]
I'm really not sure how to update to this. Especially since it is running on my nas.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/870

**Comment by kendog819** [comment]
Not sure what to do at all @fernandog

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1505

**Comment by fernandog** [comment]
Wait an update on master or switch to develop branch in advanced setting

**Comment by kendog819** [comment]
Will master update be long?

**Comment by kendog819** [comment]
Under "Branch Version" in the dropdown my only option to choose from is "Master" How do I change to develop?

**Comment by fernandog** [comment]
enter git user/pass in github SR settings

**Comment by kendog819** [comment]
Thank You :)

**Comment by fernandog** [comment]
@kendog819 please reply when you finish testing

**Comment by kendog819** [comment]
@fernandog  Doesn't seem to be working. I have a show that was downloaded last night I have done a rescan and forced a full update. I'm not seeing any errors, but i'm also seeing no attempts at post processing the episode. Should I try a manual PP?

**Comment by fernandog** [comment]
@kendog819 yes please.

do you still see this?

https://cloud.githubusercontent.com/assets/11353628/6531028/b55c5a2c-c403-11e4-94bf-5083a006465d.png

**Comment by kendog819** [comment]
@fernandog 
![image](https://cloud.githubusercontent.com/assets/11353628/6562076/4f4d0c3e-c66c-11e4-94f4-c990404cab49.png)

**Comment by kendog819** [comment]
![image](https://cloud.githubusercontent.com/assets/11353628/6562101/7d7a7786-c66c-11e4-9c41-205d178f36fc.png)

![image](https://cloud.githubusercontent.com/assets/11353628/6562115/9c7f170e-c66c-11e4-8d09-a7c287d71cf5.png)

**Comment by fernandog** [comment]
@kendog819 are you sure you are using develop branch?

please check /config page

**Comment by kendog819** [comment]
@fernandog  Pretty Sure ;)

![image](https://cloud.githubusercontent.com/assets/11353628/6562734/d6370600-c671-11e4-8887-297b1f9077ed.png)

**Comment by fernandog** [comment]
@TagForce PR 1505 didn't fixed =(

**Comment by TagForce** [comment]
What's wrong with it? It's ignoring the hidden folders.

**Comment by kendog819** [comment]
It's still not auto post processing though. Not even an attempt.

**Comment by TagForce** [comment]
@kendog819 Is autoPP not running at all?
What are your settings for PP?
Scan and Process enabled at what frequency?
If you restart SR does it run a Post Process thread (check logs)?
Can you restart SR and upload the log from that here?

**Comment by kendog819** [comment]
![image](https://cloud.githubusercontent.com/assets/11353628/6563205/a7103528-c675-11e4-8db7-24a925aa6306.png)

**Comment by kendog819** [comment]
I have nothing in my download folder to try to APP besides these now:

![image](https://cloud.githubusercontent.com/assets/11353628/6563241/1149704e-c676-11e4-899b-fdcec768f94d.png)


And SR doesn't touch them, I assume because they have been downloaded not inside of a folder (All FUM releases are never in a folder for some reason). Hoping SR can be adjusted to add those as well, I'm sure I'll need to start a new thread for that though.

**Comment by TagForce** [comment]
Ok. Restart SR, wait 15 minutes and upload the logs from the restart on... There should be 2 PP runs in there.
Apart from asking for the folder to process there is absolutely 0 difference between Auto Postprocessing and manual Postprocessing. They are the exact same functions being called.

**Comment by kendog819** [comment]
I have nothing to PP now though. Other than those 4 files that don't get touched anyways.

**Comment by TagForce** [comment]
@kendog819 It should PP those files just fine. It should PP any files in the folder you set as your download folder in SR or any subfolder thereof as long as the folder is not hidden.

**Comment by kendog819** [comment]
It hasn't touched those files ever. They don't even show up in Manual PP unless I throw them in a folder 1st.

![image](https://cloud.githubusercontent.com/assets/11353628/6563400/48c7f97c-c677-11e4-8dfc-f0e2fc11759a.png)

![image](https://cloud.githubusercontent.com/assets/11353628/6563410/5cdfe1cc-c677-11e4-9178-6e698aec0f10.png)

**Comment by TagForce** [comment]
That's because you browse for a folder... Files shouldn't show up there. Just hit ok and it should find the files in there.

**Comment by kendog819** [comment]
Thanks for that @TagForce , learned something new. Now I really have nothing to PP though..lol

Let me find a new show to add real quick so we can test this.

**Comment by TagForce** [comment]
@kendog819 take your time. I need some sleep anyway. Gather some logs and I'll take a look when I wake up. :)

**Comment by kendog819** [comment]
Since updating to this develop, im having issues getting SR to snatch episodes.
![image](https://cloud.githubusercontent.com/assets/11353628/6566357/2d95a59c-c68f-11e4-9922-9a4149a654ac.png)

Manual Searching is fine though.

Still not Auto Post Processing either: http://pastebin.com/LTkjtgdk

![image](https://cloud.githubusercontent.com/assets/11353628/6566636/8f28cb7e-c692-11e4-887b-dbcb936e3bb5.png)

**Comment by TagForce** [comment]
Found temporary sync files, skipping post processing...
Are there any files with the following extensions in the download folder?
!sync,lftp-pget-status,part,bts
Uncheck postpone if syncfiles are found in pp settings.

As for snatching. It's only searching for season packs and only on ipt... Enable a couple of other providers and try again.

**Comment by abeloin** [comment]
@kendog819 IPT is currently broken in sickrage when looking for multiple episodes as it search via season but IPT doesn't support partial searches. A fix is underway and will be available soon.

**Comment by kendog819** [comment]
@TagForce  I don't see any of those file types. I disabled the option anyways though. 

@abeloin Even though it says "FALLBACK EPISODE SEARCH INITIATED" and "Performing episode search for..." It isn't searching for the episodes? This all just stopped working yesterday.

**Comment by kendog819** [comment]
Ok, seems like Auto PP is working now =) 

@abeloin Is there a thread on the IPT issue I can keep my eye on?

**Comment by TagForce** [comment]
@kendog819 Either the files are there, or SR 'thinks' they are there... Maybe we should add an option to display which syncfiles are found in the log so we can debug them.

**Comment by TagForce** [comment]
@kendog819 https://github.com/SiCKRAGETV/SickRage/pull/1520 adds the syncfiles to the log.
It's based off of the current develop commits, so you can just replace the processTV.py with this one.

**Comment by kendog819** [comment]
@TagForce  Do I just update SR for that file to be replaced? Then turn back on the postpone option?

**Comment by TagForce** [comment]
No, it's not yet merged into develop... just download/edit that file only. Or patiently wait for @fernandog or @abeloin to merge and then update :) (it's only a very minor change that can be merged at any time)

**Comment by kendog819** [comment]
Yeah, I'm way too noobish to start messing with that. I think I better just wait till they merge it. I don't want to screw anything up :)

**Comment by abeloin** [comment]
@TagForce PR merged in develop

**Comment by kendog819** [comment]
![image](https://cloud.githubusercontent.com/assets/11353628/6582412/a815ebb6-c733-11e4-98a9-c5dd76632325.png)

That seems to be working =)

**Comment by kendog819** [comment]
When is it ok for me to switch back to Master?

**Comment by fernandog** [comment]
@kendog819 any time you want. But this fix will be not there until sunday

**Comment by TagForce** [comment]
@kendog819 Is the folder the downloads go into also the folder where incomplete downloads go?
You should seperate those in your download client.
You should have the following folders:
- an incomplete folder where files go that are still downloading
- a complete folder where completed downloads are put by your downloadclient
- a tvshows folder where your episodes vget transferred to by SR.

This keeps the files SR will process clean. Less chance of errors because of incomplete files.

**Comment by kendog819** [comment]
The Transmission folders are inside of my Downloads folder. The incomplete go to transmissions incomplete folder.

I will try setting up a location outside of the actual downloads folder though.

Thank you guys so much, @fernandog  @TagForce  @abeloin

**Comment by TagForce** [comment]
That's why PP will never run. There's always some file with a .part extension because it tries to PP incomplete folders as well.

You're very welcome
