### ISSUE TITLE
[Feature Request] Add thesportsdb.com indexer

### ISSUE THREAD

**Issue by Vodka2014** [SiCKRAGETV/sickrage-issues#872]
Hi All

This is not really an Issue i just want to know how to add new Indexes to SickRage for sports like F1:

http://www.thesportsdb.com/league/4370

Thanks

**Comment by Vodka2014** [comment]
Thanks fernandog :)

**Comment by fernandog** [comment]
Its not our priority. also there is  a lot of FR and 2-3 dev

**Comment by Vodka2014** [comment]
Sure whenever you get time to make the changes just hope before the 2016 Season :) 

In the mean time ppl can check out - http://forum.kodi.tv/showthread.php?tid=96518 for the content that has been sorted out. if anyone is interested (if this post is allowed :) )

**Comment by neoatomic** [comment]
@Vodka2014 Just took a look, they have API support so it should be possible.
However if i read the forum correct they are expecting a donation for the API key. (Witch the Sickrage developers need to get it working.)

http://www.thesportsdb.com/forum/viewforum.php?f=6

That could complicate things....

**Comment by Vodka2014** [comment]
@neoatomic Thanks looks like i miss read some thing some where.

So if they want a donation then will there be a place on SickRage to add in the creds ?.I will take a look and reply back on what they give me to use for the API. (Not The API Its Self)

**Comment by neoatomic** [comment]
@Vodka2014 When this is a good indexer (that works) and a lot of the Sickrage users want this added. Than we might consider adding this, but currently you are the only one requesting this and there is the donating issue.  If you could do a little more research and post the outcome it will help the developers making a decision in the future. But again at this point it is very unlikely that it will be added, at least any time soon...

**Comment by Vodka2014** [comment]
@neoatomic so i have had a chat to zag who is the admin on sports DB. i got an API now and he states it is free and unlimited to use. I am just waiting to find out if he is happy for this to go public as in for all sickrage users. Once i get this i will send you a msg with the API.

**Comment by neoatomic** [comment]
@Vodka2014 Thanks for your efforts.

However at this point it is way to early to request an api key from thesportsdb.
If in the future the developers decide to implement this, they will contact the responsible person them-selfs. Please relay this message to him and thank him for his willingness to help.
But it is nice to know that a donation is not explicitly required.

**Comment by Vodka2014** [comment]
Will do and i hope some time in the future this is added to the Index.

**Comment by Vodka2014** [comment]
@neoatomic so zag stated we can add it to the Index.  But like you stated this may take time, I will check this out as well to see if i can add it some how in Dev.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
