### ISSUE TITLE
[APP SUBMITTED]: u'[HD-Episode].Unbreakable.Kimmy.Schmidt.S01E02.720p.WEBRip.x264-2HD.[SEEDERS.(1)/LEECHERS.(0)]'

### ISSUE THREAD

**Issue by nytemyst** [SiCKRAGETV/sickrage-issues#873]
### INFO
Python Version: **2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2008ServerR2-6.1.7601-SP1**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@a0043e2d8fa3168b7d3bc1a414b8ae2bf10e9206
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Transmit] :: Error while searching Transmit, skipping: [HD-Episode].Unbreakable.Kimmy.Schmidt.S01E02.720p.WEBRip.x264-2HD.[SEEDERS.(1)/LEECHERS.(0)]
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@nytemyst what is Transmit ?!

**Comment by fernandog** [comment]
@neoatomic is this issue from sickgear? don't know what transmit is

**Comment by neoatomic** [comment]
@fernandog Its probably a custom provider. He just named it Transmit.?

@nytemyst Please post a full log and screenshot with the settings of this provider. 
With only the error we cant do anything...

**Comment by nytemyst** [comment]
it is a custom provider and I'm not showing anything else in the logs for this error. The provider is working it just was just that one time error so far. I was hoping by submitting it'll give more information then what the screen showed but i guess not. I wouldn't sweat this.

**Comment by neoatomic** [comment]
@nytemyst As you cant provide any more info, and we cant troubleshoot this without it, I'm going to close this issue.

**Comment by fernandog** [comment]
With you provide full logs (with the above error in it) we can reopen issue
