### ISSUE TITLE
[Feature Request] Add Torrentz.eu provider

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#874]
Simple feature request ,add torrentz.eu as a torrent provider 

This project (a lightweight sickbeard for torrent) could be used as a base ( https://github.com/tax/snor ) it has torrentz.eu as a sonely provider and its license allows copying ,modifing, etc

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
