### ISSUE TITLE
FR - Scan folder for missing episodes

### ISSUE THREAD

**Issue by ugokanain** [SiCKRAGETV/sickrage-issues#876]
Would be nice to have the option to have SR scan a folder to see if you are missing any episodes. Ideally it should be able to use the directory name for the show (big_show/01x01), as well as the file. This because it is nice to remove the show name from the file, since it can be a rather long title. 

I usually keep the archived apart from the current, so you would need to either ignore the tail or allow to scan multiple folders. The other option is to have a date range for which no action is taken (i.e. don't fetch shows that were aired within 1 or 2 weeks)

You can do this by hand, but it is a pain. It can be a chore if you have a bunch of shows, and usually get a headache .

**Comment by neoatomic** [comment]
I'm reading your request but i'm not sure what you exactly want. There is already a button "Re-Scan" to scan all the files in your folder.

**Comment by ugokanain** [comment]
Rather than scanning if the files are in for any show, I meant to scan for any missing episodes for all shows. Sometimes the episode monster eats some shows, some abscond or simply go missing. Some shows are easy to see if you skipped an episode, but some don't have any continuity between episodes.

I search occasionally to see all shows are there, but would be nice if SR could search each folder to make sure all episodes for that show are there.

**Comment by neoatomic** [comment]
@ugokanain Sorry but i'm still a little confused what you are requesting. :( 

SickRage does scan your folders from time to time to see if episodes are missing. And if they are missing it sets them to your preferred status. (archived/skipped/ignored etc.)
If you want to scan all folders yourself you can go to Massupdate and select rescan to scan all folders at once.
Also all shows that still need to be downloaded you can find under "Backlog overview"
And last there are the process bars on the show page where you can see how many % of all episodes you have.

**Comment by fernandog** [comment]
@ugokanain 
use the http://lcalshost:8081/manage/episodeStatuses/

find ep by status.
take care. the second action changes the status

**Comment by ugokanain** [comment]
No not same.

I have all my  shows in a separate disk. For whatever reason, some episodes go missing. It would be nice if SR could delve into the drive and make sure all the shows are complete (not only downloaded).

That way SR could generate a list of the missing episodes and ask you if you want to download these again. Since SR named these files, all it would need is do a listing of each show and compare it against the show info. Any episode not in the folder, it would be added to the list to download those shows.

It is just a little housekeeping, but it takes a while if you have many episodes

**Comment by fernandog** [comment]
If you mass refresh, missing episodes will be set to SKIPPED. Go to manage ep status and see them
