### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by ryanf86** [SiCKRAGETV/sickrage-issues#877]
### INFO
Python Version: **2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]**
Operating System: **Darwin-14.1.0-x86_64-i386-64bit**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@a0043e2d8fa3168b7d3bc1a414b8ae2bf10e9206
Link to Log: https://gist.github.com/8649c87f75fd016833d3
### ERROR
```
Thread-87 :: Failed doing webui callback: Traceback (most recent call last):
  File "/Users/ryanfoyle/SickRage/sickbeard/webserve.py", line 257, in async_call
    result = function(**kwargs)
  File "/Users/ryanfoyle/SickRage/sickbeard/webserve.py", line 3593, in index
    return t.respond()
  File "/Users/ryanfoyle/SickRage/cache/cheetah/_Users_ryanfoyle_SickRage_gui_slick_interfaces_default_config_general_tmpl.py", line 1039, in respond
    for cur_branch in VFFSL(SL,"gh_branch",True): # generated from line 582, col 10
TypeError: 'NoneType' object is not iterable

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@ryanf86 what you were doing? What is the steps  to reproduce?

**Comment by ryanf86** [comment]
Went to settings then general. Once I clicked on general I am redirected back to the shows page

**Comment by fernandog** [comment]
I think GITHUB is having issues

**Comment by abeloin** [comment]
PR merged

**Comment by fernandog** [comment]
@ryanf86 please update

**Comment by fernandog** [comment]
@ryanf86 please update and report back. otherwise will close

**Comment by ryanf86** [comment]
Have updated and is now working correctly

**Comment by OmgImAlexis** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-57-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@e1bf8412922d898878e98e5f4466492eb39c4456
Link to Log: https://gist.github.com/a71fb3074ec9a07a634e
### ERROR
```
SEARCHQUEUE-MANUAL-74768 :: [BitCannon] :: Error while searching BitCannon, skipping: 'NoneType' object is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by OmgImAlexis** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-57-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@e1bf8412922d898878e98e5f4466492eb39c4456
Link to Log: https://gist.github.com/18089bf3a989a5fffe46
### ERROR
```
SEARCHQUEUE-BACKLOG-296497 :: [BitCannon] :: Error while searching BitCannon, skipping: 'NoneType' object is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by OmgImAlexis** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-57-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@e1bf8412922d898878e98e5f4466492eb39c4456
Link to Log: https://gist.github.com/b3e691d8f73bacd942c8
### ERROR
```
SEARCHQUEUE-MANUAL-296497 :: [BitCannon] :: Error while searching BitCannon, skipping: 'NoneType' object is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by OmgImAlexis** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-57-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@e1bf8412922d898878e98e5f4466492eb39c4456
Link to Log: https://gist.github.com/e796a8faee0a8715905d
### ERROR
```
SEARCHQUEUE-MANUAL-296497 :: [BitCannon] :: Error while searching BitCannon, skipping: 'NoneType' object is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-30-generic-i686-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@5e2a794d903eb4c382b69a00890d8c36f67a2e9e
Link to Log: https://gist.github.com/88f0cb2a64d3e6f7ccf3
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: 'NoneType' object is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by didyouexpectthat** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-2.6.32-40-pve-x86_64-with-debian-8.2**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@30435190ef8880901df555bcda0d46902ea81fb5
Link to Log: https://gist.github.com/f573b9819a56f9c4bd78
### ERROR
```
Thread-50 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/share/sickrage/sickbeard/webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "/usr/share/sickrage/sickbeard/webserve.py", line 2152, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/usr/share/sickrage/sickbeard/processTV.py", line 268, in processDir
    process_media(processPath, videoInRar, nzbName, process_method, force, is_priority, result)
  File "/usr/share/sickrage/sickbeard/processTV.py", line 555, in process_media
    result.result = processor.process()
  File "/usr/share/sickrage/sickbeard/postProcessor.py", line 1083, in process
    cur_ep.downloadSubtitles(force=True)
  File "/usr/share/sickrage/sickbeard/tv.py", line 1458, in downloadSubtitles
    self.subtitles, newSubtitles = subtitles.downloadSubtitles(subtitles_info)
TypeError: 'NoneType' object is not iterable

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by didyouexpectthat** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-2.6.32-40-pve-x86_64-with-debian-8.2**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@30435190ef8880901df555bcda0d46902ea81fb5
No Log available with ERRORS: 
### ERROR
```
Thread-28 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/share/sickrage/sickbeard/webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "/usr/share/sickrage/sickbeard/webserve.py", line 2152, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/usr/share/sickrage/sickbeard/processTV.py", line 273, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/usr/share/sickrage/sickbeard/processTV.py", line 555, in process_media
    result.result = processor.process()
  File "/usr/share/sickrage/sickbeard/postProcessor.py", line 1083, in process
    cur_ep.downloadSubtitles(force=True)
  File "/usr/share/sickrage/sickbeard/tv.py", line 1458, in downloadSubtitles
    self.subtitles, newSubtitles = subtitles.downloadSubtitles(subtitles_info)
TypeError: 'NoneType' object is not iterable

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@medariox fix is in develop only?
