### ISSUE TITLE
set episodes as wanted on paused show starts backlog and dl

### ISSUE THREAD

**Issue by djack42** [SiCKRAGETV/sickrage-issues#878]
On a tvshow page, setting one or many episodes to wanted (from ignored, archived or anything else was set as default for new episodes) starts the backlog disregarding the paused status.
I end up having the downloads starting and that should not be the case for a paused show.

Also That would be great if the config page had a preformatted version info for creating an issue, even better, a button filling the clipboard or sending directly to a git preformatted issue creation page.
And if the others config pages had the submenu to access on the first config page.

SR Version:	BRANCH: (master) / COMMIT: (495b040ffadd5386f52f343bba13dfb017a92035) 
Python Version:	2.7.1 (r271:86832, Feb 20 2015, 08:10:01) [GCC 4.8.3 20140401 (prerelease)]

**Comment by fernandog** [comment]
isn't the correct ? if you set as WANTED, you want it.

**Comment by djack42** [comment]
Yes, wanted, but in this case, it's ready to download as soon as i unpause the show. not right now
Tell me how it's done when the default for new episodes is wanted, but the show is pausee. Is it downloading automaticaly when a new episode is released ? I don't think so !
A paused show means no downloads, we should be able to change episode states without triggering a snatch.
the setting pause should take precedance, if i want to downlod some episodes for a paused show, i hit the search button of the episode.
It's not that big of a deal, but it happened to me a few times and it's a bit annoying when it's unwanted

**Comment by fernandog** [comment]
no automatic downloads. will mark this as FR

**Comment by djack42** [comment]
Thx

**Comment by fernandog** [comment]
@TagForce what do you think?

**Comment by TagForce** [comment]
@fernandog I'll see if I can add a check to set_status in webserve.py... If it's paused then don't add it to backlog, and just set the ep to wanted.

**Comment by TagForce** [comment]
@djack42 @fernandog 
https://github.com/SiCKRAGETV/SickRage/pull/1504

**Comment by fernandog** [comment]
merged
