### ISSUE TITLE
[APP SUBMITTED]: Cannot find attribute 'rating'

### ISSUE THREAD

**Issue by krash1220** [SiCKRAGETV/sickrage-issues#880]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca**
Branch: **master**
Commit: SiCKRAGETV/SickRage@495b040ffadd5386f52f343bba13dfb017a92035
Link to Log: https://gist.github.com/c5f5b44efbf2243d4123
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: Cannot find attribute 'rating'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
Duplicate https://github.com/SiCKRAGETV/sickrage-issues/issues/867

This is fixed in develop and will be in master soon.
