### ISSUE TITLE
Raspberry Pi crashes when using SickRage

### ISSUE THREAD

**Issue by koper89** [SiCKRAGETV/sickrage-issues#881]
Hi, 
I have strange problem lately (since about 2 months) - my Raspberry Pi keeps freezing after using sickrage. I'm using it on xbian system (www.xbian.org) - My version of Python 2.7.3.
Firstly I thought my system is crashing cause of xbian - below link with screenshot how it looks like:
http://forum.xbian.org/thread-2693-post-26701.html#pid26701
Then i thought if maybe my raspberry Pi is corrupted - and i bought raspberry Pi 2, now on fresh install I installed sickrage - and i still got freezes, but now nothing on screen. I tried with rtorrent on and sickrage off and my raspberry Pi is stable, but as soon as I turn on sickrage it's working for awhile - f.e. 2-3hours then crashes my whole system, and i need to hard reset it. I searched in sickrage logs but there's nothing strange in them it just crashes in the middle of something (every time something else so this is not a cause). I tried on newest master and development branch got problem on both. I can give some dev ssh access if it'll help the problem. 
Here's my config:
http://pastebin.com/QkLs2GK7

**Comment by fernandog** [comment]
@koper89 I used to have this problems. RPI was killing python.exe because it was out of memory.

SSH and run this:
```
sudo grep "Out of memory" /var/log/syslog
```

if you find a lot you need to adjust your pi memory

**Comment by koper89** [comment]
What you mean by adjust? And its not killing python its freezing, the only thing i can do is plug off rpi and plug in once again.

**Comment by fernandog** [comment]
@koper89 did you run that command? post the output please

**Comment by koper89** [comment]
Don't have syslog in /var/log

**Comment by fernandog** [comment]
locate syslog file in your OS

**Comment by koper89** [comment]
I've got only dmseg

**Comment by fernandog** [comment]
openelec, xbian, raspbmc or osmc?
you have to google or consult the developer of the OS to check the syslog

**Comment by koper89** [comment]
xbian, got no syslog embeded - as i said i installed it now and waiting for crash.

**Comment by fernandog** [comment]
check with xbian develops where an error of Out of Memory is logger

**Comment by koper89** [comment]
But if it would be out of memory i suppouse it would just kill process, but it's freezing whole kernel in my case.

**Comment by fernandog** [comment]
I depends how OOM Killer is set. 

search google for: linux oom killer freeze kernel

**Comment by fernandog** [comment]
@koper89 please try this:

Set "CPU throttling" to HIGH in /config/general/ Advanced settings tab

**Comment by koper89** [comment]
Tried it, but still with the same result.

**Comment by fernandog** [comment]
I'm certain is an out of memory error.
Try to increase your search frequency to 12 hours. Just a test

also try to check syslog or where your OS stores the out of memory errors

**Comment by fernandog** [comment]
@koper89 any updates?

**Comment by koper89** [comment]
Hi,
I'm using xbian installed on btrfs partition on external hdd. You may be right about OOM here's my output before freeze:
Mar 7 15:23:10 xbian kernel: <30>[ 24.876932] udevd[1114]: starting version 175
Mar 7 15:23:10 xbian kernel: [ 25.335103] bcm2708_spi bcm2708_spi.0: master is unqueued, this is deprecated
Mar 7 15:23:10 xbian kernel: [ 25.335606] bcm2708_spi bcm2708_spi.0: SPI Controller at 0x3f204000 (irq 80)
Mar 7 15:23:10 xbian kernel: [ 25.400182] bcm2708_i2c_init_pinmode(1,2)
Mar 7 15:23:10 xbian kernel: [ 25.400203] bcm2708_i2c_init_pinmode(1,3)
Mar 7 15:23:10 xbian kernel: [ 25.400711] bcm2708_i2c bcm2708_i2c.1: BSC1 Controller at 0x3f804000 (irq 79) (baudrate 100000)
Mar 7 15:23:10 xbian kernel: [ 25.572035] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0x45E1
Mar 7 15:23:10 xbian kernel: [ 25.807001] pcm512x 1-004d: Failed to reset device: -5
Mar 7 15:23:10 xbian kernel: [ 25.807049] pcm512x: probe of 1-004d failed with error -5
Mar 7 15:23:10 xbian kernel: [ 25.807197] pcm512x 1-004c: Failed to reset device: -5
Mar 7 15:23:10 xbian kernel: [ 25.807226] pcm512x: probe of 1-004c failed with error -5
Mar 7 15:23:10 xbian kernel: <12>[ 31.875105] init: failsafe main process (512) killed by TERM signal
Mar 7 15:23:10 xbian kernel: <12>[ 35.713325] init: wait-for-state (xbmcxbmc-loaded) main process (1578) killed by TERM signal
Mar 7 15:23:10 xbian kernel: <12>[ 42.803300] init: xbmc-failed-start main process (930) killed by TERM signal
Mar 7 15:23:10 xbian kernel: <12>[ 42.829024] init: wait-for-state (zram-swapxbmc-done) main process (1275) killed by TERM signal
Mar 7 15:23:10 xbian kernel: [ 43.100164] Adding 84988k swap on /dev/mmcblk0p3. Priority:0 extents:1 across:84988k SSFS
Mar 7 15:23:10 xbian kernel: <12>[ 48.414153] init: rtorrent main process (2261) terminated with status 255
Mar 7 15:23:10 xbian kernel: <12>[ 48.414349] init: rtorrent main process ended, respawning
Mar 7 15:23:10 xbian kernel: <12>[ 48.505727] init: rtorrent main process (2350) terminated with status 255
Mar 7 15:23:10 xbian kernel: <12>[ 48.505895] init: rtorrent main process ended, respawning
Mar 7 15:23:10 xbian kernel: <12>[ 48.595088] init: rtorrent main process (2374) terminated with status 255
Mar 7 15:23:10 xbian kernel: <12>[ 48.595306] init: rtorrent respawning too fast, stopped

I'll try to collect more data now, my process loooks familiar to yours about 30% MEM and not much CPU usage.

**Comment by fernandog** [comment]
but when it start to search you get high cpu and mem

**Comment by pavelbenisek** [comment]
I agree with the memory-based incident, I was having the same problem on vmware guest lately with 1024MB of RAM assigned to the VM, after increasing the memory it works fine once again.
