### ISSUE TITLE
episodes keep standing on wanted

### ISSUE THREAD

**Issue by ikkeenjij36** [SiCKRAGETV/sickrage-issues#882]
Hi after reinstalling my syno and thus sickrage as well it dl 1 or 2 episodes from a serie and after that the rest are standing still at wanted and not get searched or put through to sabnzbd.
Is there anyway i can solve this?
I can manually search for episodes but i have more then a lot of episodes to be searche so not really a solution to do it all by hand.
Please advice on how to solve.
Thanks for this great prog by the way.

**Comment by fernandog** [comment]
Tell me your enabled providers

**Comment by ikkeenjij36** [comment]
Sickbeard provider,usenetcrawler,nzbgeek,nzbs2go,nzbsootie.
I hope those are enough/good enough?

**Comment by fernandog** [comment]
@ikkeenjij36 post full logs and follow guidelines: https://github.com/SiCKRAGETV/sickrage-issues
