### ISSUE TITLE
[Feature Request] "Send logs" button in viewlog

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#885]
I'm tired of asking for logs. Users don't read guidelines. It's easier to create a button that uploads the log to gist (if git user and pass). I will get at least 24hrs of logs (?) - if available

https://help.github.com/articles/working-with-large-files/
**Working with large files**
When pushing to GitHub, you'll receive a warning message if you add a new file or update an existing file larger than 50MB, and will be blocked from pushing files larger than 100MB.

@abeloin @TagForce 
thoughts? Agree? Disagree?

**Comment by abeloin** [comment]
https://help.github.com/articles/working-with-large-files/#files-to-consider-removing-from-git

**Comment by fernandog** [comment]
@abeloin should we change milestone to 4.0.15?

**Comment by neoatomic** [comment]
@fernandog At the Potato Couch issue tracker they use an BOT to auto comment to users that dont submit all info. Might also be an option.?

https://github.com/RuudBurger/CouchPotatoServer/issues

**Comment by fernandog** [comment]
@neoatomic we can think to use that in the future. thanks!

with this send log in gui we will try to decrease the number of issues opened directly in github.

**Comment by abeloin** [comment]
@fernandog Pushing back Milestone, too many issues this week.

**Comment by MGaetan89** [comment]
The "Submit errors" is available now. Can we close this?

Concerning the bot, it would be nice to also have one that auto-close PR made against `master`.

**Comment by miigotu** [comment]
This is for a full logs upload, not just for errors.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
