### ISSUE TITLE
 'ascii' codec can't encode character u'\u2019' in position 131

### ISSUE THREAD

**Issue by fferraro87** [SiCKRAGETV/sickrage-issues#887]
every hour (frequency to scan subtitles) i've this error : 

2015-03-08 11:40:45 FINDSUBTITLES :: Error occurred when downloading subtitles: 'ascii' codec can't encode character u'\u2019' in position 131: ordinal not in range(128)

http://pastebin.com/bC9HASrZ

i've this BRANCH: (master) / COMMIT: (495b040ffadd5386f52f343bba13dfb017a92035) 
Python 2.7.6
Ubuntu 14.04 LTS
i've set up scan and download subtitles on same video folder and i'm using opensubtitles and add7cted.com providers.

**Comment by fernandog** [comment]
Did you read this before opening a issue?

https://github.com/SiCKRAGETV/sickrage-issues

**Comment by abeloin** [comment]
Need a copy of the output of your locale.
`locale`
and
`locale -a`

**Comment by fferraro87** [comment]
http://pastebin.com/PThmzFca

**Comment by fernandog** [comment]
What about all others info?

**Comment by abeloin** [comment]
@fferraro87 More log needed as a one liner is rather slim. Also do you know the file name which it was searched?

**Comment by fferraro87** [comment]
http://pastebin.com/fe0t9BCM

**Comment by fernandog** [comment]
@fferraro87 

Need a copy of the output of your locale.
locale
and
locale -a

**Comment by fferraro87** [comment]
@fernandog i've already posted locale and locale -a output 
http://pastebin.com/PThmzFca

**Comment by fernandog** [comment]
@fferraro87 sorry!

can you SSH and run:
```
python
```

then
```
print(u'\2019')
```

do you get an error or does it show correctly?

**Comment by abeloin** [comment]
@fferraro87 Can you check the locale for the user running sickrage?

**Comment by fferraro87** [comment]
@fernandog print a square followed by a 9
this is pastebin http://pastebin.com/c0ejeAr5 but on pastebin there is a strange character. 
@abeloin i'm already post the output for locale

**Comment by abeloin** [comment]
Just to confirm the locale you posted is from the user running sickrage not your user on ubuntu?

**Comment by fferraro87** [comment]
@abeloin yes it's the user running sickrage

**Comment by abeloin** [comment]
Can you add this in between L354-355 of SickBeard.py:
```
        if sickbeard.SYS_ENCODING:
            logger.log(u"Using encoding: {0}".format(sickbeard.SYS_ENCODING), logger.DEBUG)
```
Stop sickrage before editing, send me the log at start up where a line like this is shown:
```
2015-03-08 15:14:45 DEBUG    MAIN :: Using encoding: UTF-8
```

**Comment by fferraro87** [comment]
this is log after added that line
http://pastebin.com/ckRrrTTr

**Comment by fernandog** [comment]
@fferraro87 there is no "Using encoding" in your log. please go to view log and enter "Using encoding" in the Search field. Post the result line

**Comment by fferraro87** [comment]
sorry but if i put Using encoding on search filter i've only these two lines:
http://pastebin.com/LV6Qpd7d

**Comment by fernandog** [comment]
@abeloin UTF-8

should be working

**Comment by abeloin** [comment]
@fferraro87 The location were you save the data, is it a mounted cifs, extra partition or on the same drive as sickrage?
Ref: `/home/hd13/*********/media/TVShows/How to Get Away with Murder/How to Get Away with Murder - 1x14 & 1x15 - The Night Lila Died & It’s All My Fault.mp4`

**Comment by fferraro87** [comment]
@abeloin it's the same drive where it is sickrage

**Comment by fernandog** [comment]
@fferraro87 what's subtitle provider you have enabled?

**Comment by fferraro87** [comment]
@fernandog opensubtitles and add7cted in this order

**Comment by fernandog** [comment]
@fferraro87 try enable only opensubtitles and see it works. then disable opensubtitles and enable only add7cted. Want to make sure it's not provider related

**Comment by fferraro87** [comment]
i've tried both solutions first only opensubtitles and after only add7cted but same error

**Comment by fernandog** [comment]
@abeloin what else can be causing this error?

**Comment by abeloin** [comment]
I don't know but I see it's maybe related to Ubunty distro has all the reports are using Ubuntu.

**Comment by TagForce** [comment]
@abeloin My production rig runs on Ubuntu 14.04 LTS, and I see none of those errors.
I'll go through my logs to make double sure.

**Comment by TagForce** [comment]
python
print(u'\u2019') prints a proper '

I'll add the show and download How to Get Away with Murder - 1x14 & 1x15 - The Night Lila Died & It’s All My Fault.mp4 (it's tripping on the apostrophe in It's... That's character \u2019)

**Comment by fernandog** [comment]
@Tagforce Mine does not print. It prints a square. using utf-8. Using raspbmc os (debian)

**Comment by TagForce** [comment]
@fernandog 
It should.. You need to type the command correctly :) There's two u's in it.
print(u'\u2019')
if you do print(u'\2019) it'll print a square with chinese characters in it with a 9 behind it.

**Comment by fernandog** [comment]
@TagForce  thanks!

```
>>> print(u'\u2019')
’
>>>
```

@fferraro87 can you run this command too?

**Comment by fferraro87** [comment]
i've same output of you
http://pastebin.com/xUEP7Xzk

**Comment by fernandog** [comment]
@fferraro87 can you post the contents of  /etc/default/sickbeard ?

**Comment by fferraro87** [comment]
@fernandog i've no access to this folder, i'm on a seedbox so i start sickrage entered on his folder (on my home folder) and do this python Sickbeard.py -p port

**Comment by fernandog** [comment]
@fferraro87 when you run "top", what's the user next to python Sickbeard.py -p?

**Comment by fferraro87** [comment]
@fernandog it's my user

**Comment by abeloin** [comment]
@fferraro87 What the underlying fs on the machine, you can check with `mount`?

**Comment by fferraro87** [comment]
this is output of python console:
http://pastebin.com/FUvk6je1
and this is mount output
http://pastebin.com/cmzhjZ5w
and
i'm on this:
/dev/sdx1 on /home/hd13 type ext4 (rw,noatime,nodiratime,errors=remount-ro,usrjquota=aquota.user,jqfmt=vfsv0,commit=120)

**Comment by abeloin** [comment]
@fferraro87 Can you replace lib/subliminal/videos.py by this one: https://github.com/abeloin/SickRage/blob/f7398e81a99ca3baf37068c2eaaeef02eeacfd87/lib/subliminal/videos.py
Stop sickrage before changing. And retry.

**Comment by fferraro87** [comment]
now i can't open sickrage anymore after this change

**Comment by abeloin** [comment]
What is the error message?

**Comment by fferraro87** [comment]
i don't know, i've 404 error on address of sickrage so i uninstall and reinstall but i've same error... (i've delete how to get away with murder so now i've different character problem 2015-03-11 14:53:30 FINDSUBTITLES :: Error occurred when downloading subtitles: 'ascii' codec can't encode character u'\xe2' in position 80: ordinal not in range(128) )

**Comment by abeloin** [comment]
Do you have the sickrage's log when to 404 error happened?

**Comment by fferraro87** [comment]
where i can find .log?

**Comment by abeloin** [comment]
In Sickrage folder, look for a Logs folder. Inside there should be all sickrage log files.

**Comment by fferraro87** [comment]
@abeloin nothing is written on log after shutdown and restart sickrage with new videos.py file...but also it's strange that my videos.py file is 10,7kb while yours is 126...my videos.py : http://pastebin.com/CgALXhGX

**Comment by fernandog** [comment]
@fferraro87 
Infos: 304 lines (253 sloc)  11.005 kb
https://github.com/abeloin/SickRage/blob/f7398e81a99ca3baf37068c2eaaeef02eeacfd87/lib/subliminal/videos.py

**Comment by fferraro87** [comment]
@fernandog so my videos.py is wrong?

**Comment by fernandog** [comment]
@fferraro87
Stop SR
open videos.py
erase all contents
copy all from https://raw.githubusercontent.com/abeloin/SickRage/f7398e81a99ca3baf37068c2eaaeef02eeacfd87/lib/subliminal/videos.py
paste
save
start SR

**Comment by fferraro87** [comment]
@fernandog with this new videos.py error is gone..now it works fine thanks for your support

**Comment by fernandog** [comment]
@abeloin

**Comment by abeloin** [comment]
@fferraro87 Please update sickrage to the latest version as a fix was pushed into master and develop

**Comment by fferraro87** [comment]
@abeloin ok thanks i've update now and it works, thanks again!
