### ISSUE TITLE
Unable to post process

### ISSUE THREAD

**Issue by Alexwijn** [SiCKRAGETV/sickrage-issues#888]
I'm trying to post process an episode of Forever but he is unable to find the show.

Postprocessing results
Processing folder /mnt/kodi/Downloads/Done
TV_DOWNLOAD_DIR: /mnt/kodi/Downloads/Done
PostProcessing Path: /mnt/kodi/Downloads/Done
PostProcessing Dirs: []
PostProcessing Files: ['Forever.S01E02.Look.Before.You.Leap.720p.WEB-DL.DD5.1.H.264-ECI.mkv']
PostProcessing VideoFiles: ['Forever.S01E02.Look.Before.You.Leap.720p.WEB-DL.DD5.1.H.264-ECI.mkv']
PostProcessing RarContent: []
PostProcessing VideoInRar: []
Processing /mnt/kodi/Downloads/Done/Forever.S01E02.Look.Before.You.Leap.720p.WEB-DL.DD5.1.H.264-ECI.mkv (None)
This show isn't in your list, you need to add it to SB before post-processing an episode
Processing failed for /mnt/kodi/Downloads/Done/Forever.S01E02.Look.Before.You.Leap.720p.WEB-DL.DD5.1.H.264-ECI.mkv: 
Problem(s) during processing

I also added "Forever" as Scene exception, before it was only "Forever US".

**Comment by fernandog** [comment]
Did you read https://github.com/SiCKRAGETV/sickrage-issues before open this issue?

**Comment by Alexwijn** [comment]
Latest version of master since I'm not allowed to use the develop branch and the OS is Raspbian. 

Anything else I'm missing?

**Comment by ripper1967** [comment]
a debug log https://github.com/SiCKRAGETV/sickrage-issues#enabling-detailed-debugging-for-logs

**Comment by Alexwijn** [comment]
Apparently after enabling debug mode and restarting he successfully processed it. Very weird. I guess he did not invalid the cache and did not had the scene without US.

**Comment by fernandog** [comment]
You are allowed to use. But only to confirm that a fix for your issue was succeeded.
