### ISSUE TITLE
Improve quality detection for MKV files

### ISSUE THREAD

**Issue by raymondtrueman** [SiCKRAGETV/sickrage-issues#889]
Currently when an MKV files is scanned when you add an existing show it will add them with quality "Downloaded:Unknown". Is there a way this can be improved to detect a proper quality like HDTV, 720p BluRay, Web-DL etc. I know its hard to detect this but maybe by using clever formulas on the size, length, bit rate etc. of the video file, a guess could be made on what the actual quality is. This would help a lot if your importing a large amount of episodes and want to set archive download qualities on them in order to replace bad quality files for example

**Comment by abeloin** [comment]
Sickrage use the filename to detect the quality:
`Black.Sails.S02E07.1080p.HDTV.x264-BATV`

**Comment by raymondtrueman** [comment]
Thanks @abeloin, I know it uses the file name, I have set my naming options to now name all files with the %QN parameter when post processing. But I have a large collection with mixed quality files and their file names were never saved to include the quality. SD files however are flawlessly labelled as "SD TV" when scanned, without any quality being specified in the file name, so it should be possible/partially possibly?

**Comment by crazyasyou** [comment]
I personally never want to see a sickrage feature that requires anything more than interrogation of the filename. 
This is for two reasons:
1, I’ve used different applications over the years that interrogate image, audio and video files in an attempted to get codec, length, bitrate and other information and find they cause disk trashing even on fairly small content libraries even when the data and application are local to each other.
2, My personal Sickrage deployment is remote from my video and metadata datastore (Internet VPN) simple directory, filename listing and move/rename commands are not an issue as minimal data needs to be transferred, interrogation of files would mean massive data transfer over my VPN.
My advice would be to use another tool that you run once to interrogate and rename your current library and then with your sickrage naming settings let that keep it I check.

**Comment by Ic3Nine** [comment]
I would let your media server do that job.  SR get the stuff for you and MS serves it up, for lack of a better term...

**Comment by neoatomic** [comment]
@fernandog Is this labeled incorrectly.? Dont really see a FR here. Close.?

**Comment by raymondtrueman** [comment]
@fernandog  I just thought it would be helpful, if you have a large library of files with no quality info in the filename. SickRage can then use some logic to make a guess of what the quality is. Also during post processing. But there is an existing request somewhere here suggesting using MediaInfo. #969 I think.
