### ISSUE TITLE
[APP SUBMITTED]: local variable 'fout' referenced before assignment

### ISSUE THREAD

**Issue by ripper1967** [SiCKRAGETV/sickrage-issues#890]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@495b040ffadd5386f52f343bba13dfb017a92035
### debug log  http://pastebin.com/6diWisUW
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: local variable 'fout' referenced before assignment
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Why did you close?

**Comment by abeloin** [comment]
Look at the commit number it's before the merge this morning.

**Comment by ripper1967** [comment]
i didnt have a visual c++ installed  it didnt compile correct, after i installed it the error went away..

**Comment by ripper1967** [comment]
i take it the time its is submitted goes by the time on my system? i just reloaded it and had the wrong time zone.

**Comment by ripper1967** [comment]
Had to pull from git couldnt update from web ui.,,

**Comment by fernandog** [comment]
what was the error while updating from UI?

**Comment by ripper1967** [comment]
there was no error it just told me no update needed, didnt notice it till Albeion mentioned the commit number.
http://pastebin.com/hxu4Ab82 so i just used git to pull the current commit we will see if it will update with the next commit..
