### ISSUE TITLE
Fanzub has closed

### ISSUE THREAD

**Issue by Thraxis** [SiCKRAGETV/sickrage-issues#893]
http://fanzub.com/ has shut down the provider for this service is no longer needed at this time.

The owner of the site is providing the source code and database as it was when he shut down so there is a possibility clone sites using the code may appear, and this provider may become of use again in the future.

**Comment by neoatomic** [comment]
@Thraxis Thank you for the notification. Could you keep an eye out if any clones appear.?

**Comment by fernandog** [comment]
@Thraxis we will remove it if nobody clone it

**Comment by abeloin** [comment]
Done with PR 1624
