### ISSUE TITLE
[APP SUBMITTED]: not a valid bencoded string

### ISSUE THREAD

**Issue by jiBYo** [SiCKRAGETV/sickrage-issues#894]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@558684cca7605dc4c2c3058d1f92e13f23881bd3
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: Deluge: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Do you have IPT provider?
You dont have enought seed ratio to download that torrrent.

**Comment by jiBYo** [comment]
I have enough.

Ratio: 3.32  Up: 1.15 TB  Dn: 355 GB

**Comment by fernandog** [comment]
Try to download that torrent directly from IPT
please send full logs in pastebin

**Comment by fernandog** [comment]
@jiBYo any news?
