### ISSUE TITLE
[APP SUBMITTED]: 'utf8' codec can't decode byte 0xb8 in position 1: invalid start byte

### ISSUE THREAD

**Issue by grimd34th** [SiCKRAGETV/sickrage-issues#895]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2]**
Operating System: **Linux-3.13.0-46-generic-x86_64-with-Ubuntu-14.04-trusty**
Branch: **master**
Commit: SiCKRAGETV/SickRage@558684cca7605dc4c2c3058d1f92e13f23881bd3
### ERROR
```
Thread-59 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 257, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 2445, in getTrendingShows
    shows = trakt_api.traktRequest("shows/trending?limit=50&extended=full,images") or []
  File "/opt/sickrage/lib/trakt/trakt.py", line 57, in traktRequest
    self.validateAccount()
  File "/opt/sickrage/lib/trakt/trakt.py", line 29, in validateAccount
    data=json.dumps(data), timeout=self.timeout, verify=self.verify)
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb8 in position 1: invalid start byte

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@grimd34th can you SSH and post the result of

```
locale
```

and

```
locale -a
```

**Comment by grimd34th** [comment]
###Locale
```
$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

###Locale -a
```
$ locale -a
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
POSIX
```

**Comment by fernandog** [comment]
@grimd34th how do you run SickRage?

**Comment by grimd34th** [comment]
using a conf in /etc/init

```
#Set username for the process. Should probably be what you use for logging in
setuid d34th

start on runlevel [2345]
stop on runlevel [016]

respawn

exec /opt/sickrage/SickBeard.py
```

**Comment by fernandog** [comment]
@grimd34th the user name from "locale" command is the same of SickRage user?

**Comment by grimd34th** [comment]
yes

**Comment by fernandog** [comment]
@gborri can you check this please?

**Comment by gborri** [comment]
@fernandog The point in the code that can generate a utf-8 error is:

```
resp = requests.request('POST', self.api_url+"auth/login", headers=self.headers,
                **data=json.dumps(data)**, timeout=self.timeout, verify=self.verify)
```
and the only var that can have special character is data in which there is:
```
        data = {
            'login': self.username,
            'password': self.password
        }
```

@grimd34th there is some special character in username or password?

**Comment by grimd34th** [comment]
@gborri no, there is not

**Comment by gborri** [comment]
@grimd34th hidden character? try to rewrite either username and password and save again

**Comment by grimd34th** [comment]
i deleted the full lines and retyped, still erroring

**Comment by gborri** [comment]
@grimd34th can you change the password on traktv and try with the new one?

**Comment by grimd34th** [comment]
I removed all the numbers from my password and it had worked, but now the api doesnt return any results

**Comment by grimd34th** [comment]
fixed it, had to re-enter the details in the UI versus adding it to the config.ini manually

**Comment by fernandog** [comment]
@gborri is there a way to fix so user can choose any type of chars in password?

**Comment by abeloin** [comment]
@grimd34th If you change back to your old password do you get the same error?

**Comment by grimd34th** [comment]
@abeloin yes

**Comment by abeloin** [comment]
Do you encrypt your passwords in config.ini?

**Comment by grimd34th** [comment]
I no longer do it though the config.ini i use thew webpanel

**Comment by abeloin** [comment]
So Encrypt passwords is checked in advanced settings?

**Comment by grimd34th** [comment]
yes

**Comment by abeloin** [comment]
Can you set "Encrypt passwords" unchecked, restart sickrage, make sure the password is ok and retry?

**Comment by grimd34th** [comment]
unencrypted the password works

**Comment by abeloin** [comment]
How long is your original password? Your password contain only A-Z and 0-9?

**Comment by grimd34th** [comment]
12 chars a-z A-Z 0-9

**Comment by abeloin** [comment]
Can you try the following:
* Encrypt the passwords again
* Stop sickrage
* In between line 26 and 27 of /opt/sickrage/lib/trakt/trakt.py", add the following:
`        logger.log("Trakt data variable is: {0}".format(str(data)),logger.DEBUG)`
* Start sickrage
* Look in the log for a line starting with `Trakt data variable is`
* Check if the password is the same from config.ini

**Comment by fernandog** [comment]
@grimd34th use the log search feature

**Comment by fernandog** [comment]
@grimd34th any news on this?

**Comment by grimd34th** [comment]
sorry about that, they seem to match with no invisible chars

**Comment by abeloin** [comment]
@grimd34th So to resume, when you disable encrypted password it work and when it is enable it doesn't. The password shown in the logger line(Trakt data variable is) is the same as the one which isn't encrypted.

**Comment by grimd34th** [comment]
correct

**Comment by abeloin** [comment]
@grimd34th Can you change the logger line from my previous line to:
`logger.log("Trakt data variable is: {0}, {1}, {2}".format(str(type(data)), str(type(self.username)), str(type(self.password))),logger.DEBUG)`
and give me the results when running with encrypted and not?

**Comment by abeloin** [comment]
@fernandog Why did you close this issue?

**Comment by fernandog** [comment]
@abeloin sorry! wrong closing.

**Comment by fernandog** [comment]
@grimd34th any news about this?

*Can you change the logger line from my previous comments to:*
```
logger.log("Trakt data variable is: {0}, {1}, {2}".format(str(type(data)), str(type(self.username)), str(type(self.password))),logger.DEBUG)
```
*and give me the results when running with encrypted and not?*
