### ISSUE TITLE
sickrage randomly closes after a couple of hours

### ISSUE THREAD

**Issue by totalfrenzy** [SiCKRAGETV/sickrage-issues#897]
Branch: Master
Commit Hash: 558684cca7605dc4c2c3058d1f92e13f23881bd3
OS: Debian 7.8
Python: 2.7.3
What I did: Seemed to start happening after moving back from dev verion (Issues with ipt). 
What happened: Sickrage randomly closes after ~1-2 hours
What I expected: That it doesn't close or at least leaves an error.
Specific Log: I cannot find anything in the log that might be causing this issue, however I've attached it anyway. http://pastebin.com/cTc2edtn

I've tried to Git reset to no avail. I'm yet to attempt reinstalling the entire thing.

**Comment by abeloin** [comment]
Look into your system's log, it should leave a trace when it crashed.

**Comment by totalfrenzy** [comment]
I'm unable to check the system logs because I'm on a shared seedbox. Which specific log should I be looking for so I can possibly request it? 

Would I be better off doing a reinstall in the meantime?

**Comment by abeloin** [comment]
Do you have the permission to install such software on a shared seedbox? As Sickrage can consume a lot of CPU and memory, it may be killed by the  vps or provider depending on the packages options you chosen.

**Comment by totalfrenzy** [comment]
Yeah they provide a script that sets it all up for us

**Comment by abeloin** [comment]
Is it a vps on a sharedbox or multiple users using on server? Because if it's vps you may be hitting a memory limit. Ask them if they can provide the log when sickrage closed unexpectedly.

Can you share the provider's name?

**Comment by totalfrenzy** [comment]
It's probably multiple users on the server provided by Feralhosting.

I'll make an effort to get the log.

**Comment by totalfrenzy** [comment]
Couldn't get a hold of the logs, but a reinstall/restore seems to have fixed it.
