### ISSUE TITLE
[APP SUBMITTED]: 'ascii' codec can't encode character u'\xc5' in position 47: ordinal not in range(128)

### ISSUE THREAD

**Issue by frederoni** [SiCKRAGETV/sickrage-issues#898]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2]**
Operating System: **Linux-3.13.0-46-generic-x86_64-with-Ubuntu-14.04-trusty**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@2df54608e079cd694766608d156568daa06ea471
Link to Log: https://gist.github.com/1454e18e755056ea09c1
### ERROR
```
FINDSUBTITLES :: Error occurred when downloading subtitles: 'ascii' codec can't encode character u'\xc5' in position 47: ordinal not in range(128)
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@frederoni 

can you SSH and post the results of:
please run these commands using  the same user which SR is using

```
locale
```
and 
```
locale -a 
```

**Comment by frederoni** [comment]
Absolutely @fernandog 
`$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=en_US.utf8`

`$ locale -a
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
POSIX`

**Comment by frederoni** [comment]
hm yea, there's the problem

**Comment by fernandog** [comment]
@abeloin why using ascii if is UTF-8 ?

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/887

**Comment by fernandog** [comment]
@frederoni how do you run SickRage? is it the same user of the command locale?

**Comment by abeloin** [comment]
@frederoni Can you check the user running sickrage?

**Comment by squareflapjack** [comment]
I have the same issue.
Raspberry Pi B+ running the latest version of Raspbmc.
BRANCH: (master) / COMMIT: (74e48176ebd63a89b2968f79b80c56e52e29dc24) 
SR Config file:	/opt/sickrage/config.ini
SR Database file:	/opt/sickrage/sickbeard.db
SR Cache Dir:	/opt/sickrage/cache
SR Arguments:	['--nolaunch']
SR Web Root:	
Python Version:	2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]

I have opensubtitles and addic7ed checked and searching for English subtitles.  I am in the Netherlands and using local timezone.

**Comment by abeloin** [comment]
@squareflapjack Please provide the sickrage user locale.

**Comment by frederoni** [comment]
@abeloin @fernandog I ran the locale command with the same user as sickrage. It only breaks with Swedish series containing åäö. I have Opensubtitles and Thesubdb enabled.

**Comment by squareflapjack** [comment]
locale

LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=

locale -a
C
C.UTF-8
POSIX

**Comment by abeloin** [comment]
@frederoni Are the result of the locale on sickrage user the same as the one you provided or different as you don´t mention it?

**Comment by abeloin** [comment]
@squareflapjack See the following http://raspberrypi.stackexchange.com/questions/19854/how-can-i-change-the-locale you need to install an utf-8 valid charset(eg: en_US.UTF-8) and use it for sickrage.

**Comment by frederoni** [comment]
@abeloin looks like changing SB_USER in the init script solved the problem but the process is still being reported running by the same user.

**Comment by squareflapjack** [comment]
ok did that
now i get 
locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

locale -a
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_COLLATE to default locale: No such file or directory
C
C.UTF-8
POSIX

**Comment by abeloin** [comment]
@squareflapjack You need to set LANGUAGE to `en_US.UTF-8` not `en_US:en`

**Comment by fernandog** [comment]
@frederoni can we close then?

**Comment by frederoni** [comment]
@fernandog yes

**Comment by abeloin** [comment]
@frederoni You change SB_USER from what to what?

**Comment by frederoni** [comment]
@abeloin it was not set (default)
I set it to my normal user and it is not reporting any errors now.
