### ISSUE TITLE
kickass.to search is broken

### ISSUE THREAD

**Issue by hoefs** [SiCKRAGETV/sickrage-issues#899]
https://kickass.to/usearch/Top.Gear+2015+03+08/?field=seeders&sorder=desc&rss=1

is not working and does not give any results...

2015-03-09 13:32:15 DEBUG    SEARCHQUEUE-BACKLOG-74608 :: [KickAssTorrents] :: Last update was too soon, using old cache: today()-2015-03-09 13:13:19<0:20:00
2015-03-09 13:32:15 INFO     SEARCHQUEUE-BACKLOG-74608 :: [KickAssTorrents] :: Performing episode search for Top Gear
2015-03-09 13:32:15 DEBUG    SEARCHQUEUE-BACKLOG-74608 :: [KickAssTorrents] :: Search string: https://kickass.to/usearch/Top.Gear+2015+03+08/?field=seeders&sorder=desc&rss=1
2015-03-09 13:32:15 INFO     SEARCHQUEUE-BACKLOG-74608 :: No needed episodes found during backlog search for: [Top Gear]

SR Version:	BRANCH: (master) / COMMIT: (558684cca7605dc4c2c3058d1f92e13f23881bd3) 
SR Config file:	/usr/local/sickbeard-custom/var/config.ini
SR Database file:	/usr/local/sickbeard-custom/var/sickbeard.db
SR Cache Dir:	/usr/local/sickbeard-custom/var/cache
SR Arguments:	['--daemon', '--pidfile', '/usr/local/sickbeard-custom/var/sickbeard-custom.pid', '--config', '/usr/local/sickbeard-custom/var/config.ini', '--datadir', '/usr/local/sickbeard-custom/var/', '--nolaunch']
SR Web Root:	
Python Version:	2.7.8 (default, Dec 12 2014, 20:09:05) [GCC 4.6.4]

**Comment by fernandog** [comment]
They are having issues with rss in past week. Please use RARBG instead

**Comment by hoefs** [comment]
@fernandog I have checked, the rss is working, but only when you use Air-By-Date is is not working!

**Comment by fernandog** [comment]
Rss dont support air by date anymore?

**Comment by hoefs** [comment]
Seems that air by date search is broken with kickass

**Comment by fernandog** [comment]
SR is doing wrong or RSS dont return air by date  correctly?

**Comment by hoefs** [comment]
SR is doing correctly I assume, but RSS is not returning anything

**Comment by fernandog** [comment]
can you keep checking this? if KAT will not allow air-by-date anymore we will need do remove it from the code

**Comment by abeloin** [comment]
Kat doesn't have any episode of Top Gear by air date:
https://kickass.to/usearch/Top%20Gear%202015%2003%2008/

Please uncheck Air by date in Top Gear config.
