### ISSUE TITLE
[Feature Request] Add provider status icon/message in "Provider Priorities" tab

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#900]
We can show a warning if the provider is down, or having some sort of issue or if is blocked so user can enable a proxy for it

additionally we can use that bunch of "isdown" websites to confirm it's not a local problem 
KAT was having rss issues in past week and with this status icon/message users can be aware of problems

@abeloin @TagForce @neoatomic @Hellowlol thoughts?

**Comment by TagForce** [comment]
@fernandog @abeloin @neoatomic @Hellowlol
I usually don't go into the provider priorities when something is not working. I check logs. Maybe we can add a more descriptive error message there rather than in the provider priorities page?

**Comment by Hellowlol** [comment]
Agreed, first place too look if there is a error should be the logs.

**Comment by neoatomic** [comment]
Like the idea, but not sure how you can make a reliable test for this on the users side.?
There are simply to many variables to consider when you want to implement this. Its not simply ping an IP.

Only thing i can think of is a "scrolling message" on top of the show list. (To push messages to the user)
We make a notification.txt on the SR github repository and add news messages we like to push. Example: 

"The Pirate Bay is currently down" 
"Develop is getting a large update, please switch to master"
"Please consider a donation"
"The rss feed of KAT is having problems.
"Happy New year!"
etc...

And might add a clear message to the log when SR has a (provider) timeout, 
that tells the users to try another proxy or check if the site is down/having problems.

**Comment by fernandog** [comment]
The problem ia that single timeout or a single error is not a big issue. The big issue is consecutive (same) problems

**Comment by fernandog** [comment]
@neoatomic https://github.com/SiCKRAGETV/sickrage-issues/issues/854

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
