### ISSUE TITLE
[APP SUBMITTED]: <urlopen error timed out>

### ISSUE THREAD

**Issue by hairyhippy** [SiCKRAGETV/sickrage-issues#902]
### INFO
Python Version: **2.7.8 (default, Dec 12 2014, 21:57:17) 
[GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Branch: **master**
Commit: SiCKRAGETV/SickRage@558684cca7605dc4c2c3058d1f92e13f23881bd3
### ERROR
```
SEARCHQUEUE-BACKLOG-251495 :: [Rarbg] :: Error while searching Rarbg, skipping: error timed out
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@rarbg anything has changed or minor issue with website?

**Comment by rarbg** [comment]
@fernandog 
Not an issue from this side :)

**Comment by hairyhippy** [comment]
@fernandog 

Here is debug log:
http://pastebin.com/YthBS8zp

**Comment by rarbg** [comment]
@hairyhippy  can you open the site at all ?

**Comment by hairyhippy** [comment]
@rarbg do you mean via a normal browser (e.g. in Chrome type the url rarbg.com)?  if so, no I can't today, could yesterday.

**Comment by rarbg** [comment]
@hairyhippy thats because you are using the old sickrage code that @CoRpO coded.
Unfortunately he was unaware that we have a bot protection , you were detected as bot and your ip was banned.
I will clear the bot protection history now , and you should be able to open the site / use sickrage until it detects you as a bot again. Please @hairyhippy tell me if you can open the site now and use the sickragetv search ?
As soon as the new api is implemented in sickragetv this wont happen. so @hairyhippy just update as soon as they implement it!

**Comment by fernandog** [comment]
@hairyhippy try this:
http://www.downforeveryoneorjustme.com/rarbg.com

What is your country?
try to access via any web proxy (google it)

**Comment by fernandog** [comment]
@rarbg we need a few days to change the code. 
i never had this issue and I only download from rarbg.
maybe @hairyhippy search frequency was too high

**Comment by hairyhippy** [comment]
@rarbg thanks

@fernandog get the following "It's just you. http://rarbg.com is up."  UK, can access via proxy.

**Comment by fernandog** [comment]
@hairyhippy read above comments please

**Comment by hairyhippy** [comment]
@fernandog I have, will wait on code and reduce frequency.  The defaults were:
Backlog search frequency 720
Daily search frequency 40

have doubled these.

**Comment by rarbg** [comment]
@hairyhippy 
From the uk you can use any of the public proxies or just use https://rarbg.com or if thats blocked https://rarbg.com:444/

**Comment by hairyhippy** [comment]
@rarbg do you mean within SR itself as neither working Chrome. Can access in Chrome via another proxy.

**Comment by rarbg** [comment]
@hairyhippy 
Lets move this outside sickrage because this is really an issue not related to sickrage. Please send an email to support@rarbg.com and you will get instant support , please include your ip address so the support can investigate your issue asap ( i notified them in advance )
