### ISSUE TITLE
[APP SUBMITTED]: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by thesmj** [SiCKRAGETV/sickrage-issues#903]
### INFO
Python Version: **2.7.3 (default, Apr 10 2012, 23:24:47) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@558684cca7605dc4c2c3058d1f92e13f23881bd3
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: coercing to Unicode: need string or buffer, NoneType found
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by thesmj** [comment]
The above happens whenever postprocessing is run. Started after running the auto updater yesterday afternoon.

**Comment by ripper1967** [comment]
link to debug log?

**Comment by thesmj** [comment]
Well, I shut down SR to enable debugging, enabled it and started it back up. Now it's working fine?

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/892
