### ISSUE TITLE
Unrar failed in Post Processing

### ISSUE THREAD

**Issue by henryclovin** [SiCKRAGETV/sickrage-issues#904]
Hello,

Python: 2.7.8
Operating system: FreeNAS 9.3

I repeatedly get errors from post processing saying "Unrar: No file to extract, file already exist?"

I can manually unrar the files via command line so unrar is working and installed correctly. Not sure where to go from here. Thanks for your help.

Logfile: http://pastebin.com/zucdLDNR

**Comment by henryclovin** [comment]
BRANCH: (master) / COMMIT: (74e48176ebd63a89b2968f79b80c56e52e29dc24)

**Comment by abeloin** [comment]
Usually an indication of permissions issue, the process was unable to extract any files in the directory. Check the parent folder permissions where archer.2009.s05e13.720p.bluray.x264-reward.rar is located and if sickrage user as write access to it.

**Comment by henryclovin** [comment]
Thanks! I changed the permissions for the parent folder and it works now. What about this error I still get? 

"Failed to set permission for /media/TVShows/Archer/Season 06/Archer (2009) - S06E03 - The Archer Sanction.mkv to 664"

**Comment by abeloin** [comment]
You see this error because sickrage user need to be the owner of the file to change the file mode and will fail if not.
If the file in the destination has the proper permissions then you can safely ignore this message.

**Comment by fernandog** [comment]
@abeloin can we check if is permission and show another log message instead of "Unrar: No file to extract, file already exist?" ?

**Comment by henryclovin** [comment]
@abeloin Ah ok. How would set the sickrage user or "media" in my jail to be the owner of the file? It is already in the group which owns the directory it is copying the files into. Not super important but if I could, I would like to get rid of the errors.

Thanks for your help!

**Comment by abeloin** [comment]
@henryclovin It depend on your permissions setup.

Usually people tend to simplify their setup by have the same user/group for their torrent/nzb client and sickrage. This way the owner stay the the same for processing the file. Also they set sgid on the parent download folder, so the group permission is inherited from the parent.

**Comment by abeloin** [comment]
@fernandog This is the error message from unrar source, the error is RARX_NOFILE. We could change the message to:
`Unrar: No file extracted, check the parent folder and destination file permissions.`

**Comment by fernandog** [comment]
@abeloin I think its better
