### ISSUE TITLE
[APP SUBMITTED]: [Error 183] Cannot create a file when that file already exists.

### ISSUE THREAD

**Issue by StitchFurbix** [SiCKRAGETV/sickrage-issues#905]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **null**
Commit: SiCKRAGETV/SickRage@
Link to Log: https://gist.github.com/588ca0ca97a750e6b204
### ERROR
```
Thread-77 :: Failed to create hardlink of E:\Shared\My Videos\new\seedbox\Marvels.Agents.of.S.H.I.E.L.D.S02E06.INTERNAL.720p.HDTV.x264-aAF\Marvel's Agents of S.H.I.E.L.D - 2x06 - A Fractured House.mkv at E:\Shared\My Videos\new\seedbox\Marvels.Agents.of.S.H.I.E.L.D.S02E06.INTERNAL.720p.HDTV.x264-aAF\Marvel's Agents of S.H.I.E.L.D - 2x06 - A Fractured House.mkv: error 183 : Cannot create a file when that file already exists.. Copying instead
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Are you using latest update? Your Branch is null

**Comment by fernandog** [comment]
@abeloin is this a confirmed issue?

**Comment by abeloin** [comment]
@fernandog The stack trace is useless as it was re-raised with `raise e` which cause python to start the stack trace from the raise. Pushed a PR to fix that: https://github.com/SiCKRAGETV/SickRage/pull/1534 So we need to cause the issue again.

@StitchFurbix Switch to the dev branch and try reprocessing the same file.

**Comment by StitchFurbix** [comment]
I wasn't but am now, I updated it and it's chugging along nicely

**Comment by abeloin** [comment]
@StitchFurbix Reopen the issue when you get that issue again
