### ISSUE TITLE
[APP SUBMITTED]: 

### ISSUE THREAD

**Issue by StitchFurbix** [SiCKRAGETV/sickrage-issues#906]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@495b040ffadd5386f52f343bba13dfb017a92035
### ERROR
```
Thread-41 :: Failed Unrar archive the.big.bang.theory.s08e01.the.locomotion.interruption.1080p.hdtv.x264-fihtv.rar: Unrar: Invalid Password
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
Your rar archive seems to be password protected
