### ISSUE TITLE
Update wont work, Stuck on comit 2d8aad80cdfb8

### ISSUE THREAD

**Issue by freddysmith1** [SiCKRAGETV/sickrage-issues#907]
for some strange reason ive managed to get stuck on BRANCH: (master) / COMMIT: (2d8aad80cdfb8983832206af445039de0decded9)   
Ive tried manual git pull  comes back and says already up to date, 
Ive tried changing it to dev branch using (git checkout develop)  comes back with already using dev
also still misssing the dev branch in settings  

What other commands are their to reset it or something?    using a synology

**Comment by fernandog** [comment]
did you tried update from gui? What was the error?

**Comment by TagForce** [comment]
git fetch origin
git pull

**Comment by freddysmith1** [comment]
tried updating from gui  
checked log and all i can see is
2015-03-10 21:17:14 INFO     Thread-57 :: Checking for updates using GIT

tried git fetch with no luck  says already up to date 
Diskstation> cd /volume1/@appstore/sickbeard-custom/var/SickBeard/
Diskstation> /volume1/@appstore/git/bin/git fetch origin
Diskstation> /volume1/@appstore/git/bin/git pull
Already up-to-date.

**Comment by TagForce** [comment]
Shutdown SR
Go into your config.ini and set the following values to "":
cur_commit_hash
cur_commit_branch

make sure the git_remote_url = https://github.com/SiCKRAGETV/SickRage.git

**Comment by freddysmith1** [comment]
have now got it to update,  for some strange reason one of the updates must of screwed it up,  its always been on master but it seem to think it was on dev branch,  a simple checkout master command finally worked 
SR Version:	BRANCH: (master) / COMMIT: (74e48176ebd63a89b2968f79b80c56e52e29dc24) 

but i still have no dev branch in the branch section...Bug? 
![no dev branch](https://cloud.githubusercontent.com/assets/8336824/6573744/d04446de-c76d-11e4-9cd5-896ed16eaf51.jpg)

**Comment by TagForce** [comment]
enter your github username and pass... It should add it.

**Comment by freddysmith1** [comment]
thanks for your helps , problem is now solved

**Comment by fernandog** [comment]
@freddysmith1 now you can use the "submit errors" button when an error happens. please do.

**Comment by freddysmith1** [comment]
@fernandog   have many times before, but had to resetup synology drive and forgot to readd those settings

**Comment by freddysmith1** [comment]
need help again,   without changing anything  i noticed i get this error now,
![no branch](https://cloud.githubusercontent.com/assets/8336824/6633529/fffa9d64-c999-11e4-9d59-29d86ad8a34e.png)

**Comment by fernandog** [comment]
SR couldnt connect to github or you have changed something in the code and now SR does not recognize it anymore.
