### ISSUE TITLE
[APP SUBMITTED]: 'ascii' codec can't encode character u'\u2019' in position 67: ordinal not in range(128)

### ISSUE THREAD

**Issue by nordika** [SiCKRAGETV/sickrage-issues#914]
### INFO
Python Version: **2.6.6 (r266:84292, Nov 27 2010, 19:47:39) 
[GCC 4.5.1]**
Operating System: **Linux-3.9.6p-unRAID-i686-Intel-R-_Core-TM-_i3-3220T_CPU_@_2.80GHz-with-slackware-13.1.0**
Branch: **master**
Commit: SiCKRAGETV/SickRage@019a8b363d65db598d85173d457fa40aed6328fc
Link to Log: https://gist.github.com/5dc562510dc8ab6208d5
### ERROR
```
FINDSUBTITLES :: Error occurred when downloading subtitles: 'ascii' codec can't encode character u'\u2019' in position 67: ordinal not in range(128)
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@nordika 


please post:
- user that runs SR OR
- post the contents of /etc/default/sickbeard
- post the result of this commands running as SR user:

```
locale
```
and
```
locale -a 
```

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/887

**Comment by abeloin** [comment]
@nordika Can you replace lib/subliminal/videos.py by this one: https://github.com/abeloin/SickRage/blob/f7398e81a99ca3baf37068c2eaaeef02eeacfd87/lib/subliminal/videos.py
Stop sickrage before changing. And retry.
