### ISSUE TITLE
[APP SUBMITTED]: sequence item 0: expected string, Language found

### ISSUE THREAD

**Issue by klutchrider** [SiCKRAGETV/sickrage-issues#916]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@019a8b363d65db598d85173d457fa40aed6328fc
### ERROR
```
Thread-46 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 257, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 1773, in setStatus
    sql_l.append(epObj.get_sql())
  File "C:\SickRage\sickbeard\tv.py", line 1977, in get_sql
    [self.indexerid, self.indexer, self.name, self.description, ",".join([sub for sub in self.subtitles]),
TypeError: sequence item 0: expected string, Language found

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@klutchrider what you were doing when the error happened?

**Comment by klutchrider** [comment]
@fernandog Just tried to snatch a subtitle, I will try to get it to reproduce and will update with logs if possible.

**Comment by fernandog** [comment]
@klutchrider any news on this?
