### ISSUE TITLE
Inconsistent required/ignored words (show vs global)

### ISSUE THREAD

**Issue by Toilal** [SiCKRAGETV/sickrage-issues#919]
There's an inconsistency in require words and ignore words.

When setting words globally, it is not possible to use regexp as input go through a `re.escape` call (https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/show_name_helpers.py#L64).

But when settings words on a specific show, it is possible because it is not escaped (https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/search.py#L194)

Problem is that I wan't to define globally a regexp to perform a OR condition on required words. (something like `\bfrench\b|\btruefrench\b|\bfr\b` to keep only series dubbed in french). If using simple commas, ALL words are required for the release to be snapped, and I only need a single word.

I could open a PR, there's three options:

1) Never escape regexps.
2) Add a "Use Regular Expression" checkbox for "required words" and "ignored words".
3) Use the same "Required words" filtering rule in global settings than show ("Results without one of these words in the title will be filtered out" instead of "results not containing all words in the comma separated word list will be ignored") 

Please tell me what option is the best, and i'll write the code. (I think option 3 is best, because easier, but it change the current behavior ...)

**Comment by fernandog** [comment]
@TagForce @abeloin thoughts?

**Comment by Toilal** [comment]
It seems to be AND in global settings, and OR in show settings, that's why it's inconsistent.

**Comment by Toilal** [comment]
If I set `french,truefrench,fr` in global settings, it filter out releases like "Some.Serie.S01E01.720p.FRENCH.XViD-SomeGroup", but if I set `french,truefrench,fr` in show settings, then it will keep it.

**Comment by TagForce** [comment]
@fernandog I'd not enable entering regex's to the acceptable input for req or ign words. Users are going to submit issues when they mess up their own.

I'd opt for changing the global AND to OR for required words. There needs to be at least one of the required words, just like ignored words only needs 1 to have a hit. That seems most logical to me, anyway.

**Comment by fernandog** [comment]
@TagForce agree

What I don't know is how PR prioritize global or show? What if they conflict?

**Comment by Toilal** [comment]
Current it checks show first, then global. I'll open a PR.

**Comment by Toilal** [comment]
PR is there https://github.com/SiCKRAGETV/SickRage/pull/1531
