### ISSUE TITLE
When moving files unable to parse causes follow on files in directory to fail

### ISSUE THREAD

**Issue by WebStizzle** [SiCKRAGETV/sickrage-issues#920]
I currently have SickRage set to rename and then move the files to the new directory.  After completion of a show with a file name that was unable to parse the rest of the files in the directory were skipped.  And after SickRage finished processing the other directories (Season 2 also had unparsed names) SickRage automatically deleted the Show folder including 6GB of unprocessed episodes.

I apologize here is the missing information:
Branch: (master) 
Commit: (019a8b363d65db598d85173d457fa40aed6328fc) 
Operating System: FreeBSD 10.0-RELEASE #0 r260789: Thu Jan 16 22:34:59 UTC 2014 
Python version: 2.7.9 (default, Jan 28 2015, 05:37:45) [GCC 4.2.1 Compatible FreeBSD Clang 3.3 (tags/RELEASE_33/final 183502)]

What happened: SickRage failed to parse a file name skipped the rest of the files in the season folder and then deleted the Show folder including all of the unprocessed shows.
What I Expected: SickRage to not delete a show folder that still contains unprocessed episodes and folders.

Paste Bin with Log excerpts.  I had to use the log search function for the Season 6 directory to see what was processed and then I searched for deleted to see what was deleted.
http://pastebin.com/eHCD7BUb

**Comment by fernandog** [comment]
Follow guidelines:
https://github.com/SiCKRAGETV/sickrage-issues

**Comment by WebStizzle** [comment]
Sorry about the confusion fernandog, I updated the original post with the missing information

**Comment by TagForce** [comment]
@WebStizzle Please post the full logs from the entire POSTPROCESSOR run. There are 2 instances of delete_folder, one of which should not delete folders if they have files in them, the other should not be called unless there's one of the following log entries before it:
- The directory name indicates it failed to extract.
- The directory name indicates that it was previously rejected for being undersized.

This means one of two things:
- SR encounters failed files in the folder, and deletes it anyway (shows in log)
- SR deletes the entire contents of the folder during the PP run because they are listed as unwanted files (which should not include any videofiles, but may include associated files like subs)

Seeing as you say it skips all the other files in the folder after it is unable to parse one episode, I think it's the latter, but I need the entire PP run to make sure it follows the correct path in the code.

**Comment by WebStizzle** [comment]
I had to use two pastebins, this is everything from when the post processor started on the show until the end, I took these directly from the SickRage log in the logs folder:
http://pastebin.com/hWzUHRiL

http://pastebin.com/syL42Sai

**Comment by TagForce** [comment]
@WebStizzle Thank you... I'll get right on it.

**Comment by WebStizzle** [comment]
Don't know if it will help either, but when the files first appeared they were all named like the unparsable files.  I used filebot and renamed the everything but 3 episodes that were duplicates/specials shortly after that was when sickrage rescanned and began auto processing them.  So it only seemed to happen when it encountered the misnamed file during actual processing, but not when all the files were misnamed.

**Comment by TagForce** [comment]
@WebStizzle I just tried a similar setup like yours...
Created a folderstructure like:
tbbt:
    -season 1
        - tbbt.s01e12.mp4
    -season 2
        - tbbt.s02e01.mp4
    -season 3
        - season 3 episode 1.mp4
    -season 4
        - tbbt.s04e01.mp4
    -season 5
        - season 5 episode 1.mp4
    -season 6
        - tbbt.s06e01.mp4

and it skips the folders that were not succesful. It then proceeds to the next folder.
In the end it will try to delete the folder tbbt, but encounters folders inside it, so returns false without deleting it...

I'll try it with multiple files in the folders, while leaving the unparsable ones, now. Which is basically exactly your setup.

**Comment by TagForce** [comment]
@WebStizzle I just did a new run, with multiple files in each folder, some of which were unparsable.

It only deleted the folders where it moved the files succesfully. All the folders that had unprocessed files were left.
Last thing it does is run PP on the base folder (ie 3rd rock from the sun in your case) and it found folders in them, so it didn't delete it.

Right now, the only thing I can think of causing this would be if the os.listdir(path) call on FreeBSD doesn't list folders, causing SR to think the folder is empty.

**Comment by WebStizzle** [comment]
@TagForce Thanks for looking into it, I tried recreating the issue.  With the manual post processor everything worked like I would expect.  The unparsed files stayed with directories/files intact.  The other files in those directories also stayed unprocessed.

But when I moved them back and waited for the automatic post processor to hit, the same thing as happened as with 3rd rock the directories with unparsed files were untouched until the final check on the main folder which again wiped them out:
2015-03-11 10:37:19 INFO     POSTPROCESSER :: Deleting folder: /downloads/completed/American Loggers
2015-03-11 10:37:18 WARNING  POSTPROCESSER :: Processing failed for /downloads/completed/American Loggers/Season 03/Episode 2.avi: 
2015-03-11 10:37:18 WARNING  POSTPROCESSER :: This show isn't in your list, you need to add it to SB before post-processing an episode

Running from a python prompt (2.7.9) this is what returns from os.listdir:
>>> os.listdir("/downloads/completed/American Loggers")
['Season 04', 'Season 01', 'Season 05', 'Season 02']
>>> os.listdir("/downloads/completed/")
['American Loggers', 'full']

So I am not actually sure what it is checking for, I tried looking at the post processing script, but I couldn't see anything that stood out to me.

**Comment by TagForce** [comment]
@WebStizzle 
Weirder and weirder... That it won't delete anything when it's manual PP is normal... It avoids deleting folders completely when type="manual" (which is set by running PP from the UI).

Just the fact that it lists the folder names should be enough for it to not delete the folder.

I've changed something in the delete_folder function... it uses os.rmdir(path) for deleting the folder when you want to check if it's empty. That should always fail if a folder is not empty...
It will show the following in the logs if the folder is not empty: 
14:36:41 WARNING::POSTPROCESSER :: Warning: unable to delete folder: C:\temp\bb\tbbt: error 145 : The directory is not empty

https://github.com/TagForce/SickRage/commit/cb0fdf5a4c35df9efa0c6d2574e74f83c58bd958
https://github.com/TagForce/SickRage/commit/73bf24fc945c7266b4d27919227479c30299f9cf

Can you add those two commits to your processTV.py and see if that gives you a clearer picture of what's happening? It should actually fix it...
Make a backup of your processTV.py file, though. This is just for testing.

**Comment by TagForce** [comment]
Add this one as well (removes a - at the start of the line for "if check_files" because I'm stupid)

https://github.com/TagForce/SickRage/commit/af92837f4b27a787f8415c6b0e36b7098bb38807

**Comment by WebStizzle** [comment]
Sorry about the delay, I tried manually typing in the changes at first because I was having trouble pulling the commit.  It didn't change the results so I forced the commit changes through the git pull and had the same results.

For a test I made seasons 1-6 I put 2 files in each folder S0XE01 and S0XE02 I then added an Episode 3 file to both season 3 and season 6.  The same results happened as before if the episode 3 file got read first none of the other files were copied over and they were all deleted.

http://pastebin.com/63rtsevi

**Comment by fernandog** [comment]
@TagForce squash all commit so he can patch -p1 < commit.patch

**Comment by TagForce** [comment]
https://github.com/TagForce/SickRage/commit/89b6ef1e7c47b7b650ecdf6403847982703981f8

Yeah, it got messy.

**Comment by TagForce** [comment]
@WebStizzle Make sure you get all the changes in processTV.py... Or replace the current one with the one from the above commit (has all the changes in it)
If they are all there and this is the output, then it runs the delete_folder using check_empty=False...
And that only happens when it finds folders that start with _FAILED_ or _UNDERSIZED_

**Comment by fernandog** [comment]
@WebStizzle

stop SR
SSH
enter SR directory
run:
```
wget -q --no-check-certificate https://github.com/TagForce/SickRage/commit/89b6ef1e7c47b7b650ecdf6403847982703981f8.patch
patch -p1 < 89b6ef1e7c47b7b650ecdf6403847982703981f8.patch
``` 
start SR

**Comment by TagForce** [comment]
@fernandog If he's changed processTV.py himself, he'll need to
git stash
git stash drop
first, otherwise the patch won't find the correct file contents to modify.

**Comment by WebStizzle** [comment]
@TagForce Sorry, it was past midnight and I have baby watch today.

After manually trying last night I did a git reset to reset my local before pulling via cherry-pick the commits from your repository.

After waking up I fetched and did another reset to get back to the base commit (019a8b363d65db598d85173d457fa40aed6328fc) and then pulled the latest commit change you had again 89b6ef1

The remainder of the episodes with unparsed names still remain unparsed, but the directory isn't removed which is great.

**Comment by TagForce** [comment]
Ok, it will never be able to parse those...
If it doesn't remove the folders I'll PR it later today.

**Comment by WebStizzle** [comment]
Understandable, I was only using those names since I knew they caused the original problem.  But as far as I can tell everything is working as it should now.  Thanks for the speedy help.

**Comment by fernandog** [comment]
merged

**Comment by fernandog** [comment]
@WebStizzle can you update to develop and report if the fix is working?

**Comment by WebStizzle** [comment]
@fernandog as far as I can tell it is working how it should be now.  It stops processing the rest of the folder once it hits one that wasn't able to be matched/parsed but leaves all the files intact.  Which is perfect because then I know to go fix the incorrect file if there is one.
