### ISSUE TITLE
Manual Search don't show finished message

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#921]
SR Version:	BRANCH: (develop) / COMMIT: (7089fa9ac0959195e9ba4e642b2b7ae410bbe512) 
SR User:	pi
SR Locale:	('pt_BR', 'UTF-8')
SR Config file:	/home/pi/SickRage/config.ini
SR Database file:	/home/pi/SickRage/sickbeard.db
SR Cache Dir:	/home/pi/SickRage/cache
SR Arguments:	['-q', '--daemon', '--nolaunch', '--pidfile=/var/run/sickrage/sickrage.pid', '--datadir=/home/pi/SickRage']
SR Web Root:	
Python Version:	2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]

@abeloin 
Manual Search don't show finished message and the spinning wheel is still spinning!

From log:
```
2015-03-11 09:56:19 INFO     SEARCHQUEUE-MANUAL-248742 :: Unable to find a download for: 
```

ended 09:56

but:

![2](https://cloud.githubusercontent.com/assets/2620870/6596754/0235611a-c7d6-11e4-9d10-42d4892a62df.png)

![3](https://cloud.githubusercontent.com/assets/2620870/6596748/f3da2c4a-c7d5-11e4-915f-98559ca35afe.png)

**Comment by fernandog** [comment]
@TagForce can you confirm please?

**Comment by TagForce** [comment]
@fernandog @abeloin Confirmed. Refreshing the page shows Snatched, but until then it keeps saying 'searching' and showing the busy-wheel.

**Comment by fernandog** [comment]
@TagForce @abeloin in my case I didn't received the ui.notification

**Comment by abeloin** [comment]
@fernandog @TagForce You get this issue in the comingEpisodes and backlog but not in displayShow? It's a known issue as there's no code to handle it, saw it when redoing the color status in displayShow.

I'm currently writing the code to handle that.

**Comment by TagForce** [comment]
@abeloin It won't update the image in DisplayShow for me.

**Comment by abeloin** [comment]
Look in the network tab in the developer tools, you should see a Get home/getManualSearchStatus?show=xxxx every 5 secs look at the returned json:
`{"episodes": [{"status": "Wanted", "episode": 8, "episodeindexid": 5129254, "season": 24, "searchstatus": "searching", "overview": "wanted", "quality": "Unknown"}], "show": "72454"}`
`{"episodes": [{"status": "Wanted", "episode": 8, "episodeindexid": 5129254, "season": 24, "searchstatus": "finished", "overview": "wanted", "quality": "Unknown"}], "show": "72454"}`

You should be able to see the progress. Do you get any error in the JS console?

**Comment by fernandog** [comment]
@abeloin @TagForce mine is in coming episodes page

**Comment by abeloin** [comment]
@fernandog @TagForce Fixed, please test.

**Comment by fernandog** [comment]
worked!
