### ISSUE TITLE
tv_episodes table column type

### ISSUE THREAD

**Issue by gborri** [SiCKRAGETV/sickrage-issues#924]
is it correct that *indexer* is TEXT type?

**Comment by fernandog** [comment]
@gborri what should be?

**Comment by TagForce** [comment]
@gborri Yes, that is correct. Whether or not it should be numeric is up for debate, I guess.

**Comment by fernandog** [comment]
@gborri  if we add another indexer like IMDB, it has the leading "tt", so can't be integer. Others may have string too

**Comment by TagForce** [comment]
@fernandog No, the 'other' column... The indexerid column already is numeric, so we'll run into that issue anyway. The indexer column tells us which indexer was used for that show (1 = tvdb, 2 = tvrage).

**Comment by fernandog** [comment]
ok! sorry

**Comment by gborri** [comment]
@fernandog if you like you can close this issue. it was strange for me. I run on this because i was making a merge procedure in order to change schema for my db due to check available function.
