### ISSUE TITLE
[APP SUBMITTED]: 'ascii' codec can't encode character u'\u2019' in position 68: ordinal not in range(128)

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#926]
### INFO
Python Version: **2.7.8 (default, Oct 20 2014, 15:05:29) 
[GCC 4.9.1]**
Operating System: **Linux-3.16.0-31-generic-i686-with-Ubuntu-14.10-utopic**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@7089fa9ac0959195e9ba4e642b2b7ae410bbe512
### ERROR
```
FINDSUBTITLES :: Error occurred when downloading subtitles: 'ascii' codec can't encode character u'\u2019' in position 68: ordinal not in range(128)
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by matigonkas** [comment]
Locale and locale -a
http://pastebin.com/Aur7580C

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/914

**Comment by abeloin** [comment]
@matigonkas Can you replace lib/subliminal/videos.py by this one: https://github.com/abeloin/SickRage/blob/f7398e81a99ca3baf37068c2eaaeef02eeacfd87/lib/subliminal/videos.py
Stop sickrage before changing. And retry.

**Comment by matigonkas** [comment]
@abeloin It seems to have fixed the issue
I believe the problem was with the banshee episode 3x09 "Even God Doesn’t Know What to Make of You" ,i replaced the file booted SR up and the subtiles for that episode pooped up without any issues :)

**Comment by fernandog** [comment]
@matigonkas thanks for replying!

**Comment by abeloin** [comment]
@fernandog It was merged for issues in Windows with logging error: https://github.com/SiCKRAGETV/sickrage-issues/issues/610. As it cause issue on Ubuntu's systems, I think it can be safely removed as we don't output log lines from subliminal in Windows anymore https://github.com/SiCKRAGETV/SickRage/pull/1388

**Comment by fernandog** [comment]
Ok. Go ahead and revert it. (Hotfix?)

**Comment by abeloin** [comment]
PR merged in master and develop: https://github.com/SiCKRAGETV/SickRage/pull/1540

**Comment by fernandog** [comment]
@matigonkas can you update and confirm ? thanks!

**Comment by matigonkas** [comment]
Just tested it by redownloading the supposed offending episode of Banshee 3x09 "Even God Doesn’t Know What to Make of You"  and his subtitles and didnt got errors ,so the fix worked @fernandog
