### ISSUE TITLE
Mede8er Metadata - episode metadata XML declaration

### ISSUE THREAD

**Issue by crazyasyou** [SiCKRAGETV/sickrage-issues#927]
First of all thanks for all the hard work and time you all put into this project, I don’t need a fix for this but want to bring it to your attention.
I'm not sure if this is something at fault due to my personal setup and I have self-corrected the issue with my very limited programing skills by 'hacking' at one of the python2.7 ElementTree files (ElementTree.py)

In summary for the mede8er devices to correctly display episode information the xml file must have the xml declaration <?xml version='1.0' encoding='utf-8'?> which is missing, I guess this is because generic.py only makes a call data.write(nfo_file, encoding="utf-8") and when ElementTree.py processes this the default xml_declaration=none will be applied. 

My 'hack' is dirty, I've simply changed the default in ElementTree.py to always be xml_declaration=True, as this is a dedicated sickrage server changing python directly has no impact on anything else, I took this route to correct my issue but also to ensure that when sickrage updates my hack is not overwriten, I've not testing changing generic.py to data.write(nfo_file, encoding="utf-8" xml_declaration=True) but I guess it would work and might be something that can be done as a commit providing it would not interfere with other types of metadata file creation.

**Comment by fernandog** [comment]
@TagForce can you check this please?

**Comment by TagForce** [comment]
@crazyasyou @fernandog I'll have a look if I can add this only for mede8er.
I don't myself own a mede8er, though. A colleague of mine does, so I fix the mede8er files according to his wishes :)

**Comment by crazyasyou** [comment]
@TagForce Thanks for taking a look, as I said I have my own fix in place that has been working well for many many months but I guess if it’s fixed globally other people will benefit.

**Comment by TagForce** [comment]
@crazyasyou Is this only needed for episode data? Or also for the show data?

**Comment by TagForce** [comment]
@crazyasyou Output should be something like the following?

series.xml:
```
<?xml version='1.0' encoding='utf-8'?>
<details>
  <movie isExtra="false" isSet="false" isTV="true">
    <title>The Big Bang Theory</title>
    <genres>
      <Genre>Comedy</Genre>
    </genres>
    <premiered>2007-09-24</premiered>
    <year>2007</year>
    <plot>What happens when hyperintelligent roommates Sheldon and Leonard meet Penny, a free-spirited beauty moving in next door, and realize they know next to nothing about life outside of the lab. Rounding out the crew are the smarmy Wolowitz, who thinks he's as sexy as he is brainy, and Koothrappali, who suffers from an inability to speak in the presence of a woman.</plot>
    <rating>92</rating>
    <status>Continuing</status>
    <mpaa>TV-PG</mpaa>
    <id moviedb="imdb">tt0898266</id>
    <indexerid>80379</indexerid>
    <runtime>30</runtime>
    <cast />
  </movie>
</details>
```

episodefilename.xml:

```
<?xml version='1.0' encoding='utf-8'?>
<details>
  <movie isExtra="false" isSet="false" isTV="true">
    <title>The Closet Reconfiguration</title>
    <season>6</season>
    <episode>19</episode>
    <year>2007</year>
    <plot>What happens when hyperintelligent roommates Sheldon and Leonard meet Penny, a free-spirited beauty moving in next door, and realize they know next to nothing about life outside of the lab. Rounding out the crew are the smarmy Wolowitz, who thinks he's as sexy as he is brainy, and Koothrappali, who suffers from an inability to speak in the presence of a woman.</plot>
    <episodeplot>Howard considers whether or not he should open a letter from his father; Penny and Leonard host a "grown-up" cocktail party.</episodeplot>
    <mpaa>TV-PG</mpaa>
    <rating>78</rating>
    <director>Anthony Rich</director>
    <credits>|Steven Molaro|Steve Holland|Eric Kaplan|</credits>
    <cast />
  </movie>
</details>
```

**Comment by crazyasyou** [comment]
sorry for the delay getting back to you, the above look good, it's really just a case of having <?xml version="1.0" encoding="utf-8"?> at the top of episodefilename.xml.

What is really bizzare is that series.xml is perfectly happy without it (something random in the mede8er code I guess)

**Comment by TagForce** [comment]
Ok, i'll add it for both. They don't seem to mind with it. My colleague's mede8er works fine without in either file and with it in both files.

**Comment by abeloin** [comment]
@TagForce PR Merged

**Comment by shadowjustice** [comment]
Hi,

I think  this fix is causing errors with me:

*Branch: Master*
Commit hash: 669046ea40a7a26a6121a1b07721f3c1c3cf5b10

*Hardware*: Excito B3
Operating system:
Distributor ID: Debian
Description: Debian GNU/Linux 6.0.8 (squeeze)
Release: 6.0.8
Codename: squeeze

*Python version*:
Python 2.6.6 (r266:84292, Dec 27 2010, 21:57:32)
[GCC 4.4.5 20100902 (prerelease)] on linux2

What did I do?
Auto processing, manual post processing

*What I expect?*
Message with prowl with the message that the video is downloaded and renamed and stuff...

*What do I get?*

AATypeError: write() got an unexpected keyword argument 'xml_declaration'
AA    data.write(nfo_file, encoding="utf-8", xml_declaration = True)
AA  File "/home/programs/programs/sickbeard/sickbeard/metadata/mede8er.py", line 438, in write_ep_file

**Comment by abeloin** [comment]
@shadowjustice Open a new issue and reference this one. Thanks
