### ISSUE TITLE
[FEATURE] Add minimum size

### ISSUE THREAD

**Issue by Alexwijn** [SiCKRAGETV/sickrage-issues#930]
Is it possible to add a feature to specify the minimum size of specific quality. Sometimes I see that he is downloading a 720p WEB-DL version but that it is only 150Mb. It probably has a resolution of 720p but the quality would not be the same as on a ~1.3Gb version.

**Comment by fernandog** [comment]
Check if the codec of thoses files are HEVC or h.265.
 If so add to ignore words
its a new codec that reduces file size with the same quality

**Comment by Alexwijn** [comment]
Yeah, they were. Thanks!

**Comment by fernandog** [comment]
Limit by size its not the best way. Correct is limit by codec.
will close this

**Comment by andyblac** [comment]
i am getting this swell but there not HEVC or h.265


```
Filename: Arrow.S02E01.720p.BluRay.350MB.ShAaNiG.mkv

Video
ID : 1
Format : AVC
Format/Info : Advanced Video Codec
Format profile : High@L4
Format settings, CABAC : Yes
Format settings, ReFrames : 5 frames
Codec ID : V_MPEG4/ISO/AVC
Duration : 42mn 28s
Nominal bit rate : 1 086 Kbps
Width : 1 280 pixels
Height : 720 pixels
Display aspect ratio : 16:9
Frame rate mode : Constant
Frame rate : 23.976 fps
Color space : YUV
Chroma subsampling : 4:2:0
Bit depth : 8 bits
Scan type : Progressive
Bits/(Pixel*Frame) : 0.049
Writing library : x264 core 133 r2334 a3ac64b
```

how can i stop these ?

**Comment by c0rnflex** [comment]
+1

**Comment by OmgImAlexis** [comment]
@Alexwijn please add this to [feathub](http://feathub.com/SiCKRAGETV/SickRage) as this issue tracker isn't being used for feature requests anymore.

@c0rnflex please don't comment on closed issues with `+1`.
