### ISSUE TITLE
[APP SUBMITTED]: [Error 32] The process cannot access the file because it is being used by another process: u'F:\\Media 4\\Downloading\\The.Killing.S02\\The.Killing.S02E09.HDTV.x264-ASAP.[VTV].Sayonara.Hiawatha.mp4'

### ISSUE THREAD

**Issue by guyleonard** [SiCKRAGETV/sickrage-issues#934]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@558684cca7605dc4c2c3058d1f92e13f23881bd3
Link to Log: https://gist.github.com/94003d7569ebc1a03e25
### ERROR
```
POSTPROCESSER :: Unable to move file F:\Media 4\Downloading\The.Killing.S02\The.Killing.S02E09.HDTV.x264-ASAP.[VTV].Sayonara.Hiawatha.mp4 to F:\TV_Shows_Shared\The Killing\Season 2\The Killing (US) - S02E09 - Sayonara Hiawatha.mp4: [Error 32] The process cannot access the file because it is being used by another process: u'F:\\Media 4\\Downloading\\The.Killing.S02\\The.Killing.S02E09.HDTV.x264-ASAP.[VTV].Sayonara.Hiawatha.mp4'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Please have on folder for incomplete and another to complete. You cant post-process the folder witch your torrent download saves the file

**Comment by guyleonard** [comment]
i do
files are downloaded to F:\Media 4\download_temp with !qB and then moved to F:\Media 4\Downloading with their proper extension..?

**Comment by fernandog** [comment]
Still seeding after moved?

**Comment by guyleonard** [comment]
Actually yes, and also some files seem to be entirely deleted after seeding happens. Maybe qBitorrent is acting up!

**Comment by fernandog** [comment]
So choose COPY instead of move or chose symlinks. 
OR
only move to PP folder when seeding is finished

**Comment by fernandog** [comment]
@TagForce confirm?

**Comment by TagForce** [comment]
@fernandog Correct :)

**Comment by fernandog** [comment]
@TagForce when this happen, can't we just copy or symlink as fallback?

**Comment by TagForce** [comment]
@fernandog I would copy, not symlink... As we don't know what the client does when seeding finishes.
If it removes the file the symlink would break.

**Comment by fernandog** [comment]
@TagForce what do you think adding a note in PP telling users to NOT use the download folder as the PP download?

**Comment by TagForce** [comment]
@fernandog Is not going to fix the problem...
If a torrent is seeding and it is active, at that time there will be an exclusive lock on it in Windows for most torrent clients, as the program is actively accessing the file.

It doesn't matter whether the file is in the incomplete folder or the complete folder, as long as it's seeding it runs the chance of being locked by the client.

I run a script that scans for and deletes any torrents in my client that have completed downloading, depending on the label. If it's a private tracker then it will leave it, if it's from a public tracker it removes it.

**Comment by fernandog** [comment]
@TagForce so we add another note in mode: don't use MOVE if you always seed your torrents

**Comment by TagForce** [comment]
@fernandog Yeah, using a different complete folder is best-practice though so leave that on in as well.

Note: Please use seperate downloading and completed folders in your download client if possible. Also, if you keep seeding torrents after they finish, please set Process Method to 'copy' instead of move to prevent errors while moving files.

On the other hand, it should skip the file and retry on the next PP run and if it's idle it'll work.

**Comment by fernandog** [comment]
OK!
