### ISSUE TITLE
Error: Unable to connect to rTorrent

### ISSUE THREAD

**Issue by sgtsquiggs** [SiCKRAGETV/sickrage-issues#936]
Hi,

I have rtorrent and sickrage running on my QNAP. I'd like for sickrage to communicate with rtorrent but that doesn't seem to work. I know that the scgi port is open and working, because the rutorrent GUI uses it, and it works fine.

I enable debug logging, but nothing seems to be logged for this.

**Comment by fernandog** [comment]
Follow guidelines: https://github.com/SiCKRAGETV/sickrage-issues
and print of your torrent settings

**Comment by sgtsquiggs** [comment]
Branch: master
Commit: 019a8b363d65db598d85173d457fa40aed6328fc
OS: QNAP's flavor of linux? it's x86, on a TS-807 Pro
Python: 2.7.3

SickRage torrent settings:
Send .torrent files to: rTorrent
rTorrent host:port: scgi://localhost:5000 (tried localhost:5000 too)
http auth: disabled
verify cert: enabled
rtorrent username/password: set properly
add label to torrent: sickbeard
add label to anime: anime
downloaded files location: empty


rTorrent settings:
a lot of things but also
scgi_port = 127.0.0.1:5000

**Comment by fernandog** [comment]
Read all this. See if helps
https://github.com/SiCKRAGETV/sickrage-issues/issues/625

**Comment by sgtsquiggs** [comment]
I'm using the scgi connection method and not http/https, so a self-signed certificate shouldn't be affecting it afaik

**Comment by fernandog** [comment]
Did you read all comments?

**Comment by sgtsquiggs** [comment]
yes, zero comments regarding scgi connections, all regarding httprpc via http or https

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/242#issuecomment-74566447

**Comment by sgtsquiggs** [comment]
Removing the username/password fixes the SCGI connection.

Seems it isn't needed unless you're going http.

Thanks @fernandog

**Comment by fernandog** [comment]
@abeloin should we add this info in UI?

**Comment by abeloin** [comment]
Yes, I'll add a js that will disable the field depending on what is selected

**Comment by fernandog** [comment]
@abeloin wrong reference here?

**Comment by abeloin** [comment]
yes, already fixed but the reference stayed, github limitation
