### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by dirkr07** [SiCKRAGETV/sickrage-issues#938]
### INFO
Python Version: **2.7.8 (default, Dec 12 2014, 22:18:04) 
[GCC 4.3.2]**
Operating System: **Linux-2.6.32.12-ppc-with-glibc2.0**
Branch: **master**
Commit: SiCKRAGETV/SickRage@019a8b363d65db598d85173d457fa40aed6328fc
Link to Log: https://gist.github.com/8f41d3161860aa98ead8
### ERROR
```
FINDPROPERS :: DownloadStation: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Not an issue. That torrent you are trying to download is buggy.
Try manually download it and add to torrent downloader.
