### ISSUE TITLE
[Feature Request] notification: gmail client with 2-step autentication

### ISSUE THREAD

**Issue by gborri** [SiCKRAGETV/sickrage-issues#939]
if gmail has been chosen as mail relay, the 2-step autentication wont work.

**Comment by Thraxis** [comment]
Not sure why this is needed.  Google already provides the ability to create App Specific Passwords to bypass the 2-factor authentication for specific devices or applications that don't support it.

https://security.google.com/settings/security/apppasswords

You can revoke the passwords from that page at anytime as well if it has been compromised
