### ISSUE TITLE
[APP SUBMITTED]: [Error 2] The system cannot find the file specified: u'F:\\TV_Shows_Shared\\The 100\\Season 2\\The 100 - S02E11 - Coup de Gr\xe2ce.nfo'

### ISSUE THREAD

**Issue by guyleonard** [SiCKRAGETV/sickrage-issues#941]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@558684cca7605dc4c2c3058d1f92e13f23881bd3
Link to Log: https://gist.github.com/ac9b8ea5400caea6195e
### ERROR
```
Thread-55 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 257, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 1306, in displayShow
    return t.respond()
  File "C:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_displayShow_tmpl.py", line 659, in respond
  File "C:\SickRage\sickbeard\helpers.py", line 1359, in get_size
    total_size += ek.ek(os.path.getsize, fp)
  File "C:\SickRage\sickbeard\encodingKludge.py", line 56, in ek
    result = func(*args, **kwargs)
  File "C:\Python27\lib\genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
WindowsError: [Error 2] The system cannot find the file specified: u'F:\\TV_Shows_Shared\\The 100\\Season 2\\The 100 - S02E11 - Coup de Gr\xe2ce.nfo'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@guyleonard can you explain what you were doing or what you did?

**Comment by guyleonard** [comment]
Ooops, yes! 

Clicking on the show name under the show list causes this error and returns you to the show list rather than the episode list, if there are any episode names where there is a letter with an accent e.g. 'Coup de Grâce' is the title of that episode, same occurs for other diacritics... Renaming the episode with an 'a' instead of an 'â' seems to get round the problem, but the episode was renamed with the 'â' by sickrage...

**Comment by abeloin** [comment]
Can you give us the result of running this in a command line:
`chcp`

**Comment by guyleonard** [comment]
Active code page: 850

**Comment by abeloin** [comment]
ok, in the same command line where you start sickrage, can you try `chcp 65001`.

It would look like this
```
c:\> chcp 65001
c:\> c:\python27\python.exe SickBeard.py --nolaunch
```

**Comment by fernandog** [comment]
@guyleonard please reply

**Comment by guyleonard** [comment]
Apologies, I was away on business.

```
Active code page: 65001

and

```
18:32:50 INFO::MAIN :: Trying to clean cache folder C:\SickRage\cache
18:32:50 INFO::MAIN :: Checking database structure...
18:32:50 INFO::MAIN :: Checking database structure...
18:32:50 INFO::MAIN :: Checking database structure...
18:32:50 INFO::MAIN :: No duplicate show, check passed
18:32:50 INFO::MAIN :: No duplicate episode, check passed
18:32:50 INFO::MAIN :: No orphan episodes, check passed
18:32:50 INFO::MAIN :: No UNAIRED episodes, check passed
18:32:50 INFO::MAIN :: No MALFORMED episode statuses, check passed
18:32:50 INFO::MAIN :: Loading initial show list
18:32:50 INFO::MAIN :: 269533: Loading show info from database
...
...
18:32:51 INFO::TORNADO :: Starting SickRage on http://0.0.0.0:8083/
18:32:51 INFO::DAILYSEARCHER :: Searching for new released episodes ...
18:32:51 INFO::CHECKVERSION :: Checking for updates using GIT
18:32:51 INFO::MAIN :: No scene exceptions update needed
18:32:51 INFO::MAIN :: Building internal name cache for all shows
18:32:51 INFO::BACKLOG :: Seeing if we need anything from Show X
...
...
18:32:54 INFO::DAILYSEARCHER :: No new released episodes found
...
18:32:54 INFO::SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
18:32:54 INFO::SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from Show Y
18:32:55 INFO::SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
18:32:56 INFO::POSTPROCESSER :: Successfully processed
18:32:57 INFO::SEARCHQUEUE-BACKLOG-70415 :: Beginning backlog search for: [Show Z]
18:32:57 INFO::SEARCHQUEUE-BACKLOG-70415 :: No scene exceptions update needed
18:33:03 INFO::SEARCHQUEUE-BACKLOG-70415 :: No needed episodes found during backlog search for: [Show Z
Starting up SickRage master from C:\SickRage\config.ini]

**Comment by abeloin** [comment]
@guyleonard Is it working?

**Comment by fernandog** [comment]
@abeloin can't we auto run "chcp 65001" inside SickBeard.py before anything using "os.system" when windows?

**Comment by abeloin** [comment]
@fernandog Not really as it's not stable in all Windows versions

**Comment by fernandog** [comment]
@guyleonard reply or we will close it

**Comment by guyleonard** [comment]
Changing the code page does seem to fix the issue, yes. I'll just add 'chcp 65001' before SickRage starts, thanks! :)
