### ISSUE TITLE
[APP SUBMITTED]: No module named pwd

### ISSUE THREAD

**Issue by copekyle** [SiCKRAGETV/sickrage-issues#952]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@d15e9e0bb698b02be5202a5b4255b69e02566e59
Link to Log: https://gist.github.com/dd33cf7aea219806d1ec
### ERROR
```
Thread-191 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\Users\Ktrain_Media\Sickbeard\SickRage\sickbeard\webserve.py", line 257, in async_call
  File "C:\Users\Ktrain_Media\Sickbeard\SickRage\sickbeard\webserve.py", line 3579, in index
    display_filesize=None, fuzzy_dating=None, trim_zero=None, date_preset=None, date_preset_na=None, time_preset=None,
  File "C:\Users\Ktrain_Media\Sickbeard\SickRage\sickbeard\webserve.py", line 109, in __init__
    kwargs['filter'] = html_entities
  File "C:\Python27\lib\site-packages\Cheetah\Template.py", line 1259, in __init__
    self._compile(source, file, compilerSettings=compilerSettings)
  File "C:\Python27\lib\site-packages\Cheetah\Template.py", line 1553, in _compile
    keepRefToGeneratedCode=True)
  File "C:\Users\Ktrain_Media\Sickbeard\SickRage\sickbeard\webserve.py", line 152, in compile
    kwargs['cacheDirForModuleFiles'] = os.path.join(sickbeard.CACHE_DIR, 'cheetah')
  File "C:\Python27\lib\site-packages\Cheetah\Template.py", line 788, in compile
    exec(co, mod.__dict__)
  File "C:\Users\Ktrain_Media\Sickbeard\SickRage\cache\cheetah\_Users_Ktrain_Media_Sickbeard_SickRage_gui_slick_interfaces_default_config_tmpl.py", line 30, in <module>
    import pwd
ImportError: No module named pwd

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by copekyle** [comment]
So this happened on both master and developer branch.  This popped up on the master branch 1-2 days ago.  I switch to the developer branch and got the same.  I'm using utorrent and it just gives me an authentication error.  I've check the utorrent gui from the web outside of sickrage and it is working.  It was working perfectly until about 24 hours ago.

**Comment by fernandog** [comment]
That is strange because that change was only in develop.
Are you switching branches using command line? If so you can get errors.

**Comment by fernandog** [comment]
@copekyle 

you don't need to stop SR to do this:
change SickRagegui/slick/interfaces/default/config.tmpl, line 46
from : ImportError
to: importerror
save
fully load page again

https://github.com/SiCKRAGETV/SickRage/blob/develop/gui/slick/interfaces/default/config.tmpl#L46

**Comment by fernandog** [comment]
@abeloin 

why the exception is not being raised?

```
#set $sr_user = None
#try
	#import pwdd
	#set $sr_user = $pwd.getpwuid(os.getuid()).pw_name
#except ImportError
	#import getpass
	#set $sr_user = $getpass.getuser()
#end try
#if $sr_user:
    <tr><td class="infoTableHeader">SR User:</td><td class="infoTableCell">$sr_user</td></tr>
#end if
```
```
  File "/home/pi/SickRage/cache/cheetah/_home_pi_SickRage_gui_slick_interfaces_default_config_tmpl.py", line 30, in <module>
    import pwdd
ImportError: No module named pwdd (CHANGE THIS TO RAISE THE ERROR)
```

**Comment by fernandog** [comment]
@abeloin 


SickRage/cache/cheetah/_home_pi_SickRage_gui_slick_interfaces_default_config_tmpl.py

the "import" is in the begining of the file. Not here!
```
''')
        sr_user = None
        try: # generated from line 43, col 1
            sr_user = VFN(VFN(VFFSL(SL,"pwd",True),"getpwuid",False)(os.getuid()),"pw_name",True)
        except ImportError: # generated from line 46, col 1
            sr_user = VFN(VFFSL(SL,"getpass",True),"getuser",False)()
        if VFFSL(SL,"sr_user",True): # generated from line 50, col 1
            write(u'''    <tr><td class="infoTableHeader">SR User:</td><td class="infoTableCell">''')
            _v = VFFSL(SL,"sr_user",True) # u'$sr_user' on line 51, col 76
            if _v is not None: write(_filter(_v, rawExpr=u'$sr_user')) # from line 51, col 76.
            write(u'''</td></tr>
''')
```

**Comment by abeloin** [comment]
@fernandog Cheetah is installed by the user.
@copekyle What is your cheetah version?

**Comment by abeloin** [comment]
Confirm not working on cheetah 2.4.4

**Comment by fernandog** [comment]
@abeloin is there something we can do?

**Comment by copekyle** [comment]
I am using cheetah 2.4.4 which I think is the newest version...

**Comment by copekyle** [comment]
I'm on a windows machine and only use python/cheetah for SickRage.  Is there a version I can install that is working?

**Comment by abeloin** [comment]
http://pythonhosted.org/Cheetah/cheps/2_import.html

**Comment by abeloin** [comment]
From cheetah changes:
```
The middle-ground I'm going to settle on for the release of v2.1.1 is
the introduction of a new compiler setting: useLegacyImportMode

In 2.1.1 this will be defaulted to True, this means that in order to
handle inline imports, you should compile your code with
"useLegacyImportMode=False".
```

**Comment by abeloin** [comment]
PR merged 
@copekyle Can you update and test?

**Comment by abeloin** [comment]
@fernandog FYI

**Comment by fernandog** [comment]
Thanks

**Comment by copekyle** [comment]
@abeloin @fernandog 
That fixed the bug for me.  Thanks for the quick support guys!

**Comment by fernandog** [comment]
@copekyle the user in /config page is correct?

**Comment by copekyle** [comment]
if you're asking about /config/ in the webgui.  Yes, that is accessible and correct.  I was having issues accessing it before the lastest commit.
