### ISSUE TITLE
Manually fetching from T******D** not working.

### ISSUE THREAD

**Issue by nucce1** [SiCKRAGETV/sickrage-issues#958]
Branch: 
master
Commit hash: 
3b399f16126c2566028312ecedcbb0a0d47d3dfa
Your operating system: 
Windows 2012 Server Standard
Python version: 
Python2.7
What you did: 
Trying to manually search for a "old" release, I have disabled backlog search by purpose for NZB just to force SickRage to use  T******D** instead. 
What happened:
When I'm doing like this it never finds anything, no matter what series I trying to fetch. (it does work on "fresh" and new releases")
What you expected:
I want it to find a proper release and download it, according to logfile the error is that it cant find anything like that, but I can see proper releases that are valid on T******D**.
Like "B***er C*** S*** S01E06 Fiv*-O 1080p WE*-D* **5 1 H 264-CtrlHD [** R*R]" would be a perfect match.

Using * to hide.

Part of logfile that won't find anything:
http://pastebin.com/4UvkBpNh

**Comment by nucce1** [comment]
I notice this may be the almost the same problem as for another provider(except login errors) and a open issue: https://github.com/SiCKRAGETV/sickrage-issues/issues/942

**Comment by fernandog** [comment]
@nucce1 check your quality settings

2015-03-13 22:59:11 DEBUG    SEARCHQUEUE-RETRY-273181 :: [T******D**] :: **Ignoring result** Better.Call.Saul.S01E06.720p.HDTV.X264-DIMENSION because **we don't want an episode that is HD TV&&

**Comment by nucce1** [comment]
Quality is set to HD1080, that's is why it should match the release I did mention in my first comment.

Full log:
http://pastebin.com/QNwXtJ92

**Comment by abeloin** [comment]
@nucce1 backlog search is enable?

In UK? You will need to update the urls: https://github.com/SiCKRAGETV/SickRage/pull/1519/files

**Comment by nucce1** [comment]
@abeloin Yes, Backlog is enabled on this provider.

I don't live in UK and can perfectly fine reach the host.

Regards

**Comment by abeloin** [comment]
Enabled any proxies in the options?

**Comment by abeloin** [comment]
Can you add after https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/providers/torrentday.py#L202 `logger.log(u"No result returned for " + search_string, logger.WARNING)`

Which should look like this:
```
                if not parsedJSON:
                    logger.log(u"No result returned for " + search_string, logger.WARNING)
                    continue
```
Don't forget to stop sickrage first, edit, then start sickrage and try again.

**Comment by nucce1** [comment]
Stopped, edited and added what you suggested and now I can't start.
  File "c:\SickRage\sickbeard\providers\torrentday.py", line 204
    continue
           ^
IndentationError: unindent does not match any outer indentation level

Row 198-209:
---
                if self.freeleech:
                    post_data.update({'free': 'on'})

                parsedJSON = self.getURL(self.urls['search'], post_data=post_data, json=True)
                if not parsedJSON:
					logger.log(u"No result returned for " + search_string, logger.WARNING)
                    continue

                try:
                    torrents = parsedJSON.get('Fs', [])[0].get('Cn', {}).get('torrents', [])
                except:
                    continue
-----


(I did not enable any proxies btw).
Regards/nucce

**Comment by abeloin** [comment]
Use space not tab before logger.log

**Comment by nucce1** [comment]
Okay, thanks, I done it, here is the log file from a new attempt.

http://pastebin.com/sG3S6UxV

Regards

**Comment by abeloin** [comment]
Ok there's data. Can you add after https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/providers/torrentday.py#L205 `logger.log(u"Json dump " + str(parsedJSON), logger.WARNING)`

Which should look like this:
```
                    continue

                logger.log(u"Json dump " + str(parsedJSON), logger.WARNING)
                try:
                    torrents = parsedJSON.get('Fs', [])[0].get('Cn', {}).get('torrents', [])
```
Don't forget to stop sickrage first, edit, then start sickrage and try again.

**Comment by nucce1** [comment]
Ok, alot of more data in the logfile.
Found here:
http://pastebin.com/t9hzXauk

**Comment by abeloin** [comment]
@nucce1 Stupid question but I have to ask, what are the values in:
* Minimum seeders
* Minimum leechers

**Comment by nucce1** [comment]
@abeloin: I'm so sorry for occupied your time, i'm official an retard. I had both these set to 20, I never thought it should be able to go below that, sorry, i'm to used to open trackers. *sigh*

It's working as intended now after I did set leechers to zero.

You can close this thread. Thank you.

Full Regards/nucce

**Comment by abeloin** [comment]
@nucce1 See the bright side, we now have a PR that improve debug logging: logs when there no data, no torrents, no title or url, doesn't meet min seeds or leechs. This will make it easier for everyone using TD to better understand when they get strange results. ;)
