### ISSUE TITLE
[APP SUBMITTED]: 'utf8' codec can't decode byte 0xe1 in position 20: invalid continuation byte

### ISSUE THREAD

**Issue by 11182711114** [SiCKRAGETV/sickrage-issues#959]
### INFO
Python Version: **2.7.8 (default, Dec 15 2014, 02:33:48) 
[GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.3-RELEASE-p5-amd64-64bit-ELF**
Branch: **master**
Commit: SiCKRAGETV/SickRage@3b399f16126c2566028312ecedcbb0a0d47d3dfa
Link to Log: https://gist.github.com/2f371fc02a00c7bb581c
### ERROR
```
Thread-74 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 257, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 2176, in processEpisode
    is_priority=is_priority, failed=failed, type=type)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 196, in processDir
    for dir in [x for x in dirs if validateDir(path, x, nzbNameOriginal, failed, result)]:
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 253, in validateDir
    result.output += logHelper(u"Processing folder " + dirName, logger.DEBUG)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe1 in position 20: invalid continuation byte

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
What is the complete dir for Spartacus.War.Of.The.Damned.S03E05.1080p.BluRay.x264-ROVERS.1

**Comment by 11182711114** [comment]
/mnt/downloads/sabnzbd/complete/.tv/Spartacus.War.Of.The.Damned.S03E05.1080p.BluRay.x264-ROVERS.1

**Comment by fernandog** [comment]
@11182711114 did you get this error for another episodes or just this one?

**Comment by 11182711114** [comment]
@fernandog It happends whenever I try to manually postprocess ".tv/". Going to start systematically deleting folders to find the right one, in the mean time I cleaned up the folder with empty files but am still getting it. 

Another, hopefully more useful log(At least in case it tries to pp them in the same order as the dir listing)
http://pastebin.com/4WxqpJ9Z

**Comment by fernandog** [comment]
@11182711114 try remove the DOT in ".tv"

**Comment by fernandog** [comment]
@TagForce the dot in the folder can cause this issue?

**Comment by 11182711114** [comment]
@fernandog Thought of the same thing, but no .tv/ -> tv/ still erroring out;

http://pastebin.com/xf2FQRCX

**Comment by 11182711114** [comment]
@fernandog Actually, I have had problems with "House.S03E06.Que.Ser?.Ser?.WEBRip.x264-MOBBit" before and removing it seems to have fixed it.

"House.S03E06.Que.Ser?.Ser?.WEBRip.x264-MOBBit" where the ? are supposed to be "á"

**Comment by TagForce** [comment]
@11182711114 
House.S03E06.Que.Ser\xe1.Ser\xe1.WEBRip.x264-MOBBit.1

That's the culprit.

**Comment by fernandog** [comment]
@11182711114 remove the folder that has "á"

**Comment by TagForce** [comment]
@11182711114 lol... nice... Exactly the same time we figured the offending file.
I think this is caused by the download client saving it with a wrong name. Best to just rename the file to something without the title in the name, and PP it. That way it shouldn't return.

**Comment by 11182711114** [comment]
@TagForce Yeah, I even knew that those were breaking PP but I guess I just forgot they existed :(

**Comment by fernandog** [comment]
what is the original torrent name/filename? Maybe SR send the torrent to the downloader with this chars

**Comment by TagForce** [comment]
@fernandog That shouldn't really matter... The torrent file can be named anything, as soon as it reads it it will know what the names of the files in it should be. If those get saved in a wrong way you'll end up with weird characters.

Either a File system limitation (fat or fat32 have issues with this) or a locale/codepage issue with the download client. Or it could be a bug in SR, but in this case the actual files were named wrongly after downloading, which basically eliminates SR as the culprit.

**Comment by 11182711114** [comment]
@fernandog It was supposed to be á, however nzbToMedia has an option to convert any foreign char to UTF8 completely nullifying this error. It is not a perfect solution but it works for those that use it.
