### ISSUE TITLE
Wrong flags are used in interface

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#96]
<a href="https://github.com/aidik"><img src="https://avatars.githubusercontent.com/u/5146636?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [aidik](https://github.com/aidik)**
_Sunday Dec 14, 2014 at 10:57 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/1134 (3 comment(s))_

----

Subtitles downloaded in Czech language are represented by wrong flag.
Please refer to the Wiki page http://en.wikipedia.org/wiki/Flag_of_the_Czech_Republic or simple Google search.

This it is a very quick fix.

**Comment by fernandog** [comment]
@neoatomic can you check this comment please? https://github.com/SiCKRAGETV/sickrage-issues/issues/96#issuecomment-67771609

**Comment by fernandog** [comment]
@aidik is this still an issue?

**Comment by aidik** [comment]
It is all correct for sometime already. Thank you!
