### ISSUE TITLE
Update quality of TV and redownload existing episodes doesn't work

### ISSUE THREAD

**Issue by adprom** [SiCKRAGETV/sickrage-issues#960]
Add a tv show and set the quality to 720 Web-DL.

Allow an episode to download. 

Then change the quality of 'initial' for the tv show to 1080p web-dl. The press the maginifying glass for a particular episode to force a rescan for that episode. Sickrage will tell you that no downloads were found despite there clearly being valid releases in 1080p which could replace the existing 720p download.

Note: Ensure releases are actually available on indexer.

**Comment by Rouzax** [comment]
That is the same issue as this :smile: 
https://github.com/SiCKRAGETV/sickrage-issues/issues/747

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1547
