### ISSUE TITLE
TV Shows marked as Low Quality if you change Archive Quality after shows have downloaded

### ISSUE THREAD

**Issue by adprom** [SiCKRAGETV/sickrage-issues#961]
See below.... If you already have TV shows at a certain quality and you change the archive quality afterwards - all downloaded shows are marked as 'low quality' even though they meet the archive quality. SR seems to just mark everything as low quality without checking the current episode quality of those downloaded.

![image](https://cloud.githubusercontent.com/assets/10583376/6650965/01b8ea3c-ca82-11e4-9d22-83cea15f6e3f.png)

**Comment by adprom** [comment]
Selecting "archive on first match" fixes the issue

**Comment by thezoggy** [comment]
not a bug, its doing what its suppose to. since all qualities but the greatest (in your example, 720p bluray) would be treated as low quality.
