### ISSUE TITLE
Manual post processing does not delete the folder.

### ISSUE THREAD

**Issue by jesse0032** [SiCKRAGETV/sickrage-issues#962]
Anyone that likes to seed what they are transferring will understand why most people that use sickrage for torrents will use manual post processing (because it fails to move the file if its seeding).

Having it leave behind all the folders is very annoying.  Could we add a basic tick box to allow for folder deletion when using manual post processing.

Thanks.

**Comment by fernandog** [comment]
If you seed why dont you symlink instead of move?

**Comment by jesse0032** [comment]
I do. But it gets too messy and confusing and too many files all in one directory. Makes sorting it later if I want to stop seeding tedious.  I prefer to run a manual process when it suits.  I run a manual move after a while as a tidy up, but it is not exactly tidy when all these empty folders are left behind.  I don't really understand why folders are not removed?  Some people use manual to test and don't want their files deleted if it fails? Not sure.  Be nice to have the option.

**Comment by TagForce** [comment]
@jesse0032 I have the code in place to add the option to delete files even when manually processing (it is a checkbox on the PP page), but I want to know if @abeloin is going to merge my other PP which handles failures anytime soon, as it will most certainly cause merge conflicts. I'd rather do it in that code, as it will be less messy in the end, and provides a more complete change to the Post Processing.

**Comment by abeloin** [comment]
@TagForce It was merged by @fernandog 2 hours ago

Ref: https://github.com/SiCKRAGETV/SickRage/pull/1548

**Comment by TagForce** [comment]
@fernandog @abeloin https://github.com/SiCKRAGETV/SickRage/pull/1576

**Comment by abeloin** [comment]
PR merged
