### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by Rouzax** [SiCKRAGETV/sickrage-issues#963]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@3b399f16126c2566028312ecedcbb0a0d47d3dfa
Link to Log: https://gist.github.com/1d3fcd8bb7ba52ebc41b
### ERROR
```
FINDPROPERS :: uTorrent: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Rouzax** [comment]
![image](https://cloud.githubusercontent.com/assets/4103090/6651414/6369ebaa-ca41-11e4-931c-bf442f2ea720.png)
Here is the link to the complete logs:
http://cloud.codstats.nl/index.php/s/A6MYJ9XCEaDgyfW

**Comment by Rouzax** [comment]
Sorry just saw there was already a new issue open: https://github.com/SiCKRAGETV/sickrage-issues/issues/955

**Comment by fernandog** [comment]
Try that fix please
