### ISSUE TITLE
[APP SUBMITTED]: This show is already being updated, can't update again until it's done.

### ISSUE THREAD

**Issue by scythe000** [SiCKRAGETV/sickrage-issues#966]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@3b399f16126c2566028312ecedcbb0a0d47d3dfa
### ERROR
```
SHOWUPDATER :: Automatic update failed: This show is already being updated, can't update again until it's done.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Not an error
