### ISSUE TITLE
[Feature Request] Better way to determine quality of files

### ISSUE THREAD

**Issue by nicolasmartinelli** [SiCKRAGETV/sickrage-issues#969]
Branch: master

Hello,

I don't understand why in generic.py, the quality of the file is determined in two different ways.

First, it uses self.getQuality: https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/providers/generic.py#L301
Then, it uses parse_result.quality: https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/providers/generic.py#L330

This can lead to inconsistencies. For example, "Your.TV.Show.2x02.(HDTV-ASAP)" will return an unknown quality with parse_result.quality, while the provider knows it is a SD TV.

Regards

**Comment by fernandog** [comment]
@nicolasmartinelli 

" while the provider knows it is a SD TV." 

or HDTV?

**Comment by nicolasmartinelli** [comment]
Nope, SDTV ;) https://github.com/SiCKRAGETV/SickRage/blob/2d8aad80cdfb8983832206af445039de0decded9/sickbeard/common.py#L212

Anyway, my question is why would you determine the quality with two different methods, knowing that the final method override anyway the quality sent by the provider?

**Comment by TagForce** [comment]
@nicolasmartinelli The first one only has the scene release name to work with, so it checks that. Then, later on, we're actually using a parsed result, which can be done on files already renamed by SR. To get the qualities from that it tries to find the Quality Strings SR uses for its renaming scheme in the filename, if that fails (quality.NONE is reached in the iteration of all the quality codes) it will call the same function to get the name from the scene release_name. So, for a file with a release name, the resulting quality information is in both cases gotten from the same function (sceneQuality), and should give you the same results.

**Comment by nicolasmartinelli** [comment]
Thanks for the explanation.

So, I would then reformulate: do you think it would be interesting idea to allow a provider to provide the quality of every result, and take that result (if provided) into account instead of the parsing?

I actually have a clear case, following my PR https://github.com/SiCKRAGETV/SickRage/pull/1561. The API http://eztvapi.re/ provides the quality of the link, so there is no need to parse the file to guess the quality. However, some naming (especially SD TV) are not recognized by SickRage. This leads to an unfortunate situation: the provider can return the quality, but SickRage will not use this information. 

I'm pretty sure it is not the only case, I guess other providers could also return the quality right away. A simple solution would be to replace the line https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/providers/generic.py#L330 by:
`if 'quality' in item:
`    quality = item['quality']
`else:
`    quality = parse_result.quality

This is of course not the cleanest solution since you still determine the quality during the parsing while it is not used afterwards.

**Comment by TagForce** [comment]
@nicolasmartinelli Yeah, if the provider has this information, we might as well use it. I'm thinking about changing the whole quality tracking in SR, since it loses the info way too often. I'll add this option to the todo list for it. Along with an option to determine it using mediainfo if you explicitly request.
It'll require a db change (new quality field) so it will be a while, but it'll happen.

**Comment by raymondtrueman** [comment]
See #889 as well, its a similar request

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
