### ISSUE TITLE
Unable to access Sickrage within local network

### ISSUE THREAD

**Issue by ryanf86** [SiCKRAGETV/sickrage-issues#970]
INFO

Python Version: 2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
Operating System: Darwin-14.1.0-x86_64-i386-64bit
Branch: develop
Commit: SiCKRAGETV/SickRage@5626fa5977

ERROR

For quite a while now I have been unable to access Sickrage from any other computer on my local network.

On my computer where Sickrage is installed I can access it with http://localhost:8081 however on the same computer I cannot access using the computers ip address i.e. http://10.0.0.4:8081.

I have have changed the port number multiple times, as well as forwarding the port numbers on my router.

When attempting to access Sickrage from 10.0.0.4:8081 I get page cannot be displayed on both the localhost computer and another on my network. Issue is on windows and osx.

I have no issue accessing other web based interfaces running from the computer on other port numbers i.e. couch potato.

It looks like the ip address and port number are not resolving.

Im also not getting any errors in sickrage and I've looked at the log after attempting to access using the ip address and the log shows nothing.

If you require anymore info let me know.

**Comment by fernandog** [comment]
@ryanf86 

please open config.ini and send the following settings:

```
web_port = 
web_host = 
web_ipv6 = 
web_root = 
```

**Comment by abeloin** [comment]
@ryanf86 make sure the web_host is set to 0.0.0.0 not 127.0.0.1

**Comment by ryanf86** [comment]
web_port = 8081
web_host = 0.0.0.0
web_ipv6 = 1
web_log = 0
web_root = ""

**Comment by fernandog** [comment]
Stop SR
edit config.ini
set web_host with the IP
save
start

**Comment by ryanf86** [comment]
Changed the IP address but still can access it on other computers on the network. 

It appears as if it's going to load then after a minute or to it says 'could not open the page because the server stopped responding'

Have no issue access from the computer SR is running although I now have to put in the IP address instead of locahost. Assuming that's because of the changes made to the config file

**Comment by fernandog** [comment]
Why did you enabled IPV6? 
Stop SR, disable in config. Start

**Comment by ryanf86** [comment]
Not sure when or why I did that but have turned it off and still no change

**Comment by fernandog** [comment]
did you restarted after disable it or did you disable while running SR?
did you try clear cache?
It's not a SR problem as I can access my SR using IP and host name

**Comment by ryanf86** [comment]
Shutdown and changed it in the config file then started again. Just deleted the cache and still no luck.

I might download a fresh package and try accessing before I import my settings and see if I can access. Could be some corrupt or erroneous files somewhere

**Comment by fernandog** [comment]
ok. let us know

**Comment by ryanf86** [comment]
Still no luck even with a blank slate which leads me to think that it maybe something to do with my system. I just seems strange that it is only happening with SR. I swapped SR and Couchpotato port number and couch potato works fine no matter what port i put it on

**Comment by abeloin** [comment]
Do you use the firewall? Check preferences > security & privacy > firewall to see if you allow incoming connection for sickrage.

To see if sickrage is binding to all adapter, try this command in terminal: `sudo lsof -i -n -P | grep TCP`
In result look for a line similar to this one(contain 8081):
`python    17496 user   10u  IPv4  57570      0t0  TCP *:8081 (LISTEN)`
The start indicate it's listening on all adapter

**Comment by ryanf86** [comment]
Turns out python wasn't accepting incoming connections but its all good now. Thanks for the assistance

**Comment by Verkurkie** [comment]
I had the same problem but somehow fixed it by switching the web port to another value and then back to the original value. I'm running Windows and in my case, port 8081 is already in use so i had entered 8086 in my config. This worked locally (http://localhost:8086) but not from other nodes on my local LAN. Here were my steps:

- Tried the changing of IP address from 0.0.0.0 to the machine's IP and that didn't work (couldn't even hit it locally
- Went back to 0.0.0.0
- Made sure web_ipv6 was set to 0
- I stopped the SB service, changed the port to 8082 in config.ini, saved it, started service
- Tried to hit it - didn't work (locally or remote). 
- Stopped the service again, changed port back to 8086, started service
- Presto! Everything now worked!

Thought this might help others ... give it a shot!

**Comment by labrys** [comment]
@Verkurkie that kind of sounds like you were being blocked by Windows firewall, and that the change allowed it to detect and auto-configure the port.  Glad this worked for you.
