### ISSUE TITLE
[APP SUBMITTED]: Connection error ('Connection aborted.', BadStatusLine("''",)) while loading URL http://services.tvrage.com/myfeeds/showinfo.php

### ISSUE THREAD

**Issue by xrolfex** [SiCKRAGETV/sickrage-issues#973]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2]**
Operating System: **Linux-3.13.0-46-generic-x86_64-with-Ubuntu-14.04-trusty**
Branch: **master**
Commit: SiCKRAGETV/SickRage@401cb666016e45b42fe675bafdf7908ad6c2b9bb
### ERROR
```
SHOWQUEUE-REFRESH :: Unable to look up show on TVRage, not downloading images: error Connection error ('Connection aborted.', BadStatusLine("''",)) while loading URL http://services.tvrage.com/myfeeds/showinfo.php
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
Not an error, tvrage is temporarily unavailable
