### ISSUE TITLE
[Feature Request] 'tp' mediaExtensions Addition

### ISSUE THREAD

**Issue by REDdimension** [SiCKRAGETV/sickrage-issues#975]
Hi, awesome Sickrage people!

I have a simple request. If it's not too much trouble, would you please add "tp" to the allowed mediaExtensions list in line 28 of common.py?

I use Beyond TV, and *.tp is the native file format of that DVR software. Kodi plays it fine, but Sickrage doesn't recognize it by default, so after every update (and thanks to the frequent update schedule, that's often) I have to manually edit the list and delete common.pyc & restart Sickrage to force my Beyond TV videos to be recognized.

Thanks in advance!

**Comment by fernandog** [comment]
@REDdimension please send the modified line in common.py

**Comment by fernandog** [comment]
@REDdimension done in develop. wait until sunday to be merged in master
