### ISSUE TITLE
[Feature Request] Save Custom Quality Profiles

### ISSUE THREAD

**Issue by edru** [SiCKRAGETV/sickrage-issues#977]
Just a way to define an initial/archive quality config, then save it with a custom name. This would make mass editing a lot easier, and identify better if you have various "custom" qualities you could see the difference on a list level rather than show level.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/981

**Comment by samdchuck** [comment]
Yes, would love this. Currently most of my shows are either SD+SDDVD or 720p+720pBR. But they all just show as custom.

**Comment by fernandog** [comment]
@miigotu related to new DB fields issue:
Should we add this to DB (profiles quality table) instead of common.py so user can create custom quality profiles?

I agree with this issue and the other about mass edit custom qualities as I can't see the real custom quality.

```
SD = Quality.combineQualities([Quality.SDTV, Quality.SDDVD], [])
HD = Quality.combineQualities(
    [Quality.HDTV, Quality.FULLHDTV, Quality.HDWEBDL, Quality.FULLHDWEBDL, Quality.HDBLURAY, Quality.FULLHDBLURAY],
    [])  # HD720p + HD1080p
HD720p = Quality.combineQualities([Quality.HDTV, Quality.HDWEBDL, Quality.HDBLURAY], [])
HD1080p = Quality.combineQualities([Quality.FULLHDTV, Quality.FULLHDWEBDL, Quality.FULLHDBLURAY], [])
ANY = Quality.combineQualities(
    [Quality.SDTV, Quality.SDDVD, Quality.HDTV, Quality.FULLHDTV, Quality.HDWEBDL, Quality.FULLHDWEBDL,
     Quality.HDBLURAY, Quality.FULLHDBLURAY, Quality.UNKNOWN], [])  # SD + HD

# legacy template, cant remove due to reference in mainDB upgrade?
BEST = Quality.combineQualities([Quality.SDTV, Quality.HDTV, Quality.HDWEBDL], [Quality.HDTV])

qualityPresets = (SD, HD, HD720p, HD1080p, ANY)
qualityPresetStrings = {SD: "SD",
                        HD: "HD",
                        HD720p: "HD720p",
                        HD1080p: "HD1080p",
                        ANY: "Any"}
```
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/common.py#L388

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
