### ISSUE TITLE
Provider TD error "sslv3 alert handshake failure" when searching

### ISSUE THREAD

**Issue by chrisric** [SiCKRAGETV/sickrage-issues#978]
Hi,

Since updating to latest master torrentday gets the below error when searching for a episode.

2015-03-16 13:17:50 ERROR    SEARCHQUEUE-BACKLOG-78998 :: [TorrentDay] :: Error while searching TorrentDay, skipping: error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:581)

Full log: (scroll to end of file)
https://drive.google.com/file/d/0B8JFLK_cWhrbbndweFhDR2ZTZDA/view?usp=sharing

SR Version: BRANCH: (master) / COMMIT: (c46a03d5471c9e2f0cfa0c20a9cddb8e45d5f86b) 
Python Version:	2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

Thanks.

**Comment by fernandog** [comment]
@chrisric do you have global proxy enable or provider proxy enabled? If so, try disable please. TD changed his domain name

**Comment by fernandog** [comment]
@abeloin looks like TD don't support SSL3 anymore. Should we change something in SR or not?

```
Protocols
TLS 1.2	Yes
TLS 1.1	Yes
TLS 1.0	Yes
SSL 3	No
SSL 2	No
```

https://www.ssllabs.com/ssltest/analyze.html?d=tdonline.org&s=104.27.133.232&hideResults=on

**Comment by chrisric** [comment]
@fernandog I do not use any proxy, Australia hasn't blocked anything as yet.

Was SSLv3 support just enabled on SR? TD was working 5min before I upgraded to the latest master. TD making a change to no longer support SSLv3 within that time frame is unlikely... but not impossible I guess.

**Comment by fernandog** [comment]
@chrisric 
latest master changed the TD domain name
stop SR, edit SickRage/sickbeard/providers/torrentday.py
and change tdonline.org > torrentday.eu
save
star and test

**Comment by chrisric** [comment]
@fernandog Sorry, I didn't notice the domain change. It works now I have changed it back.

Thanks.

**Comment by abeloin** [comment]
@chrisric What version of python did you download from [python website](https://www.python.org/downloads/release/python-279/)?
* Mac OS X 64-bit/32-bit installer (10.6+)
* Mac OS X 32-bit i386/PPC installer (10.5)

Because if you use the i386/PPC version it will be linked to an old version of openssl.

To check your openssl version: `python -c 'import ssl; print(ssl.OPENSSL_VERSION)'` SNI was added in 0.9.8 if I remember correctly.

If it sill doesn't work try adding these modules via pip [stackoverflow discussion](http://stackoverflow.com/questions/18578439/using-requests-with-tls-doesnt-give-sni-support/18579484#18579484):
* pyOpenSSL
* ndg-httpsclient
* pyasn1

This should enable SNI without using openssl.

**Comment by fernandog** [comment]
@abeloin mine:

```
pi@raspbmc:~/SickRage$ python -c 'import ssl; print(ssl.OPENSSL_VERSION)'
OpenSSL 1.0.1e 11 Feb 2013
```

**Comment by chrisric** [comment]
@abeloin I downloaded "Mac OS X 64-bit/32-bit installer"

Looks like I just passed with OpenSSL version "OpenSSL 0.9.8za 5 Jun 2014"

I installed modules as suggested but it gave the same error.

This looks to be working for others, probably not a SR issue based on your comments.

Feel free to close this and I'll troubleshoot it in some python or mac forum. Maybe I should just install Linux on my mac mini :)

Thanks.

**Comment by abeloin** [comment]
Can you run this in terminal: `openssl version`

Maybe you could use brew or macports to upgrade your openssl version: http://stackoverflow.com/questions/15185661/openssl-version-macosx-homebrew

Reference: http://bugs.python.org/issue17128

**Comment by chrisric** [comment]
@abeloin Here you go.

```
greyfrog:SickRage admin$ openssl version
OpenSSL 0.9.8za 5 Jun 2014
```
I will install macports and let you know.

Thanks.

**Comment by chrisric** [comment]
@abeloin Okay... I'm getting a new error now. Logs are below, scroll to end of file etc.
https://drive.google.com/file/d/0B8JFLK_cWhrbVFNVVVFWOUk1T3c/view?usp=sharing

Changes I've made:
Upgraded pyOpenSSL and OpenSSL
```
greyfrog:SickRage admin$ pip show pyOpenSSL
---
Name: pyOpenSSL
Version: 0.14
Location: /Library/Python/2.7/site-packages
Requires: cryptography, six

greyfrog:SickRage admin$ openssl version
OpenSSL 1.0.2 22 Jan 2015
```
Thanks.

**Comment by chrisric** [comment]
@abeloin I updated 


```
greyfrog:SickRage admin$ pip show urllib3
---
Name: urllib3
Version: 1.10.2
Location: /Library/Python/2.7/site-packages
Requires: 
```

**Comment by abeloin** [comment]
@chrisric Changing the domain isn't a long term solution as more and more website uses sni.
You updated urllib3 in /lib/requests? That won't work, better upgrade requests to 2.6.0

Also since you updated to openssl 1.1.2 you can remove:
* pyOpenSSL
* ndg-httpsclient
* pyasn1

**Comment by abeloin** [comment]
@chrisric Forgot to ask, after upgrading openssl didi you checked if python the new openssl:
`python -c 'import ssl; print(ssl.OPENSSL_VERSION)'`

**Comment by chrisric** [comment]
@abeloin I can't thank you enough for your help. I would never have known what to research without your help.

When checking the openssl version within python (as you suggested above) it showed the old openssl version was still being used.

After some reading I realized it was using the old ssl libs, the new openssl version was installed with macports. python27 was installed through an gui installer.

Once I installed python27 and the cheetah module through macports it started working.

SR Version: BRANCH: (master) / COMMIT: (cc4896e96a27dda5cc9ed198209aa514bf68a4eb)
Python Version: 2.7.9 (default, Dec 11 2014, 01:21:43) [GCC 4.2.1 Compatible Apple Clang 4.1 ((tags/Apple/clang-421.11.66))]

Thanks again!

-Chris

**Comment by chrisric** [comment]
I had a SSL issue a couple of weeks back on SickRage, everything was working and then one of the torrent providers moved to a web server that uses SSL SNI and stopped working. I'm no programmer so don't know the nuts and bolts of it all but below is what fixed it for me.

I'm running MacOS 10.8.5, it was using OpenSSL 0.9.8za.

You can't only install OpenSSL via MacPorts (MP) as Python will still use the old OpenSSL libs. You may know how to fix that but I found it easier to just install Python through MP too. You obviously need to run the MP versions when start CP.

Using MacPorts I installed:
openssl @1.0.2_0
py27-cheetah @2.4.4_1
python27 @2.7.9_0

You can check your versions with:
```
python -V
openssl version
python -c 'import ssl; print(ssl.OPENSSL_VERSION)'
```
Or after you install MacPorts versions:
```
/opt/local/bin/python2.7 -V
/opt/local/bin/openssl version
/opt/local/bin/python2.7 -c 'import ssl; print(ssl.OPENSSL_VERSION)'
```

Both CouchPotato and SickRage are working perfectly on my Mac Mini now.

Thanks.
