### ISSUE TITLE
[Feature Request] Anyone interested in multi language support?

### ISSUE THREAD

**Issue by cytec** [SiCKRAGETV/sickrage-issues#979]
Hi, 

I've been working on a SickBread fork for quite a long time and recently switched to my own SickRage Fork. I was amazed how few changes (compared to SickBeard) i had to make to take the same effect and i really love it!

I've done a lot of smaller changes in my fork but the "main" feature would be that it has support for downloading multiple Languages out of the box... I'm using the Shows Metalanguage as a starting point to check for language specific required/ignored words. Currently i'm cleaning some stuff up and if there is any interest in this being merged i'd love to make a PR for those changes...

**Comment by fernandog** [comment]
@cytec how do you handle when indexer don't have all necessary non-english data to add a show? do you fallback to english?

**Comment by fernandog** [comment]
@cytec is that it?
 https://github.com/SiCKRAGETV/SickRage/pull/1372

**Comment by neoatomic** [comment]
@cytec I'm a firm believer that its better to combine/concentrate forces on one place than do our separate things. Saw you have a substantial German community, so there must be demand for those changes. 
So when its possible, lets do it.

**Comment by cytec** [comment]
@fernandog well... the indexer stuff is still handled by the indexer itself... tvdb for example falls back to english descriptions if there is no content entered for the requested non-english language.

that pull request you are referencing would be something to give the user more choices for the default language an indexer uses which would also be great :) But i'm talking about downloading foreign stuff based on the shows selected indexer language (because i think if you want, for example, german metadata you'll probably want to have german releases too)

@neoatomic yeah, thats what i was thinking about... I have done a few other changes besides that as well, but they are basically stuff to make german airdates working if german Lanugage is selected, added some network icons and thats it...

**Comment by neoatomic** [comment]
Closing as this was Merged.
