### ISSUE TITLE
Unable to parse the filename into a valid show

### ISSUE THREAD

**Issue by flightlevel** [SiCKRAGETV/sickrage-issues#980]
Not sure why SickRage won't parse the below filename, looks fairly standard to me.
`2015-03-16 21:17:21 INFO     SEARCHQUEUE-BACKLOG-267736 :: [IPTorrents] :: Performing episode search for Yukon Gold`
`2015-03-16 21:17:21 DEBUG    SEARCHQUEUE-BACKLOG-267736 :: [IPTorrents] :: IPTorrents search page URL: https://iptorrents.eu/torrents/?l73=1&l78=1&l66=1&l65=1&l79=1&l5=1&l4=1&q=Yukon.Gold S03E03 &qf=ti;o=seeders`
`2015-03-16 21:17:22 DEBUG    SEARCHQUEUE-BACKLOG-267736 :: [IPTorrents] :: Found result: Yukon Gold WEBRip S03E03 360p mp4 (https://iptorrents.eu/details.php?id=1350803)`
`2015-03-16 21:17:22 DEBUG    SEARCHQUEUE-BACKLOG-267736 :: [IPTorrents] :: Using ALL regexes`
`2015-03-16 21:17:22 DEBUG    SEARCHQUEUE-BACKLOG-267736 :: [IPTorrents] :: Unable to parse the filename Yukon.Gold.WEBRip.S03E03.360p.mp4 into a valid show`
`2015-03-16 21:17:22 INFO     SEARCHQUEUE-BACKLOG-267736 :: No needed episodes found during backlog search for: [Yukon Gold] `

It handled both episode 1 & 2 of these just fine
`Yukon.Gold.S03E01.540p.WEBRip.H.264.mp4`
`Yukon.Gold.S03E02.Game.Changer.WEB-DLx264.mp4`

SR Version: 	BRANCH: (master) / COMMIT: (03a6584904c85147719f14e4e8f5010b80603db4) 
Python Version:	2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]

**Comment by fernandog** [comment]
@flightlevel IMO there isn't codec info. SR needs the codec info.

**Comment by flightlevel** [comment]
I thought that might be the case as well, but plenty of the test cases don't provide that much info eg.
https://github.com/SiCKRAGETV/SickRage/blob/master/tests/name_parser_tests.py

**Comment by fernandog** [comment]
tests are not running
https://github.com/SiCKRAGETV/SickRage/pull/    1525

**Comment by TagForce** [comment]
Yukon.Gold.WEBRip.S03E03.360p.mp4
The WEBRip part is in the wrong place...
My guess is it's trying to convert Yukon Gold WEBRip into a valid show name.
Try adding that to your scene exceptions.

**Comment by flightlevel** [comment]
Thanks @TagForce & @fernandog 
Spot on @TagForce , added it to scene exceptions and bingo! It was just poor naming.

**Comment by fernandog** [comment]
@flightlevel it's not a scene exceptions. you can have problems with PP or KODI. It's a bad naming.
