### ISSUE TITLE
[Feature Request] Show actual quality (hdtv/1080p) instead of custom quality labels

### ISSUE THREAD

**Issue by Rouzax** [SiCKRAGETV/sickrage-issues#981]
I've set al my shows for either HD TV or 1080p HD TV.
It would be great to see that in the show overview table instead of Custom
![image](https://cloud.githubusercontent.com/assets/4103090/6683879/e9e722d2-cc8b-11e4-950e-13933094d904.png)
Is that possible?

**Comment by fernandog** [comment]
maybe we can check if user set only ONE quality and show quality name instead of the preset

https://github.com/SiCKRAGETV/SickRage/blob/develop/gui/slick/views/inc_defs.mako#L15

**Comment by VinceVal** [comment]
@fernandog isn't this exactly what my PR does? With my collection, almost all of them are set to a single quality and show that quality.

The case where this doesn't work is if the user has also set an archive quality.

I didn't see this FR when I submitted my PR, but I believe it's exactly what @Rouzax was after...

**Comment by fernandog** [comment]
"The case where this doesn't work is if the user has also set an archive quality." - didnt know that

What if allowed(initial) = preferred(archive) ?
Can we add that rule too?

**Comment by VinceVal** [comment]
I don't think that would be too hard. I'll take a look tonight.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!

**Comment by Rouzax** [comment]
Not necessary, already implemented in the current Master.

**Comment by miigotu** [comment]
part of the reason we decided to go this route and move to Feathub. =¶
