### ISSUE TITLE
Sorting show list by network isn't working

### ISSUE THREAD

**Issue by Zzaap** [SiCKRAGETV/sickrage-issues#984]
it sorts by show name instead

BRANCH: (master) / COMMIT: (568421b27a7940bfdebfef1be5f2b121d8a00b8f) 
Python Version:	2.7.8

**Comment by fernandog** [comment]
Screenshot please

**Comment by Zzaap** [comment]
![network](https://cloud.githubusercontent.com/assets/5058994/6699229/2ba8dd36-cd00-11e4-99f0-9408813b5689.png)

**Comment by fernandog** [comment]
@Zzaap did you tried the dropdown list and select "Network" ?

**Comment by fernandog** [comment]
@abeloin if we can sort direct in the table we can remove the "Sort by", can't we?

![2](https://cloud.githubusercontent.com/assets/2620870/6708861/e12341b8-cd52-11e4-8358-20ad0835d6e7.png)

**Comment by Zzaap** [comment]
I just tried, in layout 'poster' and 'simple' it sorts correctly, however in layout 'small poster' and 'banner' when clicking the network column it sorts by show name instead.

**Comment by abeloin** [comment]
@fernandog They are talking about the home page not the coming episodes page.

**Comment by fernandog** [comment]
@abeloin coming episodes dont work either

**Comment by abeloin** [comment]
@fernandog Which layout?

**Comment by abeloin** [comment]
@fernandog How do you sort when in calendar, banner and Poster mode?

>@abeloin if we can sort direct in the table we can remove the "Sort by", can't we?

**Comment by fernandog** [comment]
Good point. Sorry

**Comment by abeloin** [comment]
Both PR merged in develop

**Comment by fernandog** [comment]
working! thanks!
