### ISSUE TITLE
Add priority setting in Sab configuration section

### ISSUE THREAD

**Issue by saitoh183** [SiCKRAGETV/sickrage-issues#985]
It would great if we could set the sab priority in the SR config for daily downloads vs backlog downloading. NZBGet settings section in SR has this setting. 

For people like me that have download limits, you can set Sab to pause and whatever comes in as a force priority can still download anyways but if something from backlog comes in as normal, it would be paused till you give it the go.

 Sonarr has this function and it is really helpful in managing downloading. Yes you can put a schedule in sab but the problem with that is you might still want your day to day to download right away and always be highest priority over backlog. 

I also know about the SR setting Allow High Priority in Search Settings but this only sets the priority to High and that isnt the highest priority in Sab...Force is the highest priority.

**Comment by fernandog** [comment]
@saitoh183 

test this please:
stop SR
edit SickRage/sickbeard/sab.py, Line 62
change to this :
```
params['priority'] = 2
```

2 = forced

https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/sab.py#L62

**Comment by saitoh183** [comment]
Made the change and testing...will report back in a few

**Comment by saitoh183** [comment]
Seems to be working :)

**Comment by fernandog** [comment]
@saitoh183 wait be merged into master. you can keep your local change until then

**Comment by saitoh183** [comment]
@fernandog Thanks :)
