### ISSUE TITLE
[Feature Request] Add support for Deluge LabelPlus plugging

### ISSUE THREAD

**Issue by saitoh183** [SiCKRAGETV/sickrage-issues#987]
LabelPlus is just a way better and more flexible compared to the built-in one

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
