### ISSUE TITLE
Preferred search providers per show

### ISSUE THREAD

**Issue by saitoh183** [SiCKRAGETV/sickrage-issues#988]
It Would be great to be able to set a specific search provider to a specific show. For example i have french shows which on only found on t411.io so its pointless for SR to search all providers for this show since it will only , always be on t411. Also in a less granular way, being able to set whether we want torrent search or usenet search for a specific show would be also nice to have. Certain shows never get on usenet  but are always available on torrent. So maybe a sort of  profile system...Sonarr has this function.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/28
https://github.com/SiCKRAGETV/sickrage-issues/issues/357
