### ISSUE TITLE
No needed episodes found during backlog

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#99]
<a href="https://github.com/kodikas"><img src="https://avatars.githubusercontent.com/u/10159571?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kodikas](https://github.com/kodikas)**
_Sunday Dec 14, 2014 at 17:14 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/1137 (4 comment(s))_

----

BRANCH: (develop) / COMMIT: (b63fdd2b5118af25d1c4c94fc9892363e716b3c2) 
You are using BETA software
SR Config file:	/home/kodikas/.sickrage/config.ini
SR Database file:	/home/kodikas/.sickrage/sickbeard.db
SR Cache Dir:	/home/kodikas/.sickrage/cache
SR Arguments:	[]
SR Web Root:	
Python Version:	2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]

Automatic searching and snatching is not working. If I do manual search for each episode then that episode is snatched. I'm using Torrenday,IPTorrents and on both the same problem. 

My Log:  http://pastebin.com/35dqX357

**Comment by rafaelbiriba** [comment]
Automatic searching and snatching is not working. If I do manual search for each episode then that episode is snatched

**Comment by fernandog** [comment]
please open new issue and as always follow guidelines. plain text of info wont help us see the problem with your setup (probaly)
