### ISSUE TITLE
Backlog Overview filters

### ISSUE THREAD

**Issue by kingfenix** [SiCKRAGETV/sickrage-issues#990]
Could some form of checkboxes/filters be added to turn off/on various types of files in the backlog overview?

For example, I only want to see needed files, not low quality ones...it makes the list much longer than I need it to be.

Thanks

**Comment by fernandog** [comment]
low quality is a backlog isn't? SR is still try to find high quality. Unless you check "archive first match" then SR won't try to get higher quality and that eps won't appear in backlog overview

**Comment by kingfenix** [comment]
well it only started showing me the yellow highlighted items in one of the recent updates...it never used to do it. All of a sudden now I have a two page long backlog mostly with yellow I cant remove...

**Comment by fernandog** [comment]
@kingfenix do you want SR searching for the high quality?

**Comment by kingfenix** [comment]
no I prefer just the normal HDTV releases and lower file sizes

**Comment by fernandog** [comment]
so you must check quality settings from all that shows. If you only want HDTV, set the same quality for "Initial" and "Archive" qualities

**Comment by kingfenix** [comment]
ok let me go find out where/how to do that...thanks

**Comment by kingfenix** [comment]
ok I went to EDIT on two shows...SD was chosen for quality, and archive was unchecked. I checked archive on both shows, saved and then did a re-scan on both....both shows still show up yellow in backlog?

**Comment by kingfenix** [comment]
I do notice that the shows appearing yellow, instead of having the red SD beside the episode, it has a grey rectangle saying unknown....

**Comment by fernandog** [comment]
@kingfenix check your naming pattern in PP. you should add quality to the name, otherwise SR can't tell the quality

https://sickrage.tv/forums/forum/main-category/main-forum/20090-wanted-quality-hd-downloaded-hd-but-status-downloaded-unknown

**Comment by kingfenix** [comment]
lol, now see instead of all this....if I could just tell the backlog page I dont want it to report quality stuff I wouldnt need to do this....

**Comment by kingfenix** [comment]
and if I need to have the quality in the name...why doesnt that hit all episodes?

for example I have a season of 2 broke girls...all episodes but 2 have the red SD and do not appear in backlog, but two single episodes have grey unknowns and appear in that backlog

**Comment by fernandog** [comment]
@kingfenix your setup is wrong. you need to fix it.

you have an alternative that is enable for all shows "Archive on First Match"
https://github.com/SiCKRAGETV/SickRage/wiki/Quality-Settings#custom-qualities

**Comment by kingfenix** [comment]
I get that and I will, but why does this affect only 2 shows out of 14 in a season? all files are .mp4 and named SxxExx - Title.mp4

**Comment by fernandog** [comment]
@kingfenix because there is no quality information in the filename

**Comment by kingfenix** [comment]
yes but all 14 files are named the same and it got the quality SD on 12 of them, only two it did not...either way...fixing it now
