### ISSUE TITLE
UNC Path for Root Directory

### ISSUE THREAD

**Issue by saitoh183** [SiCKRAGETV/sickrage-issues#992]
Is it possible to have?

**Comment by fernandog** [comment]
@saitoh183 fully explain please

**Comment by saitoh183** [comment]
My media is stored on my Storage Server and SR is on my app server. In order to add my Media root directory, i had to create a map drive. I did not see the possibility to add a network path (UNC). Also if i run SR as a service using my Administrator account as user, I was not able to see the map drive in my choices of Root Directories. 

With being able to use UNC path, if we reinstall our server or move the SR installation to a new machine, we dont have to worry about re-creating the map-drive or juggling map-drive letters if the letter is already taken.

**Comment by TagForce** [comment]
@saitoh183 @fernandog Python has very little support for unc paths. There is a library that provides unc support, but it would require a lot of changes in SR since none of the functions take unc paths into account. It's probably easier to find a solution for mounting them when starting the service.

**Comment by abeloin** [comment]
@saitoh183 You can use UNC, but it's unsupported as it is not cross-platform.

To use mapped drive and sickrage as a service you need to run the service as the user who has the mapped drive.

**Comment by saitoh183** [comment]
@abeloin 

That is what i did yet i could not see them....i will give it a go again

**Comment by TagForce** [comment]
@saitoh183 set the SR service as delayed start, and make sure the drives get mapped at startup for that user.
