### ISSUE TITLE
Subtitle Issue: wrong chars in filename and subtitles packed with gz

### ISSUE THREAD

**Issue by saitoh183** [SiCKRAGETV/sickrage-issues#994]
I dont know what is happening but my subtitle download is doing some odd this. Here is a snippet of a entry from the log:
>2015-03-18 14:06:00 DEBUG    FINDSUBTITLES :: STATUS IS 104
2015-03-18 14:06:00 DEBUG    FINDSUBTITLES :: 248841: Saving episode details to database
2015-03-18 14:05:52 DEBUG    FINDSUBTITLES :: 248841: Downloading subtitles for episode 4x15
2015-03-18 14:05:52 DEBUG    FINDSUBTITLES :: Setter sets location to D:\TV\Scandal (2012)\Season 4\Scandal (2012) - 4x15 - The Testimony of Diego Muñoz.mp4
2015-03-18 14:05:52 DEBUG    FINDSUBTITLES :: 248841: Loading episode details from DB for episode 4x15
2015-03-18 14:05:52 DEBUG    FINDSUBTITLES :: 248841: An object for episode 4x15 didn't exist in the cache, trying to create it
2015-03-18 14:05:52 DEBUG    FINDSUBTITLES :: Downloading subtitles for episode 4x15 of show Scandal (2012)

Here is what i find:

In my SickRage folder
![image](https://cloud.githubusercontent.com/assets/1534197/6717213/6c1f0e9a-cd81-11e4-8d75-b15b4e3469e4.png)

In my Show folder...no sub

![image](https://cloud.githubusercontent.com/assets/1534197/6717252/9f454168-cd81-11e4-910a-9cf1faa378b0.png)

Also notice the gz extension file...what are those...?

Link to my post on forum https://sickrage.tv/forums/forum/main-category/main-forum/20345-subtitles-in-sickrage-folder-filename-lang-srt-gz

**Comment by abeloin** [comment]
Please read on how to submit an issue:
Ref: https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md

Here is the important required information from that page:
(DO NOT POST ANYTHING THAT CONTAINS YOUR LOGIN INFORMATION OR API KEY)
Please include the following when opening a new ticket:

    Branch
    Commit hash
    Your operating system and python version
    What you did
    What happened
    What you expected
    Link to a copy/paste of your logfile with clear debug info of the error on PASTEBIN

**Comment by saitoh183** [comment]
Branch :  (master) 
Commit hash : cc4896e96a27dda5cc9ed198209aa514bf68a4eb
Windows  2012 STD R2 / python 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
What you did:  Explained above
Here is my current subtitle settings:

![image](https://cloud.githubusercontent.com/assets/1534197/6723208/de30669e-cdba-11e4-89be-9f563c33495d.png)


What happened : Explained above
What you expected : Saved srt into show folder and not create gz files (dont know if that is a by-product of the other problem or a separate issue)

Logs: i dont anything besides what i post since the logs have already overwritten. But i will post more next time it does it. But what settings should i set the logs to pick the proper data to post?

**Comment by fernandog** [comment]
@saitoh183 open CMD and run `chcp` - post result

**Comment by saitoh183** [comment]
I run it using the VBS file i found on htpcguides.

`Set WshShell = CreateObject("WScript.Shell")
WshShell.Run chr(34) & "E:\SickRage\SickBeard.py" & Chr(34), 0
Set WshShell = Nothing`

chcp: Active code page: 850

**Comment by fernandog** [comment]
@saitoh183 try this: before running SR, run this: `chcp 65001` 
try to reproduce the error

**Comment by saitoh183** [comment]
@fernandog 

Is this for both issues or 1 of the 2?

**Comment by fernandog** [comment]
@saitoh183 Subtitle strange chars

**Comment by abeloin** [comment]
@saitoh183 Any logs?

**Comment by saitoh183** [comment]
@abeloin 

Doing test right now...just did chcp change mentioned by fernandog

**Comment by saitoh183** [comment]
Ok...chcp didnt change anything for the strange characters

![image](https://cloud.githubusercontent.com/assets/1534197/6724048/626da000-cdc7-11e4-8923-ceb67ee52388.png)

![image](https://cloud.githubusercontent.com/assets/1534197/6724106/19856c5a-cdc8-11e4-884f-b32761f8bffa.png)

![image](https://cloud.githubusercontent.com/assets/1534197/6724119/3f1dfa86-cdc8-11e4-9e4c-d94f2cabeda3.png)


log: http://pastebin.com/mmFu0pNz

relevant lines i think are 7711 - 7720

**Comment by fernandog** [comment]
@saitoh183 there is nothing in the log about the .gz files

**Comment by saitoh183** [comment]
@fernandog 

I will try again later on. I will start SR wait a few minutes for startup scans to be done...clear log, do a sub seatch and post log

**Comment by fernandog** [comment]
Delete that subtitle with .gz and the one with bad chars and force to redownlosd

**Comment by saitoh183** [comment]
@fernandog 

Ok...delete all the gz everywhere or only the series i will use for the test

**Comment by fernandog** [comment]
@saitoh183 any news?

**Comment by saitoh183** [comment]
@fernandog in the process of doing it right now...will post in a few minutes

Going to clear logs first

**Comment by saitoh183** [comment]
@fernandog Im having a bit of trouble capturing logs. What would be the best way to go about it in or to capture the log at the right moment? There doesnt seem to be any indicator to when SR finishes try ing to find a subtitle. And clear log seems to only be for the errors and not the log itself. Can i just delete the log files without restarting SR in roder to not have all the start stuff in the log?

**Comment by fernandog** [comment]
Are you changing log level in viewlog?

**Comment by saitoh183** [comment]
Yes...Changed it to Debug

**Comment by saitoh183** [comment]
@fernandog All i saw in the log that talked about subtitles was 

2015-03-20 10:49:01 DEBUG    Thread-56 :: 164541: No subtitles downloaded for episode 5x8
2015-03-20 10:49:01 DEBUG    Thread-56 :: STATUS IS 104
2015-03-20 10:49:01 DEBUG    Thread-56 :: 164541: Saving episode details to database
2015-03-20 10:48:51 DEBUG    Thread-56 :: 164541: Downloading subtitles for episode 5x8

and it still saved file in my SR folder with weird characters

**Comment by fernandog** [comment]
Search for Hawaii Five

**Comment by saitoh183** [comment]
I did it and i comes up with nothing relevant...just a big list off all shows...I tried heart of dixie and gives a similar result to the log above. When i do a search for "Heart", the log level changes to DB and this cannot be edited.

Log:

http://pastebin.com/DXVRe0Bg

**Comment by fernandog** [comment]
@saitoh183 you must delete the contents of search field to reset log search

use the LogFilter and filter: FINDSUBTITLES

**Comment by saitoh183** [comment]
@fernandog I did that and nothing there.The only way i see anything subtitle related is setting it to DB/Debug and  filter by thread. I just noticed that it seems all the files that are failing and being added to the SR folder have special characters. Hannibal for example, most eps have accent on a letter...all those failed to download sub and when i try them, they are sent to the SR folder. Eps with apostrophe also seem to be affected. I tried Marco Polo (2014) - 1x10 - The Heavenly and Primal and it worked just fine (saved in right location)

http://pastebin.com/ZjK6sHm2

**Comment by fernandog** [comment]
@saitoh183 Post full contents of your /config page

**Comment by saitoh183** [comment]
SR Version:	BRANCH: (master) / COMMIT: (cc4896e96a27dda5cc9ed198209aa514bf68a4eb) 
SR User:	Administrator
SR Locale:	('en_CA', 'cp1252')
SR Config file:	E:\SickRage\config.ini
SR Database file:	E:\SickRage\sickbeard.db
SR Cache Dir:	E:\SickRage\cache
SR Arguments:	[]
SR Web Root:	
Python Version:	2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]

**Comment by fernandog** [comment]
@saitoh183 stop SR. run CMD as admin and run:

chcp 65001

then enter sickrage folder and run:
python SickBeard.py

Post results of /config

**Comment by saitoh183** [comment]
SR Version:	BRANCH: (master) / COMMIT: (cc4896e96a27dda5cc9ed198209aa514bf68a4eb) 
SR User:	Administrator
SR Locale:	('en_CA', 'cp1252')
SR Config file:	E:\SickRage\config.ini
SR Database file:	E:\SickRage\sickbeard.db
SR Cache Dir:	E:\SickRage\cache
SR Arguments:	[]
SR Web Root:	
Python Version:	2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]

**Comment by fernandog** [comment]
If you run chcp 65001 it should appear 

SR Locale: ('en_CA', 'cp65001')

**Comment by saitoh183** [comment]
i checked the chcp and it was set to 850 again. So i stopped everything again and ran the command from admin cmd and from the same console navigated to my SR folder and started it and it still says the same thing in config and when i type chcp it showed 65001 just before i started SR via tha same console. If i close and re-open the CMD it is back to 850, is that normal?

**Comment by fernandog** [comment]
@abeloin any ideias?

**Comment by abeloin** [comment]
@saitoh183 It's normal, chcp change the currently active code page in the currently running process only. It doesn't change it system wide. So the change(chcp 65001) must be included in your vbs.

**Comment by fernandog** [comment]
@abeloin he runned manual: chcp 65001 and python SickBeard.py but the new locale didn't appeared in /config

**Comment by abeloin** [comment]
@saitoh183 You did this?
```
chcp 65001
cd c:\sickrage
c:\python27\python.exe SickBeard.py --nolaunch
```

**Comment by saitoh183** [comment]
yes minus the --nolaunch since i have it set to not run browser already

```chcp 65001
cd e:\sickrage
python sickbeard.py```

I can try again if you like

**Comment by fernandog** [comment]
@saitoh183 please do

**Comment by saitoh183** [comment]
https://drive.google.com/file/d/0B-nxnSB-4zQ4bXhfbU9ZNVdDVmM/view?usp=sharing

**Comment by fernandog** [comment]
@saitoh183 contents of /config please

**Comment by saitoh183** [comment]
@fernandog 

its on the video.

SR Version:	BRANCH: (master) / COMMIT: (cc4896e96a27dda5cc9ed198209aa514bf68a4eb) 
SR User:	Administrator
SR Locale:	('en_CA', 'cp1252')
SR Config file:	E:\SickRage\config.ini
SR Database file:	E:\SickRage\sickbeard.db
SR Cache Dir:	E:\SickRage\cache
SR Arguments:	[]
SR Web Root:	
Python Version:	2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]

**Comment by fernandog** [comment]
@saitoh183 I don't know why cp65001 don't know in /config.

after running chcp 65001, and delete local subtitles, and try to download them again, does is appear with bad chars too?

**Comment by saitoh183** [comment]
yes and in the sickrage folder

**Comment by fernandog** [comment]
@saitoh183 I really don't know what's wrong. you are the only user reporting this

**Comment by saitoh183** [comment]
@fernandog 

sigh...could it be because i used Git for Windows to install or cuz im on Server 2012 R2 STD. I hope its not because of my DB..i wouldnt want to have to re-populate it...took very long to sort out the different settings for the shows and then wait a few hours for the import to finish. Should i be running on chcp 65001?

**Comment by fernandog** [comment]
@saitoh183 you can try install SR in **ANOTHER** folder. and add just that show and try to find subtitles

**Comment by abeloin** [comment]
@saitoh183 It's not db related

**Comment by saitoh183** [comment]
@fernandog 

I will try that 

@abeloin 

If moving SR to my other server works, would it be complicated to move my DB over . The TV path isnt the same since the storage server is the local machine for my TV shows. Is the same drive letter as my map drive an my map drive but it has a extra folder (D:\videos\TV instead of D:\TV). Can i just change the path in SR and it would update my TV shows or does this have to be done directly in the  DB?

**Comment by abeloin** [comment]
@fernandog I'm now in Windows, and I can confirm @saitoh183 issue:

SR Version: 	BRANCH: (develop) / COMMIT: (d15e9e0bb698b02be5202a5b4255b69e02566e59)
SR User:	Alexandre
SR Locale:	('fr_CA', 'cp1252')
SR Config file:	D:\SickRage\config.ini
SR Database file:	D:\SickRage\sickbeard.db
SR Cache Dir:	D:\SickRage\cache
SR Arguments:	['--nolaunch']

**Comment by abeloin** [comment]
@saitoh183 Can you apply this patch in reverse? 

https://github.com/SiCKRAGETV/SickRage/pull/1540.diff

`patch -p1 -R < 1540.diff `

Stop sickrage first

**Comment by abeloin** [comment]
Try it on my system and it fix the issue.

**Comment by abeloin** [comment]
@saitoh183 Created a PR fixing the issue can you try it?

**Comment by saitoh183** [comment]
@abeloin 

Just got home...will try it in a few minutes

**Comment by saitoh183** [comment]
SR Version:	BRANCH: (master) / COMMIT: (cc4896e96a27dda5cc9ed198209aa514bf68a4eb) 
SR User:	Administrator
SR Locale:	('en_CA', 'cp1252')
SR Config file:	E:\SickRage\config.ini
SR Database file:	E:\SickRage\sickbeard.db
SR Cache Dir:	E:\SickRage\cache
SR Arguments:	[]
SR Web Root:	
Python Version:	2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]

started manually like we did before but i can confirm subtitles that were failing before are now working

**Comment by saitoh183** [comment]
do i need to add the change of the chpc to my vbs?

**Comment by fernandog** [comment]
@saitoh183 yes

**Comment by fernandog** [comment]
@abeloin what don't let SR run or give a ERROR if we detect that user is running windows and didn't run chcp 65001 before run sickrage?

**Comment by saitoh183** [comment]
since i just copied the vbs...how so i modify it?

Set WshShell = CreateObject("WScript.Shell")
WshShell.Run chr(34) & "E:\SickRage\SickBeard.py" & Chr(34), 0
Set WshShell = Nothing

**Comment by fernandog** [comment]
chr(34) is the same as "
you are running the command using double quotes in the end and in the beginning

Set WshShell = CreateObject("WScript.Shell")
WshShell.Run chr(34) & "chcp 64001" & Chr(34), 0
WshShell.Run chr(34) & "E:\SickRage\SickBeard.py" & Chr(34), 0
Set WshShell = Nothing

**Comment by saitoh183** [comment]
@fernandog 

Thank you ..but isnt it 65001?..im guessing typo :)

@abeloin Thank you

**Comment by fernandog** [comment]
yes

**Comment by saitoh183** [comment]
![image](https://cloud.githubusercontent.com/assets/1534197/6763189/3cc476a8-cf48-11e4-9db2-0d7bfc1e850e.png)

**Comment by fernandog** [comment]
@saitoh183 is the file still there?

**Comment by saitoh183** [comment]
@fernandog 

which file?

The error is when i add the line for chcp...comment it out and the vbs works

**Comment by fernandog** [comment]
@saitoh183 so I don't know how to add it. sorry

**Comment by saitoh183** [comment]
@fernandog 

No worries i will figure it out :)

**Comment by abeloin** [comment]
@saitoh183 Put the 2 commands in a batch file

**Comment by saitoh183** [comment]
@abeloin 

Ok..will try that

**Comment by abeloin** [comment]
PR merge in master please update
