### ISSUE TITLE
[Feature Request] Only Post-Process if video has subtitle associated

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#996]
@TagForce it's the inverse of sync files. This is why I still don't use SR PP.
I have my own script that downloads subtitles. It downloads subtitle with/without language in the file name ([release].por.srt or [release].srt)
Too complicated?

**Comment by TagForce** [comment]
@fernandog I think it could be done. Not now, though. Other things have priority.

**Comment by fernandog** [comment]
No problem at all. thanks

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
