### ISSUE TITLE
Can't enable subtitle in mass update

### ISSUE THREAD

**Issue by Symbiot78** [SiCKRAGETV/sickrage-issues#997]
hi

Sickrage running on debian (open media vault)
BRANCH: (master) / COMMIT: (cc4896e96a27dda5cc9ed198209aa514bf68a4eb) 

I've enabled subtitles plugin and selected 2 languages.
I haven't changed anything else in the subtitle page.

When I do a manual search for subtitles SR reports that all my episodes have both subtitles available (which I know isn't right)

When I do a "mass update" the subtitles column tick boxes are all greyed out.

it looks like SB somehow thinks all episodes have all the subs needed. which is false.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/668

**Comment by fernandog** [comment]
@Symbiot78 

not an issue

```
		#if not $curShow.subtitles or $sickbeard.showQueueScheduler.action.isBeingSubtitled($curShow) or $sickbeard.showQueueScheduler.action.isInSubtitleQueue($curShow):
			#set $curSubtitle_disabled = "disabled=\"disabled\" "
```

if:
show don't have subtitle enabled OR
subtitle is queue to download OR
subtitle is being downloaded
then
you'll see the checkbox "disabled"

**Comment by Hellowlol** [comment]
This is not a bug, but i do think its bad design, the checkfield should be checked if curshow.subtitles, else unchecked. This way a user can edit this asap.

**Comment by fernandog** [comment]
@Hellowlol to fix this we should disable the check "not $curShow.subtitles". But we must keep the others otherwise user can't disable subtitles while subtitle search is running

**Comment by Hellowlol** [comment]
Fine by me, i dont carr as long as i can enable it.

**Comment by fernandog** [comment]
@Symbiot78 

please stop SR
edit /SickRage/gui/slick/interfaces/default/manage.tmpl
clear contents
paste this one:
https://raw.githubusercontent.com/fernandog/SickRage/enable_subtitle_mass_edit/gui/slick/interfaces/default/manage.tmpl

save
start SR
test it please

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1592

**Comment by fernandog** [comment]
@Symbiot78 @Hellowlol 

We found out that the "subtitle" column its misplaced. It should be a indicator (with x or v) like anime/sports and etc
mass update for subtitles should be done selecting the shows you want to enable subtitle and click "edit"
then select "enable/disable" subtitle

is that ok? or you want to change your FR to enable in the main page?

**Comment by Hellowlol** [comment]
I disagree there is no reason why it should be a x or v column at all. there should only be checkboxes on for everything so mass edit actually is mass edit not "mass edit some stuff just display some other"

**Comment by Symbiot78** [comment]
I Always used it as a mass-search for subtitles.. Have I completely misunderstood?

Sent from Outlook




On Thu, Mar 19, 2015 at 11:15 AM -0700, "Hellowlol" <notifications@github.com> wrote:
I disagree there is no reason why it should be a x or v column at all. there should only be checkboxes on for everything so mass edit actually is mass edit not "mass edit some stuff just display some other"

---

**Comment by fernandog** [comment]
@Symbiot78 mass search it's the correct function.

@neoatomic @markheloking @TagForce do you used this mass update/edit with subtitles?

**Comment by Symbiot78** [comment]
For me the explanation is fine. If the checkboxes work as answered above :-)
