### ISSUE TITLE
SickRage crash on Startup (after update)

### ISSUE THREAD

**Issue by sr-gi** [SiCKRAGETV/sickrage-issues#998]
Hi everyone, 

I'm unable to start SickRage after updating it a few hours ago (Master branch).

The last line in the SickRage log is:

Restarting SickRage with ['/usr/bin/python2', '/opt/sickrage/SickBeard.py', '--nolaunch']

If I try to restart the service, or start it again, it crashes. Also, if I try to start it manually using the same command used in the log:

```
pi@raspberrypi /opt/sickrage $ python2 ../SickBeard.py --nolaunch

Traceback (most recent call last):
  File "SickBeard.py", line 69, in <module>
    import sickbeard
  File "/opt/sickrage/sickbeard/__init__.py", line 35, in <module>
    from github import Github
  File "/opt/sickrage/lib/github/__init__.py", line 36, in <module>
    from MainClass import Github
  File "/opt/sickrage/lib/github/MainClass.py", line 31, in <module>
    from Requester import Requester
  File "/opt/sickrage/lib/github/Requester.py", line 36, in <module>
    import httplib
  File "/usr/lib/python2.7/httplib.py", line 79, in <module>
    import mimetools
  File "/usr/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/usr/lib/python2.7/tempfile.py", line 34, in <module>
    from random import Random as _Random
MemoryError
```
Any idea?

Thank you.

**Comment by fernandog** [comment]
@sr-gi try restarting you Pi. Looks like you are out of memory.

**Comment by sr-gi** [comment]
@fernandog if tried several times but it still doesn't work.

**Comment by fernandog** [comment]
@sr-gi 
do you have other services running? 
what is your /boot/config.txt settings? 
512MB or 256MB pi ?

**Comment by sr-gi** [comment]
There's only sickrage and transmission running.
The /boot/config.txt is set with the default values.
The Pi is the 512 MB version.

Also, top command returns that the Pi is using only about a 10% of memory.

**Comment by fernandog** [comment]
@abeloin can you confirm - or not - that is a memory issue?

**Comment by abeloin** [comment]
From https://docs.python.org/2/library/exceptions.html#exceptions.MemoryError
```
exception MemoryError

    Raised when an operation runs out of memory but the situation may still be rescued (by deleting some objects). The associated value is a string indicating what kind of (internal) operation ran out of memory. Note that because of the underlying memory management architecture (C’s malloc() function), the interpreter may not always be able to completely recover from this situation; it nevertheless raises an exception so that a stack traceback can be printed, in case a run-away program was the cause.
```
It's suing to much memory, maybe add a swap space?

**Comment by sr-gi** [comment]
I've tried to add an additional 512 MB of memory as a swap space, but python still crashes.

**Comment by abeloin** [comment]
Can you try a `git reset --hard`?

**Comment by abeloin** [comment]
If it doesn't work, try git bisect(stop sickrage first and go to sickrage folder):
```
$ git bisect start
$ git bisect bad
$ git bisect good v4.0.11
```
* git will then tell tell you `Bisecting: x revisions left to test after this`.
* Start sickrage manually `python SickBeard.py --nolaunch`
* Check if ok:
  * If ok, stop sickrage(Ctrl-C) and type: `git bisect good`
  * If not ok, stop sickrage(Ctrl-C) and type: `git bisect bad`
* Repeat until you see `is first bad commit` take note of the commit id.
* At the end `git bisect reset` to return to the HEAD revision.

See this documentation on how to bisect: http://git-scm.com/book/en/v2/Git-Tools-Debugging-with-Git

**Comment by sr-gi** [comment]
This is what I get:

48f42ad42eba1d85d8a12b9ca33b6147f9d24c0c is the first bad commit
commit 48f42ad42eba1d85d8a12b9ca33b6147f9d24c0c
Author: Fernando <fernandog@users.noreply.github.com>
Date:   Sat Mar 7 23:32:14 2015 -0300

    Try to fix invalid date

    OverflowError: mktime argument out of range

    https://github.com/SiCKRAGETV/sickrage-issues/issues/883

:040000 040000 ee149173eb65f422bdffde26162dea7f92a2a323 d601e01a8773f390351c21674f0b6514fc0f13ef M      gui

**Comment by fernandog** [comment]
@sr-gi what I did wrong?! =)

**Comment by sr-gi** [comment]
By the way, it seems like in some way SR is started when I try to start the service. 

service sickrage status returns: sickrage start/running with a different pid each time. 

This is some how related to the fact that yesterday I saw a python2 process changing It's pid each second, but I don't know if it's the normal behaviour.

**Comment by fernandog** [comment]
@sr-gi you should have only one python for SickBeard.py. unless you are running couchpotato or another service.

**Comment by sr-gi** [comment]
@fernandog I have only one, but It changes it's pid constantly. It should be like this?

**Comment by fernandog** [comment]
@sr-gi this is my top command.

your PID column is changing?! are you sure? how frequent?

![1](https://cloud.githubusercontent.com/assets/2620870/6762821/1a23100c-cf46-11e4-8c87-ae73bfb114ba.png)

run this and report back results
```
clear && mes= date | cut -d " " -f2 && sudo grep "$mes .* Out of memory" /var/log/syslog
```

**Comment by sr-gi** [comment]
Those are two different snapshots, with more or less 5 secs of delay.

![image](https://cloud.githubusercontent.com/assets/6665628/6762876/d226ff66-cf68-11e4-98ce-4853cdc86e50.png)

![image](https://cloud.githubusercontent.com/assets/6665628/6762880/dcf0d098-cf68-11e4-80e8-adeeca9f27db.png)

The process only appears either if I start it manually (with service start), or the reboot the Pi. If I try to do it via python SickBeard.py --nolauch, it crash with the error posted above.

**Comment by fernandog** [comment]
@sr-gi disable sickrage at startup, restart pi, start SR manually

**Comment by sr-gi** [comment]
I've deleted sickrage.conf from /etc/init, reboot the pi, and try to start SR manually with python SickBeard.py --nolaunch.

Same error :(

**Comment by fernandog** [comment]
Please run:

python --version

and

clear && mes= date | cut -d " " -f2 && sudo grep "$mes .* Out of memory" /var/log/syslog

**Comment by sr-gi** [comment]
pi@raspberrypi /opt/sickrage $ python --version
Python 2.7.3
pi@raspberrypi /opt/sickrage $ clear && mes= date | cut -d " " -f2 && sudo grep "$mes .* Out of memory" /var/log/syslog
Mar

**Comment by fernandog** [comment]
@abeloin do you know what is that python2 in top?

**Comment by TagForce** [comment]
@fernandog that's python. It changes its PID because its set to restart on an error. Each time it starts it will crash with a memoryerror, exits with an errorcode other than 0, and gets restarted, causing a new pid.

**Comment by abeloin** [comment]
@sr-gi Try reverting the bad commit:

Download: https://github.com/abeloin/SickRage/commit/48f42ad42eba1d85d8a12b9ca33b6147f9d24c0c.diff

`patch -p1 -R < 48f42ad42eba1d85d8a12b9ca33b6147f9d24c0c.diff` in sickrage folder

**Comment by sr-gi** [comment]
I've done it and I tried to start SR manually again, but it still crashes.

I'm thinking about trying a clean Raspbian installation in another SD and see if it works.

**Comment by sr-gi** [comment]
I've installed a clean raspbian distro and configured all again. It seems to work fine. Thanks everyone for the support.
